### ISSUE TITLE
Include a "custom" sort option in new bookmarks sidebar

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#34776]
## Description 

Many of the people who have lots of bookmarks are usually meticulous about the way they are ordered/organized. The new bookmarks side panel offers more options for sorting your bookmarks — which is great for everyday users (since initially the only way to sort was by name). But this change means that those users with thousands of bookmarks now lose that meticulous organization when opening the bookmarks sidebar, since it defaults to one of the pre-defined sorting options.

This can be understandably frustrating for those users. I suggest we include a "custom" (name pending) sort option for the bookmarks sidebar, so that users can still organize their bookmarks there to display exactly the way they want them and not be limited to the pre-defined sort order.  

Will also use this issue to track users "affected" by this:
https://community.brave.com/t/i-am-not-satisfied-with-the-side-bookmarks-ordering-options-in-the-newest-version/519956

**Comment by simonhong** [comment]
Upstream issue - https://bugs.chromium.org/p/chromium/issues/detail?id=1444154

**Comment by Brave-Matt** [comment]
Additional feedback:
https://community.brave.com/t/bookmarks-sidebar-downgrade/520368/11

**Comment by kjozwiak** [comment]
The above requires `1.63.139` or higher for `1.63.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.63.141 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | aa92f6cecec7f6c576bd1cf120f4cf359d770159
OS | Windows 11 Version 23H2 (Build 22631.3085)
```

Installed 1.63.141
launched Brave
visited few websites (eg. cnn.com, brave.com)
Added few bookmarks and organized into folders
opened bookmarks side panel and clicked `Custom order`
verified the order of the bookmarks match to bookmarks bar, brave://bookmarks, hamburger > bookmarks menu



Open bookmarks side panel and set Custom order sort filter
Open any folder in side panel and check items order is same with bookmakrs bar or bookmarks page


All bookmarks 

bookmarks sidepanel | bookmarks bar | bookmarks flyout menu | brave://bookmarks
----- | ---- | ----- | -----
<img width="258" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/4359ab0c-17ae-4c6e-82f0-ad15c49e6aec">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/68a9e601-0fd2-49d2-b426-38fbb7cc32d4">|<img width="258" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/ac41bc36-fb7e-4010-b21c-7f0eb5d5023f">|<img width="258" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/3a00f63c-6205-4fa8-ad83-8408f4e942c3">

specific folder

bookmarks sidepanel | bookmarks bar | bookmarks flyout menu | brave://bookmarks
------- | ---------- | ---------- | ---------  
![image](https://github.com/brave/brave-browser/assets/98358127/a56eb83a-83de-4cfe-ac2a-da1a4b8865ed)|![image](https://github.com/brave/brave-browser/assets/98358127/fd3e405e-8801-4693-bdc6-2e7ef531ae6f)|![image](https://github.com/brave/brave-browser/assets/98358127/86626dcf-496e-4aa7-bd5b-5c9917b0cab7)|![image](https://github.com/brave/brave-browser/assets/98358127/35e1ea4b-acaf-43e8-82ee-b6df6e2c0941)|![image](https://github.com/brave/brave-browser/assets/98358127/415ef92f-045e-48e8-9a0a-51192fbaee6c)|![image](https://github.com/brave/brave-browser/assets/98358127/3ee463a1-b98f-4316-80e0-c0f5b183dccb)|![image](https://github.com/brave/brave-browser/assets/98358127/3df034f6-1a49-4b83-95a7-b36b9e330eed)|![image](https://github.com/brave/brave-browser/assets/98358127/e731b7ef-c638-4788-9ed4-3cd332af6cd1)
