### ISSUE TITLE
Remove 0.25 BAT minimum for Rewards BAT contributions

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#34780]
## Description

With vBAT sunsetted, we are no longer constrained by a minimum denomination of 0.25 BAT.

```[tasklist]
### Tasks
- [ ] Make new minimum 0.002 BAT.
```

![image](https://github.com/brave/brave-browser/assets/11497541/77196f48-36ac-4f89-8100-a8e9d5269c40)

**Comment by zenparsing** [comment]
@Miyayes Do we want the minimum to be 0.002 instead, in order to better support the 5% fee? (The fee for the minimum case would then be 0.0001 BAT.)

**Comment by zenparsing** [comment]
Also, for small BAT values, the fiat display will be zero (since we round to 2 decimal places). Is that acceptable?

**Comment by Miyayes** [comment]
@zenparsing 0.002 sounds fine. Good consideration.

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.63.146 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | cb9ee9c98182a64716e4237bf1202f1aec3bcff8
OS | Windows 10 Version 22H2 (Build 19045.3930)
```
