### ISSUE TITLE
[Commander]: Enable Quick Commands by default

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#34781]
We should enable commander by default in Nightly and decide if we want it to ride the trains!

## Test Plan

1. Pressing Ctrl+Space should trigger the commander
2. Commands should be sorted by frecency (i.e. using a command should make it rank higher) as well as the match
3. Commands should be clickable
4. Commands should be selectable with the keyboard
5. Commands should be translated
6. Commands should do what they say on the tin
7. It should be possible to change the shortcut for opening the commander (chrome://settings/system/shortcuts), under Quick Commands

**Comment by fallaciousreasoning** [comment]
cc @rebron

**Comment by fallaciousreasoning** [comment]
@rebron @bsclifton should this be marked release-notes/include

**Comment by bsclifton** [comment]
@fallaciousreasoning yes please! You might ping @LaurenWags or @kjozwiak to come up with a descriptive title. You can check https://github.com/brave/brave-browser/blob/master/CHANGELOG_DESKTOP.md to see previous features being added and what naming convention it uses

I would go with something like `Added Command Palette to omnibox when person presses Ctrl + Space`.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.63.41 Chromium: 120.0.6099.115 (Official Build) nightly (64-bit)
-- | --
Revision | c56c5ba04606284792201770bb6cb52d1ef367b6
OS | Windows 11 Version 22H2 (Build 22621.2861)
```

1. Installed 1.63.41
2. launched Brave
3. pressed Ctrl + Space to open Commander 
4. confirmed list of commands shown in the omnibox
5. clicked on `About Brave` 
6. confirmed `About Brave` (brave://settings/help) page opened as expected. 
7. clicked `Add all tabs to new group` 
8. confirmed above command is sorted and ranked higher 
9. confirmed able to add new command to Omnibox (New window - Ctrl + N)
10. added a new quick command `Ctrl + Alt + Space` in `brave://settings/system/shortcuts`
11. confirmed `Commander` opened with the new quick command `Ctrl + Alt + Space`
12. Able to reset to original quick command `Ctrl + Alt + Space`


step 3 | step 6 | step 8 | step 9 | step 10 | step 11 | step 12
---- | ---- | ---- | ---- | ---- | ---- | ----
<img width="951" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b368c0d7-d0be-4c36-9029-62e71f8f6167">|<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/56f53ccf-ce0c-4e53-b63e-eb346942047f">|<img width="942" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/58b0d783-f881-4bd5-9a8e-d91d046045fe">|<img width="949" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2e314d56-6b13-4904-b13b-0bde56ca886a">|<img width="950" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6f772fae-478a-4a53-ab67-a6d0cbafe3f9">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/14ccc1a8-498f-49d5-9534-e76b30d2eb30">|<img width="951" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b931916c-cb10-4072-85cd-86a9f605dc19">

**Comment by ppcamp** [comment]
Hey Guys, I know this is a bit odd, but can you guide me were should I go to see the API/specs for this feature? I just discovered it by accident, and I thought it would be pretty cool if we are able to use it in some extension development. 

> I do know that Edge used to have something like this, but was dropped some time ago.

**Comment by fallaciousreasoning** [comment]
Unfortunately, there's not really an API exposed to extensions for this - it'd be cool to add something but it probably wouldn't be that useful as Brave extensions are normally installed via the Chrome store, so they couldn't really use this API :/

If you're interesting in adding your own commands, we'd be happy to accept a PR (or if you open an issue with the commands you think would be useful we can take a look, but might be a while!)

**Comment by ppcamp** [comment]
@fallaciousreasoning got it. Yeah, for now I don't have much insights on this, so when I got some time I'll definitely take a look on it.

My idea was to have something similar to `vscode command palette`. At first sight, my idea was to allow me to type console commands directly without the need to open the console and then, type it
`F12 ctrl+p`. Doing so, we could run snippets more easily, instead of `F12 ctrl+p ! snippet name`, we could just do something like, `:>!snippet`. 

But not only that, if we have some API for this, we could increase the shortcuts functionality by using extensions. So for example, we could have another one that would search using regex in the current page.

Anyway, thanks for the response!

**Comment by fallaciousreasoning** [comment]
Yeah, sounds like a great idea - I wonder if we could get most of the way there with `bookmarklets`?

This is my super hacky demo 😆 

https://github.com/user-attachments/assets/9ba5bf20-bb17-4059-8447-4e83d3a304f5

I added another shortcut for bookmarks like this:
![Image](https://github.com/user-attachments/assets/de449c6e-985d-411c-a495-46d977d7fed7)

so if you press
<kbd>Ctrl</kbd>+<kbd>L</kbd>, <kbd>!</kbd>, `<snippet>`

it'll run your snippet!

https://github.com/user-attachments/assets/ea564665-3f64-4843-a197-8b4bf01906ea

As you can clearly see, `Jay's Dark Mode` is the perfect dark mode, and is optimized for all sites 😆 

(but this was a pretty fun - cool to see how you can join together a bunch of handy browser features)

**Comment by ppcamp** [comment]
For sure, that's the best dark mode I ever saw LoL 😆. Jokings a side, that's a good workaround for this behavior, I'll give it a try.

Thanks again!
