### ISSUE TITLE
BraveBrowserNightlySetup.exe and BraveBrowserNightlySetup32.exe can't be installed behind proxy

### ISSUE THREAD

**Issue by gerroon** [brave/brave-browser#34789]
## Description 

Not providing the zip folders for the Windows is a big mistake because these executables can't be installed in internet restricted environments. I am behind proxy and I am unable to install. 

Setting up a system-wide proxy so I can install the browser is a big security and privacy problem. I can access internet through running Brave because I am using proxy extension.

## Steps to Reproduce

Dowload BraveBrowserNightlySetup.exe 
Disable your internet
Try to install it

**Comment by rebron** [comment]
@gerroon .zip versions are available as well as standalone and standalone silent versions of our .exes. 
https://github.com/brave/brave-browser/releases/tag/v1.61.101
and https://github.com/brave/brave-browser/releases/tag/v1.60.125
