### ISSUE TITLE
chrome.declarativeNetRequest.updateDynamicRules 

### ISSUE THREAD

**Issue by Sp0kzz** [brave/brave-browser#34799]
When are you gonna fix the issue where all extensions that have this in the worker.js/background.js need to be restarted every time the browser is launched ? it's been months and still no fix ?? 
https://github.com/brave/brave-browser/issues/30854

i think this should be prioritized over some shitty ai assistant and more bloat added every update

**Comment by rebron** [comment]
Closing as dupe of https://github.com/brave/brave-browser/issues/30854. Can follow progress in that issue unless a different follow-up issue is created.
