### ISSUE TITLE
Global shields settings 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#348]
![image](https://user-images.githubusercontent.com/17010094/41445294-95e06d92-7016-11e8-9991-b01d0acd7b72.png)

Should also provide an option to clear all saved site settings. Currently settings changed in shields can't be cleared and just show up as a read only option under global settings. 

May be related to #232 

cc: @bradleyrichter

**Comment by bsclifton** [comment]
Implemented with https://github.com/brave/brave-browser/pull/1100
<img width="720" alt="screen shot 2018-10-30 at 1 01 09 pm" src="https://user-images.githubusercontent.com/4733304/47747097-c2ddc200-dc44-11e8-929f-fc37fef06819.png">

We do have an issue to restyle this content, which is captured with https://github.com/brave/brave-browser/issues/606
