### ISSUE TITLE
Incorrect exclude count displayed in a-c table

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3480]
## Description 

Found while testing #3476
Incorrect exclude count displayed in a-c table

## Steps to Reproduce

   1. Clean profile 0.61.36
   2.  Enable rewards
   3.  Open DDG and add it to a-c table
   4. Click on `Include in Auto-Contribute` switch multiple times
   5. Observe that exclude count shows up incorrect count 
   6. Click on `Include in Auto-Contribute` switch multiple times when the switch is turned off
   7. Observe that exclude count shows up incorrect count 

## Actual result:

The message displayed after step 5:
`Total number of sites you excluded from Auto-Contribute: 34(Restore All)`

The message displayed after step 7:
`Total number of sites you excluded from Auto-Contribute: 4294967286 (Restore All)`

![issue with a-c table exclude sites](https://user-images.githubusercontent.com/38657976/53345482-061e1800-393b-11e9-817e-9a7b05cdfd63.gif)

## Expected result:
exclude could should be displayed correctly

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.61.36 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 10 OS Build 17134.523

### Reproducible on current release: No
- Does it reproduce on brave-browser dev/beta builds? Beta

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information

@brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
https://github.com/brave/brave-browser/issues/3476#issuecomment-467033829

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.47 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1782
Used test plan from the description.

Including and excluding sites through Brave Panel works without problems.
There is still a problem when including and excluding sites through `brave://rewards/`. Logged https://github.com/brave/brave-browser/issues/3610
