### ISSUE TITLE
Shields onboarding highlight should time out

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#34802]
## Description 

Shields onboarding added with https://github.com/brave/brave-browser/issues/27490 doesn't seem to have any timeout.

It would be nice if it went away on its own after a bit rather than a user needing to click on shields to dismiss it.

## Steps to Reproduce

   1. Clean profile on Nightly.
   2. Visit a site where things will be blocked
   3. See shields onboarding

## Actual result:

The below doesn't time out
<img width="466" alt="Screenshot 2023-12-08 at 2 02 14 PM" src="https://github.com/brave/brave-browser/assets/28145373/cb1f52d2-c7aa-4671-a3b6-211a2a5e09cd">

## Expected result:

should time out

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.63.26 Chromium: 120.0.6099.71 (Official Build) nightly (x86_64)
-- | --
Revision | 2a6e297bd394f70bf15a195fba3b007f54317995
OS | macOS Version 13.6.1 (Build 22G313)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes 1.63.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron

**Comment by stephendonner** [comment]
Maybe only if we detect **_active_** users, rather than _**idle**_ ones?  Just thinking of a use-case where the user is pulled away from screen, returns later, misses notification.

**Comment by rebron** [comment]
cc: @aguscruiz @simonhong

**Comment by simonhong** [comment]
Another option is making it activated bubble after some times passed.
For now, that bubble is launched with in-activate bubble.
So, it's not dismissed by itself till it gets activated and de-activated or user clicks shields button.
If we make it activated bubble at some point, it'll be gone when user clicks any area outside of that bubble.

**Comment by LaurenWags** [comment]
clicking outside of the bubble to dismiss it would be great too 😄

**Comment by aguscruiz** [comment]
+1 to clicking outside to dismiss

**Comment by simonhong** [comment]
I realized that making bubble activate after some times passed have a severe drawback.
It steals user's current focus as bubble gets activated.
I think closing with timer is more proper option.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.63.101 Chromium: 120.0.6099.199 (Official Build) nightly (64-bit)
-- | --
Revision | 8d3f0a563e185b6a763cc8e210ab24775dfb9047
OS | Windows 11 Version 22H2 (Build 22621.2861)
```

1. Installed 1.63.101
2. launched Brave
3. visited Washingtonpost.com in a new tab
4. waited until Shields onboarding bubble (~1sec) appears
5. not clicked in the bubble 

#### Confirmed the bubble auto dismissed at about 15s 

https://github.com/brave/brave-browser/assets/98358127/7065f26c-a931-4549-b1f8-38200949f769
