### ISSUE TITLE
[Brave News]: Notify user when feed has new data

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#34819]
There should be update notifications when:
1. The feed gets new data
2. The sources for the feed change

From this notification, it should be possible to refresh the feed :D

**Comment by kjozwiak** [comment]
The above requires `1.62.115` or higher for `1.62.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | 41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6
OS | Windows 10 Version 22H2 (Build 19045.3803)

```
