### ISSUE TITLE
Using Brave on old MacBookPro

### ISSUE THREAD

**Issue by angelog0** [brave/brave-browser#34812]
I have a MacBookPro early 2011 on which macOS 10.13.6 is the last version I can use and there is installed as default browser Brave 1.57.64. 

Now, each time I start Brave it flags it is outdated and that I have to reinstall it. ALL THIS IS VERY ANNOYING.

So I am here to ask if I can avoid this, what I have to remove/change in `Brave Browser.app` tree to avoid this, if there is some service I have to remove and HOW, or what else I can do to continue to use Brave on this MBP.

I will wait a bit then I will remove Brave in favor of [Chromium legacy](https://github.com/blueboxd/chromium-legacy) which still supports this MBP, or have you a similar project for Brave?

**Comment by meguroyama** [comment]
I'd like to see a screenshot of the issue also your OS is quite old (latest update `November 12, 2020`) and as far as I'm aware the warning is baked-in for Chromium.

**Comment by angelog0** [comment]
> your OS is quite old 

@meguroyama, as maybe you know, Apple decided that these old MBP are to be thrown away and I cannot upgrade the OS anymore. This MBP is perfectly functional. 

Attached the screenshot you requested.

> the warning is baked-in for Chromium.

It does not shows up in the above Chromium Legacy.

Is there a similar project for Brave?

![brave_to_be_reinstalled-annoying](https://github.com/brave/brave-browser/assets/35931460/5e5ee97c-c3c6-4a24-a19d-9ed68fe69e77)

**Comment by bsclifton** [comment]
Hi there - you should be able to hide this via group policy
```
defaults write com.brave.Browser SuppressUnsupportedOSWarning -bool true
```

Here's an example thread that shows the equivalent on Windows. I had to look up the macOS group policy syntax
https://www.reddit.com/r/chrome/comments/z9ay1h/how_do_i_disable_the_to_get_future_google_chrome/

Please try that @angelog0 and let us know. Thanks!

**Comment by angelog0** [comment]
@bsclifton wrote:

> defaults write com.brave.Browser SuppressUnsupportedOSWarning -bool true

> Please try that @angelog0 and let us know. Thanks!

The window (see the above screenshot) "Impossibile aggiornare Brave" is still there... It is that window which is annoying....

**Comment by angelog0** [comment]
.. and the 2-dots (lines) menu contains "Aggiorna" But I cannot upgrade. I would just a simple Brave window...
