### ISSUE TITLE
leo side panel is not persisted after reboot

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#34817]
## Steps to Reproduce

   1. Launch Brave and open leo side panel
   2. Close leo side panel and relaunch
   3. Open side panel with shortcut (ctrl + b)

## Actual result:

Leo is not opened. Instead, previously used global panel is opened.

## Expected result:
Leo is opened

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```

.

```


example | example | example
----------|-----------|----------

**Comment by LaurenWags** [comment]
changed to `release-notes/exclude` per discussion with @rebron
