### ISSUE TITLE
One time tip shows incorrect message on banner

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3481]
## Description 

One time tip shows incorrect message on banner

## Steps to Reproduce

   1. Clean profile 0.61.36
   2. Open DDG
   3. Send one-time tips to DDG
   4. Verify banner message after tipping - message displayed as expected
   5. Send monthly tips to DDG
   6. Verify banner message after tipping - message displayed as expected
   7. Send one-time tips to DDG
   8. Verify banner message - shows up monthly tip message which is not correct.

## Actual result:

One time tip shows incorrect message on banner

## Expected result:
One-time tips message should be displayed instead of monthly

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.61.36 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 10 OS Build 17134.523

### Reproducible on current release: NO
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional Information

@brave/legacy_qa

**Comment by btlechowski** [comment]
Reproduced on

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

**Comment by kjozwiak** [comment]
Reproducible on `macOS 10.14.3 x64` using the following build:

Brave | 0.61.38 Chromium: 73.0.3683.39 (Official Build) beta(64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Mac OS X

**Comment by GeetaSarvadnya** [comment]
Verification passed on


rave | 0.61.48 Chromium: 73.0.3683.56 (Official Build) beta (64-bit)
-- | --
Revision | 303af44e2f2948869279f120021c778855d76ead-refs/branch-heads/3683@{#653}
OS | Windows 10 OS Build 17134.523

- Verified the STR mentioned in the description
