### ISSUE TITLE
The "Extensions" tab in private window with Tor makes all Brave's windows crash

### ISSUE THREAD

**Issue by Drago-ir** [brave/brave-browser#34811]
## Description 
In a private window with Tor if you go to "Customize and control Brave" (the three horizontal lines top right) then click on "Extensions" all Brave's windows will shutdown. Even the windows in normal mode or in simple private mode.

## Steps to Reproduce
   1. Open a private window with Tor
   2. Click on "Customize and control Brave" (the three horizontal lines top right) 
   3. Click on "Extensions" tab

## Actual result:
All Brave's windows close

## Expected result:
1. Do not close all windows
2. Show "Extensions" parameters

## Reproduces how often: 
Every time

## Brave version (brave://version info) 
Brave	1.61.101 Chromium: 120.0.6099.71 (Official Build) (64-bit) 
Revision	a2125180c183a2b5775b45c2138fda37d240b773
OS	Linux

Same problem on Windows 11
Brave	1.61.101 Chromium: 120.0.6099.71 (Official Build) (64-bit) 
Revision	a2125180c183a2b5775b45c2138fda37d240b773
OS	Windows 11 Version 23H2 (Build 22631.2793)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? : No
- Does the issue resolve itself when disabling Brave Rewards? : No
- Is the issue reproducible on the latest version of Chrome?

**Comment by MadhaviSeelam** [comment]
Reproduced the issue in 
```
Brave | 1.61.101 Chromium: 120.0.6099.71 (Official Build) (64-bit)
-- | --
Revision | a2125180c183a2b5775b45c2138fda37d240b773
OS | Windows 11 Version 22H2 (Build 22621.2715)
```

```
Status: | Uploaded
Uploaded Crash Report ID: | b2110c00-8bde-260b-0000-000000000000
Upload Time: | Monday, December 11, 2023 at 2:06:28 PM
```

```
(std::__Cr::__tree<std::__Cr::__value_type<safety_hub::SafetyHubModuleType,std::__Cr::unique_ptr<SafetyHubModuleInfoElement,std::__Cr::default_delete<SafetyHubModuleInfoElement> > >,std::__Cr::__map_value_compare<safety_hub::SafetyHubModuleType,std::__Cr::__value_type<safety_hub::SafetyHubModuleType,std::__Cr::unique_ptr<SafetyHubModuleInfoElement,std::__Cr::default_delete<SafetyHubModuleInfoElement> > >,std::__Cr::less<safety_hub::SafetyHubModuleType>,1>,std::__Cr::allocator<std::__Cr::__value_type<safety_hub::SafetyHubModuleType,std::__Cr::unique_ptr<SafetyHubModuleInfoElement,std::__Cr::default_delete<SafetyHubModuleInfoElement> > > > >::begin)
```

**Comment by diracdeltas** [comment]
cc @boocmp could you take a look here?

**Comment by simonhong** [comment]
I'm checking now. It's not related with tor. It's reproduced with private widow also.

**Comment by LaurenWags** [comment]
Removed `OS/Linux` as @MadhaviSeelam reproduced with Windows

**Comment by kjozwiak** [comment]
The above requires `1.61.104` or higher for `1.61.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.61.101 Chromium: 120.0.6099.71 (Official Build) (64-bit)
-- | --
Revision | a2125180c183a2b5775b45c2138fda37d240b773
OS | Windows 10 Version 22H2 (Build 19045.3693)
```
Reproduced the issue on `1.61.10`

- Confirmed that click on `Extensions` menu option via 3 dot menu or Hamburger menu via `Private Tab` doesn't crash Brave in `1.61.101`
- Confirmed that click on `Extensions` menu option via 3 dot menu or Hamburger menu via `Private window with Tor tab` doesn't crash Brave in `1.61.101`

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.61.104 Chromium: 120.0.6099.115 (Official Build) (x86_64)
-- | --
Revision | 38497f14ca9ff6f1d5b9c1d72f61fec6f0efcf1d
OS | macOS Version 13.6.1 (Build 22G313)
```

**Comment by btlechowski** [comment]
Verified with

Brave | 1.61.104 Chromium: 120.0.6099.115 (Official Build) (64-bit)
-- | --
Revision | 38497f14ca9ff6f1d5b9c1d72f61fec6f0efcf1d
OS | Linux


Using STR from description and `1.61.101 Chromium: 120.0.6099.71`, reproduced the crash with both Private and Private with Tor windows.

Using STR from description and `1.61.104 Chromium: 120.0.6099.115`,
- Confirmed that clicking on "Extensions" menu option via hamburger menu via Private window doesn't crash
- Confirmed that clicking on "Extensions" menu option via hamburger menu via Private window with Tor doesn't crash
