### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Sp0kzz** [brave/brave-browser#34816]
## Description 
Browser crashes whenever i click "cookies and site data" from the button next to the URL.

## Steps to Reproduce

![IdCei2Po4f](https://github.com/brave/brave-browser/assets/58868692/67b85a3d-7bc7-419a-b3cc-fd5f05fea969)

   1. click icon next to url
   2. click "cookies and site data"
   3. browser crashes

## Actual result:
CRASH

## Expected result:
NO CRASH

## Reproduces how often: 
every time i click "cookies and site data"

## Brave version (brave://version info)
latest "stable" version [Version 1.61.101]

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  
- NO
- Does the issue resolve itself when disabling Brave Rewards? 
- NO
- Is the issue reproducible on the latest version of Chrome? 
- NO

tried disabling all extensions, resetting all brave://flags settings, nothing fixed it.
it was working fine on previous version.

**Comment by goodov** [comment]
https://github.com/brave/brave-browser/issues/34833
