### ISSUE TITLE
Update Wiki document for Pagegraph

### ISSUE THREAD

**Issue by L3thal14** [brave/brave-browser#34815]
Some of the references to the files in the codebase are outdated due to restructuring. I also believe the documentation could include a lot more information regarding the graph output which consists of in-depth information regarding properties for each node and edge type so that its easier to get started. For example, the wiki mentions `privacy-relevant Web API accesses` being recorded but does not contain the actual list of web APIs recorded by default. I stumbled upon the [types.rs#L77](https://github.com/brave/pagegraph-rust/blob/ffc2101b22b5a3be4f8d06d1d151e9aef1d806c9/pagegraph/src/types.rs#L77) file in the `pagegraph-rust` repository which led me to [interface.py#32](https://github.com/brave/brave-core/blob/5756da92b47887ea483dd6207dc4c7a134a305c5/chromium_src/third_party/blink/renderer/bindings/scripts/bind_gen/interface.py#L32). 

I believe the comments in [types.rs](https://github.com/brave/pagegraph-rust/blob/ffc2101b22b5a3be4f8d06d1d151e9aef1d806c9/pagegraph/src/types.rs) are detailed enough to be included in the documentation. 

@pes10k

**Comment by pes10k** [comment]
yep, absolutely, the pagegraph-rust docs are the best place to look for understanding the structure of the output graph.  I've updated the wiki to better explain where folks can find documentation for the graphs' structure, and how they can request more information as the documentation is further fleshed out.

I've also added an explicit link to the [interface.py](https://github.com/brave/brave-core/blob/master/chromium_src/third_party/blink/renderer/bindings/scripts/bind_gen/interface.py#L32) file that indicates which Web APIs are instrumented.

I'm going to close this issue for the time being, but please add more comments or follow up if you think further changes would be helpful for finding existing documentation.
