### ISSUE TITLE
Crash Report (Crash while accessing cookies and site data)

### ISSUE THREAD

**Issue by 13Groszy** [brave/brave-browser#34822]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.101 Chromium: 120.0.6099.71
Operating System: Mac OS X 14.1.2

URL (if applicable) where crash occurred:
Every single page. Github, google, personal, private, other person profile too.

Can you reproduce this crash?
Every single time it works this same. Crash on every click.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Click settings in url input.
2. Click 'Cookies and site data'
3. See browser crash.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/aee90a00-8bde-260b-0000-000000000000

**Comment by goodov** [comment]
https://github.com/brave/brave-browser/issues/34833
