### ISSUE TITLE
Add a maximum width to Leo's content in the panel

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#34823]
We need to control the maximum width the conversation in the panel can grow to.
I'm thinking about using the same width as I have planned for the full page view, which is 680px and content centered

https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Leo-MVP?type=design&node-id=5680%3A80838&mode=design&t=x4zty0HjDPHJ6Wer-1

![image](https://github.com/brave/brave-browser/assets/15734630/5b132d22-7d4f-4ea1-a934-d30cc69f6ae0)

![image](https://github.com/brave/brave-browser/assets/15734630/ef240d49-b1d3-4f8b-adbf-27ef0a4259bd)

![image](https://github.com/brave/brave-browser/assets/15734630/2b12c4bf-0f37-47c9-bedb-60ab9433c7f7)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.69.101 Chromium: 127.0.6533.43 (Official Build) nightly (x86_64)
-- | --
Revision | 9073515479afc03ab66a21bb8175263fc56ba1f1
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.69.101`
2. launched Brave using `--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev`
3. loaded `https://www.theverge.com/2024/7/12/24197065/samsung-galaxy-fold-flip-airpods-vergecast`
4. opened `Leo` in the sidebar
5. using the pane-divider widget, gave `Leo` the maximum-available horizontal space
6. compared with `1.68.117`

### Confirmed `Leo`'s content pane has tighter horizontal width constraints

`1.68.117` | `1.69.101`
-----------|---------
<img width="2029" alt="Screen Shot 2024-07-12 at 4 35 06 PM" src="https://github.com/user-attachments/assets/cc54fef1-e0df-4f43-9dc3-8504692c1333"> | <img width="2002" alt="Screen Shot 2024-07-12 at 4 35 20 PM" src="https://github.com/user-attachments/assets/0f49b6dc-8c1b-4faa-ba5a-1eef77952bec">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.69.101 Chromium: 127.0.6533.43 (Official Build) nightly (64-bit)
-- | --
Revision | 9073515479afc03ab66a21bb8175263fc56ba1f1
OS | Windows 10 Version 22H2 (Build 19045.4651)
```

`1.68.117` | `1.69.101`
-----------|-----------
![image](https://github.com/user-attachments/assets/8e315039-7839-4c96-b9a0-e3d577c1730e) | ![image](https://github.com/user-attachments/assets/50c9d16b-0a00-48fc-bf92-dddd40ab9c5e)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave	1.69.101 Chromium: 127.0.6533.43 (Official Build) nightly (64-bit) 
Revision	9073515479afc03ab66a21bb8175263fc56ba1f1
OS	Linux
```

`1.68.118` | `1.69.101`
-----------|---------
<img width="2032" alt="Screen Shot 2024-07-12 at 5 10 32 PM" src="https://github.com/user-attachments/assets/0dd53dda-7d93-48e9-b583-b9997a7f0c39"> | <img width="2032" alt="Screen Shot 2024-07-12 at 5 06 10 PM" src="https://github.com/user-attachments/assets/2809abaf-1e2c-465f-b04f-f5bc437d69d9">
