### ISSUE TITLE
[Brave News]: Some channels are missing translations

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#34828]
We've added a few new channels in the backend, which don't have translations in the frontend.
- `Celebrity News`
- `Sport` (I think this channel should be renamed to `Sports` to match the existing channel)
- `Education`
- `Lifestyle`

@aguscruiz any chance of getting some icons for the new categories?

cc @mattmcalister @LorenzoMinto to confirm these channels are intentional.

There are also a number of similar channels:

- Entertainment/Entertainment news/Film & TV/Celebrity News
- Tech news/Tech reviews/Technology
- Top news/Top sources/World news (these might be intentional)
- `Sport`/`Sports`

**Comment by LorenzoMinto** [comment]
Yes, this is related to https://github.com/brave/news-aggregator/issues/680, which we've been delaying to figure out the best and less disruptive way forward. One question: will we have to handle the channel migration on the client if we update a channel name? I.e. I'm subscribed to `Sport`, but now the channel called `Sports`. I guess my question is around how we represent the channel subscription on the client

**Comment by fallaciousreasoning** [comment]
Do you think it's better to add these translations for now?

**Comment by ioc2e3** [comment]
> 您認為現在添加這些翻譯是否更好？

At least it's better than no translation ...

At least ...

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.66.83 Chromium: 124.0.6367.60 (Build oficial) beta (64 bits)
-- | --
Revisión | 05e51102638aec2f59c93a45527d6840c17cb704
Sistema operativo | Windows 10 Version 22H2 (Build 19045.4291)
```

### `Spanish`

### `German`

### `...`
