### ISSUE TITLE
Prevent flashing elements during wallet initializations

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34824]
## Description 

Add a default background color to the main HTML element and show a loading indicator while the wallet initializes. 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

https://github.com/brave/brave-browser/assets/30185185/cb9cf111-4941-4208-9b9c-a67d7ad14f42

## Expected result:
When using dark-mode, the screen should not flash white when loading the wallet. The default wallet banner should not attempt to render until needed.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from issue description
- Verified with dark theme, reloading portfolio doesn't show white flash 

https://github.com/brave/brave-browser/assets/17010094/027f39bd-f91b-4939-9f21-176ce720574d
