### ISSUE TITLE
Back doesn't work on wallet recovery screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#34838]
## Description 

Back doesnt work on wallet reocvery screen

## Steps to Reproduce

   1. Initiate wallet backup from anywhere onboarding/banner/menu
   2. Go to `brave://wallet/crypto/backup-wallet/backup-recovery-phrase`
   3. Click on the Back button, doesn't navigate
   4. Click on the navigation button at top, goes back to `brave://wallet/crypto/backup-wallet/explain-recovery-phrase`

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/da80cef4-76a5-4fdf-977c-8eb1e0df278b

## Expected result:
Should be able to navigate back

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.62.105 Chromium: 120.0.6099.71 (Official Build) beta (64-bit)
-- | --
Revision | f72c783bcd52110d026061575b4bef28ccb547f7
OS | Windows 11 Version 23H2 (Build 22631.2715)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @josheleonard

**Comment by josheleonard** [comment]
@srirambv, This issue is now fixed in Nightly via this PR: [Feat: add wallet onboarding network selection step](https://github.com/brave/brave-core/pull/21088#top)

**Comment by josheleonard** [comment]
@srirambv, I could not replicate this on the latest master branch


https://github.com/brave/brave-browser/assets/30185185/649ab5f6-f2e0-43e4-8513-391f18b67aa2

**Comment by srirambv** [comment]
Issue not reproducible any more. Closing as stale

https://github.com/brave/brave-browser/assets/17010094/9ccfdac1-8ce5-41a5-ae77-6f0d7bd4c28f
