### ISSUE TITLE
`Signature verification error` throw in wallet standard signTransaction method

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#34842]
Seeing this error in console when trying to mint https://magiceden.io/launchpad/ryder_one.
This error would be happen when calling signTransaction with partial signed legacy Solana transaction(s).

**Comment by yrliou** [comment]
wallet standard fix in https://github.com/brave/wallet-standard-brave/pull/39

**Comment by kjozwiak** [comment]
The above requires `1.61.104` or higher for `1.61.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.61.104 Chromium: 120.0.6099.115 (Official Build) (64-bit)
-- | --
Revision | 38497f14ca9ff6f1d5b9c1d72f61fec6f0efcf1d
OS | Windows 11 Version 23H2 (Build 22631.2715)

- Verified steps from [brave/brave-core#21343](https://github.com/brave/brave-core/pull/21343)
- Verified able to mint NFT on `https://magiceden.io/launchpad/ryder_one`, [transaction hash](https://solscan.io/tx/4YD9jQXKGyiAM4kDtvHVbMLmjqkE3wLRv9SCSZ6evVmoBnGeK3d5kEEZ4n4UrEiXr1kH3JbvJYDddjwWM8yGkuQP)
- Verified able to `Sign message` using Devnet on `https://solana-labs.github.io/wallet-adapter/example/`

---------

Verification passed on Google Pixel 8 with Android 14 running 1.61.104 x64 build

- Verified steps from [brave/brave-core#21343](https://github.com/brave/brave-core/pull/21343)
- Verified able to mint NFT on `https://magiceden.io/launchpad/ryder_one`, [transaction hash](https://solscan.io/tx/4b6GRNtmcRXyara6EmvkJjPEu2rM8ctQYxpmrSnF33AyUKTQHxRhTkXVHCTv6noBhhGKvgVear4DoxE8K3LyGv6s)
- Verified able to `Sign message` using Devnet on `https://solana-labs.github.io/wallet-adapter/example/`
