### ISSUE TITLE
NTP background proper image sizing is not applied - follow up to #33998

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#34845]
## Description 

New tab page background image sizing is incorrect. Should be sized properly to fit new tab page window.

Originally logged with https://github.com/brave/brave-browser/issues/33998.

## Steps to Reproduce

   1. Launch clean profile 1.62.x
   2. Resize window (or not, seems I don't need to)
   3. Open some new tabs, notice NTP background image isn't sized properly

## Actual result:

Example | Example
--- | ---
<img width="1560" alt="Screenshot 2023-12-12 at 12 22 16 PM" src="https://github.com/brave/brave-browser/assets/28145373/16733949-c3a2-4189-85d0-8152481f48d9"> | <img width="1555" alt="Screenshot 2023-12-12 at 12 22 28 PM" src="https://github.com/brave/brave-browser/assets/28145373/5e0c5d8a-a509-491a-93b8-5822d2225ccf">

## Expected result:

Images should be sized properly

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.62.105 Chromium: 120.0.6099.71 (Official Build) beta (x86_64)
-- | --
Revision | f72c783bcd52110d026061575b4bef28ccb547f7
OS | macOS Version 13.6.1 (Build 22G313)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? 1.62.x yes
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron  @fallaciousreasoning @brave/qa-team

**Comment by stephendonner** [comment]
In addition to the above, I also reproduced images (sponsored and regular) not appearing on a new-tab page until you scroll down ever-so-slightly

```
Brave | 1.62.105 Chromium: 120.0.6099.71 (Official Build) beta (x86_64)
-- | --
Revision | f72c783bcd52110d026061575b4bef28ccb547f7
OS | macOS Version 11.7.10 (Build 20G1427)
```


example | example
---------|---------
<img width="1905" alt="Screen Shot 2023-12-12 at 9 49 13 AM" src="https://github.com/brave/brave-browser/assets/387249/c0f258f9-a1af-4eed-90ef-e1e8b4939e85"> | <img width="1905" alt="Screen Shot 2023-12-12 at 9 49 20 AM" src="https://github.com/brave/brave-browser/assets/387249/462d2796-b940-4d82-b7e0-b1c1b9e47de8">

**Comment by fallaciousreasoning** [comment]
This should be fixed when https://github.com/brave/brave-core/pull/21329 is uplifted.

**Comment by kjozwiak** [comment]
Closing the above as it's most likely addressed/fixed by https://github.com/brave/brave-core/pull/21295. Will be uplifted into `1.62.x` via https://github.com/brave/brave-core/pull/21329.

**Comment by kjozwiak** [comment]
The above requires `1.62.109` or higher for `1.62.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.62.110 Chromium: 120.0.6099.115 (Official Build) beta (x86_64)
-- | --
Revision | 4ddf185a65205df8535b2ab6e81b393bf0704309
OS | macOS Version 14.3 (Build 23D5033f)
```

### Confirmed new-tab page images -- both backgrounds and sponsored images -- render at their correct ratio.
 
example | example | example | example
---------|---------|----------|---------
<img width="1312" alt="Screenshot 2023-12-17 at 1 02 33 PM" src="https://github.com/brave/brave-browser/assets/387249/96b5814f-f216-4a24-b1bb-8319fcec3453"> | <img width="1312" alt="Screenshot 2023-12-17 at 12 58 13 PM" src="https://github.com/brave/brave-browser/assets/387249/4ebabef5-f1d0-418f-b308-ee1994cf933c"> | <img width="1312" alt="Screenshot 2023-12-17 at 12 58 20 PM" src="https://github.com/brave/brave-browser/assets/387249/130a1aa6-d9fd-4cb5-a71a-872f83cbd469"> | <img width="1312" alt="Screenshot 2023-12-17 at 12 58 39 PM" src="https://github.com/brave/brave-browser/assets/387249/ed2415fd-10f4-4eb4-af93-8f52f2273aeb">
