### ISSUE TITLE
[New Tab]: Custom backgrounds with a `(` or `)` don't get a backdrop in the new Brave News feed

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#34859]
## Steps to Reproduce

   1. Choose a custom background with a `)` in the name. I use 
![take (that)](https://github.com/brave/brave-browser/assets/7678024/e19d7088-09c7-4e46-9694-cfbf34591e9f)

   2. Scroll down to Brave News

## Actual result:
(using a different image)

![image](https://github.com/brave/brave-browser/assets/7678024/dfff3f05-cb7a-4937-83e6-c46967dae30f)

## Expected result:
![image](https://github.com/brave/brave-browser/assets/7678024/bc46dbf6-44a5-4a0c-937d-eb6f792fda5f)

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave. 1.63.42 Chromium: 120.0.6099.115 (Official Build) nightly (64-bit) 
Revision  170e1e58f272c95056d5b1e6f0680a6a401ae3e4
OS. Linux
```

### First, reproduced using `1.63.42`

example | example
---------|---------
<img width="1493" alt="Screen Shot 2023-12-14 at 2 11 53 PM" src="https://github.com/brave/brave-browser/assets/387249/bac0ad3f-645a-4f94-a66f-c6489802181b"> | <img width="1493" alt="Screen Shot 2023-12-14 at 2 11 59 PM" src="https://github.com/brave/brave-browser/assets/387249/1c40df12-eed5-4bc7-97cb-68012f0225ff">

### Steps:
1. installed `1.63.42`
2. launched Brave
3. chose supplied "snowy mountain" image and added a `)` to its name
4. opened a new-tab window
5. scrolled Brave News

## Confirmed the custom-chosen background isn't rendered in the `News` view

example | example | example
---------|----------|---------
<img width="1493" alt="Screen Shot 2023-12-14 at 2 13 45 PM" src="https://github.com/brave/brave-browser/assets/387249/1e166623-07c5-440c-9e4f-9db3a29acfbd"> | <img width="1493" alt="Screen Shot 2023-12-14 at 2 13 35 PM" src="https://github.com/brave/brave-browser/assets/387249/3c3a66da-e6dd-4593-98fa-3e2acc125e6d"> | <img width="1493" alt="Screen Shot 2023-12-14 at 2 13 52 PM" src="https://github.com/brave/brave-browser/assets/387249/fe454e4d-c38b-4e25-98fc-80c355827e4d">
