### ISSUE TITLE
Crash Report crash/088d0e00-8bde-260b-0000-000000000000

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#34855]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.62.105 Chromium: 120.0.6099.71
Operating System: Windows NT 10.0.22000

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Changing cookies in urlbar crashes
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/088d0e00-8bde-260b-0000-000000000000

**Comment by goodov** [comment]
same callstack as in https://github.com/brave/brave-browser/issues/34855, so it should be fixed.
