### ISSUE TITLE
challenge bypass ristretto crashes for windows x86

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#34854]
```
    core::panicking::panic_fmt [0x022F0073+3] (\src\third_party\rust-toolchain\lib\rustlib\src\rust\library\core\src\panicking.rs:54)
    core::panicking::panic [0x022F0068+56] (\src\third_party\rust-toolchain\lib\rustlib\src\rust\library\core\src\panicking.rs:127)
    block_buffer::BlockBuffer<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UTerm,typenum::bit::B1>,typenum::bit::B0>,typenum::bit [0x02859278+40] (\src\brave\third_party\rust\block_buffer\v0_9\crate\src\lib.rs:214)
    block_buffer::BlockBuffer<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UTerm,typenum::bit::B1>,typenum::bit::B0>,typenum::bit [0x02858B6C+44] (\src\brave\third_party\rust\block_buffer\v0_9\crate\src\lib.rs:55)
    sha2::sha512::Engine512::update [0x0285C8BC+92] (\src\brave\third_party\rust\sha2\v0_9\crate\src\sha512.rs:32)
    sha2::sha512::impl$3::update<ref$<generic_array::GenericArray<u8,typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UTerm,typenum::bit::B1>,typenum::bi [0x022F032A+26] (\src\brave\third_party\rust\sha2\v0_9\crate\src\sha512.rs:68)
    hmac::impl$3::finalize<sha2::sha512::Sha512> [0x022F0265+85] (\src\brave\third_party\rust\hmac\v0_10\crate\src\lib.rs:187)
    challenge_bypass_ristretto::oprf::VerificationKey::sign<hmac::Hmac<sha2::sha512::Sha512> > [0x022EABA3+131] (\src\brave\third_party\rust\challenge_bypass_ristretto\v1\crate\src\oprf.rs:517)
    challenge_bypass_ristretto_ffi::verification_key_sign_sha512 [0x02307041+97] (\src\brave\third_party\challenge_bypass_ristretto_ffi\src\lib.rs:268)
    challenge_bypass_ristretto::VerificationKey::sign [0x01A65AE9+41] (\src\brave\third_party\challenge_bypass_ristretto_ffi\src\wrapper.cc:253)
```

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x86` using the following build(s):

```
Brave | 1.61.106 Chromium: 120.0.6099.115 (Official Build) (32-bit)
-- | --
Revision | 57dbe1d28d3d06a4524c853d8c9e2684c8c24bcc
OS | Windows 10 Version 22H2 (Build 19045.3803)
```

* ensured that 1.61.106 Chromium: 120.0.6099.115` was installed without any issues/failures
* ensured that you restart/relaunch `1.61.106 Chromium: 120.0.6099.115` several times without any issues
* ensured that Griffin studies are pulled/applied after the second restart without any issues
  * checked `brave://version` and ensured that the studies are being listed
* loaded several popular websites (FB/YT/Gmail/LinkedIn) and ensured everything was loading without issues
  * ensured that you can login without any issues/passwords being saved via `brave://password-manager/passwords`
* ensured that you can join `Brave Rewards` without any issues/failures

```
[2392:8716:1215/175245.274:VERBOSE1:get_signed_tokens_url_request_util.cc(78)] Added 50 confirmation tokens, you now have 50 confirmation tokens
[2392:8716:1215/175245.274:VERBOSE1:account.cc(440)] Successfully refilled confirmation tokens
```

* ensured that you can login into a custodian without any issues (used `Uphold` in this case)
* ensured that `System Notifications` are working without any crashes (before joining Griffin and enabling client side notifications)
* ensured that `Client Side Notifications` are working without any crashes (after retrieving Griffin studies)
* ensured that viewing/clicking on `SNTP` worked without any issues/crashes
* ensured that viewing/clicking on ads via the `Brave News` feed worked without any issues/failures

**`System Notification`** |**`SNTP`** | **`SNTP`** | **`News Ad`** | **`News Ad`**| **`Now Earning`** | **`History`**
----------------------------|------------|-------------|----------------|----------------|----------------------|---------------
![image](https://github.com/brave/brave-browser/assets/2602313/889a9bc4-4d51-4a04-a1ed-d50589eba906) | ![image](https://github.com/brave/brave-browser/assets/2602313/f9a8c2d2-049b-4d2e-9988-568476701c8a) | ![image](https://github.com/brave/brave-browser/assets/2602313/418124d5-386c-4545-bf07-3f01958d5d86) | ![image](https://github.com/brave/brave-browser/assets/2602313/ef245475-8c0e-4b3b-b500-69c1bd84e986) | ![image](https://github.com/brave/brave-browser/assets/2602313/d8a6e90a-17f8-4056-a1a8-1bcc6411f209) | ![image](https://github.com/brave/brave-browser/assets/2602313/b302d0ab-43e5-416c-85a1-003c66f82980) | ![image](https://github.com/brave/brave-browser/assets/2602313/b8513b8b-3053-4958-9f89-b94279134c36)
