### ISSUE TITLE
Profile button is located in the middle of toolbar buttons

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#34858]
## Description 

![image](https://github.com/brave/brave-browser/assets/6786187/3b6f3a4f-83a7-4f21-8136-b88cc62cebd7)

## Steps to Reproduce

   1. 
   2. 
   3. 

## Expected result:
It should be positioned before the app menu button

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not checked. Maybe same
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Only happens on linux

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave	1.63.42 Chromium: 120.0.6099.115 (Official Build) nightly (64-bit) 
Revision	170e1e58f272c95056d5b1e6f0680a6a401ae3e4
OS	Linux
```

### Reproduced easily using `1.62.107`

### Steps:
1. installed `1.63.42`
2. launched Brave
3. created a new profile
4. examined the position of the profile's avatar

### Confirmed the profile avatar is just to the left of the "hamburger" menu

`1.62.107` | `1.63.42`
---------|----------
<img width="1392" alt="Screen Shot 2023-12-14 at 11 36 29 AM" src="https://github.com/brave/brave-browser/assets/387249/3c90c0ca-8aff-4e20-a3ff-2169a57ada4a"> | <img width="1392" alt="Screen Shot 2023-12-14 at 11 43 52 AM" src="https://github.com/brave/brave-browser/assets/387249/fe1aa142-4aa0-459d-baa4-beadb45231ec">
