### ISSUE TITLE
Wallet Panel Title should be Center Aligned

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#34851]
## Description 

The Wallet Panel `Title` is not center aligned

## Steps to Reproduce

   1. Go to a `DApp` and open the Wallet `Panel`
   2. The Panel `Title` is not center aligned

## Actual result:

![Screenshot 9](https://github.com/brave/brave-browser/assets/40611140/5e6b1708-0528-4390-b3df-703098db1011)

## Expected result:
The Panel `Title` should always maintain center alignment

![Screenshot 10](https://github.com/brave/brave-browser/assets/40611140/4d1125f6-9791-41d7-9346-a032e7e9a6ce)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.63.152 Chromium: 121.0.6167.164 (Official Build) beta (64-bit)
-- | --
Revision | 497ab49eab494dd35d416b3bab3eece99c27510d
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21348](https://github.com/brave/brave-core/pull/21348)
- Verified panel title is centre aligned when connected to DApps

Before | After
-- | --
![GHEoqQ1x33](https://github.com/brave/brave-browser/assets/17010094/b1fe9674-c351-420c-a8a3-637330413d1a) | ![yJ7sE4IYnP](https://github.com/brave/brave-browser/assets/17010094/2f585cca-a793-4a79-b9cc-fe8783eb5f81)
