### ISSUE TITLE
[Brave News]: FeedV2 Button Styling

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#34850]
FeedV2 buttons are currently hard to see using the default Nala theme. We should update them to be grey, as per Martin's new design:

1. Update the customize button
2. Update the refresh button
3. Update the call to action button on Advertisements

### Test Plan
The new buttons should be grey, instead of Blurple. Additionally, the refresh/customize button should be icon buttons now.

Also in this issue:
1. Make the scroll bar slightly less ugly when you're subscribed to a lot of feeds
2. Load images more eagerly (hard to test, but if images still load it should be working)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```

Brave | 1.63.41 Chromium: 120.0.6099.115 (Official Build) nightly (x86_64)
-- | --
Revision | c56c5ba04606284792201770bb6cb52d1ef367b6
OS | macOS Version 11.7.10 (Build 20G1427)


```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.63.41 Chromium: 120.0.6099.115 (Official Build) nightly (64-bit)
-- | --
Revision | c56c5ba04606284792201770bb6cb52d1ef367b6
OS | Windows 11 Version 22H2 (Build 22621.2861)
```

1. Installed 1.63.41
2. launched Brave
3. clicked on `Turn on Brave News` in the NTP 
4. scrolled down for Brave Technologist Podcast ad
5. confirmed `Customize` & `Refresh` buttons are updated to show as grey icon buttons
6. confirmed `Call to action` button on Advertisements are updated to show grey button
7. confirmed Scrollbar navigation is working as expected. 

**_Customize_** button

1.62.x | 16.3.x 
----- | -----
<img width="641" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/343b9635-3e59-4b10-90cb-6fc2fb88f035">| <img width="641" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c7778e4c-b113-49bb-9c77-a5318a66a5cb">

**_Refresh_**

1.62.x | 16.3.x 
----- | -----
<img width="641" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/343b9635-3e59-4b10-90cb-6fc2fb88f035">|<img width="641" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/5bbd02dd-6e13-478f-9450-a07ea05391c1">

**_Call to action button_**

1.62.x | 1.6.3.x 
----- | -----
<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/01486f32-dc51-4113-9c4c-6b5e955168fe">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/81ca8f87-33df-4fff-8070-26b56df91ece">

**_Scrollbar_**

`1.62.x | 1.63.x 
---- | ----
<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e7696d0b-2802-467f-af1a-06c7f2e76dad">|<img width="951" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/821d9bcc-8c92-4ee8-8cf8-1a437aff42b1">

**Comment by kjozwiak** [comment]
Removing the `QA Pass` label as the above will need to be rechecked using `1.62.x`. The above requires `1.62.116` or higher for `1.62.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.62.121 Chromium: 120.0.6099.144 (Official Build) beta (x86_64)
-- | --
Revision | ec4a006cb0f9a9d309ef78f6e11882e4bcf12c14
OS | macOS Version 14.3 (Build 23D5033f)
```


Customize
Refresh
Call to action
Scrollbar

**Comment by MadhaviSeelam** [comment]
Adding `QA/Test-All-Platforms` label due to new design changes.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | 41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6
OS | Windows 11 Version 22H2 (Build 22621.2861)
```


1. Installed 1.63.41
2. launched Brave
3. clicked on `Turn on Brave News` in the NTP 
4. scrolled down for Brave Technologist Podcast ad
5. confirmed `Customize` & `Refresh` buttons are updated to show as grey icon buttons
6. confirmed `Call to action` button on Advertisements are updated to show grey button
7. confirmed Scrollbar navigation is working as expected. 
8. confirmed images are loading as expected 

**_Customize_** | **_Refresh_** |**_Call to action_** | **_Scrollbar_**
------ | ------ | ------ | -----
<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/febe4d80-465a-4808-bb7b-2bc78719fd4d">|<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/52545c51-6314-47ea-a9e0-8c19f9dea2f7">|<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/28060531-9a28-4d9c-9542-b7777475fbd5">|<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/db5215cb-0fb6-45c3-a1b4-5bdb33257e2c">|

**Comment by stephendonner** [comment]
_Customize_ | _Refresh_ | _Call to action_  | _Scrollbar_
-----------|---------|---------------|----------
<img width="1791" alt="Screen Shot 2024-01-02 at 9 56 08 AM" src="https://github.com/brave/brave-browser/assets/387249/969d5660-89a6-48b2-a8fd-16ca9b9b11e3"> | <img width="1789" alt="Screen Shot 2024-01-02 at 9 58 16 AM" src="https://github.com/brave/brave-browser/assets/387249/67ca4284-6c4f-4532-a408-2c524021f0d8"> | <img width="1976" alt="Screen Shot 2024-01-02 at 10 00 04 AM" src="https://github.com/brave/brave-browser/assets/387249/62836696-8c93-481b-8dd9-e247497bc653"> | <img width="1904" alt="Screen Shot 2024-01-02 at 10 03 21 AM" src="https://github.com/brave/brave-browser/assets/387249/cd349731-7520-463b-9dbb-bfbbaecd5b79">
