### ISSUE TITLE
Add primary language P3A metric

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#34853]
Add a monthly P3A metric for the user's primary language:

What is your primary language?
`Brave.Core.PrimaryLang`

List of answers defined in `components/misc_metrics/language_metrics.cc`

Only available via STAR/Constellation.

cc @AndyAnds265

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | Windows 10 Version 22H2 (Build 19045.4046)
```
- Verified the tets plan from https://github.com/brave/brave-core/pull/21355
- Confirmed that the metrics `Brave.Core.PrimaryLang` is shown under `logs_constellation_prep_slow` and `constellation_logs_slow` blocks
- The metrics index value isn't matching with the browser language hence logged a follow up issue https://github.com/brave/brave-browser/issues/36529

Example | Example
----------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/f5f18dee-103f-4568-913c-06ea2ed66832) | ![image](https://github.com/brave/brave-browser/assets/38657976/b7e59e60-c169-49b6-8fbc-08300d2b2b30)

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.64.95
Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/21355#issue-2038798606
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the metrics `Brave.Core.PrimaryLang` is shown under `logs_constellation_prep_slow` block

---------------------------

|English|Russian|Spanish|Japanise|Hebrew|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/091fdbae-1d1a-4fc4-b471-bf3d388ac896) | ![2](https://github.com/brave/brave-browser/assets/128532965/3ee6584e-d9dc-4b85-9bcd-83f5c65e48ab) | ![3](https://github.com/brave/brave-browser/assets/128532965/ef8281e9-c907-4bf4-b524-374f7b412047) | ![4](https://github.com/brave/brave-browser/assets/128532965/a2008e0a-fa6b-4938-9429-365a60de6c57) | ![5](https://github.com/brave/brave-browser/assets/128532965/9a7297c4-b708-41b0-bee0-6cf004dc69a4) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/b5b6b8d9-ee57-4153-9879-e36b21d47bc3) | ![2](https://github.com/brave/brave-browser/assets/128532965/fba2eb0e-d78a-4bf5-8f5b-a2034ae05c01) | ![3](https://github.com/brave/brave-browser/assets/128532965/990555c2-cbc5-49d8-97ce-d5420aa134c7) | ![4](https://github.com/brave/brave-browser/assets/128532965/839b0e24-cbf8-47dd-832e-3d6977611ed2) | ![5](https://github.com/brave/brave-browser/assets/128532965/e3d212a6-5199-4674-bf5f-555b788cfc39) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/22f91fde-fc56-4f32-947c-11f3009577eb) | ![2](https://github.com/brave/brave-browser/assets/128532965/3c1936c0-a9bf-4489-b8f0-51b89df28b2b) | ![3](https://github.com/brave/brave-browser/assets/128532965/83bbfc77-9825-4d07-bd84-df923b4e2117) | ![4](https://github.com/brave/brave-browser/assets/128532965/b16bc582-473f-4e84-8162-de6fde0a75a8) | ![5](https://github.com/brave/brave-browser/assets/128532965/7d5dbd4a-43e1-43c9-9402-74a040702f8f) |
