### ISSUE TITLE
Remove global "selected asset" state

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34869]
## Description 

This state is no longer used. We should remove it.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21367](https://github.com/brave/brave-core/pull/21367)
- Verified Portfolio overview and portfolio asset details screen and price charts work as expected without any regression
- Verified hiding and unhiding tokens work as expected
