### ISSUE TITLE
[Speedreader] Wrong distillation state on navigation from the error page.

### ISSUE THREAD

**Issue by boocmp** [brave/brave-browser#34868]
## Steps to Reproduce

   1. Set 'Brave' as a default search engine.
   2. Enable Speedreader for all sites.
   3. Navigate to `http://http//phillywomenintech.com/2015/01/17/b-big-data-how-big-is-it-in-your-future/`, the error page should appear
   4. In the address bar type `Viki Boykis`

## Actual result:

The Brave search results are displayed in speedreader mode

## Expected result:

The Brave search results are displayed in normal mode

## Reproduces how often: 

Easily

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.63.73 Chromium: 120.0.6099.144 (Official Build) nightly (x86_64)
-- | --
Revision | db1fca96f43235a6d54b114a4dfc928a8cbeac95
OS | macOS Version 11.7.10 (Build 20G1427)
```
## Followed original steps to reproduce from https://github.com/brave/brave-browser/issues/34868#issue-2039141981

example | example | example
---------|----------|---------
<img width="1293" alt="Screen Shot 2023-12-27 at 10 01 36 AM" src="https://github.com/brave/brave-browser/assets/387249/33a4f159-f3b6-4e6d-b46b-f3b6c53bfb37"> | <img width="1293" alt="Screen Shot 2023-12-27 at 10 01 40 AM" src="https://github.com/brave/brave-browser/assets/387249/3cee10c0-7ddd-4774-aa98-d70c8e825d5d"> | <img width="1293" alt="Screen Shot 2023-12-27 at 10 01 43 AM" src="https://github.com/brave/brave-browser/assets/387249/442b620b-882f-4d60-a32b-ae965517e896">
