### ISSUE TITLE
Move "get sell asset url" to a cached query

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34870]
## Description 

Cache the results of the "sell" url for an asset

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21368](https://github.com/brave/brave-core/pull/21368)
- Verified Sell option works as expected
- Verified Off-ramp page loads and populates the value correctly
