### ISSUE TITLE
Loss of "Clickable area" on new tab page tiles

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#3487]
## Description 

The tiles on the new tab page have lost some of the "clickable" area surrounding them. Must click closer to the center of the tile in order to get a response.

## Reproduces how often: 

Always

## Brave version (brave://version info)
Release - v0.60.45
Beta - v0.61.36
Dev - v0.62.8

### Additional Information

User report with rough graphic outline of "clickable" area:
https://www.reddit.com/r/brave_browser/comments/atkkex/release_channel_update_v06045_is_live/eh33f2u/?context=3

**Comment by dayfuaim** [comment]
Yes, I confirm this.

Brave 0.61.36 Chromium: 73.0.3683.39 (Официальная сборка), beta (64 бит)
