### ISSUE TITLE
Move ERC20 allowance lookups to a query

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34871]
## Description 

Allow polling in addition to on-demand lookups of ERC20 allowances

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.148 Chromium: 121.0.6167.164 (Official Build) beta (64-bit)
-- | --
Revision | c68893a5f2bbf2898967a976b21b3fe5d581f714
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21369](https://github.com/brave/brave-core/pull/21369)
- Verified ERC20 token approval, revoke and amount all work as expected without any regression
