### ISSUE TITLE
Grouping portfolio assets by account or network always hides valueless tokens

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34893]
## Description 

Tokens with no fiat value such as Testnet Filecoin are not shown when the portfolio is grouped by "accounts" or "networks". They onnly appear when gourping is set to "none".This happens regardless if the "hide small balances" filter is disabled or not

## Steps to Reproduce

   1. Add a testnet Filecoin account
   2. add funds to the testnet account
   3. click on the portfolio filters button and group the portfolio aseets by "accounts" or "networks"
   4. disable the "hide small balances" filter

## Actual result:

Filecoin testnet assets are not shown

## Expected result:
Filecoin testnet assets should be shown

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from issue description
- Verified disabling hide small balances and grouping by accounts/network, continues to show Filecoin testnet balances

https://github.com/brave/brave-browser/assets/17010094/ba9d7007-553c-4c24-93dd-090e7379492b
