### ISSUE TITLE
Vertical Tabs Missing Scrollbar

### ISSUE THREAD

**Issue by supplefrog** [brave/brave-browser#34894]
## Description 
Issue is self-explanatory. A small tweak is required to improve the UX

## Expected result:
Scrollbar needed for faster scrolling in vertical tabs.

## Reproduces how often: 
No steps to reproduce

## Brave version (brave://version info)
1.60.125 Chromium: 119.0.6045.199 (Official Build) (64-bit)

**Comment by rebron** [comment]
Closing as dupe of https://github.com/brave/brave-browser/issues/31204. 
Set brave://flags/#brave-vertical-tab-scroll-bar to Enabled
We'll create a different issue to have this as a visible setting in brave://settings.
