### ISSUE TITLE
Add options for controlling how blocking is done at a high level

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#3489]
This is Step 2 of the plan outlined in this issue:
https://github.com/brave/brave-browser/issues/3475
In the section "Summary of the plan"

It looks like this:
<img width="1001" alt="Screen Shot 2019-03-10 at 11 11 09 PM" src="https://user-images.githubusercontent.com/831718/54098232-0e8a4000-438a-11e9-9a70-f317e08932f5.png">

Step 2: Add options to easily disable the exception rules, it will be allowed by default when this step lands as it is today for FB login buttons, embedded tweets, and embedded FB posts.
This will allow you to uncheck things, and it will look like:

# Test Plan

Before testing on this can be done, the data-files must be updated from:
https://github.com/brave/adblock-lists/pull/54
If that pull request is closed, then you can assume they are updated.

1. Make sure defaults look like this:
```
* [x]  Allow Google login buttons on third party sites
* [x]  Allow Facebook logins and embedded posts
* [x]  Allow Twitter embedded tweets
* [ ]  Allow LinkedIn embeds
```

2. Use this test page: https://fmarier.github.io/brave-testing/social-widgets.html and make sure toggling settings and reloading the page works correctly.

Note that between reloads you need to do a clean reload (cmd+shift+r) so that it doesn't use cache.

3. Test logins to the following sites work:
https://twitch.tv FB login
https://quora.com FB login
https://www.espn.com/login/ FB login
https://www.etsy.com/signin FB login

4. Retest these issues about embedded tweets, they should still work.
brave/browser-laptop#2014
brave/browser-laptop#1208

5. Test that Google login only works when the option is on for https://pinterest.com/login/
You will need to reload between login attempts after the setting is changed.
You may need to click the login button twice, if so the issue is not related to this ticket but can be posted.

**Comment by tomlowenthal** [comment]
cc: @karenkliu

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.62.37 Chromium: 73.0.3683.86 (Official Build) beta (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Linux

* Verified the default settings are as expected
* Verified individual toggle working on mentioned sites
* Verified sites mentioned in  brave/browser-laptop#2014 & brave/browser-laptop#1208 work when setting is enabled
* Verified scenario when settings are toggled to off
