### ISSUE TITLE
Time overlaps on stats when incognito tab is resized 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#349]
## Description 
Time overlaps on stats when incognito tab is resized 

## Steps to Reproduce
   1. Ensure stats have a good count
   2. Open a new incognito tab
   3. Resize to min width, time overlaps the stats 
   4. Private tab info text should be responsive based on size of window

 ## Actual result:

## Reproduces how often: 

![tabresize](https://user-images.githubusercontent.com/17010094/41445687-2309c086-7019-11e8-81a8-8b21c4bb6ea7.gif)

## Brave version (about:brave info)

332140d8

### Website problems only:  
- Does the issue gets fixed with Brave Shields disabled? 
- Does the issue reproduces on Chrome? 

### Additional Information
Similar issue on https://github.com/brave/browser-laptop/issues/14408

**Comment by cezaraugusto** [comment]
closing as private windows doesn't have stats anymore

**Comment by bbondy** [comment]
Marking invalid milestone since no code was landed for this.
