### ISSUE TITLE
Maximized may give incorrect window size to extensions

### ISSUE THREAD

**Issue by skewty** [brave/brave-browser#34900]
## Description 
Maximizing Brave window seems to give incorrect window size to extensions.

## Steps to Reproduce
 
   1. Maximize window.
   2. Click on extension.

## Actual result:
![Screenshot from 2023-12-14 11-09-00](https://github.com/brave/brave-browser/assets/9087223/6b35e4b5-7471-4be8-86c0-0d1a31a5f946)

## Expected result:
Window opens with proper width to be usable.

## Reproduces how often: 
100%.

## Brave version (brave://version info)

Brave	1.61.104 Chromium: 120.0.6099.115 (Official Build) (64-bit) 
Revision	38497f14ca9ff6f1d5b9c1d72f61fec6f0efcf1d
OS	Linux
JavaScript	V8 12.0.267.10
User agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Command Line	/opt/brave.com/brave/brave --profile-directory=Default --app-id=cifhbcnohmdccbgoicgdjpfamggdegmo --disable-domain-reliability --enable-dom-distiller --enable-distillability-service --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --ozone-platform-hint=auto --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions --ozone-platform=wayland
Executable Path	/opt/brave.com/brave/brave
Profile Path	/home/jsmith/.config/BraveSoftware/Brave-Browser/Default
Active variations	AllowCertainClientHintsStudy:Enabled
BraveAIChatEnabledStudy:Enabled
BraveAdblockMobileNotificationsListDefault:Enabled
BraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=6/MaximumInlineContentAdsPerDay=20/AdServingVersion=2
BraveAutoTranslateStudy:AutoTranslateDisabled
BraveDebounceStudy:Enabled
BraveForgetFirstPartyStorage:Enabled
BraveGoogleSignInPermissionStudy:Disabled
BraveHttpsByDefaultRolloutStudy:Enabled
BraveP3AConstellationReleaseRollout:Enabled
BraveRewardsWebUiPanelStudy:Enabled
BraveScreenFingerprintingBlockerStudy:Enabled
BraveSearchAdStudy:EnabledInProcessDesktop
ClampPlatformVersionClientHint:Disabled
CookieListDefaultStudy:Enabled
Default1pBlockingStudy:Disabled
DisableReduceLanguage:Enabled
EphemeralStorageStudy:Enabled
FirstPartyEphemeralDomainBlockStudy:Enabled
ForceDisableBlinkFeatures:Enabled
PartitionBlinkMemoryCacheStudy:Enabled
PartitionConnectionsByNetworkIsolationKeyStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled
SmilAutoSuspendOnLagKillSwitch:Disabled_EmergencyKillSwitch
UserActivityStudy:Triggers
WhatsNewStudy:Enabled

## Other Additional Information:
- Fedora 39 Workstation
- Wayland session

**Comment by hofmmaxi** [comment]
I am experiencing the same issue, and I am able to reproduce it 100% as well.

<details><summary>Brave Version</summary>

| About | Version |
|--------|--------|
| Brave | 1.63.41 Chromium: 120.0.6099.115 (Official Build) nightly (64-bit) |
| OS | Linux |
| JavaScript | V8 12.0.267.10 |
| User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 |
| Command Line | `/opt/brave.com/brave-nightly/brave --disable-domain-reliability --enable-dom-distiller --enable-distillability-service --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --enable-experimental-web-platform-features --enable-quic --ozone-platform-hint=auto --enable-features=TabGroupsSave --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions --ozone-platform=wayland` |
| Executable Path | /opt/brave.com/brave-nightly/brave |
| Profile Path | /home/maggsii/.config/BraveSoftware/Brave-Browser-Nightly/Default |
| Active Variations | AllowCertainClientHintsStudy:EnabledBraveAdblockMobileNotificationsListDefault:EnabledBraveAds.AdNotificationsStudy:AdNotificationTimeout=15BraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=6/MaximumInlineContentAdsPerDay=20/AdServingVersion=2BraveAutoTranslateStudy:AutoTranslateDisabledBraveDebounceStudy:EnabledBraveForgetFirstPartyStorage:EnabledBraveGoogleSignInPermissionStudy:EnabledBraveHorizontalTabsUpdateEnabledStudy:EnabledBraveHttpsByDefaultRolloutStudy:EnabledBraveLocalhostAccessPermissionStudy:EnabledBraveP3AConstellationBetaNightlyRollout:EnabledBraveRequestOTRTabRolloutStudy:EnabledBraveRewardsWebUiPanelStudy:EnabledBraveScreenFingerprintingBlockerStudy:EnabledBraveSearchAdStudy:EnabledBraveSearchPromotionBannerStudy:banner_type_BBraveWebViewRoundedCornersStudy:EnabledClampPlatformVersionClientHint:DisabledCookieListDefaultStudy:EnabledCosmeticFilteringChildFramesStudy:EnabledDefault1pBlockingStudy:DisabledDefaultBraveCommandsStudy:EnabledDisableReduceLanguage:EnabledEphemeralStorageStudy:EnabledFirstPartyEphemeralDomainBlockStudy:EnabledForceDisableBlinkFeatures:EnabledHangWatcher:DefaultPartitionBlinkMemoryCacheStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeStudy:EnabledSmilAutoSuspendOnLagKillSwitch:Disabled_EmergencyKillSwitchUserActivityStudy:Triggers |

</details>

<details><summary>Other Additional Information</summary>

### Software Information
- **OS Name:**                                     Fedora Linux 39 (Workstation Edition)
- **Windowing System:**                            Wayland

</details>

**Comment by rebron** [comment]
cc: @simonhong

**Comment by skewty** [comment]
#### Reports of it working in:

- 1.62.153 Chromium: 121.0.6167.85 (Official Build) (64-bit)
- v1.62.156 Brave (Jan 31, 2024)

**Comment by bsclifton** [comment]
Thanks for sharing the work-around @sg-qwt! and thanks for reporting this is fixed in latest release @skewty!

I'll close this issue out - but let's comment here and we can re-open if it's still broken for folks
