### ISSUE TITLE
Add additional Leo feature usage metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#34906]
Add the following P3A metrics for Leo:

Did you use Leo this week?
`Brave.AIChat.UsageWeekly`

1. Yes, as a free user
2. Yes, as a premium user

As a first time user of Brave Leo this week, did I return again to use it during the first 7 day period?
`Brave.AIChat.NewUserReturning`

0. I have never used the feature
1. I have used the feature, but I'm not a first time feature user this week
2. I'm a first time feature user this week but, no, I did not return the rest of the week
3. I'm a first time feature this week and, yes, I returned and used it again the following day
4. I'm a first time feature user this week and, yes, I returned and used it again this week but not the following day

As an opted in Brave Leo user, when was the last time I used Brave Leo? (reported monthly)
`Brave.AIChat.LastUsageTime`

1. Within the last 6 days
2. 7 - 13 days ago
3. 14 - 20 days ago
4. 21 - 30 days ago

cc @mattmcalister

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.63.106 Chromium: 120.0.6099.199 (Official Build) nightly (64-bit)
-- | --
Revision | 281307652d5d2dca2705422c9b01e68316d22f5f
OS | Windows 10 Version 22H2 (Build 19045.3803)
```
