### ISSUE TITLE
Crash Report, 1.61.104 crashed when closing a tab

### ISSUE THREAD

**Issue by valynor** [brave/brave-browser#34909]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.104 Chromium: 120.0.6099.115
Operating System: Mac OS X 14.2.0 (arm64)

@simonhong 

It seems like the crash on closing a tab (#34785) is not fully fixed in 1.61.104, after ~12 hours being open Brave just crashed to desktop again when I closed a tab. 

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/3f5e0300-100a-300b-0000-000000000000

**Comment by simonhong** [comment]
Hmm, it seems crash still happens. Looking.

**Comment by kjozwiak** [comment]
The above requires `1.61.108` or higher for `1.61.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.61.109 Chromium: 120.0.6099.144 (Official Build) (x86_64)
-- | --
Revision | ea6e204b94e25f08d7a80301c88ba8d2bf96502f
OS | macOS Version 14.3 (Build 23D5033f)
```


First, reproduced using

```
Brave | 1.61.104 Chromium: 120.0.6099.115 (Official Build) (x86_64)
-- | --
Revision | 38497f14ca9ff6f1d5b9c1d72f61fec6f0efcf1d
OS | macOS Version 14.3 (Build 23D5033f)
```

### Crash ID: `ff020100-a543-390b-0000-000000000000`


<br class="Apple-interchange-newline">
<img width="1312" alt="Screenshot 2023-12-20 at 5 36 49 PM" src="https://github.com/brave/brave-browser/assets/387249/f218e25e-63ba-4c77-9948-bce5e92f8929">

**Comment by LaurenWags** [comment]
Verified with

```
Brave	1.61.109 Chromium: 120.0.6099.144 (Official Build) (arm64) 
Revision	ea6e204b94e25f08d7a80301c88ba8d2bf96502f
OS	macOS Version 14.2 (Build 23C64)
```

Reproduced the issue using test plan from https://github.com/brave/brave-core/pull/21397#issue-2043000216 and `1.61.104 Chromium: 120.0.6099.115`.

Using same steps as test plan, could not reproduce the crash using `1.61.109 Chromium: 120.0.6099.144`.

1.61.104 | 1.61.109
--- | ---
![Screenshot 2023-12-21 at 7 50 57 AM](https://github.com/brave/brave-browser/assets/28145373/2f918f9d-6432-4eb2-82cc-e8cd40222eab) | ![Screenshot 2023-12-21 at 7 54 30 AM](https://github.com/brave/brave-browser/assets/28145373/7be0ec1d-84c7-4049-bb25-6c4b3c016b27)
