### ISSUE TITLE
perf: persist portfolio token balances to local storage

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34917]
## Description 

Save queried portfolio token balances to local storage and initialize the query result with the stored value to speedup subsequent app launches.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.153 Chromium: 121.0.6167.164 (Official Build) beta (64-bit)
-- | --
Revision | ef6dd148841564e2c5d9110bed5d6b7aad780525
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21400](https://github.com/brave/brave-core/pull/21400)
- Verified portfolio token balances continue to work without regressions
