### ISSUE TITLE
Update toolbar / sidebar / navigation icons size and margins

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#34918]
I made a small adjustment on the toolbar icons size, they were all too small I realized. So I adjusted them.

### New sizes are:

> In summary: All our own icons are 18x18px. Favicons or extension icons are 16x16px.
> All button sizes remain as they're now. The only thing that changes is the icon size inside of them

---------------------------
![image](https://github.com/brave/brave-browser/assets/15734630/a3cfb774-c1ad-4609-8484-c18788591619)

### Toolbar / Tab bar / URL bar:
- Icons in tab bar: New tab, tab search, 18x18px
- Toolbar icons: Back / forward / reload, Wallet, side panel, etc etc. are 18x18px
- Icons inside of the url bar: Speedreader, share, shields, etc. are 18x18px
- Icons from extensions in toolbar: 16x16px.

----------------------------
<img width="218" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/2a1b9558-64e6-4ffd-b040-662644858b7c">

### Sidebar:
- Sidebar icons are all 18x18px.
- Favicons from items added to sidebar: 16x16px.

All available here for reference:
https://www.figma.com/file/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?type=design&node-id=186%3A17108&mode=design&t=LMgARCK6IraPo4hP-1

**Comment by simonhong** [comment]
working on this.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.63.138 Chromium: 121.0.6167.85 (Official Build) beta (64-bit)
-- | --
Revision | 742a3bdf71b710125a1c1dd8e89981b9009a87bc
OS | Windows 11 Version 23H2 (Build 22631.3085)
```

Installed 1.63.138
launched Brave



![image](https://github.com/brave/brave-browser/assets/98358127/d183b37d-54f0-4bfb-8f44-66c54814c9ea)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave	1.63.142 Chromium: 121.0.6167.139 (Official Build) beta (64-bit) 
Revision	7f6a671325da3f7f1ba2680c7a2115f895b4ff6b
OS	Linux
JavaScript	V8 12.1.285.28
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.63.154 Chromium: 121.0.6167.184 (Official Build) beta (x86_64)
-- | --
Revision | f35267209b18bcda22c64916148c654e7d5b19ca
OS | macOS Version 13.6.4 (Build 22G513)
```
