### ISSUE TITLE
AI Chat: Allow some premium models to be used by non-premium users

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#34910]
The models will have stricter limits from the server-side and have special labelling when those limits are reached on the client side.

**Comment by petemill** [comment]
I'm not sure we yet have the exact UI designed for the rate limiting error on freemium models. I imagine it's similar to this, except the action will be something like "switch to basic model" @mattmcalister @aguscruiz?

<img width="463" alt="image" src="https://github.com/brave/brave-browser/assets/741836/f10fc4e4-4faf-44c3-9b4e-f1e21d2e76ce">

**Comment by aguscruiz** [comment]
Yeah I agree, instead of "retry" we could use that action.

**Comment by aguscruiz** [comment]
Just remembered we actually have that full design here:
https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=950-6301&mode=design

**Comment by kjozwiak** [comment]
The above requires `1.62.147` or higher for `1.62.x` verification 👍

**Comment by kjozwiak** [comment]
@SergeyZhukovsky looks like the above is labelled as `OS/Android`. Double checking if the above can even be checked on `Android` yet? Maybe we can quickly check the above via `1.63.x` for `Android` to make sure it's also working?

**Comment by SergeyZhukovsky** [comment]
@kjozwiak yes it's applied for Android and could be checked same way as on desktop using Android nightly build.

**Comment by kjozwiak** [comment]
> @kjozwiak yes it's applied for Android and could be checked same way as on desktop using Android nightly build.

Thanks @SergeyZhukovsky. @hffvld @Uni-verse when verifying this one, lets use `1.64.x` and add the results/verification notes within this issue 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.62.149 Chromium: 121.0.6167.75 (Official Build) (64-bit)
-- | --
Revision | ff84587bd70af9fcbcbe59fc5194ca65082759c4
OS | Windows 11 Version 22H2 (Build 22621.3007)
```

**_Mixtral_** 

1. installed 1.63.124
2. launched Brave (using `--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev`)
3. visited techcrunch.com in a new tab
4. clicked sidebar on the toolbar 
5. clicked Leo on the sidebar
6. entered `Disney` in the `Enter a prompt here`
7. clicked `Accept and begin` button
8. verified `Mixtral` is a default
9. loaded an article https://techcrunch.com/2024/01/22/disney-holotile/
10. clicked on Summarize this page
11. clicked on Suggest questions...

Confirmed  non-premium users can use premium model `Mixtral` 
example | example | example 
----- | ------ | ----
<img width="565" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/cbe35d97-8b45-4229-9e52-04bebf4ab44b">|<img width="568" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a39b5444-03e7-4048-a307-f4e6e3fefc62">|<img width="565" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9b633a3c-d118-4283-bec9-673bbcfe9112">


**_Llama 2 13B by Meta_** 

1. new profile 
2. launched Brave (using `--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev`)
3. visited https://www.cnbc.com/2024/01/22/bitcoin-briefly-dips-below-40000-for-the-first-time-this-year-.html in a new tab
4. clicked sidebar on the toolbar 
5. clicked Leo on the sidebar
6. clicked `Summarize this page`
7. clicked `Accept and begin` button
8. switched to Llama 2 13b via `...` settings
10. clicked on Summarize this page
11. clicked on Suggest questions...

example | example 
----- | ------ 
<img width="240" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/1dba3358-9cc4-4a9c-8e2a-47baf6f8d535">|<img width="566" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/eccdf41c-519d-407d-8b8f-06d90034699a">


**_Claude Instant by Anthropic_** - Failed

1. new profile 
2. launched Brave (using `--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev`)
3. visited https://www.cnbc.com/2024/01/22/bitcoin-briefly-dips-below-40000-for-the-first-time-this-year-.html in a new tab
4. clicked sidebar on the toolbar 
5. clicked Leo on the sidebar
6. clicked `Summarize this page`
7. clicked `Accept and begin` button
8. switched to Claude Instant by Anthropic `...` settings
10. clicked on Summarize this page
11. clicked on Suggest questions...

Actual results:  Got an there was a network issue connection to Leo` 

example | example 
----- | -----
<img width="255" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e3c68d47-c8fd-4ad0-b425-d13ce775ca52">|<img width="566" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/28d57566-3b86-4a43-8aba-f2349b588faf">

**Comment by hffvld** [comment]
Based on https://github.com/brave/brave-browser/issues/34910#issuecomment-1901752574 verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP11.231215.007 release-keys
Brave build: 1.64.20 
Chromium: 121.0.6167.85 (Official Build) canary (64-bit) 
```

Filed follow-up issue #35560
---------------------------

<details>
<summary> Mixtral </summary>

**STEPS:**
1. Install and launch Brave `1.64.20 `
2. Visit any website, for example, https://chromeunboxed.com
3. Three-dot menu > Leo
4. Tap `Summarize this page` > Accept and begin > Verify
5. Tap the `Three-dot` menu in `Leo` > Verify
6. Go to any article on https://chromeunboxed.com
7. Three-dot menu > Leo > Tap `Summarize this page`
8. Tap on `Suggest questions...` > Verify
9. Tap suggested questions or make a new query > Verify

**ACTUAL RESULTS:**
- Verified that `summarize this page` is working
- Verified that `Mixtral` is set by default
- Verify that `Suggest questions...` is working
- Verified that `non-premium` users can use the premium model `Mixtral`. After 3 attempts, got the rate-limiting dialog `Response rate limit reached`

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/9c3771a4-9c65-4c76-bda7-4cf7acff463d) | ![2](https://github.com/brave/brave-browser/assets/128532965/6bfe4240-218c-4014-8cbb-56324b566a00) | ![3](https://github.com/brave/brave-browser/assets/128532965/6489e435-f3bb-491a-b11a-cd04f835dcd1) |
</details>

<details>
<summary> Claude Instant </summary>

**STEPS:**
1. Install and launch Brave `1.64.20 `
2. Visit any website, for example, https://chromeunboxed.com
3. Three-dot menu > Leo
4. Tap `Summarize this page` > Accept and begin > Verify
5. `Three-dot` menu on `Leo` page > Choose `Claude Instant`
7. Tap `Summarize this page` > Verify
8. Go to any article on https://chromeunboxed.com
9. Three-dot menu > Leo > Tap `Summarize this page`
10. Tap a link in the article > Three-dot menu > Leo > Tap `Summarize this page`
11. Repeat Steps 9 and 10 a few times

**ACTUAL RESULTS:**
- Verified that `Mixtral` is set by default
- Verified that `summarize the page` is working when switched to `Claude Instant` language model
- Verified that `non-premium` users can use the premium model `Claude Instant`. After 7 attempts, got the rate-limiting dialog `Response rate limit reached`

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/d5ca7fa8-c9a7-41e1-856a-bd3790c3a328) | ![2](https://github.com/brave/brave-browser/assets/128532965/62c879d2-aa32-4530-84fa-168382476747) | ![3](https://github.com/brave/brave-browser/assets/128532965/de7b3fa5-fe9c-42da-b033-e4cb77f20cc8) |
</details>

<details>
<summary> Llama 2 13B </summary>

**STEPS:**
1. Install and launch Brave `1.64.20 `
2. Visit any website, for example, https://chromeunboxed.com
3. Three-dot menu > Leo
4. Tap `Summarize this page` > Accept and begin > Verify
5. `Three-dot` menu on `Leo` page > Choose `Llama 2 13B`
7. Tap `Summarize this page` > Verify
8. Go to any article on https://chromeunboxed.com
9. Three-dot menu > Leo > Tap `Summarize this page`
10. Tap a link in the article > Three-dot menu > Leo > Tap `Summarize this page`
11. Repeat Steps 9 and 10 ~5 times

**ACTUAL RESULTS:**
- Verified that `Mixtral` is set by default
- Verified that `summarize the page` is working when switched to `Claude Instant` language model
- Verified that responses returned as expected, and rate limit dialog is not shown after repeating about 5 times

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/0b5c4066-5b8a-4b5b-9fdb-b3c80db8b4d7) | ![2](https://github.com/brave/brave-browser/assets/128532965/b2e9a461-8043-41e3-900a-3f135d941cf8) | ![3](https://github.com/brave/brave-browser/assets/128532965/2f6fed98-b3dc-4f13-ad53-eff142238e56) | ![4](https://github.com/brave/brave-browser/assets/128532965/369cfd8a-0706-4bf2-a921-c323d44932da) |
</details>

**Comment by kjozwiak** [comment]
Removing the above from https://github.com/brave/brave-browser/issues/35625 as `Leo` is targeting `1.63.x` for `Android`.
