### ISSUE TITLE
Account address is not shown in transaction details screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#34926]
## Description 

Account address is not shown in transaction details screen

## Steps to Reproduce

   1. Submit a bitcoin transaction
   2. Go to activity tab and open the submitted transaction
   3. Shows Account name
   4. Click on the copy button
   5. Nothing is copied to clipboard

## Actual result:

Account address is not shown in transaction details screen

## Expected result:
Should show the account address similar to other network and should copy the address to clipboard

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.63.45 Chromium: 120.0.6099.115 (Official Build) nightly (64-bit)
-- | --
Revision | c03dc500310f859f5b782db68041ec758bd5108e
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @supermassive

**Comment by supermassive** [comment]
![image](https://github.com/brave/brave-browser/assets/168356/27bea1d2-d38e-4b42-8bf4-806ebf775dad)
![image](https://github.com/brave/brave-browser/assets/168356/230a4098-3dfd-456e-8ed5-58b87cd8acde)

**Comment by supermassive** [comment]
There is no 'from address' for BTC transaction as there could be many of them. This PR https://github.com/brave/brave-core/pull/21415 fixes some related issues from screenshots above
