### ISSUE TITLE
Thumbnail not shown for some of the cards in the Brave news feed

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#34936]
## Steps to Reproduce

   1. Install 1.62.107 
   2. launch Brave
   3. click `Turn on Brave News`
   4. clicked `Refresh`
 

## Actual result:
Thumbnails are not shown for some of the cards 

example | example 
---- | ----
<img width="403" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/75100abe-a371-4340-a68c-3b6f8308e3fa">|<img width="346" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/7115902d-2917-4b9e-96e9-f2617e6cfabc">

## Expected result:

<img width="319" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/bf0ef4d5-0577-4661-a89d-6641e2173f6e">

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.62.108 Chromium: 120.0.6099.115 (Official Build) beta (64-bit)
-- | --
Revision | a4384535072a2aee6e7c21d221f8aa29dae3dd9f
OS | Windows 11 Version 22H2 (Build 22621.2861)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@fallaciousreasoning

**Comment by sanskar1306** [comment]
I want to work on this issue.

**Comment by fallaciousreasoning** [comment]
Hey @MadhaviSeelam - I think @aurangzaib048 has fixed the backend issue which was causing this :smile:

**Comment by LorenzoMinto** [comment]
This should be resolved. Haven't seen this in a while. We now also show cards without images (except hero cards)
