### ISSUE TITLE
Vertical tabs occasionally detach from the main window since the last 3 recent updates

### ISSUE THREAD

**Issue by TheBeachMaster** [brave/brave-browser#34938]
## Description 
Over the last 3 updates, I have noticed that Vertical tabs get detached from the main window, this results into tabs going off-screen.

## Steps to Reproduce

   1. Have a series of multiple vertical tabs (mine number into 30/40 open tabs per browser window; I have also multiple windows open - about 17 browser windows with up-to 30 or more tabs each. I am not sure if that's the trigger)
   2. Bring window into focus
   3. Click on one of the tabs
 

## Actual result:

See arrows pointing to the results on how this looks...
![Screenshot 2023-12-16 at 00 30 04](https://github.com/brave/brave-browser/assets/9129843/a1341971-81e8-4d72-b7a4-58b6c527b7e3)

This is what a window with detached vertical tabs looks like
![Screenshot 2023-12-16 at 00 40 42](https://github.com/brave/brave-browser/assets/9129843/b2aee3d8-90eb-479b-89aa-b92334aa1a5b)

## Expected result:
Properly behaved vertical tabs.

## Reproduces how often: 

Intermittent

## Brave version (brave://version info)

**Brave Version**: 1.61.101 Chromium: 120.0.6099.71 (Official Build) (arm64) 
**OS**: macOS Version 14.2 (Build 23C64)
**HW**: Apple M2 Max

## Version/Channel Information:

- Can you reproduce this issue with the current release? - **Yes**
- Can you reproduce this issue with the beta channel?  - **N/A**
- Can you reproduce this issue with the nightly channel? - **N/A**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? - **No**
- Does the issue resolve itself when disabling Brave Rewards? - **No**
- Is the issue reproducible on the latest version of Chrome? - **N/A (I do not use Chrome)**

**Comment by rebron** [comment]
cc: @sangwoo108

**Comment by TheBeachMaster** [comment]
I've noticed that this is triggered when the window has been idle for a while.

**Comment by bsclifton** [comment]
Closing as stale. If this is still happening, please let us know and we can re-open. I haven't heard any other reports of this unfortunately and there aren't clear steps to reproduce. We have had a lot of fixes landed for vertical tabs since this was opened
