### ISSUE TITLE
`New content available.  Reload?` message appears too often

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#34937]
## Description 

`New content available.  Reload?` message appears too often

## Steps to Reproduce

   1. install `1.63.46`
   2. launch Brave
   3. open a new-tab page
   4. scroll down
   5. click on `Turn on Brave News`
   6. click on either the `Refresh` button or the `New content available.  Reload?` button at the top
   7. wait
   8. new content appears
   9. notice message is still there
   10. click it again
   11. new content appears
   12. rinse, lather, repeat

## Actual result:

See above - you can keep dismissing the `New content available.  Reload?` button for quite a while

![refresh-issue](https://github.com/brave/brave-browser/assets/387249/83fdf36e-a597-47b9-b94b-8963d7e91203)

## Expected result:

It should disappear after the initial, full-feed-content load, no?

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.63.46 Chromium: 120.0.6099.115 (Official Build) nightly (x86_64)
-- | --
Revision | a03c7973112557e032d5d393d16b0a979d17c464
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @fallaciousreasoning @aguscruiz @rebron @mattmcalister @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.62.116` or higher for `1.62.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```

Brave | 1.62.121 Chromium: 120.0.6099.144 (Official Build) beta (x86_64)
-- | --
Revision | ec4a006cb0f9a9d309ef78f6e11882e4bcf12c14
OS | macOS Version 14.3 (Build 23D5033f)
```
