### ISSUE TITLE
brave:// pages show up in browsing history

### ISSUE THREAD

**Issue by Liunkae** [brave/brave-browser#3493]
## Description 
Special pages (that begin with brave://, such as brave://history/) show up in the browsing history.

## Steps to Reproduce
   1. Go to brave://history/
   2. Look at the latest entry in the browsing history.

## Actual result:
The history page is in the browsing history.
![](https://user-images.githubusercontent.com/19424103/53376287-6f922c80-3923-11e9-8040-f4e9a5b8c876.png)

## Expected result:
The history page should not be in the browsing history.

## Reproduces how often: 
Always

## Brave version (brave://version info)
Brave | 0.62.8 Chromium: 73.0.3683.39 (Official Build) dev(64-bit)
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes, 0.62.8 dev.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Not applicable.
- Is the issue reproducible on the latest version of Chrome? Not sure.

**Comment by srirambv** [comment]
Reproduced on Linux as well

**Comment by rebron** [comment]
cc: @simonhong @bridiver can you take a look?

**Comment by simonhong** [comment]
@rebron Yep, I'll take a look after finishing current item(MacOS OS theme controls theme)

**Comment by btlechowski** [comment]
Not reproducible on Release and Beta

Brave | 0.60.45 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows

Brave | 0.61.39 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

![image](https://user-images.githubusercontent.com/34715963/53466214-5d161100-3a51-11e9-9073-70e17dca1106.png)

Reproducible on dev

Brave | 0.62.8 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312



![image](https://user-images.githubusercontent.com/34715963/53466356-e4638480-3a51-11e9-8bd6-558abf492096.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.63.5 Chromium: 73.0.3683.67 (Official Build) dev (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 10 OS Build 17134.523
