### ISSUE TITLE
AI Chat: Fix video transcripts for youtube navigations

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#34945]
Youtube specifically will only partially be fixed by https://github.com/brave/brave-browser/issues/34946.

The technique we use to get the transcript for a Youtube video page is  
```js
const tracks = ytplayer?.config?.args?.raw_player_response?.captions?.playerCaptionsTracklistRenderer?.captionTracks
```

However, `window.ytplayer` is only provided for the first Youtube video load. Subsequent "pages" are same-document (data is loaded via JS and Url is modified via `history.pushState`). The data is fetched via API, but not exposed as a global.

We could assume there are english transcripts for a video, build the expected url and attempt to download it.
Or we could intercept the JSON response from the Youtube server and extract the video metadata, a la https://stackoverflow.com/questions/54610750/why-does-the-youtube-ytplayer-object-not-update-when-navigating-between-youtube

## Steps to Reproduce (from https://github.com/brave/brave-browser/issues/34145)

   1. Navigate to youtube.com
   2. Navigate from there to any youtube video
   3. Begin playing the video.
   4. Open Leo from sidebar. 
   5. Observe blank, unrelated prompt.
   6. Ask Leo to summarize video; observe generic "unable to summarize the video in the youtube page" message.

## Actual result:

View from my machine when I invoke Leo while YT is playing in the foreground of the active tab alongside the sidebar; note, I have not navigated to another window away from the active tab/page at all, I have only clicked the sidebar to open Leo alongside the active view.
<img width="1198" alt="leo-invoked-with-yt-playing-in-active-view-0" src="https://github.com/brave/brave-browser/assets/8979240/1e08f48b-dba2-4a1f-8fde-06ffcd8b354b">
## Expected result:
When I refresh the active tab and window, I observe the expected behavior that I would hope to see when I initially invoke Leo from the active foreground page/tab. 
<img width="1202" alt="leo-invoked-with-yt-playing-on-refresh-1" src="https://github.com/brave/brave-browser/assets/8979240/ab50e75a-a70c-48e1-88d2-ebe4fed448a9">

**Comment by kjozwiak** [comment]
The above requires `1.64.112` or higher for `1.64.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.64.112 Chromium: 123.0.6312.58 (Official Build) (64-bit) 
Revision	99f35375946ee8d232a0b111983ea341c24eadb5
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

Using STR/Test Plan in https://github.com/brave/brave-core/pull/22334#issue-2156189918

- Verified summary for correct youtube video is given.
- Verified context used is updated when opening another video.

Example | Example | Example
-|-|-
![Screenshot 2024-03-26 at 1 45 17 PM](https://github.com/brave/brave-browser/assets/17885425/afd55cf0-7e87-4b2b-b568-9a211e915053) | ![Screenshot 2024-03-26 at 1 45 21 PM](https://github.com/brave/brave-browser/assets/17885425/d67fa0d6-19af-42b8-9198-3ad96f2dffcb) | ![Screenshot 2024-03-26 at 1 45 12 PM](https://github.com/brave/brave-browser/assets/17885425/c624dfdc-c808-4ba4-80a5-b36fdaf578e3)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.64.112 Chromium: 123.0.6312.58 (Official Build) (64-bit)
-- | --
Revision | 99f35375946ee8d232a0b111983ea341c24eadb5
OS | Windows 11 Version 23H2 (Build 22631.3296)
```

1. Installed 1.64.112
2. launched Brave
3. logged in as a Leo premium user
4. visited youtube.com in a new tab
5. navigated to another video in the same tab and played the video - https://www.youtube.com/watch?v=xVWEwgLNX-U 
6. opened Leo panel and clicked `Summarize this page`
7. navigated to another video in the same tab and played the video - https://www.youtube.com/watch?v=549zqueskD4
8. clicked `Summarize this page`

- Confirmed the correct video content is summarized for the first video
- Confirmed updated video transcript is shown for the second video   


example | example 
---- | ---
![image](https://github.com/brave/brave-browser/assets/98358127/17b02fe9-1f2c-4c0e-9863-a799a3d2517b)|![image](https://github.com/brave/brave-browser/assets/98358127/cf3d360d-f13a-4e7a-b817-f68d7430267a)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Revision | 4e20399c0c5e3cbbb80dd1119122400e08259feb
OS | Windows 10 Version 22H2 (Build 19045.4239)
```
