### ISSUE TITLE
Wrong date of the first monthly tip on the monthly tip confirmation dialog

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3494]
Follow up from https://github.com/brave/brave-browser/issues/3023

## Steps to Reproduce

   1. Clean profile
   2. Enable rewards
   3. Claim Grant
4. Make a recurring tip on a site

## Actual result:

`Your first monthly tip will be sent on` shows current date
![image](https://user-images.githubusercontent.com/34715963/53377321-de8e7600-3961-11e9-8c07-9ef363829d30.png)

## Expected result:
`Your first monthly tip will be sent on` shows `Next monthly tip date` from `brave://rewards/`
![image](https://user-images.githubusercontent.com/34715963/53378513-28795b00-3966-11e9-9e0f-de8815b27677.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

cc @brave/legacy_qa @NejcZdovc @ryanml

**Comment by kjozwiak** [comment]
Reproduced on `macOS 10.14.3 x64` using the following build:

Brave | 0.61.38 Chromium: 73.0.3683.39 (Official Build) beta(64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Mac OS X

Example of the issue occurring on macOS (notice the inconsistent contribution dates):

<img width="1595" alt="screen shot 2019-02-26 at 4 59 55 pm" src="https://user-images.githubusercontent.com/2602313/53449575-1a6c1e80-39e8-11e9-93bc-6346c41ad6e7.png">

**Comment by rebron** [comment]
@NejcZdovc can you ask for uplift to 61.x/62.x?

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.61.48 Chromium: 73.0.3683.56 (Official Build) beta (64-bit)
-- | --
Revision | 303af44e2f2948869279f120021c778855d76ead-refs/branch-heads/3683@{#653}
OS | Windows 10 OS Build 17134.523

- Verified the test plan from https://github.com/brave/brave-core/pull/1789
- Verified the STR mentioned in the description

![image](https://user-images.githubusercontent.com/38657976/53976594-5d876980-412d-11e9-940f-ef63d5413f62.png)
![image](https://user-images.githubusercontent.com/38657976/53976616-68da9500-412d-11e9-9c81-39d6533182d5.png)
