### ISSUE TITLE
Implement Soprano external account option

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#34952]
## Description

https://github.com/brave/internal/issues/1105

**Comment by LaurenWags** [comment]
@brave/qa-team please put verification notes for this under https://github.com/brave/internal/issues/1116.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.63.145 Chromium: 121.0.6167.139 (Official Build) beta (x86_64)
-- | --
Revision | 73dc726c461ceae35c2aa15c4a2d9e6736b5c86d
OS | macOS Version 13.6.4 (Build 22G513)
```

Verification notes can be found under https://github.com/brave/internal/issues/1116#issuecomment-1927411414.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.63.146 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | cb9ee9c98182a64716e4237bf1202f1aec3bcff8
OS | Windows 10 Version 22H2 (Build 19045.3930)
```
Verification notes can be found under https://github.com/brave/internal/issues/1116#issuecomment-1908032609

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave	1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit) 
Revision	b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS	Linux
```
