### ISSUE TITLE
Tweetdeck does not load with brave shields enabled.

### ISSUE THREAD

**Issue by jnki** [brave/brave-browser#3495]
## Description 

When Brave shields are enabled, tweetdeck no longer loads.

## Steps to Reproduce

   1. have shields enabled
   2. go to tweetdeck.twitter.com

## Actual result:

![image](https://user-images.githubusercontent.com/17442109/53381289-34feb300-3968-11e9-9430-c5bf285f53bc.png)

## Expected result:
tweet deck should load.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

Brave | 0.60.45 Chromium: 72.0.3626.109 (Official Build) (64-bit)
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 

Yes the issue is resolved when disabling shields, but I never had to disable them for tweetdeck previously.

**Comment by srirambv** [comment]
cc: @lukemulks @jonathansampson

**Comment by eljuno** [comment]
+1s from Twitter 

https://twitter.com/torgo/status/1100321016910409728?s=09

**Comment by mritzmann** [comment]
Same with [mobile.twitter.com](https://mobile.twitter.com/home). Problem exists because Brave is blocking `api.twitter.com`.

**Comment by arnoldn** [comment]
+1 mobile.twitter.com is not working with Ads and trackers blocked in shields.  Worked yesterday, but not this morning.

**Comment by bsclifton** [comment]
Sounds like an ad-block rule update, if this worked yesterday

**Comment by fmarier** [comment]
Presumably this will be fixed by brave/ad-block#172.

**Comment by bsclifton** [comment]
@jnki @arnoldn @mritzmann are you all still experiencing this?

**Comment by mritzmann** [comment]
@bsclifton mobile.twitter.com works again, but on tweetdeck.twitter.com the problem still exists.

**Comment by arnoldn** [comment]
Looks like mobile.twitter.com now works with ads and trackers blocked, but tweetdeck still doesn't load.  This is on 0.61.36.

**Comment by torgo** [comment]
Just testing again on Brave Version 0.61.17 on MacOS - Now Tweetdeck *does* seem to be working, with all shields up. 🙄

**Comment by jnki** [comment]
Tweetdeck has started working again with brave shields enabled in Brave 0.60.45 on windows.

**Comment by bsclifton** [comment]
Awesome- I'll go ahead and close this issue for now... thanks for the updates, folks!

Please do re-open the issue or at least leave a comment if you experience this again 😄
