### ISSUE TITLE
Perf: combine Brave Rewards information lookup queries

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34955]
## Description 

Combine Brave Rewards information lookup queries to reduce the number of hooks ran in components. Also create the rewards account, token and network during lookup to cache these object and prevent extra renders without the need for more memoization hooks. Utilize the base query cache to hold this data so we can later improve the tokens registry, token balances registry and price history queries to include rewards data without creating new object or refetching rewards info.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21418](https://github.com/brave/brave-core/pull/21418)
- Verified Brave rewards balance works as expected on Wallet

https://github.com/brave/brave-browser/assets/17010094/d5bfa221-3970-41cc-bb1c-435c0d907a13
