### ISSUE TITLE
`Top Sources` feeds are not populated/shown by default on a new-profile

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#34958]
## Description 

`Top Sources` feeds are not populated/shown by default on a new-profile

## Steps to Reproduce

   1. install `1.63.46`
   2. launch Brave
   3. open a new-tab page
   4. scroll down
   5. click on `Turn on Brave News`
   6. look at the default experience

## Actual result:

<img width="1312" alt="Screen Shot 2023-12-18 at 8 22 22 AM" src="https://github.com/brave/brave-browser/assets/387249/08c1b2d9-8bef-4dae-8794-17c1b594e38f">

## Expected result:

It should probably have loaded and shown the `Top Sources` since we're subscribed to them by default

<img width="1312" alt="Screen Shot 2023-12-18 at 8 30 03 AM" src="https://github.com/brave/brave-browser/assets/387249/384fe0b5-d7a7-4306-8b5b-1c26e929cef3">

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.63.46 Chromium: 120.0.6099.115 (Official Build) nightly (x86_64)
-- | --
Revision | a03c7973112557e032d5d393d16b0a979d17c464
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @fallaciousreasoning @rebron @mattmcalister @brave/qa-team

**Comment by stephendonner** [comment]
Ah, looks like this should be fixed with the landing of https://github.com/brave/brave-core/pull/21410

**Comment by fallaciousreasoning** [comment]
Fixed by https://github.com/brave/brave-browser/issues/34937

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.62.129 Chromium: 120.0.6099.144 (Official Build) beta (x86_64)
-- | --
Revision | be1405d346b33750ce1b2b8e2a3b9e8ce84847c4
OS | macOS Version 13.6.3 (Build 22G436)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.62.129 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | be1405d346b33750ce1b2b8e2a3b9e8ce84847c4
OS | Windows 11 Version 22H2 (Build 22621.2861)
```

Verified STR from description.

Confirmed after enabling Brave News on a new profile `Top Sources` content is shown in `My Feed` as a default and `Top Sources` s channel feed. 
Confirmed when unfollowed `Top Sources`, `No content` message displayed 

example | example | example 
----- | ----- | ----
<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c86feadc-3378-4333-a081-9c0a3995b76f">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/791b7d82-05ca-4b6d-99d6-21d098d10559">|<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6dfbdc25-05a3-46a8-b33e-77191bba9d07">

**Comment by btlechowski** [comment]
Verified with


Brave | 1.62.129 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | be1405d346b33750ce1b2b8e2a3b9e8ce84847c4
OS | Linux

Verified STR from description.

Confirmed after enabling Brave News on a new profile content was populated initially.

![image](https://github.com/brave/brave-browser/assets/34715963/bd84822a-dd82-49a6-885e-b608e6f74d42)
