### ISSUE TITLE
[Brave News]: Feed ranking fixes

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#34951]
We introduced a couple of regressions in https://github.com/brave/brave-core/pull/21111
- Following feed no longer only contains articles you're following
- Sometimes feed generation stops earlier than it should

**Comment by stephendonner** [comment]
@fallaciousreasoning can you get this uplifted into `1.62.x`?

**Comment by fallaciousreasoning** [comment]
Should be uplifting now :smile:

**Comment by kjozwiak** [comment]
The above requires `1.62.117` or higher for `1.62.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.62.121 Chromium: 120.0.6099.144 (Official Build) beta (x86_64)
-- | --
Revision | ec4a006cb0f9a9d309ef78f6e11882e4bcf12c14
OS | macOS Version 14.3 (Build 23D5033f)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | 41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6
OS | Windows 11 Version 22H2 (Build 22621.2861)
```

1. installed 1.62.128
2. launched Brave
3. opened a new-tab page
4. scrolled down
5. clicked on `Turn on Brave News`
6. clicked on `Customize`
7. subscribed to `LA times` and `Lonely Planet`
8. unsubscribed from Top Sources
9. clicked `New content available. Reload?`
10. clicked `Following` in the sidebar


Have noticed the issue in 1.62.112.  Verified and confirmed, `Following` shows articles from `LA times` and `Lonely Planet`. 

<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/22ae1fde-867d-4106-8979-34c6c0553747">
