### ISSUE TITLE
Square off tune icon and other url bar icons

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#34957]
## Description 

The icons in the url bar are too round and should use our square icon design for consistency.

## Design

![image](https://github.com/brave/brave-browser/assets/5951041/92d33aff-7110-4edf-aebc-aa01591ba6e9)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by simonhong** [comment]
Working now.

**Comment by stephendonner** [comment]
## Verification  `IN-PROGRESS` using

```
Brave | 1.63.101 Chromium: 120.0.6099.199 (Official Build) nightly (x86_64)
-- | --
Revision | 8d3f0a563e185b6a763cc8e210ab24775dfb9047
OS | macOS Version 14.3 (Build 23D5043d)
```

`Light` | `Dark`
-------|--------

**Comment by stephendonner** [comment]
I spun off the oblong, circular site-permissions "bubbles" over in https://github.com/brave/brave-browser/issues/35191.

**Comment by kjozwiak** [comment]
Removing `QA Pass-macOS` as the above will need to be verified via `1.62.x` now that it's been uplifted via https://github.com/brave/brave-core/pull/21548. However, used https://github.com/brave/brave-browser/issues/34957#issuecomment-1881811929 as the needed verification for uplifting as per https://github.com/brave/brave-core/pull/21548#pullrequestreview-1822339799.

The above requires `1.62.144` or higher for `1.62.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.62.144 Chromium: 120.0.6099.217 (Official Build) beta (x86_64)
-- | --
Revision | 75de8d953f6a5686e425d46d7f0dc9284dc1c064
OS | macOS Version 13.6.3 (Build 22G436)
```
