### ISSUE TITLE
[Brave News]: We should support channel migrations in Brave News

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#34950]
There are a number of channels which should be migrated based on the attached spreadsheet:
https://docs.google.com/spreadsheets/d/1kTfiHtJey05ZfknP6ZK1Kgt_y-2wGNkQ6zxau7PkT6k/edit#gid=1348208051

**Comment by kjozwiak** [comment]
The above requires `1.62.131` or higher for `1.62.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.62.131 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | 217e8080b48df17845efb3c1a80433a8028978de
OS | Windows 11 Version 22H2 (Build 22621.2861)
```

1. Installed 1.61.114
2. launched Brave
3. clicked `Turn on Brave News`
4. clicked `Customize`
5. followed below publishers - `The New York Times` 
6. subscribed to following channels:
- `Culture`, `Celebrity News` `Entertainment`, `Entertainment News`, `Technology`, `Tech News`, `Tech Reviews`, `Sport`, `Sports`, `Film and TV`,  
7. closed Brave
8. installed 1.62.131
9. rename the above profile to Brave-Browser-Beta
10. launch Brave Beta
11. verified news is still enabled
12. scrolled to down to view the feed 
13. clicked `Customize` button to view Brave news dialog
 
Confirmed subscribed to only `Technology` in the Brave news feed sidebar
- `Tech News` and `Tech Reviews` are not present in the list of channels
-  Also `Sport` is not present in the list of channels 
Confirmed Brave news dialog shows `Technology` in the sidebar
- `Tech News` and `Tech Reviews` are not present in the list of channels
-  Also `Sport` is not present in the list of channels         
step 5-6 | step 12 | step 13
------ | ------ | ----- 
<img width="947" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d478ee9b-95d3-4aac-9865-4585c0eadba2">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/0d54649a-8979-4d5f-a714-24ae2cfe4112">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/5bd9f539-3f98-4d0f-ac40-b9e83ddbf31e">

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP11.231020.013.A1 release-keys
Brave build: 1.62.134
Chromium: 120.0.6099.199 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Install and launch Brave `1.61.86`
2. After landing on `NTP` tap `Show Brave News`
3. Scroll down and tap the `Customize` button in the top right corner
4. Channels > Subscribe to `Celebrity News` and `Culture`, `Entertainment` and `Entertainment News`, `Sport` and `Sports`, `Tech News`, `Tech Reviews` and `Technology`
5. Go back and tap `Load new content` to see the updated news feed
6. Close Brave > Upgrade Brave to `1.62.134`
7. Launch Brave > Scroll down the news feed > Tap the `Customize` button in the top right corner
8. Channels > Verify

**ACTUAL RESULTS:**
- Verified that `Brave News` still enabled after Brave upgrade
- Verified that subscriptions to `Culture`, `Entertainment`, `Sports` and `Technology` still exist after Brave upgrade
- Verified that `Celebrity News`, `Entertainment News`, `Sport`, `Tech News` and `Tech Reviews` don't exist anymore after Brave upgrade

---------------------------

*Before upgrade*

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/a12f3519-2222-4cb6-aee4-521a57f66157) | ![2](https://github.com/brave/brave-browser/assets/128532965/164177c0-9b4d-4d98-9a79-74452005a297) | ![3](https://github.com/brave/brave-browser/assets/128532965/5b6359e6-cd23-4c37-94ce-564971122525) |

*After upgrade*

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/b0d8225a-2013-4bdd-862f-f4df0cfe6a00) | ![2](https://github.com/brave/brave-browser/assets/128532965/b38eff8a-b6ec-4105-ba1d-12c384b64fcc) | ![3](https://github.com/brave/brave-browser/assets/128532965/91138896-0aa0-4c46-887c-f44d01c04b14) |
