### ISSUE TITLE
[Brave News]: Don't crop ad image in News Ads cards

### ISSUE THREAD

**Issue by LorenzoMinto** [brave/brave-browser#34967]
News Ads cards should be scaled vertically to fit the ad image and avoid cropping it. Ad images won't exceed 1:1 ratio.

**Comment by kjozwiak** [comment]
The above requires `1.62.116` or higher for `1.62.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `PASSED` using

```
Brave | 1.62.116 Chromium: 120.0.6099.144 (Official Build) beta (x86_64)
-- | --
Revision | 632ccd5061221cfe5e1b9f3d14345cfd62db9655
OS | macOS Version 11.7.10 (Build 20G1427)
```


<img width="1762" alt="Screen Shot 2023-12-27 at 9 47 51 AM" src="https://github.com/brave/brave-browser/assets/387249/4a0da87b-1415-45ad-9ed2-d25480ab0942">
