### ISSUE TITLE
426 Upgrade required UI message is not shown

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#34960]
When refiling tokens fails with 426, we should show a modal.
The message was introduced https://github.com/brave/brave-browser/issues/21388

## Steps to Reproduce

1. Override `https://mywallet.ads.brave.com/v2/confirmation/token/*` response code to 426
1. Enable rewards and ads
1. Connect to a custodian

## Actual result:

Upgrade required UI modal is not shown

![image](https://github.com/brave/brave-browser/assets/34715963/0a967bb8-37e4-4fac-acbb-9ce5f3832657)|![image](https://github.com/brave/brave-browser/assets/34715963/ef2519e5-cb25-434e-9429-496913adcd38)
--|--

## Expected result:
Upgrade required UI modal is shown

![image](https://github.com/brave/brave-browser/assets/34715963/ef188272-dfb4-463d-a4cf-3451a2aff995)|![image](https://github.com/brave/brave-browser/assets/34715963/2951ba68-fa6d-4a82-bfea-7f5ec57ef74e)
--|--

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.62.107 Chromium: 120.0.6099.115 (Official Build) beta (64-bit)
-- | --
Revision | 67a3b21572338a0660bb25a5855da0f1e9372a39
OS | Linux

cc @tmancey @aseren

**Comment by kjozwiak** [comment]
The above requires `1.63.143` or higher for `1.63.x` verification 👍

**Comment by btlechowski** [comment]
Verified with

Brave | 1.63.157 Chromium: 122.0.6261.43 (Official Build) (64-bit)
-- | --
Revision | 5fbb7c60cc44e15a910a39a349e632f1b904c58e
OS | Linux



![image](https://github.com/brave/brave-browser/assets/34715963/3b969d3a-2095-4fe9-8353-fd81d9841656)|![image](https://github.com/brave/brave-browser/assets/34715963/b3c1dd22-64cc-4341-b47c-3b5e152b52b9)
--|--
