### ISSUE TITLE
Extension settings appears at the bottom of the Manage Search Engines page

### ISSUE THREAD

**Issue by Liunkae** [brave/brave-browser#3496]
## Description 
On the Manage Search Engines settings page, the Extension settings section appears at the bottom. It should only appear on the main settings page.

## Steps to Reproduce
   1. Go to brave://settings/
   2. Select **Manage search engines**
   3. Scroll to the bottom of the page

## Actual result:
The Extensions section appears at the bottom:
![](https://user-images.githubusercontent.com/19424103/53387694-a2511a80-394d-11e9-848a-9c95187dc342.png)

## Expected result:
The Extensions section should not be on an unrelated page.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
Brave | 0.62.8 Chromium: 73.0.3683.39 (Official Build) dev(64-bit)
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes, 0.62.8.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Not applicable
- Is the issue reproducible on the latest version of Chrome? Not sure

**Comment by bsclifton** [comment]
cc: @yrliou

**Comment by rebron** [comment]
dupe of #3444 ?

**Comment by Liunkae** [comment]
Yes, looks like a duplicate of #3444.
