### ISSUE TITLE
Sometimes account blockies are just blank

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#34965]
## Description 
Sometimes account blockies are just blank

## Steps to reproduce 

   1. Create a new wallet or restore wallet
   2. Go to accounts tab
   3. Some accounts have a blank blockie mostly seen on first Solana account 

## Actual result 

New wallet | Restore Wallet
-- | --
![NewAccount](https://github.com/brave/brave-browser/assets/17010094/62a07c80-493d-40e9-a0b5-f0e1a5118605) | ![RestoreAccount](https://github.com/brave/brave-browser/assets/17010094/0cc7df21-7637-453b-9fb1-3e59abb99381)

## Expected result
Show proper blockie

## Issue reproduces how often 
Some what easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Not checked

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.61.107

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe

**Comment by simoarpe** [comment]
Solid colors can happen. The behavior is expected.
Link to Slack discussion: https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1699544681612909?thread_ts=1699450616.856909&cid=C023VS4HJ6Q

I'm closing this.
