### ISSUE TITLE
Remove custom partner headers

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#34971]
[Custom partner headers](https://github.com/brave/brave-browser/wiki/Custom-Headers#x-brave-partner) are now down to a [single partner](https://github.com/brave/brave-core/blob/3f943c78376b4c09d8f2322d85b8e71f285b4572/components/brave_referrals/browser/brave_referrals_service.cc#L210-L223) and are no longer needed.

This was removed from the iOS browser in https://github.com/brave/brave-ios/pull/5083.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.63.101 Chromium: 120.0.6099.199 (Official Build) nightly (x86_64)
-- | --
Revision | 8d3f0a563e185b6a763cc8e210ab24775dfb9047
OS | macOS Version 14.3 (Build 23D5043d)
```

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP11.231215.009 release-keys
Brave build: 1.63.146
Chromium: 121.0.6167.139 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/21426#issue-2049356084

**ACTUAL RESULTS:**
- Verified that `X-Brave-Partner` request header is missing

---------------------------

|Reproduced with `1.62.161` build|Verified with `1.63.146` build|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/50cd079c-a240-4081-9a60-8edcde9d8ba5) | ![2](https://github.com/brave/brave-browser/assets/128532965/08b68fb4-f8bf-4c91-ba78-2e9f1d20671c) |
