### ISSUE TITLE
Panel is not updated immediately 

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#3497]
## Description 

If you visit youtube video and open panel % is not updated automatically, you need to re-open it to view %.

## Steps to Reproduce

   1. enable rewards
   2. go to youtube video
   3. open panel

## Actual result:

% stays the same

## Expected result:
% should update if you stay on the panel

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.63.5 Chromium: 73.0.3683.67 (Official Build) dev (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 10 OS Build 17134.523
