### ISSUE TITLE
After hiding a publisher via 3 dot menu, no feed loaded when refreshed 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#34973]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/34593.  This could be an edge case but when a publisher is hidden, the article/Hero card is not hidden from the feed even after reloading page.  Tried again to hide via 3 dots menu in the card and reloaded feed.  Clicked to Refresh to get the new feed. Empty feed is shown.  Nightly shows same behavior, however upon reload the page, feed is shown. 

## Steps to Reproduce

   1. Install 
   2. launch Brave
   3. enable Brave News via Customize dialog
   4. Follow `TVLine` publisher  
   4. clicked Refresh button
   5. clicked 3 dots menu in the TVLine Card to hide the content from publisher
   6. `TVLine` publisher is hidden from the Publisher list
   7. Reload the page and Hero card still shown 
   8. clicked 3 dots menu in the TVLine Card to hide the content from publisher
   9. clicked `Refresh` button again
## Actual result:

- Empty feed is shown 
- Article card is not hidden

https://github.com/brave/brave-browser/assets/98358127/c8350de4-1db7-4118-ae37-69188b5ab945

## Expected result:
New feed should be loaded

## Brave version (brave://version info)

Easily

## Version/Channel Information:

```
Brave | 1.62.112 Chromium: 120.0.6099.115 (Official Build) beta (64-bit)
-- | --
Revision | ae1e179b9884b2de2f4ba0bdea7da3beaad93ffa
OS | Windows 11 Version 22H2 (Build 22621.2861)
```

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@fallaciousreasoning @rebron 
@brave/qa-team

**Comment by stephendonner** [comment]
Yeah, I've also noticed that `Refresh` doesn't seemingly purge unsubscribed feed content either.


Brave | 1.62.114 Chromium: 120.0.6099.115 (Official Build) beta (x86_64)
-- | --
Revision | 99aef745405a1811625f22be58b850977f1f2d51
OS | macOS Version 11.7.10 (Build 20G1427)

**Comment by stephendonner** [comment]
If we want parity with `1.61.x`, after adding or removing a feed subscription, we should pop-up the "New content available.  Reload?` messaging/button, which is the new version of `1.61.x`'s blurple `Load new content` messaging/button.

<img width="1312" alt="Screen Shot 2023-12-19 at 4 35 54 PM" src="https://github.com/brave/brave-browser/assets/387249/19f36cb3-423e-47e9-a5bd-ba03dadcd4af">

**Comment by kjozwiak** [comment]
The above requires `1.62.124` or higher for `1.62.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.62.124 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | d281285150cedd393f665d2b99e12cb0e62ae12a
OS | Windows 11 Version 22H2 (Build 22621.2861)
```

1. Installed 1.62.124
2. launched Brave
3. enabled Brave News via Customize dialog
4. Followed TVLine publisher
5. clicked `New content available. Reload?` 
6. confirmed `TVLine article/Hero card` is shown
7. clicked 3 dots menu in the `TVLine Card` to hide the content from publisher
8. confirmed  `New content available. Reload? message shown
9. TVLine publisher is hidden from the Publisher list
10. clicked `New content available. Reload? 

### Confirmed TVLine publisher article/Hero card is hidden

Example | Example | Example 
----- | ---- | ----
<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/0750bf74-b895-49c1-89c3-d693646fc469">|<img width="951" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/7c3210e9-f069-4210-aadd-9b0de27a235f">|<img width="954" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/14cf07f5-7947-41ff-aa34-32e198c25f98">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (x86_64)
-- | --
Revision | 41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6
OS | macOS Version 11.7.10 (Build 20G1427)
```
