### ISSUE TITLE
Brave Ad-Blocking inefficiency

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#34985]
## Description  
The Ad-Blocking capabilities of Brave Browser in Android seem to have **degraded manifold**.

## Steps to reproduce 

   1. Visit the website https://timesofindia.indiatimes.com/city/navi-mumbai/leopard-prey-in-well-for-6hrs-both-live-to-purr-the-tale/articleshow/105796018.cms
   2. **Wait a bit till the full web page is loaded** and explore the content.

## Actual result  
A vast area of the screen is occupied by an element which is seemingly the **leftover of a scrolling ads** or something similar. A screenshot of the same follows:

![image](https://github.com/brave/brave-browser/assets/117711238/340421a5-355b-46e0-ac6f-afc1b1bc2935)

## Expected result
Brave should have seamlessly loaded a clean page with all irritating elements removed. A screenshot of the same **page loaded in Samsung Internet browser running AdGuard extension** is attached herewith: 

![image](https://github.com/brave/brave-browser/assets/117711238/7c90cbed-464c-4bf8-8a59-3fdc4d382550)
(Ads have been gotten rid off in Samsung Internet evidently.)
## Issue reproduces how often 
_**Persistent**_ issue.

## Version/Channel Information:

Brave 1.61.104 Chromium: 120.0.6099.115 (Official Build) (32-bit) 
- Can you reproduce this issue with the current Play Store version? Yes.
- Can you reproduce this issue with the current Play Store Beta version? Not sure.
- Can you reproduce this issue with the current Play Store Nightly version? Not sure.

## Device details
   - Install type (ARM, x86): ARMv7
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy M11
   - Android version: Android 12
   
## Brave version
Brave 1.61.104 Chromium: 120.0.6099.115 (Official Build) (32-bit) 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No. 
- Is the issue reproducible on the latest version of Chrome? Yes. 

### Additional information

I have already tried turning off/on Brave Shield and clearing browsing data.
List of filters enabled in Brave Ad-Block:

![image](https://github.com/brave/brave-browser/assets/117711238/712a7677-417b-4234-80df-ada11435d7be)

Thanking you for your concern.

**Comment by ryanbr** [comment]
Is this working okay now @Sujoy-Paul  ?

**Comment by ryanbr** [comment]
We'll close, free to re-open if its still an issue.
