### ISSUE TITLE
--rewards=staging=false command-line arg and official builds should use production Ads Serve

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#3498]
## Steps to Reproduce

   1.  Launch browser with `--rewards=staging=false` or an official build

## Actual result:
https://ads-server.bravesoftware.com is used for all communications with the Ads Serve for production

## Expected result:
https://ads-server.brave.com should be used for all communications with the Ads Serve for production

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
0.63.x

### Reproducible on current release:
No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional Information
Ads Serve URL can be seen in the console log

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.63.31 Chromium: 73.0.3683.75 (Official Build) beta(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

* Verfied console logs, request/response uses https://ads-server.brave.com
