### ISSUE TITLE
Tab pages

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#35]
To keep in line with browser-laptop, all tab set options should be available

![image](https://user-images.githubusercontent.com/17010094/41445042-cf49dfde-7014-11e8-9e55-8c5233fef5e8.png)

**Comment by bsclifton** [comment]
Per https://github.com/brave/browser-laptop/issues/955, there could be a slick animation when a new tab causes a new tab page to be created:
![tabs2set_animation_mockup](https://cloud.githubusercontent.com/assets/13509546/13410204/4297290a-deeb-11e5-9ae0-bcf346359806.gif)

**Comment by bsclifton** [comment]
Per https://github.com/brave/browser-laptop/issues/5532 there should be keyboard shortcuts for switching between pages

**Comment by bsclifton** [comment]
Per https://github.com/brave/browser-laptop/issues/6603 the page indicator should be obvious:
![image](https://cloud.githubusercontent.com/assets/17010094/21847503/1fa5103a-d7f4-11e6-966b-07e3572bd808.png)

**Comment by srirambv** [comment]
+2 from https://community.brave.com/t/brave-chromium-tab-handling/39627

**Comment by SilverPuppy** [comment]
This, in my opinion, is part of a much larger issue: the settings interface which was so well-executed in the Muon build has been reverted, if you will, to the default interface and set that comes with Chromium, with a few small customizations. The entire settings system from Muon needs to be backported into the new codebase as part of the ongoing recreating of the browser.

**Comment by srirambv** [comment]
+1 from @popcornrulez via #2767 to implement multiple rows of tabs

**Comment by bsclifton** [comment]
+1 from @caspertone2003
> I am running 0.63.48 @W10-x64
When there are too many tabs open, new opened tabs are not shown.
Currently I have 15 pined tabs (that are wider in size than unpinned ones) and 19 non pinned ones. If I open another one I can not reach it after going to another of the opened tabs...

**Comment by Brave-Matt** [comment]
+1 from reddit -- user initially requested muliple tab "rows". That issue (#2767) seems to have been closed in favor of this one.
https://www.reddit.com/r/brave_browser/comments/bkzz5u/customizing_the_browser_to_fix_a_few_glaring/

Fwiw I agree with @bsclifton's [post regarding nice looking animation](https://github.com/brave/brave-browser/issues/35#issuecomment-414196827) when adding pages.

**Comment by Brave-Matt** [comment]
+1 from community (2 users):
https://community.brave.com/t/85-open-tabs-and-then-any-new-tabs-just-disappear/62279/3

**Comment by JonnyRedHed** [comment]
I am a very heavy daily open tabs user and just love the FF kinetic mouse scrolling of the tabs. But I stopped using FF years ago for Opera and Brave/Dev.    300 in Opera and the the current max in Brave Dev 85 (which sucks).

There must be a way you can do this, with your own Brave flavor of doing things… I hope so. With kinetic mouse scrolling settings like speed, accerlaeration etc, ease in and ease out. You could even offer a little graph section in settings so one can see the mouse curve, and adjust interactively. Or just the usual settings found with something like the chrome extension ‘Smoothscroll’ LINK

**Comment by CruiseMan** [comment]
This feature was number one reason i downloaded Brave when what you call it now legacy version was released in beta, please bring it bank

**Comment by ylluminarious** [comment]
+1

Please do something here.

I saw that Chrome now has a flag called `#scrollable-tabstrips`, but it seems to have no effect and according to [this post](https://superuser.com/questions/1323820/how-to-implement-scrollable-tab-bar-in-chrome-like-in-firefox), the Chromium developers have reneged on their promise to implement scrollable tabs. They apparently detest scrolling tabs and like their design the way it is (which is asinine IMO).

Does this flag actually do anything? Can Brave leverage it to have some remedy here? The current tab situation is absolutely a show-stopper for me and dozens if not hundreds of others I've seen around the web and spoken to. Having many tabs open is far more common than Google devs like to think. Anyone who does any kind of research is familiar with this. I've tried using Chrome with 100+ tabs open and it's a total nightmare. In Firefox, it's at least somewhat manageable, especially with the [Tree Style Tabs](https://github.com/piroor/treestyletab) extension. Not being able to even see what a tab is in Chrome is truly terrible.

**Comment by Tectract** [comment]
Please BUMP this in the priority list! This is the main thing keeping me using Firefox instead of Chrome. Tab handling is CRITICALLY BROKEN right now!

**Comment by Sa-Ja-Di** [comment]
Agreed. Bring back this useful feature.

When is Brave finally starting to deliver customization features which are meant for power users? So far Brave serves only the simple users.

**Comment by SilverPuppy** [comment]
This is an illustration of another casualty of the move to stock chromium as the base instead of Muon. Feature parity with the Muon version has been promised but not delivered. The Muon version was much better. The feature I miss the most is actually the way it handled downloads, with a delete button and a close button on each item.

Unfortunately feature parity with its slicker past self is clearly not a developer priority at this point.

On March 17, 2020 7:12:19 AM EDT, Sajadi <notifications@github.com> wrote:
>Agreed. Bring back this useful feature.
>
>When is Brave finally starting to deliver customization features which
>are meant for power users? So far Brave serves only the simple users.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/brave/brave-browser/issues/35#issuecomment-600012996

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Tectract** [comment]
Tab pages would be great, but right now, we are not even guaranteed that the tab we are on will even be VISIBLE in the tabs at all. It's a critical flaw that effectively prevents you from being a "power-user" on chrome and Brave, while Firefox still has it. For this single reason alone, both Brave and Chrome are deprecated to the point of being critically broken, and I have to use Firefox instead.

**Comment by Minasti7** [comment]
I find Brave one of the best and fastest browsers out there but as this feature is not implemented I stopped to use brave at all. I'm a person who open hundreds of tabs and this is annoying, for me it's limited on 70 tabs. There are no plans on this?

**Comment by INeedTogepi** [comment]
I was wanting this ever since the move to chromium. Please add it soon.

**Comment by Tectract** [comment]
Just came back to bump this again. Tabbing is completely broken in Chrome and Brave. Please please prioritize fixing this.

**Comment by TheOneWhoseUsernameWasTaken** [comment]
+1 for multiple rows of tabs.

**Comment by caspertone2003** [comment]
Sorry to say, but lack of this feature made me try other alternatives. I had to give up Brave unique ones as isolated tabs is a need for me. Firefox containers work a treat.

Fact is that believing isolated tabs will come back to Brave is just wishful thinking. Probably it breaks the business model. So, I suggest to move on... live with it or switch.

CT

**Comment by ValeTheVioletMote** [comment]
Just want to add that the lack of this feature continues to keep me off Brave each time I come back to it. It's baffling to think that there are fellow software developers out there who think shrinking tabs is a good idea.

**Comment by rhclayto** [comment]
+1.

Infinitely shrinking tabs in Chromium browsers is so weird to me, coming from Firefox, with a minimum tab width & tab scrolling for overflow. To me the Firefox way of handling numerous tabs is just way better. Please make this happen in Brave, at least as an option, maybe using the `#scrollable-tabstrip` flag that is available in Chromium. Enabling that does make minimum width tabs that overflow the tab bar, but they do no scroll, & they push the 'new tab' button off the screen was well.

+1

**Comment by ValeTheVioletMote** [comment]
I walked over to Vivaldi. Not only can I move the tabs to the sides to prevent infinite shrinkage, but I can also easily add custom CSS to make topbar tabs not shrink.... Now that's a power user feature.

**Comment by SilverPuppy** [comment]
This is more important to some others than to me, but tiny tabs DO bother me occasionally; I don't routinely have a lot of tabs open at a time, nor do most, but for those who do, when we do, being able to clearly tell what they are no matter how many there are is important. I remain VERY DISAPPOINTED in the utter complacency regarding feature parity with the Muon version. At this point I think it has become pure laziness; as long as whatever Chrome does is working well enough for most, the devs aren't interested in looking at it.

**Comment by dabat** [comment]
> +1.
> 
> Infinitely shrinking tabs in Chromium browsers is so weird to me, coming from Firefox, with a minimum tab width & tab scrolling for overflow. To me the Firefox way of handling numerous tabs is just way better. Please make this happen in Brave, at least as an option, maybe using the `#scrollable-tabstrip` flag that is available in Chromium. Enabling that does make minimum width tabs that overflow the tab bar, but they do not scroll, & they push the 'new tab' button off the screen was well.
> 
> This would be a huge UX win for Brave over all the other Chromium browsers, especially for people lured away from Firefox.
> 
> Edit: It looks like the Chromium team added left & right buttons in a commit last October: https://chromium-review.googlesource.com/c/chromium/src/+/2436593 Perhaps that means progress on a Firefox-like scrolling tab bar might come from the Chromium side sometime soon?
> 
> +1

I found that the following flags make the tab situation in Brave tolerable:
![image](https://user-images.githubusercontent.com/37282138/114202480-d5cc4480-991c-11eb-844d-1653d9ade981.png)
here's how it looks:
![image](https://user-images.githubusercontent.com/37282138/114203436-c8fc2080-991d-11eb-85bf-d928556a1a94.png)

**Comment by bbondy** [comment]
We have tab groups now and this is stale / wontfix.

**Comment by Tectract** [comment]
This should be re-opened. It's still a major major major bug. I don't even know what tab groups are and I don't use them, just like 99% of all users.

**Comment by bsclifton** [comment]
@Tectract you can likely achieve most of the same goals with tab groups. Tab groups are a bit easier to use (in my opinion) when you use vertical tabs. You can create a group and stuff as many tabs into that group as you'd like. You can then collapse/expand all the tabs in that group with a click.

One of the challenges with tab pages is that there isn't a grouping. It's just an arbitrary number of tabs, in a paged fashion.

If you have time, please try tab groups and share feedback. To get started, you can right click any tab and pick `Add tab to group`.

**Comment by Tectract** [comment]
> when you use vertical tabs

I don't use vertical tabs, and I have literally never seen anyone use vertical tabs. This still doesn't address that tabbing itself has a critical bug. Firefox fixed this problem very gracefully many years ago, with no need for janky solutions like tab groups or vertical tabbing.

**Comment by ValeTheVioletMote** [comment]
> Message ID: ***@***.***>

Agreed, this should be re-opened. Tab groups are not a solve. They don't 
address the underlying issues at all. Firefox's base UX is simply 
superior to Brave when it comes to tabs. Vivaldi opens the door for 
powerusers to make the browser theirs, which is why I'm still using it 
over Brave. If Brave is only built for casual users who'll have at most 
five tabs open, fine, then you don't need any poweruser options, and I 
understand why you're marking this as "won't fix." But if you want to 
attract users who use the net for hobby or work, enabling the user able 
to easily manage 25, 50, 100, 200, 300 tabs is a must. Shrinking tabs is 
not ok. Needing to go out of the way to shove tabs into groups is not 
ok.

**Comment by Geblaat** [comment]
> > +1.
> > Infinitely shrinking tabs in Chromium browsers is so weird to me, coming from Firefox, with a minimum tab width & tab scrolling for overflow. To me the Firefox way of handling numerous tabs is just way better. Please make this happen in Brave, at least as an option, maybe using the `#scrollable-tabstrip` flag that is available in Chromium. Enabling that does make minimum width tabs that overflow the tab bar, but they do not scroll, & they push the 'new tab' button off the screen was well.
> > This would be a huge UX win for Brave over all the other Chromium browsers, especially for people lured away from Firefox.
> > Edit: It looks like the Chromium team added left & right buttons in a commit last October: https://chromium-review.googlesource.com/c/chromium/src/+/2436593 Perhaps that means progress on a Firefox-like scrolling tab bar might come from the Chromium side sometime soon?
> > +1
> 
> I found that the following flags make the tab situation in Brave tolerable: ![image](https://user-images.githubusercontent.com/37282138/114202480-d5cc4480-991c-11eb-844d-1653d9ade981.png) here's how it looks: ![image](https://user-images.githubusercontent.com/37282138/114203436-c8fc2080-991d-11eb-85bf-d928556a1a94.png)

Unfortunately the scrollable tabstrip flag seems removed.. tabstrip is now unusable.
