### ISSUE TITLE
Provide URL bar title mode

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#350]
cc: @bradleyrichter for mockup

**Comment by bsclifton** [comment]
Per https://github.com/brave/browser-laptop/issues/9901, we should make sure (on Windows) that Title Mode is enabled when mouse is entered from the top

**Comment by bsclifton** [comment]
Per https://github.com/brave/browser-laptop/issues/9900 we should consider whether or not this should be enabled by default on Windows
