### ISSUE TITLE
Remove deprecated wallet prefs

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#35004]
For QA: Wallet needs smoke testing.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified wallet works as expected

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.63.157 x64 build
- Verified wallet works as expected
