### ISSUE TITLE
ERC20Approve transactions reporting incorrect spender address

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#35007]
![pika-1703144261567-1x](https://github.com/brave/brave-browser/assets/3684187/8dbebd55-886b-4cf1-beae-f8a8c9a1b7f4)

The headline displays the token address instead of the contract address, which should match the Details tab of the transaction.

Also, it's unsafe to approve this transaction by only looking at the USDC symbol.

**Comment by jamesmudgett** [comment]
Should also remove the account blockie

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.97 Chromium: 124.0.6367.118 (Official Build) beta (64-bit)
-- | --
Revision | 94909f2aaefd7a8137c8b4fa27235378e79231e3
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22650](https://github.com/brave/brave-core/pull/22650)
- Verified ERC20 Approve transaction now correctly shows the spender address
![image](https://github.com/brave/brave-browser/assets/17010094/14fa4aea-7785-4d0f-b591-b56317bf37c9)
