### ISSUE TITLE
Peeking card missing on new-tab page when opted-out of Brave News

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#35001]
## Description 

Peeking card missing on new-tab page when opted-out of Brave News

## Steps to Reproduce

   1. install `1.63.56`
   2. launch Brave
   3. skip or complete onboarding (but *don't* enable `Brave News`)
   4. look at the new-tab page

## Actual result:

No "peeking card" when you're opted-out by default

<img width="1312" alt="Screenshot 2023-12-20 at 1 04 41 PM" src="https://github.com/brave/brave-browser/assets/387249/d8d1df05-6e85-41c8-9bcd-b8b06f47e80b">

## Expected result:

I believe there should also (still) be a peeking card when you're opted-out, as there is with `beta` and `release`

<img width="1312" alt="Screenshot 2023-12-20 at 1 04 28 PM" src="https://github.com/brave/brave-browser/assets/387249/8c828761-a393-4e56-87bb-513bceadeebb">

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.63.56 Chromium: 120.0.6099.115 (Official Build) nightly (x86_64)
-- | --
Revision | 9822b7ef57464ac11d27d48c164ca5e0780d1e1f
OS | macOS Version 14.3 (Build 23D5033f)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @fallaciousreasoning @mattmcalister @martin-c0des @LorenzoMinto @rebron @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.62.124` or higher for `1.62.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | 41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6
OS | Windows 10 Version 22H2 (Build 19045.3803)
```
- Verified the STR from the description and ensured that the opt-in brave news card in shown in the new tab page

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (x86_64)
-- | --
Revision | 41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6
OS | macOS Version 11.7.10 (Build 20G1427)
```

Verified the STR from the description and ensured that the opt-in brave news card in shown in the new tab page

_peeking card_ | _opt-in dialog_
----------------|----------------
<img width="1312" alt="Screen Shot 2024-01-02 at 1 59 43 PM" src="https://github.com/brave/brave-browser/assets/387249/215f9a69-a957-4dcb-9189-9bbbbec3a26c"> | <img width="1312" alt="Screen Shot 2024-01-02 at 1 59 52 PM" src="https://github.com/brave/brave-browser/assets/387249/ee5d039f-a43f-4048-9e27-7a60b714b517">
