### ISSUE TITLE
Canceling uninstallation on Windows breaks VPN

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#35006]
## Description 

The uninstallation process on Windows removes the VPN services even if the user cancels the uninstaller.

The cause of the problem lies in our implementation of `UninstallProduct`. It removes the VPN services immediately, before calling the upstream implementation. But upstream has special handling for when the uninstallation process gets canceled. Our implementation therefore does not handle this case properly.

## Steps to Reproduce

   1. Install Brave system-wide.
   2. Set up VPN.
   3. Check that VPN works.
   4. Disable VPN.
   5. Also disable the VPN tray icon (to make sure VPN isn't running, for good measure).
   6. Close Brave.
   7. Go to _Add/Remove Programs_.
   8. Select to uninstall Brave.
   9. Accept the UAC prompt.
   10. In the dialog "Are you sure you want to uninstall Brave?", select _Cancel_.
   11. Start Brave.
   12. Enable VPN.

## Actual result:

An alert is shown saying that the VPN helper service is not running.

![image](https://github.com/brave/brave-browser/assets/1076393/66d6400e-fd81-4ae9-a583-3d441057c59f)

The reason is that the VPN services were already uninstalled before we canceled the uninstallation prompt.

## Expected result:

VPN should "just work", without the alert being shown.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

1.61.104 64 bit Windows.

## Version/Channel Information:

Release.

**Comment by rebron** [comment]
cc: @bsclifton @simonhong

**Comment by simonhong** [comment]
Checking this

**Comment by kjozwiak** [comment]
The above requires `1.61.114` or higher for `1.61.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.61.114 Chromium: 120.0.6099.199 (Official Build) (64-bit)
-- | --
Revision | e0f6e091fe79c029231a86e8cdcc5fbe70bcddbe
OS | Windows 10 Version 22H2 (Build 19045.3803)

```
Reproduced the original issue on `1.61.109` using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/35006#issue-2051875932 as per the following:

![image](https://github.com/brave/brave-browser/assets/38657976/8a372b0b-5eac-4415-ab16-7bf100fbf245)


Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/35006#issue-2051875932 & https://github.com/brave/brave-core/pull/21478#issue-2063195455, ensured that VPN service hasn't been removed via `Services`. In this case, `BraveVpnService` as the verification is occurring on the `Release` channel:

* ensured that logging into an account that already has a VPN subscription works without any issues
  * ensured that the tokens/credentials were retrieved automatically once logged into `https://account.bravesoftware.com`
* ensured that VPN is connecting/working as expected (checked several regions/locations)
  * used https://ipleak.net to verify that the VPN is being used
* ensured that `BraveVpnService` is installed via the `Services` tab under `Task Manager`

**`Installing & Running VPN`**

**`Example`** | **`Example`** | **`Example`** | **`Example`** 
----------------|----------------|----------------|----------------



* disabled Brave VPN via the panel
* ensured that the Brave VPN appeared disabled via the tray icon
  * once the VPN was disconnected, removed the Brave VPN tray icon via `Remove Icon`
* started uninstall process via `Control Panel\Programs\Programs and Features`
  * clicked on `Cancel` when prompted `Are you sure you want to uninstall Brave?`
* ensured that `BraveNightlyVpnService` is still installed via the `Services` tab under `Task Manager`
* relaunched Brave and ensured that you can still enable/use VPN without any issues

**`Uninstalling & Cancelling`**

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|----------------|----------------
![image](https://github.com/brave/brave-core/assets/2602313/c8b6d8ef-d5a4-4adf-af4e-c037641b211e) | ![image](https://github.com/brave/brave-core/assets/2602313/b4c70d23-f797-4bc3-8b2a-7c820ba5db63) | ![image](https://github.com/brave/brave-core/assets/2602313/7be1b7d2-1152-4558-b6f9-82699dc7314c) | ![image](https://github.com/brave/brave-core/assets/2602313/4a8f0579-52c1-4c0c-b867-78ed85892fbf) | ![image](https://github.com/brave/brave-core/assets/2602313/12f3847e-bef1-42bd-b77b-749bb1cb665e) | ![image](https://github.com/brave/brave-core/assets/2602313/2b8e4017-6dd5-49f7-a539-6bf0be44d3ce)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.61.114 Chromium: 120.0.6099.199 (Official Build) (64-bit)
-- | --
Revision | e0f6e091fe79c029231a86e8cdcc5fbe70bcddbe
OS | Windows 11 Version 22H2 (Build 22621.2861)
```

Reproduced the original issue on `1.61.109 Chromium: 120.0.6099.144` using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/35006#issue-2051875932 as per the following:

**`Example`** | **`Example`**
---------------|-------------------
![Screenshot 2024-01-04 091547](https://github.com/brave/brave-browser/assets/98358127/b567b9d7-5f40-4261-9271-8d456fac579e)|![Screenshot 2024-01-04 091640](https://github.com/brave/brave-browser/assets/98358127/c909f131-8dfa-4b3c-ac52-c09d531fe179)


Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/35006#issue-2051875932 & https://github.com/brave/brave-core/pull/21478#issue-2063195455, ensured that VPN service hasn't been removed via `Services`. In this case, `BraveVpnService` as the verification is occurring on the `Release` channel:

* ensured that logging into an account that already has a VPN subscription works without any issues
  * ensured that the tokens/credentials were retrieved automatically once logged into `https://account.bravesoftware.com`
* ensured that VPN is connecting/working as expected (checked several regions/locations)
  * used https://ipleak.net to verify that the VPN is being used
* ensured that `BraveVpnService` is installed via the `Services` tab under `Task Manager`

**`Installing & Running VPN`**

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** |**`Example`** |**`Example`** |
----------------|----------------|----------------|----------------|-----------------|---------------|------- |--------
<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c177797a-c5b8-4e2b-a82f-ce702b3d6056">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a85ee2bb-09d7-457c-934f-d23488e0568e">|<img width="954" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e1999b5b-4fab-489e-a62d-35c656e568bc">|<img width="952" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/80eaf092-f37f-408b-8494-85d0c54a4dfd">|<img width="962" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/32397da4-7699-48cc-8de3-27addd3e185f">|<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/124a2e4a-fcf9-430c-8f1f-58646fdd25cb">|<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/be86fbc9-c3b3-4148-9d76-ecab1ded6bdb">|<img width="952" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f79a5081-0d30-49ab-9e63-566e47607f1d">


* disabled Brave VPN via the panel
* ensured that the Brave VPN appeared disabled via the tray icon
  * once the VPN was disconnected, removed the Brave VPN tray icon via `Remove Icon`
* started uninstall process via `Control Panel\Programs\Programs and Features`
  * clicked on `Cancel` when prompted `Are you sure you want to uninstall Brave?`
* ensured that `BraveNightlyVpnService` is still installed via the `Services` tab under `Task Manager`
* relaunched Brave and ensured that you can still enable/use VPN without any issues

**`Uninstalling & Cancelling`**

**`Example`** | **`Example`** | **`Example`** 
----------------|----------------|---------------- 
<img width="952" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d686b6ee-2873-4464-b1ca-7050faa15706">||<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/66ca516b-1718-42dc-a065-a837e3b4cf1f">|<img width="950" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/5bd33108-b776-4441-8003-a08cd911e3fe">


**`After launching Brave, Re-enable vpn and change the region`**

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|----------------|----------------|------------
<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/abf8ab18-ee4a-40f5-8fe6-659123d73fee">|<img width="951" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e16ead86-9e29-4c42-97b5-6814d919fd39">|<img width="949" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/24714e32-ce2c-4edf-8d65-7578ef4d432c">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/539c7487-137a-41fc-8c0f-4d4e2e46f66d">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/134bfa74-07db-439e-9677-30f4629e9f60">|<img width="965" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/aee5d1e5-0666-4ee4-96d4-05258124cd91">|<img width="951" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/3c50390b-d372-472d-a616-37e21685b3a7">
