### ISSUE TITLE
Ads Panel in 0.61x should have Ads Coming Soon 

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#3500]
Please see issue created by @LaurenWags for 0.60 for details below.
Status quo for 0.61 - https://github.com/brave/brave-browser/issues/3421

Original plan is here: https://github.com/brave/brave-browser/issues/3141

cc @jsecretan @bbondy @rebron

**Comment by jsecretan** [comment]
Ads will finally go to production on 0.63.

**Comment by ryanml** [comment]
This was done via: https://github.com/brave/brave-core/pull/1793

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.61.46 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Linux

* Can't test with old profile with ads enabled on Linux as its still not supported 
![image](https://user-images.githubusercontent.com/17010094/53816285-50059000-3f31-11e9-9d0c-9f2c55590ca2.png)
