### ISSUE TITLE
Need to click `Reload` on a just-added direct feed to populate it

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#35000]
## Description 

Need to click `Reload` on a just-added direct feed to populate it

## Steps to Reproduce

   1. install `1.63.56`
   2. launch Brave
   3. open a new-tab page
   4. scroll down
   5. click on `Turn on Brave News`
   6. load `https://chriscoyier.net/`
   7. clicked on `Manage Subscriptions`
   8. clicked `Subscribe`
   9. close the `Customize` dialog
   10. click on `Chris Coyer` under `Publishers`
   11. look at the feed

## Actual result:

example | example
---------|---------
<img width="1312" alt="Screenshot 2023-12-20 at 12 40 48 PM" src="https://github.com/brave/brave-browser/assets/387249/43f0f714-9658-404c-b6d3-9e0a278de008"> | <img width="1196" alt="Screenshot 2023-12-20 at 12 41 19 PM" src="https://github.com/brave/brave-browser/assets/387249/bc0bc6de-d8f3-4eb5-8208-2f462a0909b1">

## Expected result:

<img width="1312" alt="Screenshot 2023-12-20 at 12 41 29 PM" src="https://github.com/brave/brave-browser/assets/387249/cf45783b-c60d-494b-8e98-b04c1aebd3c9">

Since we've just added the feed, it should either be populated or pop-up a `New content available.  Reload?` message or similar?

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.63.56 Chromium: 120.0.6099.115 (Official Build) nightly (x86_64)
-- | --
Revision | 9822b7ef57464ac11d27d48c164ca5e0780d1e1f
OS | macOS Version 14.3 (Build 23D5033f)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @fallaciousreasoning @LorenzoMinto @mattmcalister @rebron @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.62.124` or higher for `1.62.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | 41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6
OS | Windows 10 Version 22H2 (Build 19045.3803)

```

**Comment by stephendonner** [comment]
Thanks for taking a look at this, @GeetaSarvadnya.

Here's what I'm still seeing:

![chriscoyier-feed](https://github.com/brave/brave-browser/assets/387249/69b7ddd9-fab2-4404-8aaf-162c350bcb42)

@fallaciousreasoning do we need a separate followup issue for the above?

**Comment by fallaciousreasoning** [comment]
Yeah, I think a separate issue is a good call!

**Comment by stephendonner** [comment]
> Yeah, I think a separate issue is a good call!

Logged https://github.com/brave/brave-browser/issues/35096.
