### ISSUE TITLE
Brave reward/ad fetches should use SimpleURLLoader tied to user profile

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#3501]
See https://github.com/brave/brave-core/pull/1756#issuecomment-466515552 for concerns about the current way Brave does background fetches in ads and rewards.

`URLFetcher` is used in https://github.com/brave/brave-core/blob/c6506166b093f2c3fb88e43007c05a5133993640/components/brave_rewards/browser/rewards_service_impl.cc#L1134 and https://github.com/brave/brave-core/blob/c6506166b093f2c3fb88e43007c05a5133993640/components/brave_ads/browser/ads_service_impl.cc#L892

It should use https://github.com/brave/brave-browser/wiki/Simple-Guide-to-SimpleURLLoader and be tied to the user profile

**Comment by NejcZdovc** [comment]
+1 from https://github.com/brave/brave-browser/issues/4164

**Comment by simonhong** [comment]
Pushed PR for this.
https://github.com/brave/brave-core/pull/2350
https://github.com/brave/brave-core/pull/2351

**Comment by simonhong** [comment]
All use of `URLFetcher` are deleted.

**Comment by LaurenWags** [comment]
@simonhong does this require manual QA? if so, can you add a test plan? if not, let's mark as `QA/No` 👍

**Comment by simonhong** [comment]
@LaurenWags This was code refactoring.  Marked as `QA/No`. :)
