### ISSUE TITLE
Create helps for creating a combined registry for known & user tokens 

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#35014]
## Description 

There are some areas in the wallet that need both the user's tokens as well as Braves tokens registry. We should add helpers to create the combined registry

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21444](https://github.com/brave/brave-core/pull/21444)
- Verified known tokens and user added tokens are visible under `Available assets` tab of `Edit visible assets` in portfolio overiew menu
