### ISSUE TITLE
Deprecate global redux state for selected portfolio timeline

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#35016]
## Description 

The global Redux state for the portfolio price history graph timeline is currently a wrapper for LocalStorage. Remove this state from Redux to allow updating this state without dispatching actions

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21445](https://github.com/brave/brave-core/pull/21445)
- Verified the selected price graph timeline is same in portfolio overview, portfolio asset, and market asset charts
- Verified the graphs still work as expected without any regressions

https://github.com/brave/brave-browser/assets/17010094/45cd6c0a-4042-4741-8c4c-dbba8ee98c9e
