### ISSUE TITLE
Move hardware wallet account import logic to API mutations

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#35018]
## Description 

Move hardware wallet account import logic to API mutations

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.63.146 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | cb9ee9c98182a64716e4237bf1202f1aec3bcff8
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21446](https://github.com/brave/brave-core/pull/21446)
- Verified able to import ETH/SOL/FIL accounts from Ledger without issues
- Verified able to import Ethereum accounts from Trezor without issues
