### ISSUE TITLE
use api slice for async swap logic

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#35027]
## Description 

Refactor frontend usage of the swap service to utilize the api slice instead of the `lib` context

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.146 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | cb9ee9c98182a64716e4237bf1202f1aec3bcff8
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21454](https://github.com/brave/brave-core/pull/21454)
- Verified EVM/Solana swaps works as expected without any regressions
