### ISSUE TITLE
nperf.com not connecting to server when shields are turned on.

### ISSUE THREAD

**Issue by thanuj10** [brave/brave-browser#35020]
## Description 
nperf.com is a network speed check website and it connects to a third-party server to assess the network. Brave with it's shields turned on with the default settings, blocks the connection to the servers making the speed test to fail. 

## Steps to Reproduce
   1. go to https://www.nperf.com
   2. Wait for the site to check network.
   3. Connection fails.

## Actual result:
![image](https://github.com/brave/brave-browser/assets/43717642/e38e2466-0b16-4929-9813-0d9dad06b99c)
Error that pops up with the shields turned on.

## Expected result:
![image](https://github.com/brave/brave-browser/assets/43717642/13365749-e65d-4e0c-94ed-5d9ce070d657)
Connection successful with shields off.

![Screenshot (14)](https://github.com/brave/brave-browser/assets/43717642/50a3fc8b-6b5e-4d88-ad2a-6c47405d8503)
Speed test works as expected.

## Reproduces how often: 
Consistently Reproduced.

## Brave version (brave://version info)
**Version:** 1.62.107 Chromium: 120.0.6099.115 (Official Build) beta (64-bit) 
**Revision:** 67a3b21572338a0660bb25a5855da0f1e9372a39
**OS:** Windows 11 Version 23H2 (Build 22631.2861)

## Version/Channel Information:
- Can you reproduce this issue with the current release? - Not tested
- Can you reproduce this issue with the beta channel? - Yes
- Can you reproduce this issue with the nightly channel? -  Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? - Yes
- Does the issue resolve itself when disabling Brave Rewards? - Not tested
- Is the issue reproducible on the latest version of Chrome? - No

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by arthuredelstein** [comment]
"Allow fingerprinting" fixes the page.

**Comment by arthuredelstein** [comment]
Now that we are rolling out the Webcompat Exceptions Manager in Release to 100%, this is fixed.
