### ISSUE TITLE
brave://urls work in tor window

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#3503]
## Description 
brave://urls should open in normal window if open'ed in either private or tor window. This works as expected for private but not for `tor windows`

## Steps to Reproduce

   1. Open `brave://settings` in tor
   2. Opens in tor window

## Actual result:
Opens in tor windows

## Expected result:
Should open in regular window

## Reproduces how often: 
Easily

## Brave version (brave://version info)
0.62.8 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Dev

**Comment by kjozwiak** [comment]
With the new preference styles landing in `0.63.x`, loading `brave://settings` in either `Tor` or `Guest` windows will produce the following results:

<img width="1225" alt="Screen Shot 2019-03-15 at 12 27 16 AM" src="https://user-images.githubusercontent.com/2602313/54658185-9a931a80-4aa2-11e9-9904-6649373d0ec9.png">

You'll notice that not all the settings are loaded in the page and the new preference style isn't displayed correctly. Example of the settings page under a normal tab:

<img width="1221" alt="Screen Shot 2019-03-20 at 12 00 57 AM" src="https://user-images.githubusercontent.com/2602313/54658328-463c6a80-4aa3-11e9-99e2-8c84da755071.png">

With the above results, users might get confused why their settings page isn't correctly being loaded in `Tor` & `Guest` windows. The sooner we fix this and disallow `brave://settings` in `Tor`, `PB' & `Guest`, the better.

**Comment by srirambv** [comment]
On windows, only downloads page is loaded in private window. Clicking on any of the other navigation switches it to regular window.  
Tor window, properly shows settings page, download page, bookmarks/history is not shown as expected but Rewards shows optin state but doesn't create wallet

**Comment by riastradh-brave** [comment]
This should be handled as part of #2307.

**Comment by yrliou** [comment]
This is fixed now by https://github.com/brave/brave-core/pull/3319.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.72.110 Chromium: 78.0.3904.70 (Official Build) dev (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

Verified test plan from the description.
Verified that handling of `brave` protocol is the same on `Private Window` and `Private Window with Tor`
