### ISSUE TITLE
Back arrow bug

### ISSUE THREAD

**Issue by dryspeed** [brave/brave-browser#35036]
https://github.com/brave/brave-browser/assets/142707208/11d896a5-2cbd-4bb3-a1a8-5b0a97087925

While using back gesture, an another arrow is being displayed.
Version: Sonoma 14.2.1
---
Version 1.61.109 Chromium: 120.0.6099.144 (Official Build) (arm64)
cc: @rebron @LaurenWags

**Comment by valynor** [comment]
Yeah, I reported that in #34109 a while ago .. no reaction.

**Comment by rebron** [comment]
closing as duplicate of #34109
