### ISSUE TITLE
"Copy clean link" feature not working on poedit.net

### ISSUE THREAD

**Issue by Bushido1** [brave/brave-browser#35035]
## Description 
"Copy clean link" feature not removing the referral part from the link.

## Steps to Reproduce

   1. Open https://poedit.net/news/poedit-3.4-localazy/
   2. Right click with the pointer icon of computer mouse on the hyperlink found in the sentence "One of the standout features of Poedit 3.4 is the addition of support for syncing with the [Localazy localization platform](http://localazy.com/?ref=a9PjgZZmxYvt-12r) directly from the app."
   3. Select Copy clean link
   4. Paste the copied link somewhere where you can insert the text.

## Actual result:
"ref=a9PjgZZmxYvt-12r" part is not removed.

## Expected result:
"ref=a9PjgZZmxYvt-12r" part is removed.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave	1.61.104 Chromium: 120.0.6099.115 (Ametlik järk) (64-bitine) 
Redaction	38497f14ca9ff6f1d5b9c1d72f61fec6f0efcf1d
OS	Linux

## Version/Channel Information:
JavaScript	V8 12.0.267.10
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by rebron** [comment]
cc: @fmarier

**Comment by fmarier** [comment]
You're right, we don't filter out the `ref` URL parameter using the [Clean URLs list](https://github.com/brave/adblock-lists/blob/master/brave-lists/clean-urls.json). I am however pretty hesitant to add it to the global list because it's such a generic term. It could easily be necessary in some URLs.
