### ISSUE TITLE
declarativeNetRequest Rules

### ISSUE THREAD

**Issue by Sp0kzz** [brave/brave-browser#35030]
when will this be fixed ?
https://github.com/brave/brave-browser/issues/30854

some extensions like Live stream Downloader and TwitchNoSub need to be reloaded every time you launch Brave. Brave is the only browser having this issue. What's taking so long ?

**Comment by Sp0kzz** [comment]
@goodov

**Comment by goodov** [comment]
@Sp0kzz thanks for pinging. resolving in https://github.com/brave/brave-browser/issues/30854 with https://github.com/brave/brave-core/pull/21459
