### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by bradmatt275** [brave/brave-browser#35043]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.104 Chromium: 120.0.6099.115
Operating System: Mac OS X 14.2.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Opened a new tab.

Seems to crash randomly when I re-arrange tabs or close a tab. 

It crashes 4 or 5 times a day at the moment.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/cb2a0d00-a543-390b-0000-000000000000

**Comment by valynor** [comment]
@bradmatt275 has been fixed, update your browser

**Comment by bradmatt275** [comment]
> @bradmatt275 has been fixed, update your browser (and your mac ;-)

Thanks @valynor I appreciate the quick reply. Sorry I should have checked the release log before posting the crash report.

I have just updated to 1.61.109.
