### ISSUE TITLE
Sync chain randomly ceases working

### ISSUE THREAD

**Issue by valynor** [brave/brave-browser#35042]
Since 1.61 across all kinds of devices (Windows, Android, macOS, iOS, iPadOS) the Sync chain randomly fails and is not updating across devices anymore. 

More information from multiple users here: 

https://community.brave.com/t/sync-stops-working-randomly-and-cannot-be-restarted-without-new-sync-chain-bookmarks-no-longer-syncing-send-to-device-no-longer-working-reliably-either/521949

This is a major issue IMHO, reliable syncing is very important for a lot of users. Please assign a high priority to this bug.

**Comment by the-overdriven** [comment]
I'm struggling with the same problem. Last time when it happened I've created a new sync ring, but it helped only for a few days because now I've realized it randomly stopped again. 
Almost all models show "Backed off message" at brave://sync-internals shows.
Status from Last Completed Session: `Commit Step Result | Protocol error (TRANSIENT_ERROR)`

**Comment by Jorg333** [comment]
Same here. 
No sync between pc and android. (TRANSIENT_ERROR)” shows in sync internals.

**Comment by ntarox** [comment]
+1. Same issue here, and didn't realize it immediately because I don't change my bookmarks (and also look immediately to verify that change on all of my other devices) very often. I imagine many, many others are in a similar situation.

**Comment by valynor** [comment]
It has been exactly 30 days since my post and the new sync chain I made back then broke again today with 

`Commit Step Result | Protocol error (TRANSIENT_ERROR)` 

Took me 15-20 minutes to create a new one on my 5 devices. This is really annoying and a major issue for people who rely on it to work.

**Comment by Tallyrald** [comment]
Sync stopped working for me somewhere around 2023.12.17 (+- couple days) and is non-functional ever since. Really annoying. Sending a tab/link from the URL bar to another device also doesn't work.

**Comment by jonatan-ivanov** [comment]
I have the same issue. Under brave://sync-internals/ I see this:
```
Throttled or Backoff | true
```
If I click on any `Commit Response` in the `Sync Protocol Log` I see a bunch of errors like this:
```
{
    "error_message": "There are already 50000 non-deleted objects in store",
    "response_type": "OVER_QUOTA"
}
```
Despite of this, the `Commit Response` says: `Result: Success` and in the response there is also this: `"error_code": "SUCCESS"`.


It seems history is also synced and it pushes the objects to sync easily over the quota.

**Comment by jonatan-ivanov** [comment]
Connected to https://github.com/brave/brave-browser/issues/35042#issuecomment-1920066849, if I create a new chain, it works since the object store is empty again. But I think if you do not disable history sync, it will be full again relatively quickly.

I guess removing history from the remote object store and disabling history sync could also work but I have no idea how to do the former.

I think this also mean that 1.61 writes full everyone's object store who use the browser eventually and makes the sync feature broken for them.

**Comment by jonatan-ivanov** [comment]
@AlexeyBarabash I'm not familiar with Brave's triaging process but if the above is correct, breaking sync for everyone who actually uses the browser could get higher priority in my opinion.

**Comment by Jorg333** [comment]
The problem has fixed itself! I just realized that I have all three devices (2 PCs and a mobile) syncing again, with all the bookmarks in their place.

**Comment by oleg-derevenetz** [comment]
> The problem has fixed itself! I just realized that I have all three devices (2 PCs and a mobile) syncing again, with all the bookmarks in their place.

For me, there is still "Protocol error (TRANSIENT_ERROR)".

**Comment by hamirmahal** [comment]
In `Status from Last Completed Session` at brave://sync-internals/ I see

```
Status from Last Completed Session
Sync Source	GU_TRIGGER
GetKey Step Failed	false
Download Step Result	Success
Commit Step Result	Protocol error (TRANSIENT_ERROR)
```

but bookmarks between a Windows 10 laptop and a Linux desktop seemed to sync anyway when I checked yesterday evening.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

**Comment by p134c0d3** [comment]
Having this issue right now, added my Linux machine to my sync chain, and only bookmarks were synced. None of my extensions or autofill were synced even though I left the browser open for an hour, had `Sync Everything` selected. Uninstalled, reinstalled, removed from sync chain, re-added to sync chain, seems to be stuck on "In progress..." in the Sync Node Browser Tab. Clicking Request Start or Trigger Updates does nothing.

**Comment by kmfoodservice** [comment]
Same situation here syncing with 2 Windows 11 computers and 2 Android devices. The only thing that works is deleting the sync chain completely and recreating it.

**Comment by p134c0d3** [comment]
Only fix I've found so far is leaving the browser open overnight, so I'm think the sync might just be EXTREMELY delayed...

**Comment by Jorg333** [comment]
Again "Protocol error (TRANSIENT_ERROR)"

**Comment by martinlanger90** [comment]
same for me

**Comment by BenjaminMichaelis** [comment]
Same error for me "There are already 75000 non-deleted objects in store".

<img width="245" alt="image" src="https://github.com/brave/brave-browser/assets/22186029/fd982d0a-2937-4ed7-b55d-e66866930125">

it would also give me a http error under "Download Step Result".

For me, turning off "sync everything" and only turning on everything except for history got everything seeming to sync again, however, I would love to be able to sync history...

**Comment by martinlanger90** [comment]
> For me, turning off "sync everything" and only turning on everything except for history got everything seeming to sync again somewhat,
that did the trick for me too. disabling history for now...

**Comment by BenjaminMichaelis** [comment]
> That worked only for one time sync... now again transient error.... 

Yeah, 12 hours later and it stopped again... bummer

**Comment by petcap** [comment]
Same issue here, this has been an issue for a while, at least 6+ months. The only working solution so far has been to completely remove and create a new sync chain, but the new chain always stops working after a month or two.

**Comment by mogarchy** [comment]
@AlexeyBarabash Plz help

**Comment by jonatan-ivanov** [comment]
Fyi: **if history sync is on no matter what you do this issue will come back** (unless this will be fixed in Brave), see: https://github.com/brave/brave-browser/issues/35042#issuecomment-1920066849

As a workaround, you need to disable syncing history and remove objects from your object store. The only way I'm aware to remove objects from your object store is creating a new sync chain (history sync disabled).

**Comment by ntarox** [comment]
Surprised that this has been an issue for 4+ months for a browser as mature as Brave. @AlexeyBarabash, can we get a brief explanation on why this is such low priority? The sync feature is quite literally broken

**Comment by shellscape** [comment]
This is clearly not a priority for the team or org, and it's eroding trust in the platform on my end. Odd as it's billed as one of the premier features that sets Brave apart.

**Comment by Tallyrald** [comment]
For the last couple of days, sync started working again and everything was fine... until today. The Transient_error is back and the whole chain stopped once more. In sync-internals the highest number I see in the Type Info table is 778 (bookmarks). History is showing 30 so I'm guessing this isn't just simply and object limit.

**Comment by calipupsr** [comment]
Also been having this issue. Noticed it a few weeks ago when a bookmark didn't go through to my other computer. Everything is marked Backed off and I have the error of "Commit Step Result	Protocol error (TRANSIENT_ERROR)"

**Comment by NicholasYamamoto** [comment]
Wanted to chime in and report that I'm seeing this issue as well. `Protocol error (TRANSIENT_ERROR)`. Everything is `Backed Off` and nothing is syncing at all. Using Brave Browser version 1.64.122 Chromium: 123.0.6312.122 on desktop and Brave Browser version 1.63.2 (183) on iOS.

Really hope this gets addressed or something soon! This has been broken for months! 

@AlexeyBarabash can we please get an update?

**Comment by thrivingproject** [comment]
Same issue here, using Brave on macOS, iPadOS, iOS

**Comment by 4Source** [comment]
![image](https://github.com/brave/brave-browser/assets/38220764/1344926e-b6cd-4591-b800-68ff4aa96afb)

Same Issue here note Local State/Server Connection: ``server error since 2024-04-19 22:18:21 +02``

**Comment by dtantono** [comment]
@4Source I did that workaround before. But, the thing is couple of months later the thing is the sync is broken again and we need to repeat it again. Let's see where it goes

**Comment by 4Source** [comment]
@dtantono I know this would not be a permanent solution just mention it for people who need a Quick Fix.

**Comment by gurgunday** [comment]
My sync died this week, nothings is effectively getting synced, I can't send tabs either

Here's the screenshot:

![IMG_1679](https://github.com/brave/brave-browser/assets/74139498/f86c748a-e134-4056-a19d-10b6a7593fcc)

**Comment by gurgunday** [comment]
Brave should really fix their Sync, I can't think of a more important functionality for a browser

Like literally, please stop adding more crypto stuff until you fix this for good

**Comment by Valmirius** [comment]
This is taking the mickey now, given how long this has been going on.

If you can't make your Browser sync properly then people are going to stop using it eventually

**Comment by hamirmahal** [comment]
I noticed a favorite synced between a desktop and a laptop on my sync chain last night, but I have the `History` option off at
```
brave://settings/braveSync/setup
```
![image](https://github.com/brave/brave-browser/assets/43425812/d859a290-78c3-460d-b07a-5ee3f7c88bce)

**Comment by hamirmahal** [comment]
@kjozwiak could you maybe provide an update to the community on this? When would it be possible for users to enable `History` in their sync settings again?

**Comment by ntarox** [comment]
@AlexeyBarabash @kjozwiak If there is no update on work being done, can you let us know? Would prefer not having to keep checking in and bothering you if this issue is low priority or no longer actively being worked on. Thanks!

**Comment by gurgunday** [comment]
**Update:**

Sometimes [you just have to tag the CEO on Twitter](https://x.com/gurgundayX/status/1786120099725729917) 😄, he confirmed that he has forwarded this issue to the right people

And to be fair to the team at Brave, they are communicating much more actively on their forum and [have also confirmed that they are working on it](https://community.brave.com/t/sync-stops-working-randomly-and-cannot-be-restarted-without-new-sync-chain-bookmarks-no-longer-syncing-send-to-device-no-longer-working-reliably-either/521949/83)

Hopefully we'll have a closure soon

**Comment by bsclifton** [comment]
Hi folks - I wanted to give an update

@AlexeyBarabash, myself, and a few others are looking at this and there are a few problems we've identified. **For the time being, I would strongly recommend to turn OFF history sync**. If you are in a broken state, please note it can take up to 14 days for the server side to clean those records up- after that happens, you should be back in business. As a work-around, you can delete the sync chain and create a new one (making sure to have history sync off).

The problem is we have a hard limit on the number of sync objects. Before, history was only sending URLs that you typed into the URL bar. Now (since 1.61), it's sending all history URLs - which fills this number up quickly. When the maximum number of items is hit, the server side is returning `OVER_QUOTA` for each attempted update.  Kudos to @jonatan-ivanov for summarizing well in https://github.com/brave/brave-browser/issues/35042#issuecomment-1920066849 back in January.

Each object type doesn't have a hard limit. Meaning if you eat through all the objects with history, you can't sync the rest of the object types (even if you turn off history sync). When it fails, it's setting all the other types to `Backed off` and they will NOT be updated. Since no updates can be received, the person will be in a broken state.

You might be able to use the `Sync Node Browser` interface in brave://sync-internals to delete all the History objects. That should trigger an update to delete the server side and you should be in good shape. However, this disappears as soon as you stop syncing history and re-enabling history sync when you are OVER_QUOTA causes another bug 😭 

I'm working with the team on next steps. Thanks for your patience folks - and thanks for those who have helped collect information. This is definitely an important one for us to solve.

**Comment by dtantono** [comment]
I did that workaround by delete new sync chain and start new sync without History. But, I got this issue
<img width="306" alt="image" src="https://github.com/brave/brave-browser/assets/29157187/877ee3b5-6dfd-4de9-ab8e-5515c85ebd7e">

**Comment by AlexeyBarabash** [comment]
@dtantono 
this error looks as a conflict for `Sessions`/`Open Tabs` type.

Probably it appeared because the recovery procedure was disabled to investigate HTTP 504 error with 
 https://github.com/brave/brave-variations/pull/1032 . This recovery procedure is a workaround and not the correct fix because we could not reproduce the issue but had the feedback that the problem happens.
 
Advice for now is to turn off `Open tabs`  type and restart browser.

@dtantono could you please check the traffic log and write here what sync type was involved to that failed commit?

**Comment by dtantono** [comment]
@AlexeyBarabash it looks reboot my PC and restart the browser solves the issue. BTW, for disable history toggle solution for brave sync. It is just temporary workaround right?

**Comment by AlexeyBarabash** [comment]
@dtantono , yes this is a temporary workaround. we are working at these directions to solve it:
1. decrease history auto-expire period on server from 14 days now to 10 or 7 days. that can affect only those clients which are offline more than this period, they won't be able to fetch expired entries. 
2. consider to increase server objects limit from 85k to some  other value again.
3. make objects limit per-type, so when the history will reach the limit, other type still will work.

these options are discussed now.

**Comment by bsclifton** [comment]
OK folks - have a happy update 🙂

@DJAndries put together two patches:
- [Sync history count fix](https://github.com/brave/go-sync/pull/246)
- [Add history quota](https://github.com/brave/go-sync/pull/247)

The server side will delete records that are 14 days or older. However, the quota for folks was not adjusted to reflect this. The `Sync history count fix` pull request addresses this and should fix a subset of folks.

The second fix (`Add history quota`) adds a server side quota for History, limiting the # records allowed for History type to 26k. By limiting, this should prevent the situation where a TON of history eats up all the object storage. For example, if someone had 85k history entries, that would consume all of the available objects for a person. Now, history is limited to 26k so they have an additional 59k records available for the other types (bookmarks, passwords, etc). If the history limit is exceeded, the server won't error out and the other types will sync properly.

These two server-side changes should fix the majority of folks - please stay tuned. They are being deployed to staging now and will then be pushed to production soon after.

**Comment by NicholasYamamoto** [comment]
happy to see this getting resolved! My sync randomly started working tonight between my iOS and MacOS browsers so something good must be happening. 😄

**Comment by nfacha** [comment]
> OK folks - have a happy update 🙂
> 
> @DJAndries put together two patches:
> 
> * [Sync history count fix](https://github.com/brave/go-sync/pull/246)
> * [Add history quota](https://github.com/brave/go-sync/pull/247)
> 
> The server side will delete records that are 14 days or older. However, the quota for folks was not adjusted to reflect this. The `Sync history count fix` pull request addresses this and should fix a subset of folks. Because this fix is going to free up records, the quota is now lowered from 85k to 60k.
> 
> The second fix (`Add history quota`) adds a server side quota for History, limiting the # records allowed for History type to 26k. By limiting, this should prevent the situation where a TON of history eats up all the object storage. For example, if someone had 60k history entries, that would consume all of the available objects for a person. Now, history is limited to 26k so they have an additional 35k records available for the other types (bookmarks, passwords, etc). If the history limit is exceeded, the server won't error out and the other types will sync properly. We'll have follow up issues to display when limits are hit - I'm working with the team on that.
> 
> These two server-side changes should fix the majority of folks - please stay tuned. They are being deployed to staging now and will then be pushed to production soon after.

Hi

now the error is different:
![image](https://github.com/brave/brave-browser/assets/8540172/6931d8d2-d848-4f0b-9842-1b410b412517)

Along with this log:
```json
{
  "client_command": {
    "max_commit_batch_size": "90",
    "set_sync_poll_interval": "30"
  },
  "commit": {
    "entryresponse": [
      {
        "error_message": "Insert sync entity failed: error inserting sync item with client tag: TransactionCanceledException: Transaction cancelled, please refer cancellation reasons for specific reasons [ConditionalCheckFailed, None]\n{\n  RespMetadata: {\n    StatusCode: 400,\n    RequestID: \"QK8CPD2DCIJD9RLBSUSQE1AJBNVV4KQNSO5AEMVJF66Q9ASUAAJG\"\n  },\n  CancellationReasons: [{\n      Code: \"ConditionalCheckFailed\",\n      Message: \"The conditional request failed\"\n    },{\n      Code: \"None\"\n    }],\n  Message_: \"Transaction cancelled, please refer cancellation reasons for specific reasons [ConditionalCheckFailed, None]\"\n}",
        "response_type": "CONFLICT"
      },
      {
        "id_string": "f133bff6-77f3-4bbb-9a56-ac4ffed36443",
        "mtime": "1715684344569",
        "response_type": "SUCCESS",
        "version": "1715684344569"
      },
      {
        "id_string": "ed90ff28-e118-4311-9594-b9d7069e3b34",
        "mtime": "1715684344585",
        "response_type": "SUCCESS",
        "version": "1715684344585"
      },
      {
        "id_string": "8fa98461-8f7b-469f-a851-c998e62ea03a",
        "mtime": "1715684344590",
        "response_type": "SUCCESS",
        "version": "1715684344590"
      },
      {
        "id_string": "3ad5507a-2741-4688-a76f-1a34ddd9f50c",
        "mtime": "1715684344595",
        "response_type": "SUCCESS",
        "version": "1715684344595"
      },
      {
        "id_string": "9ebdf4a6-dafc-4bdf-98fb-d6079174948d",
        "mtime": "1715684344600",
        "response_type": "SUCCESS",
        "version": "1715684344600"
      },
      {
        "id_string": "+spp5KDEXftLb753Q9TxtE3eN5g=",
        "mtime": "1715684344604",
        "response_type": "SUCCESS",
        "version": "1715684344604"
      },
      {
        "id_string": "44G4cLavNKQ1qsC9Sm3DrAZRCGU=",
        "mtime": "1715684344611",
        "response_type": "SUCCESS",
        "version": "1715684344611"
      },
      {
        "id_string": "67RXhbqxJnJp0mLS0cEGb0PrAvk=",
        "mtime": "1715684344619",
        "response_type": "SUCCESS",
        "version": "1715684344619"
      },
      {
        "id_string": "BtfIib1eNa09ZwoHk0Ez3/dYqj0=",
        "mtime": "1715684344626",
        "response_type": "SUCCESS",
        "version": "1715684344626"
      },
      {
        "id_string": "E/FmfFxntEKuSE+rXEpB1SWy4aU=",
        "mtime": "1715684344633",
        "response_type": "SUCCESS",
        "version": "1715684344633"
      },
      {
        "id_string": "JxVe/CCOut7hbRM7cdoXC7zYZKA=",
        "mtime": "1715684344638",
        "response_type": "SUCCESS",
        "version": "1715684344638"
      },
      {
        "id_string": "LmIPRq5ITFdv73Go7RpchtbrP90=",
        "mtime": "1715684344644",
        "response_type": "SUCCESS",
        "version": "1715684344644"
      },
      {
        "id_string": "PliMcjxwY9SikXvLyJwFArJqnQY=",
        "mtime": "1715684344650",
        "response_type": "SUCCESS",
        "version": "1715684344650"
      },
      {
        "id_string": "Q3BEIuot+PtOv/YnZwjhQiaFLUM=",
        "mtime": "1715684344656",
        "response_type": "SUCCESS",
        "version": "1715684344656"
      },
      {
        "id_string": "Vx7uaZeQOj8MO0gECodhqsYCiZs=",
        "mtime": "1715684344664",
        "response_type": "SUCCESS",
        "version": "1715684344664"
      },
      {
        "id_string": "bYzwHTeg1nsk5RtckxL5OnV77fY=",
        "mtime": "1715684344671",
        "response_type": "SUCCESS",
        "version": "1715684344671"
      },
      {
        "id_string": "bz/lLZbQfnQoTMBHQjPmKE9aJAU=",
        "mtime": "1715684344677",
        "response_type": "SUCCESS",
        "version": "1715684344677"
      },
      {
        "id_string": "d2WsIK/fdZC0bUufMhbpJPjKLI4=",
        "mtime": "1715684344683",
        "response_type": "SUCCESS",
        "version": "1715684344683"
      },
      {
        "id_string": "mztIeh4yoLPLdG58jzjfiKFAIoY=",
        "mtime": "1715684344689",
        "response_type": "SUCCESS",
        "version": "1715684344689"
      },
      {
        "id_string": "yOWeljkzDWzA1yAV5xvCLuGYkVM=",
        "mtime": "1715684344696",
        "response_type": "SUCCESS",
        "version": "1715684344696"
      }
    ]
  },
  "error_code": "SUCCESS",
  "store_birthday": "1"
}
```

![image](https://github.com/brave/brave-browser/assets/8540172/1467200c-ead4-41b9-abde-8dfaa99765c6)

How can I figure out what data type is causing the conflict, or fix it?

**Comment by valynor** [comment]
@nfacha 
As mentioned above turning off syncing of the open tabs and restarting the browser fixes this (had the same issue today). 

But new problems started today: despite brave://sync-internals/ showing OK/all green and commits to sync apparently running normally HISTORY DOES NOT SYNC across devices. Sigh.

**Comment by bsclifton** [comment]
Hi folks - we did the update yesterday and as @nfacha noticed, you can get into an error state as it tries to repair. @AlexeyBarabash removed an experiment we had on our variations server that was disabling reset on commit failures - see https://github.com/brave/brave-variations/pull/1055

The easiest way to pick up that variations change is to exit Brave and relaunch. With that in place, a series of events will happen which get you into a good state 😄 I myself was in a bad state and used my profile for the troubleshooting. I ran into the conflict state too and then @AlexeyBarabash's change was merged ~13 hours ago.

Since there are many folks affected, our servers are taking some extra traffic and we're watching over them closely. As more folks get into the fixed state, things should cool down a bit.

@valynor for now, there is now a limit of 26k records for history allowed. We are working on longer term strategy to have soft limits in the client and to show warnings and errors as the limit gets approached. It should still sync across devices though. I would try to exit Brave and relaunch on all platforms and visit brave://sync-internals and give it a few cycles. Every 10 mins, it should update and eventually get into a good state.

**Comment by bsclifton** [comment]
There are too many individuals to tag - but anyone following along with this issue, please let us know how things are going!

Basically, I would recommend the following:
1. Exit Brave and relaunch on all platforms
2. Give each device about 30 minutes running Brave to try and sort itself out
3. Visit brave://sync-internals and report back - are things looking good there?

If you're in a bad state, you might see some red text under `Status from Last Completed Session` along with an error.

Please let us know! And thanks for your patience

**Comment by Saoiray** [comment]
@bsclifton definitely keeping an eye out and passing word here on the good news, hoping this is the solution for recent issues..

I do have one request as you guys are working on all of this. Would it be possible to implement some sort of notification or warning that will appear to users somewhere noticeable that might alert anyone if they are approaching objects limit on any type of sync criteria? Perhaps have it show objects synced vs object limit in the sync menu in Settings and not require people to think to go to sync-internals?

While we hope people won't hit that often, it would be great to have something for times when bookmarks, passwords, or whatever else might be reaching limits. And would want it to advise enough in advance that people can delete or export long before actually hitting limit and sync breaking.

**Comment by valynor** [comment]
Waiting for sync to fix itself definitely did not work here. 

- I just deleted the sync chain again (hey, I'm pretty proficient with that by now ;-) 
- I manually deleted the history from all devices but one 
- I created a new sync chain from the device with the history still enabled

... and NOW it is working again and syncing history, too.

**Comment by NicholasYamamoto** [comment]
Just wanted to report that Sync appears to be working still, however I'm still seeing a `Protocol error (CONFLICT)` when visiting `brave://sync-internals/`. I'll keep checking it periodically to see if it flips over. Thanks again team!

**Comment by nfacha** [comment]
> Just wanted to report that Sync appears to be working still, however I'm still seeing a `Protocol error (CONFLICT)` when visiting `brave://sync-internals/`. I'll keep checking it periodically to see if it flips over. Thanks again team!

Was having this, but left ot there for a while and it fixed itself

**Comment by valynor** [comment]
@bsclifton 
I'm sorry to say but the fix is no good. 

With the new sync chain that I made just 4 hours ago **history** syncing stopped working about 2 hours later. 
History gets synced to the same point on all devices and then just stops syncing both ways. 

Open tabs still sync within seconds but nothing from the history. 
brave://sync-internals/ are all green on all devices and show Status from Last Completed Session Sync Source | PERIODIC"
but no history gets synced. 

There is absolutely no way I ran into the 26k limit either.

**Comment by bsclifton** [comment]
@valynor thank you for the updates - I think the major problem is that a large amount of folks are hitting the servers at the same time.  We're seeing things stabilize over time - it should continue to get better as more people get fixed. We did push another fix - where timeouts would not adjust the count. Pushing this fix could have helped 😄

**Comment by valynor** [comment]
History sync is still working for me. I'll update in case that changes again. ;-)

**Comment by valynor** [comment]
@bsclifton 

Same thing as yesterday: 
- history sync worked for 2 hours and now it simply stopped at the same point in time across multiple devices
- "Status from Last Completed Session Sync Source | PERIODIC" / all green / OK on all devices but no new history data gets actually synced "GetUpdates Response Received 0 update(s)."

It's not working reliably.

**Comment by bsclifton** [comment]
@valynor history sync aside, how is sync working? Sounds like tabs from other devices is OK... how about the other types?

There is a limit of 26k history items - after that, it won't do new items. So that could very well be what you're running into

**Comment by valynor** [comment]
Update: since I last complained ;-) a week ago sync has been working flawlessly without any changes on my part.

**Comment by gurgunday** [comment]
Hey @bsclifton, thanks a lot for the updates, everything is working now!

Just a quick question, isn't Sync end-to-end encrypted? How does the server know to delete history entries older than 14 days? I guess it's just the metadata that isn't e2e encrypted, right?

Reference:
> The server side will delete records that are 14 days or older. However, the quota for folks was not adjusted to reflect this. The Sync history count fix pull request addresses this and should fix a subset of folks. Because this fix is going to free up records, the quota is now lowered from 85k to 60k.

**Comment by dtantono** [comment]
@gurgunday So, History sync also worked properly as well?

**Comment by bsclifton** [comment]
> Just a quick question, isn't Sync end-to-end encrypted? How does the server know to delete history entries older than 14 days? I guess it's just the metadata that isn't e2e encrypted, right?

@gurgunday sorry for the late response - great question. 

The entries themselves are client-side encrypted - meaning Brave has no way to see what's inside the object. We can tell what the object type is (ex: is it History? or Bookmark?) and when it was last modified. Being able to see the type and last modified is the only way we can clean these records up.

**Comment by bsclifton** [comment]
@valynor great to hear! Something we did do, which I failed to update here... was as things smoothed out on the server side (less errors w/ clients, servers getting hit less, etc) we started to increase the limits. We had lower limits and then gradually increased

Kudos to @DJAndries for that work! He can provide more information about that rollout if you have questions

Given the status here, I'm going to close this ticket. However, there are some follow ups we have planned on our side. I'll create some new GitHub issues and link them to this issue.

**Comment by dtantono** [comment]
@bsclifton I deleted the sync chain and recreated it again. But, it does not worked
<img width="375" alt="8AB4477B-1A0E-474F-BA84-6356E60A9EDA" src="https://github.com/brave/brave-browser/assets/29157187/384c0a59-00e5-499b-8aeb-fc6717b2c8d9">

**Comment by hamirmahal** [comment]
Are you on the latest version of Brave? What does it say at brave://version/?

**Comment by dtantono** [comment]
1.65

**Comment by dtantono** [comment]
it looks like I need to stay off from History sync atm.

**Comment by mrnooz** [comment]
In 2024, it happened to me three times that my PC lost synchronization on Brave. What could this be caused by?

**Comment by FrankRay78** [comment]
Happened to me today.  22 May 2025.  And periodically all through 2024.

**Comment by FrankRay78** [comment]
@valynor  agreed. Luckily it's just bookmarks I care about, so it's more annoyance than show stopper.  I can't imagine the backstory why it's still broken though, been a while.

**Comment by gracybird** [comment]
This is happening to me repeatedly on iOS 26. I just set up a new sync chain after deleting the old one entirely. I added my Mac, my PC and my iPhone and within 2 hours of zero use, my iPhone is saying to set up a new sync chain.

The primary feature I'm after here, and the one that will pull me from Safari for good, is tab syncing. I'm disappointed this is so broken.

**Comment by valynor** [comment]
@gracybird 

Sync is working fine for me since they last fixed it. Make sure to NOT sync history.

**Comment by gracybird** [comment]
That's not a fix, it's a workaround.

**Comment by valynor** [comment]
> That's not a fix, it's a workaround.

While true you can have it one of two ways: working perfectly without history or turn history sync on and it will break as soon as the data limit is reached. 

As you can see above I reported this bug 3 years ago and they made no effort to fix it yet.
