### ISSUE TITLE
Adjust border radius of website padding area on macOS

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#35040]
## Description 

Lukas brought to my attention that on MacOS at least, we have an issue with the border radius value of the content window.

This is is my bad, because I thought MacOS had a 8px window radius, but it's 10px. **So the inner radius has to be 6px**, not 4.

The math behind it is: 
Outer border radius value - Padding value = Inner border radius value.
10 - 4 = 6px.

<img width="1673" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/19fde1bd-97df-408d-aaea-e915581ef3cd">

**Comment by syedali237** [comment]
assign me this issue.
