### ISSUE TITLE
Expand dragbar area of Leo panel on Android

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#35041]
AI-panel is implemented in a custom tab which takes half of the screen.
It is possible to expand or collapse it either
1. by tap on drag handle button;
2. by pull the top border, "drag bar", which is thin and hard to reach with a finger, especially when the panel is expanded to the highest position.

It would be better to expand drag area to make it more comfortable for the work with it.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using version:

```
Brave	1.63.146 Chromium: 121.0.6167.139 (Official Build) beta (64-bit) 
Revision	cb9ee9c98182a64716e4237bf1202f1aec3bcff8
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured drag area is expanded for Leo panel. 
- Ensured user is able to expand/contract panel by dragging the top of the header.
- Ensured tapping on the bar in the panel header will expand the window automatically when minimized.
- Ensured dragging panel works when keyboard is shown. 

Example | Example | Example | Example | Example
-|-|-|-|-
![Screenshot 2024-02-06 at 1 04 15 PM](https://github.com/brave/brave-browser/assets/17885425/e68f61bc-85c0-493f-9ad5-122d0666250d) | ![Screenshot 2024-02-06 at 1 04 22 PM](https://github.com/brave/brave-browser/assets/17885425/c32f85be-72fb-4877-a4da-4b98152e9c56) | ![Screenshot 2024-02-06 at 2 32 54 PM](https://github.com/brave/brave-browser/assets/17885425/c5e97534-eb0a-48f9-8c64-366df8ebda87) | ![Screenshot 2024-02-06 at 2 33 01 PM](https://github.com/brave/brave-browser/assets/17885425/38358965-9597-43db-91b2-154c9a2c3ba2) | ![Screenshot 2024-02-06 at 2 37 45 PM](https://github.com/brave/brave-browser/assets/17885425/6046385c-e1c1-479a-bd68-7cf9a47e1896)
