### ISSUE TITLE
Fix NTP image attribution

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#3505]
The credit for this image should go to: https://www.instagram.com/ntgns/  with the name `Nout Gons` instead of SkyFolk.
![screen shot on 2019-02-26 at 16 02 58](https://user-images.githubusercontent.com/29072694/53455636-08867d80-39e0-11e9-9f88-94b3724a05ea.png)

**Comment by gaetan1903** [comment]
someone can give me link of the original picture please? or just path in my system?
