### ISSUE TITLE
Localization issue with 'Summarize this page' button in Leo chat

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#35057]
## Description 
Localization issue with  'Summarize this page' button in Leo chat

## Steps to reproduce 

Precondition: Set locale to English (UK) or English (IN)

   1. Enable `brave-ai-chat` flag in `Brave://flags`
   2. Open a webpage
   3. Enable `Leo` from the hamburger menu

## Actual result 

English (UK) | English (IN)
-|-
![image (4)](https://github.com/brave/brave-browser/assets/17885425/e63e67de-ef43-4edf-ac48-ba27b30a1997) | ![image (5)](https://github.com/brave/brave-browser/assets/17885425/82395667-2883-46c3-8029-adb70c642dce)

## Expected result
Should be 'Summarize`

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? N/A

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Any
   - Android version: 13
   
## Brave version
1.62.121

**Comment by nullhook** [comment]
<img width="423" alt="image" src="https://github.com/brave/brave-browser/assets/8665427/858d7785-71b4-4086-b81f-8c2327cf51dc">

this is fixed
