### ISSUE TITLE
`Unlock private` button color is not as per the design and lock icon is missing in the button 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#35056]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/29688
`Unlock private` button color is not as per the design and lock icon is missing in the button 
## Steps to reproduce 

   1. 
   2. 
   3. 

## Actual result 
![image](https://github.com/brave/brave-browser/assets/38657976/beacc175-e7cb-4b91-a369-c2558800e220)

## Expected result
As per the design https://github.com/brave/brave-browser/issues/29688#issuecomment-1520044924 the `Unlock private` button color is not orange

![image](https://github.com/brave/brave-browser/assets/38657976/d5b83ce2-3209-491e-b604-4ef002ea45f5)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Not sure

## Device details
   - Install type (ARM, x86):all
   - Device type (Phone, Tablet, Phablet):all
   - Android version: 12
   
## Brave version

1.62.121
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @deeppandya @samartnik

**Comment by GeetaSarvadnya** [comment]
Also `See other tabs` text color is not as per the design https://github.com/brave/brave-browser/issues/29688#issuecomment-1520044924

cc: @samartnik

**Comment by samartnik** [comment]
@GeetaSarvadnya the orange color is the old one, new colors are in the spec here https://www.figma.com/file/6KPhbe8yqCPOLgFT2AYlju/Private-nav---Application-lock?node-id=1%3A2&t=akjs30qOI2MTM5UX-1

**Comment by samartnik** [comment]
Also note that we simplified that task in favor of this one where the complete overhaul will be done https://github.com/brave/brave-browser/issues/33949
