### ISSUE TITLE
Google Maps loads with WebGL error, apparently random shapes on screen

### ISSUE THREAD

**Issue by rogerdc** [brave/brave-browser#35065]
## Description 

When loading Google Maps on my Linux (Debian) desktop, the default view appears for a few moments, and then a console message is logged: 

```
[.WebGL-0x32a0082e9400] GL_INVALID_OPERATION: Feedback loop formed between Framebuffer and active Texture.
```
with a reference to [the downloaded script from the main page](https://www.google.com/maps/@33.4066696,-86.7315686,15z?entry=ttu) line 1. Following that into the source file, I don't see it highlighted exactly where the error occurs. 

After the console message is logged, the screen changes to a bunch of apparently random shapes that are probably related to the location, but I can't make heads or tails of it: 

![FireShot Capture 042 - Google Maps - www google com](https://github.com/brave/brave-browser/assets/4684857/29713697-3af0-4b86-9bb9-08fcca77b640)

Here is a HAR file of the load: 

[googlemaps.har.gz](https://github.com/brave/brave-browser/files/13790027/googlemaps.har.gz)

## Steps to Reproduce

   1. In a private window with devtools  open, load [https://www.google.com/maps/@33.4066696,-86.7315686,15z?entry=ttu](https://www.google.com/maps/@33.4066696,-86.7315686,15z?entry=ttu)

## Actual result:
See above description.

## Expected result:
Google Maps loads legibly and correctly.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave	1.61.109 Chromium: 120.0.6099.144 (Official Build) (64-bit) 
Revision	ea6e204b94e25f08d7a80301c88ba8d2bf96502f
OS	Linux

## Version/Channel Information:
Unknown. I could not reproduce this on MacOS.

## Other Additional Information:

- Is the issue reproducible on the latest version of Chrome? 

No

## Miscellaneous Information:

N/A

**Comment by rogerdc** [comment]
After a few system updates, this has resolved. Not sure which one did it.

**Comment by bsclifton** [comment]
Thanks for updating @rogerdc - not sure what happened 🤔 Might be driver related? 

The screenshot you shared with the shapes is wild!

**Comment by ramadhanafif** [comment]
Happens again with me. 

OS: Fedora 39. 
Brave: Version 1.61.116 Chromium: 120.0.6099.217 (Official Build) (64-bit).

On the console it also says the same thing about WebGL error. The error also persist on private window, without any browser extension.

**Comment by edufc** [comment]
I had this problem until update my version to 1.62.153 Chromium: 121.0.6167.85
