### ISSUE TITLE
Support text extraction via screenshots for Leo (Google docs support)

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#35069]
For getting page contents, Leo is not always great :-1:

This issue is to add a method which gets past issues of multiple iframes, images within a page, and also canvas based rendering (such as what Google docs and Google sheets does)

It works by first taking a screenshot of the visible tab and then uses text recognition to extract the text.
It then feeds that text into Leo

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.63.134 Chromium: 121.0.6167.85 (Official Build) beta (64-bit)
-- | --
Revision | cdcba6ef408b305ce19b1a9b3fabbb5e9e3b36bf
OS | Windows 11 Version 23H2 (Build 22631.3085)
```

1. Installed 1.63.164
2. launched Brave using --env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev --enable-logging=stderr --v=2
3. loaded a Google Doc
4. clicked on Leo in the sidebar
5. clicked on `Summarize this page`
6. clicked on `Accept and begin`
7. clicked `Suggest questions`
8. queried couple of questions eg. `Surprise`

#### Confirmed Leo had summarized correct information from the Google Doc

**_Google_**

example | example | example 
----- | ------ | -----
![image](https://github.com/brave/brave-browser/assets/98358127/8975b137-dd29-4136-95c0-fc6933777800)|![image](https://github.com/brave/brave-browser/assets/98358127/c3747890-2e84-4705-b965-aebbe7980c94)|![image](https://github.com/brave/brave-browser/assets/98358127/5ce5d04d-eed7-4dff-a5cd-31f9c673dd48)


**_Twitter_** 
Did the same for Twitter post https://twitter.com/lukemulks/status/1748060018942026195

1.63.164 | 1.62.153
--- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/6b3badcc-0469-41a0-97c6-91e0f10ca556)|![image](https://github.com/brave/brave-browser/assets/98358127/0327de2d-af64-4264-aae6-6e572fd020b3)


**_Google sheets_**

1.63.164 | 1.62.153
--- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/207ce83f-5408-4738-bb4c-44924774a013)
![image](https://github.com/brave/brave-browser/assets/98358127/e61ff5af-5d02-4044-88f4-9517badcec5d)

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.63.138 Chromium: 121.0.6167.85 (Official Build) beta (x86_64)
-- | --
Revision | 742a3bdf71b710125a1c1dd8e89981b9009a87bc
OS | macOS Version 11.7.10 (Build 20G1427)
```

`Google Docs`

`Google Sheets`

`Twitter`

**Comment by stephendonner** [comment]
Apologies, removing `QA/Test-All-Platforms` as I had erroneously added it, forgetting that `linux` isn't-yet supported, per https://github.com/brave/brave-core/pull/21470#issue-2060259455.

**Comment by bbondy** [comment]
I guess for Linux you could test just that it doesn't crash and works like it used to

**Comment by stephendonner** [comment]
> I guess for Linux you could test just that it doesn't crash and works like it used to

Thanks, @bbondy - I considered that and can and will do; want the label restored, or just a verification on `linux`?  Or both? 😁

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```

```

<img width="1654" alt="Screen Shot 2024-02-08 at 12 01 50 AM" src="https://github.com/brave/brave-browser/assets/387249/c048794e-8ed5-4f25-bc96-cf5d90c8e0d0">
<img width="1654" alt="Screen Shot 2024-02-08 at 12 01 54 AM" src="https://github.com/brave/brave-browser/assets/387249/b41abe61-7747-4d75-8b0f-504c6e15e659">
<img width="1654" alt="Screen Shot 2024-02-08 at 12 03 34 AM" src="https://github.com/brave/brave-browser/assets/387249/e663c63d-ea9b-49a9-a651-4a7918a2189f">
<img width="1654" alt="Screen Shot 2024-02-08 at 12 04 01 AM" src="https://github.com/brave/brave-browser/assets/387249/bd7bebc2-8467-49e8-8c69-34999bd9a182">
<img width="1654" alt="Screen Shot 2024-02-08 at 12 10 15 AM" src="https://github.com/brave/brave-browser/assets/387249/986f8362-ef72-4b27-9a9f-439465cb38e9">
<img width="1654" alt="Screen Shot 2024-02-08 at 12 11 04 AM" src="https://github.com/brave/brave-browser/assets/387249/8c3bdd62-6a6f-4a79-b122-4ae8d8314f36">
<img width="1654" alt="Screen Shot 2024-02-08 at 12 11 30 AM" src="https://github.com/brave/brave-browser/assets/387249/f62a079d-ae06-40fb-974c-3d24a662ad62">
<img width="1654" alt="Screen Shot 2024-02-08 at 12 11 36 AM" src="https://github.com/brave/brave-browser/assets/387249/5ce877da-f7b7-43c3-b051-381edb41d49d">
<img width="1654" alt="Screen Shot 2024-02-08 at 12 11 53 AM" src="https://github.com/brave/brave-browser/assets/387249/8ee48ac9-ed5f-4108-8bee-897fe01972ea">


---
