### ISSUE TITLE
Address bar shows incomplete list of URL history

### ISSUE THREAD

**Issue by marceljay** [brave/brave-browser#35063]
## Description 
Whenever trying to find a resource that i've access a few days before, it seems like I have to be lucky for Brave to actually show me the URL. 
I suppose there is some filtering mechanism to not overload the UI with hundreds of results, but this is opinionated and not clear based on what metrics results are shown. So even when a resource has been visited multiple times during the past 30 days, it's sometimes not shown. This is annoying and confusing.

## Steps to Reproduce
   1. Visit a lot of sites to fill your history
   2. find some random urls in your history e.g. via `brave://history/?q=exampleTerm`
   3. Type the same term (`exampleTerm`) into the address bar and see if you get the same amount of results.

## Actual result:
<img width="762" alt="image" src="https://github.com/brave/brave-browser/assets/37071670/44dd1773-b713-48a2-9c08-58bea830b1ec">

## Expected result:
Should include all 22 results. 
Or at least there should be a setting specifying the amount of matches shown and filter rules.

## Reproduces how often: 

Intermittent / Always happening

## Brave version (brave://version info)

1.61.109 Chromium: 120.0.6099.144 (Official Build) (arm64) 
Revision: ea6e204b94e25f08d7a80301c88ba8d2bf96502f
macOS Version 14.2.1 (Build 23C71)

**Comment by rebron** [comment]
cc: @fallaciousreasoning @aguscruiz

**Comment by fallaciousreasoning** [comment]
Big :+1: from me. This drives me insane :laughing:

**Comment by fallaciousreasoning** [comment]
@marceljay I've found a big chunk of the cause it that only titles from the last 3 days are searched - I'm experimenting with increasing this to see whether it's more useful.

**Comment by fallaciousreasoning** [comment]
In latest Nightly, if you flip the brave://flags/#brave-history-more-search-results flag would you mind letting me know if it's improved for you?

It's definitely not as good as Firefox, but I actually get some history results now :laughing: If you've got any suggestions for further improvements, I'd love to hear!

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.64.94 Chromium: 122.0.6261.94 (Official Build) beta (x86_64)
-- | --
Revision | 866e3a4bd76c9cc1762928df0cf9a53b8685ab71
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.64.94`
2. renamed `Brave-Browser-Nightly` profile folder to `Brave-Browser-Beta`
3. launched Brave
4. typed `starbucks` into the URL bar, and confirmed only a few matches
5. flipped `brave://flags/#brave-history-more-search-results` to `Enabled` and restarted Brave
6. typed `starbucks` into the URL bar

### Confirmed "new" `starbucks` matches from March 1st

example | example | example | example | example
---------|---------|----------|---------|----------
<img width="1905" alt="Screen Shot 2024-03-05 at 11 44 10 AM" src="https://github.com/brave/brave-browser/assets/387249/a7cf084c-9d85-4493-b7cd-74dfd1f206c7"> | <img width="1905" alt="Screen Shot 2024-03-05 at 11 44 26 AM" src="https://github.com/brave/brave-browser/assets/387249/b54c8923-834c-4602-ac05-2e9c233fd92c"> | <img width="1588" alt="Screen Shot 2024-03-05 at 11 45 03 AM" src="https://github.com/brave/brave-browser/assets/387249/d8296450-8c98-4c86-ae53-7bdf738c9c6c"> | <img width="1588" alt="Screen Shot 2024-03-05 at 11 45 23 AM" src="https://github.com/brave/brave-browser/assets/387249/f8965f26-0f52-4ba3-83aa-3dc0fd54b547"> | <img width="1588" alt="Screen Shot 2024-03-05 at 11 46 19 AM" src="https://github.com/brave/brave-browser/assets/387249/20390be3-a22a-4e8c-bdae-99e425b9dea3">

**Comment by stephendonner** [comment]
@fallaciousreasoning @rebron  do we plan on flipping this flag to `Enabled`?

**Comment by stephendonner** [comment]
> I wouldn't be opposed - I think it might be on by default in Nightly, but I don't remember.

It's actually `Default (Disabled)` there too.

**Comment by fallaciousreasoning** [comment]
Ah okay, maybe I'll enable it via Griffin then

**Comment by marceljay** [comment]
Sweet, thanks for prioritising this. 
Any idea when it will come to stable from nightly?

**Comment by fallaciousreasoning** [comment]
Hopefully the flag will be in stable soon (it's in 1.64), but won't be enabled by default for a while.

**Comment by jhult** [comment]
@fallaciousreasoning, @rebron - any news on enabling this by default?

**Comment by therightstuff** [comment]
i've been struggling with this for ages! i just found this thread now for the first time, is there any chance of it being enabled by default / being added to the settings?

**Comment by fallaciousreasoning** [comment]
cc @rebron wdyt? I think this is a much better default
