### ISSUE TITLE
Wallet panel from manages wallet page history multiple times per render

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#35062]
## Description 

The wallet panel container is trying to initialize and handle the wallet session routes when this is also handled by the page container (which can also be rendered by the panel) remove this logic to prevent unexpected router behavior

## Steps to Reproduce

   1. Viist a page in the wallet panel
   2. close the panel

## Actual result:

The panel sometimes alters persisted page URLs differently than the main wallet page

## Expected result:
The panel should return to the opened page (excludes "panel" specific views (signing, pending transactions, switching chains, selecting accounts for site connections)

## Reproduces how often: 

Intermittent

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.102 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | c9343c77bd5dee3524fc45f89721ce0bf4c09b8d
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from issue description
- Verified panel retains the previous view when close and open states

https://github.com/brave/brave-browser/assets/17010094/1702cf84-1683-4d67-a73a-94c3f78bc14d
