### ISSUE TITLE
“Your request is still being processed, please wait. Sorry there was a problem processing your request, please try again.”

### ISSUE THREAD

**Issue by brighterlemons** [brave/brave-browser#35064]
On attempt to connect your wallet to Brave, you get a pop up “Your request is still being processed, please wait.
Sorry there was a problem processing your request, please try again.”.

   1. Install Brave
   2. Attempt brave to uphold link
   3. Brave returns this error 

![image](https://github.com/brave/brave-browser/assets/67809463/bf487f27-ae09-4310-b238-bc0282dd3ed8)

easily reproduce 100% of the time

	1.61.109 

This happens on every channel

I tried on all three channels 

I disabled Brave shields, but it did not get fixed

**Comment by bsclifton** [comment]
cc: @brave/rewards-support

**Comment by Miyayes** [comment]
If this was when you were trying to log in or connect to Uphold, this has since been resolved. Please try again, thanks!
