### ISSUE TITLE
Native asset transfers are not shown in portfolio asset details screen

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#35068]
## Steps to Reproduce

   1. Send SOL
   2. go to the activity page (the transaction is visible)
   3. go to the SOL asset details page
   4. click transactions tab

## Actual result:

Transaction is not visible

## Expected result:
Transaction should be visible

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

https://github.com/brave/brave-browser/assets/30185185/b2bbf278-0327-479f-ab20-865c1d6bed08

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.159 Chromium: 122.0.6261.57 (Official Build) (64-bit)
-- | --
Revision | 118f746822a0acc7abc8c48993a704fcd0e29122
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from issue description
- Verified native asset transfers are shown in portfolio asset details screen
- Verified transfers are shown on both wallet page and panel

https://github.com/brave/brave-browser/assets/17010094/d679fdbb-7357-4cf9-b61c-dcfb460ab396
