### ISSUE TITLE
Channels are not populated in Brave News dialog after enabling news

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#35071]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/34593.  After enabling news,  Channels are not populated except for `Top sources`.  Had to follow a publisher before all channels are populated. 

## Steps to Reproduce

   1. Install 1.62.123
   2. launch Brave
   3. click `Customize` button
   4. click `Brave News`
   5. click `Turn on Brave News` 

   
## Actual result:

Channels are not populated.  However, channels are loaded after following a publisher

Example | Example 
---- | -----
<img width="952" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/dd57cb53-5fc5-489c-91e3-ab3017ccd842">|<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/521269bf-5ccb-4cce-b91a-e81ec1d04365">

## Expected result:
Channels should be populated after enabling news. 
<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f29db334-1541-45ba-a8ab-e965004eb292">

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.62.124 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | d281285150cedd393f665d2b99e12cb0e62ae12a
OS | Windows 11 Version 22H2 (Build 22621.2861)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@fallaciousreasoning @LorenzoMinto 
cc: @stephendonner @rebron

**Comment by kjozwiak** [comment]
The above requires `1.62.131` or higher for `1.62.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.62.131 Chromium: 120.0.6099.199 (Official Build) beta (x86_64)
-- | --
Revision | 217e8080b48df17845efb3c1a80433a8028978de
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Followed the original STR and confirmed the fix (the screencast here shows slightly different, as there are multiple paths)



![channels-populated](https://github.com/brave/brave-browser/assets/387249/6e6f451c-4d54-4451-a36f-235331cae2d4)
