### ISSUE TITLE
my brave Crash Report

### ISSUE THREAD

**Issue by itssamuelll** [brave/brave-browser#35074]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.109 Chromium: 120.0.6099.144
Operating System: Mac OS X 14.3.0

URL (if applicable) where the crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. basic like watching youtube
2. browsing
3. happens so frequently i switched to opera gx 

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/0d5a1400-a543-390b-0000-000000000000

**Comment by Wizjonero** [comment]
I'm having this issue too and it's driving me nuts. Brave works perfectly fine on my 2021 MacBook Pro with Sonoma, but crashes randomly every 10-30 minutes on also Sonoma but '23 MBP
