### ISSUE TITLE
Ads should be opened in a new tab as a default along with Brave news articles

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#35070]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/34593.  As a default, Brave news articles and Ads should be opened in a new tab.  Currently, when articles are clicked, they are opened in a new tab but Inline Ads are opened in the same tab.  

## Steps to Reproduce

   1. Install 1.62.123
   2. launch Brave
   3. click `Customize` button
   4. click `Brave News`
   5. click `Turn on Brave News`
   6. navigate to inline ad in the feed
   7. click the ad 
## Actual result:

Ad opened in the same tab though the default is to open a new tab

Example | Example 
---- | -----
 <img width="952" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9da2b6e2-6937-4145-aea2-7c1492fa524e">|<img width="954" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/20d8815a-0f04-4991-a8a9-1f803108ebd5">

## Expected result:
Ads should open in new tab along with the news articles.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.62.124 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | d281285150cedd393f665d2b99e12cb0e62ae12a
OS | Windows 11 Version 22H2 (Build 22621.2861)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@fallaciousreasoning @LorenzoMinto 
cc: @stephendonner @rebron

**Comment by kjozwiak** [comment]
The above requires `1.62.131` or higher for `1.62.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.62.131 Chromium: 120.0.6099.199 (Official Build) beta (x86_64)
-- | --
Revision | 217e8080b48df17845efb3c1a80433a8028978de
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Open articles in new tab - `PENDING`

### Open articles in current tab - `PENDING`

**Comment by stephendonner** [comment]
Gonna `QA/All-Platforms` this one, because more eyeballs == better

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.62.131 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | 217e8080b48df17845efb3c1a80433a8028978de
OS | Windows 11 Version 22H2 (Build 22621.2861)
```

Verified using STR from the description. 

#### Confirmed Ad opened in new tab as a default.


Brave news dialog | Brave news feed Ad | Ad opened in a new tab | News article opened in a new tab
-------- | -------- | -------- | ---------
<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a749dd7c-f6c9-49f0-89bf-01e1fe1e8b79">|<img width="954" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/4cce0da4-42e1-4ba7-928c-46e8052a5efb">|<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/cfd39a84-d791-4a41-90b3-67f004b129b2">|<img width="952" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/7aa8410e-97f0-465d-b02d-8145094e89db">

Brave news dialog | Brave news feed Ad | Ad opened in a new tab | News feed | News article opened in a new tab
-------- | -------- | -------- | --------- | --------
<img width="963" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/968fdb79-2624-4426-a07a-6ec14cfc6c04">|<img width="954" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/428bbdc9-ea80-4f08-bc86-dba2961f3777">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/04ffaa37-c272-4db1-bd54-61ca04227b8e">|<img width="963" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/62b5dc65-ca24-41d4-babd-8ecbc8e167fa">|<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6c1b2865-a8dc-4b68-adfe-849ea5f7406b">

**Comment by btlechowski** [comment]
Verified with

Brave | 1.62.135 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | c66fd7306403245e6c370da9f287f69a5cf46a10
OS | Linux

### Open articles in new tab - `PASSED`
<details>

Verified opening articles in new tab is selected

![image](https://github.com/brave/brave-browser/assets/34715963/641a6630-988b-4c47-b0d7-5ea419efa5c1)


Confirmed the `Ad` opened in a new tab
![image](https://github.com/brave/brave-browser/assets/34715963/9c3ef7c3-b814-4704-986a-7ff1b30a99c0)


Verified click confirmation was successfully redeemed
```
[9983:9983:0110/134151.935469:VERBOSE1:redeem_non_reward_confirmation.cc(106)] Successfully redeemed non-reward click confirmation for inline_content_ad with transaction id f5d156d0-2d3f-4c00-85cd-25a04a8044ab and creative instance id 22110568-4125-4b84-b97a-27ef45c5c07c
```

Verified landed confirmation was successfully redeemed
```
[9983:9983:0110/134157.072168:VERBOSE1:redeem_non_reward_confirmation.cc(106)] Successfully redeemed non-reward landed confirmation for inline_content_ad with transaction id d3596d2b-da3e-4431-8675-8b071d174f57 and creative instance id 22110568-4125-4b84-b97a-27ef45c5c07c

```

Clicking again on the same ad does not sent the confirmation:
```
[9983:9983:0110/134325.150605:VERBOSE1:inline_content_ad_event_handler.cc(118)] Inline content ad: Not allowed as debounced kClicked event for placement id 6fa96b5d-ce1c-4846-ba6e-b26888cc3a91
[9983:9983:0110/134325.151120:VERBOSE1:inline_content_ad_event_handler.cc(163)] Failed to fire inline content ad kClicked event for placement id 6fa96b5d-ce1c-4846-ba6e-b26888cc3a91 and creative instance id 22110568-4125-4b84-b97a-27ef45c5c07c
```

</details>

### Open articles in current tab - `PASSED`
<details>

Verified opening articles in current tab is selected

![image](https://github.com/brave/brave-browser/assets/34715963/897ceb53-56e1-4473-b131-cd54fe0ffdda)


Confirmed the `Ad` opened in the current tab
![image](https://github.com/brave/brave-browser/assets/34715963/8fada2d4-3328-45d9-82ba-5ec69678efca)|![image](https://github.com/brave/brave-browser/assets/34715963/a5733644-122e-4104-bc70-75f97629e4e9)
--|--

Verified click confirmation was successfully redeemed
```
[9983:9983:0110/134915.491006:VERBOSE1:redeem_non_reward_confirmation.cc(106)] Successfully redeemed non-reward click confirmation for inline_content_ad with transaction id 2538d722-61c9-4090-966f-692de6d196d5 and creative instance id 211a9ff9-48bf-4b79-bd2a-f6b450edac0a

```

Verified landed confirmation was successfully redeemed
```
[9983:9983:0110/134927.238993:VERBOSE1:redeem_non_reward_confirmation.cc(106)] Successfully redeemed non-reward landed confirmation for inline_content_ad with transaction id f3131560-387d-43c6-ab6c-d37753410b96 and creative instance id 211a9ff9-48bf-4b79-bd2a-f6b450edac0a

```
</details>

**Comment by stephendonner** [comment]
Thanks for adding the `Ad`-logging and verification, @btlechowski <3
