### ISSUE TITLE
Retry button on Rewards connect wallet error modal not working

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#35072]
## Description 

The "Retry" button on the Rewards connect wallet error modal is not working; it simply closes the modal without retrying the login process.

## Steps to Reproduce

   1. Attempt to connect to an external wallet provider.
   2. When the user is directed back to the Rewards page, ensure that an error is displayed.
   3. Press the "retry" button.

## Actual result:

The modal is hidden.

## Expected result:

The user should be redirected to the wallet provider's login page.

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

Beta (1.62)

**Comment by kjozwiak** [comment]
Thanks @LaurenWags 👍 Sounds like `1.62.x` & `1.63.x` were the only affected versions. Was checking to see if we needed to get the above into the next `1.61.x` release.

**Comment by kjozwiak** [comment]
The above requires `1.62.138` or higher for `1.62.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.62.144 Chromium: 120.0.6099.217 (Official Build) beta (x86_64)
-- | --
Revision | 75de8d953f6a5686e425d46d7f0dc9284dc1c064
OS | macOS Version 13.6.3 (Build 22G436)
```

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP11.231215.007 release-keys
Brave build: 1.62.146
Chromium: 120.0.6099.234 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Setup Charles Proxy to simulate a 500 error being returned from the `https://grant.rewards.bravesoftware.com/v3/wallet/uphold/*/claim` endpoint
2. Launch a clean profile (using staging env)
3. Close and relaunch to pull griffin
4. Join `Rewards`
5. Attempt to connect `Uphold` account
6. See generic error
7. Select "Try again"
8. Remove the Charles Proxy rule
9. Select "Try again"

**ACTUAL RESULTS:**
- Verified that the attempt was retried (page navigated back to Uphold for re-attempt, then back to `brave://rewards` and showed an error again)
- Verified that the attempt was retried (page navigated back to Uphold for re-attempt, then back to `brave://rewards` and was successful this time)

---------------------------

https://github.com/brave/brave-browser/assets/128532965/d8b4a7a2-9f71-4699-b5bd-61c4c6c01de7
