### ISSUE TITLE
WebUI doesn't update correctly when two options are selected 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#35086]
## Description 
WebUI doesn't update correctly when two options are selected 

## Steps to reproduce 

   1. Create/Restore wallet
   2. Open Wallet and select Swap
   3. Ensure Swap WebUI is shown in a new tab
   4. Go back to wallet and select Send/Deposit
   5. Opens Send/Deposit WebUI in a new tab
   6. Go back to wallet and select Swap again
   7. Switches back to Swap tab but retains Send/Deposit UI but wallet route is showing Swap
   8. Close all tabs and open Deposit, opens in a new tab
   9. Select Swap from wallet, opens in new tab
   10. Go back to wallet and select Deposit
   11. Switches back to deposit tab but retains Swap WebUI

## Actual result 

https://github.com/brave/brave-browser/assets/17010094/5f78f04e-c1f1-4130-8e3d-3bd1b395de06

## Expected result
Should show the correct WebUI

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe

**Comment by simoarpe** [comment]
This issue should be fixed on the latest Brave nightly (1.63.x) for Android. 
@srirambv can you please try again using that version?

**Comment by srirambv** [comment]
Verified this is not an issue on nightly anymore. Closing as invalid
