### ISSUE TITLE
getAllAccounts Method is not returning an address for Bitcoin Accounts

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35089]
## Description 

The `keyringService.getAllAccounts()` method is returning an empty `""` for both `address` fields for `Bitcoin` accounts.

![Screenshot 21](https://github.com/brave/brave-browser/assets/40611140/383494dd-68e1-4a4d-ae28-4a8d940908a3)

**Comment by supermassive** [comment]
@Douglashdaniel 
There is no such thing as an `address` for bitcoin account. It there some bigger problem we need to solve by having an address?
