### ISSUE TITLE
[Leo] Change Leo icon to new one where needed

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#35087]
We need to update Leo's icon to the new one in all places:

<img width="795" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/a1cf953b-0e1e-4e12-88eb-591cc129564c">

-------------------------------

Wondering if this change would be easy by just importing the new versions of icons into Nala 👇. 

```[tasklist]
### Desktop
- [x] Change in sidebar https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=347%3A19952&mode=design&t=0YEt9nHKfZSWLrju-1
- [x] Change in omnibar
- [x] Change in sidepanel contents:
  - [ ] Avatar bubble
  - [ ] Product header menu
```
-------------------------------
```[tasklist]
### Android
- [x] Browser menu https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Leo-MVP?type=design&node-id=2839%3A45816&mode=design&t=nxXVEVTKq9S84nAG-1
- [x] Chat bubble avatar https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Leo-MVP?type=design&node-id=3628%3A95252&mode=design&t=nxXVEVTKq9S84nAG-1
- [x] Paywall background icon https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Leo-MVP?type=design&node-id=5374%3A90858&mode=design&t=nxXVEVTKq9S84nAG-1
```
-------------------------------
```[tasklist]
### iOS
- [x] Browser menu https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Leo-MVP?type=design&node-id=3459%3A51890&mode=design&t=nxXVEVTKq9S84nAG-1
- [x] Chat bubble avatar https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Leo-MVP?type=design&node-id=5087%3A77980&mode=design&t=nxXVEVTKq9S84nAG-1
- [x] Paywall background icon https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Leo-MVP?type=design&node-id=5374%3A91228&mode=design&t=nxXVEVTKq9S84nAG-1
```
-------------------------------
```[tasklist]
### Websites
- [x] Change in account pages (product icon) https://www.figma.com/file/XV4j13TSqvau3D8dldn8CS/Accounts-page-redesign?type=design&node-id=183%3A50918&mode=design&t=L0DGk0V4JuobLrk9-1
- [x] Change in product page
```

**Comment by bridiver** [comment]
why is this assigned to me?

**Comment by aguscruiz** [comment]
> why is this assigned to me?

I must've selected the wrong person from the dropdown! Sorry :D

**Comment by mattmcalister** [comment]
@aguscruiz now that 1.64 is out will you review and check for any outstanding missing items?

**Comment by aguscruiz** [comment]
@mattmcalister I'm still seeing the old one in the Omnibar on desktop 
<img width="1049" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/bf3674a2-579e-4b19-9c97-1b918897bdee">

**Comment by aguscruiz** [comment]
Everywhere else looks good, haven't found another instance of the old icon

**Comment by aguscruiz** [comment]
@petemill 

We still have the old icon in there 👁️👄👁️

![image](https://github.com/brave/brave-browser/assets/15734630/94b04cbf-efdc-4fc7-8597-a652ff3d29d6)

**Comment by aguscruiz** [comment]
@sangwoo108 could we fix this soon? It's the bane of my existence 😂

**Comment by sangwoo108** [comment]
> @sangwoo108 could we fix this soon? It's the bane of my existence 😂

Sure, could you give me a figma link?

**Comment by aguscruiz** [comment]
Sure, https://www.figma.com/design/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?node-id=1386-11575&t=Q9ZdgwI4hi2EzrHQ-1

Tagged you in a comment for the location

**Comment by aguscruiz** [comment]
Complete!
