### ISSUE TITLE
How To Add Primary Password To Protect Password Manager On Linux/Ubuntu

### ISSUE THREAD

**Issue by terlan4** [brave/brave-browser#35082]
Sorry, I have to share this one again since previous one is closed since it is implemented in someway, but how can I use it properly tho, there is no feature like that?

Passwords on Linux are easily accessible without any protection. We can not set protection against "viewing, editing, deleting, copying passwords". 

I am using Ubuntu and as you can see there is no feature related "primary password" like you can see on windows and mac. Please share a guide on how to properly set it up so that we can have primary password.
![image](https://github.com/brave/brave-browser/assets/138553763/665979fc-04c6-4de7-b213-fabb39a980d6)

**Comment by diracdeltas** [comment]
cc @fmarier

**Comment by fmarier** [comment]
That feature is not yet available: https://github.com/brave/brave-browser/issues/13350
