### ISSUE TITLE
Loading indicator should be gray for Brave news

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#35093]
## Description 

https://github.com/brave/brave-browser/issues/34593.  Load indicator shows blurple instead of gray. 

## Steps to Reproduce

   1. Install 1.62.128
   2. launch Brave
   3. complete onboarding
   4. click `Turn on Brave News`
    
## Actual result:

Loading indicator shows gray
<img width="954" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a8cc96e2-9a44-4aa9-81d5-f6c270898b13">

## Expected result:
Should be gray 

## Reproduces how often: 

Easily 

## Brave version (brave://version info)

```
Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | 41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6
OS | Windows 11 Version 22H2 (Build 22621.2861)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@fallaciousreasoning @LorenzoMinto 
cc: @stephendonner @rebron

**Comment by stephendonner** [comment]
cc @martin-c0des

**Comment by kjozwiak** [comment]
The above requires `1.62.131` or higher for `1.61.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.62.131 Chromium: 120.0.6099.199 (Official Build) beta (x86_64)
-- | --
Revision | 217e8080b48df17845efb3c1a80433a8028978de
OS | macOS Version 11.7.10 (Build 20G1427)
```

Followed provided steps

### Confirmed content-loading indicator is now `gray`, rather than `blurple`

<img width="1906" alt="Screen Shot 2024-01-05 at 1 31 45 AM" src="https://github.com/brave/brave-browser/assets/387249/b3618a6f-37f6-4958-a515-e1b42b5206f5">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.62.131 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | 217e8080b48df17845efb3c1a80433a8028978de
OS | Windows 11 Version 22H2 (Build 22621.2861)
```

Verified with original STR from the description

#### Confirmed content-loading indicator is now gray, rather than blurple

![image](https://github.com/brave/brave-browser/assets/98358127/81e0026e-2cb6-4b9e-93ed-cae69a893763)
