### ISSUE TITLE
Bookmarks are synced when not connected to sync chain

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3509]
Found when verifying https://github.com/brave/brave-browser/issues/3225

## Steps to Reproduce

1. Create sync chain brave-core device1
2. Connect to sync chain brave-core device2
3. Create bookmark on device1 and ensure it is synced to device2
4. Copy sync codes from device1
5. On device2 press `Leave Sync Chain`
6. Wait until both devices will get sync turned off
7. Try to sync brave-core device3 with sync codes from 4.

## Actual result:

bookmark is synced, even though joining sync chain fails.

On device3:
![sync fail](https://user-images.githubusercontent.com/34715963/53458342-fa634c00-3a35-11e9-8db4-b34c94f9b128.gif)

## Expected result:
bookmark is not synced.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

device1: brave 0.61.38 on Windows 7
device2: brave 0.62.8 on Windows 7
device3: brave 0.61.38 on Ubuntu 17.10

Brave | 0.61.38 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Related issues: https://github.com/brave/brave-browser/issues/2687

cc @brave/legacy_qa @AlexeyBarabash

**Comment by rebron** [comment]
Related to https://github.com/brave/brave-browser/issues/2148

**Comment by kjozwiak** [comment]
@AlexeyBarabash did this land in `0.64.x`? Can you add the appropriate milestone to this issue including https://github.com/brave/brave-core/pull/2016?

**Comment by AlexeyBarabash** [comment]
@kjozwiak , yes, sorry, missed milestone 2nd time in row after merging.
Done.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.63.30 Chromium: 73.0.3683.75 (Official Build) beta (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

Used test plan from the description

**Comment by bsclifton** [comment]
Removed from `release-notes/include` since impact to customer is the same as https://github.com/brave/brave-browser/issues/2687
