### ISSUE TITLE
Migrate to Jupiter Swap API v6

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#35091]
🚨 Jupiter Swap API v4 will be discontinued by end of January 2024 per an announcement on their dev Telegram channel.

**A few things about v6:**
* complex routing - up to 10% saving to users depending on the amount
* performance improvement - from p99 > 4s to now sub 1s in v6

The PR needs to uplifted to 1.62.x to avoid disruption of service to users swapping on Solana.

**Comment by kjozwiak** [comment]
The above requires `1.62.136` or higher for `1.62.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.62.137 Chromium: 120.0.6099.217 (Official Build) beta (64-bit)
-- | --
Revision | 92c88bc64f4e5c37e60774394436493726ad7d63
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21475](https://github.com/brave/brave-core/pull/21475)
- Verified multiple quote options are removed 
- Verified Swap work as expected

https://github.com/brave/brave-browser/assets/17010094/3384707f-6811-457d-a9e1-f14f723b6fd1

--------------------
Verification passed on Google Pixel 8 with Android 14 running 1.62.137 x64 Beta build
- Verified steps from [brave/brave-core#21475](https://github.com/brave/brave-core/pull/21475)
- Verified multiple quote options are removed 
- Verified Swap work as expected

https://github.com/brave/brave-browser/assets/17010094/6a1ddd2b-36dc-4986-b4d8-5908ae214ced
