### ISSUE TITLE
Remove Instagram's new `igsh` share tracker

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#35094]
Similar to YouTube's sharing functionality which copies a URL along with a tracking parameter to the clipboard (https://github.com/brave/brave-browser/issues/33037), Instagram adds an `igsh` parameter to the URLs that it copies to the clipboard in JS.

<img src="https://github.com/brave/brave-browser/assets/167821/c78451b3-5ca8-49a7-9d96-54d8ec220d24" height="40%" width="40%">
<img src="https://github.com/brave/brave-browser/assets/167821/b070113f-d8c0-4b46-9bf5-aff62bf5bc19"  height="40%" width="40%">

We should add it to our default filter and the [copy clean link feature](https://github.com/brave/adblock-lists/pull/1461). Then, https://github.com/brave/brave-browser/issues/33037 will end up sanitizing both YouTube and Instagram.

**Comment by fmarier** [comment]
More info on why they track outbound links like that: https://help.instagram.com/2599848706833869

(HT https://twitter.com/gateklons/status/1739407333602533461)

**Comment by fmarier** [comment]
Here are two examples (parameter value shortened for privacy):
- https://www.instagram.com/reel/C04bQYMRoQj/?utm_source=ig_web_button_share_sheet&igsh=ZDNl...IxNw==
- https://www.instagram.com/p/C1nNxSbsAzk/?utm_source=ig_web_button_share_sheet&igsh=ZDNl...IxNw==  

where the identifier appears to be stabled across logins for a given user.

Note that the `igsh` param is only added via the _Share to..._ option and not when selecting _Copy link_ directly from the first menu. _Share to..._ (first menu) followed by _Copy link_ (second menu) does append the parameter.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.63.101 Chromium: 120.0.6099.199 (Official Build) nightly (x86_64)
-- | --
Revision | 8d3f0a563e185b6a763cc8e210ab24775dfb9047
OS | macOS Version 14.3 (Build 23D5043d)
```


## Case1 : https://www.youtube.com/watch?v=dQw4w9WgXcQ&si=YjziZuccJeIE-b6z

<img width="2009" alt="Screenshot 2024-01-08 at 11 46 44 AM" src="https://github.com/brave/brave-browser/assets/387249/5e28a303-80c9-48e4-873c-95f4f4415273">


## Case 2: https://youtu.be/watch?v=dQw4w9WgXcQ&si=YjziZuccJeIE-b6z

## Case 3: https://www.instagram.com/p/C1nNxSbsAzk/?utm_source=ig_web_button_share_sheet&igsh=ZDNl...IxNw==

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP11.231215.009 release-keys
Brave build: 1.63.146
Chromium: 121.0.6167.139 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Install and launch Brave
2. Go to Instagram and log in to your test account
3. Tap the `Three-dot` button on any post > Share to > Copy link
4. Open `NTP` > Paste > Confirm that `Igsh` param is there
5. Tap `Enter` > Verify the URL when a page is loaded
6. Go to YT > Ope any video > Share > Copy URL
7. Open `NTP` > Paste > Confirm that the `si` param is there
8. Tap `Enter` > Verify the URL when a page is loaded

**ACTUAL RESULTS:**
- Verified that the `igsh` param is removed when copying Instagram links with `Share to` > `Copy link`
- Verified that the `si` param is removed when copying YouTube links

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/20ea9aa3-27e1-473a-bae1-c5d1248574bc) | ![2](https://github.com/brave/brave-browser/assets/128532965/db6f2e1d-64a3-4d81-8e54-704380bdd147) | ![3](https://github.com/brave/brave-browser/assets/128532965/29a7df34-18b9-4286-8ebd-5075662cbf7f) | ![4](https://github.com/brave/brave-browser/assets/128532965/6e0e84c0-8686-4af1-9afd-2373c7158bcb) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/36428d55-ffee-497d-ba6b-1fa52ccf65e3) | ![2](https://github.com/brave/brave-browser/assets/128532965/90c4e7e8-e84c-4b76-a8bf-51f348385425) | ![3](https://github.com/brave/brave-browser/assets/128532965/7180661a-c1d4-407e-8f58-1be96a9ebb07) | ![4](https://github.com/brave/brave-browser/assets/128532965/208dfbf9-758d-47f8-8093-4ee17580c196) |
