### ISSUE TITLE
a-c table stays corrupted after brave update

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3510]
Follow up from https://github.com/brave/brave-browser/issues/3341
Important: a-c table will not fix itself, even if user visits other sites

## Steps to Reproduce

1. Clean Install 0.60.28
2. Enable rewards
3. Open `interia.pl` and add it to a-c table
4. Open `foxnews.com` and add it to a-c table
5. Exclude `foxnews.com` for a-c table in `brave://rewards`
6. Open `cnn.com` and add it to a-c table
7. Open `foxnews.com` and try to add it to a-c table
8. check a-c table - it is corrupted(sum of attention values is not 100%)
9. Update to 0.61.36
10. Open `foxnews.com` and try to add it to a-c table
11. Open `youtube.com` and add it to a-c table
12. check a-c table

## Actual result:

a-c table stays corrupted after brave update
All attention values don't add up to 100%
![image](https://user-images.githubusercontent.com/34715963/53462341-c98a1380-3a43-11e9-8af4-aac6416f26e5.png)

Note: Restoring the excluded sites will fix the a-c table

## Expected result:
All attention values add up to 100%

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.61.38 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

cc @brave/legacy_qa @NejcZdovc @rebron

**Comment by NejcZdovc** [comment]
I am not able to corrupt profile with `Version 0.60.45 Chromium: 72.0.3626.109 (Official Build) (64-bit)`

**Comment by btlechowski** [comment]
I am also not able to corrupt the profile on 0.60.45.

Brave | 0.60.45 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows

**Comment by NejcZdovc** [comment]
this is not only problem for upgrade scenario. This can be easily reproduced.

- add site to ac table
- remove it from ac table
- include it back in the panel
- ac table will still exclude it, where % will be off

**Comment by GeetaSarvadnya** [comment]
The issue is Reproducible on Upgraded profile. I have upgraded Brave beta `0.60.28` by `0.61.40`

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

Used STR from the description.
Used test plan from https://github.com/brave/brave-core/pull/1803
