### ISSUE TITLE
[Android] Disable multi-window support by default 

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#35106]
## Test plan
It shows setting where multiple windows supported
- default setting off
- default setting on if person has multiple windows already and update the app when this feature releases.
- When user tries to feature off when multiple windows already there then it asks the user in the dialog to either merge tabs from multiple windows or close other windows.
- feature off then turning on. In this case, user can create manually new windows from three dot menu settings. And multiple windows can be created when you tap on the some links in the other app and it directly opens in the brave.

## Description
- [ ] Disable multi window support by default
- [ ] Provide an option for user to enable multi-window support

For more context follow : https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1704168952026949

**Comment by hffvld** [comment]
Hi @timchilds @deeppandya 
`Multi-window` was always available on the `phones` as well. However, it's not so straightforward as on the `tablet`.

Tablet: Launch Brave > Three-dot menu > New window
Phone: Launch Brave > Open `NTP` > Tap and hold any favorite icon > In the context menu choose `Open in other window` > Three-dot menu > Now you can see `Move to other window` and `Manage windows`

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/fc9aa908-d897-40e1-b4ff-899d988b5ec7) | ![2](https://github.com/brave/brave-browser/assets/128532965/fc24ea12-a143-4853-b81d-1477af3c4623) | ![3](https://github.com/brave/brave-browser/assets/128532965/42fd9962-ef2c-4949-99df-eae03e3a1a54) | ![4](https://github.com/brave/brave-browser/assets/128532965/9bed0668-a35d-4b07-9cea-5c572692d256) |

**Comment by hffvld** [comment]
@deeppandya  Looks like the new change completely removed this feature from the phones. Should we keep it on the phones or not?

**Comment by deeppandya** [comment]
> @deeppandya  Looks like the new change completely removed this feature from the phones. Should we keep it on the phones or not?

For new users, by default it would be disabled. And if the user wants, they can enable it from settings

**Comment by deeppandya** [comment]
> Hi @timchilds @deeppandya 
> `Multi-window` was always available on the `phones` as well. However, it's not so straightforward as on the `tablet`.
> 
> Tablet: Launch Brave > Three-dot menu > New window
> Phone: Launch Brave > Open `NTP` > Tap and hold any favorite icon > In the context menu choose `Open in other window` > Three-dot menu > Now you can see `Move to other window` and `Manage windows`
> 
> |1|2|3|4|
> |:-:|:-:|:-:|:-:|
> | ![1](https://github.com/brave/brave-browser/assets/128532965/fc9aa908-d897-40e1-b4ff-899d988b5ec7) | ![2](https://github.com/brave/brave-browser/assets/128532965/fc24ea12-a143-4853-b81d-1477af3c4623) | ![3](https://github.com/brave/brave-browser/assets/128532965/42fd9962-ef2c-4949-99df-eae03e3a1a54) | ![4](https://github.com/brave/brave-browser/assets/128532965/9bed0668-a35d-4b07-9cea-5c572692d256) |
> 
> The issue I created for the `multi-window` https://github.com/brave/brave-browser/issues/33475

Regarding this, I think we decided to wait on upstream to change the cancel button position.

**Comment by tapanmodh** [comment]
> > @deeppandya  Looks like the new change completely removed this feature from the phones. Should we keep it on the phones or not?
> 
> For new users, by default it would be disabled. And if the user wants, they can enable it from settings

This feature will not visible in the settings in the phone as there is no option to create new window from menu apart from `NTP` -> `Open in other window`. Do we want to visible in the settings for this case?

**Comment by kjozwiak** [comment]
The above requires `1.66.105` or higher for `1.66.x` verification 👍
