### ISSUE TITLE
Add P3A metric for presence of autofill payment method

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#35115]
Add a monthly metric for autofill settings:

Do you have a payment method saved in your autofill settings?
`Brave.Autofill.PaymentMethodPresent`

0. No
1. Yes

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | Windows 10 Version 22H2 (Build 19045.4046)
```
<details>
<summary>Brave.Autofill.PaymentMethodPresent = 0</summary>

</details>

<details>
<summary>Brave.Autofill.PaymentMethodPresent = 1</summary>

</details>

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.64.95 
Chromium: 122.0.6261.94 (Official Build) beta (64-bit) 
```
---------------------------
<details>
<summary> Brave.Autofill.PaymentMethodPresent = 0 </summary>

**STEPS:**
1. Install and launch Brave
2. Open `brave://local-state`
3. Search for the `Brave.Autofill.PaymentMethodPresent` metric > *Verify*

**ACTUAL RESULTS:**
- Verified that the `Brave.Autofill.PaymentMethodPresent` metric response value is `0` as expected

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/71aff6a9-898c-45c7-a4d9-9c54a5aeb37e) | ![2](https://github.com/brave/brave-browser/assets/128532965/23ddbc10-ddf2-4989-aabd-370b7dfd9467) | ![3](https://github.com/brave/brave-browser/assets/128532965/3f537aaa-5168-494c-835e-921b931c9c18) |
</details>

<details>
<summary> Brave.Autofill.PaymentMethodPresent = 1 </summary>

**STEPS:**
1. Install and launch Brave
2. Go to the `Settings` > Payment methods > Add card > Follow the flow
3. Open `brave://local-state`
4. Search for the `Brave.Autofill.PaymentMethodPresent` metric > *Verify*

**ACTUAL RESULTS:**
- Verified that the `Brave.Autofill.PaymentMethodPresent` metric response value is `1` as expected

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/e0540689-fd50-4cef-8283-ab359d5fff95) | ![2](https://github.com/brave/brave-browser/assets/128532965/e9b90a93-acb8-4042-aa81-47bc222d11ec) | ![3](https://github.com/brave/brave-browser/assets/128532965/b7c9d210-c2ae-493b-9469-0dc879f135ea) |
</details>
