### ISSUE TITLE
Brave Does not include ublock-linkshorteners

### ISSUE THREAD

**Issue by ChowMein47** [brave/brave-browser#35128]
Hi,Does brave adblock support uBlock's new filter to handle link shorteners issue? (https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/ubo-link-shorteners.txt) 

If Brave support the filter please add as default filter Brave users can receive the benefit. Thank you

@antonok-edm @ryanbr

**Comment by ryanbr** [comment]
Is now included, enabled by default. @ChowMein47
