### ISSUE TITLE
Tor not working till browser restart if page is opened just after clean install

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3512]
Follow up from https://github.com/brave/brave-browser/issues/3058

## Steps to Reproduce

   1. Clean install (make sure that profile does not exists)
   2. Immediately after Brave is launched open `https://check.torproject.org/` in Tor Window
   3. Close Tor Window
4. Open Tor Window and open a page

## Actual result:

Page is not opened.
Error page is always shown
Tor is not initialized.

Note: browser restart fixes this issue

## Expected result:
Tor is initialized

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Verification passed on 

Brave | 0.61.38 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

cc @brave/legacy_qa @tomlowenthal @riastradh-brave

**Comment by GeetaSarvadnya** [comment]
Reproduced on Linux 0.61.41 - Linux mint

Brave	0.61.41 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
Revision	cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS	Linux mint

**Comment by btlechowski** [comment]
Still reproducible.

Brave | 0.67.111 Chromium: 75.0.3770.100 (Official Build) beta (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

**Comment by riastradh-brave** [comment]
This happens if you type fast enough to beat the component updater downloading the tor component.  The tor component updater initializes the tor executable path only after the component is downloaded, but the only place that we choose to launch tor is when we construct the TorProfileServiceImpl -- which may happen before the tor component has been downloaded.

Resolution: Maybe we can teach BraveTorClientUpdater::OnComponentReady to notify the TorProfileServiceImpl that it can launch tor now.

**Comment by btlechowski** [comment]
Probably fixed by https://github.com/brave/brave-core/pull/7069

Added it to 1.19.x milestone so it can be retested.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.19.66 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.685)

```
- Verified the STR from the description and https://github.com/brave/brave-core/pull/7069
- Additional testing is covered in https://github.com/brave/brave-browser/issues/12470#issuecomment-749421953
