### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ja-softdevel** [brave/brave-browser#35139]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

** note ** : I did hit send on several of the crash reports. This only started today and quite randomly. I hadn't changed anything on the host machine today. Very weird. I noticed it was starting to respond slowly to mouse clicks and then it just crashed. Crashing google chrome and gitkraken. 

Brave Version: 1.62.128 Chromium: 120.0.6099.144
Operating System: Linux 6.2.0-39-generic

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. It's so random but consistent. After a moment it just crashes or if I try to do anything.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/e2c10200-f4b8-4b0b-0000-000000000000

**Comment by ja-softdevel** [comment]
I just remembered, I did restore a wallet yesterday. I don't normally use the wallet feature within Brave. Other changes that I can think of recently, was reinstalling lxd on host and launching a container yesterday. I did a software update with just a few packages earlier this week. FYI I'm on ubuntu 22.04

**Comment by bsclifton** [comment]
Unfortunately, looks like there's no crash information available. We'd need another crash ID to troubleshoot more

@ja-softdevel if you ran into this again, please resubmit the crash report and let us know the ID! 😄 Thanks!
