### ISSUE TITLE
[PG] Look into PageGraph arguments save

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#35130]
check recording of args for `navigator.geolocation.getCurrentPosition` and `navigator.mediaDevices.getUserMedia`.

https://bravesoftware.slack.com/archives/CGQFAK4Q0/p1703014165443789?thread_ts=1702333013.257949&cid=CGQFAK4Q0

**Comment by pes10k** [comment]
Thanks for the contenxt @L3thal14 ! Fwiw, i'd be very interested in those papers if you could share the cites @L3thal14 !

**Comment by L3thal14** [comment]
Sure, https://kapravelos.com/publications/jsobf-imc20.pdf from the Brave wiki.

**Comment by pes10k** [comment]
Oh, yes, im familiar with that one of course. You said plural so i thought there was more than one.  All good!

**Comment by L3thal14** [comment]
> Oh, yes, im familiar with that one of course. You said plural so i thought there was more than one. All good!

Oh yeah, my bad. Yeah, that specific paper used this combination. In most cases (https://dl.acm.org/doi/10.1145/3543507.3583333), I believe VisibleV8 is enough to monitor web API calls and map them to the source code. However, tracking the arguments/ return values, especially in the context of the Pagegraph's graph output, might uncover interesting source and sink cases and could help categorize their behavior.

**Comment by goodov** [comment]
Hey guys, can you please help me figure out a better format for `args` in the graph?

Right now we have `args` field in the `call` edge which is just a string with comma-separated values. It's not escaped in any way, so it's unclear how exactly it can be parsed.

I'm thinking about adding `arg 0, arg 1, ...` data fields. Does it sound good? I can also add `args count`.

**Comment by L3thal14** [comment]
any updates on this?
