### ISSUE TITLE
a-c toggle switch won't turn ON immediately, when enable rewards through hamburger menu

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3513]
## Description 

a-c toggle switch won't turn ON immediately when enable rewards through the hamburger menu. The issue is not reproducible consistently.

## Steps to Reproduce

   1. Clean profile 0.61.37
   2. Enable rewards through hamburger menu
   3. Auto-Contribution doesn't turn on immediately ( It took more than 30 secs)
   4. when a-c toggles On, rewards server error displayed

## Actual result:

a-c toggle switch won't turn ON immediately when enable rewards through hamburger menu

![a-c switch toggle](https://user-images.githubusercontent.com/38657976/53494767-7b692480-3ac4-11e9-85b4-efbe79a78cc4.gif)

## Expected result:

a-c toggle switch should turn ON immediately.

## Reproduces how often: 

Intermittent-issue
## Brave version (brave://version info)

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 10 OS Build 17134.523

### Reproducible on current release: no
- Does it reproduce on brave-browser dev/beta builds?  yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information

@brave/legacy_qa

**Comment by LaurenWags** [comment]
Haven't reproduced the server error yet, but the a-c toggle does take a couple seconds to turn on after enabling Rewards. 

Brave | 0.61.41 Chromium: 73.0.3683.39 (Official Build) beta(64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Mac OS X

**Comment by Miyayes** [comment]
@GeetaSarvadnya Does this still repro?

**Comment by GeetaSarvadnya** [comment]
@Miyayes Verified the issue against the build `1.42.68` the issue is not reproducible anymore, hence closing the issue.

```
Brave | 1.42.86 Chromium: 104.0.5112.81 (Official Build) (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 10 Version 21H2 (Build 19044.1826)

```
