### ISSUE TITLE
[Brave News]: Tweaks round 4

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#35144]
@LorenzoMinto reported a number of minor UX issues:
1. Line height on `Ad` badge is slightly off
2. Settings menu is too large in the bottom right (seems to be a padding mismatch with the Figma)
3. We should up the follow buttons on Publishers to use the new design
4. Copy for the empty feed has some small tweaks

**Comment by kjozwiak** [comment]
The above requires `1.62.136` or higher for `1.62.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.62.136 Chromium: 120.0.6099.199 (Official Build) beta (x86_64)
-- | --
Revision | b442808933893755f22c498b3c3d1f6e6931e258
OS | macOS Version 11.7.10 (Build 20G1427)
```


`Ad` line-height tweak - `PENDING`
<details>

</details>


`Settings` menu icon is too large - `PENDING`
<details>

</details>


Follow` buttons - `PENDING`
<details>

</details>


Copy - `PENDING`
<details>

</details>
