### ISSUE TITLE
Add Rewards page & panel view metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#35146]
Add the following:

If you are Rewards user who opened the Rewards panel in the past week, how many times did you open it? (desktop only)
`Brave.Rewards.DesktopPanelCount`

0. 1-5
1. 6-10
2. 11-50
3. 50+

If you are Rewards user who opened the Rewards page in the past month, how many times did you open it? (desktop & Android)
`Brave.Rewards.PageViewCount`

0. 1-2
1. 3-5
2. 6-10
3. 11-50
4. 51+

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.63.141 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | aa92f6cecec7f6c576bd1cf120f4cf359d770159
OS | Windows 10 Version 22H2 (Build 19045.3930)
```

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP11.231215.009 release-keys
Brave build: 1.63.141
Chromium: 121.0.6167.139 (Official Build) beta (64-bit) 
```
---------------------------
<details>
<summary> Brave.Rewards.PageViewCount = 0 </summary>

**STEPS:**
1. Fresh install and launch Brave
2. Open `brave://local-state` > Verify that the metrics `Brave.Rewards.PageViewCount` is NOT shown
3. Open `brave://rewrads` in a new tab page
4. Reload the local state file > Verify that the metrics `Brave.Rewards.PageViewCount` is NOT shown
5. Enable `Rewards`
6. Reload the local state file > Verify that the metrics `Brave.Rewards.PageViewCount` is NOT shown
7. Open `brave://rewrads` in another tab
8. Reload the local state file > Verify that the metrics `Brave.Rewards.PageViewCount` response value is `0` as expected
9. Open another `brave://rewrads` tab
10. Reload the local state file > Verify that the metrics `Brave.Rewards.PageViewCount` response value is `0` as expected

**ACTUAL RESULTS:**
- Verified that the metrics `Brave.Rewards.PageViewCount` is NOT shown for the `fresh profile`
- Verified that the metrics `Brave.Rewards.PageViewCount` is NOT shown when `brave://rewrads` is opened in the new tab
- Verified that the metrics `Brave.Rewards.PageViewCount` is NOT shown after `Rewards` is enabled
- Verified that the metrics `Brave.Rewards.PageViewCount` response value is `0` as expected when `1 - 2` `brave://rewrads` tabs were opened

---------------------------

|Fresh profile|Rewards not enabled|Rewards enabled|1 - 2 tabs opened|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/b62b8b96-5628-41d6-b0e2-e238e894c7db) | ![2](https://github.com/brave/brave-browser/assets/128532965/6aa88dd3-b19d-4251-af7e-bd26602d021c) | ![3](https://github.com/brave/brave-browser/assets/128532965/13c44f96-a32d-442d-81cb-93408de3bb2e) | ![4](https://github.com/brave/brave-browser/assets/128532965/ce893a9d-0ae1-4684-aae2-9a006635c7a9) |
</details>

<details>
<summary> Brave.Rewards.PageViewCount = 1 </summary>

**STEPS:**
1. Fresh install and launch Brave
2. Open `brave://local-state` > Verify that the metrics `Brave.Rewards.PageViewCount` is NOT shown
3. Open `brave://rewrads` in a new tab page
4. Reload the local state file > Verify that the metrics `Brave.Rewards.PageViewCount` is NOT shown
5. Enable `Rewards`
6. Reload the local state file > Verify that the metrics `Brave.Rewards.PageViewCount` is NOT shown
7. Open `brave://rewrads` in the 3 NTPs
8. Reload the local state file > Verify that the metrics `Brave.Rewards.PageViewCount` response value is `1` as expected
9. Open another 2 `brave://rewrads` tabs
10. Reload the local state file > Verify that the metrics `Brave.Rewards.PageViewCount` response value is `1` as expected

**ACTUAL RESULTS:**
- Verified that the metrics `Brave.Rewards.PageViewCount` is NOT shown for the `fresh profile`
- Verified that the metrics `Brave.Rewards.PageViewCount` is NOT shown when `brave://rewrads` is opened in the new tab
- Verified that the metrics `Brave.Rewards.PageViewCount` is NOT shown after `Rewards` is enabled
- Verified that the metrics `Brave.Rewards.PageViewCount` response value is `1` as expected when `3 - 5` `brave://rewrads` tabs were opened

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/c6057f0d-8ba2-42cf-b7fe-96448e357e9e) | ![2](https://github.com/brave/brave-browser/assets/128532965/d06ccd82-f56a-4c8b-8e3b-58fa76e50195) |
</details>

<details>
<summary> Brave.Rewards.PageViewCount = 2 </summary>

**STEPS:**
1. Fresh install and launch Brave
2. Open `brave://local-state` > Verify that the metrics `Brave.Rewards.PageViewCount` is NOT shown
3. Open `brave://rewrads` in a new tab page
4. Reload the local state file > Verify that the metrics `Brave.Rewards.PageViewCount` is NOT shown
5. Enable `Rewards`
6. Reload the local state file > Verify that the metrics `Brave.Rewards.PageViewCount` is NOT shown
7. Open `brave://rewrads` in the 6 NTPs
8. Reload the local state file > Verify that the metrics `Brave.Rewards.PageViewCount` response value is `2` as expected
9. Open another 4 `brave://rewrads` tabs
10. Reload the local state file > Verify that the metrics `Brave.Rewards.PageViewCount` response value is `2` as expected

**ACTUAL RESULTS:**
- Verified that the metrics `Brave.Rewards.PageViewCount` is NOT shown for the `fresh profile`
- Verified that the metrics `Brave.Rewards.PageViewCount` is NOT shown when `brave://rewrads` is opened in the new tab
- Verified that the metrics `Brave.Rewards.PageViewCount` is NOT shown after `Rewards` is enabled
- Verified that the metrics `Brave.Rewards.PageViewCount` response value is `2` as expected when `6 - 10` `brave://rewrads` tabs were opened

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/5ee79162-b7e7-4d46-8fd9-280fb28eb425) | ![2](https://github.com/brave/brave-browser/assets/128532965/95d42b1d-d5e6-4692-847d-459065bafc3e) |
</details>

<details>
<summary> Brave.Rewards.PageViewCount = 3 </summary>

**STEPS:**
1. Fresh install and launch Brave
2. Open `brave://local-state` > Verify that the metrics `Brave.Rewards.PageViewCount` is NOT shown
3. Open `brave://rewrads` in a new tab page
4. Reload the local state file > Verify that the metrics `Brave.Rewards.PageViewCount` is NOT shown
5. Enable `Rewards`
6. Reload the local state file > Verify that the metrics `Brave.Rewards.PageViewCount` is NOT shown
7. Open `brave://rewrads` in the 11 NTPs
8. Reload the local state file > Verify that the metrics `Brave.Rewards.PageViewCount` response value is `3` as expected
9. Open another 39 `brave://rewrads` tabs
10. Reload the local state file > Verify that the metrics `Brave.Rewards.PageViewCount` response value is `3` as expected

**ACTUAL RESULTS:**
- Verified that the metrics `Brave.Rewards.PageViewCount` is NOT shown for the `fresh profile`
- Verified that the metrics `Brave.Rewards.PageViewCount` is NOT shown when `brave://rewrads` is opened in the new tab
- Verified that the metrics `Brave.Rewards.PageViewCount` is NOT shown after `Rewards` is enabled
- Verified that the metrics `Brave.Rewards.PageViewCount` response value is `3` as expected when `11 - 50` `brave://rewrads` tabs were opened

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/875a6bf8-a0cb-47cd-9c43-625c79c331ec) | ![2](https://github.com/brave/brave-browser/assets/128532965/8457280b-fbfe-4d8b-b1a7-617256702426) |
</details>

<details>
<summary> Brave.Rewards.PageViewCount = 4 </summary>

**STEPS:**
1. Fresh install and launch Brave
2. Open `brave://local-state` > Verify that the metrics `Brave.Rewards.PageViewCount` is NOT shown
3. Open `brave://rewrads` in a new tab page
4. Reload the local state file > Verify that the metrics `Brave.Rewards.PageViewCount` is NOT shown
5. Enable `Rewards`
6. Reload the local state file > Verify that the metrics `Brave.Rewards.PageViewCount` is NOT shown
7. Open `brave://rewrads` in the 51+ NTPs
8. Reload the local state file > Verify that the metrics `Brave.Rewards.PageViewCount` response value is `4` as expected

**ACTUAL RESULTS:**
- Verified that the metrics `Brave.Rewards.PageViewCount` is NOT shown for the `fresh profile`
- Verified that the metrics `Brave.Rewards.PageViewCount` is NOT shown when `brave://rewrads` is opened in the new tab
- Verified that the metrics `Brave.Rewards.PageViewCount` is NOT shown after `Rewards` is enabled
- Verified that the metrics `Brave.Rewards.PageViewCount` response value is `4` as expected when `51+` `brave://rewrads` tabs were opened

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/90baeb87-7ab6-4c01-b161-e92730a7c2c1) | ![2](https://github.com/brave/brave-browser/assets/128532965/7bda42fa-b9a3-41a9-b2a4-9f338a0a1ca0) |
</details>
