### ISSUE TITLE
Upgrade for confirmations is not working

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#3514]
## Steps to Reproduce

   1. Create profile with version that don't have confirmations UI
   2. Switch to master branch
   3. go to rewards page

## Actual result:

empty page with JS error

## Expected result:
Page should be shown

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.63.20 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

- Verified the test plan from https://github.com/brave/brave-core/pull/1791
