### ISSUE TITLE
Browser Services Key v2 MVP

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#35152]
See [doc](https://docs.google.com/document/d/12Qp39Mgr1HF7VvLK44BJw-fkeOsF-aj6pW9YHqHRcUY/edit#heading=h.oppxx8yhkse4)

**Comment by kjozwiak** [comment]
The above requires `1.62.150` or higher for `1.62.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `PENDING` using 

```
Brave | 1.62.150 Chromium: 121.0.6167.85 (Official Build) (x86_64)
-- | --
Revision | c01f5cde4d5d5e41134c0ccdb1868acd80a64a34
OS | macOS Version 14.3 (Build 23D56)
```

# `Non-Premium` - `PENDING`

## `Production` - `PENDING`
<details>


### Steps:
1. installed `1.62.150`
2. launched Brave using `--enable-logging=stderr --v=2`
3. loaded `.`
4. clicked on `Summarize this page`
5. clicked on `Accept and begin`

### Confirmed responses from `Mixtral`, `Claude Instant`, and `Llama 2-13b`, using `https://ai-chat.bsg.brave.com/v2/complete`



`Mixtral` | `Claude Instant` | `LLama2-13b` | `Fiddler Everywhere`
---------|-------------------|-----------------|-----------------------



</details>

## `Development` (`--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev `) - `PENDING`
<details>

### Steps:
0. connected to `Brave VPN` (internal)
1. installed `1.62.150`
2. launched Brave using `--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev --enable-logging=stderr --v=2`
3. loaded `.`
4. clicked on `Summarize this page`
5. clicked on `Accept and begin`

### Confirmed responses from `Mixtral`, `Claude Instant`, and `Llama 2-13b`, using `https://ai-chat.bsg.brave.software/v2/complete`



`Mixtral` | `Claude Instant` | `Llama2-13b` | `Fiddler Everywhere`
----------|------------------|----------------|----------------------


</details>

---



# `Premium` - `PENDING`

## `Production` - `PENDING`
<details>


### Steps:
1. installed `1.62.150`
2. launched Brave using `--enable-logging=stderr --v=2`
3. purchased and loaded `Leo Premium` credentials from `account.brave.com` using `issue35152@mailinator.com`
3. loaded `.`
4. clicked on `Summarize this page`
5. clicked on `Accept and begin`

### Confirmed responses from `Mixtral`, `Claude Instant`, and `Llama 2-13b`, using `https://ai-chat-premium.bsg.brave.com/v2/complete`



`Mixtral` | `Claude Instant` | `LLama2-13b` | `Fiddler Everywhere`
---------|-------------------|-----------------|-----------------------




</details>

## `Development` (`--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev `) - `PENDING`
<details>

### Steps:
0. connected to `Brave VPN` (internal)
1. installed `1.62.150`
2. launched Brave using `--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev --enable-logging=stderr --v=2`
3. purchased and loaded `Leo Premium` credentials from `account.bravesoftware.com` using `issue35
4. loaded `.`
5. clicked on `Summarize this page`
6. clicked on `Accept and begin`

### Confirmed responses from `Mixtral`, `Claude Instant`, and `Llama 2-13b`, using `https://ai-chat-premium.bsg.brave.software/v2/complete`

`account.bravesoftware.com` | `Fiddler Everywhere`
--------------------------------|-----------------------




`Mixtral` | `Claude Instant` | `Llama2-13b`
----------|------------------|----------------



</details>
