### ISSUE TITLE
Probably shouldn't have collapse/expand widget ("twisty") for unpopulated `Channels` and `Publishers` views

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#35157]
## Description 

Probably shouldn't have collapse/expand widget ("twisty") for unpopulated `Channels` and `Publishers` views

## Steps to Reproduce

1. install `1.62.131`
2. launch Brave
3. open a new-tab page
4. scroll down
5. click on `Turn on Brave News`
6. for at least one category -- `Channels` or `Publishers` -- leave it without subscribed sources
7. expand that empty category, using the collapse/expand widget ("twisty")

## Actual result:

Nothing happens, nothing's there - the widget just moves

example | example
---------|--------
<img width="1312" alt="Screen Shot 2024-01-05 at 1 52 03 PM" src="https://github.com/brave/brave-browser/assets/387249/601f7905-1489-40a2-8a7d-37fe98c3a691"> | <img width="328" alt="Screen Shot 2024-01-05 at 2 02 25 PM" src="https://github.com/brave/brave-browser/assets/387249/0103fd82-af51-492a-81d6-07352f636359">

## Expected result:

I'd expect it to not-yet have the "twisty" collapse/expand widget, until we have source content

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.62.131 Chromium: 120.0.6099.199 (Official Build) beta (x86_64)
-- | --
Revision | 217e8080b48df17845efb3c1a80433a8028978de
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @martin-c0des @aguscruiz @fallaciousreasoning @mattmcalister @rebron @brave/qa-team

**Comment by fallaciousreasoning** [comment]
I think I'm going to adopt "twisty" as the name for these from now on :laughing: 

@martin-c0des should we just have some text there that says "no {publishers|channels}"?

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.63.110 Chromium: 120.0.6099.217 (Official Build) nightly (64-bit)
-- | --
Revision | f7a7c2ee42626f5a1310c9bd6789d0438e78ca6e
OS | Windows 11 Version 22H2 (Build 22621.3007)
```

1. Installed 1.63.110
2. launched Brave
3. clicked `Turn on News`
4. verified `Feed` is loaded
5. confirmed sidebar shows `Top sources` under `Channels` is shown
6. confirmed collapse/expand widget worked as expected when it's populated
7. confirmed sidebar do not show `Publishers` widget as I am not subscribed to any sources
8. clicked `Customize` button
9. unfollowed `Top sources`
10. Followed `CNN` and `Fox News`
11. confirmed `Channels` is not shown in the sidebar
12. confirmed `Fox News` and `CNN` is shown under `Publishers`
13.  confirmed collapse/expand widget for `Publishers` worked as expected when it's populated
14. return to Brave news dialog
15. unfollowed `CNN` and `Fox News`
16. confirmed `Channels` & `Publishers` are not available

step 5 | step 6 | step 7 | step 9-10 |step 11-12 | step 13 | step 15 | step 16
------ | ------ | ------ | ------- | ------ | ----- | ------- | ------- 
![image](https://github.com/brave/brave-browser/assets/98358127/a82e3592-1273-4b34-875a-ce9749059c68)|![image](https://github.com/brave/brave-browser/assets/98358127/0166c151-fa81-4760-bb60-75ffe16f5e65)|![image](https://github.com/brave/brave-browser/assets/98358127/06606d3a-2c1a-4ffd-8576-14e5db04f0e0)|![image](https://github.com/brave/brave-browser/assets/98358127/e024636a-5a55-435d-a94b-44e5e3c6f88b)|![image](https://github.com/brave/brave-browser/assets/98358127/45bb001c-4d61-469f-be4f-3a4ea8f90cbc)|![image](https://github.com/brave/brave-browser/assets/98358127/ed366078-634f-46f0-af63-a4795b83c105)|![image](https://github.com/brave/brave-browser/assets/98358127/20f5ad71-075c-48c9-ba0c-f5d08e7c7bff)|![image](https://github.com/brave/brave-browser/assets/98358127/1437b682-01dc-4934-b52f-8332d147a1b6)

**Comment by fallaciousreasoning** [comment]
Hey, so I think we're going to revert this fix - talked to @LorenzoMinto about it and he wants to still display them.

**Comment by LaurenWags** [comment]
@fallaciousreasoning if we go that rout, we should open a new issue instead of just reopening this one (things get messy when we reopen issues where code has landed). Thanks!

**Comment by kjozwiak** [comment]
Removing the `QA Pass` label as the above was uplifted into `1.62.x` via https://github.com/brave/brave-core/pull/21545#pullrequestreview-1817056726 and will need to be rechecked using `1.62.x` using `1.62.138` or higher.

However, it sounds like the above change needs to be reverted as per https://github.com/brave/brave-browser/issues/35157#issuecomment-1887781442. Going to label this as `QA/Blocked` until we have more information, or a new issue as @LaurenWags mentioned above.

@fallaciousreasoning should the above even be verified/checked? Or should we just label is as `QA/No` and wait for the revert?

**Comment by fallaciousreasoning** [comment]
Maybe let's just mark it as QA/No :smile:
