### ISSUE TITLE
Brave News doesn't recover from lack of wifi until browser restart

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#35154]
## Description 

When there isn't wifi, you will encounter https://github.com/brave/brave-browser/issues/35153 with Brave News. When wifi is restored, I'd expect Brave News to load (either after refreshing current tab or opening a new one), however the loading spinner persists. I've only been able to get news to work with a browser restart. This occurs with both v1 and v2.

## Steps to Reproduce

   1. Have a profile with news enabled (but not launched)
   2. Turn off wifi for your device
   3. Launch the profile
   4. Open a new tab and try to access news (encounter https://github.com/brave/brave-browser/issues/35153)
   5. Restore wifi for device
   6. Refresh tab/open new tab, neither will make Brave News load - spinner is just shown continuously
   7. Try restarting the browser then opening new tab, now Brave News will load

## Actual result:

Brave News continues to show loading spinner even though internet access is restored, seems like it can't recover from state without internet access

## Expected result:

Brave News should be able to recover

## Reproduces how often: 

easily

## Brave version (brave://version info)

 1.61.x, 1.62.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @brave/qa-team @fallaciousreasoning

**Comment by stephendonner** [comment]
We neither timeout from the initial request (https://github.com/brave/brave-browser/issues/35153), nor recover once reconnected to Wi-Fi:

<img width="1312" alt="スクリーンショット 2024-01-05 12 16 02" src="https://github.com/brave/brave-browser/assets/387249/ac047a23-508d-4b4e-bec9-0fff5fce432f">

**Comment by kjozwiak** [comment]
The above requires `1.62.138` or higher for `1.62.x` verification 👍

**Comment by btlechowski** [comment]
Verified with

Brave | 1.62.144 Chromium: 120.0.6099.217 (Official Build) beta (64-bit)
-- | --
Revision | 75de8d953f6a5686e425d46d7f0dc9284dc1c064
OS | Linux

Verified test plan from the description
Verified Brave feed loaded

![35154](https://github.com/brave/brave-browser/assets/34715963/5014543b-7fa3-48b0-a191-e3c0f3e21f0c)

Logged https://github.com/brave/brave-browser/issues/35361

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.62.147 Chromium: 120.0.6099.234 (Official Build) (64-bit)
-- | --
Revision | 3b25c3743150a54485dea24f0ceb1e69d6db51bc
OS | Windows 11 Version 22H2 (Build 22621.3007)
```

1. Installed 1.62.147
2. launched Brave
3. enabled #brave-news-feed-update via brave://flags
4. enabled Brave news via Customize button
5. closed Brave
6. disconnected WiFi/Network
7. relaunched Brave
8. opened new tab and `You appear to be offline` error message shown as expected 
9. enabled WiFi and clicked Refresh button

- Confirmed New content available. Reload? message shown
- Confirmed Brave news feed loaded when clicked Refresh button


step 3 | step 4 | step 6 | step 8 | step 9 | feed
----- | ----- | ----- | ----- | ----- | -----  
<img width="939" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2542c3cc-2681-438f-a73a-310417e5f659">|<img width="938" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8cc6b004-ed97-4453-9e2e-be57ffbfae1e">|<img width="604" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/20444f3d-f4cb-4f89-a339-7130e2b9076a">|<img width="939" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9099a48e-8f05-4b9e-8d17-f301effe1e60">|<img width="934" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b995e709-7fd4-486f-be76-404f959b97cd">|<img width="951" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/412b9bec-bc5e-435f-ba80-ba58783c900a">

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.62.147 Chromium: 120.0.6099.234 (Official Build) (x86_64)
-- | --
Revision | 3b25c3743150a54485dea24f0ceb1e69d6db51bc
OS | macOS Version 13.6.3 (Build 22G436)
```
