### ISSUE TITLE
loading spinner for Brave News shows square outline sometimes

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#35155]
## Description 

Sometimes the loading spinner for Brave News displays a square outline. Seems to depend on background color of the NTP and possibly the fade/blur as you scroll on Brave News?

## Steps to Reproduce

   1. Reliably get into a situation where the loading spinner displays (ex. https://github.com/brave/brave-browser/issues/35153)
   2. Look at the loading spinner on a variety of NTP backgrounds (and scroll positions on the page)

## Actual result:

Sometimes the square outline is visible:

Example | Example
--- | ---
<img width="1127" alt="Screenshot 2024-01-05 at 1 04 16 PM" src="https://github.com/brave/brave-browser/assets/28145373/8127bf96-52ff-4e5c-bd87-25f5f71734cd"> | <img width="970" alt="Screenshot 2024-01-05 at 1 15 15 PM" src="https://github.com/brave/brave-browser/assets/28145373/20d03873-28ee-401e-ada5-dc1fcdc246d7">

## Expected result:

No square outline visible

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.62.x, 1.63.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes, 1.62.x
- Can you reproduce this issue with the nightly channel? yes 1.63.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @brave/qa-team @fallaciousreasoning

**Comment by stephendonner** [comment]
Now that I see the square, I can't unsee it 😉

**Comment by AyushNigam11** [comment]
Need to conditional styling and CSS adjustments

**Comment by AyushNigam11** [comment]
> Need to conditional styling and CSS adjustments

do*

**Comment by kjozwiak** [comment]
The above requires `1.62.138` or higher for `1.62.x` verification 👍
