### ISSUE TITLE
Something changed with Brave Shields and it's blocking so much that no sites will load

### ISSUE THREAD

**Issue by KHouse75** [brave/brave-browser#35161]
Something changed with Brave Shields and it's blocking so much that no sites will load

**Comment by lodenrogue** [comment]
Was having the same issue. Go into Settings and the bottom left where it says About Brave click that. It should do an update and give you the option to relaunch. Relaunch and you should be good.

**Comment by binex-dsk** [comment]
dup #35160

**Comment by KHouse75** [comment]
> Was having the same issue. Go into Settings and the bottom left where it says About Brave click that. It should do an update and give you the option to relaunch. Relaunch and you should be good.

That's the first thing I did and the problem wasn't resolve.  Just did it again, however, and it looks to be working now.

**Comment by ryanbr** [comment]
Should be resolved. It'll automatically fix itself. If not, can force an update in brave://components in Easylist Cookie.
