### ISSUE TITLE
Everything blocked on client and can only browse websites after disabling Brave Shield

### ISSUE THREAD

**Issue by Redouane64** [brave/brave-browser#35162]
## Description 

I have sudden issue on brave, All website become inaccessible and only works after I disabled Brave Shield.

## Steps to Reproduce

I don't know

## Actual result:

Here is screenshot when loading a website:
![image](https://github.com/brave/brave-browser/assets/6832213/ad43800a-bc99-4174-b6f2-c3bb1de90a67)

## Expected result:
It should work normally.

## Brave version (brave://version info)

Brave	1.61.114 Chromium: 120.0.6099.199 (Official Build) (64-bit) 
Revision	e0f6e091fe79c029231a86e8cdcc5fbe70bcddbe
OS	Linux
JavaScript	V8 12.0.267.14
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Command Line	/opt/brave.com/brave/brave --desktop-startup-id=surtur;1704500845;754362;2222_TIME106734 --disable-domain-reliability --enable-distillability-service --enable-dom-distiller --lso-url=https://no-thanks.invalid --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --restart --sync-url=https://sync-v2.brave.com/v2 --variations-insecure-server-url=https://variations.brave.com/seed --variations-server-url=https://variations.brave.com/seed --restart --flag-switches-begin --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions,url-source=https://go-updater.brave.com/extensions,url-source=https://go-updater.brave.com/extensions,url-source=https://go-updater.brave.com/extensions
Executable Path	/opt/brave.com/brave/brave
Profile Path	/home/redouane/.config/BraveSoftware/Brave-Browser/Default
Active Variations	AllowCertainClientHintsStudy:Enabled
BraveAIChatEnabledStudy:Enabled
BraveAdblockMobileNotificationsListDefault:Enabled
BraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=6/MaximumInlineContentAdsPerDay=20/AdServingVersion=2
BraveAutoTranslateStudy:AutoTranslateDisabled
BraveDebounceStudy:Enabled
BraveForgetFirstPartyStorage:Enabled
BraveGoogleSignInPermissionStudy:Disabled
BraveHttpsByDefaultRolloutStudy:Enabled
BraveP3AConstellationReleaseRollout:Enabled
BraveRewardsWebUiPanelStudy:Enabled
BraveScreenFingerprintingBlockerStudy:Enabled
BraveSearchAdStudy:EnabledInProcessDesktop
ClampPlatformVersionClientHint:Disabled
CookieListDefaultStudy:Enabled
Default1pBlockingStudy:Disabled
DisableReduceLanguage:Enabled
EphemeralStorageStudy:Enabled
FirstPartyEphemeralDomainBlockStudy:Enabled
ForceDisableBlinkFeatures:Enabled
PartitionBlinkMemoryCacheStudy:Enabled
PartitionConnectionsByNetworkIsolationKeyStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled
SmilAutoSuspendOnLagKillSwitch:Disabled_EmergencyKillSwitch
UserActivityStudy:Triggers
WhatsNewStudy:Enabled

**Comment by benurb** [comment]
Can confirm for Brave 1.61.104 Chromium: 120.0.6099.115 (64-Bit) on Windows 11 Version 22H2 (Build 22621.2861).
No assets are loading for any website. Only the initial HTML request seems to work.

**Comment by binex-dsk** [comment]
dup #35160

**Comment by ryanbr** [comment]
Should be resolved. It'll automatically fix itself. If not, can force an update in brave://components in Easylist Cookie.

**Comment by Redouane64** [comment]
thank you guys for your work! ❤️
