### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by niallsalmon** [brave/brave-browser#35165]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.100 Chromium: 120.0.6099.62
Operating System: Mac OS X 14.0.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?
Somewhat

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Closing tabs
2. Changing tabs
3. I was surfing YouTube when it crashed.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/6a780500-f4b8-4b0b-0000-000000000000

**Comment by valynor** [comment]
@niallsalmon update your browser, you are several minor versions behind

**Comment by iefremov** [comment]
stale
