### ISSUE TITLE
Crash ReportBrave Browser closing itself after few seconds.

### ISSUE THREAD

**Issue by RostoRM** [brave/brave-browser#35170]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.114 Chromium: 120.0.6099.199
Operating System: Windows NT 10.0.19045

URL (if applicable) where crash occurred:

The Brave browser closing itself after few seconds after opening there is message that brave didn't shut down correctly.
I downloaded beta version and I have same problem The browser closing itself after few seconds too.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/85860800-f4b8-4b0b-0000-000000000000

**Comment by bsclifton** [comment]
Unfortunately, looks like this crash details are no longer available.

However - the good news is that it doesn't seem to have happened in a long time. I suspect this bug is fixed now as there hasn't been a report in the last 30 days
