### ISSUE TITLE
[iOS] - Crash when deallocating WebState off the main thread

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#35186]
## Description 
iOS crashes when tabs are closed and retained off the main thread.

## Steps to reproduce 

   1. None. No idea how to reproduce it.

## Version/Channel Information:
- Release
   
## Brave version
- All

**Comment by kjozwiak** [comment]
Removing from the `1.63.x` milestone. Once the above has been fixed, it will land in `master` and then will need to be uplifted into `1.63.x`. Once it lands in `master` (which is `1.65.x` at this time), the issue will automatically close/move into the `1.65.x` milestone. It will then be moved to the appropriate milestone when uplifted.
