### ISSUE TITLE
[ads] Custom notification ad text is trancated

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#35183]
The custom notification ad text with particular icons is truncated:

![image](https://github.com/brave/brave-browser/assets/86598290/f17f34c9-b0c7-4681-93d8-6bc7f7a0de52)

**Comment by btlechowski** [comment]
Verified with

Brave | 1.64.91 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 939586e20d208404b83713ea05cf5f6fa7fe3dd5
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/21827


Verified custom notification ad text is truncated at the bottom

![image](https://github.com/brave/brave-browser/assets/34715963/2edd5b0e-d0ab-4bed-b475-1e57449082f2)

**Comment by btlechowski** [comment]
Verified with

Brave | 1.64.91 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 939586e20d208404b83713ea05cf5f6fa7fe3dd5
OS | Windows 10 Version 22H2 (Build 19045.4170)

Verified test plan from https://github.com/brave/brave-core/pull/21827


Verified custom notification ad text is truncated at the bottom

![image](https://github.com/brave/brave-browser/assets/34715963/4c5dbe20-7846-4e24-9e7a-f7e11ae9a71f)

**Comment by btlechowski** [comment]
Verified with

Brave | 1.64.107 Chromium: 123.0.6312.46 (Official Build) (arm64)
-- | --
Revision | cb2648b2e2cf3de3bbd87f1c2826e308ebf2f906
OS | macOS Version 13.1 (Build 22C65)

Verified test plan from https://github.com/brave/brave-core/pull/21827

Verified custom notification ad text is truncated at the bottom

![image](https://github.com/brave/brave-browser/assets/34715963/0cbd9fce-4704-4819-9c78-12be2e712827)
