### ISSUE TITLE
Channel and publisher lists aren't fetched/recovered when Wi-Fi is disabled and then reenabled

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#35185]
## Description 

Channel and publisher lists aren't fetched/recovered when Wi-Fi is disabled and then reenabled

## Steps to Reproduce

   1. install `1.63.101
   2. launch Brave
   3. disable Wi-Fi
   4. open a new-tab page
   5. scroll down
   6. click on `Turn on Brave News`
   7. click on `Customize`
   8. look at the blank channels/publishers
   9. re-enable Wi-Fi

## Actual result:

![Screen Shot 2024-01-05 at 1 39 37 PM](https://github.com/brave/brave-browser/assets/387249/27343b47-19ac-46d0-b31c-e4339cabbe74)

## Expected result:

Should auto-recover when Wi-Fi is reconnected/stable again

<img width="1312" alt="Screenshot 2024-01-08 at 9 35 06 AM" src="https://github.com/brave/brave-browser/assets/387249/813d56e4-87c4-4c26-80f4-6d1e833d76fc">

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.63.101 Chromium: 120.0.6099.199 (Official Build) nightly (x86_64)
-- | --
Revision | 8d3f0a563e185b6a763cc8e210ab24775dfb9047
OS | macOS Version 14.3 (Build 23D5043d)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @fallaciousreasoning @mattmcalister @rebron @brave/qa-team

**Comment by fallaciousreasoning** [comment]
Should be fixed by https://github.com/brave/brave-core/pull/21507
