### ISSUE TITLE
PnaCl component missing in official Brave build

### ISSUE THREAD

**Issue by CamelCaseName** [brave/brave-browser#3519]
## Description 
The official Brave build misses the Portable Native Client (PNaCl), which, for example, is used by the google earth studio.

## Steps to Reproduce

   1. Open Brave
   2. Go to [Earth Studio](https://earth.google.com/studio)

## Actual result:
![error](https://user-images.githubusercontent.com/48067449/53515259-d5201d80-3ac9-11e9-9cc5-bd1a0133302a.png)

## Expected result:
<img width="800" alt="download" src="https://user-images.githubusercontent.com/48067449/53515349-10225100-3aca-11e9-806b-6fb2cd7d8775.png">

## Reproduces how often: 
Every time

## Brave version (brave://version info)
0.60.45 Chromium: 72.0.3626.109 (Official Build) (64-bit)

Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows

### Website problems only:  
It doesn't reproduce with Chrome., and i didn't find any info on the internet on how to install nacl on brave.

**Comment by bsclifton** [comment]
We turn this off intentionally:
https://github.com/brave/brave-browser/blob/0e38ec295eba29c0f0358477a70a2022bcbf70ef/lib/config.js#L74

Is this something we want to enable?
cc: @bbondy @bridiver @diracdeltas

**Comment by diracdeltas** [comment]
according to https://developer.chrome.com/native-client/nacl-and-pnacl, nacl and pnacl are being deprecated

i think we initially turned it off to reduce the security surface area of Brave

**Comment by diracdeltas** [comment]
> Given the momentum of cross-browser WebAssembly support, we plan to focus our native code efforts on WebAssembly going forward and plan to remove support for PNaCl in Q2 2019 (except for Chrome Apps). We believe that the vibrant ecosystem around WebAssembly makes it a better fit for new and existing high-performance web apps and that usage of PNaCl is sufficiently low to warrant deprecation.

from https://developer.chrome.com/native-client/migration

since Q2 2019 starts soon, i'm inclined to mark this wontfix

**Comment by bsclifton** [comment]
@diracdeltas good call 😄 

As we don't have any dev resources allocated to look at this (not high demand and Q2 is around the corner), I'll go ahead and close this out 👍

**Comment by bbondy** [comment]
Agreed on this being wontfix
