### ISSUE TITLE
Site-permissions bubbles are still circular, rather than squares/square-ish

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#35191]
## Description 

Site-permissions bubbles are still circular, rather than squares/square-ish

Found while testing https://github.com/brave/brave-browser/issues/34957

## Steps to Reproduce

1. install `1.63.102`
2. launch Brave
3. load `permission.site`
4. click on `Camera` (or most categories)
5. note the circle-shaped permission bubble
6. click `Allow`
7. note the circle-shaped permission bubble

## Actual result:

`Use Camera?` | `Allowed`
---------|---------
<img width="1689" alt="Screenshot 2024-01-08 at 5 13 24 PM" src="https://github.com/brave/brave-browser/assets/387249/97776e86-44a3-4533-bdfc-cab8b3223602"> | <img width="1689" alt="Screenshot 2024-01-08 at 5 13 27 PM" src="https://github.com/brave/brave-browser/assets/387249/1132fa22-289a-47b1-8e21-90233ae5086e">

## Expected result:

Should be more square/square-ish

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.63.102 Chromium: 120.0.6099.199 (Official Build) nightly (x86_64)
-- | --
Revision | e04c47f4648bb8a13cad74d386e61d33a80d70be
OS | macOS Version 14.3 (Build 23D5043d)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @simonhong @aguscruiz @brave/qa-team

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.63.108 Chromium: 120.0.6099.217 (Official Build) nightly (x86_64)
-- | --
Revision | af39b0a02af610eb272f84079ef80aecc3809261
OS | macOS Version 11.7.10 (Build 20G1427)
```

`Light`

example | example
---------|---------
<img width="2029" alt="Screen Shot 2024-01-10 at 1 14 40 PM" src="https://github.com/brave/brave-browser/assets/387249/074492ad-bb2a-4976-a2d5-6d271305a929"> | <img width="2029" alt="Screen Shot 2024-01-10 at 1 14 45 PM" src="https://github.com/brave/brave-browser/assets/387249/2a4af5f6-4606-4697-8cb0-dfecf8e9d1ba">

`Dark`

example | example
---------|---------
<img width="2029" alt="Screen Shot 2024-01-10 at 1 19 36 PM" src="https://github.com/brave/brave-browser/assets/387249/1cc0f779-f885-4332-af9e-7c3f91f7566a"> | <img width="2029" alt="Screen Shot 2024-01-10 at 1 19 47 PM" src="https://github.com/brave/brave-browser/assets/387249/c8dccff9-9b9e-42d9-8779-304eea1e2ccc">

**Comment by kjozwiak** [comment]
Removing `QA Pass-macOS` as the above will need to be verified via `1.62.x` now that it's been uplifted via https://github.com/brave/brave-core/pull/21548. However, used https://github.com/brave/brave-browser/issues/35191#issuecomment-1885752907 as the needed verification for uplifting as per https://github.com/brave/brave-core/pull/21548#pullrequestreview-1822339799.

The above requires `1.62.144` or higher for `1.62.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.62.144 Chromium: 120.0.6099.217 (Official Build) beta (x86_64)
-- | --
Revision | 75de8d953f6a5686e425d46d7f0dc9284dc1c064
OS | macOS Version 13.6.3 (Build 22G436)
```
