### ISSUE TITLE
Fix bitcoin balance calculation.

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#35195]
Bitcoin account's addresses list should include next change and receive addresses so new transactions to these addresses correctly affect balance.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.63.141 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | aa92f6cecec7f6c576bd1cf120f4cf359d770159
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21518](https://github.com/brave/brave-core/pull/21518)
- Verified pending balance for sender shows negative value of send amount+fee
- Verified pending balance for receiver shows sent value

Sender | Receiver
-- | --
![Screenshot 2024-02-05 044446](https://github.com/brave/brave-browser/assets/17010094/cdbaf058-5a47-4be9-8e1d-c89ab74a47c9) | ![Screenshot 2024-02-05 041246](https://github.com/brave/brave-browser/assets/17010094/c27849f9-4c52-4a2b-834b-baf9e4e8f59b)
