### ISSUE TITLE
Dependency problem of copying strategy

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#352]
I checked that modifying overridden file doesn't trigger rebuild on Win10.

Test steps
1. Check modification time of  `src/out/Debug/obj/chrome/common/common.lib`
2. Modify `src/brave/chromium_src/chrome/common/url_constants.cc`
3. Build
4. Same modification time with step 1.
5. Modify `src/chrome/common/url_constants.cc`
6. Build
7. Modification time was updated

To use copying strategy, we should fix this problem asap.

@yrliou

**Comment by bbondy** [comment]
one hacky way we can do this is provide an option to touch all chromium_src files which is used by default, but that you can pass a flag to override when you do incremental builds.
