### ISSUE TITLE
Add BTC to purchasable assets UI

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#35204]
## Description 

Add Bitcoin as an asset that can be purchased from the Brave Wallet UI

## Steps to Reproduce

   1. Go to Buy screen in wallet
   2. search for "btc"

## Actual result:

No results

## Expected result:
BTC should be available for purchase

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.63.141 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | aa92f6cecec7f6c576bd1cf120f4cf359d770159
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from issue description
- Verified BTC is available as an option in on-ramp and off-ramp
- Encountered [#35796](https://github.com/brave/brave-browser/issues/35796)

On-Ramp |  Off-Ramp
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/079db925-38ac-4ba0-8ad6-414b53266a05> | <video src=https://github.com/brave/brave-browser/assets/17010094/2d54c947-652b-497f-8a5f-b0b768ac618c>
