### ISSUE TITLE
Add setting for vertical tabs scroll bar

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#35207]
## Description 

Add a setting in brave://settings/appearance Vertical tabs to show a scrollbar. Default off.
Follow-up to [31204](https://github.com/brave/brave-browser/issues/31204) where scroll bar was added for vertical tabs via a flag.

## Brave version (brave://version info)

Target 1.63.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.64.52 Chromium: 121.0.6167.139 (Official Build) nightly (x86_64)
-- | --
Revision | 74312201fe92e37ad0cae858c52ef03ef15f6e76
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Default (`Show scrollbar` is `Disabled`)

## `Show scrollbar` is set to `Enabled`

**Comment by btlechowski** [comment]
Verified with



### Default (`Show scrollbar` is `Disabled`) - `PASSED`

<details>

### Steps:
1. installed `1.64.x`
2. launched Brave
3. opened a few tabs
4. context-clicked and chose `Use Vertical Tabs`
5. opened `brave://settings/appearance` and confirmed `Show scrollbar` was defaulted to `Disabled` / unchecked
6. opened a plethora of tabs


### Confirmed when wheel-scrolling/focusing/hovering over the tab list, no scrollbars were painted

![image](https://github.com/brave/brave-browser/assets/34715963/3f8ddabe-9a90-4a23-80c1-83e002ef389d)|![image](https://github.com/brave/brave-browser/assets/34715963/619596df-b659-4951-9406-e3e506bb9e74)|![image](https://github.com/brave/brave-browser/assets/34715963/3074a580-68ee-4bd0-b1a6-6afd39cacc30)
--|--|--

</details>



### `Show scrollbar` is set to `Enabled` - `PASSED`

<details>


### Steps:
1. installed `1.64.x`
2. launched Brave
3. opened a few tabs
4. context-clicked and chose `Use Vertical Tabs`
5. opened `brave://settings/appearance` and confirmed `Show scrollbar` was defaulted to `Disabled` / unchecked
6. toggled `Show scrollbar` to `Enabled` / checked
7. opened a plethora of tabs
8. scrolled the tabs pane

### Confirmed scrollbars were dynamically painted on scrolling (macOS behavior)

![image](https://github.com/brave/brave-browser/assets/34715963/74f914db-f884-46f4-a631-6daa2c213170)|![image](https://github.com/brave/brave-browser/assets/34715963/c0166a8b-2514-46a8-9814-4d921f270006)|![image](https://github.com/brave/brave-browser/assets/34715963/2637748f-15bb-4b1c-8354-ba94f7f6773c)
--|--|--

</details>

**Comment by stephendonner** [comment]
## Verified `PENDING` 

## Default (`Show scrollbar` is `Disabled`) - `PENDING`

## `Show scrollbar` is set to `Enabled` - `PENDING`
