### ISSUE TITLE
Update saved groups style to match current groups in tab bar

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#35202]
## Description 

- [ ] We need to update the style of the saved groups to match our new style. We can keep the dimensions in the bookmarks bar, but need to change the background and remove the outline
- [ ] Additionally, saved groups in the toolbar need to have their icon color match the text color
- [ ] And replace the icon with this one from Nala `product-sync`

## Steps to Reproduce

   1.  Enable saving groups via flags
   2. 
<img width="787" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/effe4492-65aa-4d49-98bb-72e74964f838">

   3. Save a group
   4. See how it appears on bookmarks bar

## Actual result:

<img width="348" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/9768d9c7-f384-4cb3-adfb-8bc10dbca27b">

<img width="142" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/f89650f8-2df9-4cf2-9259-149a218fe608">

## Expected result:
<img width="675" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/f32ef084-e44d-4f56-b5c8-86434d09c774">

Design here:
https://www.figma.com/file/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?type=design&node-id=125%3A9048&mode=design&t=lFdxf2XIs3s3Hw8I-1

## Reproduces how often: 

Always

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by arjpar** [comment]
+1 for this issue as the color choice/contrast makes it very hard to see the "saved tab group" (arrow) icon

**Comment by MadhaviSeelam** [comment]
Adding `QA/Test-All-Platforms` as this is a new feature.

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave	1.65.90 Chromium: 123.0.6312.58 (Official Build) beta (x86_64) 
Revision	f5ca64cd15d0d5c90f17b7d5213b6e2dd725d66a
OS	macOS Version 14.4 (Build 23E214)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
Revision	5d9143e1a0812c53bdc27fd5384591254306a88c
OS	Linux
```
