### ISSUE TITLE
Have button on `brave://adblock` page to force-update all adblock components

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#35216]
It would help adblock breakage remediation tremendously if users can force-update all adblock components by going to brave://adblock and pressing a button instead of having to go to brave://components and clicking each Update button manually. 

The button could live under the Filter lists section:

Subsection Title: **Update all filter lists**
Helper Text: _Manually update all filter lists to latest version_
Button Text: `Update lists`

**Comment by stephendonner** [comment]
cc @aguscruiz

**Comment by ShivanKaul** [comment]
iOS corollary: https://github.com/brave/brave-ios/issues/8629

**Comment by zenparsing** [comment]
@ShivanKaul which components would this button update? Given the placement of the button, it seems like it would just update the components associated with enabled filtered lists. Are there any other components that would need to be updated as well?

**Comment by ShivanKaul** [comment]
> enabled filtered lists

Right, so enabled filter lists (like EasyList Cookie, or whichever ones the user has selected from the list), as well as the following adblock related components:

```
Brave Ad Block List Catalog
Brave Ad Block Updater 
Brave Ad Block Resources Library
```

Additionally, it would be good to update any custom filter lists the user has added, but I don't think this is a showstopper.

**Comment by ShivanKaul** [comment]
Ah actually, @antonok-edm tells me that he has to build "update all adblock lists + components" functionality for https://github.com/brave/brave-browser/issues/35164. So might be easier to use that!

**Comment by antonok-edm** [comment]
> a "update all adblock lists + components" function for https://github.com/brave/brave-browser/issues/35164

@zenparsing See this upcoming [`AdBlockComponentServiceManager::CheckAdBlockComponentsUpdate`](https://github.com/brave/brave-core/pull/21868/files#diff-a5b1ae168ae0a3b0ef4bbbdbaac5d78b37be2c23a01a071f7911b3b888621130R265).

> it would be good to update any custom filter lists the user has added, but I don't think this is a showstopper.

+1. I'd suggest a similar implementation on `AdBlockSubscriptionServiceManager`.

**Comment by bsclifton** [comment]
I believe @deeppandya is looking at this on Android 

This should make https://github.com/brave/brave-browser/issues/35166 much easier to implement! 😄

**Comment by deeppandya** [comment]
@ShivanKaul android issue for the same : https://github.com/brave/brave-browser/issues/35270

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.67.85 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | d01060f5ec155e6eb64a335203663a29c0e5d81f
OS | Windows 11 Version 23H2 (Build 22631.3593)
```

**Comment by MadhaviSeelam** [comment]
Adding `QA/Test-All-Platforms` label to verify force-update to the adblock components

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using

```
Brave | 1.67.100 Chromium: 125.0.6422.112 (Official Build) beta (x86_64)
-- | --
Revision | 34fcbb6655521b55468af6c63601a8e3c5d24cd2
OS | macOS Version 14.5 (Build 23F79)
```


<details>
<summary>Case 1: New install Update successful - PENDING </summary>

1. installed `1.67.100`
2. launched Brave
3. opened `brave://settings/shields/filters`
4. in a new window, `open brave://components`
5. make sure that you can see the content of both windows at the same time.
6. press the "Update lists" button on the settings page

#### Confirmed `Lists updated` button shown as expected
#### Confirmed below Adblock components are updated successfully with the statuses as expected when clicked `Update lists` button. 

- Brave Ad Block Updater - `Component already up to date`
- Brave Ad Block First Party Filters - `Component already up to date`

#### Confirmed default lists `EasyList Cookie` and `Fanboy's Mobile Notifications` are updated
<details>

video

</details>

#### Confirmed user selected lists `YouTube Mobile Distractions` & `Fanboy's Annoyances` are updated

<details>

video

</details>

</details>

<details>
<summary>Case 2: New install Updated failed - PENDING </summary>

1. installed `1.67.100`
2. launched Brave
3. opened `brave://settings/shields/filters`
4. In a new window, `open brave://components`
5. make sure that you can see the content of both windows at the same time.
6. disconnect internet/Wi-Fi
7. press the "Update lists" button on the settings page

#### Confirmed `Updated failed - Retry` button shown as expected
#### Confirmed Adblock components are shown `Update error` status as below when clicked `Update lists` 
button. 

- Brave Ad Block Updater - `Update error`
- Brave Ad Block First Party Filters - `Update error`

video

</details>


<details>
<summary>Case 3: Upgrade - PENDING </summary>

1. installed `1.66.115`
2. launched Brave
3. opened `brave://settings/shields/filters`
4. verified `Show full list` button is shown
5. opened `brave://components` in a new window and verified components are verified
6. closed the browser and renamed the profile brave-browser-beta
7. installed `1.67.87`
8. relaunched Brave
10. opened both windows and can see the content of both windows at the same time.
11. confirmed `Update Lists` button is shown
12. Press the "Update lists" button on the settings page
13. Verify that AdBlock components are updated, as reflected on the `brave://components` page

Confirmed adblock components are updated as expected. 

1.66.x | 1.67.x (Update lists) | 1.67.x (Lists updated)
---- | ----- | -----
ss one | ss two | ss three

</details>

<details>
<summary>Case 4: Buttons UI (Light theme) - PENDING</summary>

Update Lists | Lists Updated
-------- | ------


</details/>

**Comment by superlex** [comment]
Currently, it looks like the button update only default filter lists.
I think it should update all filter lists, that is filter lists added by user as well.

<img width="661" src="https://github.com/brave/brave-browser/assets/1375223/2a663bb1-b362-4161-a322-f48c05c05856">

This is important above all on Android, where there isn't an option yet to update custom filter lists.

<img width="286" src="https://github.com/brave/brave-browser/assets/1375223/18e238f0-3d8a-4e7d-89f1-904efa8ab7c3">

**Comment by ShivanKaul** [comment]
> Currently, it looks like the button update only default filter lists.

This should update all optional and default enabled filter lists. Is that not what you're seeing? For custom filter lists, we could add a separate "Update all" button (since it's in a separate section) but that's a more advanced use-case.

**Comment by superlex** [comment]
Thanks for your reply.
Yes, I meant what you said, and I agree with "Update all" button idea.
