### ISSUE TITLE
Expose the first party list in iOS

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#35210]
## Description 

We don't use the first party list in iOS yet. We need to make this list available to iOS

Note: this is a temporary solution. A real solution should be [here](https://github.com/brave/brave-browser/issues/35209), which is a much bigger and invasive change which has a ton of other benefits.

Additional work will need to be done in iOS to use these new services:
https://github.com/brave/brave-ios/issues/7611

**Comment by LaurenWags** [comment]
@cuba could you provide a test plan for this for the various OSes? If this doesn't need to be tested on Desktop and Android we can also remove the `OS/Desktop` and `OS/Android` labels. Labeling as `QA/Blocked` until we have this info. Thanks!

**Comment by bsclifton** [comment]
@LaurenWags details added above 😄👍

**Comment by LaurenWags** [comment]
Thanks @cuba @bsclifton - removed `QA/Blocked` so this can get verified on iOS 👍🏻

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.5
Brave build: 1.66 (107)
BraveCore: 1.66.107 (125.0.6422.41)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/35210#issue-2072900978
2. *Verify*

**ACTUAL RESULTS:**
- Verified that https://acala-bridge.com/ website is blocked when Brave `Shields` is ON
- Verified that `This Site May Attempt to Track You Across Other Sites` screen is not shown when Brave `Shields` is OFF

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/5eab4a40-0e3a-41b7-9bf2-30981335acbe) | ![2](https://github.com/brave/brave-browser/assets/128532965/5b486d62-e5be-452d-9caa-1aa7adc57533) |

https://github.com/brave/brave-browser/assets/128532965/6c29873b-7078-4bea-ad83-a4940bfc8c2a
