### ISSUE TITLE
If news feed is empty, there's no indication on NTP that News is available or enabled 

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#35213]
## Description 

When there is no content to show in the feed, there's no "News" indicator on the NTP. This is different than v1 so I'm not sure if it's intentional.

## Steps to Reproduce

   1. Clean profile, close and relaunch to pull griffin
   2. Open NTP
   3. Enable News
   4. Unfollow "Top Sources"
   5. Refresh feed - no content displayed as expected
   6. Scroll up to NTP
   7. There's no indication that News is enabled/available. This differs from v1 which still showed an indicator on the NTP that News was enabled/available even though there wasn't content.

## Actual result:

1.61.x | 1.62.x
--- | ---
<img width="1192" alt="1 61 x" src="https://github.com/brave/brave-browser/assets/28145373/b0e61b40-59fa-48ab-9706-69c1a3912a48"> | <img width="1294" alt="1 62 x" src="https://github.com/brave/brave-browser/assets/28145373/c0ec80bb-b408-43ea-8678-c0f7fa4b82f4">

## Expected result:

Perhaps it makes sense to just show the small "News" indicator as it shows before Brave News is enabled:

<img width="153" alt="News" src="https://github.com/brave/brave-browser/assets/28145373/c26c1dc1-a697-4646-af0c-981c4a1b4ef9">

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.62.135 Chromium: 120.0.6099.199 (Official Build) beta (x86_64)
-- | --
Revision | c66fd7306403245e6c370da9f287f69a5cf46a10
OS | macOS Version 13.6.3 (Build 22G436)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? unsure, probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @brave/qa-team @fallaciousreasoning @LorenzoMinto

**Comment by Uni-verse** [comment]
Confirmed Android is not impacted using same version and steps as above. 

Example | Example
-|-
![Screenshot 2024-01-09 at 5 10 50 PM](https://github.com/brave/brave-browser/assets/17885425/5ec6fb8d-f18d-4a64-8a49-6a49fa9cad46) | ![Screenshot 2024-01-09 at 5 11 17 PM](https://github.com/brave/brave-browser/assets/17885425/4aadd63d-15d3-4303-a80d-f79b1db8b71a)

**Comment by kjozwiak** [comment]
The above requires `1.62.142` or higher for `1.62.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.62.144 Chromium: 120.0.6099.217 (Official Build) beta (x86_64)
-- | --
Revision | 75de8d953f6a5686e425d46d7f0dc9284dc1c064
OS | macOS Version 11.7.10 (Build 20G1427)
```
