### ISSUE TITLE
Crash when trying to open brave://sync in Guest Window

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3522]
Follow up from https://github.com/brave/brave-browser/issues/2852

## Steps to Reproduce

   1. Open Guest Window
   2. Open `brave://sync`

## Actual result:

Crash

## Expected result:
No crash

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.62.8 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Brave | 0.61.39 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Related issues: https://github.com/brave/brave-browser/issues/3003. 

@simonhong  I have not seen this issue reported for Guest Window.

cc @brave/legacy_qa

**Comment by simonhong** [comment]
@btlechowski  This was also fixed by https://github.com/brave/brave-core/pull/1704.
That PR handles crash on Tor and Guest both.

**Comment by kjozwiak** [comment]
@btlechowski mind taking a look and seeing if it's an issue on `0.63.x`. Might have to build from source as we don't have nightly builds yet. If you would like, I can check on macOS as I have a recent build already 👍

**Comment by btlechowski** [comment]
Based on https://github.com/brave/brave-browser/issues/3522#issuecomment-468123638 the issue was fixed in https://github.com/brave/brave-core/pull/1704

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.63.4 Chromium: 73.0.3683.67 (Official Build) dev (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from the description
![image](https://user-images.githubusercontent.com/34715963/54250453-2279a180-4544-11e9-8ab1-621f9fc0c48c.png)
