### ISSUE TITLE
`Not allowed to load local resource: brave://rewards/` when trying to click on `Ad` icon in `News v2`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#35235]
## Description 

`Not allowed to load local resource: brave://rewards/` when trying to click on `Ad` icon in `News v2`

## Steps to Reproduce

1. install `1.63.106`
2. launch Brave
3. enable `Brave Ads` / `Brave Rewards` from the URL bar
4. open a new-tab page
5. scroll down
6. click on `Turn on Brave News`
7. scroll until you see an `Ad`
8. click on the `Ad` icon, which links to `brave://rewards`

## Actual result:

Nothing happens; Unable to load `brave://rewards` message shows up in the `Developer Tools`' `Console`

example | example
---------|----------
<img width="1308" alt="Screenshot 2024-01-10 at 1 05 56 AM" src="https://github.com/brave/brave-browser/assets/387249/df799c2f-409b-4162-a88e-4eba0c6cf395"> | <img width="1308" alt="Screenshot 2024-01-10 at 1 00 42 AM" src="https://github.com/brave/brave-browser/assets/387249/57afa4bf-2eca-4b54-8e65-a94cff55588b">

## Expected result:

If we link to it, it should work, so should it load `brave://rewards`?

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.63.106 Chromium: 120.0.6099.199 (Official Build) nightly (x86_64)
-- | --
Revision | 281307652d5d2dca2705422c9b01e68316d22f5f
OS | macOS Version 14.3 (Build 23D5043d)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @iambrianfung @fallaciousreasoning @rebron @LorenzoMinto @mattmcalister  @btlechowski @zenparsing @tmancey  @brave/qa-team

**Comment by stephendonner** [comment]
Definitely a regression, as this works in

```
Brave | 1.61.114 Chromium: 120.0.6099.199 (Official Build) (x86_64)
-- | --
Revision | e0f6e091fe79c029231a86e8cdcc5fbe70bcddbe
OS | macOS Version 14.3 (Build 23D5043d)
```

example | example
---------|---------
<img width="1312" alt="Screenshot 2024-01-10 at 1 12 51 AM" src="https://github.com/brave/brave-browser/assets/387249/3e5c8c21-96f2-445c-a503-06999a8ad1ed"> | <img width="1312" alt="Screenshot 2024-01-10 at 1 12 54 AM" src="https://github.com/brave/brave-browser/assets/387249/9c683ae3-54ee-42f0-abd9-d6ab1f0f5a86">

**Comment by stephendonner** [comment]
Doesn't work either in 


Brave | 1.62.134 Chromium: 120.0.6099.199 (Official Build) beta (x86_64)
-- | --
Revision | 62903636ca583d9c0a0f758e98d15da6c3ee08e7
OS | macOS Version 14.3 (Build 23D5043d)

<img width="1322" alt="Screenshot 2024-01-10 at 1 20 14 AM" src="https://github.com/brave/brave-browser/assets/387249/71c5721c-7b43-498b-8a0b-d4abbbe925db">

**Comment by btlechowski** [comment]
We do not allow `brave://` schema for inline ad's target url, but clicking the `Ad` icon should open `brave://rewards`.

**Comment by Miyayes** [comment]
This seems like a Brave News side issue. If you need to bring in help from rewards-client team (Kevin, Emerick, Szilard, etc.), please let me know.

**Comment by kjozwiak** [comment]
The above requires `1.62.142` or higher for `1.62.x` verification 👍

**Comment by btlechowski** [comment]
Verified with

Brave | 1.62.144 Chromium: 120.0.6099.217 (Official Build) beta (64-bit)
-- | --
Revision | 75de8d953f6a5686e425d46d7f0dc9284dc1c064
OS | Linux

Verified test plan from the description

Verified `brave://rewards` is opened after clicking `Ad` icon on Brave News inline ad

![image](https://github.com/brave/brave-browser/assets/34715963/ddb4e7cd-42ef-4928-8ab6-254ea2f3337f)|![image](https://github.com/brave/brave-browser/assets/34715963/30a13904-3225-44cf-8b75-c65a1c588fe1)
--|--

Logged
https://github.com/brave/brave-browser/issues/35353
https://github.com/brave/brave-browser/issues/35357

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.62.144 Chromium: 120.0.6099.217 (Official Build) beta (x86_64)
-- | --
Revision | 75de8d953f6a5686e425d46d7f0dc9284dc1c064
OS | macOS Version 11.7.10 (Build 20G1427)
```

example | example
---------|---------
<img width="1312" alt="Screen Shot 2024-01-16 at 3 52 32 PM" src="https://github.com/brave/brave-browser/assets/387249/11d45b44-e9dc-4cd6-b749-0808d349e54d"> | <img width="1498" alt="Screen Shot 2024-01-16 at 3 53 18 PM" src="https://github.com/brave/brave-browser/assets/387249/52455218-f836-4ae1-b2b3-f3e05102e30d">

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.62.147 Chromium: 120.0.6099.234 (Official Build) (64-bit)
-- | --
Revision | 3b25c3743150a54485dea24f0ceb1e69d6db51bc
OS | Windows 10 Version 22H2 (Build 19045.3930)
```

example | example
----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/80d43b02-7695-4a51-876e-9d9ddca57a7f) | ![image](https://github.com/brave/brave-browser/assets/387249/1d2226bd-c9c9-4f21-8f3f-c4004c253e0f)
