### ISSUE TITLE
[ads] Frequency capping enhancements

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#35239]

**Comment by btlechowski** [comment]
Verified with

Brave | 1.63.149 Chromium: 121.0.6167.164 (Official Build) beta (64-bit)
-- | --
Revision | 16509c04a66afcc00d180c0b62a887b9fc4776a2
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/21538

<details>

</details>
