### ISSUE TITLE
Right Click does not highlight text on menubar

### ISSUE THREAD

**Issue by FirefoxWas** [brave/brave-browser#3523]
## Description 

The right click button dose not highlight the text on the minubar.

## Steps to Reproduce

   1.  right click
   2. it dose not highlight the text when i click the words. 

## Actual result:

![image](https://user-images.githubusercontent.com/32176749/53540339-f7b23680-3ac9-11e9-85fc-fcad4edc11ec.png)

## Brave version (brave://version info)

Brave | 0.60.45 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows
JavaScript | V8 7.2.502.25
Flash | 32.0.0.142 C:\WINDOWS\system32\Macromed\Flash\pepflashplayer64_32_0_0_142.dll
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,AutofillSaveCardSignInAfterLocalSave,AudioServiceOutOfProcess,AutofillServerCommunication,UnifiedConsent --flag-switches-begin --flag-switches-end -- https://go.microsoft.com/fwlink/?LinkId=517009
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\Abran\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | c134752e-f685ead32c707b42-dcf7018a411b6d4e-3f4a17dfd01ab0d3-5ac89433e006338-3f4a17dfb0271b40-360900151a0d11d4-2f9febdfe202a358-3f4a17df66df3e9d-a85d0b2fb7e2524c-c92d551c411c711e-3f4a17dfb3888d8d-afba0f916c18ba9d-3f4a17df8982496f-3f4a17df61832c80-3f4a17dfcc20827f-77c422c1d411afe-60fc1672591560a-29acad42db4845-ace4e13874785582-3f4a17df241fff6c-ddf208789853922b-3f4a17df9def365c-9def365c2342e907-3f4a17df9ca1387e-3f4a17df1c752ce9-1c752ce941e765a5-3f4a17dfab3d6cfd-3f4a17df776de70c-e0278d3ded9149a9-3f4a17dfa5cb8590-3f4a17df34d450b1-3f4a17df6c6c4f61-3f4a17df8f4db35c-3f4a17df76b48ab8-d4bd105cc70841c8-a256700714bdbe54-e8c7a65bd8343fa3-3f4a17df8ee5ed19-c3125ea274658432-fa79b94c7f7844ec-69483e079e201a2b-3f4a17df652e14d1-f4950e9927212adc-27212adc591576c8-3f4a17df249dd49a-3f4a17df5274eb09-3f4a17df36115667-3f4a17dfceff87ec-3f4a17df44827ee5-3f4a17df8ca44045-3f4a17df334aa58d-3f4a17df3f79ac13-3f4a17df8f1e27f-3f4a17df345b5b61-3f4a17dfedbcf7c5-ddf1844d77bbdddc-3f4a17df5485fc4d-3f4a17dfde47491b-3f4a17df93731dca-3f4a17df9b4c4257-3f4a17df8fa604e0-ace4e13843f62d3b-3f4a17df4ae380f4-3f4a17df165e16d1-3f4a17df9e5c75f1-30e1b12b6fa07eb4-7282ca762981bcb4-3f4a17df5139837c-3f4a17df4934552d-3f4a17df7f8176d9-3f4a17dff7217a71-b204717823a898eb-fc93cf747a5ba892-3f4a17dfd1cd70a5-80f9a33e4ea303a6-3f4a17dfb19465ab-b19465abe5373d71-3d47f4f46e6e0c7e-3f17a7d895876445-2b71ffe4d92562a9-441539fd2b33233e-881ca6c9b363a81f-3f4a17df4da5ae82-3f4a17df56302f8c-2f882e7014c5a050-61ceed18dc5b1f29-dc5b1f29cc54eb06-803f8fc4b2612322-8a9180b2cac0a91c-3f4a17dfdf072bba-9a6c5085f56e0452-3f4a17df8576baf1-3f4a17dff3ea30a0-3f4a17df3038aa2e-3f4a17df51b9b54d-3f4a17df7345ea6-3f4a17df9a2f4e5b-4bc735ae1354da85-f1a864dc17507c76-3f4a17df6844d8aa-669a04e0494d8760-3f4a17dff9e5da91-508355f5fcdd9ed9-fcdd9ed93a4029d-d7f231f3bbb8f811-3f4a17dfb0ea13bc-3f4a17df41aa6aaa-da82a76f94e68624-803f8fc4cc73f8a1-3f4a17dfb4e8892d-3f4a17df10a311eb-10a311eb8834fcca-3f4a17df6204e469-3f4a17df71140742-3f4a17df3f33c9bd-3f4a17dfe9ce63c1-36ab09a2ea0f933d-29e3c6de493ac2c5-803f8fc4

**Comment by bsclifton** [comment]
@FirefoxWas do you have more specific information about the problem?  

For example: are you saying that as you move the mouse up and down (per your screenshot), you're not seeing the menu items highlight? (ex: `Back` or `Reload`)?

Here's a screen capture of what I think you mean:
![highlight](https://user-images.githubusercontent.com/4733304/53547673-df074800-3aec-11e9-9957-539a52bb8e74.gif)

If this is the case, can you please try disabling hardware acceleration? It should be present in brave://settings but you can also try passing in `--disable-gpu` from the command line

**Comment by FirefoxWas** [comment]
Hi  Brian Clifton

thats what i mean by   move the mouse up and down (per your
screenshot  you're not seeing the menu items highlight? it dose not do
that.

Thanks

**Comment by FirefoxWas** [comment]
Hi

It works by disabling hardware acceleration. thanks
