### ISSUE TITLE
Exclude count should be fetch from the db

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#3524]
We currently have excluded number saved in the state where we should fetch it from the db.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

Used test plan from https://github.com/brave/brave-core/pull/1803
Encountered https://github.com/brave/brave-browser/issues/3808
