### ISSUE TITLE
[Android] Report invalid websites with correct domain

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#35244]
## Description 
Instead of reporting invalid domain, current webcompat reporter uses `chrome-error://chromewebdata` as domain. 

## Steps to reproduce 

   1. Type `brokenlink133.com` in search bar
   2. Disable brave shields
   3. Open `Report a broken site`

## Actual result 
![Screenshot_20240108-135722](https://github.com/brave/brave-browser/assets/5146988/95685f82-bcd0-4e6c-b4fc-d48a0420adc6)

## Expected result
`Report a broken site` should show the right domain

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.64.95 Chromium: 122.0.6261.94 (Official Build) beta (64-bit) 
Revision	6f4193fbcee7c358ae3684f777faa9f12e52206e
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured correct domain is reported for broken sites. 

Example | Example | Example
-|-|-
![Screenshot 2024-03-05 at 6 49 12 PM](https://github.com/brave/brave-browser/assets/17885425/15ddfa30-fe00-44bb-a371-08b30ddf421f) | ![Screenshot 2024-03-05 at 6 49 17 PM](https://github.com/brave/brave-browser/assets/17885425/8dad2c5b-4cf7-4365-954d-edcf27bf5849) | ![Screenshot 2024-03-05 at 6 49 23 PM](https://github.com/brave/brave-browser/assets/17885425/5c07b969-023e-4cba-9496-7963040f56c7)
