### ISSUE TITLE
Restyle PIP window

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#35259]
https://www.figma.com/file/RxyQnpxi9qtf5HmnAj1yH0/Desktop-Playlist?type=design&node-id=1%3A29&mode=design&t=qd8wPCr4slkQFIUU-1

Currently:
<img width="260" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/af0812db-ecce-4872-bd7d-0a51acc49be0">

Should be:
<img width="475" alt="image" src="https://github.com/brave/brave-core/assets/5474642/ec274591-e501-4080-914a-bb2ddd621c52">

* Back to tab button should be next to close button on the top
* Other controls should be aligned middle.

**Comment by Emi-Emi-Emi** [comment]
@sangwoo108 
The new update doesn't look good in Nightly 1.13.113 in Windows, Windows 11 at least.

![image](https://github.com/brave/brave-browser/assets/152097351/b123fb72-e9f9-4c2c-b6fb-e596c5ab1f59)

Also because of the being are misplaced, only the pause/play button shows and doesn't allow to resize from top-left corner, because the button is there.

**Comment by TEMP-ACCOUNT-m4C5gRm32s3Z** [comment]
![image](https://github.com/brave/brave-browser/assets/156566258/aa8b3a69-7d7b-4130-8687-17509bf45089)

This is Win11 in latest Nightly, where this messed up with the PiP.

**Comment by sangwoo108** [comment]
> ![image](https://private-user-images.githubusercontent.com/156566258/296536670-aa8b3a69-7d7b-4130-8687-17509bf45089.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDYxMzAsIm5iZiI6MTcwNTMwNTgzMCwicGF0aCI6Ii8xNTY1NjYyNTgvMjk2NTM2NjcwLWFhOGIzYTY5LTdkN2ItNDEzMC04Njg3LTE3NTA5YmY0NTA4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwODAzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmQ1OWUwMjkwYzU1YjJhZDZjMzA1ZGE4YzM3MTE4MjQwOGFlZDNlZDRjNzBiMjUyODExZmJiOTkwMGRiNzdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KZ2cSXvd_g0TMMm23Zwi3zlOZu0sBrnHgZTgpNRGNvo)
> 
> This is Win11 in latest Nightly, where this messed up with the PiP.

Thanks, let me check it out

**Comment by sangwoo108** [comment]
https://github.com/brave/brave-core/pull/21576 This patch seems to fix the bug too. I'll check it again when it's released on nightly

**Comment by LaurenWags** [comment]
This can be tested along side https://github.com/brave/brave-browser/issues/35263 cc @brave/qa-team

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.63.134 Chromium: 121.0.6167.85 (Official Build) beta (64-bit)
-- | --
Revision | cdcba6ef408b305ce19b1a9b3fabbb5e9e3b36bf
OS | Windows 11 Version 23H2 (Build 22631.3085)
```

Fresh Install:
<details>

**_Video_**

1. Installed 1.63.134
2. launched Brave
3. opened https://googlechrome.github.io/samples/media-session/index.html in a new tab
4. clicked `Video` link to open in a new tab via context menu 
5. clicked three dot menu in the player to open `PIP` window
6. clicked `X` 

- Confirmed PIP shows `Back to tab` button is next to close button on the top right and works as expected
- Confirmed other media controls (Previous track, Next track, Pause & Play) are aligned in the middle of the window and working as expected 
- Confirmed clicking on `X` works as expected

example | example | example 
---- | ---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/f53f7724-070f-4992-85eb-ef04ea47e34a)|![image](https://github.com/brave/brave-browser/assets/98358127/91d1867c-bd76-4891-9213-0b8530813765)|![image](https://github.com/brave/brave-browser/assets/98358127/d6b6d390-034b-4b72-aabc-e3f18a7c7b2d)

**_Video conferencing_**
 
example | example | example | example
---- | ---- | ---- | -----  
![image](https://github.com/brave/brave-browser/assets/98358127/ee0cd204-4f42-4dbf-96ea-63b6c8af7889)|![image](https://github.com/brave/brave-browser/assets/98358127/017dd00a-95ac-4616-adf5-986d83e4fb8b)|![image](https://github.com/brave/brave-browser/assets/98358127/a6fe3bfb-6b8f-461a-92e2-c299ef0fbf24)|![image](https://github.com/brave/brave-browser/assets/98358127/52023593-66a6-4fb6-8a5e-7cd34ae21bfb)

**_Slide_**

example | example | example 
---- | ---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/8e465284-b188-4d8c-937f-b07b33694a31)|![image](https://github.com/brave/brave-browser/assets/98358127/7177a718-db73-47de-acfe-1cfadad4aa97)|![image](https://github.com/brave/brave-browser/assets/98358127/433b662d-5832-43d3-8298-a3f051c1cc32)

**_PIP window via media control in the toolbar_**

1. Opened https://googlechrome.github.io/samples/media-session/video.html in a new tab
2. clicked `Video` link to open in a new tab via context menu 
3. played a video
4. clicked media control in the toolbar

- Confirmed PIP shows `Back to tab` button is next to close button on the top right and works as expected
- Confirmed other media controls (Previous track, Next track, Pause & Play) are aligned in the middle of the window and working as expected 
- Confirmed clicking on `X` works as expected

example | example 
---- | ---
![image](https://github.com/brave/brave-browser/assets/98358127/2e017acb-72fc-4162-bace-ac8e87877953)|![image](https://github.com/brave/brave-browser/assets/98358127/51e095b6-c825-4665-9ad4-a7ac15b3535b)

</details>

Upgrade
<details>

1. Installed 1.62.153
2. launched Brave
3. opened https://googlechrome.github.io/samples/media-session/index.html in a new tab
4. clicked `Video` link to open in a new tab via context menu 
5. clicked three dot menu in the player to open `PIP` window
6. opened Video Conferencing and Slides as well
7. closed Brave
8. renamed the profile Brave-Browser-Beta
9. installed 1.63.134
10. relaunched Brave

- Confirmed PIP shows `Back to tab` button is next to close button on the top right and works as expected
- Confirmed other media controls (Previous track, Next track, Pause & Play) are aligned in the middle of the window and working as expected 
- Confirmed clicking on `X` works as expected

`1.62.x`
example | example | example
---- | ---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/b6c4d356-9693-42ae-b1db-d38ec3d8f1ba)|![image](https://github.com/brave/brave-browser/assets/98358127/28e53794-9410-4229-9275-e86990f6c556)|![image](https://github.com/brave/brave-browser/assets/98358127/02627fb4-f718-4f01-838a-6b06e4813a41)

`1.63.x`
example | example | example
---- | ---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/ab5668e2-80c6-43a6-a12a-2da641cbb235)|![image](https://github.com/brave/brave-browser/assets/98358127/81680437-7962-4529-b2b5-a3116f7974bd)|![image](https://github.com/brave/brave-browser/assets/98358127/ab823a30-c9c2-4640-b01e-ae2bc2847c32)
</details>

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using
```
Brave | 1.63.138 Chromium: 121.0.6167.85 (Official Build) beta (x86_64)
-- | --
Revision | 742a3bdf71b710125a1c1dd8e89981b9009a87bc
OS | macOS Version 11.7.10 (Build 20G1427)
```

Fresh Install
<details>

**_Video_**

1. Installed 1.63.134
2. launched Brave
3. opened https://googlechrome.github.io/samples/media-session/index.html in a new tab
4. clicked `Video` link to open in a new tab via context menu 
5. clicked three dot menu in the player to open `PIP` window
6. clicked `X` 

- Confirmed PIP shows `Back to tab` button is next to close button on the top right and works as expected
- Confirmed other media controls (Previous track, Next track, Pause & Play) are aligned in the middle of the window and working as expected 
- Confirmed clicking on `X` works as expected

example | example | example 
---- | ---- | ----


**_Video conferencing_**
 
example | example | example | example
---- | ---- | ---- | -----  


**_Slide_**

example | example | example 
---- | ---- | ----


**_PIP window via media control in the toolbar_**

1. Opened https://googlechrome.github.io/samples/media-session/video.html in a new tab
2. clicked `Video` link to open in a new tab via context menu 
3. played a video
4. clicked media control in the toolbar

- Confirmed PIP shows `Back to tab` button is next to close button on the top right and works as expected
- Confirmed other media controls (Previous track, Next track, Pause & Play) are aligned in the middle of the window and working as expected 
- Confirmed clicking on `X` works as expected

example | example 
---- | ---

</details>

Upgrade
<details>

1. Installed 1.62.153
2. launched Brave
3. opened https://googlechrome.github.io/samples/media-session/index.html in a new tab
4. clicked `Video` link to open in a new tab via context menu 
5. clicked three dot menu in the player to open `PIP` window
6. opened Video Conferencing and Slides as well
7. closed Brave
8. renamed the profile Brave-Browser-Beta
9. installed 1.63.134
10. relaunched Brave

- Confirmed PIP shows `Back to tab` button is next to close button on the top right and works as expected
- Confirmed other media controls (Previous track, Next track, Pause & Play) are aligned in the middle of the window and working as expected 
- Confirmed clicking on `X` works as expected

`1.62.x`
example | example | example
---- | ---- | ----

`1.63.x`
example | example | example
---- | ---- | ----


</details>

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave	1.63.142 Chromium: 121.0.6167.139 (Official Build) beta (64-bit) 
Revision	7f6a671325da3f7f1ba2680c7a2115f895b4ff6b
OS	Linux
```


Fresh Install
<details>

**_Video_**

1. Installed 1.63.142
2. launched Brave
3. opened https://googlechrome.github.io/samples/media-session/index.html in a new tab
4. clicked `Video` link to open in a new tab via context menu 
5. clicked three dot menu in the player to open `PIP` window
6. clicked `X` 

- Confirmed PIP shows `Back to tab` button is next to close button on the top right and works as expected
- Confirmed other media controls (Previous track, Next track, Pause & Play) are aligned in the middle of the window and working as expected 
- Confirmed clicking on `X` works as expected

example | example | example | example | example 
---- | ---- | ---- | ---- | ---
![Screenshot from 2024-02-05 15-59-05](https://github.com/brave/brave-browser/assets/98358127/3de3ce95-5b06-4fc0-bdd5-ce3521862bbd)|![Screenshot from 2024-02-05 15-59-20](https://github.com/brave/brave-browser/assets/98358127/c49b6d1c-c91e-4ee0-9a24-a9bc3eabc439)|![Screenshot from 2024-02-05 15-58-27](https://github.com/brave/brave-browser/assets/98358127/32839e3b-4ff8-4860-9bef-f77e250c9b78)|![Screenshot from 2024-02-05 15-58-40](https://github.com/brave/brave-browser/assets/98358127/d4f6d4f4-9b3e-45ec-ac22-87dedcc70087)|![Screenshot from 2024-02-05 15-58-40](https://github.com/brave/brave-browser/assets/98358127/3b303c6d-f285-4a8b-bd8e-7e978bc22be9)


**_Video conferencing_**
 
example | example | example | example
---- | ---- | ---- | -----   
![Screenshot from 2024-02-05 13-36-15](https://github.com/brave/brave-browser/assets/98358127/c6819aad-8057-4bf9-a2bd-2b52acab3b55)|![Screenshot from 2024-02-05 13-58-53](https://github.com/brave/brave-browser/assets/98358127/cd9decd7-bb63-4757-9c98-71b5fdac7963)|![Screenshot from 2024-02-05 14-01-37](https://github.com/brave/brave-browser/assets/98358127/ca4fee88-fb9d-41ab-ba44-2c719425a8bf)|![Screenshot from 2024-02-05 14-02-13](https://github.com/brave/brave-browser/assets/98358127/f05b7b69-c3ba-4d38-874d-582947cfbab3)


**_Slide_**

example | example
---- | ---- 
![Screenshot from 2024-02-05 14-03-29](https://github.com/brave/brave-browser/assets/98358127/ae7ebc8a-67b9-42fe-8d12-154bacabe071)|![Screenshot from 2024-02-05 14-03-37](https://github.com/brave/brave-browser/assets/98358127/f0de4916-b871-4225-afc0-d03758fc89e0)


**_PIP window via media control in the toolbar_**

1. Opened https://googlechrome.github.io/samples/media-session/video.html in a new tab
2. clicked `Video` link to open in a new tab via context menu 
3. played a video
4. clicked media control in the toolbar

- Confirmed PIP shows `Back to tab` button is next to close button on the top right and works as expected
- Confirmed other media controls (Previous track, Next track, Pause & Play) are aligned in the middle of the window and working as expected 
- Confirmed clicking on `X` works as expected

example | example 
---- | ---
![image](https://github.com/brave/brave-browser/assets/98358127/14f8329b-6095-4cab-b3f8-3a58f6c8dc78)|![image](https://github.com/brave/brave-browser/assets/98358127/ef895e1e-a971-4d9b-971e-1f7773aff67e)
[
</details>

Upgrade
<details>

1. Installed 1.62.153
2. launched Brave
3. opened https://googlechrome.github.io/samples/media-session/index.html in a new tab
4. clicked `Video` link to open in a new tab via context menu 
5. clicked three dot menu in the player to open `PIP` window
6. opened Video Conferencing and Slides as well
7. closed Brave
8. renamed the profile Brave-Browser-Beta
9. installed 1.63.134
10. relaunched Brave

- Confirmed PIP shows `Back to tab` button is next to close button on the top right and works as expected
- Confirmed other media controls (Previous track, Next track, Pause & Play) are aligned in the middle of the window and working as expected 
- Confirmed clicking on `X` works as expected

`1.62.x`
example | example | example
---- | ---- | ----

`1.63.x`
example | example | example
---- | ---- | ----

</details>
