### ISSUE TITLE
Remove unnecessary gets for publisher data

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#3525]
Now that we update % based on normalize observer (done here https://github.com/brave/brave-core/pull/1780), we don't need to get publisher data anymore if panel is opened for the same publisher. We only need to get data if publisher is different

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.63.4 Chromium: 73.0.3683.67 (Official Build) dev (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1822
