### ISSUE TITLE
Build Out Bitcoin Balances Modal

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35258]
## Description 

We need to build out the `Bitcoin` balances modal from the `Figma` design

![image](https://github.com/brave/brave-browser/assets/40611140/36199873-97a4-49f9-9125-22ffa61c34f7)

**Comment by kjozwiak** [comment]
The above requires `1.63.138` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.153 Chromium: 121.0.6167.164 (Official Build) beta (64-bit)
-- | --
Revision | ef6dd148841564e2c5d9110bed5d6b7aad780525
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21634](https://github.com/brave/brave-core/pull/21634)
- Verified when a transaction is under confirmation, a message is shown under the token 
- Verified clicking on details shows the balance details modal
- Verified on both wallet page and panel

https://github.com/brave/brave-browser/assets/17010094/007bcdad-c908-4a17-9551-cf2c3daa18e4
