### ISSUE TITLE
[Android] Redirect users to new custom filter settings

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#35269]
Since we have the new filter list settings option: https://github.com/brave/brave-browser/issues/26587
We need to redirect users to new filter list settings when they type brave://adblock in url bar.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using version: 

```
Brave	1.64.95 Chromium: 122.0.6261.94 (Official Build) beta (64-bit) 
Revision	6f4193fbcee7c358ae3684f777faa9f12e52206e
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that typing `brave://adblock` redirects user to content filter page

Example | Example
-|-
![Screenshot 2024-03-05 at 6 32 22 PM](https://github.com/brave/brave-browser/assets/17885425/d51800eb-3b02-453b-a677-2734ed4676ea) | ![Screenshot 2024-03-05 at 6 36 14 PM](https://github.com/brave/brave-browser/assets/17885425/e5ff6491-745b-432b-a0fa-8dd4556773a8)
