### ISSUE TITLE
Migrate assets prefs to a plain list

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#35265]
We don't need tree-like structure to store assets. Plain list is enough. That also helps to remove network_id

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.102 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | c9343c77bd5dee3524fc45f89721ce0bf4c09b8d
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21550](https://github.com/brave/brave-core/pull/21550)
- Verified wallet assets work/load as expected after migrating from previous version
- Verified `wallet_user_assests` is migrated to `wallet_user_assests_list` post migration

https://github.com/brave/brave-browser/assets/17010094/ac053665-132e-488b-89a5-1d919cf2780a
