### ISSUE TITLE
If feed is empty after unfollowing sources, incorrect message is shown in nightly 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#35274]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/35157.  After unfollowing all sources, including `Top sources`, and while connected to WiFi, incorrect message shown `You appear to be offline` with Refresh button.  Correct message should be `Your Feed is Empty` as in 1.62.x

## Steps to Reproduce

   1. Install `1.63.110`
   2. launch Brave
   3. clicked `Customize` >>`Brave News` in a new tab
   4. unfollow `Top Sources`
   5. Return to feed 
   6. verified `Wifi` is `Connected` 
   
## Actual result:

`You appear to be offline` message shown 

## Expected result:
`Your Feed is Empty` message should be shown as in 1.62.x

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.63.110 Chromium: 120.0.6099.217 (Official Build) nightly (64-bit)
-- | --
Revision | f7a7c2ee42626f5a1310c9bd6789d0438e78ca6e
OS | Windows 11 Version 22H2 (Build 22621.3007)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@fallaciousreasoning @LorenzoMinto 
cc: @brave/qa-team

**Comment by stephendonner** [comment]
Thanks for logging this - I noticed it while testing https://github.com/brave/brave-core/pull/21507 but didn't want to hold up those other improvements 👍

**Comment by fallaciousreasoning** [comment]
Nice catch!

**Comment by kjozwiak** [comment]
The above requires `1.62.145` or higher for `1.62.x` verification 👍

**Comment by stephendonner** [comment]
## Verified using

```
Brave | 1.62.144 Chromium: 120.0.6099.217 (Official Build) beta (x86_64)
-- | --
Revision | 75de8d953f6a5686e425d46d7f0dc9284dc1c064
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.62.144`
2. launched Brave
3. opened a new-tab page
4. scrolled down
5. clicked on `Turn on Brave News`
6. clicked to `Unfollow` the `Top Sources` feed
7. closed the dialog
8. clicked on the `Reload?` button

### Confirmed the feed was empty, and I got the appropriate `Your Feed is Empty` message

example | example | example | example | example
---------|----------|---------|---------|----------
<img width="1312" alt="Screen Shot 2024-01-16 at 3 41 15 PM" src="https://github.com/brave/brave-browser/assets/387249/db794fd3-0e48-42a0-851f-8384a989f7b1"> | <img width="1312" alt="Screen Shot 2024-01-16 at 3 41 21 PM" src="https://github.com/brave/brave-browser/assets/387249/f48523bf-4c7d-4456-9846-1a950b68af2b"> | <img width="1312" alt="Screen Shot 2024-01-16 at 3 41 29 PM" src="https://github.com/brave/brave-browser/assets/387249/d4c236b2-412b-4ad4-9868-fae5d2fdde61"> | <img width="1312" alt="Screen Shot 2024-01-16 at 3 41 39 PM" src="https://github.com/brave/brave-browser/assets/387249/280c893e-4bfd-41b5-9b24-b8c1c886aa71"> | <img width="1312" alt="Screen Shot 2024-01-16 at 3 41 43 PM" src="https://github.com/brave/brave-browser/assets/387249/d0c42f87-bbff-4f51-81b9-02cfb69c9e6b">
