### ISSUE TITLE
Youtube Issue

### ISSUE THREAD

**Issue by Sysys242** [brave/brave-browser#35276]
![image](https://github.com/brave/brave-browser/assets/86845555/fc1c2919-e99c-458d-a299-1ec3adda2160)
Youtube new update detect brave ads block

Country: France

**Comment by Mineplayerminer** [comment]
This is happening everywhere right now. There have been changes done to the Ad-block detections. We have to only wait for a patch. There's nothing we can do for now.

**Comment by ahmaddroobi99** [comment]
Yes, I observed the same problem, YouTube on my Brave Desktop crashed, but still works in the Android version of Brave.

**Comment by ahmaddroobi99** [comment]
It is solved now.

**Comment by GaForgone** [comment]
nope still broke as heck

**Comment by Sysys242** [comment]
yep still not working

**Comment by ryanbr** [comment]
Update in brave://components, Brave Ad Block Updater - Version: 1.0.3342  (or better). Ensure not using another adblocker on YT also.

**Comment by patlempa** [comment]
<img width="960" alt="problem you tube" src="https://github.com/brave/brave-browser/assets/156380423/43a70d1a-e150-4df6-90cb-1a352d199517">
 all componet are updated on my browser and you tube is denying me access. the only adblock i'm suing is brave's native one

**Comment by ryanbr** [comment]
Try clearing the cookies/cache in `brave://settings/content/siteDetails?site=https%3A%2F%2Fwww.youtube.com`, then relogin.

**Comment by patlempa** [comment]
> Try clearing the cookies/cache in `brave://settings/content/siteDetails?site=https%3A%2F%2Fwww.youtube.com`, then relogin.

tried it. did not need a new login but it sees to be working (for now anyway) thanks

**Comment by Sysys242** [comment]
Working, thanks for the update ^^
