### ISSUE TITLE
[Android] Have an option in filterlist section to force-update all adblock components

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#35270]
It would help adblock breakage remediation tremendously if users can force-update all adblock components by going to `Settings`-> `Brave Shields & privacy` -> `Content Filtering` and pressing a button instead of having to go to brave://components and clicking each Update button manually.

The button could live under the Filter lists section:

Action button text : Update

**Comment by kjozwiak** [comment]
The above requires `1.67.109` or higher for `1.67.x` verification 👍

**Comment by superlex** [comment]
Uhm it looks like it doesn't work on my end.

It says that filter lists have been updated:

![Screenshot_20240607_232519_Brave.png](https://github.com/brave/brave-browser/assets/1375223/a2eccb1b-f890-4a68-b62d-93617cf00718)

But they don't:

![Screenshot_20240607_232208_Brave.png](https://github.com/brave/brave-browser/assets/1375223/4725d3b7-8dad-4d46-983b-71a6e2d1feab)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.67.110`

- Verified the test plan from https://github.com/brave/brave-core/pull/23929
* ensured that there's a new `UPDATE` button available via `Hamburger Menu` -> `Brave Shields & privacy` -> `Content Filtering`
* ensured that tapping `UPDATE` doesn't case any issues/crashes or visible regressions

https://github.com/brave/brave-browser/assets/38657976/f26f13a9-394d-48be-aacf-50a7a800bcbe
