### ISSUE TITLE
Sorry Brave Stuff, but I have a problem.

### ISSUE THREAD

**Issue by CanalYT** [brave/brave-browser#35280]
The YouTube updates the _**Anti-AddBlocker Wall**_.
![AdProblem](https://github.com/brave/brave-browser/assets/87686735/aed4aa51-678a-481b-9a31-72df6dc0e233)
The only thing _I ask is that **they can fix it**!_

**Comment by rebron** [comment]
Closing as dupe of https://github.com/brave/brave-browser/issues/35276

**Comment by rebron** [comment]
https://github.com/brave/brave-browser/issues/35276#issuecomment-1888037428

**Comment by CanalYT** [comment]
**THANKSUPPORT!**
