### ISSUE TITLE
Dapps accounts in dapps panel

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#35289]
Dapps panel should only show EVM and Solana accounts. Switch to some of them if currently selected is one a Bitcoin or a Filecoin account.

**Comment by srirambv** [comment]
Verification passed on <html>
<body>

Brave | 1.63.141 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | aa92f6cecec7f6c576bd1cf120f4cf359d770159
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21560](https://github.com/brave/brave-core/pull/21560)
- Verified Filecoin/Bitcoin is not listed in Dapps panel 

https://github.com/brave/brave-browser/assets/17010094/1bcdbade-058a-43a9-8be3-e6ca7d6c150d
