### ISSUE TITLE
[iOS] - Export Features API

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#35287]
## Description 
- Export the Features API for iOS to use on the Swift Side with Variations/Griffin

## Expected
- Features API to allow reading of feature flags from iOS

**Comment by kjozwiak** [comment]
Removing from the `1.63.x` milestone. Once the above has been fixed, it will land in `master` and then will need to be uplifted into `1.63.x`. Once it lands in `master` (which is `1.65.x` at this time), the issue will automatically close/move into the `1.65.x` milestone. It will then be moved to the appropriate milestone when uplifted.
