### ISSUE TITLE
Add an ability to check is publisher on recurring donations.

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#3529]
Currently we have a function `GetRecurringDonations` inside rewards server which retrieves a list of publishers which set for recurring donations. We don't need the whole list when we are on rewards panel, we need to check only current publisher. We need to add a function to verify only a certain publisher.

**Comment by Miyayes** [comment]
I think recurring donations is purely client-side now, so not sure if relevant anymore. Can reopen in future if needed.
