### ISSUE TITLE
Button _Turn on Speedreader_ causes immediate crash when reading IPFS page on MacOS

### ISSUE THREAD

**Issue by asitanc** [brave/brave-browser#35295]
I have searched for this issues on Google and also here in GitHub issues of course and could not find any similar issues.

## Description 
Button _Turn on Speedreader_ in the URL bar causes immediate crash when reading IPFS page.

## Steps to Reproduce

   1. Enable IPFS in the settings
   2. Navigate to any IPFS page such as this one [Vitalik Blog](ipfs://bafybeib24abrrlurxmgedaekfz2v2eatpzo2l5cbvdoay4hnpenuzojt6a/general/2023/12/28/cypherpunk.html)
   3. Wait for the page to load and _Turn on Speedreader_

## Actual result:

This is a video:
https://github.com/brave/brave-browser/assets/43077862/88111fef-6e3a-4ffd-a201-23393445dfe7

## Expected result:

It should not crash the whole browser app.

## Reproduces how often: 

It happens every time on any page.

## Brave version

Brave | 1.61.114 Chromium: 120.0.6099.199 (Official Build) (arm64)
-- | --
Revision | e0f6e091fe79c029231a86e8cdcc5fbe70bcddbe
OS | macOS Version 14.2.1 (Build 23C71)

## Version/Channel Information:

I downloaded all the latest releases and tested all and crash occurs with all of them.

- Can you reproduce this issue with the current release? 

Yes

- Can you reproduce this issue with the beta channel? 

Yes

- Can you reproduce this issue with the nightly channel? 

Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 

No

- Does the issue resolve itself when disabling Brave Rewards? 

No

- Is the issue reproducible on the latest version of Chrome? 

No

## Miscellaneous Information:

I am not using public IPFS gateway but using local node, but it crashes even with public gateway.

**Comment by rebron** [comment]
cc: @boocmp

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

```
Brave | 1.63.122 Chromium: 121.0.6167.57 (Official Build) nightly (x86_64)
-- | --
Revision | a0d9d1a751311402551f0e5d0520fb10caacdce4
OS | macOS Version 11.7.10 (Build 20G1427)
```
### Steps:
1. install `1.63.122`
2. launch Brave
3. load `vitalik.eth`
4. click `Use a Brave local IPFS node`
5. wait
6. click on the first article link
7. look at the URL bar
8. click on the Speedreader icon
9. nothing happens
10. reload the page
11. Speedreader icon disappears

### Confirmed no crash; `Speedreader` icon appears briefly but doesn't crash on click, and disappears on reload


example | example | example | example | example
---------|----------|---------|----------|---------
<img width="1312" alt="Screen Shot 2024-01-16 at 2 53 28 PM" src="https://github.com/brave/brave-browser/assets/387249/f114ad41-bf95-4418-b200-4f03b4701d14"> | <img width="1583" alt="Screen Shot 2024-01-16 at 2 56 22 PM" src="https://github.com/brave/brave-browser/assets/387249/70ff7816-45c0-4390-8b1e-4eab30adbb34"> | <img width="1583" alt="Screen Shot 2024-01-16 at 2 58 15 PM" src="https://github.com/brave/brave-browser/assets/387249/8b23a72b-096c-4036-9da2-41d278bc5956"> | <img width="1583" alt="Screen Shot 2024-01-16 at 2 58 18 PM" src="https://github.com/brave/brave-browser/assets/387249/340231e9-51d4-4f87-9ebd-493625958a55"> | <img width="1583" alt="Screen Shot 2024-01-16 at 2 59 33 PM" src="https://github.com/brave/brave-browser/assets/387249/d8e92ca5-62a2-48f1-811a-e58cffd600bd">


Encountered and logged:
* https://github.com/brave/brave-browser/issues/35362
