### ISSUE TITLE
Show loading indicator when fetching receive address

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#35292]
## Description 

The QR code image is broken when first opening the deposit modal for BTC accounts

## Steps to Reproduce

   1. Create a BTC account
   2. open the deposit modal

## Actual result:

the QR code image is momentarily displayed as a broken image until the latest address is available

## Expected result:
a loading indicator should be shown until the address is ready

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by yrliou** [comment]
@josheleonard @supermassive should we uplift this one into 1.62.x?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.153 Chromium: 121.0.6167.164 (Official Build) beta (64-bit)
-- | --
Revision | ef6dd148841564e2c5d9110bed5d6b7aad780525
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from issue description
- Verified loading state indicator is shown when fetching receive address
- Encountered [#36004](https://github.com/brave/brave-browser/issues/36004)

https://github.com/brave/brave-browser/assets/17010094/a9edeaf1-d586-467b-8dba-092eb63a1527
