### ISSUE TITLE
Account recovery fail causes to get stuck in Creating Wallet screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#35297]
## Description 
Account recovery fail causes to get stuck in Creating Wallet screen

## Steps to reproduce 

   1. Clean profile
   2. Try restoring a wallet with incorrect seed
   3. Shows message account recovery failed but UI shows creating wallet loading state
   4. Press back doesn't work
   5. Close browser and restart, wallet shows onboarding UI

## Actual result 
Account recovery fail causes to get stuck in Creating Wallet screen

## Expected result
Should not show creating wallet if account recovery failed

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Mostly Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.62.x and 1.63.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe

**Comment by kjozwiak** [comment]
The above requires `1.66.113` or above for `1.66.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Lenovo Tab with Android 13 running 1.66.113 x64 build
- Verified steps from [ brave/brave-core#23641](https://github.com/brave/brave-core/pull/23641)
- Verified account restore fails when invalid seed phrase is used
- Verified `Account recovery failed. Please try again` message is shown without navigating to `Creating wallet` screen
- Verified able to successfully restore wallet with correct seed phrase
