### ISSUE TITLE
Paste and Search in a Private Window uses the Normal Window search engine

### ISSUE THREAD

**Issue by danielbahrami** [brave/brave-browser#35308]
## Description 
When using "Paste and Search" in a Private Window, Brave uses the search engine that has been configured for a Normal Window. This also occurs in a Private Window with Tor.

## Steps to Reproduce
   1. In settings, choose different search engines for Normal Window and Private Window (e.g. Google for Normal Window and Brave for Private Window)
   2. Copy some text to be used for the search query
   3. Open a Private Window
   4. Right click on the address bar and press "Paste and Search for "X""

## Actual result:
The search query is performed on the Normal Window search engine (e.g. Google)

## Expected result:
The search query should be performed on the Private Window search engine (e.g. Brave)

## Reproduces how often:
Every time

## Brave version (brave://version info)
1.61.116 Chromium: 120.0.6099.217 (Official Build) (arm64)

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by simonhong** [comment]
Original profile's `AutocompleteClassifier` is used for otr profile.
maybe need to fetch proper `match` with otr profile's `AutocompleteClassifier`.
```
void OmniboxEditModel::ClassifyString(const std::u16string& text,
                                      AutocompleteMatch* match,
                                      GURL* alternate_nav_url) const {
  DCHECK(match);
  controller_->client()->GetAutocompleteClassifier()->Classify(
      text, false, false, GetPageClassification(), match, alternate_nav_url);
}
```

**Comment by kjozwiak** [comment]
@simonhong I think we should probably get this one uplifted to at least `1.63.x`. Seems like the above has been broken for a while  so probably not urgent enough to get into `Release` but can definitely uplift into at least `1.63.x`. CCing @rebron.

**Comment by simonhong** [comment]
> @simonhong I think we should probably get this one uplifted to at least `1.63.x`. Seems like the above has been broken for a while so probably not urgent enough to get into `Release` but can definitely uplift into at least `1.63.x`. CCing @rebron.

Pushed https://github.com/brave/brave-core/pull/21636

**Comment by kjozwiak** [comment]
The above requires `1.63.128` or higher for `1.63.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.63.133 Chromium: 121.0.6167.85 (Official Build) beta (64-bit)
-- | --
Revision | 55039c9dc9129b18c76ae20b9291df5a60c74c27
OS | Windows 11 Version 22H2 (Build 22621.3085)
```

Reproduced in `1.62.153 Chromium: 121.0.6167.85` 
<details>

example  | example 
-----  | -----
![image](https://github.com/brave/brave-browser/assets/98358127/f17e932a-90fd-4004-9308-9423ece40c12)
![image](https://github.com/brave/brave-browser/assets/98358127/ff2b9892-ad43-434b-b83b-fa2a08249d36)
</details>

1. Installed 1.62.153
2. launched Brave
3. opened `brave://settings/search`
4. selected `Google` for Normal Window
5. left `Brave` selection as is for Private Window
6. copied `Data centers` 
7. clicked hamburger menu >> New private window
8. right clicked in the address bar and pressed "Paste and Search for "Data centers"

#### Confirmed Brave search engine is used, and results are shown in the Private window

step 4 -5 | step 6 | step 7 | step 8
---- | ---- | ------ | ------
![image](https://github.com/brave/brave-browser/assets/98358127/f61e17ac-4846-4beb-bb75-d102ecd69654)|![image](https://github.com/brave/brave-browser/assets/98358127/182816cf-84ac-428e-ac99-5df2a4b90e6b)|![image](https://github.com/brave/brave-browser/assets/98358127/a27aad95-819b-4cb3-a71d-c125f2c21bae)|![image](https://github.com/brave/brave-browser/assets/98358127/be1e59ad-cbee-4fbe-aa14-10adbaa4b1dd)
