### ISSUE TITLE
Ads Campaign ID, Daily Cap, Per Day and Total Max use incorrect database fields

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#3530]
## Description 
Ads Campaign ID, Daily Cap, Per Day and Total Max use incorrect database fields caused by the addition of Region to the database

## Steps to Reproduce

   1. Navigate to www.imdb.com
   2. Wait 15 seconds for the browser to idle
   3. Move the mouse

## Actual result:
`Defaults/ads_service/client.json` campaignHistory array shows `US`

## Expected result:
`Defaults/ads_service/client.json` campaignHistory array should show the campaign ID

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
0.63.x

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.63.34 Chromium: 74.0.3729.40 (Official Build) beta (64-bit)
-- | --
Revision | 278d6a0d856d8314f36fb9a68b6e1d85cd0d14e7-refs/branch-heads/3729@{#470}
OS | Windows 10 OS Build 17134.523





- Verified the test plan from https://github.com/brave/brave-core/pull/1808


"campaignHistory": {
    "5d7e79b3-8bbb-46d2-b76a-7a2d63d910b9": [
      13199195906
    ]
  },
