### ISSUE TITLE
Split the "pages loaded" P3A metric into "pages loaded" and "pages reloaded" metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#35301]
Split the pages loaded metric (`Brave.Core.PagesLoaded`) into two metrics:

How many pages did you load (excluding reloads) in the past week?
`Brave.Core.PagesLoaded.2`

How many pages did you reload in the past week?
`Brave.Core.PagesReloaded`

Original bucket values would exist for both metrics:

0. 0 pages
1. 1-10
2. 11-50
3. 51-100
4. 101-500
5. 501-1000
6. Greater than 1000 pages

cc @timchilds

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | Windows 10 Version 22H2 (Build 19045.4046)

```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung galaxy version 12` running `Bravemonoarm64.apk_1.64.104`

### Brave.Core.PagesLoaded.2

<details>
<summary>Brave.Core.PagesLoaded.2 = 0_PASSED</summary>

1. Clean profile 1.64.90
2. Open brave://local-state
3. Look for the metrics `Brave.Core.PagesLoaded.2` 
4. Confirmed that the metrics `Brave.Core.PagesLoaded.2` response value is `0` under `logs_constellation_prep` block as expected
![image](https://github.com/brave/brave-browser/assets/38657976/7bd36bbb-77bb-4e4a-970e-7b6be592853c)

</details>

<details>
<summary>Brave.Core.PagesLoaded.2 = 1_PASSED</summary>

**Case 1:**

1. Clean profile 1.64.90
2. Open a site in an NTP
3. Open brave://local-state in NTP
4. Look for the metrics `Brave.Core.PagesLoaded.2` 
5. Confirmed that the metrics `Brave.Core.PagesLoaded.2` response value is `1` under `logs_constellation_prep` block as expected
![image](https://github.com/brave/brave-browser/assets/38657976/9c535681-4fba-4c2f-a961-b6cdb160ce76)

**Case 2:**

1. Clean profile 1.64.90
2. Open 10 different sites in NTP's
3. Restart the browser and wait for 1 min
4. Open brave://local-state in NTP
5. Look for the metrics `Brave.Core.PagesLoaded.2` 
6. Confirmed that the metrics `Brave.Core.PagesLoaded.2` response value is `1` under `logs_constellation_prep` block as expected
![image](https://github.com/brave/brave-browser/assets/38657976/639f7428-bf85-482a-b290-2617b4839e5e)


</details>

<details>
<summary>Brave.Core.PagesLoaded.2 = 2_PASSED</summary>


1. Clean profile 1.64.90
2. Open 11 different sites in NTP's
3. Restart the browser and wait for 1 min
4. Open brave://local-state in NTP
5. Look for the metrics `Brave.Core.PagesLoaded.2` 
6. Confirmed that the metrics `Brave.Core.PagesLoaded.2` response value is `2` under `logs_constellation_prep` block as expected
![image](https://github.com/brave/brave-browser/assets/38657976/22b7bd96-8bdf-444e-bb28-25605cc2d72b)


</details>

<details>
<summary>Brave.Core.PagesLoaded.2 = 3_PASSED</summary>

1. Clean profile 1.64.90
2. Open 51 different sites in NTP's
3. Restart the browser and wait for 1 min
4. Open brave://local-state in NTP
5. Look for the metrics `Brave.Core.PagesLoaded.2` 
6. Confirmed that the metrics `Brave.Core.PagesLoaded.2` response value is `3` under `logs_constellation_prep` block as expected
![image](https://github.com/brave/brave-browser/assets/38657976/bda741f4-7976-4883-97a6-5264e764cac7)

</details>



### Brave.Core.PagesReloaded

<details>
<summary>Brave.Core.PagesReloaded = 0_PASSED</summary>

   1. Clean profile 1.64.x
   2. Open brave://local-state file and reload this page
   3. Confirmed that the metrics `Brave.Core.PagesReloaded` response value is `0` as expected
   
![image](https://github.com/brave/brave-browser/assets/38657976/f7970128-7409-4176-989f-0aadf89ead18)

</details>

<details>
<summary>Brave.Core.PagesReloaded = 1_PASSED</summary>

**Case 1:**

  1. Clean profile 1.64.x
  2. Open brave://local-state file
  3. Confirmed that the metrics Brave.Core.PagesReloaded response value is 0 as expected
  4. Open a site in an NTP
  5. Reload the site
  8. Restart the browser and wait for 1 minute
  9. Reload brave://local-state
  10. The metrics `Brave.Core.PagesReloaded` response value is `1`  under `logs_constellation_prep` block
  11. Close the browser and set the sys date ahead by 7 days
 12. Relaunch the browser and reload brave://local-state file
13. The metrics `Brave.Core.PagesReloaded` response value is `1` as expected

![image](https://github.com/brave/brave-browser/assets/38657976/cce493bb-eb8b-40ca-81a6-36d7cc1b4fac)

**Case 2:**

  1. Clean profile 1.64.x
  2. Open brave://local-state file
  3. Confirmed that the metrics Brave.Core.PagesReloaded response value is 0 as expected
  4. Open 10 different sites in 10 NTP's
  5. Reload all the 10 sites
  6. Restart the browser and wait for 1 minute
  7. Reload brave://local-state
  8. The metrics `Brave.Core.PagesReloaded` response value is `1`  under `logs_constellation_prep` block
  9. Close the browser and set the sys date ahead by 7 days
 10. Relaunch the browser and reload brave://local-state file
11. The metrics `Brave.Core.PagesReloaded` response value is `1` as expected

![image](https://github.com/brave/brave-browser/assets/38657976/73c44013-220c-4fb9-abf5-7a844f4fa3a5)

   
</details>

<details>
<summary>Brave.Core.PagesReloaded = 2_PASSED</summary>

  1. Clean profile 1.64.x
  2. Open brave://local-state file
  3. Confirmed that the metrics Brave.Core.PagesReloaded response value is 0 as expected
  4. Open 11 different sites in 11 NTP's
  5. Reload all the 11 sites
  6. Restart the browser and wait for 1 minute
  7. Reload brave://local-state
  8. The metrics `Brave.Core.PagesReloaded` response value is `2`  under `logs_constellation_prep` block
  9. Close the browser and set the sys date ahead by 7 days
 10. Relaunch the browser and reload brave://local-state file
11. The metrics `Brave.Core.PagesReloaded` response value is `2` as expected

![image](https://github.com/brave/brave-browser/assets/38657976/da1d694b-e8c4-4348-986b-b79a4d1295c1)

</details>

<details>
<summary>Brave.Core.PagesReloaded = 3_PASSED</summary>

1. Clean profile 1.64.x
  2. Open brave://local-state file
  3. Confirmed that the metrics Brave.Core.PagesReloaded response value is 0 as expected
  4. Open 51 different sites in 51 NTP's
  5. Reload all the 51 sites
  6. Restart the browser and wait for 1 minute
  7. Reload brave://local-state
  8. The metrics `Brave.Core.PagesReloaded` response value is `3`  under `logs_constellation_prep` block
  9. Close the browser and set the sys date ahead by 7 days
 10. Relaunch the browser and reload brave://local-state file
11. The metrics `Brave.Core.PagesReloaded` response value is `3` as expected

![image](https://github.com/brave/brave-browser/assets/38657976/5c3e5867-4d34-432e-97b3-1bef228fe9db)

</details>
