### ISSUE TITLE
aichat: Include "domain" property in Leo feedback form data

### ISSUE THREAD

**Issue by porteron** [brave/brave-browser#35303]
We'd like to improve Leo when it underperforms when pulling correct information from the current webpage into context for summarizing. Users submit ratings and feedback but we do not actually know what domain url that is being reported. What we'd like to update is when a user submits feedback on their chat to include the current domain in the feedback data.

 - [ ] Add `"domain"` param to `/1/ai/feedback/form` request payload
 - [ ] Only include domains for sites that are HTTP/HTTPS
 - [ ] Include only the origin, exclude the path and query params

**Comment by porteron** [comment]
@nullhook Privacy review is complete. There is a design here: https://github.com/brave/reviews/issues/1482#issuecomment-1896394322. Here is a summary of when to capture a domain and the structure of the url: https://github.com/brave/reviews/issues/1482#issuecomment-1896844572

**Comment by porteron** [comment]
Backend is ready to accept and store the new `domain` value

**Comment by kjozwiak** [comment]
@brave/qa-team can use https://github.com/brave/brave-core/pull/21741#issuecomment-1947573334 & https://github.com/brave/brave-core/pull/21741#issuecomment-1947654784 as a template for the above verification on `1.63.x`. The above requires `1.63.156` or higher for `1.63.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

```
Brave | 1.63.156 Chromium: 122.0.6261.43 (Official Build) (x86_64)
-- | --
Revision | afb5d4402861ae4a1eb59c939832a4d27e1ed8df
OS | macOS Version 11.7.10 (Build 20G1427)
```

## HTTP/HTTPS sites - `PENDING`

## local sites/resources - `PENDING`

**Comment by stephendonner** [comment]
Logged https://github.com/brave/brave-browser/issues/36162 while testing this.

**Comment by Uni-verse** [comment]
In progress on `Samsung Galaxy S21` using version:

```
Brave	1.63.156 Chromium: 122.0.6261.43 (Official Build) (64-bit) 
Revision	afb5d4402861ae4a1eb59c939832a4d27e1ed8df
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
