### ISSUE TITLE
Local files should not be shown with "insecure" icon in the UI

### ISSUE THREAD

**Issue by ZelnickB** [brave/brave-browser#35316]
When you open a local file (e.g., a PDF) with Brave (I have tested it with Version 1.61.116 Chromium: 120.0.6099.217 (Official Build) (arm64) on MacOS Apple Silicon), the "insecure" icon used for HTTP sites (insecure origins) is displayed in the address bar:  
![Insecure \(exclamation point\) icon shown next to "File" label in address bar.](https://github.com/brave/brave-browser/assets/34197604/8da0f630-10a7-402c-ba81-2851ce4c69a8)

Local files are not "insecure" like an HTTP site, so perhaps Brave should use an icon like that used in Google Chrome (with an "info" or similar icon appearing next to the "File" label).  
!["Info" icon shown next to 'File' label in address bar when using Google Chrome.](https://github.com/brave/brave-browser/assets/34197604/9307656c-86f7-4707-a231-1b173551e5d4)

**Comment by ZelnickB** [comment]
Somewhat related to #33755.

**Comment by diracdeltas** [comment]
cc @rebron @petemill @bradleyrichter does anyone know if this was an intentional design change on our part from Chrome?

**Comment by simonhong** [comment]
When I load `http` site different icon is used (rounded triangle)
<img width="433" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/136b166f-8d80-40b3-92be-4915dbf64091">

and circle icon for file scheme.
<img width="198" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/dc77ea4f-7d75-4b50-abe8-04f2e532d090">

Is there another way to see circle icon for `http` site?

**Comment by diracdeltas** [comment]
@simonhong that's a good point. I think the issue is the exclamation point (!) is associated with insecure sites even though it's not exactly the same UI as insecure. if it was the info icon (i) instead it'd be fine.

**Comment by bradleyrichter** [comment]
@simonhong swapping over to the info icon would work here

**Comment by simonhong** [comment]
I found that we have another info icon with `i` from our icon set (https://www.figma.com/file/g8Z0q6TMPYDq6zXh9Y7LWD/%F0%9F%8C%8E-Universal?type=design&node-id=1419-13501&mode=design&t=Ae5NaXQUaIR2C1LK-0)
<img width="382" alt="Screenshot 2024-01-23 at 11 31 04 AM" src="https://github.com/brave/brave-browser/assets/6786187/c737ebae-d1e0-4f66-93ca-1127511140c1">
Maybe it's good to use here?

**Comment by diracdeltas** [comment]
lgtm

**Comment by aguscruiz** [comment]
@simonhong let's used the filled variant there, since the ⚠️ icon is also filled. 👌

**Comment by kjozwiak** [comment]
The above requires `1.62.155` or higher for `1.62.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.62.155 Chromium: 121.0.6167.85 (Official Build) (x86_64)
-- | --
Revision | 91c989228daf153ef41bd965f268fabc7b9dbbf0
OS | macOS Version 13.6.4 (Build 22G513)
```
