### ISSUE TITLE
Audio is broken for some formats/codecs in Latest Nightly

### ISSUE THREAD

**Issue by TEMP-ad** [brave/brave-browser#35318]
Brave 1.63.118 in Nightly added a https://github.com/brave/brave-core/pull/21539 that has to do with ffmpeg, so I would have to guess that could be the issue here and why the audio in most websites is completely broken on my side.

Go to https://www.twitch.tv/smitegame and it will be broken, same as https://vimeo.com/goprocedural or some stream in kick.

I am not sure what other consequences this new ffmpeg update has but at least it is impossible to watch videos and it has to be reverted to 1.63.117 for it to work again, and it seems to be the only explanation for this issue.

It should be easily able to reproduce this, if not, I guess I can give my laptop specifications so maybe someone else can try to reproduce it in a similar system.

All I know is I upgraded to 1.63.119 which only added a wallet related commit, and the sound doesn't work anymore in Twitch and other video services.

@goodov I am tagging you since you were the one making the PR, so you are aware of it.

**Comment by JunkiEDM** [comment]
I was just about to make an issue about this, but you beat me to it!
It seems to only affect audio which uses the AAC codec, audio using other codecs (tested: opus, mp3) isn't affected.
<details><summary>I was able to replicate this in a Windows 11 VM and took some screencaps showing the issue:</summary>

https://github.com/brave/brave-browser/assets/8350274/5bb0917c-1e8a-47d4-9a77-cf08d03cd67b

https://github.com/brave/brave-browser/assets/8350274/2b439790-64c7-4b4c-aab2-76db0e77da04

</details>

I also tested it in a VM running Manjaro Linux and the audio was unaffected so it's possible this is a Windows-only bug.

**Comment by TEMP-ad** [comment]
This is a good site to test this: https://tools.woolyss.com/html5-audio-video-tester/
Vorbis also has issues with it, just as AAC.
MP3, Wav, Opus seem okay.

Updated to latest 1.63.120 with Chromium 121, to test this and see if something magically changed, but no.

Windows 11 Version 22H2 (Build 22621.3007)
