### ISSUE TITLE
[Brave News]: We should enable FeedV2 in 1.62.x via Griffin

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#35317]
Currently the feature is on by default in Beta. Instead, we should enable via Griffin, so we're able to disable the feature if we need to. We can flip the flag by default in one of the hotfix releases
@LorenzoMinto @kjozwiak

**Comment by kjozwiak** [comment]
Closing the above as https://github.com/brave/brave-core/pull/21579 was merged into `1.62.x`. The above will need to be verified alongside https://github.com/brave/brave-variations/pull/868 on `staging`. We'll then get a `production` Griffin PR created closer to the release and set it as `10%`. The following schedule will be used (could be changed if issues are found):

* `10%` - Work Day One
* `25%` - Work Day Two
* `50%` - Work Day Three
* `100%` - Work Day Four

**Comment by kjozwiak** [comment]
`QA/Blocked` for now till https://bravesoftware.slack.com/archives/C01LKMP6X36/p1705882556331299?thread_ts=1705624287.392109&cid=C01LKMP6X36 gets addressed.

**Comment by kjozwiak** [comment]
Resolved via https://github.com/brave/brave-variations/pull/882. Removing `QA/Blocked`.

**Comment by kjozwiak** [comment]
## `Nightly` - `Feed v2` enabled by default (without Griffin)

Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.64.7 Chromium: 121.0.6167.75 (Official Build) nightly (64-bit)
-- | --
Revision | e30578012734478112b86971a7b87be13b011835
OS | Windows 11 Version 23H2 (Build 22631.3007)
```

### `Test Case #1` - `PASSED`

* installed `1.64.7 Chromium: 121.0.6167.75` using the `standalone` (offline) installer
* once installed, ensured there's no Griffin studies being listed/mentioned via `brave://version`
* enabled `Brave News` using the introduction card/modal and ensured that `Feed v2` was being used

**`Example`** | **`Example`**
----------------|------------------
![image](https://github.com/brave/brave-browser/assets/2602313/93b67071-43a1-4934-aeea-fae17cb83677) | ![image](https://github.com/brave/brave-browser/assets/2602313/543305b1-2c5a-4009-9fc2-d5e781864d0c)

### `Test Case #2` - `PASSED`

* installed `1.64.7 Chromium: 121.0.6167.75` using the `standalone` (offline) installer
* launched Brave using `brave.exe --enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed`
* ensured there's no Griffin studies being listed/mentioned via `brave://version`
* restarted Brave using `brave.exe --enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed`
* ensured that `BraveFeedUpdateStudy` doesn't appear under `brave://version`
* enabled `Brave News` using the introduction card/modal and ensured that `Feed v2` was being used

**`Example`** | **`Example`**
----------------|------------------
![griffin1](https://github.com/brave/brave-browser/assets/2602313/ffc7b946-0bdc-4ad8-a2e9-ed01ab80a898) | ![griffin2](https://github.com/brave/brave-browser/assets/2602313/f0749cef-346b-4077-b4b8-8514cde3b57f)

## `BETA` - `Feed v2` enabled by default (without Griffin)

Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.63.127 Chromium: 121.0.6167.75 (Official Build) beta (64-bit)
-- | --
Revision | 31b0815b75acd59aecd04b6870ccd2b073fe7bad
OS | Windows 11 Version 23H2 (Build 22631.3007)
```

### `Test Case #1` - `PASSED`

* installed `1.63.127 Chromium: 121.0.6167.75` using the `standalone` (offline) installer
* once installed, ensured there's no Griffin studies being listed/mentioned via `brave://version`
* enabled `Brave News` using the introduction card/modal and ensured that `Feed v2` was being used

**`Example`** | **`Example`**
----------------|------------------
![image](https://github.com/brave/brave-browser/assets/2602313/200f786e-4146-4e0b-bc84-9adda60b6ef0) | ![image](https://github.com/brave/brave-browser/assets/2602313/4fbd8b7c-e586-4166-a5dc-1be9afc2b710)

### `Test Case #2` - `PASSED`

* installed `1.63.127 Chromium: 121.0.6167.75` using the `standalone` (offline) installer
* launched Brave using `brave.exe --enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed`
* ensured there's no Griffin studies being listed/mentioned via `brave://version`
* restarted Brave using `brave.exe --enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed`
* ensured that `BraveFeedUpdateStudy` doesn't appear under `brave://version`
* enabled `Brave News` using the introduction card/modal and ensured that `Feed v2` was being used

**`Example`** | **`Example`**
----------------|------------------
![image](https://github.com/brave/brave-browser/assets/2602313/e2e4ed36-a4c8-412f-9d81-0a59935afb6e) | ![image](https://github.com/brave/brave-browser/assets/2602313/bce9abb7-dac4-4de0-a15b-c5b437224c4b)

## `Release` - `Feed v2` disabled by default (enable via Griffin)

Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.62.147 Chromium: 120.0.6099.234 (Official Build) (64-bit)
-- | --
Revision | 3b25c3743150a54485dea24f0ceb1e69d6db51bc
OS | Windows 11 Version 23H2 (Build 22631.3007)
```

### `Test Case #1` - `PASSED`

* installed `1.62.147 Chromium: 120.0.6099.234` using the `standalone` (offline) installer
* once installed, ensured there's no Griffin studies being listed/mentioned via `brave://version`
* enabled `Brave News` using the introduction card/modal and ensured that `Feed v1` was being used

**`Example`** | **`Example`**
----------------|------------------
![image](https://github.com/brave/brave-browser/assets/2602313/c81ee176-8cc5-4d13-8078-c8f7b1addaa7) | ![image](https://github.com/brave/brave-browser/assets/2602313/4d25e222-bc3b-463d-ba16-146cc70fe3f5)

### `Test Case #2` - `BraveFeedUpdateStudy:Default` - `PASSED`

* installed `1.62.147 Chromium: 120.0.6099.234` using the `standalone` (offline) installer
* launched Brave using `brave.exe --enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed`
* ensured there's no Griffin studies being listed/mentioned via `brave://version`
* restarted Brave using `brave.exe --enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed`
* ensured that `BraveFeedUpdateStudy:Default` appears under `brave://version` (`Feed v2` disabled)
* enabled `Brave News` using the introduction card/modal and ensured that `Feed v1` was being used

**`Example`** | **`Example`**
----------------|------------------
![image](https://github.com/brave/brave-browser/assets/2602313/574b87d6-5320-477c-b375-950fa6969dc4) | ![image](https://github.com/brave/brave-browser/assets/2602313/a57363e2-3272-4b24-888b-b73c7eb68fe2)

### `Test Case #3` - `BraveFeedUpdateStudy:Enabled` - `PASSED`

* installed `1.62.147 Chromium: 120.0.6099.234` using the `standalone` (offline) installer
* launched Brave using `brave.exe --enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed`
* ensured there's no Griffin studies being listed/mentioned via `brave://version`
* restarted Brave using `brave.exe --enable-logging=stderr --reset-variation-state --variations-server-url=https://variations.bravesoftware.com/seed`
* ensured that `BraveFeedUpdateStudy:Enabled` appears under `brave://version` (`Feed v2` enabled)
* enabled `Brave News` using the introduction card/modal and ensured that `Feed v2` was being used

**`Example`** | **`Example`**
----------------|------------------
![image](https://github.com/brave/brave-browser/assets/2602313/7aaacd33-7bc7-4c28-8398-ab372bc1be17) | ![image](https://github.com/brave/brave-browser/assets/2602313/2464ef5c-8796-494e-86c6-8cd6b5555215)

**Comment by kjozwiak** [comment]
@LaurenWags @StephenBass @btlechowski for `macOS` & `Linux`, I wouldn't worry about checking `Nightly` & `BETA`. I think one check on `Windows` should be enough. Just run through the cases on `Release` and make sure that both `BraveFeedUpdateStudy:Default` (disabled) and `BraveFeedUpdateStudy:Enabled` are working as expected. It's set to `50%` on `main` as per https://github.com/brave/brave-variations/pull/882/files#diff-7ac2945ede68c73330363911678f6c9a2a6290b70e2dd170868295f65da7e872R82.

**Comment by LaurenWags** [comment]
Removed `QA/Blocked` per https://github.com/brave/brave-browser/issues/35317#issuecomment-1902845000

**Comment by LaurenWags** [comment]
## `Release` - `Feed v2` disabled by default (enable via Griffin)

Verification in progress with:

```
Brave | 1.62.149 Chromium: 121.0.6167.75 (Official Build) (x86_64)
-- | --
Revision | ff84587bd70af9fcbcbe59fc5194ca65082759c4
OS | macOS Version 13.6.3 (Build 22G436)
```

### `Test Case #1` - `InProgress`

* installed `1.62.149 Chromium: 121.0.6167.75` 
* once installed, ensured there's no Griffin studies being listed/mentioned via `brave://version`
* enabled `Brave News` using the introduction card/modal and ensured that `Feed v1` was being used

**`Example`** | **`Example`**
----------------|------------------


### `Test Case #2` - `BraveFeedUpdateStudy:Default` - `TBD`

* installed `1.62.149 Chromium: 121.0.6167.75` 
* launched Brave using `--enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed`
* ensured there's no Griffin studies being listed/mentioned via `brave://version`
* restarted Brave using `--enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed`
* ensured that `BraveFeedUpdateStudy:Default` appears under `brave://version` (`Feed v2` disabled)
* enabled `Brave News` using the introduction card/modal and ensured that `Feed v1` was being used

**`Example`** | **`Example`**
----------------|------------------


### `Test Case #3` - `BraveFeedUpdateStudy:Enabled` - `TBD`

* installed `1.62.149 Chromium: 121.0.6167.75` 
* launched Brave using `--enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed`
* ensured there's no Griffin studies being listed/mentioned via `brave://version`
* restarted Brave using `--enable-logging=stderr --reset-variation-state --variations-server-url=https://variations.bravesoftware.com/seed`
* ensured that `BraveFeedUpdateStudy:Enabled` appears under `brave://version` (`Feed v2` enabled)
* enabled `Brave News` using the introduction card/modal and ensured that `Feed v2` was being used

**`Example`** | **`Example`**
----------------|------------------

**Comment by btlechowski** [comment]
Verified with

Brave | 1.62.149 Chromium: 121.0.6167.75 (Official Build) (64-bit)
-- | --
Revision | ff84587bd70af9fcbcbe59fc5194ca65082759c4
OS | Linux


### `Test Case #1` - `PASSED`

* installed `1.62.149 Chromium: 121.0.6167.75` 
* once installed, ensured there's no Griffin studies being listed/mentioned via `brave://version`
* enabled `Brave News` using the introduction card/modal and ensured that `Feed v1` was being used

![image](https://github.com/brave/brave-browser/assets/34715963/4f8bdd5c-5a57-4f03-a447-2c9dc232bef9)|![image](https://github.com/brave/brave-browser/assets/34715963/9372f338-621a-45e6-ab5b-8152bd38885b)
--|--

### `Test Case #2` - `BraveFeedUpdateStudy:Default` - `PASSED`

* installed `1.62.149 Chromium: 121.0.6167.75` 
* launched Brave using `--enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed`
* ensured there's no Griffin studies being listed/mentioned via `brave://version`
* restarted Brave using `--enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed`
* ensured that `BraveFeedUpdateStudy:Default` appears under `brave://version` (`Feed v2` disabled)
* enabled `Brave News` using the introduction card/modal and ensured that `Feed v1` was being used

![image](https://github.com/brave/brave-browser/assets/34715963/f2023eb1-8932-4b77-b008-63a2c4425ec4)|![image](https://github.com/brave/brave-browser/assets/34715963/5175288b-db05-4c6f-b2f9-50a24d0ebd44)
--|--


### `Test Case #3` - `BraveFeedUpdateStudy:Enabled` - `PASSED`

* installed `1.62.149 Chromium: 121.0.6167.75` 
* launched Brave using `--enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed`
* ensured there's no Griffin studies being listed/mentioned via `brave://version`
* restarted Brave using `--enable-logging=stderr --reset-variation-state --variations-server-url=https://variations.bravesoftware.com/seed`
* ensured that `BraveFeedUpdateStudy:Enabled` appears under `brave://version` (`Feed v2` enabled)
* enabled `Brave News` using the introduction card/modal and ensured that `Feed v2` was being used

![image](https://github.com/brave/brave-browser/assets/34715963/188176a4-43eb-40db-ab99-cebe3a36d151)|![image](https://github.com/brave/brave-browser/assets/34715963/d2d0f2b5-d20f-4550-bd4d-5a6727c759e5)
--|--
