### ISSUE TITLE
Confirmations state could be reset due to race condition when saving/loading state

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#3532]
## Description 
Confirmations state could be reset due to race condition when saving/loading state

## Steps to Reproduce

   1. View an Ad
   2. Close the browser
   3. Launch the browser

## Actual result:
`Defaults/rewards_service/confirmations.json` state could be reset to defaults

## Expected result:
`Defaults/rewards_service/confirmations.json` state should retained previous state

## Reproduces how often: 
Intermittent issue

## Brave version (brave://version info)
0.63.x

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by GeetaSarvadnya** [comment]
Verification passed on

Brave | 0.63.35 Chromium: 74.0.3729.61 (Official Build) beta (64-bit)
-- | --
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Windows 10 OS Build 17134.523

- Verified the test plan from https://github.com/brave/brave-core/pull/1809

Default - confirmations.json

"next_token_redemption_date_in_seconds": "13199971578",
  "transaction_history": {
    "transactions": []
  },

1st AD - confirmations.json

"next_token_redemption_date_in_seconds": "13199971578",
  "transaction_history": {
    "transactions": [
      {
        "confirmation_type": "view",
        "estimated_redemption_value": 0.05,
        "timestamp_in_seconds": "13199366906"
      },
      {
        "confirmation_type": "click",
        "estimated_redemption_value": 0,
        "timestamp_in_seconds": "13199366909"
      },
      {
        "confirmation_type": "landed",
        "estimated_redemption_value": 0,
        "timestamp_in_seconds": "13199366919"
      }
    ]
  },


2nd Ad- confirmations.json:

"next_token_redemption_date_in_seconds": "13199971578",
  "transaction_history": {
    "transactions": [
      {
        "confirmation_type": "view",
        "estimated_redemption_value": 0.05,
        "timestamp_in_seconds": "13199366906"
      },
      {
        "confirmation_type": "click",
        "estimated_redemption_value": 0,
        "timestamp_in_seconds": "13199366909"
      },
      {
        "confirmation_type": "landed",
        "estimated_redemption_value": 0,
        "timestamp_in_seconds": "13199366919"
      },
      {
        "confirmation_type": "view",
        "estimated_redemption_value": 0.05,
        "timestamp_in_seconds": "13199368502"
      },
      {
        "confirmation_type": "click",
        "estimated_redemption_value": 0,
        "timestamp_in_seconds": "13199368508"
      },
      {
        "confirmation_type": "landed",
        "estimated_redemption_value": 0,
        "timestamp_in_seconds": "13199368518"
      }
    ]
  },
