### ISSUE TITLE
[Android] Implement Soprano external account option

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#35334]
## Description

https://github.com/brave/internal/issues/1105

**Comment by Uni-verse** [comment]
@Uni-verse @hffvld QA will need to test https://github.com/brave/brave-browser/issues/36433 to ensure correct URL for explorer is used.

**Comment by LaurenWags** [comment]
Verification in progress on Android with:

```
Brave	1.64.97 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
Revision	f7c8f13563bfe1063db456650cb43207e1c960c0
OS	Android 12; Build/SP1A.210812.016.C1; 31; REL
```

Verification notes can be found under https://github.com/brave/internal/issues/1105#issuecomment-1992119194

**Comment by srirambv** [comment]
Verification passed on Lenovo Tab with Android 13 running 1.63.107 x64 build. 
- Verification notes can be found [here](https://github.com/brave/internal/issues/1105#issuecomment-2003772616)
