### ISSUE TITLE
'Sync everything' enabled when connecting device to sync chain [CR121]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#35333]
## Description 
'Sync everything' enabled when connecting device to sync chain

Regression with Chromium 121

## Steps to reproduce 

   1. Start with fresh profile
   2. Add device by scanning QR code.
   3. Check Sync `Data Preferences`

## Actual result 

![Screenshot 2024-01-16 at 11 19 08 AM](https://github.com/brave/brave-browser/assets/17885425/d2140410-bedd-417a-a173-90fcfd14eb49)

## Expected result
Only Sync Bookmarks should be enabled in preferences.

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy Tab S7
   - Android version: 13
   
## Brave version
`1.63.121, Chromium 121.0.6167.57`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Labelling as `QA/Blocked` as the above also needs to land within `1.62.x` which will happen once https://github.com/brave/brave-core/pull/21593 is uplifted into `1.62.x`.

**Comment by kjozwiak** [comment]
The above requires `1.62.149` or higher for `1.62.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP11.231215.007 release-keys
Brave build: 1.62.149
Chromium: 121.0.6167.75 (Official Build) (64-bit) 
```
---------------------------
<details>
<summary> Fresh profile - PASS </summary>

**STEPS:**
1. Install and launch Brave `1.62.149` or later
2. Settings > Sync
3. Scan QR code > Data Preferences

**ACTUAL RESULTS:**
- Verified that only `Bookmarks` are synced by default
- Verified that it's possible to enable `Sync everything`

---------------------------

https://github.com/brave/brave-browser/assets/128532965/54f75dc6-9193-420b-9e4a-f47e1d6e6218

</details>

<details>
<summary> Upgraded profile - PASS </summary>

**STEPS:**
1. Install and launch Brave `1.61.x`
2. Settings > Sync
3. Scan QR code > Data Preferences > Confirm that only `Bookmarks` are synced
4. Upgrade Brave to `1.62.149` or later
5. Launch Brave > Settings > Sync > Data Preferences > Verify

**ACTUAL RESULTS:**
- Verified that only `Bookmarks` are synced after the Brave upgrade
- Verified that it's possible to enable `Sync everything`

---------------------------

https://github.com/brave/brave-browser/assets/128532965/3a1f75c7-d1c9-412d-a93c-2ca832eb7ddf

</details>
