### ISSUE TITLE
Manual test run on `Linux x64` for `1.63.x - Nightly` (Checking C121)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#35336]
Using the following combination of Linux versions and configurations, ensure that you can load several websites without any issues using a build running `C121`. For example, ensure that the page actually loads and doesn't have any obvious/visible artifacts. Some context: try avoiding shipping `Linux` with issues like https://github.com/brave/brave-browser/issues/31947.

### Environment using `Intel (CPU)` & `Nvidia (GPU)` running `Ubuntu LTS`

Note: Regarding GPU drivers, ensure that the machine is using `nvidia` proprietary drivers

* [x] `Wayland` & `GNOME`
* [ ] `Xorg` & `KDE`

### Environment using `AMD (CPU)` & `AMD (GPU)` running `Fedora`

Note: Regarding GPU drivers, ensure that the machine is using `amdgpu` open source drivers

* [x] `Wayland` & `KDE`
* [x] `Xorg` & `GNOME`

**Comment by btlechowski** [comment]
Verified with Intel+Nvidia GPU

Brave | 1.64.3 Chromium: 121.0.6167.57 (Official Build) nightly (64-bit)
-- | --
Revision | 0ecd8a5470d06ce96921cb7585ecbc0f9878f3cf
OS | Ubuntu 22.04 LTS, GNOME 42.9
