### ISSUE TITLE
Add the ability to modify prompts and have it resubmit and truncate the history

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#35342]
We need the user to be able to go back and change a prompt to tweak it at any point in their submitted history.

cc @aguscruiz

**Comment by aguscruiz** [comment]
Would this continue the conversation or create a new one (sort of like branching out)

**Comment by bbondy** [comment]
Maybe we should allow both options for both? Edit & regenerate vs Edit in place (so it affects future prompts only?)

**Comment by bbondy** [comment]
Definitely not branching though.

**Comment by aguscruiz** [comment]
Design mocks here:
https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=1476-50011&mode=design

**Comment by petemill** [comment]
> Definitely not branching though.

@bbondy Why definitely not branching? Competing products have this feature. It might be nice to not destroy the previous history, and even continue the conversation on any of the branches especially if the user is comparing different options.

I'm asking because this affects data structure - edits for an entry could be either an array of strings (if we're destroying proceeding history) or an array of entries (to maintain history).

**Comment by bbondy** [comment]
I'm not opposed to it longer term, but I think we can survive without the complexity for now and circle back later if we feel that the UX isn't quite right.

**Comment by Asizdhung** [comment]
Im not opposed to your idea but its been 4 days that i have been doing this and half of so respectable teachers are so good they teach me so well half of them made me bot. In my like just one year class I touched computer sorry I didn’t had the luxury. I would like to thank those who have helped me and plz don’t take me to credit card acc im broke.

**Comment by petemill** [comment]
@aguscruiz What about editing the user action (aka slash tool)? If we're just using a simple text input and not the regular input to edit then the user is not able to change it?

<img width="666" alt="image" src="https://github.com/brave/brave-browser/assets/741836/8e752ad9-1239-47ae-993e-21fcfd0c36b4">

**Comment by aguscruiz** [comment]
@petemill thoughts on this?

The tool has a pencil button on the right side. If you click it you get the tools menu. 
There's also a close button to get rid of it if you want.

I'm trying to not overly complicate this UI

<img width="1434" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/2666f2f0-2ce4-4b99-ae27-790e398c5925">

**Comment by yrliou** [comment]
@aguscruiz @petemill I think it's probably better to be discussed in a new issue for slash tools, I'll create one. For this issue, I'll just don't have the buttons for actions.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.107 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | ab3f504ca4a15c330f60a93d5e3773d780498980
OS | Windows 11 Version 23H2 (Build 22631.4112)

- Verified steps from [brave/brave-core#24558](https://github.com/brave/brave-core/pull/24558)
- Verified able to edit prompt and resubmit it 
- Verified able to edit bot prompt and responses

https://github.com/user-attachments/assets/cdc94683-dccf-468f-942f-aec646941d01

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.70.107 x64 beta build
- Verified steps from [brave/brave-core#24558](https://github.com/brave/brave-core/pull/24558)
- Verified able to edit prompt and resubmit it 
- Verified able to edit bot prompt and responses

https://github.com/user-attachments/assets/18ee6981-0514-4da6-9411-d8efe2a39996
