### ISSUE TITLE
Some Google login integrations do not work

### ISSUE THREAD

**Issue by mrzealot** [brave/brave-browser#3534]
Embedded Google login integrations break with shields up. This is due to iframes loading pages from accounts.google.com and not being able to set cookies.
Examples include:

- https://imgur.com/signin
- https://pinterest.com/login/
- https://www.zillow.com/user/Login.htm
- https://www.yelp.com/login
- ...

Note that there are numerous other Google login integrations that work just fine because they use a redirect-based authentication instead of the embedded iframes.

**Comment by bbondy** [comment]
Marking as QA/No since test case for this is covered in https://github.com/brave/brave-browser/issues/3489
