### ISSUE TITLE
Edit generated AI replies

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#35343]
Some chat interfaces allow the user to modify generated replies so that they can customize the flow of the conversation. This is very similar to https://github.com/brave/brave-browser/issues/35342 but tracking it differently in case there are any security concerns. 

cc @aguscruiz

**Comment by aguscruiz** [comment]
Is there an example of this? Do you mean editing the actual generated response from Leo?

**Comment by bbondy** [comment]
Yes. Basically since the entire history is included when you ask a new question, you can guide the conversation as you want.

**Comment by bbondy** [comment]
Copying from Slack:
Edit generated AI replies
> Design: https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=1476-50011&mode=design
> Also pretty straightforward, users can open the menu on prompts and answers, select edit and change anything.
> One thing I added is the editing history on both, so we can always trace back the original version. (ed

**Comment by aguscruiz** [comment]
Updated design here:
https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/%F0%9F%94%84-Leo-%5BIN-PROGRESS%5D?node-id=4604-59495

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.70.107 x64 beta build
- Verified steps from [brave/brave-core#24944](https://github.com/brave/brave-core/pull/24944)
- Verified editing a conversation, AI uses the edited comment for generating response 
- Verified editing message works as expected 

https://github.com/user-attachments/assets/05955873-769d-4b2e-a22c-8a3d415df457
