### ISSUE TITLE
Change Leo onboarding opt-in copy

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#35355]
Change title to `Chat Privately with Brave Leo`
Change button CTA to `I understand`

<img width="529" alt="Screenshot 2024-02-06 at 9 33 42 AM" src="https://github.com/brave/brave-browser/assets/4730197/11c6cef1-b08b-4088-99fc-a5ed46afcec4">

See body in https://docs.google.com/document/d/1DOj1RSSmZ82ER1aGYlFEkM1nmreT998Fe7bsKr1Y1T0/edit#heading=h.lszc9i58xq4q

**Comment by mattmcalister** [comment]
See updated body copy in doc: https://docs.google.com/document/d/1DOj1RSSmZ82ER1aGYlFEkM1nmreT998Fe7bsKr1Y1T0/edit#heading=h.lszc9i58xq4q

**Comment by mattmcalister** [comment]
Note that some discussions are still happening around precise word choices https://github.com/brave/reviews/issues/1496#issuecomment-1919955692

**Comment by kjozwiak** [comment]
The above requires `1.63.149` or higher for `1.63.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP11.231215.009 release-keys
Brave build: 1.63.149
Chromium: 121.0.6167.164 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-browser/issues/35355#issue-2084905331

**ACTUAL RESULTS:**
- Verified that the title was updated to `Chat Privately with Brave Leo`
- Verified that the CTA button was updated to `I understand`
- Verified that tapping `I understand` triggers Leo response to the query

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/80ff558e-4174-41a0-8576-ec122f1838e9) | ![2](https://github.com/brave/brave-browser/assets/128532965/7f7a5cdc-5354-4094-8818-daec5ff07cd7) | ![3](https://github.com/brave/brave-browser/assets/128532965/006208bc-9a99-4208-91d6-b2a7a68d4297) |
