### ISSUE TITLE
"Allowed"/"Not allowed" URL buttons don't have a background/shape with light theme

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#35358]
## Description 

After allowing (or blocking) a permission request, the URL shows either "Allowed" or "Not allowed" briefly before returning to the tune icon.

In 1.62.x and 1.63.x when using light theme, "Allowed" or "Not Allowed" doesn't have a button background, so you can't see the shape. This works fine with dark theme. This also works fine on 1.61.x with light theme, so this appears to be a regression within 1.62.x.

## Steps to Reproduce

   1. Using light theme, visit a site where you can test permissions (I used browserleaks.com/geo and permission.site)
   2. If permission isn't triggered on visiting, trigger permission request
   3. Allow or block request
   4. Watch URL bar

## Actual result:

1.62.x light theme the "button" doesn't have a background:

<img width="261" alt="Screenshot 2024-01-16 at 5 02 48 PM" src="https://github.com/brave/brave-browser/assets/28145373/4fd3008d-eda4-4877-92e5-a3039f91b28b"> | <img width="235" alt="Screenshot 2024-01-16 at 5 03 04 PM" src="https://github.com/brave/brave-browser/assets/28145373/d19e8670-f6c8-48c5-8bed-97ad683d2d76">
-- | --

## Expected result:

"Allowed" and "Not allowed" should have a button background like in 1.61.x for light theme:
<img width="272" alt="Screenshot 2024-01-16 at 5 00 05 PM" src="https://github.com/brave/brave-browser/assets/28145373/0f316f47-0130-482d-8d09-83195380e614">

Also, dark theme is fine for 1.62.x for these:

<img width="247" alt="Screenshot 2024-01-16 at 5 02 19 PM" src="https://github.com/brave/brave-browser/assets/28145373/60f002b0-b36b-47b2-9beb-1fbd8aad74e5"> | <img width="288" alt="Screenshot 2024-01-16 at 5 03 26 PM" src="https://github.com/brave/brave-browser/assets/28145373/35e5e5e1-6e28-4c57-a2a2-98e62b06ba40">
-- | --

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.62.143, 1.62.144 

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, not with 1.61.x
- Can you reproduce this issue with the beta channel? yes 1.62.x (reproduced by @MadhaviSeelam )
- Can you reproduce this issue with the nightly channel? yes 1.63.x (reproduced by @stephendonner )

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron

**Comment by rebron** [comment]
cc: @simonhong

**Comment by kjozwiak** [comment]
The above requires `1.62.155` or higher for `1.62.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.62.155 Chromium: 121.0.6167.85 (Official Build) (x86_64)
-- | --
Revision | 91c989228daf153ef41bd965f268fabc7b9dbbf0
OS | macOS Version 13.6.4 (Build 22G513)
```
