### ISSUE TITLE
Clicking `Ad` icon on Brave News inline ad should respect the `Open article in` setting 

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#35353]
Follow up to https://github.com/brave/brave-browser/issues/35235

By default `Open article in` is set to `new tab`, but clicking the `Ad` icon on Brave News inline ad opens `brave://rewards` in current tab

## Steps to Reproduce

1. Clean profile
2. Open NTP
3. Scroll down and enable Brave News
4. Trigger a Brave News inline ad
5. Click `Ad` icon on the ad

## Actual result:

`brave://rewards` is opened in current tab

## Expected result:
`brave://rewards` is opened in new tab

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.62.144 Chromium: 120.0.6099.217 (Official Build) beta (64-bit)
-- | --
Revision | 75de8d953f6a5686e425d46d7f0dc9284dc1c064
OS | Linux

cc @fallaciousreasoning @stephendonner

**Comment by kjozwiak** [comment]
The above requires `1.62.148` or higher for `1.62.x` verification 👍

**Comment by btlechowski** [comment]
Verified with

Brave | 1.62.149 Chromium: 121.0.6167.75 (Official Build) (64-bit)
-- | --
Revision | ff84587bd70af9fcbcbe59fc5194ca65082759c4
OS | Linux


Verified https://github.com/brave/brave-browser/issues/35353

### Open article in new tab

![image](https://github.com/brave/brave-browser/assets/34715963/80f72cf8-862a-45e0-adb0-94c2bdd835ca)|![image](https://github.com/brave/brave-browser/assets/34715963/22b203e3-dbbf-4323-a9c0-a1504305b782)
--|--

### Open article in current tab

![image](https://github.com/brave/brave-browser/assets/34715963/ed951c0f-06a2-4cb1-ac7e-7b09afd701ed)|![image](https://github.com/brave/brave-browser/assets/34715963/0e477f33-d1c1-4f39-b8fb-48b8ddec0a61)
--|--
