### ISSUE TITLE
 A small gap (towards the left) between the edge and the header bar in an upgraded profile

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#35374]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/34702

 A small gap (towards the left) between the edge and the header bar in an upgraded profile
## Steps to Reproduce

   1. Clean profile `1.62.106`
   2. Upgrade the profile to `1.63.120`
   3. Open brave://settings
   4. A small gap (towards the left) between the edge and the header bar in an upgraded profile
  
## Actual result:

 A small gap (towards the left) between the edge and the header bar in an upgraded profile
![image](https://github.com/brave/brave-browser/assets/38657976/2afe3920-174a-47e4-81e7-2c8ec0be659f)

## Expected result:
RC - 1.61.x
![image](https://github.com/brave/brave-browser/assets/38657976/b0a3f869-89e4-4d00-99de-a23ab90eac15)

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @mkarolin

**Comment by GeetaSarvadnya** [comment]
This issue exists in CR 120 also, I have upgraded profile from 1.63.106 to 1.63.119

![image](https://github.com/brave/brave-browser/assets/38657976/005dbbd8-ca08-482b-bf0e-7c9ef054a339)

**Comment by rebron** [comment]
Closing as wontfix. Expected design https://github.com/brave/brave-browser/issues/34229
brave://flags/#brave-horizontal-tabs-update can see the difference with this flag enabled which is 100% on for beta and nightly.

**Comment by cyraid** [comment]
> Closing as wontfix. Expected design #34229 brave://flags/#brave-horizontal-tabs-update can see the difference with this flag enabled which is 100% on for beta and nightly.

@rebron With that setting disabled, the font remains in place (not centered), and gets clipped in vertical tabs. There really should be a change to have connected tabs (no gap #NoTabGap).
