### ISSUE TITLE
`Background sync` permission content settings image is not shown in the site settings page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#35372]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/34702
`Background sync` permission content settings image is not shown in the site settigs page
## Steps to Reproduce

   1. Clean or upgrade profile 1.63.x CR121 build
   2. Open any site
   3. Click on the `View site information` icon
   4. Click on `Site setting`

## Actual result:

`Background sync` permission content settings image is not shown in the site settigs page

![image](https://github.com/brave/brave-browser/assets/38657976/7855f7c2-fd89-4037-86dc-7e8eedc9f865)

## Expected result:

`Background sync` permission content settings image should be shown in the site settigs page

RC version 1.61.x
![image](https://github.com/brave/brave-browser/assets/38657976/8be71e32-2d86-4865-a94d-c96b2f553943)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.61.120 Chromium: 120.0.6099.234 (Official Build) (64-bit)
-- | --
Revision | 362207c81bff0740a8b6cff62dd91c6789f5698f
OS | Windows 10 Version 22H2 (Build 19045.3930)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @mkarolin

**Comment by mkarolin** [comment]
@fallaciousreasoning, I only gave a cursory look, but do we need a Leo icon for this? The page is looking for `sync.svg`, but I think from `cr`, not from `settings`.

**Comment by rebron** [comment]
cc: @aguscruiz We need an image for this one.

**Comment by aguscruiz** [comment]
hey @mkarolin, the icon is called `product-sync`, you'll probably find it with that name

**Comment by mkarolin** [comment]
@aguscruiz I do see, `product_sync` icon, but it seems we use that one for `Sync`. Do we want to reuse?
In the current release (1.61.120) they are slightly different:

![image](https://github.com/brave/brave-browser/assets/41635752/63df4c81-7122-4d9c-a109-2b6fd833299e)

**Comment by aguscruiz** [comment]
Yeah, let's use the one on the left, `product-sync` 👌

**Comment by kjozwiak** [comment]
The above requires `1.62.150` or higher for `1.62.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.62.150 Chromium: 121.0.6167.85 (Official Build) (64-bit)
-- | --
Revision | c01f5cde4d5d5e41134c0ccdb1868acd80a64a34
OS | Windows 10 Version 22H2 (Build 19045.3930)
```
- Confirmed that the `Background sync` permission content settings image is shown in the site settings page
![image](https://github.com/brave/brave-browser/assets/38657976/49e1638a-2b0e-418b-b4f3-eb828044a3da)
