### ISSUE TITLE
AI Chat doesn't restrict text to main elements if those elements dont have headings or paragraphs

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#35371]
If we don't find those content nodes, then we should still try to ignore parts of the page that aren't part of the article (e.g. in `<article>` or `<main>` tags). See PR for test detail

This can help reduce truncation by not sending all the text content from the page (including header, footer, etc) and increase relevance.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

### Steps:
1. installed `1.64.52`
2. launched Brave
3. clicked on Leo
4. clicked Accept and begin
5. loaded https://cdpn.io/pen/debug/yLGXPqw/ee0b1b03ebe8b75503481ce1ccd1769c
6. asked each LLM {Mixtral, Claude, llama2-13b}: "What is the text of the article?"

### Confirmed all of the LLMs answered with "I am part of the article"

`Mixtral` | `Claude` | `llama2-13b`
---------|-----------|-------------
<img width="1312" alt="Screen Shot 2024-02-06 at 3 14 01 PM" src="https://github.com/brave/brave-browser/assets/387249/a2e5ad07-c59e-427c-9f64-99095739293b"> | <img width="1312" alt="Screen Shot 2024-02-06 at 3 15 13 PM" src="https://github.com/brave/brave-browser/assets/387249/59aadd83-30f2-4883-b91d-498a17f9bf28"> | <img width="1312" alt="Screen Shot 2024-02-06 at 3 15 44 PM" src="https://github.com/brave/brave-browser/assets/387249/69b68b02-74cb-45a4-bba5-e729951fee19">

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.64.95 Chromium: 122.0.6261.94 (Official Build) beta (64-bit) 
Revision	6f4193fbcee7c358ae3684f777faa9f12e52206e
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
### Steps:
1. installed `1.64.52`
2. launched Brave
3. clicked on Leo
4. clicked Accept and begin
5. loaded https://cdpn.io/pen/debug/yLGXPqw/ee0b1b03ebe8b75503481ce1ccd1769c
6. asked each LLM {Mixtral, Claude, llama2-13b}: "What is the text of the article?"

### Confirmed all of the LLMs answered with "I am part of the article"

Mixtral | Claude | llama
-|-|-
![Screenshot 2024-03-05 at 6 26 57 PM](https://github.com/brave/brave-browser/assets/17885425/131ef413-11c9-4f86-8767-13f76b61a1e1) | ![Screenshot 2024-03-05 at 6 27 33 PM](https://github.com/brave/brave-browser/assets/17885425/5884e51d-5d15-4ca5-82a3-c863f90437c6) | ![Screenshot 2024-03-05 at 6 28 14 PM](https://github.com/brave/brave-browser/assets/17885425/fb5ed835-b1da-472a-8ebe-830520d2eb50)
