### ISSUE TITLE
WebTorrent: Ensure we are on the latest webtorrent library version

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#35385]
Lets make sure we're pulling the latest webtorrent https://github.com/webtorrent/webtorrent changes and that they're working correctly. Please post a security issue for the PR since this includes a third-party dependency.

**Comment by jamesmudgett** [comment]
Please open a sec review for the PR on this one.

**Comment by muliswilliam** [comment]
@jamesmudgett I will open one 👍

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.69.117 Chromium: 127.0.6533.57 (Official Build) beta (64-bit)
-- | --
Revision | 7b5104c54992f658db7f6b1e7441021612ba71a3
OS | Windows 10 Version 22H2 (Build 19045.4651)
```
