### ISSUE TITLE
Don't require Brave to be restarted when changing `Show Sponsored Images` setting as it is not required when performing this action in `Rewards` settings screen

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#35387]
## Description 

Don't require Brave to be restarted when changing the `Show Sponsored Images` setting as it is not required when performing this action in the `Rewards` settings screen.

## Steps to reproduce 

   1. Launch Brave
   2. Join `Rewards`
   3. Open `Rewards settings` screen > Tap `New tab page ads` toggle switch to disable (or enable) it
   4. Confirm that you can disable (or enable) it without Brave restart
   5. Tree-dot menu > Settings > New Tab Page > Confirm that these options are synced and `Show Sponsored Images` is disabled (or enabled) now
   6. Now change the setting for `Show Sponsored Images` toggle switch > Observe that Brave needs to be restarted to apply the changes

## Actual result 

`Show Sponsored Images` in Brave settings and `New tab page ads` on `Brave Rewards` screen are equal (same thing) and synced. However, Brave doesn't need to be restarted when changing `New tab page ads`, and needs to be restarted when changing `Show Sponsored Images`.

https://github.com/brave/brave-browser/assets/128532965/83b5e960-457b-4fe4-b61f-65b80043da4e

## Expected result

Don't require Brave to be restarted when changing the `Show Sponsored Images` setting as it is not required when performing this action in the `Rewards` settings screen.

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? YES
- Can you reproduce this issue with the current Play Store Beta version? YES
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM 
   - Device type (Phone, Tablet, Phablet): ANY
   - Android version: ANY
   
## Brave version

```
Brave build: 1.63.124
Chromium: 121.0.6167.57 (Official Build) canary (64-bit) 
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by deeppandya** [comment]
@hffvld i checked the issue from my side. it seems we need to have the relaunch mainly to update the image on NTP if it's opened in the background. 
STR would be : 
1. open NTP
2. Go to settings and disable background image option
3. do not relaunch the app
4. exit settings screen

You would see the same background image even if the flag is updated.
