### ISSUE TITLE
AI Chat: mixtral keeps surrounding things in quote marks

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#35391]
This is because we have a general seed "Here is your response: " that llama seems to need but makes mixtral do weird stuff

**Comment by kjozwiak** [comment]
The above requires `1.62.149` or higher for `1.62.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.62.149 Chromium: 121.0.6167.75 (Official Build) (64-bit)
-- | --
Revision | ff84587bd70af9fcbcbe59fc5194ca65082759c4
OS | Windows 11 Version 22H2 (Build 22621.3007)
```

Installed `1.62.149`
launched Brave (with Leo staging flag ` --env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev)
opened sidebar via toolbar
clicked `Leo` icon in the sidebar
entered `test` in the `Enter a prompt here` field
clicked `Accept and begin` button
opened a new tab and opened Leo sidepanel
entered `hi` in the `Enter a prompt here` field

Confirmed no `Mixtral-specific oddities` mentioned above with 


example | example | example | example | example 
----- | ---- | ----- | ----- | -----
<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/69f3ac49-3b17-410e-95cf-ca50e37e7e57">|<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6bcbeac1-1d1e-4e2e-89f4-0ac8edc47c6d">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6cff1977-8dc3-4c59-9e94-702d7a2c1772">|<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/4206ab73-7798-4ffd-bb5a-7aa47d86e084">|<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/45f3ddd6-c978-45ab-948f-0623024d115b">
