### ISSUE TITLE
Crash on new profile logging into `account.brave.com`

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#35395]
## Description 
@pavelbrm reported in Slack. He has a Mac with M2 Pro processor running macOS Sonoma.

Crash seems to be related to VPN service when getting the keyed service for this browser instance.  Private window is fine because SKU SDK and VPN service are not created for private profile.

For the code in Brave, the last call is here:
https://github.com/brave/brave-core/blob/b4278ee85661ba2fa7ab7c43ff0c5b08b9f0917d/browser/brave_vpn/brave_vpn_service_factory.cc#L114-L115

That calls into Chromium code here:
https://source.chromium.org/chromium/chromium/src/+/main:components/keyed_service/content/browser_context_keyed_service_factory.cc;l=54-57;drc=12be03159fe22cd4ef291e9561762531c2589539

Seems last recorded call in stack is here:
https://source.chromium.org/chromium/chromium/src/+/main:components/keyed_service/core/keyed_service_factory.cc;l=69;drc=8a6d4b6a266bd766e44387a83b09df5a03eea32f
Error is `EXC_BAD_ACCESS / KERN_INVALID_ADDRESS`

## Steps to Reproduce

   1. Have mac with M2 Pro processor and macOS Sonoma
   2. Fresh profile - use Brave version `1.61.114` or `1.61.116` (others may crash too)
   3. Visit https://account.brave.com
   4. Put an email, hit enter (email and environment not related; repros on any email, in staging and prod)
   5. Copy the link from your email in the browser; paste into URL bar from step 3 and hit enter
   6. Browser crashes

## Actual result:
Crashes. Here are a few crash IDs
```
29280e00-46fb-540b-0000-000000000000
20280e00-46fb-540b-0000-000000000000
26280e00-46fb-540b-0000-000000000000
25280e00-46fb-540b-0000-000000000000
```

And here is one loaded in backtrace (loadable by Brave employees)
https://brave.sp.backtrace.io/p/brave/debug?filters=JTVCJTVCJTIyX3J4aWQlMjIlMkMlMjJlcXVhbCUyMiUyQyUyMjI5MjgwZTAwLTQ2ZmItNTQwYi0wMDAwLTAwMDAwMDAwMDAwMCUyMiU1RCU1RA%3D%3D&fingerprint=a7674ea25794ca9032868af27f09c2828ea69ccc6bd6da434beb126e1c48c905&debug=(%2265f4bdd%22,0,0)

```
[ 00 ] KeyedServiceFactory::GetServiceForContext(void*, bool) ( keyed_service_factory.cc:69 )
[ 01 ] BrowserContextKeyedServiceFactory::GetServiceForBrowserContext(content::BrowserContext*, bool) ( browser_context_keyed_service_factory.cc:57 )
[ 02 ] brave_vpn::BraveVpnServiceFactory::BindForContext(content::BrowserContext*, mojo::PendingReceiver<brave_vpn::mojom::ServiceHandler>) ( brave_vpn_service_factory.cc:115 )
[ 03 ] brave_vpn::BraveVpnServiceFactory::BindForContext(content::BrowserContext*, mojo::PendingReceiver<brave_vpn::mojom::ServiceHandler>) ( brave_vpn_service_factory.cc:115 )
[ 04 ] (anonymous namespace)::MaybeBindBraveVpnImpl(content::RenderFrameHost*, mojo::PendingReceiver<brave_vpn::mojom::ServiceHandler>) ( brave_content_browser_client.cc:455 )
[ 05 ] base::RepeatingCallback<void (content::RenderFrameHost*, mojo::PendingReceiver<side_panel::customize_chrome::mojom::WallpaperSearchHandler>)>::Run(content::RenderFrameHost*, mojo::PendingReceiver<side_panel::customize_chrome::mojom::WallpaperSearchHandler>) const & ( callback.h:337 )
[ 06 ] void mojo::internal::BinderContextTraits<content::RenderFrameHost*>::BindGenericReceiver<side_panel::customize_chrome::mojom::WallpaperSearchHandler>(base::RepeatingCallback<void (content::RenderFrameHost*, mojo::PendingReceiver<side_panel::customize_chrome::mojom::WallpaperSearchHandler>)> const&, content::RenderFrameHost*, mojo::ScopedHandleBase<mojo::MessagePipeHandle>) ( binder_map_internal.h:40 )
[ 07 ] void base::internal::FunctorTraits<void (*)(base::RepeatingCallback<void (content::RenderFrameHost*, mojo::PendingReceiver<image_annotation::mojom::Annotator>)> const&, content::RenderFrameHost*, mojo::ScopedHandleBase<mojo::MessagePipeHandle>), void>::Invoke<void (* const&)(base::RepeatingCallback<void (content::RenderFrameHost*, mojo::PendingReceiver<image_annotation::mojom::Annotator>)> const&, content::RenderFrameHost*, mojo::ScopedHandleBase<mojo::MessagePipeHandle>), base::RepeatingCallback<void (content::RenderFrameHost*, mojo::PendingReceiver<image_annotation::mojom::Annotator>)> const&, content::RenderFrameHost*, mojo::ScopedHandleBase<mojo::MessagePipeHandle>>(void (* const&)(base::RepeatingCallback<void (content::RenderFrameHost*, mojo::PendingReceiver<image_annotation::mojom::Annotator>)> const&, content::RenderFrameHost*, mojo::ScopedHandleBase<mojo::MessagePipeHandle>), base::RepeatingCallback<void (content::RenderFrameHost*, mojo::PendingReceiver<image_annotation::mojom::Annotator>)> const&, content::RenderFrameHost*&&, mojo::ScopedHandleBase<mojo::MessagePipeHandle>&&) ( bind_internal.h:631 )
[ 08 ] void base::internal::InvokeHelper<false, void, 0ul>::MakeItSo<void (* const&)(base::RepeatingCallback<void (content::RenderFrameHost*, mojo::PendingReceiver<image_annotation::mojom::Annotator>)> const&, content::RenderFrameHost*, mojo::ScopedHandleBase<mojo::MessagePipeHandle>), std::__Cr::tuple<base::RepeatingCallback<void (content::RenderFrameHost*, mojo::PendingReceiver<image_annotation::mojom::Annotator>)>> const&, content::RenderFrameHost*, mojo::ScopedHandleBase<mojo::MessagePipeHandle>>(void (* const&)(base::RepeatingCallback<void (content::RenderFrameHost*, mojo::PendingReceiver<image_annotation::mojom::Annotator>)> const&, content::RenderFrameHost*, mojo::ScopedHandleBase<mojo::MessagePipeHandle>), std::__Cr::tuple<base::RepeatingCallback<void (content::RenderFrameHost*, mojo::PendingReceiver<image_annotation::mojom::Annotator>)>> const&, content::RenderFrameHost*&&, mojo::ScopedHandleBase<mojo::MessagePipeHandle>&&) ( bind_internal.h:868 )
[ 09 ] void base::internal::Invoker<base::internal::BindState<void (*)(base::RepeatingCallback<void (content::RenderFrameHost*, mojo::PendingReceiver<image_annotation::mojom::Annotator>)> const&, content::RenderFrameHost*, mojo::ScopedHandleBase<mojo::MessagePipeHandle>), base::RepeatingCallback<void (content::RenderFrameHost*, mojo::PendingReceiver<image_annotation::mojom::Annotator>)>>, void (content::RenderFrameHost*, mojo::ScopedHandleBase<mojo::MessagePipeHandle>)>::RunImpl<void (* const&)(base::RepeatingCallback<void (content::RenderFrameHost*, mojo::PendingReceiver<image_annotation::mojom::Annotator>)> const&, content::RenderFrameHost*, mojo::ScopedHandleBase<mojo::MessagePipeHandle>), std::__Cr::tuple<base::RepeatingCallback<void (content::RenderFrameHost*, mojo::PendingReceiver<image_annotation::mojom::Annotator>)>> const&, 0ul>(void (* const&)(base::RepeatingCallback<void (content::RenderFrameHost*, mojo::PendingReceiver<image_annotation::mojom::Annotator>)> const&, content::RenderFrameHost*, mojo::ScopedHandleBase<mojo::MessagePipeHandle>), std::__Cr::tuple<base::RepeatingCallback<void (content::RenderFrameHost*, mojo::PendingReceiver<image_annotation::mojom::Annotator>)>> const&, std::__Cr::integer_sequence<unsigned long, 0ul>, content::RenderFrameHost*&&, mojo::ScopedHandleBase<mojo::MessagePipeHandle>&&) ( bind_internal.h:968 )
[ 10 ] base::internal::Invoker<base::internal::BindState<void (*)(base::RepeatingCallback<void (content::RenderFrameHost*, mojo::PendingReceiver<image_annotation::mojom::Annotator>)> const&, content::RenderFrameHost*, mojo::ScopedHandleBase<mojo::MessagePipeHandle>), base::RepeatingCallback<void (content::RenderFrameHost*, mojo::PendingReceiver<image_annotation::mojom::Annotator>)>>, void (content::RenderFrameHost*, mojo::ScopedHandleBase<mojo::MessagePipeHandle>)>::Run(base::internal::BindStateBase*, content::RenderFrameHost*, mojo::ScopedHandleBase<mojo::MessagePipeHandle>&&) ( bind_internal.h:932 )
[ 11 ] mojo::BinderMapWithContext<content::RenderFrameHost*>::TryBind(content::RenderFrameHost*, mojo::GenericPendingReceiver*) ( callback.h:337 )
[ 12 ] content::BrowserInterfaceBrokerImpl<content::RenderFrameHostImpl, content::RenderFrameHost*>::BindInterface(mojo::GenericPendingReceiver) ( browser_interface_broker_impl.h:88 )
[ 13 ] mojo::BinderMapWithContext<content::RenderFrameHost*>::TryBind(content::RenderFrameHost*, mojo::GenericPendingReceiver*) ( callback.h:337 )
[ 14 ] content::BrowserInterfaceBrokerImpl<content::RenderFrameHostImpl, content::RenderFrameHost*>::BindInterface(mojo::GenericPendingReceiver) ( browser_interface_broker_impl.h:88 )
[ 15 ] content::BrowserInterfaceBrokerImpl<content::RenderFrameHostImpl, content::RenderFrameHost*>::GetInterface(mojo::GenericPendingReceiver) ( browser_interface_broker_impl.h:60 )
[ 16 ] blink::mojom::BrowserInterfaceBrokerStubDispatch::Accept(blink::mojom::BrowserInterfaceBroker*, mojo::Message*) ( browser_interface_broker.mojom.cc:180 )
[ 17 ] mojo::internal::MultiplexRouter::ProcessIncomingMessage(mojo::internal::MultiplexRouter::MessageWrapper*, mojo::internal::MultiplexRouter::ClientCallBehavior, base::SequencedTaskRunner*) ( message_dispatcher.cc:48 )
[ 18 ] mojo::internal::MultiplexRouter::Accept(mojo::Message*) ( multiplex_router.cc:710 )
[ 19 ] mojo::internal::MultiplexRouter::ProcessIncomingMessage(mojo::internal::MultiplexRouter::MessageWrapper*, mojo::internal::MultiplexRouter::ClientCallBehavior, base::SequencedTaskRunner*) ( message_dispatcher.cc:48 )
[ 20 ] mojo::internal::MultiplexRouter::Accept(mojo::Message*) ( multiplex_router.cc:710 )
[ 21 ] mojo::MessageDispatcher::Accept(mojo::Message*) ( message_dispatcher.cc:43 )
[ 22 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*) ( callback.h:154 )
[ 23 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:326 )
[ 24 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:0 )
[ 25 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*) ( callback.h:154 )
[ 26 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:326 )
[ 27 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:0 )
[ 28 ] base::MessagePumpCFRunLoopBase::RunWork() ( message_pump_apple.mm:444 )
[ 29 ] invocation function for block in base::MessagePumpCFRunLoopBase::RunWorkSource(void*) ( message_pump_apple.mm:416 )
[ 30 ] base::apple::CallWithEHFrame(void () block_pointer)
[ 31 ] 0x1893c9cf8
```

## Expected result:
Not crashing

**Comment by bsclifton** [comment]
This is the bit of problematic code here:
https://github.com/brave/brave-core/blob/b4278ee85661ba2fa7ab7c43ff0c5b08b9f0917d/browser/brave_vpn/brave_vpn_service_factory.cc#L102-L104

We should be put build flags around the factory and remove the flag for VPN. I'll check that out!

**Comment by rebron** [comment]
Related? https://github.com/brave/brave-browser/issues/35396

**Comment by simonhong** [comment]
Investigating..

**Comment by simonhong** [comment]
> Related? #35396

Seems different issue. Both have different call stack.

**Comment by stephendonner** [comment]
Just as a datapoint, no crashes here using

```
Brave | 1.61.114 Chromium: 120.0.6099.199 (Official Build) (arm64)
-- | --
Revision | e0f6e091fe79c029231a86e8cdcc5fbe70bcddbe
OS | macOS Version 13.6.4 (Build 22G513)
```

(But it's an `M1`, not an `M2`, if that makes a difference.)

example | example | example
---------|----------|---------
<img width="1312" alt="Screenshot 2024-02-01 at 11 10 56 AM" src="https://github.com/brave/brave-browser/assets/387249/c1a2e97a-3c5e-4d32-8cb8-ea621c5fa15f"> | <img width="1312" alt="Screenshot 2024-02-01 at 11 10 58 AM" src="https://github.com/brave/brave-browser/assets/387249/5cf22402-7114-4c2e-9dcd-2fd93412caf5"> | <img width="1312" alt="Screenshot 2024-02-01 at 11 11 10 AM" src="https://github.com/brave/brave-browser/assets/387249/72dd22ad-5701-4be5-80ce-4f45324d4b5a">

**Comment by pavelbrm** [comment]
> Just as a datapoint, no crashes here using
> 
> ```
> Brave | 1.61.114 Chromium: 120.0.6099.199 (Official Build) (arm64)
> -- | --
> Revision | e0f6e091fe79c029231a86e8cdcc5fbe70bcddbe
> OS | macOS Version 13.6.4 (Build 22G513)
> ```
> 
> (But it's an `M1`, not an `M2`, if that makes a difference.)
> 
> example	example	example
> <img alt="Screenshot 2024-02-01 at 11 10 56 AM" width="1312" src="https://private-user-images.githubusercontent.com/387249/301619018-c1a2e97a-3c5e-4d32-8cb8-ea621c5fa15f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MzUwNzgsIm5iZiI6MTcwNjgzNDc3OCwicGF0aCI6Ii8zODcyNDkvMzAxNjE5MDE4LWMxYTJlOTdhLTNjNWUtNGQzMi04Y2I4LWVhNjIxYzVmYTE1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwMDQ2MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjRhZGIyNzFhNmEyMjIwYTE5YjU5NzNiNTkzM2IyNTdmMmZhZmZhZGI0ZTJlYjUxNDAyYmYxZjBjYzhhNGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JwE6UlQ1S-Zrn-K0y5KwmDAHlQGTyML7AeDjQX4vi6E">	<img alt="Screenshot 2024-02-01 at 11 10 58 AM" width="1312" src="https://private-user-images.githubusercontent.com/387249/301619026-5cf22402-7114-4c2e-9dcd-2fd93412caf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MzUwNzgsIm5iZiI6MTcwNjgzNDc3OCwicGF0aCI6Ii8zODcyNDkvMzAxNjE5MDI2LTVjZjIyNDAyLTcxMTQtNGMyZS05ZGNkLTJmZDkzNDEyY2FmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwMDQ2MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjllNjBhNTk2M2VmN2QxNWI4MjRiMjc1ZjU2NzdjOTMyN2Y4MjhmNDQxOGQwZmZlYTQyOTEwYWQ1M2FiODNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O_7HhJxA0mHkBpm-8Z0N_CYnbAeb1iFi4t7C_0ehJZE">	<img alt="Screenshot 2024-02-01 at 11 11 10 AM" width="1312" src="https://private-user-images.githubusercontent.com/387249/301619030-72dd22ad-5701-4be5-80ce-4f45324d4b5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MzUwNzgsIm5iZiI6MTcwNjgzNDc3OCwicGF0aCI6Ii8zODcyNDkvMzAxNjE5MDMwLTcyZGQyMmFkLTU3MDEtNGJlNS04MGNlLTRmNDUzMjRkNGI1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwMDQ2MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2I1ZDEyNDA5ZTQ1OTIxMDBmODZkZWQwZGZkZmEyYjY4MWIwY2ZiNzY4ODU3ZjE5NmY0OTg1MmM3YzMzZDJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PVjPNYDtKGS124d02Yn_v8qoE_ZTvXLDxR31Koqwezw">

Is the VPN flag on or off? It appears the crash was triggered with the flag off.

**Comment by stephendonner** [comment]
<snip>

> Is the VPN flag on or off? It appears the crash was triggered with the flag off.

It was off; thanks for the clarification/reminder.  I can now reproduce 100% using the same build:

example | example | example
----------|--------|----------
<img width="1312" alt="Screenshot 2024-02-01 at 5 39 51 PM" src="https://github.com/brave/brave-browser/assets/387249/b2b8be79-4026-4d13-b981-1a1d3d3ee417"> | <img width="1312" alt="Screenshot 2024-02-01 at 5 43 23 PM" src="https://github.com/brave/brave-browser/assets/387249/999e9ee0-b6db-4bf1-ae11-a6253d6ca1c4"> | <img width="1312" alt="Screenshot 2024-02-01 at 5 43 26 PM" src="https://github.com/brave/brave-browser/assets/387249/9e2f2d46-3e56-4ddc-b1dd-b62e3ed5f58b">

Crash ID is: `328e0300-dba3-700b-0000-000000000000`

**Comment by pavelbrm** [comment]
> I can now reproduce 100% using the same build, but with Brave VPN disabled via brave://flags

Yes, that's what I meant.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 


```
Brave | 1.64.47 Chromium: 121.0.6167.139 (Official Build) nightly (arm64)
-- | --
Revision | 5b6c78859ffd7e8695becfaf714ba9bd19e82bb1
OS | macOS Version 13.6.4 (Build 22G513)
```

### Steps:
1. installed `1.64.47`
2. launched Brave
3. disabled `Brave VPN` via `brave://flags`
4. loaded `account.brave.com`
5. entered `isssue35395@mailinator.com`

### Confirmed I could log in to `account.brave.com` while `Brave VPN` is disabled, without crashing

`brave://flags` | `logged in`
---------------|------------
<img width="1312" alt="Screenshot 2024-02-05 at 10 59 56 AM" src="https://github.com/brave/brave-browser/assets/387249/2c42599d-50b4-4d91-b724-39ea84ad3fc6"> | <img width="1312" alt="Screenshot 2024-02-05 at 11 00 49 AM" src="https://github.com/brave/brave-browser/assets/387249/7082d10e-b4ea-4202-a31b-9da15d29fbed">

**Comment by stephendonner** [comment]
## Verifed `PASSED` using 

```
Brave | 1.64.96 Chromium: 122.0.6261.111 (Official Build) beta (x86_64)
-- | --
Revision | fb9feca2d1f25ea20265752e8ecdf548a6925bd4
OS | macOS Version 11.7.10 (Build 20G1427)
```
### Steps:

1. installed `1.64.96`
2. launched Brave
3. disabled `Brave VPN` via `brave://flags`
4. loaded `account.brave.com`
5. entered `issue35395@mailinator.com`

## Confirmed I could log in to `account.brave.com` while `Brave VPN` is disabled, without crashing

example | example | example
---------|----------|---------
<img width="1504" alt="Screen Shot 2024-03-06 at 5 15 07 PM" src="https://github.com/brave/brave-browser/assets/387249/51c9bcd3-d4e6-472d-a892-5a0380e0adf5"> | <img width="1464" alt="Screen Shot 2024-03-06 at 5 16 42 PM" src="https://github.com/brave/brave-browser/assets/387249/52977972-c982-47bb-a7e4-06adc659219a"> | <img width="1464" alt="Screen Shot 2024-03-06 at 5 16 47 PM" src="https://github.com/brave/brave-browser/assets/387249/c20917c9-161b-4c3c-964d-1b5d63cf817f">
