### ISSUE TITLE
Leo AI causes Brave to crash

### ISSUE THREAD

**Issue by x7z7** [brave/brave-browser#35396]
## Description 

Using Leo AI seem to crash Brave randomly. I downloaded Brave after a long time and found Leo AI for the first time, but when I tried using it for the first time, it crashed. I reopened it, I tried asking some questions, all goes well. I switch to another tab (create other windows and private windows) and came back to the same tab to ask more questions to Leo AI, and then it crashed. It doesn't crash if I didn't use Leo AI.

## Steps to Reproduce

   1. Open a Wikipedia article on Brave.
   2. Open Leo AI (I tested it on `llama2:13b`). Ask some questions.
   3. Open another Wikipedia article in another tab, and repeat (2).
   4. Open a private window. Visit some website.
   5. Go back to first (non-private) tab and ask more questions to the AI from where you left off.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.61.120 Chromium: 120.0.6099.234 (Official Build) (arm64) 
Operating system: macOS 14.2.1
## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Leo AI errors out saying "there is network issue connecting to Leo"

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No (doesn't have Leo AI)

## Miscellaneous Information:
Here are crash IDs for the Beta and current release channels,
- **Beta**: `01420100-802f-5e0b-0000-000000000000`
- **Current release**: `353d0100-802f-5e0b-0000-000000000000`

**Comment by darkdh** [comment]
fingerprint 6a188376d08cff8aaa2d6497e67b72557b842bbfcc99a388590d57bb22554990

**Comment by kjozwiak** [comment]
@brave/qa-team there's also STR/Cases that @darkdh added via https://github.com/brave/brave-core/pull/21992#issue-2128077370. We should run through the cases on a few `macOS` machines as per https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1707930618833979?thread_ts=1707844618.355239&cid=CHGKGMHDJ.

**Comment by kjozwiak** [comment]
The above requires `1.63.155` or higher for `1.63.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (x86_64)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | macOS Version 14.4 (Build 23E5196e)
```

## First, confirmed the crash using `1.62.165` 
### (incident ID: `41e70200-bc19-830b-0000-000000000000`)


example | example | example | example | example
---------|----------|---------|----------|--------
<img width="1878" alt="Screenshot 2024-02-15 at 11 14 46 AM" src="https://github.com/brave/brave-browser/assets/387249/77d802eb-190a-4eb9-81f3-53448eec5c63"> | <img width="1878" alt="Screenshot 2024-02-15 at 11 15 07 AM" src="https://github.com/brave/brave-browser/assets/387249/7cfa81d4-b074-4614-af94-8e861d9ee6d4"> | <img width="1802" alt="Screenshot 2024-02-15 at 11 41 01 AM" src="https://github.com/brave/brave-browser/assets/387249/9d47a14e-5a84-465c-930a-2b46954c79b1"> | <img width="1802" alt="Screenshot 2024-02-15 at 11 42 15 AM" src="https://github.com/brave/brave-browser/assets/387249/bd232105-5b1a-448c-be24-45f66467510b"> | <img width="1878" alt="Screenshot 2024-02-15 at 1 51 22 PM" src="https://github.com/brave/brave-browser/assets/387249/93137a08-2a77-4ad7-9379-3a72a95b835d">
