### ISSUE TITLE
Vertical tab's search button is misaligned on startup

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#35398]
## Description 
When opening browser while vertical tabs are turned on, tab search button is right next to the expand/collapse button.

## Steps to Reproduce

   1. Turn on the vertical tabs and expand the vertical tabs
   2. Restart the browser
   3. check where the tab search button is

## Actual result:

![image](https://github.com/brave/brave-browser/assets/5474642/b88a2310-f147-43e3-9041-cddb5a8c20e0)

## Expected result:
Search button should be at the right side of vertical tab strip
<img width="258" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/39ece046-47c4-497d-9538-62696b8a99a5">

## Reproduces how often: 

Always

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.64.48 Chromium: 121.0.6167.139 (Official Build) nightly (x86_64)
-- | --
Revision | 741f7ee622bdfde5e10e3beda02288f3c056287e
OS | macOS Version 11.7.10 (Build 20G1427)
```

<img width="1178" alt="Screen Shot 2024-02-05 at 9 29 51 AM" src="https://github.com/brave/brave-browser/assets/387249/c63bf7e6-6bf3-4cdb-853c-23e91d0c81a2">

**Comment by kjozwiak** [comment]
Removing the `QA Pass` so the above can quickly be re-checked using `1.63.x` as the above was uplifted as per https://github.com/brave/brave-core/pull/21931#pullrequestreview-1868661801. Used the STR/Cases via https://github.com/brave/brave-browser/issues/35398#issuecomment-1927537362 as the verification needed for uplift.

The above requires `1.63.148` or higher for `1.63.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.63.148 Chromium: 121.0.6167.164 (Official Build) beta (arm64)
-- | --
Revision | c68893a5f2bbf2898967a976b21b3fe5d581f714
OS | macOS Version 13.5 (Build 22G74)
```



1. Installed 1.63.148
2. launched Brave
3. turned on the vertical tabs and kept in expanded mode 
4. restarted the browser


- Confirmed the tab search button is to the right of the tab strip


<img width="1195" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a539a74b-9552-4a61-b458-6ad55d34ba64">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.63.148 Chromium: 121.0.6167.164 (Official Build) beta (64-bit) 
Revision	c68893a5f2bbf2898967a976b21b3fe5d581f714
OS	Linux
```

- Reproduced the issue using 1.63.146 using STR from the description.
- Upgraded to 1.63.148 
- Confirmed the tab search button is to the right of the tab strip

1.63.146 | 1.63.148
---- | -----
![Screenshot from 2024-02-08 11-08-58](https://github.com/brave/brave-browser/assets/98358127/e1a1318c-44df-49ec-9caa-fb72c02bd0bf)|![image](https://github.com/brave/brave-browser/assets/98358127/5af77223-9311-486f-afb4-edf7f932cb6e)
