### ISSUE TITLE
SNS resolver should accept hosts like w.sol

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#35405]
https://bravesoftware.slack.com/archives/C02QSF68MGA/p1705506309360639
We have incorrect hostname validation pattern

**Comment by kjozwiak** [comment]
The above requires `1.62.151` or higher for `1.62.x` verification 👍 CCing @srirambv

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.62.151 Chromium: 121.0.6167.85 (Official Build) (64-bit)
-- | --
Revision | ebbd33e41da941bb33944e03c2a24df87cae4927
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from issue description
- Verified visiting `w.sol` auto-redirects to `https://twitter.com/wdotsol` when enabling SNS server on the interstitial page

https://github.com/brave/brave-browser/assets/17010094/7bd2dc32-ece6-41eb-b051-8258ca27104b

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 14` using the following build(s):

```
Brave | 1.62.152 Chromium: 121.0.6167.101 (Official Build) (64-bit)
--- | ---
Revision | 43e7bbb904a2fa762d73f3ac732effecba4c5362
OS | Android 14; Build/AP11.231215.007; 34; REL
```

* Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/35405#issue-2088020324, ensured that visiting `w.sol` auto-redirects to `https://twitter.com/wdotsol` when enabling SNS server on the interstitial page.

https://github.com/brave/brave-browser/assets/2602313/c84f503b-94e4-44df-93f0-62dbf1d46aab
