### ISSUE TITLE
verified creator icon on BAT logo cut off

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#35407]
## Description 

Verified creator icon on the BAT logo in URL bar is cut off on Beta but Nightly seems to be ok (Nightly has larger/taller address bar).

Reported by @AlanBreck via https://bravesoftware.slack.com/archives/CB0KCRCQN/p1705532998948359.

## Steps to Reproduce

   1. Using 1.62.x, join rewards
   2. Navigate to a verified creator
   3. Look at BAT icon in URL bar

## Actual result:

<img width="90" alt="beta" src="https://github.com/brave/brave-browser/assets/28145373/408822cf-f8f7-464e-a648-5b07f215a677">

## Expected result:

Verified creator icon should not be cut off.

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.62.145 Chromium: 120.0.6099.234 (Official Build) beta (x86_64)
-- | --
Revision | 431a4319968af133d1c7792ad66437061f95dd83
OS | macOS Version 13.6.3 (Build 22G436)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? 1.62.x yes
- Can you reproduce this issue with the nightly channel? No (1.63.x)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @brave/qa-team

**Comment by zenparsing** [comment]
Fixed by https://github.com/brave/brave-core/pull/21616

**Comment by kjozwiak** [comment]
The above requires `1.62.147` or higher for `1.62.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.62.147 Chromium: 120.0.6099.234 (Official Build) (x86_64)
-- | --
Revision | 3b25c3743150a54485dea24f0ceb1e69d6db51bc
OS | macOS Version 13.6.3 (Build 22G436)
```
