### ISSUE TITLE
Horizontal layout new tab button misaligned

### ISSUE THREAD

**Issue by dpthegrey** [brave/brave-browser#35401]
## Description 

Horizontal layout new tab button misaligned

## Actual result:

![image](https://github.com/brave/brave-browser/assets/49444980/0fdb76a6-31d0-4314-8c6a-7696695a10b9)
![image](https://github.com/brave/brave-browser/assets/49444980/d0eb7acd-ea02-49c5-b872-26e4ab79f13f)

## Brave version (brave://version info)

1.63.124 Chromium: 121.0.6167.57 (Official Build) nightly (x86_64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? not tried
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

**Comment by dpthegrey** [comment]
cc: @sangwoo108

**Comment by simonhong** [comment]
Duplicated with https://github.com/brave/brave-browser/issues/35300
