### ISSUE TITLE
Fix mocked implementation loading for Brave Wallet and Brave Rewards proxies

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#35408]
## Description 

Adjust the build process for storybook and unit tests to replace imports of the Brave Wallet and Brave Rewards proxies with their mocked implementation. This will fix an issue where unit tests could not override state of the proxies and an issue where proxy state was shared between tests. This also simplifies test and storybook logic, as they will not need to import specific mock implementations, as the compiler will replace the production implementation with the mocks at build-time.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.105 Chromium: 123.0.6312.46 (Official Build) (64-bit)
-- | --
Revision | f0e46384b4e277529e9123c93370e113c547e206
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from [brave/brave-core#21618](https://github.com/brave/brave-core/pull/21618)
- Verified wallet works as expected
