### ISSUE TITLE
Auto Contribution fails to complete

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#35418]
## Description 

Tried with various versions (1.61.x, 1.63.x and @MadhaviSeelam tried with 1.64.x), and Auto Contribution starts to process but ultimately fails (it runs out of retries but I can't tell why it's failing in the logs).

## Steps to Reproduce

   1. Launch with staging flags (ex. `--args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=9,"*/brave_rewards/*"=9,"*/bat-native-ads/*"=9,"*/bat-native-confirmations/*"=9,"*/brave_ads/*"=9,"*/brave_user_model/*"=9 --rewards=debug=true,staging=true,reconcile-interval=3` which will trigger AC 3 minutes after joining rewards)
   2. Connect custodian (Uphold or Gemini)
   3. Visit at least one site to populate AC list
   4. Wait for AC to trigger and process

## Actual result:

BAT is removed from custodial account, but stops retrying, seems like invalid JSON is returned:

```
[24698:259:0118/133645.577551:INFO:get_credentials.cc(66)] Invalid JSON
[24698:259:0118/133645.577957:INFO:credentials_sku.cc(279)] Couldn't fetch credentials: RETRY
[24698:259:0118/133645.578359:INFO:contribution_sku.cc(174)] Order not completed
[24698:259:0118/133645.579852:VERBOSE1:contribution.cc(781)] Timer for contribution retry 
```

<img width="498" alt="Screenshot 2024-01-18 at 1 50 02 PM" src="https://github.com/brave/brave-browser/assets/28145373/4d69d93c-b82e-4f93-ae18-618f23ce12b9">

## Expected result:

AC completes successfully

## Reproduces how often: 

easily

## Brave version (brave://version info)

 1.61.x, 1.63.x, 1.64.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @brave/qa-team

**Comment by LaurenWags** [comment]
See https://bravesoftware.slack.com/archives/CNH9Q6REV/p1705603775608769 for discussion

**Comment by Miyayes** [comment]
This was a server-side issue. This was resolved with a server-side change. @zenparsing verified issue.
