### ISSUE TITLE
C121 - hide "Open in Reading Mode" context menu option

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#35411]
## Description 

In C121 there seems to be a new context menu option "Open in Reading Mode". Per https://bravesoftware.slack.com/archives/CU5UXM3EC/p1705594176394119?thread_ts=1705010635.151729&cid=CU5UXM3EC it should be hidden.

## Steps to Reproduce

   1. Using C121 version, open NTP
   2. Right click on NTP background
   3. See option in context menu.
   4. I also managed to reproduce it by enabling Brave News and after right clicking on a couple cards (large ones with images), I got this option there also.

## Actual result:

Step 3 | Step 4
--- | ---
<img width="271" alt="Screenshot 2024-01-18 at 11 05 23 AM" src="https://github.com/brave/brave-browser/assets/28145373/c625185d-ec72-4a60-a0a2-9e0e5b1c74a4"> | <img width="580" alt="Screenshot 2024-01-18 at 11 13 22 AM" src="https://github.com/brave/brave-browser/assets/28145373/2ebcbed6-3357-40f6-878e-b4625c851c27">

## Expected result:

Option should not be displayed in context menu

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.63.124 Chromium: 121.0.6167.57 (Official Build) nightly (x86_64)
-- | --
Revision | e0864ffae4be8015ad75c2b344ab75c2eefb31a7
OS | macOS Version 13.6.3 (Build 22G436)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? no 1.61.x
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? yes 1.63.x with C121

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron

**Comment by kjozwiak** [comment]
The above requires `1.62.148` or higher for `1.62.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.62.149 Chromium: 121.0.6167.75 (Official Build) (64-bit)
-- | --
Revision | ff84587bd70af9fcbcbe59fc5194ca65082759c4
OS | Windows 11 Version 22H2 (Build 22621.3007)
```

1. Installed 1.62.149
2. launched Brave
3. Right clicked on NTP background
4. enabled Brave News Feed Update in the `brave://flags`
5. enabled Brave news via `Turn on Brave News` in a new tab page

#### Confirmed `Open in Reading Mode` option in the context menu is no longer shown for NTP background
#### Confirmed `Open in Reading Mode` option is no longer shown in the context menu for a hero card

NTP | Brave News card
---- | -----
<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c9a5ea1e-ca17-49cd-b947-c847904da170">|<img width="947" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/4bc73475-1f1d-4768-995f-32701dace774">
