### ISSUE TITLE
CR121 - Cookies settings are not in sync between  `brave://settings/cookies` and `brave://settings/shields` settings pages

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#35415]
## Description 

Cookies settings are not in sync between  `brave://settings/cookies` and `brave://settings/shields` settings pages

## Steps to Reproduce

Case 1:

   1. Clean profile 1.63.24 CR121 build
   2. Open brave://settings/cookies
   3. Change the cookies settings to "Allow third-party cookies"
   4. Confirm that "Allow third-party cookies" option is selected
   5. Open brave://settings/shields
   6. Look for cookies shield setting 
   7. Cookies settings are set to "Only cross-sites" instead of "Disable"
   8. Both setting pages are NOT insync
   
Case 2:
  1. Clean profile 1.63.24 CR121 build
  2. Open brave://settings/shields
  3. Change the cookies settings to "Disable"
  4. Open brave://settings/cookies
  5. Cookies settings are still showing up "Block 3rd party cookies" settings selected instead of "Allow third-party cookies"
  6. Both setting pages are NOT in sync

## Actual result:

Cookies settings are not in sync between  `brave://settings/cookies` and `brave://settings/shields` settings pages

## Expected result:

Cookies settings should be insync between  `brave://settings/cookies` and `brave://settings/shields` settings pages
## Reproduces how often: 

100%
## Brave version (brave://version info)

Brave | 1.63.124 Chromium: 121.0.6167.57 (Official Build) nightly (64-bit)
-- | --
Revision | e0864ffae4be8015ad75c2b344ab75c2eefb31a7
OS | Windows 10 Version 22H2 (Build 19045.3930)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @rebron @mkarolin @bridiver @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.62.156` or higher for `1.62.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.62.156 Chromium: 121.0.6167.139 (Official Build) (64-bit)
-- | --
Revision | 800674fc2c6162087525ed9b5bfc07230296b27d
OS | Windows 10 Version 22H2 (Build 19045.3930)
```
### Toggle cookies settings via brave://settings/cookies

<details>
<summary>Case 1: Block third-party cookies_PASSED</summary>

1. Clean profile 1.62.x
2. Open brave://settings/cookies
3. Confirm that the `Block third-party cookies` radio button is selected by default
4. Open brave://settings/shields
5. Confirm that the `Only cross-stite` cookies setting are populated by default in the `Block cookies` shields dropdown
6. Open a site cnn.com in a NTP
7. Click on `View site information` icon in the URL bar
8. Click on `Cookies and site data`
9. Confirmed that 3rd party cookies are blocked on the site 
10. Confirmed that `no of sites allowed` is shown on the cookies and site data modal

step 3 | step 5 | step 9
-------|--------|--------
![image](https://github.com/brave/brave-browser/assets/38657976/fa54cbef-1c75-46c5-ad48-07aac6b961db) | ![image](https://github.com/brave/brave-browser/assets/38657976/69c06347-c46e-42b0-94c0-09c8ece84e35) | ![image](https://github.com/brave/brave-browser/assets/38657976/d85d27de-de5b-4dd8-806a-8178d81239e1)

</details>

<details>
<summary>Case 2: Allow third-party cookies_PASSED</summary>

1. Continuation of case 1
2. Go to brave://settings/cookies
3. Change the cookies settings by selecting `Allow third-party cookies` radio button
4. Go to brave://settings/shields
5. Confirm that the `Disabled` cookies setting is populated in the `Block cookies` shields dropdown
6. Reload the site cnn.com which is opened via case 1 
7. Click on `View site information` icon in the URL bar 
8. Confirm that no of cookies allowed on the site as expected


step 3 | step 5 | step 8
-------|--------|--------
![image](https://github.com/brave/brave-browser/assets/38657976/f0df3bec-ad57-48e3-abee-09597c56983e) | ![image](https://github.com/brave/brave-browser/assets/38657976/5af53221-861b-441a-b8b6-bf4b3196c4e0) | ![image](https://github.com/brave/brave-browser/assets/38657976/e4d85b6e-5067-4ab6-882f-b75e2bf6b624)

</details>


### Toggle cookies settings via brave://settings/shields

<details>
<summary>Case 1: Only cross-site_PASSED</summary>

1. Clean profile 1.62.x
2. Open brave://settings/shields
3. Confirmed that `Only cross-site` cookies settings is selected by default in the `Block cookies` shields dropdown
4. Go to brave://settings/cookies
5. Confirm that the `Block third-party cookies` radio button is selected by default
6. Open a site buzzfeed.com in a NTP
7. Click on `View site information` icon in the URL bar
8. Click on `Cookies and site data`
9. Confirmed that 3rd party cookies are blocked on the site 
10. Confirmed that `no of sites allowed` is shown on the cookies and site data modal

step 3 | step 5 | step 9,10
-------|---------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/099d293c-632a-43ec-86d5-7a77f636765a) | ![image](https://github.com/brave/brave-browser/assets/38657976/918c4baf-61bc-4335-a687-583e489acb32) | ![image](https://github.com/brave/brave-browser/assets/38657976/d49450a8-b7f0-42ef-b3cd-1d9413417476)

</details>

<details>
<summary>Case 2: Disabled_PASSED</summary>

1. Continuation of case 1
2. Go to brave://settings/shields
3. Change the cookies settings to `Disabled` via `Block cookies` shield settings
4. Go to brave://settings/cookies
5. Confirmed that `Allow thrid-party cookies` settings is selected
6. Reload the site buzzfeed.com which is opened in case 1
7. Click on `View site information` icon in the URL bar
8. Click on `Cookies and site data`
9. Confirm that no. of cookies allowed are shown on the cookies and site data modal

step 3 | step 5 | step 9
--------|--------|-------
![image](https://github.com/brave/brave-browser/assets/38657976/d0c8c8cc-8ec9-4db0-a7e8-3d6cc1d1a602) | ![image](https://github.com/brave/brave-browser/assets/38657976/01a45ece-faa5-4e86-8811-280b84e3cfd7) | ![image](https://github.com/brave/brave-browser/assets/38657976/e1dccde8-024e-498a-8c18-801fd1541150)

</details>

<details>
<summary>Case 3: All_PASSED</summary>

1. Continuation of case 2
2. Go to brave://settings/shields
3. Change the cookies settings to block `All` via `Block cookies` shield settings
4. Go to brave://settings/cookies
5. Confirmed that `Block third-party cookies` and `Allow thrid-party cookies` settings are unchanged and both the settings are in non selectable state as there is no block all cookies settings in brave://settings/cookies now
6. Reload the site buzzfeed.com which is opened in case 2
7. Click on `View site information` icon in the URL bar
8. Click on `Cookies and site data`
9. Confirmed that no cookies are allowed, all the cookies are blocked as block all cookies settings is selected via brave://settings/shields

step 3 | step 5 | step 9
-------|--------|--------
![image](https://github.com/brave/brave-browser/assets/38657976/9c53701f-b955-4b67-92fc-573a13c889c1) | ![image](https://github.com/brave/brave-browser/assets/38657976/4b549147-8fbe-45d4-812c-88c88a06bce5) | ![image](https://github.com/brave/brave-browser/assets/38657976/f157f622-8f9f-4923-86a0-485630dcecde)

</details>
