### ISSUE TITLE
Display an error when fees a for pending transaction cannot be estimated

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#35413]
## Description 

We currently do not display anything when transaction fees fail to load. We should warn the user when this happens

## Steps to Reproduce

   1. Initiate a solana transaction via a Dapp (https://publishers.basicattentiontoken.org/c/juKB9bpi3m)
   2. review the pending transaction

## Actual result:

An error is not shown when the fee estimates fail to load

## Expected result:
An error should be shown if the fee estimates fail to load

## Reproduces how often: 

Intermittent issue

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.62.148` or higher for `1.62.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.62.149 Chromium: 121.0.6167.75 (Official Build) (64-bit)
-- | --
Revision | ff84587bd70af9fcbcbe59fc5194ca65082759c4
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from issue description
- Verified error message is shown when fee estimates fail

https://github.com/brave/brave-browser/assets/17010094/4bd507cd-cb07-4f97-afae-e40f29fd3f80
