### ISSUE TITLE
Should order publisher feeds by most-recent first, oldest last

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#35412]
## Description 

Should order publisher feeds by most-recent first, oldest last

## Steps to Reproduce

1. install `1.64.1`
2. launch Brave
3. open a new-tab page
4. scroll down
5. click on `Turn on Brave News`
6. load `https://rss.com/blog/`
7. click on `Manage Subscriptions` in the URL bar
8. subscribe to the feed
9. open a new-tab page
10. click on the `RSS.com Blog` feed in the sidebar filter
11. scroll down, looking at the published dates

## Actual result:

Dates jump around and are not even close to sequential

<img width="1312" alt="Screen Shot 2024-01-18 at 8 15 39 AM" src="https://github.com/brave/brave-browser/assets/387249/3960a498-a511-4d13-98f8-9da3bd596670">

## Expected result:

We should order them at least by published date, most-recent first

<img width="1312" alt="Screen Shot 2024-01-18 at 8 27 22 AM" src="https://github.com/brave/brave-browser/assets/387249/9cca8c19-3ebd-4249-a449-588b935c004f">

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.64.1 Chromium: 121.0.6167.57 (Official Build) nightly (x86_64)
-- | --
Revision | 61325d30e0600469aca14650b33369615f601652
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes!`
- Can you reproduce this issue with the nightly channel? `Yes!`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @fallaciousreasoning @LorenzoMinto @brave/qa-team @rebron

**Comment by stephendonner** [comment]
This also happens easily with the default `Top Sources` feed of different sources

<img width="1312" alt="Screen Shot 2024-01-18 at 8 32 02 AM" src="https://github.com/brave/brave-browser/assets/387249/17235111-7a5e-49d6-9bc5-a7e4bce2d496">

**Comment by stephendonner** [comment]
And with our very own `Brave Blog` feed: `https://brave.com/blog/`

<img width="1312" alt="Screen Shot 2024-01-19 at 6 37 34 PM" src="https://github.com/brave/brave-browser/assets/387249/28098a5f-0d82-458e-aaba-a189a93a4a62">

```
Brave | 1.64.6 Chromium: 121.0.6167.75 (Official Build) nightly (x86_64)
-- | --
Revision | a5446236342885c92184f41597b3c37296a1887c
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by fallaciousreasoning** [comment]
From what I remember, we don't want to sort by most recent for Channel or the Following feed, right @LorenzoMinto? Only the publishers?

I have a fix for this, but I don't know if we want to uplift it to 1.62.x or not - it's getting pretty late in the release cycle, and I don't know how many people are going to be using the Publisher feeds right off the bat. Might be fine to just slip into 1.63?

**Comment by LorenzoMinto** [comment]
Correct. We only want to chronologically order Publishers' feeds (both RSS and Brave News). 

I would expect publisher feeds to be a popular feature, but ordering really becomes sensitive when the feeds serve long standing content, which some RSS feeds do. It shouldn't affect the main Brave News publishers as much as for most of them content is a week old maximum. 

If the fix is minimal (there is very little risk of it causing unexpected errors) then I'd say we could uplift. If it was not trivial then 1.63 is fine.

**Comment by kjozwiak** [comment]
The above requires `1.62.155` or higher for `1.62.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.62.155 Chromium: 121.0.6167.85 (Official Build) (x86_64)
-- | --
Revision | 91c989228daf153ef41bd965f268fabc7b9dbbf0
OS | macOS Version 11.7.10 (Build 20G1427)
```


### Steps:
1. installed `1.62.55`
2. launched Brave
3. opened a new-tab page
4. scrolled down
5. clicked on `Turn on Brave News`
6. loaded `brave.com`
7. clicked on the `Manage Subscriptions` RSS-feed icon
8. clicked on `Subscribe`
9. opened Brave News
10. selected the Brave Blog from the sidebar filter
11. scrolled down
12. noted the timestamps/date offsets

### Confirmed publisher feeds are ordered from most recent first to latest, last

(In the below example, `18 hours`, `6 days`, `9 days` , `13 days` ago)

example | example
---------|---------
<img width="1456" alt="Screen Shot 2024-01-30 at 10 00 44 AM" src="https://github.com/brave/brave-browser/assets/387249/45a2696e-8aea-4a86-b3af-2aa7559e1c17"> | <img width="1456" alt="Screen Shot 2024-01-30 at 10 01 06 AM" src="https://github.com/brave/brave-browser/assets/387249/9965f0a7-8b29-4c58-bef4-89a6014676bb">
