### ISSUE TITLE
adjust color of checkmark on verified icon in URL bar for Rewards

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#35423]
## Description 

Follow up to https://github.com/brave/brave-browser/issues/35407

Verified icon placement on BAT logo was updated, but the checkmark on the logo isn't entirely white as it should be.

## Steps to Reproduce

   1. Have rewards enabled
   2. Navigate to a verified creator
   3. Look at BAT logo in URL bar
   4. Check both light and dark modes to ensure this icon looks correct

## Actual result:

<img width="113" alt="1 64 3" src="https://github.com/brave/brave-browser/assets/28145373/35cf53dd-0a76-49fa-9498-898b237be0b0">

## Expected result:

Checkmark on the verified icon should be white

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.64.3 Chromium: 121.0.6167.57 (Official Build) nightly (x86_64)
-- | --
Revision | 0ecd8a5470d06ce96921cb7585ecbc0f9878f3cf
OS | macOS Version 13.6.3 (Build 22G436)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes 1.64.3

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @zenparsing

**Comment by kjozwiak** [comment]
Labelling the above as `release/blocking` do we don't forget to uplift https://github.com/brave/brave-core/pull/21635 into `1.62.x`.

**Comment by kjozwiak** [comment]
The above requires `1.62.148` or higher for `1.62.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.62.149 Chromium: 121.0.6167.75 (Official Build) (64-bit)
-- | --
Revision | ff84587bd70af9fcbcbe59fc5194ca65082759c4
OS | Windows 10 Version 22H2 (Build 19045.3930)

```

Light theme | Dark theme
--------------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/8e5da7bf-9a0d-4447-a3f4-676551fe234c) | ![image](https://github.com/brave/brave-browser/assets/38657976/76334b92-e8ec-4064-afc1-deb79cbcfaa8)
