### ISSUE TITLE
`Block Fingerprinting` toggle switch in the global settings is affected when updating the same setting on a specific website via `Brave Shields`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#35428]
## Description 

`Block Fingerprinting` toggle switch in the global settings is affected when updating the same setting on a specific website via `Brave Shields`.

## Steps to reproduce 

   1. Install and Launch Brave `1.63.x` which has updated `Block Fingerprinting` setting with the `toggle switch` instead of `allow, standard, strict` options
   2. Go to any website > Brave Shields > Advanced controls
   3. Disable `Block Fingerprintin` (or enable if it was disabled already)
   4. Three-dot menu > Settings > Brave Shields & privacy
   5. Find the `Block Fingerprinting` toggle switch > Observe it got disabled (or enabled)

## Actual result 

`Block Fingerprinting` toggle switch in the global settings is affected when updating the same setting on a specific website via `Brave Shields`. When `Block Fingerprinting` setting had `allow, standard, strict` options in the previous builds, the global setting wasn't overridden.

https://github.com/brave/brave-browser/assets/128532965/c777adb5-c5f3-452b-9717-ec6db555dbf8

## Expected result

When a user is updating any setting including `Block Fingerprinting` via `Brave Shields` on a specific website, the global setting for the same switch must not be overridden.

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NO
- Can you reproduce this issue with the current Play Store Beta version? YES, when `brave://flags#brave-show-strict-fingerprinting-mode` is `Disabled`
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 7 (phone)
   - Android version: Android 14
   
## Brave version

```
Brave build: 1.62.146
Chromium: 120.0.6099.234 (Official Build) beta (64-bit) 
```
and
```
Brave build: 1.63.124
Chromium: 121.0.6167.57 (Official Build) canary (64-bit) 
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by MadhaviSeelam** [comment]
@arthuredelstein @hffvld Couldn't reproduce the issue in Desktop - `Win 11 x64`. Working as expected.

Switched from `Block fingerprinting` to `Allow fingerprinting` in the per-site Shields settings
global settings show default `Standard` setting

example | example 
---- | ----
<img width="332" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/4d32b751-074a-44ff-ad07-577048a98b0f">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e5e7c3e1-a7d9-4d67-9755-1f501867ecb2">

**Comment by GeetaSarvadnya** [comment]
Not reproducible on Windows 10 x64 - The global `Block fingerprint` settings toggle is NOT affected when a fingerprint toggle is enabled/ disabled via a site

**Comment by kjozwiak** [comment]
The above requires `1.63.134` or higher for `1.63.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP11.231215.007 release-keys
Brave build: 1.63.141
Chromium: 121.0.6167.139 (Official Build) beta (64-bit) 
```
---------------------------

<details>
<summary> Fresh profile </summary>

**STEPS:**
   1. Install and Launch Brave
   2. Go to any website > Brave Shields > Advanced controls
   3. Disable `Block Fingerprinting` (or enable if it was disabled already)
   4. Three-dot menu > Settings > Brave Shields & privacy
   5. Find the `Block Fingerprinting` toggle switch > Verify

**ACTUAL RESULTS:**
- Verified that `Block Fingerprinting` is not affected in the global settings when changing it for the specific website via `Brave Shields`
- Verified if changing `Block Fingerprinting` in the global settings, then it also changed on the website without a custom settings

---------------------------

https://github.com/brave/brave-browser/assets/128532965/212e9c5e-2de5-4281-b350-26a163c47fb8
</details>

<details>
<summary> Upgraded profile </summary>

**STEPS:**
   1. Install and Launch Brave `1.62.x`
   2. Go to any website > Brave Shields > Advanced controls
   3. Block Fingerprinting > Allow all fingerprinting > Done
   4. Three-dot menu > Settings > Brave Shields & privacy
   5. Block Fingerprinting > Confirm that the `Standard` option is still selected
   6. Upgrade Brave to `1.63.141` and launch it
   7. Go to `brave://flags` > Find `Show strict fingerprinting mode` > Disable it
   8. Go to any website > Brave Shields > Advanced controls
   9.  Block Fingerprinting > Disable it
   10. Three-dot menu > Settings > Brave Shields & privacy
   11. Find `Block Fingerprinting` toggle switch > Verify, it still enabled
   12. Now disable `Block Fingerprinting` toggle switch in the global settings
   13. Go to another website > Brave Shields > Advanced controls > Block Fingerprinting > Verify, it got disabled as well

**ACTUAL RESULTS:**
- Verified that `Block Fingerprinting` is not affected in the global settings when changing it for the specific website via `Brave Shields`
- Verified if changing `Block Fingerprinting` in the global settings, then it also changed on the website without a custom settings

---------------------------

https://github.com/brave/brave-browser/assets/128532965/96227f23-73a8-4cb5-8a99-ce42d52c9661
</details>
