### ISSUE TITLE
Collapsing a Bitcoin Account Collapses All Accounts

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35425]
## Description 

Collapsing 1 `Bitcoin Account` on the `Portfolio` screen will collapse all accounts

## Steps to Reproduce

   1. Create multiple `Bitcoin Testnet Accounts` and fund them with a `Bitcoin Testnet Faucet`
   2. Go to the `Portfolio` tab and sort by `Account`
   3. Collapse one of your `Bitcoin Accounts`
   4. The others will also `Collapse`

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/3c4bd794-4415-471d-b3a2-e6e7d411325d

## Expected result:
Should only collapse the account you were collapsing

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.63.138` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.153 Chromium: 121.0.6167.164 (Official Build) beta (64-bit)
-- | --
Revision | ef6dd148841564e2c5d9110bed5d6b7aad780525
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21692](https://github.com/brave/brave-core/pull/21692)
- Verified filtering by account and collapsing Bitcoin accounts doesn't collapse or expand other accounts
- Verified selecting/deselecting one Bitcoin account doesn't select/deselect all other Bitcoin accounts

Account Selection | Account Filtering
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/5ad82aca-4e6e-4ac4-a7a8-467a934d8308> | <video src=>https://github.com/brave/brave-browser/assets/17010094/8b9eff38-943d-414d-9594-e1409b7b1395>
