### ISSUE TITLE
NTP on narrow windows doesn't scroll vertically anymore

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#35427]
Without News V2 flag (or in 1.61.x), you can vertically scroll the NTP dashboard before News takes over. Can't do that anymore.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave	1.65.88 Chromium: 123.0.6312.58 (Official Build) beta (x86_64) 
Revision	e260e641e7db9e88b9b51112f4f00febf5a2f5eb
OS	macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.65.88`
2. launched Brave
3. opened a new-tab page
4.
