### ISSUE TITLE
Bitcoin Accounts are empty in Address Book

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35426]
## Description 

Bitcoin Accounts are not being generated in the `Send` screen address book

## Steps to Reproduce

   1. Create multiple `Bitcoin Testnet Accounts`
   2. Fund one of you accounts with a `Bitcoin Testnet Faucet`
   3. Go to the `Send` screen and try to send to another account in the address book
   4. The Address book will be empty

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/eef28144-5a06-4b7b-8c20-40344c6c4cbf

## Expected result:
Should display your other available `Bitcoin Accounts` to send to.

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.63.138` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.153 Chromium: 121.0.6167.164 (Official Build) beta (64-bit)
-- | --
Revision | ef6dd148841564e2c5d9110bed5d6b7aad780525
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21710](https://github.com/brave/brave-core/pull/21710)
- Verified Bitcoin address from different accounts are shown in Send screen

https://github.com/brave/brave-browser/assets/17010094/38de4718-8274-4a49-b0af-c6a8936cf942
