### ISSUE TITLE
"+Add current tab" button doesn't work to add tab to reading list

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#35421]
## Description 

Sometimes the "+ Add current tab" button on the reading list doesn't activate to add current tab to the reading list.

Switching to a different tab and then coming back makes it activate and it can then be selected.

## Steps to Reproduce

   1. Launch C121 version (1.63.x or 1.64.x)
   2. Navigate to a site and open the reading list
   3. Click on the "+Add current tab" button at the bottom of the reading list
   4. Button won't be active and you can't click it
   5. Switch to a different tab and then navigate back
   6. Now button is active and can be clicked

## Actual result:

step 4 where button can't be clicked:

<img width="1190" alt="Screenshot 2024-01-18 at 3 03 39 PM" src="https://github.com/brave/brave-browser/assets/28145373/33125022-5cc6-4bb3-85f4-c6c34e87099c">

## Expected result:
button should always be like step 6, clickable:

<img width="1189" alt="Screenshot 2024-01-18 at 3 04 21 PM" src="https://github.com/brave/brave-browser/assets/28145373/af7223d0-bb4f-4f83-b3eb-15aab11578e5">

## Reproduces how often: 

seems to be easy to reproduce if you try just after launching, but if you try after you've been navigating around in the browser for a bit it doesn't necessarily happen

## Brave version (brave://version info)

```
Brave | 1.63.126 Chromium: 121.0.6167.57 (Official Build) beta (x86_64)
-- | --
Revision | 37cf1e839670a842970254b61cdd4ef63307c8f1
OS | macOS Version 13.6.3 (Build 22G436)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? 1.64.x with C121 yes (@kjozwiak reproduced)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron

**Comment by simonhong** [comment]
Bookmarks panel also has same issue

**Comment by simonhong** [comment]
Reported to upstream - https://bugs.chromium.org/p/chromium/issues/detail?id=1521177

**Comment by simonhong** [comment]
Bookmarks panel and reading list panel shows different behavior.
Filed separated issue for bookmarks panel - https://github.com/brave/brave-browser/issues/35563

**Comment by simonhong** [comment]
Can't repro this readling list issue on chrome.

**Comment by simonhong** [comment]
Updated this issue's title as I can repro this stable/beta/nightly on macOS.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (x86_64)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | macOS Version 13.6.4 (Build 22G513)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.64.94 Chromium: 122.0.6261.94 (Official Build) beta (arm64)
-- | --
Revision | 866e3a4bd76c9cc1762928df0cf9a53b8685ab71
OS | macOS Version 14.4 (Build 23E5191e)
```
