### ISSUE TITLE
Enable BTC by default on desktop

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#35433]

**Comment by kjozwiak** [comment]
The above requires `1.63.132` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.141 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | aa92f6cecec7f6c576bd1cf120f4cf359d770159
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from issue title
- Verified Bitcoin option is available during onboarding
- Verified Bitcoin account is created if selected during onboarding
- Verified Bitcoin account can be created on both Mainnet and Testnet 
- Verified selecting Bitcoin from Buy screen prompts to create account if not already created during onboarding
- Verified restoring wallet doesn't restore Bitcoin account if skipped during onboarding
- Verified restoring wallet restores Bitcoin account if selected during onboarding

New Wallet | Restore Wallet
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/46b1cae9-525b-46d4-a628-3879cf27a80e> | <video src=https://github.com/brave/brave-browser/assets/17010094/4ceadee2-ae53-42d8-b3a6-3a8e094abf2e>
