### ISSUE TITLE
Add additional News P3A metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#35434]
Add five metrics for News:

If you have used Brave News in the last week and clicked on at least one card, how many cards did you click on? (reported weekly, desktop & Android)
`Brave.Today.WeeklyTotalCardClicks`

0. 1-2
1. 3-5
2. 6 -10
3. 11-15
4. 16-20
5. 21-25
6. 26+

If you have clicked on 5 or more cards in the last week, what is the average rank (depth) of the cards you clicked on in the For You/Following feeds? (reported weekly, desktop & Android)
`Brave.Today.ClickCardDepth`

0. 1-3 cards deep
1. 4 to 6 cards deep
2. 7 to 10 cards deep
3. 11 to 15 cards deep
4. 16 to 20 cards deep
5. 21+

If you are a monthly active user, how many channels are you subscribed to? (reported monthly, desktop & Android only)
`Brave.Today.ChannelCount`

0. 0-1
1. 2-4
2. 5-7
3. 8-10
4. 11+

If you are a monthly active user, how many publishers are you subscribed to (excluding direct feeds)? (reported monthly, desktop & Android only)
`Brave.Today.PublisherCount`

0. 0-1
1. 2-4
2. 5-7
3. 8-10
4. 11+

If you have used Brave News in the last week and you used the sidebar filter at least once, how many times have you used the sidebar filters? (reported weekly, desktop only)
`Brave.Today.SidebarFilterUsages`

0. 1
1. 2-4
2. 5-7
3. 8-10
4. 11+

Also, replace `Brave.Today.DirectFeedsTotal` with `Brave.Today.DirectFeedsTotal.2`:

As a Brave News user this month, how many external feeds do you have in total? (reported monthly, with same buckets)

cc @LorenzoMinto

**Comment by LorenzoMinto** [comment]
@DJAndries for (1) and (2), could we use `Click` instead of `Visit`. Visit could be mistaken as a feed visit. It also matches the language in the question

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.64.74 Chromium: 122.0.6261.43 (Official Build) beta (64-bit)
-- | --
Revision | b03db955df4f1c679cb7c2ae8ebfd331d5c29276
OS | Windows 10 Version 22H2 (Build 19045.4046)
```

<details>
<summary>Brave.Today.WeeklyTotalCardClicks</summary>

</details>


<details>
<summary>Brave.Today.ClickCardDepth</summary>

</details>

<details>
<summary>Brave.Today.ChannelCount</summary>

</details>

<details>
<summary>Brave.Today.PublisherCount</summary>

</details>

<details>
<summary>Brave.Today.SidebarFilterUsages</summary>

</details>

<details>
<summary>Brave.Today.DirectFeedsTotal.2</summary>

</details>

**Comment by GeetaSarvadnya** [comment]
`Brave.Today.ChannelCount`

0. No channel added
1. 1-3
2. 4-6
3. 7-9
4. 10+

**Comment by DJAndries** [comment]
> Could you update the Brave.Today.ChannelCount metrics response bucket as below? this works as per the response bucket as below. Thanks!

The original buckets are correct. Please keep in mind that the "Top Sources" channel (which is enabled by default) is included in the channel count.

>If I click on 1 or 2 cards I get the metrics response as 0 as expected. But the response bucket range for 1 and 2 are different when I test these cases, click on upto 6 cards I get response 1 but the description say the repsonse 1 should be shown upto 5 cards click, similarly for response bucket 2 the range varies, click upto 13 cards I get the response 2 but the description says 6-10. The response buckets needs to be updated or it's a bug?

>The metrics response value is 0 is shown only when 5-6 cards are clicked, but the response bucket range is 1-3 cards deep in the issues description, similarly 7 -12 cards click yields 1 response value. For remaining response values also the cards click rang varies. Is this a bug or cards deep range needs to be updated?

I suspect that this may be due to issues with the click handler, which was fixed in https://github.com/brave/brave-core/pull/22365. I recommend performing testing on Nightly, or clicking on the article title text directly if testing on Beta.

**Comment by GeetaSarvadnya** [comment]
![image](https://github.com/brave/brave-browser/assets/38657976/fc4155c3-df2e-4f53-8dfd-d3e3ba406a6c)

@DJAndries The metrics `Brave.Today.ClickCardDepth` is shown with response value `0`  when 5 or more cads are clicked, but the metrics description says the value `0` should be shown for the `1-3 cards deep`. This needs to be changed correct?

**Comment by LorenzoMinto** [comment]
@GeetaSarvadnya card depth of a click is the ordinal number of the card that has been clicked counting from the top. The card depth metric is an average across the 5 or more clicks. So if I click the first card in the feed for 5 times that should return bucket 0. In practice, we're taking the average of the single clicks' depths. Correct me if I'm wrong @DJAndries

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.64.104`

**Comment by GeetaSarvadnya** [comment]
@DJAndries: The metrics `Brave.Today.SidebarFilterUsages` isn't shown on Android. "For you" and "Following" filters don't show up brave news cards like Desktop. There is no "For you" filter available on Android. I have verified the metrics by clicking on the Brave news cards on NTP but metrics isn't shown on the brave://local-state file.

Destop  | Android
----------|--------
![image](https://github.com/brave/brave-browser/assets/38657976/d7b89878-0438-488e-856c-d7f28d2d71d4) | ![Screenshot_20240319_134948](https://github.com/brave/brave-browser/assets/38657976/8587c386-46ca-4ed8-9a03-5e364bab173d)

**Comment by DJAndries** [comment]
> The metrics Brave.Today.SidebarFilterUsages isn't shown on Android

@GeetaSarvadnya this is expected, the metric is only for desktop
