### ISSUE TITLE
Fix Bitcoin pending balance calculate 

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#35438]
Balance should keep track of used change address when calculating pending balance change for transaction to self

**Comment by kjozwiak** [comment]
The above requires `1.63.138` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.63.141 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | aa92f6cecec7f6c576bd1cf120f4cf359d770159
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21643](https://github.com/brave/brave-core/pull/21643)
- Verified all line items show correct value depending on pending balance
![image](https://github.com/brave/brave-browser/assets/17010094/3341d22f-57a3-4b20-9b42-7a49822de047)
