### ISSUE TITLE
CR121 - `All extensions` text is shown under brave://extensions/ when no extension are installed/imported

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#35437]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/34702
 `All extensions` text is shown under brave://extensions/ when no extension are installed/imported

## Steps to Reproduce

   1. NA
 

## Actual result:

![image](https://github.com/brave/brave-browser/assets/38657976/aa993d41-8b48-4aa7-b529-5d8e410edcbc)

## Expected result:
 `All extensions` text should not be shown under brave://extensions/ when no extension are installed/imported

1.61.x RC build
![image](https://github.com/brave/brave-browser/assets/38657976/3c7ee9d8-9e30-4a89-b823-c0ea5fcd7bf2)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.64.2 Chromium: 121.0.6167.57 (Official Build) nightly (64-bit)
-- | --
Revision | 090e22fcb8520fb64937caf796f7aae8639113bf
OS | Windows 10 Version 22H2 (Build 19045.3930)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @mkarolin

**Comment by GeetaSarvadnya** [comment]
The issue is not reproducible with `1.63.119 Chromium: 120.0.6099.217`. It's reproducible only with CR121 builds

**Comment by mkarolin** [comment]
Seems like we inherited this from Chromium. Maybe just keep it, @rebron?

**Comment by rebron** [comment]
We can keep this one. Closing and marking as wontfix.
