### ISSUE TITLE
Re-prioritize which Wallet panel is shown when actions/requests are pending

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#35449]
## Description 

Certain panels should take priority of others.
Show the "connect to dApp" screen with higher priority then pending transaction confirmations

**Old priority: (1st is most important)**
1. Welcome Panel
2. Unlock Wallet
3. Transaction Status (selected transaction details)
4. ConnectHardwareWallet
5. ConfirmSwapTransaction
6. ConfirmTransaction
7. AddSuggestedToken
8. Allow Network
9. Change Network
10. SignInWithEthereumError
11. Sign Message
12. Sign Transaction
13. Provide PubKey (provide encryption key)
14. Decrypt Request
15. ConnectWithSite
16. Portfolio screens

**New priority: (1st is most important)**

1. WelcomePanel
2. Unlock Wallet
3. ConnectWithSite
4. ConnectHardwareWallet
5. Allow Add Network
6. Switch Chain
7. SignInWithEthereumError
8. ProvidePubKeyPanel
9. DecryptRequestPanel
10. SignPanel
11. AddSuggestedTokenPanel
12. TransactionStatus
13. ConfirmSwapTransaction
14. ConfirmTransactionPanel
15. SignTransactionPanel
16. Portfolio

## Steps to Reproduce

 Consult the regression test guide on how to open each panel, close the panel without dismissing requests if possible to test which one appears first when re-opening the panel

## Actual result:

panels open based on old priorities

## Expected result:
panels should open based on the new priorities 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.104 Chromium: 123.0.6312.46 (Official Build) (64-bit)
-- | --
Revision | 0ca3d372cf8aab96fafdd75f5c5c8d2012bc0cc6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from issue description
- Verified panel priority works as expected
- Verified with permission request in progress closing panel doesn't dismisses it
