### ISSUE TITLE
(Feature) Requesting for shifting of URL bar at bottom not merged with navigation buttons but above it something like Samsung browser or Vivaldi browser or Naver Whale browser has done beautifully.

### ISSUE THREAD

**Issue by Varniit-pro-90s** [brave/brave-browser#35443]
(Feature) Requesting for shifting of URL bar at bottom not merged with navigation buttons but above it something like Samsung browser or Vivaldi browser or Naver Whale browser has done beautifully.

![photo_6147689318911687231_y](https://github.com/brave/brave-browser/assets/156216269/d07ccf68-6d05-48d1-9850-e8fc72fe5912)

![photo_6147689318911687229_y](https://github.com/brave/brave-browser/assets/156216269/4d73f29d-d0e3-4e13-8b6d-fb3b3c45c2e2)

![photo_6147689318911687230_y](https://github.com/brave/brave-browser/assets/156216269/cc05d964-26e6-436a-95ea-ea2f5a9ed807)

**Comment by Varniit-pro-90s** [comment]
cc @anthonypkeane

**Comment by Varniit-pro-90s** [comment]
> @Varniit-pro-90s have you tapped the magnifying glass icon 🔎 on the bottom bar? That should bring the URL bar into focus with a keyboard. Or is there something else on the URL bar that you would like easy access to? cc @deeppandya
> 
>  Screen_Recording_20240124_121157_Brave.mp4

You should check the last pic of my post above. I am talking about a dedicated navigation buttons like back and forth (forward), share, home (or new tab), and menu bar options.

Brave has bottom bar, but not navigation bar since the buttons are not the ones mentioned and unfortunately, one cannot edit them like Samsung browser or edge browser android.

**Comment by Varniit-pro-90s** [comment]
> @Varniit-pro-90s you would like:
> 
> (1) The option to customize the action buttons on the bottom bar? (2) The option to move the url bar to the top/bottom of the screen?

both. 

I dont have navigation bar at bottom (the one brave provides doesnt have back and forth, see images clearly) in brave and url bar also for easy access on big screen devices like big display sized phones and tablets and chromebooks.

**Comment by Varniit-pro-90s** [comment]
> @Varniit-pro-90s you would like:
> 
> (1) The option to customize the action buttons on the bottom bar? (2) The option to move the url bar to the top/bottom of the screen?

![Screenshot_2024-01-29-00-12-02-703_com opera browser beta](https://github.com/brave/brave-browser/assets/156216269/26ca9770-52e9-4618-98cd-dda32b530234)

**Comment by Varniit-pro-90s** [comment]
> @Varniit-pro-90s you would like:
> 
> (1) The option to customize the action buttons on the bottom bar? (2) The option to move the url bar to the top/bottom of the screen?

This is what I am talking about @timchilds. 

I came across this while scrolling and reading about brave ads on your company's site.

See the bottom URL bar and navigation buttons. Both different not overlapping and separate, not merged.

Nothing less, nothing more. Exactly this.

cc @anthonypkeane @rebron @deeppandya 

![chrome_2MdX3SZLmV](https://github.com/brave/brave-browser/assets/156216269/04bb0b61-8095-4505-bdf1-073e1b772219)

**Comment by bsclifton** [comment]
Thanks for the recommendations including mock up! 🙂 I'm going to close this issue as a duplicate - you can track the feature at https://github.com/brave/brave-browser/issues/7356 and subscribe for updates. You can also post there if you'd like
