### ISSUE TITLE
Uphold linking always creates a new card

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#35445]
Uphold is now returning an HTTP status code of 206 on success from the `/v0/me/cards?q=currency:BAT`. This endpoint is used to determine if the user has an existing "Brave Browser" card. If the user has an existing card, then that card is used for Rewards operations. Otherwise, a new card is created with the label "Brave Browser".

Uphold is now returning 206 from this endpoint, which the Rewards client does not recognize.

**Comment by kjozwiak** [comment]
Adding `QA/Blocked` as the above will potentially be uplifted into `1.62.x` via https://github.com/brave/brave-core/pull/21885 once we verify/confirm that https://github.com/brave/brave-core/pull/21647 hasn't caused any issues and that both of `200` & `206` are working as expected.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.63.145 Chromium: 121.0.6167.139 (Official Build) beta (x86_64)
-- | --
Revision | 73dc726c461ceae35c2aa15c4a2d9e6736b5c86d
OS | macOS Version 13.6.4 (Build 22G513)
```

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.62.161 Chromium: 121.0.6167.139 (Official Build) (64-bit)
-- | --
Revision | 9afaacd1500fdbd60ed4500b63b9ab85597ef933
OS | Windows 10 Version 22H2 (Build 19045.3930)
```
Case 1 - `206` Response code - PASSED

<details>

Possible pre-req: if Uphold is sending `200` in sandbox, need to create a Charles Proxy rewrite rule to change it to 206 

1. Created a clean profile using 1.63.145
2. Closed and relaunched to pull griffin
3. Enabled Rewards
4. Connected a custodian with a non-zero balance
5. Confirmed the response code for `https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT` was rewritten to be `206`:

```
[ REQUEST ]
> URL: https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT
> Method: GET
[56755:259:0205/100434.067343:VERBOSE1:url_loader.cc(111)] 
[ RESPONSE ]
> URL: https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT
> Result: Success
> HTTP Code: 206
> Body: [{"CreatedByApplicationId":"193a7........
```

6. Confirmed I could still see a balance in rewards

<img width="662" alt="1" src="https://github.com/brave/brave-browser/assets/28145373/5ae79f94-1bad-4b56-82a4-62909d730653"> | <img width="1194" alt="2" src="https://github.com/brave/brave-browser/assets/28145373/9f980435-db66-4df4-859a-619cc0ea238c"> | <img width="1189" alt="3" src="https://github.com/brave/brave-browser/assets/28145373/7d50adee-0b89-4976-a40c-e78513323a26">
-- | -- | --

</details>

Case 2 - `200` Response code - PASSED

<details>

1. Created a clean profile using 1.63.145
2. Closed and relaunched to pull griffin
3. Enabled Rewards
4. Connected a custodian with a non-zero balance
5. Confirmed the response code for `https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT` was `200`:

```
[ REQUEST ]
> URL: https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT
> Method: GET
[56946:259:0205/101249.270917:VERBOSE1:url_loader.cc(111)] 
[ RESPONSE ]
> URL: https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT
> Result: Success
> HTTP Code: 200
> Body: [{"CreatedByApplicationId":"193a7......
```

6. Confirmed I could still see a balance in rewards

<img width="1549" alt="1" src="https://github.com/brave/brave-browser/assets/28145373/79beed04-b0a7-4f2c-b7cb-a20a6936a579"> | <img width="1546" alt="2" src="https://github.com/brave/brave-browser/assets/28145373/363c9e89-af13-4604-9f4d-5f98aa5870d8">
-- | -- 

</details>

Case 3 - Initial connection with `200` Response code, Reconnect with `206` Response code - PASSED

<details>

pre-req: have Charles Proxy running, but do not have rewrite rule for `206` response code enabled

1. Created a clean profile using 1.63.145
2. Closed and relaunched to pull griffin
3. Enabled Rewards
4. Connected a custodian with a non-zero balance
5. Confirmed the response code for `https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT` was `200`:

```
[ REQUEST ]
> URL: https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT
> Method: GET
[57271:259:0205/102958.381976:VERBOSE1:url_loader.cc(111)] 
[ RESPONSE ]
> URL: https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT
> Result: Success
> HTTP Code: 200
> Body: [{"CreatedByApplicationId":"193a77c.....
```

6. Confirmed I could still see a balance in rewards

<img width="623" alt="Screenshot 2024-02-05 at 10 30 44 AM" src="https://github.com/brave/brave-browser/assets/28145373/caf18041-39b5-4ebc-b016-f466004479cc"> | <img width="1049" alt="Screenshot 2024-02-05 at 10 30 53 AM" src="https://github.com/brave/brave-browser/assets/28145373/55cafd1d-c65d-4b60-a31b-5467ca16696a"> | <img width="1107" alt="Screenshot 2024-02-05 at 10 31 02 AM" src="https://github.com/brave/brave-browser/assets/28145373/1cc3c166-7b05-4b89-ab55-d41019f421fa">
-- | -- | --

7. Remove integration with Uphold
8. Confirm shows "Logged out" state in UI

<img width="1221" alt="Screenshot 2024-02-05 at 10 32 16 AM" src="https://github.com/brave/brave-browser/assets/28145373/a0cfc3d0-915a-4346-a3f4-7bbb7bfdec82"> | <img width="1219" alt="Screenshot 2024-02-05 at 10 32 23 AM" src="https://github.com/brave/brave-browser/assets/28145373/a0ad2bbf-1621-4c30-8a0a-018d1d8f67b6">
-- | --

9. Enable Charles Proxy rewrite rule for `206` response
10. Reconnect rewards to Uphold
11. Confirmed the response code for `https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT` was rewritten to be `206`:

```
[ REQUEST ]
> URL: https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT
> Method: GET
[57271:259:0205/103341.605485:VERBOSE1:url_loader.cc(111)] 
[ RESPONSE ]
> URL: https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT
> Result: Success
> HTTP Code: 206
> Body: [{"CreatedByApplicationId":"193a77.......
```

12. Confirmed I could still see a balance in rewards

<img width="619" alt="Screenshot 2024-02-05 at 10 34 26 AM" src="https://github.com/brave/brave-browser/assets/28145373/194990c1-1d29-4cd3-b550-764d3f489dc6"> | <img width="1221" alt="Screenshot 2024-02-05 at 10 34 38 AM" src="https://github.com/brave/brave-browser/assets/28145373/cac2f0eb-9d79-458b-996d-05881c68db87"> | <img width="1220" alt="Screenshot 2024-02-05 at 10 34 45 AM" src="https://github.com/brave/brave-browser/assets/28145373/03fb8e39-f73c-44e6-b0cf-353ba43c64c4">
-- | -- | --

</details>

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.62.161 Chromium: 121.0.6167.139 (Official Build) (x86_64)
-- | --
Revision | 9afaacd1500fdbd60ed4500b63b9ab85597ef933
OS | macOS Version 13.6.4 (Build 22G513)
```

Case 1 - `206` Response code - InProgress

<details>

Possible pre-req: if Uphold is sending `200` in sandbox, need to create a Charles Proxy rewrite rule to change it to 206 

1. Created a clean profile using 1.63.145
2. Closed and relaunched to pull griffin
3. Enabled Rewards
4. Connected a custodian with a non-zero balance
5. Confirmed the response code for `https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT` was rewritten to be `206`:

```

```

6. Confirmed I could still see a balance in rewards

-- | -- | --

</details>

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung galaxy version 12` running `Bravemonoarm64.apk_1.62.161`


Case 1 - `206` Response code - Inprogress

<details>

Possible pre-req: if Uphold is sending `200` in sandbox, need to create a Charles Proxy rewrite rule to change it to 206 

1. Created a clean profile using 1.62.161
2. Closed and relaunched to pull griffin
3. Enabled Rewards
4. Connected a custodian with a non-zero balance
5. Confirmed the response code for `https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT` was rewritten to be `206`:

```
[ REQUEST ]
> URL: https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT
> Method: GET
[18032:26840:0206/195232.414:VERBOSE6:logging_util.cc(120)]
....
[ RESPONSE - OnRequest ]
> Url: https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT
> Result: Success
> HTTP Code: 206
> Body: [{"CreatedByApplicationId":"193...}]}]
[18032:26840:0206/195232.417:VERBOSE9:logging_util.cc(121)]
```

6. Confirmed I could still see a balance in rewards

charles | BR panel | Rewards settings page
--------|------------|---------------------------
![image](https://github.com/brave/brave-browser/assets/38657976/38eb5a40-c836-42ab-aa1e-2a083f61b97b) |![image](https://github.com/brave/brave-browser/assets/38657976/f98149ef-3c29-4a4f-8e8b-185f728d915e) | ![image](https://github.com/brave/brave-browser/assets/38657976/4eb605e9-ab3c-4f7e-8cd8-60ae9d1ed25a)


</details>

Case 2 - `200` Response code - Inprogress

<details>

1. Created a clean profile using 1.62.161
2. Closed and relaunched to pull griffin
3. Enabled Rewards
4. Connected a custodian with a non-zero balance
5. Confirmed the response code for `https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT` was `200`:

```
[ REQUEST ]
> URL: https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT
> Method: GET
....
[ RESPONSE - OnRequest ]
> Url: https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT
> Result: Success
> HTTP Code: 200
> Body: [{"CreatedByApplicationId":"19...."}]}]
[18292:10724:0206/172249.536:VERBOSE9:logging_util.cc(121)]

```

6. Confirmed I could still see a balance in rewards

BR panel | Rewards settings page
-----------|---------------------------
![image](https://github.com/brave/brave-browser/assets/38657976/630b86c4-3802-4256-8338-4ace016f5a56) | ![image](https://github.com/brave/brave-browser/assets/38657976/a5d8d15b-8183-4d54-83aa-62bbf06ee625)


</details>

Case 3 - Initial connection with `200` Response code, Reconnect with `206` Response code - Inprogress

<details>

pre-req: have Charles Proxy running, but do not have rewrite rule for `206` response code enabled

1. Created a clean profile using 1.62.161
2. Closed and relaunched to pull griffin
3. Enabled Rewards
4. Connected a custodian with a non-zero balance
5. Confirmed the response code for `https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT` was `200`:

```
[ REQUEST ]
> URL: https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT
> Method: GET
[16392:23664:0206/200151.861:VERBOSE6:logging_util.cc(120)]
....
[ RESPONSE - OnRequest ]
> Url: https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT
> Result: Success
> HTTP Code: 200
> Body: [{"CreatedByApplicationId":"193a...."}]}]
[16392:23664:0206/200151.864:VERBOSE9:logging_util.cc(121)]
```

6. Confirmed I could still see a balance in rewards

charles | BR panel | Rewards settings page
--------|------------|---------------------------
![image](https://github.com/brave/brave-browser/assets/38657976/e6196e04-4040-4dbe-bb0d-1998b3df65be) | ![image](https://github.com/brave/brave-browser/assets/38657976/cacd4d07-43b2-4fc8-844a-3781395c13e7) | ![image](https://github.com/brave/brave-browser/assets/38657976/6000c4e4-d400-40e4-a625-edb5a175316c)


7. Remove integration with Uphold
8. Confirm shows "Logged out" state in UI

![image](https://github.com/brave/brave-browser/assets/38657976/b97e8ef9-3767-4774-be33-f6b0fcbb13d4) | ![image](https://github.com/brave/brave-browser/assets/38657976/56dc6191-9eec-4a4f-80fb-560b30b99d66)
-- | --

9. Enable Charles Proxy rewrite rule for `206` response
10. Reconnect rewards to Uphold
11. Confirmed the response code for `https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT` was rewritten to be `206`:

```
[ REQUEST ]
> URL: https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT
> Method: GET
[7460:13500:0206/200820.202:VERBOSE1:user_idle_detection.cc(46)] User is idle
[7460:13500:0206/200820.270:VERBOSE6:logging_util.cc(120)]
....
[ RESPONSE - OnRequest ]
> Url: https://api-sandbox.uphold.com/v0/me/cards?q=currency:BAT
> Result: Success
> HTTP Code: 206
> Body: [{"CreatedByApplicationId":"193a7...}]}]
[7460:13500:0206/200820.271:VERBOSE9:logging_util.cc(121)]

```

12. Confirmed I could still see a balance in rewards

![image](https://github.com/brave/brave-browser/assets/38657976/08059cbd-4061-4c44-bfcb-3ed6b31d882f) | ![image](https://github.com/brave/brave-browser/assets/38657976/5efe6839-e383-42f5-8642-cd1a00ad8760) | ![image](https://github.com/brave/brave-browser/assets/38657976/56c5aef1-738e-4ddd-a0c1-92ab7f065bfe)
-- | -- | --

</details>
