### ISSUE TITLE
brave:// changes to chrome:// in URL bar

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3545]
## Description 
Only seems to affect 0.61.x.

If you navigate to a page like brave://version and then double click in the URL bar (say you want to change `version` to `settings`), you'll see that the `brave://` part changes to `chrome://`.

## Steps to Reproduce

   1. Open brave://version and let the page load.
   2. Double click in URL bar

## Actual result:
`brave://` changes to `chrome://`
![urlbar061x](https://user-images.githubusercontent.com/28145373/53664229-f3a32780-3c35-11e9-8bc6-bff5e97ec2ba.gif)

## Expected result:
Should stay `brave://`
![urlbar060x](https://user-images.githubusercontent.com/28145373/53664243-fc93f900-3c35-11e9-9f6d-e23b429a628c.gif)

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.61.41 Chromium: 73.0.3683.39 (Official Build) beta(64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Mac OS X

### Reproducible on current release: no, does not reproduce on 0.60.47
- Does it reproduce on brave-browser dev/beta builds? only beta 0.61.41.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Does not reproduce on Dev version 0.62.11
![urlbar062x](https://user-images.githubusercontent.com/28145373/53664324-31a04b80-3c36-11e9-8071-9166b5eeda64.gif)

**Comment by WhiteR4bbitt** [comment]
My address bar does not update to chrome, but this may be in the same realm of `brave://` urls. Let me know if this should be in its own issue.

I am on `0.60.47`, not sure if this is similar enough to be part of this issue but this is what I notice when on `brave://about`. All the URLS highlighted show `chrome` at the bottom, but will click through to `brave://<item>`
![image](https://user-images.githubusercontent.com/5930847/53749593-ea4bd200-3e64-11e9-84ab-faa995abb19b.png)

**Comment by Modelmat** [comment]
Additionally pages such as `brave://invalid` show a `chrome://invalid` page.
![image](https://user-images.githubusercontent.com/25718989/55953866-9cff2380-5ca0-11e9-9afc-bc7fbb5b0580.png)
and the tab shows:
![image](https://user-images.githubusercontent.com/25718989/55953870-9ffa1400-5ca0-11e9-9b65-1567bde66080.png)

**Comment by bsclifton** [comment]
@LaurenWags I think this has been fixed, can you confirm?

**Comment by LaurenWags** [comment]
@bsclifton yep, appears to be working on the following versions:

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)


Brave | 0.70.111 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)


Brave | 0.71.89 Chromium: 77.0.3865.90 (Official Build) dev (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)


Brave | 0.72.83 Chromium: 77.0.3865.90 (Official Build) nightly (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

Closing this issue.
