### ISSUE TITLE
Changing default model for Leo Premium on nightly isn't "sticky"

### ISSUE THREAD

**Issue by mrose17** [brave/brave-browser#35450]
Please add `browser-ai` to this issue!

## Description 
Default model change doesn't seem sticky. When Mixtral got added to nightly premium, Mixtral became the default. I changed it to 'Claude Instant', opened a new tab, and the model is still mixtral.

## Steps to Reproduce
   1. Be premium Leo on Nightly
   2. Open a new tab
   3. Open Leo
   4. Click on "..." and click on "Settings". This takes you to `brave://settings/leo-assistant`
   5. Change "Default Model for new conversations" from "Mixtral" to "Claude Instant"
   6. Open a new tab
   7. Open Leo

## Actual result:
See this:
<img width="314" alt="Screenshot 2024-01-19 at 12 41 46" src="https://github.com/brave/brave-browser/assets/400552/b9711758-5b47-4e57-ad66-d097aa834204">

## Expected result:
It should say "Claude Instant" not "Mixtral 7B"

## Reproduces how often: 
Consistently wrong, sorry!

## Brave version (brave://version info)
`Version 1.64.5 Chromium: 121.0.6167.75 (Official Build) nightly (arm64)` on a Macbook AIr running `Sonoma 14.2.1`

## Version/Channel Information:
- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? A/A
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:
N/A

**Comment by kjozwiak** [comment]
The above requires `1.62.149` or higher for `1.62.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.62.149 Chromium: 121.0.6167.75 (Official Build) (64-bit)
-- | --
Revision | ff84587bd70af9fcbcbe59fc5194ca65082759c4
OS | Windows 11 Version 22H2 (Build 22621.3007)
```

1. Installed `1.62.149`
2. launched Brave (with Leo staging flag `--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev`)
3. purchased Leo premium via account.bravesoftware.com for user `brave2leo@mailinator.com`
4. Open a new tab
5. click sidebar in the toolbar and to sidepanel
6. click Leo icon in the sidebar
7. entered `Brave` in the `Enter a prompt here` field
8. clicked `Accept and begin` button
9. clicked "..." menu and clicked on "Settings". 
10. verified Leo sidepanel shows `Mixtral by Mistral AI`
11. verified `Mixtral` shows as default in `brave://settings/leo-assistant`
12. switched from `Mixtral` to `Claude Instant` for `Default model for new conversations` option
13. opened a new tab
14. clicked Leo icon in the sidebar


#### Confirmed Leo sidepanel shows `Claude Instant` by Anthropic


step 3 | step 7 | step 8 | step 10 | step 11 | step 12 | step 14
------ | ----- | ------ | ------ | ------ | ----- | ------
<img width="640" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b4268fc1-064f-4439-8f36-b146627e4586">|<img width="643" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f4ba9693-7130-465d-b903-11ef970f4d56">|<img width="644" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/93375686-b9d4-4ac4-9e10-c7e626b11a79">|<img width="644" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b57ff246-c0bd-43b0-93bb-8b0fce2d6f08">|<img width="646" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d03d9fe1-d10e-42c7-983b-f017588ec502">|<img width="642" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/3d42810f-1ad3-48df-9f83-67c11494d6e9">|<img width="643" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/5e1d7613-1788-439a-a6fa-8aade7bf46de">
