### ISSUE TITLE
YouTube Desktop Doesn't Load Anymore

### ISSUE THREAD

**Issue by thevinter** [brave/brave-browser#35453]
## Description 
Since a couple of days Youtube Desktop refuses to fully open and I get an empty page skeleton. I assume it has to do with the latest adblock changes. I tried both with Brave Shields UP and DOWN with no luck. 

The issue affects only the desktop version of the website (m.youtube.com works fine). 

If I open the dev tools and clear the cache and hard reload the desktop website I (sometimes) get redirected to a working mobile version.

Very rarely if I full close brave and then reopen it then youtube works (and shows me ads, which wasn't happening before)

The devtools console shows the two following errors a lot:
```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-YkfADZ1H3UiTUXujeoPTGySbaDlSwhZnDfrIBq0wbs0='), or a nonce ('nonce-...') is required to enable inline execution.
```
and 
```
Refused to load the script '<URL>' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

## Steps to Reproduce
1. Open www.youtube.com

## Actual result:
![image](https://github.com/brave/brave-browser/assets/33670112/2e048b21-42b0-47f5-8586-57eff1553722)

## Expected result:
A working youtube page

## Reproduces how often: 
All the time

## Brave version (brave://version info)
Brave	1.61.120 Chromium: 120.0.6099.234 (Official Build) (64-bit) 
Revision	362207c81bff0740a8b6cff62dd91c6789f5698f
OS	Linux
JavaScript	V8 12.0.267.17

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
Yes
- Does the issue resolve itself when disabling Brave Rewards? 
Yes
- Is the issue reproducible on the latest version of Chrome? 
No

I'm using Arch Linux and the [brave-bin](https://aur.archlinux.org/packages/brave-bin) package

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by rebron** [comment]
@thevinter Can you go to  brave://components, and check Brave Ad Block Updater - Version: 1.0.3342 (or better). You have no other adblocker extensions correct?

**Comment by thevinter** [comment]
After some testing I realized the issue was with a JS-disabling extension that was preventing the JS from loading even if it was marked as disabled. 

Closing.
