### ISSUE TITLE
1337x.to suggests that Brave needs an update.

### ISSUE THREAD

**Issue by EternalTranquility1** [brave/brave-browser#35468]
![brave_0uQFb4BFwS](https://github.com/brave/brave-browser/assets/50317210/00ff8c74-8877-45f3-b980-68ff90c277c9)
![brave_yWCEvlwmTR](https://github.com/brave/brave-browser/assets/50317210/f3517f5c-0a16-4d76-a07b-ab80402a1cd3)

**Comment by arthuredelstein** [comment]
I couldn't reproduce -- maybe the problem is fixed?

**Comment by arthuredelstein** [comment]
Thank you @EternalTranquility1 !
