### ISSUE TITLE
Upgrade from Chromium 72.0.3626.119 to Chromium 72.0.3626.121 on 0.60.x branch

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#3546]
QA tests:

Check branding items
Check for version bump

**Comment by GeetaSarvadnya** [comment]
Verification passed on

Brave	0.60.48 Chromium: 72.0.3626.121 (Official Build) (64-bit)
Revision	da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883}
OS	Linux mint
![image](https://user-images.githubusercontent.com/38657976/53824639-73b0f080-3f9a-11e9-9ff5-759b16884fae.png)
