### ISSUE TITLE
Implement stream isolation for third-party subresources in Private Windows with Tor 

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#35464]
## Description 

Tor Browser [uses](https://gitlab.torproject.org/legacy/trac/-/issues/3455) a different Tor circuit for tabs with different first-party domain. All third-party subresources in a given tab use the same circuit as the top-level document. This prevents users from being partially correlated across tabs via the Tor circuit (or exit node IP Address) of a subresource.

As detected by privacytests.org, Brave Private Window with Tor is not currently performing stream isolation (aka Tor circuit isolation) for third-party subresources on the site: 
<img width="293" alt="image" src="https://github.com/brave/brave-browser/assets/355566/bba2f763-4350-4641-b3a6-a6d9d93187cc">

## Steps to Reproduce

   1. Choose File > New Private Window with Tor
   2. Navigate to https://arthuredelstein.net/tordemos/stream-isolation.html
   3. Open a second tab and navigate to https://arthuredelstein.github.io/tordemos/stream-isolation.html

## Actual result:

Detected IP addresses (server reflexive address) are the same, meaning the same exit node is being used in both tabs for the embedded iframes.

## Expected result:
iframes in pages with different first-party domain should use different Tor circuits, which should result in displaying different IP addresses in the two tabs. (The same goes for other subresources; see further testing in the [comment below](https://github.com/brave/brave-browser/issues/35464#issuecomment-1905215588).)

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

- Brave 1.61.120 Release
- Brave 1.64.5 Nightly

**Comment by diracdeltas** [comment]
This seems like a regression, as I remember we used to do this. cc @darkdh 

If we fix it there should be a test added

**Comment by darkdh** [comment]
Yes, it's a regression and I remember that we have different circuits per site when I implemented it. And also agree that we should add test to prevent it from breaking again.

**Comment by arthuredelstein** [comment]
I made more tests that looks at stream isolation of different third-party resources. In these tests, you need to load two tabs with the following URLs that have subtly different eTLD+1 domains:
* https://test-pages.privacytests.org/stream-isolation.html
* https://test-pages.privacytests3.org/stream-isolation.html

Each of the 11 tests makes a third-party request to a URL with the eTLD+1 `*.privacytests2.org`, and records the server-reflexive IP address. The test names have the following meanings:

* `favicon` = favicon loaded in tab UI
* `fetch` = `fetch` API
* `xhr` = `XMLHttpRequest` API
* `page` = iframe
* `css` = `<style src=...>` tag
* `image` = `<img src=...>` tag
* `script` = `<script>` tag
* `prefetch` = `<link rel='prefetch' ...>`
* `font` = webfont loaded through `@font-face`
* `h1` = HTTP/1 request
* `h2` = HTTP/2 request

Here are the results I get:

<img width="1119" alt="image" src="https://github.com/brave/brave-browser/assets/355566/a99b4a4e-093b-4bd9-a770-d1a0b3aa1b95">


(These tests are slow and can be a little flaky. Sometimes you need to hard-reload them.)

**Comment by arthuredelstein** [comment]
As a control, I ran the tests on Tor Browser and confirmed that these things are isolated by first-party domain:

<img width="1080" alt="image" src="https://github.com/brave/brave-browser/assets/355566/8b02f3eb-31cf-4add-9bb3-3a69a6234cba">

**Comment by darkdh** [comment]
Removed regression label since it has always been this way since we have Tor window.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.64.97 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | f7c8f13563bfe1063db456650cb43207e1c960c0
OS | Windows 10 Version 22H2 (Build 19045.4123)
```

example | example
----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/0c1f2dc1-bfe3-4977-b1b0-991b9355d904) | ![image](https://github.com/brave/brave-browser/assets/387249/b08dee52-ea8c-41cd-a9db-55586bfea6cf)
