### ISSUE TITLE
Windows 7/8.1 are NOT supported anymore as per https://support.brave.com/hc/en-us/articles/11197967945613-Sunsetting-support-for-Windows-7-and-8-8-1

### ISSUE THREAD

**Issue by Blaukovitch** [brave/brave-browser#35460]
### REALLY?? Seriously?
**Release v1.61.120 (Chromium 120.0.6099.234) Windows 7** CRACK
https://github.com/Blaukovitch/GOOGLE_CHROME_Windows_7_CRACK/releases/tag/brave

## Hackers say: **WRONG!**
![image](https://github.com/Blaukovitch/GOOGLE_CHROME_Windows_7_CRACK/assets/116763547/36eb039f-1e45-4ea0-bb58-3333aa49cf58)

**Comment by adeii** [comment]
Brave Nightly 1.64.11 also!
https://github.com/adeii/supermium-portable/releases/tag/v1.64N
