### ISSUE TITLE
brave://settings/content page settings are not shown until the page is refreshed

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#35479]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/35369
brave://settings/content page settings are not shown until the page is refreshed
## Steps to Reproduce

   1. Clea profile 1.62.149
   2. Open brave://settings/privacy
   3. Click on `Site and Shield Settings`
   4. Content settings are NOT shown
   5. Reload the page
   6. Content settings are shown

## Actual result:

brave://settings/content page settings are not shown until the page is refreshed
![image](https://github.com/brave/brave-browser/assets/38657976/694efd37-c300-40ee-a864-591f0b7a4783)

## Expected result:

Content settings should be shown when user click on the `Site and Shield Settings` without page refresh
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.62.149 Chromium: 121.0.6167.75 (Official Build) (64-bit)
-- | --
Revision | ff84587bd70af9fcbcbe59fc5194ca65082759c4
OS | Windows 10 Version 22H2 (Build 19045.3930)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes in `1.64.5 Chromium: 121.0.6167.75`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @rebron @mkarolin @brave/qa-team

**Comment by GeetaSarvadnya** [comment]
Looks like the issue got introduced during the minor bump as the issue was not reproducible in the version `1.64.2 Chromium: 121.0.6167.57` on nightly but it got introduced in the version `1.64.5 Chromium: 121.0.6167.75`

**Comment by kjozwiak** [comment]
The above requires `1.62.50` for `1.62.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.62.150 Chromium: 121.0.6167.85 (Official Build) (64-bit)
-- | --
Revision | c01f5cde4d5d5e41134c0ccdb1868acd80a64a34
OS | Windows 10 Version 22H2 (Build 19045.3930)

```
Confirmed that the click on `Site and Shield Settings` opens up the brave://settings/content page and settings are shown as expected.
![image](https://github.com/brave/brave-browser/assets/38657976/d0b53aaf-799f-4a69-8d62-d8a3d6727f93)
