### ISSUE TITLE
Let user take screenshots when reporting webcompat issues

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#35473]
It would be extremely helpful if the user could take a screenshot when reporting webcompat issues. 

There would be a button on the Report Site form that on clicking would attach and send what the page currently looks like (below browser chrome without the Report Site overlay).

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.65.80 Chromium: 123.0.6312.29 (Official Build) nightly (64-bit)
-- | --
Revision | cd0c2b9c6f07e8f01724294c8d7e37393a8c3a38
OS | Windows 10 Version 22H2 (Build 19045.4170)
```

### Steps:
1. installed `1.65.80`
2. launched Brave
3. loaded `vox.com`
4. chose `Help >` `Report a broken site`
5. filled out the form, checked the `Include screenshot` checkbox
6. previewed the screenshot
7. submitted the form
8. repeated the above steps, without attaching a screenshot


### With screenshot

example | `screenshot preview` | `feedback submitted`
----------|-----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/dd1ec68f-0a91-42b9-ad9f-13e5b2385f67) | ![image](https://github.com/brave/brave-browser/assets/387249/ce11194a-88f6-4fda-b511-854cee2bd434) | ![image](https://github.com/brave/brave-browser/assets/387249/6d3c97fd-0fa8-4898-9f2c-6aeb3632a4df)


### Without screenshot

example | `feedback submitted`
----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/0d3c816c-b5a7-4642-9e64-173d4194e5b9) | ![image](https://github.com/brave/brave-browser/assets/387249/ff8d2906-012e-482b-8c61-0bedf88dbaef)

**Comment by stephendonner** [comment]
@DJAndries hello!  I'd like to be able to verify my above submissions; do you know where I can find them?  (In particular, the submission with the screenshot, to be sure it was sent to the server.)

**Comment by DJAndries** [comment]
> @DJAndries hello! I'd like to be able to verify my above submissions; do you know where I can find them? (In particular, the submission with the screenshot, to be sure it was sent to the server.)

will DM

**Comment by stephendonner** [comment]
Confirmed via our internal metrics/feedback system that the screenshot was indeed attached:

example | example | example
---------|---------|---------
<img width="1329" alt="Screen Shot 2024-03-14 at 8 25 00 PM" src="https://github.com/brave/brave-browser/assets/387249/351a75e9-81de-4231-9001-411643fb43a4"> | <img width="1329" alt="Screen Shot 2024-03-14 at 8 25 13 PM" src="https://github.com/brave/brave-browser/assets/387249/bbc0fcb8-9df9-4b90-9e00-ddad3dec0c21"> | <img width="1856" alt="Screen Shot 2024-03-14 at 8 21 58 PM" src="https://github.com/brave/brave-browser/assets/387249/5a4ca357-bf35-4a48-bea5-3dad46f5eb35">
