### ISSUE TITLE
Tweak navigation controls for new onboarding UI

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#35488]
![image](https://github.com/brave/brave-browser/assets/3308503/3da61870-910d-4669-a96a-0b6b15a93ced)

## Description

Add new back and close icons following Figma design for new onboarding UI.

Figma design: https://www.figma.com/file/oXIiv45pIhF2RGlpEjOfUg/Wallet-onboarding?node-id=6223%3A70942&mode=dev

Main umbrella issue: https://github.com/brave/brave-browser/issues/35294

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 and Lenovo Tab with Android 13 running 1.64.97 x64 build
- Verified steps from [brave/brave-core#21673](https://github.com/brave/brave-core/pull/21673)
- Verified back navigation works fine during onboarding
- Verified closing onboarding before completeing and restarting onboarding starts from beginning
- Verified onboarding navigation for both new wallet and restore wallet
- Encountered [#36675](https://github.com/brave/brave-browser/issues/36675)
