### ISSUE TITLE
Support better Leo extraction method for Github pull requests

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#35492]
It would be great if Brave Leo could understand pull requests better with custom extraction logic. 
This might look like getting a raw diff of the entire changeset and a different pre-prompt.

**Comment by stephendonner** [comment]
## Verification `PASSED` using

```
Brave | 1.65.87 Chromium: 123.0.6312.46 (Official Build) beta (64-bit)
-- | --
Revision | 2babfcf82ebba4c5dc0146d2ca66229ffd3ac02d
OS | Windows 10 Version 22H2 (Build 19045.4170)
```

### Steps:
1. installed `1.65.87`
2. launched Brave
3. loaded `https://github.com/brave/brave-core/pull/22616`
4. asked `Leo` which files were changed

### Confirmed `1.65.87` was able to specify the list of filenames which were changed; `1.64.107` was unable to

`1.65.87` | `1.64.107`
----|---------
![image](https://github.com/brave/brave-browser/assets/387249/3bbdd316-e567-4a45-a1fe-59fd001b0a87) | ![image](https://github.com/brave/brave-browser/assets/387249/60fbb702-55dc-415a-b125-304766df4425)


### Additionally:

`Which files have the most changes?`

### Confirmed `1.65.87` was able to specify the top two files with the most changes; `1.64.107` was unable to determine it

`1.65.87` | `1.64.107`
----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/b0c9b8ce-7fa3-4eb4-a59a-6f11a65c83d7) | ![image](https://github.com/brave/brave-browser/assets/387249/d50bdd2d-6580-4a5a-8089-89fdb9590d31)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave	1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (x86_64) 
Revision	5d9143e1a0812c53bdc27fd5384591254306a88c
OS	macOS Version 14.4.1 (Build 23E224)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave	1.65.100 Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
Revision	8456ab291d9c823aaff5de460a63b53485320488
OS	Linux
```

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
Revision	5d9143e1a0812c53bdc27fd5384591254306a88c
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

Test Scenario: 

1. Load a Github pull request 
2. Enable Leo, ask "which files were changed"
3. Also ask "which file has the most changes?"

- Ensured that Leo will provide more details on Github pages. 

1.64.x | 1.65.x | 1.65.x
-|-|-
![Screenshot 2024-04-01 at 5 58 59 PM](https://github.com/brave/brave-browser/assets/17885425/f1295677-30bf-4983-9dda-4c9cdddffa74) | ![Screenshot 2024-04-01 at 4 15 09 PM](https://github.com/brave/brave-browser/assets/17885425/515b7894-d1e7-4963-89bd-956c6e64c10f) | ![Screenshot 2024-04-01 at 4 16 18 PM](https://github.com/brave/brave-browser/assets/17885425/9df3600e-e519-42ae-b4e8-21c5194749a6)
