### ISSUE TITLE
Hide Rewards summary in self-custody case

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#35498]
## Description

Hide the Rewards summary breakdown / line item list, given that none of the line items really apply in this case.

```[tasklist]
### Tasks
- [x] Rewards panel
- [x] brave://rewards page
- [x] Continue to show the payout status banner in Rewards panel
```

cc: @LaurenWags

**Comment by kjozwiak** [comment]
The above requires `1.63.138` or higher for `1.63.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.63.138 Chromium: 121.0.6167.85 (Official Build) beta (64-bit)
-- | --
Revision | 742a3bdf71b710125a1c1dd8e89981b9009a87bc
OS | Windows 10 Version 22H2 (Build 19045.3930)

```
Per https://github.com/brave/brave-browser/issues/35498#issue-2094615599, confirmed that the summary list is removed from the panel and brave://rewards in self-custody case:

<img width="1464" alt="1" src="https://github.com/brave/brave-core/assets/28145373/ad5e4d6a-d979-4ef7-a98f-629c8b01e510"> | <img width="1465" alt="2" src="https://github.com/brave/brave-core/assets/28145373/b44c4d97-7c71-4bb1-a180-8bd34c279608"> | <img width="1475" alt="3" src="https://github.com/brave/brave-core/assets/28145373/1d88cc5f-ed1e-4c28-b136-87c6b8b7159e">
-- | -- | --

Per https://github.com/brave/brave-browser/issues/35498#issue-2094615599, confirmed that the payout status banner continued to display on the panel:

pre-req: Have some ads viewed and cashed in with the server. Then, 
- For "pending", advance computer clock ahead to next month between day 1-7 and look at panel for expected banner
- For "processing"/"completed" use Charles to re-write response to check "processing" and/or "complete" on days 8-end of month

Pending | Processing | Complete
--- | --- | ---
<img width="1900" alt="Screenshot 2024-02-03 at 12 35 24 PM" src="https://github.com/brave/brave-core/assets/28145373/49c26c96-f990-491f-b4a8-a5527ee5f31d"> | <img width="1910" alt="2" src="https://github.com/brave/brave-core/assets/28145373/1029afee-1868-4616-acce-a02aaf146724"> | <img width="1904" alt="3" src="https://github.com/brave/brave-core/assets/28145373/9a09d5b4-a85f-4a55-a8da-fd042a120797">
