### ISSUE TITLE
Task manager shows Chromium instead of Brave

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#355]
## Description 
Task manager shows Chromium instead of Brave

## Steps to Reproduce

   1. Open task manager by pressing <kbd>Shift+Esc</kbd>
   2. Main process shows Chromium icon instead of Brave
   3. New tab icon shows generic icon 

 ## Actual result:

![image](https://user-images.githubusercontent.com/17010094/41467780-be0b2b72-7075-11e8-87ff-60ad90628ac5.png)

![image](https://user-images.githubusercontent.com/17010094/41468047-9cd70678-7076-11e8-8f09-703583e0cd45.png)

## Reproduces how often: 
100%

## Brave version (about:brave info)

Packaged build most likely same on release build

cc: @simonhong @bbondy

**Comment by yrliou** [comment]
<img width="483" alt="screen shot 2018-06-27 at 7 46 16 pm" src="https://user-images.githubusercontent.com/4730197/42010291-d30282ba-7a42-11e8-9252-c5b1ec29f38a.png">

I think it's already been solved in current master, tried on Windows and Mac.
Feel free to reopen it if not, thanks!

**Comment by simonhong** [comment]
Recently chromium's `IDR_PRODUCT_LOGO_16` is replaced with ours by https://github.com/brave/brave-browser/pull/395.

I assume that task manager is affected by this change.
```
BrowserProcessTask::BrowserProcessTask()
    : Task(l10n_util::GetStringUTF16(IDS_TASK_MANAGER_WEB_BROWSER_CELL_TEXT),
           "Browser Process",
           FetchIcon(IDR_PRODUCT_LOGO_16, &s_icon_),
           base::GetCurrentProcessHandle()),
      used_sqlite_memory_(-1) {}
```
However, it should have more higher quality image than now :)

**Comment by bbondy** [comment]
@simonhong does another issue need to be created for what you mentioned in the last comment?

**Comment by simonhong** [comment]
Logo seems fine with this PR - https://github.com/brave/brave-core/pull/204/files

**Comment by bbondy** [comment]
@kjozwiak sounds like a new 1.x backog issue if you don't mind posting it.

**Comment by srirambv** [comment]
this happens to all `chrome://` pages that has custom code
![image](https://user-images.githubusercontent.com/17010094/46052387-423f1980-c10c-11e8-91f5-6c3a6cecffa2.png)

**Comment by bbondy** [comment]
we could supply a favicon easily, just need it tracked

**Comment by kjozwiak** [comment]
@srirambv yup, noticed the same thing.. I'll create a bug re: adding Brave icons for custom `chrome://pages`

> we could supply a favicon easily, just need it tracked

Yup, I'll create the bug for tracking and add it into the `1.x backlog` 👍

**Comment by kjozwiak** [comment]
@bbondy @srirambv created https://github.com/brave/brave-browser/issues/1278.
