### ISSUE TITLE
ads.brave.com is blocked

### ISSUE THREAD

**Issue by corymcdonald** [brave/brave-browser#3550]
![image 6](https://user-images.githubusercontent.com/5459225/53673373-b0a07e80-3c4c-11e9-92a6-6b4ac4257c0b.png)

Sampson and Amir reported this. Could this be an instance where `ads.*` is being blocked by the easylist?

**Comment by mrzealot** [comment]
Yupp, the blocking does come from easylist with a bunch of built-in exceptions like:

`://ads.$domain=~ads.ac.uk|~ads.adstream.com.ro|~ads.am|~ads.bigbom.com|~ads.colombiaonline.com|~ads.comeon.com|~ads.elcarado.com|~ads.google.com|~ads.harvard.edu|~ads.lapalingo.com|~ads.
lordlucky.com|~ads.mobilebet.com|~ads.msstate.edu|~ads.nc|~ads.nimses.com|~ads.quasaraffiliates.com|~ads.red|~ads.route.cc|~ads.sk|~ads.socialtheater.com|~ads.toplayaffiliates.com|~ads.viksa
ffiliates.com|~ads.watson.ch|~ads.xtribeapp.com|~badassembly.com|~caravansforsale.co.uk|~fusac.fr|~memo2.nl|~reempresa.org|~seriouswheels.com`

So we'd either need to add ourselves to this exception domain list, or add a custom exception rule with the `@@` syntax somewhere.

**Comment by bbondy** [comment]
Could we just change our subdomain? It would continue to be broken in other browsers otherwise, and also random people have a tendency to audit things and take things out of context.

**Comment by ryanbr** [comment]
Fixed;
https://github.com/easylist/easylist/commit/11b767bd5f25384703ed412b1b9c04348bbd196d

**Comment by bsclifton** [comment]
@ryanbr is the fix pushed? (ex: can we close this issue?) 😄

**Comment by ryanbr** [comment]
yup, was fixed 3 days ago
