### ISSUE TITLE
update premium upsell UI

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#35503]
the new upsell UI has a strong focus on highlighting features and allowing user to select price. we need to update this in our codebase.

figma: https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Leo-MVP?type=design&node-id=3251-39689&mode=design&t=X9jQNrQuoxf2a6pW-0

<img width="365" alt="image" src="https://github.com/brave/brave-browser/assets/8665427/9bacaf58-79ae-4dbe-a8ad-88c3c07d7fea">

**Comment by esuleman** [comment]
can i contribute to this feature?

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)
```

1. installed 1.63.155
2. launched Brave (with out command line flags)
3. clicked Leo icon
4. entered `hi` in the prompt field
5. clicked `I understand`
6. visited https://en.wikipedia.org/wiki/Main_Page
7. clicked `Summarize this page`

<details>

example | example | example 
------|----------|-------
![image](https://github.com/brave/brave-browser/assets/98358127/c4aa1fc3-9db8-4463-a653-d3ee2838bb80)|![image](https://github.com/brave/brave-browser/assets/98358127/b85c8196-7b5b-4066-8c34-b6593c017fab)|![image](https://github.com/brave/brave-browser/assets/98358127/e5f3fb48-de47-4f6c-abc6-f7ee745b620c)
</details>

#### Case 1: Default model - Mixtral
<details>

- Confirmed new premium upsell UI is shown  

Dark | Light 
----- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/5331b494-4116-4c7c-bad4-8708b8c30a3a)|![image](https://github.com/brave/brave-browser/assets/98358127/0d19477c-c63f-4c79-bb80-6829598d9c43)
![image](https://github.com/brave/brave-browser/assets/98358127/94871958-be7f-4578-92fb-e4adefd64563)|![image](https://github.com/brave/brave-browser/assets/98358127/325b0e21-3864-4faf-aa1a-9079c9e747b9)
</details>

#### Case 2: Switch to the free model - `Llama 2 13b`
<details>

1. continue from case 1:
2. clicked on `Switch to the free model`
3. clicked `Retry` button

- Confirmed model is switched to `Llama 2 13b`
- Confirmed page summarized as expected 
- Confirmed when clicked `Suggest questions..`, related questions are shown

example | example | example | example  
------|----------|-------|------
![image](https://github.com/brave/brave-browser/assets/98358127/24477e5d-68f7-49a5-b8c4-a2b2e1c2b128)|![image](https://github.com/brave/brave-browser/assets/98358127/bd215229-fd16-42a3-8e4b-9884c478cb28)|![image](https://github.com/brave/brave-browser/assets/98358127/eb4ec14c-f7b1-4101-b8f3-13c66d58ecb9)|![image](https://github.com/brave/brave-browser/assets/98358127/4725b578-04a1-47ac-a48f-1056eaa60397)
</details>

#### Case 3: Claude Instant by Anthropic
<details>

1. Continue from case 2
      - `Llama 2 13b
2. switched to `Clause Instant` in the `...` menu in the Leo panel
3. clicked a link on the page and clicked `Summarize this page`
4. queried ~4 times with different page

Confirmed with the Claude Instant, got new premium upsell UI `Response Rate limit reached`  

example | example | example | example
------ | ------ | ------ | -----
![image](https://github.com/brave/brave-browser/assets/98358127/29c7ac1c-2795-4e4f-bc00-f6ebc2559016)|![image](https://github.com/brave/brave-browser/assets/98358127/a74ef484-13b7-4b93-8fc8-f128d0812d06)|![image](https://github.com/brave/brave-browser/assets/98358127/e8d0419d-c2fa-4f81-a869-7216bba99e48)|![image](https://github.com/brave/brave-browser/assets/98358127/78e2327a-3203-4614-9613-344c5fd0531c)
</details>

**Comment by kjozwiak** [comment]
Verification **IN PROGRESS** on `Pixel 6` running `Android 14` using the following PR(s):

```
Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
--- | ---
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Android 14; Build/AP11.231215.009; 34; REL
```

Used the following STR/Cases for the three current LLM's within Brave before ensuring the correct UI/UX was displayed when the Permium upsell was displayed:

* installed/launched `1.63.155 Chromium: 122.0.6261.29`
* visited/loaded a random article via `videocardz.com` and started `Summarizing`
* ensured that clicking on `Switch to the free model` correctly selected `Llama 2 13b` once a rate limit has been reached

### `Test Case #1` - Default Model - `Mixtral`

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------
![Screenshot_20240215-222949](https://github.com/brave/brave-browser/assets/2602313/f1efb9fe-aa35-4298-a9af-ac5f7294e183) | ![Screenshot_20240215-223130](https://github.com/brave/brave-browser/assets/2602313/7b35226e-0437-4eae-ac3b-c7a6db3af23b) | ![Screenshot_20240215-222957](https://github.com/brave/brave-browser/assets/2602313/04cdb728-c727-4169-86d2-61ea3b188bce) | ![Screenshot_20240215-223015](https://github.com/brave/brave-browser/assets/2602313/a6cdf6ff-858e-4563-8748-cdb819b09433)

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------
![Screenshot_20240215-225134](https://github.com/brave/brave-browser/assets/2602313/42692c39-93cf-4e8d-b743-2dbbda410e4d) | ![Screenshot_20240215-225138](https://github.com/brave/brave-browser/assets/2602313/949d1442-5ce6-486e-b6e2-0d07fb459e5b) | ![Screenshot_20240215-225152](https://github.com/brave/brave-browser/assets/2602313/e83629ad-00b3-4d3d-93d8-517ffb024534) | ![Screenshot_20240215-225209](https://github.com/brave/brave-browser/assets/2602313/e1b4846d-7ae1-4517-b10f-3a9d372a749c)
