### ISSUE TITLE
Shields/Rewards location icon's inkdrop bottom is clipped

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#35507]
## Description 

<img width="149" alt="Screenshot 2024-01-23 at 2 30 36 PM" src="https://github.com/brave/brave-browser/assets/6786187/d188e695-9bbd-4393-bcfa-2e8b0303e5ef">
<img width="147" alt="Screenshot 2024-01-23 at 2 30 42 PM" src="https://github.com/brave/brave-browser/assets/6786187/5b900040-f5ee-4a4f-9ffe-59780a1bcda1">

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? No (1.61.x)
- Can you reproduce this issue with the beta channel? Yes (1.63.x) 
- Can you reproduce this issue with the nightly channel? Yes (1.64.x)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.62.155` or higher for `1.62.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.62.155 Chromium: 121.0.6167.85 (Official Build) (x86_64)
-- | --
Revision | 91c989228daf153ef41bd965f268fabc7b9dbbf0
OS | macOS Version 13.6.4 (Build 22G513)
```
