### ISSUE TITLE
Adjust location bar height to 32px

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#35506]
## Description 

Set location bar height to 32px.
Follow-up to https://github.com/brave/brave-browser/issues/35066 which set height to 36px.

## Actual result:

Current location bar heights:
1.61.x 28px
1.62.x 34px
1.63.x 36px

## Expected result:
32px to give location bar some vertical space, however still a good height for laptop screens. 36px is great for users on desktop or external monitors however, takes up too much space for laptop users.

## Reproduces how often: 

Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.61.x location bar height 28px/ 1.62.x location bar height 34px
- Can you reproduce this issue with the beta channel? 1.63.x location bar heigh t36px
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.64.32 Chromium: 121.0.6167.85 (Official Build) nightly (64-bit)
-- | --
Revision | 59bd6e14828f1b3b3638729ff241d7c2055b1e38
OS | Windows 11 Version 23H2 (Build 22631.3085)
```

Compared `1.64.19 Chromium 121.0.6167.85` against `1.64.32 Chromium: 121.0.6167.85` and ensured that the `locationbar/omnibox` size was reduced from `36px` -> `32px` as per the following:

**`1.64.19 Chromium 121.0.6167.85`** | **`1.64.32 Chromium: 121.0.6167.85`**
------------------------------------------|----------------------------------------------
![old36px](https://github.com/brave/brave-browser/assets/2602313/8bbb8138-fdd0-4d4a-8314-356548e8063e) | ![new32px](https://github.com/brave/brave-browser/assets/2602313/961b397e-c6c1-42a9-9625-44266e0a13d1)

Also used https://picpick.app/en to quickly check/confirm that the `locationbar/omnibox` was `32px` as per the following:

![Screenshot 2024-01-29 152412](https://github.com/brave/brave-browser/assets/2602313/5adc8996-17f2-4aba-8eb3-ee2843be4d97)

**Comment by kjozwiak** [comment]
The above requires `1.62.155` or higher for `1.62.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.62.155 Chromium: 121.0.6167.85 (Official Build) (x86_64)
-- | --
Revision | 91c989228daf153ef41bd965f268fabc7b9dbbf0
OS | macOS Version 11.7.10 (Build 20G1427)
```
