### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by larreewong** [brave/brave-browser#35504]
Nightly has crashed about 5 times in the past 5mins when I opened Leo and put a new URLin the address bar.

IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.64.12 Chromium: 121.0.6167.75
Operating System: Mac OS X 12.6.9

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open Nightly
2. Use Leo once (ask a question) 
3. Visit a new site and use Leo
4. Crash

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/b9c40b00-802f-5e0b-0000-000000000000

**Comment by darkdh** [comment]
fingerprint 6a188376d08cff8aaa2d6497e67b72557b842bbfcc99a388590d57bb22554990

**Comment by kjozwiak** [comment]
The above will be verified by QA using https://github.com/brave/brave-browser/issues/35396 and the STR/Cases outlined via https://github.com/brave/brave-core/pull/21992#issue-2128077370. https://github.com/brave/brave-browser/issues/35396 will also be used as the `release-notes/include` for the `CHANGELOG` for `1.63.x`.
