### ISSUE TITLE
[Playlist] Playlist web ui is not visible in dark theme

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#35509]
![image](https://github.com/brave/brave-browser/assets/5474642/38c953b3-45ed-4e92-abec-64bd561689f5)
![image](https://github.com/brave/brave-browser/assets/5474642/1aaa7bf4-027f-4d47-a2e2-8945e9f7a96f)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.64.48 Chromium: 121.0.6167.139 (Official Build) nightly (x86_64)
-- | --
Revision | 741f7ee622bdfde5e10e3beda02288f3c056287e
OS | macOS Version 11.7.10 (Build 20G1427)
```

Followed the inline steps to reproduce.

### Confirmed I could `Move` and `Remove` in `Dark` mode

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="1774" alt="Screen Shot 2024-02-05 at 10 15 59 AM" src="https://github.com/brave/brave-browser/assets/387249/c82d28be-9f15-49a3-bb20-92830f604287"> | <img width="1774" alt="Screen Shot 2024-02-05 at 10 16 15 AM" src="https://github.com/brave/brave-browser/assets/387249/89330dc2-dcca-4d51-945d-ff0afe718fb9"> | <img width="1774" alt="Screen Shot 2024-02-05 at 10 16 45 AM" src="https://github.com/brave/brave-browser/assets/387249/077f37bf-afd0-4be3-b85e-d1d0904b8a24"> | <img width="1774" alt="Screen Shot 2024-02-05 at 10 17 04 AM" src="https://github.com/brave/brave-browser/assets/387249/f493239d-03ca-4c74-812a-8e523d74981e"> | <img width="1774" alt="Screen Shot 2024-02-05 at 10 17 08 AM" src="https://github.com/brave/brave-browser/assets/387249/66f151e9-a3fd-4749-ace4-883a051c5705">
