### ISSUE TITLE
update gas estimates when gas fields are changed

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#35518]
## Description 

We should refetch the gas estimates when the user changes any gas setting.

## Steps to Reproduce

   1. create a new EVM transaction
   2. edit the gas setting for the transaction

## Actual result:

the gas estimates do not immediately refresh

## Expected result:
the gas estimates should refresh

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.102 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | c9343c77bd5dee3524fc45f89721ce0bf4c09b8d
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from issue description
- Verified gas estimates is updated when gas fields are changed

https://github.com/brave/brave-browser/assets/17010094/0cd6bc0c-3c9f-4150-9bb4-8ce8f1b839fd
