### ISSUE TITLE
Show a loading spinner when loading the network for a pending transaction

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#35515]
## Description 

Show a loading spinner when loading the network for a pending transaction

## Steps to Reproduce

   1. create new transactions (eth send, sol send, eth swap, sol swap)
   2. observe the transaction panel

## Actual result:

The correct panel should be displayed. No loading spinner is shown if the network is not ready

## Expected result:
The correct panel should be displayed. A loading spinner should be shown if the network is not ready

## Reproduces how often: 

Intermittent

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.102 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | c9343c77bd5dee3524fc45f89721ce0bf4c09b8d
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21703](https://github.com/brave/brave-core/pull/21703)
- Verified transaction panel works as expected for Send/Swap transactions
- Verified for ETH/SOL/FIL Send and ETH/SOL Swaps
