### ISSUE TITLE
Excluded publisher included back in

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#3551]
## Steps to Reproduce

   1. clean profile / enable rewards
   2. visit a site and add it to ac table
   3. make sure that you see it the panel
   2. visit another site (don't stay on it for min visit time, if needed adjust min visit time to a minute)
   3. exclude site
   4. make sure that you see 1 excluded site in settings page
   5. close panel and open it again

## Actual result:

site is included again

## Expected result:
site should remain excluded

## Reproduces how often: 

100%

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

This only happens for sites that are not in ac table

**Comment by GeetaSarvadnya** [comment]
The issue is reproduced on Linux mint - `0.61.48`

![exclude issue](https://user-images.githubusercontent.com/38657976/53961969-ebecf280-410f-11e9-9544-8779a1cd0151.gif)

**Comment by GeetaSarvadnya** [comment]
Reproducible on 0.63.14. STR is a bit different

1. Clean profile 0.63.14
2. Enable rewards through BR panel
3. Open Twitch.tv
4. Open few twitch videos of same publisher in multiple tabs
5. Verify pubs added to a-c table
6. Toggle the include button to OFF for one of the twitch video ( step 4 - videos playing in all tabs should get excluded as all videos belongs to same publisher)
7. Verify the pub from step 6 got excluded from a-c table
8. Open another new video of same pubs, stay on page for ~20 sec


Actual: In BR panel, the included switch is ON (edited)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.63.30 Chromium: 73.0.3683.75 (Official Build) beta (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

Used test plan from https://github.com/brave/brave-core/pull/1823
