### ISSUE TITLE
Increase performance of create-site-origin component

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#35517]
## Description 

Remove the React.useMemo hook in this component, as it is not warranted. Also reduce calls to split the url string.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.102 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | c9343c77bd5dee3524fc45f89721ce0bf4c09b8d
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21706](https://github.com/brave/brave-core/pull/21706)
- Verified origin of pending transaction continues to work as expected without any regression
