### ISSUE TITLE
Add warning when sending BTC

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#35514]
- When sending BTC we need a warning to warn the user about their ordinals being affected during the transaction.

Slack conversation: https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1705443755455329

**Comment by kjozwiak** [comment]
The above requires `1.63.138` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.63.141 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | aa92f6cecec7f6c576bd1cf120f4cf359d770159
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21701](https://github.com/brave/brave-core/pull/21701)
- Verified warning message for sending BTC is shown on both mainnet and testnet

https://github.com/brave/brave-browser/assets/17010094/616846d0-af30-4190-b0d7-272266b15892
