### ISSUE TITLE
[ads] Unify iOS `kBraveNTPBrandedWallpaper` feature

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#35522]
Add Griffin feature support for `BraveNTPBrandedWallpaper` for the following feature params:
- [x] Add `kInitialCountToBrandedWallpaper` feature param
- [x] Add `kCountToBrandedWallpaper` feature param

And is required to add support to iOS.

**Comment by kjozwiak** [comment]
The above requires `1.62.158` or higher for `1.62.x` verification 👍 @LaurenWags for the above, we just need to worry about checking `Desktop` & `Android`. We'll run through `iOS` once we get builds with https://github.com/brave/brave-core/pull/21758.

Can use the STR/Cases I used via https://github.com/brave/brave-core/pull/21751#issuecomment-1919699323 & https://github.com/brave/brave-core/pull/21751#issuecomment-1919949981 as a template for verification via `1.62.x`.

**Comment by kjozwiak** [comment]
@brave/qa-team for the above, lets just run through the default case and ensure that both `SNTP` & `NTP` are being displayed in the correct order. For example, the default should be the following as per https://github.com/brave/brave-core/pull/21751#issue-2100732566:

* `2` for `BraveNTPBrandedWallpaper`/`initial_count_to_branded_wallpaper`
* `3` for `BraveNTPBrandedWallpaper`/`count_to_branded_wallpaper`

We just need to make sure that nothing regressed with the `iOS` changes. The study mentioned in the PR via https://github.com/brave/brave-variations/pull/911 was verified using `Nightly` via https://github.com/brave/brave-core/pull/21751#issuecomment-1919699323 & https://github.com/brave/brave-core/pull/21751#issuecomment-1919949981 which should be enough.

Asked @tmancey if the above is good enough for verifications on `1.62.x` via https://bravesoftware.slack.com/archives/C01LKMP6X36/p1707183058627789. If @tmancey feels that we should verify the study, we can do that as well. But for now, lets stick to the `Default` check.

**Comment by btlechowski** [comment]
Verified with

Brave | 1.62.161 Chromium: 121.0.6167.139 (Official Build) (64-bit)
-- | --
Revision | 9afaacd1500fdbd60ed4500b63b9ab85597ef933
OS | Linux


### Default values - opted out

#### initial_count_to_branded_wallpaper fresh start

Verified initial NTPSI is shown on 2nd NTP
![image](https://github.com/brave/brave-browser/assets/34715963/1d355e3b-4561-4a4c-9627-fc921ebb9ac7)


#### count_to_branded_wallpaper

Verified after initial NTPSI, new NTPSI is shown on 3rd NTP
![image](https://github.com/brave/brave-browser/assets/34715963/0a9a6ff6-8090-45e1-a804-9c749ab1d742)


#### initial_count_to_branded_wallpaper after browser restart

Verified initial NTPSI is shown on 2nd NTP on each browser restart
![image](https://github.com/brave/brave-browser/assets/34715963/86322963-fc5b-419f-9279-83a3bb67ac0b)


### Default values - opted in

#### initial_count_to_branded_wallpaper fresh start

Verified initial NTPSI is shown on 2nd NTP
![image](https://github.com/brave/brave-browser/assets/34715963/5b5a0770-650a-42ff-b757-1897c7af1885)

#### count_to_branded_wallpaper

Verified after initial NTPSI, new NTPSI is shown on 3rd NTP
![image](https://github.com/brave/brave-browser/assets/34715963/83e2c704-6a4d-4489-ad19-a6a289166294)

#### initial_count_to_branded_wallpaper after browser restart

Verified initial NTPSI is shown on 2nd NTP on each browser restart
![image](https://github.com/brave/brave-browser/assets/34715963/388347b5-b7eb-4fa4-a547-0a33cbe7520d)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.62.162 Chromium: 121.0.6167.164 (Official Build) (64-bit) 
Revision	c18c9cc62d2b4376a5ada5b98b673dfc7994f20d
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
_**initial_count_to_branded_wallpaper**_

- Ensured NTPSI is shown on 2nd Tab after initial launch.
- Ensured that next SI is shown on 3rd new tab after that.
- Ensured NTPSI is shown on 2nd Tab after each browser restart.

Fresh start | SI after restart + next SI
-|-  
![Screenshot 2024-02-07 at 11 46 40 AM](https://github.com/brave/brave-browser/assets/17885425/633d53d1-6912-46f3-b430-c0999607d13f) | ![Screenshot 2024-02-07 at 11 43 21 AM](https://github.com/brave/brave-browser/assets/17885425/35df74e8-2556-4aed-b8ea-83d568065bcb)
