### ISSUE TITLE
Label `USD` mis aligned in the rate limit model in the Leo panel

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#35531]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/34910

## Steps to Reproduce

   1. Installed 1.62.150
   2. launched Brave
   3. visited techcrunch.com 
   4. clicked sidebar on the toolbar
   5.  clicked Leo on the sidebar
   6. clicked Summarize button
   7. clicked Accept and begin button
   8. after several Leo responses (3-5) for different articles, got Response rate limit model as expected
   
## Actual result:

Response rate limit model has `USD` label mis-aligned

<img width="179" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/91a83041-8c88-4497-8b67-ff0c5d640f85">

## Expected result:
<img width="365" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/bda3dc0d-ac24-40b2-84c4-2407ea006de5">

## Brave version (brave://version info)

```
Brave | 1.62.150 Chromium: 121.0.6167.85 (Official Build) (64-bit)
-- | --
Revision | c01f5cde4d5d5e41134c0ccdb1868acd80a64a34
OS | Windows 11 Version 22H2 (Build 22621.3007)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@petemill @mattmcalister 
cc: @aguscruiz @stephendonner

**Comment by stephendonner** [comment]
@MadhaviSeelam just make the sidepanel wider :-)

**Comment by MadhaviSeelam** [comment]
> @MadhaviSeelam just make the sidepanel wider :-)

Agreed 😄

**Comment by aguscruiz** [comment]
Yeah and also buttons shouldn't be able to grow in two lines. Here's a mock for this panel with a super narrow view. It should be more responsive. 

It's based on the new design for the premium panel but you can see the same ideas applied
https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=1599%3A5618&mode=design&t=WiEgMKooL8n491PT-1

![image](https://github.com/brave/brave-browser/assets/15734630/30bc24d4-1751-4fe2-a0de-d6487489b455)

**Comment by nullhook** [comment]
this should be fixed with: https://github.com/brave/brave-core/pull/21717
