### ISSUE TITLE
Settings modal is not closed when Rewards is disabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3553]
## Description 

Settings modal is not closed when Rewards is disabled

## Steps to Reproduce

   1. Enable rewards
   2. Open Ads/A-C settings and disable rewards
   3. Still shows settings view instead of info modal

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/53681829-fdbc3900-3cbc-11e9-8380-a92d32b285c5.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/53681850-2f350480-3cbd-11e9-9514-f059649d9abd.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.62.11 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 10 OS Build 17134.590

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.63.5 Chromium: 73.0.3683.67 (Official Build) dev (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 10 OS Build 17134.523
