### ISSUE TITLE
`Switch to the free model` link in response-rate-limited reached dialog is a no-op

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#35534]
## Description 

`Switch to the free model` link in response-rate-limited reached dialog is a no-op

## Steps to Reproduce

   1. install `1.62.150`
   2. launch Brave (*no* commandline args) - using "prod"
   3. open sidebar
   4. click on `Leo`
   5. enter `test`
   6. click `Accept and begin`
   7. keep querying/conversing with `Leo` (`Mixtral`, default)
   8. hit the response rate limit
   9. get the `Response rate limit reached` modal
   10. click on `Switch to the free model`

## Actual result:

Nothing happens (no-op)

Nothing's also logged to `Console`, exception-wise (that I can see):

<img width="1563" alt="Screenshot 2024-01-23 at 6 24 38 PM" src="https://github.com/brave/brave-browser/assets/387249/dc804fac-ab23-41be-b113-53f19734544a">

## Expected result:

Unsure if it should switch to `Llama2-13b` or `Claude Instant`?

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.62.150 Chromium: 121.0.6167.85 (Official Build) (x86_64)
-- | --
Revision | c01f5cde4d5d5e41134c0ccdb1868acd80a64a34
OS | macOS Version 14.3 (Build 23D56)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Miscellaneous Information:

cc @bbondy @kjozwiak @mattmcalister @petemill @nullhook @rebron @brave/qa-team

**Comment by stephendonner** [comment]
also cc @nvonpentz @evq to keep them in the loop

**Comment by kjozwiak** [comment]
The above requires `1.62.153` or higher for `1.62.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.62.153 Chromium: 121.0.6167.85 (Official Build) (64-bit)
-- | --
Revision | e4a51346862f226aeee12c4589ccf03d43655857
OS | Windows 11 Version 22H2 (Build 22621.3085)
```

1. Installed 1.62.153
2. launched Brave
3. visited techcrunch.com
4. opened sidebar
5. clicked on Leo
6. clicked `Summarize this page`
7. clicked `Accept and begin`
8. queried with Leo (Mixtral, default)
9. hit the response rate limit
10. got the Response rate limit reached modal
11. clicked on Switch to the free model
12. clicked `Retry` 

#### Confirmed switched to `Llama 2 13b`
#### Confirmed when clicked `Retry` queried successfully

step 6| step 7| step 8 | step 10 | step 11 | step 12
---- | ----- | ----- | ----- | ----- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/f1f47095-c121-4cea-9b50-1d7b147bc4b7)|![image](https://github.com/brave/brave-browser/assets/98358127/aaf74ec6-81ac-4b15-a5e6-9cebce956a5a)|![image](https://github.com/brave/brave-browser/assets/98358127/52213ad4-c50f-4eb9-8250-d63da7885a88)|![image](https://github.com/brave/brave-browser/assets/98358127/2acd19ae-5a74-4e5d-bd29-44b2920c0c8b)|![image](https://github.com/brave/brave-browser/assets/98358127/29d47991-56d3-423c-97a1-9d6d03abfef8)|![image](https://github.com/brave/brave-browser/assets/98358127/dfbe4ccc-55a8-4d9d-9415-4e67a25ee81c)

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.62.153 Chromium: 121.0.6167.85 (Official Build) (x86_64)
-- | --
Revision | e4a51346862f226aeee12c4589ccf03d43655857
OS | macOS Version 11.7.10 (Build 20G1427)
```
