### ISSUE TITLE
Scrolling tabs doesn't work in the collapsed/minimized mode

### ISSUE THREAD

**Issue by K0-RR** [brave/brave-browser#35549]
## Description 

When vertical tabs are not in the expanded/fixed width mode you cannot scroll them

## Steps to Reproduce

   1. Switch to vertical tabs if not using them already
   2. Make sure you have more tabs than fit on the screen
   3. Switch between two mentioned vertical modes and try using the scroll wheel

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Brave	1.61.120 Chromium: 120.0.6099.234 (Official Build) unknown (64-bit) 
Revision	362207c81bff0740a8b6cff62dd91c6789f5698f
OS	Linux
JavaScript	V8 12.0.267.17

## Version/Channel Information:

- Can you reproduce this issue with the beta channel? Did not test
- Can you reproduce this issue with the nightly channel? Did not test

**Comment by rebron** [comment]
<img width="518" alt="Screenshot 2024-01-26 at 1 31 28 PM" src="https://github.com/brave/brave-browser/assets/5951041/909ce9a9-b6ca-4e6b-a985-4ef785c2ef02">
If you select that option in brave://settings/appearance does that work for you?

If I'm reading this right, I think there's a focus issue here where the expansion of the panel happens so you can't scroll before the panel expands. I'm thinking you might the want the panel always in collapsed mode and then expand it manually with the button.

**Comment by K0-RR** [comment]
Can't reproduce after updating the browser
