### ISSUE TITLE
Build out Composer UI Dynamic Token Background

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35559]
## Description 

We need to build out a reusable background component that parses the dominant color of a tokens image and then use that color as the background in the new `Composer` UI

https://github.com/brave/brave-browser/assets/40611140/82b1c46b-6d29-4d1f-8443-2c86d8ffcbd1

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.102 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | c9343c77bd5dee3524fc45f89721ce0bf4c09b8d
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from issue description and [brave/brave-core#21739](https://github.com/brave/brave-core/pull/21739)
- Verified dynamic token background changes on both Send and Swap tokens screen

https://github.com/brave/brave-browser/assets/17010094/91fa31ba-41de-4472-8601-08d34a280316
