### ISSUE TITLE
Update contribution banner for self-custody && creator no Web3 address state

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#35553]
## Description

In case where user is self-custody && creator does not have a Web3 address, use the following UI in the contribution banner.

Use this text instead:

>**Can't send your contribution** (keeping this string the same as other cases for now, for simplicity) 
>It looks like this creator isn't set up to receive contributions via Web3 wallets yet. 

![image](https://github.com/brave/brave-browser/assets/11497541/0c76c86d-a565-42b9-83b0-c35b7f0bcae8)

We should uplift this to 1.63.x.

**Comment by Miyayes** [comment]
This is a followup for the initial PR that includes self-custody. Should go into initial launch of the feature.

**Comment by kjozwiak** [comment]
The above requires `1.63.138` or higher for `1.63.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.63.138 Chromium: 121.0.6167.85 (Official Build) beta (64-bit)
-- | --
Revision | 742a3bdf71b710125a1c1dd8e89981b9009a87bc
OS | Windows 10 Version 22H2 (Build 19045.3930)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/21738#issuecomment-1914822293

**Steps:** 

1. Create profile using staging parameters
2. Close and relaunch to pull griffin
3. Enable flag
4. Join Rewards
5. Request paymentId be invited
6. Create Brave Wallet
7. Once you get invite, connect Brave Wallet to Rewards
8. Visit a site that is verified but does not have web3 contributions set up (ex. laurenwags.github.io)
9. Open contribution banner.
10. Confirm expected text as per [issue](https://github.com/brave/brave-browser/issues/35553#issue-2098770300) and screenshot from [PR description](https://github.com/brave/brave-core/pull/21738#issue-2099101666).
11. Visit a site that does have web3 contributions configured (ex. vimeo.com/batcommunity)
12. Open contribution banner.
13. Confirm banner shows a button to contribute via web3.

Step 10 | Step 13
--- | ---
![image](https://github.com/brave/brave-browser/assets/38657976/551f1ff1-7d96-4eac-b7a3-757e50437b9d) | ![image](https://github.com/brave/brave-browser/assets/38657976/0f0d3f1b-91e4-4aea-8d78-e567c8cde6b8)
