### ISSUE TITLE
[Leo] `Leo's` bottom sheet pop-up is refreshing when scrolling down

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#35557]
## Description 

`Leo's` bottom sheet pop-up is refreshing when scrolling down.

## Steps to reproduce 

   1. Launch Brave `1.62.152`
   2. Three-dot menu > Leo > Wait when the bottom sheet pop-up is opened
   3. Ask a few questions and receive the answers, so the page contains a lot of text, and you need to scroll to read it all
   4. Try to scroll through it > Observe the page refresh

## Actual result 

`Leo's` bottom sheet pop-up is refreshing when scrolling scrolling down. This is happening in both cases when the page contains and doesn't contain a scrollable text. Looks like it just trying to open `Leo` in full-screen mode.

https://github.com/brave/brave-browser/assets/128532965/8ecf9887-fdce-44d0-a397-d60ba0d3c671

## Expected result

`Leo's` bottom sheet pop-up must not refresh when scrolling down.

## Issue reproduces how often 

`Easily reproduced`

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NO (need to enable `ai-chat` flag)
- Can you reproduce this issue with the current Play Store Beta version? YES (need to enable `ai-chat` flag)
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): phone / tablet
   - Android version: Android 13 / 14
   
## Brave version

```
Brave build: 1.64.20 
Chromium: 121.0.6167.85 (Official Build) canary (64-bit) 
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by AlexeyBarabash** [comment]
Closing as fixed with https://github.com/brave/brave-core/pull/21927
