### ISSUE TITLE
Replace background images for new - blank tab

### ISSUE THREAD

**Issue by raisty** [brave/brave-browser#3556]
## Description 

I want to replace background images for a new tab.
Cannot find dksfotoX.jpg folder.

## Steps to Reproduce

   1. Open new tab
   2. The background image will appear if it is enabled
   3. Replace photos in the folder should be available

## Actual result:

Cannot find dksfotoX.jpg images

## Expected result:
Folder with image collections.

## Reproduces how often: 

Always

## Brave version (brave://version info)

0.59.34 Chromium: 72.0.3626.81 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?
Yes 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
Yes

**Comment by bsclifton** [comment]
cc: @karenkliu

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/5838 in which our designer @karenkliu is working on with @rebron
