### ISSUE TITLE
Download protection override flag doesn't work for DLLs

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#35561]
The warning override flag added in https://github.com/brave/brave-browser/issues/28917#issuecomment-1905940643 (`brave://flags/#brave-override-download-danger-level`) does not work for `.dll` files.

The reason is that the override [only targets `ALLOW_ON_USER_GESTURE` file types](https://github.com/brave/brave-core/pull/18877/files#diff-b23c92cda936620a60fa4d2e7f8bcd8eaf666b5569ad13c35dbb449793a70ca7) where `.dll` files return the [`DANGEROUS` danger level](https://source.chromium.org/chromium/chromium/src/+/main:components/safe_browsing/content/resources/download_file_types.asciipb;l=2199-2210;drc=0f85cf3e303cd3a9705466c217b0799ca56dc36a) instead:
```
  # Windows executable. It can gain control of an executable launched from the
  # same directory, so it can do bad things without ever being clicked on.
  extension: "dll"
  uma_value: 9
  ping_setting: FULL_PING
  platform_settings {
    platform: PLATFORM_TYPE_WINDOWS
    danger_level: DANGEROUS
    auto_open_hint: DISALLOW_AUTO_OPEN
  }
```
where `.exe` files return the [`ALLOW_ON_USER_GESTURE` danger level](https://source.chromium.org/chromium/chromium/src/+/main:components/safe_browsing/content/resources/download_file_types.asciipb;l=2233-2244;drc=0f85cf3e303cd3a9705466c217b0799ca56dc36a):
```
  # Executable
  extension: "exe"
  uma_value: 0
  ping_setting: FULL_PING
  platform_settings {
    platform: PLATFORM_TYPE_WINDOWS
    danger_level: ALLOW_ON_USER_GESTURE
    auto_open_hint: DISALLOW_AUTO_OPEN
    file_weight: 10
  }
```

Test page at https://fmarier.org/files/safebrowsing-test.html

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

```
Brave | 1.64.48 Chromium: 121.0.6167.139 (Official Build) nightly (64-bit)
-- | --
Revision | 741f7ee622bdfde5e10e3beda02288f3c056287e
OS | Windows 10 Version 22H2 (Build 19045.3996)
```

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.64.52 Chromium: 121.0.6167.139 (Official Build) nightly (x86_64)
-- | --
Revision | 74312201fe92e37ad0cae858c52ef03ef15f6e76
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.64.52`
2. launched Brave
3. loaded `https://fmarier.org/files/safebrowsing-test.html` 
4. set `Safe Browsing` to `No protection` in `brave://settings/security`
5. click on `test.dmg` and then Save. The download should be blocked and you should see the same warning in the download manager
6. clicked on `test.txt` and then `Save`. The download should succeed without any warnings
7. set `chrome://flags/#brave-override-download-danger-level` to `Enabled` and relaunched the browser.
8. repeated steps 4-7

### Confirmed all downloads succeeded without warnings

**Comment by btlechowski** [comment]
Verified with

Brave | 1.64.91 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 939586e20d208404b83713ea05cf5f6fa7fe3dd5
OS | Linux



### Steps:
1. installed `1.64.x`
2. launched Brave
3. loaded `https://fmarier.org/files/safebrowsing-test.html` 
4. set `Safe Browsing` to `No protection` in `brave://settings/security`

`confirmation dialog` | `No protection`
----------------------|----------------
![image](https://github.com/brave/brave-browser/assets/34715963/19593e4a-fad2-4597-835b-e102e0bae944)|![image](https://github.com/brave/brave-browser/assets/34715963/cc1e247b-167b-48d3-95a7-1bb036f5df73)



5. click on `test.deb` and then Save. The download should be blocked and you should see the same warning in the download manager.

`test.deb` | `Unsaved, with warning`
-----------|-------------------------
![image](https://github.com/brave/brave-browser/assets/34715963/afb2d360-0e4e-42b6-986f-8baa018f372e)|![image](https://github.com/brave/brave-browser/assets/34715963/4640edbd-5dd4-47bc-ba48-a3367b079aa1)




6. clicked on `test.sh` and then `Save`. The download should be blocked and you should see the same warning in the download manager.

`test.sh` | `Unsaved, with warning`
-----------|-------------------------
![image](https://github.com/brave/brave-browser/assets/34715963/c8ffbd6a-ffff-47c8-b917-8f6003e4d29a)|![image](https://github.com/brave/brave-browser/assets/34715963/29d611fc-6192-436e-95ff-5158955f0e7f)


7. clicked on `test.txt` and then `Save`.  The download should downloaded without any warnings.

`test.txt` | `Saved without issue`
-----------|-------------------------
![image](https://github.com/brave/brave-browser/assets/34715963/76b53c73-07a6-47a8-889c-652d7729f901)|![image](https://github.com/brave/brave-browser/assets/34715963/7027ea08-1374-4445-8566-d46f5ee5b19b)



9. set `chrome://flags/#brave-override-download-danger-level` to `Enabled` and relaunched the browser.

![image](https://github.com/brave/brave-browser/assets/34715963/13d607eb-22f1-4211-ae43-8fa73e975616)


10. repeated steps 5-7

### Confirmed all downloads succeeded without warnings

test.deb | test.sh | test.txt
---------|--------|---------
![image](https://github.com/brave/brave-browser/assets/34715963/56ee600f-9bc7-42b1-b463-4efa7d6ee031)|![image](https://github.com/brave/brave-browser/assets/34715963/b2780dbc-67b7-4691-8a87-c20d8e7b16ca)|![image](https://github.com/brave/brave-browser/assets/34715963/e9bda46c-6b06-4c28-bbac-c2c8c2a18cf8)
