### ISSUE TITLE
Testnet account should not be listed in Buy screen when using mainnet account

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#35564]
## Description 

Testnet account should not be listed in Buy screen when using mainnet account

## Steps to Reproduce

   1. Create Testnet accounts on Filecoin and Bitcoin
   2. Go to Buy screen
   3. Search for FIL on mainnet 
   4. Select account drop down shows both Mainnet and Testnet accounts
   5. Repeat the same for BTC
   6. Account dropdown shows both Mainnet and Testnet accounts

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/04f67e28-ad7a-43fc-8f4b-75a11609e692

## Expected result:
Should only show the Mainnet accounts when selecting Mainnet and similarly show only Testnet account when selecting Testnet

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.64.19 Chromium: 121.0.6167.85 (Official Build) nightly (64-bit)
-- | --
Revision | df0cc8fb071ee39fd74bcc4efeccd6b4aca33732
OS | Linux

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @supermassive @josheleonard @Douglashdaniel

**Comment by jamesmudgett** [comment]
Hide testnet accounts in buy flow for now, in the future we may want to label these as 'unsupported'

**Comment by kjozwiak** [comment]
The above requires `1.63.138` or higher for `1.63.x`  verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.63.141 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | aa92f6cecec7f6c576bd1cf120f4cf359d770159
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21764](https://github.com/brave/brave-core/pull/21764)
- Verified Bitcoin testnet is not shown in Buy screen

https://github.com/brave/brave-browser/assets/17010094/6a444aec-d58e-43c8-9942-be0ab1c9c777
