### ISSUE TITLE
[Follow up to #34910][Leo] `Leo's` language model always reset to the default one `Mixtral` when opening a new tab

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#35560]
## Description 

Follow-up to #34910

## Steps to reproduce 

   1. Launch Brave
   2. Visit any website, for example, https://chromeunboxed.com
   3. Three-dot menu > Leo
   4. Tap `Summarize this page` > Accept and begin > Confirm that summarize is done
   5. `Three-dot` menu on `Leo` page > Confirm that `Mixtral` is set by default
   6. Choose `Claude Instant` or `Llama 2 13b`
   7. On the website tap and hold any link > `Open in new tab` (or you can simply tap `+` and open another website)
   8. Open that tab > Three-dot menu > Leo 
   9. Three-dot menu on Leo's page > Observe it switched back to `Mixtral`

## Actual result 

`Leo's` language model always reset to the default one `Mixtral` when opening a new tab.

https://github.com/brave/brave-browser/assets/128532965/a6d6c130-ce9f-4de9-b076-015c187ae9f1

## Expected result

If a user selects non-default Leo's language model (`Claude Instant` or `Llama 2 13b`), it must not reset it to the default one `Mixtral` when switching or opening a new tab.

## Issue reproduces how often 

`Easily reproduced`

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? YES
- Can you reproduce this issue with the current Play Store Beta version? YES
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Any
   - Android version: Android 13 / 14
   
## Brave version

```
Brave build: 1.64.20 
Chromium: 121.0.6167.85 (Official Build) canary (64-bit) 
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.63.147` or higher for `1.63.x` verification 👍 As per https://github.com/brave/brave-browser/issues/35560#issuecomment-1927230523, we basically need to ensure that there's a way to change the default model via browser settings.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.63.148 Chromium: 121.0.6167.164 (Official Build) beta (64-bit) 
Revision	c68893a5f2bbf2898967a976b21b3fe5d581f714
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Verified STR in https://github.com/brave/brave-browser/issues/35560#issue-2099324570
- Verified selected model will not change if user stays in the same tab. 
- Verified opening another tab and starting conversation will use model corresponding to default model selected in Leo settings.
- Verified starting new chat using `New chat` icon retains the selected ai model. 

Settings | Selecting model in chat | interacting with Leo | linking another link in tab
-|-|-|-
![Screenshot 2024-02-09 at 6 23 40 PM](https://github.com/brave/brave-browser/assets/17885425/47d0252b-1218-4b5e-8455-e0f20d64b9c0) | ![Screenshot 2024-02-09 at 6 24 26 PM](https://github.com/brave/brave-browser/assets/17885425/e57d44ba-b3b9-4e30-b977-dd734c9d1e7b) | ![Screenshot 2024-02-09 at 6 24 43 PM](https://github.com/brave/brave-browser/assets/17885425/0ae2beb0-6026-4140-bbc7-2834b216d013) | ![Screenshot 2024-02-09 at 6 24 58 PM](https://github.com/brave/brave-browser/assets/17885425/2e5f31d0-27ca-41c4-b618-b77f9817c0e3)
