### ISSUE TITLE
`Add current tab` button is disabled when opening the Bookmarks side panel

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#35563]
## Steps to Reproduce

   1. Load any tab that is not added yet to bookmark
   2. Open bookmarks side panel
   3. Check Add current tab button enabled state in panel

## Actual result:

Disabled

## Expected result:
`Add current tab` should be enabled

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Reported to upstream - https://bugs.chromium.org/p/chromium/issues/detail?id=1521177
and it's fixed in cr122

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```

Brave | 1.64.48 Chromium: 121.0.6167.139 (Official Build) nightly (x86_64)
-- | --
Revision | 741f7ee622bdfde5e10e3beda02288f3c056287e
OS | macOS Version 11.7.10 (Build 20G1427)
```

Followed the inline steps to reproduce.

### Confirmed `Add current tab` button was enabled and added current `att.com` tab to `Bookmarks`

example | example | example
---------|----------|---------
<img width="1178" alt="Screen Shot 2024-02-05 at 9 37 19 AM" src="https://github.com/brave/brave-browser/assets/387249/45e68309-309d-4fc9-b910-62cd63b2254b"> | <img width="1178" alt="Screen Shot 2024-02-05 at 9 37 22 AM" src="https://github.com/brave/brave-browser/assets/387249/5f414748-6aae-41a3-b17a-3c582407e491"> | <img width="1178" alt="Screen Shot 2024-02-05 at 9 37 43 AM" src="https://github.com/brave/brave-browser/assets/387249/b28a6d45-2209-49e3-b165-b174d253c997">
