### ISSUE TITLE
Include synced history entries into P3A

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#35579]
Currently `Brave.Sync.SyncedObjectsCount` P3A metric  doesn't include statistic for History, because `SyncServiceImpl::GetEntityCountsForDebugging` doesn't include that.

History is the most consuming datatype and it is vital to know the statistics.

**Comment by kjozwiak** [comment]
The above requires `1.62.165` or higher for `1.62.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung galaxy version 12` running `Bravemonoarm64.apk_1.62.165`

**Comment by GeetaSarvadnya** [comment]
@AlexeyBarabash As per my discussion with @deeppandya we can't verify `brave://inspect/#extensions` on Android hence we will not be able to verify the steps 3 to 7 (from https://github.com/brave/brave-core/pull/21623) on Android. Hence we are skipping the steps 3-7 verification on Android. Let us know if you know any alternatives I can verify from end.

cc: @kjozwiak @LaurenWags

**Comment by AlexeyBarabash** [comment]
@GeetaSarvadnya 
This is fine to verify on Desktop only.
There is no way to make good test plan on Android.

thanks.
