### ISSUE TITLE
Fix buy and deposit screen token display ordering

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#35575]
## Description 

Gas assets were not all grouped together on "buy" screen and NFTs with similar names were not grouped together.

## Steps to Reproduce

Scenario 1:
   1. Go to buy screen in wallet
   2. observe order of assets
   3. gas assets should all be first in the list

Scenario 2:
   1. Go to deposit screen in wallet
   2. observe order of assets
   3. main-net gas assets should all be first in the list, followed by:
     - all BAT tokens
     - other fungible tokens
     - NFTs (with token id removed from the name to group related tokens)
     -  test-net assets for added test networks

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.102 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | c9343c77bd5dee3524fc45f89721ce0bf4c09b8d
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified seps from issue description
- Verified on Buy screen, Gas assets are listed first 
- Verified on Deposit screen, Mainnet token is listed first, all BAT tokens next, followed by other tokens, NFTs and finally testnet tokens

https://github.com/brave/brave-browser/assets/17010094/5a67caf1-6874-4d7c-bfeb-c9a973292fec
