### ISSUE TITLE
Remove `View on block explorer` menu item from token details screen 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#35571]
## Description 

Remove `View on block explorer` menu item from token details screen 

## Steps to Reproduce

   1. Open Bitcoin token
   2. Click on the menu item next to the account name
   3. Shows `View on block explorer` which shouldn't be there
   4. Clicking it shows an error message

## Actual result:

![image](https://github.com/brave/brave-browser/assets/17010094/eab391e9-1a0c-4727-a275-3d48caafa8b2)

## Expected result:
Shouldn't have the entry for `View on block explorer`

## Reproduces how often: 
Easy

## Brave version (brave://version info)

Brave | 1.64.19 Chromium: 121.0.6167.85 (Official Build) nightly (64-bit)
-- | --
Revision | df0cc8fb071ee39fd74bcc4efeccd6b4aca33732
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @supermassive

**Comment by kjozwiak** [comment]
The above requires `1.63.138` or higher for `1.63.x`  verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.63.141 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | aa92f6cecec7f6c576bd1cf120f4cf359d770159
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21764](https://github.com/brave/brave-core/pull/21764)
- Verified block explorer is not available in bitcoin account page
![image](https://github.com/brave/brave-browser/assets/17010094/26b83c30-8324-4957-9f88-724c8970e83a)
