### ISSUE TITLE
Update Buy Send Swap Deposit Buttons Border Radius

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35583]
## Description 

We need to update the `Buy/Send/Swap/Deposit` buttons `border-radius` to the updated designs in `figma`

![Screenshot 44](https://github.com/brave/brave-browser/assets/40611140/bab8451a-617c-499c-8994-2e4c37aaf988)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21755](https://github.com/brave/brave-core/pull/21755)
- Verified Buy/Send/Swap/Depoist buttons on panel have border raidus and shows a square button
![image](https://github.com/brave/brave-browser/assets/17010094/cc407578-15f2-495f-9878-d210be8e58f6)
