### ISSUE TITLE
Yubikey doesn't work with Brave

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#3558]
## Description 
Login with U2F keys on Github or Google doesn't work
<img width="433" alt="screen shot 2019-03-03 at 4 04 29 pm" src="https://user-images.githubusercontent.com/1903815/53704118-54fdfe80-3dce-11e9-894d-5e2110e8987a.png">

## Steps to Reproduce
   1. Setup U2F with Github/Google account using a yubikey
   2. Login with U2F keys

## Actual result:
Login doesn't work

## Expected result:
Login should work

## Reproduces how often: 
Easily

## Brave version (brave://version info)
0.62.15 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Dev

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? Not on Chrome and Chrome Canary

**Comment by rebron** [comment]
cc: @kjozwiak to reproduce

**Comment by kjozwiak** [comment]
Reproducible on `0.61.x` as well. I went through both GitHub/Google using `macOS 10.14.3` with the following build:

Brave | 0.61.45 Chromium: 73.0.3683.39 (Official Build) beta(64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Mac OS X

**_Examples of the issue occurring on Google when attempting to add a key as authentication:_**

Chrome | Brave
:-------------------------:|:-------------------------:
<img width="300" alt="screen shot 2019-03-05 at 5 30 18 pm" src="https://user-images.githubusercontent.com/2602313/53843978-405a6b80-3f72-11e9-9335-695d6c4da2d2.png">  | <img width="300" alt="screen shot 2019-03-05 at 5 33 55 pm" src="https://user-images.githubusercontent.com/2602313/53844541-04280a80-3f74-11e9-9e9e-1dbc848563de.png">

**_Examples of the issue occurring on Google when attempting to login using an account with a key:_**

<img width="300" alt="screen shot 2019-03-05 at 5 31 34 pm" src="https://user-images.githubusercontent.com/2602313/53844025-6da71980-3f72-11e9-92ea-e2c6ee36ffee.png">

**_Examples of the issue occurring on GH when attempting to add a key as authentication:_**

<img width="863" alt="screen shot 2019-03-05 at 6 06 00 pm" src="https://user-images.githubusercontent.com/2602313/53844673-7862ae00-3f74-11e9-9178-9c14e063983e.png">

**_Examples of the issue occurring on GH when attempting to login using an account with a key:_**

<img width="429" alt="screen shot 2019-03-05 at 6 08 49 pm" src="https://user-images.githubusercontent.com/2602313/53844696-8284ac80-3f74-11e9-9cba-24d4b1418675.png">

Looks like adding or attempting to login using a isn't working under `0.61.x`. CCing @rebron @bbondy.

**Comment by kjozwiak** [comment]
Something to keep in mind. Chrome BETA is currently on `73.0.3683.56` and we're on `73.0.3683.39`. Entirely possible that the above issue might have been fixed between those two CR versions.

@bbondy should we bump to `73.0.3683.56` as well?

**Comment by kjozwiak** [comment]
Bumping CR https://github.com/brave/brave-browser/issues/3594. Will retest once we get new builds.

**Comment by kjozwiak** [comment]
Bumping CR again via https://github.com/brave/brave-browser/issues/3608. Will retest when we get new builds which includes `73.0.3683.67`.

**Comment by corymcdonald** [comment]
Is this the same issue as #1875?

**Comment by kjozwiak** [comment]
> Is this the same issue as #1875?

Most likely related. Attempted to go through the case mentioned in #1875 and receiving an `Operation Cancelled` right off the bat. Looking into the console, I see the following:

```
getClientExtensionResults failed TypeError: Cannot read property 'getClientExtensionResults' of null main.js?e13936b19f427d7ade29:1 
    at main.js?e13936b19f427d7ade29:1
    at main.js?e13936b19f427d7ade29:1
```

Example of https://demo.yubico.com/webauthn/ under Brave:

<img width="933" alt="screen shot 2019-03-07 at 7 53 56 pm" src="https://user-images.githubusercontent.com/2602313/53999794-cdd4c180-4112-11e9-956f-2a46611c8181.png">

Example of https://demo.yubico.com/webauthn/ under Chrome BETA:

<img width="860" alt="screen shot 2019-03-07 at 7 53 21 pm" src="https://user-images.githubusercontent.com/2602313/53999813-de853780-4112-11e9-987d-714e433cbce7.png">

I also tried using Google/Github and received the same results using the following build:

Brave | 0.61.49 Chromium: 73.0.3683.67 (Official Build) (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Mac OS X

@rebron @bbondy @bsclifton doesn't seem like the CR bump addressed the issue. We'll need to fix this ourselves.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.3 x64` using the following build:

Brave | 0.61.50 Chromium: 73.0.3683.67 (Official Build) (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Mac OS X

* Added a yubikey under Gmail using `0.61.50` and logged in without issues using the same key
* Added a yubikey under GitHub using `0.61.50` and logged in without issues using the same key
* Went through https://demo.yubico.com/webauthn/ and ensured I can register and login using yubikey

**Comment by aptly-io** [comment]
I cannot get to work U2F
On MacOS 10.14.6, Brave V1.14.84, Chromium to 85.0.4183.121
OnlyKey Firmware v0.2-beta.8c
It is as if the device does not get recognised.
It works with Firefox (it does not work on safari)

**Comment by jumde** [comment]
@aptly-io - Does the key work with Google Chrome?

**Comment by aptly-io** [comment]
@jumde Sorry, It started working without any obvious changes (I only installed Google Chrome to test as you asked)

**Comment by jumde** [comment]
@aptly-io - That's weird, glad it's working now. If you run into this issue again, feel free to file a new issue. In the meantime, I'll try getting a `OnlyKey` to test.
