### ISSUE TITLE
Add support for Trezor Safe 3 / Bump Trezor Connect v8 up to v9

### ISSUE THREAD

**Issue by brianddk** [brave/brave-browser#35584]
> Trezor Safe 3 + Brave wallet ?

>Does the Brave wallet work with Trezor Safe 3 like Metama$k?

My guess is NO.  They are using TrezorConnect version 8, and I'm guessing that Trezor-3 support was introduced in version 9.  Likely why they deprecated version 8 last year.  The following deprecation warning appears on the Connect page.

> Connect v8 is deprecated. Please ask your DeFi platform/wallet developers (not Trezor) to update to Connect v9.

Someone either needs to log an issue on github, or see if support can come on thread and address it here.

https://github.com/brave/brave-core/blob/master/package.json#L155

Looks like T1 and TT both work, but I'm betting T3 will fail.

* https://www.reddit.com/r/brave_browser/comments/19fal49/trezor_safe_3_brave_wallet/
* https://github.com/brave/brave-core/blob/master/package.json#L155

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.95 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 6f4193fbcee7c358ae3684f777faa9f12e52206e
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21861](https://github.com/brave/brave-core/pull/21861)
- Verified able to connect Trezor Safe 3, Trezor One
- Verified when using Trezor redirects to `https://connect.trezor.io/9/`
- Verified able to submit transactions via Trezor Safe 3
- Encountered [#36575](https://github.com/brave/brave-browser/issues/36575)

https://github.com/brave/brave-browser/assets/17010094/2fa2ae88-f23d-4fae-ba95-6f1f5683209c
