### ISSUE TITLE
closing translation drop down confuses state

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#35589]
## Description 

I noticed today closing the translation drop-down reverted the page to the original language. More confusing, opening the drop-down again the controls show the page as still translated and one must manually switch to the detected language and back again to re-activate the translation.

## Steps to Reproduce

   1. Visit https://www.jaxa.jp/press/2024/01/20240125-4_j.html
   2. Switch the page from Japanese to English
   3. Wait for translation to process
   4. Click the close box on the translation control
   5. After a few seconds the page reverts to Japanese
   6. Click the translation icon in the address bar to re-open the controls

## Actual result:

Page is in Japanese while controls say it is in English

## Expected result:
Page should stay translated and control should correctly reflect the translation state.

## Reproduces how often: 

Well, I reproduced it a couple of times on Nightly, but not on Release or Beta. Now I can't reproduce on Nightly either. Will update if I see it again.

## Brave version (brave://version info)

1.64.17 Chromium: 121.0.6167.85 (Official Build) nightly (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

This is on Fedora Linux 39 x86_64.

**Comment by rebron** [comment]
Cool article. I couldn't reproduce. I scrolled and got the rest of the translations towards the bottom of the page. We're translating on the go, what's in view, versus the whole doc in one go so maybe that was it?

**Comment by rillian** [comment]
I think it must have been. Sorry for the confusion, glad you enjoyed the article. :)
