### ISSUE TITLE
aichat: conversation entry context menu should open with long press on android

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#35587]
the Assistant's context menu is currently accessed by pressing the kebab menu, which doesn't scale well on mobile. 

an ideal interaction would involve displaying the context menu with a long press.

https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Leo-MVP?type=design&node-id=4729-36287&mode=design&t=5LpTjdLSyLW8lHbp-0

**Comment by stephendonner** [comment]
Logged https://github.com/brave/brave-browser/issues/36089 while testing this for uplift.

**Comment by kjozwiak** [comment]
The above requires `1.63.156` or higher for `1.63.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

```
1.63.156, Chromium 122.0.6261.43`
```

### Steps:
1. installed `1.63.156`
2. launched Brave
3. loaded `rt.com` (or any webpage)
4. tapped on the vertical 3-dots `...` menu
5. tapped on `Leo`
6. opted-in to Leo
7. tapped `Summarize this page`
8. waited for the generated response
9. long-tapped/long-pressed
10. chose `Dislike answer` (confirmed other options: `Copy` and `Like answer` worked, as well; not pictured)
11. tapped `Add feedback`
12. chose `Other` from the dropdown
13. tapped the `Provide feedback here` pre-filled text
14. entered and submitted feedback

example | example | example | example | example | example | example | example
---------|----------|---------|----------|---------|----------|----------|---------
![Screenshot_20240216-095906](https://github.com/brave/brave-browser/assets/387249/dd8493d0-9d35-41ba-bf0f-064d05fb64cc) | ![Screenshot_20240216-095922](https://github.com/brave/brave-browser/assets/387249/ed33a3ad-6b75-41a0-953f-fda3fe63733c) | ![Screenshot_20240216-095935](https://github.com/brave/brave-browser/assets/387249/d9e8b4a2-0d23-4510-891c-a04c66cc03a8) | ![Screenshot_20240216-095952](https://github.com/brave/brave-browser/assets/387249/00b780ab-643d-4bd6-b940-35d4299cf27e) | ![Screenshot_20240216-100001](https://github.com/brave/brave-browser/assets/387249/f236cbea-32d2-46ad-81af-2d5fee6e7bfc) | ![Screenshot_20240216-100022](https://github.com/brave/brave-browser/assets/387249/16001d9a-710e-482a-9c20-72b028bdd249) | ![Screenshot_20240216-100149](https://github.com/brave/brave-browser/assets/387249/9afb166e-e18e-4b7f-81fd-3e5d7544320c) | ![Screenshot_20240216-100209 (1)](https://github.com/brave/brave-browser/assets/387249/0e601752-3798-4795-8e01-9e1a3237dffd)


### Note: logged https://github.com/brave/brave-browser/issues/36166 while I was in the "neighborhood."
