### ISSUE TITLE
Add support for Brave Wallet in private tabs

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#35585]
Review https://github.com/brave/reviews/issues/1145

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.65.103 Chromium: 123.0.6312.105 (Official Build) beta (64-bit)
-- | --
Revision | 3e302d692c9b2446693d24f6808940175ee263d1
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from [brave/brave-core#21756](https://github.com/brave/brave-core/pull/21756)
- Verified new setting for `Enable Brave Wallet in Private Windows.` is available under `brave://settings/web3` and set to off by default
- Verified when setting is off, loading `brave://wallet` in a private tab redirects to normal tab
- Verified after enabling the setting, opening a private tab able to navigate to `brave://wallet` and wallet panel is also enabled on private window
- Verified when connecting wallet to Dapp, there is only one permission option `Until I close the window` is available and no other option is available
- Verified permission is reset when the tab is closed but persists in a new tab until the private window is open
- Verified permission set in private window are completely partitioned from permission set in regular window and there is no leakage of permission
- Verified permission set for private window is removed under `brave://settings/content/ethereum` and `brave://settings/content/solana` when private window is closed
- Verified permissions set in private window shows the private window icon in `brave://settings/content/ethereum` and `brave://settings/content/solana`
- Verified able to connect hardware wallets via private window
- Verified able to sign via hardware wallets when connected on private window. 
- Encountered [#37172](https://github.com/brave/brave-browser/issues/37172)

https://github.com/brave/brave-browser/assets/17010094/254fb13e-0926-44c0-878a-5938c4b8bc7c
