### ISSUE TITLE
Alternative layout for brave news

### ISSUE THREAD

**Issue by Goldman90** [brave/brave-browser#35599]
Sorry if this is wrongly written, i searched but couldn't find and issue refering to this.
There should be a more UX frendly layout for brave news, as, right now, they are only presented as a column. wasting a lot of screen real state, and making looking at it take a lot more time.
Also, an option for not having to scroll to start seeing brave news would be helpful.
if you want an example, MS's Edge new tab would be helpful.

**Comment by rebron** [comment]
hi @Goldman90 We have one rolling out but you can try it now brave://flags/#brave-news-feed-update

**Comment by Goldman90** [comment]
> hi @Goldman90 We have one rolling out but you can try it now brave://flags/#brave-news-feed-update

yeah, i tried it before posting my issue. It's a lot better, but it's still a single column, so most of what i pointed out still stands

**Comment by Goldman90** [comment]
Just to know, why was this closed/set to wont fix?
