### ISSUE TITLE
VPN connection should default to WireGuard protocol in Nightly

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#35590]
## Description 

Found while verifying the PR https://github.com/brave/brave-core/pull/20754. After logging into VPN as an existing user (Or new subscriber) and connecting to VPN in nightly (1.63.x), the connection is not defaulted to WireGuard instead it's defaulting IKEv2 protocol.  Not seeing WireGuard tray icon either.

## Steps to Reproduce

1. Install 1.64.23 
2. launched Brave
3. open  services.msc via Win + R
4. `BraveNightlyElevationService` shown
5. log into account.bravesoftware.com using existing VPN subscription
6. click Refresh Brave VPN 
7. refresh services.msc and verify below two new services
     - Brave Nightly Vpn Service (BraveNightlyVpnService)
    - Brave Nightly VPN Wireguard Service (BraveNightlyVPNWireguardService)
10. close services.msc
11. connect to VPN  
12. open brave://settings/system in a new tab

## Actual result:

`Use WireGuard protocol in Brave VPN` toggle is disabled 

example | example
----- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/16302791-e863-4cec-8113-c45af0af74ba)|![image](https://github.com/brave/brave-browser/assets/98358127/7bf7866d-623c-4344-9e8c-e35219b351b6)

## Expected result:
`Use WireGuard protocol in Brave VPN` toggle should be enabled by default and 
Should display Wireguard tray icon

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.64.23 Chromium: 121.0.6167.85 (Official Build) nightly (64-bit)
-- | --
Revision | 86733c0da106f02bb3f33a826abd5be0c4c1a2ad
OS | Windows 11 Version 22H2 (Build 22621.3085)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@bsclifton 
cc: @stephendonner @kjozwiak @LaurenWags

**Comment by stephendonner** [comment]
Also confirmed using

```
Brave | 1.64.24 Chromium: 121.0.6167.85 (Official Build) nightly (64-bit)
-- | --
Revision | 9c0d36bebeb1607ff0e2bf29b89f77bfe19a1a0e
OS | Windows 10 Version 22H2 (Build 19045.3996)
```

![image](https://github.com/brave/brave-browser/assets/387249/6faf895e-41e7-43a2-bf17-b92215584202)

**Comment by simonhong** [comment]
I suspect that this settings option is configured initially with the wireguard system service installation state.
However, we only install wg services after user purchased. Maybe we have to change that option value after purchased.

**Comment by stephendonner** [comment]
Not a hard dependency, but makes sense to probably verify in the following order, to reduce duplicate work and the chance of missing something by testing it too early:
* https://github.com/brave/brave-browser/issues/35681
* https://github.com/brave/brave-browser/issues/35590
* https://github.com/brave/brave-browser/issues/33726

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```

```

### Steps:
1. Install 1.64.23
2. launched Brave
3. open services.msc via Win + R
4. BraveNightlyElevationService shown
5. log into account.bravesoftware.com using existing VPN subscription
6. click Refresh Brave VPN
7. refresh services.msc and verify below two new services
8. Brave Nightly Vpn Service (BraveNightlyVpnService)
9. Brave Nightly VPN Wireguard Service (BraveNightlyVPNWireguardService)
10. close services.msc
11. connect to VPN
12. open brave://settings/system in a new tab

**Comment by stephendonner** [comment]
Leaving open for a `Win11-x64` verification /cc @MadhaviSeelam

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.64.94 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 866e3a4bd76c9cc1762928df0cf9a53b8685ab71
OS | Windows 11 Version 23H2 (Build 22631.3155)
```
Verified using my original STR from the description

- Confirmed `Use WireGuard protocol in Brave VPN` settings is enabled 
- Confirmed Wireguard tray icon is shown with connected status


example | example | example | example 
--- | ---- | ---- | ----
<img width="857" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f2a7d634-8f00-456a-901e-309ce8b86140">|<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/65bc382a-8c75-4c07-8e6b-5bf9c3f9b4b4">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/feb46c92-10c1-4750-8b97-0516bd60cdd7">|<img width="952" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/53a97f92-82db-4e24-8332-ab91e8f3db9e">
