### ISSUE TITLE
Uplift new Leo icons to Release channel

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#35591]
## Description 
Icons have been updated in Nightly in the Sidebar, brand bar and chat UX as per https://github.com/brave/brave-browser/issues/35087

<img width="519" alt="image" src="https://github.com/brave/brave-browser/assets/71029/9be78670-1af8-4811-82f0-e7b7fac437df">

**Comment by kjozwiak** [comment]
Going to remove the above from the `1.62.x` milestones as it's not `release/blocking` and we haven't received any PRs. If we want to get this fixed/uplifted, please create an uplift and the above will get moved into the appropriate milestone once uplifted/merged.

**Comment by nullhook** [comment]
@fallaciousreasoning do you know which nala bump pr changed to the new Leo icon? i think that might need an uplift to release.
