### ISSUE TITLE
Remove unnecessary "edit" dialog after adding a bookmark

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#35594]
## Description 

Part of the Chromium bookmarks "upgrades", there is now an additional dialog box that appears after adding a bookmark, that only says you've added the bookmark and has `Edit` and `Done` options on it. 

![image](https://github.com/brave/brave-browser/assets/3299098/72f36c83-c97c-4f4c-be30-24fa7109b6a0)

Clicking `Edit` reveals the edit bookmark drop-down that is what previously appeared after adding a bookmark. This additional dialog doesn't provide any value to us and only requires additional work for the users. I suggest we remove this entirely and revert to the old behavior.

Community thread on the issue:
https://community.brave.com/t/editing-name-and-folder-of-new-bookmarks/528195

**Comment by Brave-Matt** [comment]
+1 https://community.brave.com/t/the-new-way-to-select-bookmark-folders-when-bookmarking-a-website/528186

**Comment by mpql** [comment]
A temporary work-around is to paste `chrome://flags/#simplified-bookmark-save-flow` into your address bar and set the highlighted setting, "**Simplified Bookmark Save Flow**" to `Disabled`.

I say "*temporary*" because these settings are removed sometimes.

**Comment by Ryan-Porter66** [comment]
That workaround works for now.

Hopefully, this can get addressed quickly - Edge still has this functionality.
A lot of good features have been changed for the worse lately.

**Comment by JunkiEDM** [comment]
> A temporary work-around is to paste `chrome://flags/#simplified-bookmark-save-flow` into your address bar and set the highlighted setting, "**Simplified Bookmark Save Flow**" to `Disabled`.

Unfortunately temporary didn't last very long, this flag is gone in the nightly branch.
For the meantime I guess a janky workaround could be to triple-click the bookmark button until a proper fix.

**Comment by Ryan-Porter66** [comment]
Any new workaround(s) since the flag is now gone from normal build, or is this more Chromium "QoL updates" that just regresses everything like normal?

**Comment by HugoPerseval** [comment]
> Any new workaround(s) since the flag is now gone from normal build, or is this more Chromium "QoL updates" that just regresses everything like normal?

I downloaded the old update 121.1.63.154, and moved the files of this update to the brave folder, and forbade installing the update through another program.

**Comment by JcynR** [comment]
I just received the latest update and that option is now gone unfortunately! Very annoying, Brave should address this because I bookmark A LOT and the extra click to edit it is very annoying.

**Comment by zhaoruibing** [comment]
Really hope this could be fixed. In the meantime,

**Workaround 1: use a bookmark extension instead, like [Bookmark Plus](https://chromewebstore.google.com/detail/bookmark-plus/kcipcflegclplnkpbijedkhgljodgfcp).**
Downside is the shortcut won't be Ctrl+D.


**Workaround 2: downgrade and hold at v1.62.165.**
_WARNING_: not using the latest version implies security risks.
1. Download [Release v1.62.165](https://github.com/brave/brave-browser/releases/tag/v1.62.165)
2. Uninstall Brave, select keep browser data.
3. Install Release v1.62.165.
4. Set flag `brave://flags/#simplified-bookmark-save-flow` to 'Disabled'.
5. [Disable Brave auto update](https://community.brave.com/t/how-do-i-disable-auto-update/171152/4) with `--disable-auto-update` runtime flag.
6. Relaunch Brave.
7. (Remember to undo the above when Brave fixes this issue.)

**Comment by Saoiray** [comment]
@bsclifton and @rebron Some have opened a Chromium ticket at https://issues.chromium.org/issues/41496433 but from what I'm seeing, this was an upstream change and they intentionally moved flag out of the browser. Curious to see if they see this as a wontfix. 

There are a moderate amount of people complaining on this change. But guess big question is, what's the priority for this compared to everything else? Would I be correct in thinking this is pretty much something that needs to be resolved upstream and unlikely to get much attention here downstream with Brave?

**Comment by rebron** [comment]
@Saoiray Thanks for the pointer to the chromium issue. My preference is the previous UI is well. We'll need to take a look to see how much effort it is to maintain the old dialog.

**Comment by rebron** [comment]
Per @mkarolin, it sounds like we can "auto press" the Edit button here and get us into the next/proper dialog. 
cc: @simonhong wdyt?

**Comment by Saoiray** [comment]
Awesome. I'm sure a lot of people will be happy if this can be implemented. Thanks for looking into it.

**Comment by kjozwiak** [comment]
The above requires `1.63.172` or higher for `1.63.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.63.174 Chromium: 122.0.6261.128 (Official Build) (64-bit)
-- | --
Revision | 0d369d4e1dfee7bcea82774079dc8cd658746c98
OS | Windows 10 Version 22H2 (Build 19045.4046)
```
