### ISSUE TITLE
Update Portfolio Action Buttons Border Radius

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35592]
## Description 

We need to update the `Portfolio Action` buttons `border-radius` to the updated designs in `figma`

![Screenshot 45](https://github.com/brave/brave-browser/assets/40611140/28ac0f59-f7e1-49bb-b148-874f4d6e6b71)

![Screenshot 46](https://github.com/brave/brave-browser/assets/40611140/a0c9266f-b035-434d-8f33-8a9e044e787d)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21757](https://github.com/brave/brave-core/pull/21757)
- Verified Portfolio action buttons have border raidus now and shows a square button
![image](https://github.com/brave/brave-browser/assets/17010094/c299c88f-9684-4960-8f79-0cf91ec297c3)
