### ISSUE TITLE
Implement Sync UI

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#356]
Once @AlexeyBarabash is done with the sync functionality, he will pass this to @cezaraugusto for making the UI use React/Redux and match browser-laptop's look.

**Comment by bsclifton** [comment]
`browser-laptop` implementation available here:
https://github.com/brave/browser-laptop/pull/13197

Important issues to consider when implementing (we can create separate issues for these):
- sync v2: Add first-use wizard dialogs https://github.com/brave/browser-laptop/issues/12269
- after sync reset, devices are not visible anymore if you try to re-sync https://github.com/brave/browser-laptop/issues/13258
- sync v2: finish total sync-chain removal feature https://github.com/brave/browser-laptop/issues/12364
- sync should clear clipboard data after 30s https://github.com/brave/browser-laptop/issues/13359

**Comment by cezaraugusto** [comment]
task is completed so closing

**Comment by bradleyrichter** [comment]
@cezaraugusto the beta build appears to have Sync v1 in it. Where is the new V2 hiding?

**Comment by srirambv** [comment]
@bradleyrichter @cezaraugusto Should the verification be done against the current V1 UI or should we wait until V2 UI is implemented? 

cc: @bbondy @rebron @kjozwiak

**Comment by cezaraugusto** [comment]
since we want to sync v2 to land in 0.58.x I'd wait for it

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Mac OS X
