### ISSUE TITLE
Sync the default state of the adblock features in the code with Griffin

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#35603]
A lot of adblock features are enabled only via Griffin, but not in the code. It hides the feature impact from unit/browser/perf tests and makes harder to compare a local build vs a production one.
 
The list: https://griffin.brave.com/?search=adblock

An example:
https://github.com/brave/brave-browser/issues/35602#issuecomment-1911706553

Steps:
* change the code default to match the Griffin for launched features;
* limit the Griffin exp setting `max_version` to make the study finished.

**Comment by antonok-edm** [comment]
also removed `BraveAdblockCosmeticFilteringChildFrames` from the code in https://github.com/brave/brave-core/pull/16626, so let's remove that from Griffin.
