### ISSUE TITLE
Remove "no custodian in region" state UI

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#35615]
## Description

Remove this state. Users should just use the normal Rewards UI. For now, users in regions without any provider will go through the connect flow, but all their options will just be grayed out.

![image](https://github.com/brave/brave-browser/assets/11497541/c042ead5-20e7-451e-af97-8b70d997ea84)

**Comment by Miyayes** [comment]
Users will instead see this if they go through the "Connect" flow.
![image](https://github.com/brave/brave-browser/assets/11497541/52434d1c-9542-46fc-8d8a-5730db547027)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.65.88 Chromium: 123.0.6312.58 (Official Build) beta (x86_64) 
Revision	e260e641e7db9e88b9b51112f4f00febf5a2f5eb
OS	macOS Version 13.6.4 (Build 22G513)
```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRES** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.65.96`
