### ISSUE TITLE
rewards-internals says "Rewards profile not yet created" even though it was created

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#35617]
## STR

How I reproduced:

1. Fresh profile against staging
2. Enable Rewards, select `DE`
3. Navigate into brave://rewards-internals
4. Observe custodial account connection info section

![image](https://github.com/brave/brave-browser/assets/11497541/5ce654af-8630-4e2d-89b8-08ff03c4f374)

`1.64.23 Chromium: 121.0.6167.85 (Official Build) nightly (x86_64) `

**Comment by LaurenWags** [comment]
Reproduced with `1.63.145 Chromium: 121.0.6167.139`:

<img width="435" alt="Screenshot 2024-02-05 at 12 05 47 PM" src="https://github.com/brave/brave-browser/assets/28145373/23d42a4f-b788-44d4-93a4-f800baeb0a8b">

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (x86_64)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | macOS Version 13.6.4 (Build 22G513)
```
