### ISSUE TITLE
Bold San Francisco (-apple-system) at 14px looks blurred on macOS + Brave Nightly

### ISSUE THREAD

**Issue by brunnopleffken** [brave/brave-browser#35610]
## Description 

Since a few weeks ago, on macOS (Apple Silicon) + Brave Nightly, the bold San Francisco font (-apple-system) looks blurred. Changing the font size (using the DevTools) from 14px to 15px or 13px makes the issue disappear.

Below, I have a sample of Brave and Vivaldi, both Chromium-based browsers. Look at the commit message.

Brave:
<img width="106" alt="Screenshot 2024-01-20 at 11 54 38" src="https://github.com/brave/brave-browser/assets/3427344/5303b854-cfff-4be1-9d12-d3f22bd62543">

Vivaldi:
<img width="106" alt="Screenshot 2024-01-20 at 11 55 37" src="https://github.com/brave/brave-browser/assets/3427344/61b0c591-dc27-437b-91f6-aa857471fc92">

## Steps to Reproduce

   1. Open GitHub's commit list (e.g. https://github.com/brave/brave-core/compare/v1.64.23...master)
   2. Pay attention to the commit message. It looks blurred.
   3. To see the difference better, open the same page in a different browser on the same page.

## Actual result:

<img width="106" alt="Screenshot 2024-01-20 at 11 54 38" src="https://github.com/brave/brave-browser/assets/3427344/5303b854-cfff-4be1-9d12-d3f22bd62543">

## Expected result:

<img width="106" alt="Screenshot 2024-01-20 at 11 55 37" src="https://github.com/brave/brave-browser/assets/3427344/61b0c591-dc27-437b-91f6-aa857471fc92">

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

Brave | 1.64.23 Chromium: 121.0.6167.85 (Official Build) nightly (arm64)
-- | --
Revision | 86733c0da106f02bb3f33a826abd5be0c4c1a2ad
OS | macOS Version 14.3 (Build 23D56)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ShivanKaul** [comment]
Does disabling shields help?

**Comment by brunnopleffken** [comment]
> Does disabling shields help?

No. It's the same.

**Comment by odnamrataizem** [comment]
FWIW, this is also happening on Google Chrome at least since I recently upgraded to version 121, so I guess it's an upstream issue.

I've been applying `font-size: 14.01px;` until this is sorted out.

**Comment by matthewbrandt** [comment]
Is there a workaround for end-users at the moment or will we need to wait for the Chromium bug to be fixed and merged in?

**Comment by jcroucher** [comment]
It appears to be fixed in the latest Chrome build so I assume this should flow through
Version 121.0.6167.139 (Official Build) (arm64)

**Comment by rebron** [comment]
@jcroucher @matthewbrandt @brunnopleffken We released 1.62.156 Chromium: 121.0.6167.139 this morning. Can you all update via brave://settings/help and let us know if you're still encountering the issue?

**Comment by brunnopleffken** [comment]
@rebron Yes. Chromium 121.0.6167.139 fixed this issue! 🙂

**Comment by rebron** [comment]
Thanks @brunnopleffken for checking. Closing per last comment.
