### ISSUE TITLE
[Leo] - Update to limited / unlimited - lock indicators for freemium and premium models

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#35611]
## Description 
Updated the indicators of freemium / premium models in Leo.
Indicator in the header label for **premium** remains as is.

#### Test Plan
For both the menu in the sidebar and on the settings page
- Only the premium model should have a special label ("Premium") and only for non-premium users

### Before
- Freemium models used **limited / unlimited labels**
- Premium models used a **lock / open lock icon**

<img width="1100" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/e576563c-bc0b-46c5-bede-68a44d7d5b0f">

### Updated to
- Freemium models show **limited** only for free users. Premium users don't see a label
- Premium models show **premium** label for free users. Premium users don't see a label

<img width="945" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/c5e9e2cb-d421-4209-948b-5923c4800fa8">

### Figma file:
https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=1653-76695&mode=design

**Comment by mattmcalister** [comment]
The updated version makes sense. Let's go with that.

**Comment by petemill** [comment]
Do we really want to show the word "Limited" on all the models? There are no models anymore that aren't limited (or premium).

**Comment by mattmcalister** [comment]
As discussed, let's remove all the "limited" labels and just use the "premium" label

**Comment by stephendonner** [comment]
> As discussed, let's remove all the "limited" labels and just use the "premium" label

@mattmcalister @petemill just to be 110% clear, we are going to retain the `Unlimited` label for `Premium` users' models, right?

<img width="1312" alt="Screen Shot 2024-05-31 at 4 32 22 PM" src="https://github.com/brave/brave-browser/assets/387249/860efbbc-6934-4d73-a6b2-1ad7591a736c">

**Comment by petemill** [comment]
@stephendonner no, only Premium gets a label. No other labels any of the time (and no icons).

**Comment by kjozwiak** [comment]
The above requires `1.67.109` or higher for `1.67.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.67.109 Chromium: 126.0.6478.40 (Official Build) (64-bit)
-- | --
Revision | 98d88735f6123b755c0614e42e7868f70c35ec33
OS | Windows 11 Version 23H2 (Build 22631.3672)
```

<details>
<summary>Case 1:  Premium users </summary>

1. Installed 1.67.109
2. launched Brave
3. logged in as an existing Premium Leo user using account.bravesoftware.com
4. clicked Leo side panel and accepted agreement
5. clicked settings menu 
6. visited `brave://settings/leo-assistant`

`Leo side panel` | `brave://settings/leo-assistant`
----------- | --------------
![image](https://github.com/brave/brave-browser/assets/98358127/21db053c-76d8-45f1-b40a-edcc3f7de370)|![image](https://github.com/brave/brave-browser/assets/98358127/37b64d1d-a4d7-4f90-9dfe-03ed13632a27)

#### Confirmed no labels (Premium) are shown for premium users 
</details>

<details>
<summary>Case 2:  Freemium users </summary>

1. New profile 
2. launched Brave
3. clicked Leo side panel and accepted agreement
4. clicked settings menu 
5. visited `brave://settings/leo-assistant`

#### Confirmed Premium label is shown for Claude 3 Sonnet for non-premium users and no other labels are shown

`Leo side panel` | `brave://settings/leo-assistant`
----------- | --------------
![image](https://github.com/brave/brave-browser/assets/98358127/ef117711-ab77-432f-bdac-ad8a966544a5)|![image](https://github.com/brave/brave-browser/assets/98358127/d2d590d3-7520-4921-9e22-0784ee507b9e)

</details>

Upgrade: 

<details>
<summary>Case 1:  Premium users </summary>

1. Installed `1.66.118` 
2. launched Brave
3. logged in as an existing Premium Leo user using account.bravesoftware.com
4. clicked Leo side panel and accepted agreement
5. clicked 3 dot menu 
7. visited `brave://settings/leo-assistant`
8. installed `1.67.109`
9. upgraded from `1.66.118` -> `1.67.109` via `brave://settings/help`

#### Confirmed `UNLIMITED` labels are no longer shown for `Mixtral`, `Claude 3 Haiku` & `Claude 3 Sonnet`

`Leo side panel` | `brave://settings/leo-assistant`
----------- | --------------
![image](https://github.com/brave/brave-browser/assets/98358127/28acfd14-beef-4adb-ad80-98063062de36)|![image](https://github.com/brave/brave-browser/assets/98358127/9699eef7-6e06-4630-815e-a19f132d3650)
![image](https://github.com/brave/brave-browser/assets/98358127/5b89a1d2-937c-46f2-955f-97402003278f)|![image](https://github.com/brave/brave-browser/assets/98358127/a3d2c31e-c104-4911-95d9-39f38a7c943b)
</details>

<details>
<summary>Case 2:  Freemium users </summary>

1. Installed 1.66.118
2. launched Brave
3. clicked Leo side panel and accepted agreement
4. clicked `3 dot` menu 
5. visited `brave://settings/leo-assistant`
6. installed `1.67.109`
7. upgraded from `1.66.118` -> `1.67.109` via `brave://settings/help`

#### Confirmed Premium label is shown for Claude 3 Sonnet for non-premium users and no other labels for other models

`Leo side panel` | `brave://settings/leo-assistant`
----------- | --------------
![image](https://github.com/brave/brave-browser/assets/98358127/d5262b46-2f14-4eb0-bd8d-d9e24a8d0817)|![image](https://github.com/brave/brave-browser/assets/98358127/4ffa7b73-075a-4b8f-9e5e-00a6a33191f1)
![image](https://github.com/brave/brave-browser/assets/98358127/afb919a2-76c4-4a0e-89ce-62ef3a3b9730)|![image](https://github.com/brave/brave-browser/assets/98358127/1c1ba3c7-8d91-4015-9d43-985374960d6f)
</details>

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.67.112`

<details>
<summary>Premium user</summary>

</details>

<details>
<summary>non-premium user</summary>

</details>

**Comment by Uni-verse** [comment]
In progress on iOS using version 1.67.115

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.5.1
Brave build: 1.67 (123)
BraveCore: 1.67.123 (126.0.6478.126)
```
---------------------------
<details>
<summary> Freemium user </summary>

**STEPS:**
1. Install and launch Brave 
2. Three-dot menu > Leo
3. Opt-in as a **free user**
4. Tap ⚙️ icon > *Verify* 
5. Tap `Advanced Settings` > Default model for new conversations > *Verify*

**ACTUAL RESULTS:**
- Verified that only `PREMIUM` is shown for the `Cloud 3 Sonnet` model in the side panel and advanced settings
- Verified that the `limited/unlimited` and the `lock` icon are not shown anymore

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/4446d3e0-8690-42f8-8b5d-0f1ec2c885f2) | ![2](https://github.com/brave/brave-browser/assets/128532965/be689c8e-9fad-4c1b-b1b2-cf35b25c61ed) | ![3](https://github.com/brave/brave-browser/assets/128532965/8b35d1b6-e67b-4b35-8e95-a505cf952330) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/bc8742b7-f5d9-4bf3-8b19-c127ac66d8eb) | ![2](https://github.com/brave/brave-browser/assets/128532965/6b8638dd-d3dd-4b3c-a42c-87b4144859cd) | ![3](https://github.com/brave/brave-browser/assets/128532965/d445e57e-c390-4d8b-ab35-27f347ef9af3) |

`Upgrade flow`

https://github.com/brave/brave-browser/assets/128532965/2b7a951e-ded6-4683-ad18-ef42d12d618b
</details>

<details>
<summary> Premium user </summary>

**STEPS:**
1. Install and launch Brave 
2. Three-dot menu > Leo
3. Opt-in as a **premium user**
4. Tap ⚙️ icon > *Verify* 
5. Tap `Advanced Settings` > Default model for new conversations > *Verify*

**ACTUAL RESULTS:**
- Verified that `PREMIUM` is not shown for any language model in the side panel and advanced settings
- Verified that the `limited/unlimited` and the `lock` icon are not shown anymore

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/0e0bbb41-a761-48f7-85a8-e5977f371346) | ![2](https://github.com/brave/brave-browser/assets/128532965/5cbe22ce-e4b5-4822-8aef-9203b3575a1a) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/ba071791-7b58-449c-8b00-35c146ed9686) | ![2](https://github.com/brave/brave-browser/assets/128532965/0baab70a-c4ba-4501-aadb-c0a19c8eb509) |

`Upgrade flow`

https://github.com/brave/brave-browser/assets/128532965/9c6031dc-f996-4702-a4fc-a2d9406b1ad3
</details>
