### ISSUE TITLE
Unlocking Wallet in Panel Sometimes Closes the Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35612]
## Description 

Unlocking the Wallet in the `Panel` sometimes will cause the `Panel` to instantly close

## Steps to Reproduce

   1. Go to brave://wallet-panel.top-chrome/ and inspect the page
   2. Set `BRAVE_WALLET_LAST_VISITED_PANEL` key to `showUnlock`
   3. Set `BRAVE_WALLET_CURRENT_PANEL` key to `showUnlock`
   4. Lock your wallet and open a new tab
   5. Open the Wallet `Panel` and unlock your Wallet
   6. The `Panel` will instantly close

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/5b9154b5-5ce6-4253-9651-ee6f504bfebc

## Expected result:
Unlocking your Wallet in the `Panel` should not close the panel.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.62.155 Chromium: 121.0.6167.85 (Official Build) (64-bit)
-- | --
Revision | 91c989228daf153ef41bd965f268fabc7b9dbbf0
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21768](https://github.com/brave/brave-core/pull/21768)
- Verified panel retains the last open state between lock and unlock

https://github.com/brave/brave-browser/assets/17010094/d13313f2-3c12-4df4-8316-19cd27039660
