### ISSUE TITLE
Fix persisted portfolio token balances 

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#35619]
## Description 

Do not overwrite the persisted portfolio token balances unless triggered by the portfolio page. Also wait until the Brave Rewards check completes before initiating this request to prevent fetching balances when first loading the portfolio overview screen 

## Steps to Reproduce

   1. Create/import a wallet with balances/fiat value
   2. Active brave rewards in wallet and obtain a rewards balance
   3. load the portfolio screen

## Actual result:

The combined portfolio fiat value updates more than once when loading the portfolio overview page

## Expected result:
The combined portfolio fiat value should update no more than once when loading the portfolio overview page

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from issue description
- Verified combined portfolio fiat value updates once when loading the portfolio overview page 

https://github.com/brave/brave-browser/assets/17010094/02fc14eb-bb48-49ad-81d5-61f053cb666b
