### ISSUE TITLE
Browser toolbar and vertical toolbar background fix in dark and private/tor modes

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#35624]
## Description 

The color for the browser toolbar, bookmarks bar, sidebar and vertical tabs background is a bit darker than what we have in design.

https://www.figma.com/file/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?type=design&node-id=3014%3A33123&mode=design&t=FeRw5NvXLDfoleDy-1

- The color I get eyedropping it is #1E2125 and it should be #21272A in dark mode
- In private window is #23104B and should be #2A0D58
- In tor window is #2E0E3E and should be #350B49

These are the color tokens used are `primitive/90%` values

<img width="1055" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/1915b5ef-8c31-4a33-8b20-fc1e7b4530e5">

## Steps to Reproduce

   1. Open nightly
   2. Change theme to dark
   3. See colors

## Actual result:

![image](https://github.com/brave/brave-browser/assets/15734630/9fd7ab9d-02e4-49b2-a399-02d2ac3964a9)

## Expected result:
<img width="744" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/76bd5cc6-effc-4a7f-8006-6f156a4b41a6">

<img width="710" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/a4928f35-147e-4705-a471-2857b151775a">

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by nintendork07** [comment]
was this changed again? i updated to 1.70.117 today and the colors are too way dark.

![Screenshot 2024-09-19 at 3 10 23 PM](https://github.com/user-attachments/assets/33a0fb6d-f387-41df-88b1-f3a135fa7049)
