### ISSUE TITLE
cbsnews.com videos not playing

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#3562]
## Description 

Videos aren't playing on cbsnews.com

## Steps to Reproduce

   1. Load a video like the one reported to me: https://www.cbsnews.com/news/bernie-sanders-rally-live-stream-vermont-senator-holds-brooklyn-campaign-event-today-2019-03-02/
   2. Press play

## Actual result:

Video doesn't play

## Expected result:

Video should play

## Reproduces how often: 

Always

## Brave version (brave://version info)
0.63.x and smaller

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  yes
- Is the issue reproducible on the latest version of Chrome? no

**Comment by bbondy** [comment]
Fixed by these 2 PRs:
https://github.com/brave/brave-core/pull/1770
https://github.com/brave/brave-core/pull/1828

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.61.47 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Linux

* Verified the steps from original issue
