### ISSUE TITLE
Self-custody invitation is displayed after enabling flag

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#35622]
## Description 

The self-custody invite is being displayed when the `#brave-rewards-allow-self-custody-providers` is enabled, even if the user's payment ID is not on the allow-list.

## Steps to Reproduce

   1. With a new profile, enable the `#brave-rewards-allow-self-custody-providers` flag and restart.
   2. Enable Rewards.
   3. Wait a few seconds and open or refresh the NTP.

## Actual result:

The self-custody invite is displayed.

## Expected result:

The self-custody invite should not be displayed unless the payment ID has been allow-listed.

**Comment by kjozwiak** [comment]
The above requires `1.63.138` or higher for `1.63.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.63.138 Chromium: 121.0.6167.85 (Official Build) beta (64-bit)
-- | --
Revision | 742a3bdf71b710125a1c1dd8e89981b9009a87bc
OS | Windows 10 Version 22H2 (Build 19045.3930)
```
- Verified the STR from https://github.com/brave/brave-browser/issues/35622#issue-2102770724

**`Payment ID is not whitelisted:`**

- Confirmed that the self-custody invite is NOT shown on the BR panel and NTP when the payment ID is not whitelisted
- Confirmed that the self-custody provider is NOT shown under the custodian selection page when the payment ID is not  whitelisted

BR Panel |  NTP    | custodian selection page
----------|---------|-----------------
![image](https://github.com/brave/brave-browser/assets/38657976/2dd3961e-6641-4b30-b6b1-6b0d26cd18d6) | ![image (1)](https://github.com/brave/brave-browser/assets/38657976/56c26a66-e36c-43f6-afa7-0b12c822aec9) | ![image (2)](https://github.com/brave/brave-browser/assets/38657976/4b15a871-1673-4aaa-a914-f0ec59c5ed99)


**`Payment ID is whitelisted:`**

- Confirmed that the self-custody invite is shown on the BR panel and NTP when the payment ID is whitelisted
- Confirmed that the self-custody provider is shown under the custodian selection page when the payment ID is whitelisted

BR Panel |  NTP    | custodian selection page
----------|---------|-----------------
![image](https://github.com/brave/brave-browser/assets/38657976/7678501d-4e4f-4b95-adeb-631d44ea1644) | ![image](https://github.com/brave/brave-browser/assets/38657976/962915e5-3b4c-4bf6-bb75-83170ff33d88) | ![image](https://github.com/brave/brave-browser/assets/38657976/af64c3af-65a7-4b29-9bf6-a4b9c07040f3)
