### ISSUE TITLE
Update Line Chart Controls Style

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35621]
## Description 

We need to update the `Line Chart Controls` style to the updated designs in `figma`

![Screenshot 50](https://github.com/brave/brave-browser/assets/40611140/7dcf5af9-ec34-441b-a8e3-cfeca9d38feb)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21769](https://github.com/brave/brave-core/pull/21769)
- Verified Line chart control has a reduced padding between timeline options
![image](https://github.com/brave/brave-browser/assets/17010094/cc204cd7-e8a7-469c-b974-ad8df348e81a)
