### ISSUE TITLE
Summarize this page can be presented even after you've used it

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#35623]
1. Click summarize this page on any page
2. switch tabs
3. Go back to the tab which was summarized

Actual: New summarize this page is presented even though you already used that button.
Expected: No new summarize this page button is presented.

**Comment by MadhaviSeelam** [comment]
Reproduced the issue in Win 11 x64 in `1.62.153 Chromium: 121.0.6167.85`

example | example 
---- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/00d1e8b8-b271-4c32-96c1-84c668febe4b)|![image](https://github.com/brave/brave-browser/assets/98358127/8c231c67-b86a-4148-b600-ed4b4f64348a)

**Comment by WhatsACloud** [comment]
Hi! First time contributor here! Could I try fixing this issue?

**Comment by WhatsACloud** [comment]
Hi @mattmcalister @bbondy ! Sorry to ping you. Could I have your permission to work on this issue (as my first one)?

**Comment by bbondy** [comment]
Thanks and @WhatsACloud feel free to work on it. Just fork the repo and then submit a pull request. Thanks for your interest.

**Comment by WhatsACloud** [comment]
Alright sure, thanks!

**Comment by WhatsACloud** [comment]
To other willing contributors reading this, I've been unable to work on this for quite a long time and I think it's really bad to hog it, so if you want to work on this issue, just text in this chat and by all means go ahead! (if not I'll just continue working on it)
