### ISSUE TITLE
Unable to open new tab in Brave when clicking a link in Slack Windows 10 client

### ISSUE THREAD

**Issue by stodge** [brave/brave-browser#3563]
## Description 
If I click a link in my Slack Windows 10 client, I get an exception from Brave:

brave.exe - Application error

The application was unable to start correctly (0xc0000034). Click OK to close the application.

At the time I was already running an instance of Brave.

## Steps to Reproduce

   1. Click URL link in Slack Windows 10 client
   2. Error dialog appears
   3. Brave won't open the URL in a new tab

## Actual result:

![brave_exception](https://user-images.githubusercontent.com/95512/53747437-4288d100-3e71-11e9-843d-1e7c9d851ab4.PNG)

## Expected result:

Brave should open the URL in a new tab.

## Reproduces how often: 

I can reproduce it every time I click the URL in Slack. I haven't rebooted as I have all of my work windows open.

## Brave version (brave://version info)

Version 0.60.47 Chromium: 72.0.3626.119 (Official Build) (64-bit)

### Reproducible on current release:
- Reproducible on the latest version. I checked for updates.

### Website problems only:  
- N/A

**Comment by stodge** [comment]
A reboot seems to have fixed this.

**Comment by stodge** [comment]
It happened again, which is a pain as I don't want to reboot right now.

**Comment by rebron** [comment]
@stodge does happen to a specific url? assuming Brave is set as default? Is this happening with other applications like external mail app?
