### ISSUE TITLE
Youtube detects brave's AdBlocker on the latest version

### ISSUE THREAD

**Issue by a4amado** [brave/brave-browser#35649]
## Description 

Youtube detects brave's AdBlocker on the latest version

## Brave version (brave://version info)

[Version 1.62.153 Chromium: 121.0.6167.85 (Official Build) (64-bit)](https://brave.com/latest/)
![image](https://github.com/brave/brave-browser/assets/84184203/29ffe713-2493-4e33-b94c-50c019673ae3)

**Comment by simonhong** [comment]
Can you test again after updating `Brave Ad Block Updater` to latest in brave://components?

**Comment by a4addel** [comment]
@simonhong it's strangely did solve it, I did it one hour ago and didn't solve it, i did it now and for some reason it solved it.

**Comment by jessedegans** [comment]
Now it even continues to on purpose break JS: `Uncaught SyntaxError: Unexpected identifier 'browse' (at (index):21:637288)`
