### ISSUE TITLE
Whole Brave UI flickers and crashes when adding new extensions

### ISSUE THREAD

**Issue by gcvl** [brave/brave-browser#35648]
## Description 

The whole Brave window flickers and eventually crashes when adding new extensions.
It happens here on two machines and four different OSes (Debian 12 GNOME, Ubuntu 24.04 GNOME, Linux Mint Xfce 21.3, Zorin 17 Xfce).
The same is going on in Chromium 121.x, Chrome 121.x, Brave Beta 1.63.x; it has been occuring since the code base bumped to v121.

Tried with and without GPU acceleration, different kernel branches (5.19, 6.2, 6.5, 6.6) to no avail; my guess is this is an issue with the Chromium upstream introduced in 121.x: I saw this showing up right after updating Chromium from 120 to 121.

## Steps to Reproduce

   1. Go to the Chrome Web Store
   2. Add any extension
   3. 
   4. 

## Actual result:

The confirmation request prompt is shown but the UI flickers badly; in GNOME you're actually able to confirm/cancel the installation but in XFCE the whole browser becomes unusable and either crashes on its own or has to be force-closed.
Sometimes the entire system freezes and must be hard-rebooted.

## Expected result:

The extension gets installed after prompting the user.

## Reproduces how often: 

Easily reproduced, occurs every single time.

## Brave version (brave://version info)

1.62.153 Chromium: 121.0.6167.85 (Build ufficiale) (a 64 bit) 
1.63.133 Chromium: 121.0.6167.85 (Build ufficiale) beta (a 64 bit) 

## Version/Channel Information:

Stable and Beta, v121 branch.

- Can you reproduce this issue with the current release? 
- YES
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the nightly channel? 

Don't know, can reproduce it with Chrome 122 Dev though.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- NO
- Does the issue resolve itself when disabling Brave Rewards? 
- NO
- Is the issue reproducible on the latest version of Chrome? 
- YES

https://github.com/brave/brave-browser/assets/29081089/fcd9d543-f659-41e3-99e9-00836a8117fc

**Comment by gcvl** [comment]
Here's how disruptive it is in XFCE:

https://github.com/brave/brave-browser/assets/29081089/274ae306-b6cc-4cb9-9fab-0aa55c319959

**Comment by gcvl** [comment]
Here's how disruptive it is in XFCE:

https://github.com/brave/brave-browser/assets/29081089/992bb779-5315-45eb-95c0-5bfa6eafdaf4

**Comment by gcvl** [comment]
Maybe related to https://bugs.chromium.org/p/chromium/issues/detail?id=1522159&q=dialog&can=2 ?

**Comment by dtantono** [comment]
I use Kubuntu with plasma. how to do that?

**Comment by dtantono** [comment]
Yea, but, It works. But, it become really small though and I compared it with Vivaldi. So, I cant find this issue on Vivaldi and this is Brave specific problem.

**Comment by gcvl** [comment]
> Yea, but, It works. But, it become really small though and I compared it with Vivaldi. So, I cant find this issue on Vivaldi and this is Brave specific problem.

Yeah, that's not a solution indeed. No, it's actually a Chromium issue and maybe Vivaldi is still on an older code base than Brave (v121.x) and it's not affected yet.
