### ISSUE TITLE
[Perf] regression in unknown_processes:reported_by_chrome:partition_alloc:max_allocated_size at v1.63.18

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#35645]
Revision range: https://github.com/brave/brave-core/compare/v1.63.14...v1.63.18
Win 11, mac x64 & arm64
https://brave-perf-dashboard.appspot.com/report?sid=75b4dd3a56c456c0308ecd167a0e918acbae731ecce756a6ecbaeae808a9bc75
<img width="948" alt="image" src="https://github.com/brave/brave-browser/assets/45488748/2bcb1007-b6df-4fc6-a07b-8c776d5e8209">

**Comment by atuchin-m** [comment]
There also a regression in `reported_by_chrome:allocated_objects_size`, not just `max_allocated_size`
https://brave-perf-dashboard.appspot.com/report?sid=88b1722134def223fcd8b280d258b77003d94dd5a0ac1d29d3827c46d34e595d

**Comment by atuchin-m** [comment]
It's a regression, detected on the old revisions after enabling anomaly detector.
The reason is bumping WDP: https://github.com/brave/brave-core/pull/20961

It turns out that WDP consumes CPU and memory even it's explicitly disabled in the settings.
IMHO it isn't good for the end users and should be fixed.

<img width="1020" alt="Screenshot 2024-02-14 at 21 55 35" src="https://github.com/brave/brave-browser/assets/45488748/e055fe89-40a2-4a7c-8972-3e680683b83f">

<img width="776" alt="Screenshot 2024-02-14 at 21 55 55" src="https://github.com/brave/brave-browser/assets/45488748/422c8b5a-c7e5-4641-a59f-abcee3eefdf7">

**Comment by kjozwiak** [comment]
@atuchin-m assuming the above can be closed as https://github.com/brave/brave-core/pull/22756 is also in `1.66.x`? Should the above be labelled as `QA/Yes`? If so, mind adding some STR/Cases? If this is something the performance team has already checked/verified, we can label as `QA/No` and close it off.

**Comment by atuchin-m** [comment]
The performance fix was verified by the dashboard.
As for WDP @remusao checked thay it's good for nighty.
So I'm adding QA/No.
