### ISSUE TITLE
Bitcoin asset balance should show details for pending negative balance

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#35650]
So when I submit transaction between two accounts both should have pending balance and "Some balances may be unavailable" section: one with -(amount + fee) another with +amount
![image](https://github.com/brave/brave-browser/assets/168356/d6d356fc-ee15-46fc-a4bd-f007a6cf27e9)
![image](https://github.com/brave/brave-browser/assets/168356/b6a274a4-f857-4918-9c38-5722ea471112)
![image](https://github.com/brave/brave-browser/assets/168356/2ac8c972-ed69-46ab-a26b-55931b7ed87a)

**Comment by kjozwiak** [comment]
The above requires `1.63.140` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.63.141 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | aa92f6cecec7f6c576bd1cf120f4cf359d770159
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21786](https://github.com/brave/brave-core/pull/21786)
- Verified negative pending balance is shown for sending account
- Encountered [#35794](https://github.com/brave/brave-browser/issues/35794)

https://github.com/brave/brave-browser/assets/17010094/8ebfe062-71e1-4c49-87ad-a090f9310968
