### ISSUE TITLE
allow hiding of BR icon when user has never enabled it

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#3565]
## Description 
A user should be able to hide Brave Rewards icon when they've never joined/enabled Brave Rewards. 

## Steps to Reproduce
1. New profile.
2. Don't join, don't enable Brave Rewards.
3. Go to Settings and select Hide Brave Rewards button.
4. Notice BR button is still visible.

## Actual result:
![hide icon](https://user-images.githubusercontent.com/5951041/53753864-2da74000-3e67-11e9-8859-18acb272854d.gif)

## Expected result:
Brave Rewards button is hidden.

**Comment by rebron** [comment]
Follow up to: https://github.com/brave/brave-browser/issues/2975

**Comment by rebron** [comment]
@mkarolin mentioned this might me macOS only, need to verify on WIn/Linux.

**Comment by kjozwiak** [comment]
I can't seem to reproduce this on the following platforms:

* Win 10 x64 VM (clean profile/BR not enabled) - `Couldn't reproduce`
* macOS 10.14.3 x64 (clean profile/BR not enabled) - `Couldn't reproduce`
* Mint 19.1 x64 VM (clean profile/BR not enabled) - `Couldn't reproduce`

Used the following build for the above checks:

Brave | 0.61.45 Chromium: 73.0.3683.39 (Official Build) beta(64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}

Example of the switch being toggled on a profile that never had BR enabled:

![rewardsbutton](https://user-images.githubusercontent.com/2602313/53841427-bce94c00-3f6a-11e9-8545-511e58d5e043.gif)

@rebron @mkarolin which version did the happen on? Possibly regressed somewhere in `0.62.x` or `0.63.x`? Seems to be working fine under `0.61.x`. Is there better STR? Possibly an edge case?

**Comment by rebron** [comment]
@anthonypkeane any more details on steps to reproduce? 

I'm going to go ahead and close, marking invalid. Can't reproduce this either on 61.43 clean macOS build 10.14.2
