### ISSUE TITLE
[Brave News]: Improve peeking card selection 

### ISSUE THREAD

**Issue by LorenzoMinto** [brave/brave-browser#35659]
Spec: https://docs.google.com/document/d/1HH7pohTPp-8uqdccwK4phOrwqK0-NRo-kkBxTDuWUsM/edit#heading=h.tlm8bpd2rbjl

- [ ] No cards with short text/no description
- [ ] No cards without image
- [ ] No cards from Top Sources, if other channels/publishers subscriptions are available

<img width="1710" alt="image (3)" src="https://github.com/brave/brave-browser/assets/13190144/90eef4da-5755-473c-a46b-887da8cef860">

**Comment by LaurenWags** [comment]
@brave/qa-team along side the test plan from https://github.com/brave/brave-browser/issues/35659#issue-2105589597, generally confirm that Brave News is still working

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.72.85 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 2c872aa4d2694bc73ec58e3b14538a4008a6381e
OS | Windows 11 Version 23H2 (Build 22631.4317)
```


1. Installed 1.72.85
2. launched Brave
3. `News` peak button is shown as expected
4. enabled News via NTP
5. Peeking card is shown


step 3 | step 4 | step 5
----- | ------ | -----
![Image](https://github.com/user-attachments/assets/390e0ed7-37a8-4b5f-b16f-2cf7428803d7)|![Image](https://github.com/user-attachments/assets/b55b12c8-d794-42cb-a795-78c3857b02f5)|![Image](https://github.com/user-attachments/assets/14709ca5-249f-47d9-8a10-f00773d23e94)
