### ISSUE TITLE
Bookmarks Section flickers when opening new tab, when bookmark section was set to be hidden.

### ISSUE THREAD

**Issue by therealrinku** [brave/brave-browser#35651]
When opening new tab, bookmark section flickers for some miliseconds before being hidden again even when bookmark section was set to be hidden.

Tested on debian bookworm, HP 15 
Version: [Version 1.62.153 Chromium: 121.0.6167.85 (Official Build) (64-bit)]

I'll probably take a look if I can fix this issue.

Video:
[brave.webm](https://github.com/brave/brave-browser/assets/76877078/3e4cd296-420c-4146-a94f-f318a513cbbd)

**Comment by simonhong** [comment]
Duplicated with https://github.com/brave/brave-browser/issues/25834
