### ISSUE TITLE
Balance details message/modal is not shown in portfolio on panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#35655]
## Description 

Balance details message/modal is not shown in portfolio on panel

## Steps to Reproduce

   1. Submit a BTC transaction on testnet
   2. Wallet shows pending transaction message 
   3. Open panel and go to portfolio 
   4. Doesn't show the pending transaction message
   5. Go to account details, shows the message

## Actual result:

https://github.com/brave/brave-core/assets/17010094/7b895478-892a-4a94-afd1-0c19a87a976a

## Expected result:
Should show on panel as well

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.64.30 Chromium: 121.0.6167.85 (Official Build) nightly (64-bit)
-- | --
Revision | 01fbd61f11c42b0844bd87fe85ebfb6ab2615bd3
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @supermassive

**Comment by Douglashdaniel** [comment]
@srirambv this is contextual to an account. It is visible if you group your assets by `Accounts`.

**Comment by srirambv** [comment]
Verified this works when grouped by accounts. 
![image](https://github.com/brave/brave-browser/assets/17010094/08411371-b340-423b-8f76-62f2854d995a)


Closing as invalid
