### ISSUE TITLE
Self-custody invite is not shown for the India and Japan rewards users

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#35662]
## Description 

Self-custody invite is not shown for the India and Japan rewards users
## Steps to Reproduce

   1. Clean profile 1.63.x
   2. Launch brave using staging env flags  `brave.exe --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=9,"*/brave_rewards/*"=9,"*/bat-native-ads/*"=9,"*/bat-native-confirmations/*"=9,"*/brave_ads/*"=9,"*/brave_user_model/*"=9 --rewards=staging=true,rewards=debug=true`
  3. Enable rewards for the region India/Japan
  4. Enable self-custody flag via brave://flags
  5. Create a Brave wallet
  6. Asked @Kit Davies to whitelist the payment ID 
  7. Not received the self-custody notification on BR panel/NTP
 (Waited for 30 minutes and restarted the browser multiple times but a notification was not shown)
  

## Actual result:

Self-custody invite is not shown for the India and Japan rewards users

## Expected result:
Self-custody invite should be shown for the India and Japan rewards users

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.63.134 Chromium: 121.0.6167.85 (Official Build) beta (64-bit)
-- | --
Revision | cdcba6ef408b305ce19b1a9b3fabbb5e9e3b36bf
OS | Windows 10 Version 22H2 (Build 19045.3930)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @zenparsing @Miyayes

**Comment by kjozwiak** [comment]
The above requires `1.63.143` or higher for `1.63.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.63.145 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | 73dc726c461ceae35c2aa15c4a2d9e6736b5c86d
OS | Windows 10 Version 22H2 (Build 19045.3930)

```
confirmed that if rewards country is either India or Japan and other criteria are met, the self-custody invite is shown.

India | Japan
--- | ---
![image](https://github.com/brave/brave-browser/assets/38657976/096050f4-107b-4ddd-9507-44cd9aef5579) | ![image](https://github.com/brave/brave-browser/assets/38657976/b2dd10d2-c27b-46b1-b9f8-8fe08ebc4009)
![image](https://github.com/brave/brave-browser/assets/38657976/0fa9244c-cc95-4661-b426-94e1251f44fc) | ![image](https://github.com/brave/brave-browser/assets/38657976/75742c4b-a10b-40d5-8d9a-02b2f17b785c)
