### ISSUE TITLE
Update self-custody invite text (2023/01) 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#35665]
## Description

>We’ve added a new way for you to receive your monthly BAT rewards. Connect an account from one of our partners or use the new self-custody option to start earning now.

**Comment by kjozwiak** [comment]
The above requires `1.63.143` or higher for `1.63.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.63.145 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | 73dc726c461ceae35c2aa15c4a2d9e6736b5c86d
OS | Windows 10 Version 22H2 (Build 19045.3930)

```

Confirmed `1.64.39 Chromium: 121.0.6167.139` displayed the updated invite text as per https://github.com/brave/brave-browser/issues/35665#issue-2105824300.

US | India
---|-------
![image](https://github.com/brave/brave-browser/assets/38657976/804178bb-2cc1-48a7-9e06-9c9d54fa2141) | ![image](https://github.com/brave/brave-browser/assets/38657976/a5c7ff6c-6c58-44d2-98b5-93eeec180690)
![image](https://github.com/brave/brave-browser/assets/38657976/2aa16199-9405-470a-9d4a-03170711b570) | ![image](https://github.com/brave/brave-browser/assets/38657976/879e07ac-fd14-4b6f-bb0e-7ef322bc106c)
