### ISSUE TITLE
Scrollbar issue in the provider selection screen 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#35663]
## Description 

Scrollbar issue in the provider selection screen 
## Steps to Reproduce

   1. NA
  
## Actual result:

![image](https://github.com/brave/brave-browser/assets/38657976/45af6a36-dd6a-4a7d-ac4b-596823559b4f)

## Expected result:
unwanted scrollbar needs to be removed 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.63.134 Chromium: 121.0.6167.85 (Official Build) beta (64-bit)
-- | --
Revision | cdcba6ef408b305ce19b1a9b3fabbb5e9e3b36bf
OS | Windows 10 Version 22H2 (Build 19045.3930)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @Miyayes @zenparsing

**Comment by kjozwiak** [comment]
The above requires `1.63.143` or higher for `1.63.x` verification 👍
