### ISSUE TITLE
Bitcoin Available Balance is not Correct on Send Screen

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35660]
## Description 

The Bitcoin `Available` balance is not showing the correct value on the `Send` screen.

## Steps to Reproduce

   1. Create a `Bitcoin` transaction and then go back to the `Send` screen
   2. When you see the `Available` balance for your `Bitcoin` account click on the `Details` button
   3. The `Available` balance does not match the `Available` balance in the `Balance Details` modal.

## Expected result:
The `Available` balances should match.

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.63.140` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.153 Chromium: 121.0.6167.164 (Official Build) beta (64-bit)
-- | --
Revision | ef6dd148841564e2c5d9110bed5d6b7aad780525
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21793](https://github.com/brave/brave-core/pull/21793)
- Verified available balance in both sending and receiving accounts match in the balance details screen

https://github.com/brave/brave-browser/assets/17010094/ed1ddb0d-d723-4311-a6ac-330bd68c4426
