### ISSUE TITLE
create transaction origin component

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#35661]
## Description 

Create a component to display the origin of a transaction to be used during transaction simulation

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.104 Chromium: 123.0.6312.46 (Official Build) (64-bit)
-- | --
Revision | 0ca3d372cf8aab96fafdd75f5c5c8d2012bc0cc6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from [brave/brave-core#21794](https://github.com/brave/brave-core/pull/21794)
- Verified transaction origin and favicon is shown for Brave Swaps, Matcha, Cow Swaps and ERC20 Approve transactions

Matcha | Cow Swap | Brave Swap | ERC 20 Approval
-- | -- | -- | --
![BGg9isOGbG](https://github.com/brave/brave-browser/assets/17010094/9dad5362-796f-4bcd-8912-01f2baa050c6) | ![l0CY7Q64or](https://github.com/brave/brave-browser/assets/17010094/d9f9243e-e577-49ad-ad3c-3268f0e54bad) | ![zIG7po24Vc](https://github.com/brave/brave-browser/assets/17010094/4af3195f-78d0-47ef-84be-5ff0c09f0a71) | ![44RfuuBBBk](https://github.com/brave/brave-browser/assets/17010094/b526a51c-f529-4f4f-a0ee-67406e949b21)
