### ISSUE TITLE
Fallback DoH resolver for testing

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#35677]
## Description 

We're going to do a pilot test of one or more fallback DoH resolvers, via griffin, starting in Nightly. We need some additional browser code to make this work.

**Comment by diracdeltas** [comment]
@arthuredelstein are you going to enable this for real users (not just brave employees)? if so need to make sure the policy side of this is good to go. https://bravesoftware.slack.com/archives/CELA35G5S/p1702393446712829?thread_ts=1701931398.919489&cid=CELA35G5S cc @PrivacyMatters

**Comment by arthuredelstein** [comment]
> @arthuredelstein are you going to enable this for real users (not just brave employees)? if so need to make sure the policy side of this is good to go. https://bravesoftware.slack.com/archives/CELA35G5S/p1702393446712829?thread_ts=1701931398.919489&cid=CELA35G5S cc @PrivacyMatters

Yes, will do. This bug is for code that will be disabled behind a flag. Running the experiment that enables the flag for a population will only happen after policy signoff.

**Comment by diracdeltas** [comment]
Got it. So once the user enables the flag in brave://flags, do they automatically get assigned a fallback provider? Or do they have to pick that in settings or something?

**Comment by arthuredelstein** [comment]
> Got it. So once the user enables the flag in brave://flags, do they automatically get assigned a fallback provider? Or do they have to pick that in settings or something?

At this stage, in the PR I'm working on, there three fallback providers that can be chosen by an integer Feature Parameter that will be set via griffin. But the default value (0) is no fallback provider. So even if the user enables the Feature Flag it won't assign a fallback provider. Only users who are assigned a non-zero parameter value via griffin will receive a fallback provider.

**Comment by arthuredelstein** [comment]
**QA testing:**

This feature is disabled by default but is designed to be enabled by pilot test(s) via griffin. To manually enable it for a specific DoH provider, you can launch from the command line with specific arguments:

On desktop:
```
npm run start -- Debug --enable-features=BraveFallbackDoHProvider:BraveFallback DoHProviderEndpoint/wikimedia
npm run start -- Debug --enable-features=BraveFallbackDoHProvider:BraveFallback DoHProviderEndpoint/quad9
npm run start -- Debug --enable-features=BraveFallbackDoHProvider:BraveFallback DoHProviderEndpoint/cloudflare
```

On android:
```
../out/android_Debug_arm/bin/chrome_public_apk run --args='--enable-features=BraveFallbackDoHProvider:BraveFallbackDoHProviderEndpoint/wikimedia'
../out/android_Debug_arm/bin/chrome_public_apk run --args='--enable-features=BraveFallbackDoHProvider:BraveFallbackDoHProviderEndpoint/quad9'
../out/android_Debug_arm/bin/chrome_public_apk run --args='--enable-features=BraveFallbackDoHProvider:BraveFallbackDoHProviderEndpoint/cloudflare'
```

After launching this way, the UI should show (in its default setting) the name fallback provider being used:
- Desktop: `☰ > Settings > Privacy and Security > Security > Select DNS provider`
- Android: `⋮ > Settings > Brave Shields & privacy > Use Secure DNS`

To test if the browser is using the specified fallback DoH provider, navigate to the test pages:
- Wikimedia: https://check.wikimedia-dns.org/
- Quad9: https://on.quad9.net/
- Cloudflare: https://1.1.1.1/help

(Note that DoH will only be used if your OS is not already defaulting to a DNS provider that offers DoH. In my case I needed to alter my DNS settings on macOS and connect an Android test device to a mobile hotspot.)

**Comment by btlechowski** [comment]
Verified PASSED with

Brave | 1.64.91 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 939586e20d208404b83713ea05cf5f6fa7fe3dd5
OS | Linux

### Wikimedia

<details>

Steps:
1. Clean profile
2. Run Brave with `--enable-features=BraveFallbackDoHProvider:BraveFallbackDoHProviderEndpoint/wikimedia` 
3. Open `☰ > Settings > Privacy and Security > Security > Select DNS provider`
4. Open https://check.wikimedia-dns.org/

Verified proper DNS provider is used

![image](https://github.com/brave/brave-browser/assets/34715963/5fdb6e9d-2426-4903-aa6f-91a4a06fa8b4)|![image](https://github.com/brave/brave-browser/assets/34715963/7026e86a-da7c-4882-835f-57fd97aa046a)
--|--

</details>


### Quad9

<details>

Steps:
1. Clean profile
2. Run Brave with `--enable-features=BraveFallbackDoHProvider:BraveFallbackDoHProviderEndpoint/quad9` 
3. Open `☰ > Settings > Privacy and Security > Security > Select DNS provider`
4. Open https://on.quad9.net/

Verified proper DNS provider is used

![image](https://github.com/brave/brave-browser/assets/34715963/e7fde516-8a5f-42fb-954d-90fdc98919db)|![image](https://github.com/brave/brave-browser/assets/34715963/bfbb8305-1012-4d4d-a04c-9e935624b2b4)
--|--

</details>


### Cloudflare

<details>

Steps:
1. Clean profile
2. Run Brave with `--enable-features=BraveFallbackDoHProvider:BraveFallbackDoHProviderEndpoint/cloudflare` 
3. Open `☰ > Settings > Privacy and Security > Security > Select DNS provider`
4. Open https://1.1.1.1/help

Verified proper DNS provider is used

![image](https://github.com/brave/brave-browser/assets/34715963/905aa5ff-7099-4e15-b209-fa7630d17892)|![image](https://github.com/brave/brave-browser/assets/34715963/3e6cdd40-bd0e-4f70-83ae-f40d336edd83)
--|--

</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```

```

Wikimedia

Quad9

Cloudflare

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.64.95 
Chromium: 122.0.6261.94 (Official Build) beta (64-bit) 
```
---------------------------
<details>
<summary> Wikimedia </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>

<details>
<summary> Quad9 </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>

<details>
<summary> Cloudflare </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

```
Brave | 1.64.97 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | f7c8f13563bfe1063db456650cb43207e1c960c0
OS | Windows 10 Version 22H2 (Build 19045.4123)
```

**Comment by LaurenWags** [comment]
changed to `release-notes/exclude` per discussion with @rebron
