### ISSUE TITLE
Consider adding unused file check in presubmit

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#35678]
I saw a unittest file which wasn't added to any build target hence not run at all.
Maybe we should consider adding a check when there's a new .cc/.h file added in new changes but not added into any build target.

**Comment by goodov** [comment]
Feel free to implement a similar to [1] check in `brave/PRESUBMIT.py` that will validate source files (`.c, .cc, .mm`).

1. https://github.com/chromium/chromium/blob/07549890e7d4679bde1752f6beb6514024f38fef/PRESUBMIT.py#L5106-L5147
