### ISSUE TITLE
News general usage metrics not triggering properly

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#35676]
The News general usage metrics (`Brave.Today.UsageMonthly` and `Brave.Today.UsageDaily`) will intermittently not trigger when the user scrolls down to view the feed. The metrics are also not triggered when the user clicks on the peeking card.

cc @LorenzoMinto

**Comment by LorenzoMinto** [comment]
Fix looks great. Do you think we could uplift this? For context, we are seeing a considerable drop in the P3A DAU metric cc @fallaciousreasoning @rebron

**Comment by DJAndries** [comment]
> Do you think we could uplift this?

absolutely, will uplift once merged
