### ISSUE TITLE
Wallet Creation Dialog constantly saying Failed

### ISSUE THREAD

**Issue by WhiteR4bbitt** [brave/brave-browser#3567]
## Description 
I installed Brave on two devices and wanted to keep them in sync so I restored the wallet on my secondary device, but now I just keep getting the warning (Screenshot below)

I was getting the error before I did the restore, hoping the restore would take precedence.

## Steps to Reproduce
1. Click the BAT icon
2. Click Create Wallet
3. Fails
4. Retry
5. Fails (See screenshot)

## Actual result:

![image](https://user-images.githubusercontent.com/5930847/53755282-61886280-3e73-11e9-8ac7-beb3e4e5f1c0.png)

The wallet also appears to be working since it shows up under `brave://rewards` and my restore key matches the one I used.

## Expected result:
When I click the BAT Icon I see the regular UI after wallet creation (contributions, etc)

## Reproduces how often: 
Since I installed on this device

## Brave version (brave://version info)
`0.60.45 Chromium: 72.0.3626.109 (Official Build) (64-bit)`
`0.60.47 Chromium: 72.0.3626.119 (Official Build) (64-bit)`
Tried Both these

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
  - Dev & Beta won't launch just crash and tell me to send a report to Apple

**Comment by NejcZdovc** [comment]
closing as dupe https://github.com/brave/brave-browser/issues/3440
