### ISSUE TITLE
Prevent access of undefined Sign-In-With-ETH data

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#35670]
## Description 

The `getFormattedKeyValue` function utilized by the Sign-In-With-ETH panel does not check if a data property is defined before attempting to access it, which may cause crashes. 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.102 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | c9343c77bd5dee3524fc45f89721ce0bf4c09b8d
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [rave/brave-core#21798](https://github.com/brave/brave-core/pull/21798)
- Verified able to Sign-In-With-Ethereum works as expected

https://github.com/brave/brave-browser/assets/17010094/c435be9b-89a6-4654-ae51-d14234f50458
