### ISSUE TITLE
Include component versions in webcompat reports

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#35674]
It would be useful for webcompat debugging to know if the user is seeing issues with latest adblock component versions as well, or if they just need to update their components.

**Comment by ryanbr** [comment]
Info like Time/date, but also for other lists would be helpful

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.74.6 Chromium: 131.0.6778.69 (Official Build) beta (64-bit)
-- | --
Revision | 876de763a749f7f8a9a5a2fd72a2391129a3a0f0
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

1. Installed 1.74.6
2. launched Brave
3. visited CNN.com in a new tab
4. clicked Shields icon to open the Shields panel 
5. toggled `off` for Shieds 
6. clicked "Report site", 
7. clicked "Submit"
8. Go to the webcompat reporter dashboard and see the component versions information.


example | example | example 
------ | ------- | --------
![Image](https://github.com/user-attachments/assets/74547f5f-bec4-4169-931f-6d553163c59d)|![Image](https://github.com/user-attachments/assets/38e2ab83-910d-4c11-a12e-30e1920b4383)|![Image](https://github.com/user-attachments/assets/34a3bdfd-9a39-4954-b44d-0e2eaabd0e2f)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.74.11 Chromium: 131.0.6778.85 (Official Build) beta (64-bit) 
Revision	c777fe11bc7afc00156e58af64a6a5bb9559da7d
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

* Ensured the following adblock component versions are included in the request body for the webcompat report.
  
   * Brave Ad Block First Party Filters
   * Fanboy's Mobile Notifications
   * EasyList Cookie 
   * Brave Ad Block List Catatlog
   * Brave Ad Block Updater
   * Brave Experimental Adblock Rules
   * Brave Ad Block Resources Library

```
{
	"adBlockComponentsInfo": [{
		"id": "adcocjohghhfpidemphmcmlmhnfgikei",
		"name": "Brave Ad Block First Party Filters",
		"version": "1.0.253"
	}, {
		"id": "bfpgedeaaibpoidldhjcknekahbikncb",
		"name": "Fanboy's Mobile Notifications",
		"version": "1.0.9764"
	}, {
		"id": "cdbbhgbmjhfnhnmgeddbliobbofkgdhe",
		"name": "EasyList Cookie",
		"version": "1.0.10720"
	}, {
		"id": "gkboaolpopklhgplhaaiboijnklogmbc",
		"name": "Brave Ad Block List Catalog",
		"version": "1.0.68"
	}, {
		"id": "iodkpdagapdfkphljnddpjlldadblomo",
		"name": "Brave Ad Block Updater",
		"version": "1.0.9113"
	}, {
		"id": "jcfckfokjmopfomnoebdkdhbhcgjfnbi",
		"name": "Brave Experimental Adblock Rules",
		"version": "1.0.41"
	}, {
		"id": "mfddibmblmbccpadfndgakiopmmhebop",
		"name": "Brave Ad Block Resources Library",
		"version": "1.0.104"
	}],
	"adBlockLists": "Brave Ad Block Updater,Brave Ad Block First Party Filters,EasyList Cookie,Fanboy's Mobile Notifications,Brave Experimental Adblock Rules",
	"api_key": "fe033168-0ff8-4af6-9a7f-95e2cbfc9f4f",
	"channel": "BETA",
	"domain": "https://www.bbc.com",
	"url": "https://www.bbc.com/news/articles/cx28dzvxjyjo",
	"version": "1.74.11"
}
```
`brave://components` | webcompat report | req/res
---|---|---
![Image](https://github.com/user-attachments/assets/61c25e3f-6535-45fc-aaa0-da58d0ac9d97) | ![Image](https://github.com/user-attachments/assets/1ea87ecf-ee36-4976-a455-85ddb24056b5) | ![Image](https://github.com/user-attachments/assets/b9297fbf-4590-4a86-b17c-682c49331aad)

**Comment by Uni-verse** [comment]
Adding `QA/Blocked` due to https://github.com/brave/brave-browser/issues/42736

**Comment by Uni-verse** [comment]
Removing `QA/Blocked` as https://github.com/brave/brave-browser/issues/42736 is closed. However, there is https://github.com/brave/brave-browser/issues/43186 now but this seems to be intermittent / channel dependent.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.2.1` using version `1.74 (48)`

* Ensured the following adblock component versions are included in the request body for the webcompat report.
  
   * Brave Ad Block First Party Filters
   * Fanboy's Mobile Notifications
   * EasyList Cookie 
   * Brave Ad Block List Catatlog
   * Brave Ad Block Updater
   * Brave Ad Block Resources Library

![Image](https://github.com/user-attachments/assets/2e683706-5072-4023-ae0b-057c4fb7a0d2)
