### ISSUE TITLE
Simplify Report Broken Site language and point to external link

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#35683]
We currently say the following when someone is trying to willingly Report a Broken Site:

```
Note: The report sent to Brave servers will include the site address, Brave version number, Shields settings, VPN status, and language settings.
```

This text is not super relevant to the user at that moment, given that they're frustrated at the site not working. Also, we have plans to include [other information](https://github.com/brave/brave-browser/issues?q=is%3Aissue+is%3Aopen+label%3Awebcompat%2Freporter) soon that will help debugging and will add to this already overly long sentence. 

What if instead we just say the following:

```
This report will only send information necessary for us to fix this site. Learn More.
```

The Learn More link should point to a wiki page that will contain an itemized list of everything we send (i.e. Brave version, etc). Every time we add to that list, we will open a security/privacy review to make sure it's both necessary and non-identifying.

We should continue showing the URL that will be sent.

**Comment by kdenhartog** [comment]
One suggestion for this new proposed text is to add a Thank you for helping us make a better experience for all users.

Something to this effect

`Thank you for helping make Brave better for all. This report will only send information necessary for us to fix this site. Learn More.`
