### ISSUE TITLE
Mixtral has output quality issues 

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#35698]
## Description 

- [ ] Sometimes confuses assistant instructions and user message
- [ ] Uses code formatting where not applicable
- [ ] Adds word count at the end of replies
- [ ] Unnatural affinity for emojis

## Steps to Reproduce

 1. install `1.64.34`
 2. launch Brave
 3. opt-in to Leo
 4. load `https://www.horizoniq.com/` (can also use `Fox News` or sports sites)
 5. start clicking on `Suggest questions`
 6. keep clicking those
 7. look at the responses

## Actual result:

example | example | example
---------|----------|---------
![Screen Shot 2024-01-24 at 10 57 14 PM](https://github.com/brave/brave-browser/assets/387249/cc78772a-4b5e-4f92-96be-22c6f4cc518b) | ![Screenshot 2024-01-25 at 4 21 54 PM](https://github.com/brave/brave-browser/assets/387249/0f8876bf-7c99-4c7b-a920-e7315542117f) | ![Screenshot 2024-01-25 at 6 15 07 PM](https://github.com/brave/brave-browser/assets/387249/f6ee647a-d61f-4b45-830a-a53ce348f209)

## Expected result:

Shouldn't answer with so many emojis, at the least

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.64.34 Chromium: 121.0.6167.85 (Official Build) nightly (x86_64)
-- | --
Revision | cb45905f6e829321be56b3d34dc914e065807044
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @LorenzoMinto @bbondy @mattmcalister @rebron @petemill @nullhook @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.64.98` or higher for `1.64.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.64.98 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | a262f3c44a8960fee49fbf0bd6f5740634f32be7
OS | Windows 10 Version 22H2 (Build 19045.4123)
```
