### ISSUE TITLE
[Perf] Fix JSON processing on UI thread

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#35695]
Found here: https://github.com/brave/brave-browser/issues/35693#issuecomment-1916933301
![image](https://github.com/brave/brave-browser/assets/45488748/1f978cca-4f85-427a-b5dc-c7b79412449a)

**Comment by atuchin-m** [comment]
The urls we parse:
https://brave-today-cdn.brave.com/sources.global.json
https://brave-today-cdn.brave.com/brave-today/feed.en_USjson

One of the code parts:
https://github.com/brave/brave-core/blob/master/components/brave_news/browser/publishers_controller.cc#L199C8-L285
<img width="1378" alt="Screenshot 2024-01-30 at 21 56 57" src="https://github.com/brave/brave-browser/assets/45488748/6cc01e82-dbac-4a9a-ae41-6a637a95a546">

The same pattern is used across the brave_news code.

**Comment by petemill** [comment]
Just to note that we're agreed the main performance improvement here should first be to remove the processing off the main thread, and not adjust the request timing. We can improve that but need to consider the needs of Desktop, Android and the various UI which needs the data.

**Comment by atuchin-m** [comment]
a linked issue: https://github.com/brave/brave-browser/issues/35778

**Comment by kjozwiak** [comment]
@atuchin-m mind double checking/ensuring that the performance issues have been resolved once we get `1.63.x` builds with the above fix? Some context via https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1707869423133049.

**Comment by kjozwiak** [comment]
Going to add the `QA/Yes` as we can basically run through some spot checks and ensure that `Brave News` is working correctly/not crashing as per https://github.com/brave/brave-core/pull/21833#issue-2109056694.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 14` using the following build(s):

```
Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
--- | ---
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Android 14; Build/AP11.231215.009; 34; REL
```

* ensured that the `Brave News` onboarding card is being displayed by default via NTP without any issues
  * ensured that the modal/card is animated/working as expected in terms of performance (not seeing any jank)
* ensured that `enabling` & `disabling` the feature within `Settings` works as expected
  * ensured when `Brave News` is disabled, it doesn't appear within NTP
  * ensured once `Brave News` is enabled once again, it's visible/scrollable via NTP (ensured there's no visible performance issues)
* ensured that scrolling through the `Brave News` feed is a smooth experience
* ensured that inline ads are being displayed within the news feed
  * ensured that tapping/clicking on inline ads works as expected (opens the tab/no crashes etc..)
* ensured that tapping on cards opens the website/content without any issues
* ensured that `Load new content` works as expected when adding feeds from `Popular`, `Suggestions` & `Channels`
* ensured that tapping/clicking on `Learn more about your data` opens the website within the WebUI without issues
  * ensured that pressing `X` closes the website and returns the user back into the `Settings` page where they can enable news

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (x86_64)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | macOS Version 14.4 (Build 23E5196e)
```


Test Plan:

In a new profile click the `Learn More` link on the `Enable Brave News` popup
Navigate back
The page should not crash
Click on `Turn on Brave News`
The publishers should load
The feed should load
Disable Brave news
Enable Brave news
The publishers should load
The Feed should load
Disable Brave news, refresh the page
Enable Brave news
The publishers should load
The feed should load
