### ISSUE TITLE
Fix Brave Ads landing pages should not be included in auto-contribute

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#3570]
Advertising landing pages should not be considered for auto-contribute.
Tips are OK if the users chooses to tip directly.

cc @bradleyrichter @jsecretan @NejcZdovc @tmancey

**Comment by NejcZdovc** [comment]
@tmancey @bridiver do we know if page is ads landing page? Do we add some kind of identifier to the page so that rewards page can pick it up?

**Comment by bridiver** [comment]
@NejcZdovc why would advertiser sites ever be included in the first place? I don't want to autocontribute to Ford no matter how many times I visit their site. It just doesn't make sense.

**Comment by NejcZdovc** [comment]
@bridiver we don't want that, but currently don't have a way (afaik) to tell which page/tab is ads page and which one is normal one

**Comment by tmancey** [comment]
@jsecretan as agreed on hold, so moving to backlog
