### ISSUE TITLE
Update Asset Group Container Styles

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35709]
## Description 

We need to update the `Asset Group Container` styles to the new changes in `Figma`

![Screenshot 4](https://github.com/brave/brave-browser/assets/40611140/c47f92c1-5c26-4bfa-8253-2eb398e3a455)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21830](https://github.com/brave/brave-core/pull/21830)
- Verified grouping assets by `Networks` or `Accounts`, shows a `Darker` background for group header
- Verified collapsed groups doesn't have a `Border`
- Verified for both `Tokens` and `NFTs`
- Verified on both Wallet page and Wallet panel

https://github.com/brave/brave-browser/assets/17010094/204451fe-1d57-4cf0-b218-dffc1e92cf08
