### ISSUE TITLE
Ensure task scheduler is already initialized in ledger lib

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#3571]
https://github.com/brave/brave-core/pull/1800 added a task runner in ledger lib.
Task scheduler used in the ledger lib is already initialized by chromium code in desktop case but not in iOS.
We would need to ensure task scheduler is initialized before creating the task runner in ledger lib to avoid crashes on iOS.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Ubuntu 18.04 LTS

Used test plan from https://github.com/brave/brave-core/pull/1835
