### ISSUE TITLE
Claroty Site dose not support Brave browser

### ISSUE THREAD

**Issue by ilyak83** [brave/brave-browser#35714]
This is the link: https://industrial-demo.dashboard.claroty.com/

Screenshot attached.

![brave-claroty-issue](https://github.com/brave/brave-browser/assets/37582972/1a6fbadc-ed98-4e67-a435-8a15195e98c2)

As you can see this site works properly only in Google Chrome, Microsoft Edge and Mozilla Firefox browsers. Interesting that any Firefox forks such as Mullvad or Librewolf can open this link as a regular Firefox.

**Comment by rebron** [comment]
cc: @ryanbr @ShivanKaul

**Comment by ShivanKaul** [comment]
![image](https://github.com/brave/brave-browser/assets/5284154/b917ca84-d9ca-4bba-9c20-a817923aa631)

**Comment by ryanbr** [comment]
Should be fixed in the next component update.

**Comment by ryanbr** [comment]
Will keep ticket open once @ilyak83 confirmed its fixed. (Give it 90mins or so from this messgae for the update to go out)

**Comment by ilyak83** [comment]
Well done! The issue was resolved.
