### ISSUE TITLE
Initial onboarding screen when accessing Brave Wallet

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#35713]
![image](https://github.com/brave/brave-browser/assets/3308503/040986aa-cab5-4bec-8a3e-f6ceeacfe479)

Figma design: https://www.figma.com/file/oXIiv45pIhF2RGlpEjOfUg/Wallet-onboarding?node-id=6223%3A70942&mode=dev

Main umbrella issue: https://github.com/brave/brave-browser/issues/35294

## Description

Redesign initial onboarding screen when accessing Brave Wallet for the first time.
Include new screen for accepting T&Cs.

### Additional information

Remove copyright footer.
Share background gradient values with William.

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 and Lenovo Tab with Android 13 running 1.64.97 x64 Beta build
- Verified steps from [ brave/brave-core#21905](https://github.com/brave/brave-core/pull/21905)
- Verified new onboarding screen is shown when creating a wallet
- Verified selecting both terms enables `Continue` button
- Verified `Terms of use` clickable span points to `https://brave.com/terms-of-use/`
- Verified onboarding screen looks correct on both dark and light theme
