### ISSUE TITLE
Refine Widevine prompt with UI/UX feedback

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#3572]
Created this issue with @karenkliu 's feedback on https://github.com/brave/brave-core/pull/1772#issuecomment-469410101

The first time the user encounters a site that needs Widevine, show this notification in the page content area so that the user is sure to notice it:

![widevine spec 1](https://user-images.githubusercontent.com/2388823/53760821-d611d000-3e78-11e9-9aa9-22b561cd6106.png)

As @bbondy  pointed out, this notification and its associated behavior should replace the right popup completely:
![widevine spec 2](https://user-images.githubusercontent.com/2388823/53760828-d90cc080-3e78-11e9-8d41-a8064e664597.png)

Once the user installs Widevine, we do not need to show the notification again for any site that requires Widevine. If the user chooses to block it, we show the Widevine notification every time a website requires it. This diagram illustrates the interaction behavior:

![widevine user flow](https://user-images.githubusercontent.com/2388823/53760977-33a61c80-3e79-11e9-8ba9-edfc31bcdd76.png)

As mentioned in the specs, we should use components from our Brave design system as much as possible to brand our browser and distance it from Chrome. Ask @rossmoody , our design system lead for guidance if you need help incorporating these front-end elements. I've also attached this icon for you to use in place of the Chrome one in this dialogue (it's also available in our design system icon library): 
[icons.zip](https://github.com/brave/brave-core/files/2928066/icons.zip)
Check out CSS for our default browser dialog under the "Inspect" tab here: https://share.goabstract.com/b5476d5e-e5b3-49fd-a19d-d9f3516417c8

**Comment by simonhong** [comment]
Above user flow is what we do now and right noti is also deleted with latest PR.

**Comment by karenkliu** [comment]
@simonhong Great! So the only feedback that still needs to be addressed is styling then.

**Comment by simonhong** [comment]
This can be merged into https://github.com/brave/brave-browser/issues/3961
