### ISSUE TITLE
After closing Brave browser and All Tabs when we reopen brave browser it Automatically open All Closed Tab.

### ISSUE THREAD

**Issue by sonu2614** [brave/brave-browser#35726]
Description
After closing Brave browser and All Tabs when we reopen brave browser it Automatically open All Closed Tab.

Steps to Reproduce

   1. Click on Close Button then there is a pop up come out its ask for close all tabs.
   2. When we click on close all ,it close The Brave Browser.
   3. when we click to open Brave Browser its automatically open all close Tab.

Expected result: Open New Browser without any previews Tabs

Brave version (brave://version info):[Version 1.62.153 Chromium: 121.0.6167.85 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by rebron** [comment]
Hi @sonu2614. You can make a change here: brave://settings/getStarted
Select the "Open the New Tab page" option.
We default to "Continue where you left off" so when you launch your browser again, we're going back to where you left off.

**Comment by kergekacsa** [comment]
I have the very same issue with Version 1.64.113 Chromium: 123.0.6312.86 (Official Build) (64-bit)](https://brave.com/latest/)

I tried to set every option and then back to "Open the New Tab page", but it still opens up every single page from the previous session. :(

**Comment by aweedman** [comment]
> Hi @sonu2614. You can make a change here: brave://settings/getStarted Select the "Open the New Tab page" option. We default to "Continue where you left off" so when you launch your browser again, we're going back to where you left off.

This doesn't work for me. I've tried this and Open Specific Set of pages and still all tabs from when the browser was closed open up again.
