### ISSUE TITLE
Update Connection Settings Border Radius

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35730]
## Description 

We need to update the `DApp Connection Settings` button `border-radius` to the updated designs in `figma`

![Screenshot 12](https://github.com/brave/brave-browser/assets/40611140/e5d1c3cc-f9bb-4828-9da1-c30592145053)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21841](https://github.com/brave/brave-core/pull/21841)
- Verified connection settings now has border radius in panel
![image](https://github.com/brave/brave-browser/assets/17010094/a91c2b97-991f-4572-88d0-e89b1bbd1112)
