### ISSUE TITLE
[Zcash] Add Zcash to supported networks list when wallet is created

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#35732]
Steps to reproduce:
1) Enable Zcash feature flag at the chrome://flags page
2) Create new wallet
In this case there is no Zcash in the supported networks list:
![image](https://github.com/brave/brave-browser/assets/106654560/79fe617b-33d8-412b-98b1-e9f7e86fbc25)

**Comment by srirambv** [comment]
Removing Android label as the onboarding screen will be done via #36578

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.97 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | f7c8f13563bfe1063db456650cb43207e1c960c0
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21859](https://github.com/brave/brave-core/pull/21859)
- Verified enabling ZCash flag shows ZCash as a network during onboarding
- Verified disabling ZCash flag or setting it as Default (Disabled) doesn't show ZCash as available network during onboarding
- Verified when flag is disabled, create account doesn't list ZCash as an option
- Verified when flag is enabled, create account lists ZCash as an option
- Verified when flag is disabled, ZCash network setting is not shown in `brave://settings/wallet/networks`
- Verified when flag is enabled, ZCash network setting is shown in `brave://settings/wallet/networks`

https://github.com/brave/brave-browser/assets/17010094/e0e0b4e0-ebdd-41c3-bf9e-bb6dde4af5eb
