### ISSUE TITLE
[Zcash] Show correct error when transaction failed due existance of posted one

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#35734]
We don't have pending balance at the moment so only one outgoing transaction could be processed at point of time per account.
Otherwise it would conflict with existing one due reuse of utxos.
We should show obvious error saying to wait until previous transaction finishes.

**Comment by srirambv** [comment]
removing Android label as Zcash isn't supported yet on Android

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.102 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | c9343c77bd5dee3524fc45f89721ce0bf4c09b8d
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21935](https://github.com/brave/brave-core/pull/21935)
- Verified unable to submit 2 ZCash transaction
- Verified able to submit 2 ZCash transactions from different account simultaneously
- Verified error message is different for different tokens
- Verified success transactions show correct message and doesn't show any error button

![brave_n5Gfs52K7d](https://github.com/brave/brave-browser/assets/17010094/f68a6d93-bd26-4f2b-ae34-5fa9c09e72dd)
![brave_z59QGYHKK5](https://github.com/brave/brave-browser/assets/17010094/59d36b76-9879-4cc8-82a6-4caed51e2272)
![brave_R783zXTMrV](https://github.com/brave/brave-browser/assets/17010094/5763c91b-4b73-49f2-a117-d514bc0f5bda)
![brave_HbQ8wddfZb](https://github.com/brave/brave-browser/assets/17010094/f344a84f-35d3-40ef-b6b2-26c47818501c)
![brave_JyLa6FdMoO](https://github.com/brave/brave-browser/assets/17010094/da5eb7b2-48c4-4a2a-ba4b-0fac959731a5)
