### ISSUE TITLE
Update the Wallet Panel Portfolio Background

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35745]
## Description 

We need to update the Wallet Panel `Portfolio` background to the new designs in `figma`

![Screenshot 19](https://github.com/brave/brave-browser/assets/40611140/d88676de-bb18-418f-95b5-38be9c444580)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21854](https://github.com/brave/brave-core/pull/21854)
- Verified wallet panel uses new portfolio background
- Verified scrolling down scrolls with header being sticky
- Verified on both light and dark themes

https://github.com/brave/brave-browser/assets/17010094/abb74200-3738-4fbb-9338-710b6b50f7c6
