### ISSUE TITLE
Omaha licensing isn't up-to-date in brave://credits

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#35743]
Omaha licensing info is not currently showing up in brave://credits. In addition, upstream code was changed here https://source.chromium.org/chromium/chromium/src/+/d8c080d06ce96c209a177669b8101a520c08d037 to recursively search third_party directories for dependencies. We added a temporary exception to `brave_license_helper.py` so as not to block the cr122 upgrade, but we should figure out a better solution to this.

**Comment by fmarier** [comment]
It turns out that this is present in `brave://credits` but only on Windows since that's the platform where we include Omaha.

The notices are not fully up-to-date though.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.64.48 Chromium: 121.0.6167.139 (Official Build) nightly (64-bit)
-- | --
Revision | 741f7ee622bdfde5e10e3beda02288f3c056287e
OS | Windows 10 Version 22H2 (Build 19045.3996)
```

LZMA SDK
libzip
Omaha
zlib

**Comment by kjozwiak** [comment]
Going to remove the `QA Pass` as the above will need to be rechecked with `1.63.x` as it was uplifted via https://github.com/brave/brave-core/pull/22014. The above requires `1.63.155` or higher for `1.63.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)
```

1. Installed 1.63.155
2. launched Brave
3. opened `brave://credits`
4. Ensure that the following entries exist and have working show license and homepage links:

**_LZMA SDK_** - `PASSED` 
<details>

`show license` | `homepage` (https://www.7-zip.org/sdk.html)
----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/9570e74f-1fdc-4e6f-89f0-2e0dbb0e2b86)|![image](https://github.com/brave/brave-browser/assets/98358127/18d4daf5-cbe8-4a4c-904e-ed0a4cca76b9)
</details>

**_libzip_** - `PASSED`
<details>

`show license` | `homepage` (https://github.com/nih-at/libzip)
----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/146f86b8-20c2-4aa1-88fa-032e48f7a11d)|![image](https://github.com/brave/brave-browser/assets/98358127/a9fcc229-20d2-4b86-90b8-451ad1791bb0)
</details>

**_Omaha_** - `PASSED` 
<details>

`show license - 1` | `show license - 2` |`show license - 3` | `homepage` (https://github.com/brave/omaha) 
--------- | ---------- | ----------- | --------------
<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d5f3c3c7-6328-4a41-bc45-8a9aa04adeec">|<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/44b76d3f-785e-43f6-bdf5-8ad85ee8cfb0">|<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/7696396f-4f50-4ee9-b1a6-b600a7aea1e6">|<image width="500" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/462a4f1b-4fac-4aee-87d1-2e1441772bb3">

</details>

**_zlib_**
<details>

`show license` | `homepage` (`https://zlib.net/) 
----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/9b66bfce-5f10-479b-9a96-8ec1abd85671)|![image](https://github.com/brave/brave-browser/assets/98358127/5ddfc577-5db8-493e-b087-907d834ed3f1)
</details>

**_zlib_**
<details>

`show license` | `homepage` (`https://zlib.net/) 
----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/14818ef4-54c0-4746-b007-5d86c2cc8204)|![image](https://github.com/brave/brave-browser/assets/98358127/7cdeab15-99d7-4196-83cf-64ac984c7ec3)
</details>
