### ISSUE TITLE
Fix padding with clock and stats for NTP Hebrew locale

### ISSUE THREAD

**Issue by levi128** [brave/brave-browser#3574]
## Description 

the widgets are Asymmetrical when i'm using the  Hebrew language! 
Fix?
## Steps to Reproduce

   1. when i open the browser

## Actual result:

https://imgur.com/CljFIsI
https://imgur.com/ZPck5r6
![cljfisi](https://user-images.githubusercontent.com/5951041/53774788-bbede700-3ea4-11e9-882e-ce2193f25543.jpg)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by levi128** [comment]
https://imgur.com/MuoDWfF

here the photo!

**Comment by rebron** [comment]
@levi128 What do you mean by asymmetrical? The font sizing of the clock (larger) versus the stats?

**Comment by levi128** [comment]
> @levi128 What do you mean by asymmetrical? The font sizing of the clock (larger) versus the stats?

It's a bit too much on the sides .. the clock and the stats! moment. I'll send pictures. In English it's fine. But in Hebrew it's a bit out of the middle!

**Comment by levi128** [comment]
> @levi128 What do you mean by asymmetrical? The font sizing of the clock (larger) versus the stats?

https://imgur.com/CljFIsI

https://imgur.com/ZPck5r6

The first one is in Hebrew.

The second English! See the differences?
Thanks for the help!

**Comment by rebron** [comment]
For Hebrew locale (probably effects Arabic too or rtl languages) , need to add proper padding.
cc: @cezaraugusto @rossmoody

**Comment by LaurenWags** [comment]
@imptrx does this require manual QA? if so, can you add a test plan and `QA/Yes` label? if not, can you mark as `QA/No`? thanks! 👍

**Comment by imptrx** [comment]
@LaurenWags Here is the test plan!
Steps to check:
1. Open brave in a RTL language
2. Open a new tabs page
Assert:
- Clock and Stats widget should not be flush with screen

**Comment by LaurenWags** [comment]
awesome, thanks @imptrx 😄

**Comment by GeetaSarvadnya** [comment]
Verification passed on

Brave | 0.67.111 Chromium: 75.0.3770.100 (Official Build) beta (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1803 (Build 17134.523)

Arabic:

![image](https://user-images.githubusercontent.com/38657976/61463316-c6aba300-a991-11e9-9fea-ee0a13c6a2b1.png)

Hebrew:

![image](https://user-images.githubusercontent.com/38657976/61463358-db883680-a991-11e9-978c-95b4f2f2f50d.png)
