### ISSUE TITLE
https://mess.eu.org/web/ text is mangled by fingerprinting protection

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#35751]
## Description 

Visit https://mess.eu.org/web/. The text has extra spaces which is reportedly caused by getImageData.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

1.62.153

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
Still an issue @arthuredelstein  ? Url dead and main site seems fine, single player crashes regardless of any setting

**Comment by ryanbr** [comment]
Page loaded fine here, no repo.
