### ISSUE TITLE
BTC account's address are not discovered when created by onboarding

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#35753]
Restore wallet with BTC mainnet.
Observe account is created but might have not all balance.

**Comment by kjozwiak** [comment]
The above requires `1.63.153` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21855](https://github.com/brave/brave-core/pull/21855)
- Verified bitcoin account is auto discovered when restoring wallet
- Encountered [brave-browser#35954](https://github.com/brave/brave-browser/issues/35954)

https://github.com/brave/brave-browser/assets/17010094/7bf0b444-2c5d-442e-a08a-a2ec68cf3dbd
