### ISSUE TITLE
Update icons in Share menu to use Nala's

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#35758]
## Description 

The icons in the share menu are coming straight from Chromium it seems, need to update them.

Design
https://www.figma.com/file/tU9zrk9Ite8B06JSjHAHhn/General-dialogs-and-popups?type=design&node-id=248%3A21458&mode=design&t=jkZK4voDjkVUuQV4-1

## Actual result:

![image](https://github.com/brave/brave-browser/assets/15734630/0eb5a799-cea6-416d-9fa2-59c462c4eb71)

## Expected result:

<img width="360" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/b3e6dde8-88ef-4474-896c-233aac1a375d">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.67.35 Chromium: 124.0.6367.60 (Official Build) nightly (64-bit)
-- | --
Revision | cf6b916e6e68f45b10d6ccebe4530f7319c3d1aa
OS | Windows 11 Version 23H2 (Build 22631.3447)
```

1. Installed 1.67.35
2. launched Brave
3. load a site (google.com)
4. click on `Share this page` icon in the URL bar
5. confirmed Nala icons are used in Share menu and match to the Figma designs


Dark Theme | Light theme
------  | ------
![image](https://github.com/brave/brave-browser/assets/98358127/33a0d10b-fe23-493c-8d4a-2980e8c97042)|![image](https://github.com/brave/brave-browser/assets/98358127/9068d9dc-3092-4cbb-9dcb-60cf227dc3f3)
