### ISSUE TITLE
Remove Bitcoin and Filecoin from add custom token and NFT screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#35756]
## Description 

Remove Bitcoin and Filecoin from add custom token and NFT screen

## Actual result:

Custom Asset | NFT
-- | --
![image](https://github.com/brave/brave-browser/assets/17010094/5e564a92-4393-41ef-972a-1ff1c35762b9) | ![image](https://github.com/brave/brave-browser/assets/17010094/bc05ab24-3388-4d47-ab3e-a1274921ed79)

## Expected result:
No Bitcoin in dropdown until Ordinals/BRC20 support and no Filecoin in list 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.64.34 Chromium: 121.0.6167.85 (Official Build) nightly (64-bit)
-- | --
Revision | cb45905f6e829321be56b3d34dc914e065807044
OS | Windows 11 Version 23H2 (Build 22631.3007)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @josheleonard @Douglashdaniel @supermassive

**Comment by kjozwiak** [comment]
The above requires `1.63.147` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.153 Chromium: 121.0.6167.164 (Official Build) beta (64-bit)
-- | --
Revision | ef6dd148841564e2c5d9110bed5d6b7aad780525
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21860](https://github.com/brave/brave-core/pull/21860)
- Verified Bitcoin & Filecoin isn't listed in network dropdown in Add custom asset list or Add NFT

https://github.com/brave/brave-browser/assets/17010094/1eb18220-9c5b-4ed6-9c3e-c4e8f3c52b65
