### ISSUE TITLE
Update the Percent Change Bubble Colors

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35768]
## Description 

We need to update the `Percent Change Bubble` colors to match the updated designs in `fimga`

![Screenshot 22](https://github.com/brave/brave-browser/assets/40611140/ae1f08a1-4243-4a15-a1ea-720bf4d8685e)

![Screenshot 23](https://github.com/brave/brave-browser/assets/40611140/fdb680cf-c977-416f-b3b8-b144065d246c)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21865](https://github.com/brave/brave-core/pull/21865)
- Verified percentage change in bubble is more bold 

Light | Dark
-- | --
![brave_G1RGLgVHWD](https://github.com/brave/brave-browser/assets/17010094/744826a8-93fd-4d92-9e23-33047d23a9e1)  | ![brave_4w3Qv3d6sM](https://github.com/brave/brave-browser/assets/17010094/32512869-969f-4abe-a32e-ded84aaa0f00)
![brave_yyy9IBEBXe](https://github.com/brave/brave-browser/assets/17010094/cf9323b7-3671-40c3-a043-b4007aa780b3)| ![brave_MF1DHSwqsJ](https://github.com/brave/brave-browser/assets/17010094/9ce12af9-701c-4965-bd3a-04f6780e95de)
