### ISSUE TITLE
Shields description on sites page is incorrect.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#35765]
Reported by a localizer:

Currently on brave://settings/content page the `Shields status` description says
`Sites can block trackers, ads, and fingerprinting using Shields`, which is incorrect. The shields are the ones doing the blocking.

The description should say `Shields can block trackers, ads, and fingerprinting`.

Additionally, there's a typo in the string `Browse up to 6x faster on major news sites in Brave by blocking trackes &amp; ads.` <- should be "tracke**r**s". For testing see https://github.com/brave/brave-browser/issues/10191#issuecomment-685674422

**Comment by kjozwiak** [comment]
@hffvld @Uni-verse STR/Cases re: how to trigger the notification with the string change can be found via https://github.com/brave/brave-core/pull/21862#issuecomment-1934758650.

The above requires `1.63.149` or higher for `1.63.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP11.231215.009 release-keys
Brave build: 1.63.149
Chromium: 121.0.6167.164 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-core/pull/21862#issuecomment-1934758650

**ACTUAL RESULTS:**
- Verified that notification has fixed string `Browse up to 6x faster on major news sites in Brave by blocking trackers & ads.`

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/740df771-059a-4a92-a7d6-21e43aa453a3) | ![2](https://github.com/brave/brave-browser/assets/128532965/c0ee72a8-1430-4dd8-a813-accb8fcdfa5d) |

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.63.149 Chromium: 121.0.6167.164 (Official Build) beta (64-bit)
-- | --
Revision | 16509c04a66afcc00d180c0b62a887b9fc4776a2
OS | Windows 11 Version 23H2 (Build 22631.3085)
```

1. Installed 1.63.149
2. launched Brave
3. opened `brave://settings/content`

Confirmed correct text and it now reads `Shields can block trackers, ads, and fingerprinting` 

1.62.x | 1.63.x 
---- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/d9a8bd50-37b8-4641-90ad-58c1b8a73169)|![image](https://github.com/brave/brave-browser/assets/98358127/45719762-5dae-45a3-a2d1-4c6ee0747335)
