### ISSUE TITLE
URL field is not updated after searching brave://settings

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3576]
## Steps to Reproduce

   1. Open `brave://settings`
   2. Search for `brave`

Note: the never ending spinner is logged: https://github.com/brave/brave-browser/issues/2757

## Actual result:

Search field is not updated
![setting search fail](https://user-images.githubusercontent.com/34715963/53781632-de661b80-3f09-11e9-9be3-bfcca0c6504d.gif)

## Expected result:
Search field is updated
![setting search pass](https://user-images.githubusercontent.com/34715963/53781678-0bb2c980-3f0a-11e9-8aa7-97ead4b30857.gif)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.62.16 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Not reproducible on release(0.60.47) nor on beta(0.61.45): 

Brave | 0.60.47 Chromium: 72.0.3626.119 (Official Build) (64-bit)
-- | --
Revision | 9a65993e2cde1b5797ec98da4cd9abcea464cd7b-refs/branch-heads/3626@{#876}
OS | Windows

cc @brave/legacy_qa

**Comment by rebron** [comment]
@rebron to check if this is fixed with Pete's new search UI.

**Comment by kjozwiak** [comment]
Reproducible on `macOS 10.14.3 x64` using the following build:

Brave | 0.62.16 Chromium: 73.0.3683.39 (Official Build) dev(64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Mac OS X

**Comment by rebron** [comment]
Closing. Looks fixed with @petemill's work with Settings. Checked strs with macOS 66.100.
