### ISSUE TITLE
Inconsistent UI

### ISSUE THREAD

**Issue by sosauce** [brave/brave-browser#35762]
The Brave Shield seems to have a more modern design then the rest of the settings and it's also blue more then orange.
Also, the switches are not using the same design

![image](https://github.com/brave/brave-browser/assets/98750531/9f7a82dc-59a4-4d2e-abfa-624900ffc066)
![image](https://github.com/brave/brave-browser/assets/98750531/90b02412-48a2-480f-9e02-7dab976e0ed9)

**Comment by rebron** [comment]
Closing as stale/wfm. Fixed several versions back.
![Image](https://github.com/user-attachments/assets/27eb1cc6-45b2-4a5f-a3d9-395fec88bf72)
