### ISSUE TITLE
Fix Selling using Ramp

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#35779]
- In portfolio, click on ETH or BAT
- On the asset page, in the Accounts sections, click vertical dots on the right and select Sell
- On the modal, fill the amount and click sell with ramp
- On the new tab opened, ramp page should have an error as shown below

![Image](https://github.com/brave/brave-browser/assets/48117473/c6377b74-ef49-4835-93f7-864522f84bd3)

**Comment by kjozwiak** [comment]
The above requires `1.63.147` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.148 Chromium: 121.0.6167.164 (Official Build) beta (64-bit)
-- | --
Revision | c68893a5f2bbf2898967a976b21b3fe5d581f714
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21879](https://github.com/brave/brave-core/pull/21879)
- Verified Sell on Ramp works as expected

https://github.com/brave/brave-browser/assets/17010094/05730888-7f0d-4c6e-92a3-e7c2fd7e40fc
