### ISSUE TITLE
Onboarding issue

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#35773]
## Description 
It seems that the VPN notice is appearing too soon for some people, please see here: https://bravesoftware.slack.com/archives/CDNJ9SVUL/p1706829830940699?thread_ts=1706732254.066259&cid=CDNJ9SVUL

I tested on my OnePlus and as expected that VPN notice doesn't appear on first launch.

**Comment by deeppandya** [comment]
> My vote is to remove the VPN notice entirely. It's probably just annoying for the majority of first time users who are unlikely to purchase anyway. We already have / are testing other ways to increase VPN subscriptions:
> 
> - Campaigns optimizing towards in-app purchase action (already have)
> - Full funnel campaigns that directly deep link to the VPN paywall (in testing)
> 
> I think these likely increase subscriptions way more than the notice.
> cc @anthonypkeane @deeppandya 

Yeah I agree. I think at this point, we have a few other ways to gain users. I will remove it in this issue entirely

**Comment by anthonypkeane** [comment]
Agree, please remove this notice
