### ISSUE TITLE
Leo - Visual QA feedback

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#35776]
## Description: 
Created a section in Figma for visual QA to cover some things different from designs. Not gonna list them all here because it's better on Figma with comments and pointers.

https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=1872%3A89763&mode=design&t=wJXUxYQOUAyFLwZQ-1

**Comment by kylehickinson** [comment]
Going to close this in favor of https://github.com/brave/brave-core/pull/22483 as its already been associated with PRs
