### ISSUE TITLE
[Adblock] Re-implement support for logging uBlock Scriptlets in devtools or some specific logger like uBlock does now.

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#35789]
Recent changes in uBlock Scriptlets made it so `log` argument in Scriptlets is now obsolete and now the logs will be done when uBlock logger is opened. This means that `#brave-adblock-scriptlet-debug-logs` flag will be only work when using the `debug` argument, which is rarely used. 

Logging is important to create scriptlets and it will make it harder for Filter Authors to work directly in Brave to do so, and uBlock will be needed for the logging.

Plus, is this new logging to Logger going to work in MV3 when MV2 version of uBlock is not allowed in Chrome extension store? I have no idea. But I know these are the problem when _you_ depend on a 3rd party like uBlock for the scriptlets, one change with the scriptlets or the adblocker can mess with Brave.

I hope there can be a workaround about this and hope the adblocker gets feature parity with uBlock soon, it should be a priority, not just to make Brave Adblocker the best native adblocker (especially when MV3 adblockers are the only ones), but also to stop having to relay on having uBlock installed just to fix rules, or an incompatible regex rule (because of rust language) and now to even get the logging information from Scriptlets.

The politics and fragmentation in Adblockers will always be a problem, especially when Brave decided to take the 'uBlock inspiration' and depend on their lists and scriptlets.

**Comment by ShivanKaul** [comment]
We can accomplish this via https://github.com/brave/brave-browser/issues/35472, closing
