### ISSUE TITLE
Update Card Header Buttons Border Radius

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35780]
## Description 

We need to update the Wallet `Card Header` buttons `border-radius` to match the new designs in `figma`

![Screenshot 5](https://github.com/brave/brave-browser/assets/40611140/288f316c-65d5-4d71-8914-78f74007469f)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21881](https://github.com/brave/brave-core/pull/21881)
- Verified all card header buttons have a border radius of 8px

https://github.com/brave/brave-browser/assets/17010094/973c8688-9d3c-4f73-a071-d8d2ef4f2e53
