### ISSUE TITLE
Make sure original document security settings apply to speedreader document

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#35797]
probably the HTTP headers are already preserved but we should check:

* https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP (both the HTTP header and the meta HTML tag)
* https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity (note this is an HTML attribute not a header)
* Access-Control-Allow-Origin header https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
* Potentially other headers listed in https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html

References:
https://hackerone.com/bugs?subject=brave&report_id=2354284&view=new&substates%5B%5D=new&reported_to_team=&text_query=&program_states%5B%5D=2&program_states%5B%5D=3&program_states%5B%5D=4&program_states%5B%5D=5&sort_type=latest_activity&sort_direction=descending&limit=25&page=1
https://github.com/brave/brave-browser/issues/35095

**Comment by iefremov** [comment]
@diracdeltas we do not modify the original headers, but in fact they can be painful for us, see https://github.com/brave/brave-browser/issues/24577

**Comment by diracdeltas** [comment]
Discussed on Slack what to do:

1.  <meta> HTML tags with the http-equiv attribute from the original page should be inserted in the speedreader page. However for the content security policy meta tag, we need to make sure the `style src` directive does not overwrite the speedreader stylesheets. Therefore if a page defines `<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'self'">` this needs to make sure our style-src takes precedence but default-src none applies to everything else. Or alternatively we can start with a more restrictive policy and only allow the page to loosen it for things like images that speedreader needs to load - see https://bravesoftware.slack.com/archives/C6R461GF4/p1707157012700929?thread_ts=1707059179.689489&cid=C6R461GF4
2. As @iefremov noted, we don't modify headers so no security issues there, but there is this problem where the page CSP header can overwrite the speedreader CSP meta tag: https://github.com/brave/brave-browser/issues/24577. perhaps whatever solution we apply from #1 for CSP meta tags we can also apply for the CSP HTTP headers.
4. For https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity, it seems we can in fact delete the subresource integrity attributes which is a security problem. So we need to make sure when distilling HTML for speedreader that the HTML integrity and crossorigin attributes from the original page are preserved in the speedreader page. Test case: https://googlechrome.github.io/samples/subresource-integrity/ (the stylesheet won't render regardless but you can inspect the HTML in speedreader mode to check whether these attributes are preserved).

**Comment by boocmp** [comment]
Only these  [artributes](https://github.com/brave/brave-core/blob/dedf8d6513661bd3a3c3ca78084adb36e0fd301c/components/speedreader/rust/lib/src/readability/src/scorer.rs#L51) are removed during the distillation process, the rest remain as in the original page

**Comment by diracdeltas** [comment]
> Only these [artributes](https://github.com/brave/brave-core/blob/dedf8d6513661bd3a3c3ca78084adb36e0fd301c/components/speedreader/rust/lib/src/readability/src/scorer.rs#L51) are removed during the distillation process, the rest remain as in the original page, but we completely remove all < links > and <script> elements, so I assume we should check if there are no elements with integrity attributes, instead of checking they are preserved.

Since the CSP disables script I think we are fine to remove script elements. As for link, if we allow loading of some elements like favicon, we should make sure the integrity attributes are kept. However if we block all loading from link elements as we do for stylesheets, it's also fine to remove completely.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.64.81 Chromium: 122.0.6261.43 (Official Build) beta (x86_64)
-- | --
Revision | 19b9ce86d7aed2a1fdb7734d6a27f2fe6abd0153
OS | macOS Version 14.4 (Build 23E5205c)
```
https://github.com/brave/brave-browser/issues/35797 - `PASSED`

### Steps:
1. installed `1.64.81`
2. launched Brave
3. loaded `https://js176.gitlab.io/tools/deeplinks/2010/06/encrypt-web-https-everywhere-firefox-extension`
4. clicked on `Turn on Speedreader`

### Confirmed Speedreader-enabled view rendered, with `This image is not loaded` showing, as per the testplan

example | example
---------|---------
<img width="1162" alt="Screenshot 2024-02-21 at 12 15 47 PM" src="https://github.com/brave/brave-browser/assets/387249/18750ffb-d2c0-4d93-ba81-69aea4411da5"> | <img width="1162" alt="Screenshot 2024-02-21 at 12 15 58 PM" src="https://github.com/brave/brave-browser/assets/387249/8d34bbd4-5ead-45a1-8fd9-78ea0c4d7760">


https://github.com/brave/brave-browser/issues/24577 - Already verified: https://github.com/brave/brave-browser/issues/24577#issuecomment-1957803768

**Comment by btlechowski** [comment]
Verified with

Brave | 1.64.91 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 939586e20d208404b83713ea05cf5f6fa7fe3dd5
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/21958

### First issue

![image](https://github.com/brave/brave-browser/assets/34715963/c9c292a2-7a04-4a38-b02c-5dd1b88dad3b)|![image](https://github.com/brave/brave-browser/assets/34715963/89203a43-3759-4520-a0b3-9d4fef896e32)
--|--

### Second issue

![image](https://github.com/brave/brave-browser/assets/34715963/64672aed-4bd5-4743-a9fb-85f0f6d6478a)|![image](https://github.com/brave/brave-browser/assets/34715963/7e8642e2-8347-4151-89a8-d2d8fb7c8c0c)
--|--

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 13 TP1A.220624.014 release-keys
- Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.64.95 
Chromium: 122.0.6261.94 (Official Build) beta (64-bit) 
```
---------------------------
<details>
<summary> First issue </summary>

**STEPS:**
1. Launch Brave
2. Go to https://js176.gitlab.io/tools/deeplinks/2010/06/encrypt-web-https-everywhere-firefox-extension
3. Three-dot menu > Settings > Appearance
4. Enable Speedreader > *Verify*

**ACTUAL RESULTS:**
- Verified that Speedreader-enabled view rendered, with `This image is not loaded showing`, as per the testplan

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/31073b89-c11d-47d8-9144-eb0bc7580e90) | ![2](https://github.com/brave/brave-browser/assets/128532965/d7c7b2bf-fba8-46a4-889c-72c5f9d6a9c0) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/9adc88ec-77a0-420c-aa0f-f16fbe31ae85) | ![2](https://github.com/brave/brave-browser/assets/128532965/93b1ac8b-6a55-4258-a3c8-b95c740ad64f) |
</details>

<details>
<summary> Second issue </summary>

**STEPS:**
1. Launch Brave
2. Go to https://seirdy.one/posts/ > Open some articles
3. Three-dot menu > Settings > Appearance
4. Enable Speedreader > *Verify that the CSS for reader mode is applied*

**ACTUAL RESULTS:**
- Verified that the CSS for `Speedreader mode` is applied, as per the testplan

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/182943fb-cbe7-4b61-aff4-9d040a214b95) | ![2](https://github.com/brave/brave-browser/assets/128532965/8cc54bd7-b275-47ef-b54c-a273cae4d610) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/0a2385b9-e30e-45d8-bf73-df10283d9bb3) | ![2](https://github.com/brave/brave-browser/assets/128532965/56dbf1a8-2d36-4f47-9cc9-72304051e762) |
</details>

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.64.97 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | f7c8f13563bfe1063db456650cb43207e1c960c0
OS | Windows 10 Version 22H2 (Build 19045.4123)
```

First issue

https://js176.gitlab.io/tools/deeplinks/2010/06/encrypt-web-https-everywhere-firefox-extension

Second issue

Navigate to any page on https://seirdy.one/
Open the Console in DevTools
Activate Reader Mode
