### ISSUE TITLE
Sell with Ramp doesn't work for BTC

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#35796]
## Description 

Sell with Ramp doesn't work for BTC

## Steps to Reproduce

   1. Get some BTC balance in wallet account
   2. Open token details screen
   3. Select more menu for account and select Sell
   4. Enter value and click on `Sell on Ramp`, doesn't load the Off-Ramp page

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/e5892846-8500-40e2-9ab4-82b5106f0272

## Expected result:
Able to load Off-Ramp page

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.63.141 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | aa92f6cecec7f6c576bd1cf120f4cf359d770159
OS | Windows 11 Version 23H2 (Build 22631.3007)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? No (verified in [brave/brave-core#21525](https://github.com/brave/brave-core/pull/21525))

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @supermassive @Douglashdaniel

**Comment by kjozwiak** [comment]
The above requires `1.63.153` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.153 Chromium: 121.0.6167.164 (Official Build) beta (64-bit)
-- | --
Revision | ef6dd148841564e2c5d9110bed5d6b7aad780525
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21968](https://github.com/brave/brave-core/pull/21968)
- Verified BTC Off-Ramp works as expected 

https://github.com/brave/brave-browser/assets/17010094/75de3dc5-ee7c-43df-810d-3e282be06e0a
