### ISSUE TITLE
No option to use HTTP/S to load sites available on the IPFS network

### ISSUE THREAD

**Issue by ZelnickB** [brave/brave-browser#35790]
## Description

I recently visited the [IPFS website](https://ipfs.tech/) using my browser, and then I selected the button to load it over the IPFS network. This took me to `ipfs://bafybeic4ng3cqdampvo2vpkzhusw6gm6jpaahhuzphb7zfvsx2cgsaxswu/`. Now, I would like to load the IPFS website over HTTPS, but whenever I navigate to <https://ipfs.tech/>, I am redirected automatically to the version on the IPFS network. I was able to solve the issue by turning off my Brave-provided IPFS node, but it reappears as soon as I turn it back on. **There doesn't seem to be a way to prevent or override the automatic redirect from <https://ipfs.tech/> to `ipfs://bafybeic4ng3cqdampvo2vpkzhusw6gm6jpaahhuzphb7zfvsx2cgsaxswu/`.** In other words, when my IPFS node is enabled, there is no way to get to <https://ipfs.tech/>.

## Brave version (brave://version info)

1.62.156 Chromium: 121.0.6167.139 (Official Build) (arm64), Revision 800674fc2c6162087525ed9b5bfc07230296b27d, macOS Version 14.2.1 (Build 23C71)

## Version/Channel Information

This issue occurs on the current stable release, as shown above. I did not test it on other channels.

----

If you need any more information to troubleshoot, please let me know.

**Comment by ZelnickB** [comment]
I would classify this as a bug, not a feature request. I don't have permission to add a tag indicating that.

**Comment by bsclifton** [comment]
cc: @yrliou

**Comment by yrliou** [comment]
cc @vadimstruts

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)
