### ISSUE TITLE
Folllow up of #3209 - Navigation to `chrome://process-internals/#general` is causing webview crash

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3579]
## Description 

Folllow up of #3209 - Navigation to `chrome://process-internals/#general` is causing webview crash

## Steps to Reproduce

   1. Clean profile 0.61.41
   2. Navigate to `chrome://process-internals/#general`
   3. Webview is getting crashed
   4. Exit brave
   5. Clean profile
   6. Launch brave with using `--disable-features=IsolateOrigins,site-per-process`
   7. Navigate to `chrome://process-internals/#general`
   8. Webview is getting crashed
   

## Actual result:

Webview crash

Crash Report ID: https://stats.brave.com/dashboard#crash/5c7e766cde3611001fc6bd1e

![image](https://user-images.githubusercontent.com/38657976/53807688-3cc8e380-3f76-11e9-8413-31965330ebfe.png)

## Expected result:
No webview crash

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.61.41 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
--- | ---
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Linux Mint

### Reproducible on current release: No
- Does it reproduce on brave-browser dev/beta builds?  Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information

The issue is reproduced in macOS by @kjozwiak. Thanks!
@brave/legacy_qa @mkarolin

**Comment by iefremov** [comment]
seems working now
