### ISSUE TITLE
Full screen mode on mac make tabs and url section disappear

### ISSUE THREAD

**Issue by DaatKruby** [brave/brave-browser#35808]
## Description 
Can't use the full screen mode on MacOS Sonoma 14.0, tabs aren't visible or clickable after going full screen mode. 

## Steps to Reproduce

   1.  Open multiple tabs on brave
   2.  Click the green button to maximize the window to full screen

## Actual result:
Tabs are gone and I have to minimize the window again to toggle between tabs, I tried disabling all the extensions and I have the last update available from brave. 

## Expected result:
Tabs should be on the top of the screen so the user can switch between them even on full screen mode.

## Reproduces how often: 
Everytime I go full screen mode.

## Brave version (brave://version info)
1.62.156 Chromium: 121.0.6167.139 (Official Build) (arm64) 

## Version/Channel Information:
no

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel? not sure what this is.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
NA

**Comment by rebron** [comment]
@DaatKruby Do you have `Always show toolbar in full screen` option on? It's available via the View menu or brave://settings/appearance in The toolbar section

**Comment by DaatKruby** [comment]
> @DaatKruby Do you have `Always show toolbar in full screen` option on? It's available via the View menu or brave://settings/appearance in The toolbar section
Yup it was on, I fixed it uninstalling Brave and installing it again.

**Comment by rebron** [comment]
@DaatKruby Didn't need to uninstall Brave. Just toggling that setting will work. 
I'm going to go ahead and close this one out as it looks like it's working for you now. Thanks for the report.

**Comment by akashjobanputra** [comment]
> @DaatKruby Do you have `Always show toolbar in full screen` option on? It's available via the View menu or brave://settings/appearance in The toolbar section

This option should be accessible with a better UX, perhaps in the context menu of tab section.
![Screenshot 2024-05-16 at 12 02 40 PM](https://github.com/brave/brave-browser/assets/11390605/224e71f8-3f45-421e-aa64-0f06f126b536)
