### ISSUE TITLE
[Android] User is seeing "Brave Rewards nay not work..." notification when Rewards are disabled

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#35809]
## Description 
Android user is seeing the following notification even though user has opted out of Brave Rewards:

![image](https://github.com/brave/brave-browser/assets/3299098/a1c730b3-fd0f-4a11-8bc9-e21ac9b2ba7f)

This notification should not appear for users w/Rewards disabled.

## Device details
   - Install type (ARM, x86): 
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 14
   
## Brave version
v1.62.156

### Additional information

User report:
https://community.brave.com/t/frequently-prompted-to-enable-notifications-even-though-brave-rewards-is-disabled/528023

**Comment by DrKodiak** [comment]
I am still experiencing this problem.

**Comment by deeppandya** [comment]
> I am still experiencing this problem.

@DrKodiak the issue has been addressed in latest nightly. It will be in release soon.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.65.96`

- Confirmed that the `Brave Rewards many not work...` notification is not shown 
- Enabled rewards and reset the rewards via brave://rewards and ensured that `Brave Rewards many not work...` notification is not shown

**Comment by THETCR** [comment]
I reckon this has yet not been released to production.

Since I get this intrusive dialog if any part of the URL contains the string "reward". Which is incredibly frustrating.

**Comment by GeetaSarvadnya** [comment]
@THETCR The fix will be available on 1.65 RC version once 1.65 is released on 12th Apr
