### ISSUE TITLE
Switching from landscape to portait breaks Leo chat window

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#35806]
We need to handle that properly

**Comment by kjozwiak** [comment]
Going to add `QA/Yes` as we have STR/Cases outlined via https://github.com/brave/brave-core/pull/21955#issue-2124940454 and QA should make sure that the above is working correctly re: switching between `landscape` & `portrait`.

**Comment by kjozwiak** [comment]
Just a quick note that https://github.com/brave/brave-browser/issues/36000 is still an issue that's affecting certain devices but no others. We're still investigating/trying to figure out why it's not working for certain devices.

The above requires `1.63.154` or higher for `1.63.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 2 XL`, `Pixel 6`, `Galaxy A32 5G`, `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Pixel 2 XL / taimen-user  8.1.0 OPM2.171026.006.H1 release-keys
- Pixel 6 / oriole-user 13 TQ3A.230901.001 release-keys
- Galaxy A32 5G / a32xsq-user 13 TP1A.220624.014 release-keys
- Galaxy Tab S8 / gts8wifixx-user 13 TP1A.220624.014 release-keys
- Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.63.154
Chromium: 121.0.6167.184 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-core/pull/21955#issue-2124940454

**ACTUAL RESULTS:**
- Verified that the Leo window is not getting blank when rotating device between `Portrait` and `Landscape` mode
- Observed that the same issue is still happening on `Galaxy Tab S8` - #36000

---------------------------

*Pixel 2 XL*

https://github.com/brave/brave-browser/assets/128532965/37556b90-a2a8-4d0d-9568-a6655a44a364

*Galaxy Tab S8*

https://github.com/brave/brave-browser/assets/128532965/34ab7c98-a25a-4741-8694-f286e83a9e63

*Pixel 7*

https://github.com/brave/brave-browser/assets/128532965/b358d66b-03fc-4152-af42-7a784d343087
