### ISSUE TITLE
Unable to sign Solana dapp transactions using Ledger

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#35802]
Reproduced with https://lfg.jup.ag while trying to claim JUP airdrop - unable to successfully sign transactions with Ledger hardware wallet.

This applies only to `SignTransactionRequest` and `SignAllTransactionRequests`.

**Comment by kjozwiak** [comment]
The above requires `1.62.162` or higher for `1.62.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.62.162 Chromium: 121.0.6167.164 (Official Build) (64-bit)
-- | --
Revision | c18c9cc62d2b4376a5ada5b98b673dfc7994f20d
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21894](https://github.com/brave/brave-core/pull/21894)
- Verified able to sign and submit a Swap transaction via `https://jup.ag`

https://github.com/brave/brave-browser/assets/17010094/2a5d3b83-f10d-47ef-9954-adfb62d52b62
