### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Karl-Knapp** [brave/brave-browser#35814]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.62.156 Chromium: 121.0.6167.139
Operating System: Windows NT 10.0.19045

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Seemingly at random, in this instance while I was on another tab.
2. Has happened previously on primary tab.
3. Seemingly fixes itself when restarting browser.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/cc400c00-dba3-700b-0000-000000000000

**Comment by bsclifton** [comment]
Backtrace link https://brave.sp.backtrace.io/p/brave/debug?filters=JTVCJTVCJTIyX2RlbGV0ZWQlMjIlMkMlMjJlcXVhbCUyMiUyQyUyMjAlMjIlNUQlMkMlNUIlMjJfcnhpZCUyMiUyQyUyMmVxdWFsJTIyJTJDJTIyY2M0MDBjMDAtZGJhMy03MDBiLTAwMDAtMDAwMDAwMDAwMDAwJTIyJTVEJTVE&fingerprint=d90d73813d3a173d9b69581c047269394ac3a845a93ece561a102348042adea8&debug=(%226831f26%22,0,0)

**Comment by iefremov** [comment]
not actionable
