### ISSUE TITLE
Sidebar icons overlay full screen for some users

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#35811]
## Description 

For some users, the icons on the sidebar do not disappear when either the browser itself or a video play is set to full screen. The issue occurs only when the sidebar is set to always show. Disabling/re-enabling the side bar does not resolve the issue and issue occurs on macOS and Windows systems.

See sidebar icons on the left bleeding through.

![image](https://github.com/brave/brave-browser/assets/3299098/6af76bad-56cd-4e57-8e6b-f687d617c82e)

One user reports:

> Happens when a webpage or opened html file uses `document.body.requestFullscreen();` function to enter fullscreen.

## Steps to Reproduce

   1. Have sidebar set to show "always"
   2. Put Brave in Full screen mode (optional)
   3. Visit a website with full screen video player
   4. Set player to full screen

## Reproduces how often: 

Easily/always for those who can reproduce it

## Brave version (brave://version info)

Reported versions:
v1.63.131
v1.62.153

## Version/Channel Information:

- Can you reproduce this issue with the current release? Y
- Can you reproduce this issue with the beta channel? Y
- Can you reproduce this issue with the nightly channel? N

## Miscellaneous Information:

User report:
https://community.brave.com/t/sidebar-icons-stuck-in-full-screen-player/527867

**Comment by Brave-Matt** [comment]
Good number of users still reporting this issue after updating to latest.

cc @rebron

**Comment by rebron** [comment]
cc: @simonhong @sangwoo108

**Comment by simonhong** [comment]
checking

**Comment by MadhaviSeelam** [comment]
Adding `QA/Test-All-Platforms` label as the issue was reported on macOS & Win.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.65.83 Chromium: 123.0.6312.46 (Official Build) beta (64-bit)
-- | --
Revision | 1ea667c8c59a4a4a327579974ec11149a738e750
OS | Windows 11 Version 23H2 (Build 22631.3296)
```
Reproduced the issue in `1.64.105 Chromium: 123.0.6312.46` in Win 11 x64 

![image](https://github.com/brave/brave-browser/assets/98358127/3588d385-1adc-41db-9224-4489cfcc682e)

1. Installed 1.65.83
2. launched Brave
3. opened brave://settings/appearance
4. select `Show on the left` for Sidebar option
5. opened a new tab loaded youtube.com
6. played a clip https://www.youtube.com/watch?v=RDoy5X38iio 
7. entered video to full screen

#### Confirmed sidebar icons are not shown

step 4 | step 6 | step 7 
---- | ---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/637c735c-a83a-4cf7-a785-38247435f978)|![image](https://github.com/brave/brave-browser/assets/98358127/a919bbde-e861-4d60-8f9c-aa45425d4a82)|![2024-03-15_16h39_11](https://github.com/brave/brave-browser/assets/98358127/62da7564-bf3d-48cb-88bf-bee515cb7655)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave	1.65.87 Chromium: 123.0.6312.46 (Official Build) beta (x86_64) 
Revision	2babfcf82ebba4c5dc0146d2ca66229ffd3ac02d
OS	macOS Version 11.7.10 (Build 20G1427)
```

First, reproduced the issue using `1.64.105`:

![Screen Shot 2024-03-19 at 11 21 53 AM](https://github.com/brave/brave-browser/assets/387249/46923eb1-a973-42fe-969f-219dbada51c4)

### Steps:
1. installed `1.65.87`
2. launched Brave
3. set `Show sidebar` to `Always` in `brave://settings/appearance`
4. set `Show on the left`
5. played `https://www.youtube.com/watch?v=56WBs0A4Kng`
6. entered full-screen mode

### Confirmed no `sidebar` elements appear

example | example
---------|---------
<img width="1644" alt="Screen Shot 2024-03-19 at 11 24 29 AM" src="https://github.com/brave/brave-browser/assets/387249/667f1cf5-72a7-42e2-b7e5-89ba25d4fb89"> | ![Screen Shot 2024-03-19 at 11 24 33 AM](https://github.com/brave/brave-browser/assets/387249/144a72d4-f566-4d58-b692-efd92a32d40b)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave	1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
Revision	5d9143e1a0812c53bdc27fd5384591254306a88c
OS	Linux
```
