### ISSUE TITLE
Allow Extensions (Brave Wallet fallback) to trigger Wallet Onboarding

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35812]
## Description 

We should allow `Extensions (Brave Wallet fallback)` setting to trigger `Wallet Onboarding` if no other `Wallet Extensions` are installed and a `Brave Wallet` has not been setup.

## Steps to Reproduce

   1. Create a new `Profile` and do not setup a `Brave Wallet` or install any other `Wallet Extensions`
   2. Go to a `Solana` DApp and try to connect. 
   3. `Brave Wallet` will not be detected and user wont be able to trigger the `Brave Wallet` onboarding.

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/4f2b28b3-1d99-46d4-92b7-f600da7f861a

## Expected result:
`Brave Wallet` should be detected to allow the user to click and trigger `Wallet Onboarding`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.63.149` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.152 Chromium: 121.0.6167.164 (Official Build) beta (64-bit)
-- | --
Revision | 497ab49eab494dd35d416b3bab3eece99c27510d
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21908](https://github.com/brave/brave-core/pull/21908)
- Verified running `window.solana.connect()` without creating wallet loads onboarding in a new tab

https://github.com/brave/brave-browser/assets/17010094/6bd32f5e-ef36-429c-91f1-752feea43bc7
