### ISSUE TITLE
CTRL + W closes pinned tabs

### ISSUE THREAD

**Issue by scrobbleme** [brave/brave-browser#3581]
CTRL + W closes pinned tabs as well, but shouldn't. This is why they are pinned ;)

**Comment by tomlowenthal** [comment]
This is the intended behavior.

**Comment by scrobbleme** [comment]
@tomlowenthal Ah okay, but what is then the intended behaviour of pinned tabs then anyway?
Just "only show an icon instead icon + name"? (I see this is Chrome default behavior)

As a feature request: a configuration for this behavior would be nice.

(Okay, I'm quite spoiled with the many subtle features Opera has compared to other browser ...)

**Comment by tomlowenthal** [comment]
We don't do anything different from Chromium.

**Comment by alexander-potemkin** [comment]
Any chance to have this as an option, please? It's really handy.

**Comment by druud** [comment]
At least as an opt-in, let me choose how a pinned tab handles Cmd-W.

For example:
1. default closing; 2. only close after confirmation; 3. block-and-beep.
