### ISSUE TITLE
AIChat: improve mobile usability for page context toggle

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#35813]
In AIChat, the page context toggle has a tooltip that works properly on desktop when you hover your mouse over it. However, on mobile, any touch event has the side effect of enabling/disabling the toggle. We should allow users to interact with the tooltip without affecting other areas.

**Comment by stephendonner** [comment]
@nullhook @petemill is this `QA/Yes` or `QA/No`, and if the former, can you please also provide a step-by-step testplan; thank you!

cc @brave/qa-team

**Comment by nullhook** [comment]
test plan added in the pr

**Comment by stephendonner** [comment]
> test plan added in the pr

Thanks! 🤜 🤛

**Comment by kjozwiak** [comment]
The above requires `1.63.153` or higher for `1.63.x` verification 👍 Also created https://github.com/brave/brave-browser/issues/35989 as a follow up to improve the radius/stability.

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.63.154
Chromium: 121.0.6167.184 (Official Build) beta (64-bit) 
```

Filed follow-up issue #36112
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-core/pull/21911#issue-2119283742

**ACTUAL RESULTS:**
- Verified that tapping on the tooltip is not `enabling` or `disabling` the toggle switch `Use page context for response`
- Verified that tapping only on the `Use page context for response` title is enabling / disabling the toggle switch
- Observed that issues described in #35989 still occur

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/a6c4ed00-38bc-4511-934a-66dba289b2d1) | ![2](https://github.com/brave/brave-browser/assets/128532965/99508852-2823-48b1-a881-9784fe2eaa5d) |

https://github.com/brave/brave-browser/assets/128532965/3d2a25e0-24e1-4bec-999b-82e6f0651919
