### ISSUE TITLE
Add metric for HTTPS-Only/First mode

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#35819]
Add a weekly metric for HTTPS-Only and HTTPS-First modes:

If your "upgrade connections to HTTPS" setting is set to "standard" or "strict", how many page requests failed the auto-upgrade to HTTPS this week?
`Brave.Core.FailedHTTPSUpgrades`

0. 0%
1. Above 0%, less than or equal to 0.25%
2. Above 0.25%, less than or equal to 0.5%
3. Above 0.5, less than or equal to 1%
4. Above 1%, less than or equal to 3%
5. Above 3%, less than or equal to 7%
6. Greater than 7%

cc @arthuredelstein

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | 2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS | Windows 10 Version 22H2 (Build 19045.4170)
```

**Comment by GeetaSarvadnya** [comment]
@DJAndries when I visit 1 HTTP site ans 5 https sites, I see metrics response value `6`. if I visit 4 http sites and 1 https site, I get response value as `6`. If I visit only one http site, I get response value as `6`. For almost all combinations I get response value `6`. I what condition we supposed to see the response values 1 to 5?

**Comment by DJAndries** [comment]
@GeetaSarvadnya in order to test other metric values, please ensure that the "failed upgrade" percentage is low enough to fit in the other buckets. each example that you mentioned describes a percentage above 7%. for example, for a percentage of 5%, you'll need to make one http request and 19 https requests.

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.65.96`

**Comment by kjozwiak** [comment]
@GeetaSarvadnya mind just doing a quick spot check now that we've uplifted https://github.com/brave/brave-core/pull/22896 into `1.65.x` via https://github.com/brave/brave-core/pull/22929. Shouldn't need to run through a full verification as we've already done that via https://github.com/brave/brave-browser/issues/35819#issuecomment-2031695398 and https://github.com/brave/brave-core/pull/22896#issuecomment-2049008486.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.65.110 Chromium: 124.0.6367.29 (Official Build) (64-bit)
-- | --
Revision | 6271fdd3c799c0db71c1e6ca8c83888a7bbbfbd2
OS | Windows 10 Version 22H2 (Build 19045.4046)

```

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.65.112 Chromium: 124.0.6367.29 (Official Build) (64-bit) 
Revision	1ccdfe627ad458201908007edf699da1f3bfc02b
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

<details><summary>Case: Fresh Profile</summary>

- Ensured that `Brave.Core.FailedHTTPSUpgrades` is not shown in `brave://local-state` on fresh profile

<img width="571" alt="Screenshot 2024-04-15 at 3 19 36 PM" src="https://github.com/brave/brave-browser/assets/17885425/3c0f4e42-e0a7-4d07-8855-2650788fbdbe">

</details>

<details><summary>Case: Loading 12+ secure URLs (HTTPS)</summary>

- Ensured that `Brave.Core.FailedHTTPSUpgrades` is shown and contains value of "0" after reaching 12 secure sites and restarting browser. 

<img width="571" alt="Screenshot 2024-04-15 at 3 25 44 PM" src="https://github.com/brave/brave-browser/assets/17885425/6bbfb09f-83a9-4ebd-9f2c-288e38b7f17d">


</details>

<details><summary>Case: Loading insecure sites (HTTP)</summary>

- Ensured that `Brave.Core.FailedHTTPSUpgrades` has a value of "6" after opening 7 insecure and 7 secure webpage.

![Screenshot 2024-04-16 at 11 20 41 AM](https://github.com/brave/brave-browser/assets/17885425/f95ec1bd-2adc-44dd-85ad-67f958f8b249)

</details>
