### ISSUE TITLE
[HackerOne] Wayback machine issue

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#35820]
https://hackerone.com/reports/2356212 reported by [newfunction](https://hackerone.com/newfunction)

Internal issue: https://github.com/brave/reviews/issues/1514

**Comment by simonhong** [comment]
Working on this.

**Comment by stephendonner** [comment]
## Verified `PENDING` using

```
Brave | 1.65.80 Chromium: 123.0.6312.29 (Official Build) nightly (64-bit)
-- | --
Revision | cd0c2b9c6f07e8f01724294c8d7e37393a8c3a38
OS | Windows 10 Version 22H2 (Build 19045.4170)
```

**Comment by bsclifton** [comment]
Removing milestone - this was reverted with https://github.com/brave/brave-core/pull/22584

**Comment by bsclifton** [comment]
Employees can see conversation here for more info:
https://bravesoftware.slack.com/archives/CKNHM4RTK/p1710355668186289

We can try a different attempt. The modal was a bit much - interrupts the browsing flow

**Comment by simonhong** [comment]
@aguscruiz We added per-tab modal dialog but some folks felt that it's aggressive as it prevents interacting with web contents till it's dismissed. so it could make users disable forever easily.
Instead, there was some ideas such as page action icon(ex, news feed or pwa installation button) in omnibox.
When a page is not available, we also could show page action and modal dialog could be launched when it's clicked.
WDYT? cc @rebron
