### ISSUE TITLE
text color can be hard to see depending on the background color in send screen

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#35826]
cc @Douglashdaniel since I'm pretty sure you were working on this. Seems like we should automatically determine the text color based on the background color, but I'm not sure how best that would work with our design system. @minkyeongshin or @kleantzogu might have some suggestions here.

![image](https://github.com/brave/brave-browser/assets/23125059/92535e24-1359-48d6-a40f-b9cdfcab3936)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.97 Chromium: 124.0.6367.118 (Official Build) beta (64-bit)
-- | --
Revision | 94909f2aaefd7a8137c8b4fa27235378e79231e3
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22720](https://github.com/brave/brave-core/pull/22720)
- Verified text colour is easily legible depending on background colour on send screen
- More details [here](https://github.com/brave/brave-browser/issues/34581#issuecomment-2095337266)
