### ISSUE TITLE
Wallet Accounts page crash (show blank) with a specific address is imported.

### ISSUE THREAD

**Issue by Zergity** [brave/brave-browser#35821]
## Description 
Wallet Accounts page crash (show blank) with a specific address is imported.
All other pages works fine.
Without the specific address imported, everything works fine.

## Steps to Reproduce
   1. Import an account using private key
   2. Open Wallet Accouts page
   3. See that the page is blank

Both with brave://wallet/crypto/accounts and Accounts tab in dropdown menu.

## Actual result:
![image](https://github.com/brave/brave-browser/assets/37166829/37f52cbe-e744-47dc-8801-fcafe844132b)

![image](https://github.com/brave/brave-browser/assets/37166829/e6268eb4-c4cd-4634-a342-22e09c3edee8)

## Expected result:
Accounts should display properly.

## Reproduces how often: 
Everytime with my address. Please PM me for the address, I don't want to publish it.

## Brave version (brave://version info)
Brave	1.62.156 Chromium: 121.0.6167.139 (Official Build) (64-bit) 
Revision	800674fc2c6162087525ed9b5bfc07230296b27d
OS	Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

## Miscellaneous Information:
Contact me for may public address to reproduce the problem.

**Comment by archerallstars** [comment]
This could be related/duplicated to issue #35782, in which the PRs in issue #35612 could be the cause of the issue, since the wallet work fine before Brave 1.62.156.

**Comment by Douglashdaniel** [comment]
Please see https://github.com/brave/brave-browser/issues/35782#issuecomment-1932588696 for temp work around. Working on a fix for this!

**Comment by kjozwiak** [comment]
Closing the above as this was fixed via https://github.com/brave/brave-core/pull/21498 as per @Douglashdaniel.

**Comment by kjozwiak** [comment]
The above requires `1.62.165` or higher for `1.62.x` verification 👍

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/35782#issuecomment-1943357580
