### ISSUE TITLE
Accounts are not listed for BTC/ZCash on token details page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#35823]
## Description 

Accounts are not listed for BTC/ZCash on token details page

## Steps to Reproduce

   1. Create wallet
   2. Enable ZCash via flags
   3. Ensure Bitcoin account is created during onboarding
   4. Create ZCash account
   5. Go to portfolio and select BTC/ZCash
   6. Both of them don't list accounts created

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/443f0183-40aa-45e6-b883-94c48636ed19

## Expected result:
Should list accounts on token detail page

## Reproduces how often: 

Easy

## Brave version (brave://version info)

 
Brave | 1.64.50 Chromium: 121.0.6167.139 (Official Build) nightly (64-bit)
-- | --
Revision | 1f1dd78aa04299ea140eb7dd38811e88f1311502
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:
cc: @Douglashdaniel @cypt4 @supermassive

**Comment by Douglashdaniel** [comment]
@srirambv this is expected behavior, the `Asset Details` page will only display `Accounts` with balances. 

![Screenshot 12](https://github.com/brave/brave-browser/assets/40611140/9c189ad1-d959-4099-b598-18b279a0a9ae)

**Comment by srirambv** [comment]
Rechecked the issue and works as expected. CLosing as invalid
