### ISSUE TITLE
Change Leo onboarding opt-in copy on iOS

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#35839]
Change title to `Chat Privately with Brave Leo`
Change button CTA to `I understand`
See body in https://docs.google.com/document/d/1DOj1RSSmZ82ER1aGYlFEkM1nmreT998Fe7bsKr1Y1T0/edit#heading=h.lszc9i58xq4q

Screenshot on desktop:
<img width="529" alt="Screenshot 2024-02-06 at 9 33 42 AM" src="https://github.com/brave/brave-browser/assets/4730197/11c6cef1-b08b-4088-99fc-a5ed46afcec4">

Desktop and Android issue for reference: https://github.com/brave/brave-browser/issues/35355

**Comment by Brandon-T** [comment]
This is already in the iOS build :)
