### ISSUE TITLE
[Leo] Refresh animation when pull Leo panel up

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#35838]
## Description 
https://github.com/brave/reviews/issues/1445#issuecomment-1927197935 , point#3

>Pulling Leo's window always triggers the reload animation. I could imagine this would be very annoying to users.

## Steps to reproduce 

   1. Open Leo
   2. Pull panel up

## Actual result 
   3. see refresh spinner

## Expected result
   3. must not show refresh spinner

## Issue reproduces how often 
Easily

### Additional information

https://github.com/brave/reviews/assets/10810135/be49067f-361b-4239-8282-8dc001c5985c

**Comment by kjozwiak** [comment]
The above requires `1.63.154` or higher for `1.63.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.63.154
Chromium: 121.0.6167.184 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:Followed the steps from https://github.com/brave/brave-browser/issues/35838#issue-2121435197

**ACTUAL RESULTS:**
- Verified that no refresh spinner is shown when pulling Leo panel up

NOTE: Observe this issue #36043
---------------------------

https://github.com/brave/brave-browser/assets/128532965/2c1c29e3-953a-40e2-a788-a306e0866fbd
