### ISSUE TITLE
Cleanup brave_shields component

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#35837]
## Description 

This cleanup is needed to use more components in iOS and a number of issues related to iOS. No functional changes are done in this task

**Comment by mkarolin** [comment]
@cuba, please, add the appropriate labels: `QA/Yes` or `QA/No` and `release-notes/include` or `release-notes/exclude`

**Comment by LaurenWags** [comment]
@cuba reminder to please add labels from @mkarolin comment above. thanks.

**Comment by cuba** [comment]
@LaurenWags oops sorry I saw your message then somehow lost it. I added QA/No because its really just file moves
