### ISSUE TITLE
Inconsistent profile check for Leo 

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#35835]
When doing AIChat group policy work, I found out our profile policy checking is not always the same. It allows users to toggle Leo panel in non regular window. ex.
<img width="1218" alt="Screenshot 2024-02-05 at 16 48 52" src="https://github.com/brave/brave-browser/assets/11330831/b526121f-5aa7-4bae-9ad8-e4846713e416">
<img width="1216" alt="Screenshot 2024-02-05 at 16 57 22" src="https://github.com/brave/brave-browser/assets/11330831/9f5dbe49-f1e0-40e2-a281-445d72b32b33">

We need consistent checks across all Leo features and also make it test guarded.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.64.96 Chromium: 122.0.6261.111 (Official Build) beta (x86_64)
-- | --
Revision | fb9feca2d1f25ea20265752e8ecdf548a6925bd4
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.64.96`
2. launched Brave
3. opened the respective new-window types, below
4. loaded `https://brave.com/ads-manager/`
5. clicked on the `Turn on Speedreader` icon in the URL bar
6. confirmed no `Leo` icon in the resulting `Speedreader` toolbar

`Private Window`

example | example
---------|---------
<img width="1275" alt="Screen Shot 2024-03-06 at 11 14 26 AM" src="https://github.com/brave/brave-browser/assets/387249/d5b7f75a-cad5-4629-83ed-593aa9768b32"> | <img width="1275" alt="Screen Shot 2024-03-06 at 11 14 31 AM" src="https://github.com/brave/brave-browser/assets/387249/63078d51-dc5d-4f20-8b03-d08b421017de">

`Private Window with Tor`

example | example
---------|---------
<img width="1275" alt="Screen Shot 2024-03-06 at 11 15 12 AM" src="https://github.com/brave/brave-browser/assets/387249/15c9b951-1b8b-4e88-8917-e1f73383d100"> | <img width="1275" alt="Screen Shot 2024-03-06 at 11 15 21 AM" src="https://github.com/brave/brave-browser/assets/387249/7d762c41-ab76-42f2-9e73-467c3fbb4499">

`Private Window with Tor`, `.onion`

example | example
---------|---------
<img width="1275" alt="Screen Shot 2024-03-06 at 11 15 57 AM" src="https://github.com/brave/brave-browser/assets/387249/a7aee0d3-cb06-41c3-b0e6-c05843e6ecc0"> | <img width="1275" alt="Screen Shot 2024-03-06 at 11 16 13 AM" src="https://github.com/brave/brave-browser/assets/387249/29aef6e3-f80d-4325-85d5-8449a7d94a3e">

`New Guest Profile`

example | example
---------|---------
<img width="1779" alt="Screen Shot 2024-03-06 at 11 16 30 AM" src="https://github.com/brave/brave-browser/assets/387249/fe4bf32b-9526-41cd-8e4f-d514995a8582"> | <img width="1779" alt="Screen Shot 2024-03-06 at 11 16 34 AM" src="https://github.com/brave/brave-browser/assets/387249/c14c10a3-366d-4c65-9ecb-106ce4895266">

**Comment by stephendonner** [comment]
## Verified `PENDING` using

```
Brave | 1.64.97 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | f7c8f13563bfe1063db456650cb43207e1c960c0
OS | Windows 10 Version 22H2 (Build 19045.4123)
```

**Comment by stephendonner** [comment]
`Private window`

example | example
---------|---------
<img width="1392" alt="Screen Shot 2024-03-14 at 2 34 34 PM" src="https://github.com/brave/brave-browser/assets/387249/68b1ec06-add7-4da6-93a4-f2260e320298"> | <img width="1392" alt="Screen Shot 2024-03-14 at 2 35 21 PM" src="https://github.com/brave/brave-browser/assets/387249/025dccd2-4768-43f7-8db3-c0566784624b">


`Private window with Tor`

example | example
---------|---------
<img width="1392" alt="Screen Shot 2024-03-14 at 2 38 11 PM" src="https://github.com/brave/brave-browser/assets/387249/0954f870-5de6-4a38-9bef-65e607977189"> | <img width="1392" alt="Screen Shot 2024-03-14 at 2 38 17 PM" src="https://github.com/brave/brave-browser/assets/387249/25deaeaf-62c0-4595-b93d-f0844174017b">


`Private window with Tor`, `.onion`

example | example
---------|---------
<img width="1392" alt="Screen Shot 2024-03-14 at 2 39 13 PM" src="https://github.com/brave/brave-browser/assets/387249/2daa0927-4f1b-4d22-b7ca-a9ab1013df07"> | <img width="1392" alt="Screen Shot 2024-03-14 at 2 39 22 PM" src="https://github.com/brave/brave-browser/assets/387249/5347a058-81c1-472f-9c8d-d55c23141935">


`New Guest Profile`
