### ISSUE TITLE
Widevine Support for Linux ARM64

### ISSUE THREAD

**Issue by wxllow** [brave/brave-browser#35836]
## Description 

Widevine on ARM64 Linux is now possible thanks to the [`widevine-installer`](https://github.com/AsahiLinux/widevine-installer/tree/main) script from the Asahi Linux team and works in Chromium and Firefox. However, when trying to copy the created `WidevineCdm` directory to the Brave directory (`/opt/brave.com/brave`), which would enable Widevine to work, Widevine is unexpectedly unusable in Brave, regardless of whether you attempt to enable it in settings. When trying to enable it in settings, it will automatically be disabled on reload.

## Steps to Reproduce

   1. Install brave (`sudo dnf install brave`)
   2. Run widevine-installer script: `sudo ./widevine-installer` (https://github.com/AsahiLinux/widevine-installer)
   3. Copy WidevineCdm to Brave lib directory: `sudo cp -r /usr/lib64/chromium-browser/WidevineCdm /opt/brave.com/brave/WidevineCdm`
   4. Run Brave and try visiting a site with Widevine DRM (ex. https://bitmovin.com/demos/drm)

## Actual result:

Widevine is not detected, usable, nor able to be enabled.

## Expected result:

Widevine should be usable on supported sites when enabled in settings

## Reproduces how often: 

Easily can be reproduced

## Brave version (brave://version info)

1.62.156 Chromium: 121.0.6167.139 (Official Build) (64-bit) on Fedora Linux Asahi Remix 39

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  N
- Does the issue resolve itself when disabling Brave Rewards?  N 
- Is the issue reproducible on the latest version of Chrome?  N

**Comment by rebron** [comment]
cc: @mihaiplesa @mherrmann @simonhong

**Comment by mherrmann** [comment]
@wxllow can you please try following these instructions? https://support.brave.com/hc/en-us/articles/23881756488717-How-do-I-enable-Widevine-DRM-on-Linux

**Comment by wxllow** [comment]
> @wxllow can you please try following these instructions? https://support.brave.com/hc/en-us/articles/23881756488717-How-do-I-enable-Widevine-DRM-on-Linux

This works perfectly! Thank you

**Comment by mherrmann** [comment]
Ok, then I will go ahead and close this issue :-)
