### ISSUE TITLE
Remove Export option for Zcash accounts

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#35849]
## Description 

Remove Export option for Zcash accounts

## Steps to Reproduce

   1. Enable flag and create a Zcash account
   2. Open Accounts tab and select Zcash
   3. Click on account menu, shows Export which should not be shown

## Actual result:

![Export Zcash](https://github.com/brave/brave-browser/assets/17010094/446f7caa-0da0-4db5-888e-3c9c26b77654)

## Expected result:
No export option similar to BTC

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.64.51 Chromium: 121.0.6167.139 (Official Build) nightly (64-bit)
-- | --
Revision | f5082bd02ce5a81096046dd0c7402bd5a5898ffd
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @cypt4

**Comment by kjozwiak** [comment]
The above requires `1.63.165` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.165 Chromium: 122.0.6261.94 (Official Build) (64-bit)
-- | --
Revision | fed0fcc915f6d9e1db871202f0304c8d582a73de
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#22120](https://github.com/brave/brave-core/pull/22120)
- Verified Export account option is not shown for BTC/ZEC accounts

https://github.com/brave/brave-browser/assets/17010094/7e2472b4-f3ed-4c20-9f71-a192054bbc82
