### ISSUE TITLE
Nebula: add differential privacy sampling to P3A

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#35841]
## Description 

Per recent discussions, we want to add differential privacy to the STAR protocol used to report how features are used in the browser. The first phase of this is just to add sampling to the current reports: some percentage of the time the client submits a measurement with the value or tag of the outer layer replaced with some random value. This addresses some of the leakage from undecodable tags in STAR by adding plausible deniability to the threshold anonymity.

Proposed parameters, derived from differential privacy ε=1 and δ = 10^-8:
- sampling rate *p* = 0.105 (10.5% of measurements are submitted as before)
- aggregation threshold *K* = 20

By introducing sampling we enforce better privacy bounds even with the lower aggregation threshold (currently *K*=50).

## Rough plan

- [ ] Introduce sampling by perturbing encoded P3A values before they are sent to the randomness server
- [ ] Mark nebula vs. constellation P3A submissions so they can be processed separately by the stats backend. Perhaps a `Brave-Aggregation-Threshold` http header can mark the difference.
- [ ] Implement feature switches to control rollout. At first we want to try just two questions, maybe one with a large reporting cohort and one with a small. Then a second would enable Nebula submission for all P3A questions.

**Comment by rillian** [comment]
cc @AliShahin @DJAndries

**Comment by kjozwiak** [comment]
The above requires `1.68.101` or higher for `1.68.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.68.101 Chromium: 126.0.6478.126 (Official Build) beta (64-bit)
-- | --
Revision | ffa8411f4c8fe36c0e399f60ef7c24b3cf7d7402
OS | Windows 10 Version 22H2 (Build 19045.4529)
```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version12` running `Bravemonoarm64.apk_1.68.101`

- Verified the test plan from https://github.com/brave/brave-core/pull/22522

### Test Plan

<details>
<summary>Test plan verification_PASSED</summary>

- Confirmed that each collector request have the ` Brave-P3A-Constellation-Threshold` header value `20` or `50`

slow | express | typical | slow | express | typical 
------|---------|-------|------|------|------
![image](https://github.com/brave/brave-browser/assets/38657976/bf8230e1-d7bd-4fd8-b341-cfe3fcc2f9f4) | ![image](https://github.com/brave/brave-browser/assets/38657976/79c88140-1669-4a89-a404-6462e8325cbf) | ![image](https://github.com/brave/brave-browser/assets/38657976/92677b80-f05f-4ded-8889-cc43f8c2950a) | ![image](https://github.com/brave/brave-browser/assets/38657976/2a6f42f9-bb01-4651-9a1e-f19b74110827) | ![image](https://github.com/brave/brave-browser/assets/38657976/aad79d8e-dd42-4d77-a363-bb041e8a3e65) | ![image](https://github.com/brave/brave-browser/assets/38657976/b1a35129-b216-4b4a-b77d-30108dcc20db)


To view all the collector metrics metrics

Example | Example
----------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/fc5d7772-a6be-4747-a5df-f99dbf80cff6) | ![image](https://github.com/brave/brave-browser/assets/38657976/f908ff52-db8c-4d6e-ba7b-38f3d46473ec)

</details>
