### ISSUE TITLE
The minimum tipping amount of `0.002` BAT displays the`0.00` corresponding USD value

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#35850]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/34780

## Steps to Reproduce

   1. NA
  

## Actual result:

Example | Example
----------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/215c488c-0fb7-4616-bbda-c636416410b2) | ![image](https://github.com/brave/brave-browser/assets/38657976/b932e579-0757-4c10-ad99-fd4bc645f77e)

## Expected result:

Should it be 0.000427 USD?

## Reproduces how often: 

Easy
## Brave version (brave://version info)

<html>
<body>

Brave | 1.63.146 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | cb9ee9c98182a64716e4237bf1202f1aec3bcff8
OS | Windows 10 Version 22H2 (Build 19045.3930)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @Miyayes @zenparsing

**Comment by Miyayes** [comment]
Would putting more decimals of precision on the fiat/USD amount help?

**Comment by Miyayes** [comment]
If less than 1 cent, then add as many decimals as needed to make the value non-zero. @zenparsing

**Comment by GeetaSarvadnya** [comment]
Up to `0.022 BAT` the USD value is displayed as 0.00USD
![image](https://github.com/brave/brave-browser/assets/38657976/7dfb01a9-8805-439a-b68a-f17366b8b61b)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (x86_64)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | macOS Version 13.6.4 (Build 22G513)
```
