### ISSUE TITLE
Support Solana Priority Fees

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#35866]
https://docs.solanalabs.com/proposals/fee_transaction_priority
https://solana.com/developers/guides/advanced/how-to-use-priority-fees

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.124 Chromium: 127.0.6533.73 (Official Build) beta (64-bit)
-- | --
Revision | dbc9035349f74e493f3293d93f4cbf35c597dfec
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#23214](https://github.com/brave/brave-core/pull/23214)
- Verified `Set Compute Unit Limit` and `Set Compute Unit Price` instruction are listed on [Send transaction](https://explorer.solana.com/tx/2yjXzU1P1W2YEiSeF571PtZuqw8o6ZrDZn31tJDSSJ2NKotiDyff861Mu9Zt3dt8iDbHCYK9EqgmyC65fCFJSLXU)
- Verified `Set Compute Unit LImit` or `Set Compute Unit Price` instruction is listed on [Swap Transaction](https://explorer.solana.com/tx/5ntJ5V6u2S5ceWssXK92F6A74QxHthwP6JMpZ6Trfnh9s1mLbUPptm1JgVoEyVpGWdFuFyyLgy8ue9NdGdDppcNH)
- Verified on [Dapp transaction](https://explorer.solana.com/tx/5nLYVvPNdMcSoaEpfxo8PpvpqJYGfgqV7A8SKvJWvyJCBTNDt4e3hgXKEwPfyBMUzPbVw41u2BCYft8yQ5kBoBsS) at least one `Set Compute Unit LImit` or `Set Compute Unit Price` instruction is listed

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.69.152 x64 build

- Verified steps from [brave/brave-core#23214](https://github.com/brave/brave-core/pull/23214)
- Verified `Set Compute Unit Limit` and `Set Compute Unit Price` instruction are listed on [Send transaction](https://explorer.solana.com/tx/5hFyf1ibUMbysWsVWLawSzbspo7G3csVsaFaci3DCKiCFC7oMsWuSi3Suz5JhyZYtrJHdbPiNbt8HJsV6NCDFp4i)
- Verified `Set Compute Unit LImit` or `Set Compute Unit Price` instruction is listed on [Swap Transaction](https://explorer.solana.com/tx/4qkCVLgtjYgnWCdkqdpjmTJD9CRRWfc4gNLGVzvrPom4caup2crhmFv3kjiBpTnZEWb9UbsEsyB9i2HQDpfrMCpe)
- Verified on [Dapp transaction](https://explorer.solana.com/tx/4ZfuEzrwEx688gfBNZdvKnomEPQgXARbMQFS7U1isaCnRodjuGaj4Lvmy6VVaAEQoDH7gACH4xmNhaCPqYTu51U4) at least one `Set Compute Unit LImit` or `Set Compute Unit Price` instruction is listed
