### ISSUE TITLE
Refactor deprecated local-storage items deletion logic

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#35863]
## Description 

We should refactor this logic so that any local-storage key added to the deprecated keys object will automatically be removed

**Comment by srirambv** [comment]
Verification passed on <html>
<body>

Brave | 1.64.104 Chromium: 123.0.6312.46 (Official Build) (64-bit)
-- | --
Revision | 0ca3d372cf8aab96fafdd75f5c5c8d2012bc0cc6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from [brave/brave-core#21940](https://github.com/brave/brave-core/pull/21940)
- Verified adding a local-storage item and reloading wallet page removes it 

https://github.com/brave/brave-browser/assets/17010094/38d164a0-48c0-4294-ab13-1511cec2cfa4
