### ISSUE TITLE
Unable to load this website in Brave (chrome can)

### ISSUE THREAD

**Issue by cyfung1031** [brave/brave-browser#35862]
https://www.it-ft.com/

Excepted (Chrome, Firefox, Edge, Safari):

<img width="1510" alt="Screen Shot 2024-02-08 at 1 24 13" src="https://github.com/brave/brave-browser/assets/44498510/c8aa8579-9d0e-4cfe-8a08-4a5531aa8c95">

Actual (Brave, including Private Window Mode):
<img width="1469" alt="Screen Shot 2024-02-08 at 1 24 25" src="https://github.com/brave/brave-browser/assets/44498510/b9df8293-eb04-4943-a937-fcfd5b0e8cfe">

**Comment by Skyyie** [comment]
I can open it here in Brave browser. Seems to open without issues.

**Comment by bsclifton** [comment]
Opens for me too - although I was able to reproduce the problem by opening dev tools. Page detects this and redirects to https://www.it-ft.com/error.

That behavior is the same in Chrome too. I'm going to go ahead and close this issue out - but please comment here and re-open if you have more information @cyfung1031. Thanks!
