### ISSUE TITLE
Rewards Balance in Wallet is being summed into BAT on Ethereum token balance

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35873]
## Description 

BAT `Rewards Balance` is being summed into `BAT on Ethereum` token balance in the `Portfolio` when grouping by `None`

## Steps to Reproduce

   1. Connect your `Rewards` account to a custodial partner
   2. Open the `Wallet` and nav to the `Portfolio` page
   3. Group your portfolio by `none`
   4. BAT `Rewards Balance` is being summed into `BAT on Ethereum` token balance

## Actual result:

![Screenshot 15](https://github.com/brave/brave-browser/assets/40611140/7def36f9-1b40-40b0-81af-c4b3183f01da)

## Expected result:
Should not be summed together.

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21949](https://github.com/brave/brave-core/pull/21949)
- Verified Rewards balance in wallet is not being summed into BAT on Ethereum token balance
![image](https://github.com/brave/brave-browser/assets/17010094/647a4511-d78a-4167-bf81-4b2d667a9c2e)
