### ISSUE TITLE
Remove Icon Stack Background

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35877]
## Description 

We need to remove the `Icon Stack` background

![Screenshot 18](https://github.com/brave/brave-browser/assets/40611140/75fd391b-8da9-4cfc-9171-7086e766c64f)

## Expected result:

![Screenshot 19](https://github.com/brave/brave-browser/assets/40611140/db329907-72e1-4c5d-aadb-9a85c2d4eaa1)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21950](https://github.com/brave/brave-core/pull/21950)
- Verified background for icon stack is now removed
- Verified on both light and dark theme

Light | Dark
-- | --
![image](https://github.com/brave/brave-browser/assets/17010094/a677a631-1289-4c8e-8dd5-83302fbb07d9) | ![image](https://github.com/brave/brave-browser/assets/17010094/94ae21b9-5e01-45bf-9007-ee387dff30be)
