### ISSUE TITLE
Implement additional ad event confirmations

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#3587]
## Description 
The current implementation of ad confirmations sends those secure confirmations in the event of an ad being viewed (Confirmation type: view).  However, to complete our requirements for campaign reporting, we need to implement the following additional confirmations attached to the following events:

- Confirmation upon clicking through on an ad (Confirmation type: click)
- Confirmation for when an ad is dismissed (X'ed out) (Confirmation type: dismiss)
- Following a click, a confirmation that is sent after the user has the landing page open for 10 seconds (Confirmation type: landed)

**Comment by bsclifton** [comment]
Updated milestone after https://github.com/brave/brave-core/pull/1923 was merged

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.63.31 Chromium: 73.0.3683.75 (Official Build) beta (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

- `*Timed out ads*'After getting ads notification waited for around 2mins until ads notification vanishes without any user interaction. Verified the confirmations.json file after notification got vanished.

clicked, viewed, dismissed and landed Ads are redeemed on Ads Serve and timed out Ads are not redeemed on Ads Server.

![image](https://user-images.githubusercontent.com/38657976/55650172-a1d85900-5802-11e9-8110-52b4341b092d.png)

- Verified the test plan from https://github.com/brave/brave-core/pull/1890
- Verified the description mentioned in the issue
