### ISSUE TITLE
Update the text for p3a and usage settings

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#35871]
## Description 

Update the text in brave://settings/privacy
See screenshots below.

from:
Allow privacy-preserving product analytics (P3A)
This completely anonymized info helps Brave estimate the overall usage of certain
features and make them better for you.

Automatically send daily usage ping to Brave
This anonymous, private ping lets Brave estimate active users.

to: 
Allow privacy-preserving product analytics (P3A)
These private responses help Brave estimate the overall usage of certain
features and make them better for you.

Automatically send daily usage ping to Brave
This private ping lets Brave estimate active users.

## Actual result:

<img width="715" alt="Screenshot 2024-02-07 at 9 56 32 AM" src="https://github.com/brave/brave-browser/assets/5951041/9467a73d-f300-468c-b08c-010122b3e775">

## Expected result:
![screen_shot_2024-02-06_at_15 45 06_720](https://github.com/brave/brave-browser/assets/5951041/a3ab6578-6c47-4858-96c4-3e50978c79e8)

## Brave version (brave://version info)

Target version for release 1.64.x.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by stephendonner** [comment]
## Verified `PASSED` using

### Steps:
1. installed `1.64.81`
2. launched Brave
3. loaded `brave://settings/privacy`

### Confirmed text changes match those in `Expected Results`


<img width="1162" alt="Screenshot 2024-02-21 at 12 10 33 PM" src="https://github.com/brave/brave-browser/assets/387249/9cc471d8-25df-4c20-9385-fc27d9810a88">
