### ISSUE TITLE
Stop spawning DataDecoder process for sanitizing JSON

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#35886]
`APIRequestHelper` still uses a lot of DataDecoder instances.
We hoped that `BUILD_RUST_JSON_READER/enable_rust_json` would be enabled soon, but it's still fair from production
https://source.chromium.org/chromium/chromium/src/+/main:build/config/rust.gni;l=112?q=enable_rust_json%20lang:gn

The suggested way is to pass the string to rust, decode than, serialize back and pass to C++. It's less efficient that `BUILD_RUST_JSON_READER`, but still good enough comparing with out-of-process impl. Also DataDecoder for Android decoder uses the similar approach (using java json impl)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | 2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified Portfolio balances loads correctly
- Verified token balance loads correctly on token details page
