### ISSUE TITLE
NTPSI will never be shown on restored NTP

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#35889]
## Steps to Reproduce

1. Clean profile
1. Enable rewards and ads
1. Open several NTP 
1. Restart Brave
1. Wait for ads initialization
1. Activate the restored NTP

## Actual result:
NTP SI is not served nor shown

![ntpsi2](https://github.com/brave/brave-browser/assets/34715963/7350f1e3-007d-4b6c-9c23-939b1630f986)

## Expected result:
NTP SI is served and shown

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.62.161 Chromium: 121.0.6167.139 (Official Build) (64-bit)
-- | --
Revision | 9afaacd1500fdbd60ed4500b63b9ab85597ef933
OS | Linux

cc @tmancey @aseren @iambrianfung @LaurenWags

**Comment by tmancey** [comment]
Closing as wont fix, because choosing blank new tab pages will not show new tab takeover images.
