### ISSUE TITLE
Update Reset Rewards profile text (Feb 2024)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#35881]
### Current 

Text portion:

>By resetting, your current Brave Rewards profile will be deleted and you will start again with a completely new Brave Rewards profile. Before proceeding, learn more about resetting, just to be safe.

### New

By resetting, your current Brave Rewards profile will be deleted, and Brave Rewards will no longer be enabled. If you enable Brave Rewards again later, you will start with a new profile. Read our [support article about resetting](https://support.brave.com/hc/en-us/articles/10007969237901-Resetting-Brave-Rewards) for more details.

**Comment by mkarolin** [comment]
STR:
1. Open Brave and navigate to brave://rewards/
2. Click on Reset
3. Verify the new text

**Comment by LaurenWags** [comment]
Verified with

```
Brave	1.65.88 Chromium: 123.0.6312.58 (Official Build) beta (x86_64) 
Revision	e260e641e7db9e88b9b51112f4f00febf5a2f5eb
OS	macOS Version 13.6.4 (Build 22G513)
```

Verified test plan from https://github.com/brave/brave-browser/issues/35881#issuecomment-1967878282 and text from https://github.com/brave/brave-browser/issues/35881#issue-2124289360.
Confirmed the link in the text navigates to `https://support.brave.com/hc/en-us/articles/10007969237901-Resetting-Brave-Rewards` as per https://github.com/brave/brave-browser/issues/35881#issue-2124289360.

1.64.109 | 1.65.88
--- | ---
<img width="704" alt="Screenshot 2024-03-21 at 9 40 42 AM" src="https://github.com/brave/brave-browser/assets/28145373/9c0f4eb6-f811-44f0-acf9-20a252fbcba1"> | <img width="641" alt="Screenshot 2024-03-21 at 9 40 48 AM" src="https://github.com/brave/brave-browser/assets/28145373/f47cb74d-9e81-40e1-9cbc-3998ec019ffa">

Note, confirmed UI/style differences are ok/expected as per https://bravesoftware.slack.com/archives/CB0KCRCQN/p1711027071659509.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` runnig `Bravemonoarm64.apk_1.65.96`


Verified test plan from https://github.com/brave/brave-browser/issues/35881#issuecomment-1967878282 and text from https://github.com/brave/brave-browser/issues/35881#issue-2124289360.
Confirmed the link in the text navigates to `https://support.brave.com/hc/en-us/articles/10007969237901-Resetting-Brave-Rewards` as per https://github.com/brave/brave-browser/issues/35881#issue-2124289360.

1.64.109 | 1.65.96 
--- | --
![Screenshot_20240401_161907](https://github.com/brave/brave-browser/assets/38657976/365a9c84-ecfc-44c0-878d-524b925aebde) | ![Screenshot_20240401_161912](https://github.com/brave/brave-browser/assets/38657976/8dc0259f-c341-431e-9ed3-9445469b04e2)

![Screenshot_20240401_162000](https://github.com/brave/brave-browser/assets/38657976/1be87aea-1cb8-4754-a38c-46dd5caa0981)
