### ISSUE TITLE
updated vertical tabs design is stuck in odd state

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#35894]
## Description 

With updated design for vertical tabs, I'm stuck in a state where it's incredibly difficult to tell which tab is the active tab. @kjozwiak also experienced on Win, but after several restarts his vertical tabs sorted themselves out, mine have not (I'm on macOS).

I'm using dark theme, @kjozwiak was using light theme.

## Steps to Reproduce

Tough to tell, as of now my general setup is as below

   1. Have vertical tabs in a couple windows from prior to vertical tabs design update
   2. Get design update
   3. Be stuck (no flags enabled, no extensions)

I do have a couple pinned tabs and a couple profiles, but other profiles aren't using vertical tabs, just my default profile is.

## Actual result:

![Screenshot 2024-02-08 at 11 03 48 AM](https://github.com/brave/brave-browser/assets/28145373/d45b25f7-a5cd-44cb-a9ab-29dee9323953) | ![image](https://github.com/brave/brave-browser/assets/28145373/3cb056a5-e251-44e0-a504-8f395c3bfd19)
-- | --

## Expected result:

![Screenshot 2024-02-08 at 8 02 21 AM](https://github.com/brave/brave-browser/assets/28145373/fa43a074-0308-432a-a87d-2092e2854034) | ![image (1)](https://github.com/brave/brave-browser/assets/28145373/386e6b5e-de9c-4e73-ab2c-ab7c30d141ec)
-- | --

## Reproduces how often: 

 unsure

## Brave version (brave://version info)

 1.64.53, possibly others

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron

**Comment by bsclifton** [comment]
This should be solved now - please re-open if still an issue @LaurenWags 😄

**Comment by LaurenWags** [comment]
Thanks @bsclifton - not able to reproduce now using

```
Brave | 1.71.18 Chromium: 128.0.6613.40 (Official Build) nightly (x86_64)
-- | --
Revision | e13fa103101b5eddd5b9bb74bc79c67e1b878a74
OS | macOS Version 13.6.9 (Build 22G830)
```
