### ISSUE TITLE
Show NTT on restored NTP tabs

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#35892]
Currently, NTT will not be served nor shown on restored NTP which was just activated (See https://github.com/brave/brave-browser/issues/35889).

We could reuse restored NTP to show NTT when the NTP is made active. 

cc @tmancey @aseren @iambrianfung

**Comment by tmancey** [comment]
cc @petemill for your thoughts? As maybe this has been discussed in the past?

**Comment by tmancey** [comment]
Discussed with @iambrianfung and we won't fix because we expect users to open a new tab for those ads and it would likely only affect a small % of our users.
