### ISSUE TITLE
Unable to find the option to disable Private Window on Linux

### ISSUE THREAD

**Issue by hiensumi** [brave/brave-browser#35896]
## Description 

I have seen approaches to do so on MacOS and Windows but none of them show how to do it on Linux.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Brave version (brave://version info)

 v 1.62.156
## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@hiensumi May I ask why you're looking to hide/disable Private Window? We have an option for Private Window with Tor but not for Private Window.

**Comment by hiensumi** [comment]
> @hiensumi May I ask why you're looking to hide/disable Private Window? We have an option for Private Window with Tor but not for Private Window.

It's for parental-controls

**Comment by bsclifton** [comment]
@hiensumi you should be able to follow the instructions on https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy

Basically, you need to create a new file in the folder `/etc/brave/policies/managed/`. If that folder doesn't exist, you can create it:
```
mkdir -p /etc/brave/policies/managed/
```

With that created, you can make a new JSON file using vim, etc (in that directory). For example, you can run:
```
vim /etc/brave/policies/managed/policy.json
```

For the contents of the file, you can use what is in the example (disabling private browsing).
```
{
    "IncognitoModeAvailability": 1
}
```

That should do the trick 😄
