### ISSUE TITLE
Swap To Token List is not Loading

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35895]
## Description 

The Swap `To` token list is not loading

## Steps to Reproduce

   1. Open the `Wallet` and navigate to the `Swap` screen
   2. Select a Token to Swap `From
   3. Try to select a Token to Swap `To`
   4. The token list never loads

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/0502d1b2-ffe8-418f-9efc-448bef198dcf

## Expected result:
Token list should load

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21966](https://github.com/brave/brave-core/pull/21966)
- Verified Swap To token list loads and able to select from the list 
- Verified for different networks and works fine

https://github.com/brave/brave-browser/assets/17010094/47e9020a-dd97-4046-b10c-8de6c9c7c698
