### ISSUE TITLE
[perf] Fix the rest UI thread heavy tasks in Brave News on UI thread

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#35890]
A issue to fix the rest of https://github.com/brave/brave-browser/issues/35695
The #perf thread: https://bravesoftware.slack.com/archives/C3T9S9WKD/p1706889037498549?thread_ts=1706626988.579219&cid=C3T9S9WKD

1. large data are still stored/iterated on UI thread: https://github.com/brave/brave-core/pull/21833#discussion_r1477747653
2. other similar places in brave_news that process `base::Value` and builds something after (e.g. getting the list of sources)
3. `private_cdn_request_helper` callbacks: https://github.com/brave/brave-core/blob/master/components/brave_news/browser/brave_news_controller.cc#L429-L453

**Comment by atuchin-m** [comment]
Some extra details: this is `ParseCombinedPublisherList` work on the UI thread (19ms on a high end workstation)
![image](https://github.com/brave/brave-browser/assets/45488748/4033d88a-2449-4055-ba4c-b3a4e126df50)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.92 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 711f50838f629ac2be4d1d9592f72adecfd3c928
OS | Windows 11 Version 23H2 (Build 22631.4112)
```

1. Installed 1.70.94
2. launched Brave
3. completed onboarding
4. clicked News >> Turn on Brave News
5. confirmed Brave News feed loaded expected
6. clicked on a news card (eg. Serious Eats)
7. verified news article opened in a new tab (https://www.seriouseats.com/how-to-store-raspberries-8703108)
8. confirmed Manage subscriptions button is shown in the toolbar in the article 
9. clicked `Manage subscriptions` in the toolbar 
10. clicked `Follow` button
11. returned to Brave news feed tab
12. confirmed the publication `Serious Eats` is shown in Publishers list
13. confirmed `New content available. Reload?` button shown
14. clicked the button and news feed refreshed
15. clicked `Following` in the left side panel
16. confirmed `Serious Eats` cards are shown in the `Following` 
17. return to the news article tab 
18. clicked again `Manage subscriptions` in the toolbar 
19. clicked `Unfollow` button
20. return to news feed 
21. confirmed `Serious Eats` source is removed from Publishers list
22. clicked `New content available, Reload?` 
23. confirmed page news feed refreshed and `Serious Eats` source was removed from `Following` as well
24. clicked + sign next to `Channels` in the Panel left of the feed
25. added a channel (eg.Cars) in the Brave News dashboard
26. closed the dashboard
27. confirmed `New content available, Reload?`message shown 
28. confirmed `Cars` is shown in the Channels
29. clicked `Cars`
30. confirmed Channel feed for `Cars` is loaded


step 5-6 | step 7-10 | step 12-13 | step 15-16 | step 17-19| step 21 | step 23 | step 25 | step 30
----- | ----- | ------ | ----- | ----- | ----- | ------ | ------ | ------  
![image](https://github.com/user-attachments/assets/e9bc6f2c-983d-4dc5-b5ae-8763473d6685)|![image](https://github.com/user-attachments/assets/770efee2-1ba8-4da6-97b0-a1acbe72ac55)|![image](https://github.com/user-attachments/assets/85482da1-36f9-434a-bc91-c47d0314c6b1)|![image](https://github.com/user-attachments/assets/7cfd049c-3880-4cd0-b223-92a5a1d73d86)|![image](https://github.com/user-attachments/assets/adf74c37-7a06-474c-abb8-576e703a7601)|![image](https://github.com/user-attachments/assets/e7967c4b-241b-4596-b5b7-1dbe09a66a43)|![image](https://github.com/user-attachments/assets/98f14d57-e6f9-4f17-bc37-865cbf7db547)|![image](https://github.com/user-attachments/assets/50d80e48-8729-47ac-a1b2-907f4cc79999)|![image](https://github.com/user-attachments/assets/b6ddc3f6-d836-42e8-9d6a-542c4bdd42a5)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.70.101 Chromium: 128.0.6613.120 (Official Build) beta (64-bit) 
Revision	dc28ab38d07e9fa668801884c0c55f669ce538eb
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- [x] Ensured that Brave News feed is shown after opting in using the Brave News onboarding card.
- [x] Ensured subscribing/following sources (Channels, Popular, Suggestions) will be shown in the news feed.
- [x] Ensured that Brave News toolbar is shown when exploring the news feed. Tapping on the toolbar will open the Brave News settings page.
- [x] Ensured that updating sources will show `Load new content` button on NTP.
- [x] Ensured that subscriptions are retained after turning Brave News off and then on again.
- [x] Ensured custom RSS feeds are added to `Following` after subscribing. 
- [x] Ensured following/unfollowing sources is working and updates the feed.
- [x] Ensured scrolling through feed is smooth/consistent and does not cause performance issues.

Example | Example | Example | Example
-|-|-|-
![Screenshot 2024-09-10 at 3 47 10 PM](https://github.com/user-attachments/assets/4a7ae08c-f213-4d26-b7f6-bcea03a50989) | ![Screenshot 2024-09-10 at 3 47 14 PM](https://github.com/user-attachments/assets/2636f353-c17a-4ce8-95a1-bc38558b8004) | ![Screenshot 2024-09-10 at 3 47 35 PM](https://github.com/user-attachments/assets/2f05a1bf-b335-49b1-bf5a-248d620f8ed6) | ![Screenshot 2024-09-10 at 3 47 46 PM](https://github.com/user-attachments/assets/e91105e3-ffa3-49aa-b364-37607e51ef78)
![Screenshot 2024-09-10 at 3 53 24 PM](https://github.com/user-attachments/assets/44ab0f5a-fcc8-4a18-a96c-b84ab1af81ac) | ![Screenshot 2024-09-10 at 3 53 39 PM](https://github.com/user-attachments/assets/a9f6c79f-5697-4359-8a4d-b5e6178fc0d7) | ![Screenshot 2024-09-10 at 3 53 48 PM](https://github.com/user-attachments/assets/bd66097c-fafe-4072-a92c-493f74e2bc19) | ![Screenshot 2024-09-10 at 3 55 00 PM](https://github.com/user-attachments/assets/02fd666e-862e-4f14-bcd4-9cd1a2b443b8)
