### ISSUE TITLE
panel not showing twitch publisher info for VOD

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3590]
## Description 
Rewards panel isn't showing twitch publisher info. Found with 0.60.48, but this is occurring on 0.60.47 and 0.60.45 versions as well. This was working when both of these versions were released. 

## Steps to Reproduce

   1. Install 0.60.x version on Release Channel
   2. Enable Rewards
   3. Visit a twitch streamer (twitch.tv/jenoki works if you want a verified one)
   4. Even if user is streaming, play a VOD.
   5. After the video has been playing for a few seconds, open the panel.

## Actual result:
panel displays twitch.tv not publisher info

https://drive.google.com/file/d/1XrVrugRNCKm4CFtmoMazqCvmai1CA-Mt/view?usp=sharing

## Expected result:
Panel should show publisher info for twitch.

## Reproduces how often: 
happening consistently for me at the moment

## Brave version (brave://version info)

Brave | 0.60.48 Chromium: 72.0.3626.121 (Official Build) (64-bit)
-- | --
Revision | da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883}
OS | Mac OS X

Occurs on 0.60.47 and 0.60.45 on release channel as well.

### Reproducible on current release: yes
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Was working on above builds previously, unsure if something changed on twitch side.

Note - if twitch user is streaming and you open the panel, you will see publisher info. However, if you then open a VOD by that same user, you will see twitch.tv in the panel.

**Comment by LaurenWags** [comment]
cc @NejcZdovc @jasonrsadler

**Comment by btlechowski** [comment]
Reproduced on Windows 7

Brave | 0.60.48 Chromium: 72.0.3626.121 (Official Build) (64-bit)
-- | --
Revision | da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883}
OS | Windows 7

**Comment by GeetaSarvadnya** [comment]
Reproducible on

Brave | 0.63.15 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.65.120 Chromium: 75.0.3770.90 (Official Build) (64-bit)
-- | --
Revision | a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}
OS | Windows 7 Service Pack 1 (Build 7601.24468)

Verified the testplan from the description and https://github.com/brave/brave-core/pull/2618

![image](https://user-images.githubusercontent.com/34715963/59520433-3ed20500-8eca-11e9-9fdc-cf385326edc9.png)
