### ISSUE TITLE
Add metric for webcompat report UI source

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#35906]
Add metric for the UI source which led to the opening of webcompat reporter dialog.

If you filed a web compatibility report this week, how did you file it?
`Brave.Webcompat.UISource`

0. Via the Shields panel
1. Via the app menu (desktop only)

cc @ShivanKaul @chrismore

**Comment by ShivanKaul** [comment]
Can you not do it via the app menu on Android @DJAndries?

**Comment by DJAndries** [comment]
> Can you not do it via the app menu on Android @DJAndries?

not to my knowledge

cc @deeppandya @SergeyZhukovsky

**Comment by deeppandya** [comment]
> > Can you not do it via the app menu on Android @DJAndries?
> 
> not to my knowledge
> 
> cc @deeppandya @SergeyZhukovsky 

@darthdeus we don't have a menu option to report webcompat issues. It's only through the shield .

**Comment by ShivanKaul** [comment]
Gotcha, so then this entire question is only for Desktop, right?

**Comment by DJAndries** [comment]
> Gotcha, so then this entire question is only for Desktop, right?

It is for Desktop and Android. The answer `1` only applies to Desktop, however (as discussed on Slack).

**Comment by darthdeus** [comment]
@deeppandya Just to double check, that was an accidental ping in https://github.com/brave/brave-browser/issues/35906#issuecomment-1935056224 right? I don't think this issue relates to anything I've been working on.

**Comment by deeppandya** [comment]
> @deeppandya Just to double check, that was an accidental ping in https://github.com/brave/brave-browser/issues/35906#issuecomment-1935056224 right? I don't think this issue relates to anything I've been working on.

Sorry my bad. All good. I will update the original comment.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (64-bit)
-- | --
Revision | 5d9143e1a0812c53bdc27fd5384591254306a88c
OS | Windows 10 Version 22H2 (Build 19045.4170)
```
<details>
<summary>Brave.Webcompat.UISource = 0_</summary>

</details>

<details>
<summary>Brave.Webcompat.UISource = 1_</summary>

</details>

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.65.96`

**Comment by GeetaSarvadnya** [comment]
@DJAndries On Android I don't see `Report a broken site` settings via Hamburger menu. I am not sure how do we test the response value `1` on Android
