### ISSUE TITLE
Rounded corners creates a gap in hit testing between tabs

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#35901]
## Description 

The hit testing shape for tabs is a rounded square, where the radius is the same as the corner radius of the visible tab shape. This creates a subtle gap between the hit testing regions for adjacent tabs.

## Steps to Reproduce

   1. Open several tabs
   2. Move the cursor to the very top of a tab and then move it between two tabs

## Actual result:

There is a small space at the top of the tabstrip between tabs where neither tab is hovered.

## Expected result:

There should be no such gap.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.63.161` or higher for `1.63.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.63.161 Chromium: 122.0.6261.57 (Official Build) (64-bit)
-- | --
Revision | 37b02b4a373f40114e70cc034e491bcc8380f23a
OS | Windows 10 Version 22H2 (Build 19045.4046)
```
