### ISSUE TITLE
Close, Minimize & Maximize buttons should be larger/fill full vertical space in Windows

### ISSUE THREAD

**Issue by Skyyie** [brave/brave-browser#35918]
Close, Minimize and Maximize buttons which are at the top right corner are not at the centre, unlike Chrome and Firefox.

Here you can see it-

Brave:
![brave](https://github.com/brave/brave-browser/assets/141417720/dab74431-9d4f-4e0d-b207-2a6a61247ea4)
Chrome:
![chrome](https://github.com/brave/brave-browser/assets/141417720/fd3a3818-2744-4419-9418-6cc6b5f4ecaa)
Firefox:
![firefox](https://github.com/brave/brave-browser/assets/141417720/147436e2-1efd-46ef-a3ec-5e8e239894f1)

Brave version: 1.62.162
Windows 11 22H2

**Comment by rebron** [comment]
cc: @zenparsing @simonhong

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.65.87 Chromium: 123.0.6312.46 (Official Build) beta (64-bit)
-- | --
Revision | 2babfcf82ebba4c5dc0146d2ca66229ffd3ac02d
OS | Windows 11 Version 23H2 (Build 22631.3296)
```

Close | Minimize | Maximize 
----- | ------ | ----- 
<img width="251" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/dc334bb3-8ee0-4247-a3e0-e8c22c0eaa62">|<img width="251" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/3f3700e9-d26c-4083-987e-53574339f6b2">|<img width="251" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/bcefb40e-41df-4d32-8c1e-b0815e6b09fa">
