### ISSUE TITLE
[Zcash] Show error message when unified address without transparent part provided

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#35923]

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | 2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from [brave/brave-core#21982](https://github.com/brave/brave-core/pull/21982)
- Verified entering a wrong unified addresses or UA without a transparent part shows `Transparent part missing` error message
- Verified entering a correct unified address but without transparent part shows `Transparent part missing` error message
- Verified entering an incorrect address shows  `Transparent part missing` error message
- Verified entering a wrong transparent(t1*) address shows `Invalid recipient address` error message
- Verified entering a correct UA and transparent address doesn't show any error


https://github.com/brave/brave-browser/assets/17010094/835a3e5f-9acd-4132-97fd-042c9c0fd9d4
