### ISSUE TITLE
Update Wallet Portfolio Modal Button Styles

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#35925]
## Description 

We need to update all the `Portfolio` modal button styles to be squared to match the new designs in figma

## Expected result:

![Screenshot 3](https://github.com/brave/brave-browser/assets/40611140/3f39918d-e3d7-4bd1-ac6a-aa5d3a0a8817)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.64.74 Chromium: 122.0.6261.43 (Official Build) beta (64-bit)
-- | --
Revision | b03db955df4f1c679cb7c2ae8ebfd331d5c29276
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21983](https://github.com/brave/brave-core/pull/21983)
- Verified portfolio modal buttons are squarish as per design

Filters and Display Settings | Visible Assets | Add Custom Token | Add NFT |  Sell Asset | Remove NFT 
-- | -- | -- | -- | -- | --
![image](https://github.com/brave/brave-browser/assets/17010094/8b0a24e2-4c5c-469a-942b-16b7f67f89ea) | ![image](https://github.com/brave/brave-browser/assets/17010094/ac681b76-4488-482b-822d-87f2c932d49d) | ![image](https://github.com/brave/brave-browser/assets/17010094/144fb5e4-9925-4e4b-8904-251e6c5e5e0a) | ![image](https://github.com/brave/brave-browser/assets/17010094/e015fc7c-3df5-457b-a05b-d0df64285e80) | ![image](https://github.com/brave/brave-browser/assets/17010094/02ce2e19-d3c2-4967-8e4c-8e5cca773bfb) | ![image](https://github.com/brave/brave-browser/assets/17010094/3b04d793-feb3-4c6f-91e1-5fb1f779b5fe)
