### ISSUE TITLE
Left most tab not selected when clicking left side of the browser

### ISSUE THREAD

**Issue by Areckleh** [brave/brave-browser#35932]
## Description 

User claims that they were able in the past to click the top left of the browser to select their left most tab when in full screen mode. And is having to select directly on the left most tab to open tab. 

## Steps to Reproduce

   1. Open 2 tabs
   2. Click furtherest left on the browser to select left most tab

## Actual result:

https://www.youtube.com/watch?v=rmtEzX-e9Hk

## Expected result:
Left most tab should be selected.

## Brave version (brave://version info)

v1.62.162 (Feb 7, 2024) Windows 11 Home

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by zenparsing** [comment]
Reopening as initial implementation was reverted.

**Comment by kjozwiak** [comment]
The above requires `1.64.90` or higher for `1.64.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.64.96 Chromium: 122.0.6261.111 (Official Build) beta (x86_64)
-- | --
Revision | fb9feca2d1f25ea20265752e8ecdf548a6925bd4
OS | macOS Version 13.6.4 (Build 22G513)
```
