### ISSUE TITLE
Payment Request API's `canMakePayment` endpoint can be used for Fingerprinting, should lie behind shields

### ISSUE THREAD

**Issue by snyderp** [brave/brave-browser#3593]
Payment Request API includes a method called [canMakePayment](https://www.w3.org/TR/payment-request/#canmakepayment-method) that allows websites to determine if Brave is configured to support a given payment method.

No user interaction is required for this check to return, though Chromium applies some weak rate limiting, based on child frame's FQDN.  

This allows fingerprinting based on whether the user has a card enabled in payments, and the type of the card.  If the user has multiple cards of multiple networks, that combination reduces the user's anonymity set further.

Possible options:
* make `canMakePayment` always return true [This is what Firefox does](https://github.com/w3c/payment-request/pull/843#issuecomment-469542027)
* make `canMakePayment` always return false.  Could have web compat issues
* remove the entire web payment API.  Would make sure that websites fallback to form-based checkout pattern, but would have some pleasant-to-use cost

**Comment by tomlowenthal** [comment]
I think Firefox is going to return true in all versions of Firefox which support the API at all — meaning that the API shouldn't expose entropy not already encoded in the version number too.

**Comment by snyderp** [comment]
Yea, agreed, there was some misunderstanding on the thread (my misunderstanding of what the FF folks said).  Seems like this wouldn't get anyone more information than UA.  I'm fine closing
