### ISSUE TITLE
Replace broken bookmark count metric

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#35937]
Replace the broken bookmark count metric (`Brave.Core.BookmarksCountOnProfileLoad.2`) with a new one: `Brave.Core.BookmarkCount`

Keep all the buckets the same, except for the first bucket which should be split into 0 and 1-5.

cc @timchilds

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on
```
Brave | 1.67.85 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | d01060f5ec155e6eb64a335203663a29c0e5d81f
OS | Windows 10 Version 22H2 (Build 19045.4412)
```

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.67.90`
