### ISSUE TITLE
Do not run SKUs rust SDK on UI thread

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#35933]
It takes a long time and blocks the execution of the UI.

**Comment by nvonpentz** [comment]
Re opened because we reverted https://github.com/brave/brave-core/pull/22109 and https://github.com/brave/brave-core/pull/22169

**Comment by kjozwiak** [comment]
The above requires `1.63.164` or higher for `1.63.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```

```

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.63.164
Chromium: 122.0.6261.69 (Official Build) (64-bit) 
```
---------------------------
<details>
<summary> Search Engine options - PASS </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>

**Comment by Uni-verse** [comment]
In progress on `Samsung Galaxy Tab S7` using version: 

```
Brave	1.63.164 Chromium: 122.0.6261.69 (Official Build) (64-bit) 
Revision	0a640ded5b59268307d1ae11b74646763cb82b4c
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 14` using the following build(s):

```
Brave | 1.63.164 Chromium: 122.0.6261.69 (Official Build) (64-bit)
--- | ---
Revision | 0a640ded5b59268307d1ae11b74646763cb82b4c
OS | Android 14; Build/AP21.240119.009; 34; REL
```

### `Logging/Restore previous premium purchase` - `PASSED`


Using the account that was purchased via https://github.com/brave/brave-browser/issues/35983#issuecomment-1953412687 using a real `CC #`, went through the following:

* installed/launched `1.63.164 Chromium: 122.0.6261.69`
* loaded `https://account.brave.com` and logged into the account that already purchased a `Leo` premium subscription
  * ensured that the `SKU credentials` restored without any issues once logged into the account (basically instantly restored)
* once restored, ensured that `Leo` became `Premium` and that both the `Mixtral` & `Claude` LLM's appeared as `Unlimited`
  * also ensured that `PERMIUM` is being displayed at the top of the `Leo` window

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------
![1000001451](https://github.com/brave/brave-browser/assets/2602313/06c05faa-2247-4e8e-a293-a3094c642c27) | ![1000001452](https://github.com/brave/brave-browser/assets/2602313/0f5a5a23-50f2-477d-b79b-cb816fec7332) | ![1000001453](https://github.com/brave/brave-browser/assets/2602313/31d84f5e-90b2-4f9c-b283-2e6c6465d9bf)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave	1.63.165 Chromium: 122.0.6261.94 (Official Build) (64-bit) 
Revision	fed0fcc915f6d9e1db871202f0304c8d582a73de
OS	Linux
```
