### ISSUE TITLE
Auto-contribution contributed 11 BAT instead of 85 BAT

### ISSUE THREAD

**Issue by da2x** [brave/brave-browser#3595]
Version 0.60.47 Chromium: 72.0.3626.119 (Official Build) (64-bit)

My budget was 85 BAT and I had 85 BAT in my wallet. Auto-contribution for March was just committed as 11 BAT leaving 74 BAT in my wallet. This is with auto-contribution only with no tips. So … 11 BAT shouldn’t even have been an option.

<img width="415" alt="11bat" src="https://user-images.githubusercontent.com/1102886/53858103-053f5300-3fd9-11e9-8653-0b0263ecb796.png">

**Comment by da2x** [comment]
I just checked on my laptop, and it's 50 BAT budget (75 BAT wallet) was ignored and 4.5 BAT was contributed instead.

**Comment by NejcZdovc** [comment]
@da2x what does it say in your rewards summary? Is there pending section?

**Comment by da2x** [comment]
I just checked my laptop again (the machine that contributed 4.5 BAT last night) and this morning it contributed another 9 BAT. I'm confident that the next contribution time was set to sometime in early April after the 4.5 BAT was contributed last night. So there is definitely something wrong. The reward summary for this machine now shows one contribution of -9 BAT. The wallet shows 61.5
 BAT (which indicates both contributions were withdrawn from the wallet.)

The contribution summary on my other computer shows one transaction of -11 BAT.

There is no more detailed view of previous transactions so I can’t really give any more details than this.

**Comment by NejcZdovc** [comment]
@da2x can you pleas print screen your summary panel?

**Comment by da2x** [comment]
@NejcZdovc 
![screenshot](https://user-images.githubusercontent.com/1102886/53903598-60f2f600-4044-11e9-90ea-11954249c248.png)

**Comment by NejcZdovc** [comment]
@da2x thank you for the print screen. When doing contribution you can only contribute to verified publishers. If you have unverified publishers in the table that publishers will go into pending contributions. So what happened in your case was that you contributed 11 BAT (this is amount that represented verified publishers), 74 BAT went into pending contributions as you can see on the image.

![53903598-60f2f600-4044-11e9-90ea-11954249c248](https://user-images.githubusercontent.com/9574457/53935407-7a2c8e80-40a6-11e9-94ba-f8a071ae77b3.png)

**Comment by da2x** [comment]
@NejcZdovc No, that isn’t right. My wallet balance was 85 BAT, 11 was contributed, and now my wallet balance is at 74 BAT.

**Comment by NejcZdovc** [comment]
@da2x that looks good to me. Pending contributions are not reduced from balance/wallet until they are actually processed. They will be processed when publisher becomes verified.

**Comment by da2x** [comment]
So i can double spent from the wallet? Or aren't the funds being reserved? This is extremely poorly communicated.

**Comment by NejcZdovc** [comment]
closing as stale
