### ISSUE TITLE
Account discovery doesn't load all BTC accounts with balance

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#35954]
## Description 

Account discovery doesn't load all BTC accounts with balance

## Steps to Reproduce

   1. Import a wallet 
   2. Select Bitcoin during onboarding 
   3. Only first account is restored, subsequent accounts with balance isn't loaded

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/85e868b0-0823-498e-98e7-b58b930b1225

## Expected result:
Should restore all BTC accounts

## Reproduces how often: 

Easy

## Brave version (brave://version info)

 
Brave | 1.63.148 Chromium: 121.0.6167.164 (Official Build) beta (64-bit)
-- | --
Revision | c68893a5f2bbf2898967a976b21b3fe5d581f714
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @supermassive

**Comment by supermassive** [comment]
Bitcoin account 1 is created by onboarding with default set of addresses (1 receive and 1 change)
Then discovery starts which searches for all address for Bitcoin account 1 (next 20 receive addresses)
Discovery for Bitcoin account 2 starts after the first one ends which also takes some time until full set of addresses is searched. So after some time Bitcoin account 2 will get created by discovery

**Comment by kjozwiak** [comment]
The above requires `1.64.87` or higher for `1.64.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.64.88 Chromium: 122.0.6261.69 (Official Build) beta (64-bit)
-- | --
Revision | 2f29a9cd6ee8ec7836c1f99475794a285b9d5ceb
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#22204](https://github.com/brave/brave-core/pull/22204)
- Verified BTC/ZCash account discovery is faster
- Verified BTC/ZCash balance fetch is faster

https://github.com/brave/brave-browser/assets/17010094/627dc942-9755-4342-8dff-3b0c634200c0
