### ISSUE TITLE
[macOS] Tab groups have varying height depending on contents

### ISSUE THREAD

**Issue by abjugard** [brave/brave-browser#35956]
## Description 
The new look for the tab groups has varying height on macOS and it does not look great...
<img width="552" alt="image" src="https://github.com/brave/brave-browser/assets/287697/9c7449d5-17f5-40ba-b087-d7f1eab252fd">

I think this is contained to macOS, I first noticed the new look on Windows and don't recall if it looked the same, but I think that it didn't, will check and update the report when I get home from work.

On a related note, the pinned tabs now have some outline, which also has a different height compared to the tab groups, and the outline stands out a lot, too much in my opinion.
<img width="195" alt="image" src="https://github.com/brave/brave-browser/assets/287697/22e78ff9-40a0-4cc9-a2bc-fa729254839f">

I love that you're changing things up, and the overall style of tab groups in this update is great, but please ensure they stay the same height 🙂

## Steps to Reproduce
1. Create a tab group with only text
2. Create a tab group with an emoji as label
3. Create a tab group with no label at all
4. Pin a tab
5. Open any other tab
6. Observe that pinned tabs, each of the three tab groups, and the normal tab, all have different heights.

## Actual result:
See screenshots above.

## Expected result:
All tabs to have the same height, though maybe it is by design that pinned tabs aren't the same height, and that makes some sense, as they are "of special importance" to the user.

For example, how it looks on Windows:
![image](https://github.com/brave/brave-browser/assets/287697/0fbadd51-b979-4269-85fc-403175fa5d7b)

## Reproduces how often: 
100%

## Brave version (brave://version info)

Name | Version
-- | --
Brave | 1.62.153 Chromium: 121.0.6167.85 (Official Build) (arm64)
Revision | e4a51346862f226aeee12c4589ccf03d43655857
OS | macOS Version 14.3 (Build 23D56)

**Comment by abjugard** [comment]
I can confirm that it looks like it should on Windows. It's a macOS specific issue.

**Comment by rebron** [comment]
@abjugard Can you see if you're still seeing that with 1.62.162?

**Comment by abjugard** [comment]
> ~@abjugard Can you see if you're still seeing that with 1.62.162?~ I'm late on this comment looks like we already have a fix.

Late on the reply as well, but yes it's present in 1.62.162 as well.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (x86_64)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | macOS Version 13.6.4 (Build 22G513)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.64.94 Chromium: 122.0.6261.94 (Official Build) beta (arm64)
-- | --
Revision | 866e3a4bd76c9cc1762928df0cf9a53b8685ab71
OS | macOS Version 14.4 (Build 23E5191e)
```
