### ISSUE TITLE
non-clickable padding on tabs with new design decreases usability

### ISSUE THREAD

**Issue by doebi** [brave/brave-browser#35965]
## Description 
The new changes in UI design have a severe effect on the usability of the browser and a negative effect on my productivity.
I am using Brave with i3wm as my window manager. I specifically set i3 to have no border at all, which allowed me to switch tabs by moving the mouse at the far top of my screen. Switching tabs is very fast and effortless because it requires no aim. 

With the new design there is a non-clickable padding around the tabs, which breaks my approach and requires me to aim for the tabs. This quickly gets annoying and frustrating.

## Steps to Reproduce
   1. Open up a few tabs
   2. Use mouse click to switch between them
   3. 

## Actual result:
![2024-02-12_13-56](https://github.com/brave/brave-browser/assets/1591457/2abd04b0-a719-4bcb-a2e7-d94328be2d15)
The padding around the tab is not clickable.

## Expected result:
I expected a tab change when clicking at the tabs' border padding.

In my opinion it should be `function > form`. This is a decrease in function for a slight improvement in form. 
The changes in design can be retained. Instead of having dead pixels, the surrounding area should react to mouse events aswell.

## Reproduces how often: 
Always

## Brave version (brave://version info)
Version 1.62.162 Chromium: 121.0.6167.164 (Official Build)  (64-bit)
Ubuntu jammy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Probably

**Comment by Alecksohs** [comment]
Oh, I HATE this. Immediately uninstalling this, what the fuck.

**Comment by zenparsing** [comment]
A fix for this one is in progress. Thanks for the detailed report @doebi.

**Comment by kjozwiak** [comment]
The above requires `1.64.90` or higher for `1.64.x` verification 👍

**Comment by doebi** [comment]
When will this hit ubuntu/debian stable release?

**Comment by btlechowski** [comment]
Verified with

Brave | 1.64.105 Chromium: 123.0.6312.46 (Official Build) (64-bit)
-- | --
Revision | f0e46384b4e277529e9123c93370e113c547e206
OS | Linux

Verified padding is now clickable and changes the active tab

![35965](https://github.com/brave/brave-browser/assets/34715963/db621b59-a49b-49c1-bec1-d083d2828627)
