### ISSUE TITLE
[Brave News]: Persist Following/For You preference across browser sessions

### ISSUE THREAD

**Issue by LorenzoMinto** [brave/brave-browser#35968]

**Comment by kjozwiak** [comment]
The above requires `1.63.172` or higher for `1.63.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.63.174 Chromium: 122.0.6261.128 (Official Build) (64-bit)
-- | --
Revision | 0d369d4e1dfee7bcea82774079dc8cd658746c98
OS | Windows 10 Version 22H2 (Build 19045.4046)
```
Reproduced the issue on `1.63.169 Chromium: 122.0.6261.111` last selected `Feed` isn't respected when re-opening NTP

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/22362#issue-2157843430, ensured that the last selected `Feed` view is saved/respected when re-opening NTP. Went through the following:

**`Test Case #1`** - `Following`

* opened a NTP and selected `Following` as the default view
* closed the NTP/restarted Brave
* re-opened a NTP and scrolled down to the `Brave News Feed` and ensured `Following` was selected/displayed

**`Test Case #2`** - `Top Sources`

* opened a NTP and selected `Top Sources` as the default view
* closed the NTP/restarted Brave
* re-opened a NTP and scrolled down to the `Brave News Feed` and ensured `Top Sources` was selected/displayed

**`Test Case #3`** - `Imported RSS feed`

* opened a NTP and selected a `Imported RSS` as the default view
* closed the NTP/restarted Brave
* re-opened a NTP and scrolled down to the `Brave News Feed` and ensured `Imported RSS` was selected/displayed

**`Test Case #4`** - `For You`

* opened a NTP and selected a `Imported RSS` as the default view
* closed the NTP/restarted Brave
* re-opened a NTP and scrolled down to the `Brave News Feed` and ensured `Imported RSS` was selected/displayed
