### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by WoosikLee2510** [brave/brave-browser#35979]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.62.162 Chromium: 121.0.6167.164
Operating System: Mac OS X 15.0.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Install Bitwarden
2. add id pw
3. opens human check and crash

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/bbd30b00-8de4-790b-0000-000000000000

**Comment by bsclifton** [comment]
Backtrace link: https://brave.sp.backtrace.io/p/brave/debug?time=year&filters=JTVCJTVCJTIyX2RlbGV0ZWQlMjIlMkMlMjJlcXVhbCUyMiUyQyUyMjAlMjIlNUQlMkMlNUIlMjJfcnhpZCUyMiUyQyUyMmVxdWFsJTIyJTJDJTIyYmJkMzBiMDAtOGRlNC03OTBiLTAwMDAtMDAwMDAwMDAwMDAwJTIyJTVEJTVE&fingerprint=079bac7118f3562fc33a53c4fe33eda2a949595ebb5ad7cfde3c711b99ccce67&debug=(%226905323%22,0,0)

**Comment by bsclifton** [comment]
@WoosikLee2510 does this happen after the last upgrade?
