### ISSUE TITLE
[Android] Solana account user selection is not respected

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#35971]
## Description 
When I start the Solana rewards linking process via brave://rewards/ screen, the Connect with Brave wallet screen displays the account (Acc55) that I have funded while creating a brave wallet, but this screen should display all the accounts like desktop, but currently it displays only one account at a time, there is no scrollbar in this screen. If I click on Connect in this screen it display the Confirm Solana Address screen that displays the Solana Account1 address, that I have not selected in the  Connect with Brave wallet screen, ideally it suppose to display the address of the account Acc55 here is the mismatch, that is causing connecting to the default Solana Account1 wallet which was not created by the user.

## Steps to reproduce 

   1. Enable `Enable Brave rewards self-custody connection options` flag from `brave://flags`
   2. enable rewards from rewards panel.
   3. Go to `brave://rewards-internals` to get paymentID and white list the paymentID (@deeppandya can help with that)
   4. From rewards panel, click `Connect account`
   5. Start the process to link solana account

## Actual result 

https://github.com/brave/brave-browser/assets/5146988/65cf9742-80d1-4a75-947a-1ee6560d960b

## Expected result
Should select the correct account

## Issue reproduces how often 
Easily with above steps

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by darkdh** [comment]
It's not reward connect server side issue because it can also be reproducible on https://anza-xyz.github.io/wallet-adapter/example/

**Comment by kjozwiak** [comment]
The above requires `1.63.156` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.63.157 x64 build
- Verified steps from PR description
- Verified account used to connect is what is shown in the button as well
- Encountered [brave-browser#35951](https://github.com/brave/brave-browser/issues/35951)

https://github.com/brave/brave-browser/assets/17010094/892378c8-0bd6-47ea-a5b8-202e6e9c59c9
