### ISSUE TITLE
Reduce space above horizontal tab strip in Windows

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#35972]
## Description 

In updated horizontal tabs, there is too much space above the tabstrip.

## Actual result:

![tabstrip-top-1](https://github.com/brave/brave-browser/assets/5995084/b739da4d-60d5-4b0c-853f-4217bc86ebaf)

## Expected result:

![tabstrip-top-2](https://github.com/brave/brave-browser/assets/5995084/ed3267d1-d227-4004-bf1e-2cc04cf3b686)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.63.161` or higher for `1.63.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.63.161 Chromium: 122.0.6261.57 (Official Build) (64-bit)
-- | --
Revision | 37b02b4a373f40114e70cc034e491bcc8380f23a
OS | Windows 10 Version 22H2 (Build 19045.4046)
```

1.62.x | 1.63.x
--------|-------
![image](https://github.com/brave/brave-browser/assets/38657976/6a55cdb4-651c-4eef-836a-7a0371f2a92e) | ![image](https://github.com/brave/brave-browser/assets/38657976/ec42053a-759b-40f2-9eef-cf1009c43ecc)
