### ISSUE TITLE
Build is broken on Arm64 Windows

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#35975]
`npm run build -- --target_arch=arm64` on Windows gives:

```
../../brave/chromium_src/components/update_client/update_checker.cc(179,36): error: no member named 'SetString' in 'update_client::PersistedData'
   179 |   update_context_->persisted_data->SetString(extension_id, key, "true"); 
       |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
 ../../brave/chromium_src/components/update_client/update_checker.cc(184,44): error: no member named 'GetString' in 'update_client::PersistedData'
   184 |   return !update_context_->persisted_data->GetString(extension_id, key).empty();
       |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```

Found by @wknapik in CI [here](https://ci.brave.com/job/brave-browser-build-windows-arm64/725/execution/node/179/log/).

**Comment by kjozwiak** [comment]
The above requires `1.63.156` or higher for `1.63.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.63.156 Chromium: 122.0.6261.43 (Official Build) (arm64)
-- | --
Revision | afb5d4402861ae4a1eb59c939832a4d27e1ed8df
OS | Windows 11 Version 23H2 (Build 22631.3085)
```

### Netflix - `PASSED`
<details>

### Steps:
1. installed `1.63.156 `
2. launched Brave
3. loaded `netflix.com`
4. clicked on the `Sign In` link
5. entered QA credentials
6. clicked on the `Sign In` button
7. confirmed I got prompted to `Install and run Widevine`
8. clicked `Allow`
9. clicked on `Brave QA` avatar
10. clicked to play `Tiny creatures Arizona`

### Confirmed the content was streamed in High-Definition (HD) quality (through visual inspection)

`Widevine prompt` | `HD content`
-------------------|--------------
![image](https://github.com/brave/brave-browser/assets/98358127/3d794341-a0ac-41ba-8d95-ec6e91775920)|![image](https://github.com/brave/brave-browser/assets/98358127/ae131fb5-0935-4c52-9e4b-6b9ff2dbf185)

</details>

### Amazon Prime - `PASSED`
<details>

### Steps:

1. installed `1.63.156`
2. launched Brave
3. loaded `amazon.com`
4. logged in
5. selected `Prime Video`
6. confirmed I was prompted to `Install and run Widevine`
7. clicked on `Allow`
8. clicked to play `Paw Petrol: The Movie`

### Confirmed the content was streamed in High-Definition (HD) quality, "Best" quality level @ `1080p` (6.48 GB per hour)

`Widevine prompt` | `HD content`
---------|---------
![image](https://github.com/brave/brave-browser/assets/98358127/90c77fec-8b23-41af-9a81-5684120ad8c8)|![image](https://github.com/brave/brave-browser/assets/98358127/648e6a17-2381-4e6c-b412-1f82a62cf3b8)

</details>

### HBOMax - `PASSED`
<details>

### Steps:
1. installed `1.63.156`
9. launched Brave
10. loaded `hbomax.com`
11. clicked on the `Sign In` button
12. clicked `Sign in to your account`
13. clicked `Sign in With a Provider` button
14. clicked on QA/avatar
15. confirmed I was prompted to `Install and run Widevine`
16. clicked to play `Alvin and the Chipmunks: The Squeakquel`

### Confirmed the content was streamed in High-Definition (HD) quality, through visual inspection

`Widevine prompt` | `HD content`
-------------------|--------------
![image](https://github.com/brave/brave-browser/assets/98358127/4f801190-2ea7-4e5c-a8ef-146c8aaefed4)|![image](https://github.com/brave/brave-browser/assets/98358127/69ad3580-c8a6-4cc0-b3c6-780a3e2b67f6)

</details>

### Bitmovin.com - PASSED
<details>

### Steps:

1. Installed `1.63.156`
2. launched Brave
3. visit https://bitmovin.com/demos/drm in a new tab page
4. confirmed I got prompted to Install and run Google Widevine
5. clicked Allow
6. played the video for protected DRM stream
7. Confirmed the content was streamed in High-Definition (HD) quality (through visual inspection)

`Widevine prompt` | `HD content`
-------------------|--------------
![image](https://github.com/brave/brave-browser/assets/98358127/2cb0752b-8c16-47d9-8ab5-b6f5e91bd97c)|![image](https://github.com/brave/brave-browser/assets/98358127/9bcfacfa-3d16-4cf7-8c70-6352dcb0e592)

</details>

### Widevine component details:
<details>

Confirmed via `brave://components` that `Widevine Content Decryption Module - Version: 4.10.2710.0` was downloaded, in all cases

`brave://components` | `WidevineCdm` folder
---------|---------
![image](https://github.com/brave/brave-browser/assets/98358127/19b51d0f-901a-4bb5-abe7-fd0443b16fb2)|![image](https://github.com/brave/brave-browser/assets/98358127/cf8e8474-7b0f-4410-a65c-7f5439d01586)

</details>
