### ISSUE TITLE
New disabled state

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#3597]
Current implementation:
![image](https://user-images.githubusercontent.com/9574457/53862641-4a1eb600-3fe8-11e9-8b39-e89909ee9be6.png)

New design
![image](https://user-images.githubusercontent.com/9574457/53862653-50ad2d80-3fe8-11e9-9eae-9ed765201907.png)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

Used test plan from https://github.com/brave/brave-core/pull/1930

![image](https://user-images.githubusercontent.com/34715963/56730672-d03dba00-6758-11e9-936e-2342c23a3b12.png)

In Polish
![image](https://user-images.githubusercontent.com/34715963/56730781-0c711a80-6759-11e9-8692-0a518ef9e644.png)
