### ISSUE TITLE
Implement Brave Rewards Terms of Service update notices

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#35977]
## Description

Designs: https://www.figma.com/file/8KhY2EucP83N0NqYspTImh/Terms-of-Service-update?type=design&node-id=1-685&mode=design&t=6issNNgVY0mAJ2pc-0

**Comment by Miyayes** [comment]
Targeting 1.64.x, incl via uplift.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (x86_64) 
Revision	2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS	macOS Version 13.6.4 (Build 22G513)
```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.65.93 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | a6eee503125f9441360861f96cfdcccf43b6fee0
OS | Windows 11 Version 23H2 (Build 22631.3296)
```

<details>
<summary>Clean Profile - Unconnected state - Accept Changes - PASSED </summary>

1. With a new profile, enable Rewards.
2. Close the browser.
3. Use Charles Proxy to simulate incrementing the "tosVersion" field of the Rewards parameters endpoint.
4. Restart the browser, confirm Charles Proxy rewrite is being used:

```
[ REQUEST ]
> URL: https://api.rewards.bravesoftware.com/v1/parameters
> Method: GET
![image](https://github.com/brave/brave-browser/assets/98358127/e0588e2a-94f3-4c31-b9d9-867db58804d8)
```
```
[ RESPONSE ]
> URL: https://api.rewards.bravesoftware.com/v1/parameters
> Result: Success
> HTTP Code: 200
> Body: {"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.303038,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["US","SG","GB","CA"],"block":[]},"solana":{"allow":[],"block":["KP","ES"]},"uphold":{"allow":["AD","AU","AR","AT","BE","BR","BS","BZ","CA","CH","CL","CO","CR","CY","CZ","DK","EC","EE","FI","FR","GD","GT","GR","HK","HN","HU","IE","IS","IT","JM","KY","LI","LT","LV","LU","MC","MT","MX","NI","NO","NZ","PE","PT","PY","SG","TR","UY","ES","SE","GB","US","UM","ZA","PL","SK","HR","SI","GR","TW"],"block":[]},"zebpay":{"allow":["IN"],"block":[]}},"payoutStatus":{"bitflyer":"processing","gemini":"processing","payoutDate":"","solana":"processing","unverified":"processing","uphold":"processing","zebpay":""},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"tosVersion":2,"vbatDeadline":"2023-10-31T00:00:00Z","vbatExpired":true}
```
5.Verify that the ToS update notice is displayed on the NTP, the Rewards page, and the Rewards panel.

NTP | brave://rewards | rewards panel
--- | ----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/25cfa31e-2c8c-48f8-9511-504c1ab2ac81)|![image](https://github.com/brave/brave-browser/assets/98358127/f302bd1d-9fe7-441e-a862-0726c9877aa2)|![image](https://github.com/brave/brave-browser/assets/98358127/15756c59-1eac-4c5e-93ff-e37b71076183)
<details>
