### ISSUE TITLE
Have a way to force-update adblock lists

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#35982]
We don't currently have a way on iOS to force-update all components like we do on Desktop and Android, where a user can go to brave://components in the omnibox and manually press Update for components.

<img width="830" alt="image" src="https://github.com/brave/brave-ios/assets/5284154/df23bff8-54a5-445b-a41e-7726962e1a2a">

This is extremely important for when we need to ship an emergency component update out, like we do when there's widespread adblock list-related breakage. On iOS, AFAICT, there's nothing a user can do to make sure they have the latest version of an adblock list.

We don't need to have the update be per-component; a single button suffice somewhere in the app would suffice. For debugging purposes, it would also be nice to know the user's current version, but that's secondary in priority.

**Comment by ShivanKaul** [comment]
We should look at the Android implementation of this, at least for the placement of the Update button: https://github.com/brave/brave-browser/issues/35270. It would be best if this button lived in the Content Filtering settings page.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.0` using version `1.70.117`

**Case: New Users**

- Ensured that `Update Lists` button is shown for Default Filter Lists and External Filter Lists. 
- Ensured that `Update Lists` button is only shown for External Filters Lists when URLs are added and not shown when URLs are removed again. 
- Ensured that button is replaced with `Lists Updated` message when tapping on the update button. 
- Ensured that button state is reset to default state (showing `Update Lists`) when re-entering the settings page. 
- Ensured that custom filters can be added and are applied on webpages. 

example | example | example | example | example | example
---|---|---|---|---|---
![IMG_7346](https://github.com/user-attachments/assets/14c77ac7-b9b0-40f8-8bc2-babfa4134eb4) | ![IMG_7347](https://github.com/user-attachments/assets/14ba45af-f573-46e8-8762-608b37cbfbef) | ![IMG_7348](https://github.com/user-attachments/assets/5b487bf1-8d34-4f20-a729-8d1e8e4e5ae8) | ![IMG_7349](https://github.com/user-attachments/assets/abab7d97-aba8-49dd-b5e4-3ced16906030) | ![IMG_7350](https://github.com/user-attachments/assets/fb5d0ed4-d67a-4215-9395-04d3cf344901) | ![IMG_7351](https://github.com/user-attachments/assets/ddd26506-0b67-413f-a853-7fefae4b02cc)

**Case: Existing Users**

- Ensured that filter lists, external filters lists and custom filters are retained when upgrading from 1.69.169 -> 1.70.117.
- Ensured that disabling `Block 'Switch to App' Notices` in settings and then upgrading will retain the switch state in Content Filtering and Settings page. 
- Ensured that `Update Lists` button works after upgrading for existing users and `updated` message is shown.

example | example | example | example
---|---|---|---
![IMG_7354](https://github.com/user-attachments/assets/7e8cf79c-db6f-446f-9beb-4af9993850ac) | ![IMG_7355](https://github.com/user-attachments/assets/9ac042a5-bb2d-4d72-ac2f-a34b5091b2a9) | ![IMG_7356](https://github.com/user-attachments/assets/bf2707b8-7694-48d8-8666-fae806337f0e) | ![IMG_7357](https://github.com/user-attachments/assets/366b5a78-7002-465d-97b9-b849543bec17)

**Comment by Uni-verse** [comment]
In progress on `iPad (7th Gen)` running `iOS 17.6` using version `1.70.117`

**Case: New Users**

- Ensured that `Update Lists` button is shown for Default Filter Lists and External Filter Lists. 
- Ensured that `Update Lists` button is only shown for External Filters Lists when URLs are added and not shown when URLs are removed again. 
- Ensured that button is replaced with `Lists Updated` message when tapping on the update button. 
- Ensured that button state is reset to default state (showing `Update Lists`) when re-entering the settings page. 
- Ensured that custom filters can be added and are applied on webpages. 

example | example | example | example
---|---|---|---
![IMG_1618](https://github.com/user-attachments/assets/bb32a9a0-74ac-47ab-b308-37155a795bd7) | ![IMG_1619](https://github.com/user-attachments/assets/3eadaf64-92ce-41e5-8803-165a03b34691) | ![IMG_1620](https://github.com/user-attachments/assets/89be2764-05ea-477e-92a8-8ad6a0da774c) | ![IMG_1621](https://github.com/user-attachments/assets/8d5f3d3a-1acd-482e-b72f-12930953720c)


**Case: Existing Users**

- Ensured that filter lists, external filters lists and custom filters are retained when upgrading from 1.69.169 -> 1.70.117.
- Ensured that disabling `Block 'Switch to App' Notices` in settings and then upgrading will retain the switch state in Content Filtering and Settings page. 
- Ensured that `Update Lists` button works after upgrading for existing users and `updated` message is shown.

example | example | example | example
---|---|---|---
