### ISSUE TITLE
Add iOS metric for primary language

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#35987]
Please replicate https://github.com/brave/brave-browser/issues/34853.

**Comment by DJAndries** [comment]
superseded by https://github.com/brave/brave-browser/issues/35987

**Comment by AndyAnds265** [comment]
@iccub I just wanted to check on the status of this. Getting language data on iOS is a high priority for growth as we are monitoring changes in Search and Browser since the European choice screens were released.

**Comment by chrismore** [comment]
@DJAndries Hey Darnell. What is the level of effort for this one?

**Comment by iccub** [comment]
We can get it in this week. I do not think we have prioritized it highly

**Comment by DJAndries** [comment]
@chrismore Should be a relatively short task

**Comment by chrismore** [comment]
If it is low effort, we might as well knock it out so we have parity across platforms with the insights.

Is this in the P3A pod or iOS general pod?

**Comment by iccub** [comment]
@chrismore do you have any preference what release version do you want to have this in?

**Comment by chrismore** [comment]
> @chrismore do you have any preference what release version do you want to have this in?

Sooner the better :-)
