### ISSUE TITLE
Link IAP on Android Leo

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#35983]
- change intent from `connect-receipt` to `link-order`
- pass orderId to localStorage along with receipt

**Comment by kjozwiak** [comment]
@Uni-verse @hffvld can use https://github.com/brave/brave-core/pull/22012#issuecomment-1947440639 as the template for the above verification. However, we'll need to use `production` this time around rather than `staging`. @AlanBreck confirmed that the changes have been merged into `production`. The above requires `1.63.156` or higher for `1.63.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 14` using the following build(s):

```
Brave | 1.63.157 Chromium: 122.0.6261.43 (Official Build) (64-bit)
--- | ---
Revision | 5fbb7c60cc44e15a910a39a349e632f1b904c58e
OS | Android 14; Build/AP11.231215.009; 34; REL
```

* launched `1.63.157 Chromium: 122.0.6261.43`
* purchased `Leo` premium via `Hamburger Menu` -> `Settings` -> `Leo` -> `Go Premium` (using a real `CC #` via `production`)
* once `Leo` has been purchased, tapped on `Link purchase to your Brave account` via the `Leo` settings
* ensured that `https://account.brave.com/?intent=link-order&product=leo` (specifically `intent=link-order`)
* used/logged into an account that doesn't have any `Premium` products associated with the account
* once logged into the Brave Account, tapped on `Link my subscription now`
  * ensured that the `Success! Your subscription is now linked` message was displayed once linked
* ensured that `Leo` appeared as a purchased premium product
  * ensured that `Purchased on Android` is visible/being displayed

**Purchasing Leo via `Production`**

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------|----------------|----------------
![Screenshot_20240217-172254](https://github.com/brave/brave-browser/assets/2602313/83f7336d-00a0-4c84-9ec4-cd7fe8bd2539) | ![Screenshot_20240217-172258](https://github.com/brave/brave-browser/assets/2602313/aafe1102-2991-429a-954c-9e33c2daa2c0) | ![Screenshot_20240217-172306](https://github.com/brave/brave-browser/assets/2602313/425159a9-789c-4d83-9bbb-cd691c985a45) | ![Screenshot_20240217-172410](https://github.com/brave/brave-browser/assets/2602313/fb922686-863f-418c-817f-276c0d65b7cb) | ![Screenshot_20240217-172509](https://github.com/brave/brave-browser/assets/2602313/23dd814d-f8fa-4f84-84a6-e8cdb20ddc3d) | ![Screenshot_20240217-172849](https://github.com/brave/brave-browser/assets/2602313/a191ce14-f2bc-4e55-8737-de4dacd45327)

**Linking with Desktop using `Production`**

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------|----------------|----------------
![Screenshot_20240217-172627](https://github.com/brave/brave-browser/assets/2602313/24cd209c-7240-4a69-a685-694aebb1e247) | ![Screenshot_20240217-172907](https://github.com/brave/brave-browser/assets/2602313/91441cc8-4107-4d9f-a4f9-02157a55b36b) | ![Screenshot_20240217-172913](https://github.com/brave/brave-browser/assets/2602313/5ed888e8-e197-4f6f-95a5-920a07e7a094) | ![Screenshot_20240217-173020](https://github.com/brave/brave-browser/assets/2602313/afe6e956-3b99-4770-ad44-f6061aaecccd) | ![Screenshot_20240217-173009](https://github.com/brave/brave-browser/assets/2602313/69e00e3a-12f5-4541-bba1-21553aaa25e3) | ![Screenshot_20240217-172604](https://github.com/brave/brave-browser/assets/2602313/343e6c22-7b94-4c67-8310-067f2b872455)

Once launched `1.62.165 Chromium: 121.0.6167.184` using `Win 11 x64` and went through the following:

* logged into the same account that was used above via https://account.brave.com/account/
* once logged in, verified that `Leo` was a product that appeared as `Purchased`
  * ensured that `Purchased on Android` is visible/being displayed
* clicked on `Refresh Leo` and ensured that new credentials were pulled and `Leo` switched to `Premium` on the desktop
* ensured that `Premium` appeared throughout the UI and that `Unlimited` appeared next to each LLM (indicating `Premium`)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------|----------------|----------------|------------------
![leo1](https://github.com/brave/brave-browser/assets/2602313/8be3f321-d2a7-4c00-bd46-6ec130b995c5) | ![leo2](https://github.com/brave/brave-browser/assets/2602313/55bfe2a7-f816-4ee2-96dc-9aca9d7f937e) | ![leo3](https://github.com/brave/brave-browser/assets/2602313/b213c8d2-fdef-4d56-b006-e0eb09539c05) | ![leo4](https://github.com/brave/brave-browser/assets/2602313/19a724a9-b207-4896-a651-71668bb2b21f) | ![leo5](https://github.com/brave/brave-browser/assets/2602313/048e3171-da8f-4b93-a614-8fdea5e87ed8) | ![leo6](https://github.com/brave/brave-browser/assets/2602313/25098e8b-0677-4078-8c08-ce98db7fe3fc) | ![leo7](https://github.com/brave/brave-browser/assets/2602313/ac6d2ccc-1a1a-4b9f-8ce9-0a211404c478)
