### ISSUE TITLE
Cache token balances

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#35986]
### Description: 

We should cache token balances for each account in Core Data so user doesn't have to wait for full balances fetch for all assets to load

https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1676011945567489

In summary, balances in Portfolio (Assets) will be refreshed when
1. A wallet is created 
2. A wallet is restored
3. When wallet is unlocked 
4. A account is created or added 
6. A network is added
7. An asset is added 
8. An asset's visibility status is changed to be visible
9. A transaction is confirmed or error out or dropped

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.4 running 1.64 (109)
- Verified steps from [brave/brave-core#22029](https://github.com/brave/brave-core/pull/22029)
- Verified on a clean wallet loads all tokens with 0 balance
- Verified closing wallet and reopening wallet without locking doesn't do a balance refetch 
- Verified restoring wallet on a clean install loads wallet balance
- Verified closing wallet and reopening wallet without locking doesn't do a balance refetch
- Verified auto-discovery of NFT works as expected
- Verified adding a token with balance to visible asset automatically updates balance
- Verified adding/removing token from visible list updates balance 
- Verified adding/removing custom network updates portfolio balance 
- Verified submitting a transaction updates the token and portfolio balance
- Verified upgrading from older version with balance, there is no balance refetch everytime wallet is opened (dismiss without locking)
