### ISSUE TITLE
Wallet: P3A

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#35981]
### Wallet P3A Questions
**As an active ETH/SOL/FIL user (that currently has an active account, or previously has had one), how many accounts do you have with a non-zero balance?**
`Brave.Wallet.ActiveEthAccounts`, `Brave.Wallet.ActiveSolAccounts` and `Brave.Wallet.ActiveFilAccounts`

0) 0 accounts
1) 1 account
2) 2 accounts
3) 3 accounts
4) 4-7 accounts
5) 8+ accounts

Desktop issue: https://github.com/brave/brave-browser/issues/25504

**If you accessed the Wallet onboarding page this week, where did you stop in the onboarding process?**
`Brave.Wallet.OnboardingConversion.3`

0) Viewed onboarding splash
1) Between "Legal stuff" and "Create password"
2) During "recovery phrase" steps
3) Completed onboarding after completing "recovery phrase" steps
4) Completed onboarding after skipping "recovery phrase" steps

**If you created a wallet within the last week, did you make a deposit this week?** 
`Brave.Wallet.NewUserBalance`

1) Yes

Both metrics are weekly ephemeral metrics.
Desktop issue: https://github.com/brave/brave-browser/issues/30292

**If you viewed the NFT gallery this week, how many NFTs are displayed in the gallery?**
`Brave.Wallet.NFTCount`

0. 0
1. 1 - 4
2. 5 - 20
3. More than 20

**Did you use the NFT gallery for the first time this week?**
`Brave.Wallet.NFTNewUser`

1. Yes

**As a user that has used the wallet at least once, do you have NFT discovery enabled?**
`Brave.Wallet.NFTDiscoveryEnabled`

0. No
1. Yes

Desktop issue: https://github.com/brave/brave-browser/issues/32315

https://github.com/brave/brave-browser/wiki/P3A

#### Developer Info

Some stats are tracking internally in core:
- `Brave.Wallet.LastUsageTime`, `Brave.Wallet.UsageDaily`, `Brave.Wallet.UsageMonthly`, `Brave.Wallet.UsageWeekly`, `Brave.Wallet.NewUserReturning`
    - https://github.com/brave/brave-core/blob/a0a53a884a555ed789f747dda0dc74bfa09fe074/components/brave_wallet/browser/brave_wallet_p3a.cc#L65-L68
- `Brave.Wallet.NFTDiscoveryEnabled`
    - https://github.com/brave/brave-core/blob/a0a53a884a555ed789f747dda0dc74bfa09fe074/components/brave_wallet/browser/brave_wallet_p3a.cc#L81

N/A on iOS (no extensions on iOS to allow provider overwrites)
`Brave.Wallet.DefaultSolanaWalletSetting` (N/A on wiki or core)
`Brave.Wallet.DefaultWalletSetting` (N/A on wiki or core)
`Brave.Wallet.EthProvider`
`Brave.Wallet.SolProvider`

**Comment by kjozwiak** [comment]
@GeetaSarvadnya as per the discussion via https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1710226698445269?thread_ts=1709830656.368599&cid=CHGKGMHDJ, lets run through the `iOS` case mentioned via https://github.com/brave/brave-core/pull/22360#issue-2157815303 on `1.65.x` as we initially skipped it to save some time. As per @StephenHeaps, that PR doesn't affect `iOS` on `1.64.x` so we can defer the verification once we start running through `1.65.x`.

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `iPhone 8 version 16.7.7` running `Brave Nightly 1.65 (114)`

- Verified the test plan from https://github.com/brave/brave-core/pull/22360

**_EthAccounts_**

<details>
<summary>Case 1: Brave.Wallet.EthTransactionSent = 0_PASSED</summary>

<details>
<summary>Case 1.1: No Eth TransactionSent</summary>

1. Clean profile `1.65.x`
2. Go to `Settings->Brave Core Switches` and enable `Brave Wallet Count Test Networks`
3. Go to `Settings->Web 3->Networks` and enable `Show Test Networks` switch
4. Go to Portfolio page and click on `Filters and Display settings` ->`Select Networks`
5. Ensure that test networks are displayed under `Test Networks`
6. Enable test networks for ETH/FIL/SOL
7. Create a Ethereum account in Testnet
8. Send Eth to Ethereum accounts via https://sepolia-faucet.pk910.de/
9. Ensured that the Eth appeared in the Ethereum account
10. Ensure that the `Transactions` list is empty 
11. Open brave://local-state file and ensured that the metrics `Brave.Wallet.EthTransactionSent` is not shown as there are no Eth transaction sent

Example | Example | Example | Example | Example
-------|--------|--------|------|------
![IMG_4372](https://github.com/brave/brave-browser/assets/38657976/872a887d-ccfd-483d-9f47-be02a7480318) | ![IMG_4373](https://github.com/brave/brave-browser/assets/38657976/44a766ac-962c-469c-bb36-a9ae2070cb89) | ![IMG_4374](https://github.com/brave/brave-browser/assets/38657976/0571ad87-3e8a-45ec-b1ab-a3d802aa5121) | ![IMG_4375](https://github.com/brave/brave-browser/assets/38657976/448036f7-d173-47b0-8285-8aec8b6136b0) | ![IMG_4376](https://github.com/brave/brave-browser/assets/38657976/520a006c-64d1-4a33-a177-faf63f4f2de7)



</details>

</details>

<details>
<summary>Case 2: Brave.Wallet.EthTransactionSent = 1_PASSED</summary>

<details>
<summary>Case 2: Eth Transaction Sent in past 7 days and exceed 7 days_PASSED</summary>

1. Clean profile `1.65.x`
2. Go to `Settings->Brave Core Switches` and enable `Brave Wallet Count Test Networks`
3. Go to `Settings->Web 3->Networks` and enable `Show Test Networks` switch
4. Go to Portfolio page and click on `Filters and Display settings` ->`Select Networks`
5. Ensure that test networks are displayed under `Test Networks`
6. Enable test networks for ETH/FIL/SOL
7. Create a Ethereum account in Testnet
8. Send Eth to Ethereum accounts via https://sepolia-faucet.pk910.de/
9. Ensured that the Eth appeared in the Ethereum account
10. Ensure that the `Transactions` list is empty
11. Create a 2nd Ethereum accounts and send `0.005` Eth to 2nd account 
12. Open 1st Ethereum account and check the Transactions list and ensured that there is one Transactions listed for sending `0.005` to 2nd Eth account
13. Open brave://local-state file and ensured that the metrics `Brave.Wallet.EthTransactionSent` response value is `1` as expected
14. Close the browser and set the system date ahead by 7 days
15. Relaunch the browser
16. Open brave://local-state file and ensured that the metrics `Brave.Wallet.EthTransactionSent` response value is `1` as expected
17. Close the browser and set the system date ahead by 8 days
18. Relaunch the browser
19. Open brave://local-state file and ensured that the metrics `Brave.Wallet.EthTransactionSent` response value is `0` as expected
20. Create a 3rd Ethereum accounts and send `0.005` SOL to 3rd account 
21. Open brave://local-state file and ensured that the metrics `Brave.Wallet.EthTransactionSent` response value is `1` as expected

step 11,12 (1) | step 11,12 (2) | step 11,12 (3) | step 13 | step 16 | step 19 | step 20 (1) | step 20 (2) | step 21
---------------|-----------------|----------------|----------|----------|---------|------------|-------------|---------
![IMG_4377](https://github.com/brave/brave-browser/assets/38657976/a6a14ac3-a65e-490f-a2f5-c819e871dcf1) | ![IMG_4378](https://github.com/brave/brave-browser/assets/38657976/9b6a28af-5b5c-4798-ba93-22a454883b00) | ![IMG_4379](https://github.com/brave/brave-browser/assets/38657976/aac858fe-4685-451f-81d7-11e259d4d94e) | ![IMG_4380](https://github.com/brave/brave-browser/assets/38657976/798822b5-b409-4568-8e7f-26043087be53) | ![IMG_4381](https://github.com/brave/brave-browser/assets/38657976/3f4c6b0d-e7ae-4160-8853-3870b062880a) | ![IMG_4382](https://github.com/brave/brave-browser/assets/38657976/ece601e3-7510-4c87-b651-ddcbbace93b2) | ![IMG_4384](https://github.com/brave/brave-browser/assets/38657976/1b7c3f00-4866-4cd7-ae90-40543d36a6b1) | ![IMG_4385](https://github.com/brave/brave-browser/assets/38657976/518146d8-a0e5-4f9b-b5ee-aca66e1d42e1) | ![IMG_4383](https://github.com/brave/brave-browser/assets/38657976/86004a79-20f8-4f0a-99e1-70758cdbbb85)












</details>

</details>


**_Solana accounts:_**

<details>
<summary>Case 1: Brave.Wallet.SolTransactionSent = 0_PASSED</summary>

<details>
<summary>Case 1.1: No Sol TransactionSent</summary>

1. Clean profile `1.65.x`
2. Go to `Settings->Brave Core Switches` and enable `Brave Wallet Count Test Networks`
3. Go to `Settings->Web 3->Networks` and enable `Show Test Networks` switch
4. Go to Portfolio page and click on `Filters and Display settings` ->`Select Networks`
5. Ensure that test networks are displayed under `Test Networks`
6. Enable test networks for ETH/FIL/SOL
7. Create a Solana account in Testnet
8. Send Sol to Solana accounts via https://solfaucet.com/
9. Ensured that the SOL appeared in the Solana account
10. Ensure that the `Transactions` list is empty 
11. Open brave://local-state file and ensured that the metrics `Brave.Wallet.SolTransactionSent` is not shown as there are no SOL transaction sent

Example | Example | Example | Example | Example | Example | Example
---------|------------|-----------|---------|-----------|------------|------------
![IMG_4335](https://github.com/brave/brave-browser/assets/38657976/6db5d6f5-2c94-4805-a848-3a1d6949ad04) | ![IMG_4338](https://github.com/brave/brave-browser/assets/38657976/cad0deba-9fe2-4e2b-b5f6-bd84e9466a4a) | ![IMG_4341](https://github.com/brave/brave-browser/assets/38657976/511601b4-699e-46ec-b877-e2d2890357c7) | ![IMG_4340](https://github.com/brave/brave-browser/assets/38657976/e772574d-4d1f-43d0-b1b7-311126990c44) | ![IMG_4342](https://github.com/brave/brave-browser/assets/38657976/a940b8e9-d9e5-4ba8-af60-de378045d3e9) | ![IMG_4343](https://github.com/brave/brave-browser/assets/38657976/894a2c83-1c76-4790-87a8-8924a2127651) | ![IMG_4344](https://github.com/brave/brave-browser/assets/38657976/37c9a394-56f4-428b-a1b7-c27a67deebde)


</details>


</details>

<details>
<summary>Case 2: Brave.Wallet.SolTransactionSent = 1_PASSED</summary>

<details>
<summary>Case 2.1: Sol Transaction Sent in past 7 days and exceed 7 days_PASSED</summary>

1. Clean profile `1.65.x`
2. Go to `Settings->Brave Core Switches` and enable `Brave Wallet Count Test Networks`
3. Go to `Settings->Web 3->Networks` and enable `Show Test Networks` switch
4. Go to Portfolio page and click on `Filters and Display settings` ->`Select Networks`
5. Ensure that test networks are displayed under `Test Networks`
6. Enable test networks for ETH/FIL/SOL
7. Create a Solana account in Testnet
8. Send Sol to Solana accounts via https://solfaucet.com/
9. Ensured that the SOL appeared in the Solana account
10. Ensure that the `Transactions` list is empty
11. Create a 2nd Solana accounts and send `0.005` SOL to 2nd account 
12. Open 1st Solana account and check the Transactions list and ensured that there is one Transactions listed for sending `0.005` to 2nd SOL account
13. Open brave://local-state file and ensured that the metrics `Brave.Wallet.SolTransactionSent` response value is `1` as expected
14. Close the browser and set the system date ahead by 7 days
15. Relaunch the browser
16. Open brave://local-state file and ensured that the metrics `Brave.Wallet.SolTransactionSent` response value is `1` as expected
17. Close the browser and set the system date ahead by 8 days
18. Relaunch the browser
19. Open brave://local-state file and ensured that the metrics `Brave.Wallet.SolTransactionSent` response value is `0` as expected

step 11 | step 11 (1) | step 11(2) | step 12 | step 12 (1) | step 13 | step 16 | step 19
---------|------------|-----------|---------|-----------|------------|------------|---------
![IMG_4345](https://github.com/brave/brave-browser/assets/38657976/bf9326ab-42cd-4762-9401-a307d38085d9) | ![IMG_4346](https://github.com/brave/brave-browser/assets/38657976/50ae98c9-9d01-4f9a-878a-239533c59380) | ![IMG_4347](https://github.com/brave/brave-browser/assets/38657976/6497cbf7-de90-41bc-a711-b8eb2521fc49) | ![IMG_4348](https://github.com/brave/brave-browser/assets/38657976/4436eeec-7412-4620-825e-5f7f94c81828) | ![IMG_4349](https://github.com/brave/brave-browser/assets/38657976/c862ff91-d64f-4b4d-bc75-e0bdfd705efe) | ![IMG_4351](https://github.com/brave/brave-browser/assets/38657976/011a2838-504b-4ff5-b7a0-34546af5eb0f) | ![IMG_4352](https://github.com/brave/brave-browser/assets/38657976/75c1377e-074a-4abd-9c91-735b73507951) | ![IMG_4354](https://github.com/brave/brave-browser/assets/38657976/d6f3aa08-822a-4d8b-9a8d-3d6ef8c8ef44)

</details>
</details>

**_FilecoinAccounts_**

<details>
<summary>Case 1: Brave.Wallet.FilTransactionSent = 0_PASSED</summary>

<details>
<summary>Case 1.1: No Fil TransactionSent</summary>

1. Clean profile `1.65.x`
2. Go to `Settings->Brave Core Switches` and enable `Brave Wallet Count Test Networks`
3. Go to `Settings->Web 3->Networks` and enable `Show Test Networks` switch
4. Go to Portfolio page and click on `Filters and Display settings` ->`Select Networks`
5. Ensure that test networks are displayed under `Test Networks`
6. Enable test networks for ETH/FIL/SOL
7. Create a Filecoin account in Testnet
8. Send Fil to Filecoin accounts via https://faucet.calibnet.chainsafe-fil.io
9. Ensured that the Fil appeared in the Filecoin account
10. Ensure that the `Transactions` list is empty under `brave://wallet/crypto/accounts/t1rapzhlhwvpj7tfs6jwphsiqkvq4cdab3efmunaa/transactions`
11. Open brave://local-state file and ensured that the metrics `Brave.Wallet.FilTransactionSent` is not shown as there are no Fil transaction sent

Example | Example | Example | Example
----------|-----------|----------|----------
![IMG_4355](https://github.com/brave/brave-browser/assets/38657976/c7abd14b-244e-4bd0-8a1e-2a1458a1cf5c) | ![IMG_4356](https://github.com/brave/brave-browser/assets/38657976/ae16bad8-b09a-4144-90f1-b71d8dd83a3d) | ![IMG_4357](https://github.com/brave/brave-browser/assets/38657976/05de7bc5-100d-4e5a-b074-0f2965eb4403) | ![IMG_4358](https://github.com/brave/brave-browser/assets/38657976/a4dabc1b-04a7-4f54-9eda-f60ef97e7678)


</details>

</details>

<details>
<summary>Case 2: Brave.Wallet.FilTransactionSent = 1_PASSED</summary>

<details>
<summary>Case 2.1: Sol Transaction Sent in past 7 days and exceed 7 days_PASSED</summary>

1. Clean profile `1.65.x`
2. Go to `Settings->Brave Core Switches` and enable `Brave Wallet Count Test Networks`
3. Go to `Settings->Web 3->Networks` and enable `Show Test Networks` switch
4. Go to Portfolio page and click on `Filters and Display settings` ->`Select Networks`
5. Ensure that test networks are displayed under `Test Networks`
6. Enable test networks for ETH/FIL/SOL
7. Create a Filecoin account in Testnet
8. Send Fil to Filecoin accounts via https://faucet.calibnet.chainsafe-fil.io/send
9. Ensured that the Fil appeared in the Filecoin account
10. Ensure that the `Transactions` list is empty 
11. Create a 2nd Filecoin accounts and send `0.005` Fil to 2nd account 
12. Open 1st Filecoin account and check the Transactions list and ensured that there is one Transactions listed for sending `0.005` to 2nd Fil account
13. Open brave://local-state file and ensured that the metrics `Brave.Wallet.FilTransactionSent` response value is `1` as expected
14. Close the browser and set the system date ahead by 7 days
15. Relaunch the browser
16. Open brave://local-state file and ensured that the metrics `Brave.Wallet.FilTransactionSent` response value is `1` as expected
17. Close the browser and set the system date ahead by 8 days
18. Relaunch the browser
19. Open brave://local-state file and ensured that the metrics `Brave.Wallet.FilTransactionSent` response value is `0` as expected
20. Create a 3rd Filecoin accounts and send `1` Fil to 3rd account 
21. Open brave://local-state file and ensured that the metrics `Brave.Wallet.FilTransactionSent` response value is `1` as expected

**step 7- 12**

Example | Example | Example | Example | Example | Example
--------|----------|---------|--------|--------|-----------
![IMG_4359](https://github.com/brave/brave-browser/assets/38657976/5acd2d4f-06a0-493f-8a11-a5fdb7d7ff37) | ![IMG_4360](https://github.com/brave/brave-browser/assets/38657976/081660be-f3a5-443c-ab2e-7a5b4697417e) | ![IMG_4361](https://github.com/brave/brave-browser/assets/38657976/9a021004-aec1-4d3d-b025-de2249906c68) | ![IMG_4362](https://github.com/brave/brave-browser/assets/38657976/669ccb6b-808a-4933-b766-030173a2a530) | ![IMG_4363](https://github.com/brave/brave-browser/assets/38657976/5ac9864b-f0d2-4141-a959-4f52e16bd428) | ![IMG_4364](https://github.com/brave/brave-browser/assets/38657976/3a923c82-6016-46c4-ae08-d97c06fa3b13)


step 13 | step 19 | step 20 | step 20 (1) | step 20 (2) | step 21
--------|----------|----------|------------|-------------|-------------
![IMG_4366](https://github.com/brave/brave-browser/assets/38657976/913c5180-4503-4f23-a731-5a37486e429d) | ![IMG_4367](https://github.com/brave/brave-browser/assets/38657976/cc4c7f25-3e32-4de1-8f25-82cd2192856e) | ![IMG_4368](https://github.com/brave/brave-browser/assets/38657976/7e3a53f2-a6ae-46fb-a122-8e3dde0bdd48) | ![IMG_4370](https://github.com/brave/brave-browser/assets/38657976/09285395-2e2d-41ea-bd2e-5a2fd92c3041) | ![IMG_4371](https://github.com/brave/brave-browser/assets/38657976/3fa984a8-0e4d-4b27-8923-e11f655368bf) | ![IMG_4369](https://github.com/brave/brave-browser/assets/38657976/0c62169e-3501-40df-9509-914ea756bffc)


</details>

</details>
