### ISSUE TITLE
Wallet: Asset Deposit

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#35988]
### Description: 

Should be a reusable modal view. Linked to `...` button in each account card in Accounts tab v2, Account Details v2, etc.

<img width="299" alt="Accounts Deposit" src="https://github.com/brave/brave-ios/assets/5314553/6d59e51c-9d3a-4e90-993b-2111a352a832">

Locations:
Portfolio 
Asset Detail 
Assets in Market tab
Account Details

**Comment by kjozwiak** [comment]
The above requires `1.64.118` or higher for `1.64.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.4.1 running 1.64 (119)
- Verified steps from [brave/brave-core#22453](https://github.com/brave/brave-core/pull/22453)
- Verified Deposit works as expected 
- Verified Deposit option works from Portfolio, Account details menu, Asset details screen and Market token details screen
- Verified Deposit auto fills token details when opened from Asset details screen
- Verified Deposit screen for Eth tokens shows disclaimer message
- Verified searching for a token on multichain the disclaimer message is only shown for ETH/EVM network tokens
- Verified when there is no account created, selecting deposit brings up the account creation message. Additional notes [here](https://github.com/brave/brave-browser/issues/37123#issuecomment-2042071601)

https://github.com/brave/brave-browser/assets/17010094/22183a8a-bcec-4df5-9b62-e218da3178da
