### ISSUE TITLE
[CR 122 ] exit IP address doesn't change in the Tor window after hard refresh or with New Tor connection

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#35996]
## Description 

Found while testing manual pass for Chromium upgade https://github.com/brave/brave-browser/issues/35961.  Exit ip address doesn't refresh after hard refresh (Ctrl+Shift+R) or when clicked New Tor connection from app menu when visited https://check.torproject.org/ in a Tor window.  Refresh happens as expected in `1.64.61 Chromium 121.0.6167.164`

## Steps to Reproduce

   1. Install 1.64.65
   2. launch Brave
   3. visit https://check.torproject.org/ in Tor window
   4. note down exit node IP address. Do a hard refresh (Ctrl+Shift+R/Cmd+Shift+R), 
   5. note down exit node IP address. Click New Tor connection for this site in app menu
   
## Actual result:

exit IP changes doesn't change after page reloads.  

CR 122
---
https://github.com/brave/brave-browser/assets/98358127/500d5b53-d5a2-4120-aba5-7d402c34e10f

CR 121  
---- 
https://github.com/brave/brave-browser/assets/98358127/77bac6a4-efab-4ff4-a167-0b2e13740cf6

## Expected result:
exit IP should change in both cases.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.64.65 Chromium: 122.0.6261.29 (Official Build) nightly (64-bit)
-- | --
Revision | a31a4290998445a19f5f22b803256e97ec3036a5
OS | Windows 11 Version 23H2 (Build 22631.3085)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @fmarier 
cc: @brave/qa-team

**Comment by rebron** [comment]
cc: @boocmp

**Comment by fmarier** [comment]
Possibly related to https://github.com/brave/brave-browser/issues/35464

**Comment by boocmp** [comment]
No it isn't, I checked. There is an issue with serialization of the HostPortPair (our auth part), I'll fix it today.

**Comment by LaurenWags** [comment]
Added `QA/Blocked` as this requires uplift to 1.63.x

**Comment by kjozwiak** [comment]
The above requires `1.63.161` or higher for `1.63.x` verification 👍 Removing `QA/Blocked` as the above was uplifted into the `1.63.x` branch.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.63.161 Chromium: 122.0.6261.57 (Official Build) (64-bit)
-- | --
Revision | 37b02b4a373f40114e70cc034e491bcc8380f23a
OS | Windows 10 Version 22H2 (Build 19045.4046)

```

- Visited https://check.torproject.org/, did a hard refresh (Ctrl+Shift+R/Cmd+Shift+R) and ensured that the IP address changes to new IP
- Visited https://check.torproject.org/ and clicked `New Tor connection` for this site in app menu and ensured that the IP address changes to new IP

Example | Example | Example
----------|-----------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/70b56436-f785-4759-a48c-93ffd4ae76bf) | ![image](https://github.com/brave/brave-browser/assets/38657976/596fca73-ca30-48f3-8297-454b3f444617) | ![image](https://github.com/brave/brave-browser/assets/38657976/3bc763e7-08a9-4b00-ba96-e15c4a848893)
