### ISSUE TITLE
'Account session expired' error is not removed after upgrading to Premium

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#35998]
## Description 
'Account session expired' error is not removed after upgrading to Premium

**Note** - Opening new tab or relaunching app will remove it. 

## Steps to reproduce 

Case: upgrading when chat is active / rate limit is reach

   1. Start with fresh profile
   2. Enable Leo, begin using chat
   3. Once rate limit is reached, upgrade when upgrade card is presented
   4. After completing IAP, returning to chat shows some warning messages
   5. Hit retry/refresh several times 
   6. Try using chat some more and then try dismissing the warnings/errors

## Actual result 
Error message is not removed when tapping `refresh`, relaunching browser will remove the error message from chat. 

After subscribing | Tap Retry/Fresh
-|-
![Screenshot 2024-02-12 at 4 39 13 PM](https://github.com/brave/brave-browser/assets/17885425/203b0c35-e374-4066-9a61-ceb8e3286b60) | ![Screenshot 2024-02-12 at 10 55 37 AM](https://github.com/brave/brave-browser/assets/17885425/e1e7787b-0d46-4b3c-b654-36c3a00abce4)

## Expected result
Account session error message is shortly after subscribing (15-20 secs)

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version?  N/A
- Can you reproduce this issue with the current Play Store Beta version? N/A
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21
   - Android version: 13
   
## Brave version
`1.64.65, Chromium: 122.0.6261.29`

**Comment by SergeyZhukovsky** [comment]
@Uni-verse does close/open Leo chat window help to get rid of that message? Or do you only need restart. It happens to me when the credentials are not fully fetched and the chat window tries to check them. But it goes away when they are fetched and I re-open the chat window.

**Comment by Uni-verse** [comment]
> @Uni-verse does close/open Leo chat window help to get rid of that message? Or do you only need restart. It happens to me when the credentials are not fully fetched and the chat window tries to check them. But it goes away when they are fetched and I re-open the chat window.

@SergeyZhukovsky Yes, it will remove the message after relaunching the browser or opening new tab but still persists in the same tab for a while, not sure if we can improved this.  I've updated the description to mention this as well.

**Comment by SergeyZhukovsky** [comment]
Closing as it's a dup of https://github.com/brave/brave-browser/issues/36211 and it's been resolved.

**Comment by petemill** [comment]
This is the better issue, so using it for https://github.com/brave/brave-core/pull/22149

**Comment by kjozwiak** [comment]
The above requires `1.63.159` or higher for `1.63.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` using version: 

```
Brave	1.63.161 Chromium: 122.0.6261.57 (Official Build) (64-bit) 
Revision	37b02b4a373f40114e70cc034e491bcc8380f23a
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Ensured fresh credentials dialog is not shown after upgrading Leo

https://github.com/brave/brave-browser/assets/17885425/180a1755-e209-4ec4-86c7-2a9be6ae13e8
