### ISSUE TITLE
tapping `Brave wiki` within the `Chat Privately with Brave Leo` opens the website within the Leo WebUI

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#35990]
## Description 

When tapping on `Brave wiki`, we shouldn't be opening the link(s) within the `Leo` WebUI as we're already opening the link within the current tab. You basically get into a case where the tab loads the website, and it's loaded within the WebUI as well. You'll have the same website opened twice.

**`Note:`** Within `1.63.x`, it opens it within the `Leo` webview but NOT within the current tab. 

## Steps to reproduce 

   1. install/launch `1.64.65 Chromium: 122.0.6261.29`
   2. visit any website and within the `Hamburger Menu`, select `Leo`
   3. click on `Summarise this page` and then tap/click on `Brave wiki` within the `Chat Privately with Brave Leo` text.

## Actual result 

https://github.com/brave/brave-browser/assets/2602313/ce243b4d-5190-49f7-a0f2-702778ef607a

![Screenshot_20240212-172134](https://github.com/brave/brave-browser/assets/2602313/62d032aa-4929-400a-9efc-49d1e76e63a8)

## Expected result

I'm not 100% sure what the flow should be, but we shouldn't be opening the website within the `Leo` Webview. Maybe just let it open within the current tab like it does currently and let the user decide if they want to dismiss `Leo` to read through the website.

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A`
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 8 Pro`
   - Android version: `Android 14`
   
## Brave version

```
Brave | 1.64.65 Chromium: 122.0.6261.29 (Official Build) canary (64-bit)
--- | ---
Revision | a31a4290998445a19f5f22b803256e97ec3036a5
OS | Android 14; Build/UQ1A.240105.004; 34; REL
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @SergeyZhukovsky @hffvld @Uni-verse

**Comment by kjozwiak** [comment]
The above requires `1.63.155` or higher for `1.63.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit) 
Revision	b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Verified links are opened in tab and not in webUI.
- Verified links can be opened in tab group and also in the background (separate tab).
- Verified link is opened when using long-press menu -> open in browser

https://github.com/brave/brave-browser/assets/17885425/6b471ca1-b068-4ed7-a841-34363bf6e520
