### ISSUE TITLE
Responsibility of Playlist related classes is ambiguous

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#35991]
Feedback from @bridiver  https://github.com/brave/brave-core/pull/21332#discussion_r1486741115

> The responsibilities of the various components here are very unclear to me. There doesn't seem to be a clear distinction between what the tab helper is responsible for vs the service vs the download manager. Where did these found_items even come from here? Trying to follow what is happening here is extremely difficult.

> I think we need to clearly articular what the function of each class is here because it seems to just bounce back and forth with classes calling back into each other at various points in the process

**Comment by bsclifton** [comment]
Assigned @szilardszaloki
- we have one open PR for https://github.com/brave/brave-core/pull/22002 which has some approvals and should be merged sometime soon.
- there is work based on that branch which is happening in a branch here https://github.com/brave/brave-core/compare/master...szilard/dont-queue-background-webcontents-requests
