### ISSUE TITLE
Migrate bat-native-ads to brave-core

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#3599]

**Comment by tmancey** [comment]
Test Plan: Confirm Ads work as expected, however this has been tested in other tickets so how much needs testing would depend on other tickets

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.63.40 Chromium: 74.0.3729.61 (Official Build) beta (64-bit)
-- | --
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Windows 10 OS Build 17134.523

- Verified "View", "click", "landed" and "dismiss" status in `Confirmations.json`
- Verified Ads received and current earnings displayed properly in Ads panel in brave://rewards page
- Encountered #4023, #4102 #https://github.com/brave/brave-browser/issues/4026
