### ISSUE TITLE
`Third-party cookies` site settings not in sync with shield settings or brave://settings/cookies settings

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#36002]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/35200

`Third-party cookies` site settings is inherited from Chromium 122, Turn on/off  `Third-party cookies` site settings don't affect the site.  The **_shield settings or brave://settings/cookies settings are taking precedence over the `Third-party cookies` site settings_**, looks like this is redundant settings and not required in Brave.

## Steps to Reproduce

   1. Clean profile 1.64.x CR122
   2. Open a site any site (e.g cnn.com)
   3. Open site information 
   4. `Third-party cookies` site settings is inherited from chrome
   5. Confirm that the settings is turned off by default
   6. Enable the settings
   7. Reload the site, there is no change on the site, 3rd party cookies are blocked on the site as 3rd party cookies are blocked on brave://settings/cookies and brave://settings/shields
   8. Go back to the site and change the settings to off
   9. Reload the site, there is no change on the site, 3rd party cookies are blocked on the site as 3rd party cookies are blocked on brave://settings/cookies and brave://settings/shields

## Actual result:

Turn on/off  `Third-party cookies` site settings is not in sync with shield settings or brave://settings/cookies settings
![image](https://github.com/brave/brave-browser/assets/38657976/37d7a9fc-04b9-40a2-9c92-875a2c12f6f2)

## Expected result:
The `Third-party cookies` site settings doesn't take affect on the site. Would be better to remove this settings from Brave

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.64.65 Chromium: 122.0.6261.29 (Official Build) nightly (64-bit)
-- | --
Revision | a31a4290998445a19f5f22b803256e97ec3036a5
OS | Windows 10 Version 22H2 (Build 19045.3930)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @goodov @rebron @bridiver

**Comment by kjozwiak** [comment]
The above requires `1.63.155` or higher for `1.63.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 10 Version 22H2 (Build 19045.3930)
```
- Confirmed that the `Third-party cookies` settings is removed from the site setings
![image](https://github.com/brave/brave-browser/assets/38657976/f4db943c-36fb-42eb-856e-c37f590f9311)
