### ISSUE TITLE
Omnibox Command Palette missing

### ISSUE THREAD

**Issue by HemalR** [brave/brave-browser#36001]
## Description 
I had turned this on via a flag (can't remember which but might have been brave://flags/#quick-commands ).

As of a few weeks ago, the flag in question has disappeared and running commands from the omnibox (e.g. pin tab/take screenshot etc.) is no longer possible.

## Steps to Reproduce
* Try running commands from the omnibox - it is no longer possible. E.g Pin tab
* Cmd + Spacebar also doesn't focus the omnibox any more

## Actual result:
Omnibox only provides search results. Not commands/actions.

## Expected result:
Commands/actions to be available in the omnibox.

## Brave version (brave://version info)
[Version 1.62.156 Chromium: 121.0.6167.139 (Official Build) (arm64)](https://brave.com/latest/)

**Comment by HemalR** [comment]
Thank you!!! (Hoping this gets past the experimental stage soon, it's so useful!)

**Comment by fallaciousreasoning** [comment]
Yup - in 1.63 we're considering it launched :smile: Any other commands you think would be useful?

**Comment by fallaciousreasoning** [comment]
If so, feel free to add them to this issue: https://github.com/brave/brave-browser/issues/35999

**Comment by HemalR** [comment]
Yes, although I think some of these may not be doable in Brave because of the underlying way things work (these are commands I used a lot in Arc):

- Allow typing and opening a profile from here - I know Cmd+Shift+M brings up that menu, but the cognitive load of a single shortcut is easier plus it allows typing vs having to arrow down to the right profile.
- Moving a tab to a different profile in case it's been opened in the wrong one (in fact, Arc has this automatically based on the users url preferences)

Edit - Just seen your other comment. I'll bookmark that and add to it thanks 👍
