### ISSUE TITLE
AdsServiceImpl::RunDBTransaction slow down on each navigation

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#36008]
On my personal profile `RunDBTransaction` takes a lot of CPU time when I navigating to each frame.
The bad thing is that a part of the work (11ms on MBP M1 pro) is done on the UI thread.

UI thread:
<img width="878" alt="Screenshot 2024-02-13 at 17 02 59" src="https://github.com/brave/brave-browser/assets/45488748/f93d0bf1-392e-4d9c-a757-9af2e40655f6">

A thread for the pool:
<img width="878" alt="Screenshot 2024-02-13 at 17 03 24" src="https://github.com/brave/brave-browser/assets/45488748/a8621591-82bd-41d8-a11d-92cc2956c1ab">

**Comment by atuchin-m** [comment]
I can't find the matching things in traces on perf bots. Probably it's related to the database size.
On the other hand, `RewardsServiceImpl` consumes 20ms on android bot pixel4 (the thread pool):
<img width="677" alt="image" src="https://github.com/brave/brave-browser/assets/45488748/d76f5f88-3e79-4ace-bcc0-36ccd42cff0c">


@aseren @tmancey 
Any suggestions how to debug this?

**Comment by atuchin-m** [comment]
the trace (just navigation to example.com from about:blank):
[trace_ads-ui-tread-issue.json.gz](https://github.com/brave/brave-browser/files/14267189/trace_ads-ui-tread-issue.json.gz)

**Comment by atuchin-m** [comment]
`payload_size` in another method takes 3.5MB 
![image](https://github.com/brave/brave-browser/assets/45488748/62ada0c9-9d55-436c-b662-ca2d39cbf452)

**Comment by atuchin-m** [comment]
I've managed to transfer the profile to use with a local static build and debugger.
Here is some details:
UI thread:
<img width="825" alt="Screenshot 2024-02-14 at 14 16 25" src="https://github.com/brave/brave-browser/assets/45488748/f0b6cefc-946d-407c-ae2d-5d20b31b2292">

a task runner:
<img width="763" alt="Screenshot 2024-02-14 at 14 13 07" src="https://github.com/brave/brave-browser/assets/45488748/060ae213-ad93-4edc-b21c-bfd6614d44ad">

**Comment by atuchin-m** [comment]
I believe the main issue is the number of entries that we select from db:
![image](https://github.com/brave/brave-browser/assets/45488748/46436b7c-1342-4c56-93a6-e3999071163b)
That's why just serializing/deserializing on the UI thread of the set takes a lot time in my case.

**Comment by atuchin-m** [comment]
The request: https://github.com/brave/brave-core/blob/master/components/brave_ads/core/internal/user_engagement/ad_events/ad_events_database_table.cc#L239-L243

**Comment by iefremov** [comment]
cc @tmancey

**Comment by atuchin-m** [comment]
Linked issue: https://github.com/brave/brave-browser/issues/36056

**Comment by atuchin-m** [comment]
Related issue: https://github.com/brave/brave-browser/issues/36058

**Comment by tmancey** [comment]
Closing as resolved by https://github.com/brave/brave-browser/issues/36058
