### ISSUE TITLE
[CR122] Incorrect PDF page summary & suggested questions are rendered in Leo

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#36016]
## Description 

Thanks @GeetaSarvadnya for finding the issue as part of CR 122 desktop affected areas. 
Leo summarization of the PDF page is incorrect and as a result, suggested questions are incorrect as well in the freemium model.  Noticed with the Limited default, Mixtral, model, summary is not rendered quickly even after the wait of >30sec and since there is no spinner, had to refresh the page.  Sometimes, `suggest questions...` button spins as well.  Verified with Premium models, and the summary is rendered quickly but still has same incorrect summarization issues.  Correct summary rendered in `1.64.61 Chromium: 121.0.6167.164` (Latest nightly before CR 122)

## Steps to Reproduce

1. installed 1.64.69
2. launch Brave
3. visit https://basicattentiontoken.org/static-assets/documents/BasicAttentionTokenWhitePaper-4.pdf
4. click on Leo in the sidebar
5. click `Summarize this page`
6. clicked I understand

## Actual result:

Couple of issues have been noticed with the free default model
1.   summary is not shown even after a wait of >30 sec.  No spinner shown. Had to refresh 
2.   Page summary is incorrect
3.   Got incorrect suggested questions.

Freemium 

https://github.com/brave/brave-browser/assets/98358127/045c5fdf-5365-4314-aba1-218f27ada98c

Premium

https://github.com/brave/brave-browser/assets/98358127/5223a112-ea38-43c8-82e9-78fc9a54db61

## Expected result:
Correct summarization and suggested questions should be rendered

## Reproduces how often: 
Easily

## Brave version (brave://version info)

```
Brave | 1.64.69 Chromium: 122.0.6261.29 (Official Build) nightly (64-bit)
-- | --
Revision | 3992d5550b2a00310f063f95c597bb87c31b4d47
OS | Windows 11 Version 23H2 (Build 22631.3085)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@emerick @mattmcalister 
cc: @rebron @brave/qa-team

**Comment by rebron** [comment]
cc: @darkdh @bbondy

**Comment by darkdh** [comment]
@MadhaviSeelam did you switch to other apps right after you opened the pdf file?

**Comment by MadhaviSeelam** [comment]
> @MadhaviSeelam did you switch to other apps right after you opened the pdf file?

@darkdh I am not sure if I understood the question, but I've tested this on Win 11 desktop and loaded pdf file and queried with Leo.

**Comment by bbondy** [comment]
This is only reproducible btw @darkdh when the user is NOT opted in yet. Something related to first time use.

**Comment by MadhaviSeelam** [comment]
> This is only reproducible btw @darkdh when the user is NOT opted in yet. Something related to first time use.

@darkdh confirmed what @bbondy said.  Correct PDF summarization returned when opted-in.  (As an existing premium user)

https://github.com/brave/brave-browser/assets/98358127/d3db08f2-36f3-40e6-8ac7-8db3cf61f05d

**Comment by stephendonner** [comment]
Reproduced also with

```
Brave | 1.64.72 Chromium: 122.0.6261.29 (Official Build) nightly (x86_64)
-- | --
Revision | f2269310f9081d98f47dec5428c59f087de0814e
OS | macOS Version 11.7.10 (Build 20G1427)
```

<img width="1393" alt="Screen Shot 2024-02-14 at 1 53 46 PM" src="https://github.com/brave/brave-browser/assets/387249/dc819ffb-539a-4b99-8125-b5277712a88d">

**Comment by kjozwiak** [comment]
The above requires `1.63.157` or higher for `1.63.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.63.157 Chromium: 122.0.6261.43 (Official Build) (64-bit)
-- | --
Revision | 5fbb7c60cc44e15a910a39a349e632f1b904c58e
OS | Windows 10 Version 22H2 (Build 19045.4046)

```
