### ISSUE TITLE
Use drop down menu when setting Normal Window search engine preference

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#36019]
## Description 

With Chromium 122, there's a new button and dialog when choosing Normal Window search engine. 

We should still use the drop down menu similar to setting a search engine in Private Window, for Normal Window search engine selection.

## Steps to Reproduce

   1. Use 1.64.65 and higher with Chromium 122
   2. Got to brave://settings/search
   3. Notice the button and dialog box when choosing a search engine for normal window

## Actual result:

![screenshot_2024-02-13_at_8 59 41___am](https://github.com/brave/brave-browser/assets/5951041/1902d6e2-9cdc-4aec-8a5e-da22782be0b2)

## Expected result:

![screenshot_2024-02-13_at_8 57 18___am_720](https://github.com/brave/brave-browser/assets/5951041/4eced19e-8319-4ed5-ae90-b1ede9c95ea2)

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.64.65 and higher

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? yes

**Comment by GeetaSarvadnya** [comment]
Looks like macOS only issue. This issue is not reproducible on Windows 10 x64

```
Brave | 1.64.69 Chromium: 122.0.6261.29 (Official Build) nightly (64-bit)
-- | --
Revision | 3992d5550b2a00310f063f95c597bb87c31b4d47
OS | Windows 10 Version 22H2 (Build 19045.3930)

```

**Comment by emerick** [comment]
Yes, Windows already had this feature disabled.

**Comment by GeetaSarvadnya** [comment]
@emerick This is CR122 specific issue correct?

**Comment by emerick** [comment]
Yes this is CR122-specific. They enabled a new feature flag on Mac/Linux. We updated our code to turn it off everywhere.

**Comment by MadhaviSeelam** [comment]
Reproduced in Linux as well in Cr 122

![Screenshot from 2024-02-14 09-19-05](https://github.com/brave/brave-browser/assets/98358127/b5dcba17-df54-4dda-b9aa-d71248b67af2)

**Comment by kjozwiak** [comment]
The above requires `1.63.155` or higher for `1.63.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (x86_64)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | macOS Version 13.6.4 (Build 22G513)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.63.157 Chromium: 122.0.6261.43 (Official Build) (64-bit) 
Revision	5fbb7c60cc44e15a910a39a349e632f1b904c58e
OS	Linux
```
