### ISSUE TITLE
Connecting an account in Brave Rewards may cause a null pointer exception if Wallet is locked

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#36018]
## Description

When connecting an account in Brave Rewards panel and selecting a self-custody Brave Wallet may cause a null pointer exception if the Wallet is locked.

Slack discussion (issue 3) 👉 https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1707759099323519?thread_ts=1707513505.767269&cid=C023VS4HJ6Q

<img width="713" alt="image" src="https://github.com/brave/brave-browser/assets/3308503/999e6bb8-896e-4ab8-a8be-cf8847d75465">

## Steps to reproduce
   1. Make sure the Wallet is locked.
   2. Tap on Brave Rewards icon
   3. Tap on Connect account in the panel
   4. Tap on Brave Wallet option
   5. Tap again on Brave Wallet option
   6. Tap on the toast at the bottom to open the UI to unlock the Wallet
   7. Type the password to unlock the Wallet and press unlock
   8. Observe Brave app crashing

## Issue reproduces how often 

Intermittent issue

**Comment by kjozwiak** [comment]
The above requires `1.63.155` or higher for `1.63.x` verification 👍
