### ISSUE TITLE
Add android exception for type converter playlist

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#36011]
This issue is to resolve the crash on desktop : https://bravesoftware.slack.com/archives/C7VLGSR55/p1706890464678999

**Comment by kjozwiak** [comment]
Closing/Adding missing milestone as the above was already merged into `master` as per https://github.com/brave/brave-browser/issues/35158. Incorrect format was used hence the GH bot not closed/moving the issue into the correct milestone.
