### ISSUE TITLE
Suppress 'Turn on enhanced protection' message shown on interstitial pages for insecure pages

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#36027]
## Description 
Suppress 'Turn on enhanced protection' message shown on interstitial pages for insecure pages

**New feature in `Chromium 122`** 

Slack thread: https://bravesoftware.slack.com/archives/C7VLGSR55/p1707855258123319?thread_ts=1707520964.163159&cid=C7VLGSR55

## Steps to reproduce 

   1. Start with fresh profile
   2. Navigate to https://badssl.com and open one of the test pages
   3. Observe

## Actual result 

https://github.com/brave/brave-browser/assets/17885425/1c2b2957-f136-46e6-8bdb-871b8fb1828d

## Expected result
Suppress `Turn on enhanced protection` message

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes (C122 feature)

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung devices
   - Android version: 13
   
## Brave version
`1.64.69 Chromium: 122.0.6261.29`

**Comment by kjozwiak** [comment]
The above requires `1.63.155` or higher for `1.63.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit) 
Revision	b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Verified STR in https://github.com/brave/brave-browser/issues/36027#issue-2133089564
- Verified clicking through interstitial page works

Example | Example
-|-
![Screenshot 2024-02-15 at 11 47 36 AM](https://github.com/brave/brave-browser/assets/17885425/64f139f7-e46e-4560-aa17-bea93675297a) | ![Screenshot 2024-02-15 at 11 48 08 AM](https://github.com/brave/brave-browser/assets/17885425/4f109c0b-f4e9-48ac-87ba-4b9b56cd15de)
