### ISSUE TITLE
Nan% can be shown in Portfolio when networks hidden

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#36020]
## Description: 

On Portfolio, when hiding a all networks with balance the % change can be displayed as `nan%`.

## Steps to Reproduce 
  1. Use a wallet with some balance
  2. Hide all networks with a balance in Portfolio Filters (I used a wallet with only test network balance)
  3. Observe `nan%` can be displayed in the % change badge

## Actual result: 

<img src="https://github.com/brave/brave-browser/assets/5314553/d9161e1a-7ab6-4512-ac29-a5687cc3446a" width="250">

## Expected result:

0% change shown when networks hidden, or don't show the % change badge.

## Reproduces how often: 

Easily reproduced

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari?

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.5 running 1.66 (104)
- Verified steps from [brave/brave-core#22704](https://github.com/brave/brave-core/pull/22704)
- Verified when all networks are hidden in Portfolio `Nan%` is not shown under Portfolio balance

https://github.com/brave/brave-browser/assets/17010094/636f141f-6068-4396-94e0-5d132bb30ac9
