### ISSUE TITLE
Enable Brave Browser to be an AutoFill Provider

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#36028]
Add the ability for Brave to be an password manager in a sense, where as the users stored passwords will then be accessible from the iOS keyboard in `WKWebView`

This involves adding a new target to the project `AutoFill Credential Provider`.

More information about the APIs can be found by watching the [WWDC 2018 721 - Implementing AutoFill Credential Provider Extensions](https://developer.apple.com/videos/play/wwdc2018/721/) or reading the [AuthenticationServices doc](https://developer.apple.com/documentation/authenticationservices)

- [ ] Add an `AutoFill Credential Provider`
- [ ] Use Chromium implementation for handling password <> `AuthenticationServices` sync
- [ ] Potentially have new UI for the `AuthenticationServices` API

Potential caveats to take into account:
- The user has to explicitly enable it in `Settings > Passwords & Accounts > AutoFill Passwords`
- The user can only have 2 (+ iCloud?) AutoFill providers enabled
- The user has to do this process manually via the keyboard unlike in 1.6 where the username/password were auto-filled upon loading the page.

Screenshots of AutoFill Providers (1Password in this case): 

| Enabling AutoFill Providers | Single AutoFill | Single Auto-Fill 2 |
| --- | --- | --- |
| ![img_3745](https://user-images.githubusercontent.com/529104/46434207-01a15a80-c721-11e8-8cf8-fd1a41968cae.png) | ![img_3755](https://user-images.githubusercontent.com/529104/46434420-9441f980-c721-11e8-82e9-dd6fb09db3eb.jpg) | ![img_3756](https://user-images.githubusercontent.com/529104/46434435-9d32cb00-c721-11e8-9176-0d665a1b8024.jpg) |

| Multiple Logins (Tapping the 🔑) | Tapping "1Password…" UI |
| --- | --- |
| ![img_3751](https://user-images.githubusercontent.com/529104/46434493-c2273e00-c721-11e8-983a-0d9a1940cde8.jpg) | ![img_3752](https://user-images.githubusercontent.com/529104/46434499-c81d1f00-c721-11e8-9703-0f3f10d105c3.jpg) |

**Comment by davidcollini** [comment]
Congrats on the implementation!

**Comment by Saoiray** [comment]
@kylehickinson glad to see it looks like might be coming, but is it really going to be waiting until 1.66 or we have likelihood of uplifting to sooner release? Asking as we're currently on 1.62.2 for iOS. Trying to figure out how long of a wait for everyone.

**Comment by kylehickinson** [comment]
@Saoiray iOS releases are a bit behind, 1.63 will come next week followed very quickly by 1.64. We may however uplift this into 1.65 (mid-April) to get it out a bit quicker.

**Comment by Saoiray** [comment]
> @Saoiray iOS releases are a bit behind, 1.63 will come next week followed very quickly by 1.64. We may however uplift this into 1.65 (mid-April) to get it out a bit quicker.

kk. Thanks for the info. I'll be looking forward to it.

**Comment by iccub** [comment]
This will land in public beta soon and as far as I remember we are going to allow default browser setting for public beta app soon as well

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.3.1` using version `1.66.104`

- Ensured Brave is shown as an autofill provider in `Password Options` and can be enabled for new and existing users.
- Ensured existing saved passwords in Brave are not changed when upgrading. 
- Ensured Brave autofill data is shown in saved passwords.
- Ensured that autofill data is populated when selecting saved password from Brave.

Autofill settings | Confirmation | Saving password | Saved Password | Using Saved Password
-|-|-|-|-
![IMG_6062](https://github.com/brave/brave-browser/assets/17885425/7ae530f7-cba9-4485-a01f-8e809f84ecc1) | ![IMG_6122](https://github.com/brave/brave-browser/assets/17885425/afe3c16e-7003-4b6b-a6da-721f968483c8) | ![IMG_6123](https://github.com/brave/brave-browser/assets/17885425/ae8a0ccb-f12a-4f5a-821f-f20a3b1ab98d) | ![IMG_6124](https://github.com/brave/brave-browser/assets/17885425/d75c4a77-44c5-4b40-8417-eb8c0d756d48) | ![IMG_6128](https://github.com/brave/brave-browser/assets/17885425/e5c97dd0-46f3-4912-add9-3805cf28c4a2)

- Ensured tapping the key icon will display multiple saved password if available.
- Ensured password field can be populated by opening the saved password details and tapping on `Use` in the top right.
- Ensured copied password can be pasted when opening password manager and selecting copy from the context menu. 
- Ensured revealing password works when tapping on the eye in Brave Passwords.
- Ensured other (non-Brave) autofill provider can be used for autofill along with Brave. 

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_6063](https://github.com/brave/brave-browser/assets/17885425/823be45e-4488-46e1-ae99-308dbd4b8ca2) | ![IMG_6064](https://github.com/brave/brave-browser/assets/17885425/8e4bd211-9b97-401f-bb8e-6771e039ce74) | ![IMG_6065](https://github.com/brave/brave-browser/assets/17885425/0dfbee9a-8274-4748-9468-70a807d0dac8) | ![IMG_6066](https://github.com/brave/brave-browser/assets/17885425/33d57d08-0799-4cfd-93c7-cbfcc733e694) | ![IMG_6067](https://github.com/brave/brave-browser/assets/17885425/502cb379-efc7-49b4-a9c6-08f9eeeb102e)

- Ensured that Brave autofill is enabled on other apps on the device. 

Example | Example | Example
-|-|-
![IMG_6135](https://github.com/brave/brave-browser/assets/17885425/bf8eea2c-fc35-4e88-b3e8-73e33c084338) | ![IMG_6136](https://github.com/brave/brave-browser/assets/17885425/577ec051-8d44-437d-91b0-192a4ccff994) | ![IMG_6137](https://github.com/brave/brave-browser/assets/17885425/51612407-65e0-44a9-b3d8-79737bda0e04)
