### ISSUE TITLE
Use the debounce service from brave-core and drop the iOS custom service

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#36033]
### Description: 
We download the debounce list in iOS. We should be able to get it from the component updater.
This does not change the behaviour of the feature, just changes how we get the files.

### Test plan
Perform all the tests on https://dev-pages.brave.software/navigation-tracking/debouncing.html
Note: Performing Run on Default and Base64 will result in an error page when debounce is off. This is fine
Note2: The toggle can be found under advanced shield settings as "Auto Redirect Tracking URLs"

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.3.1` using version `1.66.90`

- Verified test cases on test page https://dev-pages.brave.software/navigation-tracking/debouncing.html
- Verified that debouncing works when "Auto Redirect Tracking URLs" is enabled. 

Example | Example
-|-
![IMG_6006](https://github.com/brave/brave-browser/assets/17885425/47b7677c-1352-4f37-8081-efd1cbb5598d) | ![IMG_6008](https://github.com/brave/brave-browser/assets/17885425/48482281-724a-4348-b29e-86551a9d275d)
