### ISSUE TITLE
[iOS] Add custom filter list in text format

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#36034]
### Description: 
Add custom text format filter list similar to desktop and android
<img width="696" alt="Screenshot 2023-09-14 at 1 33 55 PM" src="https://github.com/brave/brave-ios/assets/909331/3c8fe9ba-a5a2-4742-baa3-044cf7a279c1">

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6
Brave build: 1.68 (115)
BraveCore: 1.68.115 (127.0.6533.26)
```
---------------------------
<details>
<summary> Valid rules </summary>

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/23548#issue-2288323002
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `CUSTOM FILTERS` menu with title, subtitle, and input text field is shown under `Settings` > `Shields & Privacy` > `Content Filtering`
- Verified that the user is able to `add` and `save` a custom filer
- Verified that the main screen (Content Filtering) shows the first 2 lines under `CUSTOM FILTERS` when a new custom filter is added and saved
- Verified that the header title is blocked on https://example.com/ when custom filter from the [TP](https://github.com/brave/brave-core/pull/23548#issue-2288323002) is added
- Verified that the logo is blocked on https://www.iana.org/help/example-domains when custom filter from the [TP](https://github.com/brave/brave-core/pull/23548#issue-2288323002) is added

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/15d23b2d-7196-449e-84ee-89af5d64dd4e) | ![2](https://github.com/brave/brave-browser/assets/128532965/27aac409-83b2-4950-b76e-be5b9916d90e) | ![3](https://github.com/brave/brave-browser/assets/128532965/3fa3a267-2ef2-46d9-adc6-2d2003b25220) | ![4](https://github.com/brave/brave-browser/assets/128532965/512ea448-c948-46fd-a362-4fd26f7bd7e7) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/405d280b-fadb-432d-87ac-90e7496f9174) | ![2](https://github.com/brave/brave-browser/assets/128532965/865dea22-d925-429b-a5e3-7668466b8066) | ![3](https://github.com/brave/brave-browser/assets/128532965/f9a649f5-2d91-4209-a929-ef1d3cda3adb) | ![4](https://github.com/brave/brave-browser/assets/128532965/182aed4d-240c-4bce-af95-52436a9c32b6) |
</details>

<details>
<summary> Valid rules </summary>

**STEPS:**
1. Launch Brave 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>

<details>
<summary> Valid rules </summary>

**STEPS:**
1. Launch Brave 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>
