### ISSUE TITLE
[iOS] Add search to filter lists screen

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#36036]
### Description: 
Add a simple search to the filter lists screen so filter lists are easier to manage similar to the one found in desktop:

<img width="652" alt="Screenshot 2023-02-13 at 3 07 04 PM" src="https://user-images.githubusercontent.com/909331/218479892-4ec1cf23-0ec5-44cf-a8c7-c4b16096900c.png">

Here are the design images:
![image](https://user-images.githubusercontent.com/909331/218480083-a4b26347-1fd8-46a7-86e2-e81d820c862e.png)

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18` using version `1.70 (123)`

- Ensured that searching works in `Content Filtering` using the search bar.
- Ensured that searching is not case sensitive.
- Ensured search results include both External Filter Lists and Default Filter Lists.

example | example | example | example
---|---|---|---
![IMG_7610 2](https://github.com/user-attachments/assets/ed8c2d76-0220-4363-9890-ef1a33fafdff) | ![IMG_7611 2](https://github.com/user-attachments/assets/e5d21129-5b2d-4584-8c7b-006f0a931307) | ![IMG_7612 2](https://github.com/user-attachments/assets/0cc6d5e4-073c-406f-aa21-60dca9ecf1b2) | ![IMG_7613 2](https://github.com/user-attachments/assets/3950d628-5fa1-460e-98a1-93ad7607e351)
