### ISSUE TITLE
Chromium bookmark icon used in Brave custom tab menu

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#36042]
## Description 
Regression in C122, initial state uses chrome/chromium bookmark icon in custom tab. Correct one is used after page is bookmarked

## Steps to reproduce 

   1. Open link in custom tab
   2. Click on hamburger menu
   3. Observe bookmark icon
   4. Click bookmark icon
   5. Open menu again

## Actual result 

Menu (default) | Bookmarked | Menu (after bookmarking)
-|-|-
![Screenshot 2024-02-13 at 5 45 34 PM](https://github.com/brave/brave-browser/assets/17885425/496d0328-67b0-476b-b810-5fe256f18123) | ![Screenshot 2024-02-13 at 5 45 38 PM](https://github.com/brave/brave-browser/assets/17885425/8af353c2-06f3-4d2e-8af8-3e07ff6a90fb) | ![Screenshot 2024-02-13 at 5 45 42 PM](https://github.com/brave/brave-browser/assets/17885425/90c7226f-af57-4c6b-9a32-e74aef4efd5c)

## Expected result
Brave bookmark should be used

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21
   - Android version: 13 
   
## Brave version
`1.64.69 Chromium: 122.0.6261.29`

**Comment by samartnik** [comment]
Updated with new icon from figma https://www.figma.com/file/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?type=design&node-id=2936-30763&mode=design&t=WTZqC8bzZ0On6ApI-0

![Screenshot_20240214_102434](https://github.com/brave/brave-browser/assets/30602739/0946988e-9e95-48d2-86db-37c0973c0562)

**Comment by kjozwiak** [comment]
Closing as the above has been fixed and will be uplifted into `1.63.x` via https://github.com/brave/brave-core/pull/22014.

**Comment by kjozwiak** [comment]
The above requires `1.63.155` or higher for `1.63.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit) 
Revision	b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Verified test plan in https://github.com/brave/brave-browser/issues/36042#issue-2133291866
- Verified bookmarking custom tab works and state of the icon is updated in the menu
- Verified there are no issues opening page in browser

Example | Example | Example | Example
-|-|-|-
![Screenshot 2024-02-15 at 11 30 09 AM](https://github.com/brave/brave-browser/assets/17885425/4df135c8-43c2-4a5a-8268-7b7160fc10ca) | ![Screenshot 2024-02-15 at 11 30 12 AM](https://github.com/brave/brave-browser/assets/17885425/2a17ad2a-2eeb-4930-a45d-cf945a857480) | ![Screenshot 2024-02-15 at 11 30 16 AM](https://github.com/brave/brave-browser/assets/17885425/44f79e05-cd5a-4b67-a65c-f39b3d5a3843) | ![Screenshot 2024-02-15 at 11 32 45 AM](https://github.com/brave/brave-browser/assets/17885425/d93da185-d011-4f59-8802-b13723860caf)
