### ISSUE TITLE
[Leo] The chat is always connected to the web page that it was opened from

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#36040]
## Description 

The chat is always connected to the web page that it was opened from.

## Steps to reproduce 

   1. Launch Brave
   2. Open any website
   3. Three-dot menu > Leo
   4. Open a new tab > Ask to `Summarize this page` > *Observe that Leo is summarizing the original page where it was opened*

## Actual result 

The chat is always connected to the web page that it was opened from. Because of that Leo is summarizing the original page where it was opened in this case.

https://github.com/brave/brave-browser/assets/128532965/794ae406-cf89-4d7c-a5c0-596c47bf415c

## Expected result

Leo must be closed when opening another tab.

## Issue reproduces how often 

`Easily reproduced`

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? N/A
- Can you reproduce this issue with the current Play Store Beta version? YES
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM 
   - Device type (Phone, Tablet, Phablet): ANY
   - Android version: ANY
   
## Brave version

```
Brave build: 1.64.69
Chromium: 122.0.6261.29 (Official Build) canary (64-bit)
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @SergeyZhukovsky

**Comment by kjozwiak** [comment]
Closing the above as it's invalid now that we've moved to always displaying `Leo` via full screen on `Android` via https://github.com/brave/brave-core/pull/22240. The above issue isn't invalid anymore as you can't interact with Brave while `Leo` is opened, hence not being able to open a NTP while `Leo` is running. Quickly checked/verified on `Pixel 8 Pro` running `Android 14` using the following build(s):

```
Brave | 1.65.35 Chromium: 122.0.6261.69 (Official Build) canary (64-bit)
--- | ---
Revision | 8873b7ee8825b7b68a55a5ffbd3ab44759476d02
OS | Android 14; Build/UQ1A.240205.004; 34; REL
```
