### ISSUE TITLE
[ads] Orphaned ad events that are associated to an inactive creative ad or creative set conversion are not purged after 3 months

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#36058]
## Steps to Reproduce

   1. Join Brave Rewards
   2. View ads
   3. Quit the browser
   4. Remove all creative ads with the creative set id from the ad in step 2 from the `creative_ads` database table in `ads_service/database.sqlite`
   5. Use Charles Proxy to rewrite an INVALID catalog for the catalog endpoint (so that the `creative_ads` database table is not overwritten)
   6. Wait 3 months
   7. Launch the browser

## Actual result:

ad_events in `ads_service/database.sqlite` are not purged after 3 months if an ad event's creative set id cannot be associated a creative ad and a creative set conversion.

## Expected result:
ad_events in `ads_service/database.sqlite` are purged after 3 months if an ad event's creative set id cannot be associated a creative ad and a creative set conversion. i.e., the ad_event is now orphaned and no longer required because ads for that creative set will no longer be shown and do not need to be frequency capped.

## Reproduces how often: 

Easily reproduced

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by kjozwiak** [comment]
The above requires `1.63.157` or higher for `1.63.x` verification 👍
