### ISSUE TITLE
[Perf] UI thread CPU time regression v1.64.64 - v1.64.69

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#36059]
Win-11: `192ms` => 248.706 (+30%).
https://brave-perf-dashboard.appspot.com/report?sid=91d8ac470b9033e0e44ce32388c7fb77014b3ef855e2ad36c08067790b10080c
<img width="627" alt="image" src="https://github.com/brave/brave-browser/assets/45488748/ee7317d2-e2ac-4967-9c67-f12212c1d4b3">

Commit performance is also affected:
https://brave-perf-dashboard.appspot.com/report?sid=2ac6add03605f1c12ecec659827572f0ae41db8980618502c997ecc3923102f3

**Comment by zenparsing** [comment]
Possibly https://github.com/brave/brave-core/commit/2997f1b643d6240765d314c2e1362e36b636cb5a, which was reverted in https://github.com/brave/brave-core/commit/3debf2be6c203d13ec0768befd9b6b9a398eaff9 (1.70).

**Comment by atuchin-m** [comment]
ok, I'm checking `v1.64.71` to verify we are good now.

**Comment by atuchin-m** [comment]
Looks like v1.64.71 good (win-11):
<img width="572" alt="image" src="https://github.com/brave/brave-browser/assets/45488748/625b3733-3155-4ad7-868a-0935fc092265">


I will wait for mac-m1 recent builds, then close the issue.

**Comment by zenparsing** [comment]
Thanks for catching this @atuchin-m!

**Comment by atuchin-m** [comment]
The original issue: https://github.com/brave/brave-browser/issues/36025
