### ISSUE TITLE
Reloading page clears Ephemeral Storage

### ISSUE THREAD

**Issue by TEMP-ad** [brave/brave-browser#36055]
## Description 

@goodov

Ephemeral Storage is being cleared on page reload when you switch from **Always delete site data from your device when you close Brave** to **Allowed to save data on your device** and then back to **Always delete site data from your device when you close Brave** in brave://settings/content/siteData, the data gets removed immediately, which is just not what it should do, since you are not technically leaving the site and there is always 30 seconds for Ephemeral Storage to get cleared by Brave.

## Steps to Reproduce

  1. go to https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_localstorage2
  2. reload page 9 times to to increase the clicks to 10
  3. Add `[*.]w3schools.com` to **Always delete site data from your device when you close Brave** in brave://settings/content/siteData
  4. now reload the page, it should show clicks: 1
  5. now reload the page 4 times to increase the count to 5
  6. Now go to brave://settings/content/siteData and switch w3school from Clear to Allow and refresh the page.
  7. it should show 10 clicks
  8. now switch back from Allow to clear and it starts from 1 even if the storage should have never been removed since you never left the site, it should kept alive until the site is closed even if not active (or that's how it used to work)

## Brave version (brave://version info)

1.64.71 Chromium: 122.0.6261.29 (Official Build) nightly (64-bit)  Windows 11 22H2

**Comment by goodov** [comment]
I don't think disabling `brave://flags/#brave-ephemeral-storage-keep-alive` is our top priority, because the default state is always enabled, but I'll try to look into this when I have time.

**Comment by TEMP-ad** [comment]
Oh, I was fixing my Description, and I removed references to the flag, since I tested in a new user data, so it didn't matter to mention it.

Seems to be a small miss-behavior that shouldn't affect most people, but I noticed it testing around. It can be reproduced 100% of the time, so it shouldn't be hard to see what's the issue of Ephemeral Storage wiping the storage like that. 👍

Have a nice day.

**Comment by goodov** [comment]
@kjozwiak this is a follow up bugfix for https://github.com/brave/brave-browser/issues/26165
so it should land in `1.64.x`.
