### ISSUE TITLE
Token doesn't update when account is changed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36068]
## Description 
Token id doesn't update when account is changed

## Steps to reproduce 

   1. Create wallet
   2. Add multiple accounts for ETH/SOL
   3. Switch accounts from panel doesn't update the token type

## Actual result 

https://github.com/brave/brave-browser/assets/17010094/cfd9a1f1-4d55-4a84-8a49-c32f4cdd4b34

## Expected result
Should update token when account is changed

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 14
   
## Brave version
1.64.71

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe @Douglashdaniel

**Comment by kjozwiak** [comment]
The above requires `1.63.159` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.63.159 x64 build
- Verified steps from issue description and [brave/brave-core#22160](https://github.com/brave/brave-core/pull/22160)
- Verified token update in panel when changing account/network
- Encountered [#36247](https://github.com/brave/brave-browser/issues/36247)

https://github.com/brave/brave-browser/assets/17010094/42eec5f2-1cda-412f-8180-122854428f63
