### ISSUE TITLE
Youtube full screen black screen after unlocking the phone

### ISSUE THREAD

**Issue by iccub** [brave/brave-browser#36064]
## Steps to Reproduce 
  1. Play a YT video
  2. Lock the screen
  3. Unlock it

## Actual result: 
Black screen, audio keeps playing

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari?

**Comment by anthonypkeane** [comment]
https://appfigures.com/reviews/42132121512LwvJC3sTTHoX7uRvaPK9Hwg

**Comment by kjozwiak** [comment]
The above requires `1.64.99` or higher for `1.64.x` verification 👍
