### ISSUE TITLE
Leo auto suggestions have to be unlinked from a page context

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#36074]
We shouldn't use page context if there is no ongoing chat using it already.
Open a random page:
1. Type something in the URL bar.
2. Tap Ask Leo.
3. Make sure that the page context isn't used for the answer.

**Comment by kjozwiak** [comment]
@hffvld @Uni-verse can use https://github.com/brave/brave-core/pull/22061#issuecomment-1947488571 as a quick template for verification on `1.63.x` for the above. Basically need to ensure that the correct context is being used when expected. The above requires `1.63.156` or higher for `1.63.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 8 Pro` running `Android 14` using the following build(s):

```
Brave | 1.63.156 Chromium: 122.0.6261.43 (Official Build) (64-bit)
--- | ---
Revision | afb5d4402861ae4a1eb59c939832a4d27e1ed8df
OS | Android 14; Build/AP11.231215.009; 34; REL
```

Using the STR/information provided via https://github.com/brave/brave-browser/issues/36074#issue-2134768072, went through the following and that the correct context was being used in different cases:

*`Note:`* the following cases assumes that you've already went through onboarding and clicked on `I understand`

### `Test Case #1`

* launch `1.65.2 Chromium: 122.0.6261.43` and open any website within a new tab
* tap on the `omnibox` and type `brave browser` and click on the `Leo` suggestion
* ensure that `Leo` opens the current context is `brave browser` and not the website that you have opened

### `Test Case #2`

* launch `1.65.2 Chromium: 122.0.6261.43` and open any website within a new tab
* tap in `Hamburger Menu` -> `Leo` and then close it once it appears
* tap on the `omnibox` and type `brave browser` and click on the `Leo` suggestion
* ensure that `Leo` opens the current context is `brave browser` and not the website that you have opened

### `Test Case #3`

* launch `1.65.2 Chromium: 122.0.6261.43` and open any website within a new tab
* tap in `Hamburger Menu` -> `Leo` and tab on either `Suggestions` or `Summarize`
* tap on the `omnibox` and type `brave browser` and click on the `Leo` suggestion
* ensure that `Leo` opens the current context is `brave browser` and not the website that you have opened
