### ISSUE TITLE
Menu panel should align with Wallet panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36072]
## Description 
Menu panel should align with Wallet panel

## Steps to reproduce 

   1. Create/restore wallet
   2. Open wallet menu
   3. Menu panel and wallet panel are not properly aligned

## Actual result 
![image](https://github.com/brave/brave-browser/assets/17010094/0f29e897-93e7-4b6c-8dbe-25b364ac6055)

## Expected result
Both should be properly aligned

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 14
   
## Brave version
1.64.71

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information
cc: @Douglashdaniel @simoarpe

**Comment by simoarpe** [comment]
Even if it may not appear an elegant solution, this is how Android stacks menu views. 
The menu view correctly follows the Android behavior aligning the right side with the main window and the top side is anchored to the overflow item (the three dots).
If we want to customize the behaviour we can extend the menu view and implement a new positioning logic, but I highly recommend to leave this as is, it does not worth the effort in my opinion.

@srirambv I'm closing this, but feel free to reopen if you want to discuss possible solutions.
