### ISSUE TITLE
Issue with Gatsby.js website : Brave browser blocks chunks with analytics/google-analytics in their name

### ISSUE THREAD

**Issue by drobinhood** [brave/brave-browser#3607]
## Description 
Won't open this webpage if guard is enabled: https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/?=google%20analytics

Seems to be an issue with how Brave handles chunks of data that reference google analytics in the body.

## Steps to Reproduce
1. Enable guard in Brave browser
2. Browse to https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/?=google%20analytics

## Actual result:
Page doesn't load. Brave opens a new tab with "data:text/plain," in the url bar.

## Expected result:
Page should load.

## Reproduces how often: 
Every time the tracker guard is enabled.

## Brave version (brave://version info)
Version 0.60.48 Chromium: 72.0.3626.121 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Not 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information
See issue on Gatsby.js repository here: https://github.com/gatsbyjs/gatsby/issues/12361

**Comment by rebron** [comment]
@drobinhood Do you know if this can this be reproduced in Chrome + uBlock?

**Comment by ryanbr** [comment]
Has now been resolved upstream in Easyprivacy.
https://github.com/easylist/easylist/commit/a3e29480f95cdc7455431e7beaa2d22b358d2a30
