### ISSUE TITLE
Automatically fill in one-time verification code

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#36082]
## Description: 
https://support.apple.com/guide/iphone/automatically-fill-in-verification-codes-ipha6173c19f/ios

Safari and other browsers support automatically fill in one-time verification code. Can we add it to Brave please?

**Comment by kylehickinson** [comment]
Brave does support this already via the keyboard but only on the Release/App Store version as that is the build with the default web browser entitlement.
![IMG_768400C702A0-1](https://github.com/brave/brave-browser/assets/529104/ffb04f1b-3382-41f5-ad0d-7402f968cf52)
