### ISSUE TITLE
`Leo's` response-feedback/copy context menu isn't invoked on long-press/long-tap

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#36089]
## Description 

(Found while testing https://github.com/brave/brave-browser/issues/35587 for uplift.)

`Leo's` response-feedback/copy context menu isn't invoked on long-press/long-tap

## Steps to reproduce 

1. install `1.64.72`
2. launch Brave
3. load `abcnews.com` (or any webpage)
4. tap on the vertical 3-dots menu
5. tap on `Leo`
6. opt-in to `Leo`
7. tap `Summarize this page`
8. wait for the generated response
9. long-tap/long-press 
 
## Actual result 

Nothing happens

https://github.com/brave/brave-browser/assets/387249/3851091f-03d8-4218-88ce-bfbb46acbd15

## Expected result

You should see a context menu invoked, like the following from Figma:

![image (1)](https://github.com/brave/brave-browser/assets/387249/bfb851ed-8a6e-4ec6-ac67-8b57bda6910b)

## Issue reproduces how often 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No`
- Can you reproduce this issue with the current Play Store Beta version? `No`
- Can you reproduce this issue with the current Play Store Nightly version? `No`

## Device details
   - Install type (ARM, x86): `ARM64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL`
   - Android version: `9.0`
   
## Brave version

```
Brave	1.64.72 Chromium: 122.0.6261.29 (Official Build) canary (64-bit)
Revision	f2269310f9081d98f47dec5428c59f087de0814e
OS	Android 9; Build/PQ2A.190305.002; 28; REL
```

cc @bbondy @mattmcalister @SergeyZhukovsky @nullhook @brave/qa-team

**Comment by stephendonner** [comment]
Also cc: @aguscruiz for good measure 👍

**Comment by kjozwiak** [comment]
The above requires `1.63.156` or higher for `1.63.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.63.156
Chromium: 122.0.6261.43 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-browser/issues/36089#issue-2135219013

**ACTUAL RESULTS:**
- Verified that the overflow `3-dot` button is not shown anymore next to the Leo's answer
- Verified that `tap and hold` on Leo's answer is opening a context menu with `Copy`, `Like answer` and `Dislike answer` options
- Verified that `tap and hold` on the question part is not opening a context menu
- Verified that `Copy`, `Like answer` and `Dislike answer` are working as expected

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/8677a8e2-c8e4-40ac-b03b-118073bd20ae) | ![2](https://github.com/brave/brave-browser/assets/128532965/689b0ec0-24f4-4c1b-bf15-37caa2c690e1) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/f6de89ba-bafa-4cc5-a428-17b892925049) | ![2](https://github.com/brave/brave-browser/assets/128532965/ce88f9f5-e7db-4b31-aaae-5a2c587e6219) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/833375b4-30e0-407d-a942-af1e3e7bfa3a) | ![2](https://github.com/brave/brave-browser/assets/128532965/c06fac60-6baa-4bbc-9134-853c37dc0e64) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/6101aea4-7693-4ad5-9164-7b33c9119b9a) | ![2](https://github.com/brave/brave-browser/assets/128532965/332b4239-b4de-4282-80ba-d6a2ffae216f) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/41afeeac-940e-4946-89df-37ca5848628b) | ![2](https://github.com/brave/brave-browser/assets/128532965/204a7b03-221a-48ef-b10b-a612021a72ff) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/bba7a85a-a3d2-4ea7-be90-b6170fe3bba7) | ![2](https://github.com/brave/brave-browser/assets/128532965/c54dfabd-55d5-4512-86d3-f167b243d944) |

https://github.com/brave/brave-browser/assets/128532965/38f971ff-d11f-4240-ad1c-309c1ca65706
