### ISSUE TITLE
Google doc summary is not rendered with Mixtral model  when not opted in yet

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#36086]
## Description 

It appears this issue is isolated to Mixtral modal whether opted in or not.  Claude Instant & Llama works well.  Also noticed only single page is being summarized though there are multiple pages, but this is expected for now.

## Steps to Reproduce

   1. Installed 1.64.72
   2. launched Brave
   3. logged into account.bravesoftware.com as an existing premium user
   4. clicked Leo icon in the sidebar 
   5. typed `hi` in the prompt and clicked I understand button
   6. opened a google doc in a new tab
   7. opened Leo panel and clicked `Summarize this page` 
   8. click `Suggest questions....`

## Actual result:

Summary failed to render.  Refreshed the page and clicked `Summarize this page..` but still didn't work
Also `Suggest questions` button spins sometimes

Opt-in 
-----
https://github.com/brave/brave-browser/assets/98358127/bfe123ab-ba94-4da1-ad4c-e02fb421504a

Not opt-in
------
https://github.com/brave/brave-browser/assets/98358127/89730712-a839-4dd4-ae4b-c118b67222b4

## Expected result:
Page summary should render.

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.64.72 Chromium: 122.0.6261.29 (Official Build) nightly (64-bit)
-- | --
Revision | f2269310f9081d98f47dec5428c59f087de0814e
OS | Windows 11 Version 23H2 (Build 22631.3155)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@mattmcalister @LorenzoMinto 
cc: @rebron @stephendonner

**Comment by mattmcalister** [comment]
assigning to @LorenzoMinto as the report indicates an issue with the Mixtral seed but it's not 100% clear what's happening.

**Comment by LorenzoMinto** [comment]
@MadhaviSeelam I can't seem to reproduce on Nightly. Have you tried other docs? If not, could you send over the url for this doc? It might be an edge case

**Comment by MadhaviSeelam** [comment]
> @MadhaviSeelam I can't seem to reproduce on Nightly. Have you tried other docs? If not, could you send over the url for this doc? It might be an edge case

@LorenzoMinto verified in latest nightly `1.65.60 Chromium: 122.0.6261.111`.  Still seeing the issue however this time, summary was successful with the initial query with default Mixtral model but subsequent queries of the same document is failing with this model. No issues with Claude instant and Llama models.   Shared Google Drive document with you.  

https://github.com/brave/brave-browser/assets/98358127/b970d826-7ef0-4c76-b5fe-0ca321590992

**Comment by LorenzoMinto** [comment]
<img width="1514" alt="Screenshot 2024-03-11 at 15 41 43" src="https://github.com/brave/brave-browser/assets/13190144/a8cec8c9-a89b-4109-883c-231624cbf92d">
Nightly above and master below. The text in master is correctly parsed as:
```
<page>
Brave Together 2022: FAQ
0
Share
Sign in
File Edit View Tools Help
Request edit access
6
Outline
Headings you add to the document will
appear here.
BRAVE TOGETHER 2022
May 2nd - May 6th
Lisbon, Portugal
...
```
The summary generation fails systematically on master, I can't reproduce it failing on Nightly. The prompts in nightly and master are the same. Which brings me to think it might be due to the `dev` aichat endpoint that is used in custom builds which right now is using a different model (GPTQ-quantized Mixtral vs AWQ-quantized Mixtral as we have in `production`). The generation seems to start but it's halted soon after. @evq could this be the case?

**Comment by stephendonner** [comment]
@MadhaviSeelam can you retest, and do you have a link to the `Brave Together 2022` Google Doc handy?

I tried with another, large Google Doc, using `Mixtral`, and it worked, using

```
Brave | 1.67.92 Chromium: 125.0.6422.76 (Official Build) beta (x86_64)
-- | --
Revision | d751d2edf40b466560aaeecc4c4919041f41c20d
OS | macOS Version 11.7.10 (Build 20G1427)
```

<img width="1312" alt="Screen Shot 2024-05-29 at 11 13 48 AM" src="https://github.com/brave/brave-browser/assets/387249/a3d6de44-8483-4f93-8520-af025fbfc95f">

I'll also recheck w/Premium.

**Comment by stephendonner** [comment]
`Premium` w/`Mixtral` looks good, too.

example | example | example | example
---------|----------|----------|--------
<img width="1312" alt="Screen Shot 2024-05-29 at 11 20 05 AM" src="https://github.com/brave/brave-browser/assets/387249/b7c2c1dc-ab36-4812-af7f-f8c6bafdb593"> | <img width="1312" alt="Screen Shot 2024-05-29 at 11 20 09 AM" src="https://github.com/brave/brave-browser/assets/387249/8205bb4c-27ff-4407-ab53-1983c3ed2959"> | <img width="1312" alt="Screen Shot 2024-05-29 at 11 20 12 AM" src="https://github.com/brave/brave-browser/assets/387249/14d4723d-9423-447e-95e1-b01c9e588bc7"> | <img width="1312" alt="Screen Shot 2024-05-29 at 11 20 35 AM" src="https://github.com/brave/brave-browser/assets/387249/3d0b4d70-8399-49dc-8c58-ba66b146affd">

**Comment by MadhaviSeelam** [comment]
Can no longer reproduce this issue with Mixtral model.  Working as expected
```
Brave | 1.66.113 Chromium: 125.0.6422.76 (Official Build) (64-bit)
-- | --
Revision | b1864a9a0152d4f1631121c6b13a7426f50cf336
OS | Windows 11 Version 23H2 (Build 22631.3672)
```
Non premium | Premium
------ | ------
![image](https://github.com/brave/brave-browser/assets/98358127/f70a9d41-6f8a-4da5-bc02-936335e51739)|![image](https://github.com/brave/brave-browser/assets/98358127/83094635-d003-4ee4-88c7-7c1e2bf5b8e8)
