### ISSUE TITLE
Network selection has a flickering effect when switching network

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36081]
## Description 
Network selection has a flickering effect when switching network

## Steps to reproduce 

   1. Create wallet 
   2. Open panel
   3. Change networks, has a stuttering effect when selecting networks

## Actual result 

https://github.com/brave/brave-browser/assets/17010094/d825bd48-e00e-47fb-a9cc-965515968a2b

## Expected result
Should not flicker or jank when selecting networks

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 14
   
## Brave version
1.64.71

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information
cc: @Douglashdaniel @simoarpe

**Comment by KoushikBaagh** [comment]
Hello, @srirambv 
I am Koushik, a potential open source contributor.
I am eager in solving this issue.
I have been reviewing the codebase for several days. 
Can you provide guidance on locating the **relevant files** associated with this issue to expedite the process? Your assistance would be greatly appreciated.
