### ISSUE TITLE
Unrelated response returned after Opt-in in a new tab when initial incorrect response returned without opt-in

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#36099]
## Description 

In continuation with https://github.com/brave/brave-browser/issues/36016, verified this issue as an existing premium user, after initial PDF summarization failed as not opt-in user for Leo, and after opting in from subscription page and ran the PDF query in a new tab, the summary still failed, and a new unrelated response returned.

## Steps to Reproduce

   1. Installed 1.64.72
   2. launch Brave
   3. log into account.bravesoftware.com as an existing user 
   4. visit https://basicattentiontoken.org/static-assets/documents/BasicAttentionTokenWhitePaper-4.pdf
   5. open Leo and click `Summarize this page`
   6. click `I understand` 
   7. no response returned with default `Mixtral` model
   8. close the tab in step 4
   9. reload the PDF page step 4
   10. open Leo and clicked `Summarize this page`
   11. incorrect response returned (Issue #36016)
   12. return to the tab in step 3
   13. enter a string (`hi`) in the prompt
   14. click `I understand`
   15. open a new tab and load PDF page from step 4 
   16. open Leo and click `Summarize this page`
   

## Actual result:

New unrelated response returned

https://github.com/brave/brave-browser/assets/98358127/6117c7dc-4b2d-4243-914f-63a8e893b378

## Expected result:
Correct response should be returned 

## Reproduces how often: 

Easily 

## Brave version (brave://version info)

```
Brave | 1.64.72 Chromium: 122.0.6261.29 (Official Build) nightly (64-bit)
-- | --
Revision | f2269310f9081d98f47dec5428c59f087de0814e
OS | Windows 11 Version 23H2 (Build 22631.3155)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@mattmcalister @LorenzoMinto 
cc: @rebron @stephendonner

**Comment by kjozwiak** [comment]
The above requires `1.63.157` or higher for `1.63.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.63.157 Chromium: 122.0.6261.43 (Official Build) (64-bit)
-- | --
Revision | 5fbb7c60cc44e15a910a39a349e632f1b904c58e
OS | Windows 10 Version 22H2 (Build 19045.4046)
```

Verified the issue using original STR from https://github.com/brave/brave-browser/issues/36099#issue-2135266975

Confirmed multi page PDF document is summarized and suggest questions returned responses.

example | example | example | example | example 
----- | ------ | ----- | ----- | ------
![image](https://github.com/brave/brave-browser/assets/38657976/24be4dde-4c97-4057-8eca-46acac6f2d70) | ![image](https://github.com/brave/brave-browser/assets/38657976/b4646fce-0033-4f79-a49e-40b8c8cc0790) | ![image](https://github.com/brave/brave-browser/assets/38657976/75d63ea3-84c7-41bb-a780-c64eb55c561b) | ![image](https://github.com/brave/brave-browser/assets/38657976/9060ffd6-52e3-4f4c-8a27-b498526af95c) | ![image](https://github.com/brave/brave-browser/assets/38657976/446e9e30-0d9b-4219-9e6a-75b1537fa8f1)
