### ISSUE TITLE
[iOS] Update the text for p3a and usage settings

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-browser#36097]
Related to: https://github.com/brave/brave-browser/issues/35871

Update the P3A text in settings to

Allow privacy-preserving product analytics (P3A)
These private responses help Brave estimate the overall usage of certain
features and make them better for you.

Automatically send daily usage ping to Brave
This private ping lets Brave estimate active users.

Reference: https://github.com/brave/brave-ios/issues/8757

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPhone 8 - version 16.7.5` running `Brave Beta version 1.65.80`

Confirmed text changes match the Expected Result mentioned in https://github.com/brave/brave-browser/issues/36097#issue-2135248110
![IMG_4302](https://github.com/brave/brave-browser/assets/38657976/7d96a02a-6c91-41fc-86fc-ed683b85a5aa)
