### ISSUE TITLE
Portfolio Fiat Balance Loads Continuously for Zero Balance Wallets

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#36090]
## Description 

The Portfolio `Fiat Balance` loads continuously for `Zero` balance wallets

## Steps to Reproduce

   1. Create a fresh `Profile` and then setup a new `Wallet`
   2. The Portfolio `Fiat Balance` loads continuously

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/d85385fc-118a-42f4-93b7-ec62caeed907

## Expected result:
Should show a `$0.00` balance

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | 2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from [brave/brave-core#22073](https://github.com/brave/brave-core/pull/22073)
- Verified Portfolio fiat balance loads for zero balance wallet 
- Verified on both wallet page and panel

https://github.com/brave/brave-browser/assets/17010094/da9d39ea-05ca-4a1b-ad92-e81faecdd9a8
