### ISSUE TITLE
[iOS] Tab and UI functions should only be accessed on main

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-browser#36096]
### Description: 
- All Tab related functions should only be accessed on the main thread
- Script Injection should use async-await and ensure MainActor isolation to prevent crashes and undefined behaviour

Reference: https://github.com/brave/brave-ios/issues/8762

PR: https://github.com/brave/brave-ios/pull/8763 should be transferred to core

**Comment by kjozwiak** [comment]
Removing from the `1.63.x` milestone. Once the above has been fixed, it will land in `master` and then will need to be uplifted into `1.63.x`. Once it lands in `master` (which is `1.65.x` at this time), the issue will automatically close/move into the `1.65.x` milestone. It will then be moved to the appropriate milestone when uplifted.
