### ISSUE TITLE
Automate the process for Chromium minor bumps

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#3609]
It'd be nice to have a Jenkins job (which might have a chance to fail when run) that would do the process @mkarolin and I have done for doing minor Chromium upgrades.  It would then do a couple PRs automatically.

We'd just run a jenkins job when we seen that Chrome does this. 
We see at least a few of these on each major version so this would be a big time saver.

**Comment by bsclifton** [comment]
Considering this closed! There are some minor improvements we can make, but the majority of the work is automated

Brave employees can see the job details here:
https://github.com/brave/devops/blob/master/jenkins/jobs/chromium-update-minor.yml

**Comment by bbondy** [comment]
w000000t! 🎉
