### ISSUE TITLE
[iOS] Brave is crashing when opening View all version info. while in Landscape mode and then switching to Portrait mode

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-browser#36098]
### Description: 

Follow-up to #8705

### Steps to Reproduce 
1. Install and launch Brave `1.62 (24.2.8.16)`
2. Three-dot menu > Settings
3. Rotate the iPhone to `Landscape` mode
4. About > Tap `Version...` > Tap `View all version info.`
5. Rotate the iPhone to `Portrait` mode > *Observe Brave is crashing*
6. Launch Brave again
7. Repeat Steps 2 - 5 but this time do it in `Portrait` mode and then rotate the device to `Landscape` mode
8. *Observe Brave is freezing and `View all version info.` page is not aligned*

### Actual result: 

Observe 3 issues here when going through the same steps:
1. Brave is crashing when opening `View all version info.` while in `Landscape` mode and then switching to `Portrait` mode.
2. Brave is freezing when opening `View all version info.` while in `Portrait` mode and then switching to `Landscape` mode.
3. `View all version info.` is not properly aligned when opening while in `Portrait` mode and then switching to `Landscape` mode.

*Brave crash*

https://github.com/brave/brave-ios/assets/128532965/348e1cb3-af3c-4603-a31d-cbd20f6369a3

*Brave freeze*

https://github.com/brave/brave-ios/assets/128532965/38e8e1c3-5f47-41f1-8eaf-c8c3e9a57d86

### Expected result:

Brave must not crash or freeze. 

### Reproduces how often: [Easily reproduced, Intermittent Issue]

`Easily reproduced`

### Brave Version: 

```
Brave build: 1.62 (24.2.8.16)
BraveCore: 1.62.158 (121.0.6167.139)
```

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? N/A
- Can you reproduce this issue with the current build from AppStore? N/A

### Device details: 

```
iPhone 14 / iOS 17.4 Beta
```

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

Reference for iOS Issue: https://github.com/brave/brave-ios/issues/8752

**Comment by kjozwiak** [comment]
The above requires `1.64.103` or higher for `1.64.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.4
Brave build: 1.64 (109)
BraveCore: 1.64.109 (123.0.6312.58)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/36098#issue-2135251164
2. *Verify*

**ACTUAL RESULTS:**
- Verified that Brave is not crashing or freezing

---------------------------

https://github.com/brave/brave-browser/assets/128532965/131a8f73-0fce-4f56-8f51-f943103b0ce0
