### ISSUE TITLE
Adapt tor browser context from muon to brave-core

### ISSUE THREAD

**Issue by riastradh-brave** [brave/brave-browser#361]

**Comment by btlechowski** [comment]
Verification passes on

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

Good job! Issues found are filled under feature/tor label
