### ISSUE TITLE
[iOS] Multiple tabs can be shown as active

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#36102]
### Description: 

Dragging an inactive tab makes it active, but sometimes does not reset the previously active tab to show as inactive

### Steps to Reproduce 
  1. Have more than 1 tab open, have tab bar set to always visible
  2. Drag an inactive tab to the end of the tab bar
  3. Observe inactive tab now shows as active, but the old active tab does not update to show as inactive

### Actual result: 

https://user-images.githubusercontent.com/5314553/222179024-e5bee269-26cf-4823-813c-fdf34dbe505b.mov

### Reproduces how often: 

Not 100% of the time but consistent enough to reproduce

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
Removing from the `1.63.x` milestone. Once the above has been fixed, it will land in `master` and then will need to be uplifted into `1.63.x`. Once it lands in `master` (which is `1.65.x` at this time), the issue will automatically close/move into the `1.65.x` milestone. It will then be moved to the appropriate milestone when uplifted.

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6
Brave build: 1.68 (101)
BraveCore: 1.68.101 (126.0.6478.126)
```
---------------------------

**STEPS:**
1. Follow STR/TP from https://github.com/brave/brave-browser/issues/36102#issuecomment-1944827254 and https://github.com/brave/brave-core/pull/23770#issue-2308942864
2. *Verify*

**ACTUAL RESULTS:**
- Verified that multiple tabs can't be shown as an `active` tab

---------------------------

https://github.com/brave/brave-browser/assets/128532965/0150ed84-f25d-41b0-afc1-33edeed38cd5
