### ISSUE TITLE
Brave Rewards Panel include in a-c switch is not updated after restoring the site through rewards settings page

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3610]
Follow up to https://github.com/brave/brave-browser/issues/3480

## Steps to Reproduce

   1. Enable Rewards
   2. Open `duckduckgo.com` and add it to a-c table
   3. Open `brave://rewards/` in another window (place the windows side by side)
   4. Show the Brave Rewards Panel on `duckduckgo.com`
   5. Exclude `duckduckgo.com` from a-c through `brave://rewards/`
   6. Restore `duckduckgo.com` to a-c through `brave://rewards/`
   7. Restore `duckduckgo.com` to a-c through Brave Rewards Panel

## Actual result:

After step 6: Brave Rewards Panel is not updated.
After step 7: The excluded count is corrupted

![brave_panel](https://user-images.githubusercontent.com/34715963/53917515-074ef380-4065-11e9-9956-ab9216c6aad8.gif)

## Expected result:
Brave Rewards Panel is updated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.61.47 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

cc @brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
closing this as dupe as it was fixed in 0.63 with https://github.com/brave/brave-browser/issues/3497
