### ISSUE TITLE
Bloomberg Live tv doesn't play with shields up

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#3611]
## Description 
https://www.bloomberg.com/live
Videos don't play with shields up. 

(Autoplay block notification also shows but doesn't affect playing videos. Videos not working because of autoplay may be intermittent and dependent on whether ads are inserted, in which case videos won't play).

## Steps to Reproduce

   1. Go to https://www.bloomberg.com/live
   2. Click play icon
   3. Notice video doesn't play.

## Expected result:
Videos play without turning shields off.

## Brave version (brave://version info)
0.60.48 Chromium: 72.0.3626.121

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
Yes.

**Comment by mrzealot** [comment]
This is due to the blocking of Google's IMA script (again), allowing ads solves it in the meantime. It also manifests an autoplay refusal when the video does manage to load, which might merit a manual exception.

**Comment by rebron** [comment]
This looks fixed in 0.61.51. Videos play with shields up.

**Comment by bsclifton** [comment]
@mrzealot can you confirm? If it looks good, let's close it up 😄

**Comment by kjozwiak** [comment]
> This looks fixed in 0.61.51. Videos play with shields up.

Yup, seeing the same thing. Used the following build on both `macOS 10.14.3 x64` and `Windows 10 x64` and the video played with default shields:

Brave | 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}

**Comment by rebron** [comment]
Closing.
