### ISSUE TITLE
input field being covered when decreasing `Leo` from full screen while OSK visible

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#36114]
## Description 

When tapping on the input field, `Leo` will move all the content to the top and displays the OSK. However, if you minimize/drag `Leo` to half size while the OSK is still visible, it will cover the input field making it impossible to use in this state.

## Steps to reproduce 

   1. download/install `1.65.1 Chromium: 122.0.6261.29`
   2. once installed, visit any website and launch `Leo` via the `Hamburger` settings menu.
   3. tap on the input field and you'll notice that `Leo` will go into full screen mode and display the OSK
   4. drag `Leo` so it goes into half screen mode and you'll notice that the OSK covers the input field making it hard to use

## Actual result 

https://github.com/brave/brave-browser/assets/2602313/16da40c5-f61a-4f0f-8e7e-2e8b97eb03ed

https://github.com/brave/brave-browser/assets/2602313/c53d7b2f-7a96-4159-a170-d3563eb6e900

## Expected result

When the user drags `Leo` from full screen to the minimized version, the input field should still be displayed while the OSK is visible.

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A`
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 8 Pro`
   - Android version: `Android 14`
   
## Brave version

```
Brave | 1.65.1 Chromium: 122.0.6261.29 (Official Build) canary (64-bit)
--- | ---
Revision | a8e3b45f929c6d6fffcd66d23a9c52a2359f33f7
OS | Android 14; Build/UQ1A.240205.004; 34; REL
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by Uni-verse** [comment]
This issue is no longer reproducible/valid due to changing Leo to be full screen. Chat window is no long draggable due to https://github.com/brave/brave-core/pull/22240

https://github.com/brave/brave-browser/assets/17885425/f83557ef-eb3d-49c1-bf76-73bf2f7492df
