### ISSUE TITLE
Override download danger level flag not working

### ISSUE THREAD

**Issue by onchov** [brave/brave-browser#36111]
## Description 
Warnings are displayed and downloads are blocked even though the Override download danger level flag has been enabled.

## Steps to Reproduce

   1. Set Settings > Security > Safe Browsing to No protection.
   2. Try to download a file that's "not safe". "Unverified download blocked" pops up.
   3. Set chrome://flags/#brave-override-download-danger-level to enabled.

## Actual result:
"Insecure download blocked" pops up.

## Expected result:
No warnings. No blocks. Stop caring. Just download.

## Reproduces how often: 
Easily reproduced.

## Brave version (brave://version info)
Brave	1.62.165 Chromium: 121.0.6167.184 (Official Build) (64-bit) 
Revision	646e9a49ef45084cb2341eb1e9afabc339004a27
OS	Linux
JavaScript	V8 12.1.285.28

**Comment by stephendonner** [comment]
I think this is fixed with https://github.com/brave/brave-browser/issues/35561?

**Comment by onchov** [comment]
I

> I think this is fixed with #35561?

I saw that issue but didn't notice they were ahead with the version, my bad. Unless this one is closed by the devs, I'll verify and close it when an update comes.
