### ISSUE TITLE
Reddit Redirect Feature Problem

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-browser#36122]
## Description: 

[old.reddit.com](http://old.reddit.com/) redirect feature seems broken.

If you tap a shortened reddit link in 3rd party app, we redirect to either login or create post screen. 

ex. In Slack, tap & hold first link and tap Open in browser (Safari View Controller will redirect to second link, need to open in Brave directly) with the Old Reddit redirect feature enabled:

https://www.reddit.com/r/BurlingtonON/s/vqQEjKLKDm
https://www.reddit.com/r/BurlingtonON/comments/1aq8v6s/looking_for_a_burlington_resident/

## Actual result: 

If you tap a shortened reddit link in 3rd party app, we redirect to either login or create post screen. 

## Expected result:

Redirect properly.

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
Any

### Additional Information

 Thanks for reporting and detailed information @StephenHeaps

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.5
Brave build: 1.66.1 (120)
BraveCore: 1.66.120 (125.0.6422.165)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/22968#issue-2231672367
2. *Verify*

**ACTUAL RESULTS:**
- Verified that pasting a shortened link https://www.reddit.com/r/BurlingtonON/s/vqQEjKLKDm properly redirected to the post when the Reddit `redirect` feature is ON. 

---------------------------

`Reproduced in 1.66.1 (120)`

https://github.com/brave/brave-browser/assets/128532965/93dd8a6b-ff2f-4679-a608-bf831f082f5a

`Verified in 1.67 (108)`

https://github.com/brave/brave-browser/assets/128532965/62b32702-4789-4e7c-ad40-7028563091f7
