### ISSUE TITLE
tapping `Switch to the free model` doesn't do anything (need to tap `Retry`)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#36146]
## Description 

Tapping on `Switch to the free model` doesn't do anything. Once you tap on `Switch to the free model`, you'll instantly see a `Retry` button appear in it's place. Tapping on the `Retry` button correctly switches the user to `LLama 2 13b` as expected.

## Steps to reproduce 

**`Note:`** This assumes that you've already gone through onboarding and have hit the rate limit

   1. once you've reached a rate limit on either `Mixtral` or `Calude Instant`, ensure that the upsell UI is visible
   2. tap on `Switch to the free model` and notice that it will be replayed with a `Retry` button (nothing happens the first time around)
   3. tap on `Retry` and you'll know be switched to `LLama 2 13b`

## Actual result 

https://github.com/brave/brave-browser/assets/2602313/a9117651-f133-4c20-8aba-8924f87a45c1

## Expected result

Tapping on `Switch to the free model` should switch the user to `LLama 2 13b` without the need to tap on `Retry` (unless it failed).

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A` (reproducible with the `1.63.x` RC)
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 14`
   
## Brave version

```
Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
--- | ---
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Android 14; Build/AP11.231215.009; 34; REL
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by stephendonner** [comment]
Also reproduces with the same flow, in desktop build:

```
Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (x86_64)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | macOS Version 14.4 (Build 23E5196e)
```

example | example | example | example
---------|----------|---------|---------
<img width="1312" alt="Screenshot 2024-02-16 at 12 14 05 AM" src="https://github.com/brave/brave-browser/assets/387249/369f4510-0326-45ec-a84a-e24d1e15810a"> | <img width="1312" alt="Screenshot 2024-02-16 at 12 14 22 AM" src="https://github.com/brave/brave-browser/assets/387249/040b7fbf-9b55-418a-ad5e-b3c635ac54f5"> | <img width="1312" alt="Screenshot 2024-02-16 at 12 14 24 AM" src="https://github.com/brave/brave-browser/assets/387249/0b497146-fc13-416f-959f-5451d14afd41"> | <img width="1312" alt="Screenshot 2024-02-16 at 12 14 33 AM" src="https://github.com/brave/brave-browser/assets/387249/683b8ccd-5699-4b3b-aa3c-02388bbeb347">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.65.83 Chromium: 123.0.6312.46 (Official Build) beta (64-bit)
-- | --
Revision | 1ea667c8c59a4a4a327579974ec11149a738e750
OS | Windows 11 Version 23H2 (Build 22631.3296)
```
Reproduced this issue in `1.64.105` in Win 11 x64

1. Installed 1.65.83
2. launched Brave
3. loaded https://www.cnn.com/2024/03/15/economy/nar-realtor-commissions-settlement/index.html
4. summarize the page
5. click I understand
6. query Leo until `Response rate limit reached` message is shown
7. clicked `Switch to the free model`


#### Confirmed Leo switched to `Llama 2 13b by Meta` model
#### Confirmed Llama model summarized the article as expected

step 6| step 7 
------ | -----
![image](https://github.com/brave/brave-browser/assets/98358127/a67021c2-1f64-4efa-ab9d-c8ac0bdef8cb)|![image](https://github.com/brave/brave-browser/assets/98358127/3a72f2e0-feb0-42c2-b1d5-7e6e302a72bc)

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave	1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (x86_64) 
Revision	5d9143e1a0812c53bdc27fd5384591254306a88c
OS	macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.65.96`
2. launched Brave
3. loaded `https://www.cnn.com/2024/03/15/economy/nar-realtor-commissions-settlement/index.html`
4. summarize the page
5. click I understand
6. query Leo until Response rate limit reached message is shown
7. clicked Switch to the free model

### Confirmed Leo switched to Llama 2 13b by Meta model

### Confirmed Llama model summarized the article as expected


example | example | example | example | example | example
---------|----------|---------|----------|---------|---------
<img width="1684" alt="Screen Shot 2024-03-28 at 5 27 51 PM" src="https://github.com/brave/brave-browser/assets/387249/9c794f64-7d81-47ed-b2ca-990776580b0e"> | <img width="1684" alt="Screen Shot 2024-03-28 at 5 27 57 PM" src="https://github.com/brave/brave-browser/assets/387249/5d197e2b-e8bc-4492-9279-675cd604a86a"> | <img width="1684" alt="Screen Shot 2024-03-28 at 5 28 01 PM" src="https://github.com/brave/brave-browser/assets/387249/7ed65cd2-cf69-40b4-8d3d-718881ea3135"> | <img width="1684" alt="Screen Shot 2024-03-28 at 5 28 16 PM" src="https://github.com/brave/brave-browser/assets/387249/f0891911-43f8-4533-baac-1297a232b02f"> | <img width="1684" alt="Screen Shot 2024-03-28 at 5 28 21 PM" src="https://github.com/brave/brave-browser/assets/387249/85595826-a3a4-485c-a15d-9c35bbc858e0"> | <img width="1684" alt="Screen Shot 2024-03-28 at 5 28 54 PM" src="https://github.com/brave/brave-browser/assets/387249/529b561f-6570-48f8-8280-32d3de481312">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
1.65.100
```

**Comment by hffvld** [comment]
## IN PROGRESS...

Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 14 AP21.240305.005 release-keys
Brave build: 1.65.101
Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
```

Filed follow-up issue #
---------------------------

**STEPS:**
1. Launch Brave
2. Go to any website, for example, https://chromeunboxed.com
3. Open `Leo` > Male sure language model is set to `Mixtral` or `Claude`
4. Send some queries until you reach the rate limit
5. Tap `Switch to the free model` > *Verify*

**ACTUAL RESULTS:**
- Verified that tapping `Switch to the free model` immediately switching to the free `Llama 2 13b` language model and running the query

---------------------------

*Pixel 7 / phone*

https://github.com/brave/brave-browser/assets/128532965/533ccf7f-898d-409a-b84e-646394c12aaf
