### ISSUE TITLE
"The installer encountered error 0x80000003" on Windows

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#36147]
Reported by @thypon. In clean Windows 10 / 11 VMs, Brave's installer errors out with the above message.

## Steps to Reproduce

   1. Run Brave's (online or offline) installer.
   2. Accept the UAC prompt to perform a system-wide installation.

## Actual result:

The installer errors out with the message in the title and does not install Brave.

![image](https://github.com/brave/brave-browser/assets/1076393/0d1ce8ba-e97c-41b8-9cd5-4a9a2aeb5c91)

## Expected result:

The installer should succeed.

## Reproduces how often: 

The first time you run a Brave installer in a clean Windows VM. When you re-run the installer, it succeeds.

## Brave version (brave://version info)

1.64.x+

## Version/Channel Information:

- Can you reproduce this issue with the current release? No.
- Can you reproduce this issue with the beta channel? Yes.
- Can you reproduce this issue with the nightly channel? Yes.

## Other Additional Information:

- Is the issue reproducible on the latest version of Chrome? No.

`%LOCALAPPDATA%\Temp\chromium_installer.log` shows:

![image](https://github.com/brave/brave-browser/assets/1076393/d36d94f1-d85b-44ce-8d6f-a4c18f5edef6)

**Comment by kjozwiak** [comment]
The above requires `1.64.91` or higher for `1.64.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.64.97 Chromium: 122.0.6261.111 (Official Build) beta (64-bit) 
Revision	f7c8f13563bfe1063db456650cb43207e1c960c0
OS	Windows 10 Version 22H2 (Build 19045.3803)
```

<details>
<summary>Case 1 - Installed via BraveBrowserBetaSetup.exe - InProgress</summary>

</details>
