### ISSUE TITLE
sometimes `Leo` never loads/appears blank when opening via the `Hamburger Menu`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#36145]
## Description 

Sometimes `Leo` appears completely blank when opening via the `Hamburger Menu` while on a website. I've seen this happen ~3-4 times already but it's not easy to reproduce.

## Steps to reproduce 

**`Note:`** This assumes that you've already gone through onboarding and selected `I understand`

   1. once you've gone through onboarding, visit any website/article
   2. tap on `Hamburger Menu` -> `Leo`

It's not 100% and rare, but sometimes `Leo` will appear completely blank. You'll need to close and re-open `Leo`. Refreshing doesn't fix the issue.

## Actual result 

https://github.com/brave/brave-browser/assets/2602313/3a76c74a-84ed-41c1-9370-2e7c900232f5

## Expected result

Leo shouldn't be appearing completely blank when a user opens/initiates the feature.

## Issue reproduces how often 

As mentioned above, there's really no exact STR/Cases but I've seen this happen a few times already.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A` (but reproduced with the `1.63.x` RC)
- Can you reproduce this issue with the current Play Store Beta version? I'm not 100% as I haven't seen it on `1.64.x`
- Can you reproduce this issue with the current Play Store Nightly version? I'm not 100% as I haven seen it on `1.65.x`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 14`
   
## Brave version

```
Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
--- | ---
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Android 14; Build/AP11.231215.009; 34; REL
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by SergeyZhukovsky** [comment]
@kjozwiak I've never seen that while developed it, opened the panel hundreds of times. It would be cool if we can catch console logs when it happens.

**Comment by SergeyZhukovsky** [comment]
the screen looks very similar to what I see in that issue with protrait/landscape mode https://github.com/brave/brave-browser/issues/36000. The same spinner that we removed a while ago. @AlexeyBarabash fixed it yesterday and it could be that issue is fixed as mostly your device was affected with it.

**Comment by SergeyZhukovsky** [comment]
@kjozwiak I wonder could you still replicate it with the portrait/landscape mode fix and full screen always mode?

**Comment by AlexeyBarabash** [comment]
@wknapik do you have Google Services installed on the device?

**Comment by kjozwiak** [comment]
Going to close the above as I haven't experienced the above for a while now. I'm assuming it was fixed along the way. Perhaps it was related to https://github.com/brave/brave-browser/issues/37146.  I also don't see any ++ for the community so I'm assuming we don't have users running into the above. If I do run into the above again, I'll create a new issue.
