### ISSUE TITLE
Leo not scrolling to button when tapping on `Summarise` when rate limit reached

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#36148]
## Description 

When a user attempts to `Summarise` a page in a new instance but has hit the rate limit, the upsell UI is displayed at the bottom of the chat window but `Leo` doesn't scroll to the bottom which gives the user the impression that nothing has happened. However, once they scroll down, the user will realize that they've hit the rate limit. `Leo` should scroll to the bottom of the screen in this case.

## Steps to reproduce 

**`Note:`** This assumes you've already gone through onboarding and hit the rate limit on one of the premium models.

   1. once you've already hit the rate limit on one of the premium models, load a website/article in a new tab
   2. go into `Hamburger Menu` -> `Leo` and then tap on `Summarise`
   3. you'll notice that nothing happens which gives the impression of something failing/not loading

However, if you scroll down, you'll notice that the rate limit upsell UI was shown but `Leo` never displayed it.

## Actual result 

https://github.com/brave/brave-browser/assets/2602313/795c0638-2106-4d59-a8a2-8112a0f8c220

## Expected result

`Leo` should scroll the bottom to display the rate limit upsell UI. Basically what it does when it summarises a page.

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A` (reproducible with the `1.63.x` RC)
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 14`
   
## Brave version

```
Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
--- | ---
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Android 14; Build/AP11.231215.009; 34; REL
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240305.005 release-keys
Brave build: 1.65.101
Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
```
---------------------------


**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/36148#issue-2137944362
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Leo` UI is now opened in `full screen` mode and automatically scrolls to the `Rate limit` message.

---------------------------

https://github.com/brave/brave-browser/assets/128532965/ddefbefd-9727-49a9-a035-5a090f4130c5
