### ISSUE TITLE
Add Leo right-click quick actions

### ISSUE THREAD

**Issue by LorenzoMinto** [brave/brave-browser#36159]
Spec: https://docs.google.com/document/d/1NsMwFlalPNAv3rzV1siaHCaonbrIbvSua6t-E7fvfKE/edit
Figma: https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?node-id=2240%3A14540&mode=dev
(Note that some things are not in the first phase.)

**Comment by kjozwiak** [comment]
The above requires `1.64.96` or higher for `1.64.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `PASSED` using

```
Brave | 1.64.97 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | f7c8f13563bfe1063db456650cb43207e1c960c0
OS | Windows 10 Version 22H2 (Build 19045.4123)
```

## 1. `Leo AI Tools` context-menu invocations (high-level) - `PENDING`

### Opted-out - `PENDING`
<details>



#### No text highlighted, context-click action

### Steps:
1. installed `1.64.96`
2. launched Brave
3. loaded `skynews.com`
4. context-clicked on an empty region

### Confirmed no `Leo AI Tools` submenu in the invoked context-menu



#### Text highlighted, context-click action

### Steps:
1. installed `1.64.96`
2. launched Brave
3. loaded `skynews.com`
4. selected headline
5. context-clicked on the page
6. chose `Summarize` from the flyout `Brave AI tools >` menu
7. clicked `I understand` in the opened `Leo` pane

### Confirmed `Leo AI Tools` context-menu item appears, with flyout, in the invoked context-menu

example | example
---------|---------


</details>

### Opted-in - `PENDING`
<details>

#### No text highlighted, context-click action

### Steps:
1. installed `1.64.97`
2. launched Brave
3. loaded `example.com`
4. clicked `Summarize this page`
5. clicked `I understand`
6. context-clicked on an empty region

### Confirmed no `Leo AI Tools` submenu in the invoked context-menu



#### Text highlighted, context-click action

example | example
---------|----------



</details>

---

### Shared Steps:
<details>

1. installed `1.64.97`
2. launched Brave
3. loaded various pages (see screenshots in each respective section)
4. selected a portion of the text on the page
5. context-clicked on the page and chose `Leo AI Tools >`
6. chose the respective menu-item entry being tested
8. noted its appropriate output (per menu-item entry) in the `Leo` sidebar

</details>

## 2. Quick actions - `PENDING`
<details>

_**Summarize**_

example | example
----------|----------



_**Explain**_

example | example
----------|----------



</details>

## 3. Rewrite - `PENDING`
<details>

_**Paraphrase**_

example | example
----------|-----------



_**Improve**_ 

example | example
----------|----------



_**Change tone >**_

Academic

example | example
----------|----------




Professional

example | example
----------|----------





Persuasive

example | example
----------|----------



Casual

example | example
----------|----------



Funny

example | example
----------|----------



_**Change length >**_

Shorten

example | example
----------|----------


Expand

example | example
----------|---------



</details>

## 4. Create - `PENDING`
<details>

_**Tagline**_

example | example
----------|----------



_**Social media >**_

Short post

example | example
----------|---------



Long post

example | example
----------|----------



</details>

**Comment by stephendonner** [comment]
## Verification `PENDING` using

```
Brave	1.64.104 Chromium: 123.0.6312.46 (Official Build) (64-bit) 
Revision	0ca3d372cf8aab96fafdd75f5c5c8d2012bc0cc6
OS	Linux
```

## 1. `Leo AI Tools` context-menu invocations (high-level) - `PENDING`

### Opted-out - `PENDING`
<details>



#### No text highlighted, context-click action

### Steps:
1. installed `1.64.104`
2. launched Brave
3. loaded `skynews.com`
4. context-clicked on an empty region

### Confirmed no `Leo AI Tools` submenu in the invoked context-menu



#### Text highlighted, context-click action

### Steps:
1. installed `1.64.9104`
2. launched Brave
3. loaded a `fiercewireless.com` link
4. selected part of the article's body text
5. context-clicked on the page
6. chose `Explain` from the flyout `Brave AI tools >` menu
7. clicked `I understand` in the opened `Leo` pane

### Confirmed `Leo AI Tools` context-menu item appears, with flyout, in the invoked context-menu

example | example | example
----------|-----------|-----------

 


</details>

### Opted-in - `PENDING`
<details>

#### No text highlighted, context-click action

### Steps:
1. installed `1.64.104`
2. launched Brave
3. loaded an `msn.com/news` link
4. clicked `Summarize this page`
5. clicked `I understand`
6. context-clicked on an empty region

### Confirmed no `Leo AI Tools` submenu in the invoked context-menu



#### Text highlighted, context-click action





</details>

---

### Shared Steps:
<details>

1. installed `1.64.104`
2. launched Brave
3. loaded various pages (see screenshots in each respective section)
4. selected a portion of the text on the page
5. context-clicked on the page and chose `Leo AI Tools >`
6. chose the respective menu-item entry being tested
8. noted its appropriate output (per menu-item entry) in the `Leo` sidebar

</details>

## 2. Quick actions - `PENDING`
<details>

_**Summarize**_

example | example
----------|----------




_**Explain**_

example | example
----------|----------




</details>

## 3. Rewrite - `PENDING`
<details>

_**Paraphrase**_

example | example
----------|-----------




_**Improve**_ 

example | example
----------|----------




_**Change tone >**_

Academic

example | example
----------|----------





Professional

example | example
----------|----------






Persuasive

example | example
----------|----------




Casual

example | example
----------|----------




Funny

example | example
----------|----------




_**Change length >**_

Shorten

example | example
----------|----------




Expand

example | example
----------|---------




</details>

## 4. Create - `PENDING`
<details>

_**Tagline**_

example | example
----------|----------




_**Social media >**_

Short post

example | example
----------|---------




Long post

example | example
----------|----------





</details>
