### ISSUE TITLE
go-updater fails to handle single update request for multiple components

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#3615]
## Description 
Go-updater fails to handle single update request with Google and Brave components. We need to handle this so updates to CRLSets are handled correctly.

**Comment by rebron** [comment]
@jumde Is this deployed?

**Comment by jumde** [comment]
@rebron - It should be addressed by: https://github.com/brave/brave-core/pull/1581

Landing soon on master :)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.64.72 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/1581
* Verified test plan from description - MEI Preload, Brave Local Data Updater, Brave Ad Block Updater, Brave Tor Client Updater (OS), CRLSet, PDF Viewer (PDF.js) and Brave HTTPS Everywhere Updater have non-zero version numbers by default
