### ISSUE TITLE
[CR122] `Saved tab groups` sync type verification

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#36155]
## Description 

With CR122 `Saved tab groups` reached stable version. Here are the steps how to verify it works fine in Brave 

#### I. Desktop <=>Desktop
   1. Enable Sync on both devices; enable `Saved tab groups` data type
   
![image](https://github.com/brave/brave-browser/assets/24739341/b00d97c4-e0ae-4ae3-89ed-19b19f014a0e)

   3. On device/browser N1 open urls at new tabs
   https://search.brave.com/search?q=123&source=web
   https://search.brave.com/search?q=456&source=web
each in a new tab
   4. Right click on `123` tab => `Add tab to new group` => type name  and choose color => enable `Save group` switch
![image](https://github.com/brave/brave-browser/assets/24739341/1495c0ba-cff3-4220-9eaf-d6bd4bfe3943)
   5. Go to device/browser N2, open a new tab, you should see you group at the toolbar
   
![image](https://github.com/brave/brave-browser/assets/24739341/7f1b100e-6837-42e1-9e5b-0f0bfcd7fb71)

   7. Click on the group, it should open tabs `123` and `456`

#### II. Desktop <=>Android

Not yet supported by Chromium and Brave

CC @GeetaSarvadnya , @kjozwiak

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 10 Version 22H2 (Build 19045.4046)
```
- Verified the test plan from https://github.com/brave/brave-browser/issues/36155#issue-2138700923

Device 1 | Device 2
----------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/9352cdfc-ad07-4bc1-83c7-6aac003eb324) | ![image](https://github.com/brave/brave-browser/assets/38657976/0ce1f27b-58aa-4a96-85bf-463de28ef75f)
![image](https://github.com/brave/brave-browser/assets/38657976/aed93598-53ff-4835-a299-d1b712cb7cd4) | ![image](https://github.com/brave/brave-browser/assets/38657976/779c042b-481c-4bba-9f85-e6054cf8a684)
