### ISSUE TITLE
Split out supported DDNS domain list from the translation string

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#36164]
Move it out of the translation string so we don't need to re-translate when we add new supported domains.
https://github.com/brave/brave-core/pull/22102#pullrequestreview-1885374373

**Comment by kjozwiak** [comment]
The above requires `1.64.90` or higher for `1.64.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.95 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 6f4193fbcee7c358ae3684f777faa9f12e52206e
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#22299](https://github.com/brave/brave-core/pull/22299)
- Verified DDNS opt-in message is updated to new copy 

https://github.com/brave/brave-browser/assets/17010094/467b0b1c-b445-407a-b8d4-684bf66cbaed

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.63.169 x64 build
- Verified steps from [brave/brave-core#22299](https://github.com/brave/brave-core/pull/22299)
- Verified DDNS opt-in message is updated to new copy 

https://github.com/brave/brave-browser/assets/17010094/5bd51198-14ff-469a-81e6-990fc075b353
