### ISSUE TITLE
Update price rounding to be more accurate, show more decimals

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#36163]
### Description: 

We should handle price formatting more accurately by not restricting to 2 decimal places.

<img src="https://github.com/brave/brave-ios/assets/5314553/6c728822-59c5-4ca8-afd7-d08d4efde217" width="300">

ref: https://bravesoftware.slack.com/archives/C04JJNFRPK7/p1706044166571059

We should do a manual pass on all price displays and align as appropriate.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.5.1 running 1.67 (100)
- Verified steps from [brave/brave-core#23374](https://github.com/brave/brave-core/pull/23374)
- Verified price/fiat display throughout wallet, in Portfolio, Asset Details, Transactions (fiat value + gas fiat value), Accounts
- Verified when Fiat/price values less than 1, shows value more accurately using 3 significant digits
- Verified when Fiat/price values less than 10 (>= 1), shows value with 3 digits after decimal
- Verified when remaining larger values (>= 10), shows value with 2 digits after the decimal matching  existing behaviour

![image](https://github.com/brave/brave-browser/assets/17010094/16d4669b-5c33-487f-a29b-b296b2bf2802) | ![image](https://github.com/brave/brave-browser/assets/17010094/58cdc691-daac-4f32-a899-8c5f63a248c2) | ![image](https://github.com/brave/brave-browser/assets/17010094/4f36631a-3b33-4aa7-872f-be1d0e098238) | ![image](https://github.com/brave/brave-browser/assets/17010094/b530ce68-1c00-45eb-8287-2f91d94eb62b)
-- | -- | -- | --
![image](https://github.com/brave/brave-browser/assets/17010094/6d6b5ef6-0134-4e1d-8e11-c2cf58955f1e) | ![image](https://github.com/brave/brave-browser/assets/17010094/cdc8f0f2-4e9f-42f1-b4ff-06c7186e4970) | ![image](https://github.com/brave/brave-browser/assets/17010094/738c69f1-19cb-493e-afef-b3102dd18f20) | ![image](https://github.com/brave/brave-browser/assets/17010094/aa774038-b023-4f6c-8a6c-9e6476e23886)
