### ISSUE TITLE
CentOS reports missing public signing key

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3617]
## Description 

Previously reported on another issue as well but got closed https://github.com/brave/brave-browser/issues/2506#issuecomment-450567690. CentOS fails to read the signing key 

## Steps to Reproduce

   1. Follow steps from https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux on CentOS
   2. Complains about missing public key
   3. 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/53955723-b9a7aa80-40a7-11e9-9444-3746361e2b71.png)

## Expected result:
No key error

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Release build

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Couple of +1's from https://community.brave.com/t/brave-0-60-45-1-public-key-missing-nokey-on-centos/46352/11

**Comment by rebron** [comment]
cc: @mbacchi can you take a look?

**Comment by mbacchi** [comment]
There was a big discussion in slack about this on Friday. @bkero was going to open a security review and outline the steps that need to be done in order to address this issue.

**Comment by rkraneis** [comment]
Hi guys, anything happening here?This is still happening for brave-browser 0.61.52-1 on Centos 7 :/

**Comment by mbacchi** [comment]
Yes, there is some work going on to determine the best way to work around a Centos bug where it does not support signing with 4096-bit subkeys [1]. cc: @bkero

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1225133#c4

**Comment by fmarier** [comment]
This should be resolved in CentOS 8.

**Comment by fartwhif** [comment]
`warning: /var/cache/dnf/brave-browser-rpm-release.s3.brave.com_x86_64-4b8ac32b87fdc4aa/packages/brave-browser-1.5.122-1.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 82d3dc6c: NOKEY
Public key for brave-browser-1.5.122-1.x86_64.rpm is not installed
Public key for brave-keyring-1.8-1.noarch.rpm is not installed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Error: GPG check FAILED`

it's rearing its ugly head again, boys

**Comment by mbacchi** [comment]
I believe `NOKEY` means you don't have the key that the package was signed with in your rpm database. This shouldn't happen if you also update your `brave-keyring` package at the same time as the `brave-browser` package. We released a new keyring package with an extended key recently so this might be fallout from that.

To import the new key, please run the commands:

```
sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

sudo dnf install brave-browser brave-keyring
```

**Comment by fartwhif** [comment]
I tried that already.  Here are the results.

```
[user@host ~]$ sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
[user@host ~]$ sudo dnf install brave-browser brave-keyring
Last metadata expiration check: 2:48:57 ago on Mon 20 Apr 2020 08:35:56 PM EDT.
Dependencies resolved.
================================================================================
 Package              Arch   Version         Repository                    Size
================================================================================
Installing:
 brave-browser        x86_64 1.7.92-1        brave-browser-rpm-release.s3.brave.com_x86_64
                                                                           72 M
 brave-keyring        noarch 1.8-1           brave-browser-rpm-release.s3.brave.com_x86_64
                                                                           11 k
Installing dependencies:
 libXScrnSaver        x86_64 1.2.3-4.fc31    fedora                        25 k
 libappindicator-gtk3 x86_64 12.10.0-25.fc31 fedora                        43 k
 libdbusmenu          x86_64 16.04.0-14.fc31 fedora                       135 k
 libdbusmenu-gtk3     x86_64 16.04.0-14.fc31 fedora                        41 k
 liberation-fonts     noarch 1:2.00.5-6.fc31 fedora                       8.4 k
 libindicator-gtk3    x86_64 12.10.1-16.fc31 updates                       67 k

Transaction Summary
================================================================================
Install  8 Packages

Total download size: 72 M
Installed size: 73 M
Is this ok [y/N]: y
Downloading Packages:
(1/8): libindicator-gtk3-12.10.1-16.fc31.x86_64 319 kB/s |  67 kB     00:00
(2/8): libXScrnSaver-1.2.3-4.fc31.x86_64.rpm    297 kB/s |  25 kB     00:00
(3/8): libappindicator-gtk3-12.10.0-25.fc31.x86 1.1 MB/s |  43 kB     00:00
(4/8): libdbusmenu-16.04.0-14.fc31.x86_64.rpm   2.9 MB/s | 135 kB     00:00
(5/8): libdbusmenu-gtk3-16.04.0-14.fc31.x86_64. 1.9 MB/s |  41 kB     00:00
(6/8): liberation-fonts-2.00.5-6.fc31.noarch.rp 451 kB/s | 8.4 kB     00:00
(7/8): brave-keyring-1.8-1.noarch.rpm            23 kB/s |  11 kB     00:00
(8/8): brave-browser-1.7.92-1.x86_64.rpm         14 MB/s |  72 MB     00:05
--------------------------------------------------------------------------------
Total                                            13 MB/s |  72 MB     00:05
warning: /var/cache/dnf/brave-browser-rpm-release.s3.brave.com_x86_64-4b8ac32b87                                                                                                                                                             fdc4aa/packages/brave-browser-1.7.92-1.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 82d3dc6c: NOKEY
Public key for brave-browser-1.7.92-1.x86_64.rpm is not installed
Public key for brave-keyring-1.8-1.noarch.rpm is not installed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
[user@host ~]$```

**Comment by fmarier** [comment]
@fartwhif It looks like you might have an old signing key around that's getting in the way. Can you share the output of this:
```
$ sudo rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'
```
On my Fedora31 VM, I get the following:
```
gpg-pubkey-3c3359c4-5c6ae44d	Fedora (31) <fedora-31-primary@fedoraproject.org> public key
gpg-pubkey-c2d4e821-5e7252b8	Brave Software <support@brave.com> public key
```

**Comment by fartwhif** [comment]
```gpg-pubkey-cfc659b9-5b6eac67	gpg(Fedora (30) <fedora-30-primary@fedoraproject.org>)
gpg-pubkey-98ab5139-4bf2d0b0	gpg(Oracle Corporation (VirtualBox archive signing key) <info@virtualbox.org>)
gpg-pubkey-c2d4e821-5d13a788	gpg(Brave Software <support@brave.com>)
gpg-pubkey-f90c0e97-483e8383	gpg(Simone Caronni (slaanesh) <negativo17@gmail.com>)
gpg-pubkey-621e9f35-58adea78	gpg(Docker Release (CE rpm) <docker@docker.com>)
gpg-pubkey-be1229cf-5631588c	gpg(Microsoft (Release signing) <gpgsecurity@microsoft.com>)
gpg-pubkey-3c3359c4-5c6ae44d	Fedora (31) <fedora-31-primary@fedoraproject.org> public key
```

**Comment by fmarier** [comment]
@fartwhif Try deleting the old Brave key first:

    sudo rpm -e gpg-pubkey-c2d4e821-5d13a788

and then reinstall the current Brave key:

    sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

After that, you should be able to see the following key when you run `sudo rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'`:

    gpg-pubkey-c2d4e821-5e7252b8	Brave Software <support@brave.com> public key

**Comment by fartwhif** [comment]
thanks @fmarier  that worked perfectly

**Comment by terminal-root** [comment]
I have removed `brave-browser` and the old key, and I imported the most recent. Though, I am still receiving this output:

```
❯ sudo dnf install brave-browser
...
Public key for brave-keyring-1.13-1.noarch.rpm is not installed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
```

**Comment by fmarier** [comment]
@terminal-root Can you try again? We rolled out a fix two hours ago and we'd like to make sure it's working for you too.
