### ISSUE TITLE
`The page is too long for Leo..` message still shown even after Leo starts to summarize

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#36175]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/35503.  If Leo is asked to summarize a long article, `The page is too long for Leo...` warning message is shown but Leo starts to summarize before user clicks `Got it` button.  Either it should be auto dismissed once Leo starts to summarize or wait for the user to click the button.

## Steps to Reproduce

   1. Install 1.63.156
   2. launch Brave
   3. opened Leo sidepanel
   4. loaded a long article https://en.wikipedia.org/wiki/Sad_Eyed_Lady_of_the_Lowlands 
   5. clicked to summarize this page in the Leo panel
   6. I understand

## Actual result:

`The page is too long for Leo...` warning message is shown and persists even after Leo starts to summarize 

![image](https://github.com/brave/brave-browser/assets/98358127/9f77ee06-8259-4288-961d-63870e0505a6)
## Expected result:
Warning message should be dismissed once Leo starts to summarize?

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.63.156 Chromium: 122.0.6261.43 (Official Build) (64-bit)
-- | --
Revision | afb5d4402861ae4a1eb59c939832a4d27e1ed8df
OS | Windows 11 Version 23H2 (Build 22631.3155)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@mattmcalister @LorenzoMinto 
cc: @rebron @stephendonner

**Comment by bbondy** [comment]
I think the fix here is just a rewording so the message doesn't look like an error. It is meant to only be informational in that it tells the user that the response is based on a truncation of the requested content.

**Comment by LorenzoMinto** [comment]
I think we should also tweak the UI a bit. It's very prominent and it does look like an error (from which you don't assume it will recover). Since we are going through with the truncated request, we should probably just have an information box that says maybe the percentage of the content that was kept, but maybe more subtly. cc @aguscruiz

**Comment by aguscruiz** [comment]
We can probably change it to an info message instead. And change the CTA to "continue" so the user doesn't perceive it as a dead end 

https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Leo-MVP?type=design&node-id=1723%3A33226&mode=design&t=sYVFtLHTRM3dHyy9-1

<img width="1030" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/d5060d49-88b8-4a95-9fb1-c6604ac1e404">

**Comment by LorenzoMinto** [comment]
I think in these situations the request is already sent through, so it will generate the response without further action. Do we really want/need a CTA here or to try to convert the user? I think we could prioritise minimising the visual disruption for the user: have a single line or two saying smth like "The page is too long, Leo will be able to read the first 57%" or "The page is too long, upgrade to premium for longer inputs"

**Comment by aguscruiz** [comment]
Oh ok, so you're saying there will be a response already shown no matter if the context is too long, right? So then a "Continue" button wouldn't be necessary in that case?

**Comment by LorenzoMinto** [comment]
Correct, as it will be truncated and only then passed to Leo.

**Comment by aguscruiz** [comment]
Ok, so this kind of UI would make more sense then 

<img width="1138" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/1965c0db-2495-419e-a9ed-6a6d6dedb59f">

**Comment by aguscruiz** [comment]
Here are the two approaches we can take btw, showing the actual content Leo was stuck on, or just show the percentage.
Which one do you all think we should use? 

@LorenzoMinto @petemill @bbondy 

Reaction 😄 for text
Reaction 🚀 for percentage

<img width="434" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/f09acd34-aa93-41d5-8e7f-650c70c5c316">

---------------------------

Oh and also I think we could use it when Leo starts losing context on a long convo.
<img width="518" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/24cfc6f9-b9c9-43f1-9083-e83610576dec">

**Comment by mattmcalister** [comment]
% seems much better...users will get distracted by seeing the specific line of text.

**Comment by aguscruiz** [comment]
Ok, cool! Left the design here:
https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Leo-MVP?type=design&node-id=1723%3A33226&mode=design&t=rhbkn0g3ojXVeSWj-1

Also for the "conversation is too long", we could reuse the UI
https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Leo-MVP?type=design&node-id=3877%3A20145&mode=design&t=rhbkn0g3ojXVeSWj-1

**Comment by nullhook** [comment]
currently, the truncation limit is hardcoded and identical for both premium and non-premium users. therefore, the variant with CTA doesn't add value at this stage. it would be more appropriate if we had different truncation thresholds for the two user groups. for now, we should implement the variant displaying the percentage to all users. once we establish distinct limits for premium and non-premium users, we can consider gating as a subsequent update.

**Comment by mattmcalister** [comment]
> it would be more appropriate if we had different truncation thresholds for the two user groups with respect to model's context-size.

Agreed. If there's room for a larger context and yet we also need to restrict the size for cost reasons, then we should offer a larger context length for paying users. See https://github.com/brave/brave-browser/issues/33880

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.66.56 Chromium: 123.0.6312.86 (Official Build) nightly (64-bit)
-- | --
Revision | 029ff6b82a6cfb16bde7c6d7ab560321a023cb8b
OS | Windows 10 Version 22H2 (Build 19045.4239)
```

## Followed the steps to reproduce from https://github.com/brave/brave-browser/issues/36175#issue-2139237596

### Confirmed `The page is too long for Leo. Some context could be missing from the conversation. Leo was able to read 34% of the page's contents.` messaging, subtly, below the responded answer.


example | example | example
----------|-----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/36386c21-3afe-4c04-bc11-4e9212b4b55f) | ![image (1)](https://github.com/brave/brave-browser/assets/387249/b0db617e-695c-441d-bff0-1bb7594d779e) | ![image (2)](https://github.com/brave/brave-browser/assets/387249/a1424764-9219-4058-a687-b8de9ac9f195)
