### ISSUE TITLE
Add daily/monthly usage ping P3A metrics for iOS

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#36177]
Please replicate https://github.com/brave/brave-browser/issues/29122. Please uplift to release once complete.

cc @brave/ios

**Comment by anthonypkeane** [comment]
Would it be possible to uplift this to 1.63 @iccub

**Comment by kjozwiak** [comment]
@DJAndries @kylehickinson can we get some STR/Cases added for the above? Or is it the same cases as https://github.com/brave/brave-core/pull/17649#issue-1628500285? If that's the case, lets update the issue/PR to mention what needs to be checked/verified 👍

**Comment by kylehickinson** [comment]
@kjozwiak it should be the same as desktop, the main difference is that iOS isn't implementing the wallet-related usage P3A metrics directly, just `Brave.Core.UsageMonthly` and `Brave.Core.UsageDaily`

**Comment by kjozwiak** [comment]
@DJAndries @kylehickinson do we need to update the `Wiki` with the above? I labelled this as `Done` but I guess that also includes updating the wiki so double checking just in case 👍

**Comment by kjozwiak** [comment]
The above requires `1.63.169` or higher for `1.63.x` verification 👍

**Comment by kylehickinson** [comment]
This currently won't be verifiable on release because access to debug menus is not available there just fyi

**Comment by DJAndries** [comment]
> @DJAndries @kylehickinson do we need to update the `Wiki` with the above? I labelled this as `Done` but I guess that also includes updating the wiki so double checking just in case 👍

updated the wiki :+1:
