### ISSUE TITLE
`Dislike answer` and `Like answer` feedback types should read `Answer disliked` and `Answer liked` after their respective submissions

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#36183]
## Description 

`Dislike answer` and `Like answer` feedback types should read `Answer disliked` and `Answer liked` after their respective submissions

## Steps to Reproduce

1. install `1.65.6`
2. launch Brave
3. load an article or ask any question
4. hover over the generated response
5. click on the `...` 3-dots ellipsis
6. choose `Dislike answer`
7. dismiss the context menu
8. hover and click the `...` again
9. look at the entry for `Dislike answer`

Actual Result - `Dislike answer` | Expected Result - `Answer disliked`
--------------|----------------

<img width="309" alt="Screen Shot 2024-02-16 at 3 26 17 PM" src="https://github.com/brave/brave-browser/assets/387249/77f62a96-5acc-4fd1-b84d-5179e949ad8e"> | <img width="295" alt="Screen Shot 2024-02-16 at 3 24 28 PM" src="https://github.com/brave/brave-browser/assets/387249/31dedd50-5e4a-482d-9792-96dd2419de03">

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.65.6 Chromium: 122.0.6261.43 (Official Build) nightly (x86_64)
-- | --
Revision | 9434ed9324c9af88c51324c06e23730447030643
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@aguscruiz @bbondy @mattmcalister @nullhook @petemill @kjozwiak @MadhaviSeelam @hffvld @Uni-verse

**Comment by nullhook** [comment]
tbh, this feels redundant. the difference in text before and after submission is subtle. the only significant change i observe as a user is the visual alteration in the color of the text on these buttons; they fade out, indicating they have been pressed.

**Comment by mattmcalister** [comment]
agree with @nullhook. seems unnecessary. am going to close as wontfix.
