### ISSUE TITLE
[hackerone] consider allowing <base> elements in speedreader

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#36184]
reported at https://hackerone.com/reports/2376883

we should consider allowing the page's <base> elements to be retained after speedreader distillation, and remove base-uri 'none' from https://github.com/brave/brave-core/blob/564ade0dd3c0077c77975032284c8c8474a6d989/components/speedreader/speedreader_rewriter_service.cc#L49.

**Comment by stephendonner** [comment]
Setting `QA/Blocked`, for now; @boocmp can we please get a testplan for this?  Thanks!

**Comment by boocmp** [comment]
You cay check this one when checking https://github.com/brave/brave-browser/issues/36274 (tags order case).

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.65.87 Chromium: 123.0.6312.46 (Official Build) beta (64-bit)
-- | --
Revision | 2babfcf82ebba4c5dc0146d2ca66229ffd3ac02d
OS | Windows 10 Version 22H2 (Build 19045.4170)
```

### Confirmed both `<base href="...."` and `<base target="..."` are present in the `<head`> tag in `Speedreader` mode

Notes over in https://github.com/brave/brave-browser/issues/36415#issuecomment-2007797422.

**Comment by LaurenWags** [comment]
Per discussion with @diracdeltas, this issue wasn't addressed on iOS. @stoletheminerals would you mind logging a follow up issue (just for iOS) for this issue to be addressed? Thanks!

cc @kjozwiak @Uni-verse @hffvld for iOS visibility.

**Comment by stoletheminerals** [comment]
@LaurenWags https://github.com/brave/brave-browser/issues/36998

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240216.010 release-keys
Brave build: 1.65.96 
Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-browser/issues/36184#issuecomment-1997298436 and https://github.com/brave/brave-core/pull/22369#issue-2158707347
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `<base>` elements are presented in `<head>` when in `Speedreader` mode.

---------------------------

|`Speedreader` is OFF|`Speedreader` is ON|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/5160eaa6-96b2-4099-90a0-2c48c1e2a90e) | ![2](https://github.com/brave/brave-browser/assets/128532965/679948ad-7f3f-4b37-8292-a7b0b525036f) |
</details>

**Comment by hffvld** [comment]
Removing `iOS` tag from this issue as per https://github.com/brave/brave-browser/issues/36184#issuecomment-2013510732 the fix wasn't addressed to `iOS`, and it will be verified in a separate issue https://github.com/brave/brave-browser/issues/36184#issuecomment-2013809058
