### ISSUE TITLE
(Upstream) WASM broken when V8 optimiser disabled by default but allowed on a website 

### ISSUE THREAD

**Issue by flawedworld** [brave/brave-browser#36187]
## Description 

When V8 optimiser is disabled globally, but a site is allowed as an exception to this, WASM is broken, when it should not be.

## Steps to Reproduce

   1. Navigate to https://wasm-feature-detect.surma.technology/
   2. Observe WASM features are detected and work fine
   3. Disable V8 optimiser by default in brave://settings/content/v8
   4. Whitelist https://wasm-feature-detect.surma.technology/ (or another website which uses V8( 
   5. Navigate to https://wasm-feature-detect.surma.technology/ in a fresh tab
   6. Observe WASM are now undetected due to it being broken

## Actual result:

WASM is broken on a whitelisted site allowed to use the V8 optimiser

## Expected result:
WASM works on sites where V8 optimiser has been allowed when V8 optimiser has been disallowed globally by default.

## Reproduces how often: 

100%

## Desktop Brave version:

Brave | 1.63.157 Chromium: 122.0.6261.43 (Official Build) (64-bit)
Revision | 5fbb7c60cc44e15a910a39a349e632f1b904c58e
OS | Windows 11 Version 22H2 (Build 22621.3155)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes, (as above)
- Can you reproduce this issue with the beta channel? Yes

Brave | 1.64.74 Chromium: 122.0.6261.43 (Official Build) beta (64-bit)
Revision | b03db955df4f1c679cb7c2ae8ebfd331d5c29276
OS | Windows 11 Version 22H2 (Build 22621.3155)

- Can you reproduce this issue with the nightly channel? Yes

Brave | 1.65.6 Chromium: 122.0.6261.43 (Official Build) nightly (64-bit)
Revision | 9434ed9324c9af88c51324c06e23730447030643
OS | Windows 11 Version 22H2 (Build 22621.3155)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes, 122.0.6261.39

**Comment by flawedworld** [comment]
I tried to file this upstream but for some reason I keep getting a 403 when I try to login to the issue tracker with my Google account.

**Comment by flawedworld** [comment]
This has been confirmed to be due to Strict Origin Isolation being disabled in Brave by default. It can be manually enabled at chrome://flags/#strict-origin-isolation. I'm closing this as it is not a bug technically. Though it would be nice if Brave enabled this by default. In Vanadium in GrapheneOS, we have had it enabled since January 2022, and it has not caused any impact on users.

**Comment by buawf** [comment]
> This has been confirmed to be due to Strict Origin Isolation being disabled in Brave by default. It can be manually enabled at chrome://flags/#strict-origin-isolation. I'm closing this as it is not a bug technically. Though it would be nice if Brave enabled this by default. In Vanadium in GrapheneOS, we have had it enabled since January 2022, and it has not caused any impact on users.


 Hi,
1.
I see this option under security in brave v1.75.175 (chromium 133.0.o6943.54) - "Manage V8 Security" - shall I keep it enabled or disable it ?

2. 
What is enabled in Vanadium since jan 2022 - V8 or the flag You mentioned ?
