### ISSUE TITLE
Editing an owned NFT gets readded when switching between NFT/Portfolio view

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36197]
## Description 

Editing an owned NFT gets readded when switching between NFT/Portfolio view

## Steps to Reproduce

   1. Add an NFT that you own
   2. Edit the NFT to a different ID that you don't own
   3. Switch focus from NFT tab to Portfolio tab and back to NFT tab
   4. Owned NFT gets added back to the list along with the edited one (unowned) 

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/7507655f-c791-47a4-9141-45534d78b912

## Expected result:
TBD

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam

**Comment by kjozwiak** [comment]
The above requires `1.69.123` or higher for `1.69.x` verification 👍

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/39921#issuecomment-2250172192
