### ISSUE TITLE
Clicking on NFT doesn't load the first time

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36195]
## Description 

Clicking on NFT doesn't load the first time

## Steps to Reproduce

   1. Add an NFT that you don't own 
   2. Click on the NFT after its added to the grid
   3. First click doesn't load the NFT, click again loads the NFT details screen
   4. Edit and NFT that you own and update the ID to one that you don't own
   5. Click on the NFT after its updated
   6. Doesn't load the first time, need to click again for the NFT to open

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/ed2d4d64-9b31-43a7-ae60-befdbf82e975

## Expected result:
Should load the NFT when clicked 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

 
Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)
 
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Not checked
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam @Douglashdaniel

**Comment by josheleonard** [comment]
Closing as no longer valid
