### ISSUE TITLE
Update to Leo's product header

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#36202]
## Description 

**Changes:**

- Font size changes to 19px with 19px line-height (uses a Nala style that needs to be uploaded called `Sidebar product title)`
- The header should have a 60px minimum height. But give the top-bottom paddings a 16px value in case it needs to grow a bit more.
- Product title is always lowercase
- Product name changes to "leo ai"
- Added a "close" icon on the right to close the panel (Desktop and Android)

Design
https://www.figma.com/file/MNwi0uwXNhkAbPiJ86G4vm/%E2%9C%A8-Leo?type=design&node-id=1506%3A7892&mode=design&t=i7noPdyJ4idIyTyS-1

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.67.31 Chromium: 124.0.6367.60 (Official Build) nightly (64-bit)
-- | --
Revision | 5d142aa04ae5b4f6447932c461da4cda17db69d9
OS | Windows 10 Version 22H2 (Build 19045.4291)
```

**Comment by Uni-verse** [comment]
Verified on on `Samsung Galaxy S21` using version: 

```
Brave	1.67.92 Chromium: 125.0.6422.76 (Official Build) beta (64-bit) 
Revision	d751d2edf40b466560aaeecc4c4919041f41c20d
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Ensured that product title is always lower case.
- Ensured badging is correct for free and premium users.
- Ensured tapping on the `X` closes Leo chat and tapping on eraser icon will start new conversation.
- Ensured cog icon will open the Leo main menu.
- Ensured there are no UI or design issues when upgrading from previous versions with Leo already enabled.

Example | Example | Example
-|-|-
![Screenshot 2024-05-24 at 6 02 27 PM](https://github.com/brave/brave-browser/assets/17885425/dc6f318d-5166-4dde-a7c2-67bb8c63eaef) | ![Screenshot 2024-05-24 at 6 02 32 PM](https://github.com/brave/brave-browser/assets/17885425/87eff2f2-b1ff-412a-869d-46d81e1e5886) | ![Screenshot 2024-05-24 at 5 34 26 PM](https://github.com/brave/brave-browser/assets/17885425/f1a55bcd-49b6-4520-afe2-d3c70705a57a)
