### ISSUE TITLE
ech (encrypted client hello) doesnt work

### ISSUE THREAD

**Issue by unpinned** [brave/brave-browser#36205]
## Description 

according to https://github.com/brave/brave-browser/issues/1851 and https://privacytests.org/ brave supports ech but it doesnt work on my desktop and android devices. 

![Screenshot from 2024-02-19 22-58-04](https://github.com/brave/brave-browser/assets/123964038/16318083-dd0e-4d1e-8da3-0ebb2f822bad)

![image](https://github.com/brave/brave-browser/assets/123964038/40df58b1-316f-48e6-a5a7-5d69cd76a466)

## Steps to Reproduce

   1. use android or desktop clients (i use linux)
   2. visit https://tls-ech.dev/
   3. see results

## Actual result:

attached images in description section

## Expected result:

from firefox:
![image](https://github.com/brave/brave-browser/assets/123964038/00dba622-9a75-491b-9f31-f1de7a5cbf8e)

## Reproduces how often: 

always

## Desktop Brave version:

I use Linux:

```1.62.165 Chromium: 121.0.6167.184 (Official Build) unknown (64-bit)```

## Android Device details:
   - Install type (ARM, x86): arm64
   - Device type (Phone, Tablet, Phablet): phone
   - Android version: android 14

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel? HAVENT TRIED
- Can you reproduce this issue with the nightly channel? YES

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? DOUBT (idk if chrome even supports ech yet)

## Miscellaneous Information:

no additional miscellaneous information for now

**Comment by fmarier** [comment]
Could be related to https://issues.chromium.org/issues/41484806

**Comment by unpinned** [comment]
currently it works both on my linux desktop and android mobile. so closing for now

**Comment by alfredonodo** [comment]
Hello,
I tested latest firefox and brave version and ECH is working.
