### ISSUE TITLE
Brave installation makes every other app think I am in Japan

### ISSUE THREAD

**Issue by N1GHTR4NG3R** [brave/brave-browser#36206]
## Description 

Was previously on Windows, and have been using Brave about two weeks prior, I noticed my search results started coming up in Japanese, and small "Micro lag stutters" that are barely noticeable, but happen too often to not notice, especially while gaming.

Someone asked if I was using a VPN, and I haven't been willingly, but decided to have a look around, I noticed Brave had installed their VPN, and switched it on automatically, I turned it off, disabeld it in settings, and closed the processes. However the issue persisted!. 

I had enough and thought perhaps I had been hacked and someone was screwing with me in a strange way, So last night I wiped my OS, and installed Ubuntu 22.04.3 - I removed Firefox and installed Brave, and set it as my default, Checked for the VPN settings but there isn't any in the Ubuntu version. Everything seemed fine until about an hour ago, when my search results are returning back in Japanese again, Steam thinks I am in Japan, Epic Games thinks I am in Japan, My whole system wide applications think I am in Japan!...

Brave has no option to remove a VPN in its settings on Ubuntu, I have been banned from websites I used to visit due to my IP being banned, even though all IP searches show my IP/Country to be right???? - But my applications think I am in Japan?....

My system settings show I am not using a Proxy/VPN - I am the only one in my house with access to my router, All settings on there are normal, What is Brave changing in the background that I cannot see and cannot change, without permission?

## Steps to Reproduce

   1. Install Brave
   2. Wait a day or two max
   3. Results start coming back in Japanese

## Actual result:

![image](https://github.com/brave/brave-browser/assets/36576579/f3e52236-8f81-4956-a6d7-78fc9040484d)
Image Shows Steam giving me warnings about Japanese Interfaces.
Network Settings show no VPN or Proxy
Brave has no VPN Settings to toggle

## Expected result:
Shouldn't be installing stuff or making changes on your system without permission, Thats Malware

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Brave	1.62.165 Chromium: 121.0.6167.184 (Official Build) (64-bit) 
Revision	646e9a49ef45084cb2341eb1e9afabc339004a27
OS	Linux
JavaScript	V8 12.1.285.28
User agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Command Line	/snap/brave/354/opt/brave.com/brave/brave --disable-domain-reliability --enable-dom-distiller --enable-distillability-service --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions --desktop-startup-id=gnome-shell/Brave Web Browser/2070-30-nightranger-desk_TIME19069346
Executable Path	/snap/brave/354/opt/brave.com/brave/brave
Profile Path	/home/nightranger/snap/brave/354/.config/BraveSoftware/Brave-Browser/Default
Active variations	AllowCertainClientHintsStudy:Enabled
BraveAIChatEnabledStudy:Enabled
BraveAdblockMobileNotificationsListDefault:Enabled
BraveAutoTranslateStudy:AutoTranslateDisabled
BraveDebounceStudy:Enabled
BraveFeedUpdateStudy:Enabled
BraveForgetFirstPartyStorage:Enabled
BraveGoogleSignInPermissionStudy:Disabled
BraveHorizontalTabsUpdateEnabledStudy:Enabled
BraveHttpsByDefaultRolloutStudy:Enabled
BraveP3AConstellationEnabled:Enabled
BraveP3ATypicalJSONDeprecationEnabled:Enabled
BraveRewardsWebUiPanelStudy:Enabled
BraveScreenFingerprintingBlockerStudy:Enabled
BraveSearchAdStudy:Enabled
ClampPlatformVersionClientHint:Disabled
CloseWatcher:Disabled_EmergencyKillSwitch
CookieListDefaultStudy:Enabled
Default1pBlockingStudy:Disabled
DisableReduceLanguage:Enabled
EphemeralStorageStudy:Enabled
FirstPartyEphemeralDomainBlockStudy:Enabled
ForceDisableBlinkFeatures:Enabled
PartitionBlinkMemoryCacheStudy:Enabled
PartitionConnectionsByNetworkIsolationKeyStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled
UserActivityStudy:Triggers
WhatsNewStudy:Enabled

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  Not Tried
- Can you reproduce this issue with the nightly channel? Not Tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by bsclifton** [comment]
Apologies for not responding sooner - this issue fell through the cracks ☹️ 

While we do have a VPN product, it's not supported on Linux. We do want to add support - but we haven't done any work yet. Tracked with https://github.com/brave/brave-browser/issues/15817.

If you're on Windows or Linux, you need to actually purchase the product from account.brave.com before you can turn it on.

If you somehow connected to VPN, I can confidently say it wasn't through Brave. Looking at the screenshots provided, I only see the VPN option that's part of Gnome being shown. We hide the UI for VPN in Brave since the code doesn't work there yet.

**Comment by Libertas333** [comment]
I have used Brave for the first time now a little bit over 24 hours or so and can confirm that Japaneese and Korean text gets shown here and there while browsing the internet. Thought it was something specific the first time but now it's becoming stressing how it take over randomly..
Never experienced anything like this and I've tried a bunch of the "safe and free" browsers but after have seen "Brave is nr 1 bla bla bla" for years now I decided that I'd give it a try..
