### ISSUE TITLE
Bitcoin and Zcash mainnets should appear in primary networks list

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#36212]
![image](https://github.com/brave/brave-browser/assets/168356/c7a03955-d401-41a7-b80a-c58bfcfda900)

**Comment by kjozwiak** [comment]
The above requires `1.63.159` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.159 Chromium: 122.0.6261.57 (Official Build) (64-bit)
-- | --
Revision | 118f746822a0acc7abc8c48993a704fcd0e29122
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#22150](https://github.com/brave/brave-core/pull/22150)
- Verified Bitcoin and ZCash mainnet are shown under primary list in profile filter list

https://github.com/brave/brave-browser/assets/17010094/123574d4-2805-4d6d-9d0a-bffc9d58dac9
