### ISSUE TITLE
Registered wireguard service's property is not updated when brave is updated

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#36210]
## Description 

Whenever browser update, registered wireguard service's property should be updated also. But it seems not.
When nightly is updated to `1.65.14`, registered service is still point to executable at `1.65.6` like below.
![image](https://github.com/brave/brave-browser/assets/6786187/96effff6-5a81-4344-a38e-86207188d312)

Also related registry should be updated.
![image](https://github.com/brave/brave-browser/assets/6786187/11131c55-41ef-4df8-b45f-78f86471ea97)

## Steps to Reproduce

   1. Uninstall existing one and install old version brave
   2. Connect VPN with wireguard and check it's ok
   3. Update to latest
   4. Connect VPN with wireguard

## Actual result:

Failed to connect with wireguard

## Expected result:
Connected with wireguard

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes(1.64.x)
- Can you reproduce this issue with the nightly channel? Yes(1.65.x)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

NOTE: `BraveNightlyVpnService` also should have updated path in services' property after brave update.

**Comment by simonhong** [comment]
I think below code could make this regression.
Whenever brave update's registered wireguard service's property should be updated also
because their executable path is changed after update.
But, we don't update if there is registered services from previous brave version
because `XXXServiceInstalled()` only checkes service name.
I think we have to install again at that time.
```
HRESULT Elevator::InstallVPNServices() {
#if BUILDFLAG(ENABLE_BRAVE_VPN)
  if (!brave_vpn::IsBraveVPNHelperServiceInstalled()) {
    auto success = brave_vpn::InstallBraveVPNHelperService();
    if (!success) {
      return E_FAIL;
    }
  }

#if BUILDFLAG(ENABLE_BRAVE_VPN_WIREGUARD)
  if (!brave_vpn::wireguard::IsWireguardServiceInstalled()) {
    auto success = brave_vpn::InstallBraveWireguardService();
    if (!success) {
      return E_FAIL;
    }
  }
#endif
#endif
  return S_OK;
}
```

**Comment by bsclifton** [comment]
Note - this affects the regular DNS service too! We should update both

**Comment by simonhong** [comment]
@mherrmann Need your advice here.
What I'm trying to do is update installed relelase nightly with local build brave_installer.exe.
I did with below step and it seems it seems updated. Can you think it's all good? Thanks :)

1. Install official nightly build with admin mode - Ex, it's 1.65.16
2. Build brave_installer.exe with 1.65.40
3. Run brave_installer.exe --system-level --chrome-sxs

**Comment by mherrmann** [comment]
@simonhong `brave_installer.exe --system-level --chrome-sxs` should be OK. The last time I did it, which was a while ago, I executed:

```
set BraveSoftwareUpdateIsMachine=1
brave_installer.exe --chrome-sxs
```

in an admin prompt. To my knowledge, this should mirror the actual update process most closely. But @bsclifton said it did not work for him without `--system-level`. I think both should be OK.

**Comment by simonhong** [comment]
@mherrmann Ok, thanks! 👍🏼

**Comment by kjozwiak** [comment]
The above requires `1.64.91` or higher for `1.64.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.64.82 Chromium: 122.0.6261.57 (Official Build) beta (64-bit)
-- | --
Revision | 401b7ebe1e71cef068af9879462ee58e55b8a4fd
OS | Windows 11 Version 23H2 (Build 22631.3155)
```

1. Installed 1.65.6
2. launched Brave
3. opened `brave://settings/system` and verified `Use Wireguard protocol in Brave VPN` toggle Off
4. visited account.bravesoftware.com in a new tab
5. entered basic-auth credentials
6. logged into VPN as an existing user `vpn2brave@mailinator.com`
8. clicked `Refresh Brave VPN`
9. connected to VPN via VPN panel
10. confirmed Use WireGuard protocol in Brave VPN toggle is On
11. confirmed wireguard tray icon in the taskbar shows connected status
12. confirmed `BraveVpnBetaWireguardTunnelService` is running in the services
13. upgraded to `1.64.95` via `brave://settings/help`
14. opened settings->Apps->Startup
15. clicked brave_vpn_wireguard_service.exe tab ->open properties from context menu ->Location
16. confirmed registered wireguard service's property in the path shows correct Brave version1.64.95
17. opened Registry Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
18. confirmed registry value shows with correct Brave version
19. uninstalled Brave nightly
20. installed `1.64.95`
21. opened Task Manager -> Services (Win + R)
22. confirmed vpn services (BraveNightlyVpnWireguardService and BraveNightlyVpnService) are not registered
 
step 3|step 9-10 | step11|step 12|step 16|step 17 | step 20 | step 22
----- | ----- | ----- | ----- | ----- | ------ | ----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/0524ed0c-cbb4-4263-9879-32359a036fb8)|![image](https://github.com/brave/brave-browser/assets/98358127/10b05d29-9433-4190-a169-46f38ab177b1)|![image](https://github.com/brave/brave-browser/assets/98358127/0dbb7a80-8e53-4cb5-a829-5785246e85d0)|![image](https://github.com/brave/brave-browser/assets/98358127/686b4d69-bb2e-48d6-b508-3d0c9db11a58)|![image](https://github.com/brave/brave-browser/assets/98358127/b2b70bbf-1ace-45d6-bcc9-d01fb9d0dc6f)|![image](https://github.com/brave/brave-browser/assets/98358127/04b0ed32-7432-4f4c-8002-6283cb0d7593)|![image](https://github.com/brave/brave-browser/assets/98358127/18c38101-bad7-47f5-aae2-68a9f8aa4f42)|![image](https://github.com/brave/brave-browser/assets/98358127/2b5a0e7e-96ee-4775-86f7-1d3309f4f474)

**Comment by MadhaviSeelam** [comment]
@stephendonner for Win 10 verification

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```

```
