### ISSUE TITLE
Rewards need a string for 'BAT'

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#3621]
This is needed for Android change here: https://github.com/brave/brave-ui/pull/411/files#diff-426b14bff01edf742b02d93dd9e5dcf9R72

We do already have this string (https://github.com/brave/brave-core/blob/master/browser/ui/webui/brave_webui_source.cc#L537) but it is under the donate namespace, so we need one to use in Rewards as well

**Comment by btlechowski** [comment]
@ryanml Could you add QA/Yes or QA/No to the issue?
