### ISSUE TITLE
Wallet shows incorrect balances

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#36221]
Regression after https://github.com/brave/brave-core/pull/22110

**Comment by kjozwiak** [comment]
The above requires `1.64.96` or higher for `1.64.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.97 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | f7c8f13563bfe1063db456650cb43207e1c960c0
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#22151](https://github.com/brave/brave-core/pull/22151)
- Verified token balance is shown correctly when swithcing between Portfolio and activity tab
