### ISSUE TITLE
Scriptlet arguments with trailing escaped commas are not parsed correctly

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#36223]
Discovered in the latest Adguard Russian list, the following filter is not working correctly in adblock-rust:

```
pravda.com.ua,epravda.com.ua##+js(remove-node-text, script, \,mr=function(r\,)
```

due to the trailing escaped comma in the last argument `\,mr=function(r\,`.

**Comment by kjozwiak** [comment]
The above requires `1.63.159` or higher for `1.63.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.63.159 Chromium: 122.0.6261.57 (Official Build) (x86_64)
-- | --
Revision | 118f746822a0acc7abc8c48993a704fcd0e29122
OS | macOS Version 13.6.4 (Build 22G513)
```

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.63.159
Chromium: 122.0.6261.57 (Official Build) (64-bit) 
```

---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/22161#issue-2144671576

**ACTUAL RESULTS:**
- Verified that Brave is not crashing when enabled `Adguard Russian` in `brave://settings/shields/filters` and added a custom filter `pravda.com.ua,epravda.com.ua##+js(remove-node-text, script, \,mr=function(r\,)`
- Verified that `pravda.com.ua` and `epravda.com.ua` sites are functional and do not show ads, anti-adblock, unhandled whitespace, etc.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/6962138c-6277-4af3-8c6f-2a16cf9012a0) | ![2](https://github.com/brave/brave-browser/assets/128532965/abe033b0-3c92-4288-9d85-35bad1d76170) | ![3](https://github.com/brave/brave-browser/assets/128532965/d4fc20dd-70f1-4634-88c7-d77e54d0e1f8) | ![4](https://github.com/brave/brave-browser/assets/128532965/762b8476-3ec3-4233-893b-cbcd5a0a8764) |

https://github.com/brave/brave-browser/assets/128532965/c0401137-0dbf-4751-b97e-5d483417a73d
