### ISSUE TITLE
Option to have Vertical Tabs "Expand/Minimize Tabs" toggle button apply only to current window instead of all Brave windows

### ISSUE THREAD

**Issue by richardso21** [brave/brave-browser#36224]
## Description 

I usually have 5+ Brave browser windows, each with ~10 tabs, open concurrently for my workflow. Coming back from Arc (with a similar workflow), I missed how I was able to minimize the vertical tab strip for certain windows, while my other windows would retain the expanded strip. This would be useful if I'm watching something or playing a game in one window and would like to use more screen space without going full screen (fullscreen on macos 🤮), while keeping the rest of my windows and their vertical tab strips the way they are.

It turns out that this also makes the expanding/minimizing animation **lag significantly** (probably because it is applying the change to all the other windows' strips in the background).

I believe having an option in the settings pane to have the toggle button be applied to only the current window instead of globally would be nice to have. This change would also be reflected on the keyboard shortcut, or we can have a separate keyboard shortcut that applies the strip expand/minimize globally. Thank you!

## Steps to Reproduce

   1. Enable Vertical tabs
   2. Have multiple brave windows open
   3. Toggle Expand/Minimize Tabs at top left of the vertical tab strip
   4. See that all other Brave windows were affected as well

## Actual result:

![Screen Recording 2024-02-20 at 10 29 38 AM](https://github.com/brave/brave-browser/assets/49962416/340f9c32-ee66-49b3-a295-68a1a4a9d982)
This is recorded with these 2 windows + another 5 windows running in the background, so about 52 total tabs. There is a noticeable delay between clicking the strip expand/minimize toggle button and the actual change being reflected to the window I am focused on. Realize the window that I don't have focused have the same delay and change.

## Expected result:
![Screen Recording 2024-02-20 at 10 37 47 AM](https://github.com/brave/brave-browser/assets/49962416/82af58a8-70bb-4eac-839c-479bd0ab93b3)
This is recorded when only one window and tab of brave is open. This is what the expanding/minimizing animation should look like.

## Reproduces how often: 

N/A

## Brave version (brave://version info)

1.62.165 Chromium: 121.0.6167.184 (Official Build) (arm64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? YEP
- Can you reproduce this issue with the beta channel? YEP
- Can you reproduce this issue with the nightly channel? YEP

**Comment by rebron** [comment]
@sangwoo108 What do you think on vertical tab strip by Window?

**Comment by rebron** [comment]
Hi @richardso21. Thanks for filing the issue. In general, are you liking our sidebar implementation better or are there other things you'd like to see?

**Comment by robalexj** [comment]
I would also like this feature. I normally have a second Brave window open on my smaller laptop screen; on this I'd like to minimise the tab strip (because the screen size is small), whereas on my main monitor I want it expanded (plenty of space there).

**Comment by sangwoo108** [comment]
Sorry, somehow I missed this. Vertical tab strip expanded per window` makes sense to me because I have two different sized display - one is small and the other is large. So when I expand the vtab for large screen, a window in small display is really hard to use, as page area gets too narrow.

**Comment by Psionyde** [comment]
Bump for this.

I regularly work with.. too many.. windows and tabs open and it is very annoying and frustrating not being able to shrink/hide the vtab bar per-window, both in the missing functionality (which would be very useful for single-purpose-single-tab windows) and the chonky lag when toggling globally.

My ideal scenario would be configurable default behaviour via either vtab settings or ://flags, with a per-window override modifier (perhaps ctrl-click and/or rclick).

Apart from that, wholly positive experience with the vtab implementation. Absolute gamechanger. 9/10 👌

(PS- maybe also a modifier click to swap vtab display side for current window?)

(PPS- any chance of an open tab+window count in the tabsearch "Open tabs" header? I _really_ don't want to know. But also I do.)

**Comment by sangwoo108** [comment]
Hi @Psionyde , Thanks for your suggestion. Could you file new issues for your feature requests?

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.94 Chromium: 128.0.6613.114 (Official Build) beta (64-bit)
-- | --
Revision | 7ee7ec28264896bd8a9aff39cdb9432da38be028
OS | Windows 11 Version 23H2 (Build 22631.4112)
```

1. Installed 1.70.94
2. launched Brave
3. opened brave://settings/Appearance
4. toggled on for `Use vertical tabs` 
5. checked the check box for "Expand vertical tabs per window"  setting
6. opened multiple windows and few tabs
7. toggled `Expand/Minimize tabs` button for one of the windows

#### confirmed vertical tab panel expanded/minimized for the current window 
#### confirmed when "Expand vertical tabs per window" setting was disabled, vertical tab strip for all windows expanded/minimized


https://github.com/user-attachments/assets/8069b0c9-a511-48e0-a5e8-bfbd633e8f93

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.92 Chromium: 128.0.6613.85 (Official Build) beta (arm64)
-- | --
Revision | 711f50838f629ac2be4d1d9592f72adecfd3c928
OS | macOS Version 14.6.1 (Build 23G93)
```

1. Installed 1.70.92
2. launched Brave
3. opened brave://settings/Appearance
4. toggled on for `Use vertical tabs` 
5. checked the check box for "Expand vertical tabs per window"  setting
6. opened multiple windows and few tabs
7. toggled `Expand/Minimize tabs` button for one of the windows

#### confirmed vertical tab panel expanded/minimized for the current window 
#### confirmed when "Expand vertical tabs per window" setting was disabled, vertical tab strip for all windows expanded/minimized


https://github.com/user-attachments/assets/60d9c035-4e5d-449b-87b3-d37389aeab69

**Comment by richardso21** [comment]
Thank you @sangwoo108 for implementing this! Was trying this new feature out, but I encountered a negative side effect: the "Toggle vertical tabs expanded" shortcut does not do anything anymore once you enable "Expand vertical tabs independently per window", yet all the other shortcuts related to (vertical) tabs continue to work. Not sure if this should belong in a new GitHub issue or not.
