### ISSUE TITLE
Autofill Service for Address (Android)

### ISSUE THREAD

**Issue by tapanmodh** [brave/brave-browser#36226]
- Brave should be registered as an Autofill service. 
- Use saved addresses of Brave to autofill address in other applications.
- When you open the other app which has edittext that matches of address then it should give autofill option for saved addresses from Brave app.
- If other app fill the address manually then after finishing that, it should give option to save that address into Brave app.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.65.101 Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
Revision	538d36e197a22168b9bbd79f136891e971c78c60
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured Brave addresses are suggested to autofill on other sites.
- Ensured that addresses can be added/edited in Brave.

_**Add Address in Brave**_

Example | Example | Example
-|-|-
![Screenshot 2024-04-04 at 1 16 38 PM](https://github.com/brave/brave-browser/assets/17885425/7b496f4d-4e5a-45ae-8f59-25e99bf775f5) | ![Screenshot 2024-04-04 at 1 17 28 PM](https://github.com/brave/brave-browser/assets/17885425/6df04f1b-8de8-4061-971e-b36383da13a4) | ![Screenshot 2024-04-04 at 1 17 33 PM](https://github.com/brave/brave-browser/assets/17885425/1d8cf3d1-7133-4d13-8b57-407dd4bca65d)

**_Saved address to autofill in other apps_**

Example | Example
-|-
![Screenshot 2024-04-02 at 11 47 35 AM](https://github.com/brave/brave-browser/assets/17885425/9cfa94cb-c5ae-4b14-a7f9-403f2b7bfc81) | ![Screenshot 2024-04-02 at 11 47 46 AM](https://github.com/brave/brave-browser/assets/17885425/5d9fa145-321a-472b-8e3d-e9b727415b46)
![Screenshot 2024-04-02 at 11 48 59 AM](https://github.com/brave/brave-browser/assets/17885425/b89bc784-177d-4473-9116-c7eb5465670a) | ![Screenshot 2024-04-02 at 11 48 34 AM](https://github.com/brave/brave-browser/assets/17885425/85b39f22-b484-434e-9079-48ae89220863)
