### ISSUE TITLE
Allow totally enabling autoplay

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#3623]
Right now, autoplay can be blocked or allowed one-at-a-time. We should add a state for always allowed — beyond just adding a wildcard entry to the list.

**Comment by pipboy96** [comment]
@tomlowenthal I had a problem of autoplay still getting blocked despite the whitelist unless I launch Chromium with `--autoplay-policy=no-user-gesture-required`. Can this option also make the browser act like this flag is on?

**Comment by karenkliu** [comment]
How about something like this:

![autoplay media](https://user-images.githubusercontent.com/2388823/72947922-7fcfa900-3d38-11ea-9468-ca4a1659adf1.png)

Clicking "don't ask again" will perform that action every time from then on.

**Comment by karenkliu** [comment]
Closing due to new direction with Autoplay minispec https://docs.google.com/document/d/16nicZYs8uf-CLNJc0FrIucwwhzajJ9IL0yUbyCpajBM/edit#
