### ISSUE TITLE
Disable Leo on release channel on Android

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#36234]
We want to disable Leo on release channel to perform more performance testing.

**Comment by kjozwiak** [comment]
The above requires `1.63.159` or higher for `1.63.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.63.159 Chromium: 122.0.6261.57 (Official Build) (64-bit) 
Revision	118f746822a0acc7abc8c48993a704fcd0e29122
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that Leo is not shown in the menu on fresh profile
- Ensured that Leo is not shown in the omnibox
- Ensured that Leo can still be enabled via `brave-ai-chat` flag in `brave://flag`

Example | Example
-|-
![Screenshot 2024-02-21 at 12 26 41 PM](https://github.com/brave/brave-browser/assets/17885425/e1848efb-be55-4bfe-9d68-84df091046c2) | ![Screenshot 2024-02-21 at 12 28 25 PM](https://github.com/brave/brave-browser/assets/17885425/29d4cde9-f59a-4ca5-8ef0-8dfbf9273a69)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using version: 

```
Brave	1.63.161 Chromium: 122.0.6261.57 (Official Build) (64-bit) 
Revision	37b02b4a373f40114e70cc034e491bcc8380f23a
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that Leo is not shown in the menu on fresh profile
- Ensured that Leo is not shown in the omnibox
- Ensured that Leo can still be enabled via `brave-ai-chat` flag in `brave://flags`

Example | Example | Example | Example
-|-|-|-
![Screenshot 2024-02-22 at 11 19 33 AM](https://github.com/brave/brave-browser/assets/17885425/641ddc36-9ea9-4241-a739-c4f66958f3a9) | ![Screenshot 2024-02-22 at 11 19 53 AM](https://github.com/brave/brave-browser/assets/17885425/9763dc88-7529-41f4-9eec-15cf31bda2e5) | ![Screenshot 2024-02-22 at 11 20 43 AM](https://github.com/brave/brave-browser/assets/17885425/00e903c7-9e3e-48a2-8555-cff7c687c40a) | ![Screenshot 2024-02-22 at 11 21 20 AM](https://github.com/brave/brave-browser/assets/17885425/f11538da-3ad6-41a1-991a-3e7467416ede)
