### ISSUE TITLE
Prevent balance lookup failure when rewards provider has no localized name

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#36233]
## Description 

Balances fail to load when using a rewards provider that has not been translated (ie: Solana)

## Steps to Reproduce

   1. create a new profile
   2. enable on-chain rewards

## Actual result:

Balances fail to load. Errors are logged to the console.

## Expected result:
Balance should load without error

## Reproduces how often: 

Easy

## Brave version (brave://version info)

1.61 -> 1.65.17 Chromium: 122.0.6261.43 (Official Build) nightly (arm64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
@josheleonard Do you have a screenshot of this?

**Comment by josheleonard** [comment]
@Miyayes , added a screenshot of the logged error

**Comment by kjozwiak** [comment]
The above requires `1.63.161` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.63.161 Chromium: 122.0.6261.57 (Official Build) (64-bit)
-- | --
Revision | 37b02b4a373f40114e70cc034e491bcc8380f23a
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from issue description
- Verified no console errors when Rewards is linked with self custody wallet 

https://github.com/brave/brave-browser/assets/17010094/59b39465-6181-4e9c-ac73-3dd9c0aa815b
