### ISSUE TITLE
Retry button is redundant in `Response rate limit reached` dialog for Llama 2 13b 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#36235]
## Description 

Found while verifying https://github.com/brave/brave-browser/issues/35503 Once `Response rate limit is reached` dialog is shown after querying with Llama 2 13b, clicking `Retry` button goes into loop showing same dialog.

## Steps to Reproduce

   1. Install 1.63.156
   2. launch Brave
   3. click Leo in the sidebar
   4. select Llama 2 and query until `Response rate limit reached` dialog
    5. click `Retry` button
    
## Actual result:

https://github.com/brave/brave-browser/assets/98358127/553c044d-91f8-4c2f-b9dd-2590851dacd8

## Expected result:
Remove `Retry` button?

## Reproduces how often: 

Easily
## Brave version (brave://version info)

```
Brave | 1.63.156 Chromium: 122.0.6261.43 (Official Build) (64-bit)
-- | --
Revision | afb5d4402861ae4a1eb59c939832a4d27e1ed8df
OS | Windows 11 Version 23H2 (Build 22631.3155)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@nullhook @mattmcalister 
cc: @rebron @stephendonner

**Comment by mattmcalister** [comment]
I think it's supposed to use `Maybe later` instead of `Retry`. https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Leo-MVP?type=design&node-id=3251-39689&mode=design&t=WDs0Ra2TfDkazw9w-0

**Comment by petemill** [comment]
Then the `Maybe later` could just dismiss for the current conversation
