### ISSUE TITLE
Youtube Ads 

### ISSUE THREAD

**Issue by AuracleTech** [brave/brave-browser#36231]
## Steps to Reproduce

   1.  Youtube
   2. Ads
   3. Ruined day

## Actual result:
![image](https://github.com/brave/brave-browser/assets/40531871/6bb5c48c-ed2b-47e2-b410-060a5b8c16c0)

## Expected result:
![image](https://github.com/brave/brave-browser/assets/40531871/98611ebb-fbbc-4738-93e6-4680949c38b1)

## Reproduces how often: 
When I go on youtube

## Brave version (brave://version info)
Latest - v1.62.165 (Feb 14, 2024)

## Version/Channel Information:

- Can you reproduce this issue with the current release? To confirm
- Can you reproduce this issue with the beta channel? To confirm
- Can you reproduce this issue with the nightly channel? To confirm

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? X
- Does the issue resolve itself when disabling Brave Rewards? X
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by Fiksas** [comment]
I encountered same issue

**Comment by ryanbr** [comment]
@AuracleTech @Fiksas has it been resolved?

**Comment by ryanbr** [comment]
Closing the report, was resolved the same day. Re-open if its still an issue
