### ISSUE TITLE
Portfolio Price History is not Loading

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#36239]
## Description 

The Portfolio `Price History` is not loading

## Steps to Reproduce

   1. Unlock your `Wallet` and navigate to the `Portfolio` screen
   2. The `Price History` never loads

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/8e67ba3a-635e-49e8-ba09-53db8aa21b26

## Expected result:
Should load `Price History`

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.97 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | f7c8f13563bfe1063db456650cb43207e1c960c0
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#22183](https://github.com/brave/brave-core/pull/22183)
- Verified Portfolio price history shows the graph correclty
- Verified the graph is shown on asset details screen
- Verified on both wallet portoflio and panel

https://github.com/brave/brave-browser/assets/17010094/ccf6bd2c-dce0-4692-8379-0c23e1ec836b
