### ISSUE TITLE
add personaId, userId, bootStamp to rewards internal page

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3624]
## Description 
While troubleshooting an issue, @NejcZdovc mentioned we should add 
personaId
userId
bootStamp
to the new rewards internal page as this can help with troubleshooting issues.

## Steps to Reproduce

   1. Navigate to rewards internal page
   2. personaId, userId, bootStamp should be listed.
   3. Verify values displayed match what is in ledger_state file.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.65.93 Chromium: 74.0.3729.131 (Official Build) beta (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.523

- Verified the test plan from https://github.com/brave/brave-core/pull/2210

![image](https://user-images.githubusercontent.com/38657976/57779731-50e24b80-7744-11e9-9e0f-25a349a5410f.png)
![image](https://user-images.githubusercontent.com/38657976/57779747-5b9ce080-7744-11e9-8d96-dd432abfbd98.png)
