### ISSUE TITLE
Add "day zero" experiment daily retention P3A metric 

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#36243]
"Day zero" experiments will be performed in the future in an attempt to improve user retention. The experiments will involve small changes in the UI. Add daily retention metrics for measuring the results of the experiment.

If you are included in the day zero experiment, how long ago did you install the browser?
`Brave.DayZero.On.InstallTime`

If you are not included in the day zero experiment, how long ago did you install the browser?
`Brave.DayZero.Off.InstallTime`

Values for the metric range from 0 to 30 days. The refcode will be included with the report.

cc @chrismore @timchilds

**Comment by kjozwiak** [comment]
The above requires `1.65.110` or higher for `1.65.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.65.110 Chromium: 124.0.6367.29 (Official Build) (64-bit)
-- | --
Revision | 6271fdd3c799c0db71c1e6ca8c83888a7bbbfbd2
OS | Windows 10 Version 22H2 (Build 19045.4046)

```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.65.114`

**Comment by GeetaSarvadnya** [comment]
@DJAndries I have verified the test plan from https://github.com/brave/brave-core/pull/22195 and noticed that the metrics `Brave.DayZero.A.InstallTime` isn't shown on the local state file on Android. Steps followed are as below:

1. Clean profile `1.65.114` 
2. Enable developer options 
3. Open QA preferences and enter the flag `--enable-features="BraveDayZeroExperiment:variant/a"` on `Command Line String` field via Developer options->QA preferences
4. Relaunch the browser
5. Open brave://version
6. Ensured that the `StudyBraveDayZeroExperiment:GroupBraveDayZeroExperiment` is shown under `Active Variations` via brave://version
7. Open brave://local-state file
8. Look for the metrics `Brave.DayZero.A.InstallTime`
9. Metrics is not shown
10. Close the browser and set the sys date ahead by 7 days
11. Relaunch the browser 
12. Reload brave://local-state file
13. Look for the metrics `Brave.DayZero.A.InstallTime`
14. Metrics is not shown

cc: @hffvld

**Comment by DJAndries** [comment]
This issue cannot be QA'd effectively on Android, since the feature needs to be enabled upon first run. There is no easy way to do this on Android, currently.
