### ISSUE TITLE
Use the same account from AddUnapprovedTransaction to sign the transaction

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#36240]
## Description 

It used to be that in all cases, selected account is the one that is used to sign all transactions.
But this is not true anymore after we add the ability to add unapproved transactions from other non-selected account in the wallet native UI.

## Steps to Reproduce

   1. Have multiple Solana accounts in the wallet, and made one of them the selected dApp account.
   2. Send Sol from wallet UI, use an account other than the selected dApp account as the sender.

## Actual result:

Transaction failed with `-32003: Transaction signature verification failure`

## Expected result:
Transaction should be successful.

## Reproduces how often: 

every time

**Comment by kjozwiak** [comment]
The above requires `1.63.159` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.63.159 x64 build
- Verified steps from [brave/brave-core#22184](https://github.com/brave/brave-core/pull/22184)
- Verified when a Solana account is connected to dapp, it is listed under `selected_sol_dapp_account` in `brave://prefs-internals`
- Verified able to send SOL from dapp selected account to other account via native send
- Verified able to send SOL from non-connected account to connected account via native send
- Verified `Sign and Send (Legacy)` works with connected account via `https://pwgoom.csb.app`

https://github.com/brave/brave-browser/assets/17010094/87d3cf2b-d149-4137-bc1e-e652564cd82b

-----------------------
Verification passed on

Brave | 1.63.159 Chromium: 122.0.6261.57 (Official Build) (64-bit)
-- | --
Revision | 118f746822a0acc7abc8c48993a704fcd0e29122
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#22184](https://github.com/brave/brave-core/pull/22184)
- Verified when a Solana account is connected to dapp, it is listed under `selected_sol_dapp_account` in `brave://prefs-internals`
- Verified able to send SOL from dapp selected account to other account via native send
- Verified able to send SOL from non-connected account to connected account via native send
- Verified `Sign and Send (Legacy)` works with connected account via `https://pwgoom.csb.app`

https://github.com/brave/brave-browser/assets/17010094/d9aaad8c-73ed-491d-8244-e3d202114411
