### ISSUE TITLE
Experimental adblock filter list for risky rules

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#36244]
We'd like to test out risky filter rules before releasing widely. Even after QA, we can't capture all cases of rule-related breakage, especially on fast-moving and complex websites like YouTube. We currently don't have a way of restricting filter rule rollout by channel i.e. we can't say that a filter rule should only get applied in Nightly or Beta as opposed to Release. 

As a workaround, we could have an experimental/risky adblock list/component that:
1. Would be default on in Nightly and Beta channels
2. Would be default off in Release, but users will be able to easily opt-in via brave://adblock

This way, we can put in risky adblock rules into this list and try them out in Nightly and Beta, and if everything looks good for a while, we can manually copy them over to the respective adblock list/component that would get sent out to all channels.

When putting in rules to the experimental list, we should make sure to tag @brave/qa-team since by definition these are risky rules that might affect QA testing.

Work Plan:
- [x] Create new list https://github.com/brave/adblock-lists/blob/master/brave-lists/experimental.txt with sample rules:. PR: https://github.com/brave/adblock-lists/pull/1553
- [x] Generate new component metadata via https://github.com/brave/adblock-resources/blob/master/generate_component.sh
- [x] Upload generated PEM file to 1P and update Jenkins 
- [x] Add a new entry for non-default-enabled list in https://github.com/brave/adblock-resources/blob/master/filter_lists/list_catalog.json. PR: https://github.com/brave/adblock-resources/pull/152
- [x] Make list default on in Nightly and Beta

**Comment by ryanbr** [comment]
Test filter for youtube; A modification from the previous filter that caused issues. Something worthy to test

`||googlevideo.com/videoplayback*ctier=L&*%2Cctier%2C` from https://github.com/AdguardTeam/AdguardFilters/pull/172976

**Comment by Yuki2718** [comment]
Another set of rules worth testing
```
www.youtube.com##+js(trusted-replace-fetch-response, /"auxiliaryUi":\{"messageRenderers":\{"bkaEnforcementMessageViewModel.*?e\}\}\}\,/, , player?)
www.youtube.com##+js(trusted-replace-fetch-response, /("trackingParam":"kx_fmPxhoPZR)[-_0-9A-Za-z]{150}[-_0-9A-Za-z]+?([-_0-9A-Za-z]{43}BwOcCE59TDtslLKPQ-SS"\})/, $1$2, player?)
www.youtube.com##+js(trusted-replace-xhr-response, /"auxiliaryUi":\{"messageRenderers":\{"bkaEnforcementMessageViewModel.*?e\}\}\}\,/, , player?)
www.youtube.com##+js(trusted-replace-xhr-response, /("trackingParam":"kx_fmPxhoPZR)[-_0-9A-Za-z]{150}[-_0-9A-Za-z]+?([-_0-9A-Za-z]{43}BwOcCE59TDtslLKPQ-SS"\})/, $1$2, player?)
```

Already added to AG by https://github.com/AdguardTeam/AdguardFilters/pull/172178 and we will eventually add to uBlock filters, just unsure whether yt is no more watching us.

**Comment by Yuki2718** [comment]
`||googlevideo.com/videoplayback*ctier=L&*%2Cctier%2C` was added to uBf by https://github.com/uBlockOrigin/uAssets/commit/73a8660e073a3a9ca28d6191df9e038d8561e384 to hopefully mitigate alleged ads slip which we can't figure out yet.

**Comment by ShivanKaul** [comment]
The Experimental list was turned on in Nightly and Beta via Griffin: https://github.com/brave/brave-variations/blob/production/seed/seed.json#L2597, closing this out.
