### ISSUE TITLE
iOS onboarding for Japan

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#36245]
## Description: 
Please implement the spec for onboarding on iOS - Japan only

Search for "Mobile Onboarding - Day 0 Focus (Q1 2024)"

**Comment by anthonypkeane** [comment]
Security Review: https://github.com/brave/reviews/issues/1500

**Comment by Uni-verse** [comment]
Verification in progress on `iPhone 12` running `iOS 17.5.1` using version `1.67 (123)`

**Onboarding Flow**

- Ensured new onboarding is shown for Japan region only.
- Ensured US and France regions do not have the new onboarding flow.
- Ensured that moving slider in the first screen changes the haptic feedback.
- Ensured that tapping `Continue` will advance to the next screen.
- Ensured that tapping `X` in the first two screens will skip to the P3A screen.
- Ensured that tapping `Learn more about our Privacy Preserving Product Analytics (P3A)` will launch the Brave support page.
- Ensured that `Go To System Settings` will launch browser settings. 
- Ensured that onboarding is shown correctly in different aspect ratios / orientations.

Example | Example | Example | Example
-|-|-|-
![IMG_6543](https://github.com/brave/brave-browser/assets/17885425/b93c54be-392e-427d-82a7-0bf9ea8838cc) | ![IMG_6546](https://github.com/brave/brave-browser/assets/17885425/d2c8f60f-95ab-439b-808c-94a3f30a10fc) | ![IMG_6547](https://github.com/brave/brave-browser/assets/17885425/571e649c-1988-4135-913a-80097fd98843) | ![IMG_6551](https://github.com/brave/brave-browser/assets/17885425/76d6b70a-8e2d-438e-a5c7-2b780538cc77)
![IMG_6544](https://github.com/brave/brave-browser/assets/17885425/c25b2a0c-711e-4d85-bc03-f86fb5dccdc5) | ![IMG_6545](https://github.com/brave/brave-browser/assets/17885425/05a2493e-7af2-49df-a9f6-40ecde28427f) | ![IMG_6548](https://github.com/brave/brave-browser/assets/17885425/a954c06f-014b-4eaa-86cb-4b449856f96a) | ![IMG_6550](https://github.com/brave/brave-browser/assets/17885425/71d7ba61-a2ea-4f74-80e7-9cd0191b787e)

Support page | Default browser settings
-|-
![IMG_6549](https://github.com/brave/brave-browser/assets/17885425/4bd000b6-49de-4f95-8cad-e356639c4584) | ![IMG_6552](https://github.com/brave/brave-browser/assets/17885425/c5e0adf6-72d1-4c00-914d-c18422a8872f)

US | Germany
-|-
https://github.com/brave/brave-browser/assets/17885425/cabd1dde-0e04-44bb-b5c8-ed83e1092d8a | https://github.com/brave/brave-browser/assets/17885425/780c4b4f-c954-4e56-a30d-832956484f8d



**Callouts / Pop-ups**

- Ensured that Rewards (11 days) / Default browser (13 days) pop-ups have 3 day delay for Japan region. 

Example | Example
-|-
![IMG_6555](https://github.com/brave/brave-browser/assets/17885425/bd6608f2-08d7-402c-b520-8f508a6d6fbf) | ![IMG_6556](https://github.com/brave/brave-browser/assets/17885425/bc79b1fc-3c01-400e-a8d6-a115e03db3ec)

- Ensured that Rewards / Default browser / VPN pop-ups are shown as expected and not delayed for Non-Japan region. 

Example | Example | Example
-|-|-
![IMG_1470 4](https://github.com/brave/brave-browser/assets/17885425/d50a8f4a-f90f-42af-a886-12b748af8fd6) | ![IMG_1472 3](https://github.com/brave/brave-browser/assets/17885425/56dfebfe-d651-42bf-98ba-27644f70349c) | ![IMG_1473 3](https://github.com/brave/brave-browser/assets/17885425/809eedfd-c97a-445e-93b9-bc0e21c61caa)
