### ISSUE TITLE
Restore from MM extension is broken

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#36256]
MM switched to 600K pbkdf2 iterations 
https://github.com/MetaMask/metamask-extension/pull/21878#discussion_r1404464181
We should support this also

**Comment by kjozwiak** [comment]
The above requires `1.63.164` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.164 Chromium: 122.0.6261.69 (Official Build) (64-bit)
-- | --
Revision | 0a640ded5b59268307d1ae11b74646763cb82b4c
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#22205](https://github.com/brave/brave-core/pull/22205)
- Verified able to import MM wallet to Brave Wallet

https://github.com/brave/brave-browser/assets/17010094/abcd8d00-0822-4b71-9ff2-4e06d12d3e7f
