### ISSUE TITLE
[iOS] [hackerone] Make sure original document security settings apply to Reader Mode

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-browser#36259]
Reader mode sends pre-defined security headers. This may cause security issues if the original page has a stricter policy. 
More details: https://github.com/brave/brave-browser/issues/35797

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.5.1
Brave build: 1.67 (118)
BraveCore: 1.67.118 (126.0.6478.71)
```
---------------------------

**STEPS:**
1. Launch Brave
2. Go to https://js176.gitlab.io/tools/deeplinks/2010/06/encrypt-web-https-everywhere-firefox-extension
3. Three-dot menu > Settings > Appearance
4. Enable Speedreader > *Verify*

**ACTUAL RESULTS:**
- Verified that Speedreader-enabled view rendered, without the image, as per the test plan

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/d0a02c6c-d6ec-4dd4-9d04-4e0ec1795f6e) | ![2](https://github.com/brave/brave-browser/assets/128532965/b0071b2a-008d-453b-aeae-8fbf335f4ca9) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/69d520c2-227a-485e-86cc-3caeae2f5e1f) | ![2](https://github.com/brave/brave-browser/assets/128532965/e4b3541d-e7bf-4315-a99c-a40e65496eea) |
