### ISSUE TITLE
Browser crash when submitting a transaction

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36251]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

### Description:
Browser crash when submitting a transaction

Brave Version: 1.63.157 Chromium: 122.0.6261.43
Operating System: Android 13
Device: Lenovo Tablet 

URL (if applicable) where crash occurred: Submit a send trasnaction

Can you reproduce this crash? No. Happened once

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Restore wallet with balance
2. Submit a Send/Swap transcation
3. Browser crashes before the native transaction panel shows up 

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/0abc1000-bc19-830b-0000-000000000000

**Comment by Douglashdaniel** [comment]
Test with Solana Mainnet

**Comment by iefremov** [comment]
stale
