### ISSUE TITLE
Important data was somehow removed from ledger_state

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#3625]
## Description 
When troubleshooting a reconciliation with @NejcZdovc, we noticed that key fields in my `ledger_state` were missing.

Here is a sanitized version of that file:
```
{
  "walletInfo": {
    "paymentId": "REDACTED",
    "addressBAT": "REDACTED",
    "addressBTC": "REDACTED",
    "addressCARD_ID": "REDACTED",
    "addressETH": "REDACTED",
    "addressLTC": "REDACTED",
    "keyInfoSeed": "REDACTED"
  },
  "bootStamp": 0,
  "reconcileStamp": 1552258981,
  "last_grant_fetch_stamp": 1551991980,
  "personaId": "",
  "userId": "",
  "registrarVK": "",
  "masterUserToken": "",
  "preFlight": "",
  "fee_currency": "BAT",
  "settings": "adFree",
  "fee_amount": 20.0,
  "user_changed_fee": true,
  "days": 30,
  "rewards_enabled": true,
  "auto_contribute": true,
  "transactions": [],
  "ballots": [],
  "ruleset": "",
  "rulesetV2": "",
  "batch": [],
  "current_reconciles": {},
  "walletProperties": {
    "altcurrency": "BAT",
    "probi_": "416581468644777552878",
    "balance": 416.5815,
    "fee_amount": 30.0,
    "rates": {
      "BCH": 0.001396698385236447,
      "BTC": 0.000047099965750162,
      "BTG": 0.014742684061926885,
      "DASH": 0.002221050480130032,
      "ETH": 0.001331723809073765,
      "EUR": 0.1635795120989441,
      "LTC": 0.003230344396394519,
      "USD": 0.18296993380372796,
      "XRP": 0.5826531015000498
    },
    "parameters_choices": [
      20.0,
      30.0,
      50.0,
      85.0,
      100.0
    ],
    "parameters_range": [
      20.0,
      100.0
    ],
    "parameters_days": 30,
    "grants": [
      {
        "altcurrency": "BAT",
        "probi": "35000000000000000000",
        "expiryTime": 1555286400,
        "promotionId": ""
      }
    ]
  }
}
```

Notice that:
- `bootStamp` is 0
- `personaId` is empty
- `userId` is empty

## Steps to Reproduce
Unknown

## Brave version (brave://version info)
0.62.24 (DEV), but I also had the problem in 0.61.48 (BETA)

### Reproducible on current release:
Issue appears to have been specific to my profile... but my Beta profile had the same problem. Steps to reproduce unknown

### Additional Information
This problem can be resolved with the following steps:
1. In broken profile, copy your keywords
2. Create a new profile in a different release channel. For example, Beta
3. On that new profile, enable rewards (which creates a new wallet)
4. Restore wallet using keywords
5. Close all instances of Brave
6. Back up your broken `ledger_state` file (just in case)
7. Copy the working `ledger_state` over the broken `ledger_state`

## Related
See https://github.com/brave/brave-browser/issues/3624

**Comment by NejcZdovc** [comment]
closing as stale
