### ISSUE TITLE
Update Buy Deposit Bridge Button Styles

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#36265]
## Description 

We need to update all the `Buy, Deposit, Bridge` button styles to be squared to match the new designs in figma

## Expected result:

![Screenshot 21](https://github.com/brave/brave-browser/assets/40611140/df35f973-e3d3-425f-9413-258a8cead868)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | 2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from [brave/brave-core#22212](https://github.com/brave/brave-core/pull/22212)
- Verified Buy/Deposit/Bridge button have border radius on token details screen

https://github.com/brave/brave-browser/assets/17010094/e8ff0ba5-aaf8-4eda-bccb-f936e6a0e682
