### ISSUE TITLE
Buy/Send/Swap not opening from Asset Details

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#36266]
## Description: 

Buy, send and swap are not opening for some assets when tapped in Asset Details. The bug seems to occur on any asset with no account balance.

## Steps to Reproduce 
  1. Open Wallet
  2. Scroll Portfolio to find ETH on Optimism.
      - Seems to occur on any asset where user does not have any account balance
  3. Tap 'Buy'
  4. Observe buy does not open
      - Buy/send/swap do not open either
      - Some other assets do open as expected. Needs investigation.

## Actual result: 

https://github.com/brave/brave-browser/assets/5314553/c8a5ae71-652c-4e63-9130-86e3e8f27804

## Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced with ETH on Optimism, not all assets failing to open.

## Brave Version: 

v1.62 App Store

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details:

iPhone 14 Pro iOS 17.3.1

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari? 

### Additional Information

Community report:

**Comment by kjozwiak** [comment]
Closing as the above landed in `master` via https://github.com/brave/brave-core/pull/22229.

**Comment by kjozwiak** [comment]
The above requires `1.63.164` or higher for `1.63.x` verification 👍 @srirambv @StephenHeaps assuming this is a regression hence being uplifted into `1.63.x`? Should we add the `release-notes/include` label?

**Comment by StephenHeaps** [comment]
@kjozwiak yes regression, I think good to include in release notes as it was reported by community.

**Comment by kjozwiak** [comment]
Labelling as `QA/No` & `release-notes/exclude` as per https://github.com/brave/brave-ios/issues/8776#issuecomment-1970041691.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.4 running 1.62.1 (24.2.28.21)
- Verified steps from [brave/brave-core#22229](https://github.com/brave/brave-core/pull/22229)
- Verified Buy/Send/Swap buttons work as expected and loads correct screen when opened from asset details screen

https://github.com/brave/brave-browser/assets/17010094/dc1534a3-ae97-48a6-bb3c-a1511eef1f11
