### ISSUE TITLE
Hide Rewards account if using Solana self-custody for rewards

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#36276]
## Description 

Hide Rewards account if using Solana self-custody for rewards, since the balance will be displayed within the self-custody account

## Steps to Reproduce

   1.  Opt-in to and setup a Solana self-custody rewards profile
   2. open brave wallet
   3. Note how the information is bugged and incorrect (it says ETH on Aurora, etc.). 

## Actual result:

<img width="726" alt="Screenshot 2024-02-21 at 5 10 47 PM" src="https://github.com/brave/brave-browser/assets/30185185/d61860c9-3d1d-49e6-8e46-39bff5a2ddee">

## Expected result:

Hide the account since the balance will be shown in the self-custody wallet account and rewards panel

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
More context: Given this should be resolved for 1.63.x, this is the simplest fix (@Douglashdaniel also concurs).

**Comment by kjozwiak** [comment]
The above requires `1.63.161` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.161 Chromium: 122.0.6261.57 (Official Build) (64-bit)
-- | --
Revision | 37b02b4a373f40114e70cc034e491bcc8380f23a
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from issue description
- Verified custodian Solana account is not shown in Portfolio
![image](https://github.com/brave/brave-browser/assets/17010094/99ff3e02-8029-4b45-9faf-ed9249027567)


Note: The incorrect account/asset is not shown on RC builds before `1.63.161`.
