### ISSUE TITLE
Loading Skeleton Overflows the Asset Group Container

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#36270]
## Description 

The `Loading Skeleton` overflows the `Asset Group Container`

## Steps to Reproduce

   1. Go to the `Portfolio` page and group assets by `Account
   2. Refresh the `Page`
   3. The `Loading Skeleton` overflows the `Asset Group Container`

## Actual result:

![Screenshot 28](https://github.com/brave/brave-browser/assets/40611140/d9705eca-037e-46cd-afc2-49959e53b7db)

## Expected result:

![Screenshot 29](https://github.com/brave/brave-browser/assets/40611140/d06b3cea-52c9-4293-a488-afe099536c85)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | 2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from [ brave/brave-core#22221](https://github.com/brave/brave-core/pull/22221)
- Verified the `Loading Skeleton` doesn't overflow the `Asset Group Container`

https://github.com/brave/brave-browser/assets/17010094/b22f7552-5327-4f4c-9043-13c4ddc67ee7
