### ISSUE TITLE
[hackerone] speedreader base URL follow up

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#36274]
follow-up to https://github.com/brave/brave-browser/issues/36184 to handle an edge case

https://hackerone.com/reports/2384380

**Comment by stephendonner** [comment]
Setting QA/Blocked, for now; @boocmp can we please get a testplan for this? Thanks!

**Comment by boocmp** [comment]
Done

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.65.87 Chromium: 123.0.6312.46 (Official Build) beta (64-bit)
-- | --
Revision | 2babfcf82ebba4c5dc0146d2ca66229ffd3ac02d
OS | Windows 10 Version 22H2 (Build 19045.4170)
```

### Confirmed both `<base href="...."` and `<base target="..."` are present in the `<head`> tag in `Speedreader` mode

Notes over in https://github.com/brave/brave-browser/issues/36415#issuecomment-2007797422.

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s) via https://github.com/brave/brave-browser/issues/36184#issuecomment-2033159183:
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240216.010 release-keys
Brave build: 1.65.96 
Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
```
---------------------------

Verified that the `<base>` elements are presented in `<head>` when in `Speedreader` mode.
