### ISSUE TITLE
Leo's suggested questions' URLs/hyperlinks are listed in markdown format; consider rendering inline

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#36279]
## Description 

URLs/hyperlinks are listed in markdown format; consider rendering inline

Thanks to @MadhaviSeelam for the initial find!

## Steps to Reproduce

1. install
2. launch Brave
3. load `https://www.aqvinfo.com/`
4. open `Leo`
5. click `Suggested questions`
6. click on any/all of the suggested questions
7. look at the resulting text

## Actual result:

`visit their website at [www.americanqueenvoyages.com](http://www.americanqueenvoyages.com).`

<img width="1502" alt="Screen Shot 2024-02-21 at 10 59 18 AM" src="https://github.com/brave/brave-browser/assets/387249/b9727059-21d3-4b45-89d4-36d505d8c44e">

## Expected result:

Clickable (blue?) hyperlink for www.americanqueenvoyages.com (instead of markdown)

## Reproduces how often: 

Intermittently

## Brave version (brave://version info)

```
Brave | 1.65.22 Chromium: 122.0.6261.57 (Official Build) nightly (x86_64)
-- | --
Revision | 65f8e6ca5faa2acddbc7a1fa6b871f3510688554
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

@LorenzoMinto @bbondy @MadhaviSeelam @petemill @mattmcalister

**Comment by mattmcalister** [comment]
changing status to `Not planned` pending security review
