### ISSUE TITLE
whitespace on certain sites - follow up to 36223

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#36282]
## Description 

Found while testing #36223. There is whitespace on `pravda.com.ua` at the top and on some articles.

## Steps to Reproduce

Follow STR from above issue:

- Enable the checkbox for `Adguard Russian` in `brave://settings/shields/filters`
- Add `pravda.com.ua,epravda.com.ua##+js(remove-node-text, script, \,mr=function(r\,)` to the custom filters in `brave://settings/shields/filters` and save
- The browser should not crash
- Navigate to `pravda.com.ua` and `epravda.com.ua`
- The sites should be functional and not show any ads, anti-adblock, unhandled whitespace, etc.

## Actual result:

Whitespace at the top of the main page and on some articles:

Example | Example
-- | --
![Screenshot 2024-02-21 at 10 28 41 AM](https://github.com/brave/brave-browser/assets/28145373/cf5bdffd-00a2-4522-a30e-88e2ca52969a) | ![Screenshot 2024-02-21 at 10 33 29 AM](https://github.com/brave/brave-browser/assets/28145373/1d3180e1-436e-4965-8928-5f7f2ff8fc01)

## Expected result:

No whitespace 

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.63.159

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes, 1.62.x, RC 1.63.x
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @antonok-edm @ryanbr

**Comment by ryanbr** [comment]
Mostly resolved @LaurenWags 

Re-test  again and let me know

**Comment by LaurenWags** [comment]
lgtm @ryanbr - thanks!

```
Brave | 1.73.91 Chromium: 131.0.6778.85 (Official Build) (x86_64)
-- | --
Revision | 35427fa72a008a7e861fa9828e07a0ba2cd46ebd
OS | macOS Version 14.7.1 (Build 23H222)
```

Verified STR from description.
Confirmed no unexpected whitespace on `pravda.com.ua` and `epravda.com.ua`. Spot checked a few articles as well, confirmed no unexpected whitespace observed.

`pravda.com.ua` | `epravda.com.ua`
--- | ---
![Image](https://github.com/user-attachments/assets/73246741-8531-42cc-93eb-caccb2935b3f) | ![Image](https://github.com/user-attachments/assets/f2429bfb-9244-4173-a168-61806115008d)
![Image](https://github.com/user-attachments/assets/8a34808d-0c78-4687-9310-11862e895ab1) | ![Image](https://github.com/user-attachments/assets/3494ca2f-6f5a-4201-88be-e5cfc6eee6c8)
