### ISSUE TITLE
[Follow up to #22109] Brave is crashing when accessing `account.brave.com`/`account.bravesoftware.com` and trying to link existing VPN subscription

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#36280]
## Description 

Follow-up to #22109

## Steps to reproduce 

   1. Launch Brave
   2. Purchase a new VPN subscription
   3. Three-dot menu > Settings > Brave Firewall + VPN > Link VPN subscription
   4. Sign in to `account.brave.com`/`account.bravesoftware.com` > *Observe, Brave is crashing sometimes*
   5. After successful sign in try to link VPN subscription > *Observe Brave is crashing*

## Actual result 

Brave is crashing when accessing `account.brave.com`/`account.bravesoftware.com` and trying to link existing VPN subscription.

https://github.com/brave/brave-browser/assets/128532965/13933d30-61e3-4918-8b07-e409383eb634

https://github.com/brave/brave-browser/assets/128532965/0853dbc7-86c2-4bee-9da0-067366afc607

## Expected result

Brave must not crash. Here is the screencast for Reelase build `1.63.159` in Prod env.

https://github.com/brave/brave-browser/assets/128532965/8d09c3be-e0f1-472d-8e4e-f6452bffb436

## Issue reproduces how often 

`Easily reproduced`

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NO
- Can you reproduce this issue with the current Play Store Beta version? NO
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 7 (phone)
   - Android version: Android 14
   
## Brave version

```
Brave build: 1.65.22 
Chromium: 122.0.6261.57 (Official Build) canary (64-bit) 
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by hffvld** [comment]
Tested again with a new Nightly build, and the issue is not reproducible now.

----------------------

Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.65.26 
Chromium: 122.0.6261.57 (Official Build) canary (64-bit) 
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-browser/issues/36280#issue-2147525931

**ACTUAL RESULTS:**
- Verified that the Brave is not crashing when accessing `account.brave.com` / `account.bravesoftware.com`
- Verified that VPN subscription can be synced successfully

---------------------------

https://github.com/brave/brave-browser/assets/128532965/6ed7bb7c-bf52-484e-807a-86efd9c68634

**Comment by deeppandya** [comment]
Thank you @hffvld
