### ISSUE TITLE
Make Leo chat window full screen always

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#36286]
It seems like partial screen view brings more problems than benefits.

**Comment by kjozwiak** [comment]
The above requires `1.63.164` or higher for `1.63.x` verification 👍

**Comment by Uni-verse** [comment]
Verified `Samsung Galaxy S21` using version:

```
Brave	1.63.164 Chromium: 122.0.6261.69 (Official Build) (64-bit) 
Revision	0a640ded5b59268307d1ae11b74646763cb82b4c
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that Leo window is displayed as full screen when activated on fresh profile.
- Ensured upgrading from release channel build with version 1.63.161 with Leo enabled does not crash. 
- Ensured Leo window height cannot be changed by swiping or dragging the header area.
- Ensured onboarding content is shown when loading Leo.
- Ensured closing Leo works using the system back button.
- Ensured EULA is shown when interacting with Leo, user must accept and tap `I understand`
- Ensured that chat is working after completing onboarding flow.
- Ensured that Leo chat window is full screen using both orientations.

Encountered: https://github.com/brave/brave-browser/issues/36396

Example | Example | Example
-|-|-
![Screenshot 2024-02-27 at 10 59 07 AM](https://github.com/brave/brave-browser/assets/17885425/b6307511-7894-4ecc-bda5-7ecb0f84c1b9) | ![Screenshot 2024-02-27 at 10 59 37 AM](https://github.com/brave/brave-browser/assets/17885425/650033fd-2fb8-401a-a3ec-fcb25e688aee) | ![Screenshot 2024-02-27 at 10 59 46 AM](https://github.com/brave/brave-browser/assets/17885425/6378e489-8a9a-4dc3-a8cb-11742d67d07b)

**Comment by Uni-verse** [comment]
Verified on `Pixel 2 XL` running `Android 8` using version:

```
Brave	1.63.165 Chromium: 122.0.6261.94 (Official Build) (64-bit) 
Revision	fed0fcc915f6d9e1db871202f0304c8d582a73de
OS	Android 8.1.0; Build/OPM2.171026.006.H1; 27; REL
```

- Ensured Leo chat window is always full screen on fresh and upgraded profiles. 
- Ensured changing orientation when Leo is open does not cause problems.
- Ensured opening Leo menus/settings does not cause problems. 

Example | Example | Example | Example
-|-|-|-
![Screenshot 2024-02-28 at 11 42 47 AM](https://github.com/brave/brave-browser/assets/17885425/c1216ee6-d3d6-43b8-9259-6b3cda69f8ab) | ![Screenshot 2024-02-28 at 11 42 51 AM](https://github.com/brave/brave-browser/assets/17885425/2b1dba8a-e95b-4bf5-bca7-58d2f8b33451) | ![Screenshot 2024-02-28 at 11 43 53 AM](https://github.com/brave/brave-browser/assets/17885425/605d6436-1a7a-4ec5-bd8b-dbef231827aa) | ![Screenshot 2024-02-28 at 11 44 05 AM](https://github.com/brave/brave-browser/assets/17885425/2e4497d9-fc0e-4c14-b147-3adf339e35ea)
