### ISSUE TITLE
Guest window doesn't use private window theme

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#3629]
Below screen shot is in the order of guest window, tor window and private window.
Only guest window does not use private window theme.
Guest window also uses private profile like other windows.

<img width="1369" alt="screen shot 2019-03-08 at 08 50 11" src="https://user-images.githubusercontent.com/6786187/53997571-08c10e80-4180-11e9-93b7-a8adc9773ec8.png">

**Comment by simonhong** [comment]
@kjozwiak @rebron Is this intended or bug?

**Comment by srirambv** [comment]
@simonhong related to https://github.com/brave/brave-browser/issues/372 ?

**Comment by simonhong** [comment]
@srirambv Yes, this is duplicated one with #372
