### ISSUE TITLE
Bug when opening youtube plays the first video that the mouse passes over

### ISSUE THREAD

**Issue by GFrancV** [brave/brave-browser#36292]
## Description 
When you enter the main YouTube page or any channel, the first video you hover over will automatically open and play it, regardless of whether the page has finished loading or not.

## Steps to Reproduce
   1.  Open [youtube.com](https://youtube.com)
   2. Mouse over any video

## Actual result:
[bug.webm](https://github.com/brave/brave-browser/assets/35277540/e6a4b8e5-27e2-486c-a3d4-ce489b89865f)

## Expected result:
that does not open any video when you hover the mouse, only when you click.

## Brave version (brave://version info)
1.62.165 Chromium: 121.0.6167.184 (Official Build) (64-bit)

**Comment by rebron** [comment]
Hi @GFrancV Does setting brave://settings/content/autoplay to Block work for you?

**Comment by GFrancV** [comment]
It's working now! Thanks
