### ISSUE TITLE
Hide Rewards NTP widget in unavailable regions

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#36296]
## Description

For example, we should just hide the NTP Rewards widget in this case:

![image](https://github.com/brave/brave-browser/assets/11497541/55dec700-8c29-499c-b196-ede779330253)

**Comment by mkarolin** [comment]
STR:
1. VPN to an unsupported region
2. Open Brave and verify that the NTP doesn't show the Rewards widget.
