### ISSUE TITLE
Follow up to #33081 - Widevine does not work on Linux ARM64

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#36297]
Follow up to #33081

## Steps to Reproduce

1. Clean profile
2. Login to netflix
3. Play a movie

## Actual result:

Widevine install prompt is not shown
Cannot play a movie
![image](https://github.com/brave/brave-browser/assets/34715963/d8f24a2f-a498-44c2-834f-e944ce83e618)|![image](https://github.com/brave/brave-browser/assets/34715963/fa9323ab-4d4f-445c-a95a-2da07dcead62)
--|--

## Expected result:
Widevine install prompt is shown

![image](https://github.com/brave/brave-browser/assets/34715963/ac90cf9a-6dc6-4078-8c52-6be76b232309)

Able to play a movie

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.63.161 Chromium: 122.0.6261.57 (Official Build) (64-bit) 
-- | --
Revision | 37b02b4a373f40114e70cc034e491bcc8380f23a
OS | Ubuntu ARM 64

cc @mherrmann @mihaiplesa @theofficialgman @LaurenWags

**Comment by mherrmann** [comment]
I understand that you expect the popup. But on Arm64 Linux, it actually is not expected in the current implementation. The reasons are very technical. But if you want to know how to set up Widevine on Arm64 Linux, please see this article: https://support.brave.com/hc/en-us/articles/23881756488717-How-do-I-enable-Widevine-DRM-on-Linux

**Comment by theofficialgman** [comment]
I think this issue can be closed as "user error"/"user misunderstanding"

**Comment by rebron** [comment]
@mherrmann Should we mark this as wontfix then and close off?

**Comment by mherrmann** [comment]
@rebron yes. I'm doing so now.
