### ISSUE TITLE
[Android] Update the size of stats widget hide icon

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#36299]
## Description
Update the hide icon in the stats widget. Make it smaller and the same color as the shield icon on the left. As shown in the mockup below.

![image](https://github.com/brave/brave-browser/assets/28269287/867ec7ea-9799-42b0-bd55-1a65f302d2d5)

**Comment by deeppandya** [comment]
@aguscruiz can you recommend the size ?

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240305.005 release-keys
Brave build: 1.65.96 
Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Fresh install and launch Brave
2. Open `NTP` > *Verify*

**ACTUAL RESULTS:**
- Verified that the `Hide` icon on the `Privacy Stats` widget has the same color and compatible size as the `Shield` on the same widget.

---------------------------

|Dark Mode|Light Mode|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/ea7f2411-9d0c-4bac-8cf9-813e233cbad8) | ![2](https://github.com/brave/brave-browser/assets/128532965/9978d9d1-d370-49fe-80ea-c7d6a9e750f4) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/503c9291-7de6-40d9-8c77-7f7cb2d72333) | ![2](https://github.com/brave/brave-browser/assets/128532965/68ffeac2-f348-43dc-9762-01a9985211e1) |
