### ISSUE TITLE
Ephemeral storage not showing expected result when ephemeral storage disabled 

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#36307]
## Description 
Not getting expected results for most of the tests when `Ephemeral Storage` is `Disabled`

Session storage, local storage and cookies blocked for Remote frame (initial case)

This is for pre-chromium storage partitioning builds 

Example | Example 
-|-
![Screenshot 2024-02-21 at 4 48 42 PM](https://github.com/brave/brave-browser/assets/17885425/e4f0bd72-5679-4b4a-8269-e72d0d83d426) | ![Screenshot 2024-02-21 at 5 07 18 PM](https://github.com/brave/brave-browser/assets/17885425/79b3c187-b95f-4eab-99e7-1a42616fdca1)

## Steps to reproduce 

Test Page: https://dev-pages.brave.software/storage/ephemeral-storage.html

   1. Disable `Ephemeral Storage`
   2. Open test page
   3. Set cookie blocking to `Block cross-site cookies`
   4. Run tests

## Actual result 
Current results do not match expected result for test case

## Expected result
Should match

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Tab S7
   - Android version: 13
   
## Brave version
1.63.161

**Comment by deeppandya** [comment]
Closing the issue as it's expected.
