### ISSUE TITLE
Extensions deleted and left sync chain randomly

### ISSUE THREAD

**Issue by AwesomeKalin** [brave/brave-browser#36301]
## Description 

NOTE: This may have been a Windows 11 Bug, specifically with the Win32 API.

My browser was bugging out, likely due to a Windows 11 bug. I closed my browser, but Windows, likely due to a bug, didn't close Brave in the background. When closing it in Task Manager and then relaunching, my extensions and customisation disappeared. Out of panic, I closed my browser, and again had to kill it in Task Manager. Upon launching again, it was like I had never opened Brave, but it remembered that I had opened my extensions page. Upon further panic, I closed and killed Brave, closed everything else, and restarted my PC. When I relaunched Brave, everything except my extensions, customisation and my sync chain was removed. Bookmarks, passwords, etc. remained. This also only affected one of my profiles, not all of them. I have started to run sfc /scannow, and if any issues arise, I will update this issue. This has NOT affected my extensions information or any other devices in my sync chain

## Steps to Reproduce

Well explained above

## Actual result:

My browser info was partially removed

## Expected result:
My browser works just fine

## Reproduces how often: 

Just experienced for the first time after over a year of using Brave

## Brave version (brave://version info)

Brave: 1.62.165 Chromium: 121.0.6167.184 (Official Build) (64-bit) 
Revision: 646e9a49ef45084cb2341eb1e9afabc339004a27
OS: Windows 11 Version 22H2 (Build 22621.2428)

## Version/Channel Information:

Running Latest Stable Release

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? Unable to confirm

## Miscellaneous Information:

As stated above, this could be a Windows 11 problem, will report back if it is

**Comment by bsclifton** [comment]
@AwesomeKalin interesting - thanks for the heads up. Apologies we didn't respond when you had originally reported - I've been trying to catch up on issues to triage.

Your extensions should be synced - which makes this interesting. I'm curious if you did rejoin the sync chain and if the extensions were restored after that? 

Do you use Brave for any PWAs? (progressive web apps; basically where you can install a website like Slack, instagram, or Twitter as an application)

This can cause Brave to run in the background where you might have Brave closed but you have the PWA open. The updater will always run on Windows - but when you exit out and there are no PWA, it shouldn't have any instances running. You might check the brave://crashes screen and share if anything is there
