### ISSUE TITLE
handling of webrtc fingerprinting changed

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3630]
Found when testing https://github.com/brave/brave-browser/issues/3626
Handling of webrtc blocking changed from 0.60.x. Not sure if this is expected.
webrtc blocking is now more aggressive.

## Steps to Reproduce

   1. Clean profile
   2. Open https://diafygi.github.io/webrtc-ips/

## Actual result:

From 0.61.49
![image](https://user-images.githubusercontent.com/34715963/54006837-4eb9aa80-415f-11e9-8da6-d9efec52d969.png)

## Expected result:
From 0.60.48
![image](https://user-images.githubusercontent.com/34715963/54006738-de128e00-415e-11e9-8a14-d164c15a56c4.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.61.49 Chromium: 73.0.3683.67 (Official Build) (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 7 Service Pack 1 Build 7601.24312

cc @brave/legacy_qa

**Comment by kjozwiak** [comment]
Reproduced on `macOS 10.14.3 x64` using the following build:

Brave | 0.61.49 Chromium: 73.0.3683.67 (Official Build) (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Mac OS X

**Comment by jumde** [comment]
Behavior is same on chrome and chrome canary.

**Comment by GeetaSarvadnya** [comment]
Reproduced on `Linux Mint 0.61.49 `

Brave | 0.61.49 Chromium: 73.0.3683.67 (Official Build) (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Linux

**Comment by rebron** [comment]
cc: @diracdeltas We don't have an option anymore, IP address is hidden and chromium has the same behavior without an adblocker. We ok with this behavior now?

**Comment by diracdeltas** [comment]
Seems fine if the default behavior is that the webrtc leak is blocked.
