### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by soyoxymor0n** [brave/brave-browser#36305]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.64.74 Chromium: 122.0.6261.43
Operating System: Windows NT 10.0.22621

URL (if applicable) where crash occurred:
https://www.encotec.at/encotec-akademie/schulung-medizinprodukte/anmeldung/

Can you reproduce this crash?
Yes.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. filling in a (registration) form on a website. This happens on many registration forms I used in the last days. 
2. It might be related to having the Bitwarden extension installed. 
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/f9ee0200-b651-8c0b-0000-000000000000

**Comment by bsclifton** [comment]
See notes about Bitwarden being installed

Backtrace
https://brave.sp.backtrace.io/p/brave/debug?time=quarter&filters=JTVCJTVCJTIyX3J4aWQlMjIlMkMlMjJlcXVhbCUyMiUyQyUyMmY5ZWUwMjAwLWI2NTEtOGMwYi0wMDAwLTAwMDAwMDAwMDAwMCUyMiU1RCUyQyU1QiUyMl9kZWxldGVkJTIyJTJDJTIyZXF1YWwlMjIlMkMlMjIwJTIyJTVEJTVE&debug=(%226a4514f%22,0,0)

Callstack is not symbolized

**Comment by bsclifton** [comment]
Another incident of this https://github.com/brave/brave-browser/issues/35979

**Comment by iefremov** [comment]
@soyoxymor0n can you please reproduce on newer versoin and upload more dumps / share crash ids?

**Comment by soyoxymor0n** [comment]
Hi,

I didn't see this issue reappear anymore. Seems like it might have been
fixed.

Thanks
