### ISSUE TITLE
[Leo] Leo's full-screen UI blinks white when opening it, it's very noticeable if device is in `Dark Mode`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#36311]
## Description 

Leo's full-screen UI blinks white when opening it, it's very noticeable if the device is in `Dark Mode`. I checked on multiple devices: `Pixel 7 / 14`, `Pixel 6 / 13`, `Galaxy A32 / 13`, `Galaxy Tab S8 / 18` with and without `Premium` subscription.

## Steps to reproduce 

   1. Launch Brave
   2. Make sure, the device `Dark Mode` is ON (it's more noticeable in Dark Mode)
   3. Open Leo by going to `Three-dot menu` > Leo > *Observe, the screen blinks white*
   4. OR URL search bar > Type a query > Tap `Ask Leo` > *Observe, the screen blinks white*

## Actual result 

Leo's full-screen UI blinks white when opening it, it's very noticeable if the device is in `Dark Mode`.

https://github.com/brave/brave-browser/assets/128532965/228a3102-5bb7-4052-9581-fce252fb4386

https://github.com/brave/brave-browser/assets/128532965/82fe5d72-e331-42de-b490-c4b1cba08de3

https://github.com/brave/brave-browser/assets/128532965/4c763553-8426-4d82-aa7e-a3fa802fc70d

## Expected result

The screen must not blink white when opening Brave UI.

## Issue reproduces how often 

`Easily reproduced`

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? N/A
- Can you reproduce this issue with the current Play Store Beta version? N/A
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 7, Pixel 6, Galaxy A32, Galaxy Tab S8
   - Android version: ANY
   
## Brave version

```
Brave build: 1.65.26 
Chromium: 122.0.6261.57 (Official Build) canary (64-bit) 
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @SergeyZhukovsky

**Comment by kjozwiak** [comment]
The above requires `1.63.165` or higher `1.63.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 2 XL`, `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Pixel 2 XL / taimen-user  8.1.0 OPM2.171026.006.H1 release-keys
- Galaxy Tab S8 / gts8wifixx-user 13 TP1A.220624.014 release-keys
- Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.63.165
Chromium: 122.0.6261.94 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/36311#issue-2149953430

**ACTUAL RESULTS:**
- Verified that `Leo` UI is not blinking white

---------------------------

*Pixel 2 XL / phone*

https://github.com/brave/brave-browser/assets/128532965/6868bdef-c78f-42e5-b063-35c21cc69d4f

*Galaxy Tab S8 / tablet*

https://github.com/brave/brave-browser/assets/128532965/43b17e91-6dd2-4314-b4ff-e8cd8ea6c87a

*Pixel 7 / phone*

https://github.com/brave/brave-browser/assets/128532965/6e4c44f4-3c4b-440a-9600-8e5028804719
