### ISSUE TITLE
[Brave News]: clean up click targets

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#36314]
- Hovering an image (ads and content) should show url
- Clicking on card background should navigate to url

**Comment by LorenzoMinto** [comment]
Could we uplift this to 1.64?

**Comment by fallaciousreasoning** [comment]
Creating now :smile:

**Comment by kjozwiak** [comment]
The above requires `1.64.103` or higher for `1.64.x` verification 👍 @brave/qa-team as mentioned/discussed via https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1710217311091929?thread_ts=1710098438.193179&cid=CHGKGMHDJ, it looks like hovering over the images isn't displaying the URL as mentioned via https://github.com/brave/brave-browser/issues/36314#issue-2150072007 and will be addressed in a follow up. For the above, we just need to make sure that you can open `Brave News` articles by clicking on the `titles`, `background`, `images` etc..

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.64.103 Chromium: 122.0.6261.128 (Official Build) beta (x86_64)
-- | --
Revision | 41534736ca142c5829699b512024398eaa2bbfc0
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.64.103`
2. launched Brave
3. opened a new-tab page
4. opted in to `Brave News`
5. for each of the following, clicked on the `image`, `headline/title`, `main body link`

### Confirmed each of those link types worked

`Brave Ads`

example | example
---------|---------
<img width="1312" alt="Screen Shot 2024-03-13 at 11 15 39 AM" src="https://github.com/brave/brave-browser/assets/387249/cac67b17-4b6a-4833-8778-a3e6af88d64a"> |  <img width="1312" alt="Screen Shot 2024-03-13 at 11 15 44 AM" src="https://github.com/brave/brave-browser/assets/387249/064ddfe6-85ad-41ad-a8c2-e5cf8476d004">

`Regular article`

example | example
---------|---------
<img width="1312" alt="Screen Shot 2024-03-13 at 11 17 53 AM" src="https://github.com/brave/brave-browser/assets/387249/ec52916e-cc02-4208-abe6-7750ef351268"> | <img width="1312" alt="Screen Shot 2024-03-13 at 11 17 59 AM" src="https://github.com/brave/brave-browser/assets/387249/f847b879-9b0d-40c7-8cd5-31d5ec83bf33">

`New-tab page headline`

example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2024-03-13 at 11 19 55 AM" src="https://github.com/brave/brave-browser/assets/387249/594ce48f-ae64-4542-9afb-fcc402932834"> | <img width="1312" alt="Screen Shot 2024-03-13 at 11 19 59 AM" src="https://github.com/brave/brave-browser/assets/387249/2b33db0e-db13-446b-bdf5-aabcfe478698"> | <img width="1312" alt="Screen Shot 2024-03-13 at 11 20 03 AM" src="https://github.com/brave/brave-browser/assets/387249/fcc3bd1f-90cb-465e-ab27-879e15d4c032">
