### ISSUE TITLE
Page not available when braveshield is turned on.

### ISSUE THREAD

**Issue by Cannoli13** [brave/brave-browser#36328]
## Steps to Reproduce

   1. Enter https://ygosu.com/ with Brave Shield enabled.
   2. css is not loaded.

## Actual result: 

<img width="1604" alt="image" src="https://github.com/brave/brave-browser/assets/155059613/d53187cd-fe78-4458-885c-9e30347cf9e7">

## Expected result:
<img width="1604" alt="image" src="https://github.com/brave/brave-browser/assets/155059613/da9c6e30-7900-45a5-af6d-6fb12ef3ca62">

## Brave version (brave://version info)

brave://1.63.161

## Version/Channel Information: 
<img width="700" alt="image" src="https://github.com/brave/brave-browser/assets/155059613/465406ef-6ecd-4626-b215-83443caf689b">

- Can you reproduce this issue with the current release? -y
- Can you reproduce this issue with the beta channel? -y
- Can you reproduce this issue with the nightly channel? -y
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? -y
- Does the issue resolve itself when disabling Brave Rewards? -n
- Is the issue reproducible on the latest version of Chrome? -n

**Comment by bsclifton** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
Related;

https://github.com/brave/brave-browser/issues/35943
https://github.com/brave/brave-browser/issues/35231
https://github.com/brave/brave-browser/issues/35084

**Comment by ryanbr** [comment]
ads will show (its an anti-adblock ad-shield), but it won't be break the site anymore.
