### ISSUE TITLE
Add iOS P3A metrics for Leo

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#36324]
Add the following iOS P3A metrics for Leo:

`Brave.AIChat.Enabled.2`
`Brave.AIChat.UsageDaily.2`
`Brave.AIChat.UsageMonthly`
`Brave.AIChat.ChatCount`
`Brave.AIChat.AvgPromptCount`
`Brave.AIChat.UsageWeekly`
`Brave.AIChat.NewUserReturning`
`Brave.AIChat.LastUsageTime`

Please refer to https://github.com/brave/brave-browser/issues/34906 and https://github.com/brave/brave-browser/issues/32050 for metric definitions.

cc @brave/ios

**Comment by Brandon-T** [comment]
@DJAndries all of these are implemented already as the code is shared with iOS via: https://github.com/brave/brave-core/blob/master/components/ai_chat/core/browser/ai_chat_metrics.cc which is used by iOS via the conversation_driver.cc.

However, the only ones I'm not seeing are: 
```
Brave.AIChat.Enabled.2
Brave.AIChat.UsageDaily.2
```

**Comment by DJAndries** [comment]
@Brandon-T looking at the aggregated data, we're receiving both of the metrics that you mentioned for iOS. could you please re-confirm? The first metric should in the `logs_constellation_prep` pref and the second in `logs_constellation_prep_express`

**Comment by DJAndries** [comment]
all metrics are being reported, as expected. closing

**Comment by Brandon-T** [comment]
All of the stats are already recorded and show up now on `stats.brave.com` filtering by: `Brave.AIChat.Enabled.2` for example.
