### ISSUE TITLE
Peacock suddenly starts telling me browser not supported.

### ISSUE THREAD

**Issue by js-rushing** [brave/brave-browser#36325]
## Description 

Peacock streaming service used to work on Brave (past several months).  Now it does not as of 2/22/2024 5:00 PM CST.

## Steps to Reproduce

   1.  Login to Peacock streaming service.
   2.  See screen saying browser not supported.
   3.  Go, "aw man, that sucks."

## Actual result:

![Peacock Brave](https://github.com/brave/brave-browser/assets/66761884/cefb03b1-55fc-45e7-8888-60458b335bf7)

## Expected result:
Should allow me to watch videos.

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

Brave | 1.63.161 Chromium: 122.0.6261.57 (Official Build) (64-bit)

Revision | 37b02b4a373f40114e70cc034e491bcc8380f23a

OS | Windows 10 Version 22H2 (Build 19045.4046)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Gitchick57** [comment]
Brave has been quirky / glitchy with streaming services lately.  I try to login to CNN on my iMac and I get an error message stating that the DRM chip has expired,  not enabled or something to that effect when this is not the case.   



Feb 22, 2024, 6:43 PM by ***@***.***:

**Comment by ABWIZ74** [comment]
I have Google Chrome and the same thing happened to me yesterday. It was working just fine last weekend and all my other streaming sites are working.

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
I checked the site, we're still working on peacock. Do get a small warning "please disable your ad blocker.." at the bottom, but doesn't stop the viewing of the video.

Can you try disabling/re-enabling widevine in brave://settings/extensions @js-rushing, ensure Shields is up also. Would also test in private window mode.

**Comment by js-rushing** [comment]
Okay, yes, it turns out an update to one of my extensions managed to break that one site.  Sorry for the trouble.  Thank you for your time.  I'll close this.
