### ISSUE TITLE
Problem ASA Custom Onboarding Linked Screen

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-browser#36326]
## Description: 

The custom action is not triggering after an ad campaign is clicked in AppStore 

## Steps to Reproduce 
  1. Click Ad in AppStore
  2. Go trough Onboarding and enable p3a
  3. Check desired ad campaign screen is presented VPN or Playlist

## Actual result: 

Ad Campaign is not triggered

## Expected result:

Check VPN Buy Screen is presented when ad campaign is clicked in AppStore

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? N/A
- Can you reproduce this issue with the previous version of the current build from TestFlight? N/A
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
Any

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari? 

### Additional Information

This is follow-up for https://github.com/brave/brave-ios/pull/8591

**Comment by soner-yuksel** [comment]
This can be tested after Appstore release happened from an ad displayed inside the iOS Appstore.

**Comment by kjozwiak** [comment]
The above will be checked/verified once `1.62.1` goes out the door via https://github.com/brave/brave-ios/issues/8779.
