### ISSUE TITLE
Add support for LiFi cross-chain swaps

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#36335]
We want to add support for cross-chain swaps and bridging to the Swap UI in Brave Wallet. We have decided to go ahead with LiFi as our integration partner.

|Docs|https://apidocs.li.fi/reference/welcome-to-the-lifinance-api|
-|-

|Security|https://github.com/brave/reviews/issues/1439|
-|-

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (64-bit)
-- | --
Revision | 5d9143e1a0812c53bdc27fd5384591254306a88c
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from [brave/brave-core#22285](https://github.com/brave/brave-core/pull/22285)
- Verified existing 0x and Jupiter swaps works as expected
- Verified `exact out` swaps for EVM swaps works as expected. Entered `To` amount is same on `Review` panel
- Encountered [#35196](https://github.com/brave/brave-browser/issues/35196)

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.65.96 x64 Beta build
- Verified steps from [brave/brave-core#22285](https://github.com/brave/brave-core/pull/22285)
- Verified existing 0x and Jupiter swaps works as expected
- Verified `exact out` swaps for EVM swaps works as expected. Entered `To` amount is same on `Review` panel
