### ISSUE TITLE
Focus ring on buttons looks odd

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3633]
## Description 

Focus ring on buttons look odd 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/54028800-4029be00-4174-11e9-9ed9-81c97beca52a.png)

## Expected result:
No orange rectangular border  should be shown around the button

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.63.1 Chromium: 73.0.3683.67 (Official Build) dev (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 10 OS Build 17134.590

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes only on dev
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @cezaraugusto @rossmoody

**Comment by cezaraugusto** [comment]
cc @petemill

**Comment by rossmoody** [comment]
An updated spec for button styling can be reviewed here: https://share.goabstract.com/22f7c7af-fa47-404f-aeca-b896f0c58b4b

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.119 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2778
