### ISSUE TITLE
Implement Sidebar-enabled test with Griffin

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#36339]
For a subset of new users, we will default Sidebar to enabled. The effects of the change will be measured using P3A. 

1. Move Leo icon to top of Sidebar list
2. Group A:
```
Show Sidebar = Enabled (Always), Show on the Right
Show Sidebar button = Enabled
```
3. Group B:
```
Show Sidebar = Enabled (Always), Show on the Right
Show Sidebar button = Enabled
Open Sidebar panel one time. Show Sidebar panel in the opened state upon viewing the first non-SERP web page. Do not repeat. Default selection is Leo.
```

The plan is described in the spec here https://docs.google.com/document/d/1b4bm8bLZ0Efl1RSJMPb1N7u2O_qaOdBYyA-y0hOq3Sk/edit

**Comment by simonhong** [comment]
@mattmcalister Removed `OS/Android` label as sidebar is desktop only feature.

**Comment by simonhong** [comment]
https://github.com/brave/brave-browser/issues/32601 will be handled together with this issue.

**Comment by kjozwiak** [comment]
The above requires `1.64.103` or higher for `1.64.x` verification 👍 However, labelling the above as `QA/Blocked` till `1.64.x` migrates to the `Release` channel so the above can be verified via https://github.com/brave/brave-variations/pull/939 on `staging` before uplifting https://github.com/brave/brave-variations/pull/940 into `production` once `1.64.x` goes live.

However, because both `Group A` & `Group B` will be set to `2%`, QA might just run through the above on `Win` using the flags mentioned via https://github.com/brave/brave-core/pull/22306#issue-2153185967 like we did on `Nightly` before uplifting as per https://github.com/brave/brave-core/pull/22306#issuecomment-1990809527.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.64.108 Chromium: 123.0.6312.46 (Official Build) (64-bit)
-- | --
Revision | be7ad9d53800b7f5380fea097ff30bf628f157b0
OS | Windows 11 Version 23H2 (Build 22631.3296)
```

**`Test Case #1`** - https://github.com/brave/brave-browser/issues/32601

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/22306#issue-2153185967 & https://github.com/brave/brave-browser/issues/32601#issue-1872724131, ensured the following:

* ensured that `Leo` is the default button/feature that's selected/opened when clicking on the `Show sidebar` button
* ensured that the last selected feature/button is being opened when clicking on the `Show sidebar` button
  * clicked on `Bookmarks`, restarted Brave and ensured that `Brave Wallet` was being opened
  * clicked on `Reading List`, restarted Brave and ensured that `Brave Wallet` was being opened

**`Test Case #2`** - https://github.com/brave/brave-browser/issues/36339

#### `Group A` - `--enable-features=SidebarShowAlwaysOnStable`

**`Quick Note:`** `--dont-show-on-sidebar-non-stable` is not being used as we're verifying on `release/stable` and `sidebar` is not enabled by default. It's only enabled by default at `100%` for both `BETA` & `Nightly`.

launched `1.65.75 Chromium: 123.0.6312.29` using the following:
  * `--enable-features=SidebarShowAlwaysOnStable`
* opened `brave.com` and ensured that the `Leo` panel via the `sidebar` is not being opened

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|-----------------
![image](https://github.com/brave/brave-browser/assets/2602313/8a6ca8ee-444a-4db7-a272-a35163199853) | ![image](https://github.com/brave/brave-browser/assets/2602313/e646a6a5-f42c-4e3a-bf6d-8e882ca0147f) | ![image](https://github.com/brave/brave-browser/assets/2602313/200d8b6b-8913-4fcf-ada6-47eff2fc8f2f)

#### `Group B` - `-enable-features=SidebarShowAlwaysOnStable:open_one_shot_leo_panel/true`

**`Quick Note:`** `--dont-show-on-sidebar-non-stable` is not being used as we're verifying on `release/stable` and `sidebar` is not enabled by default. It's only enabled by default at `100%` for both `BETA` & `Nightly`.

##### `Case #1` - **PASSED**

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|-----------------
![image](https://github.com/brave/brave-browser/assets/2602313/ddaf35d2-8dba-4b00-b165-86ad633d2831) | ![image](https://github.com/brave/brave-browser/assets/2602313/9e39a0ad-06e5-4570-a724-2a7de5021687) | ![image](https://github.com/brave/brave-browser/assets/2602313/37bfb3fe-96d2-4894-a472-cddb0a3dd1d4) | ![image](https://github.com/brave/brave-browser/assets/2602313/94a401c9-8a72-486f-be98-9d45da240f1e)

##### `Case #2` - **PASSED**

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|---------------
![image](https://github.com/brave/brave-browser/assets/2602313/bdbc6acf-c5f3-4465-b82c-54c4139c45de) | ![image](https://github.com/brave/brave-browser/assets/2602313/29321b52-c7ff-4786-9f4e-5489b8f8c368) | ![image](https://github.com/brave/brave-browser/assets/2602313/c4a23dc2-e1ff-45fb-b2ac-d871168859f1)

##### `Case #3` - **PASSED**

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------
![image](https://github.com/brave/brave-core/assets/2602313/575c9d55-d189-4ea8-be51-50bb325e6b28) | ![image](https://github.com/brave/brave-core/assets/2602313/98a183cd-91ce-4fd9-a98d-bda45be8a645) | ![image](https://github.com/brave/brave-core/assets/2602313/d2873148-2168-46d4-840b-7aa95d63b1b4) | ![image](https://github.com/brave/brave-core/assets/2602313/21d8b03d-05eb-4e83-9c66-c360a6b6b51c)

##### `Case #3` - **PASSED**

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------
![image](https://github.com/brave/brave-browser/assets/2602313/7c79e79d-1f62-4608-96f5-958d7d205be4) | ![image](https://github.com/brave/brave-browser/assets/2602313/e0e99782-49c4-4afe-82dd-daab2766961d) | ![image](https://github.com/brave/brave-browser/assets/2602313/13155e3e-cade-4243-93da-4cd97280924c) | ![image](https://github.com/brave/brave-browser/assets/2602313/ac416710-7f6d-48a6-92f4-8fff3a6d0635)

##### `Case #4` - **PASSED**

* launched `1.64.108 Chromium: 123.0.6312.46` without any terminal/CLI switches/flags
* loaded `https://brave.com` and closed Brave
* re-launched the same profile using the following:
  * `brave.exe --enable-logging=stderr --enable-features=SidebarShowAlwaysOnStable:open_one_shot_leo_panel/true`
* ensured that the `sidebar` is not being loaded/opened when loading any non-SERP pages.

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|-----------------
![image](https://github.com/brave/brave-browser/assets/2602313/1e8fbc7c-9f97-495d-84e2-10379c3ce91e) | ![image](https://github.com/brave/brave-browser/assets/2602313/8436f3a6-e07a-4d5d-be8a-c210849a6268) | ![image](https://github.com/brave/brave-browser/assets/2602313/0c3c6e7f-34c9-4f4e-8502-6fbc7abddd7d)

**Comment by kjozwiak** [comment]
We'll need https://github.com/brave/brave-browser/issues/36815 to land in `1.64.x` before we can run through https://github.com/brave/brave-variations/pull/940.
