### ISSUE TITLE
Swap "Reject" and "Confirm" button within pending transaction panels when issues are detected

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#36342]
## Description 

For security, we should swap the confirm and reject button styles and placement when a pening transaction with issues is detected to prevent a user from blindly approving the transaction

## Steps to Reproduce

Scenario 1: Issue(s) detected
   1. visit https://metamask.github.io/test-dapp/
   2. connect with a wallet account + network that does not have enough funds for a transaction
   3. click the send EIP 1559 transaction button
   4. observe the pending transaction in the wallet panel

Scenario 2: No Issue(s) detected
   1. visit https://metamask.github.io/test-dapp/
   2. connect with a wallet account + network that has enough funds for a transaction
   3. click the send EIP 1559 transaction button
   4. observe the pending transaction in the wallet panel

## Actual result:

Scenario 1: Issue(s) detected
<img width="371" alt="Screenshot 2024-02-23 at 4 19 16 PM" src="https://github.com/brave/brave-browser/assets/30185185/8f02174d-8048-44c7-a756-f8ba60e7f0ea">

Scenario 2: No Issue(s) detected

<img width="382" alt="Screenshot 2024-02-23 at 4 19 54 PM" src="https://github.com/brave/brave-browser/assets/30185185/4c24d844-931a-4b98-80dc-841525cc9f68">

## Expected result:

Scenario 1: Issue(s) detected
<img width="387" alt="Screenshot 2024-02-23 at 4 09 21 PM" src="https://github.com/brave/brave-browser/assets/30185185/8b91e5dc-a93c-4f01-85c3-953255aeb61b">

Scenario 2: No Issue(s) detected
<img width="383" alt="Screenshot 2024-02-23 at 4 08 53 PM" src="https://github.com/brave/brave-browser/assets/30185185/06fdd319-1f0c-49f7-96f7-cb9a8777bf98">

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | 2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from issue description
- Verified when transaction is submitted with insufficient funds, `Reject` button is swapped with `Confirm` and is enabled 
- Verified when transaction is submitted with sufficient funds, `Confirm` button is swapped with `Reject` and is enabled 
- Encountered [37089](https://github.com/brave/brave-browser/issues/37089)

https://github.com/brave/brave-browser/assets/17010094/560a3270-ef49-49b4-8f56-02d3e4f1658a
