### ISSUE TITLE
Use latest designs for pending transaction panel confirm and reject buttons

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#36343]
## Description 

<img width="353" alt="Screenshot 2024-02-23 at 4 28 57 PM" src="https://github.com/brave/brave-browser/assets/30185185/5784a072-393b-4e20-afa2-452b60afbe1a">

## Steps to Reproduce

   1. create a pending transaction
   2. observe the confirm and reject buttons

## Actual result:

the buttons have a large border radius and have icons

## Expected result:
the buttons have a smaller border radius and no icons

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | 2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from issue description
- Verified Confirm/Reject buttons have a bigger border radius and doesn't have any icons

![image](https://github.com/brave/brave-browser/assets/17010094/75162cf1-c3cd-47d6-ac66-3e45ad061ad0) | ![image](https://github.com/brave/brave-browser/assets/17010094/e2e4374a-0d8c-445b-8524-1fba33530531)
-- | --
