### ISSUE TITLE
No download instructions for OpenSUSE

### ISSUE THREAD

**Issue by hemna** [brave/brave-browser#3635]
Went to the downloads page here:
https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

There are no download/install instructions for openSUSE.

**Comment by NumDeP** [comment]
+1 from multiple users from the community.

- https://community.brave.com/t/please-fix-these-4-issues-in-opensuses-version/33222

- https://community.brave.com/t/opensuse-brave/44524

- https://community.brave.com/t/installing-brave-on-opensuse/47721

FYI - There should also be a way to notify users in the community.brave by Discourse similarly the way moderators do when a topic is closed in Github.

@hemna mate, why did you open two [issue](#2354) that are related.

**Comment by rebron** [comment]
cc: @mbacchi @bkero @Brave-Matt can you take a look for adding instructions?

**Comment by fmarier** [comment]
In #1900, we are trying to figure out why the RPM repository is not currently compatible with OpenSUSE.

**Comment by fmarier** [comment]
As of https://github.com/brave/brave-browser/pull/6087, we now have official instructions for installing Brave on OpenSUSE.
