### ISSUE TITLE
Update Composer UI Button Border Radius

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#36354]
## Description 

We need to update the `Composer UI` Button `border-radius` to match the new designs in `figma`

## Expected result:

![Screenshot 36](https://github.com/brave/brave-browser/assets/40611140/d8620128-eb7f-4a3e-a26e-0eb1c56701cf)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | 2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from [brave/brave-core#22298](https://github.com/brave/brave-core/pull/22298)
- Verified Send/Swap dropdown is updated to new UI and is squarish appearance
- Verified on both dark and light theme

https://github.com/brave/brave-browser/assets/17010094/12386661-f7be-4094-90a6-a61ab47d966e
