### ISSUE TITLE
Settings re-organization for Privacy/Security/Shields sections

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#36363]
Proposed changes in brave://settings:

1. Combine brave://settings/privacy and brave://settings/shields: brave://settings/privacy redirects to brave://settings/shields (so some of our documentation doesn't need to be updated). The new settings menu title will be `Privacy and Shields`. Icon can be the existing Shields icon.
2. Move `Auto-redirect AMP pages`, `Auto-redirect tracking URLs` and `Prevent sites from fingerprinting me based on my language preferences` into Privacy.
3. Add new subsection in `Privacy and Shields` called `Data Collection` and move P3A, daily usage ping and diagnostic reports under it. This is independently useful and can be done in a separate work item as well.
4. After the above are done, brave://settings/shields will contain the following sections: Shields, Privacy, Data Collection, Social Media Blocking.
5. Move `Security` to be its own top-level settings menu. Icon can be existing icon for `Privacy and security`. brave://settings/security will become a top level menu item that contains:
    - Tor Windows
    - Safe browsing
    - Safety Check
    - Advanced (submenu that contains security > advanced items)

**Comment by ShivanKaul** [comment]
cc @diracdeltas @rebron

**Comment by fmarier** [comment]
> Tor Windows

Seems to me like Tor is a privacy feature (hiding IP address), not a security feature.

**Comment by ShivanKaul** [comment]
I could go either way on Tor, one consideration was that the Privacy section was already full. We could alternatively rename the Security section "Security & Tor Mode"

**Comment by ShivanKaul** [comment]
@rebron it would be good to have a link to https://brave.com/privacy-updates/7-ephemeral-storage/ somewhere where we talk about 3p cookies in settings, similar to how Firefox has a link to [Total Cookie Protection](https://support.mozilla.org/en-US/kb/introducing-total-cookie-protection-standard-mode) where the user can choose cookie policy. This is a niche concern but it is true that we are not technically outright blocking 3p cookies, we're partitioning them by top-level site and clear them when the tab closes (which is more protective than FF which partitions but never deletes.)

**Comment by rebron** [comment]
`https://www.figma.com/file/IXNCYwXmMWaF6u7Pdv1pOW/Desktop-settings---Nala?type=design&node-id=1155-30539&mode=design&t=ZIB63ZKvPuQkxD60-0`

Option 1: Tor in the Shields and Privacy section
<img width="459" alt="Screenshot 2024-02-29 at 8 34 52 PM" src="https://github.com/brave/brave-browser/assets/5951041/3e94dab4-47fa-4acc-a574-fdcbaac943a2">

<img width="445" alt="Screenshot 2024-02-29 at 8 35 01 PM" src="https://github.com/brave/brave-browser/assets/5951041/2afbf7dc-19cd-4221-bfc6-614e3faa6cb7">

Option 2: Tor in the Security section
<img width="355" alt="Screenshot 2024-02-29 at 8 35 26 PM" src="https://github.com/brave/brave-browser/assets/5951041/f16f241d-64a4-433e-8bf0-a59c90732c22">
<img width="399" alt="Screenshot 2024-02-29 at 8 35 33 PM" src="https://github.com/brave/brave-browser/assets/5951041/3bfae537-4cac-459d-b69b-7a5801631062">

**Comment by rebron** [comment]
@ShivanKaul @diracdeltas Options 1 and 2 above based on the original description. 
I have another option 3 proposal to do items 2 and 3 in the description and moving the third party cookies sub-menu item to Shields. Let me put a mock together for that option 3 which may be easier to maintain.

**Comment by ShivanKaul** [comment]
@fmarier wdyt about putting Tor into Security and renaming it "Security & Tor Mode", based on the screenshots above?

**Comment by fmarier** [comment]
Another thing that's going to be a little weird after the switch is:
- encrypting web pages is in privacy (HTTPS upgrades)
- encrypting DNS queries is in security (DoH)

They're both security features which improve privacy, but they're in different top-level sections.

**Comment by fmarier** [comment]
Looking at the new security settings, these are mostly things that don't really deserve top-level real estate:
- TLS cert management
- disabling Safe Browsing
- V8 security

and then we have the _Safety Check_ section which is pretty useless in Brave to be honest and should probably just be removed. Maybe we don't need a top-level security section?

**Comment by rebron** [comment]
Option 3. This option has the lowest touch, keeps Shields as top level label, Security and Privacy as top level label, and covers items 2 and 3 in the issue but also removed Third party cookies from Privacy and Security and put that sub-menu option into Shields.

<img width="768" alt="Screenshot 2024-03-06 at 7 04 46 PM" src="https://github.com/brave/brave-browser/assets/5951041/a40d2f2b-f00d-4fb7-b479-5dfeea896385">
<img width="918" alt="Screenshot 2024-03-06 at 7 05 00 PM" src="https://github.com/brave/brave-browser/assets/5951041/fcd838e0-2b30-403d-a6d5-329bc9d55558">

**Comment by fmarier** [comment]
Option 3 feels like a good first step to me.

@rebron what do you think about hiding the _Safety check_ section entirely? I don't think it's providing a lot of value in Brave.

**Comment by rebron** [comment]
Closing as a dupe of #36859. Fix will be reflected/released in 1.66.x.
