### ISSUE TITLE
Cannot connect Uphold account to Brave Rewards

### ISSUE THREAD

**Issue by gh0sti** [brave/brave-browser#36360]
## Description 

I am switching from gemini over to uphold. I went to reset rewards and sign into my uphold account. When I go to sign in it tries to auto complete the page and skips over the login and just errors out.

## Steps to Reproduce

   1. click connect account
   2. login to uphold
   3. Your request is still being processed, please wait. Sorry there was a problem processing your request, please try again.

## Actual result:

Not sure why I cant switch to uphold

## Expected result:
supposed to sign in to uphold and tie to rewards

## Reproduces how often: 

all the time

## Brave version (brave://version info)

Brave is up to date
[Version 1.63.162 Chromium: 122.0.6261.69 (Official Build) (x86_64)](https://brave.com/latest/)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
@gh0sti Can you try clearing your site data (cookies, etc.) for Uphold.com and then try again? That might stop it from auto-filling.

**Comment by gh0sti** [comment]
I was able to get it to work but it was challenging due to the auto skip page for acknowledgment. The login flow to uphold for connecting to Brave rewards needs to be looked at.
