### ISSUE TITLE
Clicking on the IPFS badge/button on `https://blog.ipfs.tech` doesn't loads `ipns://blog.ipfs.tech` in a new tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36366]
## Description 

Clicking on the IPFS badge/button on `https://blog.ipfs.tech` doesn't loads `ipns://blog.ipfs.tech` in a new tab

## Steps to Reproduce

   1. Install `0.26.0` Kubo via dev flags
   2. Set resolution to local node
   3. Visit `https://blog.ipfs.tech` in a new tab
   4. Click on the `IPFS` badge in URL bar
   5. Loads `ipfs://bafybeigrhkzvg4hjvefycoootx4c3cxdtnon3pgoe26vcrnbyyhnzaufqu/` instead of `ipns://blog.ipfs.tech`

## Actual result:

Loads `ipfs://bafybeigrhkzvg4hjvefycoootx4c3cxdtnon3pgoe26vcrnbyyhnzaufqu/`  with local node resolution
Loads `https://bafybeigrhkzvg4hjvefycoootx4c3cxdtnon3pgoe26vcrnbyyhnzaufqu.ipfs.dweb.link/`  with gateway resolution

## Expected result:
Should load `ipns://blog.ipfs.tech`

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @vadimstruts

**Comment by MicahZoltu** [comment]
I believe that the current behavior is correct.  There are two ways to figure out that https://blog.ipfs.tech is available on IPFS:
1. Through DNS Link by doing a DNS looking up of `_dnslink.blog.ipfs.tech` and seeing that it points at an IPFS hash.
2. By looking at the HTTP response headers, which include `X-Ipfs-Roots` and `X-Ipfs-Path` and `Etag`, all of which contain the IPFS hash.

IN the case of `blog.ipfs.tech`, all of these point to IPFS hashes, and none point to IPNS names.  I don't know if there is a support in either DNSLink or headers to provide an IPNS name, but at least for the site in question they are providing an IPFS hash so the correct behavior is to follow it to the IPFS version of the site, not the IPNS version.

**Comment by srirambv** [comment]
This seems to be an issue with VPN. Works fine without VPN. Closing the issue as invalid
