### ISSUE TITLE
add notification for monthly tip contribution

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3637]
## Description 
Currently we do not have a notification for when monthly tips are contributed. This may not be needed if auto-contribute is turned on (since tips and a-c are contributed at relatively the same time), however when auto contribute is off, it might be nice to have a notification that monthly tip contributions have processed.

cc @mandar-brave for consideration, additional information/details.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

Used test plan from https://github.com/brave/brave-core/pull/1959

![image](https://user-images.githubusercontent.com/34715963/56727333-c31ccd00-6750-11e9-8e05-5d0ebea06cf4.png)
