### ISSUE TITLE
[Wallet] Perf: remove uncached "full tokens list"

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#36374]
## Description 

Remove duplicate fetches for tokens from the Brave Wallet tokens registry, preferring the RTK-Query version.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (64-bit)
-- | --
Revision | 5d9143e1a0812c53bdc27fd5384591254306a88c
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from [brave/brave-core#22322](https://github.com/brave/brave-core/pull/22322)
- Verified known tokens continue to appear in the edit visible asset list without any regression
