### ISSUE TITLE
[Wallet] Unable to fetch network fees for Scroll & Telos

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#36370]
## Description 

https://community.brave.com/t/wallet-unable-to-fetch-fee-estimates-on-telos-network/533006

"Cannot execute any transactions using the desktop client wallet. The error ‘unable to fetch fee estimates’ appears on the transaction review screen. I have tried several of the available rpcs listed on [chainlist](https://chainlist.org/chain/40) to no avail. This was previously working and seems to only affect desktop clients. Balances display, and connecting to applications works but fee estimation fails even for direct transfers."

## Steps to Reproduce

   1. Add Telos or Scroll chain to wallet
   2. Attempt a transaction (can use https://metamask.github.io/test-dapp/ if you have no funds)
   3. Observe the pending transaction in the panel

## Actual result:

Wallet fails to fetch network fees for transactions

<img width="381" alt="Screenshot 2024-02-26 at 1 26 39 PM" src="https://github.com/brave/brave-browser/assets/30185185/0ff96834-6ee2-47f2-b332-5312ea2dcbdd">

## Expected result:
Wallet should successfully fetch network fees for transactions

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by wakqasahmed** [comment]
Same issue is happening for me on ELA network.

https://chainlist.org/?chain=40&search=elastos

**Comment by Tomklong** [comment]
How long will it take to patch this error, and is there a workaround in the meantime? 
Funds are stuck effectively locked because of this for 2 weeks at this stage.

**Comment by Tomklong** [comment]
@onyb any update?

**Comment by Tomklong** [comment]
@onyb @josheleonard @BrendanEich 

is there any update? is the issue being worked on and what is the likely leadtime to patch it? 

this issue has locked my funds for the last three weeks. brave has already used a custom derivation for their legacy wallets meaning i cant safely move my wallet out of brave, so you've locked me in and the locked my funds.

**Comment by onyb** [comment]
@Tomklong Bumped up the priority. Looking into a fix for this ASAP. Will try to get the fix as part of 1.64 due March 19, in case it's too late for 1.63.x.

**Comment by kjozwiak** [comment]
The above requires `1.64.107` or higher for `1.64.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.107 Chromium: 123.0.6312.46 (Official Build) (64-bit)
-- | --
Revision | cb2648b2e2cf3de3bbd87f1c2826e308ebf2f906
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from issue description
- Verified gas estimates is shown for Scroll and Telos

https://github.com/brave/brave-browser/assets/17010094/3df89d69-37c4-4e61-bff8-1216cbd2875c

**Comment by memehistorian** [comment]
yo brave wallet fuckin sucks. I got jebaited into using it while i was super tired one night after i installed phantom and now my shit is locked indefinitely until brave can pull their head outta their ass. Imagine not pushing a wallet fee update patch for months. wtf?
