### ISSUE TITLE
Feature Request Button is Overlapping Wallet Card

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#36373]
## Description 

The `Feature request` button sometimes overlaps the Wallet `Card` body.

## Steps to Reproduce

   1. Go to the `Portfolio` screen
   2. Shrink the browser window size
   3. The `Feature request` button will eventually overlap the Wallet `Card` body.

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/b5b0bb2e-6789-43af-a8e3-a554946de087

## Expected result:

It should disappear before overlapping the `Card`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | 2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from issue description
- Verified reducing the window size, `Request feature` button is hidden just before it overlaps on the wallet card

https://github.com/brave/brave-browser/assets/17010094/c30ef322-e6f6-41d3-9906-5222ea15d41b
