### ISSUE TITLE
Playlist items are not cleared on same-document navigation

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#36382]
This is regression from the previous PR. https://github.com/brave/brave-core/pull/21332/files#diff-b5c0bf1e1afd85e977fd6fe4e8d2f340b074e3a496285ab06709a1b5dfc3414a

We changed   void DidFinishNavigation() to PrimaryFrameChanged(). This should be revereted.

**Comment by rillian** [comment]
I think I hit this today with 1.65.35 (on desktop linux). Roughly:

1. Start youtube video playing
2. Click note icon in url bar to add it to playlist
3. Search for and start playing a new youtube video
4. Note icon acts like the new video is already in the playlist
