### ISSUE TITLE
Follow up of PR #22110 - The metrics `Brave.Wallet.ActiveSolAccounts` response value is `1` even when the Solana account doesn't have the wallet balance.

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#36387]
## Description 

Found while testing the PR https://github.com/brave/brave-core/pull/22110

The metrics `Brave.Wallet.ActiveSolAccounts` response value is `1` even when the Solana account doesn't have the wallet balance.
## Steps to Reproduce

1. Clean profile `1.65.30` launch browser using `brave.exe --p3a-count-wallet-test-networks`
2. Open brave://local-state, confirmed that the metrics `Brave.Wallet.ActiveSolAccounts` isn't shownas expected
3. Go to brave://settings/wallet/networks and click on the 3 dot menu for `Solana Testnet` and click on `set as default`
4. Create a wallet and enable the Show test networks switch while creating the wallet
5. Reload brave://local-state file
6. The metrics `Brave.Wallet.ActiveSolAccounts` response value is `1` instead of `0`
   

## Actual result:

The metrics Brave.Wallet.ActiveSolAccounts response value is `1` instead of `0`

## Expected result:
The response `1` should be shown only when the wallet has some balance

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.65.30 Chromium: 122.0.6261.69 (Official Build) nightly (64-bit)
-- | --
Revision | 4a43ce4f7cdc5f5f5f643b9e0e7d319b1b4313ac
OS | Windows 10 Version 22H2 (Build 19045.4046)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @supermassive @srirambv @DJAndries

**Comment by kjozwiak** [comment]
The above requires `1.64.96` or higher for `1.64.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.64.102 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | c9343c77bd5dee3524fc45f89721ce0bf4c09b8d
OS | Windows 10 Version 22H2 (Build 19045.4046)
```
