### ISSUE TITLE
Toolbar in main menu is moved to top after interacting with Leo

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#36396]
## Description 
After interacting with Leo, opening main menu again will show toolbar items on the top. New tab/relaunch will fix it. 

## Steps to reproduce 

   1. Fresh install
   2. Enable Leo
   3. Interact with Leo

## Actual result 
![Screenshot 2024-02-27 at 11 40 08 AM](https://github.com/brave/brave-browser/assets/17885425/dfe34a48-fcb3-4c2c-a532-fe852b022b2e)

https://github.com/brave/brave-browser/assets/17885425/91ac9d6e-f182-458d-b74b-82de7b84b6a1

## Expected result
![Screenshot 2024-02-27 at 11 40 21 AM](https://github.com/brave/brave-browser/assets/17885425/a6c7c6e5-159c-4ec1-9616-b26d2ed29ddf)

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung devices
   - Android version: 13
   
## Brave version
1.63.164

**Comment by kjozwiak** [comment]
@Uni-verse @hffvld we'll need `1.67.105` which includes https://github.com/brave/brave-core/pull/23946 before we can verify the above using `1.67.x`.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.67.105 Chromium: 126.0.6478.26 (Official Build) beta (64-bit) 
Revision	ff15eaa0be4f63abc388184895a7450c929375c8
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that toolbar in main menu is at the bottom after interacting with Leo.

https://github.com/brave/brave-browser/assets/17885425/c84c64b7-dadf-40d0-9efa-ef613a6acc55
