### ISSUE TITLE
Force Google Play to supply arm32 for Android 8/8.1

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#36390]
## Description 

Follow up for
https://github.com/brave/brave-core/pull/22132
https://github.com/brave/brave-browser/issues/36022

We disabled `use_relr_relocations` option for all builds to prevent crash on Android 8. At the same time fully optimized libs are much faster on Android 9 and above.

Chrome uses arm32 libs on Android 8/8.1.

We need to make the same:
- supply arm32 builds for Android 8;
- enable all optimizations for arm64 for Android 9 and above.

**Comment by hffvld** [comment]
Verified on `Pixel 2 XL` and `Pixel 6` using version(s):
```
Device/OS: 
- Pixel 2 XL / taimen-user  8.1.0 OPM2.171026.006.H1 release-keys
- Pixel 6 / oriole-user 13 TQ3A.230901.001 release-keys
Brave build: 1.65.96 
Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
```
---------------------------

<details>
<summary> Pixel 2 XL / Android 8.1.0 </summary>

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/22336#issue-2156629387
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `32-bit` version of Brave downloaded and installed.
- Verified that Brave is not crashing on app launch.
- Verified that `32-bit` version downloaded after upgrade is done when first sideloaded `64-bit` version, and then updated the app from Play Store.

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/d0c9da79-30d7-4a59-9dca-859a2d8f64e3) | ![2](https://github.com/brave/brave-browser/assets/128532965/e7b18325-33a4-4bb1-b881-cf967243309f) |

*Fresh install*

https://github.com/brave/brave-browser/assets/128532965/d8419ccf-f262-40f6-838e-aa9ad75b9638

*Upgrade*

https://github.com/brave/brave-browser/assets/128532965/f44a87f7-cab0-4cb0-85fa-9785c82f549f
</details>

<details>
<summary> Pixel 6 / Android 13 </summary>

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/22336#issue-2156629387
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `64-bit` version of Brave downloaded and installed.
- Verified that Brave is not crashing on app launch.

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/fe1e97ed-e640-4f61-8610-27e1cb480d5f) | ![2](https://github.com/brave/brave-browser/assets/128532965/791eb032-679b-49e3-b09b-37191382db41) |

https://github.com/brave/brave-browser/assets/128532965/138092d4-b768-4a61-bff2-0fa091d9ce4a
</details>
