### ISSUE TITLE
deprecated vBAT balance displays once self custody wallet is connected

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#36395]
## Description 

We deprecated vBAT awhile ago, however if a user had never connected to a custodian, had a vBAT balance at the time of deprecation, and then subsequently connects to self custody once available, the deprecated vBAT balance displays in the UI again.

## Steps to Reproduce

   1. Have an old profile with a vBAT balance that existed prior to deprecation and was never connected to a custodian
   2. Connect to self custody (I used Brave Wallet)
   3. See deprecated vBAT Balance in the UI

## Actual result:

<img width="1332" alt="Screenshot 2024-02-27 at 10 42 57 AM" src="https://github.com/brave/brave-browser/assets/28145373/38f60639-70d8-47b7-b1c3-862a15191b3f">

## Expected result:

no vBAT balance shown in UI as it's deprecated

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.65.35 Chromium: 122.0.6261.69 (Official Build) nightly (x86_64)
-- | --
Revision | 8873b7ee8825b7b68a55a5ffbd3ab44759476d02
OS | macOS Version 13.6.4 (Build 22G513)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? probably yes
- Can you reproduce this issue with the beta channel? probably yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing

**Comment by Miyayes** [comment]
@LaurenWags can confirm if this reproduces in release. If so, this is something we should try to get into an upcoming 1.63.x maintenance release.

**Comment by kjozwiak** [comment]
The above requires `1.63.167` or higher for `1.63.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.63.168 Chromium: 122.0.6261.94 (Official Build) (x86_64)
-- | --
Revision | 08196d502fa95681adc6dd9fc06a04d0664ac538
OS | macOS Version 13.6.4 (Build 22G513)
```
