### ISSUE TITLE
[Wallet] Hiding NFTs does not remove them from the "collected" section

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#36399]
## Description 

Clicking "Hide" on an NFT adds it to the "Hidden" section, but does not remove it from the "collected" section of the portfolio

## Steps to Reproduce

   1. Add an NFT to your wallet
   2. view the NFT "collected" section of the portfolio
   3. click the "..." icon
   4. click "hide"

## Actual result:

The NFT is not removed from the "collected" section of the portfolio NFT page

## Expected result:
The NFT is removed from the "collected" section of the portfolio NFT page

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | 2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from issue description
- Verified able to Hide/Unhide NFTs from collected and hidden states

https://github.com/brave/brave-browser/assets/17010094/4dbecbb4-cebf-46cc-af43-17d884c931a9
