### ISSUE TITLE
publisher list should go into retries

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3639]
## Description 
Per discussion with @NejcZdovc , if publisher list cannot be loaded for any reason, it should go into retries.

## Steps to Reproduce

1. Clean profile, enable Rewards.
2. Visit a verified site (brave.com) for min time.
3. Open a new tab. Close brave.com.
4. Navigate to rewards page, make sure site is recorded in ac table.
5. Close brave.
6. Delete `publisher_info` from profile folder.
7. Launch Brave
8. Navigate to another verified site (like DDG) for min time. 
9. Open panel, site does not show as verified.
10. Open a new tab.
11. Navigate to Rewards page.
12. Site is listed in a-c table but is not verified.
13. Open a new tab, navigate to brave.com for min time.
14. Navigate to Brave Rewards page.
15. brave.com no longer shows as verified.

## Actual result:
publisher list could not be reached (in this case it did not exist), so all sites showed as unverified.

## Expected result:
since publisher list could not be reached, it should have gone into retries and refetched from server.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.60.48 Chromium: 72.0.3626.121 (Official Build) (64-bit)
-- | --
Revision | da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.62.49 Chromium: 73.0.3683.86 (Official Build) (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Windows 10 OS Build 17134.523

- Verified the test plan from https://github.com/brave/brave-core/pull/1906
- Verified the STR from description
