### ISSUE TITLE
Support image based pdfs in Leo

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#36403]
## Description 

Some pdfs include text that's not accessible since they're image based. 
Leo is not able to summarize or understand these types of pdf docs. 

Related: https://chromium-review.googlesource.com/c/chromium/src/+/5246898

## Steps to Reproduce

   1. View a pdf file e.g. `https://www.vintage-trek.com/Trek-Fisher-Klein-Lemond/2004trek.pdf`
   2. Open Leo
   3. Select Summarize and notice content is not applicable to the pdf file.

## Actual result:

<img width="2157" alt="Screenshot 2024-02-27 at 11 38 06 AM" src="https://github.com/brave/brave-browser/assets/5951041/c81f2472-ed8a-4b07-a3c2-d3471e70a683">

## Expected result:
Leo has access to the text of the pdf document.

## Reproduces how often: 

Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.67.73 Chromium: 125.0.6422.26 (Official Build) nightly (64-bit)
-- | --
Revision | 76e7d97680074902ad7bde84f0a1a6c392a4ca6a
OS | Windows 10 Version 22H2 (Build 19045.4355)
```

example | example
----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/0fdb32b3-d924-4e14-88b4-29513c7b96c0) | ![image](https://github.com/brave/brave-browser/assets/387249/2eabf789-79a5-4603-95a0-18830970582e)

**Comment by stephendonner** [comment]
## Verification `PASSED` using

```

Brave | 1.67.73 Chromium: 125.0.6422.26 (Official Build) nightly (x86_64)
-- | --
Revision | 76e7d97680074902ad7bde84f0a1a6c392a4ca6a
OS | macOS Version 11.7.10 (Build 20G1427)


```

### Steps:
1. installed 
2. launched Brave
3. loaded `https://www.vintage-trek.com/Trek-Fisher-Klein-Lemond/2004trek.pdf`
4. clicked on `Leo` in the sidebar
5. clicked `Summarize this page`
6. clicked `I understand`

example | example | example
---------|----------|---------
<img width="2009" alt="Screen Shot 2024-05-07 at 1 16 35 PM" src="https://github.com/brave/brave-browser/assets/387249/e33c235e-70a8-404b-ab7e-efaab7d1673d"> | <img width="2009" alt="Screen Shot 2024-05-07 at 1 16 37 PM" src="https://github.com/brave/brave-browser/assets/387249/8e5f88b1-b274-41b4-a114-bf5f85c182a8"> | <img width="2009" alt="Screen Shot 2024-05-07 at 1 18 17 PM" src="https://github.com/brave/brave-browser/assets/387249/1a96b013-196c-4595-a55c-8c782d520aaa">
