### ISSUE TITLE
[Wallet] Unable to mark hidden or "collected" NFTs as spam

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#36400]
## Steps to Reproduce

Scenario 1 - Attempt to mark a "collected" NFT as "junk"
- Add an NFT to your wallet
- view the NFT "collected" section of the portfolio
- click the "..." icon

Scenario 1 - Attempt to mark a "hidden" NFT as "junk"
- Add an NFT to your wallet
- view the NFT "collected" section of the portfolio
- click the "..." icon
- click "hide"
- click the "collected" drop-down
- click "hidden"
- - click the "..." icon on a hidden NFT

## Actual result:

- No option to mark the NFT as "junk"

## Expected result:
- There should be an option displayed to mark the NFT as "junk"

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | 2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from issue description
- Verified new option for `Mark as Junk` is shown on NFT more menu
- Verified `Mark as Junk` is shown on both `Collected` NFTs list and manually hidden NFTs under `Hidden` list

https://github.com/brave/brave-browser/assets/17010094/5e84efc1-ace9-405f-b80e-a612b700ad94
