### ISSUE TITLE
insufficient funds notification and unable to contribute when wallet has more than enough BAT - follow up to 3212

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3640]
## Description 
Per additional comments on #3212 and some internal reports, some users are still experiencing this issue.

Sometimes users are getting a notification that alerts them that they don't have sufficient BAT to cover their auto contribution/recurring tips, but in fact, the user does have more than enough BAT for this. Subsequently, the contribution/recurring tips are not contributed.

## Steps to Reproduce

Unknown at this time.

## Actual result:
You get notification below 3 days prior. 

![image](https://user-images.githubusercontent.com/28145373/54055335-b8b36d80-41ba-11e9-93d2-13e2f350be33.png)

At time of contribution, your contribution won't go through, you will get the below message:
<img width="399" alt="Screen Shot 2019-03-14 at 10 30 21 AM" src="https://user-images.githubusercontent.com/28145373/54388702-b0ed4080-4674-11e9-857c-e57fc86b17da.png">

## Expected result:
Notification should not be shown when it is not needed.

## Reproduces how often: 

unsure

## Brave version (brave://version info)

Brave | 0.60.48 Chromium: 72.0.3626.121 (Official Build) (64-bit)
-- | --
Revision | da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883}
OS | Mac OS X

Additional versions as well.

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? unsure

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
https://github.com/brave/brave-browser/issues/3212#issuecomment-467392683
https://github.com/brave/brave-browser/issues/3212#issuecomment-470521362
https://github.com/brave/brave-browser/issues/3212#issuecomment-470627332

**Comment by mightypenguin** [comment]
I just got an alert that I Auto Contributed 1.5 BAT!
It does have a warning about how most of my BAT is to contributors that haven't signed up yet.
I didn't realize that could trigger this warning?

**Comment by Miyayes** [comment]
+1 from Reddit: https://www.reddit.com/r/BATProject/comments/b0dh3x/insufficient_funds_but_thats_not_true/

+1 from my personal experience as well.

**Comment by LaurenWags** [comment]
+1 from https://community.brave.com/t/no-monthly-rewards-or-tipping-possible/43571/5

**Comment by LaurenWags** [comment]
@mightypenguin to confirm, you're on version 0.61.51? Another user reported that after updating to 0.61.x they were able to contribute. Unsure if this will work for everyone, and unfortunately, we will have to just wait until contribution time comes in. Anyhow - glad you were able to contribute! I am not sure what you mean by triggering a warning? If you mean a message like this 
![Screen Shot 2019-03-14 at 4 45 31 PM](https://user-images.githubusercontent.com/28145373/54390343-a3d25080-4678-11e9-87d0-1dedf7e53202.png)
then this is expected if you were contributing some amount to creators who have not yet verified with Brave.

**Comment by LaurenWags** [comment]
@NejcZdovc I just experienced this on a new-ish (about a month ago) dev profile - my personal one. I don't have any recurring monthly tips set up, my wallet balance is 39 BAT and my monthly auto contribute budget is 20 BAT. If there's any other info I can provide let me know.

![Screen Shot 2019-03-19 at 11 55 22 AM](https://user-images.githubusercontent.com/28145373/54621357-01321d00-4a3e-11e9-8f59-0e832494065a.png)

**Comment by disfit** [comment]
Can confirm this on Linux platform. Had my monthly contribution go through in January and got the same message as @LaurenWags for February and March: see below. (Sorry, did not have time to post this earlier.

Currently on: Version 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)
OS: Linux Mint 18.3  Cinnamon 64-bit, kernel 4.15.0-46-generic

On February 19th:
![Screenshot from 2019-02-19 05-54-43](https://user-images.githubusercontent.com/25134539/54778979-588ae580-4c16-11e9-90f6-002501c079ba.png)
![Screenshot from 2019-02-19 05-55-23](https://user-images.githubusercontent.com/25134539/54778980-588ae580-4c16-11e9-85a1-cfbcfe3b9010.png)

On March 18th (3 days prior to contribution date):
![Screenshot from 2019-03-18 13-04-14](https://user-images.githubusercontent.com/25134539/54779043-853efd00-4c16-11e9-9db0-bb0a24488011.png)
![Screenshot from 2019-03-18 13-05-33](https://user-images.githubusercontent.com/25134539/54779044-85d79380-4c16-11e9-935b-846228dd9ede.png)

And this morning March 21th:
![Screenshot from 2019-03-21 07-14-21](https://user-images.githubusercontent.com/25134539/54779081-9b4cbd80-4c16-11e9-803b-3c8d74bdd585.png)
![Screenshot from 2019-03-21 07-14-55](https://user-images.githubusercontent.com/25134539/54779082-9b4cbd80-4c16-11e9-9b7c-973e4de9a68b.png)

If there is anything I can add to this, please let me know.

**Comment by bsclifton** [comment]
Updated to 0.62.x after https://github.com/brave/brave-core/pull/2116 was merged
cc: @ryanml

**Comment by LaurenWags** [comment]
@NejcZdovc @ryanml - test plan mentions changing `reconcileStamp` https://github.com/brave/brave-core/pull/2028 however, we do not test with this (there were issues previously) so we always test reconcile with `reconcile-interval` flag. can one of you confirm if we should be using with `reconcileStamp` or `reconcile-interval` flag?
cc @brave/legacy_qa

**Comment by NejcZdovc** [comment]
I think should work with `reconcile-interval` flag

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.62.49 Chromium: 73.0.3683.86 (Official Build) (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Linux

Used test plan from https://github.com/brave/brave-core/pull/2028 , but used `--rewards=staging=true,reconcile-interval=1` flag instead. Tested on staging server.

Sufficient funds
![image](https://user-images.githubusercontent.com/34715963/55345246-b689b980-54af-11e9-8cd5-e5e1299e09d3.png)

Insufficient funds
![image](https://user-images.githubusercontent.com/34715963/55345203-9fe36280-54af-11e9-87ed-5fe297ba171f.png)

**Comment by FelschR** [comment]
Just had this issue again today with v0.62.50.

**Comment by disfit** [comment]
Same here running on Version 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit):

Insufficient funds | Your Brave Rewards account is waiting for a deposit. 4/18/2019

Next contribution date is 4/20/2019

Wallet contains 778.9 BAT

Auto-contribute is set on signed on / verified publishers.

**Comment by LaurenWags** [comment]
@FelschR @disfit we're tracking additional fixes for this with these issues: https://github.com/brave/brave-browser/issues/4090 and https://github.com/brave/brave-browser/issues/3897
