### ISSUE TITLE
[iOS] Update UX with advanced server selection 

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-browser#36409]
This issue is to update `VPN server selection` page with more details provided on https://connect-api.guardianapp.com/api/v1.3/servers/all-server-regions/city-by-country

We need help with the design. 

The Android counterpart  https://github.com/brave/brave-browser/issues/36277

Design mockups https://www.figma.com/file/J4LKBMftiWhqromRWfUQLG/VPN---Advanced-server-selection?type=design&node-id=1-27&mode=design&t=X5Sc1t3UMuOKdCvK-0

**Comment by bsclifton** [comment]
Desktop https://github.com/brave/brave-browser/issues/38186
Android https://github.com/brave/brave-browser/issues/36277

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.69 (162)`

#### New users

- Ensured VPN paywall is showing up from settings menu as well as hamburger menu.
- Ensured enabling VPN via IAP is successful.
- Ensured enabling VPN via restoring credentials is successful.
- Ensured that `Automatic` switch is selected by default after enabling VPN.
- Ensured that advanced server selection list is shown as well as update dialog when disabling automatic server switch.
- Ensured that update dialog is shown when manually selecting server.
- Ensured that the city selection is shown after clicking on the `i` in the server list.
- Ensured that optimal setting is enabled by default for city selection. 

Example | Example | Example | Example | Example | Example | Example
-|-|-|-|-|-|-
![IMG_7192](https://github.com/user-attachments/assets/07386d9e-865f-445a-a2ac-e078a8895a04) | ![IMG_7193](https://github.com/user-attachments/assets/5be462dd-0372-49a8-9792-4264a85891b7) | ![IMG_7194](https://github.com/user-attachments/assets/5c336f8f-f873-49b1-a9e8-ce6aa6c8ffc5) | ![IMG_7195](https://github.com/user-attachments/assets/7c564b52-2395-4499-bca6-462702f7911a) | ![IMG_7196](https://github.com/user-attachments/assets/dfee059a-d633-4ddf-8d4b-8b0823d5a8b1) | ![IMG_7197](https://github.com/user-attachments/assets/62d9a07c-64e2-4fc2-a935-1f52c2e9e40f) | ![IMG_7198](https://github.com/user-attachments/assets/6cd2ae9b-b4df-4bda-8255-d9413a80a525)
![IMG_7199](https://github.com/user-attachments/assets/88bde3ea-9e3e-464c-be79-b3e641d645b9) | ![IMG_7200](https://github.com/user-attachments/assets/0dbcc543-5a4c-4ddc-8f02-f8edb39d05b8) | ![IMG_7201](https://github.com/user-attachments/assets/83365d5f-2c52-4f96-b075-9667c6b9ef84) | ![IMG_7202](https://github.com/user-attachments/assets/e4341b1f-9fda-4d94-983f-243562174502) | ![IMG_7203](https://github.com/user-attachments/assets/4d78d461-7e3d-4f5d-ba39-253e84007414) | ![IMG_7204](https://github.com/user-attachments/assets/8c31e1c2-dfdf-498e-9238-9b136afc658f) | ![IMG_7205](https://github.com/user-attachments/assets/05609bbe-5689-4f77-a3ce-b3579203a1c8) | ![IMG_7206](https://github.com/user-attachments/assets/2f3b9820-13e7-4811-aa5d-3815111b3877)

#### Existing users

- Ensured that VPN status is retained when upgrading the app.
- Ensured that VPN preferences are retained when manually setting the region/server and then upgrading to 1.69.x.
- Ensured VPN preferences can be changed after upgrading with default settings (automatic).
- Ensured that resetting configuration is working. 

Example | Example | Example | Example | Example | Example | Example
-|-|-|-|-|-|-
![IMG_7211](https://github.com/user-attachments/assets/5cf92338-b8c8-4040-b9ac-123ac3dd1047) | ![IMG_7212](https://github.com/user-attachments/assets/91cd3d72-1a85-412c-8e92-4f0a707e7f0f) | ![IMG_7213](https://github.com/user-attachments/assets/9967bced-76f0-4781-a83e-82c1e5548aa9) | ![IMG_7214](https://github.com/user-attachments/assets/707ca22f-5f44-4ba0-99eb-933da3245d4e) | ![IMG_7215](https://github.com/user-attachments/assets/c5ee27ca-b309-41a5-97f4-2819801edc79) | ![IMG_7216](https://github.com/user-attachments/assets/5d391c96-1610-48d8-b44f-8c0a5fd48383) | ![IMG_7217](https://github.com/user-attachments/assets/971079e6-191e-493c-be42-f7b704b6ecb3)
