### ISSUE TITLE
Upgrade from Chromium122.0.6261.69 to Chromium 122.0.6261.94

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#36404]
# Minor Chromium bump

https://chromium.googlesource.com/chromium/src/+log/122.0.6261.69..122.0.6261.94?pretty=fuller&n=10000

# QA tests:

* Check branding items
* Check for version bump

# Additional checks:
* No specific code changes in Brave (only line number changes in patches)

**Comment by kjozwiak** [comment]
The above requires `1.63.165` or higher for `1.63.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy Tab S8 Ultra` running `Android 14` using the following build(s):

```
Brave | 1.63.165 Chromium: 122.0.6261.94 (Official Build) (64-bit)
--- | ---
Revision | fed0fcc915f6d9e1db871202f0304c8d582a73de
OS | Android 14; Build/UP1A.231005.007; 34; REL
```

![Screenshot_20240227_231722_Brave](https://github.com/brave/brave-browser/assets/2602313/38bf779a-c082-4a28-88ea-e43f3a267b22)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.63.165 Chromium: 122.0.6261.94 (Official Build) (64-bit)
-- | --
Revision | fed0fcc915f6d9e1db871202f0304c8d582a73de
OS | Windows 10 Version 22H2 (Build 19045.4046)
```
![image](https://github.com/brave/brave-browser/assets/38657976/357b4549-3170-45fd-aa05-26a62966b77e)

**Comment by btlechowski** [comment]
Verified with

Brave | 1.63.165 Chromium: 122.0.6261.94 (Official Build) (64-bit)
-- | --
Revision | fed0fcc915f6d9e1db871202f0304c8d582a73de
OS | Linux



![image](https://github.com/brave/brave-browser/assets/34715963/8518a000-b322-48f5-a1dc-8aa8da4bff7f)

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.63.165 Chromium: 122.0.6261.94 (Official Build) (x86_64)
-- | --
Revision | fed0fcc915f6d9e1db871202f0304c8d582a73de
OS | macOS Version 13.6.4 (Build 22G513)
```

<img width="1196" alt="Screenshot 2024-02-28 at 8 11 26 AM" src="https://github.com/brave/brave-browser/assets/28145373/536d64b1-43d2-4cfb-8241-ca2b96ab9116">
