### ISSUE TITLE
Brave classes should not use `content` namespace or `brave/content/**` directory

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#3641]
there are some existing files in `brave-core/content/..` that should be moved out and the `content` directory should be removed

**Comment by bsclifton** [comment]
Looks like only a handful of icons (one icon, different sizes) are using this path now for Android. 
See https://github.com/brave/brave-core/tree/master/content/public/android/java/res

cc: @deeppandya 

I'll close this issue as I think the main ask is done
