### ISSUE TITLE
[Follow up to #36323] `Brave.AIChat.NewUserReturning` metric exists with `Fresh profile`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#36410]
## Description 

Follow-up to #36323

## Steps to reproduce 

   1. Install and launch Brave (Fresh profile)
   2. Go through onboarding
   3. Go to `brave://local-state`
   4. Search for `Brave.AIChat.` > *Observe that `Brave.AIChat.NewUserReturning` exists*

## Actual result 

`Brave.AIChat.NewUserReturning` metric exists with `Fresh profile`.

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/5f59e6f9-f5c8-4536-b5d4-d8880e3e183e) | ![2](https://github.com/brave/brave-browser/assets/128532965/6a93ef3b-f1c3-4be8-bdf6-23c252173cf1) |

## Expected result

None of the metrics must exist with a `Fresh profile`.

## Issue reproduces how often 

`Easily reproduced`

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? YES
- Can you reproduce this issue with the current Play Store Beta version? YES
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM 
   - Device type (Phone, Tablet, Phablet): PHONE
   - Android version: ANY
   
## Brave version

```
Brave build: 1.63.164
Chromium: 122.0.6261.69 (Official Build) (64-bit) 
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
@hffvld This is expected, please see the explanation below:

![image](https://github.com/brave/brave-browser/assets/38657976/5b64b03a-403c-464d-a0e9-39db58705e18)

**Comment by hffvld** [comment]
Oh, thanks @GeetaSarvadnya 

I was confused by the test plan here https://github.com/brave/brave-core/pull/19569#issue-1835805432 which says `ensure none of the metrics exist`.

**Comment by GeetaSarvadnya** [comment]
@hffvld Please close the issue

**Comment by hffvld** [comment]
Based on `P3A` [Wiki page](https://github.com/brave/brave-browser/wiki/P3A) which @GeetaSarvadnya mentioned `Brave.AIChat.NewUserReturning` metric must exist and must be set to `0`.
