### ISSUE TITLE
[hackerone] preserve speedreader tag order

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#36415]
https://hackerone.com/bugs?subject=brave&report_id=2393627&view=new&substates%5B%5D=new&reported_to_team=&text_query=&program_states%5B%5D=2&program_states%5B%5D=3&program_states%5B%5D=4&program_states%5B%5D=5&sort_type=latest_activity&sort_direction=descending&limit=25&page=1

**Comment by stephendonner** [comment]
@boocmp can you please attach a testplan?  Thanks!

**Comment by boocmp** [comment]
Added in PR

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

```
Brave	1.65.87 Chromium: 123.0.6312.46 (Official Build) beta (x86_64) 
Revision	2babfcf82ebba4c5dc0146d2ca66229ffd3ac02d
OS	macOS Version 11.7.10 (Build 20G1427)
```

### Steps:

Test pages (https://boocmp.github.io/blog/csp_order_1.html, https://boocmp.github.io/blog/csp_order_2.html)


 one of the pages listed above in speedreader mode
Open DevTools
Remember the order of <meta http-equiv> and <base> elements in the <head>
Click 'view original'
Check the order of elements is not changed.
Check other page in the same manner.

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.65.87 Chromium: 123.0.6312.46 (Official Build) beta (64-bit)
-- | --
Revision | 2babfcf82ebba4c5dc0146d2ca66229ffd3ac02d
OS | Windows 10 Version 22H2 (Build 19045.4170)
```

**Comment by hffvld** [comment]
## IN PROGRESS...

Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240216.010 release-keys
Brave build: 1.65.96 
Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
```
---------------------------
<details>
<summary> Tags order case </summary>

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/22369#issue-2158707347
2. *Verify*

**ACTUAL RESULTS:**
- Verified the order of `<meta http-equiv>` and `<base>` elements in the `<head>`

---------------------------

|`Speedreader`is ON|`Speedreader` is OFF|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/972f92eb-17eb-4e3e-be81-36d737403c1d) | ![2](https://github.com/brave/brave-browser/assets/128532965/424d3049-b4dd-4794-903e-b16efccc928b) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/fbd1c3c0-2529-4aa2-b67d-fdea8c08cbf4) | ![2](https://github.com/brave/brave-browser/assets/128532965/de4a7f13-fa75-4c5d-a7f9-9c0b0103b0d7) |
</details>

<details>
<summary> Invalid meta tag case </summary>

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/22369#issue-2158707347
2. *Verify*

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|
| ![1]() | ![2]() |
| ![1]() | ![2]() |
</details>
