### ISSUE TITLE
[Follow up to PR #22293][L10n] `Send` button is overlapping the query/string because it wasn't moved to the left side of the text field for `RTL`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#36413]
## Description 

Follow-up to [#22293](https://github.com/brave/brave-core/pull/22293)

## Steps to reproduce 

   1. Change device language to any `RTL`, for example, `Arabic` or `Hebrew`
   2. Launch Brave
   3. Three-dot menu > `Leo`
   4. *Observe that the `Send` button is not mirrored for RTL and overlaps the string/query*

## Actual result 

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/76cb7e92-2c00-4472-9059-89d42f741c15) | ![2](https://github.com/brave/brave-browser/assets/128532965/4f916513-1ed1-4fd3-8778-639899a55d6e) |

The `Send` button overlaps the query/string because it wasn't moved to the left side of the text field for `RTL`.

## Expected result

The `Send` button must be moved to the left side of the text field for `RTL, so it will not overlap the string/query`.

## Issue reproduces how often 

`Easily reproduced`

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NO
- Can you reproduce this issue with the current Play Store Beta version? NO
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): PHONE
   - Android version: ANY
   
## Brave version

```
Brave build: 1.65.40 
Chromium: 122.0.6261.69 (Official Build) canary (64-bit) 
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.63.168` or higher for `1.63.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.63.168
Chromium: 122.0.6261.94 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/36413#issue-2157842556
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Send` button is on the left side of the text field for RTL.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/9682d043-c344-4e3a-adc6-fc4aafaab92d) | ![2](https://github.com/brave/brave-browser/assets/128532965/c0feb48d-f578-4218-8206-ddf5434993fd) | ![3](https://github.com/brave/brave-browser/assets/128532965/54216dd7-727f-4d97-b526-dcb5b5695267) | ![4](https://github.com/brave/brave-browser/assets/128532965/0a15f1f3-f957-40ab-b300-48994e1b1c27) |
