### ISSUE TITLE
Remove NFT tab from Filecoin account details view

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36428]
## Description: 
Remove NFT tab from Filecoin account details view

## Steps to Reproduce 
  1. Install 1.63 build
  2. Go to accounts
  3. Open Filecoin account
  4. Shows NFT option which should be hidden

## Actual result: 
<img width=300 src=https://github.com/brave/brave-browser/assets/17010094/20cac4a4-646d-45ec-bbd6-85c7e1c475fe>

## Expected result:
No NFT for Filecoin accounts

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 
All

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Mobile Safari? NA

### Additional Information

cc: @nuo-xu @StephenHeaps

**Comment by kjozwiak** [comment]
The above requires `1.63.167` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.4 running 1.63 (169)
- Verified steps from [brave/brave-core#22375](https://github.com/brave/brave-core/pull/223750
- Verified NFT row is removed from Filecoin account details view

https://github.com/brave/brave-browser/assets/17010094/6744e799-8efd-4b8a-9a63-55c70e8cdfa3
