### ISSUE TITLE
Connected Dapps text has extra padding

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36429]
## Description: 
Connected Dapps text has extra padding

## Steps to Reproduce 

   1. Install 1.63 build
   2. Open any account which doesn't have a connected site 
   3. Connected Dapps text is not left aligned 

## Actual result: 
<img width=400 src=https://github.com/brave/brave-browser/assets/17010094/b68aa6e0-e220-4269-b26a-1aacb938cf22>

## Expected result:
No padding should be left aligned to keep consistency

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 
All

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?NA
- Is the issue reproducible on the latest version of Mobile Safari? NA

### Additional Information

cc: @nuo-xu @StephenHeaps

**Comment by kjozwiak** [comment]
The above requires `1.63.169` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.4 running 1.63 (169)
- Verified steps from [brave/brave-core#22377](https://github.com/brave/brave-core/pull/22377)
- Verified Dapp connection empty state label is left aligned

https://github.com/brave/brave-browser/assets/17010094/2e8aa765-b62b-4a6a-a0e4-5f6456ebb620
