### ISSUE TITLE
Support fingerprint webauthn on OSX

### ISSUE THREAD

**Issue by corymcdonald** [brave/brave-browser#3642]
## Description 
For publishers we received a request from @tomlowenthal to implement webauthn as a sign in provider. However in the current release of Brave webauthn is not supported

https://webauthn.bin.coffee
https://webauthndemo.appspot.com

## Actual result:
On the [webauthn.bin.coffee](
https://webauthn.bin.coffee) site when you try and generate a login
```
Contacting token... please perform your verification gesture (e.g., touch it, or plug it in)

Note: Raw response in console.
Got error:
TypeError: Cannot read property 'response' of null

Failures: 1 TODOs: 0
```

## Expected result:
webauthn successfully works when trying to authenticate with a fingerprint reader

## Reproduces how often: 
Everytime

## Brave version (brave://version info)
All versions. 

## Test Plan
Specified here: https://github.com/brave/brave-core/pull/5539

### Additional Information

Essentially think it's related to removing `credentialManager`
https://github.com/brave/brave-core/pull/1896

**Comment by bbondy** [comment]
@corymcdonald I think this is working with our 0.61.x release with Chromium 73. Could you try?

**Comment by bbondy** [comment]
I think this fixes it actually which is live:
https://github.com/brave/brave-core/pull/1899

**Comment by corymcdonald** [comment]
I was able to get Yubikey to work in both
* Version 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit) 
* Version 0.63.13 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)


However I was not able to use my fingerprint as a way for UTF. So maybe this issue should be made a little more specific?

**Comment by bsclifton** [comment]
@corymcdonald please do update the issue to cover your case 😄

**Comment by mikegrima** [comment]
Not sure if this is related to this issue, or if I should submit a new one. Touch ID currently does not work for webauthn for the latest Brave release (it does work in Chrome).

To replicate, try using Touch ID on https://webauthn.me. I think one of the issues is that Brave does not ask you to permit the site access to Touch ID, which Chrome does. Because of this, Touch ID doesn't work :(

**Comment by corymcdonald** [comment]
This is still an issue. 😄 We want to support WebAuthn on the publishers so it would be nice to get this somewhere on the roadmap so it would be released on the Release version before the end of year @rebron

**Comment by mikegrima** [comment]
It's really unfortunate that I can't use TouchID on Brave. Other than this, it would have full feature parity with Chrome.

**Comment by MattDierick** [comment]
Same comment, WebAuthn is more and more used by IDaaS and MFA like Duo or OKTA.

**Comment by ChadKillingsworth** [comment]
Github has now enabled this functionality and next month over a hundred banks and credit unions will have it enabled for their sites. Really need this enabled.

**Comment by kimbim** [comment]
Need this to switch to Brave!

**Comment by stgarf** [comment]
I like this support added to Brave to continue using Brave at work since we've switched to Okta Verify with Touch ID for authentication. This works correctly in Chrome.

**Comment by bmreilly** [comment]
I'm required to use Duo to login at work - as are many others - without touchID i have to pull my phone out >20x a day to verify. This is causing me to seriously contemplate switching back to chrome....

**Comment by evanmhm** [comment]
I am also using Duo for school and I really wish I could use touchID in Brave :/

**Comment by MartinCanovas** [comment]
Many business use Okta for authentication and it would be great for the Brave community to have Touch ID supported.

**Comment by jumde** [comment]
Work in progress! Stay tuned 😄

**Comment by LaurenWags** [comment]
Verified passed on macOS 10.14.6 Mojave using

```
Brave | 1.11.68 Chromium: 83.0.4103.106 (Official Build) dev (64-bit)
-- | --
Revision | ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5539

* Reproduced the issue using `1.10.93` (does not request touch ID):
<img width="919" alt="1 10 93 reproduce" src="https://user-images.githubusercontent.com/28145373/85042276-04441d80-b159-11ea-8c80-2a19e02b71bc.png">

* Confirmed using 1.11.x touch ID is requested:
<img width="1006" alt="Screen Shot 2020-06-18 at 11 37 01 AM" src="https://user-images.githubusercontent.com/28145373/85042322-132ad000-b159-11ea-9283-6733bc200724.png">

* Confirmed able to complete the flow using either touch ID or yubikey on demo.yubico.com/u2f

cc @kjozwiak to check on Catalina

-----
