### ISSUE TITLE
Change "Go to Solana account" link to explorer.solana.com

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#36433]
## Description

Current: `solscan.io/...`

## New 

`https://explorer.solana.com/address/{{solana-address}}/tokens`

**Comment by kjozwiak** [comment]
The above requires `1.63.167` or higher for `1.63.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.63.168 Chromium: 122.0.6261.94 (Official Build) (x86_64)
-- | --
Revision | 08196d502fa95681adc6dd9fc06a04d0664ac538
OS | macOS Version 13.6.4 (Build 22G513)
```

**Comment by Uni-verse** [comment]
In progress on Android ARM

**Comment by Uni-verse** [comment]
Not applicable in 1.63 due to feature scheduled to be release in 1.64.x for Android. Removed `OS/Android` label and made a mentioned this issue in https://github.com/brave/brave-browser/issues/35334#issuecomment-1979706829
