### ISSUE TITLE
Fix incorrect brave icons colors in top toolbar on tab view transition

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#36438]
## Description 
https://github.com/brave/brave-browser/assets/30602739/16ef5337-7f99-47c1-b3d8-69b34b7edf5f

## Steps to reproduce 

   1. In light mode go to any dark web site (like reddit.com)
   2. While it's being loaded go to tab view
   3. In transition background of our icons will be still light for a while until eventually we get proper color

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by hffvld** [comment]
Verified on `Pixel 2 XL`, `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Pixel 2 XL / taimen-user  8.1.0 OPM2.171026.006.H1 release-keys
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 14 AP21.240216.010 release-keys
Brave build: 1.65.96 
Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
```

---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/36438#issue-2159306593
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the icons on the transition screen have the correct color

---------------------------

*Pixel 2 XL*

https://github.com/brave/brave-browser/assets/128532965/e71a374c-08cf-4b03-9c71-45d01b7ef00d

*Galaxy Tab S8*

https://github.com/brave/brave-browser/assets/128532965/393ecd84-8e95-4ee4-b5af-2ec9b3225b68

*Pixel 7*

https://github.com/brave/brave-browser/assets/128532965/00a63537-768a-47a4-a637-9ff7d9ac7ee3
