### ISSUE TITLE
Support using LiFi Quote in Swap

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#36436]
## Description 

Cross-chain swaps are supported by LiFi (added to `brave-core` in https://github.com/brave/brave-browser/issues/36335) but currently are disabled and not used in front-end. We'll need to update front-end for handling `LiFiQuote` model for desktop/android WebUI and iOS.

We should handle the swap quotes disclaimers change(s) in this issue as well. Slack Ref: https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1708974083632369

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.138 Chromium: 127.0.6533.100 (Official Build) beta (64-bit)
-- | --
Revision | 2569cce791e23282c250db59de277f2e81c33d9b
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#23731](https://github.com/brave/brave-core/pull/23731)
- Verified LiFi Quotes work as expected for Swap transactions

![image](https://github.com/user-attachments/assets/26cf5959-3848-4a1d-9622-d7d0422d2862) | ![image](https://github.com/user-attachments/assets/70fc6dc0-750e-4167-8296-66e32f061723) | ![image](https://github.com/user-attachments/assets/6cfe8f1d-3579-4cc5-b382-180b3c949529)
-- | -- | --

**Comment by srirambv** [comment]
Removing `OS/Android` label as Swaps is [broken](https://github.com/brave/brave-browser/issues/40524) on Android and a follow up issuehttps://github.com/brave/brave-browser/issues/40525  is logged.
