### ISSUE TITLE
Crash when selecting token to send

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36431]
## Description: 
Crash when selecting token to send

## Steps to Reproduce 
  1. Install 1.63 
  2. Open Account 
  3. Select Send from Account screen
  4. Token sheet shows up and browser crashes

## Actual result: 

https://github.com/brave/brave-browser/assets/17010094/0df528b9-37be-4be5-8e6b-89ce15529fa9

## Expected result:
No crash. Allow user to select token

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 
iPhone 13 (iOS 17.5)

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?NA
- Is the issue reproducible on the latest version of Mobile Safari? NA

### Additional Information

cc: @StephenHeaps @nuo-xu

**Comment by kjozwiak** [comment]
The above requires `1.63.173` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.4 running 1.63 (176)
- Verified steps from issue description
- Verified no crash when selecting token to Send

https://github.com/brave/brave-browser/assets/17010094/b43c20fb-e0b8-4e46-8d17-c7da7921636b
