### ISSUE TITLE
Google cannot work in China

### ISSUE THREAD

**Issue by zaoqi** [brave/brave-browser#3644]
I cannot download it

**Comment by srirambv** [comment]
Please edit issue and add more details. This one line doesn't help much

**Comment by bsclifton** [comment]
@zaoqi if you were able to add some more details (maybe some screenshots?) please do re-open it

I'm curious: is https://brave.com/download being blocked for you?

**Comment by zaoqi** [comment]
@bsclifton I cannot download it using Google Play.

**Comment by srirambv** [comment]
@zaoqi I think you are talking about Android. Not sure if you are able to install other apps via Google Play ?

**Comment by zaoqi** [comment]
@srirambv Google Play is blocked

**Comment by srirambv** [comment]
@zaoqi unfortunately there is nothing that we can do about Google play being blocked. However you can download the latest Brave browser from our Amazon repo for Android.  You can download it by visiting this [link](https://www.amazon.com/Brave-Software-Browser-Fast-AdBlock/dp/B01M27C0RQ/ref=sr_1_2?s=mobile-apps&ie=UTF8&qid=1477686541&sr=1-2) or you can visit brave.com/download and scroll down to the bottom of the page and click on the Amazon link there.
