### ISSUE TITLE
advices

### ISSUE THREAD

**Issue by davidp88** [brave/brave-browser#36440]
Sorry for repost,wait let all of your developers read it and then close or else mistakes will happen.If they completely think and work then bugs will be properly fixed

1.Think completely and work and that thinking should be done at once,do like this when writing also ,as little thinking causes mistakes.

2.think of each bit of how it can be improved but don't add useless and unnecessary features

3.Increase patience

4.do important work first

5.If u can't reproduce a bug normally then test thoroughly and try to reproduce for 2,3 times.

6.As far as possible try to reproduce bugs in win10 64bit as most of the users in the world use win10

7.also make the app look very beautiful by using beautiful toolbar icon's,nice looking breadcrumb bar etc..(read twice)

**Comment by bsclifton** [comment]
Thanks for the advice, @davidp88 😄 I'll be sure to share with the team

**Comment by davidp88** [comment]
forward it to ur whole team today itself or else u'll forget
