### ISSUE TITLE
Manual test run on macOS (Intel) for Tor 0.4.8.10 - Release #1

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36453]
### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
	- [x] Navigate to `brave.com` and `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the sites work correctly.
- [x] Load `brave.com` and `mail.protonmail.com` in a regular Window/Tab and ensure that clicking the `Tor` button in the URL bar correctly launches a Tor window and opens the appropriate `.onion` website.

### MacOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [x] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
	- [x] Navigate to `brave.com` and `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the sites work correctly.
- [x] Load `brave.com` and `mail.protonmail.com` in a regular Window/Tab and ensure that clicking the `Tor` button in the URL bar correctly launches a Tor window and opens the appropriate `.onion` website.

### MacOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [x] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
	- [x] Navigate to `brave.com` and `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the sites work correctly.
- [x] Load `brave.com` and `mail.protonmail.com` in a regular Window/Tab and ensure that clicking the `Tor` button in the URL bar correctly launches a Tor window and opens the appropriate `.onion` website.

### MacOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [x] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
	- [x] Navigate to `brave.com` and `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the sites work correctly.
- [x] Load `brave.com` and `mail.protonmail.com` in a regular Window/Tab and ensure that clicking the `Tor` button in the URL bar correctly launches a Tor window and opens the appropriate `.onion` website.

### MacOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [x] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
	- [x] Navigate to `brave.com` and `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the sites work correctly.
- [x] Load `brave.com` and `mail.protonmail.com` in a regular Window/Tab and ensure that clicking the `Tor` button in the URL bar correctly launches a Tor window and opens the appropriate `.onion` website.

### MacOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [x] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

**Comment by LaurenWags** [comment]
Verified for the below:

<details>
<summary>macOS 13.x Ventura x64 - InProgress</summary>

```
Brave | 1.63.165 Chromium: 122.0.6261.94 (Official Build) (x86_64)
-- | --
Revision | fed0fcc915f6d9e1db871202f0304c8d582a73de
OS | macOS Version 13.6.4 (Build 22G513)
```

Confirmed that the correct Tor component was being downloaded via --use-dev-goupdater-url:

SS

Confirmed that the Tor component was started when launching Tor and ensured Tor `0.4.8.10` was being used.
Confirmed that OpenSSL version is `3.0.13`
Confirmed that Zlib version is `1.3.1`

```

```

Confirmed that you can open the following domains in a Tor window without issues:

* brave.com
* https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/
* check.torproject.org (ensured that hard refreshing gets a new circuit/IP)

Confirmed the following sites opened via “Open in Tor” button from normal window and navigated to .onion URL in a Tor window:

* brave.com --> https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/
* https://account.proton.me/login --> https://account.protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/

Confirmed that codesign is valid:

```
laurenwags@Laurens-M1 1.0.72 % codesign -vvvv tor-0.4.8.10-darwin-brave-1 

```

Confirmed that the binary is notarized: 

```
laurenwags@Laurens-M1 1.0.72 % spctl -a -vv -t install tor-0.4.8.10-darwin-brave-1

```

</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using:

```
Brave | 1.63.165 Chromium: 122.0.6261.94 (Official Build) (x86_64)
-- | --
Revision | fed0fcc915f6d9e1db871202f0304c8d582a73de
OS | macOS Version 11.7.10 (Build 20G1427)
```


```
<SNIP
```


```
<SNIP>
```

```
<SNIP>
```


------

## Big Sur

Verification PASSED on `BIg Sur`

```


```

Ensured that the correct `Tor` component -- `Version: 1.0.43` -- was being downloaded via `--use-dev-goupdater-url`:

<screenshot>

Ensured that the Tor component was started when launching Tor and ensured `` was being used:

```
<SNIP>
```

Ensured that you can open the following domains in a Tor window without issues:
* `brave.com`
* `duckduckgo.com`
* `https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/`
* `check.torproject.org` (ensured that hard refreshing gets a new circut/IP)

Confirmed the following sites opened via "Open in Tor" button and navigated to `.onion` URLs:

* `brave.com` --> `https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/`
* `mail.protonmail.com` --> `https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/`

Ensured that the tor binary was correctly signed using `codesign`:

Verified the binary was signed:
```
<SNIP>
```

Verified the binary was also notarized:

```
<SNIP>
```

**Comment by kjozwiak** [comment]
#### **`macOS Senoma 14.3.1 x64`** - **PASSED**

Verification **PASSED** on `Win 10 x86` using the following build:


```
Brave | 1.63.165 Chromium: 122.0.6261.94 (Official Build) (x86_64)
--- | ---
Revision | fed0fcc915f6d9e1db871202f0304c8d582a73de
OS | macOS Version 14.3.1 (Build 23D60)
```

<details>
<summary>macOS Senoma 14.3.1 x64 - PASSED</summary>

Launched `1.63.165 Chromium: 122.0.6261.94` using `--enable-logging=stderr --use-dev-goupdater-url` and confirmed the following versions:

* `tor` binary ` 0.4.8.10`
* `Brave Tor Client Updater (Mac) - Version: 1.0.72`
* `Libevent` - `2.1.12-stable`
* `OpenSSL` - `3.0.13`
* `Zlib` - `1.3.1`

![Screenshot 2024-03-01 at 12 28 03 AM](https://github.com/brave/brave-browser/assets/2602313/58c59c31-ac06-462b-aaf6-4ee443441209)

```Mar 01 00:27:17.299 [notice] Tor 0.4.8.10 running on Darwin with Libevent 2.1.12-stable, OpenSSL 3.0.13, Zlib 1.3.1, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
Mar 01 00:27:17.299 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Mar 01 00:27:17.299 [notice] Read configuration file "/Users/kjozwiak/Library/Application Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.72/tor-torrc".
Mar 01 00:27:17.299 [notice] Read configuration file "/Users/kjozwiak/Library/Application Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.72/tor-torrc".
Mar 01 00:27:17.301 [notice] Opening Socks listener on 127.0.0.1:0
Mar 01 00:27:17.301 [notice] Socks listener listening on port 49837.
Mar 01 00:27:17.301 [notice] Opened Socks listener connection (ready) on 127.0.0.1:49837
Mar 01 00:27:17.301 [notice] Opening Control listener on 127.0.0.1:0
Mar 01 00:27:17.301 [notice] Control listener listening on port 49838.
Mar 01 00:27:17.301 [notice] Opened Control listener connection (ready) on 127.0.0.1:49838
[2970:41987:0301/002717.301798:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
[2970:41987:0301/002717.301899:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
[2970:41987:0301/002717.303522:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
[2970:41987:0301/002717.303838:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
Mar 01 00:27:17.000 [notice] Bootstrapped 0% (starting): Starting
Mar 01 00:27:17.000 [notice] Starting with guard context "default"
Mar 01 00:27:17.000 [notice] New control connection opened from 127.0.0.1.
Mar 01 00:27:17.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
Mar 01 00:27:17.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
Mar 01 00:27:17.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
Mar 01 00:27:17.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
Mar 01 00:27:17.000 [notice] Bootstrapped 20% (onehop_create): Establishing an encrypted directory connection
Mar 01 00:27:18.000 [notice] Bootstrapped 25% (requesting_status): Asking for networkstatus consensus
Mar 01 00:27:18.000 [notice] Bootstrapped 30% (loading_status): Loading networkstatus consensus
Mar 01 00:27:20.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
Mar 01 00:27:20.000 [notice] Bootstrapped 40% (loading_keys): Loading authority key certs
Mar 01 00:27:21.000 [notice] The current consensus has no exit nodes. Tor can only build internal paths, such as paths to onion services.
Mar 01 00:27:21.000 [notice] Bootstrapped 45% (requesting_descriptors): Asking for relay descriptors
Mar 01 00:27:21.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/7603, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.)
Mar 01 00:27:21.000 [notice] Bootstrapped 50% (loading_descriptors): Loading relay descriptors
Mar 01 00:27:22.000 [notice] The current consensus contains exit nodes. Tor can build exit and internal paths.
Mar 01 00:27:24.000 [notice] Bootstrapped 56% (loading_descriptors): Loading relay descriptors
Mar 01 00:27:24.000 [notice] Bootstrapped 62% (loading_descriptors): Loading relay descriptors
Mar 01 00:27:24.000 [notice] Bootstrapped 70% (loading_descriptors): Loading relay descriptors
Mar 01 00:27:24.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
Mar 01 00:27:25.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
Mar 01 00:27:25.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
Mar 01 00:27:25.000 [notice] Bootstrapped 100% (done): Done```

Ensured that you can open the following domains in a Tor window without issues:

* brave.com
* duckduckgo.com
* https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion
* check.torproject.org (ensured that hard refreshing gets a new circuit/IP)

Confirmed the following sites opened via "Open in Tor" button and navigated to .onion URL:

* brave.com --> https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion
* mail.protonmail.com --> https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion

Confirmed that `codesign -vvvv` is valid as per the following:

```
kjozwiak@Kamils-MBP-2 ~ % codesign -vvvv ~/Library/Application\ Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.72/tor-0.4.8.10-darwin-brave-1
/Users/kjozwiak/Library/Application Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.72/tor-0.4.8.10-darwin-brave-1: valid on disk
/Users/kjozwiak/Library/Application Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.72/tor-0.4.8.10-darwin-brave-1: satisfies its Designated Requirement
```

Confirmed that `spctl -a -vv -t install` is valid as per the following:

```
kjozwiak@Kamils-MBP-2 ~ % spctl -a -vv -t install ~/Library/Application\ Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.72/tor-0.4.8.10-darwin-brave-1
/Users/kjozwiak/Library/Application Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.72/tor-0.4.8.10-darwin-brave-1: accepted
source=Notarized Developer ID
origin=Developer ID Application: Brave Software, Inc. (KL8N8XSYF4)
```

</details>
