### ISSUE TITLE
Browser freezes when quickly dragging hyperlinked text or button

### ISSUE THREAD

**Issue by Jaxus1** [brave/brave-browser#3645]
## Description 

Brave Browser (Dev build, for Linux) freezes sometimes when you drag a button / hyperlinked text (one that goes to another page), and stop dragging it just before it loads, it will freeze the whole browser completely. This has happened to me twice. The first time, i had no idea. The second time, I accidentally dragged a button and it showed a gray box and froze the browser.

## Steps to Reproduce
Go to a new webpage, quickly drag a button or hyperlinked text to a random part of the page and un-drag it.
I was unable to reproduce the bug.

## Actual result:
Browser did not freeze

## Expected result:
Browser Freezes

## Reproduces how often: 
Does not reproduce often at all. May seem like a random occurrence to a user.

## Brave version (brave://version info)
0.62.16 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)
cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
Linux

### Reproducible on current release:
Only have experienced this on Dev build, because i use that most often.

### Website problems only:  
- Unsure if the issue resolves itself when disabling Brave Shields
- Unsure if the issue reproducible on the latest version of Chrome

**Comment by rebron** [comment]
Closing. We need better reproducible steps.
