### ISSUE TITLE
Manual test run on Linux for Tor 0.4.8.10 - Release #1

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36456]
## Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
	- [x] Navigate to `brave.com` and `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the sites work correctly.
- [x] Load `brave.com` and `mail.protonmail.com` in a regular Window/Tab and ensure that clicking the `Tor` button in the URL bar correctly launches a Tor window and opens the appropriate `.onion` website.

### Linux
- [ ] Navigate to `<user-data-dir>/biahpgbdmdkfgndcmfiipgcebobojjkp`
- [ ] Run `ldd tor-<version-tor>-linux-brave-<version-brave>` to confirm tor client is a static binary

**Comment by btlechowski** [comment]
Verified with

Brave | 1.63.165 Chromium: 122.0.6261.94 (Official Build) (64-bit)
-- | --
Revision | fed0fcc915f6d9e1db871202f0304c8d582a73de
OS | Linux


```
Feb 29 16:01:49.926 [notice] Tor 0.4.8.10 running on Linux with Libevent 2.1.12-stable, OpenSSL 3.0.13, Zlib 1.3.1, Liblzma N/A, Libzstd N/A and Glibc 2.35 as libc.

```

![image](https://github.com/brave/brave-browser/assets/34715963/3f4577ee-d36d-4354-8e09-5911769183f7)
