### ISSUE TITLE
Follow up to PR [21934] - Wireguard is still in connected state after the BraveVPN Wireguard service is killed.

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#36451]
## Description 

Found the issue while verifying https://github.com/brave/brave-core/pull/21934. `Can't connect to server modal` when I try to trigger IKEv2 fallback window.  Tried twice and each time I got the error. 

## Steps to Reproduce

1. Installed 1.65.42
2. launched Brave
3. connected to Wireguard VPN
4. killed BraveVPN Wireguard service several times in the task manager  to trigger the window
5. after few attempts got the IKEv2 fallback window
6. clicked Change settings and the window is dismissed
7. here noticed VPN button is green but when clicked it's in disconnected state
8. connected and disconnected
9. tried to connect again.

## Actual result:

Got Can't connect to server modal

https://github.com/brave/brave-browser/assets/98358127/7596c950-00e5-4418-8e54-bf3020fe3644

## Expected result:
Should be connected to IKEv2 VPN

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.65.42 Chromium: 122.0.6261.94 (Official Build) nightly (64-bit)
-- | --
Revision | 169e4fc2ee1896cd009c59e7b537220ba880a882
OS | Windows 11 Version 23H2 (Build 22631.3155)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@simonhong @bsclifton 
cc: @stephendonner

**Comment by bsclifton** [comment]
Possible duplicate of https://github.com/brave/brave-browser/issues/33582

We might not be capturing events when disconnect happens

**Comment by mattmcalister** [comment]
is this still happening @MadhaviSeelam ?

**Comment by MadhaviSeelam** [comment]
> is this still happening [@MadhaviSeelam](https://github.com/MadhaviSeelam) ?

@mattmcalister Could not reproduce in 1.71.112. Closing the issue. 


https://github.com/user-attachments/assets/eb01bb0e-0550-4a4f-817e-587dac63512b
