### ISSUE TITLE
Manual test run on macOS (arm64) for Tor 0.4.8.10 - Release #1

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36454]
### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
	- [x] Navigate to `brave.com` and `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the sites work correctly.
- [x] Load `brave.com` and `mail.protonmail.com` in a regular Window/Tab and ensure that clicking the `Tor` button in the URL bar correctly launches a Tor window and opens the appropriate `.onion` website.

### MacOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [x] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

### Tor Client Updater

- [ ] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [ ] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [ ] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [ ] Navigate to `check.torproject.org` and verify that tor is working successfully.
	- [ ] Navigate to `brave.com` and `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the sites work correctly.
- [ ] Load `brave.com` and `mail.protonmail.com` in a regular Window/Tab and ensure that clicking the `Tor` button in the URL bar correctly launches a Tor window and opens the appropriate `.onion` website.

### MacOS
- [ ] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [ ] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [ ] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

**Comment by LaurenWags** [comment]
Verified for the below:

<details>
<summary>macOS 14.4 Sonoma arm64 - InProgress</summary>

Verified on macOS 14.4 arm64 using the following build:

```
Brave	1.63.165 Chromium: 122.0.6261.94 (Official Build) (arm64) 
Revision	fed0fcc915f6d9e1db871202f0304c8d582a73de
OS	macOS Version 14.4 (Build 23E5191e)
```

Confirmed that the correct Tor component was being downloaded via --use-dev-goupdater-url:

![M1](https://github.com/brave/brave-browser/assets/28145373/d99d8e10-6929-40df-8355-0236f31d161e)

Confirmed that the Tor component was started when launching Tor and ensured Tor  was being used.
Confirmed that OpenSSL version is 
Confirmed that Zlib version is 

```

```

Confirmed that you can open the following domains in a Tor window without issues:

* brave.com
* https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/
* check.torproject.org (ensured that hard refreshing gets a new circuit/IP)

Confirmed the following sites opened via “Open in Tor” button from normal window and navigated to .onion URL in a Tor window:

* brave.com --> https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/
* https://account.proton.me/login --> https://account.protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/

Confirmed that codesign is valid:

```
laurenwags@Laurens-M1 1.0.64 % codesign -vvvv tor-0.4.7.13-darwin-brave-1 

```

Confirmed that the binary is notarized: 

```
laurenwags@Laurens-M1 1.0.64 % spctl -a -vv -t install tor-0.4.7.13-darwin-brave-1 

```

</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```


```
