### ISSUE TITLE
Limit permission duration on private tabs

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#36462]
We're adding the ability to enable Brave Wallet in private tabs. In order to complete this PR https://github.com/brave/brave-core/pull/21756#top we'll need to limit the duration option to "Until I close this site" since permission history is sandboxed to the session on private tabs.

![Image](https://github.com/brave/brave-browser/assets/318119/3ca0c7f6-e1e9-4bbf-ba8d-46a57571c7e1)

Instead of showing the duration drop-down we should show the label "Until I close this site" under "Permission duration"

Use `IsPrivateWindow()` API that is exposed under the branch for this feature.

**Comment by Douglashdaniel** [comment]
Confirmed `Permission Duration` is limited to `Until I close this site` in `Private Tab`.

https://github.com/user-attachments/assets/2c557279-8585-4787-b59a-01bba88e0180
