### ISSUE TITLE
Tweak Leo right click tools

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#36469]
From @LorenzoMinto 
- Renaming `Leo Tools` to `Leo AI Tools`
- Remove `Simplify` option
- `Social media post` section could be renamed to `Social media` so the follow-up menu is `Short post` and `Long post`, and there’s more room to expand in the future if needed. This also with make the follow-up menu less wide.
- Remove `Paraphrase` & `Improve` in `Quick Actions`
- Add persuasive tone

<img width="679" alt="Screenshot 2024-02-29 at 12 23 36 PM" src="https://github.com/brave/brave-browser/assets/4730197/3271eb4f-3e6f-4bee-ba60-ef4870ed90c6">

**Comment by kjozwiak** [comment]
The above requires `1.64.96` or higher for `1.64.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `PASSED` using 


```
Brave | 1.64.96 Chromium: 122.0.6261.111 (Official Build) beta (x86_64)
-- | --
Revision | fb9feca2d1f25ea20265752e8ecdf548a6925bd4
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.64.96`
2. launched Brave
3. loaded `vox.com`
4. clicked on `https://www.vox.com/culture/24091203/gen-z-aging-panic-sephora-tweens-how-old-do-i-look`
5. selected some text on the page
6. context-clicked

Confirmed top-level menu item is renamed to `Leo AI tools` [sic - looks like I need a followup issue to for s/tools/Tools, at least on `macOS`)
<details>

<img width="537" alt="Screen Shot 2024-03-06 at 10 56 00 AM" src="https://github.com/brave/brave-browser/assets/387249/2800afa7-2162-4eb0-901b-5a7570974de9">

</details>


Confirmed `Paraphrase` and `Improve` have been moved from `Quick actions` to `Rewrite`
<details>

<img width="200" alt="Screen Shot 2024-03-06 at 10 56 04 AM" src="https://github.com/brave/brave-browser/assets/387249/91d6132d-8f08-4d12-8757-94bf5e4a4cf7">

</details>

Confirmed addition of `Persuasive` to the `Change tone >` flyout menu
<details>

<img width="268" alt="Screen Shot 2024-03-06 at 11 02 28 AM" src="https://github.com/brave/brave-browser/assets/387249/1ab8529e-c1c2-40b4-a02b-630cf51c968c">

</details>

**Comment by stephendonner** [comment]
## Verified `PENDING` using

```
Brave	1.64.104 Chromium: 123.0.6312.46 (Official Build) (64-bit) 
Revision	0ca3d372cf8aab96fafdd75f5c5c8d2012bc0cc6
OS	Linux
```
