### ISSUE TITLE
[Android] YT Improvements - Setting to remove Shorts

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#36465]
## Description
There is a new filter list available to block YouTube Shorts:
https://github.com/brave/adblock-lists/blob/master/brave-lists/yt-shorts.txt

Add a toggle to enable/disable this filter list under settings -> media:

```
Block YouTube Shorts
Blocks Shorts from the home page, trending page and search results on youtube.com.
```

cc @deeppandya @ryanbr @anthonypkeane

**Comment by deeppandya** [comment]
@timchilds should it be enabled by default ?

**Comment by deeppandya** [comment]
@ryanbr can we add `yt-shorts.txt` into https://github.com/brave/adblock-resources/blob/f614b0f63745e2f64c350f47baa0f16efe5ec7fc/filter_lists/list_catalog.json ?

**Comment by deeppandya** [comment]
> @deeppandya the toggle should be off (disabled) by default.
> 
> We should not block Shorts by default - blocking should be user initiated.

yeah i agree. Thanks

**Comment by kjozwiak** [comment]
The above requires `1.66.97` or higher for `1.66.x` verification(s) 👍 @hffvld @Uni-verse can also find some STR/Cases that were used for `Nightly` verification via https://github.com/brave/brave-core/pull/23130#issuecomment-2089219855.

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 14 AP31.240322.023 release-keys
Brave build: 1.66.95
Chromium: 124.0.6367.91 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Launch Brave > Three-dot menu > Settings
2. Media > *Verify that the `Block YouTube Shrots` toggle switch is there*
3. Enable `Block YouTube Shrots` toggle switch > Close the settings
4. Go to www.youtube.com > *Verify that `Shorts` are not shown on the `Home` tab*
5. Tap the `Compass`/`Hamburger menu` button > Trending > *Verify that `Trending Shorts` are not shown*
6. Tap the `search` button on YT > Send a query > *Verify that `Shorts` are not shown*

**ACTUAL RESULTS:**
- Verified that the `Block YouTube Shrots` toggle switch is shown in the `Media` section
- Verified that `Shorts` are not shown on the YT `Home` tab
- Verified that `Trending Shorts` are not shown on the YT `Trending` tab
- Verified that `Shorts` are not shown in the `search` results

---------------------------

<details>
<summary> Galaxy Tab S8 </summary>

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/e1bf9015-a0fe-4e0f-b427-2f2da57914a5) | ![2](https://github.com/brave/brave-browser/assets/128532965/1139a2ee-6c32-49f4-9d05-a12c2c9b3cdc) | ![3](https://github.com/brave/brave-browser/assets/128532965/6be4c257-1b8e-4f6d-b560-6993ad0a28ce) | ![4](https://github.com/brave/brave-browser/assets/128532965/da7d985d-1a83-41f2-870c-dc1c120c018e) |

https://github.com/brave/brave-browser/assets/128532965/a4988699-40c1-4c65-afb8-18d71aa5aac8

</details>

<details>
<summary> Pixel 7 </summary>

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/dea8c00f-5cdf-4ca0-b081-b459ad1ca112) | ![2](https://github.com/brave/brave-browser/assets/128532965/142105fc-3faa-4246-a4c8-c0097f7ab226) | ![3](https://github.com/brave/brave-browser/assets/128532965/971d422e-ca52-473b-b31a-b6daa7c5e829) | ![4](https://github.com/brave/brave-browser/assets/128532965/60041808-f3a7-4d5b-874e-8a75d1c31975) |

https://github.com/brave/brave-browser/assets/128532965/a4d4cff1-70da-45c4-919a-3e6e69f1040d
</details>

**Comment by anthonypkeane** [comment]
@timchilds can you check out https://github.com/brave/brave-browser/issues/36465#issuecomment-2093474959 and see if that is possible? Thanks

**Comment by deeppandya** [comment]
@timchilds @saksham-81  https://github.com/brave/brave-browser/issues/36465#issuecomment-2099389742 is updated. we are not showing `Shorts` icon now. Thanks to @ryanbr

**Comment by saksham-81** [comment]
Thank you, @timchilds, @ryanbr, @anthonypkeane, and @deeppandya, for the quick update.

**Comment by KvalheimRacing** [comment]
Unhook also have an option to make YT main screen completely empty. I didn't find any option to enable this in brave. Would help productivity and removing distraction
