### ISSUE TITLE
Transaction Details not updating transaction status automatically

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#36468]
## Description: 

Transaction status is not updated when Transaction Details modal is open.

## Steps to Reproduce 
  1. Confirm a transaction
  2. Close transaction modal quickly (before it leaves `Submitted` state), switch to activity tab and open Transaction Details
  3. Slightly pull modal down (don't fully dismiss) to see Activity tab correctly update transaction status. Wait for loading spinner to remove from the transaction.
    - You might have to do release modal pull and try again, UI may not update during user interaction .
  4. Observe Transaction Details modal does not update status from `Submitted`
  5. Dismiss and re-open the same transaction to see `Confirmed` (or `Error`) state.

## Actual result: 

https://github.com/brave/brave-browser/assets/5314553/9831dcb1-a30e-4f08-a28f-f94e10af7468

## Expected result:

Transaction Details view should update status automatically, not require dismiss & re-open.

## Reproduces how often: 

Easily reproduced

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari? 

### Additional Information

cc @jamesmudgett

**Comment by kjozwiak** [comment]
The above requires `1.63.169` or higher for `1.63.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.4 running 1.63 (169)
- Verified steps from [brave/brave-core#22405](https://github.com/brave/brave-core/pull/22405)
- Verified Transaction details screen updates status when transaction confirms/error out

https://github.com/brave/brave-browser/assets/17010094/a4025166-76bf-4c40-9a75-ee5ea1e1138f
