### ISSUE TITLE
Correct text wrapping on signing confirmation panel.

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#36461]
visit portfolio.metamask.io and attempt to enable notifications.

![Image](https://github.com/brave/brave-browser/assets/318119/d4fe34f1-3530-4774-96a6-f283b99ecdb7)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | 2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from [brave/brave-core#22399](https://github.com/brave/brave-core/pull/22399)
- Verified Signing confirmation panel text is properly wrapped 

https://github.com/brave/brave-browser/assets/17010094/82fd4299-2ec4-4738-a4fc-595e66782d33
