### ISSUE TITLE
Duplicate sites in auto-contribute list.

### ISSUE THREAD

**Issue by jnki** [brave/brave-browser#3647]
## Description 

Duplicate supported sites showing in my auto-contribute list.

## Steps to Reproduce

I don't know how to reproduce the issue.
There were simply several listings of the same site in the list.

## Actual result:

![image](https://user-images.githubusercontent.com/17442109/54085131-1a4a1800-4332-11e9-870b-177b89ef566d.png)

## Expected result:
No duplicates

## Reproduces how often: 

No steps to reproduce

## Brave version (brave://version info)

Brave | 0.60.48 Chromium: 72.0.3626.121 (Official Build) (64-bit)
Revision | da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883}
OS | Windows

### Additional Information

When I removed one of the duplicates from the list, all listings of that site were removed.

Also, unsure if related, but my auto contribution date is 1970 now.
![image](https://user-images.githubusercontent.com/17442109/54085156-87f64400-4332-11e9-9ffc-f2e6481b096b.png)

**Comment by NejcZdovc** [comment]
hi, we had this problem in previous version, but based on https://github.com/brave/brave-browser/issues/3042 it looks like it's working now. Please confirm this with version 0.63. Thank you

**Comment by jnki** [comment]
@NejcZdovc No longer seems to be happening in 0.61.51

**Comment by jjenzz** [comment]
I'm on Version 0.68.131 and I have this issue. If I remove one of them, it removes all and now I can't figure out how to add one back in as I would like to contribute, once.
