### ISSUE TITLE
Double notifications to pin Brave shown on startup of  the browser

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#36470]
## Description 

Thanks to @srirambv for finding this issue of double notifications to pin Brave showing up after Brave launch on a new install.  I believe @kjozwiak has seen in Nightly.  This happens in all three channels, Nightly, Beta & Release both in Win 11 x64 & Win 11 Arm64.  (I didn't see these notifications earlier as my OS settings for `Startup Notification` is toggled off).  The other issue that I've noticed is on a new install one of the notifications reads `setup.exe would like...` and other reads `chrmstp.exe would like...`.  On a new profile, there is a single notification, and it reads `chrmstp.exe would like...`. 

## Steps to Reproduce

   1. Install 1.65.46
   2. launch Brave
   
## Actual result:

Double notifications stacked up for a new install.  For a new profile, single notification shown as expected.

New Install

Nightly | Beta | Release
--- | ---- | ----
<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d4e035b1-041c-460b-adde-619a101fd781">|<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e5960f6b-0ee4-4d14-a6af-6bd1e159255f">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/59f51eb8-476a-45e0-b53c-87e5fff80b79">

New profile 
<img width="952" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/7e1295af-c450-4f7d-8442-f1219613314e">

## Expected result:
Should show a single notification

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.65.46 Chromium: 122.0.6261.94 (Official Build) nightly (64-bit)
-- | --
Revision | a37da47fae90488c6394ce9dfa8a2749de3bd64e
OS | Windows 11 Version 23H2 (Build 22631.3155)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron 
cc: @brave/qa-team

**Comment by rebron** [comment]
cc: @mherrmann @simonhong

**Comment by LaurenWags** [comment]
Reproduced with

```
Brave	1.64.113 Chromium: 123.0.6312.86 (Official Build) (32-bit) 
Revision	4e20399c0c5e3cbbb80dd1119122400e08259feb
OS	Windows 10 Version 22H2 (Build 19045.4170)
```

<img width="405" alt="Screenshot 2024-03-27 at 10 40 46 AM" src="https://github.com/brave/brave-browser/assets/28145373/a6c98e80-6d22-4a96-94d4-de6998ea694a">

**Comment by mherrmann** [comment]
I can reproduce this as well on x64 Windows 11. One point, which took me a while to figure out, is that notifications from "Apps" must be enabled in Windows' settings.
![image](https://github.com/brave/brave-browser/assets/1076393/8cfabc6a-d741-442d-a518-0b399e558c91)

**Comment by mherrmann** [comment]
The issue does not appear for me for per-user installations. It only appears for system-wide installations. That is, when I accept the UAC prompt that opens as a part of Brave's installer.

**Comment by mherrmann** [comment]
The behavior exists in upstream (Chromium) as well.

1. Download https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2F1270889%2Fmini_installer.exe?generation=1710164360152816&alt=media.
2. In an admin command prompt, type `mini_installer.exe --system-level`.
3. You get the first notification "Would you like to pin Chromium to your taskbar?" from setup.exe.
4. Start Chromium.
5. You get the second notification from chrmstp.exe.

**Comment by mherrmann** [comment]
I filed a bug with upstream: https://issues.chromium.org/issues/331836635

**Comment by mherrmann** [comment]
@MadhaviSeelam your descriptions says "new install". Is it understood that this is an installation without an existing profile? It was not fully clear to me. Should it be clarified in this issue's description?

**Comment by kjozwiak** [comment]
The above requires `1.64.116` or higher for `1.64.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.64.116 Chromium: 123.0.6312.105 (Official Build) (64-bit)
-- | --
Revision | d9090cab16ea606108bdf6edd7466df58d9d76fd
OS | Windows 10 Version 22H2 (Build 19045.4170)

```
- Uninstall brave and install brave shows single pin browser notification on a clean profile as expected.
![image](https://github.com/brave/brave-browser/assets/38657976/af67871d-3a58-4825-820b-4bcfdddc6735)
