### ISSUE TITLE
Scroll down automatically in the Leo sidepanel  if `Response rate limit reached` modal shown

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#36475]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/35640. If a user uses free tier and query with Leo with long text and if rate limit reached, it should auto scroll down to show `Response rate limit reached` modal as in Nightly `1.65.46`

## Steps to Reproduce

   1. Install 1.64.90
   2. launch Brave
   3. load https://www.cnn.com/2024/02/26/world/japan-moon-sniper-slim-wakes-up-images-scn/index.html in a new tab
   4. query Leo until `Response rate limit reached` reached.
   
## Actual result:

 `Response rate limit reached` modal not shown
 
https://github.com/brave/brave-browser/assets/98358127/f56eaa06-4e56-42c2-84fb-c349b6d980fa

## Expected result:
It should auto scroll down to show the `Response rate limit reached` modal

https://github.com/brave/brave-browser/assets/98358127/e6eb952c-4236-45b1-a414-6d0a14c04dac

## Brave version (brave://version info)

```
Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | Windows 11 Version 23H2 (Build 22631.3155)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
 @yrliou @mattmcalister  @LorenzoMinto 
cc: @rebron @stephendonner

**Comment by nullhook** [comment]
this should be fixed via: https://github.com/brave/brave-core/pull/22170 

can you please check again? @MadhaviSeelam

**Comment by MadhaviSeelam** [comment]
@nullhook just verified latest release `1.64.104 Chromium: 123.0.6312.46` and auto scroll worked. However, it's behaving differently 1.65.82 vs 1.65.104

`Summarize button in the Leo panel`

1.64.104 |1.65.82  
------ | ------
![image](https://github.com/brave/brave-browser/assets/98358127/753851dc-457e-435c-92a1-411a3a3f1610)|![image](https://github.com/brave/brave-browser/assets/98358127/df0f3e50-1620-429e-9097-1e3a4c45478e) 

Summarize via context menu

1.64.104 | 1.65.82 
------ | ------
![image](https://github.com/brave/brave-browser/assets/98358127/672606ff-a16d-46b8-b786-5e6f962687ee)|![image](https://github.com/brave/brave-browser/assets/98358127/fbc6544a-84e0-40f7-82cf-c4077a3d41b5)

**Comment by nullhook** [comment]
so, this has been fixed via this PR: https://github.com/brave/brave-core/pull/22170 

if needed we can uplift it.

**Comment by MadhaviSeelam** [comment]
Verification `Passed` using 
```
Brave | 1.65.83 Chromium: 123.0.6312.46 (Official Build) beta (64-bit)
-- | --
Revision | 1ea667c8c59a4a4a327579974ec11149a738e750
OS | Windows 11 Version 23H2 (Build 22631.3296)
```


1. Installed 1.65.83
2. launched Brave
3. loaded https://www.cnn.com/2024/03/15/economy/nar-realtor-commissions-settlement/index.html
4. summarize the page  
5. click I understand
6. query Leo until `Response rate limit reached`  

#### Confirmed `Response rate limit reached` modal auto scrolled down to `Upgrade now` and `Switch to the free modal` buttons

https://github.com/brave/brave-browser/assets/98358127/3fe54f48-fdb5-4f69-88d5-2eeb3c882fd4
