### ISSUE TITLE
Add "channel" property to Android webcompat reports

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#36478]
See https://github.com/brave/brave-browser/issues/36230 for details.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.71.112 Chromium: 130.0.6723.44 (Official Build) (64-bit) 
Revision	7d51df656b247f9432ee714a6d160142a1e11c13
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that `channel` and `version` properties are sent in webcompat report. 

example | example
---|---
![Image](https://github.com/user-attachments/assets/010cd8fc-3df6-4bff-a023-7b7a5c7d2679) | ![Image](https://github.com/user-attachments/assets/1cf71b96-3e0b-499d-b747-d5e66c8b33a4)
