### ISSUE TITLE
Don't allow users to submit Android webcompat reports from browser error pages

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#36484]
See https://github.com/brave/brave-browser/issues/35597 for details.

**Comment by hffvld** [comment]
Verified on `Galaxy Z Fold 6` using version(s):
```
Device/OS: Galaxy Z Fold 6 / q6quew-user 14 UP1A.231005.007 release-keys
Brave build: 1.72.90 
Chromium: 130.0.6723.70 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/25495#issue-2514944520
2. *Verify*

**ACTUAL RESULTS:**
- Verified that Webcompat reports can't be sent for `error pages`.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/412948e8-44a3-437f-8f51-9b8024ed7245) | ![2](https://github.com/user-attachments/assets/542dfcf3-4ca8-4408-ae62-b2b52f239db9) | ![3](https://github.com/user-attachments/assets/48355e08-9901-493f-b04f-19d6dc3c1dae) |
