### ISSUE TITLE
Let user take screenshots when reporting Android webcompat issues

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#36486]
See https://github.com/brave/brave-browser/issues/35473 for details

**Comment by hffvld** [comment]
Verified on `Galaxy Z Fold 6` using version(s):
```
Device/OS: Galaxy Z Fold 6 / q6quew-user 14 UP1A.231005.007 release-keys
Brave build: 1.72.90 
Chromium: 130.0.6723.70 (Official Build) beta (64-bit) 
```
---------------------------

<details>
<summary> Test case 1 </summary>

**STEPS:**
1. Launch Brave
2. Go to any web page
3. Open the `Brave Shields` pop-up dialog
4. Switch off `Brave Shields` if It is ON
5. Tap `Report broken site`
6. Tap `Submit`

**ACTUAL RESULTS:**
- Verified that the screenshot is not taken and can't be viewed
- Verified that the screenshot has not been sent with the report

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/16d95578-3292-4b6f-9c38-22a57742b7c4) | ![2](https://github.com/user-attachments/assets/52456a27-44af-4034-9516-a7aa8557587b) | ![3](https://github.com/user-attachments/assets/6ca9c8b6-f0cb-4f64-9bc3-9af71de815ce) |
</details>

<details>
<summary> Test case 2 </summary>

**STEPS:**
1. Launch Brave
2. Go to any web page
3. Open the `Brave Shields` pop-up dialog
4. Switch off `Brave Shields` if It is ON
5. Tap `Report broken site`
6. Tap the checkbox `Include screenshot of the current page`
7. Tap `View screenshot` to check the screenshot of the current page is ready
8. Tap `Submit` report

**ACTUAL RESULTS:**
- Verified that `Include screenshot of the current page` can be selected and screenshot is made
- Verified that the screenshot can be previewed
- Verified that the screenshot can be sent in the context of the Webcompat report

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/49dbf785-9d2b-4ddd-b4cd-c0980a87b751) | ![2](https://github.com/user-attachments/assets/9049b7f3-359c-451f-bfaf-688aee356300) | ![3](https://github.com/user-attachments/assets/1e3235ea-9cbe-461b-bda9-30b7ffc8a6ee) |
| ![1](https://github.com/user-attachments/assets/3db4b1e5-e9c3-461d-89c7-9545b3db8626) | ![2](https://github.com/user-attachments/assets/c149b3dc-78d6-4329-8091-9709d6b11b6a) | ![3](https://github.com/user-attachments/assets/36641eb8-2ea7-4011-9900-d988ccd706fd) |
</details>
