### ISSUE TITLE
Simplify Android Report Broken Site language and point to external link

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#36483]
See https://github.com/brave/brave-browser/issues/35683 for details.

**Comment by hffvld** [comment]
Verified on `Galaxy Z Fold 6` using version(s):
```
Device/OS: Galaxy Z Fold 6 / q6quew-user 14 UP1A.231005.007 release-keys
Brave build: 1.72.90 
Chromium: 130.0.6723.70 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/25488#issue-2513620835 and https://github.com/brave/brave-core/pull/25488#discussion_r1752331528
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the string is spelled as: `Thank you for helping make Brave better for all. This report will only contain information necessary for us to fix this site. Learn more.`
- Verified that `Learn more` is clickable and transfers to the external link `https://github.com/brave/brave-browser/wiki/Web-compatibility-reports`

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/e9d284cc-51a3-4757-baca-ec8bd3495c44) | ![2](https://github.com/user-attachments/assets/0aa5193c-8aa2-4131-b9aa-d1ffaf89b5d4) | ![3](https://github.com/user-attachments/assets/91687eb6-cc46-463f-9640-4592d2ff0e56) | ![4](https://github.com/user-attachments/assets/12d77094-9f3c-46bb-90bb-3bbb9f500a34) |
