### ISSUE TITLE
Add "channel" property to iOS webcompat reports

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#36480]
See https://github.com/brave/brave-browser/issues/36230 for details.

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6
Brave build: 1.68 (101)
BraveCore: 1.68.101 (126.0.6478.126)
```
---------------------------

**STEPS:**
1. Set Charles Proxy
2. Launch Brave 
3. Go to any website, for example, www.anker.com
4. Three-dot menu > Report a Broken Site
5. Provide some info > Submit
6. Find https://webcompat.brave.com > Webcompat in Charles Proxy > *Verify*
7. Go to https://stats.brave.com/dashboard#webcompat on Desktop > Webcompat > *Verify*

**ACTUAL RESULTS:**
- Verified that Brave's `channel` name is shown in Webcompat report

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/db7039ad-c36b-4b74-b820-24b2a5b41802) | ![2](https://github.com/brave/brave-browser/assets/128532965/a7a1e204-d349-495c-b22a-4f710271e9bc) | ![3](https://github.com/brave/brave-browser/assets/128532965/b1cb2f84-cd33-40de-acf2-689f36099073) |
