### ISSUE TITLE
The metrics `Brave.Today.SidebarFilterUsages` is not shown in the local state file even after using the sidebar panel 10+ times

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#36502]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/35434
The metrics `Brave.Today.SidebarFilterUsages` is not shown in the local state file even after using the sidebar panel 10+ times
## Steps to Reproduce

   1. Clean profile 1.54.x
   2. Open a NTP and click on Brave News cards (5)
   3. Click on the sidepanel
   4. Click on the reading list icon and add few clicked cards into reading list
   5. Click on few cards (6)
   6. Click on the sidepanel
   7. Click on the bookmarks icon and bookmark 6 cards 
   8. Open brave://local-state
   9. Look for the metrics `Brave.Today.SidebarFilterUsages`
   10. The metrics is NOT shown under brave://local-state file
   11. Close the browser and set the sys date ahead by  7 days
   12. Open browser and reload brave://local-state file
   13. The metrics is NOT shown under brave://local-state file

## Actual result:

The metrics `Brave.Today.SidebarFilterUsages` is not shown in the local state file even after using the sidebar panel 10+ times
![image](https://github.com/brave/brave-browser/assets/38657976/3d076f3f-31cc-4b99-94f4-1095d3eda1c8)

## Expected result:
The metrics `Brave.Today.SidebarFilterUsages` should be shown in the local-state file

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.64.74 Chromium: 122.0.6261.43 (Official Build) beta (64-bit)
-- | --
Revision | b03db955df4f1c679cb7c2ae8ebfd331d5c29276
OS | Windows 10 Version 22H2 (Build 19045.4046)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @DJAndries @mattmcalister @LorenzoMinto @brave/qa-team

**Comment by DJAndries** [comment]
@GeetaSarvadnya The "sidebar filters" are shown in this attached screenshot: 
![Screenshot-2024-03-01_12-32](https://github.com/brave/brave-browser/assets/5621455/e1d5ceb0-b615-41bb-91e8-fae06de3688d)

We will want to ensure that the metric shows the amount of News sessions where sidebar filters were used. Testing this metric involves starting several News sessions, and clicking on the items within the filter (i.e. "For you", "following", etc.)

**Comment by GeetaSarvadnya** [comment]
@DJAndries Thanks for the clarification. I have verified the issue, as you mentioned above, to see the metrics `Brave.Today.SidebarFilterUsages` value, I have clicked on the several items under  "For you", "following" sections (shown in the GIF below) but I see `Brave.Today.SidebarFilterUsages` response value `0` always even if I click on 4 or 5 cards
![Brave News](https://github.com/brave/brave-browser/assets/38657976/6b00b4f3-cd2c-4b87-a133-82cef7d679cd)

**Comment by DJAndries** [comment]
@GeetaSarvadnya as mentioned above, please try accessing the sidebar filters from multiple sessions, as the question refers to the amount of News sessions that used the filters.

**Comment by GeetaSarvadnya** [comment]
@DJAndries As per the comments above, The issue is working as expected hence closing the issue. Thanks @DJAndries !
