### ISSUE TITLE
Sharesheet menu is broken, `Copy Clean Link` and `Report a Broken Site` can't be added to the Favorites

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#36506]
### Description: 

Follow-up to brave/brave-ios#8070

### Steps to Reproduce 
  1. Launch Brave `1.63` or newer
  2. Go to any website
  3. Tap the `Share` button > Edit Actions...
  4. Add `Copy Clean Link` to the `Favorites` > Done > *Observe `Copy Clean Link` is not shown in the `Favorites`*
  5. Tap `Edit Actions...` > *Observe `Copy Clean Link` is not shown anymore*
  6. Add `Report a Broken Site` > Done > *Observe `Report a Broken Site` is not added to the `Favorites`*

### Actual result: 

Observed that:
- `Copy Clean Link` disappeared from the list when trying to add it to the `Favorites`
- Other items like `Report a Broken Site` can't be added to the `Favorites`

There is no option to restore the settings and see `Copy Clean Link` again. I checked `Chrome`/`Safari` and could add any item to the `Favorites` in both browsers and no items were hidden.

*Copy Clean Link*

https://github.com/brave/brave-ios/assets/128532965/6071765c-96a2-4264-85a0-5abb669fc41c

*Report a Broken Site*

https://github.com/brave/brave-ios/assets/128532965/934e9d09-2503-4e8d-b8ea-d1f291de6361

### Expected result:

`Copy Clean Link` must be available in the list on Sharesheet and can be added to the `Favorites`.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

`Easily reproduced`

### Brave Version: 

```
Brave build: 1.63 (161)
BraveCore: 1.63.161 (122.0.6261.57)
```

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? YES

### Device details: 

```
- iPhone 14 / iOS 17.4 (21E217)
- iPad Air / iPadOS 16.7.2
```

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

cc @soner-yuksel

**Comment by kjozwiak** [comment]
The above requires `1.63.169` or higher for `1.63.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.4
Brave build: 1.63 (169)
BraveCore: 1.63.169 (122.0.6261.111)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/36506#issue-2163639892
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Copy Clean Link` is shown in the sharesheet menu
- Verified that `Copy Clean Link` can be added to the `Favorites` and is not removed from the list
- Verified that `Copy Clean Link` is working as expected
- Verified that all Brave items from the list can be added to the `Favorites`

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/b88a54d6-2695-43c8-ab8b-e3af415f21e2) | ![2](https://github.com/brave/brave-browser/assets/128532965/a22e12f4-5977-4f84-9507-3747a89c384b) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/9c80cd89-b577-4997-811f-d9bb521ca589) | ![2](https://github.com/brave/brave-browser/assets/128532965/5eab3fd7-b452-4e54-a92e-474a9993859c) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/c8c56a83-152a-47a2-aa0a-ffcdf05ceb58) | ![2](https://github.com/brave/brave-browser/assets/128532965/bae980d4-afe3-43a3-a743-575cf6fb59c1) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/71da1890-820b-40e3-a480-ebdf2a1da936) | ![2](https://github.com/brave/brave-browser/assets/128532965/58b3880a-2242-41bb-8276-68d4d2346bc4) |

https://github.com/brave/brave-browser/assets/128532965/8a3ce753-7f40-47c5-9e94-68efd893a2b6
