### ISSUE TITLE
[Wallet] Add setting to adjust transaction simulation opt-in status

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#36509]
## Description 

We need an option in Web3 settings to adjust the opt-in status for transaction simulations since the opt-in pop-up will only be shown once.

<img width="679" alt="Screenshot 2024-03-01 at 4 23 04 PM" src="https://github.com/brave/brave-browser/assets/30185185/c457986b-07c7-412b-848a-c55046f061d8">

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (64-bit)
-- | --
Revision | 5d9143e1a0812c53bdc27fd5384591254306a88c
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from [brave/brave-core#22422](https://github.com/brave/brave-core/pull/22422)
- Verified enabling `brave://flags/#brave-wallet-enable-transaction-simulations` via flags adds a new setting to `brave://settings/web3`
- Verified setting is default set to `Ask`
- Verified `transaction_simulation_opt_in_status` field in `brave://prefs-internals/` updates when flag is enabled 

https://github.com/brave/brave-browser/assets/17010094/ba88db72-74a8-48f4-a1bb-0a93c01a07a9
