### ISSUE TITLE
Wrong sidebar add item button position

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#36500]
## Description 

<img width="93" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/e7a1e736-9cdb-4d21-bc44-59e0544d3b64">

## Steps to Reproduce

   1. 
   2. 
   3. 

## Expected result:
<img width="99" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/acf4d4fa-7b50-487a-af1e-285be8f873f2">

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.65.80 Chromium: 123.0.6312.29 (Official Build) nightly (64-bit)
-- | --
Revision | cd0c2b9c6f07e8f01724294c8d7e37393a8c3a38
OS | Windows 10 Version 22H2 (Build 19045.4170)
```

### Steps:
1. installed `1.65.80`
2. launched Brave
3. checked the Sidebar's icon strip

### Confirmed the `+` icon is directly below the `Reading List` icon on the sidebar

![image](https://github.com/brave/brave-browser/assets/387249/54aa84e4-3c02-487a-a0da-d34220829e5d)
