### ISSUE TITLE
Tab freezing and potential browser freeze during development with unresponsive code

### ISSUE THREAD

**Issue by Crsk** [brave/brave-browser#36501]
## Description 

Sometimes buggy code within a web application freezes the tab or even entire browser, requiring to force quit the entire browser to close the frozen tab.

## Steps to Reproduce

   1. create a demo project. eg `npm create vite@latest`
   2. in your project, type `while (true) { console.log('Gosh, is that you?') }`
   3. save it

## Actual result:

Entire browser is frozen

## Expected result:
Close the tab, no matter if  it's "busy"

## Reproduces how often: 

Rarely reproducible or depending on my mood

## Brave version (brave://version info)

| | Version |
| ------ | ------- |
| Brave | 1.63.162 Chromium: 122.0.6261.69 (Official Build) (arm64) |
| OS | Mac OS Apple M1 14.1.1 (23B81) |

## Additional

1. I could not reproduce the issue from the inspector console.
2. With the code snippet I provided the entire browser is frozen, this is the first time I experience that behavior, normally it is just the application tab that stops working.

**Comment by rebron** [comment]
@Crsk Do you see anything brave://crashes/ Can you send if so, and put the crash report ID in this issue.

**Comment by Crsk** [comment]
> @Crsk Do you see anything brave://crashes/ Can you send if so, and put the crash report ID in this issue.

I'm seeing a lot of crash IDs, averaging once a day. However, I'm not sure what situations they are related to. Three crashes occurred yesterday, the same day the error occurred, so they might be relevant.

- 54080500-0f95-950b-0000-000000000000
- c1690400-0f95-950b-0000-000000000000
- f2770100-0f95-950b-0000-000000000000

I just attempted to reproduce the crash using the infinite loop scenario. After the browser froze, I force-quit Brave, but it didn't generate a crash report.

I'll wait and update the issue with the confirmed crash ID as soon as I'm sure I have it.

**Comment by iefremov** [comment]
stale
