### ISSUE TITLE
spanish translation typo

### ISSUE THREAD

**Issue by nachodieez** [brave/brave-browser#36511]
## Description 
There is a typo in the "Protecciones y privacidad de Brave":

![typo](https://github.com/brave/brave-browser/assets/119790922/403af8df-76cf-49a6-bb74-46847bd93d3a)

This should be Borrar todos los datos de **navegación**

## Steps to reproduce

   1.  Enter "Configuración".
   2.  Enter "Protecciones y privacidad de Brave".
   3. Scroll down to "Borrar datos de navegación".
   
## Brave version
1.63.165

**Comment by bsclifton** [comment]
See correction in https://github.com/brave/brave-core/pull/22424
