### ISSUE TITLE
Strange entries in Preferences file

### ISSUE THREAD

**Issue by Johann999** [brave/brave-browser#36513]
Strange entries in Preferences file.
I never use sync.
how can i stop these entries ?

Brave	1.63.165 Chromium: 122.0.6261.94 (Offizieller Build) (32-Bit) 
![sync](https://github.com/brave/brave-browser/assets/53431361/776165b4-c58b-4d68-a5e2-163fdb36affe)

**Comment by rebron** [comment]
cc: @AlexeyBarabash @bsclifton

**Comment by AlexeyBarabash** [comment]
this is the result of  https://github.com/brave/brave-core/pull/21767 

I'll limit it to iOS and look while it keeps writing when sync is not enabled.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.65.90 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | f5ca64cd15d0d5c90f17b7d5213b6e2dd725d66a
OS | Windows 11 Version 23H2 (Build 22631.3296)
```

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

```
Brave	1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (x86_64) 
Revision	5d9143e1a0812c53bdc27fd5384591254306a88c
OS	macOS Version 14.4.1 (Build 23E224)
```

### Case 1: Desktop --> Desktop (2 profiles) - `PENDING`

### Case 2: Desktop --> iPhone - `PENDING`

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.4.1
- iPad Air / iPadOS 16.7.2
Brave build: 1.65 (96)
BraveCore: 1.65.96 (123.0.6312.86)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Settings > Sync
3. Tap `⚙️` > *Confirm that the `Leave chain details` field is empty*
4. Close `Sync Internals` > Start a `Sync` by creating a new or connect existing sync chain
5. Now remove the current device from the sync chain
6. Tap `⚙️` > *Verify that the `Leave chain details` field contains sync info*


**ACTUAL RESULTS:**
- Verified that the `Leave chain details` field is empty when no previous `sync chains` was created
- Verified that the `Leave chain details` field contains the info about the previously created `sync chain`

---------------------------

<details>
<summary> iPhone </summary>

|Before `Sync`|`Sync` established|`Sync` deleted|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/b4cd9535-b683-43f9-9074-bd06e2749438) | ![2](https://github.com/brave/brave-browser/assets/128532965/eebaf4f6-1fa7-4a11-9ec3-79450b2a64f9) | ![3](https://github.com/brave/brave-browser/assets/128532965/aaa378bb-c4c1-4c79-84c1-019cc76603cb) |
</details>

<details>
<summary> iPad </summary>

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/bfbf733b-e1f0-4d81-868f-98e24627c768) | ![2](https://github.com/brave/brave-browser/assets/128532965/dbca2aec-83cd-4dab-af9d-3ab27214fd7f) | ![3](https://github.com/brave/brave-browser/assets/128532965/9737ab94-231f-4f17-9887-5bc5875c51d2) |
</details>

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```

```

#### Case 1:  Desktop -->Desktop (2 profiles) - `PENDING`
<details>

1. installed `1.64.113`
2. launch Brave
3. imported 2 Chrome profiles (with bookmarks, history & extensions) 
4. verified Sync is not enabled as it's a new install
5. opened `brave://prefs-internals/`
6. verified Leave chain details field populated (with `metadata": [ "user_controlled", "user_modifiable", "extension_modifiable" ],
            "value": "2024-03-28 20:42:11.891965 UTC brave_sync_service_impl.cc(64) StopAndClear\n"`)
7. upgrade via `brave://settings/help`
8. confirmed `1.65.100` installed
9. opened `brave://sync-internals`
10. confirmed `Leave chain details` field is blank 
11. enabled Sync between Profile 1 and Profile 2 (chrome profile)
12. confirmed `Leave chain details` field is blank 
13. clicked `Leave Sync Chain` in brave://settings/braveSync/setup for Profile 1
14. confirmed `Leave chain details` field is blank 
15. clicked `Delete Sync account` for Profile 2 
16. confirmed `Leave chain details` field is blank

#### Confirmed `Leave chain details` field is blank 

- After enabling Sync
- Leave Sync Chain
- Delete Sync account

step 1 | step 4| steps 5-6 |step 7|step 8| steps 9-10 | step 11| step 12 | step 13 | step 14 | step 15 
----- | ----- | ----- | ------ | ------ | ----- | ------ | ------ | ----- | -----  | ------ 













</details>

#### Case 2: Desktop --> iPhone - `PENDING`
<details>

1. installed `1.64.113`
2. launch Brave
3. verified Sync is not enabled as it's a new profile
4. opened `brave://prefs-internals` field
5. verified Leave chain details field populated (with `"metadata": [ "user_controlled", "user_modifiable", "extension_modifiable" ],
            "value": "2024-03-28 21:26:47.223014 UTC brave_sync_service_impl.cc(64) StopAndClear\n"`)
6. upgrade via `brave://settings/help`
7. confirmed `1.65.100` installed
8. opened `brave://sync-internals` 
9. Confirmed `Leave chain details` field is blank 
10. enabled Sync between Desktop & iPhone device
11. confirmed `Leave chain details` field is blank in `brave://sync-internals`
12. removed `iPhone` from the device list in `brave://settings/braveSync/setup`
13. Confirmed `Leave chain details` field is blank 
14. Clicked `Leave Sync Chain` in brave://settings/braveSync/setup for Profile 1
15. Confirmed `Leave chain details` field is blank 

### Confirmed `Leave chain details` field is blank 

- After enabling Sync
- Leave Sync Chain
- Delete Sync account

step 1 | step 3| step 5|step 7|step 9 |step 10 | step 11| step 12a | step 12b | step 13 | step 14 | step 15
----- | ----- | ----- | ------ | ----- | ------ | ------ | ----- | -----  | ------ | ----- | ------
<img width="1312" alt="Screenshot 2024-03-28 at 2 27 02 PM" src="https://github.com/brave/brave-browser/assets/387249/9a316730-d136-416b-98aa-8d441e5af246"> | <img width="1312" alt="Screenshot 2024-03-28 at 2 27 54 PM" src="https://github.com/brave/brave-browser/assets/387249/32a46173-4522-4227-be83-63ad712d13ff"> | <img width="1312" alt="Screenshot 2024-03-28 at 2 28 42 PM" src="https://github.com/brave/brave-browser/assets/387249/c24bc3e5-16b7-4581-a016-27179c0e1711"> | <img width="1312" alt="Screenshot 2024-03-28 at 2 32 38 PM" src="https://github.com/brave/brave-browser/assets/387249/c0684b41-7f02-4f5e-84d3-0be9c1c3a9c6"> | <img width="1312" alt="Screenshot 2024-03-28 at 2 32 28 PM" src="https://github.com/brave/brave-browser/assets/387249/cbefd49c-636b-4201-85d0-6f27812fd625"> | <img width="1312" alt="Screenshot 2024-03-28 at 2 36 39 PM" src="https://github.com/brave/brave-browser/assets/387249/87ac3978-f052-452f-bc5d-7758f1099a27"> | <img width="1312" alt="Screenshot 2024-03-28 at 2 36 55 PM" src="https://github.com/brave/brave-browser/assets/387249/a3b32806-0561-4729-b2e7-c059f0e4daf3"> | <img width="1312" alt="Screenshot 2024-03-28 at 2 37 18 PM" src="https://github.com/brave/brave-browser/assets/387249/643e049d-34d7-484a-ac07-27e342b50409"> | <img width="1312" alt="Screenshot 2024-03-28 at 2 37 26 PM" src="https://github.com/brave/brave-browser/assets/387249/1def04c7-f03e-4047-b6e3-e91891764012"> | <img width="1312" alt="Screenshot 2024-03-28 at 2 37 44 PM" src="https://github.com/brave/brave-browser/assets/387249/b1c8ad7e-1e9f-4023-97be-bc1cf7bbb85d"> | <img width="1312" alt="Screenshot 2024-03-28 at 2 38 00 PM" src="https://github.com/brave/brave-browser/assets/387249/fc85ee26-b39c-4f26-b1c0-647569ddf110"> | <img width="1312" alt="Screenshot 2024-03-28 at 2 38 11 PM" src="https://github.com/brave/brave-browser/assets/387249/13c1960a-cd39-4e9a-9394-b5a1ed6e01ef">











</details>

**Comment by hffvld** [comment]
## IN PROGRESS...

Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 14 AP21.240305.005 release-keys
Brave build: 1.65.101
Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
```

OR

Filed follow-up issue #
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/22456#issue-2169273756
2. *Verify*

**ACTUAL RESULTS:**
- Verified that there is no info in `Leave chain sync` on `brave://sync-internals`

---------------------------

<details>
<summary> Galaxy Tab S8 / Tablet </summary>


</details>

<details>
<summary> Pixel 7 / Phone </summary>

https://github.com/brave/brave-browser/assets/128532965/1e399333-683d-4d60-8d22-316fb2f323fa
</details>
