### ISSUE TITLE
Brave Leo showing code in response when asked for comparison

### ISSUE THREAD

**Issue by dpthegrey** [brave/brave-browser#36519]
## Description 

showing code in response

## Steps to Reproduce

cannot reproduce

## Actual result:

![image](https://github.com/brave/brave-browser/assets/49444980/39337715-d778-4de9-9d48-8bfb33830745)

## Expected result:
a comparison with pros and cons of both service and give a conclusion.

## Reproduces how often: 

cannot reproduce

## Brave version (brave://version info)

1.63.165 Chromium: 122.0.6261.94 (Official Build) (x86_64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

Leo using Mixtral free version

**Comment by mattmcalister** [comment]
can't reproduce
