### ISSUE TITLE
The metrics `Brave.Core.PagesLoaded.2` value is not shown as `1` even when 10+pages are loaded in new tab pages

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#36527]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/35301
The metrics `Brave.Core.PagesLoaded.2` value is not shown as `1` even when 10+pages are loaded in new tab pages
## Steps to Reproduce

   1. Clean profile 1.64.x
   2. Open brave://local-state
   3. Confirmed that the metrics `Brave.Core.PagesLoaded.2` response value is `0` as expected 
   4. Open 10 different websites in 10 NTP's
   5. Reload brave://local-state
   6. The metrics `Brave.Core.PagesLoaded.2` response value is still `0`
   7. Restart the browser and wait for 1 or 2 mins
   8. The metrics  `Brave.Core.PagesLoaded.2` response value is `0` under `Logs` block
   9. The metrics  `Brave.Core.PagesLoaded.2` response value changes to `1` under `logs_constellation_prep` block, this looks incorrect
   10. Close the browser and set the sys date ahead by 7 days
   11. Restart the browser and reload brave://local-state
   12. The metrics  `Brave.Core.PagesLoaded.2` response value is `0` in both `Logs` and  `logs_constellation_prep` blocks

## Actual result:

step 8 | step 9
-------|--------
![image](https://github.com/brave/brave-browser/assets/38657976/12dcca68-b85c-4f17-9240-4391a87b3e1d) | ![image (8)](https://github.com/brave/brave-browser/assets/38657976/e4dcef5d-f163-4aaf-973a-64e8ce66c505)

## Expected result:
The metrics `Brave.Core.PagesLoaded.2` response value should be `1` in `Logs` block when 10+ sites are loaded in NTP's

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | Windows 10 Version 22H2 (Build 19045.4046)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes, In RC 1.63.x the metrics is shown only under `logs_constellation_prep` block with response value `0` when 10 sites are loaded. the metrics is not shown under `Logs` even when 1 site is loaded, looks like the metrics is broken in RC itself
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @DJAndries @mattmcalister

**Comment by DJAndries** [comment]
@GeetaSarvadnya For weekly metrics, please only monitor the `logs_constellation_prep` pref since the JSON reporter is deprecated which renders the `logs` pref inactive. In the event that you'd like to test the JSON reporter pref, the `BraveP3ATypicalJSONDeprecation` feature can be disabled. `1` seems to be the correct answer given the amount of pages viewed.

**Comment by GeetaSarvadnya** [comment]
Retested the issue works as expected. Thanks @DJAndries !
