### ISSUE TITLE
The metrics `Brave.Core.PagesReloaded` response value is `1` even when multiple tabs sites are reloaded

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#36528]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/36527
The metrics `Brave.Core.PagesReloaded` response value is `1` even when multiple tabs are reloaded

## Steps to Reproduce

   1. Clean profile 1.64.x
   2. Open brave://local-state file
   3. Confirmed that the metrics `Brave.Core.PagesReloaded` response value is `0` as expected
   4. Open 10 different sites in 10 NTP's
   5. Reload all the 10 sites
   6. Reload brave://local-state
   7. The metrics `Brave.Core.PagesReloaded` response value is still `0` in both `Logs` and `logs_constellation_prep` blocks
   8. Close the browser and set the sys date ahead by 7 days
   9. Relaunch the browser and reload brave://local-state file
   10. The metrics `Brave.Core.PagesReloaded` response value is still `0` in `Logs` block
   11. The metrics `Brave.Core.PagesReloaded` response value is `1` in `logs_constellation_prep` blocks 

## Actual result:

The metrics `Brave.Core.PagesReloaded` response value is `1` even when multiple tabs are reloaded
## Expected result:
The metrics `Brave.Core.PagesReloaded` response value should be greater than zero based of the no of sites reloaded

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | Windows 10 Version 22H2 (Build 19045.4046)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @mattmcalister @DJAndries

**Comment by DJAndries** [comment]
@GeetaSarvadnya please restart the browser and wait a minute, after step 5

**Comment by GeetaSarvadnya** [comment]
@DJAndries After step 5, I have restered the browser and waited for 1+ mins and the metrics is shown under `logs_constellation_prep` block with response value `1`. The metrics under the logs have the metrics `Brave.Core.PagesReloaded` value still `0`. I think this is expected
![image](https://github.com/brave/brave-browser/assets/38657976/665f320c-4480-4cee-b665-7dcccd3f16b0)
