### ISSUE TITLE
Follow up of #34853 - The metric index value isn't matches the primary language set in the browser

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#36529]
## Description 

Follow up of #34853 - The metric value index isn't matches the primary language set in the browser
## Steps to Reproduce

   1. Clean profile 1.64.x 
   2. Open brave://local-state
   3. Look for the metrics `Brave.Core.PrimaryLang`
   4. Confirmed that the metrics `Brave.Core.PrimaryLang` is shown under `logs_constellation_prep_slow` and `constellation_logs_slow` blocks
   5. The metrics `Brave.Core.PrimaryLang` value `37` corresponds to `Azerbaijani` but the primary language set at the browser `English (United States)`

step 4 | step 4 (1)
----------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/f5f18dee-103f-4568-913c-06ea2ed66832) | ![image](https://github.com/brave/brave-browser/assets/38657976/b7e59e60-c169-49b6-8fbc-08300d2b2b30)

## Actual result:

The metrics `Brave.Core.PrimaryLang` value `37` corresponds to `Azerbaijani` but the primary language set at the browser `English (United States)`

Example | Example
----------|--------
![image](https://github.com/brave/brave-browser/assets/38657976/bd78f927-7564-4953-ac89-3eb0462f6e64) | ![image](https://github.com/brave/brave-browser/assets/38657976/0a3c23a0-ea02-45f0-9b1c-bf6441ab2396)

## Expected result:
The metric index value should match the primary language set in the browser

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @mattmcalister @DJAndries

**Comment by GeetaSarvadnya** [comment]
Similarly, If I set the browser language as `Marathi` I get the metrics `Brave.Core.PrimaryLang` response value as `106` but the index value corresponds to `Marathi` language is `133` via [brave-core/components/misc_metrics/language_metrics.cc](https://github.com/brave/brave-core/blob/a317944ed75cc746f101aaeaf81b2fa416ef863f/components/misc_metrics/language_metrics.cc#L26-L210)

Example | Example | Example
----------|--------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/1a260bcc-6f4e-4404-9f1d-374e0209b966) | ![image](https://github.com/brave/brave-browser/assets/38657976/8afd27e3-64f7-4a33-ac1b-eb9336ba2472) | ![image](https://github.com/brave/brave-browser/assets/38657976/fbd04ea3-fcc6-4ad6-92c5-2e6d58d4186b)

**Comment by DJAndries** [comment]
@GeetaSarvadnya You will want to refer to the actual index within `kOrderedLangCodes`, rather than the line number. If you'd like to use the line number, you could subtract 26 from the line number to get the index. If the language occurs after line 55, subtract 1 in addition to account for the comment on line 55.

**Comment by GeetaSarvadnya** [comment]
Thanks @DJAndries !
Verified the issue again on `Windows 10 x64 1.64.90` , comparing the actau langcodes matching with reponse value and browser language. It's working as expected

**_English_**:

langcodes | local state | browser language 
-----------|-------------|---------------------
![image](https://github.com/brave/brave-browser/assets/38657976/99ee6b60-14a1-43a9-8721-b2a93ffbd0cf) | ![image](https://github.com/brave/brave-browser/assets/38657976/bc97d9bf-5266-4718-a687-1e8394286425) | ![image](https://github.com/brave/brave-browser/assets/38657976/15e4acf0-05d2-40c3-ae75-93b99244dbbd)

**Germany**:

langcodes | local state | browser language 
-----------|-------------|---------------------
![image](https://github.com/brave/brave-browser/assets/38657976/a5e0567d-c04a-4147-9ba1-28becb864eb5) | ![image](https://github.com/brave/brave-browser/assets/38657976/d1fb29a8-2a25-49b5-929c-0e664d5e45fa) | ![image](https://github.com/brave/brave-browser/assets/38657976/92182e10-4be4-44a7-a1d4-e1e302097907)

**France**:

langcodes | local state | browser language 
-----------|-------------|---------------------
![image](https://github.com/brave/brave-browser/assets/38657976/e90bc085-d009-4b18-b289-58d9357ad40f) | ![image](https://github.com/brave/brave-browser/assets/38657976/5b183caf-a97b-4cb3-9a96-c2ca302982d7) | ![image](https://github.com/brave/brave-browser/assets/38657976/6bab5753-53d2-47a4-9491-61cf969e583a)

**Kannada**:

langcodes | local state | browser language 
-----------|-------------|---------------------
![image](https://github.com/brave/brave-browser/assets/38657976/27ebdcf3-a8e6-49e3-b45b-929f6a0e83ed) | ![image](https://github.com/brave/brave-browser/assets/38657976/ad9b0362-fbaf-4916-8bdd-080e8701f569) | ![image](https://github.com/brave/brave-browser/assets/38657976/9fbeb098-aee3-4afe-9baa-c4a3521d1dbe)
