### ISSUE TITLE
Send non-reward confirmation for search ads when frequency caps are reached when opted-in

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#36523]
Currently we suppress confirmation when frequency cap is reached. We could improve on it and send a non-rewards confirmation instead.

## Steps to Reproduce

1. Clean profile
1. Join rewards
1. View Search ads till you reach per hour frequency cap
1. View a search ad

## Actual result:

The confirmation is suppressed

## Expected result:
Non rewards confirmation is sent

## Brave version (brave://version info)

Brave | 1.64.91 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 939586e20d208404b83713ea05cf5f6fa7fe3dd5
OS | Linux

cc @tmancey @iambrianfung @aseren

**Comment by tmancey** [comment]
Closing issue because search result ads are not delivered to Rewards users.
