### ISSUE TITLE
Bookmarklets cannot access globally set variables

### ISSUE THREAD

**Issue by strawbberrys** [brave/brave-browser#36520]
## Description: 
JavaScript code ran in a bookmark/the URL bar cannot access global variables defined in a websites code (ex: ``var global = 1``).

## Steps to Reproduce 
  1. Visit https://youtube.com and request desktop site
  2. Create a new bookmark with the URL set to ``javascript:alert(onPolymerReady)``
  3. Click the bookmark

## Actual result: 
Does nothing.

## Expected result:
Should alert with the function.

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Intermittent Issue

## Brave Version: 
1.62 (24.2.9.10)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
iPhone 8+ (iOS 16.2)

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Mobile Safari? No

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7.1
Brave build: 1.72 (96)
BraveCore: 1.72.96 (131.0.6778.24)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/36520#issue-2164954998
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `warning` message is shown when executing `javascript:alert(onPolymerReady)` javascript bookmark.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/5aa5a4ac-7157-42b2-8c0c-b5a834b3659e) | ![2](https://github.com/user-attachments/assets/d2894a22-dc4d-4d3d-bc96-1478a7c98ab0) | ![3](https://github.com/user-attachments/assets/e38f0f64-68d9-4960-bd1c-8af4ff8e69eb) |
