### ISSUE TITLE
Unable to sync after joining the chain nor leave and try to join again even after resetting settings

### ISSUE THREAD

**Issue by tom10271** [brave/brave-browser#36521]
## Description 

I am using Windows 10 and the latest version of Brave. Windows crashed all the sudden, after restarting I found all extensions installed and cookies etc are gone. I tried to join the sync account once to sync everything yet it is not working. I thought I can rejoin again and it is still not working either. I tried to reset the browser but still not working

## Steps to Reproduce

   1. Join Sync account
   2. Sync Everything
   3. 

## Actual result:
I joined the sync account successfully but nothing got synced. I selected sync everything.

## Expected result:
Settings and extension should be synced.

## Reproduces how often: 

I cannot tell

## Brave version (brave://version info)

<html>
<body>

Brave | 1.63.165 Chromium: 122.0.6261.94 (Official Build) (64-bit)
-- | --
Revision | fed0fcc915f6d9e1db871202f0304c8d582a73de
OS | Windows 10 Version 22H2 (Build 19045.4046)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? I cannot tell
- Can you reproduce this issue with the nightly channel? I cannot tell

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

I guess I might move back to rubbish-like Chrome but at least working.

**Comment by tom10271** [comment]
Tried to uninstall with deleting every settings and files enabled and reinstall again. Still not working. I don't believe you guys would fix it within 1 month either. Goodbye and good luck. Chrome I am back

**Comment by Beatz106** [comment]
> Tried to uninstall with deleting every settings and files enabled and reinstall again. Still not working. I don't believe you guys would fix it within 1 month either. Goodbye and good luck. Chrome I am back

And how are you supposed to get help if you can't even describe how things happened?? 

"Windows crashed all the sudden", that's not enough. Windows freezes completely, yes, it has already happened to me, and only in Windows 10, not in 11. But first of all, have you had blue screen problems? This is also important, depending on the code displayed by the OS, system corruption would occur, Windows usually deletes things indiscriminately as long as the system can be recovered.
