### ISSUE TITLE
Update Private History page to use Brave graphics

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36530]
## Description 
Update Private History page to use Brave graphics

## Steps to reproduce 

   1. Open a private tab
   2. Open Menu
   3. Click on Hisotry, shows Chromium graphics instead of Brave

## Actual result 
<img width=300 src=https://github.com/brave/brave-browser/assets/17010094/7013e177-7cf1-421f-8ecc-ef06cd8cb45f>

## Expected result
Use Brave graphics

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @aguscruiz @samartnik @kjozwiak @hffvld @Uni-verse

**Comment by samartnik** [comment]
New updated images:

![Screenshot_20240304_101120](https://github.com/brave/brave-browser/assets/30602739/c3cf786d-59da-44eb-93ac-73f6e296823c)
![Screenshot_20240304_101241](https://github.com/brave/brave-browser/assets/30602739/1c84674c-beae-4772-a2de-dbe41d251eb2)

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240216.010 release-keys
Brave build: 1.65.89 
Chromium: 123.0.6312.58 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/36530#issue-2166653151
2. *Verify*

**ACTUAL RESULTS:**
- Verified that we use Brave graphic in `Private` `History` tab 

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/a131fce9-847f-4517-a5c6-e25eacd197da) | ![2](https://github.com/brave/brave-browser/assets/128532965/b7a4e061-d1b8-4142-a4f5-dc5c32ac56c1) |
