### ISSUE TITLE
product page doesn’t render correctly due to Ads and trackers on `restorationhardware.com`

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3653]
## Description 

the product page doesn’t render correctly due to Ads and trackers on `restorationhardware.com`

## Steps to Reproduce

   1. Clean profile 0.60.48
   2.  Open restorationhardware.com
   3.  Click on any product
   4. The product page doesn't render properly, add to cart, price, customize, finishes etc... are missing on the product page ( see the image in actual result)
   5. Disable `Ads and Trackers` in the shield
   6. product page renders properly

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/54102921-59d73980-43f0-11e9-82f0-a423337c2d31.png)

## Expected result:
![image](https://user-images.githubusercontent.com/38657976/54103076-00233f00-43f1-11e9-881c-f54d9a5e6051.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.60.48 Chromium: 72.0.3626.121 (Official Build) (64-bit)
-- | --
Revision | da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883}
OS | Windows

### Reproducible on current release: yes
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

The issue is reported by the community user
https://community.brave.com/t/restoration-hardware-catalog-pages-dont-render-properly/48018

**Comment by ryanbr** [comment]
Atleast related for addthis from loading; Fixed in Annoyances list. Possibly another filter/script affecting addthis from loading correctly.
