### ISSUE TITLE
[Android] Implement Solana invitation UI/UX

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#36549]
## Description

This is specifically for the invitation UI/UX on Android. The bulk of the Rewards <> Solana feature is covered by https://github.com/brave/brave-browser/issues/35334.

**Comment by kjozwiak** [comment]
Closing as the above was addressed/fixed via https://github.com/brave/brave-core/pull/21977 and uplifted into `1.64.x` via https://github.com/brave/brave-core/pull/22275.

**Comment by kjozwiak** [comment]
The above requires `1.64.96` or higher for `1.64.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress on Android with

```
Brave	1.64.97 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
Revision	f7c8f13563bfe1063db456650cb43207e1c960c0
OS	Android 12; Build/SP1A.210812.016.C1; 31; REL
```
