### ISSUE TITLE
Create PDF has wrong icon in Share menu

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36546]
## Description: 
Create PDF has wrong icon in Share menu

## Steps to Reproduce 
  1. Open any website
  2. Open menu/Share menu
  3. Create PDF is showing Copy clean link icon 

## Actual result: 

Browser Menu | Share Menu
-- | --
![image](https://github.com/brave/brave-browser/assets/17010094/2a046d18-5160-482e-ba5e-a29d096b2ec9) | ![image](https://github.com/brave/brave-browser/assets/17010094/f78c3e84-e494-4f05-9fde-dcc0127da258)

## Expected result:
Should use the page icon 

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 
1.65 (56)

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?NA
- Is the issue reproducible on the latest version of Mobile Safari? NA

### Additional Information

cc: @soner-yuksel @aguscruiz @kjozwiak @Uni-verse @hffvld

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.4.1
Brave build: 1.65 (96)
BraveCore: 1.65.96 (123.0.6312.86)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/36546#issue-2168549983
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Create PDF` has correct icon

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/784742b1-bed3-458e-b3ae-c97f88695d56) | ![2](https://github.com/brave/brave-browser/assets/128532965/afb87f7f-b11d-4ab2-a057-ef8ecc901990) |
