### ISSUE TITLE
Summarize button is still active after summarizing twice. 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#36541]
## Description 

Once page content is summarized via `Summarize this page`, closed the panel and summarized via Leo tools menu, `Summarize this page` button shown again to send page content.  

## Steps to Reproduce

   1. Install 1.64.94
   2. launch Brave
   3. logged into Leo as a premium existing user
   4. load an article 
   5. clicked `Summarize the page`
   6. close the panel
   7. select text and summarize via Leo tools
   
## Actual result:

`Summarize this page` button is shown again

## Expected result:
`Summarize this page` should be hidden/disabled?

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.64.94 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 866e3a4bd76c9cc1762928df0cf9a53b8685ab71
OS | Windows 11 Version 23H2 (Build 22631.3155)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@mattmcalister @LorenzoMinto 
cc: @stephendonner @rebron

**Comment by WhatsACloud** [comment]
Reproduced the issue in Win 10 x64 in 1.65.63 Chromium: 122.0.6261.111

Issue also occurs after one presses "summarise this page" button prompt.

I think the "summarise this page" just occurs by default after every response.

@mattmcalister Is this a bug?

**Comment by MadhaviSeelam** [comment]
cc: @nullhook 

Issue was reproduced in 1.68.12 (nightly).  Also noticed `Summarize this page` button is shown after switching the tabs.
```
Brave | 1.68.12 Chromium: 125.0.6422.41 (Official Build) nightly (64-bit)
-- | --
Revision | 52fd85161e2ad348a6a1518a4c980d5d84d7067e
OS | Windows 11 Version 23H2 (Build 22631.3527)
```
Scenario 1:  Close panel and summarize text via context menu

https://github.com/brave/brave-browser/assets/98358127/e5be10a9-a6ed-4a86-89c4-af8543ed672a

Scenario 2: summarize text via context menu and switch tabs

https://github.com/brave/brave-browser/assets/98358127/3d6a1119-75e4-4eac-ab57-db3e31a71b89

**Comment by kjozwiak** [comment]
The above requires `1.67.105` or higher for `1.67.x` verification 👍

**Comment by MadhaviSeelam** [comment]
```
Brave | 1.67.107 Chromium: 126.0.6478.26 (Official Build) beta (64-bit)
-- | --
Revision | 2831369c7540d93e98f38d9b463f6762430a7982
OS | Windows 11 Version 23H2 (Build 22631.3672)
```
Shared steps: 

- Installed 1.67.107 
- launched Brave
- logged into Leo as a premium existing user


Scenario 1: Summarize, close Leo panel and summarize text via context menu

- load an article
- clicked Summarize the page
- close the panel
- select text and summarize via Leo tools

Confirmed `Summarize` button is not shown.  `Suggest questions` button shown as expected

![image](https://github.com/brave/brave-browser/assets/98358127/1bbd78c0-98ab-4056-941d-24599523dcd0)

Scenario 2: summarize text via context menu and switch tabs

- load an article
- clicked Summarize the page
- select text and summarize via Leo tools
- switch tabs and return to Leo panel

Confirmed `Summarize` button is not shown. `Suggest questions` button shown as expected

https://github.com/brave/brave-browser/assets/98358127/9e7bf726-78a6-4417-9e37-5ecc0662877a
