### ISSUE TITLE
Request for TLS 1.3 toggle or TLS 1.2 removal

### ISSUE THREAD

**Issue by JorgeCepeda** [brave/brave-browser#36545]
I have looked for "tls 1.2" and "tls 1.3" with no result about this request

## Description
Toggle for forcing TLS 1.3

## Steps to reproduce

   1. Go to options
   2. Look for a way to force a minimum of TLS 1.3

## Actual result
Nothing found, but there's a command line argument for launching brave directly with a minimum TLS version

## Expected result
Finding an in-browser toggle

## Issue reproduces how often
Easily reproduced

## Device details
   - Install type (ARM, x86): x86
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Android 14; Build/UP1A.231005.007
   
## Brave version
Brave 1.63.165, Chromium 122.0.6261.94

## Additional information
Alternatives are not adding it and
 -Drop support of TLS 1.2 with its weak encryption algorithms (mostly RSA as reported in [SSL Labs](https://clienttest.ssllabs.com:8443/ssltest/viewMyClient.html))
 Blocker: #1852
 -Doing nothing about it, which is also valid since TLS 1.2 is still considered mostly secure

**Comment by bsclifton** [comment]
cc: @diracdeltas @fmarier

**Comment by fmarier** [comment]
Disabling TLS 1.2 seems fairly risky from a webcompat point of view, so this option could be a bit of a footgun for users.

It sounds like you have tried the command-line argument. How was your experience with it? Did you run into many sites for which you had to enable TLS 1.2 again in order to connect?

**Comment by JorgeCepeda** [comment]
I only saw that I had to build the app to make it work and I didn't know how to, so I couldn't try it. My guess is that lots of pages wouldn't connect since when checking the connection some use TLS 1.2

How exactly can I launch brave with arguments on Android? I also don't know where I found the instructions.

According to [SSL Pulse](https://www.ssllabs.com/ssl-pulse/) about 30% of the pages don't support TLS 1.3

**Comment by fmarier** [comment]
Ah sorry, I missed the fact that you were on Android. I don't know of a way to specify command-line options on that platform.

If we're talking about a setting that would break 30% of websites, I'd say it's probably too early to offer that. We could revisit later though. TLS adoption is going much faster then it used to.

**Comment by fmarier** [comment]
We don't really have a label like `closed/waiting-for-ecosystem-to-migrate` so I'll use `closed/wontfix` to mark it as something we're not going to do in the short term.

I do appreciate the idea though and if it affected a smaller number of sites, I think it could be a good idea for an "extra-secure" browser.
