### ISSUE TITLE
Leo query set to current URL, can't be changed

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#36542]
## Description 
The only Leo query possible seems to be the current URL. Querying Leo leads to a blank screen.

## Steps to reproduce 

   1. Type a query - Leo is not suggested ![image](https://github.com/brave/brave-browser/assets/1129003/90fab039-7dca-472d-928d-cfdb5b0904cc)
   2. Hit enter to ask Brave Search instead ![image](https://github.com/brave/brave-browser/assets/1129003/c2674e19-40ee-4a28-986c-5b54aa3285e5)
   3. Click on the address bar, the current url is shown and the query suggested for Leo is that url 
![image](https://github.com/brave/brave-browser/assets/1129003/aac85e1b-fb00-443e-9b1e-d919eef353d6)
   4. Hit backspace to replace the url with a query, but the suggestion remains, even after typing a new query ![image](https://github.com/brave/brave-browser/assets/1129003/472034c2-cd1a-4679-a86e-aa8ed87ba4d4)

## Actual result 
Leo should be queried for whatever the user typed and that should actually work

## Expected result
Leo can only be queried about the current URL

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes (but only half the screen turns blank)
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 6
   - Android version: 16 (GrapheneOS 2024030300)
   
## Brave version
1.63.165, Release channel

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by SergeyZhukovsky** [comment]
So the issue basically due to global autocomplete settings is disabled `Settings -> Brave Shields & privacy -> Show autocomplete in address bar`. We should either hide `Setting->Leo->Show autocomplete in address bar` when the global autocomplete setting is off or perhaps better imo to show it as off in Leo section and once a user tried to enable it, give a warning that this move is going to enable global autocomplete setting as well.

**Comment by SergeyZhukovsky** [comment]
cc @mattmcalister and @aguscruiz for the ideas and design

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240322.023 release-keys
Brave build: 1.66.95
Chromium: 124.0.6367.91 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/22943#issue-2226351755
2. *Verify*

**ACTUAL RESULTS:**
- Verified that Leo's suggestion works when `Show autocomplete in address bar` is ON or OFF
- Verified that Leo's suggestion is not tied up to a current URL/page

---------------------------

|`Show autocomplete in address bar` is ON|`Show autocomplete in address bar` is OFF|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/9e9dd99b-2291-4198-948a-a5140415512c) | ![2](https://github.com/brave/brave-browser/assets/128532965/bab12744-b0cf-47a6-aee4-2f7a6f7cc70a) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/1f59c30e-a596-4742-b713-e131cdf4a301) | ![2](https://github.com/brave/brave-browser/assets/128532965/308c4350-0172-4576-b259-0440de623a11) |

https://github.com/brave/brave-browser/assets/128532965/d5422281-b4e5-4891-a911-3533aead07d5

https://github.com/brave/brave-browser/assets/128532965/0ddf95b5-3e80-458c-b096-9e923132e00b
