### ISSUE TITLE
Implement new password creation screen when accessing Brave Wallet for the first time

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#36552]
![image](https://github.com/brave/brave-browser/assets/3308503/db343966-1b1b-4b31-9632-85d594d212dc)

Figma design: https://www.figma.com/file/oXIiv45pIhF2RGlpEjOfUg/Wallet-onboarding?node-id=6223%3A70942&mode=dev

Main umbrella issue: https://github.com/brave/brave-browser/issues/35294

## Description

Implement new password creation screen as part of the onboarding flow when accessing Brave Wallet for the first time.

### Additional information

Implement new custom view that shows the strength of a password based on its lenght and shows a checkmark when the passwords match.

Migrate away from deprecated pager adapter in favor of `FragmentStateAdapter` and `ViewPager2`.

**Comment by StephenHeaps** [comment]
I hit a bug on Android release that should be tested against with this change. Pressing right-arrow key on hardware keyboard will bypass password input for Create Wallet and Restore Wallet (you will never pass `Creating Wallet...` screen).

STR:
1. Attach hardware keyboard
2. Do not enter a password for create/restore wallet
3. Press right-arrow key on hardware keyboard

Create Wallet:

https://github.com/brave/brave-browser/assets/5314553/23178d3f-43a1-4829-8b59-cc7d7f3c8e15


Restore Wallet:

https://github.com/brave/brave-browser/assets/5314553/2db42b93-5830-4649-aae4-16ac69212a0f

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.65.104 x64 build
- Verified steps from [brave/brave-core#22459](https://github.com/brave/brave-core/pull/22459)
- Verified new password creation screen is shown when creating new wallet
- Verified on both dark and light theme
- Encountered [#37358](https://github.com/brave/brave-browser/issues/37358), [#37360](https://github.com/brave/brave-browser/issues/37360)

Note: Recording is on Emulator for the same device as physical device doesn't record native screen for wallet creation

https://github.com/brave/brave-browser/assets/17010094/9ca4bb35-2794-4876-94ab-a797b8cb742d
