### ISSUE TITLE
vertical line separator on Bookmarks Toolbar re-appears after browser relaunch - follow up to #6043

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#36554]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/6043

If you unselect the "Show All Bookmarks Button" the "All Bookmarks" option and the vertical line separator disappear from view as expected. If you close and relaunch the browser, "All Bookmarks" is still hidden from view, but the vertical line separator shows back up. It is unnecessary as the "All Bookmarks" option is not displayed.

## Steps to Reproduce

   1. Have at least one bookmark in "Other Bookmarks" and the Bookmarks Toolbar visible in some way (NTP only is fine)
   2. Right click on the Bookmarks Toolbar
   3. Unselect "Show All Bookmarks Button"
   4. See "All Bookmarks" and vertical line separator are no longer displayed
   5. Close and relaunch the browser
   6. "All Bookmarks" is not displayed, but the vertical line separator is

## Actual result:

vertical line separator is displayed:

<img width="106" alt="Screenshot 2024-03-05 at 1 17 05 PM" src="https://github.com/brave/brave-browser/assets/28145373/2a52bd28-f6c0-431d-97f0-66f80df53fbd">

## Expected result:

no vertical line separator:

<img width="171" alt="Screenshot 2024-03-05 at 1 57 23 PM" src="https://github.com/brave/brave-browser/assets/28145373/0d18d2ca-e96b-4472-89d0-cf178f3af6b5">

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.64.95 Chromium: 122.0.6261.94 (Official Build) beta (x86_64)
-- | --
Revision | 6f4193fbcee7c358ae3684f777faa9f12e52206e
OS | macOS Version 13.6.4 (Build 22G513)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes 1.64.x
- Can you reproduce this issue with the nightly channel? yes 1.65.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @sangwoo108

**Comment by kjozwiak** [comment]
The above requires `1.68.124` or higher for `1.68.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.68.124 Chromium: 127.0.6533.57 (Official Build) (x86_64)
-- | --
Revision | d048917c488542dc56e67059011b2cf9d6043bb9
OS | macOS Version 13.6.7 (Build 22G720)
```
