### ISSUE TITLE
Wallet Balance Fetching is Broken

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#36559]
## Description 

Wallet Balance Fetching is Broken

## Steps to Reproduce

   1. Open the `Wallet`
   2. Balances are not being fetched

## Actual result:

![Screenshot 14](https://github.com/brave/brave-browser/assets/40611140/d4ece711-4b6e-40b8-8f87-707712ad21a0)

https://github.com/brave/brave-browser/assets/40611140/9757f5de-7b78-4d6f-9b3c-71bffc73852c

## Expected result:
Should load balances.

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by josheleonard** [comment]
Non issue
