### ISSUE TITLE
Fix issue with public keys when redeeming tokens

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#3655]
## Description 
Fix issue with public keys when redeeming tokens as we are incorrectly sending the wallet public key instead of the issuers public key

## Steps to Reproduce

   1. View an Ad
   2. Close browser
   3. Relaunch browser
   4. Confirm on Ads Serve that token was cashed out (additional steps are required on Ads Serve, please check with @maikelmclauflin and Jimmy)

## Actual result:
Server fails to cash out token due to incorrect public key

## Expected result:
Server cashes out token

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Dev and Nightly

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional Information
Speak to @amirsaber for help with testing server side

**Comment by btlechowski** [comment]
Verification passed by Geeta on

Brave | 0.63.44 Chromium: 74.0.3729.75 (Official Build) beta (64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Windows 10 OS Build 17134.523
