### ISSUE TITLE
[Brave News]: Publisher list in side panel collapses after adding/updating publishers/channels

### ISSUE THREAD

**Issue by LorenzoMinto** [brave/brave-browser#36550]
- Open Brave News
- Click + in the side panel headers or Customise button on the bottom right 
- Add publisher/channel

Unexpected behaviour: Navigation panel sections should not collapse when something is added/removed. See in screenshot how `Channels` section has collapsed.

<img width="1057" alt="Screen Shot 2024-05-23 at 11 38 56 AM" src="https://github.com/brave/brave-browser/assets/13190144/121b672a-9879-4693-b7fa-2f7f999b5dc5">

**Comment by TevinWang** [comment]
Hi @LorenzoMinto I'm happy to take this on as the first contribution!

**Comment by LorenzoMinto** [comment]
Hey @TevinWang! That would be awesome. Let me know if you have any questions 👍

**Comment by Hamza-H10** [comment]
hi, I have tried to reproduce this but seem like this working fine, i noticed that to some channel we need to click twice to add it in the list. please provide clarity if this is resolved or not ?

**Comment by scottish3dprinter** [comment]
I could not reproduce this issue what os are you on?

**Comment by shreyaslax** [comment]
Hi @LorenzoMinto I'm happy to take this on as the first contribution.

**Comment by LorenzoMinto** [comment]
This issue is still open and any contribution is welcome. Please open a PR and me or someone in the team will review. @scottish3dprinter I'm on OSX.

**Comment by brandedcow** [comment]
@LorenzoMinto Please let me know if I need to provide anything addition for the PR.

**Comment by LorenzoMinto** [comment]
Nice to see this fixed. Thanks for your contribution @brandedcow 💯
