### ISSUE TITLE
consider only displaying "Show All Bookmarks Button" option in context menu if there are bookmarks in Other Bookmarks

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#36555]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/6043

If you don't have any bookmarks under "Other Bookmarks" then the "Show All Bookmarks Button" option on the context menu doesn't mean anything. It could be confusing to select/deselect that option and seemingly nothing happens.

## Steps to Reproduce

   1. Have some bookmarks, but nothing in the "Other Bookmarks" folder
   2. Have Bookmarks Toolbar displayed somehow (just on NTP is fine)
   3. Right click on the Bookmarks Toolbar, see "Show All Bookmarks button" is checked
   4. Unselect this option 
   5. Notice there's no difference in how the Bookmarks Toolbar looks since this option is only applicable when there are bookmarks under "Other Bookmarks".

## Actual result:

no difference in display of Bookmarks Toolbar:

Example | Example
--- | ---
<img width="1242" alt="Screenshot 2024-03-05 at 2 49 12 PM" src="https://github.com/brave/brave-browser/assets/28145373/e51319ba-7c6e-46df-b5d1-af681e642cba"> | <img width="1247" alt="Screenshot 2024-03-05 at 2 49 23 PM" src="https://github.com/brave/brave-browser/assets/28145373/4298036a-ebdc-48b9-8fd8-30026708c00a">

## Expected result:

Consider only showing "Show All Bookmarks Button" if this option is applicable

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.64.95 Chromium: 122.0.6261.94 (Official Build) beta (x86_64)
-- | --
Revision | 6f4193fbcee7c358ae3684f777faa9f12e52206e
OS | macOS Version 13.6.4 (Build 22G513)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? 1.64.x yes
- Can you reproduce this issue with the nightly channel? 1.65.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron

**Comment by ajayseeker** [comment]
Hi @sangwoo108 and @LaurenWags, I'd like to take a shot. Can you please assign me this issue?

**Comment by bsclifton** [comment]
@ajayseeker assigned - go for it 😄 Let us know if there are questions. Getting setup and building can be a bit of a challenge if you haven't done it before

**Comment by ajayseeker** [comment]
> @ajayseeker assigned - go for it 😄 Let us know if there are questions. Getting setup and building can be a bit of a challenge if you haven't done it before

sure @bsclifton 😄. Actually, I've the setup ready, under @sangwoo108's guidance I was able to work on [issue1](https://github.com/brave/brave-browser/issues/37125) and [issue2](https://github.com/brave/brave-browser/issues/25602) in recent past. Will definitely reach out if I need any help.

**Comment by ajayseeker** [comment]
Hi @sangwoo108 and @LaurenWags,  I've made the code changes and raised a [PR](https://github.com/brave/brave-core/pull/23741), please take a look. 
However, I believe we need to make changes in `browser/ui/views/bookmarks/brave_bookmark_context_menu_unittest.cc`. 
Also, I guess we need to add a unit test in the same file and possibly add a browsertest too somewhere. I'm looking into the test part now.  
@sangwoo108  What are your thoughts on test part?

**Comment by sangwoo108** [comment]
unittest will be enough. Left some comments on it. Thanks for the patch!

**Comment by bsclifton** [comment]
Nice work @ajayseeker 😄

**Comment by ajayseeker** [comment]
> Nice work @ajayseeker 😄 

Thanks @bsclifton 😀! Looking forward to contribute in better ways.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.68.122 Chromium: 127.0.6533.43 (Official Build) beta (x86_64)
-- | --
Revision | d9f43bf666718cb9878eab117e104f5d5d39bbbe
OS | macOS Version 13.6.7 (Build 22G720)
```
