### ISSUE TITLE
[Brave News]: Separate BraveNews* classes from the PrefService

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#36558]
Currently, it's extremely difficult to push Brave News services off the main thread, as they're closely intertwined with the PrefService.

As a first step to moving BraveNews off the main thread, we should remove any PrefService access from the classes.

**Comment by stephendonner** [comment]
## Verified `PENDING` using

```

```

Subscribe to lots of publishers as you can, as quickly as you can.
Restart Brave
The list of Publishers should not have changed
Subscribe to lots of channels as quick as you can
Restart Brave
The list of Channels should not have changed
Subscribe to a publisher - the feed should say updates are available
Subscribe to a channel - the feed should say updates are available

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240216.010 release-keys
Brave build: 1.65.96 
Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
```

Filed follow-up issue #37245
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/22439#issue-2165766622
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the list of `Publishers` should not have changed
- Verified that the list of `Channels` should not have changed
- Verified that the feed should say updates are available when subscribed to a `Publisher` or `Channel`

---------------------------

https://github.com/brave/brave-browser/assets/128532965/cad332a6-1269-43a3-92d7-e3966dd30a75

https://github.com/brave/brave-browser/assets/128532965/4be613d5-9c05-4974-b748-6ae8658e9e3f
