### ISSUE TITLE
Move `Appearance > Content` to the top level, and put `Playlist` there

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#36571]
Currently, `Appearance > Content` settings has things to do with 
* content browsing, such as font and page zoom, and etc. 
* content related feature, e.g. speedreader

As Playlist is also a content related feature, we should move the playlist into that section.
And `Appearance > Content` is a little bit hard to find, we should bring it up to the top level, so that it can be found on the sidebar.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.65.80 Chromium: 123.0.6312.29 (Official Build) nightly (64-bit)
-- | --
Revision | cd0c2b9c6f07e8f01724294c8d7e37393a8c3a38
OS | Windows 10 Version 22H2 (Build 19045.4170)
```

### Steps:
1. installed `1.65.80`
2. launched Brave
3. 

## Playlist `Enabled`

example | example | example
----------|-----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/48a2cec8-67fb-404a-92ba-d1f5fc8baf59) | ![image](https://github.com/brave/brave-browser/assets/387249/a3a5e4c0-d676-42ec-aae3-afb7cb38890f) | ![image](https://github.com/brave/brave-browser/assets/387249/256c3139-e24b-46f5-a99a-94032e66b662)


## Playlist `Disabled`

example | example | example
----------|-----------|----------
