### ISSUE TITLE
Update Jitsi URL when using Brave Talk on staging servers

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#36579]
# Description

If the domain is "talk.brave.software", then we need to update the [`serverURL`](https://github.com/brave/brave-core/blob/25ff2f497dd0d67bc99a9137937933c8c2c525fe/ios/brave-ios/Sources/BraveTalk/BraveTalkConferencingOptions.swift#L15C15-L15C24) to use `https://stage.8x8.vc/` instead of `https://8x8.vc/`

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.3.1` using version `1.65.114 (124.0.6367.60)`

- Ensured that server url is pointing to `https://stage.8x8.vc/` for `talk.brave.software`
- Ensured that server url is still pointing to https://8x8.vc for the production site. 

https://github.com/brave/brave-browser/assets/17885425/b23faea9-4b2d-47a7-916e-f6d11f01dd9c
