### ISSUE TITLE
[Wallet] Perf: remove requests for and storage of uncached tokens list

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#36577]
## Description 

Remove uncached userVisible tokens list in the redux store and remove the `refreshVisibleTokensInfo` handler action as it is triggered multiple times during initial page load.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

Profile results when loading NFTs page (brave://wallet/crypto/portfolio/nfts)
<img width="908" alt="Screenshot 2024-03-06 at 3 20 34 PM" src="https://github.com/brave/brave-browser/assets/30185185/5588501a-ca4b-45bf-b441-42101d1ba3cf">

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (64-bit)
-- | --
Revision | 5d9143e1a0812c53bdc27fd5384591254306a88c
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from [brave/brave-core#22476](https://github.com/brave/brave-core/pull/22476)
- Verified no error when loading NFT details page
- Verified able to pin NFTs successfully without any regression
- Verified Dapp connection screen works as expected without any regression
- Verified user tokens continue to show/work as expected without any regression
- Encountered [#37207](https://github.com/brave/brave-browser/issues/37207)
