### ISSUE TITLE
Implement network selection during Wallet onboarding flow

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#36578]
![image](https://github.com/brave/brave-browser/assets/3308503/cbc55c44-eef9-4c5f-8be2-d906512d6920)

## Description

After terms of use screen and before password creation screen Android is missing network selection screen.

⚠ Before starting with the actual implementation sync up with the design team.

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.66.101 x64 Beta build
- Verified steps from [brave/brave-core#22962](https://github.com/brave/brave-core/pull/22962)
- Verified Bitcoin is listed during onboarding on the network selection screen
- Verified unchecking Bitcoin on network selection and creating wallet doesn't add the Bitcoin account
- Verified selecting show testnets and selecting Bitcoin Testnet and finishing onboarding creates both Mainnet and Testnet account
- Verified searching for networks name during onboarding lists all networks that match the search term
- Verified selecting testnets creates testnets accounts after onboarding is complete
