### ISSUE TITLE
Speedreader should auto-activate on Time.com

### ISSUE THREAD

**Issue by yokoffing** [brave/brave-browser#36583]
## Description 

Speedreader should automatically trigger when users visit the Time magazine website. Users can still manually activate Speedreader, but it does not automatically activate as intended.

Example: `https://time.com/6344308/weight-loss-drug-zepbound/`

## Steps to Reproduce

   1. Go to `https://time.com/6344308/weight-loss-drug-zepbound/`
   2. Speedreader does not activate automatically.

**Comment by stephendonner** [comment]
Confirmed using 
Brave | 1.64.96 Chromium: 122.0.6261.111 (Official Build) beta (x86_64)
-- | --
Revision | fb9feca2d1f25ea20265752e8ecdf548a6925bd4
OS | macOS Version 11.7.10 (Build 20G1427)

Even though I have "Always use Speedreader for this site" checked, I have to click on the Speedreader icon to force it, each time.

**Comment by stephendonner** [comment]
cc @boocmp @rebron

**Comment by boocmp** [comment]
At the moment, It's by desing, but we have several reports like this from users and mates... I'm going to change the behavior in how we decide to enable speedreader in the automatic mode. We will ignore any url patterns if the user explicitly enabled speedreader on the page. Perhaps, this may lead to a slight decrease in page loading speed on pages that could not actually be "speedreaded", but I suppose this is not a big fee for not confusing users. It will be to implemented it under the feature flag to prevent any surprises.

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave	1.66.58 Chromium: 123.0.6312.105 (Official Build) nightly (x86_64) 
Revision	3ba75ef579083c6c0dd850274c767735dd01f315
OS	macOS Version 14.5 (Build 23F5049f)
```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
 ```
Brave | 1.66.59 Chromium: 123.0.6312.105 (Official Build) nightly (64-bit)
-- | --
Revision | 2714c7ac837e7b7693b1b56a82effdf57e04fe09
OS | Windows 11 Version 23H2 (Build 22631.3374)
```
#### Case 1: Default - `PASSED`
<details>

1. installed `1.66.59`
2. launched Brave
3. loaded `www.time.com`
4. clicked on the headline article link (`https://time.com/6963088/disney-shareholder-meeting-bob-iger/`)
5. confirmed I saw the `Turn on Speedreader` icon in the URL bar
6. opened `brave://settings/braveContent`
7. confirmed `Speedreader` preference is toggled to `Off` by default

#### Confirmed page rendered _without_ Speedreader mode, as expected

`time.com` article | `Speedreader` toggled `Off`
-------------------|-----------------------------
![image](https://github.com/brave/brave-browser/assets/98358127/d46e8447-8f14-4442-b91f-41e44fa03d1d)|![image](https://github.com/brave/brave-browser/assets/98358127/1810a13f-dd58-4a71-b5c4-7b65722351c1)
</details>

#### Case 2: Always use Speedreader for this site - `PASSED`
<details>

1. Continued from `Case 1`
      -`https://time.com/6963088/disney-shareholder-meeting-bob-iger/` loaded in a tab
2. clicked on `Turn on Speedreader` icon in the URL bar
3. confirmed `Speedreader` mode enabled/rendered
4. clicked on the `Tune Speedreader` icon in speedreader toolbar
5. confirmed `Always use Speedreader for this site` on the speedreader toolbar was toggled to `Off` by default
6. toggled it to `On`
7. loaded `www.time.com` again in the same tab
8. clicked on another article (https://time.com/6960270/solar-eclipse-2024-path-of-totality-map/)
9. confirmed it rendered in `Speedreader` mode
10. opened `brave://settings/brave-content` and reconfirmed `Speedreader`'s global pref was `Off`

#### Confirmed `Always use Speedreader for this site` pref is enabled on a per-domain basis

step 3| step 5| step 6| step 7| step 9 | step 10
------|------|------|---------|----------|---------
![image](https://github.com/brave/brave-browser/assets/98358127/7f72b0f1-ff99-43f4-b8dc-c34921349f03)|![image](https://github.com/brave/brave-browser/assets/98358127/79456e9f-3889-45f3-96c4-6387747fb7bc)|![image](https://github.com/brave/brave-browser/assets/98358127/0df710fb-0e36-4ea2-bf28-6a1d4c801562)|![image](https://github.com/brave/brave-browser/assets/98358127/1ac0a0e3-b758-465d-8ea0-96f7d25001e7)|![image](https://github.com/brave/brave-browser/assets/98358127/2f69eb20-def8-4092-a5b1-c25ae6422aa7)|![image](https://github.com/brave/brave-browser/assets/98358127/f52492fb-346d-4c45-a5d3-d1cedb6b1521)|!![image](https://github.com/brave/brave-browser/assets/98358127/cb41daba-2341-4e15-a9ca-71055231b219)
</details>

#### Case 3: Always use Speedreader for this site - Second domain on a different tab - `PASSED`
<details>

1. continued from `Case 2`
      -Enabled `Always use Speedreader for this site` for Time.com article
2. opened latimes.com in a new tab
3. clicked https://www.latimes.com/california/story/2024-04-01/where-and-how-to-watch-the-solar-eclipse-in-california on the home page
4. clicked on `Turn on Speedreader` icon in the URL bar
5. confirmed `Speedreader` mode enabled/rendered
6. clicked on the `Tune Speedreader` icon in speedreader toolbar
7. enabled `Always use Speedreader for this site` on the speedreader toolbar for the site
8. loaded latimes.com in the same tab and clicked on a link for  https://www.latimes.com/world-nation/story/2024-04-05/rare-magnitude-4-7-earthquake-strikes-new-jersey-felt-across-new-york-region 
9. confirmed it rendered in `Speedreader` mode

#### Confirmed `Always use Speedreader for this site` pref is enabled on a per-domain basis

step 1| step 3 | step 5| step 7 | step 9  
------|------|------|-------- | -----  
![image](https://github.com/brave/brave-browser/assets/98358127/9d27fd7a-889a-4a53-bb85-4d98a0224d08)|![image](https://github.com/brave/brave-browser/assets/98358127/c0eaaa9d-045b-4c64-8534-877817a74350)|![image](https://github.com/brave/brave-browser/assets/98358127/ea3a70c8-bb25-40eb-bb74-39e2a4915305)|![image](https://github.com/brave/brave-browser/assets/98358127/b6c55f90-ccdf-4136-9ca4-c67c77a642dd)|![image](https://github.com/brave/brave-browser/assets/98358127/30cf187a-facd-4eab-9c0d-d0ae66b9089e)
</details>

## Case 4: `Speedreader` toggled `On` in `brave://settings/braveContent` - `FAILED`
<details>

1. installed `1.66.58`
2. launched Brave
3. opened `brave://settings/braveContent`
4. toggled `Speedreader` to `On`
5. loaded `www.time.com`
6. clicked on an article https://time.com/6963961/solar-eclipse-chasers-2024/
7. loaded `https://www.azcentral.com/`
8. clicked on an article https://www.azcentral.com/story/sports/ncaab/final-four/2024/04/05/uconn-dan-hurley-arizona-state-bobby-hurley-final-four-comment/73219365007/
9. loaded on bbc.com and click an article

- page/site does NOT render in `Speedreader` mode for Time.com & BBC.com.  
- Other sites are working (azcentral.com) as expected

step 3 | step 4| step 7 | step 8 |step 9
 ---------|----------|-------|-----|------
![image](https://github.com/brave/brave-browser/assets/98358127/72086e64-4e2e-4a39-95d2-cd1cfca3067d)|![image](https://github.com/brave/brave-browser/assets/98358127/8a6c1fab-469d-4cfd-bce1-367f8d5c490b)|![image](https://github.com/brave/brave-browser/assets/98358127/47ec154c-ae0a-4b65-9e56-1792736c43fa)|![image](https://github.com/brave/brave-browser/assets/98358127/60ab6188-4b58-498e-b4ad-ae14ffa4b5f0)|![image](https://github.com/brave/brave-browser/assets/98358127/10676715-f9c6-41d8-8ff9-aad4c0167706)
</details>

#### Case 6: Always use Speedreader for all sites - `FAILED`
<details>

1. installed `1.66.58`
2. launched Brave
3. loaded `www.time.com`
4. clicked on the headline article (`https://time.com/6963961/solar-eclipse-chasers-2024/`)
5. clicked on the `Turn on Speedreader` icon
6. toggled `Always use Speedreader for all sites` to `On` in the speedreader toolbar
7. opened `www.time.com`
8. clicked on the headline article again
9. open a new tab and enabled news
10. clicked on top news card in the brave news feed (https://www.foxnews.com/world/colombian-guerrillas-launch-multiple-attacks-military-ceasefire-breaks-down) 
11. clicked second card in the brave news feed - (https://www.espn.com/wwe/story/_/id/39871242/a-lapsed-fan-guide-wrestlemania-40-rock-back-cody-rhodes-finish-story-roman-reigns)

Noted that the site does NOT render in `Speedreader` mode for Time, Foxnews
other sites (espn.com) article shown in `Speedreader` mode

step 4| step 6| example | example | step 10| step 11
---------|----------|---------|----------|--------|------
![image](https://github.com/brave/brave-browser/assets/98358127/41ef279b-4f84-4e47-a941-82cb70c7c965)|![image](https://github.com/brave/brave-browser/assets/98358127/aab07012-8b55-4e86-82bc-12ca7509c475)|![image](https://github.com/brave/brave-browser/assets/98358127/ded38c0d-8baa-4649-87ea-5cab387df83d)|![image](https://github.com/brave/brave-browser/assets/98358127/9d89fb51-92ed-4c1d-8a1e-9558a6cff789)|![image](https://github.com/brave/brave-browser/assets/98358127/d85eaada-c21b-4911-b343-a51092db2373)|![image](https://github.com/brave/brave-browser/assets/98358127/f1fc59a7-9716-4c1b-aceb-bf5eb0320aa1)

</details>
