### ISSUE TITLE
Implement Brave Leo on iOS

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#36585]
## Description: 

Implement Brave Leo in iOS

Related issues:
- https://github.com/brave/brave-ios/issues/8135
- https://github.com/brave/brave-ios/issues/8134
- https://github.com/brave/brave-ios/issues/8133
- https://github.com/brave/brave-ios/issues/8132
- https://github.com/brave/brave-ios/issues/8131
- https://github.com/brave/brave-ios/issues/8130
- https://github.com/brave/brave-ios/issues/8129
- https://github.com/brave/brave-ios/issues/8128
- https://github.com/brave/brave-ios/issues/8127
- https://github.com/brave/brave-ios/issues/8126

**Comment by kjozwiak** [comment]
The above requires `1.63.171` or higher for `1.63.x` verification 👍

@Uni-verse @hffvld lets the issues outlined via https://github.com/brave/brave-browser/issues/36585#issue-2172081399 as a guide of the different areas that we should check/run through but can add the verification notes via this issue. There's also https://github.com/brave/brave-browser/issues/36596#issue-2172468221 which address some design changes.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 17.4` using the following build(s):

```
1.63.176 Chromium: 122.0.6261.128 (Official Build) unknown (64-bit)
--- | ---
Revision | 0767ff0f97fb...
OS | iOS
```

### Restoring `Leo` credentials from `Android` account that purchased using `CC#` - **`PASSED`**

* downloaded/installed `1.63.176 Chromium: 122.0.6261.128` via TF
* tapped on `Hamburger Menu` -> `Leo` and ensured that the onboarding/T&S are being displayed
* ensured that there's no strings/text indicating `PREMIUM` and displaying `LIMITED` for `Mixtral` & `Claude Instant`
* logged into `account.brave.com` and logged into an account that already has a `Leo` subscription
  * this account purchased `Leo` on `Android` via the `GPS` and used a `CC#`
* once logged into the account, ensured that the subscription plan is being displayed with the ability to `Refresh Leo`
  * ensured that it mentions `Purchased on Android`
* tapped on `Refresh Leo` and ensured that the credentials were loaded without any issues in a reasonable time (~10s)
  * ensured that `You have active credentials loaded!` is being displayed via `account.brave.com`
* ensured that `Leo` now appears as `PREMIUM` and both `Mixtral` & `Claude Instant` are listed as `UNLIMITED`
* ensured that `Advanced Settings` is listing the all the `Subscription` information (expirey date etc..)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|-----------------
![IMG_0065](https://github.com/brave/brave-browser/assets/2602313/ce4b78d7-c231-40fa-9a60-c60f870d3f63) | ![IMG_0066](https://github.com/brave/brave-browser/assets/2602313/f03f62b9-4cc8-4ace-a33a-92bb2019b68a) | ![IMG_0067](https://github.com/brave/brave-browser/assets/2602313/8a12c772-fc20-4b34-9d0a-c881758b133e) | ![IMG_0068](https://github.com/brave/brave-browser/assets/2602313/5103414c-a772-4c9e-8cd3-908e6af5a71a) | ![IMG_0069](https://github.com/brave/brave-browser/assets/2602313/f987e74c-453f-4172-be59-4f29de04393b)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|-----------------
![IMG_0070](https://github.com/brave/brave-browser/assets/2602313/ce5e439a-0132-478a-9f9c-3ac13d047cbe) | ![IMG_0071](https://github.com/brave/brave-browser/assets/2602313/4245e8fa-c052-4482-ac01-1504de45d89f) | ![IMG_0072](https://github.com/brave/brave-browser/assets/2602313/cd67facb-5f51-415a-b5e7-026c104019c3) | ![IMG_0078](https://github.com/brave/brave-browser/assets/2602313/9a92a7c8-b5bf-4071-88a2-b8d00324a968) | ![IMG_0075](https://github.com/brave/brave-browser/assets/2602313/b04f0634-7149-4239-b7a3-89614454b721)

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.3.1` using version `1.63.179`

- Verified using active credentials from desktop account to upgrade to Leo Premium after upgrading from `1.62.2` to `1.63.179`
- Went through and spot checked all the issues mentioned in https://github.com/brave/brave-browser/issues/36585#issue-2172081399
    - [x] Chat contextual menu
    - [x] Feedback submit UI
    - [x] Provide feedback UI
    - [x] Enter prompt input UI
    - [x] Suggested follow ups UI
    - [x] Chat UI implementation
    - [x] Top navigation UI
    - [x] Default model menu UI
    - [x] Brave-Leo settings menu UI
    
Example | Example | Example | Example
-|-|-|-
![IMG_5857](https://github.com/brave/brave-browser/assets/17885425/da614954-fa6c-4758-b523-e927fe1c7953) | ![IMG_5858](https://github.com/brave/brave-browser/assets/17885425/d7617eaa-5eb4-4503-b9c0-7437c21d9d79) | ![IMG_5871](https://github.com/brave/brave-browser/assets/17885425/ce036ca3-0989-4275-a59d-dcdf43691536) | ![IMG_5873](https://github.com/brave/brave-browser/assets/17885425/f97bec33-3955-4b1e-b603-549acf48df47)
![IMG_5860](https://github.com/brave/brave-browser/assets/17885425/beb061a3-4e28-4eb8-af60-544ca98f5f94) | ![IMG_5861](https://github.com/brave/brave-browser/assets/17885425/0f62ffe5-84c3-416f-8d03-3e58cf95f14e) | ![IMG_5862](https://github.com/brave/brave-browser/assets/17885425/37162ab2-b293-41e8-b5b1-acce87bd6450) | ![IMG_5863](https://github.com/brave/brave-browser/assets/17885425/3e3e7fac-0dd8-4e87-87c9-560666e244c2)
![IMG_5865](https://github.com/brave/brave-browser/assets/17885425/ac0f4278-cc6f-473e-b0ad-a8a7dd2d14d8)
![IMG_5866](https://github.com/brave/brave-browser/assets/17885425/0d6ce33e-0146-46ed-9ddf-e4ec871a6285) | ![IMG_5867](https://github.com/brave/brave-browser/assets/17885425/c1fedb3b-0e06-4856-b2f7-d73da0d56129) | ![IMG_5868](https://github.com/brave/brave-browser/assets/17885425/db9fe2e2-b7b5-42a3-8a2f-c5d02cfb92aa) | ![IMG_5869](https://github.com/brave/brave-browser/assets/17885425/853b2439-2202-434c-b96d-d056f42a3c7d)
