### ISSUE TITLE
Crash when quickly closing an NTP-SI tab right after its created 

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#36587]
## Steps to Reproduce 
1. Visit any page on iPad with Top-URL bar and Tabs showing.
2. Click the URL bar.
3. Tap on the PLUS sign to open a new tab.
4. Do it again.
5. Close all the newly opened tabs until you get back to the original page.

## Actual result:
Crashes

## Expected result:
No crash

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

## Brave Version:
Most likely as far back as 1.57 (when NTP-SI P3A was added)

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.4.1
- iPad Air / iPadOS 16.7.2
Brave build: 1.65 (96)
BraveCore: 1.65.96 (123.0.6312.86)
```

Filed follow-up issue #37224
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/36587#issue-2172230562
2. *Verify on `iPad` and `iPhone`*

**ACTUAL RESULTS:**
- Verify that `Brave` is not crashing. Observe that `Brave` is still crashing.
- Verified the same on both `iPad` and `iPhone`.

---------------------------

*iPhone*

https://github.com/brave/brave-browser/assets/128532965/f4c575a9-bb4c-46bb-86d5-d94c4f21e715

*iPad*

https://github.com/brave/brave-browser/assets/128532965/b630c995-ba1f-4ed1-b59d-65ee1f1e01a2
