### ISSUE TITLE
aichat: Include "token_count" in ai feedback request

### ISSUE THREAD

**Issue by porteron** [brave/brave-browser#36588]
We'd like to understand if negative Leo feedback is related to the amount of context used in a conversation with Leo.

- [ ] Create a new value `token_count` and pass it in the feedback request (`/1/ai/feedback/rating`). This should reflect the number of tokens that have been used up to the point of submitting feedback. 
    - The caveat here is that each model has a different definition of what defines a token. If it becomes too complicated we can estimate the value, maybe use `word_count` instead of `token_count`.

If the user has chosen to "Summarize this Page" or any other action that involves passing the page content into the context, that content _should_ be accounted for in the `token_count`.

cc @aekeus @brave/privacy-review-team

**Comment by nullhook** [comment]
maybe `char_count` makes sense here? tokens are a blackbox and differs from model to model. although, there is a general rule of thumb:

> A helpful rule of thumb is that one token generally corresponds to ~4 characters of text for common English text. This translates to roughly ¾ of a word (so 100 tokens ~= 75 words).

**Comment by porteron** [comment]
`char_count` should be fine
