### ISSUE TITLE
Add tab usage P3A metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#36592]
See https://github.com/brave/brave-browser/issues/32989 for question descriptions

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `iPhone 8 version 12` running `Brave Nightly 1.68(79)`

- Verified the test plan from https://github.com/brave/brave-core/pull/20159

### Brave.Core.LocationNewEntries

<details>
<summary>Brave.Core.LocationNewEntries = 0_PASSED</summary>

1. Clean profile `1.62.104`
2. Open brave://local-state in a new tab
3. Open a site in a new tab and open 10 or 15 new sites in the same tab
4. Look for the metrics `Brave.Core.LocationNewEntries` in brave://local-state file
5. The metrics `Brave.Core.LocationNewEntries` response value is `0` as expected [0. Less than 25% of total address bar entries performed in new tabs]

![IMG_4602](https://github.com/brave/brave-browser/assets/38657976/c5a377a9-caa9-433f-8a6f-84e762f22a08)


</details>

<details>
<summary>Brave.Core.LocationNewEntries = 1_PASSED</summary>

1. Clean profile `1.62.99`
2. Open brave://local-state in a new tab
3. Look for the metrics `Brave.Core.LocationNewEntries`
4. The metrics `Brave.Core.LocationNewEntries` response value is `1` as expected [1. 25% -50% of total address bar entries performed in new tabs]
![IMG_4603](https://github.com/brave/brave-browser/assets/38657976/05476eeb-7e51-456a-accb-0f96330b275e)


</details>

<details>
<summary>Brave.Core.LocationNewEntries = 2_PASSED</summary>

1. Clean profile `1.62.99`
2. Open brave://local-state in a new tab
3. Open 3 different sites in 3 new tabs
4. Open new sites in two existing tabs
6. Look for the metrics `Brave.Core.LocationNewEntries`
7. The metrics `Brave.Core.LocationNewEntries` response value is `2` as expected [2. 50% -75% of total address bar entries performed in new tabs]

![IMG_4601](https://github.com/brave/brave-browser/assets/38657976/7e1f1800-fc0d-4f50-8cff-afa98809e581)


</details>

<details>
<summary>Brave.Core.LocationNewEntries = 3_PASSED</summary>

1. Clean profile `1.62.99`
2. Open brave://local-state in a new tab
3. Open 3 different sites in 3 new tabs
4. Look for the metrics `Brave.Core.LocationNewEntries`
5. The metrics `Brave.Core.LocationNewEntries` response value is `3` as expected [3. More than 75% of total address bar entries performed in new tabs]

![IMG_4600](https://github.com/brave/brave-browser/assets/38657976/c6a87145-25cf-46da-b8de-724eeaa47218)


</details>

### Brave.Core.NewTabMethods

<details>
<summary>Brave.Core.NewTabMethods = 0_</summary>

1. Clean profile `1.62.99`
2. Open brave://local-state in a new tab
3. Look for the metrics `Brave.Core.NewTabMethods`
4. Confirmed that the metrics `Brave.Core.NewTabMethods` doesn't exists in brave://local-state file
5. Open 1 or more new tabs via hamburger settings menu
6. Reload brave://local-state file
8. Look for the metrics `Brave.Core.NewTabMethods`
9. Confirmed that the metrics `Brave.Core.NewTabMethods` response value is `0` as expected
</details>

<details>
<summary>Brave.Core.NewTabMethods = 1_</summary>

1. Clean profile `1.62.99`
2. Open brave://local-state in a new tab [New Tab is already opened by defalut]
3. Look for the metrics `Brave.Core.NewTabMethods`
4. The metrics doesn't exists
5. Open one or more new tabs via `+`  (I have opened 6 tabs via `+`)
6. Open 6 new tabs via hamburger settings menu, total no of tabs are 13 (6 NTP's opened via `+` and 6 NTP's opened via hamburger menu and 1 tab was opened by default when app was launched)
7. Reload brave://local-state file
8. Look for the metrics `Brave.Core.NewTabMethods`
10. The metrics `Brave.Core.NewTabMethods` response value is `1` as expected [1. 25% -50% of total new tabs created using [+] button]

![Screenshot_20231211_205141](https://github.com/brave/brave-browser/assets/38657976/e9338b5a-fa16-4958-b7a5-7a5d7780a2f7)

</details>

<details>
<summary>Brave.Core.NewTabMethods = 2_</summary>

1. Clean profile `1.62.99`
2. Open brave://local-state in a new tab [New Tab is already opened by defalut]
3. Look for the metrics `Brave.Core.NewTabMethods`
4. The metrics doesn't exists
5. Open one or more new tabs via `+`  (I have opened 6 tabs via `+`)
6. Open two new tabs via hamburger settings menu
7. Reload brave://local-state file
8. Look for the metrics `Brave.Core.NewTabMethods`
9. The metrics `Brave.Core.NewTabMethods` response value is `2` as expected [2. 50% -75% of total new tabs created using [+] button]

![Screenshot_20231211_205603](https://github.com/brave/brave-browser/assets/38657976/18403f1c-a7d5-47dd-9be1-fd3979304e7f)

</details>

<details>
<summary>Brave.Core.NewTabMethods = 3_</summary>

1. Clean profile `1.62.99`
2. Open brave://local-state in a new tab [New Tab is already opened by defalut]
3. Look for the metrics `Brave.Core.NewTabMethods`
4. The metrics doesn't exists
5. Open one or more new tabs via `+`  (I have opened 6 tabs via `+`)
6. Reload brave://local-state file
11. The metrics `Brave.Core.NewTabMethods` response value is `3` as expected [3. More than 75% of total new tabs created using [+] button]

![Screenshot_20231211_205507](https://github.com/brave/brave-browser/assets/38657976/67d64aea-46c0-4fbe-aa7f-3dd191578318)

</details>

**Comment by GeetaSarvadnya** [comment]
@kylehickinson: I am getting the metrics `Brave.Core.NewTabMethods` response value always `0` even when I open 3 or 6 tabs via tab switcher `+` option. Also the test plan step 2 and step 3 from https://github.com/brave/brave-core/pull/20159 says `Create a tab using the "new tab" menu item in the app menu` I don't see new tab option via app menu in iOS. I am not sure how it's implemented on the iOS. Could you review this and let me know your thoughts?

**Comment by kylehickinson** [comment]
@GeetaSarvadnya Sorry you can ignore that step, this will only trigger with the `+` button in the toolbar (while on a web page) and the `+` in the tabs bar on iPad. Is the value non-zero in `brave://histograms`? I'll double check either way today

**Comment by kylehickinson** [comment]
@GeetaSarvadnya seems to be working fine for me:
<img width="409" alt="image" src="https://github.com/brave/brave-browser/assets/529104/fddddf26-68e8-4197-b8e6-a91adda4baef">

I opened 3 tabs via the tab switcher then opened 6 tabs via the toolbar

**Comment by GeetaSarvadnya** [comment]
@kylehickinson: If I open 6 new tabs via tab switcher `+` option. I get response value as `0` on brave://local-state file and brave://histograms also shows the same response value `0`

When I open 6 new tabs via tab switcher `+` option and 6 new tabs via toolbar. I get response value as `2` on brave://local-state file and brave://histograms shows the same response value as `0.6`


Example | Example
----------|----------
![IMG_4619](https://github.com/brave/brave-browser/assets/38657976/169cf2ea-52a8-4b9c-bff8-3fe84efac475) | ![IMG_4620](https://github.com/brave/brave-browser/assets/38657976/9df32197-b889-4179-a9df-4c01963fa05f)

**Comment by kylehickinson** [comment]
@GeetaSarvadnya That makes sense. The p3a question is `how often do you use the [+] button compared to the tab switcher button?` and if you then open the same amount of tabs with the toolbar then `2` is correct as the value 2 represents `50% -75% of total new tabs created using [+] button`

**Comment by GeetaSarvadnya** [comment]
Thanks @kylehickinson!
