### ISSUE TITLE
[ads] Delay updates of video NTTs until an unmetered network (WiFi) is available

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#36598]
Seems Chrome implemented some functionality to disable (larger?) component updates on metered networks: https://github.com/chromium/chromium/commit/fb0255c8d251639c336a2f133fc65a3c6336f49b
We need to implement the same for Brave

**Comment by tmancey** [comment]
Closing issue because NTT video ads are an MVP on iOS in Japan only and if the feature is rolled out to more platforms and regions we will need write a new spec based on any limitation.
