### ISSUE TITLE
removing item while caching is in progress doesn't start to cache the next item.

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#36599]
## Steps to Reproduce

   1. Add multiple items to playlist - it'd be good to have big one, so that easily cancel while it's caching
   2. Remove an item while it's still caching
   3. See if next item starts to cache

## Actual result:

Nothing happen

## Expected result:
Next item should start caching

## Reproduces how often: 

Always

## Version/Channel Information:

Nightly

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave	1.67.2 Chromium: 124.0.6367.29 (Official Build) nightly (x86_64) 
Revision	bcc8ab0f30ea7af989211434c17eb432f9375792
OS	macOS Version 11.7.10 (Build 20G1427)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.66.103 Chromium: 124.0.6367.159 (Official Build) beta (64-bit)
-- | --
Revision | 74d46bb25d9ea5e6432e19f0cf38480cc372b0cf
OS | Windows 10 Version 22H2 (Build 19045.4355)
```

### Steps:
1. installed 
2. launched Brave
3. opened `brave://flags`
4. enabled playlist
5. restarted Brave
6. loaded `https://www.youtube.com/watch?v=E5SvVMqXDCI`
7. clicked on the `Add to Playlist` button
8. then clicked `Add selected`
9. did the same with `https://www.youtube.com/watch?v=YFmV_MRSD7M`
10. and `https://www.youtube.com/watch?v=SIm3nKfJnFE`
