### ISSUE TITLE
[iOS] - Leo Design Changes 1.63.x

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#36596]
## Description: 
- Address Leo design changes before release
https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=2533-14540&mode=design&t=oRLgegpwFgTXWUl4-0

## Brave Version: 
- 1.63.x, 1.64.x, 1.65.x

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.4
- iPad Air / iPadOS 16.7.2
Brave build: 1.63 (177)
BraveCore: 1.63.177 (122.0.6261.128)
```
---------------------------

**STEPS:**
1. Fresh install and launch Brave 
2. Open `Leo`
3. Go through all screens/scenarios > *Verify UI design*

**ACTUAL RESULTS:**
- Verified UI design changes in `Light` and `Dark` mode

<details>
<summary> iPhone </summary>

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/e413751f-311a-4c61-b8c7-28f01b529d32) | ![2](https://github.com/brave/brave-browser/assets/128532965/07d36f65-7a2f-483d-953c-5d522a7b0128) | ![3](https://github.com/brave/brave-browser/assets/128532965/4320fdea-6057-4180-b5d4-c269f21d9718) | ![4](https://github.com/brave/brave-browser/assets/128532965/094ebdb8-e2fe-4d9a-8f65-1861f31b1690) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/18c5a910-7f17-455e-b7a1-25f615c68604) | ![2](https://github.com/brave/brave-browser/assets/128532965/ff83183f-edd4-4a5f-a6f5-57829af28582) | ![3](https://github.com/brave/brave-browser/assets/128532965/086f4456-52e9-4aaf-8f97-64d60273855b) | ![4](https://github.com/brave/brave-browser/assets/128532965/c648abca-1197-4a8f-9d77-a9cd356e4456) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/7578f238-ab46-41f9-bccb-e324269b4199) | ![2](https://github.com/brave/brave-browser/assets/128532965/1ab67af6-b8b9-4c42-bc26-8aa39b4e4df2) | ![3](https://github.com/brave/brave-browser/assets/128532965/af93a12c-0a0e-493e-8b6d-5de7726e66a2) | ![4](https://github.com/brave/brave-browser/assets/128532965/82af13cd-d37c-4fa6-8c3f-ede672322c06) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/61fac017-cac9-47f3-abab-81dedba1f707) | ![2](https://github.com/brave/brave-browser/assets/128532965/ad4bcf81-5a4e-4d0b-b61d-673c14b9f5b7) | ![3](https://github.com/brave/brave-browser/assets/128532965/43982cb6-9385-4b24-aac3-954e4c4e74c4) | ![4](https://github.com/brave/brave-browser/assets/128532965/8385e50d-6fe5-4601-8559-93f813214f40) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/923ca4d8-4ec4-486d-82d6-f690ee3b6175) | ![2](https://github.com/brave/brave-browser/assets/128532965/cbf3df7d-6f87-4906-a32a-ef1b831c3372) | ![3](https://github.com/brave/brave-browser/assets/128532965/2cd77abf-4622-47fb-b776-53204343aa33) | ![4](https://github.com/brave/brave-browser/assets/128532965/c630d003-845d-4c57-8a60-e5e7785a854f) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/2558b1da-7f92-42d7-8f7b-a00e1e6f50c7) | ![2](https://github.com/brave/brave-browser/assets/128532965/8675f759-520d-448e-a124-1f5d61aa5634) | ![3](https://github.com/brave/brave-browser/assets/128532965/3f0c39a3-49cd-4ae9-963e-a577a47ac803) | ![4](https://github.com/brave/brave-browser/assets/128532965/420b589c-ba6f-449c-a667-431d2614186f) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/5185dac4-3bcd-407a-855a-4dfc6a989866) | ![2](https://github.com/brave/brave-browser/assets/128532965/1f041f9c-88f1-4369-b110-403e294c81ee) | ![3](https://github.com/brave/brave-browser/assets/128532965/bb9da30f-7085-42da-94c2-8a40f7539071) | ![4](https://github.com/brave/brave-browser/assets/128532965/5713f4bf-d876-4f49-8a6f-b6811d486826) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/1f36ac33-4291-47c6-bfc9-7b30fe4c4182) | ![2](https://github.com/brave/brave-browser/assets/128532965/15a04ef1-67e0-4e71-bfdb-95042e0e65f1) | ![3](https://github.com/brave/brave-browser/assets/128532965/00407c72-fe87-4a61-b620-75ad3af3393f) | ![4](https://github.com/brave/brave-browser/assets/128532965/a5d77f28-a505-493a-8fd7-15c10361559e) |
</details>

<details>
<summary> iPad </summary>



|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
| ![1]() | ![2]() | ![3]() | ![4]() |
| ![1]() | ![2]() | ![3]() | ![4]() |
| ![1]() | ![2]() | ![3]() | ![4]() |
| ![1]() | ![2]() | ![3]() | ![4]() |
| ![1]() | ![2]() | ![3]() | ![4]() |
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>
