### ISSUE TITLE
Tab bar interaction is broken after it becomes visible

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#36591]
### Steps to Reproduce 
  1. Prefix: Enable tabs bar visibility always, start with only 1 tab open
  2. Load a webpage in the current tab via the URL bar
  3. Click the `+` button in the toolbar to add a new tab
  4. Try to change tabs or close a tab via the tab bar that is now visible

### Actual result:
Taps passthrough to the page beneath or dont work

### Expected result:
Should interact with the tab bar

### Reproduces how often: 
Easily

### Brave Version:
1.61+

**Comment by kylehickinson** [comment]
No longer reproduces on 1.63, may also be fixed in 1.62 but not sure what change may have fixed it

**Comment by Uni-verse** [comment]
Verified on iPhone 12 running iOS 17.3.1 using version 1.64.109

encountered: https://github.com/brave/brave-browser/issues/36954, dupe of https://github.com/brave/brave-browser/issues/36587

- Ensured observed behavior in https://github.com/brave/brave-browser/issues/36591#issue-2172355295 is not reproducible using top bar and bottom bar modes.

Example | Example
-|-
![IMG_5880](https://github.com/brave/brave-browser/assets/17885425/548c90f1-0aee-4f35-af7f-ec4384483235) | ![IMG_5883](https://github.com/brave/brave-browser/assets/17885425/998f8eef-370e-46c8-b198-3a7f00b0baa1)
