### ISSUE TITLE
Change payment token redemption timing

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#3659]
## Description 
Right now, ad payout tokens are redeemed in 24 hour cycles.  We want to extend this to a week and add appropriate timing jitter to further improve privacy.

**Comment by yrliou** [comment]
Reopen the issue because this is being revert for fixing https://github.com/brave/brave-browser/issues/3883

**Comment by GeetaSarvadnya** [comment]
@terry should it be moved to milestone 0.64.x ?
The issue which I raised yesterday is fixed and moved to milestone 0.64.x

**Comment by tmancey** [comment]
This issue is in 0.63.x and can be tested. Only the debug flag for reducing the time was fixed in 0.64.x and 0.65.x

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Windows 10 OS Build 17134.523

- Verified the test plan mentioned in slack
