### ISSUE TITLE
follow up for #26165 - Ephemeral Storage/Chromium partitioning doesn't work as expected when all cookies are allowed

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#36590]
## Description 

Follow up to #26165

One case from the test page, `https://dev-pages.brave.software/storage/ephemeral-storage.html`, isn't working as expected when cookie changes are made via the shields panel instead of globally under brave://settings/shields.

## Steps to Reproduce

   1. Clean profile
   2. Navigate to `https://dev-pages.brave.software/storage/ephemeral-storage.html` and change cookie setting to "Allow all cookies" via shields panel
   3. Click on "Other site" link in header, change cookie setting to "Allow all cookies" via the shields panel
   4. Navigate back to `https://dev-pages.brave.software/storage/ephemeral-storage.html`
   5. Under "Ephemeral storage" drop down, be sure to have 1.64.31+ selected
   6. Under "Cookie blocking" drop down, be sure to have "All cookies allowed"
   7. Cases 1-5 work as expected
   8. Run case 6 (pay attention to the wait 30s part)

If you re-run the above with modifying the cookie setting from brave://settings/shields there is no issue, it works as expected.

## Actual result:

<img width="1397" alt="Screenshot 2024-03-06 at 2 56 53 PM" src="https://github.com/brave/brave-browser/assets/28145373/b6cc6e76-5cd7-46f0-be66-b77a25fc9c93">

## Expected result:

<img width="650" alt="Screenshot 2024-03-06 at 2 57 09 PM" src="https://github.com/brave/brave-browser/assets/28145373/5d3ffcf5-6f56-4fe9-9638-52df554aa6bb">

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.64.96 Chromium: 122.0.6261.111 (Official Build) beta (x86_64)
-- | --
Revision | fb9feca2d1f25ea20265752e8ecdf548a6925bd4
OS | macOS Version 13.6.4 (Build 22G513)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes 1.64.x
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @goodov @rebron

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave	1.65.83 Chromium: 123.0.6312.46 (Official Build) beta (x86_64) 
Revision	1ea667c8c59a4a4a327579974ec11149a738e750
OS	macOS Version 11.7.10 (Build 20G1427)
```

Block cross-site cookies

`Step 1`

Step 2

Step 3

Step 4

Step 5

Step 6



Allow all cookies
Block all cookies

**Comment by LaurenWags** [comment]
@goodov could you please add `release-notes/exclude` or `release-notes/include` label for this one? Thanks!

**Comment by stephendonner** [comment]
Wanted to note that I re-ran the verifications from https://github.com/brave/brave-browser/issues/36590#issuecomment-2004957298, using the 3 configurations for `Block cookies` from `brave://settings/shields`, and got the same results 👍

**Comment by MadhaviSeelam** [comment]
Verification `in progress` using
```
Brave | 1.65.90 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | f5ca64cd15d0d5c90f17b7d5213b6e2dd725d66a
OS | Windows 11 Version 23H2 (Build 22631.3296)
```



### Steps:
1. installed `1.65.90`
2. launched Brave
3. loaded `https://dev-pages.brave.software/storage/ephemeral-storage.html`
4. followed the instructions on the page (paying special attention to `Step 6` of `Allow all cookies`

### Confirmed `Step 6` and all other tests passed, for both `Allow all cookies` and `Block cross-site`, `Block cookies` options

Case 1: Enabled from Shields panel

## Allow all cookies - `PASSED`

<details>

`Step 1` | `Step 2` | `Step 3` | `Step 4` | `Step 5` | `Step 6`
---------|----------|----------|---------|----------|----------
![image](https://github.com/brave/brave-browser/assets/98358127/95dd96f5-836a-401b-8811-d5cb9ba7149e)
![image](https://github.com/brave/brave-browser/assets/98358127/4106f1ca-11a4-4f5a-8759-eb14e6f64f05)
![image](https://github.com/brave/brave-browser/assets/98358127/7df29695-bab1-4893-a236-2ff33ed2ec04)


</details>



## Block cross-site cookies - `PASSED`
<details>


`Step 1` | `Step 2` | `Step 3` | `Step 4` | `Step 5` | `Step 6`
---------|----------|----------|---------|----------|----------


</details>





## Block all cookies - `PASSED`
<details>

`Step 1` | `Step 2` | `Step 3` | `Step 4` | `Step 5` | `Step 6`
---------|----------|----------|---------|----------|----------




</details>

Case 2: Enabled from brave://settings/shields

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave	1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
Revision	5d9143e1a0812c53bdc27fd5384591254306a88c
OS	Linux
```


### Steps:
1. installed `1.65.90`
2. launched Brave
3. loaded `https://dev-pages.brave.software/storage/ephemeral-storage.html`
4. followed the instructions on the page (paying special attention to `Step 6` of `Allow all cookies`

### Confirmed `Step 6` and all other tests passed, for both `Allow all cookies` and `Block cross-site`, `Block cookies` options

#### Case 1: Enabled from Shields panel - `PASSED`

#### Allow all cookies - `PASSED`

<details>

Site 1 | Site 2 |`Step 1` | `Step 2` | `Step 3` | `Step 4` | `Step 5` | `Step 6`
----------|-----------------|----------|----------|---------|----------|--------|-----
![image](https://github.com/brave/brave-browser/assets/98358127/6f091b77-9c86-4990-90f0-a53a338af7c6)|![image](https://github.com/brave/brave-browser/assets/98358127/1f158513-6311-4ed9-be9a-6cc6aeca0239)|![image](https://github.com/brave/brave-browser/assets/98358127/4e46df84-1323-4938-b289-9d1281b1dae0)|![image](https://github.com/brave/brave-browser/assets/98358127/e70e4858-952a-4ac1-95e5-b008fa56634d)|![image](https://github.com/brave/brave-browser/assets/98358127/571c852d-ae53-4c32-b029-768b74bf6593)|![image](https://github.com/brave/brave-browser/assets/98358127/ed6f2678-cc38-45f4-9f8f-3c1bb2e75c2f)|![image](https://github.com/brave/brave-browser/assets/98358127/fb22eb8d-cbbc-4050-a75b-c4332d89b891)|![image](https://github.com/brave/brave-browser/assets/98358127/946e379b-1dce-4774-a911-9b4e28ef60e6)

</details>

#### Block cross-site cookies - `PASSED`
<details>

- Navigate to https://dev-pages.brave.software/storage/ephemeral-storage.html and change cookie setting to "Block cross-site cookies" via shields panel
- Click on "Other site" link in header, change cookie setting to "Block cross-site cookies" via the shields panel

site 1 | site 2 | `Step 1` | `Step 2` | `Step 3` | `Step 4` | `Step 5` | `Step 6`
---------|----------|----------|---------|----------|---------|------|--------
![image](https://github.com/brave/brave-browser/assets/98358127/3e731164-01ad-40e1-8ea3-02602687938c)|![image](https://github.com/brave/brave-browser/assets/98358127/69c777e1-f3b5-4b2c-9ab3-84bd58d6fe3c)|![image](https://github.com/brave/brave-browser/assets/98358127/1886760e-df9d-4972-9b54-5cb69adf2e03)|![image](https://github.com/brave/brave-browser/assets/98358127/f2aad59d-8d53-4e42-8574-ec56679b0567)|![image](https://github.com/brave/brave-browser/assets/98358127/e4c09a43-53d7-456f-9260-f25ddae52a56)|![image](https://github.com/brave/brave-browser/assets/98358127/f39898c8-553a-45e9-b646-9242e2580355)|![image](https://github.com/brave/brave-browser/assets/98358127/1f507652-6d56-458a-b987-0938c4d3d2ca)|![image](https://github.com/brave/brave-browser/assets/98358127/5f7b8e46-754b-4ba5-b701-8f0fe319ceb4)




</details>

#### Case 2: Enabled from `brave://settings/shields` - `PASSED`

#### Allow all cookies - PASSED
<details>

- Navigate to https://dev-pages.brave.software/storage/ephemeral-storage.html and change cookie setting to "Allow all cookies" via shields panel
- Click on "Other site" link in header, change cookie setting to "Allow all cookies" via the shields panel

site 1 | site 2 |`Step 1` | `Step 2` | `Step 3` | `Step 4` | `Step 5` | `Step 6`
---------|----------|----------|---------|----------|--------|------|------




</details>

#### Block all cookies - PASSED
<details>

- Navigate to https://dev-pages.brave.software/storage/ephemeral-storage.html and change cookie setting to "Block all cookies" via shields panel
- Click on "Other site" link in header, change cookie setting to "Block all cookies" via the shields panel

Global defaults | site 1 | site 2  |`Step 1` | `Step 2` | `Step 3` | `Step 4` | `Step 5` | `Step 6`
---------|----------|----------|---------|----------|--------|------|------|------





#### Block cross-site cookies - `PASSED`
<details>

  - Navigate to https://dev-pages.brave.software/storage/ephemeral-storage.html and change cookie setting to " Block cross-site cookies" via shields panel
  - Click on "Other site" link in header, change cookie setting to " Block cross-site cookies" via the shields panel

Global defaults | site 1 | site 2  |`Step 1` | `Step 2` | `Step 3` | `Step 4` | `Step 5` | `Step 6`
---------|----------|----------|---------|----------|--------|------|------|------
