### ISSUE TITLE
Change Background Sync to Brave Sync

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#366]
## Description 
Background Sync should be removed from Content settings page

## Steps to Reproduce

   1. Settings -> Content Settings -> Background Sync which requires account login

 ## Actual result:

![image](https://user-images.githubusercontent.com/17010094/41488203-7d6d5984-70b9-11e8-8f74-734478eb12b6.png)

cc: @bridiver @diracdeltas

**Comment by bbondy** [comment]
I think we'll just remove this option completely? Thoughts @AlexeyBarabash ?

**Comment by AlexeyBarabash** [comment]
@bbondy @srirambv 
I thought this option is for the synchronization of bookmarks/history/setting between devices, which will be replaced with Brave Sync https://github.com/brave/brave-browser/issues/29 . Then I would vote to remove it.
But if we go there chrome://settings/content/backgroundSync , we will see

![image](https://user-images.githubusercontent.com/24739341/44254377-53426400-a20b-11e8-981e-c0554a937ea5.png)


which is other thing.
So, I think to keep it, and maybe to  rename it  to `Background sync of recently closed sites data` .

I was not aware of this option, but it seems useful. If a page has `logout` button, which works through async JavaScript  without re-load of the page, then when user presses logout and immediately closes the tab potentially he would not be logged out in fact. But this option `Allow recently closed sites to finish sending and receiving data (recommended)` should allow to complete the operation.

The Chrome native sync for bookmarks/history/etc is not currently shown in Brave-core. Two things are required to see that at least:
1. to re-build with Google API keys with enabled Google Accounts sync; 
2. to login in browser with Google Account.

About this issue: either to keep it as and close, or rename the item. I would just close.

**Comment by GeetaSarvadnya** [comment]
Verification Passed on:

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows
