### ISSUE TITLE
[Commands]: Add more advanced tab grouping/management commands

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#36600]
This issue partially resolves https://github.com/brave/brave-browser/issues/35999

Adding new commands means users can add their own keyboard shortcuts, and run that functionality through the commander without using the mouse.

## New Commands:

- [x] Group ungrouped tabs
- [x] Ungroup current group
- [x] Remove tab from group
- [x] Ungroup all tabs
- [x] Name current group
- [x] New tab in group
- [x] Toggle group expanded
- [x] Close ungrouped tabs
- [x] Close group
- [x] Bring tabs from other windows

## Test Plan

For each of the above commands:
1. It should be possible to add a keyboard shortcut (via chrome://settings/system/shortcuts)
2. It should be possible to run the command form the command palette

**Comment by BloatedMonke** [comment]
Hi, I have another idea to add if you're still working on this.
It would be nice to be able to add all tabs under the current tab to one group. Essentially the dumber version of _Group tabs on current origin_.
Also, the newly added features are great and much appreciated!

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.65.86 Chromium: 123.0.6312.46 (Official Build) beta (64-bit)
-- | --
Revision | cfce8711dc58101a4cc216163b8beb3451d03bdf
OS | Windows 11 Version 23H2 (Build 22631.3296)
```

Shared steps:

1. Installed `1.65.86 `
2. launched Brave
3. opened `brave://settings/system/shortcuts`
4. added a keyboard shortcut for each of the new command listed https://github.com/brave/brave-browser/issues/36600#issue-2172772621
5. ran the same command from the command palette (Ctrl + Spacebar)


 `Group ungrouped tabs`
 <details>

brave://settings/shortcuts|step 4a | step 4b
----------- | ---------- | -----------
<image width="300" alt = "image" src ="https://github.com/brave/brave-browser/assets/98358127/bd147cb2-46e3-4812-98e1-228cafb91c3c">|<image width="5800" alt = "image" src ="https://github.com/brave/brave-browser/assets/98358127/93110f4d-456a-43eb-bac3-b869a8d4bdd0">|<image width="5800" alt = "image" src ="https://github.com/brave/brave-browser/assets/98358127/abe7481a-f84f-4c86-8726-db1f88ae5b02">

`command palette`
example | example | example | example 
---------- | ------- | ------ | -------
![image](https://github.com/brave/brave-browser/assets/98358127/2946fc93-add4-41b2-a364-5c2d3d8447f3)|![image](https://github.com/brave/brave-browser/assets/98358127/65373e61-ffa7-4bdf-af5d-91b296fe89c4)|![image](https://github.com/brave/brave-browser/assets/98358127/b428ef61-a22e-4364-87a2-11d1e00f5797)|![image](https://github.com/brave/brave-browser/assets/98358127/1cadecba-7dc3-49ef-9e20-9c3476660450)
</details>

`Ungroup current group`
<details>

example | example 
----- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/bb1d19af-d00c-4965-9575-1ea0c979574b)}![image](https://github.com/brave/brave-browser/assets/98358127/e929c117-aa0d-4860-a558-37842c5b9b35)

</details>
`Remove tab from group`

![image](https://github.com/brave/brave-browser/assets/98358127/8f0e2d32-77ff-49d1-a165-11baced1ad52)

**Comment by MadhaviSeelam** [comment]
Adding `QA/Test-All-Platforms` as some of the quick commands show incorrect command (`Alt` is missing and in some cases a duplicate one) in Win 11.

**Comment by fallaciousreasoning** [comment]
oooh that's a bit scary - I'll take a look

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.65.94 Chromium: 123.0.6312.58 (Official Build) beta (x86_64) 
Revision	7e46607e21340cacbbf1e53b7c3d1f5926bed731
OS	macOS Version 13.6.4 (Build 22G513)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
Revision	5d9143e1a0812c53bdc27fd5384591254306a88c
OS	Linux
```
