### ISSUE TITLE
Tweak Wallet creation screen

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#36606]
![image](https://github.com/brave/brave-browser/assets/3308503/adc6c8f7-cfc1-495b-be97-77184ff10390)

Figma design: https://www.figma.com/file/oXIiv45pIhF2RGlpEjOfUg/Wallet-onboarding?node-id=6223%3A70942&mode=dev

Main umbrella issue: https://github.com/brave/brave-browser/issues/35294

## Description

Tweak Wallet creation screen following new Figma design.

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.66.101 x64 build
- Verified steps from [brave/brave-core#22498](https://github.com/brave/brave-core/pull/22498)
- Verified `Creating Wallet` screen is shown before `Recovery seed words` screen is shown during onboarding

**Comment by kjozwiak** [comment]
We'll use https://github.com/brave/brave-browser/issues/36578 as the `release-notes/include` for the above.
