### ISSUE TITLE
Enable zcash feature flag on all channels

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#36613]
Currently it's enabled by default only for nightly and development channels, we would like to change it to be all channels and let this change ride the trains.

**Comment by kjozwiak** [comment]
The above requires `1.64.103` or higher for `1.64.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.104 Chromium: 123.0.6312.46 (Official Build) (64-bit)
-- | --
Revision | 0ca3d372cf8aab96fafdd75f5c5c8d2012bc0cc6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified ZCash is enabled by default
- Verified ZCash is shown in network selection screen
- Verified Create Account shows ZCash as an option

https://github.com/brave/brave-browser/assets/17010094/69c2029f-5c4b-411d-8201-b05f11055772
