### ISSUE TITLE
Merge in diffs to Brave Ads catalog

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#3661]
## Description 

Instead of full periodic catalog replacement, the ad catalog request should first try to pull a diff from the ad server and apply to local catalog in order to save bandwidth.

**Comment by jsecretan** [comment]
Discussing with @bridiver, we should probably do an etag check first before getting the diff.

**Comment by tmancey** [comment]
Closing as will be resolved by https://github.com/brave/brave-browser/issues/14808 and https://github.com/brave/brave-browser/issues/15466
