### ISSUE TITLE
Add support for transaction speed up/cancel/retry

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#36627]
Transactions that aren't completed can be sped up or cancelled via the `EthTxController`, we should add these to tx summary long press & tx details UI. These are only supported for Ethereum transactions currently.

```
  // Used to speed-up or cancel a transaction
  SpeedupOrCancelTransaction(CoinType coin_type,
                             string chain_id, string tx_meta_id, bool cancel)
    => (bool success, string tx_meta_id, string error_message);

  // Used to retry a transaction
  RetryTransaction(CoinType coin_type, string chain_id, string tx_meta_id)
    => (bool success, string tx_meta_id, string error_message);
```
https://github.com/brave/brave-core/blob/0d5454a8a254102dab465f4efef72b5d963e36df/components/brave_wallet/common/brave_wallet.mojom#L1733-L1740

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.5 running 1.66 (105)
- Verified steps from [brave/brave-core#22956](https://github.com/brave/brave-core/pull/22956)
- Verified Cancel/Speedup transaction options are shown when a transaction is submitted
- Verified long press on submitted transaction shows Cancel and Speedup options
- Verified Retry transaction is shown when a transaction errors out
- Verified long press on error transaction in activity shows Retry transaction

![image](https://github.com/brave/brave-browser/assets/17010094/188be943-c15c-464a-b7ef-eb389040ebc5) | ![image](https://github.com/brave/brave-browser/assets/17010094/8971d003-1b0c-4184-b47c-3185d70682fd)
-- | --
![image](https://github.com/brave/brave-browser/assets/17010094/7fabd3bc-644f-493e-adbb-aecc3915b579) | ![image](https://github.com/brave/brave-browser/assets/17010094/cc9e8b75-80f9-4aba-8f3f-98b46f6ec356)
