### ISSUE TITLE
On iOS swaps, 'swap from' asset amount changes everytime a new asset is picked on 'swap to'

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#36623]
## Description 
On iOS, when a user inserts the amount they want to swap, that figure shouldn't change.

But on mobile right now, the 'swap to' amount doesnt change from one swap to the next irrespective of whether you change asset. 

## Steps to reproduce 

   1. go to swaps on mobile
   2. enter in the amount of eth you would like to swap
   3. note the BAT amount you are getting for your eth
   4. Now see change BAT to USDC and you will see the amount on 'swap to' section never changes 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by StephenHeaps** [comment]
Closing as stale; swap values are cleared when selected token changes.
