### ISSUE TITLE
Tokens that fail to redeem due to network errors should be added to a queue and retried

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#3662]
## Test plan
See https://github.com/brave/brave-core/pull/2035

## Description 
Tokens that fail to redeem due to network errors should be added to a queue and retried. The creative_instance_id (uuid) should be added back to the queue until successful.

**Comment by bsclifton** [comment]
@tmancey just added missing labels / test plan; please update if it should be different 😄

**Comment by yrliou** [comment]
Reopen the issue because this is being revert for fixing https://github.com/brave/brave-browser/issues/3883

**Comment by jumde** [comment]
Re-opened with C74 revert

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.63.45 Chromium: 74.0.3729.75 (Official Build) beta (64-bit)
--|--
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Linux

* Failed transaction in `confirmations.json`
![image](https://user-images.githubusercontent.com/17010094/56369641-c0a5fa80-61c7-11e9-9379-0eaa18ce7a68.png)
* Failed transaction redeemed in `confirmations.json`
![image](https://user-images.githubusercontent.com/17010094/56369592-acfa9400-61c7-11e9-8fb1-3249da58fe76.png)
