### ISSUE TITLE
Add support for VLOG to help reduce noise in logs for INFO

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#3663]
## Description 
We should create a separate VLOG macro (with Chromium matching log levels) for ads that proxies back to the client. See LOG macro for implementation.

Example implementation for ledger: https://github.com/brave/brave-core/pull/1479

**Comment by tmancey** [comment]
Closing issue as a duplicate of https://github.com/brave/brave-browser/issues/7242
