### ISSUE TITLE
Update browser's toggles to use Material You styles from Chromium

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#36648]
## Description 

Chrome is using the new material design toggles in the browser settings and panels. Could we bring those into Brave?

## Steps to Reproduce

   1. Open Chrome canary.
   2. Go to settings
   3. Open Brave and go to settings to compare

### Chrome 
![image](https://github.com/brave/brave-browser/assets/15734630/78c708aa-2258-4d15-a207-1a524da91a67)

### Brave
![image](https://github.com/brave/brave-browser/assets/15734630/ca65710e-736d-4822-99d1-07dd36ec0aa4)

## Expected result:
Material toggles using Nala colors
<img width="842" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/2c7ac3e7-b20f-4f3b-8f94-467ea73a4cc4">

https://www.figma.com/file/IXNCYwXmMWaF6u7Pdv1pOW/Desktop-settings---Nala?type=design&node-id=214-26840&mode=design

**Comment by rebron** [comment]
Closing. This is fixed in 1.66.x
