### ISSUE TITLE
Full page google doc summarization support

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#36649]
Current screenshot method can only extract text from pages in the viewport, it would be 1 or 2 pages depends on how big the screen is or zoom ratio.
We will use print preview extraction method to get full pages of context and then extract text from it.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.67.52 Chromium: 124.0.6367.91 (Official Build) nightly (x86_64)
-- | --
Revision | a368a1ab342f0a5d4dee4db3f2699f7d02579247
OS | macOS Version 11.7.10 (Build 20G1427)
```


## Case 1: Regression test on previous google doc support
Open a google doc with only 1 page of content and summarize it
Summary should be relevant

## Case 2: Test on full page google doc support
Open a google doc with only multiple pages of content and summarize it
Summary should be relevant

## Case 3: Test on page limit (20)
Open a google doc with 19 pages of blank pages and 2 pages with completely different scoped of contents
Summarize the page
Summary should be only relevant to 20th page but not 21st page

## Case 4: Compatibility with print dialog
Open a google doc and print it
When print dialog is open, open Leo panel and summarize the page
Summary should show up
Close print dialog and trigger print again
Print dialog should still show up with print preview available

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.66.103 Chromium: 124.0.6367.159 (Official Build) beta (64-bit)
-- | --
Revision | 74d46bb25d9ea5e6432e19f0cf38480cc372b0cf
OS | Windows 10 Version 22H2 (Build 19045.4355)
```

## Shared Steps:
1. installed `1.66.103`
2. launched Brave
3. clicked on `Leo` in the sidebar
4. entered `test`
5. clicked on `I understand`


## Case 1: Regression test on previous Google Doc support - `PENDING`
<details>

- downloaded a newspaper template from `https://thegoodocs.com/download`
- copied it 
- clicked on `Summarize this page` 

### Confirmed page summarization was accurate



</details>

## Case 2: Test full-page Google Doc support - `PENDING`
<details>

- opened my Senior thesis (14 pages)
- clicked on `Summarize this page`

### Confirmed accurate summary





</details>

## Case 3: Test Google Docs page limit (20) - `PENDING`
<details>

- open a google doc with 19 pages of blank pages and 2 pages with completely different scoped of contents
- summarize the page

Summary should be only relevant to 20th page but not 21st page



</details>

## Case 4: Compatibility with print dialog - `PENDING`
<details>

- open a Google Doc and print it
- when print dialog is open, open Leo panel and summarize the page
- summary should show up
- close print dialog and trigger print again

### Confirmed correct `Leo` summarization and print-dialog functionality

example | example | example | example
---------|----------|---------|---------


</details>
