### ISSUE TITLE
Leo button prompts stop appearing after pressing the "suggest questions..." button prompt

### ISSUE THREAD

**Issue by WhatsACloud** [brave/brave-browser#36642]
## Description 
In an isolated tab, Leo button prompts stop appearing after pressing the "suggest questions..." button prompt and pressing all of the button prompts that appear afterwards. This issue occurs even after one creates a new chat.

Issue resolves itself after refreshing the tab however.

## Steps to Reproduce
   1. Open the Leo chat in the sidebar
   2. Press "suggest questions..." button prompt located inside the chat box
   3. Press the remaining button prompts in the chat box
   4. (optional) create a new chat

## Actual result:
No button prompts show up in the Leo chat box.

## Expected result:
The button prompts "summarise this page" and "suggest questions..." show up in the Leo chat box.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave: 1.63.169 Chromium: 122.0.6261.111 (Official Build) (64-bit)
Revision: 0e0a975cf46d4d026e184ca61788e1da6f0d76bc
OS: Windows 10 Version 22H2 (Build 19045.4046)

## Version/Channel Information:

- Can you reproduce this issue with the current release? - Yes
- Can you reproduce this issue with the beta channel? - Yes
- Can you reproduce this issue with the nightly channel? - Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? - No
- Does the issue resolve itself when disabling Brave Rewards? - No
- Is the issue reproducible on the latest version of Chrome? - Yes

## Miscellaneous Information:
@mattmcalister @LorenzoMinto 
cc: @stephendonner @rebron

**Comment by mattmcalister** [comment]
closing as expected behavior
