### ISSUE TITLE
[Wallet] Recompute swap "to" and "from" networks on URL change

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#36643]
## Description 

The "from" and "to" networks were not updating when the URL search params changed in the swap UI

## Steps to Reproduce

   1. Go to the swap page in the wallet
   2. select a "from" asset
   3. then select a different "from" asset on a different network

## Actual result:

Correct network and/or asset is not shown as selected

## Expected result:
Correct network and/or asset is shown as selected

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | 2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from issue description
- Verified changing tokens updates the networks 
- Verified Swap to only shows the selected network

https://github.com/brave/brave-browser/assets/17010094/e1c74694-c9b6-4649-ba1c-410f01bcdaa6
