### ISSUE TITLE
[ads] Improve locale language/region detection

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#36644]

**Comment by hffvld** [comment]
Verified on `iPhone 14`using version(s):
```
Device/OS: iPhone 14 / iOS 17.5
Brave build: 1.65 (103)
BraveCore: 1.65.103 (123.0.6312.105)
```
---------------------------

**STEPS:**
1. Go to device `Settings` > General > Language & Region
2. Region > Set any random region
3. Go to `Brave` > Settings > View Chromium Local State
4. Find `country_code` > *Verify, country code matches the one in device settings*

**ACTUAL RESULTS:**
- Verified that `country_code` in `Chromium Local State` matches the country whish is set in device settings > Region

---------------------------

|USA|Russia|Spain|Germany|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/68a345f3-7a7a-4c96-a066-55c68abb24d5) | ![2](https://github.com/brave/brave-browser/assets/128532965/27e3f0e6-acbf-42f9-a319-e8b7ee3d8331) | ![3](https://github.com/brave/brave-browser/assets/128532965/f187a4c2-dfa8-4aef-9e8c-818a00465029) | ![4](https://github.com/brave/brave-browser/assets/128532965/7fa6933d-988d-4ca0-b33b-2bfd1108f060) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/3cb7fa75-97b8-4765-8f84-ad8db8e20877) | ![2](https://github.com/brave/brave-browser/assets/128532965/2f5fede9-8174-4bc0-9dba-5306f6e845e5) | ![3](https://github.com/brave/brave-browser/assets/128532965/131e671e-18e9-47f1-8d2b-3352de2995fc) | ![4](https://github.com/brave/brave-browser/assets/128532965/2f105dda-2fd6-47cd-9bfa-868108eee2d3) |
|Canada|Poland|Japan|Brazil|
| ![1](https://github.com/brave/brave-browser/assets/128532965/d8bfe6e6-fbdb-4b8b-9a63-f8f173bb07a0) | ![2](https://github.com/brave/brave-browser/assets/128532965/ff8be4fe-dd32-49d6-9e74-3c4d3281cbbe) | ![3](https://github.com/brave/brave-browser/assets/128532965/3bc6f41a-16ac-4187-91f3-515a3e7bba93) | ![4](https://github.com/brave/brave-browser/assets/128532965/380a1232-7021-4530-8dd5-1063a28d982e) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/e536c3fa-faba-45e3-8865-46a450a18e2f) | ![2](https://github.com/brave/brave-browser/assets/128532965/2a632ba1-b9e2-425f-b8c1-b57bd80fc613) | ![3](https://github.com/brave/brave-browser/assets/128532965/50ed63ba-473a-49e1-a11e-e679b3cec4d9) | ![4](https://github.com/brave/brave-browser/assets/128532965/93e3608a-95f8-48ba-85bc-42867ba03336) |
