### ISSUE TITLE
Password manager: no prompt to save password on insecure websites with self-signed certificate

### ISSUE THREAD

**Issue by fear-the-beaver** [brave/brave-browser#3664]
## Description 

Password manager doesn't prompt to save login/password on insecure websites. This is inconvenient because in my work network I have a lot of servers that utilize self-signed certificates.

## Steps to Reproduce

   1. Access login form on the website that is marked as "insecure" due to self-signed certificate.
   2. Enter credentials and login.

## Actual result:

   1. No prompt to save password from Brave password manager.

## Expected result:

   1. Prompt to save password from Brave password manager.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 0.60.48 Chromium: 72.0.3626.121 (Official Build) (64-bit)
-- | --
Revision | da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

Not tested

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 

No

- Is the issue reproducible on the latest version of Chrome? 

Not tested

### Additional Information

- The issue happens even with "Safe browsing" option disabled.

**Comment by rebron** [comment]
Closing. Works as expected.

**Comment by iyx** [comment]
I agree, quite inconvenient. At least there should be specific setting to enable this.

**Comment by kayzzen01** [comment]
> I agree, quite inconvenient. At least there should be specific setting to enable this.

I would like this feature. I agree, having options is always better.
I use it to save passwords for some network devices that don't have https.

**Comment by airlie** [comment]
The browser is happy to save passwords for websites that have no encryption, but refuses to do so on sites that have SOME encryption?

Why treat some security worse than no security?

Additionally, if the user has to type in their password, they are more likely to chose a password that is easy to type and remember over one that is secure. Blocking the password manager on self signed certs is encouraging password reuse.

**Comment by pradvk** [comment]
it is important to save complex passwords even if cert is invalid or for self signed certs.
please re-open issue

**Comment by samal-rasmussen** [comment]
I am trying to develop a pwa. They require certificates. I use a self signed certificate when developing. I now need to enter the test password manually every frikkin time I reset the dev db.I am often working on something that requires me to reset the dev db to see if it is working. It's exhausting to enter the password after each try. Just frikkin let me autocomplete. It's my problem whether it's a good idea or not - not yours. Get out of my way dammit.

**Comment by tfbroner** [comment]
I switched away to Firefox, and so did the rest of devs in my company, less hassle.

**Comment by hugolin69** [comment]
This is the worst behaviour ever...
I switched to Brave, but I hesitating to go back to Firefox.
Why not adding an option, disabled by default if needed to allow us to let us save passwords on self signed page.

juste creasy this behaviour.

**Comment by sistemi-nv** [comment]
Same thoughts here. Back to Firefox? Probably yes.
Also I can't understand why not to autocomplete password for insecure sites. If the user type it manually, what does change then?
Password autocompletion is insecure if your PC is in wrong hands, even if the site is secure.
Really can't understand ...
Can please someone explain what am I missing?
Thanks.

**Comment by hugolin69** [comment]
I am coming back to Firefox for that reason.
Why ? why the dev do not give an option to allow this.

This is just creasy.

**Comment by derde** [comment]
If Brave can add a security exception for a self-signed cert, then it should allow the storage of passwords for the exceptionally secured site.  Just refusing to work with these sites is not how systems work in industry.

**Comment by sysvar** [comment]
This is really inconvenient for developers, please add a setting for an override with self signed certs.

**Comment by eehmke** [comment]
This is bothering a lot of users some years now. I am also considering giving up and return to Firefox.

**Comment by tfbroner** [comment]
> This is bothering a lot of users some years now. I am also considering giving up and return to Firefox.

I already switched back some time ago, and I don't regret it.
