### ISSUE TITLE
Issues with settings menu for Leo

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#36650]
## Description: 
There are some known cases where hamburger menu does not function normally. Resolving Case 1 should resolve the rest as this is related to the keyboard. 

## Steps to Reproduce 

**Case 1:** 

1. Enable Leo
2. Bring up the keyboard
3. Tap on the `info` icon
Result: notice popover is in the wrong spot

**Case 2:** 

1. Enable Leo
2. Change LLM from menu
3. Submit query
Result: menu opens
  
**Case 3:** 

1. Enable Leo
2. Open menu -> Advanced Settings
3. Close Adbanced Settings
5. Tap on cog to open menu
Result: menu does not respond

## Actual result: 
See above

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

## Brave Version: 
1.63 (171)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? No
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 
iPhone 12, iOS 17.3.1

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari?

**Comment by kjozwiak** [comment]
The above requires `1.63.173` or higher for `1.63.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: iPhone 14 / iOS 17.4
Brave build: 1.63 (173)
BraveCore: 1.63.173 (122.0.6261.111)
```
---------------------------
<details>
<summary> Tooltip pop-up </summary>

**STEPS:**
1. Launch Brave
2. Open `Leo`
3. Bring up the keyboard
4. Tap on the `Info` icon > *Verify*

**ACTUAL RESULTS:**
- Verified that the `Info` pop-up message is shown in a proper location when the keyboard was previously opened

---------------------------

https://github.com/brave/brave-browser/assets/128532965/1b368b76-d967-4477-b9eb-37e35867ea7b
</details>

<details>
<summary> Leo's main menu self opening </summary>

**STEPS:**
1. Launch Brave
2. Open `Leo`
3. Tap `Main menu` > Change the language model
4. Submit query > *Verify*

**ACTUAL RESULTS:**
- Verified that Leo's `Main menu` is not opened by itself

---------------------------

https://github.com/brave/brave-browser/assets/128532965/b2b10692-6ea1-4479-b256-898a66428df8
</details>

<details>
<summary> Leo's main menu responsiveness </summary>

**STEPS:**
1. Launch Brave 
2. Open `Leo`
3. Tap `Main menu` > Advanced Settings
4. Close `Advanced Settings`
5. Tap ⚙️ icon to open `Main menu` > *Verify*

**ACTUAL RESULTS:**
- Verified that the `Main menu` can be reopened again at any time

---------------------------

https://github.com/brave/brave-browser/assets/128532965/ef36b631-1bdb-42a5-853a-5b33ae57fc2f
</details>
