### ISSUE TITLE
Allow Editing Token Details

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#36657]
## Description 

We need to allow editing `Token` details just like we allow with `NFT's`

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | 2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from [brave/brave-core#22555](https://github.com/brave/brave-core/pull/22555)
- Verified native tokens can't be edited
- Verified token details can be edited via more menu

https://github.com/brave/brave-browser/assets/17010094/337d3520-f67e-4cb9-b3ff-c9aa2fdad896
