### ISSUE TITLE
Menu cut off when opened on iPad

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#36656]
## Description: 
Menu appears to be cut off when opened, perhaps the chat window should be wider in landscape.

## Steps to Reproduce 
  1. Enable Leo
  2. Open Leo settings menu (cog)
  3. Observe UI

## Actual result: 
Example | Example
-|-
![IMG_1308](https://github.com/brave/brave-browser/assets/17885425/65845366-1e2b-412c-b4cf-5573b4f471de) | ![IMG_1309](https://github.com/brave/brave-browser/assets/17885425/7cb4defa-5b25-40ee-b10b-c684e9a3ecc3)

## Expected result:
Adjust the menu position or make chat window wider

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

## Brave Version: 
1.63 (171)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? No (new feature)
- Can you reproduce this issue with the current build from AppStore? No (new feature)

### Device details: 
iPad (7th Gen) | iPadOS 17.0

**Comment by kjozwiak** [comment]
The above requires `1.63.173` or higher for `1.63.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.4
Brave build: 1.63 (173)
BraveCore: 1.63.173 (122.0.6261.111)
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-browser/issues/36656#issue-2176806747
2. *Verify*

**ACTUAL RESULTS:**
- Verified that Leo's `Main menu` is not cut off and shown correctly
- Verified the same in `Landscape` and `Portrait` modes

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/5e70bd91-5513-49f6-977b-206fe50f540a) | ![2](https://github.com/brave/brave-browser/assets/128532965/1612fc26-08b1-4ad0-b378-9a50db5d1675) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/d09da1ed-48ae-4f77-97d0-9e9259307d07) | ![2](https://github.com/brave/brave-browser/assets/128532965/2907fd09-2b68-4c64-8c8a-2ccbc4f5dfa4) |
