### ISSUE TITLE
Error being returned when sending feedback for Leo responses (rating)

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#36652]
## Description: 
When sending feedback for Leo responses, it returns general error banner

URL: `https://feedback.brave.com/1/ai/feedback/rating`
```
Request:
{
	"channel": "unknown",
	"chat": [{
		"content": "Test",
		"id": 0,
		"type": "human"
	}, {
		"content": "Hello! I'm here to help. Could you please provide more details about what you'd like to test or learn about? This will enable me to give you a more accurate and useful response. Looking forward to assisting you!",
		"id": 1,
		"type": "assistant"
	}],
	"is_premium": false,
	"locale": "en_US",
	"model": "mixtral-8x7b-instruct",
	"platform": "ios",
	"rating": 1,
	"ymd": "2024-03-08"
}
```
```
Response:
{
	"Renderer": null,
	"statusCode": 400,
	"error": "Bad Request",
	"message": "invalid platform"
}
```

## Steps to Reproduce 
  1. Enable Leo
  2. Submit query
  3. Long-press on response, select `Like` or `Dislike`

## Actual result: 
![IMG_5798](https://github.com/brave/brave-browser/assets/17885425/93cffb49-0a95-4be8-a69a-ef108112578c)

## Expected result:
Should not show error

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? No (new feature)
- Can you reproduce this issue with the current build from AppStore? No (new feature)

### Device details: 
iPhone 12

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari?

**Comment by porteron** [comment]
The issue was the serverside endpoint only accepted Brave Core platforms. This has been resolved as of this morning: https://github.com/brave-intl/go-vault/pull/222.

**Comment by kjozwiak** [comment]
Thanks @porteron 👍 Moving into `1.63.x` so this can get re-checked by QA. CCing @hffvld @Uni-verse.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.3.1` using version `1.62 (173)`

- Ensured Like/Disliking post will successfully show confirmation banner.
- Ensured tapping on `X` in the Liked banner will dismiss the confirmation banner.
- Ensured banners will automatically dismiss after 4-5 seconds.

Liked | Dislike
-|-
![IMG_5838](https://github.com/brave/brave-browser/assets/17885425/79e7deea-91ae-4a1f-8c75-cce5fcd0ed83) | ![IMG_5842](https://github.com/brave/brave-browser/assets/17885425/663df556-65a1-4408-97b8-ea1921ad1b66)
