### ISSUE TITLE
Use production url on release channel for Manage Subscriptions (active credentials)

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#36653]
## Description: 
Currently we are sending users to `account.bravesoftware.com` when tapping on Manage Subscriptions in the Leo settings menu for users that have active credentials loaded. Although this only happens in TF builds and should not be the case for store published builds, we would like to test using production site on release channel only.

## Steps to Reproduce 
  1. Enable Leo
  2. Load active credentials from account.brave.com
  3. Open menu, select `Manage Subscription`
  4. Observe URL

## Actual result: 
`account.bravesoftware.com`

## Expected result:
`account.brave.com`

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

## Brave Version: 
1.63 (171)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? No
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 
iPhone 12, iOS 17

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.4
Brave build: 1.63 (173)
BraveCore: 1.63.173 (122.0.6261.111)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/36653#issue-2176658149
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `account.brave.com` is used when tapping `Manage Subscriptions` in the Leo menu

---------------------------

https://github.com/brave/brave-browser/assets/128532965/5a872017-a836-443f-a877-85b1211ed213
