### ISSUE TITLE
[Leo] `Regenerate` function is working only towards the last query

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#36659]
## Description: 

The `Regenerate` function is working only towards the last query.

## Steps to Reproduce 
  1. Launch Brave
  2. Open `Leo`
  3. Ask a few questions and receive the answers
  4. Tap and hold on any response that is not the last one in a raw
  5. Regenerate > *Observe it's regenerating the response for the last query instead*

## Actual result: 

The `Regenerate` function is working only towards the last query.

https://github.com/brave/brave-browser/assets/128532965/7ed2d8c5-edbd-41a6-842e-e436e0a2d560

## Expected result:

The `Regenerate` function must create a new response for the specific query.

## Reproduces how often: [Easily reproduced, Intermittent Issue]

`Easily reproduced`

## Brave Version: 

```
Brave build: 1.63 (171)
BraveCore: 1.63.171 (122.0.6261.111)
```

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? N/A
- Can you reproduce this issue with the current build from AppStore? N/A

### Device details: 

```
iPhone 14 / iOS 17.4
```

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari?

**Comment by kjozwiak** [comment]
The above requires `1.63.173` or higher for `1.63.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.4
Brave build: 1.63 (173)
BraveCore: 1.63.173 (122.0.6261.111)
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-browser/issues/36659#issue-2176969502
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Regenerate` function works towards any query.

---------------------------

https://github.com/brave/brave-browser/assets/128532965/fd915d13-d060-4190-97f9-94de8b4ad629
