### ISSUE TITLE
[C123] NTP Brave rewards widget is stuck on `Start using rewards` even after joining rewards

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#36651]
After joining rewards the widget should automatically update.
This is a regression in C123, Not reproducible on C122.

## Steps to Reproduce

Case 1:
1. Clean profile
2. Join Rewards through Rewards icon in the URL bar
3. Open NTP

Case 2:
1. Clean profile
2. Join Rewards through Rewards icon in the URL bar
3. Open NTP
4. Restart Brave
5. Open NTP

Note: it is stuck even after browser restart

## Actual result:

NTP Brave rewards widget is stuck on `Start using rewards

![image](https://github.com/brave/brave-browser/assets/34715963/cee34567-4c6e-4cdf-a44c-4966e26f7ffc)

## Expected result:
NTP Brave rewards widget is updated

![image](https://github.com/brave/brave-browser/assets/34715963/89561fd7-623b-41e6-80df-dbf26522a3d8)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Reproducible on 

Brave | 1.65.62 Chromium: 123.0.6312.29 (Official Build) nightly (64-bit)
-- | --
Revision | 7760e1c54748b192dd410678c602423529d7a56f
OS | Linux

Works on

Brave | 1.65.63 Chromium: 122.0.6261.111 (Official Build) nightly (64-bit)
-- | --
Revision | fa36a45339ae09bf39bafd628a09cea8809056f5
OS | Linux

cc @emerick @Miyayes @LaurenWags

**Comment by stephendonner** [comment]
Quick and easy check, high-value across platforms - setting `QA/Test-All-Platforms` 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (x86_64) 
Revision	2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS	macOS Version 13.6.4 (Build 22G513)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
Revision	5d9143e1a0812c53bdc27fd5384591254306a88c
OS	Linux
```
