### ISSUE TITLE
Crash on startup, Brave Nightly

### ISSUE THREAD

**Issue by Coffeeling** [brave/brave-browser#36655]
## Description 
Brave Nightly crashes a couple seconds after starting on both Windows 11 and macOS Sonoma 14.4.

Crash can sometimes be averted by restoring a closed window, but that is haphazard.

Had a similar, but instant crash on Windows in Beta a while ago, there it was confined to one profile. This issue affects the entire browser installation regardless of profile.

## Steps to Reproduce

   1. Try to launch Brave Nightly

## Actual result:
Brave Nightly either crashes immediately, or somewhat works for a couple seconds and crashes.

It does not hang most of the time, everything just ceases to exist.

## Reproduces how often: 
~95% of the time, I'd say?

## Brave version (brave://version info)
Brave	1.65.63 Chromium: 122.0.6261.111 (Official Build) nightly (64-bit) 
Revision	fa36a45339ae09bf39bafd628a09cea8809056f5
OS	Windows 11 Version 23H2 (Build 22631.3155)

Will post macOS version later.

## Version/Channel Information:
Nightly only, atm.

## Other Additional Information:

- Is the issue reproducible on the latest version of Chrome? 
    - Don't have Chrome, Brave Beta and Edge Stable seem to work.

**Comment by rebron** [comment]
@Coffeeling Can you post the crash id from brave://crashes when you get a chance?

**Comment by Coffeeling** [comment]
@rebron 

This is from struggling to get my Win11 Nightly install to open.

Crash from Friday, 8 March 2024 at 01:46:19
Status:	Not uploaded
Local crash context:	7589839d-d593-43e8-82ed-225f74c4d1a6
Crash from Friday, 8 March 2024 at 01:46:12
Status:	Not uploaded
Local crash context:	86bb8a23-a454-4153-bbc9-dcf69d0c477e
Crash from Friday, 8 March 2024 at 01:44:49
Status:	Not uploaded
Local crash context:	33fa79ce-2436-4d0f-814f-e144d6287871
Crash from Friday, 8 March 2024 at 01:44:31
Status:	Not uploaded
Local crash context:	60e2b752-8736-4b29-847c-89a0f4ddb081
Crash from Friday, 8 March 2024 at 01:44:21
Status:	Not uploaded
Local crash context:	775254e0-c29d-42e7-af89-fd09b3e3f0a9
Crash from Friday, 8 March 2024 at 01:30:32
Status:	Not uploaded
Local crash context:	c1eea232-2326-4366-94de-b87793781456

**Comment by arch-btw** [comment]
Same issue on Linux, I had to revert back. For me it was with: `brave-browser-nightly_1.65.66_amd64` and one more release that I forgot the version of.

Things I tried were disabling GPU, disabling Vulkan and a variety of flags. But it doesn't appears to be related to GPU.

A couple of errors I caught were:

`ssl_client_socket_impl.cc(970)] handshake failed` and

`vulkan_swap_chain.cc(400)] Swapchain is suboptimal.`

I am however, not sure if those errors were what caused it.

**Comment by arch-btw** [comment]
Just tried 1.65.68 to capture this log:

```
[38353:38353:0308/162906.554172:ERROR:policy_logger.cc(157)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(161) Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.
[38353:38353:0308/162906.887440:ERROR:profile_attributes_storage.cc(1033)] Failed to PNG encode the image.
[38353:38353:0308/162906.892388:ERROR:profile_attributes_storage.cc(1033)] Failed to PNG encode the image.
[38353:38353:0308/162906.892872:ERROR:profile_attributes_storage.cc(1033)] Failed to PNG encode the image.
[38353:38353:0308/162906.895202:ERROR:profile_attributes_storage.cc(1033)] Failed to PNG encode the image.
[0308/162909.038031:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0308/162909.038212:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0308/162909.040070:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0308/162909.042103:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0308/162909.050021:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0308/162909.050173:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0308/162909.052218:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0308/162909.053010:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0308/162909.053693:ERROR:process_memory_range.cc(75)] read out of range
[0308/162909.054160:ERROR:process_memory_range.cc(75)] read out of range
[0308/162909.066360:ERROR:process_memory_range.cc(75)] read out of range
[0308/162909.066396:ERROR:process_memory_range.cc(75)] read out of range
[0308/162909.067460:ERROR:process_memory_range.cc(75)] read out of range
[0308/162909.067491:ERROR:process_memory_range.cc(75)] read out of range
[38404:38415:0308/162911.950324:ERROR:ssl_client_socket_impl.cc(970)] handshake failed; returned -1, SSL error code 1, net_error -3
/usr/bin/brave-browser-nightly: line 48: 38353 Trace/breakpoint trap   (core dumped) "$HERE/brave" "$@"
```

**Comment by Coffeeling** [comment]
More Crash IDs from Windows 11:

Crash from Saturday, 9 March 2024 at 02:45:24
Status:	Not uploaded
Local crash context:	c75957e0-6695-4fc8-a829-585788f17d1c
Crash from Saturday, 9 March 2024 at 02:45:15
Status:	Not uploaded
Local crash context:	e20a36f3-ab45-43be-9de5-07504b3a4666
Crash from Saturday, 9 March 2024 at 02:45:07
Status:	Not uploaded
Local crash context:	ee624feb-8edb-4a27-a275-792dac4b2bb5
Crash from Saturday, 9 March 2024 at 02:44:58
Status:	Not uploaded
Local crash context:	6185df97-6ab2-41c2-866e-8bdcf39cd8e3
Crash from Saturday, 9 March 2024 at 02:41:15
Status:	Not uploaded
Local crash context:	d89c5a80-3997-4b9f-9a5e-04f0329c67d1
Crash from Friday, 8 March 2024 at 23:29:38
Status:	Not uploaded
Local crash context:	afdabe08-220f-4e3e-874f-20e259a9ddc6

**Comment by Coffeeling** [comment]
Crash from Saturday, 9 March 2024 at 02:45:24
Status:	Uploaded
Uploaded crash report ID:	5a6a0800-38c5-9e0b-0000-000000000000
Upload time:	Saturday, 9 March 2024 at 03:00:35
Crash from Saturday, 9 March 2024 at 02:45:15
Status:	Uploaded
Uploaded crash report ID:	516a0800-38c5-9e0b-0000-000000000000
Upload time:	Saturday, 9 March 2024 at 03:00:33
Crash from Saturday, 9 March 2024 at 02:45:07
Status:	Uploaded
Uploaded crash report ID:	4e6a0800-38c5-9e0b-0000-000000000000
Upload time:	Saturday, 9 March 2024 at 03:00:31
Crash from Saturday, 9 March 2024 at 02:44:58
Status:	Uploaded
Uploaded crash report ID:	496a0800-38c5-9e0b-0000-000000000000
Upload time:	Saturday, 9 March 2024 at 03:00:29
Crash from Saturday, 9 March 2024 at 02:41:15
Status:	Uploaded
Uploaded crash report ID:	466a0800-38c5-9e0b-0000-000000000000
Upload time:	Saturday, 9 March 2024 at 03:00:27
Crash from Friday, 8 March 2024 at 23:29:38
Status:	Uploaded
Uploaded crash report ID:	11630800-38c5-9e0b-0000-000000000000
Upload time:	Saturday, 9 March 2024 at 02:48:17
Crash from Friday, 8 March 2024 at 01:46:19
Status:	Uploaded
Uploaded crash report ID:	3cf80700-38c5-9e0b-0000-000000000000
Upload time:	Friday, 8 March 2024 at 23:29:37
Crash from Friday, 8 March 2024 at 01:46:12
Status:	Uploaded
Uploaded crash report ID:	34f80700-38c5-9e0b-0000-000000000000
Upload time:	Friday, 8 March 2024 at 23:29:35
Crash from Friday, 8 March 2024 at 01:44:49
Status:	Uploaded
Uploaded crash report ID:	2af80700-38c5-9e0b-0000-000000000000
Upload time:	Friday, 8 March 2024 at 23:29:32
Crash from Friday, 8 March 2024 at 01:44:31
Status:	Uploaded
Uploaded crash report ID:	27f80700-38c5-9e0b-0000-000000000000
Upload time:	Friday, 8 March 2024 at 23:29:30
Crash from Friday, 8 March 2024 at 01:44:21
Status:	Uploaded
Uploaded crash report ID:	20f80700-38c5-9e0b-0000-000000000000
Upload time:	Friday, 8 March 2024 at 23:29:27
Crash from Friday, 8 March 2024 at 01:30:32
Status:	Uploaded
Uploaded crash report ID:	19f80700-38c5-9e0b-0000-000000000000
Upload time:	Friday, 8 March 2024 at 23:29:26

**Comment by Coffeeling** [comment]
The latest updates have solved this for me, no crashes in the last couple days. Had the issue briefly even on Android, but the next update solved it.

**Comment by bsclifton** [comment]
Thanks for confirming @Coffeeling!
