### ISSUE TITLE
Allow Biometric Unlock toggle not updated in Wallet Settings

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#36669]
## Description: 

`Allow Biometric Unlock` toggle in Web3 settings is not updating correctly. Entering correct password will show the toggle as disabled until Web3 Settings is closed & re-opened. Sometimes entering an incorrect password then closing the modal (without entering correct password) can show the toggle as enabled until Web3 Settings is closed & re-opened.

## Steps to Reproduce 
  1. Setup wallet without biometrics, or disable in Web3 settings
  2. Enable `Allow Biometric Unlock` toggle in Web3 settings
  3. Enter password
  4. Observe toggle is still in disabled position
  5. Close Web3 Settings & re-open
  6. Toggle is in the enabled position

## Actual result: 

`Allow Biometric Unlock` toggle is enabled after entering correct password.
`Allow Biometric Unlock` toggle stays disabled if entering incorrect password & closing modal without entering correct password.

https://github.com/brave/brave-browser/assets/5314553/3ac962e9-fa6a-458f-a524-dde18d529f29

## Expected result:

Entering the correct password should close the modal and show the `Allow Biometric Unlock` toggle as enabled.
Entering the incorrect password & dismissing modal without entering correct password should continue to show the `Allow Biometric Unlock` toggle as disabled.

## Reproduces how often: 

Easily reproduced issue with entering correct password and toggle is not showing as enabled.
Intermittent issue with entering incorrect password and toggle is showing as enabled.

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari? 

### Additional Information

https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1710075181024309

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.5
Brave build: 1.65 (112)
BraveCore: 1.65.112 (124.0.6367.29)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/36669#issue-2177755819
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Allow Biometric Unlock` toggle switch keeps staying OFF when `Cancel` is tapped or the wrong password is provided
- Verified that the `Allow Biometric Unlock` toggle switch switched to ON when the correct password is provided

---------------------------

*Reproduced with build `1.64.123`*

https://github.com/brave/brave-browser/assets/128532965/a1781c4b-7d8f-461b-8e28-b70aa8ab3d4b

*Verified with build `1.65.112`*

https://github.com/brave/brave-browser/assets/128532965/20a1b67a-c812-41b4-a458-d10cfcca38c3
