### ISSUE TITLE
disabling the built-in PDF viewer extensions

### ISSUE THREAD

**Issue by cascer1** [brave/brave-browser#3666]
Hi!

I noticed Brave has [this extension](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm) installed by default for PDF viewing and I can't seem to disable it.
How can I go to the default chromium pdf viewer?

Thanks!

**Comment by gabrielhug** [comment]
You can disable Brave's built-in PDF extension with: chrome://settings/content/pdfDocuments

`Chromium PDF Viewer` has been blacklisted in Brave and AFAIK can't be re-enabled. However, alternate PDF viewer extensions can be added from the Web Store.

**Comment by rebron** [comment]
Closing. gabriel above provided instructions for disabling.
