### ISSUE TITLE
"Brave Ads paused" captcha alert unavoidable on open

### ISSUE THREAD

**Issue by wackerow** [brave/brave-browser#36665]
## Description 
"Brave Ads paused" alert displays every time I open Brave despite not using Brave ads.

## Steps to Reproduce

   1. Open Brave without rewards enabled, and ads turned off
   2. Get "Brave Ads paused" captcha popup wiht "Solve" or "Later"
   3. Either click "Later", or "Solve" and pick a country
   4. Quit Brave and reopen to get the exact same popup

## Actual result:

<img width="670" alt="image" src="https://github.com/brave/brave-browser/assets/54227730/61bbb5e1-ebad-487f-880d-db0d07502a0b">

## Expected result:

I do not have ads enabled, nor an ad account, and have solved the captcha... I would expect this alert to never pop up.

## Reproduces how often: 

Every time I open Brave

## Brave version (brave://version info)

Brave | 1.63.169 Chromium: 122.0.6261.111 (Official Build) (arm64)
Revision | 0e0a975cf46d4d026e184ca61788e1da6f0d76bc
OS | macOS Version 14.2.1 (Build 23C71)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?

**Comment by wackerow** [comment]
Brave	1.65.114 Chromium: 124.0.6367.60 (Official Build) (arm64) 
Revision	f1e2cbb65e11340d9040d5ef0b0115c7a5206207
OS	macOS Version 14.2.1 (Build 23C71)

Just offering an update here, I am now faced with the same "Brave Ads paused" popup, but am not able to dismiss it at all.

<img width="441" alt="image" src="https://github.com/brave/brave-browser/assets/54227730/90dd54ef-f072-4529-a2c5-c73073f6637e">

Opening Brave places this in the top right of my main display, and I cannot move or dismiss it. Solve and Later buttons both doing nothing, nor Escape/Enter/Space keys.

**Comment by wackerow** [comment]
Okay great 👍... just went back into the Brave Rewards settings (brave://rewards/) and used the "reset" button shown in the screenshot above. Reset everything, and the popup went away. Restarted Brave and the popup did not show up this time.

I think that took care of it on my end. Not sure exactly what happened there with the popup getting stuck. Anyone else? If this isn't an issue happening to others we could probably just close this out.

**Comment by Miyayes** [comment]
@wackerow Regarding the popup getting stuck, it was a regression due to some changes in Chromium. We did an urgent hotfix for it here: https://github.com/brave/brave-browser/issues/37760

**Comment by siothelibrarian** [comment]
I'm experiencing this issue on Windows 11 / v.1.78.94 as of updating to the most recent version. 

I previously had this issue and I was able to set some flag to make it go away, but since the most recent update, this popup is back, and it pops up anytime I open up the browser, or just every few hours, it appears. 

I do not and have never had ads turned on. I do not want them on. I also do not want to have to close this popup every time. Why is this popup appearing when I don't even had the option for ads on?
