### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ph0enixd0wn** [brave/brave-browser#36663]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.63.169 Chromium: 122.0.6261.111
Operating System: Windows NT 10.0.22631

URL (if applicable) where crash occurred:

Can you reproduce this crash?
This is the first day crashes occur. From this point on, Brave crashes every time.
What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/9f9f0700-100a-300b-0000-000000000000

**Comment by iefremov** [comment]
stale
