### ISSUE TITLE
[Leo]: Exclude keywords from Leo suggestions

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#36672]
Leo suggestions should not include a keyword - it results in some super weird queries when using omnibox keywords

Actual:
![image](https://github.com/brave/brave-browser/assets/7678024/51d19fbb-8b94-4241-a3aa-cdcdaeef29a1)

Expected:
![image](https://github.com/brave/brave-browser/assets/7678024/d661f130-c59c-4e8e-8c16-bc98b6480668)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.65.80 Chromium: 123.0.6312.29 (Official Build) nightly (64-bit)
-- | --
Revision | cd0c2b9c6f07e8f01724294c8d7e37393a8c3a38
OS | Windows 10 Version 22H2 (Build 19045.4170)
```

### Steps:
1. installed `1.65.80`
2. launched Brave
3. typed `:br ` and confirmed `Ask Leo` suggestion for `:br `
4. typed `foo` and confirmed that `Ask Leo`'s suggestion disappeared
5. continued the search

### Confirmed search shortcuts beginning with `:br ` drop it and suggest the remainder of the search term

example | example | example
----------|----------|-----------
![image](https://github.com/brave/brave-browser/assets/387249/210701df-780f-4db3-9f25-2b6d0e5ca396) | ![image](https://github.com/brave/brave-browser/assets/387249/9fb8bcb4-a3f0-4ad0-863e-074c13f43e19) | ![image](https://github.com/brave/brave-browser/assets/387249/b5bc131d-f2a4-43ff-b492-1f7b8e793749)

**Comment by stephendonner** [comment]
@brave/qa-team easy and good test(s), so I'm erring on the side of coverage; setting`QA/Test-All-Platforms` 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave	1.65.90 Chromium: 123.0.6312.58 (Official Build) beta (x86_64) 
Revision	f5ca64cd15d0d5c90f17b7d5213b6e2dd725d66a
OS	macOS Version 14.4.1 (Build 23E224)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
Revision	5d9143e1a0812c53bdc27fd5384591254306a88c
OS	Linux
```

### Steps:

1. installed `1.65.96`
2. launched Brave
3. entered a search keyword in the omnibox, followed by a query `:br foo` 
4. continued the search
5. entered a search keyword in the omnibox, followed by a query `:br shoes` 
6. selected `Ask Leo`

### Confirmed search shortcuts beginning with `:br ` drop it and suggest the remainder of the search term

example | example | example| example
----------|----------|-----------|-------
![image](https://github.com/brave/brave-browser/assets/98358127/1cfdca3d-ded9-4d03-8946-ce57c5637274)|![image](https://github.com/brave/brave-browser/assets/98358127/c20cf2fa-fa81-40fd-be8b-730c5debe86c)|![image](https://github.com/brave/brave-browser/assets/98358127/787785c9-1568-4107-beb4-63e011e2ec3c)|![image](https://github.com/brave/brave-browser/assets/98358127/89450bec-03b6-4ec4-81a5-1b54206532d1)
