### ISSUE TITLE
Crash when closing wallet onboarding

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36675]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

### Description
Crash when closing wallet onboarding

Brave Version: 1.64.97 Chromium: 122.0.6261.111
Operating System: Android 14

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Initiate wallet onboarding
2. Continue with onboarding and enter password
3. Close wallet onboarding on backup wallet screen
4. Browser crashes
5. Restart browser and open wallet doesn't load the wallet WebUI

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/4f461000-38c5-9e0b-0000-000000000000
Crash ID: crash/47461000-38c5-9e0b-0000-000000000000

**Comment by srirambv** [comment]
Also ran into similar crash on Lenovo Tab with Android 13. This time the crash happened after completing the onboarding for a new wallet 

Crash ID: crash/a0671000-38c5-9e0b-0000-000000000000

**Comment by simoarpe** [comment]
@srirambv can you please try again and let me know if this one is still observable on the latest master? Thanks!

**Comment by srirambv** [comment]
Not able to repro the similar crash on 1.67.18 x64 Nightly build. Closing the issue for now as stale
