### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by scarfdays** [brave/brave-browser#36670]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.63.169 Chromium: 122.0.6261.111
Operating System: Android 11

URL (if applicable) where crash occurred:

Can you reproduce this crash? Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open youtube
2. Play any video
3. 2 seconds into playing a video it crashes

Already tried:
Shields off
Restarting the phone
Uninstalling/reinstalling the app
Switching to Brave Nightly

To my knowledge nothing changed on my device. No issues with other browsers

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/25900e00-38c5-9e0b-0000-000000000000

**Comment by iefremov** [comment]
@scarfdays pls share more dump ids if you see this again, thanks. For now this one is not actionable
