### ISSUE TITLE
Brave IOS: Can not access Synology DSM website, OpenWRT Luci Website, Portainer website and other sites with private ssl certs

### ISSUE THREAD

**Issue by abysso2** [brave/brave-browser#36688]
### Description: 
Can not access Synology DSM website, OpenWRT Luci Website, Portainer website and other sites with non standard ports (e.g. 8080) - i just get a about:blank

### Steps to Reproduce 
  1. Start Brave IOS 1.62.1
  2. Try to open Synology DSM website, OpenWRT Luci website, Portainer website
  3.

### Actual result: 
Brave try to open the URL, but then stops immediatly with a blank page
Brave can open any other wesite 
Safari IOS can open the URL

### Expected result:
Brave shouls open the websites

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Every time

### Brave Version:  v1.62.1(24.3.29.16)

- Can you reproduce this issue with the current build from AppStore? Yes

### Website problems only:
- did you check with Brave Shields down? Yes
- did you check in Safari/Firefox (WkWebView-based browsers)? Yes, it works with Safari IOS 

### Additional Information
See also: https://www.reddit.com/r/brave_browser/comments/1b8qo3a/brave_ios_and_synologylocal_url/

**Comment by kylehickinson** [comment]
Thanks for the report! It seems like something has regressed with error pages. These pages your visiting most likely have self-signed SSL certificates and usually would show a "Your connection isn't private" page that would allow you to proceed anyways. We're investigating and hope to have a solution asap!

**Comment by abysso2** [comment]
> Thanks for the report! It seems like something has regressed with error pages. These pages your visiting most likely have self-signed SSL certificates and usually would show a "Your connection isn't private" page that would allow you to proceed anyways. We're investigating and hope to have a solution asap!

Uhh, this is correct, I also have a checkmk website listening on a non standard port, but this site has got a letsencrypt-cert. brave ios is loading this site without any problems ...

**Comment by kylehickinson** [comment]
Marking as QA/No as it will be tested in `brave-ios` 1.62.2 hotfix

**Comment by abysso2** [comment]
1.16.2 works as expected
