### ISSUE TITLE
auto contribution table often contains 2^32 - 1(4294967295) percentage entry for a short period of time

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#3668]
## Description 

![image](https://user-images.githubusercontent.com/11330831/54154006-2b605b00-43fe-11e9-8b37-ee66275cc6c7.png)

![image](https://user-images.githubusercontent.com/11330831/54154136-6e223300-43fe-11e9-83aa-522ea4d27080.png)

There entries all have -1 percent in `activity_info` in `publisher_info_db` like
`bcbsm.com|16|1|1.05088239607526|-1|0.49724982169539|1553877406`
## Steps to Reproduce

   1.  Have a auto contribution table
   2. Start excluding some entries
   3. 4294967295% entry will appear
   4. Keep removing, there will be more 4294967295 coming

## Reproduces how often: 

very often

## Brave version (brave://version info)

 0.63,4

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by jasonrsadler** [comment]
Repo'd underflow. Working.
<img width="1380" alt="Screen Shot 2019-04-08 at 4 21 35 PM" src="https://user-images.githubusercontent.com/25326067/55754436-a8411d80-5a1a-11e9-92c1-efe08ff6cc57.png">

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.64.68 Chromium: 74.0.3729.108 (Official Build) beta (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Windows 10 OS Build 17134.523

- Verified the test plan from https://github.com/brave/brave-core/pull/2187
