### ISSUE TITLE
Sync data type `Passwords and passkeys` is inherited from  CR123

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#36686]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/35807
Sync data type `Passwords and passkeys` is inherited from  CR123
## Steps to Reproduce

   1. NA
   

## Actual result:

![image](https://github.com/brave/brave-browser/assets/38657976/4233b001-aa10-4bcd-ad14-21c324323bba)

## Expected result:
It should be `Passwords` as per the slack discussion https://bravesoftware.slack.com/archives/CU5UXM3EC/p1710160465562619?thread_ts=1709854113.293739&cid=CU5UXM3EC

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.65.72 Chromium: 123.0.6312.29 (Official Build) nightly (64-bit)
-- | --
Revision | 75ece6f0929f2e2192810681aab5b6d48d9584f0
OS | Windows 10 Version 22H2 (Build 19045.4046)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @AlexeyBarabash

**Comment by kjozwiak** [comment]
Removing the `QA/Pass` label as the above was a `C123` regression and will need to be rechecked via `1.64.x` after channel migrations. The above requires `1.64.104` or higher for `1.64.x` verification.

@stephendonner probably a good idea not to bother verifying issues caused by `C123` as they usually get uplifted with `C123` as per https://github.com/brave/brave-browser/issues/36686#ref-pullrequest-2178827220 and need to be checked on the landing channel.

**Comment by kjozwiak** [comment]
The above requires `1.64.104` or higher for `1.64.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave	1.64.104 Chromium: 123.0.6312.46 (Official Build) (x86_64) 
Revision	0ca3d372cf8aab96fafdd75f5c5c8d2012bc0cc6
OS	macOS Version 11.7.10 (Build 20G1427)
```


### Steps:
1. installed `1.64.104`
2. launched Brave
3. opened `brave://settings/braveSync/setup`
4. examined sync categories

### Confirmed it's labeled `Passwords`

<img width="1312" alt="Screen Shot 2024-03-14 at 10 40 05 AM" src="https://github.com/brave/brave-browser/assets/387249/8ac18f6c-eb5b-4bad-aca1-d39e54864ee4">
