### ISSUE TITLE
Support Solana Token-2022 program

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#36699]
https://spl.solana.com/token-2022

We need
- Store token program info in `BlockchainToken` (token program or token-2022 program)
    - Update token-lists to provide token2022 boolean when `"tags":["community","token-2022"]` appears in fetched JupiterTokensList https://github.com/brave/token-lists/issues/138
    - Update `BlockchainToken` mojo struct to have an optional `SPLTokenProgram` enum with either `TokenProgram` or `TokenProgram2022` value.
    - Assign `TokenProgram` or `TokenProgram2022` for SPL tokens during parsing tokens from registry
- Get balance and transfer
    - `SolanaKeyring::GetAssociatedTokenAccount` needs to take `SPLTokenProgram` enum as a parameter to use the right token program ID.
    - Migrate from `Transfer` to `TransferChecked` because `Transfer` is deprecated.
    - During `MakeTokenProgramTransferTxData`, use the correct token program ID throughout the process.
- Auto discovery(`DiscoverSPLTokensFromRegistry`) and `GetSPLTokenBalances`
    - Update `GetSolanaTokenAccountsByOwner` to also query token2022 program ID.

Obsolete items just for reference:
~- Adding custom token manually
    - When adding custom SPL tokens, in the backend we need to make a network call to fetch the program owner (token program or token program 2022) before adding it (store in `BlockchainToken` struct) if it's still unknown.~ Just wait until balance fetching or transfer to update it.
~- Migration on existing user assets (SPL tokens only),  use network call to update their token program~ Retrieve account owner (which token program) when token is used.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.68.88 Chromium: 126.0.6478.71 (Official Build) beta (64-bit)
-- | --
Revision | 70077e4ec26f79de0bac54bc09204be0a3e6cea6
OS | Windows 11 Version 23H2 (Build 22631.3737)

- Verified steps form [brave/brave-core#23945](https://github.com/brave/brave-core/pull/23945)
- Verified Swaped token updates balance in Portfolio
- Verified able to send token to a different account successfully

https://github.com/brave/brave-browser/assets/17010094/aec04734-d03f-48fa-9107-b5073a0efbb4

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.68.99 x64 Beta build
- Verified steps form [brave/brave-core#23945](https://github.com/brave/brave-core/pull/23945)
- Verified Swaped token updates balance in Portfolio
- Verified able to send token to a different account successfully
