### ISSUE TITLE
Leo premium status not shown correctly for IAP [sandbox]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#36692]
## Description: 
Leo premium status not shown correctly for IAP [sandbox]

## Steps to Reproduce 
  1. Enable Leo
  2. Open Leo settings menu and `Go Premium` and complete the flow using sandbox environment
  3. Once purchase is completed, observe premium status in chat, 

## Actual result: 
Example | Example | Example
-|-|-
![IMG_5800](https://github.com/brave/brave-browser/assets/17885425/2f13c03e-4f60-417b-bd91-2d6318d84134) | ![IMG_5804](https://github.com/brave/brave-browser/assets/17885425/5768b4a7-1a59-4577-838d-20fb62b09a42) | ![IMG_5805](https://github.com/brave/brave-browser/assets/17885425/1d0dac72-cdb0-4a8a-89cf-1d47e49fdb2f)

## Expected result:
Premium status should be shown

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

## Brave Version: 1.63 (171)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? No
- Can you reproduce this issue with the current build from AppStore? No

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari?

**Comment by Brandon-T** [comment]
This should already be fixed in: https://github.com/brave/brave-core/pull/22578/files#diff-590a33746aeef57952ea66e671d0f4b4276921624ae21df0788aa2510352c2ecR311

**Comment by iccub** [comment]
added to 1.63 milestone

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.4
Brave build: 1.63 (179)
BraveCore: 1.63.179 (122.0.6261.128)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/36692#issue-2179496591
2. *Verify*

**ACTUAL RESULTS:**
- Verified that Leo's premium subscription status `Unlimited` is shown 

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/3a27609a-ca7f-4c50-aa7e-28e3609a76e9) | ![2](https://github.com/brave/brave-browser/assets/128532965/6f6608e0-ec7c-44ac-9657-477643ced8bc) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/3af16004-ff56-4594-bb72-044a3080d062) | ![2](https://github.com/brave/brave-browser/assets/128532965/fbe7ec46-9527-4a45-8338-6db553961659) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/757b4365-6328-4114-83e8-e540246122d3) | ![2](https://github.com/brave/brave-browser/assets/128532965/750b1d85-878e-4028-82c9-92988f498749) |
