### ISSUE TITLE
SIWE message displayed by DApp is wrapping in between words

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#36706]
can be seen when using SIWE on Zora.co. This looks to be supplied by the DApp, so we likely need to be doing something different with the `\n` characters.

![Screenshot 2024-03-12 at 9 09 58 AM](https://github.com/brave/brave-browser/assets/23125059/c8d9f31d-2910-4f83-a6e3-31d9581d99bc)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.97 Chromium: 124.0.6367.118 (Official Build) beta (64-bit)
-- | --
Revision | 94909f2aaefd7a8137c8b4fa27235378e79231e3
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22661](https://github.com/brave/brave-core/pull/22661)
- Verified `Statement` text doesn't break words when wrapping the `text`
![image](https://github.com/brave/brave-browser/assets/17010094/36a5cafe-0d54-463f-b12d-08c6325b50fe)
