### ISSUE TITLE
[CR123] Ad notifications are not shown. Logs show `Shutting down Bat Ads Service`

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#36704]
## Description 

Found while testing CR 123 manual pass https://github.com/brave/brave-browser/issues/36682.  After installing `1.65.73 Chromium: 123.0.6312.29 (Official Build) nightly` and enabling Rewards, Ad notifications not received. After enabling news no inline ads are shown and logs show `Shutting down Bat Ads service`.  Connected to Uphold and the logs show `Canceled timeout for notification ad...`.   Thanks to @LaurenWags for checking but she couldn't reproduce. 

## Steps to Reproduce

   1.  Install 1.65.73
   2.  launch Brave
   3.  enable rewards via `brave://rewards`
    
## Actual result:

- No ad notifications are shown -  `Shutting down Bat Ads Service`
- No inline ads are shown in the news feed.  Logs show `Shutting down Bat Ads Service`
- After connecting to uphold, no ads are shown are either.  However, seeing `Canceled timout for notification ad.....` message shown. 

[ads.txt](https://github.com/brave/brave-browser/files/14563759/ads.txt)
[news.txt](https://github.com/brave/brave-browser/files/14563760/news.txt)
[uphold.txt](https://github.com/brave/brave-browser/files/14563782/uphold.txt)

![image](https://github.com/brave/brave-browser/assets/98358127/0d8a03a1-c978-46fd-a45a-d865ed365ed6)

## Expected result:
Ads notifications should work as expected

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.65.73 Chromium: 123.0.6312.29 (Official Build) nightly (64-bit)
-- | --
Revision | 9cc34b8cfe9e8df8faede773545252783eefd953
OS | Windows 11 Version 23H2 (Build 22631.3155)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@tmancey @rebron 
cc: @brave/qa-team

**Comment by emerick** [comment]
cc: @aseren

**Comment by aseren** [comment]
The current issue is connected with Challenge-Bypass-Ristretto library crash when running in utility process: https://github.com/brave/brave-browser/issues/36690.
Brave Ads can be started in browser process by a griffin study. 
But if griffin seed was not downloaded and applied, then Brave Ads is started in utility process and has this crash. After browser restarted, a Study from griffin seed is applied, Brave Ads are running in browser process and no longer has this crash.
This particularly happened with @MadhaviSeelam, because browser was installed without using Omaha (which downloads and applies griffin studies).

The issue is not connected with CR123 chromium bump. It can be connected with specific Windows version. 
@MadhaviSeelam has 
Edition - Windows 11 Pro
Version - 23H2
OS build - 22631.3155

**Comment by tmancey** [comment]
Let's also enable all the griffin flags for search etc by default

**Comment by aseren** [comment]
I think it would be good to uplift this change to Beta, because Beta and Release users are having the crash: https://github.com/brave/brave-core/pull/22556

But we cannot uplift search features to Beta because it will break iOS.

**Comment by LaurenWags** [comment]
@aseren should this one be `release-notes/exclude` or `release-notes/include`?

**Comment by btlechowski** [comment]
Verified with:

Brave | 1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | 2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS | Windows 11 Version 23H2 (Build 22631.3296)

Reproduced the issue on 1.63.169
```
[1788:4688:0313/194652.439:VERBOSE2:ads_service_impl.cc(1047)] Shutting down Bat Ads Service
[1788:4688:0313/194652.439:VERBOSE2:ads_service_impl.cc(1080)] Shutdown Bat Ads Service
```

Verified by default `Utility: Bat Ads Service` is not listed in Task Manager

![image](https://github.com/brave/brave-browser/assets/34715963/9543598c-f669-4443-9638-5abfe3a76fbd)


Verified no crash and that Ads Service is not shutdown and ads are served:
```
[17980:12480:0322/150526.979:VERBOSE1:notification_ad_handler.cc(168)] Opportunity arose to serve a notification ad
[17980:12480:0322/150526.979:VERBOSE1:eligible_notification_ads_v2.cc(38)] Get eligible notification ads
[17980:12480:0322/150526.979:VERBOSE1:user_idle_detection.cc(33)] User is active after 7 s
[17980:12480:0322/150526.981:VERBOSE3:priority_util.h(21)] 2 untargeted ads with a priority of 1 in bucket 1
[17980:12480:0322/150526.981:VERBOSE3:priority_util.h(32)] 10 targeted ads with a priority of 1 in bucket 1
[17980:12480:0322/150526.982:VERBOSE1:eligible_notification_ads_v2.cc(129)] Predicted ad with creative instance id 6fb366f0-57cd-4c89-afa3-92e65bb1bc0b and a priority of 1
[17980:12480:0322/150526.982:VERBOSE1:notification_ad_serving.cc(126)] Found 1 eligible ads
[17980:12480:0322/150526.982:VERBOSE1:notification_ad_serving.cc(131)] Chosen eligible ad with creative instance id 6fb366f0-57cd-4c89-afa3-92e65bb1bc0b and a priority of 1
[17980:12480:0322/150526.982:VERBOSE1:notification_ad_handler.cc(184)] Served notification ad:
  placementId: 88fd3c31-5190-462c-a7b3-08e778c80150
  creativeInstanceId: 6fb366f0-57cd-4c89-afa3-92e65bb1bc0b
  creativeSetId: 6d532773-344c-4819-8d38-a636539aaa49
  campaignId: fb5535c7-f6e2-48bf-820a-f54d4a2ed85e
  advertiserId: bfac6e60-a86e-44d7-901b-49df77e5cae3
  segment: technology & computing
  title: Zdobądź nagrody BTC na Nexo
  body: Nowy w Nexo? Odbierz swoje 10 000 Satoshi!
  targetUrl: https://nexo.com/links/brave_mb_push_bitcoin_halving_q124
[17980:12480:0322/150526.986:VERBOSE1:notification_helper_impl_win.cc(182)] Notifications are enabled
[17980:12480:0322/150526.986:VERBOSE1:notification_helper_impl_win.cc(149)] Focus Assist is disabled
[17980:12480:0322/150526.994:VERBOSE6:ads_service_impl.cc(851)] Timeout notification ad with placement id 88fd3c31-5190-462c-a7b3-08e778c80150 in 120 s
[17980:12480:0322/150527.001:VERBOSE3:notification_ad_handler.cc(195)] Served notification ad with placement id 88fd3c31-5190-462c-a7b3-08e778c80150 and creative instance id 6fb366f0-57cd-4c89-afa3-92e65bb1bc0b

```

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240305.005 release-keys
Brave build: 1.65.101
Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/22556#issue-2182744180
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Brave Ads` successfully started
- Verified that `Shutting down Bat Ads Service` is not shown

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/7a8f5443-deb1-47cc-9aff-891eb54f1836) | ![2](https://github.com/brave/brave-browser/assets/128532965/bf5a8ee2-4dde-4f5b-ba1b-8580b10d655e) |
