### ISSUE TITLE
If Brave Ads catalog is stale user may not be able to submit payment tokens

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#3670]
## Description 
If the public key fails to validate in the following code:

`// Validate public key
  auto catalog_issuers = confirmations_->GetCatalogIssuers();

  auto iterator = catalog_issuers.find(public_key_base64);
  if (iterator == catalog_issuers.end()) {
    BLOG(ERROR) << "Response public_key: " << public_key_base64
        << " was not found in the catalog issuers";
    OnRedeem(FAILED);
    return;
  }
  auto issuer_name = iterator->second;`

then a user may not be rewarded for viewing an Ad if the Catalog is stale as OnRedeem(FAILED) removes the unblinded token and does not try again.

My proposed solution is to add last_updated_timestamp timestamp to locally persisted Catalog Issuers and if the catalog is older than one day tokens should not be redeemed until the catalog is updated

**Comment by tmancey** [comment]
Closing issue as will be resolved as part of https://github.com/brave/brave-browser/issues/7796
