### ISSUE TITLE
Verify when Rewards are toggled off (but Ads were not explicitly toggled off), there are no Ads logs recorded

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#36711]

**Comment by tmancey** [comment]
@rebron rewards.log will still contain any logs for ads up until the point ads were disabled. No new logs are recorded.

**Comment by MadhaviSeelam** [comment]
Sorry, this issue was accidentally created from the manual pass line item. Please ignore. Closing as Invalid.
