### ISSUE TITLE
Price History Endlessly Loads after Navigating from Accounts Page

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#36713]
## Description 

The `Portfolio` Price History endlessly loads after navigating from the `Accounts` page

## Steps to Reproduce

   1. Open the `Wallet` and go to the `Portfolio` view
   2. Wait for all `Price Data` to load and then navigate to the `Accounts` page
   3. Navigate back to the `Portfolio` page
   4. The `Price History` endlessly loads

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/5634d943-12fe-461e-ad56-3117a26da20a

## Expected result:

Should load `Price History`

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.97 Chromium: 124.0.6367.118 (Official Build) beta (64-bit)
-- | --
Revision | 94909f2aaefd7a8137c8b4fa27235378e79231e3
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22660](https://github.com/brave/brave-core/pull/22660)
- Verified price history loads after navigating from Accounts page

https://github.com/brave/brave-browser/assets/17010094/15b118a0-e450-44b9-b9f5-7940bd8825d4
