### ISSUE TITLE
Remove "Clear browsing data" from main menu [CR123]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#36728]
## Description 
Remove "Clear browsing data" from main menu on Android

## Steps to reproduce 

   1. Fresh install
   2. Open hamburger menu
   3. 

## Actual result 
![Screenshot 2024-03-12 at 11 29 21 AM](https://github.com/brave/brave-browser/assets/17885425/1a8635e7-1fa0-4b6d-ad6a-ef181b091476)

## Expected result
Remove from menu

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy S21, Tab S7
   - Android version: 13
   
## Brave version
`1.65.73, Chromium 123.0.6312.29`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.64.104` or higher for `1.64.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240216.010 release-keys
Brave build: 1.64.104
Chromium: 123.0.6312.46 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Install Brave
2. Open `Main menu` > *Verify*
3. Tap the `Tab switch` button > Three-dot > *Verify*

**ACTUAL RESULTS:**
- Verified that `Clear browsing data` is not shown in the `Main menu`

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/333fe83a-0b57-4958-92c6-0df979588ffa) | ![2](https://github.com/brave/brave-browser/assets/128532965/7bda43f7-8175-4564-a781-704f9877454c) |
