### ISSUE TITLE
App menu item for "Commander" is missing on Mac

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#36733]
Chromium removed commands feature, and the menu item is gone together. We should resurrect it.

Related: https://github.com/brave/brave-core/pull/22107

## Test Plan:
* Enable Brave commands flag
* Check if `main menu > view > Commander` exists
<img width="339" alt="image" src="https://github.com/brave/brave-core/assets/5474642/53a8ce63-b0e8-42cd-a883-ca4bdf3d01d8">

* Check if pressing `cmd + shift + p` opens command input mode in location bar
<img width="958" alt="image" src="https://github.com/brave/brave-core/assets/5474642/f9a94d1b-151a-4276-ab9c-f6e303b369b6">

**Comment by kjozwiak** [comment]
Labelling this as `QA/Blocked` as we're going to rollback this change via https://github.com/brave/brave-browser/issues/36777 which will need to be uplifted into `1.64.x`. @LaurenWags @rebron please correct me if I'm wrong.

**Comment by LaurenWags** [comment]
Makes sense to me to wait to test this issue until https://github.com/brave/brave-browser/issues/36777 lands with the updated name and keyboard shortcut 👍🏻

**Comment by LaurenWags** [comment]
Removed `QA/Blocked` as https://github.com/brave/brave-browser/issues/36777 is available in `1.64.106` or higher.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave	1.64.107 Chromium: 123.0.6312.46 (Official Build) (x86_64) 
Revision	cb2648b2e2cf3de3bbd87f1c2826e308ebf2f906
OS	macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.64.107`
2. launched Brave
3. opened `brave://flags`
4. confirmed `Brave Commands` is `Default (Enabled)`
5. opened `View >` `Quick commands`
6. confirmed available commands
7. exited
8. pressed `control` `+` `spacebar`

### Confirmed usable `Quick commands` menu with appropriate `control` + `spacebar` shortcut

example | example | example
---------|----------|--------
<img width="1568" alt="Screen Shot 2024-03-18 at 11 22 49 AM" src="https://github.com/brave/brave-browser/assets/387249/43475358-d38e-438f-bfc2-b37a447bee9a"> | <img width="388" alt="Screen Shot 2024-03-18 at 11 20 30 AM" src="https://github.com/brave/brave-browser/assets/387249/9b6e0500-8e8b-4b0a-b624-d8029a482099"> | <img width="1568" alt="Screen Shot 2024-03-18 at 11 20 35 AM" src="https://github.com/brave/brave-browser/assets/387249/47a2a805-2730-46aa-9715-6f7362cdccf0">

**Comment by stephendonner** [comment]
## Verified `PENDING` using 

```
Brave	1.64.107 Chromium: 123.0.6312.46 (Official Build) (arm64) 
Revision	cb2648b2e2cf3de3bbd87f1c2826e308ebf2f906
OS	macOS Version 13.6.4 (Build 22G513)
```

### Steps:
1. installed `1.64.107`
2. launched Brave
3. opened `brave://flags`
4. confirmed `Brave Commands` is `Default (Enabled)`
5. opened `View >` `Quick commands`
6. confirmed available commands
7. exited
8. pressed `control` + `spacebar`

### Confirmed usable `Quick commands` menu with appropriate `control` + `spacebar` shortcut

example | example | example
---------|----------|---------
<img width="1786" alt="Screenshot 2024-03-18 at 11 35 26 AM" src="https://github.com/brave/brave-browser/assets/387249/9de876a9-78f0-4a37-92ff-8bfb4135f623">
