### ISSUE TITLE
Sidebar toolbar button's context menu is not shown

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#36747]
## Steps to Reproduce

   1. Right click on sidebar toolbar button
   2. 
   3. 

## Actual result:

No context menu

## Expected result:
Context menu

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Verified `PASSED` using

```
Brave	1.66.53 Chromium: 123.0.6312.86 (Official Build) nightly (x86_64) 
Revision	a79fb87f4f3b5b0c833644ed870a657eef74b987
OS	macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.66.53`
2. launched Brave
3. context-clicked on the `Sidebar` icon in the browser toolbar
4. confirmed `Hide Sidebar Icon` text
5. chose menu item
6. confirmed `Sidebar` icon disappeared
7. confirmed I could toggle it back via `Show Sidebar button` in `brave://settings/appearance`

`Hide Sidebar Icon`

example | example | example | example
---------|----------|---------|----------
<img width="1486" alt="Screen Shot 2024-04-02 at 6 36 38 PM" src="https://github.com/brave/brave-browser/assets/387249/66d2bfec-53fd-4573-a217-d53baf846c8c"> | <img width="1486" alt="Screen Shot 2024-04-02 at 6 36 42 PM" src="https://github.com/brave/brave-browser/assets/387249/49b8e552-853c-4c8b-ae54-f80a4224de72"> | <img width="1486" alt="Screen Shot 2024-04-02 at 6 36 45 PM" src="https://github.com/brave/brave-browser/assets/387249/38c94856-ec73-4d59-a172-f8262833534a"> | <img width="1486" alt="Screen Shot 2024-04-02 at 6 37 00 PM" src="https://github.com/brave/brave-browser/assets/387249/91d20a91-513e-4c76-919b-a33aab415f56">
