### ISSUE TITLE
Search engine for private window switching to standard SE in certain conditions

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#36758]
## Description 
Reported by customer https://community.brave.com/t/the-search-engine-for-private-window-keeps-switching-to-brave/536531

Additionally there is UI issue with bottom toolbar showing with wrong color in this case:

https://github.com/brave/brave-browser/assets/30602739/1ed0b2bf-d5ac-42c9-94f3-4bd0d4c066d6

## Steps to reproduce 

   1. Set different search engines for private and standard tabs.
   2. Fully close the browser (e.g. via exit menu).
   3. Long tap on the icon and open private tab.
   4. Try to search anything, search engine set for standard tab will be used instead of private.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240426.023.B4 release-keys
Brave build: 1.67.105
Chromium: 126.0.6478.26 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/36758#issue-2184078301
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the search results are shown using a correct `SE` in a `Private tab`

---------------------------

https://github.com/brave/brave-browser/assets/128532965/36f40e7e-d4e6-44e3-8b57-2f518b913dfe
