### ISSUE TITLE
Unable to Hide/Unhide NFTs

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36754]
## Description 

Unable to Hide/Unhide NFTs

## Steps to Reproduce

   1. Restore wallet with NFTs
   2. Go to hidden NFTs
   3. Some of the Spam NFTs can't be marked as `Not Junk`
   4. Unhide a few Spam NFTs to list it in collected
   5. Go back to Collected NFTs
   6. Click on more menu and Hide NFT
   7. Doesn't hide the NFT
   8. Click on menu again shows Unhide button

## Actual result:

<video src=https://github.com/brave/brave-browser/assets/17010094/2bd1f617-17cf-4dea-8fcc-9dc150143e0c> | <video src=https://github.com/brave/brave-browser/assets/17010094/e4857054-9e70-4a6d-9b95-a24c468fd41e>
-- | --

## Expected result:
Should be able to Hide/Unhide NFTs 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.64.102 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | c9343c77bd5dee3524fc45f89721ce0bf4c09b8d
OS | Windows 11 Version 23H2 (Build 22631.3155)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam

**Comment by kjozwiak** [comment]
Labelled as `QA/Blocked` as this will be verified via `1.68.x` once https://github.com/brave/brave-core/pull/24802 is uplifted into `1.68.x`.

**Comment by kjozwiak** [comment]
The above requires `1.68.134` or higher for `1.68.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.68.134 Chromium: 127.0.6533.88 (Official Build) (64-bit)
-- | --
Revision | 71f3c9cc80f92022892bbf6a22c0450ea056ade4
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified able to mark NFTs as Not junk
- Verified able to mark collected NFT as Junk
- Verified able to hide/unhide NFTs successfully

https://github.com/user-attachments/assets/679cb36d-aba9-4d0e-82cd-5b25c8e43efa
