### ISSUE TITLE
wayland crash when drag & drop

### ISSUE THREAD

**Issue by Reginald-Gillespie** [brave/brave-browser#36766]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.63.169 Chromium: 122.0.6261.111
Operating System: Linux 6.7.9-arch1-1

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
I'm running under KDE wayland, ozone platform parameter is set to wayland but it also does it when that parameter is set to X11 iirc (although the OS is still running wayland). This crash happened when I dragged a file from dolphin into google docs. The file did make it into the doc, and was there when I relaunched after the crash. This also happens if I grab a tab and drag it down to make a new window, and then try to drag it back up into the window it came from / any other window. Hope this helps. 

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/23350000-7ff7-a70b-0000-000000000000

**Comment by kjozwiak** [comment]
```
[ 00 ] ui::(anonymous namespace)::SetRootLocation(ui::LocatedEvent*) ( wayland_event_source.cc:115 )
[ 01 ] ui::WaylandEventSource::SetTargetAndDispatchEvent(ui::Event*, ui::EventTarget*) ( wayland_event_source.cc:619 )
[ 02 ] ui::WaylandEventSource::OnHoldEvent(ui::EventType, unsigned int, base::TimeTicks, int, wl::EventDispatchPolicy) ( wayland_event_source.cc:818 )
[ 03 ] ffi_call_unix64
[ 04 ] ffi_call_int
[ 05 ] wl_closure_invoke ( connection.c:1178 )
[ 06 ] dispatch_event ( wayland-client.c:1597 )
[ 07 ] dispatch_queue ( wayland-client.c:1743 )
[ 08 ] wl_display_dispatch_queue_pending ( wayland-client.c:1985 )
[ 09 ] ui::WaylandEventWatcher::WlDisplayDispatchPendingQueueInternal(base::WaitableEvent*) ( wayland_event_watcher.cc:310 )
[ 10 ] ui::WaylandEventWatcher::WlDisplayDispatchPendingQueue() ( wayland_event_watcher.cc:296 )
[ 11 ] ui::WaylandEventWatcherGlib::HandleDispatch() ( wayland_event_watcher_glib.cc:137 )
[ 12 ] ui::(anonymous namespace)::WatchSourceDispatch(_GSource*, int (*)(void*), void*) ( wayland_event_watcher_glib.cc:53 )
[ 13 ] 0x79364b655f69
[ 14 ] 0x79364b717c96
[ 15 ] 0x79364b717bd3
[ 16 ] 0x79364b6b43a7
[ 17 ] 0x79364b716181
[ 18 ] 0x79364b65ca40
[ 19 ] 0x79364b654162
[ 20 ] base::MessagePumpGlib::Run(base::MessagePump::Delegate*) ( message_pump_glib.cc:680 )
[ 21 ] base::allocator::dispatcher::internal::DispatcherImpl<base::PoissonAllocationSampler>::AllocFn(allocator_shim::AllocatorDispatch const*, unsigned long, void*) ( dispatcher_internal.h:131 )
```

**Comment by Reginald-Gillespie** [comment]
Not really closed issues by hand on other projects before but I can't reproduce this anymore so gonna close it. If anyone googling for drag and dropping text crashing brave, I've posted an issue about that here: https://github.com/brave/brave-browser/issues/37777
