### ISSUE TITLE
Crash when accessing Brave Wallet from bookmark

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#36763]
## Steps to Reproduce

   1. Enable Brave Wallet
   2. Add Brave Wallet URL to bookmarks
   3. Click on Brave Wallet bookmark

## Actual result:

Browser crashes

## Expected result:
Tab navigates to Brave Wallet

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Latest master

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | 2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from issue description
- Verified no crash when opening Wallet from bookmark
- Verified for different wallet routes and no crash

https://github.com/brave/brave-browser/assets/17010094/2e7352f3-7ff1-4c74-94b7-e97258bf2b3a
