### ISSUE TITLE
Wallet: Persist balance for the rest of wallet other than Portfolio/Assets

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#36764]
We have already persist balances under Portfolio/Assets
We will do the same for other screen currently fetching balance once open:
1. Portfolio/NFTs
2. B/S/S fetching token balance
3. Activity(Transactions)
4. Accounts 
5. Asset Details 
6. Account Details 
7. Wallet Panel 

Each screen can ask for cached balance using `AccountInfo`, `TokenInfo` or both directly via `WalletUserAssetManager`. 
<s>No local cache dictionary needed for each view. </s>
Double check unit tests. Might need to update the `TestableWalletUserAssetManager` to return mock asset/account balances.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 1.69 (162)
- Verified steps from [brave/brave-core#24072](https://github.com/brave/brave-core/pull/24072)
- Verified balance updates quickly on the following screens 
   - Portfolio/NFT
   - Buy/Send/Swap screens
   - Activity screen
   - Account details screen
   - Asset details screen
   - Wallet panel
 - Verified on both clean install and upgrade profile when restoring wallet
 - Encountered [#40628](https://github.com/brave/brave-browser/issues/40628)
