### ISSUE TITLE
[Commander]: Rollback label & shortcut

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#36777]
This reverts the label to `Quick commands` and the shortcut on MacOS to Control+Space

**Comment by kjozwiak** [comment]
The above requires `1.64.106` or higher for `1.64.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave	1.64.107 Chromium: 123.0.6312.46 (Official Build) (x86_64) 
Revision	cb2648b2e2cf3de3bbd87f1c2826e308ebf2f906
OS	macOS Version 11.7.10 (Build 20G1427)
```

Verification notes in https://github.com/brave/brave-browser/issues/36733#issuecomment-2004214969

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave	1.64.107 Chromium: 123.0.6312.46 (Official Build) (arm64) 
Revision	cb2648b2e2cf3de3bbd87f1c2826e308ebf2f906
OS	macOS Version 13.6.4 (Build 22G513)
```

Verification notes in https://github.com/brave/brave-browser/issues/36733#issuecomment-2004261023

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.64.107 Chromium: 123.0.6312.46 (Official Build) (64-bit)
-- | --
Revision | cb2648b2e2cf3de3bbd87f1c2826e308ebf2f906
OS | Windows 11 Version 23H2 (Build 22631.3296)
```
Verified the issue in `1.64.107` and working as expected. 

- Correct label is shown in the hamburger/App menu: `Quick commands`
- `Ctrl + Spacebar` shown list of commands

1.63.x | 1.64.x 
------ | ------
![image](https://github.com/brave/brave-browser/assets/98358127/29492228-5fdf-451f-8c78-d3f81243ab1b)|![image](https://github.com/brave/brave-browser/assets/98358127/4962c09e-be47-4d85-8a6e-fbca6846b1e1)
<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/206c98b6-f74f-44f6-817b-8f63f00a9173">|![image](https://github.com/brave/brave-browser/assets/98358127/67f9aa19-c4aa-446e-a56b-1778186ba8e0)
