### ISSUE TITLE
Unable to select network selector from portfolio

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36774]
### Description: 
Unable to select network selector from portfolio

### Steps to Reproduce 
  1. Change network to Polygon or BSC
  2. Click on dropdown again 
  3. Doesn't open the network selector 

**Actual result:** 

https://user-images.githubusercontent.com/17010094/183609832-37b9232e-8beb-4df4-b6b0-b7f9e9183bc3.mp4

**Expected result:**
Should be able to select network selector to change network

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy but steps may not be accurate (Refer video)

**Brave Version:** 
1.42 (22.8.8.19)

**Device details:** 
iPad Pro (iOS 16 Beta 3) 

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @StephenHeaps @nuo-xu . Adding iOS 16 label coz the issue isn't reproduced on iOS 15/14

**Comment by StephenHeaps** [comment]
Network picker was removed from Portfolio with multi-chain support in https://github.com/brave/brave-ios/pull/6451. Please  re-test 🙂.

**Comment by srirambv** [comment]
Changing to `QA/No` as this is not testable now since network selection is removed in portfolio
