### ISSUE TITLE
Pre-optin News banner not (fully) visible in non-full screen view ports

### ISSUE THREAD

**Issue by LorenzoMinto** [brave/brave-browser#36770]
Related to https://github.com/brave/brave-browser/issues/35112

I'm on a 15'' screen, not full screen.
<img width="1197" alt="Screenshot 2024-03-13 at 17 45 54" src="https://github.com/brave/brave-browser/assets/13190144/f036cc38-b3fc-45a1-bf92-35d427c5a9e2">
<img width="1196" alt="Screenshot 2024-03-13 at 17 46 10" src="https://github.com/brave/brave-browser/assets/13190144/05b1f639-bf35-435b-8ae1-671aa922d74d">
Second screenshot is after I increase the window size. The news banner seems to be lower than the toolbar.

**Comment by LorenzoMinto** [comment]
cc @petemill @fallaciousreasoning

**Comment by MadhaviSeelam** [comment]
linking couple of related issues:
https://github.com/brave/brave-browser/issues/26296
https://github.com/brave/brave-browser/issues/23314

**Comment by MadhaviSeelam** [comment]
News peeking card is shown currently however, without Stats & Widgets on my 14" Windows laptop.  I've enabled clock in this screenshot.  Below is the screen resolution

![image](https://github.com/user-attachments/assets/46dffaf3-fcec-4eb9-8902-3be337927439)


```
Brave | 1.70.92 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 711f50838f629ac2be4d1d9592f72adecfd3c928
OS | Windows 11 Version 23H2 (Build 22631.4037)
```

<img width="955" alt="image" src="https://github.com/user-attachments/assets/6df58cc5-7f2a-4699-900a-3c2d74cf04a9">

**Comment by MadhaviSeelam** [comment]
closing this issue as this is dup of https://github.com/brave/brave-browser/issues/39367
