### ISSUE TITLE
Add delta balance percentage change on wallet portfolio page

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#36772]
### Description: 

Under the balance if you have a some visible assets we should display a percentage growth of your balance between the first balance in the timeframe vs the last one.

**Comment by StephenHeaps** [comment]
Fix with Portfolio v2 https://github.com/brave/brave-ios/pull/8140.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.4 running 1.64 (109)
- Verified steps from issue description
- Verified delta balance percentage change is shown in green for positive change
- Verified delta balance percentage change is shown in red for negative change
- Verified delta balance percentage change is shown correctly on both Portfolio and Token details page

https://github.com/brave/brave-browser/assets/17010094/66043ee3-bb60-4375-a5bf-7d306679ec86
