### ISSUE TITLE
Payout status banner not shown in self-custody case

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#36773]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/35334

In self-custody case, the ads payout banner is not shown on the panel for Android. It is shown on desktop. It was specifically mentioned by @Miyayes that the payout banner should show on the panel for self-custody as it does with other custodians.

Might have been implemented on desktop with https://github.com/brave/brave-browser/issues/35498, @zenparsing would probably know best.

## Steps to reproduce 

   1. Have a profile where you are connected to self custody
   2. View one or more ads for current month
   3. Make sure ads are cashed in/redeemed on the server (logs will confirm this)
   4. Advance device date to next month - depending on the date and/or what is returned from the parameters endpoint this will determine which banner is shown.
   5. Compare the panel to the brave://rewards page
   6. Banner is shown on brave://rewards but not panel

Note for QA: when re-testing this, check the pending status as well as all the possible responses from the endpoint: off, processing, complete.

## Actual result 

As per the below, the ads payout banner is not shown on the panel but it is shown on the brave://rewards page:

Pending | In Progress | Completed
--- | --- | ---
![Screenshot_20240502-142859](https://github.com/brave/brave-browser/assets/28145373/59c71751-3b92-4dff-86e2-d8c2dadb579f) | ![Screenshot_20240502-141025](https://github.com/brave/brave-browser/assets/28145373/e78bb5f6-9da3-48eb-895b-96ec82ad3afe) | ![Screenshot_20240502-143001](https://github.com/brave/brave-browser/assets/28145373/52a7b5c0-e7ce-4ce0-b649-114ac8cdf4e5)

## Expected result

Banner should be shown on the panel like it is in other custodial cases (note, just the banner should be shown, not the summary for self custody):

![Screenshot_20240402-145247](https://github.com/brave/brave-browser/assets/28145373/4f3a7ee4-f238-43a6-9d90-ad65b9fd126a)

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): arm
   - Device type (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version

1.64.97 Chromium: 122.0.6261.111

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @deeppandya @Miyayes

**Comment by deeppandya** [comment]
@Miyayes @LaurenWags this issue is happening because of the existing design we have. we have payout banners attached to summary and we are hiding summary for self custody. 
Sharing figma for ref : https://www.figma.com/file/XnadxdmrOHHPYRCdHFD91b/Rewards-Settings?type=design&node-id=712-50878&mode=design&t=QoECYj6fV5xHq3Ch-0

**Comment by deeppandya** [comment]
i am making an exception for self custody with different design on my own. i will be sharing the new design here. please let me know your thoughts

**Comment by deeppandya** [comment]
@Miyayes WDYT ?
![Screenshot_2024-05-05-18-27-57-20_82cebf612ef3f9a8762672c971adaed4](https://github.com/brave/brave-browser/assets/5146988/4055e3be-720b-42b6-bf6e-35d12a52a62c)
![Screenshot_2024-05-05-18-28-09-42_82cebf612ef3f9a8762672c971adaed4](https://github.com/brave/brave-browser/assets/5146988/54782eae-335f-452b-984b-8fe885dba606)

**Comment by LaurenWags** [comment]
Out of curiosity, is there a technical limitation as to why it couldn't match desktop? 

<img width="454" alt="303401221-876f0a31-707a-441f-b310-d919f05d8a7b" src="https://github.com/brave/brave-browser/assets/28145373/1c21ed63-8366-4e32-b25d-d660480793fd">

**Comment by kjozwiak** [comment]
The above requires `1.64.111` or higher for `1.64.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.64.112 Chromium: 123.0.6312.58 (Official Build) (32-bit)
Revision	99f35375946ee8d232a0b111983ea341c24eadb5
OS	Android 12; Build/SP1A.210812.016.C1; 31; REL
```
