### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by KrazeeDave** [brave/brave-browser#36776]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.63.169 Chromium: 122.0.6261.111
Operating System: Windows NT 10.0.22631

URL (if applicable) where crash occurred:Initial opening every extension crashes.  

Can you reproduce this crash?
reboot and restart brave it crashes.  second opening everything work including all the extensions. 
What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.Opening brave the first time after a reboot every extension crashes.   The second time I open it everything works fine, 
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/86380000-0f95-950b-0000-000000000000

**Comment by kjozwiak** [comment]
@KrazeeDave thanks for the report 👍 Looks like a OOM issue.

```
[ 00 ] RaiseException
[ 01 ] partition_alloc::internal::OnNoMemoryInternal(unsigned __int64) ( oom.cc:41 )
[ 02 ] base::allocator::dispatcher::internal::DispatcherImpl<base::PoissonAllocationSampler>::FreeFn(allocator_shim::AllocatorDispatch const *,void *,void *) ( dispatcher_internal.h:189 )
[ 03 ] 0xee7f9f41a0
[ 04 ] partition_alloc::internal::OnNoMemory(unsigned __int64) ( oom.cc:74 )
[ 05 ] RtlUnwind
[ 06 ] RtlUnwind
[ 07 ] blink::ReportV8OOMError(char const *,v8::OOMDetails const &) ( v8_initializer.cc:801 )
[ 08 ] RtlUnwind
[ 09 ] RtlUnwind
[ 10 ] RtlUnwind
[ 11 ] RtlUnwind
[ 12 ] RtlUnwind
[ 13 ] RtlUnwind
[ 14 ] RtlUnwind
[ 15 ] RtlUnwind
[ 16 ] v8::internal::Isolate::SignalFatalError() ( isolate.h:1472 )
[ 17 ] v8::Utils::ReportOOMFailure(v8::internal::Isolate *,char const *,v8::OOMDetails const &) ( api.cc:347 )
[ 18 ] RtlUnwind
[ 19 ] v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate *,char const *,v8::OOMDetails const &) ( api.cc:299 )
```

**Comment by KrazeeDave** [comment]
It's a brand new gaming laptop with 32 gig onboard memory. What would cause it to run out of memory and do that.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by iefremov** [comment]
@KrazeeDave can you please update and if it reproduces share more dumps?

**Comment by iefremov** [comment]
unfortunately this is not actionable until we get more details
