### ISSUE TITLE
Do not show decimal values for NFT in send screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36771]
### Description: 
Do not show decimal values for NFT in send screen

### Steps to Reproduce 
  1. Add an NFT to portfolio
  2. Select the token details page and click Send
  3. NFT shows balance in decimals

**Actual result:** 

Ethereum NFT | Solana NFT
-- | --
![image](https://user-images.githubusercontent.com/17010094/203783728-59ec9d4f-f617-46f3-8e67-9ca6da144e78.png) | ![image](https://user-images.githubusercontent.com/17010094/203783748-7bc7c75f-d2a9-42e4-b8f4-a4423276b548.png)

**Expected result:**
NFT should not be shown in decimal values

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.45.2 (22.11.23.16)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by StephenHeaps** [comment]
Inadvertently fixed with https://github.com/brave/brave-ios/pull/7576. Please re-test 🙂.

**Comment by srirambv** [comment]
Verification passed on iPhone 14 with iOS 17.4 running 1.64 (109)
- Verified steps from issue description
- Verified NFTs doesn't show any decimal value on Send screen

![image](https://github.com/brave/brave-browser/assets/17010094/e7d4dbba-9833-48c6-8e45-e69c33ee2ea3) | ![image](https://github.com/brave/brave-browser/assets/17010094/b42ff5d4-0ae9-476c-a749-3db286794a18) | ![image](https://github.com/brave/brave-browser/assets/17010094/9d8c8024-df3f-4b1c-ac84-37ea7fff3f22) | ![image](https://github.com/brave/brave-browser/assets/17010094/8c13c76f-46af-4008-a51b-eeabe8e33e3f) | ![image](https://github.com/brave/brave-browser/assets/17010094/a9a0001c-c06c-4c0b-a514-4053d3b55eff)
-- | -- | -- | -- | --
