### ISSUE TITLE
Suddenly thin font on youtube.com? (macOS)

### ISSUE THREAD

**Issue by marintoo** [brave/brave-browser#3677]
## Description 
The font on Youtube.com has completely changed on the latest Brave version.

## Brave version (brave://version info)
Version 0.60.48

### Additional Information
macOS latest

**Comment by kjozwiak** [comment]
@marintoo can you take a screenshot of what you're seeing in Brave? It will give us a better idea of what you're seeing. Here's how YT looks under `macOS 10.14.3 x64` using `0.60.48 Chromium: 72.0.3626.121`:

<img width="1202" alt="Screen Shot 2019-03-12 at 12 40 19 AM" src="https://user-images.githubusercontent.com/2602313/54174993-72cb0380-445f-11e9-8e66-e583a16724e3.png">

**Comment by marintoo** [comment]
Solved
