### ISSUE TITLE
Cursors jumps back to first word input when space is typed in restore screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#36775]
### Description: 
Cursors jumps back to first word input when space is typed in restore screen

### Steps to Reproduce 
  1. Select recovery in the onboarding screen
  2. Start typing the first word
  3. After first word is typed in click on space
  4. Only the first char of the second word is typed in before the cursor jumps back to word brave/brave-ios#1 and continues to type with already entered word

### Actual result: 
Cursors jumps back to first word input when space is typed in restore screen

### Expected result:
Continue to next word when space is added

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 
All

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @StephenHeaps @nuo-xu

**Comment by StephenHeaps** [comment]
This was fixed with https://github.com/brave/brave-ios/pull/7960 but missed being closed. Please re-test 🙂.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.4 running 1.64 (109)
- Verified steps from [brave/brave-ios#7960](https://github.com/brave/brave-ios/pull/7960)
- Verified cursor remains in the input field where a space is added and doesn't jump back to the previous word input field
