### ISSUE TITLE
Sending feedback form for Leo posts fails [bad request]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#36780]
## Description: 
Getting Bad Request for `https://feedback.brave.com/1/ai/feedback/form`, this seems to be because the rating id is invalid. Swapping the rating id with a valid id such as `"rating_id": "8a14836f-0a4e-450f-90ae-334f62b76d4f"` via proxy seems to be working (returning 200)

Network Activity: 

**req:**

```
{
	"category": "Answer is not helpful",
	"feedback": "test",
	"locale": "en_US",
	"rating_id": "3",
	"ymd": "2024-03-13"
}
```

**res:**

```
{
	"Renderer": null,
	"statusCode": 400,
	"error": "Bad Request",
	"message": "invalid rating id"
}
```
![Screenshot 2024-03-13 at 5 05 16 PM](https://github.com/brave/brave-browser/assets/17885425/8c3f76d9-c6c0-41af-a807-75acf230bfeb)

## Steps to Reproduce 
  1. Enable Leo
  2. Submit query
  3. Long press on response, select `Dislike Answer`
  4. Tap on `Add Feedback` on the banner shown in UI
  5. Enter some text and submit form

## Actual result: 
![IMG_5845](https://github.com/brave/brave-browser/assets/17885425/9a584dfb-a05c-4f58-adac-32e505bd07ad)

## Expected result:
Should succeed

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 
iPhone

**Comment by kjozwiak** [comment]
Closing as the above is being addressed/fixed via https://github.com/brave/brave-core/pull/22578.

**Comment by kjozwiak** [comment]
The above requires `1.63.177` or higher for `1.63.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.4
Brave build: 1.63 (177)
BraveCore: 1.63.177 (122.0.6261.128)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/36780#issue-2184921756
2. *Verify*

**ACTUAL RESULTS:**
- Verified that feedback is sent and the message `Feedback sent successfully` is shown

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/c875ef09-ca83-48cc-8422-ab144b60f817) | ![2](https://github.com/brave/brave-browser/assets/128532965/a7627cbf-2918-4a3e-a190-1bd296c5ca82) |
