### ISSUE TITLE
Grant server hit twice if dashboard and panel both have captcha failed info present

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#3678]
## Description 

If a user tries to claim a grant with the panel and is unsuccessful and then opens Rewards and tries to claim grant there, two requests are sent.

## Steps to Reproduce

   1. Open brave with verbose terminal, enable Rewards on clean profile
   2. Open panel and click to claim grant
   3. Purposefully fail CAPTCHA
   4. Open Rewards dashboard, click claim grant and fail CAPTCHA

## Actual result:

Two requests are sent to grant server to get new captcha image

## Expected result:
Only one request should be made

## Reproduces how often: 

Easy with above STR

## Brave version (brave://version info)

Brave | 0.64.1 Chromium: 73.0.3683.67 (Developer Build) (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Unknown

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
this is not a problem anymore with VG
