### ISSUE TITLE
The browser looks terrible

### ISSUE THREAD

**Issue by Joovsr** [brave/brave-browser#36792]
Hi, I'm using a browser on a desktop computer. I have a 1080p 24-inch monitor and the browser interface looks terrible on it. The font of the interface is small and blurred, the folder icons are also blurred and the font is small. 
In general, the light theme looks very bad. Inactive tabs visually differ little from an active tab.
Using vertical tabs causes "pain". I can't create a new tab by double-clicking on an empty space, I have to constantly reach down to create a new empty tab. I can't close the tab by double clicking on the tab. It's just awful. In addition, disabling the window title causes the crooked location of the window control buttons to be displayed.

**Comment by rebron** [comment]
@Joovsr Do you have a screenshot you can attach for the font issues size and blur issues.
