### ISSUE TITLE
Fix Add to Metamask error on Coingecko

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#36797]
## Description: 

`Add to Metamask` button on Coingecko ethereum token details page was not prompting the Add Suggested Token modal, instead throwing a toast saying `This token does not appear to be supported` error message.

## Steps to Reproduce 
  1. Visit [Coingecko.com](https://www.coingecko.com/)
  2. Find an ethereum token to add, ex. [UNI](https://www.coingecko.com/en/coins/uniswap) token.
  3. Tap the Metamask logo / Add to Metamask button
  4. Observe `This token does not appear to be supported` error toast

## Actual result:

https://github.com/brave/brave-browser/assets/5314553/e29070cb-a227-471d-bf76-c036aaa11e27

## Expected result:

Add Suggested Token modal is shown, allowing user to add the token.

## Reproduces how often: 

Easily reproduced

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari?

**Comment by kjozwiak** [comment]
The above requires `1.64.107` or higher for `1.64.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.4 running 1.64 (109)
- Verified steps from [brave/brave-core#22596](https://github.com/brave/brave-core/pull/22596)
- Verified able to add custom tokens via Add token button
- Verified added token is shown in visible asset list

https://github.com/brave/brave-browser/assets/17010094/77ddc4eb-e357-4d37-9ad4-6cc2468df491
