### ISSUE TITLE
Opening PDF in a tab shows chrome://extension URL and PDF extension favicon

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#368]
## Description 

Opening PDF in a tab shows chrome://extension URL and PDF extension favicon
## Steps to Reproduce

   1. Load any PDF in a new tab
   2. URL prefixes `chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/` to URL
   3. Tab shows PDF extension favicon instead of the site favicon

 ## Actual result:
![image](https://user-images.githubusercontent.com/17010094/41503650-eb928b1c-71a6-11e8-931d-f2f2c393c30f.png)

## Expected result:
Should not show the extension prefix and should load the website favicon. Only show extension icon if site doesn't have favicon set
## Brave version (about:brave info)

Install build

**Comment by bbondy** [comment]
I think this is actually OK for now, so moving to backlog.  Valid though.

**Comment by Liunkae** [comment]
This problem also hides the site info popup, which makes it harder to find the HTTPS certificate, cookies, and site settings.

Normal:
![](https://user-images.githubusercontent.com/19424103/49542483-57b68980-f89b-11e8-9bf4-7b997761f46a.png)
PDF:
![image](https://user-images.githubusercontent.com/19424103/49542499-613ff180-f89b-11e8-9ddd-f32249612a72.png)

**Comment by fmarier** [comment]
I think we can close this in favor of #3846.

**Comment by bbondy** [comment]
yep
