### ISSUE TITLE
Support local vector search for the selection of key text segments of page and video context

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#36801]
Key use case to support:
What is the Gnarly nutrition discount code in [this video](https://www.youtube.com/watch?v=nllGZ2nqr30)?
Revealed at 26:56 of the video, but because of our truncation method, Leo can't answer.

Often times our summarization and Q&A leads to truncation of the input text we send up. For now we warn about it, but users get this warning very often. And often we can't produce the answers people need because they are not within the first N characters. 

Your mission, should you chose to accept, is to support this local vector search.

This should only be employed when the context is too long.  For summarization tasks, it might be useful to select dissimilar things. We could perhaps see if the input query is a summarization query via a similar similarity comparison.

It likely involves some steps like:
- Preprocess the text: lowercase, remove special characters, sentence chunking
- Convert the preprocessed text into vectors: TF-IDF: Term Frequency-Inverse Document Frequency or Word2Vec or other
- Divide the long text into chunks and doing a similarity measurement
- For each chunk calculate the similarity to the prompt using cosine similarity or other
- Find best matches and sending only that subset to avoid the truncation warning we typically give and also be able to support better answers. 

I'm not sure if we'd use TFLite or just custom code for this type of stuff, so it involves some investigation.

**Comment by darkdh** [comment]
summarization will be excluded in this [PR](https://github.com/brave/brave-core/pull/24953) and tracked in a different [issue](https://github.com/brave/brave-browser/issues/40181)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.71.112 Chromium: 130.0.6723.44 (Official Build) (64-bit)
-- | --
Revision | 7d51df656b247f9432ee714a6d160142a1e11c13
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from [brave/brave-core#24953](https://github.com/brave/brave-core/pull/24953)
- Verified `brave-ai-chat-page-content-refine` is disabled by default
- Verified when the flag is enabled, profile folder creates `AIChatLocalModels`
- Verified when the flag is disabled, profile folder removes `AIChatLocalModels`
- Verified when `browser-ai-chat` is disabled, also removes `AIChatLocalModels` when `brave-ai-chat-page-content-refine` is enabled
- Verified `Page content is refined` or `Page content is truncated` is shown when page refine flag is enabled and very long article is used to summarize or ask questions


<video src=https://github.com/user-attachments/assets/04611e93-c455-4a1a-9668-9a77b1607482> | <video src=https://github.com/user-attachments/assets/5984d62c-1549-420a-86a4-652fed0e26cd>
-- | --

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240823.009 release-keys
Brave build: 1.71.112
Chromium: 130.0.6723.44 (Official Build) (64-bit) 
```

Filed follow-up issue #41662
---------------------------
<details>
<summary> Component updater, the dir name would be "AIChatLocalModels" </summary>

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/24953#issue-2440966403
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `brave-ai-chat-page-content-refine` is OFF by default
- Verified that `AIChatLocalModels` folder is not present in the `Profile` folder if `brave-ai-chat-page-content-refine` is OFF
- Verified that `AIChatLocalModels` folder was created and shown in the `Profile` folder if `brave-ai-chat-page-content-refine` is ON

---------------------------

|`brave-ai-chat-page-content-refine` is OFF|`brave-ai-chat-page-content-refine` is ON|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/79c15488-ca89-4a73-a9c6-d4d53c31537a) | ![2](https://github.com/user-attachments/assets/114412f9-95be-430d-9fa9-ea4df02f6777) |
| ![1](https://github.com/user-attachments/assets/94a7b4cb-21ea-46b2-ba29-adccbf055097) | ![2](https://github.com/user-attachments/assets/0ac05cff-f630-4f6e-88cf-837204075d34) |
</details>

<details>
<summary> Page content refine </summary>

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/24953#issue-2440966403
2. *Verify*

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>

**Comment by srirambv** [comment]
Scenario 2 is verified as part of https://github.com/brave/brave-browser/issues/41481#issuecomment-2419384212

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7
Brave build: 1.71 (116)
BraveCore: 1.71.116 (130.0.6723.58)
```
---------------------------

<details>
<summary> Component updater, the dir name would be "AIChatLocalModels" </summary>

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/24953#issue-2440966403
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `brave-ai-chat-page-content-refine` flag is OFF by default
- Verified that `AIChatLocalModels` folder is not present in the `Library > Application Support > Chromium` folder if `brave-ai-chat-page-content-refine` is OFF
- Verified that `AIChatLocalModels` folder was created/downloaded and shown in `Library > Application Support > Chromium` folder if `brave-ai-chat-page-content-refine` is ON

---------------------------

|Default(Disabled)|Enabled flag|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/b6f3fa66-1730-4b2d-8757-2919baf29f2e) | ![2](https://github.com/user-attachments/assets/c6744c4b-db6e-444c-a9b5-2e660eba0623) |
| ![1](https://github.com/user-attachments/assets/ef0e421c-0d96-43ac-aa67-9fbc7180970a) | ![2](https://github.com/user-attachments/assets/6da69982-d210-45bb-bc4e-910c662e20a2) |
</details>

<details>
<summary> Fresh profile - PASS </summary>

**STEPS:**
1. Launch Brave 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>
