### ISSUE TITLE
Add Claude 3 Haiku (Free) and Claude 3 Sonnet (Premium) to model selection

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#36802]
We'd like to deprecate Claude Instant in favor of  Claude 3 Haiku for the free tier and Claude 3 Sonnet for the premium tier. 
The client should reflect the name of the model in use, and we do not need to list Haiku once the user purchases premium, we can just upgrade Haiku to Sonnet for the usage.
We may want to consider changing the default at some point to Haiku but the scope of this task is to only add support and not change the default.

**Comment by nvonpentz** [comment]
Serverside changes https://github.com/brave/aichat-ops/pull/251

**Comment by LorenzoMinto** [comment]
This issue is not fully resolved by the above PR. Follow up outstanding issues:

- [ ] https://github.com/brave/brave-browser/issues/37988
- [ ] https://github.com/brave/brave-browser/issues/37989

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/22706 was merged into `master`. As per the discussion via https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1715100595902499, `iOS` is currently `QA/Blocked` until https://github.com/brave/brave-browser/issues/37989 has been resolved. CCing @Uni-verse @hffvld. So for the time being, verification for the above can only be done for `Desktop` & `Android`.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.66.103 Chromium: 124.0.6367.159 (Official Build) beta (x86_64)
-- | --
Revision | 74d46bb25d9ea5e6432e19f0cf38480cc372b0cf
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.66.105 Chromium: 125.0.6422.41 (Official Build) (64-bit) 
Revision	ba88d7bb175a55287d14014823d5da31fe9c8a47
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that Claude 3 Haiku and Claude 3 Sonnet are shown on the list as free tier and premium tier respectively for new users.
- Ensured that Default model for new conversation setting shows all the models in the list and `Mixtral` is set by default.
- Ensured that new Claude 3 models have the correct badging for free users:
  - [x] `LIMITED` badging for Haiku
  - [x] The lock icon for Sonnet
- Ensured that new Claude 3 models show the correct badging for premium users: 
  - [x] `UNLIMITED` badging for Haiku
  - [x] `Open lock icon for Sonnet
- Ensured that Leo defaults to `Mixtral` model.
- Ensured upgrade card is shown when selecting `Claude 3 Sonnet` from Language models menu as well as starting new conversation when default model is set to `Sonnet` in settings.
- Ensured switching language model to Haiku and hitting rate limit, upgrading to premium using IAP. 
- Ensured premium status is shown when using active credentials from `account.brave.com`

**_Defaults_**

Example | Example | Example | Example | Example
-|-|-|-|-
![Screenshot 2024-05-13 at 5 03 08 PM](https://github.com/brave/brave-browser/assets/17885425/ba086be9-13a0-4c52-bfbb-d276c571449b) | ![Screenshot 2024-05-13 at 5 03 17 PM](https://github.com/brave/brave-browser/assets/17885425/fdb0ea8e-0963-42a8-b7d0-5ffe6adcdebb) | ![Screenshot 2024-05-13 at 5 46 58 PM](https://github.com/brave/brave-browser/assets/17885425/f16587b7-46ae-4ace-8358-ea96e69021c5) | ![Screenshot 2024-05-13 at 6 35 20 PM](https://github.com/brave/brave-browser/assets/17885425/4b89ca50-179d-43e2-b237-28372d00d500) | ![Screenshot 2024-05-13 at 6 39 28 PM](https://github.com/brave/brave-browser/assets/17885425/c818e17c-832d-490e-8826-38c038e12f6e)



**_Premium via Active Credentials_**

Example | Example | Example | Example
-|-|-|-
![Screenshot 2024-05-13 at 5 28 32 PM](https://github.com/brave/brave-browser/assets/17885425/55b3058e-8053-4a64-84d8-16aa8a90559b) | ![Screenshot 2024-05-13 at 5 28 56 PM](https://github.com/brave/brave-browser/assets/17885425/f43eb99f-dec9-4713-a358-c1fe49a6e8df) | ![Screenshot 2024-05-13 at 5 32 54 PM](https://github.com/brave/brave-browser/assets/17885425/f8dae942-c031-4021-b737-906da343190c) | ![Screenshot 2024-05-13 at 5 45 11 PM](https://github.com/brave/brave-browser/assets/17885425/495a3786-d6e3-4ad5-8168-3165a6c8e40a)

**_Premium via IAP_**

Example | Example | Example
-|-|-
![Screenshot 2024-05-13 at 6 42 27 PM](https://github.com/brave/brave-browser/assets/17885425/a962bfab-23c8-4dd4-b931-7e48df7a4ef2) | ![Screenshot 2024-05-13 at 6 44 18 PM](https://github.com/brave/brave-browser/assets/17885425/cec0a77c-0040-49c0-8e7b-6ca1f4e4f06c) | ![Screenshot 2024-05-13 at 6 45 19 PM](https://github.com/brave/brave-browser/assets/17885425/3fa25229-2987-4a79-98de-9cddc2d527fb)

**Comment by Uni-verse** [comment]
In progress on iOS using version `1.66.110`
