### ISSUE TITLE
Update text and link on brave://flags

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#36803]
## Description 

Currently text reads in description "Chrome" and links to "https://www.google.com/chrome/beta/". 
This a regression. Should be Brave and point to `https://brave.com/download-beta/`

Same issue in Beta Channel but should say Try our Nightly channel and point to `https://brave.com/download-nightly/` instead of saying Dev channel. 

## Steps to Reproduce

   1. Visit brave://flags in Release channel or Beta channel
   2. Notice text description at the top.

## Actual result:

<img width="805" alt="Screenshot 2024-03-14 at 10 30 42 AM" src="https://github.com/brave/brave-browser/assets/5951041/e93ea2b2-9e8e-4f3b-9d14-6a7c348e852b">

## Expected result:
Should have Brave branding.

## Reproduces how often: 

Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? no.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by kjozwiak** [comment]
The above requires `1.64.106` or higher for `1.64.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave	1.64.107 Chromium: 123.0.6312.46 (Official Build) (x86_64) 
Revision	cb2648b2e2cf3de3bbd87f1c2826e308ebf2f906
OS	macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.64.107`
2. launched Brave
3. opened `brave://flags`
4. examined descriptive text

### Confirmed no more `...new Chrome features`, which is now `Interested in cool new Brave features?`

<img width="1450" alt="Screen Shot 2024-03-18 at 12 03 11 PM" src="https://github.com/brave/brave-browser/assets/387249/88f581ff-1e25-40f7-a5f2-179bf24e6ed9">
