### ISSUE TITLE
Migration to Core has broken URL comparison for landed ad, easter egg and search engine state

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#3680]
## Description 
Migration of bat-native-ads to Core has broken URL comparison for landed ad, easter egg and search engine state

## Steps to Reproduce broken URL for search engine

   1. Open a search engine, i.e. www.google.com

## Actual result:
Search engine state is not updated in `Default/ads_service/client.json`

## Expected result:
Search engine state should be updated in `Default/ads_service/client.json`

## Steps to Reproduce broken URL for landed Ad

   1. View an Ad
   2. Navigate to another tab
   3. Wait 10+ seconds

## Actual result:
Ad is Landed

## Expected result:
Ad should not be landed as user navigated away before 10 seconds had elapsed

## Steps to Reproduce broken URL for easter egg

   1. Open www.iab.com

## Actual result:
Easter egg is not activated

## Expected result:
Easter egg should be activated

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
0.63.x

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  Dev

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by bsclifton** [comment]
Updated milestone after https://github.com/brave/brave-core/pull/1925 was merged
@tmancey can you update the top post here to include a test plan?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.63.44 Chromium: 74.0.3729.75 (Official Build) beta(64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Linux

* Search engine entry is updated on `client.json` file
![image](https://user-images.githubusercontent.com/17010094/56300427-f2ee2400-6103-11e9-8882-c9dc723ec971.png)
*  Verified after viewing an ad navigating a new tab doesn't trigger an ad 
![image](https://user-images.githubusercontent.com/17010094/56300837-a35c2800-6104-11e9-83ae-446fb84f7548.png)
* Verified Ad shown on iab.com based on category `business` and not `business-advertising`. Verified with @jsecretan that this is expected
