### ISSUE TITLE
[Android] Artificial self custody linking case shouldn't let user get into verification flow - follow up to 35334

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#36804]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/35334

For the "Artificial case: Get invite even though custodian-linked" (@Miyayes or @LaurenWags can provide the doc with test plan), Android behaves differently than desktop. On desktop in this artificial case, while a notification dot is shown on the BAT logo (https://github.com/brave/brave-browser/issues/36121), there is no notification on the panel. On Android, the notification is shown and a user can go through the flow which will ultimately fail (as expected).

We should probably restrict them from getting into this flow when we know it will fail.

## Steps to reproduce 

1. Create new profile, create a Brave Wallet
2. Join Rewards and link to Uphold
3. Get your Rewards Payment ID and ask for it to be whitelisted
4. Enable the self custody flag. Restart the browser.
5. Observe what happens and try to go through the process:
   - A notification dot appears on the BAT logo (https://github.com/brave/brave-browser/issues/36121 was previously logged as follow up for the notification dot)
   - The notification text/invite for self custody is shown on the panel (this does not happen on desktop)
   - After clicking on the CTA on the notification, I am able to attempt to link to Solana (I follow all the prompts with wallet)
   - However when I try to finish the linking, I get the "Something went wrong" error (as expected)

Since we know this flow will fail when user is connected to a custodian already, we should probably restrict them from getting into this flow.

## Actual result 

![Screenshot_20240314-132249](https://github.com/brave/internal/assets/28145373/6214e85e-ff41-4eaa-aa86-24152f19d6b2) | ![Screenshot_20240314-132300](https://github.com/brave/internal/assets/28145373/b5a569ec-baf4-4ea0-bcdb-848a75635a66) | ![Screenshot_20240314-133314](https://github.com/brave/internal/assets/28145373/018c1366-ed87-46dd-a16f-d39f077f4d2e) | ![Screenshot_20240314-133332](https://github.com/brave/internal/assets/28145373/8c26163f-a4d0-4763-8642-8e074fbb5dcf)
-- | -- | -- | --

## Expected result

No notification/CTA if user is mistakenly whitelisted while connected to a custodian

## Issue reproduces how often 

easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 1.63.x n/a 1.64.x yes
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
 1.64.97

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @Miyayes @deeppandya

**Comment by deeppandya** [comment]
@LaurenWags what's the behavior we have on desktop ? i can match the same for android.

**Comment by zenparsing** [comment]
@deeppandya Can you automatically clear the notification if `ShouldShowSelfCustodyInvite` is false?

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.66.97`

- Verified the STR from the description and ensured that self-custody notification is not shown when user whitelisted the payment ID and connected to a custodian.
- Confirmed that notification dot appeared on the BR panel, click on the red dot doesn't open any notification.
