### ISSUE TITLE
Add Brave Leo deep link

### ISSUE THREAD

**Issue by iccub** [brave/brave-browser#36800]
This allows us to use such link for the in-app event or in other places.

Test plan:
1. Use prod channel
2. Copy brave://deep-link?path=brave_leo to notes.app
3. Tap on it
4. It should open the browser and open Leo

This will not work if onboarding has not completed. It may not work for few other edge cases if other screens are open, nothing to worry about.

**Comment by kjozwiak** [comment]
The above requires `1.63.177` or higher for `1.63.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 17.4` using the following build(s):

```
1.63.177 Chromium: 122.0.6261.128 (Official Build) unknown (64-bit)
--- | ---
Revision | f43e1b1dc6dc...
OS | iOS
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/36800#issue-2186813988, that clicking on the deep link opened `Leo` without any issues as per the following:

https://github.com/brave/brave-browser/assets/2602313/7be7921a-1803-4b19-b503-c4445c12ee18

-----------------------

Verification **PASSED** on `iPhone 11` running `iOS 17.4` using the following build(s):

```
1.63.177 Chromium: 122.0.6261.128 (Official Build)unknown (64-bit)
-- | --
Revision | f43e1b1dc6dce1f4139b11ae15ce93c4dbc0ea42
OS | iOS
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/36800#issue-2186813988, that clicking on the deep link opened `Leo` without any issues as per the following:

https://github.com/brave/brave-browser/assets/2602313/f08292c7-76eb-494e-bf6e-d0b7ea2b8327
