### ISSUE TITLE
Only Show Visible Assets in Account Details

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#36806]
## Description: 

Only user-visible assets should be displayed in Account Details screen.

## Steps to Reproduce 
  1. In Portfolio tab, open Edit User Assets screen
  2. Search for Pozzcoin on Solana Mainnet, or another asset not currently selected as visible
  3. Tap the coin to set as visible (you will see a checkmark). Tap done to dismiss.
  4. Switch to Accounts tab, tap any Solana account, if on v1.63 or later tap Assets row
  5. Verify Pozzcoin is displayed
  6. Close account details and switch back to Portfolio tab
  7. Open Edit User Assets screen, tap Pozzcoin row again to set as not visible (you should see checkmark removed). Tap done to dismiss.
  8. Switch to Accounts tab, tap any Solana account, if on v1.63 or later tap Assets row
  9. Observe Pozzcoin is still shown in assets list

## Actual result: 

https://github.com/brave/brave-browser/assets/5314553/057f972e-6f29-49b6-bdcb-7a80c6b3fa2f

## Expected result:

Only visible assets (marked with checkmark in Edit User Assets modal) should only show in Account Details.

## Reproduces how often: 

Easily reproduced

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari? 

### Additional Information

https://community.brave.com/t/i-think-my-wallet-is-hacked-and-i-want-to-know-what-to-do/537552

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.5 running 1.66 (102) Beta build
- Verified steps from [brave/brave-core#22611](https://github.com/brave/brave-core/pull/22611)
- Verified adding a token from visible asset list shows up in Account token list
- Verified removing a token from visible asset list doesn't show up in Account token list

https://github.com/brave/brave-browser/assets/17010094/89d1e5aa-009c-414c-941c-8504d89bdfb5
