### ISSUE TITLE
Support Creating Bitcoin Accounts on iOS

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#36811]
## Description: 

Add support for creating a Bitcoin account in accounts tab. Note that Bitcoin accounts do not have an address for display, might require fix-up on Account tab UI. Hiding NFTs/Dapp Connections rows in account details, disabling export account, etc may suffice for this issue.

We should use the BraveCore `FeatureList` support to enabled Bitcoin when the [BraveCore Bitcoin feature flag is enabled](https://github.com/brave/brave-core/blob/ab6119da99c05f94775801919480d1cd0aab10fc/components/brave_wallet/common/config.gni#L11).

This brave core feature flag can be checked on iOS side via:
```
BraveCore.FeatureList.kBraveWalletBitcoinFeature.enabled
```

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.5 running 1.66 (105) Beta build
- Verified steps from [brave/brave-core#22737](https://github.com/brave/brave-core/pull/22737)
- Verified Bitcoin on Mainnet is displayed on Portfolio on a clean wallet creation
- Verified Bitcoin accounts can be created for both Mainnet and Testnet
- Verified on clean wallet select Bitcoin from portfolio and selecting Deposit/Send shows account creation prompt
- Verified able to edit Bitcoin account name on both Mainnet and Testnet
- Encountered [#36966](https://github.com/brave/brave-browser/issues/36966) & [#36968](https://github.com/brave/brave-browser/issues/36968)

https://github.com/brave/brave-browser/assets/17010094/7703d645-49d5-413c-872e-489e197edb3b
