### ISSUE TITLE
`default modal for new conversations` not respecting user choice and always reverting to `Mixtral`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#36816]
## Description: 

The `default modal for new conversations` setting under `Advanced Settings` doesn't seem to be working. If the user picks either `Claude Instant` or `Llama 2 13b`, it always seems to revert back to `Mixtral`.

## Steps to Reproduce
 
  1. install `1.63.176 Chromium: 122.0.6261.128` via TF
  2. once you've gone through onboarding/open `Leo` via the `Hamburger Menu` and run through the onboarding/T&S
  3. click on `Hamburger Menu` -> `Settings` -> `Leo` and tap on `default modal for new conversations`
  4. pick either `Claude Instant` or `Llama 2 13b` and close the `Settings` page
  5. either go back to the `Leo` settings page or take a look at `Leo` and notice that `Mixtral` is still the default model

## Actual result: 

https://github.com/brave/brave-browser/assets/2602313/8cefd2c2-5d75-408b-86cc-2f99b776cf7c

## Expected result:

The `default modal for new conversations` setting should remember/respect the users choice rather than defaulting to `Mixtral`

## Reproduces how often: [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases outlined above.

## Brave Version: 

```
1.63.176 Chromium: 122.0.6261.128 (Official Build) unknown (64-bit)
--- | ---
Revision | 0767ff0f97fb...
OS | iOS 17.4 using iPhone 11
```

- Can you reproduce this issue with the most recent build from TestFlight? `Yes`
- Can you reproduce this issue with the previous version of the current build from TestFlight? `Yes`
- Can you reproduce this issue with the current build from AppStore? `N/A` (`1.63.x` hasn't been released which includes `Leo`)

### Device details: 

* `iPhone 11` running `iOS 17.4`

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Is the issue reproducible on the latest version of Mobile Safari? `N/A`

**Comment by Brandon-T** [comment]
Brave-Core problem and also happens on Android and Desktop afaict.

We call `api.changeModel("chat-claude-instant")` or w/e the key is based on the selection for example.
It changes for sure.

Then when you create a new instance of Brave-Core API, it returns us `chat-leo-expanded`.
So this means Brave-Core does not persistently save the model selection.

I can probably fix it by saving it in a preference and forcing it every time, but that will require me to change the model every single time you load the screen which makes no sense. 

This should be fix for Desktop and Android as well. It will likely be fixed for 1.64.x as it probably requires bigger changes.

**Comment by mattmcalister** [comment]
You sure this is a desktop problem, too? The setting persists for me. cc @stephendonner

**Comment by kjozwiak** [comment]
The above requires `1.63.178` or higher for `1.63.x` verification 👍 @hffvld @Uni-verse keep in mind that https://github.com/brave/brave-browser/issues/36886 is still an issue.

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.4
- iPad Air / iPadOS 16.7.2
Brave build: 1.63 (178)
BraveCore: 1.63.178 (122.0.6261.128)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/36816#issue-2187708393
2. *Verify*

**ACTUAL RESULTS:**
- Verified that Brave can save `Claude Instant` or `Llama 2 13b` as a default language model. **_NOTE:_** _This issue #36886 still exists._

---------------------------

*iPhone*

https://github.com/brave/brave-browser/assets/128532965/ecc5c40f-2e48-48f3-aafd-a3154277c884

*iPad*

https://github.com/brave/brave-browser/assets/128532965/15b9041c-8171-4c59-af0e-f5e4ddd0c59e
