### ISSUE TITLE
[Wallet] Pending Transaction warning box dismiss button placement is off

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#36843]
## Description 

The dismiss button for the pending transaction warning box wraps below the text too eagerly

## Steps to Reproduce

   1.  Queue a pending transaction with insufficient funds for gas.
   2. Observe the warning in the panel

## Actual result:

![image (4)](https://github.com/brave/brave-browser/assets/30185185/bf46ae69-d3d1-4875-9e98-e7a0ec296c88)

## Expected result:
<img width="389" alt="Screenshot 2024-03-15 at 2 23 52 PM" src="https://github.com/brave/brave-browser/assets/30185185/d3498a00-3498-4912-ac3c-5c5bfcc577d0">

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.101 Chromium: 124.0.6367.118 (Official Build) beta (64-bit)
-- | --
Revision | 62fb0f940cad0714f585e2f01d2f968d64592d25
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from issue description
- Verified pending transaction warning close button placement is correct 
![image](https://github.com/brave/brave-browser/assets/17010094/1e364e3d-5bc0-4547-b695-a8b0adeacb46)
