### ISSUE TITLE
`Search tabs` should be on the side of vertical tabs

### ISSUE THREAD

**Issue by NomarCub** [brave/brave-browser#36855]
The search tabs button is in the upper right corner, and vertical tabs are on the left, pretty far apart. (I know they can be configured to the be on the right too.)
Tab related functionality should be accessible from the same place. It could be in either of the places I marked (1, 2, 3), or in the bottom of the vertical tabs sidebar thing.

![image](https://github.com/brave/brave-browser/assets/5298006/35a75962-56db-4c86-bae1-5c45ed346e1f)

## Brave version

1.63.174 Chromium: 122.0.6261.128 (Official Build) (64-bit)

**Comment by rebron** [comment]
This is Windows and Linux specific. The search tabs icon is in vertical tabs panel for macOS.

**Comment by NomarCub** [comment]
I don't know when this was fixed, but now the search button is at the right place (1).
Meanwhile Chrome has introduced a setting for "tab search position", which still can't be set in Brave for normal horizontal tabs.
