### ISSUE TITLE
Skus SDK returning no credentials

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#36851]
## Description 
- Brave-Core returns `premiumStatus = .activeDisconnected` even when a user paid for Premium.
- It also returns `remaining_credentials_count = 0` and `expired = null` but `active = true` which makes no sense.

```
{
  "order": {
    "id": "d4edb7af-224c-4729-be8f-6ffe3be0720f",
    "created_at": "2024-02-17T07:20:41.519882",
    "currency": "USD",
    "updated_at": "2024-02-17T16:05:26.333704",
    "total_price": 15,
    "location": "leo.bravesoftware.com",
    "merchant_id": "brave.com",
    "status": "canceled",
    "items": [
      {
        "id": "1546d43e-20ea-4042-9c24-c025759fd237",
        "order_id": "d4edb7af-224c-4729-be8f-6ffe3be0720f",
        "sku": "brave-leo-premium",
        "created_at": "2024-02-17T07:20:41.519882",
        "updated_at": "2024-02-17T07:20:41.519882",
        "currency": "USD",
        "quantity": 1,
        "price": 15,
        "subtotal": 15,
        "location": "leo.bravesoftware.com",
        "description": "Premium access to Leo",
        "credential_type": "time-limited-v2"
      }
    ],
    "metadata": {
      "stripe_checkout_session_id": null,
      "payment_processor": "ios",
      "num_intervals": 8,
      "num_per_interval": 192
    },
    "expires_at": "2024-03-17T15:59:34.511905",
    "last_paid_at": "2024-02-17T15:59:34.511905"
  },
  "remaining_credential_count": 0,
  "expires_at": null,
  "active": false,
  "next_active_at": null
}
```
`premiumStatus = activeDisconnected`
`remaining_credential_count = 0, expires_at = null, active = false`

## Steps to Reproduce

   1. Become a premium user
   2. Wait over 24 hours

## Actual result:
- Premium user is rate limited
- Desktop shows "Session Expired" and asks the user to login

## Expected result:
- Premium user should not be rate limited ever.

## Reproduces how often: 
- Intermittent Issue

**Comment by mattmcalister** [comment]
This is related to multiple issues, as discussed in the Premium dev meeting yesterday. The grace period fix will address part of the problem and the new `Restore` flow should give users a way to solve it on the client.

**Comment by mattmcalister** [comment]
Closing this now that credential `Restore` is available on clients, although the longer term refactor is still an open issue. Will track that work separately.
