### ISSUE TITLE
Update settings for Shields, and Privacy and security 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#36859]
## Description 

Follow-up to https://github.com/brave/brave-browser/issues/36363

In brave://settings/shields:
- [x] Move `Show the number of blocked items on the Shields icon` setting above `Trackers & ads blocking`
- [x] Move `Auto-redirect AMP pages`, `Auto-redirect tracking URLs`, and `Prevent sites from fingerprinting me based on my language` to brave://settings/privacy. Right below `Use Google services for push messaging`
- [ ] Move `Third-party cookies` from brave://settings/privacy to brave://settings/shields, fully replacing `Block cookies` and the drop down menu in favor of this link to the sub-menu. Keep the top-level label `Block cookies` and the sub-label from `Third-party cookies` (reflecting current status).

In brave://settings/privacy:
- [x] Move `Clear browsing data`, `Security`, and `Site and Shields settings` to the top of the `Privacy` section.
- [x] Create a new section called `Data collection` below the `Tor windows` section and move the Allow p3a, Allow ping, and Allow diagnostic reports into that section.
- [x] Remove `Safety check` section.

## Design
<img width="804" alt="Screenshot 2024-03-19 at 5 09 25 PM" src="https://github.com/brave/brave-browser/assets/5951041/033d8503-0ebd-45b2-8f73-0ba16a269de5">
<img width="793" alt="Screenshot 2024-03-19 at 5 09 38 PM" src="https://github.com/brave/brave-browser/assets/5951041/1ba17ca9-708f-4871-9f41-f256056ac3cb">

## Reproduces how often: 

n/a

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc: @ShivanKaul, @fmarier, @diracdeltas

**Comment by ShivanKaul** [comment]
@emerick I don't know if you'd gotten to the 3rd point in the issue for changes in brave://settings/shields, but just wanted to call out that I added the requirement for the sub-label for `Block cookies`.

> Move Third-party cookies from brave://settings/privacy to brave://settings/shields, fully replacing Block cookies and the drop down menu in favor of this link to the sub-menu. Keep the top-level label Block cookies and the sub-label from Third-party cookies (reflecting current status).

**Comment by emerick** [comment]
@rebron This is just about done (all checked items are finished), except I haven't removed the original "Block cookies" dropdown as you mentioned that it still needs to be supported somewhere. Let me know if you have any thoughts as far as where it should go. At the moment, I just have it in brave://settings/shields right above the "Block cookies >" entry.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.66.59 Chromium: 123.0.6312.105 (Official Build) nightly (64-bit)
-- | --
Revision | 2714c7ac837e7b7693b1b56a82effdf57e04fe09
OS | Windows 11 Version 23H2 (Build 22631.3374)
```

1. Installed 1.66.59
2. launched Brave
3. opened `brave://settings/shields`

Case 1: `brave://settings/shields`
<details>

#### Confirmed `Show the number of blocked items on the Shields icon` setting is shown above `Trackers & ads blocking`
#### Confirmed the toggle `off`/`on` to show blocked items work as expected

`1.64.116` | `1.66.69`(light theme) | `1.66.69` (dark theme)
----- | ------ | -------
<image width="500" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d7add639-5b4e-44c7-a3e3-9729f95c0453">|<image width="325" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/79b4a32d-148d-4762-a26e-3e7b0e5c2b6d">|<image width="500" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d3795703-11a6-479f-a190-17bb9c901019">

#### Confirmed following settings are moved from `brave://settings/shields` page to `brave://settings/privacy` page and are shown right below `Use Google services for push messaging`
#### Confirmed `Learn more` links work as expected
#### Confirmed `Auto-redirect AMP pages` toggle `on/off` work as expected 

  - `Auto-redirect AMP pages` 
  - `Auto-redirect tracking URLs`
  - `Prevent sites from fingerprinting me based on my language` 

***Note: Support pages need an update***

`1.64.116` | `1.66.69`(light theme | `1.66.69` (dark theme)
----- | ------ | -------
<image width="500" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/3c87df8d-0730-4086-ba28-bdfb7af96d66">|<image width="325" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/668d4325-2e0a-4669-87ac-5b8e9a3be8d6">|<image width="500" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/43b6b2a9-5872-4bbc-ab59-68c38cf8d886">

**_Auto-redirect AMP pages_**

- opened `brave://settings/privacy`
- enabled `Auto-redirect AMP pages` setting as default
- loaded https://shivankaul.com/brave/de-amp/test-amp-lightning-empty-attribute.html

example | example 
------ | ------
![image](https://github.com/brave/brave-browser/assets/98358127/3c9bf52a-9aac-4a80-9640-cb455adc4382)|![image](https://github.com/brave/brave-browser/assets/98358127/5fb16778-9b39-4660-a129-9b9668eb899c)
![image](https://github.com/brave/brave-browser/assets/98358127/13e2fc82-582f-457d-b225-639bd1b62762)|![image](https://github.com/brave/brave-browser/assets/98358127/2a54009e-c809-4e93-903e-3084d8dd3ad3)
</details>

Case 2: `brave://settings/privacy`
<details>

### Confirmed following settings moved from bottom to the top of the `Privacy and Security` section in the `brave://settings/privacy`
      - `Clear browsing data`, 
      - `Security`
      - `Site and Shields` 

`1.64.116` | `1.66.69`(light theme | `1.66.69` (dark theme)
----- | ------ | -------
![image](https://github.com/brave/brave-browser/assets/98358127/cdd55d55-2977-4423-b892-a7e89767c127)|![image](https://github.com/brave/brave-browser/assets/98358127/bfb20872-9554-4e30-bcc0-2b3b13b8ed9b)|![image](https://github.com/brave/brave-browser/assets/98358127/88d199a2-9901-40f8-98ba-002909ba7021)

**_Data collection_**

Confirmed a new section called `Data collection` displayed below the `Tor windows` section and following settings are shown in the section in the `brave://settings/privacy`

  - Allow privacy-preserving product analytics (P3A)
  - Automatically send daily usage ping to Brave
  - Automatically send diagnostic reports
  
example | example | example 
------ | ------ | -----
![image](https://github.com/brave/brave-browser/assets/98358127/c3946010-7baa-4384-91c9-22dcfbd0c8ed)|![image](https://github.com/brave/brave-browser/assets/98358127/af3e16fb-3ffb-4dc8-af83-aa5f4e293239)|![image](https://github.com/brave/brave-browser/assets/98358127/15daa875-412c-4e07-8d3b-9f1ed91129f6)

**_Safety check section_**

- Confirmed `Safety check` section is no longer shown at the bottom of the page of `brave://settings/privacy`

1.64.116 |1.66.59
---- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/543a0a2b-9735-404d-b29d-da9ae1a042b2)|![image](https://github.com/brave/brave-browser/assets/98358127/0b7742f6-c334-44f7-a672-fbda5d702993)

</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.66.94 Chromium: 124.0.6367.91 (Official Build) beta (x86_64)
-- | --
Revision | 1574096f9d2bcb69c3654cb4437217121ee9600b
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave	1.66.94 Chromium: 124.0.6367.91 (Official Build) beta (64-bit) 
Revision	1574096f9d2bcb69c3654cb4437217121ee9600b
OS	Linux
```
