### ISSUE TITLE
Need to update font's color for the `Add Feedback` when device is in `Dark Mode`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#36857]
## Description: 

We need to update the font's color for the `Add Feedback` when the device is in `Dark Mode`.

## Steps to Reproduce 
  1. Switch the device theme to the `Dark Mode`
  2. Launch Brave > Open `Leo`
  3. Send a query and wait for the answer
  4. Tap and hold on the response
  5. Dislike Answer > *Observe*

## Actual result: 

Hard to read `Add Feedback` when the device is in `Dark Mode`.

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/901239a4-abc2-48d6-a0ac-d8bc99740c46) | ![2](https://github.com/brave/brave-browser/assets/128532965/cc136439-1116-409d-b683-efd033ef69bf) |

## Expected result:

It must be easy to read `Add Feedback` when the device is in `Dark Mode`. 

## Reproduces how often: [Easily reproduced, Intermittent Issue]

`Easily reproduced`

## Brave Version: 

```
Brave build: 1.63 (177)
BraveCore: 1.63.177 (122.0.6261.128)
```

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? N/A

### Device details: 

```
iPhone 14 / iOS 17.4
```

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari?

**Comment by kjozwiak** [comment]
The above requires `1.63.178` or higher for `1.63.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 17.4` using the following build(s):

```
1.63.178 Chromium: 122.0.6261.128 (Official Build) unknown (64-bit) 
--- | ---
Revision | 83e0e6978dea...
OS | iOS
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/36857#issue-2189413192, ensured that `Add Feedback` was visible for `Dislike` via both `Light` & `Dark` themes as per the following:

**`Liked`**

**`Example`** | **`Example`**
----------------|----------------
![IMG_0147](https://github.com/brave/brave-browser/assets/2602313/0fbf4e6f-3ace-4048-9358-013063980305) | ![IMG_0149](https://github.com/brave/brave-browser/assets/2602313/4e69cd54-e162-489a-a5e9-6a3e8aa4bf33)

**`Disliked`**

**`Example`** | **`Example`**
----------------|----------------
![IMG_0148](https://github.com/brave/brave-browser/assets/2602313/07568be4-f33e-467c-bd2a-56dfb0eacf0f) | ![IMG_0150](https://github.com/brave/brave-browser/assets/2602313/56ab615f-2e9d-48ee-994b-be066c1beef6)
