### ISSUE TITLE
[Desktop] wallet not using latest version of Trezor Connect

### ISSUE THREAD

**Issue by nzjrs** [brave/brave-browser#36860]
Same as #10468 but for v9 vs v8

![image](https://github.com/brave/brave-browser/assets/41891/0de6f14d-900c-4f44-99ee-13ca7700a5bc)

**Comment by yrliou** [comment]
Thanks for reporting @nzjrs, we have upgrade to v9 in 1.64.x (https://github.com/brave/brave-browser/issues/35584) which is currently scheduled to be released next week on 03/19, it's currently in our [beta](https://brave.com/download-beta/) and [nightly](https://brave.com/download-nightly/) channel if you want to use it before next week's release. Apologies for the inconvenience and thanks again for reporting.
