### ISSUE TITLE
Rewards page fails to load if balance is between 0 and 1

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#36862]
## Description 

Rewards page fails to load if balance is between 0 and 1

## Steps to Reproduce

   1. With a profile that has a Rewards balance greater than 0 and less than 1,
   2. Open the Rewards page.

## Actual result:

![Screenshot_2024-03-15-16-51-18-88_82cebf612ef3f9a8762672c971adaed4](https://github.com/brave/brave-browser/assets/5995084/73b30783-828e-49af-a0ad-7b0b447eaffe)

## Version/Channel Information:

1.65

**Comment by kjozwiak** [comment]
The above requires `1.65.88` or higher for `1.65.x` verification(s) 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (x86_64) 
Revision	2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS	macOS Version 13.6.4 (Build 22G513)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.65.93 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | a6eee503125f9441360861f96cfdcccf43b6fee0
OS | Windows 11 Version 23H2 (Build 22631.3296)
```
Confirmed as below: 
- brave://rewards page displays properly when balance is 0, 1, and between 0 and 1
- rewards panel opens from BAT logo as expected

Balance = 0 | Balance 0 | 0 < Balance < 1 | Balance = 1|
------------- | ---------- | -------- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/ca701ee4-61e2-4519-91a7-88d77dccb64c)|![image](https://github.com/brave/brave-browser/assets/98358127/21e8048e-dd10-49df-b190-a7853ebdb750)|![image](https://github.com/brave/brave-browser/assets/98358127/57e6980d-0732-40ea-81bf-8be512f52a0c)|![image](https://github.com/brave/brave-browser/assets/98358127/b62d82fa-e1d7-4982-8fcf-02cc92536d14)
![image](https://github.com/brave/brave-browser/assets/98358127/f32dcdf6-210c-427b-8252-153f01dca9b4)|![image](https://github.com/brave/brave-browser/assets/98358127/24576e5c-3e9c-4c45-b650-1f0110848c1d)|![image](https://github.com/brave/brave-browser/assets/98358127/e3df470f-e343-4959-a41a-f376ec02401c)|![image](https://github.com/brave/brave-browser/assets/98358127/adc6eee4-b662-45a6-b6df-c98a452da41c)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.65.96`

When using `1.65.96 Chromium: 123.0.6312.58`, confirmed:
- brave://rewards page displays properly when balance is 0, 1, and between 0 and 1
- rewards panel opens from BAT logo as expected

Balance = 0 | 0 < Balance < 1 | Balance = 1
--- | --- | ---
![Screenshot_20240401_205514](https://github.com/brave/brave-browser/assets/38657976/ed72755e-0d55-4d9b-b167-1fc7fe38973d) | ![Screenshot_20240401_210030](https://github.com/brave/brave-browser/assets/38657976/88f3df40-8bbe-4a00-95d3-a5fdb6c628e3) | ![Screenshot_20240401_211934](https://github.com/brave/brave-browser/assets/38657976/8d7640ca-4d73-4f17-929e-a8e597cc9fd5)
![Screenshot_20240401_205540](https://github.com/brave/brave-browser/assets/38657976/3d018133-8e82-4aad-a560-0cae7625e992) | ![Screenshot_20240401_210038](https://github.com/brave/brave-browser/assets/38657976/280377cd-fcee-47c4-8450-cfdab155fc55) | ![Screenshot_20240401_211939](https://github.com/brave/brave-browser/assets/38657976/db5544e1-b89c-495c-99ec-dc5092928a91)
