### ISSUE TITLE
When "Win11 Mica title" and vertical tab strip are enabled, title bar is broken.

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#36868]
Reported https://github.com/brave/brave-browser/issues/33528#issuecomment-1969311928

## Steps to Reproduce

   1. enable win11 mica title bar brave://flags/#windows11-mica-titlebar
   2. use vertical tag strip from brave://settings
   3. there's no window controls
      1. When changing "show title bar" option doesn't solve the problem and titlebar isn't visible.

## Actual result:

https://github.com/brave/brave-browser/issues/33528#issuecomment-1969311928

## Expected result:
Titlebar or window controls should be visible and working.

## Reproduces how often: 
Always

## Version/Channel Information:
This is Win11 specific feature

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.66.59 Chromium: 123.0.6312.105 (Official Build) nightly (64-bit)
-- | --
Revision | 2714c7ac837e7b7693b1b56a82effdf57e04fe09
OS | Windows 11 Version 23H2 (Build 22631.3374)
```

Reproduced the issue in 1.64.x using STR from the description https://github.com/brave/brave-browser/issues/36868#issue-2190599104

![image](https://github.com/brave/brave-browser/assets/98358127/be85b695-bf33-477b-ad48-c0755435d608)

1. Installed 1.66.59
2. launched Brave
3. opened brave://flags in a new tab
4. enabled `#win11 mica title bar` 
5. enabled `Use vertical tabs in brave://settings/appearance

#### Confirmed title bar and window controls shown as expected when vertical tab strip is enabled 

example | example 
----- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/da17a1a2-5695-4f5a-964a-c66ad3b424f2)|![image](https://github.com/brave/brave-browser/assets/98358127/3ede105f-7801-480d-bdf3-8e43deb1a4bd)
