### ISSUE TITLE
Remove translation dropdown but not translation option

### ISSUE THREAD

**Issue by yajo** [brave/brave-browser#36896]
## Description 

Right now, the options for page translation on Brave are all or nothing. You can:
- Translate all from a lang 
- Never translate from a lang
- Have an annoying popup every time you visit a website in a lang

However, when I choose "never translate", the translation icon from the URL bar also disappears.

But what to do if I just don't want to get the annoying popup from English sites, but I still want to be able to translate them on some very specific situations where I don't understand some sentences?

One image speaks more than 1000 words, so:

![image](https://github.com/brave/brave-browser/assets/973709/a41574ee-fed4-4f13-a23e-d6de278d84ba)

## Steps to Reproduce

N/A

## Actual result:

Can't have translation icon while avoiding the translation popup.

## Expected result:
I can disable translation popup.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

1.63.174 Chromium: 122.0.6261.128 (Build oficial) unknown (64 bits) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

I just have the release channel.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

Not related.

**Comment by rebron** [comment]
@yajo If you select "Never translate" to make that icon disappear you can still use the right click menu to translate the text/page for you. Does that work for you?

**Comment by yajo** [comment]
Ah, sorry, I ddn't know that. Yes, that works.
