### ISSUE TITLE
Support some browser app for brave as autofill service

### ISSUE THREAD

**Issue by tapanmodh** [brave/brave-browser#36892]
## Description 
Autofill services are not working in some browser app. Add support for chrome, opera and edge

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 14 AP31.240322.023 release-keys
Brave build: 1.66.95
Chromium: 124.0.6367.91 (Official Build) beta (64-bit) 
```

OR

Filed follow-up issue #
---------------------------
<details>
<summary> Chrome </summary>

**STEPS:**
1. Launch `Brave Beta` > Three-dot menu > Settings
2. Addresses and more > Add address
3. Add some info > Done
4. Device settings > Passwords, passkeys & autofill
5. Preferred service > ⚙️ icon > Select `Brave - Beta` > Change
6. Launch `Chrome`
7. Go to https://rsolomakhin.github.io/autofill/
8. `Profile Autofill` section > Tap any text filed like `Name`, `Address`, `City`, etc.
9. *Verify that Brave's autofill pop-up is shown*
10. Tap Brave's autofill pop-up > *Verify that all sections in `Profile Autofill` are filled in*

**ACTUAL RESULTS:**
- Verified that `Brave` can be set as `Preferred service` for autofill in device settings
- Verified that Brave's autofill service is working in `Chrome`

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/33e7cebd-2d3f-41f2-a263-1eda18a12dd2) | ![2](https://github.com/brave/brave-browser/assets/128532965/ef01466c-e686-43f3-8de7-7d07d617bbf9) | ![3](https://github.com/brave/brave-browser/assets/128532965/f12d3894-4a8b-4d96-bf7c-3367d72c4042) | ![4](https://github.com/brave/brave-browser/assets/128532965/da29e586-b49a-43fc-8b4e-9be2d8c9094c) |
</details>
