### ISSUE TITLE
Autofill address ignore omnibox

### ISSUE THREAD

**Issue by tapanmodh** [brave/brave-browser#36890]
## Description 
Autofill should ignore incase of omnibox in other browser. It should not autofill.

## Steps to reproduce 

   1. Select Brave-Nightly app as default in autofill service
   2. Save some address into the Brave-Nightly
   3. Open opera app and tap on omnibox

## Actual result 
Saved addresses are displaying into dropdown

## Expected result
It should not try to autofill

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240322.023 release-keys
Brave build: 1.66.95
Chromium: 124.0.6367.91 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Launch `Brave Beta` `1.66.95` or newer > Three-dot menu > Settings
2. Addresses and more > Add address
3. Add some info > Done
4. Device settings > Passwords, passkeys & autofill
5. Preferred service > ⚙️ icon > Select `Brave - Beta` > Change
6. Launch `Opera`
7. Tap in the URL search bar > *Veriffy*

**ACTUAL RESULTS:**
- Verified that Brave's autofill pop-up is not shown in `Opera` when tapping in the URL search bar (omnibox)
- Verified the same in `Chrome` and `Edge` to make sure that no regression is happening

---------------------------

*Reproduced with `Brave Nightly` `1.66.20`*

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/78c6ddae-9b7f-4889-b749-c7877964667a) | ![2](https://github.com/brave/brave-browser/assets/128532965/92c21184-6bd6-4609-a9b0-c0f1c7e13fe1) |

*Verified with `Brave Beta` `1.66.95`*

|Preferred autofill service|Brave|Opera|Chrome|Edge|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/94e604f3-030d-4ad1-bef1-715e72452a53) | ![2](https://github.com/brave/brave-browser/assets/128532965/b2da4ed4-2127-4641-a0f0-6f61fd78df4c) | ![3](https://github.com/brave/brave-browser/assets/128532965/0bcd142d-1680-40e2-a1e8-b20d93ec69ed) | ![4](https://github.com/brave/brave-browser/assets/128532965/37d4741b-30d3-4280-85ed-4cab713100c3) | ![5](https://github.com/brave/brave-browser/assets/128532965/67842492-3a5f-46ea-a9a7-0213d889e0e9) |
