### ISSUE TITLE
iOS builds use "unknown" channel even when `KSChannelID` is embedded

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#36901]
## Description: 

Related to variations (https://github.com/brave/brave-browser/issues/36796, https://github.com/brave/brave-browser/issues/35593)

## Steps to Reproduce 
  1. Launch version with proper channels embedded via CI (1.66.13 for instance)
  2. Open settings > View All Version info

## Actual result:
channel is `unknown` (e.g. shows `(Official Build) unknown (64-bit)`)

## Expected result:
channel should be `nightly` (or whichever channel you're testing) (e.g. shows `(Official Build) nightly (64-bit)`)

## Reproduces how often:
Always

**Comment by kjozwiak** [comment]
The above requires `1.64.109` or higher for `1.64.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.4
- iPad Air / iPadOS 16.7.2
Brave build: 1.64 (109)
BraveCore: 1.64.109 (123.0.6312.58)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/36901#issue-2192785814
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the proper channel version name is shown

---------------------------

|iPhone|iPad|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/748244a0-befc-4bf5-a58b-792872c741f3) | ![2](https://github.com/brave/brave-browser/assets/128532965/c21b54b1-5332-4fc9-b1f2-c29a418e37b4) |
