### ISSUE TITLE
Can't found ECH in Flags setting

### ISSUE THREAD

**Issue by dipras** [brave/brave-browser#36904]
## Description 
So i want to activated the ECH(Encrypted Client Hello) in brave, but i don't find the flag. I check on other computer with same OS, it has the flag to activate it. I wonder why it's only my device that doesn't have itu

## Steps to Reproduce

   1. Install Brave browser from official website
   2. Open brave://flags/#encrypted-client-hello
   3. Search for "Encrypted"
   4. And the result, is not found what i exptexted

## Actual result:

![image](https://github.com/brave/brave-browser/assets/51155424/f5e53889-ee7a-44ac-b53b-bb10d671c140)
As you can see, i tried to search it but it not find the flex

## Expected result:
It should be show the flag to enable/disable it

## Brave version (brave://version info)
1.63.169

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by fmarier** [comment]
The flag was removed in upstream Chromium because the feature is enabled by default now: https://chromium-review.googlesource.com/c/chromium/src/+/5100554

**Comment by dipras** [comment]
> The flag was removed in upstream Chromium because the feature is enabled by default now: https://chromium-review.googlesource.com/c/chromium/src/+/5100554

![image](https://github.com/brave/brave-browser/assets/51155424/050a2343-fec4-423a-8121-2b570bbb8614)
But when i check my browser using https://cloudflare.com/ssl/encrypted-sni. Its detected the ECH is not activated

Different case with my firefox
![Screenshot_20240319_125744](https://github.com/brave/brave-browser/assets/51155424/03abdd6f-08ec-4fc9-bfd7-46e83f93841d)

**Comment by dipras** [comment]
Wait, Thing got different when i tried to launch it from terminal, now my browser have activated SNI

Hmmm this is weird

**Comment by dipras** [comment]
Wait, Thing got different when i tried to launch it from terminal, now my browser have activated SNI

Hmmm this is weird

**Comment by vanyasem** [comment]
@fmarier would it be possible to somehow add the flag back?

Russia recently started blocking all ECH-enabled connections, making numerous websites inaccessible: https://adguard-dns.io/en/blog/encrypted-client-hello-misconceptions-future.html
