### ISSUE TITLE
Viewed, dismissed, clicked and landed Confirmations controlled by estimated redemption value

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#3690]
We have view, dismiss, click and landed confirmation types but only views are shown in the UI under "Current earnings this month (Estimated)" and "Ad notifications received".

Would it make more sense to show "Current earnings this month (Estimated)" and "Ad notifications received" for any confirmation type with an estimated redemption value greater than 0.0BAT.

This would mean we can decide which confirmation types can be redeemed and if the estimated redemption value is set to 0.0BAT then the confirmation can just be used for stats.

**Comment by bsclifton** [comment]
Updated milestone after https://github.com/brave/brave-core/pull/1926 was merged

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.63.31 Chromium: 73.0.3683.75 (Official Build) beta (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523


- Verified the test plan from https://github.com/brave/brave-core/pull/1920

![image (1)](https://user-images.githubusercontent.com/38657976/55627765-98cc9500-57cc-11e9-98f1-686e91bfdd1e.png)
- If viewed ads which redirected to another hostname, sustain ads interaction will be failed and landed confirmation type will not be shown/recorded in the confirmations.json file - It's known limitation and @tmancey has filed an issue for it https://github.com/brave/brave-browser/issues/4026
- Logged issue for dismiss confirmation type https://github.com/brave/brave-browser/issues/4023
