### ISSUE TITLE
Change name from Leo to **leo ai** / **Leo AI** on iOS

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#36917]
Based on the new branding lockups, Leo has to be renamed to Leo AI on the product header.

https://www.figma.com/file/MNwi0uwXNhkAbPiJ86G4vm/%E2%9C%A8-Leo?type=design&node-id=1506%3A7892&mode=design&t=5P2WXuerWaqXpSol-1

<img width="720" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/62b2cb5b-7365-4fbf-9bd0-9975f28e3533">

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6
Brave build: 1.68 (106)
BraveCore: 1.68.106 (126.0.6478.126)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/36917#issue-2194790282 and https://github.com/brave/brave-core/pull/23852#issue-2319464092
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Leo` is renamed to `Leo AI` on Leo's UI header and in Leo's settings
- Verified the same with `Premium` and `non-Premium` accounts

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/024e1849-15bb-4895-94b3-eb4f250cbaa2) | ![2](https://github.com/brave/brave-browser/assets/128532965/1cd1e181-6ae9-4d68-aaac-44df96458ebb) | ![3]() | ![4](https://github.com/brave/brave-browser/assets/128532965/6d07f430-31de-41ce-8d6e-5d2209fd39ab) |
