### ISSUE TITLE
[Commander]: Add quick commands to normal omnibox searches

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#36912]
Currently, quick commands are only available when you open the command palette with the keyboard shortcut.

We can add quick commands to normal searches to increase the discoverability of commands & shortcuts.

1. Commands should be grouped under a `Quick commands` heading
2. The should be at the bottom of the list of results, but above the `Ask Leo` suggestion
3. It should be possible to enable/disable the suggestions via chrome://settings

Slack thread with details:
https://bravesoftware.slack.com/archives/CKNHM4RTK/p1710424627467349

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.66.83 Chromium: 124.0.6367.60 (Official Build) beta (64-bit)
-- | --
Revision | 05e51102638aec2f59c93a45527d6840c17cb704
OS | Windows 10 Version 22H2 (Build 19045.4291)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.66.94 Chromium: 124.0.6367.91 (Official Build) beta (64-bit) 
Revision	1574096f9d2bcb69c3654cb4437217121ee9600b
OS	Linux
```


### Steps:
1. installed `1.66.94`
2. launched Brave
3. opened `brave://settings/appearance` and confirmed `Quick commands` was `Enabled` by default 
4. loaded a few URLs containing added few tabs to groups and built history
5. typed `Group` in the omnibox
6. confirmed `QUICK COMMANDS >` entries related to `Group` in expanded group
7. clicked to collapse the entry
8. cleared browsing history
9. typed `Group`
10. confirmed `QUICK COMMANDS >` entries
11. toggled the above to `Disabled` / `Off`
12. typed `Group` again
13. typed `Ctrl + Space` to verify existing functionality of showing commands via `command palette`

### Confirmed appropriate `QUICK COMMANDS` entries appeared, with and without browsing history present
#### Commands are grouped under a Quick commands heading - `Group` and are shown at the bottom of the list of results, but above the `Ask Leo` suggestion
### Confirmed able to enable/disable the suggestions via brave://settings/appearance under `Show autocomplete suggestions in address bar` section
#### Confirmed `Add all tabs to new group` command and added tabs to a group

step 3 | step 4 | step 6 | step 7 | step 8 | step 9 | step 11 | step 12 | step 13a | step 13b
---------|----------|---------|---------|----------|---------|--------|-------|-------|------
![image](https://github.com/brave/brave-browser/assets/98358127/84647ae7-fd1b-472c-af03-61b9884316f4)|![image](https://github.com/brave/brave-browser/assets/98358127/407df98d-619f-4221-a58c-d4b53d379024)|![image](https://github.com/brave/brave-browser/assets/98358127/ceb203c9-2bba-4690-bf1a-7f94f5e1965c)|![image](https://github.com/brave/brave-browser/assets/98358127/38f85f80-d424-4c73-98e7-b0a8774b5fbf)|![image](https://github.com/brave/brave-browser/assets/98358127/058a947b-08b2-46db-bd72-6c9cc7cdcfd7)|![image](https://github.com/brave/brave-browser/assets/98358127/9f44fdd4-d71c-4650-bf2f-ac545225461d)|![image](https://github.com/brave/brave-browser/assets/98358127/68284b52-49a0-40f0-b1ba-f86e8bd83955)|![image](https://github.com/brave/brave-browser/assets/98358127/150cc1ae-acaf-465c-bc74-9a6442590ce6)|![image](https://github.com/brave/brave-browser/assets/98358127/7738c793-c3e6-4765-8182-e1184a9ba633)|![image](https://github.com/brave/brave-browser/assets/98358127/93e0f3df-7533-4da5-b387-7560e9070d6f)

**Comment by valynor** [comment]
Probably not a good idea to have chosen Control+Space for Quick commands in macOS as this is the system-wide keyboard shortcut for "switch input source".

**Comment by fallaciousreasoning** [comment]
Yeah, we didn't actually choose it as the shortcut, we inherited it from upstream. I'm tempted to steal the `Print basic` shortcut of `Ctrl+Shift+P` but I'm worried it'd be controversial. 

For now, you can remap the shortcut in `brave://settings/system/shortcuts` to whatever you like but we're happy to take suggestions :smile:

**Comment by valynor** [comment]
@fallaciousreasoning 

I set mine to Shift+Option+Q  (as in Q for quick commands). 
Works fine and apparently is not bound to anything by macOS - it _is_ kinda semi-dangerous though because Shift+Command+Q is "logout user" and Command+Q is "quit".
