### ISSUE TITLE
Leo - New menu design

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#36918]
Redesigned Leo's menu to account for more models and exploration of a "Store" to search, filter, etc. all the available models

https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=1040-7000&mode=design

### Desktop
![image](https://github.com/brave/brave-browser/assets/15734630/5e919e62-1576-4f1c-a939-545f306bcec5)

### Android
![image](https://github.com/brave/brave-browser/assets/15734630/c8f61af3-5f14-4079-a307-c8681b0f3b87)

**Comment by aguscruiz** [comment]
@mattmcalister I'm thinking maybe we can close this issue until we really need it. Design may evolve over the course of that time.

**Comment by mattmcalister** [comment]
@aguscruiz agreed. let's revisit in the future, but closing the issue seems like a good idea.

**Comment by aguscruiz** [comment]
Closing until we revisit the idea of a new menu

**Comment by aguscruiz** [comment]
Closing until we revisit the idea of a new menu
