### ISSUE TITLE
Leo - Header change for Android and Desktop

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#36916]
We need to update Leo's header based on the latest discussion with the team.

```[tasklist]
### Desktop
- [ ] Font size for "Leo AI" is now 16px
- [x] Title is back to being "Leo AI" no more lowercase.
- [ ] Change the settings icons to the `more-vertical` icon
```
```[tasklist]
### Android
- [ ] Font size for "Leo AI" is now using the style we have for the other app bar titles (see details)
- [x] Title is back to being "Leo AI" no more lowercase.
- [ ] Icons should be 24x24px (only on android)
- [ ] Change the settings icons to the `more-vertical` icon
```

https://www.figma.com/file/MNwi0uwXNhkAbPiJ86G4vm/%E2%9C%A8-Leo?type=design&node-id=1506-7892&mode=design&t=0urHQhYxI3ML8aoQ-0

<img width="598" alt="image" src="https://github.com/user-attachments/assets/b369e9af-bfe9-4939-81a8-2b867e218568">

**Comment by aguscruiz** [comment]
Mini update here @nullhook. I know I had set it up to be 19px font size, but I was asked to make it match the rest of the panels in desktop, which use 16px.

It's already updated in Figma

<img width="1025" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/b9fefb3c-3ede-4fba-8f7d-82f5955f00ab">

**Comment by mattmcalister** [comment]
@aguscruiz can we close this issue?
