### ISSUE TITLE
Crunchyroll.com doesn't load media  unless shields are down

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#3691]
## Description 

**Tested using Brave v0.60.48 on macOS Mojave (10.4.1)**
Anime website crunchroll.com can be loaded and navigated but streaming actual video content fails. Screen/media area stays blank and halts rendering with this in the console:
![image](https://user-images.githubusercontent.com/3299098/54217731-6cfa1000-44a9-11e9-8130-9709a1c6eae8.png)

Note that this site _does_ work when using both Beta and Dev channel
## Steps to Reproduce

   1. Visit crunchyroll.com with Shields up
   2. [Try to watch any video content on the site](https://www.crunchyroll.com/fullmetal-alchemist-brotherhood/episode-61-he-who-would-swallow-god-718229)

## Actual result:

Video does not load and playback never starts, appears blank as in the image above

## Expected result:
Media playback

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave v0.60.48 Release

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
No
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

Reports: 
https://community.brave.com/t/videos-cannot-play-on-crunchyroll-when-browser-is-activated/48297
https://community.brave.com/t/why-i-cant-watch-some-animes-on-crunchyroll-because-of-region-issues/47310/6

**Comment by kjozwiak** [comment]
CCing @bbondy as this is a pretty popular streaming website.

**Comment by Brave-Matt** [comment]
@kjozwiak @bbondy Looks like it works in v0.61.51 -- testing on macOS
![crunchyroll](https://user-images.githubusercontent.com/3299098/54446852-35879f80-4705-11e9-8252-dd092b4102ea.gif)
Only thing I notice is that you can see it hang just a tiny bit when you watch or skip to a time past where an ad would play.
