### ISSUE TITLE
Cannot play YouTube browser android
Server Indonesia


### ISSUE THREAD

**Issue by Jokopentil** [brave/brave-browser#36924]
![Screenshot_2024-03-19-20-35-35-14_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://github.com/brave/brave-browser/assets/114223791/2d4045ef-fd01-4640-8640-c9ad9f0a1fff)
![Screenshot_2024-03-19-20-35-12-68_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://github.com/brave/brave-browser/assets/114223791/3cd721cd-05e4-4929-99d7-63b027959279)

**Comment by bsclifton** [comment]
Hi thanks for reporting @Jokopentil 

Are you using a VPN? are you able to access YouTube in another browser? 
Please let us know. Thanks
