### ISSUE TITLE
Dutch Language launch iOS

### ISSUE THREAD

**Issue by AndyAnds265** [brave/brave-browser#36939]
## Description: 
We would like to add the Dutch language to our end of March Beta build and then rollout with the following release. To be specific, this entails adding the `nl` locale code. We are looking to use the general `nl` code not one attached to any country. 

The localization is being worked on right now and it should be done within a week. I'm adding this ticket so that it can be slated in for the next iOS grooming discussion.

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari?

**Comment by kjozwiak** [comment]
The above requires `1.65.110` or higher for `1.65.x` verification 👍

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.5
Brave build: 1.65 (114)
BraveCore: 1.65.114 (124.0.6367.60)
```

Filed follow-up issue #
---------------------------

**STEPS:**
1. Set `Dutch`language in device settings
2. Launch Brave 
3. *Verify*

**ACTUAL RESULTS:**
- Verified that Brave UI is translated to `Dutch` language

---------------------------

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/e1d9f545-a0a4-4765-908c-6a0f053925ae) | ![2](https://github.com/brave/brave-browser/assets/128532965/ff5c6495-dcb7-49c6-ac8e-a285db59ea7e) | ![3](https://github.com/brave/brave-browser/assets/128532965/d015b35e-5223-476d-8c96-7868dbad6761) | ![4](https://github.com/brave/brave-browser/assets/128532965/90632bd6-b2b6-45ef-94bb-09a0e56926c0) | ![5](https://github.com/brave/brave-browser/assets/128532965/e44837a1-6721-4ee2-a86d-98609835233d) |
| ![1]() | ![2]() | ![3]() | ![4]() | ![5]() |
| ![1]() | ![2]() | ![3]() | ![4]() | ![5]() |
| ![1]() | ![2]() | ![3]() | ![4]() | ![5]() |
| ![1]() | ![2]() | ![3]() | ![4]() | ![5]() |
| ![1]() | ![2]() | ![3]() | ![4]() | ![5]() |
| ![1]() | ![2]() | ![3]() | ![4]() | ![5]() |
| ![1]() | ![2]() | ![3]() | ![4]() | ![5]() |
| ![1]() | ![2]() | ![3]() | ![4]() | ![5]() |
| ![1]() | ![2]() | ![3]() | ![4]() | ![5]() |

**Comment by hffvld** [comment]
Verified on `iPad Air` using version(s):
```
Device/OS: iPad Air / iPadOS 16.7.2
Brave build: 1.65 (114)
BraveCore: 1.65.114 (124.0.6367.60)
```
---------------------------

**STEPS:**
1. Set `Dutch`language in device settings
2. Launch Brave 
3. *Verify*

**ACTUAL RESULTS:**
- Verified that Brave UI is translated to `Dutch` language

---------------------------

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/ad5c2f67-8526-41c4-915c-7ba9674ce448) | ![2](https://github.com/brave/brave-browser/assets/128532965/cdda2876-7bbb-48f6-9645-bc2ba6df6f26) | ![3](https://github.com/brave/brave-browser/assets/128532965/fb6ff78b-042d-4383-9d0e-f445ce7f2f77) | ![4](https://github.com/brave/brave-browser/assets/128532965/875b6c6b-8d4e-4393-9214-f68ddbc658c3) | ![5](https://github.com/brave/brave-browser/assets/128532965/d6a67fab-c982-4f68-9459-23d250ad6912) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/86c6c0f4-6674-4f40-a5aa-40aa58e6dadc) | ![2](https://github.com/brave/brave-browser/assets/128532965/b73c1269-7951-458a-9f7f-3bdab4dbb5cb) | ![3](https://github.com/brave/brave-browser/assets/128532965/b640d040-65c9-449d-8331-cbc531fa835c) | ![4](https://github.com/brave/brave-browser/assets/128532965/dab73db7-8d17-4ad4-8415-fbc1b2d3452e) | ![5](https://github.com/brave/brave-browser/assets/128532965/ca7344b1-08f6-4c66-8dcc-da3c986fd78c) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/7bc94752-c6ed-44d4-8092-74f7c74ffeac) | ![2](https://github.com/brave/brave-browser/assets/128532965/c05ceb40-b213-40c4-bab0-efd1328bfef4) | ![3](https://github.com/brave/brave-browser/assets/128532965/c4efeeb3-330c-448f-b87c-f353c5504f6d) | ![4](https://github.com/brave/brave-browser/assets/128532965/b7d47a15-4f61-497f-afc7-dead6d06333b) | ![5](https://github.com/brave/brave-browser/assets/128532965/fe394950-3e91-421d-88ef-456e5e0867bc) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/8bf66f49-1005-4db0-9df3-4a61b6686ee5) | ![2](https://github.com/brave/brave-browser/assets/128532965/f1b9e715-5c40-459a-a3e3-07816bb937b0) | ![3](https://github.com/brave/brave-browser/assets/128532965/ccae6929-8e1c-4d92-9182-80ca8b5c39fc) | ![4](https://github.com/brave/brave-browser/assets/128532965/f5b6506f-eef8-475a-bb8c-db0db4e0dcf4) | ![5](https://github.com/brave/brave-browser/assets/128532965/74df2bb4-a617-42cf-a7dc-a376bd096098) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/8845a3de-8735-4716-aae6-80f11917f599) | ![2](https://github.com/brave/brave-browser/assets/128532965/49d68518-c739-4afc-b1ec-0d662fecf754) | ![3](https://github.com/brave/brave-browser/assets/128532965/37eb8a28-46f8-4ddb-9d2a-50cd76d75ab9) | ![4](https://github.com/brave/brave-browser/assets/128532965/3d1e0415-8ce2-4318-b235-d96e00cbc454) | ![5](https://github.com/brave/brave-browser/assets/128532965/f7fa8fe2-9ab8-429c-88f3-051a6ece83d6) |
