### ISSUE TITLE
[Wallet] Do not wait for pending add-chain requests when initializing wallet

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#36935]
## Description 

Currently, when initializing the brave wallet ui, we wait for pending add-chain requests to be checked before rendering. We should check for the requests after the wallet is initialized. We should also remove the need to dispatch a navigation action when a request is detected.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.80 Chromium: 124.0.6367.29 (Official Build) beta (64-bit)
-- | --
Revision | 2d822a1940c9159c1f307cd1c0a8f58fcfb50fe0
OS | Windows 11 Version 23H2 (Build 22631.3447)

- Verified steps from [brave/brave-core#22677](https://github.com/brave/brave-core/pull/22677)
- Verified adding a chain via `https://chainlist.org/` continues to work without any regression

https://github.com/brave/brave-browser/assets/17010094/ca78b727-e898-4755-a5cb-5f206858471a
