### ISSUE TITLE
Remove "Automatic .onion redirect" feature

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#36933]
The _Automatically redirect .onion sites_ feature has been a common source of complaints from users who turned it on and then forgot about it.

It also creates a potential privacy leak for which there is no easy fix.

Therefore, I think we should remove this potentially dangerous feature entirely [like the Tor Browser](https://blog.torproject.org/new-release-tor-browser-13012/).

## Design 
<img width="789" alt="Screenshot 2024-03-19 at 5 09 47 PM" src="https://github.com/brave/brave-browser/assets/5951041/c7271480-0854-4e36-91f4-b8cdff48e561">

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```

```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave	1.66.90 Chromium: 124.0.6367.82 (Official Build) beta (64-bit) 
Revision	803a4c629341791205b744969c48b8da9f2cfa4d
OS	Linux
```


## Case 1:  "Automatic .onion redirect" Preference removed in `brave://settings/privacy` - `PASSED`

<details>

#### Confirmed "Automatic .onion redirect" option is removed in `Tor windows` seciton and no longer shown

`1.65.123 ` | `1.66.90
----------|----------
![image](https://github.com/brave/brave-browser/assets/98358127/a90b9f26-f6e7-4038-8081-98270cb2d3d8)
![image](https://github.com/brave/brave-browser/assets/98358127/5987f3a7-1745-40b5-b93a-e658beb6037b)


</details>


## Case 2: URL-bar behavior - `PASSED`
<details>


### Steps:
1. installed `1.66.59`
2. launched Brave
3. loaded `nytimes.com`
4. clicked on the `Tor` icon/button in the URL bar
5. confirmed `Private Window with Tor` loaded `https://www.nytimesn7cgmftshazwhfgzm37qxb44r64ytbb2dj3x62d2lljsciiyd.onion/` 


example | example
----------|----------
![image](https://github.com/brave/brave-browser/assets/98358127/064e4329-f6e4-47d0-a78a-76f14d8f675d)|![image](https://github.com/brave/brave-browser/assets/98358127/23c38884-428d-4320-bdc6-40e197008e89)

</details>

## Case 3: Upgrade scenario - `Pending`
<details>

### Steps:
1. installed `1.65.123`
2. launched Brave
3. loaded `https://www.theguardian.com/us`
4. clicked on the `Tor` icon/button in the URL bar
5. confirmed I landed on `hhttps://www.guardian2zotagl6tmjucg3lrhxdk4dw3lhbqnkvvkywawy3oqfoprid.onion/us`
6. shut down Brave
7. upgraded to `1.66.90` (renamed `Brave-Browser` profile folder --> `Brave-Browser-Beta`
8. launched `1.66.90`
9. opened `brave://settings/privacy`
10. confirmed no `Automatically redirect .onion sites` preference
11. loaded `https://www.theguardian.com/us`.com`
12. clicked on the `Tor` button

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.66.91 Chromium: 124.0.6367.91 (Official Build) beta (x86_64)
-- | --
Revision | 5c30ebba7e5e93df8fbf633585986e5e907d07e8
OS | macOS Version 11.7.10 (Build 20G1427)
```
