### ISSUE TITLE
[BUG]: sync broken in arch no solutiions work

### ISSUE THREAD

**Issue by its-19818942118** [brave/brave-browser#36945]
## Description 

lots of issue regarding sync. i am using endeavour os with kde plasma and hyprland works in kde but breaks in hyprland pls fix it. tried every solution nothing works out

## Steps to Reproduce

   1. sync
   2. logout
   3. relogin sync gone

## Expected result:

1. sync
2. logout
3. relogin. data gone

## Reproduces how often: 

1. sync login
2. logout
3. data present

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- everychannel possible 
- Can you reproduce this issue with the beta channel?
- yes 
- Can you reproduce this issue with the nightly channel?
- yes 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 
- no

**Comment by its-19818942118** [comment]
No update

**Comment by bsclifton** [comment]
Possibly related

**Comment by its-19818942118** [comment]
Aight
