### ISSUE TITLE
Add close button to bookmarks/readinglist/playlist panel's header 

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#36943]
## Description
Add a close, "x" button to side panels to allow users a more visible way to close a side panel.
The close button should be added to the bookmarks, reading list, and playlist side panels.
Panel should be closed after close button pressed.

## Design
<img width="560" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/4dc1ba22-1346-44f0-8acf-bf1e82a66fc4">

## Other information
Figma link: `https://www.figma.com/file/Fbtxfv2ATGlfH7nPXiWAbR/Browser-Sidebar?type=design&node-id=110-7628&mode=design`

Related issues: 
https://github.com/brave/brave-browser/issues/36202
https://github.com/brave/brave-browser/issues/35935

**Comment by simonhong** [comment]
In this issue, leo panel's close button is not added.
I'll let it done via https://github.com/brave/brave-browser/issues/36202
AFAIK, leo webui is shared between desktop and android. so it could be handled differently.

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

```
Brave | 1.66.81 Chromium: 124.0.6367.60 (Official Build) beta (64-bit)
-- | --
Revision | ee44f88609d4a72c5d0cb3305c5f340b6203a917
OS | Windows 10 Version 22H2 (Build 19045.4291)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.66.90 Chromium: 124.0.6367.82 (Official Build) beta (64-bit) 
Revision	803a4c629341791205b744969c48b8da9f2cfa4d
OS	Linux
```


### Steps:
1. installed `1.66.90`
2. launched Brave
3. clicked on `Bookmarks` and confirmed `Bookmarks` panel loaded, with a `Close` `X` icon
4. confirmed clicking it closed the panel
5. clicked on `Reading List` and confirmed `Reading List` panel loaded, with a `Close` `X` icon
6. confirmed clicking it closed the panel
7. clicked on `Playlist` and confirmed `Playlist` panel loaded, with a `Close` `X` icon

### Confirmed I could open and close panels, the latter via the new `X` `Close` widget/icon
### Confirmed tooltip of `Close` on icon
### Confirmed existing functionality of toggling open/close, Bookmarks, Reading list & Playlist via sidebar and clicking icons on the sidebar working as expected

#### Bookmarks 

Dark theme | Light theme
------- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/0732aa50-a3f2-4b6d-b51c-8587e29d0883)|![image](https://github.com/brave/brave-browser/assets/98358127/f09245ca-647a-4b32-ab73-b3394f4386f6)

#### Reading List

Dark theme | Light theme
------- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/763deac1-aff0-49f5-996b-d623df652403)|![image](https://github.com/brave/brave-browser/assets/98358127/41130d8f-cbba-4044-8640-16d99982231a)

#### Playlist

Dark theme | Light theme
------- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/ad58e3fd-fe19-4a72-9e09-28a6f0ee26c7)|![image](https://github.com/brave/brave-browser/assets/98358127/6d09bf17-547f-49bf-aa4c-d2a05ee72135)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.66.91 Chromium: 124.0.6367.91 (Official Build) beta (x86_64)
-- | --
Revision | 5c30ebba7e5e93df8fbf633585986e5e907d07e8
OS | macOS Version 11.7.10 (Build 20G1427)
```



### Steps:
1. installed `1.66.91`
2. launched Brave
3. clicked on `Bookmarks` and confirmed `Bookmarks` panel loaded, with a `Close` `X` icon
4. confirmed clicking it closed the panel
5. clicked on `Reading List` and confirmed `Reading List` panel loaded, with a `Close` `X` icon
6. confirmed clicking it closed the panel
7. clicked on `Playlist` and confirmed `Playlist` panel loaded, with a `Close` `X` icon

### Confirmed I could open and close panels, the latter via the new `X` `Close` widget/icon

### Confirmed tooltip of `Close` on icon

### Bookmarks - `PENDING`

`Dark` | `Light`
-------|-------


### Reading List - `PENDING`

`Dark` | `Light`
-------|-------


### Playlist - `PENDING`

`Dark` | `Light`
-------|-------
