### ISSUE TITLE
Random language used for Leo opt-in and chat screens [iOS 15]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#36941]
## Description: 
Opt-in and chat screens are displaying foreign languages even though EN (US) is set for device. 

## Steps to Reproduce 
  1. Set language/Region to English/US
  2. Install Brave 1.63.179
  3. Activate Leo

## Actual result: 
Example | Example | Example
-|-|-
![IMG_0367 2](https://github.com/brave/brave-browser/assets/17885425/e8025e37-f45c-4f7f-910b-5ed887de2e55) | ![IMG_0368 2](https://github.com/brave/brave-browser/assets/17885425/bc21bbaa-5740-4e17-a0e6-e9b8a2fb80cc) | ![IMG_0371](https://github.com/brave/brave-browser/assets/17885425/3853dd77-0fc8-4aa9-a2af-a9c4d59901d5)

## Expected result:
Use device language

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

## Brave Version: 1.63.179

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? TBD
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 
iPhone, iPad | iOS 15.6.1, iOS 15.5

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari?

**Comment by kjozwiak** [comment]
Closing as the above has been uplifted into `1.63.x`, `1.64.x`, 1.65.x` via https://github.com/brave/brave-core/pull/22683, https://github.com/brave/brave-core/pull/22684 & https://github.com/brave/brave-core/pull/22685. Adding the `QA/Test-All-Platforms` as we'll need to double check `iOS 15`, `iOS 16` & `iOS 17` to ensure `Leo` strings are appearing in `English` when `English` is selected as the default and ensuring that switching languages also works.

**Comment by Uni-verse** [comment]
Verified on `iPad (9th Gen)` running `iOS 15.6.1` using version `1.63.180`

- Ensured that Leo screens are displaying the correct language based on device settings (English is used correctly). 
- Ensured correct language is shown for Leo settings menu and `Ask Leo` in address bar.

Example | Example | Example | Example
-|-|-|-
![IMG_0348 2](https://github.com/brave/brave-browser/assets/17885425/fc5082e4-4042-4288-81cb-52aa7ec4d4c7) | ![IMG_0349](https://github.com/brave/brave-browser/assets/17885425/81482b88-aac9-484f-bb2e-54513fea4ab2) | ![IMG_0350 2](https://github.com/brave/brave-browser/assets/17885425/efb55fca-44c0-4b79-b596-b593c36951c7) | ![IMG_0351 2](https://github.com/brave/brave-browser/assets/17885425/97de5c36-6326-465d-bd0a-35c0cfb9f582) 
![IMG_0352](https://github.com/brave/brave-browser/assets/17885425/0ff5c4ae-3634-4fea-9328-93bd052a2865) | ![IMG_0353](https://github.com/brave/brave-browser/assets/17885425/48bba6c6-2c8e-4fc1-8a53-f74d20891b50) | ![IMG_0354](https://github.com/brave/brave-browser/assets/17885425/2fb86f9c-166f-4a5e-bd7e-2b8838f197af) | ![IMG_0355](https://github.com/brave/brave-browser/assets/17885425/328f4652-9187-43f3-bbbe-8deeb8986d89)

- Ensured that non-English languages are used correctly (French in this case).

Example | Example | Example | Example
-|-|-|-
![IMG_0357 3](https://github.com/brave/brave-browser/assets/17885425/990df5d8-7bd9-40ef-801d-b3a200e9c689) | ![IMG_0358 3](https://github.com/brave/brave-browser/assets/17885425/bd51978a-bced-414d-aff0-84a0f9fb1bb4) | ![IMG_0359 3](https://github.com/brave/brave-browser/assets/17885425/7108e610-8770-4ac9-9136-b4c265d335ea) | ![IMG_0360 3](https://github.com/brave/brave-browser/assets/17885425/7ed0ce9d-bd00-4545-9f30-6e45179e7699)
![IMG_0361 3](https://github.com/brave/brave-browser/assets/17885425/ffaa140b-1a53-40b2-a30f-54b8f03bdaff) | ![IMG_0362 3](https://github.com/brave/brave-browser/assets/17885425/2b724a9a-047b-47a5-b3e1-e80bf2dcf708) | ![IMG_0363 3](https://github.com/brave/brave-browser/assets/17885425/a50ac233-b465-49db-96ec-18e25a3d59f6) | ![IMG_0364 3](https://github.com/brave/brave-browser/assets/17885425/c737027e-ede2-4258-aae9-57d9f775a052)

**Comment by Uni-verse** [comment]
Verified on `iPhone XR` running `iOS 15.5` using version `1.63.180`

- Ensured that Leo screens are displaying the correct language based on device settings (English is used correctly).
- Ensured correct language is shown for Leo settings menu and Ask Leo in address bar.

Example | Example | Example | Example
-|-|-|-
![IMG_0373 2](https://github.com/brave/brave-browser/assets/17885425/615218fa-ad00-45b5-ab4f-872ae0fe55bb) | ![IMG_0374 2](https://github.com/brave/brave-browser/assets/17885425/99be77f0-7292-4647-a05b-bf8249fadd4a) | ![IMG_0375 2](https://github.com/brave/brave-browser/assets/17885425/4d705c48-1be4-48f2-b97a-90cbf345fa7d) | ![IMG_0376](https://github.com/brave/brave-browser/assets/17885425/5ddab47f-45b0-4c73-958c-fe4bcaa4e0bc)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6s+` running `` using the following build(s):

```

1.63.180 Chromium: 122.0.6261.128 (Official Build)unknown (64-bit)
-- | --
Revision | 9f47523f9c3a...
OS | iOS
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/36941#issue-2196245533, went through the following:

**`English (no other languages within the list)`**

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|-----------------
![IMG_0269](https://github.com/brave/brave-browser/assets/2602313/76ddbb09-b3a5-4960-9adc-f040748b4bdd) | ![IMG_0270](https://github.com/brave/brave-browser/assets/2602313/a3d64e05-31b5-4fd9-be58-85374fdefaa7) | ![IMG_0271](https://github.com/brave/brave-browser/assets/2602313/63fc06bb-7199-42fd-bada-21ba66646151)

**`English (other languages listed)`**

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|-----------------
![IMG_0275](https://github.com/brave/brave-browser/assets/2602313/d9856d37-4545-4831-9e80-18f2263c381a) | ![IMG_0276](https://github.com/brave/brave-browser/assets/2602313/1709ca94-54f1-4216-b23f-5c65f7bae428) | ![IMG_0277](https://github.com/brave/brave-browser/assets/2602313/d1d349c0-6a23-4a25-ab01-7a4dd4180dbe)

**`German`**

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|-----------------
![IMG_0272](https://github.com/brave/brave-browser/assets/2602313/6eaf4d6e-24cb-423f-8db5-0174dbe2e84a) | ![IMG_0273](https://github.com/brave/brave-browser/assets/2602313/444a4559-eb60-42fe-b6ea-c057f2be5af9) | ![IMG_0274](https://github.com/brave/brave-browser/assets/2602313/57c5feb9-a695-4d08-b0f4-4f084aa4537e)

**Comment by hffvld** [comment]
Verified on `iPad Air` using version(s):
```
Device/OS: iPad Air / iPadOS 16.7.2
Brave build: 1.63 (180)
BraveCore: 1.63.180 (122.0.6261.128)
```
---------------------------

**ACTUAL RESULTS:**
- Verified that `Leo's` language is set to the same one that is set in the device settings
- Verified the same with `English`, `Russian`, `Spanish` and `Japanese` language

---------------------------

|English|Russian|Spanish|Japanese|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/565e6935-11fd-4c25-81ee-ee56e548e2c9) | ![2](https://github.com/brave/brave-browser/assets/128532965/c75818c7-3029-425b-a150-d145a90debfe) | ![3](https://github.com/brave/brave-browser/assets/128532965/920a8a53-3306-43dc-aa0d-82b8df7c4279) | ![4](https://github.com/brave/brave-browser/assets/128532965/b5ef7a34-8aad-48a0-8841-0901e573dee9) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/00b02cec-758a-4a45-9f69-367830999868) | ![2](https://github.com/brave/brave-browser/assets/128532965/ccb4df2d-a1ca-48e9-a67d-d0e5178eb509) | ![3](https://github.com/brave/brave-browser/assets/128532965/60c2de15-840e-4225-a643-4dbe951fc949) | ![4](https://github.com/brave/brave-browser/assets/128532965/5b4fd4bb-0082-440e-91ff-05e746d5acba) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/0e3cbbd5-c8e1-4ad0-93e0-0439a4ef0f81) | ![2](https://github.com/brave/brave-browser/assets/128532965/3b5b5dc2-321d-4126-800c-bf7f9169022e) | ![3](https://github.com/brave/brave-browser/assets/128532965/02f825a2-0ea8-4fcc-bb40-58c4d591c1cd) | ![4](https://github.com/brave/brave-browser/assets/128532965/93bfb6f5-46a7-4a72-bb5a-a92eba45eb1b) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/8c6ff202-d2db-4513-b2d1-14f734a29add) | ![2](https://github.com/brave/brave-browser/assets/128532965/6d8a7e2e-4d6b-4ab9-919d-71cce0c29925) | ![3](https://github.com/brave/brave-browser/assets/128532965/2e31ca58-fe23-4f2b-bb67-97200f23e7e1) | ![4](https://github.com/brave/brave-browser/assets/128532965/ea33e8e5-45db-40a5-88c4-ca6057a38938) |
