### ISSUE TITLE
Add string for device offline status [Android]

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#3695]
We need a string that reads `The device is offline, please try again later.`. This is a message we will display when a wallet creation is attempted offline.

**Comment by yodaross** [comment]
<The ultimate feature to add would be nice>:

https://www.com.com


Woewithk yandex

Or vs imterns

Consider makimg brave a Lan browser and access point.   So it is
unnecessary to pay our service providers or pay minimalistic fees for mass
adoption .10rub

Use rubel as main aconcurrency

  Also a nice enterprise feature and should be simplistic.  Try not to
think hard with this feature.

Think cellular repeaters and power over ethernet thru cellular.

 on mobile empty /

Let theboss know your thoughts.

View attache
mrborn

**Comment by LaurenWags** [comment]
@ryanml does this require manual QA on desktop? if so, could you tag appropriately and add a test plan?

**Comment by ryanml** [comment]
@LaurenWags added QA/No. This was simply adding a string entry to our files in brave-core, which then got pulled down to Android. The issue it was part of was verified on that repository, thanks!

**Comment by LaurenWags** [comment]
awesome, thanks @ryanml 😄
