### ISSUE TITLE
[Android] Add red badge on BAT icon if there's an Terms of Service update notice

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#36955]
- It is OK if it does not show for first 7 days after Brave installation, since all badges are hidden
- It should show after that
- Uplift into 1.65.x

**Comment by kjozwiak** [comment]
The above requires `1.65.110` or higher for `1.65.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_165.112`

Confirmed using `1.65.112` and below steps showed persistent notification for ToS update.

1. Install 1.65.112
2. Set staging flags in QA Prefs, relaunch
3. Join rewards
4. Close browser
5. Connect to Charles Proxy, simulate ToS update via a rewrite rule
6. Relaunch browser ---> do not see notification
7. Wait a bit (~5-10 min), relaunch again, now notification displays

Example | Example
--- | ---
![Screenshot_20240416_141812_Brave](https://github.com/brave/brave-browser/assets/38657976/6ec65691-79a7-4ffc-a1f9-a0e5d6929387) | ![Screenshot_20240416_141859_Brave](https://github.com/brave/brave-browser/assets/38657976/20be9b76-9e78-45e3-83fb-b1032f379eba)


8. Confirmed notification goes away once ToS update is accepted
9. Confirmed notification does not come back once browser is relaunched after accepting ToS update

Example | Example
--- | ---
![Screenshot_20240416_141955_Brave](https://github.com/brave/brave-browser/assets/38657976/2c9f90f8-f757-42e7-955f-c5a8dd289be2) | ![Screenshot_20240416_142003_Brave](https://github.com/brave/brave-browser/assets/38657976/0e294e68-a018-49c9-bf4d-f20fe1ad1200)




Encountered https://github.com/brave/brave-browser/issues/37481 while testing
