### ISSUE TITLE
Add color to the Solana icon in Rewards panel 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#36953]
## Description

On desktop, when connected to Solana, the Solana icon in the Rewards panel and on the brave://rewards page does not have color. We should add color to it.

**Comment by mitras-git** [comment]
I noticed this issue was marked as a "good first issue" after being assigned to someone. I'm quite eager to make my first contribution. I understand this issue is currently assigned, @zenparsing just wanted to know if you are still working on this issue.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.66.56 Chromium: 123.0.6312.86 (Official Build) nightly (x86_64) 
Revision	029ff6b82a6cfb16bde7c6d7ab560321a023cb8b
OS	macOS Version 13.6.6 (Build 22G630)
```
