### ISSUE TITLE
Incorrect commands listed/shown for command palette 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#36965]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/36600.  Shortcuts below are added via `brave://settings/system/shortcuts` but are not listed in the quick commands list via URL bar.  It looks shortcuts with `Ctrl+Alt` combination may not be shown/listed. However the commands still work.
 
`Name current group`, `New tab in group`, `Ungroup current tab group`, `Close group`, `Close ungrouped tabs` & `Bring tabs from other windows` 
## Steps to Reproduce

1. Installed 1.65.86 
2. launched Brave
3. opened few tabs
4. opened brave://settings/system/shortcuts in a new tab
5. added a keyboard shortcut for each of the new command listed 
6. ran the same command from the command palette (Ctrl + Space)

## Actual result:

incorrect commands are shown/listed

`Name current group` - `Ctrl + N`
`New tab in group` - `Ctrl + T`
 `Ungroup current tab group` - `Ctrl +Shift + U`
 `Close group` - `Ctrl + G`
 `Close ungrouped tabs` - `Ctrl +Shift + T`
 `Bring tabs from other windows` -`Ctrl + B` 

`Name current group`| `New tab in group`| `Ungroup current tab group`|`Close group` | `Close ungrouped tabs` | `Bring tabs from other windows` 
------ | ------ | ------ | ------ | ------ | ------
![image](https://github.com/brave/brave-browser/assets/98358127/d9a32d14-0f49-409b-b2db-262e95700344)|![image](https://github.com/brave/brave-browser/assets/98358127/b53a399a-86de-41ac-b528-b47b0460f78a)|![image](https://github.com/brave/brave-browser/assets/98358127/c459a66a-e9e2-4842-8880-2640f8135095)|![image](https://github.com/brave/brave-browser/assets/98358127/4272ff5d-7454-46f3-a429-14abb6bc81e2)|![image](https://github.com/brave/brave-browser/assets/98358127/03d2976c-09f6-41b1-88b1-51047be94930)|![image](https://github.com/brave/brave-browser/assets/98358127/5537705f-64d1-4f41-8037-3043978ec078)

## Expected result:
Name current group - Ctrl + Alt + N
`New tab in group` - `Ctrl + Alt+ T`
`Ungroup current tab group` - `Ctrl + Alt + Shift + U`
`Close group` - `Ctrl + Alt + G`
`Close ungrouped tabs` - `Ctrl + Alt + Shift + T`
`Bring tabs from other windows` - `Ctrl + Alt + B`

 
## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.65.87 Chromium: 123.0.6312.46 (Official Build) beta (64-bit)
-- | --
Revision | 2babfcf82ebba4c5dc0146d2ca66229ffd3ac02d
OS | Windows 11 Version 23H2 (Build 22631.3296)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@fallaciousreasoning @rebron 
@brave/qa-team

**Comment by LaurenWags** [comment]
Added `OS/Windows` and `OS/Linux` labels as this was encountered by @MadhaviSeelam on Windows and I can reproduce on Linux with 1.65.x.

Did not reproduce on macOS when I was testing original issue (https://github.com/brave/brave-browser/issues/36600) on 1.65.x.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.66.83 Chromium: 124.0.6367.60 (Official Build) beta (64-bit)
-- | --
Revision | 05e51102638aec2f59c93a45527d6840c17cb704
OS | Windows 11 Version 23H2 (Build 22631.3447)
```

1. Installed 1.65.86
2. launched Brave
3. opened few tabs
4. opened brave://settings/system/shortcuts in a new tab
5. added a keyboard shortcut for below command 
    - `Add new profile` - `Ctrl+Alt+V`
6. searched for `Add new profile` from the command palette (Ctrl + Space)
7. confirmed `Add new profile` - `Ctrl + Alt + V` listed
8. confirmed `Ctrl + Alt + V` is the only shortcut for the command

example | example | example 
----- | ----- | -------
![image](https://github.com/brave/brave-browser/assets/98358127/82c690f3-fc0f-435d-a086-0c507b99b9d4)|![image](https://github.com/brave/brave-browser/assets/98358127/2c466b64-d2a5-463c-93d4-e17526fbb17e)|![image](https://github.com/brave/brave-browser/assets/98358127/6db62332-82fd-4ae6-8a55-82618fa39c63)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave	1.66.90 Chromium: 124.0.6367.82 (Official Build) beta (64-bit) 
Revision	803a4c629341791205b744969c48b8da9f2cfa4d
OS	Linux
```

1. Installed 1.66.90
2. launched Brave
3. opened few tabs
4. opened brave://settings/system/shortcuts in a new tab


Case 1:   `Add new profile` - `Ctrl+Alt+V` - `PASSED`
<details>

-  added a keyboard shortcut for below command in `brave://settings/system/shortcuts`
    - `Add new profile` - `Ctrl+Alt+V`
- searched for `Add new profile` from the command palette (Ctrl + Space)
- confirmed `Add new profile` - `Ctrl + Alt + V` listed
- confirmed `Ctrl + Alt + V` is the only shortcut for the command

example | example | example 
----- | ----- | -------

</details>

Case 2: `New tab in group` - `Alt+ Shift + D` - `PASSED`
<details>

- added a keyboard shortcut for below command in `brave://settings/system/shortcuts`
   - `New tab in group` - `Alt+ Shift + D`
- confirmed able to add a tab with keyboard shortcut (`Alt+ Shift + D`)
- searched for `New tab in group` from the command palette (Ctrl + Space)
- confirmed `New tab in group` - `Alt+ Shift + D` listed
- confirmed ``Alt+ Shift + D`` is the only shortcut for the command able to add the tab


</details>

Case 3: `Name this group` - `Alt+ Shift + G` - `PASSED`
<details>

- opened few tabs and clicked `Add new tab group` >> `New group` from context menu
- added a keyboard shortcut for below command in `brave://settings/system/shortcuts`
   - `Name this group` - `Alt+ Shift + G`
- confirmed able to name the group with keyboard shortcut (`Alt+ Shift + G`)
- searched for `Name this group` - `Alt+ Shift + G` from the command palette (Ctrl + Space)
- confirmed `Name this group` - `Alt+ Shift + G` listed
- confirmed `Alt+ Shift + G` is the only shortcut for the command able to name the group 


</details>

Case 4:  `Ungroup current tab group` - `Ctrl + Alt + Shift + U` - `PASSED`
<details>

- continued from Case 3 
  - Tabs are added to group and name the group (news, cars)
- added a keyboard shortcut for below command in `brave://settings/system/shortcuts`
   - `Ungroup current tab group` - `Ctrl + Alt + Shift + U`
- confirmed able to ungroup current tab group with keyboard shortcut (`Ctrl + Alt + Shift + U`)
- searched for `Ungroup current tab group` - `Ctrl + Alt + Shift + U` from the command palette (Ctrl + Space)
- confirmed `Ungroup current tab group` - `Ctrl + Alt + Shift + U` listed
- confirmed `Ctrl + Alt + Shift + U` is the only shortcut for the command able to Ungroup current tab group


</details>

Case 5: `Close ungrouped tabs` - `Ctrl + Alt + Shift + T` - `PASSED`
<details>

- continued from Case 4 
  - Tabs are ungrouped
- added a keyboard shortcut for below command in `brave://settings/system/shortcuts`
   - `Close ungrouped tabs` - `Ctrl + Alt + Shift + T`
- confirmed able to ungroup current tab group with keyboard shortcut (`Ctrl + Alt + Shift + T`)
- searched for `Close ungrouped tabs` - `Ctrl + Alt + Shift + T` from the command palette (Ctrl + Space)
- confirmed `Close ungrouped tabs` - `Ctrl + Alt + Shift + T` listed
- confirmed `Ctrl + Alt + Shift + T` is the only shortcut for the command able to Close ungrouped tabs



</details>

Case 6:  `Close group` - `Alt+ Shift + C` - `PASSED`
<details>

- opened few tabs and added to groups 
- added a keyboard shortcut for below command in `brave://settings/system/shortcuts`
   - `Close group` - `Alt+ Shift + C`
- confirmed able to close group with keyboard shortcut (`Alt+ Shift + C`)
- searched for `Close group` - `Alt+ Shift + C` from the command palette (Ctrl + Space)
- confirmed `Close group` - `Alt+ Shift + C` listed
- confirmed `Alt+ Shift + C` is the only shortcut for the command able to Close group


</details>

Case 7:  `Bring tabs from other windows` - `Ctrl + Alt + B` - `PASSED`
<details>

- continued from Case 6
  - few tabs opened in a window
- opened a new window and opened few tabs
- added a keyboard shortcut for below command in `brave://settings/system/shortcuts`
   - `Bring tabs from other windows` - `Ctrl + Alt + B`
- confirmed able to Bring tabs from other windows with keyboard shortcut (`Ctrl + Alt + B`)
- searched for `Bring tabs from other windows` - `Ctrl + Alt + B` from the command palette (Ctrl + Space)
- confirmed `Bring tabs from other windows` - `Ctrl + Alt + B` listed
- confirmed `Ctrl + Alt + B` is the only shortcut for the command able to Bring tabs from other windows


</details>
