### ISSUE TITLE
Add access to developer menus & logs in release & beta channels

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#36961]
## Description: 

Right now the debug/developer menu in settings is only visible in Nightly channel builds, however now that we are part of the brave-core train there aren't builds that exist in Nightly that may exist in other channels so we need a way to enable logs & other debug related menu options in other channels (possibly behind some sort of password)

`AppConstants.buildChannel.isPublic` should be removed and code should be replaced so that builds only differ by the `OFFICIAL_BUILD` conditional compilation flag

**Comment by kjozwiak** [comment]
@Uni-verse @hffvld as discussed via https://bravesoftware.slack.com/archives/GAA4017R7/p1711650759653529?thread_ts=1711598803.433469&cid=GAA4017R7, we'll need to verify https://github.com/brave/brave-browser/issues/37136 as well via this issue to make sure we're getting logs for `Leo`.

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.64 (123)`

- Ensured developer menu prompt is shown when tapping the version header in settings.
- Ensured that developer/debug menus are displayed when authentication is completed.
- Ensured that there is no issues accessing logs in debug menu.
- Ensured that logs are generated when enabling vmodule in BraveCore Switches.

**_Debug menu_**

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_3750 2](https://github.com/brave/brave-browser/assets/17885425/dc236df8-1ab6-4d52-8504-37b3a1b2ed33) | ![IMG_3751 5](https://github.com/brave/brave-browser/assets/17885425/91e0c037-dee4-442d-87f1-88bf2de0d0e5) | ![IMG_3754 5](https://github.com/brave/brave-browser/assets/17885425/27fed70b-b426-4934-b560-5474aea777e0) | ![IMG_3759 3](https://github.com/brave/brave-browser/assets/17885425/159450b7-fddd-49d9-8cd4-6cc43f1a0593) | ![IMG_3763](https://github.com/brave/brave-browser/assets/17885425/b097e461-4667-4637-a931-6c6f0f3c828b)

**_Console.app logs (Using Subsystem: com.ios.brave.software)_**

![Screenshot 2024-04-12 at 11 51 19 AM](https://github.com/brave/brave-browser/assets/17885425/363e0ed8-e910-4b43-8310-cb700b07d6ff)

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iOS 17.3.1` using version `1.64 (123)`

- Ensured developer menu prompt is shown when tapping the version header in settings.
- Ensured that developer/debug menus are displayed when authentication is completed.
- Ensured that there is no issues accessing logs in debug menu.
- Ensured that logs are generated when enabling vmodule in BraveCore Switches.

**_Debug menu_**

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_1349](https://github.com/brave/brave-browser/assets/17885425/36390e61-9dbf-4d03-985e-088f4f9199b8) | ![IMG_1350](https://github.com/brave/brave-browser/assets/17885425/16852d33-d387-4521-8c81-af5f1e11e6f7) | ![IMG_1351](https://github.com/brave/brave-browser/assets/17885425/e543f348-15ea-4184-aee4-8d2380f1b307) | ![IMG_1352](https://github.com/brave/brave-browser/assets/17885425/1878e3d3-c010-48ef-9930-c64c3ad97baa) | ![IMG_1353](https://github.com/brave/brave-browser/assets/17885425/2021c04a-ae38-44a5-b910-d6e23044dc35)


**_Console.app logs (Using Subsystem: com.ios.brave.software)_**
![Screenshot 2024-04-12 at 12 20 42 PM](https://github.com/brave/brave-browser/assets/17885425/746cb5b1-33c5-4ab8-aa37-b60ccc2d34d3)
