### ISSUE TITLE
Profile icons in the Profile manager misplaced in latest nightly only

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#36975]
## Steps to Reproduce

   1.  Install 1.66.x
   2.  launch Brave
   3.  click `Set Brave as default Browser`
   4.  select `Microsoft Edge`
   5. click `Import`
   6. click `Select All`
   7. click `Import Profiles` 
   8. click `Finish`
   9. open Profile manager
   
## Actual result:

Profile icons are misplaced and both icons & Profile names are overlapped

![image](https://github.com/brave/brave-browser/assets/98358127/c84e5a53-0f94-4efd-8abb-5ae383e225b1)

## Expected result:
![image](https://github.com/brave/brave-browser/assets/98358127/0e6eea2a-e091-45e1-926a-5e7a891f4263)

## Reproduces how often: 

Easily 

## Brave version (brave://version info)

```
Brave | 1.66.20 Chromium: 123.0.6312.58 (Official Build) nightly (64-bit)
-- | --
Revision | 6614caeef9b62aec8f4585fc26c81cef32cb18c9
OS | Windows 11 Version 23H2 (Build 22631.3296)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron

**Comment by rebron** [comment]
cc: @fallaciousreasoning @simonhong

**Comment by LaurenWags** [comment]
Requires `1.66.88` or higher for testing 👍🏻

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.66.94 Chromium: 124.0.6367.91 (Official Build) beta (64-bit)
-- | --
Revision | 1574096f9d2bcb69c3654cb4437217121ee9600b
OS | Windows 11 Version 23H2 (Build 22631.3527)
```

1. Install 1.66.94
2. launch Brave
3. click Set Brave as default Browser
4. select Microsoft Edge
5. click Import
6. click Select All
7. click Import Profiles
8. click Finish
9. open Profile manager (brave://settings/manageProfile)

#### Confirmed Profile icons and Avatars are displayed as expected

example | example 
----- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/706be565-e70e-43c8-b447-ed8a06e653c9)|![image](https://github.com/brave/brave-browser/assets/98358127/4009db5d-9003-4586-9334-5fdae6cd62ab)
