### ISSUE TITLE
Brave Panel always shows `Brave Rewards is off` on corrupted profile

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3697]
Follow up to https://github.com/brave/brave-browser/issues/3046

## Steps to Reproduce

   1. Use the staging profile https://github.com/brave/brave-browser/files/2823589/Brave-Browser-Beta-05925.zip
   2. Open Brave Panel

## Actual result:

![image](https://user-images.githubusercontent.com/34715963/54248063-919ec800-453b-11e9-96d6-8165a19df68a.png)

Important: If I go to `brave://rewards` I can join the rewards through `Yes, I am in` button.

## Expected result:
![image](https://user-images.githubusercontent.com/34715963/54248105-b430e100-453b-11e9-819f-af1acb51eddf.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.62.25 Chromium: 73.0.3683.67 (Official Build) beta (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 7 Service Pack 1 Build 7601.24312

cc @brave/legacy_qa @NejcZdovc

**Comment by LaurenWags** [comment]
Reproduced on macOS

Brave | 0.62.31 Chromium: 73.0.3683.75 (Official Build) beta(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

After joining Rewards on brave://rewards, panel displayed as expected.

**Comment by GeetaSarvadnya** [comment]
Reproduced on Linux

Brave | 0.62.26 Chromium: 73.0.3683.75 (Official Build) beta (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

**Comment by jasonrsadler** [comment]
What is being asked here? The "wallet turned off" panel has been modified to present user with "Re enable Rewards". Do we want that? Do we want the first run enable panel? Do we want to attempt to fix the profile?

**Comment by NejcZdovc** [comment]
@jasonrsadler problem here is that we think that rewards are disabled, when they are not actually turned on and you need to join in. So rewards page and panel should display the same state

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.65.97 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Reproduced issue with 0.64.76 on Release Channel
* Verified test plan from https://github.com/brave/brave-core/pull/2097
* Verified was able to join Rewards from panel, and after joining Rewards, publisher info displayed in panel as expected.
