### ISSUE TITLE
Start Playlist webui page where it was closed

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#36979]
We should remember where it was closed last time. And load the last page on start up.

### Test plan:
* Open Playlist web ui
* Go to any folder
* close playlist web ui
* Reopen the playlist web ui

### Actual result:
Playlist webui always starts from the index page.

### Expected behavior
Should start from where it was closed last time.

**Comment by bsclifton** [comment]
Fixed by https://github.com/brave/brave-core/pull/22702
