### ISSUE TITLE
Leo (Mixtral) breaks out of its prompt, revealing `User:` and `Assistant:` roles in its response

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#36977]
## Description: 

Leo (Mixtral) breaks out of its prompt, revealing `User:` and `Assistant:` roles in its response

## Steps to Reproduce 

**NOTE**: I've only (as of yet) been able to reproduce this _once_, on accident 🤷 

1. installed `1.64.108`
2. launched Brave
3. entered `kevin sorbo.com` into the URL bar
4. tapped on `Ask Leo - kevin sorbo.com` suggested entry
5. tapped to `Send to Leo`
6. tapped `I understand` to opt-in
7. waited for the queued `Leo` response
8. noted the strange quoted-text looking response
9. (at this point, I think I tapped `Suggest questions...`)
10. tapped the first generated question

### Actual:

`Leo's` response shows both `User:` and `Assistant:` roles, in the raw

`Actual` | `Expected`
---------|-----------
![IMG_9449](https://github.com/brave/brave-browser/assets/387249/fac4a2c0-569e-4d0c-a88a-81929b2ac7a4) | ![IMG_9451](https://github.com/brave/brave-browser/assets/387249/714ac45e-584c-4507-85b5-3fcc8317f2e2)

## Reproduces how often: [Easily reproduced, Intermittent Issue]

I've only been able to accidentally reproduce this once, and have also upgraded builds since

## Brave Version: 

```
Chromium	1.64.108 Chromium: 123.0.6312.46 (Official Build) unknown (64-bit)  
Revision	be7ad9d53800...
OS	iOS 17.4
```

- Can you reproduce this issue with the most recent build from TestFlight? `Not yet`
- Can you reproduce this issue with the previous version of the current build from TestFlight? `Not yet`
- Can you reproduce this issue with the current build from AppStore? `Not yet`

### Device details: 

iPhone 13 Pro
iOS `17.4` (`21E219`)

cc @mattmcalister @bbondy @Brandon-T @LorenzoMinto @brave/qa-team

**Comment by stephendonner** [comment]
Cross-reference: https://github.com/brave/brave-browser/issues/35698 on `Desktop`

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.3.1` using version `1.66.90`

- Verified STR in https://github.com/brave/brave-browser/issues/36977#issue-2198868896
- Ensured that response is not observed when using `Ask Leo` in URL bar, `Summarize this pag`e or `suggestions questions`. 

Ask Leo (URL) | Summarize this page | Prompt
-|-|-
![IMG_6012](https://github.com/brave/brave-browser/assets/17885425/9722480d-3501-46dd-a4e4-5d963796f46e) | ![IMG_6011](https://github.com/brave/brave-browser/assets/17885425/168e47a3-5a80-4539-96fe-bd124b0be655) | ![IMG_6010](https://github.com/brave/brave-browser/assets/17885425/bd28247b-0cb0-4836-bc81-b2b9f5847edb)
