### ISSUE TITLE
Add open in new tab / context menu to navigation history list

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#36988]
## Description: 

Add tap & hold / context menu with Open in New Tab & Open in Private Tab (etc.) to the back button long-press navigation history list, similar to our regular history list view? Desktop we can CMD+click items in the list to open in a new tab.

Back button navigation history menu | History context menu as example
--|--
![Back button navigation history](https://github.com/brave/brave-browser/assets/5314553/d444c454-155a-4c1c-b1ba-1b740570e828) | ![History context menu](https://github.com/brave/brave-browser/assets/5314553/6309ceca-9d40-407b-b14f-dd647741f762)

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
-  / iOS 17.5
- iPad Air / iPadOS 16.7.2
Brave build: 1.67 (92)
BraveCore: 1.67.92 (125.0.6422.76)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Open a few websites one by one in the same tab
3. Tap and hold `<` to see the previously opened websites
4. tab and any of these websites > *Verify that context menu is shown*
5. Tap each available option > *Verify it's working as expected*

**ACTUAL RESULTS:**
- Verified that the `context menu` is shown when doing `tap and hold` on a previously opened website (within the `Back button`)
- Verified that the context menu has `Open in New Tab`, `Copy Link`, and `Share Link` options
- Verified that these options are working as expected

---------------------------

<details>
<summary> iPhone 14 </summary>

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/c4c86fb8-d262-4be9-9f9f-22c18555e8f8) | ![2](https://github.com/brave/brave-browser/assets/128532965/2abbb5e7-4e37-4e77-bb01-b70d93d7065f) | ![3](https://github.com/brave/brave-browser/assets/128532965/b4a43f89-d491-464d-b876-17b4caffb78e) |
</details>
