### ISSUE TITLE
How to force custom filter lists update?

### ISSUE THREAD

**Issue by superlex** [brave/brave-browser#36987]
## Description 

Cannon find an option to force custom filter lists update.

## Steps to reproduce 

   1. Go to brave://adblock
   2. Look for an option to update custom filter lists 

![2024-03-21 16 29 52](https://github.com/brave/brave-browser/assets/1375223/40e4e466-852a-473a-bce4-65b11ca80b3a)

On Desktop:

<img width="697" alt="f" src="https://github.com/brave/brave-browser/assets/1375223/e9637658-6411-4694-8eb8-89398bc7fcbe">

## Actual result 

Cannot find it

## Expected result

You find it

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes, 1.64.109
- Can you reproduce this issue with the current Play Store Beta version? Yes, 1.65.89
- Can you reproduce this issue with the current Play Store Nightly version? Yes, 1.66.17

## Device details
   - Install type (ARM, x86): ARM64
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 14
   
## Brave version
1.64.109

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? /
- Does the issue resolve itself when disabling Brave Rewards? /
- Is the issue reproducible on the latest version of Chrome? /

**Comment by bsclifton** [comment]
cc: @ryanbr @deeppandya

**Comment by deeppandya** [comment]
Thank you @superlex @bsclifton we have an issue to address the concern here : https://github.com/brave/brave-browser/issues/35270. i will prioritize the issue.

**Comment by superlex** [comment]
Thank you @bsclifton for your suggestion, I tried 1 and 2 but unfortunately it looks like it doesn't work.

@deeppandya
Thank you!
As workaround, you could let the old `brave://adblock` until the issue will be fixed:

![telegram-cloud-photo-size-4-5769260656699228900-y](https://github.com/brave/brave-browser/assets/1375223/6e997167-705f-43e5-a1c5-02d1385cc670)

**Comment by superlex** [comment]
Thank you @bsclifton for your suggestion, I tried 1 and 2 but unfortunately it looks like it doesn't work.

@deeppandya
Thank you!
As workaround, you could let the old `brave://adblock` until the issue will be fixed:

<details>

![2024-03-25 20 53 02](https://github.com/brave/brave-browser/assets/1375223/60cf277a-1115-47db-93a6-2bc27ec2619d)

</details>

**Comment by bsclifton** [comment]
This should be captured with https://github.com/brave/brave-browser/issues/35216

I'll close this out as a duplicate and you can subscribe there for updates 😄 
cc: @deeppandya

**Comment by superlex** [comment]
You're right, thanks 😊
