### ISSUE TITLE
blocking third-party fingerpriting has no effect 

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#3698]
## Description 

Setting Shields to block third-party scripts has no effects.

## Steps to Reproduce

   1. Visit https://cezaraugusto.github.io/privacy-checks/fingerprinting/third-party/
   2. Set fingerprinting protection to block all fingerprinting
   3. Assert it works
   4. Set fingerprinting protection to block third party scripts 

## Actual result:

Script bypasses Shields option

## Expected result:
If a fingerprinting script is hosted in a third-party domain, this Shields setting should block resouce from loading.

## Reproduces how often: 

Always

## Brave version (brave://version info)

v0.60.23

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? no
- Is the issue reproducible on the latest version of Chrome?  n/a

### Additional Information

n/a

**Comment by pes10k** [comment]
This is addressed by the move to farbling based fingerprinting protections
