### ISSUE TITLE
Toggles for sync types don't work in Web UI

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#36991]
## Description 

It seems regression after https://github.com/brave/brave-core/pull/22565 . 
Worked fine on v1.66.18 and appeared on version v1.66.19 .

cc @fallaciousreasoning 

## Steps to Reproduce

   1. Create sync chain
   2. Open brave://settings/braveSync/setup
   3. Click on any type for example `Bookmarks`

## Actual result:

Toggle is not switched.

## Expected result:
Toggle is switched to a new value.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Reproduced starting from v1.66.19

**Comment by stephendonner** [comment]
## Verification `PASSED` using

```
Brave	1.66.82 Chromium: 124.0.6367.60 (Official Build) beta (x86_64) 
Revision	5dc8a11fe47f7e764f9108c665f3276805497669
OS	macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.66.82`
2. launched Brave
3. opened `brave://sync`
4. clicked on `Start a new Sync Chain`
5. toggled `Bookmarks`, `Settings`, `History`, `Theme`, and `Passwords`
6. Confirmed all were toggleable
7. launched Brave `1.66.82` on another laptop
8. opened `brave://sync`
9. clicked `I have a Sync Code`
10. entered the 25-word passphrase and clicked `Confirm`
11. waited for items to sync


### Confirmed `bookmarks`,`theme`, and passwords were synced (will investigate and file `history` separately, if needed.)

### `Machine A`

<img width="1805" alt="Screenshot 2024-04-18 at 2 49 09 PM" src="https://github.com/brave/brave-browser/assets/387249/931f347b-6eef-4cec-8486-626eacc0ac15">
