### ISSUE TITLE
Enable Forgetful Browsing by default

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#36999]
Forgetful Browsing is [disabled by default](https://github.com/brave/brave-core/blob/master/chromium_src/net/base/features.cc#L89) in code, and then [enabled via Griffin](https://github.com/brave/brave-variations/blob/production/seed/seed.json#L1346-L1421) on all platforms. This causes an issue for a new user on a new profile, before the Griffin variations have been downloaded. 

We should enable the feature by default.

**Comment by kjozwiak** [comment]
The above requires `1.64.112` or higher for `1.64.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.64.112 Chromium: 123.0.6312.58 (Official Build) (64-bit)
-- | --
Revision | 99f35375946ee8d232a0b111983ea341c24eadb5
OS | Windows 10 Version 22H2 (Build 19045.4170)
```
Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/22713#issue-2201263611, ensured that `Forget me when I close this site` was visible under both the shields panel and `brave://settings/shields` without `BraveForgetFirstPartyStorage:Enabled` being applied by Griffin.

**`Example`** | **`Example`** | **`Example`**
---------------|------------------|---------------
![image](https://github.com/brave/brave-browser/assets/38657976/8d7f5667-d62d-4725-88f5-a5366d002863) | ![image](https://github.com/brave/brave-browser/assets/38657976/711773b5-e602-493d-acab-bc32632f3098) | ![image](https://github.com/brave/brave-browser/assets/38657976/2a195dc9-3bb9-46d0-b7a3-29975ebf046a)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.64.112 Chromium: 123.0.6312.58 (Official Build) (x86_64) 
Revision	99f35375946ee8d232a0b111983ea341c24eadb5
OS	macOS Version 13.6.4 (Build 22G513)
```

**Comment by btlechowski** [comment]
Verified with

Brave | 1.64.112 Chromium: 123.0.6312.58 (Official Build) (64-bit)
-- | --
Revision | 99f35375946ee8d232a0b111983ea341c24eadb5
OS | Linux

Verified https://github.com/brave/brave-core/pull/22713

![image](https://github.com/brave/brave-browser/assets/34715963/bce2da78-9044-4c28-af72-408dffb93838)|![image](https://github.com/brave/brave-browser/assets/34715963/ec82bb6e-a6ef-4a32-9a1a-ee5ff152d280)|![image](https://github.com/brave/brave-browser/assets/34715963/e4271ee6-aaa2-4397-881e-6329b3643644)
--|--|--

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 14 AP21.240216.010 release-keys
Brave build: 1.64.104
Chromium: 123.0.6312.46 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/22713#issue-2201263611 
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Forget me when I close this site` was visible under both, the `Brave Shields` panel and `Brave Shields & privacy` setting without `BraveForgetFirstPartyStorage:Enabled` being applied by Griffin.

---------------------------

*Galaxy Tab S8*

https://github.com/brave/brave-browser/assets/128532965/e713b7ad-e6a1-492e-8723-fa2098c278b8

*Pixel 7*

https://github.com/brave/brave-browser/assets/128532965/a3af4179-9aec-4070-bba7-0bd7581d9113
