### ISSUE TITLE
[ads] Cannot get search ads for browser private mode

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#36997]

**Comment by kjozwiak** [comment]
The above requires `1.64.115` or higher for `1.64.x` verification 👍

**Comment by btlechowski** [comment]
Verified with

Brave | 1.64.116 Chromium: 123.0.6312.105 (Official Build) (64-bit)
-- | --
Revision | d9090cab16ea606108bdf6edd7466df58d9d76fd
OS | Linux

#### Regular Window

Verified ad is shown and `X-Brave-Ads-Enabled` header is included

![image](https://github.com/brave/brave-browser/assets/34715963/d7a32184-859f-4223-990a-a425704f64ac)


#### Private Window

Verified ad is shown and `X-Brave-Ads-Enabled` header is not included

![image](https://github.com/brave/brave-browser/assets/34715963/9da4365a-7c5f-41c8-a615-27b598c2677b)


#### Private Window with Tor

Verified ad is shown and `X-Brave-Ads-Enabled` header is not included

![image](https://github.com/brave/brave-browser/assets/34715963/1cb379f5-860d-4355-971d-66dc5ca21607)

**Comment by btlechowski** [comment]
Verification passed on Brave v1.64.116 on Lenovo TB-8506FS (Android 11.0)

#### Regular Window

Verified ad is shown and `X-Brave-Ads-Enabled` header is included

![image](https://github.com/brave/brave-browser/assets/34715963/45c97cb3-32c3-41e0-8e62-537d0f455c48)


#### Private Window

Verified ad is shown and `X-Brave-Ads-Enabled` header is not included

![image](https://github.com/brave/brave-browser/assets/34715963/b7a607fb-43ce-4178-9e92-e86d7113b7ea)
