### ISSUE TITLE
[Wallet] Refactor portfolio filters modal to not need redux

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#37004]
## Description 

Remove the need for dispatching redux actions and syncing redux with local storage for portfolio filters

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.80 Chromium: 124.0.6367.29 (Official Build) beta (64-bit)
-- | --
Revision | 2d822a1940c9159c1f307cd1c0a8f58fcfb50fe0
OS | Windows 11 Version 23H2 (Build 22631.3447)

- Verified steps from [brave/brave-core#22747](https://github.com/brave/brave-core/pull/22747)
- Verified Portfolio filters continue to work as expected without any regressions
