### ISSUE TITLE
"Block Fingerprinting" Changes Fonts in Google Docs

### ISSUE THREAD

**Issue by RM-0454** [brave/brave-browser#37001]
## Description 

Recently I noticed fonts in google docs got messed up (Arial in particular). A little digging revealed that the issue would resolve itself if I changed from "Block Fingerprinting" to "Allow Fingerprinting"

## Steps to Reproduce

   1. Open Brave
   2. Navigate to google docs
   3. "Allow fingerprinting"
   4. Type in some random words in Arial font
   5. "Block Fingerprinting"

## Actual result:

![image](https://github.com/brave/brave-browser/assets/75651584/19c9e623-ae0f-4eb6-bb24-4f7ac8ae7a8b)

## Expected result:
Fonts to not go missing

## Reproduces how often: 

I can produce this everytime on my work laptop, but not on my personal laptop (older version). Both are linux machines with Brave installed through apt

## Brave version (brave://version info)

Work Laptop
Version 1.63.174 Chromium: 122.0.6261.128 (Official Build) (64-bit)

Personal Laptop
Version 1.63.165 Chromium: 122.0.6261.94 (Official Build) (64-bit)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
  - Yes
- Does the issue resolve itself when disabling Brave Rewards? 
  - Unknown 
- Is the issue reproducible on the latest version of Chrome? 
  - Unknown

**Comment by ioc2e3** [comment]
> Google文件中的字體變得混亂（特別是 Arial）。經過一番挖掘發現，如果我從“阻止指紋識別

...?

not understand ...

Why does (blocking fingerprinting) mess up Google Docs' fonts?

.

**Comment by ShivanKaul** [comment]
This looks similar to https://github.com/brave/brave-browser/issues/36389 cc @arthuredelstein

**Comment by RM-0454** [comment]
For the record, this issue also applies to google maps. It appears to be a broader issue that is already captured by. https://github.com/brave/brave-browser/issues/36389

I am closing this duplicate issue 

![2024-03-25_09-39-57_screenshot](https://github.com/brave/brave-browser/assets/75651584/e7c303a0-34f2-49dc-8508-c161fa5467f4)
