### ISSUE TITLE
Custom notification ad is broken in CR124

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#37008]
Actual result:
![image](https://github.com/brave/brave-browser/assets/86598290/6677e3d2-5aff-435c-8bdd-533c5a5c01fe)

Expected result:
![image](https://github.com/brave/brave-browser/assets/86598290/c82ff949-9064-43ae-b901-0924b71afd60)

It was also reported that `NotificationAdPopupBrowserTest.CheckThemeChanged` test can fail on a current master local build with following:
![image](https://github.com/brave/brave-browser/assets/86598290/2834011f-168d-449c-9a9b-4fbb6e198244)

**Comment by tmancey** [comment]
Closing as resolved in another PR by @mkarolin
