### ISSUE TITLE
Leo purchases on iOS only work after the second time

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#37007]
## Description: 
- When purchasing Leo, the purchase goes through, but the user isn't granted access
- The receipt is nil before transaction and empty after the transaction is complete.

## Steps to Reproduce 
  1. Attempt to purchase Leo on iOS

## Actual result: 
- Purchase successful
- No premium access

## Expected result:
- Must grant premium access

## Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily reproduced

## Brave Version: 
- 1.63.x

**Comment by kjozwiak** [comment]
@hffvld @Uni-verse with the above fix, we'll basically need to quickly spot check once we get the RC build using TF and then run through the same checks/real purchases once it goes live on `App Store`.

* using the `1.63.x` RC build, ensure that you can make a purchase via TF and everything still works
  * ideally we would check with a new account as well just to ensure everything is working as expected

Once the above goes live via `App Store`, we'll basically need to run through a full purchase with a new account and ensure that we're mot receiving the same error messages mentioned above that we ran into with the original `1.63.x` release.

**Comment by kjozwiak** [comment]
@hffvld @Uni-verse and myself basically ensured that you can still purchase `Leo` via TF before signing off `1.63.182 Chromium: 122.0.6261.128`. However, the main verification will need to be done once `1.63.182 Chromium: 122.0.6261.128` goes live via the `App Store` at `1%`.
