### ISSUE TITLE
Manual test run for `1.63.1` on `iPad` running `iPadOS 16`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#37015]
## Installer

- [x] Check that installer is close to the size of the last release
- [x] Check the Brave version in About and make sure it is EXACTLY as expected

## Data

- [x] Verify that data from the previous build appears in the updated build as expected (bookmarks, history, etc.)
- [x] Verify that cookies from the previous build are preserved after upgrade
- [x] Verify saved passwords are retained after upgrade
- [x] Verify stats are retained after upgrade
- [x] Verify sync chain created in the previous version is still retained on upgrade
- [x] Verify per-site settings are preserved after upgrade

## VPN

- [x] Verify purchasing VPN subscription will install VPN profile and establish connection
- [x] Verify tunneling works by navigating to `https://ipinfo.io`

## App linker

- [x] Long-press on a link in the Twitter app to get the share picker, choose Brave. Verify Brave doesn't crash after opening the link

## Session storage

- [x] Verify that tabs restore when closed, including active tab

**Comment by hffvld** [comment]
Verified on `iPad Air` using version(s):
```
Device/OS: iPad Air / iPadOS 16.7.2
Brave build: 1.63.1 (182)
BraveCore: 1.63.182 (122.0.6261.128)
```
