### ISSUE TITLE
Cover Rewards panel when TOS notice is displayed - follow up to 35977

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#37011]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/35977

Per discussion via https://bravesoftware.slack.com/archives/CB0KCRCQN/p1711124369603209?thread_ts=1711029956.638829&cid=CB0KCRCQN, background of the panel should be blurry when the TOS notice is displayed so that balance and ads earnings are not visible to user.

## Steps to Reproduce

1. With a new profile, enable Rewards. Connect to a custodian.
2. Close the browser.
3. Use Charles Proxy to simulate incrementing the "tosVersion" field of the Rewards `/parameters` endpoint.
4. Restart the browser, confirm Charles Proxy rewrite is being used
5. Look at TOS update notice on Rewards panel.

## Actual result:

background of panel isn't blurry, so balance and ads earnings can be seen:

Contribution view | Summary view
--- | ---
<img width="446" alt="contrib" src="https://github.com/brave/brave-browser/assets/28145373/742c851f-c4ff-438a-af71-16a92ad66209"> | <img width="1181" alt="summary" src="https://github.com/brave/brave-browser/assets/28145373/9ddc4a62-26f5-4c69-b260-efbf041d36dd">

## Expected result:

background of panel should be blurry like brave://rewards page:

<img width="1193" alt="Screenshot 2024-03-22 at 12 13 09 PM" src="https://github.com/brave/brave-browser/assets/28145373/64aea73f-01e1-4a6f-812e-b1e020b672ed">

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave	1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (x86_64) 
Revision	2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS	macOS Version 13.6.4 (Build 22G513)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing

**Comment by GeetaSarvadnya** [comment]
Reproduced on `Samsung galaxy version 12` running `Bravemonoarm64.apk_1.65.95`

![Screenshot_20240329_160055_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/2cacd1d9-22da-4fdf-a53d-053d6e417867)

cc: @Miyayes @deeppandya

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.66.56 Chromium: 123.0.6312.86 (Official Build) nightly (x86_64) 
Revision	029ff6b82a6cfb16bde7c6d7ab560321a023cb8b
OS	macOS Version 13.6.6 (Build 22G630)
```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.66.94 Chromium: 124.0.6367.91 (Official Build) beta (64-bit)
-- | --
Revision | 1574096f9d2bcb69c3654cb4437217121ee9600b
OS | Windows 10 Version 22H2 (Build 19045.4291)
```
