### ISSUE TITLE
URL tooltips on new tab page show chrome:// links not brave://

### ISSUE THREAD

**Issue by fooforever** [brave/brave-browser#3701]
## Description 

URL tooltips on new tab screen show chrome:// links not brave:// links for settings bookmarks and history. When they are actually clicked they resolve to brave:// in the URL bar

## Steps to Reproduce

   1. Open a new tab
   2. Mouse over settings, history or bookmarks
   3. Observe in bottom left

## Actual result:

![image](https://user-images.githubusercontent.com/665772/54277426-b882eb80-4587-11e9-965f-e07f42bbe2a8.png)

## Expected result:
The brave URLs should be shown

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 0.60.48 Chromium: 72.0.3626.121 (Official Build) (64-bit)
Revision | da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No 
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by srirambv** [comment]
Should be fixed as part of #326 and #1616 (#1774)

**Comment by simonhong** [comment]
This is duplicated with https://github.com/brave/brave-browser/issues/2566 and fixed today :)
