### ISSUE TITLE
Extension page is shown as Settings in refreshed design

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3702]
## Description 

Extension page is shown as Settings in refreshed design

## Steps to Reproduce

   1. Install dev build which has the new settings page with categories
   2. Open Extensions page via kabob menu or by typing `brave://extensions`
   3. Opens extension page but uses settings as the highlighted category

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/54277583-aa70a300-4566-11e9-9c2a-bca5ea367a53.png)

## Expected result:
Should probably be a separate category in the new design or not have it the new design at all for extension page

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.63.4 Chromium: 73.0.3683.67 (Official Build) dev (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 10 OS Build 17134.523

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Easy
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @petemill @bsclifton @rebron

**Comment by petemill** [comment]
This is intentional. Extensions is accessed from Settings page now.
