### ISSUE TITLE
[Follow up to #33275] Debouncing feature is not working for `Base64` and `Regex (multi)` test cases

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#37026]
## Description: 

Follow-up to #33275

## Steps to Reproduce 
  1. Launch Brave
  2. Go to https://dev-pages.brave.software/navigation-tracking/debouncing.html
  3. `Run` through all 4 test cases > *Observe, `Base64` and `Regex (multi)` tests fail*

## Actual result: 

The debouncing feature is not working for the `Base64` and `Regex (multi)` test cases with Brave's `default` settings.

|Default|Base64|Regex|Regex (multi)|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/b64233fd-d1d1-48eb-a256-5f8f40d65109) | ![2](https://github.com/brave/brave-browser/assets/128532965/f3daf137-68b1-494f-848f-40db5af9ea9a) | ![3](https://github.com/brave/brave-browser/assets/128532965/d800267a-0a26-4578-84d2-a915c5c6b937) | ![4](https://github.com/brave/brave-browser/assets/128532965/23d0ee80-3d3d-477d-b4c4-16f00c6c2979) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/229e7782-21e4-4a6b-a95e-096362fa6909) | ![2](https://github.com/brave/brave-browser/assets/128532965/fcef2d9b-3672-4a4c-a98e-552203204dda) | ![3](https://github.com/brave/brave-browser/assets/128532965/b9098f98-7c83-48b3-8b28-ecae7766b52b) | ![4](https://github.com/brave/brave-browser/assets/128532965/64f10f90-084f-4986-b150-e8a73951343d) |

## Expected result:

When running any of the 4 test cases, `dev-pages.brave.software` referrer must be seen with `Debouncing` `enabled`.

## Reproduces how often: [Easily reproduced, Intermittent Issue]

`Easily reproduced`

## Brave Version: 

```
Brave build: 1.64 (109)
BraveCore: 1.64.109 (123.0.6312.58)
```

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? YES

### Device details: 

```
iPhone 14 / iOS 17.4
```

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari? 

### Additional Information

cc @cuba

**Comment by cuba** [comment]
Fixed in the followng debounce refactor which uses the brave-core components: 
https://github.com/brave/brave-core/pull/22039

**Comment by Uni-verse** [comment]
Verified on iPhone 12 running iOS 17.3.1 using version 1.66.90

- Ensured that all 4 cases are showing `https://dev-pages.brave.software` for Observed Referrer
- Ensured that "NoSuchKey" page is shown when disabling `Auto-Redirect Tracking URLs` in all cases.

Enabled | Disabled
-|-
![IMG_6006](https://github.com/brave/brave-browser/assets/17885425/2e54324d-dbd0-43d4-bee7-885c9b301870) | ![IMG_6008](https://github.com/brave/brave-browser/assets/17885425/b275df1c-e14c-4cdb-a25d-d97d46792082)
