### ISSUE TITLE
Update Review Swap Button border radius

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#37032]
## Description 

We need to update the `Review Swap` buttons border radius to match the new designs in figma!

![Screenshot 12](https://github.com/brave/brave-browser/assets/40611140/7a6f76dc-8d00-4e4d-b6f0-b7a99a17a7a2)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.66.97 Chromium: 124.0.6367.118 (Official Build) beta (64-bit)
-- | --
Revision | 94909f2aaefd7a8137c8b4fa27235378e79231e3
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22813](https://github.com/brave/brave-core/pull/22813)
- Verified Review Swap button has border radius 
<img width="1920" alt="brave_L0GfP4ruK1" src="https://github.com/brave/brave-browser/assets/17010094/f24c4dff-0ac4-4a14-a574-da1de52bd365">
