### ISSUE TITLE
`brave://settings/content/all` doesn't show Cookies and other site data anymore for individual sites, only a blank page.

### ISSUE THREAD

**Issue by TEMP-ad** [brave/brave-browser#37030]
## Description 

When going for example to Youtube and then **brave://settings/content/siteDetails?site=https%3A%2F%2Fwww.youtube.com%2F**, the page is blank, it doesn't show individual cookies or the total count for other storages with an easy way to remove them.
It doesn't work for any site, so you can go to any site that stores data and go to settings and it will be blank.

## Steps to Reproduce

   1. Go to Youtube, 
   2. then go to **brave://settings/content/siteDetails?site=https%3A%2F%2Fwww.youtube.com%2F** to see the cookies information.
   3. it is blank and useless.

## Actual result:

![image](https://github.com/brave/brave-browser/assets/156715894/cbe799b3-38ed-478b-9fbe-efa903d1c3c2)

## Expected result:
![image](https://github.com/brave/brave-browser/assets/156715894/86e4e294-00ab-4657-993f-cd891b84153e)

![image](https://github.com/brave/brave-browser/assets/156715894/d3f57d28-73cc-4386-9821-65c4c4ab7aa9)

## Brave version (brave://version info)

1.66.25 Chromium: 123.0.6312.58 (Official Build) nightly (64-bit)  
Windows 11 Version 23H2 (Build 22631.3296)

## Miscellaneous Information:

Images are taken from https://github.com/brave/brave-browser/issues/31690 where you can't access top level domain data from settings because of the 'expand button', so you can only access the 'cookies' if you edit the URL and remove the `www.` which is counted as a 'subdomain', but as you can see, even if it is `youtube` or `www.youtube` either Cookies or Cache Storage, Database Storage Local Storage and Service workers should show, so it shouldn't blank at all.

**Comment by diracdeltas** [comment]
cc @rebron - i get the same result on macOS beta. nothing is shown under brave://settings/cookies/detail?site=github.com for instance.

**Comment by diracdeltas** [comment]
also i noticed in chrome, the 'locally stored data' submenu is just gone. ex: chrome://settings/content/siteDetails?site=http%3A%2F%2Fyoutube.com%2F

**Comment by rebron** [comment]
cc: @ShivanKaul 
Looks like @emerick has a fix but we'll need a plan to support this going forward as it looks like this is being removed upstream.

**Comment by kjozwiak** [comment]
The above requires `1.64.116` or higher for `1.64.x` verification(s) 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.64.116 Chromium: 123.0.6312.105 (Official Build) (64-bit)
-- | --
Revision | d9090cab16ea606108bdf6edd7466df58d9d76fd
OS | Windows 10 Version 22H2 (Build 19045.4170)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.64.116 Chromium: 123.0.6312.105 (Official Build) (x86_64) 
Revision	d9090cab16ea606108bdf6edd7466df58d9d76fd
OS	macOS Version 13.6.6 (Build 22G630)
```

- Reproduced the issue on `1.64.113`  - `Cookies and site data` is not stored for websites and youtube.com 
- Verified the issue on `1.64.116` and ensured that `Cookies and site data` is stored for websites e.g cnn.com

1.64.113 | 1.64.116
--- | ---
<img width="1198" alt="1 64 113" src="https://github.com/brave/brave-browser/assets/28145373/8031144d-8744-4a9b-92fc-5bcc491389ac"> | <img width="1193" alt="1 64 116" src="https://github.com/brave/brave-browser/assets/28145373/ab62407d-32e7-4929-8de4-9f2d2a2c4500">
