### ISSUE TITLE
Navigating to brave://history/syncedTabs opens brave://history instead

### ISSUE THREAD

**Issue by igorburago** [brave/brave-browser#37035]
## Description 

In desktop Brave, at least on macOS, navigating to `brave://history/syncedTabs` (either via the address bar or through a bookmark) redirects to `brave://history`. (Clicking *Tabs from other devices* on the history page works, however.)

## Steps to Reproduce

1. Enter `brave://history/syncedTabs` in the address bar.
2. Press <kbd>Return</kbd>.

Alternatively:

1. Create a bookmark for `brave://history/syncedTabs`.
2. Open that bookmark.

## Actual result:

The `brave://history` page is displayed.

## Expected result:

The `brave://history/syncedTabs` page is displayed.

## Reproduces how often:

Every time.

## Brave version (brave://version info)

1.65.133 Chromium: 124.0.6367.208 (Official Build) (arm64),
revision a719189e6a0245a6ce7fab3ddc637e8bd75aed08.

The bug exists _at least since version 1.64.109_ (Chromium 123.0.6312.58) and was definitely introduced in one of the releases before that—I had noticed the bug a couple of months prior to the 1.64.109 release, but had not noted the exact version it first appeared in.

## Version/Channel Information:

The bug is present in the current release version.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
  No.
- Does the issue resolve itself when disabling Brave Rewards?
  No.
- Is the issue reproducible on the latest version of Chrome?
  N/A.

**Comment by igorburago** [comment]
Finally fixed in version 1.66.110.

**Comment by bsclifton** [comment]
Thanks for reporting and then closing once it's fixed 😄 I suspect it was something that broke upstream (in Chromium) and was fixed with Chromium 125.
