### ISSUE TITLE
[ads] Refactor tab helper, browser manager and tab manager

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#37039]

**Comment by btlechowski** [comment]
Verified with

Brave | 1.66.110 Chromium: 125.0.6422.60 (Official Build) (64-bit)
-- | --
Revision | de593d76e2ca4d02faa85bf1ca27bcf3ee46793c
OS | Linux

#### User idle detection

<details>

</details>


#### Page content is classified when visiting a website.

<details>

</details>


#### Page content is not classified when restoring a tab.


<details>

</details>


#### Page content is not classified when a page error occurs

<details>

</details>


#### User activity events are logged to the console

<details>

</details>


#### User activity events are not logged to the console upon tab restoration

<details>

</details>


#### Site visits and page landings are occurring

<details>

</details>


#### Conversions are triggered

<details>

</details>


#### Purchase intent is being tracked

<details>

</details>


#### Orphaned inline content ads are purged.

<details>

</details>


#### Push notification ads are being served

<details>

</details>


#### The browser becomes/resigns active appropriately

<details>

</details>


#### The browser enters the foreground/background appropriately

<details>

</details>


#### Frequent tab switching should not cause race conditions

<details>

</details>


#### Close each tab individually.

<details>

</details>
