### ISSUE TITLE
Can I use this for personal use?

### ISSUE THREAD

**Issue by mauro-balades** [brave/brave-browser#37043]
I wonder if the brave "fetching" build tool could be used to make a browser myself without having to deal with git issues. Just the utility fetching/syncing program, not the browser its self.

Thanks.

**Comment by bsclifton** [comment]
@mauro-balades not exactly sure what you mean - but you're free to use the code for Brave per the licensing terms

Do you have an example of what you'd like to do?

I'll mark issue as question and close (as it's not a product issue). But please do respond here - I'll be watching for replies

**Comment by mauro-balades** [comment]
I would like to make my own chromium based browser and it looks like brave already has the tools to fetch, sync, build, etc chromium with patches. I was wondering if I could use that "build tool" to build my own browser that's unrelated to brave.
