### ISSUE TITLE
Pre-pend [Ad] to Advertiser text for all Ad notifications

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#3705]
Add "[Ad] " to Advertiser-Title  for all notifications served via Brave Ads client.
This is to separate out advertising notifications from regular Brave notifications.

Please request uplift to launch with Ads release schedule.
cc @jsecretan

**Comment by mandar-brave** [comment]
@tmancey I realize the title may be misleading. Sorry see the text in the issue; we need [AD] pre-pended to the Advertiser title vs CTA text

**Comment by NejcZdovc** [comment]
@mandar-brave this one was already uplifted, so let's keep this closed and open new one with with new ask

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

- Verified test plan from https://github.com/brave/brave-core/pull/1944
<img width="370" alt="Screen Shot 2019-03-20 at 2 46 08 PM" src="https://user-images.githubusercontent.com/28145373/54711215-cd2f2880-4b1f-11e9-854c-b93f6e409759.png">

**Comment by srirambv** [comment]
Marking as `QA/No` as its not valid anymore
