### ISSUE TITLE
Context menu can be a moving target

### ISSUE THREAD

**Issue by warwickmm** [brave/brave-browser#37051]
### Description: 
The context menu that appears after a long press on an image can be a moving target.  If there is text in the image that triggers the "Show Text" entry, the appearance of that entry can be delayed and sometimes shifts the location of the other entries when it appears.

### Steps to Reproduce 
  1. Enter private browsing only.
  2. Go to https://en.m.wikipedia.org/wiki/LeBron_James.
  3. Scroll so that the first image is near the bottom of the screen in portrait mode.
  4. Long press the image.

### Actual result: 

The context menu appears.  Then, a brief moment later the "Show Text" entry appears, shifting all the existing entries upwards.  This may cause the user to accidentally select the wrong entry since the locations on the screen have changed.

https://github.com/brave/brave-ios/assets/17345532/8db9d955-0989-4c66-9e10-71e6d7789a6c

### Expected result:

The entries in the context menu should not change their location on the screen.

### Reproduces how often:

Easily reproduced

### Brave Version:

Version 1.62.2 (24.3.11.17)

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details:

iPad Air (5th generation)
iPadOS Version 17.4

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
This is an iOS feature, and is unfortunately controlled by Apple's WebKit framework. A quick glance suggests this is not something we can disable, but you can disable this at an OS-level if you'd like via the Settings application. (Specifically in the General > Language & Region screen, then disable "Live Text")

**Comment by warwickmm** [comment]
Thanks, I wasn't aware of that setting.  It is interesting to note that the delay doesn't occur when using Safari.
