### ISSUE TITLE
Add an ability to dictate Leo prompt

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#37053]
We want to use Android API for voice recognition. Basically a new microphone icon has to be added into the input prompt. We should recognise the prompt and submit it to Leo for a response.

**Comment by kjozwiak** [comment]
The above requires `1.64.113` or higher for `1.64.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.64.113 Chromium: 123.0.6312.86 (Official Build) (64-bit) 
Revision	4e20399c0c5e3cbbb80dd1119122400e08259feb
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Verified voice dictation is working for Leo prompt when enabling the microphone.
- Verified permission prompt is shown when first interacting with the microphone. 
- Verified there are no issues using voice dictation repeatedly for Leo. 
- Verified there are no issues using keyboard for Leo chat. 

Example | Example | Example
-|-|-
![Screenshot 2024-03-27 at 10 40 22 AM](https://github.com/brave/brave-browser/assets/17885425/d3f5d6bc-27be-475f-b92d-e674e77d9f9f) | ![Screenshot 2024-03-27 at 10 49 20 AM](https://github.com/brave/brave-browser/assets/17885425/5fa5ff2c-5970-421b-a5da-f363b8c3f434) | ![Screenshot 2024-03-27 at 10 49 35 AM](https://github.com/brave/brave-browser/assets/17885425/d6ec7ada-15df-45b4-9cc4-8749237607c4)

**Comment by lee-b** [comment]
This should use a local STT model like whisper and be conversational, rather than 2011-style siri commands.
