### ISSUE TITLE
[iOS] Closing tab grays out X in current active tab

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#37064]
### Description: 
Closing active tab grays out X in current active tab

Follow up to https://github.com/brave/brave-ios/issues/6333

### Steps to Reproduce 
  1. Install 1.46.x
  2. Enable tabs bar
  3. Open at least 4 tabs
  4. Close tab by tapping on X in the active tab

**Actual result:** 
The X shows as grayed out/not in focus

<table><tr><td>iOS</td><td>iPadOS</td></tr>

<tr><td>

https://user-images.githubusercontent.com/17885425/207667291-6d3e9833-f17b-45ab-ba30-b4240e7df6b6.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/207667429-5a0a0c2c-5315-48a9-9c0a-676042bec617.MP4

</td></tr></table>

**Expected result:**
X in tab bar should not be grayed out

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.46 (22.12.13.0)

**Device details:** 
iPhone, iPad

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6
Brave build: 1.68 (106)
BraveCore: 1.68.106 (126.0.6478.126)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/37064#issue-2206053677 and https://github.com/brave/brave-core/pull/23770#issue-2308942864
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `x` is not getting grayed out when closing the `active tab`

---------------------------

https://github.com/brave/brave-browser/assets/128532965/f3e76f0f-b796-4c2f-b126-bcfa7c3e2922
