### ISSUE TITLE
Add 'Close other tabs' option

### ISSUE THREAD

**Issue by iccub** [brave/brave-browser#37069]
Add it to the tabs button long press gesture menu

User request from here
https://www.reddit.com/r/brave_browser/comments/vubrn0/feature_request_close_other_tabs_in_ios/

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.6
- iPad Air / iPadOS 16.7.2
Brave build: 1.68 (101)
BraveCore: 1.68.101 (126.0.6478.126)
```
---------------------------
<details>
<summary> Close all "x" tabs </summary>

**STEPS:**
1. Fresh install and launch Brave 
2. Open multiple tabs > Tap and hold the `Tab switch` button
3. Use `Close All "x" Tabs` > *Verify*
4. Tap and hold the `Tab switch` button > View Recently Closed Tabs > *Verify*

**ACTUAL RESULTS:**
- Verified that only the `Close Tab` option is available when only one tab is opened and no `recently closed` tabs
- Verified that all tabs are closed including the active tab, NTP is opened and Brave is not closed
- Verified that all closed tabs are added to the `Recently closed` tabs list

---------------------------

`iPhone`

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/83be706d-e3a8-4c5c-bdc9-f33565060437) | ![2](https://github.com/brave/brave-browser/assets/128532965/1763445b-4aec-4b23-860d-ee629f34e7b9) | ![3](https://github.com/brave/brave-browser/assets/128532965/65583f68-dc8e-4ea0-90d8-0fcd25d57d21) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/a52a6f52-0215-400d-b491-85562bf070c1) | ![2](https://github.com/brave/brave-browser/assets/128532965/09510abf-a82a-47cd-a53a-6676be48e124) | ![3](https://github.com/brave/brave-browser/assets/128532965/f1a6a93f-8a2a-4067-bf4f-0a5651d88332) |

`iPad`

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/b57a731c-d56f-4ac1-b949-29cc2c6bbe5d) | ![2](https://github.com/brave/brave-browser/assets/128532965/9cf26028-986b-48d4-bca8-85e1899a30f5) | ![3](https://github.com/brave/brave-browser/assets/128532965/2d23b85b-089a-4105-bfd6-b293b1d90d17) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/56bf70d8-984a-4221-8a09-1a2e997c6467) | ![2](https://github.com/brave/brave-browser/assets/128532965/34da4382-c228-47ce-9f5c-d6d92f0a487a) | ![3](https://github.com/brave/brave-browser/assets/128532965/489889d8-c646-4703-bca7-015a32494ce4) |
</details>

<details>
<summary> Close all other tabs </summary>

**STEPS:**
1. Launch Brave 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>
