### ISSUE TITLE
Version 1.64.109 broke AWS VPN Client

### ISSUE THREAD

**Issue by gabrielgasp** [brave/brave-browser#37078]
## Description 

I use AWS VPN Client for work and, when connecting, a tab is opened in the browser for authentication purposes. After the update, when trying to connect I get an error (seen below). I confirmed that this is a browser version because it works with other browsers and with an earlier version of Brave (1.64.174).

## Steps to Reproduce

   1. Open AWS VPN Client with a profile that requires authentication via browser on AWS.
   2. Try to connect.
   3. Get erro from AWS VPN Client.

## Actual result:

![Screenshot 2024-03-25 at 16 41 04](https://github.com/brave/brave-browser/assets/83838669/b6968f31-9081-49b1-99a5-84253a62ffb4)

## Expected result:
Connection established successfully.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

Brave: 1.64.109 Chromium: 123.0.6312.58 (Official Build) (arm64) 
Revision: ded360c0dc8a4bd8aecb9cbe32a7aa4477d42246
OS: macOS Version 14.4 (Build 23E214)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Did not try.
- Can you reproduce this issue with the nightly channel? Did not try.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? No.

**Comment by rebron** [comment]
related to this issue: https://issues.chromium.org/issues/330594669
and fixed with https://github.com/brave/brave-variations/pull/971
cc: @atuchin-m

**Comment by kush-work** [comment]
@rebron Is there a way to rollback to earlier version of Brave without losing the local cache?

**Comment by rebron** [comment]
@kush-work @gabrielgasp This should be live/fixed now with a browser restart. Still having issues?

**Comment by gabrielgasp** [comment]
Issue fixed after 1.64.113 update. Appreciate the fast response!
