### ISSUE TITLE
remote list webcompat exceptions service

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#37074]
## Description 
We want a Webcompat Exceptions Manager that allows us to disable individual fingerprinting protections for specific websites. This issue refers specifically to the remote list service; a separate issue will be used for UI.

See more details at:
* [Webcompat Exceptions Manager spec](https://docs.google.com/document/d/17uc2pEizLY43k4HSVbrl2yuiExNv25EdZvV_3RYYmQE/edit#heading=h.wq0fkg1i9170)
* [Implementation Plan: Webcompat Exceptions Manager](https://docs.google.com/document/d/1mjdx3Rk2TCXbJRzpYkb3ieGm2MhFXxf4zTGEEropzuY/edit?pli=1#heading=h.qiew63uicrsj)

**Comment by davidcollini** [comment]
Is this change being made so we can see stronger fingerprinting protection in default Brave with minimal site breakage?

**Comment by arthuredelstein** [comment]
> Is this change being made so we can see stronger fingerprinting protection in default Brave with minimal site breakage?

I hope this change will enable stronger fingerprinting protections, yes!

> Or is this solving a separate issue?

It's also planned to fix some existing known webcompat issues.

**Comment by GeetaSarvadnya** [comment]
@arthuredelstein: Can you add the test plan, please? Thanks!

**Comment by LaurenWags** [comment]
Labelling as `QA/Blocked` per the above comment

**Comment by arthuredelstein** [comment]
** Suggested testing **

The webcompat exceptions service is behind a flag, brave://flags/#brave-webcompat-exceptions-service. It should be disabled by default, unless enabled remotely by griffin.

When the feature is enabled, we currently have three websites that are fixed by a remote list. That list is here: https://github.com/brave/adblock-lists/blob/master/brave-lists/webcompat-exceptions.json

In order to test each of these broken sites, follow the steps to reproduce the problem in each listed bug. Then confirm that when the webcompat exceptions is enabled, the three bugs should be fixed.

For QA testing of the webcompat exceptions service UI, please see https://github.com/brave/brave-browser/issues/39510

**Comment by arthuredelstein** [comment]
@LaurenWags -- confirmed: you don't need the code from #39510 to test this issue.

**Comment by LaurenWags** [comment]
excellent, thanks so much @arthuredelstein. Will removed `QA/Blocked` from this one 👍🏻

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.69.122 Chromium: 127.0.6533.57 (Official Build) beta (64-bit)
-- | --
Revision | bd77e9b76a8e67ff2bf9f62f1df7d60378ca811f
OS | Windows 11 Version 23H2 (Build 22631.3880)
```

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.69.129 Chromium: 127.0.6533.73 (Official Build) beta (x86_64)
-- | --
Revision | 0ab2f25cd017b563fd72d68048f809659a351a04
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.69.128 Chromium: 127.0.6533.73 (Official Build) beta (64-bit) 
Revision	715445841b1da480bcc24c12077a6dc926951996
OS	Linux
```
<details>
<summary>Case 1: Load website `maps.gsi.go.jp/...` - PASSED</summary>

1. Installed `1.69.128`
2. launched Brave
3. opened `brave://flags` in a new tab
4. verified `#brave-webcompat-exceptions-service` is disabled by default
5. loaded [maps.gsi.go.jp/...](https://maps.gsi.go.jp/index_3d.html?z=16&lat=35.653225&lon=139.73539700000003&pxsize=1024&ls=std#&cpx=-54.107&cpy=162.515&cpz=99.300&cux=-0.518&cuy=0.245&cuz=0.820&ctx=1.324&cty=20.508&ctz=33.599&a=1&b=0&dd=0) in a new tab
6. verified map spikes are shown
7. verified `Block fingerprinting` setting is selected in the shields panel
8. returned `brave://flags tab` and `#brave-webcompat-exceptions-service` flag and relaunched Brave
9. returned to the tab and refreshed the map page
10. confirmed spikes are not shown
11. confirmed new toggle setting for `Block fingerprinting` which is enabled in the shields panel

`#brave-webcompat-exceptions-service` flag disabled | `#brave-webcompat-exceptions-service` flag enabled
------ | -------
![image](https://github.com/user-attachments/assets/8dda42a4-4607-4885-9f23-971acd446f0c)|![image](https://github.com/user-attachments/assets/4b0d583a-5f18-40a5-b77a-9af71be3d241)
![image](https://github.com/user-attachments/assets/1402437f-7e16-43ad-833d-dc7747fce66c)|![image](https://github.com/user-attachments/assets/bb9a6fc7-3f2c-4935-8cbb-37f3f5d0b736)
![image](https://github.com/user-attachments/assets/0468636e-34ae-46b0-88a5-1877f6231d6a)|![image](https://github.com/user-attachments/assets/7925fc88-4c1f-4928-a3d3-9c4243e671de)

</details>

<details>
<summary>Case 2: Load website `https://www.harkins.com/` - PASSED </summary>

1. Installed `1.69.128`
2. launched Brave
3. opened `brave://flags` in a new tab
4. verified `#brave-webcompat-exceptions-service` is disabled by default
5. loaded https://www.harkins.com/ in a new tab
6. verified `Block fingerprinting` setting shown in the Shields panel 
7. select a movie (eg. Insideout 2)
8. click seat selection
9. verified seats are not selected when pressed
10. returned to `brave://flags` and enabled the `#brave-webcompat-exceptions-service` flag and relaunch Brave
11. returned to `https://www.harkins.com/` tab and refreshed page
12. confirmed able to select seats
13. confirmed able to unselect seats
14. confirmed new toggle setting for `Block fingerprinting` which is enabled in the shields panel

`#brave-webcompat-exceptions-service` flag disabled | `#brave-webcompat-exceptions-service` flag enabled
------ | -------
![image](https://github.com/user-attachments/assets/b2ebce1d-ae3f-4e6e-a100-38536434bffd)|![image](https://github.com/user-attachments/assets/840de582-5a73-4255-9016-d6abbe744535)
![image](https://github.com/user-attachments/assets/655d5f86-dc58-4e7b-a0f4-36d078b1fa53)|![image](https://github.com/user-attachments/assets/4d5d12a3-7a7f-4ac7-81ae-8402fdfea127)
![image](https://github.com/user-attachments/assets/ebeaa2ab-2726-4c87-a842-c4df566f6b2c)|![image](https://github.com/user-attachments/assets/9b1ae274-4c51-486c-a7de-d61aeefb01c6)

</details>

<details>
<summary>Case 3: Load website https://www.nperf.com/ - PASSED</summary>

1. Installed `1.69.124`
2. launched Brave
3. opened `brave://flags` in a new tab
4. verified `#brave-webcompat-exceptions-service` is disabled by default
5. loaded https://www.nperf.com/ site in a new tab
6. verified `Block fingerprinting` settings is selected in the Shields panel
7. returned to `brave://flags` tab and enable `#brave-webcompat-exceptions-service` flag and relaunched Brave
8. returned to the https://www.nperf.com/ site tab 
9. confirmed page loaded without errors and speed test worked as expected
10. confirmed page loaded without errors and connection was with Shields down as well
11. confirmed new toggle setting for `Block fingerprinting` which is enabled in the shields panel
`#brave-webcompat-exceptions-service` flag disabled | `#brave-webcompat-exceptions-service` flag enabled
------ | -------
![image](https://github.com/user-attachments/assets/2fd93a11-3cd7-4d59-8ec4-609bf47e7e64)|![image](https://github.com/user-attachments/assets/52d39f4e-ce32-423b-a570-0e651d669d4d)
![image](https://github.com/user-attachments/assets/9c315de2-2b9e-4fc0-9df7-2275fa979497)|![image](https://github.com/user-attachments/assets/67be4976-8fc3-4b0f-9901-286ce4b39905)
![image](https://github.com/user-attachments/assets/1ec82bba-bb91-4025-bdb1-6311937523af)|![image](https://github.com/user-attachments/assets/7c36e57d-bc55-462a-a464-ce9fd1fb87c2)

</details>

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 AP31.240617.010 release-keys
Brave build: 1.69.131
Chromium: 127.0.6533.88 (Official Build) beta (64-bit) 
```
---------------------------
<details>
<summary> Case 1: Load website "maps.gsi.go.jp/..." </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>

<details>
<summary> Case 2: Load website "https://www.harkins.com/" </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>

<details>
<summary> Case 3: Load website "https://www.nperf.com/" </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>
