### ISSUE TITLE
A-C/Monthly Tips computation issue (leading to incorrect notifications)

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#3707]
For monthly recurring contributions, the only BAT that needs to be counted is;

a) for verified publishers in a-c
b) for verified publishers in Tip table

In any circumstance, the unverified pending BAT should not be counted for reconcile date contributions.

Issue: currently a lot of folks are getting incorrect notifications that they don't have sufficient funds for their monthly contribution when they do.

cc @NejcZdovc @jasonrsadler @LaurenWags @rebron

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.108 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2208
* However, even if total of auto contribute for verified pubs + total of recurring monthly tips for verified pubs is less than wallet balance, contribution does not go thru. Logged #5230
