### ISSUE TITLE
[Nala]: Toggles on the chrome://extensions page don't have any CSS

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#37079]
They show up as unstyled:

![image](https://github.com/brave/brave-browser/assets/7678024/65705244-1e86-44f3-940e-e3f3c003edb1)

while they should be a Nala toggle:
![image](https://github.com/brave/brave-browser/assets/7678024/45eebab8-d8ed-4c07-b3d8-b8d58755fff1)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.66.54 Chromium: 123.0.6312.86 (Official Build) nightly (64-bit)
-- | --
Revision | f5ab7d6aacb75e42f0687e4bbced3ff9a6c9c85e
OS | Windows 10 Version 22H2 (Build 19045.4239)
```

`Dark` mode | `Light` mode
--------------|---------------
![image](https://github.com/brave/brave-browser/assets/387249/d1a403ef-20fa-42a6-b7ff-f7597408d236) | ![image](https://github.com/brave/brave-browser/assets/387249/5ac14c25-21c2-4ce2-9cb6-ac2092da7f5e)

**Comment by stephendonner** [comment]
NOTE: filed https://github.com/brave/brave-browser/issues/37316 as a followup, @fallaciousreasoning
