### ISSUE TITLE
Leo settings is blank on model selection and crashes

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#37083]

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.66.54 Chromium: 123.0.6312.86 (Official Build) nightly (64-bit)
-- | --
Revision | f5ab7d6aacb75e42f0687e4bbced3ff9a6c9c85e
OS | Windows 10 Version 22H2 (Build 19045.4239)
```

### Steps:
1. installed `1.66.54`
2. launched Brave
3. opened `brave://settings`
4. clicked on `Leo`
5. confirmed `Default model for new conversations` is `Mixtral`
6. confirmed `Claude Instant` and `LLama2-13b` were available via the dropdown <select> widget
7. chose `Claude Instant`
8. asked `Leo` what 9x9 is
9. opted-in

### Confirmed `Leo`'s `Default model for new conversations` was prepopulated with `Mixtral`, and the other LLM choices were available.  Also, no crashes.



example | example | example | example
----------|-----------|-----------|---------
![image](https://github.com/brave/brave-browser/assets/387249/d06d25b3-2617-4f12-9b9b-e90c7c0cb72f) | ![image](https://github.com/brave/brave-browser/assets/387249/66bc5723-24cb-472d-bd6e-3fe083d03562) | ![image](https://github.com/brave/brave-browser/assets/387249/3737d4ff-761a-4790-a0aa-9e3c98672e84) | ![image](https://github.com/brave/brave-browser/assets/387249/5636ca86-64ca-4f3f-ab4d-a521ed1aa552)

**Comment by stephendonner** [comment]
## Verified `PENDING` using

```
Brave	1.66.53 Chromium: 123.0.6312.86 (Official Build) nightly (x86_64) 
Revision	a79fb87f4f3b5b0c833644ed870a657eef74b987
OS	macOS Version 11.7.10 (Build 20G1427)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```

```

**Comment by hffvld** [comment]
Verified on `Pixel 6` using version(s):
```
Device/OS: Pixel 6 / oriole-user 14 AP1A.240405.002 release-keys
Brave build: 1.66.90 
Chromium: 124.0.6367.82 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Install and launch Brave
2. Three-dot menu > Settings
3. Leo > *Verify that the `Default model for new conversations` is `Mixtral`*
4. Choose `Claude Instant` > Close the settings
5. Launch `Leo` in the same tab
6. Ask something > *Verify that `Mixtral` LLM is used*
7. Open another `NTP` > Launch `Leo`
8. Ask something > *Verify that `Claude` LLM is used*

**ACTUAL RESULTS:**
- Verified that the `Default model for new conversations` is `Mixtral`
- Verified that `Claude Instant` and `Llama 2 13b` are available
- Verified that Leo's `Default` model for new conversations was prepopulated with `Mixtral`, and the other LLM choices were available. 
- Verified that Brave is not crashing

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/a4400543-2349-41cd-9ad3-28ba4f1aec3c) | ![2](https://github.com/brave/brave-browser/assets/128532965/b5861edd-d78f-43dd-8358-34ca1f6e1115) | ![3](https://github.com/brave/brave-browser/assets/128532965/658bea61-9d36-496e-96fa-82954d88b52a) | ![4](https://github.com/brave/brave-browser/assets/128532965/95d0f65e-5315-42a7-8757-f36a5d472d3a) |
