### ISSUE TITLE
turn on/off switch button loss in brave extensions page!!!

### ISSUE THREAD

**Issue by petercao** [brave/brave-browser#37087]
type below command in brave browser address line:
brave://extensions/

then we can only see plugins detail and remove button, I can't see any turn on/off button,
which still be in chrome browser: chrome://extensions/

in brave:
![image](https://github.com/brave/brave-browser/assets/927208/4ab496e1-92e5-4bf6-ae84-3cb16213b9d7)

in chrome:
![image](https://github.com/brave/brave-browser/assets/927208/c5e33373-5efc-417a-98be-2144fecf3c9a)

**Comment by petercao** [comment]
this on/off button is very usaful for me,because sometimes I need to forbidden some plugin temporarily,
Pls help to restore this function, thx

**Comment by rebron** [comment]
Closing as duplicate. This will be fixed in next nightly with this pr: https://github.com/brave/brave-core/pull/22762

**Comment by petercao** [comment]
thx a lot
