### ISSUE TITLE
Update What's New for 1.65

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#37092]
Update the What's New page with Leo info and release in 1.65. See doc: https://docs.google.com/document/d/19nzSUD9HC2ClIYot0UBh-maO973iLwNwfvVNX-_sDTY/edit

For background, originally planned for 1.63/1.64: https://github.com/brave/brave-variations/pull/931

cc @kjozwiak @rebron @larreewong @rmcfadden3

**Comment by kjozwiak** [comment]
Verifications for the above were completed via https://github.com/brave/brave-variations/pull/1001#issuecomment-2060263235.

**Comment by kjozwiak** [comment]
Removing `OS/Android` as that `Whats New` page is only available on `Desktop` as per https://github.com/brave/brave-variations/pull/1002/files#diff-7ac2945ede68c73330363911678f6c9a2a6290b70e2dd170868295f65da7e872L1536.
