### ISSUE TITLE
[Wallet] Remove redux state for hiding portfolio graph 

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#37098]
## Description 

We can utilize the useLocalStorage hook instead of syncing redux state with the local storage value

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.80 Chromium: 124.0.6367.29 (Official Build) beta (64-bit)
-- | --
Revision | 2d822a1940c9159c1f307cd1c0a8f58fcfb50fe0
OS | Windows 11 Version 23H2 (Build 22631.3447)

- Verified steps from [brave/brave-core#22782](https://github.com/brave/brave-core/pull/22782)
- Verified the toggle for hiding/showing the portfolio graph continues to work without any regressions
- Verified on both Wallet page and panel

https://github.com/brave/brave-browser/assets/17010094/9ceab2d6-fc0a-4cd9-a35e-113b86831763
