### ISSUE TITLE
Using cached ad-block results after changing shield settings

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#37090]
## Description: 
When changing from aggressive to standard (or vice versa), we use the cached values of the previous setting resulting in no change in behaviour in some cases when switching settings

NOTE: This issue will mess with the behaviour in the STR so make sure it is merged first https://github.com/brave/brave-browser/issues/37084

## Steps to Reproduce 
  1. Load a blocked page such as https://wallet-api.urbanairship.com
  2. Notice the blocked page comes up
  3. Switch modes (i.e. from standard to aggressive or aggressive to standard)
  4. Reload the page (note: you have to click on the url bar and enter the address or else you are refreshing the interstitial page and no change will occur)

## Actual result: 
No change of behaviour between standard and aggressive mode

## Expected result:
Change of behaviour between standard and aggressive mode

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari?

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.5
Brave build: 1.66 (95)
BraveCore: 1.66.95 (124.0.6367.91)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/37090#issue-2208069572
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Trackers & Ads Blocking` settings applied on a blocked page without Brave restart

---------------------------

*Reproduced*

https://github.com/brave/brave-browser/assets/128532965/42b0d330-fd49-4d1c-9808-798cb52629a7

*Verified*

https://github.com/brave/brave-browser/assets/128532965/077b1775-6471-4a0a-ae65-59ab8fec3d86
