### ISSUE TITLE
do not add internal pages in NTP top sites

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#3710]
at first run NTP shows https://chrome.google.com/webstore?hl=en as a top site and it should not.

### Test Plan

* Reset your profile
* Open Brave
* Open NTP
* a tile with https://chrome.google.com/webstore?hl=en is shown

Expected: it should show nothing

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.62.32 Chromium: 73.0.3683.75 (Official Build) beta (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

- Verified the STR mentioned in the description
![image](https://user-images.githubusercontent.com/38657976/54632165-7a179000-4aa3-11e9-843e-bd7dd65a879a.png)
