### ISSUE TITLE
Enable Media Router (cast) feature by default on Desktop

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#37109]
We had previously [disabled Media Router by default on Desktop](https://github.com/brave/brave-browser/issues/17873) (but [enabled by default on Android](https://github.com/brave/brave-browser/issues/17972)). The Media Router feature (toggleable in brave://settings/extensions) allows a user to cast a Brave tab to a device such as a smart TV. During privacy review, we'd caught that when the Media Router feature was on, outgoing SSDP packets used the Brave user agent instead of the Chrome one like we do on the Web. This was fixed in https://github.com/brave/brave-browser/issues/18017. 

At this point I don't think there's much benefit to keeping this important feature disabled by default. We should enable by default, and let privacy-conscious users turn it off.

1. New profiles should have Media Router toggle ON by default. 
2. Existing profiles should not be changed, to avoid us overriding users' preferences.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.67.86 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | a1f8e8f462d422d4b924fa9c34246f68862b21ad
OS | Windows 11 Version 23H2 (Build 22631.3593)
```
New Install
<details>
<summary>Case 1:  New profile => Media Cast is ON </summary>

1. Install 1.67.86
2. launched Brave
3. opened `brave://settings/extensions`

- Confirmed `Media Router` is enabled by default
- Confirmed `Cast` option in the Share menu is shown

example | example 
------ | ----
![image](https://github.com/brave/brave-browser/assets/98358127/8bf5c09e-7e57-4d90-af30-b9d75210405e)|![image](https://github.com/brave/brave-browser/assets/98358127/1d045895-f733-415d-a8c0-96fade23b7c1)
</details>

<details>
<summary>Case 2: Existing profile has Media Cast OFF => nothing changes </summary>

1. installed 1.66.110
2. launched Brave
3. opened `brave://settings/extensions`
4. verified `Media router` is disabled by default
5. closed the browser and renamed the `profile to brave-browser-beta`
6. installed 1.67.86
7. launched Brave
8. opened `brave://settings/extensions`

#### Confirmed `Media Router` is disabled

example | example | example 
------- | ----- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/e4fdc0f3-07df-4b2b-9409-7130de336251)|![image](https://github.com/brave/brave-browser/assets/98358127/22e36090-9bbd-422f-8b20-a69a6728c9c2)|![image](https://github.com/brave/brave-browser/assets/98358127/4b0081c1-4bea-4dac-8c4c-e567e4a60b61)

</details>

<details>
<summary>Case 3: Existing profile has Media Cast ON => nothing changes </summary>

1. installed 1.66.110
2. launched Brave
3. opened `brave://settings/extensions`
4. toggled `On` `Media router`
5. closed the browser and renamed the `profile to brave-browser-beta`
6. installed 1.67.86
7. launched Brave
8. opened `brave://settings/extensions`

#### Confirmed `Media Router` is disabled

example | example | example | example
------ | ------ | ---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/074edfdb-0b8b-4bca-9c66-65fba3048206)|![image](https://github.com/brave/brave-browser/assets/98358127/c44d70a3-da55-4c85-bb0f-09fd637fd396)|![image](https://github.com/brave/brave-browser/assets/98358127/57faddf3-973a-4092-b8ff-34fd1b7fc53a)|![image](https://github.com/brave/brave-browser/assets/98358127/19cd6c25-73eb-42ff-bcf8-70816ffb349d)

</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```

Brave | 1.67.100 Chromium: 125.0.6422.112 (Official Build) beta (x86_64)
-- | --
Revision | 34fcbb6655521b55468af6c63601a8e3c5d24cd2
OS | macOS Version 14.5 (Build 23F79)

```
Brave | 1.67.100 Chromium: 125.0.6422.112 (Official Build) beta (x86_64)
-- | --
Revision | 34fcbb6655521b55468af6c63601a8e3c5d24cd2
OS | macOS Version 14.5 (Build 23F79)
```

## New install
Case 1:
## Upgrade
Case 2: 
Case 3:

**Comment by ShalokShalom** [comment]
How to enable it on an existing profile? There is no flag or setting that I can see.

**Comment by bsclifton** [comment]
@ShalokShalom you should find it under brave://settings/extensions

Basically this one:
![image](https://github.com/user-attachments/assets/47399f21-68bd-4d8d-b937-da6a18860f1a)

**Comment by ShalokShalom** [comment]
I am speaking about the Android app.
