### ISSUE TITLE
Network Selector gets cut off in Visible Asset modal

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#37102]
## Description 

The `Network Selector` is getting cut off in the `Edit Visible Asset` modal

## Steps to Reproduce

   1. Open the Wallet `Panel` and then open the `Edit Visible Assets` modal
   2. Click on the `Network Selector`
   3. The `Popup` gets cut off at the bottom of the `Panel`

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/ab76d7ff-35bb-4fc9-8ccf-ff82cdbb11e7

## Expected result:

Should be a scrollable `Popup`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on
 
Brave | 1.66.95 Chromium: 124.0.6367.91 (Official Build) beta (64-bit)
-- | --
Revision | e1f8e3c95a12986231bc8226b78a951233e7c026
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22790](https://github.com/brave/brave-core/pull/22790)
- Verified Network selector doesn't get cut off in Visible Asset modal on panel

https://github.com/brave/brave-browser/assets/17010094/50bf0f4f-255e-4dd2-be34-b4ebc592cbd4
