### ISSUE TITLE
Add Account not prompted if account exists for same coin type on other keyring

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#37114]
## Description: 

Network picker does not prompt to create an account for Filecoin testnet/mainnet if an account is created for the opposite network. Ex Filecoin Mainnet account exists, then Filecoin Testnet is selected in network picker (or vice-versa).

## Steps to Reproduce 
  1. Create a fresh wallet
  2. Enable `Show Test Networks` in Web3 Settings -> Networks
  3. Add Filecoin Mainnet account
      - Can occur vice-versa too, creating Filecoin Testnet account here then selecting Mainnet in step 5
  4. Open Buy or Swap
  5. Select Filecoin Testnet in network picker
      - If Filecoin Testnet account created, select Filecoin Mainnet in network picker
  6. Observe Filecoin Testnet selected but Filecoin Mainnet

## Actual result: 

Filecoin Mainnet account selected / Filecoin Testnet network selected

https://github.com/brave/brave-browser/assets/5314553/9dd9bc92-c4f5-403f-a4c3-0715f4333de6

## Expected result:

Prompt to create an account if one does not exist for the network being selected

## Reproduces how often: 

Easily reproduced

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari? 

### Additional Information

Hit testing [Bitcoin add account](https://github.com/brave/brave-core/pull/22737), but same bug exists for Filecoin.

cc @srirambv @nuo-xu

**Comment by kjozwiak** [comment]
The above requires `1.64.115` or higher for `1.64.x` verification 👍
