### ISSUE TITLE
[NTP]: Currently the settings menu on the NTP isn't rendered in a dialog

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#37110]
Because the settings menu on the NTP doesn't render in a dialog, it can get stuck under other dialogs (such as the NTP Search box), which isn't desirable.

We should update it to use the Nala dialog component

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.66.82 Chromium: 124.0.6367.60 (Official Build) beta (64-bit)
-- | --
Revision | 5dc8a11fe47f7e764f9108c665f3276805497669
OS | Windows 11 Version 23H2 (Build 22631.3447)
```

1. Installed 1.66.82
2. launched Brave
3. opened a new tab 
4. clicked `customize` button in the NTP
5. confirmed `Customize Dashboard` dialog on the NTP 
6. confirmed successfully opened multiple tabs 
7. confirmed when clicked close button, `Customize Dashboard` is closed

example | example
------ | ------
![image](https://github.com/brave/brave-browser/assets/98358127/3c6ef8c3-d353-4689-89fb-24fbf81f52c6)|![image](https://github.com/brave/brave-browser/assets/98358127/01905770-5e52-41ce-8a72-f15c4696686f)

**Comment by LaurenWags** [comment]
see https://github.com/brave/brave-browser/issues/37631#issuecomment-2077818307 for discussion about related macOS specific issue
