### ISSUE TITLE
Add Shields filter list & "forget first party" metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#37124]
Add the following Shields metrics, reported monthly:

Which extra ad-block filter lists do you have enabled this month?
`Brave.Shields.FilterLists`

0. None
1. One or more hardcoded filter lists
2. One or more custom filter lists
3. Both hardcoded & custom filter lists

Do you have the "forget me when I close this site" setting enabled?
`Brave.Shields.ForgetFirstParty`

0. Not globally, and not per-site
1. Globally enabled, no exceptions for any sites
2. Globally enabled, but the setting is disabled for at least one site
3. Not globally, but the setting is enabled for at least one site

cc @anthonypkeane @ShivanKaul

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.67.85 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | d01060f5ec155e6eb64a335203663a29c0e5d81f
OS | Windows 10 Version 22H2 (Build 19045.4412)
```

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.67.90`

### Brave.Shields.FilterLists

<details>
<summary>Brave.Shields.FilterLists = 0_</summary>

1. Clean profile 1.67.x
2. Open brave://local-state file
3. Look for the metrics `Brave.Shields.FilterLists`
4. Confirmed that the metrics `Brave.Shields.FilterLists` response value is `0` as expected
![image](https://github.com/brave/brave-browser/assets/38657976/228e3c3a-526e-4674-8485-62bc9e515dfd)

</details>

<details>
<summary>Brave.Shields.FilterLists = 1_</summary>

1. Clean profile 1.67.x
2. Open brave://local-state file
3. Look for the metrics `Brave.Shields.FilterLists`
4. Confirmed that the metrics `Brave.Shields.FilterLists` response value is `0` as expected
5. Go to brave://settings/shields/filters
6. Enable one or two additional filter lists
7. Reload brave://local-state file
8. Look for the metrics `Brave.Shields.FilterLists`
9. Confirmed that the metrics `Brave.Shields.FilterLists` response value is `1` as expected

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/97b57d86-696d-4206-af31-1d30e5a94881) | ![image](https://github.com/brave/brave-browser/assets/38657976/cd1d054c-8dd7-4814-aca1-643e414495c4)


</details>

<details>
<summary>Brave.Shields.FilterLists = 2_</summary>

1. Clean profile 1.67.x
2. Open brave://local-state file
3. Look for the metrics `Brave.Shields.FilterLists`
4. Confirmed that the metrics `Brave.Shields.FilterLists` response value is `0` as expected
5. Go to brave://settings/shields/filters
6. Keep the default `Filter lists` as it is
7. Add a custom filter https://ads-for-open-source.readthedocs.io/en/latest/_static/lists/opensource-ads.txt
8. Reload brave://local-state file
9. Confirmed that the metrics `Brave.Shields.FilterLists` response value is `2` as expected

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/01c2cdd5-1ac5-4c0e-aca7-8ef35c53158a) | ![image](https://github.com/brave/brave-browser/assets/38657976/03c1ad91-7698-4db1-aa9d-2eef7a419a27)

</details>

<details>
<summary>Brave.Shields.FilterLists = 3_</summary>

1. Clean profile 1.67.x
2. Open brave://local-state file
3. Look for the metrics `Brave.Shields.FilterLists`
4. Confirmed that the metrics `Brave.Shields.FilterLists` response value is `0` as expected
5. Go to brave://settings/shields/filters
6. Enable one or two additional filter lists
7. Add a custom filter https://ads-for-open-source.readthedocs.io/en/latest/_static/lists/opensource-ads.txt
8. Reload brave://local-state file
9. Look for the metrics `Brave.Shields.FilterLists`
10. Confirmed that the metrics `Brave.Shields.FilterLists` response value is `3` as expected

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/0d3245d9-141d-4693-abb8-b2d3350d30b4) | ![image](https://github.com/brave/brave-browser/assets/38657976/6ce37be2-86ec-4c66-bcb3-6c02f071f97b)

</details>
