### ISSUE TITLE
Deposit can shown incorrect accounts for token

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#37123]
## Description: 

In Deposit, selecting FIL on Filecoin Mainnet will show all Filecoin accounts, including Filecoin Testnet accounts.
In Deposit, selecting FIL on Filecoin Testnet will show all Filecoin accounts, including Filecoin Mainnet accounts.

In Asset Detail for FIL on Filecoin Mainnet will show all Filecoin accounts, including Filecoin Testnet accounts.
In Asset Detail for FIL on Filecoin Testnet will show all Filecoin accounts, including Filecoin Mainnet accounts.

## Steps to Reproduce 
Deposit:
1. Have at least 1 Filecoin account on Filecoin Mainnet and 1 Filecoin account on Filecoin Testnet
2. Open Deposit
3. Search/Filter for FIL
4. Open FIL on Filecoin Mainnet
5. Observe test network accounts shown
6. Tap back, open FIL on Filecoin Testnet
7. Observe mainnet accounts shown

Asset Detail View (only a Filecoin Mainnet account exists):
1. Have 1 Filecoin Mainnet account and open FIL on Filecoin Testnet in Asset Detail
2. Tap Deposit, observe Filecoin Mainnet account is shown as selected

Asset Detail View (only a Filecoin Testnet account exists):
1. Have 1 Filecoin Testnet account and open FIL on Filecoin Mainnet in Asset Detail
2. Tap Deposit, observe Filecoin Testnet account is shown as selected

## Expected result:

Only Filecoin Mainnet accounts are shown in deposit for FIL on Filecoin Mainnet
Only Filecoin Testnet accounts are shown in deposit for FIL on Filecoin Testnet

## Reproduces how often: 

Easily reproduced

## Brave Version: 

v1.66+

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari?

**Comment by srirambv** [comment]
This should be exclude. It regressed in 1.64.x but works fine in 1.63.x
