### ISSUE TITLE
[Shared pinned tab] Don't close the pinned tab with cmd-w.

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#37125]
Instead ignore it, or close the WebContents instance but leave the site pinned. But this behavior is limited to when shared pinned tab feature is enabled.

cc @ajayseeker It seems it doesn't let me assign you before you interact with this issue.

**Comment by ajayseeker** [comment]
Hi! I would like to work on this issue. Please, assign it to me. 🙂

**Comment by sangwoo108** [comment]
Thanks @ajayseeker assigned

**Comment by ajayseeker** [comment]
Hi @sangwoo108,
I've been trying to understand the source code. Following is my understanding so far:
1. Brave/chromium_src contains the core browser functionality which I understand is built over open source chromium's code. It contains cpp code. 
2. Brave/ios contains code specific to ios brave app.  
3. Brave/android contains code specific to android brave app. It's mainly in java.
4. Brave/browser contains the code specific to Desktop brave browser. It's mainly in cpp.

Is my understanding correct?

I guess we must have a core brave browser logic over which Desktop, android and ios apps must be built. 
Is this core-logic present in Brave/chromium_src? or 
Is it present in Brave/browser?
Can you please clarify?

Also, I understand the fix for this issue should go in that central component over which Desktop/android/ios apps should depend.

**Comment by sangwoo108** [comment]
I believe https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/browser_commands.cc;drc=0d795c6e8be398088fdd747cb4fa4b7c7e366878 could be good starting point, which would be invoked when you press the shorcut. And the shared pinned tab feature is managed by `//src/brave/browser/ui/tabs/shared_pinned_tab_service.h`

**Comment by ajayseeker** [comment]
Hi @sangwoo108,
I was on vacation for couple of weeks so couldn't work. However, I've resumed my efforts now.

I'm facing an issue while debugging, I guess I need to set the Include paths in VSCode for all the .h files to get recognised.
I started doing it manually and realised there are lots of them. 
Can you please share the all the Include Paths which needs to be added to compile and debug files? 

Or, In case I'm completely off the path, please guide me how to debug.

**Comment by ajayseeker** [comment]
> TBH, I've never succeeded in debugging with VSCode. I usually use xcode ore visual studio. If you want to create xcode or visual studio project, then you'll need to do following
> 
> * create `.env` file to 'src/brave' directory
> * In the .env file, add `brave_extra_gn_gen_opts=--ide=xcode`, in case visual studio `--ide=vs`.
> * run `npm run build` again so that the project file can be generated.
> * Go to `src/out/Default` directory and find the solution file and open.
> 
> For logging, you can use something like `LOG(ERROR) << "Mesage"; ` or `base::debug::StackTrace(20).Print()`.

sure! thanks!

**Comment by ajayseeker** [comment]
Hi @sangwoo108, After some debugging I realised the key code handling the tab closing flow resides in actual src/chrome.
I've made the changes and tested them. Can you please take a look at the PR and share your comments?
PR :- https://github.com/brave/chromium/pull/1

**Comment by sangwoo108** [comment]
Hi, @ajayseeker . I believe you got the point.

* As for the change in tab_strip_model, we don't directly modify `brave/chromium` so that we can catch up with the chromium more easily. It could feel like hacky, but we prefer using `#define` to add code to chromium's code. Please refer to `src/brave/chromium_src/chrome/browser/ui/tabs/tab_strip_model.h`. I believe you can add interface there

```diff
- #define IsReadLaterSupportedForAny virtual IsReadLaterSupportedForAny
+ #define IsReadLaterSupportedForAny virtual IsReadLaterSupportedForAny \
  bool bool IsAnySelectedTabPinned();
```

like wise, you can add `chromium_src/.../tab_strip_model.cc` and add implementation of it.

Please refer to https://github.com/brave/brave-browser/wiki/Patching-Chromium

* as for the change in browser_frame_mac, I think you did good job at debugging and got the right way. But as browser_frame_mac.mm is used only on Mac, you might want to find more general place to put the condition.

**Comment by ajayseeker** [comment]
> Hi, @ajayseeker . I believe you got the point.
> 
> * As for the change in tab_strip_model, we don't directly modify `brave/chromium` so that we can catch up with the chromium more easily. It could feel like hacky, but we prefer using `#define` to add code to chromium's code. Please refer to `src/brave/chromium_src/chrome/browser/ui/tabs/tab_strip_model.h`. I believe you can add interface there
> 
> ```diff
> - #define IsReadLaterSupportedForAny virtual IsReadLaterSupportedForAny
> + #define IsReadLaterSupportedForAny virtual IsReadLaterSupportedForAny \
> +  bool bool IsAnySelectedTabPinned();
> ```
> 
> like wise, you can add `chromium_src/.../tab_strip_model.cc` and add implementation of it.
> 
> Please refer to https://github.com/brave/brave-browser/wiki/Patching-Chromium
> 
> * as for the change in browser_frame_mac, I think you did good job at debugging and got the right way. But as browser_frame_mac.mm is used only on Mac, you might want to find more general place to put the condition.

thanks for your comments!🙂 working on them.
