### ISSUE TITLE
Overlapping Select Token to Swap Buttons

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#37139]
## Description 

Token Buttons are overlapping each other when selecting a token to `Swap To` in the Wallet `Panel`

## Steps to Reproduce

   1. Open the Wallet `Panel` and navigate to the `Swap` page
   2. Select a token to swap `From`
   3. Now select a token to swap `To`
   4. The token buttons overlap each other sometimes

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/2e3ab624-ef01-491d-88c7-064ac2bd42bf

## Expected result:
Should not overlap each other.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.97 Chromium: 124.0.6367.118 (Official Build) beta (64-bit)
-- | --
Revision | 94909f2aaefd7a8137c8b4fa27235378e79231e3
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22837](https://github.com/brave/brave-core/pull/22837)
- Verified Select token doesn't overlaps on one another on Swap screen in panel

https://github.com/brave/brave-browser/assets/17010094/6b4a4d9c-b47e-4595-b8b4-c8caeaf81d7a
