### ISSUE TITLE
iOS Leo Performance

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#37138]
## Description: 
- iOS Leo needs performance fixes for Chat response

## Brave Version: 

- 1.63.x

**Comment by kjozwiak** [comment]
The above requires `1.63.183` or higher for `1.63.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.3.1` using version `1.63.183`

- Ensured that Chat performance (response text animation) has improved.
- Ensured that free model performance is consistent with Premium models.

https://github.com/brave/brave-browser/assets/17885425/5cafc2d0-032e-4ed5-aac1-19a6fc23dc99
