### ISSUE TITLE
Browser is connecting to 12 different Google IP addresses on start.

### ISSUE THREAD

**Issue by TontyTon** [brave/brave-browser#3713]
## Description 

Browser connects to 12 different Google IP addresses just after start. What is the reason for it?
Is it for component updates?, but they were earlier too present. Or some other reason.

## Steps to Reproduce

   1. download some network monitoring tool. (I used LiveTcpUdpWatch by NirSoft)
   2. Open it
   3. Open Brave browser

## Actual result:

browser tries to connect to 12 different Google IP addresses, when all are blocked and the number increase if they are allowed by firewall.

## Expected result:
It doesn't connect to any Google IP addresses any time.
_If they were only for componet updates_, then they should be routed through Brave servers.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)
-- | --
OS | Windows 10 OS Build 17763.348

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? no
- Is the issue reproducible on the latest version of Chrome? not relevent

### Additional Information

Checked that hangouts are disabled. Also checked by disabling all extensions.

This issue was not present on brave version 0.60.45 (Only connected to one Google IP)

**Comment by btlechowski** [comment]
Thanks for reporting.

I was unable to reproduce on clean profile.

Could you include full log of connections made?

Brave | 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 7 Service Pack 1 Build 7601.24312


```
http://no-thanks.invalid:443
http://go-updater.brave.com:443
http://go-updater.brave.com:443
http://go-updater.brave.com:443
http://go-updater.brave.com:443
http://go-updater.brave.com:443
https://go-updater.brave.com/extensions
https://go-updater.brave.com/extensions
https://go-updater.brave.com/extensions
https://go-updater.brave.com/extensions
https://go-updater.brave.com/extensions
http://brave-core-ext.s3.brave.com:443
http://brave-core-ext.s3.brave.com:443
http://brave-core-ext.s3.brave.com:443
http://brave-core-ext.s3.brave.com:443
http://brave-core-ext.s3.brave.com:443
http://laptop-updates.brave.com:443
https://brave-core-ext.s3.brave.com/release/cffkpbalmllkdoenhmdmpbkajipdjfam/extension_1_0_148.crx
https://brave-core-ext.s3.brave.com/release/oofiananboodjbbmdelgdommihjbkfag/extension_1_0_11.crx
https://laptop-updates.brave.com/promo/custom-headers
https://brave-core-ext.s3.brave.com/release/afalakplffnnnlkncjhbmahjfjhmlkal/extension_1_0_8.crx
https://brave-core-ext.s3.brave.com/release/oemmndcbldboiebfnladdacbdfmadadm/extension_2_0_673.crx
https://brave-core-ext.s3.brave.com/release/cpoalefficncklhjfpglfiplenlpccdb/extension_1_0_4.crx
http://no-thanks.invalid:443
https://go-updater.brave.com/extensions
https://laptop-updates.brave.com/1/usage/brave-core?platform=winx64-bc&channel=release&version=0.61.51&daily=true&weekly=true&monthly=true&first=true&woi=2019-03-11&ref=none
http://no-thanks.invalid:443
http://hcxrvfuktsodmhw/
http://uvepfqemkakabbi/
http://bmveepawddf/
https://go-updater.brave.com/extensions
http://static.brave.com:443
http://static.brave.com:443
https://static.brave.com/safebrowsing/csd/client_model_v5_variation_0.pb
https://static.brave.com/safebrowsing/csd/client_model_v5_ext_variation_0.pb
https://go-updater.brave.com/extensions
http://no-thanks.invalid:443
https://go-updater.brave.com/extensions
```

**Comment by TontyTon** [comment]
How can I generate the log of connections, using brave or third party tool?

If third party tool, it would be great if you could suggest one.

**Comment by btlechowski** [comment]
I used Fiddler. 

But you can use chromium internal logger
On Windows:
```
cd "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application"
brave.exe --log-net-log=/c/Users/bartlomiej/AppData/Local/BraveSoftware/netlog.json --net-log-capture-mode=IncludeSocketBytes
```

**Comment by rebron** [comment]
cc: @diracdeltas can you take a look?

**Comment by TontyTon** [comment]
When created this issue, brave was trying to connect to 12 Google IPs each time I opened Brave (5-6 trials), but now only 3 Google IPs. (I have no idea why)

In Fiddler, only these urls are shown (other than @btlechowski 's list)
http://www.gstatic.com:443
http://redirector.gvt1.com:443


Sorry for the delayed reply (in LiveTcpUdpWatch)

**Comment by jumde** [comment]
http://redirector.gvt1.com:443 - The connections to this domain happen if there are any non-default component/extensions are enabled.

**Comment by TontyTon** [comment]
These are the connections for new Profile, created for this purpose only.

Also when I checked the connections after few minutes I observed a new entry for googleapis too.[When I left the window open and did nothing (observed after getting offline)]

**Comment by TontyTon** [comment]
Closing the issue since not observing it in the dev channel.
