### ISSUE TITLE
Expose `brave://flags` on iOS

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#37149]
## Description: 

It'd be nice to be able to access `brave://flags` so that you don't have to specifically pass in `--enable-features` via the debug switches menu.

We'd need to expose the WebUI, as well as implement the appropriate patches/chromium_src overrides to add Brave-specific flags to the page.

**Comment by kjozwiak** [comment]
The above requires `1.64.118` or higher for `1.64.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.5
- iPad Air / iPadOS 16.7.2
Brave build: 1.64 (119)
BraveCore: 1.64.119 (123.0.6312.105)
```
Filed follow-up issue #37404
---------------------------

**STEPS:**
1. Launch Brave 
2. Open `NTP` > Go to:
- `brave://version`
- `brave://flags`
- `brave://histograms`
- `brave://local-state`
3. *Verify that these internal pages from above can be opened*

**ACTUAL RESULTS:**
- Verified that `brave://version`, `brave://flags`, `brave://histograms` and `brave://local-state` can be accessed from the omnibox. 

---------------------------

*iPhone*

|`brave://version`|`brave://flags`|`brave://histograms`|`brave://local-state`|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/6e849de5-7d8f-4017-94ad-05cc8adf64a2) | ![2](https://github.com/brave/brave-browser/assets/128532965/3fdd2996-1eac-4513-894b-b25a0a3c844c) | ![3](https://github.com/brave/brave-browser/assets/128532965/cc5b7b3c-7a31-47bd-8180-b603b060bc90) | ![4](https://github.com/brave/brave-browser/assets/128532965/cf5d33ee-655c-40cc-83e8-a34658aba22d) |

*iPad*

|`brave://version`|`brave://flags`|`brave://histograms`|`brave://local-state`|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/82ad987e-8236-4a72-bc1a-544251cdeda8) | ![2](https://github.com/brave/brave-browser/assets/128532965/1e4ff055-289c-411e-af78-fdb45a2d2562) | ![3](https://github.com/brave/brave-browser/assets/128532965/b0cd6668-5dc3-4ae5-84c0-a8b2e23234ca) | ![4](https://github.com/brave/brave-browser/assets/128532965/c8c5f841-cb3c-45ec-b613-2726552f121b) |
