### ISSUE TITLE
[Wallet] Remove unused global state for network and account filters

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#37144]
## Description 

We no longer utilize global state or local storage for network and account filter drop-downs. Remove unused state as well as any logic to maintain valid values.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.90 Chromium: 124.0.6367.82 (Official Build) beta (64-bit)
-- | --
Revision | 803a4c629341791205b744969c48b8da9f2cfa4d
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22817](https://github.com/brave/brave-core/pull/22817)
- Verified network filters works as expected on all screens without any regression

https://github.com/brave/brave-browser/assets/17010094/6cc553d5-8715-45f7-b054-90e48f551d79
