### ISSUE TITLE
Disable Leo on Android when a global JS toggle set to block

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#37146]
Currently Leo chat window gives us a blank screen when a global JavaScript switch set to block https://github.com/brave/brave-browser/issues/36012. It looks like it's related to a schema used for web-ui `chrome-untrusted` as with `chrome` it works ok. I tried to dig deeper and most likely we would need to patch upstream to add such kind of white listed URL, not obvious yet for now. As a first iteration we decided to disable Leo completely when the JS toggle is set to blocked to avoid bad user experience.

**Comment by kjozwiak** [comment]
The above requires `1.64.116` or higher for `1.64.x` verification(s) 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.64.116 Chromium: 123.0.6312.105 (Official Build) (64-bit) 
Revision	d9090cab16ea606108bdf6edd7466df58d9d76fd
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Verified STR / Test Plan in https://github.com/brave/brave-core/pull/22820#issue-2211438317
- Verified disabling JS toggle globally will remove Leo from the hamburger menu and omnibox.
- Verified disabling JavaScript per site via Block Scripts toggle in Shields panel will not remove Leo feature. 
- Verified Leo can be used with JavaScript disabled locally (per site).

Example | Example | Example
-|-|-
![Screenshot 2024-04-03 at 10 33 38 AM](https://github.com/brave/brave-core/assets/17885425/5d2ae1aa-06e4-4520-b4d5-d2601a3655c8) | ![Screenshot 2024-04-03 at 10 41 38 AM](https://github.com/brave/brave-core/assets/17885425/da10f31f-a672-45c1-9724-3741e3fb03e3) | ![Screenshot 2024-04-03 at 10 41 14 AM](https://github.com/brave/brave-core/assets/17885425/46083da8-0561-4e39-a8d7-36eafc129bf4)

Example | Example | Example
-|-|-
![Screenshot 2024-04-03 at 10 44 52 AM](https://github.com/brave/brave-core/assets/17885425/01151f61-e8f5-458a-964e-20d77ea09c1a) | ![Screenshot 2024-04-03 at 10 45 05 AM](https://github.com/brave/brave-core/assets/17885425/1c8e8615-d18f-4801-83ee-23062d35f1e8) | ![Screenshot 2024-04-03 at 10 45 40 AM](https://github.com/brave/brave-core/assets/17885425/2f20f5cc-05bd-4e31-baf1-74a6eb1620fb)

**Comment by Uni-verse** [comment]
In progress on `Android ARM Tablet` using version: 

```
Brave	1.64.116 Chromium: 123.0.6312.105 (Official Build) (64-bit) 
Revision	d9090cab16ea606108bdf6edd7466df58d9d76fd
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
