### ISSUE TITLE
Brave news feed is empty after enabling news for a new profile both in Beta & Nightly

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#37156]
## Description 

Brave news feed is not loaded and shows `Your feed is Empty` after enabling news via `Turn on News` card. News feed loaded after clicking `New content available. Reload?`.  This issue exists both in 1.65.x & 1.66.x.  

## Steps to Reproduce

   1. Install 1.65.93 
   2. launch Brave
   3. enable news via `Turn on News` card in the new tab page

## Actual result:

`Yout feed is Empty` message shown

![image](https://github.com/brave/brave-browser/assets/98358127/0af8d3b0-9a7b-4f3e-9143-e67b4fe2b146)

## Expected result:
Brave news feed should be loaded for `For You` tab

![image](https://github.com/brave/brave-browser/assets/98358127/85d47e91-6cbc-4914-81e5-6dadb6b747fa)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.65.93 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | a6eee503125f9441360861f96cfdcccf43b6fee0
OS | Windows 11 Version 23H2 (Build 22631.3296)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@lorenzo @rebron 
cc: @brave/qa-team

**Comment by stephendonner** [comment]
@MadhaviSeelam if you just sit at the new-tab page w/Brave News and wait, do you eventually get a `New content available` bubble at the top?

**Comment by kjozwiak** [comment]
The above is also an issue on `Android` as per https://github.com/brave/brave-browser/issues/37270. Added the `release/blocking` label as we'll need to get the above fixed before pushing out `1.65.x` next week.

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` until uplifted to 1.65.x

**Comment by kjozwiak** [comment]
The above requires `1.65.113` or higher for `1.65.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.65.113 Chromium: 124.0.6367.60 (Official Build) (64-bit)
-- | --
Revision | c1a6c6e73c1f2f1e5bf00a6f0d42065219845887
OS | Windows 10 Version 22H2 (Build 19045.4291)
```
- Confirmed that the news feed isn't empty after enabling Brave News via NTP
- Confirmed that Brave News feeds are shown on NTP 
![image](https://github.com/brave/brave-browser/assets/38657976/0d44b400-733c-4542-9b71-43c2a146f69f)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.65.113 Chromium: 124.0.6367.60 (Official Build) (64-bit) 
Revision	c1a6c6e73c1f2f1e5bf00a6f0d42065219845887
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Ensured Brave News feed is not empty after enabling on fresh profile.
- Ensured that news feed is not empty when enabling from settings page. 

![Screenshot 2024-04-16 at 12 32 30 PM](https://github.com/brave/brave-browser/assets/17885425/0f99c5ca-81ac-48a2-9a09-731a4131bb5f)
