### ISSUE TITLE
`Error no in app info in response` error on initial IAP via `production`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#37150]
## Description: 

When attempting to do a IAP for `Leo` via `production` once the builds are uploaded/available via the `App Store`, users who initially purchase `Leo` will receive an `Error` message due to the following:

```
{
  "message": "Error no in app info in response",
  "errorCode": "validation_failed",
  "code": 400,
  "data": {
    "validationErrors": {
      "receiptErrors": "no in app info in response"
    }
  }
}
```

Once the user hits the above error/issue, `Leo` has technically been purchased but the user isn't converted to a `Premium` user. When a user is in the above state, they'll need to basically `Restore` via the IAP paywall model. However, when you're in the above state, you'll notice that `Brave Leo` is under the OS's valid/available subscriptions.

## Steps to Reproduce

  1. download/install `1.63.182 Chromium: 122.0.6261.128` via the `App Store` (this is the `1.63.1` release)
  2. run through a IAP for `Leo` via `Hamburger Menu` -> `Settings` -> `Leo` -> `Go Premium`
  3. run through the `Leo` paywall modal and complete a purchase

You'll get the `400 - Error no in app info in response` error and you'll notice that the user wasn't converted into `Premium`.

## Actual result: 

**`Example`** | **`Example`**
----------------|----------------
![IMG_0209](https://github.com/brave/brave-browser/assets/2602313/7660c551-b567-46a0-9e72-265862640d3b) | ![IMG_0210](https://github.com/brave/brave-browser/assets/2602313/96758297-92c4-4d7b-89f4-407960b0cbf3)

https://github.com/brave/brave-browser/assets/2602313/75f4d7cb-40ff-4918-b64b-49e047f5f07d

## Expected result:

IAP should work 

## Reproduces how often: [Easily reproduced, Intermittent Issue]

```
1.63.182 | Chromium: 122.0.6261.128 (Official Build) unknown (64-bit)
--- | ---
Revision | aba689383f95...
OS | iOS
```

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? `Yes`
- Can you reproduce this issue with the previous version of the current build from TestFlight? `Yes`
- Can you reproduce this issue with the current build from AppStore? `Yes`

### Device details: 

* `iPhone 11` running `iOS 17.4.1` - **`Reproduced`**

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Is the issue reproducible on the latest version of Mobile Safari? `N/A`

**Comment by kjozwiak** [comment]
Closing as the above is hopefully resolved by https://github.com/brave/brave-core/pull/22791.

**Comment by kjozwiak** [comment]
The above requires `1.63.183` or higher for `1.63.x` verification 👍

**Comment by hffvld** [comment]
Verified in TF on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.4.1
Brave build: 1.63.2 (183)
BraveCore: 1.63.183 (122.0.6261.128)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/37150#issue-2211477361
2. *Verify*

**ACTUAL RESULTS:**
- Verified that no errors are shown when purchasing a new `Leo` subscription
- Verified that no rate limit is seen

---------------------------

https://github.com/brave/brave-browser/assets/128532965/aded0df4-302b-4344-8320-d2ee0bbd8640

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 17.4.1` using the following build(s):

```
1.63.183 | Chromium: 122.0.6261.128 (Official Build) unknown (64-bit) 
--- | ---
Revision | 442293d4d758...
OS | iOS
```

So unfortunately I ran into the `Error` again with the latest `1.63.2` build but this time around, when I pressed `OK` on the error modal, the subscription/credentials looked like they were loaded. I then summarized a few pages/follow up questions and didn't get the rate limit. However, I also ran into a few issues.

Here's the case that I ran through:

* using a brand new account that has never used TF before, I bought VPN via TF and that worked without any issues (however, I didn't install the profile/enable the VPN as all I cared about was the purchase)
* once VPN was purchased, I went through the `Leo` purchase using `Settings` -> `Leo` -> `Go Premium`

#### `Notes:`

* `~38s` into the video, you'll notice that I'm starting to run through the `Leo` purchase on `staging` via TF using a brand new Apple ID
* `~1:07min` -- you'll notice that I hit the `Error` message. I waited ~5-6s to see if anything happened but it wasn't being dismissed. I clicked on `OK` and then noticed that all my subscription information was filled in and I was set as `Premium`
* `~4:15min` -- When Mixtral started summarizing this question, it basically stopped at `~4:30s` and completely froze the entire UI/application. I waited ~10-15s or so and it finally completed the summarization, unfroze the UI thread and then displayed the last remaining `Suggested question`
* once the above happened, `Leo` basically stopped working in that instance/tab. I tried asking it a question via `~5:10min` and attempted to summarize another page within the same instance via `~6:06min` and it wouldn't do anything (waited ~15-20s each time). I could never get Mixtral to work in that instance after the UI froze.
* once I opened a new tab after experiencing :point_up:, Mixtral worked in the new instance

So re: the `Error`, there's a high chance that users might still see the error. Maybe we'll just experience it on TF and not `production`. If users are still getting the `Error` but recover/end up pulling/receiving the credentials, we'll probably continue pushing the build live and in the meantime, we'll look into improving the purchase/IAP flow. Hopefully we'll get more data back from users (this is assuming we continue pushing live if `production` looks good once we go live with `1.63.2`).

https://github.com/brave/brave-browser/assets/2602313/1f043798-175f-4044-8b4e-761b53b46643

**Comment by Uni-verse** [comment]
Verified on `iPhone X` using version `16.7` using version `1.63.2`

### IAP after hitting rate limit (Brand new account with clean install)

- Ensured that Premium upgrade screen was shown when reaching rate limit. 
- Ensured that IAP purchase flow is successful and Premium status is activated.
- Ensured that sending 20+ queries after upgrading does not limit user.
- Ensured that voice recognition is working in chat.

https://github.com/brave/brave-browser/assets/17885425/48ef8c0e-26fa-4834-9762-50cc93ddb408

### Restore credentials (linked from Android IAP)

- Ensured that loading account.brave.com will enable Premium status.
- Ensured that sending 20+ queries between multiple tabs does not.

https://github.com/brave/brave-browser/assets/17885425/6013daf6-8db5-4c0a-87a0-b898173b645f

**Comment by hffvld** [comment]
Verified on `iPhone 14`using version(s):
```
Device/OS: iPhone 14 / iOS 17.4.1
Brave build: 1.63.2 (183)
BraveCore: 1.63.183 (122.0.6261.128)
```
---------------------------

## `IAP subscription before hitting the rate limit` 

**STEPS:**
1. Add brand new account on device
2. Install and launch Brave
3. Go to `Leo` or `Settings > Leo`
4. Purchase new subscription
5. Open `Leo` > *Verify that `Premium` subscription is shown there*
6. Set language model to `Mixtral` > Run ~20 queries > *Verify that no rate limit*
7. Set language model to `Claude` > Run ~20 queries > *Verify that no rate limit*

**ACTUAL RESULTS:**
- Verified that IAP for new `Leo` subscription is working.
- Verified that rate limit message is not shown after sending ~20 queries.

---------------------------

https://github.com/brave/brave-browser/assets/128532965/69eaaba4-64c2-4fa5-919b-07cbffdf3266
