### ISSUE TITLE
[Wallet] Remove unneeded checks for pending unlock requests

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#37152]
## Description 

The wallet already utilizes observers to detect when the wallet is locked on unlocked and requests unlocking when the wallet is locked. There should not be a need to check for pending unlock requests, we should only need to check if the wallet is currently locked or not.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.80 Chromium: 124.0.6367.29 (Official Build) beta (64-bit)
-- | --
Revision | 2d822a1940c9159c1f307cd1c0a8f58fcfb50fe0
OS | Windows 11 Version 23H2 (Build 22631.3447)

- Verified steps from [brave/brave-core#22821](https://github.com/brave/brave-core/pull/22821)
- Verified wallet "unlock" UI is shown when the wallet is locked
- Verified wallet "unlock" UI is not shown when wallet is locked
- Verified on both wallet page and panel

https://github.com/brave/brave-browser/assets/17010094/df1ffa65-e585-4450-836e-6630094cfdaf
