### ISSUE TITLE
`JSON text` under https://star-randsrv.bsg.brave.com endpoint shows the NullpointerException 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#37169]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/35302
`JSON text` under https://star-randsrv.bsg.brave.com endpoint shows the NullpointerException 
## Steps to Reproduce

   1. Open Charles proxy
   2. Clean profile 1.65.x
   3. Launch brave
   4. Wait for few mins (1or 2), observe the metrics under https://star-randsrv.bsg.brave.com endpoint
   5. Click on any metrics and click on the `JSON text`

## Actual result:

`JSON text` under https://star-randsrv.bsg.brave.com endpoint shows the NullpointerException 
![image](https://github.com/brave/brave-browser/assets/38657976/d81ac6c9-2099-4959-bee1-fe4a79475639)

## Expected result:
should not be any exception

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.65.95 Chromium: 123.0.6312.86 (Official Build) beta (64-bit)
-- | --
Revision | ef0da42c66f8e52af0783c9f8393035a88249c10
OS | Windows 10 Version 22H2 (Build 19045.4170)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @DJAndries @mattmcalister

**Comment by DJAndries** [comment]
@GeetaSarvadnya if the parse the contents using some other JSON parsing tool, does it work? this might be an issue with Charles...

**Comment by DJAndries** [comment]
Also, are requests sent to `collector.bsg.brave.com` returning a successful HTTP status code? if so, then the payload is valid JSON for sure
