### ISSUE TITLE
Accumulated ads and earnings disappearing after upgrade

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#3716]
## Description 
When upgrading from 0.63.4 to 0.63.8, accumulated ads earnings are reset to 0.

## Steps to Reproduce
   1. Install 0.63.4
   2. Trigger an advertisment
   3. Check notifications/earnings in rewards settings
   4. Initiate upgrade through about
   5. Re-check notifications/earnings

## Actual result:
<img width="623" alt="Screen Shot 2019-03-14 at 10 21 55 AM" src="https://user-images.githubusercontent.com/382109/54364318-0b6da900-4643-11e9-9b3e-416295a08ddd.png">

## Expected result:
Ad notification count and current earnings should be the same as before the upgrade.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
0.63.4/0.63.8

### Reproducible on current release:
Dev builds

### Additional Information
Attaching a before and after ledger state

[ledger_state_v0638.txt](https://github.com/brave/brave-browser/files/2966864/ledger_state_v0638.txt)
[ledger_state_v0634.txt](https://github.com/brave/brave-browser/files/2966866/ledger_state_v0634.txt)

**Comment by jsecretan** [comment]
Adding confirmations json as well

[confirmations-v0634.txt](https://github.com/brave/brave-browser/files/2967077/confirmations-v0634.txt)
[confirmations-v0638.txt](https://github.com/brave/brave-browser/files/2967078/confirmations-v0638.txt)

**Comment by arrangilligan** [comment]
![ver](https://user-images.githubusercontent.com/11330026/54391458-2a9d2280-46a5-11e9-893e-3b29fdf63940.jpg)

i downgraded and still no User ads?! and my bat missing ?

**Comment by jsecretan** [comment]
Unfortunately, a downgrade will not make the missing ad views appear.  However, we are going to bonus dev users for lost views when ad grants with the actual BAT are issued on or around the 5th of the month.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.63.20 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

- Verified the STR mentioned in the description
