### ISSUE TITLE
Playlist item throws error when it's close to the end

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#37162]
## Description 

When playing videos in the sidebar, media player throws error when it's close to the end
## Steps to Reproduce

   1. Add this video to playlist https://www.youtube.com/watch?v=pcKR0LPwoYs
   2. Play the item in the sidebar
 

<img width="382" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/98232e18-32a8-44fa-b3d0-c7fcc5c298b8">

## Actual result:

<img width="388" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/647247a6-a100-4989-a474-353b3ed98b0f">

## Expected result:
Should be played through

## Reproduces how often: 

Always

## Brave version (brave://version info)

Nightly

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.66.54 Chromium: 123.0.6312.86 (Official Build) nightly (64-bit)
-- | --
Revision | f5ab7d6aacb75e42f0687e4bbced3ff9a6c9c85e
OS | Windows 11 Version 23H2 (Build 22631.3374)
```

Reproduced the issue using the STR from https://github.com/brave/brave-browser/issues/37162#issue-2212221909  in `1.65.68 Chromium: 122.0.6261.111 (Official Build) nightly`


example | example 
----- | ----
<image width = "500" alt="image" src ="https://github.com/brave/brave-browser/assets/98358127/829beda5-2c4b-4d2c-b540-bb931bde56e5">|<image width = "500" alt="image" src ="https://github.com/brave/brave-browser/assets/98358127/93f28c64-28cf-4652-a64b-7ed7e823a67b">

1. Installed 1.66.54
2. launched Brave
3. opened brave://flags in a new tab
4. enabled  `#playlist`
5. navigated to the video https://www.youtube.com/watch?v=pcKR0LPwoYs in a new tab
6. clicked playlist icon in the url bar
7. added video to the playlist
8. clicked playlist icon in the sidebar
9. played the item in the sidebar

#### Confirmed no errors shown when it's close to the end.


https://github.com/brave/brave-browser/assets/98358127/52e0c203-f013-4726-9374-befef0b5b01d
