### ISSUE TITLE
Remove Swap from Filecoin Account details view

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#37167]
## Description: 
Remove Swap from Filecoin Account details view

## Steps to Reproduce 
  1. Create a new wallet
  2. Open Accounts tab and create Filecoin account
  3. Open Filecoin account 
  4. Shows Swap button which is not applicable for FIL tokens

## Actual result: 
<img width=300 src=https://github.com/brave/brave-browser/assets/17010094/db6da900-6b71-4bca-9742-81dc96bf38c3>

## Expected result:
Should only have Buy/Send/Deposit for FIL 

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
All

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?NA
- Is the issue reproducible on the latest version of Mobile Safari? NA

### Additional Information

cc: @StephenHeaps @nuo-xu

**Comment by kjozwiak** [comment]
The above requires `1.64.116` or higher for `1.64.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.4.1 running 1.64 (116)
- Verified steps from issue description
- Verified Swap option is not shown for any Filecoin Account (mainnet and testnet)
- Verified Buy is only shown on Filecoin Mainnet account and not shown in Filecoin Testnet account
- Encountered [#37289](https://github.com/brave/brave-browser/issues/37289)

https://github.com/brave/brave-browser/assets/17010094/d8b3029a-75ee-4e08-8fb4-c4e4186fe445
