### ISSUE TITLE
Brave crash caused because of `variations` information in Local State file.

### ISSUE THREAD

**Issue by TEMP-ad** [brave/brave-browser#37163]
## Description 

This is just to report Brave devs about what just happened to me, because I don't know if it will happen to anyone or what, or if it can be reproduced by anyone at Brave to fix it.

It seems like I fixed it myself, so I will update if anything new happens, but at the moment I am not getting crashes anymore.

The problem basically started when I tried to access my Outlook email after installing 1.66.40, from 1.66.36 I think, I remember I installed 1.66.36, because I knew it would fix toggles in settings, and I am not sure if I manually installed one yesterday, so I will say, between 1.66.36 and 1.66.40 something changed that caused my crash, if not it was 39, 38 or 37.

Anyway... when I wanted to access the email, I got the crash, then I removed the cookies from live.com, and it made it worst because now I got the crash when trying to log in as soon as I accepted my code from the authenticator.

Then I decided to make tests in a clean profile, and after I disabled all flags and extensions from my normal profile and all that, I saw that just copying and pasting my Local State file in the new profile will cause the crash when I tried to log in to Outlook, which means, the problem was in the Local State file.

After some minutes of removing lines, I found out it was removing `variations` information from the local state file that finally stopped the crashes. I first thought it was only `variations_compressed_seed` because that's what worked in my first test, I could get in Outlook but I still couldn't access other pages like Microsoft account page and other pages besides Outlook.com without getting a crash, so I removed every line that had variation on it and then it seems like now everything is working without a crash.

I don't know if this has anything to do with the crash, but I can see there is a difference in the old information I had in the Local State file and what was added by the browser today after I removed that information.

Most variation had the name `variations_safe_seed` and now they don't:

### This is how it used to look:

```
    "variations_safe_compressed_seed":"",
    "variations_safe_seed_date": "",
    "variations_safe_seed_fetch_time": "",
    "variations_safe_seed_locale": "",
    "variations_safe_seed_milestone": ,
    "variations_safe_seed_permanent_consistency_country": "",
    "variations_safe_seed_session_consistency_country": "",
    "variations_safe_seed_signature": "",
    "variations_seed_date": "",
    "variations_seed_milestone": ,
    "variations_seed_signature": "",
```

### And this is how it looks now:

```
    "variations_compressed_seed":"",
    "variations_country": "",
    "variations_crash_streak": ,
    "variations_failed_to_fetch_seed_streak": ,
    "variations_google_groups": {
        "Default": []
    },
    "variations_last_fetch_time": "",
    "variations_limited_entropy_synthetic_trial_seed": "",
    "variations_permanent_consistency_country": [ ],
    "variations_seed_date": "",
    "variations_seed_milestone": ,
    "variations_seed_signature":

```
So as you can see, there is no `safe_seed` anymore, but I am not sure if this has something to do with the crash, but it is the only difference I see, besides the whole signature and seed and all the encoded information that is being re-added by the browser once I removed these lines.

But maybe just renaming the lines and removing the `safe` or `safe_seed`, will fix it too.

So this is more like a report to inform Brave team to see if someone can reproduce it, just see if logging or accessing Outlook or Microsoft account page causes a crash and if nobody can reproduce this, well, I guess this issue will have to get closed.

Have a good day.

## How to (try to) reproduce the crash:
I found ways to reproduce the crash, if someone is not getting it but maybe wants to try to get it to see what is happening.

The simplest way to get a similar crash was by removing `"variations_signature"` first, restart browser, and it was crashing on trying to access outlook, reverting it back wouldn't fix it, and the only way to fix it was to remove the `"variations_seed_signature"` and then it worked without issues.

I also got the crash by renaming the properties from variations_compressed_seed to variations_safe_compressed_seed and variations seed signature to variations_safe_seed_signature, and remove everything else, when I went to local state file and tried to remove everything to be without 'safe' name, then I got the crash again.

I also noticed there was a duplicate variations_compressed_seed with the value `"variations_compressed_seed": "safe_seed_content"`, removed it and then the crashes stopped and didn't have to re-login or anything.

So maybe there are ways to reproduce crashes like this and find out why it is happening, at least there is a comment confirming there is or was a crash. I also updated to 1.66.43 to re-test this to see if I get the same crash. The crashes when doing all that act the same, even if I am manually manipulating stuff that could obviously cause the crash, but it seems there is some conflict in names or something around newest Nightly.

So this is the whole research/tests I did about this, and hope it will not be an issue in the future for other users.

## Brave version (brave://version info)

1.66.40 Chromium: 123.0.6312.58 (Official Build) nightly (64-bit) 
Windows 11 Version 23H2 (Build 22631.3296)

**Comment by Dreeam-qwq** [comment]
Same issue, I got crash when I tried to download artifacts from GitHub Action.
And I tried your solution, I deleted `"variations_safe_compressed_seed"` in local state file, then reopen Brave, the crashes disappear.

## Brave version (brave://version info)
1.66.39 Chromium: 123.0.6312.58 (正式版本) nightly （64 位）
Windows 11 Version 23H2 (Build 22631.3374)

**Comment by TEMP-ad** [comment]
I installed 1.66.44 and got crashes again when trying to go to Outlook.

Seems like just removing `"variations_seed_signature"` is enough as I explained in my last tests about this. This way nothing gets affected like cookies, and the browser will keep working like if nothing happened.

**Comment by TEMP-ad** [comment]
@rebron 

can you tag and talk to other Brave team members about this? seems like a horrible crash and whatever it is, it is getting worst, not better.

**Comment by TEMP-ad** [comment]
Yeah, I created a new user data with `--user-data-dir=` and just logged in Outlook, restarted browser and it crashed.

So it seems like the problem got worst since even a totally new user data with no extensions, flags or any setting changed or anything but opening Outlook as soon as it opened is causing the crash.

**Comment by TEMP-ad** [comment]
I also found that if the problem is the variations, if I remove the `"variations_seed_signature"` from Local State file, and then I run Brave with `--variations-server-url=""`, the crash won't happen, on restarts since variations information will not get updated or anything.

Of course, no features will be turned on or disabled automatically by the variations (https://griffin.brave.com/), but I can turn them on and off through the flags if I need it or whatever.

Of course, if I open Brave without emptying the vriation server url, then it will start crashing on restart, but this is better than having to remove the same line from Local State file.

But it is more and more clear something in variations 'seed' is causing the issue.

**Comment by TEMP-ad** [comment]
Ok, so I was testing further, and it seems the crash is happening because of `#brave-ads-should-always-run-brave-ads-service` flag being enabled by variations.

I thought, if the problem is the variants, must be a feature being enabled by it, and set to disable one by one and then default, restarted twice until I didn't get more crashes trying to go to Microsoft account... for whatever reason it was working fine in Outlook, but the crash happened when trying to access Microsoft account link from outlook.

So... it seems even if I don't use Brave ads, I still get affected by it.

**Comment by TEMP-ad** [comment]
Closing this issue in favor of https://github.com/brave/brave-browser/issues/37199. Hope this gets fixed soon, but whoever has these issues, just disable `#brave-ads-should-always-run-brave-ads-service` in brave://flags and see if that fixes the crashes.
