### ISSUE TITLE
Make it possible for devs to run react dev tools extension for brave's ui

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#37166]
Full guide for react dev tools extension:
1) Build patched extension
   - `git clone -b enable_on_chrome https://github.com/supermassive/react.git`
   - `cd react`
   - `yarn install`
   - `yarn build-for-devtools`   (takes a while)
   - `yarn --cwd packages/react-devtools-extensions build:chrome` 
   - `cd ./packages/react-devtools-extensions/chrome/build/unpacked` use that folder as extension location below
1) Run brave and enable `brave://flags/#extensions-on-chrome-urls`. Restart brave.
1) Go to `brave://extensions/`
1) Enable `Developer mode` in top right corner
1) Click `Load unpacked` and pick folder from step 1.

**Comment by bsclifton** [comment]
@supermassive should we close this after https://github.com/brave/reviews/issues/1566 was closed?
