### ISSUE TITLE
[Wallet] Do not wait for pending sign-message requests when initializing panel

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#37174]
## Description 

We should show the panel UI as soon as possible

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.94 Chromium: 125.0.6422.112 (Official Build) beta (64-bit)
-- | --
Revision | 3e4d210c91412b82ad8cffca556b12bbe40ff962
OS | Windows 11 Version 23H2 (Build 22631.3593)

- Verified steps from [brave/brave-core#22829](https://github.com/brave/brave-core/pull/22829)
- Verified able to SIWE on `https://login.xyz`
- Verified able to SIWE with resources on `https://metamask.github.io`
- Verified all errors when SIWE on ` https://bbondy.github.io/eth-manual-tests/request.html`

https://github.com/brave/brave-browser/assets/17010094/5081d31b-e792-446a-8d50-73f053b1dea8
