### ISSUE TITLE
Dark theme causes filters to look disabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#37173]
## Description 

Dark theme causes filters to look disabled

## Steps to Reproduce

   1. Set browser theme to dark
   2. Open Wallet and click on portfolio filters
   3. Select any dropdown, looks disabled but can still select to change filters

## Actual result:

![brave_FhtRY5GBl9](https://github.com/brave/brave-browser/assets/17010094/5fac141d-a06a-43b9-8a74-31e9c6efba1c) | ![brave_hdlpqA9gHF](https://github.com/brave/brave-browser/assets/17010094/624e2801-9533-4f08-9600-b863613dd3ea)
-- | --

## Expected result:
Better looking UI on dark theme

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @kleantzogu @Douglashdaniel @josheleonard

**Comment by Douglashdaniel** [comment]
I think this is a `leo` issue since this is using the `Dropdown` component directly from `@brave/leo/react/dropdown`. 
cc: @fallaciousreasoning @petemill

**Comment by fallaciousreasoning** [comment]
This looks like it could be using the colors from the light theme - if you add a `data-theme="dark"` to the body (or any parent element of the dropdown) does it look better?

This is how the component should look in dark mode:
![image](https://github.com/brave/brave-browser/assets/7678024/b412195e-db75-4dd9-bb0d-4ab3e0568529)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.92 Chromium: 125.0.6422.76 (Official Build) beta (64-bit)
-- | --
Revision | d751d2edf40b466560aaeecc4c4919041f41c20d
OS | Windows 11 Version 23H2 (Build 22631.3593)

- Verified steps from [brave/brave-core#23195](https://github.com/brave/brave-core/pull/23195)
- Verified Portfolio filters are properly visible when browser is set to Dark theme

https://github.com/brave/brave-browser/assets/17010094/6a59d26e-162d-43b6-a037-7e4cd5ea51ea
