### ISSUE TITLE
Opening the Web-IDE in GitLab crashes the browser

### ISSUE THREAD

**Issue by 1muen** [brave/brave-browser#37170]
## Description 

Opening the Web-IDE in GitLab crashes the browser

## Steps to Reproduce

   1. go to https://gitlab.com/fdroid/fdroidclient or any other gitlab instance or repo, also reproducible on a selfhosted version. Doesnt matter if your logged in or not.
   2. open the web ide by pressing .
   3. browser crashes and all windows are closed

## Actual result:

browser crashes and all windows are closed

## Expected result:
opening the web ide in a new tab

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.66.39 Chromium: 123.0.6312.58 (Official Build) nightly (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? -
- Can you reproduce this issue with the beta channel? -
- Can you reproduce this issue with the nightly channel? YES

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? NO

**Comment by rebron** [comment]
@1muen Can you update to 1.66.45 and higher and let us know if you're still experiencing the crash? We had a separate crash fix but could be effecting your use case as well.
