### ISSUE TITLE
Crash when clicking on a Brave Talk link from Google calendar

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#37178]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.66.39 Chromium: 123.0.6312.58
Operating System: Mac OS X 14.4.1

URL (if applicable) where crash occurred:

Can you reproduce this crash? Yes (repro'd twice)

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Click on a Brave Talk link from Google Calendar
2. Link opens in a new tab 
3. Browser crases

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/52b80300-686b-ba0b-0000-000000000000
Crash ID: crash/bbb90300-686b-ba0b-0000-000000000000

**Comment by LaurenWags** [comment]
Reproduced with 

```
Brave	1.66.39 Chromium: 123.0.6312.58 (Official Build) nightly (x86_64) 
Revision	c97f54ae410d359f05a67d06c07e695305970a0d
OS	macOS Version 13.6.4 (Build 22G513)
```

**Comment by iefremov** [comment]
It seems this one was fixed at some point, doesn't repro after cr123
