### ISSUE TITLE
[Wallet] Refactor persisted portfolio collapsed groups to not use redux

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#37179]
## Description 

We can use the `useLocalStorage` hook instead of syncing local-storage with redux.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.90 Chromium: 124.0.6367.82 (Official Build) beta (64-bit)
-- | --
Revision | 803a4c629341791205b744969c48b8da9f2cfa4d
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22836](https://github.com/brave/brave-core/pull/22836)
- Verified collapsing portfolio accounts and network grouping works as expected without any regression

https://github.com/brave/brave-browser/assets/17010094/1142d49a-9c52-43bc-a14a-8068e06b4cc4
