### ISSUE TITLE
[i18n] source string review

### ISSUE THREAD

**Issue by AndyAnds265** [brave/brave-browser#37187]
Can you please confirm if this should be Withdraw Nonce Account or Withdraw `From` Nonce Account?

String key:
Withdraw Nonce Account
<img width="444" alt="Screenshot 2024-03-28 at 1 06 34 PM" src="https://github.com/brave/brave-browser/assets/19779922/b2e044d0-2b78-45e2-a053-198738f13471">

**Comment by StephenHeaps** [comment]
@AndyAnds265 I think including `From` is fine. Here's the definition of the instruction from Solana:

Instruction name:
> WithdrawNonceAccount (u64)

Instruction description:
> Withdraw funds from a nonce account

https://docs.rs/solana-program/latest/solana_program/system_instruction/enum.SystemInstruction.html#variant.WithdrawNonceAccount
