### ISSUE TITLE
[i18n] Source String Correction

### ISSUE THREAD

**Issue by AndyAnds265** [brave/brave-browser#37182]
A few times in the iOS strings, the App Store from iOS is incorrectly written.

The formal name for Apple's store is `App Store`, with a space. In the code, we write Appstore. 

<img width="664" alt="Screenshot 2024-03-28 at 12 29 55 PM" src="https://github.com/brave/brave-browser/assets/19779922/120d0740-c8d6-4d07-9f0f-d99b182ad0bc">

Two example string keys:

- Link your Appstore purchase to your Brave account to use Leo on other devices.
- Could not connect to Appstore, please try again later.

**Comment by AndyAnds265** [comment]
See the formal writing of the store here:

![Screenshot 2024-03-27 at 12 23 40 PM](https://github.com/brave/brave-browser/assets/19779922/ef50d88b-78ea-4ecb-9dce-93379caf03b9)

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.5
Brave build: 1.66 (95)
BraveCore: 1.66.95 (124.0.6367.91)
```
---------------------------

**STEPS:**
1. Launch Brave `Beta` or `Nightly`
2. Three-dot menu > Settings
3. Leo > Go Premium > *Verify*

**ACTUAL RESULTS:**
- Verified that `App Store` is spelled correctly: `Could not connect to App Store, please try again later.`
- Verified 

---------------------------

|Repro|Fix|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/bc52f4ce-375e-4271-ac46-069158ef8b03) | ![2](https://github.com/brave/brave-browser/assets/128532965/fe76b265-c703-417e-b8c0-482cfc8565bd) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/c48af0d3-d1b2-44fb-a692-90f8c45cf3f4) | ![2]() |
