### ISSUE TITLE
"Summarize this page" button not aligned in Leo chat [iOS 15]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#37185]
## Description: 
"Summarize this page" button not aligned in Leo chat

Only iOS 15 devices

## Steps to Reproduce 
  1. Fresh install
  2. Enable Leo
  3. Observe chat window

## Actual result: 
![IMG_0369 2](https://github.com/brave/brave-browser/assets/17885425/f8919526-ebed-4057-ad72-4dd026988224)

## Expected result:
Buttons should be horizontally aligned

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

## Brave Version: 
1.63.x

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
IPhone, iPad OS version 15.x

**Comment by kylehickinson** [comment]
Closing this as iOS 15 will no longer be supported in 1.67
