### ISSUE TITLE
Hide Zero Balance Tokens in Account Details

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#37194]
## Description 

We need to hide `Zero` balance tokens in the `Account Details` view

![Screenshot 20](https://github.com/brave/brave-browser/assets/40611140/7ec3c185-17a7-4b93-a2ba-a9d3d6f9de76)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.97 Chromium: 124.0.6367.118 (Official Build) beta (64-bit)
-- | --
Revision | 94909f2aaefd7a8137c8b4fa27235378e79231e3
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22848](https://github.com/brave/brave-core/pull/22848)
- Verified zero balance tokens are not shown in Account details views

https://github.com/brave/brave-browser/assets/17010094/d1126bd1-29da-444a-8165-b9f0649dc2f5
