### ISSUE TITLE
Update hamburger menu background color.

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#37190]
## Description 

Just realized that our browser hamburguer menu's background color is now showing with white background (on light mode at least). 

It should match the chrome color. Meaning the color on the background of the whole URL bar, bookmarks, sidebar. 

Same for all submenues too

https://www.figma.com/file/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?type=design&node-id=229%3A18699&mode=design&t=ZlHu0vMmWVK2aaC7-1

## Actual result:

<img width="323" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/b3e8a62d-dfdb-4d2a-a51d-6032024e1c44">

## Expected result:
<img width="416" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/66e34449-d8a1-4e01-b258-73e5c7135a1e">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.66.54 Chromium: 123.0.6312.86 (Official Build) nightly (64-bit)
-- | --
Revision | f5ab7d6aacb75e42f0687e4bbced3ff9a6c9c85e
OS | Windows 10 Version 22H2 (Build 19045.4239)
```

## `Dark` mode

"hamburger" menu

`History` -> 

`Bookmarks` ->

`More tools` ->

`Help` ->

## `Light` mode

"hamburger" menu

`History` -> 

`Bookmarks` ->

`More tools` ->

`Help` ->

**Comment by TheAresjej** [comment]
@aguscruiz, @sangwoo108 I really like this change (https://github.com/brave/brave-core/pull/22850), but I saw that it was revoked (https://github.com/brave/brave-core/pull/23047) due to complications with custom themes. (https://github.com/brave/brave-browser/issues/37532) Would it be possible to restore this change (since the code is already written anyway if I understand correctly) and simply introduce some option to check if the user has installed a custom theme? 😃

**Default theme** - colours enabled
![image](https://github.com/brave/brave-browser/assets/19390797/cb82e97f-3cdf-42a5-8180-1830524b09e6)

**Custom user theme** - colour scheme disabled

**Comment by sangwoo108** [comment]
Hi, @TheAresjej . Yes, theme was one of the reasons, but moreover we had bad sideeffect of the patch. Other UI components were affected by the patch but we couldn't isolate the change from them. We're still looking into it but not sure if it's possible.

**Comment by LaurenWags** [comment]
Changing to `release-notes/exclude` as this was reverted cc @rebron @kjozwiak

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.66.94 Chromium: 124.0.6367.91 (Official Build) beta (64-bit)
-- | --
Revision | 1574096f9d2bcb69c3654cb4437217121ee9600b
OS | Windows 11 Version 23H2 (Build 22631.3527)
```


#### Steps:

1. installed 1.66.54
2. launched Brave
3. started off in Dark mode
4. clicked on the so-called hamburger menu
5. noted its color, relative to the background color of the toolbar/URL bar, etc. (matches, as expected)
6. clicked on the various submenus (noted below)
7. repeated the steps above, using Light mode
8. Confirmed the colors of the app menu (main, flyouts, etc.) match their respective Dark and Light colors (toolbars, URL bar, etc.)


example | example |example | example 
----- | ------ | ----- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/f0bab6ee-19f7-4120-af0b-912bc20a9439)|![image](https://github.com/brave/brave-browser/assets/98358127/0587def3-6670-4e13-8e3d-a6036524b097)|![image](https://github.com/brave/brave-browser/assets/98358127/d5012e2e-19ec-4b24-9b1a-0c6afc7b2fbb)|![image](https://github.com/brave/brave-browser/assets/98358127/3c04ec47-164f-4868-b5a8-6ae0bf22ef69)


History| Bookmarks| Show Sidebar| Help 
----- | ----- | ----- | -----  
![image](https://github.com/brave/brave-browser/assets/98358127/1bdc9338-4b0b-4054-9cf2-422d48bd4bed)|![image](https://github.com/brave/brave-browser/assets/98358127/5f35a311-cf14-47c7-9ab1-b453eb57e1b3)|![image](https://github.com/brave/brave-browser/assets/98358127/42c4da6d-853f-4bfa-9e34-836110471f58)|![image](https://github.com/brave/brave-browser/assets/98358127/c125af33-4553-4213-9056-6b25bef3c60a)|
![image](https://github.com/brave/brave-browser/assets/98358127/385a2e92-5757-4a33-b125-524045b7a3e8)|![image](https://github.com/brave/brave-browser/assets/98358127/e981a773-cfac-4e50-bdcc-f413e24a039c)|![image](https://github.com/brave/brave-browser/assets/98358127/796cc828-a3c0-4654-a7c6-bb3afb6b9e3d)|![image](https://github.com/brave/brave-browser/assets/98358127/c0eddf32-c25b-47bb-8353-2cadb98323a6)

**_Private window_**
-------
Hamburger menu| Bookmarks| Show Sidebar| Help 
----- | ----- | ----- | -----  
![image](https://github.com/brave/brave-browser/assets/98358127/d1af973e-a545-427b-9196-aff6d6ff70f9)|![image](https://github.com/brave/brave-browser/assets/98358127/f4b243b8-49f1-40b1-9d69-032a29ede029)|![image](https://github.com/brave/brave-browser/assets/98358127/8a26fc20-459e-4222-94fb-a23af416e0f4)|![image](https://github.com/brave/brave-browser/assets/98358127/71fddefe-422a-42a2-a2ee-dc41edf8b506)

**_Private window with Tor_**
------
Hamburger menu| Bookmarks| Show Sidebar| Help 
----- | ----- | ----- | -----  
![image](https://github.com/brave/brave-browser/assets/98358127/485dd8cb-2cf1-4140-806f-1968e3934d0d)|![image](https://github.com/brave/brave-browser/assets/98358127/b9266656-f234-4655-add2-8f18dba0a930)|![image](https://github.com/brave/brave-browser/assets/98358127/df838a09-738b-495d-83b0-97f8104d7399)|![image](https://github.com/brave/brave-browser/assets/98358127/5a45886f-80ec-40fc-be42-b9ec1457d63b)

**_Guest profile_**
------
<details>
![image](https://github.com/brave/brave-browser/assets/98358127/6023af84-7246-4c39-8833-a20a1907d53f)
![image](https://github.com/brave/brave-browser/assets/98358127/fb992036-af03-44de-b1fc-ed5c0d196f0a)
![image](https://github.com/brave/brave-browser/assets/98358127/be66641d-e63e-4cc0-90ed-7a382978c044)

</details>
