### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by lonewolf0708** [brave/brave-browser#37191]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.66.43 Chromium: 123.0.6312.86
Operating System: Windows NT 10.0.22631

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Go to settings
2. Click "About Brave"
3. Brave crashes

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/c62f0400-686b-ba0b-0000-000000000000

**Comment by rebron** [comment]
Closing as duplicate. Should be fixed with https://github.com/brave/brave-core/pull/22842
@lonewolf0708 If you update to 1.66.45 and higher should be good. Let us know if that's not the case.
