### ISSUE TITLE
Guest window shows it as private tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#372]
![image](https://user-images.githubusercontent.com/17010094/41553967-55c4ec7c-7301-11e8-946d-eeb5b8d7c9d9.png)

**Comment by bsclifton** [comment]
@srirambv do you have more information about this? I'm guessing you can be logged in as a user (is that still enabled?) and if you chose to open a new guest window, it's showing as a private tab?

**Comment by srirambv** [comment]
Sorry missed the notification on this issue, but wasn't sure if its supposed to work like a private tab or should have its own custom Guest tab info.

**Comment by simonhong** [comment]
Guest window is also using private profile so, I think  its theme should be same as private tab.

**Comment by srirambv** [comment]
Closing as guest window shows private window theme as per https://github.com/brave/brave-browser/issues/372#issuecomment-471089993
