### ISSUE TITLE
Follow up to 35978 - Cover Rewards panel when TOS notice is displayed

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#37205]
## Description 

Found while testing #35978
Cover Rewards panel when TOS notice is displayed

## Steps to reproduce 

   1. Follow the STR from https://github.com/brave/brave-browser/issues/37011#issue-2202874648
 

## Actual result 

background of panel isn't blurry, so balance and ads earnings can be seen:

Contribution view | Summary view
--- | ---
![Screenshot_20240329_160120_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/41807d0a-bc03-4f79-b6a1-06944450cce4) | ![Screenshot_20240329_160055_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/42c0c7df-9ed5-402b-b993-5c91ea7d88a2)

## Expected result
background of panel should be blurry like brave://rewards page:

![Screenshot_20240329_155906_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/b02134a4-445a-462f-b2a8-127b8647ac69)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Not sure

## Device details
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet):All
   - Android version: 12
   
## Brave version
1.65.95

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @deeppandya @Miyayes

**Comment by deeppandya** [comment]
@Miyayes @GeetaSarvadnya we can't do blur background on Android because of the platform limitations. It would work on low end devices. Should we change figma as well ? Based on the design in figma, we should be able to see the background details on the panel.

**Comment by kjozwiak** [comment]
The above requires `1.65.110` or higher for `1.65.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung galaxy version 12` running `Bravemonoarm.apk_1.65.112`

brave://rewards | BR panel
------------------|-----------
![Screenshot_20240416_170401_Brave](https://github.com/brave/brave-browser/assets/38657976/8dc85ded-d33d-4c45-860a-c3405a49c2c6) | ![Screenshot_20240416_170409_Brave](https://github.com/brave/brave-browser/assets/38657976/4c234516-8409-42a5-804f-69d1e2b1e2ba)
