### ISSUE TITLE
Update the ToS update notice text message on the BR panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#37204]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/35978
Update the ToS update notice text message on the BR panel
## Steps to reproduce 

   1. With a new profile, enable Rewards.
   2. Close the browser.
   3. Use Charles Proxy to simulate incrementing the "tosVersion" field of the Rewards parameters endpoint.
   4. Restart the browser, confirm Charles Proxy rewrite is being used
   5. Verify that the ToS update notice is displayed on the Rewards page, and the Rewards panel.
   6. Observe the ToS update notice via BR panel, ToS update notice is not same as Desktop

## Actual result 
Update the ToS update notice text message on the BR panel

![Screenshot_20240329_121959_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/ddb1919e-8bfc-47da-95d3-e799d3f5bef8)

## Expected result

Update to version of text that says “if you do not agree”

![image](https://github.com/brave/brave-browser/assets/38657976/df3de826-4fdb-4b0d-b1e2-63a0922506ae)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Not sure

## Device details
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet):All
   - Android version: 12
   
## Brave version

1.65.96
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

@deeppandya @brave/qa-team @Miyayes

**Comment by kjozwiak** [comment]
The above requires `1.65.110` or higher for `1.65.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.65.112`

- Confirmed that ToS update notice message is same on both brave://rewards and BR panel

brave://rewards | BR panel
-----------------|--------------
![Screenshot_20240416_162935_Brave](https://github.com/brave/brave-browser/assets/38657976/8e01b3ed-1b43-4db2-b94c-4f85ff3fcea7) | ![Screenshot_20240416_162959_Brave](https://github.com/brave/brave-browser/assets/38657976/25451aef-2cac-4603-8769-af1bdb2f865d)
