### ISSUE TITLE
Change the “reset” hyperlink to be gray on ToS update notice via BR Panel for both connected and nonconnected users

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#37206]
## Description 

The issue is identified by @Miyayes 

The change suggested by @Miyayes via https://bravesoftware.slack.com/archives/CB0KCRCQN/p1711700278801349?thread_ts=1711029956.638829&cid=CB0KCRCQN

Change the “reset” hyperlink to be gray on ToS update notice via BR Panel for both connected and nonconnected users

## Steps to reproduce 

   1. NA

## Actual result 

non connected user | connected user 
-----------------------|-------------
![Screenshot_20240329_121959_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/f945aa87-a51d-4620-9cb4-f411a8a3e87a) | ![Screenshot_20240329_160055_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/37fbc737-ec2b-41b5-a1ae-15050f5b9f43)

## Expected result

Change the “reset” hyperlink to be gray on ToS update notice via BR Panel, same as brave://rewards page Tos notice

non connected user | connected user 
-----------------------|-------------
![Screenshot_20240329_121008_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/ba9eeaed-7ab2-446b-b79a-233524c69a96) | ![Screenshot_20240329_155906_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/258dd63a-8050-470f-969b-5a04997278c4)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Not sure

## Device details
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 12
   
## Brave version

1.65.95
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @Miyayes @deeppandya

**Comment by kjozwiak** [comment]
The above requires `1.65.110` or higher for `1.65.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.65.112`

- Confirmed that the `reset` hyperlink is gray on Tos update notice on the BR panel 

brave://rewards | BR panel
-----------------|--------------
![Screenshot_20240416_162935_Brave](https://github.com/brave/brave-browser/assets/38657976/8e01b3ed-1b43-4db2-b94c-4f85ff3fcea7) | ![Screenshot_20240416_162959_Brave](https://github.com/brave/brave-browser/assets/38657976/25451aef-2cac-4603-8769-af1bdb2f865d)
