### ISSUE TITLE
Crash Report : Too many Status_Access_voilation

### ISSUE THREAD

**Issue by anirugu** [brave/brave-browser#37210]
I am opening multiple tab (6,7) and once and once I am switch to those tab, crash happen

IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.63.162 Chromium: 122.0.6261.69
Operating System: Windows NT 10.0.19045

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/0a010700-686b-ba0b-0000-000000000000

**Comment by rebron** [comment]
@anirugu Can you update to our latest to see if you're still experiencing this crash. 1.64.113.

**Comment by anirugu** [comment]
I tried to update and it failed after the update. The Id of crash is 
"Local Crash Context:	4fd837b5-c9d8-40e7-8f42-bd038b303df9"

**Comment by iefremov** [comment]
Fixed in https://github.com/brave/brave-core/pull/22998
