### ISSUE TITLE
Follow up of #35978 - Self-custody invite displays on top of ToS update notice in the Rewards panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#37211]
## Description 

Follow up of #35978 - Self-custody invite displays on the Rewards panel
## Steps to reproduce 

   1. Follow the STR from https://github.com/brave/brave-browser/issues/37024#issue-2203185817
  

## Actual result 

Self-custody invite displays on the Rewards panel

brave://rewards | BR panel
------------------|----------
![Screenshot_20240329_194005_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/65ced7e6-efb1-4eac-a6c8-16897d05145a) | ![Screenshot_20240329_194029_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/f7f8e42d-a4c4-4893-a08f-eb922fb0e736)

## Expected result
The TOS update notice should be shown on both brave://rewards page and BR panel

## Issue reproduces how often 
Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Not sure

## Device details
   - Install type (ARM, x86):All
   - Device type (Phone, Tablet, Phablet):All
   - Android version: 12
   
## Brave version
1.65.59

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @deeppandya @Miyayes

**Comment by GeetaSarvadnya** [comment]
The issue is reproducible on `Samsung Galaxy Tab A7 version 12` running `Bravemonoarm64.apk_1.65.102`

brave://rewards | Panel
--- | --- 
![Screenshot_20240405-151835_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/6d85cc41-a05d-47e9-8465-a72ddcca0443) | ![Screenshot_20240405-151847_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/7ed4a0f5-4881-4b63-95e2-a8fe1f184a09)

**Comment by kjozwiak** [comment]
The above requires `1.65.110` or higher for `1.65.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.65.112`

- Confirmed that ToS update notice is shown on the BR panel

brave://rewards | BR panel
-----------------|--------------
![Screenshot_20240416_162935_Brave](https://github.com/brave/brave-browser/assets/38657976/8e01b3ed-1b43-4db2-b94c-4f85ff3fcea7) | ![Screenshot_20240416_162959_Brave](https://github.com/brave/brave-browser/assets/38657976/25451aef-2cac-4603-8769-af1bdb2f865d)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy Tab A7 version 12` running `Bravemonoarm64.apk_1.65.114`

Confirmed that ToS update notice is shown on the brave://rewards and BR panel both

brave://rewards | Panel
--- | --- 
![Screenshot_20240417-175459_Brave](https://github.com/brave/brave-browser/assets/38657976/f2b8e9e3-699f-45a8-84b9-89c0fcf5b715) | ![Screenshot_20240417-175510_Brave](https://github.com/brave/brave-browser/assets/38657976/d75a08ff-9dcd-4805-a24e-5e351e842a0c)
