### ISSUE TITLE
Network activity remains stale when loading a page for the first time

### ISSUE THREAD

**Issue by alessandromrc** [brave/brave-browser#37226]
## Description 
Brave doesn't seem to create any network traffic and remains stale for some time before sending anything.

## Steps to Reproduce

   1. Open Brave.
   2. Go to something like google.com and analyze the traffic using Wireshark.
   3. Notice the fact that no packets get sent for some time (stales).
   4. The page load time gets really annoying.

## Actual result:

https://github.com/brave/brave-browser/assets/66976091/38485ce1-1863-4609-8808-79f3d9ab2e5d

## Expected result:
The expected result would be Brave directly creating a connection to the website and instantly loading it up.

## Reproduces how often: 

This happens everytime with practically every website I open up.

## Desktop Brave version:

```
Brave: 1.64.113 Chromium: 123.0.6312.86 (Official Build) (64-bit)
Revision: 4e20399c0c5e3cbbb80dd1119122400e08259feb
OS: Windows 11 Version 23H2 (Build 22631.3155)
```
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?

Disabling Shields does nothing at all.

- Does the issue resolve itself when disabling Brave Rewards? 

Like Shields it doesn't change anything.

- Is the issue reproducible on the latest version of Chrome? 

The issue seems to be present within the last version of Chrome too.

## Miscellaneous Information:

If anything more is needed, just ask, I don't think there's much more I could share already.

**Comment by Zeenobit** [comment]
I'm experiencing this issue recently too (as of last few weeks) and it's driving me crazy! :(

- I've noticed this happening most often on "cold start" of the browser, or a profile (i.e. opening a new browser window with no previous existing windows).

- I've also noticed this happening most often with Google's family of websites, such as YouTube or Gmail.

I kept thinking it might be an issue with Google fighting the ad-blocker because of the latter point until I found this issue.

**Comment by alessandromrc** [comment]
> I'm experiencing this issue recently too (as of last few weeks) and it's driving me crazy! :(
> 
> 
> 
> - I've noticed this happening most often after the "cold start" of the browser, or a profile (i.e. opening a new browser window with no previous existing windows, opening a new private window, or opening a new profile window).
> 
> - I've also noticed this happening most often with Google's family of websites, such as YouTube or Gmail.
> 
> - I've also experienced that disabling shields does not resolve the issue.
> 
> 
> 
> I kept thinking it might be an issue with Google fighting the ad-blocker because of the latter point until I found this issue.

Nice to see that I am not alone, sadly I think the problem comes from the upstream since Chromium itself has this issue too in my case... Are you able to reproduce it too on Chromium?
