### ISSUE TITLE
Uphold Wallet Support 

### ISSUE THREAD

**Issue by hollons** [brave/brave-browser#3722]
## Description 

Supporting Uphold wallets
A sandbox widget was created working with Uphold to allow users to;
Add funds
Manage wallet/Claim wallet

This sandbox can be triggered as part of either of the flows and automatically triggers signing up with Uphold, or triggers cc-based (fiat) transfer functionality.

PDF flow for Uphold flow (Add Funds with KYC)

This functionality is already available as per old specification. This specification has changed based on the requirements in this document, however claiming wallet and add funds flows remain the same.

**Comment by mandar-brave** [comment]
@NejcZdovc @alexwykoff @jsecretan moving this to a P1; umbrella issue

1. Support for Uphold connect widget on user wallet
2. Support states for wallet and respective UI/UX
3. Support transactional changes once wallet is claimed
4. Manage exceptions via Uphold API

**Comment by NejcZdovc** [comment]
closing as uphold was implemented
