### ISSUE TITLE
[iOS] - Export Skus Internals

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#37222]
## Description: 
- To better help backend with debugging and the SkusSDK team, we should export Skus-Internals so we can view the Skus-State and save it to a file or export it or copy it easily.

## Brave Version: 
- 1.64.x+

### Device details: 
- Any

**Comment by kjozwiak** [comment]
The above requires `1.64.118` or higher for `1.64.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.5
- iPad Air / iPadOS 16.7.2
Brave build: 1.64 (123)
BraveCore: 1.64.123 (123.0.6312.122)
```

Filed follow-up issue #37526
---------------------------

**STEPS:**
1. Launch Brave 
2. Purchase `VPN` subscription
3. Purchase `Leo` subscription
4. Go to `brave://skus-internals/`
5. Use `Fetch VPN state`, `Fetch Leo state` and `Fetch SKUs state`
6. Use `Copy` to copy to Google Docs, for example > *Verify*
7. Use `Download` to save it to file > *Verify*

**ACTUAL RESULTS:**
- Verified that `Copy` and `Download` buttons are present on the `brave://skus-internals/` page 
- Verified that `Copy` and `Download` are working as expected and the SKUs info can be copied to a buffer or saved to a file

---------------------------

*iPhone*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/fc5f3080-1028-42b7-86ee-0f302038d2bb) | ![2](https://github.com/brave/brave-browser/assets/128532965/313e0417-6b66-4b3b-9e45-c4977decaf2e) | ![3](https://github.com/brave/brave-browser/assets/128532965/f7916609-c1a0-4c35-a715-27cc7be6e1dd) | ![4](https://github.com/brave/brave-browser/assets/128532965/c40cfa30-1391-4ac8-8e57-a37dbfa9a516) |

*iPad*

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/cf095def-2473-4bc6-9fdc-b29921f41e98) | ![2](https://github.com/brave/brave-browser/assets/128532965/33513def-acf7-4b64-b2a0-c1838eadbb72) | ![3](https://github.com/brave/brave-browser/assets/128532965/3de01a97-ce06-4356-85fd-9efb4eb96c71) |
