### ISSUE TITLE
follow-up to#36571 Update content settings page name to `braveContent` 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#37237]
## Description 

Current page address is brave://settings/brave-content.
Change to brave://settings/content to maintain consistency with other settings pages.

## Steps to Reproduce

   1. Go to brave://settings/brave-content in 1.65.x and higher
   2. Notice address, should be brave://settings/content
   
## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.65.x and higher

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by sangwoo108** [comment]
Actually, I ran into this but chrome:// is redirecting chrome://content to content setting and privacy. I think overriding that might break links we don't know.

**Comment by rebron** [comment]
We should still change to camel case then, so brave://settings/braveContent

**Comment by sangwoo108** [comment]
Do you want me to change brave://settings/leo-assistant too?

**Comment by rebron** [comment]
> Do you want me to change brave://settings/leo-assistant too? - if it's needed, it will be handled in separate issue as there could be placess depend on it.
We can handle separately with a different issue.

**Comment by kjozwiak** [comment]
The above requires `1.65.110` or higher for `1.65.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.65.110 Chromium: 124.0.6367.29 (Official Build) (x86_64) 
Revision	6271fdd3c799c0db71c1e6ca8c83888a7bbbfbd2
OS	macOS Version 13.6.6 (Build 22G630)
```
