### ISSUE TITLE
Thanks for reporting message won't disappear

### ISSUE THREAD

**Issue by GKid94** [brave/brave-browser#37230]
## Description 
The Thanks for reporting website message takes a long time to disappear

## Steps to Reproduce
   1.  Open a website
   2.  Open the three lines More options button on the browser top right
   3.  Go to Help, Report broken website and submit

## Actual result:
Message stays for a while and you can't close it

## Expected result:
For the message to disappear quicker

## Reproduces how often: 
Every time

## Brave version (brave://version info)
1.64.113 Chromium: 123.0.6312.86 (Official Build) (64-bit)]

## Version/Channel Information:
Stabe Yes
Beta Don't know
Nightly Don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Don't know

## Miscellaneous Information:
/
![Screenshot 2024-03-31 213007](https://github.com/brave/brave-browser/assets/18757054/8783b15b-6456-4274-98c3-f1644b7d1c60)

**Comment by ShivanKaul** [comment]
We should also add a X (close) button to the modal.
