### ISSUE TITLE
cookie consent banner blocking breaks https://whenavailable.com/

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#37241]
STR:

1. go to https://whenavailable.com/plan
2. note you can't enter any inputs
3. go to brave://settings/shields/filters and uncheck 'easylist cookie'
4. go back to https://whenavailable.com/plan, note you can click thru the cookie consent dialog, and then the site works

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/80277ba98  Will resolve it
