### ISSUE TITLE
Update GuardianConnect to 1.9.1

### ISSUE THREAD

**Issue by iccub** [brave/brave-browser#37248]
It adds privacy manifest file and some bugfixes

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.5
Brave build: 1.66 (108)
BraveCore: 1.66.108 (125.0.6422.41)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Purchase / Restore `VPN` subscription > *Verify*
3. Enable / Disable `VPN` > *Verify*
4. Change VPN `Region` > *Verify*

**ACTUAL RESULTS:**
- Verified that `VPN` is working as before:
  - able to purchase new and restore existing subscription
  - able to enable and disable VPN
  - able to change the region

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/f2f034a1-eb9f-4282-8d01-478e3387e2d9) | ![2](https://github.com/brave/brave-browser/assets/128532965/46900fae-1d7b-449a-8852-7cabeb5474e2) | ![3](https://github.com/brave/brave-browser/assets/128532965/5a517e43-0cc1-4850-a2c8-10e93932b1e1) | ![4](https://github.com/brave/brave-browser/assets/128532965/b7f4bf8c-b715-421c-8d43-031b57571ae7) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/818833e8-6110-4dc4-8e29-965808bacd13) | ![2](https://github.com/brave/brave-browser/assets/128532965/031fda59-f22a-4e17-8444-7e63887ae910) | ![3](https://github.com/brave/brave-browser/assets/128532965/17deab78-c52d-4e63-8249-cd8cbcea8947) | ![4](https://github.com/brave/brave-browser/assets/128532965/d8975c09-f5b0-463c-a766-83d1de8b63fb) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/8705d1c0-5ffd-44de-ae62-f73cb1cf847d) | ![2](https://github.com/brave/brave-browser/assets/128532965/dd7b97e1-b1f1-4e70-97be-2bab949626fd) | ![3](https://github.com/brave/brave-browser/assets/128532965/542436b6-3d7a-4ccb-a7a5-73f2b3c6e6b3) | ![4](https://github.com/brave/brave-browser/assets/128532965/4c9bbc19-0b6b-4b22-ac38-36b15d94a355) |
