### ISSUE TITLE
Move Portfolio Settings into Wallet Settings Menu

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#37257]
## Description 

We need to move the `Portfolio` settings into the `Wallet` settings menu

![Screenshot 25](https://github.com/brave/brave-browser/assets/40611140/daee2e1e-ec34-4a13-92b8-6a9890c809f2)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.97 Chromium: 124.0.6367.118 (Official Build) beta (64-bit)
-- | --
Revision | 94909f2aaefd7a8137c8b4fa27235378e79231e3
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22883](https://github.com/brave/brave-core/pull/22883)
- Verified `Portfolio Settings` is now listed under `Wallet Settings`
- Verified clicking on the `Plus` button in `Portfolio` opens `Edit Visible Assets` modal

https://github.com/brave/brave-browser/assets/17010094/e96e2da7-97fe-44dd-9ddc-2c4a0098896e
