### ISSUE TITLE
[Wallet] Do not wait for sign-all-transactions requests when initializing panel

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#37254]
## Description 

We should show the panel UI as soon as possible

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.95 Chromium: 124.0.6367.91 (Official Build) beta (64-bit)
-- | --
Revision | e1f8e3c95a12986231bc8226b78a951233e7c026
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22873](https://github.com/brave/brave-core/pull/22873)
- Verified panel opens and allows signing/rejecting pending request
- Verified for both Wallet account and Hardware wallet 

https://github.com/brave/brave-browser/assets/17010094/f3101c6c-c1eb-4dfe-92d3-9606c94c3483
