### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by kmcgrath** [brave/brave-browser#37259]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.64.109 Chromium: 123.0.6312.58
Operating System: Mac OS X 14.4.1

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Right click in a Chrome App created by brave

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/20d21900-686b-ba0b-0000-000000000000

**Comment by rebron** [comment]
Closing as dupe of https://github.com/brave/brave-browser/issues/36995

@kmcgrath Can you update to the latest when you get a chance. 1.65.114
