### ISSUE TITLE
Ad Notifications Received Count Reduces

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#3726]
## Description 
A user's browser has reduced the number of Ad Notifications Received over 24 hours.

3 days ago:

![image](https://user-images.githubusercontent.com/815158/54408397-c2077300-46af-11e9-99bc-7accb57dfbc2.png)

23 hours ago:

![image](https://user-images.githubusercontent.com/815158/54408403-cc297180-46af-11e9-97e3-b0dd84d9f1d3.png)

11 minutes ago:

![image](https://user-images.githubusercontent.com/815158/54408405-d186bc00-46af-11e9-9551-5fa379aabc33.png)

## Steps to Reproduce
TBD

## Actual result:
Brave appears to be losing track of how many ads have been viewed.

## Expected result:
Brave maintains an accurate record of how many ads the user has viewed.

## Reproduces how often: 
TBD

## Brave version (brave://version info)
0.63.9 Chromium (73.0.3683.75) 64-bit

### Website problems only:  
N/A

### Additional Information
TBD

**Comment by jsecretan** [comment]
Closing this because I believe this is the same problem fixed in #3716.  About 24 hours of uncashed tokens could be lost.  If use had been < 24 hours, it would reset to 0.  If more than 24 hours, it would revert to the last set of cashed in tokens.
