### ISSUE TITLE
[Wallet] Cache pin-able NFT ids

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#37264]
## Description 

We should avoid re-computing which NFTs can be pinned whenever possible

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.90 Chromium: 124.0.6367.82 (Official Build) beta (64-bit)
-- | --
Revision | 803a4c629341791205b744969c48b8da9f2cfa4d
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22882](https://github.com/brave/brave-core/pull/22882)
- Verified enabling NFT auto-pinning, ` brave://wallet/crypto/inspect-nfts` shows NFTs which are eligible and non-eligible for pinning

https://github.com/brave/brave-browser/assets/17010094/9a562841-ce62-4c46-b08c-38cec3af83d0
