### ISSUE TITLE
Brave news "No content" shown on fresh install

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#37270]
## Description 
On a fresh install, enabling Brave News via NTP displays no content initially. Tapping on "Load new content" will show the feed normally. 

Regression with `1.65.x`

## Steps to reproduce 

   1. Fresh install
   2. Enable Brave News from NTP
   3. 

## Actual result 
![Screenshot 2024-04-02 at 5 59 06 PM](https://github.com/brave/brave-browser/assets/17885425/6f862cdd-5608-4b7d-a40c-f67854399643)

## Expected result
Feed should be shown without issues

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? TBD

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy S21
   - Android version: 13
   
## Brave version
`1.65.96, Chromium 123.0.6312.86`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Cross-reference https://github.com/brave/brave-browser/issues/37156 on `desktop`.

**Comment by LorenzoMinto** [comment]
cc @petemill @fallaciousreasoning

**Comment by kjozwiak** [comment]
Closing in favour of https://github.com/brave/brave-browser/issues/37156. Added the `OS/Android` label for https://github.com/brave/brave-browser/issues/37156 as well.
