### ISSUE TITLE
[Commands]: Crash on Linux dev builds using Meta key

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#37275]
## Steps to Reproduce

   1.  Add a shortcut to a command including the Meta key
   2. Ensure it is the only shortcut
   3. Search the command in the command palette

**Note:** This only causes crashes where `NOTREACHED()` causes crashes, which is only in development builds

## Actual result:

The browser crashes

## Expected result:
The browser does not crash

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by iefremov** [comment]
@fallaciousreasoning can you share a tack or backtrace link? NOTREACHED() are not only development anymore

**Comment by fallaciousreasoning** [comment]
Its caused by `https://github.com/brave/chromium/blob/fe5eeb265d7f2ed57c13fdff15e3a1d4d19844c7/ui/base/accelerators/accelerator.cc#L405` - I have a fix in https://github.com/brave/brave-core/pull/22895

**Comment by fallaciousreasoning** [comment]
Merged the PR - I guess I must've been waiting for a green build and forgotten
