### ISSUE TITLE
Make nightly release support system level install on Windows

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#3728]
Chrome canary doesn't support system level install on Windows.
And we also set same value.

Should we have same policy for that or enable system level install on Windows?

In `setup_main.cc`,
```
  // Make sure system_level is supported if requested. For historical reasons,
  // system-level installs have never been supported for Chrome canary (SxS).
  // This is a brand-specific policy for this particular mode. In general,
  // system-level installation of secondary install modes is fully supported.
  if (!install_static::InstallDetails::Get().supports_system_level() &&
      (system_install ||
       cmd_line.HasSwitch(installer::switches::kSelfDestruct) ||
       cmd_line.HasSwitch(installer::switches::kRemoveChromeRegistration))) {
    return installer::SXS_OPTION_NOT_SUPPORTED;
  }
```

`chromium_install_modes.cc` has that config.
CC @bbondy

**Comment by simonhong** [comment]
@mihaiplesa  Because of this setting, our nightly installer doesn't work with admin.
When I run it w/o admin, it works well.

**Comment by bbondy** [comment]
I think all code that lands even on master is reviewed so I think it's ok. Is there some reason to disable or treat it different from other channels? 
cc @diracdeltas @fmarier

**Comment by simonhong** [comment]
I can't find the exact reason from the source.
`For historical reasons` and `brand specific policy` from the comments are the only reason I can find. :)
I also think supporting admin on nightly would be fine.

**Comment by mihaiplesa** [comment]
I'd suggest going forward with unblocking this (we can revert if needed).
