### ISSUE TITLE
Add Leo option to menu

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#37292]
Include Leo in the same section as Wallet and VPN

**Comment by aguscruiz** [comment]
Design here:
https://www.figma.com/design/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?node-id=6697-27337&t=jqnp6TFRG3ViPvjP-1

![image](https://github.com/brave/brave-browser/assets/15734630/eb16aa51-ae7b-4ba7-91c9-e68361d0c929)

**Comment by mattmcalister** [comment]
Done
