### ISSUE TITLE
Introduce slash tools

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#37297]
## Description: 

We want to give users the ability to select quick actions with their prompts, similar to right-click actions, but from Leo's sidepanel WebUI.

This needs to function well on mobile and possibly have the following UX nuances:

- Users should be able to remove the action type label from the input box.
- Pressing backspace on an empty input box with an action type selected should remove it.
- Typing "/" should open the tools menu and allow users to filter.

### Input box
- The send/microphone button is moved below the text input portion. This allows for better arrangement for the slash command icon and any future buttons we add in the future, like attachments.
- The padding around the whole input box is removed, so we can save some space there. Also, border radius only impacts the top of the input. The idea is to make it seem more integrated to the keyboard.

### Tools menu
- On iPad, the tools menu has a 377 max-height, this is a tentative height but the main goal is to show a menu item being cut off, so the user has a hint that the content area is scrollable.
- On iPad landscape mode, I think the tools menu should go full height like on the designs for iPhone
- On iPhone the menu goes full height (minus the margin / input box / keyboard) so users can view it better. To hide the menu, they have to click the [/] icon again.

Design system
https://www.figma.com/file/MNwi0uwXNhkAbPiJ86G4vm/%E2%9C%A8-Leo?type=design&node-id=1506%3A8040&mode=design&t=8gXTvsbx8ZIUXpoy-1

Flows
https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=1628%3A68090&mode=design&t=kvje2RSmalam6pOM-1

Duplicate issue for desktop/android
https://github.com/brave/brave-browser/issues/37294

**Before / after** 
![image](https://github.com/brave/brave-browser/assets/15734630/e14433c7-01f6-4c36-9f49-483d156723ff)

**Comment by nullhook** [comment]
done here: https://github.com/brave/brave-core/pull/22868

**Comment by kjozwiak** [comment]
The above requires `1.68.107` or higher for `1.68.x` verification 👍

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.6
- iPad Air / iPadOS 16.7.2
Brave build: 1.68 (110)
BraveCore: 1.68.110 (127.0.6533.26)
```
---------------------------

**STEPS:**
1. Launch Brave
2. Open `Leo` > *Verify that the `slash tools` button `/` is there*
3. Tap `/` > Choose `Explain`
4. Type a prompt  > Hit Enter > *Verify*
5. Tap `/` > Choose `Improve` this time
6. Type a prompt  > Hit Enter > *Verify*
7. Tap `/` > Choose `Change tone / Funny` this time
8. Type a prompt  > Hit Enter > *Verify*
9. Tap `/` > Choose `Social media / Short post` this time
10. Type a prompt  > Hit Enter > *Verify*
11. Enter some prompt > Tap `/` > *Verify*
12. Tap `/` > Choose any action > Tap in a prompt field
13. Tap `Backspace` on the keyboard > *Verify*
14. Tap the `Mic` button > Provide a `voice prompt` > *Verify*

**ACTUAL RESULTS:**
- Verified that the `Slash tools` are shown in the prompt field when launching `Leo` via `NTP` or any website
- Verified that the `Slash tools` can be opened/closed by tapping the `/` button or typing and deleting `/` in the text field
- Verified that the `Slash tools` dropdown menu is scrollable and can be collapsed/expanded by tapping the `arrow`
- Verified that any `action` can be dismissed by tapping the `x` or `Backspace` button on the keyboard
- Verified that different `actions` are working and providing different answers based on `action` type
- Verified that `Voice prompt` is working when an `action` is applied

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/0849ef55-86d0-4aa2-87a0-171054b857ca) | ![2](https://github.com/brave/brave-browser/assets/128532965/62abb95c-a059-4e46-9a88-4c8ee97a0af9) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/87de98a2-8291-418f-bbcc-0991d30a3918) | ![2](https://github.com/brave/brave-browser/assets/128532965/aa13c3ca-4083-46ec-a9ba-a149257be11c) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/4084f2a8-0784-47e2-b828-951c7198454f) | ![2](https://github.com/brave/brave-browser/assets/128532965/d5b4bc2e-6387-4cd8-a770-34f7c2e97f27) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/a06b3a38-3276-49e8-9227-17858bfeae1d) | ![2](https://github.com/brave/brave-browser/assets/128532965/01202a21-7a14-4455-b0e1-54156d71e3bd) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/c9804c1e-9f02-4b96-a866-dc65196c4e3f) | ![2](https://github.com/brave/brave-browser/assets/128532965/631425c1-3fc2-4d70-a6f6-cdf226b5870d) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/5bd74608-0981-4541-b43a-77b24f7f6dab) | ![2](https://github.com/brave/brave-browser/assets/128532965/9564669f-301c-453b-b642-8f80b5b2b67c) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/1e064f5e-6d10-4510-b851-f25af30bb9b1) | ![2](https://github.com/brave/brave-browser/assets/128532965/14e61d03-fac1-4c93-b7f9-081e65cc63b4) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/142f091a-1b11-4e71-8079-90e2d30625be) | ![2](https://github.com/brave/brave-browser/assets/128532965/6e912e1d-b011-4122-8b0f-f9089dce82a5) |
