### ISSUE TITLE
settings cookie detail page displays differently for www.youtube.com vs youtube.com

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#37291]
## Description 

Encountered while testing https://github.com/brave/brave-browser/issues/37030

When trying to test the above issue, YouTube was still not displaying locally stored data when accessed via `brave://settings/cookies/detail?site=www.youtube.com`.

However, if we manually update this URL to `brave://settings/cookies/detail?site=youtube.com`, then data displays. 

I'm not sure what can be done, as the steps below navigate to `brave://settings/cookies/detail?site=www.youtube.com` regardless of whether you visit `www.youtube.com` or just `youtube.com`. @emerick mentioned it might be due to how sites redirect via https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1712151599129159?thread_ts=1711632360.658839&cid=CHGKGMHDJ.

## Steps to Reproduce

1. Clean profile, close and relaunch to pull griffin
2. Open YouTube homepage or play any video on YouTube
3. Click on tune icon in URL bar (to view site information)
4. Click on Site settings
5. Click on Cookies and Site Data
6. Locally stored data is empty/blank

## Actual result:

<img width="1189" alt="116a" src="https://github.com/brave/brave-browser/assets/28145373/70a1b3b3-399a-4cba-8c07-fe34b7f2f578">

## Expected result:

<img width="1189" alt="116b" src="https://github.com/brave/brave-browser/assets/28145373/48f095e0-b488-4a23-ac6a-b882cc46a4b8">

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.63.174, 1.64.116 (note, release versions in between these have a different issue, referenced above)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes with RC 1.64.116
- Can you reproduce this issue with the beta channel? unsure, probably
- Can you reproduce this issue with the nightly channel? yes (@GeetaSarvadnya reproduced on 1.66.x)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @brave/qa-team

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue on 

```
Brave | 1.64.116 Chromium: 123.0.6312.105 (Official Build) (64-bit)
-- | --
Revision | d9090cab16ea606108bdf6edd7466df58d9d76fd
OS | Windows 10 Version 22H2 (Build 19045.4170)
``
![image](https://github.com/brave/brave-browser/assets/38657976/bbb4225f-2236-4dbe-a070-54385a314bd7)

**Comment by GeetaSarvadnya** [comment]
This is a regression issue, it worked fine till `1.59.111` The issue started appearing from version `1.60.109`

`1.59.111` | `1.60.109`
-----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/cf71ee82-649e-4bd2-bc00-cd3176d96d57) | ![image (1)](https://github.com/brave/brave-browser/assets/38657976/7852f487-b34d-432a-a9f0-3fc7fb4fd203)

**Comment by LaurenWags** [comment]
Cookie detail page is being removed per https://github.com/brave/brave-browser/issues/39033, so this issue is no longer valid. Closing.
