### ISSUE TITLE
follow-up to #36859, Remove redundant `Block cookies` setting

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#37305]
## Description 

1. Remove redundant `Block cookies` setting in brave://settings/shields, the one that links to brave://settings/cookies.
2. Change Shields label in per-site Shields panel from `Block cross-site cookies` => `Block third-party cookies`
3. Change labels under global `Block cookies` setting from `"All", "Only cross-site", "Disabled"` => `"Block all cookies", "Block third-party cookies", "Allow all cookies"`. In other words, mirror the Shields panel.
5. Update brave://settings/cookies to remove the entire **Default behavior** section.
6. Move the "Do Not Track" setting to be under the top-level brave://settings/privacy as the last item under "Go Off-The-Record..."

## Steps to Reproduce

   1. Use version 1.66.28 and higher
   7. Go to brave://settings/shields, brave://settings/cookies, and open up Shields advanced panel on a website.
   8. Notice items specified in the description.

## Expected result:

![image](https://github.com/brave/brave-browser/assets/5284154/a9565b91-de53-4210-a660-6d04a6ca429d)

and 

![image](https://github.com/brave/brave-browser/assets/5284154/cc69a350-9789-4771-b9d8-241052732a50)

and:

<img width="373" alt="Screenshot 2024-04-03 at 10 37 57 AM" src="https://github.com/brave/brave-browser/assets/5951041/652d7258-3017-4ae1-96e2-6596ee0ea117">

## Brave version (brave://version info)

Target 1.66.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Main issue: https://github.com/brave/brave-browser/issues/36859
cc: @ShivanKaul @fmarier

**Comment by bridiver** [comment]
@rebron it would be helpful if you showed the before state here as well

**Comment by bridiver** [comment]
This change seems problematic because it removes the ability to set "block all" as the default.

**Comment by fmarier** [comment]
> This change seems problematic because it removes the ability to set "block all" as the default.

I think that's still available via this setting in `brave://settings/content/siteData`:
![Screenshot from 2024-04-23 16-29-03](https://github.com/brave/brave-browser/assets/167821/a1039e6d-fd28-4ca3-94aa-501ce43176ff)

(this covers not just cookies, but also local storage)

**Comment by ShivanKaul** [comment]
@bridiver had the following alternative proposal: 
1. Remove the other `Block cookies` link from brave://settings/shields instead i.e. the one that points to brave://settings/cookies
2. Keep the other 3-way toggle instead (so the one being removed in this PR, sorry! 😬)
3. brave://settings/cookies is also accessible via brave://settings/content under **Content**. We keep this link, and then sync  `brave://settings/shields > Block cookies` with brave://settings/cookies. This means adding a "Block all cookies" third option under **Default behavior** in brave://settings/cookies. 

This sounds fine to me, probably more consistent, but my sense was that this would be a lot more work (especially maintenance). But if it's not a lot more work such that it would delay things beyond this release, I'm not opposed. I just strongly think we need to drop one of the "Block cookies" ASAP.

**Comment by bridiver** [comment]
> > This change seems problematic because it removes the ability to set "block all" as the default.
> 
> I think that's still available via this setting in `brave://settings/content/siteData`: ![Screenshot from 2024-04-23 16-29-03](https://private-user-images.githubusercontent.com/167821/325021095-a1039e6d-fd28-4ca3-94aa-501ce43176ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MTg2ODEsIm5iZiI6MTcxMzkxODM4MSwicGF0aCI6Ii8xNjc4MjEvMzI1MDIxMDk1LWExMDM5ZTZkLWZkMjgtNGNhMy05NGFhLTUwMWNlNDMxNzZmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQwMDI2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDk4MDY4ZjIwNDA1ZGQwNDRjNzhkNTZiNjRjNjRiY2FiZThmMzUzMGI3YjJkYjhlZjMyMDUzZDM4MzE2MmM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7JUm6JTUeQZ6z8l9MyisxUbcrX1-Zazp7Rh3BriO5XA)
> 
> (this covers not just cookies, but also local storage)

Cookies vs site data is a mess, they actually both use the cookie content settings, but in strange ways. I'm still digging into this, but I'm fairly certain this doesn't have the effect of blocking all cookies because that would mean that the chromium cookie default setting would display incorrectly.

**Comment by bridiver** [comment]
On Chrome I can have these two settings simultaneously
<img width="691" alt="image" src="https://github.com/brave/brave-browser/assets/34129/e207e21d-cd1b-48ac-9087-f3b90b2191f6">
<img width="676" alt="image" src="https://github.com/brave/brave-browser/assets/34129/40317c46-950d-4ce9-8d60-4faa08e4fa6c">

**Comment by bridiver** [comment]
<img width="784" alt="image" src="https://github.com/brave/brave-browser/assets/34129/08260e48-bbc4-4fa2-a1b6-64c6c8b228cf">
so I guess it does effectively block all, but in the most confusing way possible. One of the issues I mentioned to @ShivanKaul is that we should keep brave://settings/cookies and brave://settings/content/siteData buried right now anyway because this is a complete mess. I think the last thing we want to do is put brave://settings/cookies front and center for the default, especially when it may not even show the correct value

**Comment by bridiver** [comment]
if I replicate the above in Brave, brave://settings/shields and brave://settings/content/siteData show the correct effective setting of `block all`, but brave://settings/cookies shows `allow all`.

**Comment by bridiver** [comment]
> 3. brave://settings/cookies is also accessible via brave://settings/content under **Content**. We keep this link, and then sync  `brave://settings/shields > Block cookies` with brave://settings/cookies. This means adding a "Block all cookies" third option under **Default behavior** in brave://settings/cookies.
> 

I think we may need to completely replace what is currently in brave://settings/shields due to https://github.com/brave/brave-browser/issues/37305#issuecomment-2073784872 showing the wrong setting value (or find a fix for it)

**Comment by bridiver** [comment]
A quicker short term fix would be to do what @ShivanKaul outlined, but for now remove the default setting from brave://settings/cookies because it can sometimes show the wrong setting. We can follow up with a better fix

**Comment by kjozwiak** [comment]
The above requires `1.66.97` or higher for `1.66.x` verification(s) 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.66.97 Chromium: 124.0.6367.118 (Official Build) beta (64-bit)
-- | --
Revision | 94909f2aaefd7a8137c8b4fa27235378e79231e3
OS | Windows 10 Version 22H2 (Build 19045.4291)
```
