### ISSUE TITLE
Bookmarks not synced after removing Brave from Windows

### ISSUE THREAD

**Issue by dragGH102** [brave/brave-browser#3730]
Version: 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit) 

Reproduce (in sequence): install Brave on Windows, install Brave on Android (using latest version from play store). sync Android with Brave windows. Fully remove Brave from laptop (Windows).

Excepted: I should be able to access my bookmarks on the desktop having them on mobile but when I go to "sync" it asks me to start a keychain again (both Windows - as expected - and mobile)
Result: must reinit sync and all bookmarks are lost

**Comment by srirambv** [comment]
Sync isn't tied to device so when you fully remove Brave from laptop, the profile that was part of sync is removed however the profile is still associated with the sync. On mobile its the same, if you uninstall you device name would still be part of it but the actual install is lost. 

Once you join sync chain you have to have the profile active for the sync to happen between other devices. If your profile is deleted/removed/renamed, it wont sync any more. New profile will always ask for new sync chain to be created. 

Closing as invalid. Any questions please continue on the same thread.

**Comment by dragGH102** [comment]
@srirambv sorry but I don't understand the sentence "the profile that was part of sync is removed however the profile is still associated with the sync". How am I supposed to "join sync chain" if the chain is removed in any case, whatever device I uninstall Brave from?

Thanks for clarifying (or telling me what I'm not getting)

**Comment by rebron** [comment]
Hi @dragGH102. I'm not understanding your situation here, feels like there's a missing step. After you synced bookmarks on Brave on Android to Brave on Windows, you deleted Brave on Windows. And if you mean fully removed, you deleted your profile information as well. 

What's missing is what are you wanting to happen next? If you're adding a new Brave Browser instance, you need to create a new sync chain. You need two or more devices to create a sync chain.

**Comment by dragGH102** [comment]
By "removed" from Windows, I meant: removed Brave altogether with Windows
as I had to format the partition.
I understand that the sync chain is interrupted but I don't see why all the
bookmarks on Android also were gone.
Technical issues happen and while I understand that the point of sync is
peer-to-peer sync (just like Firefox does, right?) at least one device
needs to have the bookmark history to restore it but I find the limitation
of that device being a desktop computer quite extreme (given how unreliable
Windows is, just as an example)... or am I missing something out?
