### ISSUE TITLE
`Open Playlist settings` in Playlist sidebar goes to `brave://settings/playlist` which ends up in `brave://settings/` and not the proper `Content` settings page where Playlist settings are.

### ISSUE THREAD

**Issue by TEMP-ad** [brave/brave-browser#37317]
## Description 

https://github.com/brave/brave-browser/assets/156715894/7b33e45a-7c3d-4f77-a113-2a97cf80f15d

## Brave version (brave://version info)

1.66.56 Chromium: 123.0.6312.86 (Official Build) nightly (64-bit) 
Windows 11 Version 23H2 (Build 22631.3296)

**Comment by TEMP-ad** [comment]
@sangwoo108, bothering you again with some minor crap 👍

**Comment by sangwoo108** [comment]
No problem at all. It's a big issue 👍
