### ISSUE TITLE
Update Token List Background Hover State

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#37311]
## Description 

We need to update the `Token List` background hover state to the latest `figma` design.

![Screenshot 35](https://github.com/brave/brave-browser/assets/40611140/2dfd2b08-ab30-4983-9085-6f6377c4cd09)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.97 Chromium: 124.0.6367.118 (Official Build) beta (64-bit)
-- | --
Revision | 94909f2aaefd7a8137c8b4fa27235378e79231e3
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22914](https://github.com/brave/brave-core/pull/22914)
- Verified `Token List` has a new background hover state
- Verified `Market` tab, the list items have the same hover state similar to `Token List`

https://github.com/brave/brave-browser/assets/17010094/12647049-6c09-4ad5-ab6e-410eb4581305
