### ISSUE TITLE
crash when trying to access top left properties

### ISSUE THREAD

**Issue by Azkalaak** [brave/brave-browser#3731]
## Description 

Braves crashes when i try to mess up with the option on top left (file, edit, view...)

## Steps to Reproduce

   1. open brave from bash (didn't try with another shell)
   2. open one of the followinf tabs on the top left of the screen (file, edit, view, history, bookmarks, shields, window, help)
   3. move to show them until it crashes (takes less than a minute)

## Actual result:

makes brave crash

## Expected result:
open the tabs without crashing

## Reproduces how often: 

each time you try to access to the top left icons

## Brave version (brave://version info)

brave-bin 0.19.123 (funtoo OS)

### Additional Information

the icons that makes brave crash are no longer visible if I try to take a screenshot

**Comment by rebron** [comment]
@Azkalaak You're on an older version. Can you upgrade to brave.com/download please

**Comment by bsclifton** [comment]
Definitely an old version - please grab latest from https://brave.com/download

You can import most or all of your data 😄 Let us know if you have any questions
