### ISSUE TITLE
[iOS] - Expose brave://skus-internals

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#37315]
## Description: 
- Add skus-internals on iOS whitelist

## Steps to Reproduce 
  1. Enter `brave://skus-internals` into the URL-Bar

## Actual result: 
- Nothing happens

## Expected result:
- Should load Skus-Internals

**Comment by kjozwiak** [comment]
The above requires `1.64.120` or higher for `1.64.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.5
- iPad Air / iPadOS 16.7.2
Brave build: 1.64 (123)
BraveCore: 1.64.123 (123.0.6312.122)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Go to `brave://skus-internals` into the URL search bar
3. *Verify*

**ACTUAL RESULTS:**
- Verified that `brave://skus-internals` can be accessed successfully

---------------------------

|iPhone|iPad|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/e631ab5c-c54f-4da6-87c1-a32d0a54643b) | ![2](https://github.com/brave/brave-browser/assets/128532965/ec492b26-fd39-4c33-bd1d-434c6b32dca3) |
