### ISSUE TITLE
Add metric for comparitive DoH usage measurement

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#37318]
## Description 
To understand the impact of our default fallback DoH provider feature on DoH usage, we would like to compare the rates of DoH usage between clients enrolled in one of our candidate fallback DoH providers and clients who are not enrolled.

The fallback DoH provider is a multi-valued feature flag controlled via griffin. This feature is disabled by default but is designed to be enabled for pilot test(s) via griffin. To manually enable it for a specific DoH provider, you can launch from the command line with specific arguments:

On desktop:
```
npm run start -- Debug --enable-features=BraveFallbackDoHProvider:BraveFallbackDoHProviderEndpoint/wikimedia
npm run start -- Debug --enable-features=BraveFallbackDoHProvider:BraveFallbackDoHProviderEndpoint/quad9
npm run start -- Debug --enable-features=BraveFallbackDoHProvider:BraveFallbackDoHProviderEndpoint/cloudflare
```

On android:
```
../out/android_Debug_arm/bin/chrome_public_apk run --args='--enable-features=BraveFallbackDoHProvider:BraveFallbackDoHProviderEndpoint/wikimedia'
../out/android_Debug_arm/bin/chrome_public_apk run --args='--enable-features=BraveFallbackDoHProvider:BraveFallbackDoHProviderEndpoint/quad9'
../out/android_Debug_arm/bin/chrome_public_apk run --args='--enable-features=BraveFallbackDoHProvider:BraveFallbackDoHProviderEndpoint/cloudflare'
```

In our anticipated pilot study, the `brave-variations` the `seed.json` file would include something like
```
{
    "experiments": [
        {
            "feature_association": {
                "enable_feature": [
                    "BraveFallbackDoHProvider"
                ]
            },
            "name": "Quad9",
            "parameters": [
                {
                    "name": "BraveFallbackDoHProviderEndpoint",
                    "value": "quad9"
                }
            ],
            "probability_weight": 25
        },
        {
            "feature_association": {
                "enable_feature": [
                    "BraveFallbackDoHProvider"
                ]
            },
            "name": "Wikimedia",
            "parameters": [
                {
                    "name": "BraveFallbackDoHProviderEndpoint",
                    "value": "wikimedia"
                }
            ],
            "probability_weight": 25
        },
        {
            "name": "Default",
            "probability_weight": 50
        }
    ],
    "filter": {
        "channel": [
            "NIGHTLY"
        ],
        "platform": [
            "WINDOWS",
            "MAC",
            "LINUX",
            "ANDROID"
        ]
    },
    "name": "BraveDoHFallbackStudy"
},
```

Currently we have a P3A metric named `Brave.DNS.AutoSecureRequests`, which measures overall DoH usage across the client population. To compare different branches of the above study, we could introduce new metrics to collect the same data per branch.

Because there are currently 3 candidates, this study could have as many as 4 simultaneous branches (including the negative control). So we would likely need metrics named something like

- `Brave.DNS.AutoSecureRequests` (for users not included in the experiment)
- `Brave.DNS.AutoSecureRequests.Quad9`
- `Brave.DNS.AutoSecureRequests.Wikimedia`
- `Brave.DNS.AutoSecureRequests.Cloudflare`

where each metric would receive reports when the corresponding flag value was set.

cc @DJAndries @ShivanKaul

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.67.85 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | d01060f5ec155e6eb64a335203663a29c0e5d81f
OS | Windows 10 Version 22H2 (Build 19045.4412)
```

**Comment by GeetaSarvadnya** [comment]
@DJAndries I have verified the test plan from https://github.com/brave/brave-core/pull/19479 on the latest beta build `167.89` the steps 8 and 9 are NOT working as expected hence I ahve failed steps 8 and 9. Please review the test above and let me know if I have missed anything. Thanks!

**Comment by DJAndries** [comment]
> @DJAndries I have verified the test plan from [brave/brave-core#19479](https://github.com/brave/brave-core/pull/19479) on the latest beta build `167.89` the steps 8 and 9 are NOT working as expected hence I have failed steps 8 and 9. Please review the test above and let me know if I have missed anything. Thanks!

Thanks @GeetaSarvadnya , raised https://github.com/brave/brave-browser/issues/38459

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on `Samsung galaxy version 12` running `Bravemonoarm64.apk_1.67.90`

- Verified the test plan from https://github.com/brave/brave-core/pull/19479

**Prerequisite:**

- Configured the Cloudflare DNS settings on Windows 10
- Confirmed web traffic runs through  Cloudflare DNS Service 
- Visited the https://1.1.1.1/help and ensured `Connected to 1.1.1.1` is `Yes` and `Using DNS over HTTPS (DoH)` is `Yes`

Example | Example
----------|---------
![Screenshot_20240524_194401_Settings](https://github.com/brave/brave-browser/assets/38657976/42a541f5-0f24-4eca-aeb0-5e9337250f8f) | ![Screenshot_20240524_194627_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/9495556e-7f44-4005-b434-f039ca6ad7a7)




**Test plan steps:**

0. Ensure a DNS server that supports DoH (such as Cloudflare: 1.1.1.1) is configured in your OS network settings. Start with fresh profile.  - **PASSED**
1. Ensure that the secure setting metric `Brave.DNS.SecureSetting` has the response value of 1. - **PASSED**
![image](https://github.com/brave/brave-browser/assets/38657976/817819b4-2604-4024-931d-302ef82d76e4)
2. Make a random query on your search engine, click on a bunch unique links. **PASSED**
3. On the local state page, search for `upgraded_dns_requests` and `total_dns_requests`. Note the values. `upgraded_dns_requests` should have a positive value, if your OS settings are correct. - **PASSED**

`upgraded_dns_requests` value is `81` and  `total_dns_requests` value is `92`

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/f1daa4ac-88b2-43a8-802f-88244a94a032) | ![image](https://github.com/brave/brave-browser/assets/38657976/2155cfc1-5433-410f-8989-2fd08597acfa)

4. The percentage range indicated by the value of the auto-secure requests metric should encompass the ratio of `upgraded_dns_requests` to `total_dns_requests` (i.e. if the upgraded count is 10, and the total count is 15, the ratio would be 66% and the correct metric answer would be 2) - **PASSED**

In my case when I visit random links from search result page I have got the upgrade count is `81` and total dns requests count is `92`, the ratio would be `81/92` = `88%` and 88% fall under the response bucket `2` `Greater than 50 and less than 90%`, I am getting the the metrics `Brave.DNS.AutoSecureRequests` response value as `2` which is correct and expected.

![image](https://github.com/brave/brave-browser/assets/38657976/b3d329b4-4f8b-4865-b51d-0e21a65f89d6)


5. Disable the DoH supporting server in your OS settings (let DHCP do it's thing) - **PASSED**

- Disabled the cloudflare settings from the OS network setting and ran https://1.1.1.1/help and ensured that the cloudflare DNS settings are disabled

![image](https://github.com/brave/brave-browser/assets/38657976/b817df81-702a-42b8-9f8b-f2cf8d63180e)


6. Visit more sites, wait for 20 secs, reload local state file

Both uppgraded count (109) and total count (190) are increased

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/16578512-caf0-4a70-818b-0d9cccf3e111) | ![image](https://github.com/brave/brave-browser/assets/38657976/ae5172c3-112c-4d4b-b3c9-4c0f51105695)


6. 1 Repeat the step 6

7. Ensure that the `upgraded_dns_requests` count does not grow as you visit websites. The ratio of upgraded-to-total requests should increase as you visit more domains. The auto-secure requests metric value should also change accordingly. - **PASSED**

(Updated the step 7, the total count value is not lowered when we visit more websites)

The Uppgraded count (109) remains same, only total count (204) increases

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/9679916b-ae55-4244-8db3-567487d3da45) | ![image](https://github.com/brave/brave-browser/assets/38657976/e0b95991-aa20-430f-95ce-bf2f1e18dd6f)

![image](https://github.com/brave/brave-browser/assets/38657976/14e3331b-9e7f-45a2-bc38-ab421361e8f6)


8. Change your browser DoH setting to "With Cloudflare". `Brave.DNS.SecureSetting` should be 2, and `Brave.DNS.AutoSecureRequests` should disappear.  - **FAILED**

- Changed the DoH setting to "Cloudflare 1.1.1.1" via brave://settings/security
- Reload the brave://local-state file 
- Confirmes that the metrics `Brave.DNS.SecureSetting` response value is `2` `custom provider` as expected 
- Confirmed that the metrics `Brave.DNS.AutoSecureRequests` doesn't show up in the local state file (Note: The metrics `Brave.DNS.AutoSecureRequests` is shown with the response value `2` hence failed the case)

Example | Example | Example
----------|---------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/d1d5600f-e1d4-43c2-a5e2-45f61ebca5bf) | ![image](https://github.com/brave/brave-browser/assets/38657976/3a7aeb75-82b4-48a2-b6a9-53e8e8e08e1b) | ![image](https://github.com/brave/brave-browser/assets/38657976/ac6f797e-6091-4979-8c97-25ff86f2d0fd)


9. Turn off your browser DoH setting. Ensure both metrics do not exist. - **FAILED**

- Turned off the `Use secure DNS` via brave://settings/security
- Confirmed that the metrics `Brave.DNS.SecureSetting` doesn't show up in the local state file (Note: the metrics `Brave.DNS.SecureSetting` is shown with the response value `1` hence this step is failing)
- Confirmed that the metrics `Brave.DNS.AutoSecureRequests` doesn't show up in the local state file (Note: the metrics `Brave.DNS.AutoSecureRequests` is shown with the response value `2` hence this step is failing)

Example | Example | Example
----------|---------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/0ae0d34e-67e3-4930-bb12-205df773c0da) | ![image](https://github.com/brave/brave-browser/assets/38657976/266417b0-4650-4fa0-b823-fc7f531f6f71) | ![image](https://github.com/brave/brave-browser/assets/38657976/aa59bbfe-d58b-4a91-b32b-e0b358ce8d85)

**Comment by GeetaSarvadnya** [comment]
@DJAndries: I have verified the issue on Android on the brave version `1.67.90`. Apart from step 4 all other steps are working as expected. I have verified the step 4 multiple times but I am getting the incorrect response.

I am getting the metrics `Brave.DNS.AutoSecureRequests` response value as `2` instead of  `1`. Could you review the steps above https://github.com/brave/brave-browser/issues/37318#issuecomment-2129791013. Thanks!

**Comment by GeetaSarvadnya** [comment]
Verified the step 4 again and ensured that correct response `2` is shown for the metrics `Brave.DNS.AutoSecureRequests`
