### ISSUE TITLE
[Nala] UI glitch hanging from the toggle when `Developer mode` is toggled `On` in `brave://extensions`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#37316]
## Description 

[Nala] UI glitch hanging from the toggle when `Developer mode` is toggled `On` in `brave://extensions`

## Steps to Reproduce

   1.  install `1.66.56`
   2.  launch Brave
   3. open `brave://extensions`
   4. toggle `Developer Mode` to `On`
   5. look at the hanging UI glitch coming off of the toggle widget

## Actual result:

example | example
---------|----------
<img width="1486" alt="Screen Shot 2024-04-03 at 2 02 49 PM" src="https://github.com/brave/brave-browser/assets/387249/d5ae5608-8e76-47c3-8ad1-1a20d929d85a"> | <img width="231" alt="Screen Shot 2024-04-03 at 2 09 10 PM" src="https://github.com/brave/brave-browser/assets/387249/e6af6a8c-79ed-4065-b556-9b89a4529790">

## Expected result:

Nothing extending from the `Developer Mode` toggle widget

<img width="1846" alt="Screen Shot 2024-04-03 at 2 03 10 PM" src="https://github.com/brave/brave-browser/assets/387249/aaa68b40-8717-44b4-9642-ce0537ee3b06">

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave	1.66.56 Chromium: 123.0.6312.86 (Official Build) nightly (x86_64) 
Revision	029ff6b82a6cfb16bde7c6d7ab560321a023cb8b
OS	macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the nightly channel? `No`

cc @brave/qa-team @rebron @fallaciousreasoning

**Comment by MadhaviSeelam** [comment]
Verification `Passed` using
```
Brave | 1.68.84 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | c5a3b2ff9dcc938c32b2c1b3a66847661db5d005
OS | Windows 11 Version 23H2 (Build 22631.3672)
```

Reproduced the issue in `1.66.118` using STR from the issue description https://github.com/brave/brave-browser/issues/37316#issue-2223930735

Confirmed UI glitch when `Developer mode` is turned on, a `scrollable element`, on the extensions page is no longer shown

`1.66.118` | `1.68.84`
----- | ------
<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/3ebf9e6f-5674-43f8-85a6-129e1d6576da">|<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/5b5c46fd-8bbc-426f-93ac-e6945403b1f3">
