### ISSUE TITLE
[Follow up to #18440] `TLS` error is not shown when opening `https://ssl-pinning.someblog.org/`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#37322]
## Description 

Follow-up to #18440

## Steps to reproduce 

   1. Launch Brave
   2. Go to https://ssl-pinning.someblog.org/ > *Confirm that it returns a `NET::ERR_SSL_PINNED_KEY_NOT_IN_CERT_CHAIN` TLS error:*
   3. *Observe that the website successfully opened and no `TLS` error is shown*

## Actual result 

`TLS` error is not shown when opening `https://ssl-pinning.someblog.org/`.

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/555e27a7-727b-4066-a327-b6275aef0db8) | ![2](https://github.com/brave/brave-browser/assets/128532965/cd975b85-a714-444e-8a05-b01e267b93ea) |

## Expected result

`TLS` error must be shown when opening `https://ssl-pinning.someblog.org/`.

## Issue reproduces how often 

`Easily reproduced`

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? YES
- Can you reproduce this issue with the current Play Store Beta version? YES
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 7 (Phone)
   - Android version: Android 14
   
## Brave version

```
Brave build: 1.65.101
Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by fmarier** [comment]
This is because TLS pinning is not yet enabled on Android: https://github.com/brave/brave-browser/issues/24453

So I should have marked the original issue as desktop only. Sorry about that, I forgot we never got around to rolling this out to Android.
