### ISSUE TITLE
[Ad] should pre-pend title and not CTA for Ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#3732]
## Description 
[Ad] should pre-pend title and not CTA for Ads

## Steps to Reproduce

   1. Navigate to www.brave.com
   2. Idle for 15+ seconds

## Actual result:
[Ad] should not pre-pend the CTA, i.e.

British Test Ad
[Ad] British Test Ad

## Expected result:
[Ad] should pre-pend the title, i.e.

[Ad] British Test Ad
British Test Ad

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
0.63.9

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  brave-browser dev

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

- Verified test plan from https://github.com/brave/brave-core/pull/1963
<img width="370" alt="Screen Shot 2019-03-20 at 2 46 08 PM" src="https://user-images.githubusercontent.com/28145373/54711215-cd2f2880-4b1f-11e9-854c-b93f6e409759.png">

**Comment by srirambv** [comment]
Marking `QA/No` as this is invalid now
