### ISSUE TITLE
Soundcloud login iframe doesn't load

### ISSUE THREAD

**Issue by iamtheef** [brave/brave-browser#37327]
## Description 

Brave seems like isn't loading soundcloud's iframe for login. I have noticed some similar issues with brave where pages not loading or misbehave like opening documents on microsoft office through links. It works on incognito tho. The way I login into sc right now is take the link of the iframe, open it in a new tab, login and then go back to the initial tab and refresh. I have tried to clear cookies and localstore but didn't work. I have also tried to uninstall and install brave and still didn't work.

## Steps to Reproduce

Well not sure. I guess just wait for brave usage to build up.
   1. Maybe try to open sc's login
   2. if it works logout
   3. and try to log back in

## Actual result:

<img width="1241" alt="image" src="https://github.com/brave/brave-browser/assets/54245835/0fde873c-3afb-490f-836b-db924b308365">

## Expected result:
<img width="1233" alt="image" src="https://github.com/brave/brave-browser/assets/54245835/7fdbf846-0ba9-4c51-803d-3ceaad9a47b9">
From another browser

## Reproduces how often: 

Well, if done once you cannot do it again or undo it.

## Brave version (brave://version info)

1.64.116 Chromium: 123.0.6312.105 (Official Build) (arm64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
Have the login window here @iamtheef  Is it still not showing up?

**Comment by iamtheef** [comment]
> Have the login window here @iamtheef  Is it still not showing up?

Why would it show up now?

**Comment by ryanbr** [comment]
> > Have the login window here @iamtheef  Is it still not showing up?
> 
> Why would it show up now?

Websites can "act up" randomly, not the first time. 

Can you test in private window mode? Any custom adblock lists in brave://adblock ?

**Comment by iamtheef** [comment]
As mentioned above it works on incognito.

> Any custom adblock lists in brave://adblock ?
No

**Comment by ryanbr** [comment]
Which extensions installed? and disabling them helps?

**Comment by iamtheef** [comment]
> Which extensions installed? and disabling them helps?

Oh! After a bit of experimentation I found out that WhoCors extension is responsible and disabling it works! I have 0.0.4 version. It's an important extension so I wouldn't want to leave it disabled. Any ideas?

**Comment by ShivanKaul** [comment]
Looks like the Who CORS? extension is no longer available on Chrome Web Store, and it was itself a fork of [Allow CORS](https://chromewebstore.google.com/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf), which I just tested and seems to work fine on Brave. As such, I'm closing this issue out.
