### ISSUE TITLE
Make Entire Account List Item Clickable

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#37321]
## Description 

We need to make the entire `Account List Item` clickable in the `Accounts` tab.

![Screenshot 37](https://github.com/brave/brave-browser/assets/40611140/c45a1b05-0dda-416e-8efc-b3072287ae9d)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.66.95 Chromium: 124.0.6367.91 (Official Build) beta (64-bit)
-- | --
Revision | e1f8e3c95a12986231bc8226b78a951233e7c026
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22925](https://github.com/brave/brave-core/pull/22925)
- Verified entire Account list is clickable
- Verified no copy button is shown next to account address

https://github.com/brave/brave-browser/assets/17010094/3ae5e4ef-a6a4-4992-aa7c-f272b19a4d49
