### ISSUE TITLE
[iOS] Use brave-core components for managing filter list downloads

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#37335]
## Description: 
We use the CRX packager to download filter lists however we use some custom policies that are iOS specific. We want to remove these custom policies and use the exact same code that desktop uses

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.68 (124)`

- Ensured all the tests in Test Plan mentioned in https://github.com/brave/brave-core/pull/22937#issue-2225574207 are passing. 
- Ensured ads are blocked on YouTube - Encountered: https://github.com/brave/brave-browser/issues/39855

Encountered: https://github.com/brave/brave-browser/issues/39842 (Scriptlets issue)

Example | Example | Example | Example
-|-|-|-
![IMG_6820](https://github.com/user-attachments/assets/6eb9595c-2639-46d4-94ca-8087f59d6d6a) | ![IMG_6821](https://github.com/user-attachments/assets/1847a657-74f2-4bd5-b285-4184ae795f45) | ![IMG_6822](https://github.com/user-attachments/assets/8ea6a9ad-1e74-461c-9358-59e1a3e3a376) | ![IMG_6823](https://github.com/user-attachments/assets/547f8b26-e31c-46d2-87a0-263bcd307891)

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iOS 17.5.1` using version `1.68 (124)`

- Ensured all the tests in Test Plan mentioned in https://github.com/brave/brave-core/pull/22937#issue-2225574207 are passing. 
- Ensured ads are blocked on YouTube - Encountered: https://github.com/brave/brave-browser/issues/39855

Encountered: https://github.com/brave/brave-browser/issues/39842 (Scriptlets issue)

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_1508](https://github.com/user-attachments/assets/84fd8afd-8bbe-45ed-a17f-4d42bd1a115b) | ![IMG_1509](https://github.com/user-attachments/assets/d72bd2e5-bd63-484d-85ec-67677910e81c) | ![IMG_1510](https://github.com/user-attachments/assets/b8f13715-61a3-40ba-8d96-cb0edefb004f) | ![IMG_1511](https://github.com/user-attachments/assets/1dcfcaf6-3b0e-444b-bc0b-1d3478e7ad40) | ![IMG_1512](https://github.com/user-attachments/assets/54997920-f0e1-4160-9872-f7b76371ef43) | ![IMG_1513](https://github.com/user-attachments/assets/2f0a13be-6a9b-4763-adc5-dc002ee06fef)
