### ISSUE TITLE
Update Transaction Item Hover Background

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#37339]
## Description 

We need to update the `Transaction Item` background hover color to match new `figma` designs.

![Screenshot 39](https://github.com/brave/brave-browser/assets/40611140/b3cc6cb2-ab1f-4d85-8c0b-90c8f3227340)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.101 Chromium: 124.0.6367.118 (Official Build) beta (64-bit)
-- | --
Revision | 62fb0f940cad0714f585e2f01d2f968d64592d25
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22939](https://github.com/brave/brave-core/pull/22939)
- Verified transaction activity hover state has a lighter hover state

https://github.com/brave/brave-browser/assets/17010094/3b7264f3-fd81-4a09-a4d7-a90010a5d748
