### ISSUE TITLE
Make Entire Portfolio Account List Item Clickable

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#37340]
## Description 

We need to make the entire `Portfolio Account` list item clickable in the `Asset Details` screen.

![Screenshot 42](https://github.com/brave/brave-browser/assets/40611140/7cf6c7ba-d519-45c5-9d09-3f2e7bf4ce15)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.97 Chromium: 124.0.6367.118 (Official Build) beta (64-bit)
-- | --
Revision | 94909f2aaefd7a8137c8b4fa27235378e79231e3
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22940](https://github.com/brave/brave-core/pull/22940)
- Verified entire Portfolio account list item is clickable now
- Verified there is no copy address button next to address in account list view
- Verified deposit is now listed in more menu
- Encountered [#38077](https://github.com/brave/brave-browser/issues/38077)

https://github.com/brave/brave-browser/assets/17010094/4bc6941d-dbd0-41ac-8018-c79ff0aab298
