### ISSUE TITLE
Tab Swipe causes Rewards and Shields button area to retain previous tabs theme

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#37342]
## Description 
Tab Swipe causes Rewards and Shields button area to retain previous tabs theme

## Steps to reproduce 

   1. Visit multiple pages which have dark and light theme
   2. Swipe to switch tabs via URL bar
   3. Rewards and Shields button area retains the previous tabs theme 

## Actual result 

https://github.com/brave/brave-browser/assets/17010094/cf102f2a-2616-437d-a885-8a0ecdb41879

## Expected result
Theme should be applied to all URL bar elements

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 14/13
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @hffvld @Uni-verse @samartnik

**Comment by hffvld** [comment]
It looks like a similar issue https://github.com/brave/brave-browser/issues/36438 was fixed and verified, but I could reproduce this issue from above as well when the device theme is set to `Light Mode`.

------------------

https://github.com/brave/brave-browser/assets/128532965/9dc22421-364b-4c58-8bdb-1f779fdfd92f

**Comment by samartnik** [comment]
Issue comes from the upstream, the same issue is with Chrome

**Comment by samartnik** [comment]
As a solution we now postpone transition animation until swipe finishes
[Screen_recording_20240424_100644.webm](https://github.com/brave/brave-browser/assets/30602739/fb313654-1bcf-4171-9d19-1d7dad9440d8)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo x70 Pro version 12` running `Bravemonoarm64.apk_1.67.90`

- Verified the STR from description https://github.com/brave/brave-browser/issues/37342#issue-2226060419 and ensured that Tab swipe doesn't retain the previous theme for Rewards and shield area

https://github.com/brave/brave-browser/assets/38657976/946bb2b1-8e67-4213-b8b9-d83a460fdd68
