### ISSUE TITLE
[Skus] - SkusSDK does not propagate errors to the point of usage

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#37347]
## Description: 
- SkusSDK can return `499 - bad request - null` as an error message and we have no idea what error it is.
- So we need to propagate errors so we can decide what to do when an error occurs.
- This means errors and results should NOT be returned in the same string. It should explicitly return an error code with the error message upon failure. Otherwise it should return no error code (`Result::Ok`) and the requested data.

## Steps to Reproduce 
  1. Attempt to Link accounts from Mobile to Desktop
  2. Sometimes you'll get an error "Unknown"
  
## Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily reproduced

## Brave Version: 
- All

### Device details: 
- All

**Comment by kjozwiak** [comment]
Removing from the `1.66.x` milestone as https://github.com/brave/brave-core/pull/22944 needs to be merged into `master` and then uplifted into `1.66.x` if needed.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.69.124 Chromium: 127.0.6533.73 (Official Build) beta (64-bit)
-- | --
Revision | dbc9035349f74e493f3293d93f4cbf35c597dfec
OS | Windows 11 Version 23H2 (Build 22631.3880)
```

#### Desktop - Mobile Linking

<details>
<summary>Desktop - Desktop </summary>

1. installed 1.69.124 
2. launched Brave
3. loaded account.bravesoftware.com
4. entered basic-auth credentials
5. entered brave37347vpn@mailinator.com, clicked Get login link
6. clicked the link in the email
7. clicked Browse plans
8. scrolled down and clicked on Buy now for Brave VPN Subscription
9. completed the Stripe purchase flow
10. confirmed I could connect to the VPN via whatismyipaddress.com
11. installed 1.69.x and launched Brave on machine
12. logged into account.bravesoftware.com with basic auth
13. entered same above email address (brave37347vpn@mailinator.com) to get the email link
14. clicked login button in the email 
15. confirmed subscription page loaded
16. confirmed Brave VPN worked as expected via whatismyipaddress.com

</details>

<details>
<summary>Desktop - Android</summary>




</details>

<details>
<summary>Desktop - ioS</summary>

</details>

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP31.240617.009 release-keys
Brave build: 1.68.127
Chromium: 127.0.6533.57 (Official Build) (64-bit) 
```
---------------------------

`VPN` subscription link from `Android` to `Desktop`

**STEPS:**
1. Launch Brave on `Android`
2. Purchase `VPN` subscription
3. Hamburger menu > Settings > Brave Firewall + VPN
4. Link purchase to your Brave account
5. Enter email > Go to email and tap the confirmation button
6. On `account.brave.com` tap `Link my subscription now` > *Confirm successful result*
7. Open Brave on `Desktop` > Go to `account.brave.com`
8. Sign in with the same email > Confirm `You have active credentials loaded!` message is shown
9. Go to www.ipinfo.io > Change `VPN` location in Brave > *Verify results on www.ipinfo.io*

**ACTUAL RESULTS:**
- Verified that purchased on `Android` `VPN` subscription can be linked to `Desktop`
- Verified that changing the `VPN` location in Brave is working and shows the correct location on www.ipinfo.io

---------------------------

https://github.com/user-attachments/assets/6f3e0d8e-74c3-41a2-b730-072834ed927f
</details>

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6.1
Brave build: 1.69 (162)
BraveCore: 1.69.162 (128.0.6613.120)
```
Filed follow-up issue #40860
---------------------------

`VPN` subscription link from `iOS` to `Desktop`

**STEPS:**
1. Launch Brave on `iOS`
2. Purchase `VPN` subscription
3. Hamburger menu > Settings > Brave Firewall + VPN
4. Link purchase to your Brave account
5. Enter email > Go to email and tap the confirmation button
6. On `account.brave.com` tap `Link my subscription now` > *Confirm successful result*
7. Open Brave on `Desktop` > Go to `account.brave.com`
8. Sign in with the same email > Confirm `You have active credentials loaded!` message is shown
9. Go to www.ipinfo.io > Change `VPN` location in Brave > *Verify results on www.ipinfo.io*

**ACTUAL RESULTS:**
- Verify that purchased on `iOS` `VPN` subscription can be linked to `Desktop`
- Observed an error where an active `VPN` subscription can't be linked to the `Web`

---------------------------

https://github.com/user-attachments/assets/4578fb4f-818f-4ff1-bb6d-caf22c28477e
