### ISSUE TITLE
[hackerone] private tab title issue

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#37343]
https://hackerone.com/reports/2446716
credit: https://hackerone.com/thesur

**Comment by samartnik** [comment]
this was fixed in the context of https://github.com/brave/brave-browser/issues/36272, fix will be available in version `1.65`

**Comment by deeppandya** [comment]
@kjozwiak @hffvld @Uni-verse we need to verify the issue for 1.65 release. i am updating the milestone for the issue.

**Comment by deeppandya** [comment]
Closing the issue based on : https://github.com/brave/brave-browser/issues/37343#issuecomment-2064341540

**Comment by hffvld** [comment]
Verified this issue via https://github.com/brave/internal/issues/1144 on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP31.240322.018 release-keys
Brave build: 1.65.114
Chromium: 124.0.6367.60 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the steps from https://hackerone.com/reports/2446716
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the website URL address from the `Private tab` is not leaking to the `Standard tab`

---------------------------

https://github.com/brave/brave-browser/assets/128532965/bd7f7cc7-34af-4369-b1cc-6d67a48d2686

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 14` using the following build(s):

```
Brave | 1.65.114 Chromium: 124.0.6367.60 (Official Build) (64-bit)
--- | ---
Revision | f1e2cbb65e11340d9040d5ef0b0115c7a5206207
OS | Android 14; Build/AP21.240305.005; 34; REL
```

Verification was completed via https://github.com/brave/internal/issues/1144#issuecomment-2065027497 & https://github.com/brave/internal/issues/1144#issuecomment-2065100254.
