### ISSUE TITLE
Leo - Remove background graphics on onboarding

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#37345]
## Description: 

There was a request to remove the background graphics on the onboarding cards for Leo. This applies to all platforms.
There may be some other updates to the onboarding soon, but that's still under consideration.

<img width="1457" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/29d53c17-04a2-4a5d-8781-cdf42c3706ce">

https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=15-11967&mode=design

**Comment by kjozwiak** [comment]
The above requires `1.68.112` or higher for `1.68.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.68.117`

- Ensured that background graphics are removed for Leo onboarding flow.
- Ensured that user can successfully complete onboarding from all access points (NTP, 'Ask Leo' in search bar and on webpage).

Example | Example | Example | Example
-|-|-|-
![IMG_6747](https://github.com/brave/brave-browser/assets/17885425/48126c40-650a-45cb-a144-750a259a7c96) | ![IMG_6748](https://github.com/brave/brave-browser/assets/17885425/397442b6-e970-4020-9f3a-eee966c0881b) | ![IMG_6749](https://github.com/brave/brave-browser/assets/17885425/d27efcf1-ad37-414a-b081-29ec97f0202d) | ![IMG_6750](https://github.com/brave/brave-browser/assets/17885425/f38ac38d-982c-414d-ba60-c7c8eb608903)
