### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by DarshilRij** [brave/brave-browser#37346]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.47.186  Chromium: 109.0.5414.119
Operating System: Mac OS X 13.3.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/1bb10600-aea4-c30b-0000-000000000000

**Comment by rebron** [comment]
@DarshilRij Can you update to the latest 1.64.116 and let us know if you're still experiencing the crash. You can go here brave://settings/help to get the update.

**Comment by iefremov** [comment]
stale
