### ISSUE TITLE
align rewards OFAC countries with internal guidelines

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#37348]
at the moment the countries that should be blocked for rewards as a whole is Category 2 in https://github.com/brave/devops/wiki/Region%E2%80%90based-sanctions-blocking#category-2

```
KP		North Korea
IR		Iran
SY		Syria
CU		Cuba
-	UA-43	Ukraine (Crimea)
-	UA-14	Ukraine (Donetsk)
-	UA-09	Ukraine (Luhansk)
-	UA-40	Ukraine (Sevastopol)
```

this doesn't quite line up with https://github.com/brave/brave-core/blob/a4878409cff8bd71932c883ff1785c3a0b3d17f5/components/l10n/common/ofac_sanctioned_iso_3166_1_country_code_constants.h, which blocks all of Russian instead of the sanctioned regions of Ukraine.

if we cannot block sub-country regions, we could err on the safe side and just block all of Russia/Ukraine?

**Comment by Miyayes** [comment]
@tmancey Will this make the Rewards feature completely unavailable in these regions?

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.67.89 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | 3f2fa4d26cca2b40937e894494f573f9c4aa3532
OS | Windows 10 Version 22H2 (Build 19045.4412)
```
- Verified the test plan from https://github.com/brave/brave-core/pull/23132

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240426.022 release-keys
Brave build: 1.67.98 
Chromium: 125.0.6422.112 (Official Build) beta (64-bit) 
```
---------------------------
<details>
<summary> North Korea (KP) </summary>

**STEPS:**
1. Follow [this test plan](https://github.com/brave/brave-core/pull/23132#issue-2248885431)
2. Follow [this description](https://github.com/brave/brave-browser/issues/37348#issue-2226471925) and [comment](https://github.com/brave/brave-browser/issues/37348#issuecomment-2070628444)
3. Set device language/region to `Korean`/`North Korea`
4. Fresh install Brave > *Verify*

**ACTUAL RESULTS:**
- Verified that the `Brave Rewards` icon is not available in the `URL search bar`
- Verified that the `Brave Rewards` is not available in the `Mani menu`
- Verified that the `Brave Rewards` is not available when going to brave://rewards
- Verified that `Something went wrong` is shown when the device language is set to `English (USA)` and enabling `Brave Rewards` via the `URL search bar`

---------------------------

|1|2|3|
|:-:|:-:|:-:
| ![1](https://github.com/brave/brave-browser/assets/128532965/f61c55e8-e88b-4da5-833a-cdb31ee4a7ee) | ![2](https://github.com/brave/brave-browser/assets/128532965/0c624d74-a3b5-438a-9522-9f04cd769ecc) | ![3](https://github.com/brave/brave-browser/assets/128532965/000645a5-ae52-4c0a-858a-67d4714be78f) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/ce564151-8621-4c73-85ca-bf2e3baa9640) | ![2](https://github.com/brave/brave-browser/assets/128532965/7fe496c5-674b-49d4-b181-bb4a71d598ee) | ![3](https://github.com/brave/brave-browser/assets/128532965/3d3b6e10-5a00-4915-bf89-7bbf1c9b8b8a) |
</details>

<details>
<summary> Iran (IR) </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>

<details>
<summary> Syria (SY) </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>

<details>
<summary> Cuba (CU) </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>

<details>
<summary> Ukraine (UA) </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>

<details>
<summary> Russia (RU) </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>

<details>
<summary> Belarus (BY) </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>

<details>
<summary> Moldova (MD) </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.67.101 Chromium: 126.0.6478.26 (Official Build) beta (x86_64)
-- | --
Revision | a561f4b53cdb831888e5cd702d2b8f9598c00f50
OS | macOS Version 13.6.7 (Build 22G720)
```

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave	1.67.100 Chromium: 125.0.6422.112 (Build oficial) beta (64 bits) 
Revisión	34fcbb6655521b55468af6c63601a8e3c5d24cd2
SO	Linux
```
<details>
<summary>2. Cuba_PASSED</summary>

- Confirmed that user cannot enable rewards for [Category 2 region](https://github.com/brave/devops/wiki/Region%E2%80%90based-sanctions-blocking#category-2) `Cuba` as there is no BAT icon in the URL bar to enable the rewards
- Confirmed that user cannot see the `Enable Brave Rewards` settings via brave://settings/appeareance
- Confirmed that user can see `Sorry, Brave rewards is not available` message when user open brave://rewards page
- Confirmed that there is no `ads_service` folder created under the app data local folder `...\AppData\Local\BraveSoftware\Brave-Browser-Beta\User Data\Default`

Example | Example | Example | Example
----------|-----------|----------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/31f11062-1eea-44b5-be9c-ca831f3e79f0) | ![image](https://github.com/brave/brave-browser/assets/38657976/ff25c17a-bf87-4176-8c27-02b4bd4d4250) | ![image](https://github.com/brave/brave-browser/assets/38657976/1c05503b-eb8d-412c-9e77-8ec811467e36) | ![image](https://github.com/brave/brave-browser/assets/38657976/e69c412f-12d6-408d-bc78-08f598b23fd5)

</details>
