### ISSUE TITLE
Leo - Remove background graphics on onboarding

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#37344]
## Description 

There was a request to remove the background graphics on the onboarding cards for Leo. This applies to all platforms.
There may be some other updates to the onboarding soon, but that's still under consideration.

<img width="1570" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/d749606b-7ab5-4004-afcc-79d95455870e">

https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=15-11967&mode=design

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.67.52 Chromium: 124.0.6367.91 (Official Build) nightly (x86_64)
-- | --
Revision | a368a1ab342f0a5d4dee4db3f2699f7d02579247
OS | macOS Version 11.7.10 (Build 20G1427)
```

`Light` mode | `Dark` mode
--------------|--------------
<img width="1312" alt="Screen Shot 2024-04-30 at 4 45 06 PM" src="https://github.com/brave/brave-browser/assets/387249/bf76b385-88ed-42e0-bf3d-7d9b1df7616e"> | <img width="1312" alt="Screen Shot 2024-04-30 at 4 45 16 PM" src="https://github.com/brave/brave-browser/assets/387249/eb00300b-cc0d-4648-86cc-9e305bbc1e70">

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` running `Android 13` per https://github.com/brave/brave-browser/issues/37825#issuecomment-2130417582
