### ISSUE TITLE
Crash when disabling Wallet private tab setting when a private tab is already opened

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#37354]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.66.61 Chromium: 123.0.6312.105
Operating System: Linux 6.1.0-18-amd64

URL (if applicable) where crash occurred: 

Can you reproduce this crash? Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. New profile on 1.66.61
2. Open a private tab first
3. Enable Wallet in private tab setting, ensure wallet icon is shown in private tab
4. Create or import wallet on private tab
5. Initiate a send/swap transaction, ensure panel shows up with transaction confirmation
6. Go back to settings and disable Wallet in private tab setting with private tab already opened
7. Initiate transaction in private tab that already has wallet screen or click go back to previous window, browser crashes

https://github.com/brave/brave-core/assets/17010094/9c6c1421-6dac-4f77-bb36-acde4c4ca11b

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/b9200900-aea4-c30b-0000-000000000000
Crash ID: crash/05200900-aea4-c30b-0000-000000000000

cc: @nvonpentz

**Comment by kjozwiak** [comment]
The above requires `1.65.113` or higher for `1.65.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.67.15 Chromium: 124.0.6367.29 (Official Build) nightly (64-bit)
-- | --
Revision | eb30d51fbd9c8d0f2960f50f9df8d07a44a87694
OS | Windows 11 Version 23H2 (Build 22631.3447)
```

The above was basically tested/verified by default while running through https://github.com/brave/brave-browser/issues/37172#issuecomment-2060506060 & https://github.com/brave/brave-browser/issues/37367#issuecomment-2059594227. You won't be able to do the above as you can't disable the `Wallet` via `Private Windows` without relaunching the browser.
