### ISSUE TITLE
Grant flow UI/UX changes

### ISSUE THREAD

**Issue by hollons** [brave/brave-browser#3735]
The terms Grant and Claim need to be eliminated and need to be replaced by language that ensures user understands that Grants are Brave managed and claiming is a mere process to have some funds allocated for user to spend but via Brave.

1. Grant claim dialogs.
There are two types of grant claims that need to be resolved; 
a) The User Grant: In this flow the text should resolve for the detail that these grants are Brave controlled and the claiming process is a mere authorization to keep a BAT sum allocated to the browser to use for auto-contributing and tipping.
b) Same goes for Brave Rewards Grants

Need imagery

2. On clicking the claim button 

<img width="605" alt="Screen Shot 2019-03-15 at 8 08 06 AM" src="https://user-images.githubusercontent.com/33430967/54441234-8e513b00-46f9-11e9-9759-5168074af20a.png">
<img width="466" alt="Screen Shot 2019-03-15 at 8 08 15 AM" src="https://user-images.githubusercontent.com/33430967/54441243-91e4c200-46f9-11e9-9985-47cc19e2ce3f.png">

<img width="284" alt="Screen Shot 2019-03-15 at 8 20 10 AM" src="https://user-images.githubusercontent.com/33430967/54442078-374c6580-46fb-11e9-909f-e8ac9f029e1c.png">

4. For All Ads Rewards, repeat imagery for the grant process in terms of letting user know that BAT can be moved to their wallet if they create a verified wallet with Uphold.

Wallet summary and UI changes
The wallet summary has three clear changes;
Each of wallet states need to be clearly articulated
Grants need to be suggested as Brave owned
Summary should clearly distinguish between what is user funded and what is funded by Brave

<img width="309" alt="Screen Shot 2019-03-15 at 8 22 47 AM" src="https://user-images.githubusercontent.com/33430967/54442259-8db9a400-46fb-11e9-90da-cdbe12dbc639.png">

Wallet UI changes
The wallet should reflect is the user has not claimed a wallet, in which case the wallet panel will ask user to Claim wallet. This will cause the user to sign up for an Uphold account. The flow will encourage user to KYC but it is not mandatory.

If the user has claimed wallet, the wallet should pull balance available in the wallet and reflect the same. The wallet balance should be updated once every hour the user is active and connected to the network.

If the Uphold auth_token expires, the wallet panel will have to show connect back to Uphold button to allow users to authenticate and create a new token. When successful, the wallet balance will be refreshed.

Grant section
The old grants will now be presented as Brave owned and operated. All of the claimed grants will be show as the original specification but will be displayed as Brave contributing on user behalf. 

Summary changes
The summary clearly needs to reflect all transactions that are paid out via user funds and those that are contributed by Brave on users behalf; each separately listed.

Withdraw
A link to withdraw funds must be made to users with Uphold wallet. This link directs with the appropriate URI to Uphold website. User is logged in via url.

Managing wallet states
There are four wallet states for the client to manage;
1. No wallet: this is the anon wallet state. This wallet that will be created will not be used for any function besides signing transactions against a payment ID
2. Uphold without KYC: this wallet operates as a normal wallet. However, it is bound to certain threshold and client should be wary of exceptions re: transactions volume and handle accordingly. 
3. Uphold with KYC: this wallet operates freely without any restrictions and considered fully verified for transactions of any volume
4. Disconnected: Wallet was created, authenticated, and auth_token expired. User has to reauthenticate to get out of this state and any transaction will trigger user notification to reauthenticate if user was not on BR panel. 

Grants notifications to everyone in any of the above states. Users in state-3 can automatically get BAT transferred to their wallet without Captcha but still need to claim the grant (or ads rewards). 

Add Funds flow will work only for wallets in state-2 and state-3 above. If user has a disconnected wallet, the flow will trigger re-authentication and then redirect user to add funds. During add funds, users may get triggered for KYC depending on the transaction size if they are not KYC’d. Users in state-1 will jump to creating an Uphold account via Adds Funds flow widget.

Add Funds flow
The Add funds will call the sandbox API to transfer funds using a credit card, replacing the crypto address’ choices we have. In the Add Funds widget there is user choice to change from default to crypto-in.

<Mandar to add flow>

If user has no Uphold wallet, this will trigger user to create Uphold wallet, followed by KYC, and then trigger the transfer of funds.
If user has an Uphold wallet, this will skip registration and jump to the right place in the flow pending KYC and the sum.

On transfer a confirmation for transfer needs to be presented to the user and the balance of the wallet needs to reflect the new sum. If transfer fails, users goes back to where user started.

Wallet restore

If a user restores a wallet that has been associated with an Uphold wallet then the wallet restore process should prompt the user to re-link their Uphold wallet.

New/Updated notifications 

To be updated notifications
- Tipping “not enough funds” will direct user to add funds flow via sandbox API to add funds via fiat (Credit Card) 

New notifications
- Claim funds: ask user to claim funds in their old wallets (before upgrade)
- Account disconnected: your uphold account needs to re-authenticated

**Comment by HennyBro** [comment]
Wouldn't it make sense to colour the "Ad Rewards" BAT number in green (as a way to show that it's positive) and do the same with the "Total Grants Claimed" and "Rewards from Ads" numbers?

Just a suggestion. I like the design overall, though!
