### ISSUE TITLE
Wallet icon (Toolbar) showing in normal windows even if it is disabled in Settings -> Appearance and context menu `Hide Brave Wallet icon` doesn't work.

### ISSUE THREAD

**Issue by TEMP-ad** [brave/brave-browser#37367]
## Description 

![image](https://github.com/brave/brave-browser/assets/156715894/513dc1e1-01ca-4db2-9a21-e9ff212c07f0)

Also, if you Enable and then Disable the toggle in `brave://settings/appearance`, the icon will disappear, but only for the opened windows; the icon will re-appear in toolbar when you open a new window or restart the browser.

## Brave version (brave://version info)

1.66.61 Chromium: 123.0.6312.105 (Official Build) nightly (64-bit) 
Windows 11 Version 23H2 (Build 22631.3296)

**Comment by TEMP-ad** [comment]
@simonhong

**Comment by simonhong** [comment]
Thanks for reporting! Working now.

**Comment by kjozwiak** [comment]
The above requires `1.65.108` or higher for `1.65.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.65.113 Chromium: 124.0.6367.60 (Official Build) (64-bit)
-- | --
Revision | c1a6c6e73c1f2f1e5bf00a6f0d42065219845887
OS | Windows 11 Version 23H2 (Build 22631.3447)
```

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/22961#issue-2230130298 & https://github.com/brave/brave-core/pull/22961#issuecomment-2043046555, ensured that `Brave Wallet` was correctly being hidden/displayed when enabling/disabling via both `brave://settings/appearance` & `Hide Brave Wallet icon` by right clicking on the `Brave Wallet` icon via the toolbar as per the following:

https://github.com/brave/brave-browser/assets/2602313/bd9f65e1-d45b-40cc-b6b2-a5027f67fd61
