### ISSUE TITLE
[Speedreader] Homepage is loaded in speedreader mode.

### ISSUE THREAD

**Issue by boocmp** [brave/brave-browser#37361]
Found in https://github.com/brave/brave-browser/issues/36583 (case 2)

1. Go to https://time.com/6963032/israel-netanyahu-allies-global-standing/
2. Enable speedreader for this page
3. Go to home page https://time.com

Actual result:
The home page is loaded in speedreader mode.

Expected result:
The home page is loaded as usual.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave	1.66.75 Chromium: 124.0.6367.29 (Official Build) beta (x86_64) 
Revision	ce65b4dd1ac53d203212a8a65e54bf1ec80ab489
OS	macOS Version 11.7.10 (Build 20G1427)
```

example | example | example | example
---------|----------|---------|---------
<img width="1214" alt="Screen Shot 2024-04-11 at 1 52 41 PM" src="https://github.com/brave/brave-browser/assets/387249/d2a792e4-b0fe-4f67-b6ce-46c2c7ce3158"> | <img width="1214" alt="Screen Shot 2024-04-11 at 1 52 44 PM" src="https://github.com/brave/brave-browser/assets/387249/002a913a-d3fd-4323-8889-67355e883cb5"> | <img width="1214" alt="Screen Shot 2024-04-11 at 1 55 11 PM" src="https://github.com/brave/brave-browser/assets/387249/c5671703-7d24-4382-ade8-381ddb5be219"> | <img width="1214" alt="Screen Shot 2024-04-11 at 1 53 42 PM" src="https://github.com/brave/brave-browser/assets/387249/e70ab1db-2414-4d42-ba4a-79ccae7cc08e">
