### ISSUE TITLE
Input field border is barely visible in dark theme unless focused  

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#37360]
## Description 
Input field border is barely visible in dark theme unless focused  

## Steps to reproduce 

   1. Set device to dark theme
   2. Initiate wallet creation process
   3. Enter password fields view
   4. Input box is barely visible until you focus there

## Actual result 
![image](https://github.com/brave/brave-browser/assets/17010094/f9759b44-a5a6-4302-af56-c66d458ae62b)

## Expected result
Better contrast on dark theme

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.65.101

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe @minkyeongshin

**Comment by simoarpe** [comment]
Fixed by https://github.com/brave/brave-browser/issues/37360.

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.69.147 x64 build
- Verified steps from issue description
- Verified input field border is visible even when not focused in  dark theme
<img  alt="image" src="https://github.com/user-attachments/assets/3de2f01f-6832-45c0-9aef-d4086677cb41">
