### ISSUE TITLE
google search dark mode is weird (see screenshot) (ONLY HAPPENS WHEN LOGGED INTO MY GOOGLE ACCT)

### ISSUE THREAD

**Issue by ComfortableMilk4454** [brave/brave-browser#37363]
## Description 

theres this dark highlight around each search result thats not supposed to be there, this only happens when im logged into my google account, if i search signed out it doesnt happen

## Steps to Reproduce

   1. search anything on google while signed in

## Actual result:

![image](https://github.com/brave/brave-browser/assets/43555540/2960f80c-fb92-4dd5-9d1f-5dc969d7194d)

## Expected result:
<img width="1624" alt="image" src="https://github.com/brave/brave-browser/assets/43555540/d3897d83-0dd3-424e-92aa-6b6122294519">

## Reproduces how often: 
every time i search something on google while signed in

## Brave version (brave://version info)
Brave	1.64.116 Chromium: 123.0.6312.105 (Official Build) (arm64) 
Revision	d9090cab16ea606108bdf6edd7466df58d9d76fd
OS	macOS Version 14.4.1 (Build 23E224)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes (when signed into google)
- Can you reproduce this issue with the beta channel? yes (when signed into google)
- Can you reproduce this issue with the nightly channel? yes (when signed into google)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? already disabled
- Is the issue reproducible on the latest version of Chrome? yes

**Comment by rebron** [comment]
@ComfortableMilk4454 Interesting. I can't reproduce your Actual result screenshot with your same query, logged-in. I can't reproduce in Chrome either, logged-in/logged-out. I'm opted-in to a different version of Google Search though so I'm wondering if you're part of cohort we're they're testing layout?

**Comment by rebron** [comment]
The background in your screenshot is very subtle but it is visible.

**Comment by ComfortableMilk4454** [comment]
it fixed itself for me so i think google just fixed it a couple days ago. i made [this post on reddit](https://www.reddit.com/r/chrome/comments/1bwh003/google_search_dark_mode_is_weird_see_screenshot/) too and others were saying they were experiencing the issue so i dont think it was just me.
