### ISSUE TITLE
Remove Goerli Network (Deprecated)

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#37369]
## Description 

Goerli network was deprecated as of April 1st, 2024:
https://www.alchemy.com/blog/goerli-faucet-deprecation

We should remove from pre-loaded networks list

**Comment by kjozwiak** [comment]
The above requires `1.69.130` or higher for `1.69.x` verification 👍

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/34920#issuecomment-2268635142

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.69.147 
- Verified steps from [brave/brave-core#24438](https://github.com/brave/brave-core/pull/24438)
- Verified setting up Goerli as default on older version and upgrading to `1.69.147` removes Goerli from Portfolio and sets Sepolia as default

https://github.com/user-attachments/assets/acbe6432-2d22-47de-801d-1c4b3781afdb
