### ISSUE TITLE
[Wallet] Use new design system for wallet settings modals

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#37362]
## Description 

Update the UI to use the latest style-guide
<img width="591" alt="Screenshot 2024-04-05 at 1 22 22 PM" src="https://github.com/brave/brave-browser/assets/30185185/36838c2c-a9a0-4416-a5b3-aa30f4e34f3e">
<img width="592" alt="Screenshot 2024-04-04 at 4 52 55 PM" src="https://github.com/brave/brave-browser/assets/30185185/1a5461c7-2929-4df9-aaf2-b43d0825bf06">
<img width="460" alt="Screenshot 2024-04-05 at 1 24 31 PM" src="https://github.com/brave/brave-browser/assets/30185185/1a4dea76-957e-4089-9396-ede5e754f45e">
<img width="595" alt="Screenshot 2024-04-05 at 1 25 09 PM" src="https://github.com/brave/brave-browser/assets/30185185/87f347f7-435a-4fa2-809e-b4ebb8b1036a">

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/23361#issuecomment-2172331879
