### ISSUE TITLE
Expose APIs for updating a list of CRX components

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#37370]
During development of https://github.com/brave/brave-core/pull/21868, it was determined that Chromium doesn't expose any APIs for updating a set of CRX components in a single request.

As described in https://github.com/brave/brave-core/pull/21868#discussion_r1475771512, we want to have something like `CrxUpdateService::OnDemandUpdateMultipleIds`. We'll need the ability to change priority between `BACKGROUND` and `FOREGROUND`, as well: these APIs will be used both for user-initiated update checks (e.g. https://github.com/brave/brave-core/pull/22881) and automatic background update checks.

**Comment by diracdeltas** [comment]
is this just for updating our internal crx's? if it can be used to update user-installed extensions then that's a fingerprinting risk since it can be unique.

**Comment by ShivanKaul** [comment]
The intention was only Brave-pushed components.

**Comment by mherrmann** [comment]
> it was determined that Chromium doesn't expose any APIs for updating a set of CRX components in a single request.

I'm not sure if there's a difference between on-demand and background updates. But the last time I worked with the code, upstream absolutely did have an API for updating multiple components in the background with a single request. See SequentialUpdateChecker in our code. Maybe it's different for on-demand updates.

**Comment by mherrmann** [comment]
@goodov mentioned [here](https://github.com/brave/brave-core/pull/23169#issuecomment-2074666154) now that upstream has APIs for batch updates for background update checks, but not for on-demand update checks. However, we disable batching with a class called `SequentialUpdateChecker`. I implemented this some years ago and explained the reasoning in comments in the source code.

I wonder if we really need batch update checks for on-demand updates. And maybe we can find an alternative to the `SequentialUpdateChecker` solution that gives us batch update checks for background updates. I outline such an alternative in https://github.com/brave/brave-core/pull/23169#pullrequestreview-2019469177.
