### ISSUE TITLE
Feature Request: Re-enable "Close Window" Confirmation Prompt

### ISSUE THREAD

**Issue by MTHALO** [brave/brave-browser#37372]
## Feature Request: Re-enable "Close Window" Confirmation Prompt

**Current Behavior:**

Brave currently lacks a way to re-enable the confirmation prompt when closing a window with multiple tabs. If a user selects "Don't show me this message again" on the prompt, there seems to be no option to bring it back within the browser settings.

**Desired Behavior:**

This feature request proposes the implementation of an option within Brave settings to re-enable the confirmation prompt that appears before closing a window with multiple tabs. This prompt should ask the user for confirmation like "Are you sure you want to close all [number] tabs?" before closing the window.

**Benefits:**

* **Prevents accidental tab closure:**  Having the confirmation prompt helps users avoid accidentally closing multiple tabs when they only intended to close a single one.
* **Improved user control:**  The prompt provides users with more control over their browsing session and prevents frustration from unintended window closure.

**Additional Considerations:**

* The re-enabled confirmation prompt should offer a clear checkbox or toggle option within the Brave settings menu, likely under the "Windows" or "Tabs" section.
* The prompt itself should offer clear options like "Close all tabs" and "Cancel" for user convenience.

**Thank you for considering this feature request. Bringing back the option to enable the close window confirmation prompt will improve user experience and prevent accidental data loss.**

**Comment by rebron** [comment]
@MTHALO Can you go here: brave://settings/braveHelpTips The middle setting should give you that prompt back.
 
<img width="748" alt="Screenshot 2024-04-08 at 10 43 39 AM" src="https://github.com/brave/brave-browser/assets/5951041/5d6be4cc-d969-4a3c-aa38-c4f6a4af4b2a">

**Comment by MTHALO** [comment]
> @MTHALO Can you go here: brave://settings/braveHelpTips The middle setting should give you that prompt back.
> 
> <img alt="Screenshot 2024-04-08 at 10 43 39 AM" width="748" src="https://private-user-images.githubusercontent.com/5951041/320597580-5d6be4cc-d969-4a3c-aa38-c4f6a4af4b2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MTg4MDAsIm5iZiI6MTcxMjYxODUwMCwicGF0aCI6Ii81OTUxMDQxLzMyMDU5NzU4MC01ZDZiZTRjYy1kOTY5LTRhM2MtYWEzOC1jNGY2YTRhZjRiMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMjMyMTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjMwODkzNTkzNTA2NzUwOWY5MTYyMjYzYjRiMTRjZWQxYTc5NTQwMWIxNjFjMzA0NWVmN2NjNGNjYjk1ZTllNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nb7rxIbyDvYrLZSOTHsl1MXygBaq8D3HwudefUX7H44">

@rebron Thanks for the response you have no idea how much I searched for this you're a lifesaver.
