### ISSUE TITLE
Wallet icon appears on toolbar when disabled in settings, after recent Nightly updates.

### ISSUE THREAD

**Issue by sillyjaybird** [brave/brave-browser#37376]
Could not find similar open issues.

Issue description: 

1. Wallet icon appears on toolbar _when already disabled in settings_ after recent Nightly updates.
2. Right-click to hide Wallet doesn't work. 
3. _Only way to remove Wallet from toolbar is to enable in settings and then disable._

After recent updates Wallet icon reappears on toolbar. Rinse and repeat.

   1. Update Nightly with "Show Wallet button" already disabled.
   4. Wallet icon appears on toolbar.
   5. Attempt unsuccessfully to hide via right-click and "Hide wallet icon" in toolbar.
   6. Go to Settings > Appearance > Show Brave Wallet button > Enable, then disable.
   7. Wallet icon is hidden.
   8. Wait till next update available, and update.
   9. Wallet icon reappears on toolbar.
   10. Repress feelings of annoyance. :)

 Actual result: Wallet icon keeps reappearing on toolbar

Expected result: Wallet remains hidden when disabled in settings.

Reproduces how often: Last 2 or 3 updates

Desktop Brave version: v 1.66.62 Nightly on Windows. Not Android.

Version/Channel Information: v 1.66.62 Nightly
- Can you reproduce this issue with the current release?   No
- Can you reproduce this issue with the beta channel?      N/A
- Can you reproduce this issue with the nightly channel?  Yes, after last 2 updates when Wallet icon appeared. Not reproducible since.

- Does the issue resolve itself when disabling Brave Shields?  N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

Miscellaneous Information: Windows 11 Pro, latest stable build

**Comment by arch-btw** [comment]
Same issue on Linux Nightly. Also right clicking on it and selecting "Hide Brave Wallet Icon" doesn't work either.

`Version 1.66.63 Chromium: 123.0.6312.105 (Official Build) nightly (64-bit)`

**Comment by arch-btw** [comment]
Found this: https://github.com/brave/brave-browser/issues/37367

**Comment by sillyjaybird** [comment]
@arch-btw I missed that with my search.

**Comment by simonhong** [comment]
Thanks for reporting. closed as duplicated.
