### ISSUE TITLE
Rotating IPNS Keys doesn't auto-restart the node

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#37388]
## Description 

Rotating IPNS Keys doesn't auto-restart the server

## Steps to Reproduce

   1. Enable IPFS and set resolve method to localhost
   2. Open `brave://settings/ipfs/keys` and click on rotate key button
   3. Enter a valid name and click on submit
   4. IPFS node stops and the name prompt doesn't auto-close
   5. Closing the modal shows blank for `brave://settings/ipfs/keys`
   6. Go back to `brave://settings/web3`, `Set up your IPNS keys` section is hidden since node is stopped
   7. Restart the node and reload `brave://settings/web3`, IPNS Key section is shown again

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/57a6477c-e1af-49e4-b73f-676fc52cb015

## Expected result:
Should auto-restart the node when keys are rotated

## Reproduces how often: 

Easy

## Brave version (brave://version info)

`Version: kubo/0.26.0/brave`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @vadimstruts

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)
