### ISSUE TITLE
Refactor onboarding fragment creation adapter

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#37396]
## Description 

Refactor oboarding adapter where the new fragments are instantiated reducing memory comsuption and preventing Android framework callbacks from being fired multiple times.

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.67.98 x64 Beta build
- Verified steps from [brave/brave-core#23127](https://github.com/brave/brave-core/pull/23127)
- Verified new wallet creation works as expected
- Verified restore wallet works as expected
- Verified backup wallet from within wallet for both new wallet works as expected
