### ISSUE TITLE
Add delay on Wallet creation screen during onboarding flow

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#37395]
## Description 

Add a small delay of 700 milliseconds on Wallet creation screen during onboarding flow to prevent UI from flickering

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.67.98 x64 Beta build
- Verified steps from [brave/brave-core#23025](https://github.com/brave/brave-core/pull/23025)
- Verified noticeable delay is added to the Creating Wallet screen during new wallet creation
