### ISSUE TITLE
Forced to keep Leo AI enabled, there is no way to  disable it. 

### ISSUE THREAD

**Issue by InvisibleRasta** [brave/brave-browser#37394]
I am using Brave 1.64.116 Chromium: 123.0.6312.105 (Official Build) (64-bit) 
What is the problem with leo.. I keep disabling it and it comes back on as soon as i open the sidebar...
I disabled it like 20 times alredy and as soon as I open the sidebar its activated again.
I also removed it from the sidebar countless times. As soon as I open the sidebar again it just reactivates itself.
Why are you hardcoding this crap and give us no option to permanently disable it as any other option.
![how-to-disable-leo-v0-y2ku87afp9tc1](https://github.com/brave/brave-browser/assets/30435428/3597a19e-afb8-46ea-b825-37e3a380814d)

STR:
1. Launch Brave
2. Open leo side panel by clicking leo side panel icon
3. Close by clicking leo side panel icon
4. Remove leo panel icon via its context menu
5. Click toolbar sidebar button

Actual result:
Leo panel is opened
Expected:
Other panel should be choosen as user removes leo panel icon

**Comment by rebron** [comment]
cc: @simonhong This looks like a bug from the recent landing of setting Leo as default side panel. If a user hides Leo and doesn't choose anything else, because Leo is set as default side panel it will reappear.

@InvisibleRasta Thanks for filing the bug. If you choose, bookmarks or reading list first and then remove Leo side panel then it should work as expected for you as a workaround for now. We'll get this one fixed.

**Comment by InvisibleRasta** [comment]
how do i chose that? every time i open the sidebar no matter what leo opens up

**Comment by rebron** [comment]
@InvisibleRasta Open the sidebar and select the bookmarks or reading list button.

**Comment by InvisibleRasta** [comment]
It was just coming back, Not able to fix it. I ended up uninstalling the browser. I really liked the browsing experience but all the useless bloat we are forced to use makes no sense. 
Why don't you make extensions instead of adding and forcing useless things to people.

**Comment by rebron** [comment]
@InvisibleRasta If you just click on the bookmarks sidebar icon to open it, it'll remember that choice as your last selection.

**Comment by simonhong** [comment]
@rebron we have a logic that adding back the opened panel's icon when its icon is hidden in sidebar.
It's intended to give that icon again to users when user opens that panel explicitely.
I think we should not choose hidden panel item when user clicks sidebar toolbar button.

**Comment by simonhong** [comment]
fixing now.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```

```

Launch Brave and open bookmarks side panel
Close bookmarks side panel
Remove bookmarks side panel item
Click sidebar toolbar button
Check non-bookmarks side panel is opened

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```

Brave | 1.67.56 Chromium: 124.0.6367.91 (Official Build) nightly (x86_64)
-- | --
Revision | 5670584eb8a1807ab8ac1584fb099bd21ec1e381
OS | macOS Version 11.7.10 (Build 20G1427)


```

### Steps:

1. Launch Brave and open bookmarks side panel
2. Close bookmarks side panel
3. Remove bookmarks side panel item
4. Click sidebar toolbar button
5. Check non-bookmarks side panel is opened

**Comment by stephendonner** [comment]
## (Additional) Verification `IN-PROGRESS` using

```
Brave | 1.67.90 Chromium: 125.0.6422.60 (Official Build) beta (x86_64)
-- | --
Revision | 64f9eec1a854079c3e529e908ca300071afb1f32
OS | macOS Version 14.5 (Build 23F79)
```

### Steps:
1. install `1.67.90`
2. Launch Brave
3. Open leo side panel by clicking leo side panel icon
4. Close by clicking leo side panel icon
5. Remove leo panel icon via its context menu
6. Click toolbar sidebar button

Expected:
Other panel should be choosen as user removes leo panel icon
