### ISSUE TITLE
Implement hidden networks in Settings > Brave Wallet > Networks

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#37397]
## Description 

The Networks section available in Settings > Brave Wallet > Networks should show all the available networks and indicate which ones are currently hidden offering a similar UI as Desktop.

<img width="677" alt="Settings_-_Wallet_Networks" src="https://github.com/brave/brave-browser/assets/3308503/c644f39b-d428-4b68-9063-891592dcfa02">

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.68.99
- Verified steps from [brave/brave-core#23937](https://github.com/brave/brave-core/pull/23937)
- Verified network settings is shown similar to Desktop
- Verified selected network is shown in bold
- Verified able to hide network by tapping on the view button
- Verified hidden network is not shown in Portfolio settings
- Verified able to add new network
- Encountered [#39417](https://github.com/brave/brave-browser/issues/39417)

https://github.com/brave/brave-browser/assets/17010094/d6f4ef13-bbf5-42ef-b37f-e8b8c2e79d01
