### ISSUE TITLE
Make Swap and Send Action Views in Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#37407]
## Description 

We need to make the `Swap` and `Send` screens `Action` vies in the Wallet `Panel`.

![Screenshot 1](https://github.com/brave/brave-browser/assets/40611140/ea9917ee-58a0-4677-a301-6be86bb23fdb)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.66.95 Chromium: 124.0.6367.91 (Official Build) beta (64-bit)
-- | --
Revision | e1f8e3c95a12986231bc8226b78a951233e7c026
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22973](https://github.com/brave/brave-core/pull/22973)
- Verified `Send` / `Swap` on panel now looks like modals with `Expand` and `Close` buttons
- Encountered [#37953](https://github.com/brave/brave-browser/issues/37953)

https://github.com/brave/brave-browser/assets/17010094/a5d4717f-cac3-4424-b63e-7a2bc5b9bf2b
