### ISSUE TITLE
AIChat: Enable migration code

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#37405]
Currently AIChat's keys are not being migrated and stuck to older values. We need to enable it.

**Comment by LaurenWags** [comment]
Requires `1.65.120` or higher for testing.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.65.120 Chromium: 124.0.6367.60 (Official Build) (64-bit) 
Revision	e956d45423c37e9f83f250e5a0405bf1fbb40e4d
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that the value for `default_model_key` in `brave://pref-internals` is NOT `chat-default`

![Screenshot 2024-04-24 at 10 41 19 AM](https://github.com/brave/brave-browser/assets/17885425/17332dae-69a3-4a75-ac55-11f47da224ea)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.65.120 Chromium: 124.0.6367.60 (Official Build) (64-bit)
-- | --
Revision | e956d45423c37e9f83f250e5a0405bf1fbb40e4d
OS | Windows 10 Version 22H2 (Build 19045.4355)
```
