### ISSUE TITLE
Navigation bar styling for Downloads manager not reflected in Private or Tor Window mode

### ISSUE THREAD

**Issue by cndouglas** [brave/brave-browser#3740]
## Description 
The navigation bar at the top of the Downloads page (that shows Settings, Brave Rewards, History, Bookmarks, and Downloads) looks different when the Downloads page is viewed in a private window. This only applies to the Downloads page because the other pages may only be opened in a normal window.

## Steps to Reproduce
   1. Open a new private window.
   2. Go to brave://downloads/.

## Actual result:
The navigation bar has a solid blue background and uses a serif font.
![](https://user-images.githubusercontent.com/19424103/54450155-c23e5780-471d-11e9-9038-7d557c18c142.png)

## Expected result:
The navigation bar should match the normal one with a pink/purple background and a sans-serif font.
![](https://user-images.githubusercontent.com/19424103/54450187-d1250a00-471d-11e9-91a4-addbc0d3d679.png)

## Reproduces how often: 
Always

## Brave version (brave://version info)
Brave | 0.63.9 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes, 0.63.9.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Not applicable.
- Is the issue reproducible on the latest version of Chrome? Not applicable.

**Comment by bsclifton** [comment]
cc: @petemill

**Comment by rebron** [comment]
Related to https://github.com/brave/brave-browser/issues/3503.
This issue is showing up on Guest Windows and Tor Window (because it's set up a guest window). Private window is working properly as its showing settings in a normal window.

**Comment by rebron** [comment]
<img width="1287" alt="Screen Shot 2019-10-09 at 11 47 33 AM" src="https://user-images.githubusercontent.com/5951041/66510794-9a805980-ea8a-11e9-9f67-a82c0801b3cb.png">
Settings and Extensions are being redirected to Normal Window and maybe consider doing the same for download manager for the fix?

**Comment by petemill** [comment]
This does not seems to be an issue anymore

**Comment by rebron** [comment]
No longer an issue in Private or Tor Window mode.
Checked using: 

Brave | 1.11.77 Chromium: 83.0.4103.116 (Official Build) beta (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.16 (Build 20A4299v)

![Screen Shot 2020-06-30 at 12 21 02 PM](https://user-images.githubusercontent.com/5951041/86167906-32681c80-bacc-11ea-9c1e-26fa3e951ab2.png)
