### ISSUE TITLE
Shortcuts and User Intents not working when app is not in background

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-browser#37403]
## Description: 

The shortcuts are not working when application is not in background and killed totally. 

It is working when the application in background. But If the application is killed totally the action doesnt perform designated behaviour and only app is opened.

## Steps to Reproduce 
  1. Run a shortcut like Open Playlist
  2. Kill the application and remove it from background
  3. Run the shortcut

## Actual result: 
It only open the application if the application is not in background.

https://github.com/brave/brave-browser/assets/6643505/45c146de-783e-406e-bcce-3ce5f7f05fce

## Expected result:

Desired action should be performed regardless of application status.

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily Reproduced

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Y
- Can you reproduce this issue with the previous version of the current build from TestFlight? Y
- Can you reproduce this issue with the current build from AppStore? Y

### Device details: 
Any

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari?

**Comment by LaurenWags** [comment]
Requires `1.66.92` or higher to test

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.5
Brave build: 1.66 (95)
BraveCore: 1.66.95 (124.0.6367.91)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/37403#issue-2231726629
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `shortcut` can be used when Brave is opened in the background or closed completely

---------------------------

https://github.com/brave/brave-browser/assets/128532965/3890b096-caf2-4813-836a-cd9c2814b97c
