### ISSUE TITLE
[Wallet] Cache pin-able image checks

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#37420]
## Description 

We should cache results when checking if the NFT metadata image is pin-able to IPFS

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.90 Chromium: 124.0.6367.82 (Official Build) beta (64-bit)
-- | --
Revision | 803a4c629341791205b744969c48b8da9f2cfa4d
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22982](https://github.com/brave/brave-core/pull/22982)
- Verified token logos in the portfolio, buy and sell pages continue to load properly without regressions
- Verified pin-ability details in the NFT details screen continue to display without regressions

https://github.com/brave/brave-browser/assets/17010094/75558ff7-0fcb-4e8e-a372-79c0963bd25e
