### ISSUE TITLE
BraveUpdateSetup.exe flagged by VirusTotal (DrWeb)

### ISSUE THREAD

**Issue by ubalklen** [brave/brave-browser#37426]
In what is probably a false positive, scanning BraveUpdateSetup.exe using [VirusTotal](https://www.virustotal.com/) flags it as Trojan.Siggen27.31802, according to only one vendor (DrWeb).

[Link](https://www.virustotal.com/gui/file/4b1a40f106cabf2a5b2c660cacc391eb6fc5121bbed12dab6f125105d040ad32/detection) to the report.

**Comment by bsclifton** [comment]
@ubalklen thanks for the report! Can you share where on disk the `BraveUpdateSetup.exe` file is?

Basically, there's a false positive reporter here:
https://support.drweb.com/new/detection_issue/?lng=en

I'd like to fill in that report - but I'm not sure which exact file triggered it for you. Please let us know!

**Comment by bsclifton** [comment]
OK quick update - I downloaded the latest installer for Windows and the installer executable was enough to flag. I'll report as false positive and report back here:
![image](https://github.com/brave/brave-browser/assets/4733304/8a42d07f-a807-48c5-a272-6ca36f5d5cc4)

**Comment by ubalklen** [comment]
> @ubalklen thanks for the report! Can you share where on disk the `BraveUpdateSetup.exe` file is?

It's in the regular Downloads folder. I'm not sure if this matters since the flagging happened after I had manually uploaded the executable to VirusTotal. In fact, VirusTotal caches reports, so what I got initially was the report generated previously by someone else.

I see you already intend to report as a false positive to Dr.Web. Let me know if you need any more help.

**Comment by bsclifton** [comment]
![image](https://github.com/brave/brave-browser/assets/4733304/9c22bc4e-56cc-4d8f-b641-28b247eddd3a)

**Comment by ubalklen** [comment]
I can see VirusTotal is not flagging the executable anymore:

![image](https://github.com/brave/brave-browser/assets/42127323/5af14c1a-e538-4161-92d4-c76a8e326dbe)

[Link to the new report](https://www.virustotal.com/gui/file/d704b6d0eaddda3606a4568860740008dbe2ca6797929f5a3c1341f21bc5ccbe)

I'm closing it. Thank you very much @bsclifton!

**Comment by bsclifton** [comment]
Just to close the loop, they did remove it officially 😄 

![image](https://github.com/brave/brave-browser/assets/4733304/dca35609-18ce-4d45-973f-e1098b3e0a4e)

Thanks again for reporting @ubalklen
