### ISSUE TITLE
Toggling shields on webpage will present cookie related dialog [C124]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#37435]
## Description 
Toggling shields on webpage will present cookie related dialog

New dialog in C124

## Steps to reproduce 

   1. Fresh profile
   2. Open webpage
   3. Disable shields in panel and then re-enable
   4. Observe address bar

## Actual result 
![Screenshot 2024-04-09 at 3 34 25 PM](https://github.com/brave/brave-browser/assets/17885425/39728e41-d553-4f35-96b6-173211f6aeff)

## Issue reproduces how often 
Easily on fresh profile

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes (C124)

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung devices
   - Android version: 13
   
## Brave version
`1.66.70 Chromium: 124.0.6367.29`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? TBD

**Comment by kjozwiak** [comment]
The above requires `1.65.112` or higher for `1.65.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP31.240322.018 release-keys
Brave build: 1.65.112
Chromium: 124.0.6367.29 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/37435#issue-2234231417
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `third-party cookies warning` is hidden/not shown

---------------------------

https://github.com/brave/brave-browser/assets/128532965/c6b63860-b4f5-4c32-a275-24daab41cfad
