### ISSUE TITLE
`Disable Brave VPN` bottom sheet modal is not fully shown while device is in `Landscape` mode

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#37431]
## Description 

The `Disable Brave VPN` bottom sheet modal is not fully shown while the device is in `Landscape` mode.

## Steps to reproduce 

   1. Launch Brave
   2. Enable VPN
   3. While `VPN` is ON rotate the device (phone or tablet) into `Landscape` mode
   4. Three-dot menu > Brave VPN
   5. Tap to disable it > *Observe*

## Actual result 

The `Disable Brave VPN` bottom sheet modal is not fully shown while the device is in `Landscape` mode. In the past, we had a similar issue with `Brave News`, which has been fixed already.

|Tablet|Phone|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/45619ffd-ed63-4140-aed2-1151675a0acc) | ![2](https://github.com/brave/brave-browser/assets/128532965/43c85393-5a92-42ed-a90c-ba123ffed079) |

## Expected result

The `Disable Brave VPN` bottom sheet modal must be fully shown while the device is in `Landscape` mode.

|Tablet|Phone|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/999b431d-5012-422c-b97b-dafc0bc3d297) | ![2](https://github.com/brave/brave-browser/assets/128532965/28c99b13-dc59-48bf-b62a-b8a0f0995314) |

## Issue reproduces how often 

`Easily reproduced`

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? YES
- Can you reproduce this issue with the current Play Store Beta version? YES
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone and Tablet
   - Android version: ANY
   
## Brave version

```
Brave build: 1.66.70
Chromium: 124.0.6367.29 (Official Build) canary (64-bit)
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by hffvld** [comment]
The same issue was observed for the `Liking Brave?` bottom sheet modal.

Device is in `Landscape` mode: Brave > Three-dot menu > Settings > Scroll down > Rate Brave > *Observe*

---------------

|Actual|Expected|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/2c175704-9f7c-4e64-9ba2-3dfd59db8bf2) | ![2](https://github.com/brave/brave-browser/assets/128532965/663918ff-327c-4b01-ae63-5cdb5bc8cb19) |

**Comment by deeppandya** [comment]
@hffvld i will be creating a separate issue for https://github.com/brave/brave-browser/issues/37431#issuecomment-2046001756.

**Comment by deeppandya** [comment]
@hffvld created the issue https://github.com/brave/brave-browser/issues/37870 for rate brave

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240426.022 release-keys
Brave build: 1.67.85 
Chromium: 125.0.6422.60 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/37431#issue-2234198983
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Disable Brave VPN` bottom sheet modal is fully shown while the device is in `Landscape mode`.
- Verified the the behavior is correct during device rotation while the `Disable Brave VPN` bottom sheet modal is already opened

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/83871131-2030-44cb-9aed-769fa04600c8) | ![2](https://github.com/brave/brave-browser/assets/128532965/aa51a281-d73a-467c-ba5f-3815b887e55e) |

https://github.com/brave/brave-browser/assets/128532965/55a3fb6d-f1d7-411f-a5c6-6a790595a3a8
