### ISSUE TITLE
[C124] Blue color scrollbar for bookmarks & reading list in the sidebar panel

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#37442]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/36346. Due to C124 changes for Bookmarks & Reading list, blue color, narrow scrollbar shown in the sidepanel for both bookmarks & reading list. 

## Steps to Reproduce

   1.  install 1.66.70
   2. launch Brave
   3. click on Readling list in the sidebar
   4. add few pages to reading list via Add current tab to activate scroll bar
   5. add few bookmarks via Add current tab to activate scrollbar
   

## Actual result:

Scrollbar color shown blue

![image](https://github.com/brave/brave-browser/assets/6786187/5ed760d3-27a2-49f2-88a8-f05cd1132d2c)
![image](https://github.com/brave/brave-browser/assets/6786187/905e857e-ece9-4a10-b52d-4c23d6285bfe)

https://github.com/brave/brave-browser/issues/37434
## Expected result:
Nala colors?

## Brave version (brave://version info)

```
Brave | 1.66.70 Chromium: 124.0.6367.29 (Official Build) nightly (64-bit)
-- | --
Revision | 7f64bd490824f00eff78cc4c4688371b28e09031
OS | Windows 11 Version 23H2 (Build 22631.3374)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@max @rebron 
cc: @aguscruiz @brave/qa-team

**Comment by kjozwiak** [comment]
Labelling as `QA/Blocked` as the above will also be uplifted into `1.65.x` via https://github.com/brave/brave-core/pull/22984.

**Comment by kjozwiak** [comment]
The above requires `1.65.110` or higher for `1.65.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.65.112 Chromium: 124.0.6367.29 (Official Build) (x86_64) 
Revision	1ccdfe627ad458201908007edf699da1f3bfc02b
OS	macOS Version 13.6.6 (Build 22G630)
```

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.65.112 Chromium: 124.0.6367.29 (Official Build) (64-bit)
-- | --
Revision | 1ccdfe627ad458201908007edf699da1f3bfc02b
OS | Windows 10 Version 22H2 (Build 19045.4170)

```
Confirmed scrollbar color is not blue:

Dark Theme | Light Theme
--- | ---
![image](https://github.com/brave/brave-browser/assets/38657976/3dfae0f7-3159-429b-b2f1-c16b891803d2) | ![image](https://github.com/brave/brave-browser/assets/38657976/a7e95392-6af5-426b-b9f2-d16117e1f326)
