### ISSUE TITLE
[CR 124] "Card" look displayed for the list of bookmarks and readlists in the sidebar panel

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#37444]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/36346.  Due to C124 changes for Bookmarks & Reading list, after adding bookmarks or pages to reading list in the sidepanel in the dark theme, "card" look is shown.  This is not an issue in with light theme.

## Steps to Reproduce

   1.  install 1.66.70
   2. launch Brave
   3. add bookmarks to display in the sidebar bookmarks panel
   4. add page to display in the sidebar reading list panel
    
## Actual result:

bookmarks | reading list
---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/7e658a64-5f03-49f4-a0e3-47cc5147f6df)|![image](https://github.com/brave/brave-browser/assets/98358127/df910d36-a3b6-41be-88f3-7e91505f5074)

## Expected result:
![image](https://github.com/brave/brave-browser/assets/98358127/41f1fb6f-d351-4d28-8ad6-892bfb749a12)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.66.70 Chromium: 124.0.6367.29 (Official Build) nightly (64-bit)
-- | --
Revision | 7f64bd490824f00eff78cc4c4688371b28e09031
OS | Windows 11 Version 23H2 (Build 22631.3374)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@max @rebron 
cc: @aguscruiz @brave/qa-team

**Comment by simonhong** [comment]
Checking..

**Comment by kjozwiak** [comment]
Labelling as `QA/Blocked` as the above will also be uplifted into `1.65.x` via https://github.com/brave/brave-core/pull/22984.

**Comment by kjozwiak** [comment]
The above requires `1.65.110` or higher for `1.65.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.65.112 Chromium: 124.0.6367.29 (Official Build) (x86_64) 
Revision	1ccdfe627ad458201908007edf699da1f3bfc02b
OS	macOS Version 13.6.6 (Build 22G630)
```
