### ISSUE TITLE
[iOS/Wallet] add support for retry on Solana dropped tx

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#37443]
once core PR https://github.com/brave/brave-core/pull/22991 is merged.
please add support for retry on solana dropped tx. currently, iOS only has retry implemented for EVM txs.

Note: according to the description from the [https://github.com/brave/brave-core/pull/22991](22991)
- Swap transactions cannot be retired as it makes more sense to start over with a new quote from UI flow.
- Partial signed transactions cannot be retried unless using a durable nonce, because dApp needs to re-sign the new transaction too.

Will need verification but iOS should be contained to this boolean check to support retry on Solana throughout iOS native wallet:
https://github.com/brave/brave-core/blob/master/ios/brave-ios/Sources/BraveWallet/Extensions/BraveWalletExtensions.swift#L125-L129

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.5.1 running 1.67 (107)
- Verified steps from [brave/brave-core#23153](https://github.com/brave/brave-core/pull/23153)
- Verified dropped Solana transaction shows retry transaction

https://github.com/brave/brave-browser/assets/17010094/37138ee4-79e8-47d9-83d3-c4b6c1256749
