### ISSUE TITLE
[CR 124] Weird item deleted feedback bubble color from bookmarks side panel

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#37451]
## Steps to Reproduce

   1. Open bookmarks side panel
   2. Delete any item from panel
   3. 

## Actual result:

![image](https://github.com/brave/brave-browser/assets/6786187/8904df1e-65ce-4fde-974a-5ddc5e2e063b)

## Expected result:
![image](https://github.com/brave/brave-browser/assets/6786187/c5149866-f159-4882-86f1-be2db44a62e9)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Labelling as `QA/Blocked` as the above will also be uplifted into `1.65.x` via https://github.com/brave/brave-core/pull/22984.

**Comment by kjozwiak** [comment]
The above requires `1.65.110` or higher for `1.65.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.65.112 Chromium: 124.0.6367.29 (Official Build) (x86_64) 
Revision	1ccdfe627ad458201908007edf699da1f3bfc02b
OS	macOS Version 13.6.6 (Build 22G630)
```
