### ISSUE TITLE
[Brave News]: Record News "session start" event if existing page is used after inactivity

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#37452]
If an News card page has been inactive for an hour, and a user uses the page after the period of inactivity, record a "session start" event for P3A purposes.

cc @LorenzoMinto

**Comment by LorenzoMinto** [comment]
Can we make sure this also counts towards DAUs? I.e. if a user has left the tab open and then goes back to it the next day, it's a new session and also records the DAU

**Comment by mattmcalister** [comment]
> if a user has left the tab open and then goes back to it the next day, it's a new session and also records the DAU

makes sense, imo

**Comment by DJAndries** [comment]
> Can we make sure this also counts towards DAUs? I.e. if a user has left the tab open and then goes back to it the next day, it's a new session and also records the DAU

yep, any metrics that are triggered via the session start event will be updated.
