### ISSUE TITLE
Update `premiumPricing` for Leo on Desktop paywall

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#37459]
Use the same `USD$14.99` base plan Leo Premium pricing on Desktop as required on Android and iOS app stores. Account site and backend have the updated pricing in prod, so we just need to reflect the correct price in the Leo Premium paywall. 

- [ ] components/ai_chat/resources/page/components/premium_suggestion/index.tsx
- [ ] components/resources/ai_chat_ui_strings.grdp

See spec: https://docs.google.com/document/d/1t__lhbiWDqesNMR6lPTfaaSZlxZ8VLZWQzZ84OMvcew/edit

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.67.82 Chromium: 125.0.6422.41 (Official Build) beta (x86_64)
-- | --
Revision | cbebefd4c702801af65a196ba9701a907ed0d292
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.67.82`
2. launched Brave
3. opened a new-tab page
4. loaded `nbcnews.com`
5. clicked on `Leo` in the sidebar
6. clicked on `Summarize this page`
7. ran multiple queries until I hit the `Response rate limited reached` dialog
8. examined the monthly USD price for `Leo` Premium

### Confirmed USD `$14.99/month`

`Premium`-upsell dialog | `account.brave.com` pricing
-------------------------|------------------------------
<img width="1509" alt="Screen Shot 2024-05-13 at 3 33 20 PM" src="https://github.com/brave/brave-browser/assets/387249/1c1a876c-b745-4ccc-81e9-cf0a8920906b"> | <img width="1509" alt="Screen Shot 2024-05-13 at 3 33 29 PM" src="https://github.com/brave/brave-browser/assets/387249/5a17b0af-e4d8-48fe-80aa-f7fbf9e33a5e">

### Reproduced the `$15/month` pricing in

```
Brave | 1.66.105 Chromium: 125.0.6422.41 (Official Build) (x86_64)
-- | --
Revision | ba88d7bb175a55287d14014823d5da31fe9c8a47
OS | macOS Version 11.7.10 (Build 20G1427)
```


<img width="1611" alt="Screen Shot 2024-05-13 at 3 44 49 PM" src="https://github.com/brave/brave-browser/assets/387249/2a2b416f-436c-4f8c-9dcf-6a612272d588">

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.67.82 Chromium: 125.0.6422.41 (Official Build) beta (64-bit)
-- | --
Revision | cbebefd4c702801af65a196ba9701a907ed0d292
OS | Windows 10 Version 22H2 (Build 19045.4355)
```

![image](https://github.com/brave/brave-browser/assets/387249/d828fc87-efeb-4ff9-bf5d-59c86a31cf77)
