### ISSUE TITLE
Red highlight shown on the Brave VPN toggle in the hamburger menu

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#37450]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/36346. Due to C124 changes, the toggle for 

## Steps to Reproduce

   1.  install 1.66.70
   2. launch Brave
   3. subscribe to enable VPN via VPN panel
   4. hover over on toggle via hamburger menu >> Brave VPN
   
## Actual result:

Red highlight shown

example  
----  
![image](https://github.com/brave/brave-browser/assets/98358127/a66b57f4-7a7b-4a47-888c-d04002dd37e0)

## Expected result:
![image](https://github.com/brave/brave-browser/assets/98358127/dff69c69-5d4c-4fe5-98ef-2712689d50ef)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.66.70 Chromium: 124.0.6367.29 (Official Build) nightly (64-bit)
-- | --
Revision | 7f64bd490824f00eff78cc4c4688371b28e09031
OS | Windows 11 Version 23H2 (Build 22631.3374)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@mkarolin @rebron 
cc: @brave/qa-team

**Comment by kjozwiak** [comment]
Labelling as `QA/Blocked` as the above will also be uplifted into `1.65.x` via https://github.com/brave/brave-core/pull/22984.

**Comment by kjozwiak** [comment]
The above requires `1.65.110` or higher for `1.65.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.65.112 Chromium: 124.0.6367.29 (Official Build) (64-bit)
-- | --
Revision | 1ccdfe627ad458201908007edf699da1f3bfc02b
OS | Windows 10 Version 22H2 (Build 19045.4170)
```
- Confirmed that the Red highlight isn't shown on the Brave VPN toggle via Hamburger menu
![image](https://github.com/brave/brave-browser/assets/38657976/76004363-bcce-4391-95b6-792da1fb46d6)
