### ISSUE TITLE
Move show memory usage setting to Tabs section

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#37462]
## Description 

We have a new setting "Show memory usage on tab hover preview card" in brave://settings/appearance under Appearance. Setting should be moved to the Tabs section below "Tab hover mode" 

## Steps to Reproduce

   1. Use Brave 1.66.70 and higher
   2. Go to brave://settings/appearance
   3. Notice placement of new setting.

## Actual result:

<img width="719" alt="Screenshot 2024-04-10 at 7 57 22 AM" src="https://github.com/brave/brave-browser/assets/5951041/c053a4a4-b7e1-49d8-8900-8eda9c9821ff">
<img width="701" alt="Screenshot 2024-04-10 at 7 53 44 AM" src="https://github.com/brave/brave-browser/assets/5951041/e8d9f10e-26f8-4b3b-b904-3ea2338c5d73">

## Expected result:
See description

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by kjozwiak** [comment]
Adding `QA/Blocked` as the above will also be uplifted into `1.65.x` alongside https://github.com/brave/brave-core/pull/22984.

**Comment by kjozwiak** [comment]
The above requires `1.65.110` or higher for `1.65.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.65.110 Chromium: 124.0.6367.29 (Official Build) (x86_64) 
Revision	6271fdd3c799c0db71c1e6ca8c83888a7bbbfbd2
OS	macOS Version 13.6.6 (Build 22G630)
```
