### ISSUE TITLE
Red background/foreground on `<select>` widget when choosing permissions

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#37471]
## Description 

Red background/foreground on `<select>` widget when choosing permissions

## Steps to Reproduce

   1. install `1,66,711`
   2. load `https://permission.site/`
   3. click on any of the permission types
   4. look at the resulting dialog
   5. hover over the value for the permissions choices

## Actual result:

![image](https://github.com/brave/brave-browser/assets/387249/2216608c-7bab-4e0d-b506-65b64cc691da)

## Expected result:

![image](https://github.com/brave/brave-browser/assets/387249/3f53caf7-4e54-4170-a6e2-2aacbb0e10a3)

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.66.71 Chromium: 124.0.6367.29 (Official Build) nightly (64-bit)
-- | --
Revision | ede3daae9d4da170efeeb1361223c4b4472fe5b2
OS | Windows 10 Version 22H2 (Build 19045.4291)
```

cc @rebron @brave/qa-team @mkarolin

**Comment by mkarolin** [comment]
This has been addressed via https://github.com/brave/brave-core/pull/22994

**Comment by kjozwiak** [comment]
The above requires `1.65.110` or higher for `1.65.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.65.112 Chromium: 124.0.6367.29 (Official Build) (64-bit)
-- | --
Revision | 1ccdfe627ad458201908007edf699da1f3bfc02b
OS | Windows 10 Version 22H2 (Build 19045.4170)
```

- Confirmed that there is no red background while choosing the permissions

Light mode | Dark mode
--------------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/8d8a6505-48b9-4a53-bef3-b47a8813b8ba) | ![image](https://github.com/brave/brave-browser/assets/38657976/8b6a3e08-a034-4fb1-a1de-06d6d1470878)
