### ISSUE TITLE
Make Deposit Screen Full Height in Wallet

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#37479]
## Description 

We need to make the `Deposit` screen full height in the `Wallet

![Screenshot 15](https://github.com/brave/brave-browser/assets/40611140/83d4eb8c-0dc9-4411-8ffa-da8ce14a0fe7)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.86 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | a1f8e8f462d422d4b924fa9c34246f68862b21ad
OS | Windows 11 Version 23H2 (Build 22631.3593)

- Verified steps from [brave/brave-core#23011](https://github.com/brave/brave-core/pull/23011)
- Verified `Buy` screen shows token list in full height of the window
- Verified `Deposit` screen shows token list in full height of the window

https://github.com/brave/brave-browser/assets/17010094/c97e140e-2a10-447c-9cbf-95e093174383
