### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by felipeparente** [brave/brave-browser#37477]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.63.162 Chromium: 122.0.6261.69
Operating System: Mac OS X 14.4.1

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/47b30000-59de-cc0b-0000-000000000000

**Comment by rebron** [comment]
Hi @felipeparente. Can you update to 1.64.122 via brave://settings/help? Let us know if you're still experiencing a crash afterwards.

**Comment by felipeparente** [comment]
Everything indicates that the problem has been resolved.
