### ISSUE TITLE
App menu text color is not readable well with custom theme color

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#37485]
## Description 

Maybe this is regression from https://github.com/brave/brave-core/pull/22850
<img width="1397" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/65cca302-8310-454a-ac90-9f56141164d3">

## Steps to Reproduce

   1. Set Light theme as brave theme
   2. Pick a custom theme color(`Black`) from brave://settings/manageProfile
   3. Click app menu button

## Actual result:

<img width="314" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/3af53f84-eaad-4d9d-9919-363e62555d1c">

## Expected result:
Text color should be more bright

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @sangwoo108

**Comment by simonhong** [comment]
duplicated with https://github.com/brave/brave-browser/issues/37532

**Comment by stephendonner** [comment]
Removing `QA/Yes` from this issue, as https://github.com/brave/brave-browser/issues/37532 is `QA/Yes`
