### ISSUE TITLE
[Wallet] Account blockie images not loading

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#37502]
## Description 

We need to update or image source policy for the wallet page so that we can display the account blockie images.

## Steps to Reproduce

   1. open the wallet
   2. go to the account page

## Actual result:

The account blockie image does not load

## Expected result:
The account blockie image should load and be displayed

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.66.96` or higher for `1.66.x` verification(s) 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.97 Chromium: 124.0.6367.118 (Official Build) beta (64-bit)
-- | --
Revision | 94909f2aaefd7a8137c8b4fa27235378e79231e3
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from issue description
- Verified account blockies are shown
![image](https://github.com/brave/brave-browser/assets/17010094/bc94ac70-8346-48fa-8c9e-085384b95f2d)
