### ISSUE TITLE
Leo - Remove color banding from conversations

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#37504]
We need to remove the color banding from conversations.

What changes is 

- User avatar now may have a lighter background than current implementation.
- Gray background from the prompt is removed.

https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=347%3A20812&mode=design&t=x65dbyWkrDHEevGm-1
## Actual result:

<img width="423" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/d19f11bd-c583-4ced-a3a0-043c1f321ad9">

## Expected result:
<img width="645" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/57646743-21e6-4cfc-8a55-903c574456eb">

**Comment by LaurenWags** [comment]
@nullhook could you please add the appropriate labels?
