### ISSUE TITLE
[Wallet] Cache getBalanceScannerSupportedChains results

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#37501]
## Description 

we should cache the results when calling getBalanceScannerSupportedChains to prevent needing to call this function multiple times per session

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.92 Chromium: 125.0.6422.76 (Official Build) beta (64-bit)
-- | --
Revision | d751d2edf40b466560aaeecc4c4919041f41c20d
OS | Windows 11 Version 23H2 (Build 22631.3593)

- Verified steps from [brave/brave-core#23013](https://github.com/brave/brave-core/pull/23013)
- Verified Portfolio balance works fine when Ankr Balances is disabled

https://github.com/brave/brave-browser/assets/17010094/8174d79e-4227-4988-b08b-d86211c32ab4
