### ISSUE TITLE
[Wallet] Remove useLib hook and context

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#37505]
## Description 

We no longer need this hook or its context

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.85 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | d01060f5ec155e6eb64a335203663a29c0e5d81f
OS | Windows 11 Version 23H2 (Build 22631.3593)

- Verified steps form [brave/brave-core#23032](https://github.com/brave/brave-core/pull/23032)
- Verified able to import Ethereum accounts via Ledger and Trezor
- Verified able to import Solana account via Ledger and Trezor
- Verified able to import Filecoin accounts via Ledger
- Encountered [#38398](https://github.com/brave/brave-browser/issues/38398) & [#38400](https://github.com/brave/brave-browser/issues/38400)

Ethereum (Ledger) | Solana (Ledger) | Filecoin (Ledger)
-- | -- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/0f0e091c-5019-4762-9877-9edf773a8aab> | <video src=https://github.com/brave/brave-browser/assets/17010094/28746f18-0882-48ea-9ccd-7751b99e7fd6> | <video src=https://github.com/brave/brave-browser/assets/17010094/ab1f55b2-8962-4147-bddb-09a7efdd727c>

Ethereum (Trezor) | Solana (Trezor)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/879a9b92-5624-44a4-aaf1-2b277aaa12c5> | <video src=https://github.com/brave/brave-browser/assets/17010094/3f65b0e2-4a85-49a8-b5e4-6b1f11e31ece>
