### ISSUE TITLE
Browser settings - Move "help tips" contents

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#37510]
## Description 

We're moving the settings found in Help tips to different sections:
- `Show Wayback Machine prompt on 404 pages` moves to the `Content` section as the last item in the `Content` subsection.
- `Warn me before closing window with multiple tabs` moves to `System` below the last item in the first subsection.
- `Show warning before quitting with ⌘Q` moves to `System` below the last item in the first subsection.

As a result, the `Help tips` section is removed from settings.

## Steps to Reproduce

   1. Open brave://settings/braveHelpTips

## Actual result:

<img width="1136" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/9e3a367d-428a-4e2a-b6a0-c04ec7fd810b">

## Expected result:
1. Add Wayback machine setting to brave://settings/braveContent
<img width="819" alt="braveContent" src="https://github.com/brave/brave-browser/assets/5951041/5154a958-fb80-40e3-8ab8-7f724d911282">

2. Add two warning settings to brave://settings/system
<img width="620" alt="macOS" src="https://github.com/brave/brave-browser/assets/5951041/85e2e520-fe54-4b5d-8856-c1523878c8c3">

macOS. For Windows, should be just the `Warn me before closing windows with multiple tabs` setting.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.67.31 Chromium: 124.0.6367.60 (Official Build) nightly (64-bit)
-- | --
Revision | 5d142aa04ae5b4f6447932c461da4cda17db69d9
OS | Windows 10 Version 22H2 (Build 19045.4291)
```


Help Tips removed:

![image](https://github.com/brave/brave-browser/assets/387249/90254b73-9cc4-4c52-a4fa-fd2c5c4e664b)

Content:

![image](https://github.com/brave/brave-browser/assets/387249/5e9c47ef-12cc-4271-b1e3-56f1ffa772ea)


System:

![image](https://github.com/brave/brave-browser/assets/387249/7d8eaf45-3458-4126-b9bf-8da2d5ef2595)

Confirmed `Warn me before closing windows with multiple tabs` was moved to `brave://settings/system`

**Comment by LaurenWags** [comment]
Removing `QA Pass-Win64` as this has been uplifted to `1.66.x` and needs to be re-verified.

Requires `1.66.92` or higher for testing.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.66.94 Chromium: 124.0.6367.91 (Official Build) beta (x86_64)
-- | --
Revision | 1574096f9d2bcb69c3654cb4437217121ee9600b
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.66.94 Chromium: 124.0.6367.91 (Official Build) beta (64-bit)
-- | --
Revision | 1574096f9d2bcb69c3654cb4437217121ee9600b
OS | Windows 11 Version 23H2 (Build 22631.3527)
```

## Shared Steps:
1. installed `1.66.94`
2. launched Brave
3. opened the respective `brave://settings` page/sub-page, as referenced below
4. confirmed each noted change

## `Help Tips` removal:

<details>

### Confirmed `Help Tips` was removed from settings sidebar -- which contained the moved preferences from below 

1.65.x | 1.66.x
---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/3fb0a515-0566-4aa2-9619-4dd7b94f6bd8)|![image](https://github.com/brave/brave-browser/assets/98358127/61200e2e-df57-485b-9259-17681b9e97a3)


</details>

## Content:
<details>

### Confirmed `Show Wayback Machine prompt on 404 pages` was moved to `brave://settings/braveContent`

1.65.x | 1.66.x (light theme) | 1.66.x (dark theme)
----- | ------ | ----
![image](https://github.com/brave/brave-browser/assets/98358127/4306c689-c92d-40a8-a690-4541689a5e95)|![image](https://github.com/brave/brave-browser/assets/98358127/a34ed08c-c87f-4d38-9d02-4b34a14ecce2)|![image](https://github.com/brave/brave-browser/assets/98358127/474338a5-1757-4223-87cd-dabd6ada63e3)

</details>

## System:

<details>

### Confirmed `Warn me before closing windows with multiple tabs` was moved to `brave://settings/system` in the first subsection

1.65.x | 1.66.x (light theme) | 1.66.x (dark theme)
----- | ------ | -----
![image](https://github.com/brave/brave-browser/assets/98358127/3acd23cc-93bf-495e-a5da-05530fb1ff62)|![image](https://github.com/brave/brave-browser/assets/98358127/7754f296-9dab-452d-a49e-909f92a94b53)|![image](https://github.com/brave/brave-browser/assets/98358127/d694fc2c-0efa-4126-b2d9-7e4914993454)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.66.94 Chromium: 124.0.6367.91 (Official Build) beta (64-bit) 
Revision	1574096f9d2bcb69c3654cb4437217121ee9600b
OS	Linux
```


## Shared Steps:
1. installed `1.66.94`
2. launched Brave
3. opened the respective `brave://settings` page/sub-page, as referenced below
4. confirmed each noted change

## `Help Tips` removal:

<details>

### Confirmed `Help Tips` was removed from settings sidebar -- which contained the moved preferences from below 

1.65.x | 1.66.x
---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/03e92eec-812c-4bf3-97ac-0f9dd787f0d1)|![image](https://github.com/brave/brave-browser/assets/98358127/51b3e46a-d3f7-43d1-bd02-78804199bf8a)

</details>

## Content:
<details>

### Confirmed `Show Wayback Machine prompt on 404 pages` was moved to `brave://settings/braveContent`

1.65.x | 1.66.x (light theme) | 1.66.x (dark theme)
----- | ------ | ----
![image](https://github.com/brave/brave-browser/assets/98358127/5a65e25f-34ca-4c43-a5d9-097c2ec60fe2)|![image](https://github.com/brave/brave-browser/assets/98358127/dfee0a13-6aa2-43f8-aca6-d4a78efe5dab)|![image](https://github.com/brave/brave-browser/assets/98358127/81b5678a-852d-40af-9019-e1f3b887b9ac)

</details>

## System:

<details>

### Confirmed `Warn me before closing windows with multiple tabs` was moved to `brave://settings/system` in the first subsection

1.65.x | 1.66.x (light theme) | 1.66.x (dark theme)
----- | ------ | -----
![image](https://github.com/brave/brave-browser/assets/98358127/f671eba0-3203-44b0-8e27-0ea6b9c6ebcb)|![image](https://github.com/brave/brave-browser/assets/98358127/55bdeeb8-35ce-460f-8eda-12059950d30a)|![image](https://github.com/brave/brave-browser/assets/98358127/76ba9568-e63e-4524-9313-50c357845f05)
