### ISSUE TITLE
[Wallet] Remove setupWallet Redux action in favor of opening the welcome tab directly

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#37513]
## Description 

We do not need to update any redux state when executing this logic, and only call this in one area. We should open the welcome page in a new tab directly without dispatching an action.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.92 Chromium: 125.0.6422.76 (Official Build) beta (64-bit)
-- | --
Revision | d751d2edf40b466560aaeecc4c4919041f41c20d
OS | Windows 11 Version 23H2 (Build 22631.3593)

- Verified steps from [brave/brave-core#23036](https://github.com/brave/brave-core/pull/23036)
- Verified clicking on Learn more on new profile loads wallet onboarding in a new tab
- Encountered [#38542](https://github.com/brave/brave-browser/issues/38542)

https://github.com/brave/brave-browser/assets/17010094/5401c20b-ff5f-4d27-af80-042aa1ea2095
