### ISSUE TITLE
modals no longer have Brave colors/style

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#37515]
## Description 

Various modals within the browser no longer have Brave colors/branding.

Examples:
- Bookmarks
- modal that displays when closing a window with multiple tabs

## Steps to Reproduce

   1. Using 1.67.2, open a window with multiple sites
   2. Attempt to close the window, see the modal alerting you has incorrect colors for text/buttons
   3. Cancel this request
   4. Attempt to bookmark one of the sites
   5. See that the bookmarks modal has incorrect color for text/buttons

## Actual result:

Example | Example
--- | ---
<img width="384" alt="Screenshot 2024-04-11 at 1 52 33 PM" src="https://github.com/brave/brave-browser/assets/28145373/63d6b826-ce30-4a52-885d-be7fb74b8075"> | <img width="462" alt="Screenshot 2024-04-11 at 2 22 18 PM" src="https://github.com/brave/brave-browser/assets/28145373/6716fab8-4572-4358-974d-a369dce71685">

## Expected result:

Example | Example
--- | ---
<img width="404" alt="Screenshot 2024-04-11 at 1 53 56 PM" src="https://github.com/brave/brave-browser/assets/28145373/1e20dcc2-8dd2-438f-92a8-cea73f83dcd7"> | <img width="465" alt="Screenshot 2024-04-11 at 2 28 22 PM" src="https://github.com/brave/brave-browser/assets/28145373/8995ece5-8f84-4e0a-87e0-634f28cd6fb2">

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave	1.67.2 Chromium: 124.0.6367.29 (Official Build) nightly (x86_64) 
Revision	bcc8ab0f30ea7af989211434c17eb432f9375792
OS	macOS Version 13.6.6 (Build 22G630)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.64.x, 1.65.x (RC) no
- Can you reproduce this issue with the beta channel? 1.66.x (with C124) no
- Can you reproduce this issue with the nightly channel? 1.67.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @aguscruiz

**Comment by stephendonner** [comment]
Just a few other examples from 

```
Brave	1.67.2 Chromium: 124.0.6367.29 (Official Build) nightly (x86_64) 
Revision	bcc8ab0f30ea7af989211434c17eb432f9375792
OS	macOS Version 11.7.10 (Build 20G1427)
```

example | example | example
---------|----------|--------
<img width="368" alt="Screen Shot 2024-04-11 at 11 43 25 AM" src="https://github.com/brave/brave-browser/assets/387249/d9417f45-a0f6-41b1-adec-b9b51429d089"> | <img width="1312" alt="Screen Shot 2024-04-11 at 11 29 59 AM" src="https://github.com/brave/brave-browser/assets/387249/8907b197-36de-4dd4-aebb-2fa276e3692b"> | <img width="1312" alt="Screen Shot 2024-04-11 at 11 30 05 AM" src="https://github.com/brave/brave-browser/assets/387249/ad6cef2d-9739-444e-8c42-22b190aab62e">

**Comment by stephendonner** [comment]
<img width="468" alt="Screen Shot 2024-04-11 at 1 47 58 PM" src="https://github.com/brave/brave-browser/assets/387249/9be6c829-fde8-4fd6-b235-8157b4a6f226">

**Comment by simonhong** [comment]
Looking..

**Comment by GeetaSarvadnya** [comment]
Reproduced on `Windows 10 x64 -  1.67.1`

![image](https://github.com/brave/brave-browser/assets/38657976/f8b13585-412f-4334-b915-a401254a5452)

**Comment by simonhong** [comment]
> Reproduced on `Windows 10 x64 - 1.67.1`
> 

@GeetaSarvadnya That modal color(blue) seems same with current stable.
![image](https://github.com/brave/brave-browser/assets/6786187/56cdde0a-9fda-4899-b651-3b7c9ba6f352)

**Comment by simonhong** [comment]
This issue is regression of https://github.com/brave/brave-core/pull/22996.
We should not call upstream `AddMaterialUiColorMixer()`.
Instead, we should set missing colors.

**Comment by LaurenWags** [comment]
Thanks @simonhong - makes sense as this now reproduces on 1.65.110 after the uplift:

```
Brave	1.65.110 Chromium: 124.0.6367.29 (Official Build) (x86_64) 
Revision	6271fdd3c799c0db71c1e6ca8c83888a7bbbfbd2
OS	macOS Version 13.6.6 (Build 22G630)
```

<img width="1194" alt="Screenshot 2024-04-12 at 8 51 37 AM" src="https://github.com/brave/brave-browser/assets/28145373/795950bc-0759-4166-bf34-6c6f27bf0624">

**Comment by kjozwiak** [comment]
The above requires `1.65.111` or higher for `1.65.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.65.112 Chromium: 124.0.6367.29 (Official Build) (64-bit)
-- | --
Revision | 1ccdfe627ad458201908007edf699da1f3bfc02b
OS | Windows 10 Version 22H2 (Build 19045.4170)

```
