### ISSUE TITLE
tab hover card text color is incorrect

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#37517]
## Description 

Color on tab hovercard text is Chrome blue, should match 1.66.x (ex. white when on dark theme)

Possibly related to/same root cause as https://github.com/brave/brave-browser/issues/37515.

## Steps to Reproduce

   1. Have a window with some tabs
   2. Have "Tab hover mode" under brave://settings/appearance be set to "Card"
   3. Hover over one of the tabs
   4. See that the text on the card is blue (icon is white)

## Actual result:

1.67.2:
![Screenshot 2024-04-11 at 1 37 08 PM](https://github.com/brave/brave-browser/assets/28145373/7b9a9d03-d455-499c-8e2a-2e95fb6035c9)

## Expected result:

1.66.75:
![Screenshot 2024-04-11 at 1 36 40 PM](https://github.com/brave/brave-browser/assets/28145373/d1d083ee-1e38-40b1-9847-56cf16e62a3e)

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave	1.67.2 Chromium: 124.0.6367.29 (Official Build) nightly (x86_64) 
Revision	bcc8ab0f30ea7af989211434c17eb432f9375792
OS	macOS Version 13.6.6 (Build 22G630)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.64.x, 1.65.x no
- Can you reproduce this issue with the beta channel? 1.66.x no
- Can you reproduce this issue with the nightly channel? 1.67.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @aguscruiz

**Comment by rebron** [comment]
cc: @simonhong @mkarolin Can you take a look?

**Comment by simonhong** [comment]
This is fixed also by https://github.com/brave/brave-core/pull/23048

**Comment by simonhong** [comment]
Fixed by https://github.com/brave/brave-core/pull/23048

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.67.86 Chromium: 125.0.6422.60 (Official Build) beta (x86_64)
-- | --
Revision | a1f8e8f462d422d4b924fa9c34246f68862b21ad
OS | macOS Version 13.6.7 (Build 22G720)
```
