### ISSUE TITLE
C124 - red highlighting on drop down fields in certain cases

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#37524]
## Description 

With C124, when you hover over the drop down field modals (bookmarks, site permissions) and your profile theme is not light/dark but is a color (ex. blue or pink), the field is highlighted in red.

If you just use light/dark, this does not occur

## Steps to Reproduce

   1. Navigate to brave://settings/manageProfile and choose a theme color (ex. blue or pink) for your profile
   2. Navigate to a site like https://browserleaks.com/geo
   3. Hover over drop down on the permission modal
   4. See that it is highlighted in red
   5. Navigate to a site
   6. Click on bookmark icon
   7. Hover pver the drop down on the bookmark modal
   8. See that it is highlighted in red

## Actual result:

Permission | Bookmark
--- | ---
<img width="774" alt="Screenshot 2024-04-11 at 3 21 46 PM" src="https://github.com/brave/brave-browser/assets/28145373/5dc5f48a-ff5a-4a41-8854-c961d7d80aa5"> | <img width="1002" alt="Screenshot 2024-04-11 at 3 22 17 PM" src="https://github.com/brave/brave-browser/assets/28145373/e16c29c3-f3e0-4d9c-8030-f9b53a277508">

## Expected result:

No red highlight

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave	1.66.75 Chromium: 124.0.6367.29 (Official Build) beta (x86_64) 
Revision	ce65b4dd1ac53d203212a8a65e54bf1ec80ab489
OS	macOS Version 13.6.6 (Build 22G630)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.65.x (w/ C123) no
- Can you reproduce this issue with the beta channel? 1.66.x yes
- Can you reproduce this issue with the nightly channel? 1.67.x no, but maybe doesn't reproduce due to #37515

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @mkarolin @rebron

**Comment by LaurenWags** [comment]
Issue that was fixed for just light/dark theme is https://github.com/brave/brave-browser/issues/37434

**Comment by mkarolin** [comment]
cc: @simonhong

**Comment by simonhong** [comment]
checking

**Comment by simonhong** [comment]
I think this is fixed in latest master by https://github.com/brave/brave-core/pull/22996
Please check again with more higher version than `1.67.2`

**Comment by simonhong** [comment]
Fixed by https://github.com/brave/brave-core/pull/22996

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.67.86 Chromium: 125.0.6422.60 (Official Build) beta (x86_64)
-- | --
Revision | a1f8e8f462d422d4b924fa9c34246f68862b21ad
OS | macOS Version 13.6.7 (Build 22G720)
```
