### ISSUE TITLE
Token list alignment needs adjusted in Wallet

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#37525]
## Description 

Currently the `Token List` alignment is not consistent on the `Wallet Page` and `Wallet Panel`. 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

![image](https://github.com/brave/brave-browser/assets/40611140/2ab74f8a-20ea-4750-9d47-a25cc5761618)

## Expected result:

Everything should have the same `horizontal` padding.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.85 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | d01060f5ec155e6eb64a335203663a29c0e5d81f
OS | Windows 11 Version 23H2 (Build 22631.3593)

- Verified steps from [brave/brave-core#23040](https://github.com/brave/brave-core/pull/23040)
- Verified token list alignment is adjusted in panel 

https://github.com/brave/brave-browser/assets/17010094/cb8743f7-2b72-4416-a89d-0852a70a9eba
