### ISSUE TITLE
C124 - drop down on some modals are now theme colored, rest of modal is just light/dark

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#37523]
## Description 

With C124, the drop down on some modals (bookmarks, site permissions), is now theme colored instead of just light/dark.

Previously these drop down fields just matched the rest of the modal coloring (light/dark).

## Steps to Reproduce

   1. Navigate to brave://settings/manageProfile and choose a theme color (ex. blue or pink) for your profile
   2. Navigate to a site like https://browserleaks.com/geo
   3. Click on the drop down on the permission modal
   4. See that it is profile colored, not light/dark as the rest of the modal
   5. Navigate to a site
   6. Click on bookmark icon
   7. Click on the drop down on the bookmark modal
   8. This dropdown is also profile colored

## Actual result:

Permission | Bookmark
--- | ---
<img width="692" alt="Screenshot 2024-04-11 at 3 15 41 PM" src="https://github.com/brave/brave-browser/assets/28145373/b7f4773e-409f-454b-9d4b-ce05ec9d0f0e"> | <img width="987" alt="1 66 x" src="https://github.com/brave/brave-browser/assets/28145373/bb3eb73c-ec97-4db9-b611-77f01ba65085">

## Expected result:

Permission | Bookmark
--- | ---
<img width="716" alt="Screenshot 2024-04-11 at 3 13 43 PM" src="https://github.com/brave/brave-browser/assets/28145373/66b28411-8f70-4fda-b69b-2d666627801b"> | <img width="724" alt="Screenshot 2024-04-11 at 3 12 14 PM" src="https://github.com/brave/brave-browser/assets/28145373/f1fc9a3e-500f-4732-b77c-477c398f0f03">

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave	1.66.75 Chromium: 124.0.6367.29 (Official Build) beta (x86_64) 
Revision	ce65b4dd1ac53d203212a8a65e54bf1ec80ab489
OS	macOS Version 13.6.6 (Build 22G630)
```

```
Brave	1.67.2 Chromium: 124.0.6367.29 (Official Build) nightly (x86_64) 
Revision	bcc8ab0f30ea7af989211434c17eb432f9375792
OS	macOS Version 13.6.6 (Build 22G630)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release?  1.65.x (w/ C123) no
- Can you reproduce this issue with the beta channel? 1.66.x yes
- Can you reproduce this issue with the nightly channel? 1.67.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @mkarolin @rebron

**Comment by mkarolin** [comment]
I think that's part of the Chromium Refresh 2023 color changes that we had to pull in. WDYT @simonhong?

**Comment by simonhong** [comment]
This is regression of https://github.com/brave/brave-core/pull/22850

**Comment by kjozwiak** [comment]
The above requires `1.66.81` or higher for `1.66.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave	1.66.81 Chromium: 124.0.6367.60 (Official Build) beta (x86_64) 
Revision	ee44f88609d4a72c5d0cb3305c5f340b6203a917
OS	macOS Version 11.7.10 (Build 20G1427)
```
