### ISSUE TITLE
Contribution operations should happen in observer pattern

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#3753]
## Description 

In native-ledger, BatContribution, `StartReconcile` and `OnReconcileComplete` operations need to happen in observer

**Comment by NejcZdovc** [comment]
@jasonrsadler can you please provide some more info about this one

**Comment by jasonrsadler** [comment]
The ledger function calls should live inside of `LedgerImpl` (delegating the responsiblity correctly) while maintaining contribution functionality in `BatContribution`

@bridiver can you elaborate more or correct any misconceptions from my statement?

**Comment by NejcZdovc** [comment]
closing as code changed
