### ISSUE TITLE
Brave menu items are unreadable using Morpheon Dark 

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#37532]
## Description 

Brave menu items are unreadable using Morpheon Dark 

## Steps to Reproduce

   1. install `1.67.2`
   2. launch Brave
   3. install Morpheon Dark: `https://chromewebstore.google.com/detail/morpheon-dark/mafbdhjdkjnoafhfelkjpchpaepjknad`

## Actual result:

<img width="1987" alt="Screen Shot 2024-04-11 at 4 54 14 PM" src="https://github.com/brave/brave-browser/assets/387249/60b15cf4-0abd-47dc-817a-59759f62d4ee">

## Expected result:

<img width="1846" alt="Screen Shot 2024-04-11 at 4 53 08 PM" src="https://github.com/brave/brave-browser/assets/387249/b98a818a-9385-4efc-81c8-56fac74e0c34">

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave	1.67.2 Chromium: 124.0.6367.29 (Official Build) nightly (x86_64) 
Revision	bcc8ab0f30ea7af989211434c17eb432f9375792
OS	macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@mkarolin @rebron @simonhong @sangwoo108 @brave/qa-team

**Comment by simonhong** [comment]
I filed https://github.com/brave/brave-browser/issues/37485 yesterday :) I'll close my one

**Comment by stephendonner** [comment]
> I filed #37485 yesterday :) I'll close my one

Oh, sorry - usually the first to file "wins" but thanks 😉

**Comment by kjozwiak** [comment]
The above requires `1.66.81` or higher for `1.66.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.66.81 Chromium: 124.0.6367.60 (Official Build) beta (x86_64)
-- | --
Revision | ee44f88609d4a72c5d0cb3305c5f340b6203a917
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.66.81`
2. launched Brave
3. loaded `https://chromewebstore.google.com/detail/morpheon-dark/mafbdhjdkjnoafhfelkjpchpaepjknad?pli=1`
4. clicked `Add to Brave`
5. clicked on the "hamburger" menu
6. confirmed it was a readable black-letters-on-white scheme
7. uninstalled `Morpheon Black` and used `Dark` mode
8. confirmed it was still readable
9. switched to `Light` mode

### Confirmed app menus were appropriately colored and readable using `Morpheon Dark`, `Dark` mode, and `Light` mode settings

`Morpheon Dark` | `Dark` mode | `Light` mode
------------------|---------------|-------------
<img width="1520" alt="Screen Shot 2024-04-17 at 10 40 12 AM" src="https://github.com/brave/brave-browser/assets/387249/4152f269-63bb-4de2-95c6-d4ac3352557f"> | <img width="1520" alt="Screen Shot 2024-04-17 at 10 40 42 AM" src="https://github.com/brave/brave-browser/assets/387249/ef025d22-2b19-4088-93ac-4635df5d99e4"> | <img width="1520" alt="Screen Shot 2024-04-17 at 10 41 57 AM" src="https://github.com/brave/brave-browser/assets/387249/2bf0739e-8f08-4e2b-908a-62105442a637"> | <img width="1520" alt="Screen Shot 2024-04-17 at 10 40 12 AM" src="https://github.com/brave/brave-browser/assets/387249/5f7ad9ef-2760-45bd-b82d-43198a225ca3">
