### ISSUE TITLE
Make Review Button Wider in Wallet Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#37530]
## Description 

We need to allow the `Review Button` to grow in width in the Wallet `Panel`

## Steps to Reproduce

   1. Open the Wallet `Panel` and navigate to the `Send` screen
   2. The `Review` button should be wider

## Actual result:

![Screenshot 9](https://github.com/brave/brave-browser/assets/40611140/e1b1539c-f01f-4420-9e77-800d489a7caa)

## Expected result:

![Screenshot 11](https://github.com/brave/brave-browser/assets/40611140/aee83b4b-2e57-4d82-9698-67a3339c966f)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.85 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | d01060f5ec155e6eb64a335203663a29c0e5d81f
OS | Windows 11 Version 23H2 (Build 22631.3593)

- Verified steps from [brave/brave-core#23045](https://github.com/brave/brave-core/pull/23045)
- Verified Review button is wider in Wallet panel

Enabled | Disabled
-- | --
![brave_j777N7LoNM](https://github.com/brave/brave-browser/assets/17010094/a0b121f9-c001-4ee1-a983-fa2b139883b3) | [brave_Q0EHC29cE4](https://github.com/brave/brave-browser/assets/17010094/d3c02d2b-84b4-4eb8-a4cb-32e1dcf1f26f)
