### ISSUE TITLE
`Open in playlist` should probably read `Open in Playlist`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#37541]
## Description 

`Open in playlist` should probably read `Open in Playlist`

## Steps to Reproduce

   1. install `1.66.74`
   2. launch Brave
   3. enable `Playlist` via `brave://flags`
   4. load any video on `YouTube.com`
   5. click on the `Playlist` icon in the URL bar, to add the item to the playlist
   6. look at the capitalization of the menu items

## Actual result:

![image](https://github.com/brave/brave-browser/assets/387249/ef6234b7-1043-43e0-8c80-ec894d909b75)

## Expected result:

`Open in Playlist` (to be consistent with the other text instances)

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.66.74 Chromium: 124.0.6367.29 (Official Build) nightly (64-bit)
-- | --
Revision | 43c41a798003efcabf0d292cb2a5efdcc633857b
OS | Windows 10 Version 22H2 (Build 19045.4291)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Unsure`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @sangwoo108 @rebron @brave/qa-team

**Comment by jagadeshjai** [comment]
Will work on this.
@sangwoo108 @rebron
