### ISSUE TITLE
Missing Font Subpage

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#37555]
## Description 

Font-related setting sub page is not present, causing page to flash briefly then error.

## Steps to Reproduce
Open Settings and search for _Fonts_, or attempt direct-navigation to brave://settings/fonts?search=fonts

## Actual result:

https://github.com/brave/brave-browser/assets/815158/67905701-9204-4af3-bb60-e088584b75af

## Expected result:

Subpage is visible and interactive

## Reproduces how often: 
Easily

## Brave version (brave://version info)
1.67.6 Chromium: 124.0.6367.29 (Official Build) nightly (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? Yes

**Comment by kjozwiak** [comment]
The above requires `1.65.113` or higher for `1.65.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.65.113 Chromium: 124.0.6367.60 (Official Build) (64-bit)
-- | --
Revision | c1a6c6e73c1f2f1e5bf00a6f0d42065219845887
OS | Windows 10 Version 22H2 (Build 19045.4291)
```

example | example
----------|---------
![image](https://github.com/brave/brave-browser/assets/387249/c531cd4a-897e-46e9-931b-5c691f81349e) | ![image](https://github.com/brave/brave-browser/assets/387249/d2329a43-2e7a-4405-b936-3d1882bb6ea7)
