### ISSUE TITLE
Need setting to disable “slide over” behaviour

### ISSUE THREAD

**Issue by acli** [brave/brave-browser#37554]
## Description: 
On iPad OS, sometimes Brave would appear in a tiny window (which is almost always completely useless), and the user would have to click the ⋮ button and select “full screen” to make it go back to normal. 

## Steps to Reproduce 
Unfortunately this is a random error. There’s no observable pattern when this occurs.

## Actual result: 
Instead of appearing in full size, Brave appears in a tiny window.

## Expected result:
Brave should appear full size unless the user choose to allow it to appear in a small window.

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Intermittent.

## Brave Version: 

Version 1.62 (24.2.9.10)

### Device details: 
iPad 6th generation, iPadOS 17.4.1

### Website problems only:
n/a

### Additional Information

I have reported this issue before; it was closed because it was deemed an OS issue. But this is clearly a Brave issue because Brave is literally the *only* app that shows this behaviour, so even if it’s an OS issue Brave must be doing something that allows the OS to make this happen. Whatever Brave is doing must become a user-configurable setting.

**Comment by iccub** [comment]
Could you give us a recording of this behavior? We checked and we do not seem to differ from other apps/browsers
