### ISSUE TITLE
can't enable `Enable Brave Wallet in Private Windows` toggle via `brave://settings/web3`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#37563]
## Description 

Enabling `Enable Brave Wallet in Private Windows` via `brave://settings/web3` doesn't seem to be working. If you've enabled the setting and either closed/re-opened `brave://settings/web3` or restarted the browser, you'll notice that the toggle went from `Enabled` back to `Disabled`. Assuming this regressed due to https://github.com/brave/brave-core/pull/23014#issue-2236457995.

## Steps to Reproduce

   1. download/install `1.67.6 Chromium: 124.0.6367.29`
   2. go into `brave://settings/web3` and enable `Enable Brave Wallet in Private Windows` via the toggle
   3. restart the browser and notice that the toggle has been reverted to `disabled` rather than `enabled`

## Actual result:

https://github.com/brave/brave-browser/assets/2602313/9c9f2684-46a9-4fa7-9689-d659dac5576a

## Expected result:

Once `Enable Brave Wallet in Private Windows` has been enabled and the browser restarted, the setting should stay `enabled` rather than reverted back to the `disabled` state.

## Reproduces how often: 

100% reproducible using the STR/Cases outlined above.

## Brave version (brave://version info)

```
Brave | 1.67.6 Chromium: 124.0.6367.29 (Official Build) nightly (64-bit)
-- | --
Revision | 71ace6557041bc74135c4abb4e58bbcbbc3fbb81
OS | Windows 11 Version 23H2 (Build 22631.3447)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No` (didn't require restart till https://github.com/brave/brave-core/pull/23014)
- Can you reproduce this issue with the beta channel? `No` (didn't require restart till https://github.com/brave/brave-core/pull/23014)
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by kjozwiak** [comment]
As noted via https://github.com/brave/brave-core/pull/23065#issuecomment-2058189291 while verifying https://github.com/brave/brave-core/pull/23065 on `Nightly`, closing/re-opening Brave without pressing the `Relaunch Now` button doesn't work. However, this will hopefully be addressed via https://github.com/brave/brave-browser/issues/37560.

**Comment by kjozwiak** [comment]
The above requires `1.65.113` or higher for `1.65.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.65.113 Chromium: 124.0.6367.60 (Official Build) (64-bit)
-- | --
Revision | c1a6c6e73c1f2f1e5bf00a6f0d42065219845887
OS | Windows 10 Version 22H2 (Build 19045.4291)
```
Confirmed that the settings `Enable Brave Wallet in Private Windows` enabled once the settings is toggled ON and settings stays enabled and it doesn't reverted back to the disabled state.

![image](https://github.com/brave/brave-browser/assets/38657976/e1088f29-1743-4792-8238-aa7229191931)
