### ISSUE TITLE
News: disabling then re-enabling doesn't show any channels until NTP refresh

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#37569]
I think this regression was introduced with 1.65, same with https://github.com/brave/brave-browser/issues/37156. Possibly caused by https://github.com/brave/brave-core/pull/22439

## Steps to Reproduce

Start with a profile that already has Brave News enabled
   1. Open a new NTP
   2. Open News settings
   3. Turn off Brave News
   4. Refresh the NTP
   5. Go to "customize"
   6. Go to News settings
   7. Turn **on** Brave News

## Actual result:

No channels showing
<img width="1050" alt="image" src="https://github.com/brave/brave-browser/assets/741836/f2adc5c8-8c0d-468a-9880-8c49f71a2a82">

## Expected result:
All channels showing
<img width="1045" alt="image" src="https://github.com/brave/brave-browser/assets/741836/9583a8af-990a-45cd-8a13-2a4bdd61002f">

## Reproduces how often: 

100%

Refresh fixes the issue (on Desktop)

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.65.113` or higher for `1.65.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.65.114 Chromium: 124.0.6367.60 (Official Build) (64-bit) 
Revision	f1e2cbb65e11340d9040d5ef0b0115c7a5206207
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

Test Case: 

1. Start with fresh profile
2. Enable news
3. Open new tab
4. Open news settings, disable Brave News
5. Refresh the NTP
6. Open news settings, enable Brave News

- Ensure that channels are retained when performing test case above. 

Example | Example
-|-
![Screenshot 2024-04-17 at 10 02 37 AM](https://github.com/brave/brave-browser/assets/17885425/154c0471-35b9-4679-a3c4-eb6ecaddb3ef) | ![Screenshot 2024-04-17 at 10 05 34 AM](https://github.com/brave/brave-browser/assets/17885425/40505161-28db-42ca-b5a9-983e6f75ae66)
