### ISSUE TITLE
AI Chat: Use conversation API

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#37575]
Switch current API calls from the "anthropic-style" API to the conversation API. This API allows more structured response and request data in order to support future features such as annotations, search, etc.

## Test Plan
The aim of this issue is not to add any new functionality provided by the conversation API but to switch over existing functions, which should be tested:
- Simple messages (with and without page context)
- Rewriting commands
- Page summarization (text and video)
- Suggested question retrieval
When testing, make sure to use the feature param mentioned in https://github.com/brave/brave-core/pull/23067

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.67.84 Chromium: 125.0.6422.41 (Official Build) beta (x86_64)
-- | --
Revision | 2ef55ac0e74c86334c2cfdffcf123adc88e9f029
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Simple messages (with and without page context)
## Rewriting commands
## Page summarizations
### `Google Docs`
### `PDF`
### `HTML`
## Suggested question retrieval (?)

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.67.112`

**Comment by Uni-verse** [comment]
In progress on `Samsung Galaxy S21` using version: 

```
Brave	1.67.115 Chromium: 126.0.6478.56 (Official Build) (64-bit) 
Revision	e1f8b4850805c2eea958bad7220c5e6e9202efaa
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

**Simple messages**

- Ensured query functionality is working, with and without page context.
- Ensured summarize and suggest questions are retrieved.

Example | Exmample | Example | Example
-|-|-|-
![Screenshot 2024-06-13 at 1 52 23 PM](https://github.com/brave/brave-browser/assets/17885425/cd87ccf5-6f61-4316-be6a-d8e2624f0d99) | ![Screenshot 2024-06-13 at 1 26 44 PM](https://github.com/brave/brave-browser/assets/17885425/7f28ceff-2fb0-4474-bc29-7d9f04092fd1) | ![Screenshot 2024-06-13 at 1 27 00 PM](https://github.com/brave/brave-browser/assets/17885425/34ee75fe-81fd-417f-a61d-9fafb8af91cf) | ![Screenshot 2024-06-13 at 1 27 59 PM](https://github.com/brave/brave-browser/assets/17885425/e4f0edc4-d02e-4f12-b16d-67e84cbf8612)

**Rewriting commands**
Example | Example | Example | Example
-|-|-|-

**Page summarization for text/video**

Example | Example | Example | Example
-|-|-|-

**Comment by Uni-verse** [comment]
In progress on iOS using version 1.67.115

**Comment by kjozwiak** [comment]
Removing the `iOS` label as the above was disabled for `iOS` on `1.67.x` as per https://github.com/brave/brave-browser/issues/39330. Created https://github.com/brave/brave-browser/issues/39331 as a follow up for `iOS` so the above gets verified via `1.68.x` once https://github.com/brave/brave-core/pull/24297 lands in `1.68.x`.
