### ISSUE TITLE
News: disabling then re-enabling recreates Top Sources subscription even if there are other subscriptions

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#37570]
I think this regression was introduced with 1.65, same with https://github.com/brave/brave-browser/issues/37156 and https://github.com/brave/brave-browser/issues/37569. Possibly caused by https://github.com/brave/brave-core/pull/22439

## Steps to Reproduce

   1. Enable Brave News and notice Top Sources subscription
   2. Add a subscription to a Publisher (e.g. BBC)
   3. Remove the subscription to Top Sources
   4. Confirm mainly only seeing content from BBC
   5. Open Brave News customize screen
   6. Disable Brave News
   7. Enable Brave News

## Actual result:

Top Sources subscription comes back

## Expected result:
Only single publisher subscription remains

## Reproduces how often: 

100%

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.65.113` or higher for `1.65.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.65.113 Chromium: 124.0.6367.60 (Official Build) (64-bit) 
Revision	c1a6c6e73c1f2f1e5bf00a6f0d42065219845887
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

Using STR in https://github.com/brave/brave-browser/issues/37570#issue-2241782471


- Ensured that `Top Sources` source does not come back after unsubscribing. 
- Ensured that subscribed sources are retained and show up in the feed after toggling news feed

Example | Example
-|-
![Screenshot 2024-04-16 at 1 09 50 PM](https://github.com/brave/brave-browser/assets/17885425/9437343a-b918-4f5b-a429-cabd875f91bf) | ![Screenshot 2024-04-16 at 1 11 15 PM](https://github.com/brave/brave-browser/assets/17885425/97eccb12-55ca-48c8-b79f-1f9e516d8639)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave	1.65.113 Chromium: 124.0.6367.60 (Official Build) (x86_64) 
Revision	c1a6c6e73c1f2f1e5bf00a6f0d42065219845887
OS	macOS Version 11.7.10 (Build 20G1427)
```

example | example | example | example | example | example | example
---------|----------|---------|----------|----------|---------|----------
<img width="1312" alt="Screen Shot 2024-04-16 at 12 32 04 PM" src="https://github.com/brave/brave-browser/assets/387249/a04b868c-f368-4ca1-93d7-cee67b6f827c"> | <img width="1312" alt="Screen Shot 2024-04-16 at 12 32 09 PM" src="https://github.com/brave/brave-browser/assets/387249/f3d2917c-a669-4f11-805c-5a46b72fb3e2"> | <img width="1312" alt="Screen Shot 2024-04-16 at 12 32 26 PM" src="https://github.com/brave/brave-browser/assets/387249/29a1cb1a-c952-4eb0-a2c1-316b0f4ebbfc"> | <img width="1312" alt="Screen Shot 2024-04-16 at 12 33 02 PM" src="https://github.com/brave/brave-browser/assets/387249/484d9839-46eb-431d-a771-486a3d8831c3"> | <img width="1312" alt="Screen Shot 2024-04-16 at 12 33 20 PM" src="https://github.com/brave/brave-browser/assets/387249/2eb05bf6-6664-4626-bf3d-3708b79dc064"> | <img width="1312" alt="Screen Shot 2024-04-16 at 12 33 29 PM" src="https://github.com/brave/brave-browser/assets/387249/1094ac6f-5ca9-45b2-b486-d26f008879f9"> | <img width="1312" alt="Screen Shot 2024-04-16 at 12 33 42 PM" src="https://github.com/brave/brave-browser/assets/387249/c52c8ed6-b4fd-4cd1-92ba-5472419c0d3a">
