### ISSUE TITLE
button and toggle colors/style is incorrect in few areas

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#37582]
## Description 

button and toggle colors/style is incorrect in few areas

## Steps to Reproduce

   1. NA

## Actual result:

button and toggle colors/style is incorrect on the following pages 

brave://settings/privacy
brave://settings/cookies
brave://settings/content/javascript
brave://settings/content/braveShields
brave://settings/clearBrowserData
brave://settings/braveSync/setup
brave://settings/searchEngines
brave://settings/system
brave://settings/importData

![image](https://github.com/brave/brave-browser/assets/38657976/b56a833e-e2c1-451c-bc68-d4efb4047d06)
![image](https://github.com/brave/brave-browser/assets/38657976/6350cf96-0dfe-4368-9f2d-b1ca2c3905f9) 
![image](https://github.com/brave/brave-browser/assets/38657976/72a9fd2a-ba10-4a36-b69d-e6b5fe85ad8c) 
![image](https://github.com/brave/brave-browser/assets/38657976/41437637-61f2-4bac-975d-042aa427a7e0) 
![image](https://github.com/brave/brave-browser/assets/38657976/4f1abd95-a477-4fa2-98fd-0722685e5464)
![image](https://github.com/brave/brave-browser/assets/38657976/e98b1890-2980-4114-9b2b-1f5a9b4711a2)
![image](https://github.com/brave/brave-browser/assets/38657976/d94bf6ef-8c56-4647-91da-59835cd06c13)
![image](https://github.com/brave/brave-browser/assets/38657976/84e1b5ed-1cae-43a2-a735-af93e44d7425)
![image](https://github.com/brave/brave-browser/assets/38657976/4c369429-0a76-4fea-a942-4028eac17101)
![image](https://github.com/brave/brave-browser/assets/38657976/08d90393-a073-444e-ad51-b3ba81060392)
![image](https://github.com/brave/brave-browser/assets/38657976/7bcab00b-c9f1-4685-8ed5-23945903c729)
![image](https://github.com/brave/brave-browser/assets/38657976/0a5868c9-ed0d-4d87-b8a4-483465e53499)
![image](https://github.com/brave/brave-browser/assets/38657976/c951a290-34e0-4399-ba99-6e29699a6efe)
![image](https://github.com/brave/brave-browser/assets/38657976/ecc79690-ebc5-4efa-9bed-1157894d4b60)

## Expected result:
button and toggle colors/style should have brave branded colors/style
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.65.112 Chromium: 124.0.6367.29 (Official Build) (64-bit)
-- | --
Revision | 1ccdfe627ad458201908007edf699da1f3bfc02b
OS | Windows 10 Version 22H2 (Build 19045.4170)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Not in `1.66.79`
- Can you reproduce this issue with the nightly channel? Not in `1.67.10`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron

**Comment by LaurenWags** [comment]
Reproduces on macOS as well:

```
Brave	1.65.112 Chromium: 124.0.6367.29 (Official Build) (x86_64) 
Revision	1ccdfe627ad458201908007edf699da1f3bfc02b
OS	macOS Version 13.6.6 (Build 22G630)
```

Example | Example
--- | ---
<img width="1367" alt="Screenshot 2024-04-15 at 8 40 02 AM" src="https://github.com/brave/brave-browser/assets/28145373/150afda3-bf1b-4ea2-b7f6-371565d737b2"> | <img width="1369" alt="Screenshot 2024-04-15 at 8 40 20 AM" src="https://github.com/brave/brave-browser/assets/28145373/47c480fa-c6f5-4b42-b664-41715fa0af78">

**Comment by GeetaSarvadnya** [comment]
@mkarolin @simonhong: Almost all the buttons color/style is changed to chrome color/style across the application. cc: @brave/qa-team 

Import bookmarks:

Example | Example
----------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/07f4c259-05d4-4be3-8a5d-4e21acaf9ece) | ![image](https://github.com/brave/brave-browser/assets/38657976/ab5b15ee-5863-4bff-9ca9-238554408d31)

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/23098 was directly merged/uplifted into `1.65.x` as per https://github.com/brave/brave-core/pull/23098#event-12482327040.

**Comment by kjozwiak** [comment]
The above requires `1.65.113` or higher for `1.65.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification IN PROGRESS on

```
Brave | 1.65.113 Chromium: 124.0.6367.60 (Official Build) (64-bit)
-- | --
Revision | c1a6c6e73c1f2f1e5bf00a6f0d42065219845887
OS | Windows 10 Version 22H2 (Build 19045.4291)
```
