### ISSUE TITLE
`Search or add network` in `Wallet Networks` is broken until you've created a local wallet

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#37598]
## Description 

`Search or add network` in `Wallet Networks` is broken until you've created a local wallet

Found while testing https://github.com/brave/brave-browser/issues/36346, but not a regression 👍 

## Steps to Reproduce

   1. install `1.67.11`
   2. launch Brave
   3. open `brave://settings/web3`
   4. click on `Wallet Networks`
   5. type `meter` or similar
   6. click on the dropdown widget

## Actual result:

Nothing happens

<img width="1813" alt="Screen Shot 2024-04-15 at 11 28 22 AM" src="https://github.com/brave/brave-browser/assets/387249/e7451da4-7d04-4e6c-9cec-fbc4df144b1f">

## Expected result:

Should show search results or be disabled, if not available until post-wallet creation

example | example
---------|---------
<img width="1846" alt="Screen Shot 2024-04-15 at 12 11 07 PM" src="https://github.com/brave/brave-browser/assets/387249/cd5cec45-3a1d-4b85-b7c3-7a9f93c76a12"> | <img width="1846" alt="Screen Shot 2024-04-15 at 12 11 11 PM" src="https://github.com/brave/brave-browser/assets/387249/86d5b43b-732c-4659-b5f3-3dc7106d0f83">

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave	1.67.11 Chromium: 124.0.6367.29 (Official Build) nightly (x86_64) 
Revision	06909a5f7dbab621eb4432c4508134add6bf3c7b
OS	macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @supermassive @srirambv @brave/qa-team

**Comment by srirambv** [comment]
This is expected behaviour as the components that has the mappings are not downloaded until wallet is created/restored.

**Comment by stephendonner** [comment]
> This is expected behaviour as the components that has the mappings are not downloaded until wallet is created/restored.

Yes, but as @supermassive agrees, it's a bad user-experience.  Can we consider this?

**Comment by supermassive** [comment]
I would say we need to disable this UI until wallet is created

**Comment by srirambv** [comment]
Entire Wallet settings under Web3 setting needs to be hidden in that case until wallet is created. I think its ok to show nothing in dropdown if there is no wallet created
