### ISSUE TITLE
Private windows redesign

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#37596]
We need to redesign private windows to present information in a friendlier way. 

Design ready here:
https://www.figma.com/design/jt7tV0UsU7XhJXR2B8807E/Private-and-Tor-Windows---Nala?node-id=37%3A7636&t=wKzZwmhqCGW5ylK4-1

### Android
Sorry for the photo, doesn't let me take screenshots.
<img width="843" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/e0656385-f60b-487b-82fb-0493636a8e1a">

## Expected result
![image](https://github.com/brave/brave-browser/assets/15734630/ba026c36-8246-4f19-98a9-527870a4f162)

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by TEMP-ad** [comment]
Just want to be nosey and tell you that to take screenshots in private mode you just need to enable `brave://flags/#incognito-screenshot`

**Comment by aguscruiz** [comment]
> Just want to be nosey and tell you that to take screenshots in private mode you just need to enable `brave://flags/#incognito-screenshot`

Oh thanks! Didn't know that 👏

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 AP41.240925.009 release-keys
Brave build: 1.74.8 
Chromium: 131.0.6778.69 (Official Build) beta (64-bit) 
```

Filed follow-up issue #42470
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/25850#issue-2570815846
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the new `Private tab` UI is shown as expected.
- Verified that tapping the `Try free for 7 days` link opened the `VPN` paywall.
- Verified that closing the `VPN` paywall returns to the `Private tab`.

---------------------------

<details>
<summary> Galaxy Tab S8 </summary>

|Dark theme|Light theme|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/1c2f91ec-6a41-4f30-9504-2b519f12877f) | ![2](https://github.com/user-attachments/assets/e693e50d-75df-4edc-847b-7d35326acf53) |
| ![1](https://github.com/user-attachments/assets/93ec82ff-c902-4bc1-b484-704b352164f6) | ![2](https://github.com/user-attachments/assets/140e3a8d-b387-4e74-a13f-79dfa2b6b5c4) |

|Dark theme|Light theme|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/13f60c3f-53b6-4af0-8874-45cce0db2598) | ![2](https://github.com/user-attachments/assets/0fd44b25-48c8-413e-91c2-742ab4e319a7) |
| ![1](https://github.com/user-attachments/assets/ec77bae9-c58f-426a-a9f3-39d7344246d3) | ![2](https://github.com/user-attachments/assets/786f6ca1-ac29-44ed-a32d-4949cf93a0c0) |

https://github.com/user-attachments/assets/12228011-f248-4b7f-89a5-152630bb121a

</details>

<details>
<summary> Pixel 7 </summary>

|Dark theme|Light theme|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/f53542ea-2af5-435d-a39d-1862e1d1f988) | ![2](https://github.com/user-attachments/assets/bcf993eb-e8d4-4622-a572-042812f82783) |
| ![1](https://github.com/user-attachments/assets/e491a12c-1dc1-4278-9b7b-e5aea44496e0) | ![2](https://github.com/user-attachments/assets/50f0ac3b-5404-4ee5-8888-5d3638fac964) |
| ![1](https://github.com/user-attachments/assets/e5751272-4754-41b2-83ec-c696a85c7980) | ![2](https://github.com/user-attachments/assets/80f02f4d-a9ff-4b66-9231-a270b9bb79e1) |


https://github.com/user-attachments/assets/f52fe20b-b487-4865-8f1d-4d237305941e
</details>
