### ISSUE TITLE
Shields doesn't work on Guest window

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#376]
## Description 
Shields doesn't work on Guest window

## Steps to Reproduce

   1. Click on user account and click on Guest
   2. Visit any site in the new guest window
   3. Shields doesn't show badge and clicking it doesn't show the shields menu

 ## Actual result:

![guest](https://user-images.githubusercontent.com/17010094/41559804-3183edc4-7313-11e8-8698-bb43b26b27bf.gif)

## Expected result:
Shields should work normally on Guest window

## Reproduces how often: 

100%

## Brave version (about:brave info)

Packaged build and release build

cc: @bbondy

**Comment by bbondy** [comment]
@bridiver will we be removing guest profile support as part of your session window work?

**Comment by bridiver** [comment]
let's hold off on a fix for this until I verify that guest profile support doesn't cause an issue for session windows

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows
