### ISSUE TITLE
Persisted balances are never updated outside portfolio page

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#37609]
The `useBalancesFetcher()` hook relies on persisted token balances, which is only updated when user is on the portfolio page. This means that the balances fetched within the token selector modal (in swap/send) do not update the registry in the local storage. It can lead to stale balances being shown in places where it's important to see live balances.

### Steps to reproduce

1. Go to Swap
2. Select a To asset for which no balance exists yet
3. Finalise the swap
4. Open the From asset selector modal and wait for the balances to get updated.
5. The To asset does not show up. It might show up momentarily, but then disappears in a few seconds.

**Comment by LaurenWags** [comment]
This requires `1.65.119` or higher to test.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.65.120 Chromium: 124.0.6367.60 (Official Build) (arm64) 
-- | --
Revision | e956d45423c37e9f83f250e5a0405bf1fbb40e4d
OS | macOS Version 14.4.1 (Build 23E224)

- Verified steps from issue description
- Verified Send/Swap token selection screen is updated with current token balance


https://github.com/brave/brave-browser/assets/17010094/62f2c9ff-7e4e-4486-95e2-a59d238e6c00

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.65.120 x64 build
- Verified steps from issue description
- Verified Send/Swap token selection screen is updated with current token balance
- Encountered [#37815](https://github.com/brave/brave-browser/issues/37815)

https://github.com/brave/brave-browser/assets/17010094/d9c7ec31-4ecc-4d33-802f-3995a974b437
