### ISSUE TITLE
not getting promo ended message

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3761]
## Description 
Reported via DM from community

A user sent a screenshot of a notification (on panel) from Feb which said there was a grant waiting for them. However, clicking on Claim did nothing. If the promo has run out, which I suspect is what they encountered, clicking on Claim should have given them a message like we had in browser-laptop when a promo had ended.

## Steps to Reproduce
Unsure - these are just a guess
   1. Have a profile with rewards enabled
   2. When promo is available, get notification about grant on panel and brave://rewards
   3. Don't claim grant or dismiss notification
   4. Wait for promo to end.
   5. Attempt to claim grant from panel and brave://rewards.

## Actual result:
Clicking on claim doesn't do anything. 

## Expected result:
Some kind of message notifying user that promo has ended. This is what it looked like on muon:
![promo-ended-muon](https://user-images.githubusercontent.com/28145373/54538539-cf9c5180-496a-11e9-9f17-241e17052d4c.png)

## Reproduces how often: 
unsure

## Brave version (brave://version info)

Brave | 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

### Reproducible on current release: 
- Does it reproduce on brave-browser dev/beta builds? unsure

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Possibly related to #1793 and/or #1794 ?

**Comment by LaurenWags** [comment]
+1 from https://github.com/brave/brave-browser/issues/3382#issuecomment-486948108 - user was clicking on an old notification and got no indication that the promotion was no longer active. we should account for this.

**Comment by dinoboy197** [comment]
I believe I'm getting this issue as well. I have a claim button that does nothing when I click on it. Every time I launch Brave, the button comes back. Is there somewhere that I can validate that the promo for this claim has ended?
