### ISSUE TITLE
Startpage.com showing blank page

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#37611]
## Description 
Opening startpage.com shows blank page in Brave

## Steps to Reproduce

   1. Visit www.startpage.com 
   2. Shows nothing
   3. 

## Actual result:
Shows blank screen
![startpage-brave](https://github.com/brave/brave-browser/assets/1659004/1df4c6e2-10f1-4d58-8922-37e72ba9f937)

## Expected result:
Expect to show website
![startpage-brave2](https://github.com/brave/brave-browser/assets/1659004/a4fcb4a8-7a7b-41f4-bc88-dc7a7aface7d)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
Website is checking `Sec-CH-UA` against Brave and showing blank page. 

Have attempted to reach out via Twitter and Email to startpage

**Comment by ryanbr** [comment]
```
Hi,
 
Startpage encountered a technical issue that resulted in our homepage and search results page to not render correctly on Brave. This issue has been fixed now. Apologies for the inconvenience.
Best regards,
```

Closing issue, page is no longer blank.

**Comment by Georgew221** [comment]
Sorry to reopen this, but it's doing the exact same again.
