### ISSUE TITLE
Swap From asset balance should not rely on persisted balance registry

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#37610]
The highlighted box in the following image does not update on successful confirmation of a Swap, even after a page reload. This is because the balance is fetched from the persisted registry, which is not live. The `useScopedBalanceUpdater()` hook is a better choice here.

<img width="777" alt="Screenshot 2024-04-16 at 07 36 12" src="https://github.com/brave/brave-browser/assets/3684187/bbb10d95-df95-412a-bcd0-611ed14073d1">

**Comment by kjozwiak** [comment]
The above requires `1.65.116` or higher for `1.65.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.116 Chromium: 124.0.6367.60 (Official Build) (64-bit)
-- | --
Revision | 8727234930fb446ce6e8cf4f64a0d7234cbb1892
OS | Windows 11 Version 23H2 (Build 22631.3447)

- Verified steps from issue description
- Verified account balance is automatically reduced when Swap confirmation happens 

https://github.com/brave/brave-browser/assets/17010094/83540912-277d-455c-a3b9-c30c1a7dcc2d

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.65.118 x64 build

- Verified steps from issue description
- Verified account balance is automatically reduced when Swap confirmation happens 

https://github.com/brave/brave-browser/assets/17010094/6996c36d-f82c-4b6f-9bdd-c266c0094c92
