### ISSUE TITLE
Refactor wallet keyrings

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#37613]
Need some overhaul for further bitcoin imported accounts keyring.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.94 Chromium: 125.0.6422.112 (Official Build) beta (64-bit)
-- | --
Revision | 3e4d210c91412b82ad8cffca556b12bbe40ff962
OS | Windows 11 Version 23H2 (Build 22631.3593)

- Verified steps from [brave/brave-core#23075](https://github.com/brave/brave-core/pull/23075)
- Verified able to create HD accounts
- Verified address shows balance correctly
- Verified able to import hardware accounts 
- Verified able to remove imported hardware accounts
- Verified able to import Filecoin accounts

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.67.98 x64 Beta build
- Verified steps from [brave/brave-core#23075](https://github.com/brave/brave-core/pull/23075)
- Verified able to create HD accounts
- Verified address shows balance correctly
- Verified able to import HD accounts
- Verified able to remove imported accounts
- Verified able to import and remove Filecoin accounts
