### ISSUE TITLE
brave://apps has a black background in light mode

### ISSUE THREAD

**Issue by urbenlegend** [brave/brave-browser#37634]
## Description 
The `brave://apps` page shows a ugly black background even when the browser is in light mode.

## Steps to Reproduce

   1. Go to `brave://apps/`

## Actual result:

![image](https://github.com/brave/brave-browser/assets/241316/d008ec15-dc82-4cd6-97ff-8c2facda3b2a)

## Expected result:
Background should follow the theme set in Settings -> Appearance -> Brave colors

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.64.122 Chromium: 123.0.6312.122 (Official Build) unknown (64-bit) 
OS is Arch Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by urbenlegend** [comment]
Closing since I forgot I had a duplicate bug already filed.

**Comment by lbtbs** [comment]
Hi, could you please share the solution? Thank you in advance.
