### ISSUE TITLE
[i18n] Romanian Language Launch

### ISSUE THREAD

**Issue by AndyAnds265** [brave/brave-browser#37639]
Hey all,

@laurentiugruia, is finalizing the Romanian (`ro`) language for iOS. As soon as he has completed that, we'd like to get it into the code. 

@laurentiugruia can you update this ticket once ready?

**Comment by laurentiugruia** [comment]
RO is done in Transifex and ready to be implemented in the app.

cc @chrismore @anthonypkeane @timchilds

**Comment by kjozwiak** [comment]
Labelling as `QA/No` & `release-notes/exclude` in favour of https://github.com/brave/brave-browser/issues/37637#issuecomment-2101334310.
