### ISSUE TITLE
[i18n] New European Union Locales

### ISSUE THREAD

**Issue by AndyAnds265** [brave/brave-browser#37637]
Hello,

Due to the recent demand increase for the European Union, we're going to launch 7 new languages ASAP in order to take advantage of the opportunity. 

We kicked off the localization efforts today 4/16. It will take some time to localize the strings. As soon as they are done we would like to uplift them, but that will be formally requested. 

The locales we are adding are: 
cs, da, el, fi, hr, hu, sk

Please add the base locale only, NO COUNTRY CODE. 

If you have any questions, please let me know

**Comment by AndyAnds265** [comment]
Related: https://github.com/brave/brave-browser/issues/37638

**Comment by AndyAnds265** [comment]
cc: @chrismore / @anthonypkeane for vis

**Comment by kjozwiak** [comment]
The above requires `1.66.104` or higher for `1.66.x` verification 👍

**Comment by kjozwiak** [comment]
@hffvld @Uni-verse we'll use the above as the main issue for verification(s) re: checking the new languages that have been added:

```
Czech(cs)
Slovak(sk)
Danish(da)
Finnish(fi)
Croatian(hr)
Bosnian(bs)
Swiss German(gsw)
Portugese variants(pt, pt_PT)
Greek(el)
```

As discussed via the `iOS` planning & triage call, for each language, we'll basically just need to check the following:

* ensure that the onboarding is translated
* ensure that the `Hamburger Menu` is translated
* ensure that `Settings` look translated

I'll also ping @AndyAnds265 via the `l10n` Slack channel to see if we can get a verification from our `l10n` team re: if the translations seem correct.

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.5
Brave build: 1.66 (108)
BraveCore: 1.66.108 (125.0.6422.41)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/23458#issue-2283566067 and https://github.com/brave/brave-browser/issues/37637#issuecomment-2101334310
2. *Verify*

**ACTUAL RESULTS:**
- Verified that Brave is translated to multiple languages including:
  - Czech( cs)
  - Slovak (sk)
  - Danish (da)
  - Finnish (fi)
  - Croatian (hr)
  - Bosnian (bs)
  - Swiss German (gsw)
  - Portuguese variants (pt, pt_PT)
  - Greek (el)
 - Hungarian (hu)

---------------------------

<details>
<summary> Czech( cs) </summary>

|1|2)|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
| ![1]() | ![2]() | ![3]() | ![4]() |
| ![1]() | ![2]() | ![3]() | ![4]() |
| ![1]() | ![2]() | ![3]() | ![4]() |
| ![1]() | ![2]() | ![3]() | ![4]() |

</details>
