### ISSUE TITLE
iOS/Wallet: Bitcoin Balance Modal

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#37640]
iOS version of https://github.com/brave/brave-browser/issues/35258
need a model to display bitcoin full balance information: total balance; pending balance; available balance.
Figma link: https://www.figma.com/file/muVcmcu4RFNu0LkXe9VRDl/Wallet-2.0?type=design&node-id=17028-635575&mode=design&t=JEAoRvtAIPpTtLnt-4

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18 Developer Beta running 1.67 (112) build
- Verified steps from [brave/brave-core#23307](https://github.com/brave/brave-core/pull/23307)
- Verified balance memo banner is shown under the token in Portfolio and Assets view
- Verified clicking on `View Details` opens up the balance details modal

![image](https://github.com/brave/brave-browser/assets/17010094/2c46d8b0-e811-4222-b255-5ed80f5a3907) | ![image](https://github.com/brave/brave-browser/assets/17010094/e19f6682-87c2-4d66-ba87-857909857c71) | ![image](https://github.com/brave/brave-browser/assets/17010094/9cb6997c-27d3-4e99-a070-0b1ca649661c)
-- | -- | --
![image](https://github.com/brave/brave-browser/assets/17010094/263bf67e-0966-427b-85a7-2c7a2c583d52) | ![image](https://github.com/brave/brave-browser/assets/17010094/fa4dedb9-df00-4cbb-85cd-2ef8b74b6177) | ![image](https://github.com/brave/brave-browser/assets/17010094/55a42298-7911-47d0-a0d8-811882cbc20a)
