### ISSUE TITLE
[ads] New Tab Takeover video ad design fixes

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#37653]
- [x] Change size of NTT video ad play button to fit the design
- [x] Change gradient to be on top of the NTT video ad
- [x] If a user exits full screen, the video should return to the keyframe in the background
- [x] After the video plays in full, the video should return to the keyframe in the background

**Comment by LaurenWags** [comment]
Requires 1.66.95 or higher to test

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.5
- iPad Air / iPadOS 16.7.2
Brave build: 1.66 (95)
BraveCore: 1.66.95 (124.0.6367.91)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/23149#issue-2251275970
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `NTT video ad` autoplay is started when `NTP` with `New Tab Takeover` video ad is opened
- Verified that the `Play` button becomes visible when the `NTT` video ad autoplay is finished
- Verified that `stop keyframe` is shown after `NTT` video playback is finished (The stop keyframe is the frame where autoplay finishes)
- Verified that `stop keyframe` is shown after the user cancels the playback (The stop keyframe is the frame where autoplay finishes)

---------------------------

*iPhone*

https://github.com/brave/brave-browser/assets/128532965/0921f821-f8f8-4813-8c81-8b881c61e59f

*iPad*

https://github.com/brave/brave-browser/assets/128532965/7f926bf3-f335-435d-af70-3cca1dccf8e8
