### ISSUE TITLE
Do not report Leo omnibox & context menu metrics on mobile

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#37660]
The following metrics do not apply to mobile:

```
Brave.AIChat.ContextMenu.FreeUsages
Brave.AIChat.ContextMenu.PremiumUsages
Brave.AIChat.ContextMenu.MostUsedAction
Brave.AIChat.ContextMenu.LastUsageTime
Brave.AIChat.OmniboxOpens
Brave.AIChat.OmniboxWeekCompare
```

They should not be reported on Android & iOS.

cc @mattmcalister

**Comment by mattmcalister** [comment]
These are still relevant on mobile:

`Brave.AIChat.OmniboxOpens`
`Brave.AIChat.OmniboxWeekCompare`

**Comment by darkdh** [comment]
Those are desktop only on code recording level,
ex. our `ChromeAutocompleteProviderClient::OpenLeo` records `Brave.AIChat.OmniboxOpens` and it is excluding iOS and Android

**Comment by DJAndries** [comment]
We should be able to find a solution for Android, since we have other omnibox-based Android metrics available. iOS should be possible too. Created follow-up issues:

https://github.com/brave/brave-browser/issues/37773
https://github.com/brave/brave-browser/issues/37774
