### ISSUE TITLE
chrome "apps" always crashing on initial startup

### ISSUE THREAD

**Issue by midN** [brave/brave-browser#3766]
## Description 
Opening Authy extension crashes app_mode_loader

## Steps to Reproduce

```
Original STR from user:

   1. Install Authy extension
   2. Open it
   3. Crash report with "app_mode_loader" crash appears
```
```Case #1:```

* install https://chrome.google.com/webstore/detail/ledger-manager/beimhnaefocolcplfimocfiaiefpkgbf
* launch `Ledger` app from `brave://apps`

```Case #2:```

* install https://chrome.google.com/webstore/detail/authy/gaedmjdfmmahhbjefcbgaolhhanlaolb
* launch `Authy` app from `brave://apps`

## Actual result:
Crash report.
Authy opens anyway, but Crash report appears every time.

## Expected result:
No Crash

## Reproduces how often: 
Every time

## Brave version (brave://version info)
**Brave**: 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)
**Revision**: 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
**OS**: Mac OS X

**Comment by rebron** [comment]
cc: @kjozwiak can you reproduce, this might be the web app.

**Comment by iamniks** [comment]
I am dealing with the same behavior for almost 3 months :( There is also a security issue on MAC as after crash occurs - Problem Reporter is fired up while one is typing password and grabs focus immediately. So I believe a lot of user may accidentally left their password in problem reporter submitting the issue to the developer.

**Comment by bsclifton** [comment]
@midN @iamniks can you confirm this works in Chrome/Chromium?

**Comment by iamniks** [comment]
@bsclifton Yes, works great in Chrome

**Comment by kjozwiak** [comment]
@iamniks @midN it looks like you can still use the `app` even though it crashes at startup correct? Just double checking to see if you're seeing the same behaviour. I was able to register a new device and use the `app` after the initial crash at launch.

@bsclifton it looks like Brave having issues with `Apps` and not extension. When you download the Authy extension, it basically asks you to install the `app` which is different from extensions:

https://developer.chrome.com/webstore/apps_vs_extensions

I also reproduced the same issue when attempting to install/launch the `Ledger` app. Here's two reproducible cases:

```Case #1```:

* install https://chrome.google.com/webstore/detail/ledger-manager/beimhnaefocolcplfimocfiaiefpkgbf
* launch `app`  from `brave://apps`

<img width="873" alt="Screen Shot 2019-03-26 at 7 21 42 PM" src="https://user-images.githubusercontent.com/2602313/55039877-68cb0800-4ffc-11e9-88a0-2728748677e1.png">

```Case #2```:

* install https://chrome.google.com/webstore/detail/authy/gaedmjdfmmahhbjefcbgaolhhanlaolb
* launch `app` from `brave://apps`

<img width="1446" alt="Screen Shot 2019-03-26 at 7 24 16 PM" src="https://user-images.githubusercontent.com/2602313/55039962-c6f7eb00-4ffc-11e9-9628-8a1f9dbb7b71.png">

**Comment by kjozwiak** [comment]
Probably a `P2` as we want to make sure both `Extensions` & `Apps` are working within Brave. However, will wait till our triage meeting to set label.

**Comment by midN** [comment]
Awesome, thanks guys! @kjozwiak .

You don't see lots of big opensource apps moving fast recently.
Try opening an Issue or make a PR contribution in Kubernetes, small % it gets read/reviewed in 2020.

**Comment by Brave-Matt** [comment]
+1 from reddit:
https://www.reddit.com/r/brave_browser/comments/b9wu16/authy_extension_crashes_followed_by_complete/

**Comment by khaosdoctor** [comment]
Having the same problem here. My two apps are Google Keep and Trello, I created both as shortcuts (in the settings section), when I try to open them I get the following screen:

![image](https://user-images.githubusercontent.com/3200560/56865900-ad561480-69a9-11e9-9441-3a5a50bcfec2.png)

I can confirm that both work perfect on chrome, the problem is that everytime I open one of them, they open chrome...

**Comment by iefremov** [comment]
can't reproduce

**Comment by iefremov** [comment]
most probably it is fixed together with https://github.com/brave/brave-browser/issues/7205
