### ISSUE TITLE
Web Discovery Project article opened from onboarding is English, rather than Japanese-translated one

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#37671]
## Description 

Web Discovery Project article opened from onboarding is English, rather than Japanese-translated one

Found while testing https://github.com/brave/brave-browser/issues/31545

## Steps to Reproduce

1. set region to Japan in Windows
2. set language to Japanese in Windows
3. installed 1.66.81
4. launched Brave
5. skipped through the 1st onboarding screen
6. skipped through the 2nd onboarding screen
7. click on the `Learn More` link

## Actual result:

https://support.brave.com/hc/en-us/articles/4409406835469-What-is-the-Web-Discovery-Project opens

![323358186-d098f352-68bf-45ce-8c81-94e7c9e2a622](https://github.com/brave/brave-browser/assets/387249/b4752d53-06d7-45df-9e52-76b842682133)

## Expected result:

https://support.brave.com/hc/en-us/articles/4410421247885-Web-Discovery-Project%E3%81%A8%E3%81%AF opens

![image](https://github.com/brave/brave-browser/assets/387249/6edd9de1-ea4a-4c7c-ab61-ff0da68e2c6e)

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.66.81 Chromium: 124.0.6367.60 (Official Build) beta (64-bit)
-- | --
Revision | ee44f88609d4a72c5d0cb3305c5f340b6203a917
OS | Windows 10 Version 22H2 (Build 19045.4291)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @sangwoo108 @simonhong @brave/qa-team @rebron @A-t-s-u-s-h-i

**Comment by simonhong** [comment]
> should it be redirected to the https://support.brave.com/hc/en-us/articles/4410421247885-Web-Discovery-Project%E3%81%A8%E3%81%AF page from the server side per language settings? @simonhong what do you think?

As this page is only for japan, jp specific url could be used but ideally I think it should be handled from server side.

**Comment by sangwoo108** [comment]
@rebron , could you help us to reach out who can handle this? I think the url should be redirected to the japanese article page.

**Comment by A-t-s-u-s-h-i** [comment]
@sangwoo108 @simonhong Japanese articles are created under `en-us` locale(no `ja-jp` locale on our help center). These pages are absolutely different and I think Zendesk(help page platform) doesn't redirects automatically.

[English Page]
https://support.brave.com/hc/en-us/articles/4409406835469

[Japanese Page]
https://support.brave.com/hc/en-us/articles/4410421247885

**Comment by sangwoo108** [comment]
Yes, that's weird in the first place.

> @sangwoo108 @simonhong Japanese articles are created under `en-us` locale(no `ja-jp` locale on our help center). These pages are absolutely different and I think Zendesk(help page platform) doesn't redirects automatically.
> 
> [English Page] https://support.brave.com/hc/en-us/articles/4409406835469
> 
> [Japanese Page] https://support.brave.com/hc/en-us/articles/4410421247885

Yes, that's weird in the first place. So what I thought was that the landing pages should have same article id like

```
https://support.brave.com/hc/en-us/articles/4409406835469
https://support.brave.com/hc/ja-jp/articles/4409406835469
https://support.brave.com/hc/ko-kr/articles/4409406835469
```

And the when redirected to the proper page. At the moment, I don't think handling it from browser side is good idea, as we might need to add every different url per locale. - but this would be the same problem from the server side with the current state.

**Comment by A-t-s-u-s-h-i** [comment]
@sangwoo108 Let me discuss with support team. I'll make `ja-jp` locale contents soon if there is no big impact.

**Comment by A-t-s-u-s-h-i** [comment]
Now `ja-jp` article is on live. (We are still WIP to move all Japanese hc articles to `ja-jp` locale. This is the first one.)

> https://support.brave.com/hc/ja-jp/articles/4409406835469

@stephendonner Would you be able to test again to check if the link goes to the Japanese article, please? I think it should work. Or you may need to delete site data once. It may lead you to `en-us` article by cache/cookie even if you set browser language to Japanese.

**Comment by stephendonner** [comment]
Sure thing, @A-t-s-u-s-h-i! 

Here's an attempt using a completely new profile, with `Language`, `Region`, and more set to `Japanese`/`Japan`, as appropriate - unfortunately, it's still pulling in the `en-US` article.

Let me know if you'd like more-specific info from `Developer Tools`



```
Brave | 1.66.89 Chromium: 124.0.6367.60 (Official Build) beta （64 ビット）
-- | --
変更履歴 | dd8714d7b95e4e121ced8594e8a9e3732718e3eb
OS | Windows 10 Version 22H2 (Build 19045.4355)
```

example | example | example
----------|-----------|---------
![image](https://github.com/brave/brave-browser/assets/387249/70cbd34d-8de6-42fb-b408-7e882b2afb34) | ![image](https://github.com/brave/brave-browser/assets/387249/3aa827f5-68e1-4e07-9292-133b4c7e5979) | ![image](https://github.com/brave/brave-browser/assets/387249/373e60e7-fd63-44af-b791-a50ebb38ce82) |

**Comment by A-t-s-u-s-h-i** [comment]
@simonhong @sangwoo108 The text link is set with `en-us` locale as below.

`<a href="https://support.brave.com/hc/en-us/articles/4409406835469-What-is-the-Web-Discovery-Project" target="_blank">詳細はこちら</a>`

<img width="1210" alt="スクリーンショット 2024-04-25 8 57 34" src="https://github.com/brave/brave-browser/assets/79502386/b0d3e532-fc13-4120-b7f0-89ce75389aab">

We need to test, but I guess it will work if it is set without locale path like 

`href="https://support.brave.com/hc/articles/4409406835469-What-is-the-Web-Discovery-Project"`

What do you think?

**Comment by sangwoo108** [comment]
Aha, that's the locale-neutral location. I can update it

**Comment by sangwoo108** [comment]
Oh, It was applied only to Nightly. Will make an uplift.

**Comment by stephendonner** [comment]
> @stephendonner , could you verify it with Nightly version? I guess that'd help uplift reviewers to approve the uplift.

Done!  https://github.com/brave/brave-core/pull/23277#issuecomment-2077720021

**Comment by LaurenWags** [comment]
Closing as this is resolved in 1.66.x as per https://github.com/brave/brave-core/pull/23277

**Comment by LaurenWags** [comment]
Requires `1.66.92` or higher to test

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.66.94 Chromium: 124.0.6367.91 (Official Build) beta (64-bit)
-- | --
Revision | 1574096f9d2bcb69c3654cb4437217121ee9600b
OS | Windows 10 Version 22H2 (Build 19045.4355)
```
