### ISSUE TITLE
[i18n] Portuguese locale mappings

### ISSUE THREAD

**Issue by AndyAnds265** [brave/brave-browser#37674]
hey all,

I've just learned that our Portuguese locale mapping is somewhat broken. At the moment, we are supporting only the exact locale pt-BR. That means, that if someone's language is any other variant of Portuguese, such as pt-PT or other, then they will actually see English! 

I've just tested this on my iPhone and can confirm it is true. See screenshots below. 

So, I'd like to propose the fix here. What I would like to do is to make 2 updates to Portuguese:

- (1) The first update is change the locale pt-BR ------> pt. By doing this it will make any other variant of Portuguese globally fallback to this and no one will ever see English. This will likely entail deleting the Portuguese (Brazil) (pt-BR) language from Xcode and just adding Portuguese without any country specifier.
- (2) I'd like to add the language Portuguese (Portugal) pt-PT to Xcode. At the moment, I will handle all the localization of Portuguese (Portugal). Note: We DO NOT need to pay for additional localization efforts now but I'd like to get in the habit of adding both as they are quite different actually. (similarly, this will eventually be needed for Spanish and French). 

I'd like to request that we make some updates to the locale mapping in this file: 

![IMG_7019](https://github.com/brave/brave-browser/assets/19779922/16ac4eef-cb5c-4c67-841c-3c998851b006)
![IMG_7018](https://github.com/brave/brave-browser/assets/19779922/805d06cf-d103-4c28-b84b-2f0a770aaf1e)

**Comment by AndyAnds265** [comment]
Language codes viewed from here: https://github.com/brave/brave-core/blob/2b6deb38dd1765db0c6973c352e22388dffd68cd/ios/brave-ios/App/l10n/tools/download-translations-from-transifex.swift#L4

**Comment by kjozwiak** [comment]
Labelling as `QA/No` & `release-notes/exclude` in favour of https://github.com/brave/brave-browser/issues/37637#issuecomment-2101334310.
