### ISSUE TITLE
[Android] Remove New Tab Page Ads bottom notice (2024-04)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#37696]
## Description

CURRENT:
![image](https://github.com/brave/brave-browser/assets/11497541/e788dd14-4aab-46de-8048-493cb01cfd8b)

CHANGE TO:

Remove

**Comment by deeppandya** [comment]
@Miyayes in this issue i am removing below banners, 
![Screenshot_20240517-012753_Brave - Nightly](https://github.com/brave/brave-browser/assets/5146988/5127f6de-3871-49cf-8186-271d411925c2)
![Screenshot_20240517-020208_Brave - Nightly](https://github.com/brave/brave-browser/assets/5146988/a5610760-c326-4be1-9383-9ee5feb41c78)
![Screenshot_20240517-010721_Brave - Nightly](https://github.com/brave/brave-browser/assets/5146988/e9031602-344a-444d-9126-484b51e8eaac)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version12` running `Bravemonoarm64.apk_1.68.107`

- Verified the description from https://github.com/brave/brave-browser/issues/37696#issue-2251254276
- Reproduced the issue on `1.67.123` enabled/not enabled rewards and opened n number of NTP's and ensured that `Brave Rewards` notification is not shown on the NTP 

**Rewards enabled:**

Example | Example 
----------|----------
![Screenshot_20240705_213232](https://github.com/brave/brave-browser/assets/38657976/f241bb51-9fb3-4f5c-b0cb-4ca04f33dde4) | ![Screenshot_20240705_213254](https://github.com/brave/brave-browser/assets/38657976/96899845-262f-4700-9b70-8871edbbc29d)


**Rewards not enabled:**

Example | Example 
----------|----------
![Screenshot_20240705_215538](https://github.com/brave/brave-browser/assets/38657976/333deae6-de01-42f7-b909-5560691bd22b) | ![Screenshot_20240705_215557](https://github.com/brave/brave-browser/assets/38657976/83688bc4-66d4-44a5-b56a-bd2361d1089e)
