### ISSUE TITLE
Remove [Ad] from the Advertiser title

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#3769]
Revert Ad notification to original spec.
Remove [Ad] from the Advertiser title. Please uplift on fix.

@jsecretan @tmancey

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.21 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

- Verified test plan from https://github.com/brave/brave-core/pull/1998
<img width="361" alt="Screen Shot 2019-03-28 at 4 32 39 PM" src="https://user-images.githubusercontent.com/28145373/55191020-748f0980-5177-11e9-9d44-b2df81ee5dad.png">
