### ISSUE TITLE
Brave transparent window (wayland)

### ISSUE THREAD

**Issue by psychonaut0** [brave/brave-browser#37698]
## Description 
After the yesterday update (1.65.114) of the AUR package Brave displays an invisible window on Wayland (flags enabled). This is issue is also reported by other users on [AUR package thread](https://aur.archlinux.org/packages/brave-bin). Before the update it worked without any problem.

## Steps to Reproduce

   1. Update to 1.65.114   
   2. Use "Wayland" on "Preferred Ozone Platform" flag.
   3. Open Brave on a wayland session

## Actual result:
It opens an invisible (but working) window of brave. 
I can notice it is working because moving the cursor where the address bar should be actually changes the cursor icon.

## Reproduces how often: 
Every time i try to open brave

## Brave version (brave://version info)
1.65.114 Chromium: 124.0.6367.60 (Official Build) (64-bit) 
Revision: f1e2cbb65e11340d9040d5ef0b0115c7a5206207
OS: Linux

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No

**Comment by antonok-edm** [comment]
is this the same as https://github.com/brave/brave-browser/issues/37498?

**Comment by psychonaut0** [comment]
> is this the same as #37498?

Yep, exactly. I'm also able to workaround the problem using conf file flags instead of experiments. Thank you!
