### ISSUE TITLE
Cast info window needs to change to Brave

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#377]
## Description 
Cast info window needs to change to Brave

## Steps to Reproduce

   1. Right click on any tab
   2. Click on `Cast`  
   3. Info modal says Chromium 

 ## Actual result:

![cast](https://user-images.githubusercontent.com/17010094/41561240-54ca11f6-7317-11e8-97d7-bae218b562da.gif)

## Expected result:
If the cast option is retained should show Brave and link to a Brave support page with details

## Reproduces how often: 

100%

## Brave version (about:brave info)

Release build

#212

**Comment by simonhong** [comment]
This is already fixed.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

Reported #1223 because hep link point to community.brave.com and not to a specific help page.
