### ISSUE TITLE
[Follow up to #36939][l10n] Some `Leo` screens are not translated into `Dutch` language

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#37709]
## Description: 

Follow up to #36939

## Steps to Reproduce 
1. Set `Dutch`language in device settings
2. Launch Brave 
3. Three-dot menu > Leo > Follow the steps to land on `Leo` screen
4. `Gear` icon > *Observe*
5. Tap `Advanced Settings`
6. Change language model > *Observe*

## Actual result: 

Some `Leo` screens are not translated into `Dutch` language.

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/4bcbbd37-66ff-4505-a4cf-72c18810d95e) | ![2](https://github.com/brave/brave-browser/assets/128532965/8db0b874-d9d3-4650-9d64-64c0d6d5799e) |

## Expected result:

All `Leo` strings must be translated into `Dutch` language.

## Reproduces how often: [Easily reproduced, Intermittent Issue]

`Easily reproduced`

## Brave Version: 

```
Brave build: 1.65 (114)
BraveCore: 1.65.114 (124.0.6367.60)
```

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? N/A
- Can you reproduce this issue with the current build from AppStore? N/A

### Device details: 

```
iPhone 14 / iOS 17.5
```

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari?

**Comment by iccub** [comment]
Should be done and ready in 1.66

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.5
Brave build: 1.66 (110)
BraveCore: 1.66.110 (125.0.6422.60)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/37709#issue-2251747823
2. *Verify*

**ACTUAL RESULTS:**
- Verified that all strings in `Leo` are translated to `Dutch` language

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/c86073b8-2ff5-459b-89c3-fa6f164e0f4d) | ![2](https://github.com/brave/brave-browser/assets/128532965/5b534300-155f-48a7-aa5d-84e62fd95eb1) | ![3](https://github.com/brave/brave-browser/assets/128532965/671f8a44-913b-4f81-a97d-9c92d2731a61) |
