### ISSUE TITLE
With `Try Brave Search` promo, sometimes entering additional characters makes its button sizes change back and forth

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#37703]
## Description 

With `Try Brave Search` promo, sometimes entering additional characters makes its button sizes change back and forth

## Steps to Reproduce

   1. install `1.66.82`
   2. launch Brave
   3. change default search engine from `Brave` to anything else, in `brave://settings/search`
   4. type `tabs` and wait
   5. look at the autocomplete-dropdown results
   6. type an additional `s` character
   7. repeat, typing another character

## Actual result:

The `Try Brave Search` and `Maybe later` buttons are vertically truncated/stretched

example | example | example | example | example
---------|----------|---------|----------|--------
<img width="1267" alt="Screen Shot 2024-04-18 at 1 52 21 PM" src="https://github.com/brave/brave-browser/assets/387249/6c0ef09a-771b-4f39-96b1-fd10af6f7ee8"> | <img width="1267" alt="Screen Shot 2024-04-18 at 1 52 24 PM" src="https://github.com/brave/brave-browser/assets/387249/db98dc3a-6b1a-48ce-8a8b-1ad96329545d"> | <img width="1267" alt="Screen Shot 2024-04-18 at 1 52 26 PM" src="https://github.com/brave/brave-browser/assets/387249/5232271d-a802-4e28-9096-a04ab03ecce6"> | <img width="1267" alt="Screen Shot 2024-04-18 at 1 52 29 PM" src="https://github.com/brave/brave-browser/assets/387249/dbe4942d-be2d-4c86-88bc-8989cbd31843"> | <img width="1267" alt="Screen Shot 2024-04-18 at 1 52 33 PM" src="https://github.com/brave/brave-browser/assets/387249/df642ec7-1574-48c2-a395-f9109fc9db45">

## Expected result:

<img width="1267" alt="Screen Shot 2024-04-18 at 1 59 30 PM" src="https://github.com/brave/brave-browser/assets/387249/1453f83a-a215-4a1b-b4dd-0153e102dbcd">

## Reproduces how often: 

Can only reproduce on one macOS laptop :-(

## Brave version (brave://version info)

```
Brave | 1.66.82 Chromium: 124.0.6367.60 (Official Build) beta (x86_64)
-- | --
Revision | 5dc8a11fe47f7e764f9108c665f3276805497669
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Unknown`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Probably`

cc @simonhong @rebron @brave/qa-team

**Comment by simonhong** [comment]
Duplicated issue - https://github.com/brave/brave-browser/issues/37531
It'll be fixed soon by https://github.com/brave/brave-core/pull/23123
