### ISSUE TITLE
Make top of the window resizable vertically from the title bar

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#37702]
## Description 

Resize cursor is not shown while mousing over the on top of the title bar and so unable to resize the window. Users can still resize by either dragging the corners or the bottom of the screen, but they lose the ability to resize the window at the top.  Able to resize the window if `Show title bar` is disabled for vertical tabs which is related to https://github.com/brave/brave-browser/issues/30050.

## Steps to Reproduce

   1. Install 1.65.114 
   2. launch Brave
   3. minimize the window
   4. mouse over the top of the window

## Actual result:

Resize cursor is not shown and hence unable to resize the window from top

https://github.com/brave/brave-browser/assets/98358127/2816c38b-ad57-4ed2-9e85-5141e0915470

## Expected result:
Users should be able to resize the window from the top

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.65.114 Chromium: 124.0.6367.60 (Official Build) (64-bit)
-- | --
Revision | f1e2cbb65e11340d9040d5ef0b0115c7a5206207
OS | Windows 11 Version 23H2 (Build 22631.3447)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @brave/qa-team 
cc: @Brave-Matt

**Comment by rebron** [comment]
cc: @zenparsing

**Comment by DamianSuess** [comment]
Got me yesterday too across my desktop devices

**Comment by zenparsing** [comment]
This is likely related to the following change: https://github.com/brave/brave-core/pull/22454

**Comment by zenparsing** [comment]
It seems that this does not reproduce in 1.66.

**Comment by zenparsing** [comment]
This also seems related to an upstream change [here](https://chromium.googlesource.com/chromium/src/+/71a6ad9edd8ffe2a59ed881f736997c808d0248a%5E%21/#F0).

**Comment by LaurenWags** [comment]
This requires `1.65.119` or higher to test.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.65.118 Chromium: 124.0.6367.60 (Official Build) (64-bit)
-- | --
Revision | 8ecd7a3ff4b4d81f25b94f5b92ab7130587888cd
OS | Windows 11 Version 23H2 (Build 22631.3447)
```


1. Install 1.65.118
2. launch Brave
3. minimize the window
4. mouse over the top of the window

#### Confirmed able to resize the window including top of the window in minimized mode


https://github.com/brave/brave-browser/assets/98358127/03a0ea76-d09a-403b-bbd9-cd42fbc1999b

**Comment by stephendonner** [comment]
## Verification `PASSED` using

```
Brave | 1.65.119 Chromium: 124.0.6367.60 (Official Build) (64-bit)
-- | --
Revision | 222ef21422b9d80cf4bfa7596d1460ee5dbf7d4c
OS | Windows 10 Version 22H2 (Build 19045.4291)
```

### Steps:

1. installed `1.65.119`
2. launched Brave
3. minimized the window
4. mouse over the top of the window
5. also regression-tested each cardinal-direction corner resizer widget 👍 

## Confirmed able to resize the window including top of the window in minimized mode

https://github.com/brave/brave-browser/assets/387249/9bf1bff1-20cc-4422-99fe-f4c4028c4665
