### ISSUE TITLE
Partial text shown for the `Help improve..` text in the Search promo banner

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#37705]
## Description 

Help improve... text is cut off and partial text in the Search promo banner.  

## Steps to Reproduce

   1. Install 1.65.114
   2. launch Brave
   3. enter a string (test) in the URL bar or search.brave.com

## Actual result:

partial text in `Help improve Brave Search by sending` shown

example | example 
----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/db6d798d-5411-455e-96dd-447f21a2a8ed)|![image](https://github.com/brave/brave-browser/assets/98358127/c93d133f-9e5a-41ca-b533-045920f1d533)

## Expected result:
Text should read `Help improve Brave Search by sending anonymous usage data...` 
 
![image](https://github.com/brave/brave-browser/assets/98358127/a1ce28d1-a262-4a10-9ba7-24019938b739)
## Brave version (brave://version info)

```
Brave | 1.65.114 Chromium: 124.0.6367.60 (Official Build) (64-bit)
-- | --
Revision | f1e2cbb65e11340d9040d5ef0b0115c7a5206207
OS | Windows 11 Version 23H2 (Build 22631.3447)
```
>
## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron 
cc: @brave/qa-team

**Comment by simonhong** [comment]
Checking

**Comment by LaurenWags** [comment]
This requires `1.65.119` or higher to test.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.65.118 Chromium: 124.0.6367.60 (Official Build) (64-bit)
-- | --
Revision | 8ecd7a3ff4b4d81f25b94f5b92ab7130587888cd
OS | Windows 11 Version 23H2 (Build 22631.3447)
```

1. Installed 1.65.118
2. launched Brave
3. entered a string (test) in the URL bar or search.brave.com

#### Confirmed the WDP infobar shown correct text. `Help improve Brave Search by sending anonymous usage data...`

https://github.com/brave/brave-browser/assets/98358127/0e1ebf25-6438-4803-91fa-7e5d7531535a
