### ISSUE TITLE
Update title casing for bookmarks, reading list, and playlist

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#37715]
## Description 

Match Leo side panel title casing of `leo ai` in the other side panels: bookmarks, reading list, and playlist.

## Steps to Reproduce

   1.  Open bookmarks, reading list, and playlist
   2. Notice title casing is Bookmarks, Reading list, and Playlist

## Actual result:

Should be lowercase to match `leo ai`
<img width="234" alt="Screenshot 2024-04-18 at 9 56 58 PM" src="https://github.com/brave/brave-browser/assets/5951041/d6df4a69-aad8-4457-9f67-7a30c62d0f4f">

## Expected result:
See description

## Reproduces how often: 

easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by mkarolin** [comment]
@rebron this looks a bit odd to me. Is there a reason why we have `leo ai` in lower case here?

**Comment by aguscruiz** [comment]
> @rebron this looks a bit odd to me. Is there a reason why we have `leo ai` in lower case here?

The new brand guidelines for Brave indicate that all product names/features are all lower case

**Comment by mkarolin** [comment]
Thanks @aguscruiz. We should probably update the style guide then @rmcfadden3. I think it looks odd because we have the introductory text with the upper case just below. Perhaps we need a more comprehensive effort to update the branding then.
<img src="https://github.com/brave/brave-browser/assets/41635752/0c930602-6179-400c-b9d8-fbc67e17fdd2" height=160/>

**Comment by aguscruiz** [comment]
Oh yeah that's not a problem. In regular text it's ok to use Sentence case. it's just on the product names

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.67.37 Chromium: 124.0.6367.60 (Official Build) nightly (64-bit)
-- | --
Revision | 707251359fe3fca825eeda3e6bce6eabf22a4681
OS | Windows 11 Version 23H2 (Build 22631.3447)
```

1. Installed `1.67.37`
2. launched Brave
3. clicked Bookmarks icon on the sidebar
4. confirmed `bookmarks` side panel title is in lower case
6. clicked Reading List icon on the sidebar
7. confirmed `reading list` side panel title is in lower case
8. enabled playlist via `brave://flags`
9. clicked on Playlist
10. confirmed `playlist` side panel title is in lower case
11. clicked on Leo icon on the sidebar
12. confirmed `leo ai` side panel title is in lower case


bookmarks | reading list | playlist | leo ai
--------|--------|---------|-----------
![image](https://github.com/brave/brave-browser/assets/98358127/f2244823-2a13-40e6-b787-ca5ad2c01cdb)|![image](https://github.com/brave/brave-browser/assets/98358127/9fa945de-9e2d-4125-ae67-81dc769a4f0b)|![image](https://github.com/brave/brave-browser/assets/98358127/7593eb2e-cb82-4b63-9af0-91bc3ac90e7c)|![image](https://github.com/brave/brave-browser/assets/98358127/9f6e9a84-15ec-480d-95cd-fece099f0dfd)
![image](https://github.com/brave/brave-browser/assets/98358127/f75040d9-7b6f-4992-b1c7-6ac29474dabe)|![image](https://github.com/brave/brave-browser/assets/98358127/c41e9819-a067-4a75-9cf9-5cb07b546cd7)|![image](https://github.com/brave/brave-browser/assets/98358127/5398394d-f583-42bd-9147-87b75e7a6f3c)|![image](https://github.com/brave/brave-browser/assets/98358127/bb52b691-7bb1-4477-8fba-355b56c5dcf4)
