### ISSUE TITLE
[NTP Search]: Brave News button should be hidden when showing the search widget

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#37714]
Currently, when the search widget and Brave news are showing there's the `Brave News` button which sits awkwardly between the Search widget and the peeking card. We should hide the button when both the peeking card and the search widget are showing.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.67.35 Chromium: 124.0.6367.60 (Official Build) nightly (64-bit)
-- | --
Revision | cf6b916e6e68f45b10d6ccebe4530f7319c3d1aa
OS | Windows 11 Version 23H2 (Build 22631.3447)
```

1. Installed 1.67.35
2. launched Brave
3. opened a new tab
4. confirmed `News` button displayed and when scrolled down, `Turn on` news card shown
5. opened `brave://flag` in a new tab
6. enabled `#brave-ntp-search-widget` flag
7. opened a new tab and confirmed `Search` widget should be shown
8. News button should be visible below `Search` widget
9. scrolled down and clicked `Turn on Brave news` news card
10. clicked a new tab
11. confirmed the search widget is shown and the peeking card is shown below. News button is no longer shown

https://github.com/brave/brave-browser/assets/98358127/1743ac5a-4e4d-4fca-a411-41eb5fd01442
