### ISSUE TITLE
Android - Display Sync code expiry when showing the pairing codes

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#37725]
It is required to implement display Sync code expiry when showing the pairing codes.

Parent issue: https://github.com/brave/brave-browser/issues/31904

Figma design:
https://www.figma.com/file/GXnHuBCVRY397UNJyvu44q/Sync-V2?type=design&node-id=318-10811&mode=design&t=hhmmdWVIlRedrJ3C-0
https://www.figma.com/file/GXnHuBCVRY397UNJyvu44q/Sync-V2?type=design&node-id=318-10811&mode=design&t=eU59QlazlayMhCEG-0

 This is an issue to link to the PR.

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP31.240517.031 release-keys
Brave build: 1.68.117
Chromium: 127.0.6533.26 (Official Build) beta (64-bit) 
```
---------------------------
<details>
<summary> QR Code </summary>

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/23051#issue-2240166626
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `QR Code` is shown with a `30 min` timer.
- Verified that after the time is expired, `QR Code` become hidden, `Code expired.` warning message is shown, and `Generate New Code` button is appeared.
- Verified that the new `QR Code`, new coundown from 30 minutes are shown, and `Generate New Code` button is hidden if tapped `Generate New Code` button.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/586dc290-48ae-43a6-8e87-dfd48d9b5227) | ![2](https://github.com/user-attachments/assets/b0224b0a-dbad-4279-8861-f1a7dcc6ac5a) | ![3](https://github.com/user-attachments/assets/b6130270-6548-42f5-92a3-df135e068295) | ![4](https://github.com/user-attachments/assets/07a85335-faa9-4279-be34-0a210b3790f6) |

https://github.com/user-attachments/assets/29c540b0-fe0c-48d6-9f9e-41f4f4b1e6f9
</details>

<details>
<summary> Code Words </summary>

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/23051#issue-2240166626
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Code Words` is shown with a timer between `1 ` or `2` days (i**t depends on the local time**).
- Verified that after the time is expired, `Code Words` become hidden, `Code expired.` warning message is shown, and `Generate New Code` button is appeared.
- Verified that the new `Code Words`, new coundown are shown, and `Generate New Code` button is hidden if tapped `Generate New Code` button.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/93e0d488-e5fd-4121-8fbb-d8041f8bd219) | ![2](https://github.com/user-attachments/assets/3904bf61-bd5f-411d-bba5-738460e86cf8) | ![3](https://github.com/user-attachments/assets/f8e264d3-757c-43c1-ac0b-c53dc1ebe49c) | ![4](https://github.com/user-attachments/assets/7d6aded0-c68b-4738-8c68-695e355dc95b) |

https://github.com/user-attachments/assets/4dca1445-b316-4d7d-bb1a-72cc673ff74f
</details>
