### ISSUE TITLE
Menu buttons are shown on top after closing Leo screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#37728]
## Description 
Menu buttons are shown on top after closing Leo screen

## Steps to reproduce 

   1. Open Leo from menu or via omnibar search term
   2. Close Leo screen
   3. Open App menu `...`, menu buttons are shown on top and menu placement is covering the bottom bar
   4. Open a new tab and open menu
   5. Shows correct placement of buttons and menu

## Actual result 

Leo opened Tab | Normal NTP
-- | --
![image](https://github.com/brave/brave-browser/assets/17010094/b6a1d300-1457-4f4e-b6f5-9f64582fa197) | ![image](https://github.com/brave/brave-browser/assets/17010094/ce2d6660-2d5f-42f5-9d58-1a793d27aba6)

## Expected result
Menu should be same on all tabs irrespective of Leo being opened or not

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 14
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @SergeyZhukovsky @hffvld @Uni-verse @kjozwiak @samartnik

**Comment by SergeyZhukovsky** [comment]
@srirambv I think we have that noted in that issue https://github.com/brave/brave-browser/issues/36396
