### ISSUE TITLE
Use Brave-specific DoH endpoint for Quad9 pilot test

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#37734]
For Desktop and Android, we are going to use the address
https://doh-brave.quad9.net/dns-query

See further description and code for DoH pilot tests at https://github.com/brave/brave-browser/issues/35677 and https://docs.google.com/document/d/17jPyJ5xnLpe9_4SA7_pCsgeaBVDVJPBeRP2pbw_m5g8/edit#heading=h.m01874lykecs

**Comment by arthuredelstein** [comment]
QA testing can be the same as in https://github.com/brave/brave-browser/issues/35677#issuecomment-1942935347, but for this change, only re-testing for the `quad9` option is needed.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.66.83 Chromium: 124.0.6367.60 (Official Build) beta (64-bit)
-- | --
Revision | 05e51102638aec2f59c93a45527d6840c17cb704
OS | Windows 10 Version 22H2 (Build 19045.4291)
```

installed 1.64.90
launched Brave using --enable-features=BraveFallbackDoHProvider:BraveFallbackDoHProviderEndpoint/quad9
opened ☰ > Settings > Privacy and Security > Security > Select DNS provider
opened https://on.quad9.net/

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240426.023.B4 release-keys
Brave build: 1.67.100
Chromium: 125.0.6422.112 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Install and launch Brave
2. Enable `--enable-features=BraveFallbackDoHProvider:BraveFallbackDoHProviderEndpoint/quad9` in Dev options
3. Three-dot menu > Brave Shields & privacy > Use secure DNS > *Verify*
4. Go to https://on.quad9.net/ > *Verify*

**ACTUAL RESULTS:**
- Verified that DNS resolver automatically selected `quad9.net`

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/b0a9237c-5cca-4085-ae50-499cd031b362) | ![2](https://github.com/brave/brave-browser/assets/128532965/814e0d5c-8f32-426a-a6e4-d65e028dbb9b) |
