### ISSUE TITLE
Deprecate local node support and ipfs:// scheme

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#37735]
Brave's IPFS local node support has a cost to Brave in terms of support and maintenance, distribution of binaries, and node updates.  For each Kubo node update we need to sometimes change things in code, get it QA'd and get release management to release it.  

It is nice to support things, but we do need to also acknowledge that doing so takes away from other things we could be doing. P3A data is showing we have 0.1% local node and 0% gateway setting. 99.9% of people are on an Ask setting which means they’ve never used IPFS.

It also opens up a larger attack surface because there's more code and things running on a users's machine for those that opt into it.    This issue is to track deprecating and removing the local node support. 

Related, we've also had issues in the past with dnslink, so we should consider if we need that too https://github.com/brave/brave-browser/issues/13609

We do use local node support for NFT pinning. So that would be 1 feature that would need to be removed.
I think that we should allow users to install an old version of the browser and still have access to the profile data to get at anything they used to have pinned. I.e. don't clear out the local node data. I think we should have an FAQ in community.brave.com about how to clear out that data manually.

The setting for "IPFS Companion" should probably also be removed. Users can get this extension from the Chrome extension store already, so we don't need in-browser UI to get it. 

We would like to retain decentralized DNS handling via still having an interstitial page that redirects users to a gateway https:// directly. It would not retain the name in the URL bar. For now having 2 interstitial pages, one for Infura as we already do and 1 for enabling the public gateway is good enough.  The 2nd interstitial would have the local node option removed. 

Posting this for greater community feedback and visibility. 

# Other tasks we need to do:
- This work will need updates on our website about it
- We should do a community.brave.com post about it
- We should update past blog posts
- We should update the admin policy documentation if the admin policy is no longer used. If it is still used, maybe because maybe the decentralized dns, we can leave that in place.
- FAQ in community.brave.com about how to clear out profile data manually.
- Close out most IPFS related issues in brave/brave-browser and add the label `closed/invalid`

**Comment by bsclifton** [comment]
cc: @John-LittleBearLabs - curious what you think. I know we talked about IPFS in person at BlinkOn 18 a bit

**Comment by John-LittleBearLabs** [comment]
I know that _I_ like your UI for dealing with this stuff - it's the main reason Brave is my main browser. But obviously I'm a special (read: not representative) case and I'm sure you know your users as a whole better than I. 

Grabbing a Kubo node and running it locally for the user sounded clunky when I first heard it, but it is a pretty feature-complete approach and kinda does what I want it to. It also achieves the level of privacy I want (doesn't send all my IPFS traffic to a given third-party gateway), though I appreciate your UI gives me an appropriate explainer in case I had a higher threshold. And it short-circuits content I already have, which matters for me more than most people.

But if you were planning on supporting IPFS internally in some way, that might be an equal or better approach for an IPFS user. I believe @autonome has spoken to some Brave folks about something like that.

**Comment by autonome** [comment]
The native node feature provides a couple of unique capabilities for Brave's users - independent hosting/publishing, and truly p2p content access.

The self-hosting/-publishing flows are not easily accessible to end-users with the native node support as-is, except through the NFT archiving feature. There's a lot of opportunity there, but would take significant investment in either enabling new onboarding flows as built-in browser features or API extensibility (eg [fetch() POST to local node](https://hackmd.io/GHmvoRj-R1SQ3eskZ8J44Q) like Agregore does) to superpower web apps and dapps. All of that takes significant resources of all kinds, from design to sec eng to release to ongoing maintenance - the whole browser feature lifecycle, or web platform feature lifecycle. Both are a major long-term commitment.

The benefits of local node content client are many: data resilience, egress cost mitigation for publishers, local network applications, and more. But without flagship applications driving users to enable the local node, those benefits are not gained.

In the absence of the local node feature, there are certainly options that have far less resource cost and still provide opportunities for Brave to differentiate and provide IPFS paths for users and developers who need them.

We worked with Igalia to add [custom protocol redirect support to Chromium](https://blog.ipfs.tech/14-11-2022-igalia-chromium/) and that shipped in 2022 - just a build flag and a pref for a default gateway. No code changes, just build config. There are trade-offs in relying on a single HTTP gateway, but allowing it to be user-configurable in the pref can at least give them the choice, and at very little ongoing cost for Brave.

The multi-gateway verifiable client work that @John-LittleBearLabs is building is another option where Brave could get better IPFS client support without shouldering as much cost, so is worth evaluating if there's interest, and as that feature matures. The goal in that work is landing it in Chromium, which would mean again a build flag. Making that happen requires clear support from vendors like Brave in standards conversations like in [this proposal for IPFS at the W3C WICG](https://github.com/WICG/proposals/issues/143).

IPFS certainly has a chicken+egg problem wrt to browser support and deployed native addresses and content. Brave needs to balance their estimation of IPFS being that differentiator for them in acquiring users vs the cost of maintaining the native node feature. The IPFS ecosystem needs to be growing and succeeding to a level where it drives usage and developer interest such that it makes Brave's resource expenditure worthwhile.

**Comment by bbondy** [comment]
Thanks for the insights and options above. 

> Brave needs to balance their estimation of IPFS being that differentiator for them in acquiring users vs the cost of maintaining the native node feature.

Unfortunately the P3A data that we do have doesn't justify it given the ~0.1% of user base using the local node and ~0% using the gateway setting. 

We're going to be moving ahead with this work.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.122 Chromium: 127.0.6533.57 (Official Build) beta (64-bit)
-- | --
Revision | bd77e9b76a8e67ff2bf9f62f1df7d60378ca811f
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#23808](https://github.com/brave/brave-core/pull/23808)
- Verified `ipfs://` section is removed from `brave://settings/web3`
- Verified visiting `brave://ipfs-internals` doesn't load
- Verified ENS/SNS/Offchain/Unstoppable domain resolution works as expected 
- Verified if IPFS is enabled on older version then upgrading to 1.69.x disables and removes all set settings
- Verified visiting IPFS/IPNS links doesn't load but instead performs search for the link
- Verified no info bar is shown when trying to visiting IPFS/IPNS links
- Encountered [#39967](https://github.com/brave/brave-browser/issues/39967)

https://github.com/user-attachments/assets/399dc8ec-17eb-4a5f-91ea-2c8b51b27a0f


https://github.com/user-attachments/assets/aa0912e8-755f-48d9-98cc-10783b99a3d5

**Comment by entlaabstudio** [comment]
**Hello, friends.**

It makes me very sad. I think the IPFS network should be supported. For many reasons. It may be inconvenient and I think many people just don't know that such technology is needed on the internet. I think freedom has more advantages than disadvantages. On the other hand, I understand the developers, but the Brave browser was just an amazing way to use local IPFS. I don't think NFT is what should primarily pull IPFS up. IPFS simply leads to more decentralization and less censorship of the internet. Less dependence on centralized platforms and less censorship of the internet. I understand that this has its own thirteenth chamber, but as I wrote: I think the benefits still outweigh the benefits. What kind of internet we make is what kind of internet we will have. The internet is simply a mirror of society. That goes for IPFS as well.

Personally, I intend to keep using this technology and I believe that one day it will live up to the meaning that comes from its name. Thanks for IPFS! Thanks also to the Brave browser developers for their support so far for IPFS. Here is an example of another use of IPFS other than just for sharing data for NFT. Enjoy my music within the IPFS player:

**ipfs://bafybeiewkxwysf4jlnhbxs7pd4junvkrrais76qm3qgkpn3en4b2lcqxwm/index.htm**

**Comment by lidel** [comment]
In case anyone lost access to the data imported to their Brave node, it is possible to migrate IPFS repository (CIDs, IPNS keys, PeerID, Kubo configuration) to [IPFS Desktop](https://docs.ipfs.tech/how-to/desktop-app/)+[IPFS Companion](https://docs.ipfs.tech/install/ipfs-companion/). 

👉️ Details in the guide at https://blog.ipfs.tech/2024-brave-migration-guide/

**Comment by bbondy** [comment]
Great write-up, thanks @lidel

**Comment by MicahZoltu** [comment]
I know this is already completed/closed and unlikely to change, but I wanted to drop a comment in hopes that it may guide future decision making of this kind.

We are seeing censorship increase around the world lately as governments try to prevent their populations from seeing content the government doesn't want them to see, and we are seeing more and more scrubbing of sites off the internet by authoritarian governments that don't believe certain types of information should be available to anyone.  IPFS provides a path towards a more censorship resistant internet than we have today.

The problem is, most people won't look for tools like this until *after* they realize they are being censored.  If the tech stack isn't available for them when that happens they will remain censored and may not look again, assuming that we live in a world where state censorship is an unbeatable phenomena.  Browsers having censorship resistance tools built into them *before* people need them means that when the time comes and people need the tool, it is there waiting for them.

This somewhat echos what @entlaabstudio mentioned above in that we should be building the internet we want (censorship resistant) rather than targeting what people currently use (censorable services).  In other words, we should build towards the future use cases that we can see coming (those 0.1% of people), rather than building towards the current use cases (the 99.9% of people).

**Comment by ZelnickB** [comment]
The reasoning behind removing the built-in IPFS node makes sense, but I don't understand why the `ipfs://` scheme has been deprecated as well. Ideally, even without the IPFS Companion extension installed, when a user navigates to an `ipfs://` URL, Brave should be able to return a response from a gateway configured in settings.

**Comment by autonome** [comment]
Basic `ipfs://` redirecting to a gateway is more easily done these days via [build-time configuration in Chromium](https://blog.ipfs.tech/14-11-2022-igalia-chromium/).

However, supporting a feature in a browser is about 1000x more involved than just the technical implementation. Brave and Protocol Labs put many person-years of work into the various IPFS features, and it involved teams from design to security to docs to legal etc. Ongoing support and maintenance is not negligible. IPFS in particular needs a lot of user education to support safely, as its privacy and security model differs radically from HTTP. It is not a trivial feature. It requires significant user demand to justify what is a very large investment in time and resources.

Ultimately, making a better web for *everyone* requires a standards-based approach. There are ongoing efforts to get better custom protocol support in Chromium/Firefox/Webkit through WebExtensions using a manifest key for the protocol registration and ideally a ServiceWorker that handles requests. It has a long way to go, but is a more standards-oriented approach that will be more broadly supported. While it would require an extension, it would a big step towards normalizing non-HTTP protocol use on the web. If you'd like to follow along or participate, the tracking issue for IPFS https://github.com/ipfs/ipfs-companion/issues/164 and the WECG issue for manifest-based protocol registration is https://github.com/w3c/webextensions/issues/365.

**Comment by JWMatheo** [comment]
I understand but what a shame :/

**Comment by DeepDoge** [comment]
Brave could have just switched to a more lightweight implementation, similar to Opera.

Instead of running a whole node, having lots of IPFS features, like pinning, built-in extensions, lots of confusing settings.
Just have a single gateway URL setting. And use that to load `ipfs://` content.

If someone wants to run a local node they can just download IPFS themselves and set it as the gateway.

Opera's implementation also gives the `ipfs://` URI, when you type`location.href` in the console.
So arguably Opera's implementation is both simpler and better.

But it's Opera, not Brave, missing other amazing sides of Brave like Brave Sync Chain, being able to change the search engine, Brave Rewards, Brave Shield, etc.

**Comment by trmid** [comment]
I understand that there is little need for IPFS resolution to be enshrined into brave, but not being able to resolve IPFS URIs in net requests is a significant setback.

Protocol labs and the IPFS community have been making strides in getting native integrations available at a lower level. For example:
- [IPFS with curl](https://curl.se/docs/ipfs.html)
- [IPFS with chromium](https://blog.ipfs.tech/14-11-2022-igalia-chromium/)

The curl integration approach is extremely simple and looks for a system-defined IPFS gateway at the user level or in environment variables, allowing the system or user to dictate the need for IPFS resolution support. Checking for a user-defined gateway and then enabling chromium to resolve IPFS URIs via a predefined handler scheme seems like a simple approach to re-add IPFS resolution in a non-invasive way.

This solution would be similar to the suggestion from @DeepDoge , but would make the integration even simpler by not relying on a browser-defined variable and instead looking for standardized IPFS gateway system variable.

**Comment by akhileshthite** [comment]
https://github.com/p2plabsxyz/peersky-browser
https://github.com/AgregoreWeb/agregore-browser
