### ISSUE TITLE
Text in the application menu is `People` instead of `Profiles` for `IN` region on macOS

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#37732]
## Description 

The issue is reported by @rebron 

Text in the application menu is `People` instead of `Profiles` for `IN` region
## Actual result:

Text in the application menu is `People` instead of `Profiles` for `IN` region

![image](https://github.com/brave/brave-browser/assets/38657976/40a05602-d073-4eb5-81d0-36cec207e7ce)

## Expected result:

It should be displayed as `Profiles` in the application menu 
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave	1.65.114 Chromium: 124.0.6367.60 (Official Build) (arm64)
Revision	f1e2cbb65e11340d9040d5ef0b0115c7a5206207
OS	macOS Version 12.5 (Build 21G72)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.69.53 Chromium: 127.0.6533.17 (Official Build) nightly (x86_64)
-- | --
Revision | bedcc2e74ce45bd641d2946e0d870d68ba08b8e9
OS | macOS Version 11.7.10 (Build 20G1427)
```


## `1.67.123`

example | example
---------|---------
<img width="780" alt="Screenshot 2024-06-26 at 1 34 10 PM" src="https://github.com/brave/brave-browser/assets/387249/8117edbe-55d1-4c82-a6c9-47a4e58dad82"> | <img width="1201" alt="Screenshot 2024-06-26 at 1 34 01 PM" src="https://github.com/brave/brave-browser/assets/387249/68da0ed4-854f-4db3-b49c-47cc63283f47">

example | example
---------|---------
<img width="780" alt="Screenshot 2024-06-26 at 1 34 10 PM" src="https://github.com/brave/brave-browser/assets/387249/8117edbe-55d1-4c82-a6c9-47a4e58dad82">

**Comment by stephendonner** [comment]
NOTE: the text below, when clicking the above now-fixed menu item, still reads `Add Person...`

<img width="1250" alt="Screenshot 2024-06-26 at 1 38 39 PM" src="https://github.com/brave/brave-browser/assets/387249/e5a21e85-2c00-4fe2-b5b5-a8e633d5b755">

**Comment by stephendonner** [comment]
> NOTE: the text below, when clicking the above now-fixed menu item, still reads `Add Person...`
> 
> <img alt="Screenshot 2024-06-26 at 1 38 39 PM" width="1250" src="https://private-user-images.githubusercontent.com/387249/343326553-e5a21e85-2c00-4fe2-b5b5-a8e633d5b755.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MzUwNTIsIm5iZiI6MTcxOTQzNDc1MiwicGF0aCI6Ii8zODcyNDkvMzQzMzI2NTUzLWU1YTIxZTg1LTJjMDAtNGZlMi1iNWI1LWE4ZTYzM2Q1Yjc1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQyMDQ1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDkyY2UzODc0MmEyMmMzZGEwNDkxOTNmMzA2ZDZlYjQwNzk5MTA3M2FhN2QwOWQ1ZGJkOTkxZTBkYmY5NThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QLmo1UOARulC4lezHazqoZQoE-Wsp68AgLxNSxVcVws">

Logged https://github.com/brave/brave-browser/issues/39405 for this 👍

**Comment by kjozwiak** [comment]
The above requires `1.68.107` or higher for `1.68.x` verification 👍 Removing the `QA Pass` label as we'll need to re-check the above with `1.68.x`. However, used https://github.com/brave/brave-browser/issues/37732#issuecomment-2192592850 as the requires verification for uplift into `1.68.x` as per https://github.com/brave/brave-core/pull/24443#pullrequestreview-2154942334.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.68.107 Chromium: 127.0.6533.26 (Official Build) beta (x86_64)
-- | --
Revision | 131a9beda9f0aea74f948286e5e8c63153d9f7f8
OS | macOS Version 13.6.7 (Build 22G720)
```
