### ISSUE TITLE
Forward and backward buttons doesn't work on https://www.triumphbaptist.org/calendar

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3773]
## Description 

Forward and backward buttons doesn't work on https://www.triumphbaptist.org/calendar

## Steps to Reproduce

   1. Clean profile 0.61.51
   2. Open `https://www.triumphbaptist.org/calendar`
   3. Click on `<` and `>` button on calendar

## Actual result:

Forward and backward buttons doesn't work on https://www.triumphbaptist.org/calendar

## Expected result:
Forward and backward buttons should work on https://www.triumphbaptist.org/calendar

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

### Reproducible on current release: Yes
- Does it reproduce on brave-browser dev/beta builds?  Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

The issue is reported by the community

https://community.brave.com/t/calendar-page-wont-advance-to-next-month/49504

**Comment by ryanbr** [comment]
@GeetaSarvadnya can you confirm this is fixed? tested in Brave (Release), seems to work fine here.

**Comment by GeetaSarvadnya** [comment]
The issue is fixed in Brave `0.65.118`. Hence closing the issue.
![Caledar Issue](https://user-images.githubusercontent.com/38657976/59195179-e8eb1d80-8ba8-11e9-80ed-a919eed8f6d6.gif)
