### ISSUE TITLE
[iOS/Wallet]: Network Settings inside Wallet settings to hide/unhide networks

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#37741]
an iOS version https://github.com/brave/brave-browser/issues/37397
this needs to be done before https://github.com/brave/brave-browser/issues/37740

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.0 Beta running 1.68 (115)
- Verified steps from [brave/brave-core#23437](https://github.com/brave/brave-core/pull/23437)
- Verified network settings shows list of all networks 
- Verified there is an `eye-opened` button next to the network indicating its enabled
- Verified clicking on the `eye-opened` button changes to `eye-closed` state
- Verified when network icon has `eye-closed`, network is hidden in filters
- Verified upgrading from older version with `Show test network` disabled, new version has all test networks disabled
- Verified upgrading from older version with `Show test network` enabled, new version has all test networks enabled
- Verified able to add a custom network
- Verified custom network has `Edit`, `Delete`, `Set as default` buttons in menu
- Verified every network has `Edit` and `Set as default` options
- Verified editing network works as expected
- Verified when a network is disabled but then setting `Set as default` enables the network 


<video src=https://github.com/brave/brave-browser/assets/17010094/46a307e0-2d94-4f1f-a5e4-25729cc35b52> | <video src=https://github.com/brave/brave-browser/assets/17010094/73821e79-6187-45bb-bc6e-71ba5a6c9ec2> | <video src=https://github.com/brave/brave-browser/assets/17010094/be37bc82-e63d-46cc-ac0d-dea89ff7340c>
-- | -- | --
