### ISSUE TITLE
Not default browser banner always shows under Gnome

### ISSUE THREAD

**Issue by fooforever** [brave/brave-browser#3774]
## Description 

When launching from a cold start always shows the 'Brave is not your default browser, set as default' banner, even when it is set as default under gnome settings. Pressing the set as default button also does nothing.

## Steps to Reproduce

   1. Open Brave after a restart or new gnome session
   2. 
   3. 

## Actual result:

Set as default banner is shown

## Expected result:
Banner is not show if Brave is set as default

## Reproduces how often: 
Easily reproduced from cold start

## Brave version (brave://version info)

Brave | 0.61.51 Chromium: 73.0.3683.75 (Official Build)unknown (64-bit)
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional Information

Running Gnome 3.30.2 on Manjaro, OS up to date as of this post

**Comment by fmarier** [comment]
What do you get if you run `ls -l /etc/alternatives/x-www-browser` ?

**Comment by fmarier** [comment]
Also, what is the output of `xdg-settings get default-web-browser`?

**Comment by fooforever** [comment]
Neither of those command produce anything, no such file and help text. Although this does seem to have stopped happening now, on Gnome 3.32.1 and brave 0.63.48 though.

**Comment by fmarier** [comment]
Ok, thanks for the update. I will close this issue. If it happens again, please feel free to reopen, or to create a new issue.
