### ISSUE TITLE
Ensure correct values are returned for tab strip layout constants

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#37751]
With Refresh2023, upstream has started to change the way that they interpret and use some of the tab-related layout constants found in `chrome/browser/ui/layout_constants.h`. For instance, the `TAB_STRIP_PADDING` value is now assumed to be non-zero and is used to calculate the amount of space at the top of the frame to dedicate to resizing on Windows. (See https://github.com/brave/brave-core/pull/23176.)

We should ensure that we are returning values for these layout constants that match upstream's current assumptions. We should also ensure that horizontal tabstrip layout is correct even with the refresh flag enabled. Once this is done, we should be able to remove the `GetLayoutConstant` override in `browser_frame_view_win.cc`.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.67.37 Chromium: 124.0.6367.60 (Official Build) nightly (64-bit)
-- | --
Revision | 707251359fe3fca825eeda3e6bce6eabf22a4681
OS | Windows 11 Version 23H2 (Build 22631.3527)
```

1. Installed 1.67.37
2. launched Brave

<details>
<summary>Horizontal tab view - Pending</summary>

opened few tabs in horizontal tab view
confirmed the layout and sizing of tabs shown as expected



<details>
<summary>Vertical tab view - Pending </summary>

1. continue from Horizontal tab view case
2. clicked `Use Vertical tabs` from the context menu
3. confirmed the layout and sizing of tabs shown as expected in `Expanded`/`Minimum mode`/`mouseover mode` 
4. confirmed `Tab dragging` in vertical tab view mode working as expected
5. confirmed able to create tab groups and name them
6. confirmed able to create unnamed tab groups
7. confirmed able to save tabs groups by enabling Saved tab groups toggle via context menu
8. confirmed able to Pin tabs
