### ISSUE TITLE
[Solved]Cookies listed as to be cleared at exit - now labeled "Allowed to use third-party cookies" - cannot make sense of cookie clearing at all

### ISSUE THREAD

**Issue by NipLars** [brave/brave-browser#37755]
## Description 

Labeling become odd, as a start, what I had as cleared at exit for years, are now "allowed for third party",
Third party is blocked as a setting, and this seems meant as an exception to this then.
I end up with cookies that used to be cleared.

And the time based "Forget me..." setting seems do nothing either.
- this now happends at exit instead it seems
Whole structure for handling cookies is changed.
- there is no place to specify cookies to be cleared at exit anymore.
I tried clearing all shield data and that and start over.
So just did "forget me..." on a couple of places, and did not work.

## Steps to Reproduce
Went to www.youtube.com and added "Forget me..."
Added new tab, and clossed youtube tab.
- nothing happend looking at cookie listing
- I even exit Brave and enter again, and youtube is still there
- refreshed cookie listing, still there
Then added www.youtube.com to "allow for third party" list
- this used to be "clear at exit" list
Close Brave, then youtube disappear.

I cannot make sense of it at all, how to specify things.

Other places are bulletin.nu and samnytt.nu

Just visit, and set "forget me" and open a new tab, and close the former
Go to cookies listing and still there.

Exit Brave, and start, still there.
Enter those sites at "allow third party" listing
Then they clear at exit of Brave.

## Actual result:

Cookies still there

## Expected result:
Cookies to be cleared

## Reproduces how often: 

Every time, maybe some exception.

## Brave version (brave://version info)

Updated automatically april 18th.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 
Only ran current release.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Since this issue needs to close all Brave instances, I will return with more details as I experiment further.

**Can there be a listing what to be cleared at exit as before
- and as tab is closed be cleared in destructor?
Or the "Forget me..." do the same.**

Looking for consistency. Make it simple to predict what happends.

I have everything cleared at exit of Brave, except cookies and shield stuff.
- then used to be cookies listed cleared as well

**Comment by NipLars** [comment]
I found new settings to have the axe on site data
brave://settings/content/siteData

So cookies were divided into two sections of storage, not in the same place.
Cookies are here in settings
brave://settings/content/all

It does not explain how my previous on siteData settings were moved to "Allowed third party...", but consider it solved.

**Comment by rebron** [comment]
Closing per last comment by author.
