### ISSUE TITLE
Handle publishers list with same service that manages other updatable files

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#3775]
## Description 
Users are frequently encountering errors with known verified publishers being shown as unverified.  This is believed to be due to problems updating the publishers_list.  To help address this, we should setup the publishers_list to be pulled in the same way that we are now managing other updatable lists.

Update frequency is 24 hours.  We'd need to make a script here which would grab the list of verified publishers from an https endpoint and put it into an extension https://github.com/brave/brave-core-crx-packager
Then we'd need add code to brave-core to have a service that uses that extension.
We'd need to get devops to schedule the job for brave-core-crx-packager to run daily.

The file is currently at https://publishers-distro.basicattentiontoken.org/api/v1/public/channels and should be requested with gzip accept headers so that the CDN provides the gzipped version of the file.

### Additional Information
Because Android does not support extensions, we will have to keep the current update code with an Android guard around it and further address issues there.

**Comment by NejcZdovc** [comment]
closing as we will not go down this route
