### ISSUE TITLE
WDP infobar layout is broken when resizing

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#37758]
## Description 

F/U issue for https://github.com/brave/brave-browser/issues/37705

## Steps to Reproduce

   1. Launch brave with clean profile
   2. Set Brave search as a default search provider
   3. Loading search.brave.com
   4. Check WDP infobar is shown and its layout is fine
   5. Resize browser window to make infobar more narrower or wider to change its layout

## Actual result:

Browser launched with wider window and made narrow
<img width="731" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/cf909892-c168-47d0-9ed8-5ce221ca485b">

## Expected result:
<img width="836" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/4246eb90-503f-4636-b4ba-e8c9830e05ef">

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @MadhaviSeelam 

https://github.com/brave/brave-core/pull/23186 was partially fix the WDP's layout issue.
With that fix, WDP layout is fine if window is not resized.

**Comment by LaurenWags** [comment]
This requires `1.65.119` or higher to test.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.65.118 Chromium: 124.0.6367.60 (Official Build) (64-bit)
-- | --
Revision | 8ecd7a3ff4b4d81f25b94f5b92ab7130587888cd
OS | Windows 11 Version 23H2 (Build 22631.3447)
```


1. Installed 1.65.118
2. launched Brave
3. navigated to search.brave.com in a new tab

#### Confirmed the WDP infobar shown correct text -  `Help improve Brave Search by sending anonymous usage data... and the layout shown correctly when resizing the window.


https://github.com/brave/brave-browser/assets/98358127/e64fdb28-60b7-4382-81f7-6ec6c96f04c0
