### ISSUE TITLE
Cannot click "Solve" on Rewards aCAPTCHA (2024-04)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#37760]
## Description

Users reporting that the aCAPTCHA notice appears, but cannot press "Solve" with their mouse. It's unresponsive.

Workaround is to click on the notification then press "Enter". 

_Fix should be uplifted to next hotfix release._ 

### References

1. https://www.reddit.com/r/BATProject/comments/1c6x719/brave_browser_unusable_these_days/
2. https://community.brave.com/t/i-cant-interact-or-close-this-windows/544193
3. https://www.reddit.com/r/brave_browser/s/imzg1JHIgV

**Comment by LaurenWags** [comment]
Requires `1.65.120` or higher for testing 👍🏻

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.65.120 Chromium: 124.0.6367.60 (Official Build) (64-bit)
-- | --
Revision | e956d45423c37e9f83f250e5a0405bf1fbb40e4d
OS | Windows 10 Version 22H2 (Build 19045.4291)
```

**Comment by Miyayes** [comment]
We implemented a probable mitigation, but we need to actually validate if this fixes the issue.
