### ISSUE TITLE
Make all Wallet More Menu Icons Vertical

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#37767]
## Description 

We need to make all `More Menu` icons vertical in the `Wallet`

## Steps to Reproduce

   1. Page `More Menu` is horizontal
   2. Panel `More Menu` is horizontal
   3. NFT `More Menu` is horizontal

## Actual result:

![Screenshot 18](https://github.com/brave/brave-browser/assets/40611140/d5490fb8-6da6-47d2-bf3d-aad210a5d805)

![Screenshot 19](https://github.com/brave/brave-browser/assets/40611140/1a90cb83-78f5-4e27-be0f-e881db29fd9a)

![Screenshot 21](https://github.com/brave/brave-browser/assets/40611140/1e2be263-988f-4bb7-8fa7-1bdb5c633ea8)

## Expected result:

![Screenshot 20](https://github.com/brave/brave-browser/assets/40611140/6746c19e-7e6a-4a78-a778-b09916f24967)

![Screenshot 22](https://github.com/brave/brave-browser/assets/40611140/8848d252-9258-45d0-a1a8-54d8b0721487)

![Screenshot 23](https://github.com/brave/brave-browser/assets/40611140/de1d2c71-9733-4cf9-b082-40c5d1a68baf)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.67.85 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | d01060f5ec155e6eb64a335203663a29c0e5d81f
OS | Windows 11 Version 23H2 (Build 22631.3593)

- Verified steps from [brave/brave-core#23200](https://github.com/brave/brave-core/pull/23200)
- Verified wallet menu icons are vertically aligned


Portfolio | Panel | NFT
-- | -- | --
![brave_ip0hdgTku9](https://github.com/brave/brave-browser/assets/17010094/733bdc8b-fe09-4c94-abcb-ce23c8ce836a) | ![bZP8bP9AXu](https://github.com/brave/brave-browser/assets/17010094/05113428-2f7f-4638-98b2-63be9f871bbf) | ![brave_XbsP4qh0Ea](https://github.com/brave/brave-browser/assets/17010094/d36f8bbb-da4b-4006-a559-287f349aacfd)
