### ISSUE TITLE
AIChat: The feedback form's select box resets after typing inside the input box

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#37779]

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.65.118 Chromium: 124.0.6367.60 (Official Build) (64-bit)
-- | --
Revision | 8ecd7a3ff4b4d81f25b94f5b92ab7130587888cd
OS | Windows 11 Version 23H2 (Build 22631.3447)
```

1. Installed 1.65.118
2. launched Brave
3. visited https://www.azcentral.com/story/news/local/phoenix/2024/04/23/new-airport-terminal-moremayor-kate-gallego-announces-new-airport-terminal-in-2024-state-of-the-city/73331976007/
4. clicked Leo icon on the sidebar
5. clicked `Summarize the page`
6. clicked `I understand`
7. waited for the response to be completed
8. hovered over 3 dot menu on top of the response
9. selected `Dislike Answer`
10. clicked `Add feedback` 
11. selected `Not correct` in the `Provide Brave AI Feedback` menu
12. entered `test` in the `Provide feedback here` input box
13. confirmed selection of `Not correct` didn't reset after typing `test` in the input field
14. clicked `Submit`
15. confirmed `Submit` is active
16. verified `Feedback sent successfully` message shown

Uploading 2024-04-23_15h55_53.mp4…

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240426.023.B4 release-keys
Brave build: 1.67.100
Chromium: 125.0.6422.112 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Launch Brave
2. Open any website, for example Wikipedia
3. Three-dot menu > Leo
4. Go through Leo onboarding if not done yet
5. Summarize this page > Wait for the response
6. Tap and hold the response > Dislike answer
7. Add Feedback > Select a category
8. Type something in the description > Submit > *Verify*

**ACTUAL RESULTS:**
- Verified that `Submit` is disabled when the feedback category is not selected
- Verified that the selection is not reset
- Verified that the feedback can be submitted

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/2067bde8-ac26-4e5d-a0e4-a85a106e11f6) | ![2](https://github.com/brave/brave-browser/assets/128532965/327c8102-0a80-407f-992e-2f3616347a78) | ![3](https://github.com/brave/brave-browser/assets/128532965/25d2bb6c-0406-472b-af70-517bb1a370ca) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/62664fbb-b378-4fe0-ab3e-69cda6704e83) | ![2](https://github.com/brave/brave-browser/assets/128532965/c1fad60a-6163-4105-8d84-1d9af07074e4) | ![3](https://github.com/brave/brave-browser/assets/128532965/a10b354a-2da3-4c80-a377-2b3644b7bf93) |
