### ISSUE TITLE
Sync: not all bookmarks synced

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#3777]
## Description 

This is found from STR of https://github.com/brave/brave-browser/issues/3261 .

## Steps to Reproduce

Taken from https://github.com/brave/brave-browser/issues/3261 .

1. Designate one to be macOS1/device1. Import 5k bookmarks.
https://github.com/brave/brave-browser/files/2841825/brave_sortish_5000.-.ordered.html.zip

2. On the other device (macOS2/device2) import 1k bookmarks.
https://github.com/brave/brave-browser/files/2841831/brave_sortish_1000.-ordered.html.zip

3. Start sync chain on macOS1 and join on macOS2.

4. In about 50-60 minutes devices should be synced.

5. Export bookmarks from device1 and device2 to separate files

6. Compare exported files

## Actual result:

A lot of bookmarks are missing on device2

## Expected result:
All bookmarks are equal on both devices.
The `<DT><A HREF="https://www.amazon.com/s/ref=sr_pg_2?rh=i%3Aaps%2Ck%3AB00160D1XQ%7CB01E78WLCU%7CB00HR1M8KK%7CB00NHQHOZS%7CB00NHQHP3E%7CB00NHQHP2U%7CB00NHQHPFC%7CB00NHQHP9S%7CB00NHQHKF2%7CB00NHQHK1G%7CB00NHQHJZS%7CB00NHQHKFC%7CB00WHXP7LK%7CB00WHY4ADA%7CB018AIFN50%7CB018AIFN9Q%7CB018AIFLYS%7CB018AIFLSY%7CB018AIFN6Y%7CB018AIFM4C%7CB018AIFLFM%7CB018AIFR6K%7CB01E78WKEO%7CB010B4RSLI&page=2&keywords=B00160D1XQ%7CB01E78WLCU%7CB00HR1M8KK%7CB00NHQHOZS%7CB00NHQHP3E%7CB00NHQHP2U%7CB00NHQHPFC%7CB00NHQHP9S%7CB00NHQHKF2%7CB00NHQHK1G%7CB00NHQHJZS%7CB00NHQHKFC%7CB00WHXP7LK%7CB00WHY4ADA%7CB018AIFN50%7CB018AIFN9Q%7CB018AIFLYS%7CB018AIFLSY%7CB018AIFN6Y%7CB018AIFM4C%7CB018AIFLFM%7CB018AIFR6K%7CB01E78WKEO%7CB010B4RSLI&ie=UTF8&qid=1466508917" ADD_DATE="0">2759</A>` may be missing, this situation has another nature and will have separate issue (https://github.com/brave/sync/issues/289).

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 0.63.0 Chromium: 73.0.3683.39 (Developer Build) (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes, release/beta/dev.

**Comment by AlexeyBarabash** [comment]
Here is an explanation why https://github.com/brave/brave-core/pull/2016 fixes this issue.

Description of lost bookmarks situation:
```
1. Device1 is inserted into sync chain
2. SQS_dev1 is created
3. Device1 starts immediately send records to sync. It sends records both into S3 storage and SQS_dev1
   It probably sends more than 1000 records.
4. Device2 connects to chain
5. SQS_dev2 is created
6. There are some records had been sent to S2, SQS_dev1 and not yet into SQS_dev2, because according to logs there are several seconds (I had observed ~20 sec) between SQS_dev2 create request and appearing of SQS_dev2 in list_queues on AWS lambda
7. Device1 sends data into S3, SQS_dev1 and SQS_dev2
8. Device2 reads all the records available in S3 storage
9. Device2 had complate read all available data in S3 and starts read data from SQS_dev2. It misses records from pt6. All records after pt6 are well synced.
```

After the fix Device1 sends data when SQS_dev2 is ready, so there are no bookmarks lost.

Also tested with 3 devices: 3rd device also got all the records.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.31 Chromium: 73.0.3683.75 (Official Build) beta(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

- Verified STR from description 4x - each time all bookmarks were synced as expected.
