### ISSUE TITLE
[iOS] Update "Deprecated Sync Code Message"

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-browser#37775]
When a user tries to connect a new device with a Sync code in the old format (24 words), we tell them to upgrade their main device first.

This is the issue for tracking the change and testing on iOS side. https://github.com/brave/brave-browser/issues/37769

Old message was 

This sync code was generated by an outdated version of Brave on another device. Please update Brave on all synced devices and try again.

And change it to 

It looks like this code was created on a device running an older version of Brave. Please update to the latest version of Brave on your other device, and then create a new sync code.

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.5
Brave build: 1.67 (90)
BraveCore: 1.67.90 (125.0.6422.60)
```
---------------------------

**STEPS:**
1. Launch Brave on any device (Desktop or Mobile)
2. Go to the `Sync` settings > Add new device
3. Choose the `Code words` option > Copy the phrase
4. Go to the `iOS` device > Settings > Sync
5. I have a Sync Code > Enter code words
6. Copy the phrase and remove one word
7. Tap `Confirm` > *Verify*

**ACTUAL RESULTS:**
- Verified that the `Unable to Connect` message has new strings:
`It looks like this code was created on a device running an older version of Brave. Please update to the latest version of Brave on your other device, and then create a new sync code.`

---------------------------

|Old message|New message|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/fbe32c79-e22f-4d43-90fc-0a94b9f327c5) | ![2](https://github.com/brave/brave-browser/assets/128532965/95d331c8-eb73-42db-8670-5eaf6bb69816) |
