### ISSUE TITLE
Use isRetriable Property in Desktop Front End 

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#37776]
## Description 

Follow up to https://github.com/brave/brave-core/pull/23152#pullrequestreview-2015035674 we need to use the `isRetriable` property to display the `Retry` button in the Desktop Front-end.

- This will add support for `Solana` dropped transactions.
- `Swap` transactions cannot be retired as it makes more sense to start over with a new quote from UI flow.
- Partial signed transactions cannot be retried unless using a durable nonce, because dApp needs to re-sign the new transaction too.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.92 Chromium: 125.0.6422.76 (Official Build) beta (64-bit)
-- | --
Revision | d751d2edf40b466560aaeecc4c4919041f41c20d
OS | Windows 11 Version 23H2 (Build 22631.3593)

- Verified steps from [brave/brave-core#23222](https://github.com/brave/brave-core/pull/23222)
- Verified transaction errors out when its not submitted for more than `1 1/2`  mins
- Verified transaction shows as error under activity
- Verified `Retry transaction` is shown on errored out transaction
- Verified able to resubmit the transaction and confirmed 

https://github.com/brave/brave-browser/assets/17010094/e439e033-fde4-49f2-8770-2c80941a5b8a
