### ISSUE TITLE
Speedreader is not auto-activated on Time.com when clicked via Brave News feed

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#37780]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/36583.  Time articles opened via Brave news, Speedreader is not auto-activated after enabling `After use Speedreader for all sites` in the Speedreader toolbar

## Steps to Reproduce

   1. Install 1.66.86
   2. launch Brave
   3. load time.com
   4. click to open an article https://time.com/6962665/tipping-labor-issue-kim-kelly/
   5. click Speedreader icon 
   6. verified article displayed on Speedreader mode
   7. enable toggle `Always use Speedreader for all sites` 
   8. open a new tab and enable news
   9. follow `Time` via Brave News Dashboard
   10. clicked Times articles 
   
## Actual result:

Speedreader is not auto-activated for Time articles

https://github.com/brave/brave-browser/assets/98358127/29eaa8a9-7f0d-4062-8f41-a25fd50f6748

## Expected result:
Speedreader should auto-activate for Time articles enabled via Brave News

## Reproduces how often: 

Easily

## Brave version (brave://version info)

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@LorenzoMinto @boocmp 
cc: @rebron @brave/qa-team

**Comment by stephendonner** [comment]
Thanks for logging this.

I verified https://github.com/brave/brave-browser/issues/36583 even though a few cases failed; I think the behavior is still better than when this dual-preference version shipped, but it's still non-intuitive that you need to either
- explicitly click the `Speedreader` icon for each site and/or
- also mark the `Always use Speedreader for this site` preference, and revisit

**Comment by boocmp** [comment]
It shouldn't auto-activate if there is only '_Always use Speedreader for all sites_' enabled, you need to '_enable for this site_' (explicitly for time.com). _Always use Speedreader for all sites_ toggle is applying only on suitable urls (which looks like news articles, blogs, etc).

**Comment by boocmp** [comment]
Suitable urls are urls which contain at least one _blogs, news, story, entry, articles, posts, amp, technology, politics, business_ sub-strings in the path or contain _blog._ in sub-domain or contain a date in the path (e.g /2024/04/23/ or /2024/04/)

**Comment by MadhaviSeelam** [comment]
Closing the issue as it's working as expected as per @boocmp comments above


https://github.com/brave/brave-browser/assets/98358127/57e7ff9d-9ad5-4751-a586-2194b86dbc8f

**Comment by stephendonner** [comment]
> It shouldn't auto-activate if there is only '_Always use Speedreader for all sites_' enabled, you need to '_enable for this site_' (explicitly for time.com). _Always use Speedreader for all sites_ toggle is applying only on suitable urls (which looks like news articles, blogs, etc).

Oh, thanks, @boocmp I didn't fully realize the separation, there, until you helpfully explained it!
