### ISSUE TITLE
Satoshi Pay not showing up

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#3778]
## Description 

https://drive.google.com/file/d/1d9A_f7dSJCPPy30kb83e7APOqtYHFR6a/view

- http://naftalimusic.com/
- http://ibtimes.satoshipay.xyz/2017/12/06/blockchain-experts-provide-contrasts-and-predictions-on-consensus-protocols/
- https://www.adriankezele.com/okus-proboja/

## Steps to Reproduce

   1. Load one of the pages above 
   2. See blue box without a pay option

## Actual result:

No pay option

## Expected result:

Pay option

## Reproduces how often: 

Always

## Brave version (brave://version info)

Nearly up to date! Relaunch Brave to finish updating.
Version 0.63.13 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes, it is cookie related
- Is the issue reproducible on the latest version of Chrome?  Yes

**Comment by andywer** [comment]
Hey guys!

Some details: `https://wallet.satoshipay.io/client.js` (runs in an iFrame) needs access to the local storage in order to work, but is not allowed to.

**Comment by diracdeltas** [comment]
sounds like this would be fixed by https://github.com/brave/brave-browser/issues/2157
