### ISSUE TITLE
Browser crashes when the second split view tab is closed

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#37784]
## Description 

When creating a split view and switching between the two tabs or tab content and then closing the second split view tab crashes the browser often.

Doesn't seem to happen 100% of the time, so the easiest way to reproduce this crash 100% in my tests is by using a complete new profile with only the split view flag enabled. All I did was to duplicate the Welcome Page, click on the first tab and then the second and then closing the second tab caused the crash.

https://github.com/brave/brave-browser/assets/156715894/e7f8de92-ee0c-4883-bc8d-98bf5c89bdbd

1.67.30 Chromium: 124.0.6367.60 (Official Build) nightly (64-bit) 
Windows 11 Version 23H2 (Build 22631.3447)

@sangwoo108

**Comment by iefremov** [comment]
changing the priority as split view is not launched

**Comment by simonhong** [comment]
I think this kind of crash could be fixed by https://github.com/brave/brave-core/pull/26826.
Feel free to re-open when you see this crash again.

**Comment by rebron** [comment]
Will dupe this out to https://github.com/brave/brave-browser/issues/42518
