### ISSUE TITLE
Ads not shown if a background tab is playing video

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3779]
## Description 

Ads not shown if a background tab is playing video

## Steps to Reproduce

   1. Enable rewards/ads on a new profile
   2. Play a YT video in a background tab
   3. Open a new tab and complete criteria to trigger ad
   4. Console shows error saying `Notification not made: Media playing in browser`

## Actual result:

```
[1:1:0319/101004.376191:INFO:ads_impl.cc(628)] Notification not made: Media playing in browser
```

## Expected result:
Ad should be shown 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @brave/legacy_qa @tmancey @jsecretan @mandar-brave

**Comment by kjozwiak** [comment]
Seeing the same thing on `macOS 10.14.3 x64` using the following build:

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

Example:

```
[7814:775:0319/204849.718123:INFO:ads_impl.cc(209)] Browser state changed to idle
[7814:775:0319/204902.730308:INFO:ads_impl.cc(216)] Browser state changed to unidle
[7814:775:0319/204902.731913:INFO:ads_impl.cc(628)] Notification not made: Media playing in browser
```

**Comment by LaurenWags** [comment]
Verified passed on

Brave | 0.68.118 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2575
* When media (YT, Netflix, rainymood.com) is playing on the non-active (blurred) tab and brave is in the foreground, I am able to get notifications for ads.
* When media (YT, Netflix) is playing in the active tab, I see `[23278:775:0805/161334.958972:INFO:ads_impl.cc(641)] Notification not made: Media playing in browser` in the logs.
