### ISSUE TITLE
GetPageContent waits forever on inactive tab hosting pdf content

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#37794]
It can only be resolved by refreshing the tab on users end now.

We need a better way handling AIChatTabHelper won't receive a11y event of `IDS_PDF_LOADED_TO_A11Y_TREE` in that situation, otherwise `AIChatTabHelper::OnPDFA11yInfoLoaded()` will never be called unless page reload.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.68.85 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | 8e76a669cf78bdfa933c8d569460092a01166588
OS | Windows 10 Version 22H2 (Build 19045.4474)
```
