### ISSUE TITLE
Leo - Add "You / Leo" name indicator besides avatar on the top header of every prompt/answer

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#37793]
## Description: 
- Addding the name of the sender at the right side of the avatar.

**Design example:**
https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=3125%3A40451&mode=design&t=SWVdp58qkdjl54Jg-1

**Design system for button states:**
https://www.figma.com/file/MNwi0uwXNhkAbPiJ86G4vm/%E2%9C%A8-Leo?type=design&node-id=1506%3A8040&mode=design&t=MzAuxvpPR619wmZL-1

## Expected result:
![image](https://github.com/brave/brave-browser/assets/15734630/fbefce6e-0761-433b-82ee-9a7702a1d42e)
-------------

**Comment by kjozwiak** [comment]
The above requires `1.68.112` or higher for `1.68.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iPadOS 17.5.1` using version `1.68.117`

- Ensured that `You` is shown beside the users avatar for every prompt.
- Ensured `You` is shown when summarizing, retrieving suggested questions and uncontext messages.

Example | Example
-|-
![IMG_1494](https://github.com/brave/brave-browser/assets/17885425/aa4ab4a8-450f-4136-bc32-f3cecb152511) | ![IMG_1495](https://github.com/brave/brave-browser/assets/17885425/343c9dee-39a1-4bba-975c-d7be22db059e)
