### ISSUE TITLE
pin tab distortions

### ISSUE THREAD

**Issue by edmundlaugasson** [brave/brave-browser#378]
## Description 
Could not find an earlier issue. When to pin a new tab then earlier one appears occasionally, accidentally also. When to unpin a tab - it does not unpin unless to activate any other tab. This unpinned and closed tab might be back as soon as you try to pin a new tab.

## Steps to Reproduce
   1. open some tabs
   2. pin some tabs
   3. unpin one or more tabs

 ## Actual result:
When to pin new tab, it will be pinned but also one previously unpinned and closed tab will be also pinned. When unpinning a tab it will not unpinned unless any other tab activated. Once Brave even crashed and closed window while trying to pin a tab... After reopening the tab was pinned.

## Expected result:
Pin and unpin works flawlessly without requiring additional actions nor pinning additional already unpinned, closed tabs.

## Reproduces how often: 
every time when to pin or unpin a tab

## Brave version (about:brave info)
Name | Version
Brave | 0.22.810
V8 | 6.7.288.43
rev | 8f30eeb
Muon | 7.0.6
OS Release | 4.15.18-041518-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.71

### Reproducible on current release:
yes

**Comment by srirambv** [comment]
@edmundlaugasson  Request you to kindly open issue on https://github.com/brave/browser-laptop/issues/ relating to browser-laptop. This repo is for new brave-core issues only. 

Closing in favour of https://github.com/brave/browser-laptop/issues/14443
