### ISSUE TITLE
Card Header Buttons are not Consistent in Size

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#37801]
## Description 

Card Header Buttons are not Consistent in Size

## Steps to Reproduce

   1. Open the `Wallet` and navigate to an `Asset Detail` or `Account Details` screen
   2. The `Back` button and `Menu` button are not the same size.

## Actual result:

![Screenshot 26](https://github.com/brave/brave-browser/assets/40611140/b763b59d-1b83-41ac-a1fd-c0fd2220aae6)

## Expected result:

Should be consistent in sizes.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.85 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | d01060f5ec155e6eb64a335203663a29c0e5d81f
OS | Windows 11 Version 23H2 (Build 22631.3593)

- Verified steps from [ brave/brave-core#23250](https://github.com/brave/brave-core/pull/23250)
- Verified Card header buttons are of same size on both `Account Details` and `Asset Details` screen

![brave_1pjAcqKxNW](https://github.com/brave/brave-browser/assets/17010094/837c1b5e-a40f-4ffb-8f89-dd724d7f4153) | ![brave_L7qt5lFR1L](https://github.com/brave/brave-browser/assets/17010094/815b2513-7453-4a09-9916-2f7c9fe3d000)
-- | --
![brave_IUIuuyiYRu](https://github.com/brave/brave-browser/assets/17010094/2530bbc5-0a42-47e0-8b76-7c74b93beff7) | ![brave_fP07lXNok9](https://github.com/brave/brave-browser/assets/17010094/002b4007-d9a7-4bc5-bab5-a0493db3cf0c)
