### ISSUE TITLE
Rewards verified status should be fetched from list value rather than from database

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#3780]
## Description 

If a user visits an unverified site that later becomes verified, that site will still show unverified for that user

## Steps to Reproduce

   1. Enable Rewards clean profile
   2. Visit an unverified site and ensure place in `publisher_info_db`
   3. Quit Brave and modify site value in `publisher_list` to verified
   4. Restart Brave and go to site modified above

## Actual result:

Site still shows as unverified

## Expected result:
Site should show verified

## Reproduces how often: 

100%

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
blocked on https://github.com/brave/brave-browser/issues/4025 and https://github.com/brave/brave-browser/issues/3953

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.65.98 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2078
* Also verified test plan steps using both YouTube and Twitch channels. When YT and Twitch channels are not verified, the generic YT or Twitch icon was used as appropriate (both the site specific favicon and verified icons no longer displayed on brave://rewards or panel).
