### ISSUE TITLE
Autofill from Keepass2Android doesn't work in Brave Beta

### ISSUE THREAD

**Issue by gbil** [brave/brave-browser#37807]
## Steps to reproduce 

   1. Have Keepass2Android autofill enabled as default autofill service
   2. Install latest Brave BETA version eg. 1.66.80
   3. Open a site where autofill worked before or works with normal Brave eg. https://passwordbits.com/test-form-fields/ 

## Actual result 
   Autofill popup doesn't appear

## Expected result
Autofill popup should appear

## Issue reproduces how often 
Always

## Version/Channel Information:

Only in Beta channel, works fine in the normal release 
- Can you reproduce this issue with the current Play Store version?  No
- Can you reproduce this issue with the current Play Store Beta version?  Yes
- Can you reproduce this issue with the current Play Store Nightly version? haven't tried 

## Device details
   - Install type (ARM, x86): arm
   - Device type (Phone, Tablet, Phablet): various Android phones and tablets
   - Android version: 14
   
## Brave version
1.66.80
but also on previous beta ones since some time 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional information

as stated, used to work on beta version, can't go back and check which one as I don't want to lose my data. Works in normal Brave, works in Chrome beta, also checked that Keepass2Android still has the relevant Brave beta definitions in their autofill xml and it does. Looks like a brave issue

**Comment by Beatz106** [comment]
Today it is not a priority of the browser. To this day I am still waiting to change browsers, of course without having to go through the issue of writing down passwords.

**Comment by gbil** [comment]
Seems fixed in 1.66.90
