### ISSUE TITLE
Context menu for playlist items doesn't show up

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#37808]
## Description 

When clickng '...' button on playlist item, the context menu doesn't show up

## Steps to Reproduce

   1. Add playlist item
   2. Open web ui and go to the folder that the item was stored
   3. Move mouse over the item and click '...' button

## Actual result:

Context menu doesn't show up

## Expected result:
Context menu should show up

## Reproduces how often: 

Always

## Version/Channel Information:
The context menu seems to have broken between 1.67.17 and 1.67.18

## Miscellaneous Information:

Internal thread: https://bravesoftware.slack.com/archives/CKJCXTP9B/p1713466687592079

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.67.45 Chromium: 124.0.6367.91 (Official Build) nightly (x86_64)
-- | --
Revision | f5b8b1597695a9fa4b57874e2a469ef8ad62ff48
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.67.45`
2. launched Brave
3. enabled playlist via `brave://flags`
4. restarted Brave
5. added https://www.youtube.com/watch?v=JP3R00tCL4I to playlist
6. clicked on the queue in Sidebar
7. context-clicked on the `...` ellipsis

## Confirmed working context-menu items

example | example | example
---------|----------|---------
<img width="1396" alt="Screen Shot 2024-04-29 at 5 33 45 PM" src="https://github.com/brave/brave-browser/assets/387249/e55ae503-192a-46bb-932e-b0fd007be4ab"> | <img width="1396" alt="Screen Shot 2024-04-29 at 5 33 49 PM" src="https://github.com/brave/brave-browser/assets/387249/170327c6-a399-4548-8bcf-de9985cd0781"> | <img width="1396" alt="Screen Shot 2024-04-29 at 5 33 58 PM" src="https://github.com/brave/brave-browser/assets/387249/99d57d27-c5b6-4aed-9119-dd0a5ac56fdc">
