### ISSUE TITLE
Network Icon is Missing in Asset Details

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#37818]
## Description 

The network icon is missing in the `Asset Details` view

## Steps to Reproduce

   1. Open the `Wallet` and select an asset
   2. The network icon is missing in the header.

## Actual result:

![Screenshot 4](https://github.com/brave/brave-browser/assets/40611140/d3ca44d0-8e68-4ff9-89b3-b5900a2f0157)

## Expected result:

![Screenshot 5](https://github.com/brave/brave-browser/assets/40611140/2bf67151-9246-4aa9-82da-8dbdb6e466b6)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ucark** [comment]
sa moruq

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.86 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | a1f8e8f462d422d4b924fa9c34246f68862b21ad
OS | Windows 11 Version 23H2 (Build 22631.3593)

- Verified steps from [brave/brave-core#23262](https://github.com/brave/brave-core/pull/23262)
- Verified Network icon is shown on Asset details screen

https://github.com/brave/brave-browser/assets/17010094/61c94013-5032-411b-9793-4297ea46a26e
