### ISSUE TITLE
Only Solana and Ethereum account is shown in account selection dropdown

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#37813]
## Description 
Only Solana and Ethereum account is shown in account selection dropdown

## Steps to reproduce 

   1. Create a new wallet
   2. Create multiple FIL and BTC accounts
   3. Open panel and select Filecoin network
   4. Shows FIL account
   5. Click on Account picker only shows ETH/SOL accounts
   6. Repeat same steps for BTC, same result

## Actual result 

https://github.com/brave/brave-browser/assets/17010094/60d847cb-ef72-423d-b2b7-032ee4296176

## Expected result
Should list available accounts for the selected network

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 14
   
## Brave version
1.66.80

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe

**Comment by simoarpe** [comment]
That's expected, we show only accounts that support DApps. As of today we show Sol and Eth.

**Comment by srirambv** [comment]
I think this is a bad UX. Clicking that dropdown has been to select accounts for the selected network. Maybe we should hide the account selection dropdown if the network is not ETH/SOL.
