### ISSUE TITLE
No  instruction for installing  nightly releases in linux.

### ISSUE THREAD

**Issue by Techguyprivate** [brave/brave-browser#3782]
## Description 

No instruction to install nightly releases in linux install instruction.

## Steps to Reproduce

   1. Go to releases. 
   2. Click on linux installation instruction.
   3. http://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

### Additional Information

There is a link given under nightly releases for installing in linux . I clicked on the link to install the nightly releases , but there is no instruction to install nightly version , only stable, dev, beta. Will be there instruction to install nightly by adding sources and keys as for linux mint or ubuntu to get updates? Or one have to download the .deb .rpm files & manually update it ?

**Comment by bsclifton** [comment]
cc: @mbacchi @bkero

**Comment by mihaiplesa** [comment]
ready to merge
