### ISSUE TITLE
Leo - Simplify AI model intro and add tooltip for more details

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#37825]
## Description 

We're simplyfing the model introduction for each new conversation. This includes:

- Only visible content at the initial state will be the Model type (Chat) / Model name / Model creator / Info icon
- When you click/tap the info button, users get a tooltip with the model description.
- There's a new piece of content that indicates if the model is hosted by Brave or not.
- We include a "Learn more" link in case we want to link users to more info.

https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=3096%3A80072&mode=design&t=WqIHp5r9TFoBBBtg-1

## Actual result:

<img width="396" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/427e93d5-d117-44c0-bd4f-93340be3ef0d">

## Expected result:
![image](https://github.com/brave/brave-browser/assets/15734630/d5cc27b4-7aab-46b2-908b-e3b6023cd643)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.67.76 Chromium: 125.0.6422.26 (Official Build) nightly (64-bit)
-- | --
Revision | c8696983cac61f6c5a22bc23ca991c20737fd0b0
OS | Windows 10 Version 22H2 (Build 19045.4355)
```

## Non-`Premium` (default)

## `Premium`

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.67.92 Chromium: 125.0.6422.76 (Official Build) beta (64-bit) 
Revision	d751d2edf40b466560aaeecc4c4919041f41c20d
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
**New Onboarding (NTP)**

- Ensured graphics are removed from the onboarding and theme matches the figma specs.
- Ensured user is able to complete onboarding when summarizing with Leo. 

Example | Example | Example
-|-|-
![Screenshot 2024-05-24 at 5 10 03 PM](https://github.com/brave/brave-browser/assets/17885425/317cd04b-b721-4611-bfae-ade8a32a35c8) | ![Screenshot 2024-05-24 at 5 11 26 PM](https://github.com/brave/brave-browser/assets/17885425/8eb5fac4-9368-44c4-9796-b7af994028ab) | ![Screenshot 2024-05-24 at 5 12 18 PM](https://github.com/brave/brave-browser/assets/17885425/927f6e3f-2b08-4199-967c-9edab1be617d)


**New Onboarding (Webpage)**

- Ensured graphics are removed from the onboarding and theme matches the figma specs.
- Ensured context switch is displayed and disabling switching will remove the summarize block.
- Ensured user is able to complete onboarding when summarizing with Leo. 

Example | Example | Example | Example | Example
-|-|-|-|-
![Screenshot 2024-05-24 at 5 32 03 PM](https://github.com/brave/brave-browser/assets/17885425/3093a4ba-4aed-430d-98ad-b7d2f0e4bd55) | ![Screenshot 2024-05-24 at 5 32 37 PM](https://github.com/brave/brave-browser/assets/17885425/caf23bd4-9630-4426-a781-00413239b470) | ![Screenshot 2024-05-24 at 5 32 42 PM](https://github.com/brave/brave-browser/assets/17885425/680eb636-8f6a-4272-acf8-12f235ca41bb) | ![Screenshot 2024-05-24 at 5 32 58 PM](https://github.com/brave/brave-browser/assets/17885425/b4c7224b-be88-4eed-8a4e-29954d1356d8) | ![Screenshot 2024-05-24 at 5 33 26 PM](https://github.com/brave/brave-browser/assets/17885425/f2c8cf16-8d85-4987-9c4c-5a01ee4ff28f)

**Tool Tip**

- Ensured tool tip is shown beside the model name.
- Ensured that tapping on tool tip icon will display the dialog.
- Ensured tapping on `Learn more` will launch the support page.
- Ensured tapping anywhere in chat will dismiss the tool tip.
- Ensured tool tip displays correctly for each of the models. 
- Ensured tool tip is displayed ok in both orientations.

Mixtral | Claude Instant | Haiku | Sonnet | Llama | Support page
-|-|-|-|-|-
![Screenshot 2024-05-24 at 5 14 11 PM](https://github.com/brave/brave-browser/assets/17885425/9e253bc2-01ed-4b7b-a9ae-2a6d64937a2d) | ![Screenshot 2024-05-24 at 5 25 51 PM](https://github.com/brave/brave-browser/assets/17885425/79431b13-3b7f-49e5-b441-f56aa8b9346b) | ![Screenshot 2024-05-24 at 5 25 43 PM](https://github.com/brave/brave-browser/assets/17885425/29495a7c-d4bf-4e6e-8ba4-b55eefce0bcc) | ![Screenshot 2024-05-24 at 5 27 16 PM](https://github.com/brave/brave-browser/assets/17885425/6cbabe15-78c4-4f66-99ff-ada46daad482) | ![Screenshot 2024-05-24 at 5 26 25 PM](https://github.com/brave/brave-browser/assets/17885425/0af6f603-2123-4e2b-a507-533c3efd22ab) | ![Screenshot 2024-05-24 at 5 14 16 PM](https://github.com/brave/brave-browser/assets/17885425/98bb7438-af52-4ff4-9597-90a67da587dc)
