### ISSUE TITLE
verified sites not showing correct favicon in panel - follow up to 3525

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3783]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/3525

Verified publisher sites (non YT or Twitch) are not displaying favicon in the panel correctly. 

## Steps to Reproduce

   1. Clean profile.
   2. Enable Rewards
   3. Visit a verified site (brave.com, basicattentiontoken.org, ddg, etc)
   4. Wait a few seconds, open panel.

## Actual result:
Favicon not shown. If you wait some time, after opening/closing panel the favicon will probably be shown.
![Screen Shot 2019-03-19 at 1 19 38 PM](https://user-images.githubusercontent.com/28145373/54629489-0b5c1780-4a4e-11e9-942d-38f3ea1aeb1a.png)

## Expected result:
Favicon should be shown.
![Screen Shot 2019-03-19 at 1 55 12 PM](https://user-images.githubusercontent.com/28145373/54629773-a35a0100-4a4e-11e9-96b6-40a76d2f15a9.png)

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

### Reproducible on current release: no
- Does it reproduce on brave-browser dev/beta builds? Dev yes, beta no.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
If you run thru STR with a non-verified site (google, nyt) or a verified youtube or twitch pub, the favicon displays as expected.
Reproduced by @GeetaSarvadnya @kjozwiak on Win and Linux respectively

**Comment by LaurenWags** [comment]
Also occurs when using staging environment (need to use a different set of verified sites for testing).

**Comment by btlechowski** [comment]
Reproduced on

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

![image](https://user-images.githubusercontent.com/34715963/54711301-e947bf80-4b49-11e9-985d-f7ac063dcff0.png)

**Comment by NejcZdovc** [comment]
@LaurenWags can you try this on the latest nightly. I can't reproduce on latest 0.64

**Comment by LaurenWags** [comment]
I don't know what version you tried @NejcZdovc but I reproduced with latest Nightly available for macOS

Brave | 0.64.8 Chromium: 73.0.3683.75 (Official Build) nightly(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

![Screen Shot 2019-03-25 at 10 10 33 AM](https://user-images.githubusercontent.com/28145373/54926246-48a92500-4ee6-11e9-9110-12dae98219fc.png)

**Comment by btlechowski** [comment]
@NejcZdovc I am able to reproduce on Windows nightly

Brave | 0.64.8 Chromium: 73.0.3683.75 (Official Build) nightly (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

![image](https://user-images.githubusercontent.com/34715963/54963838-82bc0a80-4f6a-11e9-92bc-0ee0811405fe.png)

**Comment by NejcZdovc** [comment]
1) can you please inspect this icon and pass url of it?
2) is domain that you are on with www or without?
3) if you reopen panel will this fix the problem?

**Comment by NejcZdovc** [comment]
found the problem, this regressed with this one https://github.com/brave/brave-core/pull/1649, so would be good to uplift fix to 0.62.

cc @brave/uplift-approvers

**Comment by kjozwiak** [comment]
> found the problem, this regressed with this one [brave/brave-core#1649](https://github.com/brave/brave-core/pull/1649), so would be good to uplift fix to 0.62.
> 
> cc @brave/uplift-approvers

@NejcZdovc did this regress in `0.62.x`? I can't seem to reproduce it using `0.62.41 Chromium: 73.0.3683.86` and I can reproduce it with both `0.63.20 Chromium: 73.0.3683.75` and `0.64.8 Chromium: 73.0.3683.75` using the STR that @LaurenWags mentioned under https://github.com/brave/brave-browser/issues/3783#issue-422873661.

**Comment by NejcZdovc** [comment]
if that is the case then we can uplift only in 63

**Comment by LaurenWags** [comment]
I have been unable to reproduce with most recent 0.62.x version on macOS

Brave | 0.62.41 Chromium: 73.0.3683.86 (Official Build) beta(64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Mac OS X

**Comment by kjozwiak** [comment]
Thanks for the double check @LaurenWags 👍

> if that is the case then we can uplift only in 63

Sounds good! Thanks @NejcZdovc.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.30 Chromium: 73.0.3683.75 (Official Build) beta(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

- Verified test plan from https://github.com/brave/brave-core/pull/2077
- Verified STR from description
