### ISSUE TITLE
[iOS] - VPN Linking sometimes doesn't work due to Invalid ProductID

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#37837]
## Description: 
- VPN code sends `brave-firewall-vpn-premium` but never sent `brave-firewall-vpn-premium-yearly` so it does not distinguish between a monthly purchase vs. a yearly purchase when LINKING subscriptions with the Desktop/Website.
- This code was updated via find/replace and changed to `.vpnMonthly` enum, but did not account for yearly.

We should update the code to store the productId for now, and use that productId to send to the website when linking.
In the future, once VPN code has migrated to the same StoreKit-2 that AI-Chat uses, we can get rid of this preference and just use the ProductId directly!

## Steps to Reproduce 
  1. Attempt to link a yearly product

## Actual result: 
- iOS sends the `bravevpn.monthly` productId

## Expected result:
- iOS should send `bravevpn.yearly`

## Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily reproduced

## Brave Version: 
- All versions

### Device details: 
- All devices

### Website problems only:
- account.brave.com, account.bravesoftware.com

**Comment by kjozwiak** [comment]
The above requires `1.66.102` or higher for `1.66.x` verification 👍

**Comment by Uni-verse** [comment]
In progress on iPhone 12 using version 1.66.110
