### ISSUE TITLE
[Wallet] Receipt button not working in transaction status panel view

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#37835]
## Description 

After submitting a transaction, when it is confirmed a view appears with buttons to allow closing the panel or viewing the transaction receipt. The Receipt button currently does not do anything when clicked.
<img width="320" alt="Screenshot 2024-04-24 at 6 45 26 PM" src="https://github.com/brave/brave-browser/assets/30185185/983dbbb1-97d7-446a-96f9-beb705316331">

## Steps to Reproduce

   1. Initiate and approve a transaction
   2. wait for confirmation in the panel
   3. click the "Receipt" button

## Actual result:

Nothing happens

## Expected result:
User should see the details of the transaction

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.85 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | d01060f5ec155e6eb64a335203663a29c0e5d81f
OS | Windows 11 Version 23H2 (Build 22631.3593)

- Verified steps from issue description
- Verified clicking on the Receipt button loads the transaction status panel view

https://github.com/brave/brave-browser/assets/17010094/00790808-992e-479e-9072-d75f62721841
