### ISSUE TITLE
Leo - Simplify AI model intro and add tooltip for more details (iOS)

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#37832]
This is a sister issue for iOS for this work:
https://github.com/brave/brave-browser/issues/37825

**Comment by Brandon-T** [comment]
Fixed in: https://github.com/brave/brave-core/pull/23440

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6
Brave build: 1.68 (106)
BraveCore: 1.68.106 (126.0.6478.126)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/23440#issue-2281277751 and https://github.com/brave/brave-browser/issues/37825#issue-2261764471
2. *Verify*

<details>
<summary> New Onboarding (NTP) </summary>

**ACTUAL RESULTS:**
- Verified Leo onboarding flow  screens
- Verified that user is able to finish onboarding

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/0c2ecfd6-46aa-443e-8daf-eb4c91019367) | ![2](https://github.com/brave/brave-browser/assets/128532965/03c9a589-f745-4045-87e3-e20b03b3a375) | ![3](https://github.com/brave/brave-browser/assets/128532965/e719578e-0b55-47f7-b9eb-d03f315fc512) |
</details>

<details>
<summary> New Onboarding (Webpage) </summary>

**ACTUAL RESULTS:**
- Verified Leo onboarding flow  screens
- Verified that user is able to finish onboarding

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/b3cde0f0-402b-4dd4-b913-f17e6e07eb22) | ![2](https://github.com/brave/brave-browser/assets/128532965/18a87836-3653-4afd-8a04-001908788b50) | ![3](https://github.com/brave/brave-browser/assets/128532965/471aefd8-3228-4fba-a743-9dcde4c783d5) |
</details>

<details>
<summary> Tooltip </summary>

**ACTUAL RESULTS:**
- Verified that `tooltip` is shown beside the model name.
- Verified that tapping on the tooltip icon will display the dialog.
- Verified that tapping on `Learn more` will launch the support page.
- Verified that tapping anywhere in chat will dismiss the tooltip.
- Verified that the tooltip displays correctly for each of the models.
- Verified that the tooltip is displayed ok in both orientations.

---------------------------

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/67c7eeb6-fed1-4d9e-be4e-423abf356230) | ![2](https://github.com/brave/brave-browser/assets/128532965/b267c804-bb9a-4859-9286-4fbe4c5aa422) | ![3](https://github.com/brave/brave-browser/assets/128532965/e96f03a6-1f75-4f84-86ae-1385d33ceb5b) | ![4](https://github.com/brave/brave-browser/assets/128532965/b4e0f6c1-61aa-4b56-9954-d0b291442887) | ![5](https://github.com/brave/brave-browser/assets/128532965/c51570dd-fcbd-44d6-b30c-b71e2568e175) |
</details>
