### ISSUE TITLE
Update Select Token Modal

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#37838]
## Description 

We need to update the `Select Token` modal to latest designs and flows in `Figma`

- Adds a `Network` filter
- Adds an `Account` filter
- Adds a `Recently Traded Pairs` section
- Adds a `Show zero balance tokens` button
- Will now be a flat list of tokens and moves away from grouping assets by `Account`
- Introduces a `Select Account` modal after selecting a `Token` to swap

![Screenshot 6](https://github.com/brave/brave-browser/assets/40611140/1254d5b8-ac3f-4b0d-b6d0-7a6c209c51be)
![Screenshot 9](https://github.com/brave/brave-browser/assets/40611140/4affef38-f45f-4269-b6cc-7a66794bf400)
![Screenshot 7](https://github.com/brave/brave-browser/assets/40611140/b082498e-f1a3-46d9-ba63-9febb64f59e8)
![Screenshot 8](https://github.com/brave/brave-browser/assets/40611140/4125ef38-dc0f-4553-a6c8-df7093ae7941)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.68.84 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | c5a3b2ff9dcc938c32b2c1b3a66847661db5d005
OS | Windows 11 Version 23H2 (Build 22631.3672)

- Verified steps from [brave/brave-core#23467](https://github.com/brave/brave-core/pull/23467)
- Verified selecting a token shows account selection screen
- Verified token list shows token listed under `Owned` and `Not owned` 
- Verified `Not owned` tokens shows an info button which when clicked loads the block explorer in a new tab
- Verified when token balance is from multiple accounts, shows a user icon next to balance

https://github.com/brave/brave-browser/assets/17010094/21e9ec89-28b8-4521-9cde-6208212ff75a
