### ISSUE TITLE
[hackerone] Reduce WireGuard tunnel service permissions on Windows

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#37846]
originally reported at https://hackerone.com/reports/2473183 by `newfunction`. 

suggested fix - https://bravesoftware.slack.com/archives/C6R461GF4/p1713994125371129?thread_ts=1713731727.148139&cid=C6R461GF4

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS`  using

```
Brave | 1.68.85 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | 8e76a669cf78bdfa933c8d569460092a01166588
OS | Windows 10 Version 22H2 (Build 19045.4474)
```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.68.91 Chromium: 126.0.6478.71 (Official Build) beta (64-bit)
-- | --
Revision | 3827c3d5452a7f550ce225de614895c444652af7
OS | Windows 11 Version 23H2 (Build 22631.3737)
```
### Steps:
1. installed `1.68.91`
2. confirmed `User-Access Control` prompt (not pictured)
3. confirmed installed the binary to `C:\Program Files\BraveSoftware\Brave-Browser-Beta`
4. opened `Services.msc` 
5. confirmed `BraveBetaVpnWireguardService` entry  
6. loaded `account.bravesoftware.com`
8. purchased, configured, and connected to `Brave VPN`
9. loaded `whatismyipaddress.com`
10. switched `Brave VPN` to `Canada`
11. clicked to toggle it to `Connect[ed]`
12. refreshed `whatismyipaddress.com`
13. confirmed it showed `Canada`
14. switched `Brave VPN` to `Germany`
15. refreshed `whatismyipaddress.com`
16. confirmed it showed `Germany`
17. disconnected from `Brave VPN`

`step 1` | `step 3` | `Canada` | `Germany` | `disconnected`
-------|-----------|---------|----------|----------------
