### ISSUE TITLE
[Brave News] Update News subscription metric buckets

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#37844]
Change News subscription metric buckets. Amend the metric names as well.

As a Brave News user this month...
How many external feeds do you have in total?
`Brave.Today.DirectFeedsTotal.3`

How many channels are you subscribed to?
`Brave.Today.ChannelCount.2`

How many publishers are you subscribed to?
`Brave.Today.PublisherCount.2`

0. 0
1. 1
2. 2-4
3. 5-8
4. 9-13
5. 14+

cc @LorenzoMinto

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.67.90`


### Brave.Today.DirectFeedsTotal.3

<details>
<summary>Brave.Today.DirectFeedsTotal.3 =0_PASSED</summary>

1. Clean profile 1.67.x
2. Enable brave news via NTP
3. Open brave://local-state file
4. Look for the metrics `Brave.Today.DirectFeedsTotal.3`
5. Confirmed that the metrics response value is `0` as expected
![image](https://github.com/brave/brave-browser/assets/38657976/6a186a1b-ddc9-4841-a671-6f6c4b858870)

</details>

<details>
<summary>Brave.Today.DirectFeedsTotal.3 =1_PASSED</summary>

1. Clean profile 1.67.x
2. Enable brave news via NTP and import a external RSS feed `https://www.fightmag.com.au/` via NTP dashboard
3. Open brave://local-state file
4. Look for the metrics `Brave.Today.DirectFeedsTotal.3`
5. Confirmed that the metrics response value is `1` as expected
![image](https://github.com/brave/brave-browser/assets/38657976/47fb5cca-003b-4bbf-9240-ad3c129c4b28)


</details>

<details>
<summary>Brave.Today.DirectFeedsTotal.3 =2_PASSED</summary>

1. Clean profile 1.67.x
2. Enable brave news via NTP and import two external RSS feeds using `http://stephendonner.wordpress.com/`
3. Open brave://local-state file
4. Look for the metrics `Brave.Today.DirectFeedsTotal.3`
5. Confirmed that the metrics response value is `2` as expected

![image](https://github.com/brave/brave-browser/assets/38657976/e8bd6106-b7ce-4ed6-a2c8-317abe616ed1)

</details>

<details>
<summary>Brave.Today.DirectFeedsTotal.3 =3_PASSED</summary>

1. Clean profile 1.67.x
2. Enable brave news via NTP and import 5 external RSS feeds using `http://stephendonner.wordpress.com/`
3. Open brave://local-state file
4. Look for the metrics `Brave.Today.DirectFeedsTotal.3`
5. Confirmed that the metrics response value is `3` as expected

![image](https://github.com/brave/brave-browser/assets/38657976/ee12260f-2b1b-4a37-a2d8-7c0611eefd8e)

</details>


### Brave.Today.ChannelCount.2

<details>
<summary>Brave.Today.ChannelCount.2 =0_PASSED</summary>

1. Clean profile 1.67.x
2. Open brave://local-state file
3. Look for the metrics `Brave.Today.ChannelCount.2`
4. Confirmed that the metrics isn't shown as expected

</details>

<details>
<summary>Brave.Today.ChannelCount.2 =1_PASSED</summary>

1. Clean profile 1.67.x
5. Enable brave news via NTP
6. Open brave://local-state file
7. Look for the metrics `Brave.Today.ChannelCount.2`
8. Confirmed that the metrics response value is `1` as expected as `Top source` is shown by default under channels

Example | Example
----------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/d8a46cf7-f305-4b68-bb24-2d5483793a3d) | ![image](https://github.com/brave/brave-browser/assets/38657976/1692d770-1db2-4b79-b706-bbf5b9243569)

</details>

<details>
<summary>Brave.Today.ChannelCount.2 =2_PASSED</summary>

1. Clean profile 1.67.x
2. Enable brave news via NTP
3. Click on `+` icon next to Channels and add a channel by clicking on + icon on channels
4. Open brave://local-state file
5. Look for the metrics `Brave.Today.ChannelCount.2`
9. Confirmed that the metrics response value is `2` as expected as two channels are shown under channels

Example | Example
----------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/403c5875-0115-43b3-8484-89c1ad26c513) | ![image](https://github.com/brave/brave-browser/assets/38657976/16330cf9-ff0b-494c-9ee8-9128ab49b005)


</details>

<details>
<summary>Brave.Today.ChannelCount.2 =3_PASSED</summary>

1. Clean profile 1.67.x
2. Enable brave news via NTP
3. Click on `+` icon next to Channels and add 5 channels by clicking on + icon on channels
4. Open brave://local-state file
5. Look for the metrics `Brave.Today.ChannelCount.2`
6. Confirmed that the metrics response value is `3` as expected as two channels are shown under channels

Example | Example
----------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/0020c6f1-edb0-4546-9272-bb47ef3b8afb) | ![image](https://github.com/brave/brave-browser/assets/38657976/349b754e-6e4a-4834-9478-0cd389fc92a4)

</details>

<details>
<summary>Brave.Today.ChannelCount.2 =4_PASSED</summary>

1. Clean profile 1.67.x
2. Enable brave news via NTP
3. Click on `+` icon next to Channels and add 9 channels by clicking on + icon on channels
4. Open brave://local-state file
5. Look for the metrics `Brave.Today.ChannelCount.2`
6. Confirmed that the metrics response value is `4` as expected as two channels are shown under channels

Example | Example
----------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/6baa209e-7c13-42ac-91f0-d054799be828) | ![image](https://github.com/brave/brave-browser/assets/38657976/e7970cb6-7e1a-4abe-9d43-e30994a422a7)


</details>

<details>
<summary>Brave.Today.ChannelCount.2 =5_PASSED</summary>

1. Clean profile 1.67.x
2. Enable brave news via NTP
3. Click on `+` icon next to Channels and add 14+ channels by clicking on + icon on channels
4. Open brave://local-state file
5. Look for the metrics `Brave.Today.ChannelCount.2`
6. Confirmed that the metrics response value is `5` as expected as two channels are shown under channels

Example | Example
----------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/021ba048-37d7-4070-8ce8-6758e054917f) | ![image](https://github.com/brave/brave-browser/assets/38657976/a9ce2224-f090-461e-b519-0e437157de3c)


</details>

### Brave.Today.PublisherCount.2

<details>
<summary>Brave.Today.PublisherCount.2 = 0_PASSED</summary>

1. Clean profile 1.67.x
2. Enable brave news via NTP
3. Open brave://local-state file
4. Look for the metrics `Brave.Today.PublisherCount.2`
5. Confirmed that the metrics response value is `0` as expected
![image](https://github.com/brave/brave-browser/assets/38657976/4597f71e-ba25-4009-8528-def35a0e29a8)

</details>

<details>
<summary>Brave.Today.PublisherCount.2 = 1_PASSED</summary>

1. Clean profile 1.67.x
2. Enable brave news via NTP
3. Click on `+` icon on Publishers and add a publisher by clicking on + icon on publisher
4. Open brave://local-state file
5. Look for the metrics `Brave.Today.PublisherCount.2`
6. Confirmed that the metrics response value is `1` as expected

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/5b56e582-21e1-40f0-ac53-abd7dec4b79c) | ![image](https://github.com/brave/brave-browser/assets/38657976/aa49c94e-daf7-471f-885e-7170228bde6d)


</details>

<details>
<summary>Brave.Today.PublisherCount.2 = 2_PASSED</summary>

1. Clean profile 1.67.x
2. Enable brave news via NTP
3. Click on `+` icon on Publishers and add 2 publishers by clicking on + icon on publishers
4. Open brave://local-state file
5. Look for the metrics `Brave.Today.PublisherCount.2`
6. Confirmed that the metrics response value is `2` as expected

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/6f1395d5-31c9-4e9b-a0a8-8ad175185dd0) | ![image](https://github.com/brave/brave-browser/assets/38657976/0dd1efbb-2205-434f-8845-3a0a99483eba)


</details>

<details>
<summary>Brave.Today.PublisherCount.2 = 3_PASSED</summary>

1. Clean profile 1.67.x
2. Enable brave news via NTP
3. Click on `+` icon on Publishers and add 5 publishers by clicking on + icon on publishers
4. Open brave://local-state file
5. Look for the metrics `Brave.Today.PublisherCount.2`
6. Confirmed that the metrics response value is `3` as expected

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/1cbe92bb-65fa-42e8-8dbd-afd5735861b1) | ![image](https://github.com/brave/brave-browser/assets/38657976/cafdd83b-626d-4e2d-a1d7-69d01d5b420a)


</details>

<details>
<summary>Brave.Today.PublisherCount.2 = 4_PASSED</summary>

1. Clean profile 1.67.x
2. Enable brave news via NTP
3. Click on `+` icon on Publishers and add 9 publishers by clicking on + icon on publishers
4. Open brave://local-state file
5. Look for the metrics `Brave.Today.PublisherCount.2`
6. Confirmed that the metrics response value is `4` as expected

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/bf66087b-20ff-4340-bd15-19d9b03a552b) | ![image](https://github.com/brave/brave-browser/assets/38657976/28003982-eb60-4501-a533-015eab0135fa)


</details>

<details>
<summary>Brave.Today.PublisherCount.2 = 5_PASSED</summary>

1. Clean profile 1.67.x
2. Enable brave news via NTP
3. Click on `+` icon on Publishers and add 14+ publishers by clicking on + icon on publishers
4. Open brave://local-state file
5. Look for the metrics `Brave.Today.PublisherCount.2`
6. Confirmed that the metrics response value is `5` as expected

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/d8de1dfd-99bc-48a1-8ca5-a4a26c12f808) | ![image](https://github.com/brave/brave-browser/assets/38657976/f1d01f45-ab88-4932-bbde-68a5e53235bb)

</details>
