### ISSUE TITLE
Make it possible to sign components with two publisher keys

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#37853]
Brave verifies the integrity of components by checking them against a _publisher key_ that is hard-coded into the browser executable. In #37461, we want to rotate the publisher key. The present issue is a preparation for this. We currently sign components by calling Brave on the command line with the `--brave-extension-publisher-key` argument. The goal of this present issue is to add another command-line argument that makes it possible to supply a second publisher key. We can then use this argument during a transition period to sign components with both the old and the new publisher key. Then, later, we will switch the browser to only accepting components signed with the new key.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.67.86 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | a1f8e8f462d422d4b924fa9c34246f68862b21ad
OS | Windows 11 Version 23H2 (Build 22631.3593)
```

1. Installed 1.67.86
2. launched Brave

Extensions: 

- imported extensions from Chrome Person 1 via onboarding 
- imported extensions via `brave://settings/importData` from Microsoft Edge
- Confirmed Extensions were successfully imported 

Chrome | Edge 
------ | -----
![image](https://github.com/brave/brave-browser/assets/98358127/7f44f263-4ff5-45c1-b6ff-59cc62b3a87d)|![image](https://github.com/brave/brave-browser/assets/98358127/a8748190-1364-4efd-9200-09e12052065b)
![image](https://github.com/brave/brave-browser/assets/98358127/135e71c8-3255-4402-a62c-2e4e773f7254)|![image](https://github.com/brave/brave-browser/assets/98358127/3bf94e98-fa52-4076-92f8-499e44387f3f)


Components:

- Removed following component folders in the User Data folder 
- Restarted Brave
- Opened brave://components in a new tab
- Confirmed that they're being re-downloaded after restarting the browser:
      - `afalakplffnnnlkncjhbmahjfjhmlkal` - `Brave local data adapter` 
      - `CertificationRevocation` -   `CRL Set` 
      - `iodkpdagapdfkphljnddpjlldadblomo` - `Brave Adblock Updater` 
      - `mfddibmblmbccpadfndgakiopmmhebop` - `Brave Ad Block Resources Library` 

Confirmed components re-downloaded successfully

example | example | example | example 
----- | ------ | ----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/9fba9453-0ff7-4a0a-be0d-451bb9b967bd)|![image](https://github.com/brave/brave-browser/assets/98358127/7154f92b-9d1b-4d32-a22e-01810c5abd27)|![image](https://github.com/brave/brave-browser/assets/98358127/a89fc5f0-8ec6-4b7c-97a0-1fb03463a625)|![image](https://github.com/brave/brave-browser/assets/98358127/8e53b667-63cc-444c-9490-15aed394cd3c)

**Comment by LaurenWags** [comment]
Changed from `release-notes/include` to `release-notes/exclude` per discussion with @rebron 👍🏻
