### ISSUE TITLE
After browser restart tipped BAT disappeared from Rewards Summary section

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3785]
## Description 

After browser restart tipped BAT disappeared from Rewards Summary section

## Steps to Reproduce

   1. Clean profile 0.63.14
   2. Enable rewards and restore wallet
   3. Open a verified pub and tip it
   4. Restart browser

*`Note`*: Auto contribution summary is also getting cleared after the browser restart.

## Actual result:

After browser restart tipped BAT disappeared from Rewards Summary section

## Expected result:
Tipped BAT shouldn't get removed from summary section after browser restart

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

### Reproducible on current release: No
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by LaurenWags** [comment]
Reproduced on macOS 

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

**Comment by btlechowski** [comment]
Reproduced on Ubuntu

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Ubuntu 18.04 LTS

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya can you please try this on the latest nightly

**Comment by GeetaSarvadnya** [comment]
Looks like the issue is fixed. Unable to reproduce, tested on below versions:

`0.63.48` - Not reproducible
`0.66.24` - Not reproducible
`0.64.69` -  Not reproducible
