### ISSUE TITLE
Insufficient funds text not fixed on Linux (Follow up to #3286)

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3786]
## Description 

Insufficient funds text not fixed on Linux (Follow up to #3286)

## Steps to Reproduce

   1. Enable rewards
   2. Relaunch brave with `--rewards=reconcile-interval=5`
   3. Still shows payments instead of rewards

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/54633637-f8017a00-4a56-11e9-8e0f-680afc95f5dc.png)

## Expected result:
Should say rewards instead of payments

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.62.32 Chromium: 73.0.3683.75 (Official Build) beta(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Setting same priority as #3286

**Comment by kjozwiak** [comment]
Reproduced using the STR @srirambv mentioned above using the following build:

Brave | 0.62.32 Chromium: 73.0.3683.75 (Official Build) beta (64-bit)
--- | ---
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

Example of the issue occurring:

<img width="641" alt="Screen Shot 2019-03-19 at 3 23 20 PM" src="https://user-images.githubusercontent.com/2602313/54636344-a52ac100-4a5c-11e9-828c-689fe04be3be.png">

Used the following platforms:

* Mint 19.1 Tessa x64 - Reproduced
* Ubuntu 18.04.2 Bionic LTS x64 - Reproduced

**Comment by NejcZdovc** [comment]
closing as stale
