### ISSUE TITLE
Brave starts with Ozone platform X11 instead of Wayland even after specifying it to do so

### ISSUE THREAD

**Issue by SmollClover** [brave/brave-browser#37860]
## Steps to Reproduce

   1. Install Brave version 1.65.122 Chromium: 124.0.6367.82 (Official Build) (64-bit) on Linux with Wayland as the compositor
   2. Set flag `#ozone-platform-hint` to `Auto` or `Wayland`
   3. Start Brave as normal

## Actual result:

Brave will start with Ozone platform X11 regardless.
![image](https://github.com/brave/brave-browser/assets/39840298/f62a946d-3e65-4447-9c2c-3a1fe9e550a7)
![image](https://github.com/brave/brave-browser/assets/39840298/9344a3fb-f611-42c1-919e-990f514739a1)

## Expected result:

Brave should start with Ozone platform Wayland as was the case with previous versions.

## Reproduces how often: 

Very easy to reproduce when using the mentioned version on a Wayland system.

## Brave version (brave://version info)

```
Brave		1.65.122 Chromium: 124.0.6367.82 (Official Build) (64-bit) 
Revision	64099bd820a06a2843326660372e895b7d78f20b
OS		Linux
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
  - Yes
- Can you reproduce this issue with the beta channel? 
  - Uncertain
- Can you reproduce this issue with the nightly channel? 
  - Uncertain

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
  - No
- Does the issue resolve itself when disabling Brave Rewards? 
  - No 
- Is the issue reproducible on the latest version of Chrome? 
  - No (tried `Chromium 123.0.6312.86 (Official Build) Fedora Project (64-bit)`)

## Miscellaneous Information:

Selection of the Ozone platform had worked prior to the fix from https://github.com/brave/brave-browser/issues/37498

**Comment by rillian** [comment]
I can reproduce with 1.67.37 nightly (fedora 40 gnome-desktop). Passing `--ozone-platform=wayland` on the command line does result in brave://gpu reporting wayland, along with blurry scaling.

Follow-up to https://github.com/brave/brave-core/pull/23166

**Comment by why-not-try-calmer** [comment]
I can reproduce on `1.65.122 Chromium: 124.0.6367.82`(nixos-unstable).

**Comment by sojusnik** [comment]
Still happens with Version 1.65.123 (Chromium: 124.0.6367.91).

**Comment by cyangalaxy** [comment]
> I can reproduce with 1.67.37 nightly (fedora 40 gnome-desktop). Passing `--ozone-platform=wayland` on the command line does result in brave://gpu reporting wayland, along with blurry scaling.
> 
> Follow-up to [brave/brave-core#23166](https://github.com/brave/brave-core/pull/23166)

You can fix the blurryness with Ozone Wayland by also adding this flag: --disable-features=WaylandFractionalScaleV1

**Comment by qdrop17** [comment]
I can confirm the issue you mentioned. To launch Brave, I have to use the command `brave-browser --ozone-platform=wayland > /dev/null 2>&1 &` due to the problem reported in https://github.com/brave/brave-browser/issues/37954. It would be great if Brave could start directly with Wayland when the flag is set, as this workaround is inconvenient. This issue might be related to some dependencies with the profile manager, although I'm not entirely sure.

**Comment by SmollClover** [comment]
As of `1.65.126 Chromium: 124.0.6367.118 (Official Build) (64-bit)` the issue seems to be fixed?  
Launching Brave with `#ozone-platform-hint` set to `Auto` while also providing no additional command-line argument has set the ozone platform correctly again to be Wayland. 

![image](https://github.com/brave/brave-browser/assets/39840298/dc25adf3-0016-4ca2-b44f-28cda26f3645)

If others can confirm that it's not just on my end and that the new stable version seems to be fixed, then I think this Issue is resolved.

**Comment by urbenlegend** [comment]
Can confirm that ozone-platform-hint works properly now.

**Comment by SmollClover** [comment]
Since the issue seems to be fixed, I'll close this Issue.
