### ISSUE TITLE
Private web store

### ISSUE THREAD

**Issue by AtFreezingPoint** [brave/brave-browser#37865]
Hello there, I've been wondering whether It'd be possible for the Brave team to make their own web store alternative so people wouldn't have to rely solely on the Chrome Web store for stuff, I think that everything Google should just be thrown out from the browser.

**Comment by AtFreezingPoint** [comment]
Anything on this?

**Comment by bsclifton** [comment]
Hi @AtFreezingPoint - we had an issue captured for this here:
https://github.com/brave/brave-browser/issues/15187

I'll close this as a duplicate. But you can read my latest response here:
https://github.com/brave/brave-browser/issues/15187#issuecomment-1965392166
