### ISSUE TITLE
[iOS/Wallet] Unable to add custom network with chainId has single digit

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#37863]
Unable to add/edit custom networks from chainId 1 - 15 (hex 0x1 - 0xf)

**Comment by kjozwiak** [comment]
The above requires `1.66.102` or higher for `1.66.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.5 running 1.66 (105)
- Verified steps from [brave/brave-core#23295](https://github.com/brave/brave-core/pull/23295)
- Verified able to add custom networks 
- Verified able to edit custom networks
- Verified editing a custom network with new chain id adds the new network 

https://github.com/brave/brave-browser/assets/17010094/eb7d128d-b8ac-4ae6-b499-36edc75f5aba
