### ISSUE TITLE
[Android]  Rate brave bottom sheet modal is not fully shown while device is in Landscape mode

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#37870]
## Description 
`Rate brave` bottom sheet modal is not fully shown while the device is in Landscape mode.

## Steps to reproduce 

   1. Launch Brave
   2. Go to settings
   3. Rotate the device (phone or tablet) into Landscape mode
   4. Tap on `Rate Brave` -> Observe

## Actual result 
![Screenshot_2024-04-26-00-34-47-57_82cebf612ef3f9a8762672c971adaed4](https://github.com/brave/brave-browser/assets/5146988/4e779f87-4a4f-4b3a-b377-30fd0287191e)

## Expected result
![Screenshot_2024-04-26-00-35-08-28_82cebf612ef3f9a8762672c971adaed4](https://github.com/brave/brave-browser/assets/5146988/3f9f33e3-4175-443b-8078-c367f7253f72)

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone and Tablet
   - Android version: ANY
   
## Brave version

```
Brave build: 1.66.70
Chromium: 124.0.6367.29 (Official Build) canary (64-bit)
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240426.022 release-keys
Brave build: 1.67.85 
Chromium: 125.0.6422.60 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/37870#issue-2264946977
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Rate Brave` bottom sheet modal is fully shown in `Landscape` and `Portrait` modes
- Verified that the correct behavior is seen when rotating device while bottom sheet modal is opened already

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/25ae1084-6431-47ab-abe9-93374e3e12ca) | ![2](https://github.com/brave/brave-browser/assets/128532965/56f3921e-01e6-4b6c-9405-d0a8397c7082) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/6e11c08c-cb49-419c-88b4-8982d32f7e62) | ![2](https://github.com/brave/brave-browser/assets/128532965/f36738e9-5fd8-4623-a39e-a6b77d680276) |

https://github.com/brave/brave-browser/assets/128532965/49dc6f48-1298-4d12-9cf5-13dab44dafde
