### ISSUE TITLE
Implement onboarding v3

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#37871]
Implement onboarding version 3.
Figma Design [link](https://www.figma.com/file/oXIiv45pIhF2RGlpEjOfUg/Wallet-onboarding?type=design&node-id=5607%3A65825&mode=dev)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.98 Chromium: 125.0.6422.112 (Official Build) beta (64-bit)
-- | --
Revision | 9434daa5e8d2aceabb9cce574ab39429f2923b9b
OS | Windows 11 Version 23H2 (Build 22631.3593)

- Verified steps from [brave/brave-core#22579](https://github.com/brave/brave-core/pull/22579)
- Verified new onboarding works as expected
- Encountered [#38640](https://github.com/brave/brave-browser/issues/38640)

New Wallet | Restore Wallet | Restore Hardware Wallet
-- | -- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/6815d476-2d9c-4fd2-b06b-534393f53751> | <video src=https://github.com/brave/brave-browser/assets/17010094/8dc02c41-6c10-4dc8-b5e3-1989664107af> | <video src=https://github.com/brave/brave-browser/assets/17010094/a2d29701-de7a-453b-9e69-381ca4315360>
