### ISSUE TITLE
Implement Dark Mode Scrollbars on Windows

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#37882]
## Description 

Regardless the theme of the OS, scrollbars on the New Tab Page always show in light-mode.

## Actual result:

Scrollbars are always light.

## Expected result:

Scrollbars should be styled consistently with other parts of Brave (e.g., Leo, Settings).

## Reproduces how often: 

Always.

## Brave version (brave://version info)

1.65.122 Chromium: 124.0.6367.82 (Official Build) (64-bit)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.67.82 Chromium: 125.0.6422.41 (Official Build) beta (64-bit)
-- | --
Revision | cbebefd4c702801af65a196ba9701a907ed0d292
OS | Windows 10 Version 22H2 (Build 19045.4355)
```

### Steps:
1. installed `1.67.82`
2. launched Brave
3. set `Brave colors` to `Dark` and `Light` modes,
4. opened a new-tab page
5. scrolled
6. examined the scrollbars in `Dark` and `Light` modes
7. compared to `1.66.104`

### Confirmed slimmer-styled and `Dark` and `Light`-mode appropriate scrollbars, matching https://github.com/brave/brave-core/pull/23301#issue-2265847378

`Dark` mode | `Light` mode
---------------|--------------
![image](https://github.com/brave/brave-browser/assets/387249/2d00f06a-da3d-4aae-a6e0-0d64bf0a068e) | ![image](https://github.com/brave/brave-browser/assets/387249/2b9e2593-855f-4b3e-b4e8-363876fd96b3)


Scrollbars using `1.66.104 Chromium: 125.0.6422.41`, for comparison:

`Dark` mode | `Light` mode
--------------|---------------
![image](https://github.com/brave/brave-browser/assets/387249/d888ad00-152b-47b6-a11c-4d787724976e) | ![image](https://github.com/brave/brave-browser/assets/387249/6411551a-a620-48d3-bce8-80c20bae208f)
