### ISSUE TITLE
Add `Brave.Core.WeeklyUsage` P3A metric to iOS

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#37886]
See [original PR](https://github.com/brave/brave-core/pull/16249)

See [P3A definition](https://github.com/brave/brave-browser/wiki/P3A#q80-how-many-days-did-you-use-the-browser-in-the-previous-iso-week)

```
Q80. How many days did you use the browser in the previous ISO week?
Brave.Core.WeeklyUsage [D] [A]

0 days
1 day
2 days
3 days
4 days
5 days
6 days
7 days
```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `iPhone 8 version 16.7.8` running `Brave Nightly 1.68(79)`

<details>
<summary>Case 1: Brave.Core.WeeklyUsage = 0_PASSED</summary>

1. Clean profile 1.50.x
2.  Open brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `0`
![image](https://user-images.githubusercontent.com/38657976/224014304-867b7a17-5013-478b-bf48-ba4f71f750e7.png)
3. Close the browser
4. Advance the system date ahead by one day
5. Relaunch the browser
6. Reload brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `0`

![image](https://user-images.githubusercontent.com/38657976/224404879-71b234c6-5418-449a-99db-33286b6e3454.png)


</details>


<details>
<summary>Case 2: Brave.Core.WeeklyUsage = 1_</summary>

1. Clean profile 1.50.x
2. Open brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `0`
3. Close the browser
4. Advance the system date to next week (on the next Monday)
5. Reload brave://local-state fine and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `1` as expected
![image (20)](https://user-images.githubusercontent.com/38657976/224404634-3f32e79a-7427-480a-b141-80025f51b87f.png)

</details>

<details>
<summary>Case 3: Brave.Core.WeeklyUsage = 2_</summary>

1. Clean profile 1.50.x
2. Open brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `0`
3. Close the browser
4. Advance the system date ahead by one day
5. Relaunch the browser, reload brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `0`
6. Close the browser
8. Advance the system date to next week (on the next Monday or any day in next week)
9. Reload brave://local-state fine and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `2` as the browser usage is 2 days in last week

![image (19)](https://user-images.githubusercontent.com/38657976/224404516-6152e0c8-a71f-4606-b797-008d2e3b363d.png)

</details>

<details>
<summary>Case 4 : Brave.Core.WeeklyUsage = 3_</summary>

1. Clean profile 1.50.x
2. Open brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `0`
3. Close the browser
4. Advance the system date ahead by one day (day should not be monday)
5. Relaunch the browser, reload brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `0`
6. Close the browser
7. Advance the system date ahead by one day (day should not be monday)
8. Relaunch the browser, reload brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `0`
10. Close the browser
11. Advance the system date to next week (on the next Monday or any day in next week)
12. Reload brave://local-state fine and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `3` as the browser usage is 3 days in last week

![image (18)](https://user-images.githubusercontent.com/38657976/224404295-4045ecf4-dee2-4d5f-a48c-3f214d0562ae.png)

</details>


<details>
<summary>Case 5: Brave.Core.WeeklyUsage = 4_</summary>

1. Clean profile 1.50.x
2. Open brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `0`
3. Close the browser
4. Advance the system date ahead by one day (day should not be monday)
5. Relaunch the browser, reload brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `0`
6. Close the browser
7. Repeat the steps 4 to 6 for 2 times
8. Close the browser
9. Advance the system date to next week (on the next Monday or any day in next week)
10. Reload brave://local-state fine and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `4` as the browser usage is 4 days in last week

![image (17)](https://user-images.githubusercontent.com/38657976/224404269-0cce78ce-1441-4e99-80f9-0a68e4cb3b7c.png)

</details>

<details>
<summary>Case 6: Brave.Core.WeeklyUsage = 5_</summary>

1. Clean profile 1.50.x
2. Open brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `0`
3. Close the browser
4. Advance the system date ahead by one day (day should not be monday)
5. Relaunch the browser, reload brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `0`
6. Close the browser
7. Repeat the steps 4 to 6 for 3 times
8. Close the browser
9. Advance the system date to next week (on the next Monday or any day in next week)
10. Reload brave://local-state fine and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `5` as the browser usage is 5 days in last week

![image (16)](https://user-images.githubusercontent.com/38657976/224404233-042e91e7-3ee0-40f6-b66f-ec0c3f7fcb0b.png)

</details>

<details>
<summary>Case 7: Brave.Core.WeeklyUsage = 6_</summary>

1. Clean profile 1.50.x
2. Open brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `0`
3. Close the browser
4. Advance the system date ahead by one day (day should not be monday)
5. Relaunch the browser, reload brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `0`
6. Close the browser
7. Repeat the steps 4 to 6 for 4 times
8. Close the browser
9. Advance the system date to next week (on the next Monday or any day in next week)
10. Reload brave://local-state fine and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `6` as the browser usage is 6 days in last week

![image (15)](https://user-images.githubusercontent.com/38657976/224404207-8af7b95a-af41-46ab-b98c-d71dea61f295.png)

</details>

<details>
<summary>Case 8: Brave.Core.WeeklyUsage = 7_PASSED</summary>

1. Clean profile 1.50.x
2. Open brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `0`
3. Close the browser
4. Advance the system date ahead by one day (day should not be monday)
5. Relaunch the browser, reload brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `0`
6. Close the browser
7. Repeat the steps 4 to 6 for 5 times
8. Close the browser
9. Advance the system date to next week (on the next Monday or any day in next week)
10. Reload brave://local-state fine and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `7` as the browser usage is 7 days in last week

![image (14)](https://user-images.githubusercontent.com/38657976/224404142-3389dc79-b32c-4dd6-b692-ef65c7cc83aa.png)

</details>

### Additional scenario

<details>
<summary>Additional scenario_</summary>

1. Launch brave 1.50.x 
2. Open brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `0`
3. Close the browser
4. Set the sys date ahead by one day (11th March in my case) repeat the steps 1 to 3
5. Set the sys date ahead by one day (12th March in my case) repeat the steps 1 to 3
6. Set the sys date ahead to next monday(13th March (Monday) in my case)
7. Launch the browser, open brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `3` as the browser usage is 3 times in previous week
8. Close the browser
9. Set the sys date to 18th March (saturday), launch brave and close the browser , set sys date to 20th March (monday) and open brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `2` as the browser usage is 
11. Set the sys date to 27th March (monday)
13. Relaunch brave and open brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `1` as the browser usage is 1 day in previous week (18th March)
14. Close the browser
15. Set the sys date ahead by one week (i.e 3rd April (monday) in my case)
16. Relaunch brave and open brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `1` as the browser usage is 1 day in previous week (27th March)
17. Close the browser
18. Set the sys date ahead by two weeks (i.e 17th April (monday) in my case)
19. Relaunch brave and open brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `0` as the browser usage is 0 day in previous week 
20. Set the sys date ahead by one week (i.e 24th April (monday) in my case)
21. Relaunch brave and open brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `1` as the browser usage is 1 day in previous week (17th April)
22. Set the sys date ahead by three weeks (i.e 15th May (monday) in my case)
23. Relaunch brave and open brave://local-state file and ensure that the metrics `Brave.Core.WeeklyUsage` response value is `0` as the browser usage is 0 day in previous week 

</details>
