### ISSUE TITLE
[ads] Ugly gradient on NTT video ad in Landscape mode

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#37894]
Follow up to https://github.com/brave/brave-browser/issues/37653

## Steps to Reproduce 

1. Fresh install
1. Turn off WiFi and mobile network
1. Launch browser
1. Toggle `Use Staging CRX components` in `Settings -> BraveCore Switches`
1. Set rewards to staging
1. Close the browser
1. Turn on WiFi or mobile network
1. Launch Brave browser
1. Launch browser in Portrait orientation
1. Open New Tab Pages until a tab with New Tab Takeover video ad is opened
1. Wait till video stops playing
1. Rotate the phone to Landscape mode

## Actual result: 

Ugly gradient on NTT video ad in Landscape mode
Looks like we forgot to load a proper background image.

![image](https://github.com/brave/brave-browser/assets/34715963/ce41038e-6a76-4494-a9e6-350b9239057d)

## Expected result:
No ugly gradient on NTT video ad in Landscape mode

In landscape consider using the ad video keyframe and locking it to portrait (the keyframe image remains as in Portrait - it is not rotated)
So when user rotates the phone to portrait, the keyframe is already in portrait.

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

## Brave Version: 

1.67.44 on iphone 13 pro max

cc @tmancey @aseren

**Comment by tmancey** [comment]
Closing as agreed we will not fix because if an RGB color is not specified in the filename the default is black #000000.
