### ISSUE TITLE
[ads] Sometimes Play and Pause button are not responsive on NTT fullscreen video ad

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#37893]
Follow up to https://github.com/brave/brave-browser/issues/37653

Noticed that sometimes taping on `Play` or `Pause` button yielded no response.
The easiest way to reproduce is with the steps below

## Steps to Reproduce 

1. Fresh install
1. Turn off WiFi and mobile network
1. Launch browser
1. Toggle `Use Staging CRX components` in `Settings -> BraveCore Switches`
1. Set rewards to staging
1. Close the browser
1. Turn on WiFi or mobile network
1. Launch Brave browser
1. Launch browser in Portrait orientation
1. Open New Tab Pages until a tab with New Tab Takeover video ad is opened
1. Wait till video stops playing
1. Play the video in fullscreen
1. Rapidly tap Play/Pause buttons

Note: issue not reproducible when taping on the video

## Actual result: 
Play and Pause button are not responsive

## Expected result:
Play and Pause button are responsive, just like tapping next to the buttons

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

## Brave Version: 

1.67.44 on iphone 13 pro max

cc @tmancey @aseren

**Comment by kjozwiak** [comment]
The above requires `1.66.103` or higher for `1.66.x` verification 👍

**Comment by Uni-verse** [comment]
In progress on iPhone 12 running iOS 17.3.1 using version 1.66.104
