### ISSUE TITLE
logged in sites will be logged out while session remembered

### ISSUE THREAD

**Issue by edmundlaugasson** [brave/brave-browser#379]
## Description 
When to log in some sites, after browser closing or crashing, these sites are logged out even the setting "My tabs/windows from last time" has been set at "When Brave starts" in Settings. Also Bitwarden or any other credentials manager is logged out again... To be honest - it's quite boring to enter all the time credentials, use 2FA - this is an issue that prevents using Brave. Especially while trying to pin a tab will crash the Brave (#378 ). Such additional time for entering credentials will eliminate the time I saved using Brave, which is one of the key arguments to use Brave.

## Steps to Reproduce
   1. open Settings and set at "When Brave starts" value as "My tabs/windows from last time"
   2. open some sites where you can log in, e.g. Google Drive, Facebook etc
   3. close Brave either a nice way or using force, when reopening - sites are logged out

 ## Actual result:
logged in sites are logged out

## Expected result:
logged in sites are still logged in

## Reproduces how often: 
every time

## Brave version (about:brave info)
Name | Version
Brave | 0.22.810
V8 | 6.7.288.43
rev | 8f30eeb
Muon | 7.0.6
OS Release | 4.15.18-041518-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.71

### Reproducible on current release:
yes

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/browser-laptop/issues/14444
