### ISSUE TITLE
Long domain names should fit in along with site icon in the new shields panel 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3791]
## Description 

Long domain names should fit in along with site icon in the new shields panel 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/54636830-a14b6e80-4a5d-11e9-8f68-f606af9a4135.png)

![image](https://user-images.githubusercontent.com/17010094/54636660-4b76c680-4a5d-11e9-9860-6da2aca1caf8.png)

## Expected result:
Should probably wrap the url or have a line break

## Reproduces how often: 

Easy 

## Brave version (brave://version info)

Brave | 0.64.5 Chromium: 73.0.3683.75 (Official Build) nightly(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @karenkliu @cezaraugusto

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

Used STR from the description

![image](https://user-images.githubusercontent.com/34715963/56710309-c64e9380-6725-11e9-8c26-49883cd8d622.png)
![image](https://user-images.githubusercontent.com/34715963/56710336-e5e5bc00-6725-11e9-8b80-058ce7ff331a.png)
