### ISSUE TITLE
New tab Favorites are not centered on the screen

### ISSUE THREAD

**Issue by ipaduser2000** [brave/brave-browser#37910]
## Description: When you open a new tab, the Favorites are not centered. Yet, when you click “Show More”, the Favorites move the center of the page. It is visually confusing to the user when the Favorites jump from the upper left to the center of the screen, especially when your cursor or hand is already in a particular area. 

Also, not sure why there is a 6 favorite icon limitation anyways (i.e. only 6 Favorites show before you have to click “Show More”)… but that is another issue…

## Steps to Reproduce 
  1. Open a new tab, select “Show More”.
  2.
  3.

### Device details: iPadOS 17.14.1; M2 iPad Pro 12. 

![IMG_0154](https://github.com/brave/brave-browser/assets/167967411/0463cea6-6d03-41e9-b2e3-e6941ea77d11)

**Comment by soner-yuksel** [comment]
Both of concerns here are Design choices made on purpose. Closing this as it is not actionable. 

cc @iccub
