### ISSUE TITLE
Creating a new Tor window using the purple Tor pill button in the URL bar fails to show tor daemon status

### ISSUE THREAD

**Issue by urbenlegend** [brave/brave-browser#37927]
## Description 
When clicking on the purple Tor button in the URL bar to navigate to the Tor version of a specific site, the page never seems to start loading. It's like the Tor session never connects. No progress spinner is displayed on the Tor tab. Only after opening a new blank tab in the Tor window and then going back to the previous tab and refreshing will the Tor page load.

NOTE: This does not happen if there is already an open Tor window. This bug only triggers when no previous Tor session exists.

## Steps to Reproduce

   1. Make sure all Tor windows are closed
   2. Go to nytimes.com
   3. Click the Tor button in the URL bar
   4. Notice that a new Tor window pops up, but nothing loads. The title of the page remains "New Private Tab".
   5. Open a new blank tab in the same Tor window. Make sure it says Tor is connected.
   6. Go back to previous tab and refresh. Page will now load.

## Actual result:

If a user clicks on the purple Tor button and no previous Tor session exists, Tor page refuses to load

## Expected result:
Purple Tor button should reliably open the tor page, even if it has to create a new Tor session to do so.

## Reproduces how often: 

Every time

## Brave version (brave://version info)

1.65.123 Chromium: 124.0.6367.91 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by rebron** [comment]
cc: @fmarier @MadhaviSeelam

**Comment by fmarier** [comment]
For me, it does eventually load, but there is no feedback at all during the bootstrapping phase (which can take a long time).

Tested with brave.com and then clicking on the purple Tor button in the URL bar

**Comment by MadhaviSeelam** [comment]
Verified with both brave.com & nytimes.com on 1.65.126 on Win 11. Noticed as below: 

- Tor window is blank after clicking Tor button
- brave.com loaded consistently between 40 sec - 60 sec.  (tested 2x)
- nytimes.com either loads successfully or fails after ~60 secs. (tested ~4x)

brave.com

https://github.com/brave/brave-browser/assets/98358127/5936b7de-e661-4087-b25a-6a88fcf4d401

nytimes.com

https://github.com/brave/brave-browser/assets/98358127/609bc859-7197-42c3-90b7-11fc14723fc5

**Comment by urbenlegend** [comment]
As of Brave version 1.65.126 Chromium: 124.0.6367.118 (Official Build) (64-bit), it does seem to eventually load. Maybe the failed load I experienced before and what MadhaviSeelam experienced was just typical Tor slowness?

I did a timing test for nytimes.com and they seem to line up okay:

1. **Clicking purple Tor button without a pre-existing Tor window:** 53 sec
2. **Opening Tor window, waiting for connect, and then clicking purple Tor button**: 50 sec

But yeah, I think there does need to be some loading feedback. Maybe the Tor private browsing intro page should be shown first and then once it connects transition over to loading the destination page?

**Comment by fmarier** [comment]
> I think there does need to be some loading feedback.

Agreed. I've retitled the issue to that effect.

**Comment by boocmp** [comment]
I posted a video in the PR, could you please take a look? Does it work as you expect, or does it need to be adjusted?

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.68.85 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | 8e76a669cf78bdfa933c8d569460092a01166588
OS | Windows 10 Version 22H2 (Build 19045.4474)
```
