### ISSUE TITLE
Console errors when trying to pin NFTs

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#37932]
## Description 

Console errors when trying to pin NFTs

## Steps to Reproduce

   1. Add NFTs to wallet
   2. Pin NFTs
   3. Console throws error
   4. NFTs not shown if listed via account when NFT pinning is enabled

## Actual result:

![image](https://github.com/brave/brave-browser/assets/17010094/51a9986d-5656-4386-9a5f-9c5106b6077a)

## Expected result:
No console errors and show pinned NFTs when filtered by Account

## Reproduces how often: 

Easy

## Desktop Brave version:

Brave | 1.66.90 Chromium: 124.0.6367.82 (Official Build) beta (64-bit)
-- | --
Revision | 803a4c629341791205b744969c48b8da9f2cfa4d
OS | Windows 11 Version 23H2 (Build 22631.3527)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not sure
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam

**Comment by diracdeltas** [comment]
Please do not change the content-security-policy without checking in with security team.

**Comment by Douglashdaniel** [comment]
Closing this out since we will be removing this feature.
