### ISSUE TITLE
Right click>”Search Web” button utilizes Google, not Brave Search

### ISSUE THREAD

**Issue by ipaduser2000** [brave/brave-browser#37937]
Description: Even with Brave Search as the default search engine, when you right click on a word or phrase and click “Search Web”, it goes to Google Search, not Brave Search. This is a pretty strange finding. 

## Steps to Reproduce 
  1. Right click on anything, click “Search Web”
  2.
  3.

### Device details: M2 iPad Pro 12.9, iPadOS 17.4.1

![IMG_0175](https://github.com/brave/brave-browser/assets/167967411/2bab59ca-ef17-48c1-93d0-b50cbd4cb583)

**Comment by soner-yuksel** [comment]
This is a OS default action and we cant change the designated behaviour for this. For this particular purpose we added 
"Search with Brave" custom action, please use this action.
