### ISSUE TITLE
Download toolbar not getting notified of color theme change Follow up to  #3708

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3793]
## Description 

Download toolbar not getting notified of color theme change follow up to  #3708

## Steps to Reproduce

   1. Download a file
   2. Change brave colour to light/dark, toolbar doesn't update
   3. Change to classic, dark/light colour shows correct toolbar
   4. Change to GTK+, same white bar for both dark/light colour

## Actual result:

![toolbar](https://user-images.githubusercontent.com/17010094/54641617-fb056600-4a68-11e9-9d67-e732048c6103.gif)

## Expected result:
Should not change GTK+ to Classic for correct theme to be used. Should be dependent on Brave colours

## Reproduces how often: 

Easy 

## Brave version (brave://version info)

Brave | 0.62.32 Chromium: 73.0.3683.75 (Official Build) beta(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Same on all channels
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @petemill

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/browser-colors-cant-read-filenames-of-downloaded-files-when-in-dark-mode/57363?u=eljuno

Reproduced on Windows 10 with Brave 0.63.x.

> My Windows color scheme is dark, but I set my browser to light.

**Comment by simonhong** [comment]
Duplicated this with https://github.com/brave/brave-browser/issues/965

**Comment by simonhong** [comment]
> Reproduced on Windows 10 with Brave 0.63.x.

@eljuno We have https://github.com/brave/brave-browser/issues/4272 for Windows

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.117 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Ubuntu 18.04 LTS

Verified STR from the description.

![image](https://user-images.githubusercontent.com/34715963/63815285-5569f300-c934-11e9-84f9-50089cd87e03.png)
![image](https://user-images.githubusercontent.com/34715963/63815289-5a2ea700-c934-11e9-8797-3b63d73b5317.png)
![image](https://user-images.githubusercontent.com/34715963/63815317-70d4fe00-c934-11e9-8cde-7216fddd2960.png)
![image](https://user-images.githubusercontent.com/34715963/63815337-89451880-c934-11e9-9b3e-e78d40b8349b.png)
