### ISSUE TITLE
Searching on omnibar doesn't show search engines favicons

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#37948]
## Description 

If I use DDG as my search engine, on the input area I can see their favicon. If I use any other (even Brave) I don't get a favicon at all.

In Chrome canary there's something similar going on. Some have favicons, some don't, like Yandex for example.
I think we should always show the favicon on the top area.

## Actual result:

![image](https://github.com/brave/brave-browser/assets/15734630/eda7add6-4bf1-488a-b14c-49bd2408a275)

## Expected result:
All favicons, like in Chrome

**Comment by rebron** [comment]
Closing as stale/wfm. Favicons will appear after visiting the site first. 
![Image](https://github.com/user-attachments/assets/48d9da14-2903-48b7-b7ed-ee92a814ccf5)
![Image](https://github.com/user-attachments/assets/c54a7d61-0a60-4a08-821a-3c6296b23f42)
