### ISSUE TITLE
Favicons are not displaying in the rewards panel

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#37941]
## Description 

Favicons in the rewards panel no longer display as expected.

## Steps to Reproduce

   1. Enable rewards, connect a custodian
   2. Navigate to a site (can be verified or not verified, doesn't matter)
   3. Open panel

## Actual result:

Favicons don't display as expected. 

Example | Example
--- | ---
<img width="412" alt="Screenshot 2024-04-29 at 1 05 52 PM" src="https://github.com/brave/brave-browser/assets/28145373/bf49ea1b-c89c-446c-b25b-6d7824ed7252"> | <img width="421" alt="Screenshot 2024-04-29 at 1 07 10 PM" src="https://github.com/brave/brave-browser/assets/28145373/a5175a1d-b44d-4b86-bfc1-2cc6322408a8">

## Expected result:

Favicons should show in the panel

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.65.x, 1.67.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.65.x yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 1.67.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes

**Comment by zenparsing** [comment]
It also looks like we're not correctly loading favicons on the Rewards page and images on the tip panel.

**Comment by LaurenWags** [comment]
@zenparsing I can repro the issue with the panel (background image and custom icon are not displayed), but my brave://rewards page seems to be showing the icons as expected:

Tip banner | brave://rewards
--- | ---
<img width="1183" alt="Screenshot 2024-04-30 at 7 36 59 AM" src="https://github.com/brave/brave-browser/assets/28145373/4f9092f0-15a8-48da-8973-88849ea03338"> | <img width="282" alt="Screenshot 2024-04-30 at 7 37 09 AM" src="https://github.com/brave/brave-browser/assets/28145373/7d65f7d4-1130-4374-8dd6-fa9b5bbab31c">

```
Brave | 1.65.123 Chromium: 124.0.6367.91 (Official Build) (x86_64)
-- | --
Revision | dd88871b12997b018e3acb2f589713a3ea10338b
OS | macOS Version 13.6.6 (Build 22G630)
```

**Comment by kjozwiak** [comment]
The above requires `1.65.126` or higher for `1.65.x` verification(s) 👍

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.65.126 Chromium: 124.0.6367.118 (Official Build) (x86_64)
-- | --
Revision | e6a0dcfed2e939addb42f91900875679412fa5b7
OS | macOS Version 13.6.6 (Build 22G630)
```

Reproduced the issue using `1.65.123`. Favicons were not displayed on the rewards panel, images were not displayed in the tip banner. As with https://github.com/brave/brave-browser/issues/37941#issuecomment-2085070554, images were still displaying on brave://rewards for me:

Unverified Creator | Verified Creator | Tip Banner | brave://rewards
--- | --- | --- | ---
<img width="445" alt="Screenshot 2024-05-01 at 8 51 03 AM" src="https://github.com/brave/brave-browser/assets/28145373/4898058c-6a22-4967-a857-a4dd714baca7"> | <img width="438" alt="Screenshot 2024-05-01 at 8 51 21 AM" src="https://github.com/brave/brave-browser/assets/28145373/cb47fbf3-c13c-4f9a-aead-be357c443773"> | <img width="1186" alt="Screenshot 2024-05-01 at 8 51 30 AM" src="https://github.com/brave/brave-browser/assets/28145373/24cfda37-e897-4e46-b724-3816f15e0df0"> | <img width="645" alt="Screenshot 2024-05-01 at 8 52 55 AM" src="https://github.com/brave/brave-browser/assets/28145373/16bbf2ca-f503-43ce-8318-f4b002721db0">

Upgraded the profile to `1.65.126` and confirmed favicons were now displayed on the rewards panel and images were displayed on the tip banner. Also confirmed I could still see favicons on brave://rewards:

Unverified Creator | Verified Creator | Tip Banner | brave://rewards
--- | --- | --- | ---
<img width="453" alt="Screenshot 2024-05-01 at 8 53 35 AM" src="https://github.com/brave/brave-browser/assets/28145373/01d01db3-d5d6-427a-bfb7-29f62ac2bf5c"> | <img width="439" alt="Screenshot 2024-05-01 at 8 53 47 AM" src="https://github.com/brave/brave-browser/assets/28145373/c5510985-b74b-4a43-a9ff-f929de6584b6"> | <img width="1194" alt="Screenshot 2024-05-01 at 8 53 57 AM" src="https://github.com/brave/brave-browser/assets/28145373/493039b5-355c-4649-be02-e354cd39219f"> | <img width="659" alt="Screenshot 2024-05-01 at 8 54 15 AM" src="https://github.com/brave/brave-browser/assets/28145373/45e6aaba-9036-4277-aa5e-29a86591d835">
