### ISSUE TITLE
Country code not correct for iOS P3A

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#37949]
On other systems, the country code is inferred via the system timezone setting. This doesn't seem to work well on iOS, as it could result the wrong country being reported. The country code will be inferred via the system locale setting for iOS P3A.

**Comment by kjozwiak** [comment]
Moving the above into `1.66.x` as we're most likely not going to be doing a `1.65.x` maintenance release for `iOS`. The above fix will go out via `1.66.x`. If for some reason we need a HF on `iOS` via `1.65.x`, the above will get included. If that happens, we'll move the issue back into the `1.65.x` milestone.
