### ISSUE TITLE
Closing Swap Routes Back to Previous Selected Token

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#37943]
## Description 

While on the `Swap` screen in the Wallet `Panel`, clicking the close button will route back to previous selected tokens.

## Steps to Reproduce

   1. Open the `Panel` and navigate to the `Swap` screen
   2. Select a token to swap, then reselect a different token
   3. Click the `Close` button
   4. It will route back to the `Previous` selected token

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/1ba5aa64-6ce5-44be-a0c3-dee2bbeaa6ba

## Expected result:
It should route back to the `Previous` path, not previous selected tokens.

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.66.101` or higher for `1.66.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.101 Chromium: 124.0.6367.118 (Official Build) beta (64-bit)
-- | --
Revision | 62fb0f940cad0714f585e2f01d2f968d64592d25
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#23327](https://github.com/brave/brave-core/pull/23327)
- Verified selecting multiple tokens and closing the modal routes back to Swap screen

https://github.com/brave/brave-browser/assets/17010094/b71d91ab-b252-4f5b-a1f5-0d458763639b
