### ISSUE TITLE
Update Brave wordmark on NTP Private Window and Tor

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#37946]
## Description 

Current wordmark for Brave and Brave Search has been updated. See expected result. 
Word mark on Private Window and Private window with Tor should match.

## Actual result:

<img width="716" alt="Screenshot 2024-04-29 at 10 26 00 AM" src="https://github.com/brave/brave-browser/assets/5951041/29d0ed06-3b43-4762-a4e8-12af934a42dd">
<img width="749" alt="Screenshot 2024-04-29 at 10 26 10 AM" src="https://github.com/brave/brave-browser/assets/5951041/0ccf311a-0627-41ac-baa5-6c6f269af120">

## Expected result:
<img width="777" alt="Screenshot 2024-04-29 at 10 07 29 AM" src="https://github.com/brave/brave-browser/assets/5951041/612e449c-d7c0-4e34-9bc8-ade94edf1df2">

## Brave version (brave://version info)

Target 1.66.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by aguscruiz** [comment]
Adjusted design here @emerick 

https://www.figma.com/file/5THkuEtO2Ewn9LfqrHZP9a/%5BARCHIVE%5D-Private-and-Tor-Windows?type=design&node-id=2354-3701&mode=design

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```

```

`Private window`

![image](https://github.com/brave/brave-browser/assets/387249/ab8af1bb-b823-4c31-aecb-17a956d916e2)

`Private window w/Tor`

![image](https://github.com/brave/brave-browser/assets/387249/fbb222ff-ab07-42cf-8cbf-f1c768e31e90)
