### ISSUE TITLE
Send BTC on iOS

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#37958]
## Description: 

We need to support ability to send BTC in iOS send token.
- Display Bitcoin accounts w/ available balance in Select Token to Send modal
- Display Bitcoin available balance in Send
- Validate send to address for bitcoin
- Show a warning with confirmation before allowing send:
> Brave Wallet does not currently support Bitcoin NFTs (ordinals). Sending BTC from an address that has ordinals may result in its ordinals being transferred inadvertently.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.0 Beta running 1.68 (117)
- Verified steps from [brave/brave-core#23476](https://github.com/brave/brave-core/pull/23476)
- Verified able to send BTC from one account to another
- Verified incorrect address shows error message
- Verified Send button is only enabled when the info switch is enabled
- Verified receiving address shows message about balance update 
- Verified clicking on view details shows the balance and pending 

![image](https://github.com/user-attachments/assets/2e1db5a3-c568-4a26-9ddc-566ab54b617a)  | ![image](https://github.com/user-attachments/assets/06a4f412-767a-47ce-aab5-4465320c95f5)  | ![image](https://github.com/user-attachments/assets/ad826eba-42f9-4c70-b490-cbfb4b7de3f5) | ![image](https://github.com/user-attachments/assets/cb4a51f5-a979-4f02-b097-ce9a372b8c63)  | ![image](https://github.com/user-attachments/assets/f04a8639-88c5-4987-9ea0-10a583f06483) | ![image](https://github.com/user-attachments/assets/c88c9213-2d9f-4e58-a206-f21286170905) | ![image](https://github.com/user-attachments/assets/068af2b4-78c6-468f-ade3-24be84de2b3a) 
-- | -- | -- | -- | -- | -- | --
![image](https://github.com/user-attachments/assets/a761a8bf-f8ff-43a8-a8e4-38c1055f7466)  | ![image](https://github.com/user-attachments/assets/cc2935d3-c565-4727-b6cf-86cae88f78c6)  | ![image](https://github.com/user-attachments/assets/119050f5-1b66-4b58-bfee-d8cc462a8429)  | ![image](https://github.com/user-attachments/assets/a76ad281-386e-42cc-939e-e1a1167c7e4d)  | ![image](https://github.com/user-attachments/assets/673c85b0-f167-4750-bc02-791936867c9b)  | ![image](https://github.com/user-attachments/assets/decfd0bf-00d8-41cd-94a4-b86df9d59fd7)
