### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by mek1959fMD** [brave/brave-browser#37952]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.65.123 Chromium: 124.0.6367.91
Operating System: Windows NT 10.0.22631

URL (if applicable) where crash occurred:

Can you reproduce this crash? Yes. Whenever my computer wakes up from sleep, all of my browser tabs will crash as soon as I click on them. I then have to restart my computer to stop the crashing. But now, the computer is running very slow and I've already done all sorts of anti-viral, malware cleaning.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Let computer go to sleep
2. Wake computer up.
3. Click on a tab and it will crash.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/5c601500-505c-df0b-0000-000000000000

**Comment by bsclifton** [comment]
Backtrace:
https://brave.sp.backtrace.io/p/brave/debug?time=all&filters=JTVCJTVCJTIyX2RlbGV0ZWQlMjIlMkMlMjJlcXVhbCUyMiUyQyUyMjAlMjIlNUQlMkMlNUIlMjJfcnhpZCUyMiUyQyUyMmVxdWFsJTIyJTJDJTIyNWM2MDE1MDAtNTA1Yy1kZjBiLTAwMDAtMDAwMDAwMDAwMDAwJTIyJTVEJTVE&fingerprint=bda22ff0b52e5262d0ab9293de1a564fcfeab6d1e3f7b89965c820244b445259&debug=(%22741a650%22,0,0)

Callstack:
```
[ 0 ] crash_reporter::DumpWithoutCrashing() ( crashpad.cc:269 )
[ 1 ] crash_reporter::internal::DumpProcessForHungInputThread(void *) ( crashpad_win.cc:195 )
[ 2 ] BaseThreadInitThunk
[ 3 ] RtlUserThreadStart
```

**Comment by iefremov** [comment]
@mek1959fMD the id you've shared is a diagnostic dump, not a crash. Can you please repro the problem several times and share the dumps?
