### ISSUE TITLE
Nightly no longer shows Google Calendar notifications

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#37959]
## Description 

Recently noticed that my Nightly version was no longer giving me google calendar notifications when it was previously. Notification permission is enabled (as it was before). This is not an issue on Release (1.65.x) or Beta (1.66.x).

@MadhaviSeelam reproduced on Windows using 1.67.x

## Steps to Reproduce

   1. Using 1.67.x, be logged in to gmail and have permission for notifications enabled (mine is set to "Forever" but I don't know if that's necessary)
   2. Have calendar open in a tab (doesn't need to be active tab)
   3. Wait for calendar notification

## Actual result:

Nightly 1.67.x does not give calendar notification

## Expected result:

Should get calendar notification like I do for both Beta 1.66.x and release 1.65.x

<img width="368" alt="Screenshot 2024-04-30 at 12 35 33 PM" src="https://github.com/brave/brave-browser/assets/28145373/a618fe9f-01b6-4a8c-9330-d63bd9adbee9">

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.67.42 Chromium: 124.0.6367.82 (Official Build) nightly (x86_64)
-- | --
Revision | 20596bca72f42301946d544fe158cb4e1aa7a70a
OS | macOS Version 13.6.6 (Build 22G630)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.65.x no
- Can you reproduce this issue with the beta channel? 1.66.x no
- Can you reproduce this issue with the nightly channel? 1.67.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron

**Comment by bsclifton** [comment]
You may need to sign out of Google and back in

**Comment by MadhaviSeelam** [comment]
Verified on new install 1.67.53 and notifications are shown as expected in Win 11. 


![image](https://github.com/brave/brave-browser/assets/98358127/ff0129a6-da44-44ea-af2e-3eb3cc52c111)

**Comment by LaurenWags** [comment]
thanks all - I'll give it a try 👍🏻

**Comment by LaurenWags** [comment]
Seems logging back into Google fixed it. Thanks!
