### ISSUE TITLE
[ads] Reset exponential backoff when refilling or redeeming payment tokens after a failure that should not retry

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#37957]

**Comment by LaurenWags** [comment]
@tmancey this one has both `QA/Yes` and `QA/No`, which one is correct? 😄

**Comment by tmancey** [comment]
@LaurenWags removed QA/No :-), thanks

**Comment by btlechowski** [comment]
Verified with

Brave | 1.67.107 Chromium: 126.0.6478.26 (Official Build) beta (64-bit)
-- | --
Revision | 2831369c7540d93e98f38d9b463f6762430a7982
OS | Linux

### confirmation token

<details>


</details>

### payment token


<details>


</details>
