### ISSUE TITLE
Autoplay not blocked on The Independent if opened in a tab

### ISSUE THREAD

**Issue by FWDekker** [brave/brave-browser#3795]
## Description 
Videos in [The Independent](https://www.independent.co.uk/) news articles will play automatically under some specific circumstances even if autoplay is globally disabled.

## Steps to Reproduce
The following steps are all necessary; leaving out just one detail may result in the issue not occurring.

1. Open a fresh new Brave instance or just a new incognito window.
2. Go to a website that has a link to a news article on The Independent containing a video. For example, use the page you're looking at right now because it contains [this link](https://www.independent.co.uk/news/uk/politics/brexit-delay-eu-no-deal-michel-barnier-leave-theresa-may-john-bercow-a8830716.html).
3. Open the link in a new tab and do not visit it until the page has finished loading, i.e. until the loading indicator in the tab bar has been replaced with the icon of The Independent.
4. Go to the newly opened tab and wait for 5 seconds. Do not do anything: no scrolling, no clicking, no accepting cookies. (This step is not strictly necessary but without it the issue does not always occur.)
5. Scroll down until the video collapses into a sidebar-thing and wait for 10 seconds until the video suddenly starts playing.

## Actual result
The video in the sidebar starts playing with audio.

## Expected result
The video does not start playing.

## Reproduces how often
Easily reproduced

## Brave version
```
Brave    0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)
Revision 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS       Windows 10 OS Build 17763.379
```

### Reproducible on current release
- Does it reproduce on brave-browser dev/beta builds?
Did not test.

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?
No, it makes it worse: An ad will automatically play with sound, after which the regular video will also start playing,

- Is the issue reproducible on the latest version of Chrome?
No. The latest version of Chrome will block the advert from playing before the article's video even appears.

**Comment by anotherzen** [comment]
Adding info regarding the same issue, just another website.
Issue was found from todays Tweet Brave did regarding an article Cnet wrote.
I think maybe i over-spammed Sampson as he replied to me and i was all over the place trying to tweet how to reproduce the issue. Apologies.

**Issue**
- Not autoblocking any video on Cnet if opened with the steps below.

**Steps to reproduce**
- Go to Cnet (https://www.cnet.com)
- _Middle click_ or _Right click + Open in new tab_ any article featuring a video
- Wait a few seconds before clicking on the newly created tab, for me its about 4 seconds.

**Actual result**
- Autoblock of video does not engage and the video starts playing upon page view.

**Expected result**
- Autoblock should engage and stop video from autoplay.

**Brave Version**
- Brave Version 0.66.100 Chromium: 75.0.3770.142 (Official Build) (64-bit)
- Windows 10
- Not tested any other version.

**Additional information**
The issue does not manifest if you _left click_ on a link or if you _right click + open in new tab_ on a link and immediately go to the tab.

The link does not have to come from within Cnet, you can open in new tab from external sites such as Twitter. You can check this by going to the tweet linked to below and opening the link to Cnet in that tweet in a new tab and get the same result.

I am not sure why this is, it's almost like autoblock initializes on TAB view, and if the video content gets
loaded in the background before you click on the TAB, autoblock does not catch it.
Pure speculation on my part.



Link to tweet:
(https://twitter.com/brave/status/1153358139070111745) 

Additional musings:
I have not tested other sites if they behave the same way.

There does seem to be some inconsistencies regarding autoblock on other sites as well, as i sometimes see videos on Twitter autoplay, but upon reload of twitter they can be blocked.

**Comment by warwickmm** [comment]
I just upgraded to 1.18.70 on Linux and autoplay blocking is now working for me.  Using the link in the described steps, the video is blocked, and after scrolling the video collapses to the side bar and remains blocked.  There is also a "autoplay was blocked on this page" icon at the top right in the address bar.

Version 1.18.70 Chromium: 87.0.4280.101 (Official Build) unknown (64-bit)

**Comment by FWDekker** [comment]
I no longer use Brave, so I'll trust you when you say this has been fixed :)
