### ISSUE TITLE
Apply upstream's fix for "Live HLS streams freeze".

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#37967]
By @atuchin-m's request:

Upstream fix for https://issues.chromium.org/issues/336837266 needs to be brought to Brave, but the current Chromium 124 bump doesn't have the fix yet (the fix is https://chromium.googlesource.com/chromium/src/+/6ced09e8becd17b696730e0e277a016af7548a7b and was merged into 124.0.6367.123 which was branched off of 124.0.6367.54 - not the latest Android release version).

We can just pick up the fix separately and add it to our current release.

**Comment by kjozwiak** [comment]
STR/Cases mentioned via https://github.com/brave/brave-variations/pull/1036#issue-2271201950:

```
Steps to reproduce (android):
1. Go to https://v.ggicci.me/sample/index.m3u8
2. Press play

It works in Chrome or in Brave <=cr123. Doesn’t work for Brave cr124.
```

**Comment by kjozwiak** [comment]
The above requires `1.65.126` or higher for `1.65.x` verification(s) 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using version: 

```
Brave	1.65.126 Chromium: 124.0.6367.118 (Official Build) (64-bit) 
Revision	e6a0dcfed2e939addb42f91900875679412fa5b7
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Verified test steps in https://github.com/brave/brave-browser/issues/37967#issuecomment-2087843603 and ensured that video plays without issue. 

![Screenshot 2024-05-01 at 11 44 32 AM](https://github.com/brave/brave-browser/assets/17885425/fb3d2c1f-f9be-43f9-a958-f52562eb8c11)
