### ISSUE TITLE
[hackerone] Investigate enforcing a more specific WireGuard tunnel config

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#37960]
## Test plan
TBD

## Description 
Originally reported in https://hackerone.com/reports/2481145 by newfunction

Suggested fix - https://bravesoftware.slack.com/archives/C6R461GF4/p1714494301869619?thread_ts=1714239526.751669&cid=C6R461GF4

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.69.107 Chromium: 127.0.6533.43 (Official Build) nightly (64-bit)
-- | --
Revision | b488d8743681b4b13fbe03a8d57a25af75998de5
OS | Windows 11 Version 23H2 (Build 22631.3880)
```

**Comment by stephendonner** [comment]
## Case 1 - "happy path"
## Case 2 - existing installation
## Case 3 - upgrade scenario

**Comment by LaurenWags** [comment]
Changing to `release-notes/exclude` per consultation with @diracdeltas
