### ISSUE TITLE
Change Leo to a `7-day Free Trial`

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#37961]
Mini spec: https://docs.google.com/document/d/1ck-fHBk2S8f1wk5Zu6e1bHmDRuwraieQkT1S_2qPJ3c/edit

- [x] https://github.com/brave/account-brave-com/issues/151
- [ ] https://github.com/brave-intl/subscriptions/issues/559 (https://github.com/brave-intl/subscriptions/pull/560)

**Comment by aguscruiz** [comment]
Adding designs here
https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=2804-6469&mode=design

**Comment by kjozwiak** [comment]
The above requires `1.73.91` or higher for `1.73.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7.1
Brave build: 1.73 (91)
BraveCore: 1.73.91 (131.0.6778.85)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Hamburger menu > Settings
3. Leo > Go Premium > *Verify*
4. Tap `One Year` subscription > *Verify*
5. Purchase new `yearly` subscription > *Verify*

**ACTUAL RESULTS:**
- Verified that `One Year` and `Monthly` subscriptions exist.
- Verified that a `1-week free trial` is available for users who have not subscribed to `Leo Premium`.
- Verified that purchasing Leo with a free trial is working.
- Verified that users are able to cancel the free trial.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/7fe2be5b-6876-44e7-9c72-44a8e8deea02) | ![2](https://github.com/user-attachments/assets/0e9f2292-5b92-4879-bf6c-2321da4e5ee3) | ![3](https://github.com/user-attachments/assets/e57d07e3-87ba-4c39-a081-00653bf7044b) | ![4](https://github.com/user-attachments/assets/48340bf7-f4ed-4edb-89ca-ecec9bc4d789) |
| ![1](https://github.com/user-attachments/assets/82571dbd-1ac3-496c-a67f-e4a2ec838c1d) | ![2](https://github.com/user-attachments/assets/80c702ce-13dd-409b-b160-6c80864ae60d) | ![3](https://github.com/user-attachments/assets/031b060a-b6ba-4ff1-9c6b-772853625a15) | ![4](https://github.com/user-attachments/assets/38a4e3ab-deed-49fa-b0ef-f03ed3181c71) |
