### ISSUE TITLE
HEVC/H.265 video playback on Linux

### ISSUE THREAD

**Issue by joewood9364** [brave/brave-browser#37963]
## Description 
Enable playback of HEVC/H.265 ideally with hardware acceleration although software decode would still be appreciated.

## Steps to Reproduce
Attempt playing a HEVC/H.265 video but nothing will happen

## Actual result:
No playback

## Expected result:
Video playback

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.65.123 Chromium: 124.0.6367.91 (Official Build) (64-bit) Linux

## Version/Channel Information:
HEVC decodes fine on Windows, its just Linux which does not work.

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? yes

## Miscellaneous Information:
https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/releases
The chromium binary from the above repository actually decodes HEVC quite well when I installed it on my system. I don't understand how they did this but would of course be grateful if someone more knowledgeable could carry it over to Brave.

**Comment by ghccalanzani** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/3646633

**Comment by MrJimmyPenguin** [comment]
I've got the same issue on popos brave Version 1.66.118

**Comment by bsclifton** [comment]
Hi folks - I'm going to close this as a duplicate of https://github.com/brave/brave-browser/issues/40101

Please see this post for information about how to enable the feature and how to test it
https://github.com/brave/brave-browser/issues/40101#issuecomment-2262222466

**Comment by Logan-Quest** [comment]
Confirm @joewood9364's comment. I'm also running Brave on Linux Mint (22) and adding the `--enable-features=PlatformHEVCEncoderSupport` flag still doesn't allow my security cameras to play in Brave Browser on Linux. I can play it in Windows.

**Comment by Logan-Quest** [comment]
@bsclifton please re-open. The issue you linked is a different issue from the Linux issue.

**Comment by MrJimmyPenguin** [comment]
I'm still having this issue

**Comment by Logan-Quest** [comment]
@bsclifton please re-open.

**Comment by bsclifton** [comment]
Hi folks - @MrJimmyPenguin @Logan-Quest if you didn't already, can you add your info to https://github.com/brave/brave-browser/issues/40101?

I edited the title to overall encompass HEVC. Apologies that it was worded as Windows.

**Comment by MrJimmyPenguin** [comment]
Done thank you.

**Comment by Logan-Quest** [comment]
Added to #40101.

**Comment by LaurenWags** [comment]
Adding `QA/No` as this will be covered under https://github.com/brave/brave-browser/issues/40101.
