### ISSUE TITLE
Ads are shown after launching app but before window refresh

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#37962]
## Description: 
Ads are shown after launching app. This is a regression on 1.66.x

Possibly an issue with the preloaded ad-blocking script not working

## Steps to Reproduce 
  1. New install 1.66.x
  2. Immediately navigate to youtube.com and other media sites
  3. Play videos with ads for 30-40 secs until there is a black screen at the beginning of the videos
  4. Look for ads / cookie notices in other tabs
  5. Refresh the page using the reload button
  6. Do the same for the youtube tab

## Actual result: 
Ads are shown until ad-block engines are compiled and user refreshes page 

https://github.com/brave/brave-browser/assets/17885425/bcc0d00c-a4d8-407e-856c-e51bd9056737

## Expected result:
Ads should not be shown

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Always 

## Brave Version: 
1.66.90
1.64.x (intermittent)

- Can you reproduce this issue with the most recent build from TestFlight? Yes (beta)
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes (beta)
- Can you reproduce this issue with the current build from AppStore? No (new install)

### Device details: 
iPhone 12

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari?

**Comment by kjozwiak** [comment]
The above requires `1.66.102` or higher for `1.66.x` verification 👍

**Comment by Uni-verse** [comment]
In progress on iPhone 12 using version 1.66.110

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iPadOS 17.4.1` using version `1.66.110`

- Ensured pre-roll and content ads are not shown on Youtube after launching Brave for new or existing users. 
- Ensured content ads are not shown on media sites such as `https://www.buzzfeed.com`.
- Ensured ads are blocked using `standard` and `aggressive` blocking modes.
- Ensured that disabling Shields will display pre-roll and content ads on media sites. 

Example | Example | Example | Example
-|-|-|-
![IMG_1380](https://github.com/brave/brave-browser/assets/17885425/4ee9584c-2e1c-4b72-8390-193dcdb722c0) | ![IMG_1381](https://github.com/brave/brave-browser/assets/17885425/ca279b7c-6740-4dfa-88b7-746d70c8243e) | ![IMG_1382](https://github.com/brave/brave-browser/assets/17885425/32cc5371-6a24-4f34-9b80-ae34cf469128) | ![IMG_1383](https://github.com/brave/brave-browser/assets/17885425/b528cc1a-9a8d-44d2-83ae-bc5bb4b46906)
