### ISSUE TITLE
Update button coloring/style to Nala

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#37970]
## Description 

Several buttons are still using the old Brave orange icons. These should be the "blurple" color per the Nala design system.

## Actual result:

Bookmarks dialog
<img width="473" alt="Screenshot 2024-04-29 at 5 47 01 PM" src="https://github.com/brave/brave-browser/assets/5951041/30723c9c-32c5-42ed-b674-86945070cbdf">

Views MdButton
![image_360](https://github.com/brave/brave-browser/assets/5951041/4f4e322a-9b41-422a-a99e-c6fd8ca3ae6a)

Infobar
![image](https://github.com/brave/brave-browser/assets/5951041/ffb38c7e-bc6e-426c-8f86-50e78aab21dd)

Webcompat report (maybe it's WebUI)
<img width="432" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/3eb4095e-ef8a-4ec3-9fa5-5b7835e054cd">

task manager
![image](https://github.com/brave/brave-browser/assets/6786187/037b18ee-ed0c-4884-9254-057603bb5769)

## Expected result:
<img width="348" alt="Screenshot 2024-04-30 at 3 57 29 PM" src="https://github.com/brave/brave-browser/assets/5951041/3159e52e-4bae-4eb8-aa1b-1216df07d7cb">

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Target 1.66.x for fix.

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a Orange buttons
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by simonhong** [comment]
working on this.

**Comment by MadhaviSeelam** [comment]
**_Import bookmarks now... | Close tabs_** 

![image](https://github.com/brave/brave-browser/assets/98358127/3f8d30d3-eac0-4b1d-a00a-a39a49d09646)

**_Report broken site_**

example | example 
----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/fb4ba5c3-e2dd-42b9-9a4c-8f5511f7846e)|![image](https://github.com/brave/brave-browser/assets/98358127/c6044cdb-bf6d-47b6-883a-019413c62d60)

**_Save Password_**

example | example 
----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/5449beba-6581-4829-b527-8435487e7b8b)
![image](https://github.com/brave/brave-browser/assets/98358127/d988cc72-720e-45f6-b2f1-e86a1a325eb0)
![image](https://github.com/brave/brave-browser/assets/98358127/c7fd4397-76ff-49b1-88c7-6b0e882d84b6)
![image](https://github.com/brave/brave-browser/assets/98358127/69f10426-8bdb-4ddf-b35f-0d6ced41532b)


![image](https://github.com/brave/brave-browser/assets/98358127/81c927ef-a19d-475f-8f1f-5dfec48bbc4e)
![image](https://github.com/brave/brave-browser/assets/98358127/908fc69c-46be-47b4-aded-2ada77794030)
![image](https://github.com/brave/brave-browser/assets/98358127/a2e38e4c-213d-44f0-b30a-6de3ec1e4830)
![image](https://github.com/brave/brave-browser/assets/98358127/c5c435bb-c45b-4959-9e06-f47288d64121)
![image](https://github.com/brave/brave-browser/assets/98358127/c067537f-a7e9-468b-85c6-182f404c440b)
![image](https://github.com/brave/brave-browser/assets/98358127/1d0a1137-254c-4e35-9888-172d8cfa320c)

**_Extensions_**

example | example | example | example |example 
----- | ---- | ----- | ----- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/c4d03185-b2f9-4225-89c9-b44ab9f52f73)|![image](https://github.com/brave/brave-browser/assets/98358127/82039dd1-014d-467e-beb3-93a21dc091cc)|![image](https://github.com/brave/brave-browser/assets/98358127/21bce753-8c1a-4eb3-993a-7ec270502986)|![image](https://github.com/brave/brave-browser/assets/98358127/a26c25f8-4301-4b8b-8621-f17e330546f3)|![image](https://github.com/brave/brave-browser/assets/98358127/6eaff759-f0f0-414c-a902-083b9453f9ad)

Sidebar

**_Leo_**
example | example | example  
----- | ---- | -----  
![image](https://github.com/brave/brave-browser/assets/98358127/81d7c1c9-5f10-448a-ba0c-f7fe3abe9652)|![image](https://github.com/brave/brave-browser/assets/98358127/13ed105a-463d-4af6-a7d1-6ea75316b4dd)|![image](https://github.com/brave/brave-browser/assets/98358127/5b684dc5-ba03-4cba-8632-f72e5a197550)

**Comment by kjozwiak** [comment]
@MadhaviSeelam please let me know once you're done the above as we have an uplift into `1.66.x` via https://github.com/brave/brave-core/pull/23405. However, looks like there's a few cases that are failing so we might want to get those fixed before uplifting. CCing @rebron on thoughts.

**Comment by kjozwiak** [comment]
The above requires `1.66.102` or higher for `1.66.x` verification 👍 @brave/qa-team keep in mind that @MadhaviSeelam found several issues relating to buttons/labels as per:

* https://github.com/brave/brave-browser/issues/38097
* https://github.com/brave/brave-browser/issues/38098
* https://github.com/brave/brave-browser/issues/38100
* https://github.com/brave/brave-browser/issues/38104
* https://github.com/brave/brave-browser/issues/38106

Please keep an eye on any other buttons/labels that might still appear is `orange` which should be set as `blurple`.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.66.102 Chromium: 124.0.6367.118 (Official Build) beta (x86_64)
-- | --
Revision | 3f00a25afc25dfd9a221c0d98c0ab3ed93ab47ee
OS | macOS Version 13.6.6 (Build 22G630)
```

**Comment by ivanjx** [comment]
is this also supposed to affect websites in general? how to stop the "blurple" color in websites?

normal:
![Screenshot from 2024-06-11 20-28-48](https://github.com/brave/brave-browser/assets/12814796/c78760de-aa0b-4fef-917a-2919ae1c24b8)

brave:
![Screenshot from 2024-06-11 20-28-41](https://github.com/brave/brave-browser/assets/12814796/a5456558-c89b-4146-ab2f-4a76ec2166c2)
