### ISSUE TITLE
[Brave News]: Fix infinite load after first opt in on Windows

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#37972]
This is a followup issue for https://github.com/brave/brave-browser/issues/37738

Several requests to fetch the publishers seem to be failing on @stephendonner's machine while Brave News is starting. The root bug seems to be that the `initialized_prefs_promise` wasn't signalling when there was a failure. However, we don't want to fail to initialize just because a request failed on startup.

My solution is:
1. Retry up to 3 times (we can configure this later) with gradually increasing backoffs
2. If we failed to get the feed 3 times, then fire the initialization signal anyway (which will put us in a state with no subscribed feeds).

**Comment by kjozwiak** [comment]
The above requires `1.66.103` or higher for `1.66.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.66.103 Chromium: 124.0.6367.159 (Official Build) beta (64-bit)
-- | --
Revision | 74d46bb25d9ea5e6432e19f0cf38480cc372b0cf
OS | Windows 10 Version 22H2 (Build 19045.4355)
```

### Steps:
1. installed `1.66.103`
2. launched Brave
3. opened a new-tab page
4. scrolled down
5. clicked on `Turn on Brave News`

### Confirmed Brave News loaded with its `Top Sources` feeds and articles displaying (tested multiple times)

https://github.com/brave/brave-browser/assets/387249/e7ec14cb-c05c-4b69-8d3d-185c24553401
