### ISSUE TITLE
[Brave Leo]: Add Claude 3 model (Haiku and Sonnet) to model selection in iOS

### ISSUE THREAD

**Issue by LorenzoMinto** [brave/brave-browser#37989]

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.6
- iPad Air / iPadOS 16.7.2
Brave build: 1.68 (125)
BraveCore: 1.68.125 (127.0.6533.57)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/23440#issue-2281277751
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Claude 3 Haiku` and `Claude 3 Sonnet` are available in language model list
- Verified that `Claude 3 Haiku` and `Claude 3 Sonnet` are not set as `default` LM
- Verified that `Claude 3 Sonnet` is available only for `Premium` users

---------------------------

`iPhone`

<details>
<summary> Premium user </summary>

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/8ff2fe7c-d96b-4719-91e3-b9230da4c151) | ![2](https://github.com/user-attachments/assets/1308b738-ab36-4dbe-980b-493463e0acf4) | ![3](https://github.com/user-attachments/assets/9ac0db8f-f028-4241-9a09-5382dfccb00b) | ![4](https://github.com/user-attachments/assets/a185081b-e319-48d7-9613-65b4e337fbd7) |
</details>

<details>
<summary> Freemium user </summary>

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/3bf58431-d9a0-408f-afb5-c676992bcc5f) | ![2](https://github.com/user-attachments/assets/4d1307a7-86f1-45c4-af98-73b3815fa32b) | ![3](https://github.com/user-attachments/assets/56f5c72e-21d5-4f52-8cdb-25eae8ac4f23) |
| ![1](https://github.com/user-attachments/assets/d297a1c8-9fad-45f7-a216-cb224886f5ae) | ![2](https://github.com/user-attachments/assets/c4c31140-8de6-4a97-a5b3-b1e6c7fc5397) | ![3](https://github.com/user-attachments/assets/6aa12271-a156-4733-bfa0-3a322e3c4128) |
</details>

`iPad`

<details>
<summary> Premium user </summary>

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/e089dd62-1136-4a99-8da6-1869e9634f9c) | ![2](https://github.com/user-attachments/assets/9a73f02b-83e7-4c9b-9af8-ece99296d505) | ![3](https://github.com/user-attachments/assets/d2c4f471-815f-4b4a-b7d4-33836807bed3) | ![4](https://github.com/user-attachments/assets/2c47425a-cae5-48d5-9cd3-fa127b17be24) |
</details>

<details>
<summary> Freemium user </summary>

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/e1e3980f-3670-401d-86d7-3d6d7a922a97) | ![2](https://github.com/user-attachments/assets/7421680a-c064-4dc9-babc-49ebf7b6b63a) | ![3](https://github.com/user-attachments/assets/f6ac2fee-1511-4498-b713-fbe63ed9819f) | ![4](https://github.com/user-attachments/assets/21bb219d-42df-474b-88c3-1431996a8121) |
</details>
