### ISSUE TITLE
Brave compatibility with major password managers (Google, Proton Pass, etc.) is required.

### ISSUE THREAD

**Issue by Beatz106** [brave/brave-browser#37984]
## Description 

There is no compatibility between Brave and any password manager, be it Google, KeePass, Proton Pass, among others. All builds (standard version, beta, nightly) do not offer this possibility.

Important: Someone proposed that the browser be an autifill manager, this report should not be confused with that https://github.com/brave/brave-browser/issues/36226 whose objective is radically different, making the browser an autofill manager within the browser itself with data previously entered therein.

## Steps to reproduce 

   1. You must have a password manager, in this case Google will be used: Settings/General Management/Autofill service 
![Screenshot_20240430-235016_Settings](https://github.com/brave/brave-browser/assets/74375581/ba7bff90-5ec4-495e-ae1a-0f827e317997)

   2. From your password manager there should be a website to test, on this occasion the Box service will be used. 
![Screenshot_20240430-235105_Google Play services](https://github.com/brave/brave-browser/assets/74375581/1f95a5c2-fc8c-41e2-b55f-4764fa513d66)

   3. You must visit the site that has saved credentials, regardless of the browser build type. Since the UI is the same, it is impossible to determine by itself which version is displayed, I will take care of it, also the problem does not distinguish between versions. The screenshot to be used will be the normal version (understood as Not beta or nightly) 
![Screenshot_20240501-000627_Brave](https://github.com/brave/brave-browser/assets/74375581/ca792784-3490-4e79-85fe-923482c11255)

## Actual result 

Unlike other browsers like Vivaldi or Kiwi Browser (not working on Microsoft Edge and Opera) Brave does not react even if you touch the field for entering email for a long time. 
![Screenshot_20240501-001628_Brave](https://github.com/brave/brave-browser/assets/74375581/3cd40f16-35d2-4bd1-b03f-89f4567e27ab)

## Expected result

There should be no problems filling out information, in this case login credentials information. Vivaldi example. 
![Screenshot_20240501-002146_Vivaldi](https://github.com/brave/brave-browser/assets/74375581/ec193f96-97f3-48cb-a9bc-81450b0858b6)

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version: 

1.65.122 (Normal)/1.67.49 (Nightly)

**Comment by bsclifton** [comment]
ProtonPass and others should be working fine. If that is not working, please let us know!

Google not showing for autofill in Brave is a known issue and is captured with https://github.com/brave/brave-browser/issues/27786

Please subscribe to that issue for updates! We're actively working on fixing. Kudos to @tapanmodh and @deeppandya

**Comment by grantgarbe** [comment]
> ProtonPass and others should be working fine. If that is not working, please let us know!
> 
> Google not showing for autofill in Brave is a known issue and is captured with [#27786](https://github.com/brave/brave-browser/issues/27786)
> 
> Please subscribe to that issue for updates! We're actively working on fixing. Kudos to [@tapanmodh](https://github.com/tapanmodh) and [@deeppandya](https://github.com/deeppandya)

Proton Pass works fine for filling in passwords, but signing in with passkeys saved in Proton Pass is not working for me. I click to sign in with a passkey but it asks me to use a security key or use another device. I exit the prompt and nothing else shows up.
