### ISSUE TITLE
Feature request: sandbox

### ISSUE THREAD

**Issue by 3noki** [brave/brave-browser#3798]
## Request to add a sandbox feature to Brave
I would like to request adding a sandbox or immutability to Brave. There's a few types of sandboxes out there like Sandboxie, virustotal.com, reverse.it, cuckoo sandbox, [windows enterprise sandbox](https://techcommunity.microsoft.com/t5/Windows-Kernel-Internals/Windows-Sandbox/ba-p/301849), or just a Virtual machine.

### Brave core dev tools sandbox question raised but not for production browser 
[issues/911](https://github.com/brave/brave-browser/issues/911)
[issues/1086](https://github.com/brave/browser-laptop/issues/1086)

**Comment by diracdeltas** [comment]
Brave uses the Chromium sandbox to run untrusted content in separate processes. is there something specific you're looking for? https://chromium.googlesource.com/chromium/src/+/lkgr/docs/design/sandbox_faq.md

**Comment by fmarier** [comment]
If you can provide more details as to how that sandbox would be different from the Chromium one, please reopen this issue.
