### ISSUE TITLE
Crash in `ai_chat::PrintPreviewExtractor::PreviewCleanup()` while trying to summarize page 20 of a 21-page Google Doc

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#37997]
## Description 

Crash in `ai_chat::PrintPreviewExtractor::PreviewCleanup()` while trying to summarize page 20 of a 21-page Google Doc

Found while testing https://github.com/brave/brave-browser/issues/36649

## Steps to Reproduce

1. install 1.67.56
2. launch Brave
3. load https://docs.google.com/document/d/1p5kTWB3o2Y99rspl1yV3a64bEsXmx39Rp01HhWpR-Ok/edit#heading=h.y1t7tbvgyce or a similar 22-page document (19 blank pages, 1 page with content, 1 more page with totally different content)
4. click on Leo in the sidebar
5. advance in the document to page 20
6. click on Summarize this page
7. wait

## Actual result:

Crashes

Incident ID: `eb750000-ea91-e80b-0000-000000000000`

```
[ 00 ] ai_chat::PrintPreviewExtractor::PreviewCleanup() ( immediate_crash.h:179 )
[ 01 ] ai_chat::PrintPreviewExtractor::OnGetOCRResult(std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>>) ( print_preview_extractor.cc:432 )
[ 02 ] void base::internal::DecayedFunctorTraits<void (ai_chat::PrintPreviewExtractor::*)(std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>>), base::WeakPtr<ai_chat::PrintPreviewExtractor>&&>::Invoke<void (ai_chat::PrintPreviewExtractor::*)(std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>>), base::WeakPtr<ai_chat::PrintPreviewExtractor> const&, std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>>>(void (ai_chat::PrintPreviewExtractor::*)(std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>>), base::WeakPtr<ai_chat::PrintPreviewExtractor> const&, std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>>&&) ( bind_internal.h:738 )
[ 03 ] void base::internal::InvokeHelper<true, base::internal::FunctorTraits<void
<SNIP>
[ 56 ] content::ContentMain(content::ContentMainParams) ( content_main.cc:345 )
[ 57 ] ChromeMain ( chrome_main.cc:192 )
[ 58 ] main ( chrome_exe_main_mac.cc:217 )
[ 59 ] start
```

## Expected result:

No crash

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

```
Brave | 1.67.56 Chromium: 124.0.6367.91 (Official Build) nightly (x86_64)
-- | --
Revision | 5670584eb8a1807ab8ac1584fb099bd21ec1e381
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Unknown; working on it!`
- Can you reproduce this issue with the beta channel? `Checking...`
- Can you reproduce this issue with the nightly channel? `Yes`

@darkdh @bbondy @petemill @mattmcalister @rebron @voqan @LorenzoMinto @brave/qa-team

**Comment by stephendonner** [comment]
cc @LorenzoMinto @evq in case this is context-limit related?

**Comment by darkdh** [comment]
> cc @LorenzoMinto @evq in case this is context-limit related?

No, it is not. It's within the scope of `PrintPreviewExtractor`

**Comment by darkdh** [comment]
@stephendonner can you reproduce it with normal one or two pages with contents?
I was having hard time reproduce it but I'm pretty sure it hit the CHECK.

**Comment by stephendonner** [comment]
> @stephendonner can you reproduce it with normal one or two pages with contents? I was having hard time reproduce it but I'm pretty sure it hit the CHECK.

No, I cannot.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.67.64 Chromium: 125.0.6422.26 (Official Build) nightly (x86_64)
-- | --
Revision | 53ddfd8ce864582b576ac5c24a189fa392e53b59
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```

```

![image](https://github.com/brave/brave-browser/assets/387249/522afa0a-1309-4f7c-892a-bd9a0614cd71)
