### ISSUE TITLE
Google Docs: Unable to get accurate summarization of page 20

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#37996]
## Description 

Google Docs: Unable to get accurate summarization of page 20

Found while testing https://github.com/brave/brave-browser/issues/36649

## Steps to Reproduce

   1. install `1.67.56`
   2. launch Brave
   3. load `https://docs.google.com/document/d/1p5kTWB3o2Y99rspl1yV3a64bEsXmx39Rp01HhWpR-Ok/edit#heading=h.y1t7tbvgyce` or a similar 22-page document (19 blank pages, 1 page with content, 1 more page with totally different content)
   4. click on `Leo` in the sidebar
   5. advance in the document to `page 20`
   6. click on `Summarize this page`
   7. wait

## Actual result:

![Screenshot 2024-05-01 at 9 44 58 AM](https://github.com/brave/brave-browser/assets/387249/b9a1d18e-0c8c-40c7-9e83-da21928c467c)

## Expected result:

<img width="1312" alt="Screen Shot 2024-05-01 at 10 30 54 AM" src="https://github.com/brave/brave-browser/assets/387249/b0c203fd-cf3f-4519-856b-2ade4091508a">

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.67.56 Chromium: 124.0.6367.91 (Official Build) nightly (x86_64)
-- | --
Revision | 5670584eb8a1807ab8ac1584fb099bd21ec1e381
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @darkdh @bbondy @petemill @mattmcalister @rebron @brave/qa-team

**Comment by darkdh** [comment]
The problem is print preview only gives us 15 pages of data so the extractor won't get a chance to process beyond 15 pages.
Print dialog doesn't have this issue, needs further investigation.

**Comment by darkdh** [comment]
> Not a regression, we couldn't even summarize more than one page before this PR.

Just saw this in steps
`5. advance in the document to page 20`

If we do this intentionally to make that page appear in viewport then it is a regression

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.68.85 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | 8e76a669cf78bdfa933c8d569460092a01166588
OS | Windows 10 Version 22H2 (Build 19045.4474)
```

### Confirmed `Claude 3 Haiku` correctly summarized the 20th page

### Steps:
1. installed `1.68.85`
2. launched Brave
3. loaded `https://docs.google.com/document/d/1p5kTWB3o2Y99rspl1yV3a64bEsXmx39Rp01HhWpR-Ok/edit`
4. clicked on `Leo` in the sidebar
5. advanced to page `20`
6. clicked on `Summarize this page` with `Claude 3 Haiku` selected

![image](https://github.com/brave/brave-browser/assets/387249/40c8f25e-ac41-43ef-9828-995d9c54262a)
