### ISSUE TITLE
Show Web Discovery Project onboarding card for all countries

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#38006]
## Description 

Follow-up to #31545. Onboarding card for Web Discovery Project should be shown to all countries.

## Expected result:

![290694395-e0a4a7aa-5143-4bb8-8afd-74506a10a0f0](https://github.com/brave/brave-browser/assets/5951041/17352e64-cbfb-403c-9bf8-a0f335fdd864)

## Brave version (brave://version info)

Target 1.66.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```

```

**Comment by kjozwiak** [comment]
The above requires `1.66.103` or higher for `1.66.x` verification 👍 Removing the `QA Pass` label as we'll need to re-verify using `1.66.x`. Used https://github.com/brave/brave-browser/issues/38006#issuecomment-2099274101 as the needed verification on `Nightly` for uplift as per https://github.com/brave/brave-core/pull/23482#pullrequestreview-2044564403.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.66.103 Chromium: 124.0.6367.159 (Official Build) beta (64-bit)
-- | --
Revision | 74d46bb25d9ea5e6432e19f0cf38480cc372b0cf
OS | Windows 11 Version 23H2 (Build 22631.3527)
```

1. Installed 1.66.103
2. launched Brave
3. clicked `Set Brave as default browser`
4. clicked `Skip`
5. clicked `Sure, I'll help`
6. clicked `May be later


#### Confirmed `Web Discovery Project` onboarding card shown for `en-US`, `en-DE`,  `en-BR`, en-FR`

#### locale - `en-US`

<details>
<summary>Existing Profile:  clicked "Sure I'll help later" button</summary>

screen 1 | screen 2 | screen 3 | screen 4 | brave://settings/search
------ | ----- | ----- | ------ | -----
<img width ="400" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/0c3111c5-ff40-4181-bac1-08c25a8d5df0">|<img width ="400" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/72aa2ec4-a4ab-48b4-989a-35e23c3a000a">|<img width ="300" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/cf9a67e9-a1d8-4f87-be18-42de72c12424">|<img width ="400" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d8b5d848-9ef5-4b92-adcd-aae8fd954092">|<img width ="150" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d404542c-62f4-4d68-9024-240d16d135f3">
</details>

<details>
<summary>New Profile:  clicked "Sure I'll help later" button</summary> 

screen 1 | screen 2 | screen 3 | screen 4 | brave://settings/search
------ | ----- | ----- | ------ | -----
![image](https://github.com/brave/brave-browser/assets/98358127/14a5de3f-fa6c-43e1-81d4-89482ec01494)|![image](https://github.com/brave/brave-browser/assets/98358127/96efefb1-b23c-4686-862f-1aeea99a5ffe)|![image](https://github.com/brave/brave-browser/assets/98358127/942c5bd4-b51d-4692-977b-752e952c97f2)|![image](https://github.com/brave/brave-browser/assets/98358127/9cd3b870-9cc3-4442-9e63-460737db633d)|![image](https://github.com/brave/brave-browser/assets/98358127/42719baf-6257-4a15-95f0-237f0d8779d7)
</details>

<details>
<summary>New Profile:  clicked "May be later" button</summary>

screen 1 | screen 2 | screen 3 | screen 4 | brave://settings/search
------ | ----- | ----- | ------ | -----
![image](https://github.com/brave/brave-browser/assets/98358127/86dbc43f-2fc5-4e30-a374-c83607068d29)|![image](https://github.com/brave/brave-browser/assets/98358127/e12b6e17-2602-4342-b6a3-fa9d7e7d2273)|![image](https://github.com/brave/brave-browser/assets/98358127/00aedb84-8d27-41cd-8129-e6647bbf9f2e)|![image](https://github.com/brave/brave-browser/assets/98358127/8c8847f0-5228-4f69-8650-340f483236a0)|![image](https://github.com/brave/brave-browser/assets/98358127/58f4a742-214a-4ba3-8cdb-48ee579f6f69)
</details>

#### locale - `en-DE`

<details>
<summary>New Profile:  clicked "Sure I'll help later" button</summary> 

screen 1 | screen 2 | screen 3 | screen 4 | brave://settings/search
------ | ----- | ----- | ------ | -----
![image](https://github.com/brave/brave-browser/assets/98358127/7dfbcbb4-46ad-4d40-91f6-4f90ac784475)|![image](https://github.com/brave/brave-browser/assets/98358127/0a034b0f-add7-4ea4-8233-d76f49bece2b)|![image](https://github.com/brave/brave-browser/assets/98358127/08c57c02-88ef-43a0-b8c4-693e8b50b6d5)|![image](https://github.com/brave/brave-browser/assets/98358127/3668813c-93fc-491d-a912-28ff9fc9771a)|![image](https://github.com/brave/brave-browser/assets/98358127/cbb88bcb-5b70-476d-a4f7-7016be3b9e3d)
</details>

<details>
<summary>New Profile:  clicked `May be later` button</summary> 

screen 1 | screen 2 | screen 3 | screen 4 | brave://settings/search
------ | ----- | ----- | ------ | -----
![image](https://github.com/brave/brave-browser/assets/98358127/28810bd6-3b62-4332-9957-1dd9a1190977)|![image](https://github.com/brave/brave-browser/assets/98358127/ffbf6a9a-a9a8-4fcc-9858-ef632353ce1c)|![image](https://github.com/brave/brave-browser/assets/98358127/c0a9df32-ed8d-443f-8cd3-fc9df563e852)|![image](https://github.com/brave/brave-browser/assets/98358127/fa879d14-64d4-49ed-a865-db773d7bbf0c)|![image](https://github.com/brave/brave-browser/assets/98358127/90bf3afa-5234-4656-82cb-35bf6074d275)
</details>

#### locale - `en-BR` (Portuguese)

<details>
<summary>New Profile:  clicked `Sure I'll help later` button</summary> 

screen 1 | screen 2 | screen 3 | screen 4 | brave://settings/search
------ | ----- | ----- | ------ | -----
![image](https://github.com/brave/brave-browser/assets/98358127/f906208a-df7a-40bc-896f-ef2ae5ba7c3e)|![image](https://github.com/brave/brave-browser/assets/98358127/e087ff1f-fb15-488e-bd10-d4674c61ea1a)|![image](https://github.com/brave/brave-browser/assets/98358127/320e63b8-8552-452e-8f6e-f692f9ac39ba)|![image](https://github.com/brave/brave-browser/assets/98358127/2fbb294d-d702-4be8-bd4c-337f0ba3c4ff)|![image](https://github.com/brave/brave-browser/assets/98358127/bfb92e97-1625-4072-95f4-4ff97e7dad76)
</details>

<details>
<summary>New Profile:  clicked `May be later` button</summary> 

screen 1 | screen 2 | screen 3 | screen 4 | brave://settings/search
------ | ----- | ----- | ------ | -----
![image](https://github.com/brave/brave-browser/assets/98358127/5d8b8ac7-289b-4a04-b1d4-65eaf3bbb4e6)|![image](https://github.com/brave/brave-browser/assets/98358127/f9da8c79-491b-4aaa-8de4-2ce1b7a50394)|![image](https://github.com/brave/brave-browser/assets/98358127/c7b5b41a-12bc-4e09-955d-767dae08aaea)|![image](https://github.com/brave/brave-browser/assets/98358127/6210a259-1219-439f-b7b8-83766bc07689)|![image](https://github.com/brave/brave-browser/assets/98358127/ac184c03-9af5-4320-8183-5cecb93edc61)
</details>

#### locale - `en-FR`  

<details>
<summary>New Profile:  clicked `Sure I'll help later` button</summary>

screen 1 | screen 2 | screen 3 | screen 4 | brave://settings/search
------ | ----- | ----- | ------ | -----
![image](https://github.com/brave/brave-browser/assets/98358127/d856fe1b-277a-4ff6-8fcd-91655dc8687e)|![image](https://github.com/brave/brave-browser/assets/98358127/ebbd91fb-c87f-4cec-965a-98b11f34a034)|![image](https://github.com/brave/brave-browser/assets/98358127/d2c756e7-d54d-44d6-b5e1-1536acd3346c)|![image](https://github.com/brave/brave-browser/assets/98358127/f8227305-83f9-43ac-9065-4b7415f74c9d)|![image](https://github.com/brave/brave-browser/assets/98358127/39eb9d36-4fcf-4f7f-8a2a-0a43067cccde)
</details>

<details>
<summary>New Profile:  clicked `May be later` button</summary> 

screen 1 | screen 2 | screen 3 | screen 4 | brave://settings/search
------ | ----- | ----- | ------ | -----
![image](https://github.com/brave/brave-browser/assets/98358127/22cadd8e-ae2a-4bd7-b6c8-715879fcdf94)|![image](https://github.com/brave/brave-browser/assets/98358127/f6aadce0-4a6e-4222-8e4d-5fcec49a8311)|![image](https://github.com/brave/brave-browser/assets/98358127/bece7cc8-a571-422b-8194-d990b4f9e430)|![image](https://github.com/brave/brave-browser/assets/98358127/baf32e90-a2a7-418d-be20-3f8a43e926bc)|![image](https://github.com/brave/brave-browser/assets/98358127/9d6c5939-acae-46fc-bced-581859775a27)
</details>
