### ISSUE TITLE
Store wallet's mnemonic only once in prefs

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#38011]

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.68.99 Chromium: 126.0.6478.126 (Official Build) beta (64-bit)
-- | --
Revision | 8ccc3a46e66d71dfd21506e1ccb42e08c7d33557
OS | Windows 11 Version 23H2 (Build 22631.3737)

- Verified steps from [brave/brave-core#23363](https://github.com/brave/brave-core/pull/23363)
- Verified wallet password works as expected 
- Verified upgrading from previous version still allows to unlock wallet using the same password

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.68.99 x64 Beta build
- Verified steps from [brave/brave-core#23363](https://github.com/brave/brave-core/pull/23363)
- Verified wallet password works as expected 
- Verified upgrading from previous version still allows to unlock wallet using the same password
