### ISSUE TITLE
Portfolio fails to load balance with console errors

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#38013]
## Description 

Portfolio fails to load balance with console errors

## Steps to Reproduce

   1. Unlock wallet/restore wallet
   2. Portfolio fails to load balance 
   3. Console throws error

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/6694c239-d06a-48f6-afb2-abdcca89e3c3

## Expected result:
Should not throw error and loads portfolio balance

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.66.97 Chromium: 124.0.6367.118 (Official Build) beta (64-bit)
-- | --
Revision | 94909f2aaefd7a8137c8b4fa27235378e79231e3
OS | Windows 11 Version 23H2 (Build 22631.3527)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @josheleonard @Douglashdaniel

**Comment by kjozwiak** [comment]
The above requires `1.65.130` or higher for `1.65.x` verification 👍
