### ISSUE TITLE
s23 Ultra - 'bottom tool bar'  not available

### ISSUE THREAD

**Issue by kristoffk15** [brave/brave-browser#38015]
I can use the new feature ‘bottom tool bar’ on my Samsung s20 - android 13.

BUT…

Not on my Samsung s23 Ultra -The option is not available in Settings>Apperance>

Im using the same version app on both devices with the only difference being my s23 ultra is on android 14.

Any ideas ?

**Comment by bsclifton** [comment]
Thanks for the recommendation! I'm going to close this as a duplicate - you can track the feature at https://github.com/brave/brave-browser/issues/7356 and subscribe for updates
