### ISSUE TITLE
Remove our Workaround for Arm64 Widevine on Windows

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#38012]
Google did not use to offer native Widevine binaries for Arm64 Windows. We therefore implemented a workaround in #28318 that still makes Widevine work in Arm64 Brave. Now, it seems that Google does offer native Arm64 Widevine binaries on Windows. The goal of this issue is therefore to remove our workaround, to simplify our code base and make it more future-proof with regards to upstream changes.

**Comment by MadhaviSeelam** [comment]
As per the testplan, this issue needs to be verified on macOS so adding OS/macOS label.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.67.85 Chromium: 125.0.6422.60 (Official Build) beta (arm64)
-- | --
Revision | d01060f5ec155e6eb64a335203663a29c0e5d81f
OS | Windows 11 Version 23H2 (Build 22631.3527)
```

**Comment by LaurenWags** [comment]
Removed `QA Pass-Win64` so this gets a Win x64 check as well

**Comment by stephendonner** [comment]
## Verification `PENDING` using 



### Widevine component details:
<details>

Confirmed via `brave://components` that `...` was downloaded, in all cases

`brave://components` | `WidevineCdm` folder
---------|---------


</details>

### Netflix - `PENDING`
<details>

### Steps:
1. installed `...`
2. launched Brave
3. loaded `netflix.com`
4. clicked on the `Sign In` link
5. entered my credentials
6. clicked on the `Sign In` button
7. confirmed I got prompted to `Install and run Widevine`
8. clicked `Allow`
9. clicked on my user avatar
10. played `Our Planet` (`https://www.netflix.com/watch/80094026`)

### Confirmed the content was streamed in High-Definition (HD) quality (through visual inspection)

`Widevine prompt` | `HD content`
-------------------|--------------




</details>


### Amazon Prime - `PENDING`
<details>

### Steps:

1. installed `...`
2. launched Brave
3. loaded `amazon.com`
4. clicked on `Prime Video`
5. logged in
6. confirmed I was prompted to `Install and run Widevine`
7. clicked on `Allow`
8. clicked to play `John Wick 3` - `https://www.amazon.com/gp/video/detail/B07SZZNFRM/ref=atv_hm_hom_c_lZOsi7_2_4?jic=8%7CEgNhbGw%3D`

### Confirmed the content was streamed in High-Definition (HD) quality, "Best" quality level @ `1080p` (6.48 GB per hour)

`Widevine prompt` | `HD content`
---------|---------




</details>

### HBOMax - `PENDING`
<details>

### Steps:
1. installed `1.52.94`
9. launched Brave
10. loaded `hbomax.com`
11. clicked on the `Sign In` button
12. clicked `Sign in to your account`
13. clicked `Sign in With a Provider` button
14. finally signed in
15. clicked on my username/avatar
16. confirmed I was prompted to `Install and run Widevine`
17. clicked on `Moonage Daydream`


### Confirmed the content was streamed in High-Definition (HD) quality, through visual inspection

`Widevine prompt` | `HD content`
-------------------|--------------

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.67.100 Chromium: 125.0.6422.112 (Official Build) beta (arm64)
-- | --
Revision | 34fcbb6655521b55468af6c63601a8e3c5d24cd2
OS | macOS Version 13.6.4 (Build 22G513)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.67.100 Chromium: 125.0.6422.112 (Official Build) beta (64-bit)
-- | --
Revision | 34fcbb6655521b55468af6c63601a8e3c5d24cd2
OS | Windows 10 Version 22H2 (Build 19045.4474)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.67.100 Chromium: 125.0.6422.112 (Official Build) beta (64-bit)
-- | --
Revision | 34fcbb6655521b55468af6c63601a8e3c5d24cd2
OS | Windows 11 Version 23H2 (Build 22631.3672)
```

### Widevine component details - `PASSED`
<details>

Confirmed via `brave://components` that `Widevine Content Decryption Module - Version: Version: 4.10.2710.0` was downloaded, in all cases

`brave://components` | `WidevineCdm` folder
---------|---------
![image](https://github.com/brave/brave-browser/assets/98358127/ded735ab-ea24-416c-bc07-81102a08ee28)|![image](https://github.com/brave/brave-browser/assets/98358127/bb88d62a-7bf2-44d2-a5d5-b32befc1accc)

</details>

### Netflix - `PASSED`
<details>

### Steps:
1. installed `1.67.100`
2. launched Brave
3. loaded `netflix.com`
4. clicked on the `Sign In` link
5. entered my credentials
6. clicked on the `Sign In` button
7. confirmed I got prompted to `Install and run Widevine`
8. clicked `Allow`
9. clicked on my user avatar
10. played `Life in Color with David Attenborough` (`https://www.netflix.com/watch/81094026?trackId=255824129`)

### Confirmed the content was streamed in High-Definition (HD) quality (through visual inspection)

`Widevine prompt` | `HD content`
-------------------|--------------
![image](https://github.com/brave/brave-browser/assets/98358127/5d0b425c-110c-4674-91d7-aebbfcc28948)|![image](https://github.com/brave/brave-browser/assets/98358127/332e9e61-f32b-4af9-8cfb-07a220dab9da)


</details>

### Amazon Prime - `PASSED`
<details>

### Steps:

1. installed `1.67.100 `
2. launched Brave
3. loaded `amazon.com`
4. clicked on `Prime Video`
5. logged in
6. confirmed I was prompted to `Install and run Widevine`
7. clicked on `Allow`
8. clicked to play `National Parks Exploration Series: Yellowstone` 
(https://www.amazon.com/National-Parks-Exploration-Yellowstone-various/dp/B07B6BQYNN/ref=sr_1_2?s=instant-video&sr=1-2)

### Confirmed the content was streamed in High-Definition (HD) quality, "Best" quality level @ `1080p` (6.84 GB per hour)

`Widevine prompt` | `HD content`
---------|---------
![image](https://github.com/brave/brave-browser/assets/98358127/2cbe0134-eb7b-409e-82bb-97bcf5c383f2)|![image](https://github.com/brave/brave-browser/assets/98358127/257e5278-d74b-40ed-9b45-da7088084007)

</details>

### HBOMax - `PASSED`
<details>

### Steps:
1. installed `1.67.100 `
9. launched Brave
10. loaded `hbomax.com`
11. clicked on the `Sign In` button
12. clicked `Sign in to your account`
13. clicked `Sign in With a Provider` button
14. finally signed in
15. clicked on my username/avatar
16. confirmed I was prompted to `Install and run Widevine`
17. clicked on `Alvin and the Chipmunks: The Squeakquel`
(https://play.max.com/video/watch/6690a829-eef6-4af0-93d9-1ce0c7d2cfed/9880f891-795b-4402-a434-bf28f69734a7)

### Confirmed the content was streamed in High-Definition (HD) quality, through visual inspection

`Widevine prompt` | `HD content`
-------------------|--------------
![image](https://github.com/brave/brave-browser/assets/98358127/d01980e4-c105-4626-bdcf-883de6af81f1)|![image](https://github.com/brave/brave-browser/assets/98358127/49caab40-7119-4396-a87e-4fb72d4cec76)

</details>

### Bitmovin.com - `PASSED` 
<details>

1. Installed `1.67.100 `
2. launched Brave
3. visit https://bitmovin.com/demos/drm in a new tab page
4. confirmed I got prompted to `Install and run Widevine`
5. clicked Allow
6. played the video for protected DRM stream
7. opened brave://components
8. confirmed `Widevine Content Decryption Module`  is loaded
9. confirmed  widevinecdm_proxy.dll is loaded when Widevine is installed

### Confirmed the content was streamed in High-Definition (HD) quality (through visual inspection)

step 4 | step 6
---- | ---- 
![image](https://github.com/brave/brave-browser/assets/98358127/593fb3a1-55d9-43cf-ae2b-1cff6e58d10b)|![image](https://github.com/brave/brave-browser/assets/98358127/11d99640-a828-4062-b792-26cdb04d4b09)

</details>
