### ISSUE TITLE
Renderer-side changes for improved performance related to adblocking

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#38029]
For adblocking features such as https://github.com/brave/brave-browser/issues/33881 and https://github.com/brave/brave-browser/issues/16935, we need to inject JS into the page. This can often have an adverse effect on the perf of the page, especially if we're inserting MutationObservers into the page. There's some renderer changes we can make to improve perf for these features.

**Comment by petemill** [comment]
@iefremov can you elaborate on what the plan would be to make MutationObservers more performant?

**Comment by iefremov** [comment]
After re-reading slack and the tickets, I think there was a misunderstanding. What I said in DM with shivan/goodov was that Aleksey can actually pick up the original task as an implementor, I didn't have any specific changes in mind (until the JS part is implemented).
