### ISSUE TITLE
How do I download the offline installation package？

### ISSUE THREAD

**Issue by rLry** [brave/brave-browser#3803]

**Comment by Techguyprivate** [comment]
For windows or linux. You didn't specify anything. Are you talking about standalone setups to install for later or for people who have slow connections or anything else? They are available at  github releases and also at brave.com .

https://brave.com/download/

https://github.com/brave/brave-browser/releases

**Comment by bsclifton** [comment]
@rLry using the link that @Techguyprivate shared, you can find the full packages that should work great for offline install. There's even a silent installer, so you can automate the install if needed

Our latest stable release is 0.61.51 which you can find here:
https://github.com/brave/brave-browser/releases/tag/v0.61.51

The installers you'd be interested in:
- `BraveBrowserStandaloneSetup.exe` - offline installer for 64 bit Windows
- `BraveBrowserStandaloneSilentSetup.exe` offline installer that doesn't show any UI. Great choice for automating the install on a corporate network

(and of course there are 32 bit versions of the above)

For macOS, you can use the .PKG format:
- `Brave-Browser.pkg`

For automating installs, you can use `pkgutil` to extract the items and then move it into place.  The Linux packages are on that releases page too

Hope this helps 😄
