### ISSUE TITLE
[Android] Wrong menu position on Custom Tabs

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#38044]
## Description 
Wrong menu position on Custom Tabs
![Screenshot_20240503-081407](https://github.com/brave/brave-browser/assets/30602739/2f4a9652-8812-41e8-acf8-61cfddf9aabc)

## Steps to reproduce 

   1. Open link in Cutom Tab form the other app (like Gmail)
   2. Click menu
   3. Menu in on bottom

## Actual result 
Menu in on bottom

## Expected result
Menu in on top

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240426.022 release-keys
Brave build: 1.67.85 
Chromium: 125.0.6422.60 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/38044#issue-2277571196
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the menu is opened in the right place on top when Custom tab/Webview is used

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/95e71a3d-3a13-41e4-b4df-fa82271139b0) | ![2](https://github.com/brave/brave-browser/assets/128532965/987eebf5-1128-4d80-b491-7ab7493bf2f0) |
