### ISSUE TITLE
Can not add a page to top sites

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3805]
Top sites are always empty on clean profile

## Steps to Reproduce

   1. Clean profile
   2. Add page to top sites (I used `youtube.com`, `interia.pl`)

## Actual result:

page in not added to top sites
Top sites are always empty

Possible regression due to https://github.com/brave/brave-browser/issues/3710

![image](https://user-images.githubusercontent.com/34715963/54681722-60ab2e00-4b0d-11e9-8e34-65dca7eae5c7.png)

## Expected result:
page is added to top sites

![image](https://user-images.githubusercontent.com/34715963/54681368-753af680-4b0c-11e9-9781-fadd25dfa312.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

**Reproduced on** 

Brave | 0.62.32 Chromium: 73.0.3683.75 (Official Build) beta (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Ubuntu 18.04 LTS

**Not reproducible on**

Brave | 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

cc @brave/legacy_qa @cezaraugusto

**Comment by GeetaSarvadnya** [comment]
Reproducible on Windows 10 x64 - 0.63.4

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

**Comment by LaurenWags** [comment]
Reproduced on macOS

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

**Comment by kjozwiak** [comment]
@rebron we should probably fix this for `0.62.x` as it's a regressions. Top sites aren't being added onto the NTP. Labelling this as P2 for now. If you feel differently, please re-assign priority.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.62.49 Chromium: 73.0.3683.86 (Official Build) (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Windows 10 OS Build 17134.523



- Verified the STR mentioned in the description

![image](https://user-images.githubusercontent.com/38657976/55311293-22ecc480-5480-11e9-9216-5ab027135878.png)
