### ISSUE TITLE
[ads] db error: 1299/NOT NULL constraint failed: creative_ads.creative_instance_id

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#38050]
https://brave.sp.backtrace.io/p/brave/triage?time=all&filters=JTVCJTVCJTIyQnJhdmVBZHNTcWxEaWFnbm9zdGljSW5mby12YWx1ZSUyMiUyQyUyMmNvbnRhaW5zJTIyJTJDJTIyZGIlMjBlcnJvciUzQSUyMDEyOTklMkZOT1QlMjBOVUxMJTIwY29uc3RyYWludCUyMGZhaWxlZCUzQSUyMGNyZWF0aXZlX2Fkcy5jcmVhdGl2ZV9pbnN0YW5jZV9pZCUyMiU1RCU1RA%3D%3D&aggregations=((guid%2Cunique)%2C(classifiers%2Chead))&similarity=false

**Comment by btlechowski** [comment]
Verified with

Brave | 1.67.110 Chromium: 126.0.6478.40 (Official Build) (64-bit)
-- | --
Revision | ac00bac697a2d9dad0b2e7f832391263816fd78d
OS | Linux


Verified ads with empty creative instance id are not saved into db

<details>


</details>
