### ISSUE TITLE
Unsolicited connections to Google made, when using a custom `DNS-Over-HTTPS` config

### ISSUE THREAD

**Issue by Retold3202** [brave/brave-browser#38058]
## Description 
If the Secure DNS feature is enabled on Brave, Brave connects to `www.gstatic.com` and `google.com`. A connection is then made to `www.gstatic.com` on every launch of the browser, and at other times as well.

## Steps to Reproduce

   1. Enable Secure DNS.
   2. Select "Choose another provider" and configure the provider of your choice. (I used NextDNS)
   3. Brave connects to `www.gstatic.com` and `google.com`.

Update: see https://github.com/brave/brave-browser/issues/38058#issuecomment-2118199829 for the testplan w/steps

## Actual result:

Brave connects to Google.

![brave-issue](https://github.com/brave/brave-browser/assets/132830388/e8797d94-3a34-470d-a623-0836645b003a)

## Expected result:
Brave should not make unsolicited connections to Google in this way.

## Reproduces how often: 

Very easy to reproduce, I was able to replicate the issue on macOS, Fedora Linux, and Android (GrapheneOS). 

## Desktop Brave version:

v1.65.126

## Android Device details:
   - ARM
   - Phone
   - Android 14 (GrapheneOS)

## Version/Channel Information:

- Can you reproduce this issue with the current release? ✅
- Can you reproduce this issue with the beta channel? ✅
- Can you reproduce this issue with the nightly channel? ✅

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? ❌
- Does the issue resolve itself when disabling Brave Rewards? ❌
- Is the issue reproducible on the latest version of Chrome? ✅ (By design, N/A)

**Comment by diracdeltas** [comment]
cc @arthuredelstein

**Comment by ShivanKaul** [comment]
@Retold3202 can you tell us the custom DoH query URL you put into Secure DNS? I wasn't able to repro but would be useful to know exactly what you were doing when you saw the requests.

**Comment by LaurenWags** [comment]
Wasn't able to reproduce using `1.65.126` (version referenced in issue description). Also tried with `1.66.110` (current release channel version).  Here are the steps I used:

1. Removed existing profile for Release channel 
2. Launched Fiddler Everywhere or Wireshark
3. Launched version specified in issue (1.65.126) with a completely clean profile without any data and was using standard settings.
4. Watched Fiddler Everywhere and/or Wireshark for connections to `google.com` or `gstatic.com` --> no connections observed (waited for ~5 min after launching)
5. Navigated to brave://settings/security. Note, here "Use secure DNS" is enabled by default so I did not need to enable it.
6. I changed "Select DNS provider" from "OS default" (default setting) to "NextDNS"
7. Saw that in Wireshark there were connections to `chromium.dns.nextdns.io` after making this change. I didn't see anything in Fiddler when using their standard System Proxy config. However, if I used their Network Capture (Beta) option, then I could see the same connections. There were no connections to `google.com` or `gstatic.com`:

Wireshark | Fiddler Network Capture
--- | ---
![ws- change to nextdns 1 65 126](https://github.com/brave/brave-browser/assets/28145373/7ab74bbd-79b8-4bf4-b60d-51c72caccc33) | ![fid - change to nextdns](https://github.com/brave/brave-browser/assets/28145373/6a8ec841-0839-4f56-9c1e-756781a75620)

8. Closed/relaunched the browser to see if this connection was made on each launch. Still did not see any connections to `google.com` or `gstatic.com` but the connections to `chromium.dns.nextdns.io` still occurred:

Wireshark | Fiddler Network Capture
--- | ---
![ws - relaunch with nextdns 1 65 126](https://github.com/brave/brave-browser/assets/28145373/cfdcaedd-e6da-4348-8ef8-51577b8d019a) | ![fid - relaunch with nextdns](https://github.com/brave/brave-browser/assets/28145373/bb06fd91-1458-4de1-b41a-95ee4e8992a3)

**Comment by stephendonner** [comment]
> @LaurenWags @stephendonner

<SNIP>

> I just tried and I was able to replicate this with Adguard, NextDNS, and ControlD. I also recorded it as well to show the exact steps I took. I would post the videos here, but I'm unable to as the size is too large for GitHub (like 25mb each). What would be the best way for me to show these? I think this would probably help repro.

Thanks for sticking with us and being patient, @Retold3202 - you could publish the video to `Google Drive` or `Dropbox` or `Box.com` (or similar), and share it via their provided public-viewable-permissions-settings link, as an option.  Then just give us the link here and we'll check it out.

**Comment by stephendonner** [comment]
To confirm @Retold3202 are you populating this textfield in Brave using the option from logged-in `NextDNS.com` session?

![image](https://github.com/brave/brave-browser/assets/387249/b99f22be-4fd9-4459-a0c2-3421107e0c51)



Specifically, the DNS-over-HTTPS value?

![image](https://github.com/brave/brave-browser/assets/387249/505dd509-51a6-425b-8d99-7a5bb7263b3e)

**Comment by stephendonner** [comment]
UPDATE: was able to reproduce at-will, using

```
Brave | 1.67.85 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | d01060f5ec155e6eb64a335203663a29c0e5d81f
OS | Windows 10 Version 22H2 (Build 19045.4412)
```

### Steps:
1. installed `1.67.85`
2. launched `Microsoft Edge` with blank content/new-tab pages, and only loaded `NextDNS.com` to get a logged-in session
3. opened `nextdns.com` and clicked on `Settings`
4. copied the `NextDNS.com`-provided `DNS-over-HTTTPS` config string/URI (in my case, that's `https://dns.nextdns.io/d82499` from the above post's screenshot)
5. opened `brave://settings/security`
6. chose `Use custom DNS provider` from `Select DNS provider`/`Use Secure DNS`, and pasted in `https://dns.nextdns.io/d82499`
7. watched logs on `NextDNS.com`

### Confirmed I saw calls to `google.com` and `www.gstatic.com`, in that order

example | example
----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/a85c2310-7195-464a-9857-01c39c9268de) | NextDNS log screenshot

**Comment by ShivanKaul** [comment]
Hi folks, sorry for the delay here, I wanted to dig into why I couldn't see the connections to gstatic/google in Wireshark but you all saw it in the DNS logs. 

The answer is that Brave is not actually connecting to gstatic.com or google.com. When you choose a custom DoH provider, Chromium does an A query via DoH for google.com and gstatic.com to your new DoH provider. **This however does not cause Brave to actually connect to those domains**, it's simply a DNS probe. gstatic.com or google.com do not get your IP address. This is why you see it on the NextDNS logs, and I was able to see it in Wireshark once I decrypted the DoH TLS packets. 

If anything, if we modified gstatic.com to point to brave.com or something, we would leak the fact that you're a Brave user to your DoH provider.

**Comment by ShivanKaul** [comment]
> Is there any other potential data that could be leaked? I guess its just a bit discomforting seeing this "connection" to Google, but its relieving to hear its at least not leaking IP address.

Right, the key thing here is that it's not actually a connection to Google.

> Isn't this already obvious to the DoH provider due to other connections Brave already makes (like for updates, rewards, news, variations, safe browsing, etc)? I feel like it might be nice to change this just for the extra peace of mind, as long as doing so doesn't actually compromise privacy or have any downsides.

True, a DoH provider can see all your traffic (which is why it's so important to pick one with a good privacy posture) and very quickly determine that you're a Brave user anyway. It's definitely not a privacy goal to hide that. It's a fair point that we might want to change this to a Brave domain anyway, but every change we make to Chromium has a maintenance cost and I suspect in this case it'll have to be a [patch](https://github.com/brave/brave-browser/wiki/Patching-Chromium#patch-the-chromium-files). I opened https://github.com/brave/brave-browser/issues/38555 to keep track of this. 

Thanks for reporting this! Was interesting to repro. I'll go ahead and close this issue given that it is not actually an unsolicited connection to Google, and we can continue conversation on the other issue.
