### ISSUE TITLE
[ads] db error: 1/sql::Database is not opened.

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#38052]
https://brave.sp.backtrace.io/p/brave/triage?time=all&filters=JTVCJTVCJTIyQnJhdmVBZHNTcWxEaWFnbm9zdGljSW5mby12YWx1ZSUyMiUyQyUyMmNvbnRhaW5zJTIyJTJDJTIyZGIlMjBlcnJvciUzQSUyMDElMkYlMjIlNUQlNUQ%3D&aggregations=((guid%2Cunique)%2C(classifiers%2Chead))&similarity=false

**Comment by tmancey** [comment]
Occurs when trying to recover a corrupt database and executing new database transactions while the database is closed. Closing issue as working as expected.
