### ISSUE TITLE
[Follow up to #36465] YT `Shorts` is not removed by the `swiping down` method when refreshing the page while YT is in `Desktop mode`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#38059]
## Description 

Follow-up to #36465

## Steps to reproduce 

   1. Launch Brave (phone or tablet)
   2. Go to www.youtube.com
   3. Three-dot menu > *Confirm that `Desktop site` is ON, if not, enable it*
   4. *Confirm that `Shorts` are shown on the `Home` tab, `Trending` tab or in the `search results` tab*
   5. Three-dot menu > Settings > Media
   6. Turn on the `Block YouTube Shorts` toggle switch > Close the settings
   7. Refresh the YT page by swiping down in the middle of the screen with your finger > *Observe that `Shorts` are not removed*
   8. Now refresh the YT page by tapping Brave's `Refresh` button > *Confirm that `Shorts` are removed now*

OR

   1. Launch Brave (phone or tablet)
   2. Go to www.youtube.com
   3. Three-dot menu > *Confirm that `Desktop site` is ON, if not, enable it*
   4. *Confirm that `Shorts` are shown on the `Home` tab, `Trending` tab or in the `search results` tab*
   5. Open `NTP`
   6. Three-dot menu > Settings > Media
   7. Turn on the `Block YouTube Shorts` toggle switch > Close the settings
   8. Go to www.youtube.com on `NTP` > *Confirm that `Shorts` are not shown*
   9. Go back to the first YT tab
   10. Refresh the page by swiping down in the middle of the screen with your finger > *Observe that `Shorts` are not removed*
   11. Now refresh the YT page by tapping Brave's `Refresh` button > *Confirm that `Shorts` are removed now*

## Actual result 

YT `Shorts` is not removed by the `swiping down` method when refreshing the page while YT is in `Desktop mode`.

https://github.com/brave/brave-browser/assets/128532965/24e4a763-bbc9-4161-9ecc-dbde8513968f

https://github.com/brave/brave-browser/assets/128532965/5c110219-c49b-43a1-9111-bb0986fea13f

## Expected result

YT `Shorts` must be removed on the `Home`, `Trending` or `Search results` tab when refreshing the page using any method (`Refresh` button or `Swipe down`) while YT is in `Desktop` or `Mobile` mode.

## Issue reproduces how often 

`Easily reproduced`

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? N/A
- Can you reproduce this issue with the current Play Store Beta version? YES
- Can you reproduce this issue with the current Play Store Nightly version? YES 

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Galaxy Tab S8 or Pixel 7
   - Android version: Android 14 and Android 15
   
## Brave version

```
Brave build: 1.66.97
Chromium: 124.0.6367.118 (Official Build) beta (64-bit)
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @deeppandya

**Comment by ryanbr** [comment]
Want to check this again @hffvld is it fixed?

**Comment by hffvld** [comment]
I checked the latest Nightly `1.67.70` and it looks like the same behavior exists. There are <ins>3 methods</ins> to refresh the page:
- Full refresh by tapping the `Refresh` button
- Full refresh by `swiping down` in the `upper part` of the YT page
- Just the content refresh without refreshing the whole page by `swiping down` in the `middle of the page`

`Shorts` presence is not changed when using the third method as before.

**Comment by ryanbr** [comment]
From my testing in Galaxy Tab; https://www.youtube.com/watch?v=EaMI2bc2zCw

I'm seeing no shorts after scrolling, with shields up.

**Comment by deeppandya** [comment]
@hffvld i tried the steps on 1.67.73. and it seems to be working as expected. only thing i noticed is that if desktop mode is enabled, it still shows `Shorts` in the left panel menu. Would you please add a recording if you can still reproduce the issue for more context ?

**Comment by hffvld** [comment]
I checked it again on `Galaxy Tab S8` & `Pixel 7` with Brave Nightly `1.67.77` and still see the same issue. It's possible to refresh the `whole YT page` and `just the content on the page`. In first case you'll see an `orange` refresh spinner, in the second case you'll see a `white` refresh spinner.

|Whole page refresh|Content refresh|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/ddda157e-7c17-4ce6-9cef-6af34ec4d202) | ![2](https://github.com/brave/brave-browser/assets/128532965/1b8bc546-ef7a-4226-b3d8-4e04fd5db019) |

I feel that customrs who uses a tablet will be more affected then these who uses a phone, because this issue is happening only in `Desktop view` which is ON on the <ins>tablet</ins>, but OFF on the <ins>phone</ins> by `default`

https://github.com/brave/brave-browser/assets/128532965/d4835190-5af1-4820-9243-a1eda6aba44d

https://github.com/brave/brave-browser/assets/128532965/82f8a6a7-e322-4e23-a22a-ae4061134c0e

I talked to @deeppandya and we agreed that we can explicitly ask user to `relaunch` Brave as we do for some of the other features like `Widevine DRM` or `Enable bottom bar`, for example. This way we'll be on a safe side and know for sure that the changes are applied.

*Example for `Widevine DRM`*

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/62ff9d38-9d54-44fd-beb8-ce48fc0ae976) | ![2](https://github.com/brave/brave-browser/assets/128532965/1a885e29-ac61-4268-9204-b3e48eb31a91) |

cc @kjozwiak @Uni-verse

**Comment by deeppandya** [comment]
@hffvld i have added the relaunch here : https://github.com/brave/brave-core/pull/23523.

**Comment by kjozwiak** [comment]
The above requires `1.66.105` or higher for `1.66.x` verification 👍

**Comment by saksham-81** [comment]
![Screenshot_2024-05-10-20-35-47-136_com brave browser](https://github.com/brave/brave-browser/assets/157354265/d3f16ce5-9df9-4c74-8350-27e0c28e76e7)
@ryanbr 
Version: 1.66.104

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 14 AP31.240322.023 release-keys
Brave build: 1.66.105
Chromium: 125.0.6422.41 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Launch Brave `1.66.105` or newer
2. Go to www.youtube.com > *Confirm that `Shorts` are shown on the `Home`, `Trending` and `Search` tab*
3. Three-dot menu > Settings > Media
4. Block YouTube Shorts > Enable it > Relaunch now
5. *Verify*

**ACTUAL RESULTS:**
- Verified that `Shorts` are not shown on the `Home`, `Trending` and `Search` tabs when `Block YouTube Shorts` toggle switch is ON
- Verified that pop-up message saying that changes will be applied after Brave relaunch is shown when toggling `Block YouTube Shorts` ON or OFF 
- Verified that `Shorts` are not shown in both `Mobile` and `Desktop` view when `Block YouTube Shorts` is ON

---------------------------

<details>
<summary> Galaxy Tab S8 </summary>

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>

<details>
<summary> Pixel 7 </summary>

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |

</details>

**Comment by kaif-00z** [comment]
Unable To Find This Option In Brave Desktop Version v1.73.104
