### ISSUE TITLE
Truncate long token names and balances

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#38064]
## Description 

We need to truncate long token `Names` and `Balances` in the `Select Token` modal when needed.

![Screenshot 25](https://github.com/brave/brave-browser/assets/40611140/f7b0f0eb-ff33-441f-a494-bdfa63c59641)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.68.84 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | c5a3b2ff9dcc938c32b2c1b3a66847661db5d005
OS | Windows 11 Version 23H2 (Build 22631.3672)

- Verified steps from [brave/brave-core#23648](https://github.com/brave/brave-core/pull/23648)
- Verified long token names are truncated in the panel

Swap | Send
-- | --
<img width="1920" alt="brave_b9y91ze9QB" src="https://github.com/brave/brave-browser/assets/17010094/ae36b106-ea2b-485c-ae56-54d2e133cd8c"> | <img width="1920" alt="brave_ZQ02ciM4NV" src="https://github.com/brave/brave-browser/assets/17010094/2ab50bde-74a1-46b4-b682-6724c3cc1728">
