### ISSUE TITLE
`brave://version/` does not show link to `brave://rewards-internals/`

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3806]
Follow up to https://github.com/brave/brave-browser/issues/1174

## Steps to Reproduce

   1. Clean install
   2. Enable rewards though Brave Panel
   3. Open `brave://version/` in a new tab

## Actual result:

There is no link to `brave://rewards-internals/`
![image](https://user-images.githubusercontent.com/34715963/54682488-5be77980-4b0f-11e9-91dd-a4079c4f064f.png)

## Expected result:
![image](https://user-images.githubusercontent.com/34715963/54682529-74f02a80-4b0f-11e9-8172-8661aa69d0bf.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

cc @brave/legacy_qa @emerick

**Comment by NejcZdovc** [comment]
closing as we decided to not add it there. This is an issue that tracks where we want to place it hub.com/brave/brave-browser/issues/3538

**Comment by kjozwiak** [comment]
@btlechowski some more context if you're interested:

@bridiver mentioned that adding it into `brave://version` would require a lot of patching via https://github.com/brave/brave-browser/issues/1174#issuecomment-468514005. @bbondy confirmed via https://github.com/brave/brave-browser/issues/1174#issuecomment-468530508. So we ended up creating https://github.com/brave/brave-browser/issues/3538 to figure out where we should place the link so users have easy access.
