### ISSUE TITLE
Brave shares fingerprint across different profiles

### ISSUE THREAD

**Issue by anon88391** [brave/brave-browser#38067]
## Description 
When using different profiles in Brave, most if not all unique browser properties (for example: the canvas fingerprint, font list, audio properties) are identical across profiles. This makes the profiles cross-fingerprintable, which is probably undesirable as the user may use the same website through in profiles and their activity will point to the same, unique device beyond any doubt.

## Steps to Reproduce

  1. Start Brave in any profile.
  2. Create and simultaneously open any new profile.
  3. Go to https://browserleaks.com/canvas , https://browserleaks.com/fonts and/or https://browserleaks.com/webgl in both profiles and compare the fingerprint signatures in each page. Optionally use any other fingerprinting websites and compare fingerprints - most unique properties will be identical.
  4. (Optional) Note down the fingerprint, close Brave and repeat steps 1-3. The fingerprint will change after restart, but be identical in both profiles.

## Actual result:
Very unique, fingerprintable properties remain identical across profiles.
![screenshot](https://github.com/brave/brave-browser/assets/35631947/4b88d398-2b49-4479-b447-189e0b211114)

## Expected result:
Very unique, fingerprintable properties should be different across profiles to prevent cross-profile fingerprinting and giving away the information that the user is accessing the website on the same device.

## Reproduces how often: 

Easily reproduced 100% of the time

## Version/Channel Information:

Version 1.65.126 Chromium: 124.0.6367.118 (Official Build) (64-bit)

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? didn't check
- Can you reproduce this issue with the nightly channel? didn't check

## Other Additional Information:
I have only tested this on the desktop version of Brave.
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Doesn't apply

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.70.93 Chromium: 128.0.6613.85 (Official Build) beta (x86_64)
-- | --
Revision | d5947d34ee18f45238e77a82783306862f678ac6
OS | macOS Version 13.6.9 (Build 22G830)
```

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.70.100 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | c30694e8a60583be9d1784e4d42b4a0b94c70ab5
OS | Windows 10 Version 22H2 (Build 19045.4780)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.70.109 Chromium: 128.0.6613.138 (Official Build) beta (64-bit) 
Revision	fec4422ae56f4d9680c71a3c1de60b9a8e5ef32f
OS	Linux
```

Reproduced with `1.69.168 Chromium: 128.0.6613.138`

Profile 1 | Profile 2
------ | -----
![image](https://github.com/user-attachments/assets/eebfd6c4-90e7-4144-ade3-43af4e93f9c3)|![image](https://github.com/user-attachments/assets/8417e4d4-0a76-41e9-8407-d0cec7388ab9)
![image](https://github.com/user-attachments/assets/5a9a2f79-5177-48ab-9601-0c35da005386)|![image](https://github.com/user-attachments/assets/f2cee230-708a-4649-9e6e-12928984d848)
![image](https://github.com/user-attachments/assets/88124e6e-acf2-4145-b48b-2f944e5e3b7a)|![image](https://github.com/user-attachments/assets/c475db97-d23d-4bf6-8460-dea3b320c3b3)


Using same STR and 1.70.109 Chromium: 128.0.6613.120, confirmed `Canvas` and `WebGL` fingerprints are different between profiles. 
`Font` fingerprint is the same, encountered the issue https://github.com/brave/brave-browser/issues/40736.

Profile 1| Profile 2
-----  | -----
![image](https://github.com/user-attachments/assets/260e9ed3-48d1-4427-a72b-e4190442b08a)|![image](https://github.com/user-attachments/assets/5df50b31-9115-49d9-b5cb-d4a112a65db6)
![image](https://github.com/user-attachments/assets/6923474b-c17f-4548-9c89-612cc1d1c1f5)|![image](https://github.com/user-attachments/assets/f7e40d97-c16a-428d-9040-4a97540bc041)
![image](https://github.com/user-attachments/assets/953b8aa7-7499-4fe2-9849-df1c9c7d922e)|![image](https://github.com/user-attachments/assets/549ef48a-961a-467c-bd57-ef15366fb98c)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.70.107 Chromium: 128.0.6613.120 (Official Build) beta (64-bit) 
Revision	ab3f504ca4a15c330f60a93d5e3773d780498980
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that fingerprinting is enabled for the following test pages: 
   - [x] https://browserleaks.com/canvas
   - [x] https://browserleaks.com/fonts
   - [x] https://browserleaks.com/webgl
   
**`canvas`** | **`fonts`** | **`webgl`**
---|---|---
![Screenshot 2024-09-13 at 2 17 24 PM](https://github.com/user-attachments/assets/35be024f-0fc2-4fb0-a50a-9cedc3e68d1e) | ![Screenshot 2024-09-13 at 2 18 12 PM](https://github.com/user-attachments/assets/e9b9c9e1-acf5-4c26-9ac2-c82b836dd7db) | ![Screenshot 2024-09-13 at 2 19 01 PM](https://github.com/user-attachments/assets/9eb0f105-c036-4693-9257-55f62f6f7665)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using version: 

```
Brave	1.70.107 Chromium: 128.0.6613.120 (Official Build) beta (64-bit) 
Revision	ab3f504ca4a15c330f60a93d5e3773d780498980
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that fingerprinting is enabled for the following test pages: 
   - [x] https://browserleaks.com/canvas
   - [x] https://browserleaks.com/fonts
   - [x] https://browserleaks.com/webgl
   - [x] https://dev-pages.brave.software/fingerprinting/farbling.html
   
**`canvas`** | **`fonts`** | **`webgl`** | **`farbling test page`**
---|---|---|---
<img width="736" alt="Screenshot 2024-09-13 at 5 21 31 PM" src="https://github.com/user-attachments/assets/ccec5e25-b703-4ade-9b93-16e3e33dd9d5"> | <img width="736" alt="Screenshot 2024-09-13 at 5 21 31 PM" src="https://github.com/user-attachments/assets/ccec5e25-b703-4ade-9b93-16e3e33dd9d5"> | <img width="736" alt="Screenshot 2024-09-13 at 5 21 53 PM" src="https://github.com/user-attachments/assets/57b8ec99-9a19-4138-94d3-5683e15bf70d"> | <img width="736" alt="Screenshot 2024-09-13 at 5 34 03 PM" src="https://github.com/user-attachments/assets/60e896c0-f11b-4f03-9d10-67139bfdfb24">
