### ISSUE TITLE
Replace Llama 2 with Llama 3 as an AI model

### ISSUE THREAD

**Issue by I-I-IT** [brave/brave-browser#38071]
This seems obvious, but haven't seem an issue about adding the new more accurate and more responsive [Meta Llama 3 8b ](https://llama.meta.com/llama3/ )as a the unlimited model to replace Llama 2 13b. Llama 3 8b is better than even Llama 2 70b, according to [Arena LMSYS leaderboard](https://chat.lmsys.org/?leaderboard)<

## Test plan

All llama2 strings now use llama3. Query functionality still works with the llama model selection.

**Comment by mattmcalister** [comment]
Thanks @TechFanTheo . It is indeed coming and we need an issue for it.

**Comment by kjozwiak** [comment]
The above requires `1.67.105` or higher for `1.67.x` verification 👍

**Comment by I-I-IT** [comment]
I have latest Nightly and tested it. Says Connection error with Llama 3 but it works fine with other models.

Did you enable the Llama 3 servers yet ?
![VideoCapture_20240603-192613](https://github.com/brave/brave-browser/assets/78900789/ccb76588-cbfd-487c-bec9-bea3430a2122)
![VideoCapture_20240603-192622](https://github.com/brave/brave-browser/assets/78900789/c7f29fb8-2603-40de-8751-f9d5264c9c3a)
![VideoCapture_20240603-192633](https://github.com/brave/brave-browser/assets/78900789/3c480cf1-9479-428f-9529-ef944822346c)
![VideoCapture_20240603-192641](https://github.com/brave/brave-browser/assets/78900789/ca0de12c-3091-448c-bc2b-c5350b4ff9a4)
![VideoCapture_20240603-192644](https://github.com/brave/brave-browser/assets/78900789/7aadc287-1255-4d3a-bd67-ab077b40b675)

**Comment by I-I-IT** [comment]
Fixed.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.67.107 Chromium: 126.0.6478.26 (Official Build) beta (x86_64)
-- | --
Revision | 2831369c7540d93e98f38d9b463f6762430a7982
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by Uni-verse** [comment]
In progress on Samsung Galaxy S21 using version 1.66.120

**Comment by kjozwiak** [comment]
The above requires `1.67.121` or higher for `1.67.x` verification on `iOS` 👍 CCing @hffvld @Uni-verse
