### ISSUE TITLE
Unable to import Crypto Wallets during new onboarding

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#38074]
## Description 

Unable to import Crypto Wallets during new onboarding

## Steps to Reproduce

   1. Enable Crypto Wallets via flag and set default Ethereum to `Crypto Wallets (depricated`
   2. Create Crypto Wallet after component is downloaded
   3. Set default to `Extensions (Brave Wallet fallback)`
   4. Initiate onboarding and select `Already have a wallet`
   5. Continue onboarding doesn't detect Deprecated wallet
   6. Repeat same steps with MetaMask
   7. Detects Metamask for import

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/2a8577b6-9bb1-441a-9af8-3ec1c97d944b

## Expected result:
Should show similar to MM import
<img width="1920" alt="MM Import" src="https://github.com/brave/brave-browser/assets/17010094/3a049e85-d518-472f-b7bf-8702736571c1">

## Reproduces how often: 

Easy

## Brave version (brave://version info)

 
Brave | 1.67.69 Chromium: 125.0.6422.26 (Official Build) nightly (64-bit)
-- | --
Revision | 3ac44647a57f1d97bd6f702b5c13fd134a352079
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam

**Comment by kjozwiak** [comment]
The above requires `1.67.93` or higher for `1.67.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.98 Chromium: 125.0.6422.112 (Official Build) beta (64-bit)
-- | --
Revision | 9434daa5e8d2aceabb9cce574ab39429f2923b9b
OS | Windows 11 Version 23H2 (Build 22631.3593)

- Verified steps from issue description
- Verified Legacy wallet import option is shown during onboarding
- Verified able to import legacy wallet into new wallet without any issue

https://github.com/brave/brave-browser/assets/17010094/48306512-4a68-450a-b770-dcf8715f2f71
