### ISSUE TITLE
Add Leo shortcut to URL bar microphone

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#38089]
We want to open Leo's chat window with a text from dictation on URL bar microphone tap.
Let's make it for English locale only currently and detect if the phrase starts with `Leo`. For example:
1. `Leo, what time is it now` - opens a chat window with a prompt `what time is it now`.
2. `Leo` - brings up a chat window without anything filled in a prompt Edit box.

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 14 AP31.240426.023.B4 release-keys
Brave build: 1.68.101
Chromium: 126.0.6478.126 (Official Build) beta (64-bit) 
```

Filed follow-up issue #
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/38089#issue-2281158242
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the phrase `Leo, what time is it now` - opens a chat window with a prompt `what time is it now`
- Verified that the phrase `Leo` - brings up a chat window without anything filled in a prompt `Edit` box
- Verified that the phrase `Hi Leo` is not triggering Leo chat to be opened, even if the phrase includes `Leo` word

---------------------------

`Pixel 7`

https://github.com/brave/brave-browser/assets/128532965/409f471e-c0be-467b-b474-c407dbd9cf98

https://github.com/brave/brave-browser/assets/128532965/d86f657b-07cb-47bb-922a-5ac9a681f121
