### ISSUE TITLE
[Android] Fix `Refresh` credentials flow for mobile users

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#38085]
Add a link to `Refresh your credentials` for both VPN and Leo. See [spec](https://docs.google.com/document/d/1Xd7aGflHnZfausse_MGVbUxvJlIf06YV9XX8LcGjLXQ/edit#heading=h.zci6nrxpifmw).

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 AP31.240517.031 release-keys
Brave build: 1.68.101
Chromium: 126.0.6478.126 (Official Build) beta (64-bit) 
```
---------------------------
<details>
<summary> VPN </summary>

**STEPS:**
1. Purchase a new `VPN` subscription on Desktop, iOS or Android
2. If purchased on an iOS or Android device, link the subscription to account.brave.com
3. Take `Android` test device > Launch Brave
4. Hamburger menu > Brave VPN > *Verify new strings and `Refresh your credentials` button*
5. Tap `Refresh your credentials` > Enter your email address > Tap `Get login link` > *Verify that link is sent to an email*
6. Go to email and tap `Confirm your email` > *Verify `account.brave.com` is opened, and the `Success!` message is shown*
7. Hamburger menu > Brave VPN > Install VPN Profile > *Verify*

**ACTUAL RESULTS:**
- Verified that new text is shown below the `Monthly subscription` button
- Verified that the new `Refresh your credentials` button is shown and working
- Verified that the `restore link` is sent an email
- Verified that the `Confirm your email` link is working, `account.brave.com` opened, and the `Success!` message shown
- Verified that the VPN subscription can be linked and enabled successfully 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/5884bba6-26dd-4e40-8061-8ebc33b686cd) | ![2](https://github.com/user-attachments/assets/b003482c-5469-4f3e-8702-d316aa988c5f) | ![3](https://github.com/user-attachments/assets/618d8723-6b86-48a4-b460-bc3a41c2cfda) | ![4](https://github.com/user-attachments/assets/84e2d895-7422-44e5-975b-f97dfce09ede) |
| ![1](https://github.com/user-attachments/assets/28a35ad5-32a0-4713-9344-21f6d38e13d1) | ![2](https://github.com/user-attachments/assets/a69afeba-37e9-433e-83ec-faef15a46104) | ![3](https://github.com/user-attachments/assets/9df70541-8762-471c-bd0e-ddc19cd6879d) | ![4](https://github.com/user-attachments/assets/35e3b0f6-63f0-4a98-b9ba-4eeb9c16d985) |

https://github.com/brave/brave-browser/assets/128532965/51d11a04-f1f1-46fb-a32c-d0ad90298f0d


</details>

<details>
<summary> Leo </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>
