### ISSUE TITLE
Old Attention value is shown in Rewards Panel for an excluded page

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3808]
## Steps to Reproduce

   1. Clean profile
   2. Enable rewards
   3. Go to `interia.pl` and wait till it is included in a-c table
4.  Go to `google.com` and wait till it is included in a-c table
5. Exclude `interia.pl` from a-c table through `brave://rewards`
6. Open `interia.pl` in a new tab 
7. Open Rewards Panel

## Actual result:

Old Attention value is shown
![image](https://user-images.githubusercontent.com/34715963/54690541-eb962380-4b21-11e9-852f-97d27b5115a7.png)

Note: Excluding the site though Rewards Panel will show 0% Attention

## Expected result:
Attention value is 0%

![image](https://user-images.githubusercontent.com/34715963/54690564-f8b31280-4b21-11e9-863a-2d565397f063.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

cc @brave/legacy_qa @NejcZdovc

**Comment by GeetaSarvadnya** [comment]
Reproducible on 

Brave | 0.63.15 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

**Comment by LaurenWags** [comment]
Reproduced with 

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

**Comment by NejcZdovc** [comment]
@btlechowski can you reproduce this on latest nightly. I can't reproduce on latest 0.64

**Comment by btlechowski** [comment]
Not able to reproduce on Nightly since handling of excluded sites changed in https://github.com/brave/brave-browser/issues/3459

Brave | 0.64.24 Chromium: 73.0.3683.75 (Official Build) nightly (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523
