### ISSUE TITLE
Profile theme colors and icons are inherited from CR125

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#38087]
## Description 

 Found while testing https://github.com/brave/brave-browser/issues/37333
Profile theme colors and icons are inherited from CR125

## Steps to Reproduce

   1. Clean profile 1.67.x CR 125
   2. Click on Hamburger menu
   3. Select `Add new profile` via more tools menu item
   4. Profile theme colors and icons are inherited from CR125

## Actual result:

![image](https://github.com/brave/brave-browser/assets/38657976/eec57da8-cd60-4ae4-b4f0-a04ac8e869e5)

- Currently, the chromium themes have tri-colors for 2 themes, earlier it was two colors for all themes
- The number of themes varies on CR 125, it was 23 on CR 124 now it's reduced to 16 theme
- There is no much difference when 1st and 2nd themes are selected
## Expected result:

- Currently, the chromium themes have tri-colors for 2 themes, earlier it was two colors for all themes
- The number of themes varies on CR 125, it was 23 on CR 124 now it's reduced to 16 theme
- There is no much difference when 1st and 2nd themes are selected

TBD on the above, RC looks as below:
![image](https://github.com/brave/brave-browser/assets/38657976/46944783-7f3a-47c5-9ff1-1c3747f554db)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.67.69 Chromium: 125.0.6422.26 (Official Build) nightly (64-bit)
-- | --
Revision | 3ac44647a57f1d97bd6f702b5c13fd134a352079
OS | Windows 11 Version 22H2 (Build 22621.3447)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @rebron @aguscruiz @mkarolin @brave/qa-team

**Comment by bsclifton** [comment]
Looks like latest Chromium has made tri-colors for basically everything. Here's a screenshot from Chrome Beta (`125.0.6422.26`)
![image](https://github.com/brave/brave-browser/assets/4733304/514dec64-c9f9-4606-93dd-f9bfedaf49be)

Clicking each option actually works. For Brave, the first two tri-color options don't do anything. 
![colors](https://github.com/brave/brave-browser/assets/4733304/a696cb39-c988-46a4-ab6e-263e486c6407)

If our tri-color ones don't work, maybe we can remove them?

cc: @petemill @rebron

**Comment by rebron** [comment]
<img width="367" alt="Screenshot 2024-05-07 at 9 28 18 PM" src="https://github.com/brave/brave-browser/assets/5951041/d58015a3-3540-4bcb-8f75-5e4f47f5cd31">

@aguscruiz We need a new icon for the default one, not the tri-color state and we need to remove the second one completely as the one doesn't do anything.

**Comment by GeetaSarvadnya** [comment]
**Case 1: Upgrade case for the theme which is available on both CR 124 and CR125**


1. Clean profile 1.67.66 - CR 124
2. Click on Add a new profile
3. Select Dark purple theme
4. make sure theme changed to Dark purple
5. Upgrade the profile to 1.67.73 - CR 125
6. Confirmed that Dark purple theme retained upon upgrade

**Case 2: Upgrade case for the theme which is NOT available on CR 125**

1. Clean profile 1.67.66 - CR 124
2. Click on Add a new profile
3. Select Light purple theme
4. make sure theme changed to Light purple
5. Upgrade the profile to 1.67.73 - CR 125
6. Confirmed that Light purple theme NOT retained upon upgrade

**Comment by GeetaSarvadnya** [comment]
```
Light teal and white
Green and white
Beige and white
Pink and white
Beige
Orange
Dark red and orange
Dark green
Light purple and white
```
 All the above theme are present on CR124 but not on CR125. If user on CR 124 using any one of these theme and upgrade their profile to CR 125, theme will not be retain on CR 125 build. Existing users are going to loose their themes.

**Comment by GeetaSarvadnya** [comment]
I have verified the Case 2 (above) again today, looks like it's working fine.

```
Light teal and white
Green and white
Beige and white
Pink and white
Beige
Orange
Dark red and orange
Dark green
Light purple and white
```
The above themes are present only on CR 124, if user select any one of the theme above and upgrade the profile to CR 125 build, the theme is retained and the selected theme color is shown under `Custom color` via brave://settings/manageProfile on CR 125 build. Which looks correct to me. Please ignore the case 2 above as it's working fine. Thanks!

CR 124 | CR 125 | CR 125
---------|---------|-------
![image (7)](https://github.com/brave/brave-browser/assets/38657976/97af317c-9e04-419b-ba5a-3d796c8c04dc) | ![image (8)](https://github.com/brave/brave-browser/assets/38657976/944f2a85-7e1c-484e-b3ad-5debff0614f8) | ![image (9)](https://github.com/brave/brave-browser/assets/38657976/915a467c-fbf1-4f59-8e38-57535c46ceeb)

**Comment by aguscruiz** [comment]
For the first one, our default, we can keep the horizontal division we have in the new update, but we should use our default color themes in light/dark modes.

If you take them from Nala @simonhong, they should be:

Top: `Chrome/Background-Desktop`
Bottom: `Container/Background-Desktop`

Let me know if you need the hex codes instead

Should look like this:
<img width="710" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/6931f3e6-6240-4c92-9a75-e26574f1c5ec">

![image](https://github.com/brave/brave-browser/assets/15734630/ebab5287-d8c5-4aae-ae70-496c71508ec9)

**Comment by simonhong** [comment]
Working on this.

**Comment by kjozwiak** [comment]
The above requires `1.66.107` or higher for `1.66.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.66.107 Chromium: 125.0.6422.41 (Official Build) (64-bit)
-- | --
Revision | 188213f024297511fc5e37efe56eabde5992b300
OS | Windows 11 Version 23H2 (Build 22631.3527)
```
Verified using the description via https://github.com/brave/brave-core/pull/23571#issue-2288922140, ensured the following:

1. Installed 1.66.107
2. launched Brave
3. opened brave://settings/manageProfile
4. clicked hamburger menu -> Add new profile -> Add button
5. clicked Avatar -> Manage profile settings ->Add button 

- confirmed a random color is selected when creating new/additional profiles
- confirmed tri-colour themes are not visible via brave://settings/manageProfile & the new profile picker
- confirmed that the light theme/avatar is selected as the default for new profiles if Light is being used
- confirmed that the dark theme/avatar is selected as the default for new profiles if Dark is being used
- confirmed able to pick custom color theme when creating new/additional profiles

<details>
<summary>Light theme <summary>

example | example | random color selected| pink theme| grey theme | custom color
------ | ------ | ------ | ------ | ------- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/af23dc09-e2c3-47d1-b82f-c6b152f5b942)|![image](https://github.com/brave/brave-browser/assets/98358127/b16824c3-eae2-4c02-b983-63a5a2b8bf63)|![image](https://github.com/brave/brave-browser/assets/98358127/b94e487c-aacd-42e3-bac6-ac777f8e1618)|![image](https://github.com/brave/brave-browser/assets/98358127/d8754c41-8e78-4474-8ee9-0c739e41e41e)|![image](https://github.com/brave/brave-browser/assets/98358127/03172496-bb53-4383-9015-9a650d1eba24)|![image](https://github.com/brave/brave-browser/assets/98358127/a5a3b8d4-8609-4de2-9889-3ff66fedc78f)
</details>

<details>
<summary>Dark theme<summary>

example | example | random color selected| light green theme| grey theme | custom color
------ | ------ | ------ | ------ | ------- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/5e75aa8a-3e59-42f3-94d6-ab8166c5e537)|![image](https://github.com/brave/brave-browser/assets/98358127/3e6a0784-a83a-43e1-85d6-9f0675d37764)|![image](https://github.com/brave/brave-browser/assets/98358127/53a1dacb-e608-4208-a96b-b2a9c824be37)|![image](https://github.com/brave/brave-browser/assets/98358127/c4d7560a-59f6-4a82-878e-c9a9d8536b2d)|![image](https://github.com/brave/brave-browser/assets/98358127/7006da19-48b4-40a2-94b9-9d927e3145e6)|![image](https://github.com/brave/brave-browser/assets/98358127/d5ec491c-6505-46e0-98b2-e103e91c2f83)
</details>
