### ISSUE TITLE
Bookmarks icon displayed in red color under sidebar panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#38091]
## Description 

Bookmarks icon displayed in red color under sidebar panel

## Steps to Reproduce

   1. Clean profile 1.67.x CR 125
   2. Import some bookmarks
   3. Click on Bookmarks icon via Sidebar panel
   4. Bookmarks icon displayed in red color under sidebar panel

## Actual result:

Bookmarks icon displayed in red color under sidebar panel

Example | Example | Example
----------|-----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/245219ec-51d4-4331-a168-dddb87c11b66) | ![image](https://github.com/brave/brave-browser/assets/38657976/24fab66b-3533-4dfc-a94d-3586276bcd35) | ![image](https://github.com/brave/brave-browser/assets/38657976/8c086826-42dd-4c3b-a84f-e6f0433a0cb2)

## Expected result:

Bookmarks icon should not be in red color
## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.67.69 Chromium: 125.0.6422.26 (Official Build) nightly (64-bit)
-- | --
Revision | 3ac44647a57f1d97bd6f702b5c13fd134a352079
OS | Windows 10 Version 22H2 (Build 19045.4291)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @mkarolin

**Comment by kjozwiak** [comment]
The above requires `1.66.104` or higher for `1.66.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.66.104 Chromium: 125.0.6422.41 (Official Build) (64-bit)
-- | --
Revision | 6213f85e37bb676772fb221ce11a41c2b1be0fe2
OS | Windows 11 Version 23H2 (Build 22631.3527)
```

Verified using original STR from https://github.com/brave/brave-browser/issues/38091#issue-2281202464

#### Confirmed no red background displayed for Bookmarks icon and Bookmarks view is shown as expected


example | example | example
----- | ----- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/39be34d7-c6ac-41ef-93f8-a35245f19d0e)|![image](https://github.com/brave/brave-browser/assets/98358127/92c90e89-238a-4b61-bfbf-ebdda7235903)|![image](https://github.com/brave/brave-browser/assets/98358127/d6ed4e8a-ee62-4013-8c14-0002856828fa)
