### ISSUE TITLE
Undo button is not readable when a bookmark is deleted in the bookmarks sidepanel

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#38097]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/37970.  When a bookmark is deleted in the bookmarks sidepanel, background is black so Undo button with Nala color is unreadable.

## Steps to Reproduce

   1.  Install 1.67.64
   2.  launch Brave
   3.  navigate to a website (cnn.com) and bookmark it
   4.  open bookmarks sidepanel
   5.  open context menu for the selected bookmark
   6.  click `Delete`
   
## Actual result:

1 bookmark deleted message with `Undo` button shown with black background
example | example | example 
---- | ---- | ---
![image](https://github.com/brave/brave-browser/assets/98358127/6636dc2a-4173-48c9-9b80-dadab45b7937)|![image](https://github.com/brave/brave-browser/assets/98358127/93adfd14-4aae-4ab4-841a-1e1cb2c8b4c3)|![image](https://github.com/brave/brave-browser/assets/98358127/c405a76d-2e4e-4ff7-ab54-128895da5f0a)

## Expected result:
No black background with Undo button in Nala color

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.67.64 Chromium: 125.0.6422.26 (Official Build) nightly (64-bit)
-- | --
Revision | bfd2636e5cf7bb0b023414637e9a803310544b77
OS | Windows 11 Version 23H2 (Build 22631.3527)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @aguscruiz 
cc: @brave/qa-team

**Comment by simonhong** [comment]
Closed as duplicated with https://github.com/brave/brave-browser/issues/38091

**Comment by simonhong** [comment]
Oops, sorry. this issue is for `undo` button. reopened.

**Comment by simonhong** [comment]
It seems current background color is not fit with nala buttons

**Comment by simonhong** [comment]
Tested with different bg color for each themes. WDYT? @aguscruiz @rebron 
<img width="519" alt="Screenshot 2024-05-07 at 15 47 29" src="https://github.com/brave/brave-browser/assets/6786187/50b6edfc-1318-4a8b-8ee9-e69d09c5c786">
<img width="544" alt="Screenshot 2024-05-07 at 15 47 40" src="https://github.com/brave/brave-browser/assets/6786187/ad857711-7967-47be-912c-28da10d9a6a7">

**Comment by aguscruiz** [comment]
Looks good. That drop shadow is very dark though. Could you use elevation/02 from Nala? Or if you're using another preset let me know and we can tweak

**Comment by simonhong** [comment]
> elevation/02

Applied elevation/02(`box-shadow: 0px 4px 8px -1px #0000001A;`) - https://www.figma.com/file/g8Z0q6TMPYDq6zXh9Y7LWD/%F0%9F%8C%8E-Universal?type=design&node-id=2838-17201&mode=design&t=NvDiawq9JFZXvCG9-0
<img width="389" alt="Screenshot 2024-05-08 at 11 24 59" src="https://github.com/brave/brave-browser/assets/6786187/d1a16b93-9cc5-42de-919f-0663e6278715">
<img width="400" alt="Screenshot 2024-05-08 at 11 25 17" src="https://github.com/brave/brave-browser/assets/6786187/8a1a4dd0-84c9-422b-ad44-925a0529c94b">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.68.85 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | 8e76a669cf78bdfa933c8d569460092a01166588
OS | Windows 11 Version 23H2 (Build 22631.3672)
```

Verified using STR from the description https://github.com/brave/brave-browser/issues/38097#issue-2281413794

- Confirmed the toast message background color is shown as per Light/Dark themes when deleted a bookmark in the bookmarks panel
- Undo button is readable in the toast message with Dark theme

example | example 
------ | -------
![image](https://github.com/brave/brave-browser/assets/98358127/2b84f7c8-d4f5-45d3-bdf1-1c3e12aa35a3)|![image](https://github.com/brave/brave-browser/assets/98358127/00983629-4b2b-46fc-9efd-5a7b4000f3d8) 
![image](https://github.com/brave/brave-browser/assets/98358127/431e0d46-72ef-4e50-9c8a-353b550288ea)|![image](https://github.com/brave/brave-browser/assets/98358127/54a1bc52-c7bd-4cb2-a26b-bd02e73a1ca3)
