### ISSUE TITLE
[CR125] Bookmarks should be defaulted to default view in the bookmarks sidepanel

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#38109]
## Steps to Reproduce

   1. Install 1.67.x
   2. launch Brave
   3. import from Google Chrome and complete importing
   4. click on bookmarks icon in the sidebar
   5. click Bookmarks

## Actual result:

![image](https://github.com/brave/brave-browser/assets/98358127/cb5555fe-5aa1-4d7a-af68-9784fa9316d5)

## Expected result:

![image](https://github.com/brave/brave-browser/assets/98358127/b9c6c8ea-cfc6-4772-8700-71c62a28a911)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.67.71 Chromium: 125.0.6422.26 (Official Build) nightly (64-bit)
-- | --
Revision | 9e902199670f39502d25d82e7d61817129eea8ca
OS | Windows 11 Version 23H2 (Build 22631.3527)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
 @max @rebron 
cc: @brave/qa-team

**Comment by simonhong** [comment]
checking

**Comment by simonhong** [comment]
It's upstream issue and fixed recently https://chromium-review.googlesource.com/c/chromium/src/+/5499234

**Comment by kjozwiak** [comment]
The above requires `1.66.105` or higher for `1.66.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.66.105 Chromium: 125.0.6422.41 (Official Build) (64-bit)
-- | --
Revision | ba88d7bb175a55287d14014823d5da31fe9c8a47
OS | Windows 10 Version 22H2 (Build 19045.4291)
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/38109#issue-2281870673, ensured that `Bookmarks` are being displayed correctly under the `Sidebar` as per the following:

Example | Example | Example
---------|------------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/aab165ab-6b28-4a95-94cf-e23588842ecd) | ![image](https://github.com/brave/brave-browser/assets/38657976/823ee1e8-3da5-4c31-a2a4-ec7a3c8473da) | ![image](https://github.com/brave/brave-browser/assets/38657976/54017dcc-6cc0-4f97-8357-69604eb36e78)
