### ISSUE TITLE
Buttons in Background Image, Top sites & Cards sections in the Customize Dashboard are not updated to Nala blue color

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#38104]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/37970.  Buttons in the various areas such Background Image, Top Sites and Cards do not show updated Nala blue color for Check marks & buttons.  Also Sidebar button text is not updated either.

## Steps to Reproduce

1. Install 1.67.64
2. Launch Brave
3. Click `Customize` button in the new tab page
4. Check marks in for any of the background images & Top sites do not show updated Nala blue color
5. Hide & Add buttons for Cards sections

## Actual result:

example | example | example| example | example 
----- | ----- | ----- | ---- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/94635c73-57fe-4d14-a5a6-94a01b940f9b)|![image](https://github.com/brave/brave-browser/assets/98358127/6d17a881-9ad1-43ee-b3a4-0cc73e86f246)|![image](https://github.com/brave/brave-browser/assets/98358127/8a56c511-f7b8-48e3-a08b-d2d606636b3d)|![image](https://github.com/brave/brave-browser/assets/98358127/3936c687-e7da-42c3-901c-b6d847009565)|![image](https://github.com/brave/brave-browser/assets/98358127/4e18af53-f562-4281-962c-de5f42ae867d)

## Expected result:
Updated Nala blue color

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.67.64 Chromium: 125.0.6422.26 (Official Build) nightly (64-bit)
-- | --
Revision | bfd2636e5cf7bb0b023414637e9a803310544b77
OS | Windows 11 Version 23H2 (Build 22631.3527)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron @aguscruiz 
cc: @brave/qa-team

**Comment by rebron** [comment]
cc: @fallaciousreasoning

**Comment by fallaciousreasoning** [comment]
I've got a fix for the buttons - the sidebar is less urgent but blocked on some Nala changes, so might address that as a followup

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.67.76 Chromium: 125.0.6422.26 (Official Build) nightly (64-bit)
-- | --
Revision | c8696983cac61f6c5a22bc23ca991c20737fd0b0
OS | Windows 10 Version 22H2 (Build 19045.4355)
```




## `Light` mode

`Background Image` | `Cards` | example | example | example
----------|----------|------------|----------|-----------
![image](https://github.com/brave/brave-browser/assets/387249/40fd63e1-446f-423e-99f3-df2912b61135) | ![image](https://github.com/brave/brave-browser/assets/387249/83b78bb4-c266-40a0-b115-ccca98cd9a0f)

## `Dark` mode

**Comment by kjozwiak** [comment]
The above requires `1.66.104` or higher for `1.66.x` verification 👍 Used https://github.com/brave/brave-browser/issues/38104#issuecomment-2101497231 as the needed verification for `1.66.x` uplift but removing the `QA Pass` label as we'll need to re-verify using `1.66.x`.

**Comment by aguscruiz** [comment]
I have an updated design for those little illustrations here
https://www.figma.com/design/xjmYkVb0sPD31xxAV1MFhS/Customize-NTP-modal?node-id=0-1

![image](https://github.com/brave/brave-browser/assets/15734630/6ed5442d-0fff-497f-99e8-ee7602dc0a74)

![image](https://github.com/brave/brave-browser/assets/15734630/20d33949-ec37-42e3-88db-4f2da0c953ca)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.66.104 Chromium: 125.0.6422.41 (Official Build) (64-bit)
-- | --
Revision | 6213f85e37bb676772fb221ce11a41c2b1be0fe2
OS | Windows 11 Version 23H2 (Build 22631.3527)
```

1. installed 1.66.104
2. launched Brave
3. opened a new-tab window
4. clicked Customize at the bottom
5. clicked Background Image, Cards, Top Sites

Encountered https://github.com/brave/brave-browser/issues/38173

#### Confirmed Check marks for background images, Hide & Add buttons for Cards sections shown blurple color

Background Image | Cards | Top Sites
----- | ------- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/796b94a2-e716-42e6-9871-c2caae0e7d31)|![image](https://github.com/brave/brave-browser/assets/98358127/be9d39c3-9679-48dd-a2cf-f7e59c34570c)|![image](https://github.com/brave/brave-browser/assets/98358127/3792737b-62d3-47c2-a502-b0bb1ef08d4d)
![image](https://github.com/brave/brave-browser/assets/98358127/a7a7e355-f15b-4f00-8015-aaa356881b80)|![image](https://github.com/brave/brave-browser/assets/98358127/6a0dc541-ca9a-49c7-b0b3-d2326282f25a)|![image](https://github.com/brave/brave-browser/assets/98358127/518b0b60-f1e6-446c-8ff6-c54604694d5f)
