### ISSUE TITLE
[Speedreader]  Double scrollbars.

### ISSUE THREAD

**Issue by boocmp** [brave/brave-browser#38118]
## Steps to Reproduce

   1. Enable Fanboy's Annoyances list on brave://settings/shields/filters
   2. Open [https://www.microsoft.com/en-us/security/blog/2024/05/01/dirty-stream-attack-discover[…]d-mitigating-a-common-vulnerability-pattern-in-android-apps/](https://www.microsoft.com/en-us/security/blog/2024/05/01/dirty-stream-attack-discovering-and-mitigating-a-common-vulnerability-pattern-in-android-apps/) in speedreader mode

## Actual result:

Double scrollbars appear.

## Expected result:

Only page's scrollbar should be visible.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.68.6 Chromium: 125.0.6422.41 (Official Build) nightly (x86_64)
-- | --
Revision | 2886cb2a986d182705496c6252456cf7424e08a5
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.68.6`
2. launched Brave
3. opened `brave://settings/shields/filters`
4. enabled `Fanboy's Annoyances`
5. loaded `https://www.microsoft.com/en-us/security/blog/2024/05/01/dirty-stream-attack-discovering-and-mitigating-a-common-vulnerability-pattern-in-android-apps/`
6. clicked on `Turn on Speedreader`

### Confirmed only one set of scrollbars


<img width="1495" alt="Screen Shot 2024-05-13 at 11 26 44 AM" src="https://github.com/brave/brave-browser/assets/387249/1ee951fc-e299-488a-a002-8de3185cb719">

**Comment by LaurenWags** [comment]
Removed `QA Pass-macOS` as this needs to be verified on 1.67.x.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.67.91 Chromium: 125.0.6422.76 (Official Build) beta (x86_64)
-- | --
Revision | 14f0efcb744b293ececd4a8c74ec947d8b22e002
OS | macOS Version 14.5 (Build 23F79)
```

### Steps:

1. installed `1.67.91`
2. launched Brave
3. opened `brave://settings/shields/filters`
4. enabled Fanboy's Annoyances
5. loaded `https://www.microsoft.com/en-us/security/blog/2024/05/01/dirty-stream-attack-discovering-and-mitigating-a-common-vulnerability-pattern-in-android-apps/`
6. clicked on `Turn on Speedreader` in the URL bar

### Confirmed only one set of scrollbars

example | example | example | example
---------|----------|---------|----------
<img width="1810" alt="Screenshot 2024-05-22 at 12 15 56 PM" src="https://github.com/brave/brave-browser/assets/387249/a253b63e-6646-4f79-966a-ed5ee74447e3"> | <img width="1810" alt="Screenshot 2024-05-22 at 12 16 00 PM" src="https://github.com/brave/brave-browser/assets/387249/98f9f988-70e4-4d8a-bc6e-3c5ea318b857"> | <img width="1810" alt="Screenshot 2024-05-22 at 12 16 13 PM" src="https://github.com/brave/brave-browser/assets/387249/bc515aae-636f-4374-88a0-064eac9a0023"> | <img width="1810" alt="Screenshot 2024-05-22 at 12 16 22 PM" src="https://github.com/brave/brave-browser/assets/387249/d6a730af-5c5a-4411-80c4-b5956b3c0293">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.67.90 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | 64f9eec1a854079c3e529e908ca300071afb1f32
OS | Windows 11 Version 23H2 (Build 22631.3593)
```

Reproduced the issue in `1.66.113 Chromium: 125.0.6422.76` 

enabled enable Fanboy's Annoyances list | double scrollbars
------- | -------
![image](https://github.com/brave/brave-browser/assets/98358127/5bef35ca-bcfa-49a6-ac7a-041a038cf4dd)|![image](https://github.com/brave/brave-browser/assets/98358127/6ddf902e-a3ab-42e0-9dff-77d04a8fbe46)


1. installed 1.67.91
2. launched Brave
3. opened `brave://settings/shields/filters`
4. enabled `Fanboy's Annoyances`
5. loaded https://www.microsoft.com/en-us/security/blog/2024/05/01/dirty-stream-attack-discovering-and-mitigating-a-common-vulnerability-pattern-in-android-apps/
6. clicked on Turn on `Speedreader` in the URL bar


#### Confirmed only one set of scrollbars 

`Enabled Fanboy's Annoyances`  | `Not checked Fanboy's Annoyances`  
------ | ------  
![image](https://github.com/brave/brave-browser/assets/98358127/b0669ddf-ea6a-45b0-8f24-c0dbff01e289)|!![image](https://github.com/brave/brave-browser/assets/98358127/f7a83916-f050-4149-93e1-9a90c7c308d4)
![image](https://github.com/brave/brave-browser/assets/98358127/b55e91a2-a813-4b41-a5d2-de4e9928c739)|![image](https://github.com/brave/brave-browser/assets/98358127/9546ad45-d011-4975-8546-f16782aa9560)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.67.94 Chromium: 125.0.6422.112 (Official Build) beta (64-bit) 
Revision	3e4d210c91412b82ad8cffca556b12bbe40ff962
OS	Linux
```


1. installed 1.67.94
2. launched Brave
3. opened `brave://settings/shields/filters`
4. enabled `Fanboy's Annoyances`
5. loaded https://www.microsoft.com/en-us/security/blog/2024/05/01/dirty-stream-attack-discovering-and-mitigating-a-common-vulnerability-pattern-in-android-apps/
6. clicked on Turn on `Speedreader` in the URL bar


#### Confirmed only one set of scrollbars 

`Enabled Fanboy's Annoyances`  | `Not checked Fanboy's Annoyances`  
------ | ------  
![image](https://github.com/brave/brave-browser/assets/98358127/4000fff4-f5f1-496f-afd1-9a301d9547e1)|![image](https://github.com/brave/brave-browser/assets/98358127/4cd37716-4c25-4c99-b188-95ee0137a9a6)
![image](https://github.com/brave/brave-browser/assets/98358127/1ef78df2-076a-46b6-9526-9935d417dcd7)|![image](https://github.com/brave/brave-browser/assets/98358127/4e8cbc68-5b36-4129-9953-9e023f4071e6)
