### ISSUE TITLE
[Commands]: Fix ampersand replacement

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#38113]
Issue reported by @junkworld in https://github.com/brave/brave-browser/issues/37905#issuecomment-2088236209

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.67.73 Chromium: 125.0.6422.26 (正式版本) nightly （64 位）
-- | --
修订版本 | 76e7d97680074902ad7bde84f0a1a6c392a4ca6a
操作系统 | Windows 10 Version 22H2 (Build 19045.4355)
```

### Steps:
0. set OS region, language, etc. to `Simplified Chinese`
1. installed `1.67.73`
2. launched Brave
3. opened `chrome://settings/system/shortcuts`
4. typed `avascript`
5. examined all instances of matches

### Confirmed all `JavaScript` entries began with `J`

![image](https://github.com/brave/brave-browser/assets/387249/a171c667-c04f-4717-8fcc-a49a26b9e6e6)

**Comment by kjozwiak** [comment]
The above requires `1.66.104` or higher for `1.66.x` verification 👍 Removing the `QA Pass` label as the above will need to be re-verified using `1.66.x`. However, used https://github.com/brave/brave-browser/issues/38113#issuecomment-2099350510 as the needed verification on `Nightly` before uplifting into `1.66.x` as per https://github.com/brave/brave-core/pull/23487#pullrequestreview-2046216741.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.66.104 Chromium: 125.0.6422.41 (Official Build) (x86_64)
-- | --
Revision | 6213f85e37bb676772fb221ce11a41c2b1be0fe2
OS | macOS Version 13.6.6 (Build 22G630)
```
