### ISSUE TITLE
Add metric for Brave Search daily usage

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#38117]
Add metric to measure daily usage of Brave Search:

If you have your default engine set to Brave Search, did you make a Brave search query today?
`Brave.Search.BraveDaily`

1. Yes

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.68.92 Chromium: 126.0.6478.71 (Official Build) beta (64-bit)
-- | --
Revision | 393b9968e233540a48f04d74bc4601a05d3a0169
OS | Windows 10 Version 22H2 (Build 19045.4529)
```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.68.101`

<details>
<summary>Brave.Search.BraveDaily = 1_PASSED</summary>

1. Clean profile 1.68.x
2. Enable rewards
3. Open brave://local-state file
4. Look for the metrics `Brave.Search.BraveDaily`
5. Confirmed that metrics `Brave.Search.BraveDaily` isn't shown 
6. Go to `search.brave.com`
7. Reload local state file and ensured that metrics isn't shown 
8. Make a query via `search.brave.com`
9. Reload brave://local-state file
10. Confirmed that metrics `Brave.Search.BraveDaily` response value is `1` as expected

Example | Example | Example
----------|------------|-------------
![image](https://github.com/brave/brave-browser/assets/38657976/f60f2db1-a331-49ba-800a-1cdd585055bf) | ![image](https://github.com/brave/brave-browser/assets/38657976/55bbee8c-5982-4c9e-9cd9-0e7da78a1063) | ![image](https://github.com/brave/brave-browser/assets/38657976/e2ef5610-7d9f-45b8-8c37-0f38b420b76d)

</details>
