### ISSUE TITLE
Brave Rewards `Reset` button is not working and grayed out when checkbox is selected

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#38112]
## Description 

Brave Rewards `Reset` button is not working and grayed out when the checkbox is selected.

## Steps to reproduce 

   1. Launch Brave Nightly `1.67.18` or newer
   2. Join `Rewards` (Prod or Staging)
   3. Go to `brave://rewards`
   4. Tap `Reset` > Select the `checkbox` > *Notice that the checkbox is not selected on the 1st tap*
   5. Tap the 2nd time on the checkbox > *Observe that the `Reset` CTA button is still grayed out*

## Actual result 

Brave Rewards `Reset` button is not working and grayed out when the checkbox is selected. Also, notice in the attached video, that tapping the checkbox the first time is not doing anything, and only the second time it got checked.

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/61bb9c14-2976-4b60-bb7a-7b675804fc3f) | ![2](https://github.com/brave/brave-browser/assets/128532965/34cf6211-5572-4e7f-a5f0-d5a8ebf1ef4e) |

![2024-05-06_17-38-00](https://github.com/brave/brave-browser/assets/128532965/7617417e-ddb7-47d4-9fdb-461b92a512b4)

## Expected result

Rewards `Reset` button must work.

## Issue reproduces how often 

`Easily reproduced`

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NO
- Can you reproduce this issue with the current Play Store Beta version? NO
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 6, Pixel 7
   - Android version: Android 14, Android 15
   
## Brave version

```
Brave build: 1.67.18 
Chromium: 124.0.6367.60 (Official Build) canary (64-bit) 
```

or newer up to 

```
Brave build: 1.67.70 
Chromium: 125.0.6422.26 (Official Build) canary (64-bit) 
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
As per @deeppandya, this is the same issue as https://github.com/brave/brave-browser/issues/38099 which was also reported by @GeetaSarvadnya & @mkarolin. Going to close the above and label as `closed/duplicate` but will add the `OS/Android` label via https://github.com/brave/brave-browser/issues/38099 and mention this issue.
