### ISSUE TITLE
[iOS/Wallet]: Missing import legacy wallet toggle in onboarding 

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#38123]
iOS wallet onboarding is missing the toggle indicates user is importing a legacy wallet after user choose 24 recovery phrases.

**Comment by kjozwiak** [comment]
The above requires `1.66.105` or higher for `1.66.x` verification 👍

**Comment by kjozwiak** [comment]
@nuo-xu @srirambv added the `release-notes/include` label but please correct if it should be `release-notes/exclude` 👍

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.5 running 1.66 (105) build
- Verified steps from [brave/brave-core#23462](https://github.com/brave/brave-core/pull/23462)
- Verified on onboarding selecting Restore wallet and selecting 24 word phrase shows `Import from legacy Brave crypto wallets?` option
- Verified restoring wallet from lock screen and selecting 24 word phrase shows `Import from legacy Brave crypto wallets?` option
- Verified able to import 24 word seed 
- Verified if `Import from legacy Brave crypto wallets?` option is not selected it imports a different set of address
- Verified if `Import from legacy Brave crypto wallets?` option is selected it imports the actual/correct wallet address 
- Verified able to import 12 word seed from both onboarding and wallet lock state
- Verified when importing 24 word seed, going to backup shows the same set of seed words 

https://github.com/brave/brave-browser/assets/17010094/89c8efaf-442e-4509-89d5-a82a54f7bc87
