### ISSUE TITLE
[ads] `Landed` confirmation for the push notification ads is broken

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#38128]
## Description 

`Landed` confirmation for the `notification` ads is broken.

## Steps to reproduce 

   1. Launch Brave `1.66.97` or newer
   2. Activate `Rewards Staging server` via `Dev options`
   3. Enabled `Rewards` (no need to connect custodian)
   4. Wait for the notification ad > Tap it
   5. Keep the page opened
   6. Check the logs via Terminal/Android Studio > *Observe that `landed` confirmation is not shown*

## Actual result 

`Landed` confirmation for the `notification` ads is broken and not shown. This issue starts with Brave `1.66.x` build and is not reproducible with `1.65.129`. Also, the issue is showing all the logs for `NTP` ads.

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/00199ac0-268c-4c16-b44c-45493367439b) | ![2](https://github.com/brave/brave-browser/assets/128532965/0946d55c-b055-4762-98bd-b773a1e4fa73) |

https://github.com/brave/brave-browser/assets/128532965/4e7bdcbb-2a88-4dcd-b720-9e72176e49c0

## Expected result

`Landed` confirmation logs must be shown as before.

## Issue reproduces how often 

`Easily reproduced`

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NO
- Can you reproduce this issue with the current Play Store Beta version? YES
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 7 (phone)
   - Android version: Android 15
   
## Brave version

```
Brave build: 1.66.97 
Chromium: 124.0.6367.118 (Official Build) beta (64-bit) 
```

and

```
Brave build: 1.67.70 
Chromium: 125.0.6422.26 (Official Build) canary (64-bit) 
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @tmancey @aseren

**Comment by tmancey** [comment]
@aseren this was tested by @btlechowski, but if you do discover this affects desktop too, can you please add the `OS/Desktop` label.

**Comment by kjozwiak** [comment]
The above requires `1.66.104` or higher for `1.66.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240322.023 release-keys
Brave build: 1.66.104
Chromium: 125.0.6422.41 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/38128#issue-2283880304
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Landed` confirmation logs are shown for the `Notification`, `NTP` and `Inline` ads

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/1c9926a7-23b5-4c47-a0ce-2b4a01c68f6e) | ![2](https://github.com/brave/brave-browser/assets/128532965/0d68d07f-2139-4fcb-bfed-2af4650be8a8) | ![3](https://github.com/brave/brave-browser/assets/128532965/fe1bcd39-4077-41e2-81eb-6b1142c1229b) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/ac5440c5-f0e4-48d5-86c8-25181611a504) | ![2](https://github.com/brave/brave-browser/assets/128532965/6a599994-4f6f-484d-8030-434671c961bc) | ![3](https://github.com/brave/brave-browser/assets/128532965/f1695a98-107e-42d5-9e2c-beefe77529d2) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/cb6a82bd-d325-4266-98b5-7247219d4b42) | ![2](https://github.com/brave/brave-browser/assets/128532965/bd503d78-b950-421d-b5dd-f18429f4737b) | ![3](https://github.com/brave/brave-browser/assets/128532965/315da9b3-1a8c-4aac-916c-b9f33646439a) |
