### ISSUE TITLE
Very specific: Issue with zendesk web app five9 plugin

### ISSUE THREAD

**Issue by olly-writes-code** [brave/brave-browser#3812]
## Description 
I'm sorry but this isn't an easy one to reproduce as it requires zendesk web app with a specific app installed. I'll try and give as many details as possible and maybe I can debug further or try to create something that is reproducible.

This is the app installed on the zendesk web app https://www.zendesk.com/apps/support/five9-for-zendesk/

The app does not work when the shield is active (it hangs as it's external requests are blocked). When the shield is deactivated the app works and the login option comes up.  When login credentials are submitted the app either hangs or shows this error. 

## Actual Result
![image](https://user-images.githubusercontent.com/7778402/54712389-5dae3e80-4b09-11e9-9d1e-26f3a9ed6189.png)

When running with the developer console. I see the following errors over and over as it tries to connect.

```
all.js? [sm]:42985 WebSocket connection to 'wss://app-scl.five9.com/appsvcs/ws' failed: HTTP Authentication failed; no valid credentials available
SocketAdapter.connect @ all.js? [sm]:42985
all.js? [sm]:41430 03/20/2019 10:11:19,823 [1553101812833sqhktr6rj] [ERR] ["SocketAdapter:socket:onerror:",{"isTrusted":true}]
```

Is something within brave somehow blocking the wss connection?

I've also tried allowing 3rd party fingerprinting. And allowing non HTTPS. I've checked and cookies should be stored.

## Expected Result
Should login

## Steps to Reproduce
Sorry this is a hard one

   1. Log into zendesk
   2. Install the five9 app https://www.zendesk.com/apps/support/five9-for-zendesk/
   3. Try and log into the five9 app

## Reproduces how often: 
Every time

## Brave version (brave://version info)
0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit) (latest)

### Reproducible on current release:
Yes. Tried with v0.64.7

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No. Works fine in Chrome (latest version).

**Comment by rebron** [comment]
@Brave-Matt can you take a look, do you use this Zendesk extension?

**Comment by ryanbr** [comment]
@kindjacket  Hey, just checking if the current Brave release is still experiencing this issue?

**Comment by kindjacket** [comment]
Sorry I've stopped using Brave now :/ 

Feel free to close the issue
