### ISSUE TITLE
[Perf] 22.1% regression in CPU usage after cr125 update (win-11)

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#38121]
```
Median of segment before: 2279.2195
Median of segment after: 2783.4985
Relative change: 22.1%
Test: BravePerf/win11-hp-laptop-typical/system_health.common_desktop/cpuTime:browser_process:all_threads:all_stages:all_initiators/load_chrome/load_chrome_blank
```
https://brave-perf-dashboard.appspot.com/report?sid=10c4d2afabce418e81a95e0e914be61e4dddea6db5edf454a5ec24edd3acc071&rev=19294

![image](https://github.com/brave/brave-browser/assets/45488748/ef813bc8-30e8-4ce2-9c9a-116e290d72ca)

**Comment by atuchin-m** [comment]
I suspect it's PGO profiles, clang or rust version related issue, because:
1. no direct adblock related changes in the commit range.
2. We don't see the matching changes on the other platforms.

**Comment by atuchin-m** [comment]
Static build also has the regression:
![image](https://github.com/brave/brave-browser/assets/45488748/b9b4d5d9-8e19-4376-ac10-c27a7e43ce1a)

**Comment by bridiver** [comment]
We are using the same rust/clang versions as upstream

**Comment by atuchin-m** [comment]
@bridiver it's definitely not PGO issue because `Static` is also affected.

**Comment by atuchin-m** [comment]
A result of profiling `Static` builds:
![image](https://github.com/brave/brave-browser/assets/45488748/c8dfe660-53dc-466f-a997-cc754c7257c2)

**Comment by atuchin-m** [comment]
It turns out it's Chromium Rust issues.
A upstream CL to fix: https://chromium-review.googlesource.com/c/chromium/src/+/5542720

**Comment by atuchin-m** [comment]
Related upstream CL: https://chromium-review.googlesource.com/c/chromium/src/+/5542720
