### ISSUE TITLE
aichat: update page context toggle copy and minor design tweaks

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#38127]
https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=422%3A12579&mode=design&t=fyjpfxxWe8V7rVYh-1

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```

```

hover or tap should show tooltip
tap radius should be improved on mobile
tap info icon should show tooltip and tapping outside should make it dissapear

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12 `running `Bravemonoarm64.apk_1.68.115`

- Confirmed that user can toggle `Shape answers based on the page's contents` 
- Confirmed tooltip on hover of (i) icon
- Click on info icon (i) displays the tooltip `Shape answers based on the page's contents` 
- Click on info icon (i) disable the toggle - Need to log an issue 
- Confirmed that tap info icon shows the tooltip and tapping outside makes the tooltip disappear


`tooltip` | `disabled` | `enabled`
---------|---------|---------
![Screenshot_20240711_143408](https://github.com/brave/brave-browser/assets/38657976/4ba5a262-b53c-46a6-ab0b-a5a772159abb) | ![Screenshot_20240711_143356](https://github.com/brave/brave-browser/assets/38657976/35872174-0251-4e39-8037-53a4125f0fcc) | ![Screenshot_20240711_141644](https://github.com/brave/brave-browser/assets/38657976/e368a565-e506-4c12-bb6b-c2c9d0700d9a)

**Comment by GeetaSarvadnya** [comment]
@nullhook: Click on info icon (i) disable the toggle on Android. Is this expected?

Uploading XRecorder_11072024_143957.mp4…

cc: @stephendonner
