### ISSUE TITLE
[ads] Fullscreen NTT video ad plays extra sound when started before autoplay finished

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#38133]
## Steps to Reproduce

1. Get iPhone as a device
2. Do Brave fresh install
3. Do prerequisites to install staging components
4. Launch browser in Portrait orientation
5. Open New Tab Pages until a tab with New Tab Takeover video ad is opened
6. Check that video autoplay starts after the tab with New Tab Takeover video ad is opened
7. Check that New Tab Takeover video autoplay is started
8. Tap the video before autoplay is finished

## Actual result: 
NTT video ad plays extra sound in the beginning when going Fullscreen

## Expected result:
NTT video ad does't play extra sound in the beginning when going Fullscreen

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

**Comment by kjozwiak** [comment]
The above requires `1.66.104` or higher for `1.66.x` verification 👍 @hffvld @Uni-verse there's some STR/Cases via https://github.com/brave/brave-core/pull/23480#issue-2284280195 that can be used as well for `1.66.x` verification.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.3.1` using version `1.66.104`

- Ensured issue is not reproducible using STR in https://github.com/brave/brave-browser/issues/38133#issue-2284243173.
- Ensured that Video NTT autoplay is enabled. 
- Ensured there are no issues loading additional NTT with video. 

Note: Additional checks were completed on iPhone and iPad in https://github.com/brave/brave-browser/issues/36435#issuecomment-2103497280

https://github.com/brave/brave-browser/assets/17885425/44b0f135-1fa2-4c5c-9469-a507be58dda5
