### ISSUE TITLE
Change title/label back to `Downloads` in `brave://downloads/`

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#38135]
## Description 

Chromium 125 introduce a text/label change for Downloads to Download History. 

We should keep this labeled as `Downloads`. 

While the Chrome team is looking to remove confusion with this label change, the change may also add to the confusion for users thinking this is where you "download" your "browser history". 

## Steps to Reproduce

   1. Go to brave://downloads/ (or brave://settings, etc as the title is in the header)
   2. Notice title is Download History.
   3. Should still be Downloads

## Actual result:

<img width="1110" alt="Screenshot 2024-05-07 at 3 13 00 PM" src="https://github.com/brave/brave-browser/assets/5951041/18adf80c-8f47-4d4e-98d6-9ea4d9a91252">

## Expected result:
<img width="1067" alt="Screenshot 2024-05-07 at 3 13 12 PM" src="https://github.com/brave/brave-browser/assets/5951041/909bf5be-39ab-4191-b28c-c0038e0d5763">

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a 
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by kjozwiak** [comment]
The above requires `1.66.105` or higher for `1.66.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.66.105 Chromium: 125.0.6422.41 (Official Build) (64-bit)
-- | --
Revision | ba88d7bb175a55287d14014823d5da31fe9c8a47
OS | Windows 10 Version 22H2 (Build 19045.4291)
```

Using the same STR/Cases as mentioned above, ensured that `Download History` is renamed to `History` as per the following:
![image](https://github.com/brave/brave-browser/assets/38657976/9a782957-0e62-4651-adac-1fe5b92d741c)
