### ISSUE TITLE
Search Suggestions Enhancement

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#38137]
## Description: 
For context please search for _Spec: Brave Search Suggestions Default On (2024)_ on GDrive

Security Review:https://github.com/brave/reviews/issues/1567

When Brave Search is set as the default search engine (Standard Tab), search suggestions will be enabled by default. Given this, for **New Users** of Brave who download the browser in countries where Brave Search is the default, please:

- Remove the iOS search suggestions opt-in as it will no longer be necessary.

**Additionally, for all users of Brave:**
- Prevent search suggestions from displaying when text is copy-pasted into the URL bar
- Remove personally identifiable information (PII) and sensitive data from URL bar input, similar to how it is currently handled in search See here: https://github.com/brave/search/blob/e4e1b2b2cee4d33ec42960f8f82cf7d8b8cc4976/services/mixer/serpkit/src/lib/components/suggest/queryChecker.ts#L37
- Ensure that search suggestions remain active if a user manually switches their search engine to another provider.

**For Reference:**
The 12 countries where Brave Search is currently set as default include: US, CA, GB, DE, FR, MX, BR, IN, ES, AR, AT, IT.

Additionally:
- If a user enables search suggestions in settings at any point, that preference should be respected, regardless of the search engine in use.
- If a user disables search suggestions in settings, that preference should also be respected, regardless of the search engine.

**Comment by soner-yuksel** [comment]
So multiple questions and concerns from mobile side here related with Additionally section.

1. `Prevent search suggestions from displaying when text is copy-pasted into the URL bar
`

So this is very vague, user can add a character at any moment of search display before search is executed. 

To determine this, the only way I can think of is to compare the entry done in search bar and the entry after a new entry is performed is combination of existing text + what is in clipboard.

So a question arise here when user copied a text we hid the search suggestions section but lets say user added a new character to the copied text should we redisplay search suggestion again. First of all this is not easy to detect and the execution of this will make search suggestions look janky and buggy in some circumstances.

I am kinda questioning and struggling the to understand the reasoning behind this. And this should be mentioned in the security ticket open for this issue, it is not mentioned there.

2. `Remove personally identifiable information (PII) and sensitive data from URL bar input, similar to how it is currently handled in search `

First concern is we should not manipulate the text user copied for any reason on client. It is the user who is entering this text malicious or not. Our responsibility is to securely execute or block etc the query entered.

This what we are doing already, for instance you cant execute a malicious script from url bar etc.

Also the example code linked from Search Repo is not removing any PII or something from the query, it is doing some process related with copy pasting and doing it in a way first determining the query is copied if it is longer than certain number of characters and using a function ?! called isSuspiciousQuery or isSafeQueryURLs and returning a  boolean after some algorithm we have no details bout here. And we also have no idea where is this result used.

IMO both these options should not be implemented on client side. And if it will, they should be properly clarified and documented in addition this requirement should be mentioned in security ticket.

**Comment by iccub** [comment]
For 1 just hide it when you paste, if you modify it then they can appear no matter if you edited back to the original contents or not.
But I do not see a reason, browsers do not do it. And it is useful if I paste a name of the hotel and it can be recommend more words to it

Overall I think this ticket can be split into few smaller ones.

**Comment by soner-yuksel** [comment]
Totally agree we should be adding these additional parts into new tickets so we can discuss their relevance and also open new security tickets for them.

For 1 I think we are in the same page, I really don not understand the reasoning behind it and we should carry over to a new issue and discuss it there.

And for 2 it needs brand new ticket with proper requirements even to start and also security ticket for proposed changes which isnt so clear.

**Comment by iccub** [comment]
I found more details in the spec, so it's not really up to us. I will work on it and I shared our concerns in that spec as well.
I will also ask if we can implement it step by step

**Comment by anthonypkeane** [comment]
Please note that there are other settings like https://github.com/brave/brave-browser/issues/38688#issuecomment-2138428304 that are at play here. Disabling Search Suggestions entirely should disable probably disable (https://github.com/brave/brave-browser/issues/38688#issuecomment-2138428304)

**Comment by kjozwiak** [comment]
@Uni-verse @hffvld I went through https://github.com/brave/brave-core/pull/24376#issuecomment-2311439149 as we had uplifts into `1.69.x` & `1.70.x` but decided to let the above ride the trains via `1.71.x`. Can use my example as a template but I would check a few more regions just in case to ensure everything is working. For example:

* check two regions that have Brave Search as the default to ensure the above work is working as expected
* check two regions that doesn't use Brave Search as the default and ensure they're still getting `enable search suggestions`

**Comment by Uni-verse** [comment]
In progress on `iPhone 12` running `iOS 18` using version `1.71.112`

**Brave Default SE (US)**
 
* Ensured `Show Search Suggestions` is enabled in `Search Engine` settings.
* Ensured search suggestions are shown when entering search term into omnibox and enable search suggestions modal is not shown in the omnibox area. 
* Ensured search suggestions are now shown when entering invalid/suspicious search terms. 
* Ensured disabling `Show Search Suggestions` will not show search suggestions. 

example | example | example | example | example
---|---|---|---|---
![Image](https://github.com/user-attachments/assets/1bc89a1f-5a93-48a9-964b-8aca3a72503f) | ![Image](https://github.com/user-attachments/assets/0b7312e5-0fd6-413a-96b6-8eca0facee13) | ![Image](https://github.com/user-attachments/assets/d6bdc516-d625-452a-8bac-b9d0317a102f) | ![Image](https://github.com/user-attachments/assets/953866ac-51c0-4b10-b6f6-11c1eaaa7fbd) | ![Image](https://github.com/user-attachments/assets/e187e0bf-f3c6-4204-8333-ad4dcd0f15bf)

**Brave Default SE (France)**

**Brave Not Default SE (Singapore)**

**Brave Not Default SE (South Africa)**

**Comment by Uni-verse** [comment]
In progress on `iPad` running `iOS 17.5.1` using version `1.70.112`

**Brave Default SE (US)**
 
* Ensured `Show Search Suggestions` is enabled in `Search Engine` settings.
* Ensured search suggestions are shown when entering search term into omnibox and enable search suggestions modal is not shown in the omnibox area. 
* Ensured search suggestions are now shown when entering invalid/suspicious search terms. 
* Ensured disabling `Show Search Suggestions` will not show search suggestions. 

example | example | example | example | example
---|---|---|---|---

**Brave Default SE (France)**

* Ensured `Show Search Suggestions` is enabled in `Search Engine` settings.
* Ensured search suggestions are shown when entering search term into omnibox and enable search suggestions modal is not shown in the omnibox area. 
* Ensured search suggestions are now shown when entering invalid/suspicious search terms. 
* Ensured disabling `Show Search Suggestions` will not show search suggestions. 
* Ensured changing default SE will still show search suggestions. 

example | example | example | example | example
---|---|---|---|---

**Brave Not Default SE (Singapore)**

* Ensured `Show Search Suggestions` is disabled in Search Engine settings for region where Brave is not default. 
* Ensured that enable search suggestions dialog is shown in omnibox.
* Ensured that search suggestions are shown after opting in the omnibox and the setting is not enabled in Search Engine settings. 

example | example | example | example | example
---|---|---|---|---


**Brave Not Default SE (South Africa)**

* Ensured `Show Search Suggestions` is disabled in Search Engine settings for region where Brave is not default. 
* Ensured that enable search suggestions dialog is shown in omnibox.
* Ensured that search suggestions are shown after opting in the omnibox and the setting is not enabled in Search Engine settings. 

example | example | example
---|---|---
