### ISSUE TITLE
[iOS] - Add Receipt Viewer UI

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#38132]
## Description: 
- We need a UI that allows us to view receipts on device and decode them.

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6
Brave build: 1.68 (124)
BraveCore: 1.68.124 (127.0.6533.57)
```
---------------------------

**STEPS:**
1. Launch Brave
2. Open `Dev menu`
3. Find `StoreKit Receipt Viewer` > *Verify*

**ACTUAL RESULTS:**
- Verified that `StoreKit Receipt Viewer` is present and shows `In-App Purchases` data for both `VPN` and `Leo` subscriptions

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/0198fa1e-253d-4fd0-8989-4824f403a7f4) | ![2](https://github.com/user-attachments/assets/f2bcd0ca-fcdc-4f59-bf65-36d31328db37) | ![3](https://github.com/user-attachments/assets/a1d379ac-f47b-49a8-8736-1b3088f8b8ee) | ![4](https://github.com/user-attachments/assets/24525104-8647-490f-a8ac-7ac9d3200ef0) |
| ![1](https://github.com/user-attachments/assets/1a161ef3-73bf-45fb-a0dd-1e0162f8e70e) | ![2](https://github.com/user-attachments/assets/0c832870-4c9e-4a03-a9c7-f494b4f5b0d6) | ![3](https://github.com/user-attachments/assets/dcc65d09-3db4-44bd-970b-ee7beac7d38c) | ![4](https://github.com/user-attachments/assets/3df08f40-d61b-4ce2-a5f7-810ce773771f) |
