### ISSUE TITLE
FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! You probably need to enable user namespaces in your kernel. See https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux for more information.

### ISSUE THREAD

**Issue by darkvader1996** [brave/brave-browser#3814]
<!-- Have you searched for similar issues? Before submitting this issue, please check the open issues and add a note before logging a new issue. 

## Description 
Brave browser won't work in linux

## Steps to Reproduce

Download and install Brave browser, on ubuntu 18.04x64

## Actual result:
Won't boot and it will show this message on linux logs
i have enabled user namespaces still doesn't work

FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! You probably need to enable user namespaces in your kernel. See https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux for more information.

## Expected result:

Brave browser boot

## Brave version (brave://version info)

It was installed yesterday so i guess it's the last one

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Tried Beta, developer, all branchs, same result
i have enabled user namespaces still doesn't work

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
i have enabled user namespaces still doesn't work

Just created this account in order to notify this error and hope it get solved, thank you.

**Comment by srirambv** [comment]
Please add relevant info and reopen the issue

**Comment by darkvader1996** [comment]
@srirambv  okay, sorry! for some reason the description didn't came out
