### ISSUE TITLE
[cr125] bookmarks panel checkbox color is weird when editing

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#38152]
## Steps to Reproduce

   1. Open bookmarks panel
   2. Add any bookmark items
   3. Click edit button in the panel
   4. 

## Actual result:

![Screenshot from 2024-05-08 15-00-47](https://github.com/brave/brave-browser/assets/6786187/5e185722-0ff1-4a28-a5ab-fc1ab323623b)

## Expected result:
![Screenshot from 2024-05-08 15-00-19](https://github.com/brave/brave-browser/assets/6786187/1df51804-d159-4232-bd3b-b38a444a87da)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron cc: @brave/qa-team

**Comment by simonhong** [comment]
fixing..

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.66.104 Chromium: 125.0.6422.41 (Official Build) (64-bit)
-- | --
Revision | 6213f85e37bb676772fb221ce11a41c2b1be0fe2
OS | Windows 11 Version 23H2 (Build 22631.3527)
```
Case 1: New Install - `PASSED` 
<details>

1. Installed 1.66.104
2. launched Brave
3. clicked  `import bookmarks now...` in a new tab 
4. selected `Google Chrome Person 1`
5. clicked `Import` > Done
6. navigated youtube.com and bookmarked the site
7. enabled sidebar and clicked bookmarks button
8. clicked `Bookmarks` in the bookmarks panel
9. clicked `Edit` button

#### Confirmed checkbox blurple color shown

example | example | example | example 
------- | ------ | ------ | ------
![image](https://github.com/brave/brave-browser/assets/98358127/3055bdbe-8610-411c-8fa6-29b1372d7d0f)|![image](https://github.com/brave/brave-browser/assets/98358127/54882d95-6f2e-4da5-91ef-08edfe53d39b)|![image](https://github.com/brave/brave-browser/assets/98358127/e5e3cf61-f347-4421-8c0e-eebbc6b5485e)|![image](https://github.com/brave/brave-browser/assets/98358127/dbdbe1bf-c8a6-4072-a4aa-d256cf0fbc6b)
</details>

Case 2: Upgrade - `PASSED`
<details>

1. Installed 1.65.130
2. launched Brave
3. imported bookmarks from `Google Chrome Person 1`
4. clicked `Import` > Done
5. enabled sidebar and clicked bookmarks button
6. clicked `Bookmarks` in the bookmarks panel
7. clicked `Edit` button
8. upgraded to 1.66.104 
9. clicked `bookmarks` on the sidebar
10. clicked `Bookmarks` in the bookmarks panel
11. clicked `Edit` button

#### Confirmed checkbox blurple color shown

example | example   
------- | ------  
![image](https://github.com/brave/brave-browser/assets/98358127/b416842a-8185-46dd-8b09-403d641fd9f2)|![image](https://github.com/brave/brave-browser/assets/98358127/37117b6a-e09e-4b9d-adef-4e0d528f7fb2)
</details>
