### ISSUE TITLE
[Android] Dynamic price discount for VPN plan

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#38154]
This issue to update the price discount with dynamic calculations for the VPN plan page.

**Comment by kjozwiak** [comment]
The above requires `1.66.105` or higher for `1.66.x` verification 👍 @btlechowski @srirambv @GeetaSarvadnya @hffvld mind running through again like we did earlier once we get `1.66.105`? This way we'll have `India`, `Poland` & `US` covered which should be enough for verification.

**Comment by hffvld** [comment]
### `USA`

Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240322.023 release-keys
Brave build: 1.66.105
Chromium: 125.0.6422.41 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/23500#issue-2285068639
2. *Verify*

**ACTUAL RESULTS:**

```
Monthly price * 12 = Yearly price
$9.99 * 12 = $119.88

Actual yearly price = yearly price of the subscription
$99.99

Yearly price - Actual yearly price = Discount
$119.88 - $99.99 = $19.89

(Discount / Yearly price) × 100 = Discount Percentage
($19.89 / $119.88) * 100 = 16.59%
```

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/20e9fa0e-1b7f-4375-a6e3-6bb6b657aae2) | ![2](https://github.com/brave/brave-browser/assets/128532965/1e67817d-e4a5-4776-9e79-ef082e2a8cad) |

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 14` using the following build(s):

```
Brave | 1.66.110 Chromium: 125.0.6422.60 (Official Build) (64-bit)
--- | ---
Revision | de593d76e2ca4d02faa85bf1ca27bcf3ee46793c
OS | Android 14; Build/AP21.240305.005; 34; REL
```

#### `Canada` verification

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/23500#issue-2285068639, went through the following calculation via `Canada`:

```
Yearly price = monthly price * 12 ---> $13.99 * 12 = $167.88
Actual yearly price = yearly price of the subscription ---> $139.99
Discount = Yearly price - Actual yearly price ---> $167.88 - $139.99 - $27.89
Discount Percentage = (Discount / Yearly price) × 100 ---> ($27.89 / $167.88) * 100 = 16.61% Discount (appears as 17% via the premium modal)
```

![Screenshot_20240516-135618](https://github.com/brave/brave-browser/assets/2602313/a24083fb-9d6d-4c50-9a6d-5c7e4f061eb0)

**Comment by btlechowski** [comment]
Verification passed on Brave v1.66.110 on Lenovo TB-8506FS (Android 11.0)


### Poland

`The percentage discount is: 16.65% so 17%`

![image](https://github.com/brave/brave-browser/assets/34715963/1a1a95c5-c757-4db2-9624-3be202fcb1cc)
