### ISSUE TITLE
AI Chat: Integrate search events from the Conversation API

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#38155]
The Conversation API is now returning events related to Brave Search. We can implement the designed statuses:

- Search in progress
<img width="357" alt="image" src="https://github.com/brave/brave-browser/assets/741836/d8be4507-6015-4360-8812-0760a0fc9534">

- Search queries used to generate a response
<img width="354" alt="image" src="https://github.com/brave/brave-browser/assets/741836/31185c1c-73b8-44f7-be00-e2ac27efd3cb">

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.67.92 Chromium: 125.0.6422.76 (Official Build) beta (64-bit)
-- | --
Revision | d751d2edf40b466560aaeecc4c4919041f41c20d
OS | Windows 11 Version 23H2 (Build 22631.3593)
```

1. Installed 1.67.92
2. launched Brave with `--enable-logging=stderr --v=2 --enable-features=AIChat:conversation_api/true --env-leo=staging --env-ai-chat.bsg-dev --env-ai-chat-premium.bsg.dev--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev`
3. logged in as a Leo premium user
4. opened `brave://settings/leo-assistant` in a new tab
5. switched to `Claude 3 Sonnet` from default `Mixtral`


 `Claude 3 Sonnet` 

Confirmed `Search in progress` & `Search queries used to generate a response` statuses are shown

 example | example | example | example 
 ------ | ----- | ------ | ------
![image](https://github.com/brave/brave-browser/assets/98358127/13fb7b04-a208-4138-9201-b227f07ea181)|![image](https://github.com/brave/brave-browser/assets/98358127/cbfacac9-fb1f-4761-8f55-cba68c23554f)|![image](https://github.com/brave/brave-browser/assets/98358127/57ab861c-3495-4f9f-88b2-53a03b84a74d)|![image](https://github.com/brave/brave-browser/assets/98358127/47f3059d-f47c-4b26-bcd6-9a57d849501f)

`Claude 3 Haiku`  - `PASSED`

Confirmed `Search in progress` & `Search queries used to generate a response` statuses are shown

 example | example | example | example 
 ------ | ----- | ------ | ------
![image](https://github.com/brave/brave-browser/assets/98358127/9380d26e-c734-4aa1-a451-9bf914780f55)|![image](https://github.com/brave/brave-browser/assets/98358127/892ac594-4f2b-4eeb-b836-e4614d883904)|![image](https://github.com/brave/brave-browser/assets/98358127/b44c4c99-5afd-43a1-8fe8-795a63aceb78)|![image](https://github.com/brave/brave-browser/assets/98358127/9e73c259-417b-4224-9fcc-6e76e787392b)

`Claude Instant` - `Failed`

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.67.113 Chromium: 126.0.6478.56 (Official Build) (64-bit) 
Revision	2c6c9c73e7382e94dd9f7327dff55cb1fe56ff59
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured `improved answer with Brave Search` loader is shown for queries.
- Ensured search integration is working with all models for free and premium users.
- Ensured chat responses are labelled using `Improved answer searching...`.

Mixtral | Haiku | Sonnet | Llama
-|-|-|-
![Screenshot 2024-06-12 at 11 09 51 AM](https://github.com/brave/brave-browser/assets/17885425/bc2d6d40-b0ab-4650-99e4-b4380a92e44c) | ![Screenshot 2024-06-12 at 11 11 08 AM](https://github.com/brave/brave-browser/assets/17885425/5d0f0228-d7dd-45b5-90ad-a729824e34f5) | ![Screenshot 2024-06-12 at 11 17 10 AM](https://github.com/brave/brave-browser/assets/17885425/4d82034a-6ae9-4380-ba3f-674eb47fe30e) | ![Screenshot 2024-06-12 at 11 27 38 AM](https://github.com/brave/brave-browser/assets/17885425/0f1432ae-8744-42a1-9ff3-5121c9b539cd)
