### ISSUE TITLE
Brave Browser Android Push Notification pop-ups

### ISSUE THREAD

**Issue by Roxelanne** [brave/brave-browser#38169]
Brave browser on Android blocks most of the pop-ups for notification requests from websites. 

Settings> Website Notifications> Notifications toggle is on (Websites can ask for notifications) and the "snooze notification requests" option is unchecked. 

Still Brave Shields blocks all of the pop-ops most of the websites. You can check www.karar.com to reproduce the issue. Enter the site and close the Brave shields for that website buy clicking lion icon. Refresh the site and here you get the notification request pop-up. 

Version: Brave 1.65.126 - Chromium 124.0.6367.118 
- Android 14. 

Note: In the privacy settings I let all Google - Twitter or whatever. Shields are set up on mid level. Not added extra filter lists.

**Comment by kenherbert** [comment]
You don't see the notification request with Shields up because it is not a native notification request - it is a request generated by a tracking script Brave is blocking.

If the site was properly using native notification requests you would see it.

**Comment by Roxelanne** [comment]
The website I provided is an example. How is possible that all websites in my country/language are not using proper notification workflow?
