### ISSUE TITLE
Brave nightly connects to clientservices.googleapis.com on startup

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#3816]
Just installed Version 0.64.7 Chromium: 73.0.3683.75 (Official Build) nightly (64-bit).

<img width="651" alt="Screen Shot 2019-03-20 at 14 33 11" src="https://user-images.githubusercontent.com/639937/54720784-88a28d80-4b1d-11e9-9b6e-a04bf921a491.png">

**Comment by bbondy** [comment]
@tomlowenthal Do you know the full URL? I think we have a network audit in CI so not sure why it wouldn't catch it.
Only Nightly?

**Comment by tomlowenthal** [comment]
I *think* only Nightly, but I didn't reinstall Dev yesterday to check. It's not a behavior I've seen before, but I think the last time I tested was about a week ago with Dev. I don't have the URL because my firewall couldn't get that out of the HTTPS connection.

**Comment by pilgrim-brave** [comment]
Potential sources:

- `components/metrics/url_constants.cc::kNewMetricsServerUrl`
- `components/variations/variations_url_constants.cc::kDefaultServerUrl`

**Comment by pilgrim-brave** [comment]
OK according to PJ it's `kNewMetricsServerUrl`

**Comment by simonhong** [comment]
I think this happened by https://github.com/brave/brave-core/pull/1985.
That PR turned on metrics reporting by default for dev/nightly.
That means latest dev have same issue if user don't  it off explicitly.
So, stable/beta could have this issue when user turn on crash reporting explicitly.

**Comment by jumde** [comment]
Re-opened with C74 revert

**Comment by srirambv** [comment]
@jumde any test plan for the CI builds? I only see `npm` tests on #3816.

**Comment by kjozwiak** [comment]
Assuming @LaurenWags and myself can check using Little Snitch to make sure we're not connecting to `clientservices.googleapis.com` at startup. As @srirambv mentioned above, is there a better way to Win/Linux?

**Comment by jumde** [comment]
@kjozwiak @srirambv - Fiddler works really well on Win/Linux https://www.telerik.com/download/fiddler

@btlechowski @srirambv - Test plan specified here: https://github.com/brave/brave-core/pull/2095

Let me know if you have any questions.

**Comment by btlechowski** [comment]
On Windows 10 x64, Brave connects to `gvt1.com` domain.

Steps:
1. Clean profile
2. Go to settings through hamburger menu

URLs:
```
http://redirector.gvt1.com:443
https://redirector.gvt1.com/edgedl/chrome/dict/en-us-8-0.bdic
http://r5---sn-f5f7lnel.gvt1.com:443
https://r5---sn-f5f7lnel.gvt1.com/edgedl/chrome/dict/en-us-8-0.bdic?cms_redirect=yes&mip=188.121.0.11&mm=28&mn=sn-f5f7lnel&ms=nvh&mt=1554156499&mv=m&pl=19&shardbypass=yes

```

Tested on

Brave | 0.62.49 Chromium: 73.0.3683.86 (Official Build) (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Windows 10 OS Build 17134.523

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.62.49 Chromium: 73.0.3683.86 (Official Build) (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Windows 10 OS Build 17134.523

Brave | 0.63.28 Chromium: 73.0.3683.75 (Official Build) beta (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

Used test plan from https://github.com/brave/brave-core/pull/2095
Reproduced https://github.com/brave/brave-browser/issues/1947 while testing

**Comment by kjozwiak** [comment]
@LaurenWags if the above worked for you, can you label this as `QA/Passed` for macOS? Thanks!
