### ISSUE TITLE
Top Sites' orange checkmark should be blue/blurple - Favorites is a missing image

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#38173]
## Description 

Top Sites' orange checkmark should be blue/blurple - Favorites is a missing image

## Steps to Reproduce

1. install
2. launch Brave
3. open a new-tab page
4. click on `Customize` at the bottom
5. click on `Top Sites`
6. notice the missing image for `Favorites` and the orange checkmark (should be blue/blurple) on `Frequently Visited`

## Actual result:

<img width="2009" alt="Screen Shot 2024-05-08 at 2 33 45 PM" src="https://github.com/brave/brave-browser/assets/387249/42a0a5a5-ddf0-4a3d-a6b0-2a9d0a59b448">

## Expected result:

the Favorites image should be present, and the orange checkmark should be blue/blurple-colored

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.67.76 Chromium: 125.0.6422.26 (Official Build) nightly (x86_64)
-- | --
Revision | c8696983cac61f6c5a22bc23ca991c20737fd0b0
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Partially; no broken image`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @fallaciousreasoning @rebron @brave/qa-team

**Comment by stephendonner** [comment]
<img width="2009" alt="Screen Shot 2024-05-08 at 3 04 18 PM" src="https://github.com/brave/brave-browser/assets/387249/4b18855c-2e42-46e6-a729-e4b7e5d0a8a1">

**Comment by fallaciousreasoning** [comment]
@stephendonner is this on the Intel Mac?

**Comment by fallaciousreasoning** [comment]
(the missing images)

**Comment by stephendonner** [comment]
> @stephendonner is this on the Intel Mac?

@fallaciousreasoning Yes; let me check on `macOS-arm64` and report back, too 👍

**Comment by stephendonner** [comment]
> (the missing images)

fine using:

```
Brave | 1.67.77 Chromium: 125.0.6422.26 (Official Build) nightly (arm64)
-- | --
Revision | 1bc6f60ef45b0a540cbc7dc10cada06d5c78f58f
OS | macOS Version 13.6.4 (Build 22G513)
```

<img width="1630" alt="Screenshot 2024-05-08 at 5 23 12 PM" src="https://github.com/brave/brave-browser/assets/387249/4275e9d2-f8fd-4561-8487-a6fbcaffd3ad">

**Comment by fallaciousreasoning** [comment]
Hmmm, I was afraid of that.

**Comment by fallaciousreasoning** [comment]
@aguscruiz do we have the source images from this dialog somewhere? Unfortunately they're PNGs with the icon baked into them so I can't edit them easily.

**Comment by aguscruiz** [comment]
I can re do them, it wouldn't be a big deal. 
I'll link you to it, I can have create them as SVG even

**Comment by fallaciousreasoning** [comment]
Figma file (so I don't lose it): https://www.figma.com/design/xjmYkVb0sPD31xxAV1MFhS/Customize-NTP-modal?node-id=0-1

**Comment by kjozwiak** [comment]
The above requires 1.66.107` or higher for `1.66.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.66.107 Chromium: 125.0.6422.41 (Official Build) (x86_64)
-- | --
Revision | 188213f024297511fc5e37efe56eabde5992b300
OS | macOS Version 11.7.10 (Build 20G1427)
```

### `Light` mode

example | example
---------|---------
<img width="1312" alt="Screen Shot 2024-05-14 at 10 07 03 AM" src="https://github.com/brave/brave-browser/assets/387249/406fa218-2e27-42c3-b7e5-cb0da8854f29"> | <img width="1312" alt="Screen Shot 2024-05-14 at 10 07 07 AM" src="https://github.com/brave/brave-browser/assets/387249/0a5f59d7-4d0e-4b10-a407-5d1d8fa46728">
