### ISSUE TITLE
incorrect SE being used after upgrading when upgrading to `C125`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#38179]
## Description 

In some cases, when a user upgrades from `C124` -> `C125`, the incorrect SE is being used in certain cases. In this particular example, if you have `Startpage` selected as `Normal` and `Bing` as `Private`, upgrading to `C125` will make it appear like `Bing` is selected, but if you go into the `Private` list of SE, you'll notice that `Startpage` is selected/being used rather than `Bing`.

Assuming this is due to `Bing` being changed to `Microsoft Bing` in `C125`.

## Steps to reproduce 

   1. download/install `1.67.64 Chromium: 124.0.6367.118`
   2. go into `Settings` -> Search engines` and change `Normal` to `Startpage` and `Private` to `Bing`
   3. upgrade to `1.67.74 Chromium: 125.0.6422.26`

You'll notice that `Bing` is selected but if you go into the `Private` SE selection, you'll notice `Startpage` is being used.

## Actual result 

https://github.com/brave/brave-browser/assets/2602313/0bf085a2-57d7-4824-84ab-27f5d15057f0

## Expected result

Brave should use the same SE the user has selected as default rather than using something different (`Startpage` rather than `Bing`)

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A` (however, it's in the `1.66.x` RC)
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 14`
   
## Brave version

```
Brave | 1.67.74 Chromium: 125.0.6422.26 (Official Build) canary (64-bit)
--- | ---
Revision | 8abe16ff01716bd4851b1dcc432ec3c662d121c9
OS | Android 14; Build/AP21.240305.005; 34; REL
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by kjozwiak** [comment]
@LaurenWags adding the `OS/Desktop` just to quickly check to make sure that `Microsoft` Bing` was renamed to `Bing` and didn't cause any issues. The above issue mentioned above is only for `Android` but would be worth double checking on `Desktop` to make sure nothing obvious regressed with the SE list for `Normal` & `Private`. Can go through something similar as https://github.com/brave/brave-core/pull/23526#issuecomment-2108428678.

**Comment by kjozwiak** [comment]
The above requires `1.66.107` or higher for `1.66.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240322.023 release-keys
Brave build: 1.66.107
Chromium: 125.0.6422.41 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Install and launch Brave `1.65.129` with `Cr129`
2. Go to `Settings` > Search engines > Change `Standard` to `Startpage` and `Private` to `Bing`
3. Upgrade Brave to `1.66.107` or newer
4. Launch Brave > Go to `Settings` > Search engines > *Verify*

**ACTUAL RESULTS:**
- Verified that `Startpage` is still set as SE for the `Standard` tab after Brave upgrade
- Verified that `Bing` is still set as SE for the `Private` tab after Brave upgrade

---------------------------

https://github.com/brave/brave-browser/assets/128532965/6c9b9d0e-cac2-4a24-b9ec-db5ee72b6013

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.66.108 Chromium: 125.0.6422.41 (Official Build) (64-bit)
-- | --
Revision | 3a79189ba4e3cf17c382dd265d4f447f83a8f49d
OS | Windows 10 Version 22H2 (Build 19045.4291)
```
Confirmed that `Startpage` is still set as SE for the Normal windows after Brave upgrade to CR 125
Confirmed that `Bing` is still set as SE for the Private window after Brave upgrade to CR 125

**1.65.133 - CR 124** | **1.66.108 - CR 125**
------------------------|--------------------------
![image](https://github.com/brave/brave-browser/assets/38657976/6f2180b0-b401-48f5-96dd-85fe4b574415) | ![image](https://github.com/brave/brave-browser/assets/38657976/35018d1d-e902-483b-a3da-63fc20e913c3)

Search in normal window | Search in private window
-----------------------------|--------------------------
![image](https://github.com/brave/brave-browser/assets/38657976/ffa62ff4-e773-4a3e-b7ae-1de20c3146d3) | ![image](https://github.com/brave/brave-browser/assets/38657976/a41b2778-b2fe-4335-8dcf-91af4fc35afd)
