### ISSUE TITLE
Multiple windows not able to close or merge from settings

### ISSUE THREAD

**Issue by tapanmodh** [brave/brave-browser#38170]
## Description 
If more than one window is already opened and we tries to disable it from `Enable multiple windows`, It opens new dialog with merge windows or close windows buttons but buttons are not working.

## Steps to reproduce 

   1. Enable multiple windows from `Settings -> Appearance -> Enable multiple windows`
   2. Create `New window` from three dot menu. So that we have two windows.
   3. Now go back to `Settings -> Appearance` and tries to disable `Enable multiple windows`
   4. Dialog will display with `Merge windows` and `Close windows`. 
   5. Tap on any of these two buttons. Nothing is happening.

## Actual result 
On tap of `Merge windows` nothing is happening
On tap of `Close windows` nothing is happening

## Expected result
On tap of `Merge windows` should opens chromium dialogs of Move tabs between windows.
On tap of `Close windows` should close other window and disable `Enable multiple windows`

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? 1.67.73

## Device details
   - Install type (ARM, x86): arm64
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: Android 14
   
## Brave version 
1.67.73

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.66.105` or higher for `1.66.x` verification 👍
