### ISSUE TITLE
"This is a secondary installation of Brave, and cannot be made your default browser."

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#3817]
Just installed version 0.64.7 Chromium: 73.0.3683.75 (Official Build) nightly (64-bit)
<img width="981" alt="Screen Shot 2019-03-20 at 14 38 03" src="https://user-images.githubusercontent.com/639937/54721070-46c61700-4b1e-11e9-8f96-a9fc24a5196d.png">

Reader, I was able to set Brave as my default browser manually. Looks fine on Dev, but not nightly.

**Comment by rebron** [comment]
cc: @simonhong

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

Used test plan from the description.
