### ISSUE TITLE
QR code is not shown on deposit screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#38185]
## Description 

QR code is not shown on deposit screen

## Steps to Reproduce

   1. Go to deposit screen
   2. Select a token and click on Deposit
   3. QR code is not shown
   4. Right click on broken image and open in new tab shows QR code
   5. Console logs error

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/b6f42e34-0042-47aa-bb1b-94696f6a21c6

## Expected result:
Should show QR code

## Reproduces how often: 

Easy

## Brave version (brave://version info)

 
Brave | 1.65.130 Chromium: 124.0.6367.159 (Official Build) (64-bit)
-- | --
Revision | 67843557ad274aba4b206391773c789c174b7fad
OS | Windows 11 Version 23H2 (Build 22631.3527)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No but on RC build
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:
cc: @Douglashdaniel @diracdeltas @josheleonard 
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by josheleonard** [comment]
Fixed by: [fix(wallet): display account blockies](https://github.com/brave/brave-core/pull/23027#top)
