### ISSUE TITLE
[CR125] Tab search button icon is hidden when hovered/pressed

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#38182]
## Steps to Reproduce

   1. Hover/Press tab search button
   2. Enable vertical tab mode and check search button
   3. 

## Actual result:

Image is invisible when hovered/pressed
![image](https://github.com/brave/brave-browser/assets/6786187/586198be-a5f2-433e-aaf5-6c491e5fb1f8)
![image](https://github.com/brave/brave-browser/assets/6786187/a7c1afa8-d90d-493c-98dd-1c13b03adac9)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @rebron @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.66.105` or higher for `1.66.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.66.105 Chromium: 125.0.6422.41 (Official Build) (64-bit)
-- | --
Revision | ba88d7bb175a55287d14014823d5da31fe9c8a47
OS | Windows 10 Version 22H2 (Build 19045.4291)
```
Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/38182#issue-2286828123, ensured that the Search button is being displayed when clicked as per the following:

![image](https://github.com/brave/brave-browser/assets/38657976/1530d67e-c1ac-4aa2-baf4-7881cdade5df)
