### ISSUE TITLE
[Brave News]: Remove small "News" Card from above peeking card

### ISSUE THREAD

**Issue by LorenzoMinto** [brave/brave-browser#38188]
When News is enabled we should only show the peeking card. This is already the case if the Search bar widget is enabled.
![Screen Shot 2024-05-08 at 4 15 37 PM](https://github.com/brave/brave-browser/assets/13190144/369cfca7-cf55-4f8c-ad0d-64d9e9fd789f)

**Comment by akash-Sa19** [comment]
Hello, @LorenzoMinto this is my first time contributing to open source, and I like to fix this issue. I have read all the contribution guidelines and Triage guidelines document pages.

**Comment by jsonOdison** [comment]
Has it been fixed yet if not I'll take a crack at it 😁
