### ISSUE TITLE
Profile avatar hover effect obscures icon

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#38187]
## Steps to Reproduce

   1. Visit brave://settings/manageProfile
   2. Hover mouse over any of the icons in the "Pick an avatar" section
   3. 

## Actual result:

An overlay obscures the selected "Avatar Edgy Brave" icon.

![Screenshot 2024-05-09 092541](https://github.com/brave/brave-browser/assets/5033691/62a0dd23-f432-49d2-8830-9b5751989a25)

## Expected result:

It seems like the overlay should be a hover background for the icon, rather than appearing on top of the icon instead.

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

This was with a development build from latest master.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
I can reproduce the issue using:

```
Brave | 1.67.76 Chromium: 125.0.6422.26 (Official Build) nightly (x86_64)
-- | --
Revision | c8696983cac61f6c5a22bc23ca991c20737fd0b0
OS | macOS Version 13.6.6 (Build 22G630)
```

but not with

```
Brave | 1.66.104 Chromium: 125.0.6422.41 (Official Build) (x86_64)
-- | --
Revision | 6213f85e37bb676772fb221ce11a41c2b1be0fe2
OS | macOS Version 13.6.6 (Build 22G630)
```

1.67.76 Chromium: 125.0.6422.26 | 1.66.104 Chromium: 125.0.6422.41
--- | ---
<img width="302" alt="Screenshot 2024-05-09 at 9 36 15 AM" src="https://github.com/brave/brave-browser/assets/28145373/14d38246-6c6c-4bdb-a701-aa3b5af594c6"> | <img width="375" alt="Screenshot 2024-05-09 at 9 35 18 AM" src="https://github.com/brave/brave-browser/assets/28145373/7d288c8c-3252-488b-aefc-ea36ba4e6230">

**Comment by emerick** [comment]
Seems to be related to the `--bg-hover` on `leoButton.isPlain`, from what I can see in DevTools cc: @petemill @fallaciousreasoning

**Comment by emerick** [comment]
@mkarolin and I think this may have been introduced in the latest Nala bump via this commit: https://github.com/brave/leo/commit/b38c5079e208574723c006401c20a373119b2c48 cc: @AlanBreck

**Comment by AlanBreck** [comment]
It appears that the problem is that these avatar buttons don't actually have content, but rather set a background image on the parent element (`<cr-button>`). As such, when the `<button>` element within `<leo-button>` is hovered, it overlays the background image from the parent.

I believe the appropriate solution for this is to ensure that `<leo-button>` sets the `fab` attribute for avatars, as this will remove the background on hover. I _think_ that would get set here: https://github.com/brave/brave-core/blob/b9b56dbdb6f0b8bcc3d589a7de5bff08b1b8c5b6/ui/webui/resources/cr_elements/cr_button/cr_button.ts#L58-L60 cc @fallaciousreasoning

**Comment by kjozwiak** [comment]
The above requires `1.67.83` or higher for `1.67.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.67.86 Chromium: 125.0.6422.60 (Official Build) beta (x86_64)
-- | --
Revision | a1f8e8f462d422d4b924fa9c34246f68862b21ad
OS | macOS Version 13.6.7 (Build 22G720)
```
