### ISSUE TITLE
Simplify Onboarding and Privacy hub panels

### ISSUE THREAD

**Issue by iccub** [brave/brave-browser#38190]
This also reduces the app size a bit

**Comment by kjozwiak** [comment]
The above requires `1.66.107` or higher for `1.66.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.5
Brave build: 1.66 (108)
BraveCore: 1.66.108 (125.0.6422.41)
```
---------------------------

**ACTUAL RESULTS:**
- Verified that Brave `onboarding` is working as expected
- Verified that `Privacy Hub` is working as expected
