### ISSUE TITLE
[ads] Restoring window does not resume landed counter

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#38191]
Follow up to: https://github.com/brave/brave-browser/issues/36603

## Steps to Reproduce

1. Clean profile
2. Trigger ad
3. Start landed counter
4. Minimize the browser window
5. Restore the browser window

Note: the counter was suspended on minimize.

## Actual result:

Landed counter is not resumed

## Expected result:
Landed counter is resumed

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.66.104 Chromium: 125.0.6422.41 (Official Build) (64-bit)
-- | --
Revision | 6213f85e37bb676772fb221ce11a41c2b1be0fe2
OS | Linux

cc @tmancey @aseren @iambrianfung

**Comment by kjozwiak** [comment]
The above requires `1.66.105` or higher for `1.66.x` verification 👍

**Comment by btlechowski** [comment]
Verified with

Brave | 1.66.105 Chromium: 125.0.6422.41 (Official Build) (64-bit)
-- | --
Revision | ba88d7bb175a55287d14014823d5da31fe9c8a47
OS | Linux

Issue still reproducible, logged: https://github.com/brave/brave-browser/issues/38234
