### ISSUE TITLE
Re-enable network service

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#3819]
Work to get us on Chromium 74 disabled the network service.
This issue is to track work needed to enable the network service by default.
https://github.com/brave/brave-core/pull/2013/commits/9257ced4da3931e81d0a580d0eb8fc6bd582f603

**Comment by mkarolin** [comment]
Related: https://github.com/brave/brave-browser/issues/2351

**Comment by bbondy** [comment]
Oops I'll just dupe to that and add a comment there 👍
