### ISSUE TITLE
[ads] Landed counter is not suspended after URL navigation

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#38193]
Follow up to: https://github.com/brave/brave-browser/issues/36603

## Steps to Reproduce

1. Clean profile
2. Trigger ad
3. Start landed counter
4. Type `t` in URL bar and press `Enter`

## Actual result:

Landed counter is not suspended after URL navigation
Landed counter is still active. Ad is marked landed even after navigation to another page 

## Expected result:
Landed counter is suspended
OR
Landed counter is canceled

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.66.104 Chromium: 125.0.6422.41 (Official Build) (64-bit)
-- | --
Revision | 6213f85e37bb676772fb221ce11a41c2b1be0fe2
OS | Linux

cc @tmancey @aseren @iambrianfung

**Comment by tmancey** [comment]
@btlechowski what happens if you enter a valid URL instead of `t`?

**Comment by tmancey** [comment]
Closing as will be resolved by https://github.com/brave/brave-browser/issues/38191

**Comment by kjozwiak** [comment]
The above requires `1.66.105` or higher for `1.66.x` verification 👍

**Comment by btlechowski** [comment]
Verified with

Brave | 1.66.105 Chromium: 125.0.6422.41 (Official Build) (64-bit)
-- | --
Revision | ba88d7bb175a55287d14014823d5da31fe9c8a47
OS | Linux

Verified test plan from the description

Verified landed counter is canceled:
```
[8390:8390:0513/222134.599808:VERBOSE1:ad_handler.cc(183)] Canceled page land for creative instance id c1bbef73-5201-4ccd-9ed0-d897610d6a0e on tab id 1715014670

```
