### ISSUE TITLE
[ads] Landed counter is not suspended when browser goes to background

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#38194]
Follow up to: https://github.com/brave/brave-browser/issues/36603

## Steps to Reproduce

1. Clean profile
2. Trigger ad
3. Start landed counter
4. Put Brave window to background (bring another application forward)

## Actual result:

Landed counter is not suspended

## Expected result:
Landed counter is suspended

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.66.104 Chromium: 125.0.6422.41 (Official Build) (64-bit)
-- | --
Revision | 6213f85e37bb676772fb221ce11a41c2b1be0fe2
OS | Linux

cc @tmancey @aseren @iambrianfung

**Comment by tmancey** [comment]
Closing as resolved by https://github.com/brave/brave-browser/issues/38191

**Comment by kjozwiak** [comment]
The above requires `1.66.105` or higher for `1.66.x` verification 👍

**Comment by btlechowski** [comment]
Verified with

Brave | 1.66.105 Chromium: 125.0.6422.41 (Official Build) (64-bit)
-- | --
Revision | ba88d7bb175a55287d14014823d5da31fe9c8a47
OS | Linux

Verified test plan from the description

Verified landed counter is suspended when browser goes background:
```
[8885:8885:0513/222552.956673:VERBOSE1:ad_handler.cc(153)] Suspended page landing on tab id 301581231 with 17.8792 s remaining

```

Verified landed counter is resumed when browser goes foreground:
```
[8885:8885:0513/222551.827871:VERBOSE1:ad_handler.cc(159)] Resumed page landing on tab id 301581231 and maybe land in 18.9976 s

```
