### ISSUE TITLE
[iOS] Update search engine default for IT

### ISSUE THREAD

**Issue by iccub** [brave/brave-browser#38192]
Desktop issue: https://github.com/brave/brave-browser/issues/38028

**Comment by kjozwiak** [comment]
The above requires `1.67.109` or higher for `1.67.x` verification 👍

**Comment by kjozwiak** [comment]
@Uni-verse @hffvld we'll need to check both `iPhone` & `iPad` using the template from https://github.com/brave/brave-core/pull/23539#issuecomment-2153082399. We'll need to run through the following:

* `Test Case #1` - Run through Italy (new locale being added re: `Brave Search` being the default)

* `Test Case #2` - Pick one of the previous locales via https://github.com/brave/brave-core/pull/23539/files#diff-02620ad38a4fb15c7ba4d13fcbb764e9f40b7956633a44563552802e83d56c2fR87 and run through the template. I checked `DE` so please a different one

* `Test Case #3` - Pick a random locale that's not listed via https://github.com/brave/brave-core/pull/23539/files#diff-02620ad38a4fb15c7ba4d13fcbb764e9f40b7956633a44563552802e83d56c2fR87 and ensure everything is still working using the template mentioned above.

**Comment by Uni-verse** [comment]
In progress on `iPhone 12` running `iOS 17.3.1` using version `1.67.115`

**IT (Italy) - PASSED**

<details><summary>Clean profile</summary>

* ensured that `Brave Search` was selected as the default for both Standard/Private tab via `Search Engines` in `Settings`
* ensured that `Brave Search` was the first engine via the drop down list under `Search Engines` for `Standard` tab
* ensured that `Brave Search` was the first engine via the drop down list under `Search Engines` for `Private` tab

Example | Example | Example
-|-|-
![IMG_6392](https://github.com/brave/brave-browser/assets/17885425/3daed67f-9b03-4150-b673-a8436f9398c1) | ![IMG_6393](https://github.com/brave/brave-browser/assets/17885425/63c39e49-b90a-40f0-bb25-750676a80b6c) | ![IMG_6394](https://github.com/brave/brave-browser/assets/17885425/9ea3137f-3dee-49d9-819c-97fb12f34c77)

</details>

<details><summary>Updated Profile (Google/Google)</summary>

* installed `1.66.x`
* ensured that `Google` was the default SE selected under `Search Engines` for both `Standard` & `Private` tab
* updated to `1.67.115` and ensured that `Google` is still the default SE for `Standard` & `Private` tabs
* ensured that `Brave Search` was the first engine via the drop down list under `Search Engines` for `Standard` tab
* ensured that `Brave Search` was the first engine via the drop down list under `Search Engines` for `Private` tab
* ensured Google search is used when searching from the omnibar

1.66 | 1.67.115
-|-
![IMG_6395](https://github.com/brave/brave-browser/assets/17885425/5191095d-83e8-4a76-a40b-fa0bb4d110c4) | ![IMG_6398](https://github.com/brave/brave-browser/assets/17885425/2dcbe53b-6d43-49a7-8eda-8b1540b926ac)
![IMG_6396](https://github.com/brave/brave-browser/assets/17885425/83406976-6009-427d-b697-7531ab35d864) | ![IMG_6399](https://github.com/brave/brave-browser/assets/17885425/90aac5ca-afce-4207-b1e3-a8c9f0faa308)
![IMG_6397](https://github.com/brave/brave-browser/assets/17885425/1d5dc6e7-a755-4d7f-82ca-3b0dbc40360a) | ![IMG_6400](https://github.com/brave/brave-browser/assets/17885425/b94fbb7d-af17-4cb7-9f9e-1e8420fc043c)

</details>

<details><summary>Updated Profile (Bing/Ecosia)</summary>

* installed `1.66`
* changed the default SE to `Bing` under `Search Engines` for `Standard` tab
* changed the default SE to `Ecosia` under `Search Engines` for `Private` tab
* updated to `1.67.115`
* ensured that `Bing` wasn't replaced with `Brave Search` as the default SE for `Standard` tab
* ensured that `Ecosia` wasn't replaced with `Brave Search` as the default SE for `Private` tab
* ensured that `Brave Search` was the first engine via the drop down list under `Search Engines` for `Standard` tab
* ensured that `Brave Search` was the first engine via the drop down list under `Search Engines` for `Private` tab

1.66 | 1.67.115
-|-
![IMG_6402](https://github.com/brave/brave-browser/assets/17885425/c99ed2fb-b2cf-4cc2-91c0-32a50ddacdfc) | ![IMG_6403](https://github.com/brave/brave-browser/assets/17885425/392b49c7-b95e-4dba-979d-6f60fcfe659d)

</details>

**FR (France) - IN PROGRESS**

<details><summary>Clean Profile</summary>

* ensured that `Brave Search` was selected as the default for both Standard/Private tab via `Search Engines` in `Settings`
* ensured that `Brave Search` was the first engine via the drop down list under `Search Engines` for `Standard` tab
* ensured that `Brave Search` was the first engine via the drop down list under `Search Engines` for `Private` tab

Example | Example | Example
-|-|-
![IMG_6411](https://github.com/brave/brave-browser/assets/17885425/1809f37f-3825-42b8-870a-222d4e0d7dd2) | ![IMG_6412](https://github.com/brave/brave-browser/assets/17885425/9e7f794c-e92e-44f2-b6d4-219b018b1927) | ![IMG_6413](https://github.com/brave/brave-browser/assets/17885425/5c024068-2099-4a83-97de-0db5f5a45a85)

</details>

<details><summary>Updated Profile (Google/Google)</summary></details>

<details><summary>Updated Profile (Google/Google)</summary></details>


**sv_SE (Sweden) - PASSED**

<details><summary>Clean Profile</summary>

* ensured that `Google` was selected as the default for both Standard/Private tab via `Search Engines` in `Settings`
* ensured that `Brave Search` was the first engine via the drop down list under `Search Engines` for `Standard` tab
* ensured that `Brave Search` was the first engine via the drop down list under `Search Engines` for `Private` tab

Example | Example | Example
-|-|-
![IMG_6404](https://github.com/brave/brave-browser/assets/17885425/7b460cc1-0338-4a5e-8cdf-e218c7ce7874) | ![IMG_6405](https://github.com/brave/brave-browser/assets/17885425/cfb42f96-d056-49ff-b69f-5a7beece7dbc) | ![IMG_6406](https://github.com/brave/brave-browser/assets/17885425/53e1d721-0a30-4512-83f0-ae704ef8a29f)

</details>

<details><summary>Updated Profile (Google/Google)</summary>

* installed `1.66`
* ensured the default SE is `Google` under `Search Engines` for `Standard` tab
* ensured the default SE is `Google` under `Search Engines` for `Private` tab
* updated to `1.67.115`
* ensured that `Google` wasn't replaced with `Brave Search` as the default SE for `Standard` tab
* ensured that `Google` wasn't replaced with `Brave Search` as the default SE for `Private` tab
* ensured that `Brave Search` was the first engine via the drop down list under `Search Engines` for `Standard` tab
* ensured that `Brave Search` was the first engine via the drop down list under `Search Engines` for `Private` tab

1.66 | 1.67.115
-|-
![IMG_6407](https://github.com/brave/brave-browser/assets/17885425/d432113b-5136-42a1-b084-360c5fb3c1b0) | ![IMG_6408](https://github.com/brave/brave-browser/assets/17885425/1fd38c47-fd4a-47af-be2a-a9491195dcdf)

</details>

<details><summary>Updated Profile (DDG/Startpage)</summary>

* installed `1.66`
* changed the default SE to `DDG` under `Search Engines` for `Standard` tab
* changed the default SE is `Startpage` under `Search Engines` for `Private` tab
* updated to `1.67.115`
* ensured that `DDG` wasn't replaced with `Brave Search` as the default SE for `Standard` tab
* ensured that `Startpage` wasn't replaced with `Brave Search` as the default SE for `Private` tab
* ensured that `Brave Search` was the first engine via the drop down list under `Search Engines` for `Standard` tab
* ensured that `Brave Search` was the first engine via the drop down list under `Search Engines` for `Private` tab

Example | Example
-|-
![IMG_6409](https://github.com/brave/brave-browser/assets/17885425/ed6df544-71fc-41bd-aa35-e5960f2095aa) | ![IMG_6410](https://github.com/brave/brave-browser/assets/17885425/03cc195b-9440-4c1d-beb3-b2467c6c5e1e)

</details>

**Comment by Uni-verse** [comment]
In progress on iPad (7th Gen) running iOS 17.4 using version 1.67.115
