### ISSUE TITLE
Remove Llama 2 13B from model selector

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#38195]
```[tasklist]
### Related Changes
- [ ] https://github.com/brave/brave-browser/issues/38071
- [ ] https://github.com/brave/brave-browser/issues/36802
- [ ] https://github.com/brave/brave-browser/issues/37989
- [ ] https://github.com/brave/brave-browser/issues/37988
```

**Comment by mattmcalister** [comment]
Mapping to new models:
1. Llama 2 --> Llama 3
2. Claude Instant --> Haiku (Free Tier users)
3. Claude Instant --> Sonnet (Premium users)

**Comment by petemill** [comment]
Closing as a tracking issue since all tasks have other issues and the main task is duplicated with https://github.com/brave/brave-browser/issues/38071
