### ISSUE TITLE
Show multiple windows toggle in settings for Phone

### ISSUE THREAD

**Issue by tapanmodh** [brave/brave-browser#38203]
## Description 
Show multiple windows toggle in settings for Phone where multi window is supported by os.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Actual result 
Go to `Settings` -> `Appearance` -> `Enable multiple windows` is not visible for phone

## Expected result
Go to `Settings` -> `Appearance` -> `Enable multiple windows` should be visible where it is supported by os.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? 1.67.73

## Device details
   - Install type (ARM, x86): arm64
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Android 14
   
## Brave version
1.67.73

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.66.105 Chromium: 125.0.6422.41 (Official Build) (64-bit) 
Revision	ba88d7bb175a55287d14014823d5da31fe9c8a47
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Ensured that `Enable multiple windows` is shown in `Appearance` setting and is disabled by default for new users. 
- Ensured that `Enable multiple windows` is enabled when upgrading with multiple windows open for existing users.
- Ensured that `Enable multiple windows` is disabled for existing users without any other windows open. 
- Ensured that multiple windows can be enabled for existing users after upgrading and disabled.
- Ensured users can disable `Enable multiple windows` and dialog is not shown when other windows are not open.
- Ensured `Multiple windows detected` dialog is shown when 2 or more windows are open.
- Ensured `Move to other window` page is opened when selecting `merge windows` on the dialog.
- Ensured current window is closed when selecting `close windows` on the dialog.
- Ensured merging windows successfully will disable the setting. 

**_New Users (default)_**

Example | Example | Example
-|-|-
![Screenshot 2024-05-13 at 10 55 23 AM](https://github.com/brave/brave-browser/assets/17885425/f841c378-be81-4bf2-9e36-558987c27e71) | ![Screenshot 2024-05-13 at 10 55 33 AM](https://github.com/brave/brave-browser/assets/17885425/8ca85693-fdf6-4476-b6d9-596b430d0478) | ![Screenshot 2024-05-13 at 10 55 39 AM](https://github.com/brave/brave-browser/assets/17885425/90c2684e-bd7f-4995-943e-bb0b2ef5bd2d)

**_New Users (Feature Enabled)_**

Example | Example | Example | Example
-|-|-|-
![Screenshot 2024-05-13 at 11 32 25 AM](https://github.com/brave/brave-browser/assets/17885425/6c7c5e52-5b60-4ed6-a4fd-37890ce7511e) | ![Screenshot 2024-05-13 at 10 56 53 AM](https://github.com/brave/brave-browser/assets/17885425/d0ac2e61-52ba-4c49-9746-bc92d66233a4) | ![Screenshot 2024-05-13 at 10 57 00 AM](https://github.com/brave/brave-browser/assets/17885425/bdf14ebf-40d2-4002-aa2a-e79d8bb3f30c) | ![Screenshot 2024-05-13 at 10 57 05 AM](https://github.com/brave/brave-browser/assets/17885425/b03f77dc-7f77-4f56-a215-6ab2e996751d)

**_Dialog/Disabling with Multiple Windows_**

Example | Example | Example
-|-|-
![Screenshot 2024-05-13 at 11 02 18 AM](https://github.com/brave/brave-browser/assets/17885425/233c5af9-abcf-484d-a2cb-eacd845b9273) | ![Screenshot 2024-05-13 at 11 00 43 AM](https://github.com/brave/brave-browser/assets/17885425/c1fdf931-3590-436b-906b-531ef4a62f9b) | ![Screenshot 2024-05-13 at 11 00 52 AM](https://github.com/brave/brave-browser/assets/17885425/0feb997e-8af1-4711-992d-a563d0585a65)
