### ISSUE TITLE
[Android] Update shields tooltip

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#38206]
This change should help reducing the app size.

**Comment by kjozwiak** [comment]
The above requires `1.66.107` or higher for `1.66.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240322.023 release-keys
Brave build: 1.66.107
Chromium: 125.0.6422.41 (Official Build) (64-bit) 
```
----------------
**ACTUAL RESULTS:**
- Verified that Brave `Shields` tooltip is updated and working as expected
