### ISSUE TITLE
[ads] Opening iOS NTT video ad in landscape mode shows different stop key frame

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#38204]
## Description: 
Opening Video NTT in landscape mode shows different stop key frame

Precondition: 

New Tab Takeover video ads are available in staging component updater for iOS.
Steps to setup staging component updater on iOS:

- Fresh install
- Turn off WiFi and mobile network
- Launch browser
- Toggle Use Staging CRX components in Settings -> BraveCore Switches
- Close the browser
- Turn on WiFi or mobile network
- Launch Brave browser
- Staging components are downloaded and applied in a minute after start

## Steps to Reproduce 
  1. Rotate iphone to landscape
  2. Open new tab until video ad is shown
  3. Rotate to portrait
 

## Actual result: 
Different stop frame is used (which is imo even fancier than the one in portrait)

![IMG_6115](https://github.com/brave/brave-browser/assets/17885425/17b1f8ad-21c6-4460-9c9a-a0e830f38600)

## Expected result:

![IMG_6121](https://github.com/brave/brave-browser/assets/17885425/b5b6ca44-1197-4939-a262-6aec92145a5f)

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

## Brave Version: 
1.66.x, 1.68.x

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 
iPhone 12

**Comment by tmancey** [comment]
Blocked until a decision is made on whether this feature will become widely adopted.

**Comment by aseren** [comment]
The issue was fix in https://github.com/brave/brave-browser/issues/40090
