### ISSUE TITLE
[Android] Separate always on & kill swicth

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#38238]
Follow up of https://github.com/brave/brave-browser/issues/37013. 
In this issue we need to separate always on & kill switch options.

**Comment by kjozwiak** [comment]
The above requires `1.67.102` or higher for `1.67.x` verification 👍

**Comment by kjozwiak** [comment]
Labelling as `QA/No` & `release-notes/exclude` in favour of https://github.com/brave/brave-browser/issues/38853. We've basically reverted the above via https://github.com/brave/brave-core/pull/24042.
