### ISSUE TITLE
Pin to Brave notification is not shown upon initial install of Brave

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#38233]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/26301 in 1.66.104. `Would you like to pin Brave to your taskbar?` notifications were shown in 1.67.59 when this issue was originally tested.   Failed to get notifications in `1.67.78 beta` and `1.68.2 nightly` on initial installs as well.  However, notifications are received during first install of current release. 

## Steps to Reproduce

   1. Install 1.66.104
   2. launch Brave
   
## Actual result:

`Would you like to pin Brave to your taskbar?` notification is not shown

## Expected result:

![image](https://github.com/brave/brave-browser/assets/98358127/f979f894-d32e-4cb9-b8c8-a08ed113e7aa)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.66.104 Chromium: 125.0.6422.41 (Official Build) (64-bit)
-- | --
Revision | 6213f85e37bb676772fb221ce11a41c2b1be0fe2
OS | Windows 11 Version 23H2 (Build 22631.3527)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @simonhong 
cc: @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.66.108` or higher for `1.66.x` verification 👍 Removing the `QA Pass` as we'll need to re-verify the above using `1.66.x`. However, used https://github.com/brave/brave-browser/issues/38233#issuecomment-2109005834 as the needed verification on `Nightly` for the `1.66.x` uplift as per https://github.com/brave/brave-core/pull/23626#pullrequestreview-2054245092.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.66.108 Chromium: 125.0.6422.41 (Official Build) (64-bit)
-- | --
Revision | 3a79189ba4e3cf17c382dd265d4f447f83a8f49d
OS | Windows 10 Version 22H2 (Build 19045.4291)

```
![image](https://github.com/brave/brave-browser/assets/38657976/38fc4436-52c0-4e08-af6b-d8b91ecd3609)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

example | example
----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/c40bb9b4-22a8-4a74-a054-aaf52c761869) | ![image](https://github.com/brave/brave-browser/assets/387249/4da59473-aad7-4131-b789-47219ff4a990)
