### ISSUE TITLE
[ads] Landed counter is not suspended after searching through URL bar

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#38235]
Follow up to: https://github.com/brave/brave-browser/issues/38193

## Steps to Reproduce

1. Clean profile
2. Trigger ad
3. Start landed counter
4. Type `t` in URL bar and press `Enter`

## Actual result:

Landed counter is not suspended after URL navigation
Landed counter is still active. Ad is marked landed even after navigation to another page 

## Expected result:
Landed counter is suspended
OR
Landed counter is canceled

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.68.6 Chromium: 125.0.6422.41 (Official Build) nightly (64-bit)
-- | --
Revision | 2886cb2a986d182705496c6252456cf7424e08a5
OS | Linux

cc @tmancey @aseren @iambrianfung

**Comment by tmancey** [comment]
@btlechowski, the reason is because Brave has Brave Search as its default search engine. Consequently, after typing 't', the URL remains search.brave.com once the search is completed, indicating that we're still within the same eTLD+1.

**Comment by btlechowski** [comment]
Verified with

Brave | 1.66.105 Chromium: 125.0.6422.41 (Official Build) (64-bit)
-- | --
Revision | ba88d7bb175a55287d14014823d5da31fe9c8a47
OS | Linux


Verified landed is canceled after using google as default search provider

```
[5821:5821:0513/155200.132776:VERBOSE1:ad_handler.cc(183)] Canceled page land for creative instance id c1bbef73-5201-4ccd-9ed0-d897610d6a0e on tab id 1548449954
```
