### ISSUE TITLE
Update shields onboarding tooltip

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#38237]
## Description 

Update the tooltip for Shields during onboarding to match Android/iOS.

**Comment by kjozwiak** [comment]
The above requires `1.66.108` or higher for `1.66.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.66.108 Chromium: 125.0.6422.41 (Official Build) (x86_64)
-- | --
Revision | 3a79189ba4e3cf17c382dd265d4f447f83a8f49d
OS | macOS Version 11.7.10 (Build 20G1427)
```

Confirmed that Brave Shields' tooltip is updated and working/displaying as expected.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.66.108 Chromium: 125.0.6422.41 (Official Build) (64-bit) 
Revision	3a79189ba4e3cf17c382dd265d4f447f83a8f49d
OS	Linux
```

Confirmed that Brave Shields' tooltip is updated and working/displaying as expected.
