### ISSUE TITLE
Brave corrupts when bookmarking onion sites - March 2019

### ISSUE THREAD

**Issue by MarkCate** [brave/brave-browser#3824]
## Description 

Brave **cannot bookmark onion sites from Tor** window. Additionally, the menu item "New Private Window With Tor" disappears at the same time as Mac's Command-D fails to create bookmark. Search for issue reveals nothing in DuckDuckGo.

## Steps to Reproduce

   1. Open Brave Tor window, open Ahmia onion http://msydqstlz2kzerdg.onion/. Press command-D to bookmark, nothing happens.
   2. Open Brave Tor window, open SearX http://eljwdzi4pgrrlwwq.onion/. Press command-D and bookmark is created. Open new Brave Tor window, SearX bookmark is gone and command-D no longer creates bookmark.
   3. Now menu item "New Private Window With Tor" is missing from menu. There is no way to open a Brave Tor window using any command or menu. Close Brave, clear all system caches, re-open Brave, close and re-open Brave multiple times until missing menu item re-appears. First Brave Tor window shows SearX bookmark! Any other Brave window or tab, SearX bookmark is missing and cannot be re-created. At all times during 3 noted steps, when Tor window cannot be created, all three (3) Bookmark menu items are greyed out in menu bar, and in Brave Browser drop menu the same three greyed out menu items.

## Actual result:

The actual result is well described above. Consideration: Tor is causing Brave to partially regress to an earlier build. A dozen onion search engine sites were used to test bookmarking. Only SearX provided expected behavior, consistently.

## Reproduces how often: 

This specific corruption of the Brave Browser is 100% reproducible on this 2018 Oct Mac Pro machine.

## Brave version (brave://version info)

Version 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)
Copyright 2019 Brave Software Inc. All rights reserved.

### Reproducible on current release:

- Does it reproduce on brave-browser dev/beta builds? Not tested 

### Website problems only:  

- Does the issue resolve itself when disabling Brave Shields? Not tested
- Is the issue reproducible on the latest version of Chrome? Not Tested

### Additional Information

Current macOS 10.14.3 also has installed Tor 
8.0.7 (based on Mozilla Firefox 60.6.0esr) (64-bit)
Running Tor or or not running Tor, Brave issue with **failed bookmarks and disappearing access to Brave Tor** persists. Onion sites can be dragged from Tor bookmarks to Brave address bar, opening Tor Browser bookmarks using Brave Browser.

(( _if only Brave could bookmark onion sites without losing the ability to open Brave Tor tabs/windows_ ))

**Comment by kjozwiak** [comment]
@MarkCate I can't seem to reproduce this on my `macOS 10.14.3 x64` running `0.61.52 Chromium: 73.0.3683.86`. Here's what I've been trying:

* launch `0.61.52 Chromium: 73.0.3683.86`
* open a new tor window and load http://msydqstlz2kzerdg.onion
* attempt to bookmark the above site with `command + d` (nothing happens)
* open a new tor window and load http://eljwdzi4pgrrlwwq.onion/
* attempt to bookmark the above site with `command + d` (nothing happens)

I tried several different combinations of single windows, multiple tabs etc. Can't seem to get `command + d` to add a bookmark which is expected. We don't allow folks to create bookmarks while using `Tor`. CCing @tomlowenthal to confirm.

@MarkCate Between ```step #1``` & ```step #2```, are you closing the windows and reopening them? If you can reproduce 100% of the time, mind adding more detailed STR? Example:

* opened `0.61.52 Chromium: 73.0.3683.86`
* loaded X in Tor window and attempted to bookmark it via the shortcut
* while the first window is still opened, created a new Tor window via the menu

Something similar to the above 👍

**Comment by tomlowenthal** [comment]
Yes: as long as Tor is implemented with guest sessions, it shouldn't be possible to access or create bookmarks in a private window with Tor. Once we switch to interchangeable incognito sessions, bookmarks will work just like in regular private windows.

**Comment by kjozwiak** [comment]
> Yes: as long as Tor is implemented with guest sessions, it shouldn't be possible to access or create bookmarks in a private window with Tor. Once we switch to interchangeable incognito sessions, bookmarks will work just like in regular private windows.

Thanks @tomlowenthal 👍 @MarkCate as per the comment above, did you manage to get a `. onion` address bookmarked in a `Tor Window` using `command + d`?
