### ISSUE TITLE
Fatal error when trying to start brave on ubuntu

### ISSUE THREAD

**Issue by darkvader1996** [brave/brave-browser#3825]
## Description 

i just installed  brave(stable branch)  in a a clean installation of ubuntu 18.04 x64

then tried to run it but it won't start and it will throw an error in the ubuntu logs console

FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! You probably need to enable user namespaces in your kernel. See https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux for more information.

tried enabling "user namespaces" in my kernel and still not working

then tried with beta release and dev release and it don't worked out

## Steps to Reproduce

   1.  install ubuntu  (latest release 18.04.2)
   2.  install brave
   3.  run it

## Actual result:
this: http://prnt.sc/n0s4pv

## Expected result:

running like chrome do

## Reproduces how often: 
it fails everytime

## Brave version (brave://version info)

it happened today so i suppose it's the last version (beta,dev,stable)(20-03-2019)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 

N/A

- Is the issue reproducible on the latest version of Chrome? 

it doesn't happens on chrome, i saw it's something about to do with sandboxing but everything is correctly sandboxed here but brave 

### Additional Information

Just by simply installing ubuntu and brave
![Screenshot from 2019-03-20 22-41-49](https://user-images.githubusercontent.com/48666964/54731194-3dab6900-4b63-11e9-8727-9d682d047ad7.png)

i just created this account to report this error, thank you in foward for your help and assistance!

**Comment by darkvader1996** [comment]
it's weird because i don't see people talking about it and it's happening to me

**Comment by srirambv** [comment]
Are you installing it via the steps mentioned here  https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux ? That error used to happen on the older muon build but not on the new brave-core. If you follow the instructions on the document you shouldn't encounter any errors while launching brave via terminal

**Comment by darkvader1996** [comment]
@srirambv  Yes, of course i do, i'll try a fresh install again and see how it goes then

**Comment by srirambv** [comment]
I've tried couple of times with the instructions from [here](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux) and launching brave doesn't show that error. Going to close the thread for now. If you do happen to run into it do reply on the same thread and we can reopen the issue if required.

**Comment by brianddk** [comment]
@darkvader1996 getting the exact same issue on Debian 9 stretch.  I'm not installing through apt.  I'm just installing the `deb` files with dpkg, but it should work (I would think).

**Comment by brianddk** [comment]
@darkvader1996 , @srirambv , this fixed it: 

* [Super User: Enable user namespaces in Debian kernel](https://superuser.com/questions/1094597/enable-user-namespaces-in-debian-kernel)
