### ISSUE TITLE
Extension-generated blobs are not accessible because of blob partitioning

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#38256]
https://github.com/brave/brave-core/pull/22619#issuecomment-2105991429

> According to my bisect in [violentmonkey/violentmonkey#2098](https://github.com/violentmonkey/violentmonkey/issues/2098) this breaks `fetch(blobUrl)` inside an isolated world (content script) of chrome extensions where `blobUrl` is created by the extension's background script via URL.createObjectURL() and looks like `blob:chrome-extension://bhlejohahnjoegdhipncajfeefppembn/35ec611b-0186-4b9c-acfb-787211fda68a`
> 
> The error is `Failed to fetch` and devtools shows the request as `(canceled)`, no further info. Chrome doesn't have this problem.

**Comment by kjozwiak** [comment]
The above requires `1.66.108` or higher for `1.66.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.66.108 Chromium: 125.0.6422.41 (Official Build) (64-bit)
-- | --
Revision | 3a79189ba4e3cf17c382dd265d4f447f83a8f49d
OS | Windows 10 Version 22H2 (Build 19045.4291)
```
As per https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1715662346973799?thread_ts=1715607014.839959&cid=CHGKGMHDJ, please ensure that `violentmonkey.github.io` is added into the `Whitelist` as per the following:

![image](https://github.com/brave/brave-browser/assets/38657976/2cd3ff9c-6585-401e-804c-a4a2bc3d745f)

Using the STR/Cases mentioned via https://github.com/violentmonkey/violentmonkey/issues/2098#issue-2290987912, reproduced the `TypeError: Failed to fetch` error appearing under `github.com` when running the script while using `1.68.10 Chromium: 125.0.6422.41` as per the following:

Using the same STR/Cases mentioned above, verified that the `TypeError: Failed to fetch` wasn't being displayed as per the following:

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```

```
As per https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1715662346973799?thread_ts=1715607014.839959&cid=CHGKGMHDJ, please ensure that `violentmonkey.github.io` is added into the `Whitelist` as per the following:

![image](https://github.com/brave/brave-browser/assets/38657976/2cd3ff9c-6585-401e-804c-a4a2bc3d745f)

Using the STR/Cases mentioned via https://github.com/violentmonkey/violentmonkey/issues/2098#issue-2290987912, reproduced the `TypeError: Failed to fetch` error appearing under `github.com` when running the script while using `1.66.107 Chromium: 125.0.6422.41` as per the following:
![Reproduced issue](https://github.com/brave/brave-browser/assets/38657976/a986e0b4-d468-4de1-96bc-89c10a903972)


Using the same STR/Cases mentioned above, verified the issue on `1.66.108 Chromium: 125.0.6422.41` and ensured that the `TypeError: Failed to fetch` wasn't being displayed as per the following:
![Fixblobfetch](https://github.com/brave/brave-browser/assets/38657976/9b654b31-bdeb-4b98-be7f-81d1efa1707b)
