### ISSUE TITLE
Can't disable secure DNS

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#38258]
## Description 
Can't disable secure DNS via brave://settings

## Steps to Reproduce

   1.  open `brave://settings/security?search=dns`
   2.  disable `Use secure DNS`
   3.  reload the page

## Actual result:
`Use secure DNS` checkbox is enabled.

## Expected result:
`Use secure DNS` checkbox is disabled. Secure DNS doesn't work. 

## Reproduces how often: 
Easily

## Brave version (brave://version info)
1.68.2 Chromium: 125.0.6422.41 (Official Build) nightly (arm64) 

## Version/Channel Information:
Nightly, mac-arm64

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by atuchin-m** [comment]
Probably it's a result of chromium patches in https://github.com/brave/brave-browser/issues/35677

**Comment by arthuredelstein** [comment]
So far I tried reverting 
- https://github.com/brave/brave-core/commit/07a2c177d8d0baf5e46afb5d618cd654f5e6be06
- https://github.com/brave/brave-core/commit/775f48c978ef1e21117aba141192eed9d043b72f
- https://github.com/brave/brave-core/commit/e4c07298a7106fa146870b2b856dd92734160214,
- https://github.com/brave/brave-core/commit/45bb93ab3f18cbfd90e5ae3074923682a402bf8d
but that didn't fix the problem.

**Comment by atuchin-m** [comment]
1.65.132 Chromium: 124.0.6367.202 (Official Build) (arm64) is unaffected to me

**Comment by kjozwiak** [comment]
The above requires `1.66.10` or higher for `1.66.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.66.110 Chromium: 125.0.6422.60 (Official Build) (64-bit)
-- | --
Revision | de593d76e2ca4d02faa85bf1ca27bcf3ee46793c
OS | Windows 10 Version 22H2 (Build 19045.4412)

```
Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/38258#issue-2292499996, ensured that refreshing `brave://settings/security` doesn't enable `Secure DNS` if it's already disabled as per the following:

![SecureDNS](https://github.com/brave/brave-browser/assets/38657976/22844c26-7ff2-4436-8ce4-901757540fe1)
