### ISSUE TITLE
Button text cut off on dialog when in split view [Phone]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#38269]
## Description 
Button text is cut off when `Multiple windows detected` dialog is shown in split view.

Related to: https://github.com/brave/brave-browser/issues/38203

## Steps to reproduce 

   1. New install
   2. Set `Enable multiple windows` to ON in `Appearance` settings
   3. Go back to new tab, long press on favorites and select `Open in new window`
   4. While in split view, open menu in either one of the windows and turn `Enable multiple windows` toggle to OFF in `Appearance` settings
   5. Observe dialog

## Actual result 
Button text is cut off. Should probably be stacked or dialog should be expanded.
![Screenshot 2024-05-13 at 11 00 24 AM](https://github.com/brave/brave-browser/assets/17885425/55d260cf-d38c-4fe9-9272-c2cd5c294b58)

## Expected result
![Screenshot 2024-05-13 at 11 00 43 AM](https://github.com/brave/brave-browser/assets/17885425/302b7736-df40-495c-befa-18bce809814a)

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM 
   - Device type (Phone, Tablet, Phablet): Samsung GS21
   - Android version: 13
   
## Brave version
`1.66.105`

**Comment by kjozwiak** [comment]
The above requires `1.66.10` or higher for `1.66.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.66.110 Chromium: 125.0.6422.60 (Official Build) (64-bit) 
Revision	de593d76e2ca4d02faa85bf1ca27bcf3ee46793c
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

**New Users**

   1. New install
   2. Set `Enable multiple windows` to ON in `Appearance` settings
   3. Go back to new tab, long press on favorites and select `Open in new window`
   4. While in split view, open menu in either one of the windows and turn `Enable multiple windows` toggle to OFF in `Appearance` settings
   5. Observe dialog
   
**Existing Users**

1. Install 1.65.133
2. Upgrade to 1.66.110
3. Set `Enable multiple windows` to ON in `Appearance` settings
4. Go back to new tab, long press on favorites and select `Open in new window`
5. While in split view, open menu in either one of the windows and turn `Enable multiple windows` toggle to OFF in `Appearance` settings
6. Observe dialog

- Ensured button text dialog visibility is improved from the previous version.
- Ensured `Merge windows` and `Close windows` buttons are working. 

Example | Example
-|-
![Screenshot 2024-05-16 at 10 29 25 AM](https://github.com/brave/brave-browser/assets/17885425/1f7aed41-bcb2-4431-b6f4-04781e84a5c3) | ![Screenshot 2024-05-16 at 10 32 23 AM](https://github.com/brave/brave-browser/assets/17885425/df1e29f7-6798-445c-91db-4820f0c03035)
