### ISSUE TITLE
WebUI: History page pre-load UI is not consistent with post-load UI

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#3826]
Since we've changed the look of the top toolbar area of WebUI pages, the layout of the pre-load top area of pages is inconsistant. This is especially noticeable on the History page, since it contains the page title in the incorrect coords:

![image](https://user-images.githubusercontent.com/741836/54731450-82c3a100-4b4b-11e9-950f-d4f5f66df1e3.png)

![image](https://user-images.githubusercontent.com/741836/54731478-a4248d00-4b4b-11e9-8c48-c6709cae9a4d.png)

## Test plan
1. Visit brave://history

### Actual
The page title is displayed in the top left (in English it's 'History')

### Expected
No page title is displayed before the Navigation Bar loads

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.65.98 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2019 and https://github.com/brave/brave-core/pull/1909
