### ISSUE TITLE
Select Account Dropdown is Highlighting Multiple Accounts

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#38262]
## Description 

The `Select Account Dropdown` is highlighting multiple accounts when filtering by `Bitcoin` or `ZCash` account

## Steps to Reproduce

   1. Navigate to the `Send` screen and open the `Select Token Modal`
   2. Filter tokens by a `Bitcoin` or ZCash` Account
   3. All `Bitcoin` and `ZCash` account will be highlighted as the selected account

## Actual result:

![Screenshot 34](https://github.com/brave/brave-browser/assets/40611140/9997957a-410c-46af-8beb-eba7545c6ff6)

## Expected result:
Should use the accounts `Unique key` rather than `address` to fix this issue.

![Screenshot 37](https://github.com/brave/brave-browser/assets/40611140/4aa093b5-6486-4d31-82ce-165cc91d44cf)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.68.85 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | 8e76a669cf78bdfa933c8d569460092a01166588
OS | Windows 11 Version 23H2 (Build 22631.3672)

- Verified steps from [brave/brave-core#23598](https://github.com/brave/brave-core/pull/23598)
- Verified select account dropdown only  shows the selected account
- Encountered [#38983](https://github.com/brave/brave-browser/issues/38983)

https://github.com/brave/brave-browser/assets/17010094/93c08ba4-1854-4340-a7d6-147331a4e847
