### ISSUE TITLE
Check Icon is Missing from Select Account Dropdown

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#38261]
## Description 

The `check` icon is missing in the `Select Account Dropdown` 

## Steps to Reproduce

   1. Navigate to the `Send` screen and open the `Select Token Modal`
   2. Filter tokens by an `Account`
   3. The `Selected Account` is missing a `check` icon in the dropdown.

## Actual result:

![Screenshot 35](https://github.com/brave/brave-browser/assets/40611140/e0df43bc-a3c4-486a-a28d-c1b27435a0ec)

## Expected result:
Should display a `check` icon next to the `Account` you have selected.

![Screenshot 36](https://github.com/brave/brave-browser/assets/40611140/90b0246d-6562-43d1-be3c-c9ffc083cccf)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.68.85 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | 8e76a669cf78bdfa933c8d569460092a01166588
OS | Windows 11 Version 23H2 (Build 22631.3672)

- Verified steps from [brave/brave-core#23598](https://github.com/brave/brave-core/pull/23598)
- Verified Selected Account from dropdown has a check mark next to the account 
<img width="1920" alt="brave_ygAUJuQbWT" src="https://github.com/brave/brave-browser/assets/17010094/8159b23c-e023-4fc8-92b3-7872ebffda5b">
