### ISSUE TITLE
'Move to other window' page is not shown sometimes when selecting from dialog

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#38277]
## Description 
'Move to other window' page is not shown sometimes when selecting from dialog

Intermittent issue, usually happens after opening new windows and closing one of them.
Related to https://github.com/brave/brave-browser/issues/38203

## Steps to reproduce 

Use Case 1: 

   1. New install
   2. Set `Enable multiple windows` to ON in `Appearance` settings
   3. Go back to new tab, long press on a favorite and select `Open in new window`
   4. Expand one of the windows (get out of split view)
   5. Open menu in either one of the windows and turn `Enable multiple windows` toggle to OFF in `Appearance` settings
   6. Select `merge windows` in the dialog
   
Use Case 2: 

   1. New Install
   2. Set `Enable multiple windows` to ON in `Appearance` settings.
   3. Go back to new tab, long press on a favorite and select `Open in new window`.
   4. Repeat this to open a third window.
   5. Open menu and select Manage windows (3).
   6. Select another window.
   7. Toggle off `Enable multiple windows`
   8. Select `merge windows` on dialog

## Actual result 
`Move to other window` page is not shown, only tab itself

https://github.com/brave/brave-browser/assets/17885425/c4c1c239-7127-470b-a49f-530976c36f8f

## Expected result
Should show `Move to other window` page

![Screenshot 2024-05-13 at 12 44 37 PM](https://github.com/brave/brave-browser/assets/17885425/d254cbaf-2537-4a82-91b2-29cb0012800f)

## Issue reproduces how often 
Intermittent

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21
   - Android version: 13
   
## Brave version
1.66.105

**Comment by kjozwiak** [comment]
The above requires `1.66.113` or higher for `1.66.x` verification(s) 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using version: 

```
Brave	1.66.113 Chromium: 125.0.6422.76 (Official Build) (64-bit) 
Revision	b1864a9a0152d4f1631121c6b13a7426f50cf336
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that `Move to other window` page is always shown when disabling the multi-window settings with multiple windows open and selecting `merge windows` from the dialog.
- Ensured that `close windows` button on `multiple windows detected` dialog is functional.
- Ensured that `Enable multiple windows` is disabled by default for new users.
- Ensured that dialog is not shown when disabling `Enable multiple windows` with single window open.
- Ensured use cases in https://github.com/brave/brave-browser/issues/38277#issue-2293336080 are working in incognito window. 

Example | Example | Example 
-|-|-
![Screenshot 2024-05-22 at 11 16 14 AM](https://github.com/brave/brave-browser/assets/17885425/a168efe0-0cfe-4e26-b0ae-e4acea852c98) | ![Screenshot 2024-05-22 at 11 16 55 AM](https://github.com/brave/brave-browser/assets/17885425/574a5579-b5d2-4064-bbd2-9da500c6420f) | ![Screenshot 2024-05-22 at 11 17 15 AM](https://github.com/brave/brave-browser/assets/17885425/d2e301ea-d5d1-47d0-9535-5af4baa78603)
