### ISSUE TITLE
[ads] Same document navigations should trigger `NotifyTab[Text/Html]ContentDidChange` after tab switch

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#38276]
## Steps to Reproduce 
  1. Visit Single Page Application webpage
  2. Open new tab with another webpage
  3. Switch back to a tab with Single Page Application webpage
  4. Do a same document navigation within SPA webpage

## Actual result: 
Same document navigation within SPA webpage don't trigger `NotifyTab[Text/Html]ContentDidChange`

## Expected result:
Same document navigation within SPA webpage trigger `NotifyTab[Text/Html]ContentDidChange`

## Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

**Comment by btlechowski** [comment]
Verified on Brave 1.68.125 on iPhone 13 Pro Max

Verified test plan from https://github.com/brave/brave-core/pull/23616

<details>




</details>
