### ISSUE TITLE
[ads] Page reload should not trigger `NotifyTab[Text/Html]ContentDidChange`

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#38270]
## Steps to Reproduce 
  1. Open a webpage
  2. Reload the webpage

## Actual result: 
Webpage reload triggers `NotifyTab[Text/Html]ContentDidChange `

## Expected result:
Webpage reload triggers `NotifyTab[Text/Html]ContentDidChange `

## Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

**Comment by btlechowski** [comment]
Verified on Brave 1.68.125 on iPhone 13 Pro Max

Verified test plan from the description.

Verified `NotifyTab[Text/Html]ContentDidChange` is not triggered on page reload

Verified test plan from https://github.com/brave/brave-core/pull/23886

<details>




</details>
