### ISSUE TITLE
[ads] Back/forward page transitions should not trigger `NotifyTabDidChange`

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#38279]
## Steps to Reproduce 
  1. Do a search query on search.brave.com
  2. Tap any link with URL other then brave.com
  3. Tap Back button
  4. Tap Forward button

## Actual result: 
Back/Forward transition doesn't trigger `NotifyTabDidChange`

## Expected result:
Back/Forward transition triggers `NotifyTabDidChange`

## Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6
Brave build: 1.68 (110)
BraveCore: 1.68.110 (127.0.6533.26)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/38279#issue-2293413015 and https://github.com/brave/brave-core/pull/23886#issue-2322263612
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Back/Forward` transition on search.brave.com does not trigger the `NotifyTabDidChange` log.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/da92ea12-57ac-451d-a4a4-d98ef0f2fae1) | ![2](https://github.com/brave/brave-browser/assets/128532965/6604d2ee-dcd3-49b0-a801-4297837ff813) | ![3](https://github.com/brave/brave-browser/assets/128532965/d48c2358-e675-433f-9dc8-6f97d9fba6f2) | ![4](https://github.com/brave/brave-browser/assets/128532965/f34c0854-a543-4cc8-a9eb-75055a4ca0e1) |

https://github.com/brave/brave-browser/assets/128532965/aced9779-4d05-4c9f-bd26-8398aa26a166
