### ISSUE TITLE
[ads] Back/forward page transitions should not trigger `NotifyTab[Text/Html]ContentDidChange`

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#38278]
## Steps to Reproduce 
  1. Do a search query on search.brave.com
  2. Tap any link with URL other then brave.com
  3. Tap Back button
  4. Tap Forward button

## Actual result: 
Back/Forward transition doesn't trigger `NotifyTab[Text/Html]ContentDidChange`

## Expected result:
Back/Forward transition triggers `NotifyTab[Text/Html]ContentDidChange`

## Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

**Comment by btlechowski** [comment]
Verified on Brave 1.68.125 on iPhone 13 Pro Max

Verified test plan from the description.

Verified `NotifyTab[Text/Html]ContentDidChange` is not triggered on Back/forward page transitions

Verified test plan from https://github.com/brave/brave-core/pull/23886

<details>




</details>
