### ISSUE TITLE
[SkusSDK] - Improve Rust-C++ FFI

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#38327]
## Description: 
- Current Rust and C++ communication is rough. It requires generating callbacks on the C++ side and passing them to Rust and hoping that the caller passes the correct arguments. Otherwise it will crash.
- Current Rust and C++ communication requires creating a callback-state holder that holds the callback, and a bunch of callback signatures:
```Rust
type RefreshOrderCallbackState;
type RefreshOrderCallback = crate::RefreshOrderCallback;
type FetchOrderCredentialsCallbackState;
type FetchOrderCredentialsCallback = crate::FetchOrderCredentialsCallback;
type PrepareCredentialsPresentationCallbackState;
type PrepareCredentialsPresentationCallback = crate::PrepareCredentialsPresentationCallback;
type CredentialSummaryCallbackState;
type CredentialSummaryCallback = crate::CredentialSummaryCallback;
type SubmitReceiptCallbackState;
type SubmitReceiptCallback = crate::SubmitReceiptCallback;
type CreateOrderFromReceiptCallbackState;
type CreateOrderFromReceiptCallback = crate::CreateOrderFromReceiptCallback;
```
where `create::XXXX` is also defined in C++ via a `shim.h` file.

- Current Rust and C++ communication also requires Unsafe code and "extern C" style functions where the first argument is a pointer to an instance allocated on the heap, and the second argument is the function to be called, and it's called via a trampoline:
```Rust
#[allow(improper_ctypes_definitions)]
#[repr(transparent)]
pub struct RefreshOrderCallback(
    pub  extern "C" fn(
        callback_state: *mut ffi::RefreshOrderCallbackState,
        result: ffi::SkusResult,
        order: &str,
    ),
);

unsafe impl ExternType for RefreshOrderCallback {
    type Id = type_id!("skus::RefreshOrderCallback");
    type Kind = cxx::kind::Trivial;
}
```
This is done for every single C++ function that Skus Rust code needs to call. It's tedious, and error prone, and can easily lead to Undefined Behaviour if proper care is not taken to ensure the right signatures and arguments are passed on the heap.

**Comment by LaurenWags** [comment]
@Brandon-T please add a test plan for Desktop, Android, and iOS. Labelling as `QA/Blocked` until we have this.

**Comment by Brandon-T** [comment]
> @Brandon-T please add a test plan for Desktop, Android, and iOS. Labelling as `QA/Blocked` until we have this.

Updated the test cases.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.68.99 Chromium: 126.0.6478.126 (Official Build) beta (64-bit)
-- | --
Revision | 8ccc3a46e66d71dfd21506e1ccb42e08c7d33557
OS | Windows 10 Version 22H2 (Build 19045.4529)
```

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP31.240517.031 release-keys
Brave build: 1.68.117
Chromium: 127.0.6533.26 (Official Build) beta (64-bit) 
```
---------------------------

`IAP: Account linking from Android --> Desktop`

**STEPS:**
1. Launch Brave on `Android` device
2. Open `Leo` > Settings > Go Premium > Upgrade now > Finish the flow
3. Go to Leo settings > Link purchase to your Brave account
4. Provide email > Get login link
5. Open your email and tap `Confirm your email`
6. When `account.brave.com` opens, tap `link my subscription now` > *Confirm that the `Success!` message is shown*
7. Launch Brave on `Desktop`
8. Go to `account.brave.com` > Login with your test account
9. Go to your email and tap `Log in to Brave`
10. When `account.brave.com` opens, tap `Refresh Leo` > *Verify that Leo subscription was loaded successfully*
11. Go to any website, for example, `chromeunboxed.com` > Open any article
12. Launch `Leo` > *Verify that the `Premium` subscription is active, and `Claude 3 Sonnet` is available and working as expected*

**ACTUAL RESULTS:**
- Verified that `Leo Premium subscription` purchased on `Android` (IAP) can be linked to `account.brave.com`, and active credentials can be loaded to `Desktop`

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/082e6f0f-4fdd-4bf3-9142-aee61ab44739) | ![2](https://github.com/user-attachments/assets/020c50e9-75ec-46dc-904a-79bc2fe7f4e3) | ![3](https://github.com/user-attachments/assets/6fdc901f-591d-4625-b87f-c69e2dcfae04) | ![4](https://github.com/user-attachments/assets/cbad6638-c7cd-4850-be1d-cc3ceefbdf0f) |
| ![1](https://github.com/user-attachments/assets/5373ebb5-7b35-4228-8c61-1d9e98b5d09e) | ![2](https://github.com/user-attachments/assets/97497feb-daf7-4b86-a192-8197877d7b7b) | ![3](https://github.com/user-attachments/assets/740b2e3b-b128-4d46-b22a-89de757c43b7) | ![4](https://github.com/user-attachments/assets/de815c0b-f675-40df-b4de-2825addc0f09) |
| ![1](https://github.com/user-attachments/assets/70d7bd3c-752d-4a10-aa3d-c1ee280e4b31) | ![2](https://github.com/user-attachments/assets/a6a4342f-00c7-4ff1-a35b-b108dc0f3634) | ![3](https://github.com/user-attachments/assets/4f3706c4-3dc2-44f1-afb2-d3ffb2c7fd5c) | ![4](https://github.com/user-attachments/assets/a8d597c1-5cbe-49e3-97a6-86f5dd31a6e8) |

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6
Brave build: 1.68 (130)
BraveCore: 1.68.130 (127.0.6533.73)
```
---------------------------

`IAP: Account linking from iOS --> Desktop`

**STEPS:**
1. Launch Brave on `iOS` device
2. Open Settings > Leo > Go Premium > Upgrade now > Finish the flow
3. Go to `Leo` settings > Link purchase to your Brave account
4. Provide email > Get login link
5. Open your email and tap `Confirm your email`
6. When `account.brave.com` opens, tap `link my subscription now` > *Confirm that the `Success!` message is shown*
7. Launch Brave on `Desktop`
8. Go to `account.brave.com` > Login with your test account
9. Go to your email and tap `Log in to Brave`
10. When `account.brave.com` opens, tap `Refresh Leo` > *Verify that Leo subscription was loaded successfully*
11. Go to any website, for example, `chromeunboxed.com` > Open any article
12. Launch `Leo` > *Verify that the `Premium` subscription is active, and `Claude 3 Sonnet` is available and working as expected*

**ACTUAL RESULTS:**
- Verified that `Leo Premium subscription` purchased on `iOS` (IAP) can be linked to `account.brave.com`, and active credentials can be loaded to `Desktop`

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/9fa7cc37-2b70-4363-a897-aa9e9d3b5cb8) | ![2](https://github.com/user-attachments/assets/c8c8ace5-8a72-4a29-9c5f-66d0cbe7b0a5) | ![3](https://github.com/user-attachments/assets/5825cc7d-6eaf-423b-8e05-225d6b7ecb60) | ![4](https://github.com/user-attachments/assets/99743f8b-48ed-424a-91e1-3574bb82a9a7) |
| ![1](https://github.com/user-attachments/assets/d3e198af-52a1-4521-a9b7-9c6860eefea5) | ![2](https://github.com/user-attachments/assets/b262f64e-12ad-4496-bede-ce66119881a1) | ![3](https://github.com/user-attachments/assets/528f49d6-8ed7-4a87-9d48-f53794c82296) | ![4](https://github.com/user-attachments/assets/6694b035-a501-4502-a9f5-2cf501e3d22f) |
| ![1](https://github.com/user-attachments/assets/fd45efc3-f6b7-4cc1-bab2-39ad80e4b5c0) | ![2](https://github.com/user-attachments/assets/719f6392-36b0-4742-8bf4-b30ef2f3c059) | ![3](https://github.com/user-attachments/assets/803ff155-fcaf-431e-9626-d79721beaa5a) | ![4](https://github.com/user-attachments/assets/0d4cffbc-48d6-4a86-bcb4-de55857b1cc7) |
| ![1](https://github.com/user-attachments/assets/d06d0ea2-f44f-4ac3-8eee-f228e0617a8f) | ![2](https://github.com/user-attachments/assets/14bc0c87-926e-4c2e-a8eb-8da81b2dc4ff) | ![3](https://github.com/user-attachments/assets/07e734b4-1546-4709-b2ab-8db26d8d23d8) | ![4](https://github.com/user-attachments/assets/dd86130a-bd72-4cd4-8fe8-4fe42ca57915) |
