### ISSUE TITLE
Need tooltip for `Leo's` slash-tools icon

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#38329]
## Description 

Need tooltip for `Leo's` slash-tools icon

Found while testing https://github.com/brave/brave-browser/issues/37294

## Steps to Reproduce

   1. install `1.68.14`
   2. launch Brave
   3. open a new-tab page
   4. click on `Leo` in the sidebar
   5. type `test`
   6. click `I understand`
   7. hover over the `[ / ]` icon in the `Enter a prompt here` input box 

## Actual result:

No tooltip on hover

<img width="380" alt="Screenshot 2024-05-14 at 7 48 34 PM" src="https://github.com/brave/brave-browser/assets/387249/a5795009-cb9a-441c-b9f8-c2741ad0e549">

## Expected result:

Appropriate tooltip appears on hover, like this `Send message to Leo` one for the paper-airplane icon to its right

<img width="396" alt="Screenshot 2024-05-14 at 7 48 24 PM" src="https://github.com/brave/brave-browser/assets/387249/2a7eed2c-cb7a-44b6-89cf-efde65a73ce8">

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.68.14 Chromium: 125.0.6422.41 (Official Build) nightly (x86_64)
-- | --
Revision | b2b820a3f51cde3fbd10db0cb93be8a00642c5bb
OS | macOS Version 14.5 (Build 23F79)
```

cc @aguscruiz @mattmcalister @nullhook @brave/qa-team

**Comment by jonathansampson** [comment]
Looks like this was addressed already by https://github.com/brave/brave-core/pull/23942

![image](https://github.com/user-attachments/assets/323a1119-c7c8-49ac-aea0-b9731fb7fd68)
