### ISSUE TITLE
should be "Same as macOS" and not "Same as MacOS" under brave colors selection

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#3832]
## Description 

The `Brave colors` selection under Appearances should be `Same as macOS` and not `Same as MacOS`. Apple uses `macOS`.

## Steps to Reproduce

   1. launch brave and visit brave://settings and look for `Brave colors:` under `Appearances`

## Actual result:

<img width="757" alt="Screen Shot 2019-03-21 at 12 33 07 AM" src="https://user-images.githubusercontent.com/2602313/54733628-ef9d6200-4b70-11e9-8ff4-c8964eed6086.png">

## Expected result:

Should be `Same as macOS` and NOT `Same as MacOS`

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

### Reproducible on current release:

N/A as this hasn't made it into release.

- Does it reproduce on brave-browser dev/beta builds?

Yes, reproducible under Nightly/Dev.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @petemill there's this one and a few other text clean up ones, #2494 and location bar -> address bar.

**Comment by kjozwiak** [comment]
I was . going to grab this one as it seems like an easy one to fix 👍

**Comment by aqeelparpia** [comment]
Hello @kjozwiak @rebron
Could I please would on this ? I really want to contribute to this project.

**Comment by aqeelparpia** [comment]
Hello @kjozwiak @rebron
 Could I please work on this ? I really want to contribute to this project.

**Comment by petemill** [comment]
Hi @aqeelparpia, this is a simple string change, but I'd be happy to help you contribute this change if you want to get used to the contribution process, if @kjozwiak doesn't have something in-progress.

You should be able to search for "Same as MacOS" in a code editor to find the file. It's in a .grd file.

**Comment by kjozwiak** [comment]
@aqeelparpia all yours :) Appreciate the contribution!

**Comment by aqeelparpia** [comment]
I'm having troubles setting up the project

**Comment by bsclifton** [comment]
@aqeelparpia what steps have you done so far? Do you have XCode and the command line tools installed? You should be able to follow the steps here:
https://github.com/brave/brave-browser/wiki/macOS-Development-Environment

**Comment by rebron** [comment]
Closing. Fixed with https://github.com/brave/brave-core/pull/1909

**Comment by LaurenWags** [comment]
@kjozwiak can you test this one since you have Mojave?

**Comment by simonhong** [comment]
@LaurenWags I tested this on from beta(0.65.x) to nightly (0.67.x) now and all are using correct string (`macOS`).

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.4 x64` using the following build:

Brave | 0.65.98 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

<img width="682" alt="Screen Shot 2019-05-23 at 9 01 08 PM" src="https://user-images.githubusercontent.com/2602313/58295580-085b0b80-7d9e-11e9-8704-2f4df9be4cac.png">

@LaurenWags looks good 👍

**Comment by LaurenWags** [comment]
Thanks @simonhong @kjozwiak for confirming 😄
