### ISSUE TITLE
Invalid console message

### ISSUE THREAD

**Issue by ondrejfuhrer** [brave/brave-browser#3833]
## Description 
When visiting some pages in the console I can see following message
```
As part of an experiment, Chrome temporarily shows only the lock icon in the address bar. Your SSL certificate with Extended Validation is still valid.
```

If possible, `Chrome` should be changed to `Brave`

## Steps to Reproduce

   1. Open a page with EV certificate (i.e. paypal.com)
   2. Open Console

## Actual result:

```
As part of an experiment, Chrome temporarily shows only the lock icon in the address bar. Your SSL certificate with Extended Validation is still valid.
```

## Expected result:
```
As part of an experiment, Brave temporarily shows only the lock icon in the address bar. Your SSL certificate with Extended Validation is still valid.
```

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)

**Comment by bsclifton** [comment]
@ondrejfuhrer this is expected - EV certs are no longer shown prominently in the UI (before, they were shown as a green lock and the entity name was shown)

**Comment by ondrejfuhrer** [comment]
Hello @bsclifton , thank you for a quick reaction, but I guess you missed the point of that issue - it states that `Chrome` does something, but would be better if it stated that `Brave` does something. It is more about branding 😉

**Comment by bsclifton** [comment]
@ondrejfuhrer thanks for clarification. I'm not sure it would make sense to customize this since it may only be temporary (if/when it gets dropped entirely)

cc: @rebron in case we wanted to reopen/look at fixing
