### ISSUE TITLE
Add bookmarks button shows wrong count when landing pages are open

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#38340]
## Description: 
![Simulator Screenshot - iPhone 14 Pro - 2024-05-15 at 09 43 28](https://github.com/brave/brave-browser/assets/909331/6578bd8f-3440-469a-8fa8-a57db144a448)

When long pressing the tabs button when on a landing page, add bookmark is not there because i'm on the landing page. But then it shows "add bookmarks for 3 tabs" where one of the tabs is the landing page and so it will add 2 bookmarks instead of 3. So it should say "add bookmarks for 2 tabs" or maybe not show anything at all.

## Steps to Reproduce 
  1. Open a tab and go to any website
  2. Open a new tab and stay on the landing page
  3. Long press the tabs button ("[1]") in the navigation bar 

## Actual result: 
Shows "Add bookmarks for 2 tabs"

## Expected result:
Should either show nothing or ignore landing pages and say "Add bookmarks for 1 tab"

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

## Brave Version: 
1.66

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details: 
Any

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari?

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6
Brave build: 1.68 (110)
BraveCore: 1.68.110 (127.0.6533.26)
```

Filed follow-up issue #39590
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/38340#issue-2298364840 and https://github.com/brave/brave-core/pull/23707#issue-2300969496
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Add Bookmark for %lld Tabs` is not shown when staying on `NTP`
- Verified that `Add Bookmark for %lld Tabs` shows the correct number of tabs that must be saved when staying on a tab with any website

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/d7a03c42-94bc-4ce4-82fc-d4924c99dbb7) | ![2](https://github.com/brave/brave-browser/assets/128532965/7b7fec76-00d8-4fcf-bddf-fc6b6fee2c7a) | ![3](https://github.com/brave/brave-browser/assets/128532965/d516ed7f-edcb-43f7-b931-f9c7d17acf93) | ![4](https://github.com/brave/brave-browser/assets/128532965/1de11d9a-ad49-4519-99f9-224089e84ae2) |
