### ISSUE TITLE
Import bookmark link text in the infobar is difficult to read with the new theme colors & updated nala colors 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#38354]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/38087.  For some of the profile themes with Dark background, particularly `import bookmarks now...` link is difficult to read 

## Steps to Reproduce

   1. Install 1.66.107
   2. launch Brave
   3. opened brave://settings/manageProfile
   4. select Dark blue, Midnight blue or custom blue 
## Actual result:

example | example
----- | ----
![image (1)](https://github.com/brave/brave-browser/assets/98358127/8c91c14a-0779-438e-b000-d74be148b02d)|![image](https://github.com/brave/brave-browser/assets/98358127/2cf85081-37ec-4777-b3e9-9edd7a7664f2)

## Expected result:
Need contrasting colors?

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @aguscruiz

**Comment by aguscruiz** [comment]
Yes, should use the dark mode version of that color. Seems to be using light mode

**Comment by simonhong** [comment]
> Yes, should use the dark mode version of that color. Seems to be using light mode

Correct. we should consider bg color also in this case.

**Comment by frypf** [comment]
This lack of legibility doesn't just seem isolated to the specific example mention by OP -  I'm using the default theme, and having just now upgraded to 1.66.110 I instantly noticed similar difficulties reading items on "brave://discards":

<img width="358" alt="Screenshot 2024-05-16 at 18 51 21" src="https://github.com/brave/brave-browser/assets/65832791/1123b39a-0065-439a-a0f2-c1c300b0462c">

The same is true of other builtin pages, eg. settings etc. Prior to upgrading, all the dark blue clickable items were a nice legible & contrasting shade of orange IIRC.
Changing brave themes doesn't affect anything on these pages - only switching my whole system to light mode makes them readable again.

**Comment by frypf** [comment]
Ok I see now it's apparently known as the accent colour - forgive my UI ignorance. Was this supposed to have changed from the previous orange with the latest update?

**Comment by Rikk** [comment]
This issue with color was fixed in 1.65/1.66/1.67 at some time:
https://github.com/brave/brave-browser/issues/37515 ➔ https://github.com/brave/brave-core/pull/23048 / https://github.com/brave/brave-core/pull/23054 / https://github.com/brave/brave-core/pull/23055
But in 1.66 release (v1.66.110) it is happening again as described here.

**Comment by bsclifton** [comment]
@frypf yes - it was changed. From the orange to the "blurple" (blue/purple). Thanks for flagging 😄

**Comment by simonhong** [comment]
I'll fix this after cr126 is merged into master to avoid conflict with it as cr126 has some related color value changes.

**Comment by Rikk** [comment]
> I'll fix this after cr126 is merged into master to avoid conflict with it as cr126 has some related color value changes.

So, does this mean Brave main color will be "Hard on the Eyes Burple" for the next 3 weeks?

_cc @bsclifton_

**Comment by bsclifton** [comment]
@Rikk no - we'll get something earlier 😄 We're just going to fix it in the Chromium 126 code branch first - then we can backport a fix to the Chromium 125 branches (Beta / Release). Thanks for your patience!

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.68.85 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | 8e76a669cf78bdfa933c8d569460092a01166588
OS | Windows 10 Version 22H2 (Build 19045.4474)
```

`Blue` | `Slate Gray` | `Purple`
-------|-------------|---------
![image](https://github.com/brave/brave-browser/assets/387249/15655760-5393-4e7f-a9d4-78dda546c3b0) | ![image](https://github.com/brave/brave-browser/assets/387249/f5e9af58-c103-4728-a00e-923f2d4c37c2) | ![image](https://github.com/brave/brave-browser/assets/387249/059b6f35-8505-4a1f-9500-5c037f3d4503)
