### ISSUE TITLE
aichat: Fix crash caused by HTML entities in markdown renderer

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#38351]
HTML entities returned from the remote LLM cause a crash because the markdown renderer internally uses `innerHTML` in one of the packages. This conflicts with UntrustedWebUI, of which AIChat's WebUI is an instance.

> “Uncaught TypeError: Failed to set the ‘innerHTML’ property on ‘Element’: This document requires ‘TrustedHTML’ assignment and no ‘default’ policy for ‘TrustedHTML’ has been defined.“, source: chrome-untrusted://chat/chat_ui.bundle.js

prompt: `why we use & to escape in HTML?`

**Comment by LaurenWags** [comment]
@nullhook can you please add the following labels as necessary:
- `QA/No` or `QA/Yes`
- `release-notes/exclude` or `release-notes/include`

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.68.86 Chromium: 126.0.6478.56 (Official Build) beta (x86_64)
-- | --
Revision | b4eadb4942277a3eb455fc7c3c8569185bd745af
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.68.86 Chromium: 126.0.6478.56 (Official Build) beta (64-bit)
-- | --
Revision | b4eadb4942277a3eb455fc7c3c8569185bd745af
OS | Windows 10 Version 22H2 (Build 19045.4529)
```

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave	1.68.87 Chromium: 126.0.6478.56 (Official Build) beta (64-bit) 
Revision	786b6b66ebe624e5c4ef760b3fe3047ea61932de
OS	Linux
```

### Steps:

1. installed `1.68.87`
2. launched Brave
3. selected `Claude 3 Haiku` in `brave://settings/leo-assistant`
4. opened `brave://version`
5. typed test
6. clicked on `I understand` to opt-in
7. asked Leo, "why we use & to escape in HTML?"

### Confirmed full, accurate response without crashing or blanking

example | example
---------|----------
<img width="1557" alt="Screen Shot 2024-06-13 at 2 24 37 PM" src="https://github.com/brave/brave-browser/assets/387249/bdc9ba02-f4bc-497d-ad6b-975cf49324c4"> | <img width="1434" alt="Screen Shot 2024-06-13 at 2 25 32 PM" src="https://github.com/brave/brave-browser/assets/387249/7ee045bf-e8f6-4d66-9c9f-cd8892c39c52">

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 AP31.240517.031 release-keys
Brave build: 1.68.115
Chromium: 127.0.6533.26 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/23710#issue-2301065774
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the UI is not blank and Brave is not crashing

---------------------------

`Galaxy Tab S8`

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/4575dc66-1eb0-4a00-9f0e-04ce37c59075) | ![2](https://github.com/brave/brave-browser/assets/128532965/ca88f9c7-f474-410b-8f91-7f4513f91c06) |

`Pixel 7`

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/c085f88e-da4c-4f74-9751-7809e136e86b) | ![2](https://github.com/brave/brave-browser/assets/128532965/ae484815-937d-49f4-8708-e78b6c104456) |
