### ISSUE TITLE
Automatically marks and deletes first couple of letters

### ISSUE THREAD

**Issue by servetcoskun** [brave/brave-browser#3835]
1. Open new tab
   2. Start typing webpage/search
   3. See letters getting removed

## Actual result:
Letters are removed forcing user to retype.

## Expected result:
Should just be typing as usual or autocomplete

## Reproduces how often: 
Usually only 1st time entering anything in to url-bar in a new tab, or if it happens it does happen a few times in succession, then might not for a while.

## Brave version (brave://version info)
Version 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information
It is quite hard to reproduce but it happens quite a few times in succession then not for a while.

**Comment by Liunkae** [comment]
I also have seen similar behavior recently with 0.63.x (dev) on macOS. The first one or two characters are dropped when quickly creating a new tab and typing a URL. I have not noticed it yet with 0.64.x (nightly).

**Comment by bsclifton** [comment]
Thanks for creating an issue - this is a known issue which we're tracking with https://github.com/brave/brave-browser/issues/3756

Closing this issue as a duplicate
