### ISSUE TITLE
Integrate Jitsi SDK with Transcription support

### ISSUE THREAD

**Issue by iccub** [brave/brave-browser#38368]

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.6
- iPad Air / iPadOS 16.7.2
Brave build: 1.68 (117)
BraveCore: 1.68.117 (127.0.6533.26)
```
---------------------------
<details>
<summary> Fresh profile - PASS </summary>

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/23323#issue-2269223827 
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `video` and `transcript` recordings can not be started on `iOS` when the call started on `iOS`. 
- Verified that recordings on `iOS` started only after joining the call, all recordings made before `iOS` device joined the call are not shown.
- Verified that the transcripts are gone if `iOS` device leaves the call.
- Verified that transcripts are shown in `PiP` mode when doing `Summarize this page` in `Leo`. 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>
