### ISSUE TITLE
[ads] Brave News ads are not served for restored NTP tab

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#38378]
## Steps to Reproduce 
  1. Fresh install
  2. Join Brave Rewards
  3. Open NTP
  4. Close the Browser
  5. Open the Browser
  6. Join Brave News In the restored NTP tab

## Actual result: 
* Brave News ads cards are not shown

## Expected result:
* Brave News ads cards are shown

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

## Brave Version: 

The issue is reproducible with Browser version 1.66 and above.

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.5
Brave build: 1.66.1 (120)
BraveCore: 1.66.120 (125.0.6422.165)
```
---------------------------
<details>
<summary> Test case 1 </summary>

**STEPS:**
1. Fresh install Brave
2. Open `NTP`
3. Join `Brave Rewards`
4. Restart the Browser
5. Join `Brave News` In the restored `NTP` tab
6. Scroll `News Feed` > *Verify*

**ACTUAL RESULTS:**
- Verified that Brave `News` ads card is shown
- Verified that logs are shown:
```
[ads] Served inline content ad:
[ads] Viewed inline content ad impression with placement id
```
---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/ffc202df-63a0-4685-a48d-452951537db7) | ![2](https://github.com/brave/brave-browser/assets/128532965/43987bd7-f10b-47fd-b0f9-9c2ac06224dc) |
</details>

<details>
<summary> Test case 2 </summary>

**STEPS:**
1. Fresh install Brave
2. Open `NTP`
3. Join `Brave Rewards`
4. Join `Brave News` in the `NTP` tab (do not scroll to the News Feed)
5. Restart the Browser
6. Scroll `News Feed` in the restored `NTP` > *Verify*

**ACTUAL RESULTS:**
- Verified that Brave `News` ads card is shown
- Verified that logs are shown:
```
[ads] Served inline content ad:
[ads] Viewed inline content ad impression with placement id
```
---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/7608de19-22d5-4d14-a17f-b5cd802467e7) | ![2](https://github.com/brave/brave-browser/assets/128532965/202d0c3f-dbd3-4048-b20f-763e21759697) |
</details>
