### ISSUE TITLE
Approving transaction without internet does not remove submitting / loading overlay

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#38375]
## Description: 

On iOS there is a transaction status overlay on Transaction Confirmation after a user taps Approve, until they tap 'ok' to either dismiss or show the next transaction in queue. More details: https://github.com/brave/brave-ios/issues/6861

While a transaction is moving from `unapproved` to `submitted`/`error`/`dropped` status, there is currently no way to hide this overlay (without dismissing entire transaction confirmation modal). 

When approving a transaction without an internet connection, this 'Submitting' overlay is not removed, but if you dismiss entire Transaction Confirmation and check Activity tab you can see the transaction is in error status. 

## Steps to Reproduce 
  1. Create a transaction on any network. Used ethereum for testing but should work for any transaction.
  2. In Transaction Confirmation panel, wait for data to load
  3. Once data has loaded, disable network connection
  4. Tap approve
  5. Loading spinner will not be removed from transaction. Dismiss transaction confirmation and open activity tab, observe transaction has error status

## Actual result: 

https://github.com/brave/brave-browser/assets/5314553/ae92948a-8ccc-488b-b2bb-9e3538b3cea3

## Expected result:

Transaction should show error status after the loading spinner screen in Transaction Confirmation

## Reproduces how often: 

Easily reproduced

## Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari? 

### Additional Information

CC @srirambv thanks for reporting 👍

**Comment by kjozwiak** [comment]
The above requires `1.67.98` or higher for `1.67.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.67 (100)
- Verified steps from [brave/brave-core#23706](https://github.com/brave/brave-core/pull/23706)
- Verified when transaction isn't submitted it shows error message

iPhone 13 (iOS 17.5.1) | iPad (iOS 16.7.7)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/85ad1e7b-8521-4767-ab3e-78cc2baa1d26> | <video src=https://github.com/brave/brave-browser/assets/17010094/7b28e708-5f4f-4bdc-a536-383d96c87193>
