### ISSUE TITLE
Connection error when using Leo Sonnet model

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#38385]
## Description: 
Connection error when using Leo Sonnet model

## Steps to Reproduce 
  1. New install
  2. Open Leo from menu
  3. Select Claude 3 Sonnet as free user
  4. Send a query
  5. Observe chat box

## Actual result: 
Example | Example
-|-
![IMG_6162](https://github.com/brave/brave-browser/assets/17885425/382b3c36-210e-496e-9462-0196fa9457cf) | ![IMG_6163](https://github.com/brave/brave-browser/assets/17885425/2d60126c-92e3-4d1d-a126-4ea516de3b34)

## Expected result:
Should work

## Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

## Brave Version: 
1.66.x

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No (new feature)

### Device details: 
iPhone, iOS 17

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari?

**Comment by kjozwiak** [comment]
The above requires `1.66.112` or higher for `1.66.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.3.1` using version `1.66.112`

- Ensured that selecting Sonnet chat model as a free user will display the upgrade card in chat.
- Ensured that badging is correct in Leo settings menu and advanced settings page for free and premium users. 
- Ensured that Claude 3 Sonnet model works without issues with or without page content. 

Example | Example | Example
-|-|-
![IMG_6224](https://github.com/brave/brave-browser/assets/17885425/782c78de-a6ba-403c-b5d7-e76d12fa4a03) | ![IMG_6227](https://github.com/brave/brave-browser/assets/17885425/38b4c1f1-a3e9-4292-97b0-216606284e4a) | ![IMG_6225](https://github.com/brave/brave-browser/assets/17885425/ccf14aa8-8282-449c-9ff9-fee28a3ad96f)
![IMG_6235](https://github.com/brave/brave-browser/assets/17885425/01191dcd-91f6-4d92-a084-7a1e03962c23) | ![IMG_6236](https://github.com/brave/brave-browser/assets/17885425/e20c45fd-0ea9-41f9-b567-755b6a8c4d40)
