### ISSUE TITLE
[iOS] Support for `:remove`/`:remove-attr`/`:remove-class`

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#38381]
iOS tracking issue for https://github.com/brave/brave-browser/issues/33881

**Comment by antonok-edm** [comment]
[desktop implementation](https://github.com/brave/brave-browser/issues/33881) for reference

**Comment by cuba** [comment]
Will be available as part of the procedural filtering PR: https://github.com/brave/brave-core/pull/24688
