### ISSUE TITLE
New set default screen to UK users

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#38380]
## Description: 
We have a new set default screen as part of the new onboarding. We also have the Brave.IOS.IsLikelyDefault P3A.

Let's use these in combination.

## Requirements
From https://github.com/brave/brave-ios/issues/8674:

> (1) Special case: If the user has just installed the app within the past 7 days, instead of recording No, record Not enough info to avoid skewing data
> (2) If a user opens a http/https link with Brave immediately record Yes even if within 7 day window

The timing to show the set default screen would be next launch after 7 days has passed, if (2) did not happen.

Please roll out to UK users only.

## Design
This screen without the pagination dots and change the "Start Browsing" CTA copy to "Not Now"
https://www.figma.com/design/FiluJhwOjucQL4iGLmVZLW/iOS-Onboarding-(mobile)---Feb%2C-2024?node-id=3625%3A8401&t=nnN8lgCCp4iTyVVe-1

**Comment by anthonypkeane** [comment]
@timchilds has finalized the info here, can you please add and move the issue to "ready to work" Thanks

**Comment by kjozwiak** [comment]
@GeetaSarvadnya mind taking a look at this one re: the `P3A` portion of the verification? If you run into any issues/need help with `iOS` pleaes reach out to @Uni-verse or @hffvld 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `iPhone 8 version 16.7.10`  running `Brave Release 1.73 (89)`

<details>
<summary>Brave.IOS.IsLikelyDefault=0</summary>

</details>

<details>
<summary>Brave.IOS.IsLikelyDefault=1</summary>

</details>

<details>
<summary>Brave.IOS.IsLikelyDefault=2</summary>

</details>

**Comment by kylehickinson** [comment]
@GeetaSarvadnya sorry can you clarify what you mean by "open any https site in the Brave browser" in this case? Do you mean open a link from outside of Brave (like clicking a link from Mail/Notes)?

If you just mean you're loading a page in the browser itself then 0 is correct
