### ISSUE TITLE
Add platform check for filter list entries

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#38384]
## Description: 
We have a platform field we want to check and ensure desktop and android only lists don't make it to iOS

## Testing
1. Test content blockers here: https://test-pages.privacytests.org/tracking_content.html
2. Test aggressive/standard mode here: https://dev-pages.brave.software/filtering/network-requests.html
3. Test scriplets here: https://dev-pages.brave.software/filtering/scriptlets.html
4. Test cosmetic filtering here: https://dev-pages.brave.software/filtering/cosmetic-filtering.html
5. Test query param stripping https://fmarier.github.io/brave-testing/query-filter.html

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.68.117`

- Ensured that ad-blocking is working on YT using standard and aggressive modes.
- Ensured that all tests have passed for the following tests pages: 
   - Test content blockers here: `https://test-pages.privacytests.org/tracking_content.html`
   - Test aggressive/standard mode here: `https://dev-pages.brave.software/filtering/network-requests.html`
   - Test scriplets here: `https://dev-pages.brave.software/filtering/scriptlets.html`
   - Test cosmetic filtering here: `https://dev-pages.brave.software/filtering/cosmetic-filtering.html`
   - Test query param stripping `https://fmarier.github.io/brave-testing/query-filter.html`
   
Example | Example | Example | Example
 -|-|-|-   
![IMG_6795](https://github.com/user-attachments/assets/632a18ca-74af-47cb-b914-a3203c519a63) | ![IMG_6796](https://github.com/user-attachments/assets/719631af-3713-43d3-8e10-53abe9383f7f) | ![IMG_6798](https://github.com/user-attachments/assets/ed32e43d-affa-4069-b4eb-849183a3e659) | ![IMG_6799](https://github.com/user-attachments/assets/1a03bdac-b3b3-4fcb-aca3-8ef24111dcd0)

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iPadOS 17.5.1` using version `1.68.115`

- Ensured that ad-blocking is working on YT using standard and aggressive modes.
- Ensured that all tests have passed for the following tests pages: 
   - Test content blockers here: `https://test-pages.privacytests.org/tracking_content.html`
   - Test aggressive/standard mode here: `https://dev-pages.brave.software/filtering/network-requests.html`
   - Test scriplets here: `https://dev-pages.brave.software/filtering/scriptlets.html`
   - Test cosmetic filtering here: `https://dev-pages.brave.software/filtering/cosmetic-filtering.html`
   - Test query param stripping `https://fmarier.github.io/brave-testing/query-filter.html`
   
Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_1503](https://github.com/user-attachments/assets/4e12bc49-b526-45aa-90e6-3c31a78c3184) | ![IMG_1504](https://github.com/user-attachments/assets/adbd042f-beb7-4181-9ad6-ecf34888fdca) | ![IMG_1505](https://github.com/user-attachments/assets/17e73ba8-7df4-4120-885e-6955600e7ceb) | ![IMG_1506](https://github.com/user-attachments/assets/7e8f32f8-546f-4cff-8b3c-3e28c384098b) | ![IMG_1507](https://github.com/user-attachments/assets/e1023b68-57ed-44df-9a5a-b076fe9fafb3)
