### ISSUE TITLE
Redundant `Apply changes` button is shown in the Tor `Use Bridges` setting 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#38386]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/37896. In the Tor windows section of `brave://settings/privacy` page, unnecessary `Apply changes` button is shown.  When clicked, doesn't do anything and it just disappears and when refreshed the page, it reappears. This button wasn't displayed in 1.65.x 

## Steps to Reproduce

   1. Install 1.67.85
   2. launch Brave
   3. open brave://settings/privacy
   4. navigate to `Tor windows` section

## Actual result:

`Apply changes` button is shown.  When clicked doesn't do anything. Refreshed the page and the button reappears

![image](https://github.com/brave/brave-browser/assets/98358127/dbdbbc81-30a5-4648-af24-a45fc048f952)

## Expected result:
![image](https://github.com/brave/brave-browser/assets/98358127/0dab3e0d-8e48-4435-b3f5-4ce66a532a57)

## Reproduces how often: 

Easily

## Version/Channel Information:

```
Brave | 1.67.85 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | d01060f5ec155e6eb64a335203663a29c0e5d81f
OS | Windows 11 Version 23H2 (Build 22631.3593)
```
- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @boocmp

**Comment by stephendonner** [comment]
I see it too with

```
Brave | 1.67.85 Chromium: 125.0.6422.60 (Official Build) beta (x86_64)
-- | --
Revision | d01060f5ec155e6eb64a335203663a29c0e5d81f
OS | macOS Version 11.7.10 (Build 20G1427)
```

<img width="1471" alt="Screen Shot 2024-05-16 at 1 43 20 PM" src="https://github.com/brave/brave-browser/assets/387249/c2556240-cdcb-4b3d-aa33-925aabc69883">

**Comment by rebron** [comment]
cc: @fallaciousreasoning @boocmp Wondering if the Nala updates aren't sticking here either?

**Comment by fallaciousreasoning** [comment]
It doesn't repro in 1.66, which is where the Nala changes landed, so it might not be - I'll dig in a bit but it might be related to upstream moving to `Lit` from `Polymer`

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.68.85 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | 8e76a669cf78bdfa933c8d569460092a01166588
OS | Windows 10 Version 22H2 (Build 19045.4474)
```

### Steps:
1. installed `1.68.85`
2. launched Brave
3. opened `brave://settings/privacy`
4. confirmed no `Apply changes` button/text next to `Use Bridges`
5. toggled `Use Bridges` to `On`/`Enabled`
6. confirmed a new, dynamic `Apply changes` button appears to the left of the radio button
7. confirmed `Select a built-in bridge` was chosen, with `obfs4` default-selected
8. clicked on `Apply changes`
9. confirmed the button disappeared

example | example | example
----------|-----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/7092d335-ce29-4964-b6d8-d9e9539771c1) | ![image](https://github.com/brave/brave-browser/assets/387249/9d4c8840-471d-42e5-ac53-171906e7cfeb) | ![image](https://github.com/brave/brave-browser/assets/387249/70a21eaf-3f89-4fdd-a0b0-b1cd99144188)
