### ISSUE TITLE
[Android] Enable in app update dialog < android 14

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#38394]
As a follow up to https://github.com/brave/brave-browser/issues/38034, we need to enable in app update dialog for < android 14 devices.

**Comment by kjozwiak** [comment]
The above requires `1.67.109` or higher for `1.67.x` verification 👍

**Comment by kjozwiak** [comment]
@hffvld @Uni-verse can use https://github.com/brave/brave-core/pull/23727#issuecomment-2154118073 as a general template. Some info to keep in mind when running through the above:

* the GPS modal will appear once a month
* the `Update` toast at the bottom of the page will appear once per sessions once the update is ready/staged
* keep in mind if you move too ahead, sometimes updates won't work due to the device being ahead in time
  * certain websites will also stop working due to the device being to ahead

While we're running through the above, we should also verify that updating with the above way doesn't cause any issues re: losing state. Please run through an upgrade like we usually do but running through the above method.

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Pixel 2 XL` using version(s):
```
Device/OS: Pixel 2 XL / taimen-user  8.1.0 OPM2.171026.006.H1 release-keys
Brave build: 1.67.108
Chromium: 126.0.6478.40 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/23727#issuecomment-2154118073
2. *Verify*

<details>
<summary> Test Case 1 - Basic Update/Dismissing toast several times (functionality check) </summary>

**ACTUAL RESULTS:**
- Verified that there's no GPS bottom-sheet modal `re: requiring an update` when Brave `1.67.112` is installed and `1.67.113` is available for the upgrade if the system time is set to: `today's date`/`one week from today`/`two weeks from today `/`three weeks from today`.
- Verified that GPS bottom-sheet modal `re: requiring an update` is shown when Brave `1.67.112` is installed and `1.67.113` is available for the upgrade if the system time is set to `one month from today's date`.
- Verified that tapping on `Learn more` opens the Brave Browser page via the `GPS`.
- Verified that tapping on `Update` eventually shows an `Update toast message` at the bottom of the current Brave's tab/page.
- Verified that the `Update toast message` which appears at the bottom of the page is dismissed after a few seconds
- Verified that the `Update toast message` appears anytime you restart Brave after you tapped `Update` in the original bottom-sheet GPS modal
- Verified that the `Update toast message` doesn't appear again for the same Brave session
- Verified that tapping on `Update` installs/relaunches Brave without any issues

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/27e035e4-567e-424f-954e-c29517393a46) | ![2](https://github.com/brave/brave-browser/assets/128532965/fbc7d5e4-97a5-43cf-9ee9-82afdd8e1e85) | ![3](https://github.com/brave/brave-browser/assets/128532965/ed537ba8-ea45-47f9-90cf-bb6b984c42fa) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/28a99ef3-e909-4e29-8408-172828424ce8) | ![2](https://github.com/brave/brave-browser/assets/128532965/a4b0409f-1e21-468e-9dbd-4732f793b6b5) | ![3](https://github.com/brave/brave-browser/assets/128532965/c4cda691-7f91-4d28-bae0-3593a6fcc580) |
</details>

<details>
<summary> Test Case 2 - Basic Update/Dismissing toast several times (functionality check) </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>
