### ISSUE TITLE
[Tab Crash]: I had spotify open in a pinned tab and muted - it crashed at some point while in the background

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#38391]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.68.18 Chromium: 125.0.6422.41
Operating System: Linux 6.5.0-35-generic

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. I had 
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/8f3f0500-ce01-fb0b-0000-000000000000

**Comment by iefremov** [comment]
dupe https://github.com/brave/brave-browser/issues/36356
