### ISSUE TITLE
Brave crashing with "brave!brave_shields::AdBlockBaseService::ShouldStartRequest"

### ISSUE THREAD

**Issue by monaxle** [brave/brave-browser#3839]
## Description 
Every time today I type anything into the omnisearch bar and press enter Brave closes. Brave also closes when navigating to a site from saved bookmarks. Can't think of anything notable I may have done leading up to this. Auto upload of crash reports now enabled. 

## Steps to Reproduce
   1. Open Brave
   2. Type anything onto omniscience bar
   3. press enter
or 
1. Open Brave
2. Click on a saved bookmark to open in exiting or a new tab

## Actual result:
Brave closes every time after either of the above steps are followed.  

## Expected result:
Normal browser navigation from omnisearch or saved bookmarks 

## Reproduces how often: 
Every time from 21/03/2019

## Brave version (brave://version info)
Brave | 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux
JavaScript | V8 7.3.492.22
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36

### Reproducible on current release:
- Yes.  

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No. 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@monaxle if you go into `brave://crashes` do you see any crash reports that were generated?

**Comment by monaxle** [comment]
![bravecrash](https://user-images.githubusercontent.com/16516140/54786594-2d59c380-4c21-11e9-9eb6-ba3665593355.png)

**Comment by monaxle** [comment]
No idea what happened but all working again now after a manual fsck this morning.

**Comment by bsclifton** [comment]
Awesome, thanks for the update @monaxle 😄 I'll go ahead and close, but let's re-open if you experience again

**Comment by kjozwiak** [comment]
Re-opening as this is still happening. @davidtemkin shared several crash stacks which are matching the one @monaxle shared in the original issue. @davidtemkin also mentioned that he's still seeing the crash on `dev`. So this is definitely still occurring.

Direct links to crashes from @davidtemkin:

* https://stats.brave.com/dashboard#crash/5c9a540f7661e4001f7425ff
* https://stats.brave.com/dashboard#crash/5c97e9d7051c87001faa2416

Direct links to the crashes from @monaxle:

* https://stats.brave.com/dashboard#crash/5c93e9dc067c2e001f2676c7
* https://stats.brave.com/dashboard#crash/5c93cb93067c2e001f1bf508
* https://stats.brave.com/dashboard#crash/5c93cb81e42485001f49bc2a
* https://stats.brave.com/dashboard#crash/5c93c716067c2e001f1a5b0e

Looks like Brave is crashing around:

```
brave!brave_shields::AdBlockBaseService::ShouldStartRequest(GURL const&, content::ResourceType, std::__1::basic_string, std::__1::allocator > const&, bool*) [ad_block_base_service.cc : 134 + 0x13]
```

**Comment by kjozwiak** [comment]
@hspencer77 ran into a crash when he was upgrading brave on `macOS 10.4.4 x64`. After taking a look at the crash, seems to be the same crash that @davidtemkin and @monaxle ran into, example:

```
Brave Browser Framework!brave_shields::AdBlockBaseService::ShouldStartRequest(GURL const&, content::ResourceType, std::__1::basic_string, std::__1::allocator > const&, bool*) [ad_block_base_service.cc : 138 + 0x13]
    rbp = 0x000070001b264870   rsp = 0x000070001b264790
    rip = 0x000000010f890e42
    Found by: previous frame's frame pointer
```

Crash report: https://stats.brave.com/dashboard#crash/5cae2aa20bb29e001fbc62f8

**Comment by bbondy** [comment]
@kjozwiak 

I'm particularly interested in any crashes if they happen on a version 
=*.0.66.*
>74.0.65.66
>740.64.56
>740.63.44

If any new crashes come in for that please only post the link if the version is higher than what is listed above

**Comment by kjozwiak** [comment]
@asmaloney regarding https://github.com/brave/brave-browser/issues/4392 and the following crashes:

* https://stats.brave.com/dashboard#crash/5ce7dece8d2f56001f494a9b
* https://stats.brave.com/dashboard#crash/5ce7decfade2c2001f0cf838
* https://stats.brave.com/dashboard#crash/5cd9b95235cf8a001f4ddc4e

Are you using a build that meats the following criteria as per @bbondy?

```
=*0.66.x*
>74.0.65.66
>74.0.64.56
>74.0.63.44
```

**Comment by asmaloney** [comment]
@kjozwiak I'm using the official release (that's keeping itself up to date):

`Version 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)`

**Comment by asmaloney** [comment]
This is still an issue and it's getting really frustrating.

> Version 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit)

This time it died when restarting after installing the latest update.

**Uploaded Crash Report ID 2f7589bf2464ea33 (Local Context: 6a8ce946-edd9-4e6c-b4f7-6986360084cb)**

If it didn't kill all my tabs it would be... less frustrating.

**Comment by asmaloney** [comment]
Here's another log for you:

**Uploaded Crash Report ID 786a059ef1c08f78 (Local Context: 6f0ee7f7-bcc5-4e34-b435-c88f50d886ad)**

And to reiterate what happens after each crash when I launch it again:

- no window shows up and I can't quit
- I have to force quit Brave
- it works next time I run it, but all my open tabs are gone

**Comment by bbondy** [comment]
I think this is gone with 0.66.x and also we have a rust replacement with 0.68.x in the worst case. Closing.

**Comment by asmaloney** [comment]
Ironically Brave crashed (3rd time today) when I was launching it to see the email the closing of this issue generated...

> macOS 10.14.5
> Brave is up to date
> Version 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)

**Uploaded Crash Report ID 01e801b3c3385d9b (Local Context: f931c8fe-ea56-4179-8134-78edff0e52d2)**
