### ISSUE TITLE
Brave connects to clientservices.googleapis.com on start

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#3840]
## Description 
test-security fails with this error:

```
14:35:25 NETWORK AUDIT FAIL: https://clientservices.googleapis.com/uma/v2
14:35:25 NETWORK AUDIT FAIL: https://clientservices.googleapis.com/uma/v2
```

## Steps to Reproduce

   1. Run npm run test-security on master

## Actual result:
Connects to clientservices.googleapis.com

## Expected result:
Should not connect to clientservices.googleapis.com

## Reproduces how often: 
Easily

## Brave version (brave://version info)
master

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  No

**Comment by tomlowenthal** [comment]
→ #3816
