### ISSUE TITLE
Extend EVM ABI decoder to support dynamic and tested types

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#38402]
The current [ABI decoder](https://github.com/brave/brave-core/blob/master/components/brave_wallet/browser/eth_abi_decoder.cc) does not support complex composite types and dynamic types. Implementing this will allow us to decode arbitrary calldata and also avoid dependency on LiFi API to parse calldata of bridge transactions.

Note to QA: Ensure that transaction signing screen for common use-cases still work as expected (no need to approve though), and **Safe Sign** screen continues to work for 0x swaps.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.135 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 96e3ea6d105b9e3f1a388fa1838571774216b82e
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified transaction signing screen works as expected 

![image](https://github.com/user-attachments/assets/96824e5d-3e76-4e16-9dfe-e0749f572ca0) | ![image](https://github.com/user-attachments/assets/dee1c13f-2eda-4bf0-be8f-d51c9ba6e546) | ![image](https://github.com/user-attachments/assets/da02e21a-d2cb-46b6-9fe0-fd1663e1ebed) | ![image](https://github.com/user-attachments/assets/afcf50ef-fdff-4ad6-bd00-a7d7d55ea411)
-- | -- | -- | --

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.69.152 x64 build
- Verified steps from issue description
- Verified transaction signing screen works as expected
Note: Safe sign is not yet available on Android so only verified regular signing screen

https://github.com/user-attachments/assets/0d518c1c-ef64-4671-8547-7007adc3bf6d
