### ISSUE TITLE
Deposit icon should be same on all screens

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#38403]
## Description 

Follow up to[38077](https://github.com/brave/brave-browser/issues/38077), Deposit icon should be same on all screens

## Steps to Reproduce

   1. Same as [38077](https://github.com/brave/brave-browser/issues/38077)

## Actual result:

Deposit icon is QR code

## Expected result:
Deposit icon should be money bag

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.67.85 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | d01060f5ec155e6eb64a335203663a29c0e5d81f
OS | Windows 11 Version 23H2 (Build 22631.3593)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by kjozwiak** [comment]
The above requires `1.67.93` or higher for `1.67.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.94 Chromium: 125.0.6422.112 (Official Build) beta (64-bit)
-- | --
Revision | 3e4d210c91412b82ad8cffca556b12bbe40ff962
OS | Windows 11 Version 23H2 (Build 22631.3593)

- Verified steps from [brave/brave-core#23740](https://github.com/brave/brave-core/pull/23740)
- Verified Deposit icon is same on all screens

https://github.com/brave/brave-browser/assets/17010094/37e9b606-991e-46e1-bb3f-afdd1648471b
