### ISSUE TITLE
Changing account derivation shows error for Solana Hardware wallet import

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#38400]
## Description 

Changing account derivation shows error for Solana Hardware wallet import

## Steps to Reproduce

   1. Connect Ledger/Trezor
   2. Open Import Hardware wallet
   3. Select Solana
   4. Change derivation method
   5. Shows error 

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/18a87809-4315-4737-ac52-bb359357da7c

## Expected result:
Should be able to select different derivation path 

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA 
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @josheleonard

**Comment by LaurenWags** [comment]
Requires `1.67.110` or higher to test 👍🏻

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.110 Chromium: 126.0.6478.40 (Official Build) (64-bit)
-- | --
Revision | ac00bac697a2d9dad0b2e7f832391263816fd78d
OS | Windows 11 Version 23H2 (Build 22631.3672)

- Verified steps from issue description
- Verified able to import Solana accounts from different derivation paths when importing from Ledger hardware

https://github.com/brave/brave-browser/assets/17010094/4cd27344-4015-439e-a45f-34c7a2594daf
