### ISSUE TITLE
[CR126] GetLastUsedBrowserState is deprecated now

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#38419]
### Description

As of CR126, `GetLastUsedBrowserState` is now deprecated and renamed to `GetLastUsedBrowserStateDeprecatedDoNotUse`. It will probably be dropped completely very soon, so we should update our code to use a different approach. See related upstream change here: https://source.chromium.org/chromium/chromium/src/+/236a5a62f305419289ee89151bf8a15decf22ae6.

**Comment by kylehickinson** [comment]
This has been replaced already in cr131
