### ISSUE TITLE
Only incognito browsing deletes cookies from Default User Profile

### ISSUE THREAD

**Issue by whosithat** [brave/brave-browser#38412]
### Description

Hey everybody,

using incognito mode, by starting it directly from the taskbar, it deletes all cookies in the default userprofile. 

### Steps to reproduce

1. Open Brave with the default user profile (%localappdata%\BraveSoftware\Brave-Browser\User Data\Default)
2. Open any page and log into the site (e.g. facebook) 
3. Close Brave
4. Open Brave Incognito by doing a right click into the taskbar brave icon
5. Close the Brave Incognito Windows
6. Open Brave again with the default user profile, the cookies should be deleted, you should recognize it by being logged out

### Actual result

The cookies in the default user profile gets deleted after closing the incognito mode windows.

### Expected result

The cookies of the default user profile stays untouched

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave: 1.66.110 Chromium: 125.0.6422.60 (Offizieller Build) (64-Bit)
Überarbeitung | de593d76e2ca4d02faa85bf1ca27bcf3ee46793c
Betriebssystem | Windows 10 Version 22H2 (Build 19045.4412)
JavaScript | V8 12.5.227.8

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Could be also that all site data gets deleted, I've only had an eye on the cookies.

**Comment by ShivanKaul** [comment]
Wasn't able to repro on MacOS either.

**Comment by ShivanKaul** [comment]
Can you confirm you don't have "forget me when I close this site" set to be on for facebook.com on the Shields panel?

![image](https://github.com/brave/brave-browser/assets/5284154/192b8b37-3189-4d46-95eb-ef087f6b2a3f)

**Comment by diracdeltas** [comment]
You can also check brave://settings/clearBrowserData and make sure it's not set to clear all cookies on exit.

**Comment by whosithat** [comment]
Hey everybody,

thanks for your very fast feedback on this! @ShivanKaul pointed into the right direction, I've had the property "forget me when I close this site" turned on globaly in brave. 

I've also have selected the setting "Continue where I left" on brave startup. Somehow, if I'm using Brave without incognito mode, it never deletes any cookies from this pages (as these tabs will never be closed, only brave will be shutted down), but when I do the steps which I've wrote down in the description of this thread.

I thought the incognito is a completly seperated form any brave profile. Is Brave Shield only running in one instance, which will cause this issue?

Many thanks again for your answers!

**Comment by rebron** [comment]
@whosithat I'm going to go ahead and close this one out per your last comment. 

If you have "Continue where you left off" on startup which is the default, you will get new cookies for the sites again. It's not that they weren't deleted, it's just that the pages should be setting them again. 

Private browsing/incognito isn't exactly like a new profile since you have bookmarks and extensions available to you. It's just that your browsing history isn't saved.

**Comment by ShivanKaul** [comment]
It might just be that when you're opening and closing the private window you hit the 30 second timeout for "forget me when I close this site". We keep data around for 30 seconds just to make sure the user didn't accidentally close the tabs for a site.

**Comment by whosithat** [comment]
> If you have "Continue where you left off" on startup which is the default, you will get new cookies for the sites again. It's not that they weren't deleted, it's just that the pages should be setting them again.

That's the point which is confusing me. If I'm just closing brave completly (with "continue where you left off" activated and Shields "forget me when I close this site" also) the cookies will not be deleted / archived / recreated. But if I'm open a single incognito windows they will. I believe this happens, because in the incognito mode start's without any open tab, so brave shield believes that all the other tabs have been closed and will throw away the site data.

The question is: Is that a bug, or a feature? ;-P

**Comment by bsclifton** [comment]
> The question is: Is that a bug, or a feature? ;-P

![image](https://github.com/brave/brave-browser/assets/4733304/6e3b27a8-2ead-4003-a735-2e687db7ceac)

**Comment by whosithat** [comment]
Hey @diracdeltas, @ShivanKaul, @rebron, @MadhaviSeelam,

in my opinion this is a bug, as Brave Shield shouldn't remove any site data, as the tab haven't been closed. So it's a bug in the area of Brave Shield. Are you agree with me?

And if yes, should I create another issue, or can we reopen this one?

Many thanks!
