### ISSUE TITLE
[ads] sometimes tab events are not processed after browser restart

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#38420]
### Description

Follow up to https://github.com/brave/brave-browser/issues/38373

### Steps to reproduce

1. Clean profile
1. Run Brave with
```
--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6,"*/bat_ads/*"=6,"*/whats_new/*"=9 --variations-server-url=https://variations.bravesoftware.com/seed1 --rewards=staging=true,debug=true --use-dev-goupdater-url --enable-features=ShouldAlwaysRunBraveAdsService,ShouldAlwaysTriggerBraveSearchResultAdEvents,ShouldLaunchBraveAdsAsInProcessService,ShouldSupportSearchResultAds,ShouldAlwaysTriggerBraveNewTabPageAdEvents,CustomNotificationAds,NotificationAds:default_ads_per_hour/5,InlineContentAds:maximum_ads_per_day/1
```
3. Open NTP 
4. Open `brave.com` in the tab
5. Restart browser
6. Check logs for `Created tab with id` and `Tab id did become focused`

### Actual result

Events are not processed

### Expected result

Events are processed

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.68.29 Chromium: 125.0.6422.60 (Official Build) nightly (64-bit)
-- | --
Revision | 00e032de86c92faa949ed70f87fa29f9ef10aad6
OS | Linux

cc @tmancey @aseren

**Comment by btlechowski** [comment]
Verified with

Brave | 1.68.32 Chromium: 125.0.6422.60 (Official Build) nightly (64-bit)
-- | --
Revision | 07cffa57cd15d0fd66e102fdc5c906d5e49c9fc1
OS | Linux


Verified test plan from the description

Verified tab is restored
```
[16745:16745:0521/185008.222269:VERBOSE2:tab_manager.cc(233)] Restored focused tab with id 57455858
```

Verified switching tabs works
```
[16745:16745:0521/185208.475052:VERBOSE2:tab_manager.cc(249)] Tab id 57455858 did become occluded
[16745:16745:0521/185208.517968:VERBOSE2:tab_manager.cc(249)] Tab id 57455860 did become focused

```

**Comment by kjozwiak** [comment]
The above requires `1.66.113` or higher for `1.66.x` verification 👍 Removing `QA Pass` as we'll need to recheck using `1.66.x`. However, used https://github.com/brave/brave-browser/issues/38420#issuecomment-2123051415 as the needed verification for both `1.67.x` & `1.66.x` uplifts as per https://github.com/brave/brave-core/pull/23736#pullrequestreview-2070003887 & https://github.com/brave/brave-core/pull/23737#pullrequestreview-2070004046.

**Comment by btlechowski** [comment]
Verified with

Brave | 1.66.113 Chromium: 125.0.6422.76 (Official Build) (64-bit)
-- | --
Revision | b1864a9a0152d4f1631121c6b13a7426f50cf336
OS | Linux

Verified test plan from the description

Verified tab is restored
```
[5253:5253:0522/143752.948339:VERBOSE2:tab_manager.cc(243)] Restored focused tab with id 1888054382
```

Verified switching tabs works
```
[5253:5253:0522/143853.154349:VERBOSE2:tab_manager.cc(259)] Tab id 1888054384 did become occluded
[5253:5253:0522/143853.158069:VERBOSE2:tab_manager.cc(259)] Tab id 1888054382 did become focused

```
