### ISSUE TITLE
iOS app crashes when loading plaintextsports.com

### ISSUE THREAD

**Issue by PaulJuliusMartinez** [brave/brave-browser#38431]
### Description

Opening [plaintextsports.com](plaintextsports.com) in the iOS app causes the app to crash. This site is intentionally very, very simple, with everything contained in a single HTML file + favicon.svg + manifest.webmanifest, so hopefully it's easy to debug.

### Steps to reproduce

1. Open app
2. Navigate to plaintextsports.com

### Actual result

It crashes

### Expected result

The page should have loaded

### Reproduces how often

Easily reproduced

### Brave version

Version 1.65 (122)
BraveCore 1.65.122 (124.0.6367.82)

### Device/iOS version

iPhone 12 Pro/iOS 17.4.1

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

Originally reported by random Twitter user: https://x.com/ben_wagner99/status/1791489702937149443

**Comment by iccub** [comment]
Hi this is fixed in version 1.66, it should go live next week

**Comment by iccub** [comment]
1.66 is out let us know if it fixes the problem for you :)

**Comment by PaulJuliusMartinez** [comment]
Works like a charm. Thank you!!
