### ISSUE TITLE
Import from metamask regression

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#38430]
### Description
Regression after https://github.com/brave/brave-core/pull/23363

Import from metamask should work and don't stop after providing mm password

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.68.85 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | 8e76a669cf78bdfa933c8d569460092a01166588
OS | Windows 11 Version 23H2 (Build 22631.3737)

- Verified steps from issue
- Verified able to successfully import MetaMask wallet into Brave Wallet from onboarding

https://github.com/brave/brave-browser/assets/17010094/300fe785-b5ca-4951-86a0-c21f04a039fe
