### ISSUE TITLE
Support import of BTC zprv extended keys

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#38446]
Wallet's import account ui should support import of BTC accounts in format of zprv BIP84 extended keys.

https://learnmeabitcoin.com/technical/keys/hd-wallets/derivation-paths/#bip84

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.68.99 Chromium: 126.0.6478.126 (Official Build) beta (64-bit)
-- | --
Revision | 8ccc3a46e66d71dfd21506e1ccb42e08c7d33557
OS | Windows 11 Version 23H2 (Build 22631.3737)

- Verified steps from issue description
- Verified able to import Bitcoin account via `zprv` private keys for BIP84 derivation 
- Verified when using `xprv` or `yprv` private keys account restore fails
- Verified when imported `m/84'/0'/0'/0/0` is imported as the account address 
- Verified accounts created for 6/12/15/21/24 seed words import via private key works as expected

https://github.com/brave/brave-browser/assets/17010094/4e323e27-e1ae-4dc2-a4c4-cf673d1bd911

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.68.99 x64 Beta build
- Verified steps from issue description
- Verified able to import Bitcoin account via `zprv` private keys for BIP84 derivation 
- Verified when using `xprv` or `yprv` private keys account restore fails
- Verified when imported `m/84'/0'/0'/0/0` is imported as the account address 
- Verified accounts created for 6/12/15/21/24 seed words import via private key works as expected

https://github.com/brave/brave-browser/assets/17010094/3c3ceee7-f73b-4c64-a9db-7c1a9b1d759e
