### ISSUE TITLE
Support BTC Ledger hardware accounts

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#38447]
Test plan:
- Bitcoin is available on Import from hardware wallet UI by default. Bitcoin testnet is available when corresponding network is enabled in wallet's settings beforehand.
- Only Ledger is supported now. Please note: there are two different apps for Ledger - one for mainnet, another for testnet.
- Adding HW accounts should work.
- Wallet should be able to show HW accounts' balances.
- Signing transactions for HW accounts should work (i.e. transferring coins from BTC Ledger accounts)

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/41574#issuecomment-2482193391. Also encountered https://github.com/brave/brave-browser/issues/42336 & https://github.com/brave/brave-browser/issues/42338
