### ISSUE TITLE
[iOS] Add Tab Debug clipboard action

### ISSUE THREAD

**Issue by iccub** [brave/brave-browser#38449]
### Platforms

iOS

### Description

We see more 'lost tabs' problems recently. We were never able to reproduce it internally. To avoid fixing the issue blindly we want to let users share useful information with us. That should help us checking what could be wrong.

**Comment by kjozwiak** [comment]
The above requires `1.67.98` or higher for `1.67.x` verification 👍

**Comment by kjozwiak** [comment]
The above requires `1.66.120` or higher for `1.66.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.5
- iPad Air / iPadOS 16.7.2
Brave build: 1.66.1 (120)
BraveCore: 1.66.120 (125.0.6422.165)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/reviews/issues/1624#issuecomment-2125535694
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Copy Tabs info to clipboard` is present under `Version` section
- Verified that the data can be copied/paste/sent

---------------------------

`iPhone`

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/ea59e796-0e33-4fdd-b3e1-be14d2c973f7) | ![2](https://github.com/brave/brave-browser/assets/128532965/26649ba7-083e-40f0-b573-ed2ab7e76d09) |

`iPad`

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/a4c373ac-5884-4573-8c70-84935950eb17) | ![2](https://github.com/brave/brave-browser/assets/128532965/49412f37-804b-4225-a48e-24373fc20b14) |
