### ISSUE TITLE
Learn more link in the location bubble is not shown

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#38456]
### Description

Found https://github.com/brave/brave-browser/issues/16897.  Location bubble should display `Learn more` link and when clicked, it would redirect to https://support.microsoft.com/en-us/windows/windows-location-service-and-privacy-3a8eee0a-5b0b-dc07-eede-2a5ca1c49088. However, it appears in Win 11 & Win 10 testing, `Learn more` link doesn't display for Type A bubble.  After disabling and enabling location services in Windows settings, Type B & C bubbles do not show `Learn more` link either.

### Steps to reproduce

1. install 1.67.86
2. launch browser
3. open Developer Tools' Console tab
4. run navigator.geolocation.getCurrentPosition(() => {}, () => {}, { enableHighAccuracy : false });
5. verify `Type A` permission-prompt dialog was shown with general location request
6. dismiss the dialog (reset permission state if needed)
7. disable OS location service
8. run navigator.geolocation.getCurrentPosition(() => {}, () => {}, { enableHighAccuracy : true });
9. verify Type C bubble is shown
10. dismiss dialog and reset permission state if needed
11. enable OS location service, and ensured Brave Beta was checked
12. run navigator.geolocation.getCurrentPosition(() => {}, () => {}, { enableHighAccuracy : true });
13. verify Type B bubble is shown

### Actual result

Type A, Type B & Type C bubbles do not show `Learn more` link

Type A | Location service settings | Type B | Location service settings | Type C
------- | ------- | ------- | ------- | ---------- 
![image](https://github.com/brave/brave-browser/assets/98358127/4a5855f6-dfd3-4b0c-bcf9-0c2eda7ba26c)|![image](https://github.com/brave/brave-browser/assets/98358127/04ab793a-a239-4855-9fa0-bb3dec3c57c3)|![image](https://github.com/brave/brave-browser/assets/98358127/8ac00ed6-b579-413d-acf8-589aaf1624b0)|!![image](https://github.com/brave/brave-browser/assets/98358127/c590da87-9cb4-49cf-ad95-4e1c0b3e5476)|![image](https://github.com/brave/brave-browser/assets/98358127/bee7802d-30ee-42d1-b874-536a0faedce8)

### Expected result

`Learn more` link should display

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.67.90 Chromium: 125.0.6422.60 (Official Build) beta (64-bit)
-- | --
Revision | 64f9eec1a854079c3e529e908ca300071afb1f32
OS | Windows 11 Version 23H2 (Build 22631.3593)

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

@simonhong 
cc: @stephendonner

**Comment by stephendonner** [comment]
This also reproduces using `Win10-x64`:

```
build id
```

**Comment by simonhong** [comment]
checking now

**Comment by kjozwiak** [comment]
The above requires `1.67.99` or higher for `1.67.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.67.100 Chromium: 125.0.6422.112 (Official Build) beta (64-bit)
-- | --
Revision | 34fcbb6655521b55468af6c63601a8e3c5d24cd2
OS | Windows 11 Version 23H2 (Build 22631.3672)
```
Verified using STR from the issue description https://github.com/brave/brave-browser/issues/38456#issue-2308833110

Confirmed when clicked `Learn more` link, redirected to `Windows location service and privacy` page via 
https://support.microsoft.com/en-us/windows/windows-location-service-and-privacy-3a8eee0a-5b0b-dc07-eede-2a5ca1c49088

Type A | Type C | Type B 
------ | ----- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/3450a9ae-8224-44a2-85a2-89eb3a902067)|![image](https://github.com/brave/brave-browser/assets/98358127/7767cc7c-701d-4644-86e1-9735d7334c26)|![image](https://github.com/brave/brave-browser/assets/98358127/d10cf048-16cd-4029-b9c6-c8b07cb026da)
![image](https://github.com/brave/brave-browser/assets/98358127/96013c55-f783-4049-b8ef-929d4b7a49a9)|![image](https://github.com/brave/brave-browser/assets/98358127/07a51b02-27be-4d98-9746-d618a39aff8f)|![image](https://github.com/brave/brave-browser/assets/98358127/daf5dc2a-fc9c-45c8-a8a6-a8c7a5e521a3)

![image](https://github.com/brave/brave-browser/assets/98358127/d1b61764-ce15-477e-b46d-49eed1988826)
