### ISSUE TITLE
Always display Show Zero Balances button in Select a Token to Send

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#38452]
### Description

Currently the button is only displayed when 0 tokens (with balance) are shown. We could keep the the logic to 

### Steps to reproduce

1. Use wallet with 0 balance on some account and/or some network
2. Open Send
3. In `Select a Token to Send` modal, `Show Zero Balances` button is not displayed
4. If tokens displayed, filter to network without any balance on any account
5. `Show Zero Balances` button is displayed

### Actual result

`Show Zero Balances` button is not displayed

<img src="https://github.com/brave/brave-browser/assets/5314553/8ffe5e3e-b2c2-4132-b0ba-8b8bc32faf7f" width="300"> 

### Expected result

Always show `Show Zero Balances` button, but continue hiding zero balance accounts/tokens by default.

ex:
<img src="https://github.com/brave/brave-browser/assets/5314553/fb25a6bc-08e3-435f-a197-35dd740170d9f" width="300"> | <img src="https://github.com/brave/brave-browser/assets/5314553/d2d3a1d0-2ee0-4764-b9f5-5da1fcf7ec33" width="300">
--|--

### Reproduces how often

Easily reproduced

### Brave version

Release, Beta, Nightly

### Device/iOS version

iOS 17

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

Slight frontend UX improvement for https://github.com/brave/brave-browser/issues/38451

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.0 running 1.68 (115)
- Verified steps from [brave/brave-core#23831](https://github.com/brave/brave-core/pull/23831)
- Verified on Send screen shows zero balance button 
- Verified tapping on `Show Zero Balances` shows all zero balance tokens in Send screen
- Verified tapping on `Show Zero Balances` changes text to `Hide Zero Balance`
- Verified tapping on `Hide Zero Balances` hides all zero balance tokens in Send screen
- Encountered [#39639](https://github.com/brave/brave-browser/issues/39639)

https://github.com/brave/brave-browser/assets/17010094/379c2130-ab56-4008-9757-72a7c55f190b
