### ISSUE TITLE
Crash Report after update to 1.66.110

### ISSUE THREAD

**Issue by alanhoyle** [brave/brave-browser#38458]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.66.110 Chromium: 125.0.6422.60
Operating System: Mac OS X 14.5.0

URL (if applicable) where crash occurred:

Happend on startup, so whatever was in history.  

Can you reproduce this crash?

Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.  Open Brave
2. Choose to NOT resume 
3.  load amazon.com

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/379b1700-ce01-fb0b-0000-000000000000

**Comment by bsclifton** [comment]
Identical callstack to https://github.com/brave/brave-browser/issues/38460 - closing as a duplicate
