### ISSUE TITLE
Auto secure requests not always cleared after disabling DoH

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#38459]
The `Brave.DNS.AutoSecureRequests` metric (along with the fallback provider variants) sometimes does not clear when the user disables DNS-over-HTTPS.

**Comment by GeetaSarvadnya** [comment]
Steps 8 and 9 are failing, we can refer the https://github.com/brave/brave-browser/issues/37318#issuecomment-2120340140 for steps to reproduce the issue.

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.68.94 Chromium: 126.0.6478.114 (Official Build) beta (64-bit)
-- | --
Revision | 8981faf58380240eab6e999e6bf06f9ed9314336
OS | Windows 10 Version 22H2 (Build 19045.4529)
```

- Verified the test plan from https://github.com/brave/brave-core/pull/19479

**Prerequisite:**

- Configured the Cloudflare DNS settings on Windows 10
- Confirmed web traffic runs through  Cloudflare DNS Service 
- Visited the https://1.1.1.1/help and ensured `Connected to 1.1.1.1` is `Yes` and `Using DNS over HTTPS (DoH)` is `Yes`

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/90ed8b0e-0671-4939-bb6e-a43f015d8e07) | ![image](https://github.com/brave/brave-browser/assets/38657976/3e84ef50-de87-4d68-99ab-75f56f3d0007)


**Test plan steps:**

0. Ensure a DNS server that supports DoH (such as Cloudflare: 1.1.1.1) is configured in your OS network settings. Start with fresh profile.  - **PASSED**
1. Ensure that the secure setting metric `Brave.DNS.SecureSetting` has the response value of 1. - **PASSED**
![image](https://github.com/brave/brave-browser/assets/38657976/817819b4-2604-4024-931d-302ef82d76e4)
2. Make a random query on your search engine, click on a bunch unique links. **PASSED**
3. On the local state page, search for `upgraded_dns_requests` and `total_dns_requests`. Note the values. `upgraded_dns_requests` should have a positive value, if your OS settings are correct. - **PASSED**

`upgraded_dns_requests` value is `81` and  `total_dns_requests` value is `92`

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/f1daa4ac-88b2-43a8-802f-88244a94a032) | ![image](https://github.com/brave/brave-browser/assets/38657976/2155cfc1-5433-410f-8989-2fd08597acfa)

4. The percentage range indicated by the value of the auto-secure requests metric should encompass the ratio of `upgraded_dns_requests` to `total_dns_requests` (i.e. if the upgraded count is 10, and the total count is 15, the ratio would be 66% and the correct metric answer would be 2) - **PASSED**

In my case when I visit random links from search result page I have got the upgrade count is `81` and total dns requests count is `92`, the ratio would be `81/92` = `88%` and 88% fall under the response bucket `2` `Greater than 50 and less than 90%`, I am getting the the metrics `Brave.DNS.AutoSecureRequests` response value as `2` which is correct and expected.

![image](https://github.com/brave/brave-browser/assets/38657976/b3d329b4-4f8b-4865-b51d-0e21a65f89d6)


5. Disable the DoH supporting server in your OS settings (let DHCP do it's thing) - **PASSED**

- Disabled the cloudflare settings from the OS network setting and ran https://1.1.1.1/help and ensured that the cloudflare DNS settings are disabled

![image](https://github.com/brave/brave-browser/assets/38657976/b817df81-702a-42b8-9f8b-f2cf8d63180e)


6. Visit more sites, wait for 20 secs, reload local state file

Both uppgraded count (109) and total count (190) are increased

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/16578512-caf0-4a70-818b-0d9cccf3e111) | ![image](https://github.com/brave/brave-browser/assets/38657976/ae5172c3-112c-4d4b-b3c9-4c0f51105695)


6. 1 Repeat the step 6

7. Ensure that the `upgraded_dns_requests` count does not grow as you visit websites. The ratio of upgraded-to-total requests should increase as you visit more domains. The auto-secure requests metric value should also change accordingly. - **PASSED**

(Updated the step 7, the total count value is not lowered when we visit more websites)

The Uppgraded count (109) remains same, only total count (204) increases

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/9679916b-ae55-4244-8db3-567487d3da45) | ![image](https://github.com/brave/brave-browser/assets/38657976/e0b95991-aa20-430f-95ce-bf2f1e18dd6f)

![image](https://github.com/brave/brave-browser/assets/38657976/14e3331b-9e7f-45a2-bc38-ab421361e8f6)


8. Change your browser DoH setting to "With Cloudflare". `Brave.DNS.SecureSetting` should be 2, and `Brave.DNS.AutoSecureRequests` should disappear.  - **FAILED**

- Changed the DoH setting to "Cloudflare 1.1.1.1" via brave://settings/security
- Reload the brave://local-state file 
- Confirmes that the metrics `Brave.DNS.SecureSetting` response value is `2` `custom provider` as expected 
- Confirmed that the metrics `Brave.DNS.AutoSecureRequests` doesn't show up in the local state file (Note: The metrics `Brave.DNS.AutoSecureRequests` is shown with the response value `2` hence failed the case)

Example | Example | Example
----------|---------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/d1d5600f-e1d4-43c2-a5e2-45f61ebca5bf) | ![image](https://github.com/brave/brave-browser/assets/38657976/3a7aeb75-82b4-48a2-b6a9-53e8e8e08e1b) | ![image](https://github.com/brave/brave-browser/assets/38657976/ac6f797e-6091-4979-8c97-25ff86f2d0fd)


9. Turn off your browser DoH setting. Ensure both metrics do not exist. - **FAILED**

- Turned off the `Use secure DNS` via brave://settings/security
- Confirmed that the metrics `Brave.DNS.SecureSetting` doesn't show up in the local state file (Note: the metrics `Brave.DNS.SecureSetting` is shown with the response value `1` hence this step is failing)
- Confirmed that the metrics `Brave.DNS.AutoSecureRequests` doesn't show up in the local state file (Note: the metrics `Brave.DNS.AutoSecureRequests` is shown with the response value `2` hence this step is failing)

Example | Example | Example
----------|---------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/0ae0d34e-67e3-4930-bb12-205df773c0da) | ![image](https://github.com/brave/brave-browser/assets/38657976/266417b0-4650-4fa0-b823-fc7f531f6f71) | ![image](https://github.com/brave/brave-browser/assets/38657976/aa59bbfe-d58b-4a91-b32b-e0b358ce8d85)

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.68.94 Chromium: 126.0.6478.114 (Official Build) beta (64-bit)
-- | --
Revision | 8981faf58380240eab6e999e6bf06f9ed9314336
OS | Windows 10 Version 22H2 (Build 19045.4529)

```

- Verified the test plan from https://github.com/brave/brave-core/pull/19479

**Prerequisite:**

- Configured the Cloudflare DNS settings on Windows 10
- Confirmed web traffic runs through  Cloudflare DNS Service 
- Visited the https://1.1.1.1/help and ensured `Connected to 1.1.1.1` is `Yes` and `Using DNS over HTTPS (DoH)` is `Yes`

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/90ed8b0e-0671-4939-bb6e-a43f015d8e07) | ![image](https://github.com/brave/brave-browser/assets/38657976/3e84ef50-de87-4d68-99ab-75f56f3d0007)


**Test plan steps:**

0. Ensure a DNS server that supports DoH (such as Cloudflare: 1.1.1.1) is configured in your OS network settings. Start with fresh profile.  - **PASSED**
1. Ensure that the secure setting metric `Brave.DNS.SecureSetting` has the response value of 1. - **PASSED**
![image](https://github.com/brave/brave-browser/assets/38657976/817819b4-2604-4024-931d-302ef82d76e4)
2. Make a random query on your search engine, click on a bunch unique links. **PASSED**
3. On the local state page, search for `upgraded_dns_requests` and `total_dns_requests`. Note the values. `upgraded_dns_requests` should have a positive value, if your OS settings are correct. - **PASSED**

`upgraded_dns_requests` value is `81` and  `total_dns_requests` value is `92`

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/f1daa4ac-88b2-43a8-802f-88244a94a032) | ![image](https://github.com/brave/brave-browser/assets/38657976/2155cfc1-5433-410f-8989-2fd08597acfa)

4. The percentage range indicated by the value of the auto-secure requests metric should encompass the ratio of `upgraded_dns_requests` to `total_dns_requests` (i.e. if the upgraded count is 10, and the total count is 15, the ratio would be 66% and the correct metric answer would be 2) - **PASSED**

In my case when I visit random links from search result page I have got the upgrade count is `81` and total dns requests count is `92`, the ratio would be `81/92` = `88%` and 88% fall under the response bucket `2` `Greater than 50 and less than 90%`, I am getting the the metrics `Brave.DNS.AutoSecureRequests` response value as `2` which is correct and expected.

![image](https://github.com/brave/brave-browser/assets/38657976/b3d329b4-4f8b-4865-b51d-0e21a65f89d6)


5. Disable the DoH supporting server in your OS settings (let DHCP do it's thing) - **PASSED**

- Disabled the cloudflare settings from the OS network setting and ran https://1.1.1.1/help and ensured that the cloudflare DNS settings are disabled

![image](https://github.com/brave/brave-browser/assets/38657976/b817df81-702a-42b8-9f8b-f2cf8d63180e)


6. Visit more sites, wait for 20 secs, reload local state file

Both uppgraded count (109) and total count (190) are increased

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/16578512-caf0-4a70-818b-0d9cccf3e111) | ![image](https://github.com/brave/brave-browser/assets/38657976/ae5172c3-112c-4d4b-b3c9-4c0f51105695)


6. 1 Repeat the step 6

7. Ensure that the `upgraded_dns_requests` count does not grow as you visit websites. The ratio of upgraded-to-total requests should increase as you visit more domains. The auto-secure requests metric value should also change accordingly. - **PASSED**

(Updated the step 7, the total count value is not lowered when we visit more websites)

The Uppgraded count (109) remains same, only total count (204) increases

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/9679916b-ae55-4244-8db3-567487d3da45) | ![image](https://github.com/brave/brave-browser/assets/38657976/e0b95991-aa20-430f-95ce-bf2f1e18dd6f)

![image](https://github.com/brave/brave-browser/assets/38657976/14e3331b-9e7f-45a2-bc38-ab421361e8f6)


8. Change your browser DoH setting to "With Cloudflare". `Brave.DNS.SecureSetting` should be 2, and `Brave.DNS.AutoSecureRequests` should disappear.  - **FAILED**

- Changed the DoH setting to "Cloudflare 1.1.1.1" via brave://settings/security
- Reload the brave://local-state file 
- Confirmes that the metrics `Brave.DNS.SecureSetting` response value is `2` `custom provider` as expected 
- Confirmed that the metrics `Brave.DNS.AutoSecureRequests` doesn't show up in the local state file (Note: The metrics `Brave.DNS.AutoSecureRequests` is shown with the response value `2` hence failed the case)

Example | Example | Example
----------|---------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/d1d5600f-e1d4-43c2-a5e2-45f61ebca5bf) | ![image](https://github.com/brave/brave-browser/assets/38657976/3a7aeb75-82b4-48a2-b6a9-53e8e8e08e1b) | ![image](https://github.com/brave/brave-browser/assets/38657976/ac6f797e-6091-4979-8c97-25ff86f2d0fd)


9. Turn off your browser DoH setting. Ensure both metrics do not exist. - **FAILED**

- Turned off the `Use secure DNS` via brave://settings/security
- Confirmed that the metrics `Brave.DNS.SecureSetting` doesn't show up in the local state file (Note: the metrics `Brave.DNS.SecureSetting` is shown with the response value `1` hence this step is failing)
- Confirmed that the metrics `Brave.DNS.AutoSecureRequests` doesn't show up in the local state file (Note: the metrics `Brave.DNS.AutoSecureRequests` is shown with the response value `2` hence this step is failing)

Example | Example | Example
----------|---------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/0ae0d34e-67e3-4930-bb12-205df773c0da) | ![image](https://github.com/brave/brave-browser/assets/38657976/266417b0-4650-4fa0-b823-fc7f531f6f71) | ![image](https://github.com/brave/brave-browser/assets/38657976/aa59bbfe-d58b-4a91-b32b-e0b358ce8d85)

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.68.107`

- Verified the test plan from https://github.com/brave/brave-core/pull/19479

**Prerequisite:**

- Configured the Cloudflare DNS settings on Windows 10
- Confirmed web traffic runs through  Cloudflare DNS Service 
- Visited the https://1.1.1.1/help and ensured `Connected to 1.1.1.1` is `Yes` and `Using DNS over HTTPS (DoH)` is `Yes`

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/7ccfcb5d-f165-4624-8567-4a57d624355a) |![image](https://github.com/brave/brave-browser/assets/38657976/8ff3f171-6516-4132-9da4-70f6fc14d9ec)



**Test plan steps:**

0. Ensure a DNS server that supports DoH (such as Cloudflare: 1.1.1.1) is configured in your OS network settings. Start with fresh profile.  - **PASSED**
1. Ensure that the secure setting metric `Brave.DNS.SecureSetting` has the response value of 1. - **PASSED**
![image](https://github.com/brave/brave-browser/assets/38657976/bbf1bae0-64fa-4f4a-a6c2-1732231d1665)
2. Make a random query on your search engine, click on a bunch unique links. **PASSED**
3. On the local state page, search for `upgraded_dns_requests` and `total_dns_requests`. Note the values. `upgraded_dns_requests` should have a positive value, if your OS settings are correct. - **PASSED**

`upgraded_dns_requests` value is `58` and  `total_dns_requests` value is `70`

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/e36d538e-0137-4c8e-8b31-57c8a80846ac) | ![image](https://github.com/brave/brave-browser/assets/38657976/28a0bd24-f2b7-41b8-9715-0e9ca6bce6bd)



4. The percentage range indicated by the value of the auto-secure requests metric should encompass the ratio of `upgraded_dns_requests` to `total_dns_requests` (i.e. if the upgraded count is 10, and the total count is 15, the ratio would be 66% and the correct metric answer would be 2) - **PASSED**

In my case when I visit random links from search result page I have got the upgrade count is `81` and total dns requests count is `92`, the ratio would be `58/70` = `82%` and 82% fall under the response bucket `2` `Greater than 50 and less than 90%`, I am getting the the metrics `Brave.DNS.AutoSecureRequests` response value as `2` which is correct and expected.

![image](https://github.com/brave/brave-browser/assets/38657976/24de0355-5e1d-4116-ab86-d583de0d04d6)



5. Disable the DoH supporting server in your OS settings (let DHCP do it's thing) - **PASSED**

- Disabled the cloudflare settings from the OS network setting and ran https://1.1.1.1/help and ensured that the cloudflare DNS settings are disabled

![image](https://github.com/brave/brave-browser/assets/38657976/51e6aa11-828b-41d1-a7a9-d6ddc5364134)



6. Visit more sites, wait for 20 secs, reload local state file

Both uppgraded count (67) and total count (121) are increased

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/b6cb93e3-fdc5-489d-aef0-834c6c4840cf) | ![image](https://github.com/brave/brave-browser/assets/38657976/bc69689f-faf2-4f41-9400-4df385f45bee)


6. 1 Repeat the step 6

7. Ensure that the `upgraded_dns_requests` count does not grow as you visit websites. The ratio of upgraded-to-total requests should increase as you visit more domains. The auto-secure requests metric value should also change accordingly. - **PASSED**

(Updated the step 7, the total count value is not lowered when we visit more websites)

The Uppgraded count (67) remains same, only total count (195) increases

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/ea501f93-d18b-4cd3-8f23-33eaa1ff6d1d) | ![image](https://github.com/brave/brave-browser/assets/38657976/b7206ef0-8a86-42c5-968f-3f711fea4b39)


![image](https://github.com/brave/brave-browser/assets/38657976/b489b4ac-c5fd-4bf3-9384-0934a5c6c6a1)


8. Change your browser DoH setting to "With Cloudflare". `Brave.DNS.SecureSetting` should be 2, and `Brave.DNS.AutoSecureRequests` should disappear.  - **PASSED**

- Changed the DoH setting to "Cloudflare 1.1.1.1" via brave://settings/security
- Reload the brave://local-state file 
- Confirmes that the metrics `Brave.DNS.SecureSetting` response value is `2` `custom provider` as expected 
- Confirmed that the metrics `Brave.DNS.AutoSecureRequests` doesn't show up in the local state file 

Example | Example | Example
----------|---------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/e974efa2-3f2c-45a4-8321-244cec749e29) | ![image](https://github.com/brave/brave-browser/assets/38657976/de7ce4f1-28e8-4d1f-a27e-c69f8de0e22b) | ![image](https://github.com/brave/brave-browser/assets/38657976/7ff2d856-fa0a-423e-82c1-5b539d78a300)



9. Turn off your browser DoH setting. Ensure both metrics do not exist. - **PASSED**

- Turned off the `Use secure DNS` via brave://settings/security
- Confirmed that the metrics `Brave.DNS.SecureSetting` doesn't show up in the local state file 
- Confirmed that the metrics `Brave.DNS.AutoSecureRequests` doesn't show up in the local state file 

Example | Example | Example
----------|---------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/46d88a1f-a6d0-4da3-ba52-c71784641607) | ![image](https://github.com/brave/brave-browser/assets/38657976/5536f493-f1ba-4165-b04f-f769533315a2) | ![image](https://github.com/brave/brave-browser/assets/38657976/100918ad-b0d8-4df3-b399-7554b38e6efa)
