### ISSUE TITLE
[ads] sometimes tab events are not processed after browser restart

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#38464]
### Description

Follow up to https://github.com/brave/brave-browser/issues/38373

### Steps to reproduce

1. Clean profile
1. Run Brave with
```
--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6,"*/bat_ads/*"=6,"*/whats_new/*"=9 --variations-server-url=https://variations.bravesoftware.com/seed1 --rewards=staging=true,debug=true --use-dev-goupdater-url --enable-features=ShouldAlwaysRunBraveAdsService,ShouldAlwaysTriggerBraveSearchResultAdEvents,ShouldLaunchBraveAdsAsInProcessService,ShouldSupportSearchResultAds,ShouldAlwaysTriggerBraveNewTabPageAdEvents,CustomNotificationAds,NotificationAds:default_ads_per_hour/5,InlineContentAds:maximum_ads_per_day/1
```
3. Open NTP 
4. Open `brave.com` in the tab
5. Restart browser
6. Check logs for `Restored tab with id` 

### Actual result

Events are not processed

### Expected result

Events are processed

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.68.32 Chromium: 125.0.6422.60 (Official Build) nightly (64-bit)
-- | --
Revision | 00e032de86c92faa949ed70f87fa29f9ef10aad6
OS | Android 11

cc @tmancey @aseren

**Comment by kjozwiak** [comment]
@tmancey @btlechowski not sure what's going on with this one as it's been in the `1.68.x` milestone for some time but is also labelled as `closed/works-for-me`. However, even though it's closed, looks like it was still being triaged?

Either way, please re-open if this is still an issue and needs to be resolved.
