### ISSUE TITLE
Split news ads metric

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#38462]
Split the existing News ad views metric into two:

As a rewards user, how many News ads have I viewed in the past 7 days?
`Brave.Today.RewardsAdViews`

As a non-rewards user, how many News ads have I viewed in the past 7 days?
`Brave.Today.NonRewardsAdViews`

Buckets would remain the same.

cc @lukaslevert

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.68.87 Chromium: 126.0.6478.56 (Official Build) beta (64-bit)
-- | --
Revision | 786b6b66ebe624e5c4ef760b3fe3047ea61932de
OS | Windows 10 Version 22H2 (Build 19045.4529)

```

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.68.87 Chromium: 126.0.6478.56 (Official Build) beta (64-bit)
-- | --
Revision | 786b6b66ebe624e5c4ef760b3fe3047ea61932de
OS | Windows 10 Version 22H2 (Build 19045.4529)
```
### Brave.Today.RewardsAdViews

<details>
<summary>Brave.Today.RewardsAdViews = 0</summary>

</details>

<details>
<summary>Brave.Today.RewardsAdViews = 1</summary>

</details>

<details>
<summary>Brave.Today.RewardsAdViews = 2</summary>

</details>

<details>
<summary>Brave.Today.RewardsAdViews = 3</summary>

</details>

### Brave.Today.NonRewardsAdViews

<details>
<summary>Brave.Today.NonRewardsAdViews = 0</summary>

</details>

<details>
<summary>Brave.Today.NonRewardsAdViews = 1</summary>

</details>

<details>
<summary>Brave.Today.NonRewardsAdViews = 2</summary>

</details>

<details>
<summary>Brave.Today.NonRewardsAdViews = 3</summary>

</details>

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12`  running `Bravemonoarm64.apk_1.68.101`


### Brave.Today.RewardsAdViews

<details>
<summary>Brave.Today.RewardsAdViews = 0_PASSED</summary>

1. Clean profile 1.67.x
2. Enable rewards 
4. Open brave://local-state file
5. Look for the metrics `Brave.Today.RewardsAdViews` restart the browser if required
6. The metrics `Brave.Today.RewardsAdViews` response value is `0` as expected
![image](https://github.com/brave/brave-browser/assets/38657976/13da9221-11af-4cbe-8dbe-45be5f38a72a)

</details>

<details>
<summary>Brave.Today.RewardsAdViews = 1_PASSED</summary>

1. Clean profile 1.67.x
2. Enable rewards 
3. Open a NTP and enable Brave News and view an inline content Ad via Brave News
4. Open brave://local-state file
5. Look for the metrics `Brave.Today.RewardsAdViews`
6. The metrics `Brave.Today.RewardsAdViews` response value is `1` as expected
![image](https://github.com/brave/brave-browser/assets/38657976/9937df4a-adb5-4499-ba31-398662dda675)

</details>

<details>
<summary>Brave.Today.RewardsAdViews = 2_PASSED</summary>

Case 1:

1. Clean profile 1.67.x
2. Enable rewards 
3. Open a NTP and enable Brave News and view 2 inline content Ads via Brave News
4. Open brave://local-state file
5. Look for the metrics `Brave.Today.RewardsAdViews`
6. The metrics `Brave.Today.RewardsAdViews` response value is `2` as expected
![image](https://github.com/brave/brave-browser/assets/38657976/4bb5546e-793a-4940-b84b-fa39cb965380)

Case 2:

1. Clean profile 1.67.x
2. Enable rewards 
3. Open a NTP and enable Brave News and view 4 inline content Ads via Brave News
4. Open brave://local-state file
5. Look for the metrics `Brave.Today.RewardsAdViews`
6. The metrics `Brave.Today.RewardsAdViews` response value is `2` as expected

Example | Example
----------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/539cafe0-12e7-45fa-9ffd-d59fab0af026) | ![image](https://github.com/brave/brave-browser/assets/38657976/4a26af8e-b6b1-4f12-acc5-1ca540768140)


</details>

<details>
<summary>Brave.Today.RewardsAdViews = 3_PASSED</summary>

1. Clean profile 1.67.x
2. Enable rewards 
3. Open a NTP and enable Brave News and view 5 inline content Ads via Brave News
4. Open brave://local-state file
5. Look for the metrics `Brave.Today.RewardsAdViews`
6. The metrics `Brave.Today.RewardsAdViews` response value is `3` as expected

Example | Example
----------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/dda0726d-bff8-470f-81eb-4255ffe3414b) | ![image](https://github.com/brave/brave-browser/assets/38657976/e0f61802-7d4d-4a2d-a48e-4b607ed5846c)


</details>

### Brave.Today.NonRewardsAdViews

<details>
<summary>Brave.Today.NonRewardsAdViews = 0_PASSED</summary>

1. Clean profile 1.67.x
2. Open brave://local-state file
3. Look for the metrics `Brave.Today.NonRewardsAdViews`
4. Confirmed that the metrics `Brave.Today.NonRewardsAdViews` response value is `0` as expected

![image](https://github.com/brave/brave-browser/assets/38657976/7852f5ad-8191-4665-a8c4-a03bd4bd72af)

</details>

<details>
<summary>Brave.Today.NonRewardsAdViews = 1_PASSED</summary>

1. Clean profile 1.67.x
5. Don't enable rewards
6. Open an NTP and enable Brave News
7. View an Inline content ad via Brave News
8. Open brave://local-state
9. Look for the metrics `Brave.Today.NonRewardsAdViews `
10. Confirmed that the metrics `Brave.Today.NonRewardsAdViews ` response value is `1` as expected
![image](https://github.com/brave/brave-browser/assets/38657976/9c5a4219-285c-40fd-8fe4-2a0378e75bc7)

</details>

<details>
<summary>Brave.Today.NonRewardsAdViews = 2_PASSED</summary>

1. Clean profile 1.67.x
2. Don't enable rewards
3. Open an NTP and enable Brave News
4. View 2 Inline content ads via Brave News
5. Open brave://local-state
6. Look for the metrics `Brave.Today.NonRewardsAdViews `
7. Confirmed that the metrics `Brave.Today.NonRewardsAdViews ` response value is `2` as expected
![image](https://github.com/brave/brave-browser/assets/38657976/933fba2a-0c7b-4117-9418-1aa70eb9bd52)

</details>

<details>
<summary>Brave.Today.NonRewardsAdViews = 3_PASSED</summary>

1. Clean profile 1.67.x
2. Don't enable rewards
3. Open an NTP and enable Brave News
4. View 5 Inline content ads via Brave News
5. Open brave://local-state
6. Look for the metrics `Brave.Today.NonRewardsAdViews `
7. Confirmed that the metrics `Brave.Today.NonRewardsAdViews ` response value is `3` as expected
![image](https://github.com/brave/brave-browser/assets/38657976/b7f4d1fb-b16f-4e4a-87d7-6e2a14f3608e)

</details>
