### ISSUE TITLE
remove Beta label for Sync

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#3847]
## Description 
Remove (Beta) label for Sync on initial setup screen and main page.

Current
<img width="855" alt="Screen Shot 2019-03-21 at 8 20 37 PM" src="https://user-images.githubusercontent.com/5951041/54798701-1f9f4080-4c17-11e9-8721-a5744f742629.png">

<img width="852" alt="Screen Shot 2019-03-21 at 8 28 32 PM" src="https://user-images.githubusercontent.com/5951041/54798883-eca97c80-4c17-11e9-81de-f42dd3ec1b09.png">

Expected
see #3079

**Comment by rebron** [comment]
cc: @anthonypkeane

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.45 Chromium: 74.0.3729.75 (Official Build) beta(64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2068
![Screen Shot 2019-04-19 at 11 05 54 AM](https://user-images.githubusercontent.com/28145373/56430790-7e4aef00-6295-11e9-8934-a4f1d0c10921.png)
![Screen Shot 2019-04-19 at 11 20 13 AM](https://user-images.githubusercontent.com/28145373/56430792-8014b280-6295-11e9-8359-d4d33b1e935c.png)
