### ISSUE TITLE
Pending verification's/Release Notes from `1.66.x` milestones (includes all `iOS` issues)

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#38470]
Current list of issues that have been fixed/resolved via [`1.66.x - Release`](https://github.com/brave/brave-browser/milestone/474) & [`1.66.x - Release #2`](https://github.com/brave/brave-browser/milestone/490), haven't been verified by QA and should be completed before `1.66.x` goes out on `iOS`:

* [x] https://github.com/brave/brave-browser/issues/38342
* [x] https://github.com/brave/brave-browser/issues/37742

Current list of issues that were `release-notes/include` via [`1.66.x - Release`](https://github.com/brave/brave-browser/milestone/474) & [`1.66.x - Release #2`](https://github.com/brave/brave-browser/milestone/490) and should be added into the release notes for the `iOS 1.66.x` release:

1. [[iOS/Wallet]: Missing import legacy wallet toggle in onboarding #38123](https://github.com/brave/brave-browser/issues/38123)
2. [[iOS/Wallet] Unable to add custom network with chainId has single digit #37863](https://github.com/brave/brave-browser/issues/37863)
3. [[i18n] New European Union Locales #37637](https://github.com/brave/brave-browser/issues/37637)
4. [Using cached ad-block results after changing shield settings #37090](https://github.com/brave/brave-browser/issues/37090)
5. [[Follow up to #33275] Debouncing feature is not working for Base64 and Regex (multi) test cases #37026](https://github.com/brave/brave-browser/issues/37026)
6. [Only Show Visible Assets in Account Details #36806](https://github.com/brave/brave-browser/issues/36806)
7. [Add Claude 3 Haiku (Free) and Claude 3 Sonnet (Premium) to model selection #36802](https://github.com/brave/brave-browser/issues/36802)
8. [Cache AdBlock DAT files client side #36539](https://github.com/brave/brave-browser/issues/36539)
9. [[ads] New tab takeover iOS video ads #36435](https://github.com/brave/brave-browser/issues/36435)
10. [Expose the first party list in iOS #35210](https://github.com/brave/brave-browser/issues/35210)
11. [Use the debounce service from brave-core and drop the iOS custom service #36033](https://github.com/brave/brave-browser/issues/36033)
12. [[iOS] Merge all filter lists (including general ones) into one engine #36035](https://github.com/brave/brave-browser/issues/36035)
13. [Add support for transaction speed up/cancel/retry #36627](https://github.com/brave/brave-browser/issues/36627)
14. [Enable Brave Browser to be an AutoFill Provider #36028](https://github.com/brave/brave-browser/issues/36028)
15. [Upgrade from Chromium 125.0.6422.60 to Chromium 125.0.6422.76 #38465](https://github.com/brave/brave-browser/issues/38470)

**Comment by kjozwiak** [comment]
Closing as the above has been completed. @Uni-verse we'll just need to create release notes within this milestone when ready 👍
