### ISSUE TITLE
Change maximum Ads per day to 20 for Desktop and 12 for Android

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#3849]
Change maximum Ads per day to 20 for Desktop and 12 for Android

**Comment by LaurenWags** [comment]
Logged https://github.com/brave/browser-android-tabs/issues/1485 in Android repo to track testing Android part.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.4 x64` using the following build:

Brave | 0.63.47 Chromium: 74.0.3729.108 (Official Build) (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Mac OS X

* Went through the test plan outlined under https://github.com/brave/brave-core/pull/2030
* Created https://github.com/brave/brave-browser/issues/4207
