### ISSUE TITLE
[ads] Refactor purchase intent to listen for `OnTabDidChange` and `OnDidOpenNewTab` instead of `OnTextContentDidChange`

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#38493]
### Description

[ads] Refactor purchase intent to listen for `OnTabDidChange` and `OnDidOpenNewTab` instead of `OnTextContentDidChange` because we do not require the text.

**Comment by btlechowski** [comment]
Verified with

Brave | 1.68.94 Chromium: 126.0.6478.114 (Official Build) beta (64-bit)
-- | --
Revision | 8981faf58380240eab6e999e6bf06f9ed9314336
OS | Linux


Verified test plan from https://github.com/brave/brave-core/pull/23787

<details>



</details>
