### ISSUE TITLE
Crash Report - Spotify memory usage

### ISSUE THREAD

**Issue by sethforbtc** [brave/brave-browser#38499]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.66.110 Chromium: 125.0.6422.60
Operating System: Windows NT 10.0.22621

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Playing music via Spotify in an open tab
2. The memory usage for the tab becomes enormous, sometimes as much as 15 GB.
3. Then the tab crashes and I have to refresh.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/e26d1800-ce01-fb0b-0000-000000000000

**Comment by iefremov** [comment]
dupe https://github.com/brave/brave-browser/issues/36356
