### ISSUE TITLE
YouTube element arrangement wrong

### ISSUE THREAD

**Issue by 4Source** [brave/brave-browser#38490]
### Description

While watching videos on YouTube there are some problems with the arrangement of the video information and the video recommendations. Also getting some Errors in the Dev Console. I think this is part of YouTube trying to block AdBlockers. 

### Steps to reproduce

1. Enable AdBlocker
2. Go to YouTube 
3. Open video

### Actual result

![image](https://github.com/brave/brave-browser/assets/38220764/cb637cd8-6db7-463d-ba9b-15e9b993d18e)

![image](https://github.com/brave/brave-browser/assets/38220764/c66e79b5-d438-4418-be0f-90d4bd5ed286)

### Expected result

The Original YouTube arrangement with the video information below the video and recommendations left

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.66.110 Chromium: 125.0.6422.60 (Offizieller Build) (64-Bit) 

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment]
@4Source What ad blocker are you using? Are you talking about Shields or are you using a third party ad blocker in addition to Shields?

**Comment by 4Source** [comment]
Only ad block from brave but is already fixed
