### ISSUE TITLE
UI polish for NTP search widget, follow-up to #38300 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#38506]
### Description
<img width="950" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/e7ad97a5-8b99-4ef7-b24f-44579cc5dc8d">

- [x] There's a weird second glass effect above the search input
- [x] Icons (carat-down and search icon) should have a glass/50 color
- [x] Removed the outline on the dropup for engine selection, and added a divider. Cleans up the view a bit
- [ ] ~~Placeholder text should be glass/70 and use font/large/regular~~ Will be fixed with a Nala bump.
- [ ] The whole search input doesn't use a regular divider, uses a custom one called strokegradient/dark
- [ ] The dropdown to change engines doesn't open in the closed state. When I click on it, it opens the full thing instead of the dropdown

--------------------

### Autosuggestions

<img width="583" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/89675879-fe84-475f-8659-39c6e066ba6d">

- [x] Search term is black, should be glass/100
- [x] Search icons on the left shouldn't have a square background, and the color is glass/50 (note: Some of the icons come from chrome://resources/images, where it's quite hard to style them. This might need a nala update).
- [x] If we can divide the "Ask Leo" item like on the design, that'd be ideal
- [x] General stroke is the same as initial state, strokegradient/dark
- [ ] Need to add a close button when the input text is entered to clear the box
- [x] Link previews beneath results is glass/70

### Steps to reproduce

1. Use 1.68.130 or higher in Nightly channel

### Actual result

See description

### Expected result

See description

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.130 or higher

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Related: https://github.com/brave/brave-browser/issues/38300

**Comment by fallaciousreasoning** [comment]
**Note:** For me at least, the top borders and default text color are fine. 

**Note to self:** I think part of the reason for the border on the search box is that the backdrop filter doesn't have a border radius. Also, the placeholder text color should be inferred from the text color.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.68.86 Chromium: 126.0.6478.56 (Official Build) beta (64-bit)
-- | --
Revision | b4eadb4942277a3eb455fc7c3c8569185bd745af
OS | Windows 11 Version 23H2 (Build 22631.3737)
```

1. Installed 1.68.86
2. launched Brave
3. verified `NTP search widget` is shown on the new tab page by default
4. verified UI elements as below:

<details>
<summary>Confirmed second glass effect above the search input is not shown</summary>

1.67.110 | 1.68.86
------ | ------
![image](https://github.com/brave/brave-browser/assets/98358127/c7d9f74e-b4e1-4028-9f7a-894e86171071)|![image](https://github.com/brave/brave-browser/assets/98358127/58d84c76-fa85-4558-a40e-289a68d80f80)
</details>

<details>
<summary>Confirmed Icons (carat-down and search icon) are shown as per the screenshot</summary> 

- Confirmed search term is no longer shown black and shown as expected
- Confirmed Search icons on the left do not have square background and shown as per the screenshot
- Confirmed "Ask Leo" icon and a divider is shown
-  Confirmed Link previews beneath results are shown as expected as per the screenshot

1.67.110 | 1.68.86
------ | ------
<img width="435" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/23ca1513-eab5-4d11-8b44-64d59b121b0f">|<img width="435" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/56dafd46-391a-4b3e-9af8-7f452b3fa410">
</details>

<details>
<summary>Confirmed outline is removed on the dropup for engine selection, and a divider is shown</summary>

1.67.110 | 1.68.86
------ | ------
![image](https://github.com/brave/brave-browser/assets/98358127/8afdb5ce-0d73-41ca-8568-b977176ba43e)|![image](https://github.com/brave/brave-browser/assets/98358127/f9b35cd7-52a1-4b23-bb22-29363f59cf9c)
</details>
