### ISSUE TITLE
Excluded sites cannot be restored

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3850]
## Description 
Excluded sites cannot be restored

## Steps to Reproduce

   1. Clean profile 0.64.8
   2. Add a site to A-C table
   3. Exclude site from a-c table by clicking on Delete icon
   4. Click on ` ...1(Restore All)` link
   5. The excluded site is not restored

## Actual result:

Excluded sites cannot be restored

## Expected result:
Excluded sites should be restored

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.64.8 Chromium: 73.0.3683.75 (Official Build) nightly (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

### Reproducible on current release: No
- Does it reproduce on brave-browser dev/beta builds? No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information

@brave/legacy_qa

**Comment by jasonrsadler** [comment]
+1 repro:

Brave | 0.64.15 Chromium: 74.0.3729.22 (Developer Build) (64-bit)
-- | --
Revision | d183f516540c1a0c21310ced2e2170a534bca5a5-refs/branch-heads/3729@{#254}
OS | Mac OS X

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya so you still see restore all link? or what is the problem exactly. If I click on trashcan and then click restore all, link is removed and table is cleared. If I re-visit that publisher is added back to the table.

**Comment by kjozwiak** [comment]
@NejcZdovc did the behaviour change in `0.64.x` regarding restoring publishers back into the a-c table? When you restore under `0.63.20 Chromium: 73.0.3683.75`, the website is added back into the table. However under `0.64.8 Chromium: 73.0.3683.75`, clicking on `Restore All` doesn't add anything back into the a-c which might confuse users. Assuming this is what @GeetaSarvadnya is pointing out. CCing @LaurenWags.

Example of `0.63.20 Chromium: 73.0.3683.75`:

![devExample](https://user-images.githubusercontent.com/2602313/55042391-98334200-5007-11e9-850c-ef4cd0b16a72.gif)

Example of `0.64.8 Chromium: 73.0.3683.75`:

![nightlyExample](https://user-images.githubusercontent.com/2602313/55042495-168fe400-5008-11e9-8751-80476a2d53b4.gif)

**Comment by NejcZdovc** [comment]
@kjozwiak yes we changed this, so that it behaved the same as it behaved in Muon. https://github.com/brave/brave-browser/issues/3459

**Comment by NejcZdovc** [comment]
closing as this is expected
