### ISSUE TITLE
Blank screen on all sites including setting pages with 1.66.133 on Mac

### ISSUE THREAD

**Issue by solstudioim** [brave/brave-browser#38511]
### Description

I have version 1.66.133 on mac and all pages are blank while they have titles on the top. 

Setting pages also blank like: brave://settings/

### Steps to reproduce

1. Install Brave 1.66.133
2. Open web pages
3. Use mac Sonoma 14.5 Max Chip

### Actual result

![Markup on 2024-05-23 at 10:58:49](https://github.com/brave/brave-browser/assets/17371139/4e0a514a-8afa-4fbd-8945-0b8e75be1bb4)

### Expected result

Pages should all load

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.66.133
Mac OS 14.5 Sonoma

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [x] in the latest version of Chrome

**Comment by solstudioim** [comment]
Downgraded to version 110 didn't work

**Comment by rebron** [comment]
@solstudioim Did you mean version 1.66.113 (instead of 1.66.113?) Our latest version is 1.66.115. Can you update to that version and see if you're still experiencing the issue.

**Comment by rebron** [comment]
Closing as stale. 
@solstudioim We can reopen if you're still experiencing the issue in 1.73.89 our latest version.
