### ISSUE TITLE
[Android] Fix domain representation in Shields pop-up

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#38514]
More info: https://hackerone.com/reports/2501378

**Comment by kjozwiak** [comment]
The above requires `1.67.105` or higher for `1.67.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240426.023.B4 release-keys
Brave build: 1.67.105
Chromium: 126.0.6478.26 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/23927#issue-2327004704
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Shields` displays the end of the URL/Domain

---------------------------

|Reproduced|Verified|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/c249cc68-4771-49ee-a506-cad29f734855) | ![2](https://github.com/brave/brave-browser/assets/128532965/e19991e7-6683-4426-ae87-b6966d8d6d8a) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/51a3e245-ad32-4f7d-825c-698a1e300001) | ![2](https://github.com/brave/brave-browser/assets/128532965/c98fa045-4bac-4316-9671-1e6f49493f45) |
