### ISSUE TITLE
`Attention %` and `Include in Auto-contribute` options are shown in the BR panel for web3-only creator

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#38517]
### Description

Found while testing https://github.com/brave/brave-browser/issues/37464
`Attention %` and `Include in Auto-contribute` options are shown in the BR panel for web3-only creator

### Steps to reproduce

1. Clean profile 1.67.x
2. Enable rewards and connect uphold custodian
3. Open web3-only creator https://shredshark.ca/ in an NTP
4. Open the BR panel for https://shredshark.ca/
5. `Attention %` and `Include in Auto-contribute` options are shown in the BR panel 

### Actual result

The `Attention %` and `Include in Auto-contribute` options are shown in the BR panel for web3-only creator

![Screenshot_20240523_201923_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/d903ff1a-6773-4df1-b7a5-5bc2915ce8f3)

### Expected result

The `Attention %` and `Include in Auto-contribute` options should not be shown on the BR panel for web3-only creators

![image](https://github.com/brave/brave-browser/assets/38657976/66eb9720-ba89-4a3d-80fa-627f06f0d93f)

### Reproduces how often

Easily reproduced

### Brave version

1.67.90

### Device

- Brand/model: Samsung galaxy
- Android version:  12

### Channel information

- [ ] release (stable)
- [X] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by GeetaSarvadnya** [comment]
cc: @Miyayes @deeppandya @LaurenWags

**Comment by kjozwiak** [comment]
The above requires `1.67.112` or higher for `1.67.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on `Vivo X70 Pro version 12`  running `Bravemonoarm64.apk_1.67.112`
