### ISSUE TITLE
[C125] Leo suggestion doesn't have rounded corners

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#38516]
### Description

Due to upstream changes in C125 https://github.com/chromium/chromium/commit/d1b49f40581b6336dd8ab8a03153f7dd65ecc109

![Screenshot_20240523-094738](https://github.com/brave/brave-browser/assets/30602739/b6dc3528-d1f6-4d76-83d4-81e1989eb251)

### Steps to reproduce

1. Tap in url bar
2. Leo suggestion shape is rectangular

### Actual result

Leo suggestion shape is rectangular

### Expected result

Leo suggestion shape match other items (with rounded corners)

### Reproduces how often

Easily reproduced

### Brave version

1.68.x

### Device

- Brand/model: any
- Android version: any

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.66.115` or higher for `1.66.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.66.115 Chromium: 125.0.6422.112 (Official Build) (64-bit) 
Revision	a168513c9c84b6ba793d5eac01c725982187aeb4
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that Leo suggestion box in search has rounded corners. 

Example | Example
-|-
![Screenshot 2024-05-24 at 12 01 25 PM](https://github.com/brave/brave-browser/assets/17885425/b1409628-4e22-4ba2-9eba-82cf9099cf77) | ![Screenshot 2024-05-24 at 12 31 51 PM](https://github.com/brave/brave-browser/assets/17885425/7ecde809-b78e-4f19-9347-c43c6cc48af1)
