### ISSUE TITLE
When Rewards is set to OFF, click on `Enable Brave Rewards` does nothing

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3851]
## Description 

When Rewards is set to OFF, click on `Enable Brave Rewards` does nothing
## Steps to Reproduce

   1. Clean profile 0.64.8
   2. Enable rewards
   3. Turn off the rewards switch in `brave://rewards` page
   4. Open BR panel and click on `Enable Brave Rewards` button

## Actual result:

Click on `Enable Brave Rewards` does nothing

## Expected result:
Click on  `Enable Brave Rewards` should enable the rewards

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.64.8 Chromium: 73.0.3683.75 (Official Build) nightly (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

### Reproducible on current release: No
- Does it reproduce on brave-browser dev/beta builds? No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information

@brave/legacy_qa

**Comment by jasonrsadler** [comment]
cc @ryanml 
@GeetaSarvadnya I believe expected functionality is the BR panel 'Enable' simply navigates to Rewards page to allow user to enable on the Rewards page

**Comment by ryanml** [comment]
@nejczdovc @jenn-rhim are you fine with current behavior of navigation or would you like the button to turn on Rewards directly?

**Comment by NejcZdovc** [comment]
@ryanml button should enable rewards directly

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.64.68 Chromium: 74.0.3729.108 (Official Build) beta (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Windows 10 OS Build 17134.523

- Verified the STR mentioned in the description
