### ISSUE TITLE
[Cr126] Omnibox overlaps on the first Brave launch

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#38524]
### Description

Omnibox overlaps on the first Brave launch. The issue is not seen after Brave restart.

### Steps to reproduce

1. Fresh install and launch Brave `1.68.38` with `Cr126`
2. Go through the onboarding
3. Land on `NTP` > *Observe*

### Actual result

Omnibox overlaps on the first Brave launch. The issue is not seen after Brave restart.

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/89e3b8ec-88f5-461e-ad7b-2a153f1f197b) | ![2](https://github.com/brave/brave-browser/assets/128532965/431a019f-db56-44e4-af68-f33dcd7f0aa2) |

https://github.com/brave/brave-browser/assets/128532965/43980414-c4b0-4cb6-90f7-1e0fcf97726f

### Expected result

Omnibox must not be overlapped.

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.68.38 
Chromium: 126.0.6478.17 (Official Build) canary (64-bit) 

### Device

- Brand/Model: Google Pixel 6
- Android version: oriole-user 14 AP1A.240505.004 release-keys

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by AlexeyBarabash** [comment]
this is fixed at https://github.com/brave/brave-core/pull/23233/commits/5c3d0b7f4f190ee04afbba8dc6f72c737ad9730f
