### ISSUE TITLE
Xcode build failed braveCore with output ios_current_link

### ISSUE THREAD

**Issue by minh1997** [brave/brave-browser#38523]
### Platforms

iOS, macOS

### Description

I followed the instructions step by step from documenation: https://github.com/brave/brave-browser/blob/master/README.md

```
git clone git@github.com:brave/brave-core.git path-to-your-project-folder/src/brave
cd path-to-your-project-folder/src/brave
npm install

# the Chromium source is downloaded, which has a large history (gigabytes of data)
# this might take really long to finish depending on internet speed

npm run init -- --target_os=ios

npm run build -- --target_os=ios 

```
<img width="991" alt="Screenshot 2024-05-24 at 00 30 17" src="https://github.com/brave/brave-browser/assets/11721352/f060cf5f-d69e-41eb-ac01-59380b1efe4d">

After done for build all the BraveCore then I open Xcode with command
`npm run ios_bootstrap -- --open_xcodeproj`

Finally I get the errors with output from braveCore I was build it before. Is there any step I'm missing?? Thanks all

<img width="1580" alt="Screenshot 2024-05-23 at 23 40 38" src="https://github.com/brave/brave-browser/assets/11721352/fc686350-d883-4a2f-b293-14496469964d">

**Comment by atybmx** [comment]
Hi, I'm getting the same error, did you resolve?
