### ISSUE TITLE
Differentiate between mainnet and testnet in default account names

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#38526]
### Description

Currently there are different account types for Filecoin and Bitcoin, one for Mainnet and one for Testnet. Both currently use the same default name (no name entered), so it's

### Steps to reproduce

1. Switch to accounts tab
2. Tap `...` and tap `Add Account`
3. Select Filecoin
    - Default should have Filecoin Mainnet selected
4. Do not enter a name and tap `Add`
5. Tap `...` and tap `Add Account` again
6. Select Filecoin
7. Change network to Filecoin Testnet
8. Do not enter a name, and tap `Add`

### Actual result

`Filecoin Account 1` (Mainnet account address starts with `f`) and `Filecoin Account 2` (Testnet account starts with `t`) are created.

<img src="https://github.com/brave/brave-browser/assets/5314553/a627ac79-05b3-4a7e-be57-45035ed3c8d4" width="300">

### Expected result

Mainnet accounts still default to `Filecoin Account #`, where testnet accounts include `Testnet`.

### Reproduces how often

Easily reproduced

### Brave version

All with Filecoin support

### Device/iOS version

iOS 15+

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

As part of work for https://github.com/brave/brave-browser/issues/37740, we will be creating accounts automatically for networks selected during onboarding. As a result we may be creating Filecoin Mainnet & Filecoin Testnet accounts (or Bitcoin Mainnet & Bitcoin Testnet accounts). It's better we differentiate which is which, especially for Bitcoin which does not display an address to differentiate which is which.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.0 Beta running1.68 (110) 
- Verified steps from [brave/brave-core#23815](https://github.com/brave/brave-core/pull/23815)
- Verified tokens show mainnet / testnet when opened from account asset details view

https://github.com/brave/brave-browser/assets/17010094/a463acae-e567-476e-a77d-f56304259127
