### ISSUE TITLE
Build out and enable Bridging in Wallet UI

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#38527]
### Platforms

Linux, macOS, Windows

### Description

Now that https://github.com/brave/brave-browser/issues/36335 and https://github.com/brave/brave-browser/issues/37212 are merged, we need to enable `Bridging` in the `Wallet` UI.

Reference our `Figma` designs here https://www.figma.com/design/26xCR66ZscSyVpTKrt85Hn/Transactions-2024?node-id=1-47452&t=t80kvZcDN6I0pDGo-0

Should utilize the existing `Swap` UI with addition information and features

- `Est time` quote information
- `Recipient` Allowing to select a different account to for the `Receiving` token.

![Screenshot 1](https://github.com/brave/brave-browser/assets/40611140/6c4c2d72-6153-43e4-8f23-115024b1b9c7)

![Screenshot](https://github.com/brave/brave-browser/assets/40611140/76e67cbf-9212-49ad-9231-640de13ab124)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.147 Chromium: 128.0.6613.40 (Official Build) (64-bit)
-- | --
Revision | d29b1747d0f906239936b0d94c40889920ebf2c0
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from [brave/brave-core#23817](https://github.com/brave/brave-core/pull/23817)
- Verified Bridge work as expected

https://github.com/user-attachments/assets/6f557fcc-acbf-4002-ae21-a4ff273c7ec7
