### ISSUE TITLE
[Cr126] Open `New tab` button shown at the top of the `Tab overview` screen on the first Brave launch

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#38525]
### Description

Open the `New tab` button shown at the top of the `Tab overview` screen on the first Brave launch.

### Steps to reproduce

1. Fresh install and launch Brave `1.68.38` with `Cr126`
2. Go through the onboarding
3. Land on `NTP`
4. Tap the `Tab switch` button > *Observe*

### Actual result

Open the `New tab` button shown at the top of the `Tab overview` screen on the first Brave launch.

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/d547accd-fac4-4e4f-b005-001dde5c606a) | ![2](https://github.com/brave/brave-browser/assets/128532965/50f8c4fc-484f-4c66-85ff-2e8b891d7983) |

### Expected result

Open the `New tab` button which must look like a `+` must be shown at the bottom of the `Tab overview` screen.

|1|
|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/e7f021a8-22a9-48cd-8c31-02f303c51bdd) |

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.68.38
Chromium: 126.0.6478.17 (Official Build) canary (64-bit)

### Device

- Brand/model: Google Pixel 6
- Android version: oriole-user 14 AP1A.240505.004 release-keys

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by AlexeyBarabash** [comment]
this is fixed at https://github.com/brave/brave-core/pull/23233/commits/5c3d0b7f4f190ee04afbba8dc6f72c737ad9730f 

thanks @hffvld
