### ISSUE TITLE
Missing color from download bubble

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#38531]
### Description

red icon color means that color is missed.

<img width="360" alt="Screenshot 2024-05-24 at 10 24 11 AM" src="https://github.com/brave/brave-browser/assets/6786187/f6f48d93-8743-472f-a678-ed86ca09b435">

### Steps to reproduce

1. Try to download anything
2. 
3. 

### Actual result

red icon color

### Expected result

No read

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.66.113 Chromium: 125.0.6422.76 (Official Build) (x86_64) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Any red color in native UI means that color is missed.
cc @brave/qa-team

**Comment by TEMP-ad** [comment]
Also, Private window:

![image](https://github.com/brave/brave-browser/assets/156715894/442082c8-920e-4f10-ae0e-395149d32573)

**Comment by simonhong** [comment]
Confirmed that this is fixed in `cr126`.
As `cr126` will be included to next stable(`1.67.x`), I think leave as-is is fine. WDYT? @stephendonner

**Comment by kjozwiak** [comment]
> Confirmed that this is fixed in `cr126`. As `cr126` will be included to next stable(`1.67.x`), I think leave as-is is fine. WDYT? @rebron @stephendonner

Closing the above as per the above so QA can check to make sure this has been resolved via `1.67.x` running `C126`. @brave/qa-team if this is still an issue, please re-open and remove from the `1.67.x` milestone 👍
