### ISSUE TITLE
[Wallet] Allow hiding un-owned NFTs in portfolio

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#38549]
### Description

We should add a toggle to enable/disable showing NFTs that are not owned by any wallet account
<img width="477" alt="Screenshot 2024-05-24 at 8 16 03 AM" src="https://github.com/brave/brave-browser/assets/30185185/fac03772-b004-409f-b59a-fef7b093789c">

### Steps to reproduce

1. create a wallet
2. add an NFT that is owned by one of your accounts
3. import an NFT that is not owned by any of your accounts 
4. view the portfolio NFTs tab
5. open the filters modal

### Actual result

There is no option to hide unowned NFTs; The unowned NFTs will always be displayed

### Expected result

There should be an option to hide unowned NFTs; The unowned NFTs will be displayed only if the option is set to not hide unowned NFTs

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.66.113 Chromium: 125.0.6422.76 (Official Build) (arm64) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/38547#issuecomment-2162706887
