### ISSUE TITLE
[Wallet] Paginate portfolio NFT screen

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#38547]
### Description

We should add pagination to the NFT page to prevent page slowdowns due to displaying many NFTs at once

<img width="765" alt="Screenshot 2024-05-24 at 8 16 30 AM" src="https://github.com/brave/brave-browser/assets/30185185/272488ec-832c-4ccb-998d-13d04f5b0780">

### Steps to reproduce

1. Create a wallet with many NFTs
2. open the wallet
3. go to the NFT tab of the portfolio page

### Actual result

The wallet performance decreases as more NFTs are added

### Expected result

The NFT page should have pagination to prevent loading many NFTs at once

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.66.113 Chromium: 125.0.6422.76 (Official Build) (arm64) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.68.85 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | 8e76a669cf78bdfa933c8d569460092a01166588
OS | Windows 11 Version 23H2 (Build 22631.3672)

- Verified steps from [brave/brave-core#23816](https://github.com/brave/brave-core/pull/23816)
- Verified NFTs are listed in page
- Verified searching NFTs shows page 1 as search result
- Verified enabling `Hide not owned NFTs`, removes NFTs that are not owned and updates the pagination 
- Encountered [#38986](https://github.com/brave/brave-browser/issues/38986)

https://github.com/brave/brave-browser/assets/17010094/06e9b8cf-f2f5-47cd-b522-50cbb0865edc
