### ISSUE TITLE
Loading a URL that would trigger a calendar invite doesn't work on NTP/other websites

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#38548]
### Description

The iOS app supports opening a Safari web view to handle adding iCal files to the users calendar but this is currently not working when you attempt to load that URL from the NTP or any website that isn't the origin of the 

### Steps to reproduce

1. Paste  `https://developer.apple.com/wwdc23/WWDC2023.ics` into the URL bar and load it from the NTP or any tab that doesn't have `developer.apple.com` loaded in it

### Actual result

Doesn't prompt to add to calendar

### Expected result

Should prompt to add to calendar

### Reproduces how often

Easily reproduced

### Brave version

This issue affects 1.62+

### Device/iOS version

All

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.66.120` or above for `1.66.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.5
Brave build: 1.66.1 (120)
BraveCore: 1.66.120 (125.0.6422.165)
```
Filed follow-up issue #38838
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/38548#issue-2315542876
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the prompt to add calendar event is shown on the `NTP` when passing a link for `iCal`

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/43f953af-93ca-46e6-a1ac-9107699b6da6) | ![2](https://github.com/brave/brave-browser/assets/128532965/01d0e989-fe46-4cb7-9fdb-7015db479d45) | ![3](https://github.com/brave/brave-browser/assets/128532965/30448df9-5fd1-4a9c-b427-1fe7a42fce02) |

https://github.com/brave/brave-browser/assets/128532965/010de9c0-2a75-4d59-ac00-28d891fa71a6
