### ISSUE TITLE
Bridge Transactions are not Parsed Correctly in Activity Tab

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#38552]
### Description

`Bridge` transactions are not parsed correctly in the `Activity` tab.

### Steps to reproduce

1. Open the `Wallet` and navigate to the `Bridge` screen
2. Create a `Bridge` transaction
3. Now navigate to the `Activity` tab
4. The `Bridge` transactions does not get parsed correctly, is missing information and token `Icons`.

### Actual result

![Screenshot 2](https://github.com/brave/brave-browser/assets/40611140/9f5823f2-2e77-4aee-8476-e1e219e89826)

![Screenshot 3](https://github.com/brave/brave-browser/assets/40611140/f01bfa54-b3a4-4d1f-97ae-4916c5e1a760)

### Expected result

Should display the same information as a `Swap` transaction

![Screenshot 4](https://github.com/brave/brave-browser/assets/40611140/45bfc95c-e254-4e0f-862c-c46f4c623104)

![Screenshot 5](https://github.com/brave/brave-browser/assets/40611140/bb70e388-b81e-413d-b373-e1269f1c6ff2)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.131 Chromium: 127.0.6533.88 (Official Build) beta (arm64) 

### Channel information

- [ ] release (stable)
- [x] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.138 Chromium: 127.0.6533.100 (Official Build) beta (64-bit)
-- | --
Revision | 2569cce791e23282c250db59de277f2e81c33d9b
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24968](https://github.com/brave/brave-core/pull/24968)
- Verified Bridge transaction parsing works as expected

https://github.com/user-attachments/assets/a9e0f23f-91c7-44f7-9116-862c857205c5
