### ISSUE TITLE
Download prompts can appear after switching tabs

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#38551]
### Description

Tapping on a link that would prompt the user to download a file can appear even after switching tabs

### Steps to reproduce

1. Find a page to download something (e.g. 1Password download page)
2. Click to download or paste download URL
3. Quickly tap the `+` button in the toolbar to add a new tab

### Actual result

![image](https://github.com/brave/brave-browser/assets/529104/c0e6d3bd-fa0d-4f81-915d-6e303252fff7)

### Expected result

The download prompt should be tied to the tab itself and not appear when the tab has been backgrounded

### Reproduces how often

Easily reproduced

### Brave version

1.66 but likely an issue for a long time

### Device/iOS version

iOS 17.4 (iPhone), but will be a problem on all devices/versions

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by iccub** [comment]
@stoletheminerals hi do you want this uplifted or can it sit in release version 1.68?

**Comment by stoletheminerals** [comment]
@iccub would be good to get it uplifted

**Comment by kjozwiak** [comment]
The above requires `1.66.120` or higher for `1.66.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.5
- iPad Air / iPadOS 16.7.2
Brave build: 1.66.1 (120)
BraveCore: 1.66.120 (125.0.6422.165)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/38551#issue-2315589448
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `download` pop-up message is not shown on the `NTP`
- Verified that it's still possible to download a file from the correct page

---------------------------

`Reproduced in 1.66 (113)`


https://github.com/brave/brave-browser/assets/128532965/716f3f92-5974-4cb7-b804-25780aa0a407

`Verified In 1.66.1 (120) on iPhone`

https://github.com/brave/brave-browser/assets/128532965/396df35a-6218-406f-bba4-6b7ade97ba84

`Verified In 1.66.1 (120) on iPad`

https://github.com/brave/brave-browser/assets/128532965/93baccc5-8864-4bf0-b700-a5a3f549912c
