### ISSUE TITLE
Share/Copy/Edit tools not shown in url bar for sites loaded by only typing eTLD

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#38563]
### Description

Share/Copy/Edit tools are not shown on webpages when focusing on url bar that are loaded by using eTLD+1. For example if you type `brave.com` without including `https://www.` this will be the case. 

Related to https://github.com/brave/brave-browser/issues/38507

### Steps to reproduce

1. New install
2. Open new tab, type in `brave.com` or `https://yahoo.com`
3. Once the page loads, tap on the URL bar

### Actual result

Example | Example
-|-
![Screenshot 2024-05-24 at 12 00 53 PM](https://github.com/brave/brave-browser/assets/17885425/e45fcd05-e2c1-4d88-ab6a-3a0587592ea0) | ![Screenshot 2024-05-24 at 12 01 25 PM](https://github.com/brave/brave-browser/assets/17885425/a2bae28d-82b0-477a-ba95-c2a9a8923ed6)

### Expected result

![Screenshot 2024-05-24 at 10 58 55 AM](https://github.com/brave/brave-browser/assets/17885425/92a8b323-6b01-48cb-9f66-b5548c1d7863)

### Reproduces how often

Easily reproduced

### Brave version

1.66.x - reproducible

### Device

- Brand/model: Samsung Galaxy devices 
- Android version: 13

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Chrome behavior when focusing on URL bar clears field and displays the share/copy/edit tools
Brave pre C125 show the tools when focusing on URL bar.

**Comment by hffvld** [comment]
`Brave` and `Chrome` have different behavior:

- In `Brave` when you tap on a web address, the address is shown and selected automatically.
- In `Chrome` when you tap on a web address, the address is not shown and the `Share`, `Copy`, & `Edit` buttons are shown.

So, in `Brave` if you type the address without `https://www.` `Share`, `Copy` & `Edit` are not shown, but if you tap `x` to remove the address, these buttons appear similar to what Chrome has.

*Brave*

https://github.com/brave/brave-browser/assets/128532965/33b94aaa-4622-4640-b569-3fefcc1a59a0

*Chrome*

https://github.com/brave/brave-browser/assets/128532965/c46d67b6-e395-4805-98bb-6889b8b969b2

**Comment by kjozwiak** [comment]
The above requires `1.66.117` or higher for `1.66.x` verification 👍 Added `QA/Test-All-Platforms` so we're not sure the above is working on `Mobile` & `Tablet`.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using version

```
Brave	1.66.118 Chromium: 125.0.6422.147 (Official Build) (64-bit) 
Revision	07af53490e0a52336cfb99a376f87671be258049
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Verified test plan in https://github.com/brave/brave-browser/issues/38563#issue-2315916083
- Verified navigating to webpages via links or typing URLs will show the Share/Copy/Edit tools when tapping on the address bar.

Using link | Typing eTLD | Clearing url bar
-|-|-
![Screenshot 2024-05-31 at 11 59 41 AM](https://github.com/brave/brave-browser/assets/17885425/0c834de4-3d7d-46a8-bffc-a61292e1a55b) | ![Screenshot 2024-05-31 at 12 00 26 PM](https://github.com/brave/brave-browser/assets/17885425/fe958ef5-abfd-41c3-9564-c0fca6e9ae2e) | ![Screenshot 2024-05-31 at 12 00 31 PM](https://github.com/brave/brave-browser/assets/17885425/852ca11f-2cce-459d-849b-dc70b53bc82b)
![Screenshot 2024-05-31 at 12 06 38 PM](https://github.com/brave/brave-browser/assets/17885425/5e569eba-97da-4691-bba0-651747cf697e) | ![Screenshot 2024-05-31 at 12 07 04 PM](https://github.com/brave/brave-browser/assets/17885425/7be82f78-5ff3-4dea-b32c-f83ab8c884b3) | ![Screenshot 2024-05-31 at 12 07 32 PM](https://github.com/brave/brave-browser/assets/17885425/c07612b8-f001-4a00-9f05-bb923efae098)

**Comment by hairycactus** [comment]
> @kjozwiak: The above requires `1.66.117` or higher for `1.66.x` verification 👍 Added `QA/Test-All-Platforms` so we're not sure the above is working on `Mobile` & `Tablet`.

The `Share | Copy | Edit` icons are still missing when the URL bar is tapped -- as observed in my:
- Brave Android v1.66.118 x64 (released: 31 May 2024)
- OS: Android v12 x64

The only workarounds for copying/ pasting text from/ into the URL bar are either via long-pressing the URL bar, or by using Gboard keypad's text-select tool menu.

#### Screenshots:
![BraveAndroid1.66.118(31May24)-MissingCopyEditPasteOptions-URLBar2](https://github.com/brave/brave-browser/assets/9943769/4b5e51e2-6d85-476b-91bf-da473c85a2ec)

![BraveAndroid1.66.118(31May24)-MissingCopyEditPasteOptions-URLBar3](https://github.com/brave/brave-browser/assets/9943769/b3bd678c-88e9-4b8b-974c-c21bee52bd8b)
