### ISSUE TITLE
Remove Brave Swap Fee

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#38566]
### Description

We should remove `Brave Fee` for Swaps on all platforms. WebUI for desktop & Android, native for iOS. Implementation TBD.

![Desktop & Android WebUI Swap](https://github.com/brave/brave-browser/assets/5314553/9c9dcfc7-d076-4e5e-bab3-7b2001c2f376) | ![iOS Swap](https://github.com/brave/brave-browser/assets/5314553/1732e146-c5af-46df-9ef9-6d0ef436ddd8)
--|--

### Steps to reproduce

1. Fetch a price quote in swap
2. `Brave Fee` label is shown with a percentage beside it

### Actual result

Brave fee is shown for swaps (Ethereum & Solana)

### Expected result

No Brave fee for swaps (Ethereum or Solana)

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

All

### Android device

All

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.66.120` or higher for `1.66.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.120 Chromium: 125.0.6422.165 (Official Build) (64-bit)
-- | --
Revision | bd9a9589253e659c93a1c77eb9a3974525a80312
OS | Windows 11 Version 23H2 (Build 22631.3672)

- Verified steps from [brave/brave-core#23960](https://github.com/brave/brave-core/pull/23960)
- Verified Brave fee is set to `0%` on all Swap transactions

https://github.com/brave/brave-browser/assets/17010094/7bd7fe2f-a9d0-4960-8d64-93e0eea19074

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.66.120 x64 build
- Verified steps from [brave/brave-core#23960](https://github.com/brave/brave-core/pull/23960)
- Verified Brave fee is set to `0%` on all Swap transactions

https://github.com/brave/brave-browser/assets/17010094/7f23682c-b6c3-4e62-841b-a1a35c77109d

**Comment by srirambv** [comment]
Verification passed on iPhone 13 running 1.66.1 (120)
- Verified steps from [brave/brave-core#23960](https://github.com/brave/brave-core/pull/23960)
- Verified Brave fee is set to `0%` on all Swap transactions

https://github.com/brave/brave-browser/assets/17010094/bf70834c-651d-4d74-8a1d-f4f48c9a9023

**Comment by kjozwiak** [comment]
Moved this into the `1.67.x` milestone as we're not going to be releasing another `1.66.x` with `C125`. We'll be releasing `C126` via `1.67.x` on `June 13th`. Added so it can be included in the `1.67.x` release notes.

However, keep in mind that the above was released on `Android` via `1.66.x - Release #6` so there's no need to add the above into the release notes for `Android`. CCing @hffvld.
