### ISSUE TITLE
Search promotion UI layout regressions

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#38579]
### Description

Promotion UI layout is broken for narrow width.
It was fixed by https://github.com/brave/brave-browser/issues/37531 but happened again with cr126.
<img width="649" alt="Screenshot 2024-05-27 at 10 16 00 AM" src="https://github.com/brave/brave-browser/assets/6786187/70c01288-7f44-4df0-a4da-168d12a69ade">

### Steps to reproduce

1. Launch brave with `--enable-features=BraveSearchOmniboxBanner:banner_type/type_B` cmd args
2. Set non-brave search as a default search provider
3. Type anything and check promotion UI in omnibox popup

### Actual result

See the screen shot above

### Expected result

Promotion UI should have sufficient height to show its UI properly
<img width="746" alt="Screenshot 2024-05-27 at 10 15 49 AM" src="https://github.com/brave/brave-browser/assets/6786187/45e4cf66-e7c4-46e0-b02b-041437e927f1">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Latest master with `cr126`

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @brave/qa-team @rebron

**Comment by simonhong** [comment]
@emerick It's fixed. I think this fix should be uplifted together with `cr126` uplift.

**Comment by emerick** [comment]
@simonhong Thank you, I just cherry-picked this into the `cr126` uplift.

**Comment by kjozwiak** [comment]
The above requires `1.67.101` or higher for `1.67.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.67.101 Chromium: 126.0.6478.26 (Official Build) beta (64-bit)
-- | --
Revision | a561f4b53cdb831888e5cd702d2b8f9598c00f50
OS | Windows 11 Version 23H2 (Build 22631.3672)
```

Case 1: `Make Brave Search default`
<details>

1. Installed 1.67.101
2. launched Brave with `--enable-features=BraveSearchOmniboxBanner:banner_type/type_B cmd` args
3. opened `brave://settings/search` in a new tab
4. selected `Google` for `Normal Window` 
5. entered `Ireland` string in the URL bar
6. clicked `Try Brave Search` button
7. clicked `Make Brave search default` 

- Confirmed `Search promotion` is shown as per the screenshot in the description
- Confirmed Brave search results page is shown
- Confirmed `brave://settings/search` shows `Brave` for `Normal Window`

step 2 | step 4 | step 5-6 | step 7 | results
------- | ------- | ------ | ------ | --------
![image](https://github.com/brave/brave-browser/assets/98358127/5af47edb-1769-4f6c-ac45-ffce4952f269)|![image](https://github.com/brave/brave-browser/assets/98358127/8da2a4d6-5096-4356-821d-3f55f955b0e9)|![image](https://github.com/brave/brave-browser/assets/98358127/8bfd14fe-9da0-48c7-b3b9-6fde283f61a8)|![image](https://github.com/brave/brave-browser/assets/98358127/6a8baaf9-7f14-4909-baf6-517e3a067f8f)|![image](https://github.com/brave/brave-browser/assets/98358127/280b49d6-e779-432d-8e30-075d65a2c9b5)
</details>

Case 2: `Maybe later`
<details>

1. Installed 1.67.101
2. launched Brave with `--enable-features=BraveSearchOmniboxBanner:banner_type/type_B cmd` args
3. opened `brave://settings/search` in a new tab
4. selected `DuckDuckGo` for `Normal Window` 
5. entered `Amsterdam` string in the URL bar
6. clicked `Maybe later` button

- Confirmed `Search promotion` is shown as per the screenshot in the description
- Confirmed Search promotion modal is dismissed, and new tab page is shown
- Confirmed `brave://settings/search` still shows `DuckDuckGo` for `Normal Window`

step 2 | step 4 | step 5-6 | step 7 | brave://settings/search 
------- | ------- | ------ | ------ | --------
![image](https://github.com/brave/brave-browser/assets/98358127/3a3eb692-294f-4293-9fd9-88f40fe182e3)|![image](https://github.com/brave/brave-browser/assets/98358127/98e3f103-fd42-4f0a-bb79-9b6203c0e255)|![image](https://github.com/brave/brave-browser/assets/98358127/a1641692-cd94-4ab5-b48a-4ca89b26b198)|![image](https://github.com/brave/brave-browser/assets/98358127/a295b91e-22eb-41de-b266-ed52f91ca365)|![image](https://github.com/brave/brave-browser/assets/98358127/814c18c8-16a7-4f53-8689-e5ab0e4d42d4)

</details>
