### ISSUE TITLE
Evernote Web Clipper fails with error in Brave ≥ v1.66.110 macOS / Linux / Windows

### ISSUE THREAD

**Issue by bu11etpr00f** [brave/brave-browser#38576]
### Description

This issue has also been reported on the Brave Community Forum:
https://community.brave.com/t/evernote-web-clipper-fails-in-brave-v1-66-110-may-16-2024-windows-11/549284

Clipping a Webpage with the Evernote Web Clipper Extension fails with following Error:

`2024\5\26 13:55:32 LOG: Capturing content with article 
2024\5\26 13:55:33 LOG: HTMLSerializer: styles fetched and starting serialization 
2024\5\26 13:55:34 ERR: Could not clip the page Could not fetch 'blob:https://github.com/4b32d532-a6dc-40bd-9caa-19f985ba0389' error is 'TypeError: Failed to fetch' 
2024\5\26 13:55:34 ERR: Channel: Message 'tabClipper.clip' failed with error: UNK/UNK 
2024\5\26 13:55:34 ERR: Channel: Error in handleResponse UNK/UNK tabClipper clip`

### Steps to reproduce

1. Add Evernote Web Clipper Extension (https://chromewebstore.google.com/detail/evernote-web-clipper/pioclpoplcdbaefihamjohnefbikjilc) to Brave ≥ v1.66.110.
2. Go to a Webpage (like https://github.com/brave/brave-browser).
3. Click on the Evernote Web Clipper Extension to Clip the Webpage to Evernote.
4. Fails with Error

### Actual result

Fails with Error.

Evernote Log:

`2024\5\26 14:00:34 LOG: HTMLSerializer: styles fetched and starting serialization 
2024\5\26 14:00:36 ERR: Could not clip the page Could not fetch 'blob:https://github.com/6fda83b1-0f5d-4d52-9491-1cf511294ead' error is 'TypeError: Failed to fetch' 
2024\5\26 14:00:36 ERR: Channel: Message 'tabClipper.clip' failed with error: UNK/UNK 
2024\5\26 14:00:36 ERR: Channel: Error in handleResponse UNK/UNK tabClipper clip`

### Expected result

Should receive a response from the Evernote Web Clipper Extension that the Clipped Webpage was saved to Evernote successfully.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.66.113 Chromium: 125.0.6422.76 (Official Build) (x86_64)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by ryanbr** [comment]
Some investigation and regression testing;

```
Nightly v1.63.28 (Chromium 120.0.6099.71) good
Nightly v1.65.61 (Chromium 122.0.6261.111) good
Nightly v1.66.22 (Chromium 123.0.6312.58) good
Nightly v1.66.31 (Chromium 123.0.6312.58) good
Nightly v1.66.44 (Chromium 123.0.6312.86) good
Nightly v1.66.47 (Chromium 123.0.6312.86) good
Nightly v1.66.51 (Chromium 123.0.6312.86) good

Nightly v1.66.52 (Chromium 123.0.6312.86) bad
Nightly v1.66.54 (Chromium 123.0.6312.86) bad
```

The error is caused by; https://github.com/brave/brave-core/pull/22619 cc: @goodov

**Comment by kjozwiak** [comment]
The above requires `1.66.117` or higher for `1.66.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.66.118 Chromium: 125.0.6422.147 (Official Build) (64-bit)
-- | --
Revision | 07af53490e0a52336cfb99a376f87671be258049
OS | Windows 10 Version 22H2 (Build 19045.4412)
```
Reproduced the original issue using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/38576#issue-2317916233 with `1.66.110`

Using the same STR/Cases mentioned above, ensured that `Evernote` clipping was working as per the following:

**`1.66.110`** | **`1.66.118`**
---------------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/02c42eb9-e857-4021-a09e-7d3a9e743cec) | ![image](https://github.com/brave/brave-browser/assets/38657976/fba4486a-385b-45e1-a7af-c44e83bf0afc)
