### ISSUE TITLE
[CR 126] `Show all bookmarks` icon is inherited from CR 126

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#38589]
### Description

Found while testing https://github.com/brave/brave-browser/issues/37788
`Show all bookmarks` icon is inherited from CR 126

### Steps to reproduce

1. Clean profile `1.68.50`
2. Click on the hamburger menu
3. Click on `Bookmarks and lists`
4. `Show all bookmarks` icon is inherited from CR 126
 

### Actual result

`Show all bookmarks` icon is inherited from CR 126

![image](https://github.com/brave/brave-browser/assets/38657976/5cd39a7a-757c-48d9-8c61-b4e8b882e9ca)

### Expected result

`Show all bookmarks` settings should have brave branded icon

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.68.50 Chromium: 126.0.6478.17 (Official Build) nightly (64-bit)
-- | --
Revision | 72b186fbe4e288f53b0ee102f6ec66133b41a992
OS | Windows 10 Version 22H2 (Build 19045.4412)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @emerick @rebron

**Comment by GeetaSarvadnya** [comment]
cc: @aguscruiz

**Comment by GeetaSarvadnya** [comment]
The following settings should have the brave icons

The ones that are from new menu items:

Main menu:
- Translate
- Find and edit
- Find and share
![image](https://github.com/brave/brave-browser/assets/38657976/8f661a8a-0513-4872-b2b4-a2d4cd09c96d)

Passwords and autofill:
- Password manager
- Payment methods
- Addresses and more
![image](https://github.com/brave/brave-browser/assets/38657976/4186831d-69a0-4f62-8167-edfb2dc1a5dc)

Bookmarks:
- Show all bookmarks
![image](https://github.com/brave/brave-browser/assets/38657976/6f4e0075-b91c-4177-ab7e-8381f0859de9)

**Comment by GeetaSarvadnya** [comment]
Please refer https://bravesoftware.slack.com/archives/CU5UXM3EC/p1716812764653739?thread_ts=1716477777.596219&cid=CU5UXM3EC for more info

**Comment by simonhong** [comment]
checking.

**Comment by kjozwiak** [comment]
The above requires `1.67.108` or higher for `1.67.x` verification 👍
