### ISSUE TITLE
 `Exit` settings is hidden from the app menu on higher resolutions

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#38587]
### Description

Found while testing https://github.com/brave/brave-browser/issues/37788
`Exit` settings is missing from the hamburger menu

### Steps to reproduce

1. Clean profile `1.68.50`
2. Click on the hamburger menu
3. `Exit` settings is missing from the hamburger menu

### Actual result

`Exit` settings is missing from the hamburger menu

![image](https://github.com/brave/brave-browser/assets/38657976/9a488621-69b7-4e68-943e-7f4f22e91483)

### Expected result

`Exit` settings should be present in the hamburger menu

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.68.50 Chromium: 126.0.6478.17 (Official Build) nightly (64-bit)
-- | --
Revision | 72b186fbe4e288f53b0ee102f6ec66133b41a992
OS | Windows 10 Version 22H2 (Build 19045.4412)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @rebron @brave/qa-team @emerick

**Comment by emerick** [comment]
I can't repro this with nightly on Windows 11. According to the upstream code, the "Exit" menu should show on Windows and be hidden on Mac which is what I'm seeing.

**Comment by stephendonner** [comment]
I just installed 

```
Brave | 1.68.58 Chromium: 126.0.6478.17 (Official Build) nightly (64-bit)
-- | --
Revision | ec786b623be34c911487c24144c0650bdd057fc1
OS | Windows 10 Version 22H2 (Build 19045.4412)
```

The `Exit` option is there for me 👍 

![image](https://github.com/brave/brave-browser/assets/387249/387ad21b-6844-4b29-805f-11036f26308a)

**Comment by GeetaSarvadnya** [comment]
I have two windows 10 x64 machines. In one machine the `Exit` button is shown and in other machine the `Exit` option isn't shown. Based on the system resolution, the exit option is shown.

**Machine 1 - Windows 10 x64**

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/a959550c-9f09-47ea-ba48-9c4e90bc6905) | ![image](https://github.com/brave/brave-browser/assets/38657976/6ba3f935-4bdb-4cb0-ba70-af2d437719c1)


**Machine 2 - Windows 10 x64**

Example | Example
----------|---------

**Comment by GeetaSarvadnya** [comment]
cc: @emerick @rebron https://github.com/brave/brave-browser/issues/38587#issuecomment-2138679767

**Comment by emerick** [comment]
Oh, is that because at the increased resolution the menu becomes scrollable (i.e., the Exit option scrolled off the end and maybe the scrollbar is not visible?)

**Comment by GeetaSarvadnya** [comment]
@emerick 
![exit menu issue](https://github.com/brave/brave-browser/assets/38657976/7c6d2892-b7d1-473b-a91b-a0a75d8d9701)

**Comment by stephendonner** [comment]
> Oh, is that because at the increased resolution the menu becomes scrollable (i.e., the Exit option scrolled off the end and maybe the scrollbar is not visible?) That's the only conceivable option I can imagine, because the menu item "should" physically be there.

@emerick this is how it is for me, yes:
* invisible scrollbar
* `X Exit` below `Settings`

**Comment by stephendonner** [comment]
> > Oh, is that because at the increased resolution the menu becomes scrollable (i.e., the Exit option scrolled off the end and maybe the scrollbar is not visible?) That's the only conceivable option I can imagine, because the menu item "should" physically be there.
> 
> @emerick this is how it is for me, yes:
> 
> * invisible scrollbar
> * `X Exit` below `Settings`


https://github.com/brave/brave-browser/assets/387249/8b88215c-9550-48ff-b2a7-96989c766302

**Comment by stephendonner** [comment]
And Chrome has this little expand arrow

![image](https://github.com/brave/brave-browser/assets/387249/2f87462e-6b78-4e1f-878b-94abd3a71446)

**Comment by GeetaSarvadnya** [comment]
Chrome Vs Brave
![chrome exit Vs Brave exit](https://github.com/brave/brave-browser/assets/38657976/bffb6a06-3098-47b7-8b88-b42e40b6f004)

**Comment by simonhong** [comment]
working on this.

**Comment by GeetaSarvadnya** [comment]
@simonhong @emerick: The issue is fixed and working fine now. I could see the `Exit` settings menu with default screen resolution 150%. Looks like removal `Translate` settings would have fixed the issue? not sure. 
![Exit issue fixed](https://github.com/brave/brave-browser/assets/38657976/490dc9ff-c769-47d8-b407-432d6cf95526)

**Comment by rebron** [comment]
I think with Upgrade notifications and adding IPFS users may still run into this issue. So we'll still need the scroll.

**Comment by simonhong** [comment]
Hmm, I couldn't repro. I can see scroll arrow like below. dev build, nightly all same on my Win11 machine.
![image](https://github.com/brave/brave-browser/assets/6786187/d90b7bd0-a78a-43b8-b5f4-400860e28443)

**Comment by emerick** [comment]
Did you try with increased screen resolution @simonhong?

**Comment by simonhong** [comment]
> Did you try with increased screen resolution @simonhong?

Yes, above one was with 200%

**Comment by rebron** [comment]
This might be Windows 10 specific.

**Comment by rebron** [comment]
I can't reproduce this either. I'm going to go ahead and close per https://github.com/brave/brave-browser/issues/38587#issuecomment-2162096815. In Nightly, 1.69.15, with the new sidebar settings moved to the top level, I'm getting a scroll bar on Windows 10. On Beta 1.68.85 and in RC 1.67.113, I'm still seeing Exit so it's not a problem there either. Expanding to 175% I'm able to scroll up and down.

Windows 10 with recommended 150% and 1920x1080 display resolution.
