### ISSUE TITLE
Install Omaha v1.3.361.151 for new users

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#38597]
### Description

Our automatic update mechanism on Windows is implemented via a fork of Google's "Omaha" technology. Google have released several new versions. We want to pull in those improvements by releasing a new version of our copy of Omaha with the new changes.

Omaha runs as a separate application on users' systems. It gets installed when the user first installs Brave. The goal of this issue is to make Brave's Windows installers install our new version 1.3.361.151 of Omaha. There are no functional changes in the new version of the updater.

After the implementation for this issue has hit Release, we should also install the new Omaha version for existing users. This is captured by #38602.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.68.86 Chromium: 126.0.6478.56 (Official Build) beta (64-bit)
-- | --
Revision | b4eadb4942277a3eb455fc7c3c8569185bd745af
OS | Windows 11 Version 23H2 (Build 22631.3737)
```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.68.87 Chromium: 126.0.6478.56 (Official Build) beta (arm64)
-- | --
Revision | 786b6b66ebe624e5c4ef760b3fe3047ea61932de
OS | Windows 11 Version 23H2 (Build 22631.3737)
```

- Verified the test plan from https://github.com/brave/brave-core/pull/23842#issue-2318994083

### Windows 11 arm64

#### Test Case 1: Verify Brave's various Windows installers on a new install.- Pending

<details>
<summary>Case 1: Verify correct Omaha updater version installed with Standalone installer - PASSED</summary>

1. Uninstalled all the brave versions (Release, Beta and Nightly) via [Brave Manager 
](https://github.com/brave/brave-manager)
2. downloaded and installed `BraveBrowserStandaloneBetaSetup.exe` installer for `1.68.87` - (https://github.com/brave/brave-browser/releases/download/v1.68.87/BraveBrowserStandaloneBetaSetupArm64.exe)
3. confirmed 1.68.87 installed with admin privileges successfully  
4. confirmed that the new Omaha updater `1.3.361.151` is shown in the registry path as below as expected 
    - `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\Update`
5. confirmed new Omaha updater version `1.3.361.151` is shown in `C:\Program Files (x86)\BraveSoftware\Update`
6. Uninstall the `1.68.87` via control panel and remove the profile folder from the `%LOCALAPPDATA%\BraveSoftware`
7. Install the `1.68.85` and confirmed that the brave installed successfully
8. open `brave://settings/help` and wait for the update and click on the `Relaunch` 
9. confirmed that brave is upgraded to latest public version - `1.68.87`

step 3 | step 4 | step 5 | step 7 | step 8 | step 9
---- | ---- | ----- | ---- | ---- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/567769e9-dbf4-4d39-81be-4bb46b1a72eb)|![image](https://github.com/brave/brave-browser/assets/98358127/fd44f2b1-72c4-4e7d-aad5-2f84e86ba0d4)|![image](https://github.com/brave/brave-browser/assets/98358127/c1163121-8810-47ee-9a37-8ba74c0bd513)|![image](https://github.com/brave/brave-browser/assets/98358127/af3e9e2d-3330-4095-a4d2-07c09eb27cf2)|![image](https://github.com/brave/brave-browser/assets/98358127/a1222ef8-c6ad-4e5f-aef0-afc0adb17b4d)|![image](https://github.com/brave/brave-browser/assets/98358127/e88f5117-fd3a-4d8a-bcef-445883018f85)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.68.92 Chromium: 126.0.6478.71 (Official Build) beta (64-bit)
-- | --
Revision | 393b9968e233540a48f04d74bc4601a05d3a0169
OS | Windows 10 Version 22H2 (Build 19045.4529)
```

**Comment by MadhaviSeelam** [comment]
Not adding `QA Pass-Win 64` label yet as the Win 10 x86` verification is pending. 
cc: @LaurenWags @kjozwiak

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.68.99 Chromium: 126.0.6478.126 (Official Build) beta (32-bit) 
Revision	8ccc3a46e66d71dfd21506e1ccb42e08c7d33557
OS	Windows 10 Version 22H2 (Build 19045.4170)
```
