### ISSUE TITLE
Log flooding in GLSurfacePresentationHelper

### ISSUE THREAD

**Issue by RiFi2k** [brave/brave-browser#3859]
On Wayland Linux w/ hardware acceleration on this gets throw constantly.
```
ERROR:gl_surface_presentation_helper.cc(237)] GetVSyncParametersIfAvailable() failed!
```
There is an issue and a fix upstream. Save my logs! Just kidding, thanks a ton for this project its awesome!

https://bugs.chromium.org/p/chromium/issues/detail?id=879929

https://chromium.googlesource.com/chromium/src/+/1fb4edaf534c278a0b7a3150efff8e712c1efe91%5E%21/#F0

**Comment by bsclifton** [comment]
This should be resolved now, per the issue shared. @RiFi2k are you able to retest?
