### ISSUE TITLE
CR 126 - Install Password Manager icon and the modal popup buttons are inherited from chrome

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#38599]
### Description

Found while testing https://github.com/brave/brave-browser/issues/37788

Install Password Manager icon and the modal popup buttons are inherited from chrome

### Steps to reproduce

1. Clean profile `1.68.50` CR 126
2. Click on `Autofill and passwords` settings via left navigation menu bar
3. Click on `Password Manager`
4. `brave://password-manager/passwords` page opens up
5. `Install Password Manager` icon inherited from chrome
6. Click on `Install Password Manager` icon displays `Install app?` popup modal at the center of the URL bar
7. `Install` and `Cancel` buttons are inherited from chrome
8. There is no `x` button to close the popup modal

### Actual result

1. `Install Password Manager` icon inherited from chrome
2. `Install` and `Cancel` buttons are inherited from chrome
3. There is no `x` button to close the popup modal
4. Click on `Install Password Manager` icon displays `Install app?` popup modal at the center of the URL bar

![image](https://github.com/brave/brave-browser/assets/38657976/9b283a56-7d4b-4dff-bfc8-052c392fe071)

### Expected result

The `Install Password Manager` icon, popup modal and buttons should be same as below:

![image](https://github.com/brave/brave-browser/assets/38657976/f73a082e-bc20-4ef2-9508-1b0250331326)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.68.50 Chromium: 126.0.6478.17 (Official Build) nightly (64-bit)
-- | --
Revision | 72b186fbe4e288f53b0ee102f6ec66133b41a992
OS | Windows 10 Version 22H2 (Build 19045.4412)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @rebron @brave/qa-team @emerick

**Comment by aguscruiz** [comment]
The actions in the dialog should always be:

- Primary action on the right, using filled button
- Dismissive action (in this case cancel) in plain-faint buttons. 

![image](https://github.com/brave/brave-browser/assets/15734630/0f1d06f0-fbae-4c4b-b142-28dc05474449)

**Comment by GeetaSarvadnya** [comment]
same issue on the page below:
![image](https://github.com/brave/brave-browser/assets/38657976/fba1f37f-231a-4e55-b298-fa5a6036359c)

**Comment by aguscruiz** [comment]
Yeah, we need to make this pattern the default. I'll create an issue for defining that

**Comment by kjozwiak** [comment]
The above requires `1.67.101` or higher for `1.67.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
@emerick: I can see the old `Install Password Manager` popup modal, but icon in the URL bar is still inherited from chrome. 
![image](https://github.com/brave/brave-browser/assets/38657976/25c6387a-a7f7-455d-bda1-fe687ebf3eb1)

**Comment by emerick** [comment]
@GeetaSarvadnya Sorry, I missed the icon when I did this. Working on it now.

**Comment by GeetaSarvadnya** [comment]
@emerick: I don't have any issues with new icon if @rebron and @aguscruiz are ok with it.

**Comment by aguscruiz** [comment]
I'm ok with the download icon, makes it clear. But let's use our version of it, in Nala, called `pwa-install`

**Comment by MadhaviSeelam** [comment]
@emerick looks like Nala icon of `pwa-install` is not implemented or am I looking at the wrong icon?

1.67.107 Chromium: 126.0.6478.26 | Nala icon
------------ | -------------
![image](https://github.com/brave/brave-browser/assets/98358127/29864d4a-fff2-4937-835d-b202d0bc1a6e)|![image](https://github.com/brave/brave-browser/assets/98358127/889f7c2e-c73d-4d2c-b6ec-5cbae76341d9)

**Comment by emerick** [comment]
@MadhaviSeelam No, it's not there yet. Will get it in tomorrow, sorry for the delay.

**Comment by MadhaviSeelam** [comment]
> @MadhaviSeelam No, it's not there yet. Will get it in tomorrow, sorry for the delay.



> @MadhaviSeelam No, it's not there yet. Will get it in tomorrow, sorry for the delay.

@emerick my bad.. I was looking at the earlier comment and went ahead with it.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.67.108 Chromium: 126.0.6478.40 (Official Build) beta (x86_64)
-- | --
Revision | a286dc9f61f7d70fbf0157fcf3d924b00297d450
OS | macOS Version 13.6.7 (Build 22G720)
```
