### ISSUE TITLE
CR 126 - `Search engine`, `Downloads` and `System` settings icons are inherited from Chrome

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#38595]
### Description

Found while testing https://github.com/brave/brave-browser/issues/37788

`Search engine`, `Downloads` and `System` settings icons are inherited from Chrome

### Steps to reproduce

1. Clean profile `1.68.50`
2. Open brave://settings/

### Actual result

`Search engine`, `Downloads` and `System` settings icons are inherited from Chrome

![image](https://github.com/brave/brave-browser/assets/38657976/e4b34d16-1ebd-48e7-9215-ea827a251182)

### Expected result

`Search engine`, `Downloads` and `System` settings should have brave branded icons
![image](https://github.com/brave/brave-browser/assets/38657976/192a954b-b346-44af-9d3d-052d321cc5f2)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.68.50 Chromium: 126.0.6478.17 (Official Build) nightly (64-bit)
-- | --
Revision | 72b186fbe4e288f53b0ee102f6ec66133b41a992
OS | Windows 10 Version 22H2 (Build 19045.4412)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @rebron @emerick @brave/qa-team

**Comment by GeetaSarvadnya** [comment]
cc: @aguscruiz

**Comment by kjozwiak** [comment]
The above requires `1.67.101` or higher for `1.67.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.67.101 Chromium: 126.0.6478.26 (Official Build) beta (64-bit)
-- | --
Revision | a561f4b53cdb831888e5cd702d2b8f9598c00f50
OS | Windows 10 Version 22H2 (Build 19045.4412)
```
- Ensured that `Search engine`, `Download` and `System` settings have brave branded icons
![image](https://github.com/brave/brave-browser/assets/38657976/c42ec9c8-6247-40fe-a755-0f0797b7513c)
