### ISSUE TITLE
Turn on crash reporting by default on beta

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#3861]
Currently it's off on beta by default.

STR:
1. Start beta browser with clean profile
2. Check crash reporting is enabled in settings page

**Comment by btlechowski** [comment]
Changed the milestone to `0.64.x`, because the PRs are not uplifted yet.
https://github.com/brave/brave-core/pull/2064
https://github.com/brave/brave-core/pull/2062

Please, change the milestone after changes are uplifted.

**Comment by simonhong** [comment]
Changed milestone to 0.63.x. it is merged into it.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.28 Chromium: 73.0.3683.75 (Official Build) beta(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

- Verified STR from description
