### ISSUE TITLE
scroll not working properly 

### ISSUE THREAD

**Issue by ananti15mulay** [brave/brave-browser#38611]
### Description

when a webpage is opened and is tried to be scrolled down using two fingers on touchpad then the cursor moves directly to the bottom of the page and does not provide scrolling functionality causing inconvenience to read

### Steps to reproduce

1. open a webpage
2. scroll down by sliding two fingers on touch pad
3. 

### Actual result

on scrolling it jumps directly to the end of the webpage, not faciliating the scrolling feature seamlessly 

### Expected result

the scrolling can be adjusted according to users finger movements on the touchpad as facilitated by chrome and other browsers

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

0.25.2

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kmr-ankitt** [comment]
Which OS you are using currently? In linux, try to change Brave flags to wayland from x11.
Brave flags are at : brave://flags/

![image](https://github.com/brave/brave-browser/assets/90329779/968ffeff-f276-4434-894b-08bcb1f4b0c5)
