### ISSUE TITLE
Brave crashes if CarPlay becomes the main window

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#38612]
### Description

This was a bug caused by Chromium 125 specifically https://source.chromium.org/chromium/chromium/src/+/main:ui/display/ios/screen_ios.mm;l=120

This does strict conversions of all scenes to `UIWindowScene` which will not be the case when there is a CarPlay scene also connected

### Steps to reproduce

1. Connect phone to CarPlay
2. Open Brave on the CarPlay device _without_ opening it on your phone

### Actual result

Crashes

### Expected result

Should just open the CarPlay window

### Reproduces how often

Easily reproduced

### Brave version

Chromium 125 and up which I believe is 1.65+

### Device/iOS version

iPhone only since its CarPlay specific, any OS version

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.68.117`

- Ensured Brave does not crash when opening Brave on CarPlay device without opening on Phone. 
- Ensured Playlist controls are working on the CarPlay device.
- Ensured Playlist gestures in Brave app are working with CarPlay. 

Example | Example | Example
-|-|-
![Screenshot 2024-07-12 at 5 08 07 PM](https://github.com/user-attachments/assets/ed646625-a03c-41b1-95f4-78580d0302bf) | ![Screenshot 2024-07-12 at 5 12 51 PM](https://github.com/user-attachments/assets/f601ae24-d25b-4208-bed6-1d56f412bf13) | ![Screenshot 2024-07-12 at 5 13 04 PM](https://github.com/user-attachments/assets/88487158-3595-4d70-9c4c-5746e40aea10)
