### ISSUE TITLE
A url with two consecutive dots result in an error page, should show a query

### ISSUE THREAD

**Issue by iccub** [brave/brave-browser#38620]
### Description

-

### Steps to reproduce

1. enter tes..t.com into the url bar

### Actual result

Shows error page

### Expected result

Should submit a search query, other browsers do it like this

### Reproduces how often

Easily reproduced

### Brave version

-

### Device/iOS version

-

### Affected browser versions

- [X] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by anthonypkeane** [comment]
A nice to have but not a very high priority given other issues right now.

Aloha seems to have the best UX here, they take the user to a search result when a URL like tes..t.com is entered. 

![DDG](https://github.com/brave/brave-browser/assets/7606853/4a4afaa1-9f43-4c2c-a9d7-7bc77ab24b22)
![Firefox](https://github.com/brave/brave-browser/assets/7606853/2f0dda07-7798-4836-b2d0-a1a2f43469e6)
![Safari](https://github.com/brave/brave-browser/assets/7606853/cc95c7e5-27d1-4bc6-ae9c-e2bde3cd5660)
![Aloha](https://github.com/brave/brave-browser/assets/7606853/b195e45b-adf2-42e6-aec0-ee813a5bdbca)

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7
Brave build: 1.70 (115)
BraveCore: 1.70.115 (129.0.6668.59)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Open `NTP` > Go to `test..t.com` > *Verify*
3. Open another `NTP` > Go to `google..com` > *Verify*

**ACTUAL RESULTS:**
- Verified that search results are shown for search query with 2 consecutive dots
- Verified that error page is not shown
- Verified the same in `Standard` and `Private` tabs

---------------------------

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/a0df1e75-ccf2-49bf-a7ee-3ce374dbc6d7) | ![2](https://github.com/user-attachments/assets/a8925c38-eb12-4354-86a7-b77bb1e9116b) | ![3](https://github.com/user-attachments/assets/48433386-d4c4-4a13-9895-6af186a3d022) | ![4](https://github.com/user-attachments/assets/1e381cb6-f379-41c0-b4b9-4dfeb969484e) | ![5](https://github.com/user-attachments/assets/1f746c9e-050a-4dfa-b217-e4587ad718ca) |
| ![1](https://github.com/user-attachments/assets/51f3e13e-5088-415b-87a0-c30941ff967d) | ![2](https://github.com/user-attachments/assets/f62809bc-b1aa-4931-8f4c-b6a4576c8fce) | ![3](https://github.com/user-attachments/assets/8cde1afc-4332-4407-9138-ef13a4fbdd91) | ![4](https://github.com/user-attachments/assets/55da9d2d-92e0-4210-8cb5-bdb97b761d94) | ![5](https://github.com/user-attachments/assets/c421c427-956e-4243-b98a-f13ca9c91cb4) |
