### ISSUE TITLE
[Android]New tab is added automatically when launching the app

### ISSUE THREAD

**Issue by A-t-s-u-s-h-i** [brave/brave-browser#38635]
### Description

We have several feedback says Brave Android adds a new tab automatically when launching the app.

This is the community thread for the issue.

https://community.brave.com/t/brave-opens-new-tab-on-startup/549900

> Whenever I open Brave on Android, there’s a high chance that it opens up to a new tab automatically.

And the comments below are from PlayStore review.

> A new tab will now open on startup. It's inconvenient, so I'd like to be able to skip it in the settings.

> every time I start this app, a new tab is created, and I'm in a very troubled situation with multiple tabs.If it's a bug, please fix it as soon as possible.

### Steps to reproduce

1. Closing and re-launching Brave

### Actual result

A new tab is added automatically.

### Expected result

Only existed tabs should be in the tab list.

### Reproduces how often

Intermittent issue

### Brave version

1.66

### Device

Android 13; Build/TP1A.220624.014 (Galaxy S20 Ultra)
Android 14; Build/UP1A.231005.007 (Galaxy Z Fold 4)

### Channel information

- [X] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by ZdrytchX** [comment]
Can be reliably triggered if day/night mode is set to auto. Causes app to restart and open into a new tab. Other factors may also trigger it. Did not have this issue a few months ago.

Brave 1.67.119, Chromium 126.0.6478.114
Android 12; Build/SP1A.210812.003

**Comment by kjozwiak** [comment]
The above requires `1.67.131` or higher for `1.67.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.67.134 Chromium: 126.0.6478.186 (Official Build) (64-bit) 
Revision	e27c9744a0ed98bfa60e287af7e5eaffde15bd57
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that closing and re-launching Brave does not add a new tab. 
- Ensured that closing Brave and changing light/dark theme in device settings manually and re-launching Brave again does not add a new tab.

Before | After
-|-
![Screenshot 2024-07-17 at 12 26 00 PM](https://github.com/user-attachments/assets/0ae2a175-d768-40bf-a038-1f2789eb55d7) | ![Screenshot 2024-07-17 at 12 28 10 PM](https://github.com/user-attachments/assets/a403252a-78d5-4689-b330-f6b0a61b31c3)
