### ISSUE TITLE
[CR 126] In brave://history the text `Your browsing history appears here` is positioned up same as chrome 126 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#38638]
### Description

Found while testing https://github.com/brave/brave-browser/issues/37788

In brave://history the text `Your browsing history appears here` is positioned up same as chrome 126 

### Steps to reproduce

1. Clean profile 1.68.50 CR 126
2. Open brave://history
3. The text `Your browsing history appears here` is positioned up same as chrome 126 
4. The icons for `Brave history`, `Tabs from other devices` and `Delete browsing data` icons are inherited from Chrome

### Actual result

- In brave://history the text `Your browsing history appears here` is positioned up same as chrome 126 
- The icons for `Brave history`, `Tabs from other devices` and `Delete browsing data` icons are inherited from Chrome

![image](https://github.com/brave/brave-browser/assets/38657976/4d89a5e7-3571-442c-a29a-633387df65c9)

### Expected result

The text should be same as below also the icons should be brave branded

![image](https://github.com/brave/brave-browser/assets/38657976/0663fa05-bc44-4e7b-ab23-38304e7301bf)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.68.52 Chromium: 126.0.6478.17 (Official Build) nightly (64-bit)
-- | --
Revision | 50cc18531580b50749c55b81575e2f9cf3f054f2
OS | Windows 10 Version 22H2 (Build 19045.4412)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @emerick @aguscruiz @rebron

**Comment by kmr-ankitt** [comment]
can i work over this?

**Comment by rebron** [comment]
@kmr-ankitt Maybe, but we need a quick fix for this one. There are some good ones here to try: https://github.com/brave/brave-browser/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by rebron** [comment]
Let's target this one for next week's 1.67.x minor release.

**Comment by kjozwiak** [comment]
The above requires `1.67.115` or higher for `1.67.x` verification 👍
