### ISSUE TITLE
Build out Swap and Bridge Route Selection

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#38648]
### Platforms

Linux, macOS, Windows

### Description

We need to enable users to select available `routes` when initiating a `Bridge` or `Swap` transaction.

UI to be built out can be found in our `Figma` designs here 

https://www.figma.com/design/26xCR66ZscSyVpTKrt85Hn/Transactions?node-id=601-134140&t=ZhJJwbyG9qKXTRAv-0

![Screenshot 9](https://github.com/brave/brave-browser/assets/40611140/af7199dd-bd32-4260-b209-4c7e2ccb4787)

**Comment by LaurenWags** [comment]
@Douglashdaniel please add the appropriate platform label(s):
- `OS/Desktop` and/or `OS/Android` and/or `OS/iOS`

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.101 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | dc28ab38d07e9fa668801884c0c55f669ce538eb
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from [brave/brave-core#24854](https://github.com/brave/brave-core/pull/24854)
- Verified Swap and Bridge has route selection
- Verified updating the provider automatically updates the quotes accordingly

https://github.com/user-attachments/assets/332da249-b03f-4b7d-baf2-506b24e3aca9

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.70.107 x64 Beta build
- Verified steps from [brave/brave-core#24854](https://github.com/brave/brave-core/pull/24854)
- Verified Swap and Bridge has route selection
- Verified updating the provider automatically updates the quotes accordingly

https://github.com/user-attachments/assets/ff591fd4-dad6-46c2-ab52-7beb1a7010b7
