### ISSUE TITLE
No it can't, stop asking.

### ISSUE THREAD

**Issue by AnonymousRonin** [brave/brave-browser#38643]
### Description

No, you can't disable the urlbar search only.  Brave generates revenue by selling the search results from it's browser, how else you think they generate revenue.  Their privacy features are mainly frontend to satisfy the privacy weirdos.  Their backend is no different than anyone else's. But because of the frontend config they don't and won't allow search from the big search box that eveyone likes.  A browser can be as private as you want it to be, any of them.  Brave is just chromium, use headless chromium and config it yourself.  Or try Librewolf which is far more secure or Floorp which is a firefox based browser but layed out and packed with features similar to chrome.  Remember, at the end of the day you're using chrome, it's never going to take into account your privacy first.  

### Steps to reproduce

1. No
2. 
3. 

### Actual result

Same as always

### Expected result

The expected result

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

All

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [X] in the latest version of Chrome

### Miscellaneous information

Stop believing Brave is some privacy centric open sourced company.  If they were you wouldn't be here, you'd be able to config your browser however you wanted.

**Comment by rebron** [comment]
Closing invalid. Believe whatever you want to believe: https://support.brave.com/hc/en-us/articles/10742158329613-What-does-Brave-remove-from-the-Chromium-engine

**Comment by AnonymousRonin** [comment]
Invalid?  Then prove me wrong.  Because our backend analysis says otherwise.  You could just prove me wrong by allowing the feature with instructions on how to enable it.  But you won't.

**Comment by AnonymousRonin** [comment]
> Closing invalid. Believe whatever you want to believe: https://support.brave.com/hc/en-us/articles/10742158329613-What-does-Brave-remove-from-the-Chromium-engine

Yeah, we've seen that.  All it says it you don't route various bits of info to google.  What it doesn't say is where you do route info, which info and by what mechanism.  What's funny is that this has been investigated multiple times by credible sources who all say the same thing.
