### ISSUE TITLE
Backup wallet from menu loads `brave://wallet/crypto/backup-wallet` with Settings tab bar instead of the new onboarding flow

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#38640]
### Description

Backup wallet from menu loads `brave://wallet/crypto/backup-wallet` with Settings tab bar instead of the new onboarding flow

### Steps to reproduce

1. Create a new wallet or restore a wallet from seed
2. Open Portfolio menu and click on `Backup now`
3. Loads `brave://wallet/crypto/backup-wallet` 
4. Try to click on settings tab strip doesn't work

### Actual result

https://github.com/brave/brave-browser/assets/17010094/12c51bca-b497-40d4-9c5b-4ab294206d57

### Expected result

Should navigate to `brave://wallet/crypto/onboarding/new/explain-recovery-phrase` instead of `brave://wallet/crypto/backup-wallet`

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

<html>
<body>

Brave | 1.67.98 Chromium: 125.0.6422.112 (Official Build) beta (64-bit)
-- | --
Revision | 9434daa5e8d2aceabb9cce574ab39429f2923b9b
OS | Windows 11 Version 23H2 (Build 22631.3593)

</body>
</html>

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @muliswilliam

**Comment by kjozwiak** [comment]
The above requires `1.67.105` or higher for `1.67.x` verification 👍

**Comment by srirambv** [comment]
@muliswilliam something's broken on 1.67.105. Backup screen doesn't work and console logs some errors

https://github.com/brave/brave-browser/assets/17010094/bbfa0136-03e3-4cb5-898e-e40cd7fcd777

**Comment by srirambv** [comment]
Follow up issue https://github.com/brave/brave-browser/issues/38816

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/38816#issuecomment-2152201453
