### ISSUE TITLE
[CR 126] Update brave notification text is not visible and update brave icon is changed

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#38645]
### Description

Found while testing https://github.com/brave/brave-browser/issues/37788
Update brave notification text is not visible and update brave icon is changed

### Steps to reproduce

1. Clean profile `1.68.50` CR 126
2. Open brave://settings/help
3. Wait for an update don't click on `Relaunch`
4. Update brave notification is shown
5. Update brave notification text is not visible and update brave icon is changed

### Actual result

Update brave notification text is not visible and update brave icon is changed

![image](https://github.com/brave/brave-browser/assets/38657976/78642988-bebf-40cf-a69f-8d453ec85552)

### Expected result

Install `1.68.45 - CR 125`, the build before CR126 nightly build, the update brave notification is shown as expected
![image (5)](https://github.com/brave/brave-browser/assets/38657976/7c9a9192-b7a7-4075-bd41-79544f867fe0)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.68.50 Chromium: 126.0.6478.17 (Official Build) nightly (64-bit)
-- | --
Revision | 72b186fbe4e288f53b0ee102f6ec66133b41a992
OS | Windows 10 Version 22H2 (Build 19045.4412)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @emerick @rebron @mherrmann

**Comment by kjozwiak** [comment]
Just adding some more context/data. Seeing the same issue in `Win 11 x64` using the following build(s):

```
Brave | 1.68.58 Chromium: 126.0.6478.17 (Official Build) nightly (64-bit)
-- | --
Revision | ec786b623be34c911487c24144c0650bdd057fc1
OS | Windows 11 Version 23H2 (Build 22631.3672)
```

![image](https://github.com/brave/brave-browser/assets/2602313/44bc9bb3-36dc-4757-b0ca-aa4215761ca4)

**Comment by emerick** [comment]
@simonhong Will probably leave this one in your hands if that's OK.

**Comment by simonhong** [comment]
working on this.

**Comment by bsclifton** [comment]
Ran into this today - nice work @simonhong 😄 And thanks for logging @GeetaSarvadnya

**Comment by kjozwiak** [comment]
The above requires `1.67.106` or higher for `1.67.x` verification 👍 Just a quick note, created https://github.com/brave/brave-browser/issues/38810 in case we want to improve the highlight/selection UX/UI. However, Chrome looks the same so we might just want to leave it. @simonhong provided the following image re: Chrome having the same UI/UX experience:

![image](https://github.com/brave/brave-browser/assets/2602313/7eb33948-bcc6-4a71-96cf-156684f7c925)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.67.107 Chromium: 126.0.6478.26 (Official Build) beta (arm64) 
Revision	2831369c7540d93e98f38d9b463f6762430a7982
OS	macOS Version 14.5 (Build 23F79)
```

Installed above version, waiting for update to `1.67.108` to show on hamburger menu.

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.67.107 Chromium: 126.0.6478.26 (Official Build) beta (x86_64)
-- | --
Revision | 2831369c7540d93e98f38d9b463f6762430a7982
OS | macOS Version 13.6.7 (Build 22G720)
```

Reproduced the issue using `1.67.105`:

Dark | Light
--- | ---
<img width="1193" alt="Screenshot 2024-06-07 at 8 56 09 AM" src="https://github.com/brave/brave-browser/assets/28145373/9d3b7ce5-e95b-45e9-a79e-ef31fbb47901"> | <img width="1195" alt="Screenshot 2024-06-07 at 9 02 32 AM" src="https://github.com/brave/brave-browser/assets/28145373/9a9c6978-2b1e-44a4-9d64-1e9261ebdb32">

Using `1.67.107`:
- Launched via terminal with `--args --enable-logging=stderr --simulate-critical-update`
- Confirmed no red/orange coloring on menu item (hamburger menu with "Update" text is red as expected)
- Confirmed expected icon on hamburger menu item for "Relaunch to Update Brave"

Dark | Light
--- | ---
<img width="1181" alt="Screenshot 2024-06-07 at 8 54 37 AM" src="https://github.com/brave/brave-browser/assets/28145373/024e8297-6b2a-4c30-978f-a2c46c41831b"> | <img width="1194" alt="Screenshot 2024-06-07 at 9 04 45 AM" src="https://github.com/brave/brave-browser/assets/28145373/faf02b27-2973-4cf3-8516-c5fbdab9fc58">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.67.107 Chromium: 126.0.6478.26 (Official Build) beta (64-bit)
-- | --
Revision | 2831369c7540d93e98f38d9b463f6762430a7982
OS | Windows 11 Version 23H2 (Build 22631.3672)
```
Reproduced the issue using `1.67.105`:

Light | Dark
---- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/e878ce9f-c445-4ec9-897c-a693aa8349c7)|![image](https://github.com/brave/brave-browser/assets/98358127/9552decc-ff30-4a31-9af8-f54d600e97f9)

Using `1.67.107`:

- Launched via terminal with `--enable-logging=stderr --simulate-critical-upgrade`
- Confirmed no red/orange coloring on menu item  
- Confirmed expected icon on hamburger menu item for "Relaunch to Update Brave"

Light | Dark
---- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/dfcacaf0-e5f2-485a-8829-d87f5078ae13)|![image](https://github.com/brave/brave-browser/assets/98358127/856677e6-252d-4598-b5dd-b1aba27585a6)
