### ISSUE TITLE
Unable to download passwords on local storage

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#38655]
### Description

Starting with Brave `1.65.110` which has `Cr124` a user not able to download saved passwords on local storage, instead Brave is offering only to share the `CSV` file.

### Steps to reproduce

1. Launch Brave `1.65.110` or newer
2. Go to any website, for example, www.feedly.com and sign in with your account
3. Save the password in Brave when a pop-up is shown
4. Open the settings > Password Manager
5. Three-dot menu > Export passwords...
6. Authenticate with PIN/Password/Biometric
7. Export passwords... > *Observe*

### Actual result

The user is not able to save a `CSV` file with saved passwords on the local storage.

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/6c1b36e9-8069-4738-adab-1b7c92752dd2) | ![2](https://github.com/brave/brave-browser/assets/128532965/7f655fa6-4b86-4c24-bf32-1bad5b885bcc) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/8c685da6-8cf9-4a7c-8f4b-c5b903c27ad0) | ![2](https://github.com/brave/brave-browser/assets/128532965/120d7475-da55-40c4-b0a9-b151f6716d23) |

### Expected result

The user must be able to save a `CSV` file with saved passwords on the local storage.

https://github.com/brave/brave-browser/assets/128532965/af9d4f05-ce11-42b7-a602-20281ff9e29c

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.66.115
Chromium: 125.0.6422.112 (Official Build) (64-bit) 

### Device

- Brand/model: Pixel 6
- Android version: oriole-user 14 AP1A.240505.004 release-keys

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by AlexeyBarabash** [comment]
It happens at [ExportFlow.sendExportIntent](https://source.chromium.org/chromium/chromium/src/+/main:chrome/android/java/src/org/chromium/chrome/browser/password_manager/settings/ExportFlow.java;l=541-548;drc=c0265133106c7647e90f9aaa4377d28190b1a6a9;bpv=0;bpt=1)
```
        // With UNIFIED_PASSWORD_MANAGER_LOCAL_PWD_MIGRATION_WARNING feature on, offer to save the
        // exported passwords on disk. Otherwise offer to share the passwords with a chosen Android
        // app.
        if (ChromeFeatureList.isEnabled(UNIFIED_PASSWORD_MANAGER_LOCAL_PWD_MIGRATION_WARNING)) {
            runCreateFileOnDiskIntent();
        } else {
            runSharePasswordsIntent();
        }
```
The behaviour depends on `UNIFIED_PASSWORD_MANAGER_LOCAL_PWD_MIGRATION_WARNING` flag.

If the flag is set to `true`, migration happens to the local disk, otherwise - through sharing mechanism.

And this feature was disabled by us to prevent migration warning https://github.com/brave/brave-core/pull/22433/files which doesn't have much  sense for Brave.

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Pixel 2 XL`, `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Pixel 2 XL / taimen-user  8.1.0 OPM2.171026.006.H1 release-keys
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 AP31.240517.031 release-keys
Brave build: 1.68.110
Chromium: 127.0.6533.26 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/38655#issue-2322075516
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Export passwords` is working and `.csv` file is saved to a local storage
- Verified that `Import passwords` via `.csv` file is working in Chrome (waiting for [this feature](https://github.com/brave/brave-browser/issues/35729) to be implemented in Brave)

---------------------------

`Pixel 2 XL / Android 8.1`

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
| ![1]() | ![2]() | ![3]() | ![4]() |

`Galaxy Tab S8 / Android 14`

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
| ![1]() | ![2]() | ![3]() | ![4]() |

`Pixel 7 / Android 15`

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/392c5948-d8d2-4449-96e3-474d7bf114ca) | ![2](https://github.com/brave/brave-browser/assets/128532965/eb7872fb-3a88-4524-8d1e-4f4302fba1ea) | ![3](https://github.com/brave/brave-browser/assets/128532965/83ee85c9-47ea-4546-9cb3-0e160954ca01) | ![4](https://github.com/brave/brave-browser/assets/128532965/e3b775e2-f284-4360-b487-e34da549b0b8) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/7503e78f-058f-4212-84cc-78449f62cbc7) | ![2](https://github.com/brave/brave-browser/assets/128532965/7e8fa72e-e8a5-46a6-9d5f-a47370108887) | ![3](https://github.com/brave/brave-browser/assets/128532965/57118147-7957-4acb-9291-da266a75de43) | ![4](https://github.com/brave/brave-browser/assets/128532965/39557dc8-f721-4ed4-9dae-3c08eb81e7b0) |
