### ISSUE TITLE
[CR126] - Downloads page is inherited from upstream as the warning buttons are not shown when dangerous files are downloaded

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#38657]
### Description
[Edit:  including normal file download buttons as well]
Found while testing https://github.com/brave/brave-browser/issues/38556.  When tested to verify downloading a  `malicious` file via https://testsafebrowsing.appspot.com/s/content.exe, `Remove from list` and `Keep dangerous file` buttons are not shown in the `brave://downloads` page.  And the page is inherited from chromium as `chrome://downloads` page shown same.
Downloaded normal files and `Pause`, `Cancel`, `Resume` & `Retry` buttons are not shown when regular files (not malicious) are downloaded

### Steps to reproduce

1. Install <html>
2. launch Brave
3. open https://testsafebrowsing.appspot.com/s/content.exe in a new tab
4. open https://ubuntu.com/download/desktop/thank-you?version=24.04&architecture=amd64&lts=true
5. click Save
6. open brave://downloads page

### Actual result

`Remove from list` and `Keep dangerous file` buttons are not shown

example | example | example | example 
----- | ------ | ----- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/653ae460-6808-49b8-9a13-eeb60486471e)|![image](https://github.com/brave/brave-browser/assets/98358127/c983a739-9e74-4e01-b4a2-7b67cae6c338)|![image](https://github.com/brave/brave-browser/assets/98358127/d0f810d5-5491-4710-ae28-e514e531e11b)|![image](https://github.com/brave/brave-browser/assets/98358127/182cef33-c082-4ddd-b52c-ce5740ab412a)

### Expected result

`Remove from list` and `Keep dangerous file` buttons should be shown

example | example | example 
----- | ------ | -----
![image](https://github.com/brave/brave-browser/assets/98358127/8d6796ad-df13-41cd-9578-e008738f9d6a)|![image](https://github.com/brave/brave-browser/assets/98358127/c96679da-7f4b-4a2c-92d5-592e76b818f1)|![image](https://github.com/brave/brave-browser/assets/98358127/b3641510-f6f6-447e-9812-955885e208d5)|![image](https://github.com/brave/brave-browser/assets/98358127/03cb21d0-9f54-4462-8797-a5e1e7ac223c)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.68.55 Chromium: 126.0.6478.17 (Official Build) nightly (64-bit)
-- | --
Revision | 5a7678f3d6d2c339a12dd6a91d6369c04cd34287
OS | Windows 11 Version 23H2 (Build 22631.3593)
```

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

@rebron @emerick 
cc: @brave/qa-team

**Comment by emerick** [comment]
This change is due to the `kImprovedDownloadPageWarnings` which is now enabled by default. I'm pushing a PR that disables that setting which restores the old UI, but the buttons seem a little bit squared off to me. Not sure if that's acceptable or not. Might need someone like @fallaciousreasoning to take a look, if not.

This is what they look like with my change
![Screenshot 2024-05-29 161050](https://github.com/brave/brave-browser/assets/5033691/28df51b3-cc3b-4ee8-ab2c-afa00304fa06)

**Comment by fallaciousreasoning** [comment]
@emerick that's fine - @aguscruiz squared all the squircles :D

**Comment by kjozwiak** [comment]
The above requires `1.67.101` or higher for `1.67.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.67.101 Chromium: 126.0.6478.26 (Official Build) beta (64-bit)
-- | --
Revision | a561f4b53cdb831888e5cd702d2b8f9598c00f50
OS | Windows 11 Version 23H2 (Build 22631.3672)
```
Verified using the STR from issue description https://github.com/brave/brave-browser/issues/38657#issue-2322105488

Confirmed `Remove from list` and `Keep dangerous file` buttons are shown for dangerous file downloads
Confirmed Download page buttons (Pause, Cancel, Resume, Retry) are shown and working as expected

example | example | example | example | example | example 
------ | ------ | ------ | ------ | ------- | -------
![image](https://github.com/brave/brave-browser/assets/98358127/cc431a97-8177-4bbc-8357-7054529bee01)|![image](https://github.com/brave/brave-browser/assets/98358127/bb4b3e15-586a-4c84-941f-d28e4695dac4)|![image](https://github.com/brave/brave-browser/assets/98358127/afcb530b-2e11-4551-946f-a1f45319adb2)|![image](https://github.com/brave/brave-browser/assets/98358127/b916e102-da74-4efc-a584-214cca0d372d)|![image](https://github.com/brave/brave-browser/assets/98358127/50022e2a-3c5f-453b-be40-d7e9ec36176e)|![image](https://github.com/brave/brave-browser/assets/98358127/e0f8b433-b53c-42cf-8a04-dc01b611b447)
