### ISSUE TITLE
[ads] Align iOS `NotifyTab[TextContent/HtmlContent]DidChange` with Desktop

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#38659]
### Description

Need to align behavior of following Brave Ads API calls on iOS with Desktop:
* NotifyTabDidChange
* NotifyTabTextContentDidChange
* NotifyTabHtmlContentDidChange

**Comment by btlechowski** [comment]
Verified on Brave 1.68.125 on iPhone 13 Pro Max

Verified test plan from https://github.com/brave/brave-core/pull/23886

<details>




</details>
