### ISSUE TITLE
Brave crashes when alerts/action sheets are dismissed while WebKit is awaiting a response

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#38651]
### Description

If a webpage causes Brave to display an alert such as when `getUserMedia` is called to gain permissions and that alert is dismissed before a user gets a chance to select an option, Brave will crash because WebKit requires we call _all_ completion handlers for all `WKNavigationDelegate`/`WKUIDelegate` methods that have them.

This is caused by `UIAlertController` presented in these delegates not executing any action when they are dismissed thus never calling any completion handlers.

Currently this is a problem is easiest seen with the `webView(_:requestMediaCapturePermissionFor:initiatedByFrame:type:decisionHandler:)` method but it can be an issue for any controllers presented on BVC that handle some input which eventually calls a completion handler on WebKit delegate methods

<details>
<summary>Exception/Crash Log</summary>

```crash
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Completion handler passed to -[Brave.BrowserViewController webView:requestMediaCapturePermissionForOrigin:initiatedByFrame:type:decisionHandler:] was not called'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001804ae138 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x0000000180087db4 objc_exception_throw + 56
	2   CoreFoundation                      0x00000001804ae048 -[NSException initWithCoder:] + 0
	3   WebKit                              0x000000018b1eb268 _ZN6WebKit28CompletionHandlerCallCheckerD2Ev + 140
	4   WebKit                              0x000000018b269c90 _ZNK3WTF20ThreadSafeRefCountedIN6WebKit28CompletionHandlerCallCheckerELNS_17DestructionThreadE0EE5derefEv + 40
	5   WebKit                              0x000000018b4273a4 _ZZN3WTF8BlockPtrIFv20WKPermissionDecisionEE12fromCallableIZN6WebKit10UIDelegate8UIClient41decidePolicyForUserMediaPermissionRequestERNS5_12WebPageProxyERNS5_13WebFrameProxyERN3API14SecurityOrigi	6   libsystem_blocks.dylib              0x00000001800ef118 _call_dispose_helpers_excp + 44
	7   libsystem_blocks.dylib              0x00000001800eff54 _Block_release + 300
	8   Client                              0x00000001022dbaf8 $sIeyB_Ieg_TRTA + 32
	9   libswiftCore.dylib                  0x0000000193271d40 _swift_release_dealloc + 28
	10  libswiftCore.dylib                  0x000000019327276c _ZN5swift9RefCountsINS_13RefCountBitsTILNS_19RefCountInlinednessE1EEEE15doDecrementSlowILNS_13PerformDeinitE1EEEbS3_j + 132
	11  Client                              0x00000001022dae60 $s5Brave21BrowserViewControllerC03webC0_32requestMediaCapturePermissionFor16initiatedByFrame4type15decisionHandlerySo05WKWebC0C_So16WKSecurityOriginCSo11WKFrameInfoCSo07WKMediaH4TypeVySo20WKPermi	12  libswiftCore.dylib                  0x0000000193271d40 _swift_release_dealloc + 28
	13  libswiftCore.dylib                  0x000000019327276c _ZN5swift9RefCountsINS_13RefCountBitsTILNS_19RefCountInlinednessE1EEEE15doDecrementSlowILNS_13PerformDeinitE1EEEbS3_j + 132
	14  Client                              0x000000010217a358 block_destroy_helper + 16
	15  libsystem_blocks.dylib              0x00000001800ef118 _call_dispose_helpers_excp + 44
	16  libsystem_blocks.dylib              0x00000001800eff54 _Block_release + 300
	17  UIKitCore                           0x0000000184906cf4 -[UIAlertController _clearActionHandlers] + 152
	18  UIKitCore                           0x00000001849051c8 -[UIAlertController dealloc] + 300
	19  UIKitCore                           0x0000000184bcf454 -[UIPresentationController .cxx_destruct] + 300
	20  libobjc.A.dylib                     0x0000000180062418 _ZL27object_cxxDestructFromClassP11objc_objectP10objc_class + 112
	21  libobjc.A.dylib                     0x000000018007c6e8 objc_destructInstance + 76
	22  libobjc.A.dylib                     0x0000000180083d70 _objc_rootDealloc + 60
	23  UIKitCore                           0x0000000184bcae28 -[UIPresentationController dealloc] + 364
	24  libsystem_blocks.dylib              0x00000001800f0f70 _ZN10HelperBaseI13GenericInlineE14disposeCaptureILNS1_16BlockCaptureKindE3EEEbjPh + 64
	25  libsystem_blocks.dylib              0x00000001800ef88c _ZN10HelperBaseI13GenericInlineE12destroyBlockEP12Block_layoutbPh + 148
	26  libsystem_blocks.dylib              0x00000001800ef130 _call_dispose_helpers_excp + 68
	27  libsystem_blocks.dylib              0x00000001800eff54 _Block_release + 300
	28  UIKitCore                           0x0000000184cd2444 -[_UIViewControllerTransitionContext .cxx_destruct] + 76
	29  libobjc.A.dylib                     0x0000000180062418 _ZL27object_cxxDestructFromClassP11objc_objectP10objc_class + 112
	30  libobjc.A.dylib                     0x000000018007c6e8 objc_destructInstance + 76
	31  libobjc.A.dylib                     0x0000000180083d70 _objc_rootDealloc + 60
	32  UIKitCore                           0x0000000184cd1344 -[_UIViewControllerTransitionContext dealloc] + 52
	33  UIKitCore                           0x0000000184cd24cc -[_UIViewControllerOneToOneTransitionContext dealloc] + 68
	34  libsystem_blocks.dylib              0x00000001800f0f70 _ZN10HelperBaseI13GenericInlineE14disposeCaptureILNS1_16BlockCaptureKindE3EEEbjPh + 64
	35  libsystem_blocks.dylib              0x00000001800ef88c _ZN10HelperBaseI13GenericInlineE12destroyBlockEP12Block_layoutbPh + 148
	36  libsystem_blocks.dylib              0x00000001800ef130 _call_dispose_helpers_excp + 68
	37  libsystem_blocks.dylib              0x00000001800eff54 _Block_release + 300
	38  libsystem_blocks.dylib              0x00000001800f106c _ZN10HelperBaseI13GenericInlineE14disposeCaptureILNS1_16BlockCaptureKindE4EEEbjPh + 64
	39  libsystem_blocks.dylib              0x00000001800ef8a0 _ZN10HelperBaseI13GenericInlineE12destroyBlockEP12Block_layoutbPh + 168
	40  libsystem_blocks.dylib              0x00000001800ef130 _call_dispose_helpers_excp + 68
	41  libsystem_blocks.dylib              0x00000001800eff54 _Block_release + 300
	42  UIKitCore                           0x0000000185900240 -[UIViewAnimationBlockDelegate .cxx_destruct] + 48
	43  libobjc.A.dylib                     0x0000000180062418 _ZL27object_cxxDestructFromClassP11objc_objectP10objc_class + 112
	44  libobjc.A.dylib                     0x000000018007c6e8 objc_destructInstance + 76
	45  libobjc.A.dylib                     0x0000000180083d70 _objc_rootDealloc + 60
	46  CoreFoundation                      0x00000001803bfbf4 -[__NSDictionaryI dealloc] + 152
	47  libobjc.A.dylib                     0x0000000180086ddc _ZN19AutoreleasePoolPage12releaseUntilEPP11objc_object + 220
	48  libobjc.A.dylib                     0x0000000180086c98 objc_autoreleasePoolPop + 256
	49  CoreFoundation                      0x00000001804c32e0 _CFAutoreleasePoolPop + 28
	50  CoreFoundation                      0x000000018040de68 __CFRunLoopPerCalloutARPEnd + 44
	51  CoreFoundation                      0x00000001804090e0 __CFRunLoopRun + 1976
	52  CoreFoundation                      0x0000000180408514 CFRunLoopRunSpecific + 572
	53  GraphicsServices                    0x000000018ef06ae4 GSEventRunModal + 160
	54  UIKitCore                           0x00000001853e8040 -[UIApplication _run] + 868
	55  UIKitCore                           0x00000001853ebcc8 UIApplicationMain + 124
	56  UIKitCore                           0x000000018488c1cc __swift_destroy_boxed_opaque_existential_1Tm + 10048
	57  Client                              0x0000000102143d08 $sSo21UIApplicationDelegateP5UIKitE4mainyyFZ + 120
	58  Client                              0x0000000102143c80 $s6Client11AppDelegateC5$mainyyFZ + 44
	59  Client                              0x00000001021449f4 main + 28
	60  dyld                                0x00000001097a1544 start_sim + 20
	61  ???                                 0x00000001098c20e0 0x0 + 4455145696
	62  ???                                 0xa316800000000000 0x0 + 11751721015158243328
)
```

</details>

### Steps to reproduce

This is just one way of triggering the crash, however there are many points at which we dismiss anything presented on BrowserViewController.

*Prefix*: Add a Brave shortcuts widget to the home screen and make one of the shortcuts "Brave News" 

Test Case 1 (Media permissions prompt):

1. Visit https://webrtc.github.io/samples/src/content/getusermedia/gum/ and tap `Open Camera` and leave the prompt open without selecting any option
3. Background Brave and on the home screen tap on the "Brave News" shortcut

Test Case 2 (JS alert):

1. Visit https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_alert and tap "Try it" to bring up a JS alert
2. Background Brave and on the home screen tap on the "Brave News" shortcut

### Actual result

Crashes

### Expected result

Shouldn't crash

### Reproduces how often

Easily reproduced

### Brave version

Crash group seems to go as far back as 1.62 ish, but may be an issue in 1.61 as well

### Device/iOS version

Any

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

Follow up to https://github.com/brave/brave-browser/issues/38372
https://github.com/brave/brave-core/pull/23701 should be reverted

**Comment by kjozwiak** [comment]
The above requires `1.66.120` or higher for `1.66.x` verification 👍 @hffvld @Uni-verse just a heads up that I had issues running through `Test Case #1` re: not being able to background Brave while the modal was visible. However, I was able to run through `Test Case #2` and verify that the crash was resolved via https://github.com/brave/brave-core/pull/23915#issuecomment-2148412567.

**Comment by Uni-verse** [comment]
In progress on `iPhone 12 Pro` running `iOS 17.4` using `1.66.1 (120)`

**Case 1: Media permissions prompt**

Test Steps: 

1. New install.
2. Create Brave News shortcut by selecting `Siri Shortcuts` settings page in `Settings` menu.
3. Open `Shortcuts` App on home screen and add Brave News Shortcut to home screen. 
4. Navigate to `https://webrtc.github.io/samples/src/content/getusermedia/gum/ ` and tap on `Open Camera`.
5. Select `Allow` on first prompt (iOS 17).
6. Leave the second prompt open, do not select any of the options and background Brave.
7. Open Brave News shortcut.

- Ensured that crash is not observed when using shortcut while permission prompt is open.

https://github.com/brave/brave-browser/assets/17885425/d9885df9-48f4-40d8-9aaa-12245b8bc3ca

**Case 2: JS Alert**

1. New install
2. Create Brave News shortcut by selecting `Siri Shortcuts` settings page in `Settings` menu.
3. Open `Shortcuts` App on home screen and add Brave News Shortcut to home screen. 
4. Navigate to `https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_alert`
5. Tap on `Try it`
6. Leave the alert open and background app.
7. Open Brave news shortcut.

**Comment by hffvld** [comment]
Verified on `iPad Air` using version(s):
```
Device/OS: iPad Air / iPadOS 16.7.2
Brave build: 1.66.2 (124)
BraveCore: 1.66.124 (125.0.6422.165)
```
---------------------------
<details>
<summary> Media permissions prompt </summary>

**STEPS:**
1. Install and launch Brave
2. Create a `Brave News` shortcut by selecting the `Siri Shortcuts` settings page in the `Settings` menu
3. Open the `Shortcuts` App on the home screen and add Brave News Shortcut to the home screen
4. Navigate to `https://webrtc.github.io/samples/src/content/getusermedia/gum/ ` and tap on `Open Camera`
5. Select `Allow` on the first prompt
6. Leave the second prompt open, do not select any of the options and background Brave
7. Open the `Brave News` shortcut

**ACTUAL RESULTS:**
- Verified that a crash is not observed when using a shortcut while the permission prompt is open.

---------------------------

https://github.com/brave/brave-browser/assets/128532965/3392d146-0637-4a93-afb7-c03476b01a4f
</details>

<details>
<summary> JS Alert </summary>

**STEPS:**
1. Launch Brave 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>
