### ISSUE TITLE
Edit buttons are not aligned in the `Move to...` modal in the bookmarks sidepanel UI 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#38650]
### Description

Looks like this is regression. After importing bookmarks from various sources (Chrome, FF etc), tried move one folder to another, buttons are not aligned horizontally as expected as in 1.66.x. 

### Steps to reproduce

1.  Install 1.67.x
2.  launch Brave
3.  import bookmarks from various browsers (Chrome, FF etc)
4.  open Bookmarks via sidepanel 
5.  click `Bookmarks`
6.  click `Edit` button
7. checked checkbox for `Imported From Firefox`
8. clicked `Move` button from the menu at the bottom of the panel

### Actual result

New Folder, Cancel & Save buttons are not aligned
example | example 
------ | ------
![image](https://github.com/brave/brave-browser/assets/98358127/fbc8da3a-0e0f-4b2f-b826-b1b115c650d1)|![image](https://github.com/brave/brave-browser/assets/98358127/ad0d7a74-3b97-4ef4-95c5-4aa661c45f5f)

### Expected result

New Folder, Cancel & Save buttons should be horizontally aligned 

![image](https://github.com/brave/brave-browser/assets/98358127/93c52508-b860-4e5a-aea2-6f128ad5d759)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.66.113 Chromium: 125.0.6422.76 (Official Build) (64-bit)
-- | --
Revision | b1864a9a0152d4f1631121c6b13a7426f50cf336
OS | Windows 11 Version 23H2 (Build 22631.3593)

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

@rebron  
cc: @brave/qa-team

**Comment by rebron** [comment]
cc: @emerick @simonhong

**Comment by fallaciousreasoning** [comment]
Reproduces in 1.68

**Comment by fallaciousreasoning** [comment]
This is being caused because the Nala buttons are a bit fatter and the text wraps - I think this will happen in other languages too, where the translations are longer than the english text

**Comment by fallaciousreasoning** [comment]
Reproduces in Chromium, in Spanish 
![image](https://github.com/brave/brave-browser/assets/7678024/e74b7f09-4a9e-4563-9308-672a736fd7c2)

**Comment by GeetaSarvadnya** [comment]
Dup of https://github.com/brave/brave-browser/issues/38639
