### ISSUE TITLE
[CR 126] Elements in the Tab search UI may have been inherited from Chromium

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#38652]
### Description

Found while testing https://github.com/brave/brave-browser/issues/38556.   Some of the elements may have may have been inherited from Chromium i.e. 
Search tabs short cut shown ->`Shift+Ctrl+A`  ---> should show `Ctrl + Shift + A`
Open tabs --> should be bold and caps **OPEN TABS**
Blue Scrollbar -->  should show `gray`

### Steps to reproduce

1. Install 1.68.55
2. launch Brave
3. open few tabs and close some of the tabs
4. click `Search tabs` button in the top right corner of browser window

### Actual result

Following seem to have inherited from Chromium 

- Search tabs short cut shown ->`Shift+Ctrl+A`  ---> should show `Ctrl + Shift + A`
- Open tabs --> should be bold and caps **OPEN TABS**
- Blue Scrollbar --> should show `gray`

![Screenshot 2024-05-28 125608](https://github.com/brave/brave-browser/assets/98358127/3de0c2cd-34ff-4455-b1da-2a7ef40927c6)

### Expected result

![image](https://github.com/brave/brave-browser/assets/98358127/25f31ca1-458c-4d77-b35a-53613899874d)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.68.55 Chromium: 126.0.6478.17 (Official Build) nightly (64-bit)
-- | --
Revision | 5a7678f3d6d2c339a12dd6a91d6369c04cd34287
OS | Windows 11 Version 23H2 (Build 22631.3593)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

@rebron @emerick 
cc: @qa

**Comment by simonhong** [comment]
checking.

**Comment by rebron** [comment]
@brave/qa-team Discussed with @MadhaviSeelam and @LaurenWags and @simonhong 

We only need to update the scrollbar color for this issue.
We'll keep the text change from All caps to sentence casing and the shortcut hints change

**Comment by kjozwiak** [comment]
The above requires `1.67.106` or higher for `1.67.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.67.107 Chromium: 126.0.6478.26 (Official Build) beta (64-bit)
-- | --
Revision | 2831369c7540d93e98f38d9b463f6762430a7982
OS | Windows 11 Version 23H2 (Build 22631.3672)
```

Verified using STR from the issue description https://github.com/brave/brave-browser/issues/38652#issue-2321847102

#### Confirmed tab search bubble's scroll thumb color shown gray as expected

Light | Theme
------  | --------
![image](https://github.com/brave/brave-browser/assets/98358127/4b9e2fd3-2943-456f-9656-ead9abf79072)|![image](https://github.com/brave/brave-browser/assets/98358127/4f2459bb-0ad9-43f5-b88d-eb1be0b8b2d1)
