### ISSUE TITLE
"Turn on sync" nagbar under bookmark dialog

### ISSUE THREAD

**Issue by JunkiEDM** [brave/brave-browser#38663]
### Description

In Brave Nightly 1.68.55-1.68.57, a nagbar to "Turn on sync" appears under bookmark dialogs. Other than being mildly annoying, the button also opens a Google Chrome sign-in page (`https://accounts.google.com/signin/chrome/sync?ssp=1&continue=https%3A%2F%2Fwww.google.com%2F`) instead of the expected `brave://settings/braveSync` page.

### Steps to reproduce

1. Click bookmark icon on any page (doesn't matter if bookmarked already or not)
2. (Optional) Click "Turn on sync..." button to open Google Chrome sign-in tab

### Actual result

![Bookmark dialog with nagbar](https://github.com/brave/brave-browser/assets/8350274/e3fa3c32-5679-4072-a683-448269991d43)
"Turn on sync..." button opens `https://accounts.google.com/signin/chrome/sync?ssp=1&continue=https%3A%2F%2Fwww.google.com%2F` in a new tab.

### Expected result

No nagbar at all ideally, or at least redirect to `brave://settings/braveSync` instead of Google sign-in

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.68.55 Chromium: 126.0.6478.17 (Official Build) nightly (64-bit)
-- | --
Revision | 5a7678f3d6d2c339a12dd6a91d6369c04cd34287
OS | Windows 11 Version 23H2 (Build 22635.3646)

Also reproduced in:
Brave | 1.68.57 Chromium: 126.0.6478.17 (Official Build) nightly (64-bit)
-- | --
Revision | 39f61f3a6273f9853f504bfe8ae88dc159cb3d7f
OS | Windows 11 Version 23H2 (Build 22635.3646)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.67.101` or higher for `1.67.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.67.101 Chromium: 126.0.6478.26 (Official Build) beta (64-bit)
-- | --
Revision | a561f4b53cdb831888e5cd702d2b8f9598c00f50
OS | Windows 10 Version 22H2 (Build 19045.4412)

```
- Verified the STR from the description and ensured that `Turn on sync` isn't shown on the bookmarks dialog
![image](https://github.com/brave/brave-browser/assets/38657976/bad6e6c7-89c7-43ba-bd4b-fdad30883970)

**Comment by emerick** [comment]
Thanks @0xAndrewBlack, I think we just fixed this in https://github.com/brave/brave-browser/issues/45713.
