### ISSUE TITLE
[ads] `NotifyTabTextContentDidChange` is called non-Rewards users

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#38668]
### Description

`NotifyTabTextContentDidChange` shouldn't be called for non-Rewards users. See Desktop implementation: https://github.com/brave/brave-core/blob/master/browser/brave_ads/tabs/ads_tab_helper.cc#L235

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6
Brave build: 1.68 (106)
BraveCore: 1.68.106 (126.0.6478.126)
```
---------------------------
<details>
<summary> Test case 1 </summary>

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/23893#issue-2323502843 and:
2. Fresh install and launch Brave
3. Open `Dev options` and enable the `ShouldAlwaysRunBraveAdsService` feature
4. Enable `Log Verbosity` for the ads
5. Restart Brave
6. Open some web page > *Verify*

**ACTUAL RESULTS:**
- Verified that tab HTML content changed notification is fired. _There should be a log line: `[ads] Tab id <id> HTML content changed`_
- Verified that tab text content changed notification is NOT fired. _There should NOT be a log line: `[ads] Tab id <id> text content changed`_

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/7b818280-de48-49f6-bdaf-92ecc9e3280e) | ![2](https://github.com/brave/brave-browser/assets/128532965/97c442df-d83e-4bee-984d-6dcec1b9c838) |
</details>

<details>
<summary> Test case 2 </summary>

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/23893#issue-2323502843 and:
2. Fresh install and launch Brave
3. Open `Dev options` and enable `Log Verbosity` for the ads
4. Restart Brave
5. Join Brave Rewards
6. Open some web page > *Verify*

**ACTUAL RESULTS:**
- Verified that tab HTML content changed notification is fired. _There should be a log line: `[ads] Tab id <id> HTML content changed`_
- Verified that tab text content changed notification is fired. _There should be a log line: `[ads] Tab id <id> text content changed`_

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/63cc7a1d-be94-48ea-a988-37768bcdabb4) | ![2](https://github.com/brave/brave-browser/assets/128532965/fac6fe19-9f2f-46a6-91f0-a2673160face) |
</details>
