### ISSUE TITLE
URL Bar may show insecure connection during a network change

### ISSUE THREAD

**Issue by iccub** [brave/brave-browser#38671]
### Description

This bug works on legit websites like [google.com](http://google.com/).

### Steps to reproduce

May require few tries

1. Have some vpn app.
2. Connect or disconnect to the vpn
3. Load a google search query during the connection/disconnection process.

It may also happen when you you drop out of wifi range and fall back to the mobile network.

The serverTrust from webkit seems to return nil in this case.

### Actual result

![IMG_3634 2](https://github.com/brave/brave-browser/assets/6950387/9ff4f0cc-7c40-4ad8-bb16-73e387e0dfa9)

You may see the (i) insecure indicator in the url bar, the 'Site info' will show 'Page not secure'

### Expected result

Something else

### Reproduces how often

Easily reproduced

### Brave version

Latest

### Device/iOS version

Latest

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [X] with Brave Shields disabled
- [X] in the latest version of mobile Safari

### Miscellaneous information

Seems like a webkit bug. It also happens in Chromium
https://issues.chromium.org/issues/343247651

We try to investigate whether this bug can happen outside of the network switch condition.

Related https://github.com/brave/brave-browser/issues/38667

**Comment by diracdeltas** [comment]
putting p2 for now; if it could potentially do the opposite (showing secure for insecure site) then it should be bumped to p1

**Comment by iccub** [comment]
Hi. The current copy looks like this

![IMG_D7B732687952-1](https://github.com/brave/brave-browser/assets/6950387/faf2cca9-4175-4d43-97a5-a16088235b04)

@stoletheminerals or @rmcfadden3 can you help with suggesting the new copy? For the title and description
The new state is something like 'unavailable' or 'unknown' and we want to tone down the 'scariness' level. So making it sound more neutral

**Comment by stoletheminerals** [comment]
`The connection to this site could not be fully verified. You may proceed or try reloading the page to establish a secure connection.`

Something along these lines

**Comment by iccub** [comment]
@rmcfadden3 are you ok with following copy^? Or want to reword it a bit

**Comment by rmcfadden3** [comment]
Yeah, looks solid. Just a couple minor copyedits:

`Your connection to this site could not be fully verified. You may proceed, or try reloading the page to establish a secure connection.`

**Comment by iccub** [comment]
@stoletheminerals @rmcfadden3 what about the title, do we update it to something more neutral?

**Comment by rmcfadden3** [comment]
@iccub would something like `Unverified site connection` or `Unsecured site connection` or `Site connection not verified` work?

**Comment by iccub** [comment]
@stoletheminerals do you like one of the choices above?

**Comment by stoletheminerals** [comment]
1 or 3 looks good to me

**Comment by kylehickinson** [comment]
@stoletheminerals Any preference on colors?

| Default Icon | Sys Feedback Info | Sys Feedback Warning | Sys Feedback Error |
| -- | -- | -- | -- |
| ![image](https://github.com/brave/brave-browser/assets/529104/dfd8c251-b34c-48ca-b2ac-4916e1e209a3) | ![image](https://github.com/brave/brave-browser/assets/529104/a03a8cb7-8470-4434-adf7-c96fb568f4bb) | ![image](https://github.com/brave/brave-browser/assets/529104/cd1ad2b6-e3f4-4044-8ea5-3cc97543711c) | ![image](https://github.com/brave/brave-browser/assets/529104/35a086ae-afd1-4dcc-852d-1e87b45c0c2d) |

**Comment by stoletheminerals** [comment]
The blue one I don't like, implies it's safe and work as expected imo. The `Sys Feedback Warning` looks like a good balance between an error and default icon, i'd prefer that one.

**Comment by kjozwiak** [comment]
The above requires `1.67.118` or higher for `1.67.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.67.118`

- Ensured that tapping on the URL bar icons for various `badssl.com` pages will show the correct copy for insecure/mixed content.
- Ensured tapping`(i)` icon in URL when loading pages shows new copy/color of unknown state.
- Ensured certificate can be viewed via URL bar and shared menu.

Example | Example | Example
-|-|-
![IMG_6468](https://github.com/brave/brave-browser/assets/17885425/0fbd4599-fbe7-4bbf-8e4d-a4d7686abceb) | ![IMG_6473](https://github.com/brave/brave-browser/assets/17885425/973737a9-1bc3-42ac-a0bd-f52913dfdc9d) | ![IMG_6474](https://github.com/brave/brave-browser/assets/17885425/df0ad181-843d-492b-b918-a339cc50ba48)

1.66 | 1.67.118 | Dark Mode
-|-|-
![IMG_6476](https://github.com/brave/brave-browser/assets/17885425/a5b27298-7e96-4223-a86c-1e69b6384cbf) | ![IMG_6477](https://github.com/brave/brave-browser/assets/17885425/c338fbf6-c3b5-46bd-af90-34e52308852f) | ![IMG_6478](https://github.com/brave/brave-browser/assets/17885425/8caed7b8-fa4e-49c7-8046-14159cbd06ea)
