### ISSUE TITLE
Timestamps in Rewards logs should include timezone and be normalized to UTC

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#38677]
## Description

Currently, Rewards logs timestamps show local time but doesn't specify the timezone. This can be confusing when viewing the logs at a later date or when different people looking at it are in different timezones.

## Solution

1. Timestamps should also include timezone
2. Timezone should be UTC, which helps with location privacy if logs are shared

**Comment by Miyayes** [comment]
@tmancey Would this need separate changes for ads logging? Just want to make sure it's consistent.

@fmarier Does this pose any privacy issue? We can keep timestamps always in UTC.

**Comment by tmancey** [comment]
@Miyayes this would not need separate changes for ads. Thanks

**Comment by fmarier** [comment]
That's the log that's manually shared by users with support when we are trying to debug their problems, right?

My preference would be to just show UTC because it leaks less info about the user and it sounds like it would solve support's problem.

**Comment by Miyayes** [comment]
>That's the log that's manually shared by users with support when we are trying to debug their problems, right?

Yes, that's correct.

>My preference would be to just show UTC because it leaks less info about the user and it sounds like it would solve support's problem.

Great, we will make sure all timestamps are always in UTC, never in any local timezone.

**Comment by GeetaSarvadnya** [comment]
@Miyayes The logs tab in brave://rewards-internals shows the UTC timestamp for logs as expected, but there is no mention of UTC is that ok? Also the event logs still shows the local timestamp, looks like it's expected, I just wanted to double check.
cc: @LaurenWags 

Logs | event logs
------|---------
![image](https://github.com/user-attachments/assets/23fbd2d0-ae05-4ec5-9cc1-835bd739ad50) | ![image](https://github.com/user-attachments/assets/d22dcb09-6a04-4c96-aecc-f6fd87741d6d)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.69.115 Chromium: 127.0.6533.43 (Official Build) nightly (64-bit)
-- | --
Revision | 0f3c95cf9cac0acfd6d49bd72bb2ed548901a082
OS | Windows 10 Version 22H2 (Build 19045.4651)
```
Verified the description from the issue https://github.com/brave/brave-browser/issues/38677#issue-2323915567
Confirmed that UTC timestamp is shown for the rewards logs via brave://rewards-internals
Logged a follow up issue https://github.com/brave/brave-browser/issues/39844

Logs | event logs
------|---------
![image](https://github.com/user-attachments/assets/23fbd2d0-ae05-4ec5-9cc1-835bd739ad50) | ![image](https://github.com/user-attachments/assets/d22dcb09-6a04-4c96-aecc-f6fd87741d6d)
