### ISSUE TITLE
Back button not disabled on New Tab Page without history

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#38670]
### Description

Back button is no longer disabled on fresh new tab page without history

### Steps to reproduce

1. Open new tab
2. Back button not disabled (can long-press but tapping does nothing)

### Actual result

Not disabled

![NTP](https://github.com/brave/brave-browser/assets/5314553/939817fd-5e25-4956-8c60-2f706a10db86) | ![NTP - back](https://github.com/brave/brave-browser/assets/5314553/e832783d-2d9b-4f62-b308-3ef99c17bd60)
--|--

### Expected result

Disabled when no history

### Reproduces how often

Easily reproduced

### Brave version

v1.68.46+

### Device/iOS version

all

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6
Brave build: 1.67 (125)
BraveCore: 1.67.125 (126.0.6478.126)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/23971#issue-2331882738

**ACTUAL RESULTS:**
- Verified that `Back arrow` disabled on `NTP` when no history available

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/fd66b24f-303f-4d31-895f-fb634a0088fa) | ![2](https://github.com/brave/brave-browser/assets/128532965/b4961274-c5c6-4c7c-8164-7b4c7e953e40) |

https://github.com/brave/brave-browser/assets/128532965/4284329c-fd3c-4577-b3bd-f6e1db484de3
