### ISSUE TITLE
Switch toggle disabled state inherits Chrome theme [CR126]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#38687]
### Description

Design/color scheme for switches has changed changed in Chromium 126 in Shields panel and some pages in settings menu.

### Steps to reproduce

1. New install Chromium 126 build
2. Open webpage, expand Shields panel / disable Shields
3. Also check `Content Filters` in `Privacy Settings`

### Actual result

C125 | C126
-|-
![Screenshot 2024-05-29 at 10 42 12 AM](https://github.com/brave/brave-browser/assets/17885425/3523aabf-2906-4e9d-808f-9382028bc8cc) | ![Screenshot 2024-05-29 at 11 25 19 AM](https://github.com/brave/brave-browser/assets/17885425/f3462e0d-e9fd-4653-bbc6-bf397f0fc333)
![Screenshot 2024-05-29 at 11 57 09 AM](https://github.com/brave/brave-browser/assets/17885425/f8d71bc4-c683-4c2e-91a4-e2fd2e82f0cd) | ![Screenshot 2024-05-29 at 11 44 51 AM](https://github.com/brave/brave-browser/assets/17885425/ab160c62-3cd2-4dfd-b700-0b75b84840ff)

### Expected result

Color theme should be retained from previous version

### Reproduces how often

Easily reproduced

### Brave version

1.68.45

### Device

- Brand/model: Samsung Devices
- Android version: 13

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.67.101` or higher for `1.67.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.67.105 Chromium: 126.0.6478.26 (Official Build) beta (64-bit) 
Revision	ff15eaa0be4f63abc388184895a7450c929375c8
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that the disabled state for switch toggle does not inherit the chromium theme. 
- Ensured that the switches in `Content Filtering` settings page do not have the chromium switch theme.

Example | Example | Example
-|-|-
![Screenshot 2024-06-04 at 3 28 37 PM](https://github.com/brave/brave-browser/assets/17885425/0c6f2f70-91c6-4f50-b16e-156f9cdf93a6) | ![Screenshot 2024-06-04 at 3 28 46 PM](https://github.com/brave/brave-browser/assets/17885425/0d080c26-6fa0-4734-a5fa-035583a9b8dc) | ![Screenshot 2024-06-04 at 3 29 14 PM](https://github.com/brave/brave-browser/assets/17885425/7f10ffe1-e90a-4652-93f5-dbb96ca22ad4)
