### ISSUE TITLE
Ads confirmations should not be sent if the wildcard is in a forbidden part of the URL

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#38683]
### Description

See https://bravesoftware.slack.com/archives/CJR5902AW/p1717002819317479?thread_ts=1716931296.694229&cid=CJR5902AW for details. If the view/click/landing/conversion URLs for any ad contains a wildcard, we must validate that the wildcard is in either the URL's path or a subdomain before sending a confirmation event. Wildcards in the "base domain" (eTLD+1) part of the URL are invalid and should not trigger any kind of reporting.

**Comment by diracdeltas** [comment]
Needs to be done on iOS/Android as well if we support wildcards in conversion/etc URLs on those platforms.

**Comment by diracdeltas** [comment]
see server side implementation in https://github.com/brave/ads-serve/pull/3957

**Comment by diracdeltas** [comment]
@tackley Can you confirm what is being done (or going to be done) server-side for third party validations? We should probably copy those in the client as well.

**Comment by tackley** [comment]
> @tackley Can you confirm what is being done (or going to be done) server-side for third party validations? We should probably copy those in the client as well.

Yes, we will use the same tests cases on both server and client. I'll share them with you for your review once I've got to that point in implementation.

**Comment by tmancey** [comment]
@diracdeltas we use the same test cases, however, we also support certain brave:// schemes which was approved in a previous privacy review. Thanks

**Comment by btlechowski** [comment]
Verified with

Brave | 1.69.139 Chromium: 127.0.6533.100 (Official Build) beta (64-bit)
-- | --
Revision | 0da988816510c06ff835a14b500d5ab861e18d6e
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/24076



#### Confirmed that catalog creative set conversions are discarded if the url_pattern contains asterisk wildcard(s) in eTLD+1
<details>


</details>

#### Confirmed that catalog creative set conversions are discarded if the url_pattern contains question mark wildcard(s) in eTLD+1
<details>


</details>


#### Confirmed that catalog creative set conversions are discarded if the url_pattern does not have the same domain and registry as the target_url
<details>


</details>



#### Confirmed that catalog creative instances are discarded if the target_url contains asterisk wildcard(s) in eTLD+1
<details>


</details>


#### Confirmed that catalog creative instances are discarded if the target_url contains question mark wildcard(s) in eTLD+1
<details>


</details>



#### Confirmed that catalog creative instances are discarded if the imageUrl contains asterisk wildcard(s) in eTLD+1
<details>


</details>

#### Confirmed that catalog creative instances are discarded if the imageUrl contains question mark wildcard(s) in eTLD+1
<details>


</details>



</details>
