### ISSUE TITLE
[CR 126] - `Not secure` font size is smaller and URL bar height appear to be shorter

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#38685]
### Description

Found while testing https://github.com/brave/brave-browser/issues/38556.  While verifying SSL pinning error testcase with https://ssl-pinning.someblog.org/, URL bar shown `Not secure` text but the font size appears be smaller, compared with [CR 125] build `1.68.45 Chromium: 125.0.6422.112 (Official Build) nightly`.  Additionally, URL bar height visually seem to be shorter.

### Steps to reproduce

1. Install 1.68.58
2. launch Brave
3. visit https://ssl-pinning.someblog.org/ in a new tab
4. verify `Not sure` font size in the URL bar and the URL bar height

### Actual result

`1.68.58 Chromium: 126.0.6478.17 (Official Build) nightly (64-bit)`
---------------- 
![image](https://github.com/brave/brave-browser/assets/98358127/a37c41d4-d940-435d-8db4-bac74feb936f)

### Expected result

Same as in `1.68.45 Chromium: 125.0.6422.112 (Official Build) nightly`?
![image (1)](https://github.com/brave/brave-browser/assets/98358127/ca1fd4a8-f8d9-4509-8c40-bcfa771efb02)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.68.58 Chromium: 126.0.6478.17 (Official Build) nightly (64-bit)
-- | --
Revision | ec786b623be34c911487c24144c0650bdd057fc1
OS | Windows 11 Version 23H2 (Build 22631.3593)
```

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

@zenparsing @aguscruiz 
cc: @rebron @qa

**Comment by simonhong** [comment]
working on this.

**Comment by simonhong** [comment]
Internal page's icon label is also small.
<img width="160" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/72884e56-9375-489b-a49f-b16b311ec9eb">

**Comment by kjozwiak** [comment]
The above requires `1.67.105` or higher for `1.67.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.67.107 Chromium: 126.0.6478.26 (Official Build) beta (64-bit)
-- | --
Revision | 2831369c7540d93e98f38d9b463f6762430a7982
OS | Windows 11 Version 23H2 (Build 22631.3672)
```

Verified using STR from the description https://github.com/brave/brave-browser/issues/38685#issue-2324270329

Confirmed  `Not secure` button is shown as expected

![image](https://github.com/brave/brave-browser/assets/98358127/27d4d67a-29fd-4b8d-bd7c-1bc9541fa8ef)
