### ISSUE TITLE
Text update

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#38688]
### Description

Pls update the text for this setting, ideally make it shorter and also update to Title Case

![Screenshot 2024-05-29 at 16 34 22](https://github.com/brave/brave-browser/assets/7606853/eb46f3b1-f14d-4c4d-b85e-e3cf5648d525)

### Steps to reproduce

1. 
2. 
3. NA

### Actual result

NA

### Expected result

NA

### Reproduces how often

Easily reproduced

### Brave version

All

### Device/iOS version

all

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by aguscruiz** [comment]
There's also been a copy update here that we should do:

https://www.figma.com/design/h7fKSJF2P556bZWfyLTfwD/Leo-MVP?node-id=4886-50831&t=AODAUq0xoUog7blB-1

![image](https://github.com/brave/brave-browser/assets/15734630/edeb20a8-7817-4169-85f0-9c43c718d533)

cc @mattmcalister @Brandon-T

**Comment by Brandon-T** [comment]
This is already completed on iOS since release :)
