### ISSUE TITLE
Accessing MoneyMetals.com causes Brave iOS to crash

### ISSUE THREAD

**Issue by SamBonavika** [brave/brave-browser#38694]
### Description

Visit https://www.moneymetals.com, app goes boom! ;-}

### Steps to reproduce

1. Open Brave
2. Enter "www.moneymetals.com" in address bar, press "go" button.

### Actual result

App "hard" crashes.

### Expected result

Site should have displayed.

### Reproduces how often

Easily reproduced

### Brave version

Version 1.65 (122)
BraveCore 1.65.122 (124.0.6367.82)

### Device/iOS version

Device iPhone 8 Plus (iOS 16.7.8)

### Affected browser versions

- [X] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [X] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

Issue occurs in both "private" and regular mode.

**Comment by iccub** [comment]
Do you use any custom filter lists? We can't reproduce the crash

**Comment by SamBonavika** [comment]
The issue no longer manifests with the latest version:

  Version 1.66 (113)
  BraveCore 1.66.113 (125.0.6422.76)

I will re-open if it happens again.
