### ISSUE TITLE
[ads] Unable to trigger Brave News inline ad viewed event when opted-in to News from NTP

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#38698]
### Description

Follow up to: https://github.com/brave/brave-browser/issues/38378

### Steps to reproduce

  1. Fresh install
  2. Join Brave Rewards
  3. Open NTP
  4. Close the Browser
  5. Open the Browser
  6. Join Brave News In the restored NTP tab
  7. Trigger view event on Brave News inline ad

### Actual result

Brave news inline ad is served, but is not able to trigger view event in initial state. The event is not triggered event when ad is in full view.

Note: scrolling fully up to NTP, then down again to the ad, triggers view event

view event is not triggered for following ad placement:
![image](https://github.com/brave/brave-browser/assets/34715963/9355fea1-8e4f-483f-baaf-2d60eab6aa67)

### Expected result

view event is triggered

### Reproduces how often

Easily reproduced

### Brave version

Reproduced on 1.68.56 on iPhone 13 Pro Max 

cc @tmancey @aseren @iambrianfung

**Comment by kjozwiak** [comment]
The above requires `1.66.120` or higher for `1.66.x` verification 👍
