### ISSUE TITLE
[iOS] Issue with sometimes the resources on the engine not being set

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#38697]
### Description

There are some cases we've seen that the resources are not set. This seems to be caused only during branch switching and results from the resources updated callback only triggering if the resources were updated.

As a precaution, we should ensure that the callback is triggered at least once when subscribing regardless if resources have been updated or not. This will not cause any unforeseen performance issues as the engines will ignore any resource updates that are of a lower or same version but will ensure the resources are set if they weren't.

### Steps to reproduce

Unfortunately the steps to reproduce this are impossible to define. However we should test youtube ad-blocking on launch (new install) and re-launch (after termination)

### Actual result

Sometimes youtube ads are not blocked (again seems to only happen in isolated development cases)

### Expected result

Should always block youtube ads.

### Reproduces how often

No steps to reproduce

### Brave version

1.67

### Device/iOS version

Any

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.68.127` or higher for `1.68.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6
Brave build: 1.68 (128)
BraveCore: 1.68.128 (127.0.6533.73)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/38697#issue-2325450519
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `True` is shown for the `This frame` column when loading/refreshing https://dev-pages.brave.software/filtering/scriptlets.html

---------------------------

https://github.com/user-attachments/assets/83ff9f52-efb5-4211-bef0-e7e64b7ca43e
