### ISSUE TITLE
Move Sidebar up to the top level in the application menu

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#38708]
### Description

Currently sidebar is buried in the application/hamburger menu in `More tools...`. Sidebar visibility should be at the top level. On | Autohide | Off should correspond to Always | On mouse over | Never sub menu items.

### Steps to reproduce

1. Open application menu.
2. Notice sidebar is another level deep under `More tools...`

### Actual result

<img width="568" alt="Screenshot 2024-05-30 at 1 27 10 PM" src="https://github.com/brave/brave-browser/assets/5951041/6f1fd5bc-bfd2-4749-9928-165fe59f6ac5">

### Expected result
<img width="440" alt="Screenshot 2024-05-30 at 1 29 19 PM" src="https://github.com/brave/brave-browser/assets/5951041/171f0a89-9125-45e3-9c56-33ed0947c5f2">

<img width="377" alt="Screenshot 2024-06-06 at 9 01 53 AM" src="https://github.com/brave/brave-browser/assets/5951041/2a3de885-74f1-409c-a136-608f25aa806e">

<img width="283" alt="Screenshot 2024-06-06 at 9 01 46 AM" src="https://github.com/brave/brave-browser/assets/5951041/970a1824-a8ed-4d7f-bab8-4b42ab2bc21e">

Figma file: `https://www.figma.com/design/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?node-id=229-18698&t=L2JqSDrMOKAtOFrc-0`

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.x and higher.

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by aguscruiz** [comment]
Design file here:
https://www.figma.com/design/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?node-id=6697-27337&t=LVdwfrGMPFimqU0t-1

@rebron ready

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.69.88 Chromium: 127.0.6533.26 (Official Build) nightly (x86_64)
-- | --
Revision | d60303973dc3604d9d348b981322a8a04dcbb86d
OS | macOS Version 13.6.7 (Build 22G720)
```

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.69.137 Chromium: 127.0.6533.100 (Official Build) beta (x86_64)
-- | --
Revision | 40b6ccbd1eb76c8f575e83de8ad81c4349d3f32a
OS | macOS Version 11.7.10 (Build 20G1427)
```

Verified test plan from https://github.com/brave/brave-core/pull/24121#issue-2345659095 and STR from https://github.com/brave/brave-browser/issues/38708#issue-2326490890.

Confirmed the "Sidebar" show option is at the top level of the app/hamburger menu, right below VPN
Confirmed the "Sidebar" show option is not displayed under "More Tools" on app/hamburger menu
Confirmed On | Autohide | Off correspond to Always | On mouse over | Never options from settings
Confirmed selecting On | Autohide | Off is persisted across new windows and browser restarts
Confirmed expected color of selection for both dark and light themes

`Light` | `Dark`
--------|-------
<img width="347" alt="Screen Shot 2024-08-08 at 12 06 07 PM" src="https://github.com/user-attachments/assets/0b3b0ae0-772c-405c-b7b0-c9765d26a64e"> | <img width="354" alt="Screen Shot 2024-08-08 at 12 06 26 PM" src="https://github.com/user-attachments/assets/5a6324c8-c1f2-445c-8b10-db850b78c7bf">
