### ISSUE TITLE
Shields is no longer dark

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#3870]
https://github.com/brave/brave-core/pull/1931 changed Shields UI from always-dark to always-light. We want to make sure that this reaches release without this theme change. Either make it always-dark or, preferrably, make it switch depending on browser / OS theme-type choice (dark or light).

## Test Plan:

1. Go to chrome://settings/appearance
2. Switch theme
3. Change active tab to an http(s) site
4. Open shields

Expected: Shields should match whether dark/light theme was selected in Settings
Actual: Shields is only ever light

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

Used test plan from the description.
