### ISSUE TITLE
Playlist buttons are oversized

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#38702]
### Description

An update to Nala via this PR https://github.com/brave/brave-core/pull/23246 caused the Playlist buttons to be oversized an no longer fit in the panel space. Playlist buttons should be using previous button/UI styling before this pr update.

### Steps to reproduce

1. Use 1.67.76 or higher.
2. Open playlist in the sidebar
3. Notice the buttons are oversized.

### Actual result

![screenshot_2024-05-08_at_5 16 44___pm_480](https://github.com/brave/brave-browser/assets/5951041/b6ce0b5a-82d6-4154-9315-40bf92df2a0f)

### Expected result

![screenshot_2024-05-08_at_5 17 06___pm_480](https://github.com/brave/brave-browser/assets/5951041/8e471ebd-78fe-49d6-a831-5309b25435b8)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Started with 1.67.76 and higer.

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by stephendonner** [comment]
## Verification `PASSED` using

```
Brave | 1.68.85 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | 8e76a669cf78bdfa933c8d569460092a01166588
OS | Windows 10 Version 22H2 (Build 19045.4474)
```

### Steps:
1. installed `1.67.76`
2. launched Brave
3. enabled `Playlist` via `brave://flags`
4. clicked `Relaunch`
5. loaded `https://www.youtube.com/watch?v=qNDXdW4jO3I`
6. clicked to `Add to Playlist`
7. expanded the playlist section
8. double-clicked on the `YouTube` video
9. examined and played with the player controls

### Confirmed the full set of player controls are visible now and work

`1.67.76` | `1.68.85`
----------|---------
![image](https://github.com/brave/brave-browser/assets/387249/81cbfa4c-7386-4760-a262-620bc2bc8aaf) | ![image](https://github.com/brave/brave-browser/assets/387249/127264a1-2db4-490c-be7c-485fb5e4f092)
