### ISSUE TITLE
AI Chat search query results need "learn more" link

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#38709]
Learn more should appear after search results and link to a relevant help page.

<img width="743" alt="image" src="https://github.com/brave/brave-browser/assets/741836/cae2505b-4ab6-4af9-a905-e497d24da53c">

**Comment by kjozwiak** [comment]
The above requires `1.67.106` or higher for `1.67.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.67.107 Chromium: 126.0.6478.26 (Official Build) beta (x86_64)
-- | --
Revision | 2831369c7540d93e98f38d9b463f6762430a7982
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.67.107`
2. launched Brave
3. asked `Leo` `Has India landed on the moon?`
4. waited
5. confirmed `Improving answer with Brave Search...` messaging
6. (ignored incorrect answer)
7. clicked on each link provided
8. confirmed `Brave Search`-query source
9. looked at the final link
10. confirmed and clicked on `Learn more` link

## Confirmed `https://support.brave.com/hc/en-us/categories/20990938292237-Brave-Leo` loaded in a new tab

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="1312" alt="Screen Shot 2024-06-05 at 2 31 17 PM" src="https://github.com/brave/brave-browser/assets/387249/cf6719f1-bbbf-4a62-912c-4c9e30d290be"> | <img width="1312" alt="Screen Shot 2024-06-05 at 2 31 34 PM" src="https://github.com/brave/brave-browser/assets/387249/6d975bc6-602e-49be-9e53-cc995845a202"> | <img width="1312" alt="Screen Shot 2024-06-05 at 2 31 44 PM" src="https://github.com/brave/brave-browser/assets/387249/d5c9c58f-b251-4db1-b770-16e53fc7f596"> | <img width="1312" alt="Screen Shot 2024-06-05 at 2 31 50 PM" src="https://github.com/brave/brave-browser/assets/387249/1a1aa267-c0ea-4311-9a21-7d4b99fa7efa"> | <img width="1312" alt="Screen Shot 2024-06-05 at 2 31 56 PM" src="https://github.com/brave/brave-browser/assets/387249/a499e0c6-62f0-4540-8be3-b506ab0d2bdb">

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.67.112`

- Confirmed click on `Learn more` link redirects to https://support.brave.com/hc/en-us/categories/20990938292237-Brave-Leo loaded in a new tab

Example | Example | Example | Example
----------|-----------|----------|---------
![Screenshot_20240611_174611](https://github.com/brave/brave-browser/assets/38657976/e71e2e07-c5fd-41e9-86a7-ede40936608f) | ![Screenshot_20240611_174625](https://github.com/brave/brave-browser/assets/38657976/91c4e851-ed7c-4f25-beb9-c980c41dd56d) | ![Screenshot_20240611_174727](https://github.com/brave/brave-browser/assets/38657976/1bb62e82-0250-4efc-8819-64badac29873) | ![Screenshot_20240611_174740](https://github.com/brave/brave-browser/assets/38657976/c758c999-59cc-4b66-b0d0-3731f1484490)
