### ISSUE TITLE
Remove `Translate...` from the application menu

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#38707]
### Description

Remove `Translate...` from the application (hamburger) menu as it's not hooked up to the translation UI in the url bar.

### Steps to reproduce

1. Use 1.68.60 Chromium: 126.0.6478.26 
2. Open application/hamburger menu
3. Notice the Translate option is greyed out and is not functional

### Actual result

<img width="320" alt="Screenshot 2024-05-30 at 1 20 42 PM" src="https://github.com/brave/brave-browser/assets/5951041/505c2daf-cdce-48b7-afc9-72fd1683f463">

### Expected result

Should appear like this:

<img width="425" alt="Screenshot 2024-05-30 at 1 21 23 PM" src="https://github.com/brave/brave-browser/assets/5951041/c91ec122-625e-4a7d-8f65-12fe84a6ec17">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.x w/ CR126

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.67.105` or higher for `1.67.x` verification 👍
