### ISSUE TITLE
Webcompat reports should have browser version

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#38714]
### Description

We currently parse the browser version from the User Agent. This doesn't work on Android or iOS, and requires us to do a mapping between Chromium version and Brave Core version on the webcompat reporter backend. 
Version information is very important for debugging webcompat issues since we can track when users started seeing issues and check if a hotfix worked.

We should send the full browser version (e.g. 1.68.40) in webcompat reports for all platforms. 

Note 1: this will require updating https://github.com/brave/brave-browser/wiki/Web-compatibility-reports. 
Note 2: https://github.com/brave/brave-browser/issues/38713 is the issue for iOS

### Steps to reproduce

Go to the webcompat reporter dashboard and see the `version`.

### Actual result

Version is the Chromium version for Desktop, empty for Android and OS version for iOS.

### Expected result

We should simply send and report the brave-core version (1.68.40).

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

All

### Android device

All

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by ShivanKaul** [comment]
cc @DJAndries

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.69.108 Chromium: 127.0.6533.43 (Official Build) nightly (x86_64)
-- | --
Revision | d5e7dd710a027aa197965d0603ec587791be032e
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.69.108`
2. launched Brave
3. loaded `gregdonner.org`
4. clicked on the Shields icon
5. clicked to set Shields to `Disabled`/`Off`
6. clicked on `Report Site`
7. entered `Just a test for https://github.com/brave/brave-browser/issues/38714`
8. entered my @brave.com email address
