### ISSUE TITLE
Do not request randomness server info if P3A is disabled

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#38712]
Steps to reproduce:

1. Create a new profile.
2. Start the browser with that profile, disable all data collection in `brave://settings/privacy`.
3. Close the browser.
4. Start a local mitmproxy: `mitmproxy --mode socks5 --listen-port 9000`
5. Start the browser with that proxy: `brave-browser-stable --user-data-dir=/home/francois/brave-temp-profile --proxy-server="socks5://localhost:9000"`
6. Wait for the startup requests to show up in mitmproxy.

![Screenshot from 2024-05-30 14-18-37](https://github.com/brave/brave-browser/assets/167821/03851365-393a-4a41-b75e-72294483777f)

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.70.51 Chromium: 127.0.6533.88 (Official Build) nightly (64-bit)
-- | --
Revision | c39ff5a89233f396d214b305233de91ff13a8b9e
OS | Windows 10 Version 22H2 (Build 19045.4651)
```
Verified the test plan from https://github.com/brave/brave-core/pull/24516

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung Galaxy A52s 5G version 12` running `Bravemonoarm64.apk_1.70.92`
