### ISSUE TITLE
iOS webcompat reports should include app version

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#38713]
### Description

See https://metabase.bsg.brave.com/question/2089-stats-webcompat-reports-table?domain=989.blackbaudhosting.com, the `version` column shows OS version instead of app version. This is because the backend infers the OS version from the User Agent, but has no way of getting the app version. 

We should send the app version in webcompat reports. Make sure to update the [wiki](https://github.com/brave/brave-browser/wiki/Web-compatibility-reports) too.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` and `iPad (7th Gen)` running `iOS 17.5.1` using version `1.69 (156)`

 - Ensured that app version is sent in webcompat report - https://webcompat.brave.com/1/webcompat

 iPhone  | iPad
 -|-
![Screenshot 2024-08-27 at 10 52 02 AM](https://github.com/user-attachments/assets/137dd697-85d4-4160-a8fb-8061835e5129) | ![Screenshot 2024-08-27 at 11 02 27 AM](https://github.com/user-attachments/assets/387a2020-f3c1-48ff-a262-f4fcc5e41d9d)
