### ISSUE TITLE
Failed to load on Ubuntu

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#3873]
## Description 
Loaded OK but then I get:
```
~$ sudo apt install brave-keyring brave-browser
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package brave-browser
```

## Steps to Reproduce
I used from your Ubuntu page: 

```
curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
OK
```

## Actual result:
As above I get:

```
~$ sudo apt install brave-keyring brave-browser
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package brave-browser
```

### Additional Information
I just updated to Ubuntu 18.04.2 LTS

**Comment by srirambv** [comment]
Can you try `sudo apt-get clean && apt-get update` and then try reinstalling?

**Comment by knucklas** [comment]
Thanks. It looked OK at first but ended up: 
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
xxxxx:~$ curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
OK
echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ $UBUNTU_CODENAME main" | sudo tee /etc/apt/sources.list.d/brave-browser-release-${UBUNTU_CODENAME}.list
deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ bionic main
xxxxx:~$ 
sudo apt update
Hit:1 http://mirror.netcologne.de/ubuntu bionic InRelease
Hit:2 http://mirror.netcologne.de/ubuntu bionic-updates InRelease        
Hit:3 http://mirror.netcologne.de/ubuntu bionic-backports InRelease      
Hit:4 http://mirror.netcologne.de/ubuntu bionic-security InRelease             
Hit:5 https://brave-browser-apt-release.s3.brave.com bionic InRelease          
Reading package lists... Done                                                  
Building dependency tree       
Reading state information... Done
7 packages can be upgraded. Run 'apt list --upgradable' to see them.
xxxxx:~$ 
xxxxx:~$ sudo apt install brave-keyring brave-browser
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package brave-browser

**Comment by knucklas** [comment]
Don't know where those cross-outs came from!

**Comment by fmarier** [comment]
@knucklas Can you tell me what files you've got in the `/etc/apt/sources.list.d/` directory?

**Comment by knucklas** [comment]
I have these:
/etc/apt/sources.list.d/brave-browser-release-bionic.list
/etc/apt/sources.list.d/brave-xenial.list
/etc/apt/sources.list.d/brave-xenial.list.distUpgrade

**Comment by fmarier** [comment]
Since you are on Ubuntu 18.04, then you can delete these old files:

* `/etc/apt/sources.list.d/brave-xenial.list`
* `/etc/apt/sources.list.d/brave-xenial.list.distUpgrade`

and then do `sudo apt update`.

What do you get if you run `apt-key list`?

Finally, can you then paste the contents of `/etc/apt/sources.list.d/brave-browser-release-bionic.list`?

**Comment by knucklas** [comment]
Thanks, but would you believe, my Ubuntu system has collapsed! I'll respond when I get it back.

**Comment by knucklas** [comment]
Back up again!
1. Cannot delete "permission denied"
2. seems to work
3. xx@Ubuntu2:~$ apt-key list
/etc/apt/trusted.gpg
--------------------
pub   rsa2048 2017-02-01 [SC] [expires: 2025-01-30]
      5AB4 CA7A C2F9 3FE3 EBD6  082D 6ED1 9DBB 448E EE6C
uid           [ unknown] Brave Software (We're reinventing the browser as a user-first platform for speed and privacy) <support@brave.com>
sub   rsa2048 2017-02-01 [E] [expires: 2025-01-30]

/etc/apt/trusted.gpg.d/brave-browser-release.gpg
------------------------------------------------
pub   rsa4096 2018-10-15 [SC] [expired: 2019-04-13]
      D8BA D4DE 7EE1 7AF5 2A83  4B2D 0BB7 5829 C2D4 E821
uid           [ expired] Brave Software <support@brave.com>

/etc/apt/trusted.gpg.d/ubuntu-keyring-2012-archive.gpg
------------------------------------------------------
pub   rsa4096 2012-05-11 [SC]
      790B C727 7767 219C 42C8  6F93 3B4F E6AC C0B2 1F32
uid           [ unknown] Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>

/etc/apt/trusted.gpg.d/ubuntu-keyring-2012-cdimage.gpg
------------------------------------------------------
pub   rsa4096 2012-05-11 [SC]
      8439 38DF 228D 22F7 B374  2BC0 D94A A3F0 EFE2 1092
uid           [ unknown] Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>

/etc/apt/trusted.gpg.d/ubuntu-keyring-2018-archive.gpg
------------------------------------------------------
pub   rsa4096 2018-09-17 [SC]
      F6EC B376 2474 EDA9 D21B  7022 8719 20D1 991B C93C
uid           [ unknown] Ubuntu Archive Automatic Signing Key (2018) <ftpmaster@ubuntu.com>

4. # deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ bionic main

How's that?
PS I see you are the only program that appears in the Software updater settings other than canonical etc.

**Comment by knucklas** [comment]
By the way, now removed those 2 files.

**Comment by fmarier** [comment]
Ok, now try installing again using these commands:

```
sudo apt update
sudo apt install brave-keyring brave-browser
dpkg -l 'brave-*'
```

and please copy the output of all of this here.

**Comment by knucklas** [comment]
This is the result:
xxx@Ubuntu2:~$ sudo apt update
Hit:1 http://mirror.netcologne.de/ubuntu bionic InRelease
Hit:2 http://mirror.netcologne.de/ubuntu bionic-updates InRelease
Hit:3 http://mirror.netcologne.de/ubuntu bionic-backports InRelease
Hit:4 http://mirror.netcologne.de/ubuntu bionic-security InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
10 packages can be upgraded. Run 'apt list --upgradable' to see them.
xxx@Ubuntu2:~$ sudo apt install brave-keyring brave-browser
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package brave-keyring
E: Unable to locate package brave-browser
xxx@Ubuntu2:~$ dpkg -l 'brave-*'
dpkg-query: no packages found matching brave-*

**Comment by knucklas** [comment]
Not my crossing outs!

**Comment by knucklas** [comment]
My system might still be a bit of a mess. I intend to do a re-install.

**Comment by fmarier** [comment]
Ok, it looks like you don't have the Brave repository installed.

Try going through the 5 steps on https://brave-browser.readthedocs.io/en/latest/installing-brave.html#ubuntu-16-04-and-mint-18 again one by one.

**Comment by yearmfew** [comment]
```
yearmfew@Vefa:~$ sudo apt install brave-keyring brave-browser
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package brave-browser
yearmfew@Vefa:~$ dpkg -l 'brave-*'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  brave-keyring  1.3          all          Brave Browser keyring and reposit

```

I have tried the same. But it gives the same error 

`E: Unable to locate package brave-browser`

**Comment by fmarier** [comment]
@yearmfew Are you using a 64-bit machine? What's the output of `uname -a`?

**Comment by yearmfew** [comment]
@fmarier No I am using 32-bit machine.

**Comment by bsclifton** [comment]
@yearmfew we don't support 32 bit Linux unfortunately. It might be possible to get things working from source, but I'm not aware of anyone that has done that

**Comment by AliOfficial** [comment]
> ```
> yearmfew@Vefa:~$ sudo apt install brave-keyring brave-browser
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package brave-browser
> yearmfew@Vefa:~$ dpkg -l 'brave-*'
> Desired=Unknown/Install/Remove/Purge/Hold
> | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
> |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
> ||/ Name           Version      Architecture Description
> +++-==============-============-============-=================================
> ii  brave-keyring  1.3          all          Brave Browser keyring and reposit
> ```
> 
> I have tried the same. But it gives the same error
> 
> `E: Unable to locate package brave-browser`

I have Ubuntu 19.10 and the same trouble. Is there any solution?

**Comment by gregbenner** [comment]
E: Failed to fetch https://brave-browser-apt-release.s3.brave.com/dists/eoan/InRelease  403  Forbidden [IP: 151.101.126.217 443]
E: The repository 'https://brave-browser-apt-release.s3.brave.com eoan InRelease' is not signed.

**Comment by gregbenner** [comment]
without having to build brave yourself you can https://github.com/brave/brave-browser/releases
seems like only nightly is built https://github.com/brave/brave-browser/releases/download/v0.73.25/brave-browser-nightly_0.73.25_amd64.deb

**Comment by fmarier** [comment]
@gregbenner For problems running Brave on Ubuntu 19.10, see https://github.com/brave/brave-browser/issues/6522#issuecomment-545672208.

**Comment by fmarier** [comment]
Going to close this old issue since the original reporter is no longer on GitHub and we haven't seen similar problems lately.
