### ISSUE TITLE
[CR 126] `Switch to this tab` button should be rounded

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#38731]
### Description

Due to CR 126, the `Switch to this tab` button is squared off. The `Switch to this tab button` should be rounded at the corners with more of square/circle shape.

### Steps to reproduce

1. Use 1.68.x with CR 126
2. Open a few web sites.
3. Type in the a url from step 2 to in a different tab to invoke the `Switch to this tab` button

### Actual result

<img width="377" alt="Screenshot 2024-05-30 at 9 37 00 PM" src="https://github.com/brave/brave-browser/assets/5951041/0d9ebed6-bfe5-40ac-83a6-cd85ccc56c01">

### Expected result

<img width="483" alt="Screenshot 2024-05-30 at 9 36 44 PM" src="https://github.com/brave/brave-browser/assets/5951041/ce4604b5-7d74-44ae-97d5-0568d0795b70">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.x and higher with CR 126

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by simonhong** [comment]
checking..

**Comment by simonhong** [comment]
@rebron Do we want to revert radius only?
It seems its border color and text colors are also changed.

**Comment by kjozwiak** [comment]
The above requires `1.67.105` or higher for `1.67.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.67.107 Chromium: 126.0.6478.26 (Official Build) beta (x86_64)
-- | --
Revision | 2831369c7540d93e98f38d9b463f6762430a7982
OS | macOS Version 13.6.7 (Build 22G720)
```
