### ISSUE TITLE
[Wallet/iOS] Update NFT balance fetching and NFT metadata fetching APIs

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#38738]
Once https://github.com/brave/brave-core/pull/23759 is merged. We will need to update APIs to 
1. fetch NFT balance
2. fetch NFT metadata
3. Integrate `MakeBubbleGumProgramTransferTxData`

A sanity test is needed by the QA team to make sure NFT is working as expected after the update.

**Comment by neehhaa06** [comment]
## Update Fetch NFT Balance API

> Change endpoint URL.
> Adjust request parameters.

> Update Fetch NFT Metadata API

> Change endpoint URL.
> Adjust request parameters.

> Integrate NFT Transfer Data

> Use MakeBubbleGumProgramTransferTxData in the transfer process. 

func createNFTTransferTransaction(sender: String, recipient: String, nftID: String, completion: @escaping (Result<Transaction, Error>) -> Void) { ... }

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18 running 1.71 (117)
- Verified steps from [brave/brave-core#25051](https://github.com/brave/brave-core/pull/25051)
- Verified able to fetch NFT balance for compressed NFT
- Verified able to send Compressed NFT from one account to another account

https://github.com/user-attachments/assets/3254c66f-616f-4efd-bb0f-8c9fa8cb35d9
