### ISSUE TITLE
[iOS] Update Leo opt-in text

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#38742]
```[tasklist]
### Tasks
- [ ] New copy in master doc here: https://docs.google.com/document/d/1TRDiN5r1f2OCwtjxcDq7RlG192e3t7s7z3KTDGX6Ous/edit
```
Also, we're missing an 'X' or cancel option to close the Opt-in text box. Upon closing or cancelling the user must remain in the opt-out state.

**Comment by anthonypkeane** [comment]
The opt-in notice is massive, and in my view, not very user-friendly. I recommend reducing its size by about 80% and adding a “Learn More” button where users can get more context if they wish.

Have you tested it on a mobile screen to see how large this opt-in appears? I’m guessing it occupies more than one full screen.

**Comment by kjozwiak** [comment]
The above requires `1.68.112` or higher for `1.68.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6
Brave build: 1.68 (115)
BraveCore: 1.68.115 (127.0.6533.26)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/38742#issue-2328166973
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the new Leo opt-in text is the same as mentioned in https://docs.google.com/document/d/1TRDiN5r1f2OCwtjxcDq7RlG192e3t7s7z3KTDGX6Ous/edit#heading=h.h2mv1xec7bsq
- Verified that the `Help Center` and `privacy policy` links are working and opening https://support.brave.com/hc/en-us/categories/20990938292237-Brave-Leo and https://brave.com/privacy/browser/#brave-leo respectively
- Verified that the `Close` button is working, tapping it cancels the opt-in flow and starts it from the beginning the next time a user opens `Leo`

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/9aa27b80-f4b2-44de-9ecc-71ae72a1a4ac) | ![2](https://github.com/brave/brave-browser/assets/128532965/ab64b912-26c0-416c-8966-c548bee2a85f) | ![3](https://github.com/brave/brave-browser/assets/128532965/d87d116a-53d6-4aea-9bec-6d40b81ad27e) | ![4](https://github.com/brave/brave-browser/assets/128532965/c947116d-0988-451c-a029-f678223e21ab) |

https://github.com/brave/brave-browser/assets/128532965/fc06ee5f-1a1b-4fb5-8af4-61cc15ea8a47
