### ISSUE TITLE
Support Stacked Mode in Split View

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#38740]
### Description

Split View currently supports views side-by-side; we should consider stacked views too. Like many folks, I have a combination of monitors in portrait mode and landscape mode. Split View currently works well in landscape mode, but can be a bit uncomfortable in portrait mode due to reduced lateral space.

### Steps to reproduce

Use _split view_ on a narrow/tall monitor.

![split-view-fighters](https://github.com/brave/brave-browser/assets/815158/fd60aea2-f67e-4bee-aec7-d5e0ac5dbfbe)

### Actual result

On a 1080x1920 monitor, each frame will have at most 540 pixels of width. This assumes no sidebar is open in the browser. On Windows this can be even less given the behavior of scrollbars on pages.

### Expected result

Stacked mode would give each frame full-width, enabling a more comfortable experience in portrait mode.

### Brave version (brave://version info)

1.68.61 Chromium: 126.0.6478.26 (Official Build) nightly (64-bit)

**Comment by aguscruiz** [comment]
Added design here.
https://www.figma.com/design/Dt0iJdVaaAj7DikWLO1P7I/Split-view-%2F-Sidebar-browsing?node-id=2173-10163&t=qkjJooFRXhLF4Y6X-1

Also changes contextual menu items:
- Added  "Horizontal split" when in vertical mode / "Vertical split" in horizontal mode. 

![image](https://github.com/brave/brave-browser/assets/15734630/f06e1bd8-2b9b-4877-a014-3b1def859e15)

**Comment by LaurenWags** [comment]
reverted via https://github.com/brave/brave-core/pull/24420
