### ISSUE TITLE
AIChat: Leo tools a11y and string bug 

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#38747]
### Description

- add tooltip on leo tools for a11y
- missing space in one of the slash tools items' string

### Steps to reproduce

open sidepanel and click on ai chat and hover your mouse on the "slash" icon

### Actual result

no tooltip is shown

### Expected result

show a native tooltip explaining what the action means

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

1.68.0 Chromium: 126.0.6478.26 (Developer Build) (arm64) 

### Android device

all

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.67.105` or higher for `1.67.x` verification 👍

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240426.023.B4 release-keys
Brave build: 1.67.105
Chromium: 126.0.6478.26 (Official Build) beta (64-bit) 
```
---------------------------
<details>
<summary> add tooltip on leo tools for a11y </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>

<details>
<summary> Missing "space" in one of the "slash" tools items' string </summary>

**STEPS:**
1. Install and launch Brave `1.67.105`
2. Open `Leo`
3. Tap `/` in the bottom left corner
4. Scroll down and find `Change tone / Expand` > *Verify*

**ACTUAL RESULTS:**
- Verified that the string `Change tone / Expand` is spelled correctly
- Verified other strings in the `/` menu for regression

---------------------------

|Bug|Fix|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/079f3bd7-3761-4972-b3d7-05fa4798f03e) | ![2](https://github.com/brave/brave-browser/assets/128532965/f81b5324-1c87-4eb4-9467-33518c054ba7) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/4e69d0df-8820-44fc-9864-ef9262d2e01d) | ![2](https://github.com/brave/brave-browser/assets/128532965/2225d841-7d75-46bc-bf76-806122caa13c) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/165012a2-a7a9-418f-90a8-f6b84bcde02b) | ![2](https://github.com/brave/brave-browser/assets/128532965/c251e764-a28e-4599-a894-f9c8d0d1f6ff) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/c9f244a8-562b-47b7-b328-142920c1d33a) | ![2](https://github.com/brave/brave-browser/assets/128532965/fbf61180-b184-4e96-9f52-8aada4f4f951) |
</details>

**Comment by stephendonner** [comment]
## Verified `PASSED` using


Brave | 1.67.107 Chromium: 126.0.6478.26 (Official Build) beta (x86_64)
-- | --
Revision | 2831369c7540d93e98f38d9b463f6762430a7982
OS | macOS Version 11.7.10 (Build 20G1427)

`Leo tools` | `Change tone / Expand`
------------|------------------------
<img width="369" alt="Screen Shot 2024-06-05 at 2 14 50 PM" src="https://github.com/brave/brave-browser/assets/387249/664ab4d2-fa39-44d7-ab2d-79be7af0f5e6"> | <img width="383" alt="Screen Shot 2024-06-05 at 2 15 14 PM" src="https://github.com/brave/brave-browser/assets/387249/0ff315b7-4362-45e7-8392-f34b73774fb4">
