### ISSUE TITLE
Update Leo opt-in text

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#38741]
```[tasklist]
### Tasks
- [ ] New copy in master doc here: https://docs.google.com/document/d/1TRDiN5r1f2OCwtjxcDq7RlG192e3t7s7z3KTDGX6Ous/edit
```

Also, we're missing an 'X' or cancel option to close the Opt-in text box. Upon closing or cancelling the user must remain in the `opt-out` state.

**Comment by anthonypkeane** [comment]
The opt-in notice is massive, and in my view, not very user-friendly. I recommend reducing its size by about 80% and adding a “Learn More” button where users can get more context if they wish.

Have you tested it on a mobile screen to see how large this opt-in appears? I’m guessing it occupies more than one full screen.

**Comment by aguscruiz** [comment]
Added the designs for desktop and android here, with the close button:

### Desktop
https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/Leo?node-id=15-12393&t=3FvcJcAX8Md9hH9F-1

### Android
https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/Leo?node-id=3969-66835&t=3FvcJcAX8Md9hH9F-1

### iOS (but maybe we need another issue for that)
https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/Leo?node-id=3969-66716&t=3FvcJcAX8Md9hH9F-1

---------------------------
> The opt-in notice is massive, and in my view, not very user-friendly. I recommend reducing its size by about 80% and adding a “Learn More” button where users can get more context if they wish.
> 
> Have you tested it on a mobile screen to see how large this opt-in appears? I’m guessing it occupies more than one full screen.

Yes, it takes more than 1 screen, it's long. I added inner scroll for it. But I don't know if it's up to us to reduce it.

**Comment by aguscruiz** [comment]
@mattmcalister that's something to note, on android and iOS y had to tweak the design to add an inner scroll area. We should update it in the apps too
