### ISSUE TITLE
Add note in saved password or during save password modal

### ISSUE THREAD

**Issue by golu7679** [brave/brave-browser#38758]
### Platforms

all

### Description

X

**Comment by rebron** [comment]
Hi @golu7679. If you want to add a note to a password, you can already do that. If you go to the password manager for each site you should be able to see it or in the password dialog too. Hope that helps.
 
<img width="319" alt="Screenshot 2024-06-05 at 9 29 11 PM" src="https://github.com/brave/brave-browser/assets/5951041/e809d5e2-defb-401c-a92a-cc6325f133c1">
