### ISSUE TITLE
Add iOS News MAU/DAU metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#38769]
Add the following metrics on iOS:

`Brave.Today.UsageMonthly`
`Brave.Today.UsageDaily`

cc @LorenzoMinto @brave/ios

**Comment by LorenzoMinto** [comment]
@kylehickinson @DJAndries any chance we could uplift this? So it's out with 1.68

**Comment by kylehickinson** [comment]
Uplift created: https://github.com/brave/brave-core/pull/24366
