### ISSUE TITLE
The IOS version of the browser filter can only add three custom lists

### ISSUE THREAD

**Issue by HX-Technology-LLC** [brave/brave-browser#38761]
### Description

The IOS version of the browser filter can only add three custom lists，If try to add four lists, it will automatically exit when the URL of the fourth is entered.

### Steps to reproduce

1. open ios browser
2. go to setting menu
3. go to shields option
4. go to Filter option
5. press add custom list
6. add more than four list

### Actual result

When you try to add the fourth list, the keyboard hides itself and you will return to the list screen.

### Expected result

Add more lists normally

### Reproduces how often

Easily reproduced

### Brave version

latest appstore version

### Device/iOS version

iPhone 15 Pro
IOS 17.4.1

### Affected browser versions

- [X] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by cuba** [comment]
Cannot reproduce this:
![Simulator Screenshot - iPhone 14 Pro - 2024-07-24 at 14 35 47](https://github.com/user-attachments/assets/b28fc516-ced2-4d31-871a-5056c93407b4)
@HX-Technology-LLC Could you provide some additional details or verify this again?
