### ISSUE TITLE
[ads] Keep deposit values for 7 days after the campaign expiry date

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#38766]
### Description

Keep deposit values for 7 days after the campaign expiry date

**Comment by btlechowski** [comment]
Verified with

Brave | 1.68.94 Chromium: 126.0.6478.114 (Official Build) beta (64-bit)
-- | --
Revision | 8981faf58380240eab6e999e6bf06f9ed9314336
OS | Linux


Verified test plan from https://github.com/brave/brave-core/pull/23959


<details>



</details>
