### ISSUE TITLE
[CR 126] Use proper bookmark icon in the url bar instead of Star icon

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#38765]
### Description

With CR126, the star icon is being used in the URL bar. It should be using the bookmark icon.

### Steps to reproduce

1. Use 1.68.x with CR 126.
2. Have a few items bookmarked and type down parts of the url to open up the bookmark suggestions drop down.
3. Notice the star icon for favorites when it should be the bookmark icon.

### Actual result

<img width="173" alt="Screenshot 2024-06-02 at 8 34 41 PM" src="https://github.com/brave/brave-browser/assets/5951041/95b6c48b-004b-485a-90ed-2f33a05f43e7">

The wrong star icon also flows through the NTP search widget:
<img width="157" alt="Screenshot 2024-06-02 at 8 39 03 PM" src="https://github.com/brave/brave-browser/assets/5951041/e8c1e863-f093-4d8d-b072-0ae4e8e983cf">

### Expected result

<img width="226" alt="Screenshot 2024-06-02 at 8 35 40 PM" src="https://github.com/brave/brave-browser/assets/5951041/333519e0-2e52-41b8-9273-2ab14b3b0080">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.x with CR126

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by simonhong** [comment]
checking
