### ISSUE TITLE
[CR 126] Tune and search icons are rounded and not squared

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#38763]
### Description

The tune and search icons in the url bar are rounded and should be squared off (squircle) in shape. Light and dark themes are ok, other colors such as blue, red, and green are not.

### Steps to reproduce

1. Create a new profile with 1.68.x and CR126 with a theme that's not light or dark theme defaults.
2. Notice the search icon is circle.
3. Enter a url and go to that page. Notice the tune icon is rounded.

### Actual result

![screenshot_2024-06-02_at_09 24 25_720](https://github.com/brave/brave-browser/assets/5951041/493d45e4-0601-4101-abc0-c66aab3e8e52)
<img width="84" alt="Screenshot 2024-06-02 at 8 03 27 PM" src="https://github.com/brave/brave-browser/assets/5951041/ab59ed03-f1d4-4f56-86ec-85a176691db8">
<img width="145" alt="Screenshot 2024-06-02 at 8 03 33 PM" src="https://github.com/brave/brave-browser/assets/5951041/d102ab79-a018-4408-9948-6a17386b8877">

### Expected result

<img width="168" alt="Screenshot 2024-06-02 at 8 06 44 PM" src="https://github.com/brave/brave-browser/assets/5951041/f3bc2e5d-0666-4588-8253-f66272e029b0">
<img width="137" alt="Screenshot 2024-06-02 at 8 07 07 PM" src="https://github.com/brave/brave-browser/assets/5951041/999ce17b-f541-4086-a47c-31cebb19ca07">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.x with CR 126

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by simonhong** [comment]
checking..

**Comment by kjozwiak** [comment]
The above requires `1.67.105` or higher for `1.67.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.67.107 Chromium: 126.0.6478.26 (Official Build) beta (x86_64)
-- | --
Revision | 2831369c7540d93e98f38d9b463f6762430a7982
OS | macOS Version 13.6.7 (Build 22G720)
```
