### ISSUE TITLE
[Android] Parallel downloading setting

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#38772]
### Description
Expose the parallel downloading flag as a Brave setting.
brave://flags/#enable-parallel-downloading

### Requirements
- Title: Parallel Downloading
- Description: Enable parallel downloading to accelerate download speed.
- Location: settings --> downloads
- Default state: enabled

### Why
This setting might resonate with the India market. More context here:
https://bravesoftware.slack.com/archives/C0717QSFCGN/p1717187617214489

**Comment by kjozwiak** [comment]
The above requires `1.70.86` or higher for `1.70.x` verification 👍

**Comment by Uni-verse** [comment]
In progress on `Samsung Galaxy S21` using version: 

```
Brave	1.70.101 Chromium: 128.0.6613.120 (Official Build) beta (64-bit) 
Revision	dc28ab38d07e9fa668801884c0c55f669ce538eb
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using version: 

```
Brave	1.70.107 Chromium: 128.0.6613.120 (Official Build) beta (64-bit) 
Revision	ab3f504ca4a15c330f60a93d5e3773d780498980
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Ensured that `Parallel Downloading` setting is shown under Settings -> Downloads and is enabled by default on for new users. 
- Ensured that `brave://flags#enable-parallel-downloading` is showing the correct state. 
- Ensured webpages can be downloaded and show up in Downloads.
- Ensured `Parallel Downloading` can be disabled/enabled and restart dialog is shown.
- Ensured setting state is not changed after multiple browser relaunches.

Example | Example | Example | Example
-|-|-|-
<img width="736" alt="Screenshot 2024-09-11 at 11 11 36 AM" src="https://github.com/user-attachments/assets/f0dfb03b-3fe4-41a6-9c72-d5c0087aa483"> | <img width="735" alt="Screenshot 2024-09-11 at 11 12 19 AM" src="https://github.com/user-attachments/assets/0a45b87e-dd21-454e-aef6-7b79758676d8"> | <img width="735" alt="Screenshot 2024-09-11 at 11 12 41 AM" src="https://github.com/user-attachments/assets/62965adf-843e-4809-a1e9-30fe504950b5"> | <img width="735" alt="Screenshot 2024-09-11 at 11 13 03 AM" src="https://github.com/user-attachments/assets/336789a0-5555-4cdc-9df1-b221ed44026f">


- Ensured disabling `brave://flags#enable-parallel-downloading` and upgrading the app (1.69.130 -> 1.70.107) will retain the setting. 
- Ensured `Parallel Downloading` can be enabled in Downloads settings page after its been disabled for existing users. 

Example | Example | Example | Example
-|-|-|-
<img width="735" alt="Screenshot 2024-09-11 at 11 13 03 AM" src="https://github.com/user-attachments/assets/8c4cbe15-7bb2-427d-bf72-6126654e18c9"> | <img width="736" alt="Screenshot 2024-09-11 at 11 17 14 AM" src="https://github.com/user-attachments/assets/8c16e3f7-fe8b-4076-961f-ada9a9344249"> | <img width="736" alt="Screenshot 2024-09-11 at 11 17 25 AM" src="https://github.com/user-attachments/assets/62333a66-f37d-4b82-9c47-3aa7bb37ec72"> | <img width="736" alt="Screenshot 2024-09-11 at 11 21 49 AM" src="https://github.com/user-attachments/assets/226fef33-20d1-4db2-8230-f6d4d37e9497">
