### ISSUE TITLE
Disabling `Close window when closing last tab` breaks `Bring all tabs to this window` functionality.

### ISSUE THREAD

**Issue by TEMP-ad** [brave/brave-browser#38779]
### Description

When you disable `Close window when closing last tab` (brave://settings/system) and try to use `Bring all tabs to this window`, the functionality of bringing new tabs will work, but it will not close those tabs even if they are not _the last tab in the last window_ for the window to stay opened.

This means since it will leave windows with a new tab behind instead of closing them normally because they are not the _last tab_ you will end up with many windows opened, and you have to close them all manually anyway.

I recorded a video showing the issue, and how the expected behavior should be just like when I closed the window manually, because there is no 'last tab' yet, so the problem with how Bring all tabs to this window is doing stuff on the background to bring the tabs which messed with the whole other feature, so those two features are conflicting even if technically they shouldn't.

### Steps to reproduce

1. go to brave://settings/system and make sure `Close window when closing last tab` is disabled
2. create a new window and right click any tab to use `Bring all tabs to this window` button.
3. the _other_ window doesn't get closed and leaves a normal new tab behind.

### Actual result

https://github.com/brave/brave-browser/assets/156715894/79d1f0ef-4d3f-4155-aedf-aacd62cf346d

### Expected result

- All windows but the one where `Bring all tabs to this window` is used gets closed.
- No windows with new tabs left behind.
- Window doesn't get closed only when it is really the real very last one.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.70 Chromium: 126.0.6478.26 (Official Build) nightly (64-bit) 
Windows 11 Version 23H2 (Build 22631.3672)

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by TEMP-ad** [comment]
@sangwoo108 I didn't know you also implemented `Bring all tabs to this window` so I will tag you, so you know about this misbehavior.
As usual you not anybody got assigned, tagged or anything to do something about real issues. So I guess I am forced to tag you to force these types of issues to actually get somewhere, I wish I didn't have to.

Thank you for caring about my reports, Have a nice day!

**Comment by sangwoo108** [comment]
Thank you for reporting! Let me take a look

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.69.95 Chromium: 127.0.6533.26 (Official Build) nightly (64-bit)
-- | --
Revision | ef586bb495b8e8353315768cbc905b14079fbf0f
OS | Windows 10 Version 22H2 (Build 19045.4651)
```
