### ISSUE TITLE
Enable Bitcoin by default on iOS

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#38775]
### Platforms

iOS

### Description

Issue to enable Bitcoin by default on iOS.

Security/privacy review: https://github.com/brave/reviews/issues/1625

Meta ticket for tracking all Bitcoin iOS work: https://github.com/brave/brave-browser/issues/32722
Summary:
- Setup core services for Bitcoin on iOS (v1.67+): https://github.com/brave/brave-core/pull/22632
- Bitcoin account creation (v1.67+): https://github.com/brave/brave-core/pull/22737
- Bitcoin Balance Fetching (v1.67+): https://github.com/brave/brave-core/pull/23117
- Pending Balance Details Modal (v1.67+): https://github.com/brave/brave-core/pull/23307
- Creating & Displaying BTC Transactions (v1.68+): https://github.com/brave/brave-core/pull/23476
    - Can be uplifted if passed security / privacy review before v1.67 release
- iOS front-end support for Bitcoin account import (v1.68+): https://github.com/brave/brave-browser/issues/38546
    - Could be uplifted but will require uplift of core PR: https://github.com/brave/brave-core/pull/23729

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.0 running 1.69 (147)
- Verified steps from issue description
- Verified Bitcoin account is enabled by default
- Verified both Bitcoin Mainnet and Testnet accounts is enabled by default
- Verified balance is fetched for both mainnet and testnet

https://github.com/user-attachments/assets/baae4257-909f-409c-949e-02da29da2aa4
