### ISSUE TITLE
Action Extension not triggering for txt file

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-browser#38774]
### Description

Action Extension doesnt trigger Brave and do desired action for txt files. Brave supports urls and text under "Open in Brave" action inside Share Sheet. The action should open Brave and open the text file if user can access this file using Brave, if not the search engine should be triggered.

### Steps to reproduce

1. Open Files app and try to share a txt file
2. Click Open in Brave action
3. Confirm Brave is opened and desired action is performed

### Actual result

Nothing happens the Brave is not triggered.

https://github.com/brave/brave-browser/assets/6643505/f9445ee3-88a2-4efa-919c-9cc08e9f2ba5

### Expected result

The Brave should be triggered and desired action should be performed. 

### Reproduces how often

Easily reproduced

### Brave version

Any

### Device/iOS version

Any

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.6.1
- iPad Air / iPadOS 16.7.2
Brave build: 1.69 (162)
BraveCore: 1.69.162 (128.0.6613.120)
```
Filed follow-up issue #40842
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/23969#issue-2331769044
2. *Verify*

**ACTUAL RESULTS:**
- Verify that Brave must be launched and desired `*.txt` file must be opened in Brave.
- Observed that Brave crashed when using `Open in Brave` to open a `*.txt` file if Brave is closed before doing this action.

---------------------------

https://github.com/user-attachments/assets/8f971b5a-150c-4dc3-8213-fec592e8f5a6
