### ISSUE TITLE
[iOS] - Support Multi-Device Skus Payments

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#38788]
### Platforms

iOS

### Description

- iOS should support multi-device. If you purchase AI-Chat on one device, it should automatically show up on another device.
- If you purchase Leo on one device, and then install the browser on another device, it should automatically restore all purchased subscriptions.

**Comment by hffvld** [comment]
Marking this as `QA/No` based on an offline conversation with @Brandon-T. The above issue will be covered by verifying **[iOS] - Temporarily disable Apple MDR for Leo #39540**.
