### ISSUE TITLE
[iOS] Add Shred Data Feature

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#38789]
### Platforms

iOS

### Description

Add a shred data feature:
https://www.figma.com/design/rsiGfV4XiqTGz0UdODaTAc/Shred-browser-data

**Comment by ShivanKaul** [comment]
One follow-up from Privacy Confab that would be good to do in V1 is that we should say in the warning prompt that we’re closing X number of tabs for that site.
cc @cuba

**Comment by ShivanKaul** [comment]
As pointed out by @fmarier in the privacy review, we should document this feature on support.brave.com to clarify what exactly happens when a user Shreds: Shredding clears state visible to the website but doesn't clear all traces of this website from your device. For e.g. it doesn't clear history traces (just like forgetful browsing on brave-core)

**Comment by Uni-verse** [comment]
In progress on iPhone 12 running iOS 17.5.1 using version 1.69 (144)

**Feature flag**

- Ensured Shred Data feature is disabled by default.
- Ensured enabling `brave://flags#brave-shred` will enable Shred in UI.

Flag OFF | Flag ON | brave://flags 
-|-|-
![IMG_6956](https://github.com/user-attachments/assets/ccc13eef-4335-409e-89ab-4b9773bc19cf) | ![IMG_6959](https://github.com/user-attachments/assets/6c596629-0979-43a0-b1c7-7ecec179e385) | ![IMG_6958](https://github.com/user-attachments/assets/69f0a2e5-731b-4204-ad51-33285c06a9fb)

**Globals settings**

**Per site settings**

**History (#39115)**

**Comment by Uni-verse** [comment]
In progress on iPad (7th Gen) running iOS 17.5.1 using version 1.69 (144)

**Feature flag**

- Ensured Shred Data feature is disabled by default.
- Ensured enabling `brave://flags#brave-shred` will enable Shred in UI.

Flag OFF | Flag ON | brave://flags 
-|-|-

**Globals settings**

<details><summary>Case: Globals - defaults</summary>

- Ensured Auto Shred is set to `Never` in global settings and Shields panel when enabling feature flag on new install.

Example | Example
-|-



</details>

<details><summary>Case: Globals - `Site Tabs Closed` setting</summary>

- Ensured that first party data (cache, databases, cookies and local storage) is deleted 30 seconds after closing tab. 

Before (reddit.com) | After (reddit.com)
-|-

</details>

<details><summary>Case: Globals - `Site Tabs Closed` & Closing App</summary>

- Ensured that closing app when `Site Tabs Closed` is set for Auto Shred does not delete data.

</details>

<details><summary>Case: Globals - `App Closed` setting</summary>

</details>

<details><summary>Case: Globals - `Never` setting</summary>

</details>

<details><summary>Case: Switching global settings</summary>

</details>

<details><summary>Case: Auto Shred last tab open</summary>

</details>

<details><summary>Case: Delete data after 30 seconds</summary>

</details>
 

**Per site settings**

<details><summary>Case: Override globals</summary>

</details>

**Shred button**

<details><summary>Case: Multiple tabs</summary>

</details>

<details><summary>Case: Tab bar</summary>

</details>

<details><summary>Case: Tab view</summary>

- Ensured that using the Shred button when in tab view will remove data.
- Ensured that `Shred Site Data` dialog was shown when using the Shred button
- Ensured that Shred animation is shown and tab is closed.

youtube.com (before) | tab view | youtube.com (after) 
-|-|-



</details>

<details><summary>Case: Shields panel</summary>

</details>


**Embedded Frame Storage Tests**

**History (#39115)**

**Comment by kjozwiak** [comment]
Changing to `release-notes/exclude` as we'll be enabling the above feature via `1.70.x` rather than `1.69.x` after speaking with @ShivanKaul.
