### ISSUE TITLE
[CR 126] change `Switch to this tab` text/border colour - follow up of #38731

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#38780]
### Description

As per https://github.com/brave/brave-browser/issues/38731#issuecomment-2144399102, we need to update the current text/border colour of the `Switch to this tab` button within the omnibox. In it's current state, it's really hard to read on the `light` theme, especially when the entry is selected via the omnibox.

### Steps to reproduce

1. download/install `1.68.70 Chromium: 126.0.6478.26`
2. open https://steamdb.info
3. open a NTP and start typing in the above URL into the omnibox

You'll notice that the text/border is blue which is hard to see, especially when the entry is selected.

### Actual result

**`Example`** | **`Example`**
----------------|-----------------
![image](https://github.com/brave/brave-browser/assets/2602313/04455c3e-9841-4985-8214-aacb09717a20) | ![image](https://github.com/brave/brave-browser/assets/2602313/fdc2ddc9-6e28-4d86-ae0d-d905d1692a3c)

### Expected result

![image](https://github.com/brave/brave-browser/assets/2602313/a186d9ce-ddad-4936-8184-de88175201b6)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.68.70 Chromium: 126.0.6478.26 (Official Build) nightly (64-bit)
-- | --
Revision | 28f8af9c7d27ab764fc358d8e3c5735d3139d267
OS | Windows 11 Version 23H2 (Build 22631.3672)
```

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.67.108` or higher for `1.67.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.67.108 Chromium: 126.0.6478.40 (Official Build) beta (x86_64)
-- | --
Revision | a286dc9f61f7d70fbf0157fcf3d924b00297d450
OS | macOS Version 13.6.7 (Build 22G720)
```
