### ISSUE TITLE
[ZCash] Switch to another zcash endpoint

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#38782]
### Description

lightwalletd was turned off so we need to switch our zcash grpc endpoint and block explorer url.
ECC team reccomended to use zec.rocks and https://3xpl.com/ instead.

### Steps to reproduce

1. Try to retrieve zcash account balance
2. Try to check tx from history in block explorer

### Actual result

Balance won't load, blockexplorer url won't load

### Expected result

Everything is working

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Every version that supports zcash

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.66.120` or higher for `1.66.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.120 Chromium: 125.0.6422.165 (Official Build) (64-bit)
-- | --
Revision | bd9a9589253e659c93a1c77eb9a3974525a80312
OS | Windows 11 Version 23H2 (Build 22631.3672)

- Verified steps from [brave/brave-core#23981](https://github.com/brave/brave-core/pull/23981)
- Verified ZCash balance is shown in Portfolio
- Verified `https://3xpl.com/` is used for showing block explorer when transaction confirmation link is clicked from activity tab

https://github.com/brave/brave-browser/assets/17010094/e74ad55b-5b29-4b7d-84bb-aa6f91cc7f12

**Comment by kjozwiak** [comment]
Moved this into the `1.67.x` milestone as we're not going to be releasing another `1.66.x` with `C125`. We'll be releasing `C126` via `1.67.x` on `June 13th`. Added so it can be included in the `1.67.x` release notes.
