### ISSUE TITLE
Homepage search engine selector fingerprinted

### ISSUE THREAD

**Issue by I-I-IT** [brave/brave-browser#38790]
### Description

Sorry for the unclear title.
![Screenshot](https://github.com/brave/brave-browser/assets/78900789/d3d9352e-fd58-40e5-9ca4-f7cee90a7727)
As you can see, the url query contains "segment=brave.homepage". This tells Startpage specifcally that you are using this feature, and that you are using a Desktop browser. This is a problem because Startpage has lost the trust of many users due to fingerprinting (see this [Privacy Guides forum thread](https://discuss.privacyguides.net/t/startpage-has-apparently-started-to-fingerprint-users/18434)).

### Steps to reproduce

1. Nighty version
2. Click on the search engine at the bottom
3. Customise list
4. Add Ecosia
5. Select Ecosia
6. Type

### Actual result

Fingerprinted url

### Expected result

Just a source:brave, not specifying wheter it comes from a default search engine or the homepage search selector.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.72

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by ShivanKaul** [comment]
> This tells Startpage specifcally that you are using this feature, and that you are using a Desktop browser.

Note that it is not a privacy goal to prevent websites from knowing that users are on a Desktop browser, or that [users are on Brave](https://github.com/brave/brave-browser/wiki/Detecting-Brave-(for-Websites)).

**Comment by ShivanKaul** [comment]
> Just a source:brave, not specifying wheter it comes from a default search engine or the homepage search selector.

This is already true, the attribution code is the same between searching via the omnibox or via the homepage/NTP search box.

**Comment by I-I-IT** [comment]
No that's false. For other search engines, it just says Brave. Even for Startpage normal it just says Brave

**Comment by ShivanKaul** [comment]
You can see that the `segment` is the same in both omnibox/address bar search if Startpage is default, or the homepage/NTP search box if you manually select Startpage:

<img width="707" alt="image" src="https://github.com/brave/brave-browser/assets/5284154/fd2197dc-199a-4d9e-a81f-2daf31d40358">


and


<img width="672" alt="image" src="https://github.com/brave/brave-browser/assets/5284154/0cae94d8-1800-464f-ba84-cd69345f898a">

**Comment by ShivanKaul** [comment]
Also note that the user has to manually select this search engine. Brave recommends using Brave Search for best privacy. On a separate note I don't think we need to send this `segment` anyway, but it's not a fingerprinting risk or bug.
