### ISSUE TITLE
Update Brave VPN sell panel text

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#38799]
### Description

Need to update text/copy on the VPN sell panel

### Steps to reproduce

1. Don't have VPN purchased
2. Click `VPN` button in top right by hamburger menu

### Actual result

![image](https://github.com/brave/brave-browser/assets/4733304/8ac4963f-93fc-481b-87ee-269a31f8e9be)

### Expected result
<img width="377" alt="Screenshot 2024-07-01 at 12 12 35 PM" src="https://github.com/brave/brave-browser/assets/5951041/c4233970-5fea-4a61-a21e-6a3fc5d5bcad">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

n/a

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by bsclifton** [comment]
For more info, Brave employees can see https://bravesoftware.slack.com/archives/C02ML9R5P1R/p1716578043722799?thread_ts=1716576618.215899&cid=C02ML9R5P1R

**Comment by larreewong** [comment]
A rewrite of the paywall panels (desktop and mobile), account.brave.com card for VPN, and Stripe copy for any VPN purchases. [That doc is here](https://docs.google.com/document/d/14dNDajUGPR6CEddAc4cLq1vncMT4NXLjbmeW0hsSVec/edit).

@mattmcalister and @bsclifton are already in the loop on this, as is the Guardian team. 
cc @rebron @anthonypkeane @timchilds

**Comment by larreewong** [comment]
See the updated copy for the desktop paywall: https://docs.google.com/document/d/14dNDajUGPR6CEddAc4cLq1vncMT4NXLjbmeW0hsSVec/edit#heading=h.jjdig63jjf6f

The security/privacy review for the updated copy is completed/closed:
https://github.com/brave/reviews/issues/1664#issuecomment-2194640121

@mattmcalister: please advise if the multi-device refresh test is completed or not. We have a placeholder in the copy for the last bullet point:  **Protect up to [TK] devices with one plan**

@aguscruiz: could you mock up the updated copy in Figma for us to preview? Thank you

cc @macauleyberg @rmcfadden3 @rebron

**Comment by aguscruiz** [comment]
Here's the update copy mockups for all platforms. 

Please let me know if there are any notes in Figma
https://www.figma.com/design/DSDkzFJ4NdBKLKkf3tDdnE/%F0%9F%94%90-VPN?node-id=3054-394&t=3MytY4ROcDv1XjBC-1

**Comment by macauleyberg** [comment]
Reviewed and added just a couple comments in Figma

**Comment by bsclifton** [comment]
@macauleyberg @mattmcalister @rebron let me know when it's ready for work - you can assign me and I can help get this knocked out

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.70.30 Chromium: 127.0.6533.73 (Official Build) nightly (x86_64)
-- | --
Revision | 252bfcfa10e3f2a7e92ee1be5b9e488ab43b7218
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.70.30`
2. launched Brave
3. clicked on the `VPN` button in the browser toolbar
4. examined the promotional-copy text

### Confirmed it matches the `Expected Result` image

<img width="1312" alt="Screen Shot 2024-07-30 at 11 33 07 AM" src="https://github.com/user-attachments/assets/736fe55e-3848-4b9c-bd24-b34ebac53c43">
