### ISSUE TITLE
Enable Web Serial by default

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#38791]
### Description

We currently [disable Web Serial by default](https://github.com/brave/brave-browser/issues/13902), and allow [enabling via flag](https://github.com/brave/brave-browser/issues/24404). On looking at the user flow now, I don't see a reason to keep this disabled. Users get a permission popup and the API doesn't increase fingerprinting surface by default. Mozilla also [changed their position recently](https://github.com/mozilla/standards-positions/issues/720#issuecomment-2113627711); in Chromium Web Serial use requires a permission popup.

<img width="455" alt="image" src="https://github.com/brave/brave-browser/assets/5284154/018f9976-718d-4c3f-a984-befe2e3a3321">

### Steps to reproduce

Check status of brave://flags/#brave-web-serial-api 

### Actual result

Is off by default

### Expected result

Should be on by default

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.40 Chromium: 125.0.6422.76 (Official Build) nightly (arm64)  (I'm on Nightly but this is on all versions)

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by mkarolin** [comment]
Test plan:

1. Start Brave and navigate to permissions.site
2. Click on Serial button

Observe: 
Permission prompt shows up.

3. Cancel from the permission prompt
4. Navigate to brave://settings/content
5. Click Additional permissions 
6. Verify that `Serial ports` is listed

**Comment by mkarolin** [comment]
Note on deviation from the original description. Instead of making the flag enabled by default, the flag was removed entirely.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.69.122 Chromium: 127.0.6533.57 (Official Build) beta (64-bit)
-- | --
Revision | bd77e9b76a8e67ff2bf9f62f1df7d60378ca811f
OS | Windows 11 Version 23H2 (Build 22631.3880)
```
1. installed 1.69.122
2. launched Brave
3. opened `brave://flags` and searched for `#brave-web-serial-api`
4. confirmed `No matching experiments` message shown
5. loaded permission.site
6. clicked on Serial
7. confirmed permissions prompt
8. clicked on Connect for the first highlighted entry
9. confirmed the Serial button on the page turned green (enabled)
10. clicked again on Serial


step 3 | step 7 | step 8 | step 9 | step 10 
----- | ----- | ----- | ----- | ------  
![image](https://github.com/user-attachments/assets/1e555ff6-0bf6-4610-959a-84d1e7ade3d0)|![image](https://github.com/user-attachments/assets/07c37d75-84fd-4bd3-b997-d08c05da63f6)|![image](https://github.com/user-attachments/assets/fc3f25af-e651-4ca1-b748-b2912341235c)|![image](https://github.com/user-attachments/assets/cf8c022d-b2a3-4274-b8d7-83b8e90aa7a2)|![image](https://github.com/user-attachments/assets/91858623-2b57-48c8-9c18-13950f5b2e5f)

Upgrade:

1. installed 1.68.128
2. launched Brave
3. opened `brave://flags` and searched for `#brave-web-serial-api`
4. confirmed `Web Serial API` flag is disabled by default
5. closed Brave 
6. renamed Brave profile to `Brave-Manager-Beta`
7. installed 1.69.122
8. relaunched Brave
9. opened `brave://flags` and searched for `#brave-web-serial-api`
10. confirmed `No matching experiments` message shown
11. loaded permission.site
12. clicked on Serial
13. confirmed permissions prompt
14. clicked on Connect for the first highlighted entry
15. confirmed the Serial button on the page turned green (enabled)
16. clicked again on Serial


step 3| step 10 | step 13 | step 16
---- | ------ | ----- | -----
![image](https://github.com/user-attachments/assets/b42e55d3-3dca-4125-a671-fafbb79840c7)|![image](https://github.com/user-attachments/assets/1a125301-fb89-478d-ae2d-a36aafe0dcd1)|![2024-07-24_16h24_31](https://github.com/user-attachments/assets/1007cd78-0d13-455f-8498-c4966ac910f6)|![2024-07-24_16h30_05](https://github.com/user-attachments/assets/89bec229-4062-423a-8300-8e938f6e47e8)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.69.124 Chromium: 127.0.6533.73 (Official Build) beta (arm64)
-- | --
Revision | dbc9035349f74e493f3293d93f4cbf35c597dfec
OS | macOS Version 13.5 (Build 22G74)
```

<details>
<summary>Case 1: New install - PASSED</summary>

1. installed 1.69.124
2. launched Brave
3. opened `brave://flags` and searched for `#brave-web-serial-api`
4. confirmed `No matching experiments` message shown
5. loaded permission.site
6. clicked on Serial
7. clicked `Allow`
8. confirmed permissions prompt shown
9. clicked on Connect for the first highlighted entry
10. confirmed the Serial button on the page turned green (enabled)
11. clicked again on Serial to confirm the device is paired
12. cancel from the permission prompt
13. navigated to brave://settings/content
14. clicked Additional permissions
15. confirmed `Serials ports` entry is shown
16. opened `Serial ports` page
17. confirmed page shows the entry for the site `https://permissions.site/`

step 4 | step 7 | step 8-9  | step 10-11 | step 13 -15  | step 17
----- | ----- | ----- | ----- | ------  | -----  
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/7085aa68-3971-4f23-9c67-7007e017e7fb">|<img width="1470" alt="image" src="https://github.com/user-attachments/assets/8ed55645-89d8-442f-a688-b022785824e4">|<img width="1470" alt="Screenshot 2024-07-25 at 9 29 56 AM" src="https://github.com/user-attachments/assets/9b5230f4-aa91-4ca9-b8c2-c6a970dae16c">|<img width="1470" alt="Screenshot 2024-07-25 at 9 30 13 AM" src="https://github.com/user-attachments/assets/0dbe6629-1886-4a4a-87af-15b4f05788e9">|<img width="1470" alt="Screenshot 2024-07-25 at 9 30 48 AM" src="https://github.com/user-attachments/assets/a0b409d5-7ea7-43aa-ad6a-5ea97541bb39">|<img width="1470" alt="Screenshot 2024-07-25 at 9 30 55 AM" src="https://github.com/user-attachments/assets/270ec425-f296-43fb-8c86-2e3650005cd4">

</details>

<details>
<summary>Case 2: Reset Permissions - PASSED</summary>

1. Continue from Case 1
2. clicked the tune icon in the URL bar for the permission.site
3. clicked Reset Permission button
4. navigated brave://settings/content and clicked `Additional permissions`
5. clicked `Serial ports`
6. confirmed no entry is shown in the `No serial ports found`

step 3a | step 3b | step 5 | step 6
----- | ----- | ----- | ------
<img width="1470" alt="Screenshot 2024-07-25 at 9 56 36 AM" src="https://github.com/user-attachments/assets/f200d112-31a8-457f-baa4-657215948785">|<img width="1470" alt="Screenshot 2024-07-25 at 9 56 41 AM" src="https://github.com/user-attachments/assets/21bcf5b0-c9a8-489f-aded-7b5ae8f50d79">|<img width="1470" alt="Screenshot 2024-07-25 at 9 58 20 AM" src="https://github.com/user-attachments/assets/a5fd44c0-5794-4a98-ae3f-7d85f527ba18">|<img width="1470" alt="Screenshot 2024-07-25 at 9 57 08 AM" src="https://github.com/user-attachments/assets/ca118920-229c-4cca-ae2a-714125d8d2fb">

</details>

<details>
<summary>Case 3: Upgrade - PASSED </summary>

1. installed 1.68.128
2. launched Brave
3. opened `brave://flags` and searched for `#brave-web-serial-api`
4. confirmed `Web Serial API` flag is disabled by default
5. opened `brave://settings/content`
6. confirmed `Serial ports` entry is not listed in Additional permissions
7. closed Brave 
8. renamed Brave profile to `Brave-Manager-Beta`
9. installed 1.69.122
10. relaunched Brave
11. opened `brave://flags` and searched for `#brave-web-serial-api`
12. confirmed `No matching experiments` message shown
13. loaded https://permission.site
14. clicked on Serial
15. confirmed permissions prompt shown
16. clicked on Connect for the first highlighted entry
17. confirmed the Serial button on the page turned green (enabled) 
18. clicked again Serial button to confirm the device is paired
19. cancel from the permission prompt
20. navigated to `brave://settings/content`
21. clicked Additional permissions
22. confirmed `Serials ports` entry is shown
23. opened `Serial ports` page
24. confirmed pages shows the entry for the site `https://permission.site/`

step 4 | step 6 | step 12 | step 15-17 | step 18 | step 20-22 | step 24
---- | ------ | ----- | ----- | ----- | ----- | ---
<img width="1470" alt="Screenshot 2024-07-25 at 10 02 50 AM" src="https://github.com/user-attachments/assets/b99f9041-48df-435e-ac81-eca6fa592fb3">|<img width="1470" alt="Screenshot 2024-07-25 at 10 41 38 AM" src="https://github.com/user-attachments/assets/1ea2bea9-568e-4f89-95bf-e82072f434bb">|<img width="1470" alt="Screenshot 2024-07-25 at 10 39 22 AM" src="https://github.com/user-attachments/assets/bee53f71-d54f-4239-8083-6d3a2a708a9e">|<img width="1470" alt="Screenshot 2024-07-25 at 10 44 53 AM" src="https://github.com/user-attachments/assets/c4f0466c-ced0-42fe-96ba-3d503393e0b7">|<img width="1470" alt="Screenshot 2024-07-25 at 10 44 53 AM" src="https://github.com/user-attachments/assets/283b71c4-3825-4af3-8832-19febdc03762">|<img width="1470" alt="Screenshot 2024-07-25 at 10 49 32 AM" src="https://github.com/user-attachments/assets/94524aa0-e207-43b3-97f9-3916ffed0022">|<img width="1470" alt="Screenshot 2024-07-25 at 10 49 39 AM" src="https://github.com/user-attachments/assets/7e436867-d06a-477e-a875-c8aa3fb39e6c">


</details>

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.69.128 Chromium: 127.0.6533.73 (Official Build) beta (64-bit) 
Revision	715445841b1da480bcc24c12077a6dc926951996
OS	Linux
```

<details>
<summary>Case 1: New install - PASSED</summary>

1. installed 1.69.124
2. launched Brave
3. opened `brave://flags` and searched for `#brave-web-serial-api`
4. confirmed `No matching experiments` message shown
5. loaded permission.site
6. clicked on Serial
7. confirmed permissions prompt shown
8. clicked on Connect for the first highlighted entry
9. confirmed the Serial button on the page turned green (enabled)
10. clicked again on Serial to confirm the device is paired
11. cancel from the permission prompt
12. navigated to brave://settings/content
13. clicked Additional permissions
14. confirmed `Serials ports` entry is shown
15. opened `Serial ports` page
16. confirmed page shows the entry for the site `https://permissions.site/`

step 4 | step 7-8  | step 9-10 | step 12 -14  | step 16
----- | ----- | ----- | ----- | ------  | -----  
![image](https://github.com/user-attachments/assets/ea99948f-310f-49e0-807c-3317e390c886)|![image](https://github.com/user-attachments/assets/bb3ef98d-973d-4b67-9d60-b9eef5b9080e)|![image](https://github.com/user-attachments/assets/d89d24a7-02fb-433e-afd3-d5ac166f4a90)|![image](https://github.com/user-attachments/assets/1314ba21-719c-4342-8eac-ac31f428a8a4)|![image](https://github.com/user-attachments/assets/8034c0b7-81fa-4892-b5dd-39d347b5dfc4)


</details>

<details>
<summary>Case 2: Reset Permissions - PASSED</summary>

1. Continue from Case 1
2. clicked the tune icon in the URL bar for the permission.site
3. clicked Reset Permission button
4. clicked Reload button
5. navigated brave://settings/content and clicked `Additional permissions`
6. clicked `Serial ports`
7. confirmed no entry is shown in the `No serial ports found`

step 3a | step 3b | step 4 | step 5 | step 6
----- | ----- | ----- | ------ | -----
![image](https://github.com/user-attachments/assets/2e7e7d36-9445-4cb5-87d9-789e73d40b40)|![image](https://github.com/user-attachments/assets/ae86e3b7-c4ec-41a8-a639-99750e63fbe3)|![image](https://github.com/user-attachments/assets/5fb648a1-5166-4225-a4c0-22a589494f39)|![image](https://github.com/user-attachments/assets/c4692ee3-3a5b-4ddd-b9c9-df4ba5dbde82)|![image](https://github.com/user-attachments/assets/34253b24-d29b-4e69-b7a1-e489e7e0a05a)


</details>

<details>
<summary>Case 3: Upgrade - PASSED </summary>

1. installed 1.68.128
2. launched Brave
3. opened `brave://flags` and searched for `#brave-web-serial-api`
4. confirmed `Web Serial API` flag is disabled by default
5. opened `brave://settings/content`
6. confirmed `Serial ports` entry is not listed in Additional permissions
8. closed Brave 
9. renamed Brave profile to `Brave-Manager-Beta`
10. installed 1.69.128
11. relaunched Brave
12. opened `brave://flags` and searched for `#brave-web-serial-api`
13. confirmed `No matching experiments` message shown
14. loaded https://permission.site
15. clicked on Serial
16. confirmed permissions prompt shown
17. clicked on Connect for the first highlighted entry
18. confirmed the Serial button on the page turned green (enabled) 
19. clicked again Serial button to confirm the device is paired
20. cancel from the permission prompt
21. navigated to `brave://settings/content`
22. clicked Additional permissions
23. confirmed `Serials ports` entry is shown
24. opened `Serial ports` page
25. confirmed pages shows the entry for the site `https://permission.site/`

step 4 | step 6 | step 13 | step 15-17 | step 18-19 | step 21-22 | step 25
---- | ------ | ----- | ----- | ----- | ----- | ---
![image](https://github.com/user-attachments/assets/ec15b57a-71e1-4f01-a4ed-4980c1f4c595)|![image](https://github.com/user-attachments/assets/9291f1c0-65fb-4097-ae50-c5c84e62157c)|![image](https://github.com/user-attachments/assets/89cfb554-354d-4b6d-a738-79c55161ea2b)|![image](https://github.com/user-attachments/assets/8f78d5d4-2e9d-4180-9bdf-edebd154d574)|![image](https://github.com/user-attachments/assets/972e0155-264c-4adb-ab02-c6b42cbde466)|![image](https://github.com/user-attachments/assets/1ee7ae8d-fa89-4511-b008-36d74c19efd9)|![image](https://github.com/user-attachments/assets/4d15f6df-a96c-42dd-950e-f82d8478b600)



</details>

**Comment by Dinth** [comment]
Many thanks! Sorry for throwing my couple of pence here, but this is a great decision! Im not a dev, but i am an IT Security expert who done fair bit of threat modelling and risk assessments, and i have never seen the point of removing that feature from the browser.

>Mozilla also https://github.com/mozilla/standards-positions/issues/720#issuecomment-2113627711;
Looking at what Mozilla does is not the best thing, their market share is constantly getting smaller and not without a reason. Not implementing WebSerial in FF was one of those reasons.
