### ISSUE TITLE
Building on Windows in Release mode with official_build=false fails. 

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#3879]
After merging C74 into master (#3502) building on Windows in Release mode with `official_build=false` produces the following link errors:

<pre>
FAILED: nasm.exe nasm.exe.pdb
ninja -t msvc -e environment.x64 -- ../../third_party/llvm-build/Release+Asserts/bin/lld-link.exe /nologo /OUT:./nasm.exe /PDB:./nasm.exe.pdb @./nasm.exe.rsp
lld-link: error: duplicate symbol: ilog2_32 in obj/third_party/nasm/nasm/directiv.obj and in obj/third_party/nasm/nasm/ilog2.obj
lld-link: error: duplicate symbol: ilog2_64 in obj/third_party/nasm/nasm/directiv.obj and in obj/third_party/nasm/nasm/ilog2.obj
lld-link: error: duplicate symbol: alignlog2_32 in obj/third_party/nasm/nasm/ilog2.obj and in obj/third_party/nasm/nasm/outmacho.obj
</pre>

cc: @emerick

**Comment by mkarolin** [comment]
- Both the latest C73 and C74 use the same `nasm` code (commit `4ee6a69c`).
- The compilation flags for Release mode with `official_build=false` have not changed (`/Od /Ob0 /GF`).
- The Clang version has changed (from `351477` to `354873`).

Rolling back to Clang `351477` eliminates the errors.

**Comment by mkarolin** [comment]
When linking with /VERBOSE there is a bit more info:
`lld-link: conflicting comdat type for ilog2_32: 2 in obj/third_party/nasm/nasm/directiv.obj and 1 in obj/third_party/nasm/nasm/ilog2.obj
lld-link: error: duplicate symbol: ilog2_32 in obj/third_party/nasm/nasm/directiv.obj and in obj/third_party/nasm/nasm/ilog2.obj`

Recent llvm changes of note:

https://reviews.llvm.org/D58180
https://bugs.llvm.org/show_bug.cgi?id=40094 (see all changes at the bottom)

**Comment by mkarolin** [comment]
Also, notice this change in `nasm` from Nov 2018 where config for windows was switched from `config/config-win.h` to `config/msvc.h` (https://chromium.googlesource.com/chromium/deps/nasm.git/+/274b50137b6209b106f8989a24ab92f287654147). Of note in this case is that `config-win.h` had `#define HAVE_STDC_INLINE 1` whereas `msvc.h` doesn't. This means that on windows none of the functions declared in `ilog2.h` are inline.

**Comment by rebron** [comment]
Closing. Reopen if this happens again.

**Comment by mkarolin** [comment]
This will be addressed by brave/brave-browser#3502 (re-landing of C74 with LLVM reverted to `351477`).
