### ISSUE TITLE
Brave As Portable Application

### ISSUE THREAD

**Issue by MisterTeeXD** [brave/brave-browser#3880]
I think Brave should be a Portable application so those who move to different PC's can use Brave anywhere.

**Comment by bsclifton** [comment]
@MisterTeeXD as far as I know, all issues with this should be resolved.  Can you please check out the details in https://github.com/brave/brave-browser/issues/694?

(let's re-open if something is still now working)

**Comment by MisterTeeXD** [comment]
So, should i use that Brave Instance now?

**Comment by bsclifton** [comment]
@MisterTeeXD it's not an official release, but it's an available option you can check out

**Comment by caspertone2003** [comment]
@MrTeeXD 
@crazy-max

I am a happy user of brave portable, not related to crazy-max.
You should definetively try it.
I use both brave-portable .25 (based on brave-desktop) and .6x (based on brave-core) as .25 implements session tabs and brave-core .6x is not implementing session tabs (yet? ever?). On the other hand .25 does not support chrome extensions and .6x does. For me session tabs is a/the USP of brave...

Brave portable is frequently updated to new releases of brave-core.
You can check portapps and see the serious work of crazy-max.
In any case, trust is a complex thing and your mileage may vary...

**Comment by crazy-max** [comment]
@MrTeeXD You can find link to download and test Brave portable on https//portapps.io

**Comment by My1** [comment]
while it is great that someone made a portable version, an official one would still be crazy awesome.
