### ISSUE TITLE
Ad events related to Brave News cannot be cleared without opting into Rewards

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#38804]
### Description

Ad events in Brave News such as impressions and clicks are recorded by the browser's Ads service. This information is stored in a local sqlite in the browser profile. This happens when the user opts into Brave News, but regardless of whether or not that user has also opted into Brave Rewards.

The fact that the data is collected is not a surprise since Brave News is opt-in and a notice is shown telling users that Brave News is ad supported. The problem is that there is no way for non-Rewards users to clear that local data.

### Steps to reproduce

1. Create a new profile.
2. Skip the onboarding.
3. Go to the newtab page and scroll down for Brave News.
4. Opt in to Brave News.
5. Restart the browser.
6. Open a newtab page and scroll through the Brave news feed until you see ads.
7. Click on an ad.

### Actual result

The "Reset Brave Rewards data" functionality is only available from `brave://rewards` and that page is gated on opting into Brave Rewards.

### Expected result

There should be a way to clear the local database (`Default/ads_service/database.sqlite`) since it contains history-like data. Right now, the two choices are to opt into Rewards (for the sole purpose of clearing the data) or delete the database manually on disk.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Linux 1.67.100 Chromium: 125.0.6422.112 (Official Build) beta (64-bit) 

### Channel information

- [ ] release (stable)
- [X] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by fmarier** [comment]
We already have a link to clear Rewards data from `brave://settings/clearBrowserData`:
![Screenshot from 2024-06-04 16-07-16](https://github.com/brave/brave-browser/assets/167821/c277f65c-7bc8-49ef-8d49-7b688d47eb8d)

and so I think all we need is to make that link work for non-Rewards users too.

Perhaps we should also rename it to "Rewards and Ads" data.

**Comment by fmarier** [comment]
Also, I filed a related issue because this should be cleaned up automatically when users opt out of Brave News: https://github.com/brave/brave-browser/issues/38900

**Comment by Miyayes** [comment]
@fmarier Does this apply to Search Ads or any other ad units, or uniquely Brave News?

**Comment by fmarier** [comment]
> Does this apply to Search Ads or any other ad units, or uniquely Brave News?

It applies to non-Rewards users for Brave News, Search Ads and probably NTT when `chrome://flags/#brave-ads-should-always-trigger-new-tab-page-ad-events` is set, but I've not tested that last one.

**Comment by Miyayes** [comment]
Thanks @fmarier. So it's more general than just Brave News. Should we edit this issue to reflect that? And adminisratively, wondering if we should use this issue or https://github.com/brave/brave-browser/issues/39051?

**Comment by tmancey** [comment]
@fmarier thank you. We will close this as it will be resolved by https://github.com/brave/brave-browser/issues/39051. Thank you
