### ISSUE TITLE
WebUI not changing theme to Light

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#3881]
If you have a WebUI open, it is in dark mode, and then you change to light mode, the webui will not change theme to light mode until it is closed and re-opened.

However, switching from light to dark seems to be fine.

Assigning to 0.63.x for now since this is a bug with webui themeing which is introduced with 0.63.x

#### Explicit theme
1. Open Settings, switch to 'Dark'
2. Close Settings
3. Open Settings, it will be 'Dark'
4. Change theme to Light
Actual: Browser chrome changes to Light, but Settings remains as Dark
Expected: Settings changes to Light too

#### Same as macOS theme
1. Change macOS theme to Dark
1. Open Settings, switch to 'same as macOS'
2. Close Settings
3. Open Settings, it will be 'Dark' and keep Settings as active tab
4. Change macOS theme to Light
Actual: Browser chrome changes to Light, but Settings remains as Dark
Expected: Settings changes to Light too

**Comment by simonhong** [comment]
Do we use `onBraveThemeTypeChanged` to get theme change in settings webui?

**Comment by simonhong** [comment]
Found the case.
`features::kWebUIDarkMode` is enabled on MacOS/Win10 in C74 and `DarkModeHandler` only observes non-dark native theme.

**Comment by simonhong** [comment]
One more thing - we can reuse chrome's api to get current theme and event notification.
`loadTimeData.getBoolean('darkMode')`
`FireWebUIListener("dark-mode-changed", base::Value(UseDarkMode()));`

**Comment by petemill** [comment]
@simonhong this proble
 is happening in brave’s chromium webui too which I assume use that technique. E.g. chrome://settings

**Comment by simonhong** [comment]
@petemill I think that problem can be fixed by notifying both theme (native/dark aura).
I mean how about using chrome's variable(`darkMode`) and event(`dark-mode-changed`) to get current theme type and theme changing instead of using our own.

**Comment by petemill** [comment]
@simonhong it's possible we can use that, certainly now whilst there is only 'light' and 'dark' vs more (not sure if there will ever be more choices, probably not!). It would need to be available from extensions panel and I don't believe the chromium variable is?

**Comment by simonhong** [comment]
@petemill ah.. they are webui messages. I think it's not available for extension..

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.63.35 Chromium: 74.0.3729.61 (Official Build) beta (64-bit)
-- | --
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Windows 10 OS Build 17134.523

Used test plan from the description.
Logged https://github.com/brave/brave-browser/issues/4059
