### ISSUE TITLE
[ads] Ads should be shutdown if the wallet is invalid for a Brave Rewards user

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#38818]
Previously, we only initiated a shutdown if the user had opted into notification ads and the wallet was invalid. A wallet is required for any type of ad if a user has joined Rewards.

**Comment by btlechowski** [comment]
Verified with

Brave | 1.68.94 Chromium: 126.0.6478.114 (Official Build) beta (64-bit)
-- | --
Revision | 8981faf58380240eab6e999e6bf06f9ed9314336
OS | Linux


Verified ads are not initialized when recovery seed is corrupted
```
[2863:2863:0622/142501.136891:VERBOSE1:ads_service_impl.cc(463)] Failed to initialize Brave Rewards wallet
```

**Comment by btlechowski** [comment]
Removed `OS/Android` as it is not possible to corrupt seed on Android.
