### ISSUE TITLE
Update search promotion UI for DDG

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#38811]
### Description

This is f/u issue for https://github.com/brave/brave-browser/issues/38692.

We show different types of promotion UI by using griffin's type param.
Instead of using griffin type params, we want to rotate types if this search promotion feature is enabled

### Steps to reproduce

1. Launch browser with --enable-features=BraveSearchOmniboxDDGBanner
2. Set DDG as a default search provider
3. Type anything and check DDG promotion is shown
4. Check different banner type is shown during the run time

### Actual result

Banner type should be provided from griffin

### Expected result

Different banner type should be used after launch

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.x

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by simonhong** [comment]
Working on this.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.69.98 Chromium: 127.0.6533.26 (Official Build) nightly (64-bit)
-- | --
Revision | a7710883b2316472175f7b756e561cca3f02b254
OS | Windows 11 Version 23H2 (Build 22631.3880)
```
Installed 1.69.98
launched Brave
opened brave://settings/search
selected `DuckDuckGo` as SE for Normal Window

example | example | example | example | example 
---- | ---- | ----- | ----- | -----
![image](https://github.com/user-attachments/assets/0f86829e-782d-45ef-bd21-6488d513b48a)|![2024-07-11_17h14_12](https://github.com/user-attachments/assets/c45635cb-ec1d-4079-912a-f6d7fb374060)|![2024-07-11_17h12_01](https://github.com/user-attachments/assets/3dd2a97b-0b38-44ed-a810-91faf215e7d7)|![2024-07-11_17h13_13](https://github.com/user-attachments/assets/f577bfea-6f5f-4383-8cf2-8a653a823326)|![2024-07-11_17h12_46](https://github.com/user-attachments/assets/e0904620-9412-4a20-8298-b5e8fdd36640)
