### ISSUE TITLE
Backup from portfolio is broken

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#38816]
### Description

Backup from portfolio is broken

### Steps to reproduce

1. Create wallet
2. Go to backup from protfolio 
3. shows blank page

### Actual result

https://github.com/brave/brave-browser/assets/17010094/bbfa0136-03e3-4cb5-898e-e40cd7fcd777

### Expected result

Should show backup screen

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.67.105 Chromium: 126.0.6478.26 (Official Build) beta (64-bit)
-- | --
Revision | ff15eaa0be4f63abc388184895a7450c929375c8
OS | Windows 11 Version 23H2 (Build 22631.3672)

### Channel information

- [ ] release (stable)
- [X] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @muliswilliam

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/24007 was merged into `1.67.x`. The above requires `1.67.108` or higher for `1.67.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.108 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | a286dc9f61f7d70fbf0157fcf3d924b00297d450
OS | Windows 11 Version 23H2 (Build 22631.3672)

- Verified steps from issue description
- Verified able to load backup screen from Portfolio

https://github.com/brave/brave-browser/assets/17010094/c87b7bee-6adc-47c0-8db0-2e6d9d5df590
