### ISSUE TITLE
improve the selection highlight when hovering over `Relaunch to update Brave` via `Hamburger Menu` - follow up to #38645

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#38810]
### Description

You'll notice when hovering over the `Relaunch to update Brave` button via the `Hamburger Menu` will apply a grey selection on the entire row. However, because the `Relaunch to update Brave` button doesn't span the entire width of the settings menu, it looks a bit strange having portion of the row highlighted.

### Steps to reproduce

**Quick Note:** You'll need to make sure that there's a few updates pending so the `Hamburger Menu` gets into a `Update` state.

1. once you get into a `Update` state, hover over `Relaunch to update Brave` via the `Hamburger Menu`

You'll notice that the grey highlight spills over to the edges as the `Relaunch to update Brave` button doesn't span the entire width.

### Actual result

**`Example`** | **`Example`**
---------------|-----------------
![image](https://github.com/brave/brave-core/assets/2602313/14c99062-b299-44f1-9729-f689b0f2693e) | ![image](https://github.com/brave/brave-core/assets/2602313/d91d28b2-2d77-4168-b1f4-d90f981f78e4)

### Expected result

Probably should ether widen the `Relaunch to update Brave` button or improve the grey highlight.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.68.70 Chromium: 126.0.6478.26 (Official Build) nightly (64-bit)
-- | --
Revision | 28f8af9c7d27ab764fc358d8e3c5735d3139d267
OS | Windows 11 Version 23H2 (Build 22631.3672)
```

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.67.115` or higher for `1.67.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.67.115 Chromium: 126.0.6478.56 (Official Build) (x86_64)
-- | --
Revision | e1f8b4850805c2eea958bad7220c5e6e9202efaa
OS | macOS Version 13.6.7 (Build 22G720)
```
