### ISSUE TITLE
Change navigation for "Removed permissions for x unused site(s)" from hamburger menu

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#38825]
### Description

When the "Removed permissions for x unused site(s)" option is shown under the hamburger menu, if you click on this menu item it attempts to redirect to `brave://settings/safetyCheck` but this was removed via https://github.com/brave/brave-browser/issues/36859 so it instead redirects to `brave://settings` which isn't helpful.

Per @rebron, should redirect to `brave://settings/content`.

![Screenshot 2024-06-05 at 9 09 37 AM](https://github.com/brave/brave-browser/assets/28145373/85325703-c2e7-4621-bfb6-731198cd40c8)

See additional discussion: https://bravesoftware.slack.com/archives/CKNHM4RTK/p1717591007662489

### Steps to reproduce

1. Trigger this hamburger menu option (don't know how to do this)
2. Once this menu option is displayed, click on it

### Actual result

You are directed to `brave://settings`

### Expected result

Should be directed to `brave://settings/content`

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.68.72 Chromium: 126.0.6478.26 (Official Build) nightly (x86_64)
-- | --
Revision | d8df78a64942936219a2b2bb4b6b8d7daca59146
OS | macOS Version 13.6.7 (Build 22G720)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron

**Comment by kjozwiak** [comment]
Closing/Confirmed this is now working now. Verified the above while I was running through https://github.com/brave/brave-core/pull/24162#issuecomment-2164345492.
