### ISSUE TITLE
`onBraveThemeTypeChanged` not getting called from extension page

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#3882]
Here is a branch that is attempting to use `chrome.braveTheme.onBraveThemeTypeChanged` event handler: 
~https://github.com/brave/brave-core/compare/try-shields-theme...try-shields-theme-onchange~ _edit: now on master_

It is not getting fired when the system theme is changed.

### Steps to reproduce
- Run the above branch
- In Settings, change theme to 'Same as macOS'
- Visit a website
- Open shields panel
- Keep shields panel open and change macOS theme
Observed: theme doesn't change
Expected: theme changes

This is not a huge issue for Shields panel, but is a nice to have, especially for other webui.

Assigning to 0.63.x for now since 'Same as macOS' was introduced there, but this is not urgent.

**Comment by simonhong** [comment]
I found that current implementation only fires `onBraveThemeTypeChanged` when preference is changed. I missed this 👍

**Comment by petemill** [comment]
Uplifting only to 0.64.x as the only code that depends on this event is in 0.64.x

**Comment by LaurenWags** [comment]
@petemill @simonhong is this one macOS (specifically Mojave) only?

**Comment by simonhong** [comment]
@LaurenWags extension page on Windows should change by windows os theme change.
However, only nightly will work properly.
For dev, beta, uplift PRs are waiting for approving. https://github.com/brave/brave-core/pull/2332 and https://github.com/brave/brave-core/pull/2331.

**Comment by btlechowski** [comment]
Based on the above comment, added `OS/macOS` label

**Comment by simonhong** [comment]
@btlechowski yes, it's correct 👍

**Comment by LaurenWags** [comment]
@kjozwiak can you check this one since you have Mojave?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.4 x64` using the following build:

Brave | 0.64.72 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Went through the original test case outlined under https://github.com/brave/brave-browser/issues/3882#issue-425047834

![themeSettingsmacOS](https://user-images.githubusercontent.com/2602313/57317867-17b43680-70c7-11e9-8e3b-258ca75b108c.gif)
