### ISSUE TITLE
[CR 126] Update icon for "Removed permissions for x unused site(s)" from hamburger menu

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#38826]
### Description

When the "Removed permissions for x unused site(s)" option is shown under the hamburger menu, the icon displayed with this option is Chrome's, not ours.

See additional discussion: https://bravesoftware.slack.com/archives/CKNHM4RTK/p1717591007662489

### Steps to reproduce

1. Trigger this hamburger menu option (don't know how to do this)
2. View icon on menu option

### Actual result

Icon is Chrome's icon:

<img width="344" alt="Screenshot 2024-06-05 at 11 46 50 AM" src="https://github.com/brave/brave-browser/assets/28145373/51b27d78-14ee-4d2e-b570-d88574e4f64f">

### Expected result

Should be Brave's icon

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.68.72 Chromium: 126.0.6478.26 (Official Build) nightly (x86_64)
-- | --
Revision | d8df78a64942936219a2b2bb4b6b8d7daca59146
OS | macOS Version 13.6.7 (Build 22G720)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron

**Comment by aguscruiz** [comment]
Let's use `shield-block`

**Comment by rebron** [comment]
We'll fix this one in a follow-up 1.67.x minor release.

**Comment by kjozwiak** [comment]
The above requires `1.67.118` or higher for `1.67.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.67.119 Chromium: 126.0.6478.114 (Official Build) (64-bit)
-- | --
Revision | 36e2dbd9e397c3a8a4d54a741ea5a6316eab0203
OS | Windows 11 Version 23H2 (Build 22631.3737)
```

**`Example`** | **`Example`**
----------------|----------------
![image](https://github.com/brave/brave-browser/assets/2602313/fb71703a-dd9f-4a46-8510-cbee1362674c) | ![image](https://github.com/brave/brave-browser/assets/2602313/5fb17bee-4c32-4e2a-b6ed-34807b5eff7a)
