### ISSUE TITLE
[Wallet] Incorrect deposit address shown in deposit-funds screen

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#38833]
### Description

Attempting to deposit displays the Account 1 address no matter which account is selected. https://community.brave.com/t/deposit-address-not-changing-for-multiple-accounts/549656

### Steps to reproduce

1. create a wallet with multiple ETH accounts. 
2. select Deposit
3. select the ETH network token
4. continue to next screen

### Actual result

It shows an address and a QR code for one of my accounts. 
When switching to a different account using the selector above the QR code, the QR code and the address don’t change. They still show the other account’s QR and address

### Expected result

When switching to a different account using the selector above the QR code, the QR code and the address should change to the correct address

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.66.118 Chromium: 125.0.6422.147 (Official Build) (arm64) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

https://community.brave.com/t/deposit-address-not-changing-for-multiple-accounts/549656

**Comment by LaurenWags** [comment]
Requires `1.67.110` or higher for testing 👍🏻

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.110 Chromium: 126.0.6478.40 (Official Build) (64-bit)
-- | --
Revision | ac00bac697a2d9dad0b2e7f832391263816fd78d
OS | Windows 11 Version 23H2 (Build 22631.3672)

- Verified steps from issue description
- Verified address and QR code changes when selected on Deposit screen

https://github.com/brave/brave-browser/assets/17010094/14cb7117-5cee-4eb1-913d-7aa6f3627709
