### ISSUE TITLE
[iOS] Users report tab loss

### ISSUE THREAD

**Issue by iccub** [brave/brave-browser#38834]
### Description

Getting reports every now and then that user's tabs are gone.

### Steps to reproduce

We never reproduced

### Actual result

Tabs are gone

### Expected result

-

### Reproduces how often

Easily reproduced

### Brave version

-

### Device/iOS version

-

### Affected browser versions

- [X] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by anthonypkeane** [comment]
Some user reports

https://appfigures.com/reviews/42132121512Lj9bOfAf01QuJvl77LxHYbA?lang=en
https://appfigures.com/reviews/42132121512Lvz_fhCHnXUGJxb_QChnNtw?lang=en
https://appfigures.com/reviews/42132121512LKXz3nmskPG1t7J73iydOow?lang=en
https://appfigures.com/reviews/42132121512LzYxKC_sWkvqlnniqgZyjQA?lang=en

**Comment by anthonypkeane** [comment]
Related: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1707862535977719

**Comment by kjozwiak** [comment]
The above requires `1.66.162` or higher for `1.66.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.5.1
- iPad Air / iPadOS 16.7.2
Brave build: 1.66.1 (120)
BraveCore: 1.66.120 (125.0.6422.165)
```

Filed follow-up issue #38965
---------------------------

**STEPS:**
1. Launch Brave
2. Open multiple tabs with any websites
3. Set `Tabs Bar` to ON in Brave settings (not 100% sure if this step is needed)
4. Go to the home screen or another app and keep Brave opened
5. Lock and then unlock the device
6. Close and relaunch Brave until tabs are lost > *Observe that tabs are lost*
7. Tap and hold `Tabs overview` button
8. View Recently Closed Tabs > *Observe that tabs from another session are shown*

**ACTUAL RESULTS:**
- Verify that tabs are not lost when closing and reopening Brave
- Observed that tabs can be lost sometimes and:
  - on `iPad` tabs can be restored by closing and reopening Brave again. According to @Brandon-T this happens on `ALL` browsers on `iPadOS` including `Chrome` and `Safari`
  - on `iPhone` tabs can't be restored - #38965

---------------------------

`iPad`

https://github.com/brave/brave-browser/assets/128532965/ac1dd2f4-be8c-4024-8bf0-031450d101ae

`iPhone`

https://github.com/brave/brave-browser/assets/128532965/bda1c08c-585c-4016-a2c6-ab87cc7fc44f

https://github.com/brave/brave-browser/assets/128532965/c611d09d-6ce9-44d9-8ce5-da372cbb5194
