### ISSUE TITLE
Allow dynamic compute limit and priority fees in Jupiter swaps

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#38845]
### Description

Jupiter Swap API can use dynamic compute limit (as opposed to a hardcoded value) and auto-compute priority fee instead of using a fixed value, as documented here: https://station.jup.ag/docs/apis/swap-api#setting-priority-fee-for-your-transaction

This should improve success rates of swap transactions landing onchain.

Additionally, we should also consider reducing the transaction rebroadcast delay to a smaller value like 2s (currently 5s) so we get more retry attempts within the 150 slots that the transaction is retried for.

### Steps to reproduce

N/A - this is about an internal core change

### Actual result

Jupiter swap transactions initiated from within Brave Wallet never get confirmed onchain. Typically, the explorer indefinitely shows "Not found" for the transaction signature, indicating that the node didn't pick up the transaction.

### Expected result

Improved success rates of Jupiter swap transactions getting confirmed.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Reproduces on all versions of Brave including 1.66.118. PR may be uplifted to at least 1.67.x.

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [X] in the latest version of Chrome

### Miscellaneous information

Note that the real improvement may only come if/when we switch to Helius nodes (currently under discussion). Please DM me if you need link to a Helius RPC node to use for testing.

**Comment by kjozwiak** [comment]
The above requires `1.67.109` or higher for `1.67.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.110 Chromium: 126.0.6478.40 (Official Build) (64-bit)
-- | --
Revision | ac00bac697a2d9dad0b2e7f832391263816fd78d
OS | Windows 11 Version 23H2 (Build 22631.3672)

- Verified steps from  from issue description
- Verified Swap transactions work

https://github.com/brave/brave-browser/assets/17010094/0e8947b6-41ca-4ea4-a2c2-1cc8ac5431a6
