### ISSUE TITLE
Sync isn't working notification

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#38847]
### Description

Reported on community
https://community.brave.com/t/cant-add-my-android-phone-to-a-sync-chain/552075

And at Slack https://bravesoftware.slack.com/archives/C2HJYB45N/p1715131038656949 from @hffvld 

Back at May I wasn't able to reproduce, but today I could do it.

### Steps to reproduce

1. On deviceA create a new chain, stay screen on showing QR
2. Connect deviceB by scanning QR from deviceA

### Actual result

3. Actual - warning in notification, but device is connected

### Expected result

4. Expected - no warning

### Reproduces how often

Intermittent issue

### Brave version

deviceA - Brave 1.68.53, Chromium 126.0.6478.17, own built, 
deviceB - Android 14, Brave v1.68.45, Chromium 125.0.6422.112, own built.

Stable 1.66.120 / Chromium 125.0.6422.165 (Google Play) - cannot reproduce
Beta 1.68.0 / Chromium 126.0.6478.8 (own built) - I was able to reproduce
Nightly 1.69.3 / Chromium 126.0.6478.40 (Google Play) - I was able to reproduce
Beta 1.67.108 / Chromium 126.0.6478.40 (Google Play) - I was able to reproduce

### Device

deviceA - Pixel 6, Android 15
deviceB - S22 Ultra, Android 14

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240426.023.B4 release-keys
Brave build: 1.67.116
Chromium: 126.0.6478.71 (Official Build) (64-bit)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/38847#issue-2336786799
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Sync isn't working` notification is not shown
- Verified that the `Sync` chain was established successfully

---------------------------

`Reproduced in build 1.67.116`

https://github.com/brave/brave-browser/assets/128532965/d1250788-f100-42d3-a55a-0981e971f362

`Verified in build 1.69.22`

https://github.com/brave/brave-browser/assets/128532965/86629ea3-b815-4b0f-8a21-62135eb0a248

**Comment by kjozwiak** [comment]
The above requires `1.67.118` or higher for `1.67.x` verification 👍 Removing the `QA Pass` label as the above will need to be re-checked via `1.67.x` once the RC's become available. However, used https://github.com/brave/brave-browser/issues/38847#issuecomment-2174388708 as the needed verification for uplift as per https://github.com/brave/brave-core/pull/24239#pullrequestreview-2123950812 & https://github.com/brave/brave-core/pull/24238#pullrequestreview-2123951068.

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240426.023.B4 release-keys
Brave build: 1.67.118
Chromium: 126.0.6478.71 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/38847#issue-2336786799
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Sync isn't working` notification is not shown
- Verified that the `Sync` chain was established successfully
- Verified above for fresh and upgraded profiles

---------------------------

`Fresh profile`

https://github.com/brave/brave-browser/assets/128532965/9f5796c6-4d77-4518-ba39-1507d450c398

`Upgraded profile`

https://github.com/brave/brave-browser/assets/128532965/8d0d7c01-61e1-4824-a1c9-d5ce787d4a28
