### ISSUE TITLE
Site search shortcut doesn't work with NTP Search widget

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#38846]
### Description

When added Site search shortcut via brave://settings/searchEngines, it worked as expected via omnibox however, the results are not show via NTP Search widget, i.e site is not loaded when using shortcut. Tested with two sites, cnn.com and wikipedia.com
(asked question via https://bravesoftware.slack.com/archives/C7VLGSR55/p1717615651534679)

### Steps to reproduce

1. Installed 1.67.105
2. launch Brave
3. enabled `#brave-ntp-search-widget` via `brave://flags`
4. opened brave://settings/searchEngines
5. added shortcut @news for CNN under Site search
6. opened a new tab entered @news in the omnibox
7. Got results as expected - loaded CNN home page
8. tried entering same shortcut @news

### Actual result

Redirected to search results instead of the site page

https://github.com/brave/brave-browser/assets/98358127/4647af32-fc1b-430d-af5a-ecc03a4879b3

### Expected result

Results should be same as omnibox, i.e. cnn.com should be loaded

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.67.105 Chromium: 126.0.6478.26 (Official Build) beta (64-bit)
-- | --
Revision | ff15eaa0be4f63abc388184895a7450c929375c8
OS | Windows 11 Version 23H2 (Build 22631.3672)

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

@rebron

**Comment by fallaciousreasoning** [comment]
I'm going to close this, as we don't support keyword searches from the NTP search box (internally we use keyword searches to change search engines, so I think this functionality would conflict).
