### ISSUE TITLE
[Follow up to 38651] Crash when dismissing JS alert

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#38849]
### Description

Crash when dismissing JS alert.

Related to https://github.com/brave/brave-browser/issues/38651

### Steps to reproduce

1. New install
2. Navigate to `https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_alert`
3. Tap on `Try it`
4. Press `OK` to dismiss alert

### Actual result

App crashes

Example | Example
-|-
![IMG_6292](https://github.com/brave/brave-browser/assets/17885425/ab798acb-c543-49be-8353-0779e0ada6df) | ![IMG_6293](https://github.com/brave/brave-browser/assets/17885425/674d9840-a706-4dc8-902f-0892bcf3bb73)

### Expected result

Should not crash

### Reproduces how often

Easily reproduced

### Brave version

1.66.1 (120)

### Device/iOS version

iPhone 12

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.66.122` or higher for `1.66.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.3.1` using version `1.66.122`

- Verified STR in https://github.com/brave/brave-browser/issues/38849#issue-2336892724 and also ensured these STR do not cause crash for exiting users (upgraded).
- Verified there is no issue suppressing alerts.

Example | Example | Example
-|-|-
![IMG_6328](https://github.com/brave/brave-browser/assets/17885425/4e39c5a8-3789-47d2-a93e-c0b5ecc9ac24) | ![IMG_6329](https://github.com/brave/brave-browser/assets/17885425/ac2bc76a-0379-4e19-a3c2-b2dd1eab467e) | ![IMG_6330](https://github.com/brave/brave-browser/assets/17885425/d1dda9c9-cdbc-4269-8072-8e898dca6658)
