### ISSUE TITLE
Enhancements for the PR uplifter CI job 

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#3885]
Just used the PR uplifter and the experience was 💯 
Nice work @bsclifton!

Here's a couple of minor suggestions: 
- [x] Have `Fix <issue link>` in the uplift PRs
- [x] Instead of assigning users, assign the brave approvers group

**Comment by bsclifton** [comment]
Fixed assigned users with https://github.com/brave/brave-core/pull/2251 - looking at adding fixed issues in the uplift now
