### ISSUE TITLE
Refactor parts of wallet's networks mojo API

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#38857]
### Description

Refactor parts of wallet's networks mojo API

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.136 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 47255350e0d135b2172cb9dd2ba344d3d7fe4572
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#23954](https://github.com/brave/brave-core/pull/23954)
- Verified [Native transfer](https://etherscan.io/tx/0x07fee4c75cbf9fe73c06052fe4f65f324d98a547b8ae2b00d3a63557257962a1), [ERC20 Transfer](https://etherscan.io/tx/0xdeaeba39fb095eea543e5ae41512953fec4cf1e2bb18834e9cd2030165a31e5f), [Swap](https://etherscan.io/tx/0x58e69f6ef1e11ca16fd391442c20ed360b8fd5461f9a2966b272619bd8acd643), [ERC721 transfer](https://etherscan.io/tx/0x300d91b4e86b82de7d3224426f38a8b101bb39a5835f6d58ac21eabaf3b75c03) works as expected
- Verified Gas calculation for Eip1559/Legacy networks work as expected

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.69.152 x64 build

- Verified steps from [brave/brave-core#23954](https://github.com/brave/brave-core/pull/23954)
- Verified [Native transfer](https://etherscan.io/tx/0x70924cba79d91a956ea4ad3622b30a7f603fa5981997d8e4cb9831b0fde11c54), [ERC20 Transfer](https://etherscan.io/tx/0x2546ae4961dc492bbdb7511be9e83f813a89cc6983b909ec1faafb0397c3682f), [Swap](https://scan.li.fi/tx/0xf19611b785edb87018ea8e390bd9a4e8c10ce5296750a51a9b971f70abf8b469), [ERC721 transfer](https://etherscan.io/tx/0x2546ae4961dc492bbdb7511be9e83f813a89cc6983b909ec1faafb0397c3682f) works as expected
- Verified Gas calculation for Eip1559/Legacy networks work as expected

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.0 running 1.69 (152)

- Verified steps from [brave/brave-core#23954](https://github.com/brave/brave-core/pull/23954)
- Verified [Native transfer](https://etherscan.io/tx/0x4066b1704addc84ef217c730e955d8bdd4d4e6c75fc5281791ff896e94bc561a), [ERC20 Transfer](https://etherscan.io/tx/0xe406cb941c9d395920fcc6476b82b9271ab1f1ad9bbab1b74b6e720708becc1c), [Swap](https://etherscan.io/tx/0x1f3ffc21d7a36b277f70243986ca8c006103d4c38d6be037acb9df6a8d31fac1), [ERC721 transfer](https://etherscan.io/tx/0x8ebaaece5185f455a45721cb23129732de0dbf802dd1775f4a5b5e1da68f662d) works as expected
- Verified Gas calculation for Eip1559/Legacy networks work as expected
