### ISSUE TITLE
The certificate viewer displays an expired cached cert issued 2 years ago and expired a year ago instead of the not-expired one retrieved from the server

### ISSUE THREAD

**Issue by Speeddymon** [brave/brave-browser#38855]
### Description

I'm updating a TLS certificate which expired this evening and applies to numerous customer facing FQDNs. The new certificate was deployed and I was able to verify that the updated certificate is being served via `openssl s_client` and web browsers where I don't have the site cached at all because I have never visited it in those browsers.

Unfortunately I think I can't share the link publicly without getting management approval so for the moment I hope to not talk specifics. The issue I'm reporting may have a security impact. Not sure.

There's a FQDN I most recently visited in the first half of 2023 which serves the certificate in question. The last time I visited this particular FQDN, the cached certificate was still valid (expired in mid-2023), so it was cached by Brave at that time. Today I updated the certificate and redeployed the app.

When I load up the FQDN in Edge or Firefox, and pull up the certificate viewer, I get the new cert and the new CA chain as expected. However, I have not visited this FQDN in those browsers before; there was previously no cache of this cert in those browsers, so this makes sense and confirms that both another Chrome based browser and a non-Chrome based browser are getting the right cert from an empty cache.

I then went to the FQDN in Brave, opened the Inspect pane, then right clicked on the main Refresh button in the navigation area near the top left, and clicked Empty cache and Reload.

After reloading, I went to check in the certificate viewer in Brave to confirm the old certificate would not be cached. To my surprise, our old cert (not from 2023-2024, but from 2022-2023) is visible along with the cert chain from the same time.

Brave's cache of this certificate should have expired long ago and the certificate viewer should be displaying the new one issued in 2024. It's only this one FQDN showing the really old cert, and only in the browser where I had it cached from over a year ago. Other FQDNs either show the new cert, or the one that expired this evening (we can verify with openssl that they are serving correctly though).

Question:

Is this considered a vulnerability here? Something like poisoning the browser cache at the right place can cause the cert viewer to show a different certificate for a site from what the browser received which can be used to deceive users into divulging personal info to a phishing URL? I mean I don't know how to insert the certificate into the cache but is that something that could be possible? It seems that the methods that handle loading and displaying the certificate for that viewer are improperly leveraging the cache instead of the server's response and that could be abusable, in my mind.

FYI- I'm posting from my personal account because while I found this at work, I can't actually reach Github from there. I do need to determine if this is something I need to report to my internal security team though.

Brave version 1.66.118 for Mac (x86_64). MacOS Sonoma 14.5.

### Steps to reproduce

1. Visit a TLS encrypted FQDN
2. Wait until the cert expires, renew it, update the app to use the new cert, get it working, test from another browser or device that it is working. Now wait until that new cert expires. Use short lifetimes if testing with self-signed certs or something. Do the same process to reissue and replace the cert again.
3. Visit the site in the web browser where you originally visited the site and cached the first cert
4. Right click the site and click Inspect
5. Ensure you can see the main reload/refresh button on the navigation panel (top left, not in the inspect pane)
6. Right click on that button and click Empty cache and hard reload
7. When the site finishes loading, open up the certificate viewer and observe the cached cert is displayed
8. Run `openssl x509 s_client -connect fqdn:443 -showcerts` and confirm your new cert is the one being sent to clients.

It seems like there is no way to clear the cached certificates for some of these FQDNs short of blowing away my whole profile and starting anew.

### Actual result

I see a cert from 2 years ago

### Expected result

I should see the one that was deployed

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave: 1.66.118 Chromium: 125.0.6422.147 (Official Build) (x86_64)
Revision: 07af53490e0a52336cfb99a376f87671be258049 (manually typed since it's on my Mac - apologies if there's a typo)
OS: macOS Version 14.5 (Build 23F79)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [X] in the latest version of Chrome

**Comment by diracdeltas** [comment]
We use the same TLS validation as Chrome, and I see you marked it as reproducible there. Have you tried reporting it to them?

**Comment by Luq2521** [comment]
Not yet, because you the only can respond my bookmark. Show me more tips

**Comment by Speeddymon** [comment]
> Not yet, because you the only can respond my bookmark. Show me more tips

?



> We use the same TLS validation as Chrome, and I see you marked it as reproducible there. Have you tried reporting it to them?

I honestly didn't reproduce it outside of Brave because it was a real world event and our cert expirations are yearly; but I knew logically that the same validation was used; I thought to report here first and confirm there aren't any changes to this part of Chromium in Brave that might be causing it before going upstream.

Thanks for confirming it's the same, with that I'll go ahead. Shall I close this or leave it open?

**Comment by diracdeltas** [comment]
Thanks @Speeddymon, I marked this as waiting for upstream and will close it out. If it's different for some reason in Brave vs Chrome let us know, but I'd be surprised.

**Comment by clicks** [comment]
I can observe the same behavior on one of our websites, the site is marked as secure and no warning issued,  but the details of the certificate show outdated information (e.g. long gone dates and wrong certificate authority)

Brave, showing outdated certificate information:
![Image](https://github.com/user-attachments/assets/3a11f185-ac17-46c2-ae12-879d758dce99)

Brave showing correct information in incognito mode:
![Image](https://github.com/user-attachments/assets/8ac9a3ce-bcd5-4462-ae2a-e18d2d615ef7)

Chromium shows correct information:
![Image](https://github.com/user-attachments/assets/ea9250b0-6728-4ead-a819-166003bbbb12)

**Comment by Raptus1** [comment]
I also have similar issues. after initially visiting my own site before adding proper LE cert, now certs show as invalid, even though they have been replaced.
