### ISSUE TITLE
Move `Delete browsing data` under Extensions in app menu

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#38852]
### Description

In the app/hamburger menu, `Delete browsing data...` should be underneath the Extensions line item and removed from the History sub-menu.

### Steps to reproduce

1. Open 1.68.x and higher
2. Open app/hamburger menu.
3. Notice placement of `Delete browsing data...` should be in the location per the Description.

### Actual result

`Delete browsing data...` is currently hard to find in the History sub-menu of the app/hamburger menu.

![image](https://github.com/brave/brave-browser/assets/5951041/e5b0ecec-a3a9-4ac4-9ecf-89dff8957de7)

### Expected result

`Delete browsing data...` should be at the top level of the app/hamburger menu
<img width="535" alt="Screenshot 2024-06-06 at 8 58 37 AM" src="https://github.com/brave/brave-browser/assets/5951041/d6c592cf-795f-4c6c-967d-ecb74d43df4f">
Figma link: `https://www.figma.com/design/Yl3SMPuL6mH4Vqtiv8ov0p/Untitled?node-id=0-1&t=49AOZ8XtPDgF02lb-0`

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.x

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.67.113` or higher for `1.67.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.67.113 Chromium: 126.0.6478.56 (Official Build) (x86_64)
-- | --
Revision | 2c6c9c73e7382e94dd9f7327dff55cb1fe56ff59
OS | macOS Version 13.6.7 (Build 22G720)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.67.113 Chromium: 126.0.6478.56 (Official Build) (64-bit) 
Revision	2c6c9c73e7382e94dd9f7327dff55cb1fe56ff59
OS	Linux
```
Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/38852#issue-2337109611 & https://github.com/brave/brave-core/pull/24025#issue-2337300716:

- ensured that Delete browsing data... was moved from History into the the root level of the Hamburger Menu below Extensions
- ensured that clicking on Delete browsing data... via the Hamburger Menu opens brave://settings/clearBrowserData

1.66.118  | 1.67.113
----- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/9acf3841-5782-4056-ab4e-2aa9a6b18bca)|![image](https://github.com/brave/brave-browser/assets/98358127/54dde908-ef15-4842-8618-c82142238408)
![image](https://github.com/brave/brave-browser/assets/98358127/ffa0928a-b087-4b27-9c88-9899735fbd86)|![image](https://github.com/brave/brave-browser/assets/98358127/f2a1f56d-97b2-47a4-8da2-62a362725e9b)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.67.113 Chromium: 126.0.6478.56 (Official Build) (64-bit)
-- | --
Revision | 2c6c9c73e7382e94dd9f7327dff55cb1fe56ff59
OS | Windows 11 Version 23H2 (Build 22631.3737)
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/38852#issue-2337109611 & https://github.com/brave/brave-core/pull/24025#issue-2337300716:

- ensured that Delete browsing data... was moved from History into the the root level of the Hamburger Menu below Extensions
- ensured that clicking on Delete browsing data... via the Hamburger Menu opens brave://settings/clearBrowserData


1.66.118 | 1.67.113
----- | -------
![image](https://github.com/brave/brave-browser/assets/98358127/fbbf00b2-e936-4900-b7d8-3a8497802986)|![image](https://github.com/brave/brave-browser/assets/98358127/6f25599a-b8c0-4b46-bc7e-94e54521499d)
![image](https://github.com/brave/brave-browser/assets/98358127/de882a8f-1895-48e8-8e9a-97de4f013004)|![image](https://github.com/brave/brave-browser/assets/98358127/0c788a1c-7465-4c77-a332-65a3b113d962)
