### ISSUE TITLE
AI Chat Conversation API "this conversation is too long" on first message with page content

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#38854]
### Description

The Conversation API client expects the server to truncate page content (since the server could be more accurate and deal with tokens rather than characters). However, the server part of this is not (yet) implemented. Therefore we should restore the client limits. Otherwise when attempting to summarize (or any other AI Chat action) on a conversation associated with a page that has a lot of content, the server will immediately send a "too long" error, and we will display the "This conversation is too long and cannot continue" error

### Steps to reproduce

1. Visit a large page, e.g. https://brianbondy.com/blog/187/cocodona-2024
2. Use the default mixtral model in Leo
3. Attempt to summarize via "Summarize this page" button

### Actual result

<img width="413" alt="image" src="https://github.com/brave/brave-browser/assets/741836/feccf64a-cac6-4809-9df8-90dfe8cbc269">

### Expected result

A response is received but a warning is shown about the page content being truncated

<img width="363" alt="image" src="https://github.com/brave/brave-browser/assets/741836/aecea3d3-e238-47c4-afc4-9e56d589a381">

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

1.68.64

### Android device

N/A

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by LaurenWags** [comment]
Requires `1.67.110` or higher for testing 👍🏻

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.67.110 Chromium: 126.0.6478.40 (Official Build) (64-bit)
-- | --
Revision | ac00bac697a2d9dad0b2e7f832391263816fd78d
OS | Windows 10 Version 22H2 (Build 19045.4412)
```
### Steps:
1. installed `1.67.110`
2. launched Brave
3. confirmed `Mixtral` is still the default
4. loaded `https://en.wikipedia.org/wiki/Firefox`
5. loaded `https://brianbondy.com/blog/187/cocodona-2024`
6. clicked on `Summarize this page` for each page, individually
7. confirmed page summarization
8. also confirmed and clicked on `Suggest questions...`

example | example | example
----------|----------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/5b74e235-eeb5-4c12-bf02-469dbf2d6ae5) | ![image](https://github.com/brave/brave-browser/assets/38657976/81322974-4861-4747-ba36-f80370137b4a) | ![image](https://github.com/brave/brave-browser/assets/38657976/6b551adf-73fb-4fcb-a5dc-5038df317977)
