### ISSUE TITLE
[Android] Remove kill switch option for VPN

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#38853]
We need to remove kill switch option based on the discussion we here : https://github.com/brave/reviews/issues/1637

**Comment by kjozwiak** [comment]
The above requires `1.67.109` or higher for `1.67.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.67.113`

- Ensured that `Kill switch` header message is removed from the `Always-on VPN` tutorial slides
- Ensured that `Kill switch` footer message is removed from the `Always-on VPN` tutorial slides

Example | Example | Example | Example
----------|----------|----------|------------
![Screenshot_20240613_133419](https://github.com/brave/brave-browser/assets/38657976/82128d68-9867-4d5e-b7ba-5c7bdd2ddff1) | ![Screenshot_20240613_133455](https://github.com/brave/brave-browser/assets/38657976/3452e770-d083-43c4-affb-e1bc43cb1f92) | ![Screenshot_20240613_133522](https://github.com/brave/brave-browser/assets/38657976/87390bb8-9526-489f-9fa7-2a95a56db0ce) | ![Screenshot_20240613_133540](https://github.com/brave/brave-browser/assets/38657976/3bf7304c-952b-4380-b831-de556f0bfbbe)
