### ISSUE TITLE
update URL bar icon for Install Password Manager - follow up to 38599

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#38864]
### Description

Follow up to https://github.com/brave/brave-browser/issues/38599

URL bar icon for "Install Password Manager" needs to be updated to Brave icon.

### Steps to reproduce

1. Clean profile 1.67.x CR 126 version
2. Navigate to 1brave://password-manager/passwords` page 
3. Look at `Install Password Manager` icon in URL bar

### Actual result

Icon is Chrome icon:

<img width="706" alt="Screenshot 2024-06-06 at 9 31 41 AM" src="https://github.com/brave/brave-browser/assets/28145373/194eb1a7-4981-483c-b99f-b896b156acac">

### Expected result

Should be Brave icon per https://github.com/brave/brave-browser/issues/38599#issuecomment-2151133711

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.67.108 Chromium: 126.0.6478.40 (Official Build) beta (x86_64)
-- | --
Revision | a286dc9f61f7d70fbf0157fcf3d924b00297d450
OS | macOS Version 13.6.7 (Build 22G720)

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @emerick

**Comment by kjozwiak** [comment]
The above requires `1.67.109` or higher for `1.67.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.67.109 Chromium: 126.0.6478.40 (Official Build) (x86_64)
-- | --
Revision | 98d88735f6123b755c0614e42e7868f70c35ec33
OS | macOS Version 13.6.7 (Build 22G720)
```
