### ISSUE TITLE
Tipping content creators on particular platforms

### ISSUE THREAD

**Issue by anfederico** [brave/brave-browser#3886]
This is a general question about why you can tip content creators on some platforms but not others.

For example, why can Brave users tip individual Youtube channels, but not tip individual Github developers?

**Comment by bsclifton** [comment]
cc: @davidtemkin @mandar-brave @rebron

**Comment by rebron** [comment]
Closing. Thanks for the suggestion. We have plans to add more platforms but no concrete dates yet.
