### ISSUE TITLE
Chromium 125 Feature: Compute Pressure not implemented correctly.

### ISSUE THREAD

**Issue by Trisplus** [brave/brave-browser#38867]
### Description

Chromium 125 Feature [Compute_Pressure](https://chromestatus.com/feature/5597608644968448) not implemented.

### Steps to reproduce

1. Go to: _https://www.chromiumchecker.com/_
2. Scroll 
3. Showing compute pressure feature not implemented.

### Actual result

Compute Pressure feature not passed.

![Screenshot_20240606-201113 (1)](https://github.com/brave/brave-browser/assets/157130680/88a6a308-f877-41ca-b194-15b6d8b15f1e)

### Expected result

Compute Pressure feature should be passed.
![Screenshot_20240606-201009 (1)](https://github.com/brave/brave-browser/assets/157130680/a9e56a45-41db-41ab-a92b-bce1ee4016d0)

### Reproduces how often

Easily reproduced

### Brave version

1.66.118

### Device

- Brand/model: Moto G64
- Android version: 14

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by ShivanKaul** [comment]
@Trisplus this should be fixed in Nightly: https://github.com/brave/brave-browser/issues/38341
