### ISSUE TITLE
[Wallet] Add "Group by collection" feature to portfolio NFTs page  

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#38865]
### Description

We should add a "Group by collection" feature to portfolio NFTs page to help organize their assets.

### Steps to reproduce

1. Create a wallet with multiple NFTs for a collection
2. Open wallet portfolio and click "NFTs"
3. click the filters icon
4. observe the available settings

### Actual result

No option is shown to group NFTs by collection

### Expected result

An option is shown to group NFTs by collection. Enabling this should re-render the NFTs list with NFTs from the same collection grouped per this design: https://www.figma.com/design/mvoB5HzIyQT9O4vbcA1XhP/NFT-(Wallet-2.0)?node-id=1858-19107&t=Pz7PjdmXXqY0OmZe-0

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

All

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.124 Chromium: 127.0.6533.73 (Official Build) beta (64-bit)
-- | --
Revision | dbc9035349f74e493f3293d93f4cbf35c597dfec
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24035](https://github.com/brave/brave-core/pull/24035)
- Verified `Group by collection` option is available in NFT settings
- Verified enabling the setting groups NFTs by collection
- Verified able to search when NFTs are grouped by collection
- Verified able to hide unowned NFTs when grouped by collection
- Verified `Group by collection` option is only available for NFTs and not for Assets
- Encountered [#40073](https://github.com/brave/brave-browser/issues/40073)

https://github.com/user-attachments/assets/7aefec74-19de-4122-b13e-9d8828806dd7
