### ISSUE TITLE
[Wallet] Connected Sites option missing when Non-Solana network selected (Can no Longer Disconnect from EVM Web3 Sites)

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#38868]
### Description

In Brave Wallet, the "Connected sites" settings button is not displayed if the current selected network is not a Solana network.  (Not shown when EVM networks are selected)

### Steps to reproduce

1. Open the wallet
2. switch the selected network to Solana mainnet
3. Click the "..." button
4. The settings are shown
5. the "connected sites" option is shown
6. switch the selected network to Ethereum Mainnet
7. The settings are shown
5. the "connected sites" option is not shown

### Actual result

the "connected sites" option is not shown if a non-solana network is selected

### Expected result

the "connected sites" option should be shown if the selected network is a EVM (Ethereum) or SVM (Solana) network

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.66.118 Chromium: 125.0.6422.147 (Official Build) (arm64) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

https://community.brave.com/t/connected-sites-gone-can-no-longer-disconnect-from-web3-sites/550314

**Comment by LaurenWags** [comment]
Requires `1.67.110` or higher for testing 👍🏻

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.110 Chromium: 126.0.6478.40 (Official Build) (64-bit)
-- | --
Revision | ac00bac697a2d9dad0b2e7f832391263816fd78d
OS | Windows 11 Version 23H2 (Build 22631.3672)

- Verified steps from issue description
- Verified connected sites settings when Ethereum/Solana/EVM network is set

https://github.com/brave/brave-browser/assets/17010094/b51f110a-6b17-4be6-8c73-b2f4b8553e36
