### ISSUE TITLE
Enable background playback by default

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#38869]
We have it enabled via griffin for 100% users on nightly, beta and 50% for stable channel.
We want to enable it by default for everyone and remove the griffin study after that.

**Comment by kjozwiak** [comment]
The above requires `1.67.115` or higher for `1.67.x` verification 👍 @hffvld @Uni-verse can use the STR/Cases from https://github.com/brave/brave-core/pull/24037#issuecomment-2163570120,

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP31.240426.023.B4 release-keys
Brave build: 1.67.115
Chromium: 126.0.6478.56 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/24037#issue-2338512286 and https://github.com/brave/brave-core/pull/24037#issuecomment-2163570120
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Background play` is ON by default as per https://github.com/brave/brave-core/pull/24037#issue-2338512286
- Verified that YT videos continue playing in the background when the toggle switch is ON

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/e2247121-cfe9-42f9-8181-97d18788a39e) | ![2](https://github.com/brave/brave-browser/assets/128532965/9c9ccf49-1ac3-496e-8c81-23ef64e36e78) | ![3](https://github.com/brave/brave-browser/assets/128532965/0dcef411-831d-4210-8fa9-040a7e4d367e) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/1790f5c8-ea0a-47ab-aaa5-57ac08665236) | ![2](https://github.com/brave/brave-browser/assets/128532965/fe4c7397-ba39-42df-b2d4-5412fc8c9fe3) | ![3](https://github.com/brave/brave-browser/assets/128532965/8bc48492-d22b-41f5-bb60-a8f06b77aefc) |
