### ISSUE TITLE
Brave crashes when enabling `News` from `NTP` and scrolling down the screen immediately

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#38871]
### Description

Brave crashes when enabling `News` from `NTP` and scrolling down the screen immediately.

### Steps to reproduce

1. Fresh install and launch Brave
2. Go through onboarding and land on `NTP`
3. Tap the `Turn on Brave News` CTA button and scroll down immediately > *Observe the crash*

### Actual result

Brave crashes when enabling `News` from `NTP` and scrolling down the screen immediately.

https://github.com/brave/brave-browser/assets/128532965/0ece4609-b980-4b88-9daf-1921475cdb94

### Expected result

Brave must not crash.

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.66.1 (120)
BraveCore: 1.66.120 (125.0.6422.165)

### Device/iOS version

- iPhone 14 / iOS 17.5
- iPad Air / iPadOS 16.7.2

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.69 (156)`

- Ensured that crash does not happening when enabling Brave News from NTP and immediately scrolling down the feed.

Example | Example
-|-
![IMG_7143](https://github.com/user-attachments/assets/e400b9cc-8304-478a-96e4-f1dc1624188d) | ![IMG_7144](https://github.com/user-attachments/assets/a66c1ab2-e800-421d-b140-10c02f0ba651)
