### ISSUE TITLE
[Windows] Client changes for the distraction free A/B test

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#38874]
### Description
Search `A B test - Windows - Simplified post-install experience` in GDrive for the requirements.

**Comment by simonhong** [comment]
working on this. cc @bsclifton

**Comment by bridiver** [comment]
@timchilds is there a link to a spec or something? It seems that the current code will make changes after 24 hours even if it's in the middle of a browsing session which seems like it would be disruptive and confusing, is this intended?

**Comment by chrismore** [comment]
> @timchilds It seems that the current code will make changes after 24 hours even if it's in the middle of a browsing session which seems like it would be disruptive and confusing, is this intended?

Yes, that is possible. But, this 5% sample a/b test of new users and is not meant to dictate the final future onboarding experience as it is just testing if minimizing distractions on day 0 has an impact on returning for day 1. Also, 90% of the bits flipped for the day 0 experiment are on the new tab page, which would should not be disruptive if they are acting using a website. It is only after they open up a new tab, would they see new elements on the NTP to interact with. 

If we find it true that keeping it simple on day 0 and just focusing on them getting browsing the web with the value Shields provides, we can figure out how to best progressively reveal the rest of our great features without a) being distracting b) overwhelming them with too much. If this a/b is successful at day 0 retention, it will not be deployed. The insights will help with designing a user-first onboarding experience that is better for the user.

**Comment by bridiver** [comment]
> If we find it true that keeping it simple on day 0 and just focusing on them getting browsing the web with the value Shields provides

How do we know they didn't drop out because the settings changed unexpectedly? This change in behavior after 24 hours could potentially have a more negative affect on retention than starting with them.

**Comment by bridiver** [comment]
> @bridiver in that case we would see the drop in the A/B test retention data. The drop would shift from D1 --> D2 for the exposed users. That would be a learning and inform the next A/B test. cc @chrismore

but my point is how do you know which one is causing the effect or whether it's a mix of the two (which is mostly likely the case)? You could be seeing a slight bump from one and a slight drop from the other that offset each other to some degree. Wouldn't it make more sense to at least separate them out by extending the period before the setting change so you can measure drop out rates for the two variables independently?

**Comment by chrismore** [comment]
> > @bridiver in that case we would see the drop in the A/B test retention data. The drop would shift from D1 --> D2 for the exposed users. That would be a learning and inform the next A/B test. cc @chrismore
> 
> but my point is how do you know which one is causing the effect or whether it's a mix of the two (which is mostly likely the case)? You could be seeing a slight bump from one and a slight drop from the other that offset each other to some degree. Wouldn't it make more sense to at least separate them out by extending the period before the setting change so you can measure drop out rates for the two variables independently?

Understood. This is the first of a series of a/b tests and there will be follow up tests to isolate variables.

**Comment by bridiver** [comment]
It seems very odd to me that we would start with a flawed study that can't differentiate between the two effects when it would be trivial to extend out the period for changing the settings. If we get back a positive result then we probably want to proceed with other experiments, but what if we get a false negative because the setting change hurts retention as much or more than the day zero default settings help it? We have now lost some users that we might have kept and we also don't know if the default settings had any positive impact or not. 

I'm also still a bit concerned about this in general even as a small test. I know I would be really annoyed if settings just suddenly changed on me and wonder what was going on, whether it was a bug or Brave doing something sneaky. My feeling is that for this small sample we should not revert the defaults back at all until we have some method to ask them or notify them somehow so they don't just suddenly change without warning. That accomplishes the goal of testing how this affects retention without introducing this second factor, no?

**Comment by LaurenWags** [comment]
marking as `QA/Blocked` per discussion via https://bravesoftware.slack.com/archives/C7VLGSR55/p1721306267864729?thread_ts=1721253014.926999&cid=C7VLGSR55. Per suggestion of @simonhong waiting on https://github.com/brave/brave-browser/issues/39810 to be fixed and uplifted prior to testing.

cc @kjozwiak @rebron @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.68.134` or higher for `1.68.x` verification 👍 Please use https://github.com/brave/brave-core/pull/24731#issuecomment-2259329243 as the template for verification notes 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.68.134 Chromium: 127.0.6533.88 (Official Build) (64-bit)
-- | --
Revision | 71f3c9cc80f92022892bbf6a22c0450ea056ade4
OS | Windows 10 Version 22H2 (Build 19045.4651)
```
