### ISSUE TITLE
Switch to Chainstack RPC proxy endpoints

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#38872]
### Description

We're currently using Infura as our main RPC provider, and the code in brave-core hardcodes this. We'd like to use a generic proxy URL format, which uses Chainstack under the hood. This allows us to easily switch providers whenever we want.

### Steps to reproduce

N/A

### Actual result

Portfolio balances should load correctly without any console errors. Infura RPCs are used for making requests.

### Expected result

Portfolio balances should load correctly without any console errors. Chainstack RPCs are used for making requests.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.66.118

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [X] in the latest version of Chrome

### Miscellaneous information

Ideally uplift this to 1.67.x so we can save on Infura bills. We're currently paying for both Infura as well as Chainstack RPCs.

**Comment by kjozwiak** [comment]
The above requires `1.68.92` or higher for `1.68.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.68.92 Chromium: 126.0.6478.71 (Official Build) beta (64-bit)
-- | --
Revision | 393b9968e233540a48f04d74bc4601a05d3a0169
OS | Windows 11 Version 23H2 (Build 22631.3737)

- Verified steps from [brave/brave-core#24045](https://github.com/brave/brave-core/pull/24045)
- Verified balances work as expected on Portfolio
- Verified no console errors when loading Portfolio balance
