### ISSUE TITLE
[Android] Client changes for the distraction free A/B test

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#38875]
### Description
Search `A B test - Android - Simplified post-install experience` in GDrive for the requirements.

**Comment by LaurenWags** [comment]
marking as `QA/Blocked` per discussion via https://bravesoftware.slack.com/archives/C7VLGSR55/p1721306267864729?thread_ts=1721253014.926999&cid=C7VLGSR55. Per suggestion of @simonhong waiting on https://github.com/brave/brave-browser/issues/39810 to be fixed and uplifted prior to testing.

cc @kjozwiak @rebron @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.68.134` or higher for `1.68.x` verification 👍 Please use https://github.com/brave/brave-core/pull/24731#issuecomment-2259356791 as the template for verification notes 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6 Pro` running `Android 15` running the following build(s):

```
Brave | 1.68.134 Chromium: 127.0.6533.88 (Official Build) (64-bit)
--- | ---
Revision | 71f3c9cc80f92022892bbf6a22c0450ea056ade4
OS  | Android 15; Build/AP31.240617.009; 35; REL
```

### `Test Case #1` - Fresh/New User

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/24617#issue-2404247933, connected the `Pixel 6 Pro` to a `Linux` VM and ran `adb shell "echo ' --enable-features=BraveDayZeroExperiment:variant/a' > /data/local/tmp/brave-test-day-zero-expt"` as per the following:

![image](https://github.com/user-attachments/assets/3809ccf4-4209-4468-93de-2af0c9523488)

Once completed, installed `Brave` and ensured that the following items have been removed:

* ensured that the `rewards` button from toolbar is not visible anymore
* ensured that NTP SI images are not being displayed when opening new NTP tabs
* ensured that the `Brave News` peek onboarding card is not visible when swiping down via the NTP
* ensured that `Favorites` are still being added into the NTP when visiting websites

**`Example`** | **`Example`** | **`Example`**
---------------|----------------|-----------------
![1000001863](https://github.com/user-attachments/assets/9d0dc4d3-c8ad-46c7-8f99-b62ea5fe9367) | ![1000001864](https://github.com/user-attachments/assets/dd8a04f4-bc27-4935-ba2c-e360727a57ac) | ![Screenshot_20240731-114059](https://github.com/user-attachments/assets/09473c96-266f-4d73-ae23-0ec62e239d04)

* ensured that you can enable the `Rewards` icon within the toolbar without any issues via `Appearance`
  * ensured that you can run through the `Rewards` onboarding within the panel without issues
* ensured that you can enable `Brave News` without any issues/crashes

**`Example`** | **`Example`** | **`Example`** |  **`Example`**
---------------|----------------|-----------------|------------------
![1000001865](https://github.com/user-attachments/assets/1fb54f8c-79c7-4f22-9f00-f64e62dd8709) | ![1000001866](https://github.com/user-attachments/assets/a80a0218-b981-4acb-b4e0-96aaa3e518a0) | ![1000001867](https://github.com/user-attachments/assets/b8768e63-20e3-4f04-977d-15e71f41b977) | ![1000001868](https://github.com/user-attachments/assets/70bee139-d00a-413e-a22c-a7a0886d4c0d)

* ensured that inline `ads` are being displayed via `Brave News` once `Rewards` has been enabled
* ensured that `NTP SI` are being displayed/shown once `News tab page ads` are enabled via `brave://rewards`
* ensured the ad notifications are still being triggered without issues

**`Example`** | **`Example`** | **`Example`** |  **`Example`**
---------------|----------------|-----------------|------------------
![1000001870 (1)](https://github.com/user-attachments/assets/cfbc1a38-3de5-445f-ade9-37b888ca9f0b) | ![1000001871 (1)](https://github.com/user-attachments/assets/635cfd73-9651-40df-9b3e-304909e007d2) | ![1000001872 (1)](https://github.com/user-attachments/assets/7c528d44-e104-4fc3-af8f-39ffe0f9524c) | ![1000001873 (1)](https://github.com/user-attachments/assets/eda74f39-f9c0-4fce-892e-ac27505fa534)

### `Test Case #2` - Existing Users

Using the `Linux` VM as mentioned above, launched/used the following commands to remove the `day-zero` test:

* removed via `adb shell "rm /data/local/tmp/brave-test-day-zero-expt"`
* ensured it's removed via `db shell "cat /data/local/tmp/brave-test-day-zero-expt"`

![image](https://github.com/user-attachments/assets/c0f866f6-590f-46c8-8bc2-dbacf375eec8)

* installed/launched `1.68.134 Chromium: 127.0.6533.88`
* ensured that all the expected UI elements are visible/available on first launch
* populated the NTP with a few `Favicons`
* enabled both `Rewards` & `Brave` news

**`Example`** | **`Example`** | **`Example`** |  **`Example`**
---------------|----------------|-----------------|------------------
![Screenshot_20240731-114931](https://github.com/user-attachments/assets/180ca888-f690-432c-91aa-2790583e8ce6) | ![Screenshot_20240731-114943](https://github.com/user-attachments/assets/b42351e4-f011-46b4-8640-26781701c291) | ![Screenshot_20240731-114947](https://github.com/user-attachments/assets/62a4b3d0-340c-47b4-94e8-34c62aec0edc) | ![Screenshot_20240731-115038](https://github.com/user-attachments/assets/4b3d6073-a84e-42d0-933b-f66b342ac2a5)

Once the above was completed, launched `adb shell "echo ' --enable-features=BraveDayZeroExperiment:variant/a' > /data/local/tmp/brave-test-day-zero-expt"` and ensured that none of the UI elements are being removed as the above is a existing user as per the following:

![image](https://github.com/user-attachments/assets/c6fd1243-bd7d-4a5c-8355-61656008a30f)

* ensured that `Brave News` is still enabled and being displayed without any issues
* ensured that `Brave Rewards` is still enabled and `NTP SI` are being displayed
* ensured that the same `Favicons` are still present/visible via the NTP
* ensured that `ads` notifications are still being displayed

**`Example`** | **`Example`** | **`Example`** |  **`Example`** | **`Example`**
---------------|----------------|-----------------|-----------------|-----------------
![1000001878](https://github.com/user-attachments/assets/0e046f10-5c44-45d1-bb12-408485b04452) | ![1000001879](https://github.com/user-attachments/assets/ee32f132-58a8-438b-9734-2a5a7a45c87d) | ![1000001882](https://github.com/user-attachments/assets/b094a67e-e9f2-4859-9f30-ca99fe3718ab) | ![1000001881](https://github.com/user-attachments/assets/eb00fc36-55bb-45a9-9836-2d2bce55983f) | ![1000001880](https://github.com/user-attachments/assets/b7477cc1-9742-42a1-9b57-ade9dfce7ba9)

### `Test Case #3` - P3A Disabled/UI changes not applied/removed

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/24617#issue-2404247933, connected the `Pixel 6 Pro` to a `Linux` VM and ran `adb shell "echo ' --enable-features=BraveDayZeroExperiment:variant/a' > /data/local/tmp/brave-test-day-zero-expt"` as per the following:

![image](https://github.com/user-attachments/assets/c6fd1243-bd7d-4a5c-8355-61656008a30f)

* disabled `P3A` via the onboarding flow when first launching `Brave`
* ensured that the UI elements that were removed from `Test Case #1` are not being removed when `P3A` has been disabled

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------|----------------
![1000001883](https://github.com/user-attachments/assets/864ddd95-492d-4732-96b8-69cb40a23cc8) | ![1000001884](https://github.com/user-attachments/assets/d9030d08-f903-4043-8fa7-09d8fa77fc19) | ![1000001885](https://github.com/user-attachments/assets/89978349-e3ba-4efd-a856-fd91a1cbda3b) | ![1000001886](https://github.com/user-attachments/assets/cc010f29-863b-421c-9bc9-c8d79833a61c) | ![1000001887](https://github.com/user-attachments/assets/d02e9d0f-3953-4165-83aa-c0727f7e6b02)
