### ISSUE TITLE
SIWE failed in tally.xyz

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#38878]
### Description

We added addition uri check which is not specified in [eip-4361](https://eips.ethereum.org/EIPS/eip-4361#wallet-implementer-steps) and it failed in the case of tally sign in.
https://bravesoftware.slack.com/archives/CBP2ZKC0H/p1717697713982729?thread_ts=1717689824.083089&cid=CBP2ZKC0H

### Steps to reproduce

1.  Navigate to https://www.tally.xyz/gov/wormhole
2. Click "Connect" and approve
3. Click "Sign in"

### Actual result

<img width="409" alt="Screenshot 2024-06-06 at 11 40 07" src="https://github.com/brave/brave-browser/assets/11330831/cd99dc5d-4ed1-4a31-8919-e97d65693606">

### Expected result

There should be no errors.

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

Brave | 1.68.61 Chromium: 126.0.6478.26 (Official Build) nightly (x86_64)
-- | --
Revision | 33acf8f3b22f4ec9f640dc46911d4a9ea15654af
OS | macOS Version 14.5 (Build 23F79)

### Android device

device info is not relevant

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.68.92` or higher for `1.68.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.68.92 Chromium: 126.0.6478.71 (Official Build) beta (64-bit)
-- | --
Revision | 393b9968e233540a48f04d74bc4601a05d3a0169
OS | Windows 11 Version 23H2 (Build 22631.3737)

- Verified steps from issue description
- Verified able to sign and connect on `https://passport.gitcoin.co/`
- Verified able to sign and connect on `https://www.tally.xyz/gov/wormhole`

https://github.com/brave/brave-browser/assets/17010094/969ce986-86ec-4acd-903a-a373da06ed5a

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.68.99 x64 Beta build
- Verified steps from issue description
- Verified able to sign and connect on `https://passport.gitcoin.co/`
- Verified able to sign and connect on `https://www.tally.xyz/gov/wormhole`

https://github.com/brave/brave-browser/assets/17010094/281a6ee6-82e4-4025-bf36-19391252d147
