### ISSUE TITLE
cvent.com fails to load

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#3887]
## Steps to Reproduce

   1. Navigate to http://www.cvent.com/m-events/Info/Summary?e=61db141c-4587-4a0b-afd4-334003cc3ef2&RefID=3.25
   2. Fails to load

## Actual result:
Fails to load

## Expected result:
Should load

## Reproduces how often: 
Easily

## Brave version (brave://version info)
0.64.8 Chromium: 73.0.3683.75 (Official Build) nightly (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

**Comment by ryanbr** [comment]
Turn off "upgrade to https" and re-test.

**Comment by ryanbr** [comment]
Re-tested this with a new link `https://www.cvent.com/venues/miami/cvb/greater-miami-convention-visitors-bureau/venue-e09da1a6-c43a-419f-af4b-0ff9ebde5e73`  Seems to load okay now, can you confirm @jumde ?

**Comment by bsclifton** [comment]
Closing - works for me 😄
