### ISSUE TITLE
Booking on https://www.amtrak.com/ fails

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#38884]
### Description

Unable to book on https://www.amtrak.com due to fingerprinting

### Steps to reproduce

1. Open https://www.amtrak.com
3. Select various destinations  and date
4. Click "Find Trains"
5. Endless loading

### Actual result

Endless loading, eventually erroring with "We've experienced an unknown error. Try again later or call us at 1-800-USA-RAIL."

![amtrak-disabled](https://github.com/brave/brave-browser/assets/1659004/bd06a3c4-cf37-4eb8-bd30-05ce315e7183)

### Expected result

Load the trains time tables

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.66.118 Chromium: 125.0.6422.147 (Official Build) (arm64)
Revision | 07af53490e0a52336cfb99a376f87671be258049
OS | macOS Version 14.5 (Build 23F79)

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Disabling Fingerprinting helps

**Comment by ryanbr** [comment]
Working in release.

**Comment by emrecio** [comment]
booking still failing
