### ISSUE TITLE
[Wallet/iOS]: Hide Zero Balance Tokens in Account Details

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#38882]
an iOS version of https://github.com/brave/brave-browser/issues/37194

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.0 Beta running 1.69 (147)
- Verified steps from [brave/brave-core#24135](https://github.com/brave/brave-core/pull/24135)
- Verified `Hide Zero Balance` from filter hides all tokens with zero balance

https://github.com/user-attachments/assets/718069ca-74e8-4734-8b7d-fbebed59af6c
