### ISSUE TITLE
Remove `Learn more` link from WireGuard fallback to IKEv2 dialog

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#38888]
### Description

If a person is a Brave VPN customer on Windows and WireGuard fails to start for whatever reason, a fallback dialog is shown.

There is a `Learn more` link which does not go anywhere. We intended to make a page - creating https://github.com/brave/brave-browser/issues/31652 but we never actually finished the article. We should remove the link since it's dead.

### Steps to reproduce

1. Install Brave as admin; verify WireGuard VPN services are installed
2. Verify `Use WireGuard protocol in Brave VPN` is enabled on brave://settings/system
3. Login to account.brave.com. Buy VPN.
4. Verify VPN works (connect, disconnect).
5. Disconnect from VPN. Exit Brave.
6. Intentionally break VPN by creating a registry entry for the specific release channel you're using

    For example, on Development (building from source), you can:
    - Windows + R, type `regedit`, hit enter
    - Accept UAC elevation
    - In the path box, paste in `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Vpn\BraveDevelopmentVpnWireguardService`
    - Inside this key, create a new DWORD value (32-bit) called `tunnel_launches_counter`
    - Set this value to 4

7. Now you can launch Brave and try to connect to VPN.
8. The fallback dialog will show up

### Actual result

![image](https://github.com/brave/brave-browser/assets/4733304/803a2c94-633c-40e2-9977-3a746b8c7a47)

### Expected result

No `Learn more` link
![image](https://github.com/brave/brave-browser/assets/4733304/16dd95e9-63cc-4a62-b367-ff85707b738a)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

all

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.69.22 Chromium: 126.0.6478.71 (Official Build) nightly (64-bit)
-- | --
Revision | f08b31c4a921392ba24b4a3c33ef320147999c62
OS | Windows 10 Version 22H2 (Build 19045.4529)
```

example | example | example
----------|-----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/7903ae44-2249-4b8b-a08f-cad8552a7ec4) |

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

```
Brave | 1.69.22 Chromium: 126.0.6478.71 (Official Build) nightly (64-bit)
-- | --
Revision | f08b31c4a921392ba24b4a3c33ef320147999c62
OS | Windows 10 Version 22H2 (Build 19045.4529)
```

### Steps:
1. installed `1.69.22` (confirmed user-access control prompt during install)
2. renamed `wireguard.dll` to `wireguard.dll.bad` in `C:\Program Files\BraveSoftware\Brave-Browser-Nightly\Application\126.1.69.22\BraveVpnWireguardService`
3. ensured `Use WireGuard protocol in Brave VPN` was checked
4. purchased, configured, and attempted to connect to `Brave VPN`
5. confirmed `Brave VPN on Windows` error-message dialog (modal)

### Confirmed *NO* `Learn more` hyperlink, per test plan in https://github.com/brave/brave-browser/issues/38888#issue-2339795162

example | example | example | example
----------|----------|-----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/ed99dead-1d7a-485f-ae48-a0590a47f5b3) | ![image](https://github.com/brave/brave-browser/assets/387249/eced50e0-9119-469e-8fff-0493dd1c8a7d) | ![image](https://github.com/brave/brave-browser/assets/387249/eeafdf25-b4a8-485c-9fe2-5feef14723ef) | ![image](https://github.com/brave/brave-browser/assets/387249/a438aac5-6ec6-4fdd-9fa6-f0516a848e29)

**Comment by stephendonner** [comment]
Left this as-is without verifying with the label, so it can also get a verification on `Win11-x64`, when @MadhaviSeelam or others have a chance 👍

**Comment by LaurenWags** [comment]
@bsclifton could you please add `release-notes/exclude` or `release-notes/include` label as appropriate? Thanks!

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.69.121 Chromium: 127.0.6533.57 (Official Build) beta (64-bit)
-- | --
Revision | 6ab76d6b98b9a4c22c06c9bb3487062edbbfb3f2
OS | Windows 11 Version 23H2 (Build 22631.3880)
```

1. installed 1.69.22 (confirmed user-access control prompt during install)
2. purchased, configured, and attempted to connect to Brave VPN
3. ensured Use WireGuard protocol in Brave VPN was checked
4. verified `Brave VPN Wireguard Service` is installed via taskmanager
5. killed the `Brave VPN Wireguard Service` few times 
6. verified `Brave VPN on Windows` IKEv2 dialog (modal) is shown
7. confirmed `Learn more` link is not shown 

step 2 | step 3 | step 4 | step 5 | step 6-7  
----- | ----- | ----- | ----- | ------  
![2024-07-22_14h33_25](https://github.com/user-attachments/assets/eea88c27-8436-4383-b2ee-45a2c44c54d8)|![2024-07-22_14h33_35](https://github.com/user-attachments/assets/62ca4ba6-67bb-4af9-ba76-b4d86da373e7)|![2024-07-22_14h34_12](https://github.com/user-attachments/assets/27e4bc4f-6111-4370-be77-a20903ccf948)|![2024-07-22_14h35_56](https://github.com/user-attachments/assets/dadd889d-4bd9-44fd-ba50-83e91104c080)|![2024-07-22_14h37_59](https://github.com/user-attachments/assets/f4dcf43a-9720-46b0-9c07-2f50cadc1ef1)
