### ISSUE TITLE
Deleting browsing data dialog is too small

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#38898]
### Description

The "Delete browsing data" dialog box is too small and currently obscures the "Reset Brave Rewards data" link. This probably happened when the notice about search history was added in Chromium. It does however make it look like we are intentionally hiding this option behind a scrollbar.

### Steps to reproduce

1. Open `brave://settings/clearBrowserData`

### Actual result

![Screenshot from 2024-06-07 11-30-51](https://github.com/brave/brave-browser/assets/167821/4438ea87-8eac-497b-9107-bdd0fbc7c52d)
![Screenshot from 2024-06-07 11-31-00](https://github.com/brave/brave-browser/assets/167821/2aa93d0a-3e0f-4f12-9a8a-9e38a88f1066)

### Expected result

The scroll bar should not be present and the dialog box should be big enough to fit the extra link we add:
![Screenshot from 2024-06-07 11-34-55](https://github.com/brave/brave-browser/assets/167821/94f7fb31-5615-42e8-96d2-665357805ef8)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave	1.67.105 Chromium: 126.0.6478.26 (Official Build) beta (64-bit) 
Revision	ff15eaa0be4f63abc388184895a7450c929375c8
OS	Linux
```

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.69.73 Chromium: 127.0.6533.26 (Official Build) nightly (64-bit)
-- | --
Revision | ebfe046ab1178f2195d83704420ed1ffa0370804
OS | Windows 10 Version 22H2 (Build 19045.4598)
```






example | example
----------|-----------
![image](https://github.com/brave/brave-browser/assets/387249/819bd785-776c-4d6b-98da-d76cd17f503a) | ![image](https://github.com/brave/brave-browser/assets/387249/7b997178-aa0f-43ba-8a70-863df29135bd)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.69.122 Chromium: 127.0.6533.57 (Official Build) beta (64-bit)
-- | --
Revision | bd77e9b76a8e67ff2bf9f62f1df7d60378ca811f
OS | Windows 11 Version 23H2 (Build 22631.3880)
```

1. installed 1.69.122
2. launched Brave
3. opened `brave://settings/clearBrowserData`

#### Compared dialogs, and confirmed "Your search engine is Brave...." displays without need for a scrollbar


1.67.134 | 1.69.122
------ | ------
![image](https://github.com/user-attachments/assets/a2bd0cc8-b34b-4b8e-9130-14d2cacb6cca)|![image](https://github.com/user-attachments/assets/8daaa28f-c751-49b4-8771-919add439dda)
