### ISSUE TITLE
[iOS] - Brave-Leo Apple Pay not working on Nightly or Beta

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#38897]
### Description

- Purchasing Leo on Nightly or Beta does not work

### Steps to reproduce

1. Try to purchase Leo on Nightly or Beta with Apple Pay

### Actual result

- Fails to purchase with the error "Appstore Error"

### Expected result

- Should purchase

### Reproduces how often

Easily reproduced

### Brave version

1.63.x+

### Device/iOS version

iPhone

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by JoinEvgen** [comment]
Старт

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using versions `1.70.99 (Beta)` & `1.71.58 (Nightly)`

#### Nightly App

- Ensured in-app purchase flow for Leo is working.
- Ensured Leo status upgrades to Premium after completing purchase.

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_7232](https://github.com/user-attachments/assets/917ce09e-1d6b-4d31-80d6-d73490fd958b) | ![IMG_7233](https://github.com/user-attachments/assets/85198f3b-ce38-4187-b7b5-4d139510b60a) | ![IMG_7234](https://github.com/user-attachments/assets/6a0c148e-c696-42d8-b856-f2b66990171a) | ![IMG_7235](https://github.com/user-attachments/assets/d10b1af6-dba5-4043-b850-080ecb87d989) | ![IMG_7236](https://github.com/user-attachments/assets/c543abad-333d-4914-9379-dd66f434fdba)

#### Beta App

- Ensured that Leo cannot be purchased on beta through in-app purchase (expected).

Example | Example | Example | Example
-|-|-|-
![IMG_7228](https://github.com/user-attachments/assets/95c1cbc5-9467-460c-a535-35c91346cc46) | ![IMG_7229](https://github.com/user-attachments/assets/cd03bb5c-67bb-4a8f-b410-873cc4ec11b4) | ![IMG_7230](https://github.com/user-attachments/assets/cdc4cc16-bbaf-43e1-8d24-4bfabb5c6cbc) | ![IMG_7231](https://github.com/user-attachments/assets/42441915-1852-469a-be45-cf58fc602acc)
