### ISSUE TITLE
[CR 126] hamburger "Update" prompt is missing a color when using light theme

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#38899]
### Description

When the hamburger shows that an update is available, it displays in green, orange, or red. These colors display fine on dark theme but on light theme only green and red show. The second color (presumably orange to match dark theme) just displays as black.

This is not new with C126, occurs on 1.66.x with C125 also.

### Steps to reproduce

1. Launch via terminal with `--args --enable-logging=stderr --simulate-upgrade`
2. Watch the hamburger menu
3. After ~20-30s it will show the green "Update" notification on the hamburger menu (works on both light and dark theme)
4. After another ~20-30s it will show the orange "Update" notification on the hamburger menu in dark theme only. Light theme displays this as black.
5. Finally after another ~20-30s it will show the red "Update" notification on the hamburger menu (works on both light and dark theme)

### Actual result

second update color on light theme doesn't match dark theme

<img width="114" alt="1 67l" src="https://github.com/brave/brave-browser/assets/28145373/d8df249b-8e81-4307-ad1c-c75cd28dee2c">

### Expected result

Light theme should probably also have an orange color

<img width="113" alt="1 67d" src="https://github.com/brave/brave-browser/assets/28145373/af6c8a42-7eeb-496b-8bea-eed1b6eef2a4">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.66.x, 1.67.x

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

For comparison, here's 1.66.x vs 1.67.x:

1.66.x | 1.67.x
--- | ---
<img width="1108" alt="1 66 dk theme" src="https://github.com/brave/brave-browser/assets/28145373/5e0c7a18-37eb-44e9-a524-708a3f2fb897"> | <img width="1192" alt="1 67 dk theme" src="https://github.com/brave/brave-browser/assets/28145373/2c5b9318-2a9d-4758-943b-fa0242856b82">
<img width="1189" alt="1 66 lt theme" src="https://github.com/brave/brave-browser/assets/28145373/816fb7bd-bd21-44a1-a8d0-e206012ae9eb"> | <img width="1196" alt="1 67 lt theme" src="https://github.com/brave/brave-browser/assets/28145373/c09c23fc-7e70-432a-97f0-13b827daf519">

cc @rebron @aguscruiz

**Comment by simonhong** [comment]
checking

**Comment by kjozwiak** [comment]
@LaurenWags I couldn't get `Nightly` to change to the `Orange` phase after trying a bunch of methods/waiting and moving the time forward. I managed to reproduce it on `Release` using your STR/Cases pretty easily as per the following:

![Old2](https://github.com/brave/brave-browser/assets/2602313/b153d3bf-70c8-42db-b855-f934669a8982)

Going to uplift the above as it's a simple colour change. This is the last issue that needs to be uplifted before we can kick of the final RC. Hopefully it's easier to check/verify on the RC rather than on `Nightly`.

**Comment by kjozwiak** [comment]
The above requires `1.67.115` or higher for `1.67.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.67.115 Chromium: 126.0.6478.56 (Official Build) (x86_64)
-- | --
Revision | e1f8b4850805c2eea958bad7220c5e6e9202efaa
OS | macOS Version 13.6.7 (Build 22G720)
```
