### ISSUE TITLE
Review whats tracked in the repo / initial clone situation

### ISSUE THREAD

**Issue by snyderp** [brave/brave-browser#389]
(initially mistakenly filled on brave/browser-laptop)

With a clean build / pull / sync, there are some confusing (to me) aspects of the repos.  @garrettr suggested creating an issue to track / work them out.

browser-laptop
---
- `vendor/depot_tools` is not ignored, but changes regularly.  Should this be tracked, ignored, or committed on changes?
- `yarn.lock` not tracked or ignored
- `src/.gitkeep` is deleted.

brave/brave-core
---
-  `package-lock.json` and `vendor/` are untracked
-  The repo URL is https://github.com/brave/brave-core.git, should be `git@…` no?

**Comment by RyanJarv** [comment]
So src/.gitkeep was meant to keep the directory around in git which prevented windows from erring out when the chrome src isn't checked out yet.. but now mentioning that I'm somewhat suspicious why that was an issue in the first place.

Curious do we have any plans to track src/ as well? I think ideally a yarn run init on a given commit of brave-browser will always pull down the same code.

**Comment by garrettr** [comment]
I have also recently been encountering issues with untracked `package-lock.json` in `src/brave/vendor/brave-extension`, particularly upon `yarn run sync --all`.

**Comment by RyanJarv** [comment]
Been looking into the chrome/google tools a bit more recently and seems this is all handled by gclient for them, may be worth looking into if we can reuse that for the repos we left out.

**Comment by garrettr** [comment]
The untracked `package-lock.json` in brave-core has been getting on my nerves recently. Shouldn't it be tracked? If not we should gitignore.

**Comment by bsclifton** [comment]
@snyderp can this issue be closed?

**Comment by snyderp** [comment]
@bsclifton I don't mind closing it, but should be marked "won't fix" then.  but I don't think anything has been changed
