### ISSUE TITLE
Show split view menu button only when it's hovered

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#38908]
Split view menu button can cover part of web pages, so we should make it narrower when it's not hovered.

**Comment by TEMP-ad** [comment]
This looks nice and works good, but when you click the Swap tab positions button, then as long as you don't touch the button, it will stay expanded and you can click on other element in the window, and even navigate or use the resize bar and the button never changes.

https://github.com/brave/brave-browser/assets/156715894/06a71c6b-a748-4469-a2e7-dbe311cbb20f
