### ISSUE TITLE
Unreadable button in the download manager

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#38905]
### Description

Due to a bad color choice, the button to trash the download is unreadable.

### Steps to reproduce

1. Open https://testsafebrowsing.appspot.com/
2. Download _Should show an "uncommon" warning, for .exe_ under _Download desktop warning_
3. Click the download button in the URL bar
4. Click the file that was just downloaded but blocked by Safe Browsing.

### Actual result

![Screenshot from 2024-06-08 12-04-00](https://github.com/brave/brave-browser/assets/167821/5135bba7-39a7-4aef-ab03-aeb2e38ef931)

### Expected result

Should be white on dark blue instead of black on dark blue.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave	1.67.108 Chromium: 126.0.6478.40 (Official Build) beta (64-bit) 
Revision	a286dc9f61f7d70fbf0157fcf3d924b00297d450
OS	Linux
```

### Channel information

- [ ] release (stable)
- [X] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.67.123` or higher for `1.67.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.67.123 Chromium: 126.0.6478.126 (Official Build) (64-bit)
-- | --
Revision | fc7619ef621fe4e6a0fa8b16c718f78ffc97a861
OS | Windows 10 Version 22H2 (Build 19045.4529)
```
Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/38905#issue-2341788807, ensured that the correct UI/colouring was being used via the `uncommon" .exe warning` as per the following:

**`Example`** | **`Example`**
----------------|----------------
![image](https://github.com/brave/brave-browser/assets/38657976/b4b9eb93-ed31-4e5c-a708-8dcc567815b4) | ![image](https://github.com/brave/brave-browser/assets/38657976/5e9e1b97-38ce-45e6-a784-2468eb6454bd)
