### ISSUE TITLE
Copy/Paste from Open Office into a Google Sheet crashes Brave

### ISSUE THREAD

**Issue by peterdalydickson** [brave/brave-browser#3891]
## Description 
Copy/Paste from Open Office into a Google Sheet crashes Brave

## Steps to Reproduce

   1. open attached, or any other, Open Office s/sheet
   2. create new Google Sheet
   3. select and copy a block of cells in Open Office (say, A2- B6 in the attached)
   4. use ⌘V or `Edit >> Paste Special >> Paste Values Only` (SHIFT-⌘-V) to paste into the Google Sheet

## Actual result:
Brave crashes.

<img width="800" alt="Problem_Report_for_Brave_Browser" src="https://user-images.githubusercontent.com/17453188/54977932-b6148e80-4f96-11e9-9b2c-1215b5f713f1.png">

[2019-03-26 crash result.txt](https://github.com/brave/brave-browser/files/3006896/2019-03-26.crash.result.txt)

## Expected result:
Cells paste successfully into Google Sheet.

## Reproduces how often: 
Easily reproduced. Brave crashes every time following the above steps.

## Brave version (brave://version info)
Brave | 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

Not tested.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 

No

- Is the issue reproducible on the latest version of Chrome? 

No

### Additional Information
[2019-03-26 test file.zip](https://github.com/brave/brave-browser/files/3006912/2019-03-26.test.file.zip)

**Comment by kjozwiak** [comment]
Thanks for the report @peterdalydickson! Reproduced on `macOS 10.14 x64 VM` on the following channels:

* `0.62.50 Chromium: 73.0.3683.86` - Reproduced
* `0.63.30 Chromium: 73.0.3683.75` - Reproduced
* `0.64.35 Chromium: 73.0.3683.75` - Reproduced
* `0.65.17 Chromium: 74.0.3729.40` - Reproduced

Can't reproduce on `Win 10 x64` using `0.62.50 Chromium: 73.0.3683.86`.

Crashes with the following via the terminal (probably not much help):

```
[0403/210309.456881:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffeed804000, 0x2000): (os/kern) invalid address (1)
Illegal instruction: 4
```

Example of the issue occurring:

![crashmacOS](https://user-images.githubusercontent.com/2602313/55529651-69087a80-5670-11e9-98bd-5bc664241db0.gif)

**Comment by iefremov** [comment]
seems working now
