### ISSUE TITLE
update color of "Relaunch to Update Brave" hamburger menu item on dark/light themes

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#38919]
### Description

When the hamburger menu shows that an update is available, the hamburger menu option is highlighted in blue. Should be more of a Brave-ified color.

This is new with C126 builds, does not reproduce with C125 builds.

### Steps to reproduce

1. Launch via terminal with `--args --enable-logging=stderr --simulate-critical-upgrade`
2. Observe the hamburger menu
3. See "Update" notification on the hamburger menu 
4. Open hamburger menu
5. See that the "Relaunch to Update Brave" option is blue (darker blue on dark theme, lighter blue on light theme)

### Actual result

Dark | Light
--- | ---
![Screenshot 2024-06-07 at 9 12 02 AM](https://github.com/brave/brave-browser/assets/28145373/74eaa453-791a-4e63-958c-f4452c114074) | ![Screenshot 2024-06-07 at 9 12 35 AM](https://github.com/brave/brave-browser/assets/28145373/18ea87c0-3dd6-41e8-a9fe-3c0adc97e625)

### Expected result

The blue should be a "Brave" color

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.67.x, 1.68.x, others

### Channel information

- [x] release (stable) (RC, not current 1.66.x)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @aguscruiz

**Comment by aguscruiz** [comment]
Added Figma details for color here
https://www.figma.com/design/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?node-id=6697-27337&t=jUJVEMS8kwBif2QJ-1

**Comment by simonhong** [comment]
working on this.

**Comment by rebron** [comment]
Dupe https://github.com/brave/brave-browser/issues/38810

**Comment by LaurenWags** [comment]
@rebron not quite a duplicate of https://github.com/brave/brave-browser/issues/38810. That one is more focused on the highlighting of the menu item, not the coloring.

**Comment by simonhong** [comment]
https://github.com/brave/brave-core/pull/24120 will resolve both together!

**Comment by kjozwiak** [comment]
The above requires `1.67.115` or higher for `1.67.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.67.115 Chromium: 126.0.6478.56 (Official Build) (x86_64)
-- | --
Revision | e1f8b4850805c2eea958bad7220c5e6e9202efaa
OS | macOS Version 13.6.7 (Build 22G720)
```
