### ISSUE TITLE
Force VPN Skus CredentialSummary Refresh

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#38926]
The following is basically a place holder for https://github.com/brave/premium-support/issues/14 so we have something pointing to https://github.com/brave/brave-core/pull/23322 on https://github.com/brave/brave-browser.

@SergeyZhukovsky @hffvld as mentioned on Slack and https://github.com/brave/premium-support/issues/14, we'll basically need to run through the VPN feature and ensure that nothing as regressed. Also as per the previous discussions, doing a `staging/test card` purchase on the RC should be enough re: checking if purchasing the `Monthly` & `Yearly` subscriptions are working.

**Comment by kjozwiak** [comment]
The above requires `1.66.122` or higher for `1.66.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.3.1` using version `1.66.122`

- Ensured purchasing monthly and yearly subscription are working using IAP.
- Ensured tunneling is working when VPN is enabled.
- Ensured changing region is successful using the quick action selector in hamburger menu.
- Ensured changing protocol is from `Wireguard` to `IKEv2` without issues and user is able to change regions after this. 
- Ensured `Reset Configuration` resets VPN settings except for the set location. 
- Ensured linking receipt is successful when using the staging premium site (account.bravesoftware.com).
- Ensured enabling VPN via loading active credentials from `account.brave.com` is successful. 

**Monthly Subscription - IAP Flow**

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_6332](https://github.com/brave/brave-browser/assets/17885425/314ef747-24b6-45f8-b479-7684acc0d37b) | ![IMG_6333](https://github.com/brave/brave-browser/assets/17885425/b83d515c-719a-4a46-833f-66d01bec2b2f) | ![IMG_6334](https://github.com/brave/brave-browser/assets/17885425/b63d9236-fe08-453a-86f2-331baa15cb78) | ![IMG_6335](https://github.com/brave/brave-browser/assets/17885425/017a96ff-4c66-497b-af77-3e8de5232f4d) | ![IMG_6337](https://github.com/brave/brave-browser/assets/17885425/9f0cbc95-1b1c-4ebc-baa0-a56b20b2e3df)

**Yearly Subscription - IAP Flow**

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_6355](https://github.com/brave/brave-browser/assets/17885425/1d565fbd-03ed-46db-8182-d9d2d5a49dac) | ![IMG_6356](https://github.com/brave/brave-browser/assets/17885425/fa66816e-e373-468e-83c5-6441faf54a92) | ![IMG_6357](https://github.com/brave/brave-browser/assets/17885425/66348f84-30a2-4f3c-9b05-feacb16ea928) | ![IMG_6358](https://github.com/brave/brave-browser/assets/17885425/3def9660-87f3-49d0-b68c-b6d65c4cffb5) | ![IMG_6359](https://github.com/brave/brave-browser/assets/17885425/6636526c-9f67-412d-b58f-c9862cc0f96e)

**Loading Active Credentials - Account Site**

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_6364](https://github.com/brave/brave-browser/assets/17885425/6d494eea-0c92-4d87-b0e4-dfba4793915c) | ![IMG_6365](https://github.com/brave/brave-browser/assets/17885425/fc9a78fb-c9bb-45ba-b559-2d96a173d369) | ![IMG_6366](https://github.com/brave/brave-browser/assets/17885425/4e6e9147-07c4-4239-ad53-0754563b98df) | ![IMG_6367](https://github.com/brave/brave-browser/assets/17885425/8e4d3eb2-8f9f-4168-8507-c146a37ff047) | ![IMG_6368](https://github.com/brave/brave-browser/assets/17885425/972b668d-83aa-4627-af61-5b9b5d9a571e)


**Linking Receipt**

 Example | Example | Example | Example
-|-|-|-
![IMG_6343](https://github.com/brave/brave-browser/assets/17885425/e55a42b0-081d-4bd7-b104-e1b7a2946f64) | ![IMG_6344](https://github.com/brave/brave-browser/assets/17885425/c885d9c9-263d-48a4-9a75-8c30ea36c4f5) | ![IMG_6345](https://github.com/brave/brave-browser/assets/17885425/aeacbbdf-73c0-4deb-8aa3-aa915cb33ff3) | ![IMG_6346](https://github.com/brave/brave-browser/assets/17885425/89240309-da7f-410c-b85a-e964856dfaab)

**Changing Regions/Protocol & Resetting**

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_6349](https://github.com/brave/brave-browser/assets/17885425/084e5c57-fc3c-4446-8850-e59e0d7ccbb6) | ![IMG_6350](https://github.com/brave/brave-browser/assets/17885425/b2bf3ccf-46df-4c3d-b77a-b9bca18179c0) | ![IMG_6351](https://github.com/brave/brave-browser/assets/17885425/d6d21669-eb3e-4e55-a80e-5ed8d572e7ff) | ![IMG_6352](https://github.com/brave/brave-browser/assets/17885425/7ae6e6a7-76da-4225-89df-3dff725e7da2) | ![IMG_6353](https://github.com/brave/brave-browser/assets/17885425/4652e64a-9193-469c-bf0c-7bd4d4a15931)

**Comment by hffvld** [comment]
Verified on `iPad Air` using version(s):
```
Device/OS: iPad Air / iPadOS 16.7.2
Brave build: 1.66.1 (122)
BraveCore: 1.66.122 (125.0.6422.165)
```
---------------------------

**ACTUAL RESULTS:**
- Ensured purchasing a `yearly` subscription is working using IAP.
- Ensured tunneling is working when `VPN` is enabled.
- Ensured the changing region was successful using the quick action selector on the hamburger menu.
- Ensured changing protocol is from `Wireguard` to `IKEv2` without issues and the user can change regions after this. 
- Ensured `Reset Configuration` resets VPN settings except for the set location. 
- Ensured linking receipt is successful when using the staging premium site (account.bravesoftware.com).
- Ensured enabling VPN via loading active credentials from `account.brave.com` is successful. 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/b65487ee-b588-43f1-a2b2-df35ad1e9c19) | ![2](https://github.com/brave/brave-browser/assets/128532965/926bd207-70eb-414e-8212-5ef275d7e260) | ![3](https://github.com/brave/brave-browser/assets/128532965/962406b8-eff2-45ee-9fac-cf7d525f0cb0) | ![4](https://github.com/brave/brave-browser/assets/128532965/ba74f277-3f0f-44e7-8437-6d4f81816846) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/453383d0-d10f-437d-a96c-4228ac701403) | ![2](https://github.com/brave/brave-browser/assets/128532965/0f20bc18-774d-4a16-9398-b7eb76619711) | ![3](https://github.com/brave/brave-browser/assets/128532965/f4aa7497-d640-4b66-92d3-5e0d2a8b1b6a) | ![4](https://github.com/brave/brave-browser/assets/128532965/91f0fe72-1cdc-4989-8837-b0ae2aea8e15) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/78722231-c378-4a98-bc5e-fa903cc7ea3e) | ![2](https://github.com/brave/brave-browser/assets/128532965/31fdcddc-0e88-4cdc-a1e3-f54ddf981602) | ![3](https://github.com/brave/brave-browser/assets/128532965/203d1d6b-75d7-44bc-8962-55b7ba0fa1f9) | ![4](https://github.com/brave/brave-browser/assets/128532965/9a1a76c4-ca22-47d3-b366-027a34040574) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/e5526a04-d409-4fbf-b674-18947c2c3e74) | ![2](https://github.com/brave/brave-browser/assets/128532965/a5cbe5bc-b208-4606-89ab-b936c01cce42) | ![3](https://github.com/brave/brave-browser/assets/128532965/03c7d963-47f3-4f5c-9442-51c776821b34) | ![4](https://github.com/brave/brave-browser/assets/128532965/7f5b3fce-caa2-4df1-853f-d71a69ef9928) |

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iPadOS 17.4` using version `1.66.122`

- Ensured purchasing monthly subscription are working using IAP.
- Ensured tunneling is working when VPN is enabled.
- Ensured changing region is successful using the quick action selector in hamburger menu.
- Ensured changing protocol is from Wireguard to IKEv2 without issues and user is able to change regions after this.
- Ensured Reset Configuration resets VPN settings except for the set location.
- Ensured enabling VPN via loading active credentials from `account.brave.com` is successful.

Example | Example | Example | Example | Example 
-|-|-|-|-
![IMG_1409](https://github.com/brave/brave-browser/assets/17885425/86a4b0a8-b81c-4d52-8d64-364707973dfd) | ![IMG_1410](https://github.com/brave/brave-browser/assets/17885425/9e56d45c-fbb2-4092-9062-0ae416d6eabd) | ![IMG_1411](https://github.com/brave/brave-browser/assets/17885425/27baf089-d258-4d09-a3f9-af7551b65e5e) | ![IMG_1412](https://github.com/brave/brave-browser/assets/17885425/69e160b3-fea1-4edf-bd22-8932fbda505d) | ![IMG_1418](https://github.com/brave/brave-browser/assets/17885425/67a5bc39-9b84-4083-8f82-758195233a39)
