### ISSUE TITLE
Select Account is not filtering by Testnet Accounts

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#38927]
### Description

When selecting a `Token` to send, the `Select Account` prompt is not filtering accounts by `Testnet Accounts` vs `Mainnet Accounts` for `Bitcoin`, `ZCash` and `Filecoin`.

### Steps to reproduce

1. Go to the `Send` screen and select `Bitcoin`, `Zcash` or `Filecoin` to send.
2. When the `Select Account` prompt appears, it does not filter accounts based on `Testnet` or `Mainnet`.

### Actual result

https://github.com/brave/brave-browser/assets/40611140/e489b548-9119-4361-9b67-c796ec2111b0

### Expected result

It should filter accounts by `Testnet` or `Mainnet` for `Bitcoin`, `Zcash` and `Filecoin`.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.x

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.68.87` or higher for `1.68.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.68.88 Chromium: 126.0.6478.71 (Official Build) beta (64-bit)
-- | --
Revision | 70077e4ec26f79de0bac54bc09204be0a3e6cea6
OS | Windows 11 Version 23H2 (Build 22631.3737)

- Verification passed on [brave/brave-core#24096](https://github.com/brave/brave-core/pull/24096)
- Verified only Testnet accounts/Mainnet accounts are shown in account selection screen

https://github.com/brave/brave-browser/assets/17010094/16615688-e155-4132-b7da-37280d7e248a
