### ISSUE TITLE
Make RPC calls concurrently when fetching GetSolanaTxFeeEstimation

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#38925]
### Description

Please see https://github.com/brave/brave-core/pull/23214#discussion_r1631688443. These calls can be done concurrently.

### Steps to reproduce

N/A

### Actual result

N/A

### Expected result

N/A

### Reproduces how often

No steps to reproduce

### Brave version (brave://version info)

N/A

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/35866#issuecomment-2255634693
