### ISSUE TITLE
[ads] Scheduled captcha code health

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#38937]

**Comment by btlechowski** [comment]
Verified with

Brave | 1.69.139 Chromium: 127.0.6533.100 (Official Build) beta (64-bit)
-- | --
Revision | 0da988816510c06ff835a14b500d5ab861e18d6e
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/24109

<details>

Verified captcha is shown

![image](https://github.com/user-attachments/assets/e659c2fb-de5f-49fe-95f7-d8c351015c59)

Verified capcha is shown

![image](https://github.com/user-attachments/assets/1c7925c2-d030-4c41-9aeb-857135dcc25c)


Verified captcha can be solved
![image](https://github.com/user-attachments/assets/425691a0-6b5f-42a2-87e3-6cb30e0b7571)

Verified tokens are refilled
```
[3595:3595:0814/202540.726671:VERBOSE1:get_signed_tokens_url_request_util.cc(73)] Added 50 confirmation tokens, you now have 50 confirmation tokens

```


</details>

**Comment by btlechowski** [comment]
Verification passed on Brave v1.69.145 on Lenovo TB-8506FS (Android 11.0)

Verified test plan from https://github.com/brave/brave-core/pull/24109

<details>


Captcha was scheduled:
```
01:46:23.483  V  [VERBOSE6:refill_confirmation_tokens.cc(191)] URL Response:
                   URL: https://mywallet.ads.bravesoftware.com/v3/confirmation/token/b0d595c4-08fd-5a5f-bb17-19fe4071a8c2?nonce=89c67991-928a-4aad-a3ce-8fcd22714c13
                   Response Status Code: 401
                   Response: {"message":"Captcha Required","captcha_id":"c773720e-64c4-4018-9c5e-25e620d3a10f"}
01:46:23.485  I  [INFO:refill_confirmation_tokens.cc(198)] Captcha is required to refill confirmation tokens
01:46:23.486  V  [VERBOSE1:user_rewards.cc(129)] Failed to refill confirmation tokens

```


Verified tokens are refilled
```

```


</details>
