### ISSUE TITLE
Display Loading Spinner while Generating Address

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#38931]
### Platforms

Android, Linux, macOS, Windows

### Description

When selecting an account to send `Bitcoin` or `ZCash` to, it sometimes takes a moment for the address to be generated. Currently there is no indication that the address is being generated which could cause user to keep clicking. We should add a loading spinner to the `Select Account` prompt while an address is being generated.

https://github.com/brave/brave-browser/assets/40611140/7a45850a-2a42-479f-95f4-bd2bfa41ac9f

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.135 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 96e3ea6d105b9e3f1a388fa1838571774216b82e
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24104](https://github.com/brave/brave-core/pull/24104)
- Verified loading spinner is shown when generating address on Send screen

https://github.com/user-attachments/assets/12181b58-fd8f-4a6b-9e70-41009a6c21dc
