### ISSUE TITLE
Zenhub extension doesn't load boards

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3893]
## Description 

Zenhub extension doesn't load boards

## Steps to Reproduce

   1. Install Zenhub extension
   2. Login to github 
   3. Open Zenhub tab, boards fail to load

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/54997737-c29ee400-4fa2-11e9-97ee-35fa4fc04189.png)

## Expected result:
Boards should load correctly 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS |  All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  
Yes disabling shields loads boards
- Is the issue reproducible on the latest version of Chrome? 
No, works fine on Chrome. Confirmed by @jhreis 

### Additional Information

Adding P3 since it breaks complete functionality with shields up. Toggle adblock doesn't make a difference
cc: @rebron

**Comment by rebron** [comment]
Looks like this is working on dev 0.63.20 Chromium: 73.0.3683.75 and nightly 0.64.8 Chromium: 73.0.3683.75.

@srirambv can you double check on 62? I'm going to do it now too.

**Comment by rebron** [comment]
Making clear we're talking about this extension: https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd?hl=en-US

I have it working ok on macOS 0.62.41 Chromium: 73.0.3683.86 and seeing the boards, drag and drop, the usual functions.

**Comment by srirambv** [comment]
Seems to be working on Windows too now on release build. Not sure what fixed it. Closing for now. Will reopen if reproduced again
