### ISSUE TITLE
Condense Portfolio Actions with a More Menu Button

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#38935]
### Platforms

Linux, macOS, Windows

### Description

We need to condense the `Portfolio` actions to have a `More` menu button to display `Bridge` and `Deposit`

![Screenshot 15](https://github.com/brave/brave-browser/assets/40611140/f2a9c710-2951-489e-b02d-6d629f2f26fd)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.124 Chromium: 127.0.6533.73 (Official Build) beta (64-bit)
-- | --
Revision | dbc9035349f74e493f3293d93f4cbf35c597dfec
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24108](https://github.com/brave/brave-core/pull/24108)
- Verified Portfolio actions is now consolidated in more menu
- Verified Bridge and Deposit buttons work as expected in panel

https://github.com/user-attachments/assets/3c4d517b-fcac-4ef6-9eec-8f3d1d98a315
