### ISSUE TITLE
[NTP Search]: URL handling

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#38941]
Currently there are no URL matches on the NTP Searchbox. @rebron has asked if we can add exact matches, where we skip the search.

The Omnibox doesn't provide this functionality in <keyword> search mode, so it'll need to be a bespoke implementation.

Testing:
1. Enter `example.com` in the NTP search box
2. Press enter - you should navigate to example.com
3. Should not navigate to `chrome://` urls
4. Should not navigate to `brave://` urls
5. Should not navigate to url with spaces
6. Should not navigate to url with no `.`s
7. Ctrl+Enter should open in new tab
8. Ctrl+Click should open in new tab
9. Middle click should open in new tab

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.68.101 Chromium: 126.0.6478.126 (Official Build) beta (64-bit)
-- | --
Revision | ffa8411f4c8fe36c0e399f60ef7c24b3cf7d7402
OS | Windows 10 Version 22H2 (Build 19045.4598)
```
