### ISSUE TITLE
Most webui buttons are hidden in new dark theme with c74

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#3894]
## Description 

When in main settings in dark mode, regular (not 'action') buttons (e.g. the 'cancel' button within modal, the 'default browser' button, etc) cannot be seen.

## Steps to Reproduce

   1. Open Brave
   2. Open settings (switch to dark theme if not already)
   3. Go to 'Clear Browsing Data'

## Actual result:

'cancel' button is hidden
<img width="615" alt="Screen Shot 2019-03-24 at 11 57 57 AM" src="https://user-images.githubusercontent.com/25326067/55009236-98f0b780-4fb8-11e9-952b-bb20a835c892.png">

## Expected result:
'cancel' button should be easily seen

## Reproduces how often: 

easily

## Brave version (brave://version info)

0.64.x (c74)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc @petemill

**Comment by rebron** [comment]
@petemill Can you take a look?

**Comment by petemill** [comment]
Yes I’ll fix it when c74 lands again

**Comment by petemill** [comment]
This also affects normal buttons, changing title / description to reflect that

**Comment by bsclifton** [comment]
Resolved when C74 was merged to master with https://github.com/brave/brave-browser/pull/3931 😄

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.64.72 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Verified test plan from description for both dark and light themes. cc @kjozwiak to check macOS using Mojave for 'matches macOS theme' option.
![Screen Shot 2019-05-07 at 4 25 44 PM](https://user-images.githubusercontent.com/28145373/57330780-02e69b80-70e5-11e9-8fa8-b1721f8ef6ca.png)
![Screen Shot 2019-05-07 at 4 26 45 PM](https://user-images.githubusercontent.com/28145373/57330782-0417c880-70e5-11e9-8a91-34178f8ff05b.png)
