### ISSUE TITLE
[ads] SPIKE: Investigate allowing users to clear ad event data

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#38959]
### Description

See https://github.com/brave/reviews/issues/1636 > 2.5

Discuss adding to brave://settings/clearBrowserData

**Comment by fmarier** [comment]
I think this is basically the same as fixing https://github.com/brave/brave-browser/issues/38804

**Comment by tmancey** [comment]
Privacy review https://github.com/brave/reviews/issues/1636

**Comment by tmancey** [comment]
Closing as implementation will be via https://github.com/brave/brave-browser/issues/39051
