### ISSUE TITLE
Leo - Stop generating answer button in input box

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#38958]
### Description

Feature to stop generating an answer while it's in progress. The flow is as follows:

1. User sends a prompt
2. While the answer is being generated, the "Send" button transforms to a "Stop" icon.
3. If pressed, the answer will stop generating.
4. The input box is reset to the empty state.

Figma file:
https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/Leo?node-id=3496-13366&t=A9ttQuDnBniPq7sv-1

### Steps to reproduce

New feature - Not applicable

### Actual result

Not applicable

### Expected result

![image](https://github.com/brave/brave-browser/assets/15734630/fa0a9f38-23a1-4166-941c-d34162dd5313)

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

Not applicable

### Android device

Not applicable

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by nullhook** [comment]
dupe: https://github.com/brave/brave-browser/issues/38337

**Comment by aguscruiz** [comment]
Closing then!
