### ISSUE TITLE
Stats updater uses wrong timestamps

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#3895]
https://github.com/brave/brave-core/blob/master/browser/brave_stats_updater_params.cc#L17

Here we cache `base::Time::Now()` on startup and then use it in all outgoing pings. This way, all stats updater pings contain the same timestamp until the browser restart. 

It would be more precise to take the actual `Now()` every time.

Brave | 0.64.2 Chromium: 73.0.3683.75 (Developer Build) (64-bit)

**Comment by iefremov** [comment]
@bbondy @too4words @aekeus JFYI

**Comment by iefremov** [comment]
Also there is a possible underflow: https://github.com/brave/brave-core/blob/master/browser/brave_stats_updater_params.cc#L98

(`day_of_week` can be zero if it is Sunday)

**Comment by emerick** [comment]
I guess I ported this bug right over from Muon, oops: https://github.com/brave/browser-laptop/blob/8692beec44ff4a0a7c56b5ba004bc6ea75365ccf/app/dates.js#L42

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.62.49 Chromium: 73.0.3683.86 (Official Build) (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Windows 10 OS Build 17134.523

Used test plan from https://github.com/brave/brave-core/pull/2112
Clean install ping on `2019-04-01`
`https://laptop-updates.brave.com/1/usage/brave-core?platform=winx64-bc&channel=release&version=0.62.49&daily=true&weekly=true&monthly=true&first=true&woi=2019-04-01&ref=none`
Ping on `2019-04-02`
`https://laptop-updates.brave.com/1/usage/brave-core?platform=winx64-bc&channel=release&version=0.62.49&daily=true&weekly=false&monthly=false&first=false&woi=2019-04-01&ref=none`
