### ISSUE TITLE
[Android] `wallet-generation-disabled` notice text is cutoff in Rewards panel and does not match desktop

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#38968]
## Description

![image](https://github.com/brave/brave-browser/assets/11497541/02152e04-acbe-4ffc-bcc3-7648810522f3)

Text should not be cut off and should match desktop. 

>**Brave Rewards not available**
New signups for Brave Rewards are currently disabled in your region. However, you can always try again later. Learn more

cc: @hffvld

**Comment by hffvld** [comment]
More info for this:

You can see the full text, but you have to scroll for it.

------------------

https://github.com/brave/brave-browser/assets/128532965/03266115-8f09-474e-8468-e9b30e680801

**Comment by kjozwiak** [comment]
The above requires `1.68.103` or higher for `1.68.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.68.107`

- Verified the description from the issue https://github.com/brave/brave-browser/issues/38968#issue-2347030266 and ensured that the following text is shown completely on the BR panel. 
- Confirmed that the text is matching with the Desktop message
- Confirmed that user can view the complete message on the panel there is no text cutoff on the BR panel
>Brave Rewards not available
New signups for Brave Rewards are currently disabled in your region. However, you can always try again later. Learn more

https://github.com/brave/brave-browser/assets/38657976/23a5bdad-921f-42b5-ad54-c918c690bd27

![Screenshot_20240703_175655](https://github.com/brave/brave-browser/assets/38657976/9ff08e48-b389-497a-a65f-8a536c5ae740)
