### ISSUE TITLE
Leo - Update input box to match design tweaks

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#38960]
### Description

Design
https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/%F0%9F%94%84-Leo-%5BIN-PROGRESS%5D?node-id=4492-5464

- [ ] Input area looks "attached" to the keyboard, there's no padding between the input and the borders. Top borders are rounded off
- [ ] Changed the icon size for the items in the input box to be 24x24px. 
- [ ] There's also the addition of slash tools.
- [ ] Font size uses the `large` style now
- [ ] Added 8px padding between the text input and the icons.
- [ ] Bottom padding of the icon area is 16px.
- [ ] Spacing between icons is 16px

###Send button detail
- [ ] When there isn't a prompt, the icon shows as disabled.
- [ ] When a prompt is entered, the icon changes to `send-filled` and changes color to `icon-interactive`

### Expected result
![image](https://github.com/brave/brave-browser/assets/15734630/458004c8-7f28-4036-938c-2ca828d1ce65)

------------------

![image](https://github.com/brave/brave-browser/assets/15734630/07b627f6-6430-4458-8812-dcc4052deff1)

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.69 (156)`

#### `New install`

- Ensured microphone has moved to left side of the Leo chat prompt. 
- Ensured that send button is not filled when chat prompt is empty.
- Ensured that send button is filled when user enters characters into the prompt.
- Ensured that send button is filled when using microphone (voice to text)

Example | Example | Example
-|-|-
![IMG_7161](https://github.com/user-attachments/assets/98869258-2d2c-4ec4-af2a-fa2bfe490c16) | ![IMG_7162](https://github.com/user-attachments/assets/d44c12f1-1ab1-4cec-9d34-62adb497ef4a) | ![IMG_7163 2](https://github.com/user-attachments/assets/9466ea9f-f322-4e3d-807b-7277142a48fe)


#### `Existing users (upgrade case)`
 
 - Ensured chat functionality has not regress when migrating from 1.68
 
 1.68 | 1.68 | 1.69
 -|-|-
![IMG_7165](https://github.com/user-attachments/assets/e2af6dcb-956c-4280-adbc-4ed5ba8d89c2) | ![IMG_7166](https://github.com/user-attachments/assets/9097b73f-b837-4d19-a56c-f6d7052433be) | ![IMG_7168](https://github.com/user-attachments/assets/56388c04-6cba-4ffb-9391-cc043808e877)
