### ISSUE TITLE
[Follow up to #38834] Opened tabs are lost and can't be restored on `iPhone`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#38965]
### Description

Follow-up to #38834

### Steps to reproduce

1. Launch Brave
2. Open multiple tabs with any websites
3. Set `Tabs Bar` to ON in Brave settings (not 100% sure if this step is needed)
4. Go to the home screen or another app and keep Brave opened
5. Lock and then unlock the device
6. Close and relaunch Brave until tabs are lost > *Observe that tabs are lost*
7. Tap and hold `Tabs overview` button
8. View Recently Closed Tabs > *Observe that tabs from another session are shown*

### Actual result

Opened tabs are lost and can't be restored on `iPhone` when closing and reopening Brave. I was able to reproduce it a few times after I closed and reopened Brave ~20 - 100 times. Also, restoring tabs via `View Recently Closed Tabs` is impossible because tabs from another session are shown.

https://github.com/brave/brave-browser/assets/128532965/837c1aeb-442e-42bc-b957-1e4b1d6f1076

https://github.com/brave/brave-browser/assets/128532965/10121206-93ff-4f62-9204-e0d0b72f4d4b

### Expected result

Tabs must not be lost when closing and reopening Brave.

### Reproduces how often

Intermittent issue

### Brave version

Brave build: 1.66.1 (122)
BraveCore: 1.66.122 (125.0.6422.165)

### Device/iOS version

iPhone 14 / iOS 17.5.1

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
Labelling as `release-notes/exclude` in favour of https://github.com/brave/brave-browser/issues/38834 which we'll use for the release notes re: tab loss.

**Comment by kjozwiak** [comment]
The above requires `1.66.123` or higher for `1.66.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.5.1
Brave build: 1.66.1 (122)
BraveCore: 1.66.122 (125.0.6422.165)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/24125#issuecomment-2163559849
2. *Verify*

**ACTUAL RESULTS:**
- Verified that tabs are not lost after Brave `closed` and `relaunched`
- Verified the same with `Tabs Bar` set to `Landscape only` and `On`

---------------------------

https://github.com/brave/brave-browser/assets/128532965/679fcbde-f072-4896-a0af-fe087e73ce2d

https://github.com/brave/brave-browser/assets/128532965/9a0ee1c0-513a-47df-b21c-73e594604c1e
