### ISSUE TITLE
Update Transaction Confirmation labels for BTC transactions

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#38967]
### Description

For Bitcoin transactions, we should display the fee using `Transaction Fee` instead of `Gas Fee`.

### Steps to reproduce

1. Create a send BTC transaction
2. In Transaction Confirmation, the labels read `Gas Fee` instead of `Transaction Fee`

### Actual result

<img src="https://github.com/brave/brave-browser/assets/5314553/9ed83b03-2025-4881-af39-e2093cebf94f" width="300">

### Expected result

`Transaction Fee` instead of `Gas Fee`

### Reproduces how often

Easily reproduced

### Brave version

v1.68+

### Device/iOS version

all

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by srirambv** [comment]
Verification passed on iPhone  13 with  iOS 18 running 1.69 (147)
- Verified steps from [brave/brave-core#24130](https://github.com/brave/brave-core/pull/24130)
- Verified for BTC transactions, `Gas Fee` is renamed to `Transaction Fee`
<img width=400 src=https://github.com/user-attachments/assets/730de783-6741-4a5f-b277-5194ad2a36f9>
