### ISSUE TITLE
Editing non-eth network causes `eth_chainId` request on iOS

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#38972]
### Description

Editing a non-ethereum network in iOS settings results in an `eth_chainId` request.

### Steps to reproduce

1. Setup/run a proxy to observe network requests
2. Open Web3 Settings -> Networks
3. For any non-eth network, for example Solana, Filecoin or Bitcoin tap the network to open edit network panel
4. Change the RPC url to anything
5. Tap `Save`

### Actual result

`eth_chainId` request is made

### Expected result

`eth_chainId` request should only be made for ethereum networks

### Reproduces how often

Easily reproduced

### Brave version

All

### Device/iOS version

All

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.0 running 1.69 (147)
- Verified steps from [brave/brave-core#24225](https://github.com/brave/brave-core/pull/24225)
- Verified when adding network via Dapp, all fields are view only
- Verified long press on the field shows `Tap to copy` message
- Verified able to add new EVM networks
- Verified `chain_id` field is not editable for Solana/Filecoin and Bitcoin networks
- Verified editing a non-eth network by changing active RPC endpoint doesn't show any `eth_chainId` in network requests
