### ISSUE TITLE
[Wallet] Panel crashes when attempting to lookup EIP1159 estimates for non EVM or FIL transactions

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#38970]
### Description

We should not attempt to lookup EIP1159 gas feee estimates for transactions that are not EVM or FVM types.

### Steps to reproduce

1. Submit a Solana transaction from the "send" screen

### Actual result

Panel crashes

### Expected result

Panel should not crash

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.0 Chromium: 126.0.6478.40 (Developer Build) (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.124 Chromium: 127.0.6533.73 (Official Build) beta (64-bit)
-- | --
Revision | dbc9035349f74e493f3293d93f4cbf35c597dfec
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24134](https://github.com/brave/brave-core/pull/24134)
- Verified no browser crash when submitting a send transaction for ETH/SOL/BTC/ZEC/EVM Tokens 

https://github.com/user-attachments/assets/54890de5-1ef9-4482-9af6-3dd6b689871b
