### ISSUE TITLE
[NTP Search]: Ecosia icon is missing for the NTP Search box

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#38977]
Currently, if you set the default search engine to Ecosia there is no search icon

Expected:
We should display the ecosia search icon

**Comment by kjozwiak** [comment]
The above requires `1.68.101` or higher for `1.68.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `PASSED` using

```
Brave | 1.68.101 Chromium: 126.0.6478.126 (Official Build) beta (64-bit)
-- | --
Revision | ffa8411f4c8fe36c0e399f60ef7c24b3cf7d7402
OS | Windows 10 Version 22H2 (Build 19045.4598)
```

### Steps:
1. installed `1.68.101`
11. launched Brave
12. opened a new-tab page
13. clicked on `Customize` at the bottom
14. clicked on `Search`
15. scrolled down
16. (noticed that `Ecosia`s icon is missing (https://github.com/brave/brave-browser/issues/39406)
17. selected `Ecosia`
18. de-selected `Brave`
19. clicked on the `x` at the top right of the `Customize Dashboard` dialog
20. focused the `Search the web` textfield
21. typed `Jeep Wrangler`
24. still, noted no `Ecosia` icon
25. performed search
26. returned to the `Customize Dashboard` -> `Search` dialog
27. scrolled down to `Ecosia`


### Confirmed the `Ecosia` icon is NOW present in both the `Customize Dashboard` view and the `Search the web` textfield

example | example | example | example | example
----------|-----------|-----------|----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/76d2eadb-981b-44db-b2da-437979fe1ba4) | ![image](https://github.com/brave/brave-browser/assets/387249/c86fd2cc-0c01-45fe-a22d-92f9daf734c4) | ![image](https://github.com/brave/brave-browser/assets/387249/9e54b9a2-6922-4f21-b72f-23a697044581) | ![image](https://github.com/brave/brave-browser/assets/387249/c198a3f3-e64f-4cfa-a638-12de96ab57b3) | ![image](https://github.com/brave/brave-browser/assets/387249/e92056de-5fe2-49e5-be44-7f06b3784938)
