### ISSUE TITLE
[NTP Search]: Improve handling of disabled/enabled engines

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#38976]
https://bravesoftware.slack.com/archives/CKNHM4RTK/p1718103621331509

### Currently selected search engine

When disabling search engines, if the engine the use has disabled the last use engine, it should change to the next available search engine (if there is one), instead of always using Brave (even if it isn't enabled).

### Disabling all search engines

When the user disables all search engines, we should hide the NTP Search box

**Comment by kjozwiak** [comment]
The above requires `1.68.101` or higher for `1.68.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.68.101 Chromium: 126.0.6478.126 (Official Build) beta (64-bit)
-- | --
Revision | ffa8411f4c8fe36c0e399f60ef7c24b3cf7d7402
OS | Windows 10 Version 22H2 (Build 19045.4598)
```
