### ISSUE TITLE
unable to contribute when wallet contains more than enough BAT

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3897]
## Description 
Follow up to #3212, #3640 

Generally seen in conjunction with the two issues above, users are being notified that they can't contribute (auto contribute and/or recurring monthly tips) because their wallet does not contain enough BAT. However, the user's wallet does contain enough BAT.

## Steps to Reproduce

Unknown at this time. 

## Actual result:
Contribution (for auto-contribute and/or recurring monthly tips) does not go thru:
<img width="399" alt="54388702-b0ed4080-4674-11e9-857c-e57fc86b17da" src="https://user-images.githubusercontent.com/28145373/55023953-3dccbe00-4fd4-11e9-84c1-2132adb75ff6.png">

## Expected result:
Enough BAT is in wallet, monthly contribution should go thru.

## Reproduces how often: 
Unsure

## Brave version (brave://version info)
Many

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @mandar-brave

**Comment by mandar-brave** [comment]
@NejcZdovc please prioritize after the Publisher refresh fixes. Tag dupe if it sum game of different issues.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.63.45 Chromium: 74.0.3729.75 (Official Build) beta (64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Windows 10 OS Build 17134.523

Used test plan from https://github.com/brave/brave-core/pull/2091
