### ISSUE TITLE
Editing ZEC network RPC url causes `eth_chainId` request

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#38971]
### Description

When editing a ZEC network RPC url, after you tap `Submit` a `eth_chainId` request is made:
<img width="454" alt="Screenshot 2024-06-11 at 3 12 17 PM" src="https://github.com/brave/brave-browser/assets/5314553/0e774267-db12-4251-a0d2-802a02261f87">

### Steps to reproduce

1. Setup/run a proxy to observe network requests
2. Open brave://settings/wallet/networks
3. For either Zcash Mainnet or Zcash Testnet, click the `...` and select edit
4. Change the RPC url to anything
5. Click submit

### Actual result

`eth_chainId` request is made (see above screenshot)

### Expected result

No `eth_chainId` request for ZEC coin type

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Tested on [Version 1.66.118 Chromium: 125.0.6422.147 (Official Build) (arm64)](https://brave.com/latest/)

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Should be simple fix to include `ZEC` coin type in this check:
https://github.com/brave/brave-core/blob/ee2745aaf2e53ee58b34a59453a45b0301eca2ce/components/brave_wallet/browser/json_rpc_service.cc#L456-L471

cc @cypt4 @yrliou

**Comment by yrliou** [comment]
Should be resolved by https://github.com/brave/brave-core/pull/24249 already, closing.
