### ISSUE TITLE
Hidden NFTs show up on Collected list when switching between Collected and Hidden

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#38986]
### Description

Hidden NFTs show up on Collected list when switching between Collected and Hidden

### Steps to reproduce

1. Restore wallet with multiple collected and junk NFTs
2. Switch from Collected to Hidden
3. Click on any page in Junk NFT
4. Switch back to Collected
5. Lists Junk NFTs in collected section
6. Reload page, hides the Junk NFTs

### Actual result

https://github.com/brave/brave-browser/assets/17010094/d386a224-9873-4efe-89f2-e64878f2752b

### Expected result

Should not list Junk NFTs in Collected NFTs

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.68.85 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | 8e76a669cf78bdfa933c8d569460092a01166588
OS | Windows 11 Version 23H2 (Build 22631.3672)

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @muliswilliam @Douglashdaniel

**Comment by josheleonard** [comment]
Closing: No longer valid
