### ISSUE TITLE
Chromium 74 update is breaking nightly build

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#3898]
## Description
The major breakage happens during `create_dist` on macOS

Employees can get more info on our Jenkins instance:
https://staging.ci.brave.com/job/brave-browser-build-darwin-createdist/288/console
> 07:02:33 [INFO] ./../../brave/build/mac/sign_app.sh succeded
> 07:07:04 [238/260] ACTION //chrome:chrome_dsym_archive(//build/toolchain/mac:clang_x64)
> 07:07:04 ninja: build stopped: subcommand failed.
> 07:07:04 null
> 07:07:04 null
> 07:07:04 npm ERR! code ELIFECYCLE
> 07:07:04 npm ERR! errno 1
> 07:07:04 npm ERR! brave@0.64.20 create_dist: `node ./scripts/commands.js create_dist "Release" "--debug_build=false" "--official_build=true" "--channel=nightly" "--mac_signing_keychain=signing" "--mac_signing_identifier=REDACTED" "--mac_installer_signing_identifier=REDACTED"`
> 07:07:04 npm ERR! Exit status 1
> 07:07:04 npm ERR! 
> 07:07:04 npm ERR! Failed at the brave@0.64.20 create_dist script.
> 07:07:04 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

## Additional info (possibly related)
There is also an issue breaking on Windows with `official_build`=`false`:
https://github.com/brave/brave-browser/issues/3879

**Comment by LaurenWags** [comment]
Does this require manual QA on desktop? Could you tag `QA/No` or `QA/Yes` as appropriate and add a test plan if manual QA is needed?

**Comment by bsclifton** [comment]
@LaurenWags whoops- no, it doesn't. Sorry about that! 😄

**Comment by LaurenWags** [comment]
awesome, thanks for the confirmation @bsclifton 😄
