### ISSUE TITLE
Meld Buy Front-end integration for Desktop

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#38985]
PRD: https://docs.google.com/document/d/1QuufBM21692_E2sASiFs9Sy5q3dV_YXcDpWcTWh8UXY/edit?usp=sharing

Panel

Buy: [https://www.figma.com/proto/5SYlDbuFsODIXhZXgbAy5O/Brave-Wallet-Meld-Integration?ty[…]n-zoom&starting-point-node-id=615%3A36132&show-proto-sidebar=1](https://www.figma.com/proto/5SYlDbuFsODIXhZXgbAy5O/Brave-Wallet-Meld-Integration?type=design&node-id=1-71&viewport=468%2C395%2C0.03&t=EdzFu6npQET1ExO1-0&scaling=min-zoom&starting-point-node-id=615%3A36132&show-proto-sidebar=1)

Expanded View

Buy: [https://www.figma.com/proto/5SYlDbuFsODIXhZXgbAy5O/Brave-Wallet-Meld-Integration?ty[…]n-zoom&starting-point-node-id=619%3A46629&show-proto-sidebar=1](https://www.figma.com/proto/5SYlDbuFsODIXhZXgbAy5O/Brave-Wallet-Meld-Integration?type=design&node-id=1-71&viewport=468%2C395%2C0.03&t=EdzFu6npQET1ExO1-0&scaling=min-zoom&starting-point-node-id=619%3A46629&show-proto-sidebar=1)

**Comment by srirambv** [comment]
Blocked on 
https://github.com/brave/brave-browser/issues/42079
https://github.com/brave/brave-browser/issues/42081
https://github.com/brave/brave-browser/issues/42082
https://github.com/brave/brave-browser/issues/42083
https://github.com/brave/brave-browser/issues/42084
https://github.com/brave/brave-browser/issues/42085
https://github.com/brave/brave-browser/issues/42086

cc: @Douglashdaniel

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.20 Chromium: 131.0.6778.108 (Official Build) beta (64-bit)
-- | --
Revision | 6f52e170fb1611fc69347fb24bca600ed052f7b3
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from issue description
- Verified Meld transaction confirmation modal is shown when selecting Buy from side navigation
- Verified able to select tokens from list which automatically updates the providers
- Verified token resets to ETH when selecting Buy from side navigation
- Encountered [#42822](https://github.com/brave/brave-browser/issues/42822), [#42785](https://github.com/brave/brave-browser/issues/42785),[#42082](https://github.com/brave/brave-browser/issues/42082), [#42084](https://github.com/brave/brave-browser/issues/42084), [#42085](https://github.com/brave/brave-browser/issues/42085)

Wallet Page | Panel
-- | --
<video src=https://github.com/user-attachments/assets/5fa4a787-ca83-4664-9650-57ada43ee7fb> | <video src=https://github.com/user-attachments/assets/73b7999d-dacc-488a-b38f-e3dda1cf0cb6>
