### ISSUE TITLE
Wallet's confirm panel regression

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#38981]
### Description

Bitcoin confirmation panel is not shown after https://github.com/brave/brave-core/pull/23954

### Steps to reproduce

1. Make a BTC transaction
2. 
3. 

### Actual result

Confirm panel doesn't popup

### Expected result

Confirm panel should popup

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

nightly

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.110 Chromium: 127.0.6533.43 (Official Build) nightly (64-bit)
-- | --
Revision | b48482acae2813d6c44e4a83f48b479c56dbc116
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified confirmation panel shows up for BTC transaction
- Verified confirmation panel shows up for other tokens transactions as well

https://github.com/user-attachments/assets/9297ed30-5630-4b1e-8b65-314e7bbb6010
