### ISSUE TITLE
Implement new touch ID screen

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#38987]
## Description

Implement new touch ID screen that will be shown to the user during Wallet onboarding process.

![image](https://github.com/brave/brave-browser/assets/3308503/b979e9eb-a3bc-447a-b5eb-4ff59af000df)

🎨 Figma design: https://www.figma.com/file/oXIiv45pIhF2RGlpEjOfUg/Wallet-onboarding?node-id=6223%3A70942&mode=dev

☂ Main umbrella issue: https://github.com/brave/brave-browser/issues/35294

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.69.147 x64 build
- Verified steps from [brave/brave-core#24159](https://github.com/brave/brave-core/pull/24159)
- Verified new touch ID is as per design

Light | Dark
-- | --
<img width="330" alt="image" src="https://github.com/user-attachments/assets/4aed9c4f-41ec-41b1-bae0-a35b2d77c058"> | <img width="330" alt="image" src="https://github.com/user-attachments/assets/4f266a83-99bc-4a61-b1bc-07ac5f6ed351">
