### ISSUE TITLE
"Relaunch to Update Brave" icon is Chrome icon, not Brave's

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#38991]
### Description

Found while testing https://github.com/brave/brave-browser/issues/38919

This was broken when updating to C126 - logged and fixed with https://github.com/brave/brave-browser/issues/38645.

However, wrong icon got used again, maybe due to https://github.com/brave/brave-browser/issues/38919.

### Steps to reproduce

1. Launched `1.69.14` with `--args --enable-logging=stderr --aue-reached-for-update-required-test --check-for-update-interval=10 --simulate-upgrade`
2. Saw update notification on hamburger menu
3. Clicked on hamburger menu
4. Observed observed incorrect icon for "Relaunch to Update Brave" menu item

### Actual result

Chrome's rocket ship icon is used:

<img width="322" alt="Screenshot 2024-06-12 at 11 04 01 AM" src="https://github.com/brave/brave-browser/assets/28145373/8aadeb2a-3089-456f-a92a-0f4ba047316d">

### Expected result

Should be Brave icon

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.69.14 Chromium: 126.0.6478.56 (Official Build) nightly (x86_64)
-- | --
Revision | b74f168a50e2c7c1c1a168016b89fa7a16c77049
OS | macOS Version 13.6.7 (Build 22G720)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by simonhong** [comment]
Closed as current rocket icon is our new one for upgrade menu entry.
@LaurenWags Sorry for the inconvenience. I should describe icon change also in that issue.
