### ISSUE TITLE
Server error when summarizing video transcripts

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#38996]
### Description

500 returned when trying to summarize videos, seems to be a regression in 1.67.x

Impacts both Desktop & Android

### Steps to reproduce

1. New install
2. Open video URL
3. Launch Leo, opt in and summarize

### Actual result

![Screenshot 2024-06-12 at 12 51 26 PM](https://github.com/brave/brave-browser/assets/17885425/565d8c10-6b8c-4b46-b787-753747857dad)

![Screenshot 2024-06-12 at 1 23 07 PM](https://github.com/brave/brave-browser/assets/17885425/d9085b85-48da-4722-a8a1-51e8f2fe7ce6)

### Expected result

Should summarize video transcripts

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

1.67.113, 1.67.x

### Android device

- Brand/model: ARM devices
- Android version: 13

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by stephendonner** [comment]
Desktop, for posterity:

```
Brave | 1.69.15 Chromium: 126.0.6478.56 (Official Build) nightly (64-bit)
-- | --
Revision | 857e48ef53e02c8048a0eca541571194d5249981
OS | Windows 10 Version 22H2 (Build 19045.4529)
```

![image](https://github.com/brave/brave-browser/assets/387249/6dd3495d-bc36-4996-a75d-8f8fcb403958)

**Comment by kjozwiak** [comment]
The above requires `1.67.115` or higher for `1.67.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.67.115 Chromium: 126.0.6478.56 (Official Build) (64-bit)
-- | --
Revision | e1f8b4850805c2eea958bad7220c5e6e9202efaa
OS | Windows 10 Version 22H2 (Build 19045.4529)
```

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.67.115 Chromium: 126.0.6478.56 (Official Build) (64-bit) 
Revision	e1f8b4850805c2eea958bad7220c5e6e9202efaa
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured video transcripts and text summary is working using production environment.
- Ensured that suggest questions is working for video transcripts.
- Ensured that free and premium models are able to summarize video transcripts. 
- Ensured that summary content matches the URL. 
- Ensured `YouTube` and` Rumble` videos are summarized. 

Mixtral | Haiku | Llama | Sonnet
-|-|-|-
![Screenshot 2024-06-13 at 2 00 01 PM](https://github.com/brave/brave-browser/assets/17885425/3fe61a06-f7ce-4bc2-aa07-4fd837490245) | ![Screenshot 2024-06-13 at 1 55 01 PM](https://github.com/brave/brave-browser/assets/17885425/cbf46d51-6649-44e0-9e69-2be80ef610c0) | ![Screenshot 2024-06-13 at 1 57 32 PM](https://github.com/brave/brave-browser/assets/17885425/90d96bf7-0093-4925-a131-291df06803f3) | ![Screenshot 2024-06-13 at 2 25 45 PM](https://github.com/brave/brave-browser/assets/17885425/13884169-b35b-4cf1-b9b5-ad3b4f745b87)
