### ISSUE TITLE
Create whitelist for using Brave UA

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#39]
For reference:
https://github.com/brave/browser-android-tabs/commit/55fda525fd64a1f6539ea20b8a0a0ebe6a573533

**Comment by bbondy** [comment]
This is already done.

**Comment by bbondy** [comment]
QA notes: You'll need to use dev tools for this in the network tab.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux
![image](https://user-images.githubusercontent.com/17010094/45856357-21e51880-bd22-11e8-950d-4188a4eb4e64.png)
