### ISSUE TITLE
[AI Rewriter]: Improve the sizing/positioning of the AI Rewriter dialog

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#39005]
Currently, the dialog loses its position if the host window is moved/resized. Additionally, the dialog can't render outside the bounds of the parent window, so it is often truncated.

On the WebView side, when the size of the dialog is changed then content is pushed out the bottom and there's no way to resize it. The Dialog should autosize to fit the webcontent.

**Comment by stephendonner** [comment]
@fallaciousreasoning can you check if this fixes/you can fix https://github.com/brave/brave-browser/issues/38998 along with this PR?
