### ISSUE TITLE
Loading Skeleton not displayed while Owned Tokens are Populated

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#39000]
### Description

The `Loading Skeleton` is not displayed in the `Select Token` modal while the `Owned` token list is being populated.

### Steps to reproduce

1. Open the `Wallet` and navigate to the `Bridge` screen
2. Open the `Select Token` modal
3. The `Loading Skeleton` disappears while the `Owned` tokens list is populated.

### Actual result

https://github.com/brave/brave-browser/assets/40611140/fbf2c062-0b15-46b2-b25e-8253067c8966

### Expected result

Should continue to display the `Loading Skeleton` while the `Owned` tokens list is being `sorted` and `populated`.

https://github.com/brave/brave-browser/assets/40611140/85bf40ed-ce1e-4d75-b38d-22904b7f9422

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.64 Chromium: 126.0.6478.26 (Official Build)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.69.131 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 7f9c5cb9840ea18f57d485ee263b5bf4b1075953
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified passed on [brave/brave-core#24176](https://github.com/brave/brave-core/pull/24176)
- Verified `Loading Skeleton` is shown when `Owned` tokens list is populated on `Bridge` screen

https://github.com/user-attachments/assets/91a39e9d-7a4c-498d-b291-5106d9a34b8f
