### ISSUE TITLE
Ads panel in 0.62x should have Ads Coming Soon text

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#3900]
Please see 60.x issue created by @LaurenWags for details.
0.60.x -> https://github.com/brave/brave-browser/issues/3421
0.61.x -> (same as well) https://github.com/brave/brave-browser/issues/3500

cc: @jsecretan @bbondy @mandar-brave 

## Expected result:
same as 0.61.x
![screen shot 2019-02-19 at 1 55 52 pm](https://user-images.githubusercontent.com/28145373/53041509-2ee17180-3452-11e9-8490-c6f4b911eddf.png)

**Comment by kjozwiak** [comment]
Thanks for getting this filed @rebron 👍 Currently looks as follows when using `0.62.41 Chromium: 73.0.3683.86`:

<img width="648" alt="Screen Shot 2019-03-26 at 6 12 22 PM" src="https://user-images.githubusercontent.com/2602313/55037016-b93d6800-4ff2-11e9-933f-418411c5a7a9.png">

**Comment by ryanml** [comment]
Closed via: https://github.com/brave/brave-core/pull/2082

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.62.49 Chromium: 73.0.3683.86 (Official Build) (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Windows 10 OS Build 17134.523

- Verified the description mentioned in the issue


![image](https://user-images.githubusercontent.com/38657976/55307678-d8664a80-5475-11e9-9a42-e5292e9b0127.png)
