### ISSUE TITLE
URLs need to be updated for Help Desk installation guide

### ISSUE THREAD

**Issue by atsyed87** [brave/brave-browser#3901]
## Description 
Two support URLs  need to be changed to reflect the updated URL on the support.brave.com helpdesk. 

The original link `https://support.brave.com/hc/en-us/articles/360017886232-How-do-I-download-and-install-Brave-`

needs to be changed to `https://support.brave.com/hc/en-us/articles/360025390311-How-do-I-download-and-install-Brave-` 

The [Support URLs doc](https://docs.google.com/spreadsheets/d/16ubLUdPWmbzD4wiiiu0QbEGA6tbhJgqBemp_eVHz3FA/edit#gid=0) shows this link is present in two places: `kUpgradeHelpCenterBaseURL[]` and `kMac10_9_ObsoleteURL[]` but it should be replaced everywhere we are linking to the installation guide article.

## Steps to Reproduce

1. visit https://support.brave.com/hc/en-us/articles/360017886232-How-do-I-download-and-install-Brave-

## Actual result:
Zendesk 404 error

## Expected result:
Should link to the correct helpdesk URL: https://support.brave.com/hc/en-us/articles/360025390311-How-do-I-download-and-install-Brave-

## Reproduces how often: 
Always

**Comment by bsclifton** [comment]
@atsyed87 do you know where this help URL is located in the UI? For example, if we get a new build, how can we test this change?

**Comment by atsyed87** [comment]
I do not -- was my first real PR :) I found the URLs here:
https://docs.google.com/spreadsheets/d/16ubLUdPWmbzD4wiiiu0QbEGA6tbhJgqBemp_eVHz3FA/edit#gid=0

**Comment by kjozwiak** [comment]
@Brave-Matt would you know where that particular URL might exist within Brave so we can verify? If . the URL doesn't exist within Brave, we should add the `QA/No` label instead.

**Comment by kjozwiak** [comment]
@Brave-Matt found that the incorrect link was being used after receiving a `0x80070057` updater error. Because this is going to take a lot of effort in reproducing and possibly involving DevOps so we can get the staging server into a state where it fails with the above code, labelling as `QA/No`. This change is small enough that there's basically no risk. If someone disagree's, please let me know.

**Comment by bsclifton** [comment]
Thanks for following through with that, @kjozwiak 😄
