### ISSUE TITLE
Bug at sync words count calculation

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#39010]
### Description

When there is more than one space at the code phrase, count is calculated and displayed wrongly.

Related report is https://github.com/brave/brave-browser/issues/38745 

#### Android

1. Open Sync screen
2. `Scan or enter sync code` button
3. `Enter code words`
4. Type `d<space><space><space><space><space><space>d`
**Actual:** `Words count: 3`, **expected** `Words count: 2`
5. Type:
```
d<enter>
<enter>
<enter>
d
```
Actual: `Words count: 4`, expected `Words count: 2`

#### Desktop
1. Open brave://settings/braveSync , press `Start using sync` 
2. Press `I have a Sync Code`
3. Type `d<space><space>d`
**Actual:** `Words count: 3`, **expected** `Words count: 2`
4. Type:
```
d<enter>
d
```
Actual: `Words count: 1`, expected `Words count: 2`
5. Type `d<paste tab char from other text editor>d`
**Actual:** `Words count: 1`, **expected** `Words count: 2`

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

`1.69.0`

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by LaurenWags** [comment]
Requires `1.70.95` or higher for testing 👍🏻

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.95 Chromium: 128.0.6613.114 (Official Build) beta (64-bit)
-- | --
Revision | 58a39a29fce4db0417a269766b0157fad397767b
OS | Windows 11 Version 23H2 (Build 22631.4112)
```

1. Installed 1.70.95
2. launched Brave
3. opened `brave://settings/braveSync` 
4. pressed `Start using sync`
5. pressed `I have a Sync Code`
6. Type `d<space><space>d`
7. confirmed correct word count shown `Words count: 2`  
8. Type:
```
d<enter>
d
```
9. confirmed correct word count shown - `Words count: 2`  
10. Type `d<paste tab char from other text editor>d`
11. confirmed correct word count shown `Words count: 2`


step 5 | step 7 | step 9 | step 11
---- | ----- | ----- | -----
![image](https://github.com/user-attachments/assets/273314b3-58fc-4af5-9e04-b252411ff09d)|![image](https://github.com/user-attachments/assets/a0d9ac2d-30bb-4450-8082-bc292eac6e6e)|![image](https://github.com/user-attachments/assets/abd84bf2-047c-4213-b8f8-e1e81310ef2e)|![image](https://github.com/user-attachments/assets/b5fd9a6c-af4e-4416-87cb-26484a669f7b)

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240726.010 release-keys
Brave build: 1.70.101
Chromium: 128.0.6613.120 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/24186#issue-2351076234 and https://github.com/brave/brave-core/pull/24186#issuecomment-2318903143
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the expected word count is shown for both use cases

---------------------------

|`d<space><space><space><space><space><space>d`|`d<enter><enter><enter>d`|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/c33cb255-7b2c-49ec-96c4-75299a40a03b) | ![2](https://github.com/user-attachments/assets/39f39fa0-0bdc-43b2-94c4-8a2778da3b88) |
