### ISSUE TITLE
Make the title bar configurable in mobile app

### ISSUE THREAD

**Issue by atefBB** [brave/brave-browser#39023]
### Platforms

Android

### Description

In mobile view, the title bar can be placed at the bottom of the page, making the user experience more flexible and easier (similar to Safari on mobile and Firefox on Android). This can be a configurable option, meaning it is at the top of the page by default, but the user can choose to place it at the bottom. I look forward to hearing from you! Thank you.

**Comment by bsclifton** [comment]
Thanks for the recommendation! I'm going to close this as a duplicate - you can track the feature at https://github.com/brave/brave-browser/issues/7356 and subscribe for updates
