### ISSUE TITLE
[Wallet] Refactor NFT iframe logic

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39024]
### Description

Currently, we are using React to render NFT images that are in a sandboxed iframe. We should render this image using vanilla js to reduce the script size.

### Steps to reproduce

1. Create/import a wallet with nfts
2. view the NFTs tab of the portfolio page

### Actual result

NFTs take some time to load due to importing a large js bundle

### Expected result

NFTs should load faster

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

All

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.69.131 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 7f9c5cb9840ea18f57d485ee263b5bf4b1075953
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified NFT loads quickly
- Verified no regression when viewing NFT

https://github.com/user-attachments/assets/ba848301-5700-40c6-a79f-d5eb80bdc2bc
