### ISSUE TITLE
Remove cookie page from settings: brave://settings/cookies/detail?site=XYZ

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#39033]
### Description

Upstream Chromium has removed the cookie page which let you view all cookies for a site. We brought it back briefly by disabling the `kDeprecateCookiesTreeModel` flag in https://github.com/brave/brave-browser/issues/37030, but CR 125 immediately removed that flag which caused the page to be broken again. 

Note that users can already view cookies by going to a page and seeing/editing cookies via DevTools => Application => Cookies. That workaround doesn't address the use-case of seeing cookies for a page without actually visiting it, but if we want to address that use-case it needs to be a whole new feature; patching and tweaking upstream code is too brittle at this point. In the meantime this page is actively broken in Release and we should fix ASAP: https://github.com/brave/brave-browser/issues/38578.

### Steps to reproduce

1. Go to brave://settings/content/all
2. Select a site e.g. github.com (brave://settings/content/siteDetails?site=https%3A%2F%2Fgithub.com%2F)
3. Go to `Cookies and Site Data` (brave://settings/cookies/detail?site=github.com)

### Actual result

![image](https://github.com/brave/brave-browser/assets/5284154/eb4d580e-8eeb-46b7-b449-31ae99af2802)

![image](https://github.com/brave/brave-browser/assets/5284154/391d643f-c54d-4aa5-a826-9f3ac8241e47)

### Expected result

1. There should be no `Cookies and Site Data` under the Site Details page for a site.
2. brave://settings/cookies/detail?site=github.com page should not exist.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.66.118 Chromium: 125.0.6422.147 (Official Build) (arm64) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by emerick** [comment]
https://github.com/brave/brave-core/pull/17746 would essentially need to be reverted (we'd have to be careful of course; it's probably not quite a direct revert).

**Comment by iefremov** [comment]
There is a PR by a volunteer, can somebody review? @emerick @petemill  https://github.com/brave/brave-core/pull/24256

**Comment by kjozwiak** [comment]
The above requires `1.67.129` or higher for `1.67.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.67.131 Chromium: 126.0.6478.126 (Official Build) (64-bit)
-- | --
Revision | e3ca6babc88232bab25830c09164a034adae83bd
OS | Windows 10 Version 22H2 (Build 19045.4529)
```

Reproduced the issue using `1.67.123 Chromium: 126.0.6478.126` and STR from https://github.com/brave/brave-browser/issues/39033#issue-2352240949. The "Cookies and Site Data" option was present and when clicked, opened a blank page that did not show data:

Example | Example
--- | ---
![image](https://github.com/brave/brave-browser/assets/38657976/089b7670-62d2-4cb6-b941-dbfd91039381) | ![image](https://github.com/brave/brave-browser/assets/38657976/2ca3aa87-0105-4e1c-96b2-59d417b147ae)

Confirmed with `1.67.131 Chromium: 126.0.6478.126`, the "Cookies and Site Data" option was removed from the site specific page as expected:

![image](https://github.com/brave/brave-browser/assets/38657976/589e3e0d-38de-43ec-825b-cbcf0e0f2db3)

**Comment by wilrodx** [comment]
I will NOT and can NOT use Brave anymore because the idiots will not let you remove specific cookies and site data for unwanted sites.  This means that now I have to verify by phone or email all my banking and business sites before I can login.  It is a very stupid move by Brave that made me go back to using Firefox.  Do they only care about their convenience and not give a crap about their users?  Well they lost this user and I now use firefox as my browser.
