### ISSUE TITLE
Swap Error doesnt get cleared upon successful quote response

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#39031]
### Description

When there is a quote error for a `Swap` or `Bridge` quote, it doesn't get cleared out automatically after a successful quote.

### Steps to reproduce

1. Attempt to create a `Swap` or `Bridge` quote error (Sometimes happens intermittently)
2. Wait for the new quote countdown to fetch a quote
3. The `Error` does not get cleared and is persisted.

### Actual result

https://github.com/brave/brave-browser/assets/40611140/44557842-23fd-4487-b49c-6b134db6075f

### Expected result

Should be cleared out upon a successful quote response.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.19 Chromium: 126.0.6478.56 (Official Build)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.124 Chromium: 127.0.6533.73 (Official Build) beta (64-bit)
-- | --
Revision | dbc9035349f74e493f3293d93f4cbf35c597dfec
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24201}(https://github.com/brave/brave-core/pull/24201)
- Verified Swap error is removed when successful quote is fetched

https://github.com/user-attachments/assets/2b47fd24-f7fa-4593-9fab-c0aa94be9dcc
