### ISSUE TITLE
Quote Countdown Continues for Empty Swap Values

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#39030]
### Description

The new quote `Countdown` continues to countdown when `Swap` amounts have empty values.

### Steps to reproduce

1. Open the `Wallet` and navigate to the `Swap` screen
2. Select some tokens to swap and enter an amount to get a quote
3. After you get a quote, delete the swap amount
4. The new quote `Countdown` will continue to countdown

### Actual result

https://github.com/brave/brave-browser/assets/40611140/110c319d-c1cb-4f07-9c4a-55a9103ee0f0

### Expected result

It should stop the `countdown` when there are empty values for swap.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.19 Chromium: 126.0.6478.56 (Official Build)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.124 Chromium: 127.0.6533.73 (Official Build) beta (64-bit)
-- | --
Revision | dbc9035349f74e493f3293d93f4cbf35c597dfec
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24200](https://github.com/brave/brave-core/pull/24200)
- Verified quote countdown is removed when input value is cleared
- Verified for both Swap and Bridge

https://github.com/user-attachments/assets/79ea9bba-057c-46f5-b786-7984149e7c97
