### ISSUE TITLE
Update browser colors to use material static and dynamic color themes

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#39045]
### Description

I've remapped the whole browser design to take advantage of Chromium's material design color scheme. The color scheme now uses the same color mapping that Chromium for the most part.

It should also work with the new tri-color themes introduced with the material refresh, and accept any custom color the user may want to set up.

Note that every single color used in the browser needs to be updated to use the new tokens, including status colors (red/green/etc.), menues, including hamburger - right click menus, etc. 

This update depends on the new color tokens being brought into Nala (check with me or @fallaciousreasoning to see if it's already done).

Check with me for details

The details are all here:
https://www.figma.com/design/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?node-id=1386-11575&t=mViVLZtbKpYd3kFP-1

### Steps to reproduce

Not applicable

### Actual result

Not applicable

### Expected result

![image](https://github.com/brave/brave-browser/assets/15734630/c56463d4-8036-4029-80f7-e7292c7906f2)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Not applicable

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by aguscruiz** [comment]
Leaving this here as a way to brainstorm the best way to handle this.

I was thinking that perhaps the best path forward, if our objective is to use as much as Chromium's standards without losing our identity, is maybe start fresh with just their color theming.

That way we can get all their full theming capabilities, and we can add just our exclusive styles, like our vertical tabs, split view colors, etc.

**I'm saying this because:**
- The latest version of Nala uses the material design schemes already. So if we use those set of tokens, we would have to basically mimic Chromium's styles anyways (just using our palette colors, instead of theirs).
👆 Meaning I've transformed Nala to use material primitive palettes from 0 to 100, and the material naming scheme too.

- I've been moving to match Chromium styles for the browser in Nala too, so the relationship there is already close. 

- For upcoming features, I'll also be using material colors exclusively, so having them available would be easier.

Of course I don't know anything about how intricate our implementation is, and how difficult it would be to undo a lot of the work that's been done over the years.

But I wanted to start the conversation here

**Comment by simonhong** [comment]
I think we're already handling colors in upstream's way.
Let me explain briefly how upstream colors are replaced with ours and how it's used from UI.

For example, below UI code fill colors for top container(toolbar and etc)
and it gets colors by using `kColorToolbar` color id. via color provider.

```
void TopContainerBackground::PaintBackground(gfx::Canvas* canvas,
                                             const views::View* view,
                                             const BrowserView* browser_view) {
  bool painted = PaintThemeCustomImage(canvas, view, browser_view);
  if (!painted) {
    canvas->DrawColor(view->GetColorProvider()->GetColor(kColorToolbar));
  }
}
```

and upstream sets that color in `AddChromeColorMixer()`
```
  mixer[kColorToolbar] = {dark_mode ? SkColorSetRGB(0x35, 0x36, 0x3A)
                                                                : SK_ColorWHITE};
```

As we want to use different colors for that color,
we replace it in our mixer (`AddChromeLightThemeColorMixer()`. (below is light theme)
```
mixer[kColorToolbar] = {leo::kColorPrimitiveGray1};
```

As a result, UI code gets our `leo::kColorPrimitiveGray1`  instead of upstream's one.

This is how we replace upstream color with ours.

So, I think we could handle tri-state colors also like this.

**Comment by rebron** [comment]
cc: @brave/qa-team Coordinate with @aguscruiz for the test plan design/QA.

**Comment by aguscruiz** [comment]
Just got the update. We got the colors but we still need to do all the remapping of the new colors with the implementation to match Figma.

**Comment by LaurenWags** [comment]
Need a test plan for this one - marking as `QA/Blocked` for now

**Comment by fallaciousreasoning** [comment]
Added a vague test plan in the PR - sorry, let me know if you need something more detailed.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.70.100 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | c30694e8a60583be9d1784e4d42b4a0b94c70ab5
OS | Windows 10 Version 22H2 (Build 19045.4780)
```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.70.101 Chromium: 128.0.6613.120 (Official Build) beta (arm64)
-- | --
Revision | dc28ab38d07e9fa668801884c0c55f669ce538eb
OS | macOS Version 14.6.1 (Build 23G93)
```

<Details>
<summary>Dark mode should look roughly similar to 1.69</summary>

Confirmed Horizontal tabview is shown as expected in the default view
Confirmed Toolbar view/icons are shown as expected in the default view 


1.69.162 (default) | 1.70.101 (Default)
------ | ------
![Screenshot at Sep 05 16-49-07](https://github.com/user-attachments/assets/fc4ba5f6-09b5-4c41-9fc9-daa9fddc9180)|![image](https://github.com/user-attachments/assets/ca44b25a-814e-41c5-8514-280ceed9b6ad)
</Details>

<Details>
<summary>Light mode should look roughly similar to 1.69</summary>

Confirmed Horizontal tabview is shown as expected in the default view
Confirmed Toolbar view/icons are shown as expected in the default view 

1.69.162 (default) | 1.70.101 (Default)
------ | ------
![Screenshot at Sep 05 16-49-27](https://github.com/user-attachments/assets/ed44b080-c9d8-4109-bd0d-ce91a12e4dcc)|![Screenshot at Sep 05 16-45-00](https://github.com/user-attachments/assets/08024fed-2cc6-4bb5-bf62-4fc7a222a7a9)
</Details>

Tabs should have a hover effect


Omnibox should still have hover / select effect


Tor/Private mode should still be purple


Areas likely to be affected by this PR

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave	1.70.110 Chromium: 128.0.6613.138 (Official Build) beta (64-bit) 
Revision	7dec99ca278e09ce2087e9f04914f0aa2507ea4c
OS	Linux
```

**Comment by nintendork07** [comment]
can the dark mode colors please be reviewed again?  i updated to 1.70.117 today and the colors are too way dark for comfortable use.

![Screenshot 2024-09-19 at 11 09 59 PM](https://github.com/user-attachments/assets/185cc546-82a7-472f-b94f-521b8ab75757)

**Comment by FazDux** [comment]
> can the dark mode colors please be reviewed again? i updated to 1.70.117 today and the colors are too way dark for comfortable use.
I completely agree with this sentiment, it's quite distracting

**Comment by hazzuk** [comment]
It wasn't until reading the patch notes did I notice the shift in color. To add some balance to the previous comments, I'm quite happy with the overall change to a darker 'dark mode'.

But understandably any change in styling can be divisive. If there are specific parts people find "uncomfortable" or "distracting", that would be worth pointing out.

---

For me whilst I enjoy most of the changes, I find the new settings menu accent color on user inputs just looks so strange, it feels like a step backwards:

![image](https://github.com/user-attachments/assets/ed8893de-e824-41ff-a477-ec6ca3b59c8b)
