### ISSUE TITLE
Global side panel is not persisted with contextual side panel

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#39041]
### Description

global panel should be activated when active tab doesn't have contextual(per-tab) panel.

### Steps to reproduce

1. Open two tabs
2. Activate first tab and open Leo panel
3. Activate second tab and open playlist panel
4. Activate first tab and sidebar shows Leo panel
5. Activate second tab 

### Actual result

Sidebar is closed after activating second tab

### Expected result

Playlist panel should be shown after activating second tab as playlist is global side panel

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.67.115 Chromium: 126.0.6478.56 (Official Build) (x86_64) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Found this issue while investigating `ExtensionSidePanelBrowserTest.TabSpecificPanelsOwnViewState` test failure from `cr127` but it seems this test is also failed laster master.
cc @rebron @emerick

**Comment by simonhong** [comment]
Investigating..

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.69.88 Chromium: 127.0.6533.26 (Official Build) nightly (x86_64)
-- | --
Revision | d60303973dc3604d9d348b981322a8a04dcbb86d
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.69.88`
2. launched Brave
3. opened `brave://flags`
4. set `Playlist` to `Enabled`
5. clicked `Relaunch`
6. opened a new-tab page
7. loaded `abcnews.com`
8. clicked on `Leo` in the sidebar
9. opened a 2nd new-tab page
10. loaded `bbcnews.com`
11. clicked on `Playlist` in the sidebar
12. clicked back on the 1st tab (`abcnews.com`) and confirmed it still had the `Leo` tab expanded in the sidebar
13. clicked on the 2nd tab (`bbcnews.com`) and confirmed it still had the `Playlist` tab expanded in the sidebar

step 3-4 | step 6-8 | step 9-11 | step 12 | step 13
---------|----------|----------|---------|--------
<img width="1661" alt="Screen Shot 2024-07-08 at 3 18 26 PM" src="https://github.com/brave/brave-browser/assets/387249/c90ab595-a905-453f-96e9-23cd347696c9"> | <img width="1312" alt="Screen Shot 2024-07-08 at 3 17 19 PM" src="https://github.com/brave/brave-browser/assets/387249/03c2a72e-82d4-4918-97d1-4e6232fe6929"> | <img width="1661" alt="Screen Shot 2024-07-08 at 3 19 06 PM" src="https://github.com/brave/brave-browser/assets/387249/bc5a8a4a-a6d9-46df-910d-d35c1b2680f2"> | <img width="1661" alt="Screen Shot 2024-07-08 at 3 18 40 PM" src="https://github.com/brave/brave-browser/assets/387249/1e7823ee-6584-4e41-9883-2344761f4728"> | <img width="1661" alt="Screen Shot 2024-07-08 at 3 21 48 PM" src="https://github.com/brave/brave-browser/assets/387249/6a36628a-4085-433b-b889-3b780d46093a">
