### ISSUE TITLE
Minimum Snapping Window Size is Too Big

### ISSUE THREAD

**Issue by InklingGirl** [brave/brave-browser#39047]
### Description

On a 1920×1080p display, `brave-browser` (installed via `apt-get` from the project's official Deb repo) doesn't snap to the side of my screen as the expected 961-width window, it is instead 6 pixels wider & so overlaps w/ w/e is snapped to the other side.
 
Also, presumably due to my desktop configuration (I use the GNOME Shell extension [`dash-to-panel`](https://github.com/home-sweet-gnome/dash-to-panel) w/ the 'Keep original gnome-shell top panel' setting switched **on**) the snapped window is also rendering 23 lines taller than it needs to be, drawing behind the `dash-to-panel` transparent taskbar.

Neither of these related issues were a thing before today's update.

EDIT: I now notice that it must be even wider than 6 extra pixels, because when snapped to the right while on a page w/ a scrollbar, the scrollbar is occluded by the edge of the screen by a few pixels too, so it's snapping beyond the screen.

### Steps to reproduce

1. Run `brave-browser`
2. Snap window to a side of the screen
3. Snap another window (`brave-browser` or any other program) to the other side & observe the slight overlap between them

### Actual result

`brave-browser` window is too wide & (w/ & in relation to `dash-to-panel`) too tall:
![2024-06-15_01-15](https://github.com/brave/brave-browser/assets/9910447/488c3581-2ef5-4b4f-b6d1-db7ec1352b32)

### Expected result

`brave-browser` window to be the appropriate dimensions when snapped.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.67.115 Chromium: 126.0.6478.56 (Official Build) (64-bit) 

e1f8b4850805c2eea958bad7220c5e6e9202efaa

Linux

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [x] in the latest version of Chrome

### Miscellaneous information

More specific details about my OS:

_Ubuntu 22.04.4 LTS_ (_Jammy Jellyfish_) on the _Linux_ 6.5.0-35-generic kernel (kernel via latest first-party OS updates) & the _GNOME 42.9_ desktop environment (default DE) w/ _Wayland_ window server (default session), etc.

**Comment by nhaggin** [comment]
I am experiencing the same issue with the same version of Brave on Linux Mint 21.3/Cinnamon 6.0.4, on a system with dual 3840x2160 monitors.

**Comment by nhaggin** [comment]
I just installed 1.67.116/Chromium: 126.0.6478.71, and can confirm that the problem persists. Mint 21.3/Cinnamon 6.0.4, kernel 6.5.0-35.

**Comment by InklingGirl** [comment]
> I just installed 1.67.116/Chromium: 126.0.6478.71, and can confirm that the problem persists.

Thanks for doing that for me @nhaggin (I neglected to in my report), I guess that must mean it's an upstream bug. My Linux kernel's 6.5.0-35-generic too apparently.

**Comment by N1ve5h** [comment]
I am on OS: Linux Mint 21.3 x86_64, Kernel: 6.5.0-35-generic. I am experiencing the same issue. In the second step if I did another brave browser window, the window will overflow like a few pixels into my second monitor.

**Comment by InklingGirl** [comment]
> the window will overflow like a few pixels into my second monitor

@N1ve5h this is what I imagine would happen to me if I had a second monitor, based on what I noted here:
> EDIT: I now notice that it must be even wider than 6 extra pixels, because when snapped to the right while on a page w/ a scrollbar, the scrollbar occluded by the edge of the screen by a few pixels too, so it's snapping beyond the screen.

**Comment by InklingGirl** [comment]
The issue seems to have gone away for me?? I don't think `brave-browser` updated between now & when I opened this issue. Leaving it open for now.

**Comment by InklingGirl** [comment]
Also, I notice that often when I fullscreen, the video is scaled beyond the full res of my screen & so the edges of it & the player are cut off.

**Comment by iraklisg** [comment]
I noticed the same behavior in Manjaro Linux - Gnome version

**Comment by InklingGirl** [comment]
As of the newest `brave-browser` update:

1.67.119 Chromium: 126.0.6478.114 (Official Build) (64-bit) 

The initial window snapping size issue & #39080 appear to be completely resolved.

**Comment by nhaggin** [comment]
The issue is persisting for me with Brave 1.67.123 (Chromium 126.0.6478.126) on Mint 21.3/Cinnamon 6.0.4, but only if I do not use the system title bar/borders. Chromium itself exhibits the same behavior under the same conditions.

For example, here's Brave without system title bar:
![brave-snap](https://github.com/brave/brave-browser/assets/50666701/6df294bf-66ca-4350-93f8-ac1ae7ab67e7)

And here's Chromium with the system title bar:
![chromium-snap](https://github.com/brave/brave-browser/assets/50666701/28036867-10d1-4582-92b9-4ad9cdc15ed8)

Both windows are snapped to the top of my desktop; Brave is snapped to the right and Chromium to the left.

**Comment by InklingGirl** [comment]
will reopen

**Comment by nhaggin** [comment]
Just to make the situation more confusing: I installed official Google Chrome 126.0.6478.182, and it is snapping to the edges of the screen correctly both with and without the system title bar/window decorations. Something else got fixed between 126.0.6478.126 and now.

I am still running Brave 1.67.123/Chromium 126.0.6478.126.

**Comment by nhaggin** [comment]
I came back from lunch to find Brave 1.67.134 available in the stable repo and installed it. Windows are now snapping correctly in all configurations.

Many thanks!
