### ISSUE TITLE
Update Brave logo in Brave Wallet

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#39059]

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.69.110 Chromium: 127.0.6533.43 (Official Build) nightly (64-bit)
-- | --
Revision | b48482acae2813d6c44e4a83f48b479c56dbc116
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24268](https://github.com/brave/brave-core/pull/24268)
- Verified Logo is updated on Brave Wallet


Light | Dark
-- | --
<img  src="https://github.com/user-attachments/assets/b93d674d-3ab3-47d4-903e-ae5cbaffb872"> | <img  src="https://github.com/user-attachments/assets/1b1f1e44-7db7-4efc-af68-8c777f5ef3be">
