### ISSUE TITLE
Update text in chat for Llama 3

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#39068]
### Description

When selecting Llama 3 8b, it still shows Llama 2 in chat

### Steps to reproduce

1. New install
2. Open Leo, select Llama 3 from menu
3. Observe chat

### Actual result

![IMG_6390](https://github.com/brave/brave-browser/assets/17885425/97f7502a-b58d-4e59-a908-609e1cd6f7f4)

### Expected result

Should show updated model

### Reproduces how often

Easily reproduced

### Brave version

All versions

### Device/iOS version

iPhone, iOS 17.3

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.67.118` or higher for `1.67.x` verification 👍
