### ISSUE TITLE
NFT send selection shows multiple amounts for a single NFT

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#39065]
### Description

When selecting an NFT to send in the `Select Token` modal. NFT's in the list are showing more then `1` for the amount of a single NFT.

### Steps to reproduce

1. Add multiple `NFT's` with the same contract address to your wallet
2. Navigate to the `Send` screen and open the `Select Token` modal
3. You will see the amount will show more then `1`

### Actual result

![Screenshot](https://github.com/brave/brave-browser/assets/40611140/0bcdb646-a167-497c-a176-217984298df5)

### Expected result

Each `NFT` is unique by it's `tokenId` so we should not be showing more then `1` for the amount

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.85 Chromium: 126.0.6478.40 (Official Build) beta

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.69.124 Chromium: 127.0.6533.73 (Official Build) beta (64-bit)
-- | --
Revision | dbc9035349f74e493f3293d93f4cbf35c597dfec
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified when multiple NFT from the same collection is added only shows 1 amount

https://github.com/user-attachments/assets/a36f2972-8b2f-48dd-b6e5-6bcae8c07e35
