### ISSUE TITLE
`Next` button label/text for pin required/passkey-pin input is unreadable

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#39072]
### Description

`Next` button label/text for pin required/passkey-pin input is unreadable in `Light` mode

### Steps to reproduce

1. install `1.69.23`
2. launch Brave
3. insert an MFA device/passkey
4. load `https://github.com`
5. click on `Log in`
6. click on `Use a passkey` option
7. look at the resulting dialog

### Actual result

The button text/label for the `Next` button isn't readable in `Light` mode

<img width="1798" alt="Screen Shot 2024-06-14 at 5 03 14 PM" src="https://github.com/brave/brave-browser/assets/387249/4ac1c887-9c05-4dea-8b07-5ad5f85bd20c">

### Expected result

The `Next` button's text should be readable, in both `Dark` and `Light` browser modes

<img width="1798" alt="Screen Shot 2024-06-14 at 5 26 35 PM" src="https://github.com/brave/brave-browser/assets/387249/1da7b568-5451-4af3-b71d-e72d5f4b53df">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.69.23 Chromium: 126.0.6478.71 (Official Build) nightly (x86_64)
-- | --
Revision | 18f7cda0b21e2fd5a80aa0e7c862579270b64c8b
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @simonhong @bsclifton @fmarier @kdenhartog @brave/qa-team

**Comment by stephendonner** [comment]
This works in

```
Brave | 1.66.118 Chromium: 125.0.6422.147 (Official Build) (x86_64)
-- | --
Revision | 07af53490e0a52336cfb99a376f87671be258049
OS | macOS Version 11.7.10 (Build 20G1427)
```

<img width="1798" alt="Screen Shot 2024-06-14 at 5 26 35 PM" src="https://github.com/brave/brave-browser/assets/387249/1805a721-adc0-4258-9ba5-d72e95336330">

**Comment by stephendonner** [comment]
And also is fine in `Dark` modes for the following builds:


`1.66.118` | `1.69.23`
----------|----------
<img width="1798" alt="Screen Shot 2024-06-14 at 5 34 01 PM" src="https://github.com/brave/brave-browser/assets/387249/73f13235-7206-4478-bcf8-3c79bf7448f3"> | <img width="1429" alt="Screen Shot 2024-06-14 at 5 35 20 PM" src="https://github.com/brave/brave-browser/assets/387249/880683ea-64aa-4256-86a5-c8a14fd2c8ed">

**Comment by stephendonner** [comment]
I think this might be `macOS-specific` (maybe it happens on `linux` too?), as `Windows 10` renders the buttons natively, it looks like:

![image](https://github.com/brave/brave-browser/assets/387249/47dfde0b-0177-4fea-948b-72868ef4e1ea)

**Comment by fmarier** [comment]
https://github.com/brave/brave-browser/issues/38905 is another example of an unreadable button in light mode.

**Comment by simonhong** [comment]
Working on this now.

**Comment by kjozwiak** [comment]
The above requires `1.67.123` or higher for `1.67.x` verification 👍

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.67.123 Chromium: 126.0.6478.126 (Official Build) (x86_64)
-- | --
Revision | fc7619ef621fe4e6a0fa8b16c718f78ffc97a861
OS | macOS Version 13.6.7 (Build 22G720)
```

Note - unable to reproduce the issue using the PIN modal as I couldn't trigger this modal specifically, but was able to reproduce with the Passkey modal using `https://demo.yubico.com/playground`:

Using `1.67.119`,
1. Navigated to `https://demo.yubico.com/playground`
2. Created an account
3. Clicked on "Add Internal Authenticator" under "Internal (Built-in) Authenticators"
4. On the modal, clicked "Save another way" button
5. Selected "Your Brave profile" option
6. Saw that the text on the "Continue" button was unreadable when using light theme, but readable (if slightly difficult) with dark theme

Light | Dark
--- | ---
<img width="513" alt="Screenshot 2024-06-25 at 9 11 23 AM" src="https://github.com/brave/brave-browser/assets/28145373/de9b4f9b-0348-4613-9aca-a3b9b74ffd54"> | <img width="499" alt="Screenshot 2024-06-25 at 9 12 11 AM" src="https://github.com/brave/brave-browser/assets/28145373/c7896cbe-0d04-4ea8-94ef-7065c5dd13dd">

Upgraded to `1.67.123` and re-ran above steps. Confirmed "Continue" button was readable for both light and dark themes on the Passkey modal:

Light | Dark
--- | ---
<img width="496" alt="Screenshot 2024-06-25 at 9 13 16 AM" src="https://github.com/brave/brave-browser/assets/28145373/8cac5639-4054-45fe-8f7a-cc375501ec62"> | <img width="494" alt="Screenshot 2024-06-25 at 9 13 37 AM" src="https://github.com/brave/brave-browser/assets/28145373/32442b62-0453-4cc7-a947-dc58b2c729e5">

**Comment by stephendonner** [comment]
For posterity, also checked this using

```
Brave | 1.67.123 Chromium: 126.0.6478.126 (Official Build) (x86_64)
-- | --
Revision | fc7619ef621fe4e6a0fa8b16c718f78ffc97a861
OS | macOS Version 11.7.10 (Build 20G1427)
```

<img width="1312" alt="Screen Shot 2024-06-25 at 9 17 40 AM" src="https://github.com/brave/brave-browser/assets/387249/d8ae9023-10dc-4201-88b1-02efd67f6afb">
