### ISSUE TITLE
Brave crashes when trying to migrate from v3 to v5+ publisher_info_db version

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#3907]
## Steps to Reproduce

   1. Open Brave with a v3 publisher_info_db version database
   2. Go to rewards page or open rewards panel
   3. Brave will attempt to upgrade the database

## Actual result:

Fatal crash:
```
[2614:44291:0327/133243.040948:ERROR:database.cc(1713)] publisher_info_db sqlite error 1, errno 0: table activity_info has no column named month, sql: PRAGMA foreign_keys=off;INSERT INTO activity_info (publisher_id, duration, score, percent, weight, month, year, reconcile_stamp) SELECT publisher_id, duration, score, percent, weight, month, year, reconcile_stamp FROM activity_info_old;UPDATE activity_info SET visits=5;DROP TABLE activity_info_old;PRAGMA foreign_keys=on;
[2614:44291:0327/133243.041042:FATAL:database.cc(1726)] table activity_info has no column named month
```

## Expected result:
The database upgrades successfully

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 0.64.20 Chromium: 74.0.3729.22 (Developer Build) (64-bit)
-- | --
Revision | d183f516540c1a0c21310ced2e2170a534bca5a5-refs/branch-heads/3729@{#254}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
unknown

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

v3 database to test
[publisher_info_db.zip](https://github.com/brave/brave-browser/files/3014647/publisher_info_db.zip)

**Comment by jasonrsadler** [comment]
Caused by v4 upgrade after v3 has performed. v4 tries to select a month and year column that doesn't exist.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.63.42 Chromium: 74.0.3729.75 (Official Build) beta(64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Ubuntu 18.04 LTS

Used test plan from https://github.com/brave/brave-core/pull/2122

**Comment by kjozwiak** [comment]
@jasonrsadler just a quick question. When upgrading the `v3` database to the `v4` database, the two database schema's look the same. Is there a way to tell if the database was updated to `v4`? I'm noticing that the size of `publisher_info_db` increases when i's updated, but it looks the same in `DB Browser`, example:

Here's the `publisher_info_db` that you've provided in the `zip`:

<img width="897" alt="Screen Shot 2019-04-17 at 12 18 55 PM" src="https://user-images.githubusercontent.com/2602313/56304266-c2aa8380-610b-11e9-83d5-cac08f49b2fe.png">

Here's the `publisher_info_db` after visiting `brave://rewards` and upgrading to `v4`:

<img width="884" alt="Screen Shot 2019-04-17 at 12 25 28 PM" src="https://user-images.githubusercontent.com/2602313/56304327-e66dc980-610b-11e9-81e5-49710ffc1dc8.png">

The cases work and there's no crashes, but I was just curious if there's a way of telling what version the database was.
