### ISSUE TITLE
Support ExactOut swaps with 0x if swap provider is set to Auto

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#39070]
### Description

Currently, we do support fetching `ExactOut` swap quotes with 0x API, but the actual exchange is done in `ExactIn` mode.

Secondly, we recently added a way to specify the swap provider to use for fetching quotes in https://github.com/brave/brave-core/pull/23731. Turns out that LiFi, which is the default provider if set to `Auto`, doesn't support `ExactOut` swaps. We should fallback to 0x when `Auto` provider is set, in case user wants to do an `ExactOut` swap.

### Steps to reproduce

1. Go to Swap page, and select from and to tokens
2. Enter the amount in the "To amount" input field, instead of the "From amount" field.

### Actual result

We try to obtain fetch `ExactOut` quotes using LiFi which results in an error or no-op.

### Expected result

* When using `ExactIn` mode with `Auto` provider, LiFi should be used for fetching swap quote.
* When using `ExactOut` mode with `Auto` provider, 0x should be used for fetching swap quote.

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

1.69.x

### Android device

N/A

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [X] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.138 Chromium: 127.0.6533.100 (Official Build) beta (64-bit)
-- | --
Revision | 2569cce791e23282c250db59de277f2e81c33d9b
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified when using `ExactIn` mode with Auto provider, `LiFi` is used to fetch Swap quote
- Verified when using `ExactOut` mode with Auto provider, `0x` is used to fetch Swap quote

https://github.com/user-attachments/assets/64345f78-21f3-40d9-8e17-050045061d10

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.69.152 x64 build
- Verified steps from issue description
- Verified when using `ExactIn` mode with Auto provider, `LiFi` is used to fetch Swap quote
- Verified when using `ExactOut` mode with Auto provider, `0x` is used to fetch Swap quote

https://github.com/user-attachments/assets/19394a97-342f-43f3-9215-71affd97bb9a
