### ISSUE TITLE
sync: support dark mode

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#3908]
Sync screens should support dark theme when set by OS preference or by user. 

## Description 
Placeholder for dark theme screenshots of Sync.

**Comment by rebron** [comment]
cc: @rossmoody

**Comment by rossmoody** [comment]
Do we have one of these for Welcome screens?

**Comment by rebron** [comment]
@rossmoody nope, I can file one though.

**Comment by rebron** [comment]
Closing as stale. Sync already supports dark mode.
