### ISSUE TITLE
Fullscreen videos are cut off on the edges when fullscreening from a non-maximized window

### ISSUE THREAD

**Issue by urbenlegend** [brave/brave-browser#39080]
### Description

Updated Brave and now fullscreen videos are getting cut off on the edges when you fullscreen from a non-maximized window.

### Steps to reproduce

1. Open Brave and navigate to a Youtube video
2. Make sure window is non-maximized
3. Fullscreen the video

### Actual result

The edges of the video are cut off, particularly the bottom toolbar with the playback buttons. Here's a video to show the bug in action:

https://github.com/brave/brave-browser/assets/241316/4865365f-b2ca-4c7f-85e0-f1b5480adce4

### Expected result

Fullscreen video should fit into screen edges perfectly

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave	1.67.116 Chromium: 126.0.6478.71 (Official Build) (64-bit) 
Revision	f4237fe448716e50cca6e827ff87ffd701c7d0c7
OS	Linux

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by InklingGirl** [comment]
[It seems to be solved.](https://github.com/brave/brave-browser/issues/39047#issuecomment-2179999077)

**Comment by rebron** [comment]
Closing per last comment and fixed with 1.67.119 https://github.com/brave/brave-browser/issues/39047#issuecomment-2179999077
