### ISSUE TITLE
[Commands]: Quick commands group shows up on Android even though quick commands is disabled

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#39086]
1. Search for a bookmark or open tab

## Expected

There is no `Quick commands` header

## Actual

There is a `Quick commands` header

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP31.240617.010 release-keys
Brave build: 1.69.129
Chromium: 127.0.6533.73 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Launch Brave
2. Open any website
3. Tap in the URL search bar > *Verify*

**ACTUAL RESULTS:**
- Verified that `Quick commands` header is not shown

---------------------------

|Reproduced in `1.68.134`|Verified in `1.69.129`|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/b32f4f49-6aae-4ce0-832a-a2256972997c) | ![2](https://github.com/user-attachments/assets/77213bbb-7d44-4cfc-83ed-1f3350e05c1b) |
