### ISSUE TITLE
Playlist JS code is injected on many (all?) frames, even when feature is disabled

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#39084]
### Description

In the testing i've been doing with PageGraph, ~[this JS code](https://github.com/brave/playlist-component/blob/main/media_source_api_suppressor.js)~ [this code](https://sourcegraph.com/github.com/brave/playlist-component/-/blob/index.js?L269) seems to be being injected on all frames, in the page context / main frame.

Also as best as I can tell, i still see the JS being injected when i disable the playlist feature in brave://settings (as long as it was enabled at one point)

### Steps to reproduce

1. Make sure the playlist feature is enabled in brave://settings
2. Visit a standard website (I was observing it on both a localhost test site, example.org, and on the NTP). The JS will be injected into the document in the page context
3. Disable the feature in brave://settings
4. Visit the same sites, see the same JS is injected

### Actual result

JS was injected in all pages, in the main context

### Expected result

not having any JS injected in page context, not having any JS injected when the feature is disabled

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.22 Chromium: 126.0.6478.71 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by szilardszaloki** [comment]
@pes10k Just downloaded our latest Nightly, and I can't see the script being injected anywhere. Would you mind letting me know where you saw the script appearing exactly?

For context: the script you're referring to should only be injected into background `WebContents`es.
- renderer-side initialization is triggered here from the browser: [https://github.com/brave/brave-core/blob/6b09beeffda080aade3465132fde0c4c5635f17c/[…]nts/playlist/browser/playlist_background_web_contents_helper.cc](https://github.com/brave/brave-core/blob/6b09beeffda080aade3465132fde0c4c5635f17c/components/playlist/browser/playlist_background_web_contents_helper.cc#L65)
- that's the initializer function in the renderer: https://github.com/brave/brave-core/blob/6b09beeffda080aade3465132fde0c4c5635f17c/components/playlist/renderer/playlist_render_frame_observer.cc#L44
- and that's where the injection happens: https://github.com/brave/brave-core/blob/6b09beeffda080aade3465132fde0c4c5635f17c/components/playlist/renderer/playlist_render_frame_observer.cc#L79

Thanks!

**Comment by pes10k** [comment]
I believe what I’m seeing is being triggered here: https://sourcegraph.com/github.com/brave/brave-core/-/blob/components/playlist/renderer/playlist_render_frame_observer.cc?L102Will check more tomorrow On Jun 16, 2024, at 15:20, Szilard Szaloki ***@***.***> wrote:﻿
@pes10k Just downloaded our latest Nightly, and I can't see the script being injected anywhere. Would you mind letting me know where you saw the script appearing exactly?
For context: the script you're referring to should only be injected into background WebContentses.

renderer-side initialization is triggered here from the browser: https://github.com/brave/brave-core/blob/6b09beeffda080aade3465132fde0c4c5635f17c/[…]nts/playlist/browser/playlist_background_web_contents_helper.cc
that's the initializer function in the renderer: https://github.com/brave/brave-core/blob/6b09beeffda080aade3465132fde0c4c5635f17c/components/playlist/renderer/playlist_render_frame_observer.cc#L44
and that's where the injection happens: https://github.com/brave/brave-core/blob/6b09beeffda080aade3465132fde0c4c5635f17c/components/playlist/renderer/playlist_render_frame_observer.cc#L79

Thanks!

**Comment by szilardszaloki** [comment]
Hmm, that's not the script you mentioned above (but the "media detector" script), and is only injected into main world on Android. Talk to you tomorrow!

**Comment by pes10k** [comment]
apologies this is the code im seeing be inserted

https://sourcegraph.com/github.com/brave/playlist-component/-/blob/index.js?L259

I've corrected the issue description

**Comment by atuchin-m** [comment]
@pes10k Thanks for raising this.
It's a known issue for me. I hoped it would be fixed before releasing.
https://github.com/brave/reviews/issues/1570#issuecomment-2057599785

>when i disable the playlist feature in brave://settings (as long as it was enabled at one point)

That part looks scary.
@szilardszaloki could you please check it?

**Comment by pes10k** [comment]
@atuchin-m thank you.  A request though, when possible, please avoid merging code that does JS injection without user interaction if at all possible (especially if its not planned to ship in that form).

I think @bridiver has thoughts on this too.  Even setting aside the perf concerns, it makes it very difficult for some tools (pagegraph for example) to programmatically understand what pages are doing, if the browser is also unexpectedly injecting JS in the main page context JS too

**Comment by bridiver** [comment]
> @atuchin-m thank you.  A request though, when possible, please avoid merging code that does JS injection without user interaction if at all possible (especially if its not planned to ship in that form).
> 
> 
> 
> I think @bridiver has thoughts on this too.  Even setting aside the perf concerns, it makes it very difficult for some tools (pagegraph for example) to programmatically understand what pages are doing, if the browser is also unexpectedly injecting JS in the main page context JS too

It was a bug that it was not properly disabled when the feature is disabled, but it does seem relevant to perf to ensure that these things only run when necessary.

**Comment by szilardszaloki** [comment]
@pes10k @atuchin-m @bridiver Above predates me, but happy to fix to get Playlist back on Nightly ASAP. In release we're not planning to have any injections (other than the one that disables the `MediaSource` API in background `WebContents`es).
