### ISSUE TITLE
Remove KeyedService from some wallet services 

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#39088]
### Description
Refactor some wallet's internal stuff so it uses less KeyedService classes

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.138 Chromium: 127.0.6533.100 (Official Build) beta (64-bit)
-- | --
Revision | 2569cce791e23282c250db59de277f2e81c33d9b
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified wallet continues to work as expected

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.69.152 x64 build
- Verified steps from issue description
- Verified wallet continues to work as expected

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.0 Beta running 1.69 (152)
- Verified steps from issue description
- Verified wallet continues to work as expected
