### ISSUE TITLE
Follow up of #3732- [Ad] is NOT pre-pend the ads title

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3909]
## Description 

Follow up of #3732- [Ad] is NOT pre-pend the ads title

## Steps to Reproduce

   1. Navigate to www.brave.com
   2. Idle for 15+ seconds

## Actual result:

 [Ad] is NOT pre-pend the ads title

![image](https://user-images.githubusercontent.com/38657976/55103029-b5424080-50ed-11e9-8ebf-a8aaa5859681.png)

## Expected result:

[Ad] should pre-pend the title, i.e.

[Ad] British Test Ad
British Test Ad
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 0.63.20 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

### Reproducible on current release: No
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information

@brave/legacy_qa @tmancey

**Comment by tmancey** [comment]
@GeetaSarvadnya this issue has been superseded by #3769

**Comment by kjozwiak** [comment]
Closing as we decided to remove the `[Ad]` as per last weeks meeting when we discussed the above.

**Comment by GeetaSarvadnya** [comment]
@kjozwiak Thanks for closing was not knowing Ads title is superseded in #3769. Yesterday I didn't find this defect #3769 while testing Ads.
