### ISSUE TITLE
[Wallet] Show a preview when adding an NFT 

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39092]
### Description

We should show the NFT name, symbol and image during the "Add NFT" modal flow to inform the user as to which NFT will be added

### Steps to reproduce

1. Go to NFT portfolio tab
2. click the "+" icon
3. Fill-out the form (network, contract address, token id)

### Actual result

No preview is shown

### Expected result

the NFT name, symbol and image should be shown

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.66.118 Chromium: 125.0.6422.147 (Official Build) (arm64) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.136 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 47255350e0d135b2172cb9dd2ba344d3d7fe4572
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified NFT preview image is shown  when adding a new NFT

https://github.com/user-attachments/assets/201a157e-cea2-4ac5-8ce6-d34f1d56f3f4
