### ISSUE TITLE
Resolve copy https URL from omnibox

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#39095]
## Description 

we have an issue when someone copy a https URL, the clipboard ends up containing a http URL, both on release/nightly. 
![Screenshot_20240617-010108~2](https://github.com/brave/brave-browser/assets/5146988/3327e655-eb81-4e72-9481-a9a7a1c4e35c)

**Comment by kjozwiak** [comment]
The above requires `1.68.112` or higher for `1.68.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 AP31.240517.031 release-keys
Brave build: 1.68.115
Chromium: 127.0.6533.26 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Launch Brave
2. Open any `https` website, for example, https://ipinfo.io
3. Tap in the URL search bar > Tap the `Copy` button > *Verify*
4. Open `NTP` > Paste the URL from the buffer > *Verify*

**ACTUAL RESULTS:**
- Verified that copying/pasting `https` websites is working as expected
- Verified the same for `Standard` and `Private` tabs

---------------------------

`Galaxy Tab S8`
|`Standard` tab|`Private` tab|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/e61ad439-15ac-43b3-967f-02e71729a71c) | ![2](https://github.com/brave/brave-browser/assets/128532965/df93bb49-f3cc-4daa-9b6b-9b4a3675423a) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/f2a7dd52-cd5d-4d78-87ca-aaf5597b3053) | ![2](https://github.com/brave/brave-browser/assets/128532965/23ede32f-5608-401e-98f9-f4f45f538d44) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/6324dc1d-043a-4705-a747-38bdb0909671) | ![2](https://github.com/brave/brave-browser/assets/128532965/790afbbc-ebd9-4277-b984-de3234f0c447) |

`Pixel 7`

|`Standard` tab|`Private` tab|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/6eb83942-f312-4290-b919-9983da262312) | ![2](https://github.com/brave/brave-browser/assets/128532965/d517592d-7bc5-4def-8374-e164d480fb3b) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/dfd5ec86-7dad-4ac8-93e1-7f22d3122513) | ![2](https://github.com/brave/brave-browser/assets/128532965/87f1935d-c802-4196-901a-20f58c4eb1f7) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/473b9e8c-fe76-495a-a843-19fac882a1b2) | ![2](https://github.com/brave/brave-browser/assets/128532965/040d6ba9-5642-4c70-8edd-b3ed7e947d3e) |
