### ISSUE TITLE
#brave-horizontal-tabs-update Disabled: New tab icon not align properly 

### ISSUE THREAD

**Issue by quivenda** [brave/brave-browser#39091]
### Description

After update to 1.67.116 seems new tab (+) not vertically align, it shows 1px solid border color.

### Steps to reproduce

1. Install latest Brave stable or nightly (I tested on this branch)
2. Open `brave://flags/#brave-horizontal-tabs-update` and `Disabled`
3. Relaunch

### Actual result

![2024-06-17_13-16](https://github.com/brave/brave-browser/assets/125377517/9e38363a-8d72-4343-abf6-6bf7c57b23c9)
![2024-06-17_13-17](https://github.com/brave/brave-browser/assets/125377517/43ef5e4a-6493-437e-8c89-39abba10a96d)

### Expected result

![2024-06-17_13-28](https://github.com/brave/brave-browser/assets/125377517/0a963335-9cd4-4c23-a0d2-55baa7e31bc3)
![2024-06-17_13-29](https://github.com/brave/brave-browser/assets/125377517/55f3957e-f7ed-464a-a8bd-1ab844abe3d7)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave: 1.67.116 Chromium: 126.0.6478.71 (Official Build) (64-bit) 
Revision: f4237fe448716e50cca6e827ff87ffd701c7d0c7
OS: Linux

### Channel information

- [X] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment]
cc: @aguscruiz @zenparsing The disabled state for horizontal tabs could be our compact view and maybe go tighter/more compact with the UI.

**Comment by bsclifton** [comment]
Looks like the icon placement for new tab has been fixed:
![image](https://github.com/user-attachments/assets/11ee511a-0a81-4c6e-a5dc-c10125c5e16a)

There is still an issue with the favicon / tab title which is tracked with https://github.com/brave/brave-browser/issues/39985
