### ISSUE TITLE
[Wallet/iOS]: Add gas token balance checking in send confirmation 

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#39097]
Currently, we only check gas token balance with account's native token balance. This could make user lose gas money by submitting a send tx with insufficient balance if user send gas/native token. 
In this case, we should compare estimated gas fee with the subtraction of native token balance and send amount.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.0 Beta running 1.69 (147)
- Verified steps from [brave/brave-core#24326](https://github.com/brave/brave-core/pull/24326)
- Verified `Insufficient funds` message is shown when sending 100% of the token 
- Verified error popup message is shown for FIL send transaction using 100% of the available balance

https://github.com/user-attachments/assets/ff2aead2-f5df-4c22-b887-8985f8563040
