### ISSUE TITLE
Open brave from terminal

### ISSUE THREAD

**Issue by fadiphi** [brave/brave-browser#391]
I am currently trying to open webpages from a terminal using brave, but using something like `brave google.com` does not open a new tab in my window nor it opens a new one. What am I doing wrong? Thanks!

**Comment by srirambv** [comment]
Is this for the brave-core browser or muon browser-laptop? For browser-laptop passing command line argument doesn't load the site. There is an issue logged for the command line option on browser-laptop https://github.com/brave/browser-laptop/issues/388.

Closing the issue.

**Comment by George-Vasileiou** [comment]
For me, in Kali Linux, I just have to type `brave-browser` to open it or `brave-browser google.com` to open it and immediately open google.com . I hope I helped you 😁

**Comment by sumuhere** [comment]
> For me, in Kali Linux, I just have to type `brave-browser` to open it or `brave-browser google.com` to open it and immediately open google.com . I hope I helped you grin

Yeah! this works on Ubuntu 20.04 too

**Comment by raamnathmallya** [comment]
I use Ubuntu 20.04 and i'm getting this response. What am i doing wrong here?
```
xxx:~$ brave-browser
brave-browser: command not found

```

**Comment by George-Vasileiou** [comment]
> 

I currently do not have an Ubuntu environment to test this on. Do you have brave installed? If you do, maybe try to uninstall it and install it again. @thatsuman could you help here?

**Comment by raamnathmallya** [comment]
So this is what I did: 
```
raamnathmallya@xxx:~$ which brave
/snap/bin/brave
raamnathmallya@xxx:~$ /snap/bin/brave
```
And the Brave browser opened. After which, I just had to type `brave` and the browser opened. 
I guess the above `/snap/bin/brave` worked as a refresh of some sort!

**Comment by srirambv** [comment]
@raamnathmallya you have a snap install which will only take `brave` as the command line to launch you can't use `brave-browser`

**Comment by raamnathmallya** [comment]
Thank you :smile:  @srirambv

**Comment by ronn** [comment]
On MAC: /usr/bin/open -a "/Applications/Brave Browser.app" "{link}"
Example: /usr/bin/open -a "/Applications/Brave Browser.app" "https://github.com/brave/brave-browser/issues/391"

**Comment by ashishrout-tech** [comment]
On windows, use `start brave`
