### ISSUE TITLE
Browser does not see directories that are mounts in the root of Linux file system

### ISSUE THREAD

**Issue by bhlevca** [brave/brave-browser#3910]
## Steps to Reproduce

   1. create a mount  in the root filesystem  that will be shown as a directory (use mount)
   2. go to a browser a page and right-click->Save As
   3. in the new open Save As box select the root of the file system
   4. observe that the additional directories are not shown 
   5. The funny thing is that the /home directory is shown although is the same type of mount  

## Expected result:
To see all the directories whether they are mounts or not. All the other browsers, including Chrome show them. It appears that Brave is using a Windows inspired save as dialog box. Are you using using Wine? 
See all the directories including mounts

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Brave | 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
Not reproducible in Chome is all Brave.

**Comment by rebron** [comment]
@bhlevca Can you update to a more recent version and see if this is still an issue?

**Comment by bhlevca** [comment]
@rebron I will try, I have not been using brave lately because I am on a 30 bit depth color display, which makes brave display complementary colours and unreadable text
