### ISSUE TITLE
Leo screen unresponsive after using app switcher with Leo menu opened

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#39109]
### Description

Leo screen unresponsive after using app switcher with Leo menu opened

Seems like only way to fix it is to switch apps again and return which will fix the responsiveness or close and relaunch Brave.

### Steps to reproduce

1. New install
2. Opt in to Leo, open menu
3. Using app switcher, switch to another application and then back to Brave
4. Check UI / App functionality

### Actual result

![IMG_6441](https://github.com/brave/brave-browser/assets/17885425/d4718f59-12c7-4e08-8a03-555374fbdddc)

### Expected result

Leo screen should be responsive after switching applications.

### Reproduces how often

Easily reproduced

### Brave version

1.69.x - reproducible
1.67.x - reproducible
1.66.1 - reproducible

### Device/iOS version

iPhone, iOS 17

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.68.113` or higher for `1.68.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` and `iPad (7th Gen)` running `iOS 17.5.1` using version `1.68.115`

- Ensured that Leo screen is responsive after backgrounding app with the Leo menu opened as mentioned in https://github.com/brave/brave-browser/issues/39109#issue-2357963087


https://github.com/brave/brave-browser/assets/17885425/36ef0ab3-9b99-42af-966e-91aa203f031a

https://github.com/brave/brave-browser/assets/17885425/1e39412c-f23b-4721-a1db-ea815b22e490
