### ISSUE TITLE
[iOS] Toolbar state resets after 'open in new tab' action is picked on a hyperlink

### ISSUE THREAD

**Issue by iccub** [brave/brave-browser#39108]
### Description

The back button becomes deactivated after a hyper link preview

### Steps to reproduce

1. Open wikipedia
2. Long press on a link there
3. Check back button

### Actual result

https://github.com/brave/brave-browser/assets/6643505/81bbe249-9677-4756-9f75-2a38cc7d94f1

Notice back button goes disabled like there is no history forward backward 

### Expected result

The proper back button state should be shown

### Reproduces how often

Easily reproduced

### Brave version

1.68

### Device/iOS version

Any

### Affected browser versions

- [ ] latest AppStore
- [x] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [x] with Brave Shields disabled

**Comment by Uni-verse** [comment]
Verified on iPhone 12 running iOS 17.5.1 using version 1.69 (156)

### `Test Case 1:`

1. Opened wikipedia homepage
2. Long pressed on a link there
3. Ensured back button state is correct

Example | Example | Example
-|-|-
![IMG_7158](https://github.com/user-attachments/assets/6569684d-b59a-4082-91d4-4956ef24014e) | ![IMG_7159](https://github.com/user-attachments/assets/ed0ca538-9360-4157-b9c8-4475d0af9802) | ![IMG_7160](https://github.com/user-attachments/assets/17370f3c-1da1-43e0-b080-8b04919eab6f)

### `Test Case 2:`

1. Loaded news article
2. Enabled Reader Mode
3. Disabled Reader Mode
4. Checked share button is in bottom toolbar

Step 1 | Step 2 | Step 3 | Step 4
-|-|-|-
![IMG_7149](https://github.com/user-attachments/assets/2574fd07-c963-4c73-b26f-542401e1405e) | ![IMG_7154](https://github.com/user-attachments/assets/355eceac-ea14-4615-9cb0-ec7f84e84419) | ![IMG_7155](https://github.com/user-attachments/assets/a4474d97-72b9-40fc-964d-f6963cc25f24) | ![IMG_7156](https://github.com/user-attachments/assets/c0caa135-4a0a-4f45-936d-18c2a44bdfd8)
