### ISSUE TITLE
Small text update within Bbrave://flags

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#39105]
### Description

Please update the text as follows

The changes will take effect the next time you relaunch the app

![IMG_2FC605371C79-1](https://github.com/brave/brave-browser/assets/7606853/431231d7-927f-4009-b008-9996f3f4c718)

### Steps to reproduce

1. NA
2. 
3. 

### Actual result

NA

### Expected result

NA

### Reproduces how often

No steps to reproduce

### Brave version

NA

### Device/iOS version

NA

### Affected browser versions

- [X] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kylehickinson** [comment]
Duplicate of https://github.com/brave/brave-browser/issues/37404
