### ISSUE TITLE
[Shred] Show the site name in the warning prompt before Shredding

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#39113]
### Description

We currently don't show the site's name in the warning prompt. Displaying this would make it clearer to the user what's being Shredded. We should truncate to 10 characters if it's too long.

### Steps to reproduce

1. Enable Shred via brave://flags
2. Open cnn.com
3. Try to Shred (via long pressing tab button for e.g.)

### Actual result

No site name:
![Image from iOS](https://github.com/brave/brave-browser/assets/5284154/9d383857-5083-444a-8e7a-c3b9f25bd7f5)

### Expected result

![image (8)](https://github.com/brave/brave-browser/assets/5284154/a06f436d-119b-422a-9b7b-fa456673331b)

The site name is truncated to 10 characters.

### Reproduces how often

Easily reproduced

### Brave version

Latest Nightly: 1.69 (27) on TestFlight

### Device/iOS version

Any

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by cuba** [comment]
QA not needed because this was "reverted" [here](https://github.com/brave/brave-core/pull/24755)
