### ISSUE TITLE
[iOS] - History Search not working correctly

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#39114]
### Description

- History Search does not work
- History Search bar disappears when no results are shown

### Steps to reproduce

1. Try to Search/Filter History

### Actual result

- Not working
- Search bar disappears

### Expected result

- Should filter search results and the search bar should not disappear

### Reproduces how often

Easily reproduced

### Brave version

1.68.x

### Device/iOS version

- iPhone

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.68.100` or higher for `1.68.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6
Brave build: 1.68 (106)
BraveCore: 1.68.106 (126.0.6478.126)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/39114#issue-2358053705 and https://github.com/brave/brave-core/pull/24250#issuecomment-2189549363
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `History search` is working and showing the results properly
- Verified that the search bar is not disappearing

---------------------------

https://github.com/brave/brave-browser/assets/128532965/3a029f84-23c6-409f-b63d-591245d8dfb7
