### ISSUE TITLE
When settings change all tabs are reloaded

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#39117]
### Description

Instead of reloading only the active tab like desktop, we reload all the tabs when settings like "Shield Level" changes. This can really hit the device hard if a lot of tabs are open and results in popups such as location permission to appear for inactive tabs

### Steps to reproduce

1. Open multiple tabs (something that you can the page has been reloaded) such as https://dev-pages.brave.software/filtering/cosmetic-filtering.html and https://dev-pages.bravesoftware.com/filtering/cosmetic-filtering.html (make sure to run the tests so you can see they are cleared after a page reload)
2. Change Shield Level
3. Go to an inactive tab and see if the page was reloaded

### Actual result

Page is reloaded

### Expected result

Page should not be relaoded

### Reproduces how often

Easily reproduced

### Brave version

1.66

### Device/iOS version

Any

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

This issue has been around since 2022

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6.1
Brave build: 1.69 (160)
BraveCore: 1.69.160 (128.0.6613.114)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/39117#issue-2358156366
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `active` tab is reloaded when updating the `Shields` settings.
- Verified that the `inactive` tab is NOT reloaded when updating the `Shields` settings.

---------------------------

*Reproduced in `1.66.1`*

https://github.com/user-attachments/assets/b2554e78-f4fe-4166-95cb-703550bd6ca4

*Verified in `1.69.160`*

https://github.com/user-attachments/assets/96a24af7-636d-44e4-8d1c-d165beb8bb10
