### ISSUE TITLE
Allow only HTTPS and localhost HTTP URL for RPC, icon, and explorer URLs in AddChain

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#39111]
During BTC security/privacy review, security team would like to disallow HTTP urls unless it's localhost.
https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1718134732414669

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.136 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 47255350e0d135b2172cb9dd2ba344d3d7fe4572
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24249](https://github.com/brave/brave-core/pull/24249)
- Verified editing a network and updating RPC URL to be `HTTPS` shows `Invalid URL` message

https://github.com/user-attachments/assets/13e03f8c-0e1c-44fe-b6e8-392af761922f

**Comment by srirambv** [comment]
Android verification failed. Logged https://github.com/brave/brave-browser/issues/40498. Removing OS/Android label from the issue as follow up issue is logged
