### ISSUE TITLE
welcome screen: support dark mode 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#3911]
Welcome screens should support dark theme when set by OS preference. 

## Description 
Placeholder for dark theme screenshots of Welcome Tour.

**Comment by rossmoody** [comment]
![Welcome Light](https://user-images.githubusercontent.com/29072694/58681910-6e5a0c80-8323-11e9-9901-aef6181af70c.jpg)
![Welcome Dark](https://user-images.githubusercontent.com/29072694/58681912-6e5a0c80-8323-11e9-8409-f8d6d3547cd9.jpg)

**Comment by imptrx** [comment]
Test Plan:
1. Ensure OS is dark mode enabled; ensure theme is set to `System theme (default)` on welcome or `Same as ____OS` in settings page
2. Change system OS, welcome page should change accordingly
3. All welcome screens should be dark mode enabled

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/2909
Encountered https://github.com/brave/brave-browser/issues/5950
