### ISSUE TITLE
Download bar support Mojave dark mode 

### ISSUE THREAD

**Issue by levinunnink** [brave/brave-browser#3912]
## Description

Download bar is illegible when in dark mode on macOS Mojave. 

## Steps to Reproduce

Download any file Brave

## Expected result

The download bar should be readable.

## Actual result

It appears that the color values in the download bar are hardcoded instead of using the dynamic system colors, like `[NSColor controlTextColor]`.

<a href="https://d.pr/i/7soypL"><img src="https://d.pr/i/7soypL.png" /></a>

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

- Version 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)
- macOS 10.14.1 (18B75)

**Comment by simonhong** [comment]
Duplicated with https://github.com/brave/brave-browser/issues/3708 and fixed.
