### ISSUE TITLE
[iOS] - Playlist crash deleting too many items

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#39131]
### Description

- Deleting dangling items are too slow and can use significants amount of memory, eventually crashing the app

### Steps to reproduce

1. Have 16GB of playlist items on 1.66
2. Update to 1.66.1

### Actual result

- Crash or frozen

### Expected result

- Should not crash or freeze

### Reproduces how often

Easily reproduced

### Brave version

1.66.1

### Device/iOS version

All

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.67.125` or higher for `1.67.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.67 (125)`

- [x] Went through the test plan in https://github.com/brave/brave-core/pull/24260#issue-2360233436 on a new install and ensured that the app size was reduced after using the `7 Day reset` from the Playlist debug menu and restarting app.
- [x] Ensured adding videos to an already existing Playlist with 5000+ items does not cause app to freeze or crash when applying 7 day clean up. This includes opening video in Playlist. 

Setup | Playlist | before 7 day clean up | after 7 day clean up | 
-|-|-|-
![IMG_6577 2](https://github.com/brave/brave-browser/assets/17885425/f03a1d60-8d48-43ac-9935-6c3a752019a3) | ![IMG_6578 2](https://github.com/brave/brave-browser/assets/17885425/259b2437-4fe1-4775-9d91-57cb012d3b52) | ![IMG_6579 2](https://github.com/brave/brave-browser/assets/17885425/ce65b72f-61d2-413b-ac98-fea1c4fa3bac) | ![IMG_6580 2](https://github.com/brave/brave-browser/assets/17885425/19c4a6d1-31f4-4b6a-8d4d-f38499c5b0dd)

- [x] Ensured there were no issues using Playlist after upgrading to 1.67 (125) with some items in Playlist. 
- [x] Ensured adding and deleting Playlist items without issue on upgraded profile.

1.66.2 | 1.67.125
-|-
![IMG_6583 2](https://github.com/brave/brave-browser/assets/17885425/fe010de2-6a50-46af-9a06-a0a3d2158f7e) | ![IMG_6584 2](https://github.com/brave/brave-browser/assets/17885425/83611a05-35a7-4fba-ba1d-2c2e3523874b)
