### ISSUE TITLE
UI Issue - Double “Done” when a user tries to edit the custom search engines

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#39137]
### Description

When user navigates to Search Engines customization from SearchViewController, the controller is being presented modally and the left bar button is shown as done.

This creates a confusion when user wants to edit table and there are 2 done buttons on the controller.

Link: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1718737979980609

### Steps to reproduce

1. Tap address bar and tap search icon (settings) above it 
2. Press Edit
3. 2 done buttons

### Actual result

2 done buttons for different functionality 

https://github.com/brave/brave-browser/assets/6643505/e18a6285-af57-439f-889b-84683fc89a08

### Expected result

To show the done button for this type of scenario shown as X

### Reproduces how often

Easily reproduced

### Brave version

NA

### Device/iOS version

NA

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [x] with Brave Shields disabled

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.69 (156)`

- Ensured that there is only a single `Done` button when trying to edit custom search engines.

Example | Example
-|-
![IMG_7173](https://github.com/user-attachments/assets/a55eb240-23d2-4ddc-89c0-1026046b701d) | ![IMG_7174 2](https://github.com/user-attachments/assets/82bf54c7-3358-4913-8f85-92c6f40fcabb)
