### ISSUE TITLE
QA Issue for tracking Multi-device Refresh tests

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#39132]
See test plan https://github.com/brave/qa-resources/wiki/Multi%E2%80%90device-Refresh-(MDR)-Test-Plan-(desktop)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```

```

## Purchases

### purchase `Leo Premium`

<details>

### Steps:
1. install [appropriate Brave version]
2. launch Brave using `--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev`
3. load `account.bravesoftware.com`
4. enter basic auth username/password
5. enter @mailinator.com test address
6. click `Get login link`
7. click on the `Log in to Brave` link in the resulting email
8. click on `Browse plans`
9. click on `Start free trial` button
10. complete Stripe checkout
11. confirm `You have active credentials loaded!` green banner and messaging

### Expected Results:


</details>

### purchase `VPN` + `Leo`
<details>

### Steps:
1. install [appropriate Brave version]
2. launch Brave using `--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev`
3. load `account.bravesoftware.com`
4. enter basic auth username/password
5. enter @mailinator.com test address
6. click `Get login link`
7. click on the `Log in to Brave` link in the resulting email
8. click on `Browse plans`
9. click on `Start free trial` button on the `Brave VPN` section
10. complete Stripe checkout
11. confirm `You have active credentials loaded!` green banner and messaging
12. click on `Plans`
13. click on `Start free trial` on the `Leo Premium` section
14. complete Stripe checkout

### Expected Results:



</details>

### purchase `Brave Talk Premium`
<details>

### Steps:
1. install [appropriate Brave version]
2. load `account.bravesoftware.com`
3. enter basic auth username/password
4. enter @mailinator.com test address
5. click `Get login link`
6. click on the `Log in to Brave` link in the resulting email
7. click on `Browse plans`
8. click on `Start free trial` button for the `Brave Talk Premium` product
8. complete Stripe checkout
10. confirm `Brave Talk Premium` page, with `Start Premium call` button


### Expected Results:


</details>

### purchase `Brave Search Premium`
<details>

### Steps:
1. install [appropriate Brave version]
2. load `account.bravesoftware.com`
3. enter basic auth username/password
4. enter @mailinator.com test address
5. click `Get login link`
6. click on the `Log in to Brave` link in the resulting email
7. click on `Browse plans`
8. click on `Buy now` button for the `Brave Search Premium` product
8. complete Stripe checkout

### Expected Results:

Product shows as `Paid` in `brave://skus-internals`, with an appropriate `expires_at` value 1 month from the original `created_at` date


</details>


### purchase all Premium products
<details>

1. install [appropriate Brave version]
2. launch Brave using `--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev`
3. load `account.bravesoftware.com`
4. enter basic auth username/password
5. enter @mailinator.com test address
6. click `Get login link`
7. click on the `Log in to Brave` link in the resulting email
8. click on `Browse plans`
9. click on `Start free trial` button on the `Brave VPN` section
10. complete Stripe checkout
11. confirm `You have active credentials loaded!` green banner and messaging
12. click on `Plans`
13. click on `Start free trial` on the `Leo Premium` section
14. complete Stripe checkout
15. click on `Plans`
16. click on `Start free trial` on the `Brave Talk Premium` section
17. complete Stripe checkout
18. click on `Plans`
19. click on `Buy now` on the `Brave Search Premium` section


### Expected Results:

Each purchased product shows as `ActiveCredentials` in `brave://skus-internals` with a valid, extended `expires_at` value; should be 1 month past the initial `expires_at`


### purchase (a) specific combination(s) of the above

</details>


## `Refresh` (redeem) credentials
<details>

### Steps:
1. install [appropriate Brave version]
2. launch Brave on `device A`
3. load `account.bravesoftware.com`
4. enter basic auth username/password
5. enter @mailinator.com test address
6. click `Get login link`
7. click on the `Log in to Brave` link in the resulting email
8. click on `Browse plans`
9. click on `Start free trial` for `Brave VPN`
10. complete Stripe checkout
11. confirm working `Brave VPN`
12. quit Brave
13. switch to a new device, `device B`
14. launch Brave
15. log in to `account.bravesoftware.com` using the same @mailinator.com address you used for `device A`
16. click on `Refresh Leo`


### Expected Results:

The credentials on `device B` should be valid (`ActiveCredentials`) and mirror those of `device A` (same `expires_at`)

</details>


## Max limit # of actively-linked/recovered devices {1.68.x, 1.61.x}
<details>


### Steps:
* run `Refresh (redeem) credentials` testcase
* repeat for 9 devices (totaling 10)
* confirm no errors linking
* attempt redeeming `device A` credentials on device # 11

### Expected Results:

Confirm visible, logical error message (`exceeded recovery limit for subscription` from https://github.com/brave-intl/subscriptions/pull/570/files#diff-a5ce247e55d5a20707517e34bef620f2eb369b4f9b8fa44fdfb2c18a702418e8R29)?

</details>


## Auto-renew (within 5 days of exp.) {1.68.x, 1.61.x}
<details>

### Steps:
1. install [appropriate Brave version]
2. launch Brave using `--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev`
3. load `account.bravesoftware.com`
4. enter basic auth username/password
5. enter @mailinator.com test address
6. click `Get login link`
7. click on the `Log in to Brave` link in the resulting email
8. click on `Browse plans`
9. click on `Start free trial` for `Brave VPN`
10. complete Stripe checkout
11. open `brave://skus-internals`
12. confirm `created_at` and `expires_at` are 1 month apart
13. quit Brave
14. time-travel (advance system clock) to 4 days before `expires_at` for VPN in `brave://skus-internals`
15. relaunch Brave
16. wait a couple minutes
17. check `brave://skus-internals`


### Expected Results:

Product shows as `ActiveCredentials` in `brave://skus-internals` with a valid, extended `expires_at` value; should be 1 month past the initial `expires_at`

</details>


## Cancellation
<details>

### Steps:
1. install [appropriate Brave version]
2. launch Brave using `--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev`
3. load `account.bravesoftware.com`
4. enter basic auth username/password
5. enter @mailinator.com test address
6. click `Get login link`
7. click on the `Log in to Brave` link in the resulting email
8. click on `Browse plans`
9. click on `Start free trial` button
10. complete Stripe checkout
11. confirm `You have active credentials loaded!` green banner and messaging* cancel VPN
12. click on `Cancel plan`
13. click on `Cancel subscription`
14. confirm `Your plan has been canceled.` message

### Expected Results:

Product shows as `Paid` in `brave://skus-internals`, with an appropriate `expires_at` value 1 month from the original `created_at` date

</details>


## Renewal
<details>


### Steps:
1. install [appropriate Brave version]
2. launch Brave using `--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev`
3. load `account.bravesoftware.com`
4. enter basic auth username/password
5. enter @mailinator.com test address
6. click `Get login link`
7. click on the `Log in to Brave` link in the resulting email
8. click on `Browse plans`
9. click on `Start free trial` button
10. complete Stripe checkout
11. confirm `You have active credentials loaded!` green banner and messaging* cancel VPN
12. click on `Cancel plan`
13. click on `Cancel subscription`
14. confirm `Your plan has been canceled.` message
15. click on `Return to account`
16. confirm `Your subscription has been canceled.  Access until {1 month from now}.`
16. click on `Renew plan`


### Expected Results:

Product shows as `ActiveCredentials` in `brave://skus-internals` with a valid, extended `expires_at` value

</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```

```

**Comment by stephendonner** [comment]
I consider myself done with `Win10-x64` but am leaving open until @MadhaviSeelam is able to finish to her satisfaction on `Win11-x64` 👍 

I'm moving on to `macOS-arm64` coverage.

**Comment by mattmcalister** [comment]
If we could get someone to check the happy path for `Auto-renew (within 5 days of exp.), 1.68x` on either or both Android and iOS then we could make a call on whether to move ahead and push this. cc @kjozwiak @stephendonner @MadhaviSeelam @pavelbrm @bbondy

**Comment by Uni-verse** [comment]
In progress on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using version: 

```
Brave	1.68.101 Chromium: 126.0.6478.126 (Official Build) beta (64-bit) 
Revision	ffa8411f4c8fe36c0e399f60ef7c24b3cf7d7402
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

**Case: VPN - IAP**

<details>

- Ensured installing profile and enabling VPN is successful after purchasing via IAP.
- Ensured disabling and then re-enabling VPN is working.

Example | Example | Example
-|-|-
![Screenshot 2024-07-03 at 10 55 56 AM](https://github.com/brave/brave-browser/assets/17885425/4dc3543e-9789-4181-bd0c-f96cfa9bc15a) | ![Screenshot 2024-07-03 at 10 56 01 AM](https://github.com/brave/brave-browser/assets/17885425/cf3d0ee2-d806-4163-8d12-748c5b902566) | ![Screenshot 2024-07-03 at 10 56 12 AM](https://github.com/brave/brave-browser/assets/17885425/42e17cf6-d505-47ac-81c0-b7f22606793e) | ![Screenshot 2024-07-03 at 10 56 24 AM](https://github.com/brave/brave-browser/assets/17885425/ac795b35-9000-4854-b52c-60dde5611557)

</details>

**Case: Leo - IAP**

<details>

- Ensured Leo premium status is enabled after completing purchase via IAP.
- Ensured premium models are accessible and user is not rate limited.

Example | Example | Example
-|-|-
![Screenshot 2024-07-02 at 12 33 43 PM](https://github.com/brave/brave-browser/assets/17885425/1e111449-7358-47a1-b524-2b6f33cfde66) | ![Screenshot 2024-07-02 at 12 33 54 PM](https://github.com/brave/brave-browser/assets/17885425/f4c22c40-9185-43f9-9558-f79377172aa5) | ![Screenshot 2024-07-02 at 12 34 06 PM](https://github.com/brave/brave-browser/assets/17885425/bca735de-e54e-4500-9910-4030f27e23ef) | ![Screenshot 2024-07-03 at 11 03 05 AM](https://github.com/brave/brave-browser/assets/17885425/55bb3a54-8052-4044-8e82-dcdc69209a1d)

</details>

**Case: Linking Receipts**

<details>

- Ensured linking to staging site (account.bravesoftware.com) is successful for Leo and VPN. 

Example | Example | Example
-|-|-
![Screenshot 2024-07-02 at 2 47 27 PM](https://github.com/brave/brave-browser/assets/17885425/8b0275d0-c48d-4a25-930b-074c2a1a32b7) | ![Screenshot 2024-07-02 at 2 48 23 PM](https://github.com/brave/brave-browser/assets/17885425/4a0c143d-c71c-4e36-a694-77604cc147b9) | ![Screenshot 2024-07-02 at 6 30 50 PM](https://github.com/brave/brave-browser/assets/17885425/f9b69ca4-3800-4aa0-8190-c755d28f5a9d)

</details>

**Case: Restore Credentials on Android (Purchased on Desktop)**

<details>

- Ensured loading credentials enables premium for Leo on Android using desktop account. 
- Ensured that expiration value in the SKU State matches the original order. 

Example | Example | Example | Example
-|-|-|-
![Screenshot 2024-07-02 at 3 41 34 PM](https://github.com/brave/brave-browser/assets/17885425/db32c5df-0e0d-496c-8a04-99a2197dce40) | ![Screenshot 2024-07-02 at 3 43 01 PM](https://github.com/brave/brave-browser/assets/17885425/7073f668-99f0-4658-84cc-e9bda98777f0) | ![Screenshot 2024-07-02 at 3 43 11 PM](https://github.com/brave/brave-browser/assets/17885425/93c5e3cd-75da-4c13-b7e3-5d9574f80ef5) | ![Screenshot 2024-07-02 at 5 01 33 PM](https://github.com/brave/brave-browser/assets/17885425/22c197dc-4b72-4eb0-a01b-2913c0fc6c29)

</details>

**Case: Restore Credentials on Android (Purchased on Android)**

<details>

- Ensured loading credentials for Leo and VPN is successful from account site (account.bravesoftware.com)
- Ensured that `expires_at` value in SKU State matches the original purchase receipt under `brave://skus-internals`

Example | Example | Example | Example | Example
-|-|-|-|-
![Screenshot 2024-07-02 at 6 44 11 PM](https://github.com/brave/brave-browser/assets/17885425/f7a7d900-65f7-4853-95b8-720c94dd26bd) | ![Screenshot 2024-07-02 at 6 44 24 PM](https://github.com/brave/brave-browser/assets/17885425/0ae4d980-96f7-4d4f-9657-fcf0a1405fa8) | ![Screenshot 2024-07-02 at 6 44 34 PM](https://github.com/brave/brave-browser/assets/17885425/08f8b945-e77a-4f71-abf0-7aaf06c00a75) | ![Screenshot 2024-07-02 at 6 44 40 PM](https://github.com/brave/brave-browser/assets/17885425/f15cbd98-9efc-466a-8af1-4258ac70e94a) | ![Screenshot 2024-07-02 at 6 45 11 PM](https://github.com/brave/brave-browser/assets/17885425/2261aaaa-f562-4db3-a9c0-7dc77f7eace5) 

Device A | Device B
-|-
![Screenshot 2024-07-02 at 6 34 41 PM](https://github.com/brave/brave-browser/assets/17885425/d2fb590a-86bb-44af-93e8-c508438f828f) | ![Screenshot 2024-07-03 at 11 35 16 AM](https://github.com/brave/brave-browser/assets/17885425/042b87e2-ac49-4524-bab7-a9127a6e7e1e)

</details>

**Case: Restore Credentials on iOS (Purchased on Android)**

<details>

- Ensured loading credentials for Leo purchased on Android from staging account site (account.bravesoftware.com)
- Ensured that `expires_at` value in SKU State matches the original purchase receipt under `brave://skus-internals`

Example | Example | Example | Example
-|-|-|-
![IMG_6624](https://github.com/brave/brave-browser/assets/17885425/9e6ed618-c63d-4305-9381-76cbd3ed7640) | ![IMG_6625](https://github.com/brave/brave-browser/assets/17885425/4b8201d7-21c8-4643-8ce3-ba41f4dcba5f) | ![IMG_6626](https://github.com/brave/brave-browser/assets/17885425/ec1c7fd6-1d67-4484-9f63-66eab3a8446b) | ![IMG_6627](https://github.com/brave/brave-browser/assets/17885425/116b7015-1af3-4d97-b56b-ecd0c8c8c0cf)

</details>

**Case: Verify VPN & Leo credentials work as expected after upgrade**

<details>

In progress

</details>

**Case: Max limit # of actively-linked/recovered devices**

<details>

In progress

</details>

**Case: Auto-renew (within 5 days of exp.), 1.68.x**

<details>

In progress

</details>

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.68.109`

**Preconditions:**

Enable debug menu and set 3 custom switches in `BraveCore Switches` to enable staging environment.
```
--env-leo=staging
--env-ai-chat.bsg=dev
--env-ai-chat-premium.bsg=dev

```
<img width="300" alt="debug_menu" src="https://github.com/brave/brave-browser/assets/17885425/7a3b6940-38ed-4df2-98e2-b12dec48f039">


**Case: Loading Credentials:** 

- Ensured that credentials are loaded for VPN and Leo from account site in staging. 
- Ensured that Leo premium status is enabled in UI.
- Ensured SKU state shows expiration in `brave://skus-internals`.
- 

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_6646](https://github.com/brave/brave-browser/assets/17885425/f5752f04-bdc2-453d-a250-218de08c004f) | ![IMG_6647](https://github.com/brave/brave-browser/assets/17885425/30172ba5-2f51-4788-af8e-7951e21e8a73) | ![IMG_6648](https://github.com/brave/brave-browser/assets/17885425/43092eaf-aa40-4f63-a371-d704f2a24120) | ![IMG_6649](https://github.com/brave/brave-browser/assets/17885425/ad5c5be1-e33c-48bc-8a0c-1822037bb0eb) | ![IMG_6650](https://github.com/brave/brave-browser/assets/17885425/71109c6d-78bb-48f4-b64d-afd11989399d)

**Case: Verify VPN & Leo credentials work as expected after upgrade**

- Ensured that VPN and Leo credentials work after upgrading app.

Example | Example | Example
-|-|-
![IMG_6655](https://github.com/brave/brave-browser/assets/17885425/db498fb5-22a8-4d0a-80dd-9b333fafde42) | ![IMG_6656](https://github.com/brave/brave-browser/assets/17885425/33dcb4ef-ae1e-40f6-a1ee-42d32a7a69f8) | ![IMG_6651](https://github.com/brave/brave-browser/assets/17885425/17e8c3f9-47de-4b32-b565-5f35cf4863f6)

**Case: Max limit # of actively-linked/recovered devices**

- Ensured error is shown when reaching the limit for actively linked/recovered devices.

Example | Example
-|-
![IMG_6639 3](https://github.com/brave/brave-browser/assets/17885425/6c4c086e-93ab-4b1c-a4f1-10491145ad62) | ![IMG_6640 3](https://github.com/brave/brave-browser/assets/17885425/74f135f8-6172-4c87-84ac-7cb58b5193d6)

**Comment by kjozwiak** [comment]
@mattmcalister believe the above work as been completed and has been shipped/pushed into `production`. Can we close this one off? Or is there still some pending QA that needs to be completed?
