### ISSUE TITLE
Manual test run for `1.66.2 HF` on `iPhone` running `iOS 17`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#39148]
## Installer

- [x] Check that installer is close to the size of the last release
- [x] Check the Brave version in About and make sure it is EXACTLY as expected

## Data

- [x] Verify that data from the previous build appears in the updated build as expected (bookmarks, history, etc.)
- [x] Verify that cookies from the previous build are preserved after upgrade
- [x] Verify saved passwords are retained after upgrade
- [x] Verify stats are retained after upgrade
- [x] Verify sync chain created in the previous version is still retained on upgrade
- [x] Verify per-site settings are preserved after upgrade

## Brave Rewards/Ads

- [x] Verify wallet is auto-created after enabling Rewards
- [x] Verify when you click on the Brave Rewards panel while on a site, the panel displays if the site is verified or not
- [x] Verify ads are only shown while the app is being used
- [x] Verify tapping on an ad notification shows the landing page
- [x] Verify inline-content ads show on Brave News and are correctly redeemed from the server
- [x] Verify `view`, `clicked`, `landed` and `dismiss` confirmation states are logged based on the action. Ensure these are working for inline ads, ad notifications and New Tab Page ads.

## Playlist & Autoplay

- [x] Verify Playlist is enabled by default on a clean install
- [x] Verify when a site with audio/video is detected, `Playlist` button is shown in URL bar and a notification badge on the menu
- [x] Verify clicking the `Playlist` button adds audio/video to playlist and initiates offline play
- [x] Verify adding audio/video to playlist via share menu works as expected
- [x] Verify adding audio/video to playlist via long press context menu works as expected
- [x] Verify Autoplay is enabled by default
- [x] Verify with Autoplay enabled, able to play audio/video automatically
- [x] Verify with background audio enabled, able to play audio/video with device locked or app in background
- [x] Verify Playlist media works with CarPlay on iOS devices
- [x] Verify playback gestures are working in Playlist
- [x] Verify adding shared folder to playlist using `https://playlist.brave.com/bsa-sample` works. Verify all actions on shared folder are working

## App linker

- [x] Long-press on a link in the Twitter app to get the share picker, choose Brave. Verify Brave doesn't crash after opening the link

## Session storage

- [x] Verify that tabs restore when closed, including active tab

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.66.2 (124)`

<img width="300" alt="0" src="https://github.com/brave/brave-browser/assets/17885425/47819292-47ae-454c-92b0-c00a45ce5f5a">
