### ISSUE TITLE
Disable In product help (iph) bubbles

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#39143]
### Description

in product help bubbles started showing since CR 126 implementation.  There might be others. 
1. Control the media you're casting
2. Manage passwords

### Steps to reproduce

1. install 1.67.116
2. launch Brave
3. visit youtube.com and play a video
4. click media/control music icon

### Actual result

`Control the media you are casting` bubble |To view your password or add a note about it, click the key icon bubble
---------------------------------- | -----------------------------------
![image](https://github.com/brave/brave-browser/assets/98358127/7187dde4-6a11-4bb2-a095-f208cf2f0014)|![image](https://github.com/brave/brave-browser/assets/98358127/11e6ae21-8379-4f4c-8278-1d097ae8e1ce)

### Expected result

Disable?

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.67.116 Chromium: 126.0.6478.71 (Official Build) (64-bit)
-- | --
Revision | f4237fe448716e50cca6e827ff87ffd701c7d0c7
OS | Windows 11 Version 23H2 (Build 22631.3737)
```

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

@rebron

**Comment by aguscruiz** [comment]
We just wanto disable them alltogether?

**Comment by rebron** [comment]
@aguscruiz We need to style these. Some of the IPH bubbles are good to keep.

**Comment by aguscruiz** [comment]
Gotcha, ok, added the design to Figma
https://www.figma.com/design/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?node-id=1386-11575&t=BcSaR8UPXXNQ5so6-1

<img width="339" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/d96b1925-66ff-4e67-a93b-b5e408e2f50d">

**Comment by mkarolin** [comment]
Per the latest discussion with @rebron, we want to turn off IPH altogether.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` 
```
Brave | 1.75.161 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | 7e59e37e24ad33062e0f20e842236aa03f579407
OS | Windows 11 Version 24H2 (Build 26100.2894)
```

Reproduced the issue in 1.67.116

![Image](https://github.com/user-attachments/assets/857f369a-fbac-4229-9e1c-6ba874fd9b88)

1. Installed 1.75.161
2. opened nytimes.com in a new tab
3. logged into the site and clicked `Save` in the Save the password? dialog
4. opened youtube.com and played media

#### Confirmed In-product help (iph) bubbles are not shown

https://github.com/user-attachments/assets/351e024b-8c17-4f68-9ed1-083098d4536d
