### ISSUE TITLE
Add the favicons for split view on the left side of omnibox

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#39151]
Subtask of https://github.com/brave/brave-browser/issues/39027

<img width="463" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/8fff391d-a269-46e7-b609-c605de146d78">

**Comment by ajayseeker** [comment]
Hi @sangwoo108 
Can I work on this?
I'll probably need some help in understanding the task, unable to access figma docs in the parent issue.

**Comment by sangwoo108** [comment]
Sorry @ajayseeker . I was already working on this.

**Comment by ajayseeker** [comment]
sure! NP!

> Sorry @ajayseeker . I was already working on this.

sure. NP!
Will look out for other issues.

**Comment by thypon** [comment]
The icons on the URL bar might used to spoof other browser features (e.g. rewards/brave shields).
Do we want to proceed with this?

**Comment by diracdeltas** [comment]
> The icons on the URL bar might used to spoof other browser features (e.g. rewards/brave shields).
> Do we want to proceed with this?

I would rather skip it. It would also conflict with the stuff @aguscruiz is now prototyping for shields on the left.

**Comment by rebron** [comment]
Closing as wontfix
