### ISSUE TITLE
Fixup File I/O on the UI thread

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#39169]
### Description

For calls to `FileManager` please wrap that in calls to `Task.detached` or `backgroundTaskQueue.async`
https://github.com/search?q=repo%3Abrave%2Fbrave-core%20FileManager.default.removeItem&type=code
But not just removals, anything that would lead to an IO operation, for example even file existence checks.

If possible, it would probably be best to wrap `FileManager` in something else that does the equivalent of a `DCHECK` if it runs on the main thread

Note that some calls are already off the main thread, but most likely some calls are not and should be audited.

We should also semgrep checks to flag any calls (FileManager, known slow ios api calls, etc…) to manually check in code review.

### Steps to reproduce

n/a

### Actual result

Can lead to ANRs, app hangs, and perf problems

### Expected result

no intermittent hangs

### Reproduces how often

Intermittent issue

### Brave version

n/a

### Device/iOS version

n/a

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [X] with Brave Shields disabled
- [X] in the latest version of mobile Safari

**Comment by kylehickinson** [comment]
Editing the title to avoid only pointing out `FileManager` as a majority of those APIs are low risk to use, and there are other methods of file I/O that are considered higher risk: 

- `FileManager.createFile(atPath:contents:)`
- `FileManager.copyItem(atPath:toPath:)` (APFS may make this instant)
- `FileManager.contents(atPath:)`
- `Data.write(to:options:)` / `Data.write(to:)`
- `Data.init(contentsOf:options:)`
- `String.init(contentsOf:)` / `String.init(contentsOf:encoding)` / `String.init(contentsOf:usedEncoding:)`
- `String.init(contentsOfFile:)`

**Comment by Uni-verse** [comment]
In progress on `iPhone 12` running `iOS 17.5.1` using version `1.69 (162)`

#### Test Plan:

Favourites Widgets (Home & Lock Screen)
Leo: Code block highlighting, Receipt validation
Shields: Block all Cookies
Web Downloads (Download prompts, Viewing a PDF inline and saving from share sheet)
Favicons: Caching, Fetching, Bundled/Custom icons
Interstitial pages (error pages, IPFS, session restore, web3, etc.)
OpenSearch parsing / Search Engines list
Reader Mode
Rewards Internals sharing
Adblock (Engine building, caches, custom filter lists)
Brave News: Caches, RSS OPML parsing
Brave VPN: Receipt validation, contact form
Passbook passes
Create PDF action
Playlist: Content sizes, delete item/folder, downloading
Onboarding: Blocking summary list (popup stating you blocked content from Google, Amazon, etc.)
