### ISSUE TITLE
update text in brave://settings/shields and search text

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#39164]
### Description

"This will block most ads on websites, not Brave Private Ads" should be reworded to something like "This will block most ads on websites, not Brave Rewards Ads" or just remove this entire sentence (which only shows up for rewards users)

Also text about Brave Search needs to be updated to address the fact that the search page shows ads

### Steps to reproduce

n/a

### Actual result

n/a

### Expected result

n/a

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

n/a

### Android device

- Brand/model: 
- Android version: 

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.69.73 Chromium: 127.0.6533.26 (Official Build) nightly (64-bit)
-- | --
Revision | ebfe046ab1178f2195d83704420ed1ffa0370804
OS | Windows 10 Version 22H2 (Build 19045.4598)
```

example | example
----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/ce447abb-74bb-4b17-b736-43e4ff608a05) | ![image](https://github.com/brave/brave-browser/assets/387249/4f9cf359-f387-4155-b0a3-b87f27ebf0ba)

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP31.240617.010 release-keys
Brave build: 1.69.131
Chromium: 127.0.6533.88 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Make sure the device language is set to either `US`, `CA`, `DE`, `FR`, `UK`, `AT`, `ES` or `MX`
2. Launch Brave
3. Change `SE` from `Brave` to any other one, for example, `Google`
4. Go to `Dev options` and add `--enable-features=BraveSearchOmniboxBanner` > Relaunch `Brave`
5. Tap in the `URL search bar` > Type some query > *Verify*

**ACTUAL RESULTS:**
- Verified that the new string says `Brave Search doesn't profile you.` when `Brave` is not set as `default` `SE`
- Verified that Brave search promo doesn't appear in `Private` tab when `Brave` is not set as `default` `SE`

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/18ba96f8-6933-4798-a5a2-6907d4ce9acf) | ![2](https://github.com/user-attachments/assets/ff726c60-5e44-4b35-8ba2-981ae4477a93) | ![3](https://github.com/user-attachments/assets/6ab954f4-8269-48bf-9424-c0944124fe02) |

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.69 (156)`

- Ensured that Brave Search banner contains the text `Brave Search doesn't profile you.`
- Ensured that tapping `Maybe Later` on the banner and relaunching browser will show it again. 
- Ensured that user is able to finally dismiss the Search Banner by tapping `Dismiss`.

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_7178](https://github.com/user-attachments/assets/f4a0c393-9bd1-4559-9ebf-aa771f83e445) | ![IMG_7175](https://github.com/user-attachments/assets/870f6ec4-9a5f-4111-9965-03dac6558f0e) | ![IMG_7176](https://github.com/user-attachments/assets/ed6ff69e-42d8-4983-ac20-5f5d6ba09710) | ![IMG_7177](https://github.com/user-attachments/assets/88928ee6-afbf-48e9-8797-e390c6485831) | ![IMG_7178](https://github.com/user-attachments/assets/bdf8694c-f6c4-43d4-8993-5dd13a2a87b4)
