### ISSUE TITLE
Add a switch for IPFS companion extension

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#3918]
Add a pref to control IPFS companion extension installation, which will be off by default.

**Comment by rebron** [comment]
cc: @Brave-Matt We're going to need an article to explain this switch and IPFS in general.

**Comment by bsclifton** [comment]
Updated top post to link to test plan 😄 
cc: @yrliou

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.63.45 Chromium: 74.0.3729.75 (Official Build) beta (64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Windows 10 OS Build 17134.523

Used test plan from https://github.com/brave/brave-core/pull/2106
Also verified that user cannot install ipfs extension from Google webstore when ipfs is already installed through the toggle 

Logged https://github.com/brave/brave-browser/issues/4211 and https://github.com/brave/brave-browser/issues/4212
Encountered while testing https://github.com/brave/brave-browser/issues/3950
