### ISSUE TITLE
Leo - Update input box to match design tweaks

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#39191]
### Description
Design
https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/%F0%9F%94%84-Leo-%5BIN-PROGRESS%5D?node-id=4604-42375&t=c1iZjyqK3fxbV2Kn-1

- [ ] Input area looks "attached" to the keyboard, there's no padding between the input and the borders. Top borders are rounded off
- [ ] Changed the icon size for the items in the input box to be 24x24px. 
- [ ] Font size uses the `large` style now
- [ ] Added 8px padding between the text input and the icons.
- [ ] Bottom padding of the icon area is 16px.
- [ ] Spacing between icons is 16px
- [ ] The initial send button should be a microphone to allow you to talk, if the user starts typing it changes to the send button. 
- [ ] The microphone icon is removed from besides the slash tools

###Send button detail
- [ ] When there isn't a prompt, the icon shows as disabled.
- [ ] When a prompt is entered, the icon changes to `send-filled` and changes color to `icon-interactive`

### Expected result
![image](https://github.com/brave/brave-browser/assets/15734630/ba0a22c5-469c-4ff7-b889-4b04ae35ecea)
------------------
![image](https://github.com/brave/brave-browser/assets/15734630/1bcd541a-2fba-473a-8f01-fffdb9d6df91)

**Comment by Xisrr1** [comment]
Unrelated, but what keyboard is that?

**Comment by aguscruiz** [comment]
Just regular GBoard 👀

**Comment by Xisrr1** [comment]
> Just regular GBoard 👀

Mine looks different, maybe because it's not a Pixel.

**Comment by aguscruiz** [comment]
Issue no longer relevant with new design
