### ISSUE TITLE
Linux command line help needs updating for brave specific details 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#392]
## Description 
Linux command line help needs updating for brave specific details 
## Test plan / Steps to Reproduce
   1. Install packaged build
   2. Type `brave-browser --help` in terminal  
   3. See help section details which needs rebranding 

 ## Actual result:
![image](https://user-images.githubusercontent.com/17010094/41718195-4a485886-752a-11e8-8a2b-b12fdbb64e11.png)

## Expected result:
Should be branded for Brave Software

## Brave version (about:brave info)

Packaged build

## Additional Information
#212 
cc: @bbondy

**Comment by bbondy** [comment]
nice find

**Comment by srirambv** [comment]
This needs a check on mac as well for command line launch. Didn't see anything like this for Windows.

**Comment by bsclifton** [comment]
+1 from https://github.com/brave/brave-browser/issues/3757

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.62.32 Chromium: 73.0.3683.75 (Official Build) beta (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/54773617-53ab3f00-4be0-11e9-99c5-bf886c99ee5f.png)

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/54773661-66257880-4be0-11e9-8e85-e6543dc4edc5.png)
