### ISSUE TITLE
Unable to remove/reassign Default Brave Keyboard Shortcuts

### ISSUE THREAD

**Issue by piercecohen1** [brave/brave-browser#39206]
### Description

I want to remove or reassign any of the default Brave shortcuts in `brave://settings/system/shortcuts`.

For example, the default keyboard shortcut for "Quick commands" is ⌃ + space. I want to remove this keyboard shortcut because it overrides another one on my Mac.

I am able to add an additional shortcut to trigger "Quick commands", and remove this shortcut by hovering over it and clicking the "minus" icon. But I am not able to delete or replace the default shortcut (⌃ + space).

See the screen recording in "Actual result" section below for a demo of this.

### Steps to reproduce

1. Visit `brave://settings/system/shortcuts`
2. There is no way to remove the default shortcuts, or to replace a default shortcut with a different shortcut (see attached gif)

### Actual result

![Screenshot_003726](https://github.com/brave/brave-browser/assets/19575201/7df92f00-9e85-4da0-a543-d69609c5fcfa)

### Expected result

Hovering over a shortcut key combo should display a minus icon next to the shortcut. Clicking this icon should remove the key combo for that shortcut.

### Reproduces how often

Easily reproduced

## Brave
1.67.119 Chromium: 126.0.6478.114 (Official Build) (arm64) 
## Revision
36e2dbd9e397c3a8a4d54a741ea5a6316eab0203
## OS
macOS Version 14.5 (Build 23F79)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment]
@sangwoo108 @fallaciousreasoning I think it makes sense to use the other shortcut now for Quick commands, or rollback the rollback. 

https://github.com/brave/brave-browser/issues/36777

**Comment by fallaciousreasoning** [comment]
@piercecohen1 yeah, unfortunately shortcuts on MacOS are a bit limited at the moment - the interactions with the Menu bar are quite complicated.

You can probably replace the default shortcut via shortcuts in the system settings if you add a new app specific shortcut for Brave:
https://apple.stackexchange.com/questions/119463/how-to-change-osx-system-default-shortcuts

More helpfully, let's move to Cmd+Shift+P for the command palette. @sangwoo108 do you want to do it, or shall I?

**Comment by cleatherbury** [comment]
This is a major blow to my tilting window management workflow not being able to change these settings... Its kinda pushing me over to Orion.

**Comment by fallaciousreasoning** [comment]
@cleatherbury yeah, it definitely sucks - that said, I think you should still be able to change the defaults in the MacOS system menu (which is a pain). I'd love to fix this but I don't have an OSX device which makes it harder

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.69.117 Chromium: 127.0.6533.57 (Official Build) beta (x86_64)
-- | --
Revision | 7b5104c54992f658db7f6b1e7441021612ba71a3
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.69.117`
2. launched Brave
3. pressed `cmd` + `shift` + `p`
4. confirmed the `:>` prompt opened, with key-command options below
5. pressed `ctrl` + `space`
6. confirmed nothing happened
7. typed `quick commands`
8. confirmed it autocompleted the function, with the correct keyboard shortcuts shown
9. opened `brave://settings/system/shortcuts`
10. scrolled down to `Quick commands`
11. noted the correct shortcut
12. clicked `Add`
13. pressed `command` + `shift` + `z`
14. clicked `Save`
15. confirmed I could invoke `Quick commands` via the above
16. clicked on `-` to remove the above extra-added command/binding


`cmd` + `shift` + `p` | `quick commands` shortcut | example | example | example | example | example
-----|------|--------|------|-------|--------|-------
<img width="1208" alt="Screen Shot 2024-07-18 at 4 25 50 PM" src="https://github.com/user-attachments/assets/da2a58d2-dcac-457f-b5f9-2a8e9dddcf90"> | <img width="1208" alt="Screen Shot 2024-07-18 at 4 31 14 PM" src="https://github.com/user-attachments/assets/970868d6-34df-41a2-bb8c-2dc8d9d695da"> | <img width="1208" alt="Screen Shot 2024-07-18 at 4 32 09 PM" src="https://github.com/user-attachments/assets/f0ade290-4173-4e95-b579-8a4012539cf8"> | <img width="1208" alt="Screen Shot 2024-07-18 at 4 33 17 PM" src="https://github.com/user-attachments/assets/b9dac9be-dba4-4d0a-8b8f-0474297dffa5"> | <img width="1208" alt="Screen Shot 2024-07-18 at 4 33 22 PM" src="https://github.com/user-attachments/assets/f118ff26-a747-4820-99aa-a91028acf2f7"> | <img width="1208" alt="Screen Shot 2024-07-18 at 4 33 29 PM" src="https://github.com/user-attachments/assets/a4c2babc-5866-402b-bc79-8f29c063fa24"> | <img width="1208" alt="Screen Shot 2024-07-18 at 4 33 32 PM" src="https://github.com/user-attachments/assets/a5a13d1a-cb74-403b-a045-78216bff1ece">

**Comment by yangmillstheory** [comment]
Is there a reason this bug has been closed? https://github.com/brave/brave-browser/issues/39206#issuecomment-2185318336 is a lengthy workaround, but AFAICT the original feature request still hasn't been addressed.

**Comment by idea-list** [comment]
I'm not sure why this has been closed but I found a newer open issue for this FR: https://github.com/brave/brave-browser/issues/40805

**Comment by astr0gator** [comment]
Guys, could you please fix that?
Ppl confirmed that it worked for 
1.70.119 Chromium: 129.0.6668.70 (Official Build) (64-bit)

But apparently it doesn't work for 
Version 1.71.121 Chromium: 130.0.6723.91 (Official Build) (arm64)

Looks like quite common issue now, e.g.
https://www.reddit.com/r/brave_browser/comments/wodxqk/how_do_you_change_the_default_brave_keyboard/

**Comment by realshubhamraut** [comment]
there is no way to delete the default keys assigned in the brave @rebron @brave-browser-releases, please fix the issue in the next update, giving me headaches with my workflow!

![Image](https://github.com/user-attachments/assets/48bdaf9f-df51-4d09-aeb8-fa2213bdb3fa)

**Comment by avishaan** [comment]
This has been very frustrating for me recently

**Comment by Marcin-91** [comment]
For me also. I'm not able to change the default shortcuts... Please fix it. 🤯

**Comment by astr0gator** [comment]
@rebron @fallaciousreasoning 

Guys, can we consider to re-open the issue? 

Looks like the problem does exist.

Related:
https://github.com/brave/brave-browser/issues/43240
https://github.com/brave/brave-browser/issues/40805

**Comment by realshubhamraut** [comment]
> [@rebron](https://github.com/rebron) [@fallaciousreasoning](https://github.com/fallaciousreasoning)
> 
> Guys, can we consider to re-open the issue?
> 
> Looks like the problem does exist.
> 
> Related: [#43240](https://github.com/brave/brave-browser/issues/43240) [#40805](https://github.com/brave/brave-browser/issues/40805)

yes still this isn't fixed for me as well!

**Comment by shiftux** [comment]
same vote here.
tried it on a windows machine and it's working there. so it is actually an open bug IMO
thanks in advance for fixing

**Comment by marklanderny** [comment]
It's a fair expectation for any good user experience that Keyboard shortcuts customarily used on a platform should be followed or user assignable. This situation is really not limited to inconvenience. I'd rather have no default shortcuts and the ability to set my own than be forced to use shortcuts that I can't disable or modify. Can this be achieved with a flagged setting? A forked build maybe?

**Comment by francis-junr** [comment]
+1 someone please reopen this issue, its clearly driving people nuts. You can remove the defaults shortcuts in linux and windows, the problem exists only on mac.

**Comment by karolkt1** [comment]
Yes the error is still present

**Comment by ulysse-lacour** [comment]
Same issue here with macOs

**Comment by bsclifton** [comment]
@karolkt1 @francis-junr @ulysse-lacour @marklanderny and others

Can you please subscribe to https://github.com/brave/brave-browser/issues/43240 for updates? We can use that to track. Thanks!

**Comment by yusufgungor** [comment]
same problem with macOS 

[Brave 1.82.166 (Official Build) (arm64)]
Chromium: 140.0.7339.133

**Comment by wafflexyzz** [comment]
this!

**Comment by realshubhamraut** [comment]
still waiting for this fix!!

**Comment by aparaschiv** [comment]
Wow, 1 and a half year later, and still, a simple issue is being ignored.

**Comment by marceljay** [comment]
There seems to an issue when trying to jump words in the address bar via Option + arrow. It will jump the browser tab. I don't even see that this is related to the shortcuts.

**Comment by 001101** [comment]
Is it possible to do this soon?

**Comment by pszemraj** [comment]
obnoxious that this is being used as a default shortcut

**Comment by fallaciousreasoning** [comment]
@bsrz fixed this in https://github.com/brave/brave-browser/issues/40805, so should be out in 1.95
