### ISSUE TITLE
Update to crlsets connects to storage.googleapis on windows

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#3920]
## Description 
With v.5056 crlsets components downloads resources from storage.googleapis.com. Proxy requests for the resources through redirector.

**Comment by jumde** [comment]
```
NETWORK AUDIT FAIL: http://storage.googleapis.com/update-delta/hfnkpimlhhgieaddgfemjhofmfblmnib/5056/5055/9bcb5f1d3982dec2714603514c06afba60be66683de82367d19a8b8a423bd7d5.crxd
19:48:13  NETWORK AUDIT FAIL: http://storage.googleapis.com/update-delta/hfnkpimlhhgieaddgfemjhofmfblmnib/5056/5055/9bcb5f1d3982dec2714603514c06afba60be66683de82367d19a8b8a423bd7d5.crxd
19:48:13  network-audit failed. import C:\jenkins\workspace\brave-browser-build-pr_pj\network_log.json in chrome://net-internals
```

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.65.97 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2114
![Screen Shot 2019-05-20 at 3 26 25 PM](https://user-images.githubusercontent.com/28145373/58046585-bef78b80-7b13-11e9-95db-1279e9c79ff0.png)
