### ISSUE TITLE
[Wallet/iOS]: Wrong Solana Estimated Tx Fee

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#39201]
### Description

Some math mistakes on calculating priority fee on front-end after core updates are merged. 
in `TransactionConfirmationStore.swift` and `TransactionDetailsStore.swift`

### Steps to reproduce

1. Open wallet
2. Make a solana send transaction
3. Observe the transaction confirmation screen

### Actual result

Tx esimated fee is significantly larger than the correct value.

### Expected result

Should display correct tx estimated fee value.

### Reproduces how often

Easily reproduced

### Brave version

1.69 nightly after June 10

### Device/iOS version

all iOS version

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.0 Beta running 1.69 (153)
- Verified steps from [brave/brave-core#24309](https://github.com/brave/brave-core/pull/24309)
- Verified correct estimated transaction fee is shown for transactions
  <img width=300 src=https://github.com/user-attachments/assets/405d6289-d0cc-43f9-aa2b-6b75ecb365e0>
