### ISSUE TITLE
Firefox local translate feature on Brave

### ISSUE THREAD

**Issue by AtFreezingPoint** [brave/brave-browser#39210]
### Platforms

all

### Description

Firefox in the recent-ish updates got a new handy on-browser translation feature that sends absolutely nothing to any servers, the current Brave translation in my opinion sucks and should be changed to a fork of the engine from Firefox. 
[Link (not source)](https://support.mozilla.org/en-US/kb/website-translation)

**Comment by rebron** [comment]
Firefox supports 17 languages. Brave translate supports 108 languages. 
https://support.brave.com/hc/en-us/articles/8963107404813-How-do-I-use-Brave-Translate

We evaluated the Firefox models before and the translation quality wasn't there. 

We'll do a re-evaluation and open up a new issue if we move forward with integrating with their local models or if we go with a different solution.
