### ISSUE TITLE
Update Lottie

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#39215]
### Description

Our Lottie library is majorly out of date and we might want to use dotLottie files in the future. Hence we will upgrade

### Testing

1. Check Shred animation works
2. Check playlist confetti animation works
3. Check Onboarding Animations work

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.69 (149)`

- Ensured that Shred animation is working after enabling `#Brave-shred` in `brave://flags`
- Ensured that onboarding animations are working.
- Ensured that Playlist confetti animation works when completing the onboarding tutorial on YouTube.

Example | Example
-|-
![IMG_7075](https://github.com/user-attachments/assets/19b99bd4-f26a-47b5-ac19-e62d1de81bdc) | ![IMG_7076](https://github.com/user-attachments/assets/a00fe97d-859f-453c-9d5e-5d14bf9baa1c)
