### ISSUE TITLE
Handle kUseMoveNotCopyInMergeTreeUpdate & kPdfOcr feature flag

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#39211]
We currently disable it through https://github.com/brave/brave-core/commit/10b7b1180ebcf081072fd3e766ea7dd3150e6b7b in chromium upgrade.

If the order of `AccessibilityEventReceived`=>`SendAccessibilityEventsToManager` won't go away and feature flag is removed in the future, we need to come up with another way to deal with it.
Otherwise, when we receive the ax event and we won't be able to see change reflected to ax tree right away.

**Comment by darkdh** [comment]
Merging https://source.chromium.org/chromium/chromium/src/+/168a309460d97b3aefdd5df028b33a211e8de04f from cr129 into this issue.

**Comment by mkarolin** [comment]
Added `QA/No` as this was merged as a part of https://github.com/brave/brave-browser/issues/40204.

@darkdh if there are particular things you'd like QA to check, please add them to the cr129 issue.
cc: @kjozwiak @LaurenWags
