### ISSUE TITLE
Ad categories should be calculated based upon segment name and top level of segment name

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#3922]
Ad categories should be calculated based upon Segment name and top level of Segment name:

i.e.

```
"segments": [
  {
    "code": "b6O0KdkEyr",
    "name": "Sports"
  },
  {
    "code": "q5qPgp5KncWi",
    "name": "Technology & Computing-Unix",
  }
```

Sports
Technology & Computing
Technology & Computing-Unix

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.4 x64` using the following build:

Brave | 0.63.44 Chromium: 74.0.3729.75 (Official Build) beta(64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Mac OS X

* Went through the test plan outlined under https://github.com/brave/brave-core/pull/2111
