### ISSUE TITLE
Implement process hardening for the Brave VPN services

### ISSUE THREAD

**Issue by thypon** [brave/brave-browser#39230]
### Test Plan
1. Install a version of Brave with this fix. Make sure escalation to admin happens (UAC prompt).
2. Verify the `Escalation Service` for this channel is installed in `services.msc`
3. Visit account.brave.com and login to an account with Brave VPN or buy Brave VPN
4. Verify `Use WireGuard protocol in Brave VPN` is enabled on brave://settings/system
5. Pick a VPN server and verify you can connect. Use https://whatismyipaddress.com/ to verify your location changed
6. Disconnect from VPN
7. Disable `Use WireGuard protocol in Brave VPN` on brave://settings/system
8. Pick a VPN server and verify you can connect. Use https://whatismyipaddress.com/ to verify your location changed
9. Visit https://dnsleaktest.com/ and verify there are no leaks (this is what the Brave DNS service fixes)

### Platforms

Windows

### Description

let's implement a [ProcessRedirectionTrustPolicy](https://learn.microsoft.com/en-us/windows/win32/api/winnt/ne-winnt-process_mitigation_policy) inside the Elevation Service.

This feature will allow to harden the `Elevation Service` infrastructure against vertical privilege escalations.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.69.101 Chromium: 127.0.6533.43 (Official Build) nightly (64-bit)
-- | --
Revision | 9073515479afc03ab66a21bb8175263fc56ba1f1
OS | Windows 11 Version 23H2 (Build 22631.3880)
```
