### ISSUE TITLE
Could Roadmap be as accurate as Milestones

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#3923]
In addition I wanted to ask if **Roadmap** can categorized next to **Labels** and **Milestones** on the list of Issues page on Github as well as making the list of issues in it interactive by allowing users to just select a like/thumbs-up (that's all) which in turn would move a desired feature more up as well as give an indication of importance to devops/engineers and others.

I think some of the list issues have had a lot of work already been done even though they're in **Beyond** category so perhaps they could also act a hyperlink to the actual issue.

Regarding those that are in **Beyond**, there's some excellent discussion on what users really want in in the community.brave and it would be good to take some on board.

'Clear private data on shutdown' is pretty much complete and just needs to be released in the Release version now.

Session Windows needs to be changed to Session Tabs, linked with '**Private tabs instead of just private windows**' as I think they're both similar and would probably annoy a few users if it wasn't.

A bit of input into UX of **Restyling bookmarks, history, preferences** - I suspect a whole lot UI rework is going to go into this to make it visually different from Chrome, naturally this is what everybody wants but how can it be more efficient and productive as well?

**Comment by rebron** [comment]
Closing. Thanks for the suggestions.
