### ISSUE TITLE
[Shred] Per-site Automatically Shred setting doesn't follow global setting 

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#39232]
### Description

You can set a site to Automatically Shred via Shields. There is also a global setting for Automatically Shred in Brave Shields & Privacy Settings menu. The site-specific setting should follow the global setting by default, unless the user creates an exception by manually toggling it in Shields.

### Steps to reproduce

1. Enable Shred via brave://flags
2. Open Settings > Shields & Privacy
3. Turn global setting `Automatically Shred` to be `When Site Closed`.
4. Go to a new website that you haven't toggled Shred feature on before i.e. example.com
5. Go to Shields > Advanced Controls > Shred Site's Data and see the `Automatically Shred` setting.

### Actual result

It's set to `Never`.

### Expected result

By default, it should be set to the global setting which in this case would be `When Site Closed`.

### Reproduces how often

Easily reproduced

### Brave version

Latest Nightly: 1.69 (27) on TestFlight

### Device/iOS version

Any

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.69 (144)`

- Ensured that global settings are applied per site and user is able to change Auto Shred setting in Shields panel.
- Ensured that changing Auto Shred setting in Shields will persist after relaunching browser. 
- Ensured changing global settings will not change per site Shred preference. 

Example | Example | Example
-|-|-
![IMG_6976](https://github.com/user-attachments/assets/a5166692-df41-4930-aeb5-204c000ae71a) | ![IMG_6974](https://github.com/user-attachments/assets/087f5e97-ec58-440c-8791-22dedc7c50ab) | ![IMG_6975](https://github.com/user-attachments/assets/4e1c7136-c04b-4079-9130-abb91977fdb1)
