### ISSUE TITLE
Yubikey not working on GitHub

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#3925]
When GitHub displays the security key screen as part of login, my Yubikey doesn't blink, and I can't use it to log in. Yubikey works fine for logging into Google — and seems to use the newer WebAuthn flow on Brave's G Suite.

Version 0.64.23 Chromium: 73.0.3683.75 (Official Build) nightly (64-bit) [MacOS]

**Comment by VMBindraban** [comment]
Yubikey still works in:

Brave | 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Mac OS X

**Comment by jumde** [comment]
@rebron @bsclifton @tomlowenthal - this works for me, tried with the YubiKey 5Ci on `0.72.9 Chromium: 77.0.3865.65 (Official Build) nightly (64-bit)`

**Comment by tomlowenthal** [comment]
@brave/legacy_qa Could you verify this?

**Comment by jumde** [comment]
Verified works on `0.68.139 Chromium: 77.0.3865.90 (Official Build) (64-bit)`. Closing.
