### ISSUE TITLE
Fix long delays when updating filter lists

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#39283]
### Description

When updating filter lists, there may be a long delay before they are ready (over 1 minute)

### Steps to reproduce

1. Go to youtube
2. Enable/disable mobile distractions and youtube recommendations filter lists
3. Go back to the page
4. Reload (you might still need to wait about 5 seconds so don't be too quick)

### Actual result

Changes will take about a minute to go into effect

### Expected result

Changes should be nearly instant (about 5 seconds)

### Reproduces how often

Easily reproduced

### Brave version

1.69

### Device/iOS version

Iphone 14

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6
Brave build: 1.68 (117)
BraveCore: 1.68.117 (127.0.6533.26)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/39283#issue-2367377155 and https://github.com/brave/brave-core/pull/24330#issuecomment-2214593013
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the delay is no longer than ~5 seconds when enabling/disabling filter lists.
- Verified that error in UI is not shown in `CUSTOM FILTERS`.
- Verified that ads are blocked on YT with custom filters enabled.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/becd8d81-23c6-426f-bfcf-57bfb01ba84a) | ![2](https://github.com/user-attachments/assets/a19a5b86-1e74-4ca8-8b10-78535ede61ab) | ![3](https://github.com/user-attachments/assets/572315c5-42c7-4ad1-a9d6-2685263a212c) | ![4](https://github.com/user-attachments/assets/e0e5b993-dd39-40ca-a6a4-1fab893cfdb3) |

https://github.com/user-attachments/assets/e791c50d-5218-40b1-9ded-601d928329c7
