### ISSUE TITLE
[Commands]: Remove/fix show playlist bubble from command palette

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#39295]
Currently, the command crashes if there is no video detected on the page - ideally the command should still be usable but would not crash.

cc @sangwoo108

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.69.106 Chromium: 127.0.6533.43 (Official Build) nightly (x86_64)
-- | --
Revision | 2778b12a30fa8f4d7ccd6caad101a7aabcfc6981
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.69.106`
2. launched Brave
3. opened `brave://flags`
4. toggled `Playlist` to `Enabled`
5. clicked on `Relaunch`
6. opened a new-tab page
7. clicked on `View` -> `Quick Commands`
8. typed `Show playlist bubble`

### Confirmed no crash when executing `Show playlist bubble` on a blank new-tab page

`brave://flags` | `Show playlist bubble` | no crash
---------------|------------------------|---------
<img width="1312" alt="Screen Shot 2024-07-15 at 1 32 24 PM" src="https://github.com/user-attachments/assets/e5cb3e1c-db2a-4a9f-88e0-d6d5bbf931e0"> | <img width="1312" alt="Screen Shot 2024-07-15 at 1 32 13 PM" src="https://github.com/user-attachments/assets/80a3d88e-5dcd-4c7c-993c-aea312577b71"> | <img width="1312" alt="Screen Shot 2024-07-15 at 1 32 16 PM" src="https://github.com/user-attachments/assets/fdcb46d6-5b6e-4c38-932d-c5dc543be05a">
