### ISSUE TITLE
Youtube video in full screen mode sometimes shows a black screen (Wayland, Arch Linux)

### ISSUE THREAD

**Issue by dernikolas** [brave/brave-browser#39290]
### Description

When I open a video in full screen, blackscreens sometimes appear. I use Arch Linux with KDE Plasma and Wayland. On X11 the Problem doesn't appear.

### Steps to reproduce

1. Open a Youtube Video
2. Make it fullscreen

### Actual result

Video plays but blackscreens sometimes appear for a few seconds

### Expected result

Video plays smoothly

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.67.119 Chromium: 126.0.6478.114 (Offizieller Build) (64-Bit) 

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [X] in the latest version of Chrome

**Comment by shubham-cpp** [comment]
@dernikolas, this is a KDE problem not brave browser. 

Summary: On KDE
Goto `System Settings` > `Display & Monitor` > `Adaptive Sync`

Change `Adaptive Sync` to `never`

Source:- [Reddit Post with solution](https://www.reddit.com/r/kde/comments/1ax05uq/display_turns_offblack_when_using_full_screen_in/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

**Comment by dernikolas** [comment]
@shubham-cpp, thank you very very much, now i can use Wayland again.
I close this Issue now.

**Comment by 4wl2d** [comment]
> [@dernikolas](https://github.com/dernikolas), this is a KDE problem not brave browser.
> 
> Summary: On KDE Goto `System Settings` > `Display & Monitor` > `Adaptive Sync`
> 
> Change `Adaptive Sync` to `never`
> 
> Source:- [Reddit Post with solution](https://www.reddit.com/r/kde/comments/1ax05uq/display_turns_offblack_when_using_full_screen_in/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

MAN, YOU ARE A LEGEND!
