### ISSUE TITLE
Switch to Chainstack proxy for Avalanche

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#39299]
### Description

We currently use public RPC endpoint for Avalanche. Use the Chainstack proxy instead.

Ref https://github.com/brave/devops/issues/11914

### Steps to reproduce

N/A

### Actual result

Portfolio balances for Avalanche should load correctly without any console errors. Public RPC is used for making requests.

### Expected result

Portfolio balances for Avalanche should load correctly without any console errors. Chainstack RPC is used for making requests.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.x

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [X] in the latest version of Chrome

### Miscellaneous information

Uplift to 1.68.x

**Comment by kjozwiak** [comment]
The above requires `1.68.101` or higher for `1.68.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.68.101 Chromium: 126.0.6478.126 (Official Build) beta (64-bit)
-- | --
Revision | ffa8411f4c8fe36c0e399f60ef7c24b3cf7d7402
OS | Windows 11 Version 23H2 (Build 22631.3810)

- Verified steps from issue description
- Verified Avalanche tokens balance show up in Portfolio as expected

https://github.com/brave/brave-browser/assets/17010094/e62973b8-7d1d-4929-8e8a-9b90e35e2550
