### ISSUE TITLE
[Profile Picker]: Avatar picker has wrong selected icon

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#39294]
1. Navigate to brave://settings/manageProfile
2. Note that the selected icon is a shield instead of a checkmark

reported by @kleantzogu 

I'd say that its probably a Nala icon issue

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.69.88 Chromium: 127.0.6533.26 (Official Build) nightly (x86_64)
-- | --
Revision | d60303973dc3604d9d348b981322a8a04dcbb86d
OS | macOS Version 13.6.7 (Build 22G720)
```
