### ISSUE TITLE
Consider documenting command-line switches

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#393]
Carried over from https://github.com/brave/browser-laptop/issues/388

There's a fairly exhaustive list available here:
https://peter.sh/experiments/chromium-command-line-switches/

**Comment by bbondy** [comment]
We document our own here: https://github.com/brave/brave-browser/wiki/Custom-Brave-switches but I think this issue is meant for the whole product.

**Comment by dannyob** [comment]
I think this also concerns the ability to open new URLs in a currently running instance of Brave from the command line, which is a common way Unix systems implement opening URLs from other programs.

**Comment by Alf0nso** [comment]
I'm not sure if this is the right place to ask about it, but is there any sort of flag/switch to reload a page in brave? more specifically to reload the last page that was opened?

**Comment by patarapolw** [comment]
Although, `--app=${URL}` does work, `---window-size=%d,%d` and `--start-maximized` don't work (in Arch Linux).

Also, even `--remote-debugging-port=${PORT}` doesn't work.

**Comment by bsclifton** [comment]
Added a link to https://peter.sh/experiments/chromium-command-line-switches/ into https://github.com/brave/brave-browser/wiki/Custom-Brave-switches
