### ISSUE TITLE
Network selector is not shown properly in Visible Account list

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#39304]
### Description

Network selector is not shown properly in Visible Account list reported by @supermassive 

### Steps to reproduce

1. Open portfolio
2. Select visible asset list and select network selector
3. List is not properly shown

### Actual result

![image](https://github.com/brave/brave-browser/assets/17010094/33dce9e2-5932-409d-86be-ccf3c8aa53c1)

### Expected result

<img width="520" alt="image" src="https://github.com/brave/brave-browser/assets/17010094/c18bad52-7c96-462c-986b-9f740e24807a">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.68.92 Chromium: 126.0.6478.71 (Official Build) beta (64-bit)
-- | --
Revision | 393b9968e233540a48f04d74bc4601a05d3a0169
OS | Windows 11 Version 23H2 (Build 22631.3737)

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @Douglashdaniel @supermassive

**Comment by kjozwiak** [comment]
The above requires `1.68.100` or higher for `1.68.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.68.100 Chromium: 126.0.6478.126 (Official Build) beta (64-bit)
-- | --
Revision | 85605a562431451d2710332f66952a4ec6ddfe32
OS | Windows 11 Version 23H2 (Build 22631.3737)

- Verified steps from [brave/brave-core#24347](https://github.com/brave/brave-core/pull/24347)
- Verified network selector is not cut off in portfolio visible asset lists

https://github.com/brave/brave-browser/assets/17010094/e9d227f9-b9df-4ac1-975b-23607c454886
