### ISSUE TITLE
[ads] DayOfWeek tests fail in locales where Sunday is not considered the first day of the week

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#39307]
### Description

https://en.wikipedia.org/wiki/Week#/media/File:First_Day_of_Week_World_Map.svg

```
TEST(BraveAdsCalendarUtilTest, GetDayOfWeekForYearMonthAndDay) {
  // Act & Assert
  EXPECT_EQ(/*friday*/ 6, DayOfWeek(/*year=*/2020, /*month=*/2, /*day=*/29));
}

TEST(BraveAdsCalendarUtilTest, DayOfWeek) {
  // Act & Assert
  EXPECT_EQ(/*wednesday*/ 3, DayOfWeek(TimeFromString("November 18 1970"),
                                       /*is_local=*/true));
}
```

**Comment by tmancey** [comment]
There was no issue with `DayOfWeek` itself. The problem was limited to unit tests and arose because a time floored to midnight was being compared with a time generated by `base::Time::FromString`. During Daylight Saving Time, `base::Time::FromString` returned `23:00:00` for midnight, which caused the discrepancy. The fix has been tested for both Daylight Saving Time and Standard Time for many regions.

**Comment by btlechowski** [comment]
Verified on

Brave | 1.71.105 Chromium: 129.0.6668.89 (Official Build) beta (64-bit)
-- | --
Revision | f69ba167992437799f1dbcce81e90ba501a3d63e
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/25151

#### ads statement after upgrade

<details>

Verified the statement of accounts on brave://rewards are the same after upgrading from a previous profile

1.70.x | 1.71.x
--|--
![image](https://github.com/user-attachments/assets/02cc3d96-c3c4-4b39-8f64-f0317ba49a3b)|![image](https://github.com/user-attachments/assets/6d3acc7f-6b6b-432a-9e29-eece4b155905)


</details>



#### ads statement after serving ads

<details>

Verified that the values are correct after viewing ads

```
[24626:24626:1006/143522.612390:VERBOSE3:inline_content_ad_handler.cc(192)] Served inline content ad impression with placement id 83e285d9-c33f-45a3-bafc-8895b32d19e8 and creative instance id e4958d00-e35c-4134-a408-1fbcf274d5ae
[24626:24626:1006/143529.951667:VERBOSE3:inline_content_ad_handler.cc(199)] Viewed inline content ad impression with placement id 83e285d9-c33f-45a3-bafc-8895b32d19e8 and creative instance id e4958d00-e35c-4134-a408-1fbcf274d5ae
[24626:24626:1006/143529.986130:VERBOSE3:ad_history_database_table_util.cc(33)] Successfully saved ad history
[24626:24626:1006/143530.016165:VERBOSE3:account.cc(180)] Successfully processed deposit for kInlineContentAd with creative instance id e4958d00-e35c-4134-a408-1fbcf274d5ae and kViewedImpression valued at 0.025

```

Verified ad statement is updated after viewing an ad:

![image](https://github.com/user-attachments/assets/6d3acc7f-6b6b-432a-9e29-eece4b155905)|![image](https://github.com/user-attachments/assets/bbb05732-ace3-436b-8173-94e85023af91)
--|--

</details>



#### ads statement after browser restart

<details>

 Verified that the values are correct after browser restart

![image](https://github.com/user-attachments/assets/77bd29d8-446b-43df-9687-4635f327fa21)|![image](https://github.com/user-attachments/assets/210637ed-76ba-40c2-86df-46ae2453ea75)
--|--

</details>
