### ISSUE TITLE
Scrollbar in message for unverified publisher in Rewards Panel

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3930]
## Steps to Reproduce

   1. Enable rewards
   2. Go to `interia.pl`
   3. Open Brave Panel

## Actual result:

![image](https://user-images.githubusercontent.com/34715963/55191094-9309fa80-51a1-11e9-9886-7cf093400497.png)

## Expected result:
![image](https://user-images.githubusercontent.com/34715963/54690564-f8b31280-4b21-11e9-863a-2d565397f063.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.64.24 Chromium: 73.0.3683.75 (Official Build) nightly (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

### Reproducible on current release:
Not reproducible on

Brave | 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Windows 10 OS Build 17134.523

Not reproducible on

Brave | 0.62.45 Chromium: 73.0.3683.86(Official Build) beta (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Windows 10 OS Build 17134.523

Not reproducible on

Brave | 0.63.20 Chromium: 73.0.3683.75(Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

cc @brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
@btlechowski is scroll bar only there or you can actually scroll?

**Comment by btlechowski** [comment]
@NejcZdovc The scroll bar is just there. It is inactive. Cannot scroll.

**Comment by NejcZdovc** [comment]
@ryanml can you please take a look why that is the case

**Comment by ryanml** [comment]
@NejcZdovc Can fix, I'm guessing that the content just exceeds the max height so we get a useless scrollbar.

**Comment by bsclifton** [comment]
I ran into a similar issue in a PR that @petemill had - if you're having trouble reproducing, it may be tied to using a physical mouse (instead of a track pad / magic mouse)

**Comment by petemill** [comment]
This is reproducible in macos on any site if you change your macOS scroll Preferences (under _General_) to 'Show scroll bars: Always`

![image](https://user-images.githubusercontent.com/741836/55199045-c767c180-5175-11e9-9783-491c2f58a319.png)

Fixed with `overflow-y: auto` instead of `overflow-y: scroll`

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

![image](https://user-images.githubusercontent.com/34715963/56629347-0f65f100-661b-11e9-8145-7995cc6663f9.png)

In Polish language:
![image](https://user-images.githubusercontent.com/34715963/56629496-8a2f0c00-661b-11e9-8f04-249d5aeec695.png)
