### ISSUE TITLE
Update OFAC countries based on counsel guidance (2024-06-25)

### ISSUE THREAD

**Issue by mrose17** [brave/brave-browser#39327]
### Description

Add some countries to Category 3 and 4... please see https://github.com/brave/devops/issues/11991 for the list

### Steps to reproduce

N/A

### Actual result

N/A

### Expected result

Additional countries are added to categories 3 and 4

### Reproduces how often

No steps to reproduce

### Desktop Brave version (brave://version info)

This is a new requirement, so applies to the current version.

### Android device

This is a new requirement, so applies to the current version.

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by mrose17** [comment]
Please *do not* merge yet. There may be a few more changes... Sorry!

**Comment by LaurenWags** [comment]
@Miyayes @mrose17 could we get a test plan for this one? I'm not sure which countries were added. Thanks!

**Comment by mrose17** [comment]
I would go to https://github.com/brave/devops/wiki/Region%E2%80%90based-sanctions-blocking to get the list of region categories. It doesn't change too often, but this issue does reflect a change in the list. I will DM you the delta from the last update.

**Comment by LaurenWags** [comment]
@brave/qa-team verification notes can be added under https://github.com/brave/internal/issues/1163.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.69.132 Chromium: 127.0.6533.88 (Official Build) beta (arm64) 
Revision	8b2ea0be418a7e957a25870ec61d676029b756c3
OS	macOS Version 14.6 (Build 23G80)
```

Verification notes can be found under https://github.com/brave/internal/issues/1163#issuecomment-2265465878

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.69.124 Chromium: 127.0.6533.73 (Official Build) beta (64-bit)
-- | --
Revision | dbc9035349f74e493f3293d93f4cbf35c597dfec
OS | Windows 10 Version 22H2 (Build 19045.4651)
```
And

```
Brave | 1.69.131 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 7f9c5cb9840ea18f57d485ee263b5bf4b1075953
OS | Windows 10 Version 22H2 (Build 19045.4651)

```
- Verification notes can be found in the linked issue https://github.com/brave/internal/issues/1163#issuecomment-2252422891

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 AP31.240617.010 release-keys
Brave build: 1.69.131
Chromium: 127.0.6533.88 (Official Build) beta (64-bit) 
```
---------------------------

**ACTUAL RESULTS:**
Verification notes can be found in the linked issue **QA Verification for OFAC update (2024-06-25) [#1163](https://github.com/brave/internal/issues/1163#issuecomment-2269576939)**

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.69.136 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 47255350e0d135b2172cb9dd2ba344d3d7fe4572
OS | Linux
```

Verification notes can be found under https://github.com/brave/internal/issues/1163#issuecomment-2271330463.

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6.1
Brave build: 1.69 (162)
BraveCore: 1.69.162 (128.0.6613.120)
```
---------------------------
Verification notes can be found in the linked issue **QA Verification for OFAC update (2024-06-25) [#1163](https://github.com/brave/internal/issues/1163#issuecomment-2327317175)**
