### ISSUE TITLE
Update clipboard icon

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#39323]
### Description

Use the Brave Nala version of the clipboard icon in the url bar. Current clipboard icon is from Chromium. 

### Steps to reproduce

1. Go to a page that invokes the clipboard access dialog for copy and paste, github for example.
2. Notice clipboard icon in the address bar.

### Actual result

<img width="193" alt="Screenshot 2024-06-24 at 10 43 40 AM" src="https://github.com/brave/brave-browser/assets/5951041/bea80e16-ef40-4bf8-a063-ecfd3764d3b8">
<img width="340" alt="Screenshot 2024-06-24 at 10 44 28 AM" src="https://github.com/brave/brave-browser/assets/5951041/3b91aa19-fc99-4cb9-99a1-17df06b4d55e">

### Expected result

![image_720](https://github.com/brave/brave-browser/assets/5951041/25678ef2-fb73-4938-9496-6fa297639c82)

Should use first icon on the left in Brave Nala library.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.67.x

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by aguscruiz** [comment]
@simonhong the icon to use is the one called `clipboard` in Nala

**Comment by simonhong** [comment]
checking.

**Comment by aguscruiz** [comment]
> checking.

@simonhong there's a pending Nala icon update that may have a slightly different version of the icon, FYI. But the name is the same

**Comment by simonhong** [comment]
> > checking.
> 
> @simonhong there's a pending Nala icon update that may have a slightly different version of the icon, FYI. But the name is the same

Thanks, maybe I'm seeing old one now
<img width="77" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/c3600e44-2ad4-45d5-a538-9d16eab5be13">

btw we also need clipboard off image also like below
<img width="78" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/d7ba495f-4809-4e4b-9841-0cf6825a9762">

**Comment by aguscruiz** [comment]
OK, adding it! You should get it with the next Nala update

**Comment by stephendonner** [comment]
Verified `PASSED` using

```
Brave | 1.69.88 Chromium: 127.0.6533.26 (Official Build) nightly (64-bit)
-- | --
Revision | d60303973dc3604d9d348b981322a8a04dcbb86d
OS | Windows 10 Version 22H2 (Build 19045.4598)
```

`clipboard` allowed | `clipboard` denied
----------------------|---------------------
![image](https://github.com/brave/brave-browser/assets/387249/a23ce465-ebfd-4628-9381-9760843b8f81) | ![image](https://github.com/brave/brave-browser/assets/387249/ab35fc5c-1267-4440-b190-f9f286298b1e)
