### ISSUE TITLE
AI Chat: Use conversation API - follow up to #37575

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#39331]
Follow up from https://github.com/brave/brave-browser/issues/37575 for `iOS`. We disabled the `Leo conversion API` on `iOS` on `1.67.x` as per https://github.com/brave/brave-browser/issues/39330. We'll need to be checked via `1.68.x`.

> Switch current API calls from the "anthropic-style" API to the conversation API. This API allows more structured response and request data in order to support future features such as annotations, search, etc.
> 
> ## Test Plan
> 
> The aim of this issue is not to add any new functionality provided by the conversation API but to switch over existing functions, which should be tested:
> - Simple messages (with and without page context)
> - Rewriting commands
> - Page summarization (text and video)
> - Suggested question retrieval
> When testing, make sure to use the feature param mentioned in https://github.com/brave/brave-core/pull/23067

**Comment by kjozwiak** [comment]
@hffvld @Uni-verse we'll need to wait for https://github.com/brave/brave-core/pull/24297 to get uplifted into `1.68.x` before we can start running through the above.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.68.115`

- Ensured simple messages are working with and without page context.
- Ensured page summarization is working.
- Ensured suggested questions are retrieved for page context.
- Ensured rewriting commands are working with all models for free and premium users. 
- Ensured `improving answer with Brave Search` is shown while query is sent.
- Ensured `Improved answer searching for...` is shown at the end of response.

Page summarize | Simple messages | Slash tools | Brave search integration | Suggested questions
-|-|-|-|-
![IMG_6720](https://github.com/brave/brave-browser/assets/17885425/2f48d57f-e75a-4c65-b16b-bea1efbdd889) | ![IMG_6716](https://github.com/brave/brave-browser/assets/17885425/765861c4-8c7b-4773-b6e5-3e878b4cb0b2) | ![IMG_6727](https://github.com/brave/brave-browser/assets/17885425/5be9dde5-7cec-4ab6-a429-4c312a00a937) | ![IMG_6726](https://github.com/brave/brave-browser/assets/17885425/f7949a96-30c6-42a2-80ad-e9733861501b) | ![IMG_6717](https://github.com/brave/brave-browser/assets/17885425/8b923bdc-d5c0-47d1-b338-82f9fd58d163)

**Comment by Uni-verse** [comment]
In progress on `iPad (7th Gen)` running `iPadOS 17.5.1` using version `1.68.115`
