### ISSUE TITLE
Favicons of brave welcome and rewards page are white in nightly and master on macOS

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#3933]
## Description 
favicon of brave://welcome in nightly channel seems off in dark mode, looks normal in light mode though.
btw I'm using macOS, didn't try other platforms.

## Steps to Reproduce
Install nightly or run a local build based on master and visit brave://welcome
## Actual result:
<img width="680" alt="Screen Shot 2019-03-28 at 4 33 31 PM" src="https://user-images.githubusercontent.com/4730197/55199420-3f82b700-5177-11e9-8e2e-a987cc4f6102.png">

## Expected result:
<img width="497" alt="Screen Shot 2019-03-28 at 4 34 04 PM" src="https://user-images.githubusercontent.com/4730197/55199467-588b6800-5177-11e9-8f64-ed6af9f35e53.png">

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
0.64.23 Chromium: 73.0.3683.75 (Official Build) nightly(64-bit)

### Reproducible on current release:
Not reproducible in current dev channel
(0.63.20 Chromium: 73.0.3683.75 (Official Build) dev(64-bit))

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No.
- Is the issue reproducible on the latest version of Chrome? 
Not applicable.

cc @cezaraugusto @petemill

**Comment by yrliou** [comment]
I just saw the same issue with brave://rewards in our nightly.
<img width="432" alt="Screen Shot 2019-03-28 at 5 40 51 PM" src="https://user-images.githubusercontent.com/4730197/55201555-ba9c9b00-5180-11e9-8aaf-c02b92ffc1f0.png">

**Comment by srirambv** [comment]
Could be macOS issue. Not seeing the white icon on Windows

**Comment by NejcZdovc** [comment]
see the same problem, thought that this was intentional

**Comment by kjozwiak** [comment]
Reproduced on Nightly as well 👍 Pretty easy to reproduce. Used the following build:


Brave | 0.64.23 Chromium: 73.0.3683.75 (Official Build) nightly(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

STR:

* Enable the `Dark` theme via `brave://settings` or under macOS if you're using `Same as MacOS`
* visit about `brave://` website and noticed the incorrect icons being used as @yrliou mentioned above

**Comment by rossmoody** [comment]
Code in here I can't entirely understand but think it might be relevant so passing it along: https://cs.chromium.org/chromium/src/chrome/browser/favicon/favicon_utils.cc?g=0

**Comment by kjozwiak** [comment]
Adding `OS/Linux` as per https://github.com/brave/brave-browser/issues/4535.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.65.113 Chromium: 75.0.3770.38 (Official Build) beta(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2494
![Screen Shot 2019-05-29 at 11 34 54 AM](https://user-images.githubusercontent.com/28145373/58570472-0c57b500-8206-11e9-9eb2-172e9440d99d.png)
![Screen Shot 2019-05-29 at 11 35 10 AM](https://user-images.githubusercontent.com/28145373/58570479-0eba0f00-8206-11e9-88e4-7b0984e6cf9f.png)
