### ISSUE TITLE
Implement new confirmation screen when finishing onboarding

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#39348]
## Description

Implement new confirmation screen that will be shown to the user at the end of onboarding process.

| Light Theme   |     Dark Theme      | 
|:----------:|:-------------:|
| ![Screenshot from 2024-06-25 13-14-49](https://github.com/brave/brave-browser/assets/3308503/57ffd147-cf7c-412c-930d-b1a73c094511)|  ![Screenshot from 2024-06-25 13-14-17](https://github.com/brave/brave-browser/assets/3308503/f59902db-c2c7-4362-8f11-3433c6dab83b) | 

⚠️ **Note:** Once available, replace main illustration with a version containing color reference https://github.com/brave/brave-browser/issues/39423

🎨 Figma design: https://www.figma.com/file/oXIiv45pIhF2RGlpEjOfUg/Wallet-onboarding?node-id=6223%3A70942&mode=dev

☂ Main umbrella issue: https://github.com/brave/brave-browser/issues/35294

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.69.121 x64 Beta build
- Verified steps from [brave/brave-core#24424](https://github.com/brave/brave-core/pull/24424)
- Verified new confirmation screen is shown when finishing onboarding 
- Encountered [#39608 (comment)](https://github.com/brave/brave-browser/issues/39608#issuecomment-2242633159)

Light | Dark
-- | --
<img width="275" alt="image" src="https://github.com/user-attachments/assets/df802085-1b20-4a7f-a580-4aae96352399"> | <img width="275" alt="image" src="https://github.com/user-attachments/assets/cb30558e-80ab-40b9-b99c-d57c82a3cd61">
