### ISSUE TITLE
Leo - Hitting return on the keyboard should do a line break instead of sending message

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#39351]
### Description

When the user hits return on the iOS keyboard, there should be a line break instead of sending the message.
This will be a better user experience to let users craft their prompt in a more organized way.

The button should say "return" instead of "send".

To send a message, you'd have to hit the send button on the input.

### Steps to reproduce

----

### Actual result

----

### Expected result

---

### Reproduces how often

Easily reproduced

### Brave version

---

### Device/iOS version

---

### Affected browser versions

- [X] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.68.112` or higher for `1.68.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6
Brave build: 1.68 (117)
BraveCore: 1.68.117 (127.0.6533.26)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/24462#issue-2386395489 and https://github.com/brave/brave-core/pull/24462#issuecomment-2211497944
2. *Verify*

**ACTUAL RESULTS:**
- Verified that taping on `Return` via the OSK correctly created a new line.
- Verified that taping on the `Send` button via `Leo` submitted the query to `Leo` via the panel.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/9e7389ee-fed4-4a48-a806-c5ed0f164944) | ![2](https://github.com/user-attachments/assets/07ab644d-393d-4268-bbe4-d9e532c797f1) | ![3](https://github.com/user-attachments/assets/6f145a93-af04-4dc5-ab34-62225753c591) |

https://github.com/user-attachments/assets/3ecca34e-b8dc-4d28-87a0-0b6e43976a97
