### ISSUE TITLE
PDF files downloaded twice

### ISSUE THREAD

**Issue by Fulgan** [brave/brave-browser#3935]
## Description 

Links to PDF downloads the PDF twice. If PDf is nt available any more, it is not displayed.

## Steps to Reproduce

   1. Setup a network trace (for instance, with Fiddler)
   2. Attempt to to access a PDF file. Notice that the document is downloaded twice.
   3. If the document is not available from the same link twice, notice that it will not be displayed in Brave.

## Actual result:

![image](https://user-images.githubusercontent.com/3026545/55239058-2ee54600-5236-11e9-8351-4caa816eb3ae.png)

## Reproduces how often: 

Systematic

## Brave version (brave://version info)

0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit) 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Unknown

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? **No**
- Is the issue reproducible on the latest version of Chrome? **No**

**Comment by rebron** [comment]
Closing. Dupe/will be fixed with https://github.com/brave/brave-browser/issues/3846
