### ISSUE TITLE
Good luck

### ISSUE THREAD

**Issue by samsul1212** [brave/brave-browser#3936]
## Steps to Reproduce

   1. 
   2. 
   3. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
Thanks for the good luck! I'm about to get some lottery tickets right now.

**Comment by bbondy** [comment]
Please try shutting down your computer, removing the power plug for at least 120 seconds, and then start it up again. Then you should be good to go!

**Comment by srirambv** [comment]
![wnxLY0R](https://user-images.githubusercontent.com/17010094/55247972-4533d780-521f-11e9-85cf-fc49d2fbfbec.gif)
