### ISSUE TITLE
Side panel open/close animation doesn't work in some condition

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#39376]
### Description

Side panel open/close animation doesn't work when `Show sidebar` option is `Always`
With `On mouseover` or `Never`, we can see panel animation

### Steps to reproduce

1. Set `Always` for `Show sidebar` option
2. Click sidebar toolbar button
3. Check sidebar opens/closes with animation

### Actual result
No animation

https://github.com/brave/brave-browser/assets/6786187/b2d468a7-d113-46c9-a86b-9ce939ad23ab

### Expected result
With animation

https://github.com/brave/brave-browser/assets/6786187/f7a25832-9947-429f-9b93-08a52fcd97d0

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

All version.

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information
cc @rebron @brave/qa-team

**Comment by simonhong** [comment]
checking now.

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.69.95 Chromium: 127.0.6533.26 (Official Build) nightly (64-bit)
-- | --
Revision | ef586bb495b8e8353315768cbc905b14079fbf0f
OS | Windows 10 Version 22H2 (Build 19045.4651)
```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave	1.69.128 Chromium: 127.0.6533.73 (Official Build) beta (64-bit) 
Revision	715445841b1da480bcc24c12077a6dc926951996
OS	Linux
```

Reproduced the issue in `1.68.128 Chromium: 127.0.6533.73`
```

### Steps:
1. installed `1.69.128`
2. launched Brave
3. confirmed default setting of `Sidebar` -> `On`
4. clicked on the `Show sidebar`
5. confirmed sidebar was shown (defaulting to `Leo`),  with a sliding animation
6. clicked on `Hide sidebar`
7. confirmed sidebar was hidden, with a sliding animation

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.69.129 Chromium: 127.0.6533.73 (Official Build) beta (x86_64)
-- | --
Revision | 0ab2f25cd017b563fd72d68048f809659a351a04
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:

1. installed `1.69.129`
2. launched Brave
3. confirmed default setting of Sidebar -> On
4. clicked on the Show sidebar
5. confirmed sidebar was shown (defaulting to Leo), with a sliding animation
6. clicked on Hide sidebar
7. confirmed sidebar was hidden, with a sliding animation
8. verified when sidebar was on mouseover mode, sliding animation is shown as expected

![sidebar-open](https://github.com/user-attachments/assets/1a1088be-99b9-4a81-b428-9844f90f4a8a)
