### ISSUE TITLE
Omnibox flickering when clicking download toolbar button

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#39373]
### Description

Omnibox width is is changed whenever clicks download toolbar button.
https://github.com/brave/brave-browser/assets/6786187/8c23a77c-16ba-4bf1-a76f-603a878b37cb

### Steps to reproduce

1. Download anything and click download toolbar button
2. 
3. 

### Actual result

Flickering omnibox

### Expected result

No flickering

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

All curent version

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @qa

**Comment by simonhong** [comment]
checking now.

**Comment by kjozwiak** [comment]
The above requires `1.68.107` or higher for `1.68.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.68.107 Chromium: 127.0.6533.26 (Official Build) beta (x86_64)
-- | --
Revision | 131a9beda9f0aea74f948286e5e8c63153d9f7f8
OS | macOS Version 13.6.7 (Build 22G720)
```
