### ISSUE TITLE
[iOS] - Add a debug menu to toggle all injected scripts

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#39372]
### Platforms

iOS

### Description

- We've been having a lot of scripts injected to help with features (Equivalent of Tab-Helpers)
- Sometimes these scripts can impact performance and need to be disabled
- We need the ability to turn on and off these features/scripts

**Comment by kjozwiak** [comment]
The above requires `1.68.107` or higher for `1.68.x` verification 👍 @srirambv probably a good idea to take a look and see if the `Wallet` related flags are working as well re: being able to disable/enable features. For example, `Ethereum Provider` & `Solana Provider`.

**Comment by Uni-verse** [comment]
Verification in progress on iOS
