### ISSUE TITLE
CR 127 - `Grouped history` hamburger settings menu is inherited from chrome and click on it doesn't open the history in side panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#39377]
### Description

Found while testing https://github.com/brave/brave-browser/issues/38560
`Grouped history` hamburger settings menu is inherited from chrome and click on it doesn't open the history in side panel

### Steps to reproduce

1. Clean profile `1.69.53 CR 127`
2. Click on the hamburger menu 
3. Click on the `History`->`Grouped history`
4. `Grouped history` is inherited from chrome
5. Click on `Grouped history` doesn't open history in the side panel

### Actual result

`Grouped history` hamburger settings menu is inherited from chrome and click on it doesn't open the history in side panel
![image](https://github.com/brave/brave-browser/assets/38657976/20735465-cf30-4e64-9cd5-52c43066a01c)

### Expected result

not sure whether to keep this settings in Brave or not

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.69.53 Chromium: 127.0.6533.17 (Official Build) nightly (64-bit)
-- | --
Revision | bedcc2e74ce45bd641d2946e0d870d68ba08b8e9
OS | Windows 10 Version 22H2 (Build 19045.4529)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @rebron @emerick

**Comment by GeetaSarvadnya** [comment]
Not reproducible on `1.69.49 CR 126`

**Comment by kjozwiak** [comment]
The above requires `1.68.107` or higher for `1.68.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.68.107 Chromium: 127.0.6533.26 (Official Build) beta (64-bit)
-- | --
Revision | 131a9beda9f0aea74f948286e5e8c63153d9f7f8
OS | Windows 10 Version 22H2 (Build 19045.4529)

```
Confirmed that `Grouped history` menu item is hidden from `Hamburger menu->History`
![image](https://github.com/brave/brave-browser/assets/38657976/6ed426fa-9424-40bd-8c5d-4003d3fbd95c)
