### ISSUE TITLE
[CR 127] - cookies site data and site settings icon are changed as part of CR127

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#39380]
### Description

Found while testing https://github.com/brave/brave-browser/issues/38560

cookies site data and site settings icon are changed as part of CR127

### Steps to reproduce

1. `1.69.53 CR127`
2. Open any site
3. Click on the site information
4. cookies site data and site settings icon are changed as part of CR127

### Actual result

cookies site data and site settings icon are changed as part of CR127

CR 127:

![image](https://github.com/brave/brave-browser/assets/38657976/3284f09d-242b-4c1b-9f9b-efac8fb3f7c7)

### Expected result

CR 126
![image](https://github.com/brave/brave-browser/assets/38657976/8a3dfa03-9a0c-4a5b-8c2b-a14184e89322)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.69.53 Chromium: 127.0.6533.17 (Official Build) nightly (64-bit)
-- | --
Revision | bedcc2e74ce45bd641d2946e0d870d68ba08b8e9
OS | Windows 10 Version 22H2 (Build 19045.4529)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @emerick @rebron @brave/qa-team

**Comment by aguscruiz** [comment]
Let's go back to using our version of the icons:

- Cookies and site data: `Cookie`
- Settings: `Settings`
- The right side arrow is `carat-right`
- The launch icon (on the right side of site settings) is `Launch`
- Not sure if it's not ours, but the close icon should be our `Close`

**Comment by aguscruiz** [comment]
Just in case let's check that all our icons there are the Nala versions:

- Close icon should be `close`
- Lock icon should be `lock`
- Cookie icon should be `cookie`
- Settings icon should be `settings`
- Right arrow icon should be `carat-right`
- The launch icon on site settings should be `launch`

**Comment by simonhong** [comment]
checking now

**Comment by kjozwiak** [comment]
The above requires `1.68.119` or higher for `1.68.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.68.121 Chromium: 127.0.6533.43 (Official Build) beta (x86_64)
-- | --
Revision | 04a7c5d6b5e47f700fcc5a4a9c7d10077c8dfc5d
OS | macOS Version 13.6.7 (Build 22G720)
```
