### ISSUE TITLE
Ads should not be scheduled between certain hours on mobile

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#3938]
Ads should not be scheduled between 9 PM and 6 AM local time unless the App is being used actively during those hours, see https://docs.google.com/document/d/1QynlNXswjNfhxGeilooS9TjQsIPkYvgpZH8y9FJdRy4/edit# for further information

**Comment by GeetaSarvadnya** [comment]
@tmancey Is the behavior applicable only for Mobile?

**Comment by tmancey** [comment]
This functionality was only for mobile, however 1.2.0 only shows ads in the foreground so this feature has been removed
