### ISSUE TITLE
CR 127 - redundant sidebar settings added via brave://settings/appearance

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#39382]
### Description

Found while testing https://github.com/brave/brave-browser/issues/38560
CR 127 - Redundant sidebar settings added via brave://settings/appearance

### Steps to reproduce

1. Clean profile `1.69.53 CR 127`
2. Open brave://settings/appearance
3. Redundant sidebar settings added via brave://settings/appearance

### Actual result

Redundant sidebar settings added via brave://settings/appearance
![image](https://github.com/brave/brave-browser/assets/38657976/72960f72-b9c3-46ea-9bf1-fec64c73e14d)

### Expected result

Brave already have sidebar settings added via brave://settings/appearance in `Sidebar` section, so it's better to remove redundant side panel settings

![image](https://github.com/brave/brave-browser/assets/38657976/0d6b216c-5e52-4355-8d86-148f44b89496)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.69.53 Chromium: 127.0.6533.17 (Official Build) nightly (64-bit)
-- | --
Revision | bedcc2e74ce45bd641d2946e0d870d68ba08b8e9
OS | Windows 10 Version 22H2 (Build 19045.4529)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @rebron @emerick

**Comment by kjozwiak** [comment]
The above requires `1.68.107` or higher for `1.68.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.68.107 Chromium: 127.0.6533.26 (Official Build) beta (64-bit)
-- | --
Revision | 131a9beda9f0aea74f948286e5e8c63153d9f7f8
OS | Windows 10 Version 22H2 (Build 19045.4529)
```
Confirmed hat redundant sidebar settings is removed from the `Appearance` section via brave://settings/appearance page
![image](https://github.com/brave/brave-browser/assets/38657976/221c649d-35d0-4da5-bcd4-ef6e83d2b32e)
Confirmed that sidebar settings is displayed as expected under `Sidebar` section via brave://settings/appearance page
![image](https://github.com/brave/brave-browser/assets/38657976/a39a8e11-45d4-4153-8c22-e51d29cebfbf)
