### ISSUE TITLE
[iOS] - Throttle Playlist Script

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#39398]
### Platforms

iOS

### Description

- The playlist script should be throttled to only execute at the end of page load "complete" and should only send data to the native code throttled so it doesn't spam (Currently it sends 7 requests on a Youtube page. Mostly for search.mp3 and one for video.src).

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` & `iPad (7th Gen)` running `iOS 17.5.1` using version `1.69 (149)`

**Test Case: New Install**

1. Downloaded and installed `1.69.149`
2. Navigated to `https://www.youtube.com` and enter a search term to display some results
3. Ensured that Playlist icon is displayed in the URL bar.
4. Ensured that Playlist icon is shown for YouTube Shorts.
5. Ensured that Playlist icon is shown on other media sites such as `https://www.x.com`, `https://www.dailymotion.com` and `https://rumble.com`
6. Ensured that Playlist onboarding tutorial is shown and user is able to complete the flow.

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_7049](https://github.com/user-attachments/assets/0bfecf2d-a185-47b2-98aa-e5b6cdd55484) | ![IMG_7050](https://github.com/user-attachments/assets/381767d8-9e2d-4608-b86e-b4e4316e73c3) | ![IMG_7051](https://github.com/user-attachments/assets/3fe4f4ad-3feb-419c-9c1a-1d33522245ed) | ![IMG_7052](https://github.com/user-attachments/assets/9fd36f3b-b1c8-4daa-ac4f-e699a683f781) | ![IMG_7053](https://github.com/user-attachments/assets/11b2532a-db82-4510-9966-7e4da05307cc) | ![IMG_7054](https://github.com/user-attachments/assets/357e1bcf-a896-43ad-87d4-b30537ea60e2) 

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_1549 2](https://github.com/user-attachments/assets/57403cc7-7e18-4f5b-88d3-52b3f4ff0d5e) | ![IMG_1550 2](https://github.com/user-attachments/assets/3116ab03-a1bc-4bad-afea-cbada5b3de1e) | ![IMG_1551 2](https://github.com/user-attachments/assets/f98efa74-a12e-4d7c-a19f-88d34b7e7219) | ![IMG_1552 2](https://github.com/user-attachments/assets/fe4a3fa3-c370-46ec-9111-6777727f2406) | ![IMG_1554 2](https://github.com/user-attachments/assets/49904d1a-015e-4fa4-802c-ad1140251d94)

**Test Case: Existing Users**

1. Downloaded and installed `1.68.x`
2. Navigated to `https://www.youtube.com` and added a video to Playlist
3. Upgraded app to `1.69.149`
4. Reloaded YouTube tab, ensured that Playlist icon status is retained for the added video
5. Ensured that Playlist onboarding flow works fine for another YouTube video. 
7. Ensured that Playlist icon is showing up in the URL bar for existing users. 

Example | Example | Example | Example | Example | Example | Example
-|-|-|-|-|-|-
![IMG_1556](https://github.com/user-attachments/assets/23cd155a-1236-440f-ab19-a4dcd564307f) | ![IMG_1557](https://github.com/user-attachments/assets/290f6f36-4606-499c-850d-a87addf3fcfb) | ![IMG_1558](https://github.com/user-attachments/assets/08e5f80f-9bd8-4090-83ad-a15baf47f2cd) | ![IMG_1559](https://github.com/user-attachments/assets/47351142-b35b-4dc5-b688-ed8fa4fd1cc8) | ![IMG_1560](https://github.com/user-attachments/assets/3663d743-5bd0-4909-a69a-11d7e9a20b45) | ![IMG_1561](https://github.com/user-attachments/assets/73129e96-4c24-4161-95eb-eafe5c2c77e6) | ![IMG_1562](https://github.com/user-attachments/assets/57ad1f20-d9bf-4a23-830a-016cd613771c)

1.68.x | 1.69.x | onboarding 1 | onboarding 2 | onboarding 3 | onboarding 4 | onboarding complete
-|-|-|-|-|-|-
![IMG_7068](https://github.com/user-attachments/assets/005dcf96-6550-4f06-afcf-5e3b867ead0e) | ![IMG_7069](https://github.com/user-attachments/assets/5c641faa-ca66-4280-96f2-f71616530aac) | ![IMG_7070](https://github.com/user-attachments/assets/9e72125b-3fd0-4bc1-8056-45161a44add6) | ![IMG_7071](https://github.com/user-attachments/assets/4e58fe17-dd00-4b0a-9aac-db2448711eac) | ![IMG_7072](https://github.com/user-attachments/assets/02e7e039-c34b-45e8-a502-0cc390650cf7)
