### ISSUE TITLE
`Add Person...` should probably read `Add Profile...` in top-level Brave application menu in macOS

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#39405]
### Description

`Add Person...` should probably read `Add Profile...` in top-level Brave application menu in macOS

Found while testing https://github.com/brave/brave-browser/issues/37732

### Steps to reproduce

1. set macOS region to `India`
2. install `1.69.53`
3. launch Brave
4. look at the top-level application menu for `Profiles`
5. click on it
6. look at the resulting text

### Actual result

Reads `Add Person...`

<img width="1250" alt="Screenshot 2024-06-26 at 1 38 39 PM" src="https://github.com/brave/brave-browser/assets/387249/c09c0e0d-e85e-49a3-a3ef-cdd17e91b590">

### Expected result

Should probably read `Add Profile...` to match from https://github.com/brave/brave-browser/issues/37732

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.69.53 Chromium: 127.0.6533.17 (Official Build) nightly (x86_64)
-- | --
Revision | bedcc2e74ce45bd641d2946e0d870d68ba08b8e9
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @brave/qa-team @rebron @jagadeshjai

**Comment by kjozwiak** [comment]
The above requires `1.68.107` or higher for `1.68.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.68.107 Chromium: 127.0.6533.26 (Official Build) beta (x86_64)
-- | --
Revision | 131a9beda9f0aea74f948286e5e8c63153d9f7f8
OS | macOS Version 13.6.7 (Build 22G720)
```
