### ISSUE TITLE
[Wallet] Support Solana Compressed NFTs (cNFTs) in wallet frontend

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39408]
### Description

Add support for displaying and sending Solana compressed NFTs 

### Steps to reproduce

1. Add a compressed NFT to your Solana account (Compressed NFTs can be obtained via https://drip.haus/ or https://drip.tensor.trade/)
3. View portfolio NFTs or "Send" screen

### Actual result

Compressed NFTs are not displayed as owned or available for sending

### Expected result

Compressed NFTs should be displayed as owned and be available for sending

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.67.116 Chromium: 126.0.6478.71 (Official Build) (arm64) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.136 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 47255350e0d135b2172cb9dd2ba344d3d7fe4572
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified Compressed NFTs (cNFT) image is shown correctly  in Portfolio/Send screen

https://github.com/user-attachments/assets/1fe59383-409d-42b2-8432-00ca3c3f65f1
