### ISSUE TITLE
SafeSign not supported for LiFi on Ethereum

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#39413]
### Description

Reported by @StephenHeaps

> Noticing that safer sign doesn’t seem to be used on latest Nightly for EVMs (tested Ethereum Mainnet)
> Tried both ETH -> USDC and vice-versa but neither are going into our safer sign UI for desktop or iOS.

### Steps to reproduce

Perform the following swaps on Ethereum mainnet:
- ETH → token
- token → ETH
- token → token

LiFi is used to fetch quotes, but upon creating a transaction (no need to approve), SafeSign™️ is not triggered.

### Actual result

SafeSign™️ screen is not shown

### Expected result

SafeSign™️ screen is shown

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Version 1.69.45 Chromium: 126.0.6478.114 (Official Build) nightly (arm64)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [X] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.136 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 47255350e0d135b2172cb9dd2ba344d3d7fe4572
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified SafeSign is shown for LiFi transactions for ETH->Token, Token->ETH and Token->Token Swaps

https://github.com/user-attachments/assets/4930d1a6-f2dc-4bbe-a6f0-9fbdf25658eb
