### ISSUE TITLE
Remove shortcut icons and update `Customize` styling on the NTP

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#39421]
### Description

Sub-task of https://github.com/brave/brave-browser/issues/37213

- [ ] Remove the bottom right icons from the NTP: Settings, Bookmarks, History, Talk
- [ ] Style the Customize button text to use Inter
- [ ] Update photo credit text to use Inter instead of Poppins

See: `https://www.figma.com/file/QCBklDojDtDTKApz10XqSQ/%F0%9F%97%82-New-Tab-Page?type=design&node-id=1%3A648&mode=design&t=MkeWs0VdCwTbTGPd-1`

### Steps to reproduce

1. Go to the Brave NTP: brave://newtab
2. See Description

### Actual result

<img width="387" alt="Screenshot 2024-06-27 at 7 17 24 AM" src="https://github.com/brave/brave-browser/assets/5951041/90c394b5-5e15-4080-a157-10573d74dd19">

### Expected result

<img width="809" alt="Screenshot 2024-06-27 at 7 24 47 AM" src="https://github.com/brave/brave-browser/assets/5951041/cce2ecec-b2bc-453c-8a63-81aea69a12f9">
<img width="154" alt="Screenshot 2024-06-27 at 7 24 53 AM" src="https://github.com/brave/brave-browser/assets/5951041/9cc931cf-8a1d-4301-b1fe-3c82b6a33293">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Targeting for 1.68.x

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Related issue: 
https://github.com/brave/brave-browser/issues/37213

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.69.73 Chromium: 127.0.6533.26 (Official Build) nightly (64-bit)
-- | --
Revision | ebfe046ab1178f2195d83704420ed1ffa0370804
OS | Windows 10 Version 22H2 (Build 19045.4598)
```

example | example
----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/aec8a3f2-2c64-46ed-ab1b-a92765a59e96) | 
![image](https://github.com/brave/brave-browser/assets/387249/a4ac2779-e7cc-4f2b-b948-b7539c691365)

**Comment by kjozwiak** [comment]
The above requires `1.68.109` or higher for `1.68.x` verification 👍 Removed the `QA Pass` label as the above will need to be re-checked using `1.68.x`. However, used the verification via https://github.com/brave/brave-browser/issues/39421#issuecomment-2204700950 for the `1.68.x` uplift as per https://github.com/brave/brave-core/pull/24482#pullrequestreview-2156952978.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.68.111 Chromium: 127.0.6533.26 (Official Build) beta (x86_64)
-- | --
Revision | 635ef01f9ccdcb2f2f1006cb9b2c0f261df986bc
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.68.111`
2. launched Brave
3. opened a new-tab page
4. examined and confirmed the removal of all icons except for `Customize`
5. opened `Developer Tools`
6. focused on the `Customize`-containing element
7. located it in the `Elements` --> `Computed` tab

### Confirmed:
* removal of non-`Customize` icons
* `Inter`-family text for both photo attribution and `Customize` text

full snapshot | footer | Developer Tools, showing `font-family`
--------------|-------|---------------------------------------
<img width="1312" alt="Screen Shot 2024-07-05 at 3 16 05 PM" src="https://github.com/brave/brave-browser/assets/387249/0de5ad62-9522-4c83-85a6-51ff1d36ce2f"> | <img width="1159" alt="Screen Shot 2024-07-05 at 3 16 16 PM" src="https://github.com/brave/brave-browser/assets/387249/ed96368a-a2c6-42ef-903d-1a1940a14518"> | <img width="1564" alt="Screen Shot 2024-07-05 at 3 20 37 PM" src="https://github.com/brave/brave-browser/assets/387249/5ead6609-7a64-4fe5-8f3d-049a3af9c5cb">
