### ISSUE TITLE
CR 127 - Update brave notification text is not visible

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#39428]
### Description

The issue is reported by @kjozwiak !

CR 127 - Update brave notification text is not visible

### Steps to reproduce

1. Clean profile `1.69.53` 
2. Launch brave using `brave.exe --enable-logging=stderr --aue-reached-for-update-required-test --check-for-update-interval=10 --simulate-upgrade`
3. Update brave notification text is not visible

### Actual result

Update brave notification text is not visible
![image](https://github.com/brave/brave-browser/assets/38657976/c7fd1b6f-bd4a-4396-8380-876312d8c336)

### Expected result

![image](https://github.com/brave/brave-browser/assets/38657976/d30cbf60-525b-4f6d-bbdf-738dd2eb3a85)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.69.53 Chromium: 127.0.6533.17 (Official Build) nightly (64-bit)
-- | --
Revision | bedcc2e74ce45bd641d2946e0d870d68ba08b8e9
OS | Windows 10 Version 22H2 (Build 19045.4529)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @rebron @simonhong @mkarolin

**Comment by simonhong** [comment]
It's fixed recently via https://github.com/brave/brave-core/pull/23931 but got regressed again. checking.

**Comment by kjozwiak** [comment]
The above requires `1.68.107` or higher for `1.68.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.68.107 Chromium: 127.0.6533.26 (Official Build) beta (64-bit)
-- | --
Revision | 131a9beda9f0aea74f948286e5e8c63153d9f7f8
OS | Windows 10 Version 22H2 (Build 19045.4529)
```
Confirmed that `Update` text is visible
![image](https://github.com/brave/brave-browser/assets/38657976/e123e4ef-7ac3-44c0-9121-6b9c761c97b3)
