### ISSUE TITLE
Do not use "completely private" to describe privacy properties

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#39440]
### Description

Privacy and security is often a spectrum. We should not make false promises to users in our in-app messaging. We have automation in place to catch new instances of erroneous language but there are still many places in the app where we say "completely private", which goes against our internal [style guide](https://docs.google.com/document/d/17K6g3f80XbenCQdJJ2hcLX_b9GUS2h7ohIH2SWC4VDQ/edit#bookmark=id.ajimi58vl6xy).

### Steps to reproduce

1. Check P3A onboarding language on Android, Desktop and iOS
2. Check Brave News onboarding

### Actual result

We often say "completely private".

### Expected result

We should never say "completely private". 

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

All

### Android device

All

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.69.73 Chromium: 127.0.6533.26 (Official Build) nightly (64-bit)
-- | --
Revision | ebfe046ab1178f2195d83704420ed1ffa0370804
OS | Windows 10 Version 22H2 (Build 19045.4598)
```

### P3A onboarding

### Brave News onboarding

**Comment by LaurenWags** [comment]
@ShivanKaul does the note from @stephendonner above re: "completely anonymous" need to be addressed? If so, let me know and I can get a follow up issue logged. Thanks!

**Comment by ShivanKaul** [comment]
Oof, that's even worse, thanks for catching @stephendonner and @LaurenWags. Yes please let's file a separate issue for that.

**Comment by LaurenWags** [comment]
Thanks for reviewing @ShivanKaul - logged https://github.com/brave/brave-browser/issues/39972 as a follow up for the "completely anonymous" wording.

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP31.240617.010 release-keys
Brave build: 1.69.129
Chromium: 127.0.6533.73 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Clean install Brave
2. Launch Brave 
3. Go through onboarding > *Verify*

**ACTUAL RESULTS:**
- Verified that `completely private` string updated to `private` on P3A screen 
- Verified that no changes are made on the `News` onboarding screen

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/c9924774-687e-4550-90dd-f3e3075aab94) | ![2](https://github.com/user-attachments/assets/d25f924c-fa0d-4fe0-96c9-7b9e722415b3) | ![3](https://github.com/user-attachments/assets/ff4a486c-4b53-475b-9948-7b2c09238356) | ![4](https://github.com/user-attachments/assets/db62a98a-91d2-466f-8f99-263466b073d1) |

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.69 (156)`

- Ensured that `completely private` is not used on the P3A onboarding screen. 
- Ensured there are no changes in the Brave News opt in card.

Example | Example | Example | Example
-|-|-|-
![IMG_7169](https://github.com/user-attachments/assets/58887108-18b2-4226-a05b-bf55c484337c) | ![IMG_7170](https://github.com/user-attachments/assets/f6fce96c-968f-4d72-b775-05d1a52bb87b) | ![IMG_7171](https://github.com/user-attachments/assets/ccc6a2bd-58ac-45dd-9880-61097b427cc9) | x![IMG_7172](https://github.com/user-attachments/assets/79caac9e-5e1f-41dd-b8ec-818cd81cfec7)
