### ISSUE TITLE
[C127] Menu button is not clickable on tablets when the last tab is closed

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#39465]
### Description

Menu button is not clickable on tablets when the last tab is closed. Additionally we should add `New tab` button for this view to match the upstream.

### Steps to reproduce

1. Open Brave on tablet
2. Close all the tabs
3. Try to click menu

### Actual result

Menu is not clickable, there is no `New tab` button

### Expected result

Menu is clickable, there is `New tab` button

### Reproduces how often

Easily reproduced

### Brave version

1.69.x

### Device

- Brand/model: all tablets
- Android version: all

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.68.107` or higher for `1.68.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` using version(s):
```
Device/OS: Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
Brave build: 1.68.110
Chromium: 127.0.6533.26 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/39465#issue-2380834852
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `+ New tab` button is shown and tappable when all tabs are closed
- Verified that the `Main menu` is functional when all tabs are closed

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/05f95c53-cbdf-4e11-842b-6a1a4933a982) | ![2](https://github.com/brave/brave-browser/assets/128532965/28ab1097-1aec-4fbb-a55a-a0ea4297ee45) |

https://github.com/brave/brave-browser/assets/128532965/d561eecc-a15c-4ce9-9519-b0ecc20826e5
