### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#39468]
Brave Version: 1.68.101 Chromium: 126.0.6478.126
Operating System: Linux 6.9.3-76060903-generic

URL (if applicable) where crash occurred: new tab

Can you reproduce this crash? No

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open a new tab
2. Type `about:tor-internals` in the URL bar

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/7cfe0a00-b362-320c-0000-000000000000

**Comment by iefremov** [comment]
it seems working now, @fmarier can you reproduce?

**Comment by fmarier** [comment]
Yes, looks like it's fixed.
