### ISSUE TITLE
Answer with AI feature on search bar not using local Leo

### ISSUE THREAD

**Issue by Potatooff** [brave/brave-browser#39463]
### Description

I switched my main browser to Brave once I read the blog about the possibility to use Local LLM in Brave, It was something that I was looking for a while in Brave and it finally came.
Leo in the sidebar was working fine with the active local model (Llama3 70B) but when I was using 'Answer with AI' It wasn't used, I feel like this was something forgotten or an issue on my end. 

Please fix that, thank you!

### Steps to reproduce

1. Set the default model to be a local model
2. Make a query on the search box
3. Use 'Answer with AI' button in the search box section

### Actual result

It will use another model instead of the default one. It will not even tell which one it used. 

### Expected result

I expected it to actually use the default model, tell me if there was an issue with that model like "Request error" something like that instead of just using a model without telling which one it is.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.69.65 Chromium: 127.0.6533.26 (Official Build) nightly (64-bit)
Revision | 2c13a0566fdd2ef6a495035fd1efe1b123bc7d48
OS | Windows 11 Version 23H2 (Build 22631.3737)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

It will be reallty neat if Brave also had the possibility to continue the chat on the sidebar from the 'Answer with AI'

**Comment by TEMP-ad** [comment]
Do you mean the "Answer with AI" from Brave Search? because Brave Search has nothing to do with Brave Browser, any browser can use Brave Search and their LLMs don't connect like that.

- Omnibox "Ask Leo" autocomplete suggestion, uses the model you set as default.
- Select text -> right click -> AI Tools uses default model too.
- and `brave://flags/#brave-ai-rewriter` will use the default model.

**Comment by Potatooff** [comment]
Yeah from brave search

Le dim. 30 juin 2024, 3 h 13 a.m., TEMP-ad ***@***.***> a
écrit :

**Comment by diracdeltas** [comment]
As the reply above said (which I can't see for some reason, only via your quoted email reply), the search AI feature is completely separate from the Leo integration in the browser. @mattmcalister could maybe make this messaging more clear

**Comment by Potatooff** [comment]
Oh okay thank you for the clarification, if it could also be used with
local llms alongside their browser, it will be very neat!

**Comment by mattmcalister** [comment]
That's a very sensible request @Potatooff. We will be improving the feature, where it integrates and how we communicate what it does over the coming months. Thanks for the feedback.
