### ISSUE TITLE
Hamburger menu does not open after closing all tabs

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#39464]
### Description

Hamburger menu does not open after closing all tabs, likely related to CR127

### Steps to reproduce

1. New install 
2. Open some tabs
3. Open tab view, click on hamburger menu and select `Close all tabs`
4. Tap on hamburger menu again

### Actual result

Nothing happens

![Screenshot 2024-06-28 at 12 36 34 PM](https://github.com/brave/brave-browser/assets/17885425/771210db-e0ce-41f5-9f88-a6393dd7cb49)

### Expected result

Should open

### Reproduces how often

Easily reproduced

### Brave version

1.69.64 - reproducible
1.69.49 - not reproducible

### Device

- Brand/model: Samsung Tablet
- Android version: 13

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by samartnik** [comment]
This was fixed in the context of https://github.com/brave/brave-browser/issues/39465

**Comment by kjozwiak** [comment]
> This was fixed in the context of #39465

Thanks @samartnik 👍 Labelled the above as `QA/No` as we'll verify the above via https://github.com/brave/brave-browser/issues/39465.
