### ISSUE TITLE
[Cr127] Android device is duplicated in the `Sync` chain when reopening Brave

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#39470]
### Description

Android device is duplicated in the `Sync` chain when restarting Brave. Duplicated devices appear on Desktop, iOS, and another Android device, but not on "test" devices.

The issue is not reproducible for:
- `iOS` device on any channel
- `Android` device on Release or Beta channel
- `Android` device on Nightly channel with `Cr126`

### Steps to reproduce

1. Start the `Sync` chain on the Desktop, iOS or Android `A` device
2. Launch Brave on Android `B` device
3. Join the existing `Sync` chain by scanning the QR code or copying the phrase
4. Confirm that the Android `B` device appeared in the `Sync` chain
5. Close and relaunch Brave > *Observe that device is duplicated*

### Actual result

Android device is duplicated in the `Sync` chain when restarting Brave. Duplicated devices appear on Desktop, iOS, and another Android device, but not on "test" devices.

------------------

https://github.com/brave/brave-browser/assets/128532965/5af560b6-f691-4d39-95c6-66671a8ae728

### Expected result

Devices must not be duplicated in the `Sync` chain when relaunching Brave.

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.69.55 
Chromium: 127.0.6533.17 (Official Build) canary (64-bit) 

### Device

- Brand/model: Pixel 6, Pixel 7
- Android version: Android 14, 15

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @AlexeyBarabash

**Comment by kjozwiak** [comment]
The above requires `1.68.117` or higher for `1.68.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP31.240517.031 release-keys
Brave build: 1.68.117
Chromium: 127.0.6533.26 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/39470#issue-2380918038
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Android` device is not duplicated when joining the existing `Sync chain`.
- Verified the same with `fresh` and `upgraded` profiles.
- Verified that removing an `Android` device from the Sync chain on a `Desktop` or `iOS/Another Android` device is working, and the affected device is losing access to a Sync chain.

---------------------------

https://github.com/brave/brave-browser/assets/128532965/f3ee3e44-5c63-4b15-820c-ebfc573aea61
