### ISSUE TITLE
Cannot unset the default "Delete data when you close all windows" for sites

### ISSUE THREAD

**Issue by alecov** [brave/brave-browser#39473]
### Description

Cannot unset the default "Delete data when you close all windows" for sites.

Every tab I open has the "Delete data when you close all windows" selected as default, and cookies are cleared on tab close.

"Forget me when I close this site" is **unchecked**.
"Delete browsing data / On exit" list is **empty** (no item checked).

There seems to be no way to make sites be able to save data **per default** back again, I need to allow this on an individual basis.

### Steps to reproduce

Not sure how to reproduce. I have a separate profile in which cookies were deleted every time a tab was closed. Now I want to make it save the cookies back again. There seems to be no setting for this.

### Actual result

All new sites have this:

![Screenshot at 2024-06-28 17-15-26](https://github.com/brave/brave-browser/assets/20651620/3c1ec9e6-f3f7-4477-868f-aceb4dbe49c3)

### Expected result

Sites can save cookies per default again.

![image](https://github.com/brave/brave-browser/assets/20651620/4eef838b-5766-4085-bf9b-ff4a759c0ac9)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Version: 1.67.116 Chromium: 126.0.6478.71 (Official Build) (64-bit) 
Rev: f4237fe448716e50cca6e827ff87ffd701c7d0c7
OS: Linux

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by alecov** [comment]
#39033 likely related.

**Comment by TEMP-ad** [comment]
You can't unset it from the dialog, you can only either block storage or allow storage which will do the same as leaving this setting alone and not storing the data in the 1p Ephemeral Storage so it gets cleared on site close after 30 seconds.
Yes, you are not actually removing data from the persistent Storage with this setting, unlike Forget me feature which clears the persistent storage, you are storing it in the Ephemeral Storage so it will clear after 30 seconds when you close a site and never appear in the brave://settings/content/all

You can remove that entry from brave://settings/content/siteData so this is not an issue, and it is doing what it is suppose to do.

**Comment by alecov** [comment]
>You can remove that entry from brave://settings/content/siteData so this is not an issue, and it is doing what it is suppose to do.

__THAT__ was the page I was trying to find for almost an hour. Very hard to dig. I had supposed it got removed along with the cookies page. Thanks for pointing that out and apologies for the confusion.

I'll be closing this.
