### ISSUE TITLE
Build out Choose Quote Provider for Bridge and Swap

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#39472]
### Platforms

Linux, macOS, Windows

### Description

We need to build out the `Choose quote provider` feature to allow user to select which `Provider` they want to use for a `Swap` or `Bridge` transaction.

Should replace the `Settings` button on the `Swap` and `Bridge` screen

Options should be
- `Auto` (Will choose the best `Quote Provider` depending on the trade for the user.)
- `Li.Fi`
- `0x`
- `Jupiter`

![Screenshot 9](https://github.com/brave/brave-browser/assets/40611140/a0fe2a04-8b3f-4b47-878c-72e5e305e767)

![Screenshot 8](https://github.com/brave/brave-browser/assets/40611140/c8f783d4-8836-4a6c-a0bc-13b786f8dd53)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.147 Chromium: 128.0.6613.40 (Official Build) (64-bit)
-- | --
Revision | d29b1747d0f906239936b0d94c40889920ebf2c0
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from [ brave/brave-core#24444](https://github.com/brave/brave-core/pull/24444)
- Verified clicking on the Brave icon in Swap/Bridge brings up the quote provider list
- Verified on Swap, selecting ETH token as Swap from, Jupiter is disabled in quote provider list
- Verified on Swap, selecting SOL token as Swap from, 0x is disabled in quote provider list
- Verified selecting ETH token for Swap and selecting 0x as provider, changing ETH to SOL shows quote provider error message
- Verified on Bridge, 0x and Jupiter are disabled in quote provider list

https://github.com/user-attachments/assets/c6b052be-cde1-47d6-8d93-198bc4266b21
