### ISSUE TITLE
Leo - Pressing the escape key doesn't collapse the `Leo` sidebar.

### ISSUE THREAD

**Issue by hamirmahal** [brave/brave-browser#39493]
### Description

Pressing the escape key doesn't collapse the `Leo` sidebar.

### Steps to reproduce

1. Select text.
2. Ask `Leo` to summarize it.
3. Press the escape key.

### Actual result

Nothing

### Expected result

The `Leo` sidebar should close.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave	1.65.133 Chromium: 124.0.6367.208 (Official Build) (64-bit) 
Revision	a719189e6a0245a6ce7fab3ddc637e8bd75aed08
OS	Linux
```

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by hamirmahal** [comment]
brave://settings/system/shortcuts?search=Sidebar shows a setting to toggle the sidebar's position, but it'd be useful if users could collapse the sidebar altogether with just the keyboard.

**Comment by bsclifton** [comment]
cc: @rebron - could be nice for all sidebar items to collapse with ESC.
also cc: @fallaciousreasoning @bbondy

**Comment by rebron** [comment]
Ctrl+B to open and close the side panel. I'm not sure ESC makes sense here to collapse the sidebar.

**Comment by bsclifton** [comment]
oh wow- ok, Ctrl+B is super easy. I'll close this as `wontfix`. 

@hamirmahal you can visit brave://settings/system/shortcuts and then search for `Sidebar`. You can customize the shortcut there
