### ISSUE TITLE
Extension name missing for IPFS

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3950]
## Description 

Extension name missing for IPFS

## Actual result:

![Screenshot from 2019-03-30 09-54-27](https://user-images.githubusercontent.com/17010094/55277343-71119480-52d5-11e9-8d2c-b04a10133e05.png)

## Expected result:
Should show extension name

## Reproduces how often: 

Easy 

## Brave version (brave://version info)

Brave | 0.65.2 Chromium: 73.0.3683.75 (Official Build) nightly(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

Brave | 0.64.29 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on nightly and dev
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A
### Additional Information

cc: @bbondy

**Comment by bbondy** [comment]
is that just the same as the same IPFS companion installed on Chrome?

**Comment by srirambv** [comment]
@bbondy Yes its the same

**Comment by bbondy** [comment]
cc @lidel

**Comment by srirambv** [comment]
This is on Chrome btw
![Screenshot from 2019-04-02 11-18-40](https://user-images.githubusercontent.com/17010094/55414467-2728e880-5539-11e9-9e6f-ddf9dfbfcd66.png)

**Comment by bbondy** [comment]
Sorry I think this is probably an error with the way we're installing it. cc @yrliou

**Comment by lidel** [comment]
Hi, IIUC `__MSG_manifest_extensionName__` in `manifest.json` should just work.
In Chrome and Firefox it is replaced at runtime by translation from `add-on/_locales/en/messages.json`

**Comment by yrliou** [comment]
It is currently installed as a component extension, and there is a known bug in chromium that manifest is not localized for component extensions: https://bugs.chromium.org/p/chromium/issues/detail?id=66834&q=%22component%20extension%22&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified.

**Comment by lidel** [comment]
@yrliou  thank you for finding this, it is unfortunate.

I know Brave will need to patch manifest to add `sockets`  (cc @bbondy), would it be possible to also override `extensionName` and hardcode it to be `IPFS Companion` there?

(We'd like to avoid hardcoding `extensionName` to `IPFS Companion`  in our manifest, but that is always a fallback plan)

**Comment by yrliou** [comment]
@lidel I'm currently working on installing it as an extension instead of a component extension, hopefully that would get us back into a good state.
And yes, we could fallback to manually setting extension name and description of the manifest if the above doesn't work as well as we expected.

**Comment by btlechowski** [comment]
Reproduced on 

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

![image](https://user-images.githubusercontent.com/34715963/56630542-b8aee600-661f-11e9-96fe-39fe3f1c101b.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.64.68 Chromium: 74.0.3729.108 (Official Build) beta (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Windows 10 OS Build 17134.523

- Verified the test plan from https://github.com/brave/brave-core/pull/2328
