### ISSUE TITLE
Add to home screen UI shows chrome branding [CR127]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#39502]
### Description

The new `Add to Home screen` UI does not show the correct icon / browser name for the `Create shortcut` option. Adding the shortcut will show the correct branding on the Home screen.

### Steps to reproduce

1. New install
2. Navigate to a webpage that supports both PWAs and shortcuts like wikipedia
3. Open hamburger menu and select `Add to Home screen`
4. Select `Create shortcut` in the Add to home screen dialog

### Actual result

![Screenshot 2024-06-28 at 6 12 19 PM](https://github.com/brave/brave-browser/assets/17885425/0a1da101-42f1-46bb-8aa2-2f2312a6857f)

### Expected result

Branding should be Brave instead of Chrome

### Reproduces how often

Easily reproduced

### Brave version

1.69.65, Chromium 127.0.6533.26

### Device

- Brand/model: Samsung Tab S7
- Android version: 13

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.68.107` or higher for `1.68.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP31.240517.031 release-keys
Brave build: 1.68.101
Chromium: 126.0.6478.126 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/39502#issue-2384226982
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Brave` branding is shown

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/293145fd-4be9-4618-96f9-054bcaf16d4d) | ![2](https://github.com/brave/brave-browser/assets/128532965/0a9c05cd-5073-4556-a3c6-8a5a7b6862b8) |
