### ISSUE TITLE
[Wallet] Some Solana NFTs are incorrectly grouped

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39500]
### Description

We are currently using token symbols to group Solana NFTs, which can lead to unrelated NFTs being grouped together

### Steps to reproduce

1. Add multiple Solana NFTs to your wallet that have the same token symbol, but are from different collections
2. view the portfolio NFTs page
3. enable the group-by-collection option in the NFT filters

### Actual result

Solana NFTs with the same token symbol will be grouped into a single collection

### Expected result

Solana NFTs should be grouped by collection name

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.65 Chromium: 127.0.6533.26 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.136 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 47255350e0d135b2172cb9dd2ba344d3d7fe4572
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified Solana NFTs with same symbol but different collection are grouped correctly 

https://github.com/user-attachments/assets/0b58851a-7758-436d-aa46-b7bbb5216aca
