### ISSUE TITLE
AIChat: Fullscreen UI

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#39501]
- Wider version of same UX used in Sidebar
- Left-hand collapsible sidebar 
- Option for manually selecting a different model for the conversation
- Blank view includes new Conversation Starters

https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/%F0%9F%94%84-Leo-[IN-PROGRESS]?node-id=15-15519&t=ab48RVF3AIGVH6eS-0

**Comment by petemill** [comment]
Duplicate of https://github.com/brave/brave-browser/issues/30554
