### ISSUE TITLE
[ads] Do not classify page content for same document navigations

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#39506]
### Description

NOTE: We *SHOULD* still classify page content for initial page load

**Comment by btlechowski** [comment]
Verified with

Brave | 1.69.129 Chromium: 127.0.6533.73 (Official Build) beta (64-bit)
-- | --
Revision | 0ab2f25cd017b563fd72d68048f809659a351a04
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/24568

### multi-page navigations

<details>

#### page classifier



#### conversion


</details>


### single-page application

<details>

#### page classifier on first view



#### conversion




</details>

**Comment by btlechowski** [comment]
Verified test plan from https://github.com/brave/brave-core/pull/24568

### multi-page navigation

<details>

#### page classifier

Verified page is classified on each navigation
1st navigation:
```

```

2nd navigation
```

```


</details>


### single-page navigation

<details>

#### page classifier on first view

```

```

Verified subsequent navigation does not trigger page classifier



</details>
