### ISSUE TITLE
AIChat: UI Improvements for Local Models - Disable Like/Dislike and Hide Premium Prompt

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#39508]
1. don't show “Your Brave account session...” prompt when using a local model
2. hide like/dislike from UI for local models

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.69.96 Chromium: 127.0.6533.26 (Official Build) nightly (64-bit)
-- | --
Revision | 25973a147e9d4ea0cd7b27c49f55792640a3b827
OS | Windows 10 Version 22H2 (Build 19045.4651)
```

### Steps:
1. installed `1.69.96`
2. launched Brave using `--enable-logging=stderr --v=2 --env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev`
3. purchased `Leo Premium` from `account.brave.com`
4. loaded `https://www.vox.com/iran/359723/pezeshkian-iran-khamenei-elections-raisi-president-ayatollah-mahsa-amini-protests-vote-hijab`
5. installed and set up `Ollama`'s `llama3` locally
6. clicked on `Leo` in the sidebar
7. switched to using `llama3` from the `Custom models` section
8. clicked on `Summarize this page`
9. confirmed page summarization
10. hovered over the AI-generated response

### Confirmed no vertical 3-dots ellipsis for `Like answer` and `Dislike answer` options (only `Copy`, which works)


example | example
----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/986f1708-8f2e-478b-a778-98ce6ba45ea5) | ![image](https://github.com/brave/brave-browser/assets/387249/93560cca-859e-4cd2-a372-0f1c213d33a1)
