### ISSUE TITLE
Add Button for adding the current tab to reading list

### ISSUE THREAD

**Issue by iFrozenPhoenix** [brave/brave-browser#39509]
### Platforms

all

### Description

An add button to add the current tab to the reading list would make it more intuitive and fluent to browse the web and collect information.
I suggest that the button will be added within the address bar on the right side (Like already implemented by chromium based browsers edge and chrome).

**Comment by rebron** [comment]
@iFrozenPhoenix When you open the Reading list panel, there's a button to add the current tab. 
<img width="325" alt="Screenshot 2024-07-01 at 2 14 58 PM" src="https://github.com/brave/brave-browser/assets/5951041/ae0b8897-2daf-4ece-9fdc-10821f5ba4f8">

**Comment by iFrozenPhoenix** [comment]
@rebron Yeah I know, but imagine you are surfing the web and come to an interesting site that you want to read later. It is really uncomfortable to first open the list and then go down to the add button. For me it is going to the left side of the window, click reading list, go down, click add, click to close the list again.
Compared to 1 click if it would be in the address bar.

**Comment by simonhong** [comment]
@iFrozenPhoenix We have another point for you.
Tab context menu has `Add Tab to Reading List` entry.
<img width="280" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/9143fcee-4d72-407a-acbd-922ec95cbf7e">

**Comment by iFrozenPhoenix** [comment]
@simonhong ok, this is definitely better than my current way.
Thanks
