### ISSUE TITLE
Google Docs fonts jumbled with shields up

### ISSUE THREAD

**Issue by vinniejames** [brave/brave-browser#3951]
## Description 
Google docs jumbles the fonts with shields up

## Steps to Reproduce

   1. Create new Presentation (similar font rendering issues in Sheets as well)
   2. Some fonts end up collapsed on letter on letter
   3. Turn shields off, problem resolved

## Actual result:

Shields on:
<img width="1186" alt="Screen Shot 2019-03-30 at 11 58 24 AM" src="https://user-images.githubusercontent.com/2112033/55278477-4d554b00-52e3-11e9-9e80-77824f2a2b66.png">

## Expected result:

Shields off:
<img width="1263" alt="Screen Shot 2019-03-30 at 11 58 14 AM" src="https://user-images.githubusercontent.com/2112033/55278483-58a87680-52e3-11e9-88a8-5a0e2d746ede.png">

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Mac OS X
JavaScript | V8 7.3.492.25
Flash | (Disabled)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Unknown

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

**Comment by lasombra** [comment]
I'm seeing the same thing on Linux x86_64. In my case I'm using Fedora 30.

**Comment by Nixccc** [comment]
Are you using localCDN; it broke most google pages for me

**Comment by vinniejames** [comment]
No

**Comment by ryanbr** [comment]
@vinniejames is this still an issue with the latest version of Brave?

**Comment by srirambv** [comment]
I encounter similar thing for specific documents on GDrive when FP is set to strict. @ryanbr will DM the links where I can repro

**Comment by tocic** [comment]
Still reproducible with Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (64-bit).

**Comment by bsclifton** [comment]
@tocic if you have the domain set to strict fingerprinting, you can set as just regular block fingerprinting and the issue should resolve. There are fingerprints that can be made using font list / accept language lists and this can cause problems with fonts on sites

**Comment by tocic** [comment]
@bsclifton I can confirm that changing the option from  "_Aggressively block fingerprinting_" to "_Block fingerprinting_" resolves the issue without the need to completely disable shields.

**Comment by pes10k** [comment]
thank you for the followup @tocic . Closing this then
