### ISSUE TITLE
webcompat exceptions service UI

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#39510]
### Platforms

Linux, macOS, Windows

### Description

We are planning to add a user interface for the webcompat exceptions service. See design here https://docs.google.com/document/d/1mjdx3Rk2TCXbJRzpYkb3ieGm2MhFXxf4zTGEEropzuY/edit#heading=h.qiew63uicrsj

**Comment by arthuredelstein** [comment]
**Suggested QA testing**

The webcompat exceptions service UI is disabled by default behind brave://flags/#brave-webcompat-exceptions-service

Once it is enabled, you can visit any web page that calls some fingerprintable APIs. To see the new UI, go to "Advanced controls" under the per-site Shields menu, and click the integer next to "Block fingerprinting" toggle. There should be a menu with some number of toggle switches. For example, https://browserleaks.com/javascript shows 9 fingerprintable APIs that have been called from that website.

Now you can click individual toggle switches to enable/disable specific fingerprinting protections. The web page should reload after each toggle event. Because fingerprinting protections typically change the value that a Web API returns to a page, toggling those individual switches will change value for items displayed on https://browserleaks.com/javascript.

toggle | browserleaks item
--- | --- 
device memory | deviceMemory
font | N/A
hardware concurrency | hardwareConcurrency
keyboard | keyboard
language | languages
plugins | plugins
screen | Screen Resolution
speech synthesis | N/A
user agent | N/A

(Changes due to the N/A items are not visible for me on browserleaks.com, on macOS.)

**Comment by LaurenWags** [comment]
Added missing milestone to match linked PR

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.70.88 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 7431803bd1e909ef82982df42e2ea7aacbad755e
OS | Windows 11 Version 23H2 (Build 22631.4037)
```

 1. Installed 1.70.88
2. launched Brave
3. relaunched Brave to pull in the griffin study (BraveScreenFingerprintingBlockerStudy:Enabled)
4. opened https://browserleaks.com/javascript in a new tab
5. opened Shields panel > Advanced Controls
6. confirmed `Block Fingerprinting` setting shows integer `9`
7. clicked on the integer
8. confirmed below toggle switches are visible and enabled by default for the site

- device memory
- font 
- hardware concurrency
- keyboard
- language 
- plugins
- screen
- speech synthesis
- user agent
9. toggled `off` and `on` for `device memory` 
10. repeated step 10 for rest of the toggle switches in step 9

https://github.com/user-attachments/assets/89ee8b39-3396-4671-92de-4ac349ab5b95

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using

```
Brave | 1.70.92 Chromium: 128.0.6613.85 (Official Build) beta (arm64)
-- | --
Revision | 711f50838f629ac2be4d1d9592f72adecfd3c928
OS | macOS Version 14.6.1 (Build 23G93)
```

1. Installed 1.70.88
2. launched Brave
3. relaunched Brave to pull in the griffin study (BraveScreenFingerprintingBlockerStudy:Enabled)
4. opened https://browserleaks.com/javascript in a new tab
5. opened Shields panel > Advanced Controls
6. confirmed next to `Block Fingerprinting` setting shows integer `9`
7. clicked on the integer
8. confirmed below toggle switches are visible and enabled by default for the site

- device memory
- font 
- hardware concurrency
- keyboard
- language 
- plugins
- screen
- speech synthesis
- user agent
9. toggled `off` and `on` for `device memory` 
10. repeated step 10 for rest of the toggle switches in step 9
11. confirmed the correct count is shown for Fingerprinting protections applied `8`


Uploading Screen Recording 2024-08-27 at 4.17.08 PM.mov…

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.70.109 Chromium: 128.0.6613.138 (Official Build) beta (64-bit) 
Revision	fec4422ae56f4d9680c71a3c1de60b9a8e5ef32f
OS	Linux
```


1. Installed 1.70.88
2. launched Brave
3. relaunched Brave to pull in the griffin study (BraveScreenFingerprintingBlockerStudy:Enabled)
4. opened https://browserleaks.com/javascript in a new tab
5. opened Shields panel > Advanced Controls
6. confirmed next to `Block Fingerprinting` setting shows integer `9`
7. clicked on the integer
8. confirmed below toggle switches are visible and enabled by default for the site

- device memory
- font 
- hardware concurrency
- keyboard
- language 
- plugins
- screen
- speech synthesis
- user agent
9. toggled `off` and `on` for `device memory` 
10. repeated step 10 for rest of the toggle switches in step 9
11. confirmed the correct count is shown for Fingerprinting protections applied `8`
