### ISSUE TITLE
[Wallet] Do not attempt IPFS gateway URL translation for non-IPFS URLs

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39519]
### Description

Currently, we attempt to translate token image URLs to an IPFS gateway URL even when the source URL is not an IPFS URL. We should avoid this whenever possible

### Steps to reproduce

N/A - Only noticeable by adding logs to source code

### Actual result

N/A - Only noticeable by adding logs to source code

### Expected result

We should not attempt translation for non-IPFS URLs

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.67.116 Chromium: 126.0.6478.71 (Official Build) (arm64) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by josheleonard** [comment]
Related to: [Perf: wallet is dispatching too many redux actions](https://github.com/brave/brave-browser/issues/19226#top)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.136 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 47255350e0d135b2172cb9dd2ba344d3d7fe4572
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24463](https://github.com/brave/brave-core/pull/24463)
- Verified token images load as expected
