### ISSUE TITLE
Set kBraveShowStrictFingerprintingMode to disabled by default across platforms

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#39517]
### Platforms

Android, Linux, macOS, Windows

### Description

We already have disabled showing strict fingerprinting via griffin; now we can disable by default in brave-core.

**Comment by arthuredelstein** [comment]
Once we disable it in brave-core, we can remove it from brave-variations.

**Comment by LaurenWags** [comment]
@arthuredelstein since this is labeled `QA/Yes`, mind adding a test plan? Labeling as `QA/Blocked` for now.

**Comment by arthuredelstein** [comment]
**QA testing suggestion:**

1. Visit any website (example.com)
2. Check that the "Block fingerprinting" item in the Advanced shields section is a toggle switch, not a drop down menu.

**Comment by MadhaviSeelam** [comment]
Adding `QA/Test-All-Platforms` label as per the description

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.92 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 711f50838f629ac2be4d1d9592f72adecfd3c928
OS | Windows 11 Version 23H2 (Build 22631.4037)
```

1. Installed 1.70.92
2. launched Brave
3. visited example.com
4. clicked `Shileds` >> `Advanced Controls`
5. confirmed that the "Block fingerprinting" setting is a toggle switch, not a drop down menu.

example | example 
---- | ---
![image](https://github.com/user-attachments/assets/a94d44c1-ab57-45eb-9404-9fd612771f11)|![image](https://github.com/user-attachments/assets/acfa40d1-11bf-4bdd-9028-9a72f5662548)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.92 Chromium: 128.0.6613.85 (Official Build) beta (arm64)
-- | --
Revision | 711f50838f629ac2be4d1d9592f72adecfd3c928
OS | macOS Version 14.6.1 (Build 23G93)
```

1. Installed 1.70.92
2. launched Brave
3. visited example.com
4. clicked `Shileds` >> `Advanced Controls`
5. confirmed that the "Block fingerprinting" setting is a toggle switch, not a drop down menu.
6. enabled/disabled toggle and it worked as expected


example | example 
--- | ----
![image](https://github.com/user-attachments/assets/f2e77c3e-49a3-4691-bcc0-1f03b692c931)|![image](https://github.com/user-attachments/assets/79ec5572-ae43-4b4b-92ad-706b9ac8c260)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.70.109 Chromium: 128.0.6613.138 (Official Build) beta (64-bit) 
Revision	fec4422ae56f4d9680c71a3c1de60b9a8e5ef32f
OS	Linux
```

1. Installed 1.70.109
2. launched Brave
3. visited example.com
4. clicked `Shields` >> `Advanced Controls`
5. confirmed that the "Block fingerprinting" setting is a toggle switch, not a drop down menu.
6. enabled/disabled toggle and it worked as expected


example | dark theme | light theme
--- | ---- | ----
![image](https://github.com/user-attachments/assets/be50e1db-efd2-4ad3-8e5d-919db1281107)|![image](https://github.com/user-attachments/assets/fab4f34a-1617-41cb-9a8f-75fa06027c61)|![image](https://github.com/user-attachments/assets/979c49bc-63e5-47f8-9841-eaf4d16d3e79)

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 AP41.240726.010 release-keys
Brave build: 1.70.107
Chromium: 128.0.6613.120 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/39517#issuecomment-2310722728
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Block Fingerprinting` is shown as a `toggle switch`, but not as a `dropdown menu`.
- Verified that turning `Block Fingerprinting` **on** and **off** works as expected.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/0273803f-68d5-4342-9fe6-77d46822c653) | ![2](https://github.com/user-attachments/assets/3550c6c6-92e7-4db9-8817-a4f7d2a9295e) | ![3](https://github.com/user-attachments/assets/fdcf08cc-72fa-4b2a-9359-052d4c3636d2) | ![4](https://github.com/user-attachments/assets/9fef6a00-feb9-4318-ad29-860a69d29cb3) |
