### ISSUE TITLE
Build out Max Slippage Modal for Swap and Bridge

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#39514]
### Platforms

Linux, macOS, Windows

### Description

We need to build out the new `Max Slippage` modal for `Swap` and `Bridge` to allow user to set the `Max Slippage` for their transactions.

![Screenshot 1](https://github.com/brave/brave-browser/assets/40611140/18d9e52a-9a84-48c4-a0a4-6e2911e9eea7)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.136 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 47255350e0d135b2172cb9dd2ba344d3d7fe4572
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24559](https://github.com/brave/brave-core/pull/24559)
- Verified Max Slippage modal is updated to new design
- Verified Max Slippage works on both Swap and Bridge transactions
- Verified Quote is refetched when max slippage is updated
- Verified Quote value is updated when max slippage is updated

https://github.com/user-attachments/assets/d96a4734-e03e-4912-abcc-abcc89776517
