### ISSUE TITLE
Add Refresh Quote Button to Swap and Bridge

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#39513]
### Platforms

Linux, macOS, Windows

### Description

We need to add a `Refresh` quote button to the `Swap` and `Bridge` screens to allow user fetch a new quote instead of waiting.

![Screenshot](https://github.com/brave/brave-browser/assets/40611140/f7753335-385a-41d8-884f-51f4dd0a163f)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.136 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 47255350e0d135b2172cb9dd2ba344d3d7fe4572
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24469](https://github.com/brave/brave-core/pull/24469)
- Verified `Refresh Quote` button is shown on both Swap and Bridge screen
- Verified able to manually refresh quote by clicking the `Refresh Quote` button
- Verified works for all providers

https://github.com/user-attachments/assets/fc57ceee-c7a3-4a4b-90d7-9880d17b4358
