### ISSUE TITLE
AIChat: Local models should not attach page contents to system prompt

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#39525]

**Comment by petemill** [comment]
@LorenzoMinto is this actually better than putting the page content in the system prompt? Every message in the conversation will be about the fact that the user is reading this web content.

**Comment by LorenzoMinto** [comment]
Yes. We inherited putting the article in the system message from Claude, where things were structured a little different, but now we've moved away from that paradigm also there. System messages should only contain "global" instructions for the model, adding a lot of content there might actually make instruction following a bit weaker. Adding the page content as part of the user request has the same benefits, it's more flexible (can add a new piece of content later on in the convo), and has less adverse effects.
