### ISSUE TITLE
Sidebar UI is not hidden with `On mouseover` option

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#39522]
### Description

It's regressed from https://github.com/brave/brave-core/pull/24382

Sidebar UI should be hidden after mouse out from sidebar UI

https://github.com/brave/brave-browser/assets/6786187/e46d85be-489f-4b9e-a9bc-992dc6f53c8c

### Steps to reproduce

1. Set sidebar option as `On mouseover`
2. Click any panel item to open panel
3. Click current active item to close panel
4. Move mouse out from sidebar UI

### Actual result

Sidebar UI is not hidden

### Expected result

Sidebar UI should be hidden

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.70 Chromium: 127.0.6533.26 (Official Build) nightly (x86_64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by simonhong** [comment]
Fixing now.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.69.88 Chromium: 127.0.6533.26 (Official Build) nightly (x86_64)
-- | --
Revision | d60303973dc3604d9d348b981322a8a04dcbb86d
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.69.88`
2. launched Brave
3. context-clicked on the sidebar
4. changed `Show Sidebar` from `Always` to `On mouseover`
5. clicked on `Leo` to open `Leo` in the sidebar
6. clicked again on the `Leo` icon to close its panel
7. moved the mouse pointer out of the sidebar's region
8. confirmed the sidebar auto-closed
9. also confirmed it auto-opened again when moused-over

example | example | example | example
---------|----------|---------|---------
<img width="1205" alt="Screen Shot 2024-07-08 at 3 40 49 PM" src="https://github.com/brave/brave-browser/assets/387249/889d2a10-3481-488c-a2a3-1e91a587d9b3"> | <img width="1312" alt="Screen Shot 2024-07-08 at 3 41 13 PM" src="https://github.com/brave/brave-browser/assets/387249/21c922df-28f1-45ea-b3d5-c9cfa7b16f98"> | <img width="1312" alt="Screen Shot 2024-07-08 at 3 41 33 PM" src="https://github.com/brave/brave-browser/assets/387249/ce6dbf42-54fd-4852-853b-0287ae80fb70"> | <img width="1312" alt="Screen Shot 2024-07-08 at 3 41 36 PM" src="https://github.com/brave/brave-browser/assets/387249/1aae82a7-29bb-4382-bf02-554ca0e6f0e0">
