### ISSUE TITLE
Refactor tips flow

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#3953]
We need to move getters for tip list into ledger lib. Currently get tips is not wired though bat-native-ledger.

1) Rename `brave_rewards.updateTipsList` to `brave_rewards.getOneTimeTips`
2) Rename `brave_rewards.updateRecurringDonationsList` to `brave_rewards.getRecurringTips`
3) Rename `GetRecurringDonations` to `GetRecurringTips`
4) Wire `GetRecurringTips` through bat-native-ledger
5) Rename `UpdateTipsList` to `GetOneTimeTips` and merge it with `TipsUpdated` function
6) Wire `GetOneTimeTips` through bat-native-ledger

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.65.97 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2140 with regular sites, youtube channels, and twitch channels. Verified with both auto contribute enabled and auto contribute disabled.
