### ISSUE TITLE
NTP Search box - Adjustments

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#39533]
### Description

There are a couple of issues with the font styles for the autosuggestions:
Design:
https://www.figma.com/design/lVTufBkl5eNrtOQjlAHxjb/Search-box-in-NTP?node-id=220-17509&t=68Nf5eodhxUbybQp-1

- [x] The color for the autosuggestion should use `glass/100%` (now uses text/secondary)
----------------
- [x] The color for the "Brave Search" message should use `glass/70%` (now uses text/interactive) 
<img width="163" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/da6fba10-537b-45fd-9ea7-bae8f798dd07">

-----------------

- [x] The divider between the input and the autosuggestions needs to be `glass/10%`
<img width="976" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/9c6c2631-5c58-476f-8491-cc4ef6621861">

### Steps to reproduce

---

### Actual result

<img width="607" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/3d5828e7-127c-4043-8ad5-ed40b7940360">

### Expected result

<img width="863" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/ed45593a-4f57-4d69-bb67-ce80b83d94b5">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

---

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.68.117` or higher for `1.68.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.68.117 Chromium: 127.0.6533.26 (Official Build) beta (64-bit)
-- | --
Revision | 80857ef16345e7959abe655afdebf9521f5109aa
OS | Windows 10 Version 22H2 (Build 19045.4651)
```

### Steps:
1. installed `1.68.117`
2. launched Brave
3. opened a new-tab page
4. focused the `Search the web privately` textfield
5. entered `Hello`
6. looked at the auto-complete/suggest results

### * Brave Search is now below the first search term, and is now in the same glass styling as the search terms
### * the divider between the search-input textfield and the auto-suggestions text is now also glass-styled
### * the color of the auto-suggestion text is also now glass-styled (previously, it was lighter-colored)

![image](https://github.com/brave/brave-browser/assets/387249/9dec1ca1-d741-41aa-9665-c6a73cc78985)
