### ISSUE TITLE
[Wallet] Update example values in the Add-NFT form

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39531]
### Description

We should use Pudgy Penguins instead of BoardApeYachtClub as the example NFT value since their token names include the collection name instead of just the token id

### Steps to reproduce

1. Navigate to brave://wallet/crypto/portfolio/add-asset#available-assets
2. Click NFT
3. observe the form field placeholder values

### Actual result

BoardApeYachtClub values are used

### Expected result

Pudgy Penguins values should be used instead

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.65 Chromium: 127.0.6533.26 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.110 Chromium: 127.0.6533.43 (Official Build) nightly (64-bit)
-- | --
Revision | b48482acae2813d6c44e4a83f48b479c56dbc116
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified NFT place holder text reads `e. g Pudgy Penguin #1234`
![image](https://github.com/user-attachments/assets/549d4a88-b5ad-4fab-be75-fa2d2743d0b3)
