### ISSUE TITLE
[Wallet] Non-IPFS images not loading when wrapped in placeholder fallback component

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39537]
### Description

There is a bug in the `withPlaceholderIcon` function that prevents non-ipfs images from loading

### Steps to reproduce

1. Go to the Add NFT form
2. enter valid token info 
3. observe the preview image

### Actual result

image is not loaded

### Expected result

token image should load and be displayed

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.65 Chromium: 127.0.6533.26 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.136 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 47255350e0d135b2172cb9dd2ba344d3d7fe4572
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified Non-IPFS images are loaded when adding an NFT and on NFT details view

https://github.com/user-attachments/assets/1956f98d-a292-426f-9e2e-893221ed1467
