### ISSUE TITLE
[iOS] - Temporarily disable Apple MDR for Leo

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#39540]
### Description

- iOS code supports Multi-Device purchase restoring AUTOMATICALLY
- This may cause issues with our backend as we require users to LINK accounts to use their subscription on their other devices (including Apple devices).
- We should disable MDR (Multi-Device Restoration) via Apple's notification (this is NOT the same as our Skus MDR).

### Steps to reproduce

1. https://github.com/brave/brave-browser/issues/38788
2. Subscriptions should NOT automatically be restored on all other devices

### Actual result

- Subscriptions are automatically restored on other devices

### Expected result

- Subscriptions should not automatically be restored on other devices. The user must hit the restore button themselves (for now).

### Reproduces how often

Easily reproduced

### Brave version

1.69.x

### Device/iOS version

iPhone and iPad

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6.1
Brave build: 1.69 (162)
BraveCore: 1.69.162 (128.0.6613.120)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Purchase `Leo` subscription > *Verify that `Premium` subscription is active*
3. Uninstall and reinstall Brave > Launch Brave
4. Go to `Leo` settings > Go Premium > Tap `Restore` > *Verify that subscription is restored*
5. Link active subscription to the `Web` > *Verify that linking is working*
6. Use another `iOS` device 
7. Fresh install or launch already installed Brave
8. Open `Leo` > *Verify that subscription is not restored automatically*
9. Now login to `account.brave.com` with the same email
10. Restore active subscription > Open `Leo` > *Verify that `Premium` subscription is active*

**ACTUAL RESULTS:**
- Verified that the `Leo` premium subscription can be purchased and activated on an `iOS` device.
- Observed an error message when restoring the `Leo` subscription on the same device where the subscription was purchased. 
- Verified that the `Leo` premium subscription was restored successfully after Brave relaunched on the same device.
- Observed `linking` issue similar to the one that filed for `VPN` #40860.
- Verified that active `Leo` subscription is not restored `automatically` on another device for the `existing` and `fresh` profiles/installs.

---------------------------

*Purchase `Leo` subscription*

https://github.com/user-attachments/assets/548e636e-ed01-4170-acf0-f5c95b7ea47f

*Restore and link `Leo` subscription*

https://github.com/user-attachments/assets/fd7d0114-b400-48f1-86e0-dc527ce94f3f

*`Automatic` restore on another device*

https://github.com/user-attachments/assets/b76b7924-520b-464e-8d75-40e2832eaddb
