### ISSUE TITLE
[Wallet] Show a preview when editing NFTs

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39549]
### Description

We should display a preview of the NFT updates when editing an NFT.

![Screenshot 2024-07-03 at 10 39 55 AM](https://github.com/brave/brave-browser/assets/30185185/aaf665da-be90-43f3-ba9e-1346efe515d3)

### Steps to reproduce

1. Navigate to the NFTs tab of the wallet portfolio
2. click the "more" (kabab) button on the NFT
3. click "edit"
4. adjust the form values

### Actual result

No preview of the edited NFT is shown

### Expected result

A preview of the edited NFT is shown

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.67.116 Chromium: 126.0.6478.71 (Official Build) (arm64) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

https://www.figma.com/design/mvoB5HzIyQT9O4vbcA1XhP/NFT-(Wallet-2.0)?node-id=1866-147900&m=dev

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.121 Chromium: 127.0.6533.57 (Official Build) beta (64-bit)
-- | --
Revision | 6ab76d6b98b9a4c22c06c9bb3487062edbbfb3f2
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description and [brave/brave-core#24470](https://github.com/brave/brave-core/pull/24470)
- Verified image preview is shown when editing NFT 

https://github.com/user-attachments/assets/ee2477cc-064b-4ea3-a505-94a82521e6a3
