### ISSUE TITLE
Remove suggested top sites on first start on Android

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#39541]
### Description

Slack Discussion: https://bravesoftware.slack.com/archives/C0816QH3R/p1720038297944829?thread_ts=1719641904.987839&cid=C0816QH3R

Follow up to https://github.com/brave/reviews/issues/1678#issuecomment-2204676303

Please update the logic on the Android NTP favicons to follow iOS.

On iOS, we have a set of bundled favicons that are shown initially. When the user first visits one of those websites, we pull in the favicon from the website.

### Steps to reproduce

1. NA
2. 
3. 

### Actual result

NA

### Expected result

NA

### Reproduces how often

Easily reproduced

### Brave version

NA

### Device

- Brand/model: 
- Android version: 

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by SergeyZhukovsky** [comment]
We actually want to remove pre-defined fav icons for now to avoid pings to thrid parties on initial start.

**Comment by kjozwiak** [comment]
The above requires `1.68.123` or higher for `1.68.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6 Pro` running `Android 15` using the following build(s):

```
Brave | 1.68.125 Chromium: 127.0.6533.57 (Official Build) (64-bit)
--- | ---
Revision | 14ff4d467fb3eec4e6fc0a2f3e2d3f7b4c8cb788
OS | Android 15; Build/AP31.240517.031; 35; REL
```

* ensured that the pre-determined websites based on region are not being populated via NTP on first launch
* ensured that there's no websites being displayed/being loaded when opening several NTP
* ensured that there's no connections to websites like `bestbuy.com`, `facebook.com` & `amazon.com` via `Proxyman`
* ensured that once you start visiting several websites, the most popular/visited ones get loaded into `Favorites`
* upgraded from `1.67.123 Chromium: 126.0.6478.126` -> `1.68.125 Chromium: 127.0.6533.57` and ensured that the previous `Favorites` under NTP weren't affected after upgrading

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|---------------
![Screenshot 2024-07-19 at 4 07 40 PM](https://github.com/user-attachments/assets/fea41f02-19ce-4f22-a5a0-c658df5e53a9) | ![Screenshot_20240719-160726](https://github.com/user-attachments/assets/5c1b1eda-7cad-4949-9e75-74aa1da4f194) | ![Screenshot_20240719-160731](https://github.com/user-attachments/assets/c70b55b0-fd98-4d3d-9b68-ce90c32023ce) | ![Screenshot_20240719-161213](https://github.com/user-attachments/assets/e502f6e2-4ffe-494c-bedb-3e80f8eedb0f)
