### ISSUE TITLE
Sync UI thread hangs

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#3954]
## Description 

A quite rare situation which I could see during work on https://github.com/brave/sync/pull/290 on 0.64.x `master` . After re-basing master to 0.65.x I could not see the issue .

Because I had not figured the reason, created the issue.

## Steps to Reproduce

1. Adjust computer time 15 minutes forward
2. Get empty profile
3. Run Brave browser
4. brave://sync, `Start a new Sync Chain`
5. Cancel
6. Close browser
7. Repeat pt3 for several times

## Actual result:
Sometimes UI hangs, and does not response on mouse and keyboards. 

## Expected result:
No hung.

## Reproduces how often: 

Intermittent issue

## Brave version (brave://version info)

Saw it on master 0.64.x, and could not repsoduce after migration to 0.65.x

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by JoelMon** [comment]
Can reproduce on Linux Mint using Version 0.64.30 Chromium: 73.0.3683.75 (Official Build) dev (64-bit).

When I try to remove a device from the sync chain it hangs. I recorded the problem. Can be seen [here](https://streamable.com/osvi0).

**Comment by AlexeyBarabash** [comment]
@JoelMon for the situation you had recorded, removing of the device can take up to 1 minute until sync will get confirmation from the server about removing of the device.

**Comment by AlexeyBarabash** [comment]
The original issue is not related to sync and was fixed on my Ubuntu 16 computer by disabling Nvidia proprietary drivers.
