### ISSUE TITLE
Sign Windows releases with a new codesigning certificate

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#39547]
Our current codesigning certificate expires in August 2024. We have therefore made changes on the infrastructure side to sign all future Windows releases (including 1.67.x) with a new certificate, which expires in August 2027.

This issue is there to document for QA that the change was made, and to please check that `brave.exe` and `chrome.dll` in Brave's installation directory are signed with a certificate that expires in August 2027, not 2024.

**Comment by LaurenWags** [comment]
Added to 1.67.x milestone per discussion here: https://bravesoftware.slack.com/archives/C0YL5KMA8/p1720014341926969?thread_ts=1720013340.713579&cid=C0YL5KMA8

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.67.131 Chromium: 126.0.6478.126 (Official Build) (64-bit)
-- | --
Revision | e3ca6babc88232bab25830c09164a034adae83bd
OS | Windows 10 Version 22H2 (Build 19045.4529)

```
- Verified the description from https://github.com/brave/brave-browser/issues/39547#issue-2388733172 and certificate expiration date on both `brave.exe` and `chrome.dll`
- Confirmed that the certificate expiration date is `August 2027` for `brave.exe` and `chrome.dll`

`brave.exe` | `chrome.dll` | `digital signature`
------------|---------------|-------------------
![image](https://github.com/brave/brave-browser/assets/38657976/0f8e3059-3226-46c0-967d-799dcc8c457f) | ![image](https://github.com/brave/brave-browser/assets/38657976/3c1ffac1-d137-406b-8f6a-8aae9845bdf9) | 
![image](https://github.com/brave/brave-browser/assets/38657976/7886ca14-5aed-46e3-9439-46c5d7fee609)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.67.131 Chromium: 126.0.6478.126 (Official Build) (32-bit) 
Revision	e3ca6babc88232bab25830c09164a034adae83bd
OS	Windows 10 Version 22H2 (Build 19045.4170)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using

```
Brave | 1.67.131 Chromium: 126.0.6478.126 (Official Build) (arm64)
-- | --
Revision | e3ca6babc88232bab25830c09164a034adae83bd
OS | Windows 11 Version 23H2 (Build 22631.3810)
```

- Verified the description from https://github.com/brave/brave-browser/issues/39547#issue-2388733172 and certificate expiration date on both brave.exe and chrome.dll
- Confirmed that the certificate expiration date is August 2027 for brave.exe and chrome.dll

brave.exe | chrome.dll | BraveBrowserStandaloneSetupArm64.exe
----- | ------ | ----
![image](https://github.com/brave/brave-browser/assets/98358127/6e31b3e1-81d0-42a9-a803-03c6c9e0a674)|![image](https://github.com/brave/brave-browser/assets/98358127/fd69149b-8d1d-48e4-98d2-9a7be79058b8)|![image](https://github.com/brave/brave-browser/assets/98358127/ee44473e-92b7-409e-933c-ae051c0cdba9)
