### ISSUE TITLE
Fix issues with RequestBlockingScript.js

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#39546]
### Description

The request blocking script does not emit all the required events that would normally get emitted if content was blocked using the content blocking manager. This causes issues with pages such as youtube forcing us to add a exception rule for youtube

### Steps to reproduce

1. Add a custom rule '||youtube.com/youtubei/v1/log_event?' (wait a few seconds for this to compile)
2. Click on many videos (maybe 50)  (you don't have to watch them just click on them)
3. Refresh the page

### Actual result

Page is stuck loading as youtube tries to dump its log queue (unsuccessfully) This happens on every refresh.

### Expected result

Page should have normal loading delay

### Reproduces how often

Easily reproduced

### Brave version

1.66

### Device/iOS version

iOS device (not iPad)

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6.1
Brave build: 1.69 (162)
BraveCore: 1.69.162 (128.0.6613.120)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/39546#issue-2388722495
2. *Verify*

**ACTUAL RESULTS:**
- Verified that YT page is loading with normal delay when refreshing the page after watching a lot of videos (~50)

---------------------------

*Reproduced in `1.68.1.145`*

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/8a10fc8e-fe76-4661-8504-6fd3976216ef) | ![2](https://github.com/user-attachments/assets/347f2807-5471-42ec-83d2-7c89f5f19f06) |

*Verified in `1.69.162`*

https://github.com/user-attachments/assets/4594ed9d-a45d-4f10-8b14-a4ddd88ed433
