### ISSUE TITLE
Linux doesn't list Widevine component module in brave://components

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3955]
## Description 

Linux doesn't list Widevine component module in brave://components

## Steps to Reproduce

   1. Install latest dev version
   2. Login to Netflix
   3. Click Allow on both prompts to instal, run and restart browser
   4. Play any video on Netflix after restart
   5. Open brave://components, Widvine component is not listed 

## Actual result:

![linux-widevine](https://user-images.githubusercontent.com/17010094/55327440-1fddde00-5458-11e9-9188-99a7a1257b17.gif)

## Expected result:
Should list it similar to Windows/macOS

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.64.30 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes 
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A
### Additional Information

cc: @simonhong

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.20.86 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Ubuntu 18.04 LTS

Verified test plan from the description. Verified Verified widevine is available from `brave://components` after widevine installation
![image](https://user-images.githubusercontent.com/34715963/105394642-21c0f480-5c1e-11eb-9d13-b522b328c21b.png)


Verified test plan from https://github.com/brave/brave-core/pull/7228
**Test with clean profile**
Verified widevine is not available from `brave://components` on clean profile
![image](https://user-images.githubusercontent.com/34715963/105392923-0ead2500-5c1c-11eb-84ad-d0ea554ce55c.png)
Verified widevine is available from `brave://components` after installation
![image](https://user-images.githubusercontent.com/34715963/105393445-a579e180-5c1c-11eb-8a0e-320fbac1cea7.png)
Verified able to watch netflix:
![image](https://user-images.githubusercontent.com/34715963/105393273-71062580-5c1c-11eb-9f87-771260ef7ee8.png)

**Test with old profile(widevine enabled)**
Verified widevine is available from brave://components and it's version is 4.10.1610.0
![image](https://user-images.githubusercontent.com/34715963/105394280-ad865100-5c1d-11eb-8020-ea7e517a4aab.png)
Verified able to watch netflix:
![image](https://user-images.githubusercontent.com/34715963/105394357-c262e480-5c1d-11eb-9fe3-9f719da6518b.png)

**Comment by LaurenWags** [comment]
Changed to `release-notes/exclude` as this is covered under https://github.com/brave/brave-browser/issues/7081 which will be included in 1.20.x release notes
