### ISSUE TITLE
Edit custom search engines

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-browser#39552]
### Description

We dont have edit functionality for custom search engines. We have add and delete but there is edit. This issue is mentioned in ios channel, creating a follow up issue. 

The Add screen can be used for Edit functionality and swipe action can be added next to delete swipe action.

### Steps to reproduce

1. Open Settings - SearchEngines
2. Try to edit a custom search Engine

### Actual result

The custom search engines are editable.

### Expected result

They should be editable and the functionality should be added to swipe actions. 

![2123321](https://github.com/brave/brave-browser/assets/6643505/4a7d6c8c-5e79-4ead-980c-931348711bfd)

### Reproduces how often

Easily reproduced

### Brave version

1.67

### Device/iOS version

Any

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `iPhone 14` and `iPad Mini (6th gen)` using version(s):
```
Device/OS:
- iPhone 14 / iOS 17.7
- iPad Mni (6th gen) / iPadOS 18
Brave build: 1.70 (117)
BraveCore: 1.70.117 (129.0.6668.59)
```
Filed follow-up issue #41210 and #41228
---------------------------

**STEPS:**
1. Launch Brave 
2. Hamburger menu > Settings
3. Search Engines > Add Custom Search Engine
4. In URL type `https://youtube.com/search?q=%s` and in Title type `YT` > Done
5. Slide the newly created SE to the left > *Verify `Edit` button exists*
6. Tap `Edit` > Update the URL / Title > Save the changes by tapping the button in the top right corner

**ACTUAL RESULTS:**
- Verified that the `Edit` button is shown for the custom SE.
- Verified that the custom SE can be edited by tapping the `Edit` button.
- Verified that no regression happened: custom SE can be set as default for `Standard` / `Private` tabs, and search results are shown with that SE.

---------------------------

`iPad Mni (6th gen) / iPadOS 18`

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/8710ed32-d6f6-4530-a4a5-f32529450f3e) | ![2](https://github.com/user-attachments/assets/ef558964-3728-4da3-a10f-0c4442f1a6d3) | ![3](https://github.com/user-attachments/assets/e9da30ba-14d7-4b16-b0f0-c1f0aa729c72) | ![4](https://github.com/user-attachments/assets/39f78fc2-a491-4e31-bf3e-3da7c8547c9f) | ![5](https://github.com/user-attachments/assets/d0ab44de-9474-42f8-8ed5-2921122f8505) |
