### ISSUE TITLE
Apply custom filter list exceptions to standard list

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#39564]
### Description

We want exceptions for custom rules to apply to the standard engine

### Steps to reproduce

1. Add an exception for a known rule in the standard engine in the text filter list
2. Load the page that will execute the exception

### Actual result

Exception will not apply

### Expected result

Exception will apply

### Reproduces how often

Easily reproduced

### Brave version

1.68

### Device/iOS version

Any

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

You can test on one of the youtube youtube rules:
```
@@||youtube.com/api/stats/qoe?
```

**Comment by Uni-verse** [comment]
In progress on iPhone 12 running iOS 18 using version 1.70.119

**Test Plan:** 

- [ ] Test scriplets: `https://dev-pages.brave.software/filtering/scriptlets.html`
- [ ] Test additional lists: `://dev-pages.brave.software/filtering/additional-lists.html`
- [ ] Test standard vs aggressive: `https://dev-pages.bravesoftware.com/filtering/text-ads.html`
- [ ] Test cosmetic filtering: `https://dev-pages.bravesoftware.com/filtering/cosmetic-filtering.html`
