### ISSUE TITLE
[CR127] Toolbar UI regressions

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#39565]
### Description

* Toolbar button's hover/pressed color is changed after cr127 bump.
Inner window is cr127 and outer is cr126.
Also button size is bigger than cr126.

<img width="316" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/d2d10d02-8520-444f-8fc7-66c8d6a77fed">

* Also there is a separator between extensions container and other toolbar buttons. It should be hidden.
<img width="398" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/d2462833-a9ca-4457-9268-9f2bdc008f2d">

### Steps to reproduce

1. Launch browser and click any toolbar button
2. Install some extensions and check seperator is shown
3. 

### Actual result

See above screenshot(inner window's color)

### Expected result

See above screenshot(outer window's color)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.76 Chromium: 127.0.6533.26 (Official Build) nightly (x86_64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @brave/qa-team

**Comment by jagadeshjai** [comment]
Info: Upstream cleaned up the Chrome Refresh 23 flag, which caused the toolbar separator to appear after the extension button. However, as far as I know, we disabled the Chrome Refresh 23 flags a while ago, so we didn't notice this change.

Therefore, my question is whether we want to keep this separator from now on or not.

![image](https://github.com/brave/brave-browser/assets/45998266/b42f2c23-5af9-43fb-b370-3e4dfcad8eb1)

Reference: https://chromium-review.googlesource.com/c/chromium/src/+/5541688 - chrome/browser/ui/views/toolbar/toolbar_view.cc

**Comment by simonhong** [comment]
> Info: Upstream cleaned up the Chrome Refresh 23 flag, which caused the toolbar separator to appear after the extension button. However, as far as I know, we disabled the Chrome Refresh 23 flags a while ago, so we didn't notice this change.
> 
> Therefore, my question is whether we want to keep this separator from now on or not.
> 
> ![image](https://private-user-images.githubusercontent.com/45998266/346419753-b42f2c23-5af9-43fb-b370-3e4dfcad8eb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MTExNzcsIm5iZiI6MTcyMDQxMDg3NywicGF0aCI6Ii80NTk5ODI2Ni8zNDY0MTk3NTMtYjQyZjJjMjMtNWFmOS00M2ZiLWIzNzAtM2U0ZGZjYWQ4ZWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAzNTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4Y2UwOGNmNTY5YWE2MzAyZGYxOTczYWY3Y2QyN2RlYWMzYWQ4MDYyNWRjMjYwYjQ5ODUzMjQzODA4OTcyODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q2DBLqQj6dmhIpx5IXchx_MCAQm_rHmdC_TyH4wHaHc)
> 
> Reference: https://chromium-review.googlesource.com/c/chromium/src/+/5541688 - chrome/browser/ui/views/toolbar/toolbar_view.cc

Our design doesn't use that divider. It'll be hidden by https://github.com/brave/brave-core/pull/24521

**Comment by jagadeshjai** [comment]
> Our design doesn't use that divider. It'll be hidden by [brave/brave-core#24521](https://github.com/brave/brave-core/pull/24521)

Okay, Got it :+1:

**Comment by kjozwiak** [comment]
The above requires `1.68.117` or higher for `1.68.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.68.117 Chromium: 127.0.6533.26 (Official Build) beta (x86_64)
-- | --
Revision | 80857ef16345e7959abe655afdebf9521f5109aa
OS | macOS Version 13.6.7 (Build 22G720)
```
