### ISSUE TITLE
Location bar button is not squircle when permission bubble is shown 

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#39561]
### Description

`Get notifications?` button doesn't have our radius and bg color

![image](https://github.com/brave/brave-browser/assets/6786187/76c9eee6-d030-4772-af35-70ede2670ec6)

Left(cr127) vs. right(cr126)
![image](https://github.com/brave/brave-browser/assets/6786187/0841cb9f-a702-440c-bd52-e7f77adc0ec8)

### Steps to reproduce

1. Load https://www.bennish.net/web-notifications.html
2. Click `Authorize`
3. 

### Actual result

See the above screen shot

### Expected result

It should have our radius and bg color
<img width="168" alt="Screenshot 2024-07-04 at 11 00 31 AM" src="https://github.com/brave/brave-browser/assets/6786187/e4adbbfe-e014-4ca3-bfd1-df5dfc31e943">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.76 Chromium: 127.0.6533.26 (Official Build) nightly (x86_64) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Note: stable/beta 's bg color seems fine. nightly has different bg color.
cc @rebron @brave/qa-team

**Comment by simonhong** [comment]
checking now.

**Comment by kjozwiak** [comment]
The above requires `1.68.118` or higher for `1.68.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.68.118 Chromium: 127.0.6533.26 (Official Build) beta (x86_64)
-- | --
Revision | 2863b4f7f2c566e828c816caafbc2a2ce5fb527f
OS | macOS Version 13.6.7 (Build 22G720)
```
