### ISSUE TITLE
Parsing of Onion-Location header is different from Tor Browser

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#39578]
### Description

The [specification for the `Onion-Location` header](https://gitlab.torproject.org/tpo/applications/tor-browser-spec/-/blob/HEAD/proposals/100-onion-location-header.txt) is unclear about two points:
- How to handle multiple copies of the `Onion-Location` header.
- Whether the header or the `<meta>` tag takes precedence.

### Steps to reproduce

Look at the following test pages which demonstrate the problem:
- https://fmarier.org/test/onion-location1.html
- https://fmarier.org/test/onion-location2.html

### Actual result

In Brave, we only look at the first value and use that. The header takes precedence.

### Expected result

The Tor Browser merges all header values together (separated by `", "` (without the quotes) and uses that as the URL. The `<meta>` tag takes precedence.

We should match the Tor browser since it is the de-facto reference implementation, but we should check upstream whether that's the intended behavior.

### Reproduces how often

Always

### Brave version (brave://version info)

```
Brave	1.68.110 Chromium: 127.0.6533.26 (Official Build) beta (64-bit) 
Revision	83a08b66c8afbf78547e2acc7b3a7ebb962f359b
OS	Linux
```

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

**Comment by fmarier** [comment]
I have opened an issue upstream: https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/42688

**Comment by fmarier** [comment]
https://github.com/brave/brave-browser/issues/21048 is tracking adding support for the `<meta>` tag which appears to be [slightly less popular than the header](https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/42688#note_3048597).

**Comment by fmarier** [comment]
For the release notes:

> Parse the `Onion-Location` header like the `Location` header.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.70.37 Chromium: 127.0.6533.73 (Official Build) nightly (64-bit)
-- | --
Revision | 8556062edfbbe9023221ddaca3b6fe81264238c8
OS | Windows 10 Version 22H2 (Build 19045.4717)
```

### Steps:
1 .Open https://fmarier.org/test/onion-location1.html and ensure that clicking the .onion button in the URL bar takes you to the following 404 page on Brave's website:
`https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/index.html,http:/ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion/`

and not any of these:

`https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/`
`https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/index.html`,`http://ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion,%20https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/`
`https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/`
