### ISSUE TITLE
Hovering over `Follow` button makes it extend, horizontally

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#39576]
### Description

Hovering over `Follow` button makes it extend, horizontally

(Probably `Nala`-related?)

### Steps to reproduce

1. install `1.69.80`
2. launch Brave
3. open a new-tab page
4. opt in to Brave News
5. load `nbcnews.com`
6. click on the `Manage Subscriptions` button in the browser toolbar
7. hover over the `Follow` button

### Actual result

The `Follow` button's hover-effect grows or extends the button, horizontally

default | on-hover
--------|---------
<img width="336" alt="Screen Shot 2024-07-04 at 3 05 17 PM" src="https://github.com/brave/brave-browser/assets/387249/5aec1ae6-7748-47ae-9273-68493369f143"> | <img width="331" alt="Screen Shot 2024-07-04 at 3 05 25 PM" src="https://github.com/brave/brave-browser/assets/387249/71b99f85-860d-4aed-b14e-0545f3ae72d1">

### Expected result

It's still correct in `1.67.123`

default | on-hover
--------|--------
<img width="318" alt="Screen Shot 2024-07-04 at 3 05 47 PM" src="https://github.com/brave/brave-browser/assets/387249/d23b97f1-914a-4bb0-b7e7-e4e08a563bb8"> | <img width="316" alt="Screen Shot 2024-07-04 at 3 05 54 PM" src="https://github.com/brave/brave-browser/assets/387249/e1266f0a-fa74-4664-87aa-748635294f2f">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.69.80 Chromium: 127.0.6533.26 (Official Build) nightly (x86_64)
-- | --
Revision | 836aaabe7fef6db341d61b863d02c5eca5625b2d
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @fallaciousreasoning @brave/qa-team

**Comment by stephendonner** [comment]
![news-extend](https://github.com/brave/brave-browser/assets/387249/253041e4-eba8-4b2a-bf72-3cd9508e5fe5)

**Comment by stephendonner** [comment]
Another problem, shown above, is that the text of the `Unfollow` button gets ghosted as white on white, until you reload that dialog.  Probably related to Nala/styles.

**Comment by fallaciousreasoning** [comment]
This one might be related to the Chromium bump :cry:

**Comment by simonhong** [comment]
Also button is not clickable after clicking follow/unfollow button. It becomes clickable after relaunching news bubble. checking it too.

**Comment by kjozwiak** [comment]
The above requires `1.68.117` or higher for `1.68.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.68.117 Chromium: 127.0.6533.26 (Official Build) beta (64-bit)
-- | --
Revision | 80857ef16345e7959abe655afdebf9521f5109aa
OS | Windows 10 Version 22H2 (Build 19045.4651)
```


https://github.com/brave/brave-browser/assets/387249/edab7613-ee8f-4c34-a6c8-5343556e4ae9
