### ISSUE TITLE
Wallet creation does not complete correctly when selecting all available networks

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#39572]
### Description

When creating a new Wallet for the first time the creation does not complete correctly if a user selects all the available networks (including test networks). 
The Wallet creation screen will display the loading spinner endlessly.

<img src="https://github.com/brave/brave-browser/assets/3308503/9c47fea2-dd95-460b-b7c2-bf778d8d8f61" width=500 />

### Steps to reproduce

1. Clear previous Wallet data, if any.
2. Navigate to Wallet section to trigger onboarding flow.
3. Follow the instructions and when required select all the available networks, including test networks.
4. Observe the creation screen will remain stuck at the loading spinner.

### Reproduces how often

Easily reproduced

### Brave version

n/a

**Comment by kjozwiak** [comment]
The above requires `1.67.131` or higher for `1.67.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.67.131 x64 build
- Verified steps from [brave/brave-core#24506](https://github.com/brave/brave-core/pull/24506)
- Verified selecting all available networks and continue, completes the onboarding 
- Verified for both new wallet creation and restore wallet
