### ISSUE TITLE
[iOS] Per-site adblocking setting is all-or-nothing

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#39573]
### Description

We let users choose between the following adblocking modes in the global Shields settings menu:
1. Standard (default, 1p exception policy)
2. Aggressive/Strict (no 1p exception policy)
3. Off

However, on per-site Shields, we only let users choose between off and on.

### Steps to reproduce

1. Open per-site Shields on iOS
2. Click Advanced
3. See adblocking setting

### Actual result

It's a boolean toggle

### Expected result

It should be a 3-way toggle. 
Global default should be respected until user makes a selection.

### Reproduces how often

Easily reproduced

### Brave version

All

### Device/iOS version

All

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by Uni-verse** [comment]
In progress on `iPad (7th Gen)` running `iPadOS 17.5.1` using version `1.69 (150)`

**Test Case: Migration (standard)**

<details>

1. Installed 1.68.141
2. Confirmed `Trackers & Ads Blocking` is set to `Standard` by default
3. Navigated to webpage, open the Shields Panel to confirm that boolean toggle state is ON
4. Upgraded to 1.69 (150)
5. Verified `Standard` setting is retained in global settings
6. Verified `Ads Blocking` is set to `Standard` for the per site in Brave Shields
7. Verified webpage & embedded video ads are blocked after migration in aggressive mode
8. Verified changing per site setting
9. Verified `Ads Blocking` are showing the correct value in Shields panel in Private mode

1.68 | 1.68 | 1.69 | 1.69 | YT | Private Tab
-|-|-|-|-|-
![IMG_1583 2](https://github.com/user-attachments/assets/0e101f60-ffe1-4b20-8255-ba0b9b4cfe8a) | ![IMG_1584 2](https://github.com/user-attachments/assets/96895fec-e8dc-456f-8669-d2804975fee9) | ![IMG_1585 2](https://github.com/user-attachments/assets/e124f7dc-c3cb-4215-abc9-404cbc69f60a) | ![IMG_1586 2](https://github.com/user-attachments/assets/041f8a2b-fced-492d-bdfb-3cf1060a11fc) | ![IMG_1587 2](https://github.com/user-attachments/assets/db5e573d-a4c0-4654-aa33-82672dd002c0) | ![IMG_1588](https://github.com/user-attachments/assets/dc42c409-d0ac-48e7-ab79-8bc19088c063)

</details>

**Test Case: Migration (aggressive)**

<details>

1. Installed 1.68.141
2. Set Trackers & Ads Blocking to Aggressive mode in Brave Shields & Privacy
3. Navigated to webpage, open the Shields Panel to confirm that boolean toggle state
4. Upgraded to 1.69 (150)
5. Verified `Aggressive` setting is retained in global settings
6. Verified `Ads Blocking` is set to `Aggressive` for the per site in Brave Shields
7. Verified webpage & embedded video ads are blocked after migration in aggressive mode

1.68 | 1.68 | 1.69 | 1.69
-|-|-|-
![IMG_1572 2](https://github.com/user-attachments/assets/d59695be-9f95-4f79-8926-09d3ef8295e7) | ![IMG_1573 2](https://github.com/user-attachments/assets/0ccc88a0-f1c2-433f-904a-67e2ec29454e) | ![IMG_1574 2](https://github.com/user-attachments/assets/3ebe4475-98f2-42bc-9eb2-b43d860e7ad0) | ![IMG_1575 2](https://github.com/user-attachments/assets/81d72fca-d8d3-41a6-a9ef-e78b1b9cdb34)

</details>

**Test Case: Migration (disabled)**

<details>

1. Installed 1.68.141
2. Set `Trackers & Ads Blocking` to `Disabled` mode in Brave Shields & Privacy settings
3. Navigated to webpage, open the Shields Panel to confirm that boolean toggle state is OFF
4. Upgraded to 1.69 (150)
5. Verified `Disabled` setting is retained in global settings
6. Verified `Ads Blocking` is set to `Disabled` for the per site in Brave Shields
7. Verified ads are being shown on websites.

1.68 | 1.69 | YT (ads)
-|-|-
![IMG_1579](https://github.com/user-attachments/assets/8a298311-44be-40ba-b94b-fcc70b40f6c4) | ![IMG_1581](https://github.com/user-attachments/assets/1c2626ff-c1f1-4939-bc22-c2a288e85b7a) | ![IMG_1582](https://github.com/user-attachments/assets/4588d15a-e979-465c-9b77-06c285b27f21)

</details>

**Test Case: Migration (Shields down)**

**Test Case: Migration (Per site selection)**

**Test Case: New Install**

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.69 (153)`

**Test Case: Migration (standard)**

<details>

1. Installed 1.68 (141)
2. Confirmed `Trackers & Ads Blocking` is set to `Standard` by default
3. Navigated to webpage, open the Shields Panel to confirm that boolean toggle state is ON
4. Upgraded to 1.69 (153)
5. Verified `Standard` setting is retained in global settings
6. Verified `Ads Blocking` is set to `Standard` for the per site in Brave Shields
7. Verified webpage & embedded video ads are blocked after migration in aggressive mode
8. Verified changing per site setting
9. Verified `Ads Blocking` are showing the correct value in Shields panel in Private mode

1.68 | 1.69 | 1.69 | Private Mode | Media Site 1 | Media Site 2
-|-|-|-|-|-
![IMG_7095](https://github.com/user-attachments/assets/16bcc92c-ad49-4f5f-ae60-1326ed3fbb88) | ![IMG_7096](https://github.com/user-attachments/assets/c1293e2c-ce66-4d1b-9860-9314f0b4ac34) | ![IMG_7097](https://github.com/user-attachments/assets/74d90f96-c36c-4471-92e2-a67bc63d0f85) | ![IMG_7098](https://github.com/user-attachments/assets/0fc883cd-2e10-43e6-9e0d-c1195709b3b2) | ![IMG_7099](https://github.com/user-attachments/assets/7cb46189-c04c-495c-9986-a3f050e26822) | ![IMG_7100](https://github.com/user-attachments/assets/16717d6d-5d7e-4874-a2a9-05bf759a0830)

</details>

**Test Case: Migration (aggressive)**

<details>

1. Installed 1.68 (141)
2. Set Trackers & Ads Blocking to Aggressive mode in Brave Shields & Privacy
3. Navigated to webpage, open the Shields Panel to confirm that boolean toggle state
4. Upgraded to 1.69 (153)
5. Verified `Aggressive` setting is retained in global settings
6. Verified `Ads Blocking` is set to `Aggressive` for the per site in Brave Shields
7. Verified webpage & embedded video ads are blocked after migration in aggressive mode

1.68 | 1.68 | 1.69 | YT
-|-|-|-
![IMG_7102](https://github.com/user-attachments/assets/9debad67-29a9-4d5b-8ae2-6a1bc4df4f54) | ![IMG_7103](https://github.com/user-attachments/assets/40de37f1-dcf6-43eb-9ce7-0050b3465997) | ![IMG_7104](https://github.com/user-attachments/assets/dbf2b252-3e83-41b9-828d-81477fd1e80a) | ![IMG_7105](https://github.com/user-attachments/assets/b2b1b1db-7971-4d7b-b62a-21363f59a956)

</details>

**Test Case: Migration (disabled)**

<details>

1. Installed 1.68.141
2. Set `Trackers & Ads Blocking` to `Disabled` mode in Brave Shields & Privacy settings
3. Navigated to webpage, open the Shields Panel to confirm that boolean toggle state is OFF
4. Upgraded to 1.69 (153)
5. Verified `Disabled` setting is retained in global settings
6. Verified `Ads Blocking` is set to `Disabled` for the per site in Brave Shields
7. Verified ads are being shown on websites.

1.68 | 1.69 | YT (ads)
-|-|-
![IMG_7106](https://github.com/user-attachments/assets/b57dffaf-4b4d-4c68-8c60-7853cffcb2b0) | ![IMG_7107](https://github.com/user-attachments/assets/442978a4-140d-42e8-96e1-d2b3a8559923) | ![IMG_7108](https://github.com/user-attachments/assets/f9a854ec-6916-4627-8c14-211c0f304fa0)


</details>

**Test Case: Migration (Shields down)**

<details>

1. Installed 1.68.141
2. Opened a website
3. Disabled Shields in the panel
4. Upgraded to 1.69.153
5. Confirmed Shields are disabled for the webpage
6. Confirmed Shields can be enabled after upgrading
7. Confirmed the Ads Blocking settings have not changed

</details>

**Test Case: Migration (Per site selection)**

<details>

1. Installed 1.68.141
2. Opened a webpage
3. Changed global ad-blocking to `Aggressive`
4. Disabled ads-blocking in Shields panel for one webpage
5. Opened another webpage and leave the settings as is but disable fingerprint protection
6. Upgraded to 1.69.153
7. Confirmed global ads blocking setting is set to `Aggressive`
8. Confirmed ads-blocking is disabled for webpage in step 4
9. Confirmed that ads-blocking is set aggressive mode for the other site
10. Confirmed fingerprint protection setting is retained for other site.

1.68 | 1.69 | 1.69
-|-|-
![IMG_7109](https://github.com/user-attachments/assets/0b400456-19f1-4a16-b1c1-e647c5459494) | ![IMG_7110](https://github.com/user-attachments/assets/db943245-2339-45a2-9306-717166a4a881) | ![IMG_7111](https://github.com/user-attachments/assets/b46c472d-0987-4546-9e0b-db2ff1514ac2)

</details>

**Test Case: New Install**

<details>

1. Installed 1.69.153
2. Confirmed `Trackers & Ads Blocking` is set to `Standard`
3. Confirmed opening Brave Shields on a webpage will show a dropdown for `Trackers & Ads Blocking` settings
4. Ensured that changing per site ads blocking setting doesn't override globals
5. Ensured that global settings apply to new sites being opened.
6. Ensured that ads are blocked on YouTube and other media sites when `Trackers & Ads Blocking` is enabled.
11. Ensured that Shields panel UI for ad-blocking settings has not regressed in different modes.

Example | Light Mode | Dark Mode | Private Mode
-|-|-|-
![IMG_7086](https://github.com/user-attachments/assets/819bf281-de73-4419-81e0-886c3a613f47) | ![IMG_7086](https://github.com/user-attachments/assets/1e02edb0-6760-4d61-a74b-89364c48b4aa) | ![IMG_7087](https://github.com/user-attachments/assets/38b4e937-ebc0-4075-83a2-823972b27cd0) | ![IMG_7088](https://github.com/user-attachments/assets/3ba03fec-41be-479c-b327-2a967561c18c)

</details>

**Shield Test Pages**

<details>

- Ensured all of the Shields test pages were passed successfully which are mentioned in https://github.com/brave/brave-browser/issues/38384#issue-2301235075

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_7089](https://github.com/user-attachments/assets/a2b3c273-ed69-4be4-aba1-954e6c969232) | ![IMG_7090](https://github.com/user-attachments/assets/c4651996-3cae-4ff1-8bbf-46bd9e53a01c) | ![IMG_7091](https://github.com/user-attachments/assets/40fd4653-ee00-4fdc-8c12-2651aa051d41) | ![IMG_7092](https://github.com/user-attachments/assets/ea1087e2-a564-44ba-95b1-4c77145078cf) | ![IMG_7093](https://github.com/user-attachments/assets/672da348-c45e-4301-a427-3a4bfa7a9dcb) | ![IMG_7094](https://github.com/user-attachments/assets/b98179c1-d1a9-42f4-a0fa-d67270e1fb87)

</details>
