### ISSUE TITLE
Remove branch.io fingerprint ID from URLs

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#39575]
[Branch.io](https://branch.io) uses the `_branch_match_id` URL parameter to [identify individual users](https://stackoverflow.com/a/37892369). It's described in their [official documentation](https://help.branch.io/developers-hub/docs/connected-troubleshooting#branch-init-options) as:

> The current user's browser-fingerprint-id.

Here are some example URLs:
- `https://www.reddit.com/r/perplexity_ai/comments/1dsy4uj/i_compared_top_ai_search_engines_chatgpt/?%24deep_link=true&correlation_id=128c4378-a112-407c-a776-71a303e2681e&post_fullname=t3_1dsy4uj&post_index=0&ref=email_digest&ref_campaign=email_digest&ref_source=email&_branch_referrer=H4sIAAAAAAAAA21Q0WrDMAz8muwtaWNnTRmUMRj7DSFsNdHm2MZWaPv3U9atTwMbTnc%2BneRZJNeX3a6Q9ywd5twFjl87m18bM9h8IsD6pDAVnjhigLWE07y5GvvWmA89l8ul%2B%2FW7tChR9GYqOdCV5QbIWquyUJSqsPf1NqyfihiUzqhmkJT1IVTC4magqGFUwc0oUxZ4dNsSrYY%2Bm8ETZdiGbey7lJUac3CpFAoonCKwV743RzfY8dhi35t22I%2BuxXE8tGOPdm%2FJHI795supCpzXECIutLWz8BjyLnL0dFVlr0ShsyJakAN4nqjKnQSHugxP8X%2B1prU4%2BtOUXGXR%2FaPotyj7EyMsgb4ByBGkYpQBAAA%3D&%243p=e_as&_branch_match_id=1214926959150458150`
- `https://www.reddit.com/r/todoist/comments/qbd4us/are_the_comments_in_completed_tasks_ever_deleted/?%24deep_link=true&correlation_id=52bb407f-56e1-41f6-a57b-ab3ed7ea9dab&post_fullname=t3_qbd4us&post_index=1&ref=email_digest&ref_campaign=email_digest&ref_source=email&%243p=e_as&_branch_match_id=961625680547054001`

There is also a `_branch_referrer` parameter which [appears to contain an encoding of the original URL](https://www.tumblr.com/glenthemes/697514548282949632/tumblr-is-tracking-shared-links) and could be leaking more information than the `Referer` header.

Both are also [removed by _Copy clean link_](https://github.com/brave/adblock-lists/pull/1865).

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.69.88 Chromium: 127.0.6533.26 (Official Build) nightly (x86_64)
-- | --
Revision | d60303973dc3604d9d348b981322a8a04dcbb86d
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.69.88`
2. launched Brave
3. opened `Developer Tools`
4. clicked on `Persist logs`
5. copied and entered `https://brave.com/?_branch_match_id=12345&foobar&_branch_referrer=abcdef` into the URL bar
6. pressed `return`

### Confirmed I was navigated to `https://brave.com/?foobar`

<img width="1844" alt="Screen Shot 2024-07-08 at 2 19 55 PM" src="https://github.com/brave/brave-browser/assets/387249/46c3ceed-3c72-4216-9bef-fcff31fd3e8f">

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP31.240617.010 release-keys
Brave build: 1.69.129
Chromium: 127.0.6533.73 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/24515#issue-2391460002
2. *Verified*

**ACTUAL RESULTS:**
- Verified that `_branch_*` is removed when navigating to `https://brave.com/?_branch_match_id=12345&foobar&_branch_referrer=abcdef`
- Verified that the URL bar shows `https://brave.com/?foobar` only

---------------------------

|1|
|:-:|
| ![1](https://github.com/user-attachments/assets/4f7261f5-5aa2-4460-ad20-382e680fdc95) |
