### ISSUE TITLE
[CR127] Infobar background color is not aligned with toolbar

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#39580]
### Description

Infobar's background color should be same with toolbar' bg color.

![Screenshot 2024-07-05 110852](https://github.com/brave/brave-browser/assets/6786187/3d6058a8-4d7d-4a61-ad8e-649ae09a81b0)
![Screenshot 2024-07-05 110841](https://github.com/brave/brave-browser/assets/6786187/9f349993-b098-4e77-aefd-58e5aa2bcb09)

### Steps to reproduce

1. Load any site
2. Delete cookie for that site
3. `Reload` infobar should be shown
4. Check that infobar's background color

### Actual result

See the screenshot

### Expected result

![Screenshot 2024-07-05 111249](https://github.com/brave/brave-browser/assets/6786187/3fd5f46d-971c-43d8-a22f-42c651e34db1)
![Screenshot 2024-07-05 111301](https://github.com/brave/brave-browser/assets/6786187/61ddd5a3-729c-4699-9f2e-4ce56eebcded)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.110 Chromium: 127.0.6533.26 (Official Build) beta (64-bit) 
1.69.80 Chromium: 127.0.6533.26 (Official Build) nightly (64-bit) 

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @brave/qa-team

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.68.117 Chromium: 127.0.6533.26 (Official Build) beta (x86_64)
-- | --
Revision | 80857ef16345e7959abe655afdebf9521f5109aa
OS | macOS Version 13.6.7 (Build 22G720)
```
