### ISSUE TITLE
"Ad notifications received" should show Ads viewed between the 1st of the month and the 4th of the following month

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#3958]
## Description
"Ad notifications received" should show Ads viewed between the 1st of the month and the 4th of the following month which after further investigation is caused by the date range calculated in `RewardsServiceImpl::GetEarningsRange()`

## Steps to Reproduce
   1. Set your devices date to the 6th of the month
   2. Launch the browser
   3. View several Ads
   4. Quit the browser
   5. Set your devices date to the 1st of the following month
   6. Launch the browser
   7. Visit brave://rewards

## Actual result:
"Ad notifications received" does not match the amount of Ads viewed

## Expected result:
"Ad notifications received" should match the amount of Ads viewed

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
0.63 and above

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? YES

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional Information
Date range is calculated in `RewardsServiceImpl::GetEarningsRange()`

**Comment by mandar-brave** [comment]
@tmancey prioritized

**Comment by JoelMon** [comment]
Happens to me with Version 0.64.30 Chromium: 73.0.3683.75 (Official Build) dev (64-bit).

The bug happens with me when I close and open the browser or when I turn off ads reward and turn it back on.
You can see the screen recording of the bug [here](https://streamable.com/ekvlv) sorry for the poor resolution.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.45 Chromium: 74.0.3729.75 (Official Build) beta(64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Mac OS X

* Verified STR from description. Verified ads viewed on the 6th were still showing on Ads panel on the 1st of following month. Verified when an Ad was viewed on the 1st it was added to the Ads panel appropriately.
