### ISSUE TITLE
update `Default model for new conversions` via `Leo` settings - follow up to 36994

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#39594]
### Description

As mentioned via https://github.com/brave/brave-browser/issues/36994#issue-2200813802, `Default model for new conversions` should be changed/renamed to `Default Mode`.

### Steps to reproduce

1. download/launch `1.69.83 Chromium: 127.0.6533.26` via TF
2. once installed, open `Leo` via the `Hamburger Menu`
3. run through the onboarding/T&S and then go into `Advances Settings` via the `Hamburger Menu`

### Actual result

![image](https://github.com/brave/brave-browser/assets/2602313/60a1b572-8277-4267-b1f9-105b4616feaf)

### Expected result

![image](https://github.com/brave/brave-browser/assets/2602313/4c0395b5-da5b-497e-927e-fffd5eab4e1d)

### Reproduces how often

Easily reproduced

### Brave version

```
Brave | 1.69.83 Chromium: 127.0.6533.26 (Official Build) nightly (64-bit) 
--- | ---
Revision | 82eef43ce82a...
OS | iOS
```

### Device/iOS version

* `iPhone 11` running `iOS 17.5.1`

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.68.116` or higher for `1.68.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.68.117`

- Ensured that `Default model for new conversions` is changed/renamed to `Default Model` in advanced settings.
- Ensured tapping on the settings will show the default models page.

Example | Example
-|-
![IMG_6742](https://github.com/brave/brave-browser/assets/17885425/009648c0-318e-4b4b-b862-70c3266abeaa) | ![IMG_6743](https://github.com/brave/brave-browser/assets/17885425/342eaf8e-883e-4f9b-b344-4cd95cf9b90e)
