### ISSUE TITLE
Prepare for dev release

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#396]
### Windows
- [x] Silent installer for dev (can install `mini_installer --chrome-dev`)
- [x] Windows installer for dev build
- [x] dev update from server

### MacOS
- [x] Check different install location is used for each channel (https://github.com/brave/brave-core/pull/208)
- [x] dev channel update from server
- [x] Enable update from about webui

### Linux
- [x] Update icon(https://github.com/brave/brave-core/pull/205)
- [x] Check packaging is done for each channel
- [x] Add nightly channel (https://github.com/brave/brave-core/pull/205)

### Resources
- [x] Missing resources in installer - https://github.com/brave/brave-browser/issues/449

### Apply brave version (https://github.com/brave/brave-browser/issues/553)
  - [x] Windows
  - [x] Mac

**Comment by RyanJarv** [comment]
Few things to add that I'll be working on:
* Internal build ready omaha-server (https://github.com/brave/omaha-server/issues/1)
* Omaha build environment (https://github.com/brave/omaha-build/issues/4)
* Security review

**Comment by simonhong** [comment]
Mac install dir : replace target `Brave.app` to channel dependent name like `Brave-Browser-Nightly` in  `brave/build/mac/BUILD.gn`

**Comment by simonhong** [comment]
When executing windows silent installer with additional install switch such as `--chrome-dev`, `--chrome--beta` or `--chrome-sxs`, it is installed into expected install dir. (EX, C:\Users\XXX\AppData\Local\BraveSoftware\Brave-Browser-Nightly).

However, they are not visible in uninstall list. (stable version is visible)
I think there is something more to installer..

**Comment by RyanJarv** [comment]
On the initial overview of the unofficial release sec review (https://github.com/brave/internal/issues/378) it sounds like we want to have the open sparkle issues resolved as well.

@bkero is looking into https://github.com/brave/Sparkle/issues/5 some more to figure out what the tradeoffs are there.

@simonhong do you think you have time to take https://github.com/brave/Sparkle/issues/4?

**Comment by RyanJarv** [comment]
Sorry late update here, we're ok on brave/Sparkle#4 and brave/Sparkle#5 for now. We'll just need to come back to these for the official release.

**Comment by simonhong** [comment]
Title is changed because most of items in this issue are also needed for dev channel release.

**Comment by simonhong** [comment]
Install multiple release on MacOS item is deleted from this PR because we can open dev release w/o it.
It should be resolved before we open multiple channels.

So, I'm taking a look windows installer.

**Comment by simonhong** [comment]
About version, installer sets its version to register(`pv`) and its version should be same in version value of server.

**Comment by simonhong** [comment]
Hmm, installer is tightly coupled with `chrome/VERSION` than expected

**Comment by simonhong** [comment]
When runs brave after install with https://github.com/brave/brave-core/pull/250, it failed to run.
Below is `sxstrace.exe` result. Where `67.0.3396.103` came from...?
brave.exe property has `0.50.8.0` value.
```
INFO: Resolving reference 67.0.3396.103,language="&#x2a;",type="win32",version="67.0.3396.103".
	INFO: Resolving reference for ProcessorArchitecture 67.0.3396.103,language="&#x2a;",type="win32",version="67.0.3396.103".
		INFO: Resolving reference for culture en-US.
			INFO: Applying Binding Policy.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Did not find manifest for culture en-US.
			INFO: End assembly probing.
		INFO: Resolving reference for culture en.
			INFO: Applying Binding Policy.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Did not find manifest for culture en.
			INFO: End assembly probing.
		INFO: Resolving reference for culture Neutral.
			INFO: Applying Binding Policy.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\Users\simon\AppData\Local\BraveSoftware\Brave-Browser\Application\67.0.3396.103.DLL.
				INFO: Attempt to probe manifest at C:\Users\simon\AppData\Local\BraveSoftware\Brave-Browser\Application\67.0.3396.103.MANIFEST.
				INFO: Attempt to probe manifest at C:\Users\simon\AppData\Local\BraveSoftware\Brave-Browser\Application\67.0.3396.103\67.0.3396.103.DLL.
				INFO: Attempt to probe manifest at C:\Users\simon\AppData\Local\BraveSoftware\Brave-Browser\Application\67.0.3396.103\67.0.3396.103.MANIFEST.
				INFO: Did not find manifest for culture Neutral.
			INFO: End assembly probing.
	ERROR: Cannot resolve reference 67.0.3396.103,language="&#x2a;",type="win32",version="67.0.3396.103".
```

**Comment by simonhong** [comment]
All items are cleared.
