### ISSUE TITLE
How disabled the BAT Rewards "Service"

### ISSUE THREAD

**Issue by Aloyah1** [brave/brave-browser#39604]
### Description

Hi,

How to permanently disabled the BAT Rewards Service ? I'm talking about the service in task manager in brave.

Why can’t it be deactivated ? it consumes a lot of CPU for nothing.

Thanks !

### Steps to reproduce

Launch Brave on Windows. Disable rewards in settings. Check built in task manager.

### Actual result

"Brave Ads Service" and "Bat Ledger Service" continue to run.

### Expected result

"Brave Ads Service" and "Bat Ledger Service" should not have active services running.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

100% of the time.

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by Miyayes** [comment]
Hi @Aloyah1, you can disable Rewards by resetting it in brave://rewards. Resetting will return your browser into a pre-enabled state. Thanks! 

See the "Reset" here:

![image](https://github.com/brave/brave-browser/assets/11497541/ad366be2-7019-42c5-b1cf-e0b90a4a1b6d)

**Comment by Aloyah1** [comment]
> Hi @Aloyah1, you can disable Rewards by resetting it in brave://rewards. Resetting will return your browser into a pre-enabled state. Thanks!
> 
> See the "Reset" here:
> 
> ![image](https://private-user-images.githubusercontent.com/11497541/347011130-ad366be2-7019-42c5-b1cf-e0b90a4a1b6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NDE3MzgsIm5iZiI6MTcyMDU0MTQzOCwicGF0aCI6Ii8xMTQ5NzU0MS8zNDcwMTExMzAtYWQzNjZiZTItNzAxOS00MmM1LWIxY2YtZTBiOTBhNGExYjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDE2MTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYzA0YzM5YzJmYmJjNWRjMzExNDQyZjkwOTE3Nzk0MzBlYjRkMjhkNzJmMTc3Y2EwNjRlOWY3ZGRkNmQ5NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a2L6EuJ3hduGXoSSXYqcV0kH5KL5Kqv-5RXqu-wuQho)
Hi,

I think it worked, I've been worrying about it for months. 

Thanks !
