### ISSUE TITLE
Cannot open links in mail.com emails 

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#3960]
## Description 

Brave users with mail.com accounts report that opening links from within emails in Brave does not work as intended. Reports claim that when clicked an error code 403 with `“Oops, something went wrong”` is displayed.

## Steps to Reproduce

   1. (mail.com account required) Visit mail.com and login
   2. Open an email containing hyperlink to external site
   3. Click hyperlink

## Actual result:

403 error is thrown:
![image](https://user-images.githubusercontent.com/3299098/55348036-20cc3b00-546b-11e9-8a03-22df4895923d.png)

## Expected result:
Link should open in a new tab 

## Brave version (brave://version info)

v0.61.52

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Dev - No
Beta - Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

User reports:
https://community.brave.com/t/mail-com-email-links-not-opening/46898/5
https://community.brave.com/t/opening-links-redirects-from-mail-com-not-working/49873

**Comment by rebron** [comment]
@Brave-Matt Can you check this in 62.x Release and 63.x Beta?

**Comment by Brave-Matt** [comment]
@rebron same behavior in both.

**Comment by Brave-Matt** [comment]
+1 https://community.brave.com/t/email-redirect-not-working-on-web-de-and-gmx-de/43965/7?u=mattches

**Comment by Brave-Matt** [comment]
+1 (new users reporting):
https://community.brave.com/t/email-redirect-not-working-on-web-de-and-gmx-de/43965/7?u=mattches

**Comment by Brave-Matt** [comment]
+1 and Bumping this issue as it seems to be affect a good amount of users. 4 new users reporting this thread: https://community.brave.com/t/email-redirect-not-working-on-web-de-and-gmx-de/43965/11?u=mattches

**Comment by ryanbr** [comment]
It redirects via this url;

`https://deref-mail.com/mail/client/9CBHCt26J7g/dereferrer/?redirectUrl=https%3A%2F%2Fwww.reddit.com`

**Comment by ryanbr** [comment]
Looking at the http response headers, the difference between Brave Nightly and release.

Brave nightly: Redirection url used returns error code (200) (which is good),
Brave release: Redirection url used returns error code (403) (not good),

https://imgur.com/a/syT8APG  (not uploaded here to due size)

Seems like something internally changed between builds

**Comment by ryanbr** [comment]
Re-checked this, Working in Brave release. Safe to close @Brave-Matt  ?

**Comment by ryanbr** [comment]
Closing this, we can re-open if its not resolved. wasn't reproducible

**Comment by bedax** [comment]
For anyone that may still be interested in this, this error can be caused in Firefox by setting `network.http.referer.trimmingPolicy` to `2`
