### ISSUE TITLE
No Confirm Dialog on Exit With Multiple Tabs

### ISSUE THREAD

**Issue by issuant** [brave/brave-browser#39607]
### Description

Unlike with Brave desktop, there's no confirm dialog when you tap the exit button which is very likely to happen accidentally with its awful positioning (#39374). This is a terrible experience when in incognito mode.

### Steps to reproduce

1. Open multiple tabs
2. Open the 3-dot menu and tap the exit button
3. Notice no confirm dialog shows up before Brave exits

### Actual result

Android Brave exits without throwing up a confirm dialog.

### Expected result

Android Brave should show an exit confirm dialog before exiting just like desktop Brave. At the very least, there should be an option to turn this on just like on desktop.

### Reproduces how often

Easily reproduced

### Brave version

All

### Device

- Brand/model: All
- Android version: All

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by deeppandya** [comment]
@issuant thank you for the issue. I am going to add the issue for discussion and I will set the priority based on it.

**Comment by SergeyZhukovsky** [comment]
@issuant thatnks for the reminder, I'm going to prioritise that this week

**Comment by SergeyZhukovsky** [comment]
@issuant that involves some design needs apart of engineering.

**Comment by SergeyZhukovsky** [comment]
@issuant I created two separated issues for the new problems you described:
https://github.com/brave/brave-browser/issues/42352
https://github.com/brave/brave-browser/issues/42353
The #42352 exist in Chrome as well, we usually wait for upstream to fix it unless it's something really critical, the #42353 is something we will look at.

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240925.009 release-keys
Brave build: 1.74.8 
Chromium: 131.0.6778.69 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/26145#issue-2606017472
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Exit` dialog is shown when existing Brava via the `Hamburger menu`
- Verified that tapping `No` does not close Brave.
- Verified that tapping `Yes` closes/exits Brave and removes the app from memory.

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/4279937e-5647-4a2e-a5e2-a9e8bdd7d247) | ![2](https://github.com/user-attachments/assets/d6889c7b-77f7-4663-a60e-a715f6ca22b6) |

https://github.com/user-attachments/assets/ec4f8d59-bc1b-4bbf-82f1-295647525f32

**Comment by SergeyZhukovsky** [comment]
@issuant I don't think it closes Brave in that case, it's just goes into background.

**Comment by SergeyZhukovsky** [comment]
That behaviour comes from upstream back button or swipe gesture navigation, it has nothing to do with Exit confirmation dialog or Exit functionality. The confirmation dialog is only called when it's explicitly tapped.

**Comment by SergeyZhukovsky** [comment]
@issuant it would be awesome if you can create a different issue to track that. Could you also include a video of the problem recorded if possible, it really helps to avoid confusion.
