### ISSUE TITLE
[HackerOne] Validation of chainId needed

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#39602]
### Description

See https://hackerone.com/reports/2588194

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.121 Chromium: 127.0.6533.57 (Official Build) beta (64-bit)
-- | --
Revision | 6ab76d6b98b9a4c22c06c9bb3487062edbbfb3f2
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verification notes can be found [here](https://github.com/brave/internal/issues/1161#issuecomment-2244261173)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.69.121 Chromium: 127.0.6533.57 (Official Build) beta (arm64)
-- | --
Revision | 6ab76d6b98b9a4c22c06c9bb3487062edbbfb3f2
OS | macOS Version 14.5 (Build 23F79)

- Verification notes can be found [here](https://github.com/brave/internal/issues/1161#issuecomment-2244269548)
