### ISSUE TITLE
[Wallet] Do not invalidate query cache during wallet initialization

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39614]
### Description

Currently we are invalidating the cached query results when the wallet is launched. We should avoid invalidating the cache unless data has changed

### Steps to reproduce

Open the wallet.
The wallet should display valid and current data.

### Actual result

Caches for the following are cleared:
- Networks
- Token Balances
- ConnectedAccounts
- Default Wallets
- Installed Wallet extension checks

### Expected result

Wallet should initialize with correct data. No caches should be cleared since the wallet has yet to fetch these pieces of data.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.67.116 Chromium: 126.0.6478.71 (Official Build) (arm64) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Relates to: https://github.com/brave/brave-browser/issues/19226

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.138 Chromium: 127.0.6533.100 (Official Build) beta (64-bit)
-- | --
Revision | 2569cce791e23282c250db59de277f2e81c33d9b
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24549](https://github.com/brave/brave-core/pull/24549)
- Verified Wallet data is initialed correctly 
- Verified Wallet data is cached correclty
