### ISSUE TITLE
Sync: proper message on wrong device time

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#3962]
## Description 

When time is wrong, sync shows general error about cannot connect to server, though there is an opportunity to shows details and give a tip on how to solve.

## Steps to Reproduce

   1. Adjust computer time 20 minutes forward.
   2. Create a sync chain 

## Actual result:

   3. See error of `Couldn't connect to Sync servers`

## Expected result:
   3. See error of `You might be having wrong system time or timezone setup on your device. Please setup the correct time and timezone`

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
yes

Related issues in brave sync js lib:
https://github.com/brave/sync/issues/157
https://github.com/brave/sync/issues/114
https://github.com/brave/sync/issues/212
also:
https://github.com/brave/browser-android-tabs/issues/788

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.65.95 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2076 / STR from description
![Screen Shot 2019-05-17 at 4 42 27 PM](https://user-images.githubusercontent.com/28145373/57954146-21584e00-78c0-11e9-9900-bcd03c373aec.png)
