### ISSUE TITLE
[ads] Infobar/notice for first interaction with clicked SERP ad landing page

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#39625]
https://docs.google.com/document/d/1mKpqqMGKImM7ZimK2_maUKooi3-ZQ42doVLtYgqPpgg/edit

**Comment by diracdeltas** [comment]
Noting that this should not be merged til https://github.com/brave/brave-core/pull/24188 is done

**Comment by btlechowski** [comment]
Verified with

Brave | 1.75.164 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | befbba8d7568f8713d6f942f9a7350c59b57f20a
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/25393


#### Testcase 1

<details>




</details>


#### Testcase 2

<details>




</details>


#### Testcase 3

<details>




</details>

**Comment by btlechowski** [comment]
Verification passed on Brave v1.75.164 on Lenovo TB-8506FS (Android 11.0)

Verified test plan from https://github.com/brave/brave-core/pull/25393


#### Testcase 1

<details>




</details>


#### Testcase 2

<details>




</details>


#### Testcase 3

<details>




</details>
