### ISSUE TITLE
BYOM: allow private IPs over HTTP with a warning

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#39627]
Subtasks:

1. Do not allow users to bypass security restrictions on "endpoint_url" via modifying Preferences. Test plan: in Leo settings, add a non-localhost BYOM endpoint that starts with "https://" but which does not actually support HTTPS. Then edit your preferences file to change the endpoint_url to start with "http://". Requests to Leo should fail.
2. Add a new CLI flag `--allow-leo-private-ips` or something like that. Once enabled, in Leo settings, allow users to input HTTP urls with a warning (mockup needed) if they pass the following criteria:
* Allow local addresses, link-local addresses as IP addresses (i.e. 192.168.0.0/24, 172.16.0.0/12, 10.0.0.0/8, 169,254.0.0/16, fe80::/10, fc00::/7)
* Allow hostnames which end in `.local`. 
3. [Optional, mockup needed] If the user is using Leo with a non-localhost HTTP endpoint, show an unlocked icon in the chat next to the model name. 

Needs security review for mockups and implementation.

**Comment by diracdeltas** [comment]
Suggestion for UX:

1. When the user tries to enter a http URL in BYOM, **only** if the URL is a private IP, show a modal that says basically "this is not allowed. to allow private IPs, use the --allow-leo-private-ips flag."
2. Once the user enables this flag via CLI or brave://flags, we allow private IPs over HTTP in the UI with a warning icon.

**Comment by prestonvanloon** [comment]
Please allow for specifying the private IP net. I'm running a model from a tailscale IP which is internal only. `100.64.0.0/10`

**Comment by mihaiplesa** [comment]
```
Please specify either QA/Yes or QA/No.
If you specify QA/Yes, then please also specify a test plan.
Please also specify either release-notes/include or release-notes/exclude.
```
@diracdeltas @mattmcalister

**Comment by jonathansampson** [comment]
Test-plan provided on the PR: https://github.com/brave/brave-core/pull/26475
