### ISSUE TITLE
[ads] Should not fetch geo and catalog on iOS when Brave Rewards/News disabled

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#39621]
### Description

Following Brave News chromium preferences are always set to true because iOS uses it's own set of native preferences:
```
brave_news::prefs::kBraveNewsOptedIn
brave_news::prefs::kNewTabPageShowToday
```
https://github.com/brave/brave-core/blob/master/ios/browser/api/ads/brave_ads.mm#L1531

This was working as expected until `ShouldAlwaysRunBraveAdsService` feature is enabled for iOS where we start brave ads when rewards and news are disabled. To fix the issue we need to properly set Brave News chromium preferences basing on Brave News native preference values for iOS.

Following preferences should be also properly set:
```
ntp_background_images::prefs::kNewTabPageShowBackgroundImage
ntp_background_images::prefs::kNewTabPageShowSponsoredImagesBackgroundImage
```

**Comment by aseren** [comment]
These settings will be properly handled within the issue: https://github.com/brave/brave-browser/issues/39658
```
ntp_background_images::prefs::kNewTabPageShowBackgroundImage
ntp_background_images::prefs::kNewTabPageShowSponsoredImagesBackgroundImage
```

**Comment by kjozwiak** [comment]
The above requires `1.68.122` or higher for `1.68.x` verification 👍

**Comment by btlechowski** [comment]
Verified on Brave 1.68.128 on iPhone 13 Pro Max

Verified test plan from https://github.com/brave/brave-core/pull/24570

### Testcase 1

<details>

![image](https://github.com/user-attachments/assets/a0d03034-6b05-4ac7-a161-7eee0e6eee1c)


Brave Ads started and successfully initialized
```
info	02:52:49.754250+0200	Client	[ads] Successfully initialized ads
```

there is NO network request to https://geo.ads.bravesoftware.com/v1/getstate endpoint
there is NO network request to https://static.ads.bravesoftware.com/v9/catalog endpoint


there is network request to https://geo.ads.bravesoftware.com/v1/getstate endpoint after enabling Brave News
```
info	19:44:06.662122+0200	Client	[ads] URL Request:
  URL: https://geo.ads.bravesoftware.com/v1/getstate
  Method: kGet
```


there is network request to https://static.ads.bravesoftware.com/v9/catalog endpoint after enabling Brave News
```
info	19:44:06.662122+0200	Client	[ads] URL Request:
  URL: https://geo.ads.bravesoftware.com/v1/getstate
  Method: kGet
```


</details>

### Testcase 2

<details>

![image](https://github.com/user-attachments/assets/e0f85d99-e0bc-4b62-a2cb-1343dbeb7a9c)


Brave Ads started and successfully initialized
```
info	19:47:22.770364+0200	Client	[ads] Successfully initialized ads
```

there is NO network request to https://geo.ads.bravesoftware.com/v1/getstate endpoint
there is NO network request to https://static.ads.bravesoftware.com/v9/catalog endpoint


there is network request to https://geo.ads.bravesoftware.com/v1/getstate endpoint after enabling Brave News
```
info	19:47:22.770468+0200	Client	[ads] URL Request:
  URL: https://static.ads.bravesoftware.com/v9/catalog
  Method: kGet
```


there is network request to https://static.ads.bravesoftware.com/v9/catalog endpoint after enabling Brave News
```
info	19:47:22.770997+0200	Client	[ads] URL Request:
  URL: https://geo.ads.bravesoftware.com/v1/getstate
  Method: kGet
```




</details>
