### ISSUE TITLE
Tor button should be icon only f/u to #39383

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#39626]
### Description

The Tor button in the address bar should be icon only with tool tip text to show "Open in Tor" and the .onion url for example.

`Open in Tor: https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion`

### Steps to reproduce

1. Visit a website that has .onion version e.g brave.com or nytimes.com
2. Notice the Tor icon in the address bar.
3. Should be icon only.

### Actual result

<img width="430" alt="345257421-5d5f0135-b4dd-4023-b3f8-f918d7fa5545" src="https://github.com/brave/brave-browser/assets/5951041/9e3af3a3-736e-401f-b4a1-6b04ddd2542e">

### Expected result

![346669719-49cb84c0-184c-49c7-ba8c-2b6753f656b3](https://github.com/brave/brave-browser/assets/5951041/21f0b592-4b01-4c15-ab94-9c0ae386614a)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

n/a.

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by diracdeltas** [comment]
will it at least show 'open in tor' when hovered over? otherwise some people may not know what the icon does and accidentally open a tor window.

**Comment by rebron** [comment]
Yes, the tooltip will say Open in Tor.

**Comment by kjozwiak** [comment]
The above requires `1.68.117` or higher for `1.68.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.68.117 Chromium: 127.0.6533.26 (Official Build) beta (64-bit)
-- | --
Revision | 80857ef16345e7959abe655afdebf9521f5109aa
OS | Windows 10 Version 22H2 (Build 19045.4651)
```
