### ISSUE TITLE
Can’t use the “next site” feature in the comments section of spiegel.de with default shields.

### ISSUE THREAD

**Issue by hollons** [brave/brave-browser#3963]
Description of the issue

https://community.brave.com/t/cant-browse-the-next-pages-in-the-comment-section-of-spiegel-de/51520

Can’t use the “next site” feature in the comments section of spiegel.de with default shields.
Exact URL of the website in question. The site http://www.spiegel.de/ seems to block content or lose functionality in Brave. The problem seems to be HTTPS upgrades — site functions as intended after they’re turned off (or Shields down).

http://www.spiegel.de/gesundheit/diagnose/organspende-in-deutschland-ploetzlich-geht-es-voran-kommentar-a-1260662.html 

Did the issue present with default Shields settings? 
[Default states are: Block: Ads/Trackers, 3rd Party Cookies, 3rd Party Fingerprinting Allow: 

![image (8)](https://user-images.githubusercontent.com/33430967/55359185-14091080-5486-11e9-93ce-cc002e6b850f.png)

![image (9)](https://user-images.githubusercontent.com/33430967/55359208-27b47700-5486-11e9-916b-77c605f7055f.png)

Encrypt Connections enabled (HTTPS), Scripts] (yes/no)
yes

Does the site function as expected when Shields are turned off? (yes/no)
yes

Is there a specific Shields configuration that causes the site to break? If so, tell us that configuration. (yes/no)
yes. Turning Https Everywhere off fixes the issue.

Does the site function as expected when using Chrome? (yes/no)
yes

What Operating System and Brave version/Build are you using when you encounter the issue?(See the About Brave page in the main menu)
0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)
Windows 10 OS Build 17763.379

**Comment by ryanbr** [comment]
Just checked `https://www.spiegel.de/politik/ausland/traenengas-an-der-griechisch-tuerkischen-grenze-eingesetzt-a-3776aca2-f597-4d48-80b6-cb9dc88bf981#kommentare`

Was able to view next comments on this site, is everything now working @hollons ?

**Comment by ryanbr** [comment]
Reaching out via forums, probably safe to close.

**Comment by pes10k** [comment]
assuming fixed, with no follow up, please reopen if not
