### ISSUE TITLE
[Linux] Touch keyboard isn't shown when a text input field is focused

### ISSUE THREAD

**Issue by balintbarna** [brave/brave-browser#39640]
### Description

On my touchscreen devices using Gnome when I tap on a text input field in many apps, eg. the Settings app search, the on screen keyboard automatically shows up as one would expect similarly to smartphones. This doesn't happen in Brave browser, which means I have to swipe up from the bottom of the screen every time, which doesn't work very well.

### Steps to reproduce

1. Enable OSK in Gnome settings
3. Tap on URL or other input in Brave

### Actual result

OSK is not shown automatically

### Expected result

OSK is shown automatically

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave	1.67.116 Chromium: 126.0.6478.71 (Official Build) (64-bit) 
Revision	f4237fe448716e50cca6e827ff87ffd701c7d0c7
OS	Linux

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

I'm running NixOS with Gnome and Brave is installed from nixpkgs 24.05 without any special modifications.

**Comment by jmz-bit** [comment]
I have the same problem with Brave. Tried on Mint 22, Ubuntu 24 and Fedora 40.

OSK keyboard is working with any other input fields from system to other web browsers.

But not for Brave.

Any solution to this?

**Comment by Segment0895** [comment]
@jmz-bit can you check on Chrome or Chromium? It's an upstream bug AFAIK.

**Comment by jmz-bit** [comment]
> @jmz-bit can you check on Chrome or Chromium? It's an upstream bug AFAIK.

I did check it on many Linux systems like Mint 22, Ubuntu 24, Fedora 40, KDE Neon

I also check it on Brave, Microsoft Edge, Google Chrome, Chromium etc.

Looks like it is general problem to all web browsers based on Chrome/Chromium.

Problem don't exist on web browsers based on Gecko like Mozilla or Libre Wolf etc.

There is no problem with Brave ON Screen Keyboard with Windows 10.

**Comment by Segment0895** [comment]
> > @jmz-bit can you check on Chrome or Chromium? It's an upstream bug AFAIK.
> Looks like it is general problem to all web browsers based on Chrome/Chromium.

Try `brave-browser --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime --wayland-text-input-version=3` for Chromium's **experimental** text-input-v3 support.

**Comment by jmz-bit** [comment]
> > > @jmz-bit can you check on Chrome or Chromium? It's an upstream bug AFAIK.
> > > Looks like it is general problem to all web browsers based on Chrome/Chromium.
> 
> Try `brave-browser --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime --wayland-text-input-version=3` for Chromium's **experimental** text-input-v3 support.

Thanks for this... I will try in next few days.

BTW.  I know that this is separate issue... but since we are talking here. Why Sync is working so bad with Brave (Linux, Windows and Android) Bookmarks works well every time... but everything else not especially passwords.

**Comment by jlnr** [comment]
Is there a timeline for having this feature on by default? I've just received my first 2-in-1 (yay Framework 12!), and was surprised that the OSK doesn't automatically open in Brave.

**Comment by balintbarna** [comment]
This is still an issue and the flags mentioned above are not available anymore.

**Comment by pinhaman** [comment]
There is a workaround, at least on Zorin OS 18 Core. Just came across it. If you open an app and trigger the OSK and you place it directly "over" brave and then you minimize that app the OSK stays open on brave. The thing is, as soon as you click anywhere in the browser outside where you can write it goes away. I just wrote this message that way.

**Comment by KBMD** [comment]
I don't know why this issue was closed. It is still a problem that makes Brave completely unusable on a tablet.
