### ISSUE TITLE
Disable Keyboard API fingerprinting

### ISSUE THREAD

**Issue by bershanskiy** [brave/brave-browser#3964]
## Description 

Brave inherits from Chrome implementation of Keyboard API which does not provide any functionality to the user (only Chrome and Opera support it and, to my knowledge, no site actually uses it). However, the API might be used for fingerprinting.

WICG Keyboard Map Draft mentions that the API can be used for fingerprinting of:
> - Users who use uncommon ASCII layouts (like Dvorak or Colemak)
> - Users who use an ASCII layout that doesn’t match the default for the region that they are in. For example, a user in the US with an active UK or French layout.

## Steps to Reproduce

   1. Verify that "Shields" are on
   2. Enable a few different keyboards in your OS, e.g. Dvorak (DV):
   3. Run this in the console and observe the output with different keyboard layouts:
      ```
      var keyboard = {}
      navigator.keyboard.getLayoutMap()
      .then(keyboardLayoutMap => {
        keyboardLayoutMap.forEach((value,key,map) => {keyboard[key] = value})
        console.log(keyboard)
      })
      ```

## Actual result:

For standard English keyboard:
```
{KeyE: "e", KeyD: "d", Minus: "-", KeyH: "h", KeyZ: "z", ...}
```

For Dvorak keyboard:
```
{KeyE: ".", KeyD: "e", Minus: "[", KeyH: "d", KeyZ: ";", ...}
```

For Colemak keyboard:

## Expected result:
When Shields are on, either API should be unavailable ()

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

All versions of Brave based on Chromium 63 and above.

Brave | 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Windows 10 OS Build 17763.379

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Reproducible on Beta build

Brave | 0.62.37 Chromium: 73.0.3683.86 (Official Build) beta (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Windows 10 OS Build 17763.379

#### Compatibility impact is minimal
Keyboard API was only recently introduced and only in Chrome 68 and Opera 55 (according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Keyboard_API)). It should be trivial to remove or polyfill. A good candidate for dummy values is provided in the official polyfill:
https://github.com/WICG/keyboard-map/blob/master/keyboard-polyfill.js

Note that `navigator.keyboard` also includes `navigator.keyboard.lock` defined in [Keybard Lock API](https://wicg.github.io/keyboard-lock/) -- a related API introduced at the same time (and apparently with similarly small adoption).

#### WICG Keyboard Map Draft recommendations
Excerpt from [here](https://wicg.github.io/keyboard-map/#privacy):
> 6.1. Privacy Mitigations
> User agents that are concerned about the privacy impact of providing this keyboard mapping information can also consider the following mitigations:
>
> Having a user prompt to ask for permission whenever a site attempts to use this API.
>
> Always return a "standard" mapping. Although note that the standard mapping would need to vary for different parts of the world. For example, a user agent that had a "privacy mode" that always returned a US-QWERTY layout mapping would actually be providing more identifying information for users in the UK than the actual mapping would (since most users in the UK do not use a US layout).
>
> 6.2. Privacy Mode
> If a user agent provides an "incognito" or "privacy mode", then this API should act the same as it does outside of "privacy mode". The reason for this is that there is no universal neutral value that can be returned to ensure the user’s privacy.
>
> User agents may choose to give the user the option to specify what value should be returned when in this mode, although care must be taken to ensure that the user does not get a false sense of security since this value would need to be updated when if they travel outside their home region.

#### Links

[WICG Keyboard Map Draft](https://wicg.github.io/keyboard-map/)

Edit: Copied full version string; in demo code changed `let` to `var` so that you can easily run the same code many times; added a link and fixed list number.

**Comment by srirambv** [comment]
cc: @tomlowenthal @diracdeltas

**Comment by bershanskiy** [comment]
Didn't mention in the initial post, but for a while now (~month) I have been running an extension that removed this API (replaced `navigator.keyboard` with `undefined`) in every context and did not see any negative behavior yet.

**Comment by snyderp** [comment]
Related: https://github.com/brave/brave-browser/issues/2655

**Comment by bershanskiy** [comment]
> WebKit team at Apple is not interested in implementing this feature as currently proposed / spec'ed.

Source: https://github.com/WICG/keyboard-map/issues/30

**Comment by mkarolin** [comment]
**QA Test Plan:**
1. Start Brave and navigate to a HTTPS site (e.g. https://brave.com)
2. Open the Shields panel in Advanced view and verify that Fingerprinting is set to blocked (standard).
3. Open Developer Tools -> Console
4.  Paste the following code into the console and execute it:
<pre>
var keyboard = {}
navigator.keyboard.getLayoutMap()
.then(keyboardLayoutMap => {
  keyboardLayoutMap.forEach((value,key,map) => {keyboard[key] = value})
  console.log(keyboard)
})
</pre>
5. Expected result:
<pre>
VM81:2 Uncaught TypeError: Cannot read properties of null (reading 'getLayoutMap')
    at <anonymous>:2:20
</pre>

6. Open the Shields panel in Advanced view and change Fingerprinting setting to `Allow all fingerprinting`
7. Repeat steps 3-4
8. Expected result:
<pre>
Promise {<pending>}
VM123:5 {KeyE: 'e', KeyD: 'd', Minus: '-', KeyH: 'h', KeyZ: 'z', …}
</pre>

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.34.62 Chromium: 96.0.4664.110 (Official Build) dev (64-bit)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Windows 10 Version 20H2 (Build 19042.1415)

Confirmed with `Fingerprinting` set to `Standard` I see the exception.
Confirmed with `Fingerprinting` set to `Disabled` I see the JS promise returned.

example | example | example | example
---------|------------|----------|-----------
![3964-1](https://user-images.githubusercontent.com/387249/146234346-04a9ce56-3dbd-47df-b5b7-faddfb719be7.png) | ![3964-2](https://user-images.githubusercontent.com/387249/146234386-b9b707ff-2fa2-4a13-8f42-c3e300a6fb5a.png) | ![3964-3](https://user-images.githubusercontent.com/387249/146234412-24e03a1d-2f98-445c-b582-e2c23ff2df9a.png) | ![3964-4](https://user-images.githubusercontent.com/387249/146234438-e47f8414-c1db-431a-9bc5-0316196a4da1.png)

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.34.68, Chromium 97.0.4692.56` on a Google Pixel XL running Android 9.0.

example | example | example | example
---------|----------|---------|---------
![Screenshot_20211221-132258](https://user-images.githubusercontent.com/387249/146999703-66b4687b-6e19-4acf-9cfa-3f2549a0b9e9.png) | <img width="1239" alt="Screen Shot 2021-12-21 at 1 22 27 PM" src="https://user-images.githubusercontent.com/387249/146999736-dc8a1c63-96de-4818-a2cc-f9cc4fd05294.png"> | ![Screenshot_20211221-132307](https://user-images.githubusercontent.com/387249/146999760-87afa153-b2b5-4000-ac1b-b0fd9ec2829c.png) | <img width="1239" alt="Screen Shot 2021-12-21 at 1 23 48 PM" src="https://user-images.githubusercontent.com/387249/146999791-c6e9854b-62c5-493c-9b95-adfb091e40af.png">

**Comment by Nul-led** [comment]
Kinda sad to see, there are legit use cases for this api (eg for games)

**Comment by perguto** [comment]
A fingerprinter can recover the `keyboardLayoutMap` for any key the user presses anyway (by comparing `event.code` and `event.key` for the corresponding `KeyboardEvent`s), so disabling the API only enhances privacy for sites you've never pressed keys on.

@Nul-led You can still activate it by pressing on the arrow to the right of "Block Fingerprinting" in the Brave Shields dropdown menu, and toggling "keyboard" off (this will also incidentally enable the Keyboard.lock method).
