### ISSUE TITLE
Add View on Block Explorer button to Account Details menu 

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#39655]
### Platforms

Linux, macOS, Windows

### Description

We should add a `View on block explorer` button to the `Account Details` menu, which would pop a `Network selector` for EVM accounts.

![Screenshot 12](https://github.com/brave/brave-browser/assets/40611140/1fe19e41-0e79-409e-90e5-2078aa3e6dd6)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.136 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 47255350e0d135b2172cb9dd2ba344d3d7fe4572
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24607](https://github.com/brave/brave-core/pull/24607)
- Verified Block explorer option is shown in account menu
- Verified for Ethereum account shows all EVM networks when view on block explorer option is selected
- Verified for Bitcoin and ZCash there is no view on block explorer option

https://github.com/user-attachments/assets/0b2983fc-bb9a-4634-a5cf-9383f07a3915
