### ISSUE TITLE
WebUI Navigation Bar sub-menu has light-on-light items in dark mode for c74

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#3965]
WebUI Navigation Bar sub-menu should be on dark background in dark mode
C74 only

STR:
1. Visit Bookmarks Page

Actual:
![image](https://user-images.githubusercontent.com/741836/55363929-a49a1d80-5493-11e9-90b0-c8eb2110d7fd.png)

Expected:
Dark background

**Comment by bsclifton** [comment]
Resolved when C74 was merged to master with https://github.com/brave/brave-browser/pull/3931 😄

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.5 x64` using the following build:

Brave | 0.65.113 Chromium: 75.0.3770.38 (Official Build) beta(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

* **`Example of chrome://bookmarks/:`**

<img width="353" alt="Screen Shot 2019-05-29 at 11 43 36 AM" src="https://user-images.githubusercontent.com/2602313/58572624-06fc6980-820a-11e9-94fe-d9c6809153d6.png">

<img width="226" alt="Screen Shot 2019-05-29 at 11 53 00 AM" src="https://user-images.githubusercontent.com/2602313/58572642-0ebc0e00-820a-11e9-9921-3c824ce27630.png">

<img width="184" alt="Screen Shot 2019-05-29 at 11 43 52 AM" src="https://user-images.githubusercontent.com/2602313/58572651-1380c200-820a-11e9-9cac-1ab2b632d28d.png">

<img width="223" alt="Screen Shot 2019-05-29 at 11 52 48 AM" src="https://user-images.githubusercontent.com/2602313/58572659-17acdf80-820a-11e9-92da-677d38c58979.png">

* **`Example of chrome://downloads/:`**

<img width="368" alt="Screen Shot 2019-05-29 at 12 06 14 PM" src="https://user-images.githubusercontent.com/2602313/58572753-49be4180-820a-11e9-9220-f4f41c4eabd2.png">

<img width="388" alt="Screen Shot 2019-05-29 at 12 06 21 PM" src="https://user-images.githubusercontent.com/2602313/58572761-4cb93200-820a-11e9-8792-7e84286cbd77.png">

<img width="357" alt="Screen Shot 2019-05-29 at 12 06 45 PM" src="https://user-images.githubusercontent.com/2602313/58572781-55aa0380-820a-11e9-89f9-1860599662e2.png">

<img width="377" alt="Screen Shot 2019-05-29 at 12 06 50 PM" src="https://user-images.githubusercontent.com/2602313/58572788-593d8a80-820a-11e9-91df-d15817c3b0bd.png">
