### ISSUE TITLE
Input values are persisted when switching between Swap and Bridge screens

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#39657]
### Description

Currently input values are being persisted when switching between the `Swap` and `Bridge` screens.

### Steps to reproduce

1. Open the `Wallet` and navigate to the `Swap` screen
2. Select some tokens to swap and enter an `amount` to get a quote
3. Now navigate to the `Bridge` screen
4. You will see that the `Input` values are persisted along with the `New quote countdown` continues to count down.

### Actual result

https://github.com/brave/brave-browser/assets/40611140/993a1868-70dc-49e4-9bff-5e5d102f0c51

### Expected result

It should reset and clear all input fields.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.88 Chromium: 127.0.6533.26 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.135 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 96e3ea6d105b9e3f1a388fa1838571774216b82e
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24574](https://github.com/brave/brave-core/pull/24574)
- Verified input values are not persisted when switching between Swap and Bridge screens

https://github.com/user-attachments/assets/b0a08818-8527-4ad4-b28a-e14a64a2ab5b
