### ISSUE TITLE
[Wallet] Fix IPFS images not loading in panel

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39659]
### Description

IPFS images are no longer loading correctly in the wallet panel

### Steps to reproduce

1. Add an NFT to the visible assets list that has an IPFS URL ([Invisible Friends](https://opensea.io/assets/ethereum/0x59468516a8259058bad1ca5f8f4bff190d30e066/2964)) via the "Add NFT form"
2. Try to view the NFT within the NFTs screen of the panel

### Actual result

Image is not loaded

### Expected result

The NFT image should appear

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.0 Chromium: 127.0.6533.26 (Developer Build) (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Regression from: [Deprecate local node support and ipfs scheme](https://github.com/brave/brave-core/pull/23808/files#top)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.101 Chromium: 127.0.6533.43 (Official Build) nightly (64-bit)
-- | --
Revision | 9073515479afc03ab66a21bb8175263fc56ba1f1
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified able to load NFTs image when adding the NFT
- Verified NFT image is shown in Portfolio 

https://github.com/user-attachments/assets/5e54c9b8-66ed-4b8f-9b61-02862605b44c
