### ISSUE TITLE
[Wallet] Inform user that an NFT is not owned by any of their accounts in the NFT details screen

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39653]
### Platforms

all

### Description

We should alert the user that the NFT is not owned by any of their accounts when viewing it's details screen

https://www.figma.com/design/mvoB5HzIyQT9O4vbcA1XhP/NFT-(Wallet-2.0)?node-id=1866-91551&t=5yXkcmOjUXnfw9Gs-0

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.138 Chromium: 127.0.6533.100 (Official Build) beta (64-bit)
-- | --
Revision | 2569cce791e23282c250db59de277f2e81c33d9b
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24569](https://github.com/brave/brave-core/pull/24569)
- Verified Watch list message is shown on NFT details screen for unowned NFTs
![image](https://github.com/user-attachments/assets/809384e0-29d5-4a23-9fa7-7a678042bfad)
