### ISSUE TITLE
Hangouts extension should be off by default

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#39664]
### Test plan
See https://github.com/brave/brave-core/pull/24583

### Description

While we explore removing the Hangouts extension completely in https://github.com/brave/brave-browser/issues/39660, we should at least disable the extension by default for users who haven't touched the extension.

### Steps to reproduce

1. Never having touched the Hangouts toggle...
2. Go to brave://settings/extensions
3. See Hangouts toggle

### Actual result

It's on (by default)

### Expected result

It should be off

As a corollary, we should not touch the toggle for users who have touched the toggle.

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

all

### Android device

all

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

I think we want to disable in Nightly first and have it ride the trains.

**Comment by bsclifton** [comment]
Removed `OS/Android` - this should be desktop only (Android would require some work to support extensions).

**Comment by kjozwiak** [comment]
The above requires `1.67.133` or higher for `1.67.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.67.134 Chromium: 126.0.6478.186 (Official Build) (64-bit)
-- | --
Revision | e27c9744a0ed98bfa60e287af7e5eaffde15bd57
OS | Windows 10 Version 22H2 (Build 19045.4651)
```
## Case 1: Upgrade, default - `PASSED`
<details>

1. installed `1.67.123`
2. launched Brave (`release`)
3. opened `brave://settings/extensions`
4. confirmed `Hangouts` is toggled `On`/`Enabled`
5. upgraded to `1.69.98` by renaming `Brave-Browser` profile to `Brave-Browser-Nightly`
6. installed launched Brave `1.69.98` (`nightly`)
7. opened `brave://settings/extensions`


### Confirmed `Hangouts` is toggled `Off`/`Disabled`
 

`1.67.123` | `1.69.98`
-----------|----------
![image](https://github.com/brave/brave-core/assets/387249/f0599d30-d630-451b-9b75-253a6ada9400) | ![image](https://github.com/brave/brave-core/assets/387249/2ac6df3e-5240-4c75-8181-ad0aa6549fb3)



</details>

## Case 2: Upgrade, user-modified setting - `PASSED`
<details>


1. installed and launched `1.67.123` (`release`)
2. opened `brave://settings/extensions`
3. toggled `Hangouts` from its default of `Enabled` to `Disabled`, and then finally toggled back to `Enabled`/`On`
4. installed `1.69.98`
5. launched Brave (`nightly`)
6. opened `brave://settings/extensions`
7. looked at the value for the `Hangouts` preference

### Confirmed `Hangouts` was still set to `Enabled`/`On`

`1.67.123` | `1.69.98`
-----------|----------
![image](https://github.com/brave/brave-core/assets/387249/d085c32f-155d-4108-b760-e6a9c8b4cb65) | ![image](https://github.com/brave/brave-core/assets/387249/57cef88c-d4dc-4f16-8a70-39ff6a67d7bc)



</details>

## Case 3: Disabling the pref disables the extension - `PASSED`
<details>

### Steps:
1. installed `1.69.98`
2. launched Brave
3. opened `brave://settings/extensions`
4. confirmed `Hangouts` is set to `Disabled`/`Off`
5. opened `brave://extensions-internals`
6. grepped for `DISABLE_BLOCKED_BY_DEFAULT`
7. confirmed `disable_reasons` for the `Hangouts` extension ID `nkeimhogjdpnpccoofpliimaahmaaome` was set to the above
8. loaded `google.com`
9. opened the `Developer Tools`' `Console`
10. pasted the following snippet:
```
chrome.runtime.sendMessage(
  "nkeimhogjdpnpccoofpliimaahmaaome",
  { method: "cpu.getInfo" },
  (response) => {
    console.log(JSON.stringify(response, null, 2));
  },
);
```
11. confirmed I got the following error: `Uncaught TypeError: Cannot read properties of undefined (reading "sendMessage") at <anonymous>:1:16`

`brave://settings/extensions` | `brave://extensions-internals` |  `Google.com w/ Dev Console`
--------------------------------|---------------------------------|----------------------------------
![image](https://github.com/brave/brave-core/assets/387249/7b50041a-392c-4d05-b963-4286e46244f7) | ![image](https://github.com/brave/brave-core/assets/387249/c0b49a3b-b45e-45fe-bfad-c50d41a13b07) | ![image](https://github.com/brave/brave-core/assets/387249/2bf2fd0e-8b20-4d50-9059-e7b70fa6da5c)


</details>

## Case 4: Enabling the pref allows the extension - `PASSED`
<details>


### Steps:
1. installed `1.69.98`
2. launched Brave
3. opened `brave://settings/extensions`
4. toggled `Hangouts` to `Enabled`/`On`
5. opened `brave://extensions-internals`
6. grepped for `DISABLE_BLOCKED_BY_DEFAULT`
7. confirmed `disable_reasons` is **_NOT present_** for the `Hangouts` extension ID `nkeimhogjdpnpccoofpliimaahmaaome`
8. loaded `google.com`
9. opened the `Developer Tools`' `Console`
10. pasted the following snippet:
```
chrome.runtime.sendMessage(
  "nkeimhogjdpnpccoofpliimaahmaaome",
  { method: "cpu.getInfo" },
  (response) => {
    console.log(JSON.stringify(response, null, 2));
  },
);
```
11. confirmed I got the following output, without errors: 

```
{
        "usage": {
          "idle": 1573165468750,
          "kernel": 32185000000,
          "total": 1643948125000,
          "user": 38597656250
        }
 },
```

`brave://settings/extensions` | `brave://extensions-internals` |  `Google.com w/ Dev Console`
--------------------------------|---------------------------------|----------------------------------
![image](https://github.com/brave/brave-core/assets/387249/6a707515-df19-4647-b27f-4a861377f5bb) | ![image](https://github.com/brave/brave-core/assets/387249/add45b3b-8fcc-41f2-88a5-e6edb9b98152) | ![image](https://github.com/brave/brave-core/assets/387249/ead8b23c-8ae8-4325-b168-bf78d3484492)


</details>
