### ISSUE TITLE
Rewards creator detection is not working on twitter/x

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#39669]
### Description

Rewards creator detection is not working correctly on twitter/x. The "verified creator" checkmark does not appear and the Rewards panel does not display creator information.

It appears that the `chrome.braveRewards` extension API is no longer available in the built-in brave extension background script, possibly due to https://github.com/brave/brave-core/pull/24430.

### Steps to reproduce

1. With a connected rewards profile,
2. Navigate to a verified twitter/x profile.

### Actual result

The verified creator checkmark is not displayed on the Rewards icon on twitter/x. In addition the following errors appear in the console for the brave extension:

<img width="626" alt="Screenshot 2024-07-10 at 11 38 16 AM" src="https://github.com/brave/brave-browser/assets/5995084/296ce2ea-62a3-42db-914d-33ace13c06c3">

### Expected result

The verified creator checkmark should be displayed on the Rewards icon for verified creators on twitter/x.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.0 Chromium: 127.0.6533.26 (Developer Build) (x86_64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by Asizdhung** [comment]
Brother i know, Im sorry i became a part of something i don’t understand
but i enjoyed it any ways can you plz send me a link to app connect.

On Wed, 10 Jul 2024 at 11:45 pm, Kevin Smith ***@***.***>
wrote:

Closed #39669 <https://github.com/brave/brave-browser/issues/39669> as

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.69.98 Chromium: 127.0.6533.26 (Official Build) nightly (64-bit)
-- | --
Revision | a7710883b2316472175f7b756e561cca3f02b254
OS | Windows 10 Version 22H2 (Build 19045.4651)
```
- Verified the description from the issue https://github.com/brave/brave-browser/issues/39669#issue-2401117118
- Verified few verified twitter/x creators and ensured that "verified creator" checkmark is shown on the BR panel

Example | Example
----------|----------
![image](https://github.com/user-attachments/assets/bf685894-383f-4e70-8a3e-92fdf4298ab5) | ![image](https://github.com/user-attachments/assets/581ff926-89de-489d-9e0e-10b9b9abd583)

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```

Brave | 1.69.129 Chromium: 127.0.6533.73 (Official Build) beta (x86_64)
-- | --
Revision | 0ab2f25cd017b563fd72d68048f809659a351a04
OS | macOS Version 11.7.10 (Build 20G1427)


```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.69.128 Chromium: 127.0.6533.73 (Official Build) beta (64-bit) 
Revision	715445841b1da480bcc24c12077a6dc926951996
OS	Linux
```


- Verified the description from the issue https://github.com/brave/brave-browser/issues/39669#issue-2401117118
- Verified few verified twitter/x creators and ensured that "verified creator" check mark is shown on the BR panel

example | example 
----- | -----
![image](https://github.com/user-attachments/assets/14ea8d0e-ce01-4466-bf2d-2cf972a89459)|![image](https://github.com/user-attachments/assets/24d23973-a4e8-4435-b771-4559f02e2090)
