### ISSUE TITLE
Webtorrent file doesn't stream when file name is clicked on

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#3966]
## Description 

Instead of streaming the torrent content in window when clicking on the file name, Brave instead offers to save the file to your device:
![webtor]()

When torrent is opened in a new tab (from webtorrent screen), stream content opens in the new tab and will play as intended.

## Steps to Reproduce

   1. Ensure Brave webtorrent ext is enabled in settings 
   2. Start torrent file in webtorrent
   3. Click on torrent name

## Actual result:

(see above gif)

## Expected result:
Clicking the file name should start streaming content in new tab rather than offer to download file.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

v0.61.52

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Additional Information

FWIW, there should be a "play" or "start stream" button here instead of clicking on the file name -- Its not very clear nor is it stated anywhere that this is how to initiate video playback.

**Comment by feross** [comment]
@yrliou I figured out the root cause of this issue. I will send a PR shortly.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.96 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/2990. Made sure that the video file is streamed. 
Verified that opening the file in a new tab also streams the video

![image](https://user-images.githubusercontent.com/34715963/65102969-fcd6c480-d9cc-11e9-8924-d9059e839f74.png)
