### ISSUE TITLE
Remove Hangouts component

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#39660]
### Test plan
See https://github.com/brave/brave-core/pull/24594

### Platforms

Linux, macOS, Windows

### Description

We previously added the Hangouts extension to allow screen sharing: https://github.com/brave/brave-browser/pull/1983. The setting is toggleable via the `Hangouts` setting in brave://settings/extensions. 

The Hangouts extension uses private Chrome Web APIs: https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/resources/hangout_services/manifest_v3.json;l=24-30. We need to investigate if we still need this extension/component. Screen sharing does not seem dependent on this extension any more: disabling the `Hangouts` setting does not affect screen sharing on Google Meet but does prevent debugging information showing up (which is fine). 

Note that we disable log uploading done by this (and other) private WebRTC APIs: https://github.com/brave/brave-browser/issues/1993

**Comment by bsclifton** [comment]
Hangouts of course has been EOL'ed but Google Meet working great with a few tests I've done with the extension disabled.

**Comment by ShivanKaul** [comment]
I went through the extension's permissions:
1. `desktopCapture`: this doesn't seem necessary since the page can just use Screen Capture API
2. `enterprise.hardwarePlatform`: this seems purely for logging purposes. We already disable uploading of logging information
3. `processes`: logging related too, "continuously reporting relevant CPU usage information to the page."
4. `system.cpu`: logging
5.  `webrtcAudioPrivate`: AFAICT not even being used by the extension
6. `webrtcDesktopCapturePrivate`: Hmm, this might be used to [allow screen sharing via a WebView](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/chrome/common/extensions/api/webrtc_desktop_capture_private.idl). @bsclifton Does this option exist on Android? If yes, if you open a Google Meet link in a WebView (maybe if you click on the link in Messenger or WhatsApp?) are you able to share screen?
7. `webrtcLoggingPrivate`: logging

**Comment by bsclifton** [comment]
@ShivanKaul I can check that tomorrow

Should we make a separate issue to track disabling component first? This issue can track removing it entirely. I created https://github.com/brave/brave-core/pull/24583 and added some tests that I manually ran through. Let me know what you think!

**Comment by ShivanKaul** [comment]
Yeah, that makes sense, like we discussed we don't need to block on disabling this in Nightly.

**Comment by ShivanKaul** [comment]
I created https://github.com/brave/brave-browser/issues/39664 and edited the PR description for https://github.com/brave/brave-core/pull/24583 to fix that instead.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```

```

## Case 1: Upgrade, default - `PASSED`
<details>

1. installed `1.67.123`
2. launched Brave (`release`)
3. opened `brave://settings/extensions`
4. confirmed `Hangouts` is toggled `On`/`Enabled`
5. upgraded to `1.69.98` by renaming `Brave-Browser` profile to `Brave-Browser-Nightly`
6. installed launched Brave `1.69.98` (`nightly`)
7. opened `brave://settings/extensions`


### Confirmed `Hangouts` is toggled `Off`/`Disabled`
 

`1.67.123` | `1.69.98`
-----------|----------
![image](https://github.com/brave/brave-core/assets/387249/f0599d30-d630-451b-9b75-253a6ada9400) | ![image](https://github.com/brave/brave-core/assets/387249/2ac6df3e-5240-4c75-8181-ad0aa6549fb3)



</details>

## Case 2: Upgrade, user-modified setting - `PASSED`
<details>


1. installed and launched `1.67.123` (`release`)
2. opened `brave://settings/extensions`
3. toggled `Hangouts` from its default of `Enabled` to `Disabled`, and then finally toggled back to `Enabled`/`On`
4. installed `1.69.98`
5. launched Brave (`nightly`)
6. opened `brave://settings/extensions`
7. looked at the value for the `Hangouts` preference

### Confirmed `Hangouts` was still set to `Enabled`/`On`

`1.67.123` | `1.69.98`
-----------|----------
![image](https://github.com/brave/brave-core/assets/387249/d085c32f-155d-4108-b760-e6a9c8b4cb65) | ![image](https://github.com/brave/brave-core/assets/387249/57cef88c-d4dc-4f16-8a70-39ff6a67d7bc)



</details>

## Case 3: Disabling the pref disables the extension - `PASSED`
<details>

### Steps:
1. installed `1.69.98`
2. launched Brave
3. opened `brave://settings/extensions`
4. confirmed `Hangouts` is set to `Disabled`/`Off`
5. opened `brave://extensions-internals`
6. grepped for `DISABLE_BLOCKED_BY_DEFAULT`
7. confirmed `disable_reasons` for the `Hangouts` extension ID `nkeimhogjdpnpccoofpliimaahmaaome` was set to the above
8. loaded `google.com`
9. opened the `Developer Tools`' `Console`
10. pasted the following snippet:
```
chrome.runtime.sendMessage(
  "nkeimhogjdpnpccoofpliimaahmaaome",
  { method: "cpu.getInfo" },
  (response) => {
    console.log(JSON.stringify(response, null, 2));
  },
);
```
11. confirmed I got the following error: `Uncaught TypeError: Cannot read properties of undefined (reading "sendMessage") at <anonymous>:1:16`

`brave://settings/extensions` | `brave://extensions-internals` |  `Google.com w/ Dev Console`
--------------------------------|---------------------------------|----------------------------------
![image](https://github.com/brave/brave-core/assets/387249/7b50041a-392c-4d05-b963-4286e46244f7) | ![image](https://github.com/brave/brave-core/assets/387249/c0b49a3b-b45e-45fe-bfad-c50d41a13b07) | ![image](https://github.com/brave/brave-core/assets/387249/2bf2fd0e-8b20-4d50-9059-e7b70fa6da5c)


</details>

## Case 4: Enabling the pref allows the extension - `PASSED`
<details>


### Steps:
1. installed `1.69.98`
2. launched Brave
3. opened `brave://settings/extensions`
4. toggled `Hangouts` to `Enabled`/`On`
5. opened `brave://extensions-internals`
6. grepped for `DISABLE_BLOCKED_BY_DEFAULT`
7. confirmed `disable_reasons` is **_NOT present_** for the `Hangouts` extension ID `nkeimhogjdpnpccoofpliimaahmaaome`
8. loaded `google.com`
9. opened the `Developer Tools`' `Console`
10. pasted the following snippet:
```
chrome.runtime.sendMessage(
  "nkeimhogjdpnpccoofpliimaahmaaome",
  { method: "cpu.getInfo" },
  (response) => {
    console.log(JSON.stringify(response, null, 2));
  },
);
```
11. confirmed I got the following output, without errors: 

```
{
        "usage": {
          "idle": 1573165468750,
          "kernel": 32185000000,
          "total": 1643948125000,
          "user": 38597656250
        }
 },
```

`brave://settings/extensions` | `brave://extensions-internals` |  `Google.com w/ Dev Console`
--------------------------------|---------------------------------|----------------------------------
![image](https://github.com/brave/brave-core/assets/387249/6a707515-df19-4647-b27f-4a861377f5bb) | ![image](https://github.com/brave/brave-core/assets/387249/add45b3b-8fcc-41f2-88a5-e6edb9b98152) | ![image](https://github.com/brave/brave-core/assets/387249/ead8b23c-8ae8-4325-b168-bf78d3484492)




</details>

**Comment by ShivanKaul** [comment]
Just some background here:

[In 2019](https://github.com/brave/brave-core/pull/1227), Brave enabled the [Hangouts Services](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/resources/hangout_services/manifest_v3.json) extension to allow users to use Google Hangouts and Google Meet in the Brave browser. This extension fixed some broken Hangouts/Meet functionality in Brave (specifically, screen sharing [would not work](https://github.com/brave/brave-browser/issues/1982) on Google Hangouts/Meet without the extension). At the time, Chromium was cautious about giving all websites access to the [standards-compliant screen sharing API](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia) because of [security concerns](https://issues.chromium.org/issues/40344129#comment41), which is presumably why Google special-cased this ability for Google’s websites only.

Having Google Meet/Hangouts work in Chrome but not Brave was a serious Web compatibility problem. Before enabling this extension by default, [Brave made sure](https://github.com/brave/brave-browser/pull/1983#issuecomment-440165888) that we added a way for users to disable the Hangouts extension in brave://settings/extensions. We also [proactively blocked](https://github.com/brave/brave-browser/issues/1993) automatic uploading of debugging information to Google’s servers, the same way we [frequently modify Chromium](https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)) to fix leaks and boost user privacy. However, we see now why this would have raised concerns among some users. In hindsight, a better approach would have been one similar to what we did with the [Widevine extension](https://support.brave.com/hc/en-us/articles/360023851591-How-do-I-view-DRM-protected-content): keep the extension off-by-default, and ask the user if they want to enable it on their first visit to a website with functionality that would be helped by the extension.

Over the years, we received [clear reports from users](https://github.com/brave/brave-browser/issues/13469) that Google Meet did not work properly without the Hangouts Services extension, which is why we kept it on by default (though we should have revisited this sooner.) With the widespread adoption of screen sharing Web APIs, it’s clear the extension is no longer needed. [Google deprecated Hangouts](https://arstechnica.com/gadgets/2022/06/google-hangouts-finally-gets-a-shutdown-date-november-2022/), and Google Meet works fine for Brave users without the extension. We have now changed our settings panel to leave the Hangouts Services [extension off by default](https://github.com/brave/brave-core/pull/24583), and are removing the extension completely with the work in this issue.

**Comment by MadhaviSeelam** [comment]
Adding `QA/Test-All-Platforms` as per the description

**Comment by MadhaviSeelam** [comment]
Verification `PASSED using
```
Brave | 1.69.122 Chromium: 127.0.6533.57 (Official Build) beta (64-bit)
-- | --
Revision | bd77e9b76a8e67ff2bf9f62f1df7d60378ca811f
OS | Windows 11 Version 23H2 (Build 22631.3880)
```

Note:  Hangout is enabled by default `1.67.123` in, however, in `1.67.134` & `1.68.127` it's disabled by default
 <details>

1.67.123 | 1.67.134 | 1.68.127
------ | ----- | -----
![image](https://github.com/user-attachments/assets/a316c108-9010-4171-9545-07a5bb3035c2)|![image](https://github.com/user-attachments/assets/150e222a-f589-429c-81db-fb65123b8dd8)|![image](https://github.com/user-attachments/assets/f8ad5e36-89ad-4d8d-a695-c82e466285dd)
![image](https://github.com/user-attachments/assets/7f02f03d-5d33-4c91-91d6-b896c3b58c06)|![image](https://github.com/user-attachments/assets/bbe2dae2-ec0e-4543-8a54-51ffd5cbc625)|![image](https://github.com/user-attachments/assets/e130ec74-b615-4ea4-af97-8e96defa965a)
</details>

#### Case 1: Upgrade, default - `PASSED`
<details>

1. installed `1.68.127`
2. launched Brave 
3. opened `brave://settings/extensions`
4. confirmed `Hangouts` is toggled `Off`/`disabled`
5. upgraded to `1.69.122` by renaming `Brave-Browser` profile to `Brave-Browser-Beta`
6. installed launched Brave `1.69.122` (`Beta`)
7. opened `brave://settings/extensions`


### Confirmed `Hangouts` is removed from `brave://settings/extension`

step 4 | step 7
----- | ------
![image](https://github.com/user-attachments/assets/00411f8b-16ac-4fe5-b898-a4a75706a39d)|![image](https://github.com/user-attachments/assets/c1d9b892-4620-4583-a906-433b9dae72d1)
</details>

#### Case 2: Upgrade, user-modified setting - `PASSED`
<details>

1. installed and launched `1.67.123` (`release`)
2. opened `brave://settings/extensions`
3. toggled `Hangouts` from its default of `disabled` to `enabled`
4. installed `1.69.122 `
5. launched Brave (`Beta`)
6. opened `brave://settings/extensions`
7. verified `Hangouts` entry is no longer shown
8. opened brave://extensions-internals/
9. confirmed `nkeimhogjdpnpccoofpliimaahmaaome` is no longer there
10. loaded `google.com`
11. opened the `Developer Tools`' `Console`
12. pasted in the following and hit Enter:
```
chrome.runtime.sendMessage(
  "nkeimhogjdpnpccoofpliimaahmaaome",
  { method: "cpu.getInfo" },
  (response) => {
    console.log(JSON.stringify(response, null, 2));
  },
);
```
13. confirmed an error shown in console and no information shown.

step 3a | step 3b | step 7 | step 9 | step 13
----- | ----- | ----- | ------ | -------
![image](https://github.com/user-attachments/assets/6672d2c5-4877-4948-b633-44415cbfd9fe)|![image](https://github.com/user-attachments/assets/2a271b1e-d6e4-4ccf-bdb6-66fbcbba5d77)|![image](https://github.com/user-attachments/assets/56c674c1-a57c-4186-ab84-ea2ca1b920fb)|![image](https://github.com/user-attachments/assets/5de912fe-d214-4541-82fd-a02097c3445d)|![image](https://github.com/user-attachments/assets/313b4f97-45f8-4b94-b256-47d442f9cd62)

</details>

#### Case 3: New profile - `PASSED`
<details>

### Steps:
1. installed `1.69.122`
2. launched Brave
3. loaded `brave://settings/extensions`
4. confirmed no `Hangouts` UI
5. loaded `brave://extensions-internals/`
6. searched for the `nkeimhogjdpnpccoofpliimaahmaaome` extension

#### Confirmed no UI nor Hangouts extensions shown

step 3 | step 5
----- | ------
![image](https://github.com/user-attachments/assets/619e707f-164b-48be-8957-1f73c8760535)|![image](https://github.com/user-attachments/assets/f3edb2ba-4594-46bf-b12e-dc72e09c0645)

**Comment by Martin-K24** [comment]
Upon further testing there is no way to lock the slider in `brave://settings/extensions` with a group policy rule. And the one I tried above ^ does nothing.

Also many group policies are broken and dont carry over in Brave.

For example these two do not work on Brave:

- EnableMediaRouter
- ClearBrowsingDataOnExitList  

```json
{
    "EnableMediaRouter": false,
    "ClearBrowsingDataOnExitList": [
      "browsing_history",
      "download_history",
      "cookies_and_other_site_data",
      "cached_images_and_files",
      "password_signin",
      "autofill",
      "site_settings",
      "hosted_app_data"
  ]
}
```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave	1.69.128 Chromium: 127.0.6533.73 (Official Build) beta (64-bit) 
Revision	715445841b1da480bcc24c12077a6dc926951996
OS	Linux
```


Note:  Hangout is enabled by default `1.67.123` in, however, in `1.67.134` & `1.68.127` it's disabled by default
 <details>

1.68.127
-----
![image](https://github.com/user-attachments/assets/aea75389-5ee6-4c31-a9ff-abf9c4c45e2a)

</details>

#### Case 1: Upgrade, default - `Pending`
<details>

1. installed `1.68.127`
2. launched Brave 
3. opened `brave://settings/extensions`
4. confirmed `Hangouts` is toggled `Off`/`disabled`
5. upgraded to `1.69.122` by renaming `Brave-Browser` profile to `Brave-Browser-Beta`
6. installed launched Brave `1.69.122` (`Beta`)
7. opened `brave://settings/extensions`


### Confirmed `Hangouts` is removed from `brave://settings/extension`

step 4 | step 7
----- | ------

</details>

#### Case 2: Upgrade, user-modified setting - `Pending`
<details>

1. installed and launched `1.67.123` (`release`)
2. opened `brave://settings/extensions`
3. toggled `Hangouts` from its default of `disabled` to `enabled`
4. installed `1.69.122 `
5. launched Brave (`Beta`)
6. opened `brave://settings/extensions`
7. verified `Hangouts` entry is no longer shown
8. opened brave://extensions-internals/
9. confirmed `nkeimhogjdpnpccoofpliimaahmaaome` is no longer there
10. loaded `google.com`
11. opened the `Developer Tools`' `Console`
12. pasted in the following and hit Enter:
```
chrome.runtime.sendMessage(
  "nkeimhogjdpnpccoofpliimaahmaaome",
  { method: "cpu.getInfo" },
  (response) => {
    console.log(JSON.stringify(response, null, 2));
  },
);
```
13. confirmed an error shown in console and no information shown.

step 3a | step 3b | step 7 | step 9 | step 13
----- | ----- | ----- | ------ | -------

</details>

#### Case 3: New profile - `Pending`
<details>

### Steps:
1. installed `1.69.122`
2. launched Brave
3. loaded `brave://settings/extensions`
4. confirmed no `Hangouts` UI
5. loaded `brave://extensions-internals/`
6. searched for the `nkeimhogjdpnpccoofpliimaahmaaome` extension

#### Confirmed no UI nor Hangouts extensions shown

step 3 | step 5
----- | ------
