### ISSUE TITLE
Leo slash tools icon missing border

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#39673]
### Description

Leo slash tools icon missing border on Beta channel

### Steps to reproduce

1. New install 1.68.115
2. Activate Leo
3. Observe chat prompt

### Actual result

Missing border for slash tools

![IMG_6709](https://github.com/brave/brave-browser/assets/17885425/e0851c52-d65b-4416-b0c0-c8810c8a6613)

### Expected result

![IMG_3814](https://github.com/brave/brave-browser/assets/17885425/2ffcf3c1-57ca-4be1-8db1-2cac5809f296)

### Reproduces how often

Easily reproduced

### Brave version

1.68.115

### Device/iOS version

iPhone, iPad

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by Asizdhung** [comment]
Im so sorry i was not online. And plz help me sign in please. Im trying
since 2 days i have no choice but to do this. Come on guys wtf, I
understand english but what is this you gotta be from sun to understand
this. Im sorry to do this

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.68.117`

- Ensured Leo slash tools icon is not missing the border.
- Ensured that opening/closing slash tools menu works.
- Ensured using chat works as expected.

Example | Example
-|-
![IMG_6740](https://github.com/brave/brave-browser/assets/17885425/bde84114-f3e7-40ef-ba39-3e443a182ffe) | ![IMG_6741](https://github.com/brave/brave-browser/assets/17885425/9447115c-1c1f-4417-83da-efed04184c24)
