### ISSUE TITLE
Ads enabled for unsupported regions

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3967]
## Description 

While verifying #2562, found even if device on unsupported region, Ads get enabled.  

## Steps to Reproduce

   1. Set VPN to a unsupported region
   2. Launch a clean profile of beta
   3. Enable rewards
   4. Open rewards setting, `Sorry, Ads are not available in your region` message pops up for a second and then ads settings get enabled 

## Actual result:

Ads enabled for unsupported regions

## Expected result:
Unavailable message should persist and ads should not be enabled. Only for supported regions should be enabled

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.63.28 Chromium: 73.0.3683.75 (Official Build) beta(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on beta and dev. Not checked on Nightly 
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A
### Additional Information

cc: @tmancey @jsecretan set priority to P2, please change if required
@brave/legacy_qa to verify on other platforms as well

**Comment by tmancey** [comment]
@ryanml do you know of any recent changes which may have caused this please?

**Comment by ryanml** [comment]
@tmancey I have not made any changes related to this since: https://github.com/brave/brave-core/pull/1941 - I can do some investigation on this one though 👍

**Comment by tmancey** [comment]
@ryanml This could be related to Chromium returning `en_US` for non supported regions, let me check this first and I will then get back to you if that is ok?

**Comment by ryanml** [comment]
@tmancey sounds good. Double checking the logic in place is all sound but yeah just seems that the wrong value is showing for region

**Comment by btlechowski** [comment]
I am located in Poland and Ads are enabled. I don't see any ads though.

Brave | 0.63.30 Chromium: 73.0.3683.75 (Official Build) beta (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

![image](https://user-images.githubusercontent.com/34715963/55520714-c9ea7f80-567d-11e9-9738-727f82b731bd.png)

**Comment by tmancey** [comment]
@btlechowski Ads are not available at this time in Poland, an unavailable message should be shown and ads should not be enabled, thanks

**Comment by GeetaSarvadnya** [comment]
I am located in India Ads are disabled, I don't see any Ads without Brave VPN.

![image](https://user-images.githubusercontent.com/38657976/55575909-9f57ff80-572d-11e9-9613-26a206704697.png)



Brave | 0.64.36 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

**Comment by GeetaSarvadnya** [comment]
I am not getting `Sorry, Ads are not available in your region` for India. I was seeing the message on 0.64.36 but not now. I am not getting this message in any of the Dev and Beta versions.

Brave | 0.64.40 Chromium: 74.0.3729.61 (Official Build) dev (64-bit)
-- | --
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Windows 10 OS Build 17134.523


Brave | 0.63.34 Chromium: 74.0.3729.40 (Official Build) beta (64-bit)
-- | --
Revision | 278d6a0d856d8314f36fb9a68b6e1d85cd0d14e7-refs/branch-heads/3729@{#470}
OS | Windows 10 OS Build 17134.523

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.63.46 Chromium: 74.0.3729.91 (Official Build) (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Linux

* Setting VPN to supported region and OS locale changed doesn't enable ads
![image](https://user-images.githubusercontent.com/17010094/56507061-31ae2080-64ee-11e9-9477-88b39b932f01.png)
* Setting VPN and OS locale to supported region shows ads as expected

**Comment by muro886** [comment]
I am in Turkey please enable ads for Turkey. 

Brave | 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.706

**Comment by lyquocnam** [comment]
i am in Vietnam, please enable ads for Vietnam.

Brave | 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X
