### ISSUE TITLE
Pls add P3A Q26 to iOS

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#39672]
### Description

https://github.com/brave/brave-browser/wiki/P3A#q26-is-the-sponsored-new-tab-page-option-enabled

### Steps to reproduce

1. NA
2. 
3. 

### Actual result

NA

### Expected result

NA

### Reproduces how often

Easily reproduced

### Brave version

NA

### Device/iOS version

NA

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kylehickinson** [comment]
Confirmed this question is being answered by iOS already: 
![image](https://github.com/brave/brave-browser/assets/529104/df8a76a9-528b-43b0-92b3-d315862b7455)
