### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#39688]
### Description

After 2 confilicting PRs are merged:

```
../../brave/components/brave_wallet/browser/zcash/zcash_rpc.cc:306:21: error: use of undeclared identifier 'prefs_'
  306 |       GetNetworkURL(prefs_, chain_id, mojom::CoinType::ZEC));
      |                     ^
../../brave/components/brave_wallet/browser/zcash/zcash_rpc.cc:330:21: error: use of undeclared identifier 'prefs_'
  330 |       GetNetworkURL(prefs_, chain_id, mojom::CoinType::ZEC));
      |
```

### Steps to reproduce

-

### Actual result

-

### Expected result

-

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

-

### Android device

-

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by Asizdhung** [comment]
Can it wait and please. I will be back like in 2/4 hr and noo peeking
