### ISSUE TITLE
Add Info Tooltip to Price Impact section for Bridge and Swap

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#39683]
### Platforms

Linux, macOS, Windows

### Description

We need to add an `Informational` tooltip to the `Price Impact` section for `Bridge` and `Swap` 

![Screenshot 15](https://github.com/brave/brave-browser/assets/40611140/8f041792-43b6-4910-8aea-fe478a4804a1)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.117 Chromium: 127.0.6533.57 (Official Build) beta (64-bit)
-- | --
Revision | 7b5104c54992f658db7f6b1e7441021612ba71a3
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24610](https://github.com/brave/brave-core/pull/24610)
- Verified Price impact tooltip is shown when hovered over the info icon
- Encountered [#39851](https://github.com/brave/brave-browser/issues/39851)

https://github.com/user-attachments/assets/4a54c056-fbc7-4026-8bf3-b4c95d41b8c8
