### ISSUE TITLE
Different `Share this page` button icon on each platforms

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#39687]
### Description

On Windows,
![image](https://github.com/brave/brave-browser/assets/6786187/e62bd9b6-9b86-45be-9664-2ed529658f30)

On macOS,
<img width="292" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/2f15302a-d051-46d6-8b80-95fc3c3c8d13">

### Steps to reproduce

1. Load any url and check share button in location bar
2. 
3. 

### Actual result

Different icons per platforms

### Expected result

Maybe same icons for all platforms?

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.88 Chromium: 127.0.6533.26 (Official Build) nightly (64-bit) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @aguscruiz

**Comment by aguscruiz** [comment]
Yeah this is what's expected. Each platform has a different default share icon
