### ISSUE TITLE
Google extension `Office Editing for Docs, Sheets & Slides` is not working

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3968]
## Description 

Google extension `Office Editing for Docs, Sheets & Slides` is not working
https://chrome.google.com/webstore/detail/office-editing-for-docs-s/gbkeegbaiigmenfmjfclcdgdpimamgkj

## Steps to Reproduce

   1. Open brave 0.61.52
   2. Install the extension `Office Editing for Docs, Sheets & Slides` from CWS
   3.  try to open Docs, excel or slides

## Actual result:

Word, exce and slides are not loaded, page is empty.
![image](https://user-images.githubusercontent.com/38657976/55390467-e9d25400-5554-11e9-9f7a-810c8798fb2a.png)

![Office extension issue](https://user-images.githubusercontent.com/38657976/55390391-bc85a600-5554-11e9-92f3-99dbcaf5f843.gif)

Console Error:

![image](https://user-images.githubusercontent.com/38657976/55410778-12247780-5582-11e9-88a3-f71e62cff603.png)

## Expected result:
The extension should load word, excel, and slides

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Windows 10 OS Build 17134.523

### Reproducible on current release: Yes
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

The issue is reported by the community
https://community.brave.com/t/not-working-google-extension-for-office-editing-for-docs-sheets-slides/50968

@brave/legacy_qa @bbondy

**Comment by srirambv** [comment]
+1 from @fshuk1 via https://github.com/brave/browser-android-tabs/issues/1505

**Comment by benjaminrohe** [comment]
+1 this is mission critical to use BRAVE as a work browser. 

any estimate when this issue is resolved?

**Comment by bsclifton** [comment]
Looks like the extension is using Google Analytics (and possibly other 3rd party scripts)

Also seeing (in the logs) reference to `Nacl` which we don't support (it's being phased out). If this is the blocker, there should be a newer version of the extension coming out soon as Web Assembly

Blog with more info (if this does use NaCl / Native Client)
https://developer.chrome.com/native-client/migration

**Comment by benjaminrohe** [comment]
It's a official Google extension

**Comment by mishaley** [comment]
Agreed, I also need this to fully move over to Brave.

**Comment by benlc** [comment]
+1 would love a fix for this

**Comment by bblaha** [comment]
+1 absolutely essential to me

**Comment by dylan1114** [comment]
+1 I hope this gets fixed, then the browser is perfect for me.

**Comment by webjive** [comment]
Ditto!! Would love for this to work with Brave or someone to fork it and get it working.

**Comment by bjkarki** [comment]
The only reason I have chrome installed (along with Brave) is that this extension does not work in Brave.

**Comment by UtahJonF** [comment]
+1 This keeps me having both Brave and Chrome installed.

**Comment by AdamSHurwitz** [comment]
Gdocs is working offline for me which appears to be a new update for Brave!

**Version:** _1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit)_

**Comment by bsclifton** [comment]
Thanks for the update, @AdamSHurwitz!

I tried the steps specified in https://community.brave.com/t/not-working-google-extension-for-office-editing-for-docs-sheets-slides/50968 (ex: going to extension menu, picking New Spreadsheet) and it doesn't work for me ☹️ I suspect there is still a problem here

**Comment by AdamSHurwitz** [comment]
@bsclifton, This is the flow that is working for me:

1. Turn Wi-Fi off.
2. Go to https://drive.google.com/drive/my-drive
3. Select the '+ New' button in the top left menu column.
4. Select either a doc/sheet/slide/etc.

**Comment by rodrigoswz** [comment]
No news for fix this issue? This extension works perfectly on others Chromium browsers like Chrome, Edge, Vivaldi...

Only on Brave which is my favorite that doesn't 😟

**Comment by webjive** [comment]
We've given up on Brave and moved back to Chrome.

**Comment by AdamSHurwitz** [comment]
@webjive, I'm back to Chrome as of this week as well. The game changer for me is when my laptop had to go to the repair shop and being reminded how Brave does not sync 'Other search engines' and short cut keys that have been customized. Chrome allows the syncing of the above.

I'm looking forward to trying Brave again in the future. 🚀

**Comment by UtahJonF** [comment]
I'm also back to Chrome starting this week. Between all of the sites that don't work (even with shields down), bookmark sync, and offline google docs, I'm exhausted fighting with this thing. The parts I do like are the built in shields up/down idea and the incognito with Tor option. I'm sure this will all get fixed or Chrome will build out the parts that work. Best of luck.

**Comment by DarkoMir** [comment]
I found that if you use google docs format, extension works flawless, while if you use xls(x), doc(x) ecc then blank page

**Comment by simonhong** [comment]
This extension is based on nacl and we don't ship it.
@rebron @bsclifton maybe this issue should be won't fix?

**Comment by bsclifton** [comment]
nacl (Native Client) supposed to be deprecated Q4 2019
https://developer.chrome.com/native-client/migration

So I agree - this might be a `wontfix`

**Comment by fmarier** [comment]
The official Google extension I use for offline editing of Google Docs does work fine in Brave, but it appears to be a different one: https://chrome.google.com/webstore/detail/google-docs-offline/ghbmnnjooekpmoecnnnilnnbdlolhkhi

**Comment by bsclifton** [comment]
cc: @DarkoMir @UtahJonF @AdamSHurwitz @webjive @rodrigoswz @bjkarki @dylan1114 @bblaha @benlc @mishaley @benjaminrohe

Would you all be able to try the other extension that @fmarier shared above?
https://chrome.google.com/webstore/detail/google-docs-offline/ghbmnnjooekpmoecnnnilnnbdlolhkhi

I'll see if I'm able to reach Google support and will report back findings

**Comment by rodrigoswz** [comment]
In my case, I just need this extension to open documents directly from the browser.

[Try this link](http://browsernative.com/test/word.docx) for example.
In Brave, with the [extension of this issue](https://chrome.google.com/webstore/detail/office-editing-for-docs-s/gbkeegbaiigmenfmjfclcdgdpimamgkj), you will have a white screen exactly as reported.
But if you try it on Edge or Chrome, it will open perfectly as expected.

[Here's the proof](https://i.imgur.com/scYXwFh.png)

**Comment by bsclifton** [comment]
@rodrigoswz correct - because Chrome and Edge are compiling using NaCl (native client) and with Brave we don't. It was supposed to be deprecated end of 2019, but appears it hasn't been

If you download https://chrome.google.com/webstore/detail/google-docs-offline/ghbmnnjooekpmoecnnnilnnbdlolhkhi instead (and remove https://chrome.google.com/webstore/detail/office-editing-for-docs-s/gbkeegbaiigmenfmjfclcdgdpimamgkj), we suspect it should work perfectly for you

Please let us know 😄

**Comment by rodrigoswz** [comment]
@bsclifton yes, I tried https://chrome.google.com/webstore/detail/google-docs-offline/ghbmnnjooekpmoecnnnilnnbdlolhkhi on Brave (without https://chrome.google.com/webstore/detail/office-editing-for-docs-s/gbkeegbaiigmenfmjfclcdgdpimamgkj) but unfortunately the file is directly downloaded instead of open in the browser.

I tested this with the link I sent as an example in my previous comment.

**Comment by rebron** [comment]
Closing and marking as wontfix per https://github.com/brave/brave-browser/issues/3968#issuecomment-634230883 and https://developer.chrome.com/native-client/migration#p-nacl-deprecation-announcements
This is a nacl based extension and won't be supported in the future.

**Comment by TheNerdMan** [comment]
I understand that this has been closed due to nacl deprecation, but it is a huge flaw not being able to support official google extensions. Especially ones that seem to have as much traction as this one.

**Comment by andrewyuyang** [comment]
5 years and this is not fixed??

**Comment by andrewyuyang** [comment]
is this seriously not fixed after 5 years? Any workaround?

**Comment by mikel023** [comment]
As of 2026, still not fixed. I wanna fully switch to brave and this issue prevents me from doing so.

**Comment by rodrigoswz** [comment]
I still miss a lot this.

For now, I'm using Edge on Desktop.
