### ISSUE TITLE
Simplify variations pull requests testing process

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#39689]
### Description

Add support for `--variations-pr=<pull_number>` command line flag that will automatically set required flags to fetch the test seed generated as a part of https://github.com/brave/brave-variations pull request.

Related https://github.com/brave/brave-browser/issues/33654

**Comment by goodov** [comment]
To test use this pull request number https://github.com/brave/brave-variations/pull/1123

**Comment by kjozwiak** [comment]
The above requires `1.68.124` or higher for `1.68.x` verification 👍 @brave/qa-team please use https://github.com/brave/brave-core/pull/24604#issuecomment-2229417488 or https://github.com/brave/brave-core/pull/24604#issuecomment-2231943968 as the template. Would recommend using https://github.com/brave/brave-core/pull/24604#issuecomment-2231943968 as it has several other cases for `Desktop` like an upgrade case that should also be checked.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.68.124 Chromium: 127.0.6533.57 (Official Build) (x86_64)
-- | --
Revision | d048917c488542dc56e67059011b2cf9d6043bb9
OS | macOS Version 11.7.10 (Build 20G1427)
```

#### `Test Case #1` - (`offline` executable using `https://variations.brave.com/seed` as default) - **`PENDING`**

<details>

STR/Cases:

* launched `1.68.124 Chromium: 127.0.6533.57` via the `standalone` executable and visited `brave://version`
* ensured that `--variations-server-url=https://variations.brave.com/seed` is visible via `brave://version`
* ensured that `--variations-insecure-server-url=https://variations.brave.com/seed` is visible via `brave://version`

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|---------------


* restarted `1.68.124 Chromium: 127.0.6533.57` and ensured that the studies/variations were being pulled/applied
* ensured that `--variations-server-url=https://variations.brave.com/seed` is visible via `brave://version`
* ensured that `--variations-insecure-server-url=https://variations.brave.com/seed` is visible via `brave://version`

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|---------------

</details>

#### `Test Case #2` - (`online` stub executable using `https://variations.brave.com/seed` as default) - **`PENDING`**

<details>

STR/Cases:

* launched `1.68.124 Chromium: 127.0.6533.57` via the `stub` online executable and visited `brave://version`
* ensured that `--variations-server-url=https://variations.brave.com/seed` is visible via `brave://version`
* ensured that `--variations-insecure-server-url=https://variations.brave.com/seed` is visible via `brave://version`
* ensured that the studies/variations were being pulled/applied via `brave://version`

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|---------------

</details>

#### `Test Case #3` - Setting test seed using `--variations-pr=` - **`PENDING`**

<details>

STR/Cases:

* launched `1.68.124 Chromium: 127.0.6533.57` using `brave.exe --enable-logging=stderr --variations-pr=1123`
* ensured that there's no variations being displayed via `brave://version` (requires a restart to apply the pulled variation)
* re-launched using  `brave.exe --enable-logging=stderr --variations-pr=1123`
* ensured that the following parameters/switches are present/visible under `Command Line`

```
--accept-empty-variations-seed-signature
--disable-variations-seed-fetch-throttling
--variations-server-url=https://griffin.brave.com/pull/1123/seed
--variations-insecure-server-url=https://griffin.brave.com/pull/1123/seed
```

* ensured that `pull/1123@1082ba20390784d33de2b4e6275434deef6c4633
BraveAdsAdEventStudy:Enabled` is being displayed under `Active variations:` via `brave://version`

**`Example`** | **`Example`**
---------------|----------------

</details>

#### `Test Case #4` - ensuring `https://variations.brave.com/seed` is being restored - **`PENDING`**

<details>

STR/Cases:

* after running through `Test Case #2` above, removed `--variations-pr=1123` and started `1.68.124 Chromium: 127.0.6533.57` using `brave.exe --enable-logging=stderr`.
* ensured that the following two parameters/switches are visible under `Command Line` via `brave://version`

```
--variations-server-url=https://variations.brave.com/seed
--variations-insecure-server-url=https://variations.brave.com/seed
```

![image](https://github.com/user-attachments/assets/940389ee-47c5-4086-8fc8-9d8419f8f42c)

* ensured that the following parameters/switches are not visible/present via `Command Line` under `brave://version`

```
--accept-empty-variations-seed-signature
--disable-variations-seed-fetch-throttling
```

**`Example`** | **`Example`**
---------------|----------------


</details>

#### `Test Case #5` - Upgrade from `1.69.102 Chromium: 127.0.6533.43` -> `1.69.110 Chromium: 127.0.6533.43` - **`PENDING`**

<details>

STR/Cases:

* installed `1.69.102 Chromium: 127.0.6533.43` and relaunched so the studies are applied/visible via `brave://version`
* upgraded to `1.69.110 Chromium: 127.0.6533.43` via `brave://settings/help`
* ensured that once updated, the variations/studies are still visible/being applied via `brave://version`

`1.69.102 Chromium: 127.0.6533.43` | `1.69.110 Chromium: 127.0.6533.43`
----------------------------------------|------------------------------------------

</details>

**Comment by MadhaviSeelam** [comment]
Verification `Passed` using
```
Brave | 1.68.124 Chromium: 127.0.6533.57 (Official Build) (64-bit)
-- | --
Revision | d048917c488542dc56e67059011b2cf9d6043bb9
OS | Windows 11 Version 23H2 (Build 22631.3880)
```


#### `Test Case #1` - (`offline` executable using `https://variations.brave.com/seed` as default) - **`PASSED`**

<details>

STR/Cases:

* launched `1.68.124 Chromium: 127.0.6533.57` via the `standalone` executable and visited `brave://version`
* ensured that `--variations-server-url=https://variations.brave.com/seed` is visible via `brave://version`
* ensured that `--variations-insecure-server-url=https://variations.brave.com/seed` is visible via `brave://version`

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|---------------
![image](https://github.com/user-attachments/assets/91ea0c43-4a14-4d27-bebe-dd1c604d3dd9)|<img width="960" alt="image" src="https://github.com/user-attachments/assets/c8c05bf1-d523-46a8-8e1b-87684324a72b">|<img width="960" alt="image" src="https://github.com/user-attachments/assets/48607df8-27e5-424c-a347-50d1ed7b3cab">

* restarted `1.68.124 Chromium: 127.0.6533.57` and ensured that the studies/variations were being pulled/applied
* ensured that `--variations-server-url=https://variations.brave.com/seed` is visible via `brave://version`
* ensured that `--variations-insecure-server-url=https://variations.brave.com/seed` is visible via `brave://version`

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|---------------
<img width="960" alt="image" src="https://github.com/user-attachments/assets/f8f4d667-30a5-40f7-9421-e5933a487acc">|![image](https://github.com/user-attachments/assets/93ae1e66-235f-4289-8682-b790728ae84f)|![image](https://github.com/user-attachments/assets/6b53cc5f-ed5c-4b6b-96d1-61669578e898)

</details>

#### `Test Case #2` - (`online` stub executable using `https://variations.brave.com/seed` as default) - **`PASSED`**

<details>

STR/Cases:

* launched `1.69.110 Chromium: 127.0.6533.43` via the `stub` online executable and visited `brave://version`
* ensured that `--variations-server-url=https://variations.brave.com/seed` is visible via `brave://version`
* ensured that `--variations-insecure-server-url=https://variations.brave.com/seed` is visible via `brave://version`
* ensured that the studies/variations were being pulled/applied via `brave://version`

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|---------------

</details>

#### `Test Case #3` - Setting test seed using `--variations-pr=` - **`PASSED`**

<details>

STR/Cases:

* launched `1.69.111 Chromium: 127.0.6533.43` using `brave.exe --enable-logging=stderr --variations-pr=1123`
* ensured that there's no variations being displayed via `brave://version` (requires a restart to apply the pulled variation)
* re-launched using  `brave.exe --enable-logging=stderr --variations-pr=1123`
* ensured that the following parameters/switches are present/visible under `Command Line`

```
--accept-empty-variations-seed-signature
--disable-variations-seed-fetch-throttling
--variations-server-url=https://griffin.brave.com/pull/1123/seed
--variations-insecure-server-url=https://griffin.brave.com/pull/1123/seed
```

* ensured that `pull/1123@1082ba20390784d33de2b4e6275434deef6c4633
BraveAdsAdEventStudy:Enabled` is being displayed under `Active variations:` via `brave://version`

**`Example`** | **`Example`**
---------------|----------------

</details>

#### `Test Case #4` - ensuring `https://variations.brave.com/seed` is being restored - **`PASSED`**

<details>

STR/Cases:

* after running through `Test Case #2` above, removed `--variations-pr=1123` and started `1.69.111 Chromium: 127.0.6533.43` using `brave.exe --enable-logging=stderr`.
* ensured that the following two parameters/switches are visible under `Command Line` via `brave://version`

```
--variations-server-url=https://variations.brave.com/seed
--variations-insecure-server-url=https://variations.brave.com/seed
```



* ensured that the following parameters/switches are not visible/present via `Command Line` under `brave://version`

```
--accept-empty-variations-seed-signature
--disable-variations-seed-fetch-throttling
```

**`Example`** | **`Example`**
---------------|----------------

</details>

#### `Test Case #5` - Upgrade from `1.69.102 Chromium: 127.0.6533.43` -> `1.69.110 Chromium: 127.0.6533.43` - **`PASSED`**

<details>

STR/Cases:

* installed `1.69.102 Chromium: 127.0.6533.43` and relaunched so the studies are applied/visible via `brave://version`
* upgraded to `1.69.110 Chromium: 127.0.6533.43` via `brave://settings/help`
* ensured that once updated, the variations/studies are still visible/being applied via `brave://version`

`1.69.102 Chromium: 127.0.6533.43` | `1.69.110 Chromium: 127.0.6533.43`
----------------------------------------|------------------------------------------

</details>

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 AP31.240617.009 release-keys
Brave build: 1.68.125
Chromium: 127.0.6533.57 (Official Build) (64-bit) 
```
---------------------------

<details>
<summary> Test Case 1 - By default "https://variations.brave.com/seed" is used </summary>

**STEPS:**
1. Launch Brave
2. Open `brave://version` > *Verify*

**ACTUAL RESULTS:**
- Verified that `--variations-server-url=https://variations.brave.com/seed` is shown via `brave://version`
- Verified that `--variations-insecure-server-url=https://variations.brave.com/seed` is shown via `brave://version`

---------------------------

`Galaxy Tab S8`

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/86e7f8e7-b9df-4bd7-9ddb-344113cb3939) | ![2](https://github.com/user-attachments/assets/eeef24a3-3b1a-40a6-bca2-ad03bb96c2d0) |

`Pixel 7`

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/1646eacc-e159-44da-922d-d851015c7709) | ![2](https://github.com/user-attachments/assets/1a9bd068-5e2b-49ed-8bb4-09e33220c79c) |

</details>

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6 Pro` running `Android 15` using the following build(s):

```
Brave | 1.68.125 Chromium: 127.0.6533.57 (Official Build) (64-bit)
--- | ---
Revision | 14ff4d467fb3eec4e6fc0a2f3e2d3f7b4c8cb788
OS | Android 15; Build/AP31.240617.009; 35; REL
```

#### `Test Case #1` - using `https://variations.brave.com/seed` as default - **`PASSED`**

<details>

STR/Cases:

* installed/launched `1.68.125 Chromium: 127.0.6533.57`
* visited `brave://version` and ensured that the following parameters/switches were being used via `Command Line`
* ensured that `production` variations/studies were being displayed via `brave://version`

```
--variations-server-url=https://variations.brave.com/seed
--variations-insecure-server-url=https://variations.brave.com/seed
```

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|---------------
![Screenshot_20240723-014318](https://github.com/user-attachments/assets/9ddc4277-fe7d-419a-b45d-d3ce9b94f886) | ![Screenshot_20240723-014313](https://github.com/user-attachments/assets/c247e784-9ccd-4544-bad5-7ee4ea814541) | ![Screenshot_20240723-014256](https://github.com/user-attachments/assets/cc7727fc-db53-4d95-b1cf-2e2340555d51)
</details>

#### `Test Case #2` - Setting test seed using `--variations-pr=` - **`PASSED`**

<details>

**`Prerequisite:`** ensured that the network on the device has been disabled before setting `--variations-pr=` 

STR/Cases:

* installed/launched `1.68.125 Chromium: 127.0.6533.57`
* added `--variations-pr=`1123` via `Command Line String` under the `QA Developer` settings
* closed Brave and re-enabled the devices network/WiFi
* visited `brave://version` and ensured there was nothing being listed under `Variations` via `brave://version`
* restarted `1.68.125 Chromium: 127.0.6533.57` once again after waiting `~10s`
* ensured that the following parameters/switches are present/visible under `Command Line`

```
--accept-empty-variations-seed-signature
--disable-variations-seed-fetch-throttling
--variations-server-url=https://griffin.brave.com/pull/1123/seed
--variations-insecure-server-url=https://griffin.brave.com/pull/1123/seed
```

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|---------------|------------------|--------------
![Screenshot_20240723-014749](https://github.com/user-attachments/assets/18a5f630-ab94-4b33-886d-9e8457cbda5b) | ![Screenshot_20240723-014823](https://github.com/user-attachments/assets/20a54b52-ee27-49d9-b094-e4557feeaace) | ![Screenshot_20240723-014908](https://github.com/user-attachments/assets/91f3f3d6-113b-434d-a478-de05c4d20d74) | ![Screenshot_20240723-014924](https://github.com/user-attachments/assets/29f739c5-10e8-41d1-8cbb-3fd2a3a509ae) | ![Screenshot_20240723-014941](https://github.com/user-attachments/assets/d1f78de2-84c7-4421-aff5-83ced21e128f) | ![Screenshot_20240723-014959](https://github.com/user-attachments/assets/a74ab8d9-ecc6-4f87-a5ff-47967d16f7a7)

* ensured that `pull/1123@1082ba20390784d33de2b4e6275434deef6c4633
BraveAdsAdEventStudy:Enabled` is being displayed under `Active variations:` via `brave://version`

![Screenshot_20240723-015009](https://github.com/user-attachments/assets/32bf7983-b837-4820-bc9b-a9876b5001da)
</details>

#### `Test Case #3` - ensuring `https://variations.brave.com/seed` is being restored - **`PASSED`**

<details>

STR/Cases:

* after running through `Test Case #2` above, removed `--variations-pr=1123` from the  `Command Line String` under the `QA Developer` settings and restarted `1.69.113 Chromium: 127.0.6533.43`
* waited `~10s` and restarted `1.69.113 Chromium: 127.0.6533.43` once again
* ensured that the following two parameters/switches are visible under `Command Line` via `brave://version`

```
--variations-server-url=https://variations.brave.com/seed
--variations-insecure-server-url=https://variations.brave.com/seed
```

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------
![Screenshot_20240723-015328](https://github.com/user-attachments/assets/6d6798fe-c444-486a-9205-58bcd8471173) | ![Screenshot_20240723-015443](https://github.com/user-attachments/assets/228ad013-eb73-4af6-b5b6-a133358b2acb) | ![Screenshot_20240723-015512](https://github.com/user-attachments/assets/efb36775-155d-41bb-a3e3-ad937746de28) | ![Screenshot_20240723-015531](https://github.com/user-attachments/assets/86bd8eab-516b-4eee-a7be-ce9f33dff148)

* ensured that the following parameters/switches are not visible/present via `Command Line` under `brave://version`

```
--accept-empty-variations-seed-signature
--disable-variations-seed-fetch-throttling
```

**`Example`** | **`Example`**
---------------|----------------
![Screenshot_20240723-015645](https://github.com/user-attachments/assets/de5eac09-af0c-4755-b255-59b2135966f8) | ![Screenshot_20240723-015633](https://github.com/user-attachments/assets/3cf342fd-97d3-412b-a862-cbbd5a5c7eb9)
</details>

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 17.5.1` using the following build(s):

```
Brave | 1.68.130 Chromium: 127.0.6533.73 (Official Build) stable (64-bit) 
--- | ---
Revision | 841d137ffede...
OS | iOS
```

#### `Test Case #1` - using `https://variations.brave.com/seed` as default - **`PASSED`**

<details>

STR/Cases:

* installed `1.68.130 Chromium: 127.0.6533.73` via TF
* visited `brave://version` and ensured that there's no studies/variations being listed
* restarted `1.68.130 Chromium: 127.0.6533.73` once again
* visited `brave://version` and ensured that the following parameters/switches were being used via `Command Line`
* ensured that `production` variations/studies were being displayed via `brave://version`

```
--variations-server-url=https://variations.brave.com/seed
--variations-insecure-server-url=https://variations.brave.com/seed
```

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------
![IMG_0417](https://github.com/user-attachments/assets/8e191915-a6b6-47fe-9d43-6d059eea6128) | ![IMG_0419](https://github.com/user-attachments/assets/48d0787b-1ba3-4ac6-b230-ee1919675580) | ![IMG_0418](https://github.com/user-attachments/assets/324d41b5-0592-424e-afae-12101b7f3b03)

</details>

#### `Test Case #2` - Setting test seed using `--variations-pr=` - **`PASSED`** (using provided switch)

<details>

**`Prerequisite:`** ensured that the network on the device has been disabled before setting `--variations-pr=` 

STR/Cases:

* installed `1.68.130 Chromium: 127.0.6533.73` via TF
* enabled the `Variations PR` switch under `BraveCore Switches` and entered `1123` as the value
* closed Brave and re-enabled the devices network/WiFi
* visited `brave://version` and ensured there was nothing being listed under `Variations` via `brave://version`
* restarted `1.68.130 Chromium: 127.0.6533.73` once again after waiting `~10s`
* ensured that the following parameters/switches are present/visible under `Command Line`

```
--accept-empty-variations-seed-signature
--disable-variations-seed-fetch-throttling
--variations-server-url=https://griffin.brave.com/pull/1123/seed
--variations-insecure-server-url=https://griffin.brave.com/pull/1123/seed
```

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** 
---------------|-----------------|----------------|---------------|-----------------|----------------
![IMG_0420](https://github.com/user-attachments/assets/350a09db-2f59-4e3c-a211-f3a00526344b) | ![IMG_0421](https://github.com/user-attachments/assets/d04e862d-c3cb-4188-b2ea-d851032cfc7c) | ![IMG_0422](https://github.com/user-attachments/assets/4d305981-f9f6-474a-ae70-30a45212be6f) | ![IMG_0423](https://github.com/user-attachments/assets/93d07268-91d7-4e3d-a7f9-f44272c5ecfa) | ![IMG_0424](https://github.com/user-attachments/assets/7e56b9a6-e39b-4ad0-8b6b-c1c886370685) | ![IMG_0425](https://github.com/user-attachments/assets/59c9f801-57a8-4421-afab-6f5ae1b8eef2)

* ensured that `pull/1123@1082ba20390784d33de2b4e6275434deef6c4633
BraveAdsAdEventStudy:Enabled` is being displayed under `Active variations:` via `brave://version`

![IMG_0426](https://github.com/user-attachments/assets/c8ab8d31-1ddd-4910-a9bf-0351c1b7501a)
</details>

#### `Test Case #3` - ensuring `https://variations.brave.com/seed` is being restored - **`PASSED`**

<details>

STR/Cases:

* after running through `Test Case #2` above, removed `--variations-pr=1123` from the  `Command Line String` under the `QA Developer` settings and restarted `1.68.130 Chromium: 127.0.6533.73`
* waited `~10s` and restarted `1.68.130 Chromium: 127.0.6533.73` once again
* ensured that the following two parameters/switches are visible under `Command Line` via `brave://version`

```
--variations-server-url=https://variations.brave.com/seed
--variations-insecure-server-url=https://variations.brave.com/seed
```

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------|------------------
![IMG_0427](https://github.com/user-attachments/assets/02fe3713-391d-4e5a-8d3f-81852aa484d5) | ![IMG_0428](https://github.com/user-attachments/assets/606fb657-1e0f-4c3c-9846-60a33c55651e) | ![IMG_0429](https://github.com/user-attachments/assets/03999901-4e53-48b0-9127-9cdbc8a45cd2) | ![IMG_0430](https://github.com/user-attachments/assets/fa0340ed-19df-484f-8f15-7dc43e7f6aa1) | ![IMG_0431](https://github.com/user-attachments/assets/bf117e6d-21fb-45f6-8574-a9a3c422c103)

* ensured that the following parameters/switches are not visible/present via `Command Line` under `brave://version`

```
--accept-empty-variations-seed-signature
--disable-variations-seed-fetch-throttling
```

**`Example`** | **`Example`**
---------------|----------------
![IMG_0432](https://github.com/user-attachments/assets/2103b667-b981-486c-b143-dee1d1935e0d) | ![IMG_0433](https://github.com/user-attachments/assets/061cbd8d-d918-488b-8471-009d8bd5fcd6)
</details>
