### ISSUE TITLE
Show origin on file chooser dialog

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#39682]
Currently we don't show origin, e.g. search.brave.com, where file chooser dialog was triggered. We should show origin on top of the chooser

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.70.30 Chromium: 127.0.6533.73 (Official Build) nightly (x86_64)
-- | --
Revision | 252bfcfa10e3f2a7e92ee1be5b9e488ab43b7218
OS | macOS Version 11.7.10 (Build 20G1427)
```

## File open - `PASSED`
<details>

### Steps:
1. installed `1.70.30`
2. launched Brave
3. opened `Developer Tools`
4. opened `Console`
5. pasted
6. typed `allow pasting`
7. pasted again

### Confirmed the site's origin appears at the top of the file picker (`brave://version`)

<img width="1312" alt="Screen Shot 2024-07-30 at 11 38 15 AM" src="https://github.com/user-attachments/assets/cbe1f099-0ef6-4cfe-9241-60e75d3521cf">

</details>

## File save as - `PASSED`
<details>

### Steps:
1. installed `1.70.30`
2. launched Brave
3. loaded `https://www.leaseweb.com/en/why-leaseweb/platform/network`
4. right-clicked and chose `Save file as...`

### Confirmed the site's origin appears at the top of the file picker

<img width="1312" alt="Screen Shot 2024-07-30 at 11 39 05 AM" src="https://github.com/user-attachments/assets/028ddeb8-6ed1-4d04-a4e8-12af65e2946c">

</details>

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.70.94 Chromium: 128.0.6613.114 (Official Build) beta (64-bit)
-- | --
Revision | 7ee7ec28264896bd8a9aff39cdb9432da38be028
OS | Windows 10 Version 22H2 (Build 19045.4780)
```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave	1.70.110 Chromium: 128.0.6613.138 (Official Build) beta (64-bit) 
Revision	7dec99ca278e09ce2087e9f04914f0aa2507ea4c
OS	Linux
```
- Verified the test plan from https://github.com/brave/brave-core/pull/24620

### For file open

Confirmed the site's origin appears at the top of the file picker (brave://version)

Example | Example
----------|---------
![image](https://github.com/user-attachments/assets/c854b64f-9a72-4f7d-8809-be8ad09f85c2) | ![image](https://github.com/user-attachments/assets/ea33cdf3-bf01-4dfe-99d0-b95bfb7a946d)


### For file save

Confirmed the site's origin appears at the top of the file picker
