### ISSUE TITLE
Leo - Code block style updates

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#39694]
### Platforms

iOS

### Description

Add a header with a copy button to markdown code blocks. The copy button should copy all of the code in the code block.
Add line numbers beside each line in the code block.

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6.1
Brave build: 1.69 (160)
BraveCore: 1.69.160 (128.0.6613.114)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/24606#issue-2403406044
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Copy` button copies the code in the code block
- Verified that line numbers are displayed beside each line (aligned to the top line when lines wrap)

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/4bab36a4-7db8-4143-8e34-696b7b0baba7) | ![2](https://github.com/user-attachments/assets/995203dd-2dea-416b-9997-158953d0af7a) | ![3](https://github.com/user-attachments/assets/401f7bda-e138-4421-8ac6-acc55514ff6a) |
| ![1](https://github.com/user-attachments/assets/151f5b4d-6b80-45f4-bd28-a8e445bbecbe) | ![2](https://github.com/user-attachments/assets/24072f82-e7ba-4da4-a9bb-c330dce0b821) | ![3](https://github.com/user-attachments/assets/f7d680ed-0bc0-43b1-8750-9c1dd949313c) |
