### ISSUE TITLE
Implement SafeSign for LiFi bridge transactions (core)

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#39701]
### Description

Currently, the ABI decoder cannot parse cross-chain bridge transactions, which results in blind-signing 

### Steps to reproduce

1. Go to Bridge page, and fetch a quote from LiFi
2. Create bridge transaction to popup for signing panel

### Actual result

Incorrect transaction info is seen in the signing panel, with no details about the bridge transaction.

### Expected result

A signing screen similar to SafeSign for EVM swaps.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.0 Chromium: 127.0.6533.26 (Developer Build) (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [X] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.69.118` or higher for `1.69.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.136 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 47255350e0d135b2172cb9dd2ba344d3d7fe4572
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from  issue description
- Verified Safe Sign panel is shown for bridge transaction

https://github.com/user-attachments/assets/7cfdc025-9405-4532-a072-bf1389c6e5fe
