### ISSUE TITLE
[ads] Only consider client and server error responses as error pages

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#39706]
Only report `{"httpResponseStatus": "errorPage"}` in confirmation token redemption payloads for site visit/page land 4xx/5xx HTTP response code errors.

**Comment by btlechowski** [comment]
Verified with

Brave | 1.69.139 Chromium: 127.0.6533.100 (Official Build) beta (64-bit)
-- | --
Revision | 0da988816510c06ff835a14b500d5ab861e18d6e
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/24613


#### 404
<details>


</details>

#### 500
<details>


</details>

**Comment by btlechowski** [comment]
Verification passed on Brave v1.69.145 on Lenovo TB-8506FS (Android 11.0)

Verified test plan from https://github.com/brave/brave-core/pull/24613

#### 404
<details>


</details>

#### 500
<details>


</details>

**Comment by btlechowski** [comment]
Verification passed on Brave v1.69.145 on Lenovo TB-8506FS (Android 11.0)

`"httpResponseStatus": "errorPage"` is not attached to confirmation request. Logged https://github.com/brave/brave-browser/issues/40520

**Comment by btlechowski** [comment]
Verification passed on Brave v1.69.160 on iPhone 13 Pro Max (iOS 17.5.1)

#### 404

<details>



Verified `"httpResponseStatus": "errorPage"` is included in the confirmation

```

```


</details>



#### 500

<details>



Verified `"httpResponseStatus": "errorPage"` is included in the confirmation

```


```


</details>
