### ISSUE TITLE
[Brave Leo]: add Leo icon to top-right toolbar and drop-down menu

### ISSUE THREAD

**Issue by LorenzoMinto** [brave/brave-browser#39713]
### Description

We’ve received a lot feedback around “Not being able to find Leo”. And once found, user might find it hard to dismiss it or bring it back into view because of the unfamiliarity with the sidebar element. If we want Leo to be a prominent browser feature we should give it proper placement and make it a feature with one-click access. In the longer term this could become the general access to Browser AI features (not just chat). Note that this placement would not have the risk to conflict with the Search AI feature as it’s not directly related to a query or to search real estate (omnibox)

<img width="401" alt="Screenshot 2024-07-11 at 19 10 21" src="https://github.com/user-attachments/assets/67e7eefa-eecb-44bc-a313-4d666388d152">

![Image](https://github.com/user-attachments/assets/1e2976cd-a698-4f2c-adba-977850108ae3)

Clicking the Leo tool would open the Leo panel, preferably without the sidebar component.

### Toolbar button opens panel
- Click toolbar button
- Expect Leo panel to open

### Toolbar button closes panel
- Open Leo panel
- Click toolbar button
- Expect Leo panel to close

### Toolbar button switches panel
- Open bookmarks panel
- Click toolbar button
- Expect Leo panel to open

#### Same as above for menu item
Repeat previous tests but instead of toolbar button, use the menu item

#### Same as above for quick command
Repeat previous tests but instead of toolbar button, use the quick command "Toggle Leo"

#### Toolbar button, menu item and quick command do not show up in private window
- Open private window
- Expect none of these new features to show

#### Toolbar button, menu item and quick command do not show up when feature flag is disabled
- Disable AI Chat feature flag
- Expect none of these new features to show

#### Toolbar button, menu item and quick command do not show up when Windows policy disables it
- Re-enable AI Chat feature flag
- Disable AI Chat via Windows policy
- Expect none of these new features to show

**Comment by aguscruiz** [comment]
Adding Figmas here:

**Toolbar**
https://www.figma.com/design/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?node-id=186-17108&t=j3b9wsG8zVDqEP1Q-1

**Menu**
https://www.figma.com/design/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?node-id=6697-27337&t=j3b9wsG8zVDqEP1Q-1

**Comment by petemill** [comment]
The button will still open the SideBar, for now at least, and respect the user's sidebar settings on close. The button will Toggle Leo open or closed. I experimented with the button being highlighted if the Leo panel is showing, but it made the toolbar look like an airplane cockpit given the Sidebar button also highlights (see below), so I'll remove that for now



![Image](https://github.com/user-attachments/assets/b66c3804-96ec-43ac-a4fb-9077b21aa604)

**Comment by kjozwiak** [comment]
The above requires `1.69.147` or higher for `1.69.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.69.149 Chromium: 128.0.6613.40 (Official Build) (x86_64)
-- | --
Revision | a6a137ec4f7f0b30e1d3940dbfcde72c32d35baa
OS | macOS Version 13.6.9 (Build 22G830)
```

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.69.149 Chromium: 128.0.6613.40 (Official Build) (64-bit)
-- | --
Revision | a6a137ec4f7f0b30e1d3940dbfcde72c32d35baa
OS | Windows 10 Version 22H2 (Build 19045.4780)
```
