### ISSUE TITLE
Have the Windows installer pin Brave to the taskbar

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#3971]
This issue is to track having the installer of Brave automatically pin Brave to the taskbar. 
I'm not certain if this is still possible in Windows 10, but it used to be possible.
This will certainly help retain engagement for new users.

**Comment by rebron** [comment]
cc: @simonhong

**Comment by simonhong** [comment]
On Win10, chromium prevents pinning to taskbar explicitly.
Why chromium prevents it?
```
  // Win10 actively prevents creating shortcuts on the taskbar so we eliminate
  // that option from the dialog.
  if (base::win::CanPinShortcutToTaskbar()) {
```
```
bool CanPinShortcutToTaskbar() {
  // "Pin to taskbar" stopped being supported in Windows 10.
  return GetVersion() < Version::WIN10;
}

bool PinShortcutToTaskbar(const FilePath& shortcut) {
  ScopedBlockingCall scoped_blocking_call(FROM_HERE, BlockingType::MAY_BLOCK);
  DCHECK(CanPinShortcutToTaskbar());

  intptr_t result = reinterpret_cast<intptr_t>(ShellExecute(
      NULL, L"taskbarpin", as_wcstr(shortcut.value()), NULL, NULL, 0));
  return result > 32;
}
```

**Comment by simonhong** [comment]
According to comments in code review(https://codereview.chromium.org/1402003002/diff2/20001:60001/base/win/shortcut.cc), pin/unpin w/o user interaction are not allowed on Win10.

**Comment by simonhong** [comment]
Close because pin/unpin shortcuts to taskbar w/o user action are not allowed on Win10.
