### ISSUE TITLE
"Reset permissions" button text color is incorrect after being selected/clicked on - regressed between 1.68.116 and 1.68.117

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#39719]
### Description

Something that landed between 1.68.116 and 1.68.117 regressed the "Reset permissions" button text color when the button is selected.

The change is most obvious on dark theme, but also slightly different on light theme.

### Steps to reproduce

1. Install 1.68.116
2. Navigate to `permission.site`
3. Allow/block at least one item (I allowed one item, blocked one item)
4. Click on the tune icon in URL bar
5. Click on "Reset permissions"
6. After being selected, button text is still visible (for both light and dark theme)
7. Repeat above steps with 1.68.117 for both light and dark theme

### Actual result

Using 1.68.117 the "Reset permission" button text color is different than 1.68.116. Difference is slight for light theme but obvious in dark theme since the text appears to be missing, but is probably just dark on dark.

Light | Dark
--- | ---
<img width="774" alt="117 lt" src="https://github.com/user-attachments/assets/b39293cf-79eb-4d1d-8ffd-fa3d4fa5d2c6"> | <img width="761" alt="117 dk" src="https://github.com/user-attachments/assets/8fd0c23e-3b91-4b54-9c6a-db1ec51c3524">

Here's 1.68.116 vs 1.68.117 for light theme side by side to see the slight difference

1.68.116 | 1.68.117
--- | ---
<img width="337" alt="Screenshot 2024-07-12 at 10 29 31 AM" src="https://github.com/user-attachments/assets/b7c20b70-1257-4633-9ff3-b292d6072748"> | <img width="327" alt="Screenshot 2024-07-12 at 10 29 39 AM" src="https://github.com/user-attachments/assets/414211ff-cbb6-4d52-9fe1-dda51dad3fad">

### Expected result

Button text color for both light and dark theme should be visible, how it is in 1.68.116 for both themes

Light | Dark
--- | ---
<img width="643" alt="116 lt" src="https://github.com/user-attachments/assets/bc8206d5-e34a-43d4-a82b-867325c63222"> | <img width="679" alt="116 dk" src="https://github.com/user-attachments/assets/a7b31519-b45a-4f7e-9823-9fd73db23428">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.117, 1.67.118 - Beta

1.69.98 - Nightly

### Channel information

- [ ] release (stable)
- [X] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @brave/qa-team

**Comment by simonhong** [comment]
checking now.

**Comment by kjozwiak** [comment]
The above requires `1.68.122` or higher for `1.68.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.68.122 Chromium: 127.0.6533.43 (Official Build) beta (x86_64)
-- | --
Revision | d9f43bf666718cb9878eab117e104f5d5d39bbbe
OS | macOS Version 13.6.7 (Build 22G720)
```
