### ISSUE TITLE
Update Play Billing Library

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#39714]
## Description 

We need to upgrade billing client dependency to 7.0.0.

**Comment by kjozwiak** [comment]
Used the same STR/Cases that were completed via https://github.com/brave/brave-browser/issues/40078#issuecomment-2258736214 after discussing with @deeppandya.

Verification **PASSED** on `Pixel 6 Pro` running `Android 15` using the following build(s):

```
Brave | 1.69.147 Chromium: 128.0.6613.40 (Official Build) (64-bit)
--- | ---
Revision | d29b1747d0f906239936b0d94c40889920ebf2c0
OS | Android 15; Build/AP31.240617.015; 35; REL
```

### `Test Case #1` - New GPS Account (has never subscribed to premium)

* created a brand new Google account and @deeppandya added it into the GPS internal release channel
* verified that the new account had access to `1.69.147 Chromium: 128.0.6613.40` via the internal release test channel
* downloaded/launched `1.69.147 Chromium: 128.0.6613.40`
* tapped on the `Hamburger Menu` -> `VPN` -> `7 Day Free Trial`
* ensured that the purchase card was being displayed without any issues
* ensured that you can run through the Billing API and subscribe/enable VPN

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------
![1000001999](https://github.com/user-attachments/assets/7cbd3cb9-3c22-4418-8985-d1bb537d3791) | ![1000002000](https://github.com/user-attachments/assets/ea1d69ac-3fec-4ddc-96e0-ae7d08f907cb) | ![1000002001](https://github.com/user-attachments/assets/edd0496f-bec5-45ed-b4b5-0d99121a2d9c) | ![1000002002](https://github.com/user-attachments/assets/2f18d376-1e72-44f6-97c5-88ddfe2356bd) | ![1000002003](https://github.com/user-attachments/assets/f9158f86-103e-4676-896f-5075a8525542) | ![1000002004](https://github.com/user-attachments/assets/2fe37581-d465-4bdd-a7cd-b580c9273002) | ![1000002005](https://github.com/user-attachments/assets/924f63f0-76b2-4d24-9b0e-efaf43cfeb1f) | ![1000002006](https://github.com/user-attachments/assets/34965428-007f-4b22-a33b-3e7e583f3a9e)

### `Test Case #2` - Using previous/older account (has subscribed to Premium before)

* download/installed `1.68.137 Chromium: 127.0.6533.100`
* upgraded from `1.68.137 Chromium: 127.0.6533.100` --> `1.69.147 Chromium: 128.0.6613.40` via the internal test channel
* tapped on the `Hamburger Menu` -> `VPN` -> `7 Day Free Trial`
* ensured that the purchase card was being displayed without any issues (used the `test card` for this case as discussed)
