### ISSUE TITLE
Remove redundant sidebar settings in brave://settings/appearance again

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#39718]
### Description

Upstream switched their sidebar settings to use a dropdown instead of radio buttons. As part of this change, they modified the name and layout of the HTML in such a way that we're no longer hiding these redundant settings (similar to https://github.com/brave/brave-browser/issues/39382).

### Steps to reproduce

1. Clean profile
2. Open brave://settings/appearance

### Actual result

Redundant sidebar settings appear under "Appearance"

### Expected result

No sidebar settings should appear under "Appearance" section

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Latest master

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.68.122` or higher for `1.68.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.68.122 Chromium: 127.0.6533.43 (Official Build) beta (x86_64)
-- | --
Revision | d9f43bf666718cb9878eab117e104f5d5d39bbbe
OS | macOS Version 11.7.10 (Build 20G1427)
```
