### ISSUE TITLE
Consider making default browser prompt show on first startup instead of second

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#3972]
We currently only show this bar as of the 2nd startup and beyond:
<img width="472" alt="Screen Shot 2019-04-02 at 1 12 22 PM" src="https://user-images.githubusercontent.com/831718/55422173-09fc1600-5549-11e9-811e-3c5e34b1c166.png">

But some users that install only open the browser once.
This issue is to track showing the bar even on the first startup.

**Comment by naukarialerts4u** [comment]
Yeah it is common for every one whether it is brave browser or Firefox its always popup for default browser settings

**Comment by bbondy** [comment]
This may be considered but I'll close as stale for now because we should use Github for definitive work that we want to do and it can be reposted later if we want to.

**Comment by rebron** [comment]
We also show `set as default` as initial screen on first launch.

![Image](https://github.com/brave/brave-browser/assets/5951041/56c5b801-10fe-4fef-9658-f8021347d124)
