### ISSUE TITLE
`if you are not sure` should read `if you're not sure` in tooltip for Server endpoint URL in BYOM

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#39729]
### Description

`if you are not sure` should read `if you're not sure` in tooltip for Server endpoint URL in BYOM

Found while testing https://github.com/brave/brave-browser/issues/38646

### Steps to reproduce

1. install `1.69.101`
2. launch Brave
3. open `brave://settings/leo-assistant`
4. click on `Add new model`
5. hover over `Server endpoint (i)`
6. look at the resulting tooltip

### Actual result

`...if you are not sure...` 

<img width="1360" alt="Screen Shot 2024-07-12 at 11 48 38 AM" src="https://github.com/user-attachments/assets/9e99d471-6ab5-46f7-b7b0-488748bc169a">

### Expected result

Should probably read `"...if you're not sure..."` <img width="724" alt="Screen Shot 2024-07-12 at 11 48 14 AM" src="https://github.com/user-attachments/assets/8690ee3f-4c88-4cea-9bdd-7f333dc8c10e">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.69.101 Chromium: 127.0.6533.43 (Official Build) nightly (x86_64)
-- | --
Revision | 9073515479afc03ab66a21bb8175263fc56ba1f1
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rmcfadden3 @macauleyberg @nullhook @rebron @mattmcalister @petemill @bbondy

**Comment by rmcfadden3** [comment]
@stephendonner `you are` the best

**Comment by stephendonner** [comment]
> @stephendonner `you are` the best

No, @rmcfadden3 `you're` the best

**Comment by bsclifton** [comment]
Commander Data does not approve of this 😂 
![image](https://github.com/user-attachments/assets/a7b07729-8d87-473a-b6b9-2015e1692fe5)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.69.115 Chromium: 127.0.6533.43 (Official Build) nightly (64-bit)
-- | --
Revision | 0f3c95cf9cac0acfd6d49bd72bb2ed548901a082
OS | Windows 10 Version 22H2 (Build 19045.4651)
```

## `Leo` strings

example | example | example
----------|----------|----------
![image](https://github.com/user-attachments/assets/deedc9cb-0d2a-4682-b392-940f046e2262) | ![image](https://github.com/user-attachments/assets/cf99ce77-ebce-46c2-bbba-c87bdf0fa4ca) | ![image](https://github.com/user-attachments/assets/3935585c-6224-4f10-82e5-6e6db49d57ba)


## `Tor` bridges

example | example
----------|----------
![image](https://github.com/user-attachments/assets/4b211db2-97d0-442b-8e13-b1af91b20a17) | ![image](https://github.com/user-attachments/assets/069912fe-1253-4ef9-b92d-e4fb159551e3)
