### ISSUE TITLE
[CR 127] Font size and weight are incorrect in brave://history

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#39722]
### Description

In brave://history, the `font-size is 12` and `font-weight 500`. It should be `font-size 13` and `font-weight 400`

### Steps to reproduce

1. Go to brave://history
2. Have some entries and notice font size and weight.
3. 

### Actual result

CR 127 1.68.x and higher
<img width="957" alt="Screenshot 2024-07-11 at 3 56 21 PM" src="https://github.com/user-attachments/assets/3eb86144-f6b8-4c54-b380-741a57131841">

### Expected result

1.67.123 
<img width="1013" alt="Screenshot 2024-07-12 at 9 42 50 AM" src="https://github.com/user-attachments/assets/ba63af24-0e72-4d6e-995b-a33397c78ff9">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.x with CR127

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by simonhong** [comment]
checking.

**Comment by kjozwiak** [comment]
The above requires `1.68.123` or higher for `1.68.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.68.123 Chromium: 127.0.6533.43 (Official Build) beta (x86_64)
-- | --
Revision | ef3647583d97eb71b681111dd9949d91060691ba
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.68.123`
2. launched Brave
3. opened `Developer Tools`
4. browsed a few news-related sites to generate history
5. opened `brave://history`
6. clicked on `Select an element on the page to inspect it`
7. focused on a history-item's entry

### Confirmed `font-size: 13` and `font-weight: 400px`


<img width="1312" alt="Screen Shot 2024-07-17 at 9 38 58 PM" src="https://github.com/user-attachments/assets/068e2f9f-2fea-4c8c-aeb3-6ba49342b176">
