### ISSUE TITLE
iOS transaction confirmation panel contract address link out

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#39720]
### Platforms

iOS

### Description

When sending to a contract address, should treat the contract address as a link to the block explorer in the transaction confirmation panel and link out to the iOS browser when tapped on, similar to desktop behaviour:

<img width="387" alt="Transaction Confirmation Contract Address Link Out" src="https://github.com/user-attachments/assets/66b98736-93ba-4cd6-a4df-c030f0b86641">

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18 running 1.70 (119)
- Verified steps from [brave/brave-core#24686](https://github.com/brave/brave-core/pull/24686)
- Verified Address continues to show as truncated address
- Verified Contract address shows as truncated address with a hyper link to load in new tab
- Verified named address continues to show the name 

![image](https://github.com/user-attachments/assets/6bf4aa9a-fb90-459a-8ee4-b7b4b8241ae7) | ![image](https://github.com/user-attachments/assets/26ce6e53-9138-4d15-9c42-4f42af545bc1) | ![image](https://github.com/user-attachments/assets/07057a72-a83b-4008-8f7e-251ee82a10b5)
-- | -- | --
