### ISSUE TITLE
Fix gas fee on low fee networks

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#39733]
### Description

Gas fee is currently rounded to 6 decimals of precision which can cause some display issues for cases of low gas fees.

Reported by @kdenhartog 

### Steps to reproduce

1. Create a send transaction on a lower fee network like Optimism EVM
2. In transaction confirmation, observe Gas Fee is displayed as `<amount> + 0 ETH`

### Actual result

<img src="https://github.com/user-attachments/assets/ca4fc618-fed0-4400-83e5-692ff2ed45eb" width="300">

### Expected result

Non-zero gas fee when fee is non-zero

### Reproduces how often

Easily reproduced

### Brave version

All

### Device/iOS version

iOS 17

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

Gas fee was previously limited to 6 decimals due to screen space, but by trimming trailing zeros now we should be able to display more digits.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.0 Beta running .1.69(147)
- Verified steps from [brave/brave-core#24653](https://github.com/brave/brave-core/pull/24653)
- Verified gas fee doesn't show `0 ETH`
<img width=30 src=https://github.com/user-attachments/assets/972ca345-307a-4122-8eff-2f3e312f0d49>
