### ISSUE TITLE
Improve NTP responsiveness for lower screen resolutions and window sizes

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#39735]
### Description

On the NTP, widgets should be hidden and/or resized to fit the lower resolutions and narrower window sizes.
See Figma: 
https://www.figma.com/design/QCBklDojDtDTKApz10XqSQ/%F0%9F%97%82-New-Tab-Page?node-id=2320-3074&t=EIynvpPdF6enSTCg-0

In 800 x 600:
• update Privacy hub spacing
• update Site shortcuts spacing
• hide the clock widget
• hide cards widget
• The bottom links to customize are reduced
• Hide the "Customize" text
• The ad's company info is centered and
above the search bar

### Steps to reproduce

1. Open the new tab page and display resolution to 800 x 600 in 1.68.x and lower.
2. Compare actual vs expected result.

### Actual result

<img width="956" alt="Screenshot 2024-07-12 at 2 16 26 PM" src="https://github.com/user-attachments/assets/817d7742-48bb-4e2f-89a0-00fbaa92c6ec">

### Expected result

<img width="414" alt="Screenshot 2024-07-12 at 2 11 39 PM" src="https://github.com/user-attachments/assets/c9f83356-e840-4137-9303-1b336ec4279b">
<img width="595" alt="Screenshot 2024-07-12 at 2 11 31 PM" src="https://github.com/user-attachments/assets/e3752aad-d341-4f5d-ae71-84f817a4e48e">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.x

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by LaurenWags** [comment]
Labeling as `QA/Blocked` until https://github.com/brave/brave-browser/issues/39927 is resolved.

**Comment by LaurenWags** [comment]
Removed `QA/Blocked` now that https://github.com/brave/brave-browser/issues/39927 is uplifted to 1.70.x

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.70.107 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | ab3f504ca4a15c330f60a93d5e3773d780498980
OS | Windows 11 Version 23H2 (Build 22631.4112)
```
1. Installed 1.70.11
2. launched Brave
3. opened new tab page

<details>
<summary>Verified with default resolution settings </summary>

![image](https://github.com/user-attachments/assets/543d3fc2-7f9e-4f40-832a-8bd0542ce084)
</details>

<details>
<summary>Narrow</summary>

Confirmed  

- `clock`, `cards widgets`, `Customize` are hidden,
- the photo/takeover credits and/or ad company' info are centered and are moved above the search box
- spacing of Site shortcuts/favorites is updated
- spacing of stats is updated 

example | example | example 
----- | ---- | ----- 
![image](https://github.com/user-attachments/assets/6858cc77-b27c-4424-8e44-99bd9b93b9ae)|![image](https://github.com/user-attachments/assets/55665ffa-6e9b-4571-981e-5e7f787cac2b)|![2024-09-10_16h00_05](https://github.com/user-attachments/assets/2f2a69e0-d748-4493-a0fe-8ff765717e87)
</details>

<details>
<summary>Narrow + short</summary>

Stats should be hidden but seeing them on NTP
However, 1.70.11 (where PR was verified) working as expected

example | 1.70.107 | 1.70.107 | 1.70.11
----- | ---- | ----- | -----
![2024-09-10_17h22_43](https://github.com/user-attachments/assets/0aa9674b-c220-45d7-b120-04108b75575d)|![2024-09-10_17h22_13](https://github.com/user-attachments/assets/b2b8c7a2-82a8-4411-b2af-57f167bae82d)|![2024-09-10_17h23_06](https://github.com/user-attachments/assets/434ada26-aedc-45e3-99ee-ed053b30fbb2)|![2024-09-10_17h58_09](https://github.com/user-attachments/assets/ab44e7ee-8f7a-4e13-a806-76583d88c18b)

</details>

<details>
<summary>Short</summary>

Stats should be hidden but seeing them on NTP
However, 1.70.11 (where PR was verified) working as expected

example | 1.70.107 | 1.70.107 | 1.70.11
----- | ---- | ----- | -----
![image](https://github.com/user-attachments/assets/a801fcbb-a87a-42f9-9194-f87acebadbb2)|![image](https://github.com/user-attachments/assets/df26c721-65c3-4eb0-8cea-4657d83c850a)|![image](https://github.com/user-attachments/assets/e81f858e-3149-4607-bd5b-e7cde338fea7)|![2024-09-10_17h53_06](https://github.com/user-attachments/assets/9dd61a59-4874-471d-91c0-f48d920e5a1d)
</details>

<details>

<summary>800x600</summary>

Stats should be hidden but seeing them on NTP
However, 1.70.11 (where PR was verified) working as expected

example | 1.70.107 | 1.70.107 | 1.70.11
----- | ---- | ----- | -----
![image](https://github.com/user-attachments/assets/2e010297-d938-48f8-bbdc-d0fe322a7012)|![image](https://github.com/user-attachments/assets/c07b786a-ad25-4f32-9b69-d520d73ba481)|![image](https://github.com/user-attachments/assets/579f6bf1-6c22-4488-9825-693de3b9ed4e)|![image](https://github.com/user-attachments/assets/f11a706f-2f13-487e-bfb5-f45133879f85)|![2024-09-10_17h55_42](https://github.com/user-attachments/assets/b2b01c0c-51eb-40f9-b6e8-e13c22c181d7)

</details>

<details>
<summary>Normal </summary>

(21" external monitor)

example | 1.70.107  
----- | ----  
![2024-09-10_18h04_30](https://github.com/user-attachments/assets/1f0649db-e421-4e43-b294-5646216900bd)|![2024-09-10_18h04_40](https://github.com/user-attachments/assets/5d338be4-17c6-403b-8b54-d4c97484faa1)

14" laptop monitor

example | 1.70.107
----- | -----
<img width="960" alt="2024-09-10_18h16_00" src="https://github.com/user-attachments/assets/6b464141-ce78-42fd-ae3e-fa33bc16e541">|<img width="960" alt="2024-09-10_18h16_46" src="https://github.com/user-attachments/assets/bf7de445-17b4-488e-b306-f80544d88404">
