### ISSUE TITLE
[Wallet] Remove circular dependencies in wallet panel

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39731]
### Description

The wallet panel currently has many circular imports. We should try to resolve these to prevent issues

1. `components/brave_wallet_ui/constants/types.ts -> components/brave_wallet_ui/common/hardware/types.ts`
2. `components/brave_wallet_ui/common/hardware/ledgerjs/ledger-messages.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/eth-ledger-messages.ts`
3. `components/brave_wallet_ui/constants/types.ts -> components/brave_wallet_ui/common/hardware/types.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/ledger-messages.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/fil-ledger-messages.ts`
4. `components/brave_wallet_ui/common/hardware/ledgerjs/ledger-messages.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/fil-ledger-messages.ts`
5. `components/brave_wallet_ui/common/hardware/ledgerjs/ledger-messages.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/sol-ledger-messages.ts`
6. `components/brave_wallet_ui/constants/types.ts -> components/brave_wallet_ui/common/hardware/types.ts -> components/brave_wallet_ui/common/api/hardware_keyrings.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/eth_ledger_bridge_keyring.ts`
7. `components/brave_wallet_ui/constants/types.ts -> components/brave_wallet_ui/common/hardware/types.ts -> components/brave_wallet_ui/common/api/hardware_keyrings.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/eth_ledger_bridge_keyring.ts -> components/brave_wallet_ui/common/hardware/interfaces.ts`
8. `components/brave_wallet_ui/common/api/hardware_keyrings.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/eth_ledger_bridge_keyring.ts -> components/brave_wallet_ui/common/hardware/interfaces.ts`
9. `components/brave_wallet_ui/common/hardware/types.ts -> components/brave_wallet_ui/common/api/hardware_keyrings.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/eth_ledger_bridge_keyring.ts -> components/brave_wallet_ui/common/hardware/interfaces.ts`
10. `components/brave_wallet_ui/common/hardware/types.ts -> components/brave_wallet_ui/common/api/hardware_keyrings.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/eth_ledger_bridge_keyring.ts`
11. `components/brave_wallet_ui/constants/types.ts -> components/brave_wallet_ui/common/hardware/types.ts -> components/brave_wallet_ui/common/api/hardware_keyrings.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/eth_ledger_bridge_keyring.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/ledger_bridge_keyring.ts`
12. `components/brave_wallet_ui/common/api/hardware_keyrings.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/eth_ledger_bridge_keyring.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/ledger_bridge_keyring.ts`
13. `components/brave_wallet_ui/common/hardware/types.ts -> components/brave_wallet_ui/common/api/hardware_keyrings.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/eth_ledger_bridge_keyring.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/ledger_bridge_keyring.ts`
14. `components/brave_wallet_ui/constants/types.ts -> components/brave_wallet_ui/common/hardware/types.ts -> components/brave_wallet_ui/common/api/hardware_keyrings.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/eth_ledger_bridge_keyring.ts -> components/brave_wallet_ui/utils/derivation_path_utils.ts`
15. `components/brave_wallet_ui/common/hardware/types.ts -> components/brave_wallet_ui/common/api/hardware_keyrings.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/eth_ledger_bridge_keyring.ts -> components/brave_wallet_ui/utils/derivation_path_utils.ts`
16. `components/brave_wallet_ui/constants/types.ts -> components/brave_wallet_ui/common/hardware/types.ts -> components/brave_wallet_ui/common/api/hardware_keyrings.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/sol_ledger_bridge_keyring.ts`
17. `components/brave_wallet_ui/common/hardware/types.ts -> components/brave_wallet_ui/common/api/hardware_keyrings.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/sol_ledger_bridge_keyring.ts`
18. `components/brave_wallet_ui/constants/types.ts -> components/brave_wallet_ui/common/hardware/types.ts -> components/brave_wallet_ui/common/api/hardware_keyrings.ts -> components/brave_wallet_ui/common/hardware/trezor/trezor_bridge_keyring.ts`
19. `components/brave_wallet_ui/common/hardware/types.ts -> components/brave_wallet_ui/common/api/hardware_keyrings.ts -> components/brave_wallet_ui/common/hardware/trezor/trezor_bridge_keyring.ts`
20. `components/brave_wallet_ui/common/api/hardware_keyrings.ts -> components/brave_wallet_ui/common/hardware/trezor/trezor_bridge_keyring.ts`
21. `components/brave_wallet_ui/constants/types.ts -> components/brave_wallet_ui/common/hardware/types.ts -> components/brave_wallet_ui/common/api/hardware_keyrings.ts`
22. `components/brave_wallet_ui/constants/types.ts -> components/brave_wallet_ui/common/hardware/types.ts -> components/brave_wallet_ui/common/api/hardware_keyrings.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/fil_ledger_bridge_keyring.ts`
23. `components/brave_wallet_ui/common/api/hardware_keyrings.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/fil_ledger_bridge_keyring.ts`
24. `components/brave_wallet_ui/common/hardware/types.ts -> components/brave_wallet_ui/common/api/hardware_keyrings.ts -> components/brave_wallet_ui/common/hardware/ledgerjs/fil_ledger_bridge_keyring.ts`
25. `components/brave_wallet_ui/common/slices/api.slice.ts -> components/brave_wallet_ui/common/slices/api-base.slice.ts -> components/brave_wallet_ui/utils/query-cache-utils.ts -> components/brave_wallet_ui/common/slices/entities/blockchain-token.entity.ts`
26. `components/brave_wallet_ui/common/slices/api.slice.ts -> components/brave_wallet_ui/common/slices/api-base.slice.ts -> components/brave_wallet_ui/common/async/base-query-cache.ts -> components/brave_wallet_ui/common/slices/entities/account-info.entity.ts`
27. `components/brave_wallet_ui/common/slices/endpoints/account.endpoints.ts -> components/brave_wallet_ui/common/slices/endpoints/network.endpoints.ts`
28. `components/brave_wallet_ui/components/extension/buttons/nav-button/index.tsx -> components/brave_wallet_ui/components/extension/buttons/nav-button/style.ts`
29. `components/brave_wallet_ui/components/extension/dapp-connection-settings/dapp-connection-settings.tsx -> components/brave_wallet_ui/components/extension/dapp-connection-settings/dapp-connection-main.tsx`
30. `components/brave_wallet_ui/components/extension/dapp-connection-settings/dapp-connection-settings.tsx -> components/brave_wallet_ui/components/extension/dapp-connection-settings/dapp-connection-networks.tsx`
31. `components/brave_wallet_ui/components/extension/dapp-connection-settings/dapp-connection-settings.tsx -> components/brave_wallet_ui/components/extension/dapp-connection-settings/dapp-connection-accounts.tsx`

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.138 Chromium: 127.0.6533.100 (Official Build) beta (64-bit)
-- | --
Revision | 2569cce791e23282c250db59de277f2e81c33d9b
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24636](https://github.com/brave/brave-core/pull/24636)
- Verified Hardware wallet connection works as expected
- Verified able to sign transactions on Hardware wallet
- Verified for both Ledger and Trezor hardware wallet
