### ISSUE TITLE
Push wallet result to UI side in extension observer: OnWalletInitialized

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#3974]
Follow up from https://github.com/brave/brave-core/pull/2097

## Description 

extension observer method `OnWalletInitialized` is iterating on wallet creation result on native side. We would like this result to be pushed to client side code and iterated there.

Function in question: https://github.com/brave/brave-core/blob/master/components/brave_rewards/browser/extension_rewards_service_observer.cc#L29-L55

## Steps to Reproduce

   1. 
   2. 
   3. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

dev issue

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.65.93 Chromium: 74.0.3729.131 (Official Build) beta (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.523

- Verified the test plan from https://github.com/brave/brave-core/pull/2233
