### ISSUE TITLE
[NTP]: Use React 18 `createRoot` API

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#39745]
Test plan:

NTP should still load (not a blank screen)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.69.117 Chromium: 127.0.6533.57 (Official Build) beta (x86_64)
-- | --
Revision | 7b5104c54992f658db7f6b1e7441021612ba71a3
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.69.117`
2. launched Brave
3. opened a new-tab page
4. confirmed it loaded
5. clicked on `Customize`
6. clicked on `Show Clock` to enable it
7. scrolled down on the NTP
8. clicked to `Turn on Brave News`

### Confirmed the new-tab page loaded and was customizable

example | example | example | example | example
---------|----------|---------|----------|--------
<img width="1312" alt="Screen Shot 2024-07-18 at 12 41 14 PM" src="https://github.com/user-attachments/assets/e17a18fc-6c77-4280-8304-ab070f929576"> | <img width="1312" alt="Screen Shot 2024-07-18 at 12 44 37 PM" src="https://github.com/user-attachments/assets/c27e95c6-24d9-43db-93ad-49f273ff6967"> | <img width="1312" alt="Screen Shot 2024-07-18 at 12 41 27 PM" src="https://github.com/user-attachments/assets/80ff44c4-26b1-47b4-a63a-a875ec5fb7ca"> | <img width="1312" alt="Screen Shot 2024-07-18 at 12 41 40 PM" src="https://github.com/user-attachments/assets/4545a08a-5522-4035-bf7f-54b57c2f4f5b"> | <img width="1312" alt="Screen Shot 2024-07-18 at 12 41 47 PM" src="https://github.com/user-attachments/assets/b20bad84-0676-4fde-ae60-f5e599b2a348">
