### ISSUE TITLE
Open URL in PWA apps

### ISSUE THREAD

**Issue by tomy0000000** [brave/brave-browser#39740]
### Platforms

Linux, macOS, Windows

### Description

That is exactly what [this post](https://geekermag.com/how-to-open-links-in-microsoft-edge-pwas-web-apps/) is demonstrating.

Say I have https://www.youtube.com installed as a Web App on my machine. It would be great if every time I clicked a YouTube link somewhere, the YouTube App would open the URL instead of the typical Brave Browser.

**Comment by chrisgrieser** [comment]
I found this one in the experimental flags. While not doing so automatically, it puts a button into the address bar to open the link in the PWA, which is at least an improvement.
brave://flags/#enable-user-link-capturing-pwa

**Comment by tomy0000000** [comment]
> I found this one in the experimental flags. While not doing so automatically, it puts a button into the address bar to open the link in the PWA, which is at least an improvement. brave://flags/#enable-user-link-capturing-pwa

I think this flag did enable the URL handler. When I clicked on the open app button, Brave shows an hint telling me that I can customize app behavior in app setting menu. In which, it then tells me that all URL matches https://www.youtube.com/* can now natively opened with YouTube app!
