### ISSUE TITLE
Hide clock by default on the new tab page

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#39742]
### Description

Clock widget on the NTP should be hidden by default for new users. 

### Steps to reproduce

1. Install fresh version of Brave or create a new profile.
2. Compare expected result to actual result

### Actual result

<img width="1473" alt="Screenshot 2024-07-14 at 9 00 54 AM" src="https://github.com/user-attachments/assets/6293c6b7-fb53-4c93-85d1-c16c75efbf45">

### Expected result

<img width="1473" alt="Screenshot 2024-07-14 at 8 55 23 AM" src="https://github.com/user-attachments/assets/1bd3887f-5d9c-4211-9ddd-7c35ff09c4eb">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Target 1.68.x

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.69.115 Chromium: 127.0.6533.43 (Official Build) nightly (64-bit)
-- | --
Revision | 0f3c95cf9cac0acfd6d49bd72bb2ed548901a082
OS | Windows 10 Version 22H2 (Build 19045.4651)
```

## New profiles - `PENDING`
<details>

</details>


## Upgrade scenario - `PENDING`
<details>

</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.69.115 Chromium: 127.0.6533.43 (Official Build) nightly (64-bit)
-- | --
Revision | 0f3c95cf9cac0acfd6d49bd72bb2ed548901a082
OS | Windows 10 Version 22H2 (Build 19045.4651)
```

## New profile - `PASSED`
<details>

### Steps:
1. installed `1.69.115`
2. launched Brave
3. opened a new-tab page
4. confirmed no clock in the upper-right corner
5. clicked on `Customize`
6. confirmed `Show Clock` was defaulted to `Off`/`Enabled`

</details>

## Upgrade scenario - `PASSED`
<details>

### Steps:
1. installed `1.67.134`
2. launched Brave
3. opened a new-tab page
4. confirmed system-clock showing
5. clicked on `Customize`
6. toggled `Show Clock` from `On`/`Enabled` to `Off`/`Disabled`
7. toggled `Show Clock back to `On`/`Enabled` from `Off`/`Disabled`


example | example | example | example
----------|-----------|-----------|----------
![image](https://github.com/user-attachments/assets/5032a095-fb42-4738-99aa-b4f3bf6c9b40) | ![image](https://github.com/user-attachments/assets/13a3fcc8-6cfa-4ed9-8b93-79891c1c6f0c) | ![image](https://github.com/user-attachments/assets/0cd8285e-de8b-4ee2-94b8-bf8a6099a4a9) | ![image](https://github.com/user-attachments/assets/0dce5abc-18ed-435d-8c05-b84667fa9c48)



</details>
