### ISSUE TITLE
Add metrics for NTP search widget

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#39762]
Add the following metrics for the New Tab Page Search widget:

If you used the search widget in the past 7 days, how many queries did you perform this week?
`Brave.Search.WidgetUsage`

0. 1-10
1. 11-30
2. 31-40
3. 41+

If the search widget is enabled, what is your default engine for the search widget?
`Brave.Search.WidgetDefault`

0. Brave
1. Google
2. DDG
3. Qwant
4. Bing
5. Startpage
6. Ecosia
7. Other

cc @rebron

**Comment by kjozwiak** [comment]
The above requires `1.68.123` or higher for `1.68.x` verification 👍
