### ISSUE TITLE
Update source value in NTP Search widget string

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#39763]
### Description

The current value in the NTP Search widget is source=desktop.
The value should be source=newtab

### Steps to reproduce

1. Do a search (Brave Search) in the Search widget from the new tab page in 1.68.x and higher.
2. Notice the Brave Search url shows source=desktop
3. It should be source=newtab

### Actual result

<img width="707" alt="Screenshot 2024-07-15 at 1 08 37 PM" src="https://github.com/user-attachments/assets/f8c3163a-4390-47f3-9d5e-c06fb608a103">

### Expected result

<img width="720" alt="Screenshot 2024-07-15 at 1 09 20 PM" src="https://github.com/user-attachments/assets/9b75b033-873b-40c2-b130-8c4fccd8a89b">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.x

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.69.149` or higher for `1.69.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.69.150 Chromium: 128.0.6613.40 (Official Build) (64-bit)
-- | --
Revision | aea36034a3cccd841545ac66ffb79f21e2ba5dd4
OS | Windows 10 Version 22H2 (Build 19045.4780)

```
