### ISSUE TITLE
Getting `Variations Seed Type` - `Null` when trying to restore production Griffin seed after using pr seed flag

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#39767]
### Description

Getting `Variations Seed Type` - `Null` when trying to restore production Griffin seed after using pr seed flag

This was found whilst testing the 3rd case in https://github.com/brave/brave-browser/issues/39689

### Steps to reproduce

1. install `1.69.108`
2. launch Brave using `--variations-pr=1123`
3. restarted Brave
4. wait 10+ seconds (preferably more, accounting for slow connections/transfers)
5. restart Brave
6. open `brave://version` and confirm the special seed details from https://github.com/brave/brave-browser/issues/39689#issuecomment-2225992829
7. now, remove the `--variations-pr=1123` parameter
8. relaunch Brave
9. wait 10+  seconds (preferably more)
10. open brave://version`

### Actual result

In `brave://version`, it shows:

`Variations Seed Type` is `Null`

![image](https://github.com/user-attachments/assets/b9ecdc14-cd0e-4c82-9952-8164f1be902b)

### Expected result

Since the production Griffin seed was restored, there should be the usual litany of `Active Variations` studies listed, instead:

![image](https://github.com/user-attachments/assets/19b52546-7f90-45fc-aa80-cd2551d694cd)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.69.108 Chromium: 127.0.6533.43 (Official Build) nightly (64-bit)
-- | --
Revision | d5e7dd710a027aa197965d0603ec587791be032e
OS | Windows 10 Version 22H2 (Build 19045.4651)
```

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @goodov @brave/qa-team  @rebron

**Comment by goodov** [comment]
This is because of https://github.com/brave/brave-core/pull/24550

**Comment by kjozwiak** [comment]
The above requires `1.68.124` or higher for `1.68.x` verification 👍 @brave/qa-team this will get verified/checked while running through https://github.com/brave/brave-browser/issues/39689 using the template from https://github.com/brave/brave-core/pull/24604#issuecomment-2231943968. For example, the above is covered in the following tests via https://github.com/brave/brave-core/pull/24604#issuecomment-2231943968:

* `Desktop` --> `Test Case #4 - ensuring https://variations.brave.com/seed is being restored - PASSED`
* `Android` --> `Test Case #3 - ensuring https://variations.brave.com/seed is being restored - PASSED`

**Comment by stephendonner** [comment]
As @kjozwiak mentions in https://github.com/brave/brave-browser/issues/39767#issuecomment-2232562504, this was tested and verified in https://github.com/brave/brave-browser/issues/39689#issuecomment-2236806820

**Comment by btlechowski** [comment]
Verified with

Brave | 1.68.124 Chromium: 127.0.6533.57 (Official Build) (64-bit)
-- | --
Revision | d048917c488542dc56e67059011b2cf9d6043bb9
OS | Linux

Verified in https://github.com/brave/brave-browser/issues/39689#issuecomment-2237409322

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.68.124 Chromium: 127.0.6533.57 (Official Build) (64-bit)
-- | --
Revision | d048917c488542dc56e67059011b2cf9d6043bb9
OS | Windows 11 Version 23H2 (Build 22631.3880)
```

Verified via https://github.com/brave/brave-browser/issues/39689#issuecomment-2237572378
