### ISSUE TITLE
Make it possible to block Trackers only

### ISSUE THREAD

**Issue by oceanic84** [brave/brave-browser#3977]
Now on windows you only have option to either enable or disabled ads/tracking blocking.
A lot of people of us want to use ublock orgin for blocking adds because superior speed but still want to rely on brave anti-tracking, to avoid the need using apps like Ghostery.

In the Brave android app it is possible to disabled adblocking but enable anti-trackers.

**Comment by rebron** [comment]
Closing. We're doing uBlock origin feature parity in a separate group of issues.

**Comment by midnight-wonderer** [comment]
Hello there,
This is not exactly about uBlock origin; it's about choices.

I should be able to choose what to block.
Blocking tracker, but allow ads, should be possible right?

At least that is the whole point of having multiple Chromium-based browsers IMHO.
