### ISSUE TITLE
Restore upstream variations/shutdown tests

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#39773]
### Description

We recently disabled `MetricsService` [1] which led to incorrect shutdown handling and broken variations after 5th restart [2]. There are some upstream tests that could've prevented this. We need to re-enable/fix those.

1. https://github.com/brave/brave-core/pull/24550
2. https://github.com/brave/brave-browser/issues/39767

**Comment by atuchin-m** [comment]
A related perf issue: https://github.com/brave/brave-browser/issues/39864
