### ISSUE TITLE
Manually removing the offline media doesn't recover the file

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#39772]
### Description

Manually removing the offline media doesn't recover the file

### Steps to reproduce

1. Enable Playlist via flag and restart
2. Add a YT video to playlist, saves automatically for offline play
3. Manually delete the offline media_file 
4. Go back to browser and play, shows error message and gives option to `Recover` or `Dismiss`
5. Click on `Recover`, doesn't save the file again for offline play

### Actual result

https://github.com/user-attachments/assets/377b3ade-4816-45aa-9957-19dbe54bc1f0

### Expected result

Should recover file 

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.69.107 Chromium: 127.0.6533.43 (Official Build) nightly (64-bit)
-- | --
Revision | b488d8743681b4b13fbe03a8d57a25af75998de5
OS | Linux

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @rebron @sangwoo108 @brave/qa-team

**Comment by sangwoo108** [comment]
Nice catch. We don't seem to observe the actual file

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.94 Chromium: 128.0.6613.114 (Official Build) beta (64-bit)
-- | --
Revision | 7ee7ec28264896bd8a9aff39cdb9432da38be028
OS | Windows 11 Version 23H2 (Build 22631.4112)
```

1. Installed 1.70.94
2. launched Brave
3. enabled Playlist via brave://flags and restarted
4. added a YT video to playlist (do not play)
5. opened %LOCALAPPDATA%\BraveSoftware\Brave-Browser-Beta\User Data\Default\playlist
6. deleted the offline media_file
7. returned to browser and played
8. verified error message shown with option to Recover or Dismiss
9. clicked on Recover

#### Confirmed file saved again for offline play
#### Confirmed able to play video in the playlist


https://github.com/user-attachments/assets/255c0f15-ce4c-49f4-9a74-f687f44a4245
