### ISSUE TITLE
"Open Side Panel to see All Bookmarks" option displays Chrome icon

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#39782]
### Description

Found while testing https://github.com/brave/brave-browser/issues/36555

When the "All Bookmarks" option is displayed on the bookmarks toolbar, there is a menu option for "Open Side Panel to see All Bookmarks". In 1.68.x this has a Chrome icon. In 1.67.x this option doesn't have any icon at all.

We should either match 1.67.x (no icon) or use a Brave icon here.

### Steps to reproduce

1. Have bookmarks toolbar displayed (only on NTP option is fine)
2. Have bookmarks in "Other Bookmarks" folder
3. Click on "All Bookmarks" option on bookmarks toolbar

### Actual result

"Open Side Panel to see All Bookmarks" option has Chrome icon:

Light | Dark
--- | ---
<img width="337" alt="1 68 lt" src="https://github.com/user-attachments/assets/d14dee8f-e160-49be-aa7a-0c7b10a57ff8"> | <img width="318" alt="1 68 dk" src="https://github.com/user-attachments/assets/3adeb9ff-9c3f-44d0-99c6-48c4944406c3">

### Expected result

Either match 1.67.x (below) and don't show an icon or show a Brave icon instead.

Light | Dark
--- | ---
<img width="318" alt="1 67 lt" src="https://github.com/user-attachments/assets/2c4782a7-cc46-4309-997a-9028ff0518b8"> | <img width="317" alt="1 67 dk" src="https://github.com/user-attachments/assets/d3390e33-06ad-440a-9c76-89ef537dd126">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.68.122 Chromium: 127.0.6533.43 (Official Build) beta (x86_64)
-- | --
Revision | d9f43bf666718cb9878eab117e104f5d5d39bbbe
OS | macOS Version 13.6.7 (Build 22G720)
```

```
Brave | 1.69.101 Chromium: 127.0.6533.43 (Official Build) nightly (x86_64)
-- | --
Revision | 9073515479afc03ab66a21bb8175263fc56ba1f1
OS | macOS Version 13.6.7 (Build 22G720)
```

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @aguscruiz

**Comment by aguscruiz** [comment]
We could probably use our `product-bookmarks` icon

<img width="346" alt="image" src="https://github.com/user-attachments/assets/fd9ecc1d-9f1d-4065-8d41-8d14d799ab4d">

**Comment by simonhong** [comment]
working now.

**Comment by kjozwiak** [comment]
The above requires `1.68.124` or higher for `1.68.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.68.124 Chromium: 127.0.6533.57 (Official Build) (x86_64)
-- | --
Revision | d048917c488542dc56e67059011b2cf9d6043bb9
OS | macOS Version 13.6.7 (Build 22G720)
```
