### ISSUE TITLE
[iOS] - Use DarkReader for NightMode

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#39786]
### Platforms

iOS

### Description

- iOS should use DarkReader for night-mode as it works much better and is more customizable than the current NightMode script. It's also a Mozilla Approved Extension and Script.

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `iPhone 14` and `iPad Mini (6th gen)` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.7
- iPad Mni (6th gen) / iPadOS 18.0.1
Brave build: 1.70 (126)
BraveCore: 1.70.126 (129.0.6668.100)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Hamburger menu > Settings
3. Appearance > Enable `Night Mode` > *Verify*

**ACTUAL RESULTS:**
- Verified that the website is shown in `dark mode` when `Night Mode` is applied.
- Verified that some websites like www.amazon.com, www.x.com, www.chromeunboxed.com, and www.mail.google.com have exceptions and are shown in `light mode`.

---------------------------

|`Night Mode` is OFF|`Night Mode` is ON|`Night Mode` is OFF|`Night Mode` is ON|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/b090ffda-2eda-4e03-8308-f3fe29dac402) | ![2](https://github.com/user-attachments/assets/723d19eb-fdb2-4737-9f3a-f56f902f11d5) | ![3](https://github.com/user-attachments/assets/b090ffda-2eda-4e03-8308-f3fe29dac402) | ![4](https://github.com/user-attachments/assets/723d19eb-fdb2-4737-9f3a-f56f902f11d5) |
| ![1](https://github.com/user-attachments/assets/9ca19d19-d04f-4ef8-9673-a5e3d9138258) | ![2](https://github.com/user-attachments/assets/6ff57bd2-cf9f-42de-8c98-528e127b3a93) | ![3](https://github.com/user-attachments/assets/cebeff81-b94c-4718-b5c7-95daf664fd33) | ![4](https://github.com/user-attachments/assets/7fffb77e-ae4e-4d42-9222-ff76f71fbda0) |
| ![1](https://github.com/user-attachments/assets/9430bb1d-b276-4727-b740-ec01db7a0a8b) | ![2](https://github.com/user-attachments/assets/57779e6e-32bf-414e-ad85-f0517cea2918) | ![3](https://github.com/user-attachments/assets/7f06e681-edf5-42d8-9f8d-3c8556a6c936) | ![4](https://github.com/user-attachments/assets/81c1a4f7-f1a3-4650-8f76-c95e02a28586) |
| ![1](https://github.com/user-attachments/assets/42cbf332-4e05-4aa9-90ec-97371df95a07) | ![2](https://github.com/user-attachments/assets/3e8c7d88-1e8f-4027-9024-12df7b313074) | ![3](https://github.com/user-attachments/assets/19172f9b-0d1a-4ed9-b714-e2da73954e83) | ![4](https://github.com/user-attachments/assets/14498167-56a7-4572-8849-c1c2b251eb89) |
| ![1](https://github.com/user-attachments/assets/95d60e55-4f2e-4cd7-a8a0-b15bf882e7ec) | ![2](https://github.com/user-attachments/assets/16c0e047-820b-44d2-9638-c6c374bf5875) | ![3](https://github.com/user-attachments/assets/12b4aa5d-1500-48b5-807b-c68d4e7edd9f) | ![4](https://github.com/user-attachments/assets/c0f4c8b3-5036-4aa5-b826-f04bda522cbb) |
| ![1](https://github.com/user-attachments/assets/5a8caf06-770b-4daa-b7fc-f67eae1c4fc4) | ![2](https://github.com/user-attachments/assets/3f71c802-61fa-4412-bd22-947370d33b3e) | ![3](https://github.com/user-attachments/assets/e77866d3-d25e-4a74-93fb-36c15e77ee94) | ![4](https://github.com/user-attachments/assets/485e1dab-43b6-465f-8e2a-2684a482e5a5) |
| ![1](https://github.com/user-attachments/assets/82b4fa7e-eb62-4766-9392-26eea3101ae9) | ![2](https://github.com/user-attachments/assets/6259cb4e-deb9-423d-bfe6-37275a64d8e9) | ![3](https://github.com/user-attachments/assets/9eb76beb-3807-44a4-a394-f90248880b85) | ![4](https://github.com/user-attachments/assets/10755552-d3c7-4a96-849b-1de9b4ab9919) |
