### ISSUE TITLE
Bad ux when custom eth network is deleted

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#39813]
### Description

- Add custom network and select it in panel
- Remove network
- Should fallback to ETH mainnet instead of empty item
![image](https://github.com/user-attachments/assets/03096942-8019-40fc-9ead-ac91eac096be)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.105 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | dd1f0aff786e2f4b694066ba8500616833591bf1
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from issue description
- Verified removing a custom network when set as active resets network to Ethereum

https://github.com/user-attachments/assets/d30ad7a3-7074-4b6d-9f4b-d28948320bb0
