### ISSUE TITLE
[iOS] Leo - Change eraser icon to a "new chat" icon

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#39818]
### Description

With history coming, we'll need to change that perceived behavior. We're removing the eraser icon and replacing it with a new chat icon to indicate new chats.

**Affects:**
- Header icon
- Menu icon

Figma:
https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/%F0%9F%94%84-Leo-%5BIN-PROGRESS%5D?node-id=4580-3756&t=TgZmFYdaof0pLf7a-1

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7
Brave build: 1.70 (117)
BraveCore: 1.70.117 (129.0.6668.59)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Open `Leo` > *Verify `New Chat` icon*
3. Tap `Hamburger menu` > *Verify, that no `New Chat` name/icon is shown according to #39932*

**ACTUAL RESULTS:**
- Verified that the `Eraser` icon was updated to the `New Chat` icon in the header menu.
- Verified that tapping the `New Chat` icon clears the current conversation and starts a new chat.

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/501d5921-de0f-4c83-818b-44ef6f6941b7) | ![2](https://github.com/user-attachments/assets/213962bb-13e9-4120-b457-731b2b6f45f6) |
| ![1](https://github.com/user-attachments/assets/b6099631-d8be-402e-bcc8-db7cadce9d13) | ![2](https://github.com/user-attachments/assets/d14862e5-ebc2-4d7f-910f-a4fdc6059301) |
