### ISSUE TITLE
Leo - Change icons and font size

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#39819]
### Description

- With history coming, we'll need to change that perceived behavior. We're removing the eraser icon and replacing it with a new chat icon to indicate new chats. This change should be in header and dropdown menu
- Change "Leo AI" to 16px
- Change settings gear icon to more-vertical

https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/%F0%9F%94%84-Leo-%5BIN-PROGRESS%5D?node-id=4580-3749&t=TgZmFYdaof0pLf7a-1

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.70.30 Chromium: 127.0.6533.73 (Official Build) nightly (x86_64)
-- | --
Revision | 252bfcfa10e3f2a7e92ee1be5b9e488ab43b7218
OS | macOS Version 11.7.10 (Build 20G1427)
```

example | example
---------|---------
<img width="1520" alt="Screen Shot 2024-07-30 at 12 27 45 PM" src="https://github.com/user-attachments/assets/93155e12-4103-485f-9eab-6d04cf3316ca"> | <img width="1520" alt="Screen Shot 2024-07-30 at 12 27 53 PM" src="https://github.com/user-attachments/assets/9a0580c1-b814-44a9-b861-8cabb98ce9e3">
