### ISSUE TITLE
Leo - Add a button to launch Leo to full page from sidebar

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#39820]
### Description

Adding a top level icon to launch Leo to full page.

**Design**
https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/%F0%9F%94%84-Leo-%5BIN-PROGRESS%5D?node-id=4492-32855&t=TgZmFYdaof0pLf7a-1

**Comment by jagadeshjai** [comment]
@mattmcalister / @aguscruiz  Can I work on this? If yes, could you approve my request to view this design?

**Comment by petemill** [comment]
I've already done this one @jagadeshjai

**Comment by petemill** [comment]
Fixed in https://github.com/brave/brave-core/pull/25800

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/30554#issuecomment-2513707397
