### ISSUE TITLE
Improve VPN Country Server Details

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-browser#39824]
### Description

The number of server description under the city name does not represent the actual information related with it.

This should be changed with a text that can indicate the number of cities and number of servers which is working for the entire country.

The information can be fetched from Guardian SDK but it will require a version update.

This is reported by Guardian Team and asked if we can do a change around it. 

![31431231](https://github.com/user-attachments/assets/58f799a8-e595-4c65-96a0-3331b904c952)

**Comment by kjozwiak** [comment]
The above requires `1.69.137` or higher for `1.69.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6.1
Brave build: 1.69 (160)
BraveCore: 1.69.160 (128.0.6613.114)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Enable `VPN`
3. Hamburger menu > VPN Region
4. Disable `Automatic` toggle switch > *Verify*
5. Find a country with `2` or more available cities > Tap the `Info` button
6. Select any random city > *Verify*
7. Hamburger menu > Settings
8. Brave Firewall + VPN > *Verify*

**ACTUAL RESULTS:**
- Verified that proper `city` and `server` numbers are shown on the `Server Region` page
- Verified that choosing a specific city is working as expected
- Verified that the correct country/city name is shown on the VPN settings page

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/73f9212f-4a44-4b8f-b4bb-1a632dc21d27) | ![2](https://github.com/user-attachments/assets/006cdc7b-36c4-43e9-aea4-039395a09c6c) | ![3](https://github.com/user-attachments/assets/4ad6c0d8-0c60-40be-bfaa-18b6aa1b4e17) |
| ![1](https://github.com/user-attachments/assets/c3ee4116-d5bb-43a7-98e1-56abb09a3748) | ![2](https://github.com/user-attachments/assets/f27dd3c3-de3e-4c0a-9253-8cd1371dcf08) | ![3](https://github.com/user-attachments/assets/aa6d64d6-d725-4792-b392-a2e6436bbc06) |
| ![1](https://github.com/user-attachments/assets/44f69e1f-379a-4824-a178-d9996ddb806d) | ![2](https://github.com/user-attachments/assets/7a6fb368-ff13-4dac-9a98-c1b9c3713a2a) | ![3](https://github.com/user-attachments/assets/80ad2ee5-215a-43f0-8153-2f34f804d012) |
| ![1](https://github.com/user-attachments/assets/419b4d49-c680-4384-ad0b-f9943d90738e) | ![2](https://github.com/user-attachments/assets/6812f16a-f5db-45fa-8d95-6d9a9cc713c8) | ![3](https://github.com/user-attachments/assets/e7cef516-016f-48e9-904b-4dd6da779acf) |
