### ISSUE TITLE
Remove Prefilled Search Value for Bridge Selection

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#39828]
### Description

Currently we are pre-filling the search value for when selecting a token to `Bridge` to. It can be confusing to users and they may not realize that there are other tokens to `Bridge` to.

### Steps to reproduce

1. Open the `Wallet` and navigate to the `Bridge` screen
2. Select a token to bridge `from`
3. Then click to select a token to bridge `to`
4. The search value is prefilled to the `from` tokens symbol

### Actual result

https://github.com/user-attachments/assets/37bf1a74-a386-4ced-9be8-c3f349a0c0ac

### Expected result

We should not pre-fill the search value and leave it open.

https://github.com/user-attachments/assets/3df6a0a4-2a35-42b6-843f-c59d68509bae

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.107 Chromium: 127.0.6533.43 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.69.147` or higher for `1.69.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.147 Chromium: 128.0.6613.40 (Official Build) (64-bit)
-- | --
Revision | d29b1747d0f906239936b0d94c40889920ebf2c0
OS | Windows 11 Version 23H2 (Build 22631.4037)
