### ISSUE TITLE
[Follow up to #39061] Crash when dismissing upgrade card

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#39833]
### Description

Tapping `Maybe Later` on the `Unleash Leo's Full Powers with Premium` card causes crash. Rate limit card is fine. 

### Steps to reproduce

1. New install
2. Opt into Leo
3. Open menu and select premium model (Sonnet)
4. Observe chat UI for the upgrade card
5. Tap on the `Maybe Later` CTA

### Actual result

https://github.com/user-attachments/assets/30e38fcc-4c4b-4989-a4e9-0a16b3a2f3af

### Expected result

Should dismiss and not crash

### Reproduces how often

Easily reproduced

### Brave version

1.69.115

### Device/iOS version

iPhone / iOS 17.5.1

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.68.125` or higher for `1.68.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.69 (156)`

- Ensured that tapping `Maybe Later` on the upgrade card will dismiss it and does not crash after selection premium model from Leo menu.
- Ensured that `Upgrade` button takes user to the Leo premium purchase landing screen.

Example | Example
-|-
![IMG_7146](https://github.com/user-attachments/assets/97234d57-32a2-4bfa-b680-6a0cee36b25c) | ![IMG_7147](https://github.com/user-attachments/assets/9dc1a26e-ac34-45b5-9675-50b3fdc616f1)
