### ISSUE TITLE
[iOS] - Block the loading of non-http(s) URLs via Shortcuts

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#39836]
Please see https://github.com/brave/brave-core/pull/24640#issue-2406979197 & https://github.com/brave/reviews/issues/1686 for more context. @Uni-verse @hffvld please use https://github.com/brave/internal/issues/1160 for verification notes 👍

**Comment by kjozwiak** [comment]
The above requires `1.68.124` or higher for `1.68.x` verification 👍 @Uni-verse @hffvld please use https://github.com/brave/internal/issues/1160 for verification notes 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.6
- iPad Air / iPadOS 16.7.2
Brave build: 1.68 (124)
BraveCore: 1.68.124 (127.0.6533.57)
```
---------------------------

**ACTUAL RESULTS:**
- Verified that tapping on the created shortcut via the `Home` screen didn't do anything (Brave shouldn't be launched)
- Verified that tapping on the created shortcut via `Shortcuts` failed/displayed an error message

---------------------------

`iPhone 14 / iOS 17.6`

https://github.com/user-attachments/assets/56ec3923-7ad5-4694-8f69-0867ccea3e45

`iPad Air / iPadOS 16.7.2`

https://github.com/user-attachments/assets/d01fd089-3c64-44eb-a193-8b0d302db80b
