### ISSUE TITLE
[Leo] Support modifying user prompt on iOS

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#39831]
### Platforms

iOS

### Description

https://github.com/brave/brave-core/pull/24558 only makes it compile on iOS with new API changes, this issue is for tracking the iOS work to support it.
cc @StephenHeaps

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Mini (6th gen)` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.7
- iPad Mni (6th gen) / iPadOS 18
Brave build: 1.70 (119)
BraveCore: 1.70.119 (129.0.6668.70)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Open `Leo`
3. Type any query > Send request
4. Wait for Leo's response
5. Tap and hold your query > *Verify, that `Edit Promt` exist*
6.  Tap `Edit Prompt` > Edit your query > Tap ✅ > *Verify that the `Edited` button appeared, and the timestamp is updated*
 
**ACTUAL RESULTS:**
- Verified that the user can edit a query.
- Verified that `Leo` gives a new response to an updated query.
- Verified that the `Edited` label appeared on the right side.
- Verified that the string contains `Edited` with a new `timestamp` updated each time after the query was updated.

---------------------------

`iPhone 14 / iOS 17.7`

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/86f333fd-5961-4567-8205-5e9dc6b27053) | ![2](https://github.com/user-attachments/assets/a968f70f-4c76-40d7-a430-7aa4bff0dd79) | ![3](https://github.com/user-attachments/assets/fd72ab84-cf4a-4cc6-927f-a544fcd1d19e) | ![4](https://github.com/user-attachments/assets/8344d821-3d25-4333-8674-bc5dd109d421) | ![5](https://github.com/user-attachments/assets/1c549849-d70d-45c2-817b-d20bd7eb5492) |
| ![1](https://github.com/user-attachments/assets/2879dc6f-c373-46f2-b8c4-0a1aa14909e8) | ![2](https://github.com/user-attachments/assets/596bb484-478b-48d4-b76c-900fd4d7cef6) | ![3](https://github.com/user-attachments/assets/a9f5285b-ddc0-4c25-bff2-9f3aeec32826) | ![4](https://github.com/user-attachments/assets/dce7ea2e-5fb2-49d8-8897-893ed41f3b9e) | ![5](https://github.com/user-attachments/assets/af198172-886f-47dc-9513-855abcad58da) |

https://github.com/user-attachments/assets/b4b6f1e7-9bd9-47c4-ae7f-35eb074f5e5a

`iPad Mni (6th gen) / iPadOS 18`

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() | ![5]() |
