### ISSUE TITLE
Installer fails; Error 124

### ISSUE THREAD

**Issue by RichCat6** [brave/brave-browser#39837]
### Description

I'm trying to install brave browser on my computer, but the installer keeps throwing the error code 124. I've already tried whitelisting the installer, my antivirus (Windows Defender) doesn't seem to be flagging it, and my internet connection is fine. I even tried the standalone one, which threw the same error in my face.

Specs if needed:
- Intel Pentium Silver N5030
- Intel HD Graphics 605
- 1TB SSD
- 8GB DDR4 RAM
- Windows 11 23H2

### Steps to reproduce

1. Download installer
2. Wait until it throws the error in your face

### Actual result

The installer failing at its job and throwing the error in your face

### Expected result

To install the browser

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

The latest stable release as of July 17, 2024 (v1.65.122)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by stephendonner** [comment]
@RichCat6 I'm curious - you marked this as `completed` - what resolved the issue for you?
