### ISSUE TITLE
[Wallet] Price history chart is broken after balance registry changes

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39840]
### Description

The portfolio overview price chart are broken due to it not being able to find balances for tokens

### Steps to reproduce

Scenario 1
1. Open the wallet portfolio page (must have tokens with balances)
2. observe the price history chart

### Actual result

Chart has no value (flat line)

### Expected result

Chart should show valid price history

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.115 Chromium: 127.0.6533.43 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Regression from: [fix(wallet): include NFT token Ids in balance registry keys](https://github.com/brave/brave-core/pull/24680#top)

**Comment by kjozwiak** [comment]
The above requires `1.69.156` or higher for `1.69.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.156 Chromium: 128.0.6613.85 (Official Build) (64-bit)
-- | --
Revision | 1d701f8c67ab98b8c562ddd0fa2dafc1305f8605
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from issue description
- Verified price history shows for all time lines
- Verified price history graph is shown on both wallet portfolio, token details page and in panel

https://github.com/user-attachments/assets/5c3fd92c-abd4-4271-87b1-3487c3744b79
