### ISSUE TITLE
[Wallet] Price history chart does not load in asset details screen

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39857]
### Description

The price chart is not shown when viewing the asset details screen.

### Steps to reproduce

1. Open the wallet to the portfolio overview page
2. click an asset (ETH)
3. observe the details screen

### Actual result

Price chart is not shown

### Expected result

Price chart should be shown with valid price history

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.117 Chromium: 127.0.6533.57 (Official Build) beta (arm64) 

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Regression from: [Upgrade from Chromium 126 to Chromium 127](https://github.com/brave/brave-core/pull/23829#top)

Follow-up to https://github.com/brave/brave-core/commit/15315fdfa4e04504874d250f8f2048dc4d105f41

**Comment by kjozwiak** [comment]
The above requires `1.69.119` or higher for `1.69.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.121 Chromium: 127.0.6533.57 (Official Build) beta (64-bit)
-- | --
Revision | 6ab76d6b98b9a4c22c06c9bb3487062edbbfb3f2
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified ETH chart price is shown on both wallet and panel
- Verified opening Token details from portfolio and from account details page

https://github.com/user-attachments/assets/39e00c11-b868-4584-8299-b2f01c91568d
