### ISSUE TITLE
Update Dapps Explorer to match new designs

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#39850]
Old issue https://github.com/brave/brave-browser/issues/37872

Figma [Link](https://www.figma.com/design/muVcmcu4RFNu0LkXe9VRDl/Wallet-2.0?node-id=2093-511716&t=3tGAENbni01IXTXI-4)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.94 Chromium: 128.0.6613.114 (Official Build) beta (64-bit)
-- | --
Revision | 7ee7ec28264896bd8a9aff39cdb9432da38be028
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from [brave/brave-core#24857](https://github.com/brave/brave-core/pull/24857)
- Verified Dapps explorer matches new design

https://github.com/user-attachments/assets/7f104ec6-5a60-4ef5-b776-fbf2494b941a
