### ISSUE TITLE
Ads on youtube 

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#39854]
### Description

Sometimes ads appear on youtube

### Steps to reproduce

1. Install app from scratch
2. Wait for components to download
3. Go to youtube and watch some videos

### Actual result

Ads appear intermittently

### Expected result

No ads should appear on youtube

### Reproduces how often

Intermittent issue

### Brave version

1.68.x

### Device/iOS version

Any

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

Caused by resources not set

**Comment by kjozwiak** [comment]
Closing as the above was fixed via https://github.com/brave/brave-core/pull/24713 which was merged directly into `1.68.x`. The above requires `1.68.125` or higher for `1.68.x` verification 👍

**Comment by kjozwiak** [comment]
The above requires `1.68.127` or higher for `1.68.x` verification 👍 The above was fixed via https://github.com/brave/brave-core/pull/23694.

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6
Brave build: 1.68 (128)
BraveCore: 1.68.128 (127.0.6533.73)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/39855#issue-2416705699 and https://github.com/brave/brave-core/pull/23694#issuecomment-2243696063
2. *Verify*

**ACTUAL RESULTS:**
- Verified that no `ads` are seen when watching videos on YT.
- Verified that navigating to https://dev-pages.brave.software/filtering/scriptlets.html shows `True` in `This frame` column.

---------------------------

https://github.com/user-attachments/assets/09f0ea69-6b2b-4fcd-ae2a-49b19197a745

|1|
|:-:|
| ![1](https://github.com/user-attachments/assets/a32ef1e3-4da2-4635-8823-e4d4d9859bd4) |
