### ISSUE TITLE
Focus input box when opening Leo (iOS)

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#39858]
### Description

On iOS, when you invoke Leo you have to tap again on the input box to bring up the keyboard.
We should auto focus and bring up the keyboard when a user enter Leo.

Exception: Before the user is onboarded, we should not focus the input bar as per https://bravesoftware.slack.com/archives/C04KPE0BUDU/p1721325558569429?thread_ts=1721149898.469059&cid=C04KPE0BUDU

### Steps to reproduce

Invoke Leo from the menu

### Actual result

Input box is not focused

### Expected result

Input box is focused.

### Reproduces how often

Easily reproduced

### Brave version

All

### Device

- Brand/model: 
- Android version: 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [X] in the latest version of Chrome

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Mini (6th gen)` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.7
- iPad Mni (6th gen) / iPadOS 18
Brave build: 1.70 (117)
BraveCore: 1.70.117 (129.0.6668.59)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/25018#issue-2453731373
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the onscreen keyboard is not automatically opened during `Leo` onboarding.
- Verified that the onscreen keyboard is opened automatically when opening the `Leo` webview UI.

---------------------------

`iPhone 14 / iOS 17.7`

https://github.com/user-attachments/assets/abd40e53-dee6-407a-a821-ddabb88b5d57

`iPad Mni (6th gen) / iPadOS 18`

https://github.com/user-attachments/assets/ba92b344-ca9c-496a-9fe1-03bdae0972d6
