### ISSUE TITLE
Engine scripts not working on subframes

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#39860]
### Description

We should also be injecting scripts into subframes. However subframes are not nearly as important as the main frame.

### Steps to reproduce

1. Ensure content blockers are downloaded and available (wait a minute after install)
2. Go to https://dev-pages.brave.software/filtering/scriptlets.html

### Actual result

Only "This frame" is `true`

### Expected result

All columns should be `true`

### Reproduces how often

Easily reproduced

### Brave version

1.68

### Device/iOS version

Any

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

Seems to be caused by the FrameCheckWrapper.js wrapping that we are doing.

**Comment by cuba** [comment]
seems to be caused by the `use_strict` on top of the script

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.7
- iPad Air / iPadOS 16.7.2
Brave build: 1.70 (115)
BraveCore: 1.70.115 (129.0.6668.59)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/39860#issue-2416995516
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `true` is shown in each column on https://dev-pages.brave.software/filtering/scriptlets.html

---------------------------

`iPhone 14`

|1.68 (144)|1.70 (115)|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/c40e5870-b87f-4ac1-b431-c9fd91af1f10) | ![2](https://github.com/user-attachments/assets/1c73dccf-ffc4-48d9-a69a-640dc4daa107) |

`iPad Air`

|1.68 (144)|1.70 (115)|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/9c2ed575-0fca-4363-8ca9-d68b916c4d13) | ![2](https://github.com/user-attachments/assets/7c82b153-6cd8-42e1-8cba-1adffc585d1e) |
