### ISSUE TITLE
Make Rewards Event Logs use UTC and show timezone in timestamps

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#39873]
## Description 

Similar to https://github.com/brave/brave-browser/issues/38677, we should apply this to the `Event Logs` tab in brave://rewards-internals.

```[tasklist]
### Tasks
- [ ] Normalize to UTC
- [ ] Add timezone indicator in timestamp 
```

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.70.87 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 065466241068c7503125be3432f8593f19dd7f15
OS | Windows 10 Version 22H2 (Build 19045.4780)
```
- Verified the description from https://github.com/brave/brave-browser/issues/39873#issue-2418535690 and ensured that brave://rewards-internals logs use the UTC and shows the Time zone in the logs.
![image](https://github.com/user-attachments/assets/0041d0cc-7a66-44fd-9c2a-f4c28299cdca)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy A52s 5G version 12` running `Bravemonoarm64.apk_1.70.92`

- Verified the description from https://github.com/brave/brave-browser/issues/39873#issue-2418535690 and ensured that brave://rewards-internals EVENT logs use the UTC and shows the Time zone in the logs.
- Logged https://github.com/brave/brave-browser/issues/40733

Logs | Event logs
------|---------
![Screenshot_20240927_214005_Brave - Beta](https://github.com/user-attachments/assets/4b54c382-ec99-450c-8261-cc8551b93a30) | ![Screenshot_20240927_213945_Brave - Beta](https://github.com/user-attachments/assets/7419c6a8-54ff-4a16-9037-e53f56eda98e)
