### ISSUE TITLE
[Rewards 3.0] Add connected earnings card and Ads settings modals

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#39877]
### Description

For connected users, implement both the earnings card (which displays estimated earnings, along with an ad view summary) and the modal that can be accessed from that card (the Ads Settings modal and the Ads History modal).

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.70.66 Chromium: 128.0.6613.27 (Official Build) nightly (64-bit)
-- | --
Revision | 667a3d64bcaa33f50347e567971f37eeb76758aa
OS | Windows 10 Version 22H2 (Build 19045.4651)
```
