### ISSUE TITLE
Edit folder name doesn't show the `Save` button in the default sidebar panel size  

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#39874]
### Description

Edit folder name doesn't show the `Save` button in the default width 

### Steps to reproduce

1. Open Playlist
2. Create folder
3. Edit folder name from menu
4. Save button is not shown in default sidebar panel size 

### Actual result

<img width="238" alt="image" src="https://github.com/user-attachments/assets/3c0ee7e1-c1a4-431f-9df0-2d85e0e5f81c">

### Expected result

Should show the button in default size of sidebar panel

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.70.5 Chromium: 127.0.6533.57 (Official Build) nightly (64-bit)
-- | --
Revision | face8d58ab81422480c8c05b9ba5d518e1a2d227
OS | Windows 11 Version 23H2 (Build 22631.3880)

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @rebron @sangwoo108

**Comment by aguscruiz** [comment]
The input field should resize to accomodate that resizing.

Here's a mock at 280px wide (that's as thin as I can resize in my nightly)
https://www.figma.com/design/RxyQnpxi9qtf5HmnAj1yH0/Desktop-Playlist?node-id=3458-99950&t=7zK3PiseByRsTgmj-1


![image](https://github.com/user-attachments/assets/9c3478ab-6c1b-4441-96a5-497dd1858f43)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.70.30 Chromium: 127.0.6533.73 (Official Build) nightly (x86_64)
-- | --
Revision | 252bfcfa10e3f2a7e92ee1be5b9e488ab43b7218
OS | macOS Version 11.7.10 (Build 20G1427)
```


example | example | example | example | example | example
---------|----------|---------|----------|---------|----------
<img width="1321" alt="Screen Shot 2024-07-30 at 3 41 32 PM" src="https://github.com/user-attachments/assets/f80af1f3-c965-449e-babb-c859bba954b6"> | <img width="1321" alt="Screen Shot 2024-07-30 at 3 41 37 PM" src="https://github.com/user-attachments/assets/71b8d40a-d67c-4133-acd0-3d6d2f576684"> | <img width="1321" alt="Screen Shot 2024-07-30 at 3 41 43 PM" src="https://github.com/user-attachments/assets/e4d7cb98-a5de-44af-b4a7-9032de285aaa"> | <img width="1520" alt="Screen Shot 2024-07-30 at 3 42 57 PM" src="https://github.com/user-attachments/assets/6c14479d-6cfd-40c0-a336-2403ebd8c000"> | <img width="1520" alt="Screen Shot 2024-07-30 at 3 43 24 PM" src="https://github.com/user-attachments/assets/6ef6ed0a-6f4c-45fe-971d-1dba5ab81653">
