### ISSUE TITLE
Uninstall doesn't provide prompt to delete profile folder

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3987]
## Description 

Uninstall doesn't provide prompt to delete profile folder

## Steps to Reproduce

   1. Upgrade to `0.62.50`
   2. Go to apps settings and uninstall Brave
   3. No option to remove profile data is shown during uninstall process

## Actual result:

There is no prompt to remove profile folder. Just silently removes the install

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/55497405-4bef8f80-560f-11e9-8611-961dc2842174.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.62.50 Chromium: 73.0.3683.86 (Official Build) (64-bit) 
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Windows 10 OS Build 17763.379

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Reproduced by @kjozwiak and @rebron

**Comment by bsclifton** [comment]
Yikes - I am curious when this regressed. Too bad the regression script I wrote doesn't do Windows (yet!)

**Comment by kjozwiak** [comment]
@bsclifton looks like it regressed in `0.62.50 Chromium: 73.0.3683.86`. @srirambv checked 0.61.52 Chromium: 73.0.3683.86` on the release call and confirmed that it was only happening in `0.62.50 Chromium: 73.0.3683.86`. I went through a few previous versions, also confirmed that it's a new regression:

* `0.62.50 Chromium: 73.0.3683.86` - Reproduced
* `0.61.52 Chromium: 73.0.3683.86` - Couldn't reproduce
* `0.61.51 Chromium: 73.0.3683.75` - Couldn't reproduce
* `0.60.48 Chromium: 72.0.3626.121` - Couldn't reproduce

**Comment by srirambv** [comment]
@bsclifton yes it works on `0.61.52`. Used it as the screenshot for the expected result. Brave version specifies `73.0.61.52`

**Comment by kjozwiak** [comment]
@bsclifton @rebron regression range:

* `0.62.32 Chromium: 73.0.3683.75` - Reproduced
* `0.62.31 Chromium: 73.0.3683.75` - Couldn't reproduce

**Comment by kjozwiak** [comment]
@bsclifton as per requested via our weekly triage meeting on Friday, I tried the following with the latest nightly and can still reproduce the issue. Doesn't seem like `CR75` resolved the issue. Build used:

Brave | 0.68.57 Chromium: 75.0.3770.90 (Official Build) nightly (64-bit)
--- | ---
Revision | a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}
OS | Windows 10 OS Version 1809 (Build 17763.557)

**Comment by btlechowski** [comment]
No longer reproduces on Windows 7 x64 and x86

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

I also verified that the profile is purged.

![image](https://user-images.githubusercontent.com/34715963/66140951-434e3500-e603-11e9-91e2-ded2b724cb57.png)

@GeetaSarvadnya Can you reproduce on Windows 10?

**Comment by kjozwiak** [comment]
@btlechowski does the `Also delete your browsing data?` work when selected?

**Comment by btlechowski** [comment]
@kjozwiak As noted in https://github.com/brave/brave-browser/issues/3987#issuecomment-537997497 the profile was purged.

**Comment by bsclifton** [comment]
Confirmed on Windows 10 that our latest Release Channel build has this showing again 🎉
