### ISSUE TITLE
Update # of devices on VPN paywall 

### ISSUE THREAD

**Issue by larreewong** [brave/brave-browser#39888]
Please update the # of support devices on the VPN paywall to **10** 
Go live to coincide with the launch of the new brave.com/firewall-vpn page + iOS & Desktop

cc @mattmcalister @anthonypkeane @rmcfadden3 @macauleyberg

**Comment by rmcfadden3** [comment]
CC @AlanBreck just for visibility on the account.brave.com VPN card changes as well. (RE: https://github.com/brave/account-brave-com/issues/193)

**Comment by larreewong** [comment]
Closing this as the work will be done via https://github.com/brave/brave-browser/issues/39889
