### ISSUE TITLE
embedded YouTube videos no longer work

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#3988]
## Description 

This regressed in 0.63.x.

There is such a video at the bottom of this page:
https://www.dailywire.com/news/45415/tucker-carlson-unloads-ocasio-cortez-moron-nasty-ryan-saavedra

**Comment by bbondy** [comment]
See also https://twitter.com/BrendanEich/status/1113130612645228546

**Comment by rebron** [comment]
Related: https://github.com/brave/brave-browser/issues/4009 Includes location and text for YouTube switch.

**Comment by bbondy** [comment]
This seems to be not needed because it works on Release channel, so we just introduced a bug on Nightly and Dev.

**Comment by bbondy** [comment]
Fixed by reverting https://github.com/brave/brave-browser/issues/3988
here https://github.com/brave/brave-core/pull/2175
