### ISSUE TITLE
[Wallet] "Send" button on NFT details screen is not shown for owned EVM NFTs

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39882]
### Description

The "Send" button is not shown in the NFT details screen for EVM NFTs owned by a wallet account

### Steps to reproduce

1. import/restore a wallet which owns EVM NFTs
2. go to the NFTs tab of the portfolio
3. click on an EVM NFT which is owned by an account
4. observe the header of the details screen

### Actual result

The "Send" button is missing

### Expected result

The "Send" button is should be shown

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.117 Chromium: 127.0.6533.57 (Official Build) beta (arm64) 

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.69.123` or higher for `1.69.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.131 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 7f9c5cb9840ea18f57d485ee263b5bf4b1075953
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified `Send` button is shown for owned ERC721 tokens 
- Verified `Send` button is not shown for unowned ERC721 tokens 

https://github.com/user-attachments/assets/1e83399e-0432-4161-957f-50a64b75c849
