### ISSUE TITLE
Add Leo to Shortcuts Widget

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#39886]
## Description 

Add Leo AI as an option in both the Lock Screen shortcuts widget and Home Screen shortcuts widget

This should also add a new 4th slot in the home screen widget and Leo AI should be the 4th option by default

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Mini (6th gen)` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.7
- iPad Mni (6th gen) / iPadOS 18
Brave build: 1.70 (119)
BraveCore: 1.70.119 (129.0.6668.70)
```
Filed follow-up issue #41307, #41308, #41309
---------------------------
<details>
<summary> Fresh profile </summary>

**STEPS:**
1. Launch Brave 
2. Add `Brave Shortcuts` widget to the `home screen` > *Verify*
3. Tap `Leo AI` button > *Verify*
4. Tap and hold `Shortcuts` widget to modify it > Edit Widget > *Verify*
5. Tap any CTA button > *Verify*
6. Add `Brave Shortcuts` widget to the `lock screen` > *Verify*
7. Tap `Leo AI` button > *Verify*

**ACTUAL RESULTS:**
- Verified that the `Leo` is shown as the 4th option by default in the `Shortcuts` widget on `home screen`
- Verified that `Leo` UI is opened after tapping `Leo AI` button in the widget on `home screen`
- Verified that `Leo AI` title is shown when editing `Shortcuts` widget
- Verified that the `Leo` can be added as a widget on `lock screen`
- Verified that `Leo` UI is opened after tapping `Leo AI` button in the widget on `lock screen`

---------------------------

`iPhone 14 / iOS 17.7`

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/10f4b390-dcfa-4f3c-be7a-b15b5b71409a) | ![2](https://github.com/user-attachments/assets/148bdf71-acbe-43f7-81b9-70b5adae645e) | ![3](https://github.com/user-attachments/assets/0edb10aa-591b-444e-91b4-940184e515b4) |
| ![1](https://github.com/user-attachments/assets/27ed04dd-e314-4b8a-845f-5e25d40d7d3e) | ![2](https://github.com/user-attachments/assets/e3be977a-d3fd-416e-aa8a-0e76dc0b05de) | ![3](https://github.com/user-attachments/assets/6d5cf32d-cb01-47ff-9379-f8228375d94b) |

iPad Mni (6th gen) / iPadOS 18

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/01aa5597-c052-43eb-a93e-a7d3a7b5e564) | ![2](https://github.com/user-attachments/assets/c2a52a4e-12a3-43ff-9e00-0ce648cb78bb) | ![3]() | ![4]() |
| ![1]() | ![2]() | ![3]() | ![4]() |


</details>

 <details>
<summary> Upgrade profile - PASS </summary>

**STEPS:**
1. Launch Brave 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>
