### ISSUE TITLE
VPN new paywall design plus value props (Android)

### ISSUE THREAD

**Issue by larreewong** [brave/brave-browser#39889]
### Description

We want to update the VPN paywall with the new design (single page vs swiping) + value props (along with the 10 devices support)
<img width="1087" alt="Screenshot 2024-07-22 at 3 44 12 PM" src="https://github.com/user-attachments/assets/31863fc0-05ed-4e11-9782-abd7ca1f05c6">

See Figma file:  https://www.figma.com/design/DSDkzFJ4NdBKLKkf3tDdnE/%F0%9F%94%90-VPN?node-id=3054-395&t=K9ujRYnjxvoKwFRT-1

Per convo with @timchilds,

- we'll update all these in one update. Thus, I'm closing this https://github.com/brave/brave-browser/issues/39888
- @deeppandya : Let's not completely replace the whole paywall in case we need to roll back to the old paywall.

cc @timchilds @mattmcalister @macauleyberg @rmcfadden3 @anthonypkeane @AndyAnds265

### Steps to reproduce

n/a

### Actual result

n/a

### Expected result

n/a

### Reproduces how often

Easily reproduced

### Brave version

n/a

### Device

- Brand/model: 
- Android version: 

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by larreewong** [comment]
Figma link in the org ticket is updated cc @aguscruiz @timchilds @mattmcalister

**Comment by kjozwiak** [comment]
The above requires `1.70.94` or higher for `1.70.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 AP41.240726.010 release-keys
Brave build: 1.70.101
Chromium: 128.0.6613.120 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/39889#issue-2419884127 according to Figma design https://www.figma.com/design/DSDkzFJ4NdBKLKkf3tDdnE/%F0%9F%94%90-VPN?node-id=3054-395&node-type=frame&t=SKy9H1Cg5juZ8lpq-0
2. *Verify*

**ACTUAL RESULTS:**
- Verified that all the strings/text matches the design from https://www.figma.com/design/DSDkzFJ4NdBKLKkf3tDdnE/%F0%9F%94%90-VPN?node-id=3054-395&t=b9oBZ2qbFwxxSSjE-0
- Verified  that the `X` closes the VPN paywall without any issues/failures
- Verified that you can switch between `Yearly` & `Monthly` without any issues/failures
- Verified that the `Refresh your credentials` button opens https://account.brave.com using `intent=recover`
https://account.brave.com/?intent=recover&product=vpn&ux=mobile
- Verified that tapping on `Try 7 Days Free` starts the process re: starting trail/subscribing (ensured that the entire flow works)
- Verified that the `Restore` button is working once there's a subscription active and the paywall is displayed/viewed

---------------------------

<details>
<summary> Galaxy Tab S8 </summary>

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/7827995a-8ab5-423c-8cd9-b8a9a2c1f48e) | ![2](https://github.com/user-attachments/assets/ae7a6853-4f94-4675-8703-79650ffa5cfd) | ![3](https://github.com/user-attachments/assets/811d4585-7881-4fde-bbed-3e94a286729c) | ![4](https://github.com/user-attachments/assets/54cbf9ed-1654-4f44-8878-632868dc236c) |
| ![1](https://github.com/user-attachments/assets/cf261eca-d994-4e6a-a31a-c4714c314b4d) | ![2](https://github.com/user-attachments/assets/c8d526b8-2d5f-4c08-aa37-8274138133e7) | ![3](https://github.com/user-attachments/assets/97143df5-8440-4d19-969b-3bb644846e1f) | ![4](https://github.com/user-attachments/assets/f4a4cc0e-844e-4d3f-b45c-caa327cda96b) |
</details>

<details>
<summary> Pixel 7 </summary>

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>
