### ISSUE TITLE
Shred Feature Copy Changes

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#39880]
### Platforms

iOS

### Description

There are a few minor copy changes we want to add to the shred feature which can be found in figma:
https://www.figma.com/design/rsiGfV4XiqTGz0UdODaTAc/Shred-browser-data?node-id=1232-63262&t=5fzMss9morwoL1l7-0

**Comment by kjozwiak** [comment]
The above requires `1.69.137` or higher for `1.69.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on` iPhone 12` running `iOS 17.5.1` using version `1.69 (144)`

- Ensured copies for Shred Data feature are updated in the following sections: 
   - [x] `Shred Site Data` is displayed for the Shred Data feature in Shields panel.
      - [x] Opening `Shred Site Data` in Shields will display `Auto Shred` menu and `Shred Site Data Now` with Shred icon.
         - [x] Auto Shred dropdown menu contains `Never`, Site `Tabs Closed` and `App Close` strings.
         - [x] Ensured strings are updated in dialog shown when tapping on `Shred Site Data Now`.
   - [x] `Auto Shred` is displayed for the Shred Data feature in `Brave Shields & Privacy`.
      - [x] Auto Shred dropdown menu in settings contains `Never`, Site `Tabs Closed` and `App Close` strings.
   - [x] Ensured dialog header and strings are updated in `Shred Site Data?` dialog when hitting Shred icon in tab view.

Example | Example | Example | Example
-|-|-|-
![IMG_6959](https://github.com/user-attachments/assets/8c0dd22d-d9a5-4d92-8f1f-650aeb7dca83) | ![IMG_6960](https://github.com/user-attachments/assets/e1f0dd51-a5fb-4b8a-881e-7501a5e8ca21) | ![IMG_6963](https://github.com/user-attachments/assets/fd9c5505-8eb0-4d45-8b80-0da8ba4c4568) | ![IMG_6965](https://github.com/user-attachments/assets/edac5054-d58c-4e49-a44a-5b749b8cc502)
