### ISSUE TITLE
VPN new Paywall Design and Value Props 

### ISSUE THREAD

**Issue by larreewong** [brave/brave-browser#39893]
### Description

We want to update the VPN paywall with the new design (single page vs swiping) + value props (along with the 10 devices support)
<img width="1061" alt="Screenshot 2024-07-22 at 3 29 11 PM" src="https://github.com/user-attachments/assets/751945d0-da39-49ab-a21e-d6886ce6ecdc">

See final Figma design: https://www.figma.com/design/DSDkzFJ4NdBKLKkf3tDdnE/%F0%9F%94%90-VPN?node-id=3054-395&t=K9ujRYnjxvoKwFRT-1

Per convo with @timchilds, 

- we'll update all these in one update. Thus, I'm closing this [ticket](https://github.com/brave/brave-browser/issues/39892) 
- @soner-yuksel: Let's not completely replace the whole paywall in case we need to roll back to the old paywall. 

cc @timchilds @mattmcalister @macauleyberg @rmcfadden3 @anthonypkeane @AndyAnds265 

### Steps to reproduce

n/a

### Actual result

n/a

### Expected result

n/a

### Reproduces how often

Easily reproduced

### Brave version

n/a

### Device/iOS version

n/a

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by larreewong** [comment]
Figma link in the org ticket is updated cc @aguscruiz @timchilds @mattmcalister

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Mini (6th gen)` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.7.2
- iPad Mini (6th gen) / iPadOS 18.1.1
Brave build: 1.75 (97)
BraveCore: 1.75.97 (132.0.6834.46)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Open `VPN Paywall` > *Verify*

**ACTUAL RESULTS:**
- Verified that the `10 devices` support string is added.
- Verified new `VPN Paywall` design.

---------------------------

`iPhone 14`

<details>
<summary> Vertical view </summary>

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/568cee87-546b-4305-98af-fa5e30512619) | ![2](https://github.com/user-attachments/assets/8f5b1bb9-d771-4ce3-aa75-bdacab6dde80) |
</details>

<details>
<summary> Horisontal view </summary>

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/23a9a5b9-45d4-4a51-a38e-3ff8b8add5c5) | ![2](https://github.com/user-attachments/assets/22585f33-affe-4e7f-be2d-c2958868aec0) |
| ![1](https://github.com/user-attachments/assets/add25ac6-ba00-4397-9a99-c4650389614b) | ![2](https://github.com/user-attachments/assets/d1c996e3-9919-4e43-aa19-7838bfcd675d) |
</details>

`iPad Mini (6th gen)`

<details>
<summary> Vertical view </summary>

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/5feb8c1d-1f80-4ef0-ae6f-c570091851d2) | ![2](https://github.com/user-attachments/assets/7b6b47f7-1cf9-4a9f-b659-10d6d7bbf8e2) |
</details>

<details>
<summary> Horisontal view </summary>

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/7235691f-8281-414c-9ca3-bc82ec8f2ddc) | ![2](https://github.com/user-attachments/assets/19aba44c-ac1e-4ec8-9436-dc7994dac59e) |
</details>
