### ISSUE TITLE
Update # of devices on VPN paywall

### ISSUE THREAD

**Issue by larreewong** [brave/brave-browser#39892]
### Description

Please update the # of support devices on the VPN paywall to **10**
Go live to coincide with the launch of the new brave.com/firewall-vpn page + iOS & Desktop

cc @mattmcalister @anthonypkeane @rmcfadden3 @macauleyberg 
CC @AlanBreck just for visibility on the account.brave.com VPN card changes as well. (RE: https://github.com/brave/account-brave-com/issues/193)

### Steps to reproduce

n/a

### Actual result

n/a

### Expected result

n/a

### Reproduces how often

Easily reproduced

### Brave version

n/a

### Device/iOS version

n/a

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by AlanBreck** [comment]
Is this a duplicate of https://github.com/brave/brave-browser/issues/39888?

**Comment by larreewong** [comment]
Closing this ticket as the work will be part of this [ticket](https://github.com/brave/brave-browser/issues/39893
).
