### ISSUE TITLE
Remove option for safe browsing in shields

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#399]
## Description 
Remove option for safe browsing in shields

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7
