### ISSUE TITLE
action operators: `:remove()`, `:remove-attr()` and `:remove-class()` are affected by `$generichide`

### ISSUE THREAD

**Issue by TEMP-ad** [brave/brave-browser#39907]
### Description

@antonok-edm 

I was testing and comparing with uBlock, and it seems that the newest rules don't work correctly in some sites like Youtube and Twitch.

So if you use filters like this, it will only work in Brave.

```
youtube.com,brave.com,twitch.tv##body:remove()
```

Or for example, removing the 'dark' attribute from Youtube to get the light theme also doesn't work

```
youtube.com##html:remove-attr(dark)
```

I found out it works when disabling the Default lists would work, and by thinking what could it be, it was easy to find out that the [$generichide](https://github.com/easylist/easylist/blob/b85c500c52093cc53beb9852c2d1d225f6fe9c98/easylist/easylist_allowlist.txt#L374) is the reason for this wrong behavior and not allowing the action operators to work at all in certain domains.

So no action operator remove, remove-class and remove-attr can be used under those domains that have the generichide, or in a better way, bad filter the rules which can be done as a workaround, of course not a conventional workaround since custom adblock rules will not badfilter default rules but adding the badfilters to affect default lists will work. Of course, it can cause 'detection' issues with Youtube, not so much with Twitch. But in the end the behavior has to be corrected and let's hope it is not a complicated fix.

Have a nice day.

### Steps to reproduce

1. add youtube.com,brave.com,twitch.tv##body:remove()
2. go to brave - it works
3. go to Youtube or Twitch, it doesn't work
4. Edit default lists and disable default lists or remove line  `@@||twitch.tv^$generichide` or `@@||www.youtube.com^$generichide` or badfilter them `@@||twitch.tv^$generichide,badfilter` / `@@||www.youtube.com^$generichide,badfilter`
5.  body gets removed correctly by the `:remove()` action operator.

### Actual result

Action operators fail to work when a domain has a generichide rule.

### Expected result

Action operators should work in websites with generichide.

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

1.70.7 Chromium: 127.0.6533.57 (Official Build) nightly (64-bit) 

### Android device

- Brand/model: Samsung
- Android version: 14

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by TEMP-ad** [comment]
For now the only workaround on desktop will be to load a list with the $badfilter as default lists through catalog to turn off the $generichide rules without any issues even if lists update, just so I will be able to use :remove-class or :remove-attr and not scriptlet injections in sites where Easylist added the $generichide.

**Comment by antonok-edm** [comment]
@TEMP-ad thanks for reporting! I believe we disable the in-page `MutationObserver` if there is a `$generichide` filter, yet we also rely on that observer for `:remove`, `:remove-class`, and `:remove-attr` filters. I suspect the fix shouldn't be too difficult.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.70.37 Chromium: 127.0.6533.73 (Official Build) nightly (x86_64)
-- | --
Revision | 8556062edfbbe9023221ddaca3b6fe81264238c8
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.70.37`
2. launched Brave
3. opened `brave://adblock`
4. input `youtube.com,brave.com,twitch.tv##body:remove()` to the custom filters in `brave://settings/shields/filters` and clicked `Save`
5. opened a new-tab page
6. loaded `brave.com`
7. loaded `youtube.com`
8. loaded `twitch.tv`

### Confirmed the page content was removed, in each case

`brave://adblock` | `brave.com` | `youtube.com` | `twitch.tv`
------------------|-----------------|--------------|-----------
<img width="1207" alt="Screen Shot 2024-07-31 at 10 24 24 AM" src="https://github.com/user-attachments/assets/8746148c-746a-42b8-9bd3-fad512a6d29b"> | <img width="1207" alt="Screen Shot 2024-07-31 at 10 24 37 AM" src="https://github.com/user-attachments/assets/a4607e1c-4565-4dc2-9876-d34f2ddd8190"> | <img width="1207" alt="Screen Shot 2024-07-31 at 10 24 52 AM" src="https://github.com/user-attachments/assets/c054ca44-97b7-4f35-81fc-30514ab45d63"> | <img width="1207" alt="Screen Shot 2024-07-31 at 10 25 07 AM" src="https://github.com/user-attachments/assets/d39c6c53-8b72-4f0f-8db6-3e50f42ddea5">

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.70.100 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | c30694e8a60583be9d1784e4d42b4a0b94c70ab5
OS | Windows 10 Version 22H2 (Build 19045.4780)
```

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 AP41.240726.010 release-keys
Brave build: 1.70.101
Chromium: 128.0.6613.120 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/24809#issue-2425787237
2. *Verify*

**ACTUAL RESULTS:**
- Verified that https://brave.com/, https://youtube.com/ and https://twitch.com/ are blank when custom filter list is modified to `youtube.com,brave.com,twitch.tv##body:remove()`.

---------------------------

*Galaxy Tab S8*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/2e320f0f-d6de-443a-a95a-6080ee90451b) | ![2](https://github.com/user-attachments/assets/89fc815f-c40b-4a3b-9295-a9745130f07d) | ![3](https://github.com/user-attachments/assets/69cfe5b6-4f3f-4a9d-b982-3fc11a0c9325) | ![4](https://github.com/user-attachments/assets/5bbe4818-5f68-41cf-a3ea-085595560d71) |
| ![1](https://github.com/user-attachments/assets/ea807b89-e489-468b-9dbc-257eced2993a) | ![2](https://github.com/user-attachments/assets/4df230fb-29f5-4994-b588-d22082283e18) | ![3](https://github.com/user-attachments/assets/66b200b2-fcee-4c20-8fdf-7275935e482a) | ![4](https://github.com/user-attachments/assets/2a18e578-b9f2-44d2-871c-c678aeb9fe28) |

*Pixel 7*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/92ecad92-fc73-48f3-abd0-05d41d4b822e) | ![2](https://github.com/user-attachments/assets/67f941f6-2350-43c2-ae65-9eee9b7194d1) | ![3](https://github.com/user-attachments/assets/b46b02f9-474e-4334-9584-692a26255619) | ![4](https://github.com/user-attachments/assets/2f4d30eb-efdd-4c80-b549-cbe9cc699227) |
| ![1](https://github.com/user-attachments/assets/1f6aff44-21e6-4c3b-97cc-0e320cbd618c) | ![2](https://github.com/user-attachments/assets/6f2988c5-351c-4c08-a012-e80bb77e8fca) | ![3](https://github.com/user-attachments/assets/6f42d912-73f4-40c0-87ff-50b0815e2fc9) | ![4](https://github.com/user-attachments/assets/7c4487bb-e04e-4bf5-919a-1471e4338559) |

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave	1.70.110 Chromium: 128.0.6613.138 (Official Build) beta (64-bit) 
Revision	7dec99ca278e09ce2087e9f04914f0aa2507ea4c
OS	Linux
```
- Verified the test plan from https://github.com/brave/brave-core/pull/24809

### Steps:
1. installed `1.70.110`
2. launched Brave
3. opened `brave://adblock`
4. input `youtube.com,brave.com,twitch.tv##body:remove()` to the custom filters in `brave://settings/shields/filters` and clicked `Save`
5. opened a new-tab page
6. loaded `brave.com`
7. loaded `youtube.com`
8. loaded `twitch.tv`

### Confirmed the page content was removed, in each case

`brave://adblock` | `brave.com` | `youtube.com` | `twitch.tv`
------------------|-----------------|--------------|-----------
![image](https://github.com/user-attachments/assets/d872632e-1ffe-4970-9463-393f56905fb0) | ![image](https://github.com/user-attachments/assets/528ffc3e-12a7-4f61-8199-0f1842717bc4) | ![image](https://github.com/user-attachments/assets/03d157f3-b1e6-45e7-9fa8-de314cf2de2d) | ![image](https://github.com/user-attachments/assets/415062cd-c915-4beb-b997-8755e785b78d)
