### ISSUE TITLE
LiFi swaps are broken due to removal of insurance feature

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#39906]
### Description

LiFi has recently removed their insurance feature, which broke our swaps feature. We were expecting an API response where insurable routes are indicated, and since this field no longer exists, we’re unable to parse the response in core.

### Steps to reproduce

Try to fetch a swap quote on an EVM chain (such as Optimism), using LiFi as the provider.

### Actual result

The CTA button is disabled and shows "Unknown error".

### Expected result

Valid swap quote is fetched and displayed. User is able to create a transaction and sign it successfully.

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

1.69.x - desktop and android

### Android device

N/A

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [X] in the latest version of Chrome

**Comment by LaurenWags** [comment]
Requires `1.69.124` or higher for testing 👍🏻

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.145 Chromium: 128.0.6613.27 (Official Build) beta (64-bit)
-- | --
Revision | b029337c8485766fbc2dd25b11a46c88c8aaf2b4
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified EVM Swap quotes show up as expected

https://github.com/user-attachments/assets/94e96dca-514a-44d3-ba67-d3864df7d78a
