### ISSUE TITLE
[Wallet] Clicking "Send" on NFT details screen does not pre-fill send amount

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39916]
### Description

Clicking "Send" on NFT details screen does not pre-fill send amount, preventing the NFT from being send after the recipient is selected.

### Steps to reproduce

1. Restore wallet with ERC721 tokens
2. Click "Send" button on NFT details page
3. Select a recipient in the send form

### Actual result

"Review Send" button is disabled

### Expected result

"Review Send" button should be enabled

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.67.123 Chromium: 126.0.6478.126 (Official Build) (arm64) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.68.127` or higher for `1.68.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.68.127 Chromium: 127.0.6533.57 (Official Build) (64-bit)
-- | --
Revision | 88b0d9010af274686b27d8be77edd728fcba04a5
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified Review Send button is enabled and able to see the details in panel 

https://github.com/user-attachments/assets/b2ee07d8-23b8-471e-8224-76ab960e926f

**Comment by Safay99** [comment]
****
