### ISSUE TITLE
No send button on ERC721 tokens. Console throws error when loading the NFT details page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#39912]
### Description

No send button on ERC721 tokens. Console throws error when loading the NFT details page

### Steps to reproduce

1. Restore wallet with ERC721 tokens
2. No Send button loads up on NFT details page
3. Console throws error
4. Go back to NFT list and open an SVM token
5. Shows Send button

### Actual result

https://github.com/user-attachments/assets/88d75dbf-aa3b-4b01-a9c3-d404eac3788f

### Expected result

Should show Send button for ERC721 tokens on details page. And no console error

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.69.121 Chromium: 127.0.6533.57 (Official Build) beta (64-bit)
-- | --
Revision | 6ab76d6b98b9a4c22c06c9bb3487062edbbfb3f2
OS | Windows 11 Version 23H2 (Build 22631.3880)

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @Douglashdaniel @muliswilliam @josheleonard

**Comment by kjozwiak** [comment]
The above requires `1.69.123` or higher for `1.69.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.131 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 7f9c5cb9840ea18f57d485ee263b5bf4b1075953
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified `Send` button is shown for owned ERC721 tokens 
- Verified `Send` button is not shown for unowned ERC721 tokens 

https://github.com/user-attachments/assets/b233df1d-aae6-4bf7-96b6-14020dfbbd92
