### ISSUE TITLE
[Nala]: Update to latest

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#39910]
Pull in new icons and fix for input

**Comment by kjozwiak** [comment]
The above requires `1.69.123` or higher for `1.69.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.69.122 Chromium: 127.0.6533.57 (Official Build) beta (64-bit)
-- | --
Revision | bd77e9b76a8e67ff2bf9f62f1df7d60378ca811f
OS | Windows 11 Version 23H2 (Build 22631.3880)
```

1. Installed 1.69.122
2. launched Brave
3. completed onboarding

<details>
<summary>NTP still loads (a smoke test)</summary>

- confirmed loading NTP worked without any issues
- confirmed that sponsored images are loading via NTP without any issues
- confirmed that clicking on/switching between the cards worked without issues
- confirmed clicking on the ad via NTP also works without issues
- confirmed favorites are being added into the NTP without issues

example | example | example | example | example 
----- | ----- | ----- | ------ | -------
![image](https://github.com/user-attachments/assets/b84514a9-662d-41de-a913-1f850e30293f)|![image](https://github.com/user-attachments/assets/8d2f2320-9dad-42fe-ae44-2918c6c0f634)|![image](https://github.com/user-attachments/assets/082941cc-1e23-46c8-8a63-db3a453d3c43)|![image](https://github.com/user-attachments/assets/bac2b6d2-7ba0-4416-9280-2a1a493a93bb)|![image](https://github.com/user-attachments/assets/569dae4b-7db7-4709-ab00-c8b52a6397a5)

</details>

<details>
<summary>chrome://settings icons load (smoke test)</summary>

- Confirmed that all the icons under brave://settings are being displayed without any issues as per the following:

example | example | example | example | example | example | example 
----- | ----- | ----- | ------ | ------- | ------- | -------
![image](https://github.com/user-attachments/assets/2c994b2d-aab8-4423-814f-66bb8d5a0d29)|![image](https://github.com/user-attachments/assets/eb63e486-b3a8-4222-a107-1574d6633e3c)|![image](https://github.com/user-attachments/assets/e6d77a0d-cb0c-49dd-871f-3c0e306d8c77)|![image](https://github.com/user-attachments/assets/3ed6195b-d0b6-4e0a-8fc3-557c353902cb)|![image](https://github.com/user-attachments/assets/f424913c-d23e-436d-817f-7170c3c4aa72)|![image](https://github.com/user-attachments/assets/a254f265-e842-4ae2-96ce-d6a0427ff8ca)|![image](https://github.com/user-attachments/assets/8bc25530-9a0d-4f37-9254-17ca816a94c4)
</details>

<details>
<summary>Can type in NTP search box</summary>

- Confirmed able to type into the Brave Widget via the NTP as per the following:

example | example | example 
------- | ------ | -------
![image](https://github.com/user-attachments/assets/aef61753-16ad-4ed9-b33b-7371fcce313e)|![image](https://github.com/user-attachments/assets/26d422ff-439a-4e54-9a8b-5c91e9c0750b)|![image](https://github.com/user-attachments/assets/c931c545-5c75-49be-84a5-7f0694627087)

</details>

<details>
<summary>Toggles on chrome://settings still work</summary>

- Confirmed various toggles in brave://settings worked as expected

</details>

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.69.128 Chromium: 127.0.6533.73 (Official Build) beta (64-bit) 
Revision	715445841b1da480bcc24c12077a6dc926951996
OS	Linux
```

1. Installed 1.69.128
2. launched Brave
3. completed onboarding

<details>
<summary>NTP still loads (a smoke test) - PASSED</summary>

- confirmed loading NTP worked without any issues
- confirmed that sponsored images are loading via NTP without any issues
- confirmed that clicking on/switching between the cards worked without issues
- confirmed clicking on the ad via NTP also works without issues
- confirmed favorites are being added into the NTP without issues

example | example | example | example | example 
----- | ----- | ----- | ------ | -------
![image](https://github.com/user-attachments/assets/d95a7584-8b33-4453-92bc-97975d79931a)|![image](https://github.com/user-attachments/assets/ad3b48c9-0b28-40aa-9227-fff209041674)|![image](https://github.com/user-attachments/assets/c3168c6f-50c6-4ac0-b05e-2b9c2bf23fdb)|![image](https://github.com/user-attachments/assets/a6637872-82f2-4de7-b6a6-285b6abaf8a2)|![image](https://github.com/user-attachments/assets/ce70a153-d719-4e16-8d91-97bf91526659)


</details>

<details>
<summary>brave://settings icons load (smoke test) - PASSED</summary>

- Confirmed that all the icons under brave://settings are being displayed without any issues as per the following:

example | example | example | example | example | example | example 
----- | ----- | ----- | ------ | ------- | ------- | -------
![image](https://github.com/user-attachments/assets/54c50394-9377-441f-9acc-5cd6549e5443)|![image](https://github.com/user-attachments/assets/4c12cf31-5c6d-4eae-ba45-c649561e0074)|![image](https://github.com/user-attachments/assets/bfd8d07c-1176-4a4a-870d-b20e6e8038e1)|![image](https://github.com/user-attachments/assets/93a40d3d-2a2c-4dcb-b7be-4ada9df2088e)|![image](https://github.com/user-attachments/assets/2d3a59d4-c4d8-4033-985c-75c5404a65ee)|![image](https://github.com/user-attachments/assets/0ee058c7-5358-4754-880a-caa6d4e123ff)

</details>

<details>
<summary>Can type in NTP search box - PASSED</summary>

- Confirmed able to type into the Brave Widget via the NTP as per the following:

example | example | example 
------- | ------ | -------
![image](https://github.com/user-attachments/assets/448b3f89-2ad4-4648-ac78-03462dfae01e)|![image](https://github.com/user-attachments/assets/a5bbaec5-f4d0-4ca0-827e-83ee933ed9ae)|![image](https://github.com/user-attachments/assets/03d0665a-fc23-4214-9164-77fcac557aae)


</details>

<details>
<summary>Toggles on brave://settings still work - PASSED</summary>

- Confirmed various toggles in brave://settings worked as expected

</details>

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.69.128 Chromium: 127.0.6533.73 (Official Build) beta (x86_64)
-- | --
Revision | 715445841b1da480bcc24c12077a6dc926951996
OS | macOS Version 11.7.10 (Build 20G1427)
```

## NTP still loads
## brave://settings icons load
## can type in NTP search box
## toggles on brave://settings still work
