### ISSUE TITLE
Webcompat Exception Manager should allow turning off all fingerprinting protections on a site

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#39924]
### Platforms

Linux, macOS, Windows

### Description

Currently, for debugging purposes, you would have to manually specify all keys in https://sourcegraph.com/github.com/brave/brave-core/-/blob/components/webcompat/webcompat_exceptions_service.cc?L47 to turn off all fingerprinting via the remote list. There should be a single way of doing this i.e. `all` or something.

**Comment by stephendonner** [comment]
@arthuredelstein @ShivanKaul can one of you please provide a testplan here for @brave/qa-team ?  Thanks!

**Comment by stephendonner** [comment]
Setting to `QA/Blocked` for now, until we get the above, ty.

**Comment by arthuredelstein** [comment]
**QA testing suggestions:**

This PR is intended to allow the webcompat exceptions remote list to control the fingerprinting pref.

First, open Brave Nightly and browse to a target site of your choice, such as example.com. Confirm that the "Block fingerprinting" toggle is enabled (the default setting) for the site.

<img width="423" alt="image" src="https://github.com/user-attachments/assets/b935754a-6f2a-4d89-99e6-71dd8b07657e">

Next, edit the file locally to disable fingerprinting on the target site.

On my mac, the file is located at:
`cd ~/Library/Application\ Support/BraveSoftware/Brave-Browser-Nightly/afalakplffnnnlkncjhbmahjfjhmlkal/1.0.836/1/webcompat-exceptions.json`
(Note that the version number changes periodically.)

Open the JSON file in a code editor, and add a rule for the target site with an exceptions key that is `all-fingerprinting`. For example, you could add an item like:

```json
  {
    "include": [
      "*://example.com/*"
    ],
    "exceptions": [
      "all-fingerprinting"
    ],
    "issue": "just testing"
  },
```

Finally, re-launch Brave Nightly, and the website with this exception should show that the "Block fingerprinting" option is now disabled:

<img width="438" alt="image" src="https://github.com/user-attachments/assets/8820f9df-a4d8-4c0b-a88c-87720aaf959d">

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.70.52 Chromium: 127.0.6533.88 (Official Build) nightly (64-bit)
-- | --
Revision | 23ef663f6577840e420ce042b5288d2faaf6da22
OS | Windows 10 Version 22H2 (Build 19045.4717)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.70.95 Chromium: 128.0.6613.114 (Official Build) beta (x86_64)
-- | --
Revision | 58a39a29fce4db0417a269766b0157fad397767b
OS | macOS Version 13.6.9 (Build 22G830)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.70.100 Chromium: 128.0.6613.120 (Official Build) beta (64-bit) 
Revision	c30694e8a60583be9d1784e4d42b4a0b94c70ab5
OS	Linux
```

1. Installed 1.70.52
2. launched Brave
3. enabled brave://flags/#brave-webcompat-exceptions-service
4. clicked Relaunch
5. loaded example.com
6. clicked on the Shields logo in the URL bar
7. clicked on Advanced Controls
8. confirmed Block fingerprinting is default-enabled
9. opened webcompat-exceptions.json from C:\Users\steph\AppData\Local\BraveSoftware\Brave-Browser-Nightly\User Data\afalakplffnnnlkncjhbmahjfjhmlkal\1.0.847\1 in Atom (as Admin)
10. edited to include the all-fingerprinting JSON blurb
11. closed Atom
12. relaunch Brave
13. loaded example.com
15. clicked again on Shields
16. confirmed Block fingerprinting is now disabled

**Comment by kjozwiak** [comment]
Adding `QA Pass - Android ARM` & `QA Pass - Android Tab` so the above issue is removed from our QA list of required verifications for `1.70.x`. However, the above can't be verified on `Android` due to not having access to the file system as described via the STR/Cases via https://github.com/brave/brave-browser/issues/39924#issuecomment-2261521471.
