### ISSUE TITLE
[Wallet] Prevent edits to pre-filled NFT info

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39929]
### Description

When adding or editing an NFT, any info found on-chain should not be editable

## Scenario 1
1. Go to brave://wallet/crypto/portfolio/nfts
2. click the "+" icon
3. select a network
4. enter a valid contract address and token id
5. wait for metadata fetching to finish

## Scenario 2
1. brave://wallet/crypto/portfolio/add-asset
2. click "Available assets" tab
3. click "Add custom asset"
4. Click "NFT"
5. select a network
6. enter a valid contract address and token id
7. wait for metadata fetching to finish

### Actual result

Token name edits would only work if on-chain data was not found

https://github.com/user-attachments/assets/d22738c6-44a3-4d07-b239-932ece98bc3c

### Expected result

Token name should not be editable if the information was pre-filled with on-chain data
Token name should be editable if the information was not pre-filled with on-chain data

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.117 Chromium: 127.0.6533.57 (Official Build) beta (arm64) 

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by LaurenWags** [comment]
Requires `1.69.124` or higher for testing 👍🏻

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.136 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 47255350e0d135b2172cb9dd2ba344d3d7fe4572
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified Token name and Token Symbol is auto populated when a valid Contract address is added and network selected
- Verified only Token name can be edited but not the Token Symbol

https://github.com/user-attachments/assets/8747bebf-e779-4f94-8885-ab1af096c46d
