### ISSUE TITLE
[Wallet] Edit NFT form adds a new token instead of updating the existing token

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39921]
### Description

Currently, when editing an NFT a new NFT is added and the existing one is still visible. 

### Steps to reproduce

1. Load a wallet the owns an ERC721 NFT
2. edit the NFT via the Edit NFT form

### Actual result

The edited NFT is not removed and a new NFT with the edits is added.

https://github.com/user-attachments/assets/3729d82c-d567-4088-b951-b952970cdea4

### Expected result

The edited NFT is removed and a new NFT with the edits is added.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.3 Chromium: 127.0.6533.57 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.124 Chromium: 127.0.6533.73 (Official Build) beta (64-bit)
-- | --
Revision | dbc9035349f74e493f3293d93f4cbf35c597dfec
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified editing an NFT updates the NFT to new value
- Verified editing an NFT to a different contract address updates the NFT to new value

https://github.com/user-attachments/assets/51c31e52-0328-420d-97a3-ca46af8eb403
