### ISSUE TITLE
Leo - Remove "New chat" from 3dot menu

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#39931]
### Description

In order to save some menu realstate, let's remove the redundant actions. In this case, new chat. It's a main action in the top bar, so we can remove it from this menu

### Steps to reproduce

--

### Actual result

--

### Expected result

<img width="622" alt="image" src="https://github.com/user-attachments/assets/a072b093-940f-4b42-96ca-9d4367f28ba5">

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

--

### Android device

- Brand/model: 
- Android version: 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.71.104 Chromium: 129.0.6668.89 (Official Build) beta (64-bit)
-- | --
Revision | 3da42496f366e4dc607c58cfdd95ce3f5064c171
OS | Windows 11 Version 23H2 (Build 22631.4169)

- Verified steps from [brave/brave-core#24892](https://github.com/brave/brave-core/pull/24892)
- Verified `New chat` is removed from 3dot menu and only shown when a new conversation is started

https://github.com/user-attachments/assets/cb262c93-574b-44aa-b379-5e011651d1d0

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 15` using the following build(s):

```
Brave | 1.71.110 Chromium: 129.0.6668.100 (Official Build) beta (64-bit)
--- | ---
Revision | 46cd0b1af7127687895fcaceff93dd80e29e6f2b
OS | Android 15; Build/AP41.240823.009; 35; REL
```

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/24892#issue-2435920370, ensured that the `New Chat` button is only being displayed when an existing conversation exists and **NOT** appearing when initially opening/interacting with `Leo` as per the following:

https://github.com/user-attachments/assets/d9f09ab7-600a-43f4-95e1-33366dead69d
