### ISSUE TITLE
Leo - Remove "New chat" from 3dot menu

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#39932]
### Description

In order to save some menu realstate, let's remove the redundant actions. In this case, new chat. It's a main action in the top bar, so we can remove it from this menu

### Steps to reproduce

--

### Actual result

--

### Expected result

![image](https://github.com/user-attachments/assets/ef0da457-ecf3-4f33-a864-5f9a63363bd0)

### Reproduces how often

Easily reproduced

### Brave version

--

### Device/iOS version

--

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7
Brave build: 1.70 (115)
BraveCore: 1.70.115 (129.0.6668.59)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Open `Leo`
3. Tap the `...` menu > *Verify that the `New chat` option is not shown here*
4. Send some queries > Wait for `Leo's` response
5. Tap the button to the left of `...` > *Verify that the conversation is cleared*

**ACTUAL RESULTS:**
- Verified that the `New chat` option is not shown in the `...` menu.
- Verified that the conversation is cleared when tapping the `Clear` button located to the left of `...`.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/4a4f09a9-9e4d-40fa-ae8a-2629d23b582d) | ![2](https://github.com/user-attachments/assets/91ffe777-83d6-487b-a1d6-56e38856bab8) | ![3](https://github.com/user-attachments/assets/f1337d04-de48-48d6-92d8-76140fe37734) | ![4](https://github.com/user-attachments/assets/162b2a9e-62cc-4746-b673-ed1ca018d6cf) |
