### ISSUE TITLE
[Follow up to #39169] Custom Search Engines don't persist on fresh installs

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#39947]
### Description 

On fresh installs after #39169 was merged custom search engines that are added do not persist over launches

### Steps to reproduce

Prefix: Install fresh 1.69.x build after linked issue was merged

1. Visit settings > Search engines > add custom search engine
2. Enter valid info for a search engine and hit save
3. Verify search engine is selectable
4. Force close app and relaunch

### Actual result

Search engine disappears

### Expected result

Search engine should persist

**Comment by kjozwiak** [comment]
The above requires `1.69.137` or higher for `1.69.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6.1
Brave build: 1.69 (160)
BraveCore: 1.69.160 (128.0.6613.114)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/39947#issue-2426021483 and https://github.com/brave/brave-core/pull/24810#issuecomment-2271468227
2. *Verify*

**ACTUAL RESULTS:**
- Verified that custom search engines are not removed on Brave relaunch

---------------------------

https://github.com/user-attachments/assets/3050f9a3-7a53-448f-a406-fe020c6cf8d1
