### ISSUE TITLE
[Wallet] Label NFTs as watch-only until an account balance is found

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39942]
### Description

Currently, we wait for multiple balance registries to exist before showing the watch-only label. We should update this behavior to default to showing the "watch-only" label until an account balance is found

### Steps to reproduce

1. load a wallet that owns EVM and SVM NFTs
2. Add an EVM and SVM NFT that you do not own to the wallet via the "Add NFT" form
3. open the dev-tools and delete the `BRAVE_WALLET_TOKEN_BALANCES4` and `SPAM_TOKEN_BALANCES3` keys from local storage
4. refresh the NFTs portfolio tab page

### Actual result

All NFTs will temporarily render without the "Watch-Only" label until balances are fetched. The "Watch-only" label will disappear once a balance is found for that NFT

### Expected result

All NFTs will temporarily show the "Watch-Only" label until balances are fetched. The "Watch-only" label will disappear once a balance is found for that NFT

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.6 Chromium: 127.0.6533.57 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.105 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | dd1f0aff786e2f4b694066ba8500616833591bf1
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from issue description
- Verified `Watch only` label is shown on all NFTs before balance is checked
- Verified `Watch only` label is removed once the balance is fetched

https://github.com/user-attachments/assets/b544b4e1-890d-4c7a-82f0-ecedce810706
