### ISSUE TITLE
[iOS] - Cleanup Brave-Store Versioning

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#39958]
### Platforms

iOS

### Description

- Currently the iOS code doesn't respect the Brave-Core environment for Skus. It determines its own environment based on the Swift compilation scheme.
- It should respect the Brave-Core environment and also allow overriding the environment.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18` using version `1.70 (126)`

Acceptance Criteria:

- [x] Verified `Brave Services Environment` debug switch is added to override generic services environment.
- [x] Verified default setting is set to `default`.
- [x] Verified In app purchase works for Leo and VPN when changing environments. 

example | example | example | example
---|---|---|---
![Image](https://github.com/user-attachments/assets/1d76c594-eeaf-47a8-b0ee-6f04b0d8c703) | ![Image](https://github.com/user-attachments/assets/5662c7b2-7109-43d9-95ed-6901fcd64408) | ![Image](https://github.com/user-attachments/assets/731f3776-c3e9-4c8d-81b6-ba55c8497ee3) | ![Image](https://github.com/user-attachments/assets/0f40049b-920b-49f9-9b0b-4092c9c73cb5)
