### ISSUE TITLE
Positive Attention value in Rewards Panel despite minimum page time requirement not being met

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3995]
## Steps to Reproduce

   1. Clean profile
   2. Enable rewards
   3. Go to `interia.pl` and wait till the page is added to a-c table
4. Change `Minimum page time before logging a visit` to 1 minute
5. Go to `Interia.pl`
6. Open Rewards Panel

## Actual result:

Positive Attention value

![image](https://user-images.githubusercontent.com/34715963/55525927-50f62280-5693-11e9-82f2-c939e674f7ee.png)

## Expected result:
0% Attention

![image](https://user-images.githubusercontent.com/34715963/55525886-273cfb80-5693-11e9-9446-6067275fb906.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.63.30 Chromium: 73.0.3683.75 (Official Build) beta (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

Brave | 0.65.16 Chromium: 74.0.3729.40 (Official Build) nightly (64-bit)
-- | --
Revision | 278d6a0d856d8314f36fb9a68b6e1d85cd0d14e7-refs/branch-heads/3729@{#470}
OS | Windows 10 OS Build 17134.523

cc @brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
@btlechowski do you see any entry in ac table as well or the only problem is %?

**Comment by btlechowski** [comment]
@NejcZdovc `interia.pl` is not in a-c table as expected. The a-c table is empty as expected. It is only problem with Rewards Panel.

**Comment by NejcZdovc** [comment]
ok thank you

**Comment by jasonrsadler** [comment]
Update. When setting min time to 1 min, publisher stays in ac list until refresh:
`rewards_service_impl.cc(2885)] Problem saving normalized publishers in SaveNormalizedPublisherList`

**Comment by NejcZdovc** [comment]
closing as fixed with https://github.com/brave/brave-core/pull/2520
