### ISSUE TITLE
Replacing kSignedHTTPExchange feature with content::ContentBrowserClient::AllowSignedExchange override

### ISSUE THREAD

**Issue by recvfrom** [brave/brave-browser#39961]
### Description

Just FYI that we plan to remove the kSignedHttpExchange feature flag, which has been enabled by default in Chromium for several years. Brave currently uses this to disable the SignedHttpExchange functionality, but as a workaround Brave can update it's content::ContentBrowserClient subclass to override the AllowSignedExchange method to have it always return false: https://chromium-review.googlesource.com/c/chromium/src/+/5733273/1/content/browser/web_package/signed_exchange_utils.cc

**Comment by LaurenWags** [comment]
@cdesouza-chromium please add the following labels as appropriate:
- `OS/Desktop` and/or `OS/Android` and/or `OS/iOS`
- `release-notes/exclude` or `release-notes/include`
- `QA/No` or `QA/Yes`
   - if `QA/Yes`, please provide a test plan

**Comment by LaurenWags** [comment]
@cdesouza-chromium since this is labeled `QA/Yes` please add a test plan. Labeling as `QA/Blocked` until this is resolved.

cc @bsclifton

**Comment by cdesouza-chromium** [comment]
@LaurenWags Sorry for the delay. We actually don't need manually test this issue, as we already have coverage with a browser test `SignedExchangeRequestBrowserTest`.

**Comment by LaurenWags** [comment]
great! thanks @cdesouza-chromium 👍🏻
