### ISSUE TITLE
Support request: Browser is not updating itself, having trouble importing passwords

### ISSUE THREAD

**Issue by ggrp-byte** [brave/brave-browser#39966]
### Description

I recently updated my browser but now I had a notification that the browser is not up to date so I look in services and there are not 2 services from brave I don't know what to do now because I don't want to log in to all the sites again from scratch again 

### Steps to reproduce

1. normal update
2. nany problem with updating
3. lack of services

### Actual result

![image](https://github.com/user-attachments/assets/68b528cd-e6f1-4078-8da1-54d10c96f8bc)
i dont have 2 services update 

### Expected result

fixed with missing services and getting the latest version without losing data, etc.

### Reproduces how often

Intermittent issue

### Brave version (brave://version info)

Brave	1.66.90 Chromium: 124.0.6367.82 (Oficjalna wersja) beta (64-bitowa) 
Wersja	803a4c629341791205b744969c48b8da9f2cfa4d
System operacyjny	Windows 10 Version 22H2 (Build 19045.4651)
JavaScript	V8 12.4.254.14
Klient	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Wiersz poleceń	"C:\Users\X-Code\AppData\Local\BraveSoftware\Brave-Browser-Beta\Application\brave.exe" --profile-directory=Default --disable-domain-reliability --enable-dom-distiller --enable-distillability-service --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --enable-features=ParallelDownloading,WebContentsForceDark --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions
Ścieżka pliku wykonywalnego	C:\Users\X-Code\AppData\Local\BraveSoftware\Brave-Browser-Beta\Application\brave.exe
Ścieżka profilu	C:\Users\X-Code\AppData\Local\BraveSoftware\Brave-Browser-Beta\User Data\Default
Aktywne warianty	AllowCertainClientHintsStudy:Enabled
BraveAdblockExperimentalListDefaultStudy:Enabled
BraveAdblockMobileNotificationsListDefault:Enabled
BraveAds.CreativeAdModelBasedPredictorRecencyStudy:NoRecency
BraveAdsAdEventStudy:Enabled
BraveAdsConversionsStudy:Enabled
BraveAdsExclusionRulesStudy:Enabled
BraveAdsNewTabPageAdsStudy:Enabled
BraveAdsSiteVisitStudy:Enabled
BraveAdsTextClassificationPageProbabilitiesStudy:Enabled
BraveAggressiveModeRetirementExperiment:Disabled
BraveAutoTranslateStudy:AutoTranslateDisabled
BraveDebounceStudy:Enabled
BraveForgetFirstPartyStorage:Enabled
BraveGoogleSignInPermissionStudy:Enabled
BraveHorizontalTabsUpdateEnabledStudy:Enabled
BraveP3AConstellationEnabled:Enabled
BraveP3AJSONOtherDeprecation:Enabled
BraveP3ANebulaNightlyBeta:Enabled
BraveP3ATypicalJSONDeprecationEnabled:Enabled
BraveRequestOTRTabRolloutStudy:Enabled
BraveRewardsAllowSelfCustodyProvidersStudy:Enabled
BraveRewardsWebUiPanelStudy:Enabled
BraveScreenFingerprintingBlockerStudy:Enabled
BraveSearchAdStudy:Enabled
BraveWalletAnkrBalancesEnabled:Enabled
BraveWebViewRoundedCornersStudy:Enabled
CanvasKillSwitches:Disabled_EmergencyKillSwitch
ClampPlatformVersionClientHint:Disabled
CookieListDefaultStudy:Enabled
CosmeticFilteringChildFramesStudy:Enabled
CrossPlatformVPNStudy:Enabled
CustomNotificationAdsStudy:Enabled
Default1pBlockingStudy:Disabled
DefaultBraveCommandsStudy:Enabled
DisableReduceLanguage:Enabled
EphemeralStorageStudy:Enabled
ForceDarkVariations:AboutFlags
ModuleFileNamePatchStudy:Enabled
PartitionedCookies:Enabled
PrivateNetworkAccessKillswitch:Disabled_PrivateNetworkAccessKillSwitch
Speedreader TTS:Enabled
UseWritePixelsYUV:Disabled_UseWritePixelsYUV
UserActivityStudy:Triggers

### Channel information

- [ ] release (stable)
- [X] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

windows 10 no custom

**Comment by bsclifton** [comment]
@ggrp-byte interesting - I'm curious if you can try reinstalling. Don't worry - it's safe! You won't lose anything 😄 

1. Press Windows + R to pull up the `Run` box and type `appwiz.cpl` and hit enter
2. Find `Brave Beta` in there and right click it and pick `Uninstall`
3. VERY IMPORTANT: a dialog will show up asking if you want to delete the profile data. DO NOT CHECK THE BOX. Just click `Uninstall`.
4. Once it's uninstalled, grab the latest Brave Beta installer from https://brave.com/download-beta/
5. Launch this. It should elevate itself to admin - presenting you with the UAC prompt (`Do you want to allow this app to make changes to this device?`). Make sure to say yes
6. This should register the updater properly

Please give this a go at your earliest convenience and let us know if the NEXT update arrives without an issue.

**Comment by bsclifton** [comment]
> > @ggrp-byte interesting - I'm curious if you can try reinstalling. Don't worry - it's safe! You won't lose anything 😄
> > 
> > 1. Press Windows + R to pull up the `Run` box and type `appwiz.cpl` and hit enter
> > 2. Find `Brave Beta` in there and right click it and pick `Uninstall`
> > 3. VERY IMPORTANT: a dialog will show up asking if you want to delete the profile data. DO NOT CHECK THE BOX. Just click `Uninstall`.
> > 4. Once it's uninstalled, grab the latest Brave Beta installer from https://brave.com/download-beta/
> > 5. Launch this. It should elevate itself to admin - presenting you with the UAC prompt (`Do you want to allow this app to make changes to this device?`). Make sure to say yes
> > 6. This should register the updater properly
> > 
> > Please give this a go at your earliest convenience and let us know if the NEXT update arrives without an issue.
> 
> there's a problem you know because I've uninstalled everything but I still have brave-beta and there's no uninstallable in the panel
> 
> ![image](https://private-user-images.githubusercontent.com/128429494/351830715-a7aa260c-6b33-46a7-b66a-bcdc40735a30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NDY4OTksIm5iZiI6MTcyMTg0NjU5OSwicGF0aCI6Ii8xMjg0Mjk0OTQvMzUxODMwNzE1LWE3YWEyNjBjLTZiMzMtNDZhNy1iNjZhLWJjZGM0MDczNWEzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQxODQzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzI5ODZhOTJjNjBmNTIwYjVhNzc1ZjI0YjM5ZDZmNDljZGNlNTY4OWM0MTdiODQyZmZiMzYzZWRmNmNiMDVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RRzgPxFuSDavb5qVJfozjLjaV9akwvCkdTi-9ryEWIw)

Ah - ok so it DOES seem you had a local non-admin install. **You should be safe to delete the folder `Application` and then try the installation again.**

Basically, when the UAC prompt comes up (asking to elevate to admin), if you click NO - a non-admin install of Brave would be done. This goes into `C:\Users\NAME_HERE\AppData\Local\BraveSoftware` instead of `C:\Program Files\BraveSoftware`. I think that is what happened. That might not always be tracked in `appwiz.cpl`

**Comment by bsclifton** [comment]
@ggrp-byte no - the `Application` folder is safe to delete. Just make sure you exit the browser before you delete - you can download the installer from https://brave.com/download-beta/ first.

There is another folder called `User Data`. DO NOT delete that one. This is where your profile (cookies, saved passwords, history, etc) is at. This is a very important folder - and it could be beneficial to back this folder up occasionally.

**Comment by bsclifton** [comment]
@ggrp-byte I don't know Polish - but I think this is saved passwords screen? For example, URL would be brave://password-manager/passwords

As long as you did not modify `User Data` folder, you should be OK. Did you reinstall the Brave Beta application?

Please let me know what you did so far - and then we can figure it out. Also - these passwords showed before you had tried to reinstall?

**Comment by bsclifton** [comment]
@ggrp-byte OK great. Your profile didn't change - so it should still be readable. Is everything else there? (bookmarks, history, etc)

**Comment by bsclifton** [comment]
@ggrp-byte thanks for the quick reply - OK, that's unfortunate. We are aware of some events which can cause the passwords to be lost. We have an issue tracking this here https://github.com/brave/brave-browser/issues/33548


Basically, the passwords are still there - but they can't be decrypted for some reason. One event is when an administrator makes you change your password. I wonder if you helped us discover the other main reason.

If you still have the old `Application` folder in the trash can, you can try to put this back into place, at `C:\Users\NAME_HERE\AppData\Local\BraveSoftware\Brave-Browser-Beta\Application`. Then, close all instances of Brave - and open that folder and the `brave.exe` inside that folder. I am curious if this one you can see the passwords. If so, there should be an option to export them.

**Comment by bsclifton** [comment]
OK I think you can import the passwords then, from where you did export. This is good news! 

And now after reinstall, your install should be fixed and it should receive updates with no problems.

Please let us know if there is another issue with updates. Thanks!

**Comment by bsclifton** [comment]
OK I apologize @ggrp-byte - I am having a bit of trouble understanding some of your messages.

It's good you fixed for updates. But now this is a new problem - well, new to me. You are reporting that you can import the password and then if you close the browser it disappears again. Is that correct?

**Comment by bsclifton** [comment]
@ggrp-byte Spróbuj tego. Otwórz stronę brave://password-manager/settings w Brave. Tam ten ekran powinien umożliwiać eksport haseł, a także powinien znajdować się przycisk importowania. Czy przycisk importu działa? Udostępniłeś, że dwa dni temu wyeksportowałeś hasła. Daj nam znać!

**Comment by bsclifton** [comment]
OK świetnie - ciekawi mnie, w jakim formacie są hasła. Jeśli masz taką możliwość, możesz skorzystać z programu "Notepad" i przejrzeć zawartość. Przeglądarka oczekuje, że hasła będą w formacie CSV (wartość rozdzielana przecinkami).

Oto przykład, jak plik powinien być sformatowany:
```
name,url,username,password,note
example.com,https://example.com/login,userNameHere,passwordHere,
example2.com,https://example2.com/login,userNameHere,passwordHere,
```

**Comment by bsclifton** [comment]
Czy możesz to dla mnie sprawdzić?

Odwiedź brawa://settings/clearBrowserData i upewnij się, że żadne z pól wyboru nie jest zaznaczone. Możliwe jest usunięcie hasła przy wyjściu - mam nadzieję, że to hasło nie jest włączone.

Proszę daj mi znać. Inną rzeczą, którą możemy sprawdzić, jest sprawdzenie, gdzie są przechowywane hasła. Na dysku znajduje się on w C:\Users\NAME_HERE\AppData\local\BraveSoftware\Brave-Browser-Beta\User Data\Default\Login Data

Upewnij się, że masz ten plik. Możesz wtedy spróbować tego:
1. Zamknij instancje Brave
2. Usuń plik `Login Data`.
3. Otwórz ponownie Brave
4. Zaimportuj hasła ponownie

To może rozwiązać problemy z uprawnieniami.

**Comment by bsclifton** [comment]
@ggrp-byte OK, świetnie – wygląda na to, że jesteś w szczęśliwym stanie?

Czy możesz potwierdzić? Zamknę zgłoszenie... ale zawsze możesz mi odpowiedzieć. Dziękuję za zgłoszenie i rozwiązywanie problemów razem ze mną! 😄

**Comment by bsclifton** [comment]
Tak proszę! Jeśli możesz podzielić się szczegółami rozwiązania problemu, byłoby to bardzo pomocne 😄 Mogę to przetłumaczyć, aby każdy, kto szuka, mógł znaleźć rozwiązanie, które zastosowałeś

**Comment by bsclifton** [comment]
For folks who are curious - basically @ggrp-byte was having two problems:
1. Update was not working. This was fixed by uninstalling Brave and then re-installing. No profile data is lost when you do this! 😄 
2. Other problem was passwords disappearing. They would import a CSV file with passwords on brave://password-manager/settings and it looks like it worked. However, when closing and re-opening, the passwords are gone. They solved the problem by going to brave://settings/system and disabling the value `Continue running background apps when Brave is closed`

Thanks!
