### ISSUE TITLE
[Wallet] NFTs portfolio tab does not correctly filter NFTs when "Hide not owned NFTs" is disabled

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39978]
### Description

When the "Hide not owned NFTs" portfolio filter is disabled, NFTs from accounts other than the ones selected in the filters modal continue to appear (but are incorrectly displayed with a "Watch-only" label)

### Steps to reproduce

1. import a wallet with multiple accounts that own NFTs
2. go to brave://wallet/crypto/portfolio/nfts?tab=collected
3. ensure that the NFTs from multiple accounts are shown
4. click the "filter" icon
5. disable the "Hide not owned NFTs" filter
6. deselect one of the accounts that owns NFTs from the "Select accounts" filters sections
7. Click "Save changes"

### Actual result

NFTs from accounts other than the ones selected in the filters modal continue to appear

### Expected result

Only NFTs from the selected account and NFTs that are not owned by any wallet account should be shown in the list

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.128 Chromium: 127.0.6533.73 (Official Build) (arm64) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.68.134` or higher for `1.68.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.68.134 Chromium: 127.0.6533.88 (Official Build) (64-bit)
-- | --
Revision | 71f3c9cc80f92022892bbf6a22c0450ea056ade4
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified NFTs from unchecked accounts don't get listed

https://github.com/user-attachments/assets/a6212327-5d8b-4517-b71e-3b2a6c5d4e5d
