### ISSUE TITLE
[Wallet] Add frontend batching to getNftBalances to avoid SimpleHash cap

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#39970]
### Description

SimpleHash currently imposes a hard cap of 50 NFTs per balance check requests. We should batch the requests to avoid hitting this cap and avoid errors.

### Steps to reproduce

1. import a wallet with more than 50 NFTs ([Anvil](https://book.getfoundry.sh/anvil/?highlight=anvil%20accounts#how-to-use-anvil) accounts usually have a large amount)
2. Navigate to 
3. Observe the developer console

### Actual result

An error is logged that NFT balance fetching failed

### Expected result

NFT balances should load without errors

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.122 Chromium: 127.0.6533.57 (Official Build) beta (arm64) 

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

This is a work-around until core supports batching: [Add batching to getNftBalances and getNftMetadatas](https://github.com/brave/brave-browser/issues/39954#top)

**Comment by kjozwiak** [comment]
The above requires `1.69.130` or higher for `1.69.x` verifications 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.138 Chromium: 127.0.6533.100 (Official Build) beta (64-bit)
-- | --
Revision | 2569cce791e23282c250db59de277f2e81c33d9b
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24832](https://github.com/brave/brave-core/pull/24832)
- Verified no console errors when loading account with more than 50plus NFTs

https://github.com/user-attachments/assets/182de5cb-1381-4586-aba5-86ae6cb9c7ed
