### ISSUE TITLE
issues logging into GitHub

### ISSUE THREAD

**Issue by doncullen** [brave/brave-browser#3997]
## Description 
Not able to login Github.com using Brave browser.  Works fine in Chrome.  Seems similar to issue https://github.com/brave/brave-browser/issues/2489 except it's for Github.  After putting in login info and hitting submit, it simply goes back to login page with no errors. 

## Steps to Reproduce

   1.  Go to Github.com
   2.  If you're logged in, log out. 
   3.  Log in.  It'll fail silently and take you back to login page.

## Actual result:
Fails silently and takes you back to the login page.

## Expected result:
Shows Github dashboard.

## Reproduces how often: 
Easily reproduced.  

## Brave version (brave://version info)

Brave | 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Windows 10 OS Build 17134.407

### Reproducible on current release:
- No clue, don't have dev/beta

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
Result: Even with shields disabled, same result. 

- Is the issue reproducible on the latest version of Chrome? 
Result: Works fine on Chrome. 

### Additional Information
Keep in mind; one thing that may be applicable here is that I was originally logged in already via Chrome prior to importing everything to Brave, so when I attempt to access Github, it sees me as already logged in so I'm able to access everything.  But once I log out and attempt to log back in, that's when it breaks.

**Comment by kjozwiak** [comment]
@doncullen I was able to login multiple times with `0.62.50 Chromium: 73.0.3683.86` using the default shields. Here's the case that I went through:

* installed & opened `0.62.50 Chromium: 73.0.3683.86`
* Logged in (using 2FA) without any issues
* Logged out
* Logged in (using 2FA) without any issues
* Logged out, restarted Brave
* Logged in (using 2FA) without any issues

If you update to `0.62.50 Chromium: 73.0.3683.86` from `0.61.52 Chromium: 73.0.3683.86` using `brave://settings/help`, do you still experience the issue? Are you using any 2FA methods?

**Comment by doncullen** [comment]
Still experiencing the issue even after updating.  Nope, not using 2FA.

**Comment by kjozwiak** [comment]
@doncullen out of curiosity, do you see any errors in the browser console when you try logging in? You can access it by clicking on the `kabob menu` -> `More Tools` -> `Developer Tools`.

**Comment by kjozwiak** [comment]
Could you try something else as well?

* go into `brave://settings/siteData`
* delete all the GitHub cookies

Example:

<img width="729" alt="Screen Shot 2019-04-04 at 1 44 15 PM" src="https://user-images.githubusercontent.com/2602313/55576632-c4258600-56df-11e9-8fef-4f0babeb0f85.png">

Once you remove everything from GH, refresh the page and see if you can login again.

**Comment by doncullen** [comment]
Opened console and set it to retain logs (as default is to clear log when it goes to new page).  This error appears:

index.esm.js:229 POST https://github.com/signup_check/username 422 (Unprocessable Entity)
(anonymous) @ index.esm.js:229
(anonymous) @ index.esm.js:216
(anonymous) @ index.esm.js:210
check @ index.esm.js:161
(anonymous) @ index.esm.js:28
setTimeout (async)
(anonymous) @ index.esm.js:32
index.esm.js:229 XHR failed loading: POST "https://github.com/signup_check/username".

Clearing github cookies and refreshing enabled me to log in with no further issues.   If we're hoping to get people to move to the Brave browser, it'd be good to reduce friction; so it'd help to find why this causes issues.  Otherwise less technically-inclined people may simply write off the browser as broken and move on.

**Comment by kjozwiak** [comment]
> Clearing github cookies and refreshing enabled me to log in with no further issues. If we're hoping to get people to move to the Brave browser, it'd be good to reduce friction; so it'd help to find why this causes issues. Otherwise less technically-inclined people may simply write off the browser as broken and move on.

Awesome, glad it worked for you 👍 Definitely agree that less friction is always better but this issue doesn't happen often or we would definitely hear about it internally. Everyone at Brave basically lives on Slack and GitHub. Either way, finding out what causes this probably a good idea so no one else runs into something like this in the future.
