### ISSUE TITLE
Brave is crashing when I try to open extension in side panel

### ISSUE THREAD

**Issue by vpsone** [brave/brave-browser#39971]
### Description

Brave is crashing whenever I try to open extension in side panel

### Steps to reproduce

1.  Open brave
2.  Try to open extension in side panel

### Actual result

Brave is crashing

### Expected result

It should open extension in side panel

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave:	1.68.128 Chromium: 127.0.6533.73 (Official Build) (64-bit) 
Revision:   800676fd9ede2eb4174bac98c186e53749c7201f
OS:	Linux

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by iamhx** [comment]
Hi, I can confirm that the side panel is causing the browser to crash as well. Same version as @vpsone, but I am using Windows 10 instead of Linux.

**Comment by vpsone** [comment]
For me crash is caused because I removed brave talk and brave wallet from sidebar, adding them back fixed the issue
