### ISSUE TITLE
Brave does not save the password

### ISSUE THREAD

**Issue by H-COOOH** [brave/brave-browser#39980]
### Description

The Brave password manager does not store passwords any more.

### Steps to reproduce

1. open `brave://password-manager/settings`
2. `Import passwords` > `Select file`
3. import was successful
4. close tab `brave://password-manager/settings`
5. reopen tab `brave://password-manager/passwords`
6. all the passwords disappear

### Actual result

step 6 passwords disappear

### Expected result

step 6 passwords won't disappear

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave: 1.68.128 Chromium: 127.0.6533.73 (Official Build) (64-bit)
Revision: 800676fd9ede2eb4174bac98c186e53749c7201f
OS: Windows 10 Version 22H2 (Build 19045.4651)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by MaxTheDesertMan** [comment]
This has happened to my already-stored passwords as well after this update. They're suggested as autofill data and they exist in the Login Data file but password manager is empty and the export option isn't there. 

I tried adding a new password and exporting, but it only exports the new one (which disappears if I close password manager and open it again)

**Comment by H-COOOH** [comment]
> This has happened to my already-stored passwords as well after this update. They're suggested as autofill data and they exist in the Login Data file but password manager is empty and the export option isn't there.
> 
> I tried adding a new password and exporting, but it only exports the new one (which disappears if I close password manager and open it again)

Hi, @MaxTheDesertMan I deleted file `C:\Users\NAME_HERE\AppData\local\BraveSoftware\Brave-Browser-Beta\User Data\Default\Login Data` and imported the passwords again, this worked for me. I guess maybe you could try this.

**Comment by lbr38** [comment]
Having the same issue on Linux with latest Brave Version 1.68.128 Chromium: 127.0.6533.73

**Comment by oidualc** [comment]
Same issue in macOS, already stored passwords are not showing since 1.68 update. Not even the autofill works anymore. Downgrading to 1.67 restores the functionality, so the data is not lost, it's simply not accessible anymore.

**Comment by Fahl-Design** [comment]
same here on linux (Debian 12.6):
```
brave-browser 1.68.128 [Brave Browser/stable main]
├── ist installiert
└── The web browser from Brave
```

**Comment by oidualc** [comment]
Apparently, this is a Chromium issue: https://issues.chromium.org/issues/354847250.
From Brave perspective, there is an ongoing discussion here: https://community.brave.com/t/aggregate-topic-lost-passwords-in-july-2024-update/560154.

**Comment by bsclifton** [comment]
This is basically a duplicate issue of https://github.com/brave/brave-browser/issues/33548 - but this issue has some great info. I'll leave it open for now

@szilardszaloki is checking out the issue now 😄 

Thanks for sharing the command line argument above `--enable-features=SkipUndecryptablePasswords`. This should get most people fixed up. Chromium also had a Windows specific fix that we've pulled in with https://github.com/brave/brave-core/pull/24853.  I'll get this pulled into our Beta and Release channels today

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/33548
