### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by mohitkota2003** [brave/brave-browser#40006]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.67.134 Chromium: 126.0.6478.186
Operating System: Mac OS X 14.5.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open staging.whitecarrot.io
2. Inspect and go to the application tab
3. It will crash . FYI it does not happen on anyother site but happens here. Can you please add the details of logs what would be reason for crash.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/7bce0700-7e4f-570c-0000-000000000000

**Comment by bsclifton** [comment]
@mohitkota2003 I can't reproduce this on our latest version of Brave
```
Brave	1.68.134 Chromium: 127.0.6533.88 (Official Build) (64-bit) 
Revision	71f3c9cc80f92022892bbf6a22c0450ea056ade4
OS	Windows 11 Version 23H2 (Build 22631.3880)
```

Seems to load OK for me
![image](https://github.com/user-attachments/assets/6cd11349-90e2-4c7b-9887-6b09d9703b23)

Can you grab latest and see if it still happens please? Thanks!

**Comment by bsclifton** [comment]
Tested on macOS also and looks good there for me too


```
Brave | 1.68.134 Chromium: 127.0.6533.88 (Official Build) (arm64)
-- | --
Revision | 71f3c9cc80f92022892bbf6a22c0450ea056ade4
OS | macOS Version 14.6 (Build 23G80)
JavaScript | V8 12.7.224.16
```
