### ISSUE TITLE
Brave crashes when closing window

### ISSUE THREAD

**Issue by vargn** [brave/brave-browser#40002]
### Description

After updating to `brave-bin 1:1.68.128-1` on Arch+i3 i'm experiencing crashes whenever I try to close a window.

### Steps to reproduce

1. Open Brave with a handful of windows with multiple tabs in each of them.
2. Choose a window and close all but one tab, then, try closing the last tab or closing the window itself.
3. See crash

### Actual result

The result is that Brave crashes and closes all windows. Upon restart, a restore of all windows are needed.

### Expected result

I expect the window to close without crashing Brave.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.128 Chromium: 127.0.6533.73 (Official Build) (64-bit)
Linux - Arch+i3

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by vargn** [comment]
Probably related to https://github.com/brave/brave-browser/issues/39986

**Comment by Renari** [comment]
This is happening for me on Windows as well.

**Comment by iefremov** [comment]
duplicate
