### ISSUE TITLE
[Wallet] Use RTK for fetching active origin

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#40007]
### Description

We should refactor the active origin logic to use RTK so that the active origin is not requested until needed

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.105 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | dd1f0aff786e2f4b694066ba8500616833591bf1
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from [brave/brave-core#24849](https://github.com/brave/brave-core/pull/24849)
- Verified active origin is shown correctly 

https://github.com/user-attachments/assets/e3b2235e-781f-4505-81b3-22a97e39e56c
