### ISSUE TITLE
Update button is bigger than the other toolbar buttons

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#40003]
### Description

When there's an update available, the update button is showing bigger than the VPN and Extensions buttons. They need to be the same size.

Additionally, the margins between elements should be the same between all of them

Design in library
https://www.figma.com/design/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?node-id=6904-11703&t=LFSLQg47KUmiM2oI-1

### Steps to reproduce

--

### Actual result

![image](https://github.com/user-attachments/assets/472cb819-d511-4577-b7e2-ce32bede545e)

### Expected result

<img width="463" alt="image" src="https://github.com/user-attachments/assets/05b5a4f6-728a-4b6c-85e6-fe61f197fbc6">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

--

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by jagadeshjai** [comment]
![image](https://github.com/user-attachments/assets/7da0583d-8ec4-4e37-872b-fa216a71e4cd)

@aguscruiz I noticed that the margin between all the buttons is consistent except between the `VPN` button and the `Extension Container` **when the border is visible** (the border appears only when the extension is hovered or selected). Could you confirm if we really need to add extra margin specifically between these two?

**Comment by aguscruiz** [comment]
@jagadeshjai great catch! No need for the extra margin, as long as the border doesn't touch the other element. I'm not sure if that extensions border is inset or outset

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.70.101 Chromium: 128.0.6613.120 (Official Build) beta (x86_64)
-- | --
Revision | dc28ab38d07e9fa668801884c0c55f669ce538eb
OS | macOS Version 13.6.9 (Build 22G830)
```
