### ISSUE TITLE
Support fetching BTC accounts from ledger

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#40000]
### Description

First part of this https://github.com/brave/brave-browser/issues/38447

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.71.112 Chromium: 130.0.6723.44 (Official Build) (64-bit)
-- | --
Revision | 7d51df656b247f9432ee714a6d160142a1e11c13
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from [brave/brave-core#24822](https://github.com/brave/brave-core/pull/24822)
- Verified able to fetch BTC accounts from Ledger Wallet
- Verified only Ledger option is shown for BTC Hardware wallet
- Verified BTC Ledger wallet account can be imported during onboarding
- Verified Load more loads the next 5 accounts 
- Encountered [#41613](https://github.com/brave/brave-browser/issues/41613), [#41614](https://github.com/brave/brave-browser/issues/41614)


![Image](https://github.com/user-attachments/assets/d052707d-df4c-4e84-a4a3-7c01606006cc)
![Image](https://github.com/user-attachments/assets/28fe32e9-f0bd-431a-b869-a98509793528)
