### ISSUE TITLE
[Nala]: Fix inverted colors on the Private and Tor windows

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#40018]
I'm pretty sure I dropped a commit which changed these over while rebasing

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.70.30 Chromium: 127.0.6533.73 (Official Build) nightly (x86_64)
-- | --
Revision | 252bfcfa10e3f2a7e92ee1be5b9e488ab43b7218
OS | macOS Version 11.7.10 (Build 20G1427)
```

Private Window.              | Private Window with Tor
-------------------------|------------------------
<img width="1312" alt="Screen Shot 2024-07-30 at 12 00 03 PM" src="https://github.com/user-attachments/assets/b4f127e4-320d-4893-a8d4-718aeb7460e2"> | <img width="1312" alt="Screen Shot 2024-07-30 at 12 02 37 PM" src="https://github.com/user-attachments/assets/698317ce-cba7-421a-a40b-a9c08052cb4b">

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.70.94 Chromium: 128.0.6613.114 (Official Build) beta (64-bit)
-- | --
Revision | 7ee7ec28264896bd8a9aff39cdb9432da38be028
OS | Windows 10 Version 22H2 (Build 19045.4780)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.70.109 Chromium: 128.0.6613.138 (Official Build) beta (64-bit) 
Revision	fec4422ae56f4d9680c71a3c1de60b9a8e5ef32f
OS	Linux
```

Verified the test plan from https://github.com/brave/brave-core/pull/24858
Confirmed expected [Nala] colors shown on vertical view for Private window and Private window with Tor  


Private window | Private window with Tor
------- | ------
![image](https://github.com/user-attachments/assets/4287e0b4-152b-4073-9aaa-4043d3116711)|![image](https://github.com/user-attachments/assets/debc18a1-b6c1-4340-bd1c-ba697a6fdacd)
![image](https://github.com/user-attachments/assets/24185cc4-2477-40e7-8d08-7836a814dcaa)|![image](https://github.com/user-attachments/assets/dce2318e-e9df-445d-9908-e58e86f05105)
