### ISSUE TITLE
Remember a user's contact information that they provide in a webcompat report and auto-fill it

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#40021]
### Platforms

all

### Description

We optionally ask for users to give us their contact information in webcompat reports so @ryanbr can follow-up with them. If they fill in their contact information for one report, we should remember and store that locally, so we can auto-populate it for future reports.

![image](https://github.com/user-attachments/assets/6cc02b4b-4096-4ccf-a878-f17c9b11ee75)

1. If a user removes the contact information on a subsequent report, then we should not auto-populate it for the next report either. In other words, every N+1th report should auto-populate with the contact information sent in the Nth report.
2. The data stored here should only be for that specific profile, and should be erased when the user erases data. We should not store contact info if the user is in Private Window or Tor mode.
3. We'll also add a new toggle in brave://settings/shields (at the end before `Content filtering`): `Store contact information for future broken site reports` with default ON.
4. Lastly, we will add a new line in the `Submit report` panel above the Submit button, right before the Learn More link: "If you provide contact info it will be stored for future reports."

**Comment by MadhaviSeelam** [comment]
Adding `label:QA/Test-All-Platforms` label as per the issue description.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.75.133 Chromium: 132.0.6834.57 (Official Build) nightly (64-bit)
-- | --
Revision | ce1787778a7a5d92e63a29f8be965494ef49cbbd
OS | Windows 11 Version 24H2 (Build 26100.2605)
```

Case 1: Normal Window

1. Installed 1.75.133
2. launched Brave
3. opened `brave://settings/shields` in a new tab
4. verified `Store contact information for future broken site reports` toggle turned `On` by default
5. visited bbc.com in a new tab
6. clicked `Shields` icon in the URL bar
7. turned `Off` the toggle to `Shields Down`
8. clicked "Report broken site" in the Shields panel
9. entered contact information
10. Click "Submit"
11. confirmed `Report a broken site` dialog dismissed and `Thank you!!` message is shown
12. clicked Shields icon -->Report broken site again

#### Confirmed contact information that was entered previously is shown in the dialog and additional details field is blank confirming the report has been sent


step 4 | step 7 | step 9 | step 11 | step 12 
------- | ------ | ------- | -------- | -------
![Image](https://github.com/user-attachments/assets/1aeadc6c-74c7-4bfa-b9d8-ed5e3597821f)|![Image](https://github.com/user-attachments/assets/21f6d653-d09d-4150-a36a-42a29aa515fd)|![Image](https://github.com/user-attachments/assets/41b80c0e-9316-4831-b281-1a1e09774c08)|![Image](https://github.com/user-attachments/assets/061ac5dc-0dbb-499b-bf55-7b1f603c920c)|![Image](https://github.com/user-attachments/assets/437e6840-32d1-42fe-bbb7-8dc07290607d)


Case 2: Private Window

1. Continue from Case 1
   - Shields is down for bbc.com
2. opened Private window via hamburger menu
3. visited bbc.com 
4. verified Shields is DOWN
5. clicked Shields icon --> Report site

####Confirmed the dialog is blank, i.e. previously entered contact info in the Normal window does not appear here.

step 1 | step 4 | step 5 
----- | ----- | ----
![Image](https://github.com/user-attachments/assets/fb76a4dd-c311-4b43-8dc2-f6db3a791dba)|![Image](https://github.com/user-attachments/assets/cc5070f8-af7a-456a-afd3-25a344b2d9ff)|![Image](https://github.com/user-attachments/assets/a716e8ef-373a-40d5-9981-f8ade4565f0f)

Case 3:  Normal window with webcompat reports to OFF

1. Return to Normal window 
2. toggle `Off` for `Store contact information for future broken site reports` in `brave://settings/shields`
3. opened nytimes.com in a new tab
4. clicked `Shields` icon in the URL bar
5. turned `Off` the toggle to `Shields Down`
6. clicked "Report broken site" in the Shields panel
7. entered contact information
8. Click "Submit"
9. confirmed `Report a broken site` dialog dismissed and `Thank you!!` message is shown
10. clicked Shields icon -->Report broken site again

#### Confirmed previously entered contact info does not appear in the dialog field

step 2 | step 5 | step 9 | step 10
----- | ------ | ----- | ------
![Image](https://github.com/user-attachments/assets/1ff27d5f-3228-49a6-b637-a5911fdfff40)|![Image](https://github.com/user-attachments/assets/ba8d3a54-8849-406f-ad67-13e188bbee81)|![Image](https://github.com/user-attachments/assets/5e3ea329-0072-4bef-ad89-93f1cc257467)|![Image](https://github.com/user-attachments/assets/1daf3aba-0e10-4d37-b401-210942e12ba1)

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Mini (6th gen)` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.7.2
- iPad Mini (6th gen) / iPadOS 18.1.1
Brave build: 1.75 (151)
BraveCore: 1.75.151 (132.0.6834.57)
```
---------------------------
<details>
<summary> Normal Tab and "Store contact information for future broken site reports" is ON </summary>

**STEPS:**
1. Install and launch Brave 
2. Hamburger menu > Settings
3. Shields & Privacy > *Verify that `Store contact information for future broken site reports` is ON by default*
4. Close the settings and open any website in the new tab
5. Tap `Brave Shields` > Turn it off
6. Report a Broken Site > Enter `Additional details` and `Contact info`
7. Tap `Submit` > *Verify that the report is sent and the message is dismissed*
8. Open `Brave Shields` again > Report a Broken Site > *Verify that previously entered `Contact info` is shown*
9. Close and restart Brave
10. Open `Brave Shields` again > Report a Broken Site > *Verify that previously entered `Contact info` is shown*


**ACTUAL RESULTS:**
- Verified that `Store contact information for future broken site reports` is ON by default.
- Verified that the report for the broken site could be sent and that the message had been dismissed.
- Verified that the previously entered `Contact info` is shown in the text field even after closing and relaunching Brave.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/f0a3c8f9-36a1-416c-b49e-7135295f8515) | ![2](https://github.com/user-attachments/assets/49e1bc6e-9d73-4f79-9ae7-0ff09aaa626e) | ![3](https://github.com/user-attachments/assets/39f597c6-fe7c-43a8-827f-634d2846c8a9) |
| ![1](https://github.com/user-attachments/assets/cdd1d64a-68bd-4eff-85a6-c0cab7e3cdd2) | ![2](https://github.com/user-attachments/assets/705ba009-4b25-40d7-b4da-0d553b1aa810) | ![3](https://github.com/user-attachments/assets/31a836da-723f-4e36-b092-0d112a9275e5) |
</details>

**Comment by hffvld** [comment]
Verified on `iPad Mini (6th gen)` using version(s):
```
Device/OS: iPad Mini (6th gen) / iPadOS 18.2.1
Brave build: 1.75 (154)
BraveCore: 1.75.154 (132.0.6834.57)
```

Filed follow-up issue #43186
---------------------------
<details>
<summary> Test Case 1: Standard Tab and "Store contact information for future broken site reports" is ON </summary>

**STEPS:**
1. Install and launch Brave 
2. Hamburger menu > Settings
3. Shields & Privacy > *Verify that `Store contact information for future broken site reports` is ON by default*
4. Close the settings and open any website in the new tab
5. Tap `Brave Shields` > Turn it Off
6. Report a Broken Site > Enter `Additional details` and `Contact info`
7. Tap `Submit` > *Verify that the report is sent and the message is dismissed*
8. Open `Brave Shields` again > Report a Broken Site > *Verify that previously entered `Contact info` is shown*
9. Close and restart Brave
10. Open `Brave Shields` again > Report a Broken Site > *Verify that previously entered `Contact info` is shown*

**ACTUAL RESULTS:**
- Verified that `Store contact information for future broken site reports` is ON by default.
- Verified that the report for the broken site could be sent and that the message had been dismissed.
- Verified that the previously entered `Contact info` is shown in the text field even after closing and relaunching Brave.
- Observed that `webcompat` report/call is not sent - #43186.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/9562e771-f57c-4cf5-b1f2-26bc13b8007b) | ![2](https://github.com/user-attachments/assets/a6167242-eb68-4cd2-b13d-ddc29180bea1) | ![3](https://github.com/user-attachments/assets/2e3502c2-932e-4d7e-b874-4a5adaf7299f) |
| ![1](https://github.com/user-attachments/assets/13ddbdac-67f9-40e8-b877-de361620f7f2) | ![2](https://github.com/user-attachments/assets/decddf6c-c94f-4bae-96c7-7cd082b8540c) | ![3](https://github.com/user-attachments/assets/c15fa44c-a72f-432a-a258-15219789734d) |


![Image]()


</details>

<details>
<summary> Test Case 2: Private Tab and "Store contact information for future broken site reports" is ON </summary>

**STEPS:**
1. Continue from Test Case 1
2. Open a new `Private tab` > Go to any website
3. Tap `Brave Shields` > Turn it Off if it was On > *Verify that the previously entered (in 'Standard tab') `Contact info` is NOT shown in the text field*
4. Enter `Additional details` and `Contact info`
5. Tap `Submit` > *Verify that the report is sent and the message is dismissed*
6. Open `Brave Shields` again > Report a Broken Site > *Verify that previously entered `Contact info` is NOT shown*

**ACTUAL RESULTS:**
- Verified that the previously entered (in the `Standard` or `Private` tab) `Contact info` is NOT shown in the text field.
- Verified that the report for the broken site could be sent and that the message had been dismissed.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() |
| ![1]() | ![2]() | ![3]() |
</details>

<details>
<summary> Test Case 3: Standard Tab and "Store contact information for future broken site reports" is OFF </summary>

**STEPS:**
1. Continue from Test Case 1 or 2
2. Hamburger menu > Settings
3. Shields & Privacy > Turn Off `Store contact information for future broken site reports`
4. Close the settings and open any website in the `Standard tab`
5. Tap `Brave Shields` > Turn it Off
6. Report a Broken Site > Enter `Additional details` and `Contact info`
7.  Tap `Submit` > *Verify that the report is sent and the message is dismissed*
8. Open `Brave Shields` again > Report a Broken Site > *Verify that previously entered `Contact info` is NOT shown*

RESULTS:**
- Verified that `Store contact information for future broken site reports` can be `disabled`.
- Verified that the report for the broken site could be sent and that the message had been dismissed.
- Verified that the previously entered `Contact info` is NOT shown in the text field.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() |
| ![1]() | ![2]() | ![3]() |
</details>

**Comment by hffvld** [comment]
Verified on `Galaxy Z Fold 6` using version(s):
```
Device/OS: Galaxy Z Fold 6 / q6quew-user 14 UP1A.231005.007 release-keys
Brave build: 1.75.159
Chromium: 132.0.6834.83 (Official Build) beta (64-bit) 
```

OR

Filed follow-up issue #
---------------------------
<details>
<summary> Test Case 1: Standard Tab and "Store contact information for future broken site reports" is ON </summary>

**STEPS:**
1. Install and launch Brave 
2. Hamburger menu > Settings
3. Shields & Privacy > *Verify that `Store contact information for future broken site reports` is ON by default*
4. Close the settings and open any website in the new tab
5. Tap `Brave Shields` > Turn it Off
6. Report a broken site > Enter `Additional details` and `Contact info`
7. Tap `Submit` > *Verify that the report is sent*
8. Open `Brave Shields` again > Report a broken site > *Verify that previously entered `Contact info` is shown*
9. Close and restart Brave
10. Open `Brave Shields` again > Report a broken site > *Verify that previously entered `Contact info` is shown*

**ACTUAL RESULTS:**
- Verified that `Store contact information for future broken site reports` is ON by default.
- Verified that the report for the broken site could be sent successfully.
- Verified that the previously entered `Contact info` is shown in the text field even after closing and relaunching Brave.
- Verified that `https://webcompat.brave.com` report/call contains `Additional details` and `Contact info`.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/dd47a836-3387-4a42-b8c6-514d4598041d) | ![2](https://github.com/user-attachments/assets/95b9d9f1-0e43-4cc7-b641-ae56f9158881) | ![3](https://github.com/user-attachments/assets/f76f18ce-3bb2-4750-b809-5befe3e3c700) |
| ![1](https://github.com/user-attachments/assets/2746de4b-71f9-42be-96d7-b12a761893a3) | ![2](https://github.com/user-attachments/assets/1fb7c5c9-052b-4ab9-b023-6c1818b8bbb6) | ![3](https://github.com/user-attachments/assets/094ca9b3-e59c-4769-92d9-0f1cc9e3cad1) |
</details>

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` using version(s):
```
Device/OS: Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
Brave build: 1.75.159
Chromium: 132.0.6834.83 (Official Build) beta (64-bit) 
```
---------------------------
<details>
<summary> Test Case 1: Standard Tab and "Store contact information for future broken site reports" is ON </summary>

**STEPS:**
1. Install and launch Brave 
2. Hamburger menu > Settings
3. Shields & Privacy > *Verify that `Store contact information for future broken site reports` is ON by default*
4. Close the settings and open any website in the new tab
5. Tap `Brave Shields` > Turn it Off
6. Report a broken site > Enter `Additional details` and `Contact info`
7. Tap `Submit` > *Verify that the report is sent*
8. Open `Brave Shields` again > Report a broken site > *Verify that previously entered `Contact info` is shown*
9. Close and restart Brave
10. Open `Brave Shields` again > Report a broken site > *Verify that previously entered `Contact info` is shown*

**ACTUAL RESULTS:**
- Verified that `Store contact information for future broken site reports` is ON by default.
- Verified that the report for the broken site could be sent successfully.
- Verified that the previously entered `Contact info` is shown in the text field even after closing and relaunching Brave.
- Verified that `https://webcompat.brave.com` report/call contains `Additional details` and `Contact info`.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/eb296a32-41b9-4219-b3fa-ca68590152c8) | ![2](https://github.com/user-attachments/assets/86be6660-a56d-4c29-92a1-cb4839e21108) | ![3](https://github.com/user-attachments/assets/10adfe53-f3bf-41a4-b80c-72db9baa9f0c) |
| ![1](https://github.com/user-attachments/assets/b3189f27-cc92-4bbb-aa22-3edc4736c93e) | ![2](https://github.com/user-attachments/assets/d9354d3f-2465-4a6d-827b-d5743abfff1a) | ![3](https://github.com/user-attachments/assets/40bf0ac2-639b-4ca5-acd2-9e39568370c6) |
</details>

<details>
<summary> Test Case 2: Private Tab and "Store contact information for future broken site reports" is ON </summary>

**STEPS:**
1. Continue from Test Case 1
2. Open a new `Private tab` > Go to any website
3. Tap `Brave Shields` > Turn it Off if it was On
4. Report a broken site > *Verify that the previously entered (in 'Standard tab') `Contact info` is NOT shown in the text field*
5. Enter `Additional details` and `Contact info`
6. Tap `Submit` > *Verify that the report is sent and the message is dismissed*
7. Open `Brave Shields` again > Report a broken site > *Verify that previously entered `Contact info` is NOT shown*

**ACTUAL RESULTS:**
- Verified that the previously entered (in the `Standard` or `Private` tab) `Contact info` is NOT shown in the text field.
- Verified that the report for the broken site could be sent successfully.
- Verified that `https://webcompat.brave.com` report/call contains `Additional details` and `Contact info`.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/135d4e69-d9dd-46d6-87de-9e607d0f149b) | ![2](https://github.com/user-attachments/assets/e7c7c6f9-1ca5-4c9f-8a84-3c7669717571) | ![3](https://github.com/user-attachments/assets/273f04ba-1073-4400-afeb-63daf2f5caa3) |
| ![1](https://github.com/user-attachments/assets/770fb4d9-ff44-48cb-96fe-7f8e96cc58e9) | ![2](https://github.com/user-attachments/assets/97c6932a-3ce6-4182-8037-acb5bde2350d) | ![3](https://github.com/user-attachments/assets/2c4b5353-0543-45f1-99f9-0eecede499b8) |
</details>

<details>
<summary> Test Case 3: Standard Tab and "Store contact information for future broken site reports" is OFF </summary>

**STEPS:**
1. Continue from Test Case 1 or 2
2. Hamburger menu > Settings
3. Shields & Privacy > Turn Off `Store contact information for future broken site reports`
4. Close the settings and open any website in the `Standard tab`
5. Tap `Brave Shields` > Turn it Off
6. Report a broken site > Enter `Additional details` and `Contact info`
7.  Tap `Submit` > *Verify that the report is sent*
8. Open `Brave Shields` again > Report a Broken Site > *Verify that previously entered `Contact info` is NOT shown*

RESULTS:**
- Verified that `Store contact information for future broken site reports` can be `disabled`.
- Verified that the report for the broken site could be sent successfully.
- Verified that the previously entered `Contact info` is NOT shown in the text field.
- Verified that `https://webcompat.brave.com` report/call contains `Additional details` and `Contact info`.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/14b476e5-e06e-4c0b-ab62-c47e16661e59) | ![2](https://github.com/user-attachments/assets/811fed2c-98ba-4c44-a48a-2b4fbe7fc3a9) | ![3](https://github.com/user-attachments/assets/db6298a2-0a8f-4b60-b8dd-1a6e9f39e7c7) |
| ![1](https://github.com/user-attachments/assets/2fe9c4e0-c758-47f1-aae0-cc96cdeb756b) | ![2](https://github.com/user-attachments/assets/3edb6246-7b58-4382-a622-db488ae2829a) | ![3](https://github.com/user-attachments/assets/6d4c2301-8f83-46b2-8196-4c0d81cb41bc) |
</details>

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.75.168 Chromium: 132.0.6834.111 (Official Build) beta (arm64)
-- | --
Revision | 2b79fecfaacadde603f71291b8292c11ba0d22ac
OS | macOS Version 15.2 (Build 24C101)
```
<details>
<summary>Case 1: Normal Window - PASSED</summary>

1. Installed 1.75.168
2. launched Brave
3. opened `brave://settings/shields` in a new tab
4. verified `Store contact information for future broken site reports` toggle turned `On` by default
5. visited bbc.com in a new tab
6. clicked `Shields` icon in the URL bar
7. turned `Off` the toggle to `Shields Down`
8. clicked "Report site" in the Shields panel
9. entered additional details and contact information in the form
10. Click "Submit"
11. confirmed `Report a broken site` dialog dismissed and `Thank you!!` message is shown
12. clicked Shields icon -->Report site again
13. confirmed contact info is still populated in the form
14. closed Brave and restarted Brave
15. clicked Shields icon -->Report broken site again
16. verified contact info is still populated in the form

#### Confirmed contact information that was entered previously is shown in the dialog


step 4 | step 7-8 | step 9 | step 11 | step 12 | step 15  
------- | ------ | ------- | -------- | ------- | -----  
![Image](https://github.com/user-attachments/assets/b113ddde-761a-4406-8be1-d04d98ee7d3c)|![Image](https://github.com/user-attachments/assets/b083d8eb-990e-4ba1-b405-4785c2f87458|)![Image](https://github.com/user-attachments/assets/5fae82e1-cc29-4541-8996-5d0872c0a2b2)|![Image](https://github.com/user-attachments/assets/239e6948-8053-4c34-8d6c-22d4b846103a)|![Image](https://github.com/user-attachments/assets/ba1790a3-b05c-49cb-80eb-cceef7816f40)|![Image](https://github.com/user-attachments/assets/ffcf0795-4d33-4316-9efb-b5bf4a2d19e2)

</details>

<details>
<summary>Case 2: Private Window - PASSED</summary>

1. Continue from Case 1
   - Shields is down for bbc.com
2. opened Private window via hamburger menu
3. visited bbc.com 
4. verified Shields is DOWN
5. clicked Shields icon --> Report site

####Confirmed the dialog is blank, i.e. previously entered contact info in the Normal window does not appear in the Private window.

step 1 | step 4 | step 5 
----- | ----- | ----

</details>


<details>
<summary>Case 3:  Normal window with webcompat reports to OFF - PASSED</summary>

1. Return to Normal window 
2. toggle `Off` for `Store contact information for future broken site reports` in `brave://settings/shields`
3. opened nytimes.com in a new tab
4. clicked `Shields` icon in the URL bar
5. turned `Off` the toggle to `Shields Down`
6. clicked "Report broken site" in the Shields panel
7. entered contact information
8. Click "Submit"
9. confirmed `Report a broken site` dialog dismissed and `Thank you!!` message is shown
10. clicked Shields icon -->Report broken site again

#### Confirmed previously entered contact info is preserved in the dialog 

step 2 | step 5 | step 7 | step 9 | step 10 
----- | ----- | ------| ----- | ------

</details>

**Comment by btlechowski** [comment]
Verification with

Brave | 1.75.170 Chromium: 132.0.6834.111 (Official Build) beta (64-bit)
-- | --
Revision | ea6b6fa547193f9769ffb0068880a4f41e364864
OS | Linux


<details>
<summary>Case 1: Normal Window - PASSED</summary>

1. Installed 1.75.x
2. launched Brave
3. opened `brave://settings/shields` in a new tab
4. verified `Store contact information for future broken site reports` toggle turned `On` by default
5. visited abcnews.com in a new tab
6. clicked `Shields` icon in the URL bar
7. turned `Off` the toggle to `Shields Down`
8. clicked "Report site" in the Shields panel
9. entered additional details and contact information in the `Report a broken site` form
10. Click "Submit"
11. confirmed `Report a broken site` dialog dismissed and `Thank you!!` message is shown
12. clicked Shields icon -->`Report site` again
13. confirmed contact info is still populated in the `Report a broken site`form
14. closed Brave and restarted Brave
15. clicked Shields icon -->`Report site` again
16. verified contact info is still populated in the `Report a broken site` form

#### Confirmed contact information that was entered previously is shown in the dialog



</details>

<details>
<summary>Case 2: Private Window - PASSED</summary>

1. Continue from Case 1
   - Shields is down for abcnews.com
   - contact details are populated
2. opened Private window via hamburger menu
3. visited abcnews.com 
4. verified Shields is DOWN
5. clicked Shields icon --> Report site

#### Confirmed the dialog is blank, i.e. previously entered contact info in the Normal window does not appear in the Private window.



</details>


<details>
<summary>Case 3:  Normal window with webcompat reports to OFF - PASSED</summary>

1. Return to Normal window 
2. toggle `Off` for `Store contact information for future broken site reports` in `brave://settings/shields`
3. opened nytimes.com in a new tab
4. clicked `Shields` icon in the URL bar
5. turned `Off` the toggle to `Shields Down`
6. clicked "Report broken site" in the Shields panel
7. entered contact information
8. Click "Submit"
9. confirmed `Report a broken site` dialog dismissed and `Thank you!!` message is shown
10. clicked Shields icon -->Report broken site again

#### Confirmed previously entered contact info is no longer preserved in the dialog 



</details>
