### ISSUE TITLE
webcompat toggle list gets out of date

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#40024]
### Description

When a toggle switched in the webcompat UI is flipped, if you hide and re-show the side-panel, the toggle positions are stale.

### Steps to reproduce

1. Visit https://browserleaks.com/javascript
2. Open the webcompat side-panel (click Shield > "Block fingerprinting" integer)
3. Toggle one switch to `disabled`
4. Hide the side-panel (click "<-- Shields" button)
5. Show the side-panel again

### Actual result

The toggle switch is in `enabled` state again. (Note that the actual setting is still `disabled`, but the toggle switch is displaying a stale value.)

### Expected result

The toggle switch should remain `disabled`.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.70.30 Chromium: 127.0.6533.73 (Official Build) nightly (x86_64)
-- | --
Revision | 252bfcfa10e3f2a7e92ee1be5b9e488ab43b7218
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.70.30`
2. launched Brave
3. loaded `https://browserleaks.com/javascript`
4. clicked on the `Shields` icon in the URL bar
5. clicked to toggle `Block fingerprinting` to `Off`/`Disabled`
6. clicked again on the `Shields` icon

### Confirmed the `Block fingerprinting` pref remained `Off`


example | example | example | example
---------|----------|---------|---------
<img width="1312" alt="Screen Shot 2024-07-30 at 12 13 51 PM" src="https://github.com/user-attachments/assets/eecae1fc-d20f-4159-83b5-ab86ec223174"> | <img width="1312" alt="Screen Shot 2024-07-30 at 12 12 34 PM" src="https://github.com/user-attachments/assets/fed8b184-a69e-4706-9134-f11d111c726e"> | <img width="1312" alt="Screen Shot 2024-07-30 at 12 12 43 PM" src="https://github.com/user-attachments/assets/9815cb0d-6807-439c-ac4b-25d538e0151e"> | <img width="1312" alt="Screen Shot 2024-07-30 at 12 12 48 PM" src="https://github.com/user-attachments/assets/295ba51f-f097-49b7-ab6e-0224f076e7ea">

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.70.94 Chromium: 128.0.6613.114 (Official Build) beta (64-bit)
-- | --
Revision | 7ee7ec28264896bd8a9aff39cdb9432da38be028
OS | Windows 10 Version 22H2 (Build 19045.4780)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.70.109 Chromium: 128.0.6613.138 (Official Build) beta (64-bit) 
Revision	fec4422ae56f4d9680c71a3c1de60b9a8e5ef32f
OS	Linux
```

1. installed 1.70.109
2. launched Brave
3. loaded https://browserleaks.com/javascript
4. clicked on the Shields icon in the URL bar
5. verified `Block fingerprinting` is enabled
6. clicked to toggle Block fingerprinting to Off/Disabled
7. clicked again on the Shields icon
8. Confirmed the Block fingerprinting pref remained Off

step 5 | step 6 | step 7 | step 8
------- | ------ | ------ | ------
![image](https://github.com/user-attachments/assets/aa4ce9c6-817d-41b4-bcd7-551c745c4f7a)|![image](https://github.com/user-attachments/assets/7272a855-5976-402f-9095-abf5fd7cb2a3)|![image](https://github.com/user-attachments/assets/065c4745-c3f2-4eba-b48a-407385e4cc77)|![image](https://github.com/user-attachments/assets/6cfd2c54-ced3-4542-b203-a3c511dd16ec)
