### ISSUE TITLE
Title doesn't always update when updating an NFT using different contract address

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#40028]
### Description

Title doesn't always update when updating an NFT using different contract address

### Steps to reproduce

1. Restore wallet with NFTs
2. Edit NFT with different contract address and token id
3. Title doesn't auto update

### Actual result

https://github.com/user-attachments/assets/f1be46fd-efaf-4455-9e25-bd874ad99d96

### Expected result

Update title when new contract address is updated for NFT

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.69.124 Chromium: 127.0.6533.73 (Official Build) beta (64-bit)
-- | --
Revision | dbc9035349f74e493f3293d93f4cbf35c597dfec
OS | Windows 11 Version 23H2 (Build 22631.3880)

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @muliswilliam @josheleonard

**Comment by LaurenWags** [comment]
Requires `1.69.136` or higher for testing 👍🏻

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.136 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 47255350e0d135b2172cb9dd2ba344d3d7fe4572
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified NFT title is updated when updating contract address 

https://github.com/user-attachments/assets/a356a451-9e80-4e2a-a76a-a52f7073c455
