### ISSUE TITLE
Move internals out of ui folder

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#4003]
Currently in we have `internals` folder inside `components/brave_rewards/resources/ui` folder, which actually represents rewards settings page. So we have page inside the page where this pages are different. We should split them and move `internals` in this folder `components/brave_rewards/resources`

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.112 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3462

Verified `brave://rewards` page
![image](https://user-images.githubusercontent.com/34715963/66788867-8ce32d80-eee9-11e9-8327-a54f93de8c5a.png)
Verified rewards banner
![image](https://user-images.githubusercontent.com/34715963/66788884-9ec4d080-eee9-11e9-9860-5ad4a22a6777.png)
Verified `brave://rewards-internals` page
![image](https://user-images.githubusercontent.com/34715963/66788893-aa17fc00-eee9-11e9-8b8e-6e9bf28b5e76.png)

Verified on clean profile and upgrade from 0.70.x
