### ISSUE TITLE
[Wallet/iOS] Send transaction submission status update

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#40039]
https://www.figma.com/design/26xCR66ZscSyVpTKrt85Hn/Transactions?node-id=730-324167&t=OnC4WLRM0z7iDcHG-0

Cancel Transaction will be tracked by issue https://github.com/brave/brave-browser/issues/41800
Speed up Transaction will be tracked by issue https://github.com/brave/brave-browser/issues/41799

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.3 running 1.75 (176) build
- Verified steps from [brave/brave-core#26146](https://github.com/brave/brave-core/pull/26146)
- Verified transaction status screen is updated as per new design

![Image](https://github.com/user-attachments/assets/dbe09834-5587-427c-8b65-87586e9b1dca) | ![Image](https://github.com/user-attachments/assets/4496cf35-aa78-4027-a3b9-c19f7ca37fd1) | ![Image](https://github.com/user-attachments/assets/fd2ffa37-2ca8-4512-9650-737fdd7d9d41)
-- | -- | -- 
![Image](https://github.com/user-attachments/assets/0d6d9c70-9e82-4e96-9f7b-f42f01cb0903) |![Image](https://github.com/user-attachments/assets/98d444df-ed7a-4aa1-9ad4-f2cc54f5c86c)| ![Image](https://github.com/user-attachments/assets/a7837665-93fb-41e4-8577-d2f667695e55)
