### ISSUE TITLE
Add compact mode to horiztonal tabs

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#40044]
### Description

Many users prefer a more compact look to the horizontal tab bar in order to save space. We should provide a setting to give users an opportunity to use a more compact tab bar design. 

See: `https://www.figma.com/design/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?node-id=7571-32173&t=e9VYOVnUzE0SEDme-1`

### Steps to reproduce

See description

### Actual result

Normal/Default size
<img width="829" alt="Screenshot 2024-07-26 at 12 13 37 PM" src="https://github.com/user-attachments/assets/8377878f-2e03-4e1e-b0b4-30b81c54342a">

### Expected result

Compact mode
<img width="752" alt="Screenshot 2024-07-26 at 12 13 55 PM" src="https://github.com/user-attachments/assets/707f41ed-ae99-417c-aedf-41faadd1438c">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.x

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.70.30 Chromium: 127.0.6533.73 (Official Build) nightly (x86_64)
-- | --
Revision | 252bfcfa10e3f2a7e92ee1be5b9e488ab43b7218
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.70.30`
2. launched Brave
3. loaded `brave://flags`
4. flipped `brave://flags/#brave-compact-horizontal-tabs` to `Enabled`
5. clicked on `Restart`

### Confirmed horizontal tabs went to a more-compact mode (height-wise)

example | example
---------|---------
<img width="1312" alt="Screen Shot 2024-07-30 at 11 51 20 AM" src="https://github.com/user-attachments/assets/6e98f394-9b4d-40e8-980f-87bb1411348b"> | <img width="1312" alt="Screen Shot 2024-07-30 at 11 51 51 AM" src="https://github.com/user-attachments/assets/e43de644-9f70-4fb8-8718-171c356ea145">

example | example
---------|---------
<img width="1312" alt="Screen Shot 2024-07-30 at 11 53 29 AM" src="https://github.com/user-attachments/assets/0b658b3c-8144-4332-a5fe-1b67d297634f"> | <img width="1312" alt="Screen Shot 2024-07-30 at 11 53 35 AM" src="https://github.com/user-attachments/assets/3ee58be7-eca1-4c7a-b712-93453ca66354">

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.70.94 Chromium: 128.0.6613.114 (Official Build) beta (64-bit)
-- | --
Revision | 7ee7ec28264896bd8a9aff39cdb9432da38be028
OS | Windows 10 Version 22H2 (Build 19045.4780)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.70.109 Chromium: 128.0.6613.138 (Official Build) beta (64-bit) 
Revision	fec4422ae56f4d9680c71a3c1de60b9a8e5ef32f
OS	Linux
```

1. installed 1.70.109
2. launched Brave
3. loaded brave://flags
4. enabled brave://flags/#brave-compact-horizontal-tabs to Enabled
5. clicked on Restart
6. Confirmed horizontal tabs went to a more-compact mode (height-wise)


Horizontal view

Default mode | compact mode 
-------- | -------
![image](https://github.com/user-attachments/assets/e78ef2e8-bf22-4cfc-870c-f798bafcdf4c)|![image](https://github.com/user-attachments/assets/4ea8ecbb-a4a7-4ded-aee6-4d4d60b7e57c)


Vertical view 
Default mode | compact mode 
-------- | -------
![image](https://github.com/user-attachments/assets/6521f913-fd6d-4be3-850f-c6ebd3e48c83)|![image](https://github.com/user-attachments/assets/dc9ddd36-766a-4119-97f6-621388879602)


Vertical view/Minimized mode
Default mode | compact mode 
-------- | -------
![image](https://github.com/user-attachments/assets/b5c1958d-6287-4753-8c78-8c2626f1c005)|![image](https://github.com/user-attachments/assets/2181c41d-91ca-41e1-98fe-46e620ec4a29)
