### ISSUE TITLE
Remove Obj-C mojo wrapper that uses raw pointers

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#40046]
### Description

The `*OwnedImpl` store a `unique_ptr` instead of going through the mojo framework which can have threading implications. We should use the `*MojoImpl` with a self owned receiver to control the lifetime instead.

**Comment by srirambv** [comment]
Verification passed on iPhone 14 with iOS 18 running 1.71 (123)
- Verified steps from [brave/brave-core#24877](https://github.com/brave/brave-core/pull/24877)
- Verified wallet works as expected without any regressions.
