### ISSUE TITLE
Change "Learn more" to "How does it work?" on onboarding

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#40041]
### Description

Per discussion, @Miyayes would like "Learn more" link to say "How does it work?" instead.

See https://bravesoftware.slack.com/archives/CNH9Q6REV/p1722008371796999?thread_ts=1721233592.471079&cid=CNH9Q6REV for additional information.

### Steps to reproduce

1. Clean profile
2. Enable `#brave-rewards-new-rewards-ui` flag and relaunch
3. Open onboarding (from panel or brave://rewards page)

### Actual result

`Learn more` link

![1 69 x](https://github.com/user-attachments/assets/8f52e900-bcac-4ea2-b350-460c489554e9)

### Expected result

`How does it work?` link

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.x, 1.70.x

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @Miyayes @zenparsing

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.72.83 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | b49615851cd2dc4b1c3f5f13d3207d3c032bfd8d
OS | Windows 10 Version 22H2 (Build 19045.5011)
```

**Comment by LaurenWags** [comment]
Requires 1.72.86 or higher for verification 👍🏻
