### ISSUE TITLE
Brave crashes when it's reduced to the smallest size on screen

### ISSUE THREAD

**Issue by Zylon** [brave/brave-browser#40059]
### Description

Ever since the new tab update of a few days ago, brave now crashes when any instance of it is reduced to the minimum physical size on screen.

This has the added issue that when I then restart brave, it'll again launch in this small size, and report to me that it crashed and asks me if I want to "restore" the previous session.
By the time I clicked "restore" and wait for the browser window to become responsive again, it'll crash and repeat the cycle.
Getting almost infinitely stuck and having to brute-force my way out of it by repeated trial, hoping it takes a little longer to crash.

I am too afraid to repeatedly reproduce this error since I don't wanna risk a chance at losing all my tabs.
So I hope someone else will be willing to test this on other environments and versions and add the necessary detail.

### Steps to reproduce

1. Open brave
2. Un-maximize any brave window if it is maximized
3. drag the bottom-right corner as top-left as possible to resize the window to it's smallest size
4. Wait a few seconds
5. Crashes

### Actual result

Brave crashes

### Expected result

Brave doesn't crash

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
   Brave: 1.68.128 Chromium: 127.0.6533.73 (Official Build) (64-bit)
Revision: 800676fd9ede2eb4174bac98c186e53749c7201f
      OS: Windows 10 Version 21H1 (Build 19043.928)
```

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by genesis224** [comment]
Can confirm it happens to me too

**Comment by rebron** [comment]
@Zylon and @genesis224 Do you both have brave://flags/#brave-horizontal-tabs-update set to disabled?

**Comment by Zylon** [comment]
> @Zylon and @genesis224 Do you both have brave://flags/#brave-horizontal-tabs-update set to disabled?

Tested this on 2 PC's the flag seems to have no impact on brave crashing, it'll do so with the flag set to disabled as well as enabled

**Comment by genesis224** [comment]
> @Zylon and @genesis224 Do you both have brave://flags/#brave-horizontal-tabs-update set to disabled?

Same here ticking it disabled and enables makes no difference on brave crashes

**Comment by simonhong** [comment]
@Ilie-Lesan resolved this issue.

**Comment by kjozwiak** [comment]
The above requires `1.71.116` or higher for `1.71.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.71.116 Chromium: 130.0.6723.58 (Official Build) (64-bit)
-- | --
Revision | 789393dd90da88a1f9abf5a7d05fd8ccff76afa2
OS | Windows 10 Version 22H2 (Build 19045.5011)
```
Reproduced the issue on `1.71.114 Chromium: 130.0.6723.58`
Verified the STR on `1.71.116` and ensured that brave doesn't crash when `drag the bottom-right corner as top-left as possible to resize the window to it's smallest size`
![Image](https://github.com/user-attachments/assets/4554bcbe-3002-4872-847d-036b868bc3df)
