### ISSUE TITLE
[wiki] Minor update on the default value of dcheck_always_on (1->true)

### ISSUE THREAD

**Issue by starrify** [brave/brave-browser#40055]
As of its current revision [27fdf27](https://github.com/brave/brave-browser/wiki/Build-configuration/27fdf279113cff4da324145f40a349d7b0ab4e6b), the wiki page [Build configuration](https://github.com/brave/brave-browser/wiki/Build-configuration/27fdf279113cff4da324145f40a349d7b0ab4e6b) has:
> dcheck_always_on (set to 1 in PRs on non-Windows platforms)

That seems outdated though. The upstream expects it to be a boolean. One example ([ref](https://source.chromium.org/chromium/chromium/src/+/refs/tags/127.0.6533.73:build/config/dcheck_always_on.gni;l=32-33)):
```
  enable_expensive_dchecks =
      is_debug || (dcheck_always_on && !is_official_build)
```

and setting it to `1` would result in errors like this:
```
ERROR at //build/config/dcheck_always_on.gni:33:20: Left side of && operator is not a boolean.
      is_debug || (dcheck_always_on && !is_official_build)
                   ^---------------
Type is "string" instead.
```

This is a minor request as all needed may be to change the suggested value from `1` to `true`. However it's part of the wiki so that I cannot file a pull request with the fix.

**Comment by mihaiplesa** [comment]
Thank you for the suggestion, have updated the wiki.
