### ISSUE TITLE
Simplify bat_get_media in native ledger

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#4005]
Current `bat_get_media.cc` is really  all around and it's hard to add any new platform. Because of this we need to simplify it. This file will now only contain shared functionalities and every platform will have their own file with their own functionalities

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.65.98 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Encountered the following already logged issues: #3590, #3417, #3409
* Verified test plan from https://github.com/brave/brave-core/pull/2167
* Verified additional media related items such as: if the setting for 'Allow Contribution to Videos' is off, no videos were added to ac table. Verified able to tip verified YT and Twitch pubs when AC is off and the expected favicons display in both the Tips list and the Rewards Panel.
