### ISSUE TITLE
No more zip releases for Linux!

### ISSUE THREAD

**Issue by youngunix** [brave/brave-browser#40063]
### Description

Is there a reason for not releasing Linux zip files such as "brave-browser-1.68.131-linux-amd64.zip"?

### Steps to reproduce

1. Go to "https://github.com/brave/brave-browser/releases"
2. Click on "Assets"
3. file not there!

### Actual result

file not found.

### Expected result

file to be found.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

brave-browser-1.68.131-linux-amd64.zip

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by youngunix** [comment]
I believe some files are missing by mistake? 

![Screenshot_2024-07-27_21-43-42](https://github.com/user-attachments/assets/30c5c1de-1041-412e-b0b9-c6f4311ac020)
![Screenshot_2024-07-27_21-44-24](https://github.com/user-attachments/assets/5bb558de-6d2e-4c8c-8423-95880b99a4fe)
![Screenshot_2024-07-27_21-44-54](https://github.com/user-attachments/assets/15fee66f-086a-42bf-84cd-046f96d78eb3)

**Comment by TEMP-ad** [comment]
This was a windows only release to fix a specific issue present only in Windows, that's why there is no other builds no APK, no iOS no Linux and no Mac.

You need to read the release notes.

**Comment by youngunix** [comment]
Back on the menu.
