### ISSUE TITLE
regression: autocomplete highlights entire url bar contents (browser-laptop issues #5943, #5529)

### ISSUE THREAD

**Issue by kaytwo** [brave/brave-browser#4006]
### Description
Much like the previous issues, autocomplete in the url bar eats the first typed character after the new tab is opened - it seems that you have to type sufficiently shortly after opening the new tab for it to happen.

### Steps to Reproduce

  1. open a new tab, preferably via keybinding
  2. type something as quickly as possible to fill in the new empty tab address bar that has focus
  3. observe the first character you type disappearing

**Actual result:**

See gif (slowed down 4x) - I attempted to type "darksky" but the d gets highlighted and then overwritten when I type the 'a'.
![url-bar](https://user-images.githubusercontent.com/587187/55584633-47e47000-56ea-11e9-974c-5c53bcff20fc.gif)

**Expected result:**
Everything I type after the new tab keybind should show up in the url bar.

**Reproduces how often:**

100% when you type fast enough. Tried in a guest window with no extensions. Spamming "command t,asdf" as fast as you can should reproduce it - if you screen record/watch closely, you'll see the a become a full autocomplete suggestion with the entire suggestion highlighted, and then typing sdf will overwrite it.

### Brave Version

**about:brave info:**

Version 0.62.50 Chromium: 73.0.3683.86 (Official Build) (64-bit)

**Reproducible on current live release:**

Yes, on release AFAIK

**Comment by Brave-Matt** [comment]
+1's from Community:
 https://community.brave.com/t/new-tab-deletes-url/52043

**Comment by kaytwo** [comment]
Dupe of #3756
