### ISSUE TITLE
Brave Ads notification always uses release channel icon

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4007]
## Description 

Ad notification uses release channel icon

## Steps to Reproduce

   1. Install Dev(0.64.36)/Beta(0.63.31)
   2. Enable Rewards/Ads
   3. Finish ad trigger critera and wait for the ad to show up
   4. Ad uses release channel icon instead of Dev/Beta respectively 

## Actual result:

![Screenshot from 2019-04-04 16-19-45](https://user-images.githubusercontent.com/17010094/55586144-3c974180-56f6-11e9-8eed-227ca3564e33.png)

## Expected result:
Should use respective channel icon to differentiate which channel build is showing ad notification

## Reproduces how often: 

Easy 

## Brave version (brave://version info)

Brave | 0.63.31 Chromium: 73.0.3683.75 (Official Build) beta(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

Brave | 0.64.36 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Also too small icon similar to #2887 
cc: @tmancey @bridiver

**Comment by tmancey** [comment]
Blocked until https://github.com/brave/brave-browser/issues/9592 is implemented

**Comment by tmancey** [comment]
Closing issue as superseded by https://github.com/brave/brave-browser/issues/9592
