### ISSUE TITLE
NFT collection name and panel header overlap

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#40073]
### Description

NFT collection name and panel header overlap

### Steps to reproduce

1. Restore wallet with NFT
2. Open panel and enable Grouping of NFT
3. Open a collection, header and collection header overlap making it impossible to go back to NFT view 

### Actual result

![image](https://github.com/user-attachments/assets/96afa199-ebd8-425f-b18b-de103a208e66)

### Expected result

Should not have overlapping collection title and panel header

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.69.124 Chromium: 127.0.6533.73 (Official Build) beta (64-bit)
-- | --
Revision | dbc9035349f74e493f3293d93f4cbf35c597dfec
OS | Windows 11 Version 23H2 (Build 22631.3880)

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @josheleonard @muliswilliam

**Comment by LaurenWags** [comment]
Requires `1.69.136` or higher for testing 👍🏻

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.136 Chromium: 127.0.6533.88 (Official Build) beta (64-bit)
-- | --
Revision | 47255350e0d135b2172cb9dd2ba344d3d7fe4572
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from  issue description
- Verified NFT collection name and panel header doesn't overlap

https://github.com/user-attachments/assets/6364cc8d-4d6d-4936-9981-d561513fa8b2
