### ISSUE TITLE
Fix the Ad Rewards settings panel 

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#4008]
References:
Currently the uncashed tokens are sent to the server, against a wallet ID, every week. 
On the 5th of each month, Brave Rewards resets the estimated earnings counter to zero.

Issue:
Because the uncashed tokens are not in sync (weekly redemption vs. one time monthly payment), when the counter resets to zero, the user may perceive that they lost earned tokens. 

Fix:
When the clock gets to the 5th of the month, the user should see the tokens that were not redeemed yet.
- so grant will show all uncashed tokens redeemed
- and the user will see value for tokens not yet redeemed (instead of 0)

Prioritizing it as a P1 since it feels like earned BAT was lost.

@jsecretan @evq @NejcZdovc @tmancey

**Comment by JoelMon** [comment]
I don't see 0 but I do see a lot less then I am supposed to have. Every time I open the program the number drops so it's not only a problem with the date.

**Comment by tmancey** [comment]
> I don't see 0 but I do see a lot less then I am supposed to have. Every time I open the program the number drops so it's not only a problem with the date. https://streamable.com/ekvlv

@JoelMon could you please record a longer video showing the balance continuing to drop so I can investigate further as I am unable to reproduce the issue, thanks

**Comment by JoelMon** [comment]
> > I don't see 0 but I do see a lot less then I am supposed to have. Every time I open the program the number drops so it's not only a problem with the date. https://streamable.com/ekvlv
> 
> @JoelMon could you please record a longer video showing the balance continuing to drop so I can investigate further as I am unable to reproduce the issue, thanks

For the past few releases I've noticed that the balance has not dropped.

I'm using _Version 0.64.40 Chromium: 74.0.3729.61 (Official Build) dev (64-bit)_ and I haven't noticed any drop. I'll continue to keep my eyes on it and let you know if I see it dropping again, hopefully this time around I'll record it at a better quality. :wave:

**Comment by jsecretan** [comment]
So, discussing with @mandar-brave and @davidtemkin, we want to:

1) Change "Current earnings this month (Estimated") to "Estimated earnings this cycle"
2) On 12:01 on the 5th of every month, reset the notifications and earnings counters to include both uncashed "receipts" and earnings starting from the 1st.

**Comment by jsecretan** [comment]
Because cashed in and un-cashed in confirmations are not currently connected, and because we want to avoid drastic changes to the schema, @tmancey has suggested a way where we know to determine what was not yet cashed in:
If there are 10 transactions in the history and we have 7 unblinded payment tokens, we know that the first 3 transactions were cashed-in and that the last 7 transactions had not been cashed-in.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Verified with test plan provided by @tmancey
