### ISSUE TITLE
 [CR 127] Users report missing passwords in Password Manager

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#40091]
### Description

Starting with 1.68.128 127.0.6533.73 and affected Operating Systems: Windows (10.0.19045, 10.0.22631)

Users are missing passwords from the Password Manager after the latest update. There does not appear to be a country-specific trend.

Chromium issue: https://issues.chromium.org/issues/354847250?pli=1

### Steps to reproduce

1. Launch Brave
2. Goto brave://password-manager/passwords
3. Observe password list
4. Try to sign-in or add a password from a site, e.g. facebook or nytimes
5. Observe no passwords saved

### Actual result

Passwords are not saved.

### Expected result

Passwords are saved.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.128 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Related issues:
https://github.com/brave/brave-browser/issues/39980
https://github.com/brave/brave-browser/issues/33548

**Comment by bsclifton** [comment]
Marking as `QA/No` after talking with @kjozwiak

**Comment by Haider-cys** [comment]
I see this issue now, not sure if there was an update

**Comment by kjozwiak** [comment]
> I see this issue now, not sure if there was an update

@Haider-cys mind creating a new issue? The above is a pretty old/stale issue. Please include as much information as possible 👍 Can file it via https://github.com/brave/brave-browser/issues/new/choose.

**Comment by Haider-cys** [comment]
Not sure what happened, but now it's working
