### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by TheArtsyAxolotl** [brave/brave-browser#40093]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.68.131 Chromium: 127.0.6533.73
Operating System: Windows NT 10.0.22631

URL (if applicable) where crash occurred:

any

Can you reproduce this crash?

yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Separate 1 tab from the rest of the window
2. Click x to close the window with a single tab
3. All Brave windows close without an error message

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/147b0200-3daa-5d0c-0000-000000000000

**Comment by tech-zilla** [comment]
I think this is a duplicate of: https://github.com/brave/brave-browser/issues/39986

**Comment by iefremov** [comment]
dupe https://github.com/brave/brave-browser/issues/40258
