### ISSUE TITLE
Pre-installed PDF shows as Installed by enterprise policy

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#401]
## Description 

Pre-installed PDF shows as Installed by enterprise policy
## Steps to Reproduce

   1. Clean install brave
   2. Open chrome://extensions
   3. Hover over extension badge, shows installed by policy
   4. Click on Details 
   5. Hover over policy icon, shows Installed by enterprise policy

 ## Actual result:

![image](https://user-images.githubusercontent.com/17010094/41794117-4bb486c4-762c-11e8-922f-70e0e47be29a.png)

## Expected result:
Should not show as installed by enterprise poicy

**Comment by bbondy** [comment]
Fix is maybe don't install via admin policy :P

**Comment by bsclifton** [comment]
Verified this is no longer an issue on the DEV channel on macOS... Might be a Windows specific issue

**Comment by bsclifton** [comment]
Verified this also no longer happens on release channel on Windows 👍
