### ISSUE TITLE
Price Impact Displays a Negative Value for LiFi Swaps

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#40109]
### Description

The `Pice Impact` info field is displaying a negative value for `Li.Fi` swaps and bridges.

### Steps to reproduce

1. Open the `Wallet` and navigate to the `Swap` or `Bridge` tab
2. Select some tokens to swap and get a quote
3. Expand the `Advanced Quote Info`
4. `Price Impact` is displaying a negative value

### Actual result

![Screenshot 33](https://github.com/user-attachments/assets/388b11a8-33e4-4e16-9de7-267bc32f1d9f)

### Expected result

Should be an `absolute` value

![Screenshot 34](https://github.com/user-attachments/assets/8821b0ad-c347-40ac-979f-839a004cbfbf)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.129 Chromium: 127.0.6533.73 (Official Build) beta (arm64) 

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.69.132` or higher for `1.69.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.138 Chromium: 127.0.6533.100 (Official Build) beta (64-bit)
-- | --
Revision | 2569cce791e23282c250db59de277f2e81c33d9b
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from `https://github.com/brave/brave-core/pull/24923`
- Verified `Advanced Quote Info` doesn't show any `negative` value for `Price Impact`

https://github.com/user-attachments/assets/f16511fc-37b4-48c4-a01c-8d018617b1f0
