### ISSUE TITLE
[Wallet] Make the interactionNotifier a singleton

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#40113]
### Description

We should prevent multiple instances of this class from being created

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.94 Chromium: 128.0.6613.114 (Official Build) beta (64-bit)
-- | --
Revision | 7ee7ec28264896bd8a9aff39cdb9432da38be028
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from [brave/brave-core#24925](https://github.com/brave/brave-core/pull/24925)
- Verified wallet auto-lock works as expected after inactivity timeout
