### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by BenShill00r** [brave/brave-browser#40116]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.68.131 Chromium: 127.0.6533.73
Operating System: Windows NT 10.0.22631

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Its not an extension. I opend the browser on a different computer where i sync all extension.
2. I have a lot open tabs, im trying to close these (deleted "sessions" & "session storage". No different.
3. How can i delete the cash manually with the explorer? 

I need this profile working!

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/649d0600-3daa-5d0c-0000-000000000000

**Comment by iefremov** [comment]
not actinable
