### ISSUE TITLE
[Wallet] Remove API Proxy React Context

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#40127]
### Description

This context is no longer needed now that we auto-mock the api proxy in jest and storybook

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.105 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | dd1f0aff786e2f4b694066ba8500616833591bf1
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from [brave/brave-core#24933](https://github.com/brave/brave-core/pull/24933)
- Verified Mnemonic is accessible in the `Back up now` screen
- Verified Mnemonic is accessible from Backup option in Wallet menu
- Verified entering wrong password on backup now screen three times in a row locks wallet
- Verified Account private keys are accessible/exportable after entering valid password 
- Verified entering wrong password on export private key screen three times in a row locks wallet

https://github.com/user-attachments/assets/bc3b8ef4-4025-4bd1-b4e1-7a3ac39c3504
