### ISSUE TITLE
Better explanation of webcompat toggle side panel

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#40128]
### Platforms

Linux, macOS, Windows

### Description

We need a Learn More link or better phrasing for the webcompat exceptions side panel.

**Comment by arthuredelstein** [comment]
Here's what it looks like currently:

![image](https://github.com/user-attachments/assets/15094c90-faee-49fc-81f5-7216ad032e25)

**Comment by ShivanKaul** [comment]
The following would be useful:
1. Have a sentence above "N fingerprinting protections applied" saying "These APIs were used on this page which Brave farbled. Learn more here."
2. Learn more link points to a new wiki page.
3. nit: can we make the "Fingerprinting" lowercase?
4. In the preceding screen, change it from the number to an arrow to avoid giving the impression that we "blocked" <number> things.

**Comment by ShivanKaul** [comment]
cc @rmcfadden3 would appreciate help with the wording

**Comment by arthuredelstein** [comment]
> The following would be useful:
> 
> 1. Have a sentence above "N fingerprinting protections applied" saying "These APIs were used on this page which Brave farbled. Learn more here."

I think "Learn more" is a good idea, but the sentence beginning "These APIs..." sounds too technical for most users. I wonder if we can rely on the Learn More link to give a full explanation of what is happening here.

> 2. Learn more link points to a new wiki page.

I'm going to suggest we create a page on support.brave.com

> 3. nit: can we make the "Fingerprinting" lowercase?

We can, but the first letter is currently upper case on the other side panels (for blocking trackers & ads and blocking scripts). So if I change it we should probably change the others to make it consistent.

**Comment by rmcfadden3** [comment]
@ShivanKaul yeah, I'm inclined to agree with @arthuredelstein that both the phrase "These APIs…" and (probably even more so) the word "farbling" are just far too technical for most users. What if we just did `N fingerprinting protections applied. Learn more.` instead?

Agree on hosting this page on support.brave.com. That seems like a good spot for it.

And then, as far as the capitalization, agreed on going lowercase. I also saw a nit with the word ordering on the scripts-blocked message. So these 3 settings panels should be:

- `N trackers & ads blocked`
- `N scripts blocked`
- `N fingerprinting protections applied`

And then, obviously if you append the `Learn more` you'd wanna also add punctuation. So like `N scripts blocked. Learn more.` and so on.

**Comment by ShivanKaul** [comment]
All that sounds great to me

**Comment by arthuredelstein** [comment]
@ShivanKaul @rmcfadden3 I opened a separate ticket for making the titles lowercase, because doing that turns out to be somewhat complicated. I'm happy to work on it, but it would be good to get confirmation there that I'm taking the right approach: https://github.com/brave/brave-browser/issues/40259

For this ticket, I will focus on adding the Learn more link to the fingerprinting (webcompat) side panel.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.71.111 Chromium: 130.0.6723.31 (Official Build) (64-bit)
-- | --
Revision | a39f12f230248c726d3f1cac2d59dd4dcac714d7
OS | Windows 11 Version 23H2 (Build 22631.4317)

```

Installed 1.71.111
launched Brave
relaunched Brave to pull in griffin
visited browserleaks.com in a new tab
clicked Shields icon 
clicked arrow next to `Block fingerprinting`



![Image](https://github.com/user-attachments/assets/c1f815fc-abbf-4ee0-be49-4d5346a988ad)
![Image](https://github.com/user-attachments/assets/69c8f3b8-1458-4118-9887-16a327b5a3e2)
