### ISSUE TITLE
webcompat exceptions manager showing wrong number of invoked APIs on re-used tab

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#40126]
### Description

On a tab that has been reused, the number of invoked APIs doesn't get refreshed

### Steps to reproduce

1. Open arthuredelstein.net on a fresh tab
2. Note that there is ~1 invoked API
3. Go to amtrak.com on a fresh tab
4. Note that there are ~9 invoked APIs
5. Go to example.com in the same tab
6. Note that there are ~9 invoked APIs
7. Open example.com on a different tab

### Actual result

arthuredelstein.net "inherits" invoked API from previous site when the same tab is used

### Expected result

Invoked APIs on the toggle list should only refer to the current site.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave 1.70.36

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.70.56 Chromium: 127.0.6533.100 (Official Build) nightly (64-bit)
-- | --
Revision | 3801cffa8369b93eda86add07b1275dabd1c99ea
OS | Windows 10 Version 22H2 (Build 19045.4717)
```

example | example
----------|----------
![image](https://github.com/user-attachments/assets/43688aab-e3d8-45b0-8f5a-38fe8d2aa764) | ![image](https://github.com/user-attachments/assets/dbfd953e-9d77-49cc-8175-9a8f81afcaca)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.70.95 Chromium: 128.0.6613.114 (Official Build) beta (x86_64)
-- | --
Revision | 58a39a29fce4db0417a269766b0157fad397767b
OS | macOS Version 13.6.9 (Build 22G830)
```

**Comment by MadhaviSeelam** [comment]
Verification `Passed` using
```
Brave	1.70.109 Chromium: 128.0.6613.138 (Official Build) beta (64-bit) 
Revision	fec4422ae56f4d9680c71a3c1de60b9a8e5ef32f
OS	Linux
```


1. installed `1.70.109`
2. launched Brave
3. open arthuredelstein.net on a fresh tab
4. note that there is ~1 invoked API
5. went to amtrak.com on a fresh tab
6. noted that there are ~10 invoked APIs
7. went to example.com in the same tab
8. noted that there are ~1 invoked APIs in the re-used tab when different site was used and the count was different
9. opened example.com on a different tab 
10. confirmed that the invoked API count for the new tab is the same (~1) as this site was used in the re-used tab.

step 3 | step 6 | step 8 | step 10
------------|----------|----------------|-----------
![image](https://github.com/user-attachments/assets/da25c651-37c2-43b0-becb-5dff2da9c041)|![image](https://github.com/user-attachments/assets/1d1dc5f0-6865-4a30-8cd6-28e9f39c0e39)|![image](https://github.com/user-attachments/assets/34c6c53c-fd95-4226-b8e7-7c4942bc77a0)|![image](https://github.com/user-attachments/assets/9e8b6234-2049-4217-8fe2-0d81282a0364)
