### ISSUE TITLE
webcompat exceptions items show up on empty page

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#40136]
## Description 

On arthuredelstein.net, we see "screen"
On https://fmarier.org/ we see "screen" and "language"

Why are these appearing? Are they truly invoked in a way that could fingerprint?

**Comment by LaurenWags** [comment]
@arthuredelstein could you please provide a test plan? Labelling as `QA/Blocked` for now.

Also, please add `release-notes/exclude` or `release-notes/include` as appropriate, thanks!

**Comment by arthuredelstein** [comment]
**QA test plan**

Please visit the following domains and check how many items are visible on the per-site Shields menu > Advanced Controls > Block fingerprinting > integer
- arthuredelstein.net (should be 0)
- fmarier.org (should be 0)
- example.com (should be 1, `font`)

e.g.:
<img width="948" alt="image" src="https://github.com/user-attachments/assets/bc00578b-66f5-45ad-9edc-05282b1385b9">

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.70.92 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 711f50838f629ac2be4d1d9592f72adecfd3c928
OS | Windows 11 Version 23H2 (Build 22631.4112)
```

1. Installed 1.70.92
2. launched Brave
3. visited arthuredelstein.net in a new tab
4. clicked Shields >> Advanced Controls
5. confirmed next to `Block Fingerprinting` setting shows integer 0 in the Shields panel
6. visited example.com in a new tab
7. clicked Shields >> Advanced Controls
8. confirmed next to `Block Fingerprinting` setting shows integer 0 in the Shields panel
9. visited example.com in a new tab
10. confirmed next to `Block Fingerprinting` setting shows integer 0 in the Shields panel

`arthuredelstein.net` | `fmarier.org` | 
------ | ------- 
![image](https://github.com/user-attachments/assets/799bb280-3f00-4a04-9fb3-c052233044dd)|![image](https://github.com/user-attachments/assets/1b4d82e9-4c32-4fd0-a1c7-8425fb1a240e)|

`example.com`

example | example
----- | ----
![image](https://github.com/user-attachments/assets/ea4ded62-a10d-47af-af0a-93eb81dbf3c1)|![image](https://github.com/user-attachments/assets/8296c79d-c4cd-485c-bb0d-9f82d9941030)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.92 Chromium: 128.0.6613.85 (Official Build) beta (arm64)
-- | --
Revision | 711f50838f629ac2be4d1d9592f72adecfd3c928
OS | macOS Version 14.6.1 (Build 23G93)
```


1. Installed 1.70.92
2. launched Brave
3. visited arthuredelstein.net in a new tab
4. clicked Shields >> Advanced Controls
5. confirmed next to `Block Fingerprinting` setting shows integer 0 in the Shields panel
6. visited fmarier.org in a new tab
7. clicked Shields >> Advanced Controls
8. confirmed next to `Block Fingerprinting` setting shows integer 0 in the Shields panel
9. visited example.com in a new tab
10. confirmed next to `Block Fingerprinting` setting shows integer 1 in the Shields panel

`arthuredelstein.net` | `fmarier.org` 
------ | ------- 
![image](https://github.com/user-attachments/assets/7cd0ee93-3601-449d-9fc8-90afda230000)|![image](https://github.com/user-attachments/assets/2079f018-7820-4b2c-81a9-2747a19a2157)


`example.com`

example | example
----- | ----
![image](https://github.com/user-attachments/assets/5555ab90-6b36-4c69-bbcc-93a331e39f44)|![image](https://github.com/user-attachments/assets/b705de4a-79fa-4923-bd17-d28e9d8c60c1)

**Comment by hffvld** [comment]
Hi @arthuredelstein 
Is there a way to verify it on `Android`? There is no `number of blocked items` next to `Block Fingerprinting`. 

---------------

*Current behavior in ` 1.70.101`*

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/244b9443-0e47-4820-9f2b-74965105720c) | ![2](https://github.com/user-attachments/assets/764a56d8-0334-4959-8836-6319d1693c99) | ![3](https://github.com/user-attachments/assets/3a5a6e5d-1aeb-468b-a18f-bd5d176f4715) |

**Comment by arthuredelstein** [comment]
Hi @hffvld -- unfortunately there isn't currently an easy to way to verify this. Fortunately it's not really a problem for Android because there isn't a UI either that would alarm users.

**Comment by kjozwiak** [comment]
> Hi @hffvld -- unfortunately there isn't currently an easy to way to verify this. Fortunately it's not really a problem for Android because there isn't a UI either that would alarm users.

@arthuredelstein so was this a fix strictly for `Desktop`? Or it was also fixed for `Android` but users on `Android` just didn't notice/see it due to the UI as you mentioned above. Just wondering if we should remove `OS/Android`. If it also fixes the issue for `Android`, then we can keep the `OS/Android` indicating it was fixed for `Android` but can't really be verified.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.70.109 Chromium: 128.0.6613.138 (Official Build) beta (64-bit) 
Revision	fec4422ae56f4d9680c71a3c1de60b9a8e5ef32f
OS	Linux
```

1. Installed 1.70.109
2. launched Brave
3. visited arthuredelstein.net in a new tab
4. clicked Shields >> Advanced Controls
5. confirmed next to `Block Fingerprinting` setting shows integer 0 in the Shields panel
6. visited fmarier.org in a new tab
7. clicked Shields >> Advanced Controls
8. confirmed next to `Block Fingerprinting` setting shows integer 0 in the Shields panel
9. visited example.com in a new tab
10. confirmed next to `Block Fingerprinting` setting shows integer 1 in the Shields panel

`arthuredelstein.net` | `fmarier.org` 
------ | ------- 
![image](https://github.com/user-attachments/assets/6d1b895b-8ad5-42e6-b2c2-ca154b0f0b9e)|![image](https://github.com/user-attachments/assets/6a5e7565-4635-4ea7-b9f4-1f9797ecdfa8)


`example.com`

example | example
----- | ----
![image](https://github.com/user-attachments/assets/64f1665a-0dfb-42d0-b519-8069223bd854)|![image](https://github.com/user-attachments/assets/af043ac8-cfd5-4a98-ada2-8e4fa7176dab)

**Comment by kjozwiak** [comment]
Adding `QA Pass - Android ARM` & `QA Pass - Android Tab` so the above issue is removed from our QA list of required verifications for `1.70.x`. However, as per https://github.com/brave/brave-browser/issues/40136#issuecomment-2339514296 & https://github.com/brave/brave-browser/issues/40136#issuecomment-2341897115, the above can't be verified on `Android`.
