### ISSUE TITLE
Use modal component from our Brave design system for sync error message

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#4013]
## Description

Currently, an error message shown on sync init has this styling:

![55534117-19e83700-56bc-11e9-8135-2cb490a1ae3c](https://user-images.githubusercontent.com/2388823/55593096-8892b800-56ef-11e9-9bc7-133999f87277.png)

Update the styling of the modal with our Brave design system component and make it clear it's an error. This is a followup issue to https://github.com/brave/brave-core/pull/2155

## Design
![sync init error message](https://user-images.githubusercontent.com/2388823/55593073-77e24200-56ef-11e9-880a-1e8d21a67f52.png)

**Comment by AlexeyBarabash** [comment]
With sync v2 we don't have such message. Closing.
