### ISSUE TITLE
Unknown site favicon for few publishers

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#4016]
## Description 

I have been using the Nightly build as my personal profile for a few days ( since 3 days). I have opened a few YT and Twitch videos along with websites. Around 35 sites got added to a-c table. On the 3rd day, I am seeing unknown site favicon for a few publishers for e.g (Brave.com and Twitch pubs). I have reloaded the brave.com couple of times and correct favicon retained back in a-c table, but for twitch unknown favicon remained unchanged even after the page reload.

## Steps to Reproduce

   1. Open brave 0.65.16
   2.  Enable Rewards 
   3. Open Random websites including YT and Twitch ( used the same profile for 3 days)
   4. Unknown favicon is shown for a few publishers

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/55601563-1a95d180-577f-11e9-9429-993fc4c5f389.png)

## Expected result:
Correct favicon should be displayed

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 0.65.16 Chromium: 74.0.3729.40 (Official Build) nightly (64-bit)
-- | --
Revision | 278d6a0d856d8314f36fb9a68b6e1d85cd0d14e7-refs/branch-heads/3729@{#470}
OS | Windows 10 OS Build 17134.523

### Reproducible on current release: No
- Does it reproduce on brave-browser dev/beta builds? No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information

@brave/legacy_qa

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya can you please inspect the icon and let me know what the url is

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc Please find the below screen.

![image](https://user-images.githubusercontent.com/38657976/55774523-146f6000-5ab3-11e9-80f0-fe6cb461a940.png)

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya I would need the icon as well, thank you

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc Please find the image source as well

![image](https://user-images.githubusercontent.com/38657976/55774779-3ae1cb00-5ab4-11e9-9677-48037b6373f8.png)

**Comment by NejcZdovc** [comment]
all links look good. if you click on the link and then check again (refresh rewards page), do you see the image? Maybe chromium didn't fetch it

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc Click on the link and multiple page reload (brave://rewards) resolved the issue.

![image](https://user-images.githubusercontent.com/38657976/55775542-42ef3a00-5ab7-11e9-9428-a6ed71605eb4.png)

**Comment by NejcZdovc** [comment]
this link is from chromium, so we can't do anything about it if it's not stored int chromium favicon storage. Closing it
