### ISSUE TITLE
Playlist would benefit from a mute function

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#40166]
### Description

Playlist would benefit from a mute function

### Steps to reproduce

1. install `1.70.37` 
2. launch Brave
3. load `https://www.youtube.com/watch?v=n0UXA7oLc-s`
4. click on the musical-note icon in the URL bar, to add it to Playlist
5. play the video in the Playlist sidebar
6. mute the tab
7. mute the site
8. continue to hear media playing...

### Actual result

No ability to mute the playing media in your Playlist

### Expected result

Playlist's sidebar player controls should have a mute button

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.70.37 Chromium: 127.0.6533.73 (Official Build) nightly (64-bit)
-- | --
Revision | 8556062edfbbe9023221ddaca3b6fe81264238c8
OS | Windows 10 Version 22H2 (Build 19045.4717)
```

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

@rebron @aguscruiz @sangwoo108 @szilardszaloki @brave/qa-team

**Comment by aguscruiz** [comment]
Design here:
https://www.figma.com/design/RxyQnpxi9qtf5HmnAj1yH0/Desktop-Playlist?node-id=16-5384&t=dll6tP9cEWTVUwDj-1

**Comment by sangwoo108** [comment]
@aguscruiz , That's nice! How about having volume slider that reveals when mouse is hovered on the button too?

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.94 Chromium: 128.0.6613.114 (Official Build) beta (64-bit)
-- | --
Revision | 7ee7ec28264896bd8a9aff39cdb9432da38be028
OS | Windows 11 Version 23H2 (Build 22631.4112)
```

1. install 1.70.94
2. launch Brave
3. enable playlist via `brave://flags`
4. load https://www.youtube.com/watch?v=4TEhliSh_f4&list=RDEM86xMPPQ1_YmT_v8G_7YUaQ&index=10
5. click playlist icon in the toolbar and to add to the Playlist panel
6. play the video in the playlist player 
7. mute and unmute in the playlist player


#### Confirmed Mute control is available in the playlist player
#### Confirmed mute and unmute worked as expected


example | example | example  
----- | ----- | -----  
![image](https://github.com/user-attachments/assets/d29ebbb8-5074-46be-8a56-83df1d9f2e11)|![image](https://github.com/user-attachments/assets/a4b6df87-62ea-4f74-8f8d-c013ff31eab0)|![image](https://github.com/user-attachments/assets/ade41165-b42f-4e66-8217-240a61e5f511)
