### ISSUE TITLE
Group without assets not hidden when not hiding small balances

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#40164]
### Description

When `Hide Small Balances` is disabled, groups without assets are not hidden

### Steps to reproduce

1. Open Portfolio filters
2. Change group by to Networks
3. Disable `Hide Small Balances`
4. Open Edit User Assets
5. Filter to only one network
6. De-select all selected / visible tokens for that network
7. Verify 

### Actual result

https://github.com/user-attachments/assets/b98e032f-5a83-4b39-b3ce-614d473c90bb

### Expected result

Group without assets should be hidden

### Reproduces how often

Easily reproduced

### Brave version

Any

### Device/iOS version

All

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.0 running 1.70 (107)
- Verified steps from [brave/brave-core#24942](https://github.com/brave/brave-core/pull/24942)
- Verified when grouped by network and hiding all tokens shows no tokens message 

https://github.com/user-attachments/assets/4582f798-88cb-4ed1-96b3-408eddd669cc
