### ISSUE TITLE
Shields should be robust against invalid CSS in stylesheet injections

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#40177]
A recent change to uBO filter lists resulted in the following two cosmetic filters being shipped out to Brave users:

```
##html[lang] > body#body > head\" > div.cv-xwrapper > div.cvc > div.cv-inner
##html[lang] > body#body > head\" > div.cvh.BlockClicksActivityBusy
```

Users who received those rules faced some issues with cosmetic filtering, due to errors thrown by Brave's injected content script. The issue was ultimately resolved by [a serverside patch](https://github.com/brave/brave-core-crx-packager/pull/957) to remove the problematic rules.

An error was shown in the console for affected users:

```
Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '##html[lang] > body#body > head\" > div.cv-xwrapper > div.cvc > div.cv-inner{display:none !important;}'
```

That error ultimately traces to [this `insertRule` call](https://github.com/brave/brave-core/blob/8c0dfe69800e03099ec4196ffc7dc2881f0fd316/components/cosmetic_filters/renderer/cosmetic_filters_js_handler.cc#L101). It turns out that invalid CSS injected here can abort the rest of the injections.

We should add a `try`/`catch` block around the injection to improve robustness against invalid data.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.70.93 Chromium: 128.0.6613.85 (Official Build) beta (x86_64)
-- | --
Revision | d5947d34ee18f45238e77a82783306862f678ac6
OS | macOS Version 13.6.9 (Build 22G830)
```

**Comment by LaurenWags** [comment]
@brave/qa-team use the test plan under https://github.com/brave/brave-core/pull/25015 for verifying this issue 👍🏻

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.70.94 Chromium: 128.0.6613.114 (Official Build) beta (64-bit)
-- | --
Revision | 7ee7ec28264896bd8a9aff39cdb9432da38be028
OS | Windows 10 Version 22H2 (Build 19045.4780)
```

Example | Example
----------|-----------
![image](https://github.com/user-attachments/assets/66d18277-baa9-4423-9fe0-e6a6595e703a) | ![image](https://github.com/user-attachments/assets/11ef1f92-2609-402b-a123-0550f0487dd2)

**Comment by hffvld** [comment]
This issue also affects `Android` devices, but because we don't have access to `Profile` folder on our test devices, we're unable to verify it right now.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave	1.70.110 Chromium: 128.0.6613.138 (Official Build) beta (64-bit) 
Revision	7dec99ca278e09ce2087e9f04914f0aa2507ea4c
OS	Linux
```
Verified test plan from https://github.com/brave/brave-core/pull/25015.
Confirmed no messages in the console about `Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet'`.

Example | Example
----------|-----------
![image](https://github.com/user-attachments/assets/3ab5c168-6ba6-4a24-8836-62b6474836ed) | ![image](https://github.com/user-attachments/assets/f7d3b997-fd1b-4e5a-b3de-428b75e1516a)

**Comment by hffvld** [comment]
Verified on `rooted` `Pixel 6` using version(s):
```
Device/OS: Pixel 6 / oriole-user 14 AP2A.240905.003.F1 release-keys
Brave build: 1.70.114
Chromium: 129.0.6668.42 (Official Build) (64-bit)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/25015#issue-2452275918
2. *Verify*

**ACTUAL RESULTS:**
- Verified that no messages in the console about `Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet'`.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/f5790432-0321-413a-9370-164ed571c027) | ![2](https://github.com/user-attachments/assets/a890d6cb-5e78-48d2-9d8f-589a8dde0448) | ![3](https://github.com/user-attachments/assets/79352e3f-f644-434c-adbc-967ac8e5bda7) |
