### ISSUE TITLE
Chrome icon in PWA

### ISSUE THREAD

**Issue by ClaytonTDM** [brave/brave-browser#40175]
### Description

When opening the options menu for an installed PWA, the Open in Brave option displays a Chrome glyph.

### Steps to reproduce

1. Install any PWA
2. Open the options (top-right, 3 lines)
3. Open in Brave button has Chrome icon

### Actual result

Chrome icon is shown.
![image](https://github.com/user-attachments/assets/e53c0f75-805e-4050-bc7d-40e82346796b)

### Expected result

Brave icon is shown.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave	1.70.38 Chromium: 127.0.6533.73 (Official Build) nightly (64-bit) 
Revision	fa5ba873831ff147e04034be16aa6777471910e6
OS	Linux

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [X] in the latest version of Chrome

### Miscellaneous information

This doesn't seem to happen in the Flatpak version from my testing, as none of the context menu items have icons.

**Comment by ClaytonTDM** [comment]
Found by u/green_facade on r/brave_browser: https://www.reddit.com/r/brave_browser/comments/1egp0h7/chrome_icon_in_pwa/

**Comment by LaurenWags** [comment]
Added `QA/Blocked` as this one has an uplift request and will be verified on the PR/channel it is uplifted to.

**Comment by LaurenWags** [comment]
Requires `1.68.137` or higher to test 👍🏻

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.68.134 Chromium: 127.0.6533.88 (Official Build) (64-bit)
-- | --
Revision | 71f3c9cc80f92022892bbf6a22c0450ea056ade4
OS | Windows 10 Version 22H2 (Build 19045.4651)
```

Reproduced the issue on `1.68.134 Chromium: 127.0.6533.88`
![image](https://github.com/user-attachments/assets/51413cc5-275b-4619-b20f-5c5baa25399a)

Upgraded the profile to `1.68.137 Chromium: 127.0.6533.100` and ensured that Brave icon is displayed in PWA hamburger menu for the "Open in Brave" menu item for both dark and light themes:

Light theme | Dark theme
--------------|--------------
![image](https://github.com/user-attachments/assets/8c639423-3636-457b-8e19-3f76bf37df69) | ![image](https://github.com/user-attachments/assets/92de1660-576b-4803-89e6-c113b2f84ec3)
