### ISSUE TITLE
Leo - Add edited badge on edited user prompts

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#40170]
### Platforms

iOS

### Description

Add `EDITED` badge on user edited messages on iOS. Badge should be reusable with edited AI replies after https://github.com/brave/brave-browser/issues/35343

<img width="382" alt="edited use prompt badge" src="https://github.com/user-attachments/assets/7f5c37b4-67fd-4b59-a233-73bdbb336863">

https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/%F0%9F%94%84-Leo-%5BIN-PROGRESS%5D?node-id=4604-72150&m=dev

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.7
- iPad Air / iPadOS 16.7.2
Brave build: 1.70 (114)
BraveCore: 1.70.114 (129.0.6668.42)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/24950#issue-2440722749
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `New chat` section is removed from `...` menu
- Verified 

---------------------------

`iPhone 14`

|1|2|3|4|5|6|
|:-:|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/d9e6e3bb-834a-4169-93fd-bfdf186b2eed) | ![2](https://github.com/user-attachments/assets/21d2e04c-8f2b-4eed-b29a-03734b9a99b2) | ![3](https://github.com/user-attachments/assets/d72bdfb5-765d-4794-a976-407caacb7302) | ![4](https://github.com/user-attachments/assets/5e173888-2cb8-41bb-b6b3-834811e8bee8) | ![5](https://github.com/user-attachments/assets/41f64ebe-5ffc-4a8e-9406-586d3cea113b) | ![6](https://github.com/user-attachments/assets/cb0a0983-3450-4916-9c67-00bd1cca0e63) |
| ![1](https://github.com/user-attachments/assets/5226b910-6292-4c10-acd0-5dfd7e368929) | ![2](https://github.com/user-attachments/assets/4fc388cf-cadc-45b3-96ca-a010895a5e59) | ![3](https://github.com/user-attachments/assets/5305fc2d-5284-4470-bd55-63b987d53d91) | ![4](https://github.com/user-attachments/assets/77865dff-1d16-41d5-ac4f-282970b36ae0) | ![5](https://github.com/user-attachments/assets/ccdc73ab-e97e-4b00-bbbf-6204dd135ad9) | ![6](https://github.com/user-attachments/assets/49fc3605-0b03-4531-bf1b-2b10479d3f2d) |

`iPad Air`

|1|2|3|4|5|6|
|:-:|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/d1e05822-6f28-4381-8d89-3299c88b7159) | ![2](https://github.com/user-attachments/assets/b5fe32bb-cad6-457c-b415-9fff14e5b565) | ![3](https://github.com/user-attachments/assets/b35ddf99-5d93-404b-b0c9-b87d48640fe2) | ![4](https://github.com/user-attachments/assets/500f6e5a-8dd8-4eef-b44c-d711bb5b95a2) | ![5](https://github.com/user-attachments/assets/c1b6079d-5e08-48fa-a5a4-57ab05a78e8b) | ![6](https://github.com/user-attachments/assets/623ed7de-e04a-4522-b440-d396e0794b3b) |
| ![1](https://github.com/user-attachments/assets/fab9031b-b59d-46e6-bef1-26564acf7d52) | ![2](https://github.com/user-attachments/assets/f4f1fe82-5ba2-4e40-ad79-a202eca90424) | ![3](https://github.com/user-attachments/assets/d72fb0d0-0044-4d46-8d11-e8e39d8d3c89) | ![4](https://github.com/user-attachments/assets/61804d6e-02f1-4ef2-b6d9-1ae4cbd4f752) | ![5](https://github.com/user-attachments/assets/4a843c27-1c5d-4e00-a6e6-fab465390d64) | ![6](https://github.com/user-attachments/assets/7b61864a-5a04-4f80-a27c-71013eb7cdfc) |
