### ISSUE TITLE
Improve authentication callback for Wallet

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#40188]
## Description 

During onboarding process for Brave Wallet the authentication callback does not use its result for a cryptographic operation and this may lead a privileged malicious application to bypass it.

More info: https://github.com/brave/brave-core/security/code-scanning/161
Related to https://github.com/brave/brave-core/pull/24943/files

### Update

Fingeprint authentication algorithm went through security review:
* https://github.com/brave/brave-core/pull/11298 
* https://github.com/brave/reviews/issues/677

**Comment by diracdeltas** [comment]
please tag @kdenhartog and @stoletheminerals  for security review

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.71.97 x64 Beta build
- Verified steps from [brave/brave-core#25104](https://github.com/brave/brave-core/pull/25104)
- Verified biometric unlock for Wallet works as expected
- Verified able to unlock through biometric unlock when wallet is locked manually and unlock via double tap on wallet WebUI
- Verified able to unlock wallet when Brave is removed from memory and relaunched
