### ISSUE TITLE
Wallet is locking while in use

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#40184]
### Description

The Wallet is randomly locking while actively in use.

### Steps to reproduce

1. Go to brave://settings/web3 and set `Automatically lock Brave Wallet` to a low number like `2 minutes`
2. Open your Wallet and navigate to the `Swap` or `Bridge` screen
3. Stay active on this screen by clicking and changing tokens
4. It will eventually `lock`

### Actual result

https://github.com/user-attachments/assets/b3f29f7f-0264-429c-8e33-ec355075dc6b

### Expected result

The `Wallet` should not time-out if you are active.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.21 Chromium: 127.0.6533.73 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.94 Chromium: 128.0.6613.114 (Official Build) beta (64-bit)
-- | --
Revision | 7ee7ec28264896bd8a9aff39cdb9432da38be028
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from issue description
- Verified wallet doesn't lock while in use
