### ISSUE TITLE
Remove Global Javascript and Cookie blocking

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#402]
## Description 
Remove JavaScript and Cookie blocking from global settings as its being managed by Shields.

### Additional Information
#226

**Comment by rebron** [comment]
I think this is issue is meant to remove Chrome's Global Javascript and Cookie blocking in favor of our global shield settings:
https://github.com/brave/brave-browser/issues/606
https://github.com/brave/brave-browser/issues/955

**Comment by btlechowski** [comment]
Verification passes on

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Windows 7

* javascript toggle is deleted from chrome://settings/content/javascript
* `blocked third-party cookies` toggle is deleted from chrome://settings/content/cookies
