### ISSUE TITLE
When OS region is set to the allowlisted country (ex. USA), the rewards can be enabled for the category 3 region `Venezuela`

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#40203]
### Description

Found while testing https://github.com/brave/internal/issues/1163
When OS region is set to the allowlisted country (ex. USA), rewards can be enabled for the category 3 region `Venezuela`

### Steps to reproduce

1. Set OS region to US or any rewards allowed region
2. Download and install `1.69.131`
3. Click on rewards country dropdown and select `Venezuela`
4. Enable rewards for `Venezuela`
5. Rewards is enabled

### Actual result

Rewards can be enabled for `Venezuela`

### Expected result

`Brave rewards not available` message should be shown on the BR panel

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.131

### Channel information

- [ ] release (stable)
- [X] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @Miyayes @zenparsing

**Comment by hffvld** [comment]
The same issue was observed on `Android` as well.

--------------
```
Device/OS: Pixel 7 / panther_beta-user 15 AP31.240617.010 release-keys
Brave build: 1.69.131
Chromium: 127.0.6533.88 (Official Build) beta (64-bit) 
```
--------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/f779b51e-0bc1-4eb3-9235-87c359dc5d66) | ![2](https://github.com/user-attachments/assets/1869f8cd-c7ad-41aa-9122-2cbc7b646e6b) | ![3](https://github.com/user-attachments/assets/5bb7a7a6-f789-4825-98bb-b2f0c9a8431e) |

**Comment by Miyayes** [comment]
Done: https://github.com/brave-intl/payment-services/issues/229

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.69.145 Chromium: 128.0.6613.27 (Official Build) beta (x86_64)
-- | --
Revision | b029337c8485766fbc2dd25b11a46c88c8aaf2b4
OS | macOS Version 13.6.9 (Build 22G830)
```

Verified STR from https://github.com/brave/brave-browser/issues/40203#issue-2442956680 with OS = United States and rewards environment = staging.

Example | Example
--- | ---
<img width="1192" alt="Screenshot 2024-08-14 at 2 04 47 PM" src="https://github.com/user-attachments/assets/ddd375be-6e5b-4dd0-b0e3-9cc645902c49"> | <img width="1183" alt="Screenshot 2024-08-14 at 2 04 55 PM" src="https://github.com/user-attachments/assets/60e2cd83-bb09-4ae7-9921-8c925cdca658">

```
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v4/wallets
> Method: POST
> Content: {"geoCountry":"VE"}
.....
[ RESPONSE ]
> URL: https://grant.rewards.bravesoftware.com/v4/wallets
> Result: Failure
> HTTP Code: 403
> Body: {"code":403,"message":"error creating rewards wallet: geo country is disabled"}
```
