### ISSUE TITLE
Sometimes, the raw `click` handler link is shown on Brave News' Feeds page

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#40206]
### Description

Sometimes, the raw `click` handler link is shown on Brave News' Feeds page

### Steps to reproduce

1. install `1.70.40`
2. launch Brave
3. open a new-tab page
4. scroll down
5. click on `Turn on Brave News`
6. wait for the page to load/render
7. look to the top right of a feed article

### Actual result

`Click`

<img width="1476" alt="Screen Shot 2024-08-01 at 1 41 03 PM" src="https://github.com/user-attachments/assets/8efd26eb-0f44-4ba3-a26a-4924f0751f64">

### Expected result

Should render the 3-dots ellipsis `...`, as shown here

<img width="1476" alt="Screen Shot 2024-08-01 at 1 41 14 PM" src="https://github.com/user-attachments/assets/4e691c82-b1c1-49e0-ada1-d409b1b59ac6">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.70.40 Chromium: 127.0.6533.88 (Official Build) nightly (x86_64)
-- | --
Revision | efaf75994a59fed0cf6318aa9b56e5293fbd676a
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @fallaciousreasoning @LorenzoMinto @brave/qa-team @rebron

**Comment by fallaciousreasoning** [comment]
Hmmm that's not good :fearful:

**Comment by fallaciousreasoning** [comment]
Fixed via https://github.com/brave/leo/pull/770
