### ISSUE TITLE
Incorrect Dark Theme Colors in Wallet Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#40215]
### Description

After the `Nala` update https://github.com/brave/brave-core/pull/24772, there are incorrect `dark-theme` colors in the `Wallet` panel.

- `Buy/SendSwap` buttons `Icon` color
- Panel `Nav` buttons `hover` and `selected` background

### Steps to reproduce

1. Go to brave://settings and change the theme to `dark`
2. Open the `Wallet` Panel
3. The 'Buy/SendSwap' buttons `Icon` color is not correct
4. The `Nav` buttons `hover` and `selected` background is not correct

### Actual result

![Screenshot 49](https://github.com/user-attachments/assets/8ed91152-9349-4283-97cc-77da0983a5a3)

### Expected result

![Image](https://github.com/user-attachments/assets/70d75d73-5d3e-4979-94cc-a1da5899ce91)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.41 Chromium: 127.0.6533.88 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.94 Chromium: 128.0.6613.114 (Official Build) beta (64-bit)
-- | --
Revision | 7ee7ec28264896bd8a9aff39cdb9432da38be028
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from issue description
- Verified `Nav` buttons `hover` and `selected` background is correct on dark theme

https://github.com/user-attachments/assets/d94585bc-cc05-4c08-baa9-97ca5645f6ca
