### ISSUE TITLE
Revert Brave Player code

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#40216]
### Description

Introduced with https://github.com/brave/brave-core/pull/20730 and previously tracked with https://github.com/brave/brave-browser/issues/33997, a feature was added called Brave Player. This could be toggled via brave://flags and then an action icon would show in the omnibox when something eligible for the player was encountered.

The project was put on hold and no further development was done.

**Comment by mihaiplesa** [comment]
Leftovers to be removed in https://github.com/brave/devops/issues/13420
