### ISSUE TITLE
Connect unlock action from WebUI to native unlock screen

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#40224]
## Description 

![image](https://github.com/user-attachments/assets/2e2385e5-0918-416b-a7f1-b40ce063a3d3)

✅ Connect unlock action from WebUI to open Android native unlock screen.
Implement new UI in `lock-screen/index.tsx` that will react to double taps.
Double taps will call `getWalletPageApiProxy().pageHandler.unlockWalletUI()`.

🌲 Branch: https://github.com/brave/brave-core/tree/simone/unlock-action-webui-native

🎨 Figma design: [figma.com/file/oXIiv45pIhF2RGlpEjOfUg/Wallet-onboarding?node-id=6223:70942&mode=dev](https://www.figma.com/file/oXIiv45pIhF2RGlpEjOfUg/Wallet-onboarding?node-id=6223%3A70942&mode=dev)

☂ Main umbrella issue: https://github.com/brave/brave-browser/issues/35294

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.71.97 x64 Beta build
- Verified steps from [brave/brave-core#24992](https://github.com/brave/brave-core/pull/24992)
- Verified when wallet is locked shows the new Lock screen 
- Verified double tapping on the locked screen brings up the native biometric unlock screen
- Verified double tapping on the locked screen brings up the password screen to unlock when Biometric unlock is not enabled

https://github.com/user-attachments/assets/e693dcf8-3a66-41d6-96d3-bc7aaf6ed6b5
