### ISSUE TITLE
Playlist names can be edited to 31+ characters; enforced limit at creation time is 30 chars

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#40229]
### Description

Playlist names can be edited to 31+ characters; enforced limit at creation time is 30 chars

### Steps to reproduce

1. install `1.70.41`
2. launch Brave
3. restart Brave (to pick up Griffin seed)
4. click on `Playlist` in the sidebar
5. click on `Play later`
6. click on `Create new playlist`
7. type `a-z` then a few more characters
8. notice you're limited to `30/30`
9. save playlist
10. click again on the playlist name and choose `Rename`
11. start typing

### Actual result

You're able to edit and add more than the previously-restricted `30` characters

example | example | example
---------|----------|--------
<img width="1487" alt="Screen Shot 2024-08-02 at 11 31 25 AM" src="https://github.com/user-attachments/assets/d69d4ac4-c2d5-402c-81dd-e4a68df22867"> | <img width="1487" alt="Screen Shot 2024-08-02 at 11 31 33 AM" src="https://github.com/user-attachments/assets/25bda1a8-e6f0-4787-987f-ec596fe4f705"> | <img width="1487" alt="Screen Shot 2024-08-02 at 11 31 52 AM" src="https://github.com/user-attachments/assets/86275677-2166-401a-8fcc-82e5805c4ddd">

### Expected result

We should probably also cap this at `30` characters, too

<img width="1487" alt="Screen Shot 2024-08-02 at 11 33 30 AM" src="https://github.com/user-attachments/assets/0a92cce2-e279-4731-98cb-02996e324ae8">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.70.41 Chromium: 127.0.6533.88 (Official Build) nightly (x86_64)
-- | --
Revision | 9303bae9fe07bc2ec7c0cdef139e87304b2d6c96
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

@rebron @sangwoo108 @szilardszaloki @brave/qa-team

**Comment by stephendonner** [comment]
cc @aguscruiz

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.92 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 711f50838f629ac2be4d1d9592f72adecfd3c928
OS | Windows 11 Version 23H2 (Build 22631.4112)
```


1. Installed 1.70.92
2. Launched Brave
3. Enabled brave://flags/#playlist
4. Clicked on Playlist in the sidebar
5. Clicked on Play later
6. Clicked on Create new folder (icon) in the Playlist menu
7. Typed a name that has 30-character limit 
8. Noticed you're limited to 30/30 
9. clicked Create button
10. verified playlist added to the Playlist panel
11. Clicked again on the playlist name and choose Rename
12. Started typing 
13. clicked Save

#### Confirmed rename field is limited 30/30 and new playlist name is shown

step 3 | step 8 | step 10 | step 11 | step 12 | step 13
---- | ----- | ----- | ----- | ----- | -----
![image](https://github.com/user-attachments/assets/97bdf1ab-5fac-44d1-ac13-1af418967219)|![image](https://github.com/user-attachments/assets/bda2c0a7-d048-4daf-b21f-8e50a3f6e03c)|![image](https://github.com/user-attachments/assets/41539bc6-e25d-4df6-b887-b98cc29a0f80)|![image](https://github.com/user-attachments/assets/96ec2600-2d97-4069-a2fb-aa5b3a74886c)|![image](https://github.com/user-attachments/assets/26a449ca-22e8-4160-ad70-1b2e1bad58c5)|![image](https://github.com/user-attachments/assets/5e66efef-8204-4bc8-864d-bedd61fabd94)
