### ISSUE TITLE
[Wallet] Panel closes when there are still pending requests 

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#40226]
### Description

Currently when approving a pending request in the wallet panel, we only check for more pending requests of the same type to determine if the panel should close. We should instead prevent auto-closing the panel until there are no pending requests of any type.

### Request types:

**Generic**
- [Connect to site](https://metamask.github.io/test-dapp/)
- [Decrypt](https://metamask.github.io/test-dapp/)
- [Get Encryption Public Key](https://metamask.github.io/test-dapp/)
- [Sign Message](https://metamask.github.io/test-dapp/)

**EVM**
- [Add token](https://token-faucet.defillama.com/)
- [Approve transaction](https://metamask.github.io/test-dapp/)
- [Add chain](https://chainlist.org/)
- [Switch chain](https://metamask.github.io/test-dapp/)

**SVM**
- [Sign Transaction](https://278tty.csb.app/)
- [Sign All Transactions](https://278tty.csb.app/)

### Steps to reproduce

1. Create pending actions for each request type
2. Approve or cancel all requests

### Actual result

The panel closes when a request is processed unless there are more requests of the same type that are still pending

### Expected result

The panel should stay open until all requests are processed, or manually closed by the user

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.134 Chromium: 127.0.6533.88 (Official Build) (arm64) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.70.94 Chromium: 128.0.6613.114 (Official Build) beta (64-bit)
-- | --
Revision | 7ee7ec28264896bd8a9aff39cdb9432da38be028
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from issue description
- Verified panel is not closed when there are pending requests
- Encountered [#40814](https://github.com/brave/brave-browser/issues/40814)

https://github.com/user-attachments/assets/11e54642-e0ca-4583-86a5-812c35dc11b3
