### ISSUE TITLE
`Open in Playlist` doesn't play nor open the media

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#40233]
### Description

`Open in Playlist` doesn't play nor open the media

Found whilst testing issue [32585](https://github.com/brave/brave-browser/issues/32585)

### Steps to reproduce

1. install `1.70.41`
2. launched Brave
3. restarted to pick up Griffin seed for Playlist
4. load `https://www.youtube.com/watch?v=fiXaHv_9rmQ`
5. add it to your `Play Plater` playlist
6. add another video to the same playlist
7. load `https://www.youtube.com/watch?v=fiXaHv_9rmQ` again
8. click on the music icon with the checkbox in the URL bar
9. choose `Open in Playlist`
10. wait

### Actual result

It opens Playlist and the containing folder, but that's it

<img width="1312" alt="Screen Shot 2024-08-02 at 1 49 18 PM" src="https://github.com/user-attachments/assets/e697aa2b-45cd-4e52-a6f9-f815c4609f0a">

### Expected result

It should've opened/selected, and perhaps even auto-played the media: https://www.youtube.com/watch?v=fiXaHv_9rmQ

<img width="1312" alt="Screen Shot 2024-08-02 at 1 51 33 PM" src="https://github.com/user-attachments/assets/3e9ec96e-c0b9-444a-884f-646e06a80644">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.70.41 Chromium: 127.0.6533.88 (Official Build) nightly (x86_64)
-- | --
Revision | 9303bae9fe07bc2ec7c0cdef139e87304b2d6c96
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @aguscruiz @rebron @sangwoo108 @szilardszaloki @brave/qa-team

**Comment by sangwoo108** [comment]
Might be a regression from https://github.com/brave/brave-core/pull/22702

**Comment by sangwoo108** [comment]
A playlist folder will now show up. But media won't be played automatically.

**Comment by stephendonner** [comment]
> A playlist folder will now show up. But media won't be played automatically.

Thanks!  Not to split hairs, but I think that's acceptable, as it says `Open`, not `Play` so I think that expectation is fair.

**Comment by MadhaviSeelam** [comment]
Verification `Passed` using
```
Brave | 1.71.90 Chromium: 129.0.6668.59 (Official Build) beta (64-bit)
-- | --
Revision | 1f5f0d1b8a45a4c60a78c15df081751e39184b97
OS | Windows 11 Version 23H2 (Build 22631.4169)
```

1. Installed 1.71.90
2. launched Brave
3. enabled brave playlist flag `brave://flags/#playlist`
4. load https://www.youtube.com/watch?v=sKyO2TPzNxw
5. add it to default `Play Later` playlist
6. add another video to the same playlist (https://www.youtube.com/watch?v=xo6bofYGHHM)
7. load https://www.youtube.com/watch?v=sKyO2TPzNxw again
8. click on the playlist icon with the checkbox in the URL bar
9. choose `Open in Playlist`
10. clicked the item to play 

#### Confirmed Play Later bubble opened to show added playlist items, but media doesn't play as expected
#### Confirmed the playlist item played as expected

step 3 | step 5 | step 6 | step 8 | step 9 | step 10
---- | ----- | ----- | ----- | -----
![image](https://github.com/user-attachments/assets/ac12026e-002f-4a2c-9dd0-4c6c71926252)|![image](https://github.com/user-attachments/assets/fc98ab79-f385-4e82-85ee-f94d423022ac)|![image](https://github.com/user-attachments/assets/600a024d-dbf2-479b-917a-db215be5c08f)|![image](https://github.com/user-attachments/assets/6f82099f-e584-4680-bd3a-51007987f59c)|![image](https://github.com/user-attachments/assets/d92f12a1-48fa-4b0c-bc5e-b59f8ef96d15)|![image](https://github.com/user-attachments/assets/bb9c0d6d-50c3-41f2-9c34-b71a5d95974b)
