### ISSUE TITLE
`Create a new folder` for Playlist should be a folder icon with a +

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#40230]
### Description

`Create a new folder` for Playlist should be a folder icon with a +

### Steps to reproduce

1. install `1.70.41`
2. launch Brave
3. restart Brave (to pick up Playlist seed from Griffin)
4. click on `Playlist` in the sidebar
5. look at the `+` icon
6. 

### Actual result

The `Create a new folder` icon is a `+`

example | example
---------|---------
<img width="386" alt="Screen Shot 2024-08-02 at 12 00 38 PM" src="https://github.com/user-attachments/assets/233b4b99-82e9-49a8-bcf1-87a3f7de1383"> | <img width="366" alt="Screen Shot 2024-08-02 at 12 01 09 PM" src="https://github.com/user-attachments/assets/cbbcfc9d-6bc6-4e47-a72d-1b4e71bac488">

### Expected result

According to Figma, it should be a folder with a `+` on it

<img width="471" alt="Screen Shot 2024-08-02 at 11 58 34 AM" src="https://github.com/user-attachments/assets/5cd11c00-6539-4688-a3eb-7b19901825e4">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.70.41 Chromium: 127.0.6533.88 (Official Build) nightly (x86_64)
-- | --
Revision | 9303bae9fe07bc2ec7c0cdef139e87304b2d6c96
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @aguscruiz @rebron @sangwoo108 @szilardszaloki @brave/qa-team

**Comment by aguscruiz** [comment]
Side comment, in dark mode this is not looking ok. Should look the same as light mode 

![image](https://github.com/user-attachments/assets/be495470-d11b-4d47-a2fc-9d425ff68e7e)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.92 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 711f50838f629ac2be4d1d9592f72adecfd3c928
OS | Windows 11 Version 23H2 (Build 22631.4112)
```

1. Installed 1.70.92
2. Launched Brave
3. Enabled brave://flags/#playlist
4. Clicked on Playlist in the sidebar
5. Clicked on Play later

#### Confirmed `Create new folder` (icon) in the Playlist menu is shown as per Figma

example | example 
----- | -----
![image](https://github.com/user-attachments/assets/1ce3254b-9e42-4438-a177-0dae0f6a0d3f)|![image](https://github.com/user-attachments/assets/94d0baf5-ca65-4a7c-802b-23db3f10c165)
