### ISSUE TITLE
Missing `Add media from page` button from Figma

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#40231]
### Description

Missing `Add media from page` button from Figma

### Steps to reproduce

1. install `1.70.41`
2. launched Brave
3. restarted Brave (to pick up Griffin seed for Playlist)
4. clicked on `Playlist` in the sidebar
5. loaded `https://www.youtube.com/watch?v=fiXaHv_9rmQ`
6. looked at the `Playlist` sidebar

### Actual result

No `🎵 + Add media to page` button

<img width="501" alt="Screen Shot 2024-08-02 at 12 23 17 PM" src="https://github.com/user-attachments/assets/9f9a85eb-f2f9-4d78-87ae-676e021b0589">

### Expected result

Per Figma, it should have the `+ Add media to page` button at the bottom

<img width="394" alt="Screen Shot 2024-08-02 at 12 21 09 PM" src="https://github.com/user-attachments/assets/37756d8a-ed69-4ff0-b712-dd35912d5ca6">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.70.41 Chromium: 127.0.6533.88 (Official Build) nightly (x86_64)
Revision | 9303bae9fe07bc2ec7c0cdef139e87304b2d6c96
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @aguscruiz @rebron @sangwoo108 @szilardszaloki @brave/qa-team

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.92 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 711f50838f629ac2be4d1d9592f72adecfd3c928
OS | Windows 11 Version 23H2 (Build 22631.4112)
```

1. install 1.70.92
2. launched Brave
3. enabled brave://flags/#playlist
4. loaded https://www.youtube.com/watch?v=_W4Uht6SpFU
5. clicked on Playlist in the sidebar
6. verified at the Playlist sidepanel
7. clicked `Add media from page` 
8. clicked `Add selected` button in the PlaylistBubble 
9. confirmed `Add media from page` button is not shown
10. selected another playlist https://www.youtube.com/watch?v=rsiJ3rfClfc
11. `Add media from page` button is shown

#### Confirmed `Add media from page` button is shown 
#### Confirmed media added `Play Later` folder

example | example | example
------ | ------ | ------
![image](https://github.com/user-attachments/assets/f04855bf-d3cd-44f4-b358-7a30a0518abe)|![image](https://github.com/user-attachments/assets/b6f958ff-8426-4028-8f65-d15bde4800af)|![image](https://github.com/user-attachments/assets/37f20619-db78-42d9-8250-bebfa36fb8ba)
