### ISSUE TITLE
Keyboard shortcut to exit speedreader

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#40238]
### Platforms

Linux, macOS, Windows

### Description

Personally, I'd prefer if the escape key would exit speedreader

Websites can do things in response to the escape key, why shouldn't speedreader?

Otherwise it could be configurable at `brave://settings/system/shortcuts`

**Comment by rebron** [comment]
cc: @boocmp @fallaciousreasoning

**Comment by fallaciousreasoning** [comment]
I feel like escape should do this (probably not a job for our global shortcuts, should be part of reader mode) - FWIW, I think we treat reader mode as a page navigation, so whatever your shortcut for `back` is should work (i.e. ALT+Left).

If you feel super Brave, you could add escape as a shortcut for back :fearful: - it'll work but I bet you get a bunch of accidental navigations (like `Backspace` used to before Chromium removed it)

**Comment by boocmp** [comment]
@fallaciousreasoning We can't configure Escape (w/o modifiers) as a shortcut because of [this](https://github.com/brave/brave-core/blob/f8dc7e54a04ad8352a0edfaaf095e94e93d831de/browser/resources/settings/shortcuts_page/components/ConfigureShortcut.tsx#L123).
Maybe we can change it ?
- if the current shortcut isn't empty, pressing the Esc closes the dialog
- if the current shortcut is empty, pressing the Esc inserts "Escape"

**Comment by fallaciousreasoning** [comment]
@boocmp ah yeah, that is an issue. That said, I think for making escape close reader mode I think it'd be better to do it as part of the reader mode web view

```ts
window.addEventListener('keydown', e => e.key === 'Escape' && history.go(-1)) // or some mojo api for exiting reader mode
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.99 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | 6751ea52a38e61ce5042efcc55d0d60d76c2266d
OS | Windows 11 Version 23H2 (Build 22631.4112)
```

1. Installed 1.70.99
2. launched Brave
3. visited time.com and clicked to open an article (https://time.com/7008288/industry-marisa-abela-myhala-season-3-interview/)
4. Turned Speedreader icon `on` in the URL bar to enable Speedreader
5. verified the page is shown in Speedreader mode
6. pressed `Esc` key on the keyboard
7. confirmed Speedreader mode dismissed/reverted
8. toggled Speedreader `on` again
9. verified the page is shown in Speedreader mode
10. clicked `Speedreader` button again
11. confirmed Speedreader mode dismissed as expected

step 5 | step 7 | step 9 | step 11
----- | ----- | ----- | -----
![image](https://github.com/user-attachments/assets/69717f2f-9d09-439e-b967-c789a46551db)|![image](https://github.com/user-attachments/assets/1c1efe6d-d1a2-41d6-b40d-2ef3f2d53703)|![image](https://github.com/user-attachments/assets/ff81b233-383b-45fa-aeb9-cfe04f6a5ed6)|![image](https://github.com/user-attachments/assets/c57ab085-9d8c-4e30-b598-069e4bfeb995)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.98 Chromium: 128.0.6613.114 (Official Build) beta (arm64)
-- | --
Revision | 1f10dba5feae5a0e907983a48d23571064fbd81e
OS | macOS Version 14.6.1 (Build 23G93)
```

1. Installed 1.70.98
2. launched Brave
3. visited time.com and clicked to open an article (https://www.newsweek.com/key-nutrients-lacking-diet-adults-alarming-food-1947709)
4. Turned Speedreader icon `on` in the URL bar to enable Speedreader
5. verified the page is shown in Speedreader mode
6. pressed `Esc` key on the keyboard
7. confirmed Speedreader mode dismissed/reverted
8. toggled Speedreader `on` again
9. verified the page is shown in Speedreader mode
10. clicked `Speedreader` button again
11. confirmed Speedreader mode dismissed as expected

step 5 | step 7 | step 9 | step 11
----- | ----- | ----- | -----
![image](https://github.com/user-attachments/assets/9961ede3-0616-4e1a-8dca-7dfa01bf925c)|![image](https://github.com/user-attachments/assets/28fa73f6-9dec-4fe3-aa2a-456241691ab3)|![image](https://github.com/user-attachments/assets/dc32a07b-b23b-49b9-9a8a-ae2e8563b42b)|![image](https://github.com/user-attachments/assets/17b2f784-3b81-48dd-b81b-897594c5bb2c)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.70.109 Chromium: 128.0.6613.138 (Official Build) beta (64-bit) 
Revision	fec4422ae56f4d9680c71a3c1de60b9a8e5ef32f
OS	Linux
```

1. Installed 1.70.98
2. launched Brave
3. visited theatlantic.com and clicked to open an article (https://www.theatlantic.com/science/archive/2024/06/boeing-starliner-launch-nasa-astronauts/678574/)
4. Turned Speedreader icon `on` in the URL bar to enable Speedreader
5. verified the page is shown in Speedreader mode
6. pressed `Esc` key on the keyboard
7. confirmed Speedreader mode dismissed/reverted
8. toggled Speedreader `on` again
9. verified the page is shown in Speedreader mode
10. clicked `Speedreader` button again
11. confirmed Speedreader mode dismissed as expected

step 5 | step 7 | step 9 | step 11
----- | ----- | ----- | -----
![image](https://github.com/user-attachments/assets/a46ce5ef-5e45-4351-bb8b-3d0e5634a955)|![image](https://github.com/user-attachments/assets/3f57ef2b-26f6-42e2-9d14-e9459c911578)|![image](https://github.com/user-attachments/assets/56aac14c-b1be-405d-8218-beaa988b9a0a)|![image](https://github.com/user-attachments/assets/45ab54f6-0ff8-4a2e-a24e-e9e321136ab8)
