### ISSUE TITLE
Don't keep re-drawing webcompat exceptions UI for one page

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#40240]
### Platforms

Android, Linux, macOS, Windows

### Description

In https://github.com/brave/brave-browser/issues/40126 we fixed the problem that old webcompat exceptions were retained in a tab, even when we navigated to a new web page. We fixed that, but now toggling and individual webcompat exception on the same page causes the whole list to be redrawn as the reloaded page loads. We should retain the old toggle items if the page address isn't changing.

**Comment by LaurenWags** [comment]
@arthuredelstein please add the appropriate OS label(s):
- `OS/Desktop` and/or `OS/Android` and/or `OS/iOS`

Also, please add a test plan as this one is currently labeled `QA/Yes`. If that label is incorrect, can change to `QA/No`. Labelling as `QA/Blocked` until this is sorted.

**Comment by arthuredelstein** [comment]
**QA test plan**

Visit, for example, https://maps.gsi.go.jp/index_3d.html?z=16&lat=35.653225&lon=139.73539700000003&pxsize=1024&ls=std#&cpx=61.296&cpy=-75.319&cpz=102.810&cux=0.375&cuy=0.210&cuz=0.902&ctx=0.000&cty=0.000&ctz=0.000&a=1.4&b=0&dd=0.

Under per-site `Shield > Advanced Controls > Block Fingerprinting > integer` note there should be about 5 toggle switches visible (`canvas`, `font`, `screen`, `user agent`, `webgl`). Now toggle some of these off (or on) and confirm that the toggle list items don't disappear (they remain there):

<img width="376" alt="image" src="https://github.com/user-attachments/assets/c4d9bcf7-c704-49da-b09d-eebb9aa6fcc1">

Now, keeping the menu open, try a force-refresh (e.g. shift-command R on Mac or shift-control-R on Windows) and see that the toggle-list items do disappear and then reappear as the page is loaded.

Finally, browser to a new site (such as example.com) in the same tab, and confirm that the list of items is different.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.70.88 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 7431803bd1e909ef82982df42e2ea7aacbad755e
OS | Windows 11 Version 23H2 (Build 22631.4037)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.92 Chromium: 128.0.6613.85 (Official Build) beta (arm64)
-- | --
Revision | 711f50838f629ac2be4d1d9592f72adecfd3c928
OS | macOS Version 14.6.1 (Build 23G93)
```

1. Installed 1.70.92
2. launched Brave
3. relaunched Brave to pull in the griffin study (`BraveScreenFingerprintingBlockerStudy:Enabled`)
4. opened following link in a new tab 
5.   - https://maps.gsi.go.jp/index_3d.html?z=16&lat=35.653225&lon=139.73539700000003&pxsize=1024&ls=std#&cpx=61.296&cpy=-75.319&cpz=102.810&cux=0.375&cuy=0.210&cuz=0.902&ctx=0.000&cty=0.000&ctz=0.000&a=1.4&b=0&dd=0.
6. opened Shields panel > Advanced Controls
7. confirmed Block Fingerprinting` option shows integer `5`
8. clicked on the integer
9. confirmed toggle switches are visible (`canvas`, `font`, `screen`, `user agent`, `webgl`).
10. toggled `canvas` on 
11. toggled `font`  off
12. confirmed that the toggle list items don't disappear (they remain there)
13. confirmed when did a force-refresh (Command+ Shift+ R), items shown when clicked on the integer 
14. opened example.com 
15. confirmed integer `1` is shown for `Block fingerprinting` option
16. clicked `1`
17. confirmed `font` toggle is shown enabled

step 7 | step 9 | step 12 | step 13 | step 15 | step 17 
----- | ------ | ----- | ------- | ------ | ------
![image](https://github.com/user-attachments/assets/c7337b77-20ea-46da-bebd-1169ab9ca2e2)|![image](https://github.com/user-attachments/assets/988b6a83-1b27-4438-a22d-7bc5ff919d55)|![image](https://github.com/user-attachments/assets/a6632451-87d4-47e2-bb07-598f7f426e3a)|![image](https://github.com/user-attachments/assets/d032ee10-1995-4b69-a8a7-9a01cd7d241e)|![image](https://github.com/user-attachments/assets/9aebe3c4-770a-4ebb-832f-b788dc3b784a)|![image](https://github.com/user-attachments/assets/e0f353eb-81e2-4504-ad6b-43ffc43924ea)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.70.109 Chromium: 128.0.6613.138 (Official Build) beta (64-bit) 
Revision	fec4422ae56f4d9680c71a3c1de60b9a8e5ef32f
OS	Linux
```



1. Installed 1.70.109
2. launched Brave
3. relaunched Brave to pull in the griffin study (`BraveScreenFingerprintingBlockerStudy:Enabled`)
4. opened following link in a new tab 
5.   - https://maps.gsi.go.jp/index_3d.html?z=16&lat=35.653225&lon=139.73539700000003&pxsize=1024&ls=std#&cpx=61.296&cpy=-75.319&cpz=102.810&cux=0.375&cuy=0.210&cuz=0.902&ctx=0.000&cty=0.000&ctz=0.000&a=1.4&b=0&dd=0.
6. opened Shields panel > Advanced Controls
7. confirmed Block Fingerprinting` option shows integer `5`
8. clicked on the integer
9. confirmed toggle switches are visible (`canvas`, `font`, `screen`, `user agent`, `webgl`).
10. toggled `canvas` on 
11. toggled `font`  off
12. confirmed that the toggle list items don't disappear (they remain there)
13. stay on the toggle list menu and did a force-refresh (Command + Shift + R)
14. confirmed  the toggle-list items do disappear and then reappear as the page is loaded
15. opened example.com 
16. confirmed integer `1` is shown for `Block fingerprinting` option
17. clicked `1`
18. confirmed `font` toggle is shown enabled

step 7 | step 9 | step 12 | step 13 | step 15 | step 17 
----- | ------ | ----- | ------- | ------ | ------
![image](https://github.com/user-attachments/assets/cc788436-7b31-45c5-889c-d08eba6efb44)|![image](https://github.com/user-attachments/assets/ac4808c1-1055-4e9c-a0e3-e7fd67245df6)|![image](https://github.com/user-attachments/assets/6c2a93fa-2007-4e71-8ec1-efd5e8a7bf9e)|![image](https://github.com/user-attachments/assets/1e46a8cb-b9c4-471b-ac9e-c274245bdff2)|![image](https://github.com/user-attachments/assets/df168d05-35a6-4185-aa75-554add36cda7)|![image](https://github.com/user-attachments/assets/6db6e40f-7f6c-41c6-9e91-bebb20af35bf)
