### ISSUE TITLE
Can't Access Extension Keyboard Shortcuts

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#4024]
## Test plan
See https://github.com/brave/brave-core/pull/4796

## Description 
Updates to about:settings prevents users from having easy access to Extension Shortcuts. Users can still manually navigate there by visiting brave://extensions/shortcuts.

Reported by _Agent of User_ [on Twitter](https://twitter.com/agentofuser/status/1114089295286099968):

![image](https://user-images.githubusercontent.com/815158/55619852-2bcee600-575f-11e9-8b6e-fe0fee577262.png)

## Steps to Reproduce
1. Navigate to about:extensions
2. Click to view Extension shortcuts

## Actual result:
No link exists.

## Expected result:
Link should exist.

## Reproduces how often: 
100%

## Brave version (brave://version info)
0.65.16

### Reproducible on current release:
No. Reproducible on current Beta, Developer, and Nightly.

### Additional Information

![image](https://user-images.githubusercontent.com/815158/55619566-97648380-575e-11e9-9210-dce40ca18da4.png)

![image](https://user-images.githubusercontent.com/815158/55619545-8d428500-575e-11e9-921a-c6e9036e9da6.png)

**Comment by rebron** [comment]
Related: https://github.com/brave/brave-browser/issues/3771

**Comment by qnxor** [comment]
I came to create an issue about this. Not sure why this was removed. I'm very dependent on it, e.g. for invoking my global password manager. Do please bring it back :)

**Comment by agentofuser** [comment]
@qnxor yeah I miss it too. For now you can navigate directly to it by entering `brave://extensions/shortcuts` in the address bar.

**Comment by aleqx** [comment]
I wanted to chip in myself so +1

Thanks for pointing to brave://extensions/shortcuts - I wasn't aware.

However, there is at least one bug (i should report it separately I guess). I can't set `Ctrl+/` as a shortcut, whereas on Chrome I can.

**Comment by bsclifton** [comment]
Interesting- we may be unintentionally hiding this. Thanks for the heads up 😄

**Comment by jaminroe** [comment]
Glad someone else reported this. Was bugging the heck outta me! 😆 
@bsclifton did you discover if you were intentionally hiding this or not?

**Comment by Brave-Matt** [comment]
+1 https://community.brave.com/t/brave-has-removed-menu-shortcut-to-extension-keyboard-shortcuts-menu-give-it-back/56840?u=mattches

**Comment by Brave-Matt** [comment]
+1 https://community.brave.com/t/brave-has-removed-menu-shortcut-to-extension-keyboard-shortcuts-menu-give-it-back/56840/3?u=mattches

**Comment by Brave-Matt** [comment]
+1 https://community.brave.com/t/brave-has-removed-menu-shortcut-to-extension-keyboard-shortcuts-menu-give-it-back/56840/6?u=mattches

**Comment by rebron** [comment]
@jaminroe Unintentional. 

Can still manually get to it via: brave://extensions/shortcuts 
In interim we can probably get that link in there without having to do a full sidebar implementation. Possibly a link to Keyboard Shortcuts just under the "Find extensions and themes in the Web store" link.

**Comment by pauleil** [comment]
+1

**Comment by Annihilannic** [comment]
I thought I was going insane, can't even find it by searching Brave settings, eventually discovered the "power user" link on the QuickTabs settings page, but shouldn't have to find it that way.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.7.71 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4796
`brave://settings/extensions`
![image](https://user-images.githubusercontent.com/34715963/77530106-20edf380-6e91-11ea-92a4-d126e56bd574.png)
`brave://extensions/shortcuts`
![image](https://user-images.githubusercontent.com/34715963/77530562-d751d880-6e91-11ea-9f4e-ada0857b4e3c.png)
Verified assigning shortcut works
![image](https://user-images.githubusercontent.com/34715963/77530720-13853900-6e92-11ea-9ef3-2e16bd4fc8a4.png)
Verified shortcut works
