### ISSUE TITLE
`Add media from page` button is not shown in the Playlist sidepanel to match with Figma

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#40252]
### Description

Description
Found while testing https://github.com/brave/brave-browser/issues/32585. `Add media from page` button is not shown in the Playlist sidepanel to match with Figma

### Steps to reproduce

1. Install 1.70.44
2. launch/relaunch Brave
3. Add few videos to the Playlist 
4. verify `Add media from page` at the bottom of the Playlist sidepanel 

### Actual result

`Add media from page` button is not available

![2024-08-02_17h22_56](https://github.com/user-attachments/assets/fceccc05-e6dc-4aa7-9456-73c9f78e95e0)

### Expected result

![image](https://github.com/user-attachments/assets/26e2cba7-2ee4-4aea-b311-6d125487bc5e)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.70.44 Chromium: 127.0.6533.88 (Official Build) nightly (64-bit)
-- | --
Revision | c6e95da37b2d012afdca7bcc03a727e24cb2bb1c
OS | Windows 11 Version 23H2 (Build 22631.3958)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

@rebron @bsclifton @sangwoo108 
cc: @qa

**Comment by sangwoo108** [comment]
Maybe duplicated with https://github.com/brave/brave-browser/issues/40231 ?

**Comment by MadhaviSeelam** [comment]
Yep.. sorry missed it.  Closing as dup.
