### ISSUE TITLE
Update VPN panel UI

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#40253]
### Description

Update VPN panel UI to laster design - see https://www.figma.com/design/J4LKBMftiWhqromRWfUQLG/VPN-flows?node-id=1232-26888&t=VA5LnS8IjLWaCpwA-0

Note: from the laster UI, server list UI is excluded in this issue.
It'll be implemented via https://github.com/brave/brave-browser/issues/38186

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.99 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | 6751ea52a38e61ce5042efcc55d0d60d76c2266d
OS | Windows 11 Version 23H2 (Build 22631.4112)
```

1. Installed 1.70.99
2. launched Brave
3. clicked VPN button in the new tab
4. confirmed the VPN panel UI matches to Figma
5. opened `account.bravesoftware.com` in a new tab and authenticated with basic auth
6. purchased new VPN subscription `vpn40253@mailinator.com`
7. verified `credentials loaded!` subscription page shown as expected 
8. enabled VPN via VPN panel

Confirmed VPN panel match to figma for below states:
1. Onboarding UI
2. Enabled VPN panel
3. connected/disconnected VPN panel
4. settings menu & contact technical support form
5. select server
6. can't connect to server

**_Light theme_**

example | example | example | example | example | example | example | example | example
-------- | ------ | ------- | ------ | ------ | ----- | ------ | ----  | -----
![image](https://github.com/user-attachments/assets/a15cf700-f936-48b6-9a67-a78064ff0316)|![image](https://github.com/user-attachments/assets/685d139f-14fd-441b-bd15-3df9ef1b1dec)|![image](https://github.com/user-attachments/assets/c2b7eb8c-036c-4001-861a-297f0851b505)|![image](https://github.com/user-attachments/assets/0bc47ab0-ee9d-441a-abbb-27f522c69810)|![image](https://github.com/user-attachments/assets/e97df9ac-cc79-4531-a75a-dcdd300b7e5f)|![image](https://github.com/user-attachments/assets/7d6dce88-2712-4cb3-a441-c7a7f4771488)|![image](https://github.com/user-attachments/assets/a1ab768d-31ab-400e-b11c-ce819e02e484)|![image](https://github.com/user-attachments/assets/410b3dcf-08c2-4fd1-acf1-97b4438142bd)|![image](https://github.com/user-attachments/assets/d01f814e-1262-44be-89cf-fff6095b6fd3)

**_Dark theme_**

example | example | example | example | example | example | example
-------- | ------ | ------- | ------ | ------ | ----- | ------
![image](https://github.com/user-attachments/assets/f3d396d3-9bb7-4e61-8836-3be7b8c5e7bc)|![image](https://github.com/user-attachments/assets/d18c6383-096f-4513-ade4-04a580d0aade)|![image](https://github.com/user-attachments/assets/44ffdd4b-2379-4e2b-8ec3-55a9e8b42e8f)|![image](https://github.com/user-attachments/assets/3058718b-ec92-4098-b0af-83bca6b4c182)|![image](https://github.com/user-attachments/assets/38cbeb0d-06f4-41d6-8335-39c52c62fc7e)|![image](https://github.com/user-attachments/assets/f7b026a3-ab16-4430-b0e3-ecbb30709b56)|![image](https://github.com/user-attachments/assets/0ae61dbf-95bb-43ec-bb2b-0e4f16b69329)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` usin
```
Brave | 1.70.98 Chromium: 128.0.6613.114 (Official Build) beta (arm64)
-- | --
Revision | 1f10dba5feae5a0e907983a48d23571064fbd81e
OS | macOS Version 14.6.1 (Build 23G93)
```

Installed 1.70.98
launched Brave
clicked VPN button in the new tab
confirmed the VPN panel UI matches to Figma
opened account.bravesoftware.com in a new tab and authenticated with basic auth
purchased new VPN subscription vpn40253@mailinator.com
verified credentials loaded! subscription page shown as expected
enabled VPN via VPN panel
Confirmed VPN panel match to figma for below states:

Onboarding UI
connecting... state
connected/disconnected VPN panel
settings menu & contact technical support form
select server
can't connect to server



example | example | example | example | example | example | example | example | example
-- | -- | -- | -- | -- | -- | -- | -- | --
![Screenshot 2024-09-04 at 9 59 51 AM](https://github.com/user-attachments/assets/57b9d614-2a74-4727-8b43-3ad14af6d95b)
![Screenshot 2024-09-04 at 10 00 58 AM](https://github.com/user-attachments/assets/e0a7e50a-2c79-4877-ab8d-0df32e6be9b9)
![Screenshot 2024-09-04 at 9 59 44 AM](https://github.com/user-attachments/assets/8ad24bf7-3439-43de-97d9-fa2d9f9cf0f1)
![Screenshot 2024-09-04 at 10 00 31 AM](https://github.com/user-attachments/assets/3c8f74fa-7edc-4cf7-83d8-4c7ad35208b5)
![Screenshot 2024-09-04 at 10 01 44 AM](https://github.com/user-attachments/assets/a5c82bc1-a3db-46bf-8dfd-64e7bfd0bca9)
![Screenshot 2024-09-04 at 10 00 01 AM](https://github.com/user-attachments/assets/22aabebb-2f17-4fcd-9409-9cb9b6115129)
![Screenshot 2024-09-04 at 10 23 08 AM](https://github.com/user-attachments/assets/1039fb6f-2298-4b6a-8e63-fa89f2300f7b)
