### ISSUE TITLE
All publishers calls should go through ledger code

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#4025]
After additional check we have two more functions that involves publisher and are called directly from rewards service. All calls should go through ledger code.

1) `LoadPublisherInfo` https://github.com/brave/brave-core/blob/aa28d5e02521e03c0bed83b4237e039da7eb0343/components/brave_rewards/browser/rewards_service_impl.cc#L1121

2) `GetContentSiteList` https://github.com/brave/brave-core/blob/aa28d5e02521e03c0bed83b4237e039da7eb0343/components/brave_rewards/browser/rewards_service_impl.cc#L491

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.65.97 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2166
