### ISSUE TITLE
Brave Ads target URLs that redirect to a different hostname are not sustained

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#4026]
## Description 
Ad Target URLs that redirect to a different hostname are not sustained.

## Steps to Reproduce

   1. View an Ad which has a target URL which redirects to a different hostname

## Actual result:
Ad fails to confirm that it landed

## Expected result:
Ad should confirm that it has landed

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 0.63.31 Chromium: 73.0.3683.75 (Official Build) beta(64-bit)
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional Information
See `Default/rewards_service/confirmations.json` in the user profile directory and `chrome-debug.log` in the user profile directory for logs.

This is a known limitation, which also exists in Muon. A solution is to store the `uuid` (aka creative instance id) for the shown Ad as metadata for a tab and match the uuid instead of the hostname. This solution would also work for https://github.com/brave/brave-browser/issues/3570 (Clicking on Ad landing page gets them included in to a-c)

**Comment by helionmelion** [comment]
question: is this the same problem when trying to see wishlist from aliexpress? either disabling shields for this site or entering private mode, the navigation does not pass login verification. Shopping card works.

**Comment by LaurenWags** [comment]
Reproduced with

Brave | 0.63.45 Chromium: 74.0.3729.75 (Official Build) beta(64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Mac OS X

**Comment by LaurenWags** [comment]
When this is fixed, we should check https://github.com/brave/brave-browser/issues/5195 works for redirects.

**Comment by tmancey** [comment]
Closing issue as will be resolved by https://github.com/brave/brave-browser/issues/11012
