### ISSUE TITLE
[Omnibox]: Separator color looks wrong in light mode after latest Nala update

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#40269]
![Screenshot from 2024-08-05 17-52-37](https://github.com/user-attachments/assets/9bf20fde-ab3d-4892-b799-d96e2d8d8d93)

1. Enter a search result which shows an `Ask Leo` result in light mode
2. Observe the separator is too dark

Expected result:
The separator should be more subtle

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.70.51 Chromium: 127.0.6533.88 (Official Build) nightly (x86_64)
-- | --
Revision | c39ff5a89233f396d214b305233de91ff13a8b9e
OS | macOS Version 11.7.10 (Build 20G1427)
```

<img width="1644" alt="Screen Shot 2024-08-06 at 11 51 32 AM" src="https://github.com/user-attachments/assets/04180b29-dc02-4410-a1c2-7460a3d3e466">


First, reproduced using


Brave | 1.70.48 Chromium: 127.0.6533.88 (Official Build) nightly (x86_64)
-- | --
Revision | 30c6210e7c018e9aa66c1c463cafdee0ca535c31
OS | macOS Version 11.7.10 (Build 20G1427)


<img width="1644" alt="Screen Shot 2024-08-06 at 11 47 38 AM" src="https://github.com/user-attachments/assets/fcb8b451-b13a-4ec0-abc5-4fb67de1be36">
