### ISSUE TITLE
[ads] Periodically purge expired and orphaned state

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#40265]
We should also purge on browser launch after n time.

**Comment by btlechowski** [comment]
Verified using

Brave | 1.71.112 Chromium: 130.0.6723.44 (Official Build) (64-bit)
-- | --
Revision | 7d51df656b247f9432ee714a6d160142a1e11c13
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/25113

#### ad events - rewards

<details>

Verified removed after 3 months


</details>


#### ad events - non-rewards

<details>


Verified removed after 30 days


</details>

#### ad history

<details>


Verified removed after 3 months


</details>

#### conversions

<details>

Verified removed after the observation window

</details>

#### deposits

<details>

Verified removed after 7 days

</details>


#### transactions

<details>

Verified removed after 3 months

</details>
