### ISSUE TITLE
[Crash Report] Brave 1.68.134 crashes for sidepanel extensions on windows

### ISSUE THREAD

**Issue by A-Sam** [brave/brave-browser#40262]
## Test plan
1. Fresh profile
2. Install https://chromewebstore.google.com/detail/tab-tag-tree/lnlodalopnihdjkilbkpijndkddfoemc
3. Click the extension button and pin the extension to the top
4. Show Brave's sidebar if it's not already visible
5. Right click the Brave Talk and Brave Wallet icons and choose `Remove` on each
6. Close Brave
7. Re-open Brave
8. Click the extension action button

## Description
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.68.134 Chromium: 127.0.6533.88
Operating System: Windows NT 10.0.22631

URL (if applicable) where crash occurred: 
Any extension that uses sidepanel:
https://chromewebstore.google.com/detail/tab-tag-tree/lnlodalopnihdjkilbkpijndkddfoemc
https://chromewebstore.google.com/detail/copilot-sidebar-for-chrom/ncjedehfkpnliaafimjhdjjeggmfmlgf

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Install from above any extension that uses sidepanel
9. Open the extension (make sure sidepanel is allowed)
10. Brave crashes instantly

Reports:
dccd0d00-ea85-600c-0000-000000000000
d5cd0d00-ea85-600c-0000-000000000000

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/dccd0d00-ea85-600c-0000-000000000000

**Comment by A-Sam** [comment]
This might be related: https://github.com/brave/brave-browser/issues/31328

**Comment by fabivs** [comment]
I was able to find a workaround as described here:
https://github.com/brave/brave-browser/issues/39971

**Comment by A-Sam** [comment]
Hi @bsclifton, thanks for the suggestion. Yes it works now with Brave talk and wallet.

**Comment by bsclifton** [comment]
Confirmed this works as expected on Beta (1.69) and Nightly (1.70) and also confirmed it crashes on Release (1.68).

Will dig in some more and try to find the root cause! Thanks for reporting @A-Sam 😄

**Comment by bsclifton** [comment]
OK found that we fixed this already in Beta and Nightly with https://github.com/brave/brave-core/pull/24362

Will create an uplift for Release channel

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.68.140 Chromium: 127.0.6533.100 (Official Build) (64-bit)
-- | --
Revision | 612f5cee6491be373e8133bcda3f56522fbe621e
OS | Windows 10 Version 22H2 (Build 19045.4651)
```
Reproduced the issue on `1.68.137 Chromium: 127.0.6533.10` upgraded the profile to `1.68.140 Chromium: 127.0.6533.100` and ensured that click on the extension button doesn't crash the brave
![image](https://github.com/user-attachments/assets/7f8e1f0b-b72c-49f1-9e1f-1a3424a8d2dd)

**Comment by A-Sam** [comment]
Tested after the update and confirming the fix. Thanks @bsclifton @LaurenWags

**Comment by LaurenWags** [comment]
Appreciate the confirmation @A-Sam 👍🏻
