### ISSUE TITLE
Ads not blocked by Tetris site

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4027]
## Description 

Issue reported by user on community 
Ads not blocked by Tetris site

## Steps to Reproduce

   1. VIsit http://tetris.com/play-tetris
   2. Ads not blocked
   3. Try to focus on tetris and not on ads on the page

## Actual result:

Image credits to the user on community 
Brave+uBO+disabled shields
![brave](https://i.imgur.com/89bCSAf.png)
Chrome + uBO
![chrome](https://i.imgur.com/WD0oABs.png)

## Expected result:
Same as Chrome+uBO

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.62.50 Chromium: 73.0.3683.86 (Official Build) (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Original report https://community.brave.com/t/3rd-party-ad-blocking-extensions-not-working/51115
cc: @bbondy adding to webcompat board. please change if required

**Comment by rebron** [comment]
You can use right click on the image (use the Brave shields icon) and use the cosmetic filter to block those ads. It's a first party ad, that's why we're not blocking it via Shields which addresses 3rd party ads.

**Comment by JoelMon** [comment]
Like @rebron explained, they are first party ads.

![how to remove the images](https://imgur.com/068f0nZ)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/9062f0b

Will fix this, give 24-48hrs @srirambv  .

**Comment by ryanbr** [comment]
Everything working @srirambv ?

**Comment by srirambv** [comment]
Yes seems to be working fine. Closing as fixed
