### ISSUE TITLE
There's a momentary white splash screen on minimize/restore on Windows

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#40271]
### Description

Follow up for https://github.com/brave/brave-browser/issues/38214 to fix the white splash issue that happens when you minimize and then restore the window.

### Steps to reproduce

1. Open Brave window
2. Minimize the window
3. Restore the window

### Actual result

The window is restored and filled with white color. After few milliseconds the content appears.

https://github.com/user-attachments/assets/8ab68264-a64b-4897-9c14-8e1e30cddb79

### Expected result

The white splash does not appear.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave	1.70.30 Chromium: 127.0.6533.73 (Official Build) nightly (64-bit) 
Revision	252bfcfa10e3f2a7e92ee1be5b9e488ab43b7218
OS	Windows 11 Version 23H2 (Build 22631.3737)
```

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by MadhaviSeelam** [comment]
Verification PASSED using
```
Brave | 1.70.88 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 7431803bd1e909ef82982df42e2ea7aacbad755e
OS | Windows 11 Version 23H2 (Build 22631.4037)
```

Reproduced the issue in `1.70.30` 

https://github.com/user-attachments/assets/fb52300b-7a3c-4ffe-9141-389bfab3c610


Verified using the STR from https://github.com/brave/brave-browser/issues/40271#issue-2447806079

#### Confirmed white splash screen is not shown on minimize/restore on Windows 


https://github.com/user-attachments/assets/f5397d30-da0f-4aaf-918b-30c4bd775e26
