### ISSUE TITLE
Update info text on Shields

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#40279]
### Description

Update info text on Shields

### Steps to reproduce

1. Open Shields
2. Click on info button
3. Text shows "follow you across the web-tracking what you do"

### Actual result

"follow you across the web-tracking what you do"

### Expected result

Should be "follow you across the web, tracking what you do"

### Reproduces how often

Easily reproduced

### Brave version

All

### Device

- Brand/model: All
- Android version: All

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @samartnik

**Comment by ShivanKaul** [comment]
SGTM

**Comment by rmcfadden3** [comment]
SGTM as well

**Comment by deeppandya** [comment]
i have assigned this issue to myself. it's an easy change.

**Comment by kjozwiak** [comment]
The above requires `1.70.87` or higher for `1.70.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240726.010 release-keys
Brave build: 1.70.101
Chromium: 128.0.6613.120 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/40279#issue-2448961011
2. *Verify*

**ACTUAL RESULTS:**
- Verified that text in `Shields` says `follow you across the web, tracking what you do`

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/47b16a9f-623b-437f-84ef-de8046e2fc8a) | ![2](https://github.com/user-attachments/assets/a66f2c4e-b104-46a2-b786-c0c638367786) |
