### ISSUE TITLE
[Wallet] Core API Proxy is undefined when reporting user interaction interval

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#40289]
### Description

Brave wallet is not correctly reporting if the user has interacted during the lookup interval

### Steps to reproduce

1. Unlock wallet
2. do not interact or leave the page for ~1 minute

### Actual result

 error is logged to the console `Cannot read properties of undefined (reading 'proxy')`

### Expected result

No error should be logged to the console

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.49 Chromium: 127.0.6533.88 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.94 Chromium: 128.0.6613.114 (Official Build) beta (64-bit)
-- | --
Revision | 7ee7ec28264896bd8a9aff39cdb9432da38be028
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from issue description
- Verified no error when wallet is idle for more than 1minute of inactivity
