### ISSUE TITLE
New onboarding to UK users

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#40284]
### Description
Please roll out the new onboarding to UK users.

Spec: search for "Mobile Onboarding - Day 0 Focus (Q1 2024)"

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `iPhone 14` and `iPad Mini (6th gen)` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.7
- iPad Mni (6th gen) / iPadOS 18.0.1
Brave build: 1.71 (116)
BraveCore: 1.71.116 (130.0.6723.58)
```
OR

Filed follow-up issue #
---------------------------

**STEPS:**
1. Set device Language/Region to `en_UK`
2. Launch Brave 
3. Go through the onboarding flow

**ACTUAL RESULTS:**
- Verified that the new onboarding flow is shown for the United Kingdom.
- Verified that, for example, the US and Spain regions do not have the new onboarding flow.
- Verified that moving the slider on the first screen changes the haptic feedback.
- Verified that tapping `Continue` will advance to the next screen.
- Verified that tapping `X` in the first two screens will skip to the P3A screen.
- Verified that tapping `Learn more about our Privacy Preserving Product Analytics (P3A)` will launch the Brave support page.
- Verified that `Go To System Settings` will launch browser settings.
- Verified that onboarding is shown correctly in different aspect ratios/orientations.

`iPhone 14 / iOS 17.7`

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/d71188c8-7b85-48b3-b415-a86ea2f42a17) | ![2](https://github.com/user-attachments/assets/47ee3a1b-b714-44d9-a103-6a09accd988e) | ![3](https://github.com/user-attachments/assets/0ffd633e-948f-41c0-86f0-90a5ff4f87b1) | ![4](https://github.com/user-attachments/assets/bcea83ea-f573-48ed-ae94-8840bb7d7dfd) | ![5](https://github.com/user-attachments/assets/95dcecd3-d6c1-4dde-b9f9-804d43538643) |
| ![1](https://github.com/user-attachments/assets/b6bc2f0c-e1c4-42aa-8e74-a5ec690f7072) | ![2](https://github.com/user-attachments/assets/12083f04-7ab9-408b-b75e-ee66d8e10c6a) | ![3](https://github.com/user-attachments/assets/3a8af754-db22-415d-a439-e9a5f156e7db) | ![4](https://github.com/user-attachments/assets/c5724e09-982b-400c-b06c-7b9b1fec683d) | ![5](https://github.com/user-attachments/assets/0e4b0d98-df99-4763-a284-07d85ece3e04) |

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/a1ab44d4-0322-41e8-a1b4-4259cc5747f6) | ![2](https://github.com/user-attachments/assets/c00dd862-9879-42fd-9e71-5a7bf813e063) |

`iPad Mni (6th gen) / iPadOS 18.0.1`

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
