### ISSUE TITLE
PDF installer treated as pdf document

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#4028]
## Description 

Browser opens link of PDF Escape installer as a pdf instead jus to save it.

## Steps to Reproduce

   1. Use OS Windows. 
   2. Open https://www.pdfescape.com/windows/
   3. Press `Try Desktop`

## Actual result:

attempt to open pdf on address `chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/http://download-desktop.pdfescape.com/PDFescape_Desktop_Installer.exe`

## Expected result:
The installer is downloaded.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave	0.65.16 Chromium: 74.0.3729.40 (Official Build) nightly (64-bit) 
Revision	278d6a0d856d8314f36fb9a68b6e1d85cd0d14e7-refs/branch-heads/3729@{#470}
OS	Windows 10 OS Build 17134.648

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
yes, stable/beta/dev/nightly

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? No, Chrome does download

**Comment by rebron** [comment]
Closing. Duping to #3846
