### ISSUE TITLE
"Bring all tabs to this window" unexpectedly brings PWAs into the window as tabs

### ISSUE THREAD

**Issue by mdemoss** [brave/brave-browser#40287]
### Description

"Bring all tabs to this window" unexpectedly brings PWAs (portable web applications) into the window as tabs. This can't be easily undone except by re-launching the PWA.

### Steps to reproduce

1. Install a web application as a PWA
2. Launch PWA in its own window
3. Choose "Bring all tabs to this window" from the tab context window in another window.

### Actual result

PWAs move to the window as though they were tabs.

### Expected result

PWAs are expected to behave more like independent applications and shouldn't be pulled in as tabs in this way.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.134 Chromium: 127.0.6533.88 (Official Build) (64-bit) 

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Behavior seems the same on "real" PWAs and on ordinary web pages installed as PWAs.

**Comment by kjozwiak** [comment]
The above requires `1.69.137` or higher for `1.69.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.69.137 Chromium: 127.0.6533.100 (Official Build) beta (64-bit)
-- | --
Revision | 40b6ccbd1eb76c8f575e83de8ad81c4349d3f32a
OS | Windows 10 Version 22H2 (Build 19045.4717)
```

**Comment by JoshuaMacklin** [comment]
The previous unintended behavior maybe a quick way to implement a Firefox Multi-Account Container type feature. https://github.com/brave/brave-browser/issues/6346
