### ISSUE TITLE
Panel login UI update

### ISSUE THREAD

**Issue by kleantzogu** [brave/brave-browser#40296]
Visual update:
- Adding wallet logo on top
- Background color
- Space fixes

![Image](https://github.com/user-attachments/assets/84f7ca61-f340-4467-aa8e-9dfb490a97fb)

Figma link: https://www.figma.com/design/muVcmcu4RFNu0LkXe9VRDl/Wallet-2.0?node-id=18986-56935&t=EEOxmTRGskfvyte3-4

**Comment by kleantzogu** [comment]
Visual update:
- Adding wallet logo on top
- Background color
- Space fixes

![Image](https://github.com/user-attachments/assets/84f7ca61-f340-4467-aa8e-9dfb490a97fb)


Figma link: https://www.figma.com/design/muVcmcu4RFNu0LkXe9VRDl/Wallet-2.0?node-id=18986-56935&t=EEOxmTRGskfvyte3-4

**Comment by srirambv** [comment]
Verification passed on <html>
<body>

Brave | 1.72.82 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 4f0233b15f1896e28ff5ce439de1f658a2ef2df0
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from [brave/brave-core#25780](https://github.com/brave/brave-core/pull/25780)
- Verified panel has Brave band logo
- Verified panel has background colour

Light | Dark
-- | --
![Image](https://github.com/user-attachments/assets/21a3816e-ce9f-418f-bab2-b6371c5915d2) | ![Image](https://github.com/user-attachments/assets/963f7343-3743-40f9-a13f-cd33a008eb93)
