### ISSUE TITLE
[ads] Allow non-Rewards Android users to clear `Brave Ads data` from "Delete browsing data"

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#40290]
### Description

Brave Ads data clearing functionality for Desktop and iOS was added here: https://github.com/brave/brave-core/pull/24695

**Comment by btlechowski** [comment]
Verification passed on Brave v1.70.114 on Lenovo TB-8506FS (Android 11.0)

Verified test plan from https://github.com/brave/brave-core/pull/24695

#### non-rewards - search ad

<details>

Triggered search ad and verified served nor view events are not triggered
```

```

Clicked the ad
```

```

converted the ad
```

```

Verified `ad_events` and `creative_set_conversions` are not empty

![image](https://github.com/user-attachments/assets/68e76860-40b2-4121-af5e-d51ecaa6034a)|![image](https://github.com/user-attachments/assets/86109cea-d8ea-40a8-a382-d829bfb91484)
--|--

Clicked `Clear Brave Ads data...` link

![image](https://github.com/user-attachments/assets/ae89e215-50ca-4271-a30f-c4b4cc0674ab)|![image](https://github.com/user-attachments/assets/180ba8a0-faab-4deb-8c34-c72412cea19c)
--|--

Verified ads data was cleared:

![image](https://github.com/user-attachments/assets/f4c218dc-0d14-414f-b2b5-2fe5bb0bf892)|![image](https://github.com/user-attachments/assets/9f4192db-5d6d-44cd-8b1a-2f8ffa124c2d)|![image](https://github.com/user-attachments/assets/c6867f72-29d5-4413-b15e-17348026c68a)|![image](https://github.com/user-attachments/assets/886076fa-a6eb-42b1-b003-17b209c68e8b)
--|--|--|--

Verified `ads_service/client.json` and `ads_service/confirmations.json` are cleared

![image](https://github.com/user-attachments/assets/23aad008-740f-4508-bd2e-6f1495d0e2e0)|![image](https://github.com/user-attachments/assets/7325178d-9f9f-4688-8868-c87954107135)
--|--

</details>


#### rewards users

<details>

Verified after joining brave rewards, `Reset Brave Rewards data...` is shown

![image](https://github.com/user-attachments/assets/47146be7-ebb0-41eb-8754-7f5355196cac)


Verified clicking the link opens Reset Rewards


![image](https://github.com/user-attachments/assets/aee88c46-131e-4ac3-adc0-fbea6df6f90c)


Verified successful reset rewards



</details>
