### ISSUE TITLE
Improve quality of verified domain 3p checking

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#4029]
## Description 

Associate some domains with others for our shields 3p checking.

Example:
ksandbox.org and www.khanacademy.org

https://twitter.com/pamelafox/status/1114210142893953024

Currently checks are done via `SameDomainOrHost`

## Steps to Reproduce

   1. Go to https://www.khanacademy.org/computer-programming/new/pjs
   2. Type in some code
   3. Hit save

## Actual result:

Error happens because of device recognition blocking

## Expected result:

Should work

## Reproduces how often: 

Always

## Brave version (brave://version info)

All, tested on 0.64.36

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  yes
- Is the issue reproducible on the latest version of Chrome?  no

**Comment by fmarier** [comment]
That domain isn't in the Mozilla list I mentioned in #3194 so if we were to start with that list, we would likely need to fork it or supplement it with a Brave-specific list.
