### ISSUE TITLE
[Wallet] Input field values are not always immediately applied in Add token forms

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#40293]
### Description

In the add token and add NFT forms, the info lookups are delayed until the contract address value field is "blurred"

### Steps to reproduce

1. Go to the add NFT form
2. select a network and paste in a valid contract address and fill in a valid token id
3. change the contract address value

### Actual result

The NFT preview is not updated

### Expected result

The NFT preview should update

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.49 Chromium: 127.0.6533.88 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

https://github.com/user-attachments/assets/37348044-de6c-4e88-9ea0-52907bc11bef

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.94 Chromium: 128.0.6613.114 (Official Build) beta (64-bit)
-- | --
Revision | 7ee7ec28264896bd8a9aff39cdb9432da38be028
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from issue description
- Verified NFT preview is automatically updated when contract address is updated or changed 

https://github.com/user-attachments/assets/95396b4d-3057-4c59-9db8-2d16911efd86
