### ISSUE TITLE
about:adblock page with custom filter selection followup to #267

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#403]
## Description 
Create an about:adblock page followup to #267. Add a custom block filter section similar to muon build
![image](https://user-images.githubusercontent.com/17010094/47667583-bd1ca980-db7c-11e8-901a-d2921141e30b.png)

## Additional information
#267 
See also https://github.com/brave/brave-browser/issues/1931

**Comment by bsclifton** [comment]
Per https://github.com/brave/browser-laptop/issues/9711, the user should be able to specify a remote URL as the filter (instead of only adding entries themselves)

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/adblock-custom-filters/46208?u=eljuno

**Comment by tawissus** [comment]
Will it be available too in Brave for Android?

**Comment by srirambv** [comment]
Adding the issue to 0.64.x  as its a follow up to #403

Verification passed on 

Brave | 0.64.72 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Linux

**Comment by bridiver** [comment]
I don't think these settings were meant to be global, were they? I don't think that makes sense.

**Comment by bsclifton** [comment]
@bridiver what do you mean? Are these supposed to be applied on a per-site basis?

**Comment by sys9kdr** [comment]
Looks good. But I can't add remote URL as the filter https://github.com/brave/brave-browser/issues/403#issuecomment-425778061 yet. Should I open a new issue about external filter support?

> Per brave/browser-laptop#9711, the user should be able to specify a remote URL as the filter (instead of only adding entries themselves)

**Comment by bsclifton** [comment]
@sys9kdr please do

**Comment by ggiacomoo** [comment]
i'm on windows and updated,
i've copy/pasted rule from chrome's adBlock, to brave chrome://adblock/ Custom Filters
but it's doesn't works, where i'm wrong!?
