### ISSUE TITLE
[bug] the font display in vertical tabs is abnormal

### ISSUE THREAD

**Issue by jqtmviyu** [brave/brave-browser#40301]
### Description

![2024-08-06_21-45-50](https://github.com/user-attachments/assets/ee6fcd03-e02c-4af9-a024-46276ae66421)

### Steps to reproduce

1. install the last stable version 1.68.134
2. use vertical tabs

### Actual result

After a certain update, the display started to behave abnormally.

The incognito mode is experiencing the same issue.

However, the beta version displays normally.

I tried searching in the GitHub issues but couldn't find the same problem.

Resetting the settings and uninstalling the theme also resulted in the same situation.

### Expected result

The text should be displayed in its entirety.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Version 1.68.134 Chromium: 127.0.6533.88 (oficial Buid) (x86 _64)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Downgrade to `Version 167134 Chromium: 126.0.6478.186 (official Build) (x86_64)` to restore normal functionality.

**Comment by rebron** [comment]
@jqtmviyu Do you have any flags enabled on brave://flags

**Comment by jqtmviyu** [comment]
> @jqtmviyu Do you have any flags enabled on brave://flags

I inadvertently disabled the "Updated horizontal tabs design" setting at an unspecified time, which led to the issue in the new version. Reverting it to the default configuration resolved the problem.

I sincerely apologize for any inconvenience caused.
