### ISSUE TITLE
Leo webview scrolls up when keyboard pop ups

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#40303]
We shouldn't hide the content and show a blank page. We still have to scroll the page if there is a lot of text on it.

Steps to reproduce:
1. Open Leo
2. Tap on the input
3. See how content and header scroll out of view

https://github.com/user-attachments/assets/0544cdd0-c3fe-41f7-90a4-edef798db7b2

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240726.010 release-keys
Brave build: 1.70.94 
Chromium: 128.0.6613.114 (Official Build) beta (64-bit) 
```
Filed follow-up issue #40892, #40893
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/40303#issue-2451184140
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Leo's` title and upper control panel were not scrolled up when the on-screen keyboard was opened.

---------------------------

https://github.com/user-attachments/assets/88b43b6e-1eb1-4b70-8bd3-489598255008
