### ISSUE TITLE
Farbling broken on Lockdown Mode

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#40313]
### Description

Some of the APIs that are farblied are undefined on lockdown mode and this is not handled

### Steps to reproduce

1. Enable lockdown mode on the device (or for custom development builds you can just temporarily put `preferences.isLockdownModeEnabled = true` in the BVC Navigation delegate)
2. Go to any site. Ensure that fingerprint protection is on
3. Enable web inspector
4. Refresh the site 

### Actual result

Errors with `SpeechSynthesisUtterance` and `AudioBuffer` are shown

### Expected result

Should not show any errors related to the above APIs

### Reproduces how often

Easily reproduced

### Brave version

1.68

### Device/iOS version

Any

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
Some more context re: `Lockdown mode` via https://support.apple.com/en-ca/105120 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18` using version `1.70 (123)`

Test Steps: 

1. Enabled Developer Mode on Device (iOS 18)
2. Enabled Lockdown Mode in Settings -> Privacy and Security

Setup | Setup
---|---
![IMG_7614](https://github.com/user-attachments/assets/ef05c727-6cda-4687-815b-3e921969b339) | ![IMG_7615](https://github.com/user-attachments/assets/c5e1037a-8999-448f-8a59-991af9e626f2)
 
3. Installed Brave version 1.69.2
4. Opened a webpage
5. Used web inspector on Safari to inspect the webpage, filtered by errors
6. Confirmed `SpeechSynthesisUtterance` and `AudioBuffer` errors are displayed in console

 ![Screenshot 2024-10-03 at 5 19 59 PM](https://github.com/user-attachments/assets/71dd342c-88e2-4fc5-b273-9384c09171d7)

7. Upgraded to version 1.70 (123)
8. Reloaded the page, inspected using web inspector
9. Confirmed that errors are not shown with Lockdown mode enabled.

![Screenshot 2024-10-03 at 5 22 38 PM](https://github.com/user-attachments/assets/dce33c55-a296-459c-be69-207675689030)
