### ISSUE TITLE
[Brave News]: Feed is not loading in Android Nightly 1.70

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#40326]
1. Open Brave
2. Enable News
3. An error message pops up saying unable to load feed

https://bravesoftware.slack.com/archives/CU56GUJ1H/p1722894033946969

Issue found by @Brave-Matt

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240726.010 release-keys
Brave build: 1.70.94 
Chromium: 128.0.6613.114 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/40326#issue-2451814794
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Brave News` loads as expected when enabling it by tapping the `Show Brave News` CTA button or from the `Settings` > `Brave News`.

---------------------------

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/35c28e8c-5afe-4e14-b767-f454bc6ececa) | ![2](https://github.com/user-attachments/assets/8b7696ac-1a8c-41b0-a003-c1dfd8ce4d48) | ![3](https://github.com/user-attachments/assets/3733f500-6f35-4a9d-b4ad-8fe8ee5458f2) | ![4](https://github.com/user-attachments/assets/b40803d5-38b4-45a3-9ee1-15722b50f349) | ![5](https://github.com/user-attachments/assets/07ab831c-ae6b-4689-a3b4-b59d5e3c437d) |
