### ISSUE TITLE
Dark theme not applying on Linux

### ISSUE THREAD

**Issue by MulesGaming** [brave/brave-browser#40327]
### Description

Brave refuses to use dark theme on Linux. It happens with both "same as linux" and "dark". This only happens on the Beta version for some reason.

### Steps to reproduce

1. Download Brave Beta on Linux (it might only happen on gnome)
2. Go to `brave://settings/appearance`
3.  Set theme to dark

### Actual result

![image](https://github.com/user-attachments/assets/2e14cb2a-21d2-4fad-868e-ee2ab4ffcb00)

### Expected result

![image](https://github.com/user-attachments/assets/bf606501-135a-415e-a4e5-753935150135)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.136 Chromium: 127.0.6533.88 (Official Build) beta (64-bit) 
47255350e0d135b2172cb9dd2ba344d3d7fe4572
Linux

### Channel information

- [ ] release (stable)
- [X] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Using OpenSuse repo.

**Comment by rebron** [comment]
cc: @fallaciousreasoning @simonhong

**Comment by fallaciousreasoning** [comment]
Huh, that's super weird - I managed to repro this by clicking the `Use GTK` theme (but when I use classic, like you are it doesn't repro).

Could you have a play around with `Use GTK` and `Use Classic` to see if it reproduces @MulesGaming? Additionally, does it repro in a new profile?

**Comment by fallaciousreasoning** [comment]
@simonhong do you have any ideas about this?

**Comment by rebron** [comment]
@MulesGaming Are you still seeing this issue with our latest 1.73.89?

**Comment by MulesGaming** [comment]
Nope. I am able to properly apply dark theme as expected now!
