### ISSUE TITLE
Wallet: `BraveWalletTransactionType` enum string value 

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#40336]
currently, `BraveWalletTransactionType` is int value enum for iOS, which will make iOS display int value in tx confirmation detail. 
in order to support compressed NFT tx, it is better to display the `FUNCTION TYPE` in string instead of int indicating it is a compressed NFT transaction.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.107 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | ab3f504ca4a15c330f60a93d5e3773d780498980
OS | Windows 11 Version 23H2 (Build 22631.4169)

- Verified steps from [brave/brave-core#25034](https://github.com/brave/brave-core/pull/25034)
- Verified FUNCTION TYPE value in the "Details" tab is as expected 
Note: Unable to verify for Sol Sign transaction/Other and ERC1155

ERC20 Token Transfer | ERC721 Transfer NFT | ERC721 Safe Transfer | ERC20 Approve | Token Transfer | Forward FIL
-- | -- | -- | -- | -- | --
<img width="293" alt="ERC20 Token Transfer" src="https://github.com/user-attachments/assets/80888a6e-a282-46ce-ac82-7a15dc94a63b"> | <img width="293" alt="ERC721 Transfer NFT" src="https://github.com/user-attachments/assets/73bd47d4-091e-4b3b-b214-421c08c2bed2"> | <img width="293" alt="ERC721 Safe Transfer" src="https://github.com/user-attachments/assets/bde2cee2-293b-422c-af1b-c27a58d16142"> | <img width="293" alt="OHuHDCd4cf" src="https://github.com/user-attachments/assets/c538b25a-da0d-4ecc-aa1b-fcd46dc382db"> | <img width="293" alt="ERC20 Approve" src="https://github.com/user-attachments/assets/8cf65dee-300b-46c4-a247-dae8790b5ce6"> | <img width="293" alt="Forward FIL" src="https://github.com/user-attachments/assets/92f06738-f673-47d6-8101-870ea51be716">


SOL Sign and Send DApp | Send SOL | SOL Token Transfer | SOL Swap | SOL Associated Token | SOL Compressed NFT Transfer
-- | -- | -- | -- | -- | --
<img width="293" alt="SOL Sign and Send DApp" src="https://github.com/user-attachments/assets/00a8bb45-ca67-438b-89c2-ddf987f0d544"> | <img width="293" alt="Send SOL" src="https://github.com/user-attachments/assets/429b1aea-0ce0-4275-8b7a-2d7b446d1938"> | <img width="293" alt="SOL Token Transfer" src="https://github.com/user-attachments/assets/f5f77715-89bf-48da-8dd6-7121720ec323"> | <img width="293" alt="SOL Swap" src="https://github.com/user-attachments/assets/586c2136-90c5-4e9d-9dc0-bc840db35370"> | <img width="293" alt="SOL Associated Token" src="https://github.com/user-attachments/assets/d8287fdf-e170-4f7e-93c0-76be0db97ed7"> | <img width="293" alt="SOL Compressed NFT Transfer" src="https://github.com/user-attachments/assets/9093ce78-bc01-485e-be02-d8a5e23d76aa">

**Comment by nuo-xu** [comment]
reopen this issue since iOS needs front-end update as well

**Comment by kjozwiak** [comment]
> reopen this issue since iOS needs front-end update as well

@nuo-xu we usually never re-open issues that already landed into a target milestone. Mind creating a new issue for `iOS` which would be associated with https://github.com/brave/brave-core/pull/25624 and create the needed uplifts. I'll remove the `iOS` label for now as I'm assuming the above is for `Desktop` only and `iOS` requires https://github.com/brave/brave-core/pull/25624.
