### ISSUE TITLE
Material colors update - Updates needed

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#40339]
### Description

Work in progress Figma file with details
https://www.figma.com/design/cRYqYzDnZpLgFlwzSEj1mm/Material-color-update-Visual-QA?node-id=0-1

### Related Issues
Follow-up to https://github.com/brave/brave-browser/issues/39045

**Comment by aguscruiz** [comment]
This one is done

**Comment by rebron** [comment]
@aguscruiz Was there a PR that closed this one?

**Comment by aguscruiz** [comment]
Not sure which one it is, @fallaciousreasoning probably can tell

**Comment by aguscruiz** [comment]
One of them was this one
https://github.com/brave/brave-core/pull/26259
