### ISSUE TITLE
[Wallet] Skip Transaction simulation when swap safer-sign UI can be used

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#40343]
### Description

We should not attempt to simulate a transaction when the safer-sign UI can be used.

### Steps to reproduce

1. enable transaction simulations in brave://flags
2. create an EVM swap transaction from within the wallet UI

### Actual result

the simulated transaction UI is shown in the panel

### Expected result

the safer-sign UI should show instead of the simulated transaction UI in the panel

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.55 Chromium: 127.0.6533.100 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.87 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 065466241068c7503125be3432f8593f19dd7f15
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from issue description
- Verified Safe sign UI is shown for Swap transactions when transaction simulation 

https://github.com/user-attachments/assets/37a217f8-629d-40f3-9e64-f13496f00662
