### ISSUE TITLE
Upgrading to https not handling a serverside https downgrade

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#40346]
### Description

Sites such as http.badssl.com will downgrade https to http which will cause us try to upgrade multiple times before webkit spits out an error and an exception is added. This is not good because this will cause unnecessary redirects future problems (such as when using chromium web views) which may result in infinite redirect loops.

### Steps to reproduce

This is currently not reproducable until after we merge @kylehickinson 's PR: https://github.com/brave/brave-core/pull/24657

However we should do a sanity test on https upgrading anyways. You should make sure to test both http://http.badssl.com which does a https->http redirect and http://example.com which does not.

### Actual result

N/A

### Expected result

N/A

### Reproduces how often

No steps to reproduce

### Brave version

1.68

### Device/iOS version

Any

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `iPhone 14` and `iPad Mini (6th gen)` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.7
- iPad Mni (6th gen) / iPadOS 18
Brave build: 1.70 (123)
BraveCore: 1.70.123 (129.0.6668.89)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/40346#issue-2454189806
2. *Verify*

**ACTUAL RESULTS:**
- Verified that navigating to http://http.badssl.com/ downgrades `https` redirection to `http` and doesn't cause infinite redirect loops.
- Verified that navigating to http://example.com/ redirects to `https` and doesn't cause infinite redirect loops.
- Verified above with `Upgrade Connections to HTTPS` set to `Strict`, `Standard`, and `Disabled` settings.

---------------------------

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/c8987309-2452-4051-b826-199481ac8fa3) | ![2](https://github.com/user-attachments/assets/4b65ed37-bdae-4cad-94fd-3bed5fb356b6) | ![3](https://github.com/user-attachments/assets/e502d003-7a41-43db-8fc1-b0352ea5f670) | ![4](https://github.com/user-attachments/assets/ea82b353-b164-4216-aa46-57a5eadc23c4) | ![5](https://github.com/user-attachments/assets/d535072e-3ab2-4b85-bb65-59eb86d17291) |
| ![1](https://github.com/user-attachments/assets/3393b44e-7385-491a-a46a-cc14a4e068df) | ![2](https://github.com/user-attachments/assets/ce8c4cbc-9cf4-4d2f-b711-d495a3080337) | ![3](https://github.com/user-attachments/assets/fe042031-1b1e-4752-a381-ed7fc4b37cba) | ![4](https://github.com/user-attachments/assets/a402cd89-c4ac-4c2f-9963-1697d1aaa635) | ![5](https://github.com/user-attachments/assets/cbf20618-fe24-43a4-880c-60c3ffc12369) |
| ![1](https://github.com/user-attachments/assets/128640aa-f548-49bd-b597-984d405a3676) | ![2](https://github.com/user-attachments/assets/c8f1e855-8abf-432e-9d7a-9f464adaa392) | ![3](https://github.com/user-attachments/assets/2ad7bd25-45aa-421f-bdb0-18ca3ff95156) | ![4](https://github.com/user-attachments/assets/72a0f3d8-785d-41a3-88eb-a25970b4da6c) | ![5](https://github.com/user-attachments/assets/e180aec5-82eb-4d6c-82b3-bd86f4ef7790) |
