### ISSUE TITLE
`User is idle` is not fired on Wayland windowing system

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#40340]
### Description

System Notifications nor Custom Notifications are not shown on Wayland
On intel and amd gpu system, wayland is default.
On nvidia xorg is default.

### Steps to reproduce

1. Switch to Wayland
2. Trigger a notification ad

### Actual result

`User is idle` is not fired

### Expected result

`User is idle` is fired

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.68.137 Chromium: 127.0.6533.100 (Official Build) (64-bit)
-- | --
Revision | 2c62ca4f207eb8f02406936d1e5a4b226ddcfd3a
OS | Ubuntu 24

cc @tmancey @aseren @iambrianfung

**Comment by tmancey** [comment]
@btlechowski to enable Wayland support for Chromium, you'll need to include the command-line argument --ozone-platform=wayland for now.
