### ISSUE TITLE
[Wallet] To-address label in simulated transaction panel has white background in dark mode 

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#40342]
### Description

The "To address" label in simulated transaction panel has white background in dark mode. The background color should match the color of the container

### Steps to reproduce

1. Enable dark mode
2. Enable transaction simulations
3. create a "Send" transaction with a non-native token

### Actual result

![Screenshot 2024-08-07 at 19 45 18](https://github.com/user-attachments/assets/954b20ac-caf3-4cfb-8757-bb372485c4d9)

### Expected result

<img width="332" alt="Screenshot 2024-08-07 at 12 13 51 PM" src="https://github.com/user-attachments/assets/6e49afb9-9051-4284-b08c-185706b25f69">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.55 Chromium: 127.0.6533.100 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.87 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 065466241068c7503125be3432f8593f19dd7f15
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from issue description
- Verified To-Address label in simulated transaction panel is shown correctly in dark theme
- Encountered [#40664](https://github.com/brave/brave-browser/issues/40664)
<img width="1920" alt="brave_To4WHm5S9i" src="https://github.com/user-attachments/assets/172e368d-fdce-4144-9fa9-0f9f9f649fa7">
