### ISSUE TITLE
Brave news downloading data file even when disabled

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#40352]
### Description

`https://brave-today-cdn.brave.com/sources.global.json` is downloaded at startup even before Brave News is enabled

### Steps to reproduce

1. Create a new browser profile.
1. Run `mitmproxy --mode socks5 --listen-port 9000`
2. Start Brave with `--proxy-server="socks5://localhost:9000"`
3. Watch the network requests coming through.

### Actual result

![Screenshot from 2024-08-07 15-49-16](https://github.com/user-attachments/assets/0ac6da43-85a5-4f21-a58e-c69672cbb62a)

### Expected result

`https://brave-today-cdn.brave.com/sources.global.json` should only be downloaded if Brave News is enabled

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.0 Chromium: 127.0.6533.100 (Developer Build) (64-bit) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by fallaciousreasoning** [comment]
We've reenabled the upstream test which checks startup network activity, so if CI is green, this is working so I've marked this as QA/No
