### ISSUE TITLE
Polish Rewards settings panels

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#4035]
The Rewards panels in setting needs a little bit of alignment and simplification work. A few areas of note would be: 

1. The list item bullet style in the disabled panels should be removed. 
2. The typography variations can be simplified a bit. Especially the body copy. Should probably be made a little darker, bigger and given more space between lines. 
3. The amount of colors is making it a little hard to know what to concentrate on. This could be simplified down a bit. 
4. General alignment, justification and spacing consistency. In particular in the setting panels where we are setting an explicit max width and centering the content.
5. Should probably put the Brave Rewards title container in a white box with a drop shadow to match the other elements so it doesn't take on a disabled feeling being on the grey background. Could argue a change like that might resolve: https://github.com/brave/brave-browser/issues/3238

This is all a stepping stone to eventual design system rules and also making the page able to be responsively resized. 

Before and afters are below. 

![RewardsOn](https://user-images.githubusercontent.com/29072694/55656117-d6b8c180-57aa-11e9-9e4a-3f8aa6ef95ae.png)

![RewardsSettings](https://user-images.githubusercontent.com/29072694/55656160-ed5f1880-57aa-11e9-81ce-c4bda81bafd8.png)

![RewardsOff](https://user-images.githubusercontent.com/29072694/55656183-f223cc80-57aa-11e9-8c2a-9addd5b195e7.png)

**Comment by NejcZdovc** [comment]
<img width="416" alt="Screenshot 2019-04-06 at 7 48 15 AM" src="https://user-images.githubusercontent.com/9574457/55665469-796f4f80-5840-11e9-86f1-d5de1712a1d8.png">

This looks off to me

**Comment by rossmoody** [comment]
I think that’s a shoddy stitching photoshop job by me. I had to piece together screenshots. It’s ok on screen. You can see the bottom of “earnings” is cut too.

**Comment by kjozwiak** [comment]
@rossmoody mind quickly compiling a list or a few test cases of the specific area's that have been improved/polished? There's some screenshots available under https://github.com/brave/brave-browser/issues/4035#issue-429933948 and https://github.com/brave/brave-core/pull/2173 but I'm not 100% sure what changed.

Is the summary under https://github.com/brave/brave-browser/issues/4035#issue-429933948 pretty accurate? Should we be following that for verification? Thanks!

**Comment by rossmoody** [comment]
It was somewhat general low level CSS simplification and alignment but that screenshot above is definitely the most accurate. Both are real screenshots (not design mockups), left is before and right is an example of the PR built. 

If I had to itemize I would say
- alignment of panel size, padding, dropshadows, background color
- typography styles were generally simplified
- the settings options now span the whole width of the panel instead of max width center justified
- the settings icon is not to the left of the toggle instead of under it
- the grant notification spans the whole width of the column
- list item bullets were removed from the empty state descriptions next to the illustrations

**Comment by kjozwiak** [comment]
Thanks @rossmoody 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.66.88 Chromium: 75.0.3770.87 (Official Build) beta (64-bit)
-- | --
Revision | 9dc58a2353af60ab2b48bab98a25bc43ed59085d-refs/branch-heads/3770@{#982}
OS | Windows 7 Service Pack 1 (Build 7601.24465)

Used test plan from the description

![image](https://user-images.githubusercontent.com/34715963/59355278-047c3280-8d27-11e9-8116-6e7a4197e855.png)

![image](https://user-images.githubusercontent.com/34715963/59355443-42795680-8d27-11e9-9d68-ae66d87f6c52.png)

![image](https://user-images.githubusercontent.com/34715963/59355462-4c02be80-8d27-11e9-96c7-d79bd4f5f711.png)
