### ISSUE TITLE
Custom filter lists not downloading

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#40367]
### Description

Custom filter lists are not downloading

### Steps to reproduce

1. Add a new custom filter list

### Actual result

Stays pending

### Expected result

Should download

### Reproduces how often

Easily reproduced

### Brave version

1.70

### Device/iOS version

any

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

Also causes other issues:
1. Custom filter lists are not loaded
2. Not cleaning up old rule lists
3. Not downloading slim list

Should also do a sanity check for scriplets here: https://dev-pages.brave.software/filtering/scriptlets.html

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18` using version `1.70.123`

**Case: Add Custom Filter List:**

1. Started with new install
2. Opened `Content Filtering` page in settings
3. Enabled some additional filter lists in `Default Filter Lists`
4. Ensured that lists are successfully updated when tapping on `Update Lists`
5. Ensured the following custom filter list can be added and downloaded successfully by using `Add Filter By URL` option: `https://raw.githubusercontent.com/badmojr/1Hosts/master/mini/hosts.txt`
6. Ensured that ads are blocking on websites, pre-roll ads are blocked in videos

example | example | example
---|---|---
![Image](https://github.com/user-attachments/assets/330f302d-b5cc-4e21-9c36-21c1113d424d) | ![Image](https://github.com/user-attachments/assets/dfb5ea45-0d82-47b8-ae7d-f375ba3c1945) | ![Image](https://github.com/user-attachments/assets/ed43faee-ed18-4e51-8882-e27a6672d73f)

**Case: Scriplets Test Page**

1. Ensured all frames are showing as `true` for https://dev-pages.brave.software/filtering/scriptlets.html

![Image](https://github.com/user-attachments/assets/e3425f37-2821-4647-8df6-ef766385cf5f)
