### ISSUE TITLE
[Wallet] BraveWalletSolanaTxManagerProxy.solanaTxFeeEstimation returns 0 fee for compressed NFT transfer tx

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#40366]
Core (BraveWalletSolanaTxManagerProxy.solanaTxFeeEstimation) returns 0 fee for compressed NFT transfer tx after tx is submitted. 

Correct Fee Value | Wrong Fee Value
--- | ---
<img width="785" alt="Screenshot 2024-08-07 at 5 33 49 PM" src="https://github.com/user-attachments/assets/538fb83c-68f1-4fa9-9db0-3fcbbd1dea71"> | <img width="805" alt="Screenshot 2024-08-07 at 11 07 27 PM" src="https://github.com/user-attachments/assets/d8c00d3f-6b47-4a4f-b252-5f5a9aa9db1d">

**Comment by nuo-xu** [comment]
@nvonpentz @josheleonard

**Comment by nvonpentz** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/40562.  The issue here was that the blockhash was going stale when polling for fee estimations. We have a cached value on SolanaTxData.fee_estimation.  We can use that for now
