### ISSUE TITLE
[Wallet] some NFT balances are not fetched when "Enable Ankr Balances" is enabled

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#40368]
### Description

There currently is a bug in our token balance fetching logic that skips NFT balance lookups if the NFT's chain is supported by Ankr and the "[Enable Ankr balances](brave://flags/#brave-wallet-enable-ankr-balances)" flag is enabled. We should lookup NFT balances from SimpleHash regardless of the setting's value

### Steps to reproduce

1. Create a wallet that owns NFTs
2. Add an EVM and Solana NFT that you do not own to your tokens list
3. Enable brave://flags/#brave-wallet-enable-ankr-balances
4. clear all cached balances from local storage (`BRAVE_WALLET_TOKEN_BALANCES4` & `SPAM_TOKEN_BALANCES3`)
5. refresh the portfolio NFTs page 

### Actual result

The NFTs list may not be correctly filtered by selected accounts and "Hide not owned NFTs" filters in the portfolio filters
The "watch-only" label may be incorrectly displayed

### Expected result

The NFTs list should be correctly filtered by selected accounts and "Hide not owned NFTs" filters in the portfolio filters
The "watch-only" label should shown when appropriate

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.138 Chromium: 127.0.6533.100 (Official Build) beta (arm64) 

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.105 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | dd1f0aff786e2f4b694066ba8500616833591bf1
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from issue description
- Verified clearing `BRAVE_WALLET_TOKEN_BALANCES4` & `SPAM_TOKEN_BALANCES3` and enabling Ankr balance flag and restarting automatically fetches NFT balance correctly
- Verified `Watch only` label is correctly added to unowned NFTs
- Verified NFT balance shows correctly when Ankr balance flag is enabled

https://github.com/user-attachments/assets/16e070bd-a707-431a-a3bb-a83dc2032f22
