### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by dennismkerr** [brave/brave-browser#40371]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.68.137 Chromium: 127.0.6533.100
Operating System: Mac OS X 14.5.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Close the last open tab by clicking the X button on the tab.  
2. It does not happen consistently, but it happens frequently.  Additional reports:
    * 682b0400-15c1-690c-0000-000000000000
    * 0af80000-ebf9-720c-0000-000000000000
3. cmd+w can also cause this, but less frequently. 
    * c9b40400-ebf9-720c-0000-000000000000

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/25860400-15c1-690c-0000-000000000000

**Comment by davidgross** [comment]
This is affecting me as well, on both my ubuntu machines.
I'm running Ubuntu 22.04.4 LTS on both machines.

Brave Version: 1.68.137 Chromium: 127.0.6533.100
Operating System: Linux 6.5.0-45-generic

Crash ID: crash/b1600f00-15c1-690c-0000-000000000000

**Comment by dennismkerr** [comment]
This has not happened in a few weeks.
