### ISSUE TITLE
Build out new Transaction Status Panels

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#40373]
### Platforms

Linux, macOS, Windows

### Description

We need to build out the new `Transaction Status` panels from the latest `Figma` designs https://www.figma.com/design/26xCR66ZscSyVpTKrt85Hn/Transactions?node-id=730-325519&t=Ks4lAZLn4P5PXJFm-0

![Screenshot 61](https://github.com/user-attachments/assets/4b42e8f3-7d01-465e-9af3-d852396b410b)

![Screenshot 62](https://github.com/user-attachments/assets/f6e04f12-5df2-4df7-a593-3ddcf7915d15)

![Screenshot 63](https://github.com/user-attachments/assets/747cdce3-e974-4757-b988-507a3d275c34)

![Screenshot 64](https://github.com/user-attachments/assets/f363d89e-7d59-4fb9-9e64-6c93940cf640)

![Screenshot 65](https://github.com/user-attachments/assets/488bac3a-1cd2-45c4-9c48-d59c2c525a08)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.73.86 Chromium: 131.0.6778.39 (Official Build) (64-bit)
-- | --
Revision | 52163bcf4e40f27ddb76ffa79c90a8833084a9bd
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from [brave/brave-core#25470](https://github.com/brave/brave-core/pull/25470)
- Verified transaction panel shows new screen for Submitted/Complete/Cancelled


Send

![Image](https://github.com/user-attachments/assets/42a1ef3c-5262-49f0-8252-230469746642) | ![Image](https://github.com/user-attachments/assets/71e738a9-6b8b-474e-9971-b27069c52bdc) | ![Image](https://github.com/user-attachments/assets/6eb1a4b5-914e-4ad1-b317-0aad095c403c)
-- | -- | --

Swap

![Image](https://github.com/user-attachments/assets/180ee906-2f6c-4979-8a66-56a301ec62d5) | ![Image](https://github.com/user-attachments/assets/8fd0ca43-0f73-41a2-9992-5058dcdbbbec) | ![Image](https://github.com/user-attachments/assets/043ef9b9-6437-429e-88c2-a36df3b21ef2)
-- | -- | --

Bridge

![Image](https://github.com/user-attachments/assets/c732621e-d51e-44a7-b6a5-8f691f7d3443) | ![Image](https://github.com/user-attachments/assets/261ae688-5d9b-4e29-8d6b-08c02d788df6) | ![Image](https://github.com/user-attachments/assets/eecf9d2d-09e7-401e-abf0-2bac517a4f71)
-- | -- | --

ERC20 
![Image](https://github.com/user-attachments/assets/2b69ece2-8399-4227-a856-2bb993cea6c6) | ![Image](https://github.com/user-attachments/assets/72154e74-6b9b-4b14-b26b-ecc9356b0db9) | ![Image](https://github.com/user-attachments/assets/881b6330-0ae4-44d7-b1c4-f265d0bf8782)
-- | -- | --
