### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by meld-cp** [brave/brave-browser#40372]
Brave Version: 1.68.137 Chromium: 127.0.6533.100
Operating System: Windows NT 10.0.22631

URL (if applicable) where crash occurred:
https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. open the url (note it does not seem to crash in a private tab.  I have cleared site data, but normal tabs still crash)
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/07830400-15c1-690c-0000-000000000000

**Comment by rebron** [comment]
Closing as dupe of https://github.com/brave/brave-browser/issues/40356
