### ISSUE TITLE
Unknown error when trying to Bridge to Solana token

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#40380]
### Description

Unknown error when trying to Bridge to Solana token

### Steps to reproduce

1. Select Bridge
2. Use BNB->USDC on Solana
3. Enter amount
4. Fetches quote but then shows `Unkonwn error`

### Actual result

https://github.com/user-attachments/assets/8a5aa40c-4b9c-40c2-957b-6c24c0cbca91

### Expected result

No Error able to bridge

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.70.60 Chromium: 128.0.6613.18 (Official Build) nightly (64-bit)
-- | --
Revision | f110df81ade140122b1c2a8cf40f7d25ef15b1bc
OS | Linux

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @onyb

**Comment by kjozwiak** [comment]
The above requires `1.69.145` or higher for `1.69.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.145 Chromium: 128.0.6613.27 (Official Build) beta (64-bit)
-- | --
Revision | b029337c8485766fbc2dd25b11a46c88c8aaf2b4
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified LiFi quote for Solana bridge transaction works as expected
- Encountered [#40454](https://github.com/brave/brave-browser/issues/40454)

https://github.com/user-attachments/assets/d0844ae3-65cd-4995-87ea-6c4d4edd3168
