### ISSUE TITLE
various rewards screens/modals have incorrect coloring

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#40388]
### Description

On Nightly there are various rewards screens/modals with incorrect coloring - buttons, text, etc. Examples below but there could be others.

Confirmed with @Miyayes this coloring is not expected.

Not specific to C128 as this issue reproduces in non-C128 version of 1.70.x Nightly but is fine on 1.69.x Beta.

### Steps to reproduce

1. On Nightly click on BAT logo --> button/link coloring is incorrect
2. Click "Start using Rewards and pick a country --> button color is incorrect (maybe focus ring on country field too)
3. Click on "Continue" --> button/link coloring is incorrect
4. Connect a custodian
5. Visit a verified creator and open tip banner --> tip amount and button coloring is incorrect

Note for QA: when verifying, check both light and dark themes

### Actual result

Here's 1.70.x/Nightly (incorrect) side by side with 1.69.x/Beta (correct)

1.70.x | 1.69.x
--- | ---
<img width="1184" alt="nightly1" src="https://github.com/user-attachments/assets/3c96060c-6f76-45e6-864c-3d25ddffc816"> | <img width="1189" alt="beta1" src="https://github.com/user-attachments/assets/ce6cf7c6-a5b6-4b3e-a582-403ed95b3559">
<img width="1189" alt="nightly2" src="https://github.com/user-attachments/assets/9ef98e11-63ad-4d7a-983a-aea5582c050e"> | <img width="1188" alt="beta2" src="https://github.com/user-attachments/assets/778b095a-7473-4398-a698-e40a4c791ee3">
<img width="1184" alt="nightly3" src="https://github.com/user-attachments/assets/979f59b3-26a9-49e5-9229-dcd90678c5be"> | <img width="1185" alt="beta3" src="https://github.com/user-attachments/assets/c245945b-a4ab-4649-ad20-c21d63a80c01">
<img width="1184" alt="nightly4" src="https://github.com/user-attachments/assets/83fee74c-9507-455f-a05e-b4be4a9989b8"> | <img width="1189" alt="beta4" src="https://github.com/user-attachments/assets/d2c57ecd-ca91-4d20-9abf-59e909470a4b">

### Expected result

coloring should be like 1.69.x/Beta

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.x (both C127 and C128 versions)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @Miyayes

**Comment by Miyayes** [comment]
@aguscruiz Is this Nala?

**Comment by aguscruiz** [comment]
Yeah, seems like the button on those screenshots is not a Nala button and that's why it's breaking (see how it's rounded and Nala's are squircles). If the button is updated to a Nala button that should be fixed.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.70.88 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 7431803bd1e909ef82982df42e2ea7aacbad755e
OS | Windows 10 Version 22H2 (Build 19045.4780)

```

1.70.x | 1.69.x
--- | ---
![image](https://github.com/user-attachments/assets/08585d54-c7f8-4c5c-8d1f-af5ed5d6ffae) | ![image](https://github.com/user-attachments/assets/c72f7cd2-3213-4ccd-98e6-578751b6e42e)
![image](https://github.com/user-attachments/assets/b33a8506-70b9-4fa5-97e7-c9fc9f3906a7) | ![image](https://github.com/user-attachments/assets/e71f9857-6390-46d0-adc6-66067c3d6701)
![image](https://github.com/user-attachments/assets/feab5e88-acd7-4fba-b558-7b2dd41177ec) | ![image](https://github.com/user-attachments/assets/74cece7d-86f6-4b1d-bbf0-7b8aca107143)
![image](https://github.com/user-attachments/assets/4af74878-bccd-4cf1-b95c-0df0949abfa3) | ![image](https://github.com/user-attachments/assets/9ee2e91b-1dce-48db-816b-166e4344d3ba)
