### ISSUE TITLE
[cr128] Cast menu should move back to "Save and share" submenu

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#40387]
### Description

We moved `Cast...` menu item to under `More tools`, however, it's better to have it match upstream and move it "Save and share" (upstream's "Cast, save, and share") submenu (per conversation with @rebron).

### Steps to reproduce

1. Open Brave
2. Navigate to brave://settings/extensions
3. Turn on Media Router and click Relaunch
4. Open ☰

### Actual result

5. Observe: "Cast, save, and share" menu item in the menu
6. Hover on menu to expand
7. Observe: "Cast" title with no menu items under it.
8. Back in the main ☰ menu, click on "More tools"
9. Observe "Cast..." item

### Expected result

1. No "Cast..." item under "More tools"
2. "Cast..." item under "Cast, save, and share"
3. "Cast, save, and share" is named "Save and share"

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.61 Chromium: 128.0.6613.18 (Official Build) nightly (64-bit) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.69.145` or higher for `1.69.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.69.146 Chromium: 128.0.6613.27 (Official Build) (64-bit)
-- | --
Revision | 3bd0f984ce99277bd556cac8dd198aba4467a22f
OS | Windows 10 Version 22H2 (Build 19045.4780)
```
