### ISSUE TITLE
Connect button is shown when click region in brave vpn server selection panel

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#40398]
### Description

Below connection button should be shown only hovered in region box
<img width="400" alt="image" src="https://github.com/user-attachments/assets/cc99bb28-5380-42df-98b1-24666859684f">

but if clicks that region area connect button is still shown after mouse goes out.

### Steps to reproduce

1. go to server selection vpn panel
2. click any region
3. move mouse over to another region
4. 

### Actual result

Connect button is shown in the clicked region

### Expected result

Connect button should be hidden after goes out from that clicked region

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.61 Chromium: 128.0.6613.18 (Official Build) nightly (x86_64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by simonhong** [comment]
fixing now.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.99 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | 6751ea52a38e61ce5042efcc55d0d60d76c2266d
OS | Windows 11 Version 23H2 (Build 22631.4112)
```

1. Installed 1.70.99
2. launched Brave
3. opened account.bravesoftware.com in a new tab and authenticated with basic auth
4. logged in with existing subscription vpn40253@mailinator.com
5. verified credentials loaded! subscription page shown as expected
6. enabled VPN via VPN panel
7. opened server selection panel

#### Confirmed `Connect` button only shown when hovered over in the server selection panel

Not hovered | hovered
---- | ----
![image](https://github.com/user-attachments/assets/27cadff6-2580-47f9-a779-773e2f002124)|![image](https://github.com/user-attachments/assets/4b9336ba-73ed-4cda-a5f4-f99364d2272d)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.98 Chromium: 128.0.6613.114 (Official Build) beta (arm64)
-- | --
Revision | 1f10dba5feae5a0e907983a48d23571064fbd81e
OS | macOS Version 14.6.1 (Build 23G93)
```

1. Installed 1.70.99
2. launched Brave
3. opened account.bravesoftware.com in a new tab and authenticated with basic auth
4. logged in with existing subscription [vpn40253@mailinator.com](mailto:vpn40253@mailinator.com)
5. verified credentials loaded! subscription page shown as expected
6. enabled VPN via VPN panel
7. opened server selection panel

#### Confirmed Connect button only shown when hovered over in the server selection panel

Not hovered over | hovered over 
------- | ----
![Screenshot at Sep 04 16-09-16](https://github.com/user-attachments/assets/fea156ac-77ee-4f07-a88d-2c243fef3e53)|![Screenshot at Sep 04 16-10-21](https://github.com/user-attachments/assets/0a47b935-8c24-424a-bf54-f19f400ead1e)
