### ISSUE TITLE
Brave browser crashes when using the "Show all Bookmarks" menu.

### ISSUE THREAD

**Issue by nerfnet** [brave/brave-browser#40397]
### Description

When using bookmarks through the "Show all Bookmarks" menu, Brave browser crashes and throws an "Illegal instruction exception":

(1e08.1dac): Illegal instruction - code c000001d (first chance)
chrome!IsSandboxedProcess+0x1c67c9:
00007ffc`9e7623c9 0f0b            ud2

This does not seem to occur when using a private window. I have included a video for more clarity.

### Steps to reproduce

1. Open the Brave menu in the top right.
2. Open Bookmarks and Lists > Show all bookmarks
3. Play around with bookmarks by folders and bookmarks themself.

https://github.com/user-attachments/assets/3eba685e-e393-46bf-b1c6-07795a67d9da

### Actual result

Brave crashes.

### Expected result

It shouldn't crash.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave: 1.68.137 Chromium: 127.0.6533.100 (Official Build) (64-bit) 
Revision: 2c62ca4f207eb8f02406936d1e5a4b226ddcfd3a
OS: Windows 11 Version 21H2 (Build 22000.318)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by iefremov** [comment]
@nerfnet can you please try to update the browser and reproduce? If reproduced, pls share a crash id from brave://crashes, thanks
