### ISSUE TITLE
[C128] After clicking on the sidebar settings menu, the settings selected icon is not shown

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#40401]
### Description

After clicking on the sidebar settings menu, the settings selected icon is not shown

### Steps to reproduce

1. Clean profile `1.70.65`
2. Open brave://settings
3. Click on the sidebar settings menus

### Actual result

After clicking on the sidebar settings menu, the settings selected icon is not shown
![image](https://github.com/user-attachments/assets/1f5d58c1-64e7-4ce7-b8aa-2294ae12c17c)

### Expected result

After clicking on the sidebar settings menu, the settings selected icon should be shown

![image](https://github.com/user-attachments/assets/effd0605-381e-4cf1-9005-b49405707aa6)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.70.65 Chromium: 128.0.6613.27 (Official Build) nightly (64-bit)
-- | --
Revision | 8bf2d6fd36dc289a5918c6c06969c161d81717dc
OS | Windows 10 Version 22H2 (Build 19045.4651)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @mkarolin @brave/qa-team @rebron

**Comment by GeetaSarvadnya** [comment]
The issue is not reproducible on CR127 nightly build `1.70.22 - CR127`

**Comment by kjozwiak** [comment]
The above requires `1.69.145` or higher for `1.69.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.69.146 Chromium: 128.0.6613.27 (Official Build) (64-bit)
-- | --
Revision | 3bd0f984ce99277bd556cac8dd198aba4467a22f
OS | Windows 10 Version 22H2 (Build 19045.4780)
```
- After clicking on the sidebar settings menu, the settings selected icon is shown
![image](https://github.com/user-attachments/assets/0dd48311-36d1-403a-92b1-b43fc5fc25b3)
