### ISSUE TITLE
Leo Toolbar option in Settings

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#40403]
As a follow up to https://github.com/brave/brave-browser/issues/39713, add an option to enable and disable Leo in the toolbar via the Toolbar Settings in brave://settings/appearance: `Show Leo button`

**Comment by kjozwiak** [comment]
The above requires `1.69.147` or higher for `1.69.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.69.147 Chromium: 128.0.6613.40 (Official Build) (64-bit)
-- | --
Revision | d29b1747d0f906239936b0d94c40889920ebf2c0
OS | Windows 10 Version 22H2 (Build 19045.4780)
```
Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/40403#issue-2460838836 & https://github.com/brave/brave-core/pull/25100#issue-2462314589, ensured that you can enable/disable the `Leo AI` toolbar button via `brave://settings/appearance` as per the following:
![Leo enable or disable via preferences](https://github.com/user-attachments/assets/73b1ca78-fcd6-43f8-a448-b0d79bbc7d41)
