### ISSUE TITLE
Remove ddg banner promotion type A & B

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#40400]
### Description

We added four types of banner via https://github.com/brave/brave-core/pull/24057
Delete type A and B and use only C and D types for promotion.

### Steps to reproduce

1. Launch brave with --enable-features=BraveSearchOmniboxDDGBanner
2. Set DDG as a default search provider
3. Type anything in omnibox and check DDG promotion entry is shown at last
4. Wait 1 min at least to see another DDG promotion
5. type anything and check different DDG promotion is visible
6. Repeat 4-5 several times to see 2 types(C or D) of promotion is shown

### Actual result

We can see four types of banners.

### Expected result

We can see two types of banners.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

`1.69.x`

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @brave/qa-team

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.88 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 7431803bd1e909ef82982df42e2ea7aacbad755e
OS | Windows 11 Version 23H2 (Build 22631.4037)
```

1. Launch brave with --enable-features=BraveSearchOmniboxDDGBanner
2. Set DDG as a default search provider in brave://settings/search
3. Type anything in omnibox and check DDG promotion entry is shown at last
4. Wait 1 min at least to see another DDG promotion
5. type anything and check different DDG promotion is visible
6. Repeat 4-5 several times to see 2 types(C or D) of promotion is shown

Confirmed C & D banners are shown and matched to the screenshots from https://github.com/brave/brave-core/pull/24057#issue-2339361690 

step 1 | step 2 | step 3 | step 5 | step 3 - dark | step 5 - dark
----- | ----- | ----- | ----- | ----- | ------
![image](https://github.com/user-attachments/assets/45c5f819-b0b9-4200-8b66-055be54279c7)|![image](https://github.com/user-attachments/assets/32e7c241-7b9b-4a3c-bd01-ebc791e1cd20)|![image](https://github.com/user-attachments/assets/f7d4aae1-6874-4d99-82af-7793ca655c80)|![image](https://github.com/user-attachments/assets/034aa280-470f-4294-bf57-e5045f8bfdd3)|![image](https://github.com/user-attachments/assets/cf3080fe-3b4d-4fa3-8438-ce1f5d7ff377)|![image](https://github.com/user-attachments/assets/82298414-f046-428c-b748-d14b66913bd3)|
