### ISSUE TITLE
Extend LiFi swap support to other EVM chains

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#40407]
### Description

Currently we only support LiFi for the chains that are already supported by 0x API. We need to extend this support to other EVM networks.

### Steps to reproduce

1. Make sure Gnosis chain is added to visible networks
2. Go to Swap

### Actual result

Gnosis chain is not visible in the network dropdown of token selection modal.

### Expected result

Gnosis chain should be visible in the network dropdown of token selection modal. User should be able to fetch a valid quote, create a transaction, and confirm it on the network. Ensure that the SafeSign screen for the swap is rendered correctly.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.x

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.69.146` or higher for `1.69.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.69.147 Chromium: 128.0.6613.40 (Official Build) (64-bit)
-- | --
Revision | d29b1747d0f906239936b0d94c40889920ebf2c0
OS | Windows 11 Version 23H2 (Build 22631.4037)


- Verified steps from issue description
- Verified Gnosis is supported in Bridge 
- Verified Gnosis bridge successfully provides quotes 

https://github.com/user-attachments/assets/2a7a9895-fa90-4e06-b6b1-257794f3a71b
