### ISSUE TITLE
Wrong tooltip, context menu item text of leo toolbar button

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#40402]
### Description

* Wrong text of toolbar button
<img width="198" alt="Screenshot 2024-08-12 at 7 34 08 PM" src="https://github.com/user-attachments/assets/3b897bfc-3c46-4ee3-84de-68fe8de85042">
<img width="226" alt="Screenshot 2024-08-12 at 7 34 16 PM" src="https://github.com/user-attachments/assets/5734f177-45ed-4267-a12d-cb3594d52e61">

### Steps to reproduce

1. Move mouse over leo toolbar button
2. Launch context menu of leo toolbar button
3. 

### Actual result

See the image in the issue description

### Expected result

It should be `Leo` instead of sidebar

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.61 Chromium: 128.0.6613.18 (Official Build) nightly (x86_64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @brave/qa-team

**Comment by simonhong** [comment]
@rebron maybe tooltip could be `Toggle Leo panel` as this button doesn't have state?
and context menu text could be `Hide Leo icon`?

**Comment by rebron** [comment]
We could just label it `Leo` just like the sidebar icon and how we show a product label for Wallet and VPN.

Alternatively it could be `Show Leo panel`

**Comment by kjozwiak** [comment]
The above requires `1.69.147` or higher for `1.69.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.69.147 Chromium: 128.0.6613.40 (Official Build) (64-bit)
-- | --
Revision | d29b1747d0f906239936b0d94c40889920ebf2c0
OS | Windows 10 Version 22H2 (Build 19045.4780)
```
Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/25097#issue-2462208211 & https://github.com/brave/brave-browser/issues/40402#issue-2460746489, ensured that `Brave` is using the correct `tooltip` & `context menu` text as per the following:

**`Example`** | **`Example`**
---------------|-----------------
![image](https://github.com/user-attachments/assets/30c272c1-96e8-4b57-a549-2b21fae6e423) | ![image](https://github.com/user-attachments/assets/34403d0b-b446-40f2-bde7-bc42afd10650)
