### ISSUE TITLE
Rename `Improve search suggestions` to `Show search suggestions`

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#40413]
### Description

Use `Show search suggestions` to make it more explicit

### Steps to reproduce

1. Go to brave://settings/search
2. 
3. 

### Actual result

`Improve search suggestions`

### Expected result

`Show search suggestions`

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

All versions

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron

**Comment by kjozwiak** [comment]
The above requires `1.70.103` or higher for `1.70.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.70.108 Chromium: 128.0.6613.120 (Official Build) beta (x86_64)
-- | --
Revision | 3624a617c5c520e5a5ce8d5bfdfb7d0a6a696e6a
OS | macOS Version 13.6.9 (Build 22G830)
```
