### ISSUE TITLE
Prevent search suggestions from displaying when copy/pasting into the omnibar.

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#40415]
### Description

This reduces the chances of sending queries to the server that may be a username/password
This issue is prerequsite before enabling search suggestions by default (https://github.com/brave/brave-browser/issues/29517)

### Steps to reproduce

1. Enable search suggestions in brave://settings/search
2. Paste to omnibox and check search suggestions are not displayed

### Actual result

displayed

### Expected result

No search suggestions

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

all versions

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron

**Comment by simonhong** [comment]
Hmm, how to know current input in omnibox is from `ctrl-v` or just typing?

**Comment by simonhong** [comment]
Should we stop search suggestion when clipboard has text and it's same with omnibox input?

**Comment by kjozwiak** [comment]
The above requires `1.70.103` or higher for `1.70.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.70.108 Chromium: 128.0.6613.120 (Official Build) beta (x86_64)
-- | --
Revision | 3624a617c5c520e5a5ce8d5bfdfb7d0a6a696e6a
OS | macOS Version 13.6.9 (Build 22G830)
```
