### ISSUE TITLE
Fail to create non-compressed Solana NFT send transaction

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#40424]
### Description

Attempting to send any non-compressed Solana NFT fails to create the send transaction

### Steps to reproduce

1. Attempt to send any non-compressed Solana NFT
2. Shows error message in send screen, does not create transaction

### Actual result

<img src="https://github.com/user-attachments/assets/ade9c391-4f23-4797-b7d3-e0be74a1aae3" width="300">

### Expected result

Send transaction is created

### Reproduces how often

Easily reproduced

### Brave version

v1.70

### Device/iOS version

Any

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

Encountered while testing https://github.com/brave/brave-core/pull/25051
cc @nuo-xu @srirambv

**Comment by nvonpentz** [comment]
Resolved in https://github.com/brave/brave-core/pull/25154#top
