### ISSUE TITLE
[Wallet] Use Nala component for segmented control

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#40426]
### Description

Subtask of https://github.com/brave/brave-browser/issues/39221

### Steps to reproduce

1. View portfolio overview page
2. ensure the NFT tab is enabled
3. click a segmented control item (Assets/NFTs)

repeat for
- accounts details page
- visible assets modal
- explore web 3 page
- asset details page

### Actual result

Navigation occurs without any animations

### Expected result

The segmented control should animate when changing the selection

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.68.134 Chromium: 127.0.6533.88 (Official Build) (arm64) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.87 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 065466241068c7503125be3432f8593f19dd7f15
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from issue description
- Verified segmented controls has subtle animation upon selection
- Verified on Portfolio, Asset details, Account Details and Market Explore screens

https://github.com/user-attachments/assets/d1f80d26-ecc5-43dd-bb7f-5d2a36c3df5f
