### ISSUE TITLE
Ads Rewards Grants: Expiry date change

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#4042]
Any grants received via the server that below to Ads Rewards should have no expiry date.

When the grants show up;
a) they should show up as grants (no change)
b) but no expiry date should be displayed (the ask)

These grants will be signed for a really long period of time; but for the moment the BR wallet should not show the grants timetable.

Existing grants, that are not ads rewards, will continue to work the same.

@NejcZdovc

**Comment by mandar-brave** [comment]
@rebron needs uplift for 0.63 to ensure there is no confusion at the user end. Very minor change.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.45 Chromium: 74.0.3729.75 (Official Build) beta(64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2182
* Verified UGP grants still display expiration date on "It's your lucky day" screen from both panel and brave://rewards. Also, expiration date is displayed in 'Grants' list on both panel and brave://rewards.
* Ad grants did not display expiration date on "It's your lucky day" screen, but do display expiration date in 'Grants' list from panel and brave://rewards page. Logged follow up issue https://github.com/brave/brave-browser/issues/4169
