### ISSUE TITLE
CR128 - New tab separator line is white in color instead of gray

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#40425]
### Description

CR128 - New tab separator line is white in color instead of gray.

The issue is not reproducible in non CR128 builds `1.70.22 Chromium 127.0.6533.73`

### Steps to reproduce

1. NA

### Actual result

New tab separator line is white in color instead of gray
![image](https://github.com/user-attachments/assets/7c7a339c-84b0-4d3b-b451-814accb6f9ed)

### Expected result

![image](https://github.com/user-attachments/assets/c93345b7-1003-4800-ade7-5fcb6fc8c043)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.70.66 Chromium: 128.0.6613.27 (Official Build) nightly (64-bit)
-- | --
Revision | 667a3d64bcaa33f50347e567971f37eeb76758aa
OS | Windows 10 Version 22H2 (Build 19045.4651)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @mkarolin @rebron

**Comment by kjozwiak** [comment]
The above requires `1.69.147` or higher for `1.69.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.69.147 Chromium: 128.0.6613.40 (Official Build) (64-bit)
-- | --
Revision | d29b1747d0f906239936b0d94c40889920ebf2c0
OS | Windows 10 Version 22H2 (Build 19045.4780)
```
- Confirmed that the New tab separator line is gray in color as expected.

**Regular window**

Light theme | Dark theme
--------------|----------
![image](https://github.com/user-attachments/assets/6220d394-ba62-43a2-9293-20efcbdea90f) | ![image](https://github.com/user-attachments/assets/326a1144-423c-4a4c-afc0-7506997b2c77)
