### ISSUE TITLE
Add to playlist modal doesn't show the media info

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#40421]
### Description

Add to playlist modal doesn't show the media info

### Steps to reproduce

1. Open any YT video
2. Click on the Add to  Playlist video button
3. No media details is shown in popup bubble

### Actual result

![image](https://github.com/user-attachments/assets/ee74026c-072f-43f0-810e-f15c04efc8ee)

### Expected result

Show media info in the add to playlist bubble

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.70.66 Chromium: 128.0.6613.27 (Official Build) nightly (64-bit)
-- | --
Revision | 667a3d64bcaa33f50347e567971f37eeb76758aa
OS | Windows 11 Version 23H2 (Build 22631.3880)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @sangwoo108 @rebron @brave/qa-team

**Comment by LaurenWags** [comment]
Requires `1.70.100` or higher for testing 👍🏻

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.100 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | c30694e8a60583be9d1784e4d42b4a0b94c70ab5
OS | Windows 11 Version 23H2 (Build 22631.4112)
```

1. Installed 1.70.100
2. launched Brave
3. enabled playlist via brave://flags/#playlist
4. opened a YT video (eg. https://www.youtube.com/watch?v=dmd7h5p2cp8)
5. clicked Playlist button in the URL bar
6. clicked Add selected button

#### Confirmed Add to Playlist bubble is shown with the video details (favicon & video title) as expected
#### Confirmed media added to Playlist in the panel

example | example 
----- | -----
![image](https://github.com/user-attachments/assets/5d4e66d2-b12d-4f35-b003-654c36d0aedd)|![image](https://github.com/user-attachments/assets/5c0baf6c-82fa-4598-bf85-ae4c523eff58)
