### ISSUE TITLE
[Wallet/iOS] Tx confirmation/ tx parsing updates once compressed NFT tx has token information 

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#40433]
once https://github.com/brave/brave-browser/issues/40353 is resolved. Front-end should be able to get token in formation for tx type `solanaCompressedNftTransfer` some UI updates are needed.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.2 running 1.73 (94)
- Verified steps from [brave/brave-core#25561](https://github.com/brave/brave-core/pull/25561)
- Verified able to send Compressed NFT from one account to another
- Verified transaction details is show NFT details

https://github.com/user-attachments/assets/ae2426b9-0bd9-43a5-8b3d-f678591b2611
