### ISSUE TITLE
Verified sites need a different BAT logo

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#4043]
Verified BAT sites should show a different logo (original logo had a blue bar for verified sites) so user knows pre-logo click that site was verified.

cc @NejcZdovc

**Comment by mandar-brave** [comment]
@jenn-rhim can we pull the original design for this!

**Comment by mandar-brave** [comment]
@rossmoody we need an icon for the change.
cc @ryanml

**Comment by NejcZdovc** [comment]
waiting for design and final decision on how it will work

**Comment by rossmoody** [comment]
@davidtemkin Has some final fine tuning to do and then we should be good to go, I think.

**Comment by rossmoody** [comment]
![Rewards Verified Toolbar](https://user-images.githubusercontent.com/29072694/56379243-285a4680-61c4-11e9-922e-4b0816e74b9e.png)

**Comment by davidtemkin** [comment]
@rossmoody @ryanml still some discussion needed -- we are not yet final-final -- please hold implementation for a moment

**Comment by davidtemkin** [comment]
@rossmoody @ryanml -- OK, confirmed all with @bradleyrichter and we are good to go with the above

**Comment by NejcZdovc** [comment]
so if I understand image correctly, if you have notification we don't show any indication for verified publisher?

**Comment by rossmoody** [comment]
Yea, the notification would take priority until it's cleared.

**Comment by NejcZdovc** [comment]
ok sounds good

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.66.87 Chromium: 75.0.3770.80 (Official Build) beta (64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Windows 7 Service Pack 1 (Build 7601.24465)

Verified test plan from https://github.com/brave/brave-core/pull/2294
Logged https://github.com/brave/brave-browser/issues/4817
