### ISSUE TITLE
Add to Brave News dialog is oversize

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#40441]
### Description

When clicking on the `Manage Subscriptions`/ Add RSS feed to Brave News icon in the url bar, the initial dialog has oversized UI buttons. On second click the buttons return to the proper size.

### Steps to reproduce

1. Visit a site with an RSS feed e.g. https://www.silverandblackpride.com
2. Click on Brave News/Add RSS feed in the url bar
3. Observe the dialog box

### Actual result

<img width="343" alt="Screenshot 2024-08-10 at 8 05 38 AM" src="https://github.com/user-attachments/assets/d0137a2b-9ddf-4699-86eb-40a3f7c8ee42">

### Expected result

<img width="378" alt="Screenshot 2024-08-13 at 7 42 46 PM" src="https://github.com/user-attachments/assets/d1d451b4-c800-4fbb-ab4e-f8d5ade6661d">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.x and higher

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by LaurenWags** [comment]
Requires `1.69.147` or higher for testing 👍🏻
