### ISSUE TITLE
Wrong twitch channel linked in Auto-Contribute

### ISSUE THREAD

**Issue by Shaomada** [brave/brave-browser#4045]
## Description 
Wrong twitch channel linked in the Auto-Contribute section of brave://rewards.

## Steps to Reproduce

   1. Pick a twitch channel which has a name terminating witch certain strings. My current assumption is the string having to end with _ (underscore) followed by none or more digits, but this assumption is not easy to test without creating new twitch channels. If you want to be sure you have a name which will reproduce the bug, you can use anatomyz_2, the channel with which I originally encountered it.
   2. Make sure you have Auto-Contribute enabled. I recommend changing your settings to 1 visit and 1 minute so you won't have to wait too long.
   3. Watch a video or stream on your chosen twitch channel long enough (depending on your settings) for it to be included in Auto-Contribute.
   4. Go to brave://rewards, navigate to Auto-Contribute and click on the name of the twitch channel you just watched

## Actual result:
Links to the twitch channel with the initial part of the name (ie. the part before the underscore). For our example channel, it links to https://www.twitch.tv/anatomyz/videos

## Expected result:
Links to the the twitch channel you watched. Example: Links to https://www.twitch.tv/anatomyz_2/videos

## Reproduces how often: 
For a fixed channel, every time you click the link (10/10).
For different channels, reproducing it is more annoying, as you need to either find or create such channels, and channel search of twitch does not seem support underscore. So far, I only found one other channel (leagueofladies_) which has a fitting name and encountered the bug with that channel as well. If there are letters after the underscore, everything works fine

## Brave version (brave://version info)
Brave | 0.60.45 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?
Not tested

### Additional Information
The correct channel name does appear in the list, only the link is wrong. I have no idea if the contribution itself goes to the correct channel or not though.

**Comment by jasonrsadler** [comment]
This also affects `publisher_id` in addition to `url`

**Comment by jasonrsadler** [comment]
May also be worth mentioning that this seems to affect VOD only. I am unable to reproduce with live streams.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.66.90 Chromium: 75.0.3770.87 (Official Build) beta (64-bit)
-- | --
Revision | 9dc58a2353af60ab2b48bab98a25bc43ed59085d-refs/branch-heads/3770@{#982}
OS | Windows 7 Service Pack 1 (Build 7601.24468)

Used testplan from https://github.com/brave/brave-core/pull/2224. Any channel with underscore will exhibit this issue. I used https://www.twitch.tv/tal_raja/videos. Tested stream and VODs.

Encountered https://github.com/brave/brave-browser/issues/4921
![image](https://user-images.githubusercontent.com/34715963/59542539-b9207a80-8f06-11e9-9a9c-1906f5e9f0fc.png)
![image](https://user-images.githubusercontent.com/34715963/59542544-c3427900-8f06-11e9-895d-463e9bbbe83c.png)
![image](https://user-images.githubusercontent.com/34715963/59542551-cd647780-8f06-11e9-9d1d-0b4e1743c4cd.png)
![image](https://user-images.githubusercontent.com/34715963/59542561-d7867600-8f06-11e9-8385-e3f3b4ecc73b.png)
![image](https://user-images.githubusercontent.com/34715963/59542567-dd7c5700-8f06-11e9-9e8e-9986554193b1.png)
