### ISSUE TITLE
Selected token is prepopulated in Bridge To token

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#40454]
### Description

Selected token is prepopulated in Bridge To token

### Steps to reproduce

1. Select Bridge and select a `Bridge From` token
2. Select account
3. Click on `Choose asset` in `Bridge To` token
4. Already prepopulated with the same token selected in `Bridge From`

### Actual result

https://github.com/user-attachments/assets/dce90c44-046a-4e7e-9c09-828160004eb2

### Expected result

Should not pre populate the selected token

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.69.145 Chromium: 128.0.6613.27 (Official Build) beta (64-bit)
-- | --
Revision | b029337c8485766fbc2dd25b11a46c88c8aaf2b4
OS | Windows 11 Version 23H2 (Build 22631.3880)

### Channel information

- [ ] release (stable)
- [X] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @Douglashdaniel @josheleonard

**Comment by Douglashdaniel** [comment]
Fix is being uplifted to `Beta 1.69.x`  https://github.com/brave/brave-core/pull/25129

**Comment by Douglashdaniel** [comment]
@srirambv https://github.com/brave/brave-core/pull/25129 is now merged and should be fixed in `1.69.x`

**Comment by srirambv** [comment]
Closing as dupe of #39828
