### ISSUE TITLE
Empty playlist folder should show an image

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#40450]
When a playlist folder is empty, an image should show up above text.

### Expected
<img width="459" alt="image" src="https://github.com/user-attachments/assets/390ca5c2-4d5d-44fa-8494-19b406bd94e1">

### Actual
<img width="391" alt="image" src="https://github.com/user-attachments/assets/351d969f-20c8-4dc0-8d4d-1a4fd8acddbf">

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.70.88 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 7431803bd1e909ef82982df42e2ea7aacbad755e
OS | Windows 11 Version 23H2 (Build 22631.4037)
```
Installed 1.70.88
launched Brave
enabled `#playlist` flag in `brave://flags`
clicked `Playlist` button on the sidebar
clicked `Playlater` button in the playlist panel

#### Confirmed Playlist image is shown as expected in the empty playlist folder

example | example | example | example 
----- | ----- | ----- | -----
![image](https://github.com/user-attachments/assets/f3bfade2-abe3-4558-8c33-6e80a9d5b842)|![image](https://github.com/user-attachments/assets/96483ce5-15ae-4d1c-b380-87c24cb7a461)|![image](https://github.com/user-attachments/assets/0a7eb6e0-29c8-4677-868c-3bcbf2a08d74)|![image](https://github.com/user-attachments/assets/239a1495-1004-4c59-8f2e-5baedc37074a)

**Comment by aguscruiz** [comment]
Updated the Figma file to show the correct copy:

https://www.figma.com/design/RxyQnpxi9qtf5HmnAj1yH0/Desktop-Playlist?node-id=1937-23814&t=KJiHZ1Lv2ctgFrkT-1


![image](https://github.com/user-attachments/assets/d77a7c69-02ad-4955-8b05-7774530e9da1)
