### ISSUE TITLE
Fix a typo in custom AI model request name infotip

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#40459]
The info tip currently reads:

```
The name of the model as it should appear in the request to the serving framework, i.e. phi-3 (note that if this name doesn’t match exactly what is expected by the serving framework the integration will not work)
```

`i.e.` should be `e.g.`

**Test plan**
1. Launch Brave
2. Open brave://settings/leo-assistant
3. Click on Add new model
4. Hover over the (i) symbol of the Model request name field
5. Verify the text of the infotip.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.71.102 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | d901535b1091c5f39eb2b5426b8fa8e7f3c5edf0
OS | Windows 11 Version 23H2 (Build 22631.4169)

- Verified steps from issue description
- Verified custom AI model request name infotip has **`i.e.`** replaced with **`e.g.`**

https://github.com/user-attachments/assets/72db0a0e-829d-442e-a84f-0797870b8c22
