### ISSUE TITLE
[Brave Leo]: Update model names in Leo models menu

### ISSUE THREAD

**Issue by LorenzoMinto** [brave/brave-browser#40464]
### Description

We should update the model names in the model menu:
- "Llama 3 8B" -> "Llama 3.1 8B"
- "Claude 3 Sonnet" -> "Claude 3.5 Sonnet"

### Current result

<img width="459" alt="Screenshot 2024-08-14 at 18 14 53" src="https://github.com/user-attachments/assets/fcb00ea7-97d6-44a0-8923-7bc0c7b8bef9">

cc @mattmcalister @stephendonner

**Comment by kjozwiak** [comment]
The above requires `1.69.157` or higher for `1.69.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.69.157 Chromium: 128.0.6613.85 (Official Build) (64-bit)
-- | --
Revision | 14c4bb724553b882abcd2fccd9b5acf1f177fe6d
OS | Windows 10 Version 22H2 (Build 19045.4780)
```

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240726.009 release-keys
Brave build: 1.69.157
Chromium: 128.0.6613.85 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Launch Leo
2. Hamburger menu > Leo
3. ⚙️ > *Verify*
4. Advanced Settings
5. Default model for new conversations > *Verify*

**ACTUAL RESULTS:**
- Verified that `Llama 3 8B` updated to `Llama 3.1 8B`
- Verified that `Claude 3 Sonnet` updated to `Claude 3.5 Sonnet`

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/01dc3436-518f-4739-88ab-503f7a6b387e) | ![2](https://github.com/user-attachments/assets/0da11a03-b450-4e13-8c9d-3cb2b1688f4c) |

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 17.6` using the following build(s):

```
Brave | 1.69.162 Chromium: 128.0.6613.120 (Official Build) stable (64-bit)
--- | ---
Revision | e534755d4eb5...
OS | iOS
```

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/25343#issuecomment-2314137325, ensured that the correct strings/text was being used as per the following:
* `Llama 3 8B` --> `Llama 3.1 8B`
* `Claude 3 Sonnet` --> `Claude 3.5 Sonnet`

**`Example`** | **`Example`**
----------------|-----------------
![IMG_0520](https://github.com/user-attachments/assets/207e45d4-10a3-4a05-8c7b-c8c7b0b0eadc) | ![IMG_0521](https://github.com/user-attachments/assets/cce2f25f-42ba-406f-91e7-979b44bbf189)
