### ISSUE TITLE
Add 18 and over category in taxonomy

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#4046]
Issue: Need to support LDA and other similar categories for targeting purposes.

Feature needs:
- add a 18 and over master node to the taxonomy
- the 18 and over node is always set to true (BR requires user to be 17+)

During the implementation of the user feedback feature, the user can opt out of the 17+ flag as a choice and should never be shown 17+ ads.

On the server end, all appropriate ads should automatically select 17+ flag based on the campaign/creative combo.

**Comment by tmancey** [comment]
@jsecretan @dimmu Is this issue still required? As we will shortly be able to update taxonomies with user model updates via the component updater!

**Comment by tmancey** [comment]
Closing as stale
