### ISSUE TITLE
`Undo` text in `Clear all` button from `brave://downloads/` in too faint

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#40472]
### Description

`Undo` text in `Clear all` button from `brave://downloads/` in too faint

### Steps to reproduce

1. install `1.70.77`
2. launch Brave
3. start downloading a large file
4. cancel the download
5. open `brave://downloads/`
6. click on the top-right ellipsis `...`
7. click on `Clear all`
8. look at the resulting dialog's text color

### Actual result

![image](https://github.com/user-attachments/assets/78f41e3f-0cf0-49e7-8c40-183afdfd410a)

### Expected result

![image (1)](https://github.com/user-attachments/assets/ce596c6c-6279-4e93-923b-324bae22be10)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.70.77 Chromium: 128.0.6613.27 (Official Build) nightly (64-bit)
-- | --
Revision | 1c08cc9a735d56c81b9af5c80d3b136ed0ec15ff
OS | Windows 10 Version 22H2 (Build 19045.4780)
```

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

/cc @aguscruiz @rebron @brave/qa-team @mkarolin

**Comment by aguscruiz** [comment]
I think the actual problem here is the background color of the "Cleared all" notice. If that one was dark like the rest of the theme then it would look ok.

**Comment by nastavoi** [comment]
Same problem described here https://github.com/brave/brave-browser/issues/38636

**Comment by stephendonner** [comment]
> Same problem described here #38636

Thanks; marking as a duplicate.
