### ISSUE TITLE
RTL/BiDi Language Support

### ISSUE THREAD

**Issue by AndyAnds265** [brave/brave-browser#40471]
### Platforms

iOS

### Description

In an effort to expand our languages on the iOS platform to other [Apple supported languages](https://developer.apple.com/help/app-store-connect/reference/app-store-localizations), we would like to ensure that our iOS mobile app is functioning properly with right-to-left (RTL)/Bi-directional (BiDi) languages. 

Currently we do not support any BiDi/RTL languages but in the near future we would like to support Arabic then potential Hebrew soon thereafter. 

The strings are nearly complete inside of Transifex, so when we can we need to get some time to review.

**Comment by AndyAnds265** [comment]
@iccub - it looks like all the strings are ready here in Transifex. Do you have time to review?

**Comment by kjozwiak** [comment]
The above requires `1.70.128` or higher for `1.70.x` verification 👍

**Comment by Uni-verse** [comment]
in progress on iPhone XR running 17.7 using version 1.70.129
