### ISSUE TITLE
Implement user feedback loop

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#4047]
Specification details -- images and UX coming shortly.

V1.1 User feedback changes

The Brave Ads panels will be expanded to have a Browser history; this browser history table will also be allowing multi-functional actions back from the user.

In V1.0, the actions are;
Don’t send me this again - Block ad from notifying me again
Dismiss action on Ad will perform the same action 
Save - Want to ensure Ad is saved for future viewing
Adds to Bookmark
Flag - Ad is very inappropriate
This will also trigger Action#1
Personalize Ads - add/remove categories i am interested in
Includes LDA check upfront
These categories will be flagged the highest in the taxonomy
Categories opted out will be tagged opted out forever

Mock for Ads Rewards feedback panel
Note: Mock is not complete and needs to be re-rendered

User flow
 The user can reach the User feedback setting as part of Brave rewards. The user can see which ads were delivered for the last 30 days with the following detail;
Advertiser detail (main + ad-text)
Category why ad was delivered and allow quick click to opt out for that specific category
Viewed or Clicked or Dismissed
Earned reward per line level item

The above details provide a bookmark view of Ads viewed in the past. The user can decide to choose the dismissed Ads to personalize ad viewing. The user can opt out of Ad categories, including 18 and over.

In the same flow, the user can decide to personalize further and decide not opt out of categories. When the user opts out, they are opted out of those categories permanently. The user can search through categories via drop down or by searching for them. Similarly, a user can decide to opt in to certain categories in the same flow.

Spec: https://docs.google.com/document/d/1XusXB1li8I7Q-3PAk3-2BcdujwZ0Y6oD0yNvhsahZgc/edit#heading=h.l7wtf1v849do

@jsecretan V1.1 prioritization
@NejcZdovc user feedback loop in Brave Rewards
@jenn-rhim to prioritize the visualization of the user feedback loop

**Comment by mandar-brave** [comment]
@jenn-rhim would love to ship the current design for user feedback loop. If you can post it, i can get the details from the spec to map to the UI. cc @alexwykoff

**Comment by alexwykoff** [comment]
After conferring between design & dev, this is the agreed solution. 

Screens courtesy of Jenn.

<img width="1046" alt="Screen Shot 2019-05-16 at 4 32 12 PM" src="https://user-images.githubusercontent.com/1434040/57888593-2e116f00-77f8-11e9-9746-fbfbfeebfe7e.png">

**Comment by jasonrsadler** [comment]
@alexwykoff This is the wrong issue. Goto #4351

**Comment by jsecretan** [comment]
Some things to clarify for @emerick is that 

1) When the upvote/downvote on the ad is selected, it will send an "upvote" or "downvote" type of confirmation associated with the creativeInstanceId of that ad.
2) The ad delivery logic should then avoid delivering anything with the same **creativeSetId** (note that this is broader than just creativeInstanceId) as anything that was downvoted.
3) When and ad is downvoted, it is probably wise to store creativeInstanceId, creativeId, creativeSetId, campaignId and advertiserId just in case the blocking rules change in the future

**Comment by jsecretan** [comment]
And after discussion with @tmancey and @emerick, we should also filter out creativesets that are associated with downvoted categories.

**Comment by jsecretan** [comment]
Flag as inappropriate should send flagged conference type.  And when flagged, should follow the same creativesetid blocking as downvote.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from https://github.com/brave/brave-core/pull/2792
* Verified Ads older than 7days were not displayed in the main view of Ads History panel
* Verified Viewed, Clicked, Dismissed ads display in Ads History
* Verified All/Saved/Thumbs up views filtered when clicked on
* Verified `filtered_ads`, `filtered_categories`, `saved_ads`, and `flagged_ads` were populated in `client.json` as described by the PR
* Logged follow up issues: #6204, #6205, #6206, #6207, #6208, #6209

<img width="956" alt="Screen Shot 2019-09-27 at 6 51 16 PM" src="https://user-images.githubusercontent.com/28145373/65806531-f3312780-e157-11e9-8d67-c6dafe8fdaaf.png">
<img width="952" alt="Screen Shot 2019-09-27 at 6 51 27 PM" src="https://user-images.githubusercontent.com/28145373/65806532-f4625480-e157-11e9-937a-75b56c65d528.png">
<img width="956" alt="Screen Shot 2019-09-27 at 6 51 57 PM" src="https://user-images.githubusercontent.com/28145373/65806534-f5938180-e157-11e9-9c94-63d3e6def8a6.png">

**Comment by tmancey** [comment]
@jsecretan @emerick Adding the following comment, which we previously discussed to help QA with https://github.com/brave/brave-browser/issues/7833

Ads viewed count will be reset to zero due to legacy ads history having to be cleared out as we only stored a timestamp
