### ISSUE TITLE
[C128] "Relaunch to Update Brave" menu item doesn't relaunch the browser

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#40475]
### Description

When you have an update waiting ("Update" is displayed on the hamburger menu), and you click on the "Relaunch to Update Brave" menu item, the browser should show a prompt where you can choose "Not Now" or "Relaunch".

With C128 versions that prompt to select Not Now/Relaunch is not showing so when I click "Relaunch to Update Brave" menu item, the browser just closes and does not reopen on its own.

### Steps to reproduce

1. Have an update waiting (I had `1.70.61` with C128 installed).
2. Click on "Update" message on hamburger menu
3. Click on "Relaunch to Update Brave"

### Actual result

Not Now/Relaunch prompt is not shown
Browser closes and does not relaunch

https://github.com/user-attachments/assets/70a3dd24-5711-4c81-81e0-377133813c83

### Expected result

Should have gotten a prompt like below (from 1.68.x with C127) and when "Relaunch" is selected, the browser relaunches.

<img width="478" alt="Screenshot 2024-08-15 at 8 07 30 AM" src="https://github.com/user-attachments/assets/adc85b27-2669-4c65-9156-1f4a5c01555b">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.61 Chromium: 128.0.6613.18

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @mkarolin @brave/qa-team

**Comment by GeetaSarvadnya** [comment]
@LaurenWags: This works for me on Windows 10 x64. I was on `1.70.51 with CR127` I kept this version open for couple of hours, I have got update notification via Hamburger menu, I clicked on `Relaunch to update brave` menu item, I have got relaunch brave popup modal with `Relaunch` and `Not now` buttons, when I clicked on `Relaunch` , the brave is relaunched and updated to latest nightly build `1.71.2 Chromium: 128.0.6613.27`. I think issue is with macOS?

Example | Example | Example | Example
----------|----------|-----------|----------
![image (7)](https://github.com/user-attachments/assets/e17a7744-bcf2-44d8-b661-9b8e60d79068) | ![image (8)](https://github.com/user-attachments/assets/d53454f7-9769-4441-8155-2a23e287e437) | ![image (9)](https://github.com/user-attachments/assets/ce3b6160-dfe5-4089-9615-5339062058c8) | ![image (10)](https://github.com/user-attachments/assets/08955fb9-0ec0-4f04-9763-1a7b219c1341)

**Comment by mkarolin** [comment]
Interesting, I see in cr128 there's a new feature: 

```
#if BUILDFLAG(IS_WIN) || BUILDFLAG(IS_MAC) || BUILDFLAG(IS_LINUX)
// Enables the feature to remove the last confirmation dialog when relaunching
// to update Chrome.
BASE_FEATURE(kFewerUpdateConfirmations,
             "FewerUpdateConfirmations",
             base::FEATURE_ENABLED_BY_DEFAULT);
#endif
```
So, I would actually expect the popup dialog not to be shown on any of the desktop platforms.

**Comment by GeetaSarvadnya** [comment]
@mkarolin: In the case above https://github.com/brave/brave-browser/issues/40475#issuecomment-2291678253, I have updated Brave CR127 to CR 128.

You might be right [here](https://github.com/brave/brave-browser/issues/40475#issuecomment-2292212136) let me try update from CR 128 lower version (1.70.61) to CR 128 higher version. 

I will post my observation here.

**Comment by GeetaSarvadnya** [comment]
@mkarolin @LaurenWags: I am able to reproduce the issue, there is no relaunch popup modal when I update brave from `1.70.61 CR128` to `1.71.2 Chromium: 128.0.6613.27`, when I click on `Relaunch to update brave` menu item, brave closes but doesn't relaunch, when I open brave manually and view brave://version, brave updated to latest nightly version as expected.

Example | Example | Example 
----------|----------|-----------
![image](https://github.com/user-attachments/assets/59aa68b1-a037-4bc2-8f17-575f607880b3) | ![image](https://github.com/user-attachments/assets/f00ab693-0106-419a-b4be-298f2d0b2e5e) | ![image](https://github.com/user-attachments/assets/6740c8e0-aea0-4a64-be18-c2f356c1b68d)

**Comment by mkarolin** [comment]
I am able to reproduce on MacOS, but it looks to me like the new version tries to start (I see a white rectangle and then a pinwheel) and crashes. After I start the browser again normally (the upgraded version) and go to brave://crashes I see the crash. I got ecab0a00-ebf9-720c-0000-000000000000 and 9ee30800-ebf9-720c-0000-000000000000. Both look the same in backtrace: a crash in GPU process.

**Comment by mkarolin** [comment]
@LaurenWags and @GeetaSarvadnya I pushed a potential fix/workaround, which is just disabling that new feature. It seems to fix it for me on MacOS, although, I don't currently know why. If you get a moment could you please check if that would also fix it for you but running the browser version that you are updating with `--disable-features=FewerUpdateConfirmations`.

**Comment by kjozwiak** [comment]
**`Quick Note:`** the above will require two RC builds with the fix. The first one will be `1.69.149` and then we'll require `1.69.150` as well so we can run through a `1.69.149` -> `1.69.150` upgrade.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.69.150 Chromium: 128.0.6613.40 (Official Build) (64-bit)
-- | --
Revision | aea36034a3cccd841545ac66ffb79f21e2ba5dd4
OS | Windows 10 Version 22H2 (Build 19045.4780)

```

-------
Verification PASSED on

```
```
Installed `1.71.13 Chromium: 128.0.6613.40` and waited for an update notification, after getting an `Update` via hamburger menu, clicked on `Update->Relaunch to update Brave` and ensured the following:

- Confirmed that `Relaunch Brave` popup modal is shown with `Relaunch` and `Not now` buttons
- Confirmed that click on `Relaunch` button auto closed and relaunched the browser
- Confirmed that brave is updated to latest nightly public version `1.71.16 Chromium: 128.0.6613.40`

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.71.13 Chromium: 128.0.6613.40
```

Installed `1.71.13` a couple of days ago. Waited until I got the "Update" message on the hamburger menu. Confirmed clicking "Relaunch" on the modal closed the browser and reopened the updated version, `1.71.16`, as expected.


https://github.com/user-attachments/assets/2d74f9b1-a2a2-4e04-9887-72facb0ad291

**Comment by LaurenWags** [comment]
Note - @GeetaSarvadnya and I were unable to get the "Update" message on the RC (on Windows it's because of how we update using the `test` channel and on macOS it's due to timing/how long it takes to get this message which is ~2 days). However, we both confirmed the fix is working on Nightly with the appropriate build. Per discussion with @kjozwiak we're going to mark this one as `QA Pass` for Windows and macOS.
