### ISSUE TITLE
Unable to transfer SPL NFTs

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#40489]
### Description

Backend returns internal error when making SolanaTxData.

### Steps to reproduce

Transfer a Solana SPL NFT.

### Actual result

Internal error

### Expected result

Successful transfer

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Current

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.69.151` or higher for `1.69.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.152 Chromium: 128.0.6613.40 (Official Build) (64-bit)
-- | --
Revision | 08e043d00cc975667f92070e87ca21f8ac37ea4a
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from issue description
- Verified able to send Solana NFT

https://github.com/user-attachments/assets/6a5c6879-331a-4447-9ea0-5d9da5cf75dd
