### ISSUE TITLE
[Shred] Tab and data not deleted when using 'App Close' for Auto Shred

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#40484]
### Description

Tab and website data are not deleted with Auto Shred set to 'App Close'

### Steps to reproduce

1. Enable #brave-shred in Brave://flags, restart browser
2. Set Auto Shred to `App Close` in Shields & Privacy settings
3. Open a new tab, load any URL
4. Open `Manage Website Data` to confirm website data
5. In active tab, open Shields panel -> Shred Site Data, confirm Auto Shred is set to `App Close`
6. Close/relaunch Brave
7. Confirm active tab is removed
8. Confirm website data is deleted in `Manage Website Data` settings page

### Actual result

Tab and data not deleted after closing app

### Expected result

Tab and data should be deleted after closing app

### Reproduces how often

Easily reproduced

### Brave version

1.69 (146)

### Device/iOS version

`iPhone 12` | `iOS 17.5.1` - Reproducible

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by ShivanKaul** [comment]
Just a note that we want to release Shred in 1.70

**Comment by kjozwiak** [comment]
The above requires `1.71.117` or higher for `1.71.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Mini (6th gen)` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.7
- iPad Mini (6th gen) / iPadOS 18.0.1
Brave build: 1.71 (118)
BraveCore: 1.71.118 (130.0.6723.70)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/40484#issue-2468382530
2. *Verified*

**ACTUAL RESULTS:**
- Verified that all data and cache are cleared when `Auto Shred` is set to `App Close`

---------------------------

`iPhone 14 / iOS 17.7`

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/582fd38b-7795-4159-8aa2-8c10c38a804a) | ![2](https://github.com/user-attachments/assets/281d3f48-a913-4466-a8b1-9bf71ac8a45c) | ![3](https://github.com/user-attachments/assets/a6c275a2-c043-486f-af13-fb47847f1a39) |
| ![1](https://github.com/user-attachments/assets/01f8a8d7-e86f-4ee1-990f-fb6b76988705) | ![2](https://github.com/user-attachments/assets/44407bb0-feb0-4cf1-badb-b93b31ab8982) | ![3](https://github.com/user-attachments/assets/697e35b8-8be0-4b68-a7be-b5a39cff2389) |

`iPad Mini (6th gen) / iPadOS 18.0.1`

https://github.com/user-attachments/assets/1822cff6-6f5c-4728-a733-2d61ab18bbea
