### ISSUE TITLE
[C128] Inactive tab hover is incorrect

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#40486]
### Description

In C127 versions when you hover over an inactive tab there's a subtle effect to show that you're hovering over the tab.

In C128 versions the hover isn't subtle, it looks like the tab hover state is the same as the active tab's.

Only seems to affect horizontal tabs, vertical tabs seem fine.

Reproduced on Beta with `1.69.145 Chromium: 128.0.6613.27` (1.69.144 with C127 is fine).
Also reproduced with RC `1.69.146 Chromium: 128.0.6613.27` (1.68.141 with C127 is fine).

### Steps to reproduce

1. Have a window with a couple of tabs
2. On a non-active tab, hover over the tab
3. See that the hover state on the non-active tab looks like the active tab.

### Actual result

when hovering over non-active Password Manager tab:

<img width="675" alt="Screenshot 2024-08-15 at 1 01 32 PM" src="https://github.com/user-attachments/assets/e92020cf-7f20-4c1c-bc28-996aaee31553">

### Expected result

hover state should look like the below for Settings tab (subtle):

<img width="642" alt="Screenshot 2024-08-15 at 1 03 20 PM" src="https://github.com/user-attachments/assets/0303b7e0-a734-4a5d-a438-5ba38a754f3c">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.69.146 Chromium: 128.0.6613.27 (Official Build) (x86_64)
-- | --
Revision | 3bd0f984ce99277bd556cac8dd198aba4467a22f
OS | macOS Version 13.6.9 (Build 22G830)

Also reproduced with `1.69.145 Chromium: 128.0.6613.27` on Beta and `1.70.77 Chromium: 128.0.6613.27` on Nightly

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @mkarolin @brave/qa-team

**Comment by stephendonner** [comment]
Great catch!

**Comment by tech-zilla** [comment]
@simonhong  I've added a possible fix for this issue. Please free modify it if you think something is done in a wrong way. Thanks!

**Comment by simonhong** [comment]
checking now

**Comment by simonhong** [comment]
> @simonhong I've added a possible fix for this issue. Please free modify it if you think something is done in a wrong way. Thanks!

@tech-zilla Thanks for submitting PR for this issue.
And sorry to not use your PR. As this is `p2` and fix should be quickly uplifted to release channel, I used my PR. Please understand.

**Comment by LaurenWags** [comment]
Requires `1.69.151` or higher for testing 👍🏻

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.69.152 Chromium: 128.0.6613.40 (Official Build) (64-bit)
-- | --
Revision | 08e043d00cc975667f92070e87ca21f8ac37ea4a
OS | Windows 10 Version 22H2 (Build 19045.4780)
```

**Comment by tech-zilla** [comment]
> > @simonhong I've added a possible fix for this issue. Please free modify it if you think something is done in a wrong way. Thanks!
> 
> @tech-zilla Thanks for submitting PR for this issue. And sorry to not use your PR. As this is `p2` and fix should be quickly uplifted to release channel, I used my PR. Please understand.

No worries, I'm glad that I could help. thanks too!
