### ISSUE TITLE
OnDrive PowerPoint presentations broken by anti-fingerprinting

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#4048]
## Description 
OneDrive presentations are broken when Shields' anti-fingerprinting mode is enabled.

## Steps to Reproduce

1. Visit https://onedrive.live.com/view.aspx?resid=40AD2A59FD334E8C!400130&ithint=file%2cpptx&authkey=!ADAerq8JH6E4yRA
2. Go into Shields and switch the anti-fingerprinting setting to: "All device recognition allowed".

## Actual result:

With "3rd party device recognition blocked":
![Screenshot from 2019-04-08 16-23-59](https://user-images.githubusercontent.com/167821/55763174-c1e26500-5a1a-11e9-9ad6-3d616d9802c0.png)

With "all device recognition allowed":

![Screenshot from 2019-04-08 16-26-33](https://user-images.githubusercontent.com/167821/55763287-200f4800-5a1b-11e9-8ca0-fa43d84d1fa9.png)

## Expected result:

The slides should load properly.

## Reproduces how often: 

Always reproducible.

## Brave version (brave://version info)
```
Brave | 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)
Revision | e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}
OS | Linux
```

### Reproducible on current release:

It's also broken on brave-browser dev/beta builds.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 

Yes, though only the anti-fingerprinting setting needs to be disabled.

- Is the issue reproducible on the latest version of Chrome? 

No.

**Comment by ryanbr** [comment]
Just a ping @fmarier  Viewing a onedrive presentation in Brave Release, seems to work without changes to shields. Can you confirm everything is okay?

**Comment by fmarier** [comment]
I still get the error above in Brave Beta (Version 1.10.70 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)) for the same URL: https://onedrive.live.com/view.aspx?resid=40AD2A59FD334E8C!400130&ithint=file%2cpptx&authkey=!ADAerq8JH6E4yRA

**Comment by ryanbr** [comment]
@fmarier  The above link works fine in Standard fingerprinting, but breaks in Aggressive. Is this still okay?

**Comment by fmarier** [comment]
It's working fine for me now (aggressive, Linux).
