### ISSUE TITLE
[Nala]: Update to use new color provider

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#40490]
This should make it much easier to use Nala colors from Chromium views. Additionally, it's a prerequisite for enabling tri-color themes in Brave (important because Chromium is deprecating the dual color ones we rely on).

# Test plan

I don't have a rigorous test plan here, but the things to look for are all in views UI
1. Light mode should look okay
2. Dark mode should look okay
3. Omnibox should look normal ish
4. Tab hover states should look fine
5. Tab selected states should look fine
6. Vertical tabs should look fine

Things to watch out for are:
1. Missing highlights/selection states
2. Glaring yellow/red colors where they shouldn't be

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.97 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | de99cbcb1aa0aa00877d356e4733f4e5481e89eb
OS | Windows 11 Version 23H2 (Build 22631.4169)
```
In-depth Nala-color testing has been done via https://github.com/brave/brave-browser/issues/40689#issuecomment-2369864923
but testing here as per the testplan https://github.com/brave/brave-browser/issues/40490#issue-2469136950


<details>
<summary>Light mode should look okay</summary>

brave://version | NTPSI | Custom background/Leo | Solid/Bookmarks|Reading List| Playlist | Gradient/VPN
------ | ----- | ------ | ----- | ------ | ----- | ------ 
![image](https://github.com/user-attachments/assets/2d62ff3f-25bd-4e9a-a8c7-6d6feb0566de)|![image](https://github.com/user-attachments/assets/b61a44f1-5ef1-40de-a1f7-f743fe482d38)|![image](https://github.com/user-attachments/assets/38477123-726c-4403-9647-ad8d2182ba9a)|![image](https://github.com/user-attachments/assets/474eec91-7e9a-4eca-9994-7345503df266)|![image](https://github.com/user-attachments/assets/495eb611-af19-427e-a4e2-0f21379c173c)|![image](https://github.com/user-attachments/assets/27864032-e68d-4886-99a9-8322b843d6dc)|![image](https://github.com/user-attachments/assets/199b78ef-8b5b-4282-88e0-6ce0971c617d)


</details>

<details>
<summary>Dark mode should look okay</summary>

brave://version | NTPSI | Custom background/Leo | Solid/Bookmarks|Reading List| Playlist | Gradient/VPN
------ | ----- | ------ | ----- | ------ | ----- | ------ 
![image](https://github.com/user-attachments/assets/987c85f8-6c8b-4f76-9487-063cd0732e5d)|![image](https://github.com/user-attachments/assets/e078a29f-65c3-45a7-9580-04b7c2f35add)|![image](https://github.com/user-attachments/assets/451aad88-c193-49b4-b6f8-8f5947b8bdc9)|![image](https://github.com/user-attachments/assets/f043c89d-3734-4d6b-bbef-0cdea05b9b7d)|![image](https://github.com/user-attachments/assets/0d1e3af3-ed4a-443e-b7ed-279c5ba3bf3c)|![image](https://github.com/user-attachments/assets/ca64d218-a38b-456c-9ac2-c985c0c346e2)|![image](https://github.com/user-attachments/assets/1029cfc9-9219-40f1-aec2-951ae8bc6ec0)
</details>


<details>
<summary>Omnibox should look normal ish</summary>

dark | light
---- | -----
![image](https://github.com/user-attachments/assets/e387b447-5b15-4f27-ba81-3adf31313a3d)|![image](https://github.com/user-attachments/assets/59e51117-785a-4152-8cd2-ca762872d3c0)
![image](https://github.com/user-attachments/assets/9ca086be-466a-4e50-afbb-5390fe27b4c0)|![image](https://github.com/user-attachments/assets/cc01d70b-a607-4e4d-9d95-dee5b9cbde13)
![image](https://github.com/user-attachments/assets/9a1756ac-fac9-4d85-b2a8-a723a22f9f80)|![image](https://github.com/user-attachments/assets/4dd1d23c-ada2-4045-a842-8626dd4952fd)
|![image](https://github.com/user-attachments/assets/c066183b-b7a2-439e-9d1d-dd031e684bb7)|![image](https://github.com/user-attachments/assets/1a76c5d8-ed34-49b9-be3d-ec50de2d1c60)
|![image](https://github.com/user-attachments/assets/ab638de9-2ee5-46ee-851c-91bec8b8ab25)|![image](https://github.com/user-attachments/assets/edd8a014-d97c-46c5-a2bd-9f140c669366)

</details>

<details>
<summary>Tab hover states should look fine</summary>

Dark | Light

Card | Card Preview | Tooltip
----- | ----- | -----
![image](https://github.com/user-attachments/assets/130e1d5c-d662-4d69-9de7-b59c4459e045)|![image](https://github.com/user-attachments/assets/4dc32d41-660d-4610-8b6c-b5a8fad51712)|![image](https://github.com/user-attachments/assets/3dad92ce-3cd9-42c0-aa5f-455be0ea7e5c)
![image](https://github.com/user-attachments/assets/765e75c3-4f51-487f-9131-f37a620f29fc)|![image](https://github.com/user-attachments/assets/7cfd20e9-a47f-448b-abd7-15c619be78ee)|![image](https://github.com/user-attachments/assets/4d56f0a7-6ccd-4603-987d-ee55a98bf96a)

</details>

<details>
<summary>Tab selected states should look fine</summary>

Dark | Light

example | example 
------ | ------
![image](https://github.com/user-attachments/assets/56bcf182-44c2-45ae-a814-412266124071)|![image](https://github.com/user-attachments/assets/1bf70171-f530-4001-b160-64abd86cf932)
![image](https://github.com/user-attachments/assets/374b8137-eef9-4e4e-9c57-12d1796b2028)|![image](https://github.com/user-attachments/assets/42c2994e-93cc-4675-9894-25b39fd5b4b2)

</details>

<details>
<summary>Vertical tabs should look fine</summary>

Dark | Light

Maximized | Minimized
------ | ----- 
![image](https://github.com/user-attachments/assets/ef305e65-be04-4bd4-8367-13d47a9b5940)|![image](https://github.com/user-attachments/assets/682d0fe8-9554-4f90-96aa-6368a5cd1dc7)
![image](https://github.com/user-attachments/assets/abc31106-270b-461d-90d1-811bc22af3ca)|![image](https://github.com/user-attachments/assets/67a8d86e-7722-4847-8e33-1cc8c5562e86)





</details>

**Comment by MadhaviSeelam** [comment]
@brave/qa-team Feel free to any other pages other than what I had verified.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.71.105 Chromium: 129.0.6668.89 (Official Build) beta (x86_64)
-- | --
Revision | f69ba167992437799f1dbcce81e90ba501a3d63e
OS | macOS Version 14.7 (Build 23H124)
```

**Comment by btlechowski** [comment]
Verification `PASSED` using

Brave | 1.71.113 Chromium: 130.0.6723.58 (Official Build) (64-bit)
-- | --
Revision | 3ee74228044546a84c661332ddb441a7a68108fa
OS | Linux



<details>
<summary>Light mode should look okay - PASSED</summary>

- Generally spot checked light theme on various pages/menus

brave://version | NTPSI 
--- | ---
![Image](https://github.com/user-attachments/assets/ea4545bd-2115-414e-a95b-92427562f31d)|![Image](https://github.com/user-attachments/assets/1a4804d8-5286-43a1-b320-46e4f6783f88)


Custom background/Leo | Custom background/Leo | Custom background/Leo
--- | --- | ---
![Image](https://github.com/user-attachments/assets/a8810970-8fae-4756-bff1-5ed0a83769c2)|![Image](https://github.com/user-attachments/assets/4a1af886-9484-4336-a133-30ec3401eecb)|![Image](https://github.com/user-attachments/assets/5ad305c8-d50d-4bdd-81fa-c40950f9ca4c)


Solid/Bookmarks | Solid/Bookmarks | Bookmarks Manager
--- | --- | ---
![Image](https://github.com/user-attachments/assets/eb28f360-871a-4b9b-8eff-5ca151274a93)|![Image](https://github.com/user-attachments/assets/ef438d15-7048-44d2-a96f-a666d3e8b635)


Reading List | Reading List 
--- | ---
![Image](https://github.com/user-attachments/assets/c9cf13e5-26c4-4e90-b66f-06b9f9e3a771)|![Image](https://github.com/user-attachments/assets/da0ba60d-49ac-4e47-8770-31aec892988b)



Extensions | Extensions 
--- | ---
![Image](https://github.com/user-attachments/assets/c90c7fe7-bd14-4571-913e-4647c2964691)|![Image](https://github.com/user-attachments/assets/0c3c549b-2390-461d-98bd-62724d65f905)


Widevine modal | Permission modal
--- | ---
![Image](https://github.com/user-attachments/assets/f64e3226-b22a-4672-a0e5-05f07192e148)|![Image](https://github.com/user-attachments/assets/76dbb8d2-5d77-4043-9f61-29018599655d)


Wallet | Wallet 
--- | --- 
![Image](https://github.com/user-attachments/assets/d7e884a5-26b6-48b4-82f1-69528047cbac)|![Image](https://github.com/user-attachments/assets/e37db544-4d8e-4e5c-b003-b616b7d3b310)


Settings | Settings  
--- | --- 
![Image](https://github.com/user-attachments/assets/77f898ce-c690-4ac6-a5d8-fba24a5bf923)|![Image](https://github.com/user-attachments/assets/4a9c2de9-a41f-42c9-9176-0f46c2c2d442)


Rewards | Rewards | Rewards | Rewards 
------ | ----- | ------ | ----- 
![Image](https://github.com/user-attachments/assets/bc7a6fee-3715-42d1-8266-100abfe0c766)|![Image](https://github.com/user-attachments/assets/d94f7fa8-7d7f-4260-8c0b-ae30b217d67d)|![Image](https://github.com/user-attachments/assets/9a36a6e5-83a3-4ef4-814c-80c8b86d5c6c)|![Image](https://github.com/user-attachments/assets/80d9bccb-2b3f-439d-a210-f85d7d43670a)



</details>


<details>
<summary>Dark mode should look okay - PASSED</summary>

- Generally spot checked light theme on various pages/menus

brave://version | NTPSI 
--- | ---
![Image](https://github.com/user-attachments/assets/aaa07ef2-be2b-47e2-9277-6b198f7575ad)|![Image](https://github.com/user-attachments/assets/734b370b-ee4c-4c96-9c4e-5e654395cd82)


Custom background/Leo | Custom background/Leo
--- | --- 
![Image](https://github.com/user-attachments/assets/9fe81ea4-46f4-431c-92b5-ef9b913db218)


Solid/Bookmarks | Solid/Bookmarks
--- | --- 
![Image](https://github.com/user-attachments/assets/d9008d12-b8cf-46fc-82ec-9dafd190f095)|![Image](https://github.com/user-attachments/assets/b9866031-b341-4107-afe0-8bcb34714420)


Reading List | Reading List 
--- | ---
![Image](https://github.com/user-attachments/assets/4aa2e989-daa8-4daf-9568-9fd05882e88a)



Extensions | Extensions 
--- | ---
![Image](https://github.com/user-attachments/assets/4a53ae0b-2402-45e0-b242-2a5745e301d5)|![Image](https://github.com/user-attachments/assets/ef60a2bb-7b1b-4618-ad08-49eb299b2868)


Widevine modal | Permission modal
--- | ---
![Image](https://github.com/user-attachments/assets/99b055a5-68ca-41dd-af12-7024ee7de228)|![Image](https://github.com/user-attachments/assets/6fea915c-d84f-4caa-8d11-08269dc5467a)


Wallet | Wallet | Wallet 
--- | --- | --- 
![Image](https://github.com/user-attachments/assets/8d891684-c6c5-49de-8321-f91ddedad2d0)|![Image](https://github.com/user-attachments/assets/660a61e9-7f4c-4b72-908d-74e83f0ac8c9)|![Image](https://github.com/user-attachments/assets/a0b49727-91d3-48de-8c07-c0820e5b1589)


Settings | Settings | Settings | Settings 
--- | --- | --- | ---
![Image](https://github.com/user-attachments/assets/03046f4e-d39c-4a58-8095-bf555bdd6e37)|![Image](https://github.com/user-attachments/assets/b9325c27-8b0d-4ec7-b80c-8ca71a92c487)|![Image](https://github.com/user-attachments/assets/9fe10917-27a2-4040-a24a-771881f839cd)|![Image](https://github.com/user-attachments/assets/490d437b-141c-4afd-af46-3d023ec026d8)


Rewards | Rewards | Rewards
------ | ----- | ------ 
![Image](https://github.com/user-attachments/assets/7276fb76-c09f-4068-be01-c98138996c8b)|![Image](https://github.com/user-attachments/assets/04c205e1-6daf-49ae-a2b8-fae8495f2732)|![Image](https://github.com/user-attachments/assets/b88c0473-ff5d-4d36-920c-7321bf2e5034)


</details>


<details>
<summary>Omnibox should look normal ish - PASSED</summary>

![Image](https://github.com/user-attachments/assets/d9d894f0-2146-48cf-923e-63bffde0c5f5)|![Image](https://github.com/user-attachments/assets/7ca1f189-e221-4bcb-9947-8b91f8486421)
--|--

</details>

<details>
<summary>Tab hover states should look fine - PASSED</summary>

![Image](https://github.com/user-attachments/assets/de327ca7-2d4e-4a76-81cc-33a74d673a2d)|![Image](https://github.com/user-attachments/assets/a201b191-5afa-489c-a78c-c09fb3bb1aad)|![Image](https://github.com/user-attachments/assets/c25cfbfb-9d0f-45e7-b97a-0d6ea1a7e278)
--|--|--

</details>

<details>
<summary>Tab selected states should look fine - PASSED</summary>

![Image](https://github.com/user-attachments/assets/82a6a0f5-ca1a-437d-ae09-4e062b81d1a4)|![Image](https://github.com/user-attachments/assets/f924c917-cb57-4961-821c-4fabeb7f6b59)
--|--

</details>

<details>
<summary>Vertical tabs should look fine - PASSED</summary>

![Image](https://github.com/user-attachments/assets/b5d61589-26bb-45ff-ac13-e05774066966)|![Image](https://github.com/user-attachments/assets/923d3af2-1f53-4932-9b3f-ed70bb120890)
--|--

</details>
