### ISSUE TITLE
Enabling Speedreader causes blogs/pages to go blank.

### ISSUE THREAD

**Issue by TEMP-ad** [brave/brave-browser#40491]
### Description

Speedreader on Android has not worked correctly since I tried to use it with Chromium 127 and now Chromium 128.

First, on my side the flag appeared to be disabled(?), and then when I enabled it, it wasn't working like showing the little popup "Do you want to see it in Speedreader mode" and no **View in reader mode** button in the menu, so I had to enable the 'automatic' Speedreader mode in `Settings -> Appearance ` for it to show something.

By doing that two things happened:

1. Most blogs I tried just went blank.
2. When they didn't go blank, they showed the **View in reader mode** button, and when using the button, then most sites went either blank.

## will show automatically blank:

   https://brave.com/blog/blade-testbed/
   https://www.cgchannel.com/2024/07/sidefx-releases-houdini-20-5-check-out-its-five-key-features/ 
   https://cgpress.org/page/2 

## Have the **View in reader mode** and then show blank
   https://cgpress.org/

### Steps to reproduce

1. Enable chrome://flags/#brave-speedreader
2. go to any of the examples mentioned
3. nothing happens
4. Enable automatic Speedreader mode in settings -> appearance 
5. blogs show blank

### Actual result

Blank pages in supported Speedreader mode blogs/pages.

### Expected result

Speedreading going to the Speedreader mode like on Desktop.

### Reproduces how often

Easily reproduced

### Brave version

1.71.3 Chromium: 128.0.6613.40 (Official Build) canary (64-bit)

### Device

- Brand/model: Samsung A235M
- Android version: 14

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by TEMP-ad** [comment]
@SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
@TEMP-ad we decided to disable it on Android and come back to it some time in the future when we have more resources to work on that feature.

**Comment by TEMP-ad** [comment]
Well, not what I wanted to hear, but makes sense and explains everything. Thanks for the information! 👍
