### ISSUE TITLE
Page contents disappear while scrolling

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#4049]
## Description 

The contents of the page disappears after scrolling past a certain point.

## Steps to Reproduce

   1.  Open https://www.inc.com/brian-de-haaff/3-ways-remote-workers-outperform-office-workers.html
   2. Scroll down the page.

## Actual result:

![out](https://user-images.githubusercontent.com/167821/55764520-bd20af80-5a20-11e9-83b0-723b74471086.gif)

## Expected result:

The page should not disappear.

## Reproduces how often: 

Perfectly reproducible.

## Brave version (brave://version info)

```
Brave | 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)
Revision | e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}
OS | Linux
```

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

Yes.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 

Yes. If I unblock ads and trackers it works fine.

- Is the issue reproducible on the latest version of Chrome? 

No.

**Comment by ryanbr** [comment]
Okay, needed some time to debug this; Seem all 3 are needed, since they're interacting with each other (lightbox is being excuted by tinypass and consensu.org). Not sure if this cause any other issues, but it'll allow the user to scroll.

```

||lightboxcdn.com^$script,domain=inc.com
||tinypass.com^$script,domain=inc.com
||conversant.mgr.consensu.org^$script,domain=inc.com
```

consensu.org = loads the GDPR notice
tinypass.com  = is a subscription checker
lightboxcdn.com = allows to draw divs on the site.

**Comment by ryanbr** [comment]
Correction, was a dianomi issue.

**Comment by Brave-Matt** [comment]
I have some users still reporting this (or very similar) issues on other sites -- namely inc.com
User reports:
https://community.brave.com/t/page-rendering-bug-mac/69610/2
https://community.brave.com/t/when-scrolling-down-in-a-inc-com-article-of-an-particular-author-the-web-page-goes-blank/37455/11
