### ISSUE TITLE
brave://version should have brave release number along with Chromium version

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#405]
## Description 

brave://version should have brave release number along with Chromium version
## Steps to Reproduce

   1. Visit chrome://version
   2. Shows Chromium version as Brave version
   3. 

 ## Actual result:

![image](https://user-images.githubusercontent.com/17010094/41795840-35c1fa62-7632-11e8-88e3-0ad033491798.png)

## Expected result:
Should show Brave version and Chromium version separately in a custom override page

**Comment by srirambv** [comment]
Marking as P1 as this blocks testing upgrade builds.

**Comment by bbondy** [comment]
Fixed here:
https://github.com/brave/brave-core/pull/237

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

chrome://version includes Brave version.
