### ISSUE TITLE
Auto-contribute fails to contribute anything due to non-signed up creators

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#4050]
## Description 

I have a lot of BATs which are queued up to be given to creators who haven't signed up yet, more than my balance.

![Screenshot from 2019-04-08 17-40-15](https://user-images.githubusercontent.com/167821/55765676-a761b900-5a25-11e9-95e4-1ed328c795df.png)

Most of these will never get paid so it's surprising to me that this is blocking the auto-contribute to registered publishers. Once a month, I get a message saying that auto-contribute failed and that I need to top-up my Uphold account.

Since I have set my auto-contribute amount to 20 BAT / month:

![Screenshot from 2019-04-08 17-44-07](https://user-images.githubusercontent.com/167821/55765729-ed1e8180-5a25-11e9-99a9-183c2e90d6a6.png)

which is well within my current Uphold balance, it seems like failing to auto-contribute is not the optimal way to handle this, presumably common, case.

At the very least, some BATs should be sent to the registered publishers who got my attention in the last month.

**Comment by NejcZdovc** [comment]
@fmarier do you have any recurring tips?

**Comment by fmarier** [comment]
I do and this morning, I actually saw a successful Auto-Contribute and monthly tip:

![Auto-Contribute-worked](https://user-images.githubusercontent.com/167821/55819903-afb20680-5aae-11e9-9e81-e4e6e272133e.png)

I wished I had made a screenshot the error message I got yesterday :/

**Comment by NejcZdovc** [comment]
@fmarier did you maybe update browser in the meantime?

**Comment by fmarier** [comment]
I'm not sure when the update came in. I guess I'll have to wait until next month to see if I get the same error message. I'll try to remember to take a screenshot.

**Comment by NejcZdovc** [comment]
thank you, will close this one. Please reopen it if this is still a problem
