### ISSUE TITLE
Playlist index not updated when items are rearranged while playing

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#40502]
### Description

When playing media in a playlist on iOS, if the object in the list currently being played is reordered, the list index is not updated and the song after it's _original_ place gets played instead. For example:

When the playlist object at spot `n` in the list gets moved to spot `n+3` (for example), which would be three spots down from the current place on the list, the iterator never changes and will always only play `n+1` after the current media finishes. 

It may be more or less complicated than this under the hood but that appears to at least accurately describe the behavior I'm seeing. When the item is moved, the index should update and next item in the list after the _currently playing item_ should be played next

### Steps to reproduce

1. Start playing the first song/item in the Playlist, so the index at this point would be `n = 0`
2. Move the currently playing item to the fourth place in the list, so the item would now be at index 3 in the list (`n = 3`). 
3. As such, you'd expect that when the song/media completed, the index would increment and the object at `n = 4` would play, but instead observe the second song in the list played (`n = 1`)

### Actual result

Index not updated and the item behind the currently playing items _original_ place is played

### Expected result

Next item in the list after whatever is currently being played ends should be played, regardless of position.

### Reproduces how often

Easily reproduced

### Brave version

v1.67 (127)

### Device/iOS version

iPhone 8, 11, XR, iPad
17.5.1

### Affected browser versions

- [X] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

User report:
https://community.brave.com/t/brave-playlist-has-errors-when-reordering-items/563510/2

**Comment by An0n-00** [comment]
any update? still happens in the newest ios version

**Comment by Brandon-T** [comment]
This was fixed on nightly via: https://github.com/brave/brave-browser/issues/42355
