### ISSUE TITLE
[ads] Add NTP media type p3a metrics

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#40507]
### Description

Question: What type of new tab page sponsored media is shown? Answers:
1. disabled
2. images
3. images & videos

Change existing metric name to `Brave.NTP.SponsoredMediaType` for all platforms.

**Comment by kjozwiak** [comment]
The above requires `1.70.103` or higher for `1.70.x` verification 👍

**Comment by btlechowski** [comment]
Verified with

Brave | 1.70.109 Chromium: 128.0.6613.138 (Official Build) beta (64-bit)
-- | --
Revision | fec4422ae56f4d9680c71a3c1de60b9a8e5ef32f
OS | Linux

### non-rewards - NTT enabled
<details>

![image](https://github.com/user-attachments/assets/db6b55ed-21ad-42b2-b362-c135fb05dca0)|![image](https://github.com/user-attachments/assets/36fb5b10-ed5c-4e69-af8c-10ddcedadbbe)
--|--

</details>


### non-rewards -  NTT disabled

<details>

![image](https://github.com/user-attachments/assets/c4c68a67-9dd9-48b0-9bdb-132f91305cee)|![image](https://github.com/user-attachments/assets/c3de7d6d-fe26-4781-a3e8-0ac39b974466)
--|--

</details>



### rewards - NTT enabled
<details>

![image](https://github.com/user-attachments/assets/df86384b-aa70-4334-b83a-6efeb82d0c75)|![image](https://github.com/user-attachments/assets/b34ec2b4-c68c-4e88-a3b3-9454aab75e26)|![image](https://github.com/user-attachments/assets/90149cb4-9002-4255-a8f0-f58d9b467d08)
--|--|--

</details>


### rewards -  NTT disabled

<details>

![image](https://github.com/user-attachments/assets/6f6cae4b-5ca3-431d-b25b-ed629ae697f2)|![image](https://github.com/user-attachments/assets/22173c00-ac9f-442a-bae5-b5e53bbd173b)|![image](https://github.com/user-attachments/assets/79e4f2b1-aaee-488f-b01d-b7bae4c2ba38)
--|--|--

</details>

**Comment by btlechowski** [comment]
Verification passed on Brave v1.70.114 on Lenovo TB-8506FS (Android 11.0)

### non-rewards - NTT enabled
<details>

![image](https://github.com/user-attachments/assets/643367ce-b042-48ee-b992-50718fb30fde)|![image](https://github.com/user-attachments/assets/6bbbecc8-004a-4c03-88d9-52e3217ec4a9)
--|--

</details>


### non-rewards -  NTT disabled

<details>

![image](https://github.com/user-attachments/assets/d08dc077-10fd-4a50-a249-dbe2585018f6)|![image](https://github.com/user-attachments/assets/ff8a4897-2e35-4267-9383-9ec74dbe48c8)
--|--

</details>



### rewards - NTT enabled
<details>

![image](https://github.com/user-attachments/assets/4b0a5ff4-e47d-467a-81f9-5edf02cf3f29)|![image](https://github.com/user-attachments/assets/4d682885-8263-490f-843d-347cb44fac3b)
--|--

</details>


### rewards -  NTT disabled

<details>

![image](https://github.com/user-attachments/assets/572b8928-3866-42e9-a3bf-f0b162369d45)|![image](https://github.com/user-attachments/assets/ae3017a5-c14a-43a9-b7be-b68c2214e614)
--|--

</details>
