### ISSUE TITLE
Add metric for Brave Search daily usage for iOS

### ISSUE THREAD

**Issue by iambrianfung** [brave/brave-browser#40505]
### Platforms

iOS

### Description

Support this P3A question for iOS
see: https://github.com/brave/brave-browser/issues/38117 & https://github.com/brave/brave-core/pull/23898
https://github.com/brave/brave-browser/wiki/P3A#q164-did-you-make-a-brave-search-query-today

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPhone 8 version 16.7,10` running `Brave beta 1.71 (102)`
- Verified the test plan from https://github.com/brave/brave-core/pull/25228
- Confirmed that the metrics `Brave.Search.BraveDaily` response value is `1` after performing a brave search query
![IMG_4889](https://github.com/user-attachments/assets/1ee02e53-c6fc-4acd-9622-8e758e9dcae6)
