### ISSUE TITLE
Plus sign button in tab bar is cut off [iPad]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#40500]
### Description

`+` button in tab bar is cut off as of 1.69, same on Nightly 

### Steps to reproduce

1. New install 
2. Observe tab bar on NTP 
3. 

### Actual result

1.69.x 

![IMG_1544](https://github.com/user-attachments/assets/3ed6b867-e088-454c-9ffe-0dd9d9cffe4f)

### Expected result

1.68.x

![IMG_1545](https://github.com/user-attachments/assets/3142b524-75e8-443c-9255-0d0e6d76b2fe)

### Reproduces how often

Easily reproduced

### Brave version

1.69 (147) - Reproducible
1.70 (77) - Reproducible

### Device/iOS version

iPad( 7th Gen ) | iPadOS 17.5.1

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by Brandon-T** [comment]
This is broken due to this PR: https://github.com/brave/brave-browser/issues/38789
which changed the images but didn't verify it :(

**Comment by kjozwiak** [comment]
The above requires `1.69.168` or higher for `1.69.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPad Air` using version(s):
```
Device/OS: iPad Air / iPadOS 16.7.2
Brave build: 1.69 (168)
BraveCore: 1.69.168 (128.0.6613.138)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/40500#issue-2470525744
2. Verify

**ACTUAL RESULTS:**
- Verified that `+` button is shown properly and not cut off.
- Verified that all actions tapping on `+` button wrorks as expected.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/7f06bcbb-b790-4768-b2ad-fbde3ea55f7f) | ![2](https://github.com/user-attachments/assets/09c5632c-539f-425c-90fb-5859acce41f4) | ![3](https://github.com/user-attachments/assets/b5e170af-dd01-452b-bc3f-a951fbefee20) | ![4](https://github.com/user-attachments/assets/59154a16-c5c8-4059-86ae-8169a577175a) |
