### ISSUE TITLE
[Split View]: Fix separator colors

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#40518]
Slack thread

This is a regression caused by https://github.com/brave/brave-browser/issues/40490

It happened because Chromium ColorIds and SkColors are both `int`s and we were passing a Nala color id into a map expecting a SkColor.

The fix is to use a mixer instead. This is possible because none of the Nala colors were set to fall back to a Chromium color when using a custom theme.

# Test plan
1. Open a split view.
2. The separator button should not be yellow

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.71.105 Chromium: 129.0.6668.89 (Official Build) beta (x86_64)
-- | --
Revision | f69ba167992437799f1dbcce81e90ba501a3d63e
OS | macOS Version 14.7 (Build 23H124)
```

Confirmed that split view tab separator button is not yellow.
Confirmed able to open split view menu from button.

Example | Example
--- | ---
![Image](https://github.com/user-attachments/assets/a78c8621-2517-48c9-85f6-bd38318eee2e) | ![Image](https://github.com/user-attachments/assets/8c39f14b-c903-4ebb-9605-1b5b22b6cf40)
