### ISSUE TITLE
Rewards should exclude *.local URLs from auto-contribute

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#4051]
I noticed that my printer (`holmavik.local`) shows up in my Auto-Contribute data:

![Capture d’écran du 2019-04-08 19-16-38](https://user-images.githubusercontent.com/167821/55768826-388b5c80-5a33-11e9-8f1a-d8e5648da4d4.png)

We should probably exclude all of the `*.local` URLs.

**Comment by Miyayes** [comment]
I actually think this is no longer possible since we only add verified sites now, and by definition .local cannot be verified anymore.
