### ISSUE TITLE
Cast Component is Positioned Poorly

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#4053]
After enabling "#load-media-router-component-extension", I noticed the Chromecast dialog opens on the left side of the browser window, rather than in the middle.

As a result, when the browser window is full-screen, it seems like nothing happens after selecting "Cast..."

![cast](https://user-images.githubusercontent.com/46864481/51789312-c6fb7c00-216e-11e9-9cbe-46451033e2c8.gif)

_Originally posted by @glowacky in https://github.com/brave/brave-browser/issues/209#issuecomment-457840255_

**Comment by jonathansampson** [comment]
I just came across this myself as well. I suspect the issue is that we don't render the extension icon itself, which serves as the anchor for positioning the cast component popup. Note how Edge (Chromium) handles the same action:

**Brave**

![cast-ui-location](https://user-images.githubusercontent.com/815158/55777144-a7cd7480-5a64-11e9-92d4-e14622ae4d37.gif)

**Edge (Chromium)**

![cast-ui-location-edge](https://user-images.githubusercontent.com/815158/55777146-a7cd7480-5a64-11e9-91d7-266de97cd553.gif)

**Comment by Brave-Matt** [comment]
@jonathansampson, read here:
https://github.com/brave/brave-browser/issues/209#issuecomment-459846613

**Comment by rebron** [comment]
@jonathansampson Looks like a fixed landed in Nightly builds, can you try again in a Nightly build.

**Comment by simonhong** [comment]
Fix for this was landed since 0.64 (https://github.com/brave/brave-core/pull/1836)
