### ISSUE TITLE
Nightly upgrade menu with no auto upgrade takes user to a wrong URL

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#40534]
## Description 

On Nightly, when the browser haven't been upgraded in a long time so that auto-update doesn't work any more the hamburger "Brave is out of date" menu item takes the user to brave.com/download/canary instead of brave.com/download/nightly

![image](https://github.com/user-attachments/assets/3e1f265b-cd7f-4ddc-99d2-0a027959a1e8)

This is caused by the upstream change: 
https://source.chromium.org/chromium/chromium/src/+/4272994d0429c1e4382183ecdf8e0a3fb64ed58b

This landed in cr125

**Test plan:**

1. Start brave from command line with `--simulate-outdated`
2. Open hamburger menu and click "Brave is out of date"

   **Observe:**
   https://brave.com/download/canary/ is opened

   **Expected result:**
   https://brave.com/download-nightly is opened

Also, please verify that on beta https://brave.com/download-beta is opened and on stable https://brave.com/download is opened.

**Comment by kjozwiak** [comment]
The above requires `1.69.150` or higher for `1.69.x` verification 👍 @LaurenWags we should probably check this on both `Windows` & `macOS`.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.69.150 Chromium: 128.0.6613.40 (Official Build) (64-bit)
-- | --
Revision | aea36034a3cccd841545ac66ffb79f21e2ba5dd4
OS | Windows 10 Version 22H2 (Build 19045.4780)
```
Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/40534#issue-2473700047, ensured that clicking on `Brave is out of date` via the `Hamburger Menu` opened https://brave.com/download/ as per the following:

![update](https://github.com/user-attachments/assets/29063429-f9a0-4c02-b998-1a6075789f33)
