### ISSUE TITLE
Make sure Omaha 4 Griffin flag works for system-wide installations

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#40530]
In #40528, we introduced a Griffin flag that makes it possible to switch to the new auto-update implementation based on Omaha 4 for per-user installations. The present issue is a follow-up for system-wide installations. This is the typical case for the PKG installer.

Specifically: The goal of this present issue is for system-wide Brave to be able to auto-update via Omaha 4. Brave is "system-wide" when the owner of the installation directory (typically `/Applications/Brave Browser.app`.) is not the user that runs Brave.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.72.85 Chromium: 130.0.6723.58 (Official Build) beta (x86_64)
-- | --
Revision | 2c872aa4d2694bc73ec58e3b14538a4008a6381e
OS | macOS Version 14.7 (Build 23H124)
```

and

```
Brave | 1.72.87 Chromium: 130.0.6723.70 (Official Build) beta (x86_64)
-- | --
Revision | d7efa3dbae2fa83142b51cea45f023f01d3eeb33
OS | macOS Version 14.7 (Build 23H124)
```

Verified test plan from https://github.com/brave/brave-core/pull/25796#issue-2563339452.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.72.90 Chromium: 130.0.6723.70 (Official Build) beta (arm64) 
Revision	5f14a2225ebf4fcd654e064bde93e77fcc5d8f39
OS	macOS Version 15.1 (Build 24B82)
```
