### ISSUE TITLE
Add metric for Ads clear data action

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#40548]
Add metric for the "Clear Brave Ads Data" action in the browser history deletion dialog:

Did you delete your Brave Ads Data this week?

1. Yes

cc @aseren

**Comment by LaurenWags** [comment]
Requires `1.70.88` or higher for testing 👍🏻

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.70.88 Chromium: 128.0.6613.85 (Official Build) beta (64-bit)
-- | --
Revision | 7431803bd1e909ef82982df42e2ea7aacbad755e
OS | Windows 10 Version 22H2 (Build 19045.4780
```

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung galaxy S3 version 12` running `Bravemonoarm64.apk_1.70.92`

- Verified the test plan from https://github.com/brave/brave-core/pull/25209#issue-2474512138

<details>
<summary>Brave.Ads.ClearData = 0_PASSED</summary>

1. Clean profile `1.70.88`
2. Open brave://local-state
3. Look for the metrics `Brave.Ads.ClearData`
4. Confirmed that the metrics isn't shown on the local state file
![Screenshot_20240828_105803_Brave - Beta](https://github.com/user-attachments/assets/cece8bb8-fd9d-40d3-b522-ec77d2e7d40f)


</details>

<details>
<summary>Brave.Ads.ClearData = 1_PASSED</summary>

1. Clean profile `1.70.88`
2. Open brave://settings/clearBrowserData and click on "Clear Brave Ads Data" link
3. Open brave://local-state
4. Confirmed that the metrics `Brave.Ads.ClearData` response value is `1` as expected

step 2 | step 4
--------|-------
![Screenshot_20240828_105830_Brave - Beta](https://github.com/user-attachments/assets/d4fc00bd-ca90-4bda-9baf-37f0943acaf1) | ![Screenshot_20240828_105852_Brave - Beta](https://github.com/user-attachments/assets/482d2972-69b8-4c17-a5b4-10c623c8d8c9)



</details>

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPhone 8 Version 16.7.10` running `Bravemonoarm64.apk_1.70.92`

- Verified the test plan from https://github.com/brave/brave-core/pull/25209#issue-2474512138

<details>
<summary>Brave.Ads.ClearData = 0_PASSED</summary>

1. Clean profile `1.70.88`
2. Open brave://local-state
3. Look for the metrics `Brave.Ads.ClearData`
4. Confirmed that the metrics isn't shown on the local state file
![Screenshot_20240828_105803_Brave - Beta](https://github.com/user-attachments/assets/cece8bb8-fd9d-40d3-b522-ec77d2e7d40f)


</details>

<details>
<summary>Brave.Ads.ClearData = 1_PASSED</summary>

1. Clean profile `1.70.88`
2. Open brave://settings/clearBrowserData and click on "Clear Brave Ads Data" link
3. Open brave://local-state
4. Confirmed that the metrics `Brave.Ads.ClearData` response value is `1` as expected

step 2 | step 4
--------|-------
![Screenshot_20240828_105830_Brave - Beta](https://github.com/user-attachments/assets/d4fc00bd-ca90-4bda-9baf-37f0943acaf1) | ![Screenshot_20240828_105852_Brave - Beta](https://github.com/user-attachments/assets/482d2972-69b8-4c17-a5b4-10c623c8d8c9)



</details>
