### ISSUE TITLE
Merriam-Webster Resources Blocked

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#4054]
## Description 
First-party resources are blocked on www.merriam-webster.com in some builds of Brave.

![image](https://user-images.githubusercontent.com/815158/55780694-31ce0b00-5a6e-11e9-8707-1ea3cdac9301.png)

## Steps to Reproduce
1. Navigate to www.merriam-webster.com

## Actual result:
The following resources are being blocked:

- https://www.merriam-webster.com/assets/mw/app-bundles/mw-2019-04-08.11-29-23.000000-app-bundle/css/style-dsp-redesign-definitions-defer.min.css
- https://www.merriam-webster.com/assets/mw/app-bundles/mw-2019-04-08.11-29-23.000000-app-bundle/css/style-dsp-redesign-definitions.min.css
- https://js-sec.indexww.com/ht/htw-merriam-webster.js
- https://www.merriam-webster.com/assets/mw/static/shared/mw-shared/js/onetrust/onetrust.min.js
- https://www.merriam-webster.com/assets/mw/app-bundles/mw-2019-04-08.11-29-23.000000-app-bundle/js/main.dsp-redesign-definitions.min.js
- https://www.merriam-webster.com/assets/mw/static/app-standalone-images/MW_logo.png
- https://www.merriam-webster.com/images/audio.svg
- https://www.merriam-webster.com/images/show-more.svg
- https://www.merriam-webster.com/images/show-less.svg
- https://www.merriam-webster.com/images/social-icons/facebook.svg
- https://www.merriam-webster.com/images/social-icons/twitter.svg
- https://www.merriam-webster.com/images/social-icons/time-traveler.svg
- https://www.merriam-webster.com/images/social-icons/double-arrows.svg
- https://c.amazon-adsystem.com/aax2/apstag.js
- https://cdn.heapanalytics.com/js/heap-537798487.js
- https://www.merriam-webster.com/favicon.png

## Expected result:
First-party content (particularly images) should not be blocked.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
0.63.34

### Reproducible on current release:
The issue does not reproduce on 0.62.51, but does reproduce on 0.63.34.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome?  No.

### Additional Information
Originally reported [on Twitter](https://twitter.com/pivic/status/1115500831963529216):

![image](https://user-images.githubusercontent.com/815158/55780257-29290500-5a6d-11e9-9f9b-8bb10fca2708.png)

**Comment by jonathansampson** [comment]
For comparison, here is the output when viewing the same resource in Chrome with uBlock Origin 1.18.16:

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +0 |  |  | `www.merriam-webster.com` | 1 | image | `https://www.merriam-webster.com/favicon.png` |
| +0 |  |  | `www.merriam-webster.com` | 1 | image | `https://www.merriam-webster.com/favicon.png` |
| +0 | ##.abl |  | `www.merriam-webster.com` |  | dom | `https://www.merriam-webster.com/dictionary/nuance` |
| +0 | \|\|stats.merriam-webster.com^ | -- | `www.merriam-webster.com` | 1 | xhr | `https://stats.merriam-webster.com/tally.php?word=nuance&t=1554791010` |
| +0 | /stats/lookup? | -- | `www.merriam-webster.com` | 1 | xhr | `https://www.merriam-webster.com/lapi/v1/mwol-search/stats/lookup?rp=dictionary&usp=nuance&r=&ua=Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F73.0.3683.86%20Safari%2F537.36` |
| +0 |  |  | `www.merriam-webster.com` | 1 | xhr | `https://www.merriam-webster.com/images/audio.svg` |
| +0 |  |  | `www.merriam-webster.com` | 1 | xhr | `https://www.merriam-webster.com/images/show-less.svg` |
| +0 |  |  | `www.merriam-webster.com` | 1 | xhr | `https://www.merriam-webster.com/images/show-more.svg` |
| +0 |  |  | `www.merriam-webster.com` | 1 | xhr | `https://www.merriam-webster.com/images/audio.svg` |
| +0 |  |  | `www.merriam-webster.com` | 1 | xhr | `https://www.merriam-webster.com/images/social-icons/double-arrows.svg` |
| +0 |  |  | `www.merriam-webster.com` | 1 | xhr | `https://www.merriam-webster.com/images/social-icons/time-traveler.svg` |
| +0 |  |  | `www.merriam-webster.com` | 1 | xhr | `https://www.merriam-webster.com/images/social-icons/twitter.svg` |
| +0 |  |  | `www.merriam-webster.com` | 1 | xhr | `https://www.merriam-webster.com/images/social-icons/facebook.svg` |
| +0 |  |  | `www.merriam-webster.com` | 1 | xhr | `https://www.merriam-webster.com/images/show-less.svg` |
| +0 |  |  | `www.merriam-webster.com` | 1 | xhr | `https://www.merriam-webster.com/images/show-more.svg` |
| +0 |  |  | `www.merriam-webster.com` | 1 | xhr | `https://www.merriam-webster.com/images/show-less.svg` |
| +0 |  |  | `www.merriam-webster.com` | 1 | xhr | `https://www.merriam-webster.com/images/show-more.svg` |
| +0 |  |  | `www.merriam-webster.com` | 1 | xhr | `https://www.merriam-webster.com/images/audio.svg` |
| +0 |  |  | `www.merriam-webster.com` | 1 | xhr | `https://www.merriam-webster.com/images/audio.svg` |
| +0 | \|\|stats.merriam-webster.com^ | -- | `www.merriam-webster.com` | 1 | script | `https://stats.merriam-webster.com/pop-score-redesign.php?id=popularity-score&word=nuance&t=1554794302783&_=1554794302685` |
| +0 | google-analytics.com/analytics.js | << | `www.merriam-webster.com` |  | script | `https://www.google-analytics.com/analytics.js` |
| +0 | \|\|google-analytics.com^ | -- | `www.merriam-webster.com` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +0 |  |  | `www.merriam-webster.com` | 1 | inline-script | `https://www.merriam-webster.com/dictionary/nuance` |
| +0 |  |  | `www.merriam-webster.com` | 3 | script | `https://geolocation.onetrust.com/cookieconsentpub/v1/geo/countries/EU?callback=jQuery3310289762724952076_1554794302683&_=1554794302684` |
| +0 |  |  | `www.merriam-webster.com` | 3 | css | `https://cdn.cookielaw.org/skins/4.4.0/default_flat_bottom_two_button_black/v2/css/optanon.css` |
| +0 | \|\|heapanalytics.com^ | -- | `www.merriam-webster.com` | 3 | script | `https://cdn.heapanalytics.com/js/heap-537798487.js` |
| +0 | \|\|amazon-adsystem.com^ | -- | `www.merriam-webster.com` | 3 | script | `https://c.amazon-adsystem.com/aax2/apstag.js` |
| +0 |  |  | `www.merriam-webster.com` | 1 | image | `https://www.merriam-webster.com/images/social-icons/double-arrows.svg` |
| +0 |  |  | `www.merriam-webster.com` | 1 | image | `https://www.merriam-webster.com/images/social-icons/time-traveler.svg` |
| +0 |  |  | `www.merriam-webster.com` | 1 | image | `https://www.merriam-webster.com/images/social-icons/twitter.svg` |
| +0 |  |  | `www.merriam-webster.com` | 1 | image | `https://www.merriam-webster.com/images/social-icons/facebook.svg` |
| +0 |  |  | `www.merriam-webster.com` | 1 | image | `https://www.merriam-webster.com/images/show-less.svg` |
| +0 |  |  | `www.merriam-webster.com` | 1 | image | `https://www.merriam-webster.com/images/show-more.svg` |
| +0 |  |  | `www.merriam-webster.com` | 1 | image | `https://www.merriam-webster.com/images/audio.svg` |
| +0 | ##+js(abort-on-property-write.js, adonisHash) |  | `www.merriam-webster.com` |  | dom | `https://www.merriam-webster.com/dictionary/nuance` |
| +0 | googletagservices.com/gpt.js | << | `www.merriam-webster.com` |  | script | `https://www.googletagservices.com/tag/js/gpt.js` |
| +0 | \|\|googletagservices.com/tag/js/gpt.js$script | -- | `www.merriam-webster.com` | 3 | script | `https://www.googletagservices.com/tag/js/gpt.js` |
| +0 | \|\|indexww.com^ | -- | `www.merriam-webster.com` | 3 | script | `https://js-sec.indexww.com/ht/htw-merriam-webster.js` |
| +0 |  |  | `www.merriam-webster.com` | 1 | css | `https://www.merriam-webster.com/assets/mw/app-bundles/mw-2019-04-08.11-29-23.000000-app-bundle/css/style-dsp-redesign-definitions.min.css` |
| +0 |  |  | `www.merriam-webster.com` | 1 | css | `https://www.merriam-webster.com/assets/mw/app-bundles/mw-2019-04-08.11-29-23.000000-app-bundle/css/style-dsp-redesign-definitions-defer.min.css` |
| +0 |  |  | `www.merriam-webster.com` | 3 | css | `https://fonts.googleapis.com/css?family=Lato:300,400,700\|Open+Sans:300,300i,400,400i,600,700,700i\|Playfair+Display:400,700,700i` |
| +0 | \|\|merriam-webster.com^$csp=script-src 'self' * 'unsafe-inline' | -- | `www.merriam-webster.com` | 1 | csp | `https://www.merriam-webster.com/dictionary/nuance` |
| +0 |  |  | `www.merriam-webster.com` | 1 | doc | `https://www.merriam-webster.com/dictionary/nuance` |

**Comment by Brave-Matt** [comment]
+1 community:
https://community.brave.com/t/https-www-merriam-webster-com-ad-blocker-wrecked-the-site/56505/4

**Comment by bbondy** [comment]
Fixed here:
https://github.com/brave/ad-block/commit/03c18b34f071919bf28725f084bf13dd2105ab4b

Turns out to be a parsing bug only, and we don't parse from our clients (we only deserialize), so I was able to fix it by just re-generating the lists.  If you don't see it working, just restart your browser and that should force an update check for the new serialized list.
