### ISSUE TITLE
Crash Report: crash on last tab closure

### ISSUE THREAD

**Issue by davidgross** [brave/brave-browser#40557]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.68.141 Chromium: 127.0.6533.120
Operating System: Linux 5.15.0-118-generic

URL (if applicable) where crash occurred:

Can you reproduce this crash? yes, 100% of the time.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. open brave, open a website, open a new tab, pull it out of the first window
2. close the new separate tab
3. brave crashes, when reopening you get both tabs.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/32440100-ee7a-7a0c-0000-000000000000

**Comment by iefremov** [comment]
please update and retest, it should've been fixed
