### ISSUE TITLE
DHL preventing Brave from loading ticket numbers

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#40568]
### Description

Blank info when user loads ticket info from DHL.

### Steps to reproduce

1. Clear cookies
2. Open sample https://mydhl.express.dhl/us/en/tracking.html#/results?id=234234234234 (needs valid number)
3. Expect results 

### Actual result

Ticket info not loaded. Empty details.

### Expected result

Load ticket info

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

All Brave versions affected 

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

FIngerprinting (Screen) causing it.

**Comment by arthuredelstein** [comment]
Now that we are rolling out the Webcompat Exceptions Manager in Release to 100%, this is fixed.
