### ISSUE TITLE
Add NTP widget, search suggestion setting and theme metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#40569]
Add the following metrics:

What color mode are you using? (reported monthly)
`Brave.Theme.BrowserColorScheme`

0. OS default
1. Dark
2. Light

Are you using the default theme colors? (reported monthly)
`Brave.Theme.ThemeColorDefault`

0. No
1. Yes

Do you have "Show search suggestions" enabled? (reported monthly)
`Brave.Search.SearchSuggest`

0. No
1. Yes

Did you make a Google query using the NTP search widget this week? (weekly cadence)
`Brave.Search.GoogleWidgetUsage`

1. Yes

cc @rebron

**Comment by kjozwiak** [comment]
The above requires `1.69.156` or higher for `1.69.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.69.156 Chromium: 128.0.6613.85 (Official Build) (64-bit)
-- | --
Revision | 1d701f8c67ab98b8c562ddd0fa2dafc1305f8605
OS | Windows 10 Version 22H2 (Build 19045.4780)
```
