### ISSUE TITLE
Pin STAR P3A hostnames

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#40566]
The following hosts should have been added to our pin list as part of https://github.com/brave/brave-browser/issues/24338:
- https://collector.bsg.brave.com/
- https://star-randsrv.bsg.brave.com/

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.71.101 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | 734075a5959db3e93d6def81a15e1fc6c2609fc2
OS | Windows 10 Version 22H2 (Build 19045.4894)
```
- Verified the test plan from https://github.com/brave/brave-core/pull/25233
- Confirmed that Click on the following two URLs doesn't throw any error, just a line or two of text is displayed as expected
   https://collector.bsg.brave.com/
   https://star-randsrv.bsg.brave.com/

![image](https://github.com/user-attachments/assets/8e7a6925-2637-4f03-81d3-f1e446b16cb7)

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.71.104 x64 Beta build
- Verified steps from [brave/brave-core#25233](https://github.com/brave/brave-core/pull/25233)
- Verified clicking/visiting `https://collector.bsg.brave.com` loads text 
- Encountered issue when visiting `https:?/star-randsrv.bsg.brave.com` on all browsers and not specific to Brave

https://github.com/user-attachments/assets/c85aa8dd-e211-482e-bab6-ee9523fc9821

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7
Brave build: 1.71 (116)
BraveCore: 1.71.116 (130.0.6723.58)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/25233#issue-2476580824
2. *Verify*

**ACTUAL RESULTS:**
- Verified that no errors were observed when navigating to https://collector.bsg.brave.com/ 
- Verified that no errors were observed when navigating to https://star-randsrv.bsg.brave.com/

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/b16c156a-50b9-4ed4-be60-e23e72eb6f01) | ![2](https://github.com/user-attachments/assets/8b2237a5-5324-4b77-bfc3-b549dbaf2d47) |
