### ISSUE TITLE
🌑Dark theme persists in UI after switching back to Light🌕

### ISSUE THREAD

**Issue by InternetJohnny** [brave/brave-browser#4056]
## Description 
Having enabled 🌑dark theme and gone back to using the 🌕light theme, some elements of the UI remain themed dark🌑 - settings dropdown, permissions alert box (notifications, location, etc) - while the address bar and tabs have the proper 🌕light theme.

## Steps to Reproduce

   1.  Switch to dark theme 🌑
   2.  Switch back to light theme 🌕

## Actual result:

<img src="https://i.imgur.com/j7f9R3c.png">

## Expected result:
Consistent theme throughout the UI (either all dark or all light)

## Reproduces how often: 

Happens every time on my laptop and not at all on my desktop (quite weird because I installed the same version of the Beta, from scratch, on both machines.

## Brave version (brave://version info)

Brave | 0.63.34 Chromium: 74.0.3729.40 (Official Build) beta (64-bit)
-- | --
Revision | 278d6a0d856d8314f36fb9a68b6e1d85cd0d14e7-refs/branch-heads/3729@{#470}
OS | Windows 10 OS Build 17763.379
JavaScript | V8 7.4.288.13

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
It is happening on the Beta for me

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
Chrome does not have a dark theme

**Comment by bsclifton** [comment]
cc: @petemill @simonhong

**Comment by InternetJohnny** [comment]
Ok, so I actually managed to find out a bit more about its behavior.

It seems like every element of the Brave UI except for the address/tabs bar at the top follows (is controlled by) the Windows setting for the UI theme (dark/light).

Here's an example of this:
<img src="https://media.giphy.com/media/ZFKqRhNSm4aN6lZf1R/source.gif">

Basically, if your Brave theme is set to 'light' 🌕, but the Windows theme is set to 'dark' 🌑, your addres/tabs bar will be light, but the rest of the Brave UI will be dark.

**Comment by rebron** [comment]
cc: @srirambv to try to reproduce on Windows.

**Comment by simonhong** [comment]
Aligning base UI theme(ex, context menu) with brave theme is not implemented on Windows for now.
On MacOS, we did this by changing app appearance when brave theme and OS theme are different.
With this, we can use different app appearance than MacOS theme.
However, we can't apply this approach on Windows because Windows doesn't support per-app appearance. Need to find different approach for Windows.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.66.87 Chromium: 75.0.3770.80 (Official Build) beta (64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Windows 7 Service Pack 1 (Build 7601.24465)

Verified test plan from https://github.com/brave/brave-core/pull/2352 and from the description. Checked changing Light->Dark mode and Dark->Light mode. Checked settings dropdown and permissions alert box (notifications, geolocation, translations, alerts). Also checked `Same as Windows` option.
