### ISSUE TITLE
[Android] Update foregroundServiceType for VPN

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#40571]
## Description 

We have a new change coming with Android 15 related to foreground services https://developer.android.com/about/versions/15/behavior-changes-15#datasync-timeout. 
We use it for VPN, the main change is that Android OS won't allow to run it for more than 6 hours in 24 hours (unless the user interacts with the app, resetting the timer).

Solution : We can use https://developer.android.com/about/versions/14/changes/fgs-types-required#system-exempted as it's ideal for VPN apps.

**Comment by kjozwiak** [comment]
Labelling as `QA/No` as discussed with @deeppandya. The above was reverted via https://github.com/brave/brave-core/issues/25456. The whole VPN feature including the new Server/City selection will be verified alongside https://github.com/brave/brave-browser/issues/36277 👍
