### ISSUE TITLE
Leo - Edit answers - Icon shouldn't be available as a quick action

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#40576]
### Description

The quick action buttons of each answer shouldn't show the edit button. It should only be accessible from within the menu.

Quick actions are supposed to be:

**Prompt**: Copy / Edit / More
**Answer**: Copy / Regenerate / More

https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/%F0%9F%94%84-Leo-%5BIN-PROGRESS%5D?node-id=6487-102417&t=Zo61J54m8f98P5CV-1

### Actual result

![image](https://github.com/user-attachments/assets/46a9da92-97e1-4670-8d84-83c40858b74a)

### Quick actions menu for edit:
![image](https://github.com/user-attachments/assets/e01a6e74-2a4e-400f-91ff-9e53c0471bea)

[Edited by Jocelyn]: Split out the label alignment issue to a new issue.

**Comment by kjozwiak** [comment]
The above requires `1.70.115` or higher for `1.70.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.70.115 Chromium: 129.0.6668.59 (Official Build) (64-bit) 
-- | --
Revision | 031813a4ca3b5401db1aba5c85c164084a8d761a
OS | Windows 11 Version 23H2 (Build 22631.4169)

- Verified steps from [ brave/brave-core#25564](https://github.com/brave/brave-core/pull/25564)
- Verified edit answer is now shown under menu for server replies
- Verified able to edit the server response and save it 
- Verified edited label is added to the server response when its updated correctly 

https://github.com/user-attachments/assets/14265207-1e6c-48d9-b797-428c8b03c653
