### ISSUE TITLE
[iOS] Update User Agent to 17.6

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#40578]
### Description

Update the iOS 17 user agent to 17.6

Currently we hardcode the user agent to 17.5 when on iOS 17 which can cause issues for some alternative app stores which require 17.6+

**Comment by kjozwiak** [comment]
@Uni-verse @hffvld we should also check `iOS 16` and ensure we're using the correct UA alongside `iOS 17` 👍

**Comment by kjozwiak** [comment]
The above requires `1.69.157` or higher for `1.69.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.6.1` using version `1.69 (162)`

- Ensured that UA is updated to 17.6+

1.68 | 1.69
-|-
<img width="939" alt="Screenshot 2024-09-04 at 4 24 23 PM" src="https://github.com/user-attachments/assets/358dd439-5d69-48c2-9983-208e25794362"> | <img width="952" alt="Screenshot 2024-09-04 at 4 26 11 PM" src="https://github.com/user-attachments/assets/0774555f-f126-41ac-a933-366460fb026b">

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7.8` running `1.69 (162)`

- Ensured that User Agent is set to `16.6` for iOS 16 devices

<img width="962" alt="Screenshot 2024-09-04 at 6 03 01 PM" src="https://github.com/user-attachments/assets/56541035-ed2e-43bd-8934-7b2011bad549">
