### ISSUE TITLE
[cr128] wrong sunglasses icon at incognito mode

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#40584]
### Description

Atter cr128 the sunglasses icon at the incognito tab switcher is not replaced with Brave's one.

### Steps to reproduce

1. Press `New Private tab`
2. Press tab switcher button
3. See the wrong icon of sunglasses 

### Actual result

![image](https://github.com/user-attachments/assets/482daa98-03a4-4dcf-a265-bf5517a970ba)

### Expected result

![image](https://github.com/user-attachments/assets/29d9b11b-0bed-4ada-93d8-3f3a064f9868)

### Reproduces how often

Easily reproduced

### Brave version

Nightly 1.71.12
Beta 1.70.80

### Device

- Brand/model: any
- Android version: any

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP31.240617.010 release-keys
Brave build: 1.69.156
Chromium: 128.0.6613.85 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/40584#issue-2478518299
2. *Verify*

**ACTUAL RESULTS:**
- Verified that Brave's version of `sunglasses` is shown on tab switching screen

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/a26f4738-1d08-4488-a212-59f8dd714328) | ![2](https://github.com/user-attachments/assets/90964f01-3181-4dc6-ab0b-374f4b72f1d1) |
