### ISSUE TITLE
[cr128] New tab at bottom toolbar at incognito opens normal tab

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#40583]
### Description

cr128 regression. New tab button at the bottom toolbar at incognito mode opens a normal tab instead of the incognito tab.

### Steps to reproduce

1. Press app menu => `New Private tab`
2. Press tab switch button at the bottom toolbar
3. Press plus button at the bottom toolbar

### Actual result

Regular tab is open

### Expected result

Incognito tab must be open

### Reproduces how often

Easily reproduced

### Brave version

Nightly `1.71.12` 
Beta `1.70.80`

### Device

- Brand/model: any 
- Android version:  any

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.69.153` or higher for `1.69.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using version: 

```
Brave	1.69.153 Chromium: 128.0.6613.85 (Official Build) (64-bit) 
Revision	a69e96756922f88cbce3482971d70cfd1ee6f872
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Using STR in https://github.com/brave/brave-browser/issues/40583#issue-2478506729, ensured that tab is opened in Private mode when using the plus sign on the bottom bar. 
- Ensured `New Private tab` in menu opens tab in incognito mode.
- Ensured that `New tab` in menu will still open normal tab.

Example | Example | Example
-|-|-
![Screenshot 2024-08-22 at 10 35 04 AM](https://github.com/user-attachments/assets/7d6d2cf0-4dc7-4d56-ab5f-7aa294c40bad) | ![Screenshot 2024-08-22 at 10 35 11 AM](https://github.com/user-attachments/assets/5d06dc42-d04f-4341-9609-5fbc9d0bf254) | ![Screenshot 2024-08-22 at 10 35 22 AM](https://github.com/user-attachments/assets/a5ef130b-6ff2-4c91-817c-c0c58b7b262d)
![Screenshot 2024-08-22 at 10 44 36 AM](https://github.com/user-attachments/assets/1573df56-3403-46d0-a839-9e79438fe5ef) | ![Screenshot 2024-08-22 at 10 44 46 AM](https://github.com/user-attachments/assets/49cb1f82-950d-4865-b66f-479a7fcbafc7) | ![Screenshot 2024-08-22 at 10 45 19 AM](https://github.com/user-attachments/assets/4eb7ec53-a795-4279-b08c-2528dc932499)
