### ISSUE TITLE
[C128] Tab strip disappears after going fullscreen and then restoring with vertical tabs (macOS)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#40587]
### Description

When vertical tabs are enabled, going fullscreen on macOS seems to cause a massive problem.

The tab strip seems to be hidden. The tabs are still there! If you close the browser and re-open, you still have the open tabs.

### Steps to reproduce

1. Using latest Nightly (1.71) or Beta (1.70) w/ Chromium 128
2. Vertical tabs enabled
3. Have several open tabs
4. Maximize the window (green button)
5. Seems fine; tab contents is fullscreen
6. Click maximize again (green button) to restore

### Actual result

- Looks like I lost all my tabs 🙀 Tab strip is gone
- Graphical glitches

![image](https://github.com/user-attachments/assets/f34eb331-1a37-4241-99e5-2ded89756581)

### Expected result

shouldn't happen

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Latest Nightly

### Channel information

- [ ] release (stable)
- [x] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by bsclifton** [comment]
Removed release blocking - we can disable the feature (see https://github.com/brave/brave-browser/issues/40587) and the circle back on the real fix for this 😄

**Comment by kjozwiak** [comment]
The above requires `1.69.153` or higher for `1.69.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```

```

Reproduced the issue using `1.69.149 Chromium: 128.0.6613.40 (Official Build) (x86_64)` and STR from https://github.com/brave/brave-browser/issues/40587#issue-2479280738. Noticed missing tabs both during and after going full screen:

Example | Example
--- | ---
<img width="1368" alt="Screenshot 2024-08-22 at 8 18 25 AM" src="https://github.com/user-attachments/assets/9d199908-d7ab-4cce-acc0-a6621b6f81ad"> | <img width="927" alt="Screenshot 2024-08-22 at 8 18 41 AM" src="https://github.com/user-attachments/assets/ce809f2a-0aca-40b7-8661-d1adaaee4aab">
