### ISSUE TITLE
Wrong colors when changing system colors to `Light`

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#4059]
Follow up to https://github.com/brave/brave-browser/issues/3881

## Steps to Reproduce

   1. Change system colors to `Dark`
   2. Clean install Brave
   3. Go to `brave://settings/`
   4. Change `Brave colors` to `Same as Windows`
5. Change system colors to `Light`

## Actual result:

![image](https://user-images.githubusercontent.com/34715963/55842762-33aed180-5b35-11e9-9719-91bd763430af.png)

IMPORTANT: Browser restart fixes the issue

## Expected result:
![image](https://user-images.githubusercontent.com/34715963/55842773-3b6e7600-5b35-11e9-9a33-22ca247a2af4.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.63.35 Chromium: 74.0.3729.61 (Official Build) beta (64-bit)
-- | --
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Windows 10 OS Build 17134.523

cc @brave/legacy_qa @petemill @simonhong

**Comment by kjozwiak** [comment]
Looks like we'll want to get this fixed in `0.63.x` before it makes it into the release channel.

**Comment by rebron** [comment]
related to #4056 it looks like.

**Comment by rebron** [comment]
@simonhong Can we include this for 64.x/65.x too?

**Comment by simonhong** [comment]
@rebron yep, I already pushed two uplift PRs.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.65.92 Chromium: 74.0.3729.131 (Official Build) beta (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.523

- Verified the STR mentioned in the description
