### ISSUE TITLE
Add metric for first page load time

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#40590]
Add the following weekly ephemeral metric:

If you are a first-time user this week and you viewed at least one page, how long after the install time did you view your first web page?
`Brave.Core.FirstPageLoadTime`

0. 0-5 minutes
1. 6-10 minutes
2. 11 minutes - 1 hour
3. 1 hour - 4 hours
4. 4 hours - 1 day
5. Greater than a day

cc @rebron @timchilds @chrismore

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.71.101 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | 734075a5959db3e93d6def81a15e1fc6c2609fc2
OS | Windows 10 Version 22H2 (Build 19045.4894)
```

<details>
<summary>Brave.Core.FirstPageLoadTime_0</summary>

</details>

<details>
<summary>Brave.Core.FirstPageLoadTime_1</summary>

</details>

<details>
<summary>Brave.Core.FirstPageLoadTime_2</summary>

</details>

<details>
<summary>Brave.Core.FirstPageLoadTime_3</summary>

</details>

<details>
<summary>Brave.Core.FirstPageLoadTime_4</summary>

</details>

<details>
<summary>Brave.Core.FirstPageLoadTime_5</summary>

</details>

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung galaxy version 12` running `Bravemonoarm64.apk_1.71.112`



- Verified the test plan from https://github.com/brave/brave-core/pull/25273

<details>
<summary>Brave.Core.FirstPageLoadTime_0_PASSED</summary>

1. Install profile 1.71.x
2. Open brave://settings
3. Open brave://local-state
4. Look for the metrics `Brave.Core.FirstPageLoadTime` and confirmed that metrics is not found 
5. Open any webpage 
6. Reload brave://local-state
7. Confirmed that the metrics `Brave.Core.FirstPageLoadTime` response value is `0` as expected

![image](https://github.com/user-attachments/assets/d7cc30c4-ba33-461a-b363-b3a8f7a54f23)

</details>

<details>
<summary>Brave.Core.FirstPageLoadTime_1_PASSED</summary>

1. Install profile 1.71.77
2. Keep open the browser between the time range `6-10 minutes`
3. After one hour open brave://settings page
4. Open brave://local-state file
5. Look for the metrics `Brave.Core.FirstPageLoadTime` and confirmed that metrics is not found 
6. Visit any website (e.g brave.com)
7. Reload brave://local-state
8. Confirmed that the metrics `Brave.Core.FirstPageLoadTime` response value is 2 as expected 

![Image](https://github.com/user-attachments/assets/0dd20103-2316-46a5-85ce-1fb92aac1f13)

</details>

<details>
<summary>Brave.Core.FirstPageLoadTime_2_PASSED</summary>

1. Install profile 1.71.77
2. Keep open the browser between the time range `11 minutes - 1 hour`
3. Open brave://settings page
4. Open brave://local-state file
5. Look for the metrics `Brave.Core.FirstPageLoadTime` and confirmed that metrics is not found 
6. Visit any website (e.g brave.com)
7. Reload brave://local-state
8. Confirmed that the metrics `Brave.Core.FirstPageLoadTime` response value is 2 as expected

 ![Image](https://github.com/user-attachments/assets/fce8907d-6ce4-46e6-923f-bd40f1297e7c)

</details>

<details>
<summary>Brave.Core.FirstPageLoadTime_3_PASSED</summary>

1. Install profile 1.71.77
2. Keep open the browser for 1 hour
3. After one hour open brave://settings page
4. Open brave://local-state file
5. Look for the metrics `Brave.Core.FirstPageLoadTime` and confirmed that metrics is not found 
6. Visit any website (e.g brave.com)
7. Reload brave://local-state
8. Confirmed that the metrics `Brave.Core.FirstPageLoadTime` response value is 3 as expected 

![Image](https://github.com/user-attachments/assets/d8c318a6-8415-407b-9150-d1bfbc596332)
</details>

<details>
<summary>Brave.Core.FirstPageLoadTime_4_PASSED</summary>

1. Install profile 1.71.77
2. Close the browser and set the sys date ahead by 4 hours to 1 day
3. Relaunch the browser
4. Open brave://settings page
5. Open brave://local-state file
6. Look for the metrics `Brave.Core.FirstPageLoadTime` and confirmed that metrics is not found 
7. Visit any website (e.g brave.com)
8. Reload brave://local-state
9. Confirmed that the metrics `Brave.Core.FirstPageLoadTime` response value is 4 as expected 

![Image](https://github.com/user-attachments/assets/a53b29eb-534d-40be-871b-362698ff0cc9)


</details>

<details>
<summary>Brave.Core.FirstPageLoadTime_4_metrics doesn't exist_PASSED</summary>

1. Install profile 1.71.77
2. Close the browser and set the sys date ahead by 8 days
3. Relaunch the browser
4. Open brave://settings page
5. Open brave://local-state file
6. Look for the metrics `Brave.Core.FirstPageLoadTime` and confirmed that metrics is not found 
7. Visit any website (e.g brave.com)
8. Reload brave://local-state
9. Confirmed that the metrics `Brave.Core.FirstPageLoadTime` doesn't exists in the local state file

![Image](https://github.com/user-attachments/assets/e47fb0b3-8dba-44b7-b867-b9c7cc69d482)

</details>
