### ISSUE TITLE
After the latest update, google spreadsheet shows unsupported error

### ISSUE THREAD

**Issue by bondeabhijeet** [brave/brave-browser#40607]
### Description

After updating to the latest version (1.69.153) Chromium 128.0.6613.85 docs.google.com has started to show an error message

"The version of the browser you are using is no longer supported. Please upgrade to a supported version"

### Steps to reproduce

1. Update the browser to the latest update
2. open docs.google.com and open a spreadsheet

### Actual result

![image](https://github.com/user-attachments/assets/aef5de08-c12a-492b-a48d-331d07b26369)

### Expected result

The error must not have been there after the update

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.153 Chromium: 128.0.6613.85 (Official Build) (64-bit) 

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment]
@bondeabhijeet I'm not able to reproduce this. Are you using an extension or changing Brave's user agent somewhere.

cc: @ryanbr to double check

**Comment by bondeabhijeet** [comment]
That's totally my mistake, Thanks for reminding me about the user-agents, I today turned on the windscribe's "split personality" and I totally forgot that it might have been causing this issue. That setting was changing the user-agent to android user agent. 

Thanks.
