### ISSUE TITLE
[ads] NTT video background may be blank after changing NTP media type.

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#40605]
### Steps to reproduce

1. Go to Settings -> New Tab Page -> Media Type and change type to `Sponsored Images`
2. Close Settings
3. Open several tabs
4. Go to Settings -> New Tab Page -> Media Type and change type to `Sponsored Images & Videos`
5. Close Settings

### Actual result

Sometimes NTT video background is empty (but CTA logo is shown)

### Expected result

NTT video background shouldn't be empty

### Reproduces how often

Intermittent issue

**Comment by kjozwiak** [comment]
The above requires `1.70.103` or higher for `1.70.x` verification 👍
