### ISSUE TITLE
Tab separator has too much contrast on both light and dark mode

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#40608]
### Description

Follow up to https://github.com/brave/brave-browser/issues/40425

The tab separator is too dark in light mode and too light in dark mode. 

Refer to this figma for correct color
https://www.figma.com/design/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?node-id=125-9048&t=fngBE3pO9l9ExfXv-1

Color name: `DesktopBrowser/TabBar/Pinned tab outline - Horizontal`

### Expected result
<img width="921" alt="image" src="https://github.com/user-attachments/assets/86dd3646-623a-49df-9dd1-416f84f6b393">

--

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Version 1.69.153 Chromium: 128.0.6613.85 (Official Build) (arm64)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment]
The darker or lighter tab separator vertical line shows only with the default light or dark mode themes. Other colors are displaying the right level of brightness/color.

**Comment by nintendork07** [comment]
agreed, it looks pretty ugly on mac after updating to 1.69.153

![Screenshot 2024-08-22 at 2 37 57 PM](https://github.com/user-attachments/assets/640a19b4-1c69-4c85-a651-6b25f07a2b59)

**Comment by ilyapopovs** [comment]
Experiencing the same issue with default themes - light and dark, 1.69.153 ℹ️

**Comment by fallaciousreasoning** [comment]
@aguscruiz is this only a problem in 1.69.x?

**Comment by aguscruiz** [comment]
As far as I could tell, yeah

**Comment by kjozwiak** [comment]
The above requires `1.69.155` or higher for `1.69.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.69.155 Chromium: 128.0.6613.85 (Official Build) (x86_64)
-- | --
Revision | 83b4eeea6ba0d846b2c8a71f75036496b3056d36
OS | macOS Version 13.6.9 (Build 22G830)
```

**Comment by LaurenWags** [comment]
Changed to `release-notes/exclude` as this is superseded by https://github.com/brave/brave-browser/issues/40714
