### ISSUE TITLE
[Leo] Add search query and summary from Brave Search SERP when available

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#40615]
### Platforms

Linux, macOS, Windows

### Description

Add search query and summary from Brave Search SERP to conversation history when summarizer-key tag is present.
Note that it only happen on Brave Search SERP when user has opted in to Leo and page context is not unlinked.
This issue is to track the implementation of requirement # 1 in https://docs.google.com/document/d/1idelFPpUEcKDNcyKYf3M5yw91tuIddjrlYfpaWEJjNk/edit

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.71.102 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | d901535b1091c5f39eb2b5426b8fa8e7f3c5edf0
OS | Windows 11 Version 23H2 (Build 22631.4169)

- Verified steps from [brave/brave-core#25257](https://github.com/brave/brave-core/pull/25257)
- Verified asking a query in `https://search.brave.com` and selecting `Answer with AI` generates the summary
- Verified selecting Leo from sidebar automatically populates the query and summary 
- Verified toggle page context to off, removes the staged question and summary
- Verified toggle page context to on, re-adds the staged question and summary
- Verified follow up questions works as expected 

https://github.com/user-attachments/assets/b8f6d989-84c7-4ea2-a93e-1a966e373166
