### ISSUE TITLE
Make "Copy clean link" first in the share menu

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#40614]
### Description

Change the order of the first two entries in the share menu on desktop.

### Steps to reproduce

1. Click on share button in the URL bar.

### Actual result

![Screenshot from 2024-08-22 12-18-22](https://github.com/user-attachments/assets/fa34d391-111a-48b7-a2dd-d9e05c670845)

### Expected result

It should be:
- Copy clean link
- Copy
- Screenshot
- ...

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave	1.70.80 Chromium: 128.0.6613.27 (Official Build) beta (64-bit) 
Revision	6ead335dec3d127f8c0771502638567481f41080
OS	Linux
```

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.96 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | 6dc1837bd07e6dacd8b6b7b5d9f27e7bb09b5eb5
OS | Windows 11 Version 23H2 (Build 22631.4169)
```

Verified using STR from https://github.com/brave/brave-browser/issues/40614#issue-2481545157 

Confirmed the order.  `Copy clean link` shown first and `Copy link` is below in the share menu and both worked as expected

![image](https://github.com/user-attachments/assets/a0132695-6b96-4fb7-b87f-ebcf84116479)
