### ISSUE TITLE
HTTPS Strict mode interstitial "Go back" button jumps two pages back

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#40613]
### Description

The HTTPS Strict mode interstitial "Go back" button navigates too far back in history.

### Steps to reproduce

1. Enable HTTPS Strict mode
2. Go to https://example.com/. Wait for it to load
3. In the same tab, enter https://badssl.com/ in the URL bar and navigate there.
4. Tap on the "http" button
5. Interstitial (correctly) is shown. Click "Go Back" button.

### Actual result

The tab loads [example.com](http://example.com/) ("Go Back" went too far back in history) (edited)

### Expected result

The tab shows the [badssl.com](http://badssl.com/) homepage

### Reproduces how often

Easily reproduced

### Brave version

1.68.134 (127.0.6533.88)

### Device/iOS version

17.5.1

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

HTTPS Strict mode was enabled

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7.1
Brave build: 1.72 (96)
BraveCore: 1.72.96 (131.0.6778.24)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/40613#issue-2481479614
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Go back` works as expected and returned to a previous page.

---------------------------

https://github.com/user-attachments/assets/f26b5836-b5c0-46eb-80f4-862a5467ed61

**Comment by hffvld** [comment]
Verified on `iPad Mini (6th gen)` using version(s):
```
Device/OS: iPad Mini (6th gen) / iPadOS 18.0.1
Brave build: 1.73 (89)
BraveCore: 1.73.89 (131.0.6778.69)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/40613#issue-2481479614
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Go back` works as expected and returned to a previous page.
- Verified that the `Back gesture` works as expected and returned it to a previous page.
- Verified that the browser's `<` back button works as expected and returned it to a previous page.

---------------------------

https://github.com/user-attachments/assets/93ef3b97-9650-4f93-8771-4c13a2726405
