### ISSUE TITLE
HTTPS Strict interstitial shows up at the wrong time

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#40617]
### Description

After the HTTPS Strict interstitial has shown up once, it shows up later in the same tab, instead of the appropriate interstitials, and it still shows the old URL from when it was originally triggered.

### Steps to reproduce

**Flow 1:**
1. Fresh install
2. Enable HTTPS Strict mode
3. Open a new tab
4. Enter `http://badssl.com` (important it's http)
5. Tap "expired"
6. HTTPS strict interstitial shown for `http://badssl.com` 
    - Should show SSL interstitial for `https://expired.badssl.com`
7. If you tap "Proceed" it takes you to badssl.com home page, not expired page.

**Flow 2:**
1. Enable HTTPS Strict mode
2. Open a new tab (important)
3. Visit [badssl.com](http://badssl.com/)
4. Tap on "expired" --> shows an NSURLErrorServiceCertificateUntrusted interstitial (expected)
5. Hit the back button and repeat (step 4) to confirm
6. Go back, tap on an "http-" item you haven't allowlisted. For example, "http-password"  ---> shows the HTTPS Strict interstitial (expected)
7. Hit the back button (not "Go back") and now tap on "expired" again ---> shows the HTTPS strict interstitial with http://http-password.badssl.com/  in the URL bar (!! not expected !!)
8. If you click "Proceed" then it takes you to http://http-password.badssl.com/

(If you want to start this again from scratch, you can open a new tab, but you need to tap a different "http-" item in step 6 because the previous one has been allowlisted in step 8.)

### Actual result

**Flow 1:**
Shows strict HTTP interstitial for `http://badssl.com`

**Flow 2:**
After the Strict interstitial had been shown once, it was shown at an inappropriate time when a different interstitial should have been shown, and it had the old URL.

### Expected result

**Flow 1:**
Should show SSL interstitial for `https://expired.badssl.com`

**Flow 2:**
Tapping on "expired" in step 7 should result in showing the NSURLErrorServiceCertificateUntrusted interstitial again, not the HTTPS Strict interstitial

### Reproduces how often

Easily reproduced

### Brave version

1.68.134 (127.0.6533.88)

### Device/iOS version

17.5.1

### Affected browser versions

- [X] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.68.1 (145)`

**Flow 1**

1. Fresh installed 1.68.1 (145)
2. Enabled HTTPS Strict mode
3. Opened a new tab
4. Entered http://badssl.com (important it's http)
5. Tapped "expired"
6. Confirm HTTPS strict interstitial shown for http://badssl.com
7. Should show SSL interstitial for https://expired.badssl.com
8. Confirmed tapping on "Proceed" takes you to experied.badssl.com home page

Example | Example | Example | Example
-|-|-|-
![IMG_7113](https://github.com/user-attachments/assets/daf0666e-347f-43de-b709-d9f911532ea2) | ![IMG_7114](https://github.com/user-attachments/assets/ac057f2a-5361-431a-9240-b3c803a4a8aa) | ![IMG_7115](https://github.com/user-attachments/assets/200476d1-63be-4771-a235-ffbe30bc935f) | ![IMG_7116](https://github.com/user-attachments/assets/d775cf39-e625-40ee-88d9-a2726f35451e)

**Flow 2:** 

1. Enabled HTTPS Strict mode
2. Opened a new tab (important)
3. Visited` http://badssl.com/`
4. Confirmed tapping on "expired" shows an NSURLErrorServiceCertificateUntrusted interstitial
5. Hit the back button and repeated (step 4) to confirm
6. Confirmed tapping on `http-password` page will show interstitial page
7. Hit the back button to return to homepage 
8. Confirmed tapping on `expired` page again shows the  NSURLErrorServiceCertificateUntrusted interstitial for expired.badssl.com

Example | Example | Example | Example
-|-|-|-
![IMG_7117](https://github.com/user-attachments/assets/38c47a87-a10e-48a6-b91b-c51515c093e6) | ![IMG_7118](https://github.com/user-attachments/assets/a881273a-b96f-4788-89b8-d85a789d4732) | ![IMG_7119](https://github.com/user-attachments/assets/c3140c91-5719-4f6e-b53b-a6d64351e866) | ![IMG_7120](https://github.com/user-attachments/assets/989c462f-d4ce-4951-89a4-7522bffc69b1)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 17.6.1` via the following build(s):

```
Brave | 1.68.145 Chromium: 127.0.6533.120 (Official Build) stable (64-bit)
--- | ---
Revision | 86ed911e4b4765d7d8b5a700639d49cb5f1ecaa0
OS | iOS
```

**`Test Case #1`** - **Incorrectly showing strict mode interstitial / Flow 1** - **`PASSED`**

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/25292#issue-2483303323, ensured that the interstitial page appeared once clicking on `Expired` while on `http://badssl.com`. Also ensured that the SSL interstitial page was displayed on `https://badssl.com` as per the following:

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|-----------------
![IMG_0430](https://github.com/user-attachments/assets/f4dd961c-28bf-429f-906f-1b3e082c9e81) | ![IMG_0431](https://github.com/user-attachments/assets/9155cdd3-2c33-4277-80fb-578eb50892de) | ![IMG_0432](https://github.com/user-attachments/assets/876f54cd-e655-44a3-9a21-bbae065a3f6c) | ![IMG_0433](https://github.com/user-attachments/assets/d59d3e70-f562-4b91-b1e2-2b4646eef8a6)

**`Test Case #2`** - **Incorrectly showing strict mode interstitial / Flow 2** - **`PASSED`**

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/25292#issue-2483303323, ensured that clicking on the `http-password` page displayed the `Insecure` interstitial page. Also ensured that going back via `<` and then clicking on https://expired.badssl.com displayed the correct SSL interstitial page as per the following:

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|---------------|-----------------
![IMG_0436](https://github.com/user-attachments/assets/e250ac27-3929-46fb-b0c9-f28e081e5619) | ![IMG_0439](https://github.com/user-attachments/assets/61584be6-c1f9-4802-a6da-07d3bdc88235) | ![IMG_0438](https://github.com/user-attachments/assets/3ae2787a-f24f-4154-899b-5887a634fbe8) | ![IMG_0437](https://github.com/user-attachments/assets/792f1e7c-1ae0-46e6-a66f-c97ed75612d5)

**`Test Case #3`** - **Verify Proceed is still working on https strict interstitial** - **`PASSED`**

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/25292#issue-2483303323, ensured clicking on `Proceed` under http://http-login.badssl.com correctly loads `http://http-login.badssl.com` as per the following:

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------
![IMG_0440](https://github.com/user-attachments/assets/2f969f67-ced2-42a5-b171-aaa512cef8d1) | ![IMG_0441](https://github.com/user-attachments/assets/0af3fc22-2df8-4271-8c73-26978014cc58) | ![IMG_0442](https://github.com/user-attachments/assets/c29e40f5-ab0e-4197-89e9-fe2bf41ccec5)
