### ISSUE TITLE
Page Content Refining indicator

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#40618]
We should show an indicator similar to search augmentation
<img width="618" alt="Screenshot 2024-08-22 at 15 31 27" src="https://github.com/user-attachments/assets/056de5ae-efb7-47f6-8598-3e91ce316cd5">
for page content refining so users won't feel Leo irresponsive.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using the following version(s):

```
Brave	1.72.90 Chromium: 130.0.6723.70 (Official Build) beta (64-bit) 
Revision	5f14a2225ebf4fcd654e064bde93e77fcc5d8f39
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

* Ensured that loading indicator is shown for page content refining. 

example | example
--|--
![Image](https://github.com/user-attachments/assets/2930900c-9362-4d1d-a62c-46daa6505760) | ![Image](https://github.com/user-attachments/assets/9d7be14a-b309-4dfe-900c-970bdb04a6bd)

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7.1
Brave build: 1.73 (88)
BraveCore: 1.73.88 (131.0.6778.39)
```

Observed this issue #42251
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/25336#issue-2487831227
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Refining` circle indicator is shown when Leo is preparing the answer

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/fa0ca3bb-e465-4d4a-8eba-d158fc193797) | ![2](https://github.com/user-attachments/assets/a48e7568-6eb9-484a-babb-80772b6972b2) | ![3](https://github.com/user-attachments/assets/397514bf-9bd3-4618-ab04-c498b8c14398) |

https://github.com/user-attachments/assets/6a011889-08af-4352-9374-f3200cb08cc6

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.73.88 Chromium: 131.0.6778.39 (Official Build) (64-bit)
-- | --
Revision | e0a230f2aab41bbd7935065107eb039f90f0ec70
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from [brave/brave-core#25336](https://github.com/brave/brave-core/pull/25336)
- Verified page content refine message is shown with flag enabled

https://github.com/user-attachments/assets/54e541c2-48de-4813-9d94-0bf7eaa6a0ab
