### ISSUE TITLE
[Leo] Can set BYOM as the default model, but doesn't actually use it by default

### ISSUE THREAD

**Issue by Infinoid** [brave/brave-browser#40627]
### Description

I tried Leo for the first time, setting up BYOM to point to ollama then setting that as the default model.
Then I tried to use it, got some help text and a license agreement popup, and when I accepted it, it used a mixtral model.

### Steps to reproduce

1. Have a local ollama instance
2. New brave browser, never used Leo before
3. Set up BYOM, configure Leo to use the local ollama instance by default on the brave://settings/leo-assistant page
4. Open a webpage in a tab
5. Open Leo
6. Ask it something
7. See that it did not use the default model that I selected

### Actual result

![image](https://github.com/user-attachments/assets/a41559a5-069e-49e7-af75-37c836496227)

![image](https://github.com/user-attachments/assets/7e985c62-13f8-4682-8cfb-a6a6aaac93c3)

![image](https://github.com/user-attachments/assets/d7991da5-2852-41fb-9f23-f9a792f76a6b)

### Expected result

It should use the model I selected as default, by default.  I had to click the gear icon and select the ollama model again.  (This gear icon was not visible until after the first answer.)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave	1.69.153 Chromium: 128.0.6613.85 (Official Build) (64-bit) 
Revision	a69e96756922f88cbce3482971d70cfd1ee6f872
OS	Linux

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

I feel strongly about privacy.  I don't want to be forced to connect to the Leo server during the BYOM setup process.

**Comment by rebron** [comment]
@Infinoid Did you set up BYOM model before opting into Leo? Are you still seeing the BYOM default model not stick? The issue with that setting not sticking might be due to the order of how you started with Leo.

cc: @aguscruiz @LorenzoMinto

**Comment by Infinoid** [comment]
> @Infinoid Did you set up BYOM model before opting into Leo?

Yes.  I created the BYOM model and set it as default, on the same page, before opting into Leo.

> Are you still seeing the BYOM default model not stick?

No.  I set it once using the gear icon and it stayed set.  It seems to me that the setting on the settings page has no effect, and choosing the model via the gear icon does stick.  But the gear icon isn't visible before opting into Leo.

But different ways of running Leo have different memories of what model to use, and I've had to set it once for each.  

* When opening Leo using the "Customize and control Brave" menu (in the top right), I had to set it once (and it didn't use the default).
* When opening Leo by highlighting page text and choosing a quick action from the context menu, I had to set it once (and it didn't use the default).

For each of those, I had to select my model once, and in both cases, it was after having chosen my model as the default on the settings page.

> The issue with that setting not sticking might be due to the order of how you started with Leo.

Could be.  I first opened Leo using the Customize and control Brave menu in the top right.  (After setting up BYOM and selecting that as default.)

The problem still seems broken and is testable in the opposite direction.  I just tried this:
1. Have this issue open in a tab
2. Open a second tab (or a 45th... whatever) for the Leo settings
3. choose Claude 3 Haiku for the default model
4. Come back to this tab
5. Highlight the word "setting" in the textarea I am using to edit this comment
6. Choose "Explain" from the quick actions menu
7. It was explained using the ollama-llama3.1-8b model I set up with BYOM

So again, the problem seems to be that the default model dropdown on the settings page does nothing.  And it looks like I can reproduce it without having to completely throw away my browser settings or opt in again.

**Comment by srirambv** [comment]
Did the following and can't reproduce it
* Clean browser profile
* Setup BYOM (used Gemma2)
* Set Gemma2 as default model 
* Open Slashdot.org in a new tab
* Open Leo on tab and ask a question
* Accept opt-in message
* Shows Gemma2 as selected default
* Clear chat and set a new default model
* Ask a question, wait for the response
* Click on clear chat, resets to Gemma2

**Comment by Infinoid** [comment]
Confirmed.  I updated the brave-browser (deb) package, and moved the `.config/BraveSoftware` folder out of the way.  Following the same steps on the same machine with the new version, it used my chosen BYOM default model to answer the first question.

I still had to agree to the disclaimer about not trusting AI answers too much... it is what it is.

**Comment by Infinoid** [comment]
So, fixed in 1.73.91.
