### ISSUE TITLE
[ZCash] Balance resolution problems

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#40635]
### Description

There could be balance resolution problems on accounts which have used receiver addresses with 0 utxos.

### Steps to reproduce

1. Create zcash account
2.  Receive funds
3.  Send all funds to somewhere else
4. Receive funds again

### Actual result

Balance will be 0

### Expected result

Balance should be actual

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

1.69

### Android device

-

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.69.156` or higher for `1.69.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.156 Chromium: 128.0.6613.85 (Official Build) (64-bit)
-- | --
Revision | 1d701f8c67ab98b8c562ddd0fa2dafc1305f8605
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from issue description
- Verified ZCash balances work as expected after Send transaction

Before | After
-- | --
 ![image](https://github.com/user-attachments/assets/e449f38a-1683-4d2e-bb0b-609a9991acf8) | ![image](https://github.com/user-attachments/assets/c1e8e14e-05f4-4fee-b554-b3293e69ddbf)

**Comment by srirambv** [comment]
Removing `OS/Android` label as ZCash is not yet supported on Android
