### ISSUE TITLE
Lights out theme - Additional to default dark mode theme

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#40638]
### Description

After the integration with Material design's tri-color themes, we're going to introduce a spin-off of our default neutral theme, tentatevely called "lights out". It's a darker version of the default theme, closer to what we had before the material design integration.

Design:
Color changes required are available in dev mode annotations.
https://www.figma.com/design/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?node-id=7861-15123&m=dev

### Material design default theme

<img width="1712" alt="image" src="https://github.com/user-attachments/assets/e9bfa781-838e-44be-a28d-bcc3dcc3ab9b">

### Lights out theme

![image](https://github.com/user-attachments/assets/635e0399-2781-49cd-9cab-aea5c7b060a9)

**Comment by fallaciousreasoning** [comment]
I think we might be able to point users to a super dark theme in the store (ideally one published by Chrome)

Maybe this one:
https://chromewebstore.google.com/detail/just-black/aghfnjkcakhmadgdomlmlhhaocbkloab

**Comment by aguscruiz** [comment]
Yeah, closing this one based on what we talked yesterday
