### ISSUE TITLE
HTTPS By Default feature doesn't have functional feature flags

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#40634]
### Description

[We shipped HTTPS By Default](https://brave.com/privacy-updates/29-https-by-default-ios/) in 1.68 (PRs: [main feature](https://github.com/brave/brave-core/pull/23029), [strict mode and interstitial](https://github.com/brave/brave-core/pull/23337)), but the feature flags don't actually wrap around the functionality, which means we can't roll the feature out or back via Griffin. Additionally, we want a flag around the non-default Strict mode, since that proved to be tricky from a state point-of-view.

These are the flags we want:
1. One flag for the overall HTTPS By Default feature: if it’s ON then we try to upgrade all websites to HTTPS by default (and use the exception list to not try certain websites) with a silent fallback to HTTP, and an optional Strict mode to show the interstitial if there’s a fallback. If this flag is OFF, we go back to old WebKit-controlled HTTPS upgrades. Default: ON.
2. Another flag that’s conditional on 1 being ON: only controls whether the user can select Strict mode or not. If this flag is OFF, the 3 way option (Standard, Strict, Disabled) becomes a boolean toggle i.e. no Strict mode possible. If a user enabled Strict mode, and then we disable it via Griffin, it should fall back to Standard mode but preserve the pref so when we enable it again they will automatically get Strict mode. Default: ON.

These should be accessible via brave://flags.

### Steps to reproduce

1. Go to brave://flags
2. Check presence of flags above (exact names TBD)
3. Check behaviour

### Actual result

1. Second flag doesn't exist
2. First flag is incomplete i.e. doesn't disable the feature

### Expected result

See issue description. 

To check if first flag is functioning as expected, you should see a 3-way toggle for HTTPS Upgrades in Settings: Standard (default), Strict, and Disabled which should function as expected. See https://github.com/brave/brave-browser/issues/36408 for QA steps. http://http.badssl.com/ is an example of a site that will get an interstitial in Strict mode but nothing will happen if not Strict mode.

To check if second flag is functioning, the HTTPS Upgrades setting should be a boolean. You shouldn't see a Strict mode interstitial when an HTTPS upgrade fails. Test site: http://http.badssl.com/ should not get an interstitial.

### Reproduces how often

Easily reproduced

### Brave version

1.68. **_This needs to be uplifted._**

### Device/iOS version

Any

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.68.145` or higher for `1.68.x` verification 👍

**Comment by Uni-verse** [comment]
Verification in progress on `iPhone 12` running `iOS 17.5.1` using version `1.68.1 (145)`

### Case: brave://flags#https-only-mode enabled (default mode)

* ensured that `brave://flags#https-only-mode` is set as enabled by default on a clean/new install
* ensured `Upgrade Connections to HTTPS` is set as `Standard` as the default

Example | Example
-|-
![IMG_7121](https://github.com/user-attachments/assets/733645f1-9b13-47b6-a28f-203442d1b059) | ![IMG_7122](https://github.com/user-attachments/assets/9048e1ab-555b-4460-81d6-6a984ab839da)

While both `brave://flags#https-by-default` & `brave://flags#https-only-mode` are enabled, went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/36408#issue-2157693231 as per the following:

**Test interstitial**

Example | Example | Example
-|-|-
![IMG_7123](https://github.com/user-attachments/assets/7912180f-8fb3-4353-90c9-a96232503c42) | ![IMG_7124](https://github.com/user-attachments/assets/73bc79f1-28da-459e-bfab-3b4b33be672b) | ![IMG_7125](https://github.com/user-attachments/assets/8fd43678-a0c7-4d46-a7ab-c8cb9bdfe664)

**Test Upgrading**

Example | Example | Example
-|-|-
![IMG_7124](https://github.com/user-attachments/assets/2c1fd3b1-10a0-4c38-a676-86d0f61a1b97) | ![IMG_7127](https://github.com/user-attachments/assets/b9043b21-3cef-4eff-92e3-cbbd359e6008) | ![IMG_7128](https://github.com/user-attachments/assets/479dc728-be4d-4497-a5a5-d6dcbd8e00ee)

### Case - brave://flags#https-only-mode disabled

* disabled `brave://flags#https-only-mode` via `brave://flags` after installing `1.71.29 Chromium: 128.0.6613.85`
* restart the browser once the `brave://flag` has been changed
* once disabled, ensured that `Upgrade Connections to HTTPS` is set as a boolean toggle (enabled/disabled)
* visited http://http.badssl.com and ensured that a interstitial page re: HTTP upgrade is **NOT** being displayed

Example | Example | Example | Example
-|-|-|-
![IMG_7129](https://github.com/user-attachments/assets/ce3689ac-41ea-4f47-a8b1-afaa2bfdc7d8) | ![IMG_7130](https://github.com/user-attachments/assets/adc76860-3b1c-4686-b23f-65f0e78819b3) | ![IMG_7131](https://github.com/user-attachments/assets/b1e9110b-baf5-4025-8481-7adba32dca81) | ![IMG_7132](https://github.com/user-attachments/assets/21de56a9-db01-47b6-962b-c300d6adf611)

### Case - brave://flags#https-by-default disabled

* disabled `brave://flags#https-by-default` via `brave://flags` after installing `1.71.29 Chromium: 128.0.6613.85`
* restart the browser once the `brave://flag` has been changed
* ensured that `Upgrade Connections to HTTPS` is set as a boolean toggle (enabled/disabled)
   * `brave://flags#https-only-mode` is also being disabled when `brave://flags#https-by-default` has been disabled 
* visited http://http.badssl.com and ensured that a interstitial page re: HTTP upgrade is **NOT** being displayed
* ensured that `http://brave.com` --> `https://brave.com`
* ensured that `http://google.com` --> `https://google.com`
* ensured that `http://facebook.com` --> `https://m.facebook.com`
* ensured that `http://reddit.com` --> `https://reddit.com`

Example | Example
-|-
![IMG_7134](https://github.com/user-attachments/assets/36268d39-4802-4d6e-9054-a35d6a702ad6) | ![IMG_7135](https://github.com/user-attachments/assets/1099879c-de72-480d-abef-5d4b6a657dbb)

### Case - brave://flags#https-only-mode being disabled but user has Strict selected

* installed `1.71.29 Chromium: 128.0.6613.85`
* set  `Upgrade Connections to HTTPS` as `Strict` via `Settings`
* disabled `brave://flags#https-only-mode` via `brave://flags` and restarted the browser
* ensured that the `Upgrade Connections to HTTPS` setting is now set as a boolean without `Strict` mode
* visited `http://http.badssl.com` and ensured that the interstitial page re: HTTP upgrade is **NOT** being displayed
* enabled `brave://flags#https-only-mode` via `brave://flags` and restarted the browser
* ensured that `Upgrade Connections to HTTPS` is now a drop down and `Strict` is being selected (users previous choice)
* visited `http://http.badssl.com` and ensured that the interstitial page is being used/displayed

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 17.6.1` via the following build(s):

```
Brave | 1.68.145 Chromium: 127.0.6533.120 (Official Build) stable (64-bit)
--- | ---
Revision | 86ed911e4b4765d7d8b5a700639d49cb5f1ecaa0
OS | iOS
```

### `Test Case #1` - `brave://flags#https-only-mode` enabled (default mode)

* ensured that `brave://flags#https-only-mode` is set as enabled by default on a clean/new install
* ensured `Upgrade Connections to HTTPS` is set as `Standard` as the default

**`Example`** | **`Example`**
----------------|------------------
![IMG_0443](https://github.com/user-attachments/assets/1e63da10-023c-4f8e-a102-a394f3922999) | ![IMG_0444](https://github.com/user-attachments/assets/bf810a4c-a1a1-4c49-bd02-28c955b77515)

While both `brave://flags#https-by-default` & `brave://flags#https-only-mode` are enabled, went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/36408#issue-2157693231 as per the following:

**`Test interstitial`**

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** 
----------------|----------------|----------------|----------------|---------------
![IMG_0445](https://github.com/user-attachments/assets/3afe6619-c8fc-400d-b4da-252308492dd9) | ![IMG_0446](https://github.com/user-attachments/assets/381f0c81-eba7-4267-b54d-9bbdf4f65823) | ![IMG_0447](https://github.com/user-attachments/assets/fd1adc0a-1d75-4406-a4cb-1dc5c69c32da) | ![IMG_0448](https://github.com/user-attachments/assets/696caeff-56e1-4db6-893f-96086f68c26f) | ![IMG_0449](https://github.com/user-attachments/assets/ee6b4b4f-2e00-4d04-9ebc-b804005ba22e)

**`Test upgrading`**

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** 
----------------|----------------|----------------|----------------|---------------
![IMG_0450](https://github.com/user-attachments/assets/d434b311-d10a-4b4a-b4a5-accc7b8e7a8f) | ![IMG_0451](https://github.com/user-attachments/assets/4a6edb1d-e178-4a76-a91a-1acbc3b61039) | ![IMG_0452](https://github.com/user-attachments/assets/e5a0a435-e14c-469e-87f5-45d2799a6d26) | ![IMG_0453](https://github.com/user-attachments/assets/dc57a205-a15c-474b-a18b-b686dafaa864) | ![IMG_0454](https://github.com/user-attachments/assets/a7b6a240-2ef9-482c-a8f5-04e0f5c6c437)

### `Test Case #2` - `brave://flags#https-only-mode` disabled

* disabled `brave://flags#https-only-mode` via `brave://flags` after installing `1.68.145 Chromium: 127.0.6533.120`
* restart the browser once the `brave://flag` has been changed
* once disabled, ensured that `Upgrade Connections to HTTPS` is set as a boolean toggle (enabled/disabled)
* visited http://http.badssl.com and ensured that a interstitial page re: HTTP upgrade is **NOT** being displayed

**`Example`** | **`Example`** | **`Example`** 
----------------|----------------|----------------
![IMG_0455](https://github.com/user-attachments/assets/cecfdd56-7b6d-4ebd-8c29-b6d22a8f204c) | ![IMG_0456](https://github.com/user-attachments/assets/ce64da9f-8dbc-4c46-bf2e-efe00caad1ee) | ![IMG_0457](https://github.com/user-attachments/assets/62bac8e2-d24e-4649-bc57-46ed21bf9c54)

### `Test Case #3` - `brave://flags#https-by-default` disabled

* disabled `brave://flags#https-by-default` via `brave://flags` after installing `1.68.145 Chromium: 127.0.6533.120`
* restart the browser once the `brave://flag` has been changed
* ensured that `Upgrade Connections to HTTPS` is set as a boolean toggle (enabled/disabled)
   * `brave://flags#https-only-mode` is also being disabled when `brave://flags#https-by-default` has been disabled 
* visited http://http.badssl.com and ensured that a interstitial page re: HTTP upgrade is **NOT** being displayed
* ensured that `http://brave.com` --> `https://brave.com`
* ensured that `http://google.com` --> `https://google.com`
* ensured that `http://facebook.com` --> `https://m.facebook.com`
* ensured that `http://reddit.com` --> `https://reddit.com`

**`Example`** | **`Example`** | **`Example`** 
----------------|----------------|----------------
![IMG_0458](https://github.com/user-attachments/assets/f9706158-3f52-46af-b55a-1fc74193c336) | ![IMG_0459](https://github.com/user-attachments/assets/9ced6815-ad51-425e-b52a-3bcd9a6d2e1f) | ![IMG_0460](https://github.com/user-attachments/assets/773d1a82-e229-41da-b703-c9722c9a3261)

### `Test Case #4` - `brave://flags#https-only-mode` being disabled but user has `Strict` selected

* installed `1.68.145 Chromium: 127.0.6533.120`
* set  `Upgrade Connections to HTTPS` as `Strict` via `Settings`
* disabled `brave://flags#https-only-mode` via `brave://flags` and restarted the browser
* ensured that the `Upgrade Connections to HTTPS` setting is now set as a boolean without `Strict` mode
* visited `http://http.badssl.com` and ensured that the interstitial page re: HTTP upgrade is **NOT** being displayed
* enabled `brave://flags#https-only-mode` via `brave://flags` and restarted the browser
* ensured that `Upgrade Connections to HTTPS` is now a drop down and `Strict` is being selected (users previous choice)
* visited `http://http.badssl.com` and ensured that the interstitial page is being used/displayed

Video of the above verification on `iPad` --> https://youtu.be/OpyddBk0zs8
