### ISSUE TITLE
No sidebar, means no sidebar!

### ISSUE THREAD

**Issue by Ehab-d** [brave/brave-browser#40636]
### Description

I'm not a fan of the sidebar feature in Brave. Anyway I'm used to disable it every time I install Brave browser.

After version `1.69.153` Brave sidebar has been added to the hamburger menu whatever it's disabled or not!

![Untitled](https://github.com/user-attachments/assets/4f4495df-3bec-4979-a164-af6448b992cd)

### Steps to reproduce

1. Click the hamburger menu
2. You can see the Sidebar controls
*and it's disabled from settings

### Actual result

The Sidebar contrrols exists in the menu [Sidebar disabled]

### Expected result

The sidebar should be not there when it's disabled.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave 1.69.153 - Chromium 128.0.6613.85

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Please provide at least a flag or a policy to disable Brave Sidebar completely.

**Comment by rebron** [comment]
@Ehab-d. Sidebar is not visible and off by default and there is a sidebar button on the toolbar that you can hide when you right click. The sidebar setting in the hamburger menu is just that, a setting and was in there previously but under a sub menu.

Closing as wontfix.

**Comment by lidel** [comment]
@rebron should this be reopened since in the latest Brave Stable Release I see that your statement is no longer true, and Sidebar IS visible and on by default + there is no way to disable it via `/etc/brave/policies/managed/policies.json` or `--disable-*` CLI flag?
