### ISSUE TITLE
[iOS] - BraveCoreSwitches for AI-Chat testing is uses the wrong env names

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#40639]
### Description

- The brave-core switches are using `"production"` and "`development"` instead of `"prod"` or `"dev"` when TESTING on nightly builds.
- We should update the switches so they are correct on nightly when testing payments.

### Steps to reproduce

1. Attempt to make payments on nightly.
2. Notice the URL (via CharlesProxy) is always `payments.rewards.brave.com` instead of `.bravesoftware.com`

### Actual result

- Staging switch didn't work

### Expected result

- Should switch to whatever env we specify

### Reproduces how often

Easily reproduced

### Brave version

1.68.x

### Device/iOS version

Any

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7
Brave build: 1.71 (116)
BraveCore: 1.71.116 (130.0.6723.58)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Open `Dev settings` > BraveCore Switches
3. Brave Services Environment > Set it to `prod`
4. Close `Dev settings` > Attempt to purchase `Leo` subscription
5. *Verify via Charles Proxy URL is `https://payment.rewards.brave.com`*
6. Open `Dev settings` > BraveCore Switches
7. Brave Services Environment > Set it to `staging`
8. Close `Dev settings` > Attempt to purchase `Leo` subscription
8. *Verify via Charles Proxy URL is `https://payment.rewards.bravesoftware.com`*
9. Open `Dev settings` > BraveCore Switches
10. Brave Services Environment > Set it to `dev`
11. Close `Dev settings` > Attempt to purchase `Leo` subscription
12. *Verify via Charles Proxy URL is `https://payment.rewards.brave.software`*

**ACTUAL RESULTS:**
- Verified that the URL is pointing to `https://payment.rewards.brave.com` when the `Brave Services Environment` switch is set to `prod`.
- Verified that the URL is pointing to `https://payment.rewards.bravesoftware.com` when the `Brave Services Environment` switch is set to `staging`.
- Verified that the URL is pointing to `https://payment.rewards.brave.software` when the `Brave Services Environment` switch is set to `dev`.

---------------------------

|`prod`|`staging`|`dev`|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/fd2d86da-100c-4beb-8f28-c52608142c8a) | ![2](https://github.com/user-attachments/assets/ca3d3ed0-a673-4bca-9eb6-fe44b8627793) | ![3](https://github.com/user-attachments/assets/0d2b3901-6baf-4b7d-b9e2-d8d5ca2fc80c) |
| ![1](https://github.com/user-attachments/assets/830ac04b-3d79-4c76-89ca-285a19ba9d8f) | ![2](https://github.com/user-attachments/assets/2e9b68cd-5df7-4188-936a-3d16df45c9f5) | ![3](https://github.com/user-attachments/assets/f9ce7907-a8ad-4d29-95dc-558cebd5fefe) |
| ![1](https://github.com/user-attachments/assets/0add88d7-3ab9-45a6-b3c2-83be29a5abc8) | ![2](https://github.com/user-attachments/assets/c22f8e08-dec1-4392-8fc6-fd53cbbb34f9) | ![3](https://github.com/user-attachments/assets/d5e6f87e-a607-4afb-aafd-afc57f1278e5) |
