### ISSUE TITLE
"Memory Saver" setting isn't visible in brave://settings unless you search for it

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#40633]
### Description

Found by @jeremytieman 

"Memory Saver" is under brave://settings/system in `1.68.141`. In `1.69.153` it doesn't appear to be under any section. You can find it though if you search for "Memory Saver".

### Steps to reproduce

1. Go to brave://settings/system
2. Under Performance section, look for "Memory Saver"

### Actual result

"Memory Saver" is not shown but is there if you search for it:

Example | Example
--- | ---
<img width="1188" alt="Screenshot 2024-08-23 at 12 48 32 PM" src="https://github.com/user-attachments/assets/0f0740b1-816c-4699-8728-1b0d1a5f4b5c"> | <img width="1184" alt="Screenshot 2024-08-23 at 12 51 35 PM" src="https://github.com/user-attachments/assets/e4070771-fea8-48fc-adbf-7f4c99d15cda">

### Expected result

Should be visible as it is in 1.68.141:

<img width="1189" alt="Screenshot 2024-08-23 at 12 47 27 PM" src="https://github.com/user-attachments/assets/826327b6-97a6-4e7b-a8e8-015007874232">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.69.153 Chromium: 128.0.6613.85 (Official Build) (x86_64)
-- | --
Revision | a69e96756922f88cbce3482971d70cfd1ee6f872
OS | macOS Version 13.6.9 (Build 22G830)
```

```
Brave | 1.71.18 Chromium: 128.0.6613.40 (Official Build) nightly (x86_64)
-- | --
Revision | e13fa103101b5eddd5b9bb74bc79c67e1b878a74
OS | macOS Version 13.6.9 (Build 22G830)
```

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.69.155` or higher for `1.69.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.69.155 Chromium: 128.0.6613.85 (Official Build) (64-bit)
-- | --
Revision | 83b4eeea6ba0d846b2c8a71f75036496b3056d36
OS | Windows 10 Version 22H2 (Build 19045.4780)
```
Reproduced the issue on `1.69.153 Chromium: 128.0.6613.85`

Example | Example
----------|---------
![image](https://github.com/user-attachments/assets/2f172cfc-3b53-4a07-9519-d9068be4d61c) | ![image](https://github.com/user-attachments/assets/fb0ab12a-2190-4b18-afe3-ea8559e20a17)

Upgraded the profile to `1.69.155 Chromium: 128.0.6613.85` and ensured that the memory saver is shown under  brave://settings/system
![image](https://github.com/user-attachments/assets/b28e1715-2388-4d96-9a5e-bed5331e0413)
