### ISSUE TITLE
Disable cosmetic filtering on Speedreader pages

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#40642]
### Description

Speedreader can interact badly with Shields and adblock lists: https://github.com/brave/brave-browser/issues/38118. Also, Speedreader causes two scrollbars to appear on https://metro.co.uk/2023/01/01/manchester-man-ate-124-kebabs-in-month-for-charity-18023290/ because of EasyList Cookie because of the rule `metro.co.uk##body,html:style(overflow: auto !important; position: initial !important;)`

We should just disable Shields when Speedreader is active. The privacy risk is minimal given that in Speedreader mode the website is heavily bounded in what it can do.

### Steps to reproduce

1. Ensure EasyList Cookie is enabled in brave://settings/shields/filters
2. Go to https://metro.co.uk/2023/01/01/manchester-man-ate-124-kebabs-in-month-for-charity-18023290/ and enable Screenreader

### Actual result

1. Shields is enabled
2. Double scrollbar

### Expected result

1. Shields should be disabled/unclickable (similar to how it is on internal pages)
2. No double scrollbar

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.52 Chromium: 127.0.6533.88 (Official Build) nightly (arm64) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.75.133 Chromium: 132.0.6834.57 (Official Build) nightly (64-bit)
-- | --
Revision | ce1787778a7a5d92e63a29f8be965494ef49cbbd
OS | Windows 11 Version 24H2 (Build 26100.2605)
```

Reproduced the issue using STR from the [description ](https://github.com/brave/brave-browser/issues/40642#issue-2483997599)in 1.73.104


 ![Image](https://github.com/user-attachments/assets/1fe499d7-a9b5-418a-b19f-ed4d528c5b1c)

Verified the issue using STR from the [description ](https://github.com/brave/brave-browser/issues/40642#issue-2483997599)in 1.73.104

Confirmed when Screenreader is enabled,  Shields is disabled and unclickable
Confirmed no double scrollbar is shown

example | example 
----- | ----
![Image](https://github.com/user-attachments/assets/60565de9-e130-4ee4-a3da-ed784d9897cf)|![Image](https://github.com/user-attachments/assets/2a2fb9fd-c4ba-4594-9b60-1aca6fc13944)
