### ISSUE TITLE
Unable to sign in https://www.mgmresorts.com/en.html

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#40644]
### Description

Gets error when attempting to signin or login.

"Oops! We have encountered an unknown error, please contact support."

### Steps to reproduce

1. Open https://www.mgmresorts.com/en.html
2. Click on Sign-in/Join (top right)
3. Fill in random email details, then "next"

### Actual result

![mgm-errors](https://github.com/user-attachments/assets/d6d5d034-19d8-432b-8257-a67bc9550b9a)

### Expected result

![mgm-non-error](https://github.com/user-attachments/assets/55844a6d-cec7-4143-952a-aa8e6b42f3ed)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Every version

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

"Screen" Fingerprinting causing it

**Comment by bondeabhijeet** [comment]
@ryanbr I did not encounter this issue while I was trying to replicate. Although there were some errors in the console.

![image](https://github.com/user-attachments/assets/e88972af-7024-424e-9e0c-acb6ed80d7f9)

But I was able to go on with the process.

**Comment by ryanbr** [comment]
Signin and Login shows, safe to close now
