### ISSUE TITLE
Brave translation, languages unavailable

### ISSUE THREAD

**Issue by Aadam-Marshall** [brave/brave-browser#40643]
### Description

Seems like after the 22 August update, half of the languages became unavailable for translation (including translation via right-click, if you have Google Search set as the search engine), see the screenshot.

### Steps to reproduce

1. brave://settings/languages
2. "Translate into this language"
3. Many languages not present

### Actual result

![1](https://github.com/user-attachments/assets/d8b7e5a2-5ea5-4ef8-a1cc-e73cec126dbf)

### Expected result

All languages should be present.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.153 Chromium: 128.0.6613.85 (Official Build) (64-bit)
Revision | a69e96756922f88cbce3482971d70cfd1ee6f872
OS | Windows 10 Version 22H2 (Build 19045.4780)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by atuchin-m** [comment]
The same bug: https://github.com/brave/brave-browser/issues/40750
