### ISSUE TITLE
How do you access IPFS using Brave? Is it broken just for me?

### ISSUE THREAD

**Issue by andrewslock** [brave/brave-browser#40648]
### Description

There's a blog post from the brave team saying that the browser supports IPFS: https://brave.com/blog/ipfs-support/
>"As of Brave 1.19.x, you can take this address, paste it in the Brave address bar, and load it."

When I try and paste the given link in the address bar, nothing happens except the default search engine is fed the link and tries to search it.
If I paste the link and choose just to go to the link, just nothing happens.
>"Users can troubleshoot IPFS by navigating to an internal page: brave://ipfs. This also shows users the gateway, API, and swarm ports. Users can also talk to the Brave managed instance using go-ipfs command line and by specifying an argument for the --api= parameter."

I go to `brave://ipfs`, it says `This site can’t be reached. ERR_INVALID_URL `
I go to `brave://flags`, search for `IPFS`, nothing.

Have I downloaded a wrong version or maybe there's some flag the browser needs to start with?

### Steps to reproduce

paste `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html` into the address bar 
OR
go to `brave://flags` and search for `IPFS`

### Actual result

<img width="1505" alt="Screenshot 2024-08-24 at 23 25 35" src="https://github.com/user-attachments/assets/2430441f-0e1c-4765-92b4-b535297da740">

### Expected result

The ipfs link resolves in the browser displaying a wiki page of Vincent van Gogh, apparently.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.69.153 Chromium: 128.0.6613.85 (Official Build) (arm64)
-- | --
Revision | a69e96756922f88cbce3482971d70cfd1ee6f872
OS | macOS Version 14.4.1 (Build 23E224)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

I tried to go to `https://ipfs.io/ipfs/bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html` and it worked, so I guess the ipfs link is fine.

**Comment by Robotizing** [comment]
> Is it broken just for me?
Unfortunately, [no](https://github.com/brave/brave-browser/issues/37735).

**Comment by magiccodingman** [comment]
So, I was wondering about the same thing. It happened right after an update. I tried a couple VM's and laptops. Brave version 128.1.69.153 has broken IPFS or has removed the feature entirely. It's one or the other.

**Comment by srirambv** [comment]
IPFS support has been [removed](https://github.com/brave/brave-browser/issues/37735) from 1.69.x onward. You can still install the extension via Webstore and use it, however there is no support for localnode.
