### ISSUE TITLE
scrisc.com shows interstitial in HTTPS Strict mode

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#40658]
### Description

Visiting http://scrisc.com in HTTPS Strict mode shows an interstitial, but it should just take us to https://scrisc.com

### Steps to reproduce

1. Open fresh profile
2. Enable HTTPS strict
3. Visit http://scrisc.com

### Actual result

Interstitial shown. Clicking proceed takes us to http://scrisc.com

### Expected result

Should show https://scrisc.com

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

1.69.153

### Android device

- ? (not tested yet)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.71.101 Chromium: 129.0.6668.70 (Official Build) beta (x86_64)
-- | --
Revision | 734075a5959db3e93d6def81a15e1fc6c2609fc2
OS | macOS Version 14.7 (Build 23H124)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.104 Chromium: 129.0.6668.89 (Official Build) beta (64-bit)
-- | --
Revision | 3da42496f366e4dc607c58cfdd95ce3f5064c171
OS | Windows 11 Version 23H2 (Build 22631.4249)
```

Reproduced the issue using STR from https://github.com/brave/brave-browser/issues/40658#issue-2485638841


example | example | example
----- | ----- | ----
![image](https://github.com/user-attachments/assets/7497adb2-8aeb-425f-a847-f7d48cbf77e2)|![image](https://github.com/user-attachments/assets/5d89e7c1-7930-4ee8-afad-24dd54eadee0)|![image](https://github.com/user-attachments/assets/895b5a67-1a71-41ec-93cd-0cd9fdfd0509)


1. Installed 1.71.104
2. launched Brave
3. opened brave://settins/shields in a new tab
4. changed "Upgrade connections to HTTPS" to "Strict"
5. visited http://scrisc.com/ in a new tab

#### Confirmed no interstitial page is shown 

step 4 | step 5
----- | -----
![image](https://github.com/user-attachments/assets/23deb052-7e66-4040-83af-ec4c88aee4e3)|![image](https://github.com/user-attachments/assets/eff674b2-ffd0-459b-b7f7-2136d992f4a2)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 15` using the following build(s):

```
Brave | 1.71.110 Chromium: 129.0.6668.100 (Official Build) beta (64-bit)
--- | ---
Revision | 46cd0b1af7127687895fcaceff93dd80e29e6f2b
OS | Android 15; Build/AP41.240823.009; 35; REL
```

* installed `1.71.110 Chromium: 129.0.6668.100`
* set `Upgrade connections to HTTPS` to `Strict` via `Settings` -> `Brave Shields & privacy`
* loaded `http://scrisc.com` and ensured that the website loads without any issues and doesn't display an `interstitial` page

**`Example`** | **`Example`**
----------------|----------------
![Image](https://github.com/user-attachments/assets/f3c6e24c-ad3e-4a75-a944-bf08ea8f3ab8) | ![Image](https://github.com/user-attachments/assets/20b80baa-08a5-4532-b7e6-e2b95acccb00)

---------------------

Verification **PASSED** on `Samsung Galaxy S8 Ultra` running `Android 14` using the following build(s):

```
Brave | 1.71.110 Chromium: 129.0.6668.100 (Official Build) beta (64-bit)
--- | ---
Revision | 46cd0b1af7127687895fcaceff93dd80e29e6f2b
OS | Android 14; Build/UP1A.231005.007; 34; REL
```

* installed `1.71.110 Chromium: 129.0.6668.100`
* set `Upgrade connections to HTTPS` to `Strict` via `Settings` -> `Brave Shields & privacy`
* loaded `http://scrisc.com` and ensured that the website loads without any issues and doesn't display an `interstitial` page

**`Example`** | **`Example`**
----------------|----------------
![Image](https://github.com/user-attachments/assets/712d1edf-fbda-4f5c-a042-cf08f977660e) | ![Image](https://github.com/user-attachments/assets/3c46a8e5-9da5-475c-9731-b9d7fe462ee2)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.71.112 Chromium: 130.0.6723.44 (Official Build) (64-bit)
-- | --
Revision | 7d51df656b247f9432ee714a6d160142a1e11c13
OS | Linux
```
