### ISSUE TITLE
Mouse clicks not working 

### ISSUE THREAD

**Issue by vdawg-git** [brave/brave-browser#40655]
### Description

Sometimes Brave becomes unclickable.

A button will still render its active state when clicked, but the click in the end does nothing.

I also found this thread:
https://community.brave.com/t/browser-sometimes-becomes-unclickable/540321

But for me it seems to be more random, potentially connected to Figma.

### Steps to reproduce

Unable to reproduce. 

### Actual result

UI Elements (native or website) should be clickable.

### Expected result

Clicks don't work.

### Reproduces how often

Intermittent issue

### Brave version (brave://version info)

**Brave**:	1.69.153 Chromium: 128.0.6613.85 (Official Build) (64-bit) 
**Revision**: a69e96756922f88cbce3482971d70cfd1ee6f872
**OS**:	Linux, Wayland, Hyprland

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by yurihikari** [comment]
I got the same issue, and could reproduce it consistently after trying to drag something from the UI (when there is the hand holding mouse cursor if you prefer). It happened only on ozone layout with Wayland.

It also makes my CPU going crazy hot. (Going from 40°C to 89°C) after triggering that bug.

**Comment by Visual-Dawg** [comment]
I was also able to reproduce it by dragging stuff. 
As a test I used: https://swapy.tahazsh.com/ and dragged the elements around.
It does not happen instantly and sometimes my browser just ignores all input.

**Comment by yurihikari** [comment]
Also tried to edit a WordPress website by adding blocks to it, dragging them and releasing also triggers the bug. Furthermore, I also tried the latest nightly version, and the bug was still present. All mouse inputs are ignored, and only keyboard navigation works.

**Comment by yurihikari** [comment]
As of version 1.69.160, the bug is no longer present and Brave works as expected.

**Comment by vdawg-git** [comment]
Yes, I have also not experienced those anymore on `1.69.160`
