### ISSUE TITLE
Unable to input credit card details on victoriassecret.com

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#40652]
### Description

Unable to enter credit card details. With shields enabled/fingerprinting enabled.

### Steps to reproduce

1. Visit https://victoriassecret.com/  (US)
2.  Add an item 
3.  When user gets to `https://www.victoriassecret.com/us/checkout#payment` the cc payment doesn't work

### Actual result

`our payment token has expired. Please refresh to continue.` Refresh Form
`Access to fetch at 'https://api.victoriassecret.com/checkoutpayment/v8/session/credit-card' from origin 'https://www.victoriassecret.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
![vic-secrets-not-working](https://github.com/user-attachments/assets/e1b6fa22-fca3-4d0a-87ce-50874c593c7a)

### Expected result

![vic-secrets-working](https://github.com/user-attachments/assets/144b587a-bb11-4000-9194-9653f9d79513)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.87 Chromium: 128.0.6613.85 (Official Build) beta (64-bit) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

When refreshing form:

```
Access to fetch at 'https://api.victoriassecret.com/checkoutpayment/v8/session/credit-card' from origin 'https://www.victoriassecret.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Fingerprinting related:
- Disable all specific togglable Fingerprinting options doesn't fix it. 
- Disabling Fingerprint outright works.

**Comment by arthuredelstein** [comment]
When https://github.com/brave/brave-core/pull/25312 merges then the `language` exception will apply here.

**Comment by arthuredelstein** [comment]
This is now working in Nightly
