### ISSUE TITLE
Add Zen Mode (Compact Mode)

### ISSUE THREAD

**Issue by geekyBoogiepop** [brave/brave-browser#40661]
### Platforms

Linux, macOS, Windows

### Description

A Zen Mode or Compact mode keeps you away from any UI distraction like the tab strip or anything that is not the content of the website to help you focus on what you are doing! Similar implementations can be found on Zen Browser or Arc Browser. Here's a screenshot of Zen Browser's compact mode:

![image](https://github.com/user-attachments/assets/7628fa11-c490-46a9-b45c-068c9a30cb40)

If you hover over the left side of the window, a sidebar pops up to let you select the tabs. You could open the sidebar with a keyboard shortcut or even a button near the back arrow button (as Arc does).

**Comment by rebron** [comment]
@geekyBoogiepop You can get pretty close to what you're looking for now in vertical tabs mode. We're working on an option to hide the tab strip too. But you can get to the screenshot below pretty easily.

<img width="1534" alt="Screenshot 2024-08-26 at 4 40 20 PM" src="https://github.com/user-attachments/assets/963d9fd1-198f-407c-ae21-14658930b0c0">

**Comment by geekyBoogiepop** [comment]
Awesome, the option to hide the tab strip will definitely help to get the same result! Having to look at dozens of tabs all the time can be quite distracting and stressful, most of the time I know what I'm looking for, so I search it with Ctrl + Shift + S.

**Comment by LinuxMeow** [comment]
It also not only allows tab to be hidden in compact mode but above url bar section as well. I wished for this to be feature for so long but you know, no competition no interest in improving features...

**Comment by baldemar-wuda** [comment]
@LinuxMeow I've switched to Zen browser, it has all that features (and many more).

**Comment by xtrasmal** [comment]
> [@geekyBoogiepop](https://github.com/geekyBoogiepop) You can get pretty close to what you're looking for now in vertical tabs mode. We're working on an option to hide the tab strip too. But you can get to the screenshot below pretty easily.
> 
> <img alt="Screenshot 2024-08-26 at 4 40 20 PM" width="1534" src="https://private-user-images.githubusercontent.com/5951041/361605255-963d9fd1-198f-407c-ae21-14658930b0c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTA1NDE0OTQsIm5iZiI6MTc1MDU0MTE5NCwicGF0aCI6Ii81OTUxMDQxLzM2MTYwNTI1NS05NjNkOWZkMS0xOThmLTQwN2MtYWUyMS0xNDY1ODkzMGIwYzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDYyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA2MjFUMjEyNjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTM5MTE0MmEwNTY0MDAwMzU1NTA4YWFhMDFlNTUyYWM5MGYzZGRmMzhjNWEwYzZiNmY5ZDc5NmM2N2Y1NDE3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0UnQ4f5ypMBczNBvgrvU959v_vzuB8FYhSkLnt3cOOA">

This is still way too much.
 If you could make the tab bar and the search bar floatable(overlay) and hidden until hover, it would be perfect.

**Comment by xtrasmal** [comment]
At this point Brave is like an old guy, trying to lure people into his house, using healthy dry whole grain crackers.

Mr. Old Guy Sir, could you please stop telling me how great you are? Yes yes, thanks for the crackers. I enjoy those dry boring crackers whole day long. 

You keep telling me that **Brave puts me first**... but I feel you put privacy first. 

Zen and Arc will sell my soul to the market, but at least they do exactly what they promised.

Zen - welcome to a calmer internet...and some privacy
Arc - clean and calm, shapes itself to how you use the internet

Unfortunately I have put my trust in Brave.

**Comment by rexackermann** [comment]
Any updates ? I actually moved to zen and it seemed great ! Any plan for this yet ?

**Comment by gqtn** [comment]
Why this topic was closed?

**Comment by gqtn** [comment]
We already have something in Nightly version! 👍  (v1.81.135)

<img width="1886" height="1119" alt="Image" src="https://github.com/user-attachments/assets/26ba2e2b-db51-4df0-aca4-027ebb01ee00" />

**Comment by Terra972** [comment]
Can't find it in 1.81.137
EDIT: here the screenshot

<img width="615" height="497" alt="Image" src="https://github.com/user-attachments/assets/55f54695-c272-4d03-98fa-6fc0fd92c344" />

EDIT (22/10/25): Now I got that aswell! :)

**Comment by gqtn** [comment]
@Terra972, I can enable it in stable version:

<img width="1907" height="1182" alt="Image" src="https://github.com/user-attachments/assets/02ff221b-1c78-4ae5-9fda-a8c61fc1b678" />

**Comment by dkmar** [comment]
The Orion browser also has a [Focus Mode](https://blog.kagi.com/orion-features#:~:text=of%20Orion%20is-,Focus%20mode,-(%E2%87%A7%E2%8C%98F).%20This) that hides everything (sidebar and toolbar). This would be a nice feature and I would use it very frequently with a good keybinding. 


![Image](https://github.com/user-attachments/assets/a85b8169-cb07-48da-bcb9-a0873c7d4b06)

**Comment by Terra972** [comment]
@gqtn 
_#brave-vertical-tab-hide-completely_ stopped working for me in 142.1.84.141 stable (the flag is still there though)

**Comment by nihal-05** [comment]
Check this

https://github.com/brave/brave-browser/issues/50838#issuecomment-3697054429

**Comment by Necryl** [comment]
Great, now we need ability to hide the top bar, including the os level close and minimize buttons. Then Brave literally becomes perfect.
Keep in mind, in these extreme focus modes, holding down Ctrl+Tab should also show windows Alt+tab style previews of all the tabs. It becomes kind of essential to work with all bars hidden like that. But I can wait. I hope it is put on the roadmap though.
