### ISSUE TITLE
`Show pinned tabs in all windows` setting should be guarded by the brave-shared-pinned-tabs feature flag

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#40675]
## Description 

The `Show pinned tabs in all windows` is always visible in the Settings -> Appearance [Tabs]. However, if the feature flag `brave-shared-pinned-tabs` is not enabled (default) then this functionality doesn't work. The setting in the UI should be hidden when the flag isn't enabled.

**Repro:**
1. Start the browser and navigate to brave://flags
2. Search for brave-shared-pinned-tabs and verify that it's set to disabled (default).
3. Navigate to brave://settings/appearance and scroll down to the [Tabs] section
4. Enable "Show pinned tabs in all windows" setting
5. Navigate to brave.com
6. Right-click on the tab and select Pin
7. Observe the tab is now pinned
8. Open a new browser window via the hamburger menu
9. Observe the new window has no pinned tabs.

__Expected:__
1. No "Show pinned tabs in all windows" is shown in the Settings -> Appearance [Tabs] 

**Fix verification:**
1. Start the browser and navigate to brave://flags
2. Search for brave-shared-pinned-tabs and verify that it's set to disabled (default).
3. In another tab, navigate to brave://settings/appearance and scroll down to the [Tabs] section
4. **Verify** that there's no "Show pinned tabs in all windows" setting shown
5. In the first tab, enable the brave-shared-pinned-tabs flag and click Relaunch button.
6. Once the browser restarts, navigate to brave://settings/appearance and scroll down to the [Tabs] section
7. **Verify** that the "Show pinned tabs in all windows" setting is now shown and disabled (by default)
8. Navigate to brave.com
9. Right-click on the tab and select Pin
10. Observe the tab is now pinned
11. Open a new browser window via the hamburger menu
12. **Verify** the new window has no pinned tabs.
13. Enable the "Show pinned tabs in all windows" in the Settings -> Appearance [Tabs]
14. Open a new browser window via the hamburger menu
15. **Verify** the new window has brave.com pinned tab.

**Comment by jagadeshjai** [comment]
Checking...

**Comment by fepskieee** [comment]
Is this fixed? "Pinned tabs" setting is still showing and can be toggled even disabled by default in the "brave://flag"

**Comment by bsclifton** [comment]
@fepskieee fixed in the code - but the fix itself is only in Nightly so far.  We could possibly uplift it cc: @rebron

**Comment by LaurenWags** [comment]
Requires `1.70.107` or higher for verification 👍🏻

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.70.108 Chromium: 128.0.6613.120 (Official Build) beta (x86_64)
-- | --
Revision | 3624a617c5c520e5a5ce8d5bfdfb7d0a6a696e6a
OS | macOS Version 13.6.9 (Build 22G830)
```
