### ISSUE TITLE
scrisc.com shows interstitial in HTTPS Strict mode

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#40682]
### Description

Visiting http://scrisc.com/ in HTTPS Strict mode shows an interstitial, but it should just take us to https://scrisc.com/

### Steps to reproduce

1. Enable HTTPS strict
2. Open new tab
3. Visit http://scrisc.com/

### Actual result

Interstitial shown. Clicking proceed takes us to http://scrisc.com/

### Expected result

Should show https://scrisc.com/

### Reproduces how often

Easily reproduced

### Brave version

1.68+

### Device/iOS version

Any

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

Desktop/android issue:
https://github.com/brave/brave-browser/issues/40658

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7.1
Brave build: 1.72 (96)
BraveCore: 1.72.96 (131.0.6778.24)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/25544#issue-2523227177
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `http://scrisc.com/` is upgraded to `https://scrisc.com` when `Upgrade Connections to HTTPS` is set to `Standard` or `Strict` mode.
- Verified that `interstitial page` is not shown when `Upgrade Connections to HTTPS` is set to `Strict` mode.

---------------------------

|`Standard`|`Strict`|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/30619d15-b3d5-48bc-ad5e-43d237568fc3) | ![2](https://github.com/user-attachments/assets/f387c9c3-8036-4481-8a8a-04df57d82faa) |
| ![1](https://github.com/user-attachments/assets/1842a76c-26b8-4863-a689-5b0eab10071c) | ![2](https://github.com/user-attachments/assets/287f9ee2-ecd7-4eb8-ae61-89fcbab14609) |
| ![1](https://github.com/user-attachments/assets/beb3c17a-c9d8-40e6-8fc6-913a6d4e487b) | ![2](https://github.com/user-attachments/assets/c07bed51-8465-4905-a4ad-78f11d7a11b1) |
| ![1](https://github.com/user-attachments/assets/c7b94905-575f-4fae-8b4d-047da0728674) | ![2](https://github.com/user-attachments/assets/5a20507c-4bf1-4210-9f22-cb92eddfca1d) |
