### ISSUE TITLE
[AI Chat] Page content refine follow up

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#40686]
Crash when BYOM
https://github.com/brave/brave-core/pull/24953#discussion_r1731912121
and 
Leo prefix renaming
```
We added a class with the leo_ prefix instead of ai_ (or ai_chat_). Perhaps there was a good reason? Otherwise, we should keep it consistent.
```

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.71.102 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | d901535b1091c5f39eb2b5426b8fa8e7f3c5edf0
OS | Windows 11 Version 23H2 (Build 22631.4169)

- Verified steps from [brave/brave-core#25344](https://github.com/brave/brave-core/pull/25344)
- Verified no crash when using BYOM to answer queries with page reference 
- Encountered [#41079](https://github.com/brave/brave-browser/issues/41079)

https://github.com/user-attachments/assets/c9ae0d9a-2717-4bcd-8ad2-416cca80ad95

**Comment by srirambv** [comment]
Removing `OS/Android` and `OS/iOS` labels as BYOM is only applicable for desktop as of now
