### ISSUE TITLE
[Nala]: Remove Chromium color overrides

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#40689]
### Description

With the new Nala theming work @aguscruiz has been doing, it should be possible for us to remove a bunch of the overriding logic we have in our `brave_color_mixer` and `brave_tabs_color_mixer` and just use the underlying colors from Chromium.

As an added bonus, this means we can enable the tri-color themes Chromium is using now before they remove support for the old dual color themes.

**Note:*
As theming changes (especially to dark mode) are often controversial we should have a blog post explaining the changes.

### Solid Color Themes
Existing users, who've picked one of the solid color themes will not be affected by these changes. However, if they change their theme color the only way to get the solid color theme back will be to install that theme from the Chrome Web Store.

### Default Theme for New Users
By default Chromium sets the default theme to be the Gray/Blue theme. This is a bit different to the current default theme in Brave which is Gray/light gray. We should ensure that we default to the Gray/Gray theme.

### Dark Theme Changes
This is likely to be the most controversial part of the change. The new dark theme is slightly lighter than the existing dark theme, and is inherited from upstream. This will make it significantly easier for us to maintain, and there will be far fewer override points after this change.

However, people are often pretty unhappy when the colors in their browser change. As a mitigation, in a blog post we should point users to the [Just Black](https://chromewebstore.google.com/detail/just-black/aghfnjkcakhmadgdomlmlhhaocbkloab) theme in the Chrome Web Store, which should result in a suitably dark theme.

cc @rebron & @aguscruiz for all the stuff I've forgotten to mention.

### Approach

There are few parts to this change:
1. Remove unnecessary overrides
2. Enable Tri-Color themes by reverting patches
    - Revert https://github.com/brave/brave-core/commit/18090d165f7b6ade5d5d03d728facd8544484a1a
    - Revert https://github.com/brave/brave-core/commit/4877e2fc13c5961bb7193ae3fbc2efeec6b33265
3. Ensure Gray/Gray theme is selected by default

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.71.94 Chromium: 129.0.6668.59 (Official Build) beta (64-bit)
-- | --
Revision | 90ea886c66dbbc8d7c5aecda57b6ef3c4d513497
OS | Windows 11 Version 23H2 (Build 22631.4169)
```

Normal window: 

1. Installed 1.71.94
2. opened brave://settings/manageProfile in a new tab
3. confirmed new tri-color theme is shown with Grey is selected as a default color 
4. confirmed the new themes have a light/dark mode (which are different, unlike the old dual color themes)
5. The new light/dark theme should be largely similar to the existing light/dark theme????
6. confirmed vertical tabs looked as expected in light/dark mode
7. confirmed horizontal tabs looked as expected in light/dark mode
8. confirmed Omnibox still have hover/selected state when open
9. If you're editing text in the omnibox and close it, the omnibox should look the same as when its just showing the URL (unlike in Chromium)????

<details>
<summary>Horizontal tab view</summary>

tabs in horizontal view shown in default grey color

1.70.x | 1.71.x 
----- | -----
![image](https://github.com/user-attachments/assets/3182d7e4-f5ff-4b87-99db-f4c15f5f452b)|![2024-09-23_13h28_50](https://github.com/user-attachments/assets/eaf9472a-b360-4ad2-ae9a-8e0cb655fee2)
|![2024-09-23_13h37_54](https://github.com/user-attachments/assets/c49438cb-8c52-487b-9b98-7fcd97507907)|![image](https://github.com/user-attachments/assets/c9985d1a-4007-4876-8cff-cf5b9ef12b07)
![image](https://github.com/user-attachments/assets/7619aae9-a31b-4207-81f2-14db06a107fb)|![image](https://github.com/user-attachments/assets/c82388b7-ef0a-440e-a316-9e00c199b31c)


</details>

<details>
<summary>Vertical tabs </summary>

1.70.x | 1.71.x 
----- | -----
![image](https://github.com/user-attachments/assets/a91b6a88-4aee-4e18-9786-95f3b3c1d81f)|![image](https://github.com/user-attachments/assets/4c53d6cb-4235-461a-af76-f6d5ef8cb0a3)
![image](https://github.com/user-attachments/assets/870c2bc7-8c57-43e3-a62a-a4fb41b0016d)|![image](https://github.com/user-attachments/assets/74360034-1e91-4d3f-ac6d-155430edc69a)
</details>

<details>
<summary>omnibox hover/selected state when open</summary>

1.70.x | 1.71.x 
----- | -----
![image](https://github.com/user-attachments/assets/89f5c068-b447-42de-8338-684bfcf9c75b)|![image](https://github.com/user-attachments/assets/d9aebe9c-fbee-4982-ab38-f0439b323429)
![image](https://github.com/user-attachments/assets/60e57650-d866-4404-bd2b-fbb9dd6e395b)|![2024-09-23_14h25_38](https://github.com/user-attachments/assets/c0ce5aec-a62a-41c2-ae20-0094cb01b157)
</details>


<details>
<summary>New Window</summary>

Horizontal tab view

example | example | example | example | example 
----- | ----- | ----- | ------ | -----
![2024-09-23_17h19_57](https://github.com/user-attachments/assets/269661e2-ec43-4439-8e3d-9fea2700beaa)|![image](https://github.com/user-attachments/assets/f6a56482-dcd5-44dc-8ae4-7716fb6fc12e)|![image](https://github.com/user-attachments/assets/70dd657f-faf0-4b7d-906a-6fa44fb88df6)|![image](https://github.com/user-attachments/assets/7d09117e-aace-4be2-a014-93ac2fb9cda4)|![image](https://github.com/user-attachments/assets/550b2978-c2da-488f-ba01-5568f6f3e0f8)

Vertical tab view 

example | example | example | example 
----- | ----- | ----- | ----- 
![image](https://github.com/user-attachments/assets/0bd0c66f-76de-46ba-8e48-e59de534b386)|![image](https://github.com/user-attachments/assets/8cb782cd-08f2-4794-83d0-7cc7253e7eab)|![image](https://github.com/user-attachments/assets/e6a4213c-9c82-43f4-9611-b02f97d47abb)|![image](https://github.com/user-attachments/assets/ca060547-511d-432f-868b-cd6a954479e7)
</details>

<details>
<summary>Pick themes for 2nd profile</summary>

- Add new profile via hamburger menu
- verified custom color was picked by default
- entered a new profile name (Profile 2) 
- clicked Done

example | example | example | example 
----- | ----- | ----- | ----- 
![image](https://github.com/user-attachments/assets/6098a644-6317-4a07-aaac-cdcb0c6f0408)|![image](https://github.com/user-attachments/assets/4825830a-6010-46c3-b94d-c5d91f1a3ee9)|![image](https://github.com/user-attachments/assets/12958cb4-5cde-4200-871b-0006b7d70e9a)|![image](https://github.com/user-attachments/assets/fd345f90-3f58-4e34-aa5b-937f9799c1d5)
</details>


Private Window


Private window with Tor



Upgrade:

**Comment by btlechowski** [comment]
Verification `PASSED` using

Brave | 1.71.113 Chromium: 130.0.6723.58 (Official Build) (64-bit)
-- | --
Revision | 3ee74228044546a84c661332ddb441a7a68108fa
OS | Linux

1. Installed 1.71.113
2. opened brave://settings/manageProfile in a new tab
3. confirmed new tri-color theme is shown with Grey is selected as a default color 
4. confirmed the new themes have a light/dark mode (which are different, unlike the old dual color themes)
5. The new light/dark theme should be largely similar to the existing light/dark theme????
6. confirmed vertical tabs looked as expected in light/dark mode
7. confirmed horizontal tabs looked as expected in light/dark mode
8. confirmed Omnibox still have hover/selected state when open
9. confirmed If texted is edited in the omnibox and close it, the omnibox should look the same as when its just showing the URL 

<details>
<summary>Case 1: Normal Window - Default (Gray/Gray) - PASSED</summary>

<details>
<summary>Horizontal tab view</summary>

- Confirmed tab bar/inactive tabs in horizontal view shown in default gray color
- Confirmed active tab shown in white


![Image](https://github.com/user-attachments/assets/f38c6ce3-b0fc-46b7-a554-749b45e08803)|![Image](https://github.com/user-attachments/assets/d54d8a1c-e40e-4253-85fe-f50aba4b401e)|![Image](https://github.com/user-attachments/assets/94162428-b4d1-4f98-b89f-625ca2e261fa)|![Image](https://github.com/user-attachments/assets/29749a7d-a4b8-45de-8402-138600539188)
--|--|--|--


![Image](https://github.com/user-attachments/assets/380a008f-73e8-4797-8dae-e11f054828d2)|![Image](https://github.com/user-attachments/assets/e9d5ba34-09ed-426b-b2cf-f6d1b62e1e8d)|![Image](https://github.com/user-attachments/assets/558ca05d-b482-4fd3-a516-a252f0491723)|![Image](https://github.com/user-attachments/assets/9de91862-0eaf-4d6b-9f07-0aa61aac4912)
--|--|--|--


</details>

<details>
<summary>Vertical tabs - PASSED</summary>

- Confirmed vertical tab strip is not dark compared to 1.70.x which is expected as per the issue description
- Confirmed active tab shown darker than 1.70.x 

![Image](https://github.com/user-attachments/assets/11c84a5f-482a-4c18-97ab-5a0fa756188c)|![Image](https://github.com/user-attachments/assets/631f57dd-1db2-4360-b601-8f0584b9b0c2)
--|--

</details>

<details>
<summary>omnibox hover/selected state when open - PASSED</summary>

- Entered a string in the omnibox and hovered over the entries
- clicked in the omnibox
- opened a new tab and click anywhere to show placeholder in the omnibox

- Confirmed when hovered over, result entries were highlighted with gray
- Confirmed when hovered over on selected result, result was highlighted with gray
- Confirmed empty omnibox has reddish tone of Gray
 

![Image](https://github.com/user-attachments/assets/db89c81b-145e-4e35-884b-cc78c57e8f3f)|![Image](https://github.com/user-attachments/assets/5e4b7ed6-7a99-4603-ba07-a73bd1a21022)
--|--


![Image](https://github.com/user-attachments/assets/0681dd5e-e8a9-4340-b7ba-fc5cdf82e116)|![Image](https://github.com/user-attachments/assets/eb2f0cc9-32e8-488b-ac09-136511bad414)
--|--


- Background text and font of the results have coordinated colors in the omnibox

![Image](https://github.com/user-attachments/assets/4258a4b9-11e3-4424-a4ba-3d89d77dab56)|![Image](https://github.com/user-attachments/assets/cf58251e-5f5d-4d3c-a666-d0a82cf0068c)
--|--

</details>

</details>

<details>
<summary>Case 2: New Window - PASSED</summary>

- continued from Case 1 above
- opened New window via hamburger menu
- opened brave://settings/manageProfile
- selected `Violet` theme

**_Horizontal tab view_**

![Image](https://github.com/user-attachments/assets/a4c19f59-5649-45b2-a741-1936476e537d)|![Image](https://github.com/user-attachments/assets/76d25baf-9497-4945-9a0c-efbc02262209)|![Image](https://github.com/user-attachments/assets/3926a050-3c8d-443c-8336-3942fb89f087)|![Image](https://github.com/user-attachments/assets/7bef7d06-3561-4f21-b34d-76452731bf54)
--|--|--|--

**_Vertical tab view_**

![Image](https://github.com/user-attachments/assets/a3d1aa1c-da17-4fb7-9f75-ebf7a7f5834c)|![Image](https://github.com/user-attachments/assets/241f1c29-4121-4dcb-ba4d-bcb212707232)|![Image](https://github.com/user-attachments/assets/2f0985cf-0827-4fda-b98c-1b791b3f7bf0)
--|--


</details>

<details>
<summary>Multiple profiles - system generated custom color - PASSED </summary>

- Add new profile via hamburger menu
- verified custom color was picked by default
- entered a new profile name (Profile 2) 
- clicked Done

![Image](https://github.com/user-attachments/assets/77297ad0-0c43-4674-9a40-26f933c3b5cb)|![Image](https://github.com/user-attachments/assets/510dae41-7811-4c90-89a8-9d99fd3e844a)|![Image](https://github.com/user-attachments/assets/57584e90-00e2-41b5-be03-a9a3545536ad)|![Image](https://github.com/user-attachments/assets/a63558a6-6b23-4111-a6e5-9ffafbc342ad)
--|--|--|--

</details>

<details>
<summary>Install dark theme from Chrome store - PASSED</summary>

- Installed 1.71.94
- install [Just Black](https://chromewebstore.google.com/detail/just-black/aghfnjkcakhmadgdomlmlhhaocbkloab) theme via chrome webstore 

Horizontal tab view and vertical tab view looks a little darker with `Just Black` than Brave dark theme

![Image](https://github.com/user-attachments/assets/b874be07-9525-4531-8b83-e4013046230a)|![Image](https://github.com/user-attachments/assets/3e0e2381-acf9-48dc-9eb9-3d6070bad0c8)
--|--

</details>

<details>
<summary>Upgrade - PASSED </summary>

<details>
<summary>Existing theme is retained - PASSED</summary>

1. Installed 1.70.x
2. launched Brave
3. opened `brave://settings/manageProfile`
4. selected Pink
5. closed Brave
7. installed 1.71.x
8. launched Brave

- Confirmed tri color themes is shown in the brave://settings/manageProfile
- Confirmed omnibox with a URL placeholder text shows whitish
- Confirmed when hovered over, result entries were highlighted with gray
- Confirmed when hovered over on selected result, result was highlighted with gray

1.70.x
![Image](https://github.com/user-attachments/assets/55a0ac50-c6d0-4272-9a74-52d453239b2c)|![Image](https://github.com/user-attachments/assets/a4b7496d-7dea-4fd0-9f89-0c42ee09b3b5)
--|--

1.71.x
![Image](https://github.com/user-attachments/assets/280827a6-86af-46a9-b881-dc9aa84491d1)



</details>
