### ISSUE TITLE
[BYOM]: Allow users to set system prompt

### ISSUE THREAD

**Issue by LorenzoMinto** [brave/brave-browser#40690]
### Platforms

Linux, macOS, Windows

### Description

Add an extra field in the model setup where the user can enter their own system prompt.

**Comment by rajneesh-18** [comment]
Is there anyone working on this issue?

**Comment by VISHESH0932** [comment]
@LorenzoMinto  hello sir, can i work on this issue?

**Comment by jonathansampson** [comment]
> @LorenzoMinto  hello sir, can i work on this issue?
> 

Thank you for your offer to assist with this issue. There is currently an associated PR waiting to be merged. Please consider taking a look and sharing any feedback you may have! All the best!

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.74.18 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | 9e238f4e6036c0b250ffefd506a55813f3aad501
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from [brave/brave-core#25727](https://github.com/brave/brave-core/pull/25727)
- Verified setting custom system prompt, Leo uses the prompt to generate responses

https://github.com/user-attachments/assets/f519a172-af43-4657-83bf-2e3f485bb3b6

**Comment by awaescher** [comment]
Just to give a little feedback: I was looking forward to this since weeks and just noticed the update.
Thanks a thousand times, Brave is such a great browser. Really appreciate your work :heart:

![Image](https://github.com/user-attachments/assets/d1b32696-5db3-4291-8da2-61990d3d4b4a)

**Comment by jonathansampson** [comment]
> Just to give a little feedback: I was looking forward to this since weeks and just noticed the update.
> Thanks a thousand times, Brave is such a great browser. Really appreciate your work :heart:
> 
> ![Image](https://github.com/user-attachments/assets/d1b32696-5db3-4291-8da2-61990d3d4b4a)

Thank you for the kind words and support. Please let us know if there is any way we can further improve the feature 😁

**Comment by awaescher** [comment]
Honestly, Brave is so amazing with its ad blocking, web3 integration, accountless sync, and so much more. It's so easy to convince people to use Brave and noone I had onboarded returned to another browser yet.

> Please let us know if there is any way we can further improve the feature 😁

Soooo ... I did not want to use this as a platform for my requests but now that you're asking ... I found two minor things that would Leo BYOM just perfect: What do you think about #43119 and #43121?
