### ISSUE TITLE
PWAs in Brave should parity PWAs in Chrome

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#40702]
### Description

At some point, PWA behavior between Chrome and Brave changed and they are no longer parity with one another. This is the case in a couple ways:

**Create Shortcut =/= Install as app**
![image](https://github.com/user-attachments/assets/5b6c37a0-dbbf-408b-a1f8-2b8198ff186c)
I believe these options used to essentially do the same thing, however, Chrome now has both `Create shortcut` (which seems to create a shortcut on your [desktop] that points to the site) and `Install page as app` which installs the site as a PWA. 

**Chrome supports more sites**
While Brave does support this option for _some_ sites but showing the `Install as app` icon in the address bar, Brave now supports far less sites than Chrome does with respect to PWAs, including popular/widely used ones like all the Google Services, as well as other sites one might expect support for (search engines like duckduckgo, Wikipedia, Steam, ChatGPT, Twitch, for example).

**Open as window**
![image](https://github.com/user-attachments/assets/281bcdef-0430-41c5-acb1-19112fbb1eda)
While the `Open as window` option has been removed for both brave and Chrome — however, when a PWA is created and opened in Chrome, the site does in fact open in its own, separate window/instance. In Brave, the PWA just opens the site a new tab in the browser.

### Steps to reproduce

N/A

### Actual result

PWAs not supported for all sites or expected sites

### Expected result

PWA should parity behavior with Chrome

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

v1.69.153

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

https://community.brave.com/t/open-as-window-option-gone-aug-26th-2024/565232/12

**Comment by Saoiray** [comment]
I'll give some details below, but big thing I wanted to point out on the PWA is that Brave only allows for some websites while chrome seems to allow for practically all. 

### Brave does allow PWA for only some sites.
These will have the install icon ![image](https://github.com/user-attachments/assets/5e1f49f6-16bf-4981-8dd3-eca51fe3b535) in the search bar

### But it doesn't allow on most.
For example, you can check https://www.perplexity.ai/ or https://calendar.google.com/ to which Brave won't have the install icon ![image](https://github.com/user-attachments/assets/5e1f49f6-16bf-4981-8dd3-eca51fe3b535) in the search bar nor will it have it in the **Save and Share** menu 

## Example with Perplexity is below:

### Brave
![image](https://github.com/user-attachments/assets/933685ec-aec1-4023-a72d-d44398961073)

### Chrome
![image](https://github.com/user-attachments/assets/f8082459-4f15-40d4-81e8-86acd0b98a36)


# -NOTE-
When this was first reported on Community, we didn't even have the install button, such as ![image](https://github.com/user-attachments/assets/9e199ce3-5c7a-43ef-ab8a-939173311d53) available in the hamburger menu. It was only available via the search bar. It seems something has been triggered to where the sites that can be installed are showing up there. 

However, there's still the disparity. 

### Example Websites Brave Can Currently Create PWA:
https://www.crunchyroll.com/
https://www.yahoo.com/
https://anix.to/home
https://community.brave.com/
https://www.facebook.com/
https://twitter.com/home
https://www.reddit.com/

### Example Websites Brave Can't Create PWA but Chrome can:

https://www.perplexity.ai/
https://www.wellsfargo.com/
https://www.icloud.com/
https://moviesjoy.is/
https://watchmovies.nz/
https://duckduckgo.com/
https://www.cms.gov/

## Can be replicated on Release, Beta, and Nightly

**Comment by Saoiray** [comment]
### UPDATE
I'm still not seeing any changes for PWA, which is the main concern for this issue. However, regarding the other request that people had, which Matt mentioned, about the Open as window button when creating a shortcut, there is a workaround.

To bring back the Open as window option, go to `brave://flags` and set **Shortcuts not Apps** to `Disabled`. Once you do this, the option will appear again, as shown below:

![image](https://github.com/user-attachments/assets/73333853-8146-4164-9ef3-fa06b9f7dba4)

**Comment by CXwudi** [comment]
Basically the issue is that Brave can't allow user to create PWA for any site excepts for those sites that has PWA enabled.

**Comment by LZeugirdor** [comment]
> ### UPDATE
> I'm still not seeing any changes for PWA, which is the main concern for this issue. However, regarding the other request that people had, which Matt mentioned, about the Open as window button when creating a shortcut, there is a workaround.
> 
> To bring back the Open as window option, go to `brave://flags` and set **Shortcuts not Apps** to `Disabled`. Once you do this, the option will appear again, as shown below:
> 
> ![image](https://private-user-images.githubusercontent.com/99627477/362042316-73333853-8146-4164-9ef3-fa06b9f7dba4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NTExNjcsIm5iZiI6MTcyNDg1MDg2NywicGF0aCI6Ii85OTYyNzQ3Ny8zNjIwNDIzMTYtNzMzMzM4NTMtODE0Ni00MTY0LTllZjMtZmEwNmI5ZjdkYmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDEzMTQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYjBlYTMxNGExY2NhMmY1YmRkNmY0M2RjNzc2MjAyYWVhMGRjNWE2ODU5ZDE5YmQ4ZmU3Y2NhYjNiNDBlNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UVq4qBG_gLozq63khZGPPp3zkPUFkHw3W6AJGw6Zqys)

I was about to cry thinking this was a deprecated feature, it probably will be but I hope it will continue to be supported. I use this fairly often for websites with no PWA support. Thank you for the workaround.

**Comment by JSuenram** [comment]
> ### UPDATE
> I'm still not seeing any changes for PWA, which is the main concern for this issue. However, regarding the other request that people had, which Matt mentioned, about the Open as window button when creating a shortcut, there is a workaround.
> 
> To bring back the Open as window option, go to `brave://flags` and set **Shortcuts not Apps** to `Disabled`. Once you do this, the option will appear again, as shown below:
> 
> ![image](https://private-user-images.githubusercontent.com/99627477/362042316-73333853-8146-4164-9ef3-fa06b9f7dba4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NTc3NDIsIm5iZiI6MTcyNDk1NzQ0MiwicGF0aCI6Ii85OTYyNzQ3Ny8zNjIwNDIzMTYtNzMzMzM4NTMtODE0Ni00MTY0LTllZjMtZmEwNmI5ZjdkYmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDE4NTA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1M2YzODhlNWI4ZDZhOGQyMDgzMGY1ZTJhOThiNWYxOGFiZDBkN2YzODVkOWE1ZWY5MDdlMzRhYjY0ZDc5ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ao3BbJpXG68KkfrSo-tBZyIZGsAu2sZm-DdpSaUIrGo)

Thank you very much.... managing about 50 Customers Firewalls I really need this option as I have them directly accesible in a Mac-Folder Menu.... If this option will get removed I will have to lookout for another browser..... hope not....

**Comment by emerick** [comment]
Probably related to brave://flags/#web-app-universal-install being disabled.

**Comment by nunu** [comment]
TY for brave://flags/#web-app-universal-install

but what for extension as PWA?

**Comment by pnimakada** [comment]
> TY for brave://flags/#web-app-universal-install
> 
> but what for extension as PWA?

You can usually take the extension link in the address bar when it's open and try to create a shortcut as well. 
Please note that the shortcut becomes absolute when the extension is updated, as the link changes.

**Comment by BionicBison05** [comment]
> You can usually take the extension link in the address bar when it's open and try to create a shortcut as well. Please note that the shortcut becomes absolute when the extension is updated, as the link changes.

This definitely isn't ideal. I'd like to be able to turn extension pages into PWAs like I did in the past, if at all possible.

**Comment by pnimakada** [comment]
> > You can usually take the extension link in the address bar when it's open and try to create a shortcut as well. Please note that the shortcut becomes absolute when the extension is updated, as the link changes.
> 
> This definitely isn't ideal. I'd like to be able to turn extension pages into PWAs like I did in the past, if at all possible.

How did you do this in the past? I'm not aware of any method, except for this one, to turn extensions into PWAs.

**Comment by BionicBison05** [comment]
> How did you do this in the past? I'm not aware of any method, except for this one, to turn extensions into PWAs.

I just tested using Brave v1.68.137 (an arbitrary previous release that has the old behavior). In this version, the "create shortcut" option had a checkbox to "open as window" which effectively installed the page as a PWA. This checkbox is now missing, and the "create shortcut" option now just puts a link on the desktop that opens a tab in Brave instead of installing an app that opens as a separate window. See the attached screenshots. On websites, this problem is fixed by the option to "install [site]" when the previously mentioned flag is enabled, but this is absent for extension pages, so the flag does not fully solve the problem.

<img width="441" alt="Screenshot 2024-09-11 at 11 34 08 AM" src="https://github.com/user-attachments/assets/2503613b-dcc5-4295-a47b-d456c32d432d">

<img width="1196" alt="Screenshot 2024-09-11 at 11 38 10 AM" src="https://github.com/user-attachments/assets/d645beca-d921-4343-85cc-448952e87569">

**Comment by pnimakada** [comment]
> > How did you do this in the past? I'm not aware of any method, except for this one, to turn extensions into PWAs.
> 
> I just tested using Brave v1.68.137 (an arbitrary previous release that has the old behavior). In this version, the "create shortcut" option had a checkbox to "open as window" which effectively installed the page as a PWA. See the attached screenshots. This checkbox is now missing, and the "create shortcut" option now just puts a link on the desktop that opens a tab in Brave instead of installing an app that opens as a separate window. On websites, this problem is fixed by the option to "install [site]" when the previously mentioned flag is enabled, but this is absent for extension pages, so the flag does not fully solve the problem.
> 
> <img alt="Screenshot 2024-09-11 at 11 34 08 AM" width="441" src="https://private-user-images.githubusercontent.com/93722725/366530124-2503613b-dcc5-4295-a47b-d456c32d432d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNzE3NjAsIm5iZiI6MTcyNjA3MTQ2MCwicGF0aCI6Ii85MzcyMjcyNS8zNjY1MzAxMjQtMjUwMzYxM2ItZGNjNS00Mjk1LWE0N2ItZDQ1NmMzMmQ0MzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDE2MTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYWY0NjI1MDY3ZWI1MzgwODY2ZWRiYWEyMDQ4NjdmNDZmOWY5OGU1MjEyNDNkOGYxMDdlNWQ0ODFmMWIwZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9owMp1hJMrqv5H5FoZU7yxXO9i_gVAek-zfHW8QqZZE"> <img alt="Screenshot 2024-09-11 at 11 38 10 AM" width="1196" src="https://private-user-images.githubusercontent.com/93722725/366530151-d645beca-d921-4343-85cc-448952e87569.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNzE3NjAsIm5iZiI6MTcyNjA3MTQ2MCwicGF0aCI6Ii85MzcyMjcyNS8zNjY1MzAxNTEtZDY0NWJlY2EtZDkyMS00MzQzLTg1Y2MtNDQ4OTUyZTg3NTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDE2MTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwM2JjYzczODJmMTM5N2Y1NGRkZmU3Y2I5NGUxNzMyYTQ0ZWMzNzU4MjBhZWYxY2ZmNWM3MTU4ODIwMGJlZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sRBngFeSVdfkeKbe_lraDlMc0jIgCXDeBTqdSSQ-PeU">

I mean, this method is the one I was talking about, and it's working fine for me now with the flag enabled. I don't know why it's not working for you, but either way, when the extension is updated, the ID changes. Therefore, the app won't open until you repeat the steps again. It's been like this for as long as I can remember.

**Comment by BionicBison05** [comment]
> I mean, this method is the one I was talking about, and it's working fine for me now with the flag enabled. I don't know why it's not working for you, but either way, when the extension is updated, the ID changes. Therefore, the app won't open until you repeat the steps again. It's been like this for as long as I can remember.

Ah, there appears to have been a misunderstanding on my end. I was referring to the `brave://flags/#web-app-universal-install` flag, which fixed websites but not extension pages. Disabling the `brave://flags/#shortcuts-not-apps` flag does indeed solve the extension pages problem for me. Knowing this, it would be nice if Brave could keep some form of this functionality, as the fact that this flag was enabled by default suggests the "open as window" functionality may be removed entirely in the future, which would hurt my workflow.

**Comment by pnimakada** [comment]
Exactly, PWA is the only feature preventing me from fully switching to Firefox.

**Comment by nunu** [comment]
> Exactly, PWA is the only feature preventing me from fully switching to Firefox.

try https://pwasforfirefox.filips.si/

both browsers have good features, and yes without PWA a will migrate more to firefox

**Comment by Brave-Matt** [comment]
Just wanted to let everyone here know that for now, you can set the flag `brave://flags/#shortcuts-not-apps` to `Disabled` and this should resolve the issue. Note that we will be changing the "default" value to back to `Disabled` soon, which should resolve the issue for everyone.

**Comment by landoncarbenia** [comment]
> Just wanted to let everyone here know that for now, you can set the flag `brave://flags/#shortcuts-not-apps` to `Disabled` and this should resolve the issue. Note that we will be changing the "default" value to back to `Disabled` soon, which should resolve the issue for everyone.

hey @Brave-Matt, #shortcuts-not-apps is still defaulting to Enabled in both Release and Nightly. when will this be flipped to Disabled?

and for my own curiosity, does Brave have a timeline for adding separate "Install page as app" and "Create shortcut..." buttons like upstream Chromium?

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.74.10 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | bdff9e7d7314280ddbce1c3ada3abee4ce4a3b32
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

1. Installed 1.74.10
2. launched Brave
3. opened brave://flags/#shortcuts-not-apps in a new tab
4. confirmed the flag was `Disabled` by default
5. visited https://www.perplexity.ai/  in a new tab
6. clicked hamburger menu >> Save and Share 
7. confirmed `Install page as app` option is available compared `1.73.91`
8. clicked `Install page as app`
9. confirmed `Install this page as an app` dialog is shown
10. clicked `Install` 
11. confirmed the site opened in its own, separate window/instance, compared with chrome 
12. opened brave://apps
13. confirmed `Perplexity` shortcut is shown
14. visited https://www.wellsfargo.com/ in a new tab
15. clicked hamburger menu >> Save and Share 
16. clicked `Create shortcut` 
17. clicked `Create` on the `Create shortcut` 
18. checked `Open as window`
19. confirmed the site opened in its own, separate window/instance, compared with chrome 
20. opened brave://apps
21. confirmed `Wells Fargo Bank` shortcut is shown

step 4 | step 7 (1.74.x) | step 7 (1.73.x) | step 9 | step 11a | step 11b | step 13 | step 16 | step 18 | step 19 | step 21
------ | -------- | -------- | ------- | ------ | ------ | ------ | ------ | -------- | ------- | ---------- 
![Image](https://github.com/user-attachments/assets/3d4bd3a6-c223-4029-bad0-c28a96918d10)|![Image](https://github.com/user-attachments/assets/903c84ea-9299-47c6-b1cf-ade39406a79d)|![Image](https://github.com/user-attachments/assets/273b9e4e-c01a-41d4-881b-2a9f13a788e3)|![Image](https://github.com/user-attachments/assets/caa70839-29dc-4673-9f96-5f896a91375e)|![Image](https://github.com/user-attachments/assets/d1df2c28-bb67-41d6-a0db-333130d42adb)|![Image](https://github.com/user-attachments/assets/239910f4-f709-4c84-ac34-d5ec30a9e042)|![Image](https://github.com/user-attachments/assets/7ec9a364-cd3f-4055-a78b-7c5305034915)|![Image](https://github.com/user-attachments/assets/ea295dae-cf45-4642-a223-2e70fdd6d294)|![Image](https://github.com/user-attachments/assets/bfecdd74-0f3c-4ee1-aea0-68130e25af37)|![Image](https://github.com/user-attachments/assets/adf37010-fd39-4341-8632-08e7bcc87cb3)|![Image](https://github.com/user-attachments/assets/cd85c3f7-9719-4440-9154-5597df38ded3)

**Comment by BionicBison05** [comment]
This is broken again for me. Did something change?

**Comment by null-von-sushi** [comment]
Seems like it. The referenced flags all don't seem to exist, and the 'open as window' option is missing.
```
Brave 1.82.170 (Official Build) (64-bit)](https://brave.com/latest/)
Chromium: 140.0.7339.186
```
This is on Linux (aarch64 build)

**Comment by lippytak** [comment]
Confirming all the relevant flags for this feature are gone in v1.85.117 on Mac. Neither `brave://flags/#web-app-universal-install` nor `brave://flags/#shortcuts-not-apps` exist.

Chrome still has `More > Cast, Save, Share > Install page as app` and Shortcut features enabled by default.

@Brave-Matt do you know if this is intended or should we reopen this issue?

**Comment by fallaciousreasoning** [comment]
Interesting - it still seems to be working for me (arch)

<img width="2002" height="1143" alt="Image" src="https://github.com/user-attachments/assets/21c5d5a2-85b2-4854-9b76-0c477eb4887e" />

I think maybe upstream has separated them into 
1. Install page as App (or Install, if its an actual PWA) to open as window
2. Create shortcut (to just make a shortcut).

If you create it as a PWA, it should show up in `brave://apps` and if you right click you should be able to toggle `Open as window`

<img width="450" height="414" alt="Image" src="https://github.com/user-attachments/assets/bec8edd1-94c0-4687-89a3-ba3baa29ce06" />

**Comment by lippytak** [comment]
@fallaciousreasoning you're completely right, sorry I must have just missed that because I assumed the flags were still required. Thanks 🙏

**Comment by fallaciousreasoning** [comment]
No worries! I'm always happy when people are using PWAs - I've been experimenting with enabling the tabbed PWAs option too (if you go into App Settings on chrome://apps). Its pretty experimental but be interesting to hear if you have any feedback!
