### ISSUE TITLE
Strip behiiv link IDs from URLs

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#40716]
I noticed a `_bhlid` parameter in the following link: https://techcrunch.com/2024/08/26/anthropic-publishes-the-system-prompt-that-makes-claude-tick/?_bhlid=0b2d1e067fdf041e2c1a357f8466ab8c3df13f76

and then from PublicWWW I found [another example](https://www.fortwhyte.org/events/month/?_bhlid=0e32c9e4e9dee4e476d613ed473c7ef67fd2dd03&pagename=visit%2Fcalendar&shortcode=550bcfbb&utm_campaign=hollywood-star-visits-winnipeg-goldeyes-game&utm_medium=newsletter&utm_source=winnipeg-digest.beehiiv.com) that pointed me in the direction of [beehiiv.com](https://www.beehiiv.com/).

Given that they advertise the ability to [track clicks and opens](https://developers.beehiiv.com/docs/v2/bcb8390a98fc8-show), I assume that `_bhlid` stands for beehiiv link ID and that this is a unique identifier that can be traced back to an individual newsletter subscriber.

**Comment by fmarier** [comment]
I found an [example newsletter](https://winnipeg-digest.beehiiv.com/) with an [unsubscribe link](https://link.mail.beehiiv.com/ss/c/u001.EhZGQdrdvHbDoyXg6oiqE8stodr9iv_dhrS0IwPUokVvajPgSRdHbPZmLk-v1wueJNd8Sda76gGRgrhLBiX3xo9y4hfrE4spn9I-2mIvm8nu8hWFMqp0FZI2sasfx7YH20MsV70Rj3l-MKp_6TJPfJGI31yjZLFsPLu4LfnPbSpA5JJ2YTcxTqJgWMcR6pHRQnQhe23GBChpNPy5T5gPM-xVsE2fxscnGBQ9gT9d_FZrFLrNoj4g3XCjQVVpLLAfEP45g3N0Cz0r3F1ARuqknNXJr1aYYhyVHJFdihB1fSo4fqTPf3sKIR--IBilhhaKD5RoSiRMLjVMZM5ErRo94W_1sYE8Mx8EXLfLTa3c18Ubyge5r_SYOGEQhKOyIwlu39rg7KVyJtJa8-oLAnH-GoGSSSB1dR2c9IqJWX91jhRXbHSxBLAgvPuMXx39pjybX10BOFenU2TX84uTmx7Qw_ja4_sNGGiba3UKetX6QcwMcZITvyP6iT0YyUEs5ei6nTGwJAybppptIHgunqMEG6siQU50dO07_jwpphuqllsy7aQAGYmkd3XeZVwpDwV-aCmhieO6LoGYx8XJghxNNvH6xpDHRBtRjXy0OuI5rrPTOpBUowPfIY1GPVVLAdKobJMh6_LHT82c9stqm_RFYw/499/YsTN1FczRRK7xiuZZTS_SA/h1/h001.KR-qe4fQyPGpa3nlvjj3JatqXa96FjzQivEmDAiPHT8) going first to 
https://winnipeg-digest.beehiiv.com/subscribe/68569798-5d30-4097-9253-ce711164da4f/manage?last_resource_guid=EmailMessage%3A3bb91db1-0753-440d-8ec9-e5976971be2c&last_resource_guid=EmailMessage%3A3bb91db1-0753-440d-8ec9-e5976971be2c&jwt_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWJzY3JpYmVyX2lkIjoiNjg1Njk3OTgtNWQzMC00MDk3LTkyNTMtY2U3MTExNjRkYTRmIiwiZXhwIjoxNzI0OTU2MjE1LCJpc3MiOiJodHRwczovL2FwcC5iZWVoaWl2LmNvbSIsImlhdCI6MTcyNDc4MzQxNX0.-FAzoXxy793gNeunJ6PTk1XCN3GLrZiata-DjDQiJWg 
then to http://winnipeg-digest.beehiiv.com/subscribe/68569798-5d30-4097-9253-ce711164da4f/manage?last_resource_guid=EmailMessage%3A3bb91db1-0753-440d-8ec9-e5976971be2c&last_resource_guid=EmailMessage%3A3bb91db1-0753-440d-8ec9-e5976971be2c

The `_bhlid` parameter is not involved at all and so it's not needed to unsubscribe.

The ["read online" link](https://link.mail.beehiiv.com/ss/c/u001.EhZGQdrdvHbDoyXg6oiqE8stodr9iv_dhrS0IwPUokU2Ss7FkA9faH26nHywlQsHklc3LEXjKxYX9-yL9UtZ2IRHA8azRtsRaLmvFkUXRe-WV1XpwglUBnXPSzU4dLenzYA6kuTfMErUDZvHefWhPd9SJlPzEDucM7EDt3hnoW5EzPVm6XDCeWQ14byg2fVN_kJ3FOp2QiR7W-QB3gEqsm6yt7xZ4LHt0tc24n5Kc7QOFaw-5hnNx-RvElFaFQ--5zS3-cSXW7cd6L74Ord2qPgqa_eO9GbGyokr7xxPxn147bF-XWc2z-RKvYgdDVbpgldubcYaIs4J6eXqOdcl5B6NEFEyoGbgNaxHhbY-jAm-qL0T7lc1DrtRUV_u4P9EmUPEm2EXN5fz7BcqeWQvzFi4GLbQv3h4C9so2YqWBYCfn4qEUVCa9fXQly1NXhex0AHQZVJTky6AWYIas_uif1NMIcBZkm34ma-V1YDu7gccPLmm5Zz5d9Du0Ee-PIt4XUOrmcG3AjCW5uRk9zQuQIVcUNfX73vRviw6o2pVK5r6xHUfSKq2yhwk_Gy2PsI4668_T6MzPEKT4ke-_VlpyPGLV51wfp7ny6qiEBIfQj4r3BvsDYjdxKL-reKxZYXMZW-b-KRE1Pbhp0aJvXNB-adjdChEfwQUN0DAzfKrEs1e8BGZfTnGaPNiKBnD5TkqA3K9e7h-qjOQQtyUBsN1zOPmWgjC5IukCgjAqpOuo8Y/49a/jGEVUwlISJexSkqdXiJ0fg/h0/h001.gNFfJWbAA1z4O7dtYUwxtrxMqBmRaaQ5tseysH68HVk) goes to https://winnipeg-digest.beehiiv.com/p/free-manitoba-parks-entry-weekend?_bhlid=22ba2deac78828960ee1ef01a631450a69e47743&utm_campaign=free-manitoba-parks-entry-this-weekend&utm_medium=newsletter&utm_source=winnipeg-digest.beehiiv.com

which **does use** the `_bhlid` parameter, but removing it still leads to a [working page](https://winnipeg-digest.beehiiv.com/p/free-manitoba-parks-entry-weekend?utm_campaign=free-manitoba-parks-entry-this-weekend&utm_medium=newsletter&utm_source=winnipeg-digest.beehiiv.com)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.90 Chromium: 129.0.6668.59 (Official Build) beta (64-bit)
-- | --
Revision | 1f5f0d1b8a45a4c60a78c15df081751e39184b97
OS | Windows 11 Version 23H2 (Build 22631.4169)
```

Reproduced `1.70.117`

![image](https://github.com/user-attachments/assets/4e98ca35-7ad8-4b8c-bf05-7a8e3d2b43ec)

1. Installed 1.71.90
2. launched Brave
3. opened `brave://settings/shields` in a new tab
4. verified Trackers & ads blocking shows Standard
5. visited https://brave.com/?_bhlid=123456

#### Confirmed that the URL bar only shown https://brave.com/ and no `_bhlid  = 123456` parameter.

example | example 
------ | -----
![image](https://github.com/user-attachments/assets/a8fb1a2a-7fdc-4224-910d-2c6bc9cf3900)|![image](https://github.com/user-attachments/assets/28718e29-d5c8-402c-92b6-870eebcf1c06)

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.71.104 x64 Beta build
- Verified steps from issue description
- Verified with Shields set to `Block trackers & ads (Standard)` visiting `https://brave.com/?_bhlid=123456` redirects to `https://brave.com` and removes **`?_bhlid=123456`**
 
https://github.com/user-attachments/assets/94db58b7-fc2f-4a10-be6c-a8184f5f3c5a

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7
Brave build: 1.71 (116)
BraveCore: 1.71.116 (130.0.6723.58)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/25364#issue-2492869880
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `_bhlid=123456` parameter is removed when navigating to `https://brave.com/?_bhlid=123456` and redirects to `https://brave.com/` when `Trackers & Ads Blocking` in `Brave Shields` is set to `Standard`.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/d40fbe5e-779e-439d-a0c5-f978d992ced3) | ![2](https://github.com/user-attachments/assets/25141f64-4e9d-4a64-8b0d-71acf7555046) | ![3](https://github.com/user-attachments/assets/896a570c-ce7a-4052-b3c3-e38ce538ea00) | ![4](https://github.com/user-attachments/assets/f0628102-fb7e-4784-a39f-8389d2feba0d) |
