### ISSUE TITLE
Follow up - Tab separator has too much contrast on both light and dark mode

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#40714]
### Description

Follow up to https://github.com/brave/brave-browser/issues/40608

Got feedback that there's still too much contrast between between the separator and the tabbar. Let's do the following:

- Reduce opacity of separator to 50%
- Change height of separator from 24px to 16px and center it vertically

That should make it look like the attached screenshot.

Figma reference:
https://www.figma.com/design/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?node-id=7913-31400&t=YkcfLB3xQ93kkxjV-1

### Steps to reproduce

-

### Actual result

![image](https://github.com/user-attachments/assets/c10ff493-ad7e-4bf0-9a51-ba054badfd16)

### Expected result

![image](https://github.com/user-attachments/assets/85fc34cc-4ed9-4355-b4c9-1ed53e2fcfd5)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.155

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by aguscruiz** [comment]
@rebron let me know if the expected result screenshot is looking good for you. I think it's subtle enough

**Comment by fallaciousreasoning** [comment]
Note: Talked to @aguscruiz and we increased the opacity to 75%

**Comment by aguscruiz** [comment]
Latest looks great on this version 
https://github.com/brave/brave-browser/releases/tag/v1.71.42

**Comment by fallaciousreasoning** [comment]
@LaurenWags should this be marked `release-notes/exclude` instead?

**Comment by LaurenWags** [comment]
@fallaciousreasoning since this issue changes both color and size for tab separator, I marked it as `release-notes/include` because if this makes it into 1.69.x it would supersede the changes made with https://github.com/brave/brave-browser/issues/40608 (which is also `release-notes/include` for now). definitely open to changing that if others feel differently - was basically just following what we did for 40608.

cc @kjozwiak @rebron for additional input 👍🏻

**Comment by kjozwiak** [comment]
The above requires `1.69.159` or higher for `1.69.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.69.159 Chromium: 128.0.6613.114 (Official Build) (64-bit)
-- | --
Revision | b60455471a6aad96b2f031c679838da121f22b03
OS | Windows 10 Version 22H2 (Build 19045.4780)
```
- Verified the description from the issue on `1.69.159` and ensured the followings:
   - Opacity of the separator reduced to 50%
   - Changed the height of separator from 24px to 16px and center it vertically
   
### 1.69.159 - Light theme Vs Dark theme

![image](https://github.com/user-attachments/assets/828a768a-81c8-42d1-be46-f3be2f4d2ee1) 
![image](https://github.com/user-attachments/assets/65e927b1-675b-4fbe-965d-12aa4c6fc1a3)
-----
### 1.69.155 - Light theme Vs Dark theme

![image](https://github.com/user-attachments/assets/391e9c1c-9261-49af-b890-36ae522490ff)
![image](https://github.com/user-attachments/assets/33a0f0d4-c8f8-407b-a8e5-16c83cec655d)

### 1.69.153 - Light theme Vs Dark theme

![image](https://github.com/user-attachments/assets/044d90da-7314-4b14-8a72-cf4a38e35a44)
![image](https://github.com/user-attachments/assets/9d4cdc19-e104-4e86-8731-12a6233d2d74)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.69.159 Chromium: 128.0.6613.114 (Official Build) (x86_64)
-- | --
Revision | b60455471a6aad96b2f031c679838da121f22b03
OS | macOS Version 13.6.9 (Build 22G830)
```

Compared tab separator colors on `1.69.153` (current release) to `1.69.155` (previous RC with change from https://github.com/brave/brave-browser/issues/40608) to `1.69.159` for light and dark themes:

`1.69.153` | `1.69.155` | `1.69.159`
--- | --- | ---
<img width="1202" alt="153 lt" src="https://github.com/user-attachments/assets/238930c2-76b0-4f5d-9bcf-b528fcf78f08"> | <img width="1202" alt="155 lt" src="https://github.com/user-attachments/assets/147a19ff-5872-4a82-b9ef-6bfce4fff73d"> | 
<img width="1091" alt="153 dk" src="https://github.com/user-attachments/assets/032b564e-04b0-4145-b1a9-8401bb7cc62d"> | <img width="1192" alt="155 dk" src="https://github.com/user-attachments/assets/1ba9789c-e642-4509-be25-bf38b261cc2f"> |

**Comment by GeetaSarvadnya** [comment]
Verified **INPROGRESS** on

```
Brave | 1.69.159 Chromium: 128.0.6613.114 (Official Build) (arm64)
-- | --
Revision | b60455471a6aad96b2f031c679838da121f22b03
OS | macOS Version 12.5 (Build 21G72)
```

Compared tab separator colors on `1.69.153` (current release) to `1.69.155` (previous RC with change from https://github.com/brave/brave-browser/issues/40608) to `1.69.159` for light and dark themes:

`1.69.153` | `1.69.155` | `1.69.159`
--- | --- | ---

**Comment by aguscruiz** [comment]
Looks great on v1.69.159
https://github.com/brave/brave-browser/releases/tag/v1.69.159

<img width="865" alt="image" src="https://github.com/user-attachments/assets/6ed657cd-8e66-4511-871b-d05a62255857">

<img width="975" alt="image" src="https://github.com/user-attachments/assets/5f1ac9d4-706d-4245-ab17-36eaf1b799c1">

**Comment by btlechowski** [comment]
Verified with

Brave | 1.69.159 Chromium: 128.0.6613.114 (Official Build) (64-bit)
-- | --
Revision | b60455471a6aad96b2f031c679838da121f22b03
OS | Linux


![image](https://github.com/user-attachments/assets/6e6d5f42-cba0-46a5-8531-d46a9d6d551d)|![image](https://github.com/user-attachments/assets/cb74b18f-072b-43f4-81e7-ce7efc0c3999)
--|--
