### ISSUE TITLE
Pandora login/registration is failing

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#40715]
### Description

Pandora registration and login is not working on Brave, even without Shields.
It also seems to be broken on DuckDuckGo, but not broken on Chrome + GPC (via extension) or Firefox + GPC turned on.

#### Registration

I tried creating a new account on https://www.pandora.com/account/register but I get an `Email has already been registered` error even though I don't have an account with that email address.

#### Login

I tried logging into a new account on https://www.pandora.com/account/sign-in but get an `Incorrect Email or Password` error. Works fine on Firefox.
Related community post for login failure: https://community.brave.com/t/cannot-log-into-pandora/565400/3

### Steps to reproduce

1. Go to https://www.pandora.com/account/register
2. Go to https://www.pandora.com/account/sign-in 
3. Try registering or logging in

### Actual result

Login error:
![image](https://github.com/user-attachments/assets/8488e2e0-fbc2-4bee-a4af-c2095fc58058)

Sign Up error:
![image](https://github.com/user-attachments/assets/bb456e5f-e6ae-4b80-be7e-0b609eef9d79)

### Expected result

Login and registration should work

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.77 Chromium: 128.0.6613.27 (Official Build) nightly (arm64) 
Also reproducible on Release

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by ryanbr** [comment]
Regression testing:

```
https://github.com/brave/brave-browser/releases/tag/v1.54.43  No
https://github.com/brave/brave-browser/releases/tag/v1.47.56  No
https://github.com/brave/brave-browser/releases/tag/v1.37.53  No
https://github.com/brave/brave-browser/releases/tag/v1.36.41  No
https://github.com/brave/brave-browser/releases/tag/v1.35.65  No
https://github.com/brave/brave-browser/releases/tag/v1.35.63  No
https://github.com/brave/brave-browser/releases/tag/v1.35.61  No
https://github.com/brave/brave-browser/releases/tag/v1.35.59  yes
https://github.com/brave/brave-browser/releases/tag/v1.35.52  yes
https://github.com/brave/brave-browser/releases/tag/v1.35.46  yes
https://github.com/brave/brave-browser/releases/tag/v1.35.33  Yes
https://github.com/brave/brave-browser/releases/tag/v1.34.23  Yes
https://github.com/brave/brave-browser/releases/tag/v1.32.63  Yes
```

Suspect: https://github.com/brave/brave-core/pull/11638

**Comment by ryanbr** [comment]
brave://flags/#navigator-connection-attribute  (enabling this fixes it)

**Comment by ryanbr** [comment]
cc: @mkarolin

**Comment by mkarolin** [comment]
That feature was disabled per https://github.com/brave/brave-browser/issues/20122. cc: @pes10k @ShivanKaul
