### ISSUE TITLE
Fix Wallet Portfolio Segmented Control Sizing

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#40718]
### Description

The `Segmented Control` on the `Wallet` portfolio page is to big in the `Panel` and has to much `Padding`.

### Steps to reproduce

1. Open the `Wallet` panel and navigate to the `Portfolio` page
2. The `Segmented Controls` are to big and have to much `padding`

### Actual result

![Screenshot 39](https://github.com/user-attachments/assets/f72d0ebe-385d-4591-b3c8-6892234ff4cd)

### Expected result

![Screenshot 40](https://github.com/user-attachments/assets/ff784aef-d56f-4381-af60-a6da5338d843)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.92 Chromium: 128.0.6613.85 (Official Build) beta (arm64) 

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.71.97 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | de99cbcb1aa0aa00877d356e4733f4e5481e89eb
OS | Windows 11 Version 23H2 (Build 22631.4169)

- Verified steps from [brave/brave-core#25428](https://github.com/brave/brave-core/pull/25428)
- Verified segmented controls are now bigger and spanned 

Portfolio | Panel
-- | --
![image](https://github.com/user-attachments/assets/b4f47a9b-4adc-495a-b381-8d1b68775791) | ![image](https://github.com/user-attachments/assets/2828185b-9115-434c-8c56-d917d71a5364)

Portfolio Asset | Panel
-- | --
![image](https://github.com/user-attachments/assets/00616d14-abaf-42b2-8e23-992b7d572ac2) | ![image](https://github.com/user-attachments/assets/6cdd93a4-fff1-4a93-847f-31df86bad0f1)


Edit Visible Asset | Panel
-- | --
![image](https://github.com/user-attachments/assets/e64e5436-3b57-4a94-bffc-a3696435e8aa) | ![image](https://github.com/user-attachments/assets/f9bea341-e8ab-4ff3-8853-9b31002f11ea)


Explorer | Panel
-- | --
![image](https://github.com/user-attachments/assets/424075a5-1765-4ea4-afba-c32634ea31a2) | ![image](https://github.com/user-attachments/assets/c1b396db-7d74-462a-9825-68494175fee6)

Account Details | Panel
-- | --
![image](https://github.com/user-attachments/assets/e59ad859-967b-4320-a445-223d03c86ed9) | ![image](https://github.com/user-attachments/assets/8510faca-d62a-4e87-adb6-3354a395b61f)
