### ISSUE TITLE
Split `Brave.Core.PagesLoaded` by default search engine

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#40722]
Split the pages loaded metric into two:

As a user with Brave as the default search engine, how many pages did you load in the past week?
`Brave.Core.PagesLoaded.BraveSearchDefault`

As a user with a non-Brave default search engine, how many pages did you load in the past week?
`Brave.Core.PagesLoaded.OtherSearchDefault`

Keep the same buckets.

cc @porteron

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.71.101 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | 734075a5959db3e93d6def81a15e1fc6c2609fc2
OS | Windows 10 Version 22H2 (Build 19045.4894)
```

<details>
<summary>Brave.Core.PagesLoaded.BraveSearchDefault_0</summary>

</details>

<details>
<summary>Brave.Core.PagesLoaded.BraveSearchDefault_1</summary>

</details>

<details>
<summary>Brave.Core.PagesLoaded.BraveSearchDefault_2</summary>

</details>

<details>
<summary>Brave.Core.PagesLoaded.BraveSearchDefault_3</summary>

</details>
