### ISSUE TITLE
 offering to translate Russian in page translate

### ISSUE THREAD

**Issue by vvzvlad** [brave/brave-browser#40734]
### Description

Is it me or Brave is not offering to translate Russian in the settings option "Automatically translate these languages" ?
There is Ukrainien, Belarusian ... but no Russian.

### Steps to reproduce

1. click "translate site"
2. 
3. 

### Actual result

<img width="363" alt="image" src="https://github.com/user-attachments/assets/5ccd03f3-361d-4108-9082-06c98e70f326">

### Expected result

Russian in list

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.69.153 Chromium: 128.0.6613.85 (Official Build) (arm64)
-- | --
Revision | a69e96756922f88cbce3482971d70cfd1ee6f872
OS | macOS Version 14.6.1 (Build 23G93)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by atuchin-m** [comment]
The same bug: https://github.com/brave/brave-browser/issues/40750
