### ISSUE TITLE
`Leo` UI is not reflecting to device's `Dark mode` setting and is always shown in `Light theme`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#40737]
### Description

`Leo` UI is not reflecting to device's `Dark mode` setting and is always shown in `Light theme`. 

To see `Leo` UI in the `Dark theme` the user needs to go to Brave settings > Appearance > Enable "Night Mode". In Brave `1.68.x` and older builds it was enough to enable `Dark Mode` on a device only.

### Steps to reproduce

1. Turn on `Dark Mode` on device
2. Launch Brave
3. Hamburger menu > Leo > *Observe that Leo is not in dark mode*
4. Go to `wikipedia.org` > Settings > Color > Automatic > *Confirm that webpage is in dark mode*
5. NTP > Open `brave://version` > *Confirm that webpage is in dark mode*

### Actual result

`Leo` UI is not reflecting to device's `Dark mode` setting and is always shown in `Light theme`. 

---------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/6742bc3d-d146-49c8-8ad7-957eb8ccba2d) | ![2](https://github.com/user-attachments/assets/d2372fe4-d8cd-4287-ae24-2f2abe0592e9) | ![3](https://github.com/user-attachments/assets/be26e8bd-98bd-4cda-8847-3af417d544f5) | ![4](https://github.com/user-attachments/assets/042ba54a-95b5-45fa-b691-9d0fffd1a0a1) |

### Expected result

`Leo` UI must be seen in `Dark theme` when the device's `Dark mode` is ON. This is true for `wikipedia.org` or `brave://version`, for example. 

--------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/83ed0832-683a-4d5c-a9a9-1972bf562b6c) | ![2](https://github.com/user-attachments/assets/5701a40e-e681-4b9c-a7a4-dbc1241df21e) |
| ![1](https://github.com/user-attachments/assets/b07bc072-54e5-458a-8ef4-d60b4918ed3e) | ![2](https://github.com/user-attachments/assets/ee426a9d-6be3-4487-b7cb-dc0aa38c37fe) |

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.69.157
Chromium: 128.0.6613.85 (Official Build) (64-bit) 

### Device

- Brand/Model: Pixel 6 and Pixel 7
- Android version: 14 and 15

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by samartnik** [comment]
Wasn't able to reproduce with `1.71.61`. @hffvld could you please double check if it's still applicable with the latest nightly build?

https://github.com/user-attachments/assets/b68dc2ab-6563-4cfd-bf0c-674fb32de018

**Comment by hffvld** [comment]
Hi @samartnik 
I am still able to reproduce it on Pixel and Samsung devices with the latest `Nightly` builds `1.71.61`/`1.71.63`

```
Device/OS: 
- Galaxy A32 5G / a32xsq-user 13 TP1A.220624.014 release-keys
- Pixel 6 / oriole-user 14 AP2A.240705.004 release-keys
- Pixel 7 / panther_beta-user 15 AP41.240726.009 release-keys
Brave build: 1.71.63
Chromium: 128.0.6613.120 (Official Build) canary (64-bit) 
```
-----------------------

https://github.com/user-attachments/assets/5e25c62d-9645-47b9-8cff-40fd70a17559

**Comment by samartnik** [comment]
Oh, right, I actually made build off of `cr129`. I can confirm that it is reproducible with `cr128`, but it appears to be fixed in `cr129`. We will need to double check it once `cr129` gets to nightly.

**Comment by hffvld** [comment]
This issue is not reproducible in the latest RC build which included `Cr129`.

cc @samartnik 

---------------------------

Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240726.010 release-keys
Brave build: 1.70.113
Chromium: 129.0.6668.42 (Official Build) (64-bit)
```
---------------------------

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/3e460c64-ff91-4d59-9a16-1f021de3d81a) | ![2](https://github.com/user-attachments/assets/0c2d92b5-ab9b-4ab9-8018-53df5f7aca91) | ![3](https://github.com/user-attachments/assets/887d5abe-f041-4533-ba09-05998f541ead) | ![4](https://github.com/user-attachments/assets/6165e5a3-0c00-4be5-882f-7df6fec7a210) | ![5](https://github.com/user-attachments/assets/35bc26d5-0916-48f0-b8b6-0f8a5f41da23) |

**Comment by jonathansampson** [comment]
@hffvld If I understand correctly, the issue is now resolved?

**Comment by SergeyZhukovsky** [comment]
@hffvld could you please confirm it's gone and close it?

**Comment by hffvld** [comment]
Confirmed that the issue is not reproducible anymore with Brave `1.71.118`. Closing the issue.

---------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/09a4e5c2-2901-4ea9-ab00-5c75df19cb16) | ![2](https://github.com/user-attachments/assets/6f304655-e522-4911-bcc2-32411008f7ab) | ![3](https://github.com/user-attachments/assets/5f1032b4-5f3d-4f31-acaf-33b080ecc420) | ![4](https://github.com/user-attachments/assets/a350037e-dd11-4ffb-8889-59e9a82f98fa) |
