### ISSUE TITLE
Performance issue while watching HD livestreams on Twitch (while in background ?)

### ISSUE THREAD

**Issue by Blaxou** [brave/brave-browser#4074]
## Description 
When watching a stream on HD (1080p 60fps) on Twitch, it often hangs and loads as if my connection wasn't powerful enough where it's not the case as Safari handles the same livestream perfectly fine and doesn't hangs and loads.

## Steps to Reproduce

   1. Open http://twitch.tv
   2. Go on a stream and select the highest quality (the highest the quickest it hangs)
   (3.) Go onto another tab or even put Brave in background, seems to hang more often when in background 

## Actual result:

Twitch loads as if the connection was poor
![Screenshot 2019-04-11 at 22 48 56](https://user-images.githubusercontent.com/25441359/55992174-3b44b680-5cac-11e9-8391-64352eda8aaf.png)

## Expected result:
Do not load ?

## Reproduces how often: 

Easily reproduced on the long run, seems to happen once every 3 minutes or so

## Brave version (brave://version info)

Brave | 0.64.40 Chromium: 74.0.3729.61 (Official Build) dev(64-bit)
-- | --
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
Seems like it yes

**Comment by rebron** [comment]
cc: @kjozwiak, @rebron to reproduce.

**Comment by kjozwiak** [comment]
@Blaxou can you still reproduce this with `0.66.101 CR: 75.0.3770.142` which is the latest release? Has the performance improved? I tried running a few Twitch streams at `1080p60 (Source)` and didn't run into any noticeable performance issues.

**Comment by Blaxou** [comment]
@kjozwiak Hey ! It seems it has been fixed yeah ;) Didn't notice any performance issues.

**Comment by kjozwiak** [comment]
> @kjozwiak Hey ! It seems it has been fixed yeah ;) Didn't notice any performance issues.
> 
> Closing the issue 😄

Awesome, thanks for double checking! Really appreciate it 👍
