### ISSUE TITLE
No "settings" shortcut in brave://settings/system/shortcuts

### ISSUE THREAD

**Issue by mcint** [brave/brave-browser#40740]
### Description

It's normal to be able to open "settings" or "preferences" with `Ctrl+Shift+,` (macOS) or `Ctrl+Shift+P` on many platforms in many applications.  Brave seems to not have a shortcut for it any more, nor have an "access settings" action which can be assigned a shortcut, in `brave://settings/system/shortcuts`

### Steps to reproduce

1.a. Open `brave://settings/system/shortcuts`. Search /settings/ or /pref/. 
1.b. Check hamburger menu, `Settings` -- is a keybind listed alongside.

### hamburger menu
<img src="https://github.com/user-attachments/assets/27992034-25f7-46e8-bc72-7389b2d102db" width=35% title="Brave hamburger menu, bottom. Settings -- no shortcut, Downloads & others -- with shortcuts">

`< img src="https://github.com/user-attachments/assets/27992034-25f7-46e8-bc72-7389b2d102db" width=35% title="Brave hamburger menu, bottom. Settings -- no shortcut, Downloads & others -- with shortcuts">`

### /settings/
<img src="https://github.com/user-attachments/assets/11f7b9cf-ab11-4fa5-81d0-bd86db15f0e2" width=50% title="Brave system shortcuts, search: /settings/" >

`< img src="https://github.com/user-attachments/assets/11f7b9cf-ab11-4fa5-81d0-bd86db15f0e2" width=50% title="Brave system shortcuts, search: /settings/" >`

### /pref/
<img src="https://github.com/user-attachments/assets/c90e4670-1447-4bd1-9604-9a749bc0ae23" height="300" title="Brave system shortcuts, search: /pref/">

`< img src="https://github.com/user-attachments/assets/c90e4670-1447-4bd1-9604-9a749bc0ae23" height="300" title="Brave system shortcuts, search: /pref/">`

### Expected result

A default shortcut, and an ability to set one -- or placeholder explanations at the bottom of `brave://settings/system/shortcuts` for platform- or distribution-specific considerations preventing it.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave		1.69.153 Chromium: 128.0.6613.85 (Official Build) (64-bit) 
Revision	a69e96756922f88cbce3482971d70cfd1ee6f872
OS		Linux
```

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment]
cc: @fallaciousreasoning 

A few notes:
macOS has a keyboard shortcut for Settings `Command ,`. 
Windows and Linux don't have a keyboard shortcut for Settings and Linux apps aren't consistent as far as a shortcut for Settings or Preferences.

**Comment by fallaciousreasoning** [comment]
Hey, so there is actually a command for this - its called `Options`, which maybe isn't the best name for it, but it is there :smile:
