### ISSUE TITLE
Full crash when inspecting sponsored images folder

### ISSUE THREAD

**Issue by robd003** [brave/brave-browser#40742]
### Description

Navigate to brave://branded-wallpaper/sponsored-images/

Browser will fully crash on macOS & Linux.

### Steps to reproduce

1. Copy & paste `brave://branded-wallpaper/sponsored-images/` to the navigation bar
2. Hit enter

### Actual result

Full browser crash

### Expected result

...no browser crash. Maybe show a directory listing.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.153 Chromium: 128.0.6613.85 (Official Build) (arm64) 

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by simonhong** [comment]
Fixed by https://github.com/brave/brave-core/pull/25407
