### ISSUE TITLE
Chinese was removed for Brave Translate on Nightly

### ISSUE THREAD

**Issue by kund3** [brave/brave-browser#40750]
### Platforms

macOS

### Description

translate into chinese is gone wtf？！

**Comment by bsclifton** [comment]
Translate should be showing up - but I confirmed it doesn't on a few sites

Looking into this now...

**Comment by kund3** [comment]
thank you！I mistakenly thought that you no longer support Chinese.
<img width="709" alt="Screenshot 2024-08-29 at 15 53 11" src="https://github.com/user-attachments/assets/3325b98f-a09e-4194-b50f-25b7517146f0">
screenshot of my translate tab，hope this will be fix soon.

**Comment by bsclifton** [comment]
I verified Chinese is still there for Release and Beta channels. Only seems that Nightly is affected

**Comment by atuchin-m** [comment]
We disabled a list updating mechanism in favor of hardcoded list.
In CR128 get https://chromium-review.googlesource.com/c/chromium/src/+/5605569 that refactors that part and result in  reenabling it. It isn't good, but nothing should be broken (because the backend should serve the same list language).

Although, the new backend update got the issue language list.
Luckily, most of the users are still on CR127, so they are unaffected.

I will re-disable the language list updating code here. The backend issues should be resolved now (it's a separate issue)

**Comment by kjozwiak** [comment]
> We disabled a list updating mechanism in favor of hardcoded list. In CR128 get https://chromium-review.googlesource.com/c/chromium/src/+/5605569 that refactors that part and result in reenabling it. It isn't good, but nothing should be broken (because the backend should serve the same list language).
> 
> Although, the new backend update got the issue language list. Luckily, most of the users are still on CR127, so they are unaffected.
> 
> I will re-disable the language list updating code here. The backend issues should be resolved now (it's a separate issue)

Looks like it's working now that the above was fixed/pushed server side. Checked with `1.70.99 Chromium: 128.0.6613.120` & `1.69.162 Chromium: 128.0.6613.120` and ensured that both `Traditional` & `Simplified` are being displayed for `Chinese` as per:

**`1.70.99Chromium: 128.0.6613.120`** | **`1.69.162 Chromium: 128.0.6613.120`**
------------------------------------------|------------------------------------------------
![beta1 70 99Chromium128 0 6613 120](https://github.com/user-attachments/assets/785c3aa4-cebb-4c49-a307-bf67e6bdc2d0) | ![release1 69 162Chromium128 0 6613 120](https://github.com/user-attachments/assets/0aff881e-a1d2-4388-a462-d0ac99259cef)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.96 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | 6dc1837bd07e6dacd8b6b7b5d9f27e7bb09b5eb5
OS | Windows 11 Version 23H2 (Build 22631.4169)
```

1. Installed 1.71.96
2. launched Brave
3. opened brave://settings/languages in a new tab
4. navigated to Brave Translate section


- Confirmed `Chinese (Simplified)` option is shown in the Translate into this language dropdown
- Confirmed `Chinese (Traditional)` option is shown in the Translate into this language dropdown


example | example 
---- | ----
![image](https://github.com/user-attachments/assets/777a2b08-5bd1-440e-adab-83e4b644693e)|![image](https://github.com/user-attachments/assets/b0e80b3b-270c-4ca3-80df-478f38322553)
