### ISSUE TITLE
[Nala]: Inactive tab color should be the same as the active tab color

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#40754]
## Description 

1. Open a window in front of Brave

Expected:
Active tab color does not change
![image](https://github.com/user-attachments/assets/14ef0df0-e4d9-424e-993a-2e84d4352f54)

Actual:
Active tab color gets really faint
![image](https://github.com/user-attachments/assets/ec829782-d2db-4821-a6d1-b9d9a003b0bc)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.71.105 Chromium: 129.0.6668.89 (Official Build) beta (x86_64)
-- | --
Revision | f69ba167992437799f1dbcce81e90ba501a3d63e
OS | macOS Version 14.7 (Build 23H124)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.110 Chromium: 129.0.6668.100 (Official Build) beta (64-bit)
-- | --
Revision | 46cd0b1af7127687895fcaceff93dd80e29e6f2b
OS | Windows 11 Version 23H2 (Build 22631.4317)
```

Confirmed Active tab color shown as expected in both horizontal and vertical tabs. 


Light mode | dark mode 
------ | -----
![Image](https://github.com/user-attachments/assets/8c922c12-416e-4738-9dbf-aaf36012b9b7)|![Image](https://github.com/user-attachments/assets/5dd3e548-cf69-4b77-9fa7-b0df9c426914)
![Image](https://github.com/user-attachments/assets/03156b5a-6431-4c9e-86b8-5c0b2fb37158)|![Image](https://github.com/user-attachments/assets/16ef5c68-7ae0-4770-9b1f-e62535581e86)

**Comment by GeetaSarvadnya** [comment]
Verified with

```
Brave	1.71.112 Chromium: 130.0.6723.44 (Official Build) (64-bit) 
Revision	7d51df656b247f9432ee714a6d160142a1e11c13
OS	Linux
```

Verified for both light and dark themes for both horizontal and vertical tabs:

Light | Dark
--- | ---
![Image](https://github.com/user-attachments/assets/c0de44fa-d70f-4969-a60d-2c401d8e1953) | ![Image](https://github.com/user-attachments/assets/e231a45a-6e79-44da-acbe-41c445d30a32)
