### ISSUE TITLE
remove "Brave Pay"/Brave Account text

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#4076]
## Test plan
1. Visit brave://settings/payments
2. Ensure `To add or manage Brave Pay payment methods, visit your Brave Account` does NOT show (see picture below for example)

## Description 
C74 update included text that doesn't belong. Need to remove the following text:

"To add or manage Brave Pay payment methods, visit your Brave Account"
from: 
brave://settings/payments

![Screen Shot 2019-04-11 at 4 38 23 PM](https://user-images.githubusercontent.com/5951041/56002712-4382fe80-5c78-11e9-932f-712ee118219d.png)

## Expected result:
Text above isn't displayed at all.

## Brave version (brave://version info)
0.63.35 Chromium: 74.0.3729.61

### Reproducible on current release:
- Not in release builds (62.x), currently only 63.x and above.

**Comment by LaurenWags** [comment]
Encountered this issue while testing #4033 on macOS

Brave | 0.63.35 Chromium: 74.0.3729.61 (Official Build) beta(64-bit)
-- | --
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Mac OS X

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.45 Chromium: 74.0.3729.75 (Official Build) beta(64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Mac OS X

* Verified STR from description
<img width="912" alt="Screen Shot 2019-04-18 at 3 57 39 PM" src="https://user-images.githubusercontent.com/28145373/56387685-f6aca400-61f2-11e9-9c35-dcdc0ad376d7.png">
