### ISSUE TITLE
missing images on panels

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#40765]
### Description

On `1.69.159` there are missing images on some panels - Rewards, Wallet, VPN. Reproduces for both light and dark themes.

The images are there when using `1.69.157`.

Reproduced on by @GeetaSarvadnya 

### Steps to reproduce

1. Using 1.69.159 look at Rewards, Wallet, and VPN panels 

### Actual result

No images

Rewards | Wallet | VPN
--- | --- | ---
<img width="1189" alt="Screenshot 2024-08-29 at 10 12 24 AM" src="https://github.com/user-attachments/assets/6e496983-73f3-431c-b638-56b66caab70e"> | <img width="1181" alt="Screenshot 2024-08-29 at 10 18 17 AM" src="https://github.com/user-attachments/assets/73b8190e-952f-4e7b-a185-8808abfc6699"> | <img width="1191" alt="Screenshot 2024-08-29 at 10 18 46 AM" src="https://github.com/user-attachments/assets/5928d901-0e59-48a2-a076-d7be54133305">

### Expected result

These panels should have images:

Rewards | Wallet | VPN
--- | --- | ---
<img width="1195" alt="Screenshot 2024-08-29 at 10 15 55 AM" src="https://github.com/user-attachments/assets/5373f91e-5838-4dde-afe6-7b55389708b0"> | <img width="1192" alt="Screenshot 2024-08-29 at 10 36 42 AM" src="https://github.com/user-attachments/assets/06a3b8ab-0603-4325-b6ca-b3a047879f85"> | <img width="1191" alt="Screenshot 2024-08-29 at 10 36 49 AM" src="https://github.com/user-attachments/assets/e28264f4-3682-4b8f-b20d-2918192a2e80">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.69.157 Chromium: 128.0.6613.85 (Official Build) (x86_64)
-- | --
Revision | 14c4bb724553b882abcd2fccd9b5acf1f177fe6d
OS | macOS Version 13.6.9 (Build 22G830)

### Channel information

- [X] release (stable) - 1.69.159 RC
- [x] beta - reproduced on 1.70.94 by @GeetaSarvadnya on Win
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @kjozwiak  @brave/qa-team

**Comment by GeetaSarvadnya** [comment]
`1.70.94 Chromium: 128.0.6613.114` - Reproduced rewards and wallet image missing issue, VPN image looks good

Example | Example | Example
-----------|-----------|--------
![image (5)](https://github.com/user-attachments/assets/6e533629-fba0-47c8-ad28-769d6b2d7cd7) | ![image (6)](https://github.com/user-attachments/assets/d17ee9e3-d79e-4298-880d-587611ca510d) | ![image (7)](https://github.com/user-attachments/assets/645f1ee9-cce4-4b52-8ff3-c6d95c4c219b)

**Comment by kjozwiak** [comment]
The above requires `1.69.163` or higher for `1.69,x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit)
-- | --
Revision | 6918a99aa67f8b2c8cfdc9a44e6ad4f9be6c5be9
OS | Windows 10 Version 22H2 (Build 19045.4780)
```
Verified Rewards, Wallet, and VPN panels on `1.69.168` and ensured that images are shown on all the panels

Rewards | Wallet | VPN
----------|--------|------
![image](https://github.com/user-attachments/assets/d2f6c182-547f-4d23-a83a-6d6e762d9eec) | ![image](https://github.com/user-attachments/assets/ab3d2ddb-8a93-461d-9d01-a18bfb566c2d) | ![image](https://github.com/user-attachments/assets/01ae9be8-a8ca-48b6-a9ef-bc68d6bb8682)
![image](https://github.com/user-attachments/assets/e8cd0b5a-e9a4-4375-aaf0-e7d1311fb82c) | ![image](https://github.com/user-attachments/assets/b98b3ce2-5954-433d-a2c7-65c3135e2b90) | ![image](https://github.com/user-attachments/assets/14fd6abd-16ef-4ca6-9967-4f5cfaef60a6)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.69.168 Chromium: 128.0.6613.138 (Official Build) (x86_64)
-- | --
Revision | 6918a99aa67f8b2c8cfdc9a44e6ad4f9be6c5be9
OS | macOS Version 13.6.9 (Build 22G830)
```

**Comment by btlechowski** [comment]
Verified with

Brave | 1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit)
-- | --
Revision | 6918a99aa67f8b2c8cfdc9a44e6ad4f9be6c5be9
OS | Linux

### rewards

![image](https://github.com/user-attachments/assets/f92ae386-9cc2-4bfe-b70b-a4f9f4cbf6f0)|![image](https://github.com/user-attachments/assets/67147f86-4088-4797-ad96-477297707d88)
--|--

![image](https://github.com/user-attachments/assets/6de2d3cc-4efe-47b8-8002-763b310c3f76)|![image](https://github.com/user-attachments/assets/328a9647-7ec5-4fd5-8bf0-72662ecd5dd0)
--|--

![image](https://github.com/user-attachments/assets/2cd46f82-26f0-42df-ab96-d2501b108545)|![image](https://github.com/user-attachments/assets/ed6e5d9e-d632-43b0-8c2e-d9b95198d610)
--|--



### wallet

![image](https://github.com/user-attachments/assets/0e1b81e2-2c72-4982-8983-4c3efd06ec94)|![image](https://github.com/user-attachments/assets/9f965fb3-0bec-49e5-baee-eaa48cf1a3cc)
--|--
