### ISSUE TITLE
Revert webpack bump from 5.89.0 to 5.94.0 on 1.69.x (Release) branch.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#40770]
## Description 

The webpack bump is causing https://github.com/brave/brave-browser/issues/40765.
Since we need to release the latest Chromium bump quickly we will revert the wepack bump and will have another release with a proper fix next week.

**QA Test:**
Same verification as for https://github.com/brave/brave-browser/issues/40765

**Comment by mkarolin** [comment]
Fixed via https://github.com/brave/brave-core/pull/25380

**Comment by LaurenWags** [comment]
thanks @mkarolin! @brave/qa-team this requires `1.69.160` or higher to test.

**Comment by btlechowski** [comment]
Verified with

Brave | 1.69.160 Chromium: 128.0.6613.114 (Official Build) (64-bit)
-- | --
Revision | 420c771afe0dd2e36094aaf5285131ff9b0d37ab
OS | Ubuntu 24.04 LTS

Verified test plan from https://github.com/brave/brave-browser/issues/40765

Note VPN feature does not exist on Linux

Rewards | Wallet 
--- | --- 
![image](https://github.com/user-attachments/assets/70bc239e-8c31-43b9-be7b-309f3cb42498)|![image](https://github.com/user-attachments/assets/0680bc8a-9611-4cd3-8263-fbb3bc15650f)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` with 
```
Brave | 1.69.150 Chromium: 128.0.6613.40 (Official Build) (64-bit)
-- | --
Revision | aea36034a3cccd841545ac66ffb79f21e2ba5dd4
OS | Windows 11 Version 23H2 (Build 22631.4112)
```

Verified test plan from https://github.com/brave/brave-browser/issues/40765

#### Confirmed below panels show images

Rewards | Wallet | VPN
----- | ----- | -----
![image](https://github.com/user-attachments/assets/98aa9643-0d65-4145-be7d-881116997085)|![image](https://github.com/user-attachments/assets/7ffc5af2-048c-4495-a0d7-b5d404622ee7)|![image](https://github.com/user-attachments/assets/e0d3af11-7fb6-4d43-b7c9-17f55f7c6f13)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS x64` running `Sonoma 14.5` via the following build(s):

```
Brave | 1.69.160 Chromium: 128.0.6613.114 (Official Build) (x86_64)
--- | ---
Revision | 420c771afe0dd2e36094aaf5285131ff9b0d37ab
OS | macOS Version 14.5 (Build 23F79)
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/40765#issue-2494677417, ensured that the images were being displayed via the various `WebUI` panels as per the following:

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|-----------------
![Screenshot 2024-08-29 at 6 46 27 PM](https://github.com/user-attachments/assets/96d101db-8a28-4c97-8ea9-347283230ecb) | ![Screenshot 2024-08-29 at 6 46 38 PM](https://github.com/user-attachments/assets/07b47f1f-9b69-4ff6-937f-7156cf1ad7a6) | ![Screenshot 2024-08-29 at 6 46 46 PM](https://github.com/user-attachments/assets/25718004-7e6d-4aaa-9aaa-6e7045471406) | ![Screenshot 2024-08-29 at 6 46 59 PM](https://github.com/user-attachments/assets/ea205e40-ed06-454e-93ac-f9eff51a0836) | ![Screenshot 2024-08-29 at 6 47 15 PM](https://github.com/user-attachments/assets/63c3b4e7-b7a1-4354-a5bb-e3777ba6d517)
