### ISSUE TITLE
Add search promotion button in omnibox

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#40776]
### Description

<img width="753" alt="Screenshot 2024-08-30 at 10 28 51 AM" src="https://github.com/user-attachments/assets/85c8e33c-7b83-4be9-b3ec-171fe1472757">

### Steps to reproduce

NOTE: This feature will be controlled via griffin.
To test easily w/o griffin, we could launch browser with `--enable-features=BraveSearchPromotionOmniboxButton` cmd args

1. Launch browser with clean profile and with additional cmd args mentioned above note
2. Set DDG as a default search provider
3. Type any keyword and check promotion button is shown like above screenshot
4. Change to brave search as a default search provider
5. Type any keyword and check promotion button is not shown
6. Set DDG as a default search provider and type anything
7. Click the promotion button and check brave search page with typed query is loaded
8. Check default browser is changed to brave search
9. If x button is clicked after step above step 3, button will not be shown again and provider is also not changed
10. If just click enter after typing at step 3, DDG page is shown and promotion button will be shown again

### Actual result

N/A

### Expected result

See the STR

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

n/a

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @brave/qa-team

**Comment by simonhong** [comment]
@rebron This button promotion also should be controlled by griffin?

**Comment by MadhaviSeelam** [comment]
Verification in progress  using
```
Brave | 1.72.83 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | b49615851cd2dc4b1c3f5f13d3207d3c032bfd8d
OS | Windows 11 Version 23H2 (Build 22631.4317)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.93 Chromium: 131.0.6778.14 (Official Build) beta (arm64)
-- | --
Revision | 69e5dc20ca483a13316632df5bcd9279bb2a3cb7
OS | macOS Version 14.6.1 (Build 23G93)
```

Case 1: New Profile - `Switch to Brave Search` button

1. Installed 1.72.93
2. launched Brave with args --enable-features=BraveSearchPromotionOmniboxButton cmd args
3. opened `brave://settings/search` in a new tab
4. clicked `Change` button
5. selected `DuckDuckGo` and clicked `Set as defaut`
6. verified `DuckDuckGo` for Normal window in the `brave://settings/search`
7. open a new tab and typed `Diwali`
8. confirmed search promotion button `Switch to Brave Search` in the omnibox
9. returned to `brave://settings/search`
10. clicked `Change` and switched to `Brave` SE
11. opened a new tab and type `Diwali`
12. confirmed `Switch to Brave Search` promotion button in the omnibox is not shown
13. returned to brave://settings/search and switched to `DDG` SE
14. opened a new tab and typed `Diwali`
15. clicked `Switch to Brave Search` button in the omnibox
16. confirmed `Brave` search results rendered
17. closed the tab and typed `Diwali` again
18. confirmed the search promotion button `Switch to Brave Search` is not shown
19. confirmed first entry in the omnibox results show `Brave search`
20. returned to brave://settings/search
21. confirmed `Brave` is set as a default for Normal window

step 5 | step 6 | step 8 | step 10 | step 12 | step 13 | step 15 | step 16 | step 19 | step 21
------- | ------- | ------ | ------- | ------- | ------ | ------- | ------- | ------- | -------
![Image](https://github.com/user-attachments/assets/b24bea41-b500-4cee-8432-2b5efc2e77e3)|![Image](https://github.com/user-attachments/assets/7d94f231-7957-4286-9837-6ce081300254)|![Image](https://github.com/user-attachments/assets/9681cf17-4583-4114-849d-45a65a29cf76)|![Image](https://github.com/user-attachments/assets/4bf38ff7-ba41-414f-b1ec-d249011a0300)|![Image](https://github.com/user-attachments/assets/d297cb9d-58fd-4a0b-9711-39a94225b260)|![Image](https://github.com/user-attachments/assets/efcaa352-f18d-4674-bc2b-2e2f9f8954e6)|![Image](https://github.com/user-attachments/assets/f05658ee-01cd-4d3d-bbba-34a3258bd5cc)|![Image](https://github.com/user-attachments/assets/45d2fd94-45d3-4450-97b2-3d8bf729215b)|![Image](https://github.com/user-attachments/assets/09ca6e57-9c7b-46a3-81ba-d2a19c0f9348)|![Image](https://github.com/user-attachments/assets/279100bd-54be-457a-b778-78201b346538)

Case 2: Dismiss the promotion button 

1. Launched new Brave profile (with args --enable-features=BraveSearchPromotionOmniboxButton)
2. switched to Dark theme via `brave://settings/appearance` 
3. opened brave://settings/search 
4. switched to `DuckDuckGo`
5. opened a new tab and typed `Diwali`
6. confirmed search promotion button `Switch to Brave Search` shown in the omnibox
7.  clicked `x` to dismiss the button
8.  closed the tab
9.  opened a new tab and typed `Diwali`
10.  confirmed search promotion button is not shown
 
step 4 | step 6 | step 7 | step 10
------ | ------- | ------- | -----
![Image](https://github.com/user-attachments/assets/b1931c34-6481-424d-834d-b022cc3a7cc4)|![Image](https://github.com/user-attachments/assets/ac01d302-2847-4fcd-b8d0-519fbd65c8b0)|![Image](https://github.com/user-attachments/assets/564bb187-0926-408e-8d53-f8c49405b6d2)|![Image](https://github.com/user-attachments/assets/89a061f0-1423-42b7-b611-5e044914b681)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.72.95 Chromium: 131.0.6778.24 (Official Build) beta (64-bit) 
Revision	006619fbaf6013cb3495b90fc3885eda343087e5
OS	Linux
```

Verification `PASSED` using
```
Brave | 1.72.85 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 2c872aa4d2694bc73ec58e3b14538a4008a6381e
OS | Windows 11 Version 23H2 (Build 22631.4317)

```
<details>
<summary>Case 1: New Profile - `Switch to Brave Search` button - PASSED</summary>

1. Installed 1.72.85
2. launched Brave with args --enable-features=BraveSearchPromotionOmniboxButton 
3. opened `brave://settings/search` in a new tab
4. clicked `Change` button
5. selected `DuckDuckGo` and clicked `Set as defaut`
6. verified `DuckDuckGo` for Normal window in the `brave://settings/search`
7. open a new tab and typed `elections`
8. confirmed search promotion button `Switch to Brave Search` in the omnibox
9. returned to `brave://settings/search`
10. clicked `Change` and switched to `Brave` SE
11. opened a new tab and type `Hall`
12. confirmed `Switch to Brave Search` promotion button in the omnibox is not shown
13. returned to brave://settings/search and switched to `DDG` SE
14. opened a new tab and typed `Hall`
15. clicked `Switch to Brave Search` button in the omnibox
16. confirmed `Brave` search results rendered
17. closed the tab and typed `Hall` again
18. confirmed the search promotion button `Switch to Brave Search` is not shown
19. confirmed first entry in the omnibox results show `Brave search`
20. returned to brave://settings/search
21. confirmed `Brave` is set as a default for Normal window

step 5 | step 6 | step 8 | step 10 | step 12 | step 13 | step 15 | step 16 | step 19 | step 21
------- | ------- | ------ | ------- | ------- | ------ | ------- | ------- | ------- | -------
![Image](https://github.com/user-attachments/assets/2e81f08a-df5b-4418-bea2-8cf9eb2ec382)|![Image](https://github.com/user-attachments/assets/2997505b-096a-42e1-a1f3-74acdbedc255)|![Image](https://github.com/user-attachments/assets/76132241-a7b6-46dc-a40a-16195666a2ee)|![Image](https://github.com/user-attachments/assets/b845742d-b666-46da-97aa-9a1b5f5b673e)|![Image](https://github.com/user-attachments/assets/d69f909d-6285-48df-a4ab-6bf761e67dd7)|![Image](https://github.com/user-attachments/assets/2669be34-bb35-44cf-b29b-c7b67916b943)|![Image](https://github.com/user-attachments/assets/7bc103ba-d2d3-496f-95d7-b83f15bb8c3b)|![Image](https://github.com/user-attachments/assets/f49f958a-fc38-4e43-9a45-6b873e446226)|![Image](https://github.com/user-attachments/assets/defb3279-539b-4f6f-8b8a-8d7986538dab)|![Image](https://github.com/user-attachments/assets/582a2244-1a39-4dd1-8b1c-dc89febada7a)

</details>

<details>
<summary>Case 2: Dismiss the promotion button - PASSED</summary>

1. Launched new Brave profile (with args --enable-features=BraveSearchPromotionOmniboxButton cmd args)
2. switched to Light theme via `brave://settings/appearance` 
3. opened brave://settings/search 
4. switched to `DuckDuckGo`
5. opened a new tab and typed `elections`
6. confirmed search promotion button `Switch to Brave Search` shown in the omnibox
7.  clicked `x` to dismiss the button
8.  closed the tab
9.  opened a new tab and typed `elections`
10.  confirmed search promotion button is not shown
 
step 6 | step 7 | step 10
------ | ------- | -------
![Image](https://github.com/user-attachments/assets/75a8a0d8-de3f-4677-9046-a2118d19f083)|![Image](https://github.com/user-attachments/assets/717e2836-ca9c-4fc7-8867-15945cfa89f0)|![Image](https://github.com/user-attachments/assets/dd018422-a034-4fba-8878-1580759bb386)|![Image](https://github.com/user-attachments/assets/ae3a8fc1-eed0-4e4d-a490-30e0ff4af16e)


</summary>

**Comment by LaurenWags** [comment]
Changed to `release-notes/exclude` per discussion with @rebron
