### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by srmahitesh** [brave/brave-browser#40778]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.69.153 Chromium: 128.0.6613.85
Operating System: Windows NT 10.0.22631

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/e28e0400-ee7a-7a0c-0000-000000000000

**Comment by iefremov** [comment]
@srmahitesh can you share any steps to reproduce? It seems like an out of memory that is not actionable without details of what happened
