### ISSUE TITLE
Greaselion scripts loaded on twitch.tv when Rewards is not enabled

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#40784]
### Description

Greaselion scripts are being loaded on `twitch.tv` and `vimeo.com` when Rewards is not enabled. It appears that `Greaselion.json` is missing some `rewards_enabled` preconditions.

### Steps to reproduce

1. Open the browser with a new profile
2. Navigate to `twitch.tv` or `vimeo.com`
3. Open devtools (console tab)

### Actual result

<img width="593" alt="Screenshot 2024-08-30 at 11 00 09 AM" src="https://github.com/user-attachments/assets/0d1b76eb-5c04-4caf-8ed7-e4eeb3ca476f">

### Expected result

No "script loaded" messages should appear in the console.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.160 Chromium: 128.0.6613.114 (Official Build) (x86_64) 

(Note that this is due to Greaselion configs, rather than Brave Core.)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.69.162 Chromium: 128.0.6613.120 (Official Build) (x86_64)
-- | --
Revision | e534755d4eb5ad363bb357735e614be1c6421e02
OS | macOS Version 13.6.9 (Build 22G830)
```

**Comment by zenparsing** [comment]
It turns out that GL scripts are loaded for all sites for both Rewards-enabled and Rewards-not-enabled users. This is primarily for historical reasons (the scripts used to insert tip icons).

This issue will be addressed by https://github.com/brave/brave-browser/issues/40872 and https://github.com/brave/brave-browser/issues/34237.

**Comment by LaurenWags** [comment]
Removed from "Greaselion Next" milestone and updated labels

cc @Miyayes
