### ISSUE TITLE
Shift + ctrl +n doesnt open new private window anymore

### ISSUE THREAD

**Issue by EaglePPP** [brave/brave-browser#40781]
### Description

Shift + ctrl +n doesnt open new private window anymore
but shortcut opening new tab or new window or Tor works fine

### Steps to reproduce

1. Shift + ctrl +n

### Actual result

nothing happends

### Expected result

new private window open

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.153 Chromium: 128.0.6613.85
a69e96756922f88cbce3482971d70cfd1ee6f872
Windows 11 Version 23H2 (Build 22631.4112)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [X] in the latest version of Chrome

**Comment by bsclifton** [comment]
@EaglePPP works great for me on a fresh install of Brave- do you have any macro programs setup listening for global shortcuts?

Also - check brave://settings/system/shortcuts and search for `New Private Window`. Mine is showing the correct shortcut - did it get changed somehow?
![image](https://github.com/user-attachments/assets/710e7905-42c2-429c-a94d-69ef250abe87)
