### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ColoradoMark** [brave/brave-browser#40797]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.69.160 Chromium: 128.0.6613.114
Operating System: Linux 6.6.32-02877-gde0d50d4a56c

URL (if applicable) where crash occurred:
http://192.168.1.23:5000/
Can you reproduce this crash?
yes
What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Connect to the URL
2. Wait about 8 hours
3. it crashes

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/6d2e0d00-5a73-850c-0000-000000000000

**Comment by iefremov** [comment]
@ColoradoMark can you please share what exactly is hosted on the problematic URL?

**Comment by ColoradoMark** [comment]
After more testing I believe it is a issue with the server on the website. It is running Frigate and I have recently discovered that it also crashes with Chrome so you can close this ticket.
