### ISSUE TITLE
Support for Custom Site Distillers

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#40794]
### Platforms

all

### Description

Leo currently cannot see much content on GitHub (outside of patch files and pull requests). If you attempt to use Leo today to examine a file, or ask questions about its content, you'll find that Leo is almost entirely incapable of discussing these matters.

When prompting Leo, the current page is _distilled_ down to raw text that can be sent in a request along with your question(s). Leo's current approach at distilling content is to look for `main` and/or `article`, elements, and then look for `heading` and `paragraph` elements. With the results, the text is extracted from each and combined to form the distilled page content.

For some sites, this approach is sufficient, but not for GitHub in many cases. For example, source code on GitHub is usually provided via a `<textarea>` element. As such, the code is never included in the distilled page content. Rather than enable form fields in general, across all domains, what if Leo could delegate to specialized distillers for certain hosts?

It would be great if Leo supported a set of JavaScript module distillers in a component, which could be updated independently of the browser. Distillers could implement a simple interface:

```ts
interface PageDistiller {
    distill: (document: Document, maxTokens: number) => string
}
```

Then, we could have a map of hostnames to distillers. If a distiller exists for the current host, and returns a string, we use the string as the final result. Otherwise, if no such distiller exists, or a distiller returns a non-string, then we fall back to the current implementation.

This approach would enable us (and a larger cohort of community members) to support a large list of differentiated and specialized distillers with solid fallback behavior.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.2` using version `1.75 (95)`

Verified the following using test plan mentioned in https://github.com/brave/brave-core/pull/25722#issue-2553708861

* Ensured that Leo is now able to extract data from Github pages it was previously unable to. 
* Ensured that Leo can provide a list of branches with an open pull-request on `https://github.com/brave/brave-core/branches/all`

example | example
---|---
<img width="250" src="https://github.com/user-attachments/assets/856e9045-6775-4d36-974e-1982f2660002"> | <img width="250" src="https://github.com/user-attachments/assets/d5ca3173-185d-427c-a809-e27c273732b4">

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.156 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | 036ac4040dc50d4bd49b3438e20ab90686218543
OS | Windows 11 Version 23H2 (Build 22631.4602)

- Verified steps from [brave/brave-core#25722](https://github.com/brave/brave-core/pull/25722)
- Verified with `brave://flags/#brave-ai-host-specific-distillation` flag enabled able to distill and extract content from page

<img width="940" alt="Image" src="https://github.com/user-attachments/assets/a19159a6-c212-4ec9-a68b-f25c05e6b262" />
