### ISSUE TITLE
chrome://background-wallpaper/ crashes the browser

### ISSUE THREAD

**Issue by perguto** [brave/brave-browser#40807]
### Description

 Entering the URL chrome://background-wallpaper/ into the address bar crashes the browser (works both on Windows and Android).

### Steps to reproduce

1. Enter chrome://background-wallpaper/ into the address bar.
2. Press Enter

### Actual result

The browser closes and asks to restore the pages on next startup.

### Expected result

I wanted to find the background images of the new tab page. At worst the URL should give you a "not found" error.

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

[Version 1.69.160 Chromium: 128.0.6613.114 (Official Build) (64-bit)](https://brave.com/latest/)

### Android device

- Brand/model: Samsung Galaxy A54
- Android version: Android 14

### Channel information

- [X] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by simonhong** [comment]
checking

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.90 Chromium: 129.0.6668.59 (Official Build) beta (64-bit)
-- | --
Revision | 1f5f0d1b8a45a4c60a78c15df081751e39184b97
OS | Windows 11 Version 23H2 (Build 22631.4169)
```

Reproduced the issue in 1.70.117.  

![image](https://github.com/user-attachments/assets/ff26b94a-ab78-484e-ad64-4bc8287477cd)


1. Installed 1.71.90
2. launched Brave
3. loaded chrome://branded-wallpaper/ or brave://branded-wallpaper/
4. confirmed no Brave crash occurred
5. confirmed This site can't be reached page loaded


![image](https://github.com/user-attachments/assets/0d6f3b09-86d1-4616-b819-88323cec27f8)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 15` using the following build(s):

```
Brave | 1.71.110 Chromium: 129.0.6668.100 (Official Build) beta (64-bit)
--- | ---
Revision | 46cd0b1af7127687895fcaceff93dd80e29e6f2b
OS | Android 15; Build/AP41.240823.009; 35; REL
```

* ensured that `brave://branded-wallpaper` redirects to `chrome://branded-wallpaper`
* ensured that Brave isn't crashing when `chrome://branded-wallpaper` is being loaded

![Image](https://github.com/user-attachments/assets/89b3af4a-67ed-4390-ac92-4a3b3f899ff0)
