### ISSUE TITLE
Icons (Network & Sign) are not shown in panel 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#40814]
### Description

Icons (Network & Sign) are not shown in panel 

### Steps to reproduce

1. Install 1.70.94
2. Restore wallet with balance
3. Open panel to change network, icons are not loaded
4. Scroll down token list, some token network icons are not loaded 

### Actual result

![image](https://github.com/user-attachments/assets/eec44315-1794-48cf-a1e9-9d982a6c90ab)

Sign key icon is also not shown 
![image](https://github.com/user-attachments/assets/05aefb30-dc42-4ee6-9e35-592e61ff2cd6)

### Expected result

Show network icons

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

 
Brave | 1.70.94 Chromium: 128.0.6613.114 (Official Build) beta (64-bit)
-- | --
Revision | 7ee7ec28264896bd8a9aff39cdb9432da38be028
OS | Windows 11 Version 23H2 (Build 22631.4037)
 

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @doug

**Comment by Douglashdaniel** [comment]
@srirambv this is related to https://github.com/brave/brave-browser/issues/40765
