### ISSUE TITLE
Crash when closing 'Share Rewards Internals' dialog

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#40819]
### Description

Closing the dialog will cause crash everytime. Regression in 1.69

### Steps to reproduce

1. New install
2. Enable Brave Rewards
3. Open hamburger menu -> Settings -> Brave Rewards
4. Tap on `Rewards Internals` at the bottom
5. Tap on the share icon (top right)
6. Close the dialog by pressing back button

### Actual result

https://github.com/user-attachments/assets/71d216fe-c99f-42a9-b585-54b587ec4651

### Expected result

No crash

### Reproduces how often

Easily reproduced

### Brave version

1.69 - Reproducible
1.68.1 - Not reproducible

### Device/iOS version

iPhone / IOS 17

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.69.167` or higher for `1.69.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6.1
Brave build: 1.69 (167)
BraveCore: 1.69.167 (128.0.6613.127)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/40819#issue-2503156374
2. *Verify*

**ACTUAL RESULTS:**
- Verified that Brave is not crashing when sharing `Rewards Internals`.

---------------------------

https://github.com/user-attachments/assets/d5ed12ba-2928-4cbd-86d8-fba1138d16cf
