### ISSUE TITLE
[Suggestion] More features for "new tab" screen 

### ISSUE THREAD

**Issue by silent5am** [brave/brave-browser#4082]
Hi, I hope this is the right place to make a few suggestions - if not, pls let me know where. 

This is for the desktop version.

1) When I open a new tab, below the stats there will be "quick link" or "short-cut" or "auto-bookmark" or whatever they are called, allowing me to quickly access a website. These are generated automatically and I would like to have more control over this feature.

a) allow to disable the feature entirely (right now, one has to manually remove each icon)
b) allow to manually customize the size, placement and edit url of each icon (Firefox had this feature as well)

2) I think the backgrounds are nice, but it would be cool to disable them and chose a simple background color instead or allow users to use their own images.

And general suggestion: 

3) Tab size get really small when many tabs are open, only showing small icon - it would be nice to be able to customize size or change max number of tabs displayed until side-scroll kicks in. I know this is my problem due to browsing habit but when working it really get's disorganized and waste time looking for the tabs i need.

That's it. Otherwise I'm happy with Brave :)

**Comment by dagli** [comment]
I would like to see 1st and 2nd. But 3rd is as you said "a browsing habit". You can use total of 30 tabs in 2 or 3 windows instead of a single window.

**Comment by bsclifton** [comment]
We should have 1 and 2 resolved completely now; for 3 we have https://github.com/brave/brave-browser/issues/35 captured 😄
