### ISSUE TITLE
Fix X/Twitter creator detection with holdover fix (2024-09) 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#40822]
## Description

X/Twitter creation is currently broken, including in up to 1.69.x. We have a temporary solution to fix, inspired by @jonathansampson's work, that will hold us over until the full post-Greaselion solution is ready. 

## QA

Greaselion, out-of-band QA.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.69.153 Chromium: 128.0.6613.85 (Official Build) (64-bit)
-- | --
Revision | a69e96756922f88cbce3482971d70cfd1ee6f872
OS | Windows 10 Version 22H2 (Build 19045.4780)
```
Reproduced the issue on `1.70.100 Chromium: 128.0.6613.120` with production component
   - The creator name is NOT shown on the BR panel for both verified and non verified creators

Example | Example | Example
---------|---------|-------
![image](https://github.com/user-attachments/assets/8afbab92-235e-460e-9e2b-a572c60aaecf) | ![image](https://github.com/user-attachments/assets/0cecf6f1-0747-4276-9bc8-f68cb2e91297) | ![image](https://github.com/user-attachments/assets/a8a4c73c-3611-40f2-98c4-93be6ec8fd08)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.69.162 Chromium: 128.0.6613.120 (Official Build) (x86_64)
-- | --
Revision | e534755d4eb5ad363bb357735e614be1c6421e02
OS | macOS Version 13.6.9 (Build 22G830)
```
