### ISSUE TITLE
Segmented Controller is Overlapping Menus in the Wallet

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#40828]
### Description

The `Segmented Controller` is overlapping menus on the `Portfolio` and `Account Details` page

### Steps to reproduce

1. Open the `Wallet` and navigate to the `Portfolio` page
2. Shrink your window size down and then open the top right `Wallet Menu`
3. The `Segmented Controller` is overlapping the menu
4. Navigate to the `Accounts` page and view an account
5. Open both available `Wallet Menu's`
6. The `Segmented Controller` is overlapping the menus

### Actual result

![Screenshot 51](https://github.com/user-attachments/assets/56c09290-6737-4017-b58d-d85117eb1ab9)

![Screenshot 52](https://github.com/user-attachments/assets/f32fcb60-b3ea-45e3-a856-19fc0ea9e51d)

![Screenshot 53](https://github.com/user-attachments/assets/5cf16e22-2a62-49e5-92f3-4b15263525e6)

### Expected result

It should not overlap the `Menu's`

![Screenshot 54](https://github.com/user-attachments/assets/a6750844-9655-4c1b-955b-9aa51f2288bb)

![Screenshot 55](https://github.com/user-attachments/assets/d0379b02-ab95-4d64-b5c6-723be292090e)

![Screenshot 56](https://github.com/user-attachments/assets/ed8c0a34-9d75-453a-a4fa-731749e2a87a)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.92 Chromium: 128.0.6613.85 (Official Build) beta (arm64) 

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by LaurenWags** [comment]
Requires `1.70.102` or higher for verification 👍🏻

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.105 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | dd1f0aff786e2f4b694066ba8500616833591bf1
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from [brave/brave-core#25414](https://github.com/brave/brave-core/pull/25414)
- Verified segmented controller is not overlapping on menu items

https://github.com/user-attachments/assets/b7f7972e-cea3-4f18-98e5-c5eafa88877f
