### ISSUE TITLE
Address is Hidden in Deposit Funds Panel View

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#40826]
### Description

It is currently not obvious that you need to scroll down to see your address in the `Deposit Funds` view in the Wallet `Panel`.

### Steps to reproduce

1. Open the Wallet `Panel` and navigate to the `Deposit Funds` screen.
2. Select a `Token` to deposit and click continue.
3. You have to scroll down to be able to know that the `Address` is bellow the `QR` code.

### Actual result

![Screenshot 49](https://github.com/user-attachments/assets/88cc9968-b405-45e0-b545-d1a06559c013)

### Expected result

We should move the `Address` above the `QR` code to make it more obvious.
![Screenshot 50](https://github.com/user-attachments/assets/893db84a-aec3-490a-9996-3980b27c1d9a)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.153 Chromium: 128.0.6613.85 (Official Build) (arm64) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.71.97 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | de99cbcb1aa0aa00877d356e4733f4e5481e89eb
OS | Windows 11 Version 23H2 (Build 22631.4169)

- Verified steps from [brave/brave-core#25413](https://github.com/brave/brave-core/pull/25413)
- Verified deposit address is shown above the QR code in panel 
- Verified for all deposit account types
- Encountered [#41315](https://github.com/brave/brave-browser/issues/41315)

Solana | Ethereum | Filecoin | BTC | ZCash
-- | -- | -- | -- | --
![image](https://github.com/user-attachments/assets/c36ebdbd-6973-4580-b473-bdf6411c8e3e) | ![image](https://github.com/user-attachments/assets/50b9d57e-8580-47a5-a9fb-8528c4d25cab) | ![image](https://github.com/user-attachments/assets/97677461-4f2b-4ced-a1b3-f01ba631ad58) | ![image](https://github.com/user-attachments/assets/e7d2211a-fdf4-4093-b117-9f8c70051117) | ![image](https://github.com/user-attachments/assets/1f348fcf-81ef-4c03-94e3-e307044db76c)

**Comment by drshaf01** [comment]
> ### Description
> 
> It is currently not obvious that you need to scroll down to see your address in the `Deposit Funds` view in the Wallet `Panel`.
> 
> ### Steps to reproduce
> 
> 1. Open the Wallet `Panel` and navigate to the `Deposit Funds` screen.
> 2. Select a `Token` to deposit and click continue.
> 3. You have to scroll down to be able to know that the `Address` is bellow the `QR` code.
> 
> ### Actual result
> 
> ![Screenshot 49](https://github.com/user-attachments/assets/88cc9968-b405-45e0-b545-d1a06559c013)
> 
> ### Expected result
> 
> We should move the `Address` above the `QR` code to make it more obvious. ![Screenshot 50](https://github.com/user-attachments/assets/893db84a-aec3-490a-9996-3980b27c1d9a)
> 
> ### Reproduces how often
> 
> Easily reproduced
> 
> ### Brave version (brave://version info)
> 
> 1.69.153 Chromium: 128.0.6613.85 (Official Build) (arm64)
> 
> ### Channel information
> 
> * [x]  release (stable)[x]  beta[x]  nightly
> 
> ### Reproducibility
> 
> * [ ]  with Brave Shields disabled[ ]  with Brave Rewards disabled[ ]  in the latest version of Chrome
> 
> ### Miscellaneous information
> 
> _No response_

I'm
