### ISSUE TITLE
A native menu and a native inject for adblock content picker

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#40821]
### Description

The epic: https://github.com/brave/brave-browser/issues/39610
The previous task: https://github.com/brave/brave-browser/issues/40696

Currently content picker typescript doesn't need Brave extension to work, but it's still injected via the background page.
We need:
1. a native inject mechanism
2. a native menu instead of an extension-based
3. another impl of API to add a user-defined rule.

No changes in the feature logic are expected.

**Comment by atuchin-m** [comment]
@rebron
To fix https://github.com/brave/brave-browser/issues/39610 we need to reimplement the adblock-related items in the menu, that is done in the PR https://github.com/brave/brave-core/pull/25411.

Here is some product-related questions to answer. Could you please take a look?
* Do we want to rename the menu items or the current state is ok?
* Do we still need to have Leo icon? We don't use it for other items.
* Where the menu `Brave` should be located? Before the PR we use the extension section, but it's not an extension-related anymore. The the PR I add the item after `Print`. 
* Should we disable or hide the menu when `Allows all trackers and ads` is set in Shields? Currently we always show it, but added filters will not work if Shields are down.
* Should we hide the items in some menu mode (the text selected, the image, the link)? Before the PR we don't care, always show.

| before  | after |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/977634e7-5d3e-4542-9743-9c8d9bbda629)  | ![image](https://github.com/user-attachments/assets/526593ab-f0dc-4820-8105-2ecc72ef00f8) |

**Comment by rebron** [comment]
> @rebron To fix #39610 we need to reimplement the adblock-related items in the menu, that is done in the PR [brave/brave-core#25411](https://github.com/brave/brave-core/pull/25411).
> 
> Here is some product-related questions to answer. Could you please take a look?
> 
> * Do we want to rename the menu items or the current state is ok? 
I'm wondering if we just bring in `Block element` up to the menu and we can remove Manage custom filters here.
wdyt @ShivanKaul @antonok-edm  There's probably still a better name for this. `Content blocking` if we're keeping the sub-menu.

> * Do we still need to have Leo icon? We don't use it for other items.
It's fine to remove the Brave logo, especially if we do the above.

> * Where the menu `Brave` should be located? Before the PR we use the extension section, but it's not an extension-related anymore. The the PR I add the item after `Print`.
Put it back to under Translate to English. Your current location may have `Cast...` as a menu item. And Create QR Code for this page has Send to your Devices if Sync is enabled. 

> * Should we disable or hide the menu when `Allows all trackers and ads` is set in Shields? Currently we always show it, but added filters will not work if Shields are down.
Always show. It's fine even with allow all tracker and ads to have this option.

> * Should we hide the items in some menu mode (the text selected, the image, the link)? Before the PR we don't care, always show.

That makes sense to me. Don't show when selecting text and on a link. I think with an image, users may want to block that image.

> 
> before	after
> ![image](https://github.com/user-attachments/assets/977634e7-5d3e-4542-9743-9c8d9bbda629)	![image](https://github.com/user-attachments/assets/526593ab-f0dc-4820-8105-2ecc72ef00f8)

**Comment by rebron** [comment]
>> * Should we disable or hide the menu when `Allows all trackers and ads` is set in Shields? Currently we always show it, but added filters will not work if Shields are down.

>Always show. It's fine even with allow all tracker and ads to have this option.

Actually @ShivanKaul @antonok-edm. I guess with Shields down, blocking elements doesn't work then probably doesn't make sense to have this menu item available as an option.

**Comment by atuchin-m** [comment]
> Actually @ShivanKaul @antonok-edm. I guess with Shields down, blocking elements doesn't work then probably doesn't make sense to have this menu item available as an option.

It's an issue now: if Shields are done, you can still select an item to block and it will be immediately blocked (not by adblock, but by injecting a CSS by the script).
But after you reload the page the element will be still visible.

**Comment by atuchin-m** [comment]
| option 1  | option 2 |
| ------------- | ------------- |
| <img width="237" alt="image" src="https://github.com/user-attachments/assets/5690e312-0689-44e5-8306-16f9497da827"> | <img width="411" alt="image" src="https://github.com/user-attachments/assets/13b6597a-6b2f-4381-a64d-ae50c2d05ce3"> |

**Comment by atuchin-m** [comment]
BTW, @rebron WDYT about replacing `Block element` to `Block elements`? The first sounds like:
1. you have to target to particular element, but it works in another way;
2. you can select only one element. In fact, a new rule often covers multiple items.

**Comment by rebron** [comment]
Sounds good. Can change it to `Block elements` for now.

**Comment by ShivanKaul** [comment]
Okay, here's a suggestion:
1. Move the `Block elements` to be top-level. Get rid of the `Manage custom filters`.
2. Add a `Manage custom filters` button alongside `Create` and `Quit` after the user selects an element.
![image](https://github.com/user-attachments/assets/90fea38b-8b20-41a6-9113-6e813459b692)

**Comment by atuchin-m** [comment]
@rebron @ShivanKaul PTAL:
<img width="301" alt="image" src="https://github.com/user-attachments/assets/af006cf9-5b5e-4eb8-8d6c-9d3a0c01d448"><img width="343" alt="image" src="https://github.com/user-attachments/assets/8e785d32-30e4-4126-9aa7-eadcef299920">

1. I've moved the menu in before the extension section (aka under `Translate to ..`);
2. The new button `Manage filters` is added. BTW, these button are not translatable now (the same for `Create` and `Quit`)
3. The menu item is visible iff:
- the page url is http or https; i.e. it's hidden on brave://settings or on NTP.
- no text is selected;
- the selected element isn't link (no href);
- if it's image we show the item despite the previous rule;
- Shields isn't in `Allows all trackers and ads` state;

**Comment by ShivanKaul** [comment]
Thanks @atuchin-m. 

1. Looking at the screenshots, I do think it would be better for `Block elements` to live in the `View Page Source` and `Inspect` section. If it's not too much trouble, let's make this change.
2. Just want to clarify the "text selection" behaviour: if I select text, and then right-click on the text, the text stays selected. I agree that it doesn't make sense to have the menu item be visible then. However, if I select text, and right-click somewhere else on the page, the text selection goes away. In this latter case, we do want the menu item to be visible. I'm pretty sure this is what you're saying, but wanted to double-check.
3. We do want links/hrefs to be blockable.

Everything else SGTM.

**Comment by atuchin-m** [comment]
@ShivanKaul thanks for the comment.
1. it looks harder to implement because there is no fixed anchor. Inspect [could be invisible](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/renderer_context_menu/render_view_context_menu.cc;l=1653?q=render_view_context_menu.cc).
2. yep, we do show the menu item if the selection goes away in the click moment. The condition is about the opposite to `Leo AI tool`, you could try it yourself.  
3. The current PR hides the item for **text** links (if it's not an image). We could change it to show it for all the links. Just to clarify that the content picker doesn't preselect the hovered element. It's a page level action like `inspect`: after clicking it a user have to select the element again.

**Comment by ShivanKaul** [comment]
Gotcha, that all seems fine then. I guess I can't think of a case where a user might want to block an item on the page that was a hyperlink but not an image, so we can leave it out for now.

**Comment by atuchin-m** [comment]
@ShivanKaul @rebron 
Ok, let's move the item, it isn't a rocket science. Also it is always shown for links.
| blank space click  | link click |
| ------------- | ------------- |
| <img width="279" alt="image" src="https://github.com/user-attachments/assets/1d3f9c21-f5ff-4c11-81f2-aa8e9ce8d3f8"> | <img width="332" alt="image" src="https://github.com/user-attachments/assets/bd024973-515d-4e2d-a9fa-b326f90ff9e4"> |

**Comment by petemill** [comment]
IMO it should still have the Brave shields icon in the menu, but if that's been decided otherwise then fine.

**Comment by ShivanKaul** [comment]
Your rationale is that it's a Brave Shields feature? I considered that, just seems slightly inconsistent to have a Brave logo (which happens to be the same as the Shields logo) for this but not Leo context menu or Copy Clean Link.

**Comment by atuchin-m** [comment]
For QA: it makes sense to verify all the related changes together: 
https://github.com/brave/brave-core/pull/25330
https://github.com/brave/brave-core/pull/25358
https://github.com/brave/brave-core/pull/25411

Scenario 1:
1. Launch the browser, open any site (i.g reddit.com)
2. Right click on blank space and click `Block elements` 
5. Click on the item, content picker mode should be activated.
6. Select a item and click `Create`.
7. Verify that the item is blocked immediately
8. Reload the page, verify the item is blocked
9. For any controversial behavior check v1.69.x (`Brave => Block element`) as the reference

Scenario 2 (Manage filters):
1. Select `Block elements`
2. Select any element, click `Create`
3. Click `Block elements` again, click `Manage filters` button.
2. Verify the shields settings are opened and there is a new rule **related to the domain you test** (i.e. reddit.com)

Case 3 (Menu position and show/hide logic).
Verify that:
1. `Block elements` item is always above `Inspect`
2. the item is shown for any link we right-clicked and isn't shown for selected text.
3. the item is hidden when Shields are down
4. the item is hidden on NTP or brave://settings

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` pending response from https://github.com/brave/brave-browser/issues/40696#issuecomment-2362112901

**Comment by kjozwiak** [comment]
The above requires `1.71.95` or higher for `1.71.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.71.104 Chromium: 129.0.6668.89 (Official Build) beta (64-bit)
-- | --
Revision | 3da42496f366e4dc607c58cfdd95ce3f5064c171
OS | Windows 11 Version 23H2 (Build 22631.4249)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.71.105 Chromium: 129.0.6668.89 (Official Build) beta (x86_64)
-- | --
Revision | f69ba167992437799f1dbcce81e90ba501a3d63e
OS | macOS Version 14.7 (Build 23H124)
```

Verified test plan from https://github.com/brave/brave-browser/issues/40821#issuecomment-2352446992.

<details>
<summary>Case 1 - InProgress</summary>

</details>

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.71.112 Chromium: 130.0.6723.44 (Official Build) (64-bit)
-- | --
Revision | 7d51df656b247f9432ee714a6d160142a1e11c13
OS | Linux
```
