### ISSUE TITLE
[iOS] - Update JitsiMeetSDK

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#40829]
### Description

- Update the JitsiMeetSDK as requested

### Steps to reproduce

1. N/A

### Actual result

N/A

### Expected result

N/A

### Reproduces how often

Easily reproduced

### Brave version

N/A

### Device/iOS version

N/A

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by Uni-verse** [comment]
Verified on the following devices using version `1.70 (126)`

iPhone 12, iOS 18
iPhone XR, iOS 17
iPad, iPadOS 17

- Ensured `talk.brave.com` is working and checked the following areas to make sure there are no regressions: 
   - [x] Starting/Ending group call
   - [x] Car Mode
   - [x] Low Bandwidth call
   - [x] Toolbar/settings menu
   - [x] Microphone/Video feed
   - [x] Sharing talk

**iOS 18** 

example | example | example | example | example | example
---|---|---|---|---|---
![Image](https://github.com/user-attachments/assets/6315b597-d59e-4a15-baba-f98efd090d2c) | ![Image](https://github.com/user-attachments/assets/462a3b22-51cf-42d4-a099-eced25bc1b35) | ![Image](https://github.com/user-attachments/assets/4dc8c6fb-bfcf-43f5-8130-20fb734a0767) | ![Image](https://github.com/user-attachments/assets/c8436614-8008-4d2e-8f27-e24b23c97b2e) | ![Image](https://github.com/user-attachments/assets/f2d06c85-e951-483f-8803-801aa28bf00f) | ![Image](https://github.com/user-attachments/assets/590a3449-bacf-4e50-aa19-3f3ef98b6fea)

**iOS 17**

example | example | example | example | example | example | example | example | example
---|---|---|---|---|---|---|---|---
![Image](https://github.com/user-attachments/assets/dc28657b-1293-4058-ab9c-4be50a5fcf0a) | ![Image](https://github.com/user-attachments/assets/dd19b345-132a-43e8-9e34-4576abf15440) | ![Image](https://github.com/user-attachments/assets/57f50e73-6248-4e90-9ba3-f492120b58b4) | ![Image](https://github.com/user-attachments/assets/3554b695-ce94-4770-b77d-d59f84e69c57) | ![Image](https://github.com/user-attachments/assets/97bd372b-4a87-48f8-aeaa-3df957dca878) | ![Image](https://github.com/user-attachments/assets/c2bbb9fe-0d5f-4dd9-91c0-6d8028a0e85f) | ![Image](https://github.com/user-attachments/assets/4dde87ba-6931-4509-904f-207790de206d) | ![Image](https://github.com/user-attachments/assets/d518d5fd-60ec-42a4-94fa-30504adfa159) | ![Image](https://github.com/user-attachments/assets/996367f0-6d74-4427-8c5c-a676a7fc9ecf)


**iPadOS 17**

example | example | example | example | example
---|---|---|---|---
![Image](https://github.com/user-attachments/assets/e10bb014-f21e-474d-a5db-c225a93b6078) | ![Image](https://github.com/user-attachments/assets/78b4ca35-18f5-4580-af67-a1790bca88c4) | ![Image](https://github.com/user-attachments/assets/01bdc29a-f3d6-4777-b57c-aa452774e036) | ![Image](https://github.com/user-attachments/assets/8699e397-70a2-43b8-90e9-e7a9ca20a3b6) | ![Image](https://github.com/user-attachments/assets/3ae17333-4881-4b02-91fc-2cf6c5264d2d)
