### ISSUE TITLE
Autotrader.com can't use Google sign in

### ISSUE THREAD

**Issue by eturk1** [brave/brave-browser#40839]
### Description

Cannot use Google to sign in on autotrader.com on Android or Windows

### Steps to reproduce

1. go to https://autotrader.com
2. tap Sign In, upper right
3. tap Google to sign in 
fails to show Google sign in page and just returns error: "it appears that an account has already..."

### Actual result

![image](https://github.com/user-attachments/assets/cd692cd0-b262-4e9e-af1e-4831489e2ba5)

### Expected result

should display Google authentication, show a Google account, etc

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

1.69.162 Chromium: 128.0.6613.120 (Official Build) (64-bit) 

### Android device

- Brand/model: Google Pixel 9 Pro XL
- Android version: 14

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by bsclifton** [comment]
Hi @eturk1 - I think this is problem with the code on Autotrader.

I verified I can login with Google on Desktop (Release / Nightly) and I also verified I can sign in with my Pixel 8 phone.

Looking at the screenshot you provided, it seems you've already created an autotrader.com account with the same email as your Google account. Maybe you can try another Google account or go through the password reset feature on autotrader.com to recover your password and then use email login

Thanks
