### ISSUE TITLE
[Follow up to 36409] 'Server' and 'Support' subtitles switched on VPN settings page  

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#40843]
### Description

The subtitles for the VPN server section and support section have switched. Not really a regression because we made UX enhancements to the VPN feature in 1.69. 

Related to https://github.com/brave/brave-browser/issues/36409

### Steps to reproduce

1. Enable VPN
2. Open VPN settings page
3. Scroll down to server/support sections

### Actual result

![IMG_7226](https://github.com/user-attachments/assets/4f268eb9-13d7-420b-8dba-627d66386327)

### Expected result

`Server` and `Support` subtitles should be correct

### Reproduces how often

Easily reproduced

### Brave version

1.69.x

### Device/iOS version

iPhone / iOS 17

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.69.165` or higher for `1.69.x` verification 👍
