### ISSUE TITLE
[Follow up to 36409] VPN advanced server selection list not shown after Brave relaunch

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#40855]
### Description

Advanced server selection list in the VPN Region quick access section isn't shown after toggling off automatic switch and relaunching Brave.

However I shows up again eventually after accessing the list in VPN settings 

Related to https://github.com/brave/brave-browser/issues/36409

### Steps to reproduce

1. New install
2. Enable/Purchase VPN
3. From hamburger menu, select `VPN Region`
4. Disable `Automatic` switch
5. Relaunch Brave (kill app)
6. Open VPN Region page and confirm switch is off
7. Confirm list is shown

### Actual result

![IMG_7224](https://github.com/user-attachments/assets/56b1d1cd-2313-4008-ac54-8534ec69baf6)

### Expected result

Server list should be shown if the automatic switch is disabled.

### Reproduces how often

Easily reproduced

### Brave version

1.69

### Device/iOS version

iPhone / iOS 17

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7.2
Brave build: 1.75 (130)
BraveCore: 1.75.130 (132.0.6834.57)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/40855#issue-2505657298
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the list of VPN servers is shown when the `Automatic` toggle switch is off and Brave is relaunched.
- Verified that enabling and disabling the `Automatic` toggle switch works as expected.

---------------------------

https://github.com/user-attachments/assets/aeb21651-0834-4451-a977-e1c36ecf3012
