### ISSUE TITLE
[Follow up to #37347] `Linking` an active VPN subscription from `iOS` to `Web` is not working

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#40860]
### Description

Follow-up to #37347.

### Steps to reproduce

1. Launch Brave on `iOS`
2. Purchase `VPN` subscription
3. Hamburger menu > Settings > Brave Firewall + VPN
4. Link purchase to your Brave account
5. Enter email, in my case `vbravetest04@gmail.com` > Go to email and tap the confirmation button
6. On `account.brave.com` tap `Link my subscription now` > *Observe an error*

### Actual result

`Linking` an active VPN subscription from `iOS` to `Web` is not working, and error message is shown.

----------------

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/d982ccfd-3ac4-47ee-95d5-5630cf7cc311) | ![2](https://github.com/user-attachments/assets/6e1d1c59-db8b-4666-8a66-79f69b944467) | ![3](https://github.com/user-attachments/assets/0815ab18-30c6-4574-8d36-6116396c9e1c) | ![4](https://github.com/user-attachments/assets/7ab731ad-3e00-4cd7-9c0f-395a47cd5c5b) | ![5](https://github.com/user-attachments/assets/fc147958-c71d-4f02-b5b8-4895148920ed) |

https://github.com/user-attachments/assets/8fe1cae9-19ed-468e-8a91-361ef8a23a80

### Expected result

`Linking` an active VPN subscription from `iOS` to `Web` must work as expected.

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.69 (162)
BraveCore: 1.69.162 (128.0.6613.120)

### Device/iOS version

iPhone 14 / iOS 17.6.1

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

cc @Brandon-T @pavelbrm

**Comment by hffvld** [comment]
The same issue was observed when `linking` `Leo's` subscription from `iOS` to the `Web.`

------------

https://github.com/user-attachments/assets/548e636e-ed01-4170-acf0-f5c95b7ea47f

https://github.com/user-attachments/assets/de03f0d7-e0f7-4af0-a8c5-10975299d2ae

**Comment by pavelbrm** [comment]
Replied in Slack. Repeating here just in case.

@hffvld Deferring this to @Brandon-T for now.

As you can see on the recording, the website throws an error saying it could not find the receipt. The backend does not even get a chance to participate here.
We've seen a number of complains from users over the course of the last few months about similar behaviour, but I have not heard of any investigations/changes made client-side to mitigate it (it might be that I am simply not aware of them).

**Comment by Brandon-T** [comment]
This was fixed by: https://github.com/brave/brave-core/pull/25443
