### ISSUE TITLE
Some pdf do not open in browser on Linux

### ISSUE THREAD

**Issue by sirius-see** [brave/brave-browser#40878]
### Description

Certain pdf links do not open in the browser, but allow only a download. Other pdf links open as expected.

### Steps to reproduce

1. Access [this link](https://www.maxiv.lu.se/wp-content/plugins/sharepoint-plugin/ajax/downloadFile.php?site_id=MAXIV&version_series_id=68&repository_id=0fbdb5b5-c377-4ff8-9350-6889fdf4c076) and the _Save Dialog_ opens.
3. If instead I go to [this link](https://www.ekonomiwebben.lu.se/sites/ekonomiwebben.lu.se/files/2024-03/lunds-universitets-arsredovisning-2023-tillganglig.pdf) the pdf is shown.

### Actual result

Only one pdf opens in browser.

### Expected result

Both pdf open in browser.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave	1.69.162 Chromium: 128.0.6613.120 (Official Build) (64-bit) 
Revision	e534755d4eb5ad363bb357735e614be1c6421e02
OS	Linux

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Elsewhere comments about space or other special characters in the pdf filename affecting this behaviour are found.

**Comment by rebron** [comment]
Closing as works for me. The first link looks like the website intends for you to download the pdf file versus have it load in the browser which is the second link.

**Comment by sirius-see** [comment]
That's about the strangest rationale I ever heard for closing a bug "_..because it works for me_".

- It should be up to the user to decide if a pdf (or other file, for that matter) is downloaded or shown directly, not up to the website.
- Opening either of the two links in Firefox just produces the result I expect right away, so clearly it is possible to show the pdf's.
- There are countless similar but scattered reports about Brave not showing pdf's directly, but offering only download.

Please re-open or link to another open issue report and fix this because it **doesn't work for me and many others**. Happy it works for you.
