### ISSUE TITLE
Remove Greaselion after Rewards stop using it

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#40873]
### Description

After https://github.com/brave/brave-core/pull/25394 is merged and the new feature is considered as launched we don't need Greaselion code anymore.
The overlay idea of Greaselion is good, but the implementation is limited and has the number of issues:
1. slows down the startup
2. make a scoped_temp_dir folder in user-data-dir
3. user a number of extension instead of a one
4. doesn't support android

If we really need this feature is should be reimplemented.

**Comment by atuchin-m** [comment]
As the first step Greaselion should be disabled for the most of Brave users: https://github.com/brave/brave-browser/issues/40873

**Comment by LaurenWags** [comment]
@atuchin-m if this is covered by testing https://github.com/brave/brave-core/pull/25949 (per your [Test Plan on the PR](https://github.com/brave/brave-core/pull/26283#issue-2621315442)) - should this one be `QA/No`? 

Unless there are additional cases/steps to cover, in which case please let @brave/qa-team know. 

Until we decide, marking this one as `QA/Blocked` (have requested a test plan for https://github.com/brave/brave-core/pull/25949 via https://github.com/brave/brave-browser/issues/34237#issuecomment-2470977226 cc @zenparsing)

cc @rebron @kjozwiak

**Comment by atuchin-m** [comment]
@LaurenWags 
The PR doesn't change anything in terms of user-visible behavior.
The important thing is to verify that basic Rewards functionally is okay.
I believe we can done it in https://github.com/brave/brave-core/pull/25949, so we don't need to test anything extra here.

**Comment by LaurenWags** [comment]
Thanks @atuchin-m. Removing `QA/Blocked` and will change to `QA/No` as this will be covered for verifications via testing of https://github.com/brave/brave-browser/issues/34237 / https://github.com/brave/brave-core/pull/25949.
