### ISSUE TITLE
Disable Greaselion service if Rewards isn't enabled

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#40872]
### Description

We don't use Greaselion for anything else now.
I should save some CPU cycles especially during the startup.

**Comment by LaurenWags** [comment]
@atuchin-m looks like the issue with the test plan (https://github.com/brave/brave-browser/issues/39610#issuecomment-2352471054) is still open. Does that need to be closed and uplifted to 1.72.x for this issue (https://github.com/brave/brave-browser/issues/40872) to be verified? 

cc @kjozwiak

**Comment by atuchin-m** [comment]
@LaurenWags it's a meta issue to track all the related issue. I've closed it because all the depended issues are resolved.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.72.85 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 2c872aa4d2694bc73ec58e3b14538a4008a6381e
OS | Windows 10 Version 22H2 (Build 19045.5011)
```
- Verified the test plan from https://github.com/brave/brave-browser/issues/39610#issuecomment-2352471054

**Comment by LaurenWags** [comment]
Removed `QA Pass-Win64` label for now as basic WDP functionality needs to be checked in case 3.

Have asked @remusao on Slack for assistance. Adding `QA/Blocked` until we have this additional information.

cc @atuchin-m @rebron @kjozwiak

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.73.86 Chromium: 131.0.6778.39 (Official Build) (x86_64)
-- | --
Revision | 52163bcf4e40f27ddb76ffa79c90a8833084a9bd
OS | macOS Version 14.7.1 (Build 23H222)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.73.86 Chromium: 131.0.6778.39 (Official Build) (64-bit)
-- | --
Revision | 52163bcf4e40f27ddb76ffa79c90a8833084a9bd
OS | Linux
```
