### ISSUE TITLE
[iOS] - Receipt Linking on TestFlight not working

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#40874]
### Description

- Receipt Linking on TestFlight gives an error that no receipt is found, even though there is one.

### Steps to reproduce

1. Purchase VPN on the AppStore
2. Attempt to Link Receipt to the Website

### Actual result

- No Receipt Found

### Expected result

- Receipt is there locally, and the website should see it

### Reproduces how often

Easily reproduced

### Brave version

- 1.69.x

### Device/iOS version

Any

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.69.165` or higher for `1.69.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6.1
Brave build: 1.69 (167)
BraveCore: 1.69.167 (128.0.6613.127)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/40874#issue-2507434460 and https://github.com/brave/brave-core/pull/25443#issuecomment-2333000479
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `VPN` subscription can be linked to the `Web` successfully.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/8c19bb75-6439-462b-b2c8-d6e8a5c8265f) | ![2](https://github.com/user-attachments/assets/073b6da3-ee2e-424e-aa00-655127bca8f3) | ![3](https://github.com/user-attachments/assets/b46aca5d-0feb-43ed-870b-1701ac946f04) |
| ![1](https://github.com/user-attachments/assets/dfe5090e-af4d-4945-8619-bbb351e1e564) | ![2](https://github.com/user-attachments/assets/6453d849-aa42-4a33-afdb-6d76373716c5) | ![3](https://github.com/user-attachments/assets/a76cc431-ebf7-4446-9ecb-1bd8fbc4c2c3) |

https://github.com/user-attachments/assets/8b92dc6c-d653-4d1d-b71f-ea78f4d66683
