### ISSUE TITLE
[Brave News]: Update relative times in the feed

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#40875]
Steps to repro
1. Open a feed
2. Observe the relative time on a relatively new article (like 1 hour ago)
3. Wait an hour

Expected result:
The publish time is `2 hours ago`

Actual result
The publish time is `1 hour ago`

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.111 Chromium: 130.0.6723.31 (Official Build) (64-bit)
-- | --
Revision | a39f12f230248c726d3f1cac2d59dd4dcac714d7
OS | Windows 11 Version 23H2 (Build 22631.4317)
```
Reproduced the issue in `1.70.126 Chromium: 129.0.6668.100`

example | example 
----- | ------
![Image](https://github.com/user-attachments/assets/c4847c30-f6ad-481e-8e4d-df7857fba185)|![Image](https://github.com/user-attachments/assets/3162f4dc-356d-40d1-8ac1-38a6a3dd4845)

1. Installed 1.71.111
2. launched Brave
3. enable news via `Turn on News` 
4. observed the relative time on a relatively new article at 2:22 pm
      - first article show 48 minutes ago 
      - second article show 6 hours ago  
5. waited for an hour

Confirmed relative times in the feed got updated as below at 3.25 pm

  - first article (CBR) shows 2 hours ago 
  - second article (Hollywood Reporter) shows 7 hours ago  

      
example | example 
----- | -----
![Image](https://github.com/user-attachments/assets/a6b4682d-aaaf-4b81-b1a4-8017a916da1b)|![Image](https://github.com/user-attachments/assets/833b3f5c-e908-461a-95fc-98f22ef42fd8)
