### ISSUE TITLE
Provider Icons are broken for LiFi and Auto in Swap

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#40881]
### Description

- The `Auto` Brave Icon is missing when you open the `Select Provider` dropdown
- The `Li.Fi` icon is broken when you select `Li.Fi` as an option

### Steps to reproduce

1. Open the `Wallet` and navigate to the `Swap` screen
2. Open the `Select Provider` dropdown, the `Brave` icon is missing for `Auto`
3. Select `Li.Fi` as the provider, the `Li.Fi` icon is broken after selection

### Actual result

https://github.com/user-attachments/assets/62b3300f-2709-4130-8261-1c0541e66df6

### Expected result

https://github.com/user-attachments/assets/da72df5b-44cf-4b9d-b25e-01f2379da609

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.101 Chromium: 128.0.6613.120 (Official Build) beta (arm64) 

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.70.105` or higher for `1.70.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.105 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | dd1f0aff786e2f4b694066ba8500616833591bf1
OS | Windows 11 Version 23H2 (Build 22631.4037)

- Verified steps from [brave/brave-core#25451](https://github.com/brave/brave-core/pull/25451)
- Verified Provider Icons shows correctly on Swap screen
- Verified on both Swap page and wallet panel

https://github.com/user-attachments/assets/e4512a31-a880-4c23-8775-d7c07aaaf64e
