### ISSUE TITLE
Typo on Sync Page

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#4088]
## Description 
Small typo on brave://sync. The page should say _affect_ rather than _effect_. This issue was reported by a user on twitter: https://twitter.com/jackbremer/status/1116788373329518593

## Actual result:
![image](https://user-images.githubusercontent.com/815158/56062461-0ed37d80-5d32-11e9-9a40-a9780c8ee33b.png)

## Brave version (brave://version info)
0.62.51

**Comment by rebron** [comment]
cc: @AlexeyBarabash @rossmoody Can you take a look and grab this one? It should be "affect" instead of effect.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.65.93 Chromium: 74.0.3729.131 (Official Build) beta (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.523




![image](https://user-images.githubusercontent.com/38657976/57778159-132ff380-7741-11e9-85bb-eb1b61b81ff3.png)
