### ISSUE TITLE
Android 7 no longer supported, newer versions break Sync

### ISSUE THREAD

**Issue by dark-penguin** [brave/brave-browser#40890]
### Description

Which release is the latest that supports Android 7.1.2 (LineageOS 14.1)?

And is there a way disable the update notification on the desktop? I can not update, updating will introduce some changes that will break Sync since I can't update it on my phone anymore. Also, it's a nitpick, but newer versions segfault if I try to see my saved passwords.

Oh! More importantly, I can't let the Windows one update, or else it will break everything else! How can I prevent that?

### Steps to reproduce

1. Look for Brave in F-Droid - it's not there
2. Look for Brave in Aurora Store - it displays whichever version I already have installed
3. Try each release one by one, give up after 20 or 30 pages

### Actual result

"There was a problem parsing the package."

### Expected result

In the "Android" section in each release, shouldn't it specify that "Android 7.1 is not supported since release 1.6?.???", like in the Windows section?

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

v1.67.123 - stuck on this one, v1.68 broke Sync

### Android device

- Brand/model: Xiaomi Mi Max 2 (released before each new phone got worse than before :sunglasses: )
- Android version: 7.1.2 / LineageOS 14.1 (no Google services! :+1: )
- Brave 1.60.125 (1.65 is already not supported)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by bsclifton** [comment]
@dark-penguin I'm not sure what we can do for you unfortunately ☹️ 

You might consider dropping the Android 7 device from the sync chain. You definitely want to keep your desktop up to date! The updates and security patches are very important.

I don't think Brave on Android has a way to import passwords (yet). That should be tracked with https://github.com/brave/brave-browser/issues/35729. I was going to suggest periodically exporting passwords from your desktop and import on Android. It would be good on our part to prioritize password import so that you could have a working flow
cc: @timchilds

**Comment by bsclifton** [comment]
Maybe we can update the release notes too for when major versions of Android become deprecated (if we don't already). Do we do that on Desktop @rebron? I didn't see anything in https://github.com/brave/brave-browser/blob/master/CHANGELOG_DESKTOP.md or https://github.com/brave/brave-browser/blob/master/CHANGELOG_ANDROID.md

**Comment by bsclifton** [comment]
Closing as I don't think there's a solution for you unfortunately. At least not one we can recommend. You can search our issue log and find details about how to use group policy to disable updates (on Desktop), but I would not recommend that.  We are continually delivering updates to sync and the protocol could change in the future.

**Comment by dark-penguin** [comment]
Sending tabs between this Android 7 device and the desktop is more important than anything for me, so anything else is less important.

I was struggling with finding releases on the Github releases page - I haven't found a way to filter them by "releases, but not pre-releases". Filtering them by release notes is even more impossible. And the Android "package parsing error" doesn't even hint at the real problem. So I would suggest having "system requirements" (i.e. the last supported OS version) listed for all OS-es: "Windows - from 10+, Android - from 8+, MacOS..." (Linux is probably impossible, but maybe there are some important requirements as well). But putting a note there about "check this file about supported OS versions" would work as well. But I can't find any message about Android version deprecation even in CHANGELOG_ANDROID.

I've figured out a way to block updates (but not the update notification) - adding this to the hosts file:
```
# Brave update
127.0.0.1	updates.bravesoftware.com
127.0.0.1	updates-cdn.bravesoftware.com
127.0.0.1	updates-cdn2.bravesoftware.com
```
And the notification might actually be fine, because otherwise I always mix up the tiny "hamburger" button and the tiny "Hidden bookmarks" button that's right below it. The notification makes the hamburger icon makes it more intuitively distinguishable. But just for sake of knowledge: if the way to disable updates on Windows is via group policies, is there a similar way on Linux?

I'm not very happy with having to disabling updates either, but it's either that or updating LineageOS on my phone, which would require a lot of time (to transfer all the data and configuration). It would be perfect if Sync was backwards-compatible - maybe if it could negotiate the protocol version, because now everything will break as soon as I accidentally add any new device because it would convert the protocol. But I guess that just means "support for deprecated versions" only, so it doesn't make much sense in terms of effort.

The way I figured out what the issue was is when I took a look at the Sync log on the desktop and saw something like:
```
Events to receive: 500
ERROR: Unsupported event
Events to receive: 500
ERROR: Unsupported event
...

```

**Comment by dark-penguin** [comment]
And by the way, thank you for the product. :slightly_smiling_face: Brave is our only salvation from Firefox that breaks or deprecates stuff every release. And their Sync didn't even work last time I tried. :stuck_out_tongue: How do you even manage to process so many issues, actually giving attention to them!
