### ISSUE TITLE
Translation bubble is not shown on nightly builds

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#4089]
## Description 
When visits a page in a different locale on nightly, translation bubble is not shown automatically.
This is because we don't have google API key configured, so the translate flow is not triggered.

## Steps to Reproduce
   1. Visit https://www.deutschland.de/de/topic/wissen/school-of-games-ausbildung-zum-spieleentwickler or any pages not in your default locale.

## Actual result:
No translation bubble prompt in the url bar.

## Expected result:
Should have a translation bubble prompt in the url bar.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
Version 0.65.50 Chromium: 74.0.3729.61 (Official Build) nightly (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? No.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.65.95 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Verified STR from description
![Screen Shot 2019-05-17 at 4 11 58 PM](https://user-images.githubusercontent.com/28145373/57953660-afcbd000-78be-11e9-9e54-5477b2257c63.png)
