### ISSUE TITLE
Support for mouse autoscroll  ( middle click mouse)

### ISSUE THREAD

**Issue by junbr0** [brave/brave-browser#40896]
### Platforms

Linux, macOS, Windows

### Description

please support for feature mouse middle click autoscroll ( in firefox browser term feature)
when middle click mouse activated it will create web anchor and smoothly scrolling pages on mouse direction ( up or down).
very useful when middle scroll doesnt work but mouse middle click still functional.
forgive my english...
thank you.

**Comment by rebron** [comment]
@junbr0 brave://flags/#middle-button-autoscroll Does that flag work for you?

**Comment by junbr0** [comment]
works well, it turns out that the existing feature does not appear in the menu on chrome or brave browser. 
previously i didnt know...
the problem was solved. thanks
