### ISSUE TITLE
BYOM crash with Azure Open AI models

### ISSUE THREAD

**Issue by LunaticoCR** [brave/brave-browser#40902]
### Description

I have tried using the 'Bring your own model' feature to plug in my own Azure Open AI model, and I've found a few issues around this area, mainly a crash when trying to use the assistant through the model I configured. I tried with two models, gtp-3.5-turbo and gpt-4o.

The issues are:
1. After configuring a new BYOM and selecting it as the "Default model for new conversations', the Leo sidebar would not use this model until after an app restart
2. The BYOM settings have a field called 'API Key', however the underlying request out to the LLM sends a header with 'Authorization: Bearer {{api-key}}'.
3. The browser crashes right after sending something on to the assistant sidebar.

### Steps to reproduce

1. Go to Settings -> Leo -> Add new model
2. Fill in all the relevant fields
3. Click Save model
4. Select the newly added model as Default model for new conversations
5. Restart the browser app
6. Open the Leo sidebar and type something or ask a question to the assistant
7. At this point the browser will crash

### Actual result

There's two major problems:
1. Despite the fact that the UI says 'API Key', the value you put there is sent to the LLM in an Authorization header as if it was a bearer token. This is incorrect, the header should be api-key with the token as the value with no 'Bearer ' prefix. Initially I was putting the api key in there and I was getting 401's, I captured the http traffic and noticed this discrepancy. Luckily I can also use bearer tokens with my LLMs.
2. When trying to use the assistant with my own LLM the browser would crash. I can see the http request goes out to the LLM and succeeds with a 200 OK. But the browser immediately crashes so I presume the issue is while deserializing or processing the response.

### Expected result

- The BYOM settings should have the option to provide either an api key or a bearer token and the request should be sent with the appropriate corresponding header.
- The browser should not crash if it can't handle the LLM request for whatever reason, a clear error message should be presented to the user.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.69.162 Chromium: 128.0.6613.120 (Official Build) (arm64)
Revision | e534755d4eb5ad363bb357735e614be1c6421e02
OS | macOS Version 14.6.1 (Build 23G93)
JavaScript | V8 12.8.374.26
User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --disable-domain-reliability --enable-dom-distiller --enable-distillability-service --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --lso-url=https://no-thanks.invalid --sync-url=https://sync-v2.brave.com/v2 --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/user/Library/Application Support/BraveSoftware/Brave-Browser/Profile 4
Linker | lld
Variations Seed Type | Safe
Active variations | main@f9743a8ef8f98bd977f1f048bf6e8f1d65fd4cffAllowCertainClientHintsStudy:EnabledBraveAIChatEnabledStudy:EnabledBraveAdblockMobileNotificationsListDefault:EnabledBraveAdsAdEventStudy:EnabledBraveAdsConversionsStudy:EnabledBraveAdsExclusionRulesStudy:EnabledBraveAdsNewTabPageAdsStudy:EnabledBraveAdsSiteVisitStudy:EnabledBraveAdsTextClassificationPageProbabilitiesStudy:EnabledBraveAggressiveModeRetirementExperiment:DisabledBraveAutoTranslateStudy:AutoTranslateDisabledBraveCleanupSessionCookiesOnSessionRestore:DisabledBraveDebounceStudy:EnabledBraveFeedUpdateStudy:EnabledBraveForgetFirstPartyStorage:EnabledBraveGoogleSignInPermissionStudy:EnabledBraveHorizontalTabsUpdateEnabledStudy:EnabledBraveP3AConstellationEnabled:EnabledBraveP3ANebulaRelease:EnabledBraveP3ATypicalJSONDeprecationEnabled:EnabledBraveRewardsAllowSelfCustodyProvidersStudy:EnabledBraveRewardsWebUiPanelStudy:EnabledBraveScreenFingerprintingBlockerStudy:EnabledBraveSearchAdStudy:EnabledBraveSearchPromotionBannerStudyOnStable:DefaultBraveWalletAnkrBalancesEnabled:DefaultBraveWebcompatExceptionsServiceReleaseStudy:EnabledClampPlatformVersionClientHint:DisabledCookieListDefaultStudy:EnabledCrossPlatformVPNStudy:EnabledDefault1pBlockingStudy:DisabledDisableReduceLanguage:EnabledEphemeralStorageStudy:EnabledExtensionsManifestV2StudyRelease:EnabledMacCoreLocationBackendStudy:EnabledPartitionedCookies:EnabledSpeedreader TTS:EnabledUndecryptablePasswords:EnabledUserActivityStudy:TriggersWhatsNewStudy:Enabled

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Please let me know what other information (logs or stack traces) I can provide to analyse this further.

**Comment by rebron** [comment]
@LunaticoCR Can you go to brave://crashes and paste the crash ID in this issue.

**Comment by LunaticoCR** [comment]
@rebron sure, I just reproduced it again and here's the crash info.
```
Crash from Monday 16 September 2024 at 09:56:56
Status: Uploaded
Uploaded crash report ID: ac671100-9ce4-970c-0000-000000000000
Upload time: Monday 16 September 2024 at 09:56:57
```

In this screenshot you can see the captured request that was sent and succeeded.
![image](https://github.com/user-attachments/assets/1ba76eac-f639-4992-a28d-374547297f9c)

Here are the response stream events, in case you can spot something that could blow up the parser:
```
data: {"choices":[],"created":0,"id":"","model":"","object":"","prompt_filter_results":[{"prompt_index":0,"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}]}

data: {"choices":[{"content_filter_results":{},"delta":{"role":"assistant"},"finish_reason":null,"index":0}],"created":1726477015,"id":"chatcmpl-A81pP6alc0RE3Zla0twbE5qPswTLA","model":"gpt-4o-2024-05-13","object":"chat.completion.chunk","system_fingerprint":"fp_80a1bad4c7"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"Hello"},"finish_reason":null,"index":0}],"created":1726477015,"id":"chatcmpl-A81pP6alc0RE3Zla0twbE5qPswTLA","model":"gpt-4o-2024-05-13","object":"chat.completion.chunk","system_fingerprint":"fp_80a1bad4c7"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"!"},"finish_reason":null,"index":0}],"created":1726477015,"id":"chatcmpl-A81pP6alc0RE3Zla0twbE5qPswTLA","model":"gpt-4o-2024-05-13","object":"chat.completion.chunk","system_fingerprint":"fp_80a1bad4c7"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" How"},"finish_reason":null,"index":0}],"created":1726477015,"id":"chatcmpl-A81pP6alc0RE3Zla0twbE5qPswTLA","model":"gpt-4o-2024-05-13","object":"chat.completion.chunk","system_fingerprint":"fp_80a1bad4c7"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" can"},"finish_reason":null,"index":0}],"created":1726477015,"id":"chatcmpl-A81pP6alc0RE3Zla0twbE5qPswTLA","model":"gpt-4o-2024-05-13","object":"chat.completion.chunk","system_fingerprint":"fp_80a1bad4c7"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" I"},"finish_reason":null,"index":0}],"created":1726477015,"id":"chatcmpl-A81pP6alc0RE3Zla0twbE5qPswTLA","model":"gpt-4o-2024-05-13","object":"chat.completion.chunk","system_fingerprint":"fp_80a1bad4c7"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" assist"},"finish_reason":null,"index":0}],"created":1726477015,"id":"chatcmpl-A81pP6alc0RE3Zla0twbE5qPswTLA","model":"gpt-4o-2024-05-13","object":"chat.completion.chunk","system_fingerprint":"fp_80a1bad4c7"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" you"},"finish_reason":null,"index":0}],"created":1726477015,"id":"chatcmpl-A81pP6alc0RE3Zla0twbE5qPswTLA","model":"gpt-4o-2024-05-13","object":"chat.completion.chunk","system_fingerprint":"fp_80a1bad4c7"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" today"},"finish_reason":null,"index":0}],"created":1726477015,"id":"chatcmpl-A81pP6alc0RE3Zla0twbE5qPswTLA","model":"gpt-4o-2024-05-13","object":"chat.completion.chunk","system_fingerprint":"fp_80a1bad4c7"}

data: {"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":"?"},"finish_reason":null,"index":0}],"created":1726477015,"id":"chatcmpl-A81pP6alc0RE3Zla0twbE5qPswTLA","model":"gpt-4o-2024-05-13","object":"chat.completion.chunk","system_fingerprint":"fp_80a1bad4c7"}

data: {"choices":[{"content_filter_results":{},"delta":{},"finish_reason":"stop","index":0}],"created":1726477015,"id":"chatcmpl-A81pP6alc0RE3Zla0twbE5qPswTLA","model":"gpt-4o-2024-05-13","object":"chat.completion.chunk","system_fingerprint":"fp_80a1bad4c7"}

data: [DONE]
```

I also re-ran this same request, but with ```stream=false```, and below is the json response, in case in case there's something interesting in that payload. The aggregation of all the deltas in the streamed events should be equivalent to this.
```
{
  "choices": [
    {
      "content_filter_results": {
        "hate": {
          "filtered": false,
          "severity": "safe"
        },
        "self_harm": {
          "filtered": false,
          "severity": "safe"
        },
        "sexual": {
          "filtered": false,
          "severity": "safe"
        },
        "violence": {
          "filtered": false,
          "severity": "safe"
        }
      },
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": "Hello! How can I assist you today?",
        "role": "assistant"
      }
    }
  ],
  "created": 1726477614,
  "id": "chatcmpl-A81z4urHJFyXXIfPQYjwx6mTweGvO",
  "model": "gpt-4o-2024-05-13",
  "object": "chat.completion",
  "prompt_filter_results": [
    {
      "prompt_index": 0,
      "content_filter_results": {
        "hate": {
          "filtered": false,
          "severity": "safe"
        },
        "self_harm": {
          "filtered": false,
          "severity": "safe"
        },
        "sexual": {
          "filtered": false,
          "severity": "safe"
        },
        "violence": {
          "filtered": false,
          "severity": "safe"
        }
      }
    }
  ],
  "system_fingerprint": "fp_80a1bad4c7",
  "usage": {
    "completion_tokens": 9,
    "prompt_tokens": 227,
    "total_tokens": 236
  }
}
```

**Comment by jonathansampson** [comment]
@LunaticoCR, I'd like to start investigating this issue. Can you tell me more about how you setup access to these models with Azure?

**Comment by LunaticoCR** [comment]
Sure @jonathansampson .
Azure AI Services <-> proxy <-> consumer services

The models are just deployed on shared instances. We have a proxy in the middle, it's not a proxy in the common sense, it's just a passthrough that abstracts authentication. Proxy authenticates with azure using api key. Consumer authenticates with proxy with a bearer token provided in an "Authorization" header. request/response payloads are not manipulated in any way in the proxy.

**Comment by rpatel15-hue** [comment]
+1 had the same issue

**Comment by jonathansampson** [comment]
@LunaticoCR and @rpatel15-hue - I can see that we're crashing upon attempting to read data from the first `choices` array, which is empty in some cases. This will be resolved. That said, the payload is different for `stream=false` scenarios. Can you disable streaming, and see if you see experience any other issues? I'm setting up some unit tests on my end, to make sure we handle Azure better moving forward.

**Comment by LunaticoCR** [comment]
Thanks for that @jonathansampson ! Yes your observations are correct. The chunks parser needs to essentially be null and empty safe for pretty much all properties in the payload.
I did not enable streaming from the server side, the request sent from Leo has the stream=true field. I'm not sure if there's an option in the Browser setting to disable this?

**Comment by jonathansampson** [comment]
> Thanks for that [@jonathansampson](https://github.com/jonathansampson) ! Yes your observations are correct. The chunks parser needs to essentially be null and empty safe for pretty much all properties in the payload. I did not enable streaming from the server side, the request sent from Leo has the stream=true field. I'm not sure if there's an option in the Browser setting to disable this?

No option in the browser at the moment to disable streaming, though that is something we could consider for a future release :)

**Comment by LunaticoCR** [comment]
Got it @jonathansampson . So the only way I could test with no streaming is if I intercept the http request and modify the stream value to false on the fly. But I'm not sure if your response parser will behave correctly or will it be expecting chunks.

**Comment by jonathansampson** [comment]
@LunaticoCR No need to test this scenario any further for now. But, for what it's worth, I believe we're already setup to handle single-chunk responses as well.

**Comment by jonathansampson** [comment]
@LunaticoCR, a fix for this has landed in version 1.75.171 of Brave. Would you be able to test your endpoint in Brave Nightly (brave.com/download-nightly/) to see if this addresses the crashing behavior?

**Comment by LunaticoCR** [comment]
I can confirm this is now working on Beta, so I assume it's working on Nightly too. Thank you!

**Comment by jonathansampson** [comment]
> I can confirm this is now working on Beta, so I assume it's working on Nightly too. Thank you!

That's wonderful to hear. Thank you, @LunaticoCR!
