### ISSUE TITLE
[iOS] Update "Indirect Support" text for non-connected users in Rewards 2.5 panel

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#40909]
https://github.com/brave/internal/issues/1186

**Comment by kjozwiak** [comment]
The above requires `1.70.108` or higher for `1.70.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7
Brave build: 1.70 (114)
BraveCore: 1.70.114 (129.0.6668.42)
```
---------------------------

**ACTUAL RESULTS:**
- Verification notes can be found via https://github.com/brave/internal/issues/1186#issuecomment-2357050139
