### ISSUE TITLE
Auto-contribute fails due to unpaid non-signed up creators

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#4090]
This is similar to #4050, but on a different machine (work laptop) and on Beta instead of Release:

```
Brave | 0.63.35 Chromium: 74.0.3729.61 (Official Build) beta(64-bit)
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Linux
```

I got the following "insufficient funds" error:

![insufficient-funds](https://user-images.githubusercontent.com/167821/56069496-244ba600-5d38-11e9-9f11-4b3fbdb65381.png)

even though I have enough BATs in my grants wallet:

![wallet](https://user-images.githubusercontent.com/167821/56069525-3b8a9380-5d38-11e9-8d1c-2a7da25a5b4b.png)

to cover my monthly allowance:

![autocontribute-settings](https://user-images.githubusercontent.com/167821/56069540-58bf6200-5d38-11e9-8719-b4d193780f8a.png)

Here's the complete `brave://rewards` page:

![brave-rewards](https://user-images.githubusercontent.com/167821/56069546-61b03380-5d38-11e9-9582-b04720de7bdd.png)

**Comment by fmarier** [comment]
@NejcZdovc did I provide enough info this time?

**Comment by NejcZdovc** [comment]
yeah, this is great. Looks like that https://github.com/brave/brave-browser/issues/3640 didn't fix it. We will need to add balance fetch for notifications as well

**Comment by LaurenWags** [comment]
@NejcZdovc looks like https://github.com/brave/brave-core/pull/2115 (fix for #3640) wasn't merged to 0.63.x, could that be why this is occurring?

**Comment by NejcZdovc** [comment]
this is one and we had another fix for it https://github.com/brave/brave-browser/issues/4115

**Comment by rebron** [comment]
brave/brave-core#2115 got merged into 63.x and #4115 was merged into 65.x. 
This should be fixed in 65.x then?

**Comment by NejcZdovc** [comment]
@rebron this one will completely solve it https://github.com/brave/brave-browser/issues/3707

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.108 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2208
* However, even if total of auto contribute for verified pubs + total of recurring monthly tips for verified pubs is less than wallet balance, contribution does not go thru. Logged #5230
