### ISSUE TITLE
Stop using /chrome and /brave/browser in /brave/components/brave_ads

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#40903]
### Description

This includes violates chromium layering rules: https://source.chromium.org/chromium/chromium/src/+/main:components/README.md

Also it makes hard to reuse the code on mobile platforms (no //chrome for iOS, many differences for Android ) 
<img width="598" alt="image" src="https://github.com/user-attachments/assets/36807946-0b4b-427c-b081-24cf615da593">

1. the code should be refactored pass the necessary things interfaces ([an example](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/translate/chrome_translate_client.h;l=50?q=delegate&ss=chromium%2Fchromium%2Fsrc:chrome%2Fbrowser%2Ftranslate%2F)
2. these rules should be enforce via DEPS/gn

**Comment by tmancey** [comment]
@atuchin-m, as discussed closing this one as a dupicate of https://github.com/brave/brave-browser/issues/33805. If it becomes a blocker we can prioritize.
