### ISSUE TITLE
[Android] Update "Indirect Support" text for non-connected users in Rewards 2.5 panel

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#40907]
https://github.com/brave/internal/issues/1184

**Comment by kjozwiak** [comment]
The above requires `1.70.107` or higher for `1.70.x` verification 👍

**Comment by kjozwiak** [comment]
`QA/Blocked` till we get `l10n` merged into `1.70.x`. Once merged, we can remove the `QA/Blocked` label and continue verification 👍

**Comment by Uni-verse** [comment]
Verified on `Android` for `1.70.x` release per https://github.com/brave/internal/issues/1184#issuecomment-2356420793
