### ISSUE TITLE
`Save to Files` is missing from `Share menu`, and instead `Create PDF` is shown, which doesn't work at all

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#40918]
### Description

`Save to Files` is missing from the `Share menu` starting with Brave `1.69 (164)`. Instead `Create PDF` is shown, but that option doesn't work.

### Steps to reproduce

1. Launch Brave `1.69 (164)` or newer
2. Open `https://basicattentiontoken.org/BasicAttentionTokenWhitePaper-4.pdf` or `http://www.pdf995.com/samples/pdf.pdf`
3. Tap the `Share menu` > *Observe that `Save to Files` is missing*
4. Scroll down > *Observe that `Create PDF` is shown*
5. Tap `Create PDF` > Now tap `Save to Files` > *Observe that the file has `no name` and is `4KB`*

### Actual result

`Save to Files` is missing from the `Share menu` starting with Brave `1.69 (164)`. Instead `Create PDF` is shown, but that option doesn't work because the created file has `no name` and is `4KB` in size.

---------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/c8efd47d-1210-4768-857e-dfa0d07b360c) | ![2](https://github.com/user-attachments/assets/9d8e1aca-fc0a-424b-af68-8d683f38a014) | ![3](https://github.com/user-attachments/assets/38a69094-cf69-413a-9430-5c790e26c8e7) | ![4](https://github.com/user-attachments/assets/19795091-c730-4fae-9348-722f9cd2e04d) |
| ![1](https://github.com/user-attachments/assets/f642955c-0cda-420a-88d3-cf8bfb627273) | ![2](https://github.com/user-attachments/assets/532680fa-cf36-41c5-8833-f598db69a194) | ![3](https://github.com/user-attachments/assets/ddfe7544-fd81-4d99-a5fe-619d7964f049) | ![4](https://github.com/user-attachments/assets/f039a303-2169-4d0d-b191-b71e12db03ea) |

### Expected result

The `Save to Files` option must be shown in the `Share menu`, so PDF files can be saved locally.

----------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/990d6308-1646-4f88-b537-7ade03c47356) | ![2](https://github.com/user-attachments/assets/5e4db16f-256e-4bd2-8b58-a778ef6f2795) | ![3](https://github.com/user-attachments/assets/0a0bdb61-d13d-419b-8ccc-c77f5b15fc77) |

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.69 (165)
BraveCore: 1.69.165 (128.0.6613.127)

### Device/iOS version

- iPhone 14 / iOS 17.6.1
- iPad Air / iPadOS 16.7.2

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.69.168` or higher for `1.69.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.6.1
Brave build: 1.69 (168)
BraveCore: 1.69.168 (128.0.6613.138)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/40918#issue-2511356204
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Save to Files` option is shown in the `Share menu`, and PDF files can be saved locally.

---------------------------

*Save PDF*

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/8ea82d53-f5d2-46fb-90cb-633f6500cf90) | ![2](https://github.com/user-attachments/assets/db762d5e-e979-4d7b-86c9-31ea60c6f952) | ![3](https://github.com/user-attachments/assets/77658020-129c-4387-aa0f-f9aeefee04ae) |

*Save website as PDF*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/318031a6-800d-4ec5-b4a0-9cb523c97126) | ![2](https://github.com/user-attachments/assets/a7f57764-d0c7-4b86-a11c-3344ee66236d) | ![3](https://github.com/user-attachments/assets/829c2c69-84bf-4dcb-ac98-ec4ba161d5cb) | ![4](https://github.com/user-attachments/assets/71a3622e-4191-43cf-9549-4d36a093d64e) |
