### ISSUE TITLE
Enable New Playlist UI by default

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#40911]
## Description 

New Playlist UI will now be enabled by default, and should be fully tested.

Test Plan should be the same as normal Playlist tests, except the new playlist UI does not support shared playlists

Roadmap issues:
https://github.com/brave/roadmap/issues/1393
https://github.com/brave/roadmap/issues/1205

**Comment by Uni-verse** [comment]
in progress on iPhone 12 running iOS 18.0 using version 1.71.115

**New Users**

Test Cases
<table>
<tr><td>

- [x] **feature flag**
- [ ] **playlist tutorial**
- [ ] **adding items**
   - [ ] YouTube videos
   - [ ] Other media sites (Rumble, DailyMotion)
   - [ ] Audio/Sound only
- [ ] **opening in Playlist**
   - [ ] via url bar
   - [ ] via share menu
   - [ ] via long press
   - [ ] siri shortcut on homescreen (shortcuts app)
- [ ] **deleting items**
   - [ ] offline items
   - [ ] saved items
   - [ ] folders/playlists
- [ ] **creating playlists**
- [ ] **saving offline**
   - [ ] wifi
   - [ ] cellular
- [ ] **using with VPN**

</td><td>

- [ ] **playlist controls**
   - [ ] pip 
   - [ ] full screen functions
   - [ ] background play
   - [ ] timer
   - [ ] edit mode
      - [ ] delete
      - [ ] move
   - [ ] long press functions
- [ ] **settings/preferences**
   - [ ] autoplay (setting)
   - [ ] auto-save for offline (setting)
   - [ ] enable long press (setting)
   - [ ] web compatibility (setting)
- [ ] **misc.** 
   - [ ] opening playlist after re-launching Brave
   - [ ] ensure no issues after device restarts/device sleeps
   - [ ] enabling airplane mode

</td></tr></table>


 
**Existing Users**

**Comment by Uni-verse** [comment]
In progress on iPad running iOS 17.5.1 using version 1.71.116
