### ISSUE TITLE
Strip `srsltid` from all URLs

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#40912]
## Description 

Google [recently started](https://ppcmania.com/digital-marketing/googles-new-srsltid-parameter-in-organic-search) to add a new parameter to organic search results via the [auto-tagging feature of the Merchant Center](https://support.google.com/merchants/answer/15191080). It is used for conversion reporting.

We should remove `srsltd` from URLs since this identifier is [unique to each user](https://support.google.com/merchants/answer/14166401):

> The result id is created at the time of an impression. If a customer clicks the same free listings again, the same result id will be used.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.90 Chromium: 129.0.6668.59 (Official Build) beta (64-bit)
-- | --
Revision | 1f5f0d1b8a45a4c60a78c15df081751e39184b97
OS | Windows 11 Version 23H2 (Build 22631.4169)
```

Reproduced the issue in 1.70.117 

Confirmed srsltid=12345 is shown in the URL bar

![image](https://github.com/user-attachments/assets/0952df7e-8247-4bb1-84c4-163e664f8f57)




1. Installed 1.71.90
2. launched Brave
3. opened `brave://settings/shields` in a new tab
4. verified `Trackers & ads blocking` shows `Standard`
5. visited https://brave.com/?srsltid=12345

#### Confirmed that the URL bar shows https://brave.com/ and `srsltid=12345` was stripped off.


example | example 
------ | ----
![image](https://github.com/user-attachments/assets/eb5ae9f7-4a2f-43be-a644-9e35f257a6f3)|![image](https://github.com/user-attachments/assets/22ac5995-93ae-46c0-bbb4-088d950e8103)

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.71.104 x64 Beta build
- Verified steps from issue description
- Verified setting Shields to `Block trackers and ads (Standard) and visiting `https://brave.com/?srsltid=12345`, redirects to `https://brave.com` and removes **`?srsltid=12345`**

https://github.com/user-attachments/assets/7572defc-6779-47b0-9847-0c373d8c689b

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7
Brave build: 1.71 (116)
BraveCore: 1.71.116 (130.0.6723.58)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/25478#issue-2511073311
2. *Verify*

**ACTUAL RESULTS:**
- Verified that navigating to `https://brave.com/?srsltid=12345 ` removes `srsltid=12345` parameter and redirects to `https://brave.com/` when `Trackers & Ads Blocking` in `Brave Shields` is set to `Standard`.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/e53634fd-42e5-47f1-bf31-42be27069dd8) | ![2](https://github.com/user-attachments/assets/7f708435-9620-4d94-b19e-1a19161b09c7) | ![3](https://github.com/user-attachments/assets/238401ad-3eca-43c3-9298-b46f633963fa) | ![4](https://github.com/user-attachments/assets/8c9e0c86-1a63-45c7-a0be-51a3edd50920) |
