### ISSUE TITLE
Devices duplicated after adding new Bookmark

### ISSUE THREAD

**Issue by wueric77** [brave/brave-browser#40928]
### Description

After addind a link to my bookmark in my Brave Desktop v1.69.162 on Linux Ubuntu 22.04, my device is dupicated in my Android Brave v.1.69.160 on Android 13 TKQ1.221114.001

![Screenshot_2024-09-07-14-52-40-420_com brave browser](https://github.com/user-attachments/assets/1af060f0-7c00-4af5-9edd-7d7bad78576a)

### Steps to reproduce

1. Add new bookmark in Brave on Linux Ubuntu 22.04
2. 
3. 

### Actual result

My device is dupicated in my Android Brave v.1.69.160 on Android 13 TKQ1.221114.001

### Expected result

Device duplication in Brave on Android

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

Brave Desktop v1.69.162 Linux Ubuntu 22.04,4

### Android device

- Brand/model: Xiaomi Redmi Note 11
- Android version: 13 TKQ1.221114.001

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [X] in the latest version of Chrome

**Comment by wueric77** [comment]
After update to App-Version Brave 1.69.164, Chromium 128.0.6613.127 on my Android Phone, the issue is gone ;-)

**Comment by bsclifton** [comment]
Thanks for the update @wueric77!

cc: @AlexeyBarabash
