### ISSUE TITLE
Revoked certificates not recognized by Brave desktop (CRLSets)

### ISSUE THREAD

**Issue by brokoler** [brave/brave-browser#40929]
### Description

Brave should automatically updat and use CRLSets to recognize websites with revoked HTTPS certificates.
When certificates were revoked, Brave should recognize them and prevent opening the websites.

Earlier this was discussed, the issue is closed but it's not working:
https://github.com/brave/brave-browser/issues/518

### Steps to reproduce

1. Open website https://revoked.badssl.com
2. Brave opens the website which is wrong, the website should be prevented to load and Brave should show an error

### Actual result

Website is opened. It should not

### Expected result

After TLS handshake the website should not be loaded.
A local webpage should be shown with error "SEC_ERROR_REVOKED_CERTIFICATE"

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave v1.69.162 based on Chromium v128.0.6613.120

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by diracdeltas** [comment]
What OS have you tried this on? It's working as expected on MacOS.

**Comment by diracdeltas** [comment]
Our QA team could not repro on windows either. Could you try going to brave://components/ and let us know what it says for CRLset?

**Comment by brokoler** [comment]
Based on the old issue posted above, it seemed to work with macOS but not with different operating systems.
I'm using Brave on Windows and it's not working.

I see following for CRLset:
![grafik](https://github.com/user-attachments/assets/4d287fcd-d0ba-4215-ba16-66fb15834e0f)

Thanks that you are looking into the issue

**Comment by brokoler** [comment]
Okay it seems to partly work after testing again, probably my CRLset file was not updated immediately when Brave was installed.

But Brave doesn't warn for some websites that use revoked certificates.
So there still is an issue, probably with the CRLset database itself.

**Tested websites:**
- https://revoked.badssl.com/ is working, an error "net::ERR_CERT_REVOKED" is shown before the page is loaded
- https://revoked.grc.com/ is not working, the page is loaded but it should not since the cert is revoked (Firefox is warning me)
- https://digicert-tls-ecc-p384-root-g5-revoked.chain-demos.digicert.com/ is not working, the page is loaded but it should not since the cert is revoked (Firefox is warning me)

**Comment by diracdeltas** [comment]
@brokoler thanks for the additional information. FWIW Brave uses Chrome's crlsets which may differ from Firefox's; however I would expect the results to always be the same in Chrome.

In our testing we also found that sometimes revoked.badssl.com loads without warning in Chrome, so this appears to be an upstream issue as well

**Comment by diracdeltas** [comment]
We reported it upstream here and they are working on it: https://issues.chromium.org/issues/365589060 (private for now)

**Comment by diracdeltas** [comment]
This should be fixed once you pull CRLSet - Version: 9105
