### ISSUE TITLE
[Android] Replace desktop icon with laptop icon for desktop/laptop device

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#40936]
This issue is to update desktop/laptop icon as a follow up of https://github.com/brave/brave-browser/issues/7359 based on https://github.com/brave/brave-browser/issues/7359#issuecomment-2333865760

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240925.009 release-keys
Brave build: 1.74.8 
Chromium: 131.0.6778.69 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/25939#issue-2579864258
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `phones` (Android and iOS) have the `Phone` thumbnail in the `Sync` chain.
- Verified that `tablets` (Android and iPadOS) have the `Tablet` thumbnail in the `Sync` chain.
- Verified that `computers` (Desktop and Laptop) have the `Laptop` thumbnail in the `Sync` chain.

### **NOTE: `Tablets` have a wrong thumbnail in the `Send to your devices` bottom-sheet modal - #41413.**

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/f093736f-8897-48ed-b84c-0338ce78e4f0) | ![2](https://github.com/user-attachments/assets/3ee6a82c-84c5-4be7-9701-3e4d394d6dc6) | ![3](https://github.com/user-attachments/assets/5fb73359-cb50-47aa-88ce-54f78021b750) | ![4](https://github.com/user-attachments/assets/10dcfa0b-5674-4f50-9d32-ce122167f6ab) |
