### ISSUE TITLE
Favicons empty on NTP after loading webpage in Private mode

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#40935]
### Description

Favicons are not shown after navigating to URL in Private browsing mode

### Steps to reproduce

1. New install
2. Open Private tab
3. Tap on one of the favorites on NTP
4. Once webpage loads, return to NTP
5. Confirm favicon is shown

### Actual result

Favicon is updated and looks empty/generic

![IMG_7279](https://github.com/user-attachments/assets/0ec6bdc6-e026-41d2-8345-f31597fc2beb)

### Expected result

Favicon should not be empty

### Reproduces how often

Easily reproduced

### Brave version

1.69.167

### Device/iOS version

iPhone 12 / iOS 17

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7.1
Brave build: 1.73 (89)
BraveCore: 1.73.89 (131.0.6778.69)
```

---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/40935#issue-2514175058
2. *Verify*

**ACTUAL RESULTS:**
- Verified that Favicon is not empty
- Verified the same for `Standard` and `Private` tabs

---------------------------

https://github.com/user-attachments/assets/b47f0665-0fec-4695-8478-313e08f07c9c
