### ISSUE TITLE
Update Wallet Background

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#40948]
### Platforms

Linux, macOS, Windows

### Description

We need to update the `Wallet` background to the updated designs in fimga https://www.figma.com/design/muVcmcu4RFNu0LkXe9VRDl/Wallet-2.0?node-id=19356-251399&node-type=INSTANCE&m=dev

![Screenshot 17](https://github.com/user-attachments/assets/be7ee803-f51e-4bf4-a228-0c110532115f)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.71.97 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | de99cbcb1aa0aa00877d356e4733f4e5481e89eb
OS | Windows 11 Version 23H2 (Build 22631.4169)

- Verified steps from [brave/brave-core#25507](https://github.com/brave/brave-core/pull/25507)
- Verified wallet background is updated to gradient colour

Light | Dark
-- | --
![image](https://github.com/user-attachments/assets/2d09df6d-934e-4d58-b61f-6bbf82ce930d) | ![image](https://github.com/user-attachments/assets/53abae56-6dd5-4ac3-98d2-9c60b18ee72e)
