### ISSUE TITLE
Bookmark Icons Do Not Sync

### ISSUE THREAD

**Issue by Modelmat** [brave/brave-browser#4095]
## Steps to Reproduce

   1. Set up a browser on one device, add some bookmarks
   2. Set up a sync chain with another device
   3. Bookmark icons do not sync

## Actual result:

Synced device;
![image](https://user-images.githubusercontent.com/25718989/56072548-94f7ce80-5ddb-11e9-85dd-fc3e0b52b342.png)
original device;
![2019-04-13_11-02](https://user-images.githubusercontent.com/25718989/56072563-c375a980-5ddb-11e9-9af0-7a63049d4bd5.png)

## Expected result:
Icons sync between devices.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

Brave | 0.62.51 Chromium: 73.0.3683.103 (Official Build)unknown (64-bit)
-- | --
Revision | e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

**Comment by Blaxou** [comment]
I don't think it is needed to sync the icons as they usually can change pretty often, when you visit a bookmarked page the icons are cached by the browser. It's probably a design choice the, not a bug ;)

**Comment by srirambv** [comment]
Once you visit the bookmark link the favicon automatically loads.  This is expected behaviour.
