### ISSUE TITLE
[ads] Add brave://ads-internals

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#40952]
### Description

Add a new `brave://ads-internals` page to display URL patterns and expiry dates extracted from the `creative_set_conversions` table within `Default/ads_service/database.sqlite`, specifically the `url_pattern` and `expire_at` fields.

If there are URL patterns, we should display this message:

> Active Brave Search Ads [conversion URL patterns](https://ads-help.brave.com/campaign-performance/reporting#choosing-an-effective-conversion-url):
>
> (table with two columns: URL pattern & expiry)
>

If no URL patterns are present, we should display this message:

> No Brave Search Ads [conversion URL patterns](https://ads-help.brave.com/campaign-performance/reporting#choosing-an-effective-conversion-url) are currently being matched.

Refer to `brave://skus-internals` for a multi-platform implementation of an internal page.

**Comment by tmancey** [comment]
cc @fmarier @iambrianfung

**Comment by fmarier** [comment]
Is it possible to add a "Clear Brave Ads data" button at the bottom like we have on `brave://settings/clearBrowserData`?

**Comment by tmancey** [comment]
> Is it possible to add a "Clear Brave Ads data" button at the bottom like we have on `brave://settings/clearBrowserData`?
> 
> This could reload the page afterwards so that users can have immediate confirmation that the data is gone.

We only allow users to clear ads data for non-Rewards, because for Rewards users they can reset. This would be strange to have the ability to clear rewards from brave://ads-internals, your thoughts? Thanks

**Comment by fmarier** [comment]
Yes, I think we can have something like:
- _Clear Brave Ads data_ button for non-Rewards users
- _Reset Brave Rewards_ link for Rewards users

**Comment by tmancey** [comment]
Ok sure let's have nothing for rewards users as this makes more sense to me. Thanks

**Comment by aseren** [comment]
Screenshots of brave://ads-internals on Desktop:
![Image](https://github.com/user-attachments/assets/abd9ac09-f299-4c2d-913a-375db2d19676)
![Image](https://github.com/user-attachments/assets/b76d4883-f100-479c-89be-d64fbf330a3e)

Screenshots of brave://ads-internals on iOS:
![Image](https://github.com/user-attachments/assets/3b72b314-dc51-406f-892e-1f10f16a1e99)
![Image](https://github.com/user-attachments/assets/229e1aab-3b65-45d1-8993-0258157b04c8)

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.2` using version `1.75 (95)`

Using test plan mentioned in https://github.com/brave/brave-core/pull/26614#issue-2669460522

**`Test Case #1`**

* Ensured that loading `brave://ads-inernals` on fresh profile will not show any records on page.
* Ensured that conversion-url-pattern records are shown after viewing ads in results page using `search.brave.software`.
* Ensured that `Clear Ads Data` button is hidden when enabling rewards. 

default | staging search results | staging ad | brave://ads-internals after viewing ad | enabling rewards
---|---|---|---|---
<img width="200" alt="01" src="https://github.com/user-attachments/assets/85bb57b9-795e-44d4-908d-61f36d7e6df5"> | <img width="200" alt="02" src="https://github.com/user-attachments/assets/20f04383-a3da-4e92-a7ec-6bc376b944b9"> | <img width="200" alt="03" src="https://github.com/user-attachments/assets/1c03f06a-969f-4afc-8916-1663cacd75d3"> | <img width="200" alt="04" src="https://github.com/user-attachments/assets/e0c93cb6-a698-40a3-a541-9e101a9c1d74"> | <img width="200" alt="05" src="https://github.com/user-attachments/assets/db8ef61c-e6c0-4d0f-bcc0-b7fffdd9b269">

**`Test Case #2`**

* Ensured that brave://ads-internals can be loaded in Private tab.
* Ensured that tapping on `Clear Ads Data` button will not cause crash

<img width="300" alt="06" src="https://github.com/user-attachments/assets/2e0e8ff7-b6fb-46bf-bdca-8a759904f616">

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.75.86 Chromium: 132.0.6834.33 (Official Build) canary (64-bit) 
Revision	0e6fd65d499de588288c231ca0aba711876f5022
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

Using test plan mentioned in https://github.com/brave/brave-core/pull/26614#issue-2669460522

**`Test Case #1`**

* Ensured that loading `brave://ads-inernals` on fresh profile will not show any records on page.
* Ensured that conversion-url-pattern records are shown after viewing ads in results page using `search.brave.software`.
* Ensured that `Clear Ads Data` button is hidden when enabling rewards. 

default | staging search results | brave://ads-internals after viewing ad | enabling rewards | ads-internals with rewards enabled
---|---|---|---|---
<img width="200" alt="01" src="https://github.com/user-attachments/assets/a68b933f-2b4e-404b-82f3-0d65ae876a1e"> | <img width="200" alt="02" src="https://github.com/user-attachments/assets/bfc49dba-4610-4a29-8b4d-cdd2046591e7"> | <img width="200" alt="03" src="https://github.com/user-attachments/assets/57d768de-b541-4c14-b504-b0af363b5390"> | <img width="200" alt="04" src="https://github.com/user-attachments/assets/0e4243b0-acc1-4f4d-8299-e69ba7cf4e9e"> | <img width="200" alt="05" src="https://github.com/user-attachments/assets/ab6cb3d4-2f08-4c31-828c-9093a6ca4580">


**`Test Case #2`**

* Ensured that `brave://ads-internals` can be loaded in Private tab.
* Ensured that tapping on `Clear Ads Data` button will not cause crash.

**Comment by btlechowski** [comment]
Verified with

Brave | 1.75.164 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | befbba8d7568f8713d6f942f9a7350c59b57f20a
OS | Linux



#### Testcase 1 - search ad

<details>

Verified `brave://ads-internals` is empty on clean profile

![Image](https://github.com/user-attachments/assets/a23fe1b4-c652-46b5-9cc0-02497a2d7f40)

Verified conversion url is added to `brave://ads-internals` after clicking an ad

![Image](https://github.com/user-attachments/assets/b4cea77c-2b29-4a9f-9d40-46a1126b6b2f)

Verified data is cleared after clicking `Clear Ads Data`

![Image](https://github.com/user-attachments/assets/c0fcda32-e5ef-485b-94cb-bc7f02e2c643)

Verified `Clear Ads Data` is hidden after joining rewards

![Image](https://github.com/user-attachments/assets/97df7541-7b23-411b-a602-6ef56cd2bff6)

Verified conversion url is added to `brave://ads-internals` after viewing an ad in rewards state

![Image](https://github.com/user-attachments/assets/e32fd5f2-49c2-4132-9705-e2593e38f3c4)

</details>


#### Testcase 2

<details>

Verified clicking `Clear Ads Data` does not crash the browser

![Image](https://github.com/user-attachments/assets/c882659f-2047-4ceb-8e00-f46880f092d3)

Verified clicking `Clear Ads Data` does not crash the browser

![Image](https://github.com/user-attachments/assets/8591f106-0b3d-48dd-87b9-a915cf27a226)


</details>
