### ISSUE TITLE
Approval details and Estimated balance details are hidden in transaction simulation

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#40958]
### Description

Approval details and Estimated details are hidden in transaction simulation

### Steps to reproduce

1. Enable transaction simulation
2. Create a Send/Swap EVM transaction
3. Close and reopen panel
4. Shows pending transaction but Approval and Estimated balance section is not shown
5. Switch to Details view and go back to transaction, shows the details

### Actual result

https://github.com/user-attachments/assets/37da8e94-855f-4462-ac3a-f2c97ed7d731

### Expected result

Should not hide transaction details

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.70.107 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | ab3f504ca4a15c330f60a93d5e3773d780498980
OS | Windows 11 Version 23H2 (Build 22631.4112)

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @onyb @Douglashdaniel

**Comment by kjozwiak** [comment]
The above requires `1.71.92` or higher for `1.71.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.71.97 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | de99cbcb1aa0aa00877d356e4733f4e5481e89eb
OS | Windows 11 Version 23H2 (Build 22631.4169)

- Verified steps from issue description and [brave/brave-core#25611](https://github.com/brave/brave-core/pull/25611)
- Verified Transaction simulations details are not hidden when cycling through pending transactions

https://github.com/user-attachments/assets/3f30253d-310d-449d-96d6-35d1a95fcf81
