### ISSUE TITLE
[C129 PR build] - Profiles names are overlapped with Avatars 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#40964]
### Description

During CR 129 new installs or upgrades with multiple profiles, Profile names are overlapped with Avatars in the Profile manager

### Steps to reproduce

1. Install 1.71.73
2. launch Brave
3. create multiple profiles
4. open Profile manager

### Actual result

Profile names are overlapped with Avatars

<img width="876" alt="image" src="https://github.com/user-attachments/assets/18436862-b0cc-435e-aa9f-4935bf318b3b">

### Expected result

<img width="960" alt="image" src="https://github.com/user-attachments/assets/3dd00ad2-9d76-4d56-824c-cf3508ba093e">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.71.73 Chromium: 129.0.6668.31 (Official Build) nightly (64-bit)
-- | --
Revision | f6000c6537cef475d001df5d3674ae1fb9d8afd7
OS | Windows 11 Version 23H2 (Build 22631.4112)
```

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

@rebron @mkarolin 
cc: @brave/qa-team

**Comment by mkarolin** [comment]
cc: @fallaciousreasoning

**Comment by kjozwiak** [comment]
The above requires `1.70.113` or higher for `1.70.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.113 Chromium: 129.0.6668.42 (Official Build) (64-bit)
-- | --
Revision | e73406d8277b78a1d8f3f2f82bbc6babed537f7f
OS | Windows 11 Version 23H2 (Build 22631.4169)
```
Confirmed Profile names are not overlapped, and avatar alignment is shown as expected.
![image](https://github.com/user-attachments/assets/a5ffc8a9-237b-4227-8a1d-7225bd117043)
