### ISSUE TITLE
Brave should port a lite Antivirus into it

### ISSUE THREAD

**Issue by littleboy0k** [brave/brave-browser#4096]
Brave should consider putting a lite antivirus that will protect it if it is installed in a computer that doesn't have virus protection.

**Comment by Jeztical** [comment]
And have it take in more ram and cpu usage? No thanks.

**Comment by Blaxou** [comment]
Well there isn't much upsides in adding an antivirus I'd say, the only thing I could think of would check in virustotal if the file might be malicious or not, but running an antivirus isn't the goal of Brave or any browser ;)

**Comment by srirambv** [comment]
I feel Antivirus should be at a system level and not at browser level. Don't think we would work on this at any point of time. 

cc: @tomlowenthal  for any thoughts

**Comment by Blaxou** [comment]
@srirambv How about just querying VirusTotal for the file we just downloaded ? Would it overload the site or anything ?
