### ISSUE TITLE
[Brave News]: Potentially refresh old data, if its stale when switching back to the news tab

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#40960]
Currently, if you open a tab and leave it open for a long time Brave News will show stale data. We should refresh the feed if the data is old.

cc @LorenzoMinto should we do 1 hour here (our stale data timeout) or 3 hours (our feed refresh rate)

1. Open a tab
2. Swap to another
3. Wait <n> hours
4. Switch back

**Expected**
Feed is fresh

**Actual**
Feed is the same data as before

**Comment by fallaciousreasoning** [comment]
1 hour to regenerate the feed - the backend will refetch data every 3 hours

So:
Fresh feed every hour
Fresh data every 3 (unchanged)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.71.98 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | 453ddf665beda526b19af7aa60047a0e757b6a7a
OS | Windows 11 Version 23H2 (Build 22631.4249)
```

1. Installed 1.71.98
2. launched Brave
3. clicked `Turn on News` to enable news (at 12.16)
4. opened Tab 1 and articles show news updated as following 
5. Good House Keeping 24 hours ago
6. Wikihow:  2 hours ago
7. Business Insider:  2 hours 
8. Polygon: 4 hours 
9. opened tab 2 and and it shows same 
10. Waited for an hour (12:16 pm -->1:22pm)

- Confirmed times for the articles on Tab 2 got updated 
- Confirmed Tab 1 page is refreshed, and new article cards shown

Tab 1  
----  
example | example | example 
----- | ---- | -----
<img width="953" alt="image" src="https://github.com/user-attachments/assets/df82face-7a40-4c66-b821-bb6883d6de82">|![image](https://github.com/user-attachments/assets/c6a48f5d-3d64-4793-8ddb-277dee95eecb)|![image](https://github.com/user-attachments/assets/429edf80-be18-4d70-96bb-81f809669048)

Tab 2
-----
example | example 
------ | -----
![image](https://github.com/user-attachments/assets/77bb23ad-c810-4bb9-8054-fc3b3f8818d2)|![image](https://github.com/user-attachments/assets/dc26b9da-c34c-424f-a9f3-bd74aa097505)
