### ISSUE TITLE
Improve iOS Shields standard mode logic

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#40967]
https://github.com/brave/internal/issues/1188

**Comment by kjozwiak** [comment]
Verification **PASSED** using `iPhone 11` running `iOS 17.6.1` using the following build(s):

```
Brave | 1.71.80 Chromium: 128.0.6613.120 (Official Build) nightly (64-bit) 
Revision | 4dea6843510d...
OS | iOS
```

Verification notes can be found via https://github.com/brave/internal/issues/1188#issuecomment-2342611739.

**Comment by kjozwiak** [comment]
The above requires `1.69.170` or higher for `1.69.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.6.1
- iPad Air / iPadOS 16.7.2
Brave build: 1.69 (170)
BraveCore: 1.69.170 (128.0.6613.138)
```
---------------------------

Verification notes can be found via https://github.com/brave/internal/issues/1188#issuecomment-2344831684 and https://github.com/brave/internal/issues/1188#issuecomment-2344977815.
