### ISSUE TITLE
Upgrade from Chromium 128.0.6613.120/128.0.6613.127 to Chromium 128.0.6613.138

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#40972]
### Minor Chromium bump

https://chromium.googlesource.com/chromium/src/+log/128.0.6613.120..128.0.6613.138?pretty=fuller&n=10000

### QA tests

- Check branding items
- Check for version bump

### Minor Chromium bump

- No specific code changes in Brave (only line number changes in patches)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit)
-- | --
Revision | 6918a99aa67f8b2c8cfdc9a44e6ad4f9be6c5be9
OS | Windows 10 Version 22H2 (Build 19045.4780)
```
![image](https://github.com/user-attachments/assets/29ee9d23-501a-4b2e-9c0d-82e2c8c4a383)

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.69.168 Chromium: 128.0.6613.138 (Official Build) (x86_64)
-- | --
Revision | 6918a99aa67f8b2c8cfdc9a44e6ad4f9be6c5be9
OS | macOS Version 13.6.9 (Build 22G830)
```

<img width="1204" alt="Screenshot 2024-09-11 at 7 49 38 AM" src="https://github.com/user-attachments/assets/c35d3bad-bcac-4ed1-971a-5e61d912426b">

**Comment by LaurenWags** [comment]
Verified with

```
Brave	1.69.168 Chromium: 128.0.6613.138 (Official Build) (arm64) 
Revision	6918a99aa67f8b2c8cfdc9a44e6ad4f9be6c5be9
OS	macOS Version 15.0 (Build 24A335)
```

![Screenshot 2024-09-11 at 9 29 45 AM](https://github.com/user-attachments/assets/75ce74cb-12b7-4b22-97af-45b6c1101aea)

**Comment by btlechowski** [comment]
Verified with

Brave | 1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit)
-- | --
Revision | 6918a99aa67f8b2c8cfdc9a44e6ad4f9be6c5be9
OS | Linux

![image](https://github.com/user-attachments/assets/cdc556ef-72e5-4f1c-b5e9-70597ca74fa6)

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.6.1
- iPad Air / iPadOS 16.7.2
Brave build: 1.69 (168)
BraveCore: 1.69.168 (128.0.6613.138)
```
---------------------------

`iPhone 14`

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/0f641b8f-e1ee-415a-9b63-1f31a7b588fe) | ![2](https://github.com/user-attachments/assets/f91dc632-18d5-4ed5-b478-2cb728ef5501) |

`iPad Air`

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/375c1f36-b7dd-4290-8c31-0687f46b57cf) | ![2](https://github.com/user-attachments/assets/db3ce9d5-2588-4020-be4b-f4c6e98528ea) |
