### ISSUE TITLE
Print preview on google doc failed to extract content sometimes

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#40970]
Failed to extract:
![image](https://github.com/user-attachments/assets/a8bcf4ba-bc91-4f28-b308-87023b3fb8ab)

Normal scenario:
![image](https://github.com/user-attachments/assets/4b72fd7c-70a7-46ca-951e-a295c1be75de)

https://bravesoftware.slack.com/archives/C05NDQP03AQ/p1725048835025339?thread_ts=1724683222.911259&cid=C05NDQP03AQ

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.72.96 Chromium: 131.0.6778.24 (Official Build) beta (64-bit)
-- | --
Revision | 10f472615a5ea2cccb71ffc48639efbaef71b801
OS | Windows 10 Version 22H2 (Build 19045.5011)
```
- Verified the test plan from https://github.com/brave/brave-core/pull/25513
- Reproduced the issue on `1.71.121 Chromium: 130.0.6723.91 `
![Image](https://github.com/user-attachments/assets/b65d2096-91b7-4dd3-87f7-7486cb474b95)
- Verified the test plan on `1.72.96 Chromium: 131.0.6778.24` and ensured that page content is extracted via summarize page as expected

Example | Example | Example
-----------|----------|----------
![Image](https://github.com/user-attachments/assets/e413202c-8272-4176-9c4d-40000b4b2039) | ![Image](https://github.com/user-attachments/assets/ea95745c-8ebd-4631-939b-c149e535b1a9) | ![Image](https://github.com/user-attachments/assets/85acd18a-c5d9-4ba0-b5fa-5060018d387d)

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```

Brave | 1.73.88 Chromium: 131.0.6778.39 (Official Build) (arm64)
-- | --
Revision | e0a230f2aab41bbd7935065107eb039f90f0ec70
OS | macOS Version 12.5 (Build 21G72)


```
