### ISSUE TITLE
A white line is shown on vertical tab strip in dark mode 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#40971]
### Description

A white line on vertical tab strip is shown in dark mode on my Win 11 x64 machine.  However, I couldn't reproduce on Win 11 arm64 machine.  This was reproduced 1.68.128, 1.69.162 & 1.70.107.  The white is shown only vertical tab view mode Not in Horizontal view.

### Steps to reproduce

1. Install 1.70.107
2. launch Brave
3. open few tabs
4. enable vertical tab view via Use vertical tabs from the context menu of a tab

### Actual result

A white line is shown

dark mode | light mode
![image](https://github.com/user-attachments/assets/2e3893df-de4b-4e64-b4d7-64a4faa10147)
![image](https://github.com/user-attachments/assets/63d02146-1fd0-4087-98f4-f976de1092fb)

### Expected result

![image](https://github.com/user-attachments/assets/b2892d88-289a-4645-96ad-309d9ae62ace)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.70.107 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | ab3f504ca4a15c330f60a93d5e3773d780498980
OS | Windows 11 Version 23H2 (Build 22631.4112)

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

@kjozwiak @bsclifton - could you please try and reproduce this issue of white line in vertical tab strip in dark mode on your Win 11 x64 machines please?  Could not reproduce in Win 11 arm64.  @rebron couldn't reproduce in his Win 11 x64 machine.

**Comment by kjozwiak** [comment]
I'm noticing a few discrepancies on my main `Nightly` profile as well. For example, with the `Light` theme, there's no separator via the vertical tabs so it blends in with websites that use a light background. It's also an issue at the top of the window where there's missing separators and the `omnibox`, `Bookmark toolbar` are blended together. It's hard to tell where the website WebView starts.

**`Example`** | **`Example`**
---------------|-------------------
![image](https://github.com/user-attachments/assets/faac0f31-028b-406c-b54d-52e5e0214bac) | ![image](https://github.com/user-attachments/assets/eaed5054-3da1-4544-8469-a86b10553c16)

Regarding the white line appearing via the vertical tabs in `Dark` mode, I'm not seeing that issue with my current profile

![image](https://github.com/user-attachments/assets/7028ee67-cb32-4424-9718-07297cde7ce4)

**Comment by rebron** [comment]
cc: @simonhong @fallaciousreasoning This was happening for @MadhaviSeelam on 1.69.x release dark theme/vertical tabs. I couldn't reproduce on either Windows or macOS and @kjozwiak couldn't either. 

Related: https://github.com/brave/brave-browser/issues/41024

**Comment by fallaciousreasoning** [comment]
Interesting - @kjozwiak I think @rebron found the reason you weren't getting borders - we deliberately remove them as part of the brave://flags/#brave-web-view-rounded-corners flag

Maybe we don't want to flip that flag in release just yet?

**Comment by fallaciousreasoning** [comment]
I managed to repro on latest Linux:
1. Disable the brave://flags/#brave-web-view-rounded-corners flag
2. Install https://chromewebstore.google.com/detail/just-black/aghfnjkcakhmadgdomlmlhhaocbkloab theme
3. Change the color scheme to dark

**Comment by kjozwiak** [comment]
The above requires `1.71.91` or higher for `1.71.x` verification 👍
