### ISSUE TITLE
CR129 - Redundant settings `Use secure DNS` and `Select DNS provider` under brave://settings/security

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#40989]
### Description

Found while testing https://github.com/brave/brave-browser/issues/40204

CR129 - Redundant settings `Use secure DNS` and `Select DNS provider` under brave://settings/security

### Steps to reproduce

1. NA

### Actual result

![image](https://github.com/user-attachments/assets/11fbf531-7bf0-40ea-b742-9659490ce71d)

### Expected result

There should be one set of  `Use secure DNS` and `Select DNS provider` under brave://settings/security

![image](https://github.com/user-attachments/assets/638d6c14-ce74-46cd-8b41-df93cc9cf521)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.71.81 Chromium: 129.0.6668.31 (Official Build) nightly (64-bit)
-- | --
Revision | 33ed75506c3a0d5a964e5ca61494d6144c52fd7d
OS | Windows 10 Version 22H2 (Build 19045.4780)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @rebron @mkarolin @simonhong

**Comment by mkarolin** [comment]
I can see the same on Chrome Beta (129.0.6668.29). Filed upstream issue https://issues.chromium.org/issues/365884462

**Comment by kjozwiak** [comment]
Added `QA/Bocked` as this was fixed via https://github.com/brave/brave-core/pull/25521 but still needs an uplift. @mkarolin mentioned we might get the above via one of the `C129` but we'll uplift just in case. Once https://github.com/brave/brave-core/pull/25521 has been uplifted, we'll remove the `QA/Blocked` 👍

**Comment by kjozwiak** [comment]
The above requires `1.70.113` or higher for `1.70.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.113 Chromium: 129.0.6668.42 (Official Build) (64-bit)
-- | --
Revision | e73406d8277b78a1d8f3f2f82bbc6babed537f7f
OS | Windows 11 Version 23H2 (Build 22631.4169)
```

Confirmed single setting of `Use secure DNS` and `Select DNS provider` under `brave://settings/security` is shown


![image](https://github.com/user-attachments/assets/5feb4cd2-5ead-4ec8-a613-f078a12be59f)
