### ISSUE TITLE
[Settings]: Upstream has updated the names of a lot of their security/privacy icons

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#40998]
This means that a bunch of the icons we show in brave://settings/content are wrong

Expected
![image](https://github.com/user-attachments/assets/4398167c-6482-4426-88dc-cdb1d61b7f70)

Actual:
![image](https://github.com/user-attachments/assets/f17c2dd2-b8bd-4a74-9095-5e2fb65d1b45)

# Test Plan
1. Icons should match expected screenshot
2. Off icons should not be missing (if you go into the setting and there is an off option) and should match the style of the on icon

**Comment by MadhaviSeelam** [comment]
Verification In progress using
```
Brave | 1.72.85 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 2c872aa4d2694bc73ec58e3b14538a4008a6381e
OS | Windows 11 Version 23H2 (Build 22631.4391)
```

Verified the issue from the testplan https://github.com/brave/brave-browser/issues/40998#issue-2519868011

#### Confirmed security/privacy icons match to the expected results screenshot 


1.71.x | 1.72.x
----- | -----
![Image](https://github.com/user-attachments/assets/21718e6b-d8cf-486a-8036-4d1a5e1abf4d)|![Image](https://github.com/user-attachments/assets/6e2a5522-8b9c-4762-9fe2-4d87159ae25a)
![Image](https://github.com/user-attachments/assets/73ce6a53-9d8f-4617-8a45-60ea73ce338c)|![Image](https://github.com/user-attachments/assets/ec9963b1-4c1a-4072-9b0e-2fc087da62f1)
![Image](https://github.com/user-attachments/assets/ca357fb1-d74a-4616-aa31-d7b5be763b76)|![Image](https://github.com/user-attachments/assets/e873ca8d-39af-4845-aff3-fafe664549a4)
![Image](https://github.com/user-attachments/assets/d1190f47-d81e-49ca-b99f-e8287dcd73a2)|![Image](https://github.com/user-attachments/assets/90cccbd9-50ed-4aca-a640-81319088be83)
![Image](https://github.com/user-attachments/assets/dc4c396e-fdea-455d-84a1-b48d129c2efe)|![Image](https://github.com/user-attachments/assets/8cd43170-21bc-43a1-9b2f-c510f97d7d23)

Dark theme

example | example | example | example | example 
----- | ----- | ------ | ------ | -----
![Image](https://github.com/user-attachments/assets/e3397639-3a65-4714-a2ee-55073be5e2bc)|![Image](https://github.com/user-attachments/assets/290b832f-a6ac-498f-aa08-0b2d3281461b)|![Image](https://github.com/user-attachments/assets/929f99db-84b8-4919-acb6-6ecb96b41f04)|![Image](https://github.com/user-attachments/assets/9cb4a383-1963-436c-b7dc-206f2cea11d6)|![Image](https://github.com/user-attachments/assets/35db0c0b-cd6f-484b-ac83-165c55465524)
