### ISSUE TITLE
Unable to log into transferwise.com

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#4099]
## Description 
Users are unable to log into transferwire.com with shields up.

## Steps to Reproduce
1. Navigate to transferwire.com
2. Attempt to login

## Actual result:
An error is shown (TBD)

## Expected result:
User is authenticated.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
TBD

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? TBD

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome?  No

### Additional Information
Originally reported on Twitter: https://twitter.com/hknerdr/status/1117364838378897409

![image](https://user-images.githubusercontent.com/815158/56094076-9554a000-5e95-11e9-8e44-1f5adaae7811.png)

**Comment by ryanbr** [comment]
Seems fine here, I couldn't login if I blocked all cookies. So switching to 3-party cookies should help? can you confirm?

**Comment by ryanbr** [comment]
@jonathansampson Is the issue still occurring if you change the cookie settings?

**Comment by ryanbr** [comment]
Seems to be okay. reaching out https://twitter.com/fanboynz/status/1238658939597647872

**Comment by bsclifton** [comment]
Closing as user reports it works fine now 😄
