### ISSUE TITLE
Renderer processes crash on macOS when an update is pending and a new instance of Brave is launched

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#40992]
### Description

From time to time browser stops works, all renderer process crash immediately . It's perfectly match the time that a new update is ready.
crash-ids:
[846c1800-24ac-8e0c-0000-000000000000](https://brave.sp.backtrace.io/p/brave/debug?filters=JTVCJTVCJTIyX3J4aWQlMjIlMkMlMjJlcXVhbCUyMiUyQyUyMjg0NmMxODAwLTI0YWMtOGUwYy0wMDAwLTAwMDAwMDAwMDAwMCUyMiU1RCU1RA%3D%3D&debug=(%22554756e%22,0,1))
```
[ 0 ] base::apple::(anonymous namespace)::BundleFromPath(base::FilePath const&) ( immediate_crash.h:176 )
[ 1 ] base::apple::SetOverrideFrameworkBundlePath(base::FilePath const&) ( bundle_locations.mm:91 )
[ 2 ] base::apple::(anonymous namespace)::BundleFromPath(base::FilePath const&) ( bundle_locations.mm:69 )
[ 3 ] base::apple::SetOverrideFrameworkBundlePath(base::FilePath const&) ( bundle_locations.mm:91 )
[ 4 ] SetUpBundleOverrides() ( chrome_main_mac.mm:25 )
[ 5 ] ChromeMain ( chrome_main.cc:185 )
[ 6 ] main ( chrome_exe_main_mac.cc:217 )
```

The details show that there that the old framework and resources were removed, but the browser is still trying to use it.    
[ls.txt](https://github.com/user-attachments/files/16962671/ls.txt)
[open_files_and_ports.txt](https://github.com/user-attachments/files/16962672/open_files_and_ports.txt)

Note, that it's an old issue and it's likely isn't connected with O4 integration.

### Steps to reproduce

1.  Wait for the update is ready, don't relaunch the browser.

### Actual result

Blank pages on every tab, all the renderer processes crash.
Browser works well after the restart.

### Expected result

Browser works normally.

### Reproduces how often

Intermittent issue

### Brave version (brave://version info)

1.71.73 Chromium: 128.0.6613.120 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [x] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by atuchin-m** [comment]
The screencast:
https://github.com/user-attachments/assets/5ca41c38-a076-46ed-8689-9cf86a90cc5d

**Comment by mherrmann** [comment]
@atuchin-m do you happen to have any more specific steps for reproducing? I just installed an old version of Nightly, left it running for 12 hours, then advanced the system clock by another 12 hours. I also got the green "Update" button in the top right corner. But no render process crashes. When I finally restarted, it updated to the latest version as expected.

**Comment by atuchin-m** [comment]
@mherrmann it happens usually one of 5-10 updates, no particular steps.

**Comment by mherrmann** [comment]
Summarizing a hypothesis @atuchin-m and I discussed a few weeks ago:

Sparkle installs a downloaded version that is ready to be installed before Brave launches. Normally, this only happens when no instance of Brave is running.

But there are ways to launch a second instance of Brave. For example, by supplying a `--user-data-dir`.

The hypothesis is that the crashes happen when an update is waiting to be installed, and the users manages to launch a second instance of Brave. In this case, Sparkle applies the update and removes the old files. But the first running instance, eg. its renderer processes, still need it. So they crash.
