### ISSUE TITLE
[Brave News]: Add it_IT and es_AR to list of enabled locales for News

### ISSUE THREAD

**Issue by LorenzoMinto** [brave/brave-browser#40996]
Add `it_IT` and `es_AR` to list of enable locales. Check if `en_UK` is correct, on the server we generate for the `en_GB` locale.

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7
Brave build: 1.71 (116)
BraveCore: 1.71.116 (130.0.6723.58)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/40996#issue-2519771088 and https://github.com/brave/brave-core/pull/25525#issue-2519870325
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Brave News` opt-in is shown when the device locale is set to `es_AR`.
- Verified that `Brave News` opt-in is shown when the device locale is set to `it_IT`.
- Verified that `Brave News` opt-in is shown when the device locale is set to `en_UK`.

---------------------------

|`es_AR`|`it_IT`|`en_UK`|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/f49f85a3-4118-4d69-93b0-5cb25bfb669a) | ![2](https://github.com/user-attachments/assets/37c0b33d-8225-4395-aa81-06c91115f948) | ![3](https://github.com/user-attachments/assets/334368a2-c2af-4999-9e93-904456358c9f) |
| ![1](https://github.com/user-attachments/assets/091730d6-d076-4bb3-a932-f162a78531db) | ![2](https://github.com/user-attachments/assets/f3362858-805a-4d7c-9a1b-766d61ea9e99) | ![3](https://github.com/user-attachments/assets/1dc76f95-9aed-4c1c-8871-8f4d93c8d327) |
| ![1](https://github.com/user-attachments/assets/fbbe9c6d-f062-4f62-942b-07675ec5d064) | ![2](https://github.com/user-attachments/assets/9ae6d0c4-c393-4de9-a7bf-5202c3caf1d0) | ![3](https://github.com/user-attachments/assets/14444f55-3ab2-4ca7-8d7f-8a3f123d45c3) |
| ![1](https://github.com/user-attachments/assets/df1b0cfd-f4e3-472b-a0d7-55c02d2b6e56) | ![2](https://github.com/user-attachments/assets/dde1e933-9d72-4f83-9537-59d6386319d0) | ![3](https://github.com/user-attachments/assets/1c4e3ca4-2ebc-4693-b3d0-a5c377e968b7) |
| ![1](https://github.com/user-attachments/assets/af4db046-7416-49ee-8467-55bd5c361f85) | ![2](https://github.com/user-attachments/assets/8a4588bb-e518-4e18-8430-26ac48570d61) | ![3](https://github.com/user-attachments/assets/cc1876c5-8125-42c6-8102-0b3edf001b09) |
