### ISSUE TITLE
[ads] Followup to "Send HTTP response status for landed events as part of the confirmation token redemption" #36752

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#40991]
### Description

Change from a BOOLEAN to:

1xx: Informational responses

2xx: Success

3xx: Redirection

400: Bad Request
401: Unauthorized
403: Forbidden
404: Not Found
408: Request Timeout
429: Too Many Requests
451: Unavailable For Legal Reasons
4xx: Any other client error not listed

500: Internal Server Error
502: Bad Gateway
503: Service Unavailable
504: Gateway Timeout
5xx: Any other server error not listed

**Comment by btlechowski** [comment]
Verification passed on 1.74.20 on iPhone 13 Pro Max (iOS 17.7)

<details>



</details>
