### ISSUE TITLE
CR 129 - Site and shield settings icon is inherited from chrome

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#40990]
### Description

Found while testing https://github.com/brave/brave-browser/issues/40204
CR 129 - Site and shield settings icon is inherited from chrome

### Steps to reproduce

1. NA

### Actual result

![image](https://github.com/user-attachments/assets/b2e7401e-d785-47d6-8efb-72022ee0828b)

### Expected result

![image](https://github.com/user-attachments/assets/99461203-346c-4d04-9c1b-7b5e24a9fbdc)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.71.81 Chromium: 129.0.6668.31 (Official Build) nightly (64-bit)
-- | --
Revision | 33ed75506c3a0d5a964e5ca61494d6144c52fd7d
OS | Windows 10 Version 22H2 (Build 19045.4780)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @rebron @mkarolin @simonhong

**Comment by simonhong** [comment]
That icon is `privacy:page-info` from below in https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/resources/settings/privacy_page/privacy_page.html

but can't find which icon file is used for that icon. @fallaciousreasoning can you give advice?
```
        <cr-link-row id="permissionsLinkRow" start-icon="privacy:page-info"
            class="hr" label="$i18n{siteSettings}"
            sub-label="$i18n{permissionsPageDescription}"
            on-click="onPermissionsPageClick_"
            role-description="$i18n{subpageArrowRoleDescription}"></cr-link-row>
```

**Comment by fallaciousreasoning** [comment]
Nice find @GeetaSarvadnya!

**Comment by kjozwiak** [comment]
The above requires `1.70.111` or higher for `1.70.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.70.113 Chromium: 129.0.6668.42 (Official Build) (64-bit)
-- | --
Revision | e73406d8277b78a1d8f3f2f82bbc6babed537f7f
OS | Windows 11 Version 23H2 (Build 22631.4169)
```


Confirmed correct `Site and shield settings icon is shown 

![Screenshot 2024-09-16 131412](https://github.com/user-attachments/assets/dfa5173c-2872-47bf-b46e-62ebc7dab99e)
