### ISSUE TITLE
[Android] Update Leo Paywalls (Annual Subscription + Trial Support)

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#41008]
### Description

Update the Leo paywalls with annual subscription and trial support.

Figma:
https://www.figma.com/design/Kl4ISaYCPaWcIsWl5c36WA/%E2%9C%85-Leo-%5BDONE%5D?node-id=336-35701&node-type=canvas&t=W1UuwC7qQGfwN4aO-0

**Comment by kjozwiak** [comment]
The above requires `1.73.86` or higher for `1.73.x` verification 👍

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 AP41.240925.009 release-keys
Brave build: 1.73.87 
Chromium: 131.0.6778.39 (Official Build) (64-bit) 
```
---------------------------
<details>
<summary> Yearly subscription </summary>

**STEPS:**
1. Launch Brave
2. Hamburger menu > Settings
3. Leo > Go Premium > *Verify*
4. Select `One year` > Try 7 days free > *Verify*

**ACTUAL RESULTS:**
- Verified that the `Leo` paywall has 2 subscription options `One year` and `Monthly`.
- Verified that the `7-day free trial` is available for the account that didn't purchase a `Leo` subscription previously and is purchasing a `One year` subscription now.
- Verified that the `yearly` Leo subscription can be purchased successfully.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/0dd05f94-2ca0-4573-ba83-abd9af30b565) | ![2](https://github.com/user-attachments/assets/13acbf13-7c2e-490a-a084-c318991ad9a3) | ![3](https://github.com/user-attachments/assets/dd4d074e-c9ff-4ab1-9c92-f4c939b2167a) |
| ![1](https://github.com/user-attachments/assets/c706e5e8-2287-4be6-aa30-22ffe212200f) | ![2](https://github.com/user-attachments/assets/bd33f200-5784-4332-ac3b-9ceb34daf0a4) | ![3](https://github.com/user-attachments/assets/a2b8d957-d08c-4be6-b31c-fd171b9f6cae) |
</details>

**Comment by hffvld** [comment]
Verified a `real` subscription purchase with `7-day free trial` on `Pixel 8a` using version(s):
```
Device/OS: Pixel 8a / akita-user 15 AP3A.241105.007 release-keys
Brave build: 1.73.89 
Chromium: 131.0.6778.69 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Launch Brave
2. Hamburger menu > Settings
3. Leo > Go Premium > *Verify*
4. Select `One year` > Try 7 days free > *Verify*

**ACTUAL RESULTS:**
- Verified that the `Leo` paywall has 2 subscription options `One year` and `Monthly`.
- Verified that the `7-day free trial` is available for the account that didn't purchase a `Leo` subscription previously and is purchasing a `One year` subscription now.
- Verified that the `yearly` Leo subscription can be purchased successfully.
- Verified that canceling subscription while on trial works as expected.

---------------------------

https://github.com/user-attachments/assets/0e0524a2-0170-4b6f-b222-2535ba8c0a62
