### ISSUE TITLE
Add 1.69 translations 

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#41007]

**Comment by kjozwiak** [comment]
The above requires `1.69.170` or higher for `1.69.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.5.1` using version `1.69 (170)`

- Ensured existing strings in NTP, settings, Shields and context menus have not regressed for `German`, `French` and `Russian` locales. 
- Ensured new strings are translated (VPN Advanced Server Selection).

#### German

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_7307](https://github.com/user-attachments/assets/7a3fb538-d5e0-4490-a930-c1692052c1d2) | ![IMG_7308](https://github.com/user-attachments/assets/064f01f6-f892-4f45-bddb-9ffc276d30d3) | ![IMG_7309](https://github.com/user-attachments/assets/90f88c9b-3ccf-4297-9982-3b6e71e70fda) | ![IMG_7310](https://github.com/user-attachments/assets/9120c63d-5eb7-4679-a28e-dc026ea1907c) | ![IMG_7311](https://github.com/user-attachments/assets/0c096fd3-d787-4edc-bd60-4f2d8e74f22d) | ![IMG_7312](https://github.com/user-attachments/assets/7ec5407d-409f-48ff-9a76-9a6e6bf005e5)

#### French

Example | Example | Example | Example
-|-|-|-
![IMG_7326](https://github.com/user-attachments/assets/8e61a80c-4890-474e-a180-592b4b649c1e) | ![IMG_7327](https://github.com/user-attachments/assets/ebd93faa-e6cf-437a-a760-152a0258af08) | ![IMG_7328](https://github.com/user-attachments/assets/3632d81e-e393-4848-a124-3b2b032e8759) | ![IMG_7329](https://github.com/user-attachments/assets/0af4b6b9-bfd0-41c5-b907-859e7765a4f2) 
![IMG_7330](https://github.com/user-attachments/assets/b5cad2ff-dfa8-4571-a045-0193dfc39166) | ![IMG_7331](https://github.com/user-attachments/assets/bb3c4a99-be44-4f6c-8d10-d84fd57886b6) | ![IMG_7332](https://github.com/user-attachments/assets/b78e9586-babc-49d4-affb-7eb14a040da2) | ![IMG_7333](https://github.com/user-attachments/assets/85af9bf8-016c-4c2e-8bbb-d2d70c538cd4)

#### Russian

Example | Example | Example | Example | Example | Example | Example
-|-|-|-|-|-|-
![IMG_7316](https://github.com/user-attachments/assets/43a72c93-d2e9-4d45-998b-97f8c46894a2) | ![IMG_7317](https://github.com/user-attachments/assets/e23cefc7-203d-4ab6-96e2-473418a1ea52) | ![IMG_7318](https://github.com/user-attachments/assets/00fbf333-e630-4780-a0cd-552f279d7b1a) | ![IMG_7319](https://github.com/user-attachments/assets/5cdb3b4e-f086-4c50-967d-1e205d267aff) | ![IMG_7320](https://github.com/user-attachments/assets/6b028a6e-e257-4be5-912f-1ab510bd754b) | ![IMG_7321](https://github.com/user-attachments/assets/1d312bec-a7e9-4206-b8a9-c4b6c5580608) | ![IMG_7325](https://github.com/user-attachments/assets/8dcc88ca-1c28-4abd-98e7-29839c4c17dc)
