### ISSUE TITLE
Install VPN Profile is incorrectly shown after a failed App Store subscription restore

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#41012]
### Description

If you attempt to enable VPN from the 3-dot more menu without having a subscription the VPN purchase screen will appear. If you attempt to restore your subscription on this page but and it fails, it will still show the install VPN profile screen which will then hang indefinitely.

https://github.com/user-attachments/assets/43af9faa-ac51-4040-9e81-47a47c24ee44

### Steps to reproduce

Requirement: No active VPN subscription on your account
1. Open the menu (•••) and tap the VPN or visit the VPN product purchase page in settings
2. Tap "Restore" and wait for it to fail

### Actual result

The "Install VPN Profile" screen appears after the restoration fails

### Expected result

Should not see the install profile screen unless you successfully restore your sub

### Reproduces how often

Easily reproduced

### Brave version

Tested on 1.69+ but likely an issue in older builds

### Device/iOS version

Tested on iPhone 15, iOS 18.0 RC

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.71.120` or higher for `1.71.x` verification 👍 @Uni-verse @hffvld you'll need a new account that has never completed a IAP to verify the above. I have an `iPad` in the above state so I can help verify the above as well.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 18.1` using the following build(s):

```
Brave | 1.71.120 Chromium: 130.0.6723.70 (Official Build) stable (64-bit)
--- | ---
Revision | 8e82b3c0648d52ab3e09f3b75c46fc807782415c
OS | iOS
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/41012#issue-2520687063, ensured that clicking on `Restore` with a brand new account didn't let the user create a VPN profile even though a VPN premium purchase has never been made as per the following:

https://github.com/user-attachments/assets/d92556a6-d1f5-4c11-b34d-633f58203d0f
