### ISSUE TITLE
[ads] Deselecting Like or Dislike in 30-day history sends a confirmation

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#41027]
### Description

Follow up to https://github.com/brave/brave-browser/issues/40012, https://github.com/brave/brave-browser/issues/40082

Not reproducible on 1.69.x

### Steps to reproduce

1. Enable rewards
2. View an ad
3. Open `brave://rewards`
4. Open 30-day history
5. Click `Like`
6. Click `Like`

Important: Reproducible for `Like`, `Dislike`, `Mark as inappropriate` and `Save`

### Actual result

Deselecting Like or Dislike in 30-day history sends a confirmation

### Expected result

Deselecting Like or Dislike in 30-day history does not send a confirmation

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.70.109 Chromium: 128.0.6613.138 (Official Build) beta (64-bit)
-- | --
Revision | fec4422ae56f4d9680c71a3c1de60b9a8e5ef32f
OS | Linux

cc @aseren @iambrianfung @tmancey

**Comment by tmancey** [comment]
@btlechowski as discussed this works as expected in 1.71.x, so we will let the fix ride the trains for the next release. Great catch. Thanks
