### ISSUE TITLE
[ads] Follow up to #40507: Add NTP media type p3a metrics

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#41026]
### Description

Follow up to #40507. When NTT is disabled through `brave://rewards`, p3a `Brave.NTP.SponsoredMediaType` is not changed.

Note: changing `Brave.NTP.SponsoredMediaType` through NTP works as expected

### Steps to reproduce

1. Enable rewards
2. Open `brave://rewards`
3. Turn off `NTT`
4. Open `brave://local-host` and search for `SponsoredMediaType`

### Actual result

Brave.NTP.SponsoredMediaType = 1

![image](https://github.com/user-attachments/assets/acce9468-06cd-4c3e-8473-d53a3a17d3d5)

### Expected result

Brave.NTP.SponsoredMediaType = 0

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.70.109 Chromium: 128.0.6613.138 (Official Build) beta (64-bit)
-- | --
Revision | fec4422ae56f4d9680c71a3c1de60b9a8e5ef32f
OS | Linux

cc @tmancey @aseren @iambrianfung

**Comment by btlechowski** [comment]
Reproduced on Android: Brave v1.70.114 on Lenovo TB-8506FS (Android 11.0)

![image](https://github.com/user-attachments/assets/2dd46152-59d0-49e5-98bf-2b205585875b)|![image](https://github.com/user-attachments/assets/1d913701-600e-494a-a8a7-d040c00be254)
--|--

**Comment by LaurenWags** [comment]
Requires 1.71.103 or higher for verification 👍🏻

**Comment by btlechowski** [comment]
Verified on

Brave | 1.71.105 Chromium: 129.0.6668.89 (Official Build) beta (64-bit)
-- | --
Revision | f69ba167992437799f1dbcce81e90ba501a3d63e
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/25558

### Test case 1

<details>

Clean install

![image](https://github.com/user-attachments/assets/7b89800c-1f09-409f-827a-00f723c492d2)|![image](https://github.com/user-attachments/assets/62fc6732-69aa-4a31-b196-1bc810a6d119)
--|--

Disabled Background images

![image](https://github.com/user-attachments/assets/8544b1cd-6f61-4932-8f3a-3150fe479543)|![image](https://github.com/user-attachments/assets/fb5b77ff-5850-4e94-82f8-dc50b6fecee5)
--|--

Enabled Background images

![image](https://github.com/user-attachments/assets/4ac9bc8f-d149-4868-b84b-6f65e8ea2261)|![image](https://github.com/user-attachments/assets/6d0a64de-b262-4162-a526-e47444a170bd)
--|--


</details>



### Test case 2

<details>

Clean install

![image](https://github.com/user-attachments/assets/7b89800c-1f09-409f-827a-00f723c492d2)|![image](https://github.com/user-attachments/assets/62fc6732-69aa-4a31-b196-1bc810a6d119)
--|--

Disabled NTT

![image](https://github.com/user-attachments/assets/af937c62-9526-4728-85b0-a197bf6376c6)|![image](https://github.com/user-attachments/assets/ce4056ff-19dd-447a-8490-bd87a09df5d4)
--|--

Enabled NTT
![image](https://github.com/user-attachments/assets/c6b03103-cecb-48a5-bff9-b0dd86cdb227)|![image](https://github.com/user-attachments/assets/c731c74d-efaa-43b3-bf82-2fcdcc0e8339)
--|--



</details>



### Test case 3

<details>

After joining rewards:

![image](https://github.com/user-attachments/assets/4e5dee2a-9f23-4b5c-8b4c-e7df1dfb638b)|![image](https://github.com/user-attachments/assets/8be0b35b-d3e0-4f79-95e4-637ab4e95cc8)|![image](https://github.com/user-attachments/assets/e418c447-4e72-492e-957c-1eb55dea89aa)
--|--|--

Disabled NTT from brave://rewards

![image](https://github.com/user-attachments/assets/34661686-8dd4-41b2-a4b8-5f8d43f241a5)|![image](https://github.com/user-attachments/assets/ae061db0-61e1-4030-b78c-68a111f4652d)|![image](https://github.com/user-attachments/assets/72c2e546-b047-45e5-99a6-ca0e7f9e15f7)
--|--|--

Enabled NTT from brave://rewards

![image](https://github.com/user-attachments/assets/9378f4aa-73d8-4f0f-aed0-99b897de8aa2)|![image](https://github.com/user-attachments/assets/c90c09ae-e65c-4303-82cd-744d9f9283a0)|![image](https://github.com/user-attachments/assets/e41772bd-c2c8-4675-b2ab-75929a9c50e4)
--|--|--




</details>

**Comment by btlechowski** [comment]
Verification passed on Brave v1.71.114 on Lenovo TB-8506FS (Android 11.0)

Verified test plan from https://github.com/brave/brave-core/pull/25558

### Test case 1

<details>

Clean install

![Image](https://github.com/user-attachments/assets/6dd6feeb-2aed-4bb1-a8a7-5e72ec2a6b14)|![Image](https://github.com/user-attachments/assets/98c3e3e7-8b16-4a68-a11e-ef3cb32a02ed)
--|--

Disabled Background images

![Image](https://github.com/user-attachments/assets/a043dde4-88a3-4b90-ac8c-08fba8f8ad2b)|![Image](https://github.com/user-attachments/assets/03fa070c-81e7-44d3-8abc-2e52a6855ae2)
--|--

Enabled Background images

![Image](https://github.com/user-attachments/assets/f684af7e-c1fd-4aea-863e-24830b516420)|![Image](https://github.com/user-attachments/assets/fad7fc71-8a15-45c5-a600-01fee05bae5e)
--|--


</details>



### Test case 2

<details>

Disabled NTT

![Image](https://github.com/user-attachments/assets/1ed9a559-05e1-45c3-b449-c467c48f5563)|![Image](https://github.com/user-attachments/assets/bd5c5272-753e-40aa-8a77-148637c26b7a)
--|--

Enabled NTT
![Image](https://github.com/user-attachments/assets/a1e9398f-38b3-4fb2-8ae8-ce543449b153)|![Image](https://github.com/user-attachments/assets/39f2123a-85ae-4898-bd45-f1b4bff3220a)
--|--



</details>



### Test case 3

<details>

After joining rewards:

![Image](https://github.com/user-attachments/assets/c56ec7e3-fbdc-4d92-8244-76c17903a118)|![Image](https://github.com/user-attachments/assets/cd4933bd-c405-4da6-9254-9d8a7a2df081)
--|--|--

Disabled NTT from brave://rewards
![Image](https://github.com/user-attachments/assets/15071fb9-930b-4e80-a15a-4e96f41ace34)|![Image](https://github.com/user-attachments/assets/ddfd1e8c-b6db-4ea4-b254-c9e818f1c301)
--|--|--

Enabled NTT from brave://rewards

![Image](https://github.com/user-attachments/assets/209ea849-fd1d-4e6f-ba3d-223c4a4536ff)|![Image](https://github.com/user-attachments/assets/c319379b-a0dc-4c65-82b7-601c25fa946c)
--|--|--




</details>
