### ISSUE TITLE
Update Wallet Banners to use Nala Alert Component

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#41036]
### Platforms

Linux, macOS, Windows

### Description

We need to update all Wallet `Banners` to now use the new `Nala` alert components

![Screenshot 30](https://github.com/user-attachments/assets/9800122e-bda4-41aa-a48e-c48bf65e1706)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.72.82 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 4f0233b15f1896e28ff5ce439de1f658a2ef2df0
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from [brave/brave-core#25667](https://github.com/brave/brave-core/pull/25667)
- Verified wallet banners uses Nala alert components

Light Theme

![Image](https://github.com/user-attachments/assets/b080d023-35e7-4681-9710-3f0d49e3ff3b) | ![Image](https://github.com/user-attachments/assets/d02f4b11-1441-4a45-b5e7-0b018ad877d0) | ![Image](https://github.com/user-attachments/assets/71013813-8755-4aa0-a338-788cd4001db8)
-- | -- | --

Dark Theme 

![Image](https://github.com/user-attachments/assets/6ade2663-fa04-4858-abbb-7e06a266a295) | ![Image](https://github.com/user-attachments/assets/9f33adb6-ece6-471b-965c-6db29981aa6b) | ![Image](https://github.com/user-attachments/assets/1a665cde-865b-4fe0-a77e-143a5862b51e)
-- | -- | --

------------
Verification passed on 

Brave | 1.72.82 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 4f0233b15f1896e28ff5ce439de1f658a2ef2df0
OS | Linux

- Verified steps from [brave/brave-core#25667](https://github.com/brave/brave-core/pull/25667)
- Verified wallet banners uses Nala alert components

Light Theme

![Image](https://github.com/user-attachments/assets/02719953-d1cf-4c7f-bd1a-ef7357224bb6) | ![Image](https://github.com/user-attachments/assets/b515c4fd-2ddc-4277-975a-e947f3db5e47) | ![Image](https://github.com/user-attachments/assets/c9391fe8-7eee-433d-a09e-07de338d6776)
-- | -- | --

Dark Theme 

![Image](https://github.com/user-attachments/assets/f70f8d95-2067-43e0-846c-b4fc780ac465) | ![Image](https://github.com/user-attachments/assets/82600265-88d6-4046-b33a-a01290e9140d) | ![Image](https://github.com/user-attachments/assets/07ce3410-545e-482f-913b-e1cfebd6baec)
-- | -- | --

------------
Verification passed on 

Brave | 1.72.82 Chromium: 130.0.6723.58 (Official Build) beta (arm64)
-- | --
Revision | 4f0233b15f1896e28ff5ce439de1f658a2ef2df0
OS | macOS Version 15.0.1 (Build 24A248)

- Verified steps from [brave/brave-core#25667](https://github.com/brave/brave-core/pull/25667)
- Verified wallet banners uses Nala alert components

Light Theme

![Image](https://github.com/user-attachments/assets/572d8e78-1804-4af9-8739-072befcd5189) | ![Image](https://github.com/user-attachments/assets/9cc3e3be-2c1c-4929-a068-3641080135c1) | ![Image](https://github.com/user-attachments/assets/d25baabc-021c-4838-bc00-84e5dbbde13b)
-- | -- | --

Dark Theme 

![Image](https://github.com/user-attachments/assets/fb2a43ec-b901-450f-b7c6-d41c078dfb0a) | ![Image](https://github.com/user-attachments/assets/6bdf9bf9-97f2-4082-919a-80c61e73637f) | ![Image](https://github.com/user-attachments/assets/9a6e8123-5695-443c-804f-6d38017dd1ef)
-- | -- | --
