### ISSUE TITLE
Changeable Shortcut Button

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#41031]
Change "Show Bookmarks Shortcut" to "Show Shortcut Button" with a drill down for: [None, Shred, Bookmarks, Downloads, History, Playlist, Leo, Wallet]

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.0` using version `1.73 (87)`

* Ensured that Shortcut Button setting is shown in Settings menu.
* Ensured that Shortcut Button is set to `Hide Shortcut Button` by default.
* Ensured that selecting any of the options in Shortcut Button settings will enable the feature. 
* Ensured that Shortcut Button is shown in normal and private browsing.
* Ensured that long-pressing on the Shortcut button in the address bar will display the options list.
* Ensured that all shortcuts are displaying the appropriate views. 
* Ensured hiding shortcut button from the UI. 

encountered: https://github.com/brave/brave-browser/issues/42246

`example` | `example` | `example` | `example` | `example` | `example`
---|---|---|---|---|---
![Image](https://github.com/user-attachments/assets/69b1dd55-ece4-4c60-ab5e-acf0ec0e644a) | ![Image](https://github.com/user-attachments/assets/22da7ceb-b91a-4064-b075-da50f05a5f67) | ![Image](https://github.com/user-attachments/assets/b73f9392-c683-4c1c-b691-00e04c1cdd40) | ![Image](https://github.com/user-attachments/assets/ab28c07b-a09e-4eaa-be86-317791785f27) | ![Image](https://github.com/user-attachments/assets/4a3df87a-b114-499b-85c3-2145ace2e1a9) | ![Image](https://github.com/user-attachments/assets/d14b9123-a2e1-4af6-9a45-b1089b1f5e77)
