### ISSUE TITLE
[CR129] Crash when opening 'Content Filtering' settings page

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#41039]
### Description

Crashes when tapping on Settings -> Brave Shields & privacy -> Content Filtering
Regression in Chromium 129

Crash ID: `03200500-9ce4-970c-0000-000000000000`

### Steps to reproduce

1. New install
2. Open hamburger menu -> Settings -> Brave Shields & privacy 
3. Open `Content Filtering`

### Actual result

Crashes

![Screenshot 2024-09-12 at 8 12 26 PM](https://github.com/user-attachments/assets/91a1e35d-ada3-427a-adf1-5f79c11104e0)

### Expected result

Open custom filters page / Content Filtering

### Reproduces how often

Easily reproduced

### Brave version

1.71.81 - Reproducible
1.71.78 - Not Reproducible

### Device

- Brand/model: Samsung Galaxy S21
- Android version: 13

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.70.111` or higher for `1.70.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` running `Android 13` using version `1.70.113`

- Ensured that Content Filtering page is accessible and no crash is observed.
- Ensured that filter lists can be enabled.
- Ensured that `Filter list is successfully updated` dialog is displayed after tapping `UPDATE` button.

Example | Example
-|-
![Screenshot 2024-09-16 at 10 56 00 AM](https://github.com/user-attachments/assets/17b31f2a-dbd7-4eed-b75f-47a6b9097079) | ![Screenshot 2024-09-16 at 10 56 15 AM](https://github.com/user-attachments/assets/d7526fd4-fd39-4baa-938c-adcce34d50b0)
