### ISSUE TITLE
De-duplicate implementations of EnabledCupSigning()

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#41030]
### Description

While reviewing https://github.com/brave/brave-core/pull/25190, @bridiver realized that we define `EnabledCupSigning` in several places, when we should only be doing it once. The goal of this issue is to achieve this.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.82 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 4f0233b15f1896e28ff5ce439de1f658a2ef2df0
OS | Windows 11 Version 23H2 (Build 22631.4317)
```

1. Installed 1.72.82
2. launched Brave
3. opened  LocalAppData folder %LocalAppData%\BraveSoftware\Brave-Browser\User Data
4. removed each component folder as below
5. restarted the browser
6. closed and restarted the browser
7. loaded brave://components and waited for 8 mins 
8. installed extensions

**_Components update check_** 
<details>

- Brave Local Data Updater: afalakplffnnnlkncjhbmahjfjhmlkal
- CRL Set: CertificateRevocation
- Brave Ad block Updater: iodkpdagapdfkphljnddpjlldadblomo
- NTP Sponsored Images : gccbbckogglekeggclmmekihdgdpdgoe: 
- Brave Ad Block List Catalog: gkboaolpopklhgplhaaiboijnklogmbc: 
- Brave Ad Block Resources Library: mfddibmblmbccpadfndgakiopmmhebop: 
- Safe Browsing

#### Confirmed all components are re-downloaded after restarting the browser 
#### No errors are shown after 8 minutes wait time

example | example | example | example | example | example | example 
---- | ------ | ----- | ----- | ------ | ------ | -------
![Image](https://github.com/user-attachments/assets/3507b4a9-4849-4b81-8be0-7bc378bd7efc)|![Image](https://github.com/user-attachments/assets/17d29d09-bc38-49f7-8ebd-cfd54bff462c)|![Image](https://github.com/user-attachments/assets/46ff58a8-d22c-415a-b6d9-65c8acea4af3)|![Image](https://github.com/user-attachments/assets/6504abb2-766b-4e33-8bb3-7900824884ff)|![Image](https://github.com/user-attachments/assets/b6644242-6163-4ebb-b886-8d772ab4009c)|![Image](https://github.com/user-attachments/assets/629f8b08-4ffe-423c-993d-fcb1cb85a522)|![Image](https://github.com/user-attachments/assets/482458f3-e94e-4c2a-ac86-511d4d144958)
</details>

**_Extension update check_**
<details>

- imported an older version of an extension via Chrome, Edge
- confirmed the extension got updated to new version via Google server
- Installed new extension
- confirmed extension is installed and correct version shown

![Image](https://github.com/user-attachments/assets/8c669d2d-bc46-4cc9-9727-a9454e5202e6)

</details>

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.93 Chromium: 131.0.6778.14 (Official Build) beta (arm64)
-- | --
Revision | 69e5dc20ca483a13316632df5bcd9279bb2a3cb7
OS | macOS Version 14.6.1 (Build 23G93)
```


1. Installed 1.72.82
2. launched Brave
3. closed Brave
4. opened  LocalAppData folder %LocalAppData%\BraveSoftware\Brave-Browser-Beta\User Data
5. removed each component folder as below
6. restarted the browser
7. closed and restarted the browser each time
8. loaded brave://components and waited for 8 mins 
9. installed extensions
**_Components update check_** 
<details>

- Brave Local Data Updater: afalakplffnnnlkncjhbmahjfjhmlkal
- CRL Set: CertificateRevocation
- Brave Ad block Updater: iodkpdagapdfkphljnddpjlldadblomo
- NTP Sponsored Images : gccbbckogglekeggclmmekihdgdpdgoe: 
- Brave Ad Block List Catalog: gkboaolpopklhgplhaaiboijnklogmbc: 
- Brave Ad Block Resources Library: mfddibmblmbccpadfndgakiopmmhebop: 
- Safe Browsing

#### Confirmed all components are re-downloaded after restarting the browser 
#### No errors are shown after 8 minutes of wait 

example | example | example | example | example | example | example 
---- | ------ | ----- | ----- | ------ | ------ | -------
![Image](https://github.com/user-attachments/assets/72f2b122-6755-4f5c-98b8-6056ca6d3538)|![Image](https://github.com/user-attachments/assets/8128a973-4040-4348-8dbe-e6623dcf4585)|![Image](https://github.com/user-attachments/assets/17402d74-5e21-42c6-a942-e95860d9507c)|![Image](https://github.com/user-attachments/assets/62fdf9b5-ba3c-4763-b93c-e6860267ddfe)|![Image](https://github.com/user-attachments/assets/fa34b544-2c00-4393-9cf4-2c5eeac7ffcb)|![Image](https://github.com/user-attachments/assets/91ae4ab0-687f-4089-96db-bbed94bb080b)

</details>


**_Extension update check_**
<details>

- imported an older version of an extension via Chrome, Edge
- confirmed the extension got updated to new version via Google server
- Installed new extension
- confirmed extension is installed and correct version shown

nimbus | zoom
---- | ----

**Comment by hffvld** [comment]
I was able to verify this issue on Android partially because `gccbbckogglekeggclmmekihdgdpdgoe` and `Safe Browsing` don't exist on `Android` in the profile folder.

cc @kjozwiak 

-------------------------

Verified on `Pixel 6` using version(s):
```
Device/OS: Pixel 6 / oriole-user 14 AP2A.240905.003.F1 release-keys
Brave build: 1.72.93 
Chromium: 131.0.6778.14 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Fresh install and launch Brave
2. Close Berave
3. Go to the Brave profile folder `/data/data/com.brave.browser_beta/app_chrome` on `Android` device
4. Remove components:
- Brave Local Data Updater: `afalakplffnnnlkncjhbmahjfjhmlkal`
- CRL Set: `CertificateRevocation`
- Brave Ad block Updater: `iodkpdagapdfkphljnddpjlldadblomo`
- NTP Sponsored Images: `gccbbckogglekeggclmmekihdgdpdgoe` - DOESN'T EXIST
- Brave Ad Block List Catalog: `gkboaolpopklhgplhaaiboijnklogmbc`
- Brave Ad Block Resources Library: `mfddibmblmbccpadfndgakiopmmhebop`
- `Safe Browsing` - DOESN'T EXIST
5. Restart Brave
6. Load `brave://components` and wait for 8 mins

**ACTUAL RESULTS:**
- Verified that all components are re-downloaded after restarting the browser

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/30ddeccf-1e7d-47c4-ae18-324be0b757ff) | ![2](https://github.com/user-attachments/assets/c9c43a8d-7700-4896-a190-ed3a98756597) | ![3](https://github.com/user-attachments/assets/a721a78d-af2f-4646-a070-3bf625db4af2) | ![4](https://github.com/user-attachments/assets/d8fd72ee-1b0c-4c50-85ac-4877719c8f83) |

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave	1.72.95 Chromium: 131.0.6778.24 (Official Build) beta (64-bit) 
Revision	006619fbaf6013cb3495b90fc3885eda343087e5
OS	Linux
```

1. Installed 1.72.82
2. launched Brave
3. closed Brave
4. opened `~/Library/Application Support/BraveSoftware/Brave-Browser-Beta`
5. removed each component folder as below
6. restarted the browser
7. closed and restarted the browser each time
8. loaded brave://components and waited for 8 mins 
9. installed extensions

**_Components update check_** 
<details>

- Brave Local Data Updater: afalakplffnnnlkncjhbmahjfjhmlkal
- CRL Set: CertificateRevocation
- Brave Ad block Updater: iodkpdagapdfkphljnddpjlldadblomo
- NTP Sponsored Images : gccbbckogglekeggclmmekihdgdpdgoe: 
- Brave Ad Block List Catalog: gkboaolpopklhgplhaaiboijnklogmbc: 
- Brave Ad Block Resources Library: mfddibmblmbccpadfndgakiopmmhebop: 
- Safe Browsing

#### Confirmed all components are re-downloaded after restarting the browser 
#### No errors are shown after 8 minutes of wait 

example | example | example | example | example | example | example 
---- | ------ | ----- | ----- | ------ | ------ | -------




**_Extension update check_**
<details>

- imported an older version of an extension via Chrome, Edge
- confirmed the extension got updated to new version via Google server
- Installed new extension
- confirmed extension is installed and correct version shown

nimbus | BrowserGPT 
---- | ----

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Mini (6th gen)` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.7.1
- iPad Mini (6th gen) / iPadOS 18.0.1
Brave build: 1.73 (89)
BraveCore: 1.73.89 (131.0.6778.69)
```
---------------------------

**STEPS:**
1. Fresh install and Launch Brave 
2. Close and relaunch Brave
3. Settings > Dev options
4. Go to `Sandbox Inspector` > `Library` > `Application support` > `Chromium`
5. *Verify, that the components exist*

**ACTUAL RESULTS:**
- Verified that Brave components exist in `Sandbox Inspector` > `Library` > `Application support` > `Chromium`:
  - `afalakplffnnnlkncjhbmahjfjhmlkal`
  - `iodkpdagapdfkphljnddpjlldadblomo`
  - `gkboaolpopklhgplhaaiboijnklogmbc`
  - `mfddibmblmbccpadfndgakiopmmhebop`
  - `Safe Browsing`

---------------------------

`iPhone 14`

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/bc568748-23f1-4e98-b1cf-8e788fbbb6e1) | ![2](https://github.com/user-attachments/assets/3e7e0cb5-8a8a-43e3-bed6-a05c9ec20891) | ![3](https://github.com/user-attachments/assets/704bd8d5-d47f-4597-8128-5de5225df741) | ![4](https://github.com/user-attachments/assets/37c96e0f-ee4e-4426-90da-4d3007155585) | ![5](https://github.com/user-attachments/assets/a9ab135e-5b22-4507-b046-b2505e018be8) |

`iPad Mini (6th gen)`

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/426086e3-1ee2-4257-b4a7-726a7b97d6a0) | ![2](https://github.com/user-attachments/assets/c844d595-f111-4162-8e00-8b1b1b2a30bf) | ![3](https://github.com/user-attachments/assets/7472da63-b016-44e8-8dc0-fd76c9becd55) | ![4](https://github.com/user-attachments/assets/31fb9bd8-ce4f-4117-8fe8-6cdcdde36eff) | ![5](https://github.com/user-attachments/assets/df05d5c3-bb8d-4554-8857-5900f75d44bd) |
