### ISSUE TITLE
Update Wallet Panel Watermark Background

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#41035]
### Platforms

Linux, macOS, Windows

### Description

We need to update the `Wallet` background `Watermark` to match the new figma designs.
- Background should be more prominent.
- Background should also bleed into the `header`

![Screenshot 29](https://github.com/user-attachments/assets/a9896d00-bd05-47b2-bd4f-0dd810ab036a)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.72.82 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 4f0233b15f1896e28ff5ce439de1f658a2ef2df0
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from [brave/brave-core#25615](https://github.com/brave/brave-core/pull/25615)
- Verified Wallet panel watermark background is more prominent now
- Verified background now also covers the Wallet header portion
- Verified for both light and dark theme

Light | Dark
-- | --
![Image](https://github.com/user-attachments/assets/2c8e54af-4de7-49ae-ab46-4bd6e6d0a87d) | ![Image](https://github.com/user-attachments/assets/61fe5527-88ea-4933-95ff-9ee6817cdac7)

----------
Verification passed on

Brave | 1.72.82 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 4f0233b15f1896e28ff5ce439de1f658a2ef2df0
OS | Linux

- Verified steps from [brave/brave-core#25615](https://github.com/brave/brave-core/pull/25615)
- Verified Wallet panel watermark background is more prominent now
- Verified background now also covers the Wallet header portion
- Verified for both light and dark theme

Light | Dark
-- | --
![Image](https://github.com/user-attachments/assets/9785bd12-29c2-41f2-a449-5d05b08388c5) | ![Image](https://github.com/user-attachments/assets/eb4b7d3d-63f9-465a-9275-147f6d1d4601)


-----------
Verification passed on

Brave | 1.72.82 Chromium: 130.0.6723.58 (Official Build) beta (arm64)
-- | --
Revision | 4f0233b15f1896e28ff5ce439de1f658a2ef2df0
OS | macOS Version 15.0.1

- Verified steps from [brave/brave-core#25615](https://github.com/brave/brave-core/pull/25615)
- Verified Wallet panel watermark background is more prominent now
- Verified background now also covers the Wallet header portion
- Verified for both light and dark theme

Light | Dark
-- | --
![Image](https://github.com/user-attachments/assets/52d9be39-8ea9-40d4-aec5-e6ea8875ca61) | ![Image](https://github.com/user-attachments/assets/df3e732f-4c67-4df6-ab1d-f61b1276dbbb)
