### ISSUE TITLE
Integrate Squid Router to Swap and Bridge

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#41049]
### Description

We would like to have Squid Router as an additional provider for fetching swap and bridge quotes

### Steps to reproduce

1. Open Swap / Bridge
2. Select Squid as the provider preference
3. Set the tokens and enter the amount to fetch a quote

### Actual result

N/A

### Expected result

Swap / bridge quote should be fetched via Squid Router API. Boost mode should be supported.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

N/A

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.9 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | 30ceb433b8a77b995214506d3d862edb3220614b
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from [brave/brave-core#25676](https://github.com/brave/brave-core/pull/25676)
- Verified Squid is available as a Swap/Bridge provider
- Verified entering amount and Swap/Bridge tokens generates quote
- Verified quote refresh for every 30sec 
- Encountered []()

https://github.com/user-attachments/assets/b3459611-2369-4542-bdca-cd5d5ffae550
