### ISSUE TITLE
[CR130] Address Lit/Polymer changes in download manager

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#41046]
### Description

In CR130, upstream made a few changes to the download manager replacing it with a TypeScript/CSS equivalent. This affected our patches and other overrides. We should fix this and also see if there's anything we can do to strengthen our Lit support in general.

The relevant upstream changes include:

https://crrev.com/c/5282912
https://crrev.com/c/5839328
https://crrev.com/c/5852361

**Comment by emerick** [comment]
cc: @cdesouza-chromium

**Comment by emerick** [comment]
@fallaciousreasoning I'm thinking we can probably close this out now, but let me know. if not!

**Comment by fallaciousreasoning** [comment]
Fixed by https://github.com/brave/brave-core/pull/26847
