### ISSUE TITLE
`omnibox` highlight too bright when using darker profile themes

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#41055]
### Description

On my current Nightly installation which is my daily driver with ~4 profiles, the ones using the darker theme are now using a really light `omnibox` separator which makes it really difficult to read what is being highlighted/selected as per the screenshot. 

### Steps to reproduce

I'm not 100% sure on the STR/Cases as I couldn't really reproduce the issue on a clean install, but after I updated my Nightly installation from `C128` --> `C129`, noticed that the selector via the `omnibox` was too bright within my profiles using darker themes.

Regarding QA/Verification, I would run through the following:

* install a build that has the fix and ensure that the `omnibox` separator isn't too bright and items that are highlighted are legible
* have several profiles setup via `C128` that use dark themes and upgrade to `C129` and ensure the issue doesn't occur

### Actual result

The current `omnibox` selector is really light which makes it really difficult to read which item is being selected as per the following:

![image_720](https://github.com/user-attachments/assets/afcb022e-223c-4267-b315-523429193226)

### Expected result

Should be a lot easier to read similar to the following:

![image](https://github.com/user-attachments/assets/86fbf093-3c48-4c01-b08d-e6d3ad103208)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.72.3 Chromium: 129.0.6668.42 (Official Build) nightly (64-bit)
-- | --
Revision | 86ff9ad73e0c9846e1cb572d6076c5f94a433268
OS | Windows 11 Version 23H2 (Build 22631.4112)
```

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by fallaciousreasoning** [comment]
**Note:* To repro, install a custom dark theme from the Chrome web store (i.e. https://chromewebstore.google.com/detail/just-black/aghfnjkcakhmadgdomlmlhhaocbkloab)

**Comment by kjozwiak** [comment]
The above requires `1.71.91` or higher for `1.71.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.97 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | de99cbcb1aa0aa00877d356e4733f4e5481e89eb
OS | Windows 11 Version 23H2 (Build 22631.4169)
```

**_Light theme_**

1. Installed 1.71.97 
2. launched Brave 
3. kept Windows in light mode
4. verified the flag `brave://flags/#brave-web-view-rounded-corners` is disabled
5. installed `Just Black` theme via https://chromewebstore.google.com/detail/just-black/aghfnjkcakhmadgdomlmlhhaocbkloab
6. typed `London` in the omnibox in a new tab


- Confirmed Selected result is not white ish
- Confirmed Hovering over results not be white ish
- Confirmed Separator above Ask Leo is not white ish 
              ** Separator is very faint line 

example | example | example
---- | ----- | ------ 
![image](https://github.com/user-attachments/assets/1ebf0a6c-d0cb-4512-930a-ae7ea2943654)|![image](https://github.com/user-attachments/assets/e7bf1227-e53c-4396-8029-6ae9f9f2ff29)|![image](https://github.com/user-attachments/assets/4381f86a-7e18-43b6-9ba5-676b402fdbcf)

**_Dark theme_**


1. Installed 1.71.97 
2. launched Brave
3. opened `brave://settings/appearance` and switched to `Dark`
4. disabled the flag `brave://flags/#brave-web-view-rounded-corners` 
5. typed `London` in the omnibox  
6. switched to vertical tab view 

- Confirmed Selected result is not white ish
- Hovering over results is white ish
- Separator above Ask Leo is white ish
- Confirmed a separator between vertical tabs and the page is shown and it is not white
                   ** Separator is still white.  - encountered https://github.com/brave/brave-browser/issues/41215

step 4 | step 5| step 6
----- | ----- | ---- 
![image](https://github.com/user-attachments/assets/54b543c7-1268-4426-8bb0-2ea6e7e56e0b)|![image](https://github.com/user-attachments/assets/553782e8-f7dd-4063-b087-e7eaf11866e7)|![image](https://github.com/user-attachments/assets/755acf71-f9e3-4636-9499-f58cbd12b574)
