### ISSUE TITLE
Fix safe browsing

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#41060]
### Description

Safe browsing stopped working since 1.69.145. We need to fix it.

### Steps to reproduce

1. Goto https://testsafebrowsing.appspot.com
2. Click first link.
3. There is some web site content instead of dangerous site page.

### Actual result

There is some web site content

### Expected result

Dangerous site page

### Reproduces how often

Easily reproduced

### Brave version

1.69.145 and higher

### Device

- Brand/model: any
- Android version: any

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.70.114` or higher for `1.70.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` & `Samsung Galaxy S21` running `Android 13` using version `1.70.114`

- Ensured Safe Browsing protection is enabled when using test links in `https://testsafebrowsing.appspot.com`
- Ensured that warning interstitial is displayed when navigating to a malicious/dangerous website when Safe Browsing is enabled.
- Ensured that user is able to navigate back by tapping on `Back to safety` on the warning interstitial page.
- Ensured that clicking through the warning interstitial is successful. 

example | example | example
---|---|---
![Screenshot 2024-09-17 at 12 59 08 PM](https://github.com/user-attachments/assets/6509d300-36ed-441c-b84b-869d95ef22bd) | ![Screenshot 2024-09-17 at 12 58 51 PM](https://github.com/user-attachments/assets/cc33b065-fa8b-4937-af53-08033f58702f) | ![Screenshot 2024-09-17 at 12 58 58 PM](https://github.com/user-attachments/assets/188f7d51-78c6-4ad4-933d-6deae574124b)
![Screenshot 2024-09-17 at 2 14 50 PM](https://github.com/user-attachments/assets/33c6a7af-2049-408a-82df-359f2f9fb9f2) | ![Screenshot 2024-09-17 at 2 15 27 PM](https://github.com/user-attachments/assets/ca7b4a2d-4704-4c9a-9fa5-693ef92d1fbc) | ![Screenshot 2024-09-17 at 2 15 48 PM](https://github.com/user-attachments/assets/2143c96f-0068-4a56-84f1-c17965fda148)
