### ISSUE TITLE
[BYOM] Unintended Prompt Backfilling into Chat History

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#41079]
### Description

When asking Leo to summarize a page, the prompt instructing Leo as to what content is on the page is injected into the sidebar chat history.

Also observed in reports by users on X (e.g., https://x.com/Waescher/status/1834208948099952926)

### Steps to reproduce

1. Setup a BYOM model (e.g., via Ollama)
2. With the model selected, ask Leo to "summarize a page".

### Actual result

Leo backfills the page content (surrounded with `<page />` tags) into the chat history itself.

### Expected result

The content of the page itself should not be injected into the chat history; only the summary should be presented (once available).

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit) 
1.72.6 Chromium: 129.0.6668.42 (Official Build) nightly (64-bit) 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Looks to be related to https://github.com/brave/brave-core/pull/24453 and https://github.com/brave/brave-browser/issues/39525.

**Comment by jonathansampson** [comment]
I was mistaken about this behavior being _unintentional_; https://github.com/brave/brave-core/pull/24453 shows it to be very much intentional. That PR initially split the page content and the user's prompt into two conversation entries. After some discussion, a decision was made to combine them into one conversation entry by appending the page content to the user's prompt, meaning the behavior detailed in this PR is technically _by design_.

I've broken the message up into two distinct messages again, and confirmed that Ollama continues to work as expected (even with the contiguous user messages). Because our custom engine is also used for ChatGPT integration, that scenario also needs to be tested; I'm working on that now.

**Comment by jonathansampson** [comment]
Just verified that ChatGPT handles the scenario of _conversation_history_  containing `[..., user, user, ...]` with no issue. As such, I think the best solution is to simply break the messages up, similar to how we handle this scenario in the _conversation api_ approach.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.15 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | d1293587128488865fa61e9fa277dd54aa2270b0
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from [brave/brave-core#25807](https://github.com/brave/brave-core/pull/25807)
- Verified there is no backfill when summarizing page using local model

https://github.com/user-attachments/assets/e182fc1c-0404-40e3-82f2-ffc25c4e6f91
