### ISSUE TITLE
I'd like to have the close button on tabs to be constantly visible 

### ISSUE THREAD

**Issue by kijetesantakalu042** [brave/brave-browser#41077]
### Description

I'm switching from firefox to brave, and the close button on tabs not always being visible is annoying me.

### Steps to reproduce

1. Install Brave
2. Make more tabs. only the selected tab will have the close button

### Actual result

![image](https://github.com/user-attachments/assets/12e13f65-25f0-487e-a240-2bc7c242d8ba)

### Expected result

![image](https://github.com/user-attachments/assets/aeb9d302-d4c2-4efa-99a4-443b51ce26c0)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.168

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment]
Closing as wontfix. It's a design choice we made to show more of the tab title as people open up more tabs. When you hover over the tab to close, the "x" will appear and you can close it then.

**Comment by 123658vaoo-dotcom** [comment]
> Closing as wontfix. It's a design choice we made to show more of the tab title as people open up more tabs. When you hover over the tab to close, the "x" will appear and you can close it then.

customization?
