### ISSUE TITLE
Downloads aren’t saving, files disappear after download

### ISSUE THREAD

**Issue by Saoiray** [brave/brave-browser#41073]
### Description

When downloading anything and trying to save to Files, it never appears. This issue appears to only exist with Brave and does not happen in Chrome or Safari.

### Steps to reproduce

1. Navigate to a site with a downloadable file
2. Download the file
3. Go to Downloads in Brave or navigate to Files on iOS

### Actual result

The downloaded file doesn't exist. Downloads is empty

### Expected result

File should be downloaded and available for use. 

### Reproduces how often

Easily reproduced

### Brave version

1.69.1

### Device/iOS version

iOS 17.6.1
iOS 17.4.1

### Affected browser versions

- [X] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [X] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

Issue reported by users at https://community.brave.com/t/downloaded-videos-on-ios/568738/

Then was able to replicate myself as well.  

**SIDE NOTE**
I could swear we used to have the ability to choose download destinations within Brave on iOS but I don't see that anywhere now. Did this change or am I thinking more of Android?

**Comment by GROSU1** [comment]
Happened after latest release on Friday 13th, previously worked without issues. Version build 171 of 1.69.1.
Just tested on 18.0 today with the same issue. Was thinking some change might have been for the new major iOS release but it doesn't seem like it.

**Comment by bompao108** [comment]
Got the same problem. Can't even download anything although the download section is finished tho

**Comment by roafhtun** [comment]
same problem here, goes to look into Files app on iOS nothing is downloaded there.

**Comment by Brave-Matt** [comment]
Another +1 from Community:
https://community.brave.com/t/downloads-nowhere-to-be-found/569337

**Comment by Brave-Matt** [comment]
More +1s:
https://community.brave.com/t/after-latest-update-downloading-is-not-working/568956

**Comment by lukemulks** [comment]
+1 from user via DM on X
![Screenshot_20240917_183634_X](https://github.com/user-attachments/assets/9ea278bf-2794-4b03-955d-7d8b20b4524d)

**Comment by teanea** [comment]
me too

**Comment by bompao108** [comment]
> issue

This download issue is terrible cuz I can't download anything via Brave
I need to have another browser in my iPhone

**Comment by bompao108** [comment]
@kylehickinson 
no bro it ain't fix nothing yet
I just downloaded Brave back
Tested Youtube, Tiktok, ... Still aint got any videos after the download finishes

**Comment by bompao108** [comment]
@kylehickinson proof : 
![IMG_0465](https://github.com/user-attachments/assets/42e5d5e0-7716-4104-ad8e-d2a658ea45bc)
![IMG_0466](https://github.com/user-attachments/assets/f5d69e4c-ed8f-498c-9e00-4a9834827eb6)
![IMG_0467](https://github.com/user-attachments/assets/447385e7-d981-494e-8b00-55238ddfa3a5)

**Comment by kylehickinson** [comment]
@bompao108 this fix hasn't shipped to any public builds yet. Keep an eye out for 1.69.2 in the next few days

**Comment by bompao108** [comment]
> @bompao108 this fix hasn't shipped to any public builds yet. Keep an eye out for 1.69.2 in the next few days

Thanks. I need it

**Comment by kjozwiak** [comment]
The above requires `1.69.172` or higher for `1.69.x` verification. We'll be starting RC builds shorty and hoping to get them approved by Apple sometime today/tomorrow. Once approved, we'll start pushing the fix out via `1.69.172`. Unless we find other issues related to `Downloads` & `Passbook` while verifying the RC builds.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 18` using the following build(s):

```
Brave | 1.69.172 Chromium: 128.0.6613.138 (Official Build) stable (64-bit) 
--- | ---
Revision | 6da7ca9e1ca7...
OS | iOS
```

Using similar STR/Cases outlined via https://github.com/brave/brave-core/pull/25651#issuecomment-2364318981, went through the following:

### `Passbook` verification(s):

* ensured that you can download/add passes into the `Apple Wallet` via https://pub1.pskt.io/4wcEqRJZVWU7XGKbt6sXof & https://passkit.com/guide/ as per the following:

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|---------------|---------------|---------------|--------------
![IMG_0564](https://github.com/user-attachments/assets/533f36d8-663e-4caf-bf8c-052c6a9c923c) | ![IMG_0565](https://github.com/user-attachments/assets/c3cfce87-a5c2-453d-b11f-4612d5c6681c) |  ![IMG_0567](https://github.com/user-attachments/assets/8f059c87-ddd3-483c-bcae-16ea812387ab) | ![IMG_0566](https://github.com/user-attachments/assets/3da557d1-9454-4730-bc81-1b75f740c8d9) | ![IMG_0568](https://github.com/user-attachments/assets/c5f8b17a-cf2a-417d-9312-c0e36a3cb8dd)

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|---------------|---------------|---------------
![IMG_0569](https://github.com/user-attachments/assets/36c85781-34cf-423c-b8b4-a42a0c5ff4d9) | ![IMG_0571](https://github.com/user-attachments/assets/dc8e53a7-2088-45b3-a926-7f2f2a9d034c) | ![IMG_0570](https://github.com/user-attachments/assets/44af8cf8-673a-45fa-8a11-38eb4983f7c1) | ![IMG_0572](https://github.com/user-attachments/assets/1d15aa53-f8ae-4d85-8e03-b72eb5f79342)

### `PDF` download verification(s):

* ensured that you can download/save https://bitcoin.org/bitcoin.pdf without any issues as per the following:

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|---------------|---------------|---------------
![IMG_0580](https://github.com/user-attachments/assets/d058b1e8-5be6-4e79-8681-24bd024a306b) | ![IMG_0581](https://github.com/user-attachments/assets/813ce53e-44fd-4134-9580-26caa9aa9f51) | ![IMG_0582](https://github.com/user-attachments/assets/ee54cb71-abde-4d8c-a186-9b2383d7a9e3) | ![IMG_0583](https://github.com/user-attachments/assets/c2a9396b-4ff4-4639-a131-3c38cf41aa52)

### `Image` download verification(s):

* ensured that you can download images via https://unsplash.com/s/photos/spash as per the following:

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|---------------|---------------|---------------
![IMG_0575](https://github.com/user-attachments/assets/3c24d92a-74fc-4324-9624-1564063c5535) | ![IMG_0576](https://github.com/user-attachments/assets/b567423f-0e0c-4858-8ae7-5d073bf671bc) | ![IMG_0577](https://github.com/user-attachments/assets/139b6c2b-cb2b-4a8f-b973-90354acee7e5) | ![IMG_0578](https://github.com/user-attachments/assets/7806ea32-6d92-475a-b546-d5f347ab1fb6)

### `Instagram` download verification (case provided by Community):

* using the STR/Cases outlined via https://github.com/brave/brave-core/pull/25651#issue-2536560841 which were provided by the community, ensured that you can download the `Instagram` image as per the following:

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|---------------|---------------|-----------------|------------------|-----------------
![IMG_0584](https://github.com/user-attachments/assets/74c8ecfa-3f3d-446f-b1e8-8c71f2ddf754) | ![IMG_0586](https://github.com/user-attachments/assets/4738a553-a5b0-4cb9-886b-0be2f74a041b) | ![IMG_0588](https://github.com/user-attachments/assets/89153693-fe4c-4940-bc0d-b2e62257175a) | ![IMG_0589](https://github.com/user-attachments/assets/c77c81d7-be55-448d-a594-c210eadfcb8a) | ![IMG_0590](https://github.com/user-attachments/assets/1db796ed-721a-44a1-a02e-8a6fbe056135) | ![IMG_0591](https://github.com/user-attachments/assets/79a0e28e-02b3-4b93-a611-9776b77e3e21)

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iPadOS 17.5.1` using version `1.69.2 (172)`

**Case: snapinsta.app** - **`PASSED`**

<details>

- Went through the test steps below and ensured that file is downloaded successfully and shown in `Downloads` folder. 
   - Copy an instagram link (e.g. https://www.instagram.com/reel/DABSg8nJb4D/)
   - Visit snapinsta.app and submit the link to be downloaded
   - Click "Download" when it appears
   
example | example | example
---|---|---
![IMG_1625](https://github.com/user-attachments/assets/f75f7d18-8566-4f6c-90a6-6251bfecc8a5) | ![IMG_1626](https://github.com/user-attachments/assets/a8adfdb5-e682-4e4f-bfc1-7904b0dd2418) | ![IMG_1627](https://github.com/user-attachments/assets/ab4433f5-68f0-481e-ab2d-43c008418964)

</details>

**Case: PDF download** - **`PASSED`**

<details>

- Ensured that downloading PDF files is working using `Save to Files` in share menu

example | example | example
---|---|---
![IMG_1628](https://github.com/user-attachments/assets/5407cc14-b9ae-4029-91e2-640ffe4fc9da) | ![IMG_1629](https://github.com/user-attachments/assets/9baeb648-5437-4b6c-8053-35194764c4b5) | ![IMG_1630](https://github.com/user-attachments/assets/85dd7bdc-4b0d-49bd-95c5-916de9a51838)

</details>

**Case: Saving Image to Photos** - **`PASSED`**

<details>

example | example | example
---|---|---
![IMG_1634](https://github.com/user-attachments/assets/ea6117a4-d1c7-4e29-aca8-59817067bc88) | ![IMG_1635](https://github.com/user-attachments/assets/d294f8c8-707f-439c-8ae8-6db1f0cc2b97) | ![IMG_1637](https://github.com/user-attachments/assets/2301ed42-65de-48e7-81e0-4fd7ac820c68)

</details>
 
 **Case: Add to Wallet** - **`DEFERRED`**
 
 <details>
 
 example | example
 ---|---
![IMG_1638](https://github.com/user-attachments/assets/6db54e8c-7d18-4fb9-bb13-d9155b11b4a1) | ![IMG_1639](https://github.com/user-attachments/assets/f282c9fe-f2fb-4143-a691-4826981f84e5)

*Note: iPad (7th Gen) does not support Passbook. 

</details>

**Case: Direct Download (unsplash)** - **`PASSED`**

<details>

example | example | example
---|---|---
![IMG_1631](https://github.com/user-attachments/assets/1b844bfb-cce3-4819-adb0-400d08f04c23) | ![IMG_1632](https://github.com/user-attachments/assets/1b4e33f2-7a37-4922-b689-a7f897d8acb8) | ![IMG_1633](https://github.com/user-attachments/assets/44ba6099-ff50-417b-ac1a-16b8dc8f8627)

</details>
