### ISSUE TITLE
[Downloads]: Fix download bar color

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#41082]
1. Start a download
2. On the downloads page, look at the download bar color

Expected:
Download bar color is blurple

Actual:
Download bar color is blue

**Comment by fallaciousreasoning** [comment]
**Note:** This will probably not work in cr130, as upstream has rewritten the downloads page, but its an improvement

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.82 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 4f0233b15f1896e28ff5ce439de1f658a2ef2df0
OS | Windows 11 Version 23H2 (Build 22631.4317)
```

1. Installed 1.72.82
2. launched Brave
3. download a large file (https://ubuntu.com/download/desktop/thank-you?version=24.04.1&architecture=amd64&lts=true) 
4. opened brave://downloads
5. observe the download progress bar color

#### Confirmed blurple is shown for the download bar

1.71.114 | 1.72.82
------ | ------
![Image](https://github.com/user-attachments/assets/157109e0-ecc2-450b-aae0-5c0d2e7447d9)|![Image](https://github.com/user-attachments/assets/112e87f0-bddd-4814-a1c1-5771bc1f44bc)
