### ISSUE TITLE
Settings sections should be better ordered for popularity and complexity

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#4108]
New order according to @bradleyrichter 👍 

```
Getting Started
Appearance
Sync
Shields
Social Media Blocking (soon to be folded in to Shields)
Search
Extensions
```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.109 Chromium: 76.0.3809.62 (Official Build) dev (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Ubuntu 18.04 LTS

Used test plan from https://github.com/brave/brave-core/pull/2530
Checked if all the links work as expected.

![image](https://user-images.githubusercontent.com/34715963/61835613-cf621480-ae7c-11e9-97d8-cf9a7c94a973.png)
