### ISSUE TITLE
Support Dark Mode & Tinted Icons on iOS 18

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#41088]
iOS 18 adds support for specialized dark mode & tinted app icons and apps and we should add them since iOS 18 fails to generate a dark mode icon for Brave.

We'll need dark mode & tinted icons for these all 3 channels (release, beta, nightly), and optionally for local/debug builds

**Comment by meguroyama** [comment]
Would love a dark tint for Brave. [Apple's doc / guidance ](https://developer.apple.com/design/human-interface-guidelines/app-icons#Platform-considerations) is interesting as well.

**Comment by meguroyama** [comment]
That was super quick thanks @kylehickinson !!!

**Comment by kjozwiak** [comment]
The above requires `1.70.118` or higher for `1.70.x` verification 👍

**Comment by kjmagill** [comment]
> The above requires `1.70.118` or higher for `1.70.x` verification 👍 

Does "or higher" include using the latest version of BraveBeta (1.71) from the AppStore?

Unfortunately, I'm still seeing the white background on both the Beta 1.71(90) and Release 1.69.2(172) versions of Brave when using darkmode on iOS 18. These are the latest versions available at this time for both of these apps in the AppStore

**Comment by kylehickinson** [comment]
@kjmagill it does not include the beta builds as those have a different build schedule, the next beta build that gets uploaded will include these changes (90 currently does not include it)

**Comment by hffvld** [comment]
Verified on `iPad Air`, `iPhone 14` and `iPad Mini (6th gen)` using version(s):
```
Device/OS: 
- iPad Air / iPadOS 16.7.2
- iPhone 14 / iOS 17.7
- iPad Mni (6th gen) / iPadOS 18
Brave build: 1.70 (119)
BraveCore: 1.70.119 (129.0.6668.70)
```
---------------------------
<details>
<summary> iPad Air / iPadOS 16.7.2 </summary>

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/25603#issue-2531522654
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the **standard** `light mode` Brave icon appears on `iOS 16`

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/e5094cf8-06da-4797-91ec-8e9c9998794e) | ![2](https://github.com/user-attachments/assets/bcddcca1-2c32-4702-b638-4a7c1e3bfe27) |
</details>

<details>
<summary> iPhone 14 / iOS 17.7 </summary>

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/25603#issue-2531522654
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the **standard** `light mode` Brave icon appears on `iOS 17`

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/26c87b69-6c7f-4db8-888b-c7814f96ca5e) | ![2](https://github.com/user-attachments/assets/cff56b90-5a64-4df4-9741-df60a3128e4e) | ![3](https://github.com/user-attachments/assets/6d5bd85e-4229-487f-9dce-1d167bb08cf9) | ![4](https://github.com/user-attachments/assets/058959fb-d8f8-4ddb-b235-159b9e4ca855) |
</details>

<details>
<summary> iPad Mni (6th gen) / iPadOS 18 </summary>

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/25603#issue-2531522654
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the Brave icon supports `Light`, `Dark`, `Automatic`, and `Tinted` modes.
- Verified that Brave icons appear correctly when using `small` and `large` icon settings in the customization panel.
- Verified that using different tint configurations in `Tinted` mode is applied correctly.
- Verified that the Brave icon shows the correct mode when using the `automatic` mode in the home screen customize menu.
- Verified that Brave `Widgets` support the new `Tinted` mode.

---------------------------

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/94cedd1a-da1f-44e9-aa00-f27fa3d46441) | ![2](https://github.com/user-attachments/assets/c3983e90-0fd1-47ef-bb24-e3b77b656553) | ![3](https://github.com/user-attachments/assets/b66112b9-ebd5-4638-a342-41c1225408b2) | ![4](https://github.com/user-attachments/assets/f7220cbc-b582-4321-9df3-b45b9c84347a) | ![5](https://github.com/user-attachments/assets/74f6cddb-d8a0-4af4-9964-06302e95e582) |
| ![1](https://github.com/user-attachments/assets/96e145c4-c35c-4f32-89c1-73b87a39b0a0) | ![2](https://github.com/user-attachments/assets/cf7590c1-8acf-4c4b-a028-8f02e5ad080b) | ![3](https://github.com/user-attachments/assets/13af97f8-d606-4bac-87b4-7bddf7ddf6eb) | ![4](https://github.com/user-attachments/assets/9d23344e-bba4-4794-979c-f63cb2118b99) | ![5](https://github.com/user-attachments/assets/66b4a3f4-234c-4e32-b290-a96d2b8f51f9) |
| ![1](https://github.com/user-attachments/assets/32c63e68-8bdc-42dd-a4b7-3d21c96356ed) | ![2](https://github.com/user-attachments/assets/47daf500-f914-4862-a4c3-5cd4fa1df59c) | ![3](https://github.com/user-attachments/assets/ce05b893-fdb4-4f0b-8b13-57c23340be51) | ![4](https://github.com/user-attachments/assets/a2fecd5b-96aa-4ecd-93e3-05b1454e1e1a) | ![5](https://github.com/user-attachments/assets/3150b114-7439-4147-a9d2-d9b3b2f27333) |
</details>
