### ISSUE TITLE
[Cr129] Websites can't be opened in Brave when using Android's native `Share` button

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#41089]
### Description

Websites can't be opened in Brave when using Android's native `Share` button. 

### Steps to reproduce

1. While on the device's `Homescreen` swipe right to open the Google News feed
2. Tap the `Share` button for any article
3. Choose `Brave` > *Observe*

### Actual result

Websites can't be opened in Brave when using Android's native `Share` button.

-----------------

https://github.com/user-attachments/assets/4f3fa058-ba04-46f6-872f-98dd4587f170

### Expected result

Websites must be opened in Brave when using Android's native `Share` button.

---------------

https://github.com/user-attachments/assets/ae75bd5b-a460-48c1-863f-09bfcc18030e

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.70.113
Chromium: 129.0.6668.42 (Official Build) (64-bit)

### Device

- Brand/Model: Galaxy Tab S8, Pixel 7
- Android version: 14, 15

### Channel information

- [X] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.70.115` or higher for `1.70.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 AP41.240823.009 release-keys
Brave build: 1.70.115
Chromium: 129.0.6668.59 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41089#issue-2529062233
2. *Verify*

**ACTUAL RESULTS:**
- Verified that websites can be opened in Brave via Android's native `Share` button.
- Verified that no regression happened, and weblinks can be opened in Brave `Webview` mode.
- Verified that websites can be opened within Brave via the `Share` button in other browsers.

---------------------------

`Galaxy Tab S8`


https://github.com/user-attachments/assets/2c40f3c1-11a1-44a4-b602-e0d780c3af97

`Pixel 7`

https://github.com/user-attachments/assets/d31080d5-8967-4f07-a15d-a69207f703c9
