### ISSUE TITLE
[Icons]: Currently there are a lot of ways of specifying / overriding icons - we should reduce this.

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#41086]
There are still a lot of icons specified in `brave_icons.html`. Many of these are outdated (i.e. do not apply), overridden (there is a more specific override) or there is a newer version of the icon available in Nala.

We should remove these old icon overrides to consolidate on the Nala icons approach.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.85 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 2c872aa4d2694bc73ec58e3b14538a4008a6381e
OS | Windows 11 Version 23H2 (Build 22631.4391)
```
Verified the issue from the testplan https://github.com/brave/brave-core/pull/25577#issue-2528410278

When compared with `1.71.x` to `1.72.x, confirmed icons in the `brave://settings` menu have not changed.   
Info icon when editing a BYOM model should still be present (next to the labels on the inputs)

1.71.x | 1.72.x 
---- | -----
![Image](https://github.com/user-attachments/assets/e94ecf0f-4a54-4ea9-8800-3291f21ba487)|![Image](https://github.com/user-attachments/assets/e20e31bd-4499-4e17-ba8d-e43e3a31375b)
![image](https://github.com/user-attachments/assets/d8307048-f9d1-4b1f-941c-e0ac2f6b7f59)|![image](https://github.com/user-attachments/assets/2bea10e7-228e-4457-ba0a-4ed91b891c9d)
![Image](https://github.com/user-attachments/assets/a164b2c6-1254-4b86-b931-fe363609ed0a)|![Image](https://github.com/user-attachments/assets/280b49cd-e983-473a-91e0-7ac9fdb511f2)
