### ISSUE TITLE
Not all data stored when visiting a site is deleted when shredding the site

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#41095]
### Description

When a site is shredded, all first party data is removed but caches stored under different domains are not removed

### Steps to reproduce

1. Enable Shred feature flag if not enabled via `brave://flags`, then quit and relaunch the app.
2. Close all tabs
3. Tap `...`, then open Settings -> Shields settings -> Manage Website Data view
4. If there is data stored, tap `Remove All` to remove all data stored
5. In an open tab, visit `https://google.ca`
6. Tap `...`, then open Settings -> Shields settings -> Manage Website Data view
7. Observe 3 different websites storing data
8. Tap `Done` to close Manage Website Data, and close settings
9. Long-press on the tab tray button and select `Shred Site Data`
10. Tap `...`, then open Settings -> Shields settings -> Manage Website Data view
11. Observe `google.ca` website data is removed, but `google.com` & `gstatic.com` data is still there

### Actual result

https://github.com/user-attachments/assets/56d6a19b-6497-4668-a324-203a2d44f24c

### Expected result

--

### Reproduces how often

Easily reproduced

### Brave version

v1.69+ (note: Shred feature flag is disabled by default)

### Device/iOS version

Any

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

The Brave iOS `Manage Website Data` view [displays it's data](https://github.com/brave/brave-core/blob/master/ios/brave-ios/Sources/Brave/Frontend/Settings/Features/ShieldsPrivacy/ManageWebsiteDataView.swift#L79) using the [WKWebsiteDataStore.fetchDataRecords(ofTypes:completionHandler:)](https://developer.apple.com/documentation/webkit/wkwebsitedatastore/1532932-fetchdatarecords) API. This API does not allow retrieving which site stored the given data, so we are only able to remove the data whose `displayName` we can match to the site being Shred.

**Comment by kjozwiak** [comment]
@ShivanKaul added it into the `1.70.x` milestone as `release/blocking` for now. If you feel differently or we eventually think it's not, we can remove the label/remove it from the milestone.

**Comment by kjozwiak** [comment]
The above requires `1.71.112` or higher for `1.71.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7
Brave build: 1.71 (116)
BraveCore: 1.71.116 (130.0.6723.58)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41095#issue-2529688588 and https://github.com/brave/brave-core/pull/25744#issue-2559484804
2. *Verify*

**ACTUAL RESULTS:**
- Verified that all website data is deleted when `Shredding` using `Shred Site Data` in the `Tab switch` button.
- Verified all website data is deleted when using `Auto Shred` per site and globally (~30 secs delay). **NOTE: issue #40484 is still not fixed.**

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/b529d781-89e6-4ccb-9089-79e0ee5dd1ac) | ![2](https://github.com/user-attachments/assets/5adf512e-91b7-4784-adb1-48e388da9afe) | ![3](https://github.com/user-attachments/assets/431e1141-7ef0-41ff-9703-271e977368ab) | ![4](https://github.com/user-attachments/assets/86fecfbc-ab36-441d-a8ba-7cea90834355) |

https://github.com/user-attachments/assets/2761395f-89b3-494b-9c73-d1be52c1f90a
