### ISSUE TITLE
[ads] Served event is not triggered for Search ad for non-rewards users

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#41099]
### Description

Since the ad is not served then we don't sent view confirmations etc for non-rewards users

Important: This is a regression. Not reproducible in 1.69.x
Important: works as expected for rewards users

### Steps to reproduce

1. Clean profile
2. Run Browser
3. Restart Browser to apply variations
4. Open `https://search.brave.software/search?q=chainlink`
5. Check logs

### Actual result

Search ad is not served for non-rewards users

```
[11355:11355:0917/121837.300619:VERBOSE1:search_result_ad_event_handler.cc(53)] Search result ad: Not allowed to fire event
[11355:11355:0917/121837.301208:VERBOSE1:search_result_ad_event_handler.cc(227)] Failed to fire search result ad kServedImpression event for placement_id 85a61cfb-6dc8-4ddc-b958-591eedc5e2fe and creative instance id c2f2dace-d356-4bce-b5c9-cae75f2bd2aa
```

### Expected result

Search ad is served

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.70.114 Chromium: 129.0.6668.42 (Official Build) (64-bit)
-- | --
Revision | 62ac7fa937404b201bf90c3848127b18e9d7a9b1
OS | Linux

cc @tmancey @iambrianfung @aseren

**Comment by tmancey** [comment]
@btlechowski as discussed in DM, this is working as expected for non-Rewards users. We now only report minimum data as of part of https://github.com/brave/brave-browser/issues/38955
