### ISSUE TITLE
[Lit]: Migrate existing cr_overrides to lit

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#41098]
Chromium is in the process of migrating their cr_elements to Lit, so we should follow suit.

Test Plan
1. Buttons should still work on Settings page
2. Toggles should still work on the settings page

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.93 Chromium: 131.0.6778.14 (Official Build) beta (64-bit)
-- | --
Revision | 69e5dc20ca483a13316632df5bcd9279bb2a3cb7
OS | Windows 11 Version 23H2 (Build 22631.4391)
```

1. Installed 1.72.93
2. launched Brave
3. opened `brave://settings` and other pages as below

#### Confirmed buttons and toggles worked as expected in brave://settings pages 

brave://settings/getStarted|brave://settings/appearance|brave://settings/privacy|brave://settings/languages|brave://settings/system|brave://settings/autofill|brave://settings/content/automaticDownloads|brave://settings/extensions/v2
------- | -------- | -------- | -------- | -------- |------------|--------- | ---------
![Image](https://github.com/user-attachments/assets/0b69d954-7781-4f0d-95d0-add4b71e8446)|![Image](https://github.com/user-attachments/assets/23b629b6-2de7-4ed1-a329-c17a14667a47)|![Image](https://github.com/user-attachments/assets/41b10286-efda-4dce-8d14-60974581bc5f)|![Image](https://github.com/user-attachments/assets/afddacb0-c433-4b23-9207-be91cc204c5f)|![Image](https://github.com/user-attachments/assets/e3bcaa19-cc9f-4f30-98b0-ccb5b30c0101)|![Image](https://github.com/user-attachments/assets/1628bf55-2bbe-4e73-9a74-1b3e66dae7a5)|![Image](https://github.com/user-attachments/assets/6377d540-661a-4909-bf43-c1a1d38b63d0)|![Image](https://github.com/user-attachments/assets/1594d5e4-3907-4f50-b7b9-b9d73402bafe)
![Image](https://github.com/user-attachments/assets/b35dbe9d-62c3-4036-b59a-982acf6256d8)|![Image](https://github.com/user-attachments/assets/429e0faf-2f15-4196-a6f3-6c019c1df3c1)|![Image](https://github.com/user-attachments/assets/c8673191-f90e-49be-8871-cb06a39be025)|![Image](https://github.com/user-attachments/assets/b1529480-b0de-4c5a-822c-2a14b5cfc4df)|![Image](https://github.com/user-attachments/assets/18a4577e-ed5a-4564-95ec-a8909e832d41)|![Image](https://github.com/user-attachments/assets/ed9e8602-c70c-4ac8-990f-a823221273a7)|![Image](https://github.com/user-attachments/assets/a87fe5b7-a398-41b4-9a48-9ad64cb79469)|![Image](https://github.com/user-attachments/assets/601d5ed6-d98f-4452-97fc-b79afd55f0bc)
