### ISSUE TITLE
Settings: Social Media Blocking should be part of Shields section

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#4109]
## Description
Social Media Blocking is a shield, so should be inside Shields section. There is a desire to only fold this under once it's also controllable per-site in the toolbar shields controls.

## Designs
Designs for social media blocking per-site in the Shields panel TBA

Designs for social media blocking in Shields section, in Settings:
![shields w social media blocking option B](https://user-images.githubusercontent.com/2388823/56168069-ea281180-5f8e-11e9-8101-371b5108670e.png)

**Comment by karenkliu** [comment]
Added designs @tomlowenthal

**Comment by cjwijtmans** [comment]
i think it would be better to just have an icon tabs on the left. and then categorize under them as you wish. One icon would be shields icon and have the social media category among others.

**Comment by rebron** [comment]
Closing as fixed with https://github.com/brave/brave-browser/issues/32956
