### ISSUE TITLE
brave://history shows incorrect bookmark icon

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4110]
## Description 
When viewing your history on brave://history, if you've visited a bookmarked site, the brave://history page shows the star icon next to the visited page, not our bookmark icon.

## Steps to Reproduce

   1. Have some sites bookmarked.
   2. Visit at least one.
   3. View brave://history.

## Actual result:
Star icon shows next to the bookmarked page visited, not our bookmark icon.

![Screen Shot 2019-04-15 at 4 58 04 PM](https://user-images.githubusercontent.com/28145373/56165192-552e1400-5fa0-11e9-8597-5e5c20b5d991.png)

## Expected result:
Our bookmark icon is shown.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)
-- | --
Revision | e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}
OS | Mac OS X

Brave | 0.63.41 Chromium: 74.0.3729.61 (Official Build) beta(64-bit)
-- | --
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Mac OS X

### Reproducible on current release:
yes, reproduces on current release 0.62.51
- Does it reproduce on brave-browser dev/beta builds? yes, reproduced on beta 0.63.41

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by karenkliu** [comment]
Here's the icon!
[fill-bookmarked.zip](https://github.com/brave/brave-browser/files/3958508/fill-bookmarked.zip)

**Comment by srirambv** [comment]
Closing in favour of #6013 as it also has discussion about bookmark folders.
