### ISSUE TITLE
[Android] Advanced server selection follow up

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#41106]
## Description 

Based on the suggestions from guardian team and as a follow up to https://github.com/brave/brave-browser/issues/36277, we need to update existing changes to include `country` and `continent` variables in the Region. 
We also need to update the logic around the way we persist and identify selected region after an upgrade. 

## Test Plan :
Please follow the test plan mentioned in the main PR : https://github.com/brave/brave-core/pull/25089

**Comment by srirambv** [comment]
Marking as `QA/Blocked` as [#41477](https://github.com/brave/brave-browser/issues/41477) is known issue which is waiting on [#25604](https://github.com/brave/brave-core/pull/25604) to be uplifted

**Comment by kjozwiak** [comment]
The above requires `1.71.112` or higher for `1.71.x` verification 👍 The above can be verified alongside https://github.com/brave/brave-browser/issues/36277 once we start running through the VPN feature via `1.71.x`.

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240823.009 release-keys
Brave build: 1.71.112
Chromium: 130.0.6723.44 (Official Build) (64-bit) 
```
------------------------

<details>
<summary> "Automatic" server location </summary>

**STEPS:**
1. Buy an IAP subscription on a fresh profile
2. Create a VPN profile
3. Turn on VPN
4. Go to the `Server selection` page
5. *Verify that `Automatic` must be selected*

**ACTUAL RESULTS:**
- Verified that `Automatic` location is selected by default when enabling VPN

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/1538e56d-de4d-4c11-87b1-ded3c25fe357) | ![2](https://github.com/user-attachments/assets/ea723083-4064-4631-b291-09b7a8c9f41f) | ![3](https://github.com/user-attachments/assets/a5a6885c-fdb7-4d3f-8261-9ba625d781e0) |
| ![1](https://github.com/user-attachments/assets/51b1501b-2b96-434a-af7f-e26f7227c1f9) | ![2](https://github.com/user-attachments/assets/306e67cf-189d-4e02-a1c7-81d9d994d0e1) | ![3](https://github.com/user-attachments/assets/a1c11161-7ff4-45cd-9a88-1a5aa55b96dc) |
</details>

<details>
<summary> "Optimal" server location from the selected region </summary>

**STEPS:**
1. Go to `Server selection` page
2. Disable `Automatic` toggle switch > *Verify that your region (USA in my case) is selected by default*
3. Select the `USA` as a region
4. On the next page, select `Optimal`
5. *Verify that the `Best` server location would be selected and it could give a different location based on the available resources on the location at the time*

**ACTUAL RESULTS:**
- Verified that your region (USA in my case) is selected by default after disabling the `Automatic` toggle switch.
- Verified that the `Best` server location must be selected when tapping on `Optimal`, and it could give a different location based on the available resources at the time.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/19f557b8-238a-4ad4-ab2b-d393de9ea602) | ![2](https://github.com/user-attachments/assets/40581b1c-5b9b-420a-95a2-b5ce63ab816f) | ![3](https://github.com/user-attachments/assets/00ce6a72-e170-4898-8016-53dd4cf824e5) |
| ![1](https://github.com/user-attachments/assets/d35ca82d-4605-4f1d-8a35-f83443593cd0) | ![2](https://github.com/user-attachments/assets/38a7fd1d-352a-4cbd-95ca-512d15f4225d) | ![3](https://github.com/user-attachments/assets/18aa2675-c010-493c-bd98-2009cf4ec547) |
</details>

<details>
<summary> "Specific" server selection </summary>

**STEPS:**
1. Go to `Server selection` page
2. Select the `USA` as a region
3. On the next page, select `Atlanta`
4. *Verify that `Atlanta` must be selected as server location*

**ACTUAL RESULTS:**
- Verified that a `specific` city/server must be selected as server location when tapping the `city` name.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/99b1c755-11df-45a7-9a19-e5a5036b7371) | ![2](https://github.com/user-attachments/assets/ae451a57-7b77-42b8-b7f1-e09e5a6d35b0) | ![3](https://github.com/user-attachments/assets/6f56394c-49fd-4975-afc1-f3e3a4eed2de) | ![4](https://github.com/user-attachments/assets/7fd4e583-8e7a-497e-8b3e-96670d688423) |
</details>

<details>
<summary> "Upgrade" scenario </summary>

**STEPS:**
1. Install and launch Brave `1.70.123` > Purchase/enable VPN > *Verify `VPN` server selection screen UI*
2. Upgrade Brave to `1.71.112` > Enable VPN >  Go to the `Server selection` page
3. *Verify that the `Selected` region from the previous version must be selected in the new UI*
4. Tap on the region
5. *Verify that `Optimal` must be selected as we didn't have a granular details from the previous version. A new version of the app would follow the new changes moving forward.*

**ACTUAL RESULTS:**
- Verified that `Automatic` is NOT selected after Brave `upgrade.`
- Verified that the previously selected region is still selected after Brave `upgrade`.
- Verified that the `Optimal` server location is selected by default after Brave `upgrade as we didn't have granular details from the previous version. A new version of the app would follow the new changes moving forward.`
- Verified that multiple `radio buttons` can't be selected at the same time

---------------------------

|Before `upgrade`|After `upgrade`|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/58a32a3e-5b8b-423c-991a-b66e626de400) | ![2](https://github.com/user-attachments/assets/efe552c0-68ce-4591-b7ad-d7c9030715c2) |
| ![1](https://github.com/user-attachments/assets/e094fdce-7bf1-4aa5-bd95-a23b64a2de51) | ![2](https://github.com/user-attachments/assets/7d89740c-6ff9-4a16-a47f-9dfc1ad16b38) |
| ![1](https://github.com/user-attachments/assets/461751bf-5b70-4cd9-b2d0-5c1b241d18bb) | ![2](https://github.com/user-attachments/assets/f193570e-e17e-4e94-b45b-590796835914) |
| ![1](https://github.com/user-attachments/assets/bf1ef134-4f65-49bf-9464-0757e7993c64) | ![2](https://github.com/user-attachments/assets/6214c8aa-e43c-4a9c-9f53-e38a593ba914) |
</details>
