### ISSUE TITLE
brave://crash does not crash tab

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4111]
## Description 
On C74 versions of Brave, brave://crash does not work to crash a tab. chrome://crash however, does work.

## Steps to Reproduce

   1.  Open a tab.
   2. Navigate to brave://crash --> nothing happens, NTP remains dashboard
   3. Change URL to be chrome://crash --> tab crashes

## Actual result:
brave://crash does not crash the tab

## Expected result:
brave://crash should crash the tab

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.63.41 Chromium: 74.0.3729.61 (Official Build) beta(64-bit)
-- | --
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Mac OS X

Brave | 0.64.47 Chromium: 74.0.3729.61 (Official Build) dev(64-bit)
-- | --
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Mac OS X

Brave | 0.65.56 Chromium: 74.0.3729.75 (Official Build) nightly(64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Mac OS X

### Reproducible on current release:
no, does not reproduce on 0.62.51 Release version
- Does it reproduce on brave-browser dev/beta builds? yes, reproduces on dev/beta

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
reproduced by @kjozwiak on macOS and Win

Also, when navigating to chrome://crash, the URL bar will show brave://crash, but directly going to brave://crash does not work.

**Comment by kjozwiak** [comment]
CCing @rebron @bbondy. We might want to get this fixed before `0.63.x` goes out the door. Seems like a CR74 regressions.

**Comment by bsclifton** [comment]
Using Nightly version 0.65.56, I noticed that:
- works as expected if you go to `chrome://crash`
- shows a blank screen if you go to `brave://crash`

**Comment by LaurenWags** [comment]
interesting, @bsclifton - I'm not seeing a blank screen when navigating to brave://crash, it just continues to show my dashboard (on beta, dev, nightly). chrome://crash works as expected for me (and also shows brave://crash in the URL bar)

**Comment by btlechowski** [comment]
Reproduced on

Brave | 0.63.42 Chromium: 74.0.3729.75 (Official Build) beta(64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Ubuntu 18.04 LTS

**Comment by GeetaSarvadnya** [comment]
Reproduced on


Brave | 0.63.40 Chromium: 74.0.3729.61 (Official Build) beta (64-bit)
-- | --
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Windows 10 OS Build 17134.523

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.64.68 Chromium: 74.0.3729.108 (Official Build) beta (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Windows 10 OS Build 17134.523

- Verified the STR mentioned in the issue
- Encountered https://github.com/brave/brave-browser/issues/1299
