### ISSUE TITLE
Update source for search suggestions

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#41112]
## Description 

We need to update the source for search suggestions  similar to source attached to searches. Currently we have `source=browser` for all platforms. In this issue, we need to update `source=android` for android and `source=desktop` for desktop.

For more ref : https://bravesoftware.slack.com/archives/C0816QH3R/p1726178343456589

**Comment by deeppandya** [comment]
CC @rebron for the visibility

**Comment by bsclifton** [comment]
Whoops - this should have bumped the version for this variable so that existing users would pick up the change:
https://github.com/brave/brave-core/blob/4dcfd49384d5b77eafc1f7f4a3a8b9781ad6139e/components/search_engines/brave_prepopulated_engines.cc#L16

**Comment by LaurenWags** [comment]
Requires 1.71.103 or higher for verification 👍🏻

**Comment by MadhaviSeelam** [comment]
Verification `In Progress` using
```
Brave | 1.71.111 Chromium: 130.0.6723.31 (Official Build) (64-bit)
-- | --
Revision | a39f12f230248c726d3f1cac2d59dd4dcac714d7
OS | Windows 11 Version 23H2 (Build 22631.4317)
```

1. Installed 1.71.111 
2. launched Brave
3. opened Fiddler to track network traffic.
4. relaunched Brave
5. verified Brave is default SE for my default location (i.eUnited States)
6. open NTP
7. In the omnibox, started typing a search term (eg. milton)
8. confirmed in Fiddler that the search suggestions API URL contains source=desktop
9. opened another NTP
10. In the search widget, started typing a search term
11. confirmed in Fiddler that the search suggestions API URL contains source=desktop

step 5 | step 7 | step 8 | step 10 | step 11
----- | ---- | ---- | ----- | -----
![Image](https://github.com/user-attachments/assets/09fd1a9a-8b9c-4447-981c-ab89cd79662f)|![Image](https://github.com/user-attachments/assets/433056fb-9a73-45b2-b607-4a86377e89b0)|![Image](https://github.com/user-attachments/assets/1d3943e4-818a-4b1f-80cb-c5dbd7e4aac7)|![Image](https://github.com/user-attachments/assets/00eedbcc-ddf2-4ec9-8605-4e9d81aef778)![Image](https://github.com/user-attachments/assets/20dceb11-6ef1-4015-bde8-fbf05197db35)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.71.111 Chromium: 130.0.6723.31 (Official Build) (64-bit) 
Revision	a39f12f230248c726d3f1cac2d59dd4dcac714d7
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

<details><summary>New user (Brave Search default)</summary>

1. New install (US)
2. Enter search term in omnibox
3. Monitor search.brave.com using proxy

- Ensured search suggestions URL contains query components `&source=android`

![Image](https://github.com/user-attachments/assets/7415d94f-06ab-4c57-919a-f582462bcd2c)

</details>

<details><summary>New user (Non-Brave Search initial, change to Brave Search)</summary>

1. New install
2. Confirm Brave is not default SE (Singapore)
3. Change SE to Brave Search
4. Enable search suggestions
5. Enter search term in omnibox
6. Monitor search.brave.com using proxy
- Ensured search suggestions URL contains query components `&source=android`

![Image](https://github.com/user-attachments/assets/4e869ba3-53a2-4015-a8d9-a0dc58381eaf)

</details>

<details><summary>Existing users (Brave Search default)</summary>

1. Install 1.70 (US)
2. Upgrade to 1.71.112
3. Enter search term in omnibox
4. Monitor search.brave.com using proxy

- Ensured search suggestions URL contains query components `&source=android`

![Image](https://github.com/user-attachments/assets/ee980278-75f5-4843-8615-075766ee41cd)

</details>

<details><summary>Existing users (Non-Brave Search initial, change to Brave Search)</summary>

1. Install 1.70 (Singapore)
2. Upgrade to 1.71.112
3. Change default SE to Brave
4. Enable search suggestions 
5. Enter search term in omnibox
6. Monitor search.brave.com using proxy
- Ensured search suggestions URL contains query components `&source=android`

![Image](https://github.com/user-attachments/assets/bb10d9e8-77a2-4719-ba6e-71bc05ac879e)

</details>
