### ISSUE TITLE
[Wallet/iOS]: Wallet: BraveWalletTransactionType enum string value

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#41116]
Duplicate issue of https://github.com/brave/brave-browser/issues/40336 for iOS.

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 18.1.1 running 1.74 (94)
- Verified steps from [brave/brave-core#25624](https://github.com/brave/brave-core/pull/25624)
- Verified Function type is shown as mentioned in the test plan

Send ETH | ERC20 Approval | ERC721 Safe Transfer | ERC20 Token Transfer
-- | -- | -- | --
![Image](https://github.com/user-attachments/assets/7d3aa328-326d-4289-905d-5b8043434db4) | ![Image](https://github.com/user-attachments/assets/1d0ff22f-5e7a-4d00-b4a3-faeddbb25e52) | ![Image](https://github.com/user-attachments/assets/f8103218-1036-4bd5-9c04-94d9294c1e06) | ![Image](https://github.com/user-attachments/assets/edd5e19e-aa6c-47f3-b2de-5c98417cc06a)


SOL Swap | Send SOL | SOL Compressed NFT Transfer
-- | --  | --
![Image](https://github.com/user-attachments/assets/e130b7d6-364e-4a90-97b6-45dff9803dcb) | ![Image](https://github.com/user-attachments/assets/82f0bef2-1fdd-4905-9e56-e3b556ff7b8a) | ![Image](https://github.com/user-attachments/assets/a355f020-e9ff-4234-b786-65450175edd3)
