### ISSUE TITLE
Picker layouts in settings screens are incorrect on iOS 18 SDK builds

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#41114]
Certain settings screens are showing menu pickers underneath the labels instead of on the trailing edge but only when built with iOS 18

![image](https://github.com/user-attachments/assets/2b76e4a6-d633-4e23-ad41-1a1a1da54d7d)
![image](https://github.com/user-attachments/assets/b9f2a83a-a7ea-4377-9c48-6b1207f75e43)

**Comment by kjozwiak** [comment]
The above requires `1.70.118` or higher for `1.70.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPad Mini (6th gen)` using version(s):
```
Device/OS: iPad Mni (6th gen) / iPadOS 18
Brave build: 1.70 (126)
BraveCore: 1.70.126 (129.0.6668.100)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/25617#issuecomment-2364586959
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `menu pickers` are shown on the trailing edge of the labels.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/1de8d580-f8f4-4a21-be20-1dc08cd2d39a) | ![2](https://github.com/user-attachments/assets/9540abf0-a8e8-4b47-a271-57c28da44124) | ![3](https://github.com/user-attachments/assets/ae4dceeb-f94a-46e2-97dd-553dd5376973) |
