### ISSUE TITLE
Remove Google Lens from `View menu` on macOS

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#41117]
### Description

In latest beta, 1.71.88 Chromium: 129.0.6668.42, there's an `Always show Google Lens shortcut` menu item on macOS. 
That menu item should be removed.

### Steps to reproduce

1. Install 1.71.88 Chromium: 129.0.6668.42 or higher on macOS
2. Open View menu.
3. Notice Google Lens menu item

### Actual result

<img width="347" alt="Screenshot 2024-09-17 at 8 14 14 PM" src="https://github.com/user-attachments/assets/555d4879-7e00-41c4-b386-b58c8def1742">

### Expected result

No menu item for Google Lens.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.71.88 Chromium: 129.0.6668.42

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` label until this is uplifted.

**Comment by kjozwiak** [comment]
The above requires `1.70.117` or higher for `1.70.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.70.117 Chromium: 129.0.6668.59 (Official Build) (x86_64)
-- | --
Revision | 5d4da8332eb061f79bb47ec5b0bf595600fdcd55
OS | macOS Version 14.6.1 (Build 23G93)
```
