### ISSUE TITLE
Clean up and improve transaction fragment implementation

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#41122]
![image](https://github.com/user-attachments/assets/e223828a-3cfe-43de-b74b-e72c90d50c61)

## Description

Prepare transaction fragment `ApproveTxBottomSheetDialogFragment` for UI overhaul.

🎨 Main Figma design: https://www.figma.com/design/26xCR66ZscSyVpTKrt85Hn/Transactions?node-id=730-324167&node-type=canvas&m=dev

- [ ] Remove unused classes, styles, and methods.
- [ ] Refactor code to make it easier to maintain and to read
- [ ] Adjust window flags and allow dialog sliding smoothly without flickering
- [ ] Increase bottom sheet dialog height
- [ ] Change logic to show transaction fragment without overlapping Wallet panel

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 15 running 1.72.96 x64 Beta build
- Verified steps from [brave/brave-core#25628](https://github.com/brave/brave-core/pull/25628)
- Verified closing transaction confirmation screen renders smoothly
- Verified panel opens when closing transaction confirmation screen

https://github.com/user-attachments/assets/3b8bfa64-eb34-449a-af3b-c1fe4883772f
