### ISSUE TITLE
[Material UI]: Rorange button outline in devtools

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#41128]
Slack thread where @AlanBreck found the issue:
https://bravesoftware.slack.com/archives/C01EVLWS8R5/p1726626360304599

Steps to repro:
1. Go to a site
2. Open dev tools
3. Open the application tab

Expected:
Clear site data button is not rorange

Actual
Clear site data button is rorange

![image](https://github.com/user-attachments/assets/df945224-6c13-441b-88c7-75ccb1aff934)

Until we fix the secondary colors in Nala the only way we can fix this is a patch of the devtools source, as it manually sets all of the `-sys-` colors.

See https://github.com/brave/leo/issues/838 for the issue in Nala

I've split this off from https://github.com/brave/brave-browser/issues/41125 because I think the fix is going to be slightly more controversial.

**Comment by LaurenWags** [comment]
Requires 1.71.91 or higher to verify 👍🏻

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.96 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | 6dc1837bd07e6dacd8b6b7b5d9f27e7bb09b5eb5
OS | Windows 11 Version 23H2 (Build 22631.4169)
```

Installed 1.71.96
launched Brave
opened nytimes.com
opened dev tools
opened the application tab


Confirmed Clear site data button outline is not `Rorange`

light | dark
---- | -----
![image](https://github.com/user-attachments/assets/4c82aa4d-1fc3-447d-827c-a8369f8040e2)|![image](https://github.com/user-attachments/assets/3b8d3e5d-9308-4048-92cb-c1f8f1991488)
