### ISSUE TITLE
Refactor wallet's hardware signing code

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#41121]

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.72.96 Chromium: 131.0.6778.24 (Official Build) beta (64-bit)
-- | --
Revision | 10f472615a5ea2cccb71ffc48639efbaef71b801
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from [brave/brave-core#25386](https://github.com/brave/brave-core/pull/25386)
- Verified Adding HW accounts for Ledger/Trezor for ETH, SOL, FIL works as expected
- Verified Transaction signing with Ledger for ETH, SOL, FIL works as expected
- Verified Message signing with Ledger for ETH work as expected
- Verified Transaction signing with Trezor for ETH work as expected
- Verified Message signing with Trezor for ETH work as expected
- Encountered [#42115](https://github.com/brave/brave-browser/issues/42115) & [#42116](https://github.com/brave/brave-browser/issues/42116)
