### ISSUE TITLE
some buttons still have orange ring/outline on dark theme

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#41125]
### Description

When using dark theme, some buttons still have an orange ring/outline. This orange ring/outline is not there in light theme.

Per discussion via https://bravesoftware.slack.com/archives/C01EVLWS8R5/p1726641052480589?thread_ts=1726626360.304599&cid=C01EVLWS8R5 there shouldn't be any orange.

Also found by @AlanBreck as well 👍🏻 

### Steps to reproduce

1. Be sure you are using dark theme (`brave://settings/appearance` > Brave Colors > Dark)
2. Open brave.com in a tab
3. Open a new tab
4. Type "brave." in the URL bar
5. In the drop down you will see an entry for brave.com with a button that says "Switch to this tab", this button has an orange ring/outline
6. In the URL bar erase what you've written and type ":br"
7. In the drop down you will see an entry that has a "Search Brave" button, this button has an orange ring/outline
8. If you repeat the above with light theme, there's no orange

(note, my step 6 and 7 have different button text in the screenshots below, but the premise is the same)

### Actual result

Dark has orange, light does not

Dark | Light
--- | ---
<img width="504" alt="1 72 6a" src="https://github.com/user-attachments/assets/303e7156-2421-4cd4-993f-8b79f9c50d7f"> | <img width="447" alt="1 72 a-lt" src="https://github.com/user-attachments/assets/04079052-7423-4cd7-bb2d-21c80392d651">
<img width="740" alt="1 72 6b" src="https://github.com/user-attachments/assets/5b32d2fd-6b71-4314-afac-d67c0746d186"> | <img width="755" alt="1 72 b-lt" src="https://github.com/user-attachments/assets/8002cb8b-c5d8-4b18-b449-02ad8daa6f07">

### Expected result

No orange in dark theme

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.72.6 Chromium: 129.0.6668.42 (Official Build) nightly (x86_64)
-- | --
Revision | 2071656859878e424523b78457dc7a21d7f8d01c
OS | macOS Version 14.6.1 (Build 23G93)

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Beta (1.71.x) and Nightly (1.72.x) have this issue, RC (1.70.x) does not:

1.70.114 Dark | 1.70.114 Light
--- | ---
<img width="966" alt="1 70 115" src="https://github.com/user-attachments/assets/182d416b-9782-4647-a75c-d1bf750b2864"> | <img width="742" alt="1 70 115-lt" src="https://github.com/user-attachments/assets/a698cb56-3dd5-4ce5-bf42-17b17a7245bb">

**Comment by LaurenWags** [comment]
cc @rebron

**Comment by fallaciousreasoning** [comment]
@aguscruiz I think we should fix this by making the secondary color look less jarring next to the primary color - until them, I'm just going to make the TonalOutline the primary scheme, which is similar to what we do in Nala

However, I don't really see the point in our secondary colors if we can't use them.

**Comment by MadhaviSeelam** [comment]
Reproduced the issue in Win 11 x64 
```
Brave | 1.72.6 Chromium: 129.0.6668.42 (Official Build) nightly (64-bit)
-- | --
Revision | 2071656859878e424523b78457dc7a21d7f8d01c
OS | Windows 11 Version 23H2 (Build 22631.4169)
```
dark | light 
----- | ----
![image](https://github.com/user-attachments/assets/2ffcf146-22c6-4ee7-84af-faff4de4c04a)|![image](https://github.com/user-attachments/assets/4590558a-5307-4bec-8bd4-392c4f8c1dfe)

**Comment by kjozwiak** [comment]
The above requires `1.71.96` or higher for `1.70.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.96 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | 6dc1837bd07e6dacd8b6b7b5d9f27e7bb09b5eb5
OS | Windows 11 Version 23H2 (Build 22631.4169)
```

1. Installed 1.71.96
2. launched Brave
3. opened `brave://settings/appearance` in a new tab
4. selected `Dark` from Brave colors dropdown menu
5. Opened brave.com in a tab
6. Opened a new tab
7. Typed "brave." in the URL bar
8. In the URL bar typed ":br"
9. in the URL Bar, typed "pull"


Note: opened `brave://settings/manageProfile` and used different themes in light and dark modes

- Confirmed using dark theme, some of the buttons no longer show an orange ring/outline.
- Verified buttons don't show orange/outline in light theme as expected.

Light | dark 
---- | ---
![image](https://github.com/user-attachments/assets/68cd196e-1dd2-42c9-bf0f-c466fc9f509f)|![image](https://github.com/user-attachments/assets/b5fd3dc7-5930-4972-bc47-089712b132df)
![image](https://github.com/user-attachments/assets/7e3ac783-3e6e-4df7-8cc3-2e56416b0691)|![image](https://github.com/user-attachments/assets/ac2a28bc-6058-44f6-9067-26fcee43afb4)
![image](https://github.com/user-attachments/assets/eca680f0-99d0-42ea-b07e-3a66706067d9)|![image](https://github.com/user-attachments/assets/867c506b-a38e-4c89-bba3-c7d0b94a30b2)
