### ISSUE TITLE
Add Dark mode icon for IOS dark mode

### ISSUE THREAD

**Issue by jasonwitty** [brave/brave-browser#41129]
### Description

IOS 18 includes a feature to enable dark mode icons but the brave browser does not currently support this feature, the lion head is still featured on a white background.

### Steps to reproduce

1. pin brave brower launch icon to dock
2. upgrade to ios 18
3. enable dark icons by pressing on desktop and choosing customize

### Actual result

lion head is still featured on a white background.

### Expected result

lion head is still featured on a dark background.

### Reproduces how often

Easily reproduced

### Brave version

1.69.7 (171)

### Device/iOS version

IOS18

### Affected browser versions

- [X] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kylehickinson** [comment]
Duplicate of https://github.com/brave/brave-browser/issues/41088
