### ISSUE TITLE
Brave feedback component

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#4112]
Brave needs a UI component to be able to solicit feedback on our various features (in particular if it is in beta) at the moment the user is using the feature. Since we are a privacy protecting browser and don't collect user data, we need to give the average user a way to express feedback so we can be more diligent about making well-informed updates.

**Comment by rebron** [comment]
cc: @alexwykoff 
@rossmoody Chrome and MS Edge (Canary) have good examples.
