### ISSUE TITLE
Highlighted font on customize dashboard screen is blurry/fuzzy on 1080p screens

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#41131]
### Description

The font for the highlighted category on the NTP `Customize dashboard` page appears "blurry" when viewed on normal HD screens. When viewed on my macOS UHD screen, the text looks sharp and clear.

How it appears from my 1080p monitor:
![image](https://github.com/user-attachments/assets/705cd4c7-ba9c-49c8-9e85-262d80922013)

How it appears on my macOS UHD screen:
<img width="719" alt="image" src="https://github.com/user-attachments/assets/61ee056a-a310-4faf-afc3-712cabd0a357">

### Steps to reproduce

Open `Customize dashboard` screen

### Actual result

-

### Expected result

-

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.69.168

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment]
cc: @aguscruiz

**Comment by aguscruiz** [comment]
Had a couple working theories as to what may be the cause of the issue here, but I don't know if it's accurate until we try it out.

https://bravesoftware.slack.com/archives/CKNHM4RTK/p1726760057127619?thread_ts=1726605411.825719&cid=CKNHM4RTK

cc
@fallaciousreasoning

**Comment by fallaciousreasoning** [comment]
This seems to be caused because we're setting the text color to a gradient

**Comment by aguscruiz** [comment]
We should be using blurple for this navigation anyways, so it's ok to change

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.90 Chromium: 130.0.6723.70 (Official Build) beta (64-bit)
-- | --
Revision | 5f14a2225ebf4fcd654e064bde93e77fcc5d8f39
OS | Windows 11 Version 23H2 (Build 22631.4391)
```

Verified using the STR from the description https://github.com/brave/brave-browser/issues/41131#issue-2534193033

#Confirmed no blurry font is shown in the customize dashboard screen


example | example | example 
------ | ------ | -----
![Image](https://github.com/user-attachments/assets/08f49672-a61c-4527-80df-c5e38f16b1fa)|![Image](https://github.com/user-attachments/assets/dc0ef5cb-b992-44d2-be6d-3244e6f8b73a)|![Image](https://github.com/user-attachments/assets/fba669b0-61e3-49e4-b680-04fe9f910cbd)
