### ISSUE TITLE
Allow to disable history

### ISSUE THREAD

**Issue by astier** [brave/brave-browser#4113]
## Description 

The browsing-history is always stored. I personally prefer never to store my browsing history for privacy-reasons but also because I never found it useful.

## Expected result:

There should be an option in the settings which allows to disable the browsing-history completely.

## Brave version (brave://version info)

brave-bin-0.62.51 from the AUR on Arch Linux.

**Comment by srirambv** [comment]
You can set browser to always launch private window by adding the `--incognito` flag to the startup. Normal windows will have history when you browse.

**Comment by astier** [comment]
@srirambv my objection to the incognito mode is that in incognito mode no cookies will be used and saved. I need to use cookies and be able to disable history at the same time.

**Comment by bsclifton** [comment]
@astier in that case, I believe you can use the `Clear browsing data on exit` feature that we'll be introducing with our next release, 0.63.x. Per our release schedule, we're shooting for a release next week. This feature is already live in the Beta, Dev, and Nightly channels

Basically, you go to brave://settings/clearBrowserData and then you can choose what you want deleted on exit (for regular tabs; as you've noted, private tabs already clear this info)
<img width="559" alt="Screen Shot 2019-04-16 at 2 18 07 PM" src="https://user-images.githubusercontent.com/4733304/56244755-8cf59400-6052-11e9-9cba-8e6e74786a09.png">

**Comment by astier** [comment]
Thank you. I will try it.
