### ISSUE TITLE
Don't display "Brave Menu" nudge/bubble in certain cases

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#41133]
### Description

<img width="1205" alt="Screenshot 2024-09-18 at 15 15 57" src="https://github.com/user-attachments/assets/060b695f-c79d-4c2e-9a67-239eeb469b1a">

1. can this dialog be made to respect `--disable-infobars` or `--disable-notifications` or some similar runtime flag, to avoid coming up with tests
2. similarly, could this be disabled if Brave is being run via automation?

also, more broadly, can the same change(s) be made to any other Brave notifications / bubbles?

### Steps to reproduce

1. start brave in a new profile 

### Actual result

1. bubble came up

### Expected result

no bubble should have come up

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

all

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by Brave-Matt** [comment]
Not sure if helpful but thees bubbles pop up for "inactive tabs" (if `Memory saver` is enabled) as well:

<img width="420" alt="image" src="https://github.com/user-attachments/assets/6ae824b7-6f31-450f-8b8d-333d714e7592">

![image](https://github.com/user-attachments/assets/c4e0a46b-888c-420b-8d91-b2d2d73f552d)
