### ISSUE TITLE
[iOS] - User cannot cancel history deletion

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#41148]
### Description

- Attempt to delete all history
- No way to cancel the alert once it pops up.
![image](https://github.com/user-attachments/assets/910e1bf8-2267-4ada-9765-ea5b38e2e003)

### Steps to reproduce

- Attempt to delete all history
- No way to cancel the alert once it pops up.

### Actual result

Cannot dismiss delete. Must kill the app.

### Expected result

- Should allow user to cancel deleting all history

### Reproduces how often

Easily reproduced

### Brave version

N/A

### Device/iOS version

Any

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.71.116` or higher for `1.71.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18` using version `1.71.118`

* Ensured that `Clear Browsing History` dialog has option to cancel. 
* Ensured clearing history still works. 
* Ensured that tapping on `Cancel` will dismiss action and not delete. 

`example` | `example`
---|---
![Image](https://github.com/user-attachments/assets/d7e66059-11f5-4f63-b7db-abc9e418ceea) | ![Image](https://github.com/user-attachments/assets/66ed0a66-0f61-493f-83f6-fd9095d30915)
