### ISSUE TITLE
Leo panel stuck in open state

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#41154]
### Description

https://github.com/user-attachments/assets/1d2d4a7e-aefe-4a8a-a8a3-57c896760e49

### Steps to reproduce

1. Have at least two tabs
2. On tab A, open Leo panel and close the tab
3. On tab B, Leo panel can’t be opened
4. Open new tab, Leo panel can’t be opened

### Actual result

Leo panel indicator shows it is open on other tab.

### Expected result

Leo panel can be opened/closed on other tab with correct open indicator 

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.72.22 Chromium: 129.0.6668.59 (Official Build) nightly (x86_64)
-- | --
Revision | a2054d5f1e83d781a52e1baee7a2f3307250c1d6
OS | macOS Version 14.7 (Build 23H124)

### Channel information

- [x] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information
This effect persists unless I use a new browser window or use toolbar Leo button to toggle on and off

**Comment by MadhaviSeelam** [comment]
Reproduced the issue as well in Win 11 x64
```
Brave | 1.72.22 Chromium: 129.0.6668.59 (Official Build) nightly (64-bit)
-- | --
Revision | a2054d5f1e83d781a52e1baee7a2f3307250c1d6
OS | Windows 11 Version 23H2 (Build 22631.4169)
```

**Comment by MadhaviSeelam** [comment]
However this is still an issue in current release 1.70.117 if Leo icon is clicked via Sidebar.  No issues with Leo icon on the toolbar
```
Brave | 1.70.117 Chromium: 129.0.6668.59 (Official Build) (64-bit)
-- | --
Revision | 5d4da8332eb061f79bb47ec5b0bf595600fdcd55
OS | Windows 11 Version 23H2 (Build 22631.4169)
```


https://github.com/user-attachments/assets/011bbf59-61d9-41ee-b48d-04ce2082f41a

**Comment by LaurenWags** [comment]
Requires 1.72.89 or higher for verification 👍🏻

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.73.86 Chromium: 131.0.6778.39 (Official Build) (64-bit)
-- | --
Revision | 52163bcf4e40f27ddb76ffa79c90a8833084a9bd
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from issue description
- Verified Leo button and sidebar panel shows correct state when closing tabs and reopening Leo
 
https://github.com/user-attachments/assets/27aa32c5-c45e-481c-8f80-c160827e7af9
