### ISSUE TITLE
Insufficient funds message immediately after auto contribution

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#4115]
The original issue is described in Android repo https://github.com/brave/browser-android-tabs/issues/1465. Not sure is it appeared on desktop, but it is likely.

**Comment by LaurenWags** [comment]
Is a regression test of contribution sufficient or are there additional scenarios QA should cover? If no manual QA is needed, can we mark as QA/No?

**Comment by SergeyZhukovsky** [comment]
Hey @LaurenWags I believe we checked that on Android repo, not sure was it a problem ever on desktop. So marking it as QA/No.

**Comment by LaurenWags** [comment]
thanks @SergeyZhukovsky 😄
