### ISSUE TITLE
`Connect` button flickering once when goes to vpn server selection panel

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#41161]
### Description

`Connect` button should shown only when hovered over the region entry.

https://github.com/user-attachments/assets/983a93b3-8ef1-4aec-b176-b0fb3dce7872

### Steps to reproduce

1. Setup brave vpn as purchased state
2. Launch vpn panel and go to server selection panel
3. 

### Actual result

Some `Connect` button is shown once and disappeared.

### Expected result

`Connect` button should not be visible after going to server selection panel

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.71.90 Chromium: 129.0.6668.59 (Official Build) beta (arm64) 

### Channel information

- [ ] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @brave/qa-team

**Comment by simonhong** [comment]
Fixing now.

**Comment by kjozwiak** [comment]
The above requires `1.71.110` or higher for `1.71.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` 
```
Brave | 1.71.110 Chromium: 129.0.6668.100 (Official Build) beta (64-bit)
-- | --
Revision | 46cd0b1af7127687895fcaceff93dd80e29e6f2b
OS | Windows 11 Version 23H2 (Build 22631.4317)
```

Verified using STR from https://github.com/brave/brave-browser/issues/41161#issue-2537668573

Confirmed `Connect` button is shown only when hovered over the region entry.

https://github.com/user-attachments/assets/12c90387-825a-4cf3-8e53-2eeff1e73e86
