### ISSUE TITLE
"Screen share" button not displayed during Zoom conference call in Brave

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#41175]
### Description

The `Screen sharing` option for Zoom calls is not displayed. Tested on Windows and macOS. Shields up/down does not have any effect. When testing in Chrome, screen sharing option appears as expected:

Available options for Zoom call in Brave:
![image](https://github.com/user-attachments/assets/518488fe-3af2-458e-887d-83c792206c7e)

Available options for Zoom call in Chrome:
![image](https://github.com/user-attachments/assets/6cca30f0-205e-4168-bd5a-54e2da48271f)

### Steps to reproduce

1. Launch in-browser Zoom call
2. Observe that the Share Screen button does not appear

### Actual result

Share screen button not shown

### Expected result

Share screen button should appear as it does in Chrome and other browsers.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

v1.70.117 and higher

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

User report:
https://community.brave.com/t/cannot-screenshare-in-zoom-when-using-brave/569361

**Comment by McBruno712** [comment]
This is still an issue, even with Brave Shields off.

**Comment by ShivanKaul** [comment]
Can you test with Shields on? And send a screenshot
