### ISSUE TITLE
Tinted mode not working for some Brave widgets [iOS 18]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#41178]
### Description

Apart from the single `Top News` Brave widget, the tinted mode is not applied.

### Steps to reproduce

1. New Install
2. Go to home screen
3. Place some Brave Widgets to the home screen
4. Long press on home screen, select `Edit` button at top left
5. Select `Customize`
6. Select `Tinted` in the bottom panel
7. Observe widgets

### Actual result

example | example
-|-
![IMG_7419](https://github.com/user-attachments/assets/c2b66a25-7ac1-4f3d-8f81-957c75c66898) | ![IMG_7420](https://github.com/user-attachments/assets/1ec52ce7-84a7-43c2-a157-2b7cafc186d6)

### Expected result

Tinted mode should be applied

### Reproduces how often

Easily reproduced

### Brave version

1.72 (72)

### Device/iOS version

iPhone / iOS 18

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kylehickinson** [comment]
I was able to fix all widgets except the top news widget (that has an image in the background), currently there is no way to not have this tinted using the available APIs from Apple

**Comment by hffvld** [comment]
Verified on `iPad Mini (6th gen)` using version(s):
```
Device/OS: iPad Mni (6th gen) / iPadOS 18
Brave build: 1.70 (123)
BraveCore: 1.70.123 (129.0.6668.89)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41178#issue-2539772428
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Tinted` icons style was applied to Brave widgets.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/68c08e6f-b98c-42ed-a6c2-927357cfbad9) | ![2](https://github.com/user-attachments/assets/2eb34427-76a2-42ce-bbe3-c08bba76f5cc) | ![3](https://github.com/user-attachments/assets/f38de5d5-d647-4e01-b3a0-bbd08201adb2) |
| ![1](https://github.com/user-attachments/assets/a831cca3-4b61-42f8-bec1-0dbe9226ba11) | ![2](https://github.com/user-attachments/assets/d8954d28-ebda-449c-9483-32c4d8673cdd) | ![3](https://github.com/user-attachments/assets/50726b8c-1e5d-4779-a60e-6f2abc7ca005) |
