### ISSUE TITLE
[Feature Request] Add extension support on android

### ISSUE THREAD

**Issue by thepcwiz101** [brave/brave-browser#4117]
Kiwi browser (a chromium based browser) has added extension support on android. It's hard to believe and i have tested it. It is exclusive to the xda-developers forums for the next 24 hours. kiwi browser has a github repository too. I have screenshots i will be uploading to the issue in a few minutes.

**Comment by thepcwiz101** [comment]
![Screenshot_20190416-004149](https://user-images.githubusercontent.com/31826503/56184880-5c294680-5fe1-11e9-8acc-882317d8fbc3.png)
![Screenshot_20190416-004212](https://user-images.githubusercontent.com/31826503/56184888-64818180-5fe1-11e9-84ae-fb029c96b4f6.png)

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/browser-android-tabs/issues/1471. New issue opened on Andriod repo

**Comment by srirambv** [comment]
Reopening the issue and adding `android-related` label. We should consider adding support to the new codebase when ported over to brave-core

**Comment by SergeyZhukovsky** [comment]
Duplicated https://github.com/brave/brave-browser/issues/4493
