### ISSUE TITLE
`Enable AdGuard` option installs mv3 instead of mv2

### ISSUE THREAD

**Issue by kodiakhub** [brave/brave-browser#41173]
### Description

AdGuard released a new update yesterday and replaced the AdGuard extension 4.4.22 (mv2) version. See:

- https://github.com/AdguardTeam/AdguardBrowserExtension/releases/tag/v5.0.91
  - > If you’re already using our extension for Chrome, your existing extension will be replaced with the MV3 one.

### Steps to reproduce

1. Go to brave://settings/extensions/v2
2. Enable AdGuard
3. Check AdGuard extension

### Actual result

AdGuard extension (mv3) installed

### Expected result

AdGuard extension (mv2) installed

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave 1.70.117 Chromium: 129.0.6668.59 (Official Build) (64-bit) 

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [x] in the latest version of Chrome

**Comment by antonok-edm** [comment]
@kodiakhub hi, thanks for your report. We've been in touch with the AdGuard team about this too, they are rolling out a migration for users on their original Mv2 extension ID to their Mv3 version, but will continue hosting an Mv2 version under a different extension's ID (previously designated as their "Beta" extension). We should have this fixed shortly!

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.70.126 Chromium: 129.0.6668.100 (Official Build) (64-bit)
-- | --
Revision | 35f34f21e597f5f30e9e206b0354cc137df1f2a3
OS | Windows 10 Version 22H2 (Build 19045.4894)
```
Example | Example
---------|----------
![Image](https://github.com/user-attachments/assets/477ad13b-3d4b-4698-9daf-d4cd6a54c9b1) | ![Image](https://github.com/user-attachments/assets/2680364b-0387-4b15-8d66-a496d5655c1a)
