### ISSUE TITLE
`Pointer`/`Cursor` must be shown at the end of the string when opening the `Edit` prompt

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#41176]
### Description

`Pointer`/`Cursor` must be shown at the end of the string when opening the `Edit` prompt.

### Steps to reproduce

1. Launch Brave
2. Open `Leo`
3. Send a prompt
4. Tap `Pencil` to edit the prompt > *Observe*

### Actual result

When tapping the `Pencil` button to edit the prompt, the cursor/pointer is shown at the beginning of the string.

-------------------

https://github.com/user-attachments/assets/82a66d5e-8183-4272-84df-72639299ea00

### Expected result

`Pointer`/`Cursor` must be shown at the end of the string when opening the `Edit` prompt.

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.70.117
Chromium: 129.0.6668.59 (Official Build) (64-bit)

### Device

- Brand/Model: ANY
- Android version: ANY

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.74.8 Chromium: 131.0.6778.69 (Official Build) beta (64-bit) 
Revision	0e56a6339728b1f1569eb3bdbe8261f2d5785d3b
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

* Ensured that cursor is placed at the end of the string when editing Leo queries.

`example` | `example`
---|---
![Image](https://github.com/user-attachments/assets/861360b6-5f5c-452e-b882-a4ea6d7eec79) | ![Image](https://github.com/user-attachments/assets/135341bb-b1ad-4ef4-92ba-f71d9cc2b912)
