### ISSUE TITLE
Split View – Closing the right non-empty tab in a split view causes Brave to crash

### ISSUE THREAD

**Issue by marlonjames71** [brave/brave-browser#41186]
## Main Issue
While in a split view, if you attempt to close the tab on the right side of the split, it causes Brave to crash. 

In my testing, the only instance where the crash does not occur is when the tab is a new tab meaning you haven't searched anything, switched to an already open tab, have visited any web page, or opened up a bookmark.

### A couple of things to note:
- It does not matter if you've swapped the tabs first before attempting to close the right tab (previously the left tab)
- The crash happens from clicking the "x" on the tab or using the keyboard shortcut `⌘ + w`

## Workarounds:
- separate the tabs first, then close the tab that was on the right
- swap the tabs then close the one on the left

### Steps to reproduce

1. Enable `#brave-split-view` flag
2. New Split View
3. Close the new tab (on the right) using the mouse or shortcut – Result 1
4. Repeat step 2
5. Visit a web page
6. Repeat step 3 – Result 2
7. Repeat steps 4 & 5
8. Swap tabs in split view – Result 2
9. Close the tab on the right – Result 2

You can try all of the steps again and close the tab on the left instead and you will see that Brave does not crash.

### Actual result

1. You will see Brave does not crash and works as expected
2. Brave crashes

### Expected result

Brave should not crash. It should close the tab and shift focus to the other tab that was in the split view.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

`1.71.90 Chromium: 129.0.6668.59 (Official Build) beta (arm64) `

### Channel information

- [ ] release (stable)
- [X] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [X] in the latest version of Chrome

### A couple of other things
- Open in Split View doesn't seem to do anything (tried using keyboard shortcut)
- None of the split view options seem to be showing up in Quick Commands
- Currently, it works closing the right split tab if the tab is empty (new tab), and if that's an indicator of how this feature will function when this bug is fixed, it jumps to the next tab to the right. If you're in a split view and you close one of the tabs (no matter the right one or left one, Brave should always prefer to show the remaining split view tab after the other tab in the split view has been closed.

**Comment by Coffeeling** [comment]
I've had a similar experience with Split View on Nightly.

**Comment by bsclifton** [comment]
@marlonjames71 can you please visit brave://crashes and share some of the uploaded IDs that you see there?

**Comment by marlonjames71** [comment]
> [@marlonjames71](https://github.com/marlonjames71) can you please visit brave://crashes and share some of the uploaded IDs that you see there?

- `a7f60400-2809-c60c-0000-000000000000` – Thursday, October 17, 2024 at 4:18:12 PM
- `3c550200-2809-c60c-0000-000000000000` – Thursday, October 17, 2024 at 1:57:28 AM
- `7f220200-2809-c60c-0000-000000000000` – Thursday, October 17, 2024 at 12:40:07 AM
- `b1072b00-1893-b30c-0000-000000000000` – Sunday, October 13, 2024 at 5:48:03 AM

I wanna add that I just checked to see if the bug is still there and apparently it's fixed. I could not get it to crash.

**Comment by simonhong** [comment]
Checked above crash ids' call stack but I think it's not related with split view.
And we fixed split view related crash issue (https://github.com/brave/brave-core/pull/26826) regarding to tab activation state.
I think this issue is similar with it. Feel free to re-open when you meet similar crash.

**Comment by marlonjames71** [comment]
Yeah, no problem here with the split tab anymore. Thanks for the update.

**Comment by Coffeeling** [comment]
Same, no crash on Nightly for me anymore.
