### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by tomgino453** [brave/brave-browser#41189]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.70.117 Chromium: 129.0.6668.59
Operating System: Windows NT 10.0.22000

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Every time I download a video or image file it crashes

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/c7290e00-162b-a10c-0000-000000000000

**Comment by fredystar200** [comment]
Yeah I have the same problem

**Comment by iefremov** [comment]
dupe https://github.com/brave/brave-browser/issues/41179
