### ISSUE TITLE
Manifest V2 Extensions settings page doesn't appear

### ISSUE THREAD

**Issue by thericle** [brave/brave-browser#41180]
### Description

There should be a "Manifest V2 Extensions" page under brave://settings/extensions where you can enable 4 specific manifest v2 extensions. In my case, it just doesn't exist. I tried completely uninstalling and re-installing Brave and nothing changed.

### Steps to reproduce

Go to "brave://settings/extensions" or "brave://settings/extensions/v2"

### Actual result

Under "brave://settings/extensions", there is no option "Manifest V2 Extensions".
If I open "brave://settings/extensions/v2", a page titled "Manifest V2 Extensions" appears, but it's empty.

### Expected result

There should be an option "Manifest V2 Extensions" on "brave://settings/extensions",
and when I go to "brave://settings/extensions/v2", it should show the 4 extensions instead of an empty page.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave: 1.70.117 Chromium: 129.0.6668.59 (Official Build) (64-bit)
Revision: 5d4da8332eb061f79bb47ec5b0bf595600fdcd55
OS: Windows 11 Version 23H2 (Build 22631.4169)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [X] in the latest version of Chrome

**Comment by hyperion4** [comment]
> ### Expected result
> There should be an option "Manifest V2 Extensions" on "brave://settings/extensions", and when I go to "brave://settings/extensions/v2", it should show the 4 extensions instead of an empty page.
> 
No, there shouldn't be there because Brave seems to have decided to have V2 extensions page disabled by default.
Because they have the flag disabled by default., so this must be their decision.
If you want to have this page shown go to
brave://flags/#brave-extensions-manifest-v2
and enable the flag.

**Comment by thericle** [comment]
@hyperion4 Thank you, it worked with the flag you mentioned. I used a fresh install on a different pc before I created this issue. After checking again, it seems that this flag was enabled by default on that pc. It has the same version, so maybe this is one of those experimental features.
