### ISSUE TITLE
Clock on the new tab page is not being displayed.

### ISSUE THREAD

**Issue by VarunaSene** [brave/brave-browser#41197]
### Description

The clock on the new tab page is not displayed.

### Steps to reproduce

1.  On the new tab page, try to toggle Show Clock on and off.
2. 
3. 

### Actual result

The toggle does not have any effect. The clock remains not displayed.

### Expected result

The clock should be displayed on the new tab page. Toggling Show Clock between on and off should have an effect.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Version 1.70.117 Chromium: 129.0.6668.59 (Official Build) (64-bit)

### Channel information

- [X] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by VarunaSene** [comment]
@rebron Clock on the new tab page is not being displayed

**Comment by VarunaSene** [comment]
@rebron Why is this still going on?

**Comment by VarunaSene** [comment]
@rebron All three Brave editions Brave Nightly, Beta and official, all three do not display the time(Clock) on the new tab page

**Comment by rebron** [comment]
Closing as dupe, https://github.com/brave/brave-browser/issues/41226 fixed in 1.70.123
