### ISSUE TITLE
'Add Source to Brave News' missing from hamburger menu for articles

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#41208]
### Description

'Add Source to Brave News' missing from hamburger menu for articles

Regression in 1.71

### Steps to reproduce

1. New Install
2. Enable Brave News
3. Navigate to `https://en.wikipedia.org/wiki/Main_Page` or an article
4. Scroll down the article half way
5. Open hamburger menu, look for `Add Source to Brave News` in the share menu

### Actual result

Option is missing from menu

![IMG_7446](https://github.com/user-attachments/assets/e5622386-e0a5-42cf-a478-6e7f7f03da0e)

### Expected result

![IMG_7447](https://github.com/user-attachments/assets/6b7086fc-a4d9-496c-8d25-52846787d570)

### Reproduces how often

Easily reproduced

### Brave version

1.70 - Not reproducible
1.71 - Reproducible
1.72 - Reproducible

### Device/iOS version

iPhone / iOS 18

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by LaurenWags** [comment]
Requires 1.71.105 or higher for verification 👍🏻

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18` using version `1.71.112`

- Ensured that `Add Source to Brave News` is shown in the hamburger shared menu
- Ensured that sources can be added using `Add Source to Brave News` and shows up in the `Following` list in Brave News settings.

example | example | example
---|---|---
![Image](https://github.com/user-attachments/assets/f36986bc-e43f-492c-a4ef-1df92de5edf3) | ![Image](https://github.com/user-attachments/assets/43bd7066-1bef-4d5c-9a63-3cb907e42bfa) | ![Image](https://github.com/user-attachments/assets/faa9f722-a3aa-4a17-801a-faa0819e0247)
