### ISSUE TITLE
[Follow up to #41088] Adjust dark mode icons

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#41211]
Follow up to https://github.com/brave/brave-browser/issues/41088

The current dark mode icons look a bit odd next to other dark mode icons because they have a tint applied to the background, we've decided to remove this

**Comment by hffvld** [comment]
Verified on `iPad Mini (6th gen)` using version(s):
```
Device/OS: iPad Mni (6th gen) / iPadOS 18
Brave build: 1.70 (123)
BraveCore: 1.70.123 (129.0.6668.89)
```
Filed follow-up issue #41375.
---------------------------

**STEPS:**
1. Install Brave 
2. Customize the device's home screen
3. Switch icons style to `Dark` > *Verify*
4. Switch icons style to `Automatic` > *Verify*
5. Switch between `Small` and `Large` icons > *Verify*

**ACTUAL RESULTS:**
- Verified that Brave icon in `Dark` and `Automatic` styles looks as expected without background tint.

---------------------------

|1.70 (119)|1.70 (123)|
|:-:|:-:|
|`Dark` style / Small icons|`Dark` style / Small icons|
| ![1](https://github.com/user-attachments/assets/c6c24071-8736-4f03-8bff-7b46fa0dd047) | ![2](https://github.com/user-attachments/assets/2f2a8d8e-80da-4285-88bf-14e0d9446152) |
|`Dark` style / Large icons|`Dark` style / Large icons|
| ![1](https://github.com/user-attachments/assets/59ca7668-7921-4905-be0e-fb445239fe74) | ![2](https://github.com/user-attachments/assets/5d6448e6-abfe-4e31-8db7-216a6bce364d) |
|`Automatic` style / Small icons|`Automatic` style / Small icons|
| ![1](https://github.com/user-attachments/assets/9f635b7c-b94f-4a59-b3e5-c7486762d1ea) | ![2](https://github.com/user-attachments/assets/99d007c7-9b0b-49dd-948b-eb55bac9be32) |
| `Automatic` style / Large icons | `Automatic` style / Large icons |
| ![1](https://github.com/user-attachments/assets/addb76fd-35f5-4f07-a52d-fb439462481c) | ![2](https://github.com/user-attachments/assets/2ce2ef0e-3184-4902-af5a-a5ff54bd2f12) |
