### ISSUE TITLE
[Hackerone] Handle assign in signing of signature requests

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#41219]
### Description

See https://hackerone.com/reports/2731151

**Comment by kjozwiak** [comment]
The above requires `1.71.117` or higher for `1.71.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.71.117 Chromium: 130.0.6723.58 (Official Build) (64-bit)
-- | --
Revision | 0fe5e88d5d203ca1fc7c7d215cd353539cdf472a
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from [brave/brave-core#26088](https://github.com/brave/brave-core/pull/26088)
- Verified warning message is shown when a System program instruction transaction is submitted

 ![Image](https://github.com/user-attachments/assets/10bd351b-5998-46d2-a7b8-8ac3e2ed9b1a)

**Comment by srirambv** [comment]
Removing Android and iOS labels as they need separate UI implementation for this. More discussion [here](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1729659316406509?thread_ts=1729659316.406509&cid=C023VS4HJ6Q)
