### ISSUE TITLE
[Follow up to #39552] Title for `Edit` button needs to be updated to `Done` when editing custom SE

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#41210]
### Description

Follow-up to #39552.

### Steps to reproduce

1. Launch Brave 
2. Hamburger menu > Settings
3. Search Engines > Add Custom Search Engine
4. In **URL** type `https://youtube.com/search?q=%s` and in **Title** type `YT` > Done
5. Slide the newly created SE to the left > Tap `Edit`
6. Update the `Title` > *Observe*

### Actual result

If editing custom SE (any of URL or Title), the button title (top right corner) says `Edit` instead of `Done`.

----------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/d104feae-fd4b-4461-8fb6-a80788508793) | ![2](https://github.com/user-attachments/assets/49d5db6d-beea-4f54-91ef-9d02e6a22c50) |

### Expected result

The title for `Edit` button needs to be updated to `Done` when editing custom SE.

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.70 (117)
BraveCore: 1.70.117 (129.0.6668.59)

### Device/iOS version

iPad Mni (6th gen) / iPadOS 18

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kylehickinson** [comment]
It seems like it was explicitly set to "Edit" instead of "Done" when editing a custom search engine. Do we want to go back to "Done" here? Not sure on reasoning cc @jamesmudgett @timchilds

**Comment by kylehickinson** [comment]
Correct, they have to tap the button to save whatever changes they've made in the form

**Comment by kylehickinson** [comment]
@timchilds Correct, they have to tap the button to save whatever changes they've made in the form

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7.1
Brave build: 1.72 (93)
BraveCore: 1.72.93 (131.0.6778.14)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41210#issue-2542932386
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the title for the `Edit` button is updated to `Done` when editing custom SE.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/09d8ef80-095a-455a-88e8-369e37d103ec) | ![2](https://github.com/user-attachments/assets/7d118aa4-99bf-45dc-a316-b0c7912deb33) | ![3](https://github.com/user-attachments/assets/c8544bd2-d394-4684-9fd9-0d3d09c107aa) |
