### ISSUE TITLE
Shield blocks Are.na extension

### ISSUE THREAD

**Issue by bnjmnjns** [brave/brave-browser#4121]
## Description 
The chrome extension for the website are.na's cookies appear to be blocked by Brave's shields

## Steps to Reproduce

   1.  Install extension from the [chrome web store].(https://chrome.google.com/webstore/detail/arena/lkihjlcipnbgeokmfnpogjfflofbfhga)
   2. [register](https://www.are.na/sign_up) for an are.na account
   3. attempt to sign in.

## Actual result:
Signin in blocked when shields are turn on and user redirected to login screen (login loop)

## Expected result:

sign in...

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)
-- | --
Revision | e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes, tested on all versions

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
yes
- Is the issue reproducible on the latest version of Chrome? 
no

### Additional Information
Presumably related: https://github.com/brave/brave-browser/issues/1380

Thanks!

**Comment by martinklepsch** [comment]
I saw that Shields should exempt extensions as per https://github.com/brave/brave-core/pull/975 but it looks like that isn't quite working for the Are.na extension. Would love to contribute but I'm pretty clueless when it comes to C so maybe this is a useful pointer for someone else. :v:

**Comment by bsclifton** [comment]
@bnjmnjns if you're still using Brave, do you know if this is still an issue? We've had a lot of fixes since you originally reported

**Comment by martinklepsch** [comment]
@bsclifton thanks for the update, it seems that the Are.na extension is now working on Brave. Thanks a lot.
