### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Jhosmith21** [brave/brave-browser#41221]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.70.117 Chromium: 129.0.6668.59
Operating System: Windows NT 10.0.22631

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.Al usar la extension Webp avif image converter se cierra el navegador Brave
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/9ecf1700-162b-a10c-0000-000000000000

**Comment by Jhosmith21** [comment]
When using the Webp avif image converter extension the Brave browser closes

**Comment by Jhosmith21** [comment]
![image](https://github.com/user-attachments/assets/b9b689a4-b953-49e3-9348-148791257ed7)

**Comment by Jhosmith21** [comment]
![image](https://github.com/user-attachments/assets/8203df47-e011-4567-907e-ebec0f8ff94a)

**Comment by iefremov** [comment]
dupe 9ecf1700-162b-a10c-0000-000000000000
