### ISSUE TITLE
Grey out extensions in Tor settings 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4122]
## Description 

Although extensions are disabled internally, they show up as enabled in Tor settings. The extensions section needs to be removed completely or greyed out

## Steps to Reproduce

   1. Open Tor window
   2. Open settings
   3. Extensions shows up as enabled even thoug they don't work on Tor Windows

## Actual result:

![image (1)](https://user-images.githubusercontent.com/17010094/56216735-fc0dc100-602f-11e9-941c-c439c798f371.png)

## Expected result:
Remove the extension section or grey them out as disabled

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)
-- | --
Revision | e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}
OS | All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A
### Additional Information

cc: @riastradh-brave

**Comment by yrliou** [comment]
With https://github.com/brave/brave-core/pull/3319 merged, this could be closed now since we will open the settings page in the parent profile (original regular window).

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.72.124 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
--|--
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Linux

* Verified test plan from https://github.com/brave/brave-core/pull/3319
