### ISSUE TITLE
Crash Report - browser crashes on any URL entered in Private Window or Private Window with Tor

### ISSUE THREAD

**Issue by ib0ndar** [brave/brave-browser#41229]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.71.95 Chromium: 129.0.6668.59
Operating System: Mac OS X 14.6.1

URL (if applicable) where crash occurred: https://google.com

Can you reproduce this crash?

Yes.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open a Private Window or Private Window with Tor
2. Enter ANY URL
3. Browser crashes and quits

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/f04e1a00-162b-a10c-0000-000000000000

**Comment by iefremov** [comment]
@ib0ndar do you have anything toggled on brave://flags? Also can you please share info from your brave://version? It seems you have some experimental flags related to tab groups saving enabled, they cause the crash. Neither brave nor chrome guarantee stable work with experimental flags.

**Comment by ib0ndar** [comment]
@iefremov 
Yes, you are right, the root cause is one of the flags set. I've reset all the flags and started to enable them one by one until Brave started to crash again, then disabled one by one trying to isolate the flag causing this crash. And found it - it is **#tab-group-sync-service-desktop-migration**

**Comment by ib0ndar** [comment]
Just to add that same flag doesn't crash Chrome Beta, Version 130.0.6723.19 (Official Build) beta (arm64)

**Comment by iefremov** [comment]
yeah that means we will have the fix soon once cr 130 is merged and we kick off new nightly and beta. I see that stable 129 chrome has this problem.
