### ISSUE TITLE
[iOS] - Playlist Crash

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#41232]
### Description

Playlist sometimes crashes deleting offline data

### Steps to reproduce

1. Delete offline playlist data

### Actual result

- Crash

### Expected result

- Shouldn't Crash

### Reproduces how often

Easily reproduced

### Brave version

1.68.x

### Device/iOS version

Any

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.71.116` or higher for `1.71.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7
Brave build: 1.71 (118)
BraveCore: 1.71.118 (130.0.6723.70)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41232#issue-2545909144
2. *Verify*

**ACTUAL RESULTS:**
- Verified that Brave does not crash when removing `offline` Playlist items.

---------------------------

https://github.com/user-attachments/assets/d8adc2a7-455e-4177-9d30-09d923241e3c
