### ISSUE TITLE
[AI Chat]: AI Chat shows a `0` at the start of the window in latest

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#41248]
1. Open AI Chat
2. See weird `0`

Expected:
No `0`

found by @emerick

**Comment by hffvld** [comment]
Verified on `Galaxy Z Fold 6` using version(s):
```
Device/OS: Galaxy Z Fold 6 / q6quew-user 14 UP1A.231005.007 release-keys
Brave build: 1.72.90 
Chromium: 130.0.6723.70 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41248#issue-2547665503
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `0` is not shown on the `Leo` UI.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/88db61f8-5bc8-4f91-8e1b-1d7e44794253) | ![2](https://github.com/user-attachments/assets/6c4c5168-29bf-40da-bb12-eee815e77ea0) | ![3](https://github.com/user-attachments/assets/801ada99-ec17-40cc-8801-3cf418523ca0) | ![4](https://github.com/user-attachments/assets/34733d20-7a6c-4bda-b04e-a2442a681ebc) |

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.73.86 Chromium: 131.0.6778.39 (Official Build) (64-bit)
-- | --
Revision | 52163bcf4e40f27ddb76ffa79c90a8833084a9bd
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from issue description
- Verified no `0` shown in Leo UI

https://github.com/user-attachments/assets/07f6448b-3f7e-4a16-a3e7-413573f70d6e
