### ISSUE TITLE
Selecting Ask Leo from URL bar doesn't generate response 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#41245]
### Description

Selecting Ask Leo from URL bar doesn't generate response 

### Steps to reproduce

1. Type a query in URL
2. Select Ask Leo from the dropdown
3. Doesn't answer the typed query

### Actual result

https://github.com/user-attachments/assets/a662fd76-ace4-477a-bc3d-f7edd4bf0101

### Expected result

Should respond to the query asked in URL

### Reproduces how often

Easily reproduced

### Brave version

Brave | 1.72.19 Chromium: 129.0.6668.59 (Official Build) canary (64-bit) 
-- |--
Revision	| b7e96cc7add871c7cfe6ec1817cec8baa3bee155
OS| Android 14; Build/UKQ1.230917.001; 34; REL

### Device

- Brand/model: Xiaomi 12 Pro
- Android version: 14

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Note: There is no Leo premium purchased on Nightly

cc: @brave/qa-team @mattmcalister @serg

**Comment by SergeyZhukovsky** [comment]
I tried nightly(1.73.x), beta(1.72.x) and stable(1.71.x) channels and all of them respond. Maybe it was something on nightly when @srirambv tried, but it's gone already. Plus on video it tries to summarize the page, but page is a new tab page, which strange as well. Anyways @srirambv are you able to reproduce it with current versions?

**Comment by srirambv** [comment]
@SergeyZhukovsky I couldn't reproduce it on nightly/beta/release. Going to close for now, can always reopen if it happens again
