### ISSUE TITLE
Wallet creation fails using work proxy.

### ISSUE THREAD

**Issue by cwbriscoe** [brave/brave-browser#4124]
## Description 

Brave Rewards does not work behind work proxy.  I get the error message: 
```
Wallet creation failed
Please check your internet connection
```

![image](https://user-images.githubusercontent.com/691222/56224079-d67aba80-6023-11e9-8263-525346c09473.png)

## Steps to Reproduce

   1. Click Rewards Icon
   2. Click Try Again

OR

   1. Click Rewards Icon
   2. Click Learn More
   3. Click Try Again

## Actual result:
Fails to create wallet

## Expected result:
Wallet created

## Reproduces how often: 
Fails every time

## Brave version (brave://version info)

Brave | 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)
-- | --
Revision | e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}
OS | Windows 10 OS Build 17134.648

### Reproducible on current release:
Reproducible on current stable release.  Not sure about beta or dev.

### Website problems only:  
N/A

**Comment by NejcZdovc** [comment]
@cwbriscoe is this still a problem?

**Comment by cwbriscoe** [comment]
This hasn't been an issue for me for a while.  I will go ahead and close.  Thanks.
