### ISSUE TITLE
[Wallet/iOS] Currency symbol in portfolio is not updated after currency is changed in wallet settings

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#41264]
### Description

Currency symbol in portfolio is not updated after currency is changed in wallet settings

### Steps to reproduce

1. Open wallet
2. go to wallet settings
3. change default base currency to something that is not the same as the current one
4. back to portfolio 

### Actual result

Currency symbol still display "$" in total balance and balance change label. 

### Expected result

Currency symbol for total balance and balance change label should reflect the currency change

### Reproduces how often

Easily reproduced

### Brave version

1.72.x

### Device/iOS version

all 

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.3 running 1.75 (171)
- Verified steps from [brave/brave-core#27070](https://github.com/brave/brave-core/pull/27070)
- Verified updating currency updates the symbol in portfolio 

https://github.com/user-attachments/assets/a797a996-3886-43bd-96d9-85c8c354928e
