### ISSUE TITLE
[Follow up #40960] Brave news tab is loaded with `Error code: Out of Memory` error after staying idle on the Brave news tab for little more than an hour

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#41276]
### Description

Found while testing https://github.com/brave/brave-browser/issues/40960.  After enabling Brave news on Tab 1, opened Tab 2 stayed idle for about an hour.  Switched to Tab 1, the news is refreshed with new data which is expected result for the issue.  However, couple of minutes later, an error page is shown `Out of memory` error.  Clicked Reload button and Brave news page shown as expected.  Reproduced the issue in macOS arm64 as well.   After reloading the page, stayed idle for another 45 minutes, page loaded with error again with `Not enough memory to open this page`

### Steps to reproduce

1. Installed 1.71.98
2. launched Brave
3. clicked `Turn on News` to enable news in the NTP 
4. opened Tab 1 with Brave news article cards are shown
5. opened tab 2 and same news article cards are shown as Tab 1
6. Waited for an hour 
7. Tab 2 shows cards with updated times (eg. Business insider `2 hours` --> `3 hours`)
8. Switched to Tab 
9. News feed is refreshed with new article cards
10. waited couple of more minutes
11. clicked Reload button
12. waited another 45 minutes

### Actual result

Page loaded with following error.   

- Aw, Snap! Something went wrong while displaying this webpage
    - Error code: `Out of memory` error.  Clicked Reload button

error| Task manager| Reload/Refresh | Task Manager | second iteration
------- | ------ | ------ | ----- | -----
![image](https://github.com/user-attachments/assets/4b767f02-6ad5-4055-ba31-0b8a8d616e75)|![image](https://github.com/user-attachments/assets/9e9b76f4-2bfa-4109-a926-9036a7468d71)|![image](https://github.com/user-attachments/assets/cfe85531-fefd-459e-9fc3-fb6a4bed36e3)|![image](https://github.com/user-attachments/assets/cbc76343-fd57-41e6-a86c-ce00d1e3998c)|![image](https://github.com/user-attachments/assets/b0d0869f-beff-453c-aebb-82b0475a9c1f)

### Expected result

Brave news feed should be shown without errors 

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.71.98 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | 453ddf665beda526b19af7aa60047a0e757b6a7a
OS | Windows 11 Version 23H2 (Build 22631.4249)

### Channel information

- [ ] release (stable)
- [X] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

@fallaciousreasoning @LorenzoMinto 
cc: @brave/qa-team @rebron

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.72.56 Chromium: 129.0.6668.89 (Official Build) nightly (64-bit)
-- | --
Revision | 087482aabf21a34d460885e1355f9b1c21f5047e
OS | Windows 11 Version 23H2 (Build 22631.4249)
```

1. Installed 1.72.56
2. launched Brave
3. clicked Turn on News to enable news in the NTP
4. opened Tab 1 with Brave news feed shown
5. opened tab 2 and same news feed shown as Tab 1
6. Waited for an hour
7. Tab 2 shows cards with updated times (eg. Business insider 2 hours --> 3 hours)
8. Switched to Tab 1
9. News feed is refreshed with new article cards
10. waited couple of more minutes
11. clicked Reload button
12. waited another 45 minutes


Tab 1 | Tab 2 | Tab 2 (after an hour) | Tab 1 (after an hour)
-----  | ------ | ------ | ------
![image](https://github.com/user-attachments/assets/4c426bd4-aafd-4944-bdc1-7de6080b4a6f)|![image](https://github.com/user-attachments/assets/63fa14e0-256f-4dcd-b591-7d9e501646ea)|![image](https://github.com/user-attachments/assets/70bd7058-bcc8-4dd5-be27-7e2e0ddef4ac)|![image](https://github.com/user-attachments/assets/06df8367-6ba5-4666-8216-4dbbded5de41)

**Comment by LaurenWags** [comment]
Requires 1.71.106 or higher for verification 👍🏻

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.71.111 Chromium: 130.0.6723.31 (Official Build) (64-bit)
-- | --
Revision | a39f12f230248c726d3f1cac2d59dd4dcac714d7
OS | Windows 11 Version 23H2 (Build 22631.4317)
```

1. Installed 1.71.111 
2. launched Brave
3. clicked Turn on News to enable news in the NTP
4. opened Tab 1 with Brave news feed shown
5. opened tab 2 and same news feed shown as Tab 1
6. stayed idle on Tab 2 and waited for an hour
7. Tab 2 shows cards with updated times
8. Switched to Tab 1
9. News feed is refreshed with new article cards
10. waited couple of more minutes (4 min)
11. clicked Reload button
12. waited another 45 - 60 minutes on Tab 1
13. switched to Tab 2 and page is refreshed with new feed


#### Confirmed no OOM error displayed on the Brave news feed

Initial Brave news 

step 3 (tab 1) | step 5 (tab 2) 
------ | ----------
![Image](https://github.com/user-attachments/assets/a8332076-9a53-49d3-82c2-fd0c29359443)|![Image](https://github.com/user-attachments/assets/09af9d9e-86c3-4421-87cc-1f82bd2fb857)

After hourly intervals

step 7 (tab 2)| steep 8 | step 9 | step 10 | step 11 | step 12 | step 13
---------- | ------- | ----- | ------ | ------ | ----- | --------
![Image](https://github.com/user-attachments/assets/514d58e6-85bb-489a-8d0b-6668d5dc9066)|![Image](https://github.com/user-attachments/assets/11e7a8df-2b51-48a0-9bdb-7ed8925189a2)|![Image](https://github.com/user-attachments/assets/a23aaa4c-c587-4900-948d-935f25e648ef)|![Image](https://github.com/user-attachments/assets/171e3813-de66-4e02-92f1-e81b7c89a434)|![Image](https://github.com/user-attachments/assets/856081ce-1bf8-4096-8981-f76707a93e26)|![Image](https://github.com/user-attachments/assets/d26a5488-b6bb-44ed-8cb3-ffa5a5f8dd24)|![Image](https://github.com/user-attachments/assets/e1451b0b-6800-4d82-acf7-ee60d038f9f2)
