### ISSUE TITLE
brave forgets cookies of only my google account

### ISSUE THREAD

**Issue by awa1txn** [brave/brave-browser#41288]
### Description

So I installed fresh and clean brave. Logged in to google and logged in to reddit/github using google auto sign in. After PC reload, google auth cookies was reset and reddit/github somehow saved. Cookies settings does not work?

### Steps to reproduce

1. Open browser
2. Log in to google
3. Close Brave Browser
4. Repeat Step 1
5. Open google.com
6. Check cookies
7. Reload page

### Actual result

https://youtu.be/Zu2WQ-ogG6U

### Expected result

Brave browser settings are supposed to work proper so that I do not need to log in to google every time I open Brave.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.119 Chromium: 129.0.6668.70 (Official Build) (64-bit) 

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] in the latest version of Chrome
- [X] with Brave Rewards disabled

**Comment by RuizSenior** [comment]
How did you solve it?

**Comment by awa1txn** [comment]
> How did you solve it?

I did not solve it. Tried doing so for about couple weeks tho. 
I gave up. I switched to Opera, till mess will be fixed
