### ISSUE TITLE
download of image (generic file?) fails if identical filename present locally (OTF filenames)

### ISSUE THREAD

**Issue by labor4** [brave/brave-browser#41284]
### Description

Browsers support the download of files whose filenames are defined in the `download` **attribute** of the link, and whose source filenames are supposed to be discarded in favour of that attribute content..

**This fails when** [filename already present locally] on Brave iOS, but not Safari iOS.
**This succeeds when** [no such filename conflict present locally]

The download itself is being done, but is shown as `failed` after completion.

In the reconstruction example I used a download **initialized by js**.

### Steps to reproduce

*I did not test against non-OTF (normal) filenames*

I think the minimum definition is:

    If: [supposed filename is handled on-the-fly, so is not original source/link filename]
    then: [Auto-Rename mechanism is not triggered]

**The following js download trigger code would currently fail**,
if `fileName` is already present in IOS download dir:
```
   var link = document.createElement('a');
   link.href = fileUrl;
   link.download = fileName;
   document.body.appendChild(link);
   link.click();
   document.body.removeChild(link);
```

### Actual result

- download finishes
- error "download failed"

### Expected result

- download finishes
- renamed if needed (ie: image-1.png, image-2.png)

### Reproduces how often

Easily reproduced

### Brave version

1.69.2 (172)

### Device/iOS version

17.6.1
iPhone Xs

### Affected browser versions

- [X] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [X] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

not an issue in iOS Safari

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iOS 18.2.1` using version `1.75 (175)`

* Ensured files are successfully downloaded and renamed when using the download trigger code in https://github.com/brave/brave-browser/issues/41284#issue-2554433613
* Ensured that downloading the same filename does not cause error.

![Image](https://github.com/user-attachments/assets/15a291fe-9015-423c-beb1-8d691fec1dc1)

example | example | example
--|--|--
![Image](https://github.com/user-attachments/assets/1fdaa71b-4cd8-45ef-bfde-744ba6486f5a) | ![Image](https://github.com/user-attachments/assets/d0c5b069-399e-47d2-9468-42ce9bfdff43) | ![Image](https://github.com/user-attachments/assets/12b2d1bc-6956-4fd0-a599-101553f2c98c)
