### ISSUE TITLE
Brave browser is not responding 

### ISSUE THREAD

**Issue by mr-kasper** [brave/brave-browser#41292]
### Description

When I open a window after sometime Brave's UI starts blocking and it uses a lot of RAM and CPU after that without any response, So I have to close it from the task manager.

### Steps to reproduce

1. Open brave like normal
2. Use it a few minutes
3. The UI starts blocking

### Actual result

Brave not responding at all and it takes more on the RAM and CPU

### Expected result

Brave works normal like the previous time

### Reproduces how often

No steps to reproduce

### Brave version (brave://version info)

Brave: 1.70.119 Chromium: 129.0.6668.70 (Official Build) (64-bit)

Revision: a15c836a4df987f118ece1645f54b081019049de

OS: Windows 10 Version 22H2 (Build 19045.4957)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [X] in the latest version of Chrome

**Comment by Vishwas-web** [comment]
Do You Have any Screenshot to show.
it will help.

**Comment by mr-kasper** [comment]
<img width="371" alt="brave" src="https://github.com/user-attachments/assets/6c42ccfb-acf4-4a9d-a812-eccc29545422">
I just open YouTube page and its UI blocks and slowly. Sometimes doesn't respond at all.

**Comment by Vishwas-web** [comment]
Extensions or third-party plugins may consume resources over time.
check this once and also check 
Hardware Acceleration This can sometimes cause issues with browser performance.

**Comment by mr-kasper** [comment]
Thank you that was helpful.
I think it was extensions when I turned off all of them, the browser is working correctly like it was before. 
Thank you for your support.

**Comment by Vishwas-web** [comment]
Check which one it was.
your welcome!

**Comment by rebron** [comment]
Closing per last comment https://github.com/brave/brave-browser/issues/41292#issuecomment-2385385520
Thanks! @Vishwas-web
