### ISSUE TITLE
'Open in Brave' from X app share widget not working [iOS 18] 

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#41296]
### Description

'Open in Brave' from X app share widget not working [iOS 18] 

Seems to be a regression with iOS 18

### Steps to reproduce

1. Install Brave 1.70.119
2. Open X app, share post using `Share via` in share menu
3. Select Brave in next screen dialog

### Actual result

Not opened in Brave

![IMG_7540](https://github.com/user-attachments/assets/3b5735ab-c73b-453f-bf55-be3dc0a6b7d9)

### Expected result

Open URL in Brave twitter

### Reproduces how often

Easily reproduced

### Brave version

1.70.119

### Device/iOS version

iPhone 12 / iOS 18

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by LaurenWags** [comment]
Requires 1.70.124 or higher for verification 👍🏻

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.0` using version `1.70.125`

- Ensured that URLs are opened when using `Open in Brave` from X app share widget.

example | example
---|---
![Image](https://github.com/user-attachments/assets/f22a0e6c-03fc-49ba-95a5-c78d53c5a546) | ![Image](https://github.com/user-attachments/assets/624e907d-802b-4d5d-975c-1189ec2388d4)
