### ISSUE TITLE
Clean Copy URL feature should work when copying from the URL bar

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#41302]
### Description

Currently iOS only presents users the clean copy option in the “hamburger menu” (…). If you copy the URL from the URL bar, there’s no option

### Steps to reproduce

1. Select the URL in the URL bar
2. Long press to get the copy etc options
3. See no “clean copy” option

### Actual result

![image](https://github.com/user-attachments/assets/d9cfa421-864d-4ab4-8f8d-d070ce31149a)

### Expected result

To have a “clean copy the url” option

### Reproduces how often

Easily reproduced

### Brave version

Current

### Device/iOS version

NA

### Affected browser versions

- [X] latest AppStore
- [X] latest TestFlight
- [X] previous TestFlight

### Reproducibility

- [X] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

Two suggestions 

- always show the option when selecting all text in the URL bar
- Always include the clean copy option when the selected text looks like a URL

**Comment by kylehickinson** [comment]
Discussed in triage, OK with using "Copy Clean Link" as the copy and letting it slide to second page if necessary, can fix later if needed

**Comment by pes10k** [comment]
Thanks @kylehickinson thats fantastic!

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7.1
Brave build: 1.72 (96)
BraveCore: 1.72.96 (131.0.6778.24)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Open URL in the new tab, for example, https://www.amazon.com/EF-ECOFLOW-Portable-Charging-Generator/dp/B0B9XB57XM?pd_rd_w=VjwfT&content-id=amzn1.sym.a8f3032b-cf6b-4fad-8ec8-8ede405b4845&pf_rd_p=a8f3032b-cf6b-4fad-8ec8-8ede405b4845&pf_rd_r=0MP1N1518KZJP4JTS3WK&pd_rd_wg=Jp2ky&pd_rd_r=6507e6df-f817-4e9b-899a-06ea1a25739c&pd_rd_i=B0B9XB57XM&ref_=pd_hp_mw_btf_unk_B0B9XB57XM
3. Tap URL bar > Tap again to open the menu
4. Tap `>` > *Verify, `Copy Clean Link` is shown*
5. Tap `Copy Clean Link` > Open any note-taking app
6. Paste > *Verify, copy clean link works*

**ACTUAL RESULTS:**
- Verified that `Copy Clean Link` is shown in the context menu in the URL search bar
- Verified that `Copy Clean Link` works and above URL from `Step 2` copied as https://www.amazon.com/EF-ECOFLOW-Portable-Charging-Generator/dp/B0B9XB57XM?ref_=pd_hp_mw_btf_unk_B0B9XB57XM

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/6f60cfa2-f8aa-4674-939c-d2610a789c8c) | ![2](https://github.com/user-attachments/assets/da9265fd-0339-48e6-ba28-1afad325403a) |

**Comment by hffvld** [comment]
Verified on `iPad Mini (6th gen)` using version(s):
```
Device/OS: iPad Mini (6th gen) / iPadOS 18.0.1
Brave build: 1.73 (89)
BraveCore: 1.73.89 (131.0.6778.69)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Open URL in the new tab, for example, https://www.amazon.com/EF-ECOFLOW-Portable-Charging-Generator/dp/B0B9XB57XM?pd_rd_w=VjwfT&content-id=amzn1.sym.a8f3032b-cf6b-4fad-8ec8-8ede405b4845&pf_rd_p=a8f3032b-cf6b-4fad-8ec8-8ede405b4845&pf_rd_r=0MP1N1518KZJP4JTS3WK&pd_rd_wg=Jp2ky&pd_rd_r=6507e6df-f817-4e9b-899a-06ea1a25739c&pd_rd_i=B0B9XB57XM&ref_=pd_hp_mw_btf_unk_B0B9XB57XM
3. Tap URL bar > Tap again to open the menu > *Verify, `Copy Clean Link` is shown*
5. Tap `Copy Clean Link` > Open any note-taking app
6. Paste > *Verify, copy clean link works*

**ACTUAL RESULTS:**
- Verified that `Copy Clean Link` is shown in the context menu in the URL search bar
- Verified that `Copy Clean Link` works and above URL from `Step 2` copied as https://www.amazon.com/EF-ECOFLOW-Portable-Charging-Generator/dp/B0B9XB57XM?ref_=pd_hp_mw_btf_unk_B0B9XB57XM

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/9227669d-b93f-4448-92d5-611022c638de) | ![2](https://github.com/user-attachments/assets/cca91aa4-6dd2-4b4c-b96e-585f7942b129) |
