### ISSUE TITLE
[ads] SmartNTT

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#41303]
See https://github.com/brave/reviews/issues/1757

**Comment by btlechowski** [comment]
Verification passed on Brave v1.72.97 on Lenovo TB-8506FS (Android 11.0)

#### NTT+SmartNTTs serving - non rewards

<details>

component contains regular NTTs and SmartNTTs
Verified ad is shown

![Image](https://github.com/user-attachments/assets/9c02b044-6cb3-4141-bc98-3634b940a3d4)

</details>


#### NTT+SmartNTTs serving - rewards

<details>

catalog contains regular NTTs and SmartNTTs
Verified ad is shown

![Image](https://github.com/user-attachments/assets/3be346d5-440b-4f26-82f4-462553f968c0)


```
[VERBOSE1:confirmations.cc(92)] Successfully processed kViewedImpression confirmation for kNewTabPageAd with transaction id 3c38c6ec-00b6-4a0a-a3bd-8714716e561e and creative instance id 143148ee-bd08-41f2-a8e0-fd8516e02975

```

</details>
