### ISSUE TITLE
MISSING: unVerifiedCheck in Brave Rewards panel

### ISSUE THREAD

**Issue by cndouglas** [brave/brave-browser#4130]
## Description 
In the Brave Rewards panel, it shows the following text in light blue if a site is not verified: "MISSING: unVerifiedCheck".

## Steps to Reproduce
   1. Go to github.com.
   2. Click the Brave Rewards button in the URL bar.

## Actual result:
![](https://user-images.githubusercontent.com/19424103/56236252-c0ceba80-604e-11e9-838f-bc675a586645.png)

## Expected result:
There should not be any extra text. The panel already says "Not verified yet".

## Reproduces how often: 
Always.

## Brave version (brave://version info)
Brave | 0.65.56 Chromium: 74.0.3729.75 (Official Build)nightly (64-bit)
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes, 0.65.56 nightly.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Not applicable.
- Is the issue reproducible on the latest version of Chrome? Not applicable.

### Additional Information
May be related to #1633, which is a missing translation issue.

**Comment by NejcZdovc** [comment]
closing as this was fixed with https://github.com/brave/brave-core/pull/2121
