### ISSUE TITLE
Move regional filter lists to new category, append country flags

### ISSUE THREAD

**Issue by blox814123** [brave/brave-browser#41318]
### Platforms

Linux, macOS, Windows

### Description

The filter lists are confusing, as they are all grouped together with no differentiation for users. I suggest looking at the way uBO does it. uBO groups regional lists into one category and adds a country flag to each list for better usability.

**Comment by rebron** [comment]
cc: @ShivanKaul @antonok-edm

**Comment by ShivanKaul** [comment]
This is a dupe of https://github.com/brave/brave-browser/issues/41233
