### ISSUE TITLE
[cr130] Update Settings -> Search -> Search engine setting text

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#41317]
### Description

In cr130, the text for default search engine setting changed from:
```
Normal Window - Search engine used in the address bar [Learn more]
```
to
```
The search engine you choose will be used for features like searching from the address bar and from images on web pages. [Learn more]
```
@emerick indicated that the new text regarding search from images is likely related to Google Lens.
Since we disable Google Lens, we need to modify the text to fit our needs.

@rebron, could you, please, provide the new text (or should we go back to the old text)?

STR:

1. Start Brave
2. Navigate to brave://settings/search
3. Observe `Search engine` setting description.

**Comment by emerick** [comment]
Related to https://github.com/brave/brave-browser/issues/41346, actually.

**Comment by kjozwiak** [comment]
The above requires `1.71.116` or higher for `1.71.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.71.116 Chromium: 130.0.6723.58 (Official Build) (64-bit)
-- | --
Revision | 789393dd90da88a1f9abf5a7d05fd8ccff76afa2
OS | Windows 10 Version 22H2 (Build 19045.5011)
```
Confirmed that the old text `Normal Window - Search engine used in the address bar. [Learn more]` is restored in Normal widow search settings:

![Image](https://github.com/user-attachments/assets/445ac0aa-d3de-4084-a335-951cbce90149)
