### ISSUE TITLE
[Vertical Tabs]: Vertical tabs sometimes crash when getting moved from one side to the other

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#41312]
1. Open a new profile
2. Enable vertical tabs
3. In settings, change the side vertical tabs show on

Expected:
Browser does not crash

Actual:
Browser sometimes does crash - this doesn't seem to happen in release

**Note for QA:** this is pretty hard to repro, so I think if it doesn't crash after this lands this should be fine (even if you can't repro the original issue). It seems to depend on the compiler and whether it was compiled in release mode.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.90 Chromium: 130.0.6723.70 (Official Build) beta (64-bit)
-- | --
Revision | 5f14a2225ebf4fcd654e064bde93e77fcc5d8f39
OS | Windows 11 Version 23H2 (Build 22631.4391)
```

1. installed 1.72.90
2. launched Brave
3. opened few tabs 
4. enabled vertical tabs via context menu
5. opened brave://settings/appearance
6. switched to `Show on the right` in the `Use vertical tabs`
7. switched to `Show on the left` again 
8. repeated the steps 6-7 few times.

#### Confirmed Brave is not crashed switching from right to left and vice versa.

https://github.com/user-attachments/assets/af5f0f56-c5e5-4de4-9fad-c643d6d940ba
