### ISSUE TITLE
[Rounded Corners]: In rounded corners mode, there's no separation between the web_contents and the browser chrome

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#41313]
1. In light mode, with brave://flags/#brave-web-view-rounded-corners enabled
2. Navigate to https://google.com

Expected:
There is some kind of separation between the webcontents and the browser chrome

Actual:
There is not:

![image](https://github.com/user-attachments/assets/e952f8dd-b7e9-41c2-bfd4-15630678a6c3)

**Comment by simonhong** [comment]
I can see space between web contents and sidebar in any theme.
<img width="1339" alt="image" src="https://github.com/user-attachments/assets/60be6d27-3812-4ba9-9272-ec9da64610f2">
<img width="1331" alt="image" src="https://github.com/user-attachments/assets/e5b00b1b-2413-4109-8fa9-39c950ac349b">

When vertical tab is enabled, there is no left-side space of web contents. I think this is the issue.
<img width="679" alt="image" src="https://github.com/user-attachments/assets/7cbf2f1c-b450-4277-a055-74a5c153c07e">
<img width="861" alt="image" src="https://github.com/user-attachments/assets/ca734252-89c7-4fa8-8d61-1af86cf843de">

**Comment by fallaciousreasoning** [comment]
@simonhong yeah you're right - the issue was there were no margins around the webcontents - I've added them in https://github.com/brave/brave-core/pull/25738. Mind taking a look and seeing what you think?

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.72.90 Chromium: 130.0.6723.70 (Official Build) beta (64-bit)
-- | --
Revision | 5f14a2225ebf4fcd654e064bde93e77fcc5d8f39
OS | Windows 11 Version 23H2 (Build 22631.4391)
```
