### ISSUE TITLE
[Wallet/iOS] Better error message for adding duplicated user asset. 

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#41319]
### Description

User friendly error message for adding duplicate user asset. 

### Steps to reproduce

1. open wallet
2. add a user assets that already exists 

### Actual result

Wallet showing an error message implied they needed to retry

### Expected result

Wallet should show an error message implying asset already existed. 

### Reproduces how often

Easily reproduced

### Brave version

all 

### Device/iOS version

all 

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by srirambv** [comment]
Verification passed on iPhone 13 running 1.74 (46)
- Verified steps from [brave/brave-core#25846](https://github.com/brave/brave-core/pull/25846)
- Verified error message is shown when adding an existing Token/NFT
- Verified Add button is disabled when error message is shown
- Verified no error message is shown when adding a token/NFT that is not available/already added

Tokens | NFT
-- | --
<video src=https://github.com/user-attachments/assets/6e3df155-6646-4125-8ddb-b1da5926b3d6> | <video src=https://github.com/user-attachments/assets/51da4ad8-45e3-4eb6-a77b-638d42f3901a>
