### ISSUE TITLE
Ads are enabled by default after update to 0.63.x

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4131]
## Description 
When you update from a version where Ads is not available, the Ads toggle gets turned on without user choice.

## Steps to Reproduce

1. Remove any existing Beta installs/profiles.
2. Clean install https://github.com/brave/brave-browser/releases/tag/v0.61.48 (this is a Beta version where Ads are disabled, I don't know of any more recent beta versions where this is the case)
3. Launch and enable Rewards. Note, can't enable Ads thru UI.
4. Go to brave://settings/help
5. Update to latest Beta on update channel (should be 0.63.x)
6. Relaunch, go to brave://rewards

Another way to reproduce is:
1. Install release channel version 0.62.51
2. Enable Rewards, note, can't enable Ads thru UI.
3. Close Brave.
4. Rename release channel version to be a beta profile
5. Launch Beta version 0.63.x.
6. Navigate to brave://rewards --> Ads are enabled.

## Actual result:
Ads is toggled to on and Ads will begin being served to user.

## Expected result:
Ads should not be toggled on.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.63.40 Chromium: 74.0.3729.61 (Official Build) beta(64-bit)
-- | --
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Mac OS X

### Reproducible on current release:
n/a, Ads not enabled on current release
- Does it reproduce on brave-browser dev/beta builds? yes, reproduced on Beta

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @jsecretan @brave/legacy_qa

**Comment by btlechowski** [comment]
Reproduced on

Brave | 0.63.44 Chromium: 74.0.3729.75 (Official Build) beta (64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Windows 10 OS Build 17134.523

**Comment by tmancey** [comment]
@LaurenWags this issue will be resolved by https://github.com/brave/brave-browser/issues/3967

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.46 Chromium: 74.0.3729.91 (Official Build) (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Mac OS X

* Verified on Release channel. Verified when updating from 0.62.51 to 0.63.46 Ads were not enabled by default when Rewards had been enabled on 0.62.51.
