### ISSUE TITLE
`xcar.com.cn` is suggested for US users when they type `car` in the URL search bar

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#41322]
### Description

`xcar.com.cn` is suggested for US users when they type `car` in the URL search bar. This happens for new installs with `default` Brave settings or when `Show top sites suggestions` is **ON** and `Show search suggestions` is **ON** or **OFF**.

### Steps to reproduce

1. Fresh install Brave
2. Go through onboarding
3. Type `car` in the URL search bar > *Observe `xcar.com.cn` website is suggested*

### Actual result

When `Show top sites suggestions` is **ON**, `xcar.com.cn` is suggested for US users when they type `car` in the URL search bar.

-----------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/b028396a-d127-46f9-a373-63ea30b9ca3e) | ![2](https://github.com/user-attachments/assets/d1de2749-cbd7-483d-835b-c96135049158) | ![3](https://github.com/user-attachments/assets/7ab2c1dc-b5a2-4f84-9c0b-2971e775c4ac) | ![4](https://github.com/user-attachments/assets/d12a1f70-15c2-45d5-a17d-5e939aa03201) |

https://github.com/user-attachments/assets/f37498df-6b0b-4517-95ab-44200bb79107

### Expected result

`xcar.com.cn` must not be suggested for US users when they type `car` in the URL search bar.

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.70.119
Chromium: 129.0.6668.70 (Official Build) (64-bit) 

### Device

- Brand/Model: ANY
- Android version: ANY

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by deeppandya** [comment]
Closing the issue as expected. `xcar.com.cn` is a part of alexa1-10000-urls.
