### ISSUE TITLE
Sync should show warning not to share the code with anyone

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#4132]
STR:
1. Go to brave://sync
2. Click 'start a new chain'
3. Click either desktop or mobile
4. It shows the sync code (either code words or a QR code) without any type of warning that this is a sensitive encryption key.

Impact: Someone could accidentally share the code with Brave (ex: in a support request) which gives us the access needed to decrypt their sync data. The user has no idea the sync words are security sensitive.

Desired outcome: There should be some kind of bold warning text in this modal.
<img width="631" alt="Screen Shot 2019-04-16 at 12 44 36 PM" src="https://user-images.githubusercontent.com/549654/56239562-31bda480-6046-11e9-995f-43b606643aef.png">

**Comment by diracdeltas** [comment]
Note: this needs to also be fixed in Android which presumably uses the same text. (and iOS whenever it launches)

**Comment by rebron** [comment]
![Screen Shot 2019-04-16 at 12 51 57 PM](https://user-images.githubusercontent.com/5951041/56239682-82cd9880-6046-11e9-80af-46594fbab103.png)
Muon text for reference.

**Comment by rebron** [comment]
Suggested text for this page:
**Treat this code like a password.** If someone gets ahold of it, they can read and modify your synced data.

Reference for what we mention in Wallet:
<img width="611" alt="Screen Shot 2019-04-16 at 2 36 24 PM" src="https://user-images.githubusercontent.com/5951041/56316360-ed4a0b80-610e-11e9-8080-11658675bff2.png">

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.65.95 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Verified STR from description, logged #4490, #4491
