### ISSUE TITLE
Current Release channel .deb is corrupt

### ISSUE THREAD

**Issue by texastoast** [brave/brave-browser#4133]
## Description 

Attempting to install the release version on Ubuntu fails due to a corrupt release archive.

__Affected archive: brave-browser_0.62.51_amd64.deb__

## Steps to Reproduce

   1. Follow Release Channel install instructions for Ubuntu 16.04+ on this page: https://brave-browser.readthedocs.io/en/latest/installing-brave.html#beta-channel-installation
   2. When performing the 'apt update' step, an error is returned.

*- or -*
   
  1. Download the .deb file directly from https://github.com/brave/brave-browser/releases/download/v0.62.51/brave-browser_0.62.51_amd64.deb
  2. run 'sudo dpkg -i path/to/brave-browser_0.62.51_amd64.deb'
  3. error is returned

## Actual result:

When using apt:

`
E: Failed to fetch https://brave-browser-apt-release.s3.brave.com/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (1378 != 5381). Mirror sync in progress? [IP: 199.232.34.217 443]
   Hashes of expected file:
    - Filesize:5381 [weak]
    - SHA512:bea3d322d648dbcf73e99adbcd06b826556f8dbea3671103b7ea821ff7cac37d3e93c96b980712e8c6f320fca4015426ffb7de7bd4ad8bcdb1e4ce1e4e9c0df1
    - SHA256:2a58e33ea7a3bc975cb5bad394508558ab8f4bb0e36d6715ba3cd9c71ab7b743
    - SHA1:28071e8f1c1939aaefc37c83a49396ac33b44f5d [weak]
    - MD5Sum:d20bb0b1d3f89994f054064aa49c14d4 [weak]
   Release file created at: Thu, 11 Apr 2019 21:59:02 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
`

When using downloaded .deb:

`
Preparing to unpack brave-browser_0.62.51_amd64.deb ...
Unpacking brave-browser (0.62.51) ...
dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg: error processing archive brave-browser_0.62.51_amd64.deb (--install):
 cannot copy extracted data for './opt/brave.com/brave/icudtl.dat' to '/opt/brave.com/brave/icudtl.dat.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 brave-browser_0.62.51_amd64.deb
`

## Expected result:

I would expect either method to complete without presenting errors.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

0.62.51

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

Beta builds are ok, it just seems like the .deb is corrupt.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

n/a, n/a

**Comment by rebron** [comment]
cc: @mbacchi Key change issue?

**Comment by fmarier** [comment]
@texastoast Are you still having this problem?

It works fine on my Ubuntu 18.04 laptop. It's possible you tried to update while we were pushing out new packages.

**Comment by texastoast** [comment]
I had installed the beta channel release after encountering the error. I just attempted to install the Release channel again using the instructions on https://brave-browser.readthedocs.io/en/latest/installing-brave.html#beta-channel-installation and it worked fine, so whatever caused the issue either was resolved or was only temporary. I will close the issue.

**Comment by fmarier** [comment]
Thanks for the confirmation @texastoast. I'm glad it's now working for you too!
