### ISSUE TITLE
Add metric for Sync join type

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#41336]
Add weekly ephemeral metric:

If you enabled Sync this week, did you create a new chain or join an existing chain?
`Brave.Sync.JoinType`

1. Created new chain
2. Joined existing chain

cc @aguscruiz

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.72.87 Chromium: 130.0.6723.70 (Official Build) beta (64-bit)
-- | --
Revision | d7efa3dbae2fa83142b51cea45f023f01d3eeb33
OS | Windows 10 Version 22H2 (Build 19045.5011)

```

<details>
<summary>Brave.Sync.JoinType_1_</summary>

</details>

<details>
<summary>Brave.Sync.JoinType_2_</summary>

</details>

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPhone 8 version 16.7.10` running `Bravemonoarm64.apk_1.73.86`

<details>
<summary>Brave.Sync.JoinType_1_PASSED</summary>

1. Clean profile 1.73.86
2. Open brave://local-state
3. Look for the metrics `Brave.Sync.JoinType`
4. Confirmed that metrics isn't shown under local state file
5. Create a new sync chain
6. Reload brave://local-state file
7. Confirmed that the metrics `Brave.Sync.JoinType` response value is `1` as expected
![Image](https://github.com/user-attachments/assets/7017ef64-e387-4300-8f66-61d723883996)


</details>

<details>
<summary>Brave.Sync.JoinType_2_PASSED</summary>

1. Clean profile 1.73.86
2. Open brave://local-state
3. Look for the metrics `Brave.Sync.JoinType`
4. Confirmed that metrics isn't shown under local state file
5. Join the existing sync chain
6. Reload brave://local-state file
7. Confirmed that the metrics `Brave.Sync.JoinType` response value is `2` as expected

![Image](https://github.com/user-attachments/assets/997231a6-128c-46b4-9e10-26f06225a671)

</details>
