### ISSUE TITLE
Refactor `SidebarContainerView` to not use `SidePanelRegistryObserver`

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#41342]
### Description

`SidebarContainerView` listens `SidePanelRegistryObserver` to stop observing its `SidePanelEntry`s.
However, upstream(`cr131`) deleted `SidePanelRegistryObserver`.
https://chromium-review.googlesource.com/c/chromium/src/+/5884960

We should make `SidebarContainerView` works w/o `SidePanelRegistryObserver`.

cc @cdesouza-chromium @mkarolin

**Comment by simonhong** [comment]
As this issue is blocker for `cr131`, working on this now.

**Comment by LaurenWags** [comment]
Requires 1.72.89 or higher for verification 👍🏻

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.90 Chromium: 130.0.6723.70 (Official Build) beta (64-bit)
-- | --
Revision | 5f14a2225ebf4fcd654e064bde93e77fcc5d8f39
OS | Windows 11 Version 23H2 (Build 22631.4391)
```

Installed 1.72.90
launched Brave
clicked on each sidebar icon as below

#### Confirmed Sidebar functionality worked as expected


**_Leo_**

example | example | example 
----- | ------ | ------
![Image](https://github.com/user-attachments/assets/9878d2b6-6e30-4a9a-aec1-bdcdf54ee2e1)|![Image](https://github.com/user-attachments/assets/ad656448-916b-449a-8ee6-026228aafcf4)|![Image](https://github.com/user-attachments/assets/0cdfe496-be6d-4356-8933-26bc547ab1d6)


**_Brave talk_**

Light| Dark
----- | ------
![Image](https://github.com/user-attachments/assets/e502a9ef-6392-4982-a602-df08fe3b04a2)|![Image](https://github.com/user-attachments/assets/27ed1408-d798-412f-912c-2bb5874972ea)

**_Wallet_**

Light| Dark
----- | ------
![Image](https://github.com/user-attachments/assets/a80d6755-e96c-48b6-979b-581549b53f64)|![Image](https://github.com/user-attachments/assets/8fb24755-37f6-4663-b223-066bbb865623)


**_Bookmarks_** 

Light| Dark
----- | ------
![Image](https://github.com/user-attachments/assets/4705d16b-160a-4a0f-9357-f00bc659e262)|![Image](https://github.com/user-attachments/assets/49cb03b3-1959-48cf-b88b-2bc11a69f7bc)


**_Reading List_**

Light| Dark
----- | ------
![Image](https://github.com/user-attachments/assets/575c83a3-8813-4c33-96ef-b08a4d8f5db6)|![Image](https://github.com/user-attachments/assets/3e63e56e-ba6f-4b30-a57a-4a427c3c7a42)

**_Playlist_**

Light| Dark
----- | ------
![Image](https://github.com/user-attachments/assets/6ffd9738-0b0f-4fb2-a15f-4654f616fec0)|![Image](https://github.com/user-attachments/assets/0282a2e4-8370-4b65-b06f-77866eff2b37)


**_New Window_**

Leo | Talk | Wallet | Bookmarks | Reading List 
---- | ------ | ------ | ----- | ------
![Image](https://github.com/user-attachments/assets/84157443-63bc-4f91-b413-ddea04b8b1e1)|![Image](https://github.com/user-attachments/assets/5d795dab-dc49-4db4-b08c-1b0b27cbe839)|![Image](https://github.com/user-attachments/assets/30fe55c7-dcf3-49ab-a61a-59178c53ec46)|![Image](https://github.com/user-attachments/assets/159556ed-c2d2-4d48-a738-a85faed91940)|![Image](https://github.com/user-attachments/assets/ca9cd0f8-f473-464c-9084-73dc6a91cc79)


**_Private window_**

Talk | Wallet | Bookmarks | Reading List 
---- | ------ | ------ | ----- 
![Image](https://github.com/user-attachments/assets/789c8443-48da-4e27-83f7-64303e194d67)|![Image](https://github.com/user-attachments/assets/c0018c3e-6708-4040-9ac4-6066092c55e1)|![Image](https://github.com/user-attachments/assets/8bc11bc1-ba41-4aca-8828-6e4531e8e883)|![Image](https://github.com/user-attachments/assets/e8269cc2-ee0e-415b-a215-bae5a5c4306a)

**_New private window with Tor_**

Talk | Wallet | Bookmarks | Reading List 
---- | ------ | ------ | ----- 
![Image](https://github.com/user-attachments/assets/d0daf935-b52c-4d39-9c74-4f62d6b2068e)|![Image](https://github.com/user-attachments/assets/fa08a606-39cd-4a5b-b26f-5240da012ff6)|![Image](https://github.com/user-attachments/assets/f7700bef-ed68-459d-8406-1fc259265cfc)|![Image](https://github.com/user-attachments/assets/7bc54387-571c-47f6-8fe0-571418084419)
