### ISSUE TITLE
[C130] - `Change` button via brave://settings/search is inherited from CR130

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#41346]
### Description

Found while testing https://github.com/brave/brave-browser/issues/41325

CR 130 - `Change` button is inherited from CR 130

### Steps to reproduce

1. Clean or upgraded profile `1.72.48` CR130
2. Open brave://settings/search

### Actual result

`Change` button via brave://settings/search is inherited from CR130

![image](https://github.com/user-attachments/assets/1b03854c-03f2-4ec4-951c-3c0356007293)

### Expected result

not sure about the expected results

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave	1.72.48 Chromium: 130.0.6723.19 (Official Build) nightly (64-bit) 
Revision	70b441e85b783a65b0088d92c496fa56d6509945
OS	Linux

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @emerick @rebron

**Comment by kjozwiak** [comment]
As discussed via the b-b call, we'll keep the above change. However, we'll need to change the PB selection to use the same UI/UX. This will be done/addressed via https://github.com/brave/brave-browser/issues/41499.
