### ISSUE TITLE
Editing a custom model and saving it still shows up when trying to add a new model

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#41345]
### Description

Editing a custom model and saving it still shows up when trying to add a new model

### Steps to reproduce

1. Add a custom model
2. Edit the model
3. Click on Save changes to close edit screen
4. Click on Add model
5. Shows Edit model screen with prefilled info
6. Click on Close
7. Edit existing model 
8. Close on the edit model screen
9. Click on Add model, shows screen for Adding a new model

### Actual result

https://github.com/user-attachments/assets/daddf315-f43b-4a7f-86a7-24c2cb60983d

### Expected result

Add model should always show the add new model irrespective of how the edit model screen is closed either by Save or Close

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.71.102 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | d901535b1091c5f39eb2b5426b8fa8e7f3c5edf0
OS | Windows 11 Version 23H2 (Build 22631.4169)

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @rebron @darkdh @mattmcalister @brave/qa-team

**Comment by aguscruiz** [comment]
I think it'll be a better experience if we do it like in my design where adding/editing a model happens in a new page. It'll be an even better experience once we add more options to the advanced settings like we're planning to. 

cc @petemill @LorenzoMinto 

Design:
https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/%F0%9F%94%84-Leo-%5BIN-PROGRESS%5D?node-id=3249-1029&t=Q9SIskItAPqJtDyF-1

Advanced options mock:
https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/%F0%9F%94%84-Leo-%5BIN-PROGRESS%5D?node-id=5242-36725&t=Q9SIskItAPqJtDyF-1

**Comment by mattmcalister** [comment]
@aguscruiz agreed, although maybe @jonathansampson can fix this little bug for now...?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.5 Chromium: 131.0.6778.69 (Official Build) beta (64-bit)
-- | --
Revision | fbd7c390a7daa54f1aac2c769076d3fecf7c7fc7
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from issue description
- Verified editing a custom model and saving it doesn't show when trying to add a new model
- Verified new model only shows when clicking on Add new model

https://github.com/user-attachments/assets/c5849421-b221-461e-93f3-c1c3b7fee912
