### ISSUE TITLE
[Wallet/iOS] User Assets are deletable 

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#41357]
### Description

Wallet should only provide deletion option for custom user assets

### Steps to reproduce

1. Open wallet and login with QA wallet 
2. Let the wallet loads all the auto-discovery assets 
3. Open edit user assets
4. Find BAT on Ethereum and try to swipe row to the left 

### Actual result

Deletion option is available 

### Expected result

Deletion option should be unavailable 

### Reproduces how often

Easily reproduced

### Brave version

1.70.x and after

### Device/iOS version

all

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by nuo-xu** [comment]
Update: will match desktop only allow deletion on NFTs. Reference: https://github.com/brave/brave-core/blob/087482aabf21a34d460885e1355f9b1c21f5047e/components/brave_wallet_ui/components/desktop/popup-modals/edit-visible-assets-modal/virtualized-visible-assets-list.tsx#L62

**Comment by kjozwiak** [comment]
The above requires `1.70.126` or higher for `1.70.x` verification 👍 The crash that @srirambv found while verifying the above will be fixed via https://github.com/brave/brave-core/pull/25804 and will also be uplifted into `1.71.x` & `1.70.x` via https://github.com/brave/brave-core/pull/25884 & https://github.com/brave/brave-core/pull/25885.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18` using version `1.70 (126)`

- Verified STR in test plan mentioned in https://github.com/brave/brave-core/pull/25805#issue-2564994914
   - Ensured that only NFT assets are deletable
   - **[FAILED]** Ensured that crash does not occur when swiping to delete NFT assets.

example | example | example
---|---|---
![Image](https://github.com/user-attachments/assets/22e2cc1c-b61a-48c1-8d1c-ac97215e06a4) | ![Image](https://github.com/user-attachments/assets/12e0c631-65ee-46c3-81c8-445915866b25) | ![Image](https://github.com/user-attachments/assets/2ce0387e-7e7c-4565-a80a-d651558bc4b7)
