### ISSUE TITLE
Extensions UI in Settings Page

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#4135]
## Description 
UI for Extensions is visible in other settings pages.

## Steps to Reproduce
1. Navigate to brave://settings/passwords
2. Scroll down

_Note: This happens for other pages as well, such as brave://settings/payments, brave://settings/addresses, brave://settings/fonts, brave://settings/searchEngines, etc._

## Actual result:
An extension UI component occludes the page content.

![extensions-in-passwords](https://user-images.githubusercontent.com/815158/56247179-a0602980-6069-11e9-843f-854a9a9c6084.gif)

## Expected result:
No extension component should be displayed.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
0.65.56

### Reproducible on current release:
Yes

**Comment by bsclifton** [comment]
This is a dupe - fixed by recent work landed by @petemill 😄
