### ISSUE TITLE
[Follow up to #41211] Icon colors are inverted if installing Brave while icon style is set to `Automatic`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#41375]
### Description

Follow-up to #41211.

### Steps to reproduce

1. Customize home screen
2. Select `Automatic` icon style
3. Install Brave `1.70 (119)` or higher > *Observe*

### Actual result

Icon colors are inverted if installing Brave while the icon style is set to `Automatic`.

--------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/e903c5fa-5f9a-4c89-a6d4-ee1f7e843b1f) | ![2](https://github.com/user-attachments/assets/cddf2c25-f53c-4697-988f-3d9d9fa760b2) |

### Expected result

Brave's icon must have propper colors (not inverted).

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.70 (123)
BraveCore: 1.70.123 (129.0.6668.89)

### Device/iOS version

iPad Mni (6th gen) / iPadOS 18

### Affected browser versions

- [ ] latest AppStore
- [X] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kylehickinson** [comment]
@hffvld I've seen weird bugs with the iOS 18 home screen after installing updates where it displays the wrong icon for a bit. We don't control anything past providing an icon when compiling so we can't really fix this, will be up to Apple. If you change appearances/toggle dark mode on/off or even just leave it for a bit it corrects itself
