### ISSUE TITLE
[Nala]: Base palette is slightly too red after the update

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#41370]
@aguscruiz and I have been discussing this and I think this is because we're not overriding Neutral94 in Nala (it's being generated via the material ui theme builder. 

@aguscruiz is fixing this in Nala but for now this change will fix it and be easy to uplift to 1.71

**Comment by LaurenWags** [comment]
Requires 1.71.106 or higher for verification 👍🏻

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.112 Chromium: 130.0.6723.44 (Official Build) (64-bit)
-- | --
Revision | 7d51df656b247f9432ee714a6d160142a1e11c13
OS | Windows 11 Version 23H2 (Build 22631.4317)
```

Verified the PR using TestPlan from https://github.com/brave/brave-core/pull/25783#issue-2562650730

Visually inspected omnibox and it looked slightly less red in `1.71.112` than in `1.71.104` in Light mode


![Image](https://github.com/user-attachments/assets/197c82de-a4a5-4631-af8a-2f5e04ca008d)
