### ISSUE TITLE
Focus rings on more info icon doesn't align the icon at centre

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#41379]
### Description

Focus rings on more info icon doesn't align the icon at centre

### Steps to reproduce

1. Open Settings->Leo
2. Select Add model
3. Tab select info button
4. Focus ring doesn't align the icon at centre

### Actual result

![image](https://github.com/user-attachments/assets/e6d1f688-cf28-4b50-9c5b-28dd57bfa62e)

### Expected result

Centre align icons similar to other settings 
![image](https://github.com/user-attachments/assets/d21c2316-41ff-42bd-a430-99aa8bfc0feb)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.71.102 Chromium: 129.0.6668.70 (Official Build) beta (64-bit)
-- | --
Revision | d901535b1091c5f39eb2b5426b8fa8e7f3c5edf0
OS | Windows 11 Version 23H2 (Build 22631.4169)

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @aguscruiz @rebron @MadhaviSeelam

**Comment by aguscruiz** [comment]
@fallaciousreasoning @petemill May be a Nala button issue?

**Comment by fallaciousreasoning** [comment]
This is caused because the `cr_icon` is 18x20 pixels and the actual button is 18x18 pixels, so the outline isn't outside the icon.

We could fix this by:
1. Adding some padding to the button
2. Using a `leo-icon` instead of a `cr-icon` (this would be my preference)

**Comment by aguscruiz** [comment]
> This is caused because the `cr_icon` is 18x20 pixels and the actual button is 18x18 pixels, so the outline isn't outside the icon.
> 
> We could fix this by:
> 
> 1. Adding some padding to the button
> 2. Using a `leo-icon` instead of a `cr-icon` (this would be my preference)

Makes sense to fix it properly like you suggest @fallaciousreasoning

**Comment by fallaciousreasoning** [comment]
Interesting - definitely shows up for me on Linux
![image](https://github.com/user-attachments/assets/f53563b2-c689-4378-9e30-dc15fced9063)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.72.85 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 2c872aa4d2694bc73ec58e3b14538a4008a6381e
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from issue description
- Verified focus rings on more info icon shows correctly
- Encountered [#41853](https://github.com/brave/brave-browser/issues/41853)

https://github.com/user-attachments/assets/7e2af0a2-64a6-4ce3-ab64-908cbb91ebb9

-------
Verification passed on

Brave | 1.72.85 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 2c872aa4d2694bc73ec58e3b14538a4008a6381e
OS | Linux

- Verified steps from issue description
- Verified focus rings on more info icon shows correctly
- Encountered [#41853](https://github.com/brave/brave-browser/issues/41853)

https://github.com/user-attachments/assets/e9a9393e-0fe9-4c86-9146-08b347b7aaab

-------
Verification passed on

Brave | 1.72.85 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 2c872aa4d2694bc73ec58e3b14538a4008a6381e
OS | macOS Version 15.0.1 (Build 24A348)

- Verified steps from issue description
- Verified focus rings on more info icon shows correctly
- Encountered [#41853](https://github.com/brave/brave-browser/issues/41853)

https://github.com/user-attachments/assets/56905f87-9698-4b25-bf11-655d5d58d4e6
