### ISSUE TITLE
[Wallet/iOS] Crash happens when delete NFT from Edit User Assets

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#41387]
### Description

Crash happens when delete NFT from Edit User Assets

### Steps to reproduce

1. Open Wallet
2. Make sure you have some NFTs in your wallet
3. Open Edit User Assets Screen from Portfolio 
4. Find a NFT row and swipe to the left to delete this NFT

### Actual result

App will crash most of the time following above STR

### Expected result

List should be refreshed without crashing the app

### Reproduces how often

Easily reproduced

### Brave version

1.70.x and later

### Device/iOS version

all

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.70.127` or higher for `1.70.x` verification 👍

**Comment by Uni-verse** [comment]
Verified per https://github.com/brave/brave-browser/issues/41357#issuecomment-2415142310 on `iPhone 12` running `iOS 18` using version `1.70 (127)`
