### ISSUE TITLE
Notification Ads viewed counter is not increased it's always `0` in Rewards 3.0 UI

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#41382]
### Description

Found while testing https://github.com/brave/brave-browser/issues/40563

Notification Ads viewed counter is not increased it's always `0` in Rewards 3.0 UI

### Steps to reproduce

1. Clean profile 1.71.x
2. Launch brave using staging cmd line flags `brave.exe --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=9,"*/brave_rewards/*"=9,"*/bat-native-ads/*"=9,"*/bat-native-confirmations/*"=9,"*/brave_ads/*"=9,"*/brave_user_model/*"=9 --rewards=staging=true,rewards=debug=true,reconcile-interval=3`
3. Enable the new rewards UI flag via brave://flags
4. Enable rewards and connect uphold custodian
5. View couple of notification ads
6. `Notification ads` counter is not increased, it's always `0`

### Actual result

![image](https://github.com/user-attachments/assets/5ef84720-35b3-44fc-a2da-40c59f2e3bab)

### Expected result

The counter should be increased based on the no of ads viewed

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.71.104 Chromium: 129.0.6668.89 (Official Build) beta (64-bit)
-- | --
Revision | 3da42496f366e4dc607c58cfdd95ce3f5064c171
OS | Windows 10 Version 22H2 (Build 19045.4894)

### Channel information

- [ ] release (stable)
- [X] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @Miyayes @zenparsing

**Comment by Miyayes** [comment]
Should be fixed in the latest nightly
