### ISSUE TITLE
Migrate adblock WebUI pages to be loaded through `TopChromeWebUIConfig`

### ISSUE THREAD

**Issue by cdesouza-chromium** [brave/brave-browser#41397]
### Description

Upstream is migrating away from `WebUIControllerFactory` as a method to load browser pages, and we should migrate our pages too.

**Comment by cdesouza-chromium** [comment]
Testing should be done by making sure that `brave://adblock` and `brave://adblock-internals` are accessible and working as normal.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.90 Chromium: 130.0.6723.70 (Official Build) beta (64-bit)
-- | --
Revision | 5f14a2225ebf4fcd654e064bde93e77fcc5d8f39
OS | Windows 11 Version 23H2 (Build 22631.4391)
```

1. Installed 1.72.90
2. launched Brave
3. opened `brave://adblock` in a new tab
4. confirmed page navigated to `brave://settings/shields/filters` and worked as expected
5. opened `brave://adblock-internals` in a new tab
6. confirmed page loaded as expected


step 4 | step 6
----- | ------
![Image](https://github.com/user-attachments/assets/363a0e60-5645-4e72-9002-b9f27b2a2888)|![Image](https://github.com/user-attachments/assets/83c1392e-f3b1-4473-8cb4-024019920415)
