### ISSUE TITLE
Update Wallet Panel Headers Style

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#41394]
### Platforms

Linux, macOS, Windows

### Description

We need to update the `Wallet` Panel `Header` style to match the new designs in figma

- Tabs to update: `Accounts`, Account Details`, `Activity`, `Explorer`, Token Details`
- Content should now be in a `Card` style format with the `Header` above and behind the `Card`

![Screenshot 36](https://github.com/user-attachments/assets/c2198ed9-e936-42d9-a579-1b9dba0801d9)
![Screenshot 37](https://github.com/user-attachments/assets/941d3f14-6264-4ebc-830b-802cd885ea82)
![Screenshot 38](https://github.com/user-attachments/assets/24e6969a-afd7-4392-9d47-228b67298eda)
![Screenshot 39](https://github.com/user-attachments/assets/4e3eb5ff-ebd0-437c-82b5-4c035deda7b9)
![Screenshot 40](https://github.com/user-attachments/assets/909f301a-095b-40cd-a70b-98381223676d)

**Comment by LaurenWags** [comment]
@Douglashdaniel please add the following required labels:
- `OS/Desktop` and/or `OS/Android` and/or `OS/iOS`

Thanks!

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.72.82 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 4f0233b15f1896e28ff5ce439de1f658a2ef2df0
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from [brave/brave-core#25818](https://github.com/brave/brave-core/pull/25818)
- Verified Wallet panel headers are as per new design

https://github.com/user-attachments/assets/0a159429-b2fe-4e6e-a8ec-8d9b7344ce69


-------
Verification passed on 

Brave | 1.72.82 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 4f0233b15f1896e28ff5ce439de1f658a2ef2df0
OS | Linux

- Verified steps from [brave/brave-core#25818](https://github.com/brave/brave-core/pull/25818)
- Verified Wallet panel headers are as per new design

https://github.com/user-attachments/assets/a3db8794-7ced-4f02-8dd5-82bcbde0c70f

-------
Verification passed on 

Brave | 1.72.82 Chromium: 130.0.6723.58 (Official Build) beta (arm64)
-- | --
Revision | 4f0233b15f1896e28ff5ce439de1f658a2ef2df0
OS | macOS Version 15.0.1 Build (24A348)

- Verified steps from [brave/brave-core#25818](https://github.com/brave/brave-core/pull/25818)
- Verified Wallet panel headers are as per new design

https://github.com/user-attachments/assets/49eca848-170b-4ce7-b925-529a2f6a21a8
