### ISSUE TITLE
Stub installer branding update

### ISSUE THREAD

**Issue by RyanJarv** [brave/brave-browser#414]
Opening this to cover the branding for the windows brave installer, right now it is just using what is default upstream.

From @bbondy on this we should reach out to @bradleyrichter or @jenn-rhim (hope I got the @'s right) regarding this.

Other tickets relating to the omaha client installer:
https://github.com/brave/brave-browser/issues/179
https://github.com/brave/brave-browser/issues/179

**Comment by bbondy** [comment]
As it turns out @RyanJarv mentioned on Slack that the stub doesn't have a placeholder for images, so to do something like that we'd have to create them. At the time of posting we were assuming that it was just replacing an existing missing resource. So closing this for now.
