### ISSUE TITLE
Improve toolbar icon sizing/balance

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#41405]
## Description 

The icon sizing for the shortcut button was a bit large which has led to [some discussion](https://bravesoftware.slack.com/archives/C07LWRLAYH5/p1727984631901409) about rebalancing the icon sizes in the toolbar in general. 

New expected changes:
![image](https://github.com/user-attachments/assets/a96bbab9-efb7-4ca5-a82a-c07eb8fa9ef2)

- Bottom toolbar icons when toolbars are split will stay their larger sizes
- Icons that show up in toolbar along with the URL bar will now be smaller
- Icons are now smaller when the unified toolbar is used

**Comment by Uni-verse** [comment]
In progress on iPhone / iPad using version 1.73 (89)

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iOS 17.5.1` using version `1.73 (89)`

Verified the following based on acceptance criteria in https://github.com/brave/brave-browser/issues/41405#issue-2566738869

- Bottom toolbar icons when toolbars are split will stay their larger sizes.
- Icons that show up in toolbar along with the URL bar will now be smaller.
- Icons are now smaller when the unified toolbar is used.

<hr>

**`Landscape - Unified bar`**

`1.71.x`
![Image](https://github.com/user-attachments/assets/b3365085-58cf-4e62-ba63-dda536895c7c)
`1.73.x`
![Image](https://github.com/user-attachments/assets/dfc1895d-9b86-4e1c-82c4-56c5fcf267af)


**`Split View - Landscape`** | **`Split View - Portrait`**
---|---
![Image](https://github.com/user-attachments/assets/2dcebd5a-b2c4-4292-a883-c7b0bbc426dc) | ![Image](https://github.com/user-attachments/assets/963c5809-9341-4a2e-9390-25af7998bb9b)

**`Slide Over - Landscape`** | **`Split View - Portrait`**
---|---
![Image](https://github.com/user-attachments/assets/5fb3c3bd-b6ce-4d92-93a0-78455f482d40) | ![Image](https://github.com/user-attachments/assets/5d725598-4f39-4c7d-a3bb-d86e7539d2ae)
