### ISSUE TITLE
Crash when opening 'Content Filtering' settings page [CR130] 

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#41404]
### Description

Crash when opening 'Content Filtering' settings page

Regression with CR130. This was also an issue with CR129, possibly related to https://github.com/brave/brave-browser/issues/41039

### Steps to reproduce

1. Install 1.72.60 (CR130)
2. Open Brave Shields & privacy -> Content Filtering
3. Observe

### Actual result

![Screenshot 2024-10-04 at 11 28 05 AM](https://github.com/user-attachments/assets/554ab7e5-5354-4cb2-928e-04af5b173c8b)

### Expected result

No crash

### Reproduces how often

Easily reproduced

### Brave version

1.72.60

### Device

- Brand/model: Samsung GS Tab 
- Android version: 13

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
Closing and labelling as a duplicate as the above will be fixed via https://github.com/brave/brave-core/pull/25812. We'll use https://github.com/brave/brave-browser/issues/41402 as the issue for QA verification.
