### ISSUE TITLE
CR130 - When download is paused the download manager windows turns grey instead of white

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#41401]
### Description

Found while testing https://github.com/brave/brave-browser/issues/40694

CR130 - When download is paused the download manager windows turns grey instead of white

### Steps to reproduce

1. Clean profile `1.72.60`
2. Download any file
3. Pause the download and check the download manager window

### Actual result

![image](https://github.com/user-attachments/assets/e81552db-df25-41fb-97cc-d00ed3c791f0)

### Expected result

![image](https://github.com/user-attachments/assets/17e3d5ef-f5da-4524-ab70-7f04ecda0969)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.72.60 Chromium: 130.0.6723.31 (Official Build) nightly (64-bit)
-- | --
Revision | e9a5f85df56e1d8f46bcb0e2dd0c38f22126d84b
OS | Windows 10 Version 22H2 (Build 19045.4894)

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @rebron @emerick @aguscruiz

**Comment by aguscruiz** [comment]
I don't mind it changing color, but we should use a lighter shade of gray. Let's try using `--leo-color-container-highlight`

**Comment by aguscruiz** [comment]
Note: Bookmarks has the same problem with the gray background on the top right button, should be a transparent background.

<img width="1417" alt="image" src="https://github.com/user-attachments/assets/81e28398-aaa0-45a1-b406-f6dc2480af26">

**Comment by kjozwiak** [comment]
The above requires `1.71.111` or higher for verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.112 Chromium: 130.0.6723.44 (Official Build) (64-bit)
-- | --
Revision | 7d51df656b247f9432ee714a6d160142a1e11c13
OS | Windows 11 Version 23H2 (Build 22631.4317)
```

Verified using STR from https://github.com/brave/brave-browser/issues/41401#issue-2566033337

Confirmed following:

- brave://bookmarks page:  3 dot menu is transparent
- brave://downloads page: Clear all button with white background
- downloads completed: white background
- downloads Canceled, Blocked, Paused, Retry:  No gray background shown


Paused | Resume | Cancel | Retry | Delete | brave://downloads | brave://bookmarks | example 
----- | ------ | ------  | ---- | ------ | ---- | ------- | ----------
![Image](https://github.com/user-attachments/assets/ad327d90-58a0-427f-9a8d-0dd52f9d8027)|![Image](https://github.com/user-attachments/assets/822a2373-aff5-43e4-b465-87ab63009e79)|![Image](https://github.com/user-attachments/assets/086dc420-3ccd-47da-abb3-9db65e8593a3)|![Image](https://github.com/user-attachments/assets/c3cd9384-7bac-48ec-a226-0395cbf317d9)|![Image](https://github.com/user-attachments/assets/d2a7d727-4b9b-4723-892b-33bd11b7dc9e)|![Image](https://github.com/user-attachments/assets/341dff85-aac2-459e-8cba-b137c54cd312)|![Image](https://github.com/user-attachments/assets/182ed3ae-e174-41b5-8a94-2d2dd88c4a63)|![Image](https://github.com/user-attachments/assets/6b3714f2-db13-4377-b5e6-a64756c838bc)
