### ISSUE TITLE
[AI Chat] Leo doesn't preserve newline characters

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#41409]
### Description

Leo does not preserve newline characters in the user's input. As such, pasting code, poetry, and more, will undesirably collapse everything into a single line.

### Steps to reproduce

1. Open Leo
2. Type a short line, hold shift and press enter/return twice, type another short line
3. Submit the message

### Actual result

Whatever the user enters into multiple lines will be collapsed into a single line.

### Expected result

If the user provided the content with newlines, the newline characters should be preserved.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.70.123 Chromium: 129.0.6668.89 (Official Build) (64-bit)
-- | --
Revision | 7c1bbf03546a64d969d010808e4f5c99fdf343bb
OS | Windows 10 Version 22H2 (Build 19045.4957)

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.11 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | c777fe11bc7afc00156e58af64a6a5bb9559da7d
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from issue description
- Verified Leo preserves new line characters in conversation

https://github.com/user-attachments/assets/3926a855-29e5-4efd-ad85-8f25c048c99d
