### ISSUE TITLE
[Cr130] `Safe Browsing` is broken in `Cr130`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#41407]
### Description

`Safe Browsing` is broken in `Cr130`.

### Steps to reproduce

1. Install and launch Brave with default settings
2. Go to https://testsafebrowsing.appspot.com
3. Open test links for `Android` > *Observe that no warning is shown*

### Actual result

`Safe Browsing` is broken in `Cr130`.

Issue is not reproducible with:
- Previous Brave builds with `Cr129`.
- Chrome with `Cr130`. 

-----------------

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/40998916-57fa-47cd-a55c-4bbe3667120a) | ![2](https://github.com/user-attachments/assets/616edb72-a2f8-4c3f-93d5-d7a1e8c5e909) | ![3](https://github.com/user-attachments/assets/f7a1bb16-6dd7-4996-af4c-f75875a83023) | ![4](https://github.com/user-attachments/assets/aabc30f4-c820-4513-bd5e-db9a70e4c489) | ![5](https://github.com/user-attachments/assets/91bb954a-d0bf-4820-9bd2-d413655d7b18) |

### Expected result

`Safe Browsing` must work, and the warning message must be seen when navigating to malicious websites.

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.72.60 
Chromium: 130.0.6723.31 (Official Build) canary (64-bit) 

### Device

- Brand/Model: ANY
- Android version: ANY

### Channel information

- [ ] release (stable)
- [ ] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.71.113` or higher for `1.71.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 15` using the following build(s):

```
Brave | 1.71.113 Chromium: 130.0.6723.58 (Official Build) (64-bit)
--- | ---
Revision | 3ee74228044546a84c661332ddb441a7a68108fa
OS | Android 15; Build/AP41.240823.009; 35; REL
```

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/25842#issue-2570058627, ensured that the interstitial pages are being displayed as per the following:

* ensured that clicking on `Back to safety` works without any issues/failures
* ensured that clicking on `Only visit this unsafe site` works without any issues/failures
* ensured that the interstitial pages re-appears once a user has restarted if they've proceeded to an unsafe website

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|-----------------
![Image](https://github.com/user-attachments/assets/3e9e63fb-15e9-4745-832c-d697403d6163) | ![Image](https://github.com/user-attachments/assets/c2798b48-5a1c-43d8-adab-2e434d27c023) | ![Image](https://github.com/user-attachments/assets/9d744fb3-d700-4814-bf6b-45fe7e68de05) |![Image](https://github.com/user-attachments/assets/431fea42-5e5b-4ddf-b672-71ad9fb8da48)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy Tab S8 Ultra` running `Android 14` using the following build(s):

```
Brave | 1.71.113 Chromium: 130.0.6723.58 (Official Build) (64-bit)
--- | ---
Revision | 3ee74228044546a84c661332ddb441a7a68108fa
OS | Android 14; Build/UP1A.231005.007; 34; REL
```

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/25842#issue-2570058627, ensured that the interstitial pages are being displayed as per the following:

* ensured that clicking on `Back to safety` works without any issues/failures
* ensured that clicking on `Only visit this unsafe site` works without any issues/failures
* ensured that the interstitial pages re-appears once a user has restarted if they've proceeded to an unsafe website

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|-----------------
![Image](https://github.com/user-attachments/assets/ab3be206-a421-4521-b521-b38052ce6c3c) | ![Image](https://github.com/user-attachments/assets/0a36eb2c-f49e-48f1-b8ac-eda52d70d903) | ![Image](https://github.com/user-attachments/assets/a5459dc6-ae63-4ba6-97b1-095890a69fca) | ![Image](https://github.com/user-attachments/assets/4ba2d2f9-e58d-4c92-85c9-459b49a6dd5c)
