### ISSUE TITLE
Shortcut button settings screen uses incorrect colors

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#41408]
## Description 

Not using the correct Brave colors on this settings screen

![image](https://github.com/user-attachments/assets/fd52ea61-1231-4ded-8389-b45879043437)

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7.1
Brave build: 1.72 (93)
BraveCore: 1.72.93 (131.0.6778.14)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Hamburger menu > Settings
3. Scroll to `Display` section
4. Shortcut Buttons > *Verify*

**ACTUAL RESULTS:**
- Verified that the correct colors were used on the `Shortcut Buttons` page.

---------------------------

|1.72.61|1.72.93|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/b6ed62ed-4939-44c4-bc09-20beee526b4f) | ![2](https://github.com/user-attachments/assets/8df5a722-b216-4439-8bf1-1ff298b0779f) |
