### ISSUE TITLE
Install Page As an app not working on latest brave

### ISSUE THREAD

**Issue by syscl** [brave/brave-browser#41411]
### Description

Thanks for such an amazing and speedy browser!

I installed gmail, gemini and many pages as a standalone app using `Cast, Save and Share` > `Install <website> As App` or `Create shortcut`. But after updating to [Version 1.70.123 Chromium: 129.0.6668.89 (Official Build) (arm64)](https://brave.com/latest/), opening gmail redirect me to open the page in the browser, and created shortcut does not work.

<img width="568" alt="image" src="https://github.com/user-attachments/assets/9a333105-8019-4b3e-a049-881206a39b2d">

### Steps to reproduce

1. On an order version than 1.70.123, install gmail as app
2. Update brave to latest
3. Open the standalone PWA

### Actual result

Open the app as a tab in the browser not standalone app anymore

### Expected result

Should open as an app

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

[Version 1.70.123 Chromium: 129.0.6668.89 (Official Build) (arm64)](https://brave.com/latest/)

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment]
cc: @emerick

**Comment by syscl** [comment]
Thanks @rebron and @emerick for the help! Are there any findings for the bug? Many of my friends are considering downgrading or changing the browser due to missing of this.

**Comment by emerick** [comment]
@syscl I'm not able to repro this problem, perhaps you can tell me what I'm doing wrong.

1. I installed 1.70.119
2. I visited gmail.com
3. I installed the PWA for gmail.com
4. I launched the PWA for gmail.com and verified it opened in a separate PWA window
5. I visited Help -> About and upgraded to 1.70.123
6. I launched the PWA for gmail.com and verified it opened in a separate PWA window

As far as I can tell, it's working correctly.

**Comment by syscl** [comment]
Thanks @emerick for the detail steps, unfortunately, I didn't even have the install PWA option on brave after updating to latest.

Here's a screenshot of the settings when opening gmail, there's no open as seperate window option
![Image](https://github.com/user-attachments/assets/40ae0e00-4c25-444c-b9a8-f1a850bff0c1)

As a comparison from chromium latest, this is the screenshot:
![Image](https://github.com/user-attachments/assets/b94ed551-e6d8-4c47-92fa-e4b214001d1c)

**Comment by emerick** [comment]
@syscl Yes, we don't currently have a menu option to install the PWA. But if you visit gmail.com and then type "install pwa" in the url bar, there is a "Quick Commands" option to install the PWA. You can use this as a workaround until we restore the menu option.

**Comment by Victor-root** [comment]
Hello,

I am experiencing the same issue, and it's really frustrating. Since the latest update, the option to install a website as an application (PWA) has disappeared. This feature was extremely useful, and it's quite annoying that it was removed, especially since the PWAs I had installed before the update still work perfectly.

Could you please provide some clarification on why this was removed, or if there's a way to bring it back? It feels like a regression, and it's affecting my workflow.

Thank you!

**Comment by fallaciousreasoning** [comment]
Hey, we've just opened some PRs for fixing https://github.com/brave/brave-browser/issues/40702 - hopefully they'll fix this too!

**Comment by syscl** [comment]
Hi @fallaciousreasoning thanks a lot for the fix! Currently, the `Version 1.71.121 Chromium: 130.0.6723.91 ` still has this issue

**Comment by fallaciousreasoning** [comment]
Yeah, I'm afraid it'll probably need to trickle in from Nightly, so might take a while to reach stable :/

**Comment by syscl** [comment]
thank you @fallaciousreasoning for the information, will keep an eye on it!

**Comment by fallaciousreasoning** [comment]
Its in 1.74 (current Beta version) - I'm going to close this issue (but we can keep commenting) since I think its fixed :smile:

**Comment by sridharsri32836-create** [comment]
Just go the MORE TOOLS -> SHOW APPS-> then you can see the app right click and create a short cut (This time it will be created as Web app)
