### ISSUE TITLE
add keyboard shortcut for exporting all bookmarks

### ISSUE THREAD

**Issue by hamirmahal** [brave/brave-browser#41412]
> If you wanted to add a command for exporting bookmarks and/or clearing downloads we'd definitely accept a PR

_Originally posted by @fallaciousreasoning in https://github.com/brave/brave-browser/issues/39489#issuecomment-2201389714_

**Comment by jonathansampson** [comment]
Doesn't build in its current state due to no `ExportBookmarks` member on the `chrome` namespace.

**Comment by bsclifton** [comment]
@hamirmahal I added a test plan to your top post - let me know what you think!

**Comment by hamirmahal** [comment]
It looks reasonable!

I just downloaded `brave-browser-nightly` and tried out the feature.

**Comment by hamirmahal** [comment]
# Screen Recording of Feature

This is on `brave-browser-nightly`.

https://github.com/user-attachments/assets/0b140c74-8322-4e8d-81fa-63c728b34ba3

**Comment by fallaciousreasoning** [comment]
Looks great!

**Comment by rebron** [comment]
![Image](https://github.com/user-attachments/assets/73d84306-dd53-49b7-8531-2c6fdef96b5c)

Beautiful. Works great. Thanks @hamirmahal

**Comment by hamirmahal** [comment]
You're welcome, @rebron.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.75.145 Chromium: 132.0.6834.57 (Official Build) nightly (64-bit)
-- | --
Revision | 4ecdecd1626892f9f317e9d8154c50cf8459d3bf
OS | Windows 11 Version 24H2 (Build 26100.2605)
```

1. Installed 1.75.145
2. launched Brave
3. added few bookmarks
4. opened `brave://settings/system/shortcuts` in a new tab
5. search by `export`
6. confirmed `Export all bookmarks` shortcut entry available
7. clicked `Add`
8. added shortcut (Cntrl + Shift + E) and clicked `Save`
9. opened a new tab
10. entered the shortcut ((Cntrl + Shift + E)) and saved bookmarks file
11. confirmed the Bookmarks file is saved as expected via brave://bookmarks


https://github.com/user-attachments/assets/69fff997-2e98-41fa-aabe-1019adf2fb5c
