### ISSUE TITLE
grant.rewards.brave.com broken & "Brave Ads paused" pop-up

### ISSUE THREAD

**Issue by raphaelp-github** [brave/brave-browser#41422]
### Description

Hi,

I'm having a problem with your captcha resolution page as part of a Brave Ads verification.

After clicking on “Resolve” in the pop-up, another pop-up appears, opening a page integrated with the Rewards feature. However, this one doesn't work and gives me an error. See the video screenshot : https://www.awesomescreenshot.com/video/32257266?key=9d18574e83ec417a15f55a2fd899d83f

Thanks,

### Steps to reproduce

1. Brave Rewards actived
2. Video screenshot : https://www.awesomescreenshot.com/video/32257266?key=9d18574e83ec417a15f55a2fd899d83f

### Actual result

Redirection ot [grant.rewards.brave.com](url) broken

### Expected result

Access to grant.rewards.brave.com in the integrated page

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.123 Chromium: 129.0.6668.89 (Build officiel) (64 bits) 

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [X] in the latest version of Chrome

**Comment by Miyayes** [comment]
Hi @raphaelp-github, thanks for writing. Are you on a VPN? If so, can you please try using a different output node, or disabling your VPN as part of this? It could be that your current VPN node is being blocked by our servers.

**Comment by raphaelp-github** [comment]
Hi @Miyayes ,

No, the result is identical, with or without active VPN & proxy.

**Comment by raphaelp-github** [comment]
Hi,

Nothing change in my side, but solved now!

![Image](https://github.com/user-attachments/assets/fcfdbb32-ce10-42f4-8840-806d35ae7c42)

Thanks!
