### ISSUE TITLE
media publisher info not shown in panel until you navigate away and come back

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4143]
## Description 
Sometimes media publisher info isn't displayed in the panel until you navigate away and come back to the page. This is not happening on 0.62.51, is happening on 0.63.x and above.

## Steps to Reproduce

1. Clean profile, launch Brave
2. Enable Rewards (I used panel)
3. Navigate to youtube
4. Search for someone’s channel (I used Jonathan Sampson, but you can search for others who have channels as well.)
5. Click on the channel in results list
6. Click on a video on page
7. Once page loads and video starts, click on BAT logo.
8. No publisher info in panel. Close panel, wait a few seconds, try again. Still no publisher info. 
9. Open a new tab.
10. Go back to YT video and click on BAT logo. Now publisher info displays in panel. 

## Actual result:
no publisher info in panel

## Expected result:
publisher info in panel the first time you open it

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.63.44 Chromium: 74.0.3729.75 (Official Build) beta(64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Mac OS X

Brave | 0.64.56 Chromium: 74.0.3729.75 (Official Build) dev(64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Mac OS X

### Reproducible on current release: no, does not reproduce on 0.62.51
- Does it reproduce on brave-browser dev/beta builds?  yes, both

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @brave/legacy_qa @NejcZdovc

**Comment by srirambv** [comment]
Reproduced on Linux running `0.63.44`. Issue happens for any channel video that is played after searching for the channel

**Comment by btlechowski** [comment]
Reproduced on

Brave | 0.63.44 Chromium: 74.0.3729.75 (Official Build) beta (64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Windows 10 OS Build 17134.523

Not reproducible on 


Brave | 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)
-- | --
Revision | e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}
OS | Windows 10 OS Build 17134.523

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.63.47 Chromium: 74.0.3729.108 (Official Build) (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Windows 10 OS Build 17134.523

- Verified the STR mentioned in the description
