### ISSUE TITLE
Cookie/Shields Issue

### ISSUE THREAD

**Issue by suuf** [brave/brave-browser#41437]
### Description

Hello, I am unsure of what the problem is exactly, I hope opening this issue is appropriate. 

Jira software cannot properly run on Brave with shields enabled at the moment. 

See incident on Oct 7, 2024, at [https://jira-software.status.atlassian.com/](https://jira-software.status.atlassian.com/).

### Steps to reproduce

1. Put Brave shields up
2. Open an issue on Jira Cloud

### Actual result

A `Something went wrong on our end` dialog overlaps the screen.

![Screenshot 2024-10-07 124840](https://github.com/user-attachments/assets/94803f54-3010-4e35-af8d-0fce08523aad)

### Expected result

No dialog overlapping the screen when Brave shields are up.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave: 1.70.123 Chromium: 129.0.6668.89 (Official Build) (64-bit) 
Revision: 7c1bbf03546a64d969d010808e4f5c99fdf343bb 
OS: Windows 11 Version 23H2 (Build 22631.4169)

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment]
cc: @ShivanKaul

**Comment by ShivanKaul** [comment]
@suuf is this still occurring? From the incident log on https://jira-software.status.atlassian.com/, it seems like Jira had a bad interaction with Brave and adblockers in general, which they fixed.

**Comment by suuf** [comment]
Hello, thanks for the reply. Yes, seems like this isn't happening anymore.

**Comment by ShivanKaul** [comment]
Thanks for reporting!
