### ISSUE TITLE
Missing minimize, fullscreen and close window icons in maximized window

### ISSUE THREAD

**Issue by mlec1** [brave/brave-browser#41430]
### Description

The minimize, full window and close window icons / buttons are missing (in the top right corner) when maximizing the window (click the middle button, between the close button and minimizing button in the top right corner).

### Steps to reproduce

1. Open a Window by maximizing it (click the middle button, between the close button and minimizing button in the top right corner)
2. I am using the vertical tab if it can be a reason. With horizontal tab, I can't even find the icons.

### Actual result

Here is a window not in full screen mode, where we can see the icons 

![image](https://github.com/user-attachments/assets/bb003367-2163-4113-a713-72bc85971553)

When the windows is maximized (taking the whole screen), the icons disappear and I can't even click there.

![image](https://github.com/user-attachments/assets/470fcc9e-1290-4145-aa75-33d9105d838d)

### Expected result

The icons should appear in maximized window.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave	1.70.123 Chromium: 129.0.6668.89 (Official Build) (64-bit) 
Revision	7c1bbf03546a64d969d010808e4f5c99fdf343bb
OS	Linux

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by jonathansampson** [comment]
By "fullscreen," you mean F11, or simply maximizing the browser window? Also, does this reproduce for you on any other profiles (or a Guest Window)?

**Comment by mlec1** [comment]
Yes, I can reproduce the issue in any profile, even guest. On the screenshot I used a private window as example, to disclose minimum info on the page.

Yes by "fullscreen", I mean "maximizing" the window (the middle button, between the close button and minimizing button). I will change the description and title

**Comment by jonathansampson** [comment]
@mlec1 Even though the buttons aren't visible, are they still present? That is, if you click around in that area, do you see the browser react (e.g., minimizing and/or closing)?

**Comment by mlec1** [comment]
No, the buttons are gone too. When I click, nothing is happening

**Comment by jonathansampson** [comment]
I missed that this was Linux; do you see the same issue with Chrome?

**Comment by mlec1** [comment]
I just installed chrome (Version 129.0.6668.89 (Official Build) (64-bit)) for checking that. And I don't have the issue

![image](https://github.com/user-attachments/assets/346b1183-ca7b-4f65-976c-75017e9c1e06)

In brave with horizontal tabs, I don't have the icons / buttons either. I don't know if it is expected.

![image](https://github.com/user-attachments/assets/ea79ccc4-71c8-4193-8c72-7c393408d560)

**Comment by mlec1** [comment]
OK something I noticed is that, I have the "use system title bar and border" to off in the settings.

![image](https://github.com/user-attachments/assets/f044fc1f-b57b-4523-934c-e28b4fe26cdd)

With it being off, in small window the icons are on the same level as the search bar

![image](https://github.com/user-attachments/assets/c2e93d03-a34f-470f-bf8b-b2bd0d4a1c7b)

When the setting is on, the icons are in a bar above and I don't have the issue anymore.

![image](https://github.com/user-attachments/assets/eb6e716c-6e9b-4710-bb6a-4bd3d3379847)

**Comment by jagadeshjai** [comment]
Adding a point here - I can't able to reproduce this in Ubuntu 24 in both Stable and Nightly


**Version 1.70.123 Chromium: 129.0.6668.89 (Official Build) (64-bit)**

and

**Version 1.72.55 Chromium: 129.0.6668.89 (Official Build) nightly (64-bit)**

**Comment by mlec1** [comment]
Then don't worry. I don't know how you manage the issues, but on my side, you could close the issue.

**Comment by mlec1** [comment]
It is fixed by itself in the Version 1.70.126 Chromium: 129.0.6668.100 (Official Build) (64-bit)

**Comment by Leza89** [comment]
I still can reproduce this issue on 
[Version 1.73.89 Chromium: 131.0.6778.69 (Official Build) (64-bit)](https://brave.com/latest/)

Maximized Window
![Image](https://github.com/user-attachments/assets/7504ded7-869e-4704-a94c-b39bc9d42048)

Regular Window
![Image](https://github.com/user-attachments/assets/3d891482-f0fd-4374-af5a-9ce52b0a1426)


ISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04.1 LTS"

**Comment by Leza89** [comment]
I want to add that this happens under X11. When switching to Ubuntu under Wayland, the symbols appear correctly.

**Comment by leojo** [comment]
@rebron This still seems to be happening in Oct 2025

Brave version: 1.82.170 Chromium: 140.0.7339.186 (Official Build) (64-bit)

**Comment by Leza89** [comment]
[Brave 1.82.172 (Official Build) (64-bit)](https://brave.com/latest/)
Chromium: 140.0.7339.207

Seems to be fixed now

loginctl show-session 2
Type=x11


<img width="386" height="131" alt="Image" src="https://github.com/user-attachments/assets/016f2650-25c4-44f6-bc65-b57cad1d2028" />

**Comment by Matheos96** [comment]
I too am still experiencing this issue in Oct 2025. I don't feel it is fixed in 172...

<img width="233" height="84" alt="Image" src="https://github.com/user-attachments/assets/d12a057f-0dd2-46ca-988d-855b4fa9cf92" />

 
Brave 1.83.109 (Official Build) (64-bit)
Chromium: 141.0.7390.55

6.16.10-arch1-1
KDE Plasma 6.4.5 (Wayland)
Nvidia

Honestly, I feel like it became an issue quite recently, did not notice it until yesterday. Updated brave first time in a while 4 days ago or so. Can we please re-open this?

**Comment by Leza89** [comment]
> I too am still experiencing this issue in Oct 2025. I don't feel it is fixed in 172...
> 
> <img alt="Image" width="233" height="84" src="https://private-user-images.githubusercontent.com/32064310/497453995-d12a057f-0dd2-46ca-988d-855b4fa9cf92.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTk4NTA2NDEsIm5iZiI6MTc1OTg1MDM0MSwicGF0aCI6Ii8zMjA2NDMxMC80OTc0NTM5OTUtZDEyYTA1N2YtMGRkMi00NmNhLTk4OGQtODU1YjRmYTljZjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDA3VDE1MTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNzcwNzMxZmFhNTc0MTUyYzk5N2U3ZjBiOWViMjRmYmRiOGZmMjNkMWNiNDVjY2RkMTM1M2Y2NzE2ZTAyMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fhD5FOHj8zfB63VGdtWk5cQufdsbiFSHmUqKpqDcpGI">
> Brave 1.83.109 (Official Build) (64-bit) Chromium: 141.0.7390.55
> 
> 6.16.10-arch1-1 KDE Plasma 6.4.5 (Wayland) Nvidia
> 
> Honestly, I feel like it became an issue quite recently, did not notice it until yesterday. Updated brave first time in a while 4 days ago or so. Can we please re-open this?

You are correct.. it is missing for me again. I do not know what I did for it to appear

Edit: You have the close button? I have nothing in that corner:

<img width="497" height="87" alt="Image" src="https://github.com/user-attachments/assets/1f1286dc-eb38-47c1-99f2-e04eaa159e50" />

**Comment by leojo** [comment]
Working for me once more on version 1.82.170 Chromium: 140.0.7339.186 (Official Build) (64-bit)

**Comment by Leza89** [comment]
> Working for me once more on version 1.82.170 Chromium: 140.0.7339.186 (Official Build) (64-bit)

Brave 1.82.172 (Official Build) (64-bit)
Chromium: 140.0.7339.207

Also working again for me

**Comment by Matheos96** [comment]
Still not working for me unfortunately, even on a newer version

[Brave 1.83.112 (Official Build) (64-bit)
Chromium: 141.0.7390.70

brave-bin from AUR

Still only close button

**Comment by Leza89** [comment]
### Reproduced

When Brave is not open and a link is clicked (for example from a messenger app) it will open Brave **without** the window controls

When Brave is opened directly (as in launching the program), so `/usr/bin/brave-browser-stable %U` where %U is empty, it will ask which profile to load and show the window controls

Edit:
I can not manually reproduce this behaviour. Clicking a link in wire calls

xdg-open, but trying to manually recreate the behaviour does not result in the window controls to be missing

/usr/bin/xdg-open "https://www.kleinanzeigen.de/"
/usr/bin/gio open "https://www.kleinanzeigen.de/"


here is the strace filtered for execve; Hope that helps

```
[pid 17923] execve(/home/user/.local/bin/xdg-open, [xdg-open, https://www.kleinanzeigen.de/s-a...], 0x3f74020ba000 /* 64 vars */) = -1 ENOENT (No such file or directory)
[pid 17923] execve(/usr/local/sbin/xdg-open, [xdg-open, https://www.kleinanzeigen.de/s-a...], 0x3f74020ba000 /* 64 vars */) = -1 ENOENT (No such file or directory)
[pid 17923] execve(/usr/local/bin/xdg-open, [xdg-open, https://www.kleinanzeigen.de/s-a...], 0x3f74020ba000 /* 64 vars */) = -1 ENOENT (No such file or directory)
[pid 17923] execve(/usr/sbin/xdg-open, [xdg-open, https://www.kleinanzeigen.de/s-a...], 0x3f74020ba000 /* 64 vars */) = -1 ENOENT (No such file or directory)
[pid 17923] execve(/usr/bin/xdg-open, [xdg-open, https://www.kleinanzeigen.de/s-a...], 0x3f74020ba000 /* 64 vars */) = 0
[pid 17925] execve(/usr/bin/which, [which, gnome-default-applications-prope...], 0x58ec1c70e368 /* 64 vars */) = 0
[pid 17926] execve(/usr/bin/gio, [gio, help, open], 0x58ec1c70e7c8 /* 64 vars */) = 0
[pid 17927] execve(/usr/bin/gio, [gio, open, https://www.kleinanzeigen.de/s-a...], 0x58ec1c70ed08 /* 64 vars */) = 0
[pid 17933] execve(/usr/lib/x86_64-linux-gnu/glib-2.0/gio-launch-desktop, [/usr/lib/x86_64-linux-gnu/glib-2..., /usr/bin/brave-browser-stable, https://www.kleinanzeigen.de/s-a...], 0x5e48f7ecabc0 /* 64 vars */ <unfinished ...>
[pid 17933] <... execve resumed>)       = 0
[pid 17933] execve(/usr/bin/brave-browser-stable, [/usr/bin/brave-browser-stable, https://www.kleinanzeigen.de/s-a...], 0x7ffee5f192c8 /* 64 vars */ <unfinished ...>
[pid 17933] <... execve resumed>)       = 0
[pid 17938] execve(/usr/bin/readlink, [readlink, -f, /usr/bin/brave-browser-stable], 0x6466dc2d7360 /* 65 vars */) = 0
[pid 17939] execve(/usr/bin/dirname, [dirname, /opt/brave.com/brave/brave-brows...], 0x6466dc2db5a0 /* 66 vars */) = 0
[pid 17940] execve(/usr/bin/mkdir, [mkdir, -p, /home/user/.local/share/applica...], 0x6466dc2db5a0 /* 66 vars */) = 0
[pid 17941] execve(/usr/bin/cat, [cat], 0x6466dc2df4a0 /* 67 vars */) = 0
[pid 17943] execve(/opt/brave.com/brave/brave, [/opt/brave.com/brave/brave, https://www.kleinanzeigen.de/s-a...], 0x6466dc2df7f0 /* 68 vars */ <unfinished ...>
[pid 17942] execve(/usr/bin/cat, [cat], 0x6466dc2df800 /* 67 vars */ <unfinished ...>
[pid 17943] <... execve resumed>)       = 0
[pid 17942] <... execve resumed>)       = 0
[pid 17945] execve(/opt/brave.com/brave/chrome_crashpad_handler, [/opt/brave.com/brave/chrome_cras..., --monitor-self, --monitor-self-annotation=ptype=..., --database=/home/user/.config/B..., --metrics-dir=/home/user/.confi..., --url=https://cr.brave.com, --annotation=lsb-release=Ubuntu ..., --annotation=plat=Linux, --annotation=prod=Chrome_Linux, --annotation=ver=141.1.83.120, --initial-client-fd=5, --shared-client-connection], 0x7ffc9e351450 /* 68 vars */) = 0
[pid 17947] execve(/opt/brave.com/brave/chrome_crashpad_handler, [/opt/brave.com/brave/chrome_cras..., --no-periodic-tasks, --monitor-self-annotation=ptype=..., --database=/home/user/.config/B..., --url=https://cr.brave.com, --annotation=lsb-release=Ubuntu ..., --annotation=plat=Linux, --annotation=prod=Chrome_Linux, --annotation=ver=141.1.83.120, --initial-client-fd=4, --shared-client-connection], 0x7fff254282e0 /* 68 vars */) = 0
[pid 17953] execve(/opt/brave.com/brave/brave, [/opt/brave.com/brave/brave, --type=zygote, --no-zygote-sandbox, --crashpad-handler-pid=17945, --enable-crash-reporter=cd4b3ffc..., --change-stack-guard-on-fork=ena...], 0x7ffc9e351450 /* 68 vars */) = 0
[pid 17954] execve(/opt/brave.com/brave/brave, [/opt/brave.com/brave/brave, --type=zygote, --crashpad-handler-pid=17945, --enable-crash-reporter=cd4b3ffc..., --change-stack-guard-on-fork=ena...], 0xe8000d9800 /* 71 vars */) = 0
```
