### ISSUE TITLE
[hackerone][iOS] Fix Reader Mode

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-browser#41444]
See https://hackerone.com/reports/2760854

**Comment by kjozwiak** [comment]
The above requires `1.71.117` or higher for `1.71.x` verification. Going to leave this as a single check rather than `QA/Test-All-Platforms` as we'll run through the `reader mode` when we're running through the manual passes for `1.71.x`.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18` using version `1.71.118`

* Ensured that reader mode icon is shown in the URL bar for articles.
* Ensured reader mode works with `Top Bar` and `Bottom Bar` configurations and as well as with light/dark modes.
* Ensured enabling reader mode works on different different articles and there are no issues toggling reader mode.
* Ensured that reader mode settings are retained when reader mode when switching from different webpages.
* Ensured that reader mode will continue to be used after restarting brave.

`example` | `example` | `example` | `example`
---|---|---|---
![Image](https://github.com/user-attachments/assets/39c2a3ab-d18a-46a6-a0d8-3497911f722a) | ![Image](https://github.com/user-attachments/assets/85826b31-da70-464a-b272-ead9998085b4) | ![Image](https://github.com/user-attachments/assets/1260cefb-7429-4977-8e05-aa1a73bc82ad) | ![Image](https://github.com/user-attachments/assets/b9fc4258-f6ca-4d67-9e5b-5078cfce67be)
