### ISSUE TITLE
Remove Divider Line in Wallet Headers

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#41458]
### Platforms

all, Windows, macOS, Linux

### Description

We need to remove the `Divider` line in the `Wallet Page` headers to match the new `Figma` designs.

![Image](https://github.com/user-attachments/assets/e8217be0-4420-49b3-bf6d-4d66546ca176)
![Image](https://github.com/user-attachments/assets/f6f199a0-a027-4a6e-8a41-81e459f267a0)
![Image](https://github.com/user-attachments/assets/a5aa953c-3e8f-423e-978f-1e2f8509d65c)
![Image](https://github.com/user-attachments/assets/50665550-a0b5-44a4-a098-902131422e2a)
![Image](https://github.com/user-attachments/assets/528b7b4e-9856-4543-8ae8-75d8aa6c2e3e)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.5 Chromium: 131.0.6778.69 (Official Build) beta (64-bit)
-- | --
Revision | fbd7c390a7daa54f1aac2c769076d3fecf7c7fc7
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from [brave/brave-core#25888](https://github.com/brave/brave-core/pull/25888)
- Verified divider line is removed from Wallet headers

Portfolio | Activity | Accounts | Explore
-- | -- | -- | --
![Image](https://github.com/user-attachments/assets/72a68433-592d-4c16-bac2-7b194cbec18d) | ![Image](https://github.com/user-attachments/assets/df6da629-2d71-4f72-a228-7f7201d8261f) | ![Image](https://github.com/user-attachments/assets/700e178c-9386-40f7-a585-7ccb49829924) | ![Image](https://github.com/user-attachments/assets/0a4fc4a1-90d1-47c0-a6f4-6e09cbfab1eb)
