### ISSUE TITLE
[Android] Update search engine default for Australia (AU)

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#41456]
### Description
Update search engine default for Australia:

Australia (AU)
Brave should be at the top of the drop down list at settings -> search engines -> standard tab and private tab

Related: https://github.com/brave/brave-browser/issues/41451

### Steps to reproduce
Region set to AU

1. Fresh profile
2. Default search engine SHOULD be Brave
3. Visit settings -> search engines -> standard tab and private tab
4. Brave SHOULD be first in the Default search engines list

Region set to anything else (excluding CA / DE / FR / GB / US / AT / ES / MX / BR / AR / IN, IT)

1. Fresh profile
2. Default will NOT be Brave Search
3. Visit settings -> search engines -> standard tab and private tab
4. Brave SHOULD be first in the Default search engines list - unless you're in a region where Yandex is default (AM, AZ, BY, KG, KZ, MD, RU, TJ, TM, UZ). In that case it will be second.

Notes for test plan
https://github.com/brave/brave-browser/issues/23814#issuecomment-1195841652

### Actual result
see description

### Expected result
see description

cc @rebron

**Comment by kjozwiak** [comment]
The above requires `1.71.116` or higher for `1.71.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 15` using the following build(s):

```
Brave | 1.71.118 Chromium: 130.0.6723.70 (Official Build) (64-bit)
--- | ---
Revision | d29310b051bde8ba041cd7b4edcb41ce951be12c
OS | Android 15; Build/AP41.240823.009; 35; REL
```

### `Australia (AU) locale` - `PASSED`

<details>
<summary>Clean Profile</summary>

* ensured that `Brave` was selected as the default for both Normal/Private windows via `Settings` -> `Search engines`
* ensured that `Brave` was the first engine via the drop down list under `Settings` -> `Search engines` for `Standard` Tab
* ensured that `Brave` was the first engine via the drop down list under `Settings` -> `Search engines` for `Private` Tab

**`Example`** | **`Example`** | **`Example`** 
---------------|-----------------|---------------
![Image](https://github.com/user-attachments/assets/695a35e6-c635-4219-a1b1-6cd06817fae8) | ![Image](https://github.com/user-attachments/assets/9ab3f8b8-af04-4fae-a830-3cd93c2a001b) | ![Image](https://github.com/user-attachments/assets/6c019be1-4cd2-4676-98b8-d60df24134ee)

</details>

<details>
<summary>Updated Profile (Google/Google)</summary>

* installed `1.70.126 Chromium 129.0.6668.100`
* ensured that `Google` was the default SE selected under `Settings` -> `Search engines` for `Standard` Tab
* ensured that `Google` was the default SE selected under `Settings` -> `Search engines` for `Private` Tab
* updated to `1.71.118 Chromium: 130.0.6723.70` and ensured that `Google` is still the default for `Standard` & `Private` Tab
* ensured that `Brave` was the first engine via the drop down list under `Settings` -> `Search engines` for `Standard` Tab
* ensured that `Brave` was the first engine via the drop down list under `Settings` -> `Search engines` for `Private` Tab

**`1.70.126 Chromium 129.0.6668.100`** | **`1.71.118 Chromium: 130.0.6723.70`**
--------------------------------------------|----------------------------------------------
![Image](https://github.com/user-attachments/assets/7b61acf6-4cb9-44dc-a2d2-62680f7b3340) | ![Image](https://github.com/user-attachments/assets/926b64ab-49d7-427e-857a-4020caccefb3)
![Image](https://github.com/user-attachments/assets/60c7a31a-8afd-47f2-b6de-b49c64e102c7) | ![Image](https://github.com/user-attachments/assets/805d9e10-a987-43bc-8429-49d8600a0059)
![Image](https://github.com/user-attachments/assets/dab61a24-8927-47f2-b546-063f4f75f5c4) | ![Image](https://github.com/user-attachments/assets/a7c20c0f-3208-4f10-8a18-9f462b35a448)
</details>

<details>
<summary>Updated Profile (Bing/Startpage)</summary>

* installed `1.70.126 Chromium 129.0.6668.100`
* changed the default SE to `Bing` under `Settings` -> `Search engines` for `Standard` Tab
* changed the default SE to `Startpage` under `Settings` -> `Search engines` for `Private` Tab
* updated to `1.71.118 Chromium: 130.0.6723.70`
* ensured that `Bing` wasn't replaced with `Brave` as the default SE for `Standard` Tab
* ensured that `Startpage` wasn't replaced with `Brave` as the default SE for `Private` Tab
* ensured that `Brave` was the first engine via the drop down list under `Settings` -> `Search engines` for `Standard` Tab
* ensured that `Brave` was the first engine via the drop down list under `Settings` -> `Search engines` for `Private` Tab

**`1.70.126 Chromium 129.0.6668.100`** | **`1.71.118 Chromium: 130.0.6723.70`**
--------------------------------------------|----------------------------------------------
![Image](https://github.com/user-attachments/assets/907fdf57-23a4-4e57-845e-b59474c424b8) | ![Image](https://github.com/user-attachments/assets/b7bd043f-8712-4255-bb8b-8a7b7b78f874)
![Image](https://github.com/user-attachments/assets/01661f11-bd0e-41de-b417-92894ed97406) | ![Image](https://github.com/user-attachments/assets/764f17e4-e64a-4177-8dbf-b52c1dda6aff)
![Image](https://github.com/user-attachments/assets/a0b0ccb2-247a-436c-911a-f49a2aa3144a) | ![Image](https://github.com/user-attachments/assets/1d5a0625-b437-4bff-9f2f-dc7547520b47)

</details>

-------------

### `MX (Mexico) locale` - `PASSED`

<details>
<summary>Clean Profile</summary>

* ensured that `Brave` was selected as the default for both Normal/Private windows via `Settings` -> `Search engines`
* ensured that `Brave` was the first engine via the drop down list under `Settings` -> `Search engines` for `Standard` Tab
* ensured that `Brave` was the first engine via the drop down list under `Settings` -> `Search engines` for `Private` Tab

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|---------------
![Image](https://github.com/user-attachments/assets/a766794d-3b31-4157-9189-6a0b9ca9c0dd) | ![Image](https://github.com/user-attachments/assets/5217ac37-81a1-4763-9bb6-6ee18d162a84) | ![Image](https://github.com/user-attachments/assets/55daa689-1bf8-4c1c-a18a-e8495f7ca3a6)

</details>

<details>
<summary>Updated Profile (Brave/Brave)</summary>

* installed `1.70.126 Chromium 129.0.6668.100`
* ensured that `Brave` was the default SE selected under `Settings` -> `Search engines` for `Standard` Tab
* ensured that `Brave` was the default SE selected under `Settings` -> `Search engines` for `Private` Tab
* updated to `1.71.118 Chromium: 130.0.6723.70`
* ensured that `Brave` is still the default SE for both `Standard` Tab & `Private` Tab
* ensured that `Brave` was the first engine via the drop down list under `Settings` -> `Search engines` for `Standard` Tab
* ensured that `Brave` was the first engine via the drop down list under `Settings` -> `Search engines` for `Private` Tab

**`1.72.73 Chromium: 130.0.6723.31`** | **`1.73.26 Chromium: 130.0.6723.58`**
--------------------------------------------|----------------------------------------------
![Image](https://github.com/user-attachments/assets/197c795a-aea4-4dc9-8532-64fa5bc6d5ce) | ![Image](https://github.com/user-attachments/assets/b28b6c21-cffb-406d-af9d-441d338e42ae)
![Image](https://github.com/user-attachments/assets/c6d23ce0-81da-4904-9c4e-579fcf4ae82b) | ![Image](https://github.com/user-attachments/assets/37309429-4436-4ab7-8834-5ca34398ff4d)
![Image](https://github.com/user-attachments/assets/ed483acf-4a2e-4538-aa9a-fb6534259557) | ![Image](https://github.com/user-attachments/assets/5c23fa82-3944-4f9e-8746-cb04ae3a3f9c)
</details>

<details>
<summary>Updated Profile (Qwant/Bing)</summary>

* installed `1.70.126 Chromium 129.0.6668.100`
* changed the default SE to `Qwant` under `Settings` -> `Search engines` for `Standard` Tab
* changed the default SE to `Bing` under `Settings` -> `Search engines` for `Private` Tab
* updated to `1.71.118 Chromium: 130.0.6723.70`
* ensured that `Qwant` wasn't replaced with `Brave` as the default SE for `Standard` Tab
* ensured that `Bing` wasn't replaced with `Brave` as the default SE for `Private` Tab
* ensured that `Brave` was the first engine via the drop down list under `Settings` -> `Search engines` for `Standard` Tab
* ensured that `Brave` was the first engine via the drop down list under `Settings` -> `Search engines` for `Private` Tab

**`1.72.73 Chromium: 130.0.6723.31`** | **`1.73.26 Chromium: 130.0.6723.58`**
--------------------------------------------|----------------------------------------------
![Image](https://github.com/user-attachments/assets/ce3a715b-ddbc-4263-b480-79d90d58189e) | ![Image](https://github.com/user-attachments/assets/fbd8bad1-a0d0-499d-8d5a-a721b0755860)
![Image](https://github.com/user-attachments/assets/ebae63d8-902f-4a9e-8042-edb878a3ed16) | ![Image](https://github.com/user-attachments/assets/25ca4203-d279-4170-b680-90dbb176448d)
![Image](https://github.com/user-attachments/assets/ceb921d3-d9bb-4314-bf79-824a461cd4b8) | ![Image](https://github.com/user-attachments/assets/12538b66-6ba0-497f-bf0e-82e7743a1791)
</details>

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Galaxy Tab S8` using version(s):
```
Device/OS: Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
Brave build: 1.71.118
Chromium: 130.0.6723.70 (Official Build) (64-bit) 
```
---------------------------

`Region set to AU`

<details>
<summary> Clean Profile </summary>

**STEPS:**
1. Switch device Language/Region to `English`/`Australia`
2. Fresh install Brave `1.71.118`
3. *Verify*

**ACTUAL RESULTS:**
- Verified that `Brave` was selected as the `default` for both `Normal` and `Private` tabs via `Settings` -> `Search engines`
- Verified that `Brave` was the `first` engine via the drop-down list under `Settings` -> `Search engines` for `Standard Tab`
- Verified that `Brave` was the `first` engine via the drop-down list under `Settings` -> `Search engines` for `Private Tab`

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/342ca5d2-3fe4-46bd-8ec3-071edfa71939) | ![2](https://github.com/user-attachments/assets/06eea061-548d-4652-afda-28fe8c65db2d) | ![3](https://github.com/user-attachments/assets/04c90966-aa42-4833-800b-ec0ec7b8e4f8) | ![4](https://github.com/user-attachments/assets/4b9347a2-2eb9-47a9-9d19-a8ae27d3c09c) |
</details>

<details>
<summary> Updated Profile (Google/Google) </summary>

1. Switch device Language/Region to `English`/`Australia`
2. Fresh install Brave `1.70.123`
3. Launch Brave > *Verify that `Google` is the default SE*
4. Upgrade Brave to `1.71.118` > Launch Brave
5. *Verify that `Google` is still the default SE after the upgrade*


**ACTUAL RESULTS:**
- Verified that `Google` was the default SE selected under `Settings` -> `Search engines` for `Standard` Tab
- Verified that `Google` was the default SE selected under `Settings` -> `Search engines` for `Private` Tab
- Verified that `Google` is still the default SE for the `Standard` & `Private` Tab after Brave upgrade
- Verified that `Brave` was the first SE via the drop-down list under `Settings` -> `Search engines` for the `Standard` Tab after Brave upgrade
- Verified that `Brave` was the first SE via the drop-down list under `Settings` -> `Search engines` for the `Private` Tab after Brave upgrade

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/a29b3eaf-e15c-4e25-8853-d59a02a027bd) | ![2](https://github.com/user-attachments/assets/3fbc6d70-5b6c-4cdf-aa86-5b57d2fc6f70) | ![3](https://github.com/user-attachments/assets/739483a6-3ba0-44bb-a8a7-4c08db4ff3fd) | ![4](https://github.com/user-attachments/assets/ae779867-4054-4ef8-afa1-0190d01c0709) |
| ![1](https://github.com/user-attachments/assets/c7b616f1-75e3-4cc0-8966-4ed7f9a03171) | ![2](https://github.com/user-attachments/assets/93f4c7ed-189d-405b-be32-955c5a313abf) | ![3](https://github.com/user-attachments/assets/a2fc64d6-f0a3-41c4-8461-cd67b2a66f47) | ![4](https://github.com/user-attachments/assets/44557b2c-bccc-4a50-a07e-2231ec601fa3) |
</details>

<details>
<summary> Updated Profile (Qwant/Ecosia) </summary>

**STEPS:**
1. Switch device Language/Region to `English`/`Australia`
2. Fresh install Brave `1.70.123` > Launch Brave
3. Change the default SE to `Qwant` under `Settings` -> `Search engines` for `Standard Tab`
4. Change the default SE to `Ecosia` under `Settings` -> `Search engines` for `Private Tab`
5. Upgrade Brave to `1.71.118` > Launch Brave > *Verify*

**ACTUAL RESULTS:**
- Verified that `Qwant` wasn't replaced with `Brave` as the default SE for `Standard Tab` after Brave upgrade
- Verified that `Ecosia` wasn't replaced with `Brave` as the default SE for `Private Tab` after Brave upgrade
- Verified that `Brave` was the first SE via the drop-down list under `Settings` -> `Search engines` for the `Standard` Tab after Brave upgrade
- Verified that `Brave` was the first SE via the drop-down list under `Settings` -> `Search engines` for the `Private` Tab after Brave upgrade

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/039afcc8-ea42-4205-b8f7-f5c00025908a) | ![2](https://github.com/user-attachments/assets/d2084a7b-c4cf-4920-b2c9-ba6f3f84d6b9) | ![3](https://github.com/user-attachments/assets/d3136a61-e40b-4b0e-9bc7-aef1d24757cb) |
| ![1](https://github.com/user-attachments/assets/e81da006-b520-47ca-a5f5-4d9554fa5a4b) | ![2](https://github.com/user-attachments/assets/d3233d8e-b37d-4365-8761-a9b00cd97c84) | ![3](https://github.com/user-attachments/assets/c9e9be93-d32b-4841-8d0e-a463d9bcf49f) |
</details>
