### ISSUE TITLE
Improve tab hover state contrast for vertical tabs

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#41450]
### Description

When using vertical tabs the hover state for an inactive tab should be more like it is for horizontal tabs. 

### Steps to reproduce

1. Be using vertical tabs
2. Hover over an inactive tab
3. Not much visual change on the hovered tab

### Actual result

Light theme | Dark Theme
--- | ---
<img width="474" alt="lt vt" src="https://github.com/user-attachments/assets/6d4c4f59-d54e-4ec1-acb5-1e1eae099689"> | ![dk vt](https://github.com/user-attachments/assets/6cdb5551-86db-424c-b418-8ef0c636c4fc)

### Expected result

Hover state should be more like horizontal tabs:

Light theme | Dark Theme
--- | ---
<img width="1266" alt="lt horiz" src="https://github.com/user-attachments/assets/ebdd6c44-8605-45fe-99c4-78c816c1b452"> | <img width="1261" alt="dk horiz" src="https://github.com/user-attachments/assets/840954a7-aff8-44b9-9b85-8e231a71d056">

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.123 (current release)

1.71.105 (beta)

1.72.61 (nightly)

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron

**Comment by aguscruiz** [comment]
This is the goal, but let's see what we can do with our primitives
https://www.figma.com/design/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?node-id=3014-33123&t=QnlFxJNrjqBCfedx-1

**Comment by fallaciousreasoning** [comment]
@aguscruiz I'm experimenting with 5% towards max contrast from the background color. Interested to hear your thoughts

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.91 Chromium: 130.0.6723.91 (Official Build) beta (64-bit)
-- | --
Revision | 14b8282de957b76db51dd53a3da23b482c1c19b7
OS | Windows 11 Version 23H2 (Build 22631.4391)
```

Verified the issue using the STR from https://github.com/brave/brave-browser/issues/41450#issue-2571047798

#### Confirmed the hover effect is shown on the inactive tab

**_Vertical tabs_**

dark | light | custom theme | private window | private window with TOR | custom black (Just Black)
----- | ------ | ------- | ----- | ----- | -------
![Image](https://github.com/user-attachments/assets/d8ef77be-d123-4526-bcbb-d7038c969e57)|![Image](https://github.com/user-attachments/assets/a775f3ff-7134-4b5c-bbb2-e985679e8a14)|![Image](https://github.com/user-attachments/assets/567e436c-0053-457c-bac0-758ab889d2fd)|![Image](https://github.com/user-attachments/assets/9ff14f5d-c90e-4839-aaaf-815549c14527)|![Image](https://github.com/user-attachments/assets/eb2b581c-259c-4044-aa19-48d8228aac16)|![Image](https://github.com/user-attachments/assets/1f7ff8ba-018a-4881-894e-95c79f3d8e86)

**_Horizontal tabs_**

dark | light | custom theme | private window | private window with TOR | custom black (Just Black)
----- | ------ | ---- | ----- | ------ | ---------
![Image](https://github.com/user-attachments/assets/6699cdbb-8f57-4f65-bcaa-764171bbca44)|![Image](https://github.com/user-attachments/assets/d37dbf5f-10a6-4a04-bbe8-ff598bcbb51d)|![Image](https://github.com/user-attachments/assets/0318c748-d07f-4392-8e3e-0ddab8e20ec9)|![Image](https://github.com/user-attachments/assets/59bac418-8584-45cf-bb15-fdd1787ba72a)|![Image](https://github.com/user-attachments/assets/e58b1435-c3d1-4ed6-99d8-265a6d5a98ea)|![Image](https://github.com/user-attachments/assets/aac91282-c051-43b9-badd-95e5bb01c454)
