### ISSUE TITLE
Update search engine default for Australia (AU)

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#41451]
### Description

Update search engine default for Australia:

Australia (AU)
Brave should be at the top of the drop down list at brave://settings/search

Related: https://github.com/brave/brave-browser/issues/18331, https://github.com/brave/brave-browser/issues/23814 https://github.com/brave/brave-browser/issues/26181, https://github.com/brave/brave-browser/issues/27709, and https://github.com/brave/brave-browser/issues/38028

### Steps to reproduce

Region set to AU

1. Fresh profile
2. Default search engine SHOULD be Brave
3. Visit brave://settings/searchEngines
4. Brave SHOULD be first in the Default search engines list

Region set to anything else (excluding CA / DE / FR / GB / US / AT / ES / MX / BR / AR / IN, IT)

1. Fresh profile
2. Default will NOT be Brave Search
3. Visit brave://settings/searchEngines
4. Brave SHOULD be first in the Default search engines list - unless you're in a region where Yandex is default (AM, AZ, BY, KG, KZ, MD, RU, TJ, TM, UZ). In that case it will be second.

Notes for test plan
https://github.com/brave/brave-browser/issues/23814#issuecomment-1195841652

### Actual result

see description

### Expected result

see description

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.71.x 

### Channel information

- [X] release (stable)
- [X] beta
- [X] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.71.116` or higher for `1.71.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `In Progress` using

```
Brave | 1.71.116 Chromium: 130.0.6723.58 (Official Build) (64-bit)
-- | --
Revision | 789393dd90da88a1f9abf5a7d05fd8ccff76afa2
OS | Windows 11 Version 23H2 (Build 22631.4317)
```

Update search engine default for Australia:

Pre-requisite: Set Region to AU in Window settings

1. Installed 1.71.116
2. launched Brave
3. relaunched Brave
4. set Brave as a default in the onboarding
5. clicked `Sure, I'll help` button
6. clicked `Finish` button
7. opened `brave://settings/search`
8. confirmed Brave is shown next to Change button for Normal Window as a default Search engine
9. clicked `Change` button
10. confirmed `Brave` was selected and shown on top of the Search engine list for Normal windows
11. confirmed `Brave` was the first engine via drop down list under brave://settings/search for Private windows
12. confirmed that Brave was selected as the default via brave://settings/searchEngines
13. opened a new tab and searched for a query "sydney opera house"
14. confirmed search results rendered as expected

step 0 | step 5 | step 8 | step 10 | step 11 | step 12 | step 14 
----- | ------ | ------- | ------- | -------- | ------- | --------
![Image](https://github.com/user-attachments/assets/f2848829-c97b-43b8-afae-d40ed1dc9ddd)|![Image](https://github.com/user-attachments/assets/3c24f35e-fee0-4ec8-b58c-0131f34124da)|![Image](https://github.com/user-attachments/assets/141a8ab3-110f-4a3e-bf8a-fb7706f56dad)|![Image](https://github.com/user-attachments/assets/87f8d9f2-c14c-45a0-ad50-e077efbaca36)|![Image](https://github.com/user-attachments/assets/3f12ca97-e7b8-4625-ac29-ea32b9a7f68b)|![Image](https://github.com/user-attachments/assets/7a0aaee5-f8af-43b6-b0bd-c14e30e3561b)|![Image](https://github.com/user-attachments/assets/46f9f15f-8e0d-4b2f-9755-0a71e234df56)

<details>
<summary>Upgrade (Google/Brave) - PASSED</summary>

1. installed `1.71.114 Chromium: 130.0.6723.58`
2. opened `brave://settings/search`
3. confirmed Brave is shown next to Change button for Normal Window as a default Search engine
4. clicked `Change` button
5. confirmed `Brave` was selected and shown on top of the Search engine list for Normal windows
6. confirmed that `Brave` was the default SE selected under `brave://settings/search` for `Private` windows
7. updated to `1.71.116 Chromium: 130.0.6723.58`
8. confirmed that `Google` is still the default SE for `Normal` windows in brave://settings/search
9. confirmed `Brave` was selected and shown on top of the Search engine list for Normal windows when clicked `Change` button
10. confirmed `Brave` is still the default SE for `Private` windows
11. confirmed that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows

step 1 | step 3 | step 5 | step 6 | step 7 | step 8 | step 9 | step 10 | step 11
-------- | -------- | ------- | ---------- | --------- | ------- | ---------  | ------ | ------
![Image](https://github.com/user-attachments/assets/d69d5f70-40d3-4943-aebc-6ce056847035)|![Image](https://github.com/user-attachments/assets/ea4b7e00-ba15-4631-92c0-273885abd9d7)|![Image](https://github.com/user-attachments/assets/e0e3a51c-3de3-43d4-9fcd-7d31cba88a3d)|![Image](https://github.com/user-attachments/assets/7404f41a-fba5-41bb-9372-5f9fd2b6b12e)|![Image](https://github.com/user-attachments/assets/f2ffe0a6-9e27-4c43-a53d-7a3bdf3f503a)|![Image](https://github.com/user-attachments/assets/a6c212c3-44cc-4091-9329-9b7e11a549a6)|![Image](https://github.com/user-attachments/assets/bf93b036-02a9-4a3f-8a58-6bb6695c1215)|![Image](https://github.com/user-attachments/assets/94c6caa0-4d9a-45a0-9349-9b536ccc15f9)|![Image](https://github.com/user-attachments/assets/93741596-777b-412c-b48e-3f2d7e591cfb)

</details>

<details>
<summary>Upgrade (Bing/Google) - PASSED</summary>

1. installed `1.71.114 Chromium: 130.0.6723.58`
2. verified `Google` as a default in brave://settings/search for `Normal` window
3. changed the default SE to `Bing` under `brave://settings/search` for `Normal` windows
4. verified `Bing` is shown next `Change` button as a default for `Normal` windows
5. changed the default SE to `Google` under `brave://settings/search` for `Private` windows
6. updated to `1.71.116 Chromium: 130.0.6723.58`
7. confirmed that `Bling` wasn't replaced with `Brave` as the default SE for `Normal` windows
8. confirmed that `Google` wasn't replaced with `Brave` as the default SE for `Private` windows
9. confirmed `Brave` was selected and shown on top of the Search engine list for Normal windows when clicked `Change` button
10.  confirmed that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows

step 1 | step 2 | step 3 | step 4 | step 5 | step 6 | step 7-8 | step 9 | step 10
-------- | -------- | ------- | ---------- | --------- | ------- | ---------  | ------ | -------
![Image](https://github.com/user-attachments/assets/3b34dc48-7869-4389-891e-aacd906b9260)|![Image](https://github.com/user-attachments/assets/fb51d40d-32ed-493a-a844-ad37b6e62f72)|![Image](https://github.com/user-attachments/assets/acba948b-d487-455c-98b9-234353e3b37b)|![Image](https://github.com/user-attachments/assets/452b242e-999c-4172-8059-e6f38a26f52f)|![Image](https://github.com/user-attachments/assets/2215bc66-6586-4c75-bbd9-9ea7f4febb5d)|![Image](https://github.com/user-attachments/assets/bca14423-5ba1-4dee-a998-c663ba489545)|![Image](https://github.com/user-attachments/assets/8358519c-3400-43ea-9b8f-2d2b60e25b5b)|![Image](https://github.com/user-attachments/assets/5090b721-fd14-4599-8163-695f67a3ee57)|![Image](https://github.com/user-attachments/assets/b7b3be0c-6212-4f90-b173-1c16d314c015)

</details>

---------
### Portugal (PT) locale - Existing Brave Search default region

<details>
<summary>Clean Profile - PASSED</summary>

* ensured that `Brave` was selected as the default for both Normal/Private windows via `brave://settings/search`
* ensured that `Brave` was the first engine via the "Change" modal under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows
* ensured that `Brave` was selected as the default via `brave://settings/searchEngines`

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|---------------|---------------|---------------


</details>

<details>
<summary>Updated Profile (Brave/Brave) - PASSED</summary>

* installed `1.71.114 Chromium: 130.0.6723.58`
* ensured that `Brave` was the default SE selected under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the default SE selected under `brave://settings/search` for `Private` windows
* updated to `1.72.82 Chromium: 130.0.6723.58` 
* ensured that `Brave` is still the default SE for both `Normal` & `Private` windows
* ensured that `Brave` was the first engine via the "Change" modal under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows

**`1.71.114 Chromium: 130.0.6723.58`** | **`1.72.82 Chromium: 130.0.6723.58`**
--------------------------------------------|----------------------------------------------


</details>

<details>
<summary>Updated Profile (Qwant/DDG) - PASSED</summary>

* installed `1.71.114 Chromium: 130.0.6723.58`
* changed the default SE to `Qwant` under `brave://settings/search` for `Normal` windows
* changed the default SE to `DDG` under `brave://settings/search` for `Private` windows
* updated to `1.72.82 Chromium: 130.0.6723.58`
* ensured that `Qwant` wasn't replaced with `Brave` as the default SE for `Normal` windows
* ensured that `DDG` wasn't replaced with `Brave` as the default SE for `Private` windows
* ensured that `Brave` was the first engine via the "Change" modal under `brave://settings/search for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows

**`1.71.114 Chromium: 130.0.6723.58`** | **`1.72.82 Chromium: 130.0.6723.58`**
--------------------------------------------|-----------------------------------------------


</details>

---------

### Japan (JP) locale - Existing Brave Search default region

<details>
<summary>Clean Profile - PASSED</summary>

* ensured that `Brave` was selected as the default for both Normal/Private windows via `brave://settings/search`
* ensured that `Brave` was the first engine via the "Change" modal under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows
* ensured that `Brave` was selected as the default via `brave://settings/searchEngines`

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|---------------|---------------|---------------


</details>

<details>
<summary>Updated Profile (Brave/Brave) - PASSED</summary>

* installed `1.71.114 Chromium: 130.0.6723.58`
* ensured that `Brave` was the default SE selected under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the default SE selected under `brave://settings/search` for `Private` windows
* updated to `1.72.82 Chromium: 130.0.6723.58` 
* ensured that `Brave` is still the default SE for both `Normal` & `Private` windows
* ensured that `Brave` was the first engine via the "Change" modal under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows

**`1.71.114 Chromium: 130.0.6723.58`** | **`1.72.82 Chromium: 130.0.6723.58`**
--------------------------------------------|----------------------------------------------


</details>

<details>
<summary>Updated Profile (Ecosia/Bing) - PASSED</summary>

* installed `1.71.114 Chromium: 130.0.6723.58`
* changed the default SE to `Ecosia` under `brave://settings/search` for `Normal` windows
* changed the default SE to `Bing` under `brave://settings/search` for `Private` windows
* updated to `1.72.82 Chromium: 130.0.6723.58`
* ensured that `Ecosia` wasn't replaced with `Brave` as the default SE for `Normal` windows
* ensured that `Bing` wasn't replaced with `Brave` as the default SE for `Private` windows
* ensured that `Brave` was the first engine via the "Change" modal under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows

**`1.71.114 Chromium: 130.0.6723.58`** | **`1.72.82 Chromium: 130.0.6723.58`**
--------------------------------------------|-----------------------------------------------


</details>

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.71.116 Chromium: 130.0.6723.58 (Official Build) (x86_64)
-- | --
Revision | 789393dd90da88a1f9abf5a7d05fd8ccff76afa2
OS | macOS Version 14.7 (Build 23H124)
```

**Comment by btlechowski** [comment]
Verified with

Brave | 1.71.116 Chromium: 130.0.6723.58 (Official Build) (64-bit)
-- | --
Revision | 789393dd90da88a1f9abf5a7d05fd8ccff76afa2
OS | Linux


### Australia (AU) locale - New Brave Search default region

<details>
<summary>Clean Profile - PASSED</summary>

* ensured that `Brave` was selected as the default for both Normal/Private windows via `brave://settings/search`
* ensured that `Brave` was the first engine via the "Change" modal under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows
* ensured that `Brave` was selected as the default via `brave://settings/searchEngines`

![Image](https://github.com/user-attachments/assets/ead5cde0-1c2a-4914-9cd5-9c69c52dc575)|![Image](https://github.com/user-attachments/assets/8b299336-3462-4588-a862-2e10b74ac328)|![Image](https://github.com/user-attachments/assets/100dc414-f911-4ffd-863b-5fd6a85d52d8)
--|--|--

</details>

<details>
<summary>Updated Profile (Google/Brave) - PASSED</summary>

* installed `1.71.114 Chromium: 130.0.6723.58`
* ensured that `Google` was the default SE selected under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the default SE selected under `brave://settings/search` for `Private` windows
* updated to `1.71.116 Chromium: 130.0.6723.58` and ensured that `Google` is still the default SE for `Normal` windows
* ensured that `Brave` is still the default SE for `Private` windows
* ensured that `Brave` was the first engine via the "Change" modal under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows

**`1.71.114 Chromium: 130.0.6723.58`** | **`1.71.116 Chromium: 130.0.6723.58`**
--------------------------------------------|----------------------------------------------
![Image](https://github.com/user-attachments/assets/59c4c1a1-f750-4347-a6c5-eb21a6631071)|![Image](https://github.com/user-attachments/assets/c2abae15-b1a2-4a3e-a2f4-a0bae8cdadf9)
![Image](https://github.com/user-attachments/assets/f740fa3f-49c7-420f-a199-6b893c4702af)|![Image](https://github.com/user-attachments/assets/0ed0c8c3-39cd-4225-bead-a828dd3fb053)
![Image](https://github.com/user-attachments/assets/4ac98da9-3fe6-4ce6-93ef-a2ed81c65d4d)|![Image](https://github.com/user-attachments/assets/02c11559-e8f3-4e1e-8498-33e2402e02c3)



</details>

<details>
<summary>Updated Profile (DDG/Startpage) - PASSED</summary>

* installed `1.71.114 Chromium: 130.0.6723.58`
* changed the default SE to `DDG` under `brave://settings/search` for `Normal` windows
* changed the default SE to `Startpage` under `brave://settings/search` for `Private` windows
* updated to `1.71.116 Chromium: 130.0.6723.58`
* ensured that `DDG` wasn't replaced with `Brave` as the default SE for `Normal` windows
* ensured that `Startpage` wasn't replaced with `Brave` as the default SE for `Private` windows
* ensured that `Brave` was the first engine via the "Change" modal under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows

**`1.71.114 Chromium: 130.0.6723.58`** | **`1.71.116 Chromium: 130.0.6723.58`**
--------------------------------------------|-----------------------------------------------
![Image](https://github.com/user-attachments/assets/b8129329-eded-4673-ae48-b36a9f6e88a2)|![Image](https://github.com/user-attachments/assets/d4eefaf6-fcf1-45e4-9cf6-57751e4c5d3f)
![Image](https://github.com/user-attachments/assets/635bd774-19d3-47cc-b9c6-9f84a8dd6acb)|![Image](https://github.com/user-attachments/assets/f6ede6fe-8297-4fc6-b2e5-6c482a48edf5)
![Image](https://github.com/user-attachments/assets/c4dd3110-a698-4468-820b-0e2e6eb20481)|![Image](https://github.com/user-attachments/assets/3061d612-4bb0-4a09-a70a-8a5350e1666f)



</details>

---------

### GB locale - Existing Brave Search default region

<details>
<summary>Clean Profile - PASSED</summary>

* ensured that `Brave` was selected as the default for both Normal/Private windows via `brave://settings/search`
* ensured that `Brave` was the first engine via the "Change" modal under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows
* ensured that `Brave` was selected as the default via `brave://settings/searchEngines`

![Image](https://github.com/user-attachments/assets/3c4d937f-6b2d-4764-8ff0-aa5e72c29762)|![Image](https://github.com/user-attachments/assets/7e274951-713b-4e25-bde2-955688b772a5)|![Image](https://github.com/user-attachments/assets/c4ee09dd-988b-41f3-bc49-0bc2669ffe72)
--|--|--

</details>

<details>
<summary>Updated Profile (Brave/Brave) - PASSED</summary>

* installed `1.71.114 Chromium: 130.0.6723.58`
* ensured that `Brave` was the default SE selected under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the default SE selected under `brave://settings/search` for `Private` windows
* updated to `1.71.116 Chromium: 130.0.6723.58` 
* ensured that `Brave` is still the default SE for both `Normal` & `Private` windows
* ensured that `Brave` was the first engine via the "Change" modal under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows

**`1.71.114 Chromium: 130.0.6723.58`** | **`1.71.116 Chromium: 130.0.6723.58`**
--------------------------------------------|----------------------------------------------
![Image](https://github.com/user-attachments/assets/54caef57-c751-4c01-a87c-1d54a5ef29c2)|![Image](https://github.com/user-attachments/assets/c6813da0-02c7-43f4-a20e-5558ec02b3b4)
![Image](https://github.com/user-attachments/assets/b2414144-0b62-4e5b-8170-fd6115efad7b)|![Image](https://github.com/user-attachments/assets/928b53be-93cc-4860-b2f4-143bb0f08d2b)
![Image](https://github.com/user-attachments/assets/6dc47b68-2233-433c-8024-5bdbee72226a)|![Image](https://github.com/user-attachments/assets/94bcb319-aca4-4ba1-a4e2-61b7bec65ad3)



</details>

<details>
<summary>Updated Profile (Ecosia/Bing) - PASSED</summary>

* installed `1.71.114 Chromium: 130.0.6723.58`
* changed the default SE to `Ecosia` under `brave://settings/search` for `Normal` windows
* changed the default SE to `Bing` under `brave://settings/search` for `Private` windows
* updated to `1.71.116 Chromium: 130.0.6723.58`
* ensured that `Ecosia` wasn't replaced with `Brave` as the default SE for `Normal` windows
* ensured that `Bing` wasn't replaced with `Brave` as the default SE for `Private` windows
* ensured that `Brave` was the first engine via the "Change" modal under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows

**`1.71.114 Chromium: 130.0.6723.58`** | **`1.71.116 Chromium: 130.0.6723.58`**
--------------------------------------------|-----------------------------------------------
![Image](https://github.com/user-attachments/assets/e91e7361-fb6b-4d18-9803-118a65f43fc1)|![Image](https://github.com/user-attachments/assets/c238d468-340d-493e-bdc1-cf5742cc61f7)
![Image](https://github.com/user-attachments/assets/6b26edcc-e22c-49c2-8f8d-32e163f7ec77)|![Image](https://github.com/user-attachments/assets/7e5fb9cd-52d1-4480-a360-e4f69e1e9b84)
![Image](https://github.com/user-attachments/assets/46925475-baaf-4754-bd64-0988ee414577)|![Image](https://github.com/user-attachments/assets/d1334067-0712-4c4b-9068-3be7822c7692)



</details>

------------

### PL locale - Non Brave Search default region (Google is default SE)

<details>
<summary>Clean Profile - PASSED</summary>

* ensured that `Google` was selected as the default for Normal windows via `brave://settings/search`
* ensured that `Brave` was selected as the default for Private windows via `brave://settings/search`
* ensured that `Brave` was the first engine via the "Change" modal under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows
* ensured that `Google` was selected as the default via `brave://settings/searchEngines`
* ensured that `Brave` was listed first via `brave://settings/searchEngines`

![Image](https://github.com/user-attachments/assets/afc7a008-487a-4765-b1c3-0dead284b807)|![Image](https://github.com/user-attachments/assets/1652f010-398e-4d01-b215-90db2bc6fd2e)|![Image](https://github.com/user-attachments/assets/020fade0-38fd-4f86-8543-d43c723941ce)


</details>

<details>
<summary>Updated Profile (Google/Brave) - PASSED</summary>

* installed `1.71.114 Chromium: 130.0.6723.58`
* ensured that `Google` was the default SE selected under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the default SE selected under `brave://settings/search` for `Private` windows
* updated to `1.71.116 Chromium: 130.0.6723.58` and ensured that `Google` is still the default SE for `Normal` windows
* ensured that `Brave` is still the default SE for `Private` windows
* ensured that `Brave` was the first engine via the "Change" modal under`brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows

**`1.71.114 Chromium: 130.0.6723.58`** | **`1.71.116 Chromium: 130.0.6723.58`**
--------------------------------------------|----------------------------------------------
![Image](https://github.com/user-attachments/assets/c6c59fcf-be0c-44da-8df1-bdcb355946fd)|![Image](https://github.com/user-attachments/assets/f92e61c7-9f84-4523-b39b-f6f5e1b1d89e)
![Image](https://github.com/user-attachments/assets/31c118ec-f4d8-44e0-b6d2-9ee3bbaa2255)|![Image](https://github.com/user-attachments/assets/a33200e1-953f-432a-9e91-f2f052dcc3f1)
![Image](https://github.com/user-attachments/assets/28e0457d-d28f-45c3-96a2-491349c30660)|![Image](https://github.com/user-attachments/assets/c6f0e6f9-457d-44ac-af49-7cb92f3ff60d)


</details>

<details>
<summary>Updated Profile (Qwant/Google) - PASSED</summary>

* installed `1.71.114 Chromium: 130.0.6723.58`
* changed the default SE to `Qwant` under `brave://settings/search` for `Normal` windows
* changed the default SE to `Google` under `brave://settings/search` for `Private` windows
* updated to `1.71.116 Chromium: 130.0.6723.58`
* ensured that `Qwant` wasn't replaced with `Brave` as the default SE for `Normal` windows
* ensured that `Google` wasn't replaced with `Brave` as the default SE for `Private` windows
* ensured that `Brave` was the first engine via the "Change" modal under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows

**`1.71.114 Chromium: 130.0.6723.58`** | **`1.71.116 Chromium: 130.0.6723.58`**
--------------------------------------------|-----------------------------------------------
![Image](https://github.com/user-attachments/assets/7acaeb03-3aba-45ed-829d-8227a3455714)|![Image](https://github.com/user-attachments/assets/3973114d-b1a6-4ffb-b8c3-a7cd8cff9ceb)
![Image](https://github.com/user-attachments/assets/b39b7337-e560-4f0c-a357-0ab3eb25f658)|![Image](https://github.com/user-attachments/assets/043a51ec-40fd-4027-abec-7fa1c80dfed1)
![Image](https://github.com/user-attachments/assets/4fc98e59-7f92-4c36-958d-9cf119d9d2b9)|![Image](https://github.com/user-attachments/assets/1c21c66c-7e65-4fdd-8966-5c66a143f1c2)



</details>

**Comment by sedlund** [comment]
I was using https://priv.au searx instance.

After upgrade when I put anything in the URL/Search bar and pressed enter - enter did not work anymore.

I went to brave://settings/search  and the default search engine was blank.

Clicking 'Change' does nothing.

I had to go find my search engine and reactivate it and make it default for the URL/Search bar to work again.
