### ISSUE TITLE
[Material]: Remove Material UI overrides

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#41462]
These consistently break Chromium in Chromium bumps because we need to make sure we define all the colors they do (and we currently don't so there are probably some buried places where we show the placeholder red):
- https://github.com/brave/brave-browser/issues/37515
- https://github.com/brave/brave-core/commit/ef3e86df4106e87e51b019a5d9fc97a6695a9d16
- https://github.com/brave/brave-core/commit/dfb745b41a45c95f0b8bc2bce992987c2ab024c3
- https://github.com/brave/brave-core/commit/ddb4cb9507c5faf401cc9aa06d8db17695b8cc91
- https://github.com/brave/brave-core/commit/94a127e916cab6caec0c54c64ce094dc509eafbf
- https://github.com/brave/brave-core/commit/846957b71eae92976d850e6654b6e9e4adab1d80
- https://github.com/brave/brave-core/commit/bc6fc7fd5f7415907fcc0b98bb36155be8ab74c8
- https://github.com/brave/brave-core/commit/05efe7116beeb00b901a67b2a9e4a1f1601a3683
- https://github.com/brave/brave-browser/issues/41455

and they don't really buy us anything - the main changes I noted by deleting the file were the label colors in bubbles, and this was because our override wasn't setting a color, rather than something we were setting.

We should also go over the `brave/chromium_src/ui/color/ui_color_mixer.cc` at some point, because I suspect we can remove a bunch of the overrides.

Additionally, we're trying to use Chromium colors as much as possible to reduce these kind of problems

**Comment by LaurenWags** [comment]
@brave/qa-team when checking the test plan from https://github.com/brave/brave-core/pull/25863#issue-2571724446, please check both light and dark themes as well as spot check Private/Tor windows.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.72.91 Chromium: 130.0.6723.91 (Official Build) beta (64-bit)
-- | --
Revision | 14b8282de957b76db51dd53a3da23b482c1c19b7
OS | Windows 11 Version 23H2 (Build 22631.4391)
```


1. Installed 1.72.91
2. launched Brave
3. opened browserleaks.com/geo in a new tab
4. opened maps.google.com in a new tab
5. opened abcnews.com in a new tab
6. clicked Hamburger menu >> More tools >> Task manager


- Confirmed Bubble views appeared as expected compared with 1.71.x  (eg. GeoLocation prompts, or update notifications)
- Confirmed Native buttons appeared as expected compared with 1.71.x 
- Confirmed Bookmarks dialog appeared as expected compared with 1.71.x  
- Confirmed Task manager appeared as expected compared with 1.71.x  


1.71.x | 1.72.x (light) | 1.72.x (dark)
---- | -----

**_Bubble view_**

**_GeoLocation prompts_**

1.71.x | 1.72.x (light) | 1.72.x (dark)
---- | ----- | -----
![Image](https://github.com/user-attachments/assets/bec031b1-3976-4bb0-8895-7790c5597c97)|![Image](https://github.com/user-attachments/assets/41774d00-acfb-4f6e-8f3c-6f5c908481dc)|![Image](https://github.com/user-attachments/assets/7c184190-d423-491c-b3e1-64482025b5d5)


**_Permission notifications_**

1.71.x | 1.72.x (light) | 1.72.x (dark)
---- | ----- | -----
![Image](https://github.com/user-attachments/assets/6ae01dc0-3058-48ec-a76d-f5903d8b58c6)|![Image](https://github.com/user-attachments/assets/3d424245-73a5-49c2-89ce-857c231675c6)|![Image](https://github.com/user-attachments/assets/3b85a5e1-1aea-4ff3-b110-5782bb25e3f5)

**_Bookmarks dialog_**

1.71.x | 1.72.x (light) | 1.72.x (dark)
---- | ----- | -----
![Image](https://github.com/user-attachments/assets/737f66f4-4c1f-4e0d-8dee-ae924877327b)|![Image](https://github.com/user-attachments/assets/dca1231b-6cb5-4d75-854a-12be9f1ce03d)|![Image](https://github.com/user-attachments/assets/d57956b0-5e2b-44cf-aa88-8bd6c5b5dc90)


**_Task manager_**

1.71.x | 1.72.x (light) | 1.72.x (dark)
---- | ----- | -----
![Image](https://github.com/user-attachments/assets/1b839e22-ee2c-4d0b-88b3-1b1d0ed40993)|![Image](https://github.com/user-attachments/assets/6b3c7ed5-d31e-4045-99b9-bd4be12125c0)|![Image](https://github.com/user-attachments/assets/a8a517ab-9db1-4c8b-bbb2-11d1113860e1)

**_Native buttons_**

1.71.x | 1.72.x (light) | 1.72.x (dark)
---- | ----- | -----
![Image](https://github.com/user-attachments/assets/220610fc-a5f6-4042-b1ce-0c189114c170)|![Image](https://github.com/user-attachments/assets/7ea84df2-7296-4aa8-ad42-cddf058629a8)|![Image](https://github.com/user-attachments/assets/d2296074-54b5-4f7c-82d6-6c7732188f11)
