### ISSUE TITLE
Selecting a server when connected to optimal server continues to select optimal server

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#41477]
### Description

Selecting a server when connected to optimal server continues to select optimal server

### Steps to reproduce

1. Purchase an IAP subscription for VPN
2. Select VPN Server from menu
3. Go to the connected server and select details view
4. Select a regional server option
5. Updates the selection but continues to have Optimal server selected

### Actual result

https://github.com/user-attachments/assets/747c9512-9dba-44c7-811f-ea5f26117746

### Expected result

Should update to the new server as selected and not have multiple options selected

### Reproduces how often

Easily reproduced

### Brave version

1.71.104 x64 Beta build

### Device

- Brand/model: Google Pixel 8
- Android version: 14

### Channel information

- [ ] release (stable)
- [x] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @deeppandya @simonhong @brave/qa-team

**Comment by deeppandya** [comment]
@srirambv we have a pending uplift. It should be resolved with it.

**Comment by kjozwiak** [comment]
Closing the above as this was fixed/resolved by https://github.com/brave/brave-core/pull/25604 which was uplifted into `1.71.x` via https://github.com/brave/brave-core/pull/25649.

**Comment by kjozwiak** [comment]
The above requires `1.71.112` or higher for `1.71.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Galaxy Z Fold 6` using version(s):
```
Device/OS: Galaxy Z Fold 6 / q6quew-user 14 UP1A.231005.007 release-keys
Brave build: 1.71.112
Chromium: 130.0.6723.44 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41477#issue-2572794178
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the correct server is selected 
- Verified that multiple servers can't be selected

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/cda97588-08e8-42f4-8a76-5edbf7f46ab3) | ![2](https://github.com/user-attachments/assets/6f9a2dd2-ff39-45c2-8f43-d956af5f0e69) | ![3](https://github.com/user-attachments/assets/b4929f77-332c-4e6e-8d81-1991f4dc812d) | ![4](https://github.com/user-attachments/assets/021af297-9b7b-4878-9a40-c207f956f2c8) |
| ![1](https://github.com/user-attachments/assets/5d8274d3-cb10-4c68-a29c-73021c929fdf) | ![2](https://github.com/user-attachments/assets/7dbcee5c-a1d0-4f01-ab0a-6168e1509e0f) | ![3](https://github.com/user-attachments/assets/e80199bb-fb44-4d44-87e8-5571a29da952) | ![4](https://github.com/user-attachments/assets/11ef2b9a-d509-413b-a927-2d3e8913318f) |

https://github.com/user-attachments/assets/18635e14-7be1-4455-b244-ecd530967f48
