### ISSUE TITLE
Sync - UX improvement - Users need a confirmation message after first successful sync of two devices

### ISSUE THREAD

**Issue by alexwykoff** [brave/brave-browser#4147]
## Description 
After numerous usability tests, a consistent pattern of confusion emerged where showing a list of devices on sync chain was insufficient for conveying success to the users. This confusion led to operational errors on the part of the user.

## Steps to Reproduce
This is not a programmatic error, so to reproduce one would need to conduct usability tests with new users.

## Actual result:
Users exhibited confusion during the success state of the Sync flow.

## Expected result:
For first-time Sync users, they should leave the Sync settings page and continue operation of the browser.

## Reproduces how often: 
This is a fairly regular occurrence for new or non-technical users.

## Brave version (brave://version info)
0.62.51

## Version/Channel Information:
This is an omnichannel UX issue.

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

## Miscellaneous Information:
The proposed resolution is to introduce a new modal upon successful first completion which is manually dismissible and would auto-dismiss after a reasonable period of time (10 seconds).

**Comment by alexwykoff** [comment]
This is the proposed modal. Text and image are not final.
<img width="771" alt="Screen Shot 2019-04-17 at 7 58 53 PM" src="https://user-images.githubusercontent.com/1434040/56329923-7121e900-614b-11e9-9295-a75a6d572f56.png">

**Comment by AlexeyBarabash** [comment]
Right now if user sees device in the list that means that device has joined the sync chain.
