### ISSUE TITLE
Place Inactive tabs settings in the `Appearance` section

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#41482]
### Description

Currently the Inactive tabs setting can only be found via search. We need to place this setting in the Tabs section of brave://settings/appearance 
![Image](https://github.com/user-attachments/assets/aff0c45c-e2d8-42d6-a02e-66818794d724)

The label should read "Inactive tabs". 
Learn more link should go to [placeholder].

### Steps to reproduce

1. Open brave://settings/appearance
2. Scroll down to the Tabs section.
3. Should see the setting above.

### Actual result

![Image](https://github.com/user-attachments/assets/da5f156a-cf2f-438e-b6e7-a8f379d0bdc7)

### Expected result

See description.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.x and higher

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by emerick** [comment]
@rebron PR is ready to go, just need the correct learn more URL.

**Comment by Brave-Matt** [comment]
@emerick you can use this link for the learn more URL (note that it is currently in draft so will not be visible until article goes live but link will be the same):
https://support.brave.com/hc/en-us/articles/30938249371277

**Comment by emerick** [comment]
> [@emerick](https://github.com/emerick) you can use this link for the learn more URL (note that it is currently in draft so will not be visible until article goes live but link will be the same): https://support.brave.com/hc/en-us/articles/30938249371277

Thank you!

**Comment by LaurenWags** [comment]
@brave/qa-team can see notes under https://github.com/brave/brave-core/pull/25907#issuecomment-2407351700. Keep in mind:
- Setting name will be "Inactive tabs appearance" not "Inactive tabs" as mentioned in description (confirmed this with @rebron)
- Support article currently not live (yet)
- https://github.com/brave/brave-browser/issues/41576 logged for placement of setting under the "Tabs" section of brave://settings/appearance

See https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1728568063554079 for discussion.

**Comment by LaurenWags** [comment]
Requires 1.71.113 or higher for verification 👍🏻

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.71.113 Chromium: 130.0.6723.58 (Official Build) (64-bit)
-- | --
Revision | 3ee74228044546a84c661332ddb441a7a68108fa
OS | Windows 10 Version 22H2 (Build 19045.5011)

```
