### ISSUE TITLE
Move Activity Tab into Panel Portfolio View

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#41498]
### Platforms

all, Windows, macOS, Linux

### Description

To prepare for the new `Connection` tab in the `Panel`, we need to move the `Activity` tab into the `Portfolio` view under the `Segmented Controller`.

- `Activity` should now live on the `Portfolio` view as an option in the Portfolio `Segmented Controller`.
- There should no longer be an `Activity` button in the main `Panel` navigation.
- No changes should be made for the Wallet `Desktop` view.

![Image](https://github.com/user-attachments/assets/cedffa91-6ccf-423c-846f-243a91acc3a5)

**Comment by LaurenWags** [comment]
@Douglashdaniel please add the following required labels:
- `OS/Desktop` and/or `OS/Android` and/or `OS/iOS`

Thanks!

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.72.82 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 4f0233b15f1896e28ff5ce439de1f658a2ef2df0
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from [brave/brave-core#25896](https://github.com/brave/brave-core/pull/25896)
- Verified `Activity` tab is shown in `Segmented Controller` in panel
- Verified `Activity` works as expected
- Verified there is no `Activity` tab in main wallet panel
- Verified nothings changed on Wallet desktop view

https://github.com/user-attachments/assets/e71b4774-16de-4527-a8af-2e9a968373bb
