### ISSUE TITLE
Reapply "[Rounded Corners]: Fix WebContents shadow in light mode" with fixes

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#41496]
https://github.com/brave/brave-core/pull/25738 was reverted because it was causing crashes in Nightly. We should fix the crashes and reland it.

**Comment by simonhong** [comment]
@fallaciousreasoning Can you attach crash log in this issue?

**Comment by simonhong** [comment]
Ah, NVM I found - https://github.com/brave/brave-browser/issues/41465#issuecomment-2399667241

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.74.10 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | bdff9e7d7314280ddbce1c3ada3abee4ce4a3b32
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

1. Installed 1.74.10
2. launched Brave 
3. opened few tabs
4. opened brave://flags in a new tab
5. verified `#brave-web-view-rounded-corners` flag is enabled by default
6. opened google.com in a new tab
7. enabled vertical tabs
8. confirmed that the NTP is shown as expected as per the screenshot in https://github.com/brave/brave-core/pull/25738#issue-2557992813
9. confirmed no space existing between web contents and sidebar in any theme with sidebar left side or right side
10. confirmed Brave didn't crash upon restart when collapsed and expand on hover in vertical tabs mode 



https://github.com/user-attachments/assets/41f5208c-31c2-4455-846b-f143c94eaa83
