### ISSUE TITLE
Many toggles broken (Extensions, Sync) in Brave 1.72 and newer

### ISSUE THREAD

**Issue by TEMP-ad** [brave/brave-browser#41493]
### Description

Toggles in settings stopped working in latest versions of Brave Nightly, I only tested from Nightly v1.72.59 (Chromium 129.0.6668.89) to Nightly v1.72.68 (Chromium 130.0.6723.31), and they all have the same issue.

I was not going to test every build so I ended up installing 1.71.81 with Chromium: 129.0.6668.31 from September 10th, and everything worked as it should, so, it is clear a Brave issue, I have tested this in a new User Data and everything is exactly the same in latest Brave builds.

I don't know which toggles or other settings don't work, because I only care to test the toggled I needed to change, and those are from Sync and Extension settings.

- Sync toggles don't toggle and they stay the same like if they were disabled, so it is impossible to change any sync setting, and this is bad especially for new sync chains where the only default is Bookmarks.
- For extension settings, the toggles 'toggle', but the settings don't 'stick' / write to the secured preferences file, once you reload the page, they all go back to whatever was set.

This is a serious bug and hope it gets fixed soon, I downgraded to be able to change settings, so I couldn't record what happens, but it is pretty easy to reproduce, I reproduced with even a totally new user data which shows it is not an extension or flag causing the issue. I don't know if it is an upstream issue, but I don't use Chrome to test that.

Thanks.

## Sync 
1. Create a Sync Chain
2. Try to change any setting, you can't.

## Extension settings
1. Install any extension
2. Go to brave://extensions and details and try to enable `Allow in Private`
3. refresh the settings or open inPrivate window and it doesn't work. 

### Actual result

https://github.com/user-attachments/assets/48c2c00f-585a-452a-a570-5f55d25981f9

https://github.com/user-attachments/assets/67238eaa-40b3-4c64-9fa4-b2bdd4874b6b

### Expected result

Toggles should work normally again.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Tested from `Nightly v1.72.59 (Chromium 129.0.6668.89)` to `Nightly v1.72.70 (Chromium 130.0.6723.31)` on Windows 11 24H2

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by TEMP-ad** [comment]
@bsclifton 

This is a pretty bad bug that has existed in Brave for more than 2 weeks, this needs to be fixed soon, hoping it doesn't 'leak' to Stable and more users get affected.

**Comment by TEMP-ad** [comment]
I added some videos about the issue and also tested every build until I found the last working one.

The problem started with [1.72.15](https://github.com/brave/brave-browser/releases/tag/v1.72.15) 3 weeks ago https://github.com/brave/brave-core/commits/d1172c56951380d9ab0e1f2258bafaa246d84c6a/

I searched for duplicates about it and I will say it's incredible nobody has said anything about this.

**Comment by francoism90** [comment]
Just to be sure, is this also on a new profile (without any custom flags)?

Not a Brave developer, not running nightly (only beta), just wondering if it's related to something else.

**Comment by TEMP-ad** [comment]
Yes, no extensions or flags or anything, completely new user data; and just installing adguard extension and joining/creating a sync chain, the problem is reproducible like in the videos.

**Comment by emerick** [comment]
@TEMP-ad As a temporary workaround, does it help if you click on the text of the setting (as opposed to clicking directly on the button itself?)

**Comment by bsclifton** [comment]
Seems to be in 1.71.x also

I'll see if I can check this out today - will share any notes. Also cc: @fallaciousreasoning who can help 😄

**Comment by bsclifton** [comment]
Also see https://github.com/brave/brave-browser/issues/41495 for repro steps

Seems to only be happening on 1.72 and newer. Thanks to @LaurenWags for helping me test on 1.71.112 - both sync and the extension details page seemed OK

@fallaciousreasoning can you take a look please? 😄

**Comment by TEMP-ad** [comment]
@emerick yes, that does the job, the toggles are the problem but not clicking on the text to toggle the settings 👍

@bsclifton I gave the exact build when this started happening:

> The problem started with [1.72.15](https://github.com/brave/brave-browser/releases/tag/v1.72.15) 3 weeks ago https://github.com/brave/brave-core/commits/d1172c56951380d9ab0e1f2258bafaa246d84c6a/

**Comment by LaurenWags** [comment]
Requires 1.72.83 or higher for verification 👍🏻

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.86 Chromium: 130.0.6723.70 (Official Build) beta (64-bit)
-- | --
Revision | f0bc5ea984bb6d35613d0c0b22c26fbb09b60198
OS | Windows 11 Version 23H2 (Build 22631.4391)
```


1. Installed 1.72.86
2. launched Brave
3. created sync chain in the profile
4. created a second profile via hamburger menu
5. joined the sync chain
6. toggled Sync data on/off
7. added an extension via chrome webstore (eg. Grammerly)
8. opened `brave://extensions` in a new tab
9. clicked Details
10. toggled on for `Allow in Private`

- Confirmed Sync data toggles worked as expected in both profiles
- Confirmed toggle worked for Private window and working as expected


https://github.com/user-attachments/assets/9604148c-f5ac-44be-a773-62d71bfcd9e5
