### ISSUE TITLE
[iOS] - ReaderMode replacement text

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#41491]
### Description

- https://hackerone.com/reports/2760854

### Steps to reproduce

1. N/A

### Actual result

N/A

### Expected result

N/A

### Reproduces how often

Easily reproduced

### Brave version

1.65.x+

### Device/iOS version

All

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kylehickinson** [comment]
Duplicate of https://github.com/brave/brave-browser/issues/41444
