### ISSUE TITLE
Update PB SE selection under `brave://settings/search` to use `Change` button rather than current dropdown

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#41499]
### Description

As @MadhaviSeelam mentioned via https://github.com/brave/brave-browser/issues/41346, the SE selection has changed in `C130`. Rather than a drop down like before, there's a `Change` button. Per @emerick, re-adding that code would be a lot of effort so we're better off keeping the new changes. However, our `PB` drop down should match the design/functionality of the new `Change`  button.

### Steps to reproduce

1. visit `brave://settings/search`
2. notice that the SE selection is done via a `Change` button but PB is still using the old dropdown UI/UX

### Actual result

![Image](https://github.com/user-attachments/assets/2648f148-6cad-4cd4-b264-0cbce1cb51b1)

### Expected result

Dropdown for PB should use the `Change` button UI/UX similar to that the new SE selection which was enabled via `C130`.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.72.68 Chromium: 130.0.6723.31 (Official Build) nightly (64-bit)
-- | --
Revision | f04ca2afa25cd46e348d74922bb587b88d56cba6
OS | Windows 11 Version 23H2 (Build 22631.4249)
```

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

CCing @rebron @brave/qa-team

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.75.145 Chromium: 132.0.6834.57 (Official Build) nightly (64-bit)
-- | --
Revision | 4ecdecd1626892f9f317e9d8154c50cf8459d3bf
OS | Windows 11 Version 24H2 (Build 26100.2605)
```

1. Installed 1.75.145
2. launched Brave
3. opened brave://settings/search
4. confirmed Private window selection entry shows `Change` button with `Brave` as a default 
5. clicked `Change` button
6. selected `StartPage` and clicked `Set as default
7. confirmed SE selection got updated to `StartPage` as expected.
8. opened Private window via hamburger menu
9. URL bar shows DuckDuckGo placeholder text


step 4 | step 6 | step 7 | step 9
------ | ------- | ------ | -----
![Image](https://github.com/user-attachments/assets/58c223fb-294d-4fec-8877-a7084bd2f28a)|![Image](https://github.com/user-attachments/assets/4715a083-bc74-4ce2-9d3b-6b0931d1d2f8)|![Image](https://github.com/user-attachments/assets/faeb18f9-c051-4296-8f4d-805dd55d5800)|![Image](https://github.com/user-attachments/assets/370d0dd4-226c-4919-9d14-843aeae0796a)

**Comment by kjozwiak** [comment]
Added `QA/Test-All-Platforms` after speaking with @LaurenWags. As the new UI is going to be used for `deep linking`, we should ensure that everything is working as expected re: the new UI for selecting PB SE.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.75.159 Chromium: 132.0.6834.83 (Official Build) beta (arm64)
-- | --
Revision | a7b6f5093a2dad31fc3f56241a7d55be255e69e2
OS | macOS Version 15.2 (Build 24C101)
```

New Profile: 

1. Installed 1.75.145
2. launched Brave
3. opened brave://settings/search
4. confirmed Private Window selection entry shows `Change` button with `Brave` as a default 
5. clicked `Change` button
6. selected `DuckDuckGo` and clicked `Set as default
7. confirmed SE selection got updated to `DuckDuckGo` as expected.
8. opened Private window via hamburger menu
9. URL bar shows `StartPage` placeholder text
10. searched by `test` and the search results page show correct search engine

example | example | example | example | example | example 
----- | ------- | ------- | ------- | ------- | --------
![Image](https://github.com/user-attachments/assets/0e3eab05-4a78-40f4-a44c-c827ead350a2)|![Image](https://github.com/user-attachments/assets/ddcd6243-0959-4d40-9915-c2f693b79c4f)|![Image](https://github.com/user-attachments/assets/e4616b97-5a14-4bf8-b3db-e8e382a52ceb)|![Image](https://github.com/user-attachments/assets/9917a903-91df-46d9-8fbb-52cf8fc3edaa)|![Image](https://github.com/user-attachments/assets/a7fa6009-5bec-4818-a736-8f243aa07648)|![Image](https://github.com/user-attachments/assets/f3fb2af2-4b51-45f0-8826-b65db32dec42)


Upgrade:

1. Installed  1.74.48
2. launched Brave
3. opened brave://settings/search
4. verified Private window selection shows a drop down with Brave as default
5. quit the browser
6. renamed the profile to Brave-Browser-Beta
7. installed 1.75.145
8. launched Brave
9. confirmed Private Window selection entry shows `Change` button with `Brave` as a default 
10. clicked `Change` button
11. selected `Google` and clicked `Set as default
12. confirmed SE selection got updated to `Google` as expected.
13. opened Private window via hamburger menu
14. URL bar shows `StartPage` placeholder text
15. searched by `test` and the search results page show correct search engine


example | example | example | example | example | example 
----- | ------- | ------- | ------- | ------- | --------
![Image](https://github.com/user-attachments/assets/ae5b6d5c-38a6-49fe-b3da-af349673d548)|![Image](https://github.com/user-attachments/assets/19fc9664-8ad7-40d2-a6dd-563c986c9d9c)|![Image](https://github.com/user-attachments/assets/c89a68b5-365e-403c-962b-1427f537aa5d)|![Image](https://github.com/user-attachments/assets/0e3468c9-7ef1-4b3d-b2de-4fe3cde38b83)|![Image](https://github.com/user-attachments/assets/64016b17-0aeb-4d64-b3ec-a625a451b5eb)|![Image](https://github.com/user-attachments/assets/fcc24820-e9b8-48fd-9590-3d6e8858ae34)

**Comment by btlechowski** [comment]
Verified with

Brave | 1.75.170 Chromium: 132.0.6834.111 (Official Build) beta (64-bit)
-- | --
Revision | ea6b6fa547193f9769ffb0068880a4f41e364864
OS | Linux


#### New Profile: 

<details>

1. Installed 1.75.159
2. launched Brave
3. opened brave://settings/search
4. confirmed Private Window selection entry shows `Change` button with `Brave` as a default 
5. clicked `Change` button
6. selected `DuckDuckGo` and clicked `Set as default
7. confirmed SE selection got updated to `DuckDuckGo` as expected.
8. opened Private window via hamburger menu
9. URL bar shows `DuckDuckGo` placeholder text
10. searched by `test` and the search results page show correct search engine


</details>

#### Upgrade:

<details>

1. Installed  1.74.48
2. launched Brave
3. opened brave://settings/search
4. verified Private window selection shows a drop down with Brave as default
5. quit the browser
6. renamed the profile to Brave-Browser-Beta
7. installed 1.75.145
8. launched Brave
9. confirmed Private Window selection entry shows `Change` button with `Brave` as a default 
10. clicked `Change` button
11. selected `Google` and clicked `Set as default
12. confirmed SE selection got updated to `Google` as expected.
13. opened Private window via hamburger menu
14. URL bar shows `Google` placeholder text
15. searched by `test` and the search results page show correct search engine




</details>
