### ISSUE TITLE
Make UI related to extension store visible in settings and extensions page

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#415]
UI elements in settings and extensions page related to extension web store will be hidden after https://github.com/brave/brave-core/pull/179 is merged.
This issue is for making them visible again once we have our extension store ready.
Basically what https://github.com/brave/brave-core/pull/179/commits/817e41477f9da498fbd84fbb5a37c56802b7a2a3 is hiding will need to be revisited and urls should be replaced by our own extension store link.

**Comment by bsclifton** [comment]
Web store link has been re-added and has been genericized ("web store")
