### ISSUE TITLE
https://www.skysports.com being incorrect categorized as "business-ecommerce"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#4151]
## Description 

When visiting https://www.skysports.com, Brave will classify the website as `business-ecommerce` rather than `sports` or `sports-soccer`. Example:

```
[17424:775:0417/173224.272512:INFO:ads_impl.cc(418)] Site visited https://www.skysports.com/, immediateWinner is business-ecommerce and winnerOverTime is business-ecommerce, previous tab url chrome://rewards/
```

Here's the `pageScore`: [pageScoreSkySports.txt](https://github.com/brave/brave-browser/files/3092143/pageScoreSkySports.txt)

## Steps to Reproduce

Prerequisite: build with ads enabled/working.

   1. launch brave and enable `brave://rewards` (used `0.63.44 Chromium: 74.0.3729.75`)
   2. visit https://www.skysports.com and wait for the categorization

## Actual result:

https://www.skysports.com is being categorized as `business-ecommerce`

## Expected result:

https://www.skysports.com should be categorized as `sports` or `sports-soccer`

## Reproduces how often: 

Reproducible 100% of the time when going through the STR.

## Brave version (brave://version info)

Brave | 0.63.44 Chromium: 74.0.3729.75 (Official Build) beta(64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? No (not enabled on release)
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

CCing @mandar-brave

**Comment by jsecretan** [comment]
This is probably just best for tracking, to revisit once @dimmu has a new model.

**Comment by tmancey** [comment]
Tested in 1.23.x and classified text with the top segment as sports-sports. This is now working as expected.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.23.36 Chromium: 89.0.4389.86 (Official Build) nightly (x86_64)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:
1. launched with `--args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true`
2. visited `https://www.skysports.com/`
3. examined console logs and saw `[1909:775:0312/130140.121931:VERBOSE1:text_classification_processor.cc(62)] Classified text with the top segment as sports-sports`

From `client.json`: 

`{"segment":"sports-sports","pageScore":0.06054215743315853}`
