### ISSUE TITLE
Instagram forbid the open sharing of crime links to anyone

### ISSUE THREAD

**Issue by noelknaepen** [brave/brave-browser#41511]
### Description

Instagram have a privacy policy Act 1974 issues, young female abuse of promoting adult links to anyone who have a profile, to dark websites providing pornografic services under the chat with kids age 13. Stop the overall sharing of links on the platform even under the vpn users?

**Comment by bsclifton** [comment]
I'm going to close this out - I'm confused about this issue

If the ask is to intercept behavior on Instragram, it would be more appropriate to address this by creating an extension (see the [Chrome Web Store](https://chromewebstore.google.com/))
