### ISSUE TITLE
Crash Report: NTP renderer process OOM

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#41528]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.71.88 Chromium: 129.0.6668.42
Operating System: Mac OS X 14.7.0

Can you reproduce this crash?
The crash is intermittent. 

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open NTP
2. Don't navigate/open new tab/switch it for a long time

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/98e51b00-1893-b30c-0000-000000000000

**Comment by fallaciousreasoning** [comment]
Should be fixed by https://github.com/brave/brave-core/pull/25778 (in 1.71.106)
