### ISSUE TITLE
"Quick Commands" were re-enabled when upgrading Brave Nightly

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#41525]
### Description

just updated nightly (i was maybe 4 days old, now at current) and my “Quick Commands” option got re-enabled.  I am certain i had this disabled before, and on starting nightly it was re-enabled

I also cleared browsing data before restarting Brave, but i also wouldn’t expect this to change any of the “Show autocomplete suggestions in address bar” options.

### Steps to reproduce

0. disable "quick commands" in the address bar `brave://settings/?search=quick+comm`
1. clear all browsing data
2. upgrade nightly

### Actual result

quick commands was re-enabled

### Expected result

should stay disabled

### Reproduces how often

No steps to reproduce

### Brave version (brave://version info)

1.72.72 Chromium: 130.0.6723.31 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment]
cc: @fallaciousreasoning

**Comment by MadhaviSeelam** [comment]
Could not reproduce the issue after upgrading to latest nightly build

`1.73.25 Chromium: 130.0.6723.58 (Official Build) nightly (64-bit)`

example | example 
------ | ------
![Image](https://github.com/user-attachments/assets/5a436df2-c166-4ded-879d-923931297a26)|![Image](https://github.com/user-attachments/assets/2eca55b1-be2b-4a15-a7f8-5ac28db7b815)

**Comment by rebron** [comment]
@pes10k We may need you to check this again in Brave Nightly, we haven't been able to reproduce.
