### ISSUE TITLE
Shred button cut off in private tab tray

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#41520]
### Description

In the private mode tab tray, the shred button is cut off by open tabs.

### Steps to reproduce

1. Enable Shred feature flag & restart browser
2. Open tab tray
3. Tap private
4. Open at least 2 tabs

### Actual result

<img src="https://github.com/user-attachments/assets/b6a1e44b-f92c-4159-98e9-129f6fbaed73" width="300">

### Expected result

Shred button is not cut off

### Reproduces how often

Easily reproduced

### Brave version

1.71

### Device/iOS version

--

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.71.113` or higher for `1.71.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.0` using version `1.71.115`

* Ensured that additional padding/margin was added on top of Shred button so its not cut off in tab view. 
* Ensured there are no issues tapping on Shred button. 

1.70 | 1.71.115 | Shred dialog
---|---|---
![Image](https://github.com/user-attachments/assets/7eccb696-2bba-40c7-bdab-0ea3deeb34cd) | ![Image](https://github.com/user-attachments/assets/69e0fac7-adc2-4551-a4fa-eb9887cb5e15) | ![Image](https://github.com/user-attachments/assets/3b0106e3-004e-4fcc-a92b-4990758f71af)
