### ISSUE TITLE
Don't show caption options in media control popup

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#41527]
### Description

We shouldn't display the caption options in the media control popup

### Steps to reproduce

1. Search for video on youtube.com
2. Play video
3. Click musical note icon to display media control popup window

### Actual result

![Image](https://github.com/user-attachments/assets/3288d685-9f86-4099-b8cf-600b4a5778f8)

### Expected result

We shouldn't show the caption options in the media control popup.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Latest master

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by LaurenWags** [comment]
Requires 1.71.112 or higher for verification 👍🏻

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.71.112 Chromium: 130.0.6723.44 (Official Build) (64-bit)
-- | --
Revision | 7d51df656b247f9432ee714a6d160142a1e11c13
OS | Windows 11 Version 23H2 (Build 22631.4317)
```
