### ISSUE TITLE
BAT Tips don't work on a VPN

### ISSUE THREAD

**Issue by RossClelland** [brave/brave-browser#4153]
## Description 

When connected to a VPN, trying to send a tip results in an error. 'There was a problem processing your tip, please try again.'.

Disconnecting from the VPN immediately resolves the problem. I'm using Private Internet Access.

## Steps to Reproduce

   1. Connect to VPN 
   2. Visit Brave registered website
   3. Attempt to make a tip
   4. Error shown
   5. Disconnect VPN
   6. Attempt to make a tip
   7. Tip is sent and balance debited 

## Actual result:

There was a problem processing your tip, please try again

## Expected result:
Tip sent and BAT balance debited 

## Reproduces how often: 

100% of the time I'm on the VPN

## Brave version (brave://version info)

Android. Brave version 1.0.91.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/a on android
- Can you reproduce this issue with the dev channel? N/a on android
- Can you reproduce this issue with the nightly channel? N/a on android

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.5 x64` using the following build:

Brave | 0.66.87 Chromium: 75.0.3770.80 (Official Build) beta(64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Mac OS X

* tipped https://kjozwiak.github.io/ `1 BAT` while connected to a Japan endpoint
* tipped https://www.youtube.com/channel/UCCatR7nWbYrkVXdxXb4cGXw `5 BAT` while connected to a Spain endpoint
* tipped https://duckduckgo.com/ `1 BAT` while connected to a Singapore endpoint
* tipped https://clifton.io/ `1 BAT` while connected to a Russia endpoint
* tipped https://archive.org/ `5 BAT` while connected to a Israel endpoint

<img width="650" alt="Screen Shot 2019-06-11 at 1 54 41 PM" src="https://user-images.githubusercontent.com/2602313/59295022-b39a0a80-8c50-11e9-8c75-9c0ba5784fa1.png">
