### ISSUE TITLE
[CR130] Navigation bar color at private tab

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#41545]
### Description

Reported by @simoarpe 

Navigation bar color at private tab is wrong.
This is CR130 regression

before|now
--|--
![Image](https://github.com/user-attachments/assets/6db9c337-e1ca-4af1-b6b3-f0dd7c767d46)|![Image](https://github.com/user-attachments/assets/eba2c8ea-bdd7-42b8-b161-bec2d4739d14)

### Steps to reproduce

1. Take Nightly 1.72.66
2. Open private tab

### Actual result

See issue description

### Expected result

See issue description

### Reproduces how often

Easily reproduced

### Brave version

Nightly 1.72.66

### Device

- Brand/model: Any 
- Android version: Any

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by LaurenWags** [comment]
Requires 1.71.113 or higher for verification 👍🏻

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240823.009 release-keys
Brave build: 1.71.113
Chromium: 130.0.6723.58 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/25923#issuecomment-2408199240
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the OS `navigation bar` has the correct color in the `Private` and `Standard` tabs.
- Verified the same when the device theme is set to `Light` and `Dark` mode.
- Verified the same for `Gesture navigation` and `3-button navigation`.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/91eaf791-8af2-4002-a40a-e24385380073) | ![2](https://github.com/user-attachments/assets/58d936fe-12f7-4bfe-89e7-4477a3473e48) | ![3](https://github.com/user-attachments/assets/6954b911-5493-4e0d-870a-00af5f109a17) | ![4](https://github.com/user-attachments/assets/b54450c5-a977-4326-9047-810077734b01) |
| ![1](https://github.com/user-attachments/assets/7750f8e3-caab-49b7-8f1d-c0a69c031ebd) | ![2](https://github.com/user-attachments/assets/79e78c2b-5da6-4e7c-baad-d1b79c2b684e) | ![3](https://github.com/user-attachments/assets/ca2a4f06-585c-42b0-a502-5a47843bc8b6) | ![4](https://github.com/user-attachments/assets/76461a3e-564e-4f00-97b5-a8123a4c4240) |
