### ISSUE TITLE
urlbar - Open with Tor button style update

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#41546]
We're going to change the style of the "Open with Tor" button in the omnibar.

The idea is to make it look exactly like the other buttons like reader mode, playlist, etc. Remove the background and use our default icon color for omnibar items.

![Image](https://github.com/user-attachments/assets/30f18562-68c8-4949-9531-a2c06bf98eda)

https://www.figma.com/design/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?node-id=1386-11575&t=ZMxbI58Lb6Hv0sjp-1

**Comment by boocmp** [comment]
There is  the `.onion` button in the Tor window:
![Image](https://github.com/user-attachments/assets/d7230258-f0a2-4f1b-872a-f25f21613d8b)

Do we want to change the style for it as well?
This is how it will look
![Image](https://github.com/user-attachments/assets/06d256e4-5288-406b-8217-e28aa14b8a1a)

**Comment by aguscruiz** [comment]
I think the one in the Tor window is fine as it is, since it's what you would want to see highlighted anyways. Let's keep that one with that pink background.

**Comment by kjozwiak** [comment]
The above requires `1.72.85` or higher for `1.72.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.87 Chromium: 130.0.6723.70 (Official Build) beta (64-bit)
-- | --
Revision | d7efa3dbae2fa83142b51cea45f023f01d3eeb33
OS | Windows 11 Version 23H2 (Build 22631.4391)
```

Installed 1.72.87
launched Brave
opened nytime.com in a normal window
opened brave.com in a normal window
opened proton.me in a normal window

### Confirmed `Open in Tor` button is updated and matched to the screenshot in the issue

nytimes.com | brave.com | proton mail
----- | ------ | -------
![Image](https://github.com/user-attachments/assets/65029f91-521f-45f9-89be-d457ab6fc05e)|![Image](https://github.com/user-attachments/assets/438e44f5-6f53-4426-8c07-a23c61cd1eba)|![Image](https://github.com/user-attachments/assets/89b9ace3-cbf7-484e-aaf9-08154e8aad19)
![Image](https://github.com/user-attachments/assets/fac3e9ed-9197-4563-b2ab-e3c756712f5a)|![Image](https://github.com/user-attachments/assets/c0502f10-c3b4-4265-b863-cf832eea7c36)|![Image](https://github.com/user-attachments/assets/b482aa80-ec08-4ab3-b645-991808766b69)


**_Dark theme_**

nytimes.com | brave.com | proton mail
----- | ------ | -------
![Image](https://github.com/user-attachments/assets/98f2ffa7-805d-4948-b241-88f76dc5920a)|![Image](https://github.com/user-attachments/assets/3def9049-d23b-4952-8351-d49c9bca05fd)|![Image](https://github.com/user-attachments/assets/2384a3ab-ccbd-4e92-82fe-2b4254e6906c)



**_Tor window_** 

#### Confirmed `.onion` button is shown as expected. 

proton mail | nytimes
----- | ------
![Image](https://github.com/user-attachments/assets/daaa7c88-ca82-4b21-8777-93fc79e51e39)|![Image](https://github.com/user-attachments/assets/01cdfa2d-ff67-4c69-b64d-8f2ff0c79f56)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.93 Chromium: 131.0.6778.14 (Official Build) beta (arm64)
-- | --
Revision | 69e5dc20ca483a13316632df5bcd9279bb2a3cb7
OS | macOS Version 14.6.1 (Build 23G93)
```

1. Installed 1.72.93
2. launched Brave
3. opened nytime.com in a normal window
4. opened brave.com in a normal window
5. opened proton.me in a normal window

 ### Confirmed `Open in Tor` button is updated and matched to the screenshot in the issue
 
nytimes.com | brave.com | proton.me
---- | ------ | -------
![Image](https://github.com/user-attachments/assets/2828b474-93f1-4ac0-a0c5-1459c6398da6)|![Image](https://github.com/user-attachments/assets/350633fd-eba3-4255-8661-b292f91fded4)|![Image](https://github.com/user-attachments/assets/849ec2ec-a01b-4bc1-b283-dbfe7164ea5d)


**_Dark theme_**

nytimes.com | brave.com | proton.me
----- | ------ | -------
![Image](https://github.com/user-attachments/assets/f081b1be-175d-44ec-bea0-05df7516de8c)|![Image](https://github.com/user-attachments/assets/37c5b5ca-8b1f-43d4-9777-ba2f86139ba9)|![Image](https://github.com/user-attachments/assets/03f7473d-1647-42b2-8ad2-e2a6cc3983ab)


**_Tor window_** 

#### Confirmed `.onion` button is shown as expected. 

proton.me | nytimes.com
----- | ------
![Image](https://github.com/user-attachments/assets/467a4cce-30b2-498b-acaa-61716de56f5f)|![Image](https://github.com/user-attachments/assets/93735d81-d20f-4083-a00e-ab7155701127)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.72.95 Chromium: 131.0.6778.24 (Official Build) beta (64-bit) 
Revision	006619fbaf6013cb3495b90fc3885eda343087e5
OS	Linux
JavaScript	V8 13.1.201.5
```


1. Installed 1.72.95
2. launched Brave
3. opened nytimes.com in a normal window
4. opened brave.com in a normal window
5. opened proton.me in a normal window

### Confirmed `Open in Tor` button is updated and matched to the screenshot in the issue
###  Confirmed when hovered on `Open in Tor` button, the `.onion` link is shown
###  Confirmed when clicked on the `Open in Tor` button, it navigated to Tor window
 
**_Dark theme_**

nytimes.com | brave.com | proton.me
---- | ------ | -------
![Image](https://github.com/user-attachments/assets/644fdaae-aa1e-43d7-8228-753c72985c11)|!![Image](https://github.com/user-attachments/assets/b0a14b07-3fdb-4afe-be44-8956875bfc73)|![Image](https://github.com/user-attachments/assets/d967deb9-b1a2-43a8-9934-04f83042a8dc)
![Image](https://github.com/user-attachments/assets/7f841bf6-d68c-4aa0-8363-4b2273652641)|![Image](https://github.com/user-attachments/assets/8756fff6-c300-4bcd-817e-17edb2ac65aa)|![Image](https://github.com/user-attachments/assets/d7915397-cd09-405d-92ca-5d62583472bd)


**_Light theme_**

nytimes.com | brave.com | proton.me
---- | ------ | -------
![Image](https://github.com/user-attachments/assets/11aa0614-8b3c-403c-9207-1519adbbec60)|![Image](https://github.com/user-attachments/assets/214cd7dc-b5f4-459e-a566-40d2e6f1eb29)|![Image](https://github.com/user-attachments/assets/0f34b65b-4090-41d4-8a99-8a9ff04bdcf5)|![Image](https://github.com/user-attachments/assets/9fcab0e5-196a-4c7b-a6b2-950ab6bcd382)

*__Tor window__*

nytimes.com | brave.com | proton.me
---- | ------ | -------
![Image](https://github.com/user-attachments/assets/b8a13fff-951c-409f-bc02-c88654be28fe)|![Image](https://github.com/user-attachments/assets/8a789cd1-e356-456a-9be2-85a7c359e9c8)|![Image](https://github.com/user-attachments/assets/d1869806-527b-4237-bffc-438ac62049a0)
