### ISSUE TITLE
Ads shows region not supported on upgrade

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#4154]
For upgrade paths from `<0.63.x`, the Ads panel shows that the Region is not supported, but then when the page is reloaded, it correctly does.

It should show that the Region is correctly supported on first load.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.63.46 Chromium: 74.0.3729.91 (Official Build) (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Linux

* Verified test plan from https://github.com/brave/brave-core/pull/2263
