### ISSUE TITLE
Internationalization Support for Leo system prompts (For locales fr, de, it, es)

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#41554]
### Description

 Internationalization Support for Leo

Brave browser sends up a `selected_language` and a `system_language` with prompts.

The `selected_language` is initially an empty string, but the server can send a SelectedLanguage event to set the language for future.

The server sets a selected_language based on what it detects the first message's language to be in.  If it can't make that determine or that message is not long enough it can fallback to using the system language.
Or if there is no system language specified it will use English.

More details here:
https://docs.google.com/document/d/1IWQNX-E40ujaQFQVavZEtgK3J068PgZ_xDbSLDWZOD8/edit?tab=t.0#heading=h.miolul91b7va

### Steps to reproduce

Type in "Bonjour, ça vas" without quotes to Leo? 
Repeat similarly for Spanish, German, and Italian. 
You can test with Release channel to see if you reproduce before verifying the fix in this issue.

Here are some other test strings:
English
was there an assassination attempt against Donald Trump?

French
y a-t-il eu une nouveau tentative d'assassinat contre Donald Trump ?

Spanish:
¿Hubo un intento de asesinato contra Donald Trump?

Italian:
c'è stato un tentativo di omicidio contro Donald Trump?

German:
var der et mordforsøg mod Donald Trump?

### Actual result

Reply is in English

### Expected result

Reply should be in the user's language.  We require 3 words at least to determine the language, and otherwise it uses the system language to convert the system prompts for. 

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

1.72.61 

### Android device

n/a

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.72.90` or higher for `1.72.x` verification 👍

**Comment by Uni-verse** [comment]
In progress on `Samsung Galaxy S21` using the following version(s):

```
Brave	1.72.93 Chromium: 131.0.6778.14 (Official Build) beta (64-bit) 
Revision	69e5dc20ca483a13316632df5bcd9279bb2a3cb7
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

Test Plan: https://github.com/brave/brave-browser/issues/41554#issue-2579453598

1. Set device language to non-english
2. Sent some test strings in `fr`, `de`, `it`, `es-us` and `en-us`
3. Confirmed response matches the language used by the user
4. Sent test strings under 3 words to test the logic

`Spanish` | `Italian` | `German then English` | `German` | `French`
---|---|---|---|---
![Image](https://github.com/user-attachments/assets/4ffb51d7-da1f-4746-ba79-5cd74768fc8c) | ![Image](https://github.com/user-attachments/assets/3848f457-d93e-41f8-bfb5-b1b24396c19d) | ![Image](https://github.com/user-attachments/assets/b023dd84-dd91-472e-9c8e-c56dec7d25fb) | ![Image](https://github.com/user-attachments/assets/05bf79d2-ad27-40dc-8cb2-e014f8c04068) | ![Image](https://github.com/user-attachments/assets/9801de86-35ad-46d2-885e-d20fe67dcea2)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.73.86 Chromium: 131.0.6778.39 (Official Build) (64-bit)
-- | --
Revision | 52163bcf4e40f27ddb76ffa79c90a8833084a9bd
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from [brave/brave-core#25931](https://github.com/brave/brave-core/pull/25931)
- Verified query input in non-English languages produce response in the same language
- Verified when input is less than 3 words, Leo fallback to system language for response
 
https://github.com/user-attachments/assets/9d63288d-0b17-4b52-af8e-b347630ec8cc

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `iPhone 14`using version(s):
```
Device/OS: iPhone 14 / iOS 17.7.1
Brave build: 1.73 (89)
BraveCore: 1.73.89 (131.0.6778.69)
```
---------------------------
<details>
<summary> Language/Region set to en_US </summary>

**STEPS:**
1. Set device language/region to en_US
2. Launch Brave 
3. Open `Leo`
4. Type a query:
- de_DE `var der et mordforsøg mod Donald Trump?`
- it_IT `c'è stato un tentativo di omicidio contro Donald Trump?`
- es_ES `¿Hubo un intento de asesinato contra Donald Trump?`
- fr_FR `y a-t-il eu une nouveau tentative d'assassinat contre Donald Trump ?`
- en_US `was there an assassination attempt against Donald Trump?`
5. *Verify response*


**ACTUAL RESULTS:**
- Verified that if device language/region is set to `en_US`, then Leo's response returned in the same language used to send a query if a query is longer than 3 words.
- Verified 

---------------------------

|Languge/Region is `en_US`|German|Italian|Spanish|French|English|
|:-:|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/eedb27f2-e986-486c-98c6-23dff2e067d1) | ![2](https://github.com/user-attachments/assets/a96a7c56-02ec-45e1-ac30-801ab0a5a29b) | ![3](https://github.com/user-attachments/assets/454a7965-8e8c-45c2-9a34-46f5b6aff562) | ![4](https://github.com/user-attachments/assets/e9e9232f-e712-475e-86cd-5a533c8b9dc6) | ![5](https://github.com/user-attachments/assets/06b3b8d1-5e99-4508-a737-c937c45f8405) | ![6](https://github.com/user-attachments/assets/5e8b401a-3ffe-43e2-8436-c51c22813003) |


</details>

<details>
<summary> Fresh profile - PASS </summary>

**STEPS:**
1. Launch Brave 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>
