### ISSUE TITLE
List of sites that work with Chrome and not with Brave

### ISSUE THREAD

**Issue by arisAlexis** [brave/brave-browser#4155]
Using latest Brave browser here is a list of sites not working for me with Brave while simultaneously work perfectly with Chrome. Maybe others can include other sites.

Mixcloud.com: Doesn't load with shields on
https://assassinscreed.ubisoft.com/game/en-us/home: completely fails to load with shields
Linkedin.com: Cookie consent is always shown at every login (with or without shields)

**Comment by Jezz1e** [comment]
dailymotion.com - site doesn't load unless you disable Shield

**Comment by capouch** [comment]
Running the latest beta 0.64.59 on Linux Slackware 14-current.  Lots and lots of issues, some of them show-stopping:

* Facebook feed now only shows 3-4 items, you have to click "More" and then it quickly renders some posts and just as quickly some of the content disappears.  You get 3-4 more items, then have to click again and the same thing.  Works fine on Chrome.

* Weather Underground basically the majority of their graphical icons (e.g. favorite cities, daily forecast icons, etc.) will not load when you log in, but render fine (along with annoying ads) if you do not.  Works fine on Chrome.

* Showstopper: Just added an image to a huge album in Google photos web.  Somehow under the hood clicks were made I did not do, and when I hit "Save" to add the image, ALL OTHER IMAGES IN THE ALBUM WERE DELETED.

* My banking application has a login screen that brings up a secondary login screen.  I put my username in the first one, click "Log on" and then the same screen re-renders with the username field now blank again.  Over and over.  Works fine on Chrome.

I'm getting to the point where I'm going to have to bail.  I have to run Chrome for part of the day to do my online banking, and after losing 300+ images in Google Photos I'm facing hours of recovery.

**Comment by capouch** [comment]
Update: As of 0.64.64, the Facebook problem is fixed.  Weather Underground still fails to render after login, but works fine without it.  Google Photos issue was found to belong to Google, not Brave.  Bank application hasn't ever worked on Brave; both Wunderground and the bank app work great in Chrome.

**Comment by ryanbr** [comment]
Investigated Weather Underground @capouch  can you re-test with device recognition 3rd-party/ device recognition allowed? I managed to get the map working when adjusting this.

**Comment by capouch** [comment]
@ryanbr Yes, it does work that way, thank you!!

**Comment by ryanbr** [comment]
I cant really fix the banking issues/or 'showstopper' for obvious privacy reasons,. no issues with facebook on my initial test

**Comment by capouch** [comment]
The Weather Underground issue is back--with a vengance--as of 0.66.94.  Same basic idea--if I log on, the site goes very strange.  It used to just not display my "favorite cities" after I logged in.  Then, after @ryanbr notified me, the issue was fixed.  For a while.  Now after posting the page contents, first the "favorites" across the top of the page disappears, then the whole page goes white.  Very frustrating.

**Comment by ryanbr** [comment]
url link to the issue?

**Comment by capouch** [comment]
[https://www.wunderground.com/weather/us/in/monon/40.87%2C-86.88](url) is the link to my "home page."  But the issue only occurs when I log in, and so w/o an account I don't know how you'd test it.

**Comment by ryanbr** [comment]
does the issue occur with sheilds off?

**Comment by capouch** [comment]
Dammit, no.  I turned shields off once upon a time for this site, but they were on again, and disabling them fixed the issue.  So sorry for the noise.

**Comment by tserkowski** [comment]
Another https://www.wunderground.com/ glitch:
MacBook running a fully patched version of Catalina.
The problem I have is the "Log In" button at the top right of the page, isn't a clickable item.  To login, I had to click on the gear icon then go to more options to get a login screen.
Comparing Brave to Chrome, I see:
"Log in | Join <gear>" in Chrome
"Log in | ..... <gear>" in Brave
Hovering over the "Log in" in Brave, the cursor never changed from a arrow to finger.  Hovering over the "....", the cursor changed to a text entry "I-beam", but it did change to a finger when over the gear.

**Comment by bsclifton** [comment]
Closing as this is a bit un-actionable as-is. If you run into specific websites having problems, let's open a new issue or report on Community 😄 Thanks!
