### ISSUE TITLE
[Follow up to #25604] Improve VPN server selection when `Automatic` is disabled, but `specific` region is not selected manually

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#41557]
### Description

Follow-up to #25604.

### Steps to reproduce

1. Launch Brave
2. Purchase and enable `VPN`
3. Go to the `Server selection` screen > *Confirm that `Automatic` is selected by default*
4. Turn off the `Automatic` toggle switch
5. Close the `Server selection` screen
6. Return to the `Server selection` screen again > *Observe that `Automatic` is still selected.*

### Actual result

Improve VPN server selection when `Automatic` is disabled, but the `specific` region is not selected manually. 

Users may be confused as to why `Automatic` is selected again since they just disabled it, and a `specific` country was shown as `selected` at that time.

----------------------

https://github.com/user-attachments/assets/a0a9cdcb-34b6-436c-9f09-88c1ba5770a9

### Expected result

`Automatic` must not be selected again after a user disabled it, but doesn't select a specific region, since it is already shown as a `selected` option.

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.72.66 
Chromium: 130.0.6723.31 (Official Build) canary (64-bit) 

### Device

- Brand/model: Pixel 7
- Android version: 15

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.72.88` or higher for `1.72.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Galaxy Z Fold 6` using version(s):
```
Device/OS: Galaxy Z Fold 6 / q6quew-user 14 UP1A.231005.007 release-keys
Brave build: 1.72.90 
Chromium: 130.0.6723.70 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41557#issue-2579558959
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Optimal` server is selected automatically after the `Automatic` toggle switch is OFF.

---------------------------

https://github.com/user-attachments/assets/6c48f4ca-1c00-49f4-a5a0-ba4d067aafa2
