### ISSUE TITLE
"Speed" section in Settings from Chromium still visible when searched

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#41565]
### Description

We have hidden the "speed" section in `Settings --> Performance` so that it is not visible when looking through `Settings`. However, if you search for it, it still shows up:

![Image](https://github.com/user-attachments/assets/78b54288-ce1a-48bc-ba2f-2ed6f7f9a118)

We should ensure that this (and any other) hidden sections do not appear in Brave, even when searched. 

### Steps to reproduce

1. Search "speed" in `Settings`
2. 
3. 

### Actual result

Hidden "Speed" section appears

### Expected result

Section should remain hidden

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

v1.70.126

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Internal conversation here:
https://bravesoftware.slack.com/archives/CKNHM4RTK/p1728600038306029

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.74.11 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | c777fe11bc7afc00156e58af64a6a5bb9559da7d
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

Verified the issue using STR from https://github.com/brave/brave-browser/issues/41565#issue-2580090490

Confirmed `Speed` setting is no longer visible when searched in the `brave://settings`


example | example 
----- | ------
![Image](https://github.com/user-attachments/assets/45a2f9d4-143f-4a76-a049-57f9677e1047)|![Image](https://github.com/user-attachments/assets/c95f9f91-701e-4075-a2fd-b92f7533ee20)
