### ISSUE TITLE
Some users cannot scroll on the tabs bar on iOS

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#41562]
### Description

Users are reporting that when trying to swipe/scroll using the tab strip (not tab picker) on iOS devices does not work. When attempting to do so, the strip will jump back to the tab currently in focus and prevent you from seeing tabs further down the strip. 

A Community user has shared a video of the behavior:
https://youtu.be/0B4T7qCwWZ8

The user who originally wrote the report states that this has been happening for some number of months for them.

### Steps to reproduce

1. Launch Brave on iOS
2. Open several tabs such that you need to scroll down the strip to view them all
3. Observe the tab strip jumping back to the in-focus tabs position

### Actual result

Tab strip will not properly scroll down the line of tabs

### Expected result

Tab strip should scroll responsively to the position the user desires.

### Reproduces how often

Easily reproduced

### Brave version

Version 1.69.1 (171)

### Device/iOS version

iPadOS 18+
Reported devices:
iPhone 13
iPad mini 5

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

Original user report:
https://community.brave.com/t/scrolling-through-tabs-is-broken/571045

**Comment by andyk** [comment]
Been noticing this behavior for weeks (maybe months?) too. Using iOS 18.1.1 (22B91) now, iPhone 14 Pro. Not sure if this is the right place to vote for issues (if not, feel free to delete this comment or I can)

**Comment by Rooster13** [comment]
Started noticing this on iPadOS recently too. I don’t use the device as frequently so it’s possible this has been happening for a while. Updated to iPadOS 18.2 last night. Tried crashing and restarting the app, tried rebooting the device.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.2` using version `1.75 (142)`

- Verified the Steps to Reproduce in the issue:
   - Ensured tabs in tabs bar are clickable and moveable.
   - Tested in both orientations
   - Tested using Top Bar and Bottom Bar.

**Comment by hffvld** [comment]
Verified on `iPad Mini (6th gen)` using version(s):
```
Device/OS: iPad Mini (6th gen) / iPadOS 18.2.1
Brave build: 1.75 (175)
BraveCore: 1.75.175 (133.0.6943.54)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41562#issue-2579937349
2. *Verify*

**ACTUAL RESULTS:**
- Verified that scrolling tabs works as expected.
- Verified that moving active tab works as expected.

---------------------------

https://github.com/user-attachments/assets/2cef644b-681d-416b-b51d-ba2786a5da80
