### ISSUE TITLE
[Wallet/iOS] Transaction Status will be dismissed automatically after tx gets confirmed

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#41563]
### Description

Transaction Status will be dismissed automatically after tx gets confirmed

### Steps to reproduce

1. Open wallet
2. make a send or swap tx 
3. confirm the tx

### Actual result

tx starts to showing the loader and the whole screen will get dismissed 

### Expected result

screen should stay with tx status displayed until user closes the screen.

### Reproduces how often

Easily reproduced

### Brave version

all

### Device/iOS version

iOS 18

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.70.127` or higher for `1.70.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.0` using version `1.70 (127)`

Test Steps: 

1. open wallet
2. make a send or swap tokens
3. confirm the txn

- Ensured screen stays with the transaction status until transaction is completed and user can close it. 

example | example | example | example | example
---|---|---|---|---
![Image](https://github.com/user-attachments/assets/f80e44e3-1614-43a3-af70-cfcb6d5625ca) | ![Image](https://github.com/user-attachments/assets/e18ff046-33ff-4180-9e15-6a3b5f8ffffa) | ![Image](https://github.com/user-attachments/assets/76531d4d-d517-41d6-bff9-f85189b93e84) | ![Image](https://github.com/user-attachments/assets/f038b682-c88d-4e33-8774-d6c4a32927d3) | ![Image](https://github.com/user-attachments/assets/10ccc347-cca8-4bd1-b743-08da4e7d3422)
