### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by dero** [brave/brave-browser#41568]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.70.123 Chromium: 129.0.6668.89
Operating System: Android 10

URL (if applicable) where crash occurred: google.com

Can you reproduce this crash?

Yes.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Tap the search input field on google.com.
2. Input the query and submit.
3. Tap the search input again, app crashes.

Additional context: I believe the fact that I'm using 1password to suggest credentials system wide may be having an impact here.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/f0722200-1893-b30c-0000-000000000000

**Comment by iefremov** [comment]
it should be fixed in https://github.com/brave/brave-browser/issues/41254
pls try updating the app
