### ISSUE TITLE
change location of "Inactive tabs appearance" setting and add separator

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#41576]
### Description

Per discussion via https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1728568063554079:

- We should move "Inactive tabs appearance" to the bottom of the "Tabs" section of brave://settings/appearance
- Ensure there's a separator between "Show memory usage on tab hover preview card" and "Inactive tabs appearance" that is visible on both light and dark theme

### Steps to reproduce

1. Using 1.73.3 or higher, visit brave://settings/appearance
2. Look at "Tabs" section

### Actual result

Dark | Light
--- | ---
![Image](https://github.com/user-attachments/assets/fb806461-2ce0-4552-93a5-3b93c60f5caf) | ![Image](https://github.com/user-attachments/assets/c684b9f1-a203-4171-8483-c0d0bd28c21a)

### Expected result

- Move "Inactive tabs appearance" to the bottom of the "Tabs" section of brave://settings/appearance
- Ensure there's a separator between "Show memory usage on tab hover preview card" and "Inactive tabs appearance" that is visible on both light and dark theme

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.73.5 Chromium: 130.0.6723.31 (Official Build) nightly (x86_64)
-- | --
Revision | 2fa08a74a31815d19960daea47ab1eaa9f28dc87
OS | macOS Version 14.7 (Build 23H124)
```

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @emerick

**Comment by LaurenWags** [comment]
Requires 1.71.113 or higher for verification 👍🏻

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.71.113 Chromium: 130.0.6723.58 (Official Build) (64-bit)
-- | --
Revision | 3ee74228044546a84c661332ddb441a7a68108fa
OS | Windows 10 Version 22H2 (Build 19045.5011)
```
