### ISSUE TITLE
Brave not available for Ubuntu 19.04 "Disco Dingo"

### ISSUE THREAD

**Issue by ddrager** [brave/brave-browser#4157]
Looks like the release channel for Ubuntu 19.04 "Disco Dingo" has not been made available yet. Disco dingo was released today.

Response from: https://brave-browser-apt-dev.s3.brave.com/dists/disco/InRelease

(or any release channel)

```<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>519C0EAC8C45CB9E</RequestId><HostId>PeawIjhI2HZWdcJg+Vf8nB/AVs1cEEd2BjjjFnIyXf/qUWZOQjCICi7365BCMomno/b6HTz0YPU=</HostId></Error>```

**Comment by fra98** [comment]
A workaround is to change the source in software & Update > Other Software, edit the brave-browser config and put "cosmic" instead of "disco" and then install it normally through apt.
This will work until they update the repository

**Comment by rebron** [comment]
Closing. See workaround above.

**Comment by ddrager** [comment]
With all due respect, this needs to be re-opened and fixed, not with a workaround. The install instructions on the [Brave download page](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux) return an error.

**Comment by ManuelTS** [comment]
Jep, I have a long script installing all the files and brave was the only one which failed to install. As already mentioned, this URL: 
https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux
only creates an unsinged ppa entry, which is useless.

**Comment by rebron** [comment]
@ddrager tracking down a better response for you

**Comment by netroby** [comment]
+1 19.04 need your support

**Comment by srirambv** [comment]
cc: @mbacchi @mihaiplesa 

+1 from @ReaperOfSouls1909 via #4181

**Comment by ddrager** [comment]
Thank you @rebron, appreciate it greatly for the good of the project! :)

**Comment by rebron** [comment]
Closing. Disco suite added and working for release/beta/dev channels (nightly later today). ping again if that's not the case.

**Comment by srirambv** [comment]
Verification passed on Ubuntu 19.04
![image](https://user-images.githubusercontent.com/17010094/56577627-6dea8b00-6599-11e9-804b-d6900c22e7bd.png)
