### ISSUE TITLE
Adjust create wallet account ui

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#41573]
For FIL, BTC and ZEC should see separate items on first screen when creating/importing/hw accounts
![Image](https://github.com/user-attachments/assets/3077aab5-bf6b-437c-b27a-91e5314dc4f3)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.3 Chromium: 131.0.6778.39 (Official Build) beta (64-bit)
-- | --
Revision | 0ce9628041e549979e5c522f7ec10ee1f5470182
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from [brave/brave-core#25948](https://github.com/brave/brave-core/pull/25948)
- Verified `Create Account`, `Import Account` & `Create Hardware Account` works as expected

https://github.com/user-attachments/assets/768c2684-9f72-42e7-98d2-8251fa9d0e8d

**Comment by srirambv** [comment]
Removing Android label as Ledger wallet isn't supported on mobile.
