### ISSUE TITLE
Enable BTC Ledger feature by default

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#41574]

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.5 Chromium: 131.0.6778.69 (Official Build) beta (64-bit)
-- | --
Revision | fbd7c390a7daa54f1aac2c769076d3fecf7c7fc7
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from [brave/brave-core#26060](https://github.com/brave/brave-core/pull/26060)
- Verified BTC Ledger support is enabled by default
- Verified BTC Ledger option is shown during Wallet onboarding
- Verified BTC Ledger option is shown on Connect hardware wallet 
- Verified BTC Testnet on Ledger is only shown when the network is enabled in settings
- Verified able to successfully import BTC Ledger accounts
- Encountered [#42336](https://github.com/brave/brave-browser/issues/42336)

https://github.com/user-attachments/assets/00f9347c-816d-4118-9c04-e9706aceea1e
