### ISSUE TITLE
[Follow up to #36277] `VPN Region` title and `City name`/`Optimal` strings are missing from `Hamburger menu`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#41591]
### Description

Follow-up to #36277.

### Steps to reproduce

1. Launch Brave
2. Enable `VPN`
3. Open `Hamburger menu` > *Observe*

### Actual result

`VPN Region` title and `City name`/`Optimal` strings are missing from the `Hamburger menu`.

--------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/c68c97cf-dd64-42f9-b9e5-9089fa90f39c) | ![2](https://github.com/user-attachments/assets/91c30ee3-27ec-49f6-ae1c-0bab72fedcd4) | ![3](https://github.com/user-attachments/assets/b9045614-7a38-4647-bb3e-3e67da71392a) |
| ![1](https://github.com/user-attachments/assets/77f73fac-5f4c-4afb-b8af-beb7075390e9) | ![2](https://github.com/user-attachments/assets/21a4f975-0fd4-4a90-84c4-e513299e09eb) | ![3](https://github.com/user-attachments/assets/b4deab57-c904-471d-bf2b-0d5ac16a92ad) |

### Expected result

According to Figma [design](https://www.figma.com/design/J4LKBMftiWhqromRWfUQLG/VPN-flows?node-id=21-17633&node-type=frame&t=4GnUlUg083vUsFFp-0), `VPN Region` title and `City name`/`Optimal` strings must be shown in `Hamburger menu`.

------------------

|1|
|:-:|
| ![1](https://github.com/user-attachments/assets/adde2730-84fb-4176-9ee1-fe41bb1b5dc6) |

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.71.112
Chromium: 130.0.6723.44 (Official Build) (64-bit) 

### Device

- Brand/Model: ANY
- Android version: ANY

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @deeppandya

**Comment by deeppandya** [comment]
@aguscruiz 
![Image](https://github.com/user-attachments/assets/d07685c6-ba8e-4163-b599-f3b120f1b6b7)

**Comment by aguscruiz** [comment]
Looks great!

**Comment by kjozwiak** [comment]
The above requires `1.72.83` or higher for `1.72.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using the following version(s):

```
Brave	1.72.90 Chromium: 130.0.6723.70 (Official Build) beta (64-bit) 
Revision	5f14a2225ebf4fcd654e064bde93e77fcc5d8f39
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

* Ensured that `Optimal` strings are shown for the VPN in the hamburger menu.
* Ensured that changing server to another region will include the `Optimal` for optimal setting.
* Ensured that selecting a specific a specific city/server in a region will display the appropriate strings in menu (ex: CA - Toronto).
* Ensured that there are no issues displaying strings after VPN resumes after pausing. 

`example: default for US region` | `example: Changing to Canada - Toronto server` | `example: Notifications tray`
---|---|---
![Image](https://github.com/user-attachments/assets/fcebf5cc-5304-4a0f-977d-d7ca7a7498f5) | ![Image](https://github.com/user-attachments/assets/d8bbc239-9dcc-4131-8075-6531ed02e4e8) | ![Image](https://github.com/user-attachments/assets/94877e67-8895-4275-8b25-afeaf77b7625)
