### ISSUE TITLE
[Follow up to #36277] Wrong title is shown on `country` screen: shown `Location` instead of `<Country name> server`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#41594]
### Description

Follow-up to #36277.

### Steps to reproduce

1. Launch Brave
2. Enable `VPN`
3. Open `Hamburger menu`
4. Turn off the `Automatic` toggle switch if it is ON
5. Tap on any available country > *Observe*

### Actual result

The wrong title is shown on the `country` screen: shown `Location` instead of `<Country name> server`.

------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/cfa06a10-1914-4bfb-9dfc-aed78abc30bc) | ![2](https://github.com/user-attachments/assets/8145e86c-479e-40f9-b67d-153316b93e94) |

### Expected result

According to Figma [design](https://www.figma.com/design/J4LKBMftiWhqromRWfUQLG/VPN-flows?node-id=21-17633&node-type=frame&t=4GnUlUg083vUsFFp-0), the title must say `<Country name> server`.

-------------------

|1|
|:-:|
| ![1](https://github.com/user-attachments/assets/2f8eb712-5ca1-4998-ab7b-77206d27c688) |

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.71.112
Chromium: 130.0.6723.44 (Official Build) (64-bit) 

### Device

- Brand/Model: ANY
- Android version: ANY

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @deeppandya

**Comment by kjozwiak** [comment]
The above requires `1.72.83` or higher for `1.72.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Galaxy Z Fold 6` using version(s):
```
Device/OS: Galaxy Z Fold 6 / q6quew-user 14 UP1A.231005.007 release-keys
Brave build: 1.72.90 
Chromium: 130.0.6723.70 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41594#issue-2582327217
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the title on the country page says <Country name> server. For example, for the USA it said "USA server" and for Canada said "Canada server"

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/492910cf-fe3c-4145-881b-648b4b59b754) | ![2](https://github.com/user-attachments/assets/86de71cb-0851-4746-8697-462e404998f3) |
