### ISSUE TITLE
[Follow up to #36277] Wrong title is shown on `server selection` screen: shown `Location` instead of `Server region`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#41593]
### Description

Follow-up to #36277.

### Steps to reproduce

1. Launch Brave
2. Enable `VPN`
3. Open `Hamburger menu`
4. Tap `country` to open `server selection` screen > *Observe*

### Actual result

The wrong title is shown on the `server selection` screen: shown `Location` instead of `Server region`.

------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/04a1c15d-bb91-4357-b408-7f8d9e81151b) | ![2](https://github.com/user-attachments/assets/3bca067a-7388-449c-a420-ca887da2184b) |

### Expected result

According to Figma [design](https://www.figma.com/design/J4LKBMftiWhqromRWfUQLG/VPN-flows?node-id=21-17633&node-type=frame&t=4GnUlUg083vUsFFp-0), the title must say `Server region`.

---------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/e7d30cce-a17d-433f-bfc8-850ea7b671c5) | ![2](https://github.com/user-attachments/assets/3345a37f-c62f-498c-b52c-2af11f42871e) |

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.71.112
Chromium: 130.0.6723.44 (Official Build) (64-bit) 

### Device

- Brand/Model: ANY
- Android version: ANY

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @deeppandya

**Comment by kjozwiak** [comment]
The above requires `1.72.83` or higher for `1.72.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Galaxy Z Fold 6` using version(s):
```
Device/OS: Galaxy Z Fold 6 / q6quew-user 14 UP1A.231005.007 release-keys
Brave build: 1.72.90 
Chromium: 130.0.6723.70 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41593#issue-2582317843
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the title on the country selection page says `Server region`.

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/20c1416e-d51d-42ca-bed1-41f4a6ea33bf) | ![2](https://github.com/user-attachments/assets/7ff5c5f1-1f35-4cda-8a3b-bf8ecb2ee49f) |
