### ISSUE TITLE
Ironic. Dump Google products like Chrome but install Brave from Google Play Store in 2024-25

### ISSUE THREAD

**Issue by varnit-nigam** [brave/brave-browser#41599]
### Description

Ironic. Dump Google products like Chrome but install Brave from Google Play Store. 

Other browsers wanting us to dump Google Chrome also knows some have dumped or aren't using Google other products like Google Play Store but not Brave in all these years.

And why bottom navigation bar and bottom URL bar is beautiful in this image and possible but not in Android version I'm using or is this what you see is what you don't get?

Ironic.

![Image](https://github.com/user-attachments/assets/6d2a926b-2874-418a-a7a6-8a48b533fe3b)
![Image](https://github.com/user-attachments/assets/7c7e69bd-fef7-4376-9685-83ea6f435811)

![Image](https://github.com/user-attachments/assets/9ed6c294-ce5b-4fdc-93b0-852eac9fe261)
![Image](https://github.com/user-attachments/assets/d8f697fa-7c51-4d5b-8a4c-14ac76704272)

![Image](https://github.com/user-attachments/assets/ad648031-594a-4683-92ea-a52de07c68a7)

### Steps to reproduce

Please read above. 

### Actual result

Checked your website for a change.

### Expected result

Just shocked.

### Reproduces how often

Easily reproduced

### Brave version

1.70.123

### Device

- Brand/model: Realme, Xiaomi and OnePlus 
- Android version: Android 14

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [x] in the latest version of Chrome

### Miscellaneous information

Just read above.

**Comment by jonathansampson** [comment]
Thank you for your feedback. While we encourage moving away from Google, we use the Play Store to reach more Android users efficiently. We do offer alternative installation methods for those who prefer them. 

Regarding the UI differences you noticed, I've messaged our team to take a closer look at the screenshots, and see what needs to be done from our end (e.g., updating the screenshots on the Google Play Store).

We appreciate your input and are committed to improving Brave. Let us know if you have any other questions.

**Comment by bsclifton** [comment]
Bottom toolbar is tracked with https://github.com/brave/brave-browser/issues/7356

Thanks for the other feedback (RE: Google Play Store). It has been shared with the appropriate folks
