### ISSUE TITLE
[Follow up to #36277] The names `United States` and `USA` are used at the same time

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#41592]
### Description

Follow-up to #36277.

### Steps to reproduce

1. Make sure, your IP/location is in the `US`
2. Launch Brave
3. Enable `VPN`
4. Open `Hamburger menu` > *Observe `United States` is shown*
5. Go to the server selection page > Turn off `Automatic` toggle switch
6. Scroll down > *Observe `USA` is shown*
7. Tap on `USA` > Tap `Optimal` or any available city
8. Open `Hamburger menu` > *Observe `USA` is shown*

### Actual result

The names `United States` and `USA` are used at the same time.

----------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/a6d3d0e4-fc52-4c8d-a2ba-3c3c4bc839f1) | ![2](https://github.com/user-attachments/assets/af72112a-ab58-464f-93d9-c9eb43e7df57) | ![3](https://github.com/user-attachments/assets/d5359dfa-6df0-4a8b-bd43-36e1a67705dd) |
| ![1](https://github.com/user-attachments/assets/ee01ff20-01c5-48e7-beaf-b5ae44bad376) | ![2](https://github.com/user-attachments/assets/c168e14d-53ce-4873-bbe0-8709a27a1042) | ![3](https://github.com/user-attachments/assets/bedcd85d-8daa-4f7f-b68b-92c531015bfd) |

### Expected result

We must use only one country name `United States` or `USA`.

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.71.112
Chromium: 130.0.6723.44 (Official Build) (64-bit) 

### Device

- Brand/Model: ANY
- Android version: ANY

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @deeppandya

**Comment by deeppandya** [comment]
@hffvld based on the change here : https://github.com/brave/brave-core/pull/26005, This issue would be irrelevant.

**Comment by kjozwiak** [comment]
The above requires `1.72.83` or higher for `1.72.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Galaxy Z Fold 6` using version(s):
```
Device/OS: Galaxy Z Fold 6 / q6quew-user 14 UP1A.231005.007 release-keys
Brave build: 1.72.90 
Chromium: 130.0.6723.70 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41592#issue-2582309524
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `United States` name is not used in the `Hamburger menu` and on the `server selection` page.
- Verified that `US - optimal`/`US - <city name>` is used in the `Hamburger menu`.
- Verified that the `USA` name is used on the `server selection` page.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/6200c18a-1142-4b67-8b93-23eff26b491c) | ![2](https://github.com/user-attachments/assets/bbf2efb5-3539-420f-a52b-313a43934f0a) | ![3](https://github.com/user-attachments/assets/d17b4ee2-9209-400b-a86b-6fae4601d8bb) |
