### ISSUE TITLE
Add additional logging to help diagnose issues when downloading catalogs

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#4160]
Add additional logging to help diagnose issues when downloading catalogs and fetch the latest catalog every 15 minutes instead of every 2 hours if the `--brave-ads-debug` command-line arg is passed

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.65.97 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

1. Launched clean profile with `--enable-logging=stderr --log-level=2 --vmodule=brave_ads=3 --brave-ads-debug`.
2. Enabled Rewards.
3. Saw `Start collecting activity in 962 seconds` in terminal (roughly 16 minutes).
4. Verified 962 seconds later a new catalog was pulled (verified terminal messaging).
5. Verified another `Start collecting activity` message was displayed in the terminal again - this time for 953 seconds which is just under 16 minutes.
