### ISSUE TITLE
Update `adblock-rust` to `v0.9.2`

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#41608]
Brave Browser should update adblock-rust to `v0.9.2` from `v0.9.0`, including the following changes:
- `v0.9.1`: reduce memory usage for regex network filters
    - This should decrease Brave Browser's runtime memory usage
- `v0.9.2`: properly ignore cosmetic filters with AdGuard location regex syntax
    - This should allow Brave Browser to properly ignore filters of the form `/…/##…`. These didn't cause much of a problem for Desktop/Android other than consuming slightly more memory to store an invalid internal representation, but on iOS, these filters could prevent the filter list from being converted to content-blocking syntax.

**Comment by LaurenWags** [comment]
Updated to `release-notes/exclude` per discussion with @rebron @kjozwiak
