### ISSUE TITLE
Change sync server to self-hosted sync server on mobile devices

### ISSUE THREAD

**Issue by retalieight** [brave/brave-browser#41611]
### Platforms

all

### Description

It would be nice if we could self-host our own sync server and configure it in the Brave mobile apps. Some of us like to self-host and keep all of our data to ourselves. Would it be possible to implement?

**Comment by bsclifton** [comment]
Hi there - yes, this is possible. 
On Desktop, you can use group policy to change the URL (see https://github.com/brave/brave-core/pull/25498).
We're also adding this to the UI so it's easier to customize. See https://github.com/brave/brave-core/pull/25484

You'll want to subscribe to https://github.com/brave/brave-browser/issues/12314 for updates. Thanks!
