### ISSUE TITLE
Sync device is duplicated when Google Account cookies are deleted

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#41615]
### Description

This issue is derived from https://github.com/brave/brave-browser/issues/41196 to be specified at the PR. I need this to avoid the case when https://github.com/brave/brave-browser/issues/41196 will be closed but not all the causes would be fixed.

When Google Account cookies are deleted, `Sync Client ID` gets regenerated and the device is duplicated on other synced device list.

The call stack of what had happened:

```
#2 0x61f515dba9d4 syncer::KeepAccountKeyedPrefValuesOnlyForUsers()
#3 0x61f515db915e syncer::SyncTransportDataPrefs::KeepAccountSettingsPrefsOnlyForUsers()
#4 0x61f515e30806 syncer::SyncUserSettingsImpl::KeepAccountSettingsPrefsOnlyForUsers()
#5 0x61f515ddb97b syncer::(anonymous namespace)::MaybeClearAccountKeyedPreferences()
#6 0x61f515ddbaa8 syncer::SyncServiceImpl::OnAccountsInCookieUpdatedWithCallback()
#7 0x61f515ddbc8b syncer::SyncServiceImpl::OnAccountsInCookieUpdated()
#8 0x61f5139a4d53 signin::IdentityManager::OnGaiaAccountsInCookieUpdated()
#9 0x61f5139c69f6 base::RepeatingCallback<>::Run()
#10 0x61f5139c7444 GaiaCookieManagerService::OnListAccountsSuccess()
#11 0x7dc343c10435 GaiaAuthFetcher::OnListAccountsFetched()
#12 0x7dc343c0d34b GaiaAuthFetcher::OnURLLoadComplete()
#13 0x7dc343b894bc base::OnceCallback<>::Run()
#14 0x7dc343b89ce9 network::(anonymous namespace)::SimpleURLLoaderImpl::FinishWithResult()
#15 0x7dc343b89e6d network::(anonymous namespace)::SimpleURLLoaderImpl::MaybeComplete()
#16 0x7dc343b8533f network::(anonymous namespace)::SimpleURLLoaderImpl::OnComplete()
#17 0x7dc343bd133c network::mojom::URLLoaderClientStubDispatch::Accept()

#2 0x75e9eaf4ed9f GaiaAuthFetcher::CreateAndStartGaiaFetcher()
#3 0x75e9eaf50735 GaiaAuthFetcher::StartListAccounts()
#4 0x64f162015095 GaiaCookieManagerService::StartFetchingListAccounts()
#5 0x64f162016d8b base::internal::Invoker<>::RunOnce()
#6 0x64f161f74270 base::OnceCallback<>::Run()
#7 0x64f163df7627 WaitForNetworkCallbackHelperChrome::DelayNetworkCall()
#8 0x64f163d3f1e2 ChromeSigninClient::DelayNetworkCall()
#9 0x64f162011cb0 GaiaCookieManagerService::TriggerListAccounts()
#10 0x64f162012cc0 GaiaCookieManagerService::OnCookieChange()
#11 0x64f1620b2feb network::mojom::CookieChangeListenerStubDispatch::Accept()
```

### Steps to reproduce

I. Scenario with manual logout from GMail

1. Add devices A and B into the sync chain
2. On device B login into GMail
3. On device B logout from GMail
4. Restart browser on Device B
5. Unexpected device B is duplicated at A's list

II. Scenario with `Delete sites data` option
1. Add devices A and B into the sync chain
2. On device B login into GMail
3. On device B go to brave://settings/content/siteData and choose 
```
Delete data sites have saved to your device when you close all windows
Sites will probably work as you expect but won't remember you after you close all Brave windows
```
4. Restart browser on Device B
5. Unexpected device B is duplicated at A's list

### Actual result

Device is duplicated at A's list

### Expected result

Device is not duplicated at A's list

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

`1.72.0 Chromium: 130.0.6723.31 (Developer Build) (64-bit) ` 

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.71.116` or higher for `1.71.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.71.116 Chromium: 130.0.6723.58 (Official Build) (64-bit)
-- | --
Revision | 789393dd90da88a1f9abf5a7d05fd8ccff76afa2
OS | Windows 10 Version 22H2 (Build 19045.5011)
```
