### ISSUE TITLE
“libchromescreenai.so” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by paro-paro** [brave/brave-browser#41629]
### Description

Since yesterday I am getting a macos pop-up warning every time I open brave.

### Steps to reproduce

1. Open brave browser
2. 
3. 

### Actual result

![Image](https://github.com/user-attachments/assets/8009ca84-1150-4cf0-bcc2-c49fce810570)

### Expected result

Do not get any warning.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.126 Chromium: 129.0.6668.100 (Official Build) (arm64) 

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by helloromero** [comment]
+1

**Comment by rebron** [comment]
@paro-paro @helloromero Can you update to the latest 1.71.114 and let us know if you're still seeing the issue. 
Also, what version of macOS are you running? macOS 15 Sequoia?

**Comment by S30tt** [comment]
> [@paro-paro](https://github.com/paro-paro) [@helloromero](https://github.com/helloromero) Can you update to the latest 1.71.114 and let us know if you're still seeing the issue. Also, what version of macOS are you running? macOS 15 Sequoia?

I've got the exact same issue and have the latest version installed.  I am running Sonoma 14.7 (23H124).

![Image](https://github.com/user-attachments/assets/c698bb70-0b24-4f8a-a7cd-b1a746fe806b)

**Comment by S30tt** [comment]
I could bypass the warning by manually allowing the lib to run but this is not the way.

![Image](https://github.com/user-attachments/assets/2e84e864-d48d-459e-8a33-02923e5a535a)

**Comment by paro-paro** [comment]
Hi @rebron 

I am on macos sonoma 14.1.1 and now on the latest brave version 1.71.114 which no longer displays the warning. The file is still downloaded but I guess is all fine now.

**Comment by marijnbent** [comment]
I have the same issue on Chrome

**Comment by bsclifton** [comment]
This is something shipped with Chrome / Chromium. I wonder if there is something we need to disable (via args GN or similar) if we don't want to include it?

cc: @cdesouza-chromium @emerick @mkarolin

**Comment by jiripospisil** [comment]
Debian removes it. Brave should too.

https://salsa.debian.org/chromium-team/chromium/-/commit/ee2d7017ed0b99a27f5b763ee782fdd8a0999660

**Comment by bsclifton** [comment]
Looks like this is being tracked upstream with https://issues.chromium.org/issues/366284843 - which is a bit weird, since (for Chrome) the library should have the same signer as Chrome itself

**Comment by mherrmann** [comment]
It appears to be a Google component that is pulled in when the browser uses accessibility APIs. I get it when I turn on Speedreader. Redditors [report](https://www.reddit.com/r/macsysadmin/comments/1ei9kk8/comment/lgm9qxs/) getting it when using 1Password.

**Comment by luispuerto** [comment]
I think this is a wide issue related to chrome based browsers. I'm getting the same with Vivaldi last version in macOS 15.1. I got the option to throw it to the trash and there is…

**Comment by kjozwiak** [comment]
The above requires `1.74.21` or higher for `1.74.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Brave | 1.74.25 Chromium: 132.0.6834.33 (Official Build) beta (arm64)
-- | --
Revision | 041ffab11e000929213dcdae825dba438ff8a620
OS | macOS Version 14.6.1 (Build 23G93)


Couldn't reproduce the issue in `1.70.126 Chromium: 129.0.6668.100 (arm64)` or `1.71.114 Chromium: 130.0.6723.58 (arm64)` using STR from https://github.com/brave/brave-browser/issues/41877#issue-2613528829

<details>

![Image](https://github.com/user-attachments/assets/6074ca0f-537c-4be0-a714-a9981a6f3915)
</details>

- Installed 1.74.25
- launched Brave
- enabled Screen Reader 
- logged in 1Password 

- Confirmed no errors are shown upon starting Brave on macOS Sonoma 14.6.1.  
- Confirmed no `ScreenAI Library` component is shown.  

<details>

example | example
-----  | -----
![Image](https://github.com/user-attachments/assets/faa07a8f-372e-4f31-ac9d-9b901cc6cb2d)|![Image](https://github.com/user-attachments/assets/648d15e0-0d2f-412f-b655-b5b24fdc7f24)

</details>

**Comment by LaurenWags** [comment]
Removed `QA Pass-macOS-arm64` as this was uplifted. Requires `1.73.102` or higher for verification 👍🏻

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.73.102 Chromium: 131.0.6778.139 (Official Build) (x86_64)
-- | --
Revision | 6806ad35635fe0ddfd23411347211aa34c59a8d4
OS | macOS Version 14.7.2 (Build 23H311)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.73.102 Chromium: 131.0.6778.139 (Official Build) (arm64)
-- | --
Revision | 6806ad35635fe0ddfd23411347211aa34c59a8d4
OS | macOS Version 14.6.1 (Build 23G93)
```


1.  Installed 1.73.102
2.  launched Brave
3.  visited a website 
4.  enabled Screen Reader 
5.  logged in to 1Password 


  - Confirmed no errors are shown upon starting Brave on macOS Sonoma 14.6.1.  
  - Confirmed `ScreenAI Library` component is not shown.  
  
example | example | example 
-----  | ----- | ----
![Image](https://github.com/user-attachments/assets/343403ba-7ae2-4106-999b-2ec3f66c522a)|![Image](https://github.com/user-attachments/assets/90570b46-067f-412a-a78b-5748fd6bed01)|![Image](https://github.com/user-attachments/assets/08141d31-6efa-4d2d-b2dc-52c92e31dd9c)
