### ISSUE TITLE
LinkedIn posts are blocked by in-built adblocker

### ISSUE THREAD

**Issue by Vanekkk1** [brave/brave-browser#41623]
### Description

![Image](https://github.com/user-attachments/assets/396a016f-afba-4df1-b9af-52bdf7efa6dd)

The image above is how individual LinkedIn posts look like when I use Brave Browser on MacOs, when I disable the AdBlocker all works correctly, when I enable it, they do not render

### Steps to reproduce

1. Open https://www.linkedin.com/
2. Open and individual post with AdBlocker Enabled
3. 

### Actual result

![Image](https://github.com/user-attachments/assets/396a016f-afba-4df1-b9af-52bdf7efa6dd)

### Expected result

![Image](https://github.com/user-attachments/assets/c965e3fe-099e-4af1-b59d-74852978ee90)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.70.123 Chromium: 129.0.6668.89 (Official Build) (arm64) 

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by bsclifton** [comment]
cc: @ryanbr

**Comment by Vanekkk1** [comment]
using chrome already )

Regards,
Ivan Tryskyba

**Comment by ryanbr** [comment]
All good, it should safe to use Brave on LinkedIn. If you decide to try Brave. 

Thanks for the response
