### ISSUE TITLE
Bug with last update

### ISSUE THREAD

**Issue by nunezweb** [brave/brave-browser#41625]
### Description

Hi,

I've encountered this error after a recent browser update, but I do not use shadow DOM or attachShadow in my code. Everything was working fine in previous browser versions, but this started showing up after the update. It seems like something in the browser update might be affecting the way the shadow DOM is handled. I've also noticed that it started happening across different browsers after their auto-updates, though previously everything worked perfectly.

Do you know if anyone else has reported this issue? It seems related to changes in the browser's shadow DOM behavior, and I'd appreciate any insights.

poetry.js:134 NotSupportedError: Failed to execute 'attachShadow' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree.
    at Element.attachShadow (poetry.js:134:39731)
    at new D2 (poetry.js:148:2733)
    at fn (poetry.js:134:30163)
    at Re (poetry.js:134:35696)
    at poetry.js:134:34356
    at ZA.la (poetry.js:134:33825)
    at poetry.js:134:36228
    at ku (poetry.js:148:2376)

### Steps to reproduce

1. Browser: This issue occurs after updating to the latest browser version.
Development stack: Using React and Python with Flask
2. Occurs locally and in codespace.
3. Actual Result: After the latest browser update, the following error appears in the console:
4. poetry.js:134 NotSupportedError: Failed to execute 'attachShadow' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree.
    at Element.attachShadow (poetry.js:134:39731)
    at new D2 (poetry.js:148:2733)
    at fn (poetry.js:134:30163)
    at Re (poetry.js:134:35696)
    at poetry.js:134:34356
    at ZA.la (poetry.js:134:33825)
    at poetry.js:134:36228
    at ku (poetry.js:148:2376)

### Actual result

https://prnt.sc/8OCbYgOkgo1R

### Expected result

There shouldn't be any errors because the application has been tested in previous versions. I believe this might happen with any application, but I'm not entirely sure. I've asked some colleagues, but they haven't responded yet.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

[Versión 1.70.126 Chromium: 129.0.6668.100 (Build oficial) (64 bits)](https://brave.com/latest/)

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [x] in the latest version of Chrome

**Comment by nunezweb** [comment]
It happens with many websites:
https://prnt.sc/7uEvjLgCw4KX

**Comment by rebron** [comment]
cc: @ShivanKaul @ryanbr

**Comment by ShivanKaul** [comment]
What's a good test website?

**Comment by nunezweb** [comment]
> What's a good test website?

This error occurs with the latest update in all browsers that use Chromium. I tested it with Firefox, and it works correctly there.

firefox screenshot: https://prnt.sc/44eFpZTAWf7s

**Comment by ShivanKaul** [comment]
We need to know a website that we can try to reproduce the problem on.

**Comment by ShivanKaul** [comment]
If the website you're testing misbehaves on all Chromium browsers, I would suspect a website issue and not a browser issue.

**Comment by nunezweb** [comment]
> We need to know a website that we can try to reproduce the problem on.

I have checked again and the problem comes from this extension:

https://chromewebstore.google.com/detail/ruttl/doecfodblgfnjmmphbedjgllipnbgbld

It was the only one I missed when disabling extensions.

I'm going to report it so they can fix it.

Thanks for all!!
