### ISSUE TITLE
[Leo] - Slash tools in panel are not showing up

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#41635]
In Nightly, when I click the button for slash tools, the drop-up is not showing correctly.
Additionally, when typing `/` the same drop-up should appear, but it doesn't now.

**Drop up not showing**
https://github.com/user-attachments/assets/c68e385e-8bbb-4e54-b609-38cd7296552b

**Entering `/` should open the slash tools**
![Image](https://github.com/user-attachments/assets/54e97c58-b034-4898-90a6-806c5f99a7a6)

Nightly:
1.73.9 Chromium: 130.0.6723.44 (Official Build) nightly (arm64)

**Comment by rebron** [comment]
This is happening in 1.72.x in beta channel also.

**Comment by petemill** [comment]
Duplicate of https://github.com/brave/brave-browser/issues/42279
