### ISSUE TITLE
[iOS] - Requesting Speech Recognizer from a Website crashes

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#41639]
### Description

Requesting Media permissions for a website will crash the app

### Steps to reproduce

1. Visit: https://hayabusa.open2ch.net/test/read.cgi/livejupiter/1728956006/l10
2. Scroll down.
3. Tap the drop down and enable microphone
4. Tap on the microphone to record a message

https://github.com/user-attachments/assets/0b3b2666-941a-4f6c-bf84-95ad42578434

### Actual result

- Crashes

### Expected result

- Shouldn't Crash

### Reproduces how often

Easily reproduced

### Brave version

All

### Device/iOS version

All

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.71.117` or higher for `1.71.x` verification 👍 As mentioned via Slack, we'll need to be connected to a `Japan` VPN to get the website to load. Might need to try several severs before you find one that works with the website mentioned via https://github.com/brave/brave-browser/issues/41639#issue-2589087790.

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7
Brave build: 1.71 (118)
BraveCore: 1.71.118 (130.0.6723.70)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41639#issue-2589087790 and https://github.com/brave/brave-browser/issues/41639#issuecomment-2427309872
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Brave`is not crashing when granting `Microphone` permissions

---------------------------

https://github.com/user-attachments/assets/8526b652-6cae-4f38-bbca-a194ac56a01c
