### ISSUE TITLE
Use SimpleURLLoader instead of URLFetcher

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#4164]
## Description 

URLFetcher is going to be deprecated. We use it in bat_native_ads and bat_native_ledger. We should use SimpleURLLoader instead

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
@SergeyZhukovsky is this dupe of https://github.com/brave/brave-browser/issues/3501?

**Comment by NejcZdovc** [comment]
closing as dupe of #3501
