### ISSUE TITLE
Transaction Confirmed Screen Showing Incorrect Recipient for Swap and Bridge

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#41641]
### Description

The `Confirmed` transaction screen is showing the incorrect `recipient` label for `Swap` and `Bridge` transactions.

### Steps to reproduce

1. Open the `Wallet` and create a `Swap` or `Bridge` transaction
2. Wait for the `Transaction` to be confirmed
3. The `Confirmed` screen is showing the `Exchange` name instead of the `Receiving` address or name

### Actual result

![Image](https://github.com/user-attachments/assets/53573fa8-6d27-419a-9623-a13009b70186)

### Expected result

![Image](https://github.com/user-attachments/assets/d6f5b9ba-a9cc-4d3d-af70-b5eb52785290)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.72.77 Chromium: 130.0.6723.31 (Official Build) beta (arm64) 

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by LaurenWags** [comment]
Requires 1.72.84 or higher for verification 👍🏻

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.72.96 Chromium: 131.0.6778.24 (Official Build) beta (64-bit)
-- | --
Revision | 10f472615a5ea2cccb71ffc48639efbaef71b801
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from [brave/brave-core#26002](https://github.com/brave/brave-core/pull/26002)
- Verified for LiFi transactions shows correct recipient address on transaction submitted and confirmation screen

https://github.com/user-attachments/assets/0bab8faa-b060-4818-bce0-e3bad7fa715d
