### ISSUE TITLE
Desktop settings - Move styles to use Nala tokens

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#41655]
Move styles in settings pages that were hardcoded into using Nala tokens in several places.

Should resemble designs:
https://www.figma.com/design/IXNCYwXmMWaF6u7Pdv1pOW/Desktop-settings---Nala?node-id=476-20465&t=xbBtvK7BUeb8zQn2-1

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.74.8 Chromium: 131.0.6778.69 (Official Build) beta (64-bit)
-- | --
Revision | 0e56a6339728b1f1569eb3bdbe8261f2d5785d3b
OS | Windows 11 Version 23H2 (Build 22631.4460)
```

Installed 1.74.8
launched Brave


1.73.89 | 1.74.8
----- | ----

brave:/settings/braveContent
![Image](https://github.com/user-attachments/assets/12410711-1946-448d-aef0-6a4c8ede676b)|![Image](https://github.com/user-attachments/assets/bb6f9974-e37f-486b-a286-1d5c85e9ba11)
