### ISSUE TITLE
Fix Learn More URL for inactive tabs in brave://settings

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#41658]
### Description

We need to fix the Learn More URL for inactive tabs in brave://settings. It should be https://support.brave.com/hc/en-us/articles/13383683902733-How-do-I-use-the-Memory-Saver-feature-in-Brave.

**Comment by LaurenWags** [comment]
Requires 1.71.114 or higher for verification 👍🏻

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.71.114 Chromium: 130.0.6723.58 (Official Build) (64-bit)
-- | --
Revision | 89c4031c685a4296315a6f421f46275f0b72dd55
OS | Windows 10 Version 22H2 (Build 19045.5011)

```
Confirmed the "Learn more about inactive tabs" link directs to `https://support.brave.com/hc/en-us/articles/13383683902733-How-do-I-use-the-Memory-Saver-feature-in-Brave` as expected.
Confirmed clicking on the "Learn more about inactive tabs" link opened the link in a new tab.

Example | Example
--- | ---
![Image](https://github.com/user-attachments/assets/debb7573-9e09-47e7-bc61-ae16997043aa) | ![Image](https://github.com/user-attachments/assets/230cbafa-eb1c-493b-8e2a-7a295eed3e2e)
