### ISSUE TITLE
[iOS] - MessageHandlers don't exist immediately after deleting them

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#41653]
### Description

- For security reasons, we execute `delete window.webkit.messageHandlers` and then immediately WebKit would restore the original, so we could use it securely.
- On iOS 18, it seems it does NOT restore immediately anymore, but rather after some arbitrary time-frame.

Chrome does the same thing:
```javascript
 function sendWebKitMessage(handlerName, message) {
      try {
          // A web page can override `window.webkit` with any value. Deleting the
          // object ensures that original and working implementation of
          // window.webkit is restored.
          var oldWebkit = window.webkit;
          delete window['webkit'];
          window.webkit.messageHandlers[handlerName].postMessage(message);
          window.webkit = oldWebkit;
      }
      catch (err) {
          // TODO(crbug.com/40269960): Report this fatal error
      }
  }
```
and it's also broken.

### Steps to reproduce

1. Visit https://www.atgtickets.com/shows/cabaret/kit-kat-club-at-the-playhouse/calendar/
2. Page won't load

### Actual result

- Page doesn't load at all

### Expected result

- Page should load

### Reproduces how often

Easily reproduced

### Brave version

- All

### Device/iOS version

- All

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.71.116` or higher for `1.71.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.0` using version `1.71.118`

* Ensured that `https://www.atgtickets.com/shows/cabaret/kit-kat-club-at-the-playhouse/calendar/` without delay for new users.
* Ensured that web page loads without issue after upgrading app for existing users. 
* Ensured `https://www.atgtickets.com/shows/cabaret/kit-kat-club-at-the-playhouse/calendar/` loads in private tab. 

`example` | `example`
---|---
![Image](https://github.com/user-attachments/assets/d436779b-7d13-41ec-b2a5-bdaa9df41083) | ![Image](https://github.com/user-attachments/assets/b4ea6429-1b46-423e-96d7-74b01633151a)
