### ISSUE TITLE
Recipient not displayed for 0x Swaps

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#41672]
### Description

Recipient does not get displayed after completing a `0x` swap in the `Transaction Confirmed` panel.

### Steps to reproduce

1. Open the `Wallet` and create a swap using `0x`
2. Wait for the `Transaction` to be confirmed
3. Notice that the receive `Account` or `Address` is missing.

### Actual result

![Image](https://github.com/user-attachments/assets/58ab2061-3f78-4631-91cc-b268f73bf34d)

### Expected result

![Image](https://github.com/user-attachments/assets/4049bfdf-1ea7-4d5c-a55a-45ff5c5c9dfa)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.72.77 Chromium: 130.0.6723.31 (Official Build) beta (arm64)

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.72.85` or higher for `1.72.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.72.96 Chromium: 131.0.6778.24 (Official Build) beta (64-bit)
-- | --
Revision | 10f472615a5ea2cccb71ffc48639efbaef71b801
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from [brave/brave-core#26038](https://github.com/brave/brave-core/pull/26038)
- Verified 0x transactions shows Account name on Transaction Confirmation screen

https://github.com/user-attachments/assets/e0e877ce-4298-4fa1-8b88-5f022bd3ba0e
