### ISSUE TITLE
Shred button displayed unnecessarily on certain screens

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#41671]
### Description

Shred button displayed unnecessarily on certain screens

These include:

* Private Browsing opt in page
* Synced tabs from other devices screen

Private tab | Tabs from other devices
---|---
![Image](https://github.com/user-attachments/assets/aa33690e-ab0d-48f4-901c-dbf1536e7426) | ![Image](https://github.com/user-attachments/assets/ee9a103d-11df-41a9-aa48-7fb7aacb1199)

### Steps to reproduce

1. New install
2. Switch tabs to Private
3. In normal tab mode, switch to "Tabs from other devices" after connecting to Sync chain (enable Sync tabs)

### Actual result

* Shred button is shown on Private tab screen which is unnecessary because there is nothing to shred
* Shred button is shown on "Tabs from other devices" screen in tab view. Also unnecessary because shred button only affects tabs opened locally. 

### Expected result

Remove from these screens 

### Reproduces how often

Easily reproduced

### Brave version

1.71 (112)

### Device/iOS version

iPhone, iOS 18.0

### Affected browser versions

- [ ] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.71.117` or higher for `1.71.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18` using version `1.71.118`

* Ensured that Shred button is not displayed on private tab screen (no tabs)
* Ensured that Shred button is not displayed on `Tabs from Other Devices` screen.

`example` | `example` | `example`
---|---|---
![Image](https://github.com/user-attachments/assets/cf04e56f-8ca0-43f7-b8b9-37dab5c58616) | ![Image](https://github.com/user-attachments/assets/0f23c5f1-2786-4edf-a555-cc73490ccc54) | ![Image](https://github.com/user-attachments/assets/61a0491b-bc0e-4f53-bca3-d6f013d278a4)
![Image](https://github.com/user-attachments/assets/0b7805e9-6d24-40f8-b4f3-5d9370b865d9) | ![Image](https://github.com/user-attachments/assets/584fc95a-0e2c-4470-b632-d88b717fa814) | ![Image](https://github.com/user-attachments/assets/5deff31a-9f2d-44c1-92c9-c5c19dfe6c71)
