### ISSUE TITLE
Activity Missing in Android Wallet Navigation

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#41675]
### Description

The `Activity` tab is missing in the Wallet `Navigation`

### Steps to reproduce

1. Open the `Wallet` on your `Android` device
2. Activity is missing as an option in the `Navigation`

### Actual result

![Image](https://github.com/user-attachments/assets/d2b4fb6f-bc31-4a47-9bcc-13e8b622cdd0)

### Expected result

`Activity` should be an option in the Wallet `Navigation`

### Reproduces how often

Easily reproduced

### Brave version

1.72.77 Chromium: 130.0.6723.31

### Device

- Brand/model: 
- Android version: 

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by LaurenWags** [comment]
Requires 1.72.84 or higher for verification 👍🏻

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.72.85 x64 beta build
- Verified steps from [brave/brave-core#26044](https://github.com/brave/brave-core/pull/26044)
- Verified Activity tab is shown on wallet navigation

https://github.com/user-attachments/assets/3ad4dca9-b689-4fe9-8b7b-a75eff3de5ac
