### ISSUE TITLE
Favicons are too large and are being clipped in Rewards panel

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#4167]
Need to reduce scale so we aren't pixelating favicons and also remove the circle mask since Favicons must be square so we aren't clipping brands at the edges so severely. 

## Current
![Screen Shot on 2019-04-18 at 15:10:11](https://user-images.githubusercontent.com/29072694/56394458-4fc50980-61ec-11e9-988f-326f0969d47d.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.106 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2491 
![Screen Shot 2019-07-10 at 4 23 51 PM](https://user-images.githubusercontent.com/28145373/61002323-4ea90180-a32f-11e9-9a90-8fed847a9d80.png)
