### ISSUE TITLE
Add metrics for measuring NTT reach

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#41680]
The metrics will be similar to the existing NTT/creative metrics in the sense that we will have dynamic metric names, with one metric per campaign ID.

If you have Sponsored Images enabled, is your client aware of the campaign ID specified in the metric name?
`campaignId.<campaign ID here>.aware`

If you have Sponsored Images enabled, did you view a NTT creative associated with the campaign ID specified in the metric name?
`campaignId.<campaign ID here>.viewed`

Both metrics would have a single answer index of 1.

cc @lukaslevert @iambrianfung

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.74.5 Chromium: 131.0.6778.69 (Official Build) beta (64-bit)
-- | --
Revision | fbd7c390a7daa54f1aac2c769076d3fecf7c7fc7
OS | Windows 10 Version 22H2 (Build 19045.5011)
```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.74.5`

**Comment by GeetaSarvadnya** [comment]
@DJAndries I have verified the issue on `1.74.15` on Android, I am still seeing the same issue as https://github.com/brave/brave-browser/issues/41680#issuecomment-2485991087. 

I checked with @iambrianfung regarding the Android NTT campaign, he confirmed that the campaign is up on staging environment for India region. Also @aseren confirmed that `--use-dev-goupdater-url` is pointing to staging env.

**Comment by aseren** [comment]
hey @GeetaSarvadnya , here are steps to get staging NTT on Android:

- Install Brave Browser, but DON'T start it
- Turn off Wifi and mobile network
- Start Brave Browser
- Go to Setting -> Developer Options -> QA Preferences -> Command Line String
- Enter `--use-dev-goupdater-url` arg
- Restart the Brave Browser
- Turn on Wifi
- Staging component will be downloaded in a minute
