### ISSUE TITLE
[ads] Empty device id

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#41693]

**Comment by btlechowski** [comment]
Verified with

Brave | 1.74.13 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | 3cb237ea4b804e01c49a0a6d56f84b3c395a1d31
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/26215

<details>

Verified `Device ID` is defined

![Image](https://github.com/user-attachments/assets/d90660eb-c6bc-481a-9071-7428eedf800f)

</details>
