### ISSUE TITLE
Ads Rewards Grants - expiration date in UI - follow up to 4042

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4169]
## Description 
Ad grants still displaying expiration date on UI from both brave://rewards page and panel when viewing the grants list (which contains both UGP and Ad grants).

## Steps to Reproduce

   1. Claim an Ad grant. Note, on the "It's your lucky day" screen there isn't a date.
   2. Navigate to brave://rewards or open panel.
   3. Click on 'Grants' button.

## Actual result:
Expiration date is displayed:
![Screen Shot 2019-04-18 at 7 39 32 PM](https://user-images.githubusercontent.com/28145373/56397518-17d0bd00-6212-11e9-9bb9-70b3ca32a47d.png)

## Expected result:
No expiration date (like on "It's your lucky day" screen:
![Screen Shot 2019-04-18 at 7 38 45 PM](https://user-images.githubusercontent.com/28145373/56397523-21f2bb80-6212-11e9-9a22-7707b031dcda.png)

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.63.45 Chromium: 74.0.3729.75 (Official Build) beta(64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

## Miscellaneous Information:
cc @mandar-brave @NejcZdovc @jsecretan

**Comment by btlechowski** [comment]
Reproduced on

Brave | 0.63.45 Chromium: 74.0.3729.75 (Official Build) beta (64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Windows 10 OS Build 17134.523

![image](https://user-images.githubusercontent.com/34715963/56405803-411f3680-626e-11e9-85b1-d521d852b42c.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.63.52 Chromium: 74.0.3729.131 (Official Build) (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.523




- Verified the test plan from https://github.com/brave/brave-core/pull/2337


![image](https://user-images.githubusercontent.com/38657976/57208870-a5265680-6ff3-11e9-8f9a-9c43c8fe60b3.png)
![image](https://user-images.githubusercontent.com/38657976/57208878-afe0eb80-6ff3-11e9-981f-e2d72169bf77.png)
![image](https://user-images.githubusercontent.com/38657976/57208906-d0a94100-6ff3-11e9-9ccd-9df6fb1b7371.png)
