### ISSUE TITLE
[ads] Followup to "Smart NTT" #41303

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#41695]

**Comment by kjozwiak** [comment]
The above requires `1.72.85` or higher for `1.72.x` verification 👍

**Comment by btlechowski** [comment]
Verified with

Brave | 1.72.90 Chromium: 130.0.6723.70 (Official Build) beta (64-bit)
-- | --
Revision | 5f14a2225ebf4fcd654e064bde93e77fcc5d8f39
OS | Linux

Verified in https://github.com/brave/brave-browser/issues/41303

**Comment by btlechowski** [comment]
Verification passed on Brave v1.72.97 on Lenovo TB-8506FS (Android 11.0)


Verified in https://github.com/brave/brave-browser/issues/41303#issuecomment-2465975399
