### ISSUE TITLE
Drag shields settings on to page shows up about:blank

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#417]
## Description 
Drag shields settings on to page shows up abut:blank
## Steps to Reproduce

   1. Open release build
   2. Visit any page
   3. Click on shields, drag `Edit default shield settings...` and drop on page, tab opens up about:blank

 ## Actual result:

![shieldsdrag](https://user-images.githubusercontent.com/17010094/41824750-b2f190ee-77e3-11e8-8d06-450ef5749112.gif)
Console logs the following error
```
Unable to read VR Path Registry from C:\Users\\AppData\Local\openvr\openvrpaths.vrpath
[13816:11640:0624/190629.034:ERROR:CONSOLE(24)] "Uncaught Error: Assertion failed", source: chrome://settings/crisper.js (24)
```

## Expected result:
Dnd of shields settings should not cause any page reload. 
## Reproduces how often: 

100%

## Brave version (about:brave info)

80614db15a3b00dee5c9868c00c080a8f3a8bb31

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

Edit default shield settings... is no longer draggable.
