### ISSUE TITLE
Claim notification is not removed if you claim ad grant via BR panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4170]
## Description 

Claim notification is not removed if you claim ad grant via BR panel

## Steps to Reproduce

   1. Enable rewards
   2. Wait for ads grant notification to show up
   3. Keep rewards page open to see ads payout notification
   4. Claim it via BR panel
   5. Notification doesn't get removed from rewards page
   6. Reload the page, nothing happens
   7. Try to claim the grant via rewards page, shows grant already claimed and removes the notification

## Actual result:

Claim notification is not removed if you claim ad grant via BR panel

## Expected result:
Notification should be removed immediately after its claimed 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.63.45 Chromium: 74.0.3729.75 (Official Build) beta(64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?
N/A
- Can you reproduce this issue with the beta channel? 
Yes
- Can you reproduce this issue with the dev channel?
Most probably yes
- Can you reproduce this issue with the nightly channel?
Most probably yes
## Miscellaneous Information:

cc: @jsecretan @ryanml

**Comment by tmancey** [comment]
@LaurenWags I have retested and on 1.10 this is working as expected, could you please retest. Thanks
