### ISSUE TITLE
Add a flag that disables HSTS on localhost

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#41705]
### Platforms

all

### Description

Allowing HSTS to operate on localhost can be confusing for devs. We could consider adding a flag to make localhost an exception so that HSTS doesn't work there.

**Comment by diracdeltas** [comment]
Have we considered upstreaming this?

**Comment by arthuredelstein** [comment]
See https://groups.google.com/a/chromium.org/g/blink-dev/c/WJnjKYY2iSs/m/Rh9HlI3lAwAJ h/t @kdenhartog

**Comment by ShivanKaul** [comment]
Looks like this is incoming in CR 132: https://github.com/brave/cr-diffs/blob/master/cr132/131.0.6778.85_132.0.6834.15/features/net_base_features.cc.diff#L89-L91

**Comment by ShivanKaul** [comment]
This LGTM to close out now, I don't think we need to uplift this or anything
