### ISSUE TITLE
browser crashes when closing Private window (#compact-mode bug)

### ISSUE THREAD

**Issue by KickMultistream** [brave/brave-browser#41718]
### Description

when the new [#compact-mode](chrome://flags/#compact-mode) flag is enabled closing the private mode window makes the whole browser crash.

### Steps to reproduce

1. enable #compact-mode flag then relaunch the browser
2. open a private window
3. close the private window then watch the browser crash!

### Actual result

 crash

### Expected result

no crash

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

[Version 1.71.114 Chromium: 130.0.6723.58 (Official Build) (64-bit)](https://brave.com/latest/)
Windows 10.

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by KickMultistream** [comment]
@EdwardFalzon  i gave up on brave due to too many bugs and mediocre sync and translate, using Thorium because the main dev stated they will keep support for MV2 indefinitely plus it's lightning fast.

**Comment by 097115** [comment]
Confirmed for 1.71.118, 1.71.114, 1.70.126, 1.70.123, 1.70.119, 1.70.117, Ubuntu 22.04.04

**Comment by jagadeshjai** [comment]
This is an upstream bug that was fixed in https://chromium-review.googlesource.com/c/chromium/src/+/5876389. It will likely be available in Brave's Chromium version 132.

CC: @rebron
