### ISSUE TITLE
Claim banners are of differnt text size

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4171]
## Description 

Claim banners are of differnt text size
## Actual result:

![Screenshot from 2019-04-18 20-02-01](https://user-images.githubusercontent.com/17010094/56398510-eefef680-6216-11e9-833c-e8c2b84781b3.png)

## Expected result:
Text should be of same size

## Reproduces how often: 

Easy

**Comment by jsecretan** [comment]
Might get resolved by this: https://github.com/brave/brave-core/pull/2173

**Comment by LaurenWags** [comment]
Reproduced on macOS

Brave | 0.63.47 Chromium: 74.0.3729.108 (Official Build) (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Mac OS X

**Comment by rossmoody** [comment]
@LaurenWags are you still seeing this on Mac on nightly build?

**Comment by rossmoody** [comment]
Also technically this issue was the alert component not spanning the width of the column, the text sizes are the same size.

**Comment by LaurenWags** [comment]
@rossmoody looks good with 0.66.21 on Nightly

Brave | 0.66.21 Chromium: 74.0.3729.108 (Official Build)nightly (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Mac OS X

![Screen Shot 2019-04-24 at 2 50 25 PM](https://user-images.githubusercontent.com/28145373/56685637-6c57ba80-66a0-11e9-80b6-9a45eeefc981.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.5 x64` using the following build:

Brave | 0.66.87 Chromium: 75.0.3770.80 (Official Build) beta(64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Mac OS X

<img width="931" alt="Screen Shot 2019-06-11 at 1 05 49 PM" src="https://user-images.githubusercontent.com/2602313/59291882-d117a600-8c49-11e9-891e-7de7b99508b7.png">

Also ensured that claiming both grants works without any issues:

<img width="417" alt="Screen Shot 2019-06-11 at 1 06 20 PM" src="https://user-images.githubusercontent.com/2602313/59291909-e096ef00-8c49-11e9-8aad-8c01bb4b2d43.png">
