### ISSUE TITLE
[SERP->Leo] Support `Continue with Leo` button from Brave Search

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#41711]
### Platforms

Linux, macOS, Windows

### Description

When `Continue with Leo` button is clicked on Brave Search, we will open Leo side panel with the conversation entries from Brave Search.
A permission prompt will be shown to the user before opening Leo.

**Comment by kjozwiak** [comment]
The above requires `1.72.98` or higher for `1.72.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.73.86 Chromium: 131.0.6778.39 (Official Build) (64-bit)
-- | --
Revision | 52163bcf4e40f27ddb76ffa79c90a8833084a9bd
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from [brave/brave-core#26082](https://github.com/brave/brave-core/pull/26082)
- Verified enabling search flags and asking a question shows `Save chat in Brave Leo` 
- Verified clicking on `Save chat in Brave Leo` opens Leo in side panel
- Verified if Leo is not enabled/opted-in clicking on `Save chat in Brave Leo` opens Leo in side panel and shows opt-in disclaimer. Once opted in opening a new chat loads the chat query in Leo
- Verified the `Save chat in Brave Leo` option is not shown on private tabs
- Encountered [#42112](https://github.com/brave/brave-browser/issues/42112)

https://github.com/user-attachments/assets/97608560-61a1-49ad-9b5e-73545769f4f3

**Comment by LaurenWags** [comment]
changing to `release-notes/exclude` per discussion with @bbondy @kjozwiak
