### ISSUE TITLE
[ads] Search result ad landing page metrics are not reported on iOS

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#41722]
### Steps to reproduce

1. Open search.brave.software
2. Search for `giraffe`
3. Tap the `[STAGING] Brave Ads` search result ad

### Actual result

Search result ad landing page metrics are not reported

### Expected result

Search result ad landing page metrics are reported

### Reproduces how often

Easily reproduced

### Brave version

BraveCore 1.73.24 (130.0.6723.58)
Version 1.73 (24)
Device arm64 (iOS 17.4)

### Device/iOS version

-

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by btlechowski** [comment]
Verification passed on 1.74.20 on iPhone 13 Pro Max (iOS 17.7)

Verified test plan from https://github.com/brave/brave-core/pull/26130

<details>



</details>
