### ISSUE TITLE
Fix Ads locale on Windows

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#4172]
## Description 
Ads locale returns incorrect region on Windows

## Steps to Reproduce

   1. Enable Ads

## Actual result:
Ads is not supported for US, UK, France, Germany and Canadian regions

## Expected result:
Ads should be supported for US, UK, France, Germany and Canadian regions

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
0.65.70

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the dev channel? YES
- Can you reproduce this issue with the nightly channel? YES

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.63.46 Chromium: 74.0.3729.91 (Official Build) (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

- Verified below combinations (IP Address+OS Region+OS Locale) of scenarios on Windows 10 x64
  - US IP Address(VPN)+Region(US)+Local(English United States) -`Adds are Enabled`
  - US IP Address(VPN)+Region(US)+Local(English India)-`Adds are Disabled and catlog is empty`
  - US IP Address(VPN)+Region(US)+Local(English United Kingdom) -`Adds are Enabled`
  - India IP Address+Region(US)+Local(English United States)-`Adds are Disabled and catlog is empty`
  - India IP Address+Region(India)+Local(English India)-`Adds are Disabled and catlog is empty`

**Comment by GeetaSarvadnya** [comment]
@terry In one of the scenario even though Ads are disabled catalog is not empty is this expected?

US IP Address(VPN)+Region(US)+Local(English India)-Adds are Disabled and catlog is NOT empty

**Comment by tmancey** [comment]
Region/locale are used currently to determine so this is correct based upon the code. Please check with Jimmy for confirmation too. Thanks

**Comment by GeetaSarvadnya** [comment]
@jsecretan Can you clarify the above query, please?

**Comment by GeetaSarvadnya** [comment]
Got reply for above query https://bravesoftware.slack.com/archives/C43LW5U2H/p1555933330241600?thread_ts=1555923498.238200&cid=C43LW5U2H
