### ISSUE TITLE
Unable to log in to messenger.com with shields enabled

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#4173]
## Description 

We received a report from a user that they were unable to log into messenger.com in Brave. The site would display without issue, but there's likely a filter that's breaking the auth for the site. 

## Steps to Reproduce

   1. Go to messenger.com in Brave (appears to be win10 x64 from screenshot, but not confirmed)
   2. Attempt to authenticate.
   3. Get stuck.

## Actual result:

User unable to log in.

## Expected result:
User should be able to log in.

## Reproduces how often: 

100% for the user. 

## Brave version (brave://version info)

User did not provide. Requested, but was not included in follow-up.

## Version/Channel Information:

Suspect Release Channel. 

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:
*User confirmed that lowering shields resolves issue.*
- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
Sheilds is showing the following scripts being blocked;

```
https://www.facebook.com/login/async_sso/messenger_dot_com/?__a=1
https://connect.facebook.net/en_US/fbevents.js
```

We should allow facebook.com/facebook.net on this site

**Comment by snyderp** [comment]
Fixed by brave/adblock-lists/pull/66

**Comment by rebron** [comment]
@lukemulks We're good with this one. If you wanted to verify on your end as well that would be cool too.

**Comment by GeetaSarvadnya** [comment]
+1 from community https://community.brave.com/t/messenger-com-is-not-working-loading/67779/2
