### ISSUE TITLE
[Follow up to #40051][l10n] The whole `Sync` chain regressed and was not translated into non-English languages.

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#41731]
### Description

Follow-up to #40051.

### Steps to reproduce

1. Set the device language to `Russian`, `Spanish` or another non-English language
2. Launch Brave 
3. Hamburger menu > Settings > *Observe `Sync` is not translated*
4. Tap `Sync` > *Observe all screens are not translated*

### Actual result

The whole `Sync` chain regressed and was not translated into non-English languages. The issue is not reproducible in `1.70.x`.

------------------

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/bcbd71d5-6a05-4b70-8449-398ec9ec3891) | ![2](https://github.com/user-attachments/assets/e2437b6d-34f7-4df5-ac78-4c4592587a28) | ![3](https://github.com/user-attachments/assets/c7ad02fe-faf1-4f60-8be6-270e0cda703e) | ![4](https://github.com/user-attachments/assets/c8bfab05-1dcb-4e77-bd32-5dba7efae6b8) | ![5](https://github.com/user-attachments/assets/1add259f-31b2-421f-b8e9-2679074d28bb) |
| ![1](https://github.com/user-attachments/assets/e83e013f-e903-4e91-8cdb-63f5a7cb4503) | ![2](https://github.com/user-attachments/assets/113379c2-db40-4c8c-8399-56d3062ce605) | ![3](https://github.com/user-attachments/assets/dfcaaa67-9d68-4609-a508-1b995543c0e2) | ![4](https://github.com/user-attachments/assets/c7e12823-19eb-48e2-923f-535758fda440) | ![5](https://github.com/user-attachments/assets/2dfa0a06-5ec1-4783-9840-ce77ff6d0327) |

### Expected result

All screens related to the `Sync` chain must be translated into non-English languages.

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.71 (115)
BraveCore: 1.71.115 (130.0.6723.58)

### Device/iOS version

iPhone 14 / iOS 17.7

### Affected browser versions

- [ ] latest AppStore
- [x] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.71.123` or higher for `1.71.x` verification 👍

**Comment by Uni-verse** [comment]
In progress on iPhone 12 running iOS 18.0 using version 1.71 (124)

**French**
<details>

_General UI_

example | example | example | example | example | example
---|---|---|---|---|---
![Image](https://github.com/user-attachments/assets/a1b97eb4-b626-4e21-b949-d7b72cfb35d4) | ![Image](https://github.com/user-attachments/assets/0b200de5-144f-4836-b1bf-1b185b4727b0) | ![Image](https://github.com/user-attachments/assets/e40b08bb-5934-4666-82af-b1f72b8b4ce9) | ![Image](https://github.com/user-attachments/assets/ee439db6-b508-4dc7-a7fc-797c3d469421) | ![Image](https://github.com/user-attachments/assets/7cacd944-5bfc-4546-bafc-16312954fd83) | ![Image](https://github.com/user-attachments/assets/97b619cf-3899-4467-82aa-24c95b5da151)
