### ISSUE TITLE
Add ability to import and export brave settings

### ISSUE THREAD

**Issue by maxhu08** [brave/brave-browser#41741]
### Platforms

Linux, macOS, Windows

### Description

On the `brave://settings` page, there could be a button that says export. Clicking it would download a file with all the user's settings in it. 

There would also be a import button, and when the user presses it prompts them to open the settings file that was exported earlier. After the file gets imported, all the settings on that profile would match the settings described in the file.

This would make configuring brave on a new profile or new machine a lot less annoying.

**Comment by Brave-Matt** [comment]
While not strictly to be used as a backup, at this time I would recommend using Brave Sync for this: https://support.brave.com/hc/en-us/articles/360021218111-How-do-I-set-up-Sync

Simply enable Sync on your device to setup a Sync chain and ensure that you have access to the code words generated. You can then Sync any new machine (or your current machine with a new install/profile/etc) to your Sync chain and retrieve the data from it. 

I do think that there is a need for a "hard backup" of the kind you're describing here but it will likely be a while before this is implemented. Until then, as stated before, I'd recommend using Brave Sync for this. Additionally, you can export passwords and bookmarks already as `.csv` and `.html` files (respectively) that can be saved and imported into the browser.

For passwords, this can be done in: `brave://password-manager/settings`
For Bookmarks, this can be done in (click the "overflow" icon on the top right to view the option): `brave://bookmarks/`

**Comment by ricardogarceb** [comment]
This issue should be reopened because sync does not sync settings, so we need a method to back them up and import them
