### ISSUE TITLE
Re-evaluate criteria for supporting ads for each region

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4174]
Re-evaluate criteria for supporting ads for each region. 

More details here https://bravesoftware.slack.com/archives/C43LW5U2H/p1555674320167300

cc: @tmancey @jsecretan @tomlowenthal @bbondy @davidtemkin @mandar-brave

**Comment by Brave-Matt** [comment]
Probably related to #4187 
User on Community reporting exact scenario's discussed in int' slack chat:
https://community.brave.com/t/user-feedback-recommendation-dont-make-computer-language-synonymous-with-region/61638
