### ISSUE TITLE
‘Pending’ YouTube video will start playing in the background if another tab is moved

### ISSUE THREAD

**Issue by StoppingBuck** [brave/brave-browser#4175]
## Description 
If you have 3 tabs open and the first is in focus and the second is a ‘pending’ YouTube video, if you move the third tab out into a new/different Brave window, the YouTube video on the second tab will start playing even though focus remains on the first tab.

## Steps to Reproduce
   1. Open Brave and go to YouTube
   2. Open two videos in background tabs by Ctrl/Cmd+clicking on them. Neither video should autoplay.
   3. (Optional, but good to avoid a cacophony) Go to the third tab, the video will start playing. Pause it and return to the first tab.
   4. Now, while on the first tab, drag the third tab out of the Brave window and into its own new window (don’t click it into focus first - focus should remain on the first tab).

## Actual result:
Immediately, the second tab video starts playing in the background but the first tab is still the one in focus in the window.
I’ve temporarily uploaded a video showing it [here](https://www.dropbox.com/s/3b9g9yf10kc5pbh/2019-04-14%2009-31-19.flv?dl=0)

## Expected result:
Either the focus should change to the second tab or the YouTube video in the second tab shouldn’t auto-play. Either makes sense.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 0.63.35 Chromium: 74.0.3729.61 (Officiel version) beta(64-bit)
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Mac OS X

## Version/Channel Information:
Running Beta

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

**Comment by srirambv** [comment]
Does Chrome behave in same manner?

**Comment by StoppingBuck** [comment]
> Does Chrome behave in same manner?

Just tested with stable Google Chrome. Yes, the problem is present there too.

**Comment by srirambv** [comment]
cc: @bbondy  closing thread unless we need to patch something ourselves. Probably an upstream fix would be the best approach.

**Comment by StoppingBuck** [comment]
@srirambv I'm confused. Does that mean I should report it upstream so it can get fixed? If so... where?

**Comment by srirambv** [comment]
@StoppingBuck you can log an upstream bug here https://bugs.chromium.org/p/chromium/issues/
