### ISSUE TITLE
Shred doesn't clear site from Recently Closed Tabs

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#41769]
### Description

If the user Shreds a site, we don't clear the site from Recently Closed Tabs. This might be a _little_ surprising for the user, but not a privacy leak given that it's not exposed to the website. 

### Steps to reproduce

1. Make sure Shred feature is enabled
2. Open https://brave.com in a tab
3. Close the tab. 
4. Verify that brave.com shows up in Recently Closed Tabs
5. Open https://brave.com again
6. Shred it

### Actual result

brave.com exists in Recently Closed Tabs

### Expected result

brave.com maybe shouldn't exist in Recently Closed Tabs

### Reproduces how often

Easily reproduced

### Brave version

1.73+ (but also App Store)

### Device/iOS version

N/A

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.71.120` or higher for `1.71.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7
Brave build: 1.71 (121)
BraveCore: 1.71.121 (130.0.6723.91)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41769#issue-2603467814 and https://github.com/brave/brave-core/pull/26175#issue-2609584954
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Shred` clears site data from `Recently closed tabs`.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/eef384e1-a626-4419-a040-795f3baa09fe) | ![2](https://github.com/user-attachments/assets/b5a6d339-b703-4890-b60d-de1f90232a2f) | ![3](https://github.com/user-attachments/assets/c2d4337f-d4c5-43df-b932-d1ec4380d0ad) | ![4](https://github.com/user-attachments/assets/313bfef8-c7b0-4624-8fe7-ad74d964e8db) |
| ![1](https://github.com/user-attachments/assets/c4659b23-a866-4136-9722-a4ca51b0f4fc) | ![2](https://github.com/user-attachments/assets/e0b46d44-b838-44c0-812a-e22356c9d29e) | ![3](https://github.com/user-attachments/assets/4ba1929a-4647-415c-ab0e-252974451fec) | ![4](https://github.com/user-attachments/assets/119c8fd4-ba6d-4e10-aa0a-a5002d503b7c) |
