### ISSUE TITLE
Yahoo! FINANCE Interactive Charting Failure to Load. Continuous Buffer.

### ISSUE THREAD

**Issue by saintjcp** [brave/brave-browser#4176]
## Yahoo! FINANCE Interactive Charting Failure to Load.
After attempting to access the **FULL SCREEN CHART**, I am met with a continuous buffer symbol, along with the text _"Loading interactive chart..."_

   1. Access URL  https://finance.yahoo.com
   2. Locate search bar 
   3. Type **AAPL**
   4. Press _Enter_
   5. Located beneath the share price are blue colored tabs
   6. Locate _Chart_
   7. Left Click on _Chart_
   8. You will then be met with the issue, and if you click _Full Screen_, the problem persists.

## Actual result:

![Capture](https://user-images.githubusercontent.com/49791035/56433718-71c79600-6297-11e9-9574-d783010f06b6.PNG)
![fullscreenproplemCapture](https://user-images.githubusercontent.com/49791035/56434382-07fcbb80-629a-11e9-9d0c-751038b825b6.PNG)

## Expected result:
![Chrome Capture](https://user-images.githubusercontent.com/49791035/56433776-c2d78a00-6297-11e9-944e-0ddc01b5068b.PNG)

![fullscreenCapture](https://user-images.githubusercontent.com/49791035/56434359-f3b8be80-6299-11e9-88d2-1e3aec39969f.PNG)

## Version/Channel Information: This problem does not occur when using the Chrome Browser.

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Not sure.
- Can you reproduce this issue with the dev channel? Not sure.
- Can you reproduce this issue with the nightly channel? Not sure.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No, issue remains.
- Does the issue resolve itself when disabling Brave Rewards? No, issue remains.
- Is the issue reproducible on the latest version of Chrome? No, the issue does not exist on Chrome.

**Comment by rebron** [comment]
Fixed with 63.48. Closing.
