### ISSUE TITLE
YouTube full screen video goes little darker

### ISSUE THREAD

**Issue by mr-kasper** [brave/brave-browser#41775]
### Description

When I'm going to full screen in a video the screen goes a little bit darker.

### Steps to reproduce

1. Go to a random YouTube videos
2. Click full screen
3. 

### Actual result

The screen goes little bit darker than the origin, in chrome for example this issue doesn't exist.

### Expected result

The screen should stay in the same brightness.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave : 1.71.114 Chromium: 130.0.6723.58 (Official Build) (64-bit)
Revision : 89c4031c685a4296315a6f421f46275f0b72dd55
OS : Windows 10 Version 22H2 (Build 19045.5011)

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment]
@mr-kasper Can you provide screenshots and an example video/url of where you're seeing this?

**Comment by mr-kasper** [comment]
@rebron Never mind it was just my eyes I have the same status in chrome so I think it's normal.
Thanks for your time.
