### ISSUE TITLE
[Follow up to #40284] Different `blue` colors are used on onboarding screens for the `UK` and `Japan` when `Dark` and `Light` themes are applied.

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#41776]
### Description

Follow-up to #40284.

### Steps to reproduce

1. Set device Language/Region to `en_UK` or `jp_JP`
2. Fresh install and launch Brave
3. Go through onboarding > *Observe*

### Actual result

Different `blue` colors are used on onboarding screens for the `UK and `Japan` when `Dark` and `Light` themes are applied.

-------------------------

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/662b663d-aa30-4d56-b838-2e6c6dd4adf0) | ![2](https://github.com/user-attachments/assets/8f524be4-ea0d-4e9a-beba-04c2ef71eed7) | ![3](https://github.com/user-attachments/assets/3a943290-d387-489b-b214-5e114e0ba371) | ![4](https://github.com/user-attachments/assets/b41d2906-f48a-48ec-b42f-41ff33220792) | ![5](https://github.com/user-attachments/assets/8d519f23-345b-44e5-a07a-9441ec80d527) |
| ![1](https://github.com/user-attachments/assets/22048325-8946-4da3-90e5-07623b2acba5) | ![2](https://github.com/user-attachments/assets/06c702fc-b247-4ac1-8c48-a4d329b8b92c) | ![3](https://github.com/user-attachments/assets/2f4c6ec2-80f5-446e-b142-cbfd4f5618a9) | ![4](https://github.com/user-attachments/assets/1d3a0e1b-af5a-4259-ad1b-f360cd05bb89) | ![5](https://github.com/user-attachments/assets/e10445fc-d2fe-49ba-98b4-1f2a111b68cb) |

### Expected result

The same color must be used with a `Light` and `Dark` theme. 

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.71 (116)
BraveCore: 1.71.116 (130.0.6723.58)

### Device/iOS version

- iPhone 14 / iOS 17.7
- iPad Mni (6th gen) / iPadOS 18.0.1

### Affected browser versions

- [ ] latest AppStore
- [x] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kylehickinson** [comment]
These color switches are expected, only change required is the main call to action button style should be using the updated button text color

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7.2
Brave build: 1.74 (10)
BraveCore: 1.74.10 (131.0.6778.85)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41776#issue-2603846378 and https://github.com/brave/brave-browser/issues/41776#issuecomment-2442299938
2. *Verify*

**ACTUAL RESULTS:**
- Verified the text in the buttons has the correct color when a device is in `Dark mode`.

---------------------------

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/455539a8-b7c3-4fbe-bdf3-69c2a0b50a16) | ![2](https://github.com/user-attachments/assets/8f6774c8-e7b5-4688-8065-2c1bb1c49638) | ![3](https://github.com/user-attachments/assets/c7cddc00-25b3-4b88-9f74-70c086daa356) | ![4](https://github.com/user-attachments/assets/013b6f96-b270-4912-bed9-b87a8f7cab63) | ![5](https://github.com/user-attachments/assets/c59b3f0b-f323-46f4-a566-f37c4c0eb483) |
| ![1](https://github.com/user-attachments/assets/ea04551a-f831-4c03-988c-5565af59a3fc) | ![2](https://github.com/user-attachments/assets/732db7bd-75d9-47e8-8657-fd97a8f9567b) | ![3](https://github.com/user-attachments/assets/b490e2e2-9587-45da-aead-2b96a02134b1) | ![4](https://github.com/user-attachments/assets/c1aa5f35-58e2-46df-8ad4-54a3af73f968) | ![5](https://github.com/user-attachments/assets/dd0bf51e-497f-4eef-b875-382d319b8558) |
