### ISSUE TITLE
Add last-search-engine as a pref in the browser

### ISSUE THREAD

**Issue by IanKrieger** [brave/brave-browser#41789]
Store last used widget engione as a pref, as not to lose it if local storage is ever cleared.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.74.6 Chromium: 131.0.6778.69 (Official Build) beta (64-bit)
-- | --
Revision | 876de763a749f7f8a9a5a2fd72a2391129a3a0f0
OS | Windows 11 Version 23H2 (Build 22631.4460)
```

Case 1: Single Search Engine Selected  ('Bing`)


1. Installed 1.74.6
2. launched Brave
3. opened NTP and verified NTP search widget is shown
4. confirmed Brave is default SE for US region
5. clicked Brave icon in the search widget
6. clicked `Customize list` 
7. selected `Bing` and unselected Brave 
8. closed `Customize Dashboard` 
9. confirmed `Bing` icon is shown in the Search widget
10. closed Brave and relaunched Brave 
11. confirmed selected SE is shown in the NTP search widget i.e. Bing  
12. entered search term `Turkey meal` in the search widget
13. confirmed `Bing` results page is shown


step 3 | step 4-6 | step 7 | step 9 | step 11 | step 12 | step 13
------- | --------  | ------  | ------- | ------- | ------ | ------
![Image](https://github.com/user-attachments/assets/c8c3e56c-d32c-4ec5-993f-ec96b025a36d)|![Image](https://github.com/user-attachments/assets/79694542-55cb-45c2-b4b5-c4a8681561fb)|![Image](https://github.com/user-attachments/assets/523de6f6-9bd8-45e9-898f-03c18765343a)|![Image](https://github.com/user-attachments/assets/50a8f0c6-9f6c-49f7-b910-18f6945441ff)|![Image](https://github.com/user-attachments/assets/36f5651c-f379-4d85-8879-7e62ad821d59)|![Image](https://github.com/user-attachments/assets/bc092a77-8d13-46e5-b909-468a97bb6359)|![Image](https://github.com/user-attachments/assets/7682b3ae-275a-402e-bee7-87b1faf8254c)

Case 2: Single Search Engine Selected (`DDG`)

1. Continued from Case 1
    - Bing is selected 
2. clicked Bing icon and clicked `Customize list`
3. selected `DuckDuckGo` and unselected `Bing` and close the Dashboard
4. confirmed `DuckDuckGo` logo is shown in the search widget
5. opened Dashboard again disabled `Show search widget on the new tab page` toggle
6. closed and relaunched Brave
7. confirmed the `DDG`, is shown the last SE that was set
8. entered search term `Turkey ideas` in the search widget
9. confirmed `DDG` search results page shown

step 2 | step 3 | step 4 | step 5 | step 7 | step 8 | step 9
------ | ------- | -------- | ------ | ------ | ----- | ------
![Image](https://github.com/user-attachments/assets/567b9c39-c8d2-4af0-a552-536485ba1f36)|![Image](https://github.com/user-attachments/assets/9ffc5440-1e4f-4e41-beca-3675fe478af7)|![Image](https://github.com/user-attachments/assets/9a0979a7-c589-4a53-8623-a295b022828b)|![Image](https://github.com/user-attachments/assets/6cd4d41c-97bc-4228-834f-7c1da3ee83f5)|![Image](https://github.com/user-attachments/assets/398010dc-a227-4d30-985b-8ffba0ecbf9e)|![Image](https://github.com/user-attachments/assets/e7b04e9e-90ac-4218-8b25-15508ce45a5c)|![Image](https://github.com/user-attachments/assets/80e3da53-d7bd-4a24-a0d7-473e8938beb7)

Case 3:  Multiple Search Engine Selected

1. Continue from Case 2
     - DDG is shown in the search widget 
2. clicked `Customize list` to open `Customize Dashboard`
3. selected `Google` and `Bing`
4. closed the Dashboard and opened SE list
5. confirmed all three SE are shown on the list
6. selected `Bing` as the SE from the list
7. confirmed `Bing` icon is shown in the Search widget as expected
8. closed and relaunched Brave 
9. confirmed `Bing`, is shown, the last SE that was set
10. entered search term `turkey recipes` in the search widget
11. confirmed `Bing` results shown

step 1 | step 3 | step 5 | step 6-7 | step 9 | step 10 | step 12 
------- | ------ | ------ | ------ | ------- | ------ | -----
![Image](https://github.com/user-attachments/assets/469372fa-456d-486d-be35-c1e40023849f)|![Image](https://github.com/user-attachments/assets/fa8a76a4-df3e-41d9-86c1-f9c126bbcbd4)|![Image](https://github.com/user-attachments/assets/f756d1a6-df6a-42f1-b042-cac5a505bfcc)|![Image](https://github.com/user-attachments/assets/e6da83c9-2099-4d85-940d-e27e87024d78)|![Image](https://github.com/user-attachments/assets/95942f74-ea4c-4d0d-b96c-ce6b919d496f)|![Image](https://github.com/user-attachments/assets/b7a3a0a9-5437-4fec-b14f-cf8879481234)|![Image](https://github.com/user-attachments/assets/13f44afd-7b79-47ae-b354-a8b0cf0d24e0)





Scenario 2

change default using widget icon (i.e ddg)
see that change is reflected in widget
If NTP search is enabled, disable it
close browser
open browser
enable NTP search
ensure the search engine you recently set is the same (i.e ddg)
ensure all selected engines are still selected

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.74.10 Chromium: 131.0.6778.85 (Official Build) beta (x86_64)
-- | --
Revision | bdff9e7d7314280ddbce1c3ada3abee4ce4a3b32
OS | macOS Version 14.7.1 (Build 23H222)
```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using

Brave	1.74.19 Chromium: 131.0.6778.108 (Official Build) beta (64-bit) 
Revision	12080da255dfc6f1f55b78bd96cd2f18bce5cb8a
OS	Linux

Testcase 1:  Default region - US

<details>
<summary>Case 1: Single Search Engine Selected (`Bing`) - PASSED </summary>


1. Installed 1.74.19
2. launched Brave
3. opened NTP and verified NTP search widget is shown
4. confirmed Brave is default SE for US region
5. clicked Brave icon in the search widget
6. clicked `Customize list` 
7. selected `Bing` and unselected Brave 
8. closed `Customize Dashboard` 
9. confirmed `Bing` icon is shown in the Search widget
10. closed Brave and relaunched Brave 
11. confirmed selected SE is shown in the NTP search widget i.e. Bing  
12. entered search term `christmasdecor` in the search widget
13. confirmed `Bing` results page is shown

step 3 | step 4-6 | step 7 | step 9 | step 11 | step 12 | step 13
------- | --------  | ------  | ------- | ------- | ------ | ------
![Image](https://github.com/user-attachments/assets/a153e197-1d84-4859-9d7e-d8e1f460f48c)|![Image](https://github.com/user-attachments/assets/38c1959b-e6e5-4cbb-bd05-94b50830072f)|![Image](https://github.com/user-attachments/assets/904ee314-f5ea-4cab-a14b-0f9f7961d106)|![Image](https://github.com/user-attachments/assets/9f94dfe0-3d1f-4814-b9c6-39a2fbb81021)|![Image](https://github.com/user-attachments/assets/b5ef232a-4ad9-4f76-954d-7688b7372975)|![Image](https://github.com/user-attachments/assets/a09ee51b-8ecc-410b-809d-e04ea8c37287)|![Image](https://github.com/user-attachments/assets/5baad7e6-53a8-41fd-9506-d8745b257b63)

</details>

<details>
<summary>Case 2: Single Search Engine Selected (`DDG`)- PASSED</summary>

1. Continued from Case 1
    - Bing is selected 
2. clicked Bing icon and clicked `Customize list`
3. selected `DuckDuckGo` and unselected `Bing` and close the Dashboard
4. confirmed `DuckDuckGo` logo is shown in the search widget
5. opened Dashboard again disabled `Show search widget on the new tab page` toggle
6. closed and relaunched Brave
7. opened Dashboard again and enabled `Show search widget on the new tab page` toggle
8. confirmed the `DDG`, is shown the last SE that was set
9. entered search term `christmas markets` in the search widget
10. confirmed `DDG` search results page shown
 
step 2 | step 3 | step 4 | step 5 | step7- 8| step 9 | step 10
------ | ------- | -------- | ------ | ------ | ----- | ------
![Image](https://github.com/user-attachments/assets/69c268a6-bd13-4318-b43b-38bc93ce24d4)|![Image](https://github.com/user-attachments/assets/fa39eafc-f637-4217-be1b-429cbf948f2a)|![Image](https://github.com/user-attachments/assets/faae5b83-8406-48e3-94bd-8e753071d72f)|![Image](https://github.com/user-attachments/assets/2b82999d-0cfd-48d4-a908-8b41127a64f7)|![Image](https://github.com/user-attachments/assets/1944ac80-2a0d-4737-b6ab-13210b6d9b72)|![Image](https://github.com/user-attachments/assets/e6055007-9a25-49a2-a38e-9b1d02c05325)|![Image](https://github.com/user-attachments/assets/0a2d593c-0a39-4691-bf71-919af069dba7)

</details>

<details>
<summary>Case 3:  Multiple Search Engine Selected (`Bing`) - PASSED</summary>

1. New profile 
2. clicked `Customize list` to open `Customize Dashboard`
3. selected `DuckDuckGo`, `Google` and `Bing`
4. closed the Dashboard and opened SE list
5. confirmed all three SE are shown on the list
6. selected `Bing` as the SE from the list
7. confirmed `Bing` icon is shown in the Search widget as expected
8. closed and relaunched Brave 
9. confirmed `Bing`, is shown, the last SE that was set
10. entered search term `Christmas lights` in the search widget
11. confirmed `Bing` results shown

step 3 | step 5 | step 6-7 | step 9 | step 10 | step 12 
------- | ------ | ------ | ------ | ------- | ------ 
![Image](https://github.com/user-attachments/assets/a82ba6c1-0a3e-4d69-a868-8fe67d75635f)|![Image](https://github.com/user-attachments/assets/3dfb48f6-72c3-4137-bb14-615509d5d65e)|![Image](https://github.com/user-attachments/assets/6eb6fea8-6a4e-46c7-b75a-f8889571c1e3)|![Image](https://github.com/user-attachments/assets/adf75195-1750-452c-9901-9f13ba819653)|![Image](https://github.com/user-attachments/assets/a0b0a126-6435-4bb2-80c0-6f5e3f0415c1)|![Image](https://github.com/user-attachments/assets/10925e30-8297-49ef-960c-96794c6193a8)

</details>

<details>
<summary>Case 4: Multiple Search Engine Selected (`DDG`) - PASSED</summary>

1. Continue from Case 3
     - `Bing` is shown in the search widget 
2. clicked `Bing` icon and selected `DDG` from the SE list
3. confirmed `DDG` is shown in the search widget 
4. disabled `Show search widget on the new tab page` toggle via `Customize` setting
5. closed and relaunched Brave
6. enabled NTP search via `Customize Dashboard`
7. confirmed all three SE are selected
8. confirmed `DDG`, is shown, the last SE that was set in the Search widget
9. clicked `DDG` and selected `Google` as a default SE
10. clicked 3 dot menu and click `Hide Search` button
11. closed and relaunched Brave 
12. enabled `Search` widget via `Customize` 
13. confirmed `Google` is shown, the last SE that was set
14. entered search term `Christmas holidays` in the search widget
15. confirmed `Google` results shown

step 1 | step 2 | step 3 | step 4 | step 6 -7 | step 9 | step 10 | step 12 | step 13 | step 15
------ | ------- | ------- | -------- | ----- | ----- | -------- | ------- | ---- | ----
![Image](https://github.com/user-attachments/assets/abdd741a-c6bb-44e9-8a79-f8bfbe79fc2c)|![Image](https://github.com/user-attachments/assets/2c090c89-7527-469c-964f-3b7c434b57ed)|![Image](https://github.com/user-attachments/assets/3597ff24-afe8-4211-8322-eee86530f49b)|![Image](https://github.com/user-attachments/assets/70d29213-6ba4-4ce9-89e4-e35f0cdbce6a)|![Image](https://github.com/user-attachments/assets/5b5629ec-2794-4da3-a64d-b8e25cc6b581)|![Image](https://github.com/user-attachments/assets/50d41bec-dc53-480e-8278-e4d04885cf05)|![Image](https://github.com/user-attachments/assets/75ab3b06-0fc5-4d0a-ac07-6d531b0847e8)|![Image](https://github.com/user-attachments/assets/2b6f89a5-f30e-4140-9e53-c34fe744803d)|![Image](https://github.com/user-attachments/assets/11fea0c5-bfa0-44ab-a83a-09dd41e25d6e)|![Image](https://github.com/user-attachments/assets/6ac3a58c-0099-49a6-9aa8-779d1568682c)


</details>

<details>
<summary>Case 5: Upgrade - PASSED</summary>

1. Installed 1.73.97
2. launched Brave
3. confirmed Brave icon is shown as default in the search widget
4. unselected `Brave` and selected `Qwant` 
5. confirmed `Qwant` logo is shown in the search widget
6. closed Brave
7. renamed the profile `Brave-Browser-Beta`
8. installed 1.74.19
9. launch Brave 
10. confirmed `Qwant` logo is shown in the search widget
11. closed and restarted Brave
12. confirmed `Qwant` is shown in the search widget
13. entered a search term `Christmas movies` in the search widget
14. confirmed `Qwant` results shown
 
step 1 | step 3 | step 4 | step 5 | step 8 |step 10 | step 12 | step 14
------- | ------ | ------- | ------- | -------  | ------ | ------- | -------
![Image](https://github.com/user-attachments/assets/28df1e82-95d4-4805-82c4-f2eacd72f959)|![Image](https://github.com/user-attachments/assets/e0d63b7b-e056-4e8f-af61-af7d9dff003f)|![Image](https://github.com/user-attachments/assets/c9d7e902-1540-4d24-ae82-cf300089d6d1)|![Image](https://github.com/user-attachments/assets/cd1c2a05-45cc-420c-9749-fc40b9ac8994)|![Image](https://github.com/user-attachments/assets/bba1d88b-0cac-4b69-b74e-d850e6ce3fbb)|![Image](https://github.com/user-attachments/assets/0b904c70-09ce-407b-91c9-09832c08a4a7)|![Image](https://github.com/user-attachments/assets/f0826140-f0fe-42f0-a8e4-8097fcc2fad6)|![Image](https://github.com/user-attachments/assets/58adf58d-7b0b-4352-ba97-03f4a9f74f6b)


</details>

Testcase 2:  Non - US locale (Mozamique)

<details>
<summary>Case 1: Single Search Engine Selected (`Google`) - Pending</summary>

Pre-requisite:   Changed to `Mozambique` 
`Google` is default search engine

1. Installed 1.74.6
2. launched Brave
3. opened brave://settings/search shows `Google` as default
4. opened NTP and verified NTP search widget is shown
5. confirmed Brave is shown in the search widget 
6. clicked Brave icon in the search widget
7. clicked `Customize list` 
8.  unselected Brave and selected `Google`
9. confirmed `Google` icon is shown in the search widget
10. disabled search widget and closed Brave
11. relaunched Brave and enabled the search widget 
12. confirmed selected SE (`Google`) is shown in the NTP search widget 
13. entered search term `Thanksgiving` in the search widget
14. confirmed `Google` results are shown

step 3 | step 4-6 | step 8 | step 9 | step 10 | step 10a | step 11 | step 12 | step 13 | step 14
------ | --------  | ------  | ------- | ------- | ------ | ------ | ------ | ------ | ---------


</details>
