### ISSUE TITLE
Build out Shield ZCash Account Modal

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#41780]
### Platforms

all, Windows, macOS, Linux

### Description

We need to build out and wire up the new `Shield ZCash Account` modal. 

Figma Design: https://www.figma.com/design/muVcmcu4RFNu0LkXe9VRDl/Wallet-2.0?node-id=18149-180128&node-type=frame&t=VCgBU4zVzCjUX4oA-0

![Image](https://github.com/user-attachments/assets/4c677116-3359-4de1-bc9f-d3ca5ff5c220)

![Image](https://github.com/user-attachments/assets/03a7821d-bf7b-4227-8208-7ac5fee7d18c)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.5 Chromium: 131.0.6778.69 (Official Build) beta (64-bit)
-- | --
Revision | fbd7c390a7daa54f1aac2c769076d3fecf7c7fc7
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from [brave/brave-core#26214](https://github.com/brave/brave-core/pull/26214)
- Verified `Switch to shielded account` option is shown for ZCash account
- Encountered [#42294](https://github.com/brave/brave-browser/issues/42294)
 
https://github.com/user-attachments/assets/2ade1061-6101-476e-b075-b293d216fc78
