### ISSUE TITLE
Add more padding to empty activity tab info text

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#41786]
### Description

Add more padding to empty activity tab info text

### Steps to reproduce

1. Create a new wallet
2. Open Panel and hide graph 
3. Click on Activity in segmented controller
4. Text need bottom padding

### Actual result

![Image](https://github.com/user-attachments/assets/3d2d821f-c074-49d4-8e35-4631d8300379)

### Expected result

More padding for text

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

 
Brave | 1.72.82 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 4f0233b15f1896e28ff5ce439de1f658a2ef2df0
OS | Linux
 

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @kleantzogu @Douglashdaniel

**Comment by kjozwiak** [comment]
The above requires `1.72.88` or higher for `1.72.x` verification 👍
