### ISSUE TITLE
Contextual panel item is not activated after detaching that its tab

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#41782]
### Description

This is regression from https://github.com/brave/brave-core/pull/25771

Leo icon is not activated after attached.

### Steps to reproduce

1. Create any two tabs and open leo panel
2. Detach a tab that has leo panel and create window window with it
3. 

### Actual result

New window has one tab and leo panel opened but its sidebar icon is not activated
<img src="https://github.com/user-attachments/assets/4d3e81b0-3f51-479a-9116-3ee1ffdc2e52" alt="drawing" width="600"/>

### Expected result

New window has one tab and leo panel opened and its sidebar icon is activated
<img src="https://github.com/user-attachments/assets/867b2835-7420-4a22-8147-ea855fd12b20" alt="drawing" width="600"/>

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.73.9 Chromium: 130.0.6723.44 (Official Build) nightly (x86_64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by simonhong** [comment]
Fixing now.

**Comment by LaurenWags** [comment]
Requires 1.72.89 or higher for verification 👍🏻

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.72.93 Chromium: 131.0.6778.14 (Official Build) beta (64-bit)
-- | --
Revision | 69e5dc20ca483a13316632df5bcd9279bb2a3cb7
OS | Windows 11 Version 23H2 (Build 22631.4391)
```



Reproduced this issue in `1.73.9 Chromium: 130.0.6723.44 (Official Build) nightly (64-bit)`
![Image](https://github.com/user-attachments/assets/f7d318b2-fcb8-4013-a5f2-27a501b92017)
![Image](https://github.com/user-attachments/assets/4ac9e114-449a-44ea-b1ce-216bb3f9f3ae)




![Image](https://github.com/user-attachments/assets/c14b4a05-7c79-41fe-8282-dad285f4753d)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.93 Chromium: 131.0.6778.14 (Official Build) beta (arm64)
-- | --
Revision | 69e5dc20ca483a13316632df5bcd9279bb2a3cb7
OS | macOS Version 14.6.1 (Build 23G93)
```

Confirmed that when tearing off a tab with the Leo side panel opened/active, the resulting window has one tab shows the Leo sidebar icon state as active in pressed state. 

example | example 
------- | ----
![Image](https://github.com/user-attachments/assets/81d3ae7f-3c2a-4c7d-9f75-68ea82c26e80)|![Image](https://github.com/user-attachments/assets/7cbd56ff-2536-428a-aa86-2f733d0c5c14)
