### ISSUE TITLE
unnecessary scroll bars on `brave://settings/help` and other setting pages where scrolling isn't needed

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#41796]
### Description

After UI changes to brave://settings/help, I'm seeing unnecessary scroll bars on brave://settings/help with `1.73.32`. `1.73.9` (before the changes on the same machine) does not display scroll bars.

Using macOS x64 with external monitor, here's my resolution if that helps:

![Image](https://github.com/user-attachments/assets/e956303d-f640-4818-8080-14a662369f04)

### Steps to reproduce

1. Update to a version with UI changes such as 1.73.32
2. Look at brave://settings/help

### Actual result

See unnecessary scroll bars:

![Image](https://github.com/user-attachments/assets/413394b3-9dae-43e4-9fc5-747d77175d99)

### Expected result

No scroll bars as it was previously:

![Image](https://github.com/user-attachments/assets/c037730e-6afa-4075-8d89-6f619423a878)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.73.32

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron

**Comment by LaurenWags** [comment]
fwiw, no scroll bars on different machine - macOS arm64 laptop (no external monitor) using `1.73.32`:

Example | Example
--- | ---
![Image](https://github.com/user-attachments/assets/24aa05c3-1bbd-44ee-96e2-f5e12941b3ed) | ![Image](https://github.com/user-attachments/assets/9a548b72-e35c-4b7c-8bad-7c4e0404335c)

**Comment by kjozwiak** [comment]
Seeing the same as @LaurenWags on my `Win 11 x64` machine where I'm seeing scroll bars for pages `brave://settings/getStarted`, `brave://settings/reset` & `brave://settings/downloads` where there's no need for any scroll bars to be displayed as they're not usable.

```
Brave | 1.73.34 Chromium: 130.0.6723.58 (Official Build) nightly (64-bit)
-- | --
Revision | a9151b24a2f404d4c0efeadbb486f36c35799690
OS | Windows 11 Version 23H2 (Build 22631.4317)
```

![Image](https://github.com/user-attachments/assets/4fdbd39b-6323-4d5b-a22a-5b8457dc5ab7)

**Comment by rebron** [comment]
related PR https://github.com/brave/brave-core/pull/26015

**Comment by aguscruiz** [comment]
Fixing now, found the issue.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.74.3 Chromium: 131.0.6778.39 (Official Build) beta (arm64) 
Revision	0ce9628041e549979e5c522f7ec10ee1f5470182
OS	macOS Version 15.2 (Build 24C5073e)
```

**Comment by MadhaviSeelam** [comment]
Verification `Passed` using
```
Brave | 1.73.34 Chromium: 130.0.6723.58 (Official Build) nightly (64-bit)
-- | --
Revision | a9151b24a2f404d4c0efeadbb486f36c35799690
OS | Windows 11 Version 23H2 (Build 22631.4460)
```

- Reproduced the issue with `1.73.34` using STR from the issue description https://github.com/brave/brave-browser/issues/41796#issue-2605960683.
- Confirmed unnecessary scroll bars are not shown in the internal pages.

1.73.34 | 1.74.x 


brave://settings/braveContent | brave://settings/shields | brave://extensions | brave://settings/content|
------------ | ------------- | ------------ | -------------
![Image](https://github.com/user-attachments/assets/c3aeb161-8c48-4c19-9a13-71eb49aa36c3)|![Image](https://github.com/user-attachments/assets/db352b8f-43c0-400b-b085-fd644c0ee838)|![Image](https://github.com/user-attachments/assets/bd0abb41-c200-4f15-a600-52c40b74334c)|![Image](https://github.com/user-attachments/assets/ce11fd82-cdd9-454b-a9b8-71eefa8419f6)
![Image](https://github.com/user-attachments/assets/da1a3304-d8d1-4729-921b-cf6adef68f88)|![Image](https://github.com/user-attachments/assets/5047e3ce-b8e0-48a0-a099-06b97102b1b5)|![Image](https://github.com/user-attachments/assets/91ac470a-a490-4b1f-9e46-36f7d3b18943)|![Image](https://github.com/user-attachments/assets/7da4e992-f66b-4a75-b532-3452535c2e49)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.74.19 Chromium: 131.0.6778.108 (Official Build) beta (64-bit) 
Revision	12080da255dfc6f1f55b78bd96cd2f18bce5cb8a
OS	Linux
```


- Reproduced the issue with `1.73.34` using STR from the issue description https://github.com/brave/brave-browser/issues/41796#issue-2605960683.
- Confirmed unnecessary scroll bars are not shown in the internal pages.

1.73.34 | 1.74.x 


brave://settings/help | brave://settings/braveContent | brave://settings/shields |  brave://settings/content
------------ | ------------- | ------------ | -------------  
![Image](https://github.com/user-attachments/assets/c24b959c-0abe-42b3-9d39-a7515c7b2231)|![Image](https://github.com/user-attachments/assets/3ec2fad5-5f51-42b9-b58d-c42d34b9bf67)|![Image](https://github.com/user-attachments/assets/e0470325-fbae-446e-a09a-285418704e52)|![Image](https://github.com/user-attachments/assets/f26ea756-1690-4f4c-ac21-8f043745c715)
![Image](https://github.com/user-attachments/assets/88e60bfe-c684-4211-93a0-6e9e9d84a752)|![Image](https://github.com/user-attachments/assets/14b1b791-b63a-45e3-9ab1-33d375fb1d3b)|![Image](https://github.com/user-attachments/assets/abcf3aa8-8269-419b-93b4-79b3f48fd756)|![Image](https://github.com/user-attachments/assets/62ec604a-f2a7-4a62-ba1d-611755f88ee3)
