### ISSUE TITLE
Error/No internet connectivity page needs a Brave design

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#418]
## Description 

Error/No internet connectivity page needs a Brave design
## Steps to Reproduce

   1. Disconnect from internet
   2. Load a page
   3. Shows Chrome error/no network page

 ## Actual result:

![image](https://user-images.githubusercontent.com/17010094/41825135-9da1ce10-77e9-11e8-9dbb-63cd6c2b7bff.png)

## Expected result:
Should have a new Brave error page

**Comment by rossmoody** [comment]
Closing this one in favor of #1149
