### ISSUE TITLE
[iOS/Wallet]: Speed Up Transaction in Transaction Status Screen

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#41800]
Add a button to trigger speed up transaction flow
![Image](https://github.com/user-attachments/assets/619c673a-8e17-4c29-ba36-ae5ca940650d)
Flow: https://www.figma.com/design/26xCR66ZscSyVpTKrt85Hn/Transactions?node-id=3454-139759&m=dev

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.3 running 1.75 (176)
- Verified steps from [brave/brave-core#26947](https://github.com/brave/brave-core/pull/26947)
- Verified Speedup transaction shows up when a transaction is submitted
- Verified tapping on Speed up brings up a new transaction
- Verified Cancel transaction brings up a new cancel transaction

https://github.com/user-attachments/assets/f9ce763f-0a10-4df0-853b-d46309b58233

![Image](https://github.com/user-attachments/assets/68a1ecfb-6bd2-48af-8979-6b90492e0830) | ![Image](https://github.com/user-attachments/assets/48e5896e-01f0-4a38-ba5a-5d503f359af9) | ![Image](https://github.com/user-attachments/assets/d97222ac-292c-4644-929f-e76895d71f75)
-- | -- | --
![Image](https://github.com/user-attachments/assets/415660b9-b4d6-4dc4-aa4a-e6826cd2e625) | ![Image](https://github.com/user-attachments/assets/f15167ce-6b15-4b0f-9a24-43c334a4b539) | ![Image](https://github.com/user-attachments/assets/48a8d972-5cd3-431d-86b9-1be4120ca309)
