### ISSUE TITLE
Share/Copy/Edit buttons disappear when "Show browser suggestions" is disabled

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#41806]
### Description

On Android, if the `Show browser suggestions` option in `Settings --> Search engines` is disabled, then all of the options that appear under the address bar when tapped into (`Share`, `Copy address`, `Edit address`) disappear/do not display. Not entirely sure why this is the case but this should not be the behavior, as it prevents users from accessing those [necessary] options when browsing.

![Image](https://github.com/user-attachments/assets/4da857d4-1490-4e0a-9b57-21526152d0fb)

### Steps to reproduce

1. Launch Brave on Android
2. Disable `Show browser suggestions`
3. Tap into address bar

### Actual result

Address bar options do not display

### Expected result

Address bar options should display

### Reproduces how often

Easily reproduced

### Brave version

v1.71.114

### Device

- Brand/model: All
- Android version: All 

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

https://community.brave.com/t/how-to-edit-an-address-in-toolbar-without-using-show-browser-suggestions/575954/5?u=mattches

**Comment by hollons** [comment]
Additional reports:

Screenshare provided https://x.com/matchadrop/status/1849057723591037381

https://appfigures.com/reviews/266342430751LqQDJbdjTiLfpXyAJ8Bq2WA
https://appfigures.com/reviews/266342430751LpBpzBqVQLj75IDp6z-qZCA
https://appfigures.com/reviews/266342430751LaPWB8QxsUt7rxitCYCsAYA
https://appfigures.com/reviews/266342430751LOCmhv0TuTnie10A5zRBAXg

**Comment by kjozwiak** [comment]
The above requires `1.71.120` or higher for `1.71.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 AP41.240823.009 release-keys
Brave build: 1.71.120
Chromium: 130.0.6723.70 (Official Build) (64-bit) 
```

Filed follow-up issue #41951
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41806#issue-2606807041
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Share`, `Copy` and `Edit` are still shown when `Show browser suggestions` is OFF
- Verify that `Link you copied` is still shown when `Show browser suggestions` is OFF

---------------------------

`Galaxy Tab S8`

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/dd4a50a9-c15e-46b1-b44d-bdf9a53a7285) | ![2](https://github.com/user-attachments/assets/539624a0-636e-486d-a905-d30f41f17750) | ![3](https://github.com/user-attachments/assets/45715548-da71-4a10-a115-78390da3d770) |
| ![1](https://github.com/user-attachments/assets/415bb98d-3749-4d59-9d3d-4e93c7846eac) | ![2](https://github.com/user-attachments/assets/3460fbdd-87b1-4464-8069-df30d36ff9e2) | ![3](https://github.com/user-attachments/assets/26f1ce32-487d-42eb-a7e6-0e77756b0a8e) |

`Pixel 7`

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/0eeefb63-ee6c-46a3-8cac-c62d442b76ee) | ![2](https://github.com/user-attachments/assets/cda724fd-fc8b-4e14-8855-5c32b34042a0) | ![3](https://github.com/user-attachments/assets/f2daa69b-cf34-46fa-ae00-6540eebf4fcf) |
| ![1](https://github.com/user-attachments/assets/f9c5179e-2f46-4474-8c82-661d11efd09a) | ![2](https://github.com/user-attachments/assets/f56a7f51-03e9-4c3f-b99c-4b4ffda2bca1) | ![3](https://github.com/user-attachments/assets/9063d840-ecb4-4f22-9271-fab39a55277d) |

**Comment by sk666** [comment]
Hi, is it normal that I stil have this issue with a pixel 8 android 15 after the update 1.71.118? I cleared brave cache, does not fixed it.
