### ISSUE TITLE
canvas toBlob and convertToBlob data is not farbled per-session

### ISSUE THREAD

**Issue by tjiin** [brave/brave-browser#41822]
### Description

The output of canvas.toBlob and offscreenCavas.convertToBlob is not farbled per-session like other canvas functions (toDataURL, getImageData). It's easy to fingerprint their output across different browser sessions. Is this a bug or the intended behaviour?

### Steps to reproduce

1. Enable maximum farbling settings and enable clear cookies on exit. Open the following jsfiddle (or the attached html file) in the browser.: 
https://jsfiddle.net/092g7dxj/1/

[brave_blob_poc.txt](https://github.com/user-attachments/files/17489251/brave_blob_poc.txt)

2. Note the fingerprints
3. Restart browser and reload test page
4. Note that while the toDataURL and getImageData fingerprints have changed, both of the blob method fingerprints have not

### Actual result

![Image](https://github.com/user-attachments/assets/2e69a5cc-9da9-470f-9884-b51004b52b98)
![Image](https://github.com/user-attachments/assets/1436a1db-f947-4402-bd6a-a2294f67d5f9)

### Expected result

Blob methods should have per-session farbled output as well to prevent fingerprinting.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave	1.70.126 Chromium: 129.0.6668.100 (Official Build) (64-bit) 
Revision	35f34f21e597f5f30e9e206b0354cc137df1f2a3
OS	Linux

Ubuntu 22.04.1

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by tjiin** [comment]
okay nevermind, seems to be a mistake in my hash function 😅

**Comment by rebron** [comment]
Closing per last comment.
