### ISSUE TITLE
edit new tab page

### ISSUE THREAD

**Issue by g-hill** [brave/brave-browser#4182]
## Description 

Cannot find files to edit layout (local) of new tab page

## Steps to Reproduce

   1. 
   2. 
   3. 

## Expected result:
Looking to edit new tab page. Layout and text, fonts, etc.

## Brave version (brave://version info)

latest

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
Hey there @g-hill - are you wanting to make code changes to the new tab page? If so, maybe I can help you get started 😄 

- We have build instructions up at https://github.com/brave/brave-browser/wiki
- The code itself is going to be at https://github.com/brave/brave-core/tree/master/components/brave_new_tab_ui
- `brave-core` depends on the `brave-ui` library, which has pre-build components we use: https://github.com/brave/brave-ui
- you can see a demo of `brave-ui` running here: https://brave.github.io/brave-ui/?path=/story/components--button

If you're NOT wanting to make code changes and are just asking about (as a user) being able to customize it some more, I'd like to share the issue we have tracking that:
https://github.com/brave/brave-browser/issues/353

That would be a good one to subscribe to- feedback is very much appreciated

@cezaraugusto, @karenkliu, @rebron and others will be working on that new tab experience pretty soon

In addition to that, you should be able to change your new tab experience by installing extensions which override the new tab page. Whatever the case is, please let me know! Happy Braving 😄
