### ISSUE TITLE
Handle assign in signing of signature requests

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#41820]
iOS UI implementation for https://github.com/brave/brave-browser/issues/41219

cc: @onyb @kdenhartog @nuo-xu

**Comment by kjozwiak** [comment]
The above requires `1.70.132` or higher for `1.70.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.1 running 1.70 (132) 
- Verified steps from [brave/brave-core#26198](https://github.com/brave/brave-core/pull/26198)
- Verified warning message is shown when trying to submit transaction

https://github.com/user-attachments/assets/7b0c12ad-8f8b-42bb-b991-37e492b62604
