### ISSUE TITLE
Vertical tabs - cant right click on empty space for options like New tab, reopen closed tab, etc

### ISSUE THREAD

**Issue by sarath11kb** [brave/brave-browser#41825]
### Description

While using vertical tabs, you are not able to right click on the empty spaces in the vertical tab space. 

### Steps to reproduce

1. Enable vertical tabs
2. Navigate to any empty space below the tabs
3. Try to right click.
4. You can observe no options show up.
5. Navigate cursor to any empty space on top . Example: space between reload button and bookmarks button. 
6. You can observe options menu show up.

### Actual result

1. In above Steps to reproduce - during Step 4 , no menu will show.

### Expected result

1. In above Steps to reproduce - during Step 4 , a menu should be visible.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

`1.70.126 Chromium: 129.0.6668.100 (Official Build) (arm64) `

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

- Not sure if vertical tabs are present in latest chrome.

**Comment by jagadeshjai** [comment]
Checking...

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using

```
Brave | 1.75.145 Chromium: 132.0.6834.57 (Official Build) nightly (64-bit)
-- | --
Revision | 4ecdecd1626892f9f317e9d8154c50cf8459d3bf
OS | Windows 11 Version 24H2 (Build 26100.2605)
```


Reproduced the issue in `1.73.104 Chromium: 131.0.6778.204` using the STR from issue [description](https://github.com/brave/brave-browser/issues/41825#issue-2608141534)

<details>

https://github.com/user-attachments/assets/b5c68a42-6fb6-47fc-a739-9d26e04d79b2

</details>

Confirmed context menu is shown when right clicked on empty spaces in the vertical tab view


https://github.com/user-attachments/assets/d01a9076-fa19-4910-ba65-c763895c50bf
