### ISSUE TITLE
[iOS/VPN] VPN Region Changed modal is stuck when user quickly navigates back to settings

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#41831]
### Description

@timchilds reported
VPN Region Changed modal is stuck when user quickly navigates back to settings

### Steps to reproduce

1. Enable VPN (when previously set to NOT automatic server)
2. Switch to Automatic server
3. Quickly tap back before connection established
4. Region change modal appears

### Actual result

region modal is stuck. Can't do anything in the app without restarting.

### Expected result

region modal disappears after seconds

### Reproduces how often

Easily reproduced

### Brave version

1.69.2

### Device/iOS version

all versions

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.2` using version `1.75 (115)`

* Ensured that modal is not stuck when quickly navigating back to settings menu using STR in https://github.com/brave/brave-browser/issues/41831#issue-2608874555

https://github.com/user-attachments/assets/2ead8cb7-bb74-41aa-8c49-b6334e1c8e5b
