### ISSUE TITLE
[iOS/Wallet] Transaction Activity Tab is fetching NFT metadata using duplicate nft_id

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#41839]
When user has multiple NFT transactions have involve the same NFT, wallet will fetch metadata using the an array of the same nft_id. But we should just send one nft_id since they are all the same. This will cause core return nullptr which will cause a mojom crash. 
A backend enhancement will be addressed in issue https://github.com/brave/brave-browser/issues/41829

**Comment by kjozwiak** [comment]
The above requires `1.71.120` or higher for `1.71.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.1 running 1.71 (120)
- Verified steps from [brave/brave-core#26174](https://github.com/brave/brave-core/pull/26174)
- Verified no crash when opening activity list for same NFT transactions
- Verified able to open NFT transactions from the list

https://github.com/user-attachments/assets/b899062b-3c57-4cb9-8a75-3cc6f2482463
