### ISSUE TITLE
Coachella on YouTube Requires Fingerprinting

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#4184]
## Description 
_Device Recognition_ required for https://www.youtube.com/user/coachella

## Steps to Reproduce
Visit https://www.youtube.com/user/coachella

## Actual result:
User is presented with a link to download Chrome.

![image](https://user-images.githubusercontent.com/815158/56475378-f14a9600-644c-11e9-8263-f0d4c113f0ce.png)
![image](https://user-images.githubusercontent.com/815158/56475385-235bf800-644d-11e9-8296-8a7b4a84eee1.png)

## Expected result:
User is shown the media/content.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
0.62.51

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  No

## Miscellaneous Information:
Allowing _Device Recognition_ resolves the issue.

**Comment by ryanbr** [comment]
Do you need to be logged in? Checked from a US and UK VPN; I couldn't reproduce the fingerprinting message. Is still an issue?

Tested in Brave 0.64 and Version 0.68.6

**Comment by ryanbr** [comment]
Hey @jonathansampson is this safe to close?

**Comment by pes10k** [comment]
Can't reproduce and should be sorted by farbling
