### ISSUE TITLE
Using Geolocation API leads to "Aw, Snap!" error

### ISSUE THREAD

**Issue by Igloczek** [brave/brave-browser#41859]
### Description

Any site using Geolocation API leads to crashing the whole tab with "Aw, Snap" error.

google.com is using this API on the search results view, so any search leads to a broken tab, which forced me to change the search engine, which is pretty annoying.

### Steps to reproduce

1. Open any website using the Geolocation API, for example: [W3C HTML Geolocation API Docs](https://www.w3schools.com/html/html5_geolocation.asp) and click "Try It". 
2. You will get "Aw, Snap!" error.

### Actual result

"Aw, Snap!" error page.

### Expected result

No crash and working Geolocation API.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.71.118 Chromium: 130.0.6723.70 (Official Build) (arm64)
Revision | d29310b051bde8ba041cd7b4edcb41ce951be12c
OS | macOS Version 15.0.1 (Build 24A348)

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

It was introduced this week, so I believe v1.71.114 was the first affected version, since I just did the update to 1.71.118 a few minutes ago.

- It's crashing both in standard and incognito tabs.
- Works fine on Intel-based macOS systems.
- Works fine on clean Chrome 130.0.6723.69, same as other Chromium-based browsers, like Arc.

**Comment by rebron** [comment]
@Igloczek Did you get a permission prompt after you selected Try it?
![Image](https://github.com/user-attachments/assets/5cad48af-2e28-4528-86c9-a2e97377b208)

Also wanted to check to see if you still had this setting set to the (recommended) one?
brave://settings/content/location

**Comment by Igloczek** [comment]
@rebron 
Yes, when I visit the site for the first time, I get the permissions prompt, the tab crashes right after I click "Allow". 

In other cases, let's say take the Google as an example, I already had the permission given a long time ago, so it didn't ask me for it, but still, the tab is crashing.

Yes, I do have it on "Collapse unwanted requests (recommended)" setting.
Just for the sake of testing it, tried the 2 other settings, resetting the permission each time, no difference, besides the expected change in the UI behavior.

**Comment by rebron** [comment]
related: https://github.com/brave/brave-browser/issues/41871

**Comment by iefremov** [comment]
@Igloczek can you pls upload dumps from brave://crashes and share their ids? Also, do you use wired internet connection or wifi?

**Comment by iefremov** [comment]
@Igloczek thanks for the report, it was pretty helpful. We will ship the fix soon

**Comment by LaurenWags** [comment]
cc @rebron to update labels if needed

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.71.121 Chromium: 130.0.6723.91 (Official Build) (64-bit)
-- | --
Revision | 4f0f61781aeffc3842565931be77ac3e18032066
OS | Windows 10 Version 22H2 (Build 19045.5011)

```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.71.121 Chromium: 130.0.6723.91 (Official Build) (x86_64)
-- | --
Revision | 4f0f61781aeffc3842565931be77ac3e18032066
OS | macOS Version 14.7 (Build 23H124)
```

**Comment by Igloczek** [comment]
That's a neat observation about the wifi, I indeed have it turned off.
