### ISSUE TITLE
More info icon is missing on Leo Add model label

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#41853]
### Description

More info icon is missing on Leo Add model label 

### Steps to reproduce

1. Open settings
2. Select Leo
3. Label more info icon is missing

### Actual result

![Image](https://github.com/user-attachments/assets/3f2b39ff-c049-4c10-86ef-5310f6266bbe)

### Expected result

Should show the info button

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.72.85 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | 2c872aa4d2694bc73ec58e3b14538a4008a6381e
OS | All

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @fallaciousreasoning @rebron

**Comment by fallaciousreasoning** [comment]
cc @jonathansampson did you notice this?

**Comment by jonathansampson** [comment]
@fallaciousreasoning I don't recall seeing that. I'll check it out ASAP though.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.3 Chromium: 131.0.6778.39 (Official Build) beta (64-bit)
-- | --
Revision | 0ce9628041e549979e5c522f7ec10ee1f5470182
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from issue description
- Verified more info button is shown in Add Leo model settings

![Image](https://github.com/user-attachments/assets/3fff6379-6f62-411d-a80e-4a9593a4d817)
