### ISSUE TITLE
Browser crash when closing News opt-in message on new tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#41858]
### Description

Browser crash when closing New opt-in message on new tab

### Steps to reproduce

1. Clean install browser
2. Open new tab
3. Click on `X` button on the news opt-in message
4. Browser crashes
5. Restart browser, News opt-in message is dismissed

### Actual result
Browser crash when closing New opt-in message on new tab

### Expected result

No crash 

### Reproduces how often

Easily reproduced

### Brave version

All

### Device/iOS version

iPhone 13 with iOS 18.1

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

cc: @kylehickinson @hffvld @Uni-verse @kjozwiak @StephenHeaps

**Comment by Uni-verse** [comment]
Not reproducible on iPhone / iOS 17.7

**Comment by kjozwiak** [comment]
The above requires `1.70.133` or higher for `1.70.x` verification 👍
