### ISSUE TITLE
I found that Brave browser has some strange screenshot behaviors, I suspect there is malicious code in it

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#41856]
### Description

1

### Steps to reproduce

Malicious behavior detection software

### Actual result

Detecting screenshot behavior

### Expected result

No screenshots ever

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.71.118 Chromium: 130.0.6723.70 (正式版本) （64 位） 

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by catfluoride** [comment]
You should give more details.

**Comment by rebron** [comment]
@dontseeback What OS are you running? Are you talking about screensharing permissions?

**Comment by I-I-IT** [comment]
Give proof or this is FUD.

**Comment by catfluoride** [comment]
> > Give proof or this is FUD.
> 
> Boring, you can't test it yourself. You are just fooling yourself, it's boring

Obvious troll.

**Comment by bsclifton** [comment]
There's not enough information here to do anything. Closing issue as invalid
