### ISSUE TITLE
Update automatic selection of the server for VPN

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#41869]
This is to update the automatic server selection. 
Currently when user taps on `automatic`, we use `country` as the region precision and because of that it doesn't consider the timezone for the server selection. 
After discussing the change with guardian team, we decided to update the region precision for `automatic` to `default`. 

**Existing scenario**
If you are in the mountain timezone, with the `automatic` selection, vpn tunnel connects to any other server for EST timezone as it's the fallback timezone. ideally it should select `Denver`.

**Comment by kjozwiak** [comment]
The above requires `1.72.96` or higher for `1.72.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240925.009 release-keys
Brave build: 1.72.96 
Chromium: 131.0.6778.24 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/26210#issue-2612521669
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Denver` server is selected by default when device `Time zone` is set to `Denver (GMT -7:00)`.
- Verified that the `Denver` server is still selected when the `Automatic` server toggle switch is OFF, but another city or `Optimal` is not chosen.
- Verified that `Denver` is set again after `disabling`/`enabling` `Automatic` server toggle switch.
- Verified that the same works as expected when the device `Time zone` is set to `Chicago (GMT -6:00)`, then Brave `VPN` is getting set to `Optimal - Chicago, IL`.

---------------------------

`Denver (GMT -7:00)`

https://github.com/user-attachments/assets/214cbe71-3310-456d-a098-93fe112e1f9a

`Chicago (GMT -6:00)`

https://github.com/user-attachments/assets/e19d85a3-709c-40a2-88b1-b5525d24a8c2
