### ISSUE TITLE
Fix Sign Typed Data V3 and Sign Typed Data V4  on Trezor devices

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#41864]
Doesn't work for devices newer than T1B1

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.5 Chromium: 131.0.6778.69 (Official Build) beta (64-bit)
-- | --
Revision | fbd7c390a7daa54f1aac2c769076d3fecf7c7fc7
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from [brave/brave-core#26165](https://github.com/brave/brave-core/pull/26165)
- Verified `Sign Typed Data V3` and `Sign Typed Data V4`  transactions work with Trezor hardware wallet accounts

https://github.com/user-attachments/assets/1f7e5629-1217-4007-9b57-59d7a3b7f6d8
