### ISSUE TITLE
Tokens are not redeemed for viewed Ads at server side when passing --rewards=debug=true command-line arg

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#4186]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/3659
Tokens are not redeemed for viewed Ads at server side

## Steps to Reproduce

   1.  Clean profile 0.63.46
   2.  Launch the browser through command line using `C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe --enable-logging --logging-level=2 --vmodule=brave_ads=3 --brave-ads-production --rewards=staging=false --rewards=debug=true`
   3. View couple of Ads
   4. Close the browser
   5. Wait for 25 mins
   6. Get the Payment ID from `Ledger_state` 
   7. Search redemed token records using Payment ID
  
Note:  BraveBeta 0.63.44 - Tokens are redeemed for the viewed ads at the server side, confirmed by @amirsaber 

## Actual result:

Redeemed token records are empty at the server side

Payment id: "5c53d8f3-0bd4-4830-a7e9-b5bb96e60b61"

[chrome_debug.log](https://github.com/brave/brave-browser/files/3103083/chrome_debug.log)

## Expected result:
Redeemed token records should be available in DB table

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.63.46 Chromium: 74.0.3729.91 (Official Build) (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? Not verified
- Can you reproduce this issue with the nightly channel? Not verified

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

 @amirsaber: Thanks for checking records at the server side
@brave/legacy_qa @tmancey

**Comment by tmancey** [comment]
Steps to reproduce (on any platform across all build channels)

- Launch browser with `--rewards=debug=true` command-line arg
- View some Ads
- Close the browser
- Wait for ~25 minutes
- Launch the browser

Expected result:

Tokens are redeemed with the Ads service

Actual result:

Tokens are not redeemed and the timer resets to ~25 minutes

NOTES: If the user does not close the browser tokens are redeemed.

@GeetaSarvadnya can you please confirm and update the steps in the description

**Comment by GeetaSarvadnya** [comment]
@tmancey Steps are updated. The issue is arising when we use `--rewards=debug=true` flag and close browser the browser after viewing ads.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.64.68 Chromium: 74.0.3729.108 (Official Build) beta (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Windows 10 OS Build 17134.523

- Verified the STR mentioned in the description
