### ISSUE TITLE
Using Leo on a PDF file with empty page doesn't respond

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#41877]
### Description

Using Leo on a PDF file with empty page doesn't respond

### Steps to reproduce

1. Visit `https://github.com/brave/brave-core/blob/a66745378b87834b9927855a09791f8a1fa11f44/test/data/leo/text_in_image.pdf` in a new tab
2. Open Leo and summarize the page, works as expected
3. Download the file and open in new tab
4. Try using Leo to summarize, doesn't respond and suggest questions goes into infinite loading

### Actual result

Using Leo on a PDF file with empty page doesn't respond

### Expected result

Leo should work on downloaded PDF files

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.72.87 Chromium: 130.0.6723.70 (Official Build) beta (64-bit)
-- | --
Revision | d7efa3dbae2fa83142b51cea45f023f01d3eeb33
OS | Windows 11 Version 23H2 (Build 22631.4317)

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @darkdh

**Comment by darkdh** [comment]
It happens when screen ai library is not available due to constant failing component update

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.74.25 Chromium: 132.0.6834.33 (Official Build) beta (64-bit)
-- | --
Revision | 041ffab11e000929213dcdae825dba438ff8a620
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

- Reproduced the issue in 1.74.20 Chromium: 131.0.6778.108 beta (64-bit) using STR from https://github.com/brave/brave-browser/issues/41877#issue-2613528829
- `ScreenAI Library` component is shown in `New` status in `brave://components` 

<details>

example | example 
---- | -----
![Image](https://github.com/user-attachments/assets/8970142c-2b5b-4497-a406-273e8bbdb494)|![Image](https://github.com/user-attachments/assets/b2e925f4-182f-40c4-8913-582240b81c28)
</details>

- Confirmed when Leo summarized downloaded PDF files
- Confirmed `ScreenAI Library` component is not show `brave://component`

<Details>

example | example | example 
----- | ------ | -----
![Image](https://github.com/user-attachments/assets/31eba5f8-2348-4564-8edc-13d6c5ef596f)|![Image](https://github.com/user-attachments/assets/e47494cb-a02b-4028-a562-84bce14b90b6)|![Image](https://github.com/user-attachments/assets/61b30fe2-cce5-4d39-86ea-3430d43c499c)

</Details>

**Comment by LaurenWags** [comment]
Removed `QA Pass-Win64` as this was uplifted. Requires `1.73.102` or higher for verification 👍🏻

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.73.102 Chromium: 131.0.6778.139 (Official Build) (64-bit)
-- | --
Revision | 6806ad35635fe0ddfd23411347211aa34c59a8d4
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

Verified the issue using STR from the description https://github.com/brave/brave-browser/issues/41877#issue-2613528829

- Confirmed when Leo summarized downloaded PDF files
- Confirmed `ScreenAI Library` component is not shown `brave://component`


example | example | example | example
----- | ------ | ----- | ----
![Image](https://github.com/user-attachments/assets/3e5b4454-8498-43d1-9411-2b4b42035f53)|![Image](https://github.com/user-attachments/assets/7ef14bcb-75e5-4e68-bb7a-0d8e145edd85)|![Image](https://github.com/user-attachments/assets/9414b1ba-3d79-474b-8487-22727678f30c)|![Image](https://github.com/user-attachments/assets/1634cacb-cffb-4735-b254-e049c4079fa5)
