### ISSUE TITLE
"Sorry! Ads are not supported for this region" message will not be shown in some criteria

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#4187]
## Description 

"Sorry! Ads are not supported for this region" message will not be shown in some criteria

## Steps to Reproduce

   1. Clean profile `0.63.46`
   2. Set OS region to Ads not supported country ( e.g I have set it to India)
   3. Run ipleak.net to check IP ( my ip is set to India)
   4. Set OS locale to English(United States)
   5. Launch brave 
   6. Enable Rewards
   

## Actual result:

For `India` Region - Not getting "Sorry! Ads are not supported for this region" message

![image](https://user-images.githubusercontent.com/38657976/56718263-11839900-675c-11e9-807c-dd5e72331fc8.png)

## Expected result:
When IP address criteria itself fails, the message should be shown.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.63.46 Chromium: 74.0.3729.91 (Official Build) (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
@tmancey  Even after page reload and browser restart "Sorry! Ads are not supported for this region" message" is not shown for Region `India`

**Comment by tmancey** [comment]
Microsoft recommend using https://docs.microsoft.com/en-us/windows/desktop/intl/locale-sname to retrieve the locale. Microsoft must be using a multitude of settings to determine the locale, i.e. en_US which is out of control.

**Comment by tmancey** [comment]
@GeetaSarvadnya @fmarier Can you please test latest nightly build as this was resolved in https://github.com/brave/brave-browser/issues/4224

**Comment by fmarier** [comment]
It now works for me in Beta:

```
Brave | 0.64.72 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Linux
```

**Comment by GeetaSarvadnya** [comment]
IP (India) + Locale (English (US)) -  Ads will not be served as Region is set to ads not supported region and message "Sorry! Ads are not supported for this region" is NOT displayed which is as expected. 

Hence closing the issue.
