### ISSUE TITLE
[iOS] HF Translation for 1.70.1

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#41879]

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18` using version `1.70.133`

Using test plan in https://github.com/brave/brave-core/pull/26220#issue-2613814241

* Ensured that warning message is localized on the pending transaction screen.

example | example | example
---|---|---
![Image](https://github.com/user-attachments/assets/b6c08e22-a5aa-40aa-a2a9-dcdb03b7342c) | ![Image](https://github.com/user-attachments/assets/9b49351f-f1d6-45d0-a0f6-9dde79175730) | ![Image](https://github.com/user-attachments/assets/a70bfce9-9dd7-4fed-a6bf-495f9f676168)
