### ISSUE TITLE
[iOS] - VPN allows installing profile even when not purchased

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#41887]
### Description

- VPN will prompt to install profile if you Restore subscription multiple times, even if never purchased

### Steps to reproduce

1. Go to VPN purchase screen from the 3-dot menu
2. Press Restore
3. See an Error
4. Press Restore again

### Actual result

- See install VPN profile screen

### Expected result

- Should give an error no matter how many times you press restore.

### Reproduces how often

Easily reproduced

### Brave version

- All

### Device/iOS version

- iPhone

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7.2
Brave build: 1.74 (13)
BraveCore: 1.74.13 (131.0.6778.85)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41887#issue-2614251444
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `VPN subscription` can't be `restored` if no active subscription is present.

---------------------------

https://github.com/user-attachments/assets/93014c3b-92b6-4cc4-909d-5d3c783c673b
