### ISSUE TITLE
1.70 Night mode not working on old.reddit.com and community.brave.com

### ISSUE THREAD

**Issue by hollons** [brave/brave-browser#41888]
### Description

Two user reports of 1.70 night mode not working on old.reddit.com and community.brave.com. I was able to reproduce. 

https://community.brave.com/t/night-mode-broken-on-1-70/577277
https://community.brave.com/t/new-night-mode-not-working-on-brave-community-site/577201

### Steps to reproduce

1. Go to old.reddit.com or community.brave.com on 1.70 and enable Night Mode 

### Actual result

Content is not inverted to black 

### Expected result

For the page to be dark themed 

### Reproduces how often

Easily reproduced

### Brave version

1.70

### Device/iOS version

iPhone 13 mini / 17.6.1

### Affected browser versions

- [x] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by evanrgardner** [comment]
_"Sites like [http://phoronix.com](https://t.co/qTdPWMYJ6X), [http://vuxml.freebsd.org](https://t.co/OFRQzI4OyM), [http://forums.opnsense.org](https://t.co/1KbaqVqFoe) stopped working after v1.70 with the dark mode switch, but they were fine before that, working just fine for over a year."_

**Comment by jamesmudgett** [comment]
awaiting https://github.com/darkreader/darkreader/issues/3095#issuecomment-1806145779

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18` using version `1.73 (95)`

* Ensured that Night Mode is applied to `old.reddit.com` and `community.brave.com` for new and existing users.
* Ensured that disabling Night Mode will work.

`1.71.x` | `1.73.95` 
---|---
![Image](https://github.com/user-attachments/assets/b6787ef4-6d2b-4b6a-bb3c-4f0eb816d411) | ![Image](https://github.com/user-attachments/assets/bbb2b52a-44f4-4820-801f-2eb0d17ca9b4)
![Image](https://github.com/user-attachments/assets/c72776f5-963e-44ce-b50a-4f8a014572db) | ![Image](https://github.com/user-attachments/assets/33dc746b-27c7-4fe3-9d83-27f92bb5fe97)

**Comment by abarragan-adtriba** [comment]
Hi, isnt this attached to the wrong milestone? nevertheless, wanted to ask when will this be released for iOS? Dark mode is broken in hundreds of websites. Thanks

**Comment by kylehickinson** [comment]
@abarragan-adtriba 1.73 is the next release (there won't be a 1.72). Hoping to submit to Apple by end of week
