### ISSUE TITLE
Update server selection option in settings

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#41894]
### Description

Currently with `optimal` server selection we only show `Optimal` text in the server selection option in settings. 
Based on the feedback from guardian team, we should provide more details about the connected server for the users. 

### Steps to reproduce

1. Buy vpn subscription 
2. install vpn profile
3. select `automatic` server 
4. observe settings option for server selection in `Brave Firewall + VPN`

### Actual result

![Image](https://github.com/user-attachments/assets/4d4adc81-4dc1-436f-8904-22f9d7de852a)

### Expected result

![Image](https://github.com/user-attachments/assets/dd372619-52e5-4bef-89cc-7c4ea78785fc)

### Reproduces how often

Easily reproduced

### Brave version

Release (1.71), Beta(1.72), Nightly(1.73)

### Device

- Brand/model: Google Pixle
- Android version: 15

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

For more ref : https://bravesoftware.slack.com/archives/CC5SA8CCB/p1729666472629679

**Comment by kjozwiak** [comment]
The above requires `1.72.89` or higher for `1.72.x` verification 👍

**Comment by Uni-verse** [comment]
Verified via https://github.com/brave/brave-browser/issues/41595#issuecomment-2450479467 on` Samsung Galaxy S21` running `Android 13 `
