### ISSUE TITLE
Migrate 0x Swap API to v2

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#41891]
### Description

v1 API is being sunset by EOY 2024, so we'll have to move all integrations to v2 on release before that happens.

| Migration guide | https://0x.org/docs/upgrading/upgrading_to_swap_v2 |
-|-

SafeSign fixes should land in a separate PR as it's not essential compared to the migration to v2 in time.

### Steps to reproduce

1. Go to Swap 
2. Select the From / To assets
3. Select 0x as the Provider
4. Fetch a swap quote

### Actual result

Quotes are served through the v1 router

### Expected result

0x Swaps on v2 supported chains should continue to work as expected and served via v2 routers.

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

N/A

### Android device

N/A

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [x] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.9 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | 30ceb433b8a77b995214506d3d862edb3220614b
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from issue description
- Verified 0x [Swaps ](https://etherscan.io/tx/0xc22ad320fadfabff4348dba955ebbef4234cb747147958ca70c9fd44224497a2)works as expected
- Verified Safe sign is not shown with the change as mentioned in [brave-core#26231 (comment)](https://github.com/brave/brave-core/pull/26231#issuecomment-2459418794)

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 18.1 running 1.74 (24)
- Verified steps from issue description
- Verified 0x [Swap ](https://etherscan.io/tx/0x99540738109d30dd37238a01d86560695dacbe9dd574b2147a89bfc5035474a4)works as expected
