### ISSUE TITLE
Shred intermittently not clearing all data

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#41897]
### Description

Shred is not always removing all data when a site is Shred manually from an open tab

### Steps to reproduce

1. Enable Shred feature flags in `brave://flags`
2. Open 'Settings' -> 'Shields & Privacy' -> 'Manage Website Data' and remove all data
3. Visit amazon.com
4. Shred the amazon.com tab
5. Open 'Settings' -> 'Shields & Privacy' -> 'Manage Website Data'
    - Intermittent, so may have to repeat more than once to reproduce.

### Actual result

https://github.com/user-attachments/assets/3b5b17cc-8cb7-4181-a1b4-92068724da55

### Expected result

All data is cleared from the site being Shred

### Reproduces how often

Intermittent issue

### Brave version

1.71+

### Device/iOS version

Any

### Affected browser versions

- [ ] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

cc @hffvld

**Comment by kjozwiak** [comment]
The above requires `1.71.122` or higher for `1.71.x` verification 👍
