### ISSUE TITLE
Playlist sidebar location (right) not supported [iPad]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#41893]
### Description

Playlist sidebar location (right) not supported on iPad with the new Playlist UI

May need to deprecate the setting

example | example
-|-
![Image](https://github.com/user-attachments/assets/5388f0f5-1f10-4a15-bd44-3576f38c5f42) | ![Image](https://github.com/user-attachments/assets/bed327f5-88de-4dff-8e8c-5b39bf9bedf0)

### Steps to reproduce

1. New install
2. Open video in Playlist on iPad
3. Observe sidebar is on left by default
4. Open Playlist settings, set `Sidebar Location` to `Right` 
5. Re-open Playlist

### Actual result

Setting not working

### Expected result

Fix or remove

### Reproduces how often

Easily reproduced

### Brave version

1.71.119

### Device/iOS version

iPhone, iOS 18

### Affected browser versions

- [ ] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Mini (6th gen)` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.7.2
- iPad Mini (6th gen) / iPadOS 18.1.1
Brave build: 1.74 (20)
BraveCore: 1.74.20 (131.0.6778.108)
```
---------------------------

<details>
<summary> iPhone 14 </summary>

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41893#issue-2614553678 and https://github.com/brave/brave-core/pull/26257#issue-2618679075
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the Playlist `Sidebar location` setting is hidden when `brave://flags#brave-new-playlist-ui` is ON or OFF.

---------------------------

`brave://flags#brave-new-playlist-ui` is ON

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/b28fc883-e415-4740-87fc-1ee93a2a4af6) | ![2](https://github.com/user-attachments/assets/89bf2710-9fa5-447d-9cdc-bc64fdb7cc82) | ![3](https://github.com/user-attachments/assets/a20b71e3-5fdb-4b67-ba98-94b5b6981353) |

`brave://flags#brave-new-playlist-ui` is OFF

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/07b51191-d9ba-4378-8eb2-11ad59139fad) | ![2](https://github.com/user-attachments/assets/2f1543f6-3bab-4073-8c31-9299ee4218a8) | ![3](https://github.com/user-attachments/assets/3034e6d6-bde0-4f40-b13f-61fe851672e2) |
</details>

<details>
<summary> iPad Mini (6th gen) </summary>

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41893#issue-2614553678 and https://github.com/brave/brave-core/pull/26257#issue-2618679075
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the Playlist `Sidebar location` setting is hidden when `brave://flags#brave-new-playlist-ui` is ON.
- Verified that the Playlist `Sidebar location` setting is shown when `brave://flags#brave-new-playlist-ui` is OFF.

`brave://flags#brave-new-playlist-ui` is ON

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/eb4a6a6a-f2de-45d7-9309-77128149f4b6) | ![2](https://github.com/user-attachments/assets/a61ed23b-b940-46d0-92d8-2f1254596a42) | ![3](https://github.com/user-attachments/assets/5365d111-da14-4c72-aed6-75212f692625) |

`brave://flags#brave-new-playlist-ui` is OFF

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/0a2078e1-6df3-43b9-9715-e5d4925c6c0c) | ![2](https://github.com/user-attachments/assets/fcf60857-b8aa-4efe-8318-1239e99d3e57) | ![3](https://github.com/user-attachments/assets/af13e318-de66-4a81-a072-3fea1a0d4ab6) | ![4](https://github.com/user-attachments/assets/d1e839c3-2557-474e-9d7e-af89f403e833) | ![5](https://github.com/user-attachments/assets/935857d7-ec16-47d1-9423-6e578ee05301) |
</details>
