### ISSUE TITLE
Playback speed button not working in Playlist fullscreen

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#41892]
### Description

Playback speed cant be changed in full screen on iPhone, works on iPad

Regression in new Playlist UI

### Steps to reproduce

1. New install
2. Open video site, add video to playlist
3. Open playlist
4. Enable full screen view
5. Tap on the playback speed button 

### Actual result

![Image](https://github.com/user-attachments/assets/9cf5396e-3735-4880-bac9-fbbb93fcf28d)

### Expected result

Should be able to change playback speed

### Reproduces how often

Easily reproduced

### Brave version

1.71.119

### Device/iOS version

iPhone, iOS 18

### Affected browser versions

- [ ] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kylehickinson** [comment]
This also affects the Repeat Mode button

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.0` using version `1.74 (20)`

* Ensured that playback speed button works in Playlist full screen and normal mode.
* Ensured all other controls have not regressed.

example | example | example
---|---|---
![Image](https://github.com/user-attachments/assets/40068871-5a12-4764-8f53-2f039e5c6c58) | ![Image](https://github.com/user-attachments/assets/dcf59b8b-5806-490d-b5b7-12a373534955) | ![Image](https://github.com/user-attachments/assets/094a492b-65f9-45dd-9e37-19a4b93d250c)
