### ISSUE TITLE
Shields stats is clickable even when count is 0

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#419]
## Description 

Shields stats is clickable even when count is 0
## Steps to Reproduce

   1. Visit wikipedia.org in a new tab
   2. Ensure shields shows badge as 0
   3. Open shields, you can click on all shields stats even though it shows 0

 ## Actual result:

Shields stats is clickable even when count is 0

## Expected result:
Stats in shields should not be clickable when there is nothing blocked

## Reproduces how often: 

100%

## Brave version (about:brave info)

80614db15a3b00dee5c9868c00c080a8f3a8bb31

### Additional Information
#202

**Comment by GeetaSarvadnya** [comment]
Issue is still reproduced on

Brave | 0.54.2 Chromium: 69.0.3497.42 (Official Build) dev (64-bit)
-- | --
Revision | 9c4613c66dfeb2b76ef6dd4b15884c15db3b4969-refs/branch-heads/3497@{#655}
OS | Windows
JavaScript | V8 6.9.427.14
Flash | 30.0.0.154

**Comment by cezaraugusto** [comment]
after convo with @srirambv I'm closing this in favor of #875. Thanks @GeetaSarvadnya

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

Stats are not clickable, but cursor changes. Issue reported in #875
