### ISSUE TITLE
Missing translations for Brave Ads unsupported message

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4190]
## Description 

Missing translations for ads unsupported message

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/56507061-31ae2080-64ee-11e9-9477-88b39b932f01.png)

## Expected result:
All text should be translated

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.63.45 Chromium: 74.0.3729.75 (Official Build) beta (64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
Yes- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
Yes
- Can you reproduce this issue with the nightly channel?
Yes
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
N/A
- Does the issue resolve itself when disabling Brave Rewards?
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A

**Comment by tmancey** [comment]
@anthonypkeane this ticket will need resolving to fix localization issues on the next uplift from brave-core to android

**Comment by btlechowski** [comment]
Not reproducible for bg_BG 

Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/69180032-db996e00-0b0c-11ea-80df-def365d5bfe9.png)

**Comment by tmancey** [comment]
@srirambv Can you please confirm the above language settings so I can reproduce

**Comment by LaurenWags** [comment]
Looks good with the following countries/regions. 

Brave | 1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)
-- | --
Revision | 99b6d241cf84f7fa7434ae8a59f9e74eb1464280-refs/branch-heads/3945@{#888}
OS | macOS Version 10.13.6 (Build 17G5019)

Albania/Albanian
<img width="643" alt="Albanian" src="https://user-images.githubusercontent.com/28145373/70576019-cf398b80-1b75-11ea-9f74-33aad1da68e8.png">

Hungary/Hungarian
<img width="644" alt="Hungarian" src="https://user-images.githubusercontent.com/28145373/70576026-d19be580-1b75-11ea-8eb9-e4a0e05ba5d8.png">

Thailand/Thai
<img width="646" alt="Thai" src="https://user-images.githubusercontent.com/28145373/70576032-d365a900-1b75-11ea-8030-e80738445925.png">

@srirambv what were your country/language settings for the original issue?

**Comment by srirambv** [comment]
Can't check the translations for the region from original issue as ads are available for that region now. Tried setting region to Estonia and language as Kannada for browser but system locale is overriding the text and showing in Estonian. Closing the issue for now as Estonian was also translated
