### ISSUE TITLE
Country flag and name is not aligned with title

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#41916]
### Description

Country flag and name is not aligned with title

### Steps to reproduce

1. Install VPN profile
2. Select a different server
3. Shows country/region but its not aligned with text 

### Actual result

<img widht=400 src=https://github.com/user-attachments/assets/ff8ccb5d-9ed9-4724-b387-bbc4f2a025ae>

### Expected result

Should align flag icon with title

### Reproduces how often

Easily reproduced

### Brave version

1.70 (131)

### Device/iOS version

iPhone 13 (iOS 18.1)

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

cc: @kylehickinson @bsclifton @aguscruiz @Uni-verse @hffvld @kjozwiak

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.2` using version `1.75 (115)`

* Ensured that the Country flag and name is aligned with dialog header. 

example | example
---|---
<img width="300" src="https://github.com/user-attachments/assets/1360b3d3-94ac-44d2-9793-bae25f9542b3"> | <img width="300" src="https://github.com/user-attachments/assets/2dc51ecb-2167-40d6-b72a-71c281747301">
