### ISSUE TITLE
Developer mode toggle is overlapping on the scrollbar via brave://extensions/ page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#41914]
### Description

Found while testing https://github.com/brave/brave-browser/issues/41130
Developer mode toggle is overlapping on the scrollbar via brave://extensions/ page

### Steps to reproduce

1. Clean profile 1.71.118 or 1.73.49
2. Import few extensions
3. Open brave://extensions page

### Actual result

![Image](https://github.com/user-attachments/assets/705a2c5b-b086-441c-966d-fe17bef5b128)

### Expected result

Toggle should not overlap on scrollbar

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.73.49 Chromium: 131.0.6778.14 (Official Build) nightly (64-bit)
-- | --
Revision | f70f6970d79a908b4d8f2cf70ea4576b6ff6c4ac
OS | Windows 10 Version 22H2 (Build 19045.5011)

And

Brave | 1.71.118 Chromium: 130.0.6723.70 (Official Build) (64-bit)
-- | --
Revision | d29310b051bde8ba041cd7b4edcb41ce951be12c
OS | Windows 10 Version 22H2 (Build 19045.5011)

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @emerick @rebron

**Comment by kjozwiak** [comment]
Believe the above is a dupe as the above has been known for some time now as per https://github.com/brave/brave-browser/issues/23495. Going to close the above in favor of https://github.com/brave/brave-browser/issues/23495 which has already been triaged.
