### ISSUE TITLE
Global script blocking with Private window with Tor does not work

### ISSUE THREAD

**Issue by MrBananaGuard** [brave/brave-browser#4191]
## Description 
When in Private Tor browser script blocking preferences do not work. 

## Steps to Reproduce

   1. Open Private window with Tor
   2. Go to settings by clicking the hamburger in the top right corner.
   3. Toggle the switch to enable script blocking.

## Actual result:
Scripts are still enabled.

## Expected result:
Scripts should be disabled.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Version 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)

**Comment by Brave-Matt** [comment]
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/bpchn5/brave_with_tor_and_scripts/

**Comment by Xyllon** [comment]
This is pretty important IMHO and could cause a lot of trouble if someone without knowledge of this bug gets screwed over trying to use Tor through Brave.

**Comment by yrliou** [comment]
This should be fixed now with https://github.com/brave/brave-core/pull/3319 merged.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.72.110 Chromium: 78.0.3904.70 (Official Build) dev (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

Verified test plan from the description
Verified test plan from https://github.com/brave/brave-core/pull/3319
Verified bookmarks and global settings are shared between normal and tor window.
Verified that brave://settings page is redirected to normal window.
