### ISSUE TITLE
CR131 - `My extension` and `Keyboard shortcuts` button color and mouse hover effect is inherited from chrome

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#41917]
### Description

Found while testing https://github.com/brave/brave-browser/issues/41130
CR131 - `My extension` and `Keyboard shortcuts` button color and mouse hover effect is inherited from chrome

### Steps to reproduce

1. NA

### Actual result

![Image](https://github.com/user-attachments/assets/21ba58f6-f6aa-4020-bfc8-5f581839e020)

### Expected result

![Image](https://github.com/user-attachments/assets/5fed6d09-0600-429c-963d-a2160efa4b30)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.73.49 Chromium: 131.0.6778.14 (Official Build) nightly (64-bit)
-- | --
Revision | f70f6970d79a908b4d8f2cf70ea4576b6ff6c4ac
OS | Windows 10 Version 22H2 (Build 19045.5011)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @mkarolin @emerick @brave/qa-team @rebron

**Comment by kjozwiak** [comment]
The above requires `1.72.92` or higher for `1.72.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification PASSED using
```
Brave | 1.72.93 Chromium: 131.0.6778.14 (Official Build) beta (64-bit)
-- | --
Revision | 69e5dc20ca483a13316632df5bcd9279bb2a3cb7
OS | Windows 11 Version 23H2 (Build 22631.4391)
```

Confirmed extensions sidebar (My extensions & Keyboard shortcuts) shown as expected

example | example | example 
----- | ----- | ------
![Image](https://github.com/user-attachments/assets/a1624a24-b846-46cf-bd1f-94b21d9ae06c)|![Image](https://github.com/user-attachments/assets/8acc3ec6-9583-4b68-bc04-71e8a50dec0f)|![Image](https://github.com/user-attachments/assets/1e28a12a-b4e2-4826-a322-2c5499711078)
