### ISSUE TITLE
Location name not shown on VPN Region changed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#41915]
### Description

Location name not shown on VPN Region changed

### Steps to reproduce

1. Enable VPN 
2. Switch to Singapore
3. Doesn't show the country name label

### Actual result

<img width=400 src=https://github.com/user-attachments/assets/fddea8e9-3677-4a6d-a31e-93581e22b70a>

### Expected result

Should show country name 

### Reproduces how often

Easily reproduced

### Brave version

1.70 (131)

### Device/iOS version

iPhone 13 (iOS 18.1)

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

cc: @kylehickinson @aguscruiz @Uni-verse @hffvld @bsclifton

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.2` using version `1.75 (142)`

* Ensured that location name is shown on the VPN Region Changed card when selecting `Singapore`

<img width="500" image-resolution="50dpi" src="https://github.com/user-attachments/assets/3f5fb51d-2762-4d6c-ac1e-bd937adfabf8">
