### ISSUE TITLE
There is no padding for `Usage` header section under `brave://settings/content/siteDetails...`

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#41921]
### Description

Found while testing https://github.com/brave/brave-browser/issues/41130

There is no padding for `Usage` header section under `brave://settings/content/siteDetails...`

### Steps to reproduce

1. Clean profile 1.73.43 CR 130 or 1.73.49 CR 131
2. Open any site or store cookies date
3. Open brave://settings/content/all
4. Click on '>' on any stored cookies date

### Actual result

There is no padding for `Usage` header section under `brave://settings/content/siteDetails...`

![Image](https://github.com/user-attachments/assets/ef7627ba-f967-4049-8cdc-63f72a820ed4)

### Expected result

There should be padding for `Usage` header section under `brave://settings/content/siteDetails...`

![Image](https://github.com/user-attachments/assets/54f6aa05-2c9d-4eb0-8feb-4902b26cd50c)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.73.49 Chromium: 131.0.6778.14 (Official Build) nightly (64-bit)
-- | --
Revision | f70f6970d79a908b4d8f2cf70ea4576b6ff6c4ac
OS | Windows 10 Version 22H2 (Build 19045.5011)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

The issue is reproducible on `1.73.43 CR130`

cc: @brave/qa-team @rebron

**Comment by kjozwiak** [comment]
The above requires `1.74.8` or higher for `1.74.x` verification 👍
