### ISSUE TITLE
CR131 - Disable the flag for `Allow enabling Balanced Mode for HTTPS-First Mode`

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#41933]
### Description

Found while testing https://github.com/brave/brave-browser/issues/41882.  `#https-first-balanced-mode` flag is enabled in `brave://flags` via upstream.  Disable the flag to hide `Always use secure connections` entry is shown in `brave://settings/security`.

### Steps to reproduce

1. Install 1.73.52 
2. launch Brave 
3. open brave://flags/#https-first-balanced-mode
4. open brave://settings/security

### Actual result

`Allow enabling Balanced Mode for HTTPS-First Mode` flag is shown as enabled
`Always use secure connections` entry shown as disabled in brave://settings/security

![Image](https://github.com/user-attachments/assets/11b48999-0182-4b29-8dd5-48252018d41f)|![Image](https://github.com/user-attachments/assets/e6df8e61-457c-46f3-a319-38a4f02741db)

### Expected result

Disable `Allow enabling Balanced Mode for HTTPS-First Mode` flag 

example | example 
----- | -----
![Image](https://github.com/user-attachments/assets/fc9e52ee-913f-4c2a-9ab2-cfc9edd6a670)|![Image](https://github.com/user-attachments/assets/81753a61-117a-45e7-8e62-88731c9c59f3)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.73.52 Chromium: 131.0.6778.14 (Official Build) nightly (64-bit)
-- | --
Revision | 6996738c6195caf95549bd8a9bb48be180b4b62f
OS | Windows 11 Version 23H2 (Build 22631.4391)
```

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

@emerick 

cc: @rebron @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.72.92` or higher for `1.72.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using


```
Brave | 1.72.93 Chromium: 131.0.6778.14 (Official Build) beta (64-bit)
-- | --
Revision | 69e5dc20ca483a13316632df5bcd9279bb2a3cb7
OS | Windows 11 Version 23H2 (Build 22631.4391)
```

#### Confirmed `#https-first-balanced-mode` is shown as disabled by default.
#### Confirmed `brave://settings/security` page do not show `Always use secure connections` setting

brave://flags/#https-first-balanced-mode | brave://settings/security
------ | ------
![Image](https://github.com/user-attachments/assets/d50d214d-e8d9-41cb-af9b-2478a1ca3ae1)|![Image](https://github.com/user-attachments/assets/38b20dad-3915-476c-86ea-99b9990717b6)
