### ISSUE TITLE
Padding issue in brave://settings/content/sensors page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#41939]
### Description

Found while testing https://github.com/brave/brave-browser/issues/41130
Padding issue in brave://settings/content/sensors page

### Steps to reproduce

1. NA

### Actual result

![Image](https://github.com/user-attachments/assets/57d1252a-220e-4c06-b0bf-b3610b2978be)

### Expected result

![Image](https://github.com/user-attachments/assets/f2e545ae-65ff-4dea-b4f8-9a1aabe2d224)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.73.52 Chromium: 131.0.6778.14 (Official Build) nightly (64-bit)
-- | --
Revision | 6996738c6195caf95549bd8a9bb48be180b4b62f
OS | Windows 10 Version 22H2 (Build 19045.5011)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

The issue is reproducible on `1.73.43 CR130`

cc: @brave/qa-team @rebron @aguscruiz

**Comment by aguscruiz** [comment]
This is already fixed in nightly with the redesign

![Image](https://github.com/user-attachments/assets/9da00d45-05f0-4ec2-95eb-c0a6776ec59c)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.74.8 Chromium: 131.0.6778.69 (Official Build) beta (64-bit)
-- | --
Revision | 0e56a6339728b1f1569eb3bdbe8261f2d5785d3b
OS | Windows 10 Version 22H2 (Build 19045.5131)
```
![Image](https://github.com/user-attachments/assets/98628e3b-f701-487a-9ca4-9f6eac54d058)
