### ISSUE TITLE
Disable field data fetching in DevTools and/or sending URLs to Google when it's enabled

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#41934]
### Description

Chromium allows web developers to configure field data fetching via `DevTools > Performance > Next steps > Field data > Set up`

You get the following consent screen when you press the `Set up` button:

![Image](https://github.com/user-attachments/assets/9b85b601-933c-4484-aad6-79452672180a)

This is used to compare local metric performance scores with those experienced by users in the wild ([documentation](https://developer.chrome.com/docs/devtools/performance/overview#compare))). However, enabling this feature also sends the URL of every page you visit with DevTools you visit to Google. We should disable this for privacy reasons.

We should also update https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove).

### Steps to reproduce

1. Open `DevTools > Performance > Next steps > Field data > Set up`
2. See privacy disclosure

### Actual result

You see a privacy disclosure and the URL of every page you visit is sent to Google with DevTools open if you confirm.

### Expected result

The following things should happen, in decreasing order of preference depending on easy it is:
1. Remove the "sending URLs to Google" part from the consent notice and just disable that, keeping the rest of the feature intact
2. Remove the feature all together. This means no "Field data" in `Next steps`.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

All

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [x] in the latest version of Chrome

### Miscellaneous information

cc @atuchin-m in case you have opinions on this feature as a user

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.75.130 Chromium: 132.0.6834.57 (Official Build) nightly (64-bit)
-- | --
Revision | 8cba6764764d509aef419c872a19768457d240e1
OS | Windows 11 Version 24H2 (Build 26100.2605)
```


Reproduced the issue in 1.74.41 using the STR from https://github.com/brave/brave-browser/issues/41934#issue-2619725023

#### Confirmed "Field data" feature in the `Next steps` was removed when opened `DevTools > Performance` 


1.74.41| 1.75.130 
----- | ----- 
<img width="960" alt="Image" src="https://github.com/user-attachments/assets/ac119852-e0bd-480d-b613-3d4bf7440895"/>![Image](https://github.com/user-attachments/assets/36cbb670-466f-4139-974e-8adaeed0e4ad)
