### ISSUE TITLE
[iOS] - Update Leo Yearly ID on Nightly

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#41931]
### Description

- Leo Yearly subscription ID is `nightly.braveleo.yearly` whereas on Release it is `braveleo.yearly.2` :(

### Steps to reproduce

1. Test Yearly Subscriptions

### Actual result

- Subscription doesn't work

### Expected result

- Subscription should work

### Reproduces how often

Easily reproduced

### Brave version

- 1.72.x

### Device/iOS version

- Any

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
Please wait till we have https://github.com/brave/brave-core/pull/26520 uplifted into `1.73.x` before verifying the above.

**Comment by kjozwiak** [comment]
The above requires `1.73.91` or higher for `1.73,x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7.1
Brave build: 1.73 (91)
BraveCore: 1.73.91 (131.0.6778.85)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Open `Leo`
3. Purchase a `yearly` subscription
4. Open `Dev options` > *Verify receipt/Product ID*

**ACTUAL RESULTS:**
- Verified that `Leo` `Yearly` subscription can be purchased
- Verified that `Product ID` is `braveleo.yearly.2`

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/9cd6b1ce-3ec8-4da6-9d0e-c518d25abbcd) | ![2](https://github.com/user-attachments/assets/f3cae1d1-b643-4dce-98ab-edc16c586037) | ![3](https://github.com/user-attachments/assets/bb7c0102-1ab9-4391-86f8-48abd68dea62) | ![4](https://github.com/user-attachments/assets/7b3f0a51-c3da-40bb-b2c8-29b465fee7e9) |
| ![1](https://github.com/user-attachments/assets/2a642cbc-3851-4c52-9f4d-c1a114af2e18) | ![2](https://github.com/user-attachments/assets/22d26738-63cd-449b-a8e8-98de810c0f15) | ![3](https://github.com/user-attachments/assets/d4437dac-5fb6-4346-8ecb-33a93a2432c4) | ![4](https://github.com/user-attachments/assets/49eec913-575f-47da-83e3-6968a04b4925) |
