### ISSUE TITLE
CR131 - brave://certificate-manager/crscerts is inherited from CR131 and there is a branding issue and click on learn more redirects to chrome page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#41938]
### Description

Found while testing https://github.com/brave/brave-browser/issues/41130

CR131 - brave://certificate-manager/crscerts is inherited from CR131 and there is branding issue and click on learn more redirects to chrome page

### Steps to reproduce

1. Clean profile `1.73.52 CR131`
2. Open brave://settings/security
3. Click on `Manage certificates`

### Actual result

- `Brave root store` has chrome logo instead of Brave
- Click on `Learn more` redirects to chrome page `https://chromium.googlesource.com/chromium/src/+/main/net/data/ssl/chrome_root_store/faq.md` instead of Brave support page

Example | Example
----------|-----------
![Image](https://github.com/user-attachments/assets/4c3a6804-fde5-4bb7-9b52-d48a98e2f129) | ![Image](https://github.com/user-attachments/assets/23f30322-fcfe-4776-a2b3-6a9e647594ce)

### Expected result

Should not use chrome logo and click on `learn more` link should redirects to Brave supports page

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.73.52 Chromium: 131.0.6778.14 (Official Build) nightly (64-bit)
-- | --
Revision | 6996738c6195caf95549bd8a9bb48be180b4b62f
OS | Windows 10 Version 22H2 (Build 19045.5011)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

The issue is NOT reproducible on `1.73.43 CR130` (nightly build before the CR131)

cc: @brave/qa-team @rebron @emerick @aguscruiz @mkarolin

**Comment by mkarolin** [comment]
@rebron what should we do with the `Brave Root Program` in the text there? Would it be ok to revert that back to say `Chrome Root Program`?

**Comment by fmarier** [comment]
That's a tricky one because the root store (on device) is actually using the CAs from the Chrome root _program_.

So here's what I'd recommend:
- Use "Brave Root **Store**"
- Use "Chrome Root **Program**"
- Continue to link to the Chrome Root Program FAQ

**Comment by fmarier** [comment]
> * Continue to link to the Chrome Root Program FAQ

Alternatively, we could link to https://github.com/brave/brave-browser/wiki/TLS-Policy#root-store which I've just updated to link to the root program FAQ.

**Comment by kjozwiak** [comment]
The above requires `1.74.10` or higher for `1.74.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.74.11 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | c777fe11bc7afc00156e58af64a6a5bb9559da7d
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

Verified using the STR from the issue description https://github.com/brave/brave-browser/issues/41938#issue-2620302985

- Confirmed that chrome logo is removed from the Brave Root Store option via `brave://certificate-manager/crscerts`
- Confirmed that click on `Learn more` link via `brave://certificate-manager/crscerts` redirects to https://github.com/brave/brave-browser/wiki/TLS-Policy#root-store
- Additionally, verified Brave toolbar is shown as expected for `brave://extensions`, `brave://settings pages`


example | example | example 
---- | ----- | -----
![Image](https://github.com/user-attachments/assets/98fad126-5c2b-4957-84f9-7ab1ca9e1037)|![Image](https://github.com/user-attachments/assets/f48cf7de-6bc5-4db3-b41e-e2786b7bdab7)|![Image](https://github.com/user-attachments/assets/e233228c-a9fb-440c-863e-fa740477bc5a)
