### ISSUE TITLE
Padding issue in brave://settings/content/location

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#41940]
### Description

Found while testing https://github.com/brave/brave-browser/issues/41130

Padding issue in brave://settings/content/location

### Steps to reproduce

1. NA

### Actual result

![Image](https://github.com/user-attachments/assets/cdb119d3-8885-44eb-9990-e960824acb81)

### Expected result

![Image](https://github.com/user-attachments/assets/56749607-5965-4ff2-a6db-c6dbbb592aaa)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.73.52 Chromium: 131.0.6778.14 (Official Build) nightly (64-bit)
-- | --
Revision | 6996738c6195caf95549bd8a9bb48be180b4b62f
OS | Windows 10 Version 22H2 (Build 19045.5011)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

The issue is reproducible on `1.73.43 CR130`

cc: @brave/qa-team @rebron @aguscruiz

**Comment by aguscruiz** [comment]
Solves with https://github.com/brave/brave-core/pull/26285

**Comment by aguscruiz** [comment]
Fixed in nightly with the redesign

![Image](https://github.com/user-attachments/assets/f17404a8-f1ee-4646-873e-e903106094b5)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.74.8 Chromium: 131.0.6778.69 (Official Build) beta (64-bit)
-- | --
Revision | 0e56a6339728b1f1569eb3bdbe8261f2d5785d3b
OS | Windows 10 Version 22H2 (Build 19045.5131)
```
![Image](https://github.com/user-attachments/assets/a46442f3-4750-453b-a89e-ff49a0f6db55)
