### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#41948]
### Description

crash report ID:a2975a00-9344-cf0c-0000-000000000000
crash report ID:ac975a00-9344-cf0c-0000-000000000000
Upload time:Tuesday 29 October 2024

### Steps to reproduce

n/a

### Actual result

n/a

### Expected result

n/a

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

n/a

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by iefremov** [comment]
any STR/details? the first one is real crash, but the second one is DumpWithoutCrashing

**Comment by iefremov** [comment]
```
[ 00 ] blink::internal::CrashIntentionally() ( crash_helpers.cc:23 )
[ 01 ] blink::HandleChromeDebugURL(GURL const &) ( chrome_debug_urls.cc:150 )
```

it seems like the first one is someone just entered the debug url like brave://crash/

**Comment by bsclifton** [comment]
Closing as not actionable
