### ISSUE TITLE
Track what fraction of Brave Ads system notifications sent cannot be delivered, on a per-platform basis

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#4194]
Need the ability to track the number of notifications that could not be delivered, ideally on a per-platform basis, along with the reason for our inability to show the notification client-side. 

This could be done in a more appropriate way down the road, but in the nearer term, can the ads confirmation system be harnessed to report failed notifications views as views?

**Comment by tmancey** [comment]
@davidtemkin The ability to decide the reason why notifications fail will be implemented in https://github.com/brave/brave-browser/issues/3651#issuecomment-486389026, however how this is visually shown should be completed in this ticket.

**Comment by tmancey** [comment]
Closing issue as superseded by https://github.com/brave/brave-browser/issues/9592
