### ISSUE TITLE
sync image is shown outside the frame via brave://settings/braveSync/setup

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#41942]
### Description

Found while testing https://github.com/brave/brave-browser/issues/41130

sync image is shown outside the frame via brave://settings/braveSync/setup

### Steps to reproduce

1. NA

### Actual result

sync image is shown outside the frame via brave://settings/braveSync/setup

![Image](https://github.com/user-attachments/assets/0cdbfd8a-8c59-4238-b1d5-0fd5faad19d3)

### Expected result

sync image should be shown inside the frame via brave://settings/braveSync/setup

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.73.52 Chromium: 131.0.6778.14 (Official Build) nightly (64-bit)
-- | --
Revision | 6996738c6195caf95549bd8a9bb48be180b4b62f
OS | Windows 10 Version 22H2 (Build 19045.5011)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

The issue is reproducible on `1.73.43 CR130`

cc: @brave/qa-team @rebron @aguscruiz

**Comment by aguscruiz** [comment]
Issue probably caused by the new Settings designs

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.74.8 Chromium: 131.0.6778.69 (Official Build) beta (64-bit)
-- | --
Revision | 0e56a6339728b1f1569eb3bdbe8261f2d5785d3b
OS | Windows 10 Version 22H2 (Build 19045.5131)
```
![Image](https://github.com/user-attachments/assets/f4d92b3d-cdf5-4de1-a2a4-1da146352ace) |
