### ISSUE TITLE
[Android] Open YouTube links in Brave CTA

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#41958]
### Description

Show after update (only one time) to existing users that have the youtube setting set to disabled.

- Turn on now = enable the `Open YouTube links in Brave` setting and dismiss modal
- No, thank you = dismiss modal

**Figma**
https://www.figma.com/design/BAgrUh1C7plQ9jh7WMUFoA/Youtube-on-Browser?node-id=1-2&node-type=canvas&m=dev

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 BP11.241025.006 release-keys
Brave build: 1.75.76 
Chromium: 132.0.6834.33 (Official Build) canary (64-bit) 
```

---------------------------

<details>
<summary> Open YouTube links in Brave - OFF | Open external links in Brave - ON </summary>

**STEPS:**
1. Install and launch Brave `1.73.72`
2. Hamburger menu > Settings
3. Media > Disable `Open YouTube links in Brave`
4. Go back to `Settings` > *Make sure that `Open external links in Brave` is ON*
5. Upgrade Brave to `1.75.76` or higher
6. Launch Brave > *Verify that `Watch YouTube, not Ads.` modal is shown*
7. Tap `Turn on now` > *Verify, that user is redirected to YT page*
8. Close Brave
9. Tap the YT link shared via email/messaging app > *Verify, that the YT page is opened in Brave's Webview*



**ACTUAL RESULTS:**
- Verified that the `Watch YouTube, not Ads.` modal is shown.
- Verified that user redirected to YT page when tapping `Turn on now` on the `Watch YouTube, not Ads.` modal.
- Verified that shared YT links are opened in Brave's Webview.

---------------------------

https://github.com/user-attachments/assets/b6ce7a33-9124-41ab-a7d0-3158cba27bf8
</details>

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` using version(s):
```
Device/OS: Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
Brave build: 1.75.161
Chromium: 132.0.6834.83 (Official Build) beta (64-bit) 
```
---------------------------

<details>
<summary> Tap "Turn on now" </summary>

**STEPS:**
1. Make sure that YT app is set to open supported links by `default`
2. Install and launch Brave `1.74.45`
3. Hamburger menu > Settings
4. Media > Disable `Open YouTube links in Brave`
5. Upgrade Brave to `1.75.161` or higher
6. Launch Brave > *Verify that `Watch YouTube, not Ads.` modal is shown*
7. Tap `Turn on now` > *Verify, that user is redirected to YT page*
8. In the new tab load any webpage which contains a YT link, for example, https://chromeunboxed.com/mediatek-quietly-confirmed-theyll-soon-power-a-chromebook-plus-model/
9. Tap the YT link > *Verify, that the YT page is opened in Brave*

**ACTUAL RESULTS:**
- Verified that the `Watch YouTube, not Ads.` modal is shown.
- Verified that the user is redirected to the YT page when tapping `Turn on now` in the `Watch YouTube, not Ads.` modal.
- Verified that tapping the YT link inside of Brave opens YT in Brave, but not in the YT app.

---------------------------

https://github.com/user-attachments/assets/ad4bbc31-d9fc-4337-a50a-3df583e35f66
</details>

<details>
<summary> Tap "No, thank you" </summary>

**STEPS:**
1. Install and launch Brave `1.74.45`
2. Hamburger menu > Settings
3. Media > Disable `Open YouTube links in Brave`
4. Upgrade Brave to `1.75.161` or higher
5. Launch Brave > *Verify that `Watch YouTube, not Ads.` modal is shown*
6. Tap `No, thank you` > *Verify, that no transition to a new page/screen happened*
7. In the new tab load any webpage which contains a YT link, for example, https://chromeunboxed.com/mediatek-quietly-confirmed-theyll-soon-power-a-chromebook-plus-model/
8. Tap the YT link > *Verify, that the video is opened in the YT app, but not in Brave*

**ACTUAL RESULTS:**
- Verified that the `Watch YouTube, not Ads.` modal is shown.
- Verified that the user is NOT redirected to the YT page when tapping `No, thank you` in the `Watch YouTube, not Ads.` modal.
- Verified that tapping the YT link inside of Brave opens the YT app.

---------------------------

https://github.com/user-attachments/assets/00c0a6f5-60e6-498d-916d-8b2cdc4e63d5
</details>
