### ISSUE TITLE
[Hackerone] History and Bookmarks and ShieldsPanel and 3-Dot menu URL-Eliding

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#41954]
Continuation of https://github.com/brave/internal/issues/1210 which went out via `1.70.x`.

* https://hackerone.com/reports/2790405
* https://hackerone.com/reports/2792681
* https://hackerone.com/reports/2792429

@Uni-verse @hffvld as always, please use https://github.com/brave/internal/issues/1217 for verifications 👍

**Comment by kjozwiak** [comment]
The above requires `1.71.121` or higher for `1.71.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Mini (6th gen)` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.7.1
- iPad Mini (6th gen) / iPadOS 18.0.1
Brave build: 1.71 (121)
BraveCore: 1.71.121 (130.0.6723.91)
```
------------------

Verification notes can be found [here](https://github.com/brave/internal/issues/1217#issuecomment-2448799987).
