### ISSUE TITLE
[Follow up to #41806] `Link you copied` is NOT shown when `Show browser suggestions` is OFF

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#41951]
### Description

Follow-up to #41806.

### Steps to reproduce

1. Launch Brave
2. Hamburger menu > Settings
3. Search engines > Disable `Show browser suggestions`
4. Close the settings
5. Go to any website > Tap in the URL search bar
6. Tap `Copy`
7. Open `NTP` > Tap URL search bar > *Observe that `Link you copied` is not shown*

### Actual result

`Link you copied` is NOT shown when `Show browser suggestions` is OFF.

-------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/580aa9e7-ed67-4fe5-855f-0fedbebf864c) | ![2](https://github.com/user-attachments/assets/e3f39779-f4a4-475a-a14a-e1050a506c70) | ![3](https://github.com/user-attachments/assets/7452dbe8-052e-46c3-8935-c16f3e6ba5ba) |

### Expected result

`Link you copied` must be shown when `Show browser suggestions` is OFF.

-----------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/3be13908-ac44-4930-abec-8de5b2419f24) | ![2](https://github.com/user-attachments/assets/8e9baf69-b04d-436a-b7fd-067f7f2d5133) | ![3](https://github.com/user-attachments/assets/10345b8d-4648-4f03-9dae-82d6fa1c328d) |

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.71.120
Chromium: 130.0.6723.70 (Official Build) (64-bit) 

### Device

- Brand/model: ANY
- Android version: ANY

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.71.121` or higher for `1.71.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.71.121 Chromium: 130.0.6723.91 (Official Build) (64-bit) 
Revision	4f0f61781aeffc3842565931be77ac3e18032066
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
* Verified `Link you copied` is shown in URL bar when `Show browser suggestions` is off and also on. 

`example` | `example` | `example` | `example`
---|---|---|---
![Image](https://github.com/user-attachments/assets/ab01f7ba-05e3-49c3-8a08-9f0cbf1fcc3b) | ![Image](https://github.com/user-attachments/assets/53842fc0-cf20-4f2c-a7d0-a9b92a440904) | ![Image](https://github.com/user-attachments/assets/671fa9b9-8413-49b1-b496-ca390645e729) | ![Image](https://github.com/user-attachments/assets/5ad76342-57a2-4b37-b45a-93fdb2a79a8a)
