### ISSUE TITLE
`Shared folder` can't be added to `Playlist` with new UI

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#41962]
### Description

`Shared folder` can't be added to `Playlist` with the new UI.

### Steps to reproduce

1. Launch Brave
2. Load https://playlist.brave.com/tomato90392685/
3. Tap the button to add it to the playlist > *Observe*

### Actual result

`Shared folder` can't be added to `Playlist` with the new UI. Instead `Play later` is opened only.

----------------

https://github.com/user-attachments/assets/f2f25525-57c0-48bd-ad3a-8ee4b4718e9b

### Expected result

Users must be able to add a `shared folder` to the playlist.

---------------

`Old Playlist UI`

https://github.com/user-attachments/assets/5919810e-49df-4775-8c26-16454abe08de

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.71 (120)
BraveCore: 1.71.120 (130.0.6723.70)

### Device/iOS version

- iPad Air / iPadOS 17.7
- iPhone 14 / iOS 17.7

### Affected browser versions

- [ ] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kylehickinson** [comment]
This is not a bug, it is intentionally not supported
