### ISSUE TITLE
AI Chat sidebar view should show conversation list and allow another conversation to show

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#41978]
With full-page view showing a list of conversations, those conversations should also be selectable in the sidebar. 

This UI requires the `AIChatHistory` feature flag to be enabled.

The option to show it is in the kebab menu, under "Conversation History"

![Image](https://github.com/user-attachments/assets/aece3ae2-6166-4974-92d7-aedccfb738b0)

When choosing that menu item, the list of conversations should be displayed:

![Image](https://github.com/user-attachments/assets/dcd01dc5-7a28-4cec-bddf-67fe67b2666a)

When choosing a conversation, that conversation should show in the sidebar UI, with a title on top and a back arrow button.

![Image](https://github.com/user-attachments/assets/f2a5c1bd-782b-4730-a1b1-1cd7dc03f696)

When choosing the back arrow button, the Tab's default conversation should show.

**Comment by petemill** [comment]
Completed with https://github.com/brave/brave-core/pull/25800

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/30554#issuecomment-2513707397

**Comment by LaurenWags** [comment]
Updating to `release-notes/exclude` per discussion with @srirambv as feature is currently targeted for 1.75.x
