### ISSUE TITLE
[C131] Crash in Password settings

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#41976]
### Description

There is a crash on trying to edit password and going back to password settings.

### Steps to reproduce

1. Save at least 2 passwrods
2. Go to view one of them
3. Go back to password settings, it will crash here

### Actual result

Crash

### Expected result

No crash

### Reproduces how often

Easily reproduced

### Brave version

1.73.x

### Device

- Brand/model: all
- Android version: all 

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.72.92` or higher for `1.72.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Galaxy Z Fold 6` using version(s):
```
Device/OS: Galaxy Z Fold 6 / q6quew-user 14 UP1A.231005.007 release-keys
Brave build: 1.72.93 
Chromium: 131.0.6778.14 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/41976#issue-2624337045
2. *Verify*

**ACTUAL RESULTS:**
- Verified that Brave does not crash when viewing the password and returning to the previous menu.

---------------------------

https://github.com/user-attachments/assets/2cec8138-bba2-4733-a561-32584b93183d
