### ISSUE TITLE
Add ZCash Text Memo Field on Send Screen

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#41986]
### Platforms

all, Windows, macOS, Linux

### Description

We need to add a `Memo` text field to the `Send` screen for `ZCash` shielded transactions.

![Image](https://github.com/user-attachments/assets/c2825533-34ef-434f-9bd6-b1493dbd1d0f)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.108 Chromium: 132.0.6834.46 (Official Build) nightly (64-bit)
-- | --
Revision | 2cff10e238af20f7b699d0a59b689cbe87c9c187
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps [brave/brave-core#26442](https://github.com/brave/brave-core/pull/26442)
- Verified entering a `Unified/Shielded` account address shows `Add memo` button
- Verified ZCash memo is added into `Confirmation transaction` when sending to an `Unified/Shielded` address
- Verified ZCash memo is shown in `Activity` tab

https://github.com/user-attachments/assets/f17e5847-d1c1-4092-a8e4-078ae6096ec6
