### ISSUE TITLE
[C131] [Android] Remove `New tab page cards` item from menu

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#41987]
### Description

We need to remove `New tab page cards` as it is related to upstream's NTP, not ours.
![Image](https://github.com/user-attachments/assets/e5959dea-7487-4eca-bfd4-84c8973113d6)

### Steps to reproduce

1. It appears on some devices, no real steps

### Actual result

Excessive item

### Expected result

No item

### Reproduces how often

No steps to reproduce

### Brave version

All with C131

### Device

- Brand/model: n/a
- Android version: n/a

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.72.92` or higher for `1.72.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Galaxy Z Fold 6` using version(s):
```
Device/OS: Galaxy Z Fold 6 / q6quew-user 14 UP1A.231005.007 release-keys
Brave build: 1.72.93
Chromium: 131.0.6778.14 (Official Build) beta (64-bit)
```
---------------------------

**STEPS:**
1. Launch Brave
2. Hamburger menu > Settings
3. Scroll down to the `Display` section
4. *Verify that `New tab page cards` is not shown*

**ACTUAL RESULTS:**
- Verified that `New tab page cards` is not shown under `Display` settings
- Verified the same for new install and upgrade flow

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/4a0ea785-876e-4a71-b3ed-7476b686b061) | ![2](https://github.com/user-attachments/assets/68e8ca97-a504-46bb-87ca-71e4302942b0) |
