### ISSUE TITLE
Follow up #41303: `Less than` and `Less than or equal` operators don't work for SmartNTTs

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#41998]
### Description

Follow up from #41303

### Steps to reproduce

1. Clean install
2. Close browser
3. Set matchers to:
```                    
"conditionMatchers": [{
                            "prefPath": "uninstall_metrics.installation_date2",
                            "condition": "[<]:1"
                        }
                    ],
```
4. Run Brave
5. Trigger a Smart NTT

### Actual result

Smart NTT is not shown

Console log:
```
[36445:36445:1028/210338.222010:VERBOSE1:new_tab_page_ad_serving_condition_matcher_util_internal.cc(222)] Unknown SmartNTT operator for [<]:1 condition

```

### Expected result

Smart NTT is shown

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.72.90 Chromium: 130.0.6723.70 (Official Build) beta (64-bit)
-- | --
Revision | 5f14a2225ebf4fcd654e064bde93e77fcc5d8f39
OS | Linux

cc @tmancey @aseren @iambrianfung

**Comment by tmancey** [comment]
Closing as only supported from 1.73.x

**Comment by btlechowski** [comment]
Verified with

Brave | 1.74.4 Chromium: 131.0.6778.39 (Official Build) beta (64-bit)
-- | --
Revision | 15328654b03f358466ab746b5d12a68e7fdb5017
OS | Linux

Verified test plan from the descrition

#### Less than

Used matcher:
```
"conditionMatchers": [{
                            "prefPath": "tab_stats.window_count_max",
                            "condition": "[R<]:2"
                        }
                    ],
```

Verified ad is shown

![Image](https://github.com/user-attachments/assets/c642fd81-ddcc-4ecf-8ce3-84fc8b15cf50)

#### Less than or equal


Used matcher:
```
"conditionMatchers": [{
                            "prefPath": "tab_stats.window_count_max",
                            "condition": "[R≤]:1"
                        }
                    ],
```

Verified ad is shown

![Image](https://github.com/user-attachments/assets/19dd3a12-5cff-4606-8bde-a3a18e256e50)
