### ISSUE TITLE
Network error leo byom

### ISSUE THREAD

**Issue by Remco0o** [brave/brave-browser#41997]
### Description

Hi, i added a own model(chatgpt) but everytime i got a network issue if i try to prompt a message it. But when i try a built in model it works. Any fixes for this?

(api key is provided but not for public) 

### Steps to reproduce

1.  add your own model
2. send prompt
3. got the error

### Actual result

![Image](https://github.com/user-attachments/assets/f7a49ee3-3748-4d75-bb37-f0cbbb64e7b4)

### Expected result

no network error

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

brave: 1.71.121 Chromium: 130.0.6723.91 (Official Build) (64-bit) 
Revision: 4f0f61781aeffc3842565931be77ac3e18032066
OS:  Windows 11 Version 23H2 (Build 22631.4391)

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by jonathansampson** [comment]
Can you verify how you're configuring access to ChatGPT, please?

Make sure your details are correct. For example, here is a setup for ChatGPT Mini:

| Model Request Name | Server Endpoint | API Key |
| ------------------------ | :---------------- | --------- |
| `gpt-4o-mini` | `https://api.openai.com/v1/chat/completions` | `sk*****kA` |

**Comment by Remco0o** [comment]
was api key related thank you for the help
