### ISSUE TITLE
Browser tests are failing

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#4199]
This PR broke browser tests https://github.com/brave/brave-core/pull/2296. We need to fix it

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.63.47 Chromium: 74.0.3729.108 (Official Build) (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Windows 10 OS Build 17134.523

- Verified the test plan from https://github.com/brave/brave-core/pull/1365

**Comment by kjozwiak** [comment]
We'll need to retest this once https://github.com/brave/brave-core/pull/2318 lands into `0.63.x` and a new RC3 has been created.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Ubuntu 18.04 LTS

Used test plan from https://github.com/brave/brave-core/pull/2318. Enabled rewards from panel and `brave://rewards`
