### ISSUE TITLE
Follow up #41303: `[virtual]:browser|build_channel` pref path doesn't work for SmartNTTs

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#42001]
### Description

Follow up from #41303

### Steps to reproduce

1. Clean install
2. Close browser
3. Set matchers to:
```                    
                    "conditionMatchers": [{
                            "prefPath": "[virtual]:browser|build_channel",
                            "condition": "beta"
                        }
                    ],
```
4. Run Brave
5. Trigger a Smart NTT

### Actual result

Smart NTT is not shown

Console log:
```
[19863:19863:1031/143224.216541:VERBOSE1:new_tab_page_ad_serving_condition_matcher_util_internal.cc(268)] Unknown SmartNTT [virtual]:browser key for [virtual]:browser|build_channel pref path

```

### Expected result

Smart NTT is shown

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.72.90 Chromium: 130.0.6723.70 (Official Build) beta (64-bit)
-- | --
Revision | 5f14a2225ebf4fcd654e064bde93e77fcc5d8f39
OS | Linux

cc @tmancey @aseren @iambrianfung

**Comment by tmancey** [comment]
Closing issue due to being supported in 1.73.x, thanks

**Comment by btlechowski** [comment]
Verified with

Brave | 1.74.4 Chromium: 131.0.6778.39 (Official Build) beta (64-bit)
-- | --
Revision | 15328654b03f358466ab746b5d12a68e7fdb5017
OS | Linux

Verified test plan from the descrition

Used matcher:
```
                    "conditionMatchers": [{
                            "prefPath": "[virtual]:operating_system|name",
                            "condition": "Linux"
                        }
                    ],
```

Verified ad is shown

![Image](https://github.com/user-attachments/assets/85529b38-ae94-47a4-9c3d-d1719a4b6961)
