### ISSUE TITLE
[Android] BraveSyncScreensPreference.onDevicesAvailable issues

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#42003]
### Description

There are two issues at `BraveSyncScreensPreference.onDevicesAvailable`

1. `Activity.runOnUiThread` instead Chromium counterpart  was used;
2. the try/catch block covered the code of posting thread instead the function body.

This may cause https://github.com/brave/brave-browser/issues/36190 - `Unable to sync passwords `

**Comment by kjozwiak** [comment]
This technically made it into `1.71.x` as well via https://github.com/brave/brave-core/pull/26385 but we probably won't have another `1.71.x` for `Android`. However, if we do get another `1.71.x` before `1.73.x` goes out, we'll move the following issue into the appropriate milestone.
