### ISSUE TITLE
split view mini URL view is truncating in the wrong direction

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#42011]
in the security review for split view, we asked for a mini URL view on the inactive split. when the URL is too long to fit in the entire view, it truncates from the beginning of the URL. it should instead truncate from the end so that the URL origin is visible OR only show the URL origin.

 ![Image](https://github.com/user-attachments/assets/cc9ad43e-d1b7-4b7c-b875-a70812c59eb2)

**Comment by thypon** [comment]
Alternatively we should just show the eTLD+1

**Comment by LaurenWags** [comment]
Added `QA/Test-All-Platforms` since this is a `security` issue 👍🏻 

cc @kjozwiak

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.75.159 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | a7b6f5093a2dad31fc3f56241a7d55be255e69e2
OS | Windows 11 Version 24H2 (Build 26100.2605)
```

Reproduced the issue in 1.73.61 using the testplan from https://github.com/brave/brave-core/pull/26452#issue-2642982437

![Image](https://github.com/user-attachments/assets/66dd2417-66a5-4fb6-8436-ff04cb633ff3)


1. Installed 1.75.159
2. launched Brave
3. enabled  `#brave-split-view` via `brave://flags` 
4. opened a new tab and selected `New split view` in the context view
5. loaded long url in tab 1 (https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers#:~:text=The%20original%20HTTP/1.1%20specification,%20published)
6. loaded `badssl.com` in tab 2
7. Confirmed URL origin is visible (i.e. stackoverflow.com/..)

![Image](https://github.com/user-attachments/assets/fcf7a12e-583a-43e3-8975-e9eeb8762abd)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED`
```
Brave | 1.75.159 Chromium: 132.0.6834.83 (Official Build) beta (arm64)
-- | --
Revision | a7b6f5093a2dad31fc3f56241a7d55be255e69e2
OS | macOS Version 15.2 (Build 24C101)
```


Reproduced the issue in 1.73.61 using the testplan from https://github.com/brave/brave-core/pull/26452#issue-2642982437

![Image](https://github.com/user-attachments/assets/fd2a283f-33ff-4d3d-bea0-25bef7471d8c)


1. Installed 1.75.159
2. launched Brave
3. enabled  `#brave-split-view` via `brave://flags` 
4. opened a new tab and selected `New split view` in the context view
5. loaded long url in tab 1 (https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers#:~:text=The%20original%20HTTP/1.1%20specification,%20published)
6. loaded `badssl.com` in tab 2
7. Confirmed URL origin is visible (i.e. stackoverflow.com/..)


![Image](https://github.com/user-attachments/assets/e8b262fc-5e95-4d1b-b57f-f7ea116beb92)

**Comment by btlechowski** [comment]
Verified with

Brave | 1.75.170 Chromium: 132.0.6834.111 (Official Build) beta (64-bit)
-- | --
Revision | ea6b6fa547193f9769ffb0068880a4f41e364864
OS | Linux


1. Installed 1.75.x
2. launched Brave
3. enabled  `#brave-split-view` via `brave://flags` 
4. opened a new tab and selected `New split view` in the context view
5. loaded long url in tab 1 (https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers#:~:text=The%20original%20HTTP/1.1%20specification,%20published)
6. loaded `badssl.com` in tab 2
7. Confirmed URL origin is visible (i.e. stackoverflow.com/..)

![Image](https://github.com/user-attachments/assets/de7ff65e-812e-433a-8dda-fe4f5988d606)|![Image](https://github.com/user-attachments/assets/a3418422-0725-4a6b-8376-1ab8569f3b2d)
--|--
