### ISSUE TITLE
Ads on spiegel.de

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#4201]
## Description 
Large ads fill the _above the fold_ region of https://www.spiegel.de/.

This issue was originally reported [on Twitter](https://twitter.com/sigismundf/status/1120715698723020802).

## Steps to Reproduce
1. Navigate to https://www.spiegel.de/

## Actual result:
Large ads fill the screen.

![image](https://user-images.githubusercontent.com/815158/56597698-9e8ded00-65b8-11e9-903d-d8f1f16729ea.png)

## Expected result:
Ads should not fill the screen.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
0.62.51

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
The website hosts these images, meaning they aren't third party. It doesn't use traditional links either; instead it binds a click event handler globally that inspects the target element when a click event takes place.

Ad information is stored in global objects:

![image](https://user-images.githubusercontent.com/815158/56599234-c2066700-65bb-11e9-90e2-118d9b47b40b.png)

**Comment by polent** [comment]
https://www.golem.de/ One of your registered publishers also started using the same technique. 

![image](https://user-images.githubusercontent.com/4612123/56660836-a9bc4800-66a0-11e9-913e-d3c2ccf3e312.png)

**Comment by ryanbr** [comment]
I would avoid linking directly to the sites involved to avoid tracking back. ie. wrap the url in 'code<>' on github

**Comment by snyderp** [comment]
@rebron @jonathansampson

https://github.com/brave/adblock-lists/pull/82 should fix this in the next 24 hours (its been merged in) but there are a bunch of moving pieces and difficult to replicate in Brave exactly.  Not closing this issue yet to wait and see if its fixed in 24 hours, but 🤞 this should be fixed

**Comment by ryanbr** [comment]
Golem.de will need similar fixes, i'll have something committed this week.

**Comment by snyderp** [comment]
@rebron @jonathansampson looks fixed to me, and that brave/adblock-lists#82 handled correctly.  A-ok to close?

**Comment by bsclifton** [comment]
Closing - let's re-open if it's still an issue 😄

**Comment by larseggert** [comment]
This seems to reoccur now

**Comment by ryanbr** [comment]
Yeah noticed all the whitelists just broke (looking at the Sheilds blocks), this maybe related to the adblock-rust roll out.

**Comment by rebron** [comment]
Looks good still on spiegel.de. I am seeing ads on golem.de, but let's treat that as a separate issue.

**Comment by snyderp** [comment]
@ryanbr this doesn't seem to be an adblock-rust issue.  Its due to this, right?

https://github.com/uBlockOrigin/uAssets/commit/290cdecc3224819e534fadb1cce716dd6d295cce

**Comment by ryanbr** [comment]
Okay correct, not a adblock-rust issue. Guessing we need to rethink the blocks for this site / use the snippets from uBo's filters.txt

**Comment by bsclifton** [comment]
@snyderp @ryanbr any action needed here? Should we re-open / create a new issue?

**Comment by snyderp** [comment]
I think all thats needed is a new rule from @ryanbr , either added to brave-unbreak.txt or upstream. @ryanbr can you ping here when thats done and link to the commit, and then this can be closed out

**Comment by ryanbr** [comment]
We could remove our exisiting filters (since its being overridden); ubo resolves with the following;

https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L130

`spielen.de##^script:has-text((window);)`
`spielen.de##^script:has-text(===):has-text(/[\w\W]{16000}/)`
`spielen.de##+js(abort-current-inline-script.js, Number.isNaN)`

Do we have support for $script:has-text ?

**Comment by snyderp** [comment]
I dont believe so, but im not confident.  @antonok-edm and @AndriusA would know this best

**Comment by antonok-edm** [comment]
No, and not in the upcoming `cosmetic-filters` branch either
