### ISSUE TITLE
Yandex search engine default regions are wrong

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#42023]
The original issue: https://github.com/brave/internal/issues/722

There was a typo and we were setting Yandex as the default in TZ instead of UZ

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7.2
Brave build: 1.74 (13)
BraveCore: 1.74.13 (131.0.6778.85)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/26327#issue-2627838416
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Yandex` is set as `default` SE for `Uzbekistan`
- Verified that `Google` is set as `default` SE for `Tanzania`

---------------------------

`Uzbekistan`

https://github.com/user-attachments/assets/925a7ecb-ee32-4562-b8a5-17a967977332

`Tanzania`

https://github.com/user-attachments/assets/383b3ee9-a8cb-49bb-9e27-eeadceb82f94
