### ISSUE TITLE
"Brave Ads has arrived!" notification should be shown on Linux after upgrade from 0.62.x

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#4202]
## Description
"Brave Ads has arrived!" notification should be shown on Linux after upgrade from 0.62.x

## Steps to Reproduce
   1. Install 0.62.x
   2. Upgrade to 0.63.x or above

## Actual result:
"Brave Ads has arrived!" notification was not shown on Linux after upgrading from 0.62.x

## Expected result:
"Brave Ads has arrived!" notification should be shown on Linux after upgrading from 0.62.x

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
0.63.x, 0.64.x, 0.65.x and 0.66.x

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:
`brave_ads_enabled` (https://github.com/brave/brave-core/blob/0.62.x/components/brave_ads/browser/buildflags/buildflags.gni) was set to `false` on Linux for 0.62.x

`brave_ads_enabled` (https://github.com/brave/brave-core/blob/0.63.x/components/brave_ads/browser/buildflags/buildflags.gni) was set to `true` for Linux on 0.63.x

And the upgrade path assumed this value would always be `true` for all platforms when migrating.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.64.75 Chromium: 74.0.3729.131 (Official Build) (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Linux

* Verified installing `0.62.51` and enabling rewards and upgrading to `0.64.75` shows ads is available notification
