### ISSUE TITLE
ads popup not blocked on datanodes.to

### ISSUE THREAD

**Issue by lazymonkey2** [brave/brave-browser#42028]
### Description

I have an issue with the adblocker: on the site datanodes.to there are popups that are not blocked: each time I click on the page then a popup is opened loading an ad website (which can be different, it's not always the same popup).

### Steps to reproduce

1. load https://datanodes.to/users/RomsLab/2058/3%20minutes%20Mystery%C2%A0Switch%20NSP%20Free%20Download
2. click on the link in the center of the page that starts with "3-minutes-Mystery-BASE"
3. it is opened a new page (this popup is legit and should be permitted).
4. now click anywhere on the page
5. it is opened a popup with some ads (this popup should be blocked)
6. then click on the button at bottom right part of the page called "continue to download"
7. the page is refreshed with new content
8. now click again anywhere on the page
9. a new popup is opened with some ads (this popup should be blocked too)

Please update adblocker because I don't want to see these popups with ads.

thank you.

### Actual result

popups are opened each time I interact with the pages

### Expected result

no popup with ads should be opened

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.71.121 Chromium: 130.0.6723.91 (Official Build) (64-bit)

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [x] in the latest version of Chrome

**Comment by rebron** [comment]
cc: @ryanbr @antonok-edm

**Comment by ryanbr** [comment]
Should be addressed in `Brave Ad Block Updater - Version: 1.0.8723` in brave://components or better.

**Comment by ryanbr** [comment]
Site fixed @lazymonkey2

**Comment by lazymonkey2** [comment]
yes, seems ok on brave beta. thank you.
