### ISSUE TITLE
Bug where browser window cannot be moved past chromium version 130 on fedora 40. Edit : Only if vertical tabs are enabled

### ISSUE THREAD

**Issue by r-er1309182** [brave/brave-browser#42020]
### Description

Only the window cannot be moved on current brave beta and nightly versions if vertical tabs are set on. Settings, resizing, and browsing works. I have no extensions installed. Downgrade to the latest version based on chromium 130 works. Fedora packages are all up to date. CPU is intel.

working versions :
brave nightly version : 1.73.43 
brave beta version : 1.72.87 

broken versions :
brave beta version 1.72.93
brave nightly version 1.73.64

### Steps to reproduce

1. Download the current brave nightly or beta version on Fedora 40
2. open the browser, turn on vertical tabs
3. cannot move the window

### Actual result

Window cannot be moved on the screen

### Expected result

Window should be able to be moved.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Version 1.72.93 Chromium: 131.0.6778.14 (Official Build) beta (64-bit)

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [x] in the latest version of Chrome

**Comment by rebron** [comment]
@emerick CR131 issue

**Comment by r-er1309182** [comment]
I deleted the browser cache folders and it is fixed. I'm not sure what caused it in the first place

**Comment by emerick** [comment]
cc: @mkarolin

**Comment by mkarolin** [comment]
Additional info: 
1. This relates to being able to drag the window by the toolbar (the bar with <- -> buttons and the onmibox)
2. If you turn on the "Show title bar" option for vertical tabs, you can drag the window by the title bar.

**Comment by kjozwiak** [comment]
The above requires `1.72.97` or higher for `1.72.x` verification 👍 @brave/qa-team can use https://github.com/brave/brave-core/pull/26366#issuecomment-2458020473 as a template re: verification.

**Comment by btlechowski** [comment]
Verified with

Brave | 1.73.86 Chromium: 131.0.6778.39 (Official Build) (64-bit)
-- | --
Revision | 52163bcf4e40f27ddb76ffa79c90a8833084a9bd
OS | Linux

Verified test plan from the description

Verified on Physical Machine and VM.

#### Vertical tabs - without title bar

![Image](https://github.com/user-attachments/assets/2bb4de6e-684e-4804-99ae-25cd46f7ae81)


#### Vertical tabs - with title bar

![Image](https://github.com/user-attachments/assets/0d54bce2-1c0b-457c-865b-3d57bcacf449)
