### ISSUE TITLE
[AI Chat] Persist Conversations Across Sessions

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#42037]
Requested on X (i.e., https://x.com/annadapb/status/1852529351541346307) and elsewhere, several users have expressed a desire to have conversations with Leo persisted across browsing sessions. It's worth noting that while there is presently no way to store conversation history, Brave has already shipped functionality for clearing history (see https://github.com/brave/brave-browser/issues/31441). Presumably, conversation history will be implemented somewhat differently for BYOM. Likewise, some consideration will need to be given to questions like _Is the conversation associated with a particular tab/page?_ Restoring a previous conversation from the chat history may mean we need to also stand up a previous tab/page for the purpose of continuing the discussion.

Related issues:
- https://github.com/brave/brave-browser/issues/34018
- https://github.com/brave/brave-browser/issues/31441

**Comment by petemill** [comment]
There is a combination of issues to realize this feature, and are already being tracked at:
- https://github.com/brave/brave-browser/issues/38873

Many are already merged such as introducing the `AIChatHistory` feature flag, as well as:
- https://github.com/brave/brave-browser/issues/41978
- https://github.com/brave/brave-browser/issues/30554

The implementation of storage is complete pending reviews and some privacy review required changes at:
- https://github.com/brave/brave-core/pull/25876

There is also a spec document and roadmap tracking issue.

> Presumably, conversation history will be implemented somewhat differently for BYOM

No differences needed for conversations on different models AFAIK.

**Comment by jonathansampson** [comment]
Closing this issue as there are plenty of others tracking this request and/or related work already.
