### ISSUE TITLE
In-Built Torrent Downloader

### ISSUE THREAD

**Issue by libbyslayer** [brave/brave-browser#42049]
### Platforms

all

### Description

In-Built Torrent Downloader would be helpful for many users as no need to install third party app or software.

**Comment by diracdeltas** [comment]
this exists in Brave Desktop - look for webtorrent in brave://settings > extensions.

**Comment by rebron** [comment]
@libbyslayer Please see: https://support.brave.com/hc/en-us/articles/360035025231-What-extensions-are-built-into-Brave

**Comment by libbyslayer** [comment]
once Download starts, where to see the torrent download progress?

have to reopne the same. magnet link again to see. maybe an option to see current progress, history downloads would be good
