### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Harsh-007-max** [brave/brave-browser#42045]
### Description

# Brave Browser keeps crashing in arch linux 
after a few seconds of starting brave it crashes instantly

### Steps to reproduce

1.  Run brave browser
2. 
3. 

### Actual result

Crashes in a few seconds maybe (5/ 10)

### Expected result

Brave functioning properly

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Arch Linux
brave-bin 1:1.71.121-1
installed from aur repository

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

I think its something to do with V8 engine

**Comment by bsclifton** [comment]
Unable to debug - there is no crash IDs here.

However, as this is Linux, I suspect it may be https://github.com/brave/brave-browser/issues/42315
