### ISSUE TITLE
Brave iOS doesn’t resolve some (“tweakers.net” or “news.ycombinator.com”) and instead sends them to search

### ISSUE THREAD

**Issue by ahydronous** [brave/brave-browser#42053]
### Description

Typing `tweakers.net` into the address bar does a search for that domain instead of resolving it to `https://tweakers.net`. Other domains like `news.ycombinator.com` are also affected, although something like `vkmag.com` is not.

### Steps to reproduce

1. Type `tweakers.net` in address bar, press enter

### Actual result

Brave passes of “tweakers.net” to search engine 

### Expected result

Brave processes the url and loads `https://tweakers.net`

### Reproduces how often

Easily reproduced

### Brave version

1.70.1

### Device/iOS version

iPhone 13 Mini, 18.0.1

### Affected browser versions

- [x] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [x] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kylehickinson** [comment]
Likely duplicate of https://github.com/brave/brave-browser/issues/41910

**Comment by ahydronous** [comment]
They are in my bookmarks, so definitely!
