### ISSUE TITLE
[PWA]: Revert to the old `Create shortcut`  behavior with the option to open the site as a window

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#42057]
1. Create a shortcut for a page which does **not** have a PWA (ie no `Install <site>` menu entry)
2. There should be an option on the dialog to `Open as window`

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.74.11 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | c777fe11bc7afc00156e58af64a6a5bb9559da7d
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

Issue was tested as part of https://github.com/brave/brave-browser/issues/40702#issuecomment-2492618139.  Attaching a screenshot here

![Image](https://github.com/user-attachments/assets/e711a4b0-0668-4e7f-ab82-298b77a682db)
