### ISSUE TITLE
Overlapping text on Manage search settings title

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#42058]
### Description

Overlapping text on Manage search settings title

### Steps to reproduce

1. Open settings
2. Go to Search settings and click on Manage settings
3. Text overlaps for title 

### Actual result

![Image](https://github.com/user-attachments/assets/b808dbfa-a597-4752-8c0c-bd8a55792909)

### Expected result

No overlapping texts

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.73.67 Chromium: 131.0.6778.14 (Official Build) nightly (64-bit)
-- | --
Revision | c2430cd7c3ba78db3f1ead0abd2783c1afeb1924
OS | Windows 11 Version 23H2 (Build 22631.4317)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/legacy_qa  @aguscruiz @rebron

**Comment by LaurenWags** [comment]
Requires 1.74.33 or higher for verification

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.74.33 Chromium: 132.0.6834.57 (Official Build) beta (64-bit)
-- | --
Revision | 7c275fd7e15fff5e960f2505bc49639361866c5b
OS | Windows 10 Version 22H2 (Build 19045.5247)
```
