### ISSUE TITLE
brave-browser package should depend on brave-keyring

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#4205]
We should require the `brave-keyring` package when installing `brave-browser` on Linux in order to ensure that our package/repo signing key is up-to-date.

Currently the brave-keyring package only covers the release channel.

Once that's done and has made it all the way to release, we can simply our [official installation instructions](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#release-channel-installation).

**Comment by fmarier** [comment]
Once this makes it to release, we can update the Linux installation instructions to remove mentions of `brave-keyring`.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Linux

* Verified running `sudo apt install brave-browser` installed the current stable release
![image](https://user-images.githubusercontent.com/17010094/60375611-15d86680-99d8-11e9-8d8f-8dcd277193b2.png)

*  Verified removing `brave-keyring` uninstalls brave-browser as well 
![image](https://user-images.githubusercontent.com/17010094/60375476-6b604380-99d7-11e9-9964-ebca12ac30a9.png)

Brave | 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Linux
