### ISSUE TITLE
[AI Chat]: URLs for all conversations

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#42055]
## Url variations
a. Opening FullPage Leo should be at path `/` and have a blank conversation.
b. Sending a message should change the url to `/[conversation-uuid]`
c. Refreshing should load the same conversation
d. Choosing another conversation from the navigation bar should change url to `/conversation-uuid]` (and refresh should load that same conversation)
e. Clicking the "expand" icon from SidePanel Leo should show the same conversation

## Header variations
- On FullPage Leo, the header should always be the conversation title and never show the "back" button
- On SidePanel Leo:
1. Showing a default conversation should show the regular Leo header with _no_ "back" button
2. Starting a new conversation via the side panel toolbar button should show the regular Leo header with _no_ "back" button
3. Opening a non-default conversation from the "Conversation history" menu item should show the conversation title **with** the "back" button.
4. Clicking the "back" button from that should go to the most recent default conversation for the associated tab, and should show the regular Leo header with _no_ "back" button

**Comment by diracdeltas** [comment]
can you confirm that these URLs only work within brave:// or brave-untrusted://? it would be a potential security problem if an http(s) page could link to a page within leo.

**Comment by petemill** [comment]
It's WebUI so has the same protections as any other WebUI - an http(s) page cannot link to or fetch from chrome:// or chrome-untrusted://

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.75.166 Chromium: 132.0.6834.111 (Official Build) beta (64-bit)
-- | --
Revision | 0c5da0a4df158be9400ac84df9312b627cc4dec0
OS | Windows 11 Version 24H2 (Build 26100.2894)

- Verified steps from issue description
- Verified opening Leo with blank conversation just shows `brave://leo-ai` in the URL path
- Ve4rified sending a message or starting a conversation appends `/[conversation-uuid]` to the URL path
- Verified switching between conversations updates the `[conversation-uuid]` and reloading page updates the conversation
- Verified expanding the same conversation from side panel loads the same conversation in full screen with correct `[conversation-uuid]`
- Verified there is no back button shown on conversation header when opening Leo in full page view
- Verified opening conversation history from side panel and selecting a conversation shows the back button
- Verified navigating back from Leo conversation header loads the conversation associated with the tab and removes the back button

https://github.com/user-attachments/assets/a6689567-1605-476c-ad08-71625093eee8
