### ISSUE TITLE
[Leo full page] - Tweak to expand/collapse sidebar icons

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#42068]
Based on feedback that the current icon is the same one we use on vertical tabs (true, didn't notice), I changed the icons for expanding/collapsing the sidebar to the following:

sidenav-collapse
sidenav-expand

![Image](https://github.com/user-attachments/assets/933e42f9-31fa-4804-babb-034bac62ec33)

https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/%F0%9F%94%84-Leo-%5BIN-PROGRESS%5D?node-id=15-15519

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.159 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | a7b6f5093a2dad31fc3f56241a7d55be255e69e2
OS | Windows 11 Version 23H2 (Build 22631.4602)

- Verified steps from issue description
- Verified Expand/Collapse conversation button is shown on full page view
- Verified Expand conversation has the button pointing to right
- Verified Collapse conversation has the button pointing to left
- Verified when browser window becomes narrow, conversation list collapses automatically
- Verified when collapsed, making browser window wide enough auto-expands the conversation list navigation
- Verified New conversation button is shown on the same line when conversation list is expanded
- Verified New Conversation button is shown below the side navigation button when conversation list is collapsed

https://github.com/user-attachments/assets/f1016081-3528-4add-ae7d-f9a90f8ca759
