### ISSUE TITLE
Put "block all cookies" under a default-off feature flag

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#42061]
We have a "block all cookies" feature. Unfortunately, this option essentially breaks the Web for users; we have several anecdotal cases of users inadvertently ending up with this toggle enabled. We should put this feature under a default-off but enableable feature flag (via brave://flags on all platforms). 

1. New feature flag: block-all-cookies-toggle. **Label**: `Show "block all cookies" option for global cookie setting`. **Sub-label**: `Show option to block all cookies in global cookie policy setting`.
2. (on iOS) If the feature flag is on, we show the Block all Cookies toggle. It's still default off. 
3. (on Desktop and Android) If the feature flag is on, we show the "Block all cookies" option in the "Block Cookies" setting.
4. If a user has already toggled this feature ON, we should leave as-is and have the feature flag be default ON for them. 
5. This only affects the global toggle; we should allow users to toggle per-site cookie blocking (if possible).

**Comment by rmcfadden3** [comment]
@ShivanKaul what about something like this:

Label: `Show "Block all cookies" option in Shields global defaults.`
Description: `Enables the `Block all cookies` toggle in Shields global defaults. This setting can prevent websites from storing any info about your previous visits, but is also very likely to lead to site breakage.`

**Comment by ShivanKaul** [comment]
I tweaked your text a bit, but LGTM.

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 BP11.241025.006 release-keys
Brave build: 1.75.76 
Chromium: 132.0.6834.33 (Official Build) canary (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/26479#issue-2650137513
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Block all cookies` is not shown in `global settings` when the `#block-all-cookies-toggle` flag is OFF.
- Verified that `Block all cookies` is shown in `global settings` when the `#block-all-cookies-toggle` flag is ON.
- Verified that enabling the `#block-all-cookies-toggle` flag, then selecting `Block all cookies` in the `global settings`, and then disabling the `#block-all-cookies-toggle` flag doesn't disable/hide `Block all cookies` until a user unselect it manually.
- Verified that enabling `Block all cookies` in the `global settings` also updates the `Shields` settings.

---------------------------

`#block-all-cookies-toggle` is OFF

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/3322fcab-0e51-4945-8737-b251036ae9ff) | ![2](https://github.com/user-attachments/assets/4fd74b28-d173-40b6-b13b-0852b0c1c51c) |

`#block-all-cookies-toggle` is ON

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/89da4f25-6c28-4f96-8034-6e675ba88adc) | ![2](https://github.com/user-attachments/assets/8a233be9-311d-4e91-b372-2450d0a505f5) |

`#block-all-cookies-toggle` is ON & `Block all cookies` is ON > Disable `#block-all-cookies-toggle`

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/eb63c800-ce32-4258-a37f-c9369c5809e9) | ![2](https://github.com/user-attachments/assets/8b4b1f27-8207-4b59-bc4e-5dfdd85be657) | ![3](https://github.com/user-attachments/assets/f985ae6e-49e0-4eef-8657-e7e0ddde636e) | ![4](https://github.com/user-attachments/assets/e2cc3ce3-3626-4953-b13b-00d1b67d5410) |

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.75.105 Chromium: 132.0.6834.46 (Official Build) nightly (64-bit)
-- | --
Revision | 23319880bc0dddd28b9417b78040f192738dee20
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.2` using version `1.75 (142)`

**`New Install`**

* Ensured that `#block-all-cookies-toggle` flag is disabled by default
* Ensured that Block all cookies setting is not shown in Privacy settings and enabling `#block-all-cookies-toggle` will show it after restarting.
* Ensured cookie blocking is working when enabling `Block all Cookies`. 
* Verified all cases in mentioned in https://github.com/brave/brave-core/pull/26479#issue-2650137513

**`Upgrade Case: Enabled`**

* Ensured `Block all Cookies` toggle is still shown in global settings if enabled upon upgrading. Disabling the toggle and re-opening the settings menu will hide it if the flag is set to disabled. 
* Ensured that `Block all Cookies` settings is not shown when upgrading with default settings. 

example | example | example
---|---|---
<img width="250" src="https://github.com/user-attachments/assets/304e14be-610f-4b57-9f88-c02b2e788690"> | <img width="250" src="https://github.com/user-attachments/assets/74ca0f1b-0b85-45d5-9b53-a1281fd89387"> | <img width="250" src="https://github.com/user-attachments/assets/21db1acf-a3f2-44fa-a109-ecbff1c9403e">
<img width="250" src="https://github.com/user-attachments/assets/1c8125cf-a5ff-414d-a159-c3d2a06fe501"> | <img width="250" src="https://github.com/user-attachments/assets/119515a8-b40f-407c-960a-d60d999721b6"> | <img width="250" src="https://github.com/user-attachments/assets/00d6f607-3196-4555-b3f0-3dd14c117f07">
