### ISSUE TITLE
Notify Linux users opted into Brave Rewards of Brave Ads launch

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4206]
Follow up for #2914 for Linux

Test plan : https://github.com/brave/brave-core/pull/1365

cc: @tmancey @ryanml @rebron

**Comment by btlechowski** [comment]
Already reported https://github.com/brave/brave-browser/issues/4202

**Comment by srirambv** [comment]
Thanks. closing as dupe of #4202
