### ISSUE TITLE
`http` scheme is shown in the URL bar when visiting insecure sites

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#42070]
### Description

The `http://` prefix is showing in the URL bar incorrectly when you're browsing an insecure/http site

![Image](https://github.com/user-attachments/assets/7ea4ea04-8a86-4de1-8cf4-131087c6d326)

Regressed in https://github.com/brave/brave-core/pull/26107

### Steps to reproduce

1. Visit http.badssl.com

### Actual result

Shows `http://`

### Expected result

Shouldn't show `http://`

### Reproduces how often

Easily reproduced

### Brave version

1.70+ 

### Device/iOS version

n/a

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by jamesmudgett** [comment]
@stoletheminerals needs review

**Comment by kjozwiak** [comment]
The above requires `1.73.95` or higher for `1.73.x` verification 👍 @hffvld @Uni-verse please use https://github.com/brave/internal/issues/1228 for verification similar to https://github.com/brave/brave-core/pull/26789#pullrequestreview-2470345311.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` & `iPad (9th Gen)` running `iOS 18` & `iPadOS 17.7.1` respectively using version `1.73 (95)`

* Ensured that `http://` is not displayed when loading insecure site (http://http.badssl.com).

example | example
---|---
![Image](https://github.com/user-attachments/assets/676aad20-c657-434d-a3f0-2fb4796b2a78) | ![Image](https://github.com/user-attachments/assets/99ff68d3-048c-4f65-b8a4-b89db5ca5d5d)

**Comment by Uni-verse** [comment]
Verified on `iPhone XR` and `iPad (9th Gen)` using version `1.73 (95)` per https://github.com/brave/internal/issues/1228#issuecomment-2512323459
