### ISSUE TITLE
Add Memo field to Confirm Transaction Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#42078]
### Platforms

all, Windows, macOS, Linux

### Description

After https://github.com/brave/brave-browser/issues/41986 lands we need to add a `Memo` field to the `Confirm Transaction` Panel.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.108 Chromium: 132.0.6834.46 (Official Build) nightly (64-bit)
-- | --
Revision | 2cff10e238af20f7b699d0a59b689cbe87c9c187
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps [brave/brave-core#26442](https://github.com/brave/brave-core/pull/26442)
- Verified entering a `Unified/Shielded` account address shows `Add memo` button
- Verified ZCash memo is added into `Confirmation transaction` when sending to an `Unified/Shielded` address
- Verified ZCash memo is shown in `Activity` tab

https://github.com/user-attachments/assets/f17e5847-d1c1-4092-a8e4-078ae6096ec6
