### ISSUE TITLE
Buy with provider button all shows loading state when clicking on any of them

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#42079]
### Description

Buy with provider button all shows loading state when clicking on any of them

### Steps to reproduce

1. Expand different providers on Buy Screen
2. Click on any provider
3. All buttons shows loading indicator

### Actual result

https://github.com/user-attachments/assets/cec908e9-656a-4a9f-b8ca-d493aa2969ba

### Expected result

Maybe only show loading spinner on the one that's clicked 

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.73.70 Chromium: 131.0.6778.24 (Official Build) nightly (64-bit)
-- | --
Revision | 4ee1e6a55149299c882bbe53c0fc6ef5093b0b15
OS | Windows 11 Version 23H2 (Build 22631.4317)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @Douglashdaniel @kleantzogu

**Comment by kjozwiak** [comment]
The above requires `1.74.11` or higher for `1.74.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.11 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | c777fe11bc7afc00156e58af64a6a5bb9559da7d
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from issue description
- Verified only selected provider shows loading state indicator and not on all providers

https://github.com/user-attachments/assets/69e0eea1-94ea-467e-9ddd-20759954e410
