### ISSUE TITLE
maximum daily ads at 21 instead of 20 (follow up to #3849)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#4207]
## Description 

As per https://github.com/brave/brave-browser/issues/3849, the daily limit for ads should be `20`. However, it's currently `21`. Assuming we're using `0-20` instead of `1-20`. Once you reach `21` daily ads, you'll finally receive:

```
[46648:775:0423/180021.213012:INFO:ads_impl.cc(208)] Browser state changed to idle
[46648:775:0423/180023.214693:INFO:ads_impl.cc(215)] Browser state changed to unidle
[46648:775:0423/180023.217725:INFO:ads_impl.cc(622)] Notification not made: Not allowed based on history
```

## Steps to Reproduce

   1. install a version of Brave that has `ads` and enable BR via `brave://rewards`
   2. change `Maximum number of ads displayed` to `5 ads per hour`
   3. claim the maximum amount of ads for the day (should be `20` but currently is `21`)

## Actual result:

<img width="675" alt="Screen Shot 2019-04-23 at 5 47 21 PM" src="https://user-images.githubusercontent.com/2602313/56622292-6f4d9f00-65fd-11e9-977d-88ecaca3acbd.png">

## Expected result:

Should only be `20` ads as per https://github.com/brave/brave-browser/issues/3849 instead of `21` ads.

## Reproduces how often: 

100% reproducible when going through the above STR.

## Brave version (brave://version info)

Brave | 0.63.47 Chromium: 74.0.3729.108 (Official Build) (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Haven't checked (assuming the same)
- Can you reproduce this issue with the dev channel? Haven't checked (assuming the same)
- Can you reproduce this issue with the nightly channel? Haven't checked (assuming the same)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

```
* ad #1 - received ad @ ~12:50pm - confirmed count via `brave://rewards/`
* ad #2 - recieved ad @ ~1:02pm - confirmed count via `brave://rewards/`
* ad #3 - recieved ad @ ~1:15pm - confirmed count via `brave://rewards/`
* ad #4 - recieved ad @ ~1:28pm - confirmed count via `brave://rewards/`
* ad #5 - recieved ad @ ~1:41pm - confirmed count via `brave://rewards/`
* ad #6 - recieved ad @ ~1:55pm - confirmed count via `brave://rewards/`
* ad #7 - recieved ad @ ~2:19pm - confirmed count via `brave://rewards/`
* ad #8 - recieved ad @ ~2:38pm - confirmed count via `brave://rewards/`
* ad #9 - recieved ad @ ~2:50pm - confirmed count via `brave://rewards/`
* ad #10 - recieved ad @ ~3:09pm - confirmed count via `brave://rewards/`
* ad #11 - recieved ad @ ~3:27pm - confirmed count via `brave://rewards/`
* ad #12 - recieved ad @ ~3:40pm - confirmed count via `brave://rewards/`
* ad #13 - recieved ad @ ~3:54pm - confirmed count via `brave://rewards/`
* ad #14 - recieved ad @ ~4:08pm - confirmed count via `brave://rewards/`
* ad #15 - recieved ad @ ~4:26pm - confirmed count via `brave://rewards/`
* ad #16 - recieved ad @ ~4:39pm - confirmed count via `brave://rewards/`
* ad #17 - recieved ad @ ~4:54pm - confirmed count via `brave://rewards/`
* ad #18 - recieved ad @ ~5:07pm - confirmed count via `brave://rewards/`
* ad #19 - recieved ad @ ~5:19pm - confirmed count via `brave://rewards/`
* ad #20 - recieved ad @ ~5:34pm - confirmed count via `brave://rewards/`
* ad #21 - recieved ad @ ~5:48pm - confirmed count via `brave://rewards/`

ad #22 - ~6:00pm (expected):

[46648:775:0423/180021.213012:INFO:ads_impl.cc(208)] Browser state changed to idle
[46648:775:0423/180023.214693:INFO:ads_impl.cc(215)] Browser state changed to unidle
[46648:775:0423/180023.217725:INFO:ads_impl.cc(622)] Notification not made: Not allowed based on history

ad #23 - ~6:13pm (expected):

[46648:775:0423/182623.714091:INFO:ads_impl.cc(208)] Browser state changed to idle
[46648:775:0423/182630.719808:INFO:ads_impl.cc(215)] Browser state changed to unidle
[46648:775:0423/182630.722322:INFO:ads_impl.cc(622)] Notification not made: Not allowed based on history
```

**Comment by srirambv** [comment]
Issue reproduced on Linux 

Brave | 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Linux

**Comment by GeetaSarvadnya** [comment]
Reproduced on windows:
![image](https://user-images.githubusercontent.com/38657976/56647695-8349dd00-669f-11e9-86b2-9f519ae738e9.png)



Brave | 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Windows 10 OS Build 17134.523

**Comment by LaurenWags** [comment]
Reproduced on macOS

Brave | 0.63.47 Chromium: 74.0.3729.108 (Official Build) (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Mac OS X

![Screen Shot 2019-04-24 at 9 43 43 AM](https://user-images.githubusercontent.com/28145373/56664097-8039f700-6675-11e9-84fc-9245cb48b555.png)

* Sent `Default/ads_service/client.json` to @tmancey for investigation

**Comment by tmancey** [comment]
Reverted last fix as broke frequency capping

**Comment by jsecretan** [comment]
Fixes might be simple, but needs new unit tests for all the capping cases.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.2.19 Chromium: 79.0.3945.56 (Official Build) beta (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified using same file/test plan from https://github.com/brave/brave-browser/issues/6362 thanks to assistance from @tmancey ❤️ 
* Verified more than 20 ads were not shown. When attempting to view 21st ad, this was displayed in the terminal:
```
