### ISSUE TITLE
Providers for BTC/ZCash only show up when trying to select token from list and not from Portfolio

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#42083]
### Description

Providers for BTC/ZCash only show up when trying to select token from list and not from Portfolio

### Steps to reproduce

1. Create Bitcoin account
2. Select Buy from BTC token menu in portfolio
3. Buy screen shows but doesn't show message for providers
4. Repeat the same steps for ZCash, same result

### Actual result

![Image](https://github.com/user-attachments/assets/db909cc9-008d-46ea-aea5-789a1af8c096)

### Expected result

Do not show Buy option for BTC/ZCash if not supported 

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.73.70 Chromium: 131.0.6778.24 (Official Build) nightly (64-bit)
-- | --
Revision | 4ee1e6a55149299c882bbe53c0fc6ef5093b0b15
OS | Windows 11 Version 23H2 (Build 22631.4317)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @Douglashdaniel @kleantzogu

**Comment by srirambv** [comment]
This is weird. If I change tokens and go back to BTC/ZCash I get the providers list

https://github.com/user-attachments/assets/cf2df0a1-d9d4-4935-a7ee-b30b25d0e836

**Comment by kjozwiak** [comment]
The above requires `1.74.3` or higher for `1.74.x` verification 👍
