### ISSUE TITLE
Simplified view doesn't work on regular tabs

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#42087]
Something regressed and Simplified view is available on incognito tabs only, we want to uplift the fix.

Steps:
1. Enable Simplified View via `3 dots menu->Settings->Accessibility->Simplified view for web pages`
2. Open some article where the Simplified view is available, something from cnn.com should work
3. Observe that there is a dialog that proposes to view page simplified in incognito tab, but it's not there in a regular tab.

**Comment by kjozwiak** [comment]
The above requires `1.73.87` or higher for `1.73.x` verification 👍 @Uni-verse @hffvld keep in mind that https://github.com/brave/brave-browser/issues/42175 was created as a follow up so you'll need to refresh the page to get the prompt to appear. Should definitely be improved but at least it's working/being displayed in `Normal` mode as it wasn't before.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using the following version: 

```
Brave	1.73.87 Chromium: 131.0.6778.39 (Official Build) (64-bit) 
Revision	07561cfa9399fbf9e0efbeb6bce91e63b3a95063
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

* Ensured that simplified view is available in normal and incognito tabs for web pages when enabling `Simplified view for web pages`.
* Ensured theres no issues entering/exiting simplified view and using PiP for that tab.

1.73.86 | 1.73.87 | simplified view | PiP
---|---|---|---
![Image](https://github.com/user-attachments/assets/1c582a06-e5ec-4dca-8ada-a3ad2cc2b7ea) | ![Image](https://github.com/user-attachments/assets/1e033097-6752-459d-a571-73a060b9e9ad) | ![Image](https://github.com/user-attachments/assets/82631802-6480-4b04-b65a-e20bf7d3ec8e) | ![Image](https://github.com/user-attachments/assets/377d4d94-6aa6-4915-845e-63ac057ded7a)
