### ISSUE TITLE
Selecting Buy from side navigation doesn't reset providers list

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#42086]
### Description

Selecting Buy from side navigation doesn't reset providers list

### Steps to reproduce

1. Select Buy from side navigation
2. Select Solana from tokens list
3. Wait for providers to load
4. Expand all providers list
5. Click on Buy again 
6. Resets to ETH token but none of the providers are reset

### Actual result

https://github.com/user-attachments/assets/3d60507d-5225-4cc1-a91a-5150f6aea14f

### Expected result

Should reset Buy screen when clicked on the Side navigation

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.73.70 Chromium: 131.0.6778.24 (Official Build) nightly (64-bit)
-- | --
Revision | 4ee1e6a55149299c882bbe53c0fc6ef5093b0b15
OS | Windows 11 Version 23H2 (Build 22631.4317)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @Douglashdaniel @jamesmudgett @kleantzogu

**Comment by kjozwiak** [comment]
The above requires `1.74.11` or higher for `1.74.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.11 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | c777fe11bc7afc00156e58af64a6a5bb9559da7d
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from issue description and [brave/brave-core#26613](https://github.com/brave/brave-core/pull/26613)
- Verified changing token in Buy screen and clicking on Buy on side navigation resets to ETH default

https://github.com/user-attachments/assets/903c6ca1-8f5a-4a67-a2e2-91ce4c090d23
