### ISSUE TITLE
[AI Chat]: Update suggestions style to match new design

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#42107]
https://www.figma.com/design/m0Gdbf0wtqyfEFGm32VLLc/%F0%9F%94%84-Leo-%5BIN-PROGRESS%5D?node-id=4226-13767&t=WL7FRILdWtE2Rkk7-1

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.162 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | 1c01fd7f190ad7c9c88cb964f55e35400bf399ae
OS | Windows 11 Version 24H2 (Build 26100.2894)

- Verified steps from Figma
- Verified Conversation starter suggestion is centre and extended as the same size as prompt window
- Verified icon background is grey on both Light and Dark theme
- Encountered [#43381](https://github.com/brave/brave-browser/issues/43381)

<img width="1482" src="https://github.com/user-attachments/assets/a3619b70-2545-4670-b31e-ae154efb9844"> | <img width="1482"  src="https://github.com/user-attachments/assets/5652ce4f-2473-476f-ab79-b93fbc251417" > | <img width="1482" src="https://github.com/user-attachments/assets/390fb00f-b616-4b7c-b503-807e46018ed1"> | <img width="1482" alt="Image" src="https://github.com/user-attachments/assets/6f5774f9-906e-49ba-80be-3b95ea2a640d" >
-- | -- | -- | --

-------------
Verification passed on

Brave | 1.75.162 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | 1c01fd7f190ad7c9c88cb964f55e35400bf399ae
OS | Linux

- Verified steps from Figma
- Verified Conversation starter suggestion is centre and extended as the same size as prompt window
- Verified icon background is grey on both Light and Dark theme
- Encountered [#43381](https://github.com/brave/brave-browser/issues/43381)

<img width="1920" alt="Image" src="https://github.com/user-attachments/assets/5fbae408-9324-411a-b67c-417ee63ecc83"> | <img width="1920" alt="Image" src="https://github.com/user-attachments/assets/31201b84-73f2-4db9-80d1-32329a3b8c21"> |<img width="1920" alt="Image" src="https://github.com/user-attachments/assets/c12b56e7-9f39-4348-a8c1-305dfb72b751"> | <img width="1920" alt="Image" src="https://github.com/user-attachments/assets/d595f006-8880-4bab-9ff4-9216a2dea9be">
-- | -- | -- | --

-------------
Verification passed on

Brave | 1.75.162 Chromium: 132.0.6834.83 (Official Build) beta (arm64)
-- | --
Revision | 1c01fd7f190ad7c9c88cb964f55e35400bf399ae
OS | macOS Version 15.2 (Build 24C101)

- Verified steps from Figma
- Verified Conversation starter suggestion is centre and extended as the same size as prompt window
- Verified icon background is grey on both Light and Dark theme
- Encountered [#43381](https://github.com/brave/brave-browser/issues/43381)


![Image](https://github.com/user-attachments/assets/68d5dcef-d93c-474d-8ff0-2e24bc8c63d9) | ![Image](https://github.com/user-attachments/assets/0f2b1432-0625-4384-99eb-6cbd063668aa) | ![Image](https://github.com/user-attachments/assets/3eefbf73-86aa-40b2-91d8-51b638ff507f) | ![Image](https://github.com/user-attachments/assets/35579bf0-a213-4460-ae51-0f94dbab878c)
-- | -- | -- | --
