### ISSUE TITLE
[AI Chat]: Add support for static conversation starters

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#42106]
**Available Starters:**

- Write a memo
- Generate interview questions
- Create a study plan
- Create a project timeline
- Develop a marketing strategy
- Outline a presentation
- Help me brainstorm
- Craft a professional email
- Formulate a business proposal

These should only show up when there is no associated content

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.159 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | a7b6f5093a2dad31fc3f56241a7d55be255e69e2
OS | Windows 11 Version 23H2 (Build 22631.4602)

- Verified steps from issue description
- Verified conversation starter is shown on both full page view Leo and side bar Leo
- Verified reloading the page changes the conversation starter each time
- Verified visiting a website and loading Leo in side bar doesn't show conversation starter when `Use page context` is enabled
- Verified disabling `Use page context` automatically shows the conversation starter prompts 

https://github.com/user-attachments/assets/c3c6486f-bd5a-41ee-846a-3f679a301ef7
