### ISSUE TITLE
Keep separate NTT P3A events for Constellation metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#42108]
In order to deprecate JSON reporting completely for iOS, we need to maintain separate NTT event counts for Constellation reporting. The `rotated` method in `NewTabPageP3AHelper` must acknowledge Constellation rotations.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on `iPhone 8 version  16.7.10` running on `Brave Nightly 1.75 (118)`

- Verified the test plan from https://github.com/brave/brave-core/pull/20264

**Comment by GeetaSarvadnya** [comment]
@kylehickinson:  In the Step 2 above (https://github.com/brave/brave-browser/issues/42108#issuecomment-2561194300), 
For point 5, I am seeing some discrepancy with no. of metrics count shown at `star-randsrv.bsg.brave.com` server endpoint. The no.of metrics count is (3) `express` shown at `star-randsrv.bsg.brave.com` that is not matching with no. of metrics (2) shown under `logs_constellation_prep_express` and no. of metrics (2) shown under `logs_express`

`logs_constellation_prep_express` | `logs_express` |  `express`
-------------------------------------|-----------------|-------------
![Image](https://github.com/user-attachments/assets/72bf86f1-d7da-4d4c-9064-48d2c4d45b63) | ![Image](https://github.com/user-attachments/assets/1d6c9d6b-d61d-4849-8cf4-30e2fd9d51b5) | <img width="993" alt="Image" src="https://github.com/user-attachments/assets/358af2d0-7205-4f3f-90e3-afc007237b35" />


- For point 6, I am seeing some discrepancy with no. of metrics (1) shown under `logs_slow`via brave://local-state in the browser and this is not matching with the no. of metrics (2) shown under `logs_constellation_prep_slow`and no of metrics (2) `slow` instances at the `star-randsrv.bsg.brave.com` server endpoint

`logs_constellation_prep_slow` | `logs_slow` |  `slow`
-------------------------------------|-----------------|-------------
![Image](https://github.com/user-attachments/assets/b1911733-faf5-4beb-adf9-55cf5cf45866) | ![Image](https://github.com/user-attachments/assets/978f17b5-0c1d-44d1-b33f-6672d8514c16) | ![Image](https://github.com/user-attachments/assets/6c5b3439-4682-4f45-ad86-0e0147b93dad)

**Comment by DJAndries** [comment]
> In the Step 2 above ([#42108 (comment)](https://github.com/brave/brave-browser/issues/42108#issuecomment-2561194300)), For point 5, I am seeing some discrepancy with no. of metrics count shown at `star-randsrv.bsg.brave.com` server endpoint. The no.of metrics count is (3) `express` shown at `star-randsrv.bsg.brave.com`, this is not matching with no. of metrics (2) shown under `logs_constellation_prep_express` and no. of metrics (2) shown under `logs_express` via brave://local-state via browser

Are you certain that all three randomness requests were sent to `/instances/express/randomness`. Requests are usually also sent to `/instances/slow/randomness` and `/instances/typical/randomness`. If you are not certain, I encourage you to test this once more and inspect the request paths.

> For point 6, I am seeing some discrepancy with no. of metrics (1) shown under logs_slow via brave://local-state and this is not matching with the no. of metrics (2) shown under logs_constellation_prep_slow and no of metrics (2) slow instances at the star-randsrv.bsg.brave.com server endpoint

This is fine. The "primary language" metric is only sent via Constellation, so this is expected.

**Comment by GeetaSarvadnya** [comment]
@DJAndries: Thanks for the response!.

I have re-verified the STEP2 again on iOS today. I am seeing the correct path for each metrics type `typical/express/slow`.  

I can see `3` metrics reported at the `/instances/express/randomness` via `star-randsrv.bsg.brave.com` endpoint, there are `2` metrics shown under the `logs_express` block and `3` metrics shown under `logs_constellation_prep_express` block via brave://local-state file. The 3rd metrics `creative_instanceId` was  not reported earlier when I tested the issue last week, now I can see 3rd metrics `creative_instanceId` reported at `logs_constellation_prep_express` block. Looks like this is expected.

**Comment by DJAndries** [comment]
> Can you review the same? Thanks!

Yes, this looks fine. Thanks!
