### ISSUE TITLE
Avoid sending usage ping for headless clients

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#42111]
Add variation feature for marking headless clients (i.e. clients launched with the `--headless` or `--enable-automation` switch) with a special refcode (`HED001`). If the feature is disabled, avoid sending the daily usage ping for headless clients.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.75.151 Chromium: 132.0.6834.57 (Official Build) nightly (64-bit)
-- | --
Revision | f122bf6d4cf815cc56e1ba5cf1dda5e9fc20b689
OS | Windows 11 Version 24H2 (Build 26100.2605)
```

Test Case 1: Start with fresh profile, ensure request to usage-ping.brave.com is sent within 30 seconds when --headless or --enable-automation switch is set, with the ref query parameter set to HED001.

Case 1: command line flag --headless

1. Installed 1.75.151
2. launched Fiddler everywhere
3. launched Brave with command line flags `--headless`
4. ensured request to `usage-ping.brave.com` is sent within 30 seconds 
5. confirmed the ref query parameter set to HED001 

step 3 | step 4 | step 5 
------ | ------- | ------
![Image](https://github.com/user-attachments/assets/a9d5cec5-01c0-48b9-8d2e-65a610a7252e)|![Image](https://github.com/user-attachments/assets/3f25d6c1-414e-4246-8750-8a2662618754)|![Image](https://github.com/user-attachments/assets/f19d1ed2-e182-45e3-9b7d-86f9ac3725f4)

Case 2: command line flag --enable-automation

- launched Fiddler
- launched Brave with command line flags --enable-automation

example | example | example 
----- | ----- | -----
![Image](https://github.com/user-attachments/assets/91d6eedb-c9c9-4677-900a-134115b2a050)|![Image](https://github.com/user-attachments/assets/3b38e6f5-a800-4192-94df-dba528b7ca9a)|![Image](https://github.com/user-attachments/assets/96522156-e8f2-4afb-ba71-cffb453ab2df)

Test Case 2: Start with fresh profile, ensure request to usage-ping.brave.com is NOT sent within 30 seconds when --headless or --enable-automation switch is set AND the --disable-features="BraveStatsHeadlessRefcode" switch is set.

Case 1: command line flags --headless  AND --disable-features="BraveStatsHeadlessRefcode"

- launched Fiddler
- launched Brave with command line flags --headless  AND --disable-features="BraveStatsHeadlessRefcode"

confirmed with both the flags, the feature is disabled and no daily usage ping sent for headless clients

example | example 
----- | ------
![Image](https://github.com/user-attachments/assets/774b1466-8389-4c4c-a371-173d3063b66f)|![Image](https://github.com/user-attachments/assets/b8308b49-c6e5-421d-877d-e7d8a24faf72)

Case 2: command line flag --enable-automation --disable-features="BraveStatsHeadlessRefcode"

- launched Fiddler
- launched Brave with command line flags --enable-automation  --disable-features="BraveStatsHeadlessRefcode"

example | example 
----- | -----
![Image](https://github.com/user-attachments/assets/c5efa57d-fafc-4bd4-b289-152b85567a7d)|![Image](https://github.com/user-attachments/assets/ac813635-53c1-4cea-b8ee-d9a46a13b9d2)

Test Case 3: Start again with a fresh profile and ensure a request is sent when the switches are not provided, with the ref query parameter set to BRVxxx.

1. launch Fiddler
2. launch Brave without any command line arguments
3. confirmed the ref query parameter set to BRV001

example | example | example 
---- | ----- | -----
![Image](https://github.com/user-attachments/assets/65b49c19-4142-4d32-97c1-2ba4e8ba3728)|![Image](https://github.com/user-attachments/assets/b20fce34-59ff-47cc-b90c-e0132d1bad38)|![Image](https://github.com/user-attachments/assets/b4064ab3-fd04-4ca7-acd9-b67022a2e2c0)

Test Case 4: Start again with a fresh profile and ensure a request is sent when the --disable-features="BraveStatsHeadlessRefcode" switch is set, with the ref query parameter set to BRVxxx.

1. launch Fiddler
2. launch Brave without any command line arguments
3. confirmed the ref query parameter set to BRV001

example | example | example 
---- | ----- | -----
![Image](https://github.com/user-attachments/assets/3aefd193-de55-47e2-9231-77fab7961f2e)|![Image](https://github.com/user-attachments/assets/0682746a-7c7e-4827-b732-11263351fad2)|![Image](https://github.com/user-attachments/assets/c74d26c3-bd8e-46d5-b35b-0318852f0d89)
