### ISSUE TITLE
Opening Leo from search should auto populate after user agrees to opt-in

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#42112]
### Description

Opening Leo from search should auto populate after user agrees to opt-in

### Steps to reproduce

1. Clean browser profile
2. Enable flags for search and enter query
3. Add follow up questions
4. Click on save query in brave leo
5. Side panel opens and shows the opt-in message
6. Click on I understand/agree to terms
7. Doesn't auto load the search query into Leo
8. Click on summarize, does the page summary (this should not be needed IMO)
9. Click on erase/new chat button, search query loads in Leo 

### Actual result

Opening Leo from search should auto populate after user agrees to opt-in

### Expected result

Should save chat in Leo as soon as the user opts in to Leo 

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.73.75 Chromium: 131.0.6778.24 (Official Build) nightly (64-bit)
-- | --
Revision | c3d6b9bdbbdf63fc4831eb0bc8e116e9742e3852
OS | Windows 11 Version 23H2 (Build 22631.4317)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Related to https://github.com/brave/brave-core/pull/26082

cc: @yrliou @kjozwiak

**Comment by kjozwiak** [comment]
The above requires `1.74.2` or higher for `1.74.x` verification 👍

**Comment by kjozwiak** [comment]
The above requires `1.73.88` or higher for `1.73.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.73.88 Chromium: 131.0.6778.39 (Official Build) (64-bit)
-- | --
Revision | e0a230f2aab41bbd7935065107eb039f90f0ec70
OS | Windows 11 Version 23H2 (Build 22631.4317)

- Verified steps from issue description
- Verified Search query chat is shown immediately after user opts into Leo

https://github.com/user-attachments/assets/197e1574-9c21-492c-a320-0b928c00528a
