### ISSUE TITLE
Change copy button name to text if text in code block

### ISSUE THREAD

**Issue by LorenzoMinto** [brave/brave-browser#42117]
### Description

We sometimes serve text in code block to make it easy for the user to copy it and use it elsewhere. Currently the copy button still recites "Copy code".

### Steps to reproduce

Ask Leo for a limerick to copy.

### Actual result

![Image](https://github.com/user-attachments/assets/7186ea8a-69e0-4539-956d-69bad3ecfbfd)

### Expected result

Should say "Copy text" 

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

na

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.114 Chromium: 132.0.6834.46 (Official Build) nightly (64-bit)
-- | --
Revision | 2c7caf1265beb933db9dbe9db2500da09cb93620
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from issue description
- Verified Copy button text is updated from `Copy code` to `Copy`

Light | Dark
-- | --
<img width="1392" alt="Image" src="https://github.com/user-attachments/assets/693d1eb3-1db6-4671-8aec-d3aad6cea835" />|<img width="1392" alt="Image" src="https://github.com/user-attachments/assets/967c46b3-e2f0-41a9-a779-996bba2e3539" />
