### ISSUE TITLE
IPFS companion extension is not removed from `brave://components`

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#4211]
Follow up to https://github.com/brave/brave-browser/issues/3918
Found when verifying test plan from https://github.com/brave/brave-core/pull/2106

## Steps to Reproduce

   1. Clean install
   2. Open `brave://settings/?search=ipfs`
   3. Toggle `IPFS Companion` on
   4. Wait till the extension is installed
   5. Toggle `IPFS Companion` off
6. Check `brave://components/` for `IPFS Companion`

## Actual result:

`IPFS Companion` is listed in `brave://components/`

Note: Browser restart removes the extension

## Expected result:
`IPFS Companion` is NOT listed in `brave://components/` per https://github.com/brave/brave-core/pull/2106

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

cc @brave/legacy_qa @yrliou

**Comment by yrliou** [comment]
Currently per impl it will be disabled but not unloaded before restart.
This will no longer be an issue since we're changing to install it as a normal extension in https://github.com/brave/brave-core/pull/2328.

**Comment by yrliou** [comment]
Closing as not actionable since IPFS companion is not a component extension anymore in 0.64.x and later.
