### ISSUE TITLE
Remove day zero experiment changes

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#42118]
As a follow up to https://github.com/brave/brave-core/pull/24617 changes, we need to remove the client changes for day zero experiment as the experiment is over. 
In this issue, we need to reset the default pref values for the features involved in day zero experiment.

**Comment by kjozwiak** [comment]
The above requires `1.73.90` or higher for `1.73.x` verification 👍

**Comment by kjozwiak** [comment]
The above requires `1.73.90` or higher for `1.73.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.73.89 Chromium: 131.0.6778.69 (Official Build) (64-bit)
-- | --
Revision | 199634819b22eaa58d8efc35430bc8853b178074
OS | Windows 11 Version 23H2 (Build 22631.4460)
```


Using the STR/Cases mentioned via https://github.com/brave/brave-core/pull/26396#issue-2638848640, ensured that the following feature were still enabled/usable when launching `Brave` using the following:

<details>
<summary>Case 1: Launch Brave with the flags - PASSED </summary>

1. Installed 1.73.89
2. Launched Brave with cmd line `brave.exe --enable-logging=stderr --enable-features=BraveDayZeroExperiment:variant/a`
3. Confirmed that the `Rewards` & `Talk` widgets are visible/usable via NTP
4. Confirmed that the `Brave Wallet` icon is visible/usable via the toolbar
5. Confirmed that the `Brave Rewards` icon is visible/usable via the URL bar
6. Confirmed that `SNTP` are being displayed/appearing via NTP without any issues/failures
7. Confirmed that the `Brave News` opt-in card is peaking/visible when scrolling the NTP
8. Confirmed Clock widget in shown/disappear when enabled and disabled via settings

**`step 1`** | **`step 3`** | **`step 4`** | **`step 5`** | **`step 6`** | **`step 7`** | **step 8`** 
-----------|-----------|-------------|-----------|-----------| -------- | -------
![Image](https://github.com/user-attachments/assets/7648d489-e3ea-4afa-b5cc-c26fb0f02c92)|![Image](https://github.com/user-attachments/assets/0a93232d-8dbc-445d-88ee-cd4374488b33)|![Image](https://github.com/user-attachments/assets/f5507e8e-3f73-49e3-9faf-5bdf560b1c67)|![Image](https://github.com/user-attachments/assets/8cbda251-2d19-4c94-af10-97ca4cf47b5a)|![Image](https://github.com/user-attachments/assets/c3089a4a-70b9-4073-be8e-4a167b68196a)|![Image](https://github.com/user-attachments/assets/e91b6885-c059-4312-b378-55208cc87fb1)|![Image](https://github.com/user-attachments/assets/bc488cdd-4e46-45a2-bf37-555eed9f7fac)
</details>


<details>
<summary>Case 2: Launch Brave without flags - PASSED </summary>

1. continued from above Case 1
2. closed Brave
3. relaunch Brave without the flags (cmd line `brave.exe --enable-logging=stderr --enable-features=BraveDayZeroExperiment:variant/a`)
4. Confirmed that the `Rewards` & `Talk` widgets are visible/usable via NTP
5. Confirmed that the `Brave Wallet` icon is visible/usable via the toolbar
6. Confirmed that the `Brave Rewards` icon is visible/usable via the URL bar
7. Confirmed that `SNTP` are being displayed/appearing via NTP without any issues/failures
8. Confirmed that the `Brave News` opt-in card is peaking/visible when scrolling the NTP
9. Confirmed Clock widget in shown/disappear when enabled and disabled via settings


**`step 1`** | **`step 3`** | **`step 4`** | **`step 5`** | **`step 6`** | **`step 7`** | **step 8`** 
-----------|-----------|-------------|-----------|-----------| -------- | -------
![Image](https://github.com/user-attachments/assets/bb2daa0f-f6ca-499b-b165-9d792d68097a)|![Image](https://github.com/user-attachments/assets/ae8cd4af-8b47-4bef-a133-09b426d4c45d)|![Image](https://github.com/user-attachments/assets/4f956ee6-e7be-4c35-bebd-046f27228c06)|![Image](https://github.com/user-attachments/assets/c8f17069-8e46-487d-9783-9439f48cf71b)|![Image](https://github.com/user-attachments/assets/95c1aab4-4fa8-4828-a4cb-a4882b820285)|![Image](https://github.com/user-attachments/assets/d04bd9de-2db5-4a1c-beb2-6c611c144e6e)|![Image](https://github.com/user-attachments/assets/e59c0b8e-5eb6-4c6b-987c-448981cfc850)
