### ISSUE TITLE
Remove rewards from day zero exp

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#42113]
We have an issue from https://github.com/brave/brave-core/pull/25696 which is hiding the rewards button when day zero experiment is enabled. 
In this issue, we are resetting the default value for rewards icon on the url bar.

**Comment by kjozwiak** [comment]
The above requires `1.73.86` or higher for `1.73.x` verification 👍 @Uni-verse @hffvld can use the STR/Template from https://github.com/brave/brave-core/pull/25696#issuecomment-2458389604 to verify the above.

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240925.009 release-keys
Brave build: 1.73.86 
Chromium: 131.0.6778.39 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Fresh install Brave
2. Connect the device to the Terminal and run ADB command `adb shell "echo '--enable-features=BraveDayZeroExperiment:variant/a' > /data/local/tmp/brave-test-day-zero-expt"`
3. Launch Brave > *Verify*

**ACTUAL RESULTS:**
- Verified that the [new](https://github.com/brave/brave-browser/issues/41203#issuecomment-2463170007) Brave onboarding flow is shown as expected.
- Verified that the `Rewards` icon is appearing/visible via the `Omnibox`.
- Verified that tapping the `Rewards` icon starts the `Rewards onboarding` flow.
- Verified that the `Allow Brave to send you notifications?` modal is shown during the `Brave Rewards` onboarding.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/4e76c5a8-ed1a-4863-947c-3afb2772632c) | ![2](https://github.com/user-attachments/assets/d03dbbea-fdf1-44c8-b4f4-6b44c84b0c81) | ![3](https://github.com/user-attachments/assets/a9080458-a055-4931-bc94-336afcbc6535) | ![4](https://github.com/user-attachments/assets/faf56d72-fc88-418f-a268-b3c74fc94385) |
| ![1](https://github.com/user-attachments/assets/e9a04ced-0799-49ca-b987-50439b3986fb) | ![2](https://github.com/user-attachments/assets/fd4e24f2-964f-4887-8a98-abac1ea01493) | ![3](https://github.com/user-attachments/assets/355992cd-c9e3-4328-ab54-edef335d947e) | ![4](https://github.com/user-attachments/assets/22ebe1f7-1787-4572-8655-a011514c52f6) |

https://github.com/user-attachments/assets/6b40fd50-a2b6-476e-b6bb-16c9c853d394
