### ISSUE TITLE
nothing happens on downloading anything

### ISSUE THREAD

**Issue by 0x-kys** [brave/brave-browser#42114]
### Description

> Have you searched for similar issues?

There's a [similar issue](https://github.com/brave/brave-browser/issues/32510) but not exactly same and is from 2023.

I installed Arch Linux last night after a long time of using windows. Recently switched to Brave (while i was on windows) where it was working perfectly fine. After installing on arch i just can't download any files. I tried with brave-beta, brave-nightly, google-chrome-stable and chromium as well and download is working as expected on Firefox surprisingly.

Clicking on change doesn't open any popup either.

![Image](https://github.com/user-attachments/assets/3275c738-bffd-4f48-a281-03c664dbbfbf)

Video of download not working on brave and brave-beta but working on Firefox

https://github.com/user-attachments/assets/7f29710b-8415-4c47-b58b-bece69b6a167

### Steps to reproduce

not sure if others can reproduce this behavior, but 

1. install brave from AUR repository: `yay -S brave`
2. try opening and downloading any sample file (pdf in my case) [Sample PDF](https://file-examples.com/storage/fe00d37cde6728af4966ebc/2017/10/file-sample_150kB.pdf)

### Actual result

File not downloading

### Expected result

A window should pop up and let me select where I want to save the file.

Downloading from Firefox shows expected result.

![Image](https://github.com/user-attachments/assets/4e550a2a-760e-4ec6-8ce0-90e01790eae3)

### Reproduces how often

No steps to reproduce

### Brave version (brave://version info)

**Stable**

|  |  |
| -- | -- |
| Brave | 1.71.121 Chromium: 130.0.6723.91 (Official Build) (64-bit)  |
| Revision | 4f0f61781aeffc3842565931be77ac3e18032066 |
| OS | Linux |

**Beta**

|  |  |
| -- | -- |
| Brave | 1.72.96 Chromium: 131.0.6778.24 (Official Build) beta (64-bit)   |
| Revision | 10f472615a5ea2cccb71ffc48639efbaef71b801 |
| OS | Linux |

**Nightly**

|  |  |
| -- | -- |
| Brave | 1.73.76 Chromium: 131.0.6778.24 (Official Build) nightly (64-bit)   |
| Revision | fa36788bc0d6c1c87cacd28f8508e0403b0d8a2f |
| OS | Linux |

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

- Couldn't find any similar issue on forums.
- Location is set to `/home/syk/Downloads`
- I'm unable to change download path as well.
- "Ask where to save each file before downloading" is enabled
- "Show downloads when they're done" is enabled
- I tried re-installing, removing all cache and then re-installing but this just won't work.

**Comment by lukemulks** [comment]
Thanks @0x-kys 

Tagging in @fmarier and @bsclifton for visibility on this item, as I suspect they'd likely be helpful in either investigation or with tagging/assigning some of the team that specialize in Linux and Arch. 

@fmarier & @bsclifton, @0x-kys has been really helpful with advocating for Brave with the Linux and foss community in general, and this issue was a snag reported to him in the process. If we're able to work through this and a few other rough edges, they may be able to help us significantly grow our Linux user base and presence within those communities. Just sharing the context in case it helps.

**Comment by 0x-kys** [comment]
Update: **FIXED IT!!!!**

```
syk@zero ~> systemctl --user --type=service
  UNIT                           LOAD   ACTIVE SUB     DESCRIPTION
  at-spi-dbus-bus.service        loaded active running Accessibility services bus
  dbus-broker.service            loaded active running D-Bus User Message Bus
  pipewire.service               loaded active running PipeWire Multimedia Service
  pulseaudio.service             loaded active running Sound Service
● xdg-desktop-portal-gtk.service loaded failed failed  Portal service (GTK/GNOME implementation)
  xdg-desktop-portal.service     loaded active running Portal service
  xdg-document-portal.service    loaded active running flatpak document portal service
  xdg-permission-store.service   loaded active running sandboxed app permission store
```

in these services `xdg-desktop-portal-gtk.service` was failing to load

on checking further with `journalctl`

```
syk@zero ~> journalctl --user -u xdg-desktop-portal-gtk.service

Nov 05 19:50:12 zero systemd[990]: Starting Portal service (GTK/GNOME implementation)...
Nov 05 19:50:14 zero systemd[990]: Started Portal service (GTK/GNOME implementation).
Nov 05 19:58:45 zero systemd[990]: xdg-desktop-portal-gtk.service: Main process exited, code=exited, status=1/FAILURE
Nov 05 19:58:45 zero systemd[990]: xdg-desktop-portal-gtk.service: Failed with result 'exit-code'.
```

---

```
sudo pacman -Syyu
```

```
sudo pacman -S xdg-desktop-portal-gtk gtk3 gnome-icon-theme
```

If `xdg-desktop-portal` is missing

```
sudo pacman -S xdg-desktop-portal
```

after all this i checked status of service again

```
syk@zero ~ [1]> systemctl --user restart xdg-desktop-portal-gtk.service

Job for xdg-desktop-portal-gtk.service failed because the control process exited with error code.
See "systemctl --user status xdg-desktop-portal-gtk.service" and "journalctl --user -xeu xdg-desktop-portal-gtk.service" for details.
syk@zero ~ [1]> systemctl --user status xdg-desktop-portal-gtk.service
× xdg-desktop-portal-gtk.service - Portal service (GTK/GNOME implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-gtk.service; static)
     Active: failed (Result: exit-code) since Wed 2024-11-06 21:18:59 IST; 11s ago
 Invocation: e70067e49c5147a28ee8f692864a1034
    Process: 2106 ExecStart=/usr/lib/xdg-desktop-portal-gtk (code=exited, status=1/FAILURE)
   Main PID: 2106 (code=exited, status=1/FAILURE)
   Mem peak: 2M
        CPU: 14ms

Nov 06 21:18:59 zero systemd[580]: Starting Portal service (GTK/GNOME implementation)...
Nov 06 21:18:59 zero xdg-desktop-por[2106]: cannot open display:
Nov 06 21:18:59 zero systemd[580]: xdg-desktop-portal-gtk.service: Main process exited, code=exited, status=1/FAILURE
Nov 06 21:18:59 zero systemd[580]: xdg-desktop-portal-gtk.service: Failed with result 'exit-code'.
Nov 06 21:18:59 zero systemd[580]: Failed to start Portal service (GTK/GNOME implementation).
```

it was trying to open display but couldn't so i edited `xdg-desktop-portal-gtk.service`

```
systemctl --user edit xdg-desktop-portal-gtk.service
```

Added following to it

```
[Service]
Environment=DISPLAY=:0
```

and reload my systemd config

```
systemctl --user daemon-reload
```

```
systemctl --user restart xdg-desktop-portal-gtk.service
```

and finally checked status again using

```
syk@zero ~> systemctl --user status xdg-desktop-portal-gtk.service

● xdg-desktop-portal-gtk.service - Portal service (GTK/GNOME implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-gtk.service; static)
    Drop-In: /home/syk/.config/systemd/user/xdg-desktop-portal-gtk.service.d
             └─override.conf
     Active: active (running) since Wed 2024-11-06 21:20:09 IST; 2s ago
 Invocation: 288a4bc8b9cd4575aed600936a93af5c
   Main PID: 2227 (xdg-desktop-por)
      Tasks: 6 (limit: 38290)
     Memory: 4M (peak: 4.4M)
        CPU: 47ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/xdg-desktop-portal-gtk.service
             └─2227 /usr/lib/xdg-desktop-portal-gtk

Nov 06 21:20:09 zero systemd[580]: Starting Portal service (GTK/GNOME implementation)...
Nov 06 21:20:09 zero systemd[580]: Started Portal service (GTK/GNOME implementation).
```

```
syk@zero ~> systemctl --user --type=service
  UNIT                                         LOAD   ACTIVE SUB     DESCRIPTION
  at-spi-dbus-bus.service                      loaded active running Accessibility services bus
  dbus-:1.34-org.a11y.atspi.Registry@0.service loaded active running dbus-:1.34-org.a11y.atspi.Registry@0.service
  dbus-broker.service                          loaded active running D-Bus User Message Bus
  pipewire.service                             loaded active running PipeWire Multimedia Service
  pulseaudio.service                           loaded active running Sound Service
  xdg-desktop-portal-gtk.service               loaded active running Portal service (GTK/GNOME implementation)
  xdg-desktop-portal.service                   loaded active running Portal service
  xdg-document-portal.service                  loaded active running flatpak document portal service
  xdg-permission-store.service                 loaded active running sandboxed app permission store
```

AND IT FINALLY WORKED!!!! CAN FINALLY GET BACK TO ENJOYING BRAVE!!! THANKS EVERYONE!!

> leaving this here in case someone else get into similar issue

**Comment by fmarier** [comment]
It seems like we may have missing dependencies here?

@wknapik Do you think that's an Arch-specific problem?

It looks like `xdg-desktop-portal` is a dependency of an essential package on my laptop and so it's not really possible for it to be missing on popos:
```
$ sudo apt remove xdg-desktop-portal pop-desktop
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  appstream-data-pop appstream-data-pop-icons apt-config-icons-hidpi
  apt-config-icons-large apt-config-icons-large-hidpi bpfcc-tools file-roller flatpak
  gir1.2-flatpak-1.0 gir1.2-ostree-1.0 gnome-shell-extension-appindicator
  gnome-shell-extension-cosmic-dock gnome-shell-extension-cosmic-workspaces
  gnome-shell-extension-pop-x11gestures gtk2-engines-murrine gvfs-fuse ieee-data
  inputattach libbpfcc libcdr-0.1-1 libclang-cpp11 libflatpak-dev libflatpak0
  libfreehand-0.1-1 libgnome-bg-4-1 libgnome-desktop-4-1 libgranite-common libgranite6
  libllvm11 libmalcontent-0-0 libmspub-0.1-1 libostree-1-1 libostree-dev
  libpagemaker-0.0-0 libproxy1-plugin-gsettings libproxy1-plugin-networkmanager
  libpugixml1v5 libqalculate-data libqalculate22 libreoffice-calc libreoffice-draw
  libreoffice-impress libvisio-0.1-1 lp-solve network-manager-config-connectivity-pop
  pop-cosmic pop-gnome-shell-theme pop-gtk-theme pop-icon-theme pop-launcher pop-shell
  pop-shell-shortcuts pop-shop pop-sound-theme pop-theme pop-transition popsicle
  popsicle-gtk python3-bpfcc python3-netaddr qalc repoman system76-scheduler touchegg
  x11-apps x11-session-utils xdg-user-dirs-gtk xinit xorg xwayland
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  gnome-shell-extension-desktop-icons-ng pop-de-gnome pop-desktop pop-session
  xdg-desktop-portal xdg-desktop-portal-gnome xdg-desktop-portal-gtk
WARNING: The following essential packages will be removed.
This should NOT be done unless you know exactly what you are doing!
  pop-desktop pop-de-gnome (due to pop-desktop)
0 upgraded, 0 newly installed, 7 to remove and 0 not upgraded.
After this operation, 2,623 kB disk space will be freed.
E: Removing essential system-critical packages is not permitted. This might break the system.
```

**Comment by 0x-kys** [comment]
> Seems like xdg-desktop-portal and xdg-desktop-portal-gtk were installed, but -gtk was failing to start up.

Yes, both are generally installed in distros. This probably happened because of the way I set up my Arch installation. 

That startup fail got fixed by installing gtk3 (was missing in my installation) and that broken service by double checking availability of `xdg-desktop-portak-gtk` and editing config.

**Comment by fmarier** [comment]
> I'm not sure what you mean by an Arch-specific problem.

Are we missing a dependency in the Arch package? If `gtk3` is required to be installed, then it should be a dependency (direct or indirect) of the `brave-bin` package perhaps?

**Comment by 0x-kys** [comment]
Prolly some issue with my own setup. Weird for me as well 'cause i installed it from AUR and I don't think any other package would wanna remove `gtk3`

**Comment by fmarier** [comment]
Ok, thanks it sounds like your machine got into a weird state then. Nothing to fix on our end (or the Arch's maintainer's end).
