### ISSUE TITLE
[ads] Check for the NTP SI component updates after power is resumed

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#42125]

**Comment by kjozwiak** [comment]
The above requires `1.73.98` or higher for `1.73.x` verification 👍

**Comment by btlechowski** [comment]
Verified with

Brave | 1.73.99 Chromium: 131.0.6778.108 (Official Build) (64-bit)
-- | --
Revision | 273b36438521dd91cbab7a047e6d90deabf59d56
OS | Linux

Verified in https://github.com/brave/brave-browser/issues/42531#issuecomment-2536139602

**Comment by btlechowski** [comment]
Verified with

```
Brave	1.73.100 Chromium: 131.0.6778.108 (Official Build) (arm64) 
Revision	8ae5a87a006b15ffd649ca5ff59f333d6833f1fb
OS	macOS Version 14.4 (Build 23E214)
```

https://github.com/brave/brave-browser/issues/42531#issuecomment-2536178031

**Comment by btlechowski** [comment]
Verified with

Brave | 1.73.100 Chromium: 131.0.6778.108 (Official Build) (64-bit)
-- | --
Revision | 8ae5a87a006b15ffd649ca5ff59f333d6833f1fb
OS | Windows 10 Version 22H2 (Build 19045.5247)

Verified in https://github.com/brave/brave-browser/issues/42531#issuecomment-2536208895
