### ISSUE TITLE
IPFS companion option in `brave://settings/` is not translated

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#4212]
Found when verifying test plan from https://github.com/brave/brave-core/pull/2106

## Steps to Reproduce

   1. Clean install
   2. Change Browser language to Polish
   3. Open `brave://settings/?search=ipfs`

## Actual result:

IPFS companion option is not translated

![image](https://user-images.githubusercontent.com/34715963/56631075-b188d780-6621-11e9-995b-738a949306bc.png)

## Expected result:
IPFS companion option is translated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

cc @brave/legacy_qa @yrliou

**Comment by rebron** [comment]
@btlechowski Can you recheck once @mkarolin pulls translations?

**Comment by bbondy** [comment]
cc @yrliou 
@mkarolin says it's not fixed by the translation update.
https://github.com/brave/brave-core/pull/2343#issuecomment-487171535

**Comment by yrliou** [comment]
The string was not pushed to transifex for translation yet, and now it is.
Hopefully it should be fixed by the next translation update.

**Comment by yrliou** [comment]
I believe the translated strings are pulled in chromium version bump 75.0.3770.27, I can see this on beta, dev, and nightly. Could we re-test this and close it out if fixed? Thanks. cc @brave/legacy_qa

**Comment by kjozwiak** [comment]
Seems to be working 👍Went through the following using `Win 10 x64` and ensured that IPFS under `chrome://settings/extensions` is being translated:

* `0.68.4 Chromium: 75.0.3770.38` - PASSED
* `0.67.71 Chromium: 75.0.3770.38` - PASSED
* `0.65.114 Chromium: 75.0.3770.38` - PASSED

Example:

<img width="694" alt="Screen Shot 2019-05-30 at 9 35 19 PM" src="https://user-images.githubusercontent.com/2602313/58675601-0dcacf80-8323-11e9-9a34-6aa6cc7698dc.png">

@btlechowski can you double check and close this off this it's working for you as well?

**Comment by btlechowski** [comment]
Verification passed

Brave | 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 7 Service Pack 1 (Build 7601.24468)

Brave | 0.66.93 Chromium: 75.0.3770.90 (Official Build) beta (64-bit)
-- | --
Revision | a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}
OS | Windows 7 Service Pack 1 (Build 7601.24468)

Brave | 0.67.87 Chromium: 75.0.3770.100 (Official Build) dev (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 7 Service Pack 1 (Build 7601.24468)

Brave | 0.68.60 Chromium: 75.0.3770.90 (Official Build) nightly (64-bit)
-- | --
Revision | a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}
OS | Windows 7 Service Pack 1 (Build 7601.24468)

![image](https://user-images.githubusercontent.com/34715963/59872246-a3450680-9399-11e9-92ae-07bc027d3da7.png)
