### ISSUE TITLE
Remove news from day zero exp

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#42120]
We have an issue from https://github.com/brave/brave-core/pull/25696 which is hiding the news opt in card when day zero experiment is enabled.
In this issue, we are resetting the default value for new opt in card on NTP.

**Comment by kjozwiak** [comment]
The above requires `1.73.86` or higher for `1.73.x` verification 👍 @Uni-verse @hffvld can use the STR/Template from https://github.com/brave/brave-core/pull/25696#issuecomment-2458389604 to verify the above.

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240925.009 release-keys
Brave build: 1.73.86 
Chromium: 131.0.6778.39 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Fresh install Brave
2. Connect the device to the Terminal and run ADB command `adb shell "echo '--enable-features=BraveDayZeroExperiment:variant/a' > /data/local/tmp/brave-test-day-zero-expt"`
3. Launch Brave > *Verify*

**ACTUAL RESULTS:**
- Verified that the [new](https://github.com/brave/brave-browser/issues/41203#issuecomment-2463170007) Brave onboarding flow is shown as expected.
- Verified that the `Brave News` onboarding card is being displayed via the `NTP`.
- Verified that the `Brave News` card can be hidden by tapping `X` in the top right corner.
- Verified that the `Brave News` can be enabled by tapping `SHow Brave News`.
- Verified that `Sponsored` NTP images are being shown/displayed without any issues.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/45cf17c9-a94f-4caf-a330-809caaca8522) | ![2](https://github.com/user-attachments/assets/89cffeec-cd5f-4977-a9cc-a9a6f95bda51) | ![3](https://github.com/user-attachments/assets/d1198d3e-8d1b-48c0-a1b7-45cf781664c6) | ![4](https://github.com/user-attachments/assets/21594f59-5015-44ab-8e64-9072687c1392) |
