### ISSUE TITLE
[ads] Send page land immediately for non-successful HTTP status codes

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#42137]

**Comment by btlechowski** [comment]
Verified with

Brave | 1.75.147 Chromium: 132.0.6834.57 (Official Build) nightly (64-bit)
-- | --
Revision | 6ca80c5d3414773bba6275ff7109f0cb01233795
OS | Linux

<details>




</details>

**Comment by tmancey** [comment]
@aseren we send http status codes that are not in the range 200 to 399 via page lands for landing pages, so for me this is working as expected, thanks cc @iambrianfung incase I am missing something.

Did we try to reproduce using the target URL from the campaign, because maybe that URL became invalid at some point?
