### ISSUE TITLE
Shields Panel drop downs are blank

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#4213]
Follow up to https://github.com/brave/brave-browser/issues/2488

## Steps to Reproduce

   1. Clean install
   2. Open `interia.pl`
   3. Open Shields Panel
4. Click on `3rd-party cookie blocked` to show drop down
OR
4. Click on `3rd-party recognition devices blocked` to show drop down

## Actual result:

Text in the drop down is not visible

Light theme:
![image](https://user-images.githubusercontent.com/34715963/56631882-3d503300-6625-11e9-8e35-8251626eb359.png)
![image](https://user-images.githubusercontent.com/34715963/56631889-43461400-6625-11e9-98f5-78dba78197ca.png)

Dark theme:
![image](https://user-images.githubusercontent.com/34715963/56631918-61ac0f80-6625-11e9-87b3-ce81f647a14f.png)

## Expected result:
Text in the drop down is visible

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Reproduced on

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

cc @brave/legacy_qa @cezaraugusto

**Comment by LaurenWags** [comment]
Could not reproduce on macOS

Brave | 0.64.62 Chromium: 74.0.3729.108 (Official Build) beta(64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Mac OS X

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.64.75 Chromium: 74.0.3729.131 (Official Build) (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.523

![image](https://user-images.githubusercontent.com/34715963/57635927-79354300-75a8-11e9-9e96-96ac295385ce.png)
![image](https://user-images.githubusercontent.com/34715963/57635956-86eac880-75a8-11e9-8148-552b4c5a703e.png)
