### ISSUE TITLE
Swap Screen is Showing Insufficient Balance Warning

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#42141]
### Description

The `Swap` screen is showing an `Insufficient Balance` warning when selecting a token with a balance.

### Steps to reproduce

1. Open the `Wallet` and navigate to the `Swap` screen
2. Select a `Token` to swap that has a balance
3. Enter an amount to swap
4. You will see an `Insufficient Balance` warning.

### Actual result

https://github.com/user-attachments/assets/b15871f5-ad92-4d5a-94b4-495a9bfebadb

### Expected result

https://github.com/user-attachments/assets/e3d5a4ec-815b-4124-8960-f964b82fda8d

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

1.72.96 Chromium: 131.0.6778.24 (Official Build) beta (arm64) 

### Android device

- Brand/model: 
- Android version: 

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.74.2` or higher for `1.74.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.5 Chromium: 131.0.6778.69 (Official Build) beta (64-bit)
-- | --
Revision | fbd7c390a7daa54f1aac2c769076d3fecf7c7fc7
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from [brave/brave-core#26432](https://github.com/brave/brave-core/pull/26432)
- Verified balance shows up correctly on Swap screen

https://github.com/user-attachments/assets/099c52e6-4d6d-413d-9142-250fd6a9a6ba

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 15 running 1.74.10 x64beta build
- Verified steps from [brave/brave-core#26432](https://github.com/brave/brave-core/pull/26432)
- Verified balance shows up correctly on Swap screen

https://github.com/user-attachments/assets/5e1af0ce-d499-49f6-9cec-51dfd275dc8c
