### ISSUE TITLE
Initiating Cancel transaction doesn't bring up the confirmation screen unless you close the Cancel and Transaction status screens

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#42146]
### Description

Initiating Cancel transaction doesn't bring up the confirmation screen unless you close the Cancel and Transaction status screens

### Steps to reproduce

1. Initiate a Send/Swap/Bridge transaction
2. Once transaction is submitted click on Cancel
3. Shows Cancel confirmation screen
4. Click on the Cancel button
5. Nothing happens but shows pending transaction count
6. Clicking multiple times creates that many cancel transactions
7. Only show the confirmation screen if you navigate back or close the transaction confirmation/Cancel screens

### Actual result

https://github.com/user-attachments/assets/a2e8e3a2-9aa0-4b3c-8888-2eefd0ac62ab

### Expected result

Should bring the Cancel confirmation screen without having to close the status panels

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.72.96 Chromium: 131.0.6778.24 (Official Build) beta (64-bit)
-- | --
Revision | 10f472615a5ea2cccb71ffc48639efbaef71b801
OS | Windows 11 Version 23H2 (Build 22631.4317)

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @Douglashdaniel

**Comment by kjozwiak** [comment]
The above requires `1.73.87` or higher for `1.73.x` verification 👍
