### ISSUE TITLE
Brave iOS crashes if Leo/Leo settings are accessed while Leo is disabled in flags

### ISSUE THREAD

**Issue by LegalizeNukes** [brave/brave-browser#42150]
### Description

In Brave iOS v1.70.133 if Leo is disabled using flags (#brave-ai-chat) upon interacting with anything related to Leo (icon, Leo settings) the browser will crash. Either interacting with Leo should do nothing or anything Leo-related should be hidden from the interface.

### Steps to reproduce

1. Disable Leo via flags.
2. Interact with anything related to Leo in the browser.
3. 

### Actual result

Browser crashes.

### Expected result

Browser should not crash.

### Reproduces how often

Easily reproduced

### Brave version

1.70.133 Chromium: 129.0.6668.100 (Official Build) stable (64-bit)

### Device/iOS version

iPhone 16 Pro on iOS 18.1

### Affected browser versions

- [x] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [x] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.73.90` or higher for `1.73.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.0` using version `1.73 (91)`

* Ensured that disabling `brave-ai-chat` will remove Leo elements from UI and menus.
* Ensured that `Ask Leo` is not shown in search bar when enter query.
* Ensured crash does not occur when using Leo. 

example | example | example | example | example
---|---|---|---|---
![Image](https://github.com/user-attachments/assets/ef554ba3-a5dc-429a-ad52-f7273c629e57) | ![Image](https://github.com/user-attachments/assets/fe6d8e3d-54e7-4175-a5b3-a4d10e28aacb) | ![Image](https://github.com/user-attachments/assets/162e475c-a5eb-4090-bc62-2d1899159c45) | ![Image](https://github.com/user-attachments/assets/8377c2b0-b640-416e-9eb4-ad653e246d14) | ![Image](https://github.com/user-attachments/assets/6a1ddd0f-9ed5-407b-9dba-c78c2680bee4)

**Comment by Uni-verse** [comment]
Verified on `iPad (9th Gen)` running `iOS 17.7.1` using version `1.73 (91)`


* Ensured that disabling `brave-ai-chat` will remove Leo elements from UI and menus.
* Ensured that `Ask Leo` is not shown in search bar when enter query.
* Ensured crash does not occur when using Leo. 

example | example | example | example
---|---|---|---
![Image](https://github.com/user-attachments/assets/535e09d2-2a2b-438f-8ce6-9535b9f05cb2) | ![Image](https://github.com/user-attachments/assets/f1630040-98a5-4d5c-9f9b-4a1d23532522) | ![Image](https://github.com/user-attachments/assets/589e641b-5ad1-4c31-b077-74d5a8d49eca) | ![Image](https://github.com/user-attachments/assets/1570c580-edd4-4641-8ceb-4e10c703883a)
