### ISSUE TITLE
[RESOLVED] Scrolling Tabs Flags Disappeared

### ISSUE THREAD

**Issue by 8thHalfHour** [brave/brave-browser#42166]
### Description

As of the latest version (v1.74.1 Chromium: 131.0.6778.24 (Official Build) beta (arm64)), the chrome scrollable tabs flags have disappeared. I also cannot find anything within Brave that replaces it with the same functionality. Specifically, I use these settings:

* `#scrollable-tabstrip`
* `#tab-scrolling-button-position`
* `#scrollable-tabstrip-with-dragging`
* `#scrollable-tabstrip-overflow`

### Steps to reproduce

1. Go to `brave://flags`.
2. Search for `scroll`.
3. None of those flags show up.

### Actual result

The flags are not present.

![Image](https://github.com/user-attachments/assets/a176be74-f9b2-4560-b2a9-88079898b711)

### Expected result

The flags are present, as they are still there in Chrome (v130.0.6723.92 (Official Build) (arm64)):

![Image](https://github.com/user-attachments/assets/15198924-d5cd-40c5-bcb7-45213c97f879)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

**Brave:** 1.74.1 Chromium: 131.0.6778.24 (Official Build) beta (arm64)
**Revision:** a8e7367d8022295ca5d3b1bb35475274a22a472a
**OS:** macOS Version 14.7 (Build 23H124)

### Channel information

- [x] release (stable)
- [x] beta
- [ ] nightly <- did not test

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by babycommando** [comment]
I can confirmt this is happening to me as well, damn I miss scrollable tabs. Its what was making me still use Brave over Edge.

Please bring them back.

**Comment by anthonyanikos** [comment]
so i am!

**Comment by HyperLemons** [comment]
This is extremely frustrating, I'm now forced to have the tab scrolling buttons that just take up extra space where I could be seeing my tabs. Seriously needs to be fixed.

**Comment by 8thHalfHour** [comment]
**Google Chrome stable channel latest version, all flags are available:**

![Image](https://github.com/user-attachments/assets/236749af-b25d-4b9d-9d5f-e3662c47b81b)

![Image](https://github.com/user-attachments/assets/5bf18881-4c95-4624-9915-5234f0a39be6)


**Google Chrome dev channel latest version, all flags are present:**

![Image](https://github.com/user-attachments/assets/24a15959-8149-40ef-842c-fb9de9521ff9)

![Image](https://github.com/user-attachments/assets/0c60b246-5043-4baa-b70d-c7e4b0349e90)

**Comment by 8thHalfHour** [comment]
This appears to have been resolved as of the latest version of Brave Beta; scrollable tab flags now present:

![Image](https://github.com/user-attachments/assets/771dda74-bdcc-4078-b73f-3988b5e624f6)

![Image](https://github.com/user-attachments/assets/3189ce39-4c41-4734-aea7-13435e55d20f)

**Comment by 8thHalfHour** [comment]
This appears to have been resolved as of the latest version of Brave Beta; scrollable tab flags now present:

![Image](https://github.com/user-attachments/assets/771dda74-bdcc-4078-b73f-3988b5e624f6)

![Image](https://github.com/user-attachments/assets/3189ce39-4c41-4734-aea7-13435e55d20f)

**Comment by 8thHalfHour** [comment]
This has resolved as of the latest version of Brave Beta; scrollable tab flags now present:

![Image](https://github.com/user-attachments/assets/771dda74-bdcc-4078-b73f-3988b5e624f6)

![Image](https://github.com/user-attachments/assets/3189ce39-4c41-4734-aea7-13435e55d20f)

**Comment by babycommando** [comment]
wait what? its cool that brave beta have it but are we even gonna get it into brave OG? Brave beta never stopped working thats the whole point
