### ISSUE TITLE
Clear cookie data menu shows "Chrome" instead of "Brave" when 3p cookies are allowed

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#42168]
### Description

When you go to the `Cookies and site data` menu from the "tune" icon in the address bar on Android, toggling the `Allow 3p cookies` option "on" displays `90 days until Chrome blocks cookies again`:

![Image](https://github.com/user-attachments/assets/4f9f6c61-ec0c-434f-b4bf-41de6bc4e62e)

"Chrome" should be removed/replaced with `Brave` wherever available. 

### Steps to reproduce

1. Visit a site on Android
2. Click "tune" icon and toggle `Allow third-party cookies` "on"
3. Observe the message displayed 

### Actual result

Branding shows "Chrome"

### Expected result

Branding should show "Brave"

### Reproduces how often

Easily reproduced

### Brave version

v1.71.121

### Device

- Brand/model: All
- Android version: All 

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Reports:
https://community.brave.com/t/the-name-chrome-appears-in-the-menu-when-we-accept-thirt-party-cookies-and-the-send-feedback-link-has-an-address-from-chrome-it-should-be-at-brave/579477

**Comment by Brave-Matt** [comment]
@deeppandya — also noticing that the `Send feedback` link on this same menu also links to Chrome support URL.

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 BP11.241025.006 release-keys
Brave build: 1.75.76 
Chromium: 132.0.6834.33 (Official Build) canary (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/42168#issue-2642105682
2. *Verify*

**ACTUAL RESULTS:**
- Verified, when `Third-party cookies` toggle switch is ON, the string says:

 `Help us improve Brave by telling us why you allowed third-party cookies.` [Send feedback](https://support.google.com/chrome/topic/6069782) 

- Observed that `Send feedback` link refers to https://support.google.com/chrome/topic/6069782 - cc @samartnik 

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/fad5bec2-28fe-4344-8601-dba69760970a) | ![2](https://github.com/user-attachments/assets/b9555e40-511b-4388-a3bc-a8140f685b7b) | ![3](https://github.com/user-attachments/assets/bd6b6eb8-b4bf-48ea-866b-ba255fb2d010) |

**Comment by westar0099** [comment]
The link to "Sens feedback" should also be resolved. @samartnik @hffvld

**Comment by westar0099** [comment]
The link to "Sens feedback" should also be resolved. @samartnik @hffvld

**Comment by claudiu644** [comment]
Can the send feedback link also be changed?@Brave-Matt @deeppandya @samartnik @hffvld


>     * Observed that `Send feedback` link refers to https://support.google.com/chrome/topic/6069782 - cc [@samartnik](https://github.com/samartnik)
> 
> 
> 1 	2 	3
> ![1](https://github.com/user-attachments/assets/fad5bec2-28fe-4344-8601-dba69760970a) 	![2](https://private-user-images.githubusercontent.com/128532965/394533379-b9555e40-511b-4388-a3bc-a8140f685b7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE0NDgwNjQsIm5iZiI6MTc0MTQ0Nzc2NCwicGF0aCI6Ii8xMjg1MzI5NjUvMzk0NTMzMzc5LWI5NTU1ZTQwLTUxMWItNDM4OC1hM2JjLWE4MTQwZjY4NWI3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwOFQxNTI5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWQ4Y2VjN2M0MzY5ZGQzN2NjMjhkMWVmMDY2OGMwM2U5YTk2YWYxZjc4ZWZlYmVjZDMwYTNhN2I0Yzc1NjAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dXp7vZCl6sVpi1ow6goQFnXp1O9nDRd6TKc2oKwz_HQ) 	![3](https://private-user-images.githubusercontent.com/128532965/394533378-bd6b6eb8-b4bf-48ea-866b-ba255fb2d010.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE0NDgwNjQsIm5iZiI6MTc0MTQ0Nzc2NCwicGF0aCI6Ii8xMjg1MzI5NjUvMzk0NTMzMzc4LWJkNmI2ZWI4LWI0YmYtNDhlYS04NjZiLWJhMjU1ZmIyZDAxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwOFQxNTI5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjU0ZmU4YmM0NDE4ZmU4MzhmNTk4N2MxYmUzYzBjMWI0NGNkOGRhMTRiMmNlZGMzMjFkYTdkODJiY2M5NmE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bqGPm4kw0f4LPTtFaLL5MgcdX2aQVFchL1xft40fxVY)

**Comment by deeppandya** [comment]
> Can the send feedback link also be changed?@Brave-Matt @deeppandya @samartnik @hffvld
> 
> 
> >     * Observed that `Send feedback` link refers to https://support.google.com/chrome/topic/6069782 - cc [@samartnik](https://github.com/samartnik)
> > 
> > 
> > 1 	2 	3
> > ![1](https://github.com/user-attachments/assets/fad5bec2-28fe-4344-8601-dba69760970a) 	![2](https://private-user-images.githubusercontent.com/128532965/394533379-b9555e40-511b-4388-a3bc-a8140f685b7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE0NDgwNjQsIm5iZiI6MTc0MTQ0Nzc2NCwicGF0aCI6Ii8xMjg1MzI5NjUvMzk0NTMzMzc5LWI5NTU1ZTQwLTUxMWItNDM4OC1hM2JjLWE4MTQwZjY4NWI3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwOFQxNTI5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWQ4Y2VjN2M0MzY5ZGQzN2NjMjhkMWVmMDY2OGMwM2U5YTk2YWYxZjc4ZWZlYmVjZDMwYTNhN2I0Yzc1NjAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dXp7vZCl6sVpi1ow6goQFnXp1O9nDRd6TKc2oKwz_HQ) 	![3](https://private-user-images.githubusercontent.com/128532965/394533378-bd6b6eb8-b4bf-48ea-866b-ba255fb2d010.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE0NDgwNjQsIm5iZiI6MTc0MTQ0Nzc2NCwicGF0aCI6Ii8xMjg1MzI5NjUvMzk0NTMzMzc4LWJkNmI2ZWI4LWI0YmYtNDhlYS04NjZiLWJhMjU1ZmIyZDAxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwOFQxNTI5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjU0ZmU4YmM0NDE4ZmU4MzhmNTk4N2MxYmUzYzBjMWI0NGNkOGRhMTRiMmNlZGMzMjFkYTdkODJiY2M5NmE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bqGPm4kw0f4LPTtFaLL5MgcdX2aQVFchL1xft40fxVY)
> 
> 

@claudiu644 I have the change ready. I will be pushing it on nightly channel soon.
