### ISSUE TITLE
[Follow up to #41203] `Old/Original` onboarding flow reappeared when adding `Brave widget` via `Drag & Drop` or restarting Brave

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#42170]
### Description

Follow-up to #41203.

### Steps to reproduce

1. Fresh install Brave
2. Connect the device to the Terminal and run ADB command `adb shell "echo '--enable-features=BraveDayZeroExperiment:variant/a' > /data/local/tmp/brave-test-day-zero-expt"`
3. Launch Brave > Tap `Cancel` or choose Brave as `default` browser
4. Tap `Add to home screen`
5. Add the widget to the `Home screen` via `drag & drop`
6. Tap the `Brave` Home screen shortcut > *Observe*

### Actual result

`Old/Original` onboarding flow reappeared when adding the `Brave widget` via `Drag & Drop`.

-----------------

https://github.com/user-attachments/assets/22f3eb22-c8de-44d2-a456-290fdeef9c37

### Expected result

`Old/Original` onboarding flow must not be shown.

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.73.86 
Chromium: 131.0.6778.39 (Official Build) (64-bit) 

### Device

- Brand/Model: Pixel 7
- Android version: 15

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above can also be reproduced by simply closing/re-launching `Brave` during the new onboarding. STR/Cases:

* ensure that `adb shell "echo '--enable-features=BraveDayZeroExperiment:variant/a' > /data/local/tmp/brave-test-day-zero-expt"`
* launch `Brave` and notice the new onboarding flow (should see the `Default Browser` system modal/notification)
* close/restart `Brave` and you'll notice you'll get the `Notification` system modal which means it's running the original onboarding

**Comment by kjozwiak** [comment]
The above requires `1.73.90` or higher for `1.73.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 AP41.240925.009 release-keys
Brave build: 1.73.90 
Chromium: 131.0.6778.69 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Fresh install Brave
2. Connect the device to the Terminal and run ADB command `adb shell "echo '--enable-features=BraveDayZeroExperiment:variant/a' > /data/local/tmp/brave-test-day-zero-expt"`
3. Launch Brave > *Verify new onboarding flow*
4. While seeing the `default browser` modal close and relaunch Brave > *Verify, old onboarding flow is not exposed* 
5. Select Brave as the `default` browser > *Verify that `p3a` modal is shown*
6. While seeing `p3a` modal close and relaunch Brave > *Verify, old onboarding flow is not exposed* 
7. Tap `Continue` > *Verify `NTP` is shown*
8. Close and relaunch Brave > *Verify, old onboarding flow is not exposed* 

**ACTUAL RESULTS:**
- Verified that the `new` onboarding flow works as expected:
  - `Brave animation` is shown.
  - OS level `default browser` modal is shown.
  - `p3a` modal is shown.
- Verified that the `old` onboarding flow is not exposed when closing and relaunching Brave.

---------------------------

https://github.com/user-attachments/assets/3306a292-6506-4858-bf15-32f1e38abaa2
