### ISSUE TITLE
Adding he, th, vi locales

### ISSUE THREAD

**Issue by AndyAnds265** [brave/brave-browser#42181]
### Description

Hey all,

We'd like to add 3 new languages to our iOS app. The languages are `th`, `vi`, and `he` (or sometimes `iw`). The strings are currently being worked on at the moment and we'd like to get them on the next version release if possible. This is important as we'd like to have these languages launched in 2024 so that we can start the year off strong on iOS. 

th = Thai
vi = Vietnamese
he = Hebrew

For context, we'll simultaneously be launching ASO for these languages so theoretically we'll have a month to build up some steam before the new year rush. 

### Steps to reproduce

n/a

### Actual result

n/a

### Expected result

n/a

### Reproduces how often

Easily reproduced

### Brave version

n/a

### Device/iOS version

n/a

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by AndyAnds265** [comment]
hey all, the strings are ready for all 3 languages :)

**Comment by kjozwiak** [comment]
Closing the above as https://github.com/brave/brave-core/pull/26814 was merged into the `1.73.x` branch. The above requires `1.73.96` or higher for `1.73.x` verification 👍

**Comment by Uni-verse** [comment]
In progress on `iPhone XR` running `iOS 17.7.1` using version `1.73 (96)`

* Spot checked NTP, UI, settings menus, Shields and other areas of the app and ensured that `Thai`, `Vietnamese` and `Hebrew` languages are supported. 

**Thai**

example | example | example | example | example
---|---|---|---|---
![Image](https://github.com/user-attachments/assets/4989fea7-b978-4719-a5eb-a6896c123fad) | ![Image](https://github.com/user-attachments/assets/f227d7c8-9a53-4dee-a133-aaf70da809b6) | ![Image](https://github.com/user-attachments/assets/4aa4c5b5-1658-44da-9c9c-4bf14dd4b95c) | ![Image](https://github.com/user-attachments/assets/f66258fe-8d67-4b6a-81c8-ec1a9f38cd57) | ![Image](https://github.com/user-attachments/assets/d56e5a12-2566-4c35-a42e-1f98c158cbdb)
![Image](https://github.com/user-attachments/assets/ed4a8e4d-ce36-468b-88b8-59b6dfb12158) | ![Image](https://github.com/user-attachments/assets/447f1398-b7da-4da0-8a45-fdd2ab85da21) | ![Image](https://github.com/user-attachments/assets/46de6b80-b330-4010-8ec9-d2b93c1a7b4d) | ![Image](https://github.com/user-attachments/assets/79d1ad56-3aed-404b-97ce-a6d8b405b379) | ![Image](https://github.com/user-attachments/assets/1e5d44dc-a699-468b-b95d-01d66d45c892)
![Image](https://github.com/user-attachments/assets/3ee7eacf-7b14-4610-9b55-2543e1fa3e8e) | ![Image](https://github.com/user-attachments/assets/c2ad181f-712e-4474-8c0f-1d50dded02f2) | ![Image](https://github.com/user-attachments/assets/761964e2-082a-4f20-b59d-c777ce179684) | ![Image](https://github.com/user-attachments/assets/252772e6-61a3-46e8-aaab-658641d50c36) | ![Image](https://github.com/user-attachments/assets/88faf14b-a2ee-49ee-a388-93bb1dc3e947)

**Vietnamese**

example | example | example | example | example
---|---|---|---|---



**Hebrew**

example | example | example | example | example
---|---|---|---|---
