### ISSUE TITLE
[RESOLVED] Option to Use Custom DevTools Stylesheets Missing

### ISSUE THREAD

**Issue by 8thHalfHour** [brave/brave-browser#42182]
### Description

As of the latest version (v1.74.1 Chromium: 131.0.6778.24 (Official Build) beta (arm64)), the option to use a custom stylesheet in DevTools is no longer available.  I also cannot find anything within Brave that replaces it with the same functionality. I use this feature constantly in my work for improved accessibility. 

### Steps to reproduce

1. Open DevTools (`F12`) > Settings > Experiments.
2. Search for `style`.
3. `Allow extensions to load custom stylesheets` is not in the list.

### Actual result

The option is not present.

![Image](https://github.com/user-attachments/assets/0951f834-6ee7-487c-822b-aa34e415666f)

### Expected result

The option is present, as they are still there in Chrome (v130.0.6723.92 (Official Build) (arm64)):

![Image](https://github.com/user-attachments/assets/968496a0-1908-4dc8-9a1a-1e782e11f982)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

**Brave:** 1.74.1 Chromium: 131.0.6778.24 (Official Build) beta (arm64)
**Revision:** a8e7367d8022295ca5d3b1bb35475274a22a472a
**OS:** macOS Version 14.7 (Build 23H124)

### Channel information

- [x] release (stable)
- [x] beta
- [ ] nightly <-- did not test

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [ ] in the latest version of Chrome <-- the "expected result" screenshot is from the current version of Chrome

**Comment by ouqilbo** [comment]
It seems like it has intentionally been removed by the Chromium devs.
https://issues.chromium.org/issues/369788368
ChromeDevTools/devtools-frontend@e6796272dc534345f936479de75d58ca04a8109a

We can just hope Brave won't drop this feature. Maybe we'll start having more devs using it.
Otherwise, I think that for your own projects you could use VSCode with remote debugging.
https://code.visualstudio.com/docs/nodejs/browser-debugging

Unfortunately, I'm also one of the folks that doesn't use VSCode much.

**Comment by ouqilbo** [comment]
Well, it has been removed with https://github.com/brave/brave-browser/releases/tag/v1.73.89 😞

**Comment by bsclifton** [comment]
Hi folks - thanks for the interest here. It was indeed moved upstream by Chromium devs. We don't have any plans at the moment to re-add and support this functionality. 

cc: @rebron just in case

**Comment by 8thHalfHour** [comment]
Bummer. Hopefully Chromium devs will reinstate. It was bizarre to suddenly see it gone.

**Comment by T3M1N4L** [comment]
This should definitely be reinstated into Brave Browser as it is a feature that many developers like my self used avidly
