### ISSUE TITLE
Remove VPN feature callout popup

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#42184]
![Image](https://github.com/user-attachments/assets/b7c49033-0c51-4893-a494-2c6a4f7ef63d)

We've had several complaints about this feature callout which seems to appear at random. We've checked with product team and this can be dropped.

**Comment by Uni-verse** [comment]
Verified on `iPad` running `iOS 17.5.1` using version `1.75 (115)`

* Verified the following using the test plan mentioned in https://github.com/brave/brave-core/pull/26511#issue-2652998430
   * ensured that the VPN promotional popup was reproducible on 1.73.x   
   * ensured that the VPN promotional popup is not shown on 1.75.x
   
1.73.x | 1.75.x
---|---
<img width="300" src="https://github.com/user-attachments/assets/e4c4cd85-fb95-4bf6-8079-77d90c320167"> | <img width="300" src="https://github.com/user-attachments/assets/97a858bd-6a82-4798-befb-64eaa372b003">
