### ISSUE TITLE
Quick search taking space what i typed in Facebook comment input field

### ISSUE THREAD

**Issue by abdarker** [brave/brave-browser#42186]
### Description

![Image](https://github.com/user-attachments/assets/c3309f3c-14af-479e-b1e5-c88972c3c046)

### Steps to reproduce

1. go to https://facebook.com
2. try to comment on a group's post
3. you will see the quick search is hiding the input field and preventing me to see what i typed ![Image](https://github.com/user-attachments/assets/e6243075-5438-4bc8-9a41-f386054da52c)

### Actual result

![Image](https://github.com/user-attachments/assets/e5859b91-8153-434d-8565-6a5023af7133)

### Expected result

![Image](https://github.com/user-attachments/assets/541289e8-d52a-4e61-9965-c003331c310c)

### Reproduces how often

Easily reproduced

### Brave version

1.75.6

### Device

- Brand/model: Redmi Turbo 3
- Android version: android 14

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
@abdarker thanks for the report 👍 Much appreciated. Glad we found/ran into this on `Nightly` before we release QSE to the release channel.

**Comment by kjozwiak** [comment]
The above requires `1.74.13` or higher for `1.74.x` verification 👍
