### ISSUE TITLE
ipfs companion options page cannot be shown

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#4218]
## Description 
IPFS companion has an extension option page which includes various options users could set for the extension. Because right now we installed it as a component extension if users install it using the switch in brave://settings, the extension cannot be shown in brave://extensions unless we manually pass an argument when execute the binary.

## Steps to Reproduce

   1. Visit brave://settings and toggle IPFS companion switch
   2. Right click IPFS companion extension icon and click options.

## Actual result:
Option page is not shown.

## Expected result:
Should show the option page as below
<img width="735" alt="Screen Shot 2019-04-24 at 8 13 48 AM" src="https://user-images.githubusercontent.com/4730197/56671115-e8cea700-6668-11e9-9756-07873c76d5fe.png">

## Reproduces how often: 
Every time

## Brave version (brave://version info)
This exists starting from 0.64.x where IPFS switch is landed.

**Comment by yrliou** [comment]
Test plan specified in https://github.com/brave/brave-core/pull/2328#issue-272955946

**Comment by lidel** [comment]
@yrliou would it make things better if we open Preferences in a new tab (https://github.com/ipfs-shipyard/ipfs-companion/issues/502)? 

Or is this related to the way `runtime​.open​Options​Page()` is handled in component extensions?

**Comment by yrliou** [comment]
@lidel If preference is opened as an extension page in a new tab, then we won't have problem showing it by either installing as a component extension or a regular extension.
The reason it cannot be shown if installing as a component extension is because the extension page (chrome://extensions or brave://extensions) where the overlay will be in will not show any component extensions by default.
Because installing as a normal extension gives us the benefit for manifest localization and solves this issue, I don't think we need to bump the priority of ipfs-shipyard/ipfs-companion#502 for this.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.64.68 Chromium: 74.0.3729.108 (Official Build) beta (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Windows 10 OS Build 17134.523
- Verified the test plan from https://github.com/brave/brave-core/pull/2328#issue-272955946

![image](https://user-images.githubusercontent.com/38657976/57135903-9e67cb80-6dc8-11e9-8b7b-dd2af6701827.png)
