### ISSUE TITLE
Turning off "Allow X (previously Twitter) embedded tweets" in shields setting breaks x.com 2FA login

### ISSUE THREAD

**Issue by LegalizeNukes** [brave/brave-browser#42193]
### Description

If the "Allow X (previously Twitter) embedded tweets" setting has been disabled under shields, when trying to set up 2FA or login with 2FA on x.com an error occurs. This is because https://api.x.com is blocked on the x.com domain, whitelisting it with the below custom filter fixes the issue.

! Allow requests to api.x.com only from x.com
@@||https://api.x.com^$domain=x.com,important

![Image](https://github.com/user-attachments/assets/83bd1a94-2942-4a04-ba79-17f2b13b0269)

### Steps to reproduce

1. Turn off "Allow X (previously Twitter) embedded tweets" in shields
2. Try to set up OR login with 2FA on x.com
3. 2FA process will fail and give the user an error from x.com 

### Actual result

User gets an error messages when trying to do anything 2FA related when the aforementioned setting is turned off.

### Expected result

Users should be able to log into x.com using 2FA without issues even when the aforementioned setting is turned off.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.71.123 Chromium: 130.0.6723.116 (Official Build) (arm64) 

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

I have not tested this on mobile devices, but it's possible that it could occur on them as well.

FYI, my shields are set to aggressive.

**Comment by bsclifton** [comment]
cc: @ShivanKaul

**Comment by ShivanKaul** [comment]
@ryanbr this seems like an acceptable exception rule to add, wdyt?

**Comment by ryanbr** [comment]
```
! Twitter
||api.twitter.com^$third-party,domain=~tweetdeck.com|~twitter.com|~twitter.jp|~x.com
||platform.twitter.com^$third-party,domain=~tweetdeck.com|~twitter.com|~twitter.jp|~x.com
||api.x.com^$third-party,domain=~tweetdeck.com|~twitter.com|~twitter.jp|~x.com
||platform.x.com^$third-party,domain=~tweetdeck.com|~twitter.com|~twitter.jp|~x.com
```

we're only blocking `api.x.com` in 3p context, and not apply too `tweetdeck.com,twitter.com,twitter.jp,x.com`

I tested 2FA login with this enabled, no issues here @LegalizeNukes

**Comment by LegalizeNukes** [comment]
Upon further testing I found that the issue stemmed from a configuration error on my part, after fixing the error and testing with a fresh profile I can confirm that this is not an issue. My apologies for the false positive!
