### ISSUE TITLE
Build all official brave packages with compiler optimizations

### ISSUE THREAD

**Issue by Jacalz** [brave/brave-browser#4219]
## Description 

More or less a feature request, but a lot of the other browsers are building their official packages, for all operating systems, using compile time optimizations. The guys over at Firefox are for example getting better performance with the Clang compiler, using Link Time Optimizations and probably some other stuff too. I also think it would be a good idea for Brave to do benchmarks on different impacts of optimizations.

I would recommend you to try passing the `-O3` optimization flag to force the compiler to throw almost everything it got at building it, try enabling different types of LTO (I think there is thin, and fat along with regular LTO), probably give PGO (Profile Guided Optimizations) a shot along with testing the Clang compiler from LLVM. This should preferably be done for all Windows, MacOS and Linux binary packages.

## Actual result:
Not much information about what is done in the way of optimization and there might be areas where it can be improved on.

## Expected result:
Give benchmarking a shot at squeezing every bit of performance out if there’s anything we can do. There should preferably be more documentation about what is done along with, as stated before, filling in any performance gaps where we can...

**Comment by rebron** [comment]
"Not much is done in the way of optimizations (I believe)" 

Can you explain this further?

**Comment by Jacalz** [comment]
> "Not much is done in the way of optimizations (I believe)"
> 
> Can you explain this further?

I am sorry. It was a poorly written sentence and shouldn’t have been written like that from my part. What I mean is that I haven’t seen anyone talk about optimization work. The whole task is about making sure that the browser gets as much performance as possible. I will correct that utterly stupid formulation from my part...

**Comment by bsclifton** [comment]
We pull in the optimizations which Chromium has- of which, there are quite a bit. You can check out this file in particular to see some of them:
https://chromium.googlesource.com/chromium/src/build/config/+/master/compiler/BUILD.gn#560

It's important to note- you may not get all the optimizations unless you build in release (vs debug) and also with official_build=true

**Comment by Jacalz** [comment]
Thanks, for the information. @bsclifton
