### ISSUE TITLE
restoring a wallet does not check for grant

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4220]
## Description 
After a wallet is restored, it doesn't appear as though there is a check for grant. No notification appears on BAT logo and no claim banner displays on brave://rewards.

## Steps to Reproduce

   1. Launch Brave (I used staging flag)
   2. Enable Rewards. (Since I was on staging, there was a grant notification. I claimed it for the wallet that had been created, this made the claim banner go away on brave://rewards).
   3. Restore a wallet (staging one if necessary).
   4. Wallet is restored, but no notification to accept a grant. If you refresh page then you will see the claim banner.

## Actual result:
No claim banner/notification about UGP grant

## Expected result:
Claim banner/notification

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? unsure, probably yes
- Can you reproduce this issue with the nightly channel? unsure, probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

**Comment by btlechowski** [comment]
Not reproducible on

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

Steps used:
1. Clean install
2. Run with staging flag
3. Enable rewards, make sure grant is available
4. Backup wallet through keys
5. Clean install
6. Enable rewards and claim grant
7. Restore wallet from 4.

![image](https://user-images.githubusercontent.com/34715963/56710864-65748a80-6728-11e9-8d33-df5b6ea73adf.png)

@LaurenWags Maybe your restored wallet didn't have grants available?

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.67.105 Chromium: 75.0.3770.100 (Official Build) beta (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the STR from the description
