### ISSUE TITLE
Remove Auto-Contribute

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#42209]
Remove Auto-Contribute for Rewards 3.0 (and it will also be removed in 2.x). 

- [ ] Remove UI elements (in panel and page)
- [ ] String search for mentions of Auto-Contribute
- [ ] Feature should be immediately disabled and no more A-C transactions should be triggered, including if they are already pending

Be mindful of various "gotchas".

**Comment by Miyayes** [comment]
We should have followup issues to clean up any remaining fragments on iOS and Android.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.75.127 Chromium: 132.0.6834.57 (Official Build) nightly (64-bit)
-- | --
Revision | 0916ebcaf1b20e94b9ecc3608812f538c3ac2a37
OS | Windows 10 Version 22H2 (Build 19045.5247)
```
**_UI Check:_**

AC contribution UI removal in a clean profile:

AC contribution UI removal in a upgrade profile:


**_Functionality check_**

AC functional check in a clean profile:

AC functional check in a upgrade profile:

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.75.156 Chromium: 132.0.6834.83 (Official Build) beta (x86_64)
-- | --
Revision | 036ac4040dc50d4bd49b3438e20ab90686218543
OS | macOS Version 14.7.2 (Build 23H311)
```

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Pixel 6` using version(s):
```
Device/OS: Pixel 6 / oriole-user 15 AP4A.241205.013 release-keys
Brave build: 1.75.171
Chromium: 132.0.6834.160 (Official Build) (64-bit) 
```
---------------------------
<details>
<summary> Rewards 2.5 - AC contribution removal in a clean profile </summary>

**STEPS:**
1. Install and launch Brave `1.75.171`
2. Enable `Rewards`
3. Connect custodian
4. *Verify*

**ACTUAL RESULTS:**
- Verified that `Auto contribution` is not shown anywhere on the `brave://rewards` screen.
- Verified that `Auto contribution` is not shown anywhere on the `Brave Rewards` panel.

---------------------------

`Before connecting custodian`

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/b568c316-b2d2-4297-af28-86af52f66e63) | ![2](https://github.com/user-attachments/assets/0c38def6-eabc-43f5-a35c-dac4c3fcf64f) | ![3](https://github.com/user-attachments/assets/5d740d6e-99f5-4482-8e87-e1cd784f4e4c) | ![4](https://github.com/user-attachments/assets/e56a2042-1002-400a-84e2-c72962ea5546) |
| ![1](https://github.com/user-attachments/assets/d7d6553d-b47c-4c01-8574-efe2b17988e5) | ![2](https://github.com/user-attachments/assets/d0274f52-c182-4f8a-8b03-95da39f7370b) | ![3](https://github.com/user-attachments/assets/c83dfd95-2ed4-45b2-bdd5-30754e788de0) | ![4](https://github.com/user-attachments/assets/687cbf47-862b-4375-8dca-8d9e52f48d6b) |

`After connecting custodian`

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/bedca1bd-7c80-4216-8d88-1262c51d314a) | ![2](https://github.com/user-attachments/assets/8136d96f-2ed4-414e-8b49-64d8dfbfeced) | ![3](https://github.com/user-attachments/assets/fd1ad8fd-d166-4599-b40a-c9473e709ce7) | ![4](https://github.com/user-attachments/assets/c32a62e6-4aeb-484d-9ca5-3e913187a28e) |
| ![1](https://github.com/user-attachments/assets/06626b80-4330-4122-9088-02cb5c9795a8) | ![2](https://github.com/user-attachments/assets/a9dba5c3-b85d-4a9e-8016-034f5f28d657) | ![3](https://github.com/user-attachments/assets/c602e219-b4ba-4c44-8217-a04b4c38aa30) | ![4](https://github.com/user-attachments/assets/7c5cea22-2b41-4c67-b68b-99b7d0627f31) |
</details>

<details>
<summary> Rewards 2.5 - AC contribution removal in an upgraded profile </summary>

**STEPS:**
1. Install and launch Brave `1.74.50`
2. Enable `Rewards`
3. Connect custodian > *Confirm that the `Auto-Contribute` section is shown*
4. Upgrade Brave to `1.75.171`
5. Go to Brave Rewards > *Verify that `Auto-Contribute` section is NOT shown*

**ACTUAL RESULTS:**
- Verified that `Auto contribution` is not shown anywhere on the `brave://rewards` screen.
- Verified that `Auto contribution` is not shown anywhere on the `Brave Rewards` panel.

---------------------------

https://github.com/user-attachments/assets/72b25d64-75c1-4b00-9da3-404ca6f7a862
</details>

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` using version(s):
```
Device/OS: Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
Brave build: 1.75.171
Chromium: 132.0.6834.160 (Official Build) (64-bit) 
```
---------------------------
<details>
<summary> Rewards 2.5 - AC contribution removal in a clean profile </summary>

**STEPS:**
1. Install and launch Brave `1.75.171`
2. Enable `Rewards`
3. Connect custodian
4. *Verify*

**ACTUAL RESULTS:**
- Verified that `Auto contribution` is not shown anywhere on the `brave://rewards` screen.
- Verified that `Auto contribution` is not shown anywhere on the `Brave Rewards` panel.

---------------------------

https://github.com/user-attachments/assets/ee8b26e5-9989-436e-8f98-538f7ec9b8dd
</details>

<details>
<summary> Rewards 2.5 - AC contribution removal in an upgraded profile </summary>

**STEPS:**
1. Install and launch Brave `1.74.50`
2. Enable `Rewards`
3. Connect custodian > *Confirm that the `Auto-Contribute` section is shown*
4. Upgrade Brave to `1.75.171`
5. Go to Brave Rewards > *Verify that the `Auto-Contribute` section is NOT shown*

**ACTUAL RESULTS:**
- Verified that `Auto contribution` is not shown anywhere on the `brave://rewards` screen.
- Verified that `Auto contribution` is not shown anywhere on the `Brave Rewards` panel.

---------------------------

https://github.com/user-attachments/assets/96697eac-3e7f-4c9d-80ee-bcda8448d779
</details>

<details>
<summary> Rewards 3.0 - AC contribution removal in a clean profile </summary>

**STEPS:**
1. Install and launch Brave `1.75.171`
2. Go to `brave://flags` and enable `brave-rewards-new-rewards-ui` > Restart Brave
3. Enable `Rewards`
4. Connect custodian
5. *Verify*

**ACTUAL RESULTS:**
- Verified that `Auto contribution` is not shown anywhere on the `brave://rewards` screen.
- Verified that `Auto contribution` is not shown anywhere on the `Brave Rewards` panel.

---------------------------

https://github.com/user-attachments/assets/df4454b4-5a9d-4b5b-b846-d021a848c840
</details>

<details>
<summary> Rewards 3.0 - AC contribution removal in an upgraded profile </summary>

**STEPS:**
1. Install and launch Brave `1.74.50`
2. Go to `brave://flags` and enable `brave-rewards-new-rewards-ui` > Restart Brave
3. Enable `Rewards`
4. Connect custodian > *Confirm that the `Auto-Contribute` section is shown*
5. Upgrade Brave to `1.75.171`
6. Go to Brave Rewards > *Verify that the `Auto-Contribute` section is NOT shown*

**ACTUAL RESULTS:**
- Verified that `Auto contribution` is not shown anywhere on the `brave://rewards` screen.
- Verified that `Auto contribution` is not shown anywhere on the `Brave Rewards` panel.

---------------------------

https://github.com/user-attachments/assets/bbc887d3-8360-44d9-a7a4-e6b0083208a9
</details>

**Comment by btlechowski** [comment]
Verified with

Brave | 1.75.173 Chromium: 133.0.6943.39 (Official Build) (64-bit)
-- | --
Revision | 21435b152a0c070861f182a0b6782222a8efae37
OS | Linux


#### Clean profile case - Clean profile 1.75.x, enable rewards (can be 2.5 UI)

<details>

Rewards 2.5
Verified no Auto Contribution panel on brave://rewards

![Image](https://github.com/user-attachments/assets/229f496b-2cdb-4aef-8a4b-4e336bc20886)|![Image](https://github.com/user-attachments/assets/18cb930a-9a5e-4eb8-a5cb-25f5e212bbbe)|![Image](https://github.com/user-attachments/assets/da07f6ed-5d84-431f-9b35-c6918f60778a)
--|--|--

Rewards 3.0
Verified no Auto Contribution panel on brave://rewards

![Image](https://github.com/user-attachments/assets/a5b9c5f1-5942-427f-b1b3-a389f77fabce)|![Image](https://github.com/user-attachments/assets/ad2585e3-3e9a-4daf-8222-c5a870792a8b)
--|--

</details>

#### Upgrade case - Install 1.74.x, enable rewards (2.5 UI)

<details>

1.74.x - Rewards 2.5

![Image](https://github.com/user-attachments/assets/160cc543-e30e-4f70-a71a-3e8f71221eb1)|![Image](https://github.com/user-attachments/assets/fa35c043-3a00-4045-9b20-235624b371cc)
--|--

1.75.x - Rewards 2.5

![Image](https://github.com/user-attachments/assets/8c353030-0389-4eff-bcc6-2569a1f82556)|![Image](https://github.com/user-attachments/assets/bc8002c1-970d-4666-b9b9-12c5a028dcbc)
--|--

1.75.x - Rewards 3.0



</details>
