### ISSUE TITLE
Ads not available in Canada

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#4221]
According to https://www.brave.com/blog/brave-ads-launch/, Ads are available in Canada.

However, I can't turn them on in my browser:
![Screenshot from 2019-04-24 10-11-43](https://user-images.githubusercontent.com/167821/56679280-86ca6d80-6679-11e9-80ae-6a9f806f798e.png)

```
Brave | 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Linux
```

**Comment by srirambv** [comment]
Possibly related to #4224?

**Comment by fmarier** [comment]
> Possibly related to #4224?

No, this was an update from 0.62.51.

**Comment by fmarier** [comment]
Here are the results for my residential IP address from https://www.iplocation.net:

```
Geolocation data from IP2Location (Product: DB6, updated on 2019-4-1)
IP Address	Country	Region	City
216.x.x.x	Canada 	British Columbia	Vancouver
ISP	Organization	Latitude	Longitude
Novus Entertainment Inc.	Not Available	49.xxxx	-123.xxxx

Geolocation data from ipinfo.io (Product: API, real-time)
IP Address	Country	Region	City
216.x.x.x	Canada 	British Columbia	Vancouver
ISP	Organization	Latitude	Longitude
Novus Entertainment Inc.	Novus Entertainment Inc. (novuscom.net)	49.xxxx	-123.xxxx

Geolocation data from DB-IP (Product: Full, 2019-4-1)
IP Address	Country	Region	City
216.x.x.x	Canada 	British Columbia	Vancouver (East Side)
ISP	Organization	Latitude	Longitude
Novus Entertainment Inc.	Novus Entertainment Inc.	49.xxxx	-123.xxx
```

**Comment by fmarier** [comment]
It happens on two different laptops.

One of them (running Debian unstable) is using this locale:

```
$ locale
LANG=fr_CA.utf8
LANGUAGE=
LC_CTYPE="fr_CA.utf8"
LC_NUMERIC="fr_CA.utf8"
LC_TIME="fr_CA.utf8"
LC_COLLATE="fr_CA.utf8"
LC_MONETARY="fr_CA.utf8"
LC_MESSAGES="fr_CA.utf8"
LC_PAPER="fr_CA.utf8"
LC_NAME="fr_CA.utf8"
LC_ADDRESS="fr_CA.utf8"
LC_TELEPHONE="fr_CA.utf8"
LC_MEASUREMENT="fr_CA.utf8"
LC_IDENTIFICATION="fr_CA.utf8"
LC_ALL=
```

and the other one (Ubuntu 18.04) is using:

```
$ locale
LANG=en_CA.UTF-8
LANGUAGE=en_CA:en
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC=en_CA.UTF-8
LC_TIME=en_CA.UTF-8
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY=en_CA.UTF-8
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER=en_CA.UTF-8
LC_NAME=en_CA.UTF-8
LC_ADDRESS=en_CA.UTF-8
LC_TELEPHONE=en_CA.UTF-8
LC_MEASUREMENT=en_CA.UTF-8
LC_IDENTIFICATION=en_CA.UTF-8
LC_ALL=
```

**Comment by srirambv** [comment]
Locale French has to be for France. Other region French isn't supported I guess. This is same with Qwant as well. 

cc: @tmancey

**Comment by tmancey** [comment]
@srirambv This should be resolved by https://github.com/brave/brave-browser/issues/4224

**Comment by tmancey** [comment]
@srirambv @GeetaSarvadnya is looking into this with an end user. @GeetaSarvadnya can you please update both myself and @srirambv

**Comment by tmancey** [comment]
@GeetaSarvadnya @fmarier Can you please test latest nightly build as this was resolved in https://github.com/brave/brave-browser/issues/4224

**Comment by drink7up** [comment]
I've seen a number of people are getting this "Sorry! Ads are not supported for this region" message despite being located in a supported area. I'm having the same problem.

- Windows 10 / LinuxMint

- VPN through US / Canada / UK / France / Germany

- Fresh installs / upgrades

- Release / Beta / Dev / Nightly.

I've yet to see ads work even once!

Are most people actually getting this issue resolved, or just giving up???

**Comment by tmancey** [comment]
@drink7up which version number of Brave are you using please?

**Comment by drink7up** [comment]
I'm not using any particular version. Just each time github has a new release, I try again. Last one was the nightly v0.67.4

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tmancey** [comment]
@drink7up would you be prepared to share your screen so I can help resolve the issue?

**Comment by fmarier** [comment]
It now works for me in Beta:

```
Brave | 0.64.72 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Linux
```

with this locale:

```
LANG=en_CA.UTF-8
LANGUAGE=en_CA:en
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC=en_CA.UTF-8
LC_TIME=en_CA.UTF-8
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY=en_CA.UTF-8
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER=en_CA.UTF-8
LC_NAME=en_CA.UTF-8
LC_ADDRESS=en_CA.UTF-8
LC_TELEPHONE=en_CA.UTF-8
LC_MEASUREMENT=en_CA.UTF-8
LC_IDENTIFICATION=en_CA.UTF-8
LC_ALL=
```

**Comment by fmarier** [comment]
Also works with the following locale:

```
LANG=fr_CA.UTF-8
LANGUAGE=
LC_CTYPE="fr_CA.UTF-8"
LC_NUMERIC=en_CA.UTF-8
LC_TIME=en_CA.UTF-8
LC_COLLATE="fr_CA.UTF-8"
LC_MONETARY=en_CA.UTF-8
LC_MESSAGES="fr_CA.UTF-8"
LC_PAPER=en_CA.UTF-8
LC_NAME=en_CA.UTF-8
LC_ADDRESS=en_CA.UTF-8
LC_TELEPHONE=en_CA.UTF-8
LC_MEASUREMENT=en_CA.UTF-8
LC_IDENTIFICATION=en_CA.UTF-8
LC_ALL=
```

**Comment by drink7up** [comment]
@tmancey Does this help?

![Capture1](https://user-images.githubusercontent.com/46804620/57501322-6b728a00-732a-11e9-9d71-bbc0a7891ba0.PNG)
![Capture2](https://user-images.githubusercontent.com/46804620/57501323-6c0b2080-732a-11e9-9b59-ccb095a38b02.PNG)
![Capture3](https://user-images.githubusercontent.com/46804620/57501324-6c0b2080-732a-11e9-923f-086cb759d1c7.PNG)

**Comment by drink7up** [comment]
This particular attempt was on Windows 10

**Comment by drink7up** [comment]
Where would I find the locale info that people are posting above?

**Comment by drink7up** [comment]
And just a side comment, shouldn't we be able to block Brave from accessing our location in the first place? I would have thought the privacy conscious users might want to run it in some sort of location agnostic mode? I mean, particularly in the early stages when there aren't many ad providers, presumably the ads that are available are mostly internet based services that are not location dependent anyway.

ie. What sources on my PC or IP is Brave tapping into to guess my location without my knowledge?

**Comment by tomlowenthal** [comment]
Hey @drink7up. I don't think you're asking this, but just to get it out of the way first, your browser isn't using any detailed location info — this is all happening at the granularity of a country. Unfortunately, advertisers really want to show ads in certain countries not others. We'd be spinning our wheels trying to change that. So we don't really have a choice about rolling out ads country by country.

Your browser isn't sharing region info anywhere. We don't have records of your IP address, or your locale, or anything like that.

It sounds like you've been trying to see ads for different regions by changing where your connections seem to come from. Please don't do that! Advertisers really care about showing ads in the right country. If Brave shows an ad meant for one country to someone in another country, the advertiser considers that fraud, and we get dinged for it. That makes it harder for us to build and improve this system.

Ultimately, we just can't guarantee that there are ads available for everyone right now. Switching on Rewards is an opt-in so that Brave _may_ show you ads. But it doesn't guarantee that you're going to see any. And if you're not in a supported region, you're probably not going to.

**Comment by drink7up** [comment]
@tomlowenthal I understand where you are coming from about advertisers wanting to target specific regions but I guess now you've got me concerned that my brave browser will 'never' show ads given VPN is always active for me at the router level (even if I use the local vpn server).

If region is this important to Brave, I'd suggest it should be addressed prominently in the browser setup phase - firstly letting the user know what region the browser is detecting so the user can question it, and secondly if the browser is detecting signs that the user is lying about their location, setting the region to unverified and having alternative methods of verifying your location (such as ID verification or even some new blockchain method).

Or instead of unverified, maybe it can just assume they travel in both regions (a common scenario anyway). Worst case there'd still at least be a 50% chance that ads are going to the right place. As it stands, my youtube at home is already only showing google ads in German - which benefits no-one. This would be a big deal if Brave can still get ads to the right person 50% of the time, instead of the 0% currently being achieved by Google Ads.

**Comment by tomlowenthal** [comment]
That's true: if you've configured your router like that, it's entirely possible that you'll never see any ads. Right now things are in a pretty early stage. We're most concerned about making sure that ads only get shown when we're definitely sure that they're right, rather than ensuring that everyone who flips the switch sees at least some ads. Like I said before: turning ads on is a ceiling, not a floor — there's no guarantee that there are ads which are a good fit for any particular person.

**Comment by serhangursoy** [comment]
I'm still having issues with this. 
I tried Brave at work and it was working quite good(German os with English lang pack). 
Now I tried on my pc and it's saying "Sorry! Ads are not yet available in your region." although I'm in Germany. 
- My OS Region was also Germany but my Locale was Turkey, so I uninstalled Brave, changed that, restarted PC, reinstalled, didn't work.
- I changed my language from Turkish to English, did previous steps again, it worked. For a couple of hours, now I'm experiencing the same issue again.
Right now nothing works and it's kinda exhausting to do all those steps over and over for seeing "ads".
Any help would be appreciated. 
Also, why can't you just use browser language combined with geolocation?

**Comment by tmancey** [comment]
@srirambv @GeetaSarvadnya Can you please re-test and close if working as expected?

**Comment by jeifour** [comment]
I live in Germany, but my browser says that ads are not available in my country. What could the reason be?

**Comment by tmancey** [comment]
@jeifour Could you please visit https://whatismyipaddress.com/ and let us know the region and country that is displayed, thanks

**Comment by tmancey** [comment]
> I'm still having issues with this.
> I tried Brave at work and it was working quite good(German os with English lang pack).
> Now I tried on my pc and it's saying "Sorry! Ads are not yet available in your region." although I'm in Germany.
> 
> * My OS Region was also Germany but my Locale was Turkey, so I uninstalled Brave, changed that, restarted PC, reinstalled, didn't work.
> * I changed my language from Turkish to English, did previous steps again, it worked. For a couple of hours, now I'm experiencing the same issue again.
>   Right now nothing works and it's kinda exhausting to do all those steps over and over for seeing "ads".
>   Any help would be appreciated.
>   Also, why can't you just use browser language combined with geolocation?

Could you please visit https://whatismyipaddress.com/ and let us know the region and country that is displayed, thanks

**Comment by jeifour** [comment]
> @jeifour Could you please visit https://whatismyipaddress.com/ and let us know the region and country that is displayed, thanks

For me that appears like this:

ISP: NetCologne GmbH
City: Cologne
Region: North Rhine-Westphalia
Country: Germany

The city is wrong but it's close enough and everything else is correct :)

**Comment by serhangursoy** [comment]
> > I'm still having issues with this.
> > I tried Brave at work and it was working quite good(German os with English lang pack).
> > Now I tried on my pc and it's saying "Sorry! Ads are not yet available in your region." although I'm in Germany.
> > 
> > * My OS Region was also Germany but my Locale was Turkey, so I uninstalled Brave, changed that, restarted PC, reinstalled, didn't work.
> > * I changed my language from Turkish to English, did previous steps again, it worked. For a couple of hours, now I'm experiencing the same issue again.
> >   Right now nothing works and it's kinda exhausting to do all those steps over and over for seeing "ads".
> >   Any help would be appreciated.
> >   Also, why can't you just use browser language combined with geolocation?
> 
> Could you please visit https://whatismyipaddress.com/ and let us know the region and country that is displayed, thanks
It's,
ISP: Deutsche Telekom AG
City: Obermenzing
Region: Bavaria
Country: Germany
However, I fixed the issue by changing my region and all date-related settings to the UK. It's really not related to IP because when my keyboard was in Turkish, but while my IP was pointing Germany, it was still not working.
But it's a really bad solution, to be honest. 
I think you should let people see ads based on the language settings they use in Brave. 
Probably jeifour also have some other different keyboard or Region or date setting different than Germany.

**Comment by tmancey** [comment]
@serhangursoy @jeifour Brave checks the operating systems setting, i.e. on macOS in Preferences and also checks the IP address location. Can you please confirm you had the locale set to Germany/German too?

**Comment by jeifour** [comment]
> @serhangursoy @jeifour Brave checks the operating systems setting, i.e. on macOS in Preferences and also checks the IP address location. Can you please confirm you had the locale set to Germany/German too?

Thanks for the explanation. Changing the locale to Germany fixed the issue.

**Comment by drink7up** [comment]
Any idea how I check my locale in Debian LXDE Linux? (I've still never seen an ad)

**Comment by tmancey** [comment]
> Any idea how I check my locale in Debian LXDE Linux? (I've still never seen an ad)

Hi, if you could check out https://wiki.debian.org/ChangeLanguage and let us know if this resolves the issue you are experiencing

**Comment by Martanti** [comment]
Just downloaded Brave 1.0.0., connected wallet, enabled ads, checked that the local is UK, my IP address points to the UK (no VPN). I also tried downloading and installing beta, nightly and dev versions and still get "Ads are not available in your region". Running Windows 10

**Comment by ismailelk** [comment]
> I've seen a number of people are getting this "Sorry! Ads are not supported for this region" message despite being located in a supported area. I'm having the same problem.
> 
> * Windows 10 / LinuxMint
> * VPN through US / Canada / UK / France / Germany
> * Fresh installs / upgrades
> * Release / Beta / Dev / Nightly.
> 
> I've yet to see ads work even once!
> 
> Are most people actually getting this issue resolved, or just giving up???

I'm having the same issue? And seeing that this issue is open since April. Is not really assuring? 
I'm mostly in the UK and France, and otherwise I use a VPN. But no where it seems to work.

**Comment by ismailelk** [comment]
> > I've seen a number of people are getting this "Sorry! Ads are not supported for this region" message despite being located in a supported area. I'm having the same problem.
> > 
> > * Windows 10 / LinuxMint
> > * VPN through US / Canada / UK / France / Germany
> > * Fresh installs / upgrades
> > * Release / Beta / Dev / Nightly.
> > 
> > I've yet to see ads work even once!
> > Are most people actually getting this issue resolved, or just giving up???
> 
> I'm having the same issue? And seeing that this issue is open since April. Is not really assuring?
> I'm mostly in the UK and France, and otherwise I use a VPN. But no where it seems to work.

Problem solved with setting my mac Region to UK in preferences

**Comment by GeetaSarvadnya** [comment]
@tmancey Ads are served for US/UK/Germany/Canada when we upgrade brave from older versions to a newer version. Probably we can close this issue.

**Comment by tmancey** [comment]
@GeetaSarvadnya as agreed closing this issue, thanks

**Comment by MeetPing** [comment]
for me ads DO NOT work it says not avaivable in my country BUUUUT
on a school computer (Dont ask.) does work it says it is avaivable
Own craptop(Yes i call it craptop, move on) NOT AVAIVABLE.
On my phone ads are avaivable and they are working perfectly.

But why dosent it work on my craptop??

**Comment by MeetPing** [comment]
https://prnt.sc/r80gbt

**Comment by tmancey** [comment]
@MeetPing Can you please let me know the locale settings of your operating system (preferably a screenshot, which if you prefer you can email to tmancey@brave.com). Thanks, Terry

**Comment by MeetPing** [comment]
Finland

Region Finland and stuf
Finnish language.

Is that enough?

**Comment by tmancey** [comment]
@MeetPing Can you please confirm the version of Brave Browser you are running, thanks

**Comment by MeetPing** [comment]
This problem is in Brave (Releases) I have also Brave Dev installed and ads work fine on that.

**Comment by tmancey** [comment]
@MeetPing If you could confirm the version number for your release build that would be great. Thanks

**Comment by bajtos** [comment]
Hello, I am using the following version of Brave:

```
Version 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)
```

My Windows 10 version is 1909 (build 18363.752).

My country is set to Czech Republic.

Information from https://www.iplocation.net/:

![ipaddress](https://user-images.githubusercontent.com/1140553/78169630-f9c79100-7451-11ea-9803-6e1f842a449b.png)

When I set the regional format to `English (United States)`, Brave says that rewards are not available in my region.

When I change the regional format to Czech (Czechia), Brave rewards are enabled for me.

**Comment by shackra** [comment]
I see the ads, but my friend which use Windows 10 can not see them, we both live in Costa Rica but in different zones (He lives in Heredia and I live in San José)

basically, this seems to be an issue of locales, I will match his locales and try again

**Comment by shackra** [comment]
matching the locale on WIndows 10 (`Español (Costa Rica)` instead of `Español (Latinoamerica)`) fixed the issue for him.

**Comment by tmancey** [comment]
@shackra Thank you for updating us, and apologies for the delay as we have been hard at work on the next release. If I can be of assistance in the future please do reach out.
