### ISSUE TITLE
Update Brave VPN icon

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#42226]
### Description

Update the Brave VPN icon.

See Figma for new, on, off, and error states.
https://www.figma.com/design/J4LKBMftiWhqromRWfUQLG/VPN-flows?node-id=2862-22649&t=ZT8xHIPEE4aTwa3q-0

### Steps to reproduce

1. Launch Brave.
2. Notice Brave VPN icon in the upper right corner.

### Actual result

![Image](https://github.com/user-attachments/assets/f250eb9f-56df-4320-861a-c6b9ab15b93d)

### Expected result

![Image](https://github.com/user-attachments/assets/7c89df3c-7d0d-4e95-abac-7f3f71538c5c)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

tbd for target version

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.75.95 Chromium: 132.0.6834.46 (Official Build) nightly (64-bit)
-- | --
Revision | 1adb0a920ea370950a68a2f4c01280f3097c6c4d
OS | Windows 11 Version 24H2 (Build 26100.2314)
```


- Installed 1.75.95
- launched Brave
- Confirmed Brave VPN icon in the upper right corner
- Confirmed Brave VPN icon in various states matched to Figma designs


On boarding state (a) | On boarding (b) | Disconnected state (Light) | Disconnected state (Dark) | Connected state (Dark) | Connected state (Light)  | Error state (Dark) | Error state (Light)
-------- | -------- | --------- | --------- | --------- | -------| ------- | ------
![Image](https://github.com/user-attachments/assets/085b246d-9fde-42f2-988b-2ce365a594af)|![Image](https://github.com/user-attachments/assets/c7e97f49-7816-41c6-b774-01e9dc9639ae)|![Image](https://github.com/user-attachments/assets/c0b8906c-2ea8-4d4c-a364-abac2f9efd7b)|![Image](https://github.com/user-attachments/assets/a47f4923-6f34-4cf8-bf3a-e4f8763782c0)|![Image](https://github.com/user-attachments/assets/813cf3dd-4be6-4026-b9c6-db27d8c951b9)|![Image](https://github.com/user-attachments/assets/a155252b-3f7a-4792-9506-c7d2bc1be7a0)|![Image](https://github.com/user-attachments/assets/bbb034ff-c42b-473a-9b18-6ac56a705f4d)|![Image](https://github.com/user-attachments/assets/c2b1f94a-dd86-42c2-abdc-0f810a377e8b)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.75.171 Chromium: 132.0.6834.160 (Official Build) (arm64)
-- | --
Revision | d4d146998a285171ea57c3b75c52c7819901571a
OS | macOS Version 15.2 (Build 24C101)
```

- Installed 1.75.95
- launched Brave
- Confirmed new Brave VPN icon shown in the upper right corner in the toolbar, replacing previous VPN button
- Confirmed Brave VPN icon in various states matched to Figma designs\
    - pre-purchased (on boarding)
    - purchased state (disconnected)
    - connected state
    - error state
