### ISSUE TITLE
[WebUI]: Improve overriding approach to better support Lit overrides

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#42220]
### Goals
1. It should be easier to set up overrides for new pieces of WebUI
2. There should be a consistent way we override things, rather than the exist multiple approaches
    - br_toolbar replacement from a separate target
    - br_shared_styles approach (build to a separate target, patch individual files
    - webui approach (separate target, copy to `preprocessed` dir
    - `cr_button` approach (replace upstream at compile time)
    - Probably more!
3. Ideally, we should get a compile time error when something goes wrong
4. It should be possible to override lit components
5. It should be possible to override polymer components
6. It should be possible to swap out upstream components for something completely custom
    - When we do put something custom in, we should get compile errors if it doesn't match the shape of upstreams
7. Ideally, we should be able to override/replace CSS
8. We should be able to override/replace HTML
9. Overrides should require a minimum of patching to set up

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.75.148 Chromium: 132.0.6834.57 (Official Build) nightly (64-bit)
-- | --
Revision | 89b8296af95dd49d78a9e46589c7d347cc02b63e
OS | Windows 11 Version 24H2 (Build 26100.2605)
```

Installed 1.75.148
launched Brave
opened brave://settings
confirmed following: 
      - Settings toolbar (for Settings/History/Bookmarks/Rewards) should still show up
      - Buttons on the settings page should still be the Nala buttons
      - Toggles on the settings page should still be the Nala toggles
      - Icons on the settings page should still be overridden


1.73.x | 1.75.x 
------  | -----
![Image](https://github.com/user-attachments/assets/ec16475c-a2de-46ec-b5e4-0f2b6f976071)|![Image](https://github.com/user-attachments/assets/72b604e6-e364-45c1-8fdf-832be3d085b0)
![Image](https://github.com/user-attachments/assets/2d883ead-b8fe-46e6-a886-4cfa1198c5b2)|![Image](https://github.com/user-attachments/assets/c1f83ecb-116e-42ad-87fe-dab84ffdfefb)
