### ISSUE TITLE
Build out ZCash Deposit Modal

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#42221]
### Platforms

all, Android, Linux, macOS, Windows

### Description

We need to build out the new `ZCash` Deposit modal to allow depositing to an account `Unified`, `Shielded` or `Transparent` address.

![Image](https://github.com/user-attachments/assets/d4379f5e-4b2e-461b-b50a-5651e5e1e9eb)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.159 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | a7b6f5093a2dad31fc3f56241a7d55be255e69e2
OS | Windows 11 Version 23H2 (Build 22631.4602)

- Verified steps from [brave/brave-core#26533](https://github.com/brave/brave-core/pull/26533)
- Verified ZCash Deposit modal is shown for both Shielded and regular accounts
- Verified for Shielded ZCash account, deposit modal shows `Unified`, `Shielded` and `Transparent` address
- Verified for non-Shileded ZCash account, deposit modal only shows `Transparent` account
- Encountered [#43254](https://github.com/brave/brave-browser/issues/43254)

https://github.com/user-attachments/assets/7d0e5141-8567-48e7-96ce-bc99cd350f2a
