### ISSUE TITLE
Few settings are not translated into Germany locales

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#42237]
### Description

Found while testing https://github.com/brave/brave-browser/issues/42140
Few settings are not translated into Germany locales

### Steps to reproduce

1. Set OS locale to Germany `Deutsch (Deutschland)`
2. Open brave://settings and look for `Sync`, Download` and `System` settings in the left navigation bar
3. The settings `Sync`, Download` and `System` are not translated into Germany locale
4. Open brave://settings/content
5. The content settings `Augumented Reality`, `Virtual Reality` and `Hand writing` settings are not translated into Germany locale

### Actual result

**Brave://settings:**

![Image](https://github.com/user-attachments/assets/aa6afeb2-cd1c-449d-aa77-d645346ad09a)

**brave://settings/content:**

![Image](https://github.com/user-attachments/assets/2e05e39e-541c-49dd-9919-3428ea988231)

### Expected result

Settings should be translated into other locales 

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.73.88 Chromium: 131.0.6778.39 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | e0a230f2aab41bbd7935065107eb039f90f0ec70
Betriebssystem | Windows 10 Version 22H2 (Build 19045.5011)

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @rebron @mkarolin @brave/qa-team

**Comment by rebron** [comment]
cc: @mherrmann 
Sounds like this is a wontfix?

**Comment by mherrmann** [comment]
I concur with what @ghost wrote above and think this can be closed as wontfix. I will go ahead and do so.
