### ISSUE TITLE
Offer Update functionality for brave-os-x64.zip

### ISSUE THREAD

**Issue by wordlessly** [brave/brave-browser#4223]
## Description 

Brave offers releases in the form of zip archives for all OSses.

Firefox does the same and I highly applaud this practice. You can quickly test out or even use Brave without admin rights and without actually installing it.

However, unlike Firefox, one cannot update zip-archive Brave versions. With Firefox you extract the zip and it will always check for updates and allow you to install them. Brave does not.

Technically there seems no reason to allow updates for these zip-archive installs.

**Comment by srirambv** [comment]
The zip archives are to build locally for debug. I dont believe it will check for updates.

cc: @bbondy

**Comment by wordlessly** [comment]
The zip archives are build locally for debug? What does do you mean by this?

"build" in the sense of compiling the brave binary from source code and package it all in a zip file?
"locally" means what? Aren't those zips build automatically somehow from the sources on Github and then the links added in the "release" section?
"debug" do you mean those zip archives containing a working brave binary are just meant for brave developers on Github for debugging and NOT for other developers who just wish to use brave?

For me personally installing brave by extracting a zip file is most convenient and flexible. I don't really like the official way of installing brave: https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

I find it very bad practice to modify /etc/apt/sources.list.d. Also you need admin rights which not everybody has. Either you get Brave into the offical Ubuntu repos or offer people zip-archive installs. Modifying /etc/apt/sources.list.d is no real option for a lot of people out there.

The only problem when installing via ZIP archive is the missing update functionality. Please add it!

**Comment by bsclifton** [comment]
Hi @wordlessly - the `*.zip` binaries (along with several other of our release artifacts) are intended for a developer audience. The only way to get updates on a regular basis is to use a binary which is connected to an update channel

- On macOS and Windows, this update channel is handled by Omaha. You'd need to use a binary which properly checks against our update server (not all the binaries on the releases page do). Users are safe to use the binaries on brave.com/download

- On Linux, we default to the package management for the given OS (dnf, yum, apt/apt-get). This matches what Chromium does and is the most "linux-like" experience, in my opinion

I don't believe we have plans to offer a Linux download which updates itself independent of the distro's package manager. Therefore, I'll close this issue as `wontfix`. Hope this helps
