### ISSUE TITLE
where to get stable v1.63.126 (Chromium 121.0.6167.57)

### ISSUE THREAD

**Issue by icesmartjuan** [brave/brave-browser#42233]
### Description

Hi, 
where can I get the stable v1.63.126 (Chromium 121.0.6167.57)? From https://github.com/brave/brave-browser/releases/tag/v1.63.126, it 
```Beta v1.63.126 (Chromium 121.0.6167.57),*This is NOT the release (stable) channel version of Brave.``` but not sure where to get the stable version.. 
thank you!

### Steps to reproduce

1. 
2. 
3. 

### Actual result

Hi, 
where can I get the stable v1.63.126 (Chromium 121.0.6167.57)? From https://github.com/brave/brave-browser/releases/tag/v1.63.126, it 
```Beta v1.63.126 (Chromium 121.0.6167.57),*This is NOT the release (stable) channel version of Brave.``` but not sure where to get the stable version.. 
thank you!

### Expected result

Hi, 
where can I get the stable v1.63.126 (Chromium 121.0.6167.57)? From https://github.com/brave/brave-browser/releases/tag/v1.63.126, it 
```Beta v1.63.126 (Chromium 121.0.6167.57),*This is NOT the release (stable) channel version of Brave.``` but not sure where to get the stable version.. 
thank you!

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Hi, 
where can I get the stable v1.63.126 (Chromium 121.0.6167.57)? From https://github.com/brave/brave-browser/releases/tag/v1.63.126, it 
```Beta v1.63.126 (Chromium 121.0.6167.57),*This is NOT the release (stable) channel version of Brave.``` but not sure where to get the stable version.. 
thank you!

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by valynor** [comment]
Please do not try to use a many months old browser on the Internet for whatever reason. 
It contains dozens of unpatched bugs and it is NOT safe to use under any circumstances.
