### ISSUE TITLE
Updating from an older version fails to enable ads

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4224]
## Description 

Updating from an older version fails to enable ads

## Steps to Reproduce

   1. Install an older build say (0.58.21)
   2. Enable Rewards. ensure ads is not available
   3. Upgrade to 0.63.48
   4. Ads shows sorry not available for your region even if the criteria matches

## Actual result:

Updating from an older version fails to enable ads

## Expected result:
Should enable ads post upgrade

## Reproduces how often: 

Easy 

## Miscellaneous Information:

Issue reproduced on all platforms. 
cc: @tmancey @ryanml @jsecretan

**Comment by LaurenWags** [comment]
Encountered #4404 while testing

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.64.74 Chromium: 74.0.3729.131 (Official Build) (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2340
* Verified if you update from 0.58.21 to 0.63.55, you encounter the issue as described, but when you update to 0.64.74 on `test` channel the issue no longer reproduces, you will encounter scenario 1 as described in #4404 
* Updating from 0.58.21 and 0.59.35 to 0.64.74 directly (skipping 0.63.x versions) no longer reproduces the issue but does encounter scenario 2 from #4404 
* Updating from 0.60.45, 0.61.51, 0.62.51 directly (skipping 0.63.x versions) no longer reproduces the issue, also #4404 is not encountered
