### ISSUE TITLE
Unlimited redirects on some sites in Incognito

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#42253]
### Description

Test sites:
- http://www.old-omegas.com/catde59.html 
- http://www.roadsidepeek.com/
- http://www.musemuse.jp/
- http://blog.livedoor.jp/kinisoku/

Not on Chrome Incognito, these sites show an interstitial instead:

![Image](https://github.com/user-attachments/assets/450c5234-426a-44c8-a1ca-625fbcdcc0dd)

See also https://sourcegraph.com/search?q=context:global+%2F(BASE_FEATURE%7CBASE_DECLARE_FEATURE)%5C((%5Cs*%5Cw%2B%2C)%3F%5Cs*(k%7C%5C%22)%3FHttpsFirstModeIncognito(Feature)%3F(%5C%22)%3F%5Cs*(%2C%7C%5C))%2F+repo:%5E(github%5C.com%2Fbrave%2Fbrave-core%7Cgithub%5C.com%2Fchromium%2Fchromium)%24+file:.*(.cc%7C.h%7C.mm)(.patch)%3F

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

1.71.121

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by arthuredelstein** [comment]
**QA suggestions**

Try the above test sites, as well as http://http.badssl.com.

1. Confirm that incognito windows show an interstitial page, and you can continue to an insecure version of the site.
2. Confirm that normal windows do not show an interstitial page by default, but you can force it to show an interstitial by setting the HTTPS upgrade to "Strict" per-site or globally.

**Comment by kjozwiak** [comment]
The above requires `1.73.90` or higher for `1.73.x` verification 👍

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Galaxy Z Fold 6` using version(s):
```
Device/OS: Galaxy Z Fold 6 / q6quew-user 14 UP1A.231005.007 release-keys
Brave build: 1.73.90 
Chromium: 131.0.6778.69 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/42253#issue-2653869957 and https://github.com/brave/brave-browser/issues/42253#issuecomment-2477686361
2. *Verify*

**ACTUAL RESULTS:**
- Verified that in the `Standard` tab with `Upgrade to HTTPS` set to `default` test websites loaded without any issues, and `interstitial page` is not shown. 
- Verified that in the `Standard` tab with `Upgrade to HTTPS` set to `strict` the `interstitial page` is shown for the test website. Tapping `Continue to site` loads the webpage without any issues. 

---------------------------

`Standard tab. Upgrade to HTTPS (default)`

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/3e0aaa21-07b6-4cf0-ad84-ed2ee34b1bf3) | ![2](https://github.com/user-attachments/assets/aa688791-f476-4891-b873-73b84100b57e) | ![3](https://github.com/user-attachments/assets/afde0b50-84bd-4339-b9d9-0a0cffebe5d2) | ![4](https://github.com/user-attachments/assets/d567a5c3-e98d-4bf8-ae06-515aa54baa40) | ![5](https://github.com/user-attachments/assets/ff0819ed-e7ac-441a-aafc-4485319ffa00) |

`Standard tab. Upgrade to HTTPS (strict)`

|1|2|3|4|5|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/ed9e9d60-2062-4558-85d9-dab825467c61) | ![2](https://github.com/user-attachments/assets/ccf83e8b-470f-48cc-85c4-1c8bcb430c36) | ![3](https://github.com/user-attachments/assets/de8b1626-08fa-4cf4-a1d7-0246795f7e11) | ![4](https://github.com/user-attachments/assets/b5bb35b6-1807-4cf2-9711-861e7d848e11) | ![5](https://github.com/user-attachments/assets/aee738b3-9f86-40d5-91f8-007ac3440cab) |
| ![1](https://github.com/user-attachments/assets/ed9e9d60-2062-4558-85d9-dab825467c61) | ![2](https://github.com/user-attachments/assets/79e444fd-fda7-4843-a5e4-6712f6afb958) | ![3](https://github.com/user-attachments/assets/9e8920ec-ab43-4ae6-bc1c-a58088eb7595) | ![4](https://github.com/user-attachments/assets/d571b890-67ff-4285-ad1c-4436c65f87a8) | ![5](https://github.com/user-attachments/assets/6c7b76ab-258e-40a0-93ee-bb3d70c5ed11) |
