### ISSUE TITLE
Squid provider doesn't generate quote for all token pairs

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#42256]
### Description

Squid provider doesn't generate quote for all token pairs

### Steps to reproduce

1. Select Swap
2. Select BAT in Swap Token
3. Select LINK for Swap To token
4. Change provider to Squid 
5. Enter Swap amount
6. Review Swap remains disabled
7. Change tokens to USDT->USDC, quote is generated

### Actual result

https://github.com/user-attachments/assets/ea320682-f47a-4d87-b60a-365bec746fd0

### Expected result

Should be able to get quote for all token pairs

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.74.3 Chromium: 131.0.6778.39 (Official Build) beta (64-bit)
-- | --
Revision | 0ce9628041e549979e5c522f7ec10ee1f5470182
OS | Windows 11 Version 23H2 (Build 22631.4317)

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @onyb

**Comment by kjozwiak** [comment]
The above requires `1.74.9` or higher for `1.74.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.9 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | 30ceb433b8a77b995214506d3d862edb3220614b
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from issue description
- Verified Squid provider generates quotes for all token pairs

https://github.com/user-attachments/assets/a8ece8b0-9b32-4ae8-bdcf-1aa0bf6ff3a9
