### ISSUE TITLE
Page content refine network error

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#42251]
Server responds `"{\"type\":\"error\",\"error\":{\"type\":\"50001\",\"message\":\"'NoneType' object has no attribute 'stop_sequences'\"}}"`
when sending refined page content.

STR:

1. Make sure brave://flags/#brave-ai-chat-page-content-refine is enabled
2. Choose Mixtral model
3. Navigate to content will be truncated site ex. https://www.brianbondy.com/blog/187/cocodona-2024
4. Ask a question like "Who was the pacer?"
5. Showing network error

**Comment by kjozwiak** [comment]
The above requires `1.74.9` or higher for `1.74.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.74.11 Chromium: 131.0.6778.85 (Official Build) beta (64-bit) 
Revision	c777fe11bc7afc00156e58af64a6a5bb9559da7d
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
* Reproduced the network error by installing version `1.74.8` and following STR in issue description.
* Ensured that page content refinement is working when upgrading to version `1.74.11`

`1.74.8` | `1.74.11`
---|---
![Image](https://github.com/user-attachments/assets/c13989df-0358-409a-add6-6c1a18a4b33b) | ![Image](https://github.com/user-attachments/assets/d1f872d3-46b0-49f3-92c3-bf1c11d1f4ba)

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7.2
Brave build: 1.74 (13)
BraveCore: 1.74.13 (131.0.6778.85)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/42251#issue-2653735741
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the page content refinement is working with a clean profile and when upgrading to the new version.

---------------------------

|Reproduced with `1.72.96`|Verified with `1.74.13`|Verified with `1.74.13`|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/230236d2-bb29-4982-bc9f-135ea7970595) | ![2](https://github.com/user-attachments/assets/e3d3ee65-3484-4d3a-9f36-d8f7452193aa) | ![3](https://github.com/user-attachments/assets/f86552ab-63c2-476b-b1eb-6c692bfab556) |
