### ISSUE TITLE
Change quick search engines view bg color

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#42267]
### Description

Based on the feedback here : https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1731160380504929 in this issue, we need to change the bg color of quick search engines view to match address bar bg. 

### Steps to reproduce

1. Install brave
2. Tap on address bar
3. Observe quick search engines view bg

### Actual result

![Image](https://github.com/user-attachments/assets/031831a9-1965-459f-9328-d6a34ebf75ba)

### Expected result

![Image](https://github.com/user-attachments/assets/80ae4469-7030-4e07-9e7a-e84f94e95368)

### Reproduces how often

Easily reproduced

### Brave version

Brave nightly version : 1.75.9

### Device

- Brand/model: Pixel 
- Android version: 7 Pro

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.74.13` or higher for `1.74.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240925.009 release-keys
Brave build: 1.74.13 
Chromium: 131.0.6778.85 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/42267#issue-2655806113
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the background color is updated according to the design.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/7cb1f225-376d-4807-8feb-7fd1e2a01cc5) | ![2](https://github.com/user-attachments/assets/0cceda2e-5fc5-4d14-a8ad-3be5609ef687) | ![3](https://github.com/user-attachments/assets/073b89c4-bf84-4dba-ba20-93fe517f88b1) |
