### ISSUE TITLE
[iOS] - BraveVPN crashes if purchasing Leo AFTER VPN

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#42268]
### Description

- When a user purchases Leo AFTER purchasing VPN, if the user goes to VPN settings, it will crash

### Steps to reproduce

1. Purchase VPN
2. Purchase Leo
3. 3-dot menu -> Settings -> Brave VPN

### Actual result

- Crash

### Expected result

- Should not crash

### Reproduces how often

Easily reproduced

### Brave version

- 1.62+

### Device/iOS version

- iPhone

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.73.90` or higher for `1.73.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone XR` running `iOS 17.7.1` using version `1.73 (90)`

* Ensured crash does not happen when accessing BraveVPN settings using STR in https://github.com/brave/brave-browser/issues/42268#issue-2655826782

`Leo` | `Brave VPN`
---|---
![Image](https://github.com/user-attachments/assets/2467b50a-18e2-43bf-8f04-102f1136f4d3) | ![Image](https://github.com/user-attachments/assets/937f1fee-85ff-45c2-9a32-e7694e3812ec)
