### ISSUE TITLE
Ads not available in my United States on Linux Browser

### ISSUE THREAD

**Issue by Programatic** [brave/brave-browser#4226]
## Description 
The Browser is freshly updated from the AUR and does not let me use ads in my country. I am in the United States and just to be sure I tested it from my laptop which works. 

## Brave version (brave://version info)

Brave | 0.63.48 Chromium: 74.0.3729.108 (Official Build)unknown (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Linux

![brave](https://user-images.githubusercontent.com/41210901/56707759-34746580-66e8-11e9-8b22-f8f024a9f270.png)

**Comment by srirambv** [comment]
Was this a clean install or update on an existing install?  If updated, can you tell which version was running before the upgrade? 

Possibly related to #4224 and there are a bunch of community maintained packages on AUR and some are outdated 

cc: @tmancey

**Comment by Programatic** [comment]
I updated from a previous install. For reference, I use https://aur.archlinux.org/packages/brave-bin/ and it seems to be the one that updates the most often. When I get home I will do a full reinstall and test it out again.

**Comment by cwbriscoe** [comment]
Same thing happening with me using Ubuntu 16.04.  I live in the US and used the following instructions to install:  https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

**Comment by Programatic** [comment]
Ok, so the issue was an error in updating. To fix it, I simply uninstalled and removed my .config/BraveSoftware folder and it worked
