### ISSUE TITLE
Tabs Bar disappears until interacted with

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#42272]
### Description

On iPhone with the `Tabs Bar` set to `On` (always display), it's possible for the tabs bar to be hidden with more than 1 tab open.

### Steps to reproduce

1. Open at least 2 tabs so the tabs bar is shown
2. Enter `brave://flags` or `brave://version` in url bar
3. Dismiss the modal

### Actual result

Tabs bar is hidden

### Expected result

Tabs bar is still visible

https://github.com/user-attachments/assets/66230b82-0541-44be-ace7-9d4c7a77a677

### Reproduces how often

Easily reproduced

### Brave version

Any

### Device/iOS version

Tested on iOS 18

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.2` using version `1.75.133`

* Ensured that tabs bar is still shown when opening/closing brave internal pages such as `brave://flags` or `brave://version`
* Ensured that tabs bar is working properly using Top Bar and Bottom Bar modes.

example | example
---|---
<img width="250" src="https://github.com/user-attachments/assets/03c8454e-f985-4230-8888-9017ffb67240"> | <img width="500" src="https://github.com/user-attachments/assets/30f1b040-c3db-4c70-b77d-dc810fb2a44e">

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iOS 17.7.2` using version `1.75.136`

* Ensured that tabs bar is being displayed on iPad when enabled after upgrading if it was disabled in a previous version. 
* Ensured that opening/closing brave://flags or brave://version does not cause issues with tabs bar on iPad.

![Image](https://github.com/user-attachments/assets/e07f22b4-e59e-4fc9-aaa1-3d343d884c35)
