### ISSUE TITLE
Ugly scrollbars in Shields Panel detailed view

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#4227]
## Steps to Reproduce

   1. Open `wired.com`
   2. Open Shields Panel
   3. Click on `3rd party trackers blocked` to show detailed view

## Actual result:

![image](https://user-images.githubusercontent.com/34715963/56709188-2b9f8600-6720-11e9-9e59-96c77961b174.png)

## Expected result:
![scroll behavior](https://user-images.githubusercontent.com/2388823/56771566-e0ab6000-676b-11e9-9b85-b35e12040980.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

cc @brave/legacy_qa @cezaraugusto @karenkliu @tomlowenthal

**Comment by karenkliu** [comment]
Updated scroll behavior spec with revisions from light/dark theme update.

**Comment by cezaraugusto** [comment]
@karenkliu this is the default scroll for Windows, do we want to make it look the same way across platforms? i.e. the same as macOS?

**Comment by tomlowenthal** [comment]
No, I think we should stick with OS-specific visual idioms like scrollbars.
