### ISSUE TITLE
Slash tools not working for Leo

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#42279]
### Description

Slash tools have regressed in 1.72 in Leo chat

Breaks in https://github.com/brave/brave-browser/releases/tag/v1.72.31

### Steps to reproduce

1. Install App
2. Open Leo
3. Tap on the `[/]` icon to open slash tools window

### Actual result

![Image](https://github.com/user-attachments/assets/05be79e6-baa6-43a8-9eb2-eb8bb9eee846)

### Expected result

Slash tools should work

### Reproduces how often

Easily reproduced

### Brave version

`1.73.89` - reproducible
`1.72.31` - reproducible
`1.72.28` - NOT reproducible

### Device

- Brand/model: Samsung GS device
- Android version: 13

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.73.92` or higher for `1.73.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240925.009 release-keys
Brave build: 1.73.92 
Chromium: 131.0.6778.85 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/42279#issue-2656529875 and https://github.com/brave/brave-core/pull/26555#issuecomment-2492229960
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `slash tools` menu can be opened.
- Verified that the `slash tools` can be used when sending a query to Leo.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/5b1b4a50-5e67-41e9-8796-c069d7547a62) | ![2](https://github.com/user-attachments/assets/4b93c6ab-2b2e-4c41-902f-b04f610ee415) | ![3](https://github.com/user-attachments/assets/d2262b13-85de-469c-a0bd-077a4f84d925) | ![4](https://github.com/user-attachments/assets/1a4b3da3-514b-42ef-bc5d-bd3a148599fc) |

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.73.92 Chromium: 131.0.6778.85 (Official Build) (64-bit)
-- | --
Revision | 05f178377f490b21d73d0a9bb29c2e45040dd984
OS | Windows 10 Version 22H2 (Build 19045.5131)
```
