### ISSUE TITLE
[iOS] - Add Smart-Proxy & Kill-Switch support to Brave-VPN

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#42275]
### Platforms

all, iOS

### Description

- Update GuardianConnect SDK to 2.0.0
- Add Smart Proxy toggle in settings
- Add Kill Switch toggle in settings

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.2.1` using version `1.75 (161)`

* Ensured that `Enable Smart Proxy` & `Enable Kill Switch` toggles are added to `Brave Firewall + VPN` settings
* Ensured that tunneling is working with Smart Proxy enabled.
* Ensured that enabling Smart Proxy does not cause any issues loading webpages with VPN. 

example | example | example
---|---|---
![Image](https://github.com/user-attachments/assets/81a9b55a-8726-4041-9c74-6eb41d9267c1) | ![Image](https://github.com/user-attachments/assets/1b5569b6-c26b-4088-9742-ea15c0c0b6ca) | ![Image](https://github.com/user-attachments/assets/324951cc-7109-4a8f-9c6a-5aa92ae9ee06)

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iPadOS 17.5.1` using version `1.75 (159)`

* Ensured that `Enable Smart Proxy` & `Enable Kill Switch` toggles are added to `Brave Firewall + VPN` settings
* Ensured that tunneling is working with Smart Proxy enabled.
* Ensured that enabling Smart Proxy does not cause any issues loading webpages with VPN. 

example | example | example
---|---|---
![Image](https://github.com/user-attachments/assets/c2c5f22f-8756-42e5-8cd7-3a692f60fc88) | ![Image](https://github.com/user-attachments/assets/5c6242fb-ced9-48af-ad93-2e212f88263b) | ![Image](https://github.com/user-attachments/assets/d417a1bd-d3c1-4bb2-883d-173efbd9857c)
