### ISSUE TITLE
Add SERP entry point to Leo metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#42289]
Add the "'Open in Leo' search engine result action" to two existing Leo metrics: `Brave.AIChat.AcquisitionSource` and `Brave.AIChat.MostUsedEntryPoint`

cc @mattmcalister

**Comment by LaurenWags** [comment]
Requires 1.73.91 or higher for verification 👍🏻

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.73.91 Chromium: 131.0.6778.85 (Official Build) (64-bit)
-- | --
Revision | 35427fa72a008a7e861fa9828e07a0ba2cd46ebd
OS | Windows 10 Version 22H2 (Build 19045.5131)
```
- Verified the test plan from https://github.com/brave/brave-core/pull/26543#issue-2657429959
- Confirmed that the metrics `Brave.AIChat.AcquisitionSource` response value is `6` `'Open in Leo' search engine result action` as expected
- Confirmed that the metrics `Brave.AIChat.MostUsedEntryPoint` response value is `6` `Open in Leo' search engine result action` as expected

`Brave.AIChat.AcquisitionSource` | `Brave.AIChat.MostUsedEntryPoint`
------------------------------------|----------------------------------------
![Image](https://github.com/user-attachments/assets/ac4b3d51-9262-4cc2-8b02-91be7b91ad5a) | ![Image](https://github.com/user-attachments/assets/d8db1904-42b2-4862-9360-3708e4c8a76e)
