### ISSUE TITLE
White line under address bar in new 1.73 stable update

### ISSUE THREAD

**Issue by MoeAmen** [brave/brave-browser#42286]
### Description

A thin white line is visible despite whatever theme I![Image](https://github.com/user-attachments/assets/ae13677c-33d5-4c8f-a812-8b76e785cb89)
 choose from brave settings or chrome theme store

### Steps to reproduce

Open Brave 1.73 stable

### Actual result

White line is visible

### Expected result

White line should not be visible like before the update

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.73.89

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [x] in the latest version of Chrome

**Comment by LaurenWags** [comment]
Requires 1.73.91 or higher for verification 👍🏻

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
```
- Verified the test plan from https://github.com/brave/brave-core/pull/26556
- Reproduced the issue on `1.73.89 Chromium: 131.0.6778.69` and `brave://flags/#brave-web-view-rounded-corners` disabled (this is enabled via griffin on Nightly/Beta), reproduced the issue:

Dark (default) | Light (default)
--- | ---
![Image](https://github.com/user-attachments/assets/5563889b-1a18-4716-83b1-fcca4309bf8a) | ![Image](https://github.com/user-attachments/assets/605260b3-ec16-4b1b-aca2-bb3792477a6f)


Compared above to `1.73.91 Chromium: 131.0.6778.69` and confirmed the separator line is more subdued on the various windows.

. | `1.73.89` | `1.73.91`
--- | --- | ---
Dark (default) | ![Image](https://github.com/user-attachments/assets/2b675798-0f8f-4296-9dfb-32fb944d628f) | 

Light (default) | ![Image](https://github.com/user-attachments/assets/d3831217-2cda-49ec-87be-cef373e4aa6c) | 

Dark (color) | ![Image](https://github.com/user-attachments/assets/e74cece8-1b21-487b-bfff-5aa879d1c947) | 

Light (color) | ![Image](https://github.com/user-attachments/assets/e305a7ec-5c56-4a38-8584-bba9b5b52ad1)

Private | ![Image](https://github.com/user-attachments/assets/a39782f1-4ed5-4a96-8462-390e5cd51d3d) | 

Tor | ![Image](https://github.com/user-attachments/assets/a5a7294e-bfa7-4719-879d-a11f917bbb39) |  

Webstore theme | ![Image](https://github.com/user-attachments/assets/8f0e0db7-41de-4cb8-a917-9adf22f70a00) |

**Comment by marlonjames71** [comment]
Nice! I'm glad this was fixed!

**Comment by marlonjames71** [comment]
To be clear, I'm using the beta version
