### ISSUE TITLE
[NTP Search]: On small screens the Searchbox gets wider than the screen

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#42284]
Reported by @kkarikos 

Before:
![Image](https://github.com/user-attachments/assets/c0bbfd21-8da7-4cee-867d-138419e8e619)

After:
![Image](https://github.com/user-attachments/assets/9117e008-caf6-4b8e-8667-9ae369921ce1)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.75.148 Chromium: 132.0.6834.57 (Official Build) nightly (64-bit)
-- | --
Revision | 89b8296af95dd49d78a9e46589c7d347cc02b63e
OS | Windows 11 Version 24H2 (Build 26100.2605)
```

Verified via resizing the screen to different dimensions and confirmed NTP Search widget on small screens fits the screen.

1.73.x | 1.75.x 

example | example | example 
------ | ----- | -------
![Image](https://github.com/user-attachments/assets/39f9bd80-a933-48fa-a918-e1e8e8602b9d)|![Image](https://github.com/user-attachments/assets/ddca0bd4-7c45-49e3-be8f-9484f6d0b452)|![Image](https://github.com/user-attachments/assets/c0a6f17c-d9c1-4ab8-a477-8d8c5b02bfe4)
![Image](https://github.com/user-attachments/assets/afbf5bb6-3442-4361-96a8-894e509185f2)|![Image](https://github.com/user-attachments/assets/8840abe7-4db3-46ff-864f-98b81b25dae7)|![Image](https://github.com/user-attachments/assets/5257e40b-9808-4271-8667-b291013756d5)
