### ISSUE TITLE
Add Shielded Labels to ZEC Tokens Throughout Wallet

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#42285]
### Platforms

all, Windows, macOS, Linux, Android

### Description

We need to add a `Shielded` label to all shielded `ZEC` tokens throughout the Brave Wallet.

![Image](https://github.com/user-attachments/assets/61833072-f507-44ae-95e7-9e03224f62ee)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.75.156 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | 036ac4040dc50d4bd49b3438e20ab90686218543
OS | Windows 11 Version 23H2 (Build 22631.4602)

- Verified steps from [brave/brave-core#26557](https://github.com/brave/brave-core/pull/26557)
- Verified Shielded label is shown on Portfolio and Accounts tab
- Encountered [#43200](https://github.com/brave/brave-browser/issues/43200)

https://github.com/user-attachments/assets/18697872-fc5a-420b-8dbb-c99df7cd0229
