### ISSUE TITLE
Different number of scripts blocked in main view and detailed view

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#4228]
## Steps to Reproduce

   1. Open `https://www.poboczem.pl/video,vId,2681150`
   2. Open Shields Panel
   3. Blocked the scripts

## Actual result:

Different number of scripts blocked in main view and detailed view
Main view shows 18 scripts blocked:
![image](https://user-images.githubusercontent.com/34715963/56709648-a1a4ec80-6722-11e9-843a-ab97b90d1e87.png)
Detailed view shows 3 scripts blocked
![image](https://user-images.githubusercontent.com/34715963/56709668-baad9d80-6722-11e9-98d0-de06de226b35.png)

## Expected result:
The same number of scripts blocked in main view and detailed view

Edit: The detailed view does not show actual scripts blocked, but it shows domains only. Maybe we should rename `Scripts blocked` to `Domains blocked`.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

cc @brave/legacy_qa @tomlowenthal

**Comment by srirambv** [comment]
This has always been the behaviour. Was briefly discussed here https://bravesoftware.slack.com/archives/CD495CWLR/p1548828086062300

cc: @karenkliu

**Comment by karenkliu** [comment]
The block count should count individual scripts blocked both on the main panel and scripts detail view. Detail view of scripts should have a matching number. @cezaraugusto mentioned he is able to show each individual script now, so that will help clear up the confusion; if there are 18 blocked scripts the user can go into the scripts detail view to see 18 items listed.

**Comment by btlechowski** [comment]
Awesome work!

Verification passed on

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Ubuntu 18.04 LTS

Used test plan from https://github.com/brave/brave-core/pull/2485
Used test plan from the description.
There were 19 blocked scripts in main panel and 19 scripts listed in detailed view
![image](https://user-images.githubusercontent.com/34715963/62174430-3b8bbf00-b33a-11e9-9fd9-ce555eec3303.png)
![image](https://user-images.githubusercontent.com/34715963/62174467-5a8a5100-b33a-11e9-8b22-b72ec1457dfe.png)
