### ISSUE TITLE
Add youtube in quick search engines

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#42292]
We need to add `youtube` in quick search engine right after `google` as the initial position. 
If the user changes the order for `youtube`, it should reflect the change. 

Follow PR for test plan.

**Comment by kjozwiak** [comment]
The above requires `1.74.13` or higher for `1.74.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240925.009 release-keys
Brave build: 1.74.18 
Chromium: 131.0.6778.85 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/26547#issue-2657950788
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `YT` SE/Icon is shown in the QSE panel right after `Google search` by `default`.
- Verified that `YT` SE is shown the QSE settings right after `Google search` by `default`.
- Verified that the user can change the order, and the `YT` search reflects the changes.
- Verified that the `YT` search works via the QSE panel.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/d81f0f80-15c1-4c52-967f-85a14d22fc4d) | ![2](https://github.com/user-attachments/assets/078aec93-7ae1-4045-a290-768544901955) | ![3](https://github.com/user-attachments/assets/4767e514-2e5d-411a-b302-9033cb41881f) |
| ![1](https://github.com/user-attachments/assets/216a7ccc-2451-4f70-bc8d-1466cfc81751) | ![2](https://github.com/user-attachments/assets/8bcccaec-19d8-4ba0-899d-8a39abba6055) | ![3](https://github.com/user-attachments/assets/529d1e59-ff5f-4611-9248-f338a3d28845) |
