### ISSUE TITLE
Update QSE on default search engine changed

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#42296]
This issue is match the behaviour for quick search engines with IOS for default search engines.  

- [ ] Default search should not be able to disable/reorder default SE in quick search settings. (We need to hide the default search engine from QSE settings, similar to IOS)
- [ ] Default SE should appear right after `Leo` in quick search engines view when user changes the default search engine from settings
- [ ] Default SE should always appear as 2nd item quick search engines view

**Comment by kjozwiak** [comment]
The above requires `1.74.13` or higher for `1.74.x` verification 👍 @Uni-verse went through the above on `Nightly` and added some STR/Cases that can be used for `1.74.x` verification via https://github.com/brave/brave-core/pull/26548#issuecomment-2498816754.

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240925.009 release-keys
Brave build: 1.74.13 
Chromium: 131.0.6778.85 (Official Build) beta (64-bit) 
```

Filed follow-up issue #42573
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/42296#issue-2658625012
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `default` search can't be disabled/reordered in quick search settings.
- Verified that the `default` SE appeared right after `Leo` in the quick search engines view when the user changes the default search engine from settings.
- Verified that the `default` SE always appears as the 2nd item in the quick search engine view.
- Verified the same for `Standard` and `Private` tabs.

---------------------------

### `Default` settings

|`Search engine` settings|`QSE` settings|'Standard' tab|`Private` tab|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/e6d9756d-9a75-4ebf-98e2-51d14cd61491) | ![2](https://github.com/user-attachments/assets/8febceb0-0d8e-4e85-b10b-4a9ef7a12c31) | ![3](https://github.com/user-attachments/assets/abae6814-58ca-4c49-8463-1cd4f6ab27b5) | ![4](https://github.com/user-attachments/assets/5d80dc7f-c6e3-411b-8c3c-13d9340e3129) |

### `Non-Default` settings

|`Search engine` settings|`QSE` settings|'Standard' tab|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/a2225941-0c83-4c6e-81c9-9eb85540f453) | ![2](https://github.com/user-attachments/assets/6b82a561-2eeb-4e17-9252-dc3ea18a575c) | ![3](https://github.com/user-attachments/assets/482c867d-9763-4fb3-8d03-291e9f8407b9) |
|`Search engine` settings|`QSE` settings|`Private` tab|
| ![1](https://github.com/user-attachments/assets/de56e550-f754-4ac0-862e-73afb7815033) | ![2](https://github.com/user-attachments/assets/5932184b-7fdc-4fc6-829a-3fe1709d77ec) | ![3](https://github.com/user-attachments/assets/e6dd1be2-9844-49da-9861-4e241327543f) |
