### ISSUE TITLE
Spotify doesn't work in the debug version.

### ISSUE THREAD

**Issue by chuzilaolin** [brave/brave-browser#42290]
### Description

Excuse me, I followed the steps in the README and built Brave using 'npm run build -- Debug.' I enabled Widevine permissions and ensured that Widevine has been downloaded to my data directory, but when I opened Spotify, I found that I couldn't play music.

### Steps to reproduce

1. use 'npm run build -- Debug' to build debug version.
2. open this site, 'https://open.spotify.com/'.
3. allow widevine permissions.

### Actual result

spotify cant not to paly music.

### Expected result

play music.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

![Image](https://github.com/user-attachments/assets/83b631f5-fc69-458a-9312-eea098c88885)

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by bsclifton** [comment]
@chuzilaolin I see you closed this one - quick heads up that Spotify likely requires Widevine. You'll want to make sure that is installed and enabled and then try. Thanks!
