### ISSUE TITLE
Change quick search engines settings position

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#42291]
### Description

Currently we are showing quick search engines option at the end in search engines settings. With this issue, we need to match the position to what we have in IOS.
We need to place quick search engines options right after `Standard tab`/`Private tab`.

### Steps to reproduce

1. Install Brave
2. Go to settings -> Search engines
3. Observe that Quick search engine option is at the end

### Actual result

![Image](https://github.com/user-attachments/assets/f58af22e-459d-4606-a429-5635fd33687e)

### Expected result

![Image](https://github.com/user-attachments/assets/a5920fa9-10ec-4864-b38d-315743611ad9)

### Reproduces how often

Easily reproduced

### Brave version

Brave nightly version : 1.75.9

### Device

- Brand/model: Pixel 7 pro
- Android version: 15

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.74.13` or higher for `1.74.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240925.009 release-keys
Brave build: 1.74.13 
Chromium: 131.0.6778.85 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/42291#issue-2657629932
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Quick-Search Engines` settings located between `Private Tab` and `Show browser suggestions` settings
- Verified the same for `fresh` and `upgraded` profiles.
- Verified that the `Quick-Search Engines` settings screen can be opened and closed without any issues.

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/8ae8ab04-3489-469b-8444-f19147507f09) | ![2](https://github.com/user-attachments/assets/5f9dc311-e56e-4ce2-bc08-f1f78b8940a3) |
| ![1](https://github.com/user-attachments/assets/6b2effb9-be37-44c7-a43f-b9525fc53a79) | ![2](https://github.com/user-attachments/assets/c7f62e95-b116-4eb4-b680-abbec97541c5) |
