### ISSUE TITLE
Prompt user to close Brave before importing from a Brave profile

### ISSUE THREAD

**Issue by garrettr** [brave/brave-browser#423]
## Description 

Follow-up for brave/brave-core#185.

The new BraveImporter needs a BraveProfileLock equivalent to the ChromeProfileLock implemented for ChromeImporter in brave/brave-core#101.

Brave browser-laptop is based on Muon/Chromium, so we should be able to reuse the same approach and probably also code from ChromeProfileLock for BraveProfileLock. I also want to refactor the lock dialog-related code in `BraveExternalProcessImporterHost` and `brave::importer::ImportLockDialogView` to minimize duplication of code and support long-term maintainability.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7
