### ISSUE TITLE
[iOS] - VPN Receipt Not Found when Linking

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#42302]
### Description

- When Linking VPN for some reason the receipts are not found.

### Steps to reproduce

1. Purchase VPN on iOS
2. Attempt to link VPN to the Website

### Actual result

- Linking fails with receipt not found error.

### Expected result

- Linking should work

### Reproduces how often

No steps to reproduce

### Brave version

N/A

### Device/iOS version

Any

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

I can't reproduce this bug at all. Keep being told the receipt is missing on iOS, which I highly doubt, otherwise VPN wouldn't work at all.

**Comment by kjozwiak** [comment]
The above requires `1.73.90` or higher for `1.73.x` verification 👍
