### ISSUE TITLE
Ads enable is NOT controlled by OS Region

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#4230]
## Description 

As per the new logic, Ads are enabled based on the IP address, OS region, and locale. I have set the Region as "India" (Ads not supported country) in Windows OS. Ads are enabled and I am able to view the Ads for the Region "India"

## Steps to Reproduce

   1. Set the Region as `India` in "Region and Language settings"
   2. Set the language as `English (United States)`
   3. VPN is set to `US IP`
   4. Launch brave and enable rewards
   6. Verify that there is no message display for "Ads are not supported for this region"
   5. Open `brave.com`, stay on site for 15 sec and then move the cursor
   6. Ads are popping up
   

## Actual result:

Ads are enabled for the Region "India"
There is no message display for Ads not supported for this region. 

## Expected result:
Ads are not enabled for the Region India

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Windows 10 OS Build 17134.523

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa

**Comment by srirambv** [comment]
This is expected. Locale is set to English(US) which satisfies the criteria to allow ads. 

cc: @tmancey

**Comment by GeetaSarvadnya** [comment]
Closing the issue as IP + OS Locale satisfy the criteria
