### ISSUE TITLE
Ad Notification has a settings button in Gnome

### ISSUE THREAD

**Issue by fooforever** [brave/brave-browser#4231]
## Description 

When an ad notification pop up appears in Gnome it has a settings button in the notification that takes you to the ad site, exactly the same as clicking just the notification does. Don't know if the notification is meant to have a button but its misleading that its labelled 'Settings' and just takes you to the ad, was expecting to go the brave://rewards page or something. I think the button either needs removing, relabelling, or its action changing    

## Steps to Reproduce

   1. Enable ads
   2. Wait for a notification
   3. Click the button

## Actual result:

![Screenshot from 2019-04-25 11-03-00](https://user-images.githubusercontent.com/665772/56728381-91a10300-674a-11e9-95d8-c4e3abaf3321.png)

## Expected result:
Button actually goes to ad settings

## Reproduces how often: 

All add notifications - easily reproduced

## Brave version (brave://version info)

Brave | 0.63.48 Chromium: 74.0.3729.108 (Official Build)unknown (64-bit)
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Manjaro Linux with Gnome 3.32.1

**Comment by srirambv** [comment]
Ideally it should open the system notification settings to turn on/off.

**Comment by jwsp1** [comment]
Facing the same issue (using ZorinOS) and the ad also does not go away automatically, as it does in windows after ~5 sec.

**Comment by srirambv** [comment]
@jwsp1 ads notification persist for a longer duration this is expected behaviour

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.119 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/2570
![image](https://user-images.githubusercontent.com/34715963/62659401-8d9c9800-b96b-11e9-9969-3edd13623961.png)
