### ISSUE TITLE
Missing site settings permissions entries on Android

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#42313]
Some items are missing site settings => permissions entries on Android.

### Steps to reproduce

1. open [m.youtube.com](http://m.youtube.com)
2. press the most left button at the url bar
3. at the menu choose `Permissions` item

### Actual result

There are only two items:
* `Autoplay`;
* `Sound`.
The own built debug version crashes at https://github.com/brave/brave-core/blob/master/android/java/org/chromium/base/BraveReflectionUtil.java#L46, at `assert false;`

![Image](https://github.com/user-attachments/assets/38dd9e68-7d1f-4f17-8a5a-b6d5e35b5a9e)

### Expected result

There are these at `Permissions`:
* `Autoplay`
* `Google Sign-in`
* `Localhost access`
* `Sound`.

No crash at own debug build

![Image](https://github.com/user-attachments/assets/b5bf8b75-ac46-4e30-9f4d-f0ca491c20ed)

### Reproduces how often

Easily reproduced

### Brave version

`Release 1.71.123`, `Nightly 1.75.18`

### Device

- Brand/model: Pixel 6
- Android version: 15

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.73.90` or higher for `1.73.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Galaxy Z Fold 6` using version(s):
```
Device/OS: Galaxy Z Fold 6 / q6quew-user 14 UP1A.231005.007 release-keys
Brave build: 1.73.90 
Chromium: 131.0.6778.69 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/42313#issue-2661620834
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Permissions` shows: `Autoplay`, `Google Sign-In`, `Localhost access` and `Sound`.
- Verified that these permissions can be turned on and off.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/404d00ca-bbfb-428f-9d4f-98cc3de23503) | ![2](https://github.com/user-attachments/assets/b68461f5-def3-442c-bdc8-b6b4aa0a8d22) | ![3](https://github.com/user-attachments/assets/0287361c-4bce-4d11-8584-7d721c160713) |
