### ISSUE TITLE
[ads] Add SmartNTT epoch and numerical condition matcher defaults

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#42321]

**Comment by LaurenWags** [comment]
Requires 1.73.91 or higher for verification 👍🏻

**Comment by btlechowski** [comment]
Verification passed on Brave v1.73.91 on Lenovo TB-8506FS (Android 11.0)


#### matcher exists

<details>

matcher:
```
                    "conditionMatchers": [{
                            "prefPath": "tab_stats.window_count_max",
                            "condition": "[R=]:1"
                        }
                    ],
```

Verified ad was served

![Image](https://github.com/user-attachments/assets/43b6fac2-3276-4c4c-b4e7-2f168dd56c23)


</details>


#### matcher does not exist - [R]


<details>

matcher
```
                    "conditionMatchers": [{
                            "prefPath": "tab_stats.window_count_maxFAIL",
                            "condition": "[R=]:0"
                        }
                    ],
```

![Image](https://github.com/user-attachments/assets/8e79b3c2-9a76-490a-9d2f-10dd44179a35)


</details>
