### ISSUE TITLE
Brave Panel not updated with publisher info after enabling Rewards

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#4232]
## Steps to Reproduce

   1. Enable rewards
   2. Disable rewards
   3. Open `https://kjozwiak.github.io/`
4. Enable rewards through Rewards Panel

## Actual result:

Publisher info is not shown in Rewards Panel

Note: Reopening Rewards Panel fixes the issue

![4232](https://user-images.githubusercontent.com/34715963/56731531-fe23fe00-675a-11e9-8066-2e5298aef9f7.gif)

## Expected result:
Publisher info is shown in Rewards Panel

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

cc @brave/legacy_qa @NejcZdovc @ryanml

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.106 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2453 and STR from above.
