### ISSUE TITLE
Captcha in Rewards Panel is cut in some languages

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#4233]
## Steps to Reproduce

   1. Change Brave locale to `Polish`
   2. Enable rewards
   3. Claim grant through Brave Panel

## Actual result:

Captcha in Rewards Panel is cut at the bottom
![image](https://user-images.githubusercontent.com/34715963/56732797-b7380780-675e-11e9-9fd6-87f4b6121910.png)
![image](https://user-images.githubusercontent.com/34715963/56732808-bdc67f00-675e-11e9-97ae-fc289f265fef.png)

I believe the reason is the `Prove that you are a human` and `Hmm… Not Quite. Try Again.` text, which spans over two rows in polish

Note: issue does not reproduce on `brave://rewards` page

## Expected result:
Captcha in Rewards Panel is not cut

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

cc @brave/legacy_qa @NejcZdovc
.

**Comment by srirambv** [comment]
Similar to #2956

**Comment by NejcZdovc** [comment]
fixed with https://github.com/brave/brave-browser/issues/7597
