### ISSUE TITLE
Brave browser is crashing wallets and miners

### ISSUE THREAD

**Issue by Byrd1083** [brave/brave-browser#4234]
## Description 

I have Siacoin wallet open, and I also use Rainbow miner. They both run fine in the background. As soon as I open Brave browser using version Version 0.66.21 2 out of 3 times It will crash itself along with browser extensions being reported to have crashed. I restart it a few times and it will open then close fast. Additionally my Siacoin deamon fails and my rainbow miner will force close without any logged errors leading me to believe the browser is crashing out.

## Steps to Reproduce

   1. Run Siacoin wallet fully synced
   2. Run rainbowminer
   3. Run brave browser and crash

## Actual result:

None to show

## Expected result:
Crashing apps and deamons.

## Reproduces how often: 

Happens at least 2 out of 3 times of replicating the scenario.

## Brave version (brave://version info)

Version 0.66.21

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
@bbondy do extension requests get filtered by ablocking? ex: if extensions are using a known miner script (even if user wants it), could it possibly be filtered out?

@Byrd1083 as a possible work-around, you can try allowing all ads (globally). This isn't ideal, but it would be good to know if doing this resolves the problem for you:
<img width="705" alt="Screen Shot 2019-04-26 at 11 22 23 AM" src="https://user-images.githubusercontent.com/4733304/56828194-a4ccd500-6815-11e9-8ae1-a7a2a55ca27e.png">

**Comment by bbondy** [comment]
I don't think extensions will be blocked, unless the extension does something like add a dom element for a script inside the page which loads in the context of the page.

**Comment by iefremov** [comment]
@Byrd1083 please reopen if this is reproducible
