### ISSUE TITLE
[ads] Add SmartNTT epoch condition matcher defaults

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#42351]

**Comment by btlechowski** [comment]
Verified with

Brave | 1.75.147 Chromium: 132.0.6834.57 (Official Build) nightly (64-bit)
-- | --
Revision | 6ca80c5d3414773bba6275ff7109f0cb01233795
OS | Linux

<details>




</details>

**Comment by btlechowski** [comment]
Verification passed on Brave v1.75.164 on Lenovo TB-8506FS (Android 11.0)

<details>



</details>
