### ISSUE TITLE
New tabs are not shown

### ISSUE THREAD

**Issue by caspertone2003** [brave/brave-browser#4235]
## Description 

I  am running 0.63.48 @W10-x64
When there are too many tabs open, new opened tabs are not shown.
Currently I have 15 pined tabs (that are wider in size than unpinned ones) and 19 non pinned ones. If I open another one I can not reach it after going to another of the opened tabs...

## Steps to Reproduce

Already described
## Actual result:
Already described

## Expected result:
Too see all open tabs. In brave-desktop there was the posibility of showing set of tabs with parameter open tabs per set (6, 8, 12,...)

## Reproduces how often: 
Allways
## Brave version (brave://version info)
Already provided

## Version/Channel Information:
Release channel

**Comment by srirambv** [comment]
This is a limitation on Chromium code. Once you hit the threshold new tabs are not shown. Tab pages are not yet implemented on brave-core.

cc: @bsclifton @bbondy

**Comment by caspertone2003** [comment]
Thanks for caring
CT

**Comment by rebron** [comment]
reminder to dupe against tab pages feature.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/35

I'll give a +1 on your behalf, @caspertone2003 😄

**Comment by caspertone2003** [comment]
> Closing in favor of #35
> 
> I'll give a +1 on your behalf, @caspertone2003 😄

Thanks.
In any case it is a pitty that the comeback of such iconic brave (desktop) features as session tabs and tab handling are targeted for post 1.x ...
I mainly switched to brave for those... now looks that other browsers offer those... but not brave for ... the next 18months?
CT
