### ISSUE TITLE
Opening a Playlist item in a private tab opens it in regular mode the first time

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#42357]
### Description

In the new Playlist UI if try to open an item in a private tab via the long press menu, the first time you do this the tab is opened in regular mode despite the correct private flag being passed in when creating the Tab

### Steps to reproduce

1. Prefix: Have an item in Playlist
2. Open Playlist and long press on an item and tap "Open in Private Tab"

### Actual result

The tab is opened in regular mode anyways, but only the first time you do it.

### Expected result

Should open in private mode

### Reproduces how often

Easily reproduced

### Brave version

1.71+

### Device/iOS version

N/A

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.73.91` or higher for `1.73.x` verification 👍

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7.1
Brave build: 1.73 (91)
BraveCore: 1.73.91 (131.0.6778.85)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/42357#issue-2669751695
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the video from `Playlist` is opened in the `Private tab`

---------------------------

https://github.com/user-attachments/assets/d0041f80-308b-4c49-b44a-7496888cee52
