### ISSUE TITLE
Crash Report - related to Crash Report #41906

### ISSUE THREAD

**Issue by Nolyek** [brave/brave-browser#42362]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.73.89 Chromium: 131.0.6778.69
Operating System: Linux 6.11.7-zen1-1-zen

URL (if applicable) where crash occurred:

https://www.youtube.com/watch?v=b1Yp46KCkRc

Can you reproduce this crash?

Usually yes by just doing normal tasks

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open Browser
2. Navigate to Youtube
3. Watch any youtube video for an extended period
4. Profit

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/ac9f1400-8605-eb0c-0000-000000000000

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/41906
