### ISSUE TITLE
AI Chat notice for conversation storage

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#42360]
There should be a notice that chats are now stored locally

![Image](https://github.com/user-attachments/assets/4e919957-251c-41bd-bcfc-2e68b80ddd72)

- Shows only for a single page load
  - Makes sure it's been on-screen for at least 4 seconds
- Dismissible immediately by the user

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.159 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | a7b6f5093a2dad31fc3f56241a7d55be255e69e2
OS | Windows 11 Version 23H2 (Build 22631.4602)

- Verified steps from [brave/brave-core#26678](https://github.com/brave/brave-core/pull/26678)
- Verified conversation history notification is shown on Leo when using Leo for the first time
- Verified the notification is only shown once. Closing the notification doesn't show again when Leo is opened. Resetting Leo also doesn't show the message again
- Verified disabling `Store my conversation history` under `brave://settings/leo-ai` disables the conversation history and updates the message
- Verified able to enable conversation history from Leo page

https://github.com/user-attachments/assets/ae41a0a1-ad3d-4da1-b131-3bee6a30ff82
