### ISSUE TITLE
Regression: 1.71.123->1.73.89, text selection is not highlighted on Twitter/X.

### ISSUE THREAD

**Issue by serjepatoff** [brave/brave-browser#42369]
### Description

Selection of edited text on Twitter/X, either in a post edit box or a comment edit box, is not highlighted.

### Steps to reproduce

1. Upgraded Brave from 1.71.123 to 1.73.89 on Arch Linux.
2. Opened x.com, started writing a comment.
3. When I tried to select currently edited text by using either mouse click-and-drag, or Shift+Left/Right buttons, or by pressing Ctrl-A, no highlight of selected text was visible. At the same time, selection actually worked: for example, pressing Ctrl-A, Backspace deleted all text.

### Actual result

Selection of edited text on Twitter/X is not highlighted.

### Expected result

Selection of edited text on Twitter/X should be highlighted.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Version 1.73.89 Chromium: 131.0.6778.69 (Official Build)  (64-bit)
OS: Arch Linux
uname -a: Linux 6.6.62-1-lts #1 SMP PREEMPT_DYNAMIC Sun, 17 Nov 2024 16:35:16 +0000 x86_64 GNU/Linux

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

1. This issue occured with Brave Shields both enabled or disabled
2. Rolling back to 1.71.123 fixed this issue.

**Comment by unknownuserisknown** [comment]
Can confirm. I'm running Manjaro (Arch-based distro) and text selection highlighting does not appear in Brave Version 1.73.89 Chromium: 131.0.6778.69 (Official Build) (64-bit)]

**Comment by rebron** [comment]
@serjepatoff @unknownuserisknown Can you update to 1.73.91? We just released and fix should be in this version.

**Comment by ShivanKaul** [comment]
Can confirm that `1.73.91 Chromium: 131.0.6778.85` on Brave Release fixes the issue. For reference, this is the [upstream issue](https://issues.chromium.org/issues/378754060). Chromium fixed it by disabling the runtime flag `HighlightInheritance` in all channels. With the latest Chromium bump we've inherited the [actual code change](https://github.com/chromium/chromium/commit/921435f584725f0d3da0b27e089af2fcc41686a5).

**Comment by unknownuserisknown** [comment]
I can also confirm the fix. thank  you!
