### ISSUE TITLE
Monthly tip notification is not translated

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#4236]
## Steps to Reproduce

   1. Clean install
   2. Run Brave with flag: `--rewards=staging=true,reconcile-interval=5`
   3. Change Brave locale to `Polish`
   4. Relaunch Brave with flag: `--rewards=staging=true,reconcile-interval=5`
   5. Enable Rewards and claim grant
6. Monthly tip `duckduckgo.com`
7. Disable auto-contribute in `brave://rewards`
8. Wait for Monthly tip reconciliation

## Actual result:

Monthly tip notification is not translated
![image](https://user-images.githubusercontent.com/34715963/56746806-33d9de80-677d-11e9-90c8-6d0333479c68.png)

## Expected result:
Monthly tip notification is translated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

cc @brave/legacy_qa @NejcZdovc @ryanml

**Comment by rebron** [comment]
@btlechowski can you recheck with @mkarolin localization pull?

**Comment by mkarolin** [comment]
@btlechowski, @rebron I don't see any new Polish translations in the localization I pulled.

**Comment by bbondy** [comment]
@NejcZdovc 
A @mkarolin says it's still not fixed after the localization update, could you check why?

**Comment by NejcZdovc** [comment]
this strings are quite new, so they are just not translated/added in transifex. Will close it as this will be fixed when we get new update from transifex

**Comment by kjozwiak** [comment]
Moved this back into `0.64.x` as https://github.com/brave/brave-core/pull/2343 has been uplifted. This will need to be verified.

**Comment by NejcZdovc** [comment]
@kjozwiak https://github.com/brave/brave-core/pull/2343 doesn't fix this problem. That PR doesn't have this new strings

**Comment by kjozwiak** [comment]
Moved it out of `0.64.x` but we shouldn't close the issue just because it's not actionable. This still needs to be checked once we add the new strings.

**Comment by NejcZdovc** [comment]
I am moving then this to general project

**Comment by rebron** [comment]
@btlechowski Can you take a look at this one? I think we have updated strings now.

**Comment by btlechowski** [comment]
Not reproducible on

Brave | 0.66.88 Chromium: 75.0.3770.87 (Official Build) beta (64-bit)
-- | --
Revision | 9dc58a2353af60ab2b48bab98a25bc43ed59085d-refs/branch-heads/3770@{#982}
OS | Windows 7 Service Pack 1 (Build 7601.24465)

![image](https://user-images.githubusercontent.com/34715963/59372582-22a65a80-8d48-11e9-8938-9a36bda89b20.png)

Also not reproducible on:

**Comment by kjozwiak** [comment]
Awesome, thanks for the recheck @btlechowski 👍
