### ISSUE TITLE
New Playlist is missing some system player functionality

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#42370]
### Description

A couple of pieces are missing from the new playlist for handling input from the system player (what appears on the lock screen):
- Previous & Next track buttons (`◀︎◀︎` & `▶︎▶︎`)
- Changing the playback position via the system progress bar

### Steps to reproduce

1. Start playing an item in Playlist
2. Bring up system player in one of the many places it will show up: lock screen, control center, dynamic island
3. Attempt to drag the progress bar to scrub the playlist item
4. Attempt to play the next or previous track (via AirPods, see comment below)

### Actual result

The new playlist UI doesn't support interacting with the system player for these things

### Expected result

Should support these options

### Reproduces how often

Easily reproduced

### Brave version

1.71+

### Device/iOS version

N/A

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kylehickinson** [comment]
Not sure when this changed but it seems like if you support both the 15s interval seek buttons and the next/previous track buttons only the skip ones show up. Bluetooth buttons still function correctly though to go to the next track, but I dont know how to make iOS show the next/previous buttons at all while also supporting the 15s jumps

**Comment by kjozwiak** [comment]
The above requires `1.74.13` or higher for `1.74.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.0` using version `1.74 (20)`

* Verified STR mentioned in https://github.com/brave/brave-browser/issues/42370#issue-2672474487
* Ensured that scrubbing progress bar works in lockscreen. 
* Ensured play/pause via Airpods controls works.
* Ensured next/previous track via Airpods controls works. 
* Ensured all other controls in the player UI shown are working on the device and have not regressed.

example | example
---|---
![Image](https://github.com/user-attachments/assets/137789ea-64ae-413c-90f9-47a6fd304b0e) | ![Image](https://github.com/user-attachments/assets/9ddb7055-a28c-400e-954f-46241aba292b)
