### ISSUE TITLE
Update google search url for QSE

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#42384]
In this issue, we need to update google search url for quick search engine. 
Below is the url we get from template URL service for google service, 
`{google:baseURL}search?q={searchTerms}&{google:RLZ}{google:originalQueryForSuggestion}{google:assistedQueryStats}{google:searchFieldtrialParameter}{google:language}{google:prefetchSource}{google:searchClient}{google:sourceId}{google:contextualSearchVersion}ie={inputEncoding}`
we need to update it with : `https://www.google.com/search?q={searchTerms}` for google serach

**Comment by kjozwiak** [comment]
The above requires `1.74.13` or higher for `1.74.x` verification 👍 Labelled as `QA/Yes` as the above should be checked. @Uni-verse went through the above on `Nightly` and added some STR/Cases that can be used for `1.74.x` verification via https://github.com/brave/brave-core/pull/26550#issuecomment-2498670228.

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP41.240925.009 release-keys
Brave build: 1.74.13 
Chromium: 131.0.6778.85 (Official Build) beta (64-bit) 
```

Filed follow-up issue #42565
---------------------------
<details>
<summary> Fresh profile </summary>

**STEPS:**
1. Fresh install Brave Beta `1.74.13` or higher
2. Go through onboarding
3. Open `NTP`
4. Tap in the `URL search bar`
5. Type a query > *Verify that QSE toolbar is shown*
6. Tap `Google search` thumbnail > *Verify that the search results are shown in Google `https://www.google.com/search?q={searchTerms}`*
 
**ACTUAL RESULTS:**
- Verified that `QSE` is not shown until the user starts typing a query in the `URL search bar`.
- Verified that the `Google` search works when tapping the thumbnail.
- Verified that the results are shown with `https://www.google.com/search?q={searchTerms}`.

---------------------------

https://github.com/user-attachments/assets/0037ac62-a426-4102-9347-a82fa271955a
</details>

<details>
<summary> Upgraded profile </summary>

**STEPS:**
1. Install Brave Beta `1.74.10` (it was previously available in the Play Store)
2. Go through onboarding
3. Open `NTP`
4. Tap in the `URL search bar` > Type a query
5. Tap `Google search` thumbnail > *Observe that `Google search` doesn't work*
6. Upgrade Brave to Beta `1.74.13` or higher
7. Type a query again
8. Tap `Google search` thumbnail > *Observe that `Google search` is still not working*

**ACTUAL RESULTS:**
- Verified that `QSE` is not shown until the user starts typing a query in the `URL search bar` after Brave upgraded to a new build.
- Observed that the `Google` search didn't work even after Brave upgraded to the new build.

---------------------------

https://github.com/user-attachments/assets/f736ff90-d5a3-4f48-94fd-96e64c006aea

</details>
