### ISSUE TITLE
AI Chat network error retry button has a JS error

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#42405]
### Description

AI Chat network error retry button has a JS error

### Steps to reproduce

1. Turn off local network (wifi / wired)
2. Submit a prompt to AI Chat
3. Observe network errro in AI Chat UI
4. Re-enable local network
5. Click retry

### Actual result

Nothing happens.

JS error in console:
```
[8888:15116:1104/065538.153:ERROR:CONSOLE(2)] "Uncaught TypeError: Cannot read properties of undefined (reading 'sendMessage')", source: chrome-untrusted://chat/chat_ui.bundle.js (2)
```

### Expected result

Request is retried, error disappears

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.75.18
1.73.91

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.73.95` or higher for `1.73.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.73.95 Chromium: 131.0.6778.85 (Official Build) (64-bit)
-- | --
Revision | 60a630aa8abca98618cdb3ec21d44b25c30759ae
OS | Windows 10 Version 22H2 (Build 19045.5131)
```
