### ISSUE TITLE
New Playlist UI can crash in the background due to excessive CPU usage

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#42408]
### Description

We've had reports of playlist stopping after an extended period of time in the background and its due to iOS ejecting Brave based on CPU usage while backgrounded.

The new playlist UI introduces a few nice decorative features such as the video ambiance shown around the video while playing but unfortunately these continue being used while in the background causing high CPU usages.

### Steps to reproduce

1. Find a long form video (45m+)
2. Start playing it and lock your phone so that it continues playing in the background
3. Wait

### Actual result

Should play the entire video

### Expected result

Can sometimes stop and crash Brave

### Reproduces how often

Intermittent issue

### Brave version

1.71+

### Device/iOS version

N/A

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.74.12` or higher for `1.74.x` verification 👍

**Comment by kjozwiak** [comment]
The above requires `1.73.93` or higher for `1.73.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18` using version `1.73 (93)`

* Ensured that long form videos can be played in the background without pauses or crashes. 
* Ensured that there are no issues with scrubbing long form videos and loading another long form video in the next track. 

`playlist` | `lockscreen` | `minimized/background`
---|---|---
![Image](https://github.com/user-attachments/assets/0167c1f2-512a-4819-ac4c-3ed6ec1ddfc3) | ![Image](https://github.com/user-attachments/assets/9bd58b17-fc72-4707-9e3b-8767f9b3f2e4) | ![Image](https://github.com/user-attachments/assets/36696021-ca0a-499c-98b4-ef70684d2a68)
