### ISSUE TITLE
AI Chat static conversation starters shouldn't show if conversation has chat history

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#42412]
### Description

AI Chat static conversation starters shouldn't show if conversation has chat history. They are only for the beginning of a conversation. However, generated conversation starters (from associated content) can keep showing on conversations with chat history.

### Steps to reproduce

1. Create a conversation
2. Observe conversation starters are shown
3. Submit a chat message, e.g. "Give me 1 emoji only"
4. Observe conversation starters disappear
5. Switch away from the conversation (new or older conversation)
6. Switch back to the conversation

### Actual result

Conversation starters come back

### Expected result

No conversation starters are shown

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.75.32

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed 

Brave | 1.75.166 Chromium: 132.0.6834.111 (Official Build) beta (64-bit)
-- | --
Revision | 0c5da0a4df158be9400ac84df9312b627cc4dec0
OS | Windows 11 Version 24H2 (Build 26100.2894)

- Verified steps from issue description
- Verified switching conversation focus doesn't re-add conversation starters

https://github.com/user-attachments/assets/8dc1ec96-1dff-495c-b92f-577787b48219

------
Verification passed 

Brave | 1.75.166 Chromium: 132.0.6834.111 (Official Build) beta (64-bit)
-- | --
Revision | 0c5da0a4df158be9400ac84df9312b627cc4dec0
OS | Linux

- Verified steps from issue description
- Verified switching conversation focus doesn't re-add conversation starters

https://github.com/user-attachments/assets/1454d2cc-86a5-4d64-8a83-3afa3138e173

-----
Verification passed 

Brave | 1.75.164 Chromium: 132.0.6834.83 (Official Build) beta (arm64)
-- | --
Revision | befbba8d7568f8713d6f942f9a7350c59b57f20a
OS | macOS Version 15.2 (Build 24C101)


- Verified steps from issue description
- Verified switching conversation focus doesn't re-add conversation starters


https://github.com/user-attachments/assets/2623e8d6-b50f-465e-9950-31c426147fe4
