### ISSUE TITLE
AI Chat FullPage shouldn't show in SidePanel mode when restored at startup

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#42413]
### Description

AI Chat FullPage shouldn't show in SidePanel mode when restored at startup

### Steps to reproduce

1. Open several FullPage AI Chat tabs (currently chrome-untrusted://chat)
2. Quit the browser
3. Restart the browser

### Actual result

Several or all of the FullPage AI Chat pages are in SidePanel mode (they don't have a conversation list navigation sidebar)

### Expected result

They all should be restored in FullPage mode

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.75.32

### Channel information

- [ ] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Requires AIChatHistory feature flag
SidePanel still being opened in SidePanel mode and not FullPage mode should be tested too

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.166 Chromium: 132.0.6834.111 (Official Build) beta (64-bit)
-- | --
Revision | 0c5da0a4df158be9400ac84df9312b627cc4dec0
OS | Windows 11 Version 24H2 (Build 26100.2894)

- Verified steps from issue description
- Verified AI Chat full page view is retained between browser restarts
- Encountered [#43467](https://github.com/brave/brave-browser/issues/43467)

https://github.com/user-attachments/assets/46e6ca89-cbc8-47be-b271-d0d2619daae8

-------
Verification passed on

Brave | 1.75.166 Chromium: 132.0.6834.111 (Official Build) beta (64-bit)
-- | --
Revision | 0c5da0a4df158be9400ac84df9312b627cc4dec0
OS | Linux

- Verified steps from issue description
- Verified AI Chat full page view is retained between browser restarts
- Encountered [#43467](https://github.com/brave/brave-browser/issues/43467)

https://github.com/user-attachments/assets/16254dc2-76df-4fcd-9259-1519d55d2b21

-------
Verification passed on

Brave | 1.75.164 Chromium: 132.0.6834.83 (Official Build) beta (arm64)
-- | --
Revision | befbba8d7568f8713d6f942f9a7350c59b57f20a
OS | macOS Version 15.2 (Build 24C101)

- Verified steps from issue description
- Verified AI Chat full page view is retained between browser restarts
- Encountered [#43467](https://github.com/brave/brave-browser/issues/43467)

https://github.com/user-attachments/assets/828c3d99-bc62-44d1-a84f-653ebd5cd6fd
