### ISSUE TITLE
Add ability to search local items saved in Playlist

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#42437]
Some user feedback has come back asking to search videos they've saved in Playlist, we have some ongoing design for this in Figma: https://www.figma.com/design/gafcumKE9O6T4A844I8SvL/iOS-Playlist?node-id=5782-136088 

This would be part 1 which adds just the ability to search for videos you have saved already

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.2` using version `1.75 (102)`

Verified the following acceptance criteria using test plan in https://github.com/brave/brave-core/pull/26933#issue-2727798805

- [x] Verified tapping on the spyglass will open search field
- [x] Verified you can search for items in multiple folders by name
- [x] Verified items shown show the correct download states
- [x] Verified long pressing on items shows the same context menu and that those buttons work correctly
- [x] Verified that tapping on an item starts playing that item the same way as if tapped on the main sidebar/drawer list

example | example | example | example
---|---|---|---
<img width="250" src="https://github.com/user-attachments/assets/741ce7a8-bf87-4943-930b-10e2d8bd2c17"> | <img width="250" src="https://github.com/user-attachments/assets/b6033b8e-755e-433a-887c-30765d82fb20"> | <img width="250" src="https://github.com/user-attachments/assets/38f25e99-915f-4ed4-a04a-c5443f12b7ce"> | <img width="250" src="https://github.com/user-attachments/assets/8ff1b3ed-8e7f-4399-ae7e-164a08778292">
