### ISSUE TITLE
Search ads click and conversions are not triggered for non-rewards users on clean install

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#42431]
### Description

Fixed after browser restart after variation seed is enabled

### Steps to reproduce

1. Clean profile
2. Open `https://search.brave.software/search?q=chainlink`
3. Click the ad

### Actual result

Clicked event is not processed

### Expected result

Clicked event is processed
Example:
```
[20944:20944:1121/175659.429511:VERBOSE3:search_result_ad_handler.cc(188)] Clicked search result ad with placement id e96d6b4d-ec73-4b09-ac41-88f122ea970e and creative instance id bc876b1a-ca48-4eac-b445-efb9617ead4a

```

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.74.4 Chromium: 131.0.6778.39 (Official Build) beta (64-bit)
-- | --
Revision | 15328654b03f358466ab746b5d12a68e7fdb5017
OS | Linux

cc @tmancey @aseren @iambrianfung

**Comment by tmancey** [comment]
Closed as working as expected until we enable certain feature flags by default. Will only occur after a fresh install, and as above fixes itself after the first launch. Thanks.
