### ISSUE TITLE
Solana swaps have very high rate of being dropped

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#42434]
### Description

The priority fee we use for Solana swaps, which is computed by Jupiter API, is not sufficient to land them with a high success rate. Bump it up based on the updated docs: https://station.jup.ag/docs/apis/landing-transactions#an-example-of-how-jupiter-estimates-priority-fees

### Steps to reproduce

Perform a Solana swap and approve it.

### Actual result

Transaction ends up being dropped almost all the time.

### Expected result

Transaction should be successfully confirmed.

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

1.73.x

### Android device

N/A

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.73.92` or higher for `1.73.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.73.92 Chromium: 131.0.6778.85 (Official Build) (64-bit)
-- | --
Revision | 05f178377f490b21d73d0a9bb29c2e45040dd984
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from issue description
- Verified able to perform Solana Swap without transactions being dropped

https://github.com/user-attachments/assets/6b02867c-3676-456d-8e08-c4fca85510b4

**Comment by srirambv** [comment]
Removing Android and iOS label as the change is on core. Confirmed with @onyb  desktop verification is enough

**Comment by kjozwiak** [comment]
> Removing Android and iOS label as the change is on core. Confirmed with [@onyb](https://github.com/onyb) desktop verification is enough

@srirambv I re-added the labels as the above is `release-notes/include` which means it will most likely be missed for `iOS` & `Android` when creating release notes. In these cases, lets just leave the labels but add a comment similar to what you did above re: only needed a single verification rather than checking multiple platforms.
