### ISSUE TITLE
Brave notification ads are disabled after connecting to a custodian

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#42436]
### Description

Follow up to https://github.com/brave/brave-browser/issues/41424

Notification ads are disabled.

### Steps to reproduce

1. Clean install
2. Enable rewards
3. Make sure tokens are downloaded
4. View an ad
5. Connect to a custodian
6. Check notification ads toggle on `brave://rewards`

### Actual result

Notification ads are disabled

![Image](https://github.com/user-attachments/assets/17ca4aac-9fd0-4db0-8dc9-7efdeeaa808c)

### Expected result

Notification ads are enabled

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.74.4 Chromium: 131.0.6778.39 (Official Build) beta (64-bit)
-- | --
Revision | 15328654b03f358466ab746b5d12a68e7fdb5017
OS | Linux

cc @tmancey @aseren @iambrianfung

**Comment by LaurenWags** [comment]
cc @kjozwiak @rebron this needs to be fixed for 1.74.x release

**Comment by kjozwiak** [comment]
The above requires `1.74.16` or higher for `1.74.x` verification 👍

**Comment by btlechowski** [comment]
Verified with

Brave | 1.75.59 Chromium: 131.0.6778.85 (Official Build) nightly (64-bit)
-- | --
Revision | 19d675f1e120ac1fd6bcef50fc43cf72dcb581bc
OS | Linux

Verified test plan from the description

<details>

Before connecting to custodian:

![Image](https://github.com/user-attachments/assets/d433b814-5d93-4f3c-8d1d-cb7aa29958b7)


Verified notification ads are enabled after connecting to a custodian
Verified search ads are disabled after connecting to a custodian

![Image](https://github.com/user-attachments/assets/d2c11071-93d4-40bc-ac87-9e4fbd6d1db1)


Verified retained after restart:

![Image](https://github.com/user-attachments/assets/fcde99a4-f341-4f52-aab2-737d708c8852)

Verified user is able to earn BAT

![Image](https://github.com/user-attachments/assets/1f061275-f340-4158-9f02-a04a24b1f750)

</details>
