### ISSUE TITLE
[Follow up to #26555] Leo provides an answer as a `code block` if a user uses `REWRITE` or `CHANGE TONE` when sending a query

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#42439]
### Description

Follow-up to #26555.

### Steps to reproduce

1. Launch Brave
2. Open `Leo`
3. Type any query, but don't send it yet
4. Tap [/] to open `slash tools`
5. Select anything from the `REWRITE` OR CHANGE TONE` category
6. Send the query > *Observe*

### Actual result

Leo provides an answer as a `code block` if a user uses `REWRITE` or `CHANGE TONE` when sending a query.

----------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/b3b0a231-7774-484c-aab0-74610f924e50) | ![2](https://github.com/user-attachments/assets/a3d77526-1a09-4d60-803d-e3bf395de003) | ![3]() | ![4]() |

### Expected result

`Leo` must not provide an answer as a `code block` when a user uses `REWRITE`/`CHANGE TONE` if the query/answer is not really related to a programming language.

-----------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/5f39ebc9-ba51-4a22-8a98-4b0bf723e802) | ![2](https://github.com/user-attachments/assets/5c633d7f-626d-42a7-8151-f98d6674b822) |

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.75.36 
Chromium: 131.0.6778.85 (Official Build) canary (64-bit) 

### Device

- Brand/Model: ANY
- Android version: ANY

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by mattmcalister** [comment]
closing as expected behavior.
