### ISSUE TITLE
Brave crashes if using `REWRITE` when sending a query if Leo is opened via `NTP`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#42443]
### Description

Brave crashes if using `REWRITE` when sending a query if Leo is opened via `NTP`.

### Steps to reproduce

1. Launch Brave
2. Open `NTP`
3. Launch `Leo`
4. Open `slash tools` by tapping `[/]`
5. Choose any option from `REWRITE`
6. Type a query > Send > *Observe, Brave crashes*

### Actual result

Brave crashes if using `REWRITE` when sending a query if Leo is opened via `NTP`.

--------------------

https://github.com/user-attachments/assets/ee61ab3a-9d42-44b7-adcb-7a8fa892dbc4

### Expected result

Brave must not crash when using the `REWRITE` option to send a query.

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.73 (91)
BraveCore: 1.73.91 (131.0.6778.85)

### Device/iOS version

- iPad Air / iPadOS 17.7
- iPhone 14 / iOS 17.7.1

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.73.95` or higher for `1.73.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18` using version `1.73 (95)`

* Ensured crash does not occur when using any option from `REWRITE` in Leo slash tools `[/]`.
* Ensured crash is not reproducible using various language models.

example | example
---|---
![Image](https://github.com/user-attachments/assets/e0c76518-e2ef-4ec0-9172-1923ef4e72a8) | ![Image](https://github.com/user-attachments/assets/4258cef2-658d-4d41-bbb5-12fa5d4ec1b8)
