### ISSUE TITLE
Re-add ability to scrub anywhere in Playlist fullscreen mode

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#42442]
This is a follow up to https://github.com/brave/brave-browser/issues/42325

The original playlist features allowed users to drag left and right while in fullscreen to scrub the actively playing video but this was omitted in the new playlist UI.

Usability wise this would be a major improvement to scrubbing, along with other changes to improve the area of which you can drag the scrub bar

**Comment by kylehickinson** [comment]
cc @Saoiray

**Comment by kjozwiak** [comment]
The above requires `1.74.15` or higher for `1.74.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.0` using version `1.74 (20)`

* Ensured scrubbing works anywhere on screen in Playlist full screen. 

https://github.com/user-attachments/assets/7070d77d-f3b4-4c9d-b65a-7b31b35b473a
