### ISSUE TITLE
Rewards creator detection not working on reload

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#42454]
### Description

Rewards creator detection scripts are not running on page reload.

### Steps to reproduce

1. Open the browser with a connected Rewards profile.
2. Visit a verified creator on a media platform site (e.g. `youtube.com`)
3. Reload the page.

### Actual result

The verified checkmark does not appear.

### Expected result

The verified checkmark should appear.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.75.0 Chromium: 131.0.6778.85 (Developer Build) (x86_64) 

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.74.14` or higher for `1.74.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.74.14 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | 26205573ecaf07e354266f9aa4e0bdf6e3b8ebf1
OS | Windows 10 Version 22H2 (Build 19045.5131)
```
- Verified the STR from https://github.com/brave/brave-browser/issues/42454#issue-2683085782 and ensured that the verified checkmark is NOT disappeared from the verified creators when the creators page is reloaded
![Image](https://github.com/user-attachments/assets/84395d16-08f2-413f-ac3a-4f63f12e2f4d)
