### ISSUE TITLE
Expanding Leo to full screen switches to new conversation instead of existing conversation

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#42450]
### Description

Expanding Leo to full screen switches to new conversation instead of existing conversation

### Steps to reproduce

1. Enable `AIChatHistory` flag 
2. Visit any site and open Leo
3. Initiate page summary for the page in Leo side panel
4. Once response is generated click on expand view
5. Switches to new conversation in Leo full screen instead of the active conversation

### Actual result

https://github.com/user-attachments/assets/6f710023-693d-44fd-b7c8-f9995471ff21

### Expected result

Should switch focus to the active conversation opened from side panel

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.74.10 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | bdff9e7d7314280ddbce1c3ada3abee4ce4a3b32
OS | Windows 11 Version 23H2 (Build 22631.4460)

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @petemill

**Comment by petemill** [comment]
This was first implemented in https://github.com/brave/brave-browser/issues/42055 which was merged to 1.75
