### ISSUE TITLE
unable to select Google as default SE for NTP search widget when 3 or more SEs are in the list

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#42469]
### Description

Found while testing https://github.com/brave/brave-browser/issues/41789

Unable to select Google as SE for NTP search widget when it's the first of 3 or more search engines.

Works fine on 1.73.91 (current release).

### Steps to reproduce

1. Install 1.74.10
2. Close/relaunch to pull griffin
3. Open NTP
4. Click on Brave logo of search widget
5. Select "Customize List"
6. Select (in order): DDG, Google, Bing
7. De-select Brave
8. Close customize dashboard modal
9. Click on DDG logo on search widget
10. Click on Google from list ---> Google is not selected, remains DDG
11. Try selecting Bing from the list, this works fine
12. Now try selecting Google again --> Google is not selected but it switches to DDG

I considered maybe it was a problem with the first SE in the list, but if I use 3 different SEs (ex. DDG, Bing, Qwant), all 3 are selectable.

### Actual result

https://github.com/user-attachments/assets/7c967b0e-3929-4b44-be63-b601ce074829

### Expected result

Google should be able to be chosen like any other SE in the list. Here's an example with 3 different SEs and all can be chosen without issue:

https://github.com/user-attachments/assets/e289d195-6c4c-4f6d-9bcd-450bce90bd17

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.74.10 Chromium: 131.0.6778.85 (Official Build) beta (x86_64)
-- | --
Revision | bdff9e7d7314280ddbce1c3ada3abee4ce4a3b32
OS | macOS Version 14.7.1 (Build 23H222)

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @IanKrieger @brave/qa-team

**Comment by MadhaviSeelam** [comment]
Reproduced this issue.  Initially when I tested this I may have seen but I couldn't reproduce it because  it appears to be order of selection matters., 

Select `DDG` or any other SE (Qwant)
Select `Google` 
Will encounter above issue


Select `Google` SE first in the Dashboard
then  select any other SE (DDG, Qwant etc.)
Switch between of them
No issues selecting multiple SE

https://github.com/user-attachments/assets/399fa331-fcdc-4d11-9961-d4ffcae2f2fc

**Comment by LaurenWags** [comment]
Requires 1.74.15 or higher for verification 👍🏻

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.74.15 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | d1293587128488865fa61e9fa277dd54aa2270b0
OS | Windows 10 Version 22H2 (Build 19045.5131)
```
- Verified the STR from the description https://github.com/brave/brave-browser/issues/42469#issue-2684586641

<details>
<summary>Case 1 - Google is not selected first for additional SEs (STR from issue) - PASSED</summary>

1. Install 1.75.54
2. Close/relaunch to pull griffin
3. Open NTP
4. Click on Brave logo of search widget
5. Select "Customize List"

<img width="647" alt="Screenshot 2024-11-27 at 1 11 51 PM" src="https://github.com/user-attachments/assets/bc0ffb74-a00f-4496-90dc-ab6580533035">

6. Select (in order): DDG, Google, Bing
7. De-select Brave

<img width="806" alt="Screenshot 2024-11-27 at 1 12 09 PM" src="https://github.com/user-attachments/assets/d72927b3-189f-4c03-83ff-efc193209df8">

8. Close customize dashboard modal
9. Click on DDG logo on search widget

<img width="666" alt="Screenshot 2024-11-27 at 1 12 21 PM" src="https://github.com/user-attachments/assets/c5f7ac7b-f629-4bc2-a460-3c85ea0472f0">

10. Click on Google from list ---> confirm Google is selected

<img width="650" alt="Screenshot 2024-11-27 at 1 12 28 PM" src="https://github.com/user-attachments/assets/ed38637a-da31-4f7d-8651-e8e328920d29">

11. Try selecting Bing from the list, this works fine

<img width="711" alt="Screenshot 2024-11-27 at 1 12 37 PM" src="https://github.com/user-attachments/assets/40b8beca-8224-4897-b13a-f8a1990279f3">

12. Now try selecting Google again --> confirm Google is selected

<img width="659" alt="Screenshot 2024-11-27 at 1 12 45 PM" src="https://github.com/user-attachments/assets/56b1738f-1f44-44de-9284-b23e15908760">

13. Start typing a search query ex. "Thanksgiving"

<img width="665" alt="Screenshot 2024-11-27 at 1 12 54 PM" src="https://github.com/user-attachments/assets/14687111-c2be-49ee-8216-6a5e56eca292">

14. Confirm Google search results are returned

<img width="1440" alt="Screenshot 2024-11-27 at 1 13 01 PM" src="https://github.com/user-attachments/assets/9dbc19dc-aae4-49dc-beef-092f93658827">

</details>

<details>
<summary>Case 2 - Google is selected first for additional SEs - PASSED</summary>

1. Install 1.75.54
2. Close/relaunch to pull griffin
3. Open NTP
4. Click on Brave logo of search widget
5. Select "Customize List"

<img width="636" alt="Screenshot 2024-11-27 at 1 22 55 PM" src="https://github.com/user-attachments/assets/ea215589-7139-4be0-b3ba-32295a47cc72">

6. Select (in order): Google, Bing, DDG
7. De-select Brave

<img width="829" alt="Screenshot 2024-11-27 at 1 23 09 PM" src="https://github.com/user-attachments/assets/c510d6a7-b9e6-4d38-925b-64e1ffebad95">

8. Close customize dashboard modal
9. Click on Google logo on search widget

<img width="708" alt="Screenshot 2024-11-27 at 1 23 19 PM" src="https://github.com/user-attachments/assets/50ddd502-0890-46b2-a069-b0bd1102d099">

10. Click on DDG from list ---> confirm DDG is selected

<img width="666" alt="Screenshot 2024-11-27 at 1 23 25 PM" src="https://github.com/user-attachments/assets/6965adaa-845e-4449-aaa3-67b850da43d5">

11. Try selecting Bing from the list, this works fine

<img width="626" alt="Screenshot 2024-11-27 at 1 23 35 PM" src="https://github.com/user-attachments/assets/0fb09046-a4a4-48ca-aded-a316c63df422">

12. Now try selecting Google again --> confirm Google is selected

<img width="635" alt="Screenshot 2024-11-27 at 1 23 48 PM" src="https://github.com/user-attachments/assets/ff87c1e0-218e-4c9a-8384-c34967d0da39">

13. Start typing a search query ex. "Thanksgiving sides"

<img width="675" alt="Screenshot 2024-11-27 at 1 23 57 PM" src="https://github.com/user-attachments/assets/beff0a75-990a-4406-a316-e5c520f3bf7c">

14. Confirm Google search results are returned

<img width="1440" alt="Screenshot 2024-11-27 at 1 24 06 PM" src="https://github.com/user-attachments/assets/58c01529-17f1-4c1a-bae4-16ce98e91953">

</details>
