### ISSUE TITLE
New Playlist audio stops and starts momentarily when locking/unlocking the device

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#42468]
### Description

Some users are reporting an annoyance when locking/unlocking their devices with an item playing where the audio stops/starts momentarily 

### Steps to reproduce

1. Open Playlist and start playing an item
2. Lock the device then subsequently unlock the device

### Actual result

After locking and unlocking the audio stops and resumes quickly

### Expected result

Should transition smoothly between background + foreground without stopping

### Reproduces how often

Easily reproduced

### Brave version

1.71+

### Device/iOS version

N/A

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.73.93` or higher for `1.73.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18` using version `1.73 (93)`

* Ensured audio is not disrupted or pauses when locking/unlocking the device. 

`playlist` | `lockscreen`
---|---
![Image](https://github.com/user-attachments/assets/0167c1f2-512a-4819-ac4c-3ed6ec1ddfc3) | ![Image](https://github.com/user-attachments/assets/9bd58b17-fc72-4707-9e3b-8767f9b3f2e4)
