### ISSUE TITLE
Replace "earnings so far" indicator in Rewards 2.5 UI

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#42475]
- [ ] Rewards panel: replace with `Ads seen this month`
- [ ] Rewards page: remove relevant line item and from page card
- [ ] NTP Rewards card
- [ ] Check for any other appearances

**Comment by LaurenWags** [comment]
Two things:
1. The NTP widget needs to be handled also as this info is also displayed there (didn't see that mentioned in the description)
2. On brave://rewards this info is displayed in two places: one is in the "Manage Brave Ads" section (mentioned in the description) as well as on the left where the custodial wallet info is for connected accounts (not explicitly called out in the description). Not sure if this will be handled by the removal of this info from the panel or not, so wanted to be sure it was called out specifically.

Widget | brave://rewards
--- | ---
![Image](https://github.com/user-attachments/assets/7f838e3d-dd53-450f-a904-ce4a299b37bd) | ![Image](https://github.com/user-attachments/assets/0503502e-1b41-4455-baae-99815d8c2a26)

**Comment by kjozwiak** [comment]
@LaurenWags added the `QA/Test-All-Platforms` label for the above but feel free to remove if you think only checking `Win` is good enough. Should at least spot check `macOS` & `Linux` as well.

**Comment by kjozwiak** [comment]
The above requires `1.73.96` or higher for `1.73.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.73.96 Chromium: 131.0.6778.85 (Official Build) (x86_64)
-- | --
Revision | 6f21d9296a589898eb10fe739a33b830de6c9328
OS | macOS Version 14.7.1 (Build 23H222)
```

**Comment by btlechowski** [comment]
Verified with

Brave | 1.73.96 Chromium: 131.0.6778.85 (Official Build) (64-bit)
-- | --
Revision | 6f21d9296a589898eb10fe739a33b830de6c9328
OS | Linux


Verified test plan from https://github.com/brave/brave-core/pull/26751#issuecomment-2504612069. 

<details>
<summary>Clean profile - PASSED</summary>

1. Installed `1.73.96`. 
2. Launched Brave, close/relaunch to pull griffin
3. Joined rewards (staging env)
4. No "Ads seen this month" UI is shown in unconnected state

Example | Example | Example
--- | --- | ---
![Image](https://github.com/user-attachments/assets/fe27820a-73dc-4112-b72e-48ac7351c33f)|![Image](https://github.com/user-attachments/assets/586d82d8-5e68-491d-912c-2a3b87049be5)|![Image](https://github.com/user-attachments/assets/67056d1a-0bff-45d3-a5b8-896586f1d254)


5. Connected to a custodian 
 
Confirmed:
- "Ads seen this month" is shown on the panel for both "Contribution" and "Summary" views
- "Ads seen this month" is shown on the NTP widget
- "Ads seen this month" is not shown on the wallet section/card of brave://rewards
- "Total ads received this month" is still shown under "Manage Brave Ads" panel of brave://rewards
- estimated earnings UI ("Earnings so far"/"Earnings so far this month") is not displayed on the panel, NTP widget, or brave://rewards (wallet section/card or under "Manage Brave Ads")

 Panel | NTP Widget | brave://rewards
--- | --- | --- 




Confirmed that where the "Ads seen this month" UI is shown, it updates when a new ad is viewed:




Confirmed that when the month changes (updated system date to Jan 1), "Ads seen this month" resets as expected:

Panel | Panel | NTP Widget | brave://rewards
--- | --- | --- | ---


</details>

<details>
<summary>Upgrade profile (Uphold) - PASSED</summary>

Set up a profile using `1.73.91` 

![Image](https://github.com/user-attachments/assets/82e37298-9040-4f70-b143-672a5aa32eec)|![Image](https://github.com/user-attachments/assets/795ad22c-0939-4ff4-a238-af313599361e)|![Image](https://github.com/user-attachments/assets/5c122417-8327-4e4f-9080-8b536e6091a6)
--|--|--

After updating, confirmed: 
- "Ads seen this month" is shown on the panel for both "Contribution" and "Summary" views
- "Ads seen this month" is shown on the NTP widget
- "Ads seen this month" is not shown on the wallet section/card of brave://rewards
- "Total ads received this month" is still shown under "Manage Brave Ads" panel of brave://rewards
- estimated earnings UI ("Earnings so far"/"Earnings so far this month") is not displayed on the panel, NTP widget, or brave://rewards (wallet section/card or under "Manage Brave Ads")

Panel | NTP Widget | brave://rewards
--- | --- | --- | ---
![Image](https://github.com/user-attachments/assets/f0214255-3943-437f-90cc-1d8b665579a6)|![Image](https://github.com/user-attachments/assets/02fbc7e8-058e-4982-a817-18b2337c9df0)|![Image](https://github.com/user-attachments/assets/46481729-b593-4b46-9428-98a6e35e5758)


Confirmed that where the "Ads seen this month" UI is shown, it updates when a new ad is viewed:
![Image](https://github.com/user-attachments/assets/d3206c0a-caf8-434b-adc9-48636beba7b7)|![Image](https://github.com/user-attachments/assets/c6e8be33-4303-4543-910a-2ba46ca5988c)|![Image](https://github.com/user-attachments/assets/569daccd-52e5-4c8f-b3ad-40ae7b562996)
--|--|--


</details>

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.73.97 Chromium: 131.0.6778.108 (Official Build) (64-bit)
-- | --
Revision | 7e1cc6e3239d93ac39456640abb6b6f8bc51fd39
OS | Windows 10 Version 22H2 (Build 19045.5131)
```
