### ISSUE TITLE
[Android] Replace "earnings so far" indicator in Rewards 2.5 UI

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#42476]
- [ ] Rewards panel: replace with `Ads seen this month`
- [ ] Rewards page: remove relevant line item (this should be taken care of by changes in https://github.com/brave/brave-browser/issues/42475) 
- [ ] Check for any other appearances

Android version of: https://github.com/brave/brave-browser/issues/42475

**Comment by kjozwiak** [comment]
The above requires `1.73.97` or higher for `1.73.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 15` using the following build(s):

```
Brave | 1.73.97 Chromium: 131.0.6778.108 (Official Build) (64-bit)
--- | ---
Revision | 7e1cc6e3239d93ac39456640abb6b6f8bc51fd39
OS | Android 15; Build/AP41.240925.012; 35; REL
```

#### `Test Case #1` (Clean Install)

* installed `1.73.97 Chromium: 131.0.6778.108`
* enabled rewards and logged into `Uphold` (using `staging`)
* ensured that `Earnings so far` via the rewards panel was replaced with `Ads seen this month`
* ensured that `Earnings so far` has been removed from `brave://rewards`
* ensured that the value under `Total ads received this month` via `brave://rewards` matches the panel value

**`Example`** | **`Example`**
----------------|-----------------
![Image](https://github.com/user-attachments/assets/4029f95f-d995-4395-b54b-b22df6b3475c) | ![Image](https://github.com/user-attachments/assets/7e655d19-03dc-4796-b90e-76d60afdd120)

#### `Test Case #2` (Upgrade)

* Upgraded `1.73.91 Chromium: 131.0.6778.85` --> `1.73.97 Chromium: 131.0.6778.108`
* ensured that `Earnings so far` via the rewards panel was replaced with `Ads seen this month`
* ensured that `Earnings so far` has been removed from `brave://rewards`
* ensured that the value under `Total ads received this month` via `brave://rewards` matches the panel value

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------
![Image](https://github.com/user-attachments/assets/69c1f25c-2c7b-415d-a927-a7105bec0e8b) | ![Image](https://github.com/user-attachments/assets/76dd2529-7427-47b9-bd26-dc641d26c753)
![Image](https://github.com/user-attachments/assets/ace3d96f-d8ad-4b11-9322-88057acd21a9) | ![Image](https://github.com/user-attachments/assets/3da7fb14-30e1-4535-b641-a0079858c4ff)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 15` using the following build(s):

```
Brave | 1.73.97 Chromium: 131.0.6778.108 (Official Build) (64-bit)
--- | ---
Revision | 7e1cc6e3239d93ac39456640abb6b6f8bc51fd39
OS | Android 14; Build/UP1A.231005.007; 34; REL
```

#### `Test Case #1` (Clean Install)

* installed `1.73.97 Chromium: 131.0.6778.108`
* enabled rewards and logged into `Uphold` (using `staging`)
* ensured that `Earnings so far` via the rewards panel was replaced with `Ads seen this month`
* ensured that `Earnings so far` has been removed from `brave://rewards`
* ensured that the value under `Total ads received this month` via `brave://rewards` matches the panel value

**`Example`** | **`Example`**
----------------|-----------------
![Image](https://github.com/user-attachments/assets/c0675d51-a685-48a7-9248-2fd319bb6499) | ![Image](https://github.com/user-attachments/assets/d10cd2e1-d6d7-40cf-af0a-19aec72bf131)

#### `Test Case #2` (Upgrade)

* Upgraded `1.73.91 Chromium: 131.0.6778.85` --> `1.73.97 Chromium: 131.0.6778.108`
* ensured that `Earnings so far` via the rewards panel was replaced with `Ads seen this month`
* ensured that `Earnings so far` has been removed from `brave://rewards`
* ensured that the value under `Total ads received this month` via `brave://rewards` matches the panel value

**`Example`** | **`Example`** 
----------------|----------------
![Image](https://github.com/user-attachments/assets/add0025d-38ac-41a7-abcc-8044302e0968) | ![Image](https://github.com/user-attachments/assets/1517274d-d022-4975-8671-152915edaaf7)
![Image](https://github.com/user-attachments/assets/f0c90a18-b336-4960-a2f4-8e9146ebb6cc) | ![Image](https://github.com/user-attachments/assets/6d03f135-0979-487d-9ca5-4eca952492d5)
