### ISSUE TITLE
Generic cosmetic filter list rules are not applied on some sites

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#42471]
### Description

Generic cosmetic filter list rules are not applied on some sites

### Steps to Reproduce
1. Add custom filter rules:

```
##.cc-bottom.cc-floating.cc-window
##div.cc-revoke
```

2. Visit https://laurentferrier.ch/products/classic-auto-sandstone?variant=44866903605410
3. Observe cookie banner is visible
4. Visit https://www.chefs-edge.com/collections/whetstones/products/shapton-rockstar-whetstone-1000-grit
5. Observe cookie banner is visible
6. Visit https://goldammer.me/collections/all
7. Observe cookie banner is visible

**Comment by kjozwiak** [comment]
The above requires `1.73.94` or higher for `1.73.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18` using version `1.73 (94)`

**custom filter rules:**
```
##.cc-bottom.cc-floating.cc-window
##div.cc-revoke
```

* Ensured that cookie consent banners are blocked when loading the sites mentioned in https://github.com/brave/brave-browser/issues/42471#issue-2685083235

Rules | Laurentferrier | Chefs-edge | Goldammer | Goldammer product
---|---|---|---|---
![Image](https://github.com/user-attachments/assets/73528b1e-c09e-4ba4-ba8f-f557696de8af) | ![Image](https://github.com/user-attachments/assets/02e079f6-59ff-4229-99b2-63c04211c43c) | ![Image](https://github.com/user-attachments/assets/9b57debe-48b8-4926-9df6-8692d24d7b8a) | ![Image](https://github.com/user-attachments/assets/22554887-4c13-4973-adc9-501923986cdd) | ![Image](https://github.com/user-attachments/assets/76b2402a-ae69-46d3-aae3-60e99d70efa2)
