### ISSUE TITLE
Unable to restore wallet  from lock screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#42497]
### Description

Unable to restore wallet  from lock screen

### Steps to reproduce

1. Install an older version and create a new wallet
2. Keep wallet tab active and upgrade to 1.74.x build
3. Double tap on wallet lock message
4. Click on Restore wallet in lock screen
5. Enter seed words 
6. Click on Restore to complete wallet restore
7. Doesn't restore wallet 

### Actual result

Unable to restore wallet  from lock screen

### Expected result

Should be able to restore wallet

### Reproduces how often

Easily reproduced

### Brave version

1.74.10

### Device

- Brand/model: Google Pixel 8
- Android version: 15

### Channel information

- [ ] release (stable)
- [x] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @simoarpe

**Comment by kjozwiak** [comment]
The above requires `1.73.95` or higher for `1.73.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 1.73.96 x64 build
- Verified steps from issue description
- Verified wallet can be restored from lock screen
