### ISSUE TITLE
Brave Rewards notification even though my Android phone is not eligible

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#4249]
I got a notification to enable Brave Rewards after a fresh install of Brave on my Android phone (running an old unsupported version of Cyanogen Mod):

![Screenshot_2019-04-25-16-54-01](https://user-images.githubusercontent.com/167821/56776851-4820da00-6783-11e9-85e8-91b51c56c903.png)

However, when I try to enable it, I get this error message:

![Screenshot_2019-04-25-16-53-35](https://user-images.githubusercontent.com/167821/56776861-53740580-6783-11e9-863a-69646e4e7e62.png)

It would be nice if the notification didn't show up in this case.

**Comment by srirambv** [comment]
closing in favour of https://github.com/brave/browser-android-tabs/issues/1508
