### ISSUE TITLE
First party script being blocked by shields 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#425]
## Description 

First party script being blocked by shields 

## Steps to Reproduce
   1. Visit https://brave.com on a clean profile in release build
   2. Shields shows 1 blocked item
   3. 

## Actual result:

First party script being blocked by shields  

## Expected result:
1st party scripts should not be blocked 

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Release build and packaged build

### Additional Information

cc: @bbondy @lukemulks

**Comment by bbondy** [comment]
First party scripts are considered for filtering rules so this isn't a bug, but we should fix our website.  I messaged in #website.   This matches EasyPrivacy inclusion for browser-laptop for Thursday's release by the way too.
