### ISSUE TITLE
Removing Brave from NTP search widget isn't being respected - follow up to brave-core/pull/26718

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#42505]
### Description

Found while testing https://github.com/brave/brave-core/pull/26718

When Brave Search is deselected for the NTP search widget (while other SEs are selected), Brave Search remains the default SE for the NTP widget. This started in `1.75.48`, worked as expected in `1.75.47`.

### Steps to reproduce

1. Install and launch 1.75.48
2. Close/relaunch to pull griffin
3. Open NTP
4. Click on Brave logo of search widget
5. Select "Customize list"
6. Select (in order): DDG, Google, Bing
7. De-select Brave
---> Note at this point you can see that the Brave logo is still shown on the widget, this should not be the case. The first SE you selected (in this case, DDG), should be the logo in the widget
8. Close customize dashboard modal
9. See Brave logo is still shown in the widget
10. Click on Brave logo, Brave is not in the list
11. Start typing in the search widget
12. Brave Search is used, but it shouldn't be since it wasn't selected to be in the list of SEs

### Actual result

https://github.com/user-attachments/assets/56532e95-d8e6-4a56-a996-84aeb8ddb81d

### Expected result

expected to work like 1.75.47

https://github.com/user-attachments/assets/b20ba538-74c0-47a6-98e1-987f89fc4c1b

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave	1.75.48 Chromium: 131.0.6778.85 (Official Build) nightly (arm64) 
Revision	e8f51821407a7177fc8b94a1f1037f3b4337b567
OS	macOS Version 15.2 (Build 24C5089c)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @fallaciousreasoning @kjozwiak

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.74.15 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | d1293587128488865fa61e9fa277dd54aa2270b0
OS | Windows 10 Version 22H2 (Build 19045.5131)
```
