### ISSUE TITLE
Playlist UI can be unresponsive and hang

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#42501]
### Description

We've received a number of reports stating that opening new playlist causes the app to freeze and sometimes crash. Based on some crash reports/Xcode logs this is typically caused by the UI loading the videos duration but for videos that are not cached this can sometimes make remote calls which can block the main thread.  This can be exacerbated if the user has a slower connection

This hang can sometimes cause playlist to crash if it lasts for too long

### Steps to reproduce

1. Prefix: Turn off auto-offline downloads then add playlist videos
2. Open playlist and begin dragging the drawer continuously
3. Once the video loads tap on another video and repeat

### Actual result

Playlist freezes

### Expected result

Playlist shouldn't freeze, drawer should remain draggable the entire time without hitching 

### Reproduces how often

Intermittent issue

### Brave version

1.71+

### Device/iOS version

N/A

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by kjozwiak** [comment]
The above requires `1.73.94` or higher for `1.73.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18` using version `1.73 (94)`

* Ensured that playlist UI is not unresponsive or hangs when dragging the drawer continuously.
* Verified steps mentioned in https://github.com/brave/brave-browser/issues/42501#issue-2691547411

`example` | `example`
---|---
![Image](https://github.com/user-attachments/assets/867356e6-9ca7-4b8a-970a-32bda8694ee9) | ![Image](https://github.com/user-attachments/assets/88875da0-822c-4440-b23e-19dd6d130554)
