### ISSUE TITLE
[Follow up to #37961] Title `Monthly Subscription` is shown once on Leo's settings screen right after purchasing `Yearly Subscription`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#42507]
### Description

Follow-up to #37961.

### Steps to reproduce

1. Launch Brave
2. Purchase Leo `Yearly subscription` > Wait for the end of activation of the subscription
3. Land on Leo's settings screen > *Observe the title `Monthly Subscription`*

### Actual result

The title `Monthly Subscription` is shown **once** on Leo's settings screen, right after purchasing the `Yearly Subscription` and landing settings page for the first time.

----------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/92ebc73e-faec-46cb-8a04-0f1e378b6510) | ![2](https://github.com/user-attachments/assets/8f374422-a02a-4fd3-8c28-b46386b03a70) |

https://github.com/user-attachments/assets/64986779-56e1-4825-9a8d-ec27d0675dcf

### Expected result

When purchasing the corresponding Leo subscription, the title must say `Yearly Subscription`.

-------------------

|1|
|:-:|
| ![1](https://github.com/user-attachments/assets/2051ec87-b0ee-42a7-a6be-b8e0e1d673e1) |

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.73 (91)
BraveCore: 1.73.91 (131.0.6778.85)

### Device/iOS version

iPhone 14 / iOS 17.7.2

### Affected browser versions

- [ ] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

cc @Brandon-T

**Comment by kjozwiak** [comment]
The above requires `1.74.24` or higher for `1.74.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.2` using version `1.74 (46)`

* Ensured purchasing Leo yearly subscription is successful and correct subscription type is shown on the settings page. 
* Ensured premium models are working after upgrading. 

example | example | example | example | example
---|---|---|---|---
<img width="200" src="https://github.com/user-attachments/assets/9af4de98-44a2-4b0b-aed6-23b444e5b902"> | <img width="200" src="https://github.com/user-attachments/assets/50f63ada-0384-454c-a974-014c5a81c42b"> | <img width="200" src="https://github.com/user-attachments/assets/35adb2ad-1bbc-453f-8458-2a4caca64aff"> | <img width="200" src="https://github.com/user-attachments/assets/e9313c76-f7d9-4b54-a377-3581209004bb"> | <img width="200" src="https://github.com/user-attachments/assets/0569c87e-a1a7-413d-8360-9b6ee327f29a">
