### ISSUE TITLE
[BYOM] 'Add New Model' Fails

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#42502]
### Description

Clicking _Add New Model_ may fail. The issue appears to stem from an attempt to _trim_ a non-string.

### Steps to reproduce

1. Go to Leo Settings
2. Click "Add New Model"

### Actual result

Nothing happens (but an error is shown in the page's console).

### Expected result

The user should be presented with a form to insert model details.

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

Brave	1.75.44 Chromium: 131.0.6778.85 (Official Build) nightly (64-bit) 
Revision	f14243b5f56477f2b635b3babf9d37521a02737e

### Android device

- Brand/model: 
- Android version: 

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.114 Chromium: 132.0.6834.46 (Official Build) nightly (64-bit)
-- | --
Revision | 2c7caf1265beb933db9dbe9db2500da09cb93620
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from issue description
- Verified able to add new model without issues

https://github.com/user-attachments/assets/adac8815-0479-421c-8052-c946d6fe49ab
