### ISSUE TITLE
[Follow up to #37961] Word `Monthly` is shown in the title `Brave Leo Premium Monthly` in App Store

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#42506]
### Description

Follow-up to #37961.

### Steps to reproduce

1. Launch Brave
2. Purchase Leo's `yearly` subscription
3. Open `App Store`
4. Go to Account > Subscriptions > *Observe* 

### Actual result

Word `Monthly` is shown in the title `Brave Leo Premium Monthly` in the App Store.

------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/23b8e6a7-bb55-49d4-a79e-0f5456172cf8) | ![2](https://github.com/user-attachments/assets/3ff586bc-5896-403d-803c-4709aa5079f6) |

### Expected result

The word `Monthly` must be removed from the title `Brave Leo Premium Monthly` in the App Store.

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.73 (91)
BraveCore: 1.73.91 (131.0.6778.85)

### Device/iOS version

iPhone 14 / iOS 17.7.2

### Affected browser versions

- [ ] latest AppStore
- [x] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by AndyAnds265** [comment]
I've located this and implemented a fix. Someone with 'Submit' access needs to send it to Apple though.

**Comment by AndyAnds265** [comment]
![Image](https://github.com/user-attachments/assets/4c5c967b-102c-43c8-8005-467356cd4f61)
![Image](https://github.com/user-attachments/assets/1b042564-78cc-47b1-8f56-345e65ab472b)
![Image](https://github.com/user-attachments/assets/0e82e1e8-2aa2-4851-a1a1-83a1de561e58)

**Comment by AndyAnds265** [comment]
@Brandon-T helped with this! it is 'Waiting for Review' and will be settled once Apple approves, thanks!!

[Image](https://github.com/user-attachments/assets/8e9c7a55-d813-4f50-add3-00a252a2ff89)
