### ISSUE TITLE
Navigating to chrome://rewards after unsuccessfully enabling Rewards leads to an unhelpful page

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#4250]
I tried to enable Rewards on my old Cyanogen Mod phone and got told it's not possible:

![Screenshot_2019-04-25-16-53-35](https://user-images.githubusercontent.com/167821/56776923-acdc3480-6783-11e9-86e2-784a060bee63.png)

Then I clicked on the notification:

![Screenshot_2019-04-25-16-54-01](https://user-images.githubusercontent.com/167821/56776937-b8c7f680-6783-11e9-8992-85c0053dcf37.png)

and ended up on an unhelpful page:

![Screenshot_2019-04-25-17-00-12](https://user-images.githubusercontent.com/167821/56776949-c5e4e580-6783-11e9-9b4b-5dc201fcf1c7.png)

If we don't fix #4249, then maybe we should at least have a proper error page listening on `chrome://rewards`.

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/browser-android-tabs/issues/1507
