### ISSUE TITLE
Update Brave VPN panel title

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#42503]
### Description

Current title for the VPN widget is `Firewall + VPN`. 
The title should say `Brave VPN` for the initial promo panel and the main panel.
The tooltip should also just be titled `Brave VPN`. 

### Steps to reproduce

1. Have a Brave VPN account already established.
2. Select VPN button the toolbar.
3. Notice text/title of the VPN dialog. Should match expected result.

### Actual result

![Image](https://github.com/user-attachments/assets/d9b4b4cf-51b0-41fd-9d72-5b2bd40da9de)

### Expected result
Initial/promo panel
![Image](https://github.com/user-attachments/assets/29533dbe-888b-4715-9d0c-9c079363f072)

Main panel
![Image](https://github.com/user-attachments/assets/a78b4a45-6ec3-4345-8b83-48674ffe7aca)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.75.x

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by simonhong** [comment]
@rebron Maybe we also want to update button's tooltip? Will update this to `Brave VPN: Disconnected`
![Image](https://github.com/user-attachments/assets/8b65e2e4-1ea5-4f0f-b4fa-d738c3abee2f)

**Comment by rebron** [comment]
Yes. We can update the tooltip to just `Brave VPN: Disconnected` and promo panel can be `Brave VPN`.

**Comment by kjozwiak** [comment]
The above requires `1.73.98` or higher for `1.73.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.73.99 Chromium: 131.0.6778.108 (Official Build) (64-bit)
-- | --
Revision | 273b36438521dd91cbab7a047e6d90deabf59d56
OS | Windows 10 Version 22H2 (Build 19045.5131)
```
- Verified the STR from the description 

1. Installed `1.73.99`
2. launched Brave
3. clicked on `VPN` icon on the toolbar
4. confirmed correct VPN product title, `Brave VPN` is shown on initial onboarding screen
5. clicked Start free trial button in the Brave VPN Widget in NTP
6. confirmed https://account.brave.com/?intent=checkout&product=vpn page loaded
7. entered existing email address and clicked Start free trial button
8. logged into subscription page as expected.
9. confirmed correct VPN product title, `Brave VPN` is shown on VPN panels

example | example | example | example | example 
---------|--------| --------|----------|------
![Image](https://github.com/user-attachments/assets/75aed4e0-291f-4f51-9c74-90082eb71201) | ![Image](https://github.com/user-attachments/assets/42949f45-ca06-4971-96ec-964ed5126f8a) | ![Image](https://github.com/user-attachments/assets/508d9f30-bb06-4c4b-b8ab-792dee2204cb) | ![Image](https://github.com/user-attachments/assets/737c69bf-b45a-49bb-8445-1f5e372b8829) | ![Image](https://github.com/user-attachments/assets/99203ee6-fe1d-45c3-b8cd-966eb71ca199)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.73.99 Chromium: 131.0.6778.108 (Official Build) (x86_64)
-- | --
Revision | 273b36438521dd91cbab7a047e6d90deabf59d56
OS | macOS Version 14.7.1 (Build 23H222)
```
