### ISSUE TITLE
Broken Post Confirmation Details for Solana Swap Transaction

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#42516]
### Description

Solana `Swap` transactions are displaying broken transaction details on the `Post Confirmation` panels

### Steps to reproduce

1. Open the `Wallet` and create a Solana `Swap` transactions
2. Confirm the transaction and wait for the `Post Confirmation` panels to appear.
3. The `Post Confirmation` panels are showing `missing` or `broken` localization information

### Actual result

![Image](https://github.com/user-attachments/assets/8fe63b84-4ccd-4683-bf31-c7895beb242e)
![Image](https://github.com/user-attachments/assets/ada1a958-1a81-479e-ae7d-7a18a2c96ce8)

### Expected result

Should show generic information like `Swapping on Solana Mainnet Beta` and `There was an error attempting to swap on Solana Mainnet Beta`

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.73.89 Chromium: 131.0.6778.69 (Official Build) (arm64) 

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.73.99 Chromium: 131.0.6778.108 (Official Build) (64-bit)
-- | --
Revision | 273b36438521dd91cbab7a047e6d90deabf59d56
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from [brave/brave-core#26820](https://github.com/brave/brave-core/pull/26820)
- Verified Solana Swap/Bridge Transaction Intent description is not broken and shows generic message

https://github.com/user-attachments/assets/639322f9-8dfe-4aed-ac43-163015130517
