### ISSUE TITLE
AI Chat conversations should persist when closing and opening panel on the same content

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#42510]
### Description

AI Chat conversations should persist when closing and opening panel on the same content. This should be the case when the conversation history preference is enabled and when it is disabled.

### Steps to reproduce

1. Visit a website with content
2. Open AI Chat (desktop sidebar or android panel0
3. Ask a question about the content, e.g. "provide 1 emoji for this content, no other words"
4. Wait for answer to complete (no input cursor in answer)
5. Close panel
6. Open panel again

### Actual result

New blank conversation is shown

### Expected result

Prior conversation is shown

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

1.73 - 1.75.36

### Android device

n/a

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 BP11.241025.006 release-keys
Brave build: 1.73.100
Chromium: 131.0.6778.108 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/42510#issue-2692546314
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the conversation session is being saved and not cleared when closing/re-opening the Leo panel.

---------------------------

https://github.com/user-attachments/assets/ad69862f-9131-412d-9394-31bedb4bc3e4
