### ISSUE TITLE
A longer explanation for why phones are not eligible for Brave Rewards would be nice

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#4251]
I tried to enable Rewards on my old Cyanogen Mod phone and got this error message:

![Screenshot_2019-04-25-16-53-35](https://user-images.githubusercontent.com/167821/56777011-03497300-6784-11e9-8f52-63a078c8a381.png)

A "learn more" or a longer explanation would be welcome.

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/browser-android-tabs/issues/1506
