### ISSUE TITLE
VPN Panel - Style update for header "Brave VPN"

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#42519]
### Description

I made a small adjustment to the title area in order to start creating a system for all of our panels so they look similar.

Adjustments:
- Changed VPN icon size
- Changed title size
- Changed alignment and padding around the settings button
- Header size itself is now 60px tall
- Adjusted padding between the header and the content below
https://www.figma.com/design/J4LKBMftiWhqromRWfUQLG/VPN-flows?node-id=1581-4248&t=9GVaFTrPxBkfhUfw-1

![Image](https://github.com/user-attachments/assets/0a7ab19d-fa62-4290-9627-92c577d04127)

![Image](https://github.com/user-attachments/assets/3e9f23f5-acb5-4b2e-bafa-7383772e62b3)

**Comment by MadhaviSeelam** [comment]
Verification `In Progress` using
```
Brave | 1.75.157 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | d8524431e89200eff892315294bd590b314f47d2
OS | Windows 11 Version 24H2 (Build 26100.2605)
```


Changed VPN icon size - [x] 
Changed title size - [x ] 
Changed alignment and padding around the settings button
Header size itself is now 60px tall
Adjusted padding between the header and the content below

1.73.x | 1.75.x 

Disconnected | Connecting | Connected | Server selection | settings | can't connect to server
----| ----- |-----| ----- | ---- | ----
![Image](https://github.com/user-attachments/assets/773d43e8-6d2a-4250-be90-6b87991cad00)|![Image](https://github.com/user-attachments/assets/56b5dd36-17e6-4005-8d07-e4ca9515d9bf)
![Image](https://github.com/user-attachments/assets/121fbdf9-0b96-41e0-b98f-7f7fd6c11f18)|![Image](https://github.com/user-attachments/assets/f9c53d7e-e2df-4741-b39a-917dc5b9d3a4)
![Image](https://github.com/user-attachments/assets/a79980b3-672d-45a3-9750-08544eeabf16)|![Image](https://github.com/user-attachments/assets/15c2a9bd-3a27-4412-b39f-d4220232e381)
![Image](https://github.com/user-attachments/assets/b0fe6a31-8f1f-4b27-9146-69047028739d)|![Image](https://github.com/user-attachments/assets/550950e0-515a-4f73-8a9b-2e4609017c95)
![Image](https://github.com/user-attachments/assets/2adb2094-146e-4c55-93e4-2008cab3b489)|![Image](https://github.com/user-attachments/assets/4386a731-7130-4206-bbdb-1e01f27a7531)
![Image](https://github.com/user-attachments/assets/e5d16177-d9a7-43a0-8a61-d6bd9602a95d)|![Image](https://github.com/user-attachments/assets/cbc1934d-2797-42db-a8ad-3a34cf9d61fa)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.75.171 Chromium: 132.0.6834.160 (Official Build) (arm64)
-- | --
Revision | d4d146998a285171ea57c3b75c52c7819901571a
OS | macOS Version 15.2 (Build 24C101)
```


1. Installed 1.75.171
2. launched Brave
3. logged in to Brave VPN as an existing user (brave10vpn@mailinator.com)
4. confirmed following: 
      - Changed VPN icon size - **[x]** 
      - Changed title size - **[x ]** 
      - Changed alignment and padding around the settings button **[x ]**
      - Header size itself is now 60px tall **[x ]**
      - Adjusted padding between the header and the content below **[x ]**


|1.73.x - Disconnected | 1.73.x - Connecting | 1.73.x - Connected | 1.73.x - Can't connect to server
| ----| ----- |-----| ----- |
![Image](https://github.com/user-attachments/assets/a120a35e-5224-428f-9559-b1c82974d292)|![Image](https://github.com/user-attachments/assets/2794d19b-699a-46ec-8e90-bafa154cf8ce)|![Image](https://github.com/user-attachments/assets/5dec6354-55fd-48b9-bc53-eab1e01fb311)|![Image](https://github.com/user-attachments/assets/cb86784f-1b3e-4e17-9959-130d082d54d6)

Light theme
|1.75.x - Disconnected |1.75.x - Connecting | 1.75.x - Connected | 1.75.x - Can't connect to server
-------- |  -------- | ---------- |. ----------
![Image](https://github.com/user-attachments/assets/fd115ae3-4831-448b-b2bf-a22b7b9e5d48[Image(https://github.com/user-attachments/assets/d18b0eab-c5f6-4a9d-b6bc-cb692f4f6e1a)|![Image](https://github.com/user-attachments/assets/83085942-f454-424d-add5-4ee13563394e)|![Image](https://github.com/user-attachments/assets/dc65a2bf-5e03-48c7-90cc-7965a76955da)

Dark theme
|1.75.x - Disconnected |1.75.x - Connecting | 1.75.x - Connected | 1.75.x - Can't connect to server
-------- |  -------- | ---------- |. ----------
![Image](https://github.com/user-attachments/assets/df4ce75e-3b66-4d7c-b43e-84082c0f47ed)|![Image](https://github.com/user-attachments/assets/eccafd48-6cde-42ef-afeb-f3f3f9560060)|![Image](https://github.com/user-attachments/assets/768b0d8b-7c55-4bc5-9cdb-26f1c4281efd)|![Image](https://github.com/user-attachments/assets/bb5e48f9-db6e-4776-807d-c9927844433d)
