### ISSUE TITLE
Wallet panel does not work when a web page needs to interact with Brave Wallet

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#42527]
## Details

Brave Wallet panel does not show up when a website needs to interact with Brave Wallet.
Tapping on Wallet icon in the address bar does not produce any effect.

Slack discussion link: https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1732028052798269

https://github.com/user-attachments/assets/a6806289-0554-4c32-9479-1dbf744e763f

To reproduce the issue, navigate to https://login.xyz and try to perform a login using Brave Wallet; observe that the Brave Wallet panel does not show up.

**Comment by kjozwiak** [comment]
The above requires `1.73.95` or higher for `1.73.x` verification 👍
