### ISSUE TITLE
Search ads toggle state is incorrect after connecting to a custodian

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#42534]
### Description

Search ads toggle remains on after connecting to a custodian. Page refresh does not put the toggle into the correct state (off). Close/relaunch of the browser will toggle search ads off. This works correctly in 1.73.91 (current release) but does not work in 1.74.x and above.

### Steps to reproduce

Note, also encountered https://github.com/brave/brave-browser/issues/42436 as well

1. Clean profile 1.74.x
2. Close/relaunch so you pull griffin seed
3. Join Rewards
4. Connect to custodian
---> See that Notification ads get disabled (this is logged with https://github.com/brave/brave-browser/issues/42436)
---> See that Search ads are still enabled 
5. Refresh page, no difference
6. Close/relaunch browser
7. Navigate to brave://rewards again
---> Search ads are now off as they should be

### Actual result

step 4:

![Image](https://github.com/user-attachments/assets/6d5039c0-b206-41b4-8de2-6a4a327eae9d)

### Expected result

Should be as it is in 1.73.91:

![Image](https://github.com/user-attachments/assets/d4a898cc-4c10-48ad-8bc3-a20b09b6eae3)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.74.10

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @tmancey @aseren @iambrianfung @rebron @kjozwiak @btlechowski

**Comment by LaurenWags** [comment]
@rebron @kjozwiak this seems like another one that should be fixed for 1.74.x release. Labelled as `release/blocking` and put in the 1.74.x milestone, but please adjust if you feel differently 👍🏻

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue on macOS arm64 - `1.75.39 Chromium: 132.0.6834.15`. In addition to the issues above I have seen two more issues:  

1. When a new tab page is served, the counter `1` is shown next to the `Notification ads` instead of `New tab page ads` 
2. When brave://rewards is refreshed/reloaded, new tab page ads count set to zero, I waited for 5 to 10 mins, the new tab page counter is not shown the ads panel

Issue 1 | Issue 2
-------|-------
![Image](https://github.com/user-attachments/assets/704e9f53-bb54-416a-a5a0-6ce1ee3bd516) | ![Image](https://github.com/user-attachments/assets/f2c64011-ee45-4549-9c3d-a7eda5fd62e1)

**Comment by kjozwiak** [comment]
The above requires `1.74.16` or higher for `1.74.x` verification 👍

**Comment by btlechowski** [comment]
Verified with

Brave | 1.74.17 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | f6e743e1da839a6ae279136288f657bc3fbe5f0e
OS | Linux

Verified test plan from the description

<details>

Before connecting to custodian:

![Image](https://github.com/user-attachments/assets/d433b814-5d93-4f3c-8d1d-cb7aa29958b7)


Verified notification ads are enabled after connecting to a custodian
Verified search ads are disabled after connecting to a custodian

![Image](https://github.com/user-attachments/assets/d2c11071-93d4-40bc-ac87-9e4fbd6d1db1)


Verified retained after restart:

![Image](https://github.com/user-attachments/assets/fcde99a4-f341-4f52-aab2-737d708c8852)

Verified user is able to earn BAT

![Image](https://github.com/user-attachments/assets/1f061275-f340-4158-9f02-a04a24b1f750)

</details>
