### ISSUE TITLE
NTP Sponsored Images are not updated in 15 minutes interval

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#42531]

**Comment by bsclifton** [comment]
@aseren do you have more information about when this regressed?

cc: @simonhong

**Comment by bsclifton** [comment]
OK found the conversation on Slack (employees can see at https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1730922461260349?thread_ts=1730922214.467119&cid=CHGKGMHDJ)

Basically due to bug w/ timer being frozen after putting machine to sleep 👍

**Comment by aseren** [comment]
> [@aseren](https://github.com/aseren) do you have more information about when this regressed?
> 
> cc: [@simonhong](https://github.com/simonhong)

@bsclifton, it was regressed here: https://github.com/brave/brave-core/pull/23453

**Comment by kjozwiak** [comment]
The above requires `1.73.98` or higher for `1.73.x` verification 👍

**Comment by btlechowski** [comment]
Verified with

Brave | 1.73.100 Chromium: 131.0.6778.108 (Official Build) (64-bit)
-- | --
Revision | 8ae5a87a006b15ffd649ca5ff59f333d6833f1fb
OS | Windows 10 Version 22H2 (Build 19045.5247)

#### Test Case 2: Verify Timer Resumes After Short Downtime

<details>

Verified update was executed 5 minutes after woke up from sleep

```

```

</details>


#### Test Case 3: hours of sleep

<details>

Verified update was executed after 9 hours of sleep.

```

```


</details>


#### Test Case 4: Verify Ads Component Update Timer Behavior with Restart

<details>

Verified ads component was checked immediately after browser was launched.

```



```

</details>
