### ISSUE TITLE
P3A Utility Optimizations

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#42541]
Improve STAR recovery rates by allowing reordering of metric attributes, and allowing reporting of alternative, optional attributes. Each metric would have its own configuration. This feature will allow stakeholders to choose the necessary trade-offs for each metric.

Alternative attributes would include:

- `region` and `subregion`: from UN M49 region/subregion list (i.e. region = Americas, subregion = North America)
- `general_platform`: platform identifier without the CPU architecture component

cc @AliShahin

**Comment by GeetaSarvadnya** [comment]
@DJAndries: Can you add test plan is the issue? Thanks!

cc: @LaurenWags

**Comment by DJAndries** [comment]
> [@DJAndries](https://github.com/DJAndries): Can you add test plan is the issue? Thanks!
> 
> cc: [@LaurenWags](https://github.com/LaurenWags)

@GeetaSarvadnya added, thanks

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.75.166 Chromium: 132.0.6834.111 (Official Build) beta (64-bit)
-- | --
Revision | 0c5da0a4df158be9400ac84df9312b627cc4dec0
OS | Windows 10 Version 22H2 (Build 19045.5371)
```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo x70 Pro version 12` running `Bravemonoarm64.apk_1.75.173`


- Verified the test plan from https://github.com/brave/brave-core/pull/26762


<details>
<summary>Step 2_PASSED</summary>

1. Confirmed that requests are being made to `star-randsrv.bsg.brave.com` to prepare Constellation metrics
2. Confirmed that the URL path is `/instances/<cadence type>/randomness`
3. Confirmed that when one request is `sent` for a particular cadence, check to see that metrics are being marked as "sent" as they are being sent to the server, by checking the correct "logs" object in local state.

 **44 typical/slow/express randomness** requests are sent to this endpoint `star-randsrv.bsg.brave.com`

Step 1,2 | Step 1, 2(1) | Step 1, 2(2) | Step 1, 2(2)
----------|-------------|-------------|--------
![Image](https://github.com/user-attachments/assets/085dde8a-2d2a-4f30-bdee-a58869b397c9) | ![Image](https://github.com/user-attachments/assets/c0036bff-3a91-4b16-b714-40585a0e94d2) | ![Image](https://github.com/user-attachments/assets/ac0399f2-4f58-4e84-ac78-407437bf0293) | ![Image](https://github.com/user-attachments/assets/1b81a797-9212-446b-a0d0-f211a5c1550b)



4. There are `36 metrics` listed under `logs_constellation_prep` shown in the images below `Step 4(1)`, `Step 4(2)` and `Step 4(3)`
All the metrics under `Logs` and `logs_constellation_prep` are marked as `sent:true`, when we look at the `https://star-randsrv.bsg.brave.com` endpoint at the server, `36 typical metrics` are sent to the server in the form of `randomness` instances as shown in the images above `Step 1,2(1)` and `Step 1,2(2)` 

36 metrics are shown under `logs_constellation_prep`  

Step 4(1) | Step 4(2) | Step 4(3) 
----------|------------|----------
![Image](https://github.com/user-attachments/assets/c639d8ab-c946-45d8-a32a-ec6624028d02) | ![Image](https://github.com/user-attachments/assets/2d16db81-865e-4791-bdaf-94a705923bbc) | ![Image](https://github.com/user-attachments/assets/cdeab2ac-a37e-465f-88ee-fa81244293f6)


5. Confirmed that no. of metrics shown under `logs_constellation_prep_express` are same as the no. of metrics shown under the `star-randsrv.bsg.brave.com` server endpoint as expected

`logs_constellation_prep_express` | `star-randsrv.bsg.brave.com` 
-------------------------------------|----------------
![Image](https://github.com/user-attachments/assets/b03afca4-ad6a-41a8-ba00-02491bc4aa1b) | ![Image](https://github.com/user-attachments/assets/a1936d0a-9f62-48f5-be7f-faeb5f6eec5e)


6. Confirmed that no. of metrics shown under `logs_constellation_prep_slow` are same as the no. of metrics shown under  the `star-randsrv.bsg.brave.com` server endpoint as expected

`logs_constellation_prep_slow` | `star-randsrv.bsg.brave.com` 
-------------------------------------|----------------
![Image](https://github.com/user-attachments/assets/a9ba4803-5b3b-4f06-9e07-cec81d993277) | ![Image](https://github.com/user-attachments/assets/99320e75-a031-476b-bfd9-253d10b96b51)

</details>

<details>
<summary>Step 3_PASSED</summary>

```
Ensure final measurements are being sent to collector.bsg.brave.com. The URL path should be /<cadence type>. Before metrics are sent to this server, they should appear under constellation_logs, constellation_logs_express and constellation_logs_slow after being prepared (from the requests being made in step 2). As soon as the metrics are sent to the collector, the metric should disappear in the relevant local state object.
```
1. Confirmed that, before the metrics are sent to server they are prepared to sent and hence appear under `logs_constellation_prep_express`, `logs_constellation_prep_slow` and `logs_constellation_prep` after that the metrics are appear under `constellation_logs`, `constellation_logs_express` and `constellation_logs_slow `. 
But the metrics listed under `constellation_logs`, `constellation_logs_express` and `constellation_logs_slow ` are removed once the metrics are sent to the server

**_metrics prepared_**

Example | Example | Example | Example
----------|-----------|---------|----------
![Image](https://github.com/user-attachments/assets/8ae02853-f083-41b3-a0ba-93d4d7739ecd) | ![Image](https://github.com/user-attachments/assets/de5e8dbf-ce30-409e-84d7-c032cd70fbab) | ![Image](https://github.com/user-attachments/assets/41de510d-80b3-4a62-9195-9f299a5b5e69) | ![Image](https://github.com/user-attachments/assets/54e99672-81f0-44cb-8946-9a0e5f598ad3)

  
**_constellation logs_**

![Image](https://github.com/user-attachments/assets/07e80d67-ee37-40cd-91ed-9960ff1ee58d)


2. Confirmed that the final measurements are sent to the endpoint `collector.bsg.brave.com`
     - Five `slow` metrics are sent to the endpoint `collector.bsg.brave.com` as expected
     - Two `express` metrics are sent to the endpoint `collector.bsg.brave.com` and there is one creative instance id under `logs_constellation_prep_express`
     - There is one `creative` cadence type metrics are sent to the endpoint `collector.bsg.brave.com` as expected
     - There are `36 typical` metrics are sent to the endpoint `collector.bsg.brave.com` as there are `36 typical` metrics are listed under `Logs` in brave://local-state file 

Example | Example | Example
---------|------------|-------------
![Image](https://github.com/user-attachments/assets/f5c02c35-999b-4ebf-8c47-d645fb7c1bba) | ![Image](https://github.com/user-attachments/assets/b18c531d-abfa-4df4-8336-44965c734a65) | ![Image](https://github.com/user-attachments/assets/3f7652fb-cda6-4fab-b504-8998e616a950)

</details>

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `iPhone 8 version ` running `Brave Browser 1.75.174`


- Verified the test plan from https://github.com/brave/brave-core/pull/26762


<details>
<summary>Step 2_PASSED</summary>

1. Confirmed that requests are being made to `star-randsrv.bsg.brave.com` to prepare Constellation metrics
2. Confirmed that the URL path is `/instances/<cadence type>/randomness`
3. Confirmed that when one request is `sent` for a particular cadence, check to see that metrics are being marked as "sent" as they are being sent to the server, by checking the correct "logs" object in local state.

 **19 typical/slow/express randomness** requests are sent to this endpoint `star-randsrv.bsg.brave.com`

Step 1,2 | Step 1, 2(1) 
----------|-------------
![Image](https://github.com/user-attachments/assets/2df1cb70-14d9-4859-a80f-3257356dfa20) | ![Image](https://github.com/user-attachments/assets/1cf25411-ff0e-4ec1-b3b7-64e95893ae5e)



4. There are `14 metrics` listed under `logs_constellation_prep` shown in the images below 
All the metrics under `Logs` and `logs_constellation_prep` are marked as `sent:true`, when we look at the `https://star-randsrv.bsg.brave.com` endpoint at the server, `36 typical metrics` are sent to the server in the form of `randomness` instances as shown in the images above `Step 1,2`

14 metrics are shown under `logs_constellation_prep`  

![Image](https://github.com/user-attachments/assets/438e388c-2e2f-4d6a-b705-c95b29599f81)


5. Confirmed that no. of metrics shown under `logs_constellation_prep_express` are same as the no. of metrics shown under the `star-randsrv.bsg.brave.com` server endpoint as expected

`logs_constellation_prep_express` | `star-randsrv.bsg.brave.com` 
-------------------------------------|----------------
![Image](https://github.com/user-attachments/assets/85d7fb30-d977-464c-a881-8fbc57f3acb2) | <img width="997" alt="Image" src="https://github.com/user-attachments/assets/9f8f3539-c9e7-487a-90d0-b99eed0865aa" />


6. Confirmed that no. of metrics shown under `logs_constellation_prep_slow` are same as the no. of metrics shown under  the `star-randsrv.bsg.brave.com` server endpoint as expected

`logs_constellation_prep_slow` | `star-randsrv.bsg.brave.com` 
-------------------------------------|----------------
![Image](https://github.com/user-attachments/assets/61a52021-4ae3-4df5-bd24-8db17f39ed8e) | <img width="994" alt="Image" src="https://github.com/user-attachments/assets/38199285-02ca-45fc-a448-ce5670b9adbc" />

</details>

<details>
<summary>Step 3_PASSED</summary>

```
Ensure final measurements are being sent to collector.bsg.brave.com. The URL path should be /<cadence type>. Before metrics are sent to this server, they should appear under constellation_logs, constellation_logs_express and constellation_logs_slow after being prepared (from the requests being made in step 2). As soon as the metrics are sent to the collector, the metric should disappear in the relevant local state object.
```
1. Confirmed that, before the metrics are sent to server they are prepared to sent and hence appear under `logs_constellation_prep_express`, `logs_constellation_prep_slow` and `logs_constellation_prep` after that the metrics are appear under `constellation_logs`, `constellation_logs_express` and `constellation_logs_slow `. 
But the metrics listed under `constellation_logs`, `constellation_logs_express` and `constellation_logs_slow ` are removed once the metrics are sent to the server

**_metrics prepared_**

Example | Example | Example | Example
----------|-----------|---------|----------
![Image](https://github.com/user-attachments/assets/8ae02853-f083-41b3-a0ba-93d4d7739ecd) | ![Image](https://github.com/user-attachments/assets/de5e8dbf-ce30-409e-84d7-c032cd70fbab) | ![Image](https://github.com/user-attachments/assets/41de510d-80b3-4a62-9195-9f299a5b5e69) | ![Image](https://github.com/user-attachments/assets/54e99672-81f0-44cb-8946-9a0e5f598ad3)

  
**_constellation logs_**

![Image](https://github.com/user-attachments/assets/07e80d67-ee37-40cd-91ed-9960ff1ee58d)


2. Confirmed that the final measurements are sent to the endpoint `collector.bsg.brave.com`
     - Five `slow` metrics are sent to the endpoint `collector.bsg.brave.com` as expected
     - Two `express` metrics are sent to the endpoint `collector.bsg.brave.com` and there is one creative instance id under `logs_constellation_prep_express`
     - There is one `creative` cadence type metrics are sent to the endpoint `collector.bsg.brave.com` as expected
     - There are `36 typical` metrics are sent to the endpoint `collector.bsg.brave.com` as there are `36 typical` metrics are listed under `Logs` in brave://local-state file 

Example | Example | Example
---------|------------|-------------
![Image](https://github.com/user-attachments/assets/f5c02c35-999b-4ebf-8c47-d645fb7c1bba) | ![Image](https://github.com/user-attachments/assets/b18c531d-abfa-4df4-8336-44965c734a65) | ![Image](https://github.com/user-attachments/assets/3f7652fb-cda6-4fab-b504-8998e616a950)

</details>
