### ISSUE TITLE
Don't show connect button over region entry when it's current connected region

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#42544]
### Description

In the select region page in vpn panel, connect button is shown when hovered over the each region(city).
but that button doesn't need to be shown when that region entry is currently connected entry.

### Steps to reproduce

1. Connect to Italy/Milan
2. Go to select region
3. Hover over Italy/Milan

### Actual result

Connect button is shown

### Expected result

Connect button is not shown as it's current connected region

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.75.52 Chromium: 131.0.6778.85 (Official Build) nightly (64-bit) 

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @brave/qa-team @aguscruiz

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.75.115 Chromium: 132.0.6834.57 (Official Build) nightly (x86_64)
-- | --
Revision | 190df443fcce0f6b7941b8585b756b171f690448
OS | macOS Version 14.7.2 (Build 23H311)
```

Using STR from https://github.com/brave/brave-browser/issues/42544#issue-2696891009 and `1.73.104 Chromium: 131.0.6778.204` reproduced the issue:

Example | Example
--- | ---
<img width="1196" alt="Image" src="https://github.com/user-attachments/assets/5316acd1-78ce-4a7e-b4c4-c89de251ea18" /> | <img width="1205" alt="Image" src="https://github.com/user-attachments/assets/178ce9cc-ac87-4f44-b819-660457a2521d" />

Using `1.75.115 Chromium: 132.0.6834.57` and same STR, confirmed that the "Connect" button does not display over a region when it is the currently connected region. Confirmed that the "Connect" button does display for other regions/cities.

Example | Example | Example
--- | --- | ---
<img width="1405" alt="Image" src="https://github.com/user-attachments/assets/e8cb1a06-6d7a-42c1-a10c-053c191068a5" /> | <img width="1415" alt="Image" src="https://github.com/user-attachments/assets/dae92ccc-055e-4e5b-b920-6fd021ab9ab4" /> | <img width="1415" alt="Image" src="https://github.com/user-attachments/assets/1d44efb5-9ea5-4eb8-93d7-7ae36c918838" />

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.75.158 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | 6ed90fc0125a2d115619dc3b7151df971545b75e
OS | Windows 11 Version 24H2 (Build 26100.2605)
```

Reproduced the issue in 1.74.46 using the STR from https://github.com/brave/brave-browser/issues/42544#issue-2696891009

1.74.x | 1.75
----- | ------
Italy | Milan | Mexico | Mexico city 
----- | ----- | ----- | ------
![Image](https://github.com/user-attachments/assets/8ab7e750-3c63-4b99-9847-c59c9e91b7d6)|![Image](https://github.com/user-attachments/assets/1b01dbb9-f6ed-4cef-a8bc-d6ad76a2b09f)
![Image](https://github.com/user-attachments/assets/75dd0fb3-267b-46aa-aca7-bda5047e1bbe)|![Image](https://github.com/user-attachments/assets/6fa37a43-75c8-45e5-9bb6-14f790189b86)
![Image](https://github.com/user-attachments/assets/f7d2edf8-f499-456d-890e-4627401e9cd8)|![Image](https://github.com/user-attachments/assets/43b39338-4e1e-4a78-99b2-5afa4ac34506)|![Image](https://github.com/user-attachments/assets/c374e584-3a83-4fdc-b23c-124aac98018d)

![Image](https://github.com/user-attachments/assets/edcf3686-7e53-404d-b263-1f029025dbac)
