### ISSUE TITLE
[iOS] HTTPS-Only is broken in 1.73

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-browser#42542]
### Description

Brave doesn't let you connect to non-https websites if "Upgrade connections to HTTPS" is set to Standard or Strict mode.

### Steps to reproduce

1. Set "Upgrade connections to HTTPS" to Standard
2. Open http://www.alwayshttp.com/
3. Set "Upgrade connections to HTTPS" to Strict
4. Open http://www.alwayshttp.com/

### Actual result

http://www.alwayshttp.com/ will never load

<img src="https://github.com/user-attachments/assets/1ce1661f-0465-4be2-bae4-0f4ba4a94a5d" width=300/>

### Expected result

In Standard mode http://www.alwayshttp.com/ should load
In Strict mode an interstitial should appear

### Reproduces how often

Easily reproduced

### Brave version

Beta 1.74
Nightly 1.75
Testflight Release 1.73

### Device/iOS version

iPhone 14 Pro / iOS 18.2

### Affected browser versions

- [ ] latest AppStore
- [x] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

App Store Release works correctly, also works correctly with "Upgrade connections to HTTPS" disabled

**Comment by kjozwiak** [comment]
The above requires `1.73.95` or higher for `1.73.x` verification 👍 As per https://github.com/brave/brave-core/pull/26781#pullrequestreview-2468851164, loading `alwayshttp.com` takes a while which is expected. Also double checked with @stoletheminerals & @kylehickinson via Slack. Can use the STR/Cases from https://github.com/brave/brave-core/pull/26781#issuecomment-2508168368 as a template for `1.73.x` verification.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18` using version `1.73 (95)`

Using Test Plan in https://github.com/brave/brave-core/pull/26781#issue-2699101118:

**`Upgrade Connections to HTTPS` set to `Standard`**

* Verified `http://www.alwayshttp.com` will load in standard HTTPS mode. 
* Verified typing `scrisc.com` in the address bar will load secure page (HTTPS).

example | example | example
---|---|---
![Image](https://github.com/user-attachments/assets/ce4f0be6-abc9-4a72-9bce-7d671eb80aa4) | ![Image](https://github.com/user-attachments/assets/cd7c2dd1-fd83-4689-9828-e3dd308a208a) | ![Image](https://github.com/user-attachments/assets/f01c9d12-89f3-4551-9800-0157ae89ca53)


**`Upgrade Connections to HTTPS` set to `Strict`**

* Verified interstitial page is displayed when loading `http://www.alwayshttp.com` using HTTP strict mode. 
* Verified insecure webpage will load after tapping on `Proceed` in the interstitial page. 
* Verified typing `scrisc.com` in the address bar will load secure page (HTTPS). 

example | example | example | example | example
---|---|---|---|---
![Image](https://github.com/user-attachments/assets/e600e00c-093f-4fee-8d8e-2a03266315a5) | ![Image](https://github.com/user-attachments/assets/87aa94a7-4d30-48b2-8437-72a505c03093) | ![Image](https://github.com/user-attachments/assets/f221ca8c-e893-405d-a2b3-73ad05c65bf9) | ![Image](https://github.com/user-attachments/assets/b4a8c9c9-8f13-45d9-b67b-2995f98c91d5) | ![Image](https://github.com/user-attachments/assets/fbe8950a-a6b8-49aa-a2f5-4216e96a207c)

**Comment by Uni-verse** [comment]
Verified on `iPad (9th Gen)` running `iOS 17.7.1` using version `1.73 (95)`

Using Test Plan in https://github.com/brave/brave-core/pull/26781#issue-2699101118:

**`Upgrade Connections to HTTPS` set to `Standard`**

* Verified `http://www.alwayshttp.com` will load in standard HTTPS mode. 
* Verified typing `scrisc.com` in the address bar will load secure page (HTTPS).

example | example
---|---
![Image](https://github.com/user-attachments/assets/93932132-7b1a-406c-a29f-9157afc73ba4) | ![Image](https://github.com/user-attachments/assets/9b934400-2734-41de-a78c-a0e9aa33688b)


**`Upgrade Connections to HTTPS` set to `Strict`**

* Verified interstitial page is displayed when loading `http://www.alwayshttp.com` using HTTP strict mode. 
* Verified insecure webpage will load after tapping on `Proceed` in the interstitial page. 
* Verified typing `scrisc.com` in the address bar will load secure page (HTTPS). 

example | example | example
---|---|---
![Image](https://github.com/user-attachments/assets/0fb44161-c8f0-4688-9646-46e953a95af1) | ![Image](https://github.com/user-attachments/assets/ee6487f1-1052-4657-b8dd-1e2285a6052c) | ![Image](https://github.com/user-attachments/assets/ce135d44-469e-47e4-ab18-7c7f1df8b80a)
