### ISSUE TITLE
Bottom of VPN icon of vpn card is clipped

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#42543]
### Description

![Image](https://github.com/user-attachments/assets/05fa534d-6ce5-440c-9e37-ac3b921b5b47)

### Steps to reproduce

1. Set purchased state
2. Check the bottom of vpn icon of vpn card
3. 

### Actual result

See the screenshot in the above description

### Expected result

![Image](https://github.com/user-attachments/assets/382d1a2f-883a-46de-a95d-98b4ee30c219)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.75.52 Chromium: 131.0.6778.85 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.73.98` or higher for `1.73.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.73.99 Chromium: 131.0.6778.108 (Official Build) (64-bit)
-- | --
Revision | 273b36438521dd91cbab7a047e6d90deabf59d56
OS | Windows 10 Version 22H2 (Build 19045.5131)
```
- Verified the STR from the description
- Confirmed that the bottom of the VPN icon of VPN card is NOT clipped

Example | Example 
----------|---------
![Image](https://github.com/user-attachments/assets/8a6f3cc6-07c7-4312-b719-a4e3d8ed0c4b) | ![Image](https://github.com/user-attachments/assets/2f1a3390-1e48-4f90-8da3-7b8390655ad5)

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.73.99 Chromium: 131.0.6778.108 (Official Build) (x86_64)
-- | --
Revision | 273b36438521dd91cbab7a047e6d90deabf59d56
OS | macOS Version 14.7.1 (Build 23H222)
```

- Verified the STR from the description
- Confirmed that the bottom of the VPN icon of VPN card is NOT clipped

Example | Example
--- | ---
![Image](https://github.com/user-attachments/assets/22d6a80f-0595-4cf8-9240-bf0c5600c191) | ![Image](https://github.com/user-attachments/assets/09ba673d-1b46-4a52-b819-a3df344b58d5)
