### ISSUE TITLE
[Follow up to #42384] `Google search` in QSE toolbar doesn't work for the upgraded profile

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#42565]
### Description

Follow-up to #42384.

### Steps to reproduce

1. Install Brave Beta `1.74.10` (it was previously available in the Play Store)
2. Go through onboarding
3. Open `NTP`
4. Tap in the `URL search bar` > Type a query
5. Tap `Google search` thumbnail > *Observe that `Google search` doesn't work*
6. Upgrade Brave to Beta `1.74.13`
7. Type a query again
8. Tap `Google search` thumbnail > *Observe that `Google search` is still not working*

### Actual result

`Google search` in QSE toolbar doesn't work for the upgraded profile.

-------------------------

https://github.com/user-attachments/assets/292a8339-ed3f-40e4-b64f-25151350f80a

### Expected result

`Google search` in QSE toolbar must work for the upgraded profile.

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.74.13 
Chromium: 131.0.6778.85 (Official Build) beta (64-bit) 

### Device

- Brand/Model: ANY
- Android version: ANY

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.74.23` or higher for `1.74.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 BP11.241025.006 release-keys
Brave build: 1.74.23 
Chromium: 132.0.6834.33 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/42565#issue-2699655769
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Google search` in the QSE toolbar works for the `upgraded` profile.
- Verified that `Google search` in the QSE toolbar works for the `new` profile.

---------------------------

https://github.com/user-attachments/assets/794159ce-1df4-41f1-89a5-e62de1b81d00
