### ISSUE TITLE
AI Chat conversation list should prompt to enable history storage if it's disabled

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#42576]
1. Disable Leo storage preference in Brave Settings
2. Open Leo full-page
-> The conversation list should show a notice that storage is disabled and offer a button to enable it

3. Open Leo sidebar
4. Open "conversation history" in the feature menu
-> The conversation list should show a notice that storage is disabled and offer a button to enable it

Clicking "enable" should enable storage in Brave Settings and the message should disappear from everywhere.

![Image](https://github.com/user-attachments/assets/4030628f-9615-43d9-8fe6-738ca98f09fc)

![Image](https://github.com/user-attachments/assets/1e4ccc50-f64a-492d-80aa-9ec10a42f927)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.166 Chromium: 132.0.6834.111 (Official Build) beta (64-bit)
-- | --
Revision | 0c5da0a4df158be9400ac84df9312b627cc4dec0
OS | Windows 11 Version 24H2 (Build 26100.2894)

- Verified steps from issue description
- Verified with `Store my conversation history` setting disabled, Conversation history disabled message is shown on Leo full page view
- Verified with `Store my conversation history` setting disabled, Conversation history disabled message is shown on Leo sidebar view
- Verified clicking one `Enable` from full page view or Sidebar view, setting is automatically enabled

https://github.com/user-attachments/assets/2a8aef87-8b64-4d47-8dd8-389c28f005de

-------
Verification passed on

Brave | 1.75.166 Chromium: 132.0.6834.111 (Official Build) beta (64-bit)
-- | --
Revision | 0c5da0a4df158be9400ac84df9312b627cc4dec0

- Verified steps from issue description
- Verified with `Store my conversation history` setting disabled, Conversation history disabled message is shown on Leo full page view
- Verified with `Store my conversation history` setting disabled, Conversation history disabled message is shown on Leo sidebar view
- Verified clicking one `Enable` from full page view or Sidebar view, setting is automatically enabled

https://github.com/user-attachments/assets/826880a4-07c1-487d-ae83-7aed7db0f2dd

-------
Verification passed on

Brave | 1.75.164 Chromium: 132.0.6834.83 (Official Build) beta (arm64)
-- | --
Revision | befbba8d7568f8713d6f942f9a7350c59b57f20a
OS | macOS Version 15.2 (Build 24C101)

- Verified steps from issue description
- Verified with `Store my conversation history` setting disabled, Conversation history disabled message is shown on Leo full page view
- Verified with `Store my conversation history` setting disabled, Conversation history disabled message is shown on Leo sidebar view
- Verified clicking one `Enable` from full page view or Sidebar view, setting is automatically enabled

https://github.com/user-attachments/assets/a16ab0dd-4e96-4460-9dbf-daf539e325b3
