### ISSUE TITLE
Use OpenSSL ed25519 cryptography instead of rust provided one.

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#42579]
### Description

- Drop dependency on ed25519-dalek-bip32 crate
- Use ED25519_* functions from OpenSSL

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.156 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | 036ac4040dc50d4bd49b3438e20ab90686218543
OS | Windows 11 Version 23H2 (Build 22631.4602)

- Verified steps from issue description
- Verified Solana [Send ](https://explorer.solana.com/tx/5mXXGLhgXYy4MDExtU7iDCcM76ovh9fPSRouc4u5KTZYwa8HXxedr3WoKVAxVHwn5r6ZaFBpkBr8CGB5mqPoZmdG?cluster=devnet)works as expected
- Verified Solana [Swap ](https://explorer.solana.com//tx/2RqDT2UJfpt5RCGn8JsD4xSxyE3QPkLaCPgBv9HARuugTr3n2ESD8fmYHTaxdFx5w4Agq6jgQJvCW1YX2NWiRgiN)works as expected
- Solana Bridge works as fails, logged (https://github.com/brave/brave-browser/issues/43255](https://github.com/brave/brave-browser/issues/43255)
