### ISSUE TITLE
Another two inactive new tabs are created in new window after detaching a new tab from window

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#42588]
### Description

@Ilie-Lesan reported from https://github.com/brave/brave-browser/issues/41272#issuecomment-2452981864

When detaching a new tab, new window is created but that new window has another two inactive new tabs.

@llie-Lesan 's recording:

https://github.com/user-attachments/assets/b9694bae-fd76-42b8-bdc6-c560178f8ba3

### Steps to reproduce

1. Create one window
2. Turn off `Close window when closing last tab` from brave://settings/system
3. There is one new tab in the window
4. Close that new tab and new tab is created
5. Create another new tab and detach it and make another window with it

### Actual result

New window has three new tabs

### Expected result

New window should have only one new tab with detached tab from original window

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.75.59 Chromium: 131.0.6778.85 (Official Build) nightly (arm64) 

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @brave/qa-team

**Comment by simonhong** [comment]
This doesn't happen when we select `Open the New Tab page` of `On startup` option from brave://settings/getStarted.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.75.133 Chromium: 132.0.6834.57 (Official Build) nightly (64-bit)
-- | --
Revision | ce1787778a7a5d92e63a29f8be965494ef49cbbd
OS | Windows 11 Version 24H2 (Build 26100.2605)
```
