### ISSUE TITLE
[ads] Optimize database queries serialization/deserialization overhead

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#42598]
The goal is to get rid of database queries serialization/deserialization overhead which is run on UI thread.

**Comment by btlechowski** [comment]
Verified with

Brave | 1.75.147 Chromium: 132.0.6834.57 (Official Build) nightly (64-bit)
-- | --
Revision | 6ca80c5d3414773bba6275ff7109f0cb01233795
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/26866

#### search ad

<details>



</details>


#### NTT ad

<details>



</details>

#### Brave News Inline ad

<details>



</details>


#### Notification ad

<details>



</details>

**Comment by btlechowski** [comment]
Verification passed on Brave v1.75.164 on Lenovo TB-8506FS (Android 11.0)

Verified test plan from https://github.com/brave/brave-core/pull/26866

#### search ad

<details>

served
```

```

view

```

```

click
```
```

</details>


#### NTT ad

<details>

served
```

```

view

```

```

click
```

```

</details>

#### Brave News Inline ad

<details>

served
```

```

view

```

```

click
```

```

</details>


#### Notification ad

<details>

served
```

```

view

```

```

click
```

```

</details>

**Comment by btlechowski** [comment]
Verification passed on 1.75.169 on iPhone 13 Pro Max (iOS 18.3)


Verified test plan from https://github.com/brave/brave-core/pull/26866

#### search ad

<details>

served
```

```

view

```

```

click
```
```

</details>


#### NTT ad

<details>

served
```

```

view

```

```

click
```

```

</details>

#### Brave News Inline ad

<details>

served
```

```

view

```

```

click
```

```

</details>


#### Notification ad

<details>

served
```

```

view

```


```

click
```

```

</details>
