### ISSUE TITLE
Shields count doesn't stop counting

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#426]
## Description 

Shields count doesn't stop counting

## Steps to Reproduce
   1. Visit any site which has lot of ads/trackers
   2. Keep the page active for a while
   3. Blocked count keeps increasing 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/41885730-3e9207b2-78c7-11e8-9524-b8849d09765d.png)

## Expected result:
Should only show the blocked items and not increase the count on page

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Release and packaged version

**Comment by srirambv** [comment]
Looks somewhat fixed on master(3924de4e2feab94fc10d1eb11eca8896ecc7bb24). Visiting http://www.espn.com/espn/feature/story/_/id/24340372/cristiano-ronaldo-probably-most-gifted-athlete-history-world-why-hard-complicated-writes-brian-phillips and clicking on video the shields count keeps increasing but not at the rate of reaching 4 digits like originally reported.

**Comment by bbondy** [comment]
Moved to backlog since it is less severe now.

**Comment by srirambv** [comment]
Closing in favour of #1311 which covers in depth
