### ISSUE TITLE
Warning user when disabling MV2 uBlock Origin

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#42608]
### Description

If a user unselects uBO in `brave://settings/extensions/v2` All filters and custom settings are removed.

Prompt the user with a warning will clear uBO data and settings.

### Steps to reproduce

1. Unselect mv2 uBO (and probably other extensions will clear settings)
2. 
3. 

### Actual result

Currently deletes all settings automatically.

### Expected result

Warn user that unselecting will clear extension data

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Current Brave ver

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

ref: https://old.reddit.com/r/uBlockOrigin/comments/1h41myj/end_of_support_for_ubo_on_chrome_chromium/lzv1cmt/?context=3

```
Why is there no warning that disabling an extension there will REMOVE IT (wiping your config) instead of just disabling it so you can restore it later?

You should either add a warning or offer the user a choice to remove or disable it temporarily. A lot of people doesn't backup their extension settings regularly so having an option like that with no warnings seems like a terrible idea to me.
```

**Comment by ShivanKaul** [comment]
Instead of showing a warning, we can simply split the current "toggled off" state to be different between "disabled" and "uninstalled". When the user toggles the button on an extension in brave://settings/extensions/v2, we should "disable" first, and then show a button called `Remove` next to the toggle. Then we don't need a warning.

**Comment by u-RraaLL** [comment]
Yup, that's very close to what I meant with:

> or offer the user a choice to remove or disable it temporarily

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 

```
Brave | 1.75.157 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | d8524431e89200eff892315294bd590b314f47d2
OS | Windows 11 Version 24H2 (Build 26100.2605)
```


1. Installed 1.75.157
2. launched Brave
3. closed and relaunched Brave to pull in griffin
4. opened `brave://settings/extensions/v2`
5. Toggled `Enable uBlock Origin` extension
6. clicked `Add extension`
7. verified the extension is added via `brave://extensions`
8. toggled `off` the extension,
9. confirmed `Remove` button is shown
10. confirmed extension icon is no longer shown 
11. opened brave://extension
12. confirmed the extension is disabled
13. clicked `Remove`
14. confirmed Remove button disappeared
15. confirmed the extension is uninstalled via brave://extension)


step 4 | step 5 | step 6 | step 7 | step 8 | step 9 | step 11 | step 14 | step 15
----- | ------ | ------ | ------ | ------ | ------ | ------ | ----- | ---
![Image](https://github.com/user-attachments/assets/971ea154-884d-4001-bff7-05b49307647c)|![Image](https://github.com/user-attachments/assets/e7a63522-0064-4df7-814d-d6dfddb999d1)|![Image](https://github.com/user-attachments/assets/d5333b9c-c5d0-4c28-a7b8-3a34d2edcadf)|![Image](https://github.com/user-attachments/assets/9bb2927b-47d2-4291-b841-4e89b21be5f1)|![Image](https://github.com/user-attachments/assets/3d347c42-507c-4e4a-9ff4-50840cf0ec21)|![Image](https://github.com/user-attachments/assets/eb5652dc-8162-4f81-b4da-15905192b6b5)|![Image](https://github.com/user-attachments/assets/e981dfc6-fa9e-4f3d-b836-f62d67eff7a0)|![Image](https://github.com/user-attachments/assets/7cfeb245-8830-47fe-943f-da8e8dad08bf)|![Image](ttps://github.com/user-attachments/assets/4fd490ba-b00e-47af-b0c3-599c9ef0c1ec)
