### ISSUE TITLE
Update l10n for Rewards NTP card.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#42614]
Follow up to https://github.com/brave/brave-core/pull/26751 to add l10n.

**Test plan:** 
Same as for https://github.com/brave/brave-core/pull/26751, but check for different languages.

**Comment by kjozwiak** [comment]
The above requires `1.73.96` or higher for `1.73.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.73.96 Chromium: 131.0.6778.85 (Official Build) (x86_64)
-- | --
Revision | 6f21d9296a589898eb10fe739a33b830de6c9328
OS | macOS Version 14.7.1 (Build 23H222)
```
