### ISSUE TITLE
`Already purchased Brave VPN?` link to be shown for existing user on VPN card widget in the NTP

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#42615]
### Description

Found while testing https://github.com/brave/brave-core/pull/26189
Currently VPN card widget in the NTP doesn't show `Already purchased Brave VPN` link for already subscribed users.  If a user log into different machine other than the VPN purchased machine or app, `Start free trial` button is the only option in the widget to log into VPN (ofcourse toolbar VPN onboarding panel has the `Already purchased Brave VPN` link).  Would be great to provide this link on the card widget as well.

### Steps to reproduce

pre-requisite:  subscribe to Brave VPN on a different machine or in the app
1. Install 1.75.x
2. launch Brave
3. open NTP
4. observe Brave VPN card widget 

### Actual result

 `Already purchased Brave VPN?` link is not available 

![Image](https://github.com/user-attachments/assets/2833cfbb-6ae7-4303-8c09-71fc77daa9c2)

### Expected result

 `Already purchased Brave VPN?` link should be available for existing Brave VPN users

![Image](https://github.com/user-attachments/assets/52f39e85-376d-42b0-95f9-425a98f508ce)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

```
Brave | 1.75.55 Chromium: 131.0.6778.85 (Official Build) nightly (64-bit)
-- | --
Revision | 3cc3ba11608e3bbbf9e053bdd032ec05e2a4db7f
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

@mattmcalister @bsclifton 
cc: @rebron @brave/qa-team

**Comment by kleantzogu** [comment]
Updated the CTA copy and the "Already purchased Brave VPN?" link.

![Image](https://github.com/user-attachments/assets/1f68c81b-86a3-4cf7-a9c8-4710b0ee9384)


Figma Link: https://www.figma.com/design/0JkrJVn9XyDM0yjjZ6XQy5/NTP-exploration?node-id=659-255156&t=PYEpHhcCbwisiKb1-4

**Comment by simonhong** [comment]
working on this.

**Comment by kjozwiak** [comment]
The above requires `1.73.99` or higher for `1.73.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.73.99 Chromium: 131.0.6778.108 (Official Build) (64-bit)
-- | --
Revision | 273b36438521dd91cbab7a047e6d90deabf59d56
OS | Windows 10 Version 22H2 (Build 19045.5131)
```
- Verified the STR from the description and test plan from https://github.com/brave/brave-core/pull/26853
- Confirmed that the VPN card has `Already purchased Brave VPN?` link at the bottom
- Confirmed that click on `Already purchased Brave VPN?` link redirects to `https://account.brave.com/?intent=recover&product=vpn`

Example | Example
----------|---------
![Image](https://github.com/user-attachments/assets/68d7e8a8-d34e-452c-8f20-91912086be27) | ![Image](https://github.com/user-attachments/assets/b8f36db8-c053-4e2c-98c9-e8bfd6a8fc53)
