### ISSUE TITLE
Enable self-reported webcompat issues when Shields is DOWN

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#4262]
## Description
Users may be turning off Shields in response to running into webcompat issues. Help speed up webcompat improvement in Shields by allowing the user to self-report issues when running into them.

## Designs
Add a "Report a broken site" button that allows the user to self-report issues on the Shields DOWN state:

![shields off 1](https://user-images.githubusercontent.com/2388823/57658356-8267e500-7593-11e9-8bea-e85ec175ee1f.png)

Clicking on "Report a broken site" will ask the user for permission to send information to Brave:

![shields off 2](https://user-images.githubusercontent.com/2388823/64198545-4bb52380-ce3d-11e9-81c7-5c44b2014bf9.png)

Clicking on "Submit" will flag that site for the webcompat team and give feedback to the user:

![shields off 3](https://user-images.githubusercontent.com/2388823/64198561-57084f00-ce3d-11e9-98b7-4ab0f94255e0.png)

Shields should remember that the user has previously flagged a site for a webcompat issue. In this case, the Shields DOWN state will not have a "Report a broken site" button and instead persist the thank you message.

![shields off 4](https://user-images.githubusercontent.com/2388823/64198693-9cc51780-ce3d-11e9-8e40-31775cf83763.png)

The list of flagged webcompat sites will reset when a user relaunches a new browser binary (the UP/DOWN state will be retained.)

User flow:
![user flow - selfreport webcompat issue](https://user-images.githubusercontent.com/2388823/64198704-a484bc00-ce3d-11e9-800b-8337f52de322.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.2 x64` using the following build:

Brave | 1.3.91 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.15.2 (Build 19C57)

* ensured that the `Report a broken website` button doesn't appear when shields are enabled
* ensured that the `Report a broken website` button is being displayed when shields are disabled
* ensured that the `Report a broken site` displays the correct website that's being submitted
* ensured that that clicking on `Cancel` closes the `Report a broken site` modal
* ensured that clicking on `Submit` correctly displays the `Thank You!` modal
* ensured that the `Thank You!` modal is automatically dismissed
* ensured that clicking on `Submit` correctly submits the data via the terminal

```[47434:775:0114/225922.814119:INFO:webcompat_report_uploader.cc(91)] Successfully uploaded webcompat report. Thanks!```

#### Examples of the UI under macOS:

![Screen Shot 2020-01-14 at 6 17 49 PM](https://user-images.githubusercontent.com/2602313/72403972-d11cde80-3721-11ea-821e-76f9dc40f89a.png)

![Screen Shot 2020-01-14 at 6 18 33 PM](https://user-images.githubusercontent.com/2602313/72403971-d11cde80-3721-11ea-869f-8dadd47a16b7.png)

![Screen Shot 2020-01-14 at 6 18 50 PM](https://user-images.githubusercontent.com/2602313/72404060-0b867b80-3722-11ea-9d5b-70c375e33fc4.png)

![Screen Shot 2020-01-14 at 6 19 39 PM](https://user-images.githubusercontent.com/2602313/72404061-0d503f00-3722-11ea-8ebe-00f56a1db5d8.png)

![Screen Shot 2020-01-14 at 6 21 01 PM](https://user-images.githubusercontent.com/2602313/72404072-1d681e80-3722-11ea-8e50-1d23d69b53b5.png)

<img width="411" alt="Screen Shot 2020-01-14 at 11 04 31 PM" src="https://user-images.githubusercontent.com/2602313/72404133-4be5f980-3722-11ea-982b-ed02fe790cc4.png">
