### ISSUE TITLE
[Regression] Playlist loses position of video

### ISSUE THREAD

**Issue by Windex** [brave/brave-browser#42620]
### Description

This appears to be a regression of this issue: https://github.com/brave/brave-ios/issues/3650

Playlist not keeping track of position of video playing after exiting

### Steps to reproduce

1. Start a video from the Playlist
2. Answer Phone Call
3. Return to Brave
4. Open Playlists and resume video

### Actual result

Video starts from beginning

### Expected result

Video resumes from position when interrupted at step 2

### Reproduces how often

Easily reproduced

### Brave version

Version 1.71 (125)

### Device/iOS version

iOS Version: 17.7.2
Model Name: iPhone 13 Pro Max

### Affected browser versions

- [x] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

Video in question was over 130 minutes long, in case that is related to the issue.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.2` using version `1.75 (102)`

* Ensured that video playback position is resumed after receiving phone call.

example | example | example
---|---|---
<img width="250" src="https://github.com/user-attachments/assets/b314df04-b129-4480-9e67-221cbd78f7a9"> | <img width="250" src="https://github.com/user-attachments/assets/0efc67b4-6e35-4c89-a1d0-241ec85d397b"> | <img width="250" src="https://github.com/user-attachments/assets/918a8e6b-8701-45c9-bd7c-26b3024ec773">
