### ISSUE TITLE
[Web UI]: Use new overrides approach for Password Manager

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#42648]

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.75.95 Chromium: 132.0.6834.46 (Official Build) nightly (64-bit)
-- | --
Revision | 1adb0a920ea370950a68a2f4c01280f3097c6c4d
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

Verified using the testplan from https://github.com/brave/brave-core/pull/26848#issue-2716255711

1. Installed 1.75.95
2. launched Brave
3. opened `brave://password-manager`
4. The sidebar on the left should still use Blurple as its highlight color




1.73.101 | 1.75.95 
---- | -----
![Image](https://github.com/user-attachments/assets/6fff81a1-3983-487d-af35-16b8bcad5a91)|![Image](https://github.com/user-attachments/assets/85175b3e-5b90-4931-aca3-a4347ac49413)
![Image](https://github.com/user-attachments/assets/73df835c-4c69-4414-a220-07249dc78289)|<img width="960" alt="Image" src="https://github.com/user-attachments/assets/a6632fcb-1e49-46fc-9009-bc91ab84937b"/>
