### ISSUE TITLE
[Web UI]: Use new overrides approach for downloads

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#42646]

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using

```
Brave | 1.75.95 Chromium: 132.0.6834.46 (Official Build) nightly (64-bit)
-- | --
Revision | 1adb0a920ea370950a68a2f4c01280f3097c6c4d
OS | Windows 11 Version 24H2 (Build 26100.2314)
```
Verified the issue from the testplan from https://github.com/brave/brave-core/pull/26847#issue-2716237174

- Downloaded a file
- Confirmed progress color is blurple on brave://downloads page like in previous version - Compared with current release `1.73.101`

chrome://downloads | 1.73.101 |1.75.95 
---------- | ---------- | -------------
![image](https://github.com/user-attachments/assets/2c67df38-3ecb-4172-8d52-696792925a2d)|![image](https://github.com/user-attachments/assets/916e2d35-a045-453b-b857-44a178d60cf7)|![image](https://github.com/user-attachments/assets/a2dbb6bc-fd32-4644-9830-beff0dba6826)
