### ISSUE TITLE
[Web UI]: Use new overrides approach for history

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#42649]

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.75.95 Chromium: 132.0.6834.46 (Official Build) nightly (64-bit)
-- | --
Revision | 1adb0a920ea370950a68a2f4c01280f3097c6c4d
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

Verified the issue using the testplan from https://github.com/brave/brave-core/pull/26879#issue-2719143125

- Confirmed style of sidebar on `brave://history` is unchanged
- Confirmed menu item on each history is horizontal NOT vertical


example | example 
----|----
![Image](https://github.com/user-attachments/assets/d93d8f19-5d19-47c5-bf44-888ca360f6e9)|![Image](https://github.com/user-attachments/assets/6f31861a-a717-43e2-956d-30d3cda58d79)
