### ISSUE TITLE
Brave Ads default fallback language should be "en-US" instead of "en-cUS"

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#4264]
## Description 
Brave Ads default fallback language should be "en-US" instead of "en-cUS". This default language is only used if Windows or Linux where unable to provide the locale which is very unlikely.

## Steps to Reproduce
See miscellaneous information below

## Actual result:
If Windows or Linux fail to provide a locale, then "en-cUS" is provided as a default

## Expected result:
"en-US" should be used as the default if Windows or Linux fail to provide a locale

## Reproduces how often: 
See miscellaneous information below

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the dev channel? YES
- Can you reproduce this issue with the nightly channel? YES

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

## Miscellaneous Information:
This issue is very unlikely to ever surface and was just added as defensive code if the Windows API or Linux environment variables fail.

**Comment by kjozwiak** [comment]
@tmancey looks like this was assigned a `QA/No` label. Should QA go through the above to make sure language selection for ads is working as expected? Just double checking to make sure we're not missing anything here 👍

**Comment by tmancey** [comment]
@kjozwiak Unfortunately this is not easy to test as it is just defensive code if the operating system fails to provide a locale. This could be tested on Linux by removing the env variables associated with locales, I cam help if need be. Thanks

**Comment by kjozwiak** [comment]
@tmancey no worries! Appreciate the info. We'll leave it as `QA/No` 👍
