### ISSUE TITLE
[Settings]: Settings subpages are missing background color

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#42642]
1. Navigate to a Settings subpage (such as brave://settings/manageProfile)

Expected:
Background of settings is white
![Image](https://github.com/user-attachments/assets/fa39fb25-372c-4782-a497-72b066f37f23)

Actual:
There is no background (its transparent and uses the gray)
![Image](https://github.com/user-attachments/assets/1d907109-9ab3-4ca9-bdac-3e4dfab02f7d)

**Comment by LaurenWags** [comment]
Requires `1.74.21` or higher for verification 👍🏻

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.74.24 Chromium: 132.0.6834.33 (Official Build) beta (64-bit)
-- | --
Revision | 3f746b728dd340e7d438b026bddf72f4001c1088
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

Confirmed sub pages/nested pages of brave://settings show background color as expected

1.75.x | 1.74.24
----- | -----
![Image](https://github.com/user-attachments/assets/b19c3cc5-0a98-4f66-8dad-213ebe469008)|![Image](https://github.com/user-attachments/assets/d1ae2be4-46ac-4f17-b075-0fbe3003eeae)
![Image](https://github.com/user-attachments/assets/cc29b32f-bc6c-4200-abef-a7dfab3a1264)|![Image](https://github.com/user-attachments/assets/54f885b4-7086-4904-b1e9-5d5a18439ed3)



example | example
----- | -----
![Image](https://github.com/user-attachments/assets/573bb929-ae07-4e18-9387-d6b7d42a41a2)|![Image](https://github.com/user-attachments/assets/4d79025d-8583-4413-80da-1e4457010b12)
