### ISSUE TITLE
[Web UI]: Use new overrides approach for Bookmarks page

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#42653]

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.75.95 Chromium: 132.0.6834.46 (Official Build) nightly (64-bit)
-- | --
Revision | 1adb0a920ea370950a68a2f4c01280f3097c6c4d
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

Verified the issue using the testplan from https://github.com/brave/brave-core/pull/26880#issue-2719152132

- Installed 1.75.95
- launched Brave
- opened few sites and added few bookmarks 
- Open chrome://bookmarks
- Confirmed Menus on the right should not be Blue, and should not have round highlights (they should be the same as the previous version) - compared with `1.73.101`


chrome (131.0.6778.139) | 1.73.101 |1.75.95 
---- | ------ | -----
![Image](https://github.com/user-attachments/assets/d64537ea-0005-4848-991b-75d072effcf4)|![Image](https://github.com/user-attachments/assets/707baeab-92ab-4c0f-9ea8-48aae0022e19)|![Image](https://github.com/user-attachments/assets/8adca3ae-cc3f-4b01-930f-567ed1d31319)
