### ISSUE TITLE
[Web UI]: Use new overrides approach for extensions page

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#42652]

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.75.95 Chromium: 132.0.6834.46 (Official Build) nightly (64-bit)
-- | --
Revision | 1adb0a920ea370950a68a2f4c01280f3097c6c4d
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

Verified the testplan from https://github.com/brave/brave-core/pull/26881#issue-2719192721

Open chrome://extensions
Confirmed Sidebar should be the same, when compared with current release 1.73.101

chrome (131.0.6778.139) | 1.73.101 | 1.75.95
------- | -------- | ---------
![Image](https://github.com/user-attachments/assets/46937531-8117-413e-83e6-46b4d595ddac)|![Image](https://github.com/user-attachments/assets/5eaa8175-289a-4d6e-a2c6-a5332d4cb92b)|![Image](https://github.com/user-attachments/assets/f1ef481f-ef85-4ac0-b7bd-4a2a2efff063)
