### ISSUE TITLE
Click on `Create a new tab group` via the hamburger menu does nothing

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#42663]
### Description

Found while testing https://github.com/brave/brave-browser/issues/41761
Click on `Create a new tab group` via the hamburger menu does nothing

### Steps to reproduce

1. Clean profile 1.75.69 CR132
2. Click on hamburger menu
3. Click on `Tab group`->`Create a new tab group`

### Actual result

Click on `Create a new tab group` via the hamburger menu does nothing

### Expected result

Click on `Create a new tab group` via the hamburger menu should open create tab group modal popup

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.75.69 Chromium: 132.0.6834.15 (Official Build) nightly (64-bit)
-- | --
Revision | deb39c780c5ec5570f05476b4ebd60748abd3d23
OS | Windows 10 Version 22H2 (Build 19045.5131)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @rebron @emerick

**Comment by kjozwiak** [comment]
The above requires `1.74.21` or higher for `1.74.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.74.24 Chromium: 132.0.6834.33 (Official Build) beta (64-bit)
-- | --
Revision | 3f746b728dd340e7d438b026bddf72f4001c1088
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

#### Confirmed top-level menu for Tab-groups is hidden


1.75.67 | 1.74.24
----- | ----
![Image](https://github.com/user-attachments/assets/46fd43d5-8043-438d-ba2d-e6a5411c1283)|![Image](https://github.com/user-attachments/assets/767a2c54-0846-4664-935c-747aeab1a9d5)
