### ISSUE TITLE
Unable to open tab group sites via Hamburger menu

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#42668]
### Description

Found while testing https://github.com/brave/brave-browser/issues/41761
Unable to open tab group sites via Hamburger menu

### Steps to reproduce

1. Clean profile 1.75.69 CR132
2. Click on hamburger menu
3. Click on `Tab group`->mouse hover on created tab group->click on any tabs under `Tabs in group` section
4. Site/tab in not opened in a new tab 
 

### Actual result

Unable to open tab group sites via Hamburger menu
![Image](https://github.com/user-attachments/assets/b9eb9be7-e703-47af-b6a5-91d7f799dc68)

### Expected result

Should be able to open a tab group via hamburger menu

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.75.69 Chromium: 132.0.6834.15 (Official Build) nightly (64-bit)
-- | --
Revision | deb39c780c5ec5570f05476b4ebd60748abd3d23
OS | Windows 10 Version 22H2 (Build 19045.5131)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @emerick @rebron

**Comment by kjozwiak** [comment]
The above requires `1.74.21` or higher for `1.74.x` verification 👍
