### ISSUE TITLE
`Unpin group from bookmarks` menu option is not working as expected

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#42666]
### Description

Found while testing https://github.com/brave/brave-browser/issues/41761
`Unpin group from bookmarks` menu option is not working as expected 

### Steps to reproduce

1. Clean profile 1.75.69 CR132
2. Click on hamburger menu
3. Click on `Tab group`->mouse hover on created tab group->click on `Unpin tab group from bookmarks`
4. Tab group is not unpinned from bookmarks

### Actual result

`Unpin group from bookmarks` menu option is not working as expected 
![Image](https://github.com/user-attachments/assets/f666c3d5-06d2-4b8b-aa36-1cd833c8e127)

### Expected result

Should be able to unpin the tab group from bookmarks via hamburger menu

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.75.69 Chromium: 132.0.6834.15 (Official Build) nightly (64-bit)
-- | --
Revision | deb39c780c5ec5570f05476b4ebd60748abd3d23
OS | Windows 10 Version 22H2 (Build 19045.5131)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @emerick @rebron

**Comment by kjozwiak** [comment]
The above requires `1.74.21` or higher for `1.74.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.74.24 Chromium: 132.0.6834.33 (Official Build) beta (64-bit)
-- | --
Revision | 3f746b728dd340e7d438b026bddf72f4001c1088
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

#### Confirmed Tab groups menu item is hidden in the hamburger menu


1.75.67 | 1.74.24
----- | ----
![Image](https://github.com/user-attachments/assets/46fd43d5-8043-438d-ba2d-e6a5411c1283)|![Image](https://github.com/user-attachments/assets/fdb05450-dbc5-429f-bdc1-4c3c9180a936)
