### ISSUE TITLE
`Move group to new window` menu option via hamburger menu isn't working as expected

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#42667]
### Description

Found while testing https://github.com/brave/brave-browser/issues/41761
`Move group to new window` menu option via hamburger menu isn't working as expected 

### Steps to reproduce

1. Clean profile 1.75.69 CR132
2. Click on hamburger menu
3. Click on `Tab group`->mouse hover on created tab group->click on `Move group to new window`
4. Tab group is not moved to new window.

### Actual result

`Move group to new window` menu option via hamburger menu isn't working as expected 
![Image](https://github.com/user-attachments/assets/e1c14d9f-647d-4ceb-a9eb-a750f0f32a20)

### Expected result

Click on `Move group to new window` menu option via hamburger menu should open tab group in a new window

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.75.69 Chromium: 132.0.6834.15 (Official Build) nightly (64-bit)
-- | --
Revision | deb39c780c5ec5570f05476b4ebd60748abd3d23
OS | Windows 10 Version 22H2 (Build 19045.5131)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

CC: @brave/qa-team @rebron @emerick

**Comment by kjozwiak** [comment]
The above requires `1.74.21` or higher for `1.74.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.74.24 Chromium: 132.0.6834.33 (Official Build) beta (64-bit)
-- | --
Revision | 3f746b728dd340e7d438b026bddf72f4001c1088
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

#### Confirmed Tab groups menu item is hidden in the hamburger menu



![Image](https://github.com/user-attachments/assets/fdb05450-dbc5-429f-bdc1-4c3c9180a936)
