### ISSUE TITLE
Click on `Open group` via hamburger menu does nothing

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#42664]
### Description

Found while testing https://github.com/brave/brave-browser/issues/41761
Click on `Open group` via hamburger menu does nothing

### Steps to reproduce

1. Clean profile 1.75.69 CR132
2. Click on hamburger menu
3. Click on `Tab group`->mouse hover on created tab group->click on `Open group`
4. Tab group doesn't open

### Actual result

Click on `Open group` doesn't open/expand the tabs in the tab group
![Image](https://github.com/user-attachments/assets/f11e0866-262c-41a4-9731-43d7c6bca71a)

### Expected result

Click on `Open group` should open/expand the tabs in the tab group

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.75.69 Chromium: 132.0.6834.15 (Official Build) nightly (64-bit)
-- | --
Revision | deb39c780c5ec5570f05476b4ebd60748abd3d23
OS | Windows 10 Version 22H2 (Build 19045.5131)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/legacy_qa @emerick @rebron

**Comment by emerick** [comment]
@GeetaSarvadnya Steps should probably note that you have to create a couple of tab groups and click the option to save them. At least, it wasn't obvious to me... :-)

**Comment by kjozwiak** [comment]
The above requires `1.74.21` or higher for `1.74.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.74.24 Chromium: 132.0.6834.33 (Official Build) beta (64-bit)
-- | --
Revision | 3f746b728dd340e7d438b026bddf72f4001c1088
OS | Windows 11 Version 24H2 (Build 26100.2314)
```


#### Confirmed Tab groups menu is hidden in the hamburger menu


1.75.67 | 1.74.24
----- | ----
![Image](https://github.com/user-attachments/assets/46fd43d5-8043-438d-ba2d-e6a5411c1283)|![Image](https://github.com/user-attachments/assets/fdb05450-dbc5-429f-bdc1-4c3c9180a936)
