### ISSUE TITLE
Click on `x` on search settings doesn't close the search bar 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#42678]
### Description

Click on `x` on search download history bar doesn't close the search bar 

### Steps to reproduce

1. Clean profile `1.74.x` OR `1.75.66 CR131` OR `1.75.69 CR132`
2. Open brave://downloads
3. Click on `Search` icon
4. Click on `x` button search bar is not closed

### Actual result

Click on `x` on search download history bar doesn't close the search bar 
![Image](https://github.com/user-attachments/assets/08b24c06-ddcd-4749-9d2e-f2548e51294f)

### Expected result

Click on `x` should close the search download history bar

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.75.69 Chromium: 132.0.6834.15 (Official Build) nightly (64-bit)
-- | --
Revision | deb39c780c5ec5570f05476b4ebd60748abd3d23
OS | Windows 10 Version 22H2 (Build 19045.5131)

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @brave/qa-team @emerick @rebron

**Comment by GeetaSarvadnya** [comment]
cc: @aguscruiz

**Comment by GeetaSarvadnya** [comment]
@aguscruiz : Looks like this issue is happening for all the header settings search, not only for downloads. This is a regression issue work fine on 1.73.x but broken on 1.74.x.

![Image](https://github.com/user-attachments/assets/4b63ad1a-d176-4609-b6f7-577e6ff0e42d)

cc: @rebron

**Comment by emerick** [comment]
Strangely enough, right clicking it closes it (which probably shouldn't happen). cc: @fallaciousreasoning

**Comment by fallaciousreasoning** [comment]
I think the reason right click closes it is because it closes on blur

**Comment by LaurenWags** [comment]
Requires 1.74.21 or higher for verification 👍🏻
