### ISSUE TITLE
Brave Talk audio cuts off when screen is locked

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#42675]
The page with Brave Talk becomes inactive and audio disappears in 2-3 minutes after device is locked.
STR:
1. Join a meeting using Brave Talk
2. Make sure you hear the sound from it
3. Lock your device
4. Observe the audio stops in 2-3 minutes

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 BP11.241025.006 release-keys
Brave build: 1.75.111
Chromium: 132.0.6834.46 (Official Build) canary (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/42675#issue-2717989083
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `mic` works as expected when Brave is in the `foreground`.
- Verified that the `mic` works as expected when Brave is in the `background`.
- Verified that the `mic` works as expected when a device is `locked`.

---------------------------

https://github.com/user-attachments/assets/0fb57307-29ea-487b-b297-463f1157b000
