### ISSUE TITLE
Change default value for new users for `Only open links in current tab group` option

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#42681]
### Description

To follow upstreams default behaviour we want to change default value for new users for `Only open links in current tab group` option.

### Steps to reproduce

1. Go to Appearance
2. Make sure `Only open links in current tab group` is off by default for new users
3. Make sure it retains its value for existing users

### Actual result

It is on by default

### Expected result

It is off by default for new users

### Reproduces how often

Easily reproduced

### Brave version

1.74.x

### Device

- Brand/model: n/a
- Android version: n/a

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 BP11.241025.006 release-keys
Brave build: 1.75.76 
Chromium: 132.0.6834.33 (Official Build) canary (64-bit) 
```

Filed follow-up issue #42868
---------------------------
<details>
<summary> Fresh install </summary>

**STEPS:**
1. Install and launch Brave `1.75.86`
2. Hamburger menu > Settings
3. Appearance > *Verify that `Only open links in current tab group` is OFF*
4. Close the settings, and, for example, open any article on https://foxnews.com
5. Tap any URL link in the article > *Verify that the new page is opened NOT in the group*

**ACTUAL RESULTS:**
- Verified that `Only open links in current tab group` is OFF by `default` for the new users/installs.
- Observed that the new webpages still opened in the `group` by default even with the toggle switch OFF.

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/b73ee1bb-e17f-4568-b58a-f36b5db1960f) | ![2](https://github.com/user-attachments/assets/47326fef-93a0-434a-a544-9ef2c7d89039) |

https://github.com/user-attachments/assets/bd751d0d-137d-4b01-a57a-2248e65118bb
</details>

<details>
<summary> Upgraded profile </summary>

**STEPS:**
1. 
2. 

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
</details>

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` using version(s):
```
Device/OS: Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
Brave build: 1.75.161
Chromium: 132.0.6834.83 (Official Build) beta (64-bit) 
```
---------------------------
<details>
<summary> Fresh install </summary>

**STEPS:**
1. Install and launch Brave `1.75.161`
2. Hamburger menu > Settings
3. Appearance > *Verify that `Only open links in current tab group` is OFF*
4. Close the settings, and, for example, open any article on https://foxnews.com
5. Tap any URL link in the article > *Verify that the new page is NOT opened in the group*

**ACTUAL RESULTS:**
- Verified that `Only open links in current tab group` is OFF by `default` for the new users/installs.
- Verified that the new webpages are NOT opened in the `group` if the toggle switch is OFF.

---------------------------

https://github.com/user-attachments/assets/8308e66c-45fa-41d9-9043-b5d074668d98
</details>

<details>
<summary> Upgraded profile: Toggle is OFF before upgrade </summary>

**STEPS:**
1. Install Brave `1.74.45`
2. Open `Settings` > Appearance > *Confirm that `Only open links in current tab group` is ON*
3. Turn off `Only open links in current tab group`
4. Upgrade Brave to `1.75.161`
5. Launch Brave and open `Settings` > Appearance > *Verify that `Only open links in current tab group` is OFF*
6. Go to https://foxnew.com > Open any article
7. Tap any link > *Verify that the new webpage is NOT opened in the `group tab`*

**ACTUAL RESULTS:**
- Verified that `Only open links in current tab group` is `disabled` after the Brave upgrade if the toggle switch was `disabled` before the upgrade.
- Verified that newly opened webpages are NOT opened in the `tab group`.

---------------------------

https://github.com/user-attachments/assets/ac6ff80e-4c9b-4447-9c57-80ff01c74e78
</details>

<details>
<summary> Upgraded profile: Toggle is ON before upgrade </summary>

**STEPS:**
1. Install Brave `1.74.45`
2. Open `Settings` > Appearance > *Confirm that `Only open links in current tab group` is ON*
3. Upgrade Brave to `1.75.161`
5. Launch Brave and open `Settings` > Appearance > *Verify that `Only open links in current tab group` is ON*
6. Go to https://foxnew.com > Open any article
7. Tap any link > *Verify that the new webpages are opened in the `group tab`*

**ACTUAL RESULTS:**
- Verified that `Only open links in current tab group` is `enabled` after the Brave upgrade if the toggle switch was `enabled` before the upgrade.
- Verified that newly opened webpages are opened in the `tab group`.

---------------------------

https://github.com/user-attachments/assets/58552ba0-5f83-42f4-a699-2e63e2cf96ce
</details>
