### ISSUE TITLE
Map Ctrl+Shift+S to Screenshot Feature

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#42682]
### Description

The shortcut <kbd>Ctrl+Shift+S</kbd> is well-established across browsers like Firefox, Opera, and Edge for initiating a screenshot session. Brave supports the feature, but does not ship a default shortcut. Brave should adopt the same shortcut for parity and familiarity.

**Comment by rebron** [comment]
@LaurenWags For relnotes, can use this one and maybe mention CMD+Shift+S for macOS via https://github.com/brave/brave-browser/issues/42850.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.75.157 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | d8524431e89200eff892315294bd590b314f47d2
OS | Windows 11 Version 24H2 (Build 26100.2605)
```


1. Installed 1.75.157
2. launched Brave
3. pressed `Ctrl+Shift+S`
4. confirmed `+` image icon is shown
5. dragged the icon to take a screenshot of an image
6. dragged the icon to take full page screenshot
7. Confirmed screenshot is copied to clipboard
8. clicked `Download` button
9. verified able to open `.png` file as expected

example | example | example | example 
----- | ----- | ------ | -----
![Image](https://github.com/user-attachments/assets/3325ecf6-956a-48c1-abca-6b34d43743f5)|![Image](https://github.com/user-attachments/assets/6ad43400-77f8-4885-a780-79eb836bd85a)|![Image](https://github.com/user-attachments/assets/09aefaba-ee9b-4840-9464-0d4ed68b18d3)|![Image](https://github.com/user-attachments/assets/f5e65d9e-5790-4434-89a6-2cc0a2ce31b7)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.75.168 Chromium: 132.0.6834.111 (Official Build) beta (arm64)
-- | --
Revision | 2b79fecfaacadde603f71291b8292c11ba0d22ac
OS | macOS Version 15.2 (Build 24C101)
```


Verified the issue on macOS by pressing  `CMD+Shift+S`.  
Verifications notes are in https://github.com/brave/brave-browser/issues/42850#issuecomment-2593859308

**Comment by btlechowski** [comment]
Verified with

Brave | 1.75.170 Chromium: 132.0.6834.111 (Official Build) beta (64-bit)
-- | --
Revision | ea6b6fa547193f9769ffb0068880a4f41e364864
OS | Linux


<details>

1. Installed 1.75.x
2. launched Brave
3. pressed `Ctrl+Shift+S`
4. confirmed cursor changed to crosshairs `+` icon 
5. dragged the crosshairs pointer to take a screenshot of an image
6. dragged the crosshairs pointer to take full page screenshot
7. Confirmed screenshot is copied to clipboard
8. clicked `Download` button
9. filed was saved to downloads folder
10. confirmed shortcut `Ctrl+Shift+S` is shown in `brave://settings/system/shortcuts`

![Image](https://github.com/user-attachments/assets/79a734be-ba4f-4535-8b0b-223150b304d0)|![Image](https://github.com/user-attachments/assets/f3283e19-cda2-461f-948a-2395e366a508)|![Image](https://github.com/user-attachments/assets/f4bd8383-4a76-4994-a98a-e2907fb3f644)|![Image](https://github.com/user-attachments/assets/a9f6c93e-ff4c-4ce4-b92d-5d1fe93de873)|![Image](https://github.com/user-attachments/assets/cee7f8c1-3c91-4802-9068-07aa8ec3968d)|![Image](https://github.com/user-attachments/assets/8d024581-d4c5-4593-9f05-85653be7d294)
--|--|--|--|--|--

</details>
