### ISSUE TITLE
Subdivision is fetched too frequently

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#42680]
### Description

Subdivision should be fetched on browser start and every 0.5-1.5 days.
It is fetched every hour.

### Steps to reproduce

1. Clean profile
2. Enable rewards
3. Check subdivision fetch frequency 

### Actual result

Subdivision is fetched on browser start and every hour.

```
	Line  124: [36703:36703:1204/161143.720835:VERBOSE1:subdivision_url_request.cc(104)] Fetch subdivision in 0 hours, 56 minutes, 37 seconds at 17:08:21.043
	Line 1931: [36703:36703:1204/170821.773279:VERBOSE1:subdivision_url_request.cc(104)] Fetch subdivision in 0 hours, 33 minutes, 18 seconds at 17:41:39.998
	Line 2077: [36703:36703:1204/174140.248288:VERBOSE1:subdivision_url_request.cc(104)] Fetch subdivision in 1 hour, 12 minutes, 2 seconds at 18:53:41.778
```

### Expected result

Subdivision should be fetched on browser start and every 0.5-1.5 days.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.75.66 Chromium: 131.0.6778.85 (Official Build) nightly (64-bit)
-- | --
Revision | 14bc24f2abfa4a9106607039dae171771a231d80
OS | Linux

cc @tmancey @aseren @iambrianfung

**Comment by LaurenWags** [comment]
Requires 1.74.24 or higher for verification 👍🏻

**Comment by btlechowski** [comment]
Verified with

Brave | 1.74.25 Chromium: 132.0.6834.33 (Official Build) beta (64-bit)
-- | --
Revision | 041ffab11e000929213dcdae825dba438ff8a620
OS | Linux

#### subdivision

<details>

Verified downloaded on browser launch
```
[13000:13000:1211/213209.847856:VERBOSE1:subdivision.cc(76)] Initialize subdivision URL request
[13000:13000:1211/213209.848005:VERBOSE1:subdivision_url_request.cc(58)] Fetch subdivision
[13000:13000:1211/213209.848267:VERBOSE6:subdivision_url_request.cc(64)] URL Request:
  URL: https://geo.ads.brave.com/v1/getstate
  Method: kGet
[13000:13000:1211/213209.848456:VERBOSE7:subdivision_url_request.cc(65)]   Headers:


```

Verified downloaded every 0.5 and 1.5 days
```
[26209:26209:1212/160915.846572:VERBOSE1:subdivision_url_request.cc(104)] Fetch subdivision in 15 hours, 0 minutes, 41 seconds at 07:09:56.481

```

</details>
