### ISSUE TITLE
[AI Chat]: On Android, AI Chat should open in a tab, rather than in an overlay

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#42685]

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 BP11.241025.006 release-keys
Brave build: 1.75.106
Chromium: 132.0.6834.46 (Official Build) canary (64-bit) 
```
---------------------------

**STEPS:**
1. Launch Brave
2. Open `Leo` by going to `Hamburger menu` > `Leo` > Verify*
3. Open `Leo` by going to `URL search bar` > Type a query > `Ask Leo` > *Verify*
4. Open `Leo` by going to `URL search bar` > Type a query > Choose `Leo` via `QSE` > *Verify*

***ACTUAL RESULTS:**
- Verified that the `Leo` conversation opened in the `new tab` but not in an `overlay`.
- Verified that the same works as expected when opening `Leo` via different entry points.

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/1d2b5cf8-0975-45b0-a22c-5cc121c754e4) | ![2](https://github.com/user-attachments/assets/7b8a7942-1cdf-4ada-b07b-9091707ff18f) |
