### ISSUE TITLE
Add 3-second timer for HTTPS upgrades before falling back to HTTP on iOS

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#42684]
### Description

Add a 3-second timer for HTTPS upgrades before falling back to the original http request.

Chromium does this for iOS: https://source.chromium.org/chromium/chromium/src/+/main:ios/components/security_interstitials/https_only_mode/https_upgrade_service.h;l=72;drc=1651676a30cd7abcd177975f7cd0e37bd945f663

And desktop/android ([overridden to 30s for tor windows](https://github.com/brave/brave-core/blob/7c63b71514a5f9df6313363171f7ea078447d4f6/chromium_src/chrome/browser/ssl/https_upgrades_navigation_throttle.cc#L19)):
https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ssl/https_upgrades_navigation_throttle.cc;l=37;drc=5108636c70c0b08fdbeb57de2640a22e138f6685

### Steps to reproduce

1. In Settings -> 'Privacy & Security' set 'Upgrade Connections to HTTPS' to `Standard` or `Strict`
2. Visit `alwayshttp.com`

### Actual result

In `Standard` mode, a long delay before displaying `http://www.alwayshttp.com`
In `Strict` mode, a long delay before displaying interstitial for `alwayshttp.com` then `www.alwayshttp.com`

### Expected result

We should fallback to the original http request after 3-seconds to align with Chromium.

### Reproduces how often

Easily reproduced

### Brave version

Any

### Device/iOS version

Any

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

### Miscellaneous information

Follow up for https://github.com/brave/brave-core/pull/26781#pullrequestreview-2468851164

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Mini (6th gen)` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.7.2
- iPad Mini (6th gen) / iPadOS 18.1.1
Brave build: 1.75 (148)
BraveCore: 1.75.148 (132.0.6834.57)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/26871#issue-2718731713
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `http://www.alwayshttp.com/` loads after ~6 seconds if `Upgrade Connections to HTTPS` is set to `Standard` mode.
- Verified that the interstitial page for `alwayshttp.com` is shown after ~3 seconds if `Upgrade Connections to HTTPS` is set to `Strict` mode.
- Verified that the interstitial page for `www.alwayshttp.com` is shown after ~3 seconds if `Upgrade Connections to HTTPS` is set to `Strict` mode when tapping `Proceed` on a previous page.
- Verified that `http://www.alwayshttp.com` loads after ~6 seconds when tapping `Proceed` on a previous page.

---------------------------

<details>
<summary> iPhone 14 </summary>

### `HTTPS` is set to `Standard`

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/783cc5e8-bcc5-4e62-945e-0ebdd20aa615) | ![2](https://github.com/user-attachments/assets/775102e2-7e43-4f94-896b-b0ca15c08cd7) |

### `HTTPS` is set to `Strict`

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/a94c10cb-f195-4c89-a9e9-91107a376e60) | ![2](https://github.com/user-attachments/assets/3bbd164e-078d-48c2-9ea1-722f363bbe6a) | ![3](https://github.com/user-attachments/assets/f0ac4f94-15ba-4253-977d-882fcac6c596) | ![4](https://github.com/user-attachments/assets/a18cf050-80bc-47b5-ba23-e77c30264644) |
</details>

<details>
<summary> iPad Mini </summary>

### `HTTPS` is set to `Standard`

https://github.com/user-attachments/assets/8ab4ddc1-f318-4137-a2d9-8f7f3da682e1

### `HTTPS` is set to `Strict`

https://github.com/user-attachments/assets/0e88b5c3-d58e-4078-8f63-69e37e595b0e

### `Private tab`

https://github.com/user-attachments/assets/4a1debbc-0994-4310-a093-8774b7129ac9

</details>
