### ISSUE TITLE
Transaction Partner Modal does not dismiss on first click

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#42687]
### Description

User has to click `Continue` twice to dismiss `Transaction partner` consent modal.

### Steps to reproduce

1. Create a brand new wallet.
2. Click on `Buy` in the side navigation.
3. Once the `Transaction partner` modal appears click the `Continue` button.
4. You have to click it twice for it to be dismissed. 

### Actual result

https://github.com/user-attachments/assets/4ee9518e-4ed5-4be8-b70d-ccebcf97c6df

### Expected result

Should only need to click `Continue` once for the modal to be dismissed.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.74.18 Chromium: 131.0.6778.85 (Official Build) beta (arm64) 

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.74.25` or higher for `1.74.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.74.25 Chromium: 132.0.6834.33 (Official Build) beta (64-bit)
-- | --
Revision | 041ffab11e000929213dcdae825dba438ff8a620
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from [brave/brave-core#26897](https://github.com/brave/brave-core/pull/26897)
- Verified transaction partner modal is closed on first click

https://github.com/user-attachments/assets/db128d51-d981-4850-916d-56815840d1ea
