### ISSUE TITLE
Empty entry in app menu of guest window

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#42693]
### Description

![Image](https://github.com/user-attachments/assets/4e45c6c9-45af-435e-93de-ad750d2fa424)

### Steps to reproduce

1. Open guest window
2. Open app menu
3. 

### Actual result

Empty entry above Sidebar.

### Expected result

No empty entry

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.75.69 Chromium: 132.0.6834.15 (Official Build) nightly (arm64) 

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.74.26` or higher for `1.74.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.74.26 Chromium: 132.0.6834.46 (Official Build) beta (64-bit)
-- | --
Revision | b156def5148350d62f73b53a3a56d930ad5b20d4
OS | Windows 10 Version 22H2 (Build 19045.5247)
```
