### ISSUE TITLE
[iOS] - Remove mentions of third-party services in VPN

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#42709]
### Description

- VPN mentions Netflix, Hulu, BBC.
- We should remove these

### Steps to reproduce

1. Visit Settings -> VPN -> Smart Proxy (The Text below the switch)

### Actual result

- Shows Netflix and others

### Expected result

- Remove Netflix and others

### Reproduces how often

Easily reproduced

### Brave version

1.75.x

### Device/iOS version

All

### Affected browser versions

- [ ] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.2` using version `1.75 (115)`

* Ensured that the specific third-party services (Netflix, Hulu, BBC) mentioned in the Smart Proxy switch description are removed. 

![Image](https://github.com/user-attachments/assets/c48bfa66-03a3-4c53-9671-0b8a897deb2f)
