### ISSUE TITLE
Leo AI Full-Page (chrome://leo-ai) should prompt for PWA install

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#42701]
### Description

Leo AI Full-Page (chrome://leo-ai) should prompt for PWA install

### Steps to reproduce

1. Visit chrome://leo-ai

### Expected result

Observe "install" button on toolbar

![Image](https://github.com/user-attachments/assets/e06cf9d0-f9ea-4890-8390-f5690593c40c)

### Actual result
"install" button not showing

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

1.75, 1.74

### Android device

- Brand/model: 
- Android version: 

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Also "create shortcut" app menu item is disabled, but should be enabled. All of this works on `brave://password-manager`

**Comment by hffvld** [comment]
Removing label `OS/Android` based on the conversation with @petemill. A separate issue needs to be created for the `Android` platform.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.112 Chromium: 132.0.6834.46 (Official Build) nightly (64-bit)
-- | --
Revision | f1de7e60955b06e067a605adca9d6a87d6142baf
OS | Linux

- Verified steps from issue description
- Verified Leo AI Full page shows prompt for installing PWA
- Verified installing PWA shows shortcut on Desktop
- Encountered [#43006](https://github.com/brave/brave-browser/issues/43006) & [#43007](https://github.com/brave/brave-browser/issues/43007)

https://github.com/user-attachments/assets/88e16ec1-8251-4ab1-9816-628223c75b37

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.75.112 Chromium: 132.0.6834.46 (Official Build) nightly (arm64)
-- | --
Revision | f1de7e60955b06e067a605adca9d6a87d6142baf
OS | macOS Version 15.2 (Build 24C101)


- Verified steps from issue description
- Verified Leo AI Full page shows prompt for installing PWA
- Verified installing PWA shows shortcut on Desktop
- Encountered [#43006](https://github.com/brave/brave-browser/issues/43006),  [#43007](https://github.com/brave/brave-browser/issues/43007) & [#43008](https://github.com/brave/brave-browser/issues/43008)

https://github.com/user-attachments/assets/38f164e2-b324-4155-9db1-04d4e4b99f3a
