### ISSUE TITLE
`brave://settings/security` page is blank/not loading.

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#42707]
### Description

Visit brave://settings/security on the latest master and the page is blank.

![Image](https://github.com/user-attachments/assets/e4dadc81-c784-4fe8-b522-fd25cca6749e)

**Comment by LaurenWags** [comment]
Thanks for finding and logging this one @emerick !

I can't reproduce with `1.75.75` but can reproduce with `1.75.76`:

1.75.75 | 1.75.76
--- | ---
![Image](https://github.com/user-attachments/assets/f1788c6e-a281-4e64-b1e2-a18aa368e0f8) | ![Image](https://github.com/user-attachments/assets/fa03dbe1-13bf-4a36-8bc7-895fe60bef80)

**Comment by kjozwiak** [comment]
The above requires `1.74.23` or higher for `1.74.x` verification 👍
