### ISSUE TITLE
Add loading spinner to payout account balance amount display in Rewards 3.0 UI

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#42700]
Where the balance displays for the user's payout account, while the value is loading, it is just blank. We should add a loading spinner so that it's never empty while loading:

![Image](https://github.com/user-attachments/assets/eae2817e-a586-4ea4-9104-b6f72328f5eb)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.75.139 Chromium: 132.0.6834.57 (Official Build) nightly (64-bit)
-- | --
Revision | 824a4385d099e741400ccd850d3309105a1f2c5e
OS | Windows 10 Version 22H2 (Build 19045.5247)
```
Verified Balance loading UI (includes "wave" animation) from https://github.com/brave/brave-core/pull/26891
![Image](https://github.com/user-attachments/assets/0b3c6552-9ee7-4f2c-81c5-c4237202bb11)
![Image](https://github.com/user-attachments/assets/bbe528d6-a3e1-4b79-8913-5df04bc736fe)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.75.161 Chromium: 132.0.6834.83 (Official Build) beta (x86_64)
-- | --
Revision | 7e59e37e24ad33062e0f20e842236aa03f579407
OS | macOS Version 14.7.2 (Build 23H311)
```
