### ISSUE TITLE
QSE panel overlaps on-screen keyboard

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#42706]
### Description

QSE panel overlaps the on-screen keyboard.

### Steps to reproduce

1. Launch Brave
2. Tap `URL search bar`
3. Send any query
4. Tap `URL search bar` again
5. Use the device `Back gesture` or `Back button` to hide the keyboard
6. Tap the `pencil` button to edit the URL/query
7. Tap `URL search bar` again > *Observe*

### Actual result

QSE panel overlaps the on-screen keyboard.

-------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/014d10ce-59c2-447a-9825-19fcc6ea09aa) | ![2](https://github.com/user-attachments/assets/e6c819f4-f936-464c-836a-d17b0a4a9e23) |

### Expected result

QSE panel must not overlap the on-screen keyboard.

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.74.18 
Chromium: 131.0.6778.85 (Official Build) beta (64-bit) 

### Device

- Brand/Model: Galaxy Tab S8, Pixel 8a, Pixel 7
- Android version: 14, 15

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.74.23` or higher for `1.74.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 BP11.241025.006 release-keys
Brave build: 1.74.23 
Chromium: 132.0.6834.33 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/42706#issue-2721217587
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the QSE panel doesn't overlap the on-screen keyboard.

---------------------------

https://github.com/user-attachments/assets/90aadca3-c706-414e-a8cb-325ded6ac55a
