### ISSUE TITLE
Links from external sources open in Brave normal browsing even though “Private browsing only” is enabled

### ISSUE THREAD

**Issue by cybercrypt7** [brave/brave-browser#42717]
### Description

Following brave ios update 1.73. When links from external sources on iOS, eg. iMessage, notes, social media are clicked, Brave opens these links in normal browsing mode and disregards the fact that “private browsing only” is enabled in settings. Force closing the app then reverts the app into private browsing mode but brave seems to be ignoring that private browsing is toggled on. 

### Steps to reproduce

1. Open any link from an external source
2. Brave opens the link in normal browsing mode
3. If you navigate to brave settings the “private browsing only” toggle will still be turned on but the mode is not enforced. Force closing the app fixes this, but opening a new link causes the same issue to occur. “Private browsing only” mode is being ignored when opening links. 

### Actual result

 N/A

### Expected result

Private browsing only mode should be enforced at all times if toggled on. 

### Reproduces how often

Easily reproduced

### Brave version

1.73

### Device/iOS version

iPhone 14 Pro Max running iOS 18.1.1

### Affected browser versions

- [x] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by yuyays** [comment]
I have faced same issues on brave version 1.73 from App Store, on IOS 17.72.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` & iPad `(7th Gen)` running `iOS 18.2` & `iOS 17.5.1` respectively using version `1.75 (105)`

* Ensured that external sources open in Private mode when Private browsing only is enabled.
* Ensured that links will still open in normal tabs. 

example | example
---|---
<img width="200" src="https://github.com/user-attachments/assets/ba947fd1-fd37-41ac-afb5-bb20ce1426df"> | <img width="500" src="https://github.com/user-attachments/assets/622b7934-142a-4da9-a83f-4b69b8e8b6cd">
