### ISSUE TITLE
Empty entry in more tools sub menu from app menu

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#42718]
### Description

Maybe cr132 regression.

![Image](https://github.com/user-attachments/assets/60f6c4aa-13ad-435b-a9b7-fb158a9674da)

### Steps to reproduce

1. Go to `More tools` sub menu of app menu
2. 
3. 

### Actual result

More tools sub menu includes empty entry

### Expected result

No empty entry

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.75.76 Chromium: 132.0.6834.33 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @brave/qa-team

**Comment by simonhong** [comment]
Fixing now.

**Comment by bsclifton** [comment]
Nice find! And thanks for fixing, @simonhong!

**Comment by kjozwiak** [comment]
The above requires `1.74.23` or higher for `1.74.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.74.24 Chromium: 132.0.6834.33 (Official Build) beta (64-bit)
-- | --
Revision | 3f746b728dd340e7d438b026bddf72f4001c1088
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

Confirmed empty entry no longer shown in the `More tools` sub menu



1.75.76 | 1.74.24
----- | -----
![Image](https://github.com/user-attachments/assets/d512ac79-fe18-41bd-882f-29f891e02d05)|![Image](https://github.com/user-attachments/assets/0c3af7ae-0209-4758-8d51-c19d8921ca48)
