### ISSUE TITLE
Option To Disable Brave shield on all bank and network providers site by default

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [brave/brave-browser#4271]
## Description 

It is not possible to recharge through vodafone or airtel network providers site and also after click pay securely through internet banking ,the page do not get redirected to the bank sites and the page becomes unreponsive

## Steps to Reproduce

   1. Go to https://shop.vodafone.in/shop/prepaid/easy-online-recharge.jsp
   2. enter mobile no, recharge amount
   3. click on pay (purple button)
   4.Select bank and click on pay securely button and wait the page will becom unresponsive
## Actual result:

![image](https://user-images.githubusercontent.com/38154154/56943512-79135d00-6b3d-11e9-849c-31d0b87cc8f1.png)

![image](https://user-images.githubusercontent.com/38154154/56943676-369e5000-6b3e-11e9-92d8-1ce1af9b5bee.png)

## Expected result:
It should redirect to the bank site for online payment

## Reproduces how often: 

Every time i tried to recharge
## Brave version (brave://version info)

Version 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)
## Version/Channel Information:

I don't know
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?not tried
- Can you reproduce this issue with the dev channel?not tried
- Can you reproduce this issue with the nightly channel?not tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? no tried
- Is the issue reproducible on the latest version of Chrome? no

**Comment by Brave-Matt** [comment]
@Ashutosh-Kukreti,
Have you tried disabling individual settings in the Shields panel? There's a good chance only one of these settings needs to be disabled for the site to work. It would also help us further diagnose the issue with that information.

**Comment by Ashutosh-Kukreti** [comment]
Ok got it,
It only works when all cookies are allowed option is selected in the shield , keeping everything else the same.

**Comment by Ashutosh-Kukreti** [comment]
Why did you closed it?
Brave really needs to fix this,it is not possible to make payments with it on many sites.

**Comment by tomlowenthal** [comment]
We're not going to automatically switch off Shields based on the category of site you're visiting.

If a particular site you're using doesn't work with Shields, you can turn Shields off for that site in particular, and Brave will remember your choice. You can also report the problem to us, one site at a time and we'll investigate the problems with that particular site
