### ISSUE TITLE
Crash when clicking profile button in guest window

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#42715]
### Description

Browser crashed right after clicking profile button in guest window.
Maybe this came from cr132 upgrade.

### Steps to reproduce

1. Open guest window
2. Click profile button
3. 

### Actual result

Crashed

### Expected result

No crash

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.75.66 Chromium: 131.0.6778.85 (Official Build) nightly (x86_64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc @rebron @brave/qa-team @cdesouza-chromium @emerick

**Comment by kjozwiak** [comment]
The above requires `1.74.23` or higher for `1.74.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.74.24 Chromium: 132.0.6834.33 (Official Build) beta (64-bit)
-- | --
Revision | 3f746b728dd340e7d438b026bddf72f4001c1088
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

Reproduced the issue in `1.75.66` using the STR from https://github.com/brave/brave-browser/issues/42715#issue-2721953583

Confirmed no crash happened when clicked profile button in guest window

![Image](https://github.com/user-attachments/assets/281cdd7a-735e-4b33-be2a-ed8519d8bd63)
