### ISSUE TITLE
How to disable dark theme,Downloaded file name is not readable

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [brave/brave-browser#4272]
## Description 

Please add an option to disable the dark theme,nothing is visible on the download bar.Please refer to the screenshot.

## Steps to Reproduce

   1. Set brave theme type to light and os theme type to dark
   1. Download any pdf or receipt from any site.
## Actual result:

![download](https://user-images.githubusercontent.com/38154154/56943913-32266700-6b3f-11e9-94d1-1a21f95b5fe8.PNG)

## Expected result:
It should be displayed clearly

## Reproduces how often: 

Everytime I download a receipt of payment

## Brave version (brave://version info)

Version 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)

## Version/Channel Information:

I don not know
- Can you reproduce this issue with the current release?Yes
- Can you reproduce this issue with the beta channel?not tried
- Can you reproduce this issue with the dev channel?not tried
- Can you reproduce this issue with the nightly channel?not tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards?No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

My theme is set to light in the settings but everything is dark.

**Comment by Ashutosh-Kukreti** [comment]
This will apply dark theme to the whole browser,

But that’s not what I want,
I want windows in dark mode and brave with light theme.This does not fixed my problem so there is no point in closing this issue,please fix the light theme in settings

**Comment by simonhong** [comment]
Hi @Ashutosh-Kukreti ,
With this https://github.com/brave/brave-core/pull/2352, you can use light theme as a whole brave browser theme regardless of windows theme.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.66.87 Chromium: 75.0.3770.80 (Official Build) beta (64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Windows 7 Service Pack 1 (Build 7601.24465)

Verified test plan from https://github.com/brave/brave-core/pull/2352 and from the description.

![image](https://user-images.githubusercontent.com/34715963/59317597-f34e0a00-8cc3-11e9-8ac8-4c74cbbb8eb2.png)
