### ISSUE TITLE
[Follow up to #35674] Webcompat reports are not sent [iOS] 

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#42736]
### Description

Webcompat reports are not being sent on 1.74.x (Beta app), impacts iOS only

Related to https://github.com/brave/brave-browser/issues/35674

### Steps to reproduce

1. Connect to HTTP proxy
2. Load a webpage, disable Shields
3. Open Shields panel, Use `Report a Broken Site` to sent a report
4. Confirm report is sent using proxy

### Actual result

Report not sent

### Expected result

Should be sent

### Reproduces how often

Easily reproduced

### Brave version

1.74.20 (Beta) - Reproducible
1.72.x (Beta) - Not reproducible
1.73.97 (Release) - Not reproducible

### Device/iOS version

iPhone 12, iOS 18

### Affected browser versions

- [ ] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [x] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by vadimstruts** [comment]
Closed as it is not reproducible
