### ISSUE TITLE
Syntax error at npm run init

### ISSUE THREAD

**Issue by zavodil** [brave/brave-browser#4274]
## Description 

Any ideas why am I getting it? Trying to npm run init on windows

SyntaxError: invalid syntax
  File "C:\brave-browser\src\brave\vendor\python-patch\patch.py", line 1062
    print headline.rstrip('\n')
                 ^
SyntaxError: invalid syntax

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave@0.66.32 init: `node ./scripts/sync.js --init`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brave@0.66.32 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by krionical** [comment]
Did you find a solution to this? I am having the same issue, except in linux.

**Comment by bsclifton** [comment]
@krionical are you using Python 2? That is required for building
