### ISSUE TITLE
local LEO ai chat saving

### ISSUE THREAD

**Issue by GyomeiHimejima9906** [brave/brave-browser#42750]
### Platforms

all

### Description

can add possibility to save LEO chat locally to resume it (without saving it on the server but only on devices and sync account)

**Comment by GyomeiHimejima9906** [comment]
https://community.brave.com/t/local-leo-ai-chat-saving/585625

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the feature request template to include an option for saving LEO chat locally. Added 'LEO' as a new platform option and updated the description to mention the possibility of saving chats locally without server storage.

You can review changes in this commit: https://github.com/mnmnk43434/brave-brave-browser-42750/commit/b787547b6ec8606974c33384783995cd56e4c29c.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by diracdeltas** [comment]
yes, this is going to be done soon with #42854
