### ISSUE TITLE
Dark mode - active tab contrast is too low

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#42751]
### Description

Seeing various threads on reddit about the contrast of active tabs being too low, so I'm making a small tweak to improve the contrast a bit and make it closer to our color theme contrast.

Examples
https://www.reddit.com/r/brave_browser/comments/1h9okcm/looking_for_a_browser_theme_that_is_dark_but/

### Contrast details

**Current color themes tabbar/active-tab backgrounds (Chromium's default):**
![Image](https://github.com/user-attachments/assets/69b9bbb1-274d-45f6-8d01-1481b7e006e7)

**Current dark gray themes tabbar/active-tab backgrounds:**
![Image](https://github.com/user-attachments/assets/36352d0d-0053-421d-a934-108b3cfc3a8f)

**New dark gray themes tabbar/active-tab backgrounds:**
![Image](https://github.com/user-attachments/assets/6b01e09b-e767-4851-ae7c-e30d0affcaf9)

-

### Actual result

![Image](https://github.com/user-attachments/assets/38e177fe-40ef-4a8e-8e41-2125869abde8)

### Expected result

![Image](https://github.com/user-attachments/assets/d1bcaf75-13c7-4f72-8abe-c73b9a667623)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

----

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by LaurenWags** [comment]
@aguscruiz please add the following required labels as appropriate:
- `QA/Yes` or `QA/No`
- `release-notes/exclude` or `release-notes/include`

cc @kjozwiak

**Comment by aguscruiz** [comment]
Added them, sorry @LaurenWags ! cc @rebron in case you want to exclude them from release notes

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.75.159 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | a7b6f5093a2dad31fc3f56241a7d55be255e69e2
OS | Windows 11 Version 24H2 (Build 26100.2605)
```



example | example | example | example | example | example | example | example | example
-----| ----- |----- | ----- | ----- | ----| -----| ----- | -----
![Image](https://github.com/user-attachments/assets/fb7f7c80-882d-464e-9802-d745ce52497d)|![Image](https://github.com/user-attachments/assets/10de8710-0faa-4839-b8e0-9d2a803010c5)|![Image](https://github.com/user-attachments/assets/18332a35-6cd2-4b7a-8bec-0b52ed7bc503)|![Image](https://github.com/user-attachments/assets/3ca356a5-1cf8-457a-b9ae-3f7e6dd82058)|Image](https://github.com/user-attachments/assets/187c1f28-c120-4541-9e9a-68e89efcf0c7)|![Image](https://github.com/user-attachments/assets/39500a5e-c056-43e2-ae0f-e5b6eb495727)|!Image](https://github.com/user-attachments/assets/c48c02fe-661c-4414-a9e9-40a5d9cc31b9)|![Image](https://github.com/user-attachments/assets/c1fe84e5-a66d-41ff-be4d-c8b82d7ccf1c)|![Image](https://github.com/user-attachments/assets/9d114a81-785c-4a1a-bd3c-54c253091f51)|

**Comment by NicholasFlamy** [comment]
So I'm not going crazy, this is a recent thing. Well, I might make a feature request for highlighting the current tab in neon red or something because I hate when these anti-UX UI changes happen. (And most of these bad changes are by Google through Chromium.)

**Comment by el-pol** [comment]
thank you!
