### ISSUE TITLE
Update l10n for VPN NTP card.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#42769]
For:
* French
* German
* Japanese
* Portuguese (Brazil)
* Spanish (LatAm)
* Italian
* Turkish
* Arabic
* Indonesian
* Korean
* Thai
* Vietnamese
* Russian

**Comment by kjozwiak** [comment]
The above requires `1.73.101` or higher for `1.73.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.73.101 Chromium: 131.0.6778.139 (Official Build) (64-bit)
-- | --
Revision | 45dae32a9fd5d259796f6c975ec055564fac7139
OS | Windows 10 Version 22H2 (Build 19045.5131)
```

**VPN card widget on NTP**

**_Connected state_**

French | German | Russia | Japanese 
--------|----------|--------|----------
![Image](https://github.com/user-attachments/assets/5d4c3bd6-0fbc-482c-92c1-33d3edeb0b7d) | ![Image](https://github.com/user-attachments/assets/b22bbfef-9b93-4972-ba88-61b074dddaf5) | ![Image](https://github.com/user-attachments/assets/347e4d5d-c2d8-4928-92b6-eef42da52efa) | ![Image](https://github.com/user-attachments/assets/340f3328-8644-4c4f-8ecb-4ca4c5d1b0bd)


**_Disconnected state_**

French | German | Russia | Japanese 
--------|----------|--------|----------
![Image](https://github.com/user-attachments/assets/e6ef9e5d-f887-42dd-8e59-e8158c9ed859) | ![Image](https://github.com/user-attachments/assets/12409335-0e61-41ce-acfa-474a6d6949e5) | ![Image](https://github.com/user-attachments/assets/938e5f50-e457-45e0-8918-bf7f703cb3ff) | ![Image](https://github.com/user-attachments/assets/01c7f22d-2ca0-4c24-bb9b-9de23479d69c)

**_Change country list_**

French | German | Russia | Japanese 
--------|----------|--------|----------
![Image](https://github.com/user-attachments/assets/5059a607-1426-4667-b047-8c22ede1d298) | ![Image](https://github.com/user-attachments/assets/064b71e6-37f1-478a-b07c-b17a176578b4) | ![Image](https://github.com/user-attachments/assets/7be8e398-d1a5-4e27-901b-af0b3f1cb87f) | ![Image](https://github.com/user-attachments/assets/0b183b3a-c082-4f64-8d6d-e1782f3070ef)


**VPN card on dashboard settings**

French | German | Russia | Japanese 
--------|----------|--------|----------
![Image](https://github.com/user-attachments/assets/5c0a0acc-527f-43c1-8513-97c3f2254f52) | ![Image](https://github.com/user-attachments/assets/4a5f2670-56ad-4e8f-80fd-31635409d492) | ![Image](https://github.com/user-attachments/assets/9f8434c7-a452-4175-b949-c9c79ba58345) | ![Image](https://github.com/user-attachments/assets/561650f7-74df-4738-bf67-d93649542f47)



**Hide Brave VPN**

French | German | Russia | Japanese 
--------|----------|--------|----------
![Image](https://github.com/user-attachments/assets/73e699cd-dfec-4726-9566-debf632ab7c6) | ![Image](https://github.com/user-attachments/assets/2c3fce6d-d31e-4527-bb07-5a7331787b7d) | ![Image](https://github.com/user-attachments/assets/e6cb62ad-c416-48a7-b071-d66ee525e55d) | ![Image](https://github.com/user-attachments/assets/7ca774a8-2821-4b4d-b3df-681d76cc4134)
