### ISSUE TITLE
Playlist "Enable quick-access button needs a description update"

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#42763]
Remove "(It looks like ... symbol)" from the description string in settings as the icon has changed.

![Image](https://github.com/user-attachments/assets/ab6f6fe9-94b8-455a-a542-91665d37b7a6)

**Comment by rmcfadden3** [comment]
@jamesmudgett — how about:

`Adds a playlist button (it looks like a musical note with a + symbol) beside…`

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.2` using version `1.75 (95)`

* Verified removing "(it looks like 4 lines... symbol") from the `Enable quick-access button` description in Playlist settings.

![Image](https://github.com/user-attachments/assets/9cea0e25-768c-489d-9ef1-d12fec2946bb)
