### ISSUE TITLE
SPL BAT Showing Incorrect Transfer Value in Transaction Status Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#42770]
### Description

When sending `SPL-BAT`, the transaction status shows an incorrect transfer value.

### Steps to reproduce

1. Open the `Wallet` and navigate to the `Send` screen
2. Send some `SPL-BAT` to another account
3. Confirm the `Transaction` and wait for the `Transaction Status` panel to pop up.
4. It will show an incorrect `transfer` value. example:(`17.948` will show `1.7948`)

### Actual result

https://github.com/user-attachments/assets/b61b0df4-d1cd-410c-8f20-7b019d2549d3

### Expected result

Should display the correct value being transferred.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.73.89 Chromium: 131.0.6778.69 (Official Build) (arm64) 

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.73.103` or higher for `1.73.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.73.104 Chromium: 131.0.6778.204 (Official Build) (64-bit)
-- | --
Revision | 215b794a7c1f3e28151d0f7712e32c71be48775c
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from [brave/brave-core#26939](https://github.com/brave/brave-core/pull/26939)
- Verified correct value is shown on confirmation screen

https://github.com/user-attachments/assets/66ab9045-080c-47f4-b426-2f9dd38aabc7
