### ISSUE TITLE
[hackerone] iframe download popup origin confusion

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#42772]
Reported on https://hackerone.com/bugs?organization_inbox_handle=brave_inbox&view=new&end_date=&report_id=2888770&reported_to_team=&sort_direction=descending&sort_type=latest_activity&start_date=&subject=user&substates%5B%5D=new&text_query=&limit=25&page=1 by [syarif07](https://hackerone.com/syarif07)

STR and test plan: https://bravesoftware.slack.com/archives/C7VLGSR55/p1733780897619429

**Comment by diracdeltas** [comment]
the cause of this issue (which doesn't affect chrome) is https://github.com/brave/brave-core/pull/24620

**Comment by LaurenWags** [comment]
@brave/qa-team should put verification notes under https://github.com/brave/internal/issues/1238.

**Comment by kjozwiak** [comment]
As discussed with @diracdeltas, the above needs a follow up which will be fixed/completed via https://github.com/brave/brave-browser/issues/42939. We'll want to uplift https://github.com/brave/brave-browser/issues/42939 into `1.74.x` as well so labelling https://github.com/brave/brave-browser/issues/42939 as `release/blocking` so it doesn't fall through the cracks. Labelling the following issue as `QA/No` and `release-notes/exclude` as we'll verify the fix via https://github.com/brave/brave-browser/issues/42939.
