### ISSUE TITLE
Edit Gas Slider Track Style is Broken for Low Priority

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#42775]
### Description

The `Edit Gas` slider track style is broken when sliding down to `Low` priority

### Steps to reproduce

1. Open the `Wallet` and create a pending `ERC-20` token transaction
2. When the `Confirmation` panel appears, click on the `Edit` button for `Gas Fee`
3. Move the `slider` down to `Low`
4. You will see the `fill` color appear on the right side of the `track`

### Actual result

![Image](https://github.com/user-attachments/assets/0ca0ad00-46b8-42f3-991a-e077b0d0512f)

### Expected result

![Image](https://github.com/user-attachments/assets/407bbcb8-f66b-4517-bbf0-8f283885a808)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.73.89 Chromium: 131.0.6778.69 (Official Build) (arm64) 

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.99 Chromium: 132.0.6834.46 (Official Build) nightly (64-bit)
-- | --
Revision | 3b427e6838bc157f08bb63d9ba6f245e46e090ea
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from issue description
- Verified Edit Gas slider track doesn't show fill colour when slider is set to Low
 ![Image](https://github.com/user-attachments/assets/346d3373-c21d-4dfb-a40f-7dd295a8e943)
