### ISSUE TITLE
Two ZCash accounts get created on buy screen

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#42788]
### Description

When you are prompt to create a `ZCash` account on the new `Buy` screen. There are some instances where 2 accounts get created.

### Steps to reproduce

1. Create a brand new wallet and navigate to the `Buy` screen
2. Select `ZCash` as the asset to buy, when prompt to create an account click `Cancel`
3. Re-select `ZCash` as the asset to buy, when prompt to create an account click `Create`
4. You will now have `2` ZCash accounts.

### Actual result

see https://github.com/brave/brave-core/pull/26850#issuecomment-2530573240

### Expected result

Should only create 1 account.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.75.44 Chromium: 131.0.6778.85 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.74.29` or higher for `1.74.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.31 Chromium: 132.0.6834.46 (Official Build) beta (64-bit)
-- | --
Revision | fbd8f1448360d52b035f31483af235134e7adfcc
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from [brave/brave-core#26954](https://github.com/brave/brave-core/pull/26954)
- Verified only one ZCash account is created from Buy screen

https://github.com/user-attachments/assets/28224744-b33b-4bfe-8f28-c68ae06173bb
