### ISSUE TITLE
Copying a link shows Link Copied bubble

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#42782]
### Description

Copying a link shows Link Copied bubble 

### Steps to reproduce

1. Install CR132 build
2. Open any page and right click on an URL
3. Link Copied bubble message is shown

### Actual result

https://github.com/user-attachments/assets/83984903-1cf3-4808-8e14-e139c11d7f8d

### Expected result

Toasts should not appear.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

CR132 build

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @rebron @emerick @brave/qa-team

**Comment by LaurenWags** [comment]
Reproduced on macOS with `1.75.86 Chromium: 132.0.6834.33`

![Image](https://github.com/user-attachments/assets/4704ee29-4c23-4898-9b09-c10480691e2e)

**Comment by emerick** [comment]
Related to this upstream change https://source.chromium.org/chromium/chromium/src/+/6f629f3fc569ab553702d3cd6fa72e71e6a42e38. A toast also appears when copying an image.

**Comment by aguscruiz** [comment]
I added an updated styling for this item here in the design system, under "Toast"

https://www.figma.com/design/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?node-id=1386-11575&t=iZGud6BisSrle13M-1

![Image](https://github.com/user-attachments/assets/312ee88e-1e26-4e35-8408-243769f93d66)

**Comment by LaurenWags** [comment]
Requires `1.74.27` or higher for verification 👍🏻

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.74.27 Chromium: 132.0.6834.46 (Official Build) beta (64-bit)
-- | --
Revision | 1397aa724540a0b3ad2eba98d5edd27dd7f4070f
OS | Windows 10 Version 22H2 (Build 19045.5247)
```
![Image](https://github.com/user-attachments/assets/d780f096-4846-4fbf-9610-5b0b7ec2f88b)
