### ISSUE TITLE
Able to bypass Meld partner opt-in message on Buy screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#42785]
### Description

Able to bypass Meld partner opt-in message on Buy screen

### Steps to reproduce

1. Clean wallet
2. Click on Buy in side navigation
3. Shows the Meld partner transaction partner message
4. Click Cancel, Goes back to Portfolio screen
5. Click on Send/Swap/Bridge
6. Click on Buy, Meld's transaction message is not shown
7. Change token in Buy screen, shows Meld message

### Actual result

https://github.com/user-attachments/assets/d84a4e6c-2544-41cc-afcb-583de4915dde

### Expected result

Should always show the opt-in message irrespective where Buy screen is navigated to

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.74.20 Chromium: 131.0.6778.108 (Official Build) beta (64-bit)
-- | --
Revision | 6f52e170fb1611fc69347fb24bca600ed052f7b3
OS | Windows 11 Version 23H2 (Build 22631.4460)

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.74.33` or higher for `1.74.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.41 Chromium: 132.0.6834.57 (Official Build) beta (64-bit)
-- | --
Revision | 5864eff704ffcff4c30df7041595e557036b410c
OS | Windows 11 Version 23H2 (Build 22631.4602)

- Verified steps from issue description
- Verified when selecting Buy transaction partner modal is shown
- Verified navigating to other tabs doesn't show the transaction partner modal
- Verified manually navigating to `brave://wallet/fund-wallet` shows the transaction partner modal
- Verified manually navigating to other routes doesn't show the transaction partner modal

https://github.com/user-attachments/assets/f658eda4-d096-4260-abbc-80e5f2888eb1
