### ISSUE TITLE
Upgrade from Chromium 74.0.3729.108 to 74.0.3729.131

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#4278]
QA tests:

Check branding items
Check for version bump

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.63.52 Chromium: 74.0.3729.131 (Official Build) (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.523
