### ISSUE TITLE
Speedup Transaction Button doesn't do anything

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#42799]
### Description

When clicking the `Speedup` transaction button on the `Transaction Status` panels, it doesn't do anything.

### Steps to reproduce

1. Create and submit an `EVM` transaction
2. Wait for the `Speedup` transaction alert to show up
3. Click `Speedup` transaction
4. It doesn't do anything

### Actual result

https://github.com/user-attachments/assets/37b6f77e-26e0-483a-b348-87ca24bf87b3

### Expected result

Should initiate a `Speedup` transaction

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.73.89 Chromium: 131.0.6778.69 (Official Build) (arm64) 

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.73.103` or higher for `1.73.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.73.104 Chromium: 131.0.6778.204 (Official Build) (64-bit)
-- | --
Revision | 215b794a7c1f3e28151d0f7712e32c71be48775c
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from [brave/brave-core#26967](https://github.com/brave/brave-core/pull/26967)
- Verified Speed up transaction automatically initiates new transaction

https://github.com/user-attachments/assets/dd926187-ae8d-454d-bf8f-e5a1c6a6782a
