### ISSUE TITLE
Loading indicator on Wallet seed phrase needs to be as per new design

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#42790]
### Description

Loading indicator on Wallet seed phrase needs to be as per new design

### Steps to reproduce

1. Create a new wallet 
2. Continue to backup wallet screen
3. Loading indicator is not as same

### Actual result

![Image](https://github.com/user-attachments/assets/44124a49-1afb-4156-8c64-c050c8754e99)

### Expected result

![Image](https://github.com/user-attachments/assets/c93f9e7d-c5a4-42a5-b974-24233422ca28)

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.74.x

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @Douglashdaniel

**Comment by LaurenWags** [comment]
@Douglashdaniel please add the following required labels as appropriate:
- `QA/Yes` or `QA/No`
- `release-notes/exclude` or `release-notes/include`

cc @kjozwiak

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.162 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | 1c01fd7f190ad7c9c88cb964f55e35400bf399ae
OS | Windows 11 Version 24H2 (Build 26100.2894)

- Verified steps from [brave/brave-core#26956](https://github.com/brave/brave-core/pull/26956)
- Verified loading indicator for current steps is bigger than the completed/not completed step


https://github.com/user-attachments/assets/a5ef4ec9-498d-4d80-b8b0-fc55bd135d2d
