### ISSUE TITLE
Adblock breaks image upload on Twitter

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#428]
## Description 

Adblock breaks image upload on Twitter

## Steps to Reproduce
   1. Login to Twitter 
   2. Drag and drop/ upload image to a tweet
   3. Doens't add the image 

## Actual result:

Adblock breaks image upload on Twitter

## Expected result:
Should not block adding of images to tweet

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Packaged/Release version
### Website problems only:  
- Does the issue gets fixed with Brave Shields disabled? Yes
- Does the issue reproduces on Chrome? No

### Additional Information

cc: @bbondy @lukemulks

**Comment by GeetaSarvadnya** [comment]
Validated the issue against the Latest build "Version 0.54.2 Chromium: 69.0.3497.42 (Official Build) dev (64-bit)"
