### ISSUE TITLE
[iOS] - Brave VPN is possibly having LocalStorage injection issues

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#42801]
### Description

- Some users are reporting that they cannot link their account to Desktop at all.
- The website is telling the user there is no receipt.
- However, the user gave us a screenshot, that shows there really is a receipt on the device.
- Somehow the website isn't seeing the receipt at all!

### Steps to reproduce

1. Purchase VPN on iOS
2. Attempt to link VPN to Desktop
3. User gets "No Receipt" error during linking

### Actual result

- There is a receipt, but the website cannot see it.
- User gets a linking error and can't use their subscription from iOS, on Desktop

### Expected result

- User should be able to link successfully and use the subscription on Desktop

### Reproduces how often

Intermittent issue

### Brave version

- No idea???

### Device/iOS version

All

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.2` using version `1.75 (142)`

* Verified purchasing VPN subscription (Yearly) on IOS and successfully linked to account page (account.bravesoftware.com).
* Verified that iOS subscription is shown on desktop client (1.75.136) and VPN can be enabled successfully on Nightly channel.

example | example | example
---|---|---
<img width="250" src="https://github.com/user-attachments/assets/e8418ad2-3e18-4957-948b-c562575d6078"> | <img width="250" src="https://github.com/user-attachments/assets/3ec60d8f-40d6-440c-938f-d3fdd7738dfb"> | <img width="250" src="https://github.com/user-attachments/assets/c90ee6ba-1dea-4088-b80d-db6b4d163b25">
<img width="250" src="https://github.com/user-attachments/assets/6e0dc3fb-45c2-4895-818c-e190c8998b80"> | !<img width="250" src="https://github.com/user-attachments/assets/46afa579-227c-4acf-9aea-0bf386b69b48"> | <img width="250" src="https://github.com/user-attachments/assets/d0b4425d-090a-4972-8934-a0d6c9b522b6">
<img width="250" src="https://github.com/user-attachments/assets/0c015490-94e8-4cc3-a5c1-6aa19574db83"> | <img width="250" src="https://github.com/user-attachments/assets/725ad551-f325-438f-85d8-9155f7dcda49"> | <img width="250" src="https://github.com/user-attachments/assets/67b019d1-fed8-4753-9b13-f2e2f9551285">
