### ISSUE TITLE
AI Chat conversations should persist browser restart

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#42800]
We should implement an encrypted database for AI Chat conversations

## Test Plan

1. Make the following conversations:
### Conversation without content
- Make a conversation in Leo not attached to content (toggle is disabled)
- Add an entry to the conversation and wait for the response to complete

### Conversation with content
- Make a conversation in Leo not attached to content (toggle is enabled)
- Add an entry to the conversation and wait for the response to complete

2. Restart the browser
3. Verify all conversations are available in Leo.
4. Verify the conversation with content shows the favicon and title for the conversation

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.75.162 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | 1c01fd7f190ad7c9c88cb964f55e35400bf399ae
OS | Windows 11 Version 24H2 (Build 26100.2894)

- Verified steps from issue description
- Verified initiating conversation with or without page context, conversation is retained between browser restarts
- Verified page context conversation with follow-up questions work as expected even in full page view
- Verified deleting browsing data under basic with page context conversation is retained between browser restart. 
- Encountered [#43398](https://github.com/brave/brave-browser/issues/43398) when only browser data is deleted without restarting browser
- Verified selecting Leo-Data under Advanced in clear browsing data, removes all conversation history

Scenario A | Scenario B | Scenario C
-- | -- | --
<video src=https://github.com/user-attachments/assets/ed8cd3f0-17cc-4356-ad61-be8287f4b00a> | <video src=https://github.com/user-attachments/assets/8cde5685-2189-4fb2-bf12-309a1d03b5c7> | <video src=https://github.com/user-attachments/assets/7a76c2c5-87da-492b-86c1-faa8456372cd>

-------
Verification passed on 

Brave | 1.75.162 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | 1c01fd7f190ad7c9c88cb964f55e35400bf399ae
OS | Linux

- Verified steps from issue description
- Verified initiating conversation with or without page context, conversation is retained between browser restarts
- Verified page context conversation with follow-up questions work as expected even in full page view
- Verified deleting browsing data under basic with page context conversation is retained between browser restart. 
- Encountered [#43398](https://github.com/brave/brave-browser/issues/43398) when only browser data is deleted without restarting browser
- Verified selecting Leo-Data under Advanced in clear browsing data, removes all conversation history

Scenario A | Scenario B | Scenario C
-- | -- | --
<video src=https://github.com/user-attachments/assets/f900181e-342c-4f71-8cea-8d2934e0c756> | <video src=https://github.com/user-attachments/assets/c46213ae-86b0-4c03-a307-bb61eb0334c5> | <video src=https://github.com/user-attachments/assets/638ddbf0-a02d-43aa-899d-d6384e07bdb1>

-------
Verification passed on 

Brave | 1.75.162 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | 1c01fd7f190ad7c9c88cb964f55e35400bf399ae
OS | macOS Version 15.2 (Build 24C101)

- Verified steps from issue description
- Verified initiating conversation with or without page context, conversation is retained between browser restarts
- Verified page context conversation with follow-up questions work as expected even in full page view
- Verified deleting browsing data under basic with page context conversation is retained between browser restart. 
- Encountered [#43398](https://github.com/brave/brave-browser/issues/43398) when only browser data is deleted without restarting browser
- Verified selecting Leo-Data under Advanced in clear browsing data, removes all conversation history

Scenario A | Scenario B | Scenario C
-- | -- | --
<video src=https://github.com/user-attachments/assets/ca638f76-e913-448f-a745-c75f3c97a019> | <video src=https://github.com/user-attachments/assets/259c1add-09cc-48b3-a5da-5b9243bf3e99> | <video src=https://github.com/user-attachments/assets/c57e74d4-a0ba-4b0f-b63c-785ab43b5b17>

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 15 running 1.75.166 x64 Beta build

- Verified steps from issue description
- Verified initiating conversation with or without page context, conversation is retained between browser restarts
- Verified page context conversation with follow-up questions work as expected even in full page view
- Verified deleting browsing data under basic with page context conversation is retained between browser restart. 
- Encountered [#43398](https://github.com/brave/brave-browser/issues/43398) when only browser data is deleted without restarting browser
- Verified selecting Leo-Data under Advanced in clear browsing data, removes all conversation history
- Encountered [#43575](https://github.com/brave/brave-browser/issues/43575)

Scenario A | Scenario B | Scenario C
-- | -- | --
<video src=https://github.com/user-attachments/assets/c972ca4c-0bec-4b14-9c27-2afdd0765220> | <video src=https://github.com/user-attachments/assets/66ebc570-948a-4664-8a83-178bec9ff416> | <video src=https://github.com/user-attachments/assets/8f8d2cc9-81d1-4d47-9d8b-5ccf875feccd>

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using the following version: 

```
Brave	1.75.175 Chromium: 133.0.6943.54 (Official Build) (64-bit) 
Revision	8e82be95a27b2e442e0099307c0c8ad6d12adcf0
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Verified steps from issue description
- Verified initiating conversation with or without page context, conversation is retained between browser restarts
- Verified page context conversation with follow-up questions work as expected even in full page view
- Verified deleting browsing data under basic with page context conversation is retained between browser restart. 
- Encountered [#43398](https://github.com/brave/brave-browser/issues/43398) when only browser data is deleted without restarting browser
- Verified selecting Leo-Data under Advanced in clear browsing data, removes all conversation history
- Encountered [#43575](https://github.com/brave/brave-browser/issues/43575)

Step A | Step B | Step C
--|--|--
![Image](https://github.com/user-attachments/assets/0e1c58ff-3ef3-4162-87b8-49d98d577960) | ![Image](https://github.com/user-attachments/assets/13143833-40a1-4971-8918-d27c4f07bca5) | ![Image](https://github.com/user-attachments/assets/3fb97617-ae5c-4cf5-9a56-cfa9ab900f9b)
