### ISSUE TITLE
Change AI Chat url to chrome://leo-ai

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#42817]
We should not expose chrome-untrusted:// as a visible URL to the user. And `chat` as a hostname is too generic.

## Test plan
- Visit chrome://leo-ai
- Observe full page Leo loads

- Visit chrome://settings/leo-ai
- Observe Leo's settings load

- Open the Leo sidebar
- Click the expand arrow icon
- Observe chrome://leo-ai/[conversation-id] loads

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 15 running 1.75.166 x64 Beta build
- Verified steps from issue description
- Verified visiting `brave://leo-ai` loads Leo in full page view
- Verified Opening Leo on a page, loads Leo in full page view

https://github.com/user-attachments/assets/14201820-8d03-498f-b09e-2a3660861c09


--------
Verification passed on Lenovo Tab with Android 13 running 1.75.166 x64 Beta build
- Verified steps from issue description
- Verified visiting `brave://leo-ai` loads Leo in full page view
- Verified Opening Leo on a page, loads Leo in full page view

https://github.com/user-attachments/assets/3185490f-ea11-4ec2-b9c0-99d5da33671a
