### ISSUE TITLE
[ChromeOS][Follow up to #36190] `Passwords` can't be synced/enabled on `Chromebook`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#42816]
### Description

Follow-up to #36190.

### Steps to reproduce

1. Install Brave from the Play Store on `Chromebook`
2. Launch Brave
3. Hamburger menu > Settings > Sync
4. Sart new sync or connect to the existing sync
5. When a device is in the `sync chain` already, tap `Sync options`
6. Enable `Passwords` toggle switch > *Observe*

### Actual result

`Passwords` can't be synced/enabled on `Chromebook`.

I tried it on a Chromebook without biometrics (fingerprint/face unlock) options. I was able to use only the `Gmail account password` and `PIN unlock` which can be set in OS settings.

----------------

https://github.com/user-attachments/assets/20ddfe09-c00d-489a-9ad5-4714d1bd7b49

### Expected result

The user must be able to enable `Passwords` in the sync chain using the `PIN` or `Password` device unlock method.

### Reproduces how often

Easily reproduced

### Brave version

Brave build: 1.73.100
Chromium: 131.0.6778.108 (Official Build) (64-bit) 

### Device

- Brand/Model: Acer CX5400 / ChromeOS 130.0.6723.126 (Official Build) (64-bit) 
- Android version: 13

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by sw-samuraj** [comment]
The same issue on the mobile phone with Android 14. The password switch stays disabled after authentication and it can't be enabled.

![Image](https://github.com/user-attachments/assets/d6c2b588-d6c3-4d1b-a93b-8dd66072a77b)

**Comment by hffvld** [comment]
This issue should be resolved for `Android` devices with Brave `1.73.100` which will be available in Play Store soon.

**Comment by AlexeyBarabash** [comment]
I was able to reproduce it at ChromeOS emulator

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Acer CX5400` using version(s):
```
Device/OS: Acer CX5400 / ChromeOS 131.0.6778.241 (Official Build) (64-bit)
Brave build: 1.76.1 
Chromium: 132.0.6834.57 (Official Build) canary (64-bit) 
```

---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/42816#issue-2731652412
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Passwords` sync can be enabled on `ChromeOS` devices
- Verified that the password sync works as expected between `Android`, `MacOS` and `ChromeOS` devices.

---------------------------

### Enabling `Passwords` sync

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/d530bce5-dff0-478b-b0a3-3bd5ecb09170) | ![2](https://github.com/user-attachments/assets/1f253e1d-b6cd-43d8-bd10-9c18da791323) | ![3](https://github.com/user-attachments/assets/39b9d91b-b5c8-4f50-9f98-77ed63095a35) |

https://github.com/user-attachments/assets/a8a1966c-90ad-4df6-8f0b-ce3818e46830

### Upgrade Brave and enable `Passwords` sync

https://github.com/user-attachments/assets/ea9daecc-34dc-4aad-a4ed-0ec2ff24219d

### `Passwords` sync across devices

https://github.com/user-attachments/assets/f897c872-495b-441e-b7af-dbc37fa4e9de
