### ISSUE TITLE
AI Chat conversation entries should be isolated in an untrusted frame

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#42818]
LLM responses are parsed in frontend UI. The parsing is somewhat untrusted. Whilst the whole UI is in an untrusted WebUI, it would be good to reduce the API access to the entries renderer to as minimal as possible.

**Comment by LaurenWags** [comment]
Per discussion with @diracdeltas changed from `release-notes/include` to `release-notes/exclude`.
