### ISSUE TITLE
Can't delete first chat when using full page Leo

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#42829]
### Description

When using full page chat on Leo, with conversation history enabled, the user can't delete the first chat they started. They can only rename.

### Steps to reproduce

1. Enable brave://flags/#brave-ai-chat-history
2. Go to chrome-untrusted://chat/
3. Start a conversation
4. Try to delete it

### Actual result

There's no option to delete chat, only to rename it. Plus, the styling for the context menu looks a bit displaced.

<img width="531" alt="Image" src="https://github.com/user-attachments/assets/6a91b4be-2493-4ad1-bd4d-ef1d13e48a1f" />

https://github.com/user-attachments/assets/83063716-0639-4bb8-afb8-0ca4565d938e

### Expected result

User should be able to delete the first chat.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.75.86 Chromium: 132.0.6834.33 (Official Build) nightly (arm64) 

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by petemill** [comment]
oh dear - the delete option is there but you have to scroll! 😆 
<img width="351" alt="Image" src="https://github.com/user-attachments/assets/1133a8c8-8f1e-400f-8b73-a6fc622c7da5" />

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.156 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | 036ac4040dc50d4bd49b3438e20ab90686218543
OS | Windows 11 Version 23H2 (Build 22631.4602)

- Verified steps from issue description
- Verified `Delete conversation` is shown for all conversations and able to delete every conversation

https://github.com/user-attachments/assets/6951e7ea-09da-4899-aca9-633702761b0b
