### ISSUE TITLE
`Connect` string is not translated in the Russian locale

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#42824]
### Description

 `Connect` string is not translated in the Russian locale

### Steps to reproduce

1. Set OS locale to Russia
2. Clean profile `1.73.101`
3. Connect Brave VPN
4. Open an NTP and click on Change button on VPN card widget
5. `Connect` string is not translated in the Russian locale

### Actual result

`Connect` string is not translated in the Russian locale
![Image](https://github.com/user-attachments/assets/7be8e398-d1a5-4e27-901b-af0b3f1cb87f)

### Expected result

`Connect` string should be translated Russian locale

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.73.101 Chromium: 131.0.6778.139 (Official Build) (64-bit)
-- | --
Revision | 45dae32a9fd5d259796f6c975ec055564fac7139
OS | Windows 10 Version 22H2 (Build 19045.5131)

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @mkarolin @rebron @brave/qa-team

**Comment by AndyAnds265** [comment]
This has been fixed! 

![Image](https://github.com/user-attachments/assets/bc1ae4ad-f03d-43c5-867e-8849ab16890d)

**Comment by AndyAnds265** [comment]
I fixed this in Transifex. So all we need to do is pull in the latest strings!

**Comment by kjozwiak** [comment]
Adding `QA/Blocked` as we'll need to wait for the `l10n` PR to be merged into `1.74.x`. Once that happens (probably January), we can run through the above/verify that it's been fixed/resolved.

**Comment by kjozwiak** [comment]
The above requires `1.73.102` or higher for `1.73.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.73.102 Chromium: 131.0.6778.139 (Официальная сборка) (64 бит)
-- | --
Версия | 6806ad35635fe0ddfd23411347211aa34c59a8d4
ОС | Windows 11 Version 24H2 (Build 26100.2314)
```

Verified the issue using STR from the description https://github.com/brave/brave-browser/issues/42824#issue-2732470731

#### Confirmed `Connect` string is translated to `Russian`

example | example | example 
----- | ----- | ----
![Image](https://github.com/user-attachments/assets/b3a801cc-a97e-419b-b4e3-e4301bd036a4)|![Image](https://github.com/user-attachments/assets/6a116ccf-236d-41b3-aeee-8cae56950a25)|![Image](https://github.com/user-attachments/assets/4c26f64c-8409-469f-8699-e843c0ad117d)
