### ISSUE TITLE
`Optimal` string on VPN card widget is not translated in few locales like French and German

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#42823]
### Description

Found while testing https://github.com/brave/brave-browser/issues/42769

`Optimal` string on VPN card widget is not translated in few locales like French and German

### Steps to reproduce

1. Set OS locale to `French` or `German`
2. Clean profile `1.73.101`
3. Connect Brave VPN 
4. Open an NTP
5. `Optimal` string on VPN card widget is not translated in few locales like French and German

### Actual result

`Optimal` string on VPN card widget is not translated in few locales like French and German

**_Connected state_**

French | German | Russia | Japanese 
--------|----------|--------|----------
![Image](https://github.com/user-attachments/assets/5d4c3bd6-0fbc-482c-92c1-33d3edeb0b7d) | ![Image](https://github.com/user-attachments/assets/b22bbfef-9b93-4972-ba88-61b074dddaf5) | ![Image](https://github.com/user-attachments/assets/347e4d5d-c2d8-4928-92b6-eef42da52efa) | ![Image](https://github.com/user-attachments/assets/340f3328-8644-4c4f-8ecb-4ca4c5d1b0bd)

### Expected result

`Optimal` string on VPN card widget should be translated to other locales like French and German

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.73.101 Chromium: 131.0.6778.139 (Official Build) (64-bit)
-- | --
Revision | 45dae32a9fd5d259796f6c975ec055564fac7139
OS | Windows 10 Version 22H2 (Build 19045.5131)

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @mkarolin @rebron @brave/qa-team

**Comment by AndyAnds265** [comment]
Hey @GeetaSarvadnya, the word Optimal in English is the same in both French and German, so this is expected in this case :)
