### ISSUE TITLE
Data stored in localStorage still accessible after clearing it

### ISSUE THREAD

**Issue by kodekvarteret-kim** [brave/brave-browser#42828]
### Description

I'm not entirely sure if this issue is actually related to Brave, but I'm making the issue here as I am only able to reproduce it in Brave.

I'm currently working on a web app in Vue 3, with authentication using bearer tokens (access token + refresh token).
The store containing the authentication data is stored in localStorage.

I have previously authenticated with the admin user of the app, and I came upon this issue when testing features with a normal user.

I experienced a JavaScript error, then made some changes to the Vue component, hard-refreshed (CMD+SHIFT+R), and suddenly I find myself authenticated as the admin user again somehow.

When debugging this, I also tried completely clearing localStorage manually by using localStorage.clear() in the browser console, but this still happens.

After further investigation I identified that the authentication data has been swapped out with previous data stored in localStorage, containing the admin user's access token and other related data.

To me it appears that Brave somehow remembers cleared localStorage data, and in a very specific situation ends up injecting it.

It only happened in Brave, and in the following condition:
- JavaScript error happened.
- I made some changes to the code, and saved, which triggers the hot reload (the reload didn't happen in the browser, due to the error).
- I refreshed using CMD+SHIFT+R to refresh without cache, and the authentication data had been swapped out with the admin user's data.

Clearing localStorage before logging in as the normal user didn't have any effect, and it still happened.

### Steps to reproduce

1. Setup a quick project with Vue 3, Pinia and pinia-plugin-persistedstate.
2. Setup a simple store containing some data.
3. Introduce a JavaScript error.
4. Clear the localStorage.
5. Hard refresh the page.

### Actual result

Localstorage data is being swapped with old data, even if the localStorage has been cleared.

### Expected result

localStorage data should not be swapped out by old data that has previously been cleared.

### Reproduces how often

Intermittent issue

### Brave version (brave://version info)

Brave: 1.73.97 Chromium: 131.0.6778.108 (Official Build) (arm64)
Revision: 7e1cc6e3239d93ac39456640abb6b6f8bc51fd39
OS: macOS Version 15.1.1 (Build 24B91)
JavaScript: V8 13.1.201.15

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by goodov** [comment]
> 4. Clear the localStorage.

How exactly did you clear the local storage? Does the issue reproduce in a new profile? Have you tried this exact scenario in Chromium?
