### ISSUE TITLE
Disable field trials

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#4283]
## Test Plan 

Specified here: https://github.com/brave/brave-browser/pull/4551

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.109 Chromium: 76.0.3809.62 (Official Build) dev (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-browser/pull/4551

![image](https://user-images.githubusercontent.com/34715963/61835363-aee58a80-ae7b-11e9-9890-a823798ea7a0.png)
