### ISSUE TITLE
[AI Chat]: We should add a setting for disabling/enabling AI Chat History on Android

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#42847]

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 15 running 1.75.171 x64 build
- Verified steps from [brave/brave-core#26988](https://github.com/brave/brave-core/pull/26988)
- Verified `brave://flags/#brave-ai-chat-history` is enabled by default
- Verified with setting enabled, `Store my conversation history` option is shown and enabled by default
- Verified disabling `Store my conversation history`  can be turned off and conversation history is not stored
- Encountered [#43622](https://github.com/brave/brave-browser/issues/43622)

https://github.com/user-attachments/assets/33525f0d-ecc9-496c-a916-715be8beab91
