### ISSUE TITLE
Brave Shields "Trackers & ads blocking" blocking my input type=checkbox

### ISSUE THREAD

**Issue by Chammar37** [brave/brave-browser#42846]
I have a very simple line of code that is being blocked by brave shields, specifically the "Trackers & ads blocking". I'm not sure why this would be considered a tracker or ad blocker. 

`<input id="policyConsent" type="checkbox" required >`

Is there a Brave best practice that tells Brave that this code is not malicious and shouldn't be blocked? I'm sure someone else has come across this issue, please let me know if I have missed an discussion/solution somewhere. Any help is appreciated.

With Shield On:
![Image](https://github.com/user-attachments/assets/52e5c27b-3234-4e8d-990d-8b1a230065af)

With Shield Off:
![Image](https://github.com/user-attachments/assets/aa04551a-4891-44c0-9712-7dcc603981df)

**Comment by bsclifton** [comment]
cc: @ryanbr

**Comment by Saoiray** [comment]
Already helping on Brave Community. Element is being blocked due to EasyList Cookie. https://community.brave.com/t/brave-shields-blocking-my-checkbox-input-html-tag/586214/

**Comment by Chammar37** [comment]
Be sure your div id names are not regex matching any of these... https://github.com/uBlockOrigin/uAssets/blob/master/thirdparties/easylist/easylist-cookies.txt

**Comment by Chammar37** [comment]
Be sure your div id names are not regex matching any of these... https://github.com/uBlockOrigin/uAssets/blob/master/thirdparties/easylist/easylist-cookies.txt
