### ISSUE TITLE
AI Chat omnibox entry should open full page

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#42844]
## With setting enabled 
1. Enable full page storage
2. Type "what is an emoji" in omnibox
3. Select the Leo suggestion

Observe the prompt opens in full page Leo

## With setting disabled
1. Disable full page storage
2. Type "what is an emoji" in omnibox
3. Select the Leo suggestion

Observe the prompt opens in sidebar Leo

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.166 Chromium: 132.0.6834.111 (Official Build) beta (64-bit)
-- | --
Revision | 0c5da0a4df158be9400ac84df9312b627cc4dec0
OS | Windows 11 Version 24H2 (Build 26100.2894)

- Verified steps from issue description
- Verified with `Store my conversation history` enabled, selecting `Ask Leo` from omnibar opens Leo in full page view
- Verified with `Store my conversation history` disabled, selecting `Ask Leo` from omnibar opens Leo in sidebar view

https://github.com/user-attachments/assets/90277765-7e9e-4368-a586-f6d4808300dd

-----------
Verification passed on

Brave | 1.75.166 Chromium: 132.0.6834.111 (Official Build) beta (64-bit)
-- | --
Revision | 0c5da0a4df158be9400ac84df9312b627cc4dec0
OS | Linux

- Verified steps from issue description
- Verified with `Store my conversation history` enabled, selecting `Ask Leo` from omnibar opens Leo in full page view
- Verified with `Store my conversation history` disabled, selecting `Ask Leo` from omnibar opens Leo in sidebar view

https://github.com/user-attachments/assets/e2f197a6-6ef7-4542-8939-0c98db2b827f

-----------
Verification passed on

Brave | 1.75.164 Chromium: 132.0.6834.83 (Official Build) beta (arm64)
-- | --
Revision | befbba8d7568f8713d6f942f9a7350c59b57f20a
OS | macOS Version 15.2 (Build 24C101)

- Verified steps from issue description
- Verified with `Store my conversation history` enabled, selecting `Ask Leo` from omnibar opens Leo in full page view
- Verified with `Store my conversation history` disabled, selecting `Ask Leo` from omnibar opens Leo in sidebar view

https://github.com/user-attachments/assets/607e96eb-90e0-4ba3-b38c-e58aeb9a7070
