### ISSUE TITLE
[iOS] - Remove WindowRenderScript from iOS for Youtube bug that no longer exists

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#42849]
### Description

- Window Render Script fixed a bug on Youtube with rotation that no longer exists
- Window Render Script now causes an issue with Manulife which thinks it's okay to reload the page whenever it's resized (bad code).
- Old issue: https://github.com/brave/brave-ios/pull/1257

### Steps to reproduce

1. Visit: `https://www.manulife.ca/personal.html
2. Infinite reload

### Actual result

- The page reloads indefinitely

### Expected result

- The page should not reload indefinitely

### Reproduces how often

Easily reproduced

### Brave version

- All

### Device/iOS version

- All

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` & `iPad (7th Gen)` running `iOS 18.2` & `iPadOS 17.5.1` respectively using version `1.75 (142)`

* Ensured that loading https://www.manulife.ca/personal.html is successful.
* Ensured changing `Trackers & Ads Blocking` to aggressive mode and reloading the page is successful.
* Ensured that reloading / navigating the site does not cause issues. 
* Ensured loading in both orientations is successful.

example | example
---|---
<img width="450" src="https://github.com/user-attachments/assets/af936601-bb19-4da2-ba46-49316dacbad6"> | <img width="250" src="https://github.com/user-attachments/assets/d1a89904-c4f1-4451-bd6d-ad9db9ba3be5">
