### ISSUE TITLE
Enable AI Chat History feature by default

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#42854]
Android and Desktop are ready to have the feature enabled by default

## Test plan
Ensure the `AIChatHistory` feature flag is enabled

**Comment by diracdeltas** [comment]
Noting Android should not have it enabled by default until all privacy review issues are addressed. (They are on desktop)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.75.166 Chromium: 132.0.6834.111 (Official Build) beta (64-bit)
-- | --
Revision | 0c5da0a4df158be9400ac84df9312b627cc4dec0
OS | Windows 11 Version 24H2 (Build 26100.2894)

- Verified steps from issue description
- Verified `Brave AI Chat History` flag is enabled by default

<img width="966" alt="Image" src="https://github.com/user-attachments/assets/1ce6df67-1209-4ee6-af7c-36dfdee65832" />

-------------

Verification passed on 

Brave | 1.75.166 Chromium: 132.0.6834.111 (Official Build) beta (64-bit)
-- | --
Revision | 0c5da0a4df158be9400ac84df9312b627cc4dec0
OS | Linux

- Verified steps from issue description
- Verified `Brave AI Chat History` flag is enabled by default

<img width="1920" alt="Image" src="https://github.com/user-attachments/assets/c8af42e1-327c-4975-838e-3763fea1823c" />

-------------

Verification passed on 

Brave | 1.75.164 Chromium: 132.0.6834.83 (Official Build) beta (arm64) 
-- | --
Revision | befbba8d7568f8713d6f942f9a7350c59b57f20a
OS | macOS Version 15.2 (Build 24C101)

- Verified steps from issue description
- Verified `Brave AI Chat History` flag is enabled by default

![Image](https://github.com/user-attachments/assets/6ff62178-acd7-42cc-a17a-f4ced6bf4770)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.75.171 x64 build
- Verified steps from issue description
- Verified `Brave AI Chat History` flag is enabled by default

Google Pixel 8 (Android 15) | Lenovo Tab (Android 13)
-- | --
<img width=300 src=https://github.com/user-attachments/assets/b41c011a-72eb-4289-bebc-c59eff551678> | <img width=400 src=https://github.com/user-attachments/assets/3f316488-8927-4fb5-bed5-9394b6f4ff53>
