### ISSUE TITLE
Leo is broken on Android

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#42859]
### Description

Leo is broken on Android

### Steps to reproduce

1. Install 1.75.93 
2. Open Leo from menu
3. Doesn't show Leo onboarding or conversation screen

### Actual result

https://github.com/user-attachments/assets/226e6bc7-caa5-4fff-a228-7b8a1bab042c

### Expected result

Leo should work

### Reproduces how often

Easily reproduced

### Brave version

1.75.93 x64 Nightly build

### Device

- Brand/model: Google Pixel 8
- Android version: 15

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @SergeyZhukovsky @petemill @mattmcalister @kjozwiak

**Comment by petemill** [comment]
Note this is only broken if AIChatHistory feature flag is disabled (which is currently the default for android)

**Comment by fallaciousreasoning** [comment]
Marked as QA/No as this will be tested as part of the other issues
