### ISSUE TITLE
[Bug]: "Tab Scrolling" flag breaks vertical tabs

### ISSUE THREAD

**Issue by Lerroxy** [brave/brave-browser#42855]
### Description

Enabling "Tab scrolling" flag (which is made solely for the horizontal tabs) breaks vertical tabs in many different ways, including crashing the browser entirely. Realistically, this affects only people who use both vertical and horizontal tabs and also use the experimental features from brave://flags/ , so it doesn't seem like the bug would be noticed by many, but that's a bug nonetheless. I would be glad if it gets fixed soon, as I like to use both vertical and horizontal tabs depending on the situation, and having "Tab Scrolling" enabled is a must for me, as the work I do sometimes requires me to have up to hundreds of open tabs amongst tens of groups.

### Steps to reproduce

1. Open Brave Browser
2. Go to brave://flags/
3. Enable "Tab Scrolling" (tested with "Enabled - tabs shrink with medium width")
4. Right click a tab and enable vertical tabs by clicking "Use vertical tabs"
5. Check if the vertical tabs panel is displayed correctly and doesn't have a stretched shade to the right of it, indicating that the panel can be scrolled like when having too many open tabs to fit the screen with horizontal tabs
6. Check if the tabs are displayed correctly. An icon of each tab, name and X button of the opened tab can be seen on screen at all times.
7. If the tabs are not displayed or are displayed incorrectly - minimize and then expand tabs with a dedicated "minimize tabs" on top of the vertical tabs panel
8. Open new tabs until they no longer fit the screen without scrolling
9. Check if scrolling functionality works
10. Right click a tab and disable vertical tabs by clicking "Use vertical tabs"

### Actual result

- The vertical tabs panel displays a stretched shade to the right of it, indicating that the panel can be scrolled like when having too many open tabs to fit the screen with horizontal tabs
- The tabs are too long and don't fit the sidebar dedicated for them
- The tabs cannot be scrolled
- The browser crashes when trying to exit vertical tabs

### Expected result

Vertical tabs functionality works correctly:
- The vertical tabs panel doesn't display a stretched shade to the right of it
- The tabs fit the screen
- The tabs can be scrolled
- The browser doesn't crash when trying to exit vertical tabs

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.73.97 Chromium: 131.0.6778.108 (Official Build) (x86_64)
Revision | 7e1cc6e3239d93ac39456640abb6b6f8bc51fd39
OS | macOS Version 12.7.6 (Build 21H1320)

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

No other flag is enabled
It seems like an easy fix would be to disable the "Tab Scrolling" functionality once vertical tabs are enabled

**Comment by simonhong** [comment]
Thanks for reporting - let's track this issue with https://github.com/brave/brave-browser/issues/40953.
