### ISSUE TITLE
AI Chat storage notice should dismiss only after the first prompt is sent

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#42853]
(or the close button is pressed)

### From a query
0. Fresh profile (or freshly upgraded to the storage flag being unflagged)
1. Open AI Chat panel (or full-page)
2. Observe the storage notice shows
3. Submit a query to Leo
4. Observe the storage notice disappears
5. Close and re-open Leo
6. Observe the storage notice is still not there

### From the close button
0. Fresh profile (or freshly upgraded to the storage flag being unflagged)
1. Open AI Chat panel (or full-page)
2. Observe the storage notice shows
3. Hit the close button
4. Observe the storage notice disappears
5. Close and re-open Leo
6. Observe the storage notice is still not there

**Comment by hffvld** [comment]
Verified on `Galaxy Z Fold 6` using version(s):
```
Device/OS: Galaxy Z Fold 6 / q6quew-user 14 UP1A.231005.007 release-keys
Brave build: 1.75.159
Chromium: 132.0.6834.83 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/42853#issue-2734922133
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Conversation history` storage notice is shown when launching Leo for the first time.
- Verified that the `Conversation history` storage notice is not automatically removed when closing Leo or relaunching Brave if no queries were sent to Leo previously.
- Verified that the `Conversation history` storage notice is removed and not shown anymore after the first query is sent to Leo.
- Verified that the `Conversation history` storage notice is removed and not shown anymore after tapping the `x` button on the storage notice.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/e4b1fd28-0009-48f6-8437-f7079c933a42) | ![2](https://github.com/user-attachments/assets/96ca0497-7c9b-45f5-9029-08b88f3587be) | ![3](https://github.com/user-attachments/assets/6b03442f-9ac7-40de-a81a-15b5cbf5ee7f) |
| ![1](https://github.com/user-attachments/assets/956b1c8f-db81-4dd4-bd82-dcefec274a00) | ![2](https://github.com/user-attachments/assets/4e3d153f-a1eb-407b-b146-616aaebbd9a3) | ![3](https://github.com/user-attachments/assets/4dfb1c1e-0a95-4b6e-b645-6b2a9325d100) |

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.164 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | befbba8d7568f8713d6f942f9a7350c59b57f20a
OS | Windows 11 Version 24H2 (Build 26100.2894)

- Verified steps from issue description
- Verified storage notification is dismissed when a query is posted
- Verified relaunching browser with the query doesn't show the message again
- Verified on clean profile closing the storage notification and restarting browser doesn't show the message again
- Verified reset conversation history via `brave://settings/leo-ai` doesn't show the message again

<video src=https://github.com/user-attachments/assets/48871028-22ad-4498-bc4e-41b056d55273> | <video src=https://github.com/user-attachments/assets/f8c7f84f-c21b-4389-98d4-6061296f76ba>
-- | --
