### ISSUE TITLE
Default Screenshot Shortcut Should Use CMD, not CTRL

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#42850]
### Description

The screenshot shortcut should use the platform accelerator key, which on macOS is <kbd>CMD</kbd>.

### Steps to reproduce

1. Press CMD+Shift+S on macOS

### Actual result

Nothing.

### Expected result

The user should be presented with the screenshot interface.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.75.86

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.75.159 Chromium: 132.0.6834.83 (Official Build) beta (arm64)
-- | --
Revision | a7b6f5093a2dad31fc3f56241a7d55be255e69e2
OS | macOS Version 14.6.1 (Build 23G93)
```


Reproduced the issue in 1.74.x 

Confirmed when pressed  `Cmd+Shift+S`, user is presented with the screenshot interface, cursor is changed to crosshairs.  Able to drag to to take the screenshot.



![Image](https://github.com/user-attachments/assets/be039494-be7f-4bdd-abc2-45d51c1bc706)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.75.174 Chromium: 133.0.6943.54 (Official Build) (x86_64)
-- | --
Revision | 097c41c8fd0150d3cc2f6e6500ed21ed26c430b8
OS | macOS Version 14.7.3 (Build 23H417)
```
