### ISSUE TITLE
[Android] Update onboarding with new flag

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#42863]
As a follow up to day zero A/B testing with new onboarding changes, 
In this issue we need to remove the changes for onboarding which was relying on day zero flag and update onboarding changes to use new flag `NewAndroidOnboarding` flag. 

We also removed the study for day zero flag here : https://github.com/brave/brave-variations/pull/1279
We have a new study with a new flag `NewAndroidOnboarding` here : https://github.com/brave/brave-variations/pull/1282

**Comment by kjozwiak** [comment]
The above requires `1.73.104` or higher for `1.73.x` verification 👍 @Uni-verse @hffvld can use https://github.com/brave/brave-core/pull/26999#issuecomment-2552651765 as a template for `1.73.x` verification.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.73.104 Chromium: 131.0.6778.204 (Official Build) (64-bit) 
Revision	215b794a7c1f3e28151d0f7712e32c71be48775c
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

* Enabled the following flag using CLI before launching Brave:

   ![Image](https://github.com/user-attachments/assets/b7aadd35-667e-44b1-885c-5a89ae7331b9)
   ![Image](https://github.com/user-attachments/assets/af7c6dc3-42e1-4cd6-ba25-5a1ca3cc73ee)

 - Ensured that the new onboarding is being used.
 - Ensured that there's no Notification system permission modal when Brave first launches
 - Ensured that the default browser system modal appears
 - Ensured that the P3A/Data onboarding card is still being displayed

Also ensured the following: 
 - Ensured that SINTP are being displayed/appearing without any issues
 - Ensured that Rewards icon is still being displayed and the user can opt-in into rewards
 - Ensured that Brave News opt-in card is being displayed via NTP
 - Ensured that Brave Wallet appears within the Hamburger Menu and is selectable/working without any issues


 * Ensured that once `adb shell "rm /data/local/tmp/brave-test-day-zero-expt"`, the old onboarding is being launched/working as per the following:

example | example | example | example | example
---|---|---|---|---
<img width="200" src="https://github.com/user-attachments/assets/a8a4458d-6220-4b86-94ee-a55ae90a01f8"> | <img width="200" src="https://github.com/user-attachments/assets/e366ba76-6a50-4851-9240-2fd5bfcdb92e"> | <img width="200" src="https://github.com/user-attachments/assets/183e7856-471e-496f-b509-bb9ddbbe1486"> | <img width="200" src="https://github.com/user-attachments/assets/19e2a2b0-dee8-4445-ac44-2cee27de94f0"> | <img width="200" src="https://github.com/user-attachments/assets/0ddd527c-7103-4a6e-b65f-c61a4bdc6dc8">
