### ISSUE TITLE
Remove animation for Open YT dialog

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#42864]
In this issue, we need to remove lottie animation and replace it with an svg image.

**Comment by hffvld** [comment]
Verified on `Galaxy Z Fold 6` using version(s):
```
Device/OS: Galaxy Z Fold 6 / q6quew-user 14 UP1A.231005.007 release-keys
Brave build: 1.75.111
Chromium: 132.0.6834.46 (Official Build) canary (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/26595#issue-2663292654
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `animation` is removed from the `YT` modal and replaced with the static `SVG image`.
- Verified that tapping `Turn on now` opens the `YT` website and `Open YouTube links in Brave` toggle switch in `Settings` > `Media` got enabled.
- Verified that tapping `No, thank you`  doesn't open the `YT` website and `Open YouTube links in Brave` toggle switch in `Settings` > `Media` is not enabled.

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/b552f39b-9c3e-4ddd-ae1c-84e0ed6a4434) | ![2](https://github.com/user-attachments/assets/8e965605-6065-4b53-9ca6-f3190ef3d5bc) |

https://github.com/user-attachments/assets/09ccc73e-b5b2-45e0-82a2-29b3ee3ba3de
