### ISSUE TITLE
Links shared with Brave are opening in normal browsing mode when "Private Browsing Only" option is enabled and Brave is starting from closed.

### ISSUE THREAD

**Issue by farisjarrah** [brave/brave-browser#42869]
### Description

Brave Browser for iOS is opening links in a non-private browser session  when brave is closed and links are opened from other apps. I have "Private Browsing Only" option enabled in brave settings. The behavior only started after the last Brave iOS update. When the link is opened in a non-private browser window, history can be retained if you do not have the "shred" option enabled.

### Steps to reproduce

1. Ensure brave has "Private Browsing Only" option enabled in iOS App
2. Ensure brave is set to default browser in iOS settings
3. Close the brave application all the way on iOS
4. Open another app like NetNewsWire
5. Open link
6. Brave opens link in non-private browser window, and history is present.

Attached screen recording of behavior:
https://github.com/user-attachments/assets/46ba4c53-31d4-40d9-a5ae-816752970398

### Actual result

Brave opens a link in a normal browser session with history enabled.

### Expected result

Brave should open all links in a private browser window.

### Reproduces how often

Easily reproduced

### Brave version

1.73

### Device/iOS version

iphone 12 pro max, iOS 18.1.1

### Affected browser versions

- [x] latest AppStore
- [ ] latest TestFlight
- [ ] previous TestFlight

### Reproducibility

- [x] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by farisjarrah** [comment]
Not sure if that mp4 is able to render in Github, let me try converting it to a gif

![Image](https://github.com/user-attachments/assets/6a357830-e974-49de-b3a6-987ef50f5860)

**Comment by jamesmudgett** [comment]
https://github.com/brave/brave-core/pull/26931
