### ISSUE TITLE
Request Desktop Site is always disabled on the new menu UI

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#42875]
When using the new menu UI (feature flag `brave-use-modern-browser-menu`), the "Request Desktop Site" action is always disabled regardless of if you're on the NTP or a webpage

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.2` using version `1.75 (105)`

Flag: `brave://flags#brave-use-modern-browser-menu` (needs restart)

* Ensured that `Request Desktop Site` action is enabled when loading a webpage on mobile device. 
* Ensured that request desktop site is working from the menu and also `my actions` menu with the correct icon displayed.
* Ensured that `Request Desktop Site` has not regressed with original/old menu.

contextual menu | request mobile site | in 'my actions' | original menu
---|---|---|---
<img width="250" src="https://github.com/user-attachments/assets/d6b274b9-900e-4775-a121-ff372b71c02a"> | <img width="250" src="https://github.com/user-attachments/assets/98137d7c-45cc-48bd-9f39-de7e124e7215"> | <img width="250" src="https://github.com/user-attachments/assets/bde668e3-905e-41cd-a10b-d62b6bddfd56"> | <img width="250" src="https://github.com/user-attachments/assets/b612aa61-b880-4f36-b77a-e5cc5f736771">

**Comment by hffvld** [comment]
Verified on `iPad Mini (6th gen)` using version(s):
```
Device/OS: iPad Mini (6th gen) / iPadOS 18.2.1
Brave build: 1.75 (164)
BraveCore: 1.75.164 (132.0.6834.83)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/27007#issue-2737133826
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Request Mobile Site` action is shown by `default` when loading a webpage on `iPad`.
- Verified that `Request Mobile Site`/`Request Desktop Site` works from the `Main menu` and `My actions menu` with the correct icon displayed.
- Verified that the new menu UI is turned on by `default` in `Beta`.

---------------------------

|`Request Mobile Site`|`Request Desktop Site`|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/50ee36b8-fda6-4f4f-a539-b3574a1bd23f) | ![2](https://github.com/user-attachments/assets/581e0023-b8ba-42c3-9e00-91d9ca1d56ca) |
| ![1](https://github.com/user-attachments/assets/a9afe5f4-3d70-4078-8553-fd1985057a25) | ![2](https://github.com/user-attachments/assets/5d3eae36-7501-41c7-a392-bd296bf711ae) |
