### ISSUE TITLE
AI Chat copy message from clipboard not working

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#42872]
This is due to iframe introduction

1. Generate an AI Chat response
2. Hit the copy button on the repsonse

Expected: pasting it somewhere else pasted the response
Actual: the response was never copied to the clipboard because the frame didn't have permission to copy

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.164 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | befbba8d7568f8713d6f942f9a7350c59b57f20a
OS | Windows 11 Version 24H2 (Build 26100.2894)

- Verified steps from issue description
- Verified Chat copy message from clipboard work as expected
- Verified copy message works on both prompt and response

https://github.com/user-attachments/assets/50d50dbc-b82f-4021-b1f1-c82f74e38f88
