### ISSUE TITLE
Add Base to preloaded EVM networks

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#42885]
### Description

.

### Steps to reproduce

N/A

### Actual result

N/A

### Expected result

1. Base is listed as a preloaded network in Settings > Web3 > Wallet Networks
2. Base balances are displayed in the wallet Portfolio

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

N/A

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.45 Chromium: 132.0.6834.57 (Official Build) beta (64-bit)
-- | --
Revision | b8c4625f59984c01cb763d30442350dec7f727cf
OS | Windows 11 Version 23H2 (Build 22631.4602)

- Verified steps from issue description
- Verified Aurora is removed from default network list on a clean profile
- Verified if Aurora is set as default its retained as the the default network post upgrade
- Verified if Aurora is not set as default it is removed from the list of default network
- Verified Base is added as a default network on both clean and upgrade 

https://github.com/user-attachments/assets/a4a4359e-efa0-4383-880c-f4fe31d682db
