### ISSUE TITLE
Remove Aurora from preloaded EVM networks

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#42884]
### Description

We want to drop Aurora from the preloaded EVM network list to prevent the number preloaded chains from adversely impacting wallet performance.

### Steps to reproduce

N/A

### Actual result

Aurora network is visible in Settings > Web3 > Wallet Networks.

### Expected result

Aurora network should not be visible in Settings > Web3 > Wallet Networks.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

N/A

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.45 Chromium: 132.0.6834.57 (Official Build) beta (64-bit)
-- | --
Revision | b8c4625f59984c01cb763d30442350dec7f727cf
OS | Windows 11 Version 23H2 (Build 22631.4602)

- Verified steps from issue description
- Verified Aurora is removed from default network list on a clean profile
- Verified if Aurora is set as default its retained as the the default network post upgrade
- Verified if Aurora is not set as default it is removed from the list of default network
- Verified Base is added as a default network on both clean and upgrade 

https://github.com/user-attachments/assets/59f8d49e-cf2a-481d-bdab-3c91b0afd2f0
