### ISSUE TITLE
Cayman Airways online check-in page doesn't work with Shields

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#4288]
## Description

Cayman Airways online check-in page doesn't work with Shields enabled.

## Steps to Reproduce

   1. Go to https://dx.checkin.caymanairways.com/dx/KXCI/
   2. Enter confirmation number and last name.
   3. Click "Search".

## Actual result:

Clicking "Search" clears the form.

## Expected result:

Clicking "Search" should take me to the check-in interface.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

Brave | 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?

Yes, only "ads and trackers" needs to be disabled.

Here are the blocked resources:
- `https://www.googletagmanager.com/gtm.js?id=GTM-NJ9FTD5`
- `https://assets.adobedtm.com/d8fa8fa49b406106290f6b4c580f81ee0c3c443e/satelliteLib-3c979e5ff1e9c2902705700a13a94175e8bda6cc.js`
- `https://dx.checkin.caymanairways.com/dx/KXCI/2.0.195-184-3.Updateheaders_KX_ERS0/images/beacon.gif?accessToken=...`
- `https://cp-2sg.as.havail.sabre.com/v2.2/dcci/passenger/details?jipcc=KXCI`

**Comment by ryanbr** [comment]
Okay, is this still an issue? If so, whats the field data i need to fill in?

**Comment by ryanbr** [comment]
Re-checked this @fmarier . Still an issue? Had no issues searching

**Comment by fmarier** [comment]
I would need a flight on Cayman Airways to reproduce again :)

Maybe @w0ts0n or @mrose17 can confirm next time they fly out.

**Comment by mrose17** [comment]
Sadly, I cancelled my Friday flight to Miami yesterday… The next time I book a flight, I will endeavor to remember…

Tropical Regards,

/mtr

**Comment by ryanbr** [comment]
I re-test this, searching seems fine. Tested searching for bookings, and checkin searches. Without actually purchasing a ticket.

 We could re-open ticket if it's still an issue with the latest Brave version.
