### ISSUE TITLE
Allow Brave Talk to use microphone when Brave is backgrounded

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#42897]
Microphone turns off when Brave is backgrounded and there is a meeting using Brave Talk. We need to allow microphone usage in that case.

STR:
- Join a meeting using Brave Talk
- Allow microphone usage
- Background Brave or lock your device
- Observe that microphone turn off.

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 BP11.241025.006 release-keys
Brave build: 1.75.106
Chromium: 132.0.6834.46 (Official Build) canary (64-bit)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/42897#issue-2738959337
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Mic` stays enabled when Brave is backgrounded or when a device is locked.

---------------------------

https://github.com/user-attachments/assets/6d998dc6-09be-4cd2-ab8e-27cad4352243

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` using version(s):
```
Device/OS: Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
Brave build: 1.75.161
Chromium: 132.0.6834.83 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/42897#issue-2738959337
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Mic` stays enabled when Brave is backgrounded or when a device is locked.

---------------------------

https://github.com/user-attachments/assets/80e969c8-3b75-44c3-ab6a-8e56f4f4a68f
