### ISSUE TITLE
AI Chat full page conversation list items should not activate when opening menu

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#42893]
Ideally, the conversation list menu item shouldn't activate when opening the `...` menu for the conversation after hovering it.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.159 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | a7b6f5093a2dad31fc3f56241a7d55be255e69e2
OS | Windows 11 Version 23H2 (Build 22631.4602)

- Verified steps from issue description
- Verified conversation menu is not opened when hovered over and opens only when clicked

https://github.com/user-attachments/assets/cdbb2b2e-b9ea-4fe7-b3e9-02f8be9b32dc
