### ISSUE TITLE
`Windows 10 SDK` header in Wiki says to `Install Windows 11 SDK 10.0.22621.0`

### ISSUE THREAD

**Issue by hamirmahal** [brave/brave-browser#42899]
[The `Windows 10 SDK` header in the Wiki](https://github.com/brave/brave-browser/wiki/Windows-Development-Environment#windows-10-sdk) says to `Install Windows 11 SDK 10.0.22621.0`.

Is that a typo? Should developers only install the Windows 11 SDK if they're on Windows 11, or even if they're on Windows 10?

I think clarifying this in the Wiki would help potential contributors.

**Comment by hamirmahal** [comment]
Actually, where is the source code for the wiki, and is it open to outside contributions?

**Comment by bsclifton** [comment]
Hi - yes, this is the Windows 11 SDK which covers multiple operating systems. 

I'll update the wiki to mention that. For more info, please see https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/
