### ISSUE TITLE
SafeBrowsing download checks need to be proxied through Brave proxy

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#4289]
Discovered in https://hackerone.com/bugs?subject=brave&report_id=561250. No direct connections should be made to Google.

Test plan:
Open Brave Browser and wireshark or another similar tool.
Download https://download-installer.cdn.mozilla.net/pub/firefox/releases/66.0.3/win32/en-US/Firefox%20Installer.exe (or any other exe files
After the download completes, you can see a DNS request for sb-ssl.google.com, and a TLS 1.3 request to https://sb-ssl.google.com.

Expected behavior: No connections should be made to google

**Comment by jumde** [comment]
Follow up issue: https://github.com/brave/brave-browser/issues/4290

**Comment by diracdeltas** [comment]
going to rename this issue per https://bravesoftware.slack.com/archives/C85NV6NSG/p1557176576049400?thread_ts=1557174991.034600&cid=C85NV6NSG

**Comment by diracdeltas** [comment]
closing because of https://github.com/brave/brave-browser/issues/4328
