### ISSUE TITLE
Styling regressed for speedreader controls in dark mode

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#42895]
### Description

The border/outline for speedreader controls are missing in dark mode due to an update to improve contrast with the dark mode theme overall. 
See actual vs expected result

### Steps to reproduce

1. Use 1.75.98 and use dark mode as the browser theme.
2. Go to any website with articles that trigger reader mode e.g. NYTimes or CNN.com 
3. Enter reader mode for the article and select appearance settings or text to speech to show settings/control bar.

### Actual result

<img width="908" alt="Image" src="https://github.com/user-attachments/assets/275b7b3b-2608-41e6-8447-8b3d7fa01bc4" />
<img width="895" alt="Image" src="https://github.com/user-attachments/assets/b0d7c3e4-760e-4e47-8829-4d339920ac11" />

### Expected result

<img width="906" alt="Image" src="https://github.com/user-attachments/assets/65b44373-d2c8-4869-850e-ec075286b929" />
<img width="916" alt="Image" src="https://github.com/user-attachments/assets/22619099-ccc6-4995-a482-1a50d209d290" />

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.75.x

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by aguscruiz** [comment]
I think the issue would be resolved (and future proofed) if we changed all the colors we're using for this into the corresponding Nala tokens that are set up on the design.

The most noticeable one seems to be the outlines for the buttons, but I can see this becoming an issue again if we need to adjust contrast in the main chrome UI again. 

Migrating the colors to Nala tokens will solve that automatically if we ever do change. It'll also make them themable, which is a win for us when users set up a color theme.

https://www.figma.com/design/YHMNRL2XpZDOUe6n1Dw6K1/Reader-mode?node-id=2001-50404

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.75.159 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | a7b6f5093a2dad31fc3f56241a7d55be255e69e2
OS | Windows 11 Version 24H2 (Build 26100.2605)
```

Reproduced the issue in `1.75.98` using STR from the description 

1. Installed 1.75.x
2. launched Brave
3. selected Dark mode via brave://settings/appearance
4. opened nytimes.com in a new tab
5. pressed Speedreader icon in the URL bar
6. pressed `Appearance settings` icon in the `Speedreader` toolbar
7. pressed `Text to speech` icon in the `Speedreader` toolbar

Confirmed the border around Speedreader controls for both `Appearance settings` & `Text to speech` settings

1.75.98 | 1.75.159 
----- | ------
![Image](https://github.com/user-attachments/assets/dd944627-57dd-4263-b5a1-f16c37a258fb)|![Image](https://github.com/user-attachments/assets/424e7bdd-794a-4339-a3e7-8045aec7ed1d)
![Image](https://github.com/user-attachments/assets/4f732375-e137-40f5-bb3b-f6fcb948f676)|![Image](https://github.com/user-attachments/assets/0e59274d-cdc7-40ac-8caa-9f4b2f87232d)
