### ISSUE TITLE
Shields shows incorrect blocked items when visiting anew site in the same tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#429]
## Description 

Shields shows incorrect blocked items when visiting anew site in the same tab

## Steps to Reproduce
   1. Visit icloud.com in a new tab and change to `Block all fingerprinting`
   2. See blocked count in shields
   3. Visit nytimes.com in the same tab
   4. Ensure there are no fingerprint blocked items
   5. Click on 0 Fingerprint blocked,. shows icloud items that are blocked

## Actual result:

![incorrect shields](https://user-images.githubusercontent.com/17010094/41915473-cf7ecd94-7923-11e8-90f9-b64421375c49.gif)

## Expected result:
Should only show items blocked for the current domain not from previous site visited on the same tab

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Packaged build

### Reproducible on current release: 

No

### Website problems only:  
- Does the issue gets fixed with Brave Shields disabled? 
- Does the issue reproduces on Chrome?

**Comment by GeetaSarvadnya** [comment]
Re-validated the issue against the latest build ""Version 0.54.2 Chromium: 69.0.3497.42 (Official Build) dev (64-bit)". Issue still persists hence reopening the issue.
![issue 429](https://user-images.githubusercontent.com/38657976/44723337-5122b400-aaed-11e8-9051-731358475914.gif)

**Comment by cezaraugusto** [comment]
self-note seems like a race condition. both resources and stats are reset in the `ON_BEFORE_NAVIGATION` event. commit added by myself in https://github.com/brave/brave-extension/commit/c8edd0f82f8dcad59e1475907aeea981c5794eea

**Comment by cezaraugusto** [comment]
worth check if creating an `ON_COMMITTED` action is best to host resources reset as it is the next event after `ON_BEFORE_NAVIGATION` and just before `onDOMContentLoaded` is fired which is when blocked resources start to show

**Comment by cezaraugusto** [comment]
this issue matches https://github.com/brave/brave-browser/issues/429#issuecomment-416567979 but not the original issue description which was partially addressed. 

worth noticing that both stats and resource blocked are not updated which indicates that maybe `ON_BEFORE_NAVIGATION` is happening too soon and other events might overlap it and skip stat/resource reset
