### ISSUE TITLE
AI Chat should show conversation title in tab title

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#42916]
When the conversation has a title, AI Chat should set it as the page / tab title

1. Open brave://leo-ai
2. Observe the page title is "Leo AI - New conversation"
3. Create a conversation, e.g. "write a short star trek joke"
4. Wait for the response
5. Observer the page title is "Leo AI - [title of the conversation]

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.162 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | 1c01fd7f190ad7c9c88cb964f55e35400bf399ae
OS | Linux

- Verified steps from issue description
- Verified AI Chat shows `New conversation` in title when opening `brave://leo-ai` for the first time
- Verified title updates based on search/query
- Verified summarising a page updates the title to the article title

https://github.com/user-attachments/assets/6b904f87-fe99-4fd5-bbc2-f8ea8073d8ba

------
Verification passed on 

Brave | 1.75.166 Chromium: 132.0.6834.111 (Official Build) beta (64-bit)
-- | --
Revision | 0c5da0a4df158be9400ac84df9312b627cc4dec0
OS | Windows 11 Version 24H2 (Build 26100.2894)


- Verified steps from issue description
- Verified AI Chat shows `New conversation` in title when opening `brave://leo-ai` for the first time
- Verified title updates based on search/query
- Verified summarising a page updates the title to the article title

https://github.com/user-attachments/assets/1b367fe7-6f83-4c40-b2fe-04f2cd7f4e95

------
Verification passed on 

Brave | 1.75.164 Chromium: 132.0.6834.83 (Official Build) beta (arm64)
-- | --
Revision | befbba8d7568f8713d6f942f9a7350c59b57f20a
OS | macOS Version 15.2 (Build 24C101)

- Verified steps from issue description
- Verified AI Chat shows `New conversation` in title when opening `brave://leo-ai` for the first time
- Verified title updates based on search/query
- Verified summarising a page updates the title to the article title

https://github.com/user-attachments/assets/b0be2c86-edb9-41ea-963f-858dd90659f0

**Comment by michaelchiche** [comment]
this does not work on my version on brave...

`Version 1.76.73 Chromium: 134.0.6998.45 (Official Build) (arm64)`
