### ISSUE TITLE
Leo AI favicon should be full-color in light theme

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#42915]
In light theme, chromium uses grayscale for all WebUI favicons. We override this for some WebUI (e.g. Rewards and Wallet) but not for Leo. We should.

1. Set browser / OS theme to "light"
2. Open brave://leo-ai
3. Observe Tab's favicon

Expected: Colorful
<img width="345" alt="Image" src="https://github.com/user-attachments/assets/808f7da6-a0de-46c8-83fc-33b95f3016c9" />

Actual: Grayscale
<img width="508" alt="Image" src="https://github.com/user-attachments/assets/6dcefa3b-ef7d-4462-87d5-0b8f1b3615bd" />

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.75.162 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | 1c01fd7f190ad7c9c88cb964f55e35400bf399ae
OS | Linux

- Verified steps from issue description
- Verified Leo AI Favicon is shown in colour on both Light and Dark theme
  
Light | Dark
-- | --
<img width="725" alt="Image" src="https://github.com/user-attachments/assets/dd4d0079-6cd5-49ed-ba6d-5146f2b36ad4" /> |<img width="719" alt="Image" src="https://github.com/user-attachments/assets/359b7976-c314-4686-bdf9-69fd65cc8550" />

--------------

Verification passed on 

Brave | 1.75.162 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | 1c01fd7f190ad7c9c88cb964f55e35400bf399ae
OS | Linux

- Verified steps from issue description
- Verified Leo AI Favicon is shown in colour on both Light and Dark theme

Light | Dark
-- | --
<img width="1151" alt="Image" src="https://github.com/user-attachments/assets/0a3cd7a2-7bb5-4989-a0bc-b49d3d990bb8" /> | <img width="1155" alt="Image" src="https://github.com/user-attachments/assets/15c3a3bb-4b23-453c-a7a8-05c690ca6802" />

--------------

Verification passed on 

Brave | 1.75.162 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | 1c01fd7f190ad7c9c88cb964f55e35400bf399ae
OS | macOS Version 15.2 (Build 24C101)


- Verified steps from issue description
- Verified Leo AI Favicon is shown in colour on both Light and Dark theme

Light | Dark
-- | --
![Image](https://github.com/user-attachments/assets/b1590282-2c30-4b58-8a34-81eaab0bd3c8) | ![Image](https://github.com/user-attachments/assets/11b0fef7-a3f7-46e3-ba3e-22663cfa2d13)
