### ISSUE TITLE
AI Chat history feature should be disabled by default on Android

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#42928]
Until these are all implemented:

- [ ] setting to clear history exists
  - https://github.com/brave/brave-core/pull/27074
 
- [x] user sees a disclaimer saying that history is now stored by default
  - Introduced with desktop feature in:
    - https://github.com/brave/brave-browser/issues/42360
    - https://github.com/brave/brave-browser/issues/42853
- [x] Regular browser history data deletion deletes any related web page visit from conversations
  - Introduced with desktop feature in:
    - https://github.com/brave/brave-browser/issues/42800
    - https://github.com/brave/brave-core/pull/25876

- [ ] A new "Leo AI" browser data deletion checkbox deletes all AI conversations
  - https://github.com/brave/brave-core/pull/27074

Other Android-specific PRs:
- https://github.com/brave/brave-core/pull/27003
- https://github.com/brave/brave-core/pull/26988
- https://github.com/brave/brave-core/pull/26823

**Comment by diracdeltas** [comment]
@petemill for verifcation can you link to the PRs which implement the checked-off items?


> user sees a disclaimer saying that history is now stored by default~

> Regular browser history data deletion deletes any related web page visit from conversations

**Comment by petemill** [comment]
@diracdeltas I've updated the description above to include where each item is resolved and updated the test plans in those issues to make it a little clearer. Also this issue should actually have been closed by:
- https://github.com/brave/brave-core/pull/27038

And so we'll make a new issue to verify the two open issues.

**Comment by petemill** [comment]
Fixed by https://github.com/brave/brave-core/pull/27038
