### ISSUE TITLE
Brave browser is the only browser that doesn't put an offline package option both for desktop and mobile thus keeping us dependant another on their sites unlike Naver Whale, Firefox, Opera, Vivaldi, Zen browsers. Why?

### ISSUE THREAD

**Issue by varnit-nigam** [brave/brave-browser#42944]
### Platforms

all

### Description

Brave browser is the only browser that doesn't put an offline package option both for desktop and mobile thus keeping us dependant another on their sites unlike Naver Whale, Firefox, Zen browsers. Why?

For desktop, I need net or Big Tech MS store And for, mobile it is Big Tech Google Play Store. But we should break from big tech. How? This way?

It is 2025. Please be brave enough to step out and use other methods like other app stores, direct link or cloud link aka server. We want to stop using Google and Microsoft but you guys are dependant on it. Use more ways if this is necessary.

![Image](https://github.com/user-attachments/assets/2cc19e2b-6ed5-42b4-ae0f-b140dcce5d83)
![Image](https://github.com/user-attachments/assets/85266dde-296f-4632-8711-15fdf59ff277)
![Image](https://github.com/user-attachments/assets/0435523f-8bde-4cb9-8ffb-52339530df44)
![Image](https://github.com/user-attachments/assets/9744c676-a0bc-42e7-825e-8e335736f5c6)
![Image](https://github.com/user-attachments/assets/3dc99927-119a-4466-a820-fe0dd6a996af)
![Image](https://github.com/user-attachments/assets/558d704b-76e4-40ab-9c0b-a193a714ecfa)
![Image](https://github.com/user-attachments/assets/42b5ca0e-9250-467c-96b5-9baad19ef116)
![Image](https://github.com/user-attachments/assets/7cffbeae-c8ba-4785-9e2b-cbb23305736f)

**Comment by rebron** [comment]
@varnit-nigam 

You can find additional installer options there. https://github.com/brave/brave-browser/releases/
And our latest release is: https://github.com/brave/brave-browser/releases/tag/v1.73.101
