### ISSUE TITLE
Remove Bridge to Aurora Button

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#42943]
### Description

Now that we have our own internal `Bridging` support, we need to remove the `Bridge to Aurora` feature in the wallet.

### Steps to reproduce

1. Open the `Wallet` and navigate to the `Portfolio` screen.
2. View details for `Ethereum`.
3. We need to remove the `Bridge to Aurora` button since it is no longer needed.

### Actual result

![Image](https://github.com/user-attachments/assets/dd111b8e-320b-491f-a06d-58ab4df37e0e)

### Expected result

![Image](https://github.com/user-attachments/assets/68ab5726-913c-4c44-8ca6-3c0fd265e036)

### Reproduces how often

Easily reproduced

### Desktop Brave version (brave://version info)

1.73.101 Chromium: 131.0.6778.139 (Official Build) (arm64) 

### Android device

- Brand/model: 
- Android version: 

### Channel information

- [x] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.75.148 Chromium: 132.0.6834.57 (Official Build) nightly (64-bit)
-- | --
Revision | 89b8296af95dd49d78a9e46589c7d347cc02b63e
OS | Windows 11 Version 23H2 (Build 22631.4602)

- Verified steps from [brave/brave-core#27053](https://github.com/brave/brave-core/pull/27053)
- Verified `Bridge to Aurora` button is removed from Token details page

https://github.com/user-attachments/assets/88149313-7ae7-4603-8357-f93caf930a7e

**Comment by srirambv** [comment]
Verification passed on Google Pixel with Android 15 running 1.75.145 x64 Nightly build
- Verified steps from [brave/brave-core#27053](https://github.com/brave/brave-core/pull/27053)
- Verified `Bridge to Aurora` button is removed from Token details page

https://github.com/user-attachments/assets/b84bd7f9-3c8c-4e93-9db4-204f6b30a6bb
