### ISSUE TITLE
update leo help links

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#42941]
see https://bravesoftware.slack.com/archives/C04KPE0BUDU/p1734463025776159. there are many instances where we point to https://support.brave.com/hc/en-us/categories/20990938292237-Brave-Leo instead of a more specific article.

**Comment by hffvld** [comment]
Verified on `Galaxy Z Fold 6` using version(s):
```
Device/OS: Galaxy Z Fold 6 / q6quew-user 14 UP1A.231005.007 release-keys
Brave build: 1.75.111
Chromium: 132.0.6834.46 (Official Build) canary (64-bit) 
```

Filed follow-up issue #43000
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/27051#issue-2746219879
2. *Verify*

**ACTUAL RESULTS:**
- Verified that tapping the `Learn more` URL link in the brave search footer opens `https://support.brave.com/hc/en-us/articles/27586048343309-How-does-Leo-get-current-information`.
- Verified that tapping `Learn more` in the `info` modal opens `https://support.brave.com/hc/en-us/articles/26727364100493-What-are-the-differences-between-Leo-s-AI-Models`.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/c57aa60e-d175-44cc-92bc-3a92619f542e) | ![2](https://github.com/user-attachments/assets/1165e7b9-589f-45b5-a698-4ab97b33048a) | ![3](https://github.com/user-attachments/assets/d2e2a7ec-cd66-47b6-885c-91b48707ecfe) |
| ![1](https://github.com/user-attachments/assets/58315b44-0f86-41aa-b338-257842dcb459) | ![2](https://github.com/user-attachments/assets/d1837b46-d0d5-4008-be19-55a00bba7a29) | ![3](https://github.com/user-attachments/assets/ba5fcd91-b727-4522-aa9a-38d6966b5347) |

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 18.2` using version `1.75.133`

Ensured the following using test plan mentioned in https://github.com/brave/brave-core/pull/27051#issue-2746219879

- Verified that tapping the Learn more URL link in the brave search footer opens https://support.brave.com/hc/en- 
     us/articles/27586048343309-How-does-Leo-get-current-information.

- Verified that tapping Learn more in the info modal opens https://support.brave.com/hc/en-us/articles/26727364100493- 
     What-are-the-differences-between-Leo-s-AI-Models.


example | example | example
---|---|---
<img width="250" src="https://github.com/user-attachments/assets/56cb121a-ea8e-49b0-95c8-635751959419"> | <img width="250" src="https://github.com/user-attachments/assets/3cd8baab-fb89-4f13-a8e3-63abec7c2c3b"> | <img width="250" src="https://github.com/user-attachments/assets/1b5f5b05-b7a1-47b1-998b-7571e29eb028">
<img width="250" src="https://github.com/user-attachments/assets/613ec700-a9e1-4bf3-ba98-cfaf5aca6832"> | <img width="250" src="https://github.com/user-attachments/assets/c53116b0-30b0-4bba-8628-a4d6be8a9366"> | <img width="250" src="https://github.com/user-attachments/assets/b8d0b076-6606-4f3b-a587-8061da1bc8eb">

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.162 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | 1c01fd7f190ad7c9c88cb964f55e35400bf399ae
OS | Windows 11 Version 24H2 (Build 26100.2894)

- Verified steps from [brave/brave-core#27051](https://github.com/brave/brave-core/pull/27051)
- Verified `Learn more` on search footer loads `https://support.brave.com/hc/en-us/articles/27586048343309-How-does-Leo-get-current-information`
- Verified `Learn more` on info icon next to model name loads `https://support.brave.com/hc/en-us/articles/26727364100493-What-are-the-differences-between-Leo-s-AI-Models`

https://github.com/user-attachments/assets/921d55c2-e8c4-416a-8b8e-8cae64dd6809
