### ISSUE TITLE
[Desktop] Provide a way (in product) to do a full backup

### ISSUE THREAD

**Issue by InteXX** [brave/brave-browser#4295]
A really nice feature in Chrome is its automated backup and restore of settings, passwords and bookmarks.

In the event of an unexpected data disaster, we should be able to fully recover with ease. We also should be able to easily restore after an OS reinstall. Manual backups are tedious and error-prone; they often are skipped because of this.

While I’m finding guidance for manually backing up and restoring, there seems to be no provision in Brave for automation with only a single device (a very common scenario).

Am I looking past something that's already present?

Thanks,
Jeff Bowman
Fairbanks, Alaska

**Comment by rebron** [comment]
Hi @InteXX, 

Are you requesting a sync feature or looking for backing data up? We already have sync available for bookmarks and we'll be adding passwords, history, more soon.

**Comment by InteXX** [comment]
> Are you requesting a sync feature or looking for backing data up

I'm looking for data backup.

Sync almost gets us there, but not quite.

1. It doesn't work for those with only a single device
2. For those with multiple devices, at least one peer must be running

A reliable unattended backup system that satisfies these could be built on the Sync system.

**Comment by 05nelsonm** [comment]
> Hi @InteXX,
> 
> Are you requesting a sync feature or looking for backing data up? We already have sync available for bookmarks and we'll be adding passwords, history, more soon.

Will syncing all of these things via webdav be supported, using a personal Nextcloud instance, say?

**Comment by bsclifton** [comment]
@InteXX does Chrome meet your needs (using Sync) because it doesn't have the problems listed? Or does Chrome offer a specific backup feature (not related to Chrome). I think we're mostly trying to figure out if this is a new feature request? or if we are hiding/disabling something that Chrome/Chromium offers

**Comment by rebron** [comment]
@InteXX I don't know of Chrome doing a backup and restore as @bsclifton is saying just the Sync as far as I know, unless there's another Extension for it. 

I do know there's a Firefox implementation for auto backup and restore of bookmarks that was implemented many years ago. I don't know if that's what you're looking for, and that was only bookmarks.

<img width="635" alt="Screen Shot 2019-05-13 at 10 37 53 AM" src="https://user-images.githubusercontent.com/5951041/57642561-74529e00-756c-11e9-85d6-45b3392895ea.png">

**Comment by InteXX** [comment]
@bsclifton 

> does Chrome meet your needs (using Sync) because it doesn't have the problems listed?

Yes, that's the case. When we reinstall Windows (or load up our Windows profile onto a new machine), and then sign in to Chrome for the first time on that new profile, all of our bookmarks, passwords and other info are automatically restored. We don't have to have another instance of the browser running somewhere else in order to receive these.

> I think we're mostly trying to figure out if this is a new feature request? or if we are hiding/disabling something that Chrome/Chromium offers

Hm, I'm not sure. An enhancement, certainly. Since I'm presently unaware of the internal architectures of 
Brave/Chrome, I'm not able to effectively answer this.

**Comment by InteXX** [comment]
@rebron 

> I don't know of Chrome doing a backup and restore

It's described [here](https://chrome.google.com/sync).

> a Firefox implementation ... I don't know if that's what you're looking for

Something like that, but for all personal information stored by Brave/Chrome:

- Apps
- Extensions
- Settings
- Autofill
- History
- Themes
- Bookmarks
- Passwords
- Open tabs

Similar to Chrome Sync, I'd say, without the requirement for an active peer instance (currently required with Brave Sync).

I'd love to start using Brave, but the lack of this capability is holding me back. Effective backup/restore is the lifeblood of an application such as this.

**Comment by artella-coding** [comment]
#9155

**Comment by amiremami** [comment]
Will there be any better solution for backing up all personal information on Brave instead of copy and pasting appdata folder?

**Comment by amiremami** [comment]
I want to change my windows. I want to reinstall brave with all of my data. Please explain how can I do that?

Apps
Extensions
Settings
Autofill
History
Themes
Bookmarks
Passwords
Open tabs

**Comment by bsclifton** [comment]
Going to close as this is a question and has basically been answered. With our sync functionality (available in 1.12 and newer), you can store your bookmarks/autofill/extensions/etc in the sync group which may solve the problem for the majority of folks

**Comment by InteXX** [comment]
@bsclifton 

It has not been answered. Brave's sync functionality does not provide these necessary capabilities:

1. It doesn't work for those with only a single device
2. For those with multiple devices, at least one peer must be running

**Comment by bsclifton** [comment]
Thanks for the feedback @InteXX - just re-opened; let me modify this issue a bit to include some actionable details

**Comment by amiremami** [comment]
@bsclifton  In chrome, all info will be stored on google server online. For example extensions... So, when I want to restore my info on a new computer, it connects to server and download all info.

So, you are saying, you added similar feature that info will be stored online?

**Comment by bsclifton** [comment]
@amiremami yes - you can visit brave://settings/braveSync/setup and setup a sync group. This pushes all the same information that Chrome does in their version of sync to our sync server. All of the data is client-side encrypted, so we have no way to look at the information

Older versions of sync required two machines - but new version should work fine with just one. Give it a shot- let us know how it works

**Comment by InteXX** [comment]
@bsclifton 

I finally got a minute to look at this.

Here's what I did:

1. Installed Brave
2. Bookmarked a web page
3. Turned on Sync
4. Saved the Sync Code
5. Uninstalled Brave
6. Reinstalled Brave
7. Verified that the previously saved bookmark wasn't brought forward
8. Turned on Sync, using the previously saved code
9. Verified that the previously saved bookmark was restored

So I'd call this a win. Feature complete.

Good job! I'll start the process of switching to Brave soon.
