### ISSUE TITLE
Unable to send from transparent to shielded account

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#42951]
### Description

Unable to send from transparent to shielded account

### Steps to reproduce

1. Create 2 ZCash accounts
2. Make one account as Shielded
3. Send from transparent account to Shielded account
4. Shows transparent account address for Shielded account in receiving account
5. Submit Send transaction
6. Doesn't confirm transaction

### Actual result

Unable to send from transparent to shielded account

### Expected result

Should be able to send transaction from transparent address account to shielded account

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave | 1.75.105 Chromium: 132.0.6834.46 (Official Build) nightly (64-bit)
-- | --
Revision | 23319880bc0dddd28b9417b78040f192738dee20
OS | Windows 11 Version 23H2 (Build 22631.4460)

### Channel information

- [ ] release (stable)
- [ ] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

cc: @cypt4

**Comment by cypt4** [comment]
This happens due zcash network update to the new nu6 version. Transparent transactions are also affected. Increased priority to p2.

**Comment by kjozwiak** [comment]
The above requires `1.73.105` or higher for `1.73.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.73.105 Chromium: 131.0.6778.265 (Official Build) (64-bit)
-- | --
Revision | adf1b0089a62f3ed9260e23c8cd3c7862a1e410c
OS | Windows 11 Version 23H2 (Build 22631.4602)

- Verified able to send transactions on transparent address for ZCash accounts

https://github.com/user-attachments/assets/919f8988-9f27-4b8a-841d-daadf7901ce6
