### ISSUE TITLE
On Linux chrome://crashes doesn't show crash reports

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#4296]
## Description 

Found while testing #4111 
On Linux chrome://crashes doesn't show crash reports

## Steps to Reproduce

   1. Clean profile 0.64.68
   2. Force a tab crash by entering brave://crash
   3. Navigate to brave://crashes and check the crash report

## Actual result:

You have no recently reported crashes. Crashes that occurred when crash reporting was disabled will not appear here.

![image](https://user-images.githubusercontent.com/38657976/57130905-a4ee4700-6db8-11e9-864a-9c74778c7f45.png)

## Expected result:

Crash reports should be shown in brave://crashes
## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.64.68 Chromium: 74.0.3729.108 (Official Build) beta (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No - it was blocked due to #4111 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa

**Comment by kjozwiak** [comment]
Reproduced on Ubuntu 18.04.2 LTS x64` using the following build:

* `0.63.55 CR: 74.0.3729.131` - Reproduced
* `0.64.72 CR: 74.0.3729.131` - Reproduced
* `0.65.85 CR: 74.0.3729.131` - Reproduced
* `0.67.1 CR: 74.0.3729.131` - Reproduced

Also tried the following (crashes still weren't appearing under `brave://crashes`):

* crashed using `chrome://crash` & `chrome://gpucrash`
* enabled/disabled `Enable Crash Reporting` via brave://settings

**Comment by srirambv** [comment]
This is working for me on Beta/Dev/Nightly. Visiting `brave://crash` creates a webview crash. `brave://crashes` shows uploaded crash id which is listed in stats. Doesn't work on release channel though. Not sure which PR has fixed this but looks to be working. @GeetaSarvadnya wasn't able to reproduce it on the nightly channel in her VM though.

**Comment by GeetaSarvadnya** [comment]
The issue is still Reproducible on my VM Linux Mint 

Brave | 0.67.62 Chromium: 75.0.3770.38 (Official Build) nightly (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Linux

**Comment by btlechowski** [comment]
Reproduced on

Brave | 0.65.114 Chromium: 75.0.3770.38 (Official Build) (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Ubuntu 18.04 LTS

**Comment by kjozwiak** [comment]
hmmm I'm still seeing the issue as well. Went through the following cases two cases:

* visited `brave://crash` & `chrome://crash` & `chrome://gpucrash`
* checked `brave://crash` to see if the crashes were logged

Using `Ubuntu 19.04 x64 VM`, went through the following:

* `0.65.115 Chromium: 75.0.3770.38` - Reproduced issue
* `0.67.71 Chromium: 75.0.3770.38` - Reproduced issue
* `0.68.5 Chromium: 75.0.3770.38` - Reproduced issue

Using `Mint 19.1 x64`, went through the following:

* `0.65.115 Chromium: 75.0.3770.38` - Reproduced issue
* `0.67.71 Chromium: 75.0.3770.38` - Reproduced issue
* `0.68.5 Chromium: 75.0.3770.38` - Reproduced issue

**Comment by btlechowski** [comment]
Still reproducible

Brave | 1.10.88 Chromium: 83.0.4103.97 (Official Build) (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | Ubuntu 18.04 LTS

**Comment by btlechowski** [comment]
With introduction of `First run dialog` where we ask users to enable automatic crash reporting (https://github.com/brave/brave-browser/issues/12679) I think it is a good idea to fix this issue.

@rebron Can we prioritize this issue and get someone involved?

**Comment by btlechowski** [comment]
The issue has been fixed by https://github.com/brave/brave-core/pull/8049. Thank you @keur !

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.22.53 Chromium: 89.0.4389.72 (Official Build) beta (64-bit)
-- | --
Revision | 3f345f156bfd157bd1bea06310e55f3fb2490359-refs/branch-heads/4389@{#1393}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

```
--2021-03-07 11:08:30--  https://cr.brave.com/
Resolving cr.brave.com (cr.brave.com)... 199.232.18.137
Connecting to cr.brave.com (cr.brave.com)|199.232.18.137|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 36
Saving to: ‘/dev/fd/4’

     0K                        
  Crash dump id:   1f1e0000-bef0-f505-0000-000000000000 
                          100%  764K=0s

2021-03-07 11:08:32 (764 KB/s) - ‘/dev/fd/4’ saved [36/36]

--2021-03-07 11:08:32--  https://cr.brave.com/
Resolving cr.brave.com (cr.brave.com)... 199.232.18.137
Connecting to cr.brave.com (cr.brave.com)|199.232.18.137|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 36
Saving to: ‘/dev/fd/4’

     0K                                
  Crash dump id:  201e0000-bef0-f505-0000-000000000000 
                   100%  565K=0s

2021-03-07 11:08:34 (565 KB/s) - ‘/dev/fd/4’ saved [36/36]
```

![image](https://user-images.githubusercontent.com/34715963/110236398-eceecf80-7f35-11eb-90c9-02c3619bdaaa.png)
![image](https://user-images.githubusercontent.com/34715963/110236479-5969ce80-7f36-11eb-897e-69c3a6048b80.png)
