### ISSUE TITLE
Maximize and minimize window options not required in `Add IPFS companion` popup

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#4297]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/4218

Maximize and minimize window options not required in `Add IPFS companion` popup. Maximize option is causing buttons disapper ( `Cancel`  and  `Add extension` ) from `Add IPFS companion` popup

## Steps to Reproduce

   1. Clean profile 0.64.68
   2.  Navigate to brave://settings
   3.  Search for IPFS and toggle the  `IPFS Companion` switch to ON 
   4. Click on `+` or maximize option in `Add IPFS companion` popup

## Actual result:

Buttons  `Cancel`  and  `Add extension` disappers from `Add IPFS companion` popup

![image](https://user-images.githubusercontent.com/38657976/57136941-f8b65b80-6dcb-11e9-8acb-583e0c1bede0.png)
![IPFS extension install popup issue_Linux](https://user-images.githubusercontent.com/38657976/57137029-39ae7000-6dcc-11e9-9add-a812e07243e9.gif)

## Expected result:
Maximize and minimize window options needs to removed from `Add IPFS companion` popup

![image](https://user-images.githubusercontent.com/38657976/57136963-0966d180-6dcc-11e9-8690-5bafa5b148a1.png)

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.64.68 Chromium: 74.0.3729.108 (Official Build) beta (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

@brave/legacy_qa

**Comment by rebron** [comment]
Closing. Works as expected, current linux behavior for windows.
