### ISSUE TITLE
Add Page Context Toggle for Brave AI Chat Sidebar/Popover

### ISSUE THREAD

**Issue by thypon** [brave/brave-browser#42982]
## Summary
Add a feature flag to control whether the Brave AI Chat sidebar uses the current page's content as context for generating responses.

## Description
This feature adds a new flag `brave-ai-chat-page-context` that controls whether the AI Chat sidebar should consider the current webpage's content when generating responses. This allows users to choose whether they want more contextually relevant responses based on the page they're viewing.

### Technical Details
- Feature flag name: `brave-ai-chat-page-context`
- Internal feature name: `UsePageContext`
- Default state: Enabled
- Supported platforms: all

## Implementation Notes
- Adds new feature flag in about:flags
- Modifies the conversation handler to respect the feature flag state when deciding whether to include page contents
- Feature can be toggled via about:flags interface

## User Impact
When enabled, the AI Chat sidebar will use the current page's content to provide more contextually relevant responses. When disabled, responses will be generated without page context.

## Testing Requirements
- Verify feature flag appears in about:flags
- Confirm page context is used when flag is enabled
- Confirm page context is not used when flag is disabled
- Test across supported platforms (Windows, macOS, Linux, Android)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.162 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | 1c01fd7f190ad7c9c88cb964f55e35400bf399ae
OS | Windows 11 Version 24H2 (Build 26100.2894)

- Verified steps from issue description
- Verified `brave://flags/#brave-ai-chat-web-content-association-default` flag is set to Enabled by default
- Verified with flag enabled page context switch is enabled by default when visiting a page and loading Leo in sidebar
- Verified disabling the flag and loading Leo on a webpage, page context switch is disabled. Can be toggled to on

https://github.com/user-attachments/assets/ee666968-32b9-43a2-b801-ae211c42f602

----------
Verification passed on

Brave | 1.75.162 Chromium: 132.0.6834.83 (Official Build) beta (64-bit)
-- | --
Revision | 1c01fd7f190ad7c9c88cb964f55e35400bf399ae
OS | Linux

- Verified steps from issue description
- Verified `brave://flags/#brave-ai-chat-web-content-association-default` flag is set to Enabled by default
- Verified with flag enabled page context switch is enabled by default when visiting a page and loading Leo in sidebar
- Verified disabling the flag and loading Leo on a webpage, page context switch is disabled. Can be toggled to on

https://github.com/user-attachments/assets/68da6d8c-241c-4b08-8281-c1b07b9631da

----------
Verification passed on

Brave | 1.75.162 Chromium: 132.0.6834.83 (Official Build) beta (arm64)
-- | --
Revision | 1c01fd7f190ad7c9c88cb964f55e35400bf399ae
OS | macOS Version 15.2 (Build 24C101)

- Verified steps from issue description
- Verified `brave://flags/#brave-ai-chat-web-content-association-default` flag is set to Enabled by default
- Verified with flag enabled page context switch is enabled by default when visiting a page and loading Leo in sidebar
- Verified disabling the flag and loading Leo on a webpage, page context switch is disabled. Can be toggled to on

https://github.com/user-attachments/assets/5d4f1b7e-e9b8-47ca-9f31-8c1c900ab649

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using the following version(s):

```
Brave	1.75.169 Chromium: 132.0.6834.111 (Official Build) beta (64-bit) 
Revision	edf91181b25cd5879cd12aa126fda2b736ae3a42
OS	Android 14; Build/UP1A.231005.007; 34; REL
```
* Verified brave://flags/#brave-ai-chat-web-content-association-default flag is set to `Enabled` by default on Android.
* Verified that page context is used when flag is enabled (default in this case).
* Verified that page context is not used when disabled the flag. 
* Ensured that page context toggle can be still be enabled if its disabled by flag. 
* Ensured that page summary and suggest questions have not regressed.

brave://flags (default state) | page context enabled | page context disabled | brave://flags (disabled) | suggest questions 
--|--|--|--|--
![Image](https://github.com/user-attachments/assets/5c60fef7-0688-4d6c-af0c-0dd56e3fdf16) | ![Image](https://github.com/user-attachments/assets/578e5e54-d35a-43a9-974f-c363eac35905) | ![Image](https://github.com/user-attachments/assets/dc8643df-d488-49be-bdfa-215e5e8225a8) | ![Image](https://github.com/user-attachments/assets/a8055a31-c16a-4a45-a4a8-9fc48c22d044) | ![Image](https://github.com/user-attachments/assets/3a384906-8e22-4be4-a659-0894d90126f8) |

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using version: 

```
Brave	1.75.169 Chromium: 132.0.6834.111 (Official Build) beta (64-bit) 
Revision	edf91181b25cd5879cd12aa126fda2b736ae3a42
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

* Verified brave://flags/#brave-ai-chat-web-content-association-default flag is set to `Enabled` by default on Android Tablet.
* Verified that page context is used when flag is enabled (default in this case).
* Verified that page context is not used when disabled the flag. 
* Ensured that page context toggle can be still be enabled if its disabled by flag. 
* Ensured that page summary and suggest questions have not regressed.

brave://flags (default state) | page context enabled | page context disabled | enabling toggle | page summary test 
--|--|--|--|--
![Image](https://github.com/user-attachments/assets/f58384c5-c042-4721-aa2e-c14d6a4dab15) | ![Image](https://github.com/user-attachments/assets/ca9aaef5-c37a-4531-9795-cb26fd3df4d9) | ![Image](https://github.com/user-attachments/assets/c4ee6780-8308-4c7f-ba22-c459838fc4b4) | ![Image](https://github.com/user-attachments/assets/0df82694-60fd-42e5-aa96-1c8948c37436) | ![Image](https://github.com/user-attachments/assets/011a26aa-0bd4-4970-9b6d-6c128661a3e6)

**Comment by Uni-verse** [comment]
Removed `OS/iOS` label because flag is not enabled on iOS at this time. There will be separate issue. 

 @thypon @srirambv @kjozwiak @mattmcalister
