### ISSUE TITLE
Transactions Partner Consent Keeps Popping up

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#42984]
### Description

Currently there is a bug where the `Transactions Partner` consent modal keeps popping up if closed.

### Steps to reproduce

1. Create a brand new wallet and then click on the `Buy` button in the nav.
2. Once the `Transactions Partner` consent modal appears, click the `x` button to close it.
3. Now try navigating to any other tab in the `nav`.
4. The `Transactions Partner` consent modal will keep popping up.

### Actual result

https://github.com/user-attachments/assets/e5135fa8-de4a-4fe9-8d5b-f543001abf17

### Expected result

Should only appear when navigating to the `Buy` screen and terms have not been accepted.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.74.31 Chromium: 132.0.6834.46 (Official Build) beta (arm64) 

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by kjozwiak** [comment]
The above requires `1.74.33` or higher for `1.74.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.41 Chromium: 132.0.6834.57 (Official Build) beta (64-bit)
-- | --
Revision | 5864eff704ffcff4c30df7041595e557036b410c
OS | Windows 11 Version 23H2 (Build 22631.4602)

- Verified steps from issue description
- Verified when selecting Buy transaction partner modal is shown
- Verified navigating to other tabs doesn't show the transaction partner modal
- Verified manually navigating to `brave://wallet/fund-wallet` shows the transaction partner modal
- Verified manually navigating to other routes doesn't show the transaction partner modal

https://github.com/user-attachments/assets/14fa91c6-fe1e-45a0-b5a3-db1ae353df33
