### ISSUE TITLE
[iOS] - Fix continuation leak in AlertPopupView

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#42986]
### Description

- AlertPopupView can leak the continuation when WebKit cancels the requests or starts another request while the popup is displayed.

### Steps to reproduce

1. https://hackerone.com/reports/2909560

### Actual result

- Popup is shown on the wrong page

### Expected result

- Popup should show not show

### Reproduces how often

Easily reproduced

### Brave version

- All

### Device/iOS version

- All

### Affected browser versions

- [x] latest AppStore
- [x] latest TestFlight
- [x] previous TestFlight

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] in the latest version of mobile Safari

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.7.2
Brave build: 1.75 (148)
BraveCore: 1.75.148 (132.0.6834.57)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://hackerone.com/reports/2909560
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the pop-up is not shown on the wrong page.

---------------------------

https://github.com/user-attachments/assets/c1c51269-67ec-4afa-9d1f-a0b331415955

**Comment by hffvld** [comment]
Verified on `iPad Mini (6th gen)` using version(s):
```
Device/OS: iPad Mini (6th gen) / iPadOS 18.2.1
Brave build: 1.75 (164)
BraveCore: 1.75.164 (132.0.6834.83)
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://hackerone.com/reports/2909560
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the pop-up is not shown on the wrong page.

---------------------------

https://github.com/user-attachments/assets/d2e23f27-3e74-4a93-8f28-481aa4687020
