### ISSUE TITLE
Android Settings can delete Leo AI history

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#42995]
Android needs some settings update to reach parity with Desktop and be allowed to enable persistant storage for Leo by default:
- Browser Data deletion gets Leo AI checkbox which deletes all conversations in the provided timeframe. 
- The "Leo" section of preference's "reset data" button now deletes all conversations (and has its wording changed to match desktop).

These were previously implemented for desktop in:
 - https://github.com/brave/brave-core/pull/25876
 - https://github.com/brave/brave-browser/issues/42800

Related:
- https://github.com/brave/brave-browser/issues/42928

## Test Plan
On:
- https://github.com/brave/brave-core/pull/27074

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 15 running 1.75.171 x64 build
- Verified steps from [brave/brave-core#27074](https://github.com/brave/brave-core/pull/27074)
- Verified selecting `Settings -> Leo -> Delete all Leo AI conversation data` deletes all AI conversation data
- Verified with deleting all browser data including Leo AI all AI conversation is delted
- Verified visiting a site and summarising it and deleting browsing data, going back to Leo doesn't show the title or logo

<video src=https://github.com/user-attachments/assets/1f1c5d03-1c33-43c3-9453-5af98d9eca8d> | <video src=https://github.com/user-attachments/assets/d7bb3ca0-8493-4a51-a657-103abb7fc507> | <video src=https://github.com/user-attachments/assets/65320eba-685b-43da-a8ea-9b1b1ad1f18f>
-- | -- | --
