### ISSUE TITLE
Shields shows different blocked items on b-c compared to b-l

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#430]
## Description 

Shields shows different blocked items on brave-core compared to browser-laptop

## Steps to Reproduce
   1. Visit wired.com in brave-core
   2. Shields shows different blocked items compared to current release and beta channel on b-l 

## Actual result:
Left-brave-core
Center- 0.22.810 (Release version)
Right - 0.23.18 (Release preview with Easy Privacy list)

![image](https://user-images.githubusercontent.com/17010094/41919640-fdfe1c70-792c-11e8-980e-c1d826dcef64.png)

## Expected result:
Blocked items should match with b-l with Easy Privacy list 

## Reproduces how often: 

100% on all sites

## Brave version (about:brave info) 

Packaged build

### Reproducible on current release: 

Different blocked items on b-l

### Website problems only:  
- Does the issue gets fixed with Brave Shields disabled? 
- Does the issue reproduces on Chrome? 

### Additional Information

cc: @bbondy @lukemulks

**Comment by bbondy** [comment]
do you think this is because we don't dedupe them yet? If so I think we're already tracking it.

**Comment by srirambv** [comment]
Not really. Brave-core is showing https upgrade but same is not the case on browser-laptop with release/beta version.

**Comment by bsclifton** [comment]
@srirambv this should be matching now since browser-laptop is also using EasyPrivacy

**Comment by cezaraugusto** [comment]
@srirambv can we close this?

**Comment by srirambv** [comment]
Yup we can close this one.
