### ISSUE TITLE
YouTube's anti-adblock/adblock detection system gets past Brave Shield

### ISSUE THREAD

**Issue by naufalHaidar12342** [brave/brave-browser#43015]
### Description

Recently (21 December 2024) when I want to watch YouTube's videos or live streams, YouTube's anti-adblock system being triggered and causing the videos being blocked. This issue had happened in the past to me but it is resolved by simply updating the filter list of Brave Shield, deleting the cache for YouTube, and restarting the browser

Some exceptions that I noticed are:
- watching YouTube in Brave's private window will not trigger YouTube anti-adblock system, probably due to logged out of Google Account
- watching YouTube in Brave's normal window while logged out of YouTube also would not trigger the anti-adblock system
- watching YouTube Shorts with Brave Shield being active

### Steps to reproduce

1. Open Brave's normal window
2. Make sure the Brave Shield is on/enabled and the `Trackers & ads blocking` is set to `Standard` (go to `brave://settings/shields` to check this part)
3. Go to YouTube
4. Watch the videos/live streams while logged in to Google Account

### Actual result

YouTube's video playback got blocked and I can not watch the videos/live streams

### Expected result

Brave Shield able to counter/bypass the YouTube anti-adblock detection

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.73.104 Chromium: 131.0.6778.204 (Official Build) (64-bit) 

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [x] in the latest version of Chrome

### Miscellaneous information

Edit-1:Even with additional adblock, like `uBlock Origin` being disabled, the YouTube anti-adblock system still able to detects Brave Shield's adblock
Edit-2: Filter lists that I enabled (being checked with check mark ✅) are:
- EasyList Cookie
- Fanboy's Mobile Notifications
- Brave Experimental Adblock Rules

_No response_

**Comment by edt-xx** [comment]
happening here to on Arch with brave-bin 1:1.73.104-1

**Comment by Toni500github** [comment]
same with EndeavourOS, brave-bin 1:1.73.101-1

**Comment by arxkdev** [comment]
Happening to me as well,
Version 1.73.104 Chromium: 131.0.6778.204 (Official Build) (64-bit)

**Comment by uNetworkingAB** [comment]
Can confirm. And so the cat and mouse play begins 😄

**Comment by Toni500github** [comment]
> happening here to on Arch with brave-bin 1:1.73.104-1

me too

**Comment by neofutur** [comment]
Confirmed, same exact problem here, started right now.

**Comment by naufalHaidar12342** [comment]
> Can confirm. And so the cat and mouse play begins 😄

Yeah 😭. Let's hope the team could get the patched online as soon as possible. YouTube's ignorant acts when it comes to regulating their advertisement system still continue. Phishing, scams, or even straight up malware links could be advertised and I fear more people could fell victim to it, just because they have to compromise by disabling the adblock

**Comment by CanalYT** [comment]
_I have the **same problem**!_
[Image](https://github.com/user-attachments/assets/73df734d-f0ed-43f1-8555-fd8f25de0954)

**Comment by GeeSuth** [comment]
Same here, all the best Brave developer I hope you comes with solution soon as possible.

**Comment by MihirRajeshPanchal** [comment]
I cleared my cache and the issue was solved, also I removed the youtube enhancer extension from the browser which I recently installed

Hope this solves the issue

**Comment by grondilu** [comment]
Fedora silverblue user here.

Brave version  v1.73.104 (Dec 19, 2024)

**Comment by SamuelvLopes** [comment]
![Image](https://github.com/user-attachments/assets/69ebc18e-4cff-470c-afa8-906ea0def550)

[Versão 1.73.104 Chromium: 131.0.6778.204 (Versão oficial) 64 bits](https://brave.com/latest/)

**Comment by ahmetsabri** [comment]
same problem:
mac os: 15.2 (24C101)
[Version 1.73.104 Chromium: 131.0.6778.204 (Official Build) (arm64)](https://brave.com/latest/)

**Comment by ryanbr** [comment]
Not sure if this will help or not,  @ahmetsabri @SamuelvLopes @a4amado @grondilu 

In `brave://components ` force an update of `Brave Ad Block Updater ` too  Version: **1.0.9653**

Then refresh Youtube.com tabs (important).  Let me know if it helps

**Comment by uNetworkingAB** [comment]
It works. 🥇

**Comment by ahmetsabri** [comment]
it works, thanks!

**Comment by uNetworkingAB** [comment]
You are excellent 👌

**Comment by naufalHaidar12342** [comment]
> Not sure if this will help or not, [@ahmetsabri](https://github.com/ahmetsabri) [@SamuelvLopes](https://github.com/SamuelvLopes) [@a4amado](https://github.com/a4amado) [@grondilu](https://github.com/grondilu)
> 
> In `brave://components ` force an update of `Brave Ad Block Updater ` too Version: **1.0.9653**
> 
> Then refresh Youtube.com tabs (important). Let me know if it helps

just woke up and open my Brave browser and check this, turns out the `Brave Ad Block Updater` version is set to version **1.0.9656**. Can confirm that YouTube anti-adblock detection did not block me from watching the video, even when I set the ad block level to `Aggressively block trackers&ads`
![Image](https://github.com/user-attachments/assets/501f0959-7b34-4fb7-840f-ac62cd31203b)

**Comment by ShivanKaul** [comment]
> In brave://components  force an update of Brave Ad Block Updater  too Version: 1.0.9653

If you're on iOS, you can force-update your lists by going to Settings > Shields & Privacy > Content Filtering > pressing the Update Lists button

**Comment by bsclifton** [comment]
Closing as this is now resolved 😄   Nice work, @ryanbr!
