### ISSUE TITLE
Add Activity to Portfolio Segmented Control on Full Page View

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#43024]
### Platforms

all

### Description

We need to add the `Activity` tab to the `Portfolio` segmented control on the Wallet full page view, to match how it is in the Wallet `Panel`.

![Image](https://github.com/user-attachments/assets/0a308434-18f4-4205-93af-ebc9f6bf14b0)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.75.148 Chromium: 132.0.6834.57 (Official Build) nightly (64-bit)
-- | --
Revision | 89b8296af95dd49d78a9e46589c7d347cc02b63e
OS | Windows 11 Version 23H2 (Build 22631.4602)

- Verified steps from [brave/brave-core#27101](https://github.com/brave/brave-core/pull/27101)
- Verified `Activity` is added to segmented control in Portfolio tab

https://github.com/user-attachments/assets/5f900c4e-70b1-4593-9551-95e772bed410
