### ISSUE TITLE
REQUEST: Block annoying GDPR notices

### ISSUE THREAD

**Issue by Kreyren** [brave/brave-browser#4303]
DISCLAIMER: Didn't find any relevant issue.

Requesting updating adblock definitions on Brave-browser with list https://raw.githubusercontent.com/r4vi/block-the-eu-cookie-shit-list/master/filterlist.txt to block annoying GDPR notices alike:
![image](https://user-images.githubusercontent.com/11302521/57186590-554f6e80-6ed1-11e9-83cd-b454d60fe2f0.png)

## Steps to Reproduce
Use EU geolocation and visit any website that process personal informations or telemetry, example: champions.gg

**Comment by Kreyren** [comment]
Or at least some method to add defitions to adblock from user-side..

**Comment by ryanbr** [comment]
I currently maintain a cookie list already; https://secure.fanboy.co.nz/fanboy-cookiemonster.txt  But we'll need to support cosmetic filtering before it'll be useful (which will also help out adblocking)

**Comment by bsclifton** [comment]
Added to the cosmetic filter board 😄 @ryanbr we have @Snuupy working on cosmetic filter issues. You can do blocking, but the list isn't visible or editable (yet)

**Comment by antonok-edm** [comment]
Just a heads up, cosmetic filtering is supported on Desktop and the cookie list is in brave://adblock now.

**Comment by NumDeP** [comment]
Possibly a dupe of #12597 and #9338

**Comment by ryanbr** [comment]
@Kreyren  Just install either Fanboy Annoyances or Easylist Cookie, this will help with these gdpr/cookie messages. Closing ticket as I couldn't replicate this, free to reopen with any issues.
