### ISSUE TITLE
Visiting bbcnews.com triggers “The link that you originally opened is unusual” warning

### ISSUE THREAD

**Issue by da2x** [brave/brave-browser#4304]
1. Type in ‘bbcnews.com’ and hit Enter.

Expected: To visit the British Broadcasting Corporation’s unusually good news service.

Actual: A recommendation to visit NBC News instead.

Brave: 0.63.48 Chromium: 74.0.3729.108

![screenshot](https://user-images.githubusercontent.com/1102886/57196178-858f1f80-6f5a-11e9-9fae-cb4968c14016.png)

(This URL is owned by the BBC and they’ve promoted it heavily over the years. It’s supposed to redirect you to bbc.co.uk/news if you’re in the UK or bbc.com/news internationally.)

**Comment by rebron** [comment]
All other browsers (Chrome, Firefox, Safari) are properly redirecting to bbc.co.uk and then finally to https://www.bbc.com/news.

**Comment by rebron** [comment]
Related issue: https://github.com/brave/brave-browser/issues/3942#issuecomment-489338354

**Comment by rebron** [comment]
cc: @simonhong Can you take a look at this one?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.4 x64` using the following build:

Brave | 0.64.73 Chromium: 74.0.3729.131 (Official Build) (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Went through the test plan outlined under https://github.com/brave/brave-browser/issues/4304#issue-440456552
