### ISSUE TITLE
Make Tor integration compatible with NetworkService

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#4312]
As part of migration we have to fix Tor - it doesn't work with enabled NetworkService. It seems that the reason is `TorProfileServiceImpl::SetNewTorCircuitOnIOThread`: `URLRequestContext` is not compatible with NetworkService.

**Comment by iefremov** [comment]
@darkdh @riastradh-brave FYI

**Comment by iefremov** [comment]
It is handy to use `--enable-features=NetworkService` to run Brave with NetworkService

**Comment by GeetaSarvadnya** [comment]
@darkdh When I launch brave using `--enable-features=NetworkService` flag. Open `https://check.torproject.org/` in Tor windows doesn't connect to the tor network. But, as per the test plan https://github.com/brave/brave-core/pull/2647, it should connect to tor network

![image](https://user-images.githubusercontent.com/38657976/61469587-180d5f80-a99d-11e9-9b63-1969c23893aa.png)

**Comment by darkdh** [comment]
@GeetaSarvadnya Did you launch it using fresh profile? There is another issue blocking this test case (https://github.com/brave/brave-browser/issues/5007), so before #5007 is fixed, we have to launch without `--enable-features=NetworkService` switch and wait for tor executable to be downloaded and then relaunch with `--enable-features=NetworkService` and connect to tor network

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.67.111 Chromium: 75.0.3770.100 (Official Build) beta (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

I was able to verify by using directions from https://github.com/brave/brave-core/pull/2647  and https://github.com/brave/brave-browser/issues/4312#issuecomment-512891947
Encountered https://github.com/brave/brave-browser/issues/5007 and https://github.com/brave/brave-browser/issues/3512
