### ISSUE TITLE
Further privacy and security on catalog download

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#4313]
## Description 
Transferring over this now archived issue: https://github.com/brave-intl/bat-native-ads/issues/140

The consensus appears to be that for further privacy on catalog downloads, it should not be downloaded on browser startup, and that we should impose additional variance on the pings.

**Comment by Miyayes** [comment]
@jsecretan Is this still an issue? I'm going to take it out of the Rewards global board.
