### ISSUE TITLE
Cannot automatically backup/restore

### ISSUE THREAD

**Issue by InteXX** [brave/brave-browser#4320]
There's only one thing that's stopping me from switching to Brave: the inability to automatically back up and restore passwords/settings/history/bookmarks.

This capability is absolutely critical in any modern operating environment. Data disasters do happen; operating systems do get reinstalled.

I suggest assigning this issue a high priority.

**Comment by rebron** [comment]
Closing. Dupe of previous issue filed.

**Comment by InteXX** [comment]
@rebron 

Do you have a link to the previous issue? I looked before opening this one, but I didn't find any.

**Comment by bsclifton** [comment]
@InteXX sure - the duplicate link is https://github.com/brave/brave-browser/issues/4295
