### ISSUE TITLE
Adding "Add folder" into bookmark manager

### ISSUE THREAD

**Issue by StephD** [brave/brave-browser#4329]
## Description 
Improvement proposition, not an issue.
Not sure where I can propose this improvement.

- Naming of "Bookmark**s** manager" instead of "Bookmark manager" when rightclick on any bookmark
- Ability to create folder from the bookmarks manager

## Steps to Reproduce
Naming
   1. Right-click on the bookmark bar
   2. See "Bookmark Manager"
   3. Rename into "Bookmark**S** manager"

Creating folder
   1. Going into the bookmark manager
   2. Right-click on a folder
   3. Add create folder possibility

## Reproduces how often: 
All time

## Brave version (brave://version info)
0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)

## Version/Channel Information:
??

## Other Additional Information:
??
- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
There are two ways to add a folder, right click in any empty space and in the right most menu at the top. I'm not sure we'll add this item in the context menu when right-clicking on a folder but appreciate the suggestion.

**Comment by kjozwiak** [comment]
Example of the above:

<img width="948" alt="Screen Shot 2019-05-10 at 12 14 31 PM" src="https://user-images.githubusercontent.com/2602313/57541583-59d6b580-731d-11e9-85e8-eaa9ff5100c5.png">

**Comment by StephD** [comment]
Thank for the answer. 
It's less intuitive then right-click in the middle of the list of bookmark in the bookmark manager but may be just a point of view
