### ISSUE TITLE
Too much bottom padding on scripts details view

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4336]
## Description 

Too much bottom padding on scripts details view

## Steps to Reproduce

   1. Block scripts on a page
   2. Open details view of scripts blocked
   3. Too much bottom padding for Go Back and Cancel buttons

## Actual result:

![Screenshot from 2019-05-07 12-49-09](https://user-images.githubusercontent.com/17010094/57317714-c310bb80-70c6-11e9-9599-f1dba1a2c557.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/57317773-eb98b580-70c6-11e9-8d83-87a40da1bee5.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.64.72 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
No
- Can you reproduce this issue with the beta channel?
Yes
- Can you reproduce this issue with the dev channel?
Yes
- Can you reproduce this issue with the nightly channel?
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
N/A
- Does the issue resolve itself when disabling Brave Rewards?
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A
## Miscellaneous Information:

cc: @karenkliu @cezaraugusto

**Comment by cezaraugusto** [comment]
this was fixed after https://github.com/brave/brave-ui/commit/4eeb39ebfdf3bccdd060b143579eb441f770fcf5 landed in brave-core so I'm closing this one. @srirambv please re-open if you think I'm wrong
