### ISSUE TITLE
After upgrade to the latest version, Ads switch is turned OFF automatically and unable to turn it ON 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#4339]
## Description 

After upgrade to the latest version, Ads switch is turned OFF automatically and unable to turn it ON 

## Steps to Reproduce

   1. Brave beta 0.63.45 (profile was created and viewed Ads in this version, the 
      profile was created on 16th April)
   2. Upgrade to the latest beta version 0.64.72
   3. Navigate to `brave://rewards/ `
   4. Observe that `Ads` switch is in OFF state
   5. Click on BAT logo in the URL bar
   6. Verify that Enable Ads notification was shown
   7. Click on `Turn On Ads` button in the notification

## Actual result:

Ads switch is not getting turned ON after clicking on `Turn On Ads` in the notification

Beta
![Ads issue_Ads switch is turned off](https://user-images.githubusercontent.com/38657976/57323807-182eea80-7124-11e9-9133-3e566e0a9b40.gif)

Dev channel:

![Dev profile - Ads switch OFF](https://user-images.githubusercontent.com/38657976/57399695-652bc300-71ef-11e9-9b0f-cf6cc3d5b967.gif)

## Expected result:
After upgrade Ads switch should not be turned OFF

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.64.72 Chromium: 74.0.3729.131 (Official Build) beta (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.523

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @tmancey

**Comment by LaurenWags** [comment]
cc @rebron

**Comment by LaurenWags** [comment]
Reproduced with STR from description. However, I also tried the following STR and did not reproduce:
Clean profile with 0.63.55 (release version)
Enable Rewards
Close 0.63.55
Rename profile to be for Beta
Launch with 0.64.72.
Ads are not off, there is no notification to try Ads

**Comment by LaurenWags** [comment]
@GeetaSarvadnya I tried reproducing on release channel with the following STR and could not. Could you try as well?
Clean profile 0.63.55 (current release version)
Enable Rewards, ensure Ads are enabled.
Close 0.63.55.
Update via `test` channel to 0.64.73
Verify that when 0.64.73 is launched Rewards are enabled, Ads are enabled. There is no notification to try Ads.


Brave | 0.64.73 Chromium: 74.0.3729.131 (Official Build) (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

**Comment by GeetaSarvadnya** [comment]
The issue is reproducible on Dev Channel below version. All profiles are brand new launched brave from desktop setup icon

1.    Dev 0.64.36 ->View an Ad->Go to About Brave (0.66.60)->Click on `Relaunch` –Reproduced
2.    Dev 0.63.11 ->View an Ad->Go to About Brave (0.66.60)->Click on `Relaunch` –Reproduced
3.    Dev 0.65.73 ->View an Ad->Go to About Brave (0.66.60)->Click on `Relaunch` –NOT Reproduced

Not Reproducible on Release channel:

1.	Release 0.63.55 ->View an Ad->Go to About Brave (0.64.74)->Click on `Relaunch` –NOT Reproduced

**Comment by GeetaSarvadnya** [comment]
Further investigation on the issue. The issue is not reproducible on the higher versions. The issue is reproducible only in the lower versions

1. Nightly(0.67.2)->View an Ad->Upgrade to latest version 0.67.15->Not Reproducible
2. Dev(0.65.85)->View an Ad->Upgrade to latest version 0.66.61->Not Reproducible
3. Beta(0.64.67)->View an Ad->Upgrade to latest version 0.65.88->Not Reproducible

**Comment by LaurenWags** [comment]
Release Channel tests:
1. 0.61.52 --> enable Rewards, Ads not available. Update to 0.64.75. Get notification to try Ads and Ads are toggled off as expected.
2. 0.62.51 --> enable Rewards, Ads not available. Update to 0.64.75. Get notification to try Ads and Ads are toggled off as expected.
3. 0.63.48 --> Enable Rewards, View Ad. Update to 0.64.75. Ads still enabled after update, no notification to try Ads. Works as expected.
4. 0.63.55 --> Enable Rewards, View Ad. Update to 0.64.75. Ads still enabled after update, no notification to try Ads. Works as expected.
Release Channel working as expected in all cases above.

**Comment by rebron** [comment]
Removing from milestone and release blocking label since this doesn't affect release channel.

**Comment by LaurenWags** [comment]
Nightly Channel tests:

1. 0.64.26 --> Enable Rewards. View an Ad. Update to 0.67.63. I get notification to try Ads. However, if I do not dismiss this notification and navigate to brave://rewards, Ads are on after upgrade and notification goes away without interaction from me. Issue as reported half reproduces. Logged #4627 for 'enable Brave Ads' notification. See #4627 for video of issue.
2. 0.65.69 --> Enable Rewards. View an Ad. Update to 0.67.63. Ads still enabled after update, no notification to try Ads. Works as expected (as it did previously as well)
3. 0.66.50 --> Enable Rewards. View an Ad. Update to 0.67.63. Ads still enabled after update, no notification to try Ads. Works as expected (as it did previously as well)

**Comment by LaurenWags** [comment]
Dev Channel tests:
1. 0.63.26 --> Enable Rewards. View an Ad. Update to 0.66.78. ***copy note from Nightly***
2. 0.64.56 --> Enable Rewards. View an Ad. Update to 0.66.78. ***copy note from Nightly***
3. 0.65.71 --> Enable Rewards. View an Ad. Update to 0.66.78. Ads still enabled after update, no notification to try Ads. Works as expected as it did previously.
4. 0.65.85 --> Enable Rewards. View an Ad. Update to 0.66.78. Ads still enabled after update, no notification to try Ads. Works as expected as it did previously.
5. 0.66.58 --> Enable Rewards. View an Ad. Update to 0.66.78. Ads still enabled after update, no notification to try Ads. Works as expected as it did previously.
6. 0.66.77 --> Enable Rewards. View an Ad. Update to 0.66.78. Ads still enabled after update, no notification to try Ads. Works as expected as it did previously.

Also tested Ads off status prior to upgrade:
1. 0.63.26 --> Enable Rewards. Disable Ads only. Update to 0.66.78. Ads toggle still off after update. No notification to enable ads is displayed. Works as expected.
2. 0.64.56 --> Enable Rewards. Disable Ads only. Update to 0.66.78. Ads toggle still off after update. No notification to enable ads is displayed. Works as expected.
3. 0.65.71 --> Enable Rewards. Disable Ads only. Update to 0.66.78. Ads toggle still off after update. No notification to enable ads is displayed. Works as expected.
4. 0.65.85 --> Enable Rewards. Disable Ads only. Update to 0.66.78. Ads toggle still off after update. No notification to enable ads is displayed. Works as expected.
5. 0.66.58 --> Enable Rewards. Disable Ads only. Update to 0.66.78. Ads toggle still off after update. No notification to enable ads is displayed. Works as expected.
6. 0.66.77 --> Enable Rewards. Disable Ads only. Update to 0.66.78. Ads toggle still off after update. No notification to enable ads is displayed. Works as expected.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.65.114 Chromium: 75.0.3770.38 (Official Build) (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

Release Channel tests:

1. 0.61.52 --> enable Rewards, Ads not available. Update to 0.65.114 on `test` channel. Get notification to try Ads. Don't dismiss notification. Navigate to brave://rewards in a new tab. Ads are toggled off. Notification remains until you dismiss manually. Works as expected (as it did previously).
2. 0.62.51 --> enable Rewards, Ads not available. Update to 0.65.114 on `test` channel. Get notification to try Ads. Don't dismiss notification. Navigate to brave://rewards in a new tab. Ads are toggled off. Notification remains until you dismiss manually. Works as expected (as it did previously).
3. 0.63.48 --> Enable Rewards, View Ad. Update to 0.65.114 on `test` channel. Ads still enabled after update, no notification to try Ads. Works as expected (as it did previously).
4. 0.63.55 --> Enable Rewards, View Ad. Update to 0.65.114 on `test` channel. Ads still enabled after update, no notification to try Ads. Works as expected (as it did previously).
5. 0.64.75 --> Enable Rewards, View Ad. Update to 0.65.114 on `test` channel. Ads still enabled after update, no notification to try Ads. Works as expected (as it did previously).
6. 0.64.76 --> Enable Rewards, View Ad. Update to 0.65.114 on `test` channel. Ads still enabled after update, no notification to try Ads. Works as expected (as it did previously).
7. 0.64.77 --> Enable Rewards, View Ad. Update to 0.65.114 on `test` channel. Ads still enabled after update, no notification to try Ads. Works as expected (as it did previously).

Also tested Ads off status prior to upgrade:
1. 0.63.48 --> Enable Rewards, Disable Ads only. Update to 0.65.114 on `test` channel. Ads toggle still off after update. No notification to enable ads is displayed. Works as expected.
2. 0.63.55 --> Enable Rewards, Disable Ads only. Update to 0.65.114 on `test` channel. Ads toggle still off after update. No notification to enable ads is displayed. Works as expected.
3. 0.64.75 --> Enable Rewards, Disable Ads only. Update to 0.65.114 on `test` channel. Ads toggle still off after update. No notification to enable ads is displayed. Works as expected.
4. 0.64.76 --> Enable Rewards, Disable Ads only. Update to 0.65.114 on `test` channel. Ads toggle still off after update. No notification to enable ads is displayed. Works as expected.
5. 0.64.77 --> Enable Rewards, Disable Ads only. Update to 0.65.114 on `test` channel. Ads toggle still off after update. No notification to enable ads is displayed. Works as expected.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.65.116 Chromium: 75.0.3770.38 (Official Build) (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the scenarios which @LaurenWags mentioned above
