### ISSUE TITLE
Disable safebrowsing download protection 

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#4341]
Safebrowsing download protection (not browsing protection) should be disabled until we find a way to prevent it from sending URLs to a remote service.

See https://feeding.cloud.geek.nz/posts/how-safe-browsing-works-in-firefox/ for instance

**Comment by diracdeltas** [comment]
Related: #4335 (for just Tor, not normal mode)

**Comment by diracdeltas** [comment]
cc @fmarier

**Comment by fmarier** [comment]
Test plan is the first part of what is mentioned in the PR:

> To test that remote lookups are no longer done, go to https://testsafebrosing.appspot.com and verify that none of the Download Warnings files get blocked.

The second part can't really be tested without making a custom build :(

**Comment by btlechowski** [comment]
@fmarier `https://testsafebrosing.appspot.com/` gives me 404. The test plan needs to be updated.

**Comment by tomlowenthal** [comment]
@btlechowski `https://testsafebrowsing.appspot.com` works fine for me.

**Comment by fmarier** [comment]
Sorry for the typo, I've fixed it in https://github.com/brave/brave-browser/issues/4341#issuecomment-502328316.
