### ISSUE TITLE
Rewards extension icon does not respond to clicks

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#4344]
## Description 
When using the browser, a LARGE number of notifications is shown:
<img width="119" alt="Screen Shot 2019-05-08 at 12 29 17 AM" src="https://user-images.githubusercontent.com/4733304/57358313-05b7af80-712a-11e9-876d-f83743fcdcd4.png">

However, clicking the icon does nothing (nothing logged to stdout, or background page, etc)

When inspecting using the task manager, a large % of CPU is being used:
<img width="740" alt="Screen Shot 2019-05-08 at 12 29 37 AM" src="https://user-images.githubusercontent.com/4733304/57358361-1f58f700-712a-11e9-8a94-3915ba67042b.png">

## Steps to Reproduce
Unknown - but @petemill and I both are experiencing this

## Reproduces how often: 
100% with my profile

## Brave version (brave://version info)

Brave | 0.67.2 Chromium: 74.0.3729.131 (Official Build) nightly(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? unknown
- Can you reproduce this issue with the beta channel? unknown
- Can you reproduce this issue with the dev channel? unknown
- Can you reproduce this issue with the nightly channel? Y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N
- Does the issue resolve itself when disabling Brave Rewards? N
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by jsecretan** [comment]
Important to note in this is that it pegs CPU at a 100% when this happens, so actually much worse than it initially seemed.

**Comment by bsclifton** [comment]
Marked as `QA/No` because this might be tricky to test

However, @petemill and I both have profiles where this happens and can try to share steps to force this to happen (manually editing files)
