### ISSUE TITLE
Add support for Twitter tips

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#4346]
Adds support for Twitter tips, as described in https://docs.google.com/document/d/1OlRWQ1Ksqyt6XT5N0_k503sRP-7clEthDFG1BXeZI5E

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.107 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2195
