### ISSUE TITLE
Consider adding overseas territories as part of supported Brave Ads regions

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#4347]
## Description 

Consider adding overseas territories as part of supported region

cc @tmancey @jsecretan @lukemulks

**Comment by GeetaSarvadnya** [comment]
1+ https://community.brave.com/t/no-ads-shown-at-all/58611/15

**Comment by Jeshii** [comment]
Need this in Japan!

**Comment by GeetaSarvadnya** [comment]
1+ https://community.brave.com/t/did-you-forget-us-territories/62855/2

**Comment by eljuno** [comment]
+1 from communityfor New Caledonia (France)

https://community.brave.com/t/no-ads-in-new-caledonia/64539?u=eljuno

**Comment by GeetaSarvadnya** [comment]
+1 from community US territory (Puerto Rico)

https://community.brave.com/t/ads-enabled-but-not-earning-bat/66148/17

**Comment by jwchong** [comment]
Consider adding International Ads. If not, please show a message to indicate that the user region is not supported, to avoid confusion from users expecting to earn BAT.

**Comment by tmancey** [comment]
@jwchong You should see a message along the lines of "Ads are not supported in your region" on the chrome://rewards/ page. Thanks

**Comment by jwchong** [comment]
@tmancey Please refer to below screenshots. I did not see "Ads are not supported in your region" anywhere, and I did not receive any BAT after 1 month usage (few hours usage daily).

Another question is, do we receive BAT for using iOS Brave app?

<img width="1060" alt="Screenshot 2019-09-25 at 11 12 43 PM" src="https://user-images.githubusercontent.com/24342851/65615035-45a10580-dfeb-11e9-9e09-e7de02457d34.png">
<img width="1059" alt="Screenshot 2019-09-25 at 11 13 05 PM" src="https://user-images.githubusercontent.com/24342851/65615036-45a10580-dfeb-11e9-8f62-7da87d526e7e.png">

Thanks.

**Comment by tmancey** [comment]
Brave rewards is coming to iOS, with regards to you not receiving any BAT could you please let me know your region so we can investigate further? Thanks

**Comment by jwchong** [comment]
I am in Malaysia.

**Comment by eljuno** [comment]
Covered here #7817?

**Comment by tmancey** [comment]
Closing issue as a duplicate of #7817

**Comment by GeetaSarvadnya** [comment]
@tmancey Sound good. Thanks for referencing the issue.
