### ISSUE TITLE
Custom adblock rules should allow cosmetic filters 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4348]
## Test plan
See https://github.com/brave/brave-core/pull/4700

## Description 

Custom adblock rules doesn't work

## Steps to Reproduce

   1. Install 0.64.x  build
   2. Add a custom rule for a site in `brave://adblock` 
   3. Visit the page for which the custom rule was added, doesn't block
[Detailed STR on https://github.com/brave/brave-core/pull/3121]

## Actual result:

Custom adblock rule doesn't work. Element is still loaded after adding the rule

## Expected result:
Should block elements based on custom rule

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.64.72 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?
N/A
- Can you reproduce this issue with the beta channel?
Yes
- Can you reproduce this issue with the dev channel?
Yes
- Can you reproduce this issue with the nightly channel?
Yes
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
N/A
- Does the issue resolve itself when disabling Brave Rewards?
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A
## Miscellaneous Information:

Context menu CSS blocker works fine but isn't always blocking the right element.
This didnt work on muon as well https://github.com/brave/browser-laptop/issues/12308
cc: @emerick

**Comment by rebron** [comment]
cc: @Snuupy can you take a look?

**Comment by Brave-Matt** [comment]
+1 also encountering this

**Comment by emerick** [comment]
@srirambv Can you provide one or more sample rules that don't work and/or screenshots?

**Comment by srirambv** [comment]
@emerick Here's the screenshot on latest nightly. I've added the custom adblock rule `##.header-ad` using element class name. Even after adding the rule and clean reload of the page/relaunch of browser the ad doesn't get blocked. 

![Screenshot from 2019-05-27 13-19-38](https://user-images.githubusercontent.com/17010094/58432787-28324e00-8082-11e9-929a-c960a5a61dbc.png)
![Screenshot from 2019-05-27 13-19-43](https://user-images.githubusercontent.com/17010094/58432788-28324e00-8082-11e9-8362-11d740747aa7.png)

Brave | 0.67.62 Chromium: 75.0.3770.38 (Official Build)nightly (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Linux

cc: @snyderp

**Comment by bbondy** [comment]
I think maybe the title should say custom adblock filters should allow you to add cosmetic filters?

**Comment by tbergeron** [comment]
So the way I understand it, there's currently NO way of blocking any custom element using UI nor the custom filters in brave://adblock right?

If you need another example, just try blocking ANYTHING on reddit. It just don't work at all.

I tried:
reddit.com##.promotedlink
reddit.com#?#div.promotedlink
reddit.com#?#.size-compact.Post:-abp-has([class*=promoted])

Nothing works here.

Version 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit) on Linux.

**Comment by bsclifton** [comment]
@tbergeron that is correct - there is currently no way to block UI elements

@Snuupy is working through several issues related to UI element blocking which are tracked here:
https://github.com/brave/brave-browser/projects/21

**Comment by srirambv** [comment]
cc: @ryanbr

**Comment by snyderp** [comment]
This is not really in @ryanbr's purview at the moment, since we don't have the ability to apply cosmetic filters at all, and @ryanbr is working on improving issues with existing adblocking capabilities.

Hopefully we'll have this worked out over the summer though, with @Snuupy 's work or someone else who will be joining us for the summer

**Comment by petemill** [comment]
Fixed via https://github.com/brave/brave-core/pull/3121

**Comment by btlechowski** [comment]
I am still able to repro the issue. I cannot block elements through `brave://adblock`
cc @srirambv can you quickly recheck this one?

Steps used:
1. Clean install
2. Go to `http://reddit.com/`
3. Disable shields
4. Go to `brave://adblock`
5. Add rule `##.promotedlink` or `reddit.com##.promotedlink`

Not Blocking through `Block element by selector` works as expected.

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

**Comment by srirambv** [comment]
@btlechowski  verified custom rules are not blocking elements

**Comment by bsclifton** [comment]
I don't think this issue was actually addressed with https://github.com/brave/brave-core/pull/3121

This issue is covering the brave://adblock page and being able to add cosmetic filters there

Re-opening and removing milestone

**Comment by yousefamar** [comment]
After scratching my head over why my filters weren't working, I finally found this issue. It looks like the project this issue was added to (https://github.com/brave/brave-browser/projects/21) has been closed. Does this mean that there are no plans to make the box in `brave://adblock` do anything? If so, shouldn't it be removed so others can avoid the confusion I went through? And does this mean that the only way to add custom filters is by installing a 3rd party extension?

**Comment by snyderp** [comment]
@yousefamar currently that field works for network rules, not cosmetic rules.  However, once this lands you can enable cosmetic rules behind a flag too

https://github.com/brave/brave-core/pull/3303

After that gets tested we will start exploring ways we can enable cosmetic blocking by default

**Comment by bsclifton** [comment]
Updated to 1.7 because https://github.com/brave/brave-core/pull/4772 hasn't been merged (yet). Updating the milestone back to 1.6 is in the post-merge checklist for uplifts

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.7.82 Chromium: 80.0.3987.162 (Official Build) dev (64-bit)
-- | --
Revision | f2c5dd6138153bb0658091205bd1a1717f16081a-refs/branch-heads/3987@{#1034}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified test plan from brave/brave-core#4700
- Verified test plan from brave/brave-core#3121
- Verified custom rules work and block elements correctly 
- Verified removing custom rules work as expected and blocked element is unblocked
