### ISSUE TITLE
Built-in Extensions: Could You Use `"persistent": false` For Better Performance?

### ISSUE THREAD

**Issue by ilyaigpetrov** [brave/brave-browser#4350]
I'm slightly concerned about Brave's performance in regards of memory consumption.  
In the Task Manager I've found:
- The `Bat Ledger Service` (86mb) which [can't](https://github.com/brave/brave-browser/issues/3436#issuecomment-471427854) be currently switched off.
- `Extension: Brave` (94mb) (`chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/manifest.json`, [sources](https://github.com/brave/brave-core/tree/master/components/brave_extension/extension/brave_extension)).

After analyzing the Brave's extension sources I have revealed that it hypothetically can be converted to an impersistent version:
```json
  "background": {
    "scripts": ["out/brave_extension_background.bundle.js"],
    "persistent": false
  },
``` 
This version hypothetically can be unloaded from memory when user doesn't interact with the browser.

It's hard for me to test if conversion is possible so my question is:  
__Could you convert some of Brave's built-in extensions to impersistent versions__? (e.g., pdf extension is a good candidate, this brave extension, etc.).

**Comment by petemill** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/6479
