### ISSUE TITLE
No visual confirmation that a verified publisher check is done in rewards panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4351]
## Description 

No visual confirmation that a verified publisher check is done in rewards panel

## Steps to Reproduce

   1. Install 0.64.x
   2. Visit any site and open rewards panel
   3. Click on `Check Again` next to the publisher name
   4. There is no visual confirmation that a check is completed once the spinner is completed the check

## Actual result:

No visual confirmation that a check is completed once the spinner is completed the check

## Expected result:
Should show a `Completed` or `Check complete` message once the spinner is completed the check

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.64.72 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?
N/A
- Can you reproduce this issue with the beta channel?
Yes
- Can you reproduce this issue with the dev channel?
Yes
- Can you reproduce this issue with the nightly channel?
Yes
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
N/A
- Does the issue resolve itself when disabling Brave Rewards?
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A
## Miscellaneous Information:

cc: @NejcZdovc  please change priority if needed

**Comment by jasonrsadler** [comment]
@mandar-brave What text should we display?

**Comment by mandar-brave** [comment]
If success, the rewards verified icon should show up.
if failure, the check again button should continue to stay.

I don't believe there is a "failure" message necessary.

@jenn-rhim @alexwykoff

**Comment by alexwykoff** [comment]
Plan of record is to display an icon as well as text to be clearer about success. 

<img width="531" alt="Screen Shot 2019-05-16 at 11 20 10 AM" src="https://user-images.githubusercontent.com/1434040/57870826-84b58380-77cd-11e9-9d31-49e09d975565.png">

**Comment by alexwykoff** [comment]
Conferred with design and frontend dev, the agreed flow is here : 
https://github.com/brave/brave-browser/issues/4047#issuecomment-493239615

**Comment by alexwykoff** [comment]
After conferring with design & dev, this is the agreed solution: 
<img width="1046" alt="Screen Shot 2019-05-16 at 4 32 12 PM" src="https://user-images.githubusercontent.com/1434040/57940232-a710d500-7891-11e9-830a-37620e7d1861.png">

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.106 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2491
gif of when site is verified after checking:
![4351](https://user-images.githubusercontent.com/28145373/61002760-456c6480-a330-11e9-9b87-1ac22203772a.gif)

gif of when site is not verified after checking:
![4351-unverified](https://user-images.githubusercontent.com/28145373/61002751-41d8dd80-a330-11e9-985f-12e4891e557d.gif)
