### ISSUE TITLE
npm run init issue

### ISSUE THREAD

**Issue by drbree82** [brave/brave-browser#4357]
## Description 
Getting the following output from npm run init
`Unrecognized arch machine: arm64`

I'm building for a HP Envy x2 with a Snapdragon 835

Logs as follows
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'init'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.2.0
4 verbose run-script [ 'preinit', 'init', 'postinit' ]
5 info lifecycle brave@0.67.1~preinit: brave@0.67.1
6 info lifecycle brave@0.67.1~init: brave@0.67.1
7 verbose lifecycle brave@0.67.1~init: unsafe-perm in lifecycle true
8 verbose lifecycle brave@0.67.1~init: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\flrgx\brv\brave-browser\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\SysGCC\arm-eabi\bin;C:\Program Files (x86)\Meson\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\flrgx\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\flrgx\AppData\Local\Programs\Python\Python37-32\;C:\Users\flrgx\AppData\Local\Microsoft\WindowsApps;;C:\Users\flrgx\AppData\Local\Programs\Fiddler;C:\Users\flrgx\AppData\Roaming\npm
9 verbose lifecycle brave@0.67.1~init: CWD: C:\Users\flrgx\brv\brave-browser
10 silly lifecycle brave@0.67.1~init: Args: [ '/d /s /c', 'node ./scripts/sync.js --init' ]
11 silly lifecycle brave@0.67.1~init: Returned: code: 1  signal: null
12 info lifecycle brave@0.67.1~init: Failed to exec init script
13 verbose stack Error: brave@0.67.1 init: `node ./scripts/sync.js --init`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:196:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:196:13)
13 verbose stack     at maybeClose (internal/child_process.js:1011:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
14 verbose pkgid brave@0.67.1
15 verbose cwd C:\Users\flrgx\brv\brave-browser
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "init"
18 verbose node v12.2.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error brave@0.67.1 init: `node ./scripts/sync.js --init`
22 error Exit status 1
23 error Failed at the brave@0.67.1 init script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by bridiver** [comment]
this is an upstream chromium bug - see https://groups.google.com/a/chromium.org/forum/#!topic/chromium-discuss/M7MPEeu4kFA
