### ISSUE TITLE
Enable sync on Android (when compiling Android using brave-core)

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#4365]
see https://github.com/brave/brave-browser/pull/4327/files#diff-f7bf2b665273dfa66ffa4ad7c0a52bb9R141

**Comment by HennyBro** [comment]
I think it has been enabled now. I was able to create my second sync chain ever with Brave! The first one was different to the second one and much easier to set up, ironically. But now it seems to work fine!

**Comment by bsclifton** [comment]
@bridiver maybe you can help clarify here - but this issue is specifically capturing _enabling of sync in brave-core_ when compiling for Android, right? (as part of the move for Android to use this same repository)
