### ISSUE TITLE
No menu item for Open a Private Window with Tor

### ISSUE THREAD

**Issue by tagawa** [brave/brave-browser#4369]
## Steps to Reproduce

   1. Open the `File` menu.

## Actual result:
There is no `Open a Private Window with Tor` item.

![no-private-window-with-tor-in-brave](https://user-images.githubusercontent.com/94173/57424488-679a1700-7207-11e9-9b88-2c91a5956ea5.jpg)

Opening a regular private window shows the following message:

  ```Open a Private Window with Tor from the menu, or with ⌥⌘N. ```

Note that `⌥⌘N` works, and right-clicking on links does show an `Open a Private Window with Tor` item in the context menu.

## Expected result:
There should be an `Open a Private Window with Tor` item in the `File` menu. 

## Reproduces how often: 

All the time.

## Brave version (brave://version info)

Brave 0.63.55; macOS 10.14.4
See below for full version info.

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Full version info:

Brave | 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X
JavaScript | V8 7.4.288.26
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=fill-on-account-select,NewExtensionUpdaterService,DesktopPWAWindowing --disable-features=AutofillServerCommunication,AutofillSaveCardSignInAfterLocalSave,NetworkService,UnifiedConsent,DefaultEnableOopRasterization,AudioServiceOutOfProcess --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/daniel-standard/Library/Application Support/BraveSoftware/Brave-Browser/Default
Variations | c134752e-f685ead32c707b42-dcf7018a411b6d4e-3f4a17dfd01ab0d3-5ac89438927cedd-3f4a17df16e0dd70-3f4a17dfba11b117-5b05287a4b8c3f4-3f4a17dfb3888d8d-afba0f918f029c91-3f4a17df61832c80-3f4a17dfcc20827f-77c422c9853922b-3f4a17df7038b844-3f4a17df9ca1387e-3f4a17df1c752ce9-1c752ce9776de70c-e0278d3ded9149a9-3f4a17df34d450b1-3f4a17df31362330-3f4a17dfc70841c8-a256700714bdbe54-e8c7a65bd8343fa3-3f4a17dfb517d646-3f4a17df8ee5ed19-c3125ea274658432-fa79b94c4f9b5d89-3f4a17dfc36cdb78-3f4a17df9e201a2b-3f4a17df5274eb09-3f4a17dfd6d4ee9a-3f4a17dfceff87ec-3f4a17dfdac832a5-3f4a17df44827ee5-3f4a17df332a4d9b-8e8e4a2b6a116980-3f4a17df3f79ac13-3d47f4f48f1e27f-3f4a17df5485fc4d-3f4a17df93731dca-ba4d7bd29b4c4257-3f4a17df43f62d3b-3f4a17df165e16d1-3f4a17df9e5c75f1-30e1b12b2594bdf4-3f4a17df6fa07eb4-7282ca762981bcb4-3f4a17df5139837c-3f4a17df4934552d-3f4a17df7f8176d9-3f4a17df23a898eb-fc93cf747a5ba892-3f4a17dfd1cd70a5-3f4a17df4ea303a6-3f4a17dfac8d4708-5460eccbb19465ab-b19465ab6e6e0c7e-3f17a7d895876445-2b71ffe42b33233e-881ca6c94da5ae82-3f4a17df56302f8c-2f882e70b2612322-8a9180b23dba712-a2d707c6ad6d27cc-85d38e8dcec9a952-9a6c5085f56e0452-3f4a17df8576baf1-3f4a17dfd00fcbde-3f4a17df930e30f5-3f4a17df9a2f4e5b-9ded16b91354da85-522c33b8494d8760-3f4a17dff9e5da91-508355f5fcdd9ed9-fcdd9ed985963571-85963571b0ea13bc-3f4a17df47a2af3f-3f4a17df94e68624-803f8fc4cc73f8a1-3f4a17dfb4e8892d-a2d707c67e91b7bd-c6da37cb6204e469-3f4a17df41ddf744-c78ce173

**Comment by simonhong** [comment]
Hi @tagawa :)
This was fixed some days ago (https://github.com/brave/brave-core/pull/2373) and it is in dev channel.
Thanks!

**Comment by tagawa** [comment]
That's great to hear - thanks @simonhong
