### ISSUE TITLE
Brave npm start not working. Calling_exit

### ISSUE THREAD

**Issue by XtreemSolution** [brave/brave-browser#4370]
## Description 

When I'm trying to install brave via "npm start" it produce me an error

## Steps to Reproduce

   1. Follow these instructions: https://github.com/brave/brave-browser/wiki/Linux-Development-Environment.
   2. git clone git@github.com:brave/brave-browser.git
   3. cd brave-browser
   4. npm install
   5. npm run init
   6. npm run build
   7. npm start -- Here I got this issue 

## Actual result:
![image](https://user-images.githubusercontent.com/8287110/57427537-f9bf1100-7241-11e9-9c8d-217364aa8277.png)

[end of stack trace]
Calling _exit(1). Core file will not be generated.
null
null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave@0.66.27 start: `node ./scripts/commands.js start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the brave@0.66.27 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

## Expected result:
This is final command so it should open the browser

**Comment by srirambv** [comment]
Have you installed the build dependencies as mentioned in the [Linux guide](https://github.com/brave/brave-browser/wiki/Linux-Development-Environment#install-additional-build-dependencies) ?

**Comment by XtreemSolution** [comment]
Yes, I have install build dependencies as mentioned in the Linux Guide.

**Comment by XtreemSolution** [comment]
It was my mistake. solve now
