### ISSUE TITLE
Brave autoplay blocker is inconsistent and auto plays videos sometimes

### ISSUE THREAD

**Issue by pavankjadda** [brave/brave-browser#4371]
## Description 
Brave autoplay blocker is inconsistent and auto plays videos sometimes

## Steps to Reproduce

   1. Open website [Zdnet](https://www.zdnet.com/topic/prepare-for-serverless-computing/)
   2. If brave stops autoplay, try it in a new tab or window. 4/10 times it plays videos
 

## Actual result:
Brave should block autoplay by default at all times

## Expected result:
Brave not blocking auto play always

## Reproduces how often: 
3-4 times out of 10

## Brave version (brave://version info)
Version 0.63.55 in macOS 10.14.4

## Version/Channel Information:
Have not tried with dev channels

- Can you reproduce this issue with the current release?
 **Yes**
- Can you reproduce this issue with the beta channel?
 **Have not tried**
- Can you reproduce this issue with the dev channel? 
**Have not tried**
- Can you reproduce this issue with the nightly channel?
 **Have not tried**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
**No**
- Does the issue resolve itself when disabling Brave Rewards?
 **No**
- Is the issue reproducible on the latest version of Chrome? 
**Chrome does not offer this feature**

**Comment by onmyouji** [comment]
On my system, the autoplay blocker doesn't work on this site: https://globalnews.ca/news/5342136/us-visas-social-media/

Windows 10 Home Version 1803 64-bit
Brave Version 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)

**Comment by AEverstone** [comment]
Autoplay is turned permanently to _Allow_ for me on some sites, such as YouTube. It is very inconsistent on sites where it can be turned to _Block_.
I'm using this version on Arch:  1:1.7.98-1

**Comment by warwickmm** [comment]
I just upgraded to 1.18.70 on Linux and autoplay blocking is now working for me.

Version 1.18.70 Chromium: 87.0.4280.101 (Official Build) unknown (64-bit)

**Comment by Golutazem** [comment]
Blocking autoplay fails on
Version 1.19.84 Chromium: 88.0.4324.87
Try BitChute as a test.
