### ISSUE TITLE
Brave get laggy on large web pages

### ISSUE THREAD

**Issue by frontendmonster** [brave/brave-browser#4378]
## Description 
Brave get laggy on large web pages.

## Steps to Reproduce

   1. Visit [Ecma-262](https://www.ecma-international.org/ecma-262/6.0/index.html)
   2. Try to scroll and navigate around.

## Actual result:
Here is a comparison with chromium
![gif](https://media.giphy.com/media/kDZOIIvJ4R87DjmNZz/giphy.gif)

## Expected result:
DOM get render smoothly.

## Brave version
74.0.63.55

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **No**
- Does the issue resolve itself when disabling Brave Rewards? **No**
- Is the issue reproducible on the latest version of Chrome? **No**

## Miscellaneous Information:
OS: GNU/Linux Manjaro

**Comment by srirambv** [comment]
Have you tried disabling hardware acceleration and checked? The option is available under advanced settings

**Comment by frontendmonster** [comment]
Fixed by updating to 75.0.65.121
