### ISSUE TITLE
[feature request] auto-upgrade mixed content

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#4381]
Chrome has an experiment to auto-upgrade various types of mixed content: https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/ZJxkCJq5zo4/4sSMVZzBAwAJ, https://docs.google.com/document/d/1dp-kuN25wnEbMPNWBxM8LvOjyeydWpXPklNnGcsWK1o/edit#. 

This is a good candidate to consider for enabling by default in Brave

Some considerations:
* Sites which serve different content over HTTPS vs HTTP can cause a confusing situation in which a site experiencing auto-upgrades is not simply broken but just wrong. A contrived example: forbes used to serve their regular site on http://forbes.com and their SecureDrop landing page on https://forbes.com. If a site iframed forbes.com, it would be totally different after the auto-upgrade.
* At what point in the request cycle should HTTPS Everywhere upgrades happen? Currently I think they might happen after mixed content blocking, which is non-ideal. Ideally I think the order should be `HTTPS-E upgrades -> mixed content auto-upgrade -> any content blocking`.

**Comment by jonathanKingston** [comment]
Chrome's [current plan](https://twitter.com/estark37/status/1225437058518282240) is to roll out videos and audio in Chrome 80 and measure breakage such that images would be considered in 81, this suggests Brave could match that timeline or even go first.

I'll take a look at the upgrading before HTTPS Everywhere and the current ordering.

**Comment by estark37** [comment]
Yep, it would be great to see Brave ship this as well. Note that we're also planning to ship a "Not Secure" omnibox warning for mixed images in M80, in hopes of driving sites to fix before autoupgrading+blocking in 81.

**Comment by jonathanKingston** [comment]
> Yep, it would be great to see Brave ship this as well. Note that we're also planning to ship a "Not Secure" omnibox warning for mixed images in M80, in hopes of driving sites to fix before autoupgrading+blocking in 81.

Enabling this warning also applies to insecure forms and I can't see a flag to upgrade forms, is that something you have considered?

> chromium --enable-features=AutoupgradeMixedContent --enable-features=PassiveMixedContentWarning https://very.badssl.com/

**Comment by jonathanKingston** [comment]
I just confirmed Chromium code `MixedContentChecker::ShouldAutoupgrade()` does get called before: `OnBeforeURLRequest_HttpsePreFileWork()`.
This means mixed upgrades from the HTTPS Everywhere list would no longer have any impact.

**Comment by estark37** [comment]
> > Yep, it would be great to see Brave ship this as well. Note that we're also planning to ship a "Not Secure" omnibox warning for mixed images in M80, in hopes of driving sites to fix before autoupgrading+blocking in 81.
> 
> Enabling this warning also applies to insecure forms and I can't see a flag to upgrade forms, is that something you have considered?

I don't think this should be the case. I can't reproduce on https://mixed-form.badssl.com. very.badssl.com might contain a mixed image as well as a mixed form which is maybe why you're seeing the warning on that page?

> 
> > chromium --enable-features=AutoupgradeMixedContent --enable-features=PassiveMixedContentWarning https://very.badssl.com/

**Comment by jonathanKingston** [comment]
I uploaded a patch which turns on the warning but also upgrades images by default.

I also chose to turn off the URL bar insecure script control which and instead permit controlling an override on a site specific basis:
![image](https://user-images.githubusercontent.com/338988/73982376-02a55600-492c-11ea-8210-34c4d685146f.png)
This certainly could be left to another patch however reading through other bugs it sounded like this was an intended change.

**Comment by diracdeltas** [comment]
> Perhaps the parameter to the field trial for image upgrading got flipped on my profile?

We should be disabling field trials generally as of https://github.com/brave/brave-browser/pull/4551

However, we purposefully enabled the setting to not show EV indicators (https://github.com/brave/brave-core/pull/2471/files#diff-9413752841345e7c426bf4dd82fe7e60R143) but I guess that's no longer necessary since Chrome does it too.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.7.71 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4537
Verified the `http` was upgraded to `https`
Verified page is secured

![image](https://user-images.githubusercontent.com/34715963/77527676-df5b4980-6e8c-11ea-883f-c2daf1bd82ff.png)
