### ISSUE TITLE
A new round of notifications to encourage all users to sign up for Brave rewards and eligible ones for Brave Ads

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#4383]
Create a once a reminder once a month;
- all users that have opted in to BR AND
- are in the regions where we support Ads AND
- have not opted in to Ads

"Brave Ads are available in your region" Action "Turn ON" and has standard close.
Turn ON - turns on Ads
Close - does nothing

After 6 notifications, move frequency of reminders to once every 3 months.

@alexwykoff @NejcZdovc 

@rebron we may want to push this up in to the latest release as soon as we get a PR.

**Comment by alexwykoff** [comment]
in general this makes sense. i do think we should consider an early opt-out for the 'hell no Ads' segment. 

making them frustrated with an ad for ads will just lead to churn. 

@NejcZdovc i'll get cracking on copy and will ask @jenn-rhim for an assist on UX 😄

**Comment by alexwykoff** [comment]
Note : https://github.com/brave/brave-browser/issues/4433 will impact flow for users if it is not fixed before this issue is shipped.

**Comment by mandar-brave** [comment]
@alexwykoff #4433  is not a blocker; we will maximize reach.

Redoing spec;
Two use cases:
1. Notify users that have opted in to BR, turned off Ads, and are in ads regions: We need to find the appropriate string with action "Turn ON" - turn ON will turn on Ads for these users; this is text that was already sent one time and tracked for translation
2. Turn notification toggle ON for every single BAT logo when BR is not turned ON; two use cases;
2.1 Join Rewards flow for BR users that never turned ON - use existing turn ON text
2.2 Turn ON Brave Rewards flow for BR users that had turned it ON but turned off at some point - use existing turn on BR text
2.1 and 2.2 should exist already from current designs.

cc @alexwykoff @NejcZdovc 

@rebron for uplift when ready

**Comment by davidtemkin** [comment]
I read this as us alerting people who have _manually opted out_ of ads (e.g., they enabled Rewards at a time when ads were available in their region, and then manually disabled ads). Is that correct? If so, that particular case is not a go and that case needs to be stripped out. 

We can and should ask people who turned on Rewards before ads were available, and then ads became available. That is a go. But I would think we need a "don't bother me again" option, right? 

@alexwykoff

**Comment by mandar-brave** [comment]
@davidtemkin there is no way today to know if someone turned it ON -> OFF -> ON and at what timeline. Per last chat with @tmancey, we just know Ads = ON or OFF. So very limited scope to manage BAT notification besides mass triggering of it to everyone where Ads = OFF. @tmancey is adding that flag and timeline for switch. 

@tmancey please confirm if i have it wrong.

**Comment by tmancey** [comment]
@mandar-brave This is correct, however reading @davidtemkin reply above the functionality to detect if a user enabled ads and then subsequently disabled ads is not required. Could you please update the  use case, and let me know if a "don't bother me again" option

**Comment by davidtemkin** [comment]
@tmancey are these OS native notifications? If so "don't bother me again" is pretty much a non-starter. So I withdraw the request.

**Comment by tmancey** [comment]
@davidtemkin These notifications are the ones which appear on the Rewards panel

**Comment by davidtemkin** [comment]
ah, got it, @tmancey 

Let's go with simple version regardless and see how it plays. No "don't bother me again" for now

**Comment by jsecretan** [comment]
Not necessary with the addition of the new tab page rewards signup.
