### ISSUE TITLE
Tipping is down "Please try again later"

### ISSUE THREAD

**Issue by brianddk** [brave/brave-browser#4385]
## Description 

The tipping service for the Brave desktop browser seems to be consistently failing as of the submission of this issue.  Attempts to submit issues produce an error suggesting the user try again later.

## Steps to Reproduce

   1. Browse to a verified publisher: https://archive.org
   2. Tip the verified publisher ( 1.0 BAT )
   3. Observe the message indicator on the BAT icon

## Actual result:

![image](https://user-images.githubusercontent.com/5009148/57519503-0e061b00-72e1-11e9-8834-2bc49c133583.png)

## Expected result:

The tips are expected to go through without error.

## Reproduces how often: 

The error has been consistently reproducible for the last few hours.

## Brave version (brave://version info)

Windows OS: Brave Version 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? ***Yes***
- Can you reproduce this issue with the beta channel? ***Yes***
- Can you reproduce this issue with the dev channel? ***Yes***
- Can you reproduce this issue with the nightly channel? ***Unknown***

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? ***No***
- Does the issue resolve itself when disabling Brave Rewards? ***N/A***
- Is the issue reproducible on the latest version of Chrome? ***N/A***

**Comment by Brave-Matt** [comment]
+1 reddit:
https://www.reddit.com/r/brave_browser/comments/bmv4vd/youtube_tipping_is_down_please_try_again_later/

**Comment by brianddk** [comment]
seems to be back on line now.

**Comment by NejcZdovc** [comment]
closing as we had some server problems. Now we should be all good.
