### ISSUE TITLE
Normalize callback should exclude 0% publishers

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#4386]
## Description 

When you have publisher in your AC table that are 0% if normalize happens when you are on rewards page you will see them. 

## Steps to Reproduce

   1. enable rewards
   2. add a lot of publishers to the table so that you will have some publishers that has % 0
   3. open rewards page and make sure that you don't see 0% publishers in AC table
   4. open youtube video and let it run
   5. go back to rewards page
   6. wait there for 20s

## Actual result:

AC list is updated and now you will see 0% publishers in the list

## Expected result:
0% publishers should never be in the table

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.106 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2428
