### ISSUE TITLE
Resolve Ads/Confirmations compiler errors for Android

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#4388]
Resolve Ads/Confirmations compiler errors for Android

**Comment by yrliou** [comment]
Reverted by https://github.com/brave/brave-core/pull/2420

**Comment by NejcZdovc** [comment]
@cezaraugusto what was resolution for this one?

**Comment by tmancey** [comment]
@NejcZdovc the PR was reverted and it was decided we would then work in another branch so this issue is no longer required and will be superseded once Android is finalised.
