### ISSUE TITLE
Add Vimeo support (tip/panel)

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#4391]
In first phase we added support for AC for Vimeo (https://github.com/brave/brave-browser/issues/4017). Now we would like to add support for panel/tip as well. Everything should behave in the same way as is for YT

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.104 Chromium: 75.0.3770.100 (Official Build) dev (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/2247
- Logged https://github.com/brave/brave-browser/issues/5294
![image](https://user-images.githubusercontent.com/38657976/61533304-177ed280-aa4a-11e9-8901-8d45731b435f.png)
