### ISSUE TITLE
Add Tweet button to every Tip panel

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#4393]
Add Tweet button to every single Tip panel as part of the tipping process.
When user has successful tipped and land on the final thank you page, add the Tweet button as an option for user to tweet. 
Button launched Twitter page in a new tab.

@emerick @NejcZdovc

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.107 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2195
* Verified tweet button appeared on thank you banners after tipping regular sites, YT, Twitch, and Twitter. (screenshots in https://github.com/brave/brave-browser/issues/4555#issuecomment-510575690)
* Note, tweet button is only on one-time tip thank you banner currently, not on monthly/recurring tip thank you banners. Confirmed with team this is expected for now.

**Comment by binoyxj** [comment]
The text included as part of the auto-tweet is actually broken. It's having some gibberish text too.

**Comment by LaurenWags** [comment]
@binoyxj You're probably experiencing https://github.com/brave/brave-browser/issues/5229. there's a duplicate user handle and some extra text along with it.

**Comment by binoyxj** [comment]
> @binoyxj You're probably experiencing #5229. there's a duplicate user handle and some extra text along with it.

Yup!

**Comment by LaurenWags** [comment]
thanks for confirming @binoyxj !
