### ISSUE TITLE
WebGL get's blocked by fingerprinting protection

### ISSUE THREAD

**Issue by AcruxCode** [brave/brave-browser#4400]
## Description 
WebGL content get's blocked by fingerprinting protection

## Steps to Reproduce

   1. Set fingerprinting protection to "Device recognition blocked"
   2. Go to [https://get.webgl.org/](https://get.webgl.org/) or [http://vr.ff.com/us/](http://vr.ff.com/us/)

## Actual result:
![Imgur](https://i.imgur.com/TlfnAMs.png)
![Imgur](https://i.imgur.com/AIenu8x.png)

## Expected result:
![Imgur](https://i.imgur.com/rfg2CVE.png)
![Imgur](https://i.imgur.com/X1mERuX.png)

## Brave version (brave://version info)
Brave: `0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)`
OS: `Linux` (Ubuntu 16.04 LTS)
User-Agent: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36`

## Version/Channel Information:

- Can you reproduce this issue with the current release? **Yes**
- Can you reproduce this issue with the beta channel? **Yes**
- Can you reproduce this issue with the dev channel? **N/A**
- Can you reproduce this issue with the nightly channel? **N/A**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **Yes**
- Does the issue resolve itself when disabling Brave Rewards? **No**
- Is the issue reproducible on the latest version of Chrome?  **No**

**Comment by srirambv** [comment]
That's the expected behaviour. If you set it to block and if it works that beats the purpose of blocking it. 

Marking as invalid issue.
