### ISSUE TITLE
theverge.com (among other sites) hang/delay before rendering in Brave

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#4402]
## Description 

I’m wondering if anyone can tell me what causes some sites to have a short “delay” before rendering (and rendering correctly).
For example, theverge.com and overclockers.co.uk both have this behavior (off the top of my head, i believe there are more I’ve encountered) but do load as intended. These sites load _much_ faster in Chrome. In Brave you generally get ~1-3 second delay:

![image](https://user-images.githubusercontent.com/3299098/57554246-c6ee4900-7325-11e9-8865-9206a6a9b171.png)

@snyderp notes the logic at play:
```
<style>.async-hide { opacity: 0 !important} </style>
<script>(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;
h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};
(a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;
})(window,document.documentElement,'async-hide','dataLayer',4000,
{'GTM-54FC4VZ':true});</script>
```
Further, it seems that the script says "Delay render for 4000ms (4s) unless "google optimize" is detected.

## Steps to Reproduce

   1. Visit theverge.com or overclockers.co.uk (for example)
   2. Note the page delay on load before rendering

## Reproduces how often: 

Always

## Version/Channel Information:

This issue occurs in all channels Release - Nightly

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No, but it seems as though the delay may be slightly shortened although it's hard to tell. Regardless, rendering time is still comparatively slow to Chrome and Chrome + uBO which render the site instantly.

## Miscellaneous Information:

User report: https://community.brave.com/t/slow-rendering-https-www-overclockers-co-uk/59075/4

**Comment by bbondy** [comment]
weird, thanks for the report!

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.66.98 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X
