### ISSUE TITLE
Updating from older build doesn't show notification to try Ads

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4404]
## Description 
Found while testing #4224 

After following the STR in above issue and updating to 0.64.74, the Ads panel no longer showed the incorrect error message but I did not receive a notification to try Ads.

## Steps to Reproduce

Scenario 1:
1. Install an older build say (0.58.21)
2. Enable Rewards. ensure ads is not available
3. Upgrade to 0.63.48 or 0.63.55
4. Ads shows sorry not available for your region even if the criteria matches 
5. Update to 0.64.74
6. Ads panel shows toggle (you can enable Ads) but there is no notification alerting you to try ads.

Scenario 2:
1. Install an older build say (0.58.21)
2. Enable Rewards. ensure ads is not available
4. Update to 0.64.74 directly (skipping 0.63.x versions)
5. Ads panel shows toggle (you can enable Ads) but there is no notification alerting you to try ads.

## Actual result:
No notification to alert the user that Ads are now available.

## Expected result:
Notification to try Ads is shown on BAT logo.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.64.74 Chromium: 74.0.3729.131 (Official Build) (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? reproduced with RC build
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @brave/legacy_qa @rebron

**Comment by LaurenWags** [comment]
Also tested scenario 2 with the following versions:
0.59.35 --> 0.64.74, scenario 2 reproduces
0.60.45 --> 0.64.74, scenario 2 does not reproduce
0.61.51 --> 0.64.74, scenario 2 does not reproduce
0.62.51 --> 0.64.74, scenario 2 does not reproduce
0.63.48 --> 0.64.74, scenario 2 does not reproduce
0.63.55 --> 0.64.74, scenario 2 does not reproduce

**Comment by GeetaSarvadnya** [comment]
Scenario 1 is Reproducible on Windows 10 x64:


Brave | 0.64.74 Chromium: 74.0.3729.131 (Official Build) (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.523

**Comment by tmancey** [comment]
@LaurenWags This ticket will be superseded and subsequently fixed by #4383, are you happy for us to close this ticket please?

**Comment by LaurenWags** [comment]
Closing per @tmancey comment above - issue is to be superseded/fixed by https://github.com/brave/brave-browser/issues/4383
