### ISSUE TITLE
Site incompatibility with Shields on: https://www.shortoftheweek.com/

### ISSUE THREAD

**Issue by hugobuddel** [brave/brave-browser#4409]
## Description 
Site incompatibility with Shields on: https://www.shortoftheweek.com/

Movies on https://www.shortoftheweek.com/ do not show. They do play, but are only visible when double clicking on the area where the movie ought to be so it becomes full screen.

## Steps to Reproduce

   1. Go to https://www.shortoftheweek.com/2019/05/10/the-unconditional/
   2. There is a 'rotating square' where the play button should be.
   3. Double click to enter full screen.

## Actual result:
Brave window:
![braveunconditional](https://user-images.githubusercontent.com/1306453/57568787-552d0280-73ec-11e9-9082-90c425313a76.png)

Double clicking shows movie in full screen.

## Expected result:
Chrome window:
![chromeunconditional](https://user-images.githubusercontent.com/1306453/57568788-552d0280-73ec-11e9-89c5-92acdc87d070.png)

Pressing the play button starts the movie.

## Reproduces how often: 
always

## Brave version (brave://version info)

Brave | 0.65.88 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Don't know
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Don't know
- Can you reproduce this issue with the nightly channel? Don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes, thanks!
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No (74.0.3729.131)

**Comment by ryanbr** [comment]
The issue is caused by blocking of 3rd party cookies from what I can see.

**Comment by ryanbr** [comment]
Re-tested this @hugobuddel , seems to play okay now? Can you confirm?

**Comment by hugobuddel** [comment]
Plays nicely now, Version 1.2.30 Chromium: 79.0.3945.79 (Official Build) beta (64-bit), shields up. Thanks for testing @ryanbr . Closing the issue.
