### ISSUE TITLE
SAML/SSO login and Redirects doesn't work

### ISSUE THREAD

**Issue by kid101** [brave/brave-browser#4414]
## Description 
Some of websites work with SAML/SSO authentication and there are automatic redirects. I am unable to login to such sites. some of them are enterprise applications I try to log into.

## Steps to Reproduce

   1.  Login into any website via SSO
   2. redirect not happening
   3.  page is just stuck.

## Expected result:
Should be redirected to the original site. However the page is just stuck, 

## Reproduces how often: 

Easily reproduced. 

## Brave version (brave://version info)

Version 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kid101** [comment]
workaround: Disable the shield for the SSO page.

**Comment by rebron** [comment]
@kid101 Do you have specific example sites where this isn't working? We have this working with other SSO sites.

**Comment by fmarier** [comment]
This looks like it's the same underlying issue as https://github.com/brave/brave-browser/issues/9470.

Closing in favor of the other one which has more details.
