### ISSUE TITLE
Cosmetic filter is not always working

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#4417]
## Test plan
See https://github.com/brave/brave-core/pull/2486

## Description 
For most sites, you can:
1. right click somewhere on site
2. choose `Brave` menu
3. choose `Block element via selector`
4. alert box with selector should show up

Step 4 (the alert) is not always happening. Even if you wait it out. This may be related to the changes made with https://github.com/brave/brave-core/pull/2043

## Steps to Reproduce

   1. Visit https://www.reddit.com/ or https://www.benzworld.org/forums/w126-s-se-sec-sel-sd/ or another site with the problem
   2. Right click on the ad, pick `Block element via selector` (as outlined above)

## Actual result:
Nothing happens

## Expected result:
Should be an input box with selector:
<img width="515" alt="Screen Shot 2019-05-13 at 11 37 26 AM" src="https://user-images.githubusercontent.com/4733304/57645692-ae736e00-7573-11e9-8e5a-df420cb32373.png">

## Reproduces how often: 
100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? haven't tried
- Can you reproduce this issue with the beta channel? haven't tried
- Can you reproduce this issue with the dev channel? y
- Can you reproduce this issue with the nightly channel? y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n
- Does the issue resolve itself when disabling Brave Rewards? n
- Is the issue reproducible on the latest version of Chrome? n

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/2486
Verified pages from the description.

![image](https://user-images.githubusercontent.com/34715963/62166310-ba73fe00-b320-11e9-9f52-1f65efe90b10.png)


![image](https://user-images.githubusercontent.com/34715963/62166292-ae883c00-b320-11e9-9be4-988151daa4d4.png)
