### ISSUE TITLE
CORS Issue 

### ISSUE THREAD

**Issue by rickpreston** [brave/brave-browser#4419]
Looks similar to 2252 but that is Closed.

## Description 
Unable to login to JIRA at `https://<mycompanyname>.atlassian.net` because of CORS issue. 

## Steps to Reproduce
Attempt to login to JIRA. 

## Actual result:
Dev tools console shows this:
`Access to fetch at 'https://mgas.prod.public.atl-paas.net/analytics/event' from origin 'https://<mycompanyname>.atlassian.net' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.`

![image](https://user-images.githubusercontent.com/42553852/57654219-43d52900-7599-11e9-84a2-a850a90306db.png)

## Expected result:
I can login to JIRA.

## Reproduces how often: 
Happens every time. Doesn't happen with other browsers.

## Brave version (brave://version info)

Brave | 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.648

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Unknown
- Can you reproduce this issue with the dev channel? Unknown
- Can you reproduce this issue with the nightly channel? Unknown

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
none

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/ee7cc7d5bdee6f73150e77d6ce31f949151b8009

I did make a change recently which could've caused this. (https://github.com/easylist/easylist/commit/47870cf28615)

**Comment by diracdeltas** [comment]
could be same issue as https://github.com/brave/brave-browser/issues/4396

**Comment by ryanbr** [comment]
Got a sample site and directions to test with @cmanley ?

**Comment by cmanley** [comment]
> Got a sample site and directions to test with @cmanley ?
Unfortunately not because one has to pay for Jira, so you can test it if one of your customers or employees use Jira and you use a Google account to log in.

**Comment by bsclifton** [comment]
@ryanbr I can confirm I run into the issue when signing in w/ my Atlassian account. I think the account is free to create and login to... you just won't be able to use any products.  But that's good enough to reproduce the problem

**Comment by ryanbr** [comment]
Okay, can reproduce it

Getting a lot of XSS issues on the site;
`Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 13. The default protections will be applied.`

![x-xss-protection](https://user-images.githubusercontent.com/1659004/65670514-9ec77280-e099-11e9-991d-fba23fa5e9b7.png)

**Comment by fmarier** [comment]
This is related to Shields' referrer protections. It looks like they use `id.atlassian.com` but the JIRA instances are on `atlassian.net`.

**Comment by bsclifton** [comment]
@fmarier I believe a whitelist update is needed (to the `DEPS` file). I'll re-open the issue until we can sort that out

**Comment by bsclifton** [comment]
Wait - I think I'm wrong about that. Will re-close 😄 It may be part of the ad-block definitions now

**Comment by btlechowski** [comment]
@bsclifton Is this issue `QA/No` or `QA/Yes`?

**Comment by bsclifton** [comment]
@btlechowski would be good to test - if it works on Release channel too, then I think we can remove milestone and put `Release Notes/exclude`. If the whitelist update (which happened to 0.72.x) resolves this, then we can mark as `Release Notes/include`

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.1.5 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

* Reproduced issue using version 0.63.55. Upgraded to 1.1.5 and verified I was able to login without issue.
0.63.55:
<img width="406" alt="Screen Shot 2019-11-19 at 12 50 52 PM" src="https://user-images.githubusercontent.com/28145373/69173089-18457500-0acd-11ea-8c7b-455a7daf4b69.png">
1.1.5:
<img width="1191" alt="Screen Shot 2019-11-19 at 12 56 03 PM" src="https://user-images.githubusercontent.com/28145373/69173096-1c719280-0acd-11ea-86ec-ead4b3290bf3.png">

* Confirmed able to login to Jira/Atlassian on clean profile with 1.1.5 as well.
