### ISSUE TITLE
Stop logging sites to stdout on exit

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#4420]
https://github.com/brave/brave-core/blob/ac766becf4eadaa53a90ba897781878c8a71db82/vendor/bat-native-ledger/src/bat/ledger/internal/media/twitch.cc#L181

Logs all sites visited by user to stdout. 

## Repro Steps:

1. Open Brave Browser using terminal (/Applications/Brave\ Browser\ Nightly.app/Contents/MacOS/Brave\ Browser\ Nightly)
2. Navigate to any site and see that logs of the URL you visited will be printed on the console

## Test Plan
Specified here: https://github.com/brave/brave-core/pull/2435

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.5 x64` using the following build:

Brave | 0.65.113 Chromium: 75.0.3770.38 (Official Build) beta(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

* reproduced the original issue using `0.65.89 Chromium: 74.0.3729.131`
* ensured websites are not being logged in terminal when visited when using normal tabs
* ensured websites are not being logged in terminal when visited when using Tor
* ensured websites are not being logged in terminal when visited when using PB
* ensured websites are not being logged in terminal when visited when using Guest mode

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.65.113 Chromium: 75.0.3770.38 (Official Build) beta(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Linux

* Verified no site info is logged in normal/private/Tor windows
