### ISSUE TITLE
site compatibility issue with crave.ca

### ISSUE THREAD

**Issue by samik-saha** [brave/brave-browser#4422]
## Description 
When I login to this site crave.ca with my account, it shows an error "If you continue to see this error, please ensure you have cookies enabled, and that you are using a supported device and browser."

I have tried disabling shields. Netflix works fine after installing widevine. But crave still does not work.

## Steps to Reproduce
   1. Go to crave.ca
   2. Try to login (I guess you can create a trial account if you don't have one)

## Actual result:

![{2702FCE9-7315-49B1-A700-0FC1974292DE} png](https://user-images.githubusercontent.com/3612424/57661351-7cd0c600-75b8-11e9-9267-a8dfef42b188.jpg)

## Expected result:
Not show the error and log into my account

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 18362.86

## Version/Channel Information:
N/A
- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? Haven't tried
- Is the issue reproducible on the latest version of Chrome? No

**Comment by kjozwiak** [comment]
> Does the issue resolve itself when disabling Brave Shields?

@samik-saha have you tried disabling the Brave shields? Does it fix the issue or do you run into the same problem?

**Comment by samik-saha** [comment]
> > Does the issue resolve itself when disabling Brave Shields?
> 
> @samik-saha have you tried disabling the Brave shields? Does it fix the issue or do you run into the same problem?

@kjozwiak Yes, I have tried that. But the problem persists.

**Comment by samik-saha** [comment]
@kjozwiak Actually when I tried just now, with the shields off, it works!

**Comment by kjozwiak** [comment]
> @kjozwiak Actually when I tried just now, with the shields off, it works!

Awesome 👍You can use that as a workaround for now until we fix this issue so `crave.ca` works with the default shield settings. I moved the issue into the `Web Compat` project board.

**Comment by ryanbr** [comment]
Something is blocking the following url's;
```
https://asset.entpay.9c9media.ca/image-service/version/c:Mjg4Y2EyZTAtYWEzOS00:ZWVjNzIw/image.png
https://asset.entpay.9c9media.ca/image-service/version/c:Nzc4ZmU2NDUtYzFkMi00:NmIxMmY5/image.png
```

Blocking this may cause issues also;
`https://assets.adobedtm.com/launch-EN440f4629250c4a9297e9d4c42afb4b81.min.js`

**Comment by mikepictor** [comment]
I definitely have the same issue, even with the shields turned off.

**Comment by ryanbr** [comment]
Re-checked this, needed a bit of work to get around the geo checks. I've submitted a possible patch, just needing to get reviewed/approved.

https://github.com/brave/adblock-lists/pull/350

**Comment by ryanbr** [comment]
@mikepictor @samik-saha 

Is there any issues with crave.ca anymore? (with shields enabled)

**Comment by samik-saha** [comment]
@ryanbr I still get the same error with shields on. Additionally getting 404 page missing error.
![Screenshot from 2020-06-16 20-18-28](https://user-images.githubusercontent.com/3612424/84840808-955aad80-b00e-11ea-89b9-be2354bd992d.png)

**Comment by ryanbr** [comment]
Interesting, thanks for confirming. Will look into it @samik-saha

**Comment by ryanbr** [comment]
Does Shields affect `crave.ca` @samik-saha ?

**Comment by ryanbr** [comment]
I don't have a login, but tested this page https://www.crave.ca/en/tv-shows/legendary/legendary-trailer-s1

**Comment by samik-saha** [comment]
I am not entirely sure, I no longer have a active subscription. However, the issue appears to be only during login when it redirects to https://account.bellmedia.ca/

**Comment by ryanbr** [comment]
@mikepictor  If you still have an account, does everything work okay with Brave release and `crave.ca`?

**Comment by kjozwiak** [comment]
@ryanbr asked in our **#Canada** Slack channel to see if anyone with a `crave.ca` subscription can give this a go and see if it's working.

**Comment by mikepictor** [comment]
> @mikepictor If you still have an account, does everything work okay with Brave release and `crave.ca`?
Nope

![Crave_-_500](https://user-images.githubusercontent.com/4552747/87577482-f2df2a00-c6a0-11ea-8549-014d36c4d284.png)

**Comment by mikepictor** [comment]
Crave is a bit of a dumpster fire from a technical standpoint though. I place much more of the blame for this on Crave, than I do on Brave. Among other problems, it requires 3rd party cookies to be enabled.

**Comment by kjozwiak** [comment]
@mikepictor does this work for you now? I tried it with my account and it seems to be working with default shields once I've enabled Widevine. Used the following build (assuming it works on release as well):

```
Brave | 1.19.39 Chromium: 87.0.4280.67 (Official Build) nightly (64-bit)
-- | --
Revision | 0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS | Windows 10 OS Version 2009 (Build 19042.630)
```


![image](https://user-images.githubusercontent.com/2602313/100496135-c263ce00-311f-11eb-8f68-dc085622147a.png)

![20201128_021922](https://user-images.githubusercontent.com/2602313/100496217-60f02f00-3120-11eb-9fb5-4f5c0c2b3f5c.jpg)

**Comment by ryanbr** [comment]
Probably safe to close since the crave issue was most likely related to disconnect blocking bellmedia.ca.

**Comment by kjozwiak** [comment]
Sounds good 👍 Going to close this off. @samik-saha if you're still having issues, please re-open a new issue. Thanks for reporting the above BTW!
