### ISSUE TITLE
Remove std::cout logging from ledger twitch file

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#4423]
## Description 

Occasionally, a large log blob will appear in the console.

## Steps to Reproduce

   1. Start Brave and enable Rewards
   2. Visit some sites and view terminal
   3. 

## Expected result:
Occasionally, a std::cout log dump will occur similar to:
```videos0https://www.twitch.tv/anatomyz_2/videos1https://www.twitch.tv/videos/410659815##0https://www.twitch.tv/anatomyz_2/videos0https://www.twitch.tv/anatomyz_2/videos0https://www.twitch.tv/anatomyz_2/videos0https://www.twitch.tv/anatomyz_2/videos0https://www.twitch.tv/anatomyz_2/videos0https://www.twitch.tv/anatomyz_2/videos0https://www.twitch.tv/anatomyz_2/videos0https://www.twitch.tv/anatomyz_2/videos0https://www.twitch.tv/anatomyz_2/videos0https://www.twitch.tv/anatomyz_2/videos0https://www.twitch.tv/anatomyz_2/videos0https://www.twitch.tv/anatomyz_2/videos0https://www.twitch.tv/anatomyz_2/videos0https://www.twitch.tv/anatomyz_2/videos0https://www.twit...```

## Reproduces how often: 

Always in dev. Since it relies on iostream, this would probably occur on a Release build if run from terminal

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by yrliou** [comment]
@jasonrsadler I believe we have one logged already in https://github.com/brave/brave-browser/issues/4420, so closing this one.
