### ISSUE TITLE
URL.createObjectURL() incompatibility

### ISSUE THREAD

**Issue by NathanaelA** [brave/brave-browser#4424]
Docs: https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL

## Steps to Reproduce
Using createObjectURL seems to create a state where Brave gets confused about things.
Basically the code generates a PDF in memory; and assigns it to an iFrame.   Brave seems to be the only one affected and shows the following warning in the console.log:

`Resource interpreted as Document but transferred with MIME type application/pdf: "blob:http://www.fluentreports.com/b4ffad1e-0f9e-4769-baf7-ea8cc21e454f".`

Broken sites because of this:
   1. http://pdfkit.org/demo/browser.html
   2. http://www.fluentreports.com/demo.html

## Actual result:
![image](https://user-images.githubusercontent.com/850871/57665920-8c094100-75c3-11e9-9f08-ef6f83a98edb.png)

## Expected result:
(From Chromium)
![image](https://user-images.githubusercontent.com/850871/57665757-d63df280-75c2-11e9-84a1-53fd63ca5a95.png)

## Reproduces how often: 
Always

## Brave version (brave://version info)
Windows (Should be current version)
Linux  0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)

## Version/Channel Information:
Current Release (Been this way for a while, just haven't reported it)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No.

- Does the issue resolve itself when disabling Brave Rewards?
Unknown

- Is the issue reproducible on the latest version of Chrome? 
No, Chrome/Firefox/etc work great.

## Miscellaneous Information:
The PDF blob source is being assigned to an iFrame.src property.  (FluentReports is my site; so if you need any code to see, let me know)

**Comment by bsclifton** [comment]
Confirmed this is fixed with https://github.com/brave/brave-core/pull/2342 🎉

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

Verified test plan from https://github.com/brave/brave-core/pull/2342
Verified test plan from the description.

**Comment by Naliniamu** [comment]
what is pipestream. is there anypackage for using pipe stream. how to send report as stream to browser
