### ISSUE TITLE
Allowing Cookies for Site is ignored by shields 3rd party cookie block.

### ISSUE THREAD

**Issue by MNU-497** [brave/brave-browser#4432]
## Steps to Reproduce

   1. Allow any site using brave://settings/content/cookies
   2. Enable shields with blocking of third party cookies
   3. Browse a site that loads content from allowed site from step 1, 

## Actual result:

Cookie is blocked

## Expected result:
Cookie should be allowed because you explicitly allowed it in cookie settings.

## Brave version (brave://version info)
Brave | 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.706

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? No (shields up only)

**Comment by srirambv** [comment]
Shields settings override the explicit content settings. This is expected behaviour. If you disable shields only then changes made in content settings take effect.
