### ISSUE TITLE
Ad notifications not being shown after re-enabling until browser is restarted

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4433]
## Description 
After Ads have been disabled and then re-enabled, Ad notifications will not be shown until you restart Brave.

## Steps to Reproduce

1. Clean install/profile.
2. Enable Rewards (Ads are also enabled)
3. Go to brave://rewards page
4. Disable Ads
5. Wait 30s or so, enable Ads.
6. Visit a site, wait until you see `Browser state changed to idle` in terminal then move the mouse.
7. No ad is shown. You get `Notification not made: Confirmations not ready` in terminal.
8. Give it another minute or so, try step 6 again. Same result. This will continue (you won't get Ads) until you restart Brave. Then you will start to see Ads again.

## Actual result:
Ad notifications not shown after re-enabling Ads from panel on brave://rewards

## Expected result:
Ad notifications should be shown after re-enabling Ads from panel.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

Brave | 0.64.75 Chromium: 74.0.3729.131 (Official Build) (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

Brave | 0.65.92 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

Brave | 0.66.63 Chromium: 74.0.3729.131 (Official Build) dev(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? unsure, but probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
reproduced by @srirambv 
cc @jsecretan @tmancey

**Comment by tmancey** [comment]
@LaurenWags This issue was resolved by https://github.com/brave/brave-browser/issues/4748
