### ISSUE TITLE
Use exponentially distributed intervals for privacy of periodic events

### ISSUE THREAD

**Issue by riastradh-brave** [brave/brave-browser#4435]
The exponential (or geometric) distribution is memoryless, so whether the last event happened just now or a day ago, the distribution on how long from now the next event will happen is the same -- and it's the same for every party that schedules events with exponential distribution at the same rate.  The exponential distribution is the _only_ distribution on the reals with this property (and the geometric distribution, which is the floor of an exponential, is the only one on the integers with this property).

Where we want events to happen on unpredictable intervals but at some prescribed average rate, we should use exponentially/geometrically distributed delays.

**Comment by kjozwiak** [comment]
@riastradh-brave is there anything QA can do here in terms of manual passes? Seems like a `QA/No`. If there's something QA can do here, please add some test cases into the issue and label it as `QA/Yes` 👍 Thanks!

**Comment by btlechowski** [comment]
@riastradh-brave Could you set QA/Yes or QA/No for this issue?
