### ISSUE TITLE
Cookies cannot be changed or deleted by server

### ISSUE THREAD

**Issue by fmp777** [brave/brave-browser#4437]
## Description 
Server response headers cannot modify or delete cookies that have been created from an import [from Firefox] [during initial setup].

## Steps to Reproduce
   1. Fresh download Brave Browser MAC OS 
   2. During startup, import firefox history, cookies, etc.
   3. Visit a website that requires a login that you had logged into via firefox
   4. That website freaks out in some unusual way.  Some websites infinite loop reload, others login failures, google accounts ask to login, but after logging in drop you on an error page concerning cookies
   5. Open dev console and try to manually change or delete cookies, good luck! :)
   6. Can only use Brave preferences to delete them, then relogin to site and all is happy again.

## Brave version (brave://version info)
Brave | 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

**Comment by bsclifton** [comment]
Closing as we no longer support importing cookies (option has been removed)
