### ISSUE TITLE
Shields icon alt text should not say "Has access to this site"

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#4451]
## Description
Currently, the Shields icon has "Has access to this site" as alt-text when you hover over the icon:
<img width="166" alt="Screen Shot 2019-05-09 at 4 13 45 PM" src="https://user-images.githubusercontent.com/2388823/57738995-b3651a00-7666-11e9-9c1c-7ca45c03a383.png">

## Expected Result
The text should just say "Brave Shields" and not have the additional line "Has access to this site"

**Comment by rebron** [comment]
cc: @nullhook 
New design should have the right text.

**Comment by bsclifton** [comment]
Definitely looks to be resolved! Nice work @nullhook 😄 
![image](https://user-images.githubusercontent.com/4733304/158964890-db9cb9aa-c399-40e0-8c45-8eedc1cd773e.png)
