### ISSUE TITLE
Brave's shield blocks S3 file uploads

### ISSUE THREAD

**Issue by iDuriel** [brave/brave-browser#4456]
## Description 
Similar to the bug report #2034 Brave's shield blocks AWS S3 file uploads.

## Steps to Reproduce

   1. Go to AWS S3.
   2. Enable Brave shield.
   
![Screen Shot 2019-05-15 at 15 01 32](https://user-images.githubusercontent.com/38881530/57782545-5e87d900-7724-11e9-806f-34b03b9a27a9.png)

   3. Attempt to upload an excel file with Brave Shield up.

## Actual result:

![Screen Shot 2019-05-15 at 15 02 44](https://user-images.githubusercontent.com/38881530/57782140-8460ae00-7723-11e9-8b6d-003557c7fe74.png)

## Expected result:
Upload successful message.

## Reproduces how often: 
By following the steps above I've successfully reproduced the behaviour every time I've tried to upload an excel or pdf document.

## Brave version (brave://version info)

**Browser version:**
Version 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)

**OS version:**
macOS High Sierra Version 10.13.6

**Hardware:**
MacBook Pro (15 inch, 2017)

## Other Additional Information:

The issue is resolved upon disabling Brave shield.
The only plugin / extension I have installed is 1password.

More information about the error message can be seen on Amazon help pages here: https://aws.amazon.com/premiumsupport/knowledge-center/s3-optionsrequestdenied-error/

**Comment by ryanbr** [comment]
Hey @iDuriel its been a while since this report was submitted, is still an issue with the latest release of Brave?

**Comment by iDuriel** [comment]
Hi @ryanbr thank you for checking on this one.

I've just tested it with the newest version of Brave and everything worked just fine!

Kind regards,
Svet
