### ISSUE TITLE
Implement keyboard shortcut for private tab and private tab with Tor

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#446]
## Description 

Implement keyboard shortcut for private tab and private tab with Tor

## Expected result:
mac
`Cmd+Shift+P` for Private tab using Tor
`Cmd+Shift+N` for Private tab not using Tor

Windows/Linux
`Ctrl+Shift+P` for Private tab using Tor
`Ctrl+Shift+N` for Private tab not using Tor

**Comment by riastradh-brave** [comment]
Ctrl-Shift-P/Cmd-Shift-P is taken for printing.  We settled on Alt-Shift-N/Cmd-Opt-N for new private window with Tor for now in #1387.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.17 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux

* Verified `Ctrl+Shift+N` opens a new private window
* Verified `Alt+Shift+N` opens a new Tor window (based on #1387 )
