### ISSUE TITLE
Can't add linux PC to sync chain

### ISSUE THREAD

**Issue by leobel96** [brave/brave-browser#4463]
## Description 
When I write the sync keys and then I press "confirm sync code" nothing happens

![Screenshot_20190516_152341](https://user-images.githubusercontent.com/19806799/57858126-cdcaff00-77f0-11e9-9aa2-960605c976dc.png)

## Steps to Reproduce
   1. Try to add a Linux PC to an existing sync chain
   2. Write the sync keys
   3. Press the button to confirm

## Actual result:
Nothing happens

## Expected result:
The device should be added to sync chain

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave : 0.64.75 Chromium: 74.0.3729.131 (Build ufficiale) (a 64 bit)
Revision: 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS: Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
My OS is Kubuntu 18.10

**Comment by srirambv** [comment]
Works fine. There is a slight delay in the screen being updated. 
![image](https://user-images.githubusercontent.com/17010094/57868349-d3b0e800-77d0-11e9-9266-cda29e0821c8.png)

**Comment by leobel96** [comment]
I've waited more than one hour and nothing changed. I've also tried uninstalling and installing it again. On windows, after the slight delay you mentioned, everything works as expected.

**Comment by AnthonyIV** [comment]
I am experiencing what appears to be the same issue in Windows.

Brave | 0.64.76 Chromium: 74.0.3729.157 (Official Build) (64-bit)
-- | --
Revision | 7b16107ab85c5364cdcd0b2dea2539a1f2dc327a-refs/branch-heads/3729@{#998}
OS | Windows 10 OS Build 17763.503

I push the button and nothing happens, nothing in the javascript console to give any hint as to what might be going wrong.

@leobel96 do you have any extensions installed? I wonder if we might have any in common that may be causing this?

**Comment by leobel96** [comment]
@AnthonyIV 's solution solved the problem. Thank you!

**Comment by bsclifton** [comment]
Closing as this is now resolved 😄 Let's re-open if someone else runs into this or it happens again (just leave a comment here! I'll help)

**Comment by Lunatix89** [comment]
Just wanted to let you know that I also experienced this issue with roughly the same setup - Kubuntu 18.10 with Brave Version 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit)

Nothing happens when you click the "Confirm" button on the "I have a sync code" form.
But clicking on "Create new sync chain", immediately cancelling the generated token and navigating back to "I have a sync code" works without any issues.

**Comment by NewtonGimmick** [comment]
oh hai der...I am having this same issue with Arch Linux.  The work around listed above works.   Start a new chain > cancel > then paste in my existing chain code and voila.
