### ISSUE TITLE
navigator.mediaDevices.enumerateDevices() exposes FP surface

### ISSUE THREAD

**Issue by snyderp** [brave/brave-browser#4464]
navigator.mediaDevices.enumerateDevices() gives identifiers of media devices on the client. Should be blocked behind shields (or at least, gated behind user gesture / permission).

<img width="1439" alt="Screen Shot 2019-05-16 at 8 29 15 AM" src="https://user-images.githubusercontent.com/76526/57866773-bc640180-77b4-11e9-976e-6c09f1a86f0f.png">

**Comment by yrliou** [comment]
@snyderp It is one of the method we will block if FP in shields is enabled, are we good to close this issue?

**Comment by snyderp** [comment]
yep, thanks!
