### ISSUE TITLE
navigator.mediaDevices.getSupportedConstraints() exposes FP surface

### ISSUE THREAD

**Issue by snyderp** [brave/brave-browser#4465]
related to, but distinct from https://github.com/brave/brave-browser/issues/4464, `navigator.mediaDevices.getSupportedConstraints()` reveals a lot of capabilities of underlying media hardware.  We should block behind shields, or at least limit to 1p frame or user gesture

```
navigator.mediaDevices.getSupportedConstraints()
{aspectRatio: trueautoGainControl: truebrightness: truechannelCount: truecolorTemperature: truecontrast: truedeviceId: trueechoCancellation: trueexposureCompensation: trueexposureMode: trueexposureTime: truefacingMode: truefocusDistance: truefocusMode: trueframeRate: truegroupId: trueheight: trueiso: truelatency: truenoiseSuppression: truepointsOfInterest: trueresizeMode: truesampleRate: truesampleSize: truesaturation: truesharpness: truetorch: truevolume: truewhiteBalanceMode: truewidth: truezoom: true__proto__: Object
```

**Comment by yrliou** [comment]
I checked the API and the implementation, this seems to be a fixed list in chromium across all users, so we should be good for this method, closing it here but feel free to reopen the issue if not.
Thanks for bring this up, @snyderp !
