### ISSUE TITLE
Replace chromium's product_logo_name for branding

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#447]
Right now we're using chromium's product_logo_name images in src/brave/app/theme/default_[100|200]_percent/brave, so we'll see chromium's logo in these cases.
For example, 
![image](https://user-images.githubusercontent.com/4730197/42066176-1e2b7d44-7af4-11e8-85a0-fee3d14d63b8.png)

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux
--|![image](https://user-images.githubusercontent.com/17010094/45971585-5e0cc780-c007-11e8-9165-e4af7997a35f.png)
