### ISSUE TITLE
Add pref to show 24 hour time vs 12 hour am/pm on NTP

### ISSUE THREAD

**Issue by thwaller** [brave/brave-browser#4470]
## Have you searched for similar issues?
Yes, I have done a few searches. It appears that the ending statement on all is that Brave should be respecting the locale of the host computer. This is not the case for me.

## Description 
On the Brave homepage / startpage shows the current time in 12 hour am/pm format. I would like this to be 24 hour format, like the rest of my system.

## Steps to Reproduce
View the Brave homepage / startpage.

## Actual result:
Brave shows the time in 12 hour am/pm format vs the system setting of 24 hour.

## Expected result:
Brave should be respecting the system locale, or have a setting to change it to the desired format.

## Reproduces how often: 
At all times.

## Brave version (brave://version info)
Brave Version 0.65.92 Chromium: 74.0.3729.131 (Official Build) beta (64-bit)
Ubuntu Release 18.04.2 LTS (Bionic Beaver) 64-bit
Kernel Linux 5.0.0-15-generic x86_64

## Version/Channel Information:
Not tested

- Can you reproduce this issue with the current release? -- Not tested
- Can you reproduce this issue with the beta channel? -- Not tested
- Can you reproduce this issue with the dev channel? -- Not tested
- Can you reproduce this issue with the nightly channel? -- Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
I have read a few posts on this. It appears that the "resolution" is that Brave respects the host system's locale. This is not the case.

**Comment by bsclifton** [comment]
Thanks for the report 😄 We have this captured with https://github.com/brave/brave-browser/issues/1308

I'm happy to report that both @imptrx and @cezaraugusto will be working on enhancements for the new tab page soon! Folks wanting to follow along can check out the project board here:
https://github.com/brave/brave-browser/projects/19
