### ISSUE TITLE
publisher added back to AC table after using Restore All - follow up to 3459

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4473]
## Description 
If you excluded a site on a version prior to 0.63.55 (on Release Channel), and then you Restore that site on 0.64.75 (or 0.64.76) version using Restore All, the site will be added back to your AC table, but per https://github.com/brave/brave-browser/issues/3459 it should not be.

## Steps to Reproduce

   1. Install 0.63.55 or older build.
   2. Enable Rewards
   3. Visit at least one site.
   4. Exclude site from AC table.
   5. Update to 0.64.x version.
   6. Visit another site.
   7. Exclude new site. (count of excluded sites is 2)
   8. Click on Restore All.

## Actual result:
Site excluded on 0.63.55 is added back to AC table. Site excluded with 0.64.x version is not added back to AC table.

## Expected result:
Neither site to be added back to AC table.

## Reproduces how often: 
Easily

## Brave version (brave://version info)

Brave | 0.64.76 Chromium: 74.0.3729.157 (Official Build) (64-bit)
-- | --
Revision | 7b16107ab85c5364cdcd0b2dea2539a1f2dc327a-refs/branch-heads/3729@{#998}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? unsure but probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Reproduced on Windows 10 x64 - 0.64.76

**Comment by NejcZdovc** [comment]
this issue is not valid. On 0.63 we didn't delete record like we did in 0.64. Because of that when you restore you see site in the table. So this rule is only from 0.64 forward
