### ISSUE TITLE
Rename "Restore All" to "Clear Excluded List"  in ac 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4474]
## Description 

With #3459 implementation excluded site isn't restored when you click on `Restore all` so the term `Restore all` is quite confusing and doesn't really make sense. Since we are removing sites from the db for that month, renaming to `Clear Exclude List` makes more sense. 

## Steps to Reproduce

   1. Install 0.64.x build
   2. Visit a site and add to ac list
   3. Exclude site, ensure `Restore all` message is shown
   4. Click `Restore all`, nothing gets restored as its removed from db

## Actual result:

Go into think mode of simpler times when restore meant bringing back something that was gone

## Expected result:
Clear means remove, restore means bring back

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.64.76 Chromium: 74.0.3729.157 (Official Build) (64-bit)
-- | --
Revision | 7b16107ab85c5364cdcd0b2dea2539a1f2dc327a-refs/branch-heads/3729@{#998}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes because we released with this bug
- Can you reproduce this issue with the beta channel?
Should be
- Can you reproduce this issue with the dev channel?
Definitely 
- Can you reproduce this issue with the nightly channel?
Undoubtedly 
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @NejcZdovc @mandar-brave @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 10 Version 21H2 (Build 19044.2006)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/15029
- Confirmed "Restore All" is replaced with "Clear exclude list"
- Confirmed "Restore this site" tooltip text is replaced with "Remove from excluded"

Example | Example 
-- | --
![image](https://user-images.githubusercontent.com/38657976/192729505-49d8a78c-0c93-42e4-b48d-eb91dd6a839d.png) | ![image](https://user-images.githubusercontent.com/38657976/192729619-52928672-9c01-429d-9013-189e62d76871.png)

**Comment by LaurenWags** [comment]
Verification in progress on Google Pixel 3 XL with Android 12 running 1.45.100
