### ISSUE TITLE
Re-implement statistical voting for auto-contribute

### ISSUE THREAD

**Issue by evq** [brave/brave-browser#4475]
## Description 
The statistical voting from the original javascript implementation is missing from the logic currently used for auto-contribute.

Old implementation: https://github.com/brave-intl/bat-publisher/blob/master/index.js#L419-L433

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.116 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verification passed on https://github.com/brave/brave-core/pull/2630
