### ISSUE TITLE
Country specific Add Funds for BR 

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#4476]
Need to remove other currencies from add-funds dialog.
This is specific to country - Japan. A user in country Japan should automatically get the image below when the user tries to add-funds. ROW remains the same,

See image in fix:
![image](https://user-images.githubusercontent.com/35932307/57905545-c5dc8080-782b-11e9-96d3-1790cff7d23e.png)

cc @NejcZdovc

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.5 x64 VM` using the following build:

* ensured BAT is the only token available when adding funds via `Add Funds`
* ensured that `the FAQ` link at the bottom of the `Add Funds` modal is working as expected 
* ensured that the QR button is being displayed correctly when clicking on the `Show QR Code`
* ensured that scanning the QR code displays the correct address
* ensured that you can send funds to the address being displayed under `Add Funds`
* ensured that you can still restore a previous wallet using the `Restore` feature
* ensured that the correct BAT address/QR code is being displayed after restoring a wallet using the `Restore` feature
* ensured that all the other tokens are being displayed under `Add Funds` when using the following languages/regions: Canada, Germany, France, Spain, Brazil, Hong Kong

<img width="1248" alt="Screen Shot 2019-06-13 at 11 24 37 AM" src="https://user-images.githubusercontent.com/2602313/59449235-b160b900-8dd4-11e9-8419-75fe6b364fc9.png">
