### ISSUE TITLE
Switch to use Fastly for downloading Rust deps during npm run init

### ISSUE THREAD

**Issue by mihaiplesa** [brave/brave-browser#4484]
Gets stuck sometimes when downloading from S3 bucket which is in us-west-2. Switching to Fastly should fix this and improve the speed.

**Comment by kjozwiak** [comment]
@mihaiplesa assuming there's nothing QA can do as per the `QA/No` label correct? Is this more of a backend change? Does anything need to be uplifted into `0.67.x`?

**Comment by mihaiplesa** [comment]
Have removed the milestone for now.
