### ISSUE TITLE
Make CI pipeline run only once if changes in both b-b and b-c

### ISSUE THREAD

**Issue by mihaiplesa** [brave/brave-browser#4486]
Closes https://github.com/brave/devops/issues/909

**Comment by LaurenWags** [comment]
@mihaiplesa if this doesn't need manual QA can we mark as `QA/No'?

**Comment by mihaiplesa** [comment]
@LaurenWags done

**Comment by LaurenWags** [comment]
awesome, thanks @mihaiplesa!
