### ISSUE TITLE
update opt-in text below Yes I'm Ready button on brave://rewards

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4489]
## Description 
Follow up to https://github.com/brave/brave-browser/issues/3124

On brave://rewards prior to ever opting into Rewards, the text below the 'Yes I'm Ready' button says "By clicking 'Yes, I'm in!..." when the button above it has different text. 

## Steps to Reproduce

   1. Clean profile with 0.64.95
   2. Click on BAT logo. Verify opt in text correctly references the button presented (Join Rewards)
   3. Click Learn More link.
   4. Verify opt in text below 'Yes I'm in!' buton correctly references that button.
   5. Scroll down to the bottom of the page.

## Actual result:
Opt in text below the 'Yes I'm ready' button references the wrong button.
![Screen Shot 2019-05-17 at 1 52 42 PM](https://user-images.githubusercontent.com/28145373/57949418-53fb4a00-78b2-11e9-9f6c-e6015873811e.png)

## Expected result:
"By clicking 'Yes I'm ready', you indicate that you have read and agree to the Terms of Service and Privacy Policy."

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 0.65.95 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by btlechowski** [comment]
Reproduced on 

Brave | 0.65.97 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/58047919-b28e2580-7b49-11e9-8132-662357e189ab.png)

**Comment by jdkuki** [comment]
Reproduced on

Brave |  0.67.42 Chromium: 75.0.3770.38 (Developer Build) (64-bit) 
--- | --- 
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.106 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified STR from description
