### ISSUE TITLE
Sync QR code screen should show same warning message as code words screen - follow up to 4132

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4491]
## Description 
Follow up to https://github.com/brave/brave-browser/issues/4132

Issue above states that both code words and QR code screens should display message that the sync key is sensitive. Code words screen displays such a message, but QR code screen does not.

## Steps to Reproduce

   1. Navigate to brave://sync
   2. Select Start a new Sync Chain
   3. Select 'Computer', you will see added message as dictated in https://github.com/brave/brave-browser/issues/4132#issuecomment-484234764 (except for bolding, logged separately as #4490 )
   4. Now view QR screen. 
   5. After creating sync chain, be sure to view code word and QR screens available from sync details page.

## Actual result:
QR screen does not contain message like code words screen does.
![Screen Shot 2019-05-17 at 4 40 51 PM](https://user-images.githubusercontent.com/28145373/57956195-2a4c1e00-78c6-11e9-9b46-b27097ab1dff.png)

## Expected result:
This is how the message currently looks on code words screen
![Screen Shot 2019-05-17 at 4 39 57 PM](https://user-images.githubusercontent.com/28145373/57956202-359f4980-78c6-11e9-9c2d-aaab3d3310be.png)

## Reproduces how often: 
Easily

## Brave version (brave://version info)

Brave | 0.65.95 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
cc @diracdeltas as original issue had `security` tag.

**Comment by rebron** [comment]
Would need a mechanism to save QR code if we want to go this route.

**Comment by diracdeltas** [comment]
good call, this should definitely be fixed too. i'd suggest P3 since the original issue was P2 and the QR code is just as sensitive. @LaurenWags does this apply to iOS/Android as well?

@rebron not sure i understand why we would have to save the QR code. this issue can be fixed by just adding a sentence under 'Sync Chain QR Code'.

**Comment by LaurenWags** [comment]
@diracdeltas - unsure about Android/iOS, looks like issues for those repos are still open. I'll add a comment as a reminder to double check QR code screen on each of them as well.
Android issue: https://github.com/brave/browser-android-tabs/issues/1475
iOS issue: https://github.com/brave/brave-ios/issues/1056

**Comment by rebron** [comment]
@diracdeltas You're right what I mentioned doesn't make sense. We'll use the same messaging from the code words screen.

**Comment by AlexeyBarabash** [comment]
This was fixed at some point. Hard to find the exact PR. Here is how it looks now, there is a text
`
Sync Chain QR Code
On your mobile device, navigate to Brave Sync in the Settings panel and click the button “Scan Sync Code”. Use your camera to scan the QR Code below. Treat this code like a password. If someone gets ahold of it, they can read and modify your synced data.
`

![image](https://user-images.githubusercontent.com/24739341/211386337-cb6b4277-ee6d-426b-867c-a67e9c7ddecb.png)
