### ISSUE TITLE
Remove unpacked extension warning

### ISSUE THREAD

**Issue by ireallydontwantthisaccount** [brave/brave-browser#4498]
With Chromium, when you have an unpacked extension loaded, every time you open the browser it will warn you that it's "unsafe". This should be removed because it's extremely annoying, especially when you have no other choice (I use [an extension](https://github.com/xxzefgh/youtube-classic-extension) to restore YouTube's classic look and Google took it off of the Chrome store).

**Comment by bsclifton** [comment]
@ireallydontwantthisaccount thanks for bringing that up - this is a highly requested feature that we have captured with https://github.com/brave/brave-browser/issues/4349

I'll go ahead and close this issue as a dupe and give the original issue a +1 on your behalf
