### ISSUE TITLE
The letter `s` should be in caps in `Get started` as per the design spec - Follow up of #960

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#4499]
## Description 

The letter `s` should be in caps in `Get started` - Follow up of #960

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/57990964-33590d00-7ac9-11e9-9dc2-c64df5a25425.png)

## Expected result:
As per the design spec mentioned in https://github.com/brave/brave-browser/issues/960#issue-357013447 the text should be `Get Started` instead of `Get started`

If it's expected please close the issue

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.65.95 Chromium: 74.0.3729.131 (Official Build) beta (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.523

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel?`Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@petemill @rebron

**Comment by btlechowski** [comment]
Reproduced on 

Brave | 0.65.97 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/58035780-cf1a6580-7b29-11e9-88ca-2f323860f5d1.png)

**Comment by petemill** [comment]
Thanks for reporting but the decision is to use sentence casing.
