### ISSUE TITLE
BAT is sometimes truncated on panel for 'Tip this site monthly' value

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4503]
## Description 
Found while testing #2823 

Some values of BAT for monthly drop down on panel do not display properly. eg - if you choose 20 or 50 BAT, the 'T' in BAT is cut off. Other values like 5, 10, 100 display properly. Display issue for 1 BAT logged under #4502.

## Steps to Reproduce

   1. Clean install
   2. Enable Rewards and fund wallet
   3. Visit verified publisher site (on staging, I used kjozwiakstaging.github.io)
   4. Set monthly recurring tip.
   5. Open panel and if you did not already select 20 or 50, change to one of those.

## Actual result:
T is cut off.
![Screen Shot 2019-05-20 at 1 17 29 PM](https://user-images.githubusercontent.com/28145373/58039955-391f1480-7b02-11e9-9efc-2fc5611149c0.png)

![Screen Shot 2019-05-20 at 1 17 40 PM](https://user-images.githubusercontent.com/28145373/58039965-3de3c880-7b02-11e9-847b-c6b268c2f2c8.png)

## Expected result:
T should not be cut off.

![Screen Shot 2019-05-20 at 1 17 52 PM](https://user-images.githubusercontent.com/28145373/58039973-43411300-7b02-11e9-82e6-99fb4ec58bd7.png)

![Screen Shot 2019-05-20 at 1 18 10 PM](https://user-images.githubusercontent.com/28145373/58039980-450ad680-7b02-11e9-8ebb-58959f465d88.png)

![Screen Shot 2019-05-20 at 1 18 20 PM](https://user-images.githubusercontent.com/28145373/58039986-476d3080-7b02-11e9-9935-5a1e5f567637.png)

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 0.65.97 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? unsure but probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

## Miscellaneous Information:
cc @brave/legacy_qa

**Comment by NejcZdovc** [comment]
reopening since UI PR closed it. @cg505 please don't add closing tags to UI PR's, only on brave-core PR's.

cc @ryanml

**Comment by cg505** [comment]
Sorry about that, will do in the future.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.115 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-ui/pull/489
- Verified the STR mentioned in the description

![image](https://user-images.githubusercontent.com/38657976/62367999-e8d42200-b548-11e9-9501-53c7f60ba013.png)

![image](https://user-images.githubusercontent.com/38657976/62368023-f7bad480-b548-11e9-844d-1a32ca306dc7.png)

![image](https://user-images.githubusercontent.com/38657976/62368074-1faa3800-b549-11e9-8a37-69ae934f5401.png)
