### ISSUE TITLE
BrowserAudit - 3 critical problems

### ISSUE THREAD

**Issue by CHEF-KOCH** [brave/brave-browser#4504]
## Description 
Brave Browser is the only Browser (I tested) which has 3 critical security errors/hits. I tested Firefox, Opera, Chrome, Edge & Chromium Edge (Beta) and all of them pass the test.

## Steps to reproduce the issue:

   1. Visit https://browseraudit.com/test
   2. Run the test, which takes a while.
   3. [You'll see 3 critical hits in the red box](https://browseraudit.com/results/21362/38c15578ea807b3af605a7c0639670bbb22ea091), after the test is finished you can review it which says that there are DOM related security problems.
   4. Brave Shields settings are set to block ads, block third-party cookies & fingerprinting, HTTPSE is enabled (script blocking is disabled to avoid getting "strange" results).

## Actual result:
![Audit](https://user-images.githubusercontent.com/727123/58041047-60440900-7b37-11e9-88d1-0086c5c1f0fb.png)
![sffsfsd](https://user-images.githubusercontent.com/727123/58041088-7e116e00-7b37-11e9-9a2e-e4a43d8dbd10.png)

## Expected result:
Brave should not get any critical hit on the test, however I'm not sure how reliable the test page is but since no other of my tested Browser shows a critical hit I think that should be fixed.

## Reproduces how often: 
Each time you run the test you will see 3 critical flaws. 

## Brave version (brave://version info)
* Version 0.64.76 Chromium: 74.0.3729.157 (Official Build) (64-bit)
* The issue did not appeared on a build which I tested earlier this year, [12. April](https://browseraudit.com/results/19126/a288644363b247ec5895e2722e52f6961434b524) - dunno which one it was (sorry).

## Version/Channel Information:
* Windows 10 1903 Ent.
* I did not reproduce the issue in any non stable build but I assume the result will be the same.

**Comment by diracdeltas** [comment]
I tried it on the same version (same shield settings too) but with MacOS instead of windows and got 0 warnings. do you happen to have any extensions installed?
<img width="1214" alt="Screen Shot 2019-05-20 at 11 41 52 AM" src="https://user-images.githubusercontent.com/549654/58044475-b0e64280-7af4-11e9-9d8c-68bdcbb866f8.png">

**Comment by yrliou** [comment]
Tried on Windows 10 but couldn't reproduce on my end on the same version.
<img width="951" alt="Screen Shot 2019-05-20 at 12 00 08 PM" src="https://user-images.githubusercontent.com/4730197/58045374-2521e580-7af7-11e9-8b4e-9d64a02d01e4.png">

**Comment by CHEF-KOCH** [comment]
Thanks for the confirmation. Apparently some flags triggering critical problems in the Browser Audit test. E.g. setting `#allow-sxg-certs-without-extension` to disabled causes one critical error. There are bunch of other settings which might causes my other two critical errors. I already reset all flags now (just in case) and do some further tests.

I was not aware that disabling these flags which are marked with "Enabling this may pose a security risk" are "critical", because that was the reason in the first place why I disabled them.

Theoretically such flags should be removed in order to avoid such problems but I understand that for test reasons etc they are maybe necessary.

**Comment by srirambv** [comment]
Cant reproduce on Windows
 
With default shields
![image](https://user-images.githubusercontent.com/17010094/58052941-21588800-7b24-11e9-8231-fe2bd2c5f430.png)

With all fingerprint disabled
![image (1)](https://user-images.githubusercontent.com/17010094/58052937-1ef62e00-7b24-11e9-9c6a-04864ec9079c.png)

**Comment by diracdeltas** [comment]
> I was not aware that disabling these flags which are marked with "Enabling this may pose a security risk" are "critical", because that was the reason in the first place why I disabled them.

I wonder if this should be reworded to "setting a non-default setting may pose a security risk." Not sure since we inherited this wording from Chrome
