### ISSUE TITLE
Ad blocker popover for washingtonpost

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#4507]
## Description 

https://www.washingtonpost.com/arts-entertainment/2019/05/20/game-thrones-finale-recap-how-did-it-end-daenerys-jon-snow-iron-throne
triggers an ad blocker blocker

![image (2)](https://user-images.githubusercontent.com/34129/58046662-d8400e00-7afa-11e9-8eb6-ed64c57a8848.png)
![image (3)](https://user-images.githubusercontent.com/34129/58046664-db3afe80-7afa-11e9-9588-62feac24975d.png)

## Steps to Reproduce

   1. Navigate to https://www.washingtonpost.com/arts-entertainment/2019/05/20/game-thrones-finale-recap-how-did-it-end-daenerys-jon-snow-iron-throne
   2. 
   3. 

## Actual result:
Page loads fine with shields disabled and there is no cors error

## Expected result:
Page should load with shields enabled

## Reproduces how often: 
Always

## Brave version (brave://version info)
Version 0.64.76 Chromium: 74.0.3729.157

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by diracdeltas** [comment]
the CORS error in the console would be fixed by https://github.com/brave/brave-browser/issues/4396

**Comment by snyderp** [comment]
uBO ships with this rule, which fixes:

`||washingtonpost.com/pb/api/*/adblocker-feature$xhr,1p`

https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt

**Comment by rebron** [comment]
@snyderp Did you end up getting this fix out?

**Comment by snyderp** [comment]
yep yep the above commit / PR fixes
