### ISSUE TITLE
change label to 'address bar' instead of 'location bar'

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#4508]
Under brave://settings in Appearance section, for consistency change label to read: 
'Use wide address bar'

instead of: 
'Use wide location bar'

## Current screen:
<img width="682" alt="Screen Shot 2019-05-20 at 12 51 37 PM" src="https://user-images.githubusercontent.com/5951041/58047939-4f2ad600-7afe-11e9-861b-afff5d4c1d39.png">

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.68.114 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2519
![Screen Shot 2019-08-01 at 5 34 03 PM](https://user-images.githubusercontent.com/28145373/62329000-a5af7b80-b482-11e9-81fe-7abc616570b6.png)
