### ISSUE TITLE
Failed to check for updates links needs to be redirected

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#451]
## Description 

Failed to check for updates links needs to be redirected

## Steps to Reproduce
   1. Build from source d3d567094e81483fff71216f4798b5d06ec193f2
   2. Open `chrome://chrome` from `chrome://about`
   3. Shows error updating. Error code links to community page by just appending the code at the end of the URL. Learn more links to[ Google support page](https://support.google.com/chrome?p=update_error)

## Actual result:
![image](https://user-images.githubusercontent.com/17010094/42093388-2a006996-7b7a-11e8-9a26-7efc2fe43fff.png)

## Expected result:
Error code link should be specific link on community. Learn more should link to the same page 

## Reproduces how often: 

100%

## Brave version (about:brave info) 

d3d567094e81483fff71216f4798b5d06ec193f2 release build from source 

### Additional Information
cc: @bbondy @yrliou

**Comment by simonhong** [comment]
That html error message is made by below in `UpdateCheckDriver::OnUpgradeError`.
```
...
  base::string16 html_error_msg =
      base::StringPrintf(L"%d: <a href='%ls0x%X' target=_blank>0x%X</a>",
                         error_code_, base::UTF8ToUTF16(
                             chrome::kUpgradeHelpCenterBaseURL).c_str(),
                         hresult_, hresult_);
...
}
```

**Comment by srirambv** [comment]
Happens when this message is received as well
![image](https://user-images.githubusercontent.com/17010094/43588306-3470db24-963a-11e8-8425-a5f185cb8f06.png)

**Comment by bbondy** [comment]
maybe wes hould just set shouldShowLearnMoreLink_ to false?

**Comment by simonhong** [comment]
@bbondy , what is preferred way? deleting all links or replacing all links with `community.brave.com`?

**Comment by bbondy** [comment]
I think replacing with community.brave.com. Please CC me on any PR for that though. 
I think @Brave-Matt is working on getting real links for those.

**Comment by GeetaSarvadnya** [comment]
Validated the issue against the Latest build "Version 0.54.2 Chromium: 69.0.3497.42 (Official Build) dev (64-bit)"

**Comment by kjozwiak** [comment]
@bbondy checked that the clicking on the `Learn more` link correctly points to https://community.brave.com/?p=update_error when disconnecting the internet but is there another way to check the other error codes?

**Comment by bbondy** [comment]
not sure, but I think that's a good enough test.

**Comment by kjozwiak** [comment]
Thanks for the quick response 👍 Really appreciate it!

Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X
