### ISSUE TITLE
show/hide New Tab Page elements

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#4510]
## Test plan
See https://github.com/brave/brave-browser/issues/4510#issuecomment-508211813

## Description
Provide users with the ability to show/hide the individual elements on the New Tab page: Brave Stats, Clock, Top Sites. 

## Designs
Hover or tab over the  Brave Stats widget to highlight it and display an icon representing menu options:

![r1 toggle widgets - stats 1](https://user-images.githubusercontent.com/2388823/58129372-7224bb00-7bce-11e9-851b-58bcf9d1a68d.png)

Clicking/selecting the icon shows a menu with widget options:

![r1 toggle widgets - stats 2](https://user-images.githubusercontent.com/2388823/58129382-781a9c00-7bce-11e9-8d40-62b5fa268e99.png)

Hover or tab over the Clock widget to highlight it and display an icon representing menu options:

![r1 toggle widgets - clock 1](https://user-images.githubusercontent.com/2388823/58129486-af894880-7bce-11e9-9801-fe4b1910eeed.png)

Clicking/selecting the icon shows a menu with widget options:

![r1 toggle widgets - clock 2](https://user-images.githubusercontent.com/2388823/58129501-b31ccf80-7bce-11e9-8ec5-a5babfc3cb77.png)

Hover or tab over the Top Sites widget to highlight it and display an icon representing menu options:

![r1 toggle widgets - top sites 1](https://user-images.githubusercontent.com/2388823/58129511-b912b080-7bce-11e9-96c2-b61b5dcaacdf.png)

Clicking/selecting the icon shows a menu with widget options:

![r1 toggle widgets - top sites 2](https://user-images.githubusercontent.com/2388823/58129516-bd3ece00-7bce-11e9-8d7f-d5ea639a93be.png)

The user can add widgets back to new tab page via the Dashboard Settings menu: 

![r1 toggle widgets - panel 1](https://user-images.githubusercontent.com/2388823/58129526-c29c1880-7bce-11e9-8518-932b0c48e8e7.png)

When the user has removed a widget, its corresponding toggle in the Dashboard settings menu is toggled off. This is an example of how the Dashboard would look with everything toggled off:

![r1 toggle widgets - panel 2](https://user-images.githubusercontent.com/2388823/58129592-eb241280-7bce-11e9-9705-7bcb604d6d57.png)

## Design Specs
The user can right click anywhere on the widget to bring up the same options menu:

![r1 toggle widgets - specs 2](https://user-images.githubusercontent.com/2388823/58131524-c4b4a600-7bd3-11e9-8b19-c6583aee9ffc.png)

![r1 toggle widgets - specs 1](https://user-images.githubusercontent.com/2388823/58131551-d302c200-7bd3-11e9-9855-fe7803b9608a.png)

**Comment by imptrx** [comment]
Test Plan: 
1. Open new tabs page with a fresh profile - all NTP elements should appear
2. Open settings menu from the settings icon - 3 new settings should exist below show background
3. Toggle the three options; show clock; show stats; show top sites - they should disappear/reappear on the page
4. Settings should persist after browser is closed and reopened

**Comment by btlechowski** [comment]
Awesome!

Verification passed on

Brave | 0.69.117 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Ubuntu 18.04 LTS

Verified test plan from  https://github.com/brave/brave-browser/issues/4510#issuecomment-508211813
![4510](https://user-images.githubusercontent.com/34715963/63817242-b2b57280-c93b-11e9-8b5c-bcf31c9b4e62.gif)
