### ISSUE TITLE
Update Shields description in Welcome screens

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#4511]
## Description
The current Shields description in the Welcome screens are not user-friendly and out of date from how we're describing the way Shields works. Update the text so that it matches both iOS and desktop.

Current desktop welcome screen text:
![shields descrip desktop welcome](https://user-images.githubusercontent.com/2388823/58056689-e56af600-7b16-11e9-9a9e-30a90c50410c.png)

Current iOS welcome screen text:
<img width="264" alt="Screen Shot 2019-05-20 at 3 42 07 PM" src="https://user-images.githubusercontent.com/2388823/58056455-fb2beb80-7b15-11e9-8ba5-f1e48e66ebca.png">

## Designs

Update text:
> Protect against privacy-invading ads and trackers while browsing with Brave Shields. Set Shields to "down" if a site doesn’t seem to be working properly.

Desktop welcome screen text:

<img width="560" alt="Screen Shot 2019-05-22 at 1 06 13 PM" src="https://user-images.githubusercontent.com/2388823/58208549-cba5ec00-7c99-11e9-9dfc-87834689e8f1.png">

iOS welcome screen text:

<img width="459" alt="Screen Shot 2019-05-22 at 1 50 12 PM" src="https://user-images.githubusercontent.com/2388823/58208555-ce084600-7c99-11e9-9b5a-6a6c2304489a.png">

**Comment by karenkliu** [comment]
@tomlowenthal Can you take a look at this suggested text and see if you have any edits?

**Comment by rossmoody** [comment]
Could consider leading with action. Also, I know the term in the panel is 'Down' but the phrase `bring Shields down` feels a little off to me. I don't feel like I would `bring` a setting. Considerations: 

`Protect against privacy-invading ads and trackers while browsing with Brave Shields. Turn Shields off if a site doesn’t seem to be working properly.`

`Protect against privacy-invading ads and trackers while browsing with Brave Shields. Set Shields to "down" if a site doesn’t seem to be working properly.`

**Comment by tomlowenthal** [comment]
I like Ross's text.

**Comment by karenkliu** [comment]
Mocks updated.
