### ISSUE TITLE
Shared BAT tokens between multiple Computers...

### ISSUE THREAD

**Issue by SalvorinFex** [brave/brave-browser#4512]
## Description 
I have multiple computers with Brave installed and Synced the 3 of them together, However, I noticed that the Crypto Addresses for each one is Different, making it impossible to share one 'bag' of BAT tokens between all three.

## Steps to Reproduce
   1.  Install Brave browser on 2 or more separate Computers
   2.  Turn on Brave Rewards.
   3.  Attempt to add Funds to each one and notice the each of the address is different in between them.

## Actual result:
Separate Address

## Expected result:
The same addresses for each of the 4 tokens listed. 

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
Version 0.64.76 Chromium: 74.0.3729.157 (Official Build) (64-bit)

I believe this should be the default behavior after syncing more than 2 computers with Brave installed, as it would eliminate the need to split BAT tokens between individual browsers and just have one Bag shared to your account.

**Comment by NejcZdovc** [comment]
this will be possible when we will add support for sync in Rewards. Until then what you can do is decide which wallet you will keep (maybe you already have money in one of them) and backup that wallet. Go to another two computers and restore it. More info about how to do this here: https://support.brave.com/hc/en-us/articles/360020673191-How-do-I-back-up-or-Restore-my-Wallet-in-Brave-

**Comment by SalvorinFex** [comment]
Okay, thanks for that info.
I went ahead and sent $5 to my laptop's Brave, but it's been 12+ hours and it still hasn't arrived.

https://etherscan.io/token/0x0d8775f648430679a709e98d2b0cb6250d2887ef?a=0xf26a9fa2806fe6e3f1e133f332b4b91912a91fe6

What would cause that kind of delay?
