### ISSUE TITLE
Add support for Twitter in the panel

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#4514]
We need to add support for twitter in the panel. This way when user visits https://twitter.com/{username} he can tip `{username}`

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.107 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2468
