### ISSUE TITLE
Ballots Aren't Processed

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#4515]
## Description 
It appears that ballots aren't being cleared-out and/or processed for some users. This appears to happen when a user makes numerous tips in succession, but this could be coincidental.

## Steps to Reproduce
TBD

## Actual result:
Ballots in `ledger_state` do not appear to be processed or cleared-out.

## Expected result:
Ballots should be processed.

## Reproduces how often: 
N/A

## Brave version (brave://version info)
0.64.76

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? _Not sure._
- Can you reproduce this issue with the dev channel? _Not sure._
- Can you reproduce this issue with the nightly channel? _Not sure._

## Miscellaneous Information:
Two users in particular appear to be experiencing this issue. Both issued numerous tips in rapid succession.

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/brave_browser/comments/bv6fib/brave_keeps_over_50_of_each_tip_for_themselves_i/
