### ISSUE TITLE
1 fingerprinting method blocked when default shields setting is set to block everything

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4518]
## Description 

1 fingerprinting method blocked when default shields setting is set to block everything

## Steps to Reproduce

   1. Change shields default to `Block all cookies`, `Block all device recognition`, `Block scripts`
   2. Visit a few sites repeatedly
   3. Check shields shows 1 fingerprint method blocked 
   4. Visit the same sites in a different profile/channel where shields is set to default settings, no fingerprinting method blocked

## Actual result:

Dev (0.66.71)
![image (2)](https://user-images.githubusercontent.com/17010094/58100684-1c3f1b80-7bac-11e9-9179-9aa02680b018.png)

Beta (0.65.98)
![image](https://user-images.githubusercontent.com/17010094/58100654-0c273c00-7bac-11e9-8a90-6a71d5bf2acc.png)

Release (0.64.76)
![image](https://user-images.githubusercontent.com/17010094/58100965-b2734180-7bac-11e9-9d3b-07804cbfeb88.png)

## Expected result:
Should not have a fingerprinting method blocked when there is to fingerprinting script on the page. 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Release/Beta/Dev

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Yes
- Can you reproduce this issue with the dev channel?
Yes
- Can you reproduce this issue with the nightly channel?
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
N/A
- Does the issue resolve itself when disabling Brave Rewards?
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A
## Miscellaneous Information:

Issue not reproducible when using the same site on VM
Release channel on VM (0.64.76)
![image (3)](https://user-images.githubusercontent.com/17010094/58100719-2eb95500-7bac-11e9-953d-455f82c7fc77.png)

cc: @bsclifton @tomlowenthal @bbondy @brave/legacy_qa

**Comment by tomlowenthal** [comment]
I can't repro this.

**Comment by kjozwiak** [comment]
@srirambv mind taking another look when you have some time to see if you can still reproduce this?

**Comment by bsclifton** [comment]
Let's re-open this if it happens again
