### ISSUE TITLE
Create .pkg files for all channels 

### ISSUE THREAD

**Issue by aekeus** [brave/brave-browser#4519]
In the build system, please create .pkg files for all channels, not just release. This will be useful for allowing tracking by referral codes across all channels. The .pkg files should also be transferred to the `/latest` bucket on S3.

**Comment by aekeus** [comment]
cc @emerick @mihaiplesa

**Comment by LaurenWags** [comment]
Verified .pkg files exist for Nightly, Dev, Beta. Downloaded latest .pkg and verified that expected version was installed. However, for Nightly, Dev, Beta each time the .pkg was installed, an extra `Brave` folder was created under `BraveSoftware` (`~/Library/Application Support/BraveSoftware`) which contained a `promoCode` file. This was unexpected - should this be occurring? This does not happen for Release Channel.


Brave | 0.69.49 Chromium: 75.0.3770.100 (Official Build)nightly (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

- Downloaded .pkg file for this Nightly version. Installed. Saw extra `Brave` folder under `~/Library/Application Support/BraveSoftware:
![Screen Shot 2019-07-10 at 3 52 50 PM](https://user-images.githubusercontent.com/28145373/61000627-dab92a00-a32b-11e9-911d-e238ea21d966.png)

Reproduced with Dev .pkg file

Brave | 0.68.98 Chromium: 75.0.3770.100 (Official Build) dev(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

![Screen Shot 2019-07-10 at 3 53 40 PM](https://user-images.githubusercontent.com/28145373/61000675-f0c6ea80-a32b-11e9-869b-42702bd3cab8.png)

Reproduced with Beta .pkg file

Brave | 0.67.106 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

![Screen Shot 2019-07-10 at 3 54 59 PM](https://user-images.githubusercontent.com/28145373/61000696-ffad9d00-a32b-11e9-9fb4-cba0a1ac7cfc.png)

Did not reproduce with Release Channel .pkg file

Brave | 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

cc @kjozwiak to try on macOS also

**Comment by kjozwiak** [comment]
Seeing the same thing as @LaurenWags, example:

* ~/Library/Application\ Support/BraveSoftware/Brave/promoCode --> Browser-Nighyly (`0.69.52 Chromium: 75.0.3770.100`)
* ~/Library/Application\ Support/BraveSoftware/Brave/promoCode --> Browser-Dev (`0.68.99 CR: 75.0.3770.100`)
* ~/Library/Application\ Support/BraveSoftware/Brave/promoCode --> Browser-Beta (`0.67.107 CR: 75.0.3770.100`)

@aekeus seems like an issue. I don't think we should be creating a `promoCode` under `~/Library/Application\ Support/BraveSoftware/Brave/` when installing `nightly`, `dev` or `beta`.

**Comment by emerick** [comment]
I think this might be fallout from brave/brave-browser#4600. In particular, it looks like the presence of a dash in the non-release package names (e.g., `Browser-Beta`) is causing the filename to be interpreted as a promo code.

**Comment by kjozwiak** [comment]
@emerick @aekeus I'm assuming this is something we want fixed before `0.67.x` moves to release?

**Comment by emerick** [comment]
@kjozwiak Yes, I think that makes sense. Should be an easy fix, we just need to guard against `Browser-Beta` etc. being accepted as a valid promo code.

**Comment by LaurenWags** [comment]
Logged https://github.com/brave/brave-browser/issues/5264 as follow up issue, thanks @emerick 😄
