### ISSUE TITLE
Firefox data importer makes Brave to be closed without any error message

### ISSUE THREAD

**Issue by douglascrp** [brave/brave-browser#452]
## Description 

When I tried to perform the Firefox data importer, Brave becomes unresponsive for some seconds, and then it simply closes.
I got no error messages or any useful information to share here.

## Steps to Reproduce
   1. Install Brave
   2. Open the data importer, select Firefox, and let all the options on.
   3. Confirm the import and wait.

## Actual result:

The result is, as already described, Brave being closed without any useful information.

## Expected result:
Just like what happened with Chromium data importer, my data should be imported correctly.

## Reproduces how often: 

Easily reproduced

## Brave version (about:brave info) 

 
Brave: 0.23.19 
V8: 6.7.288.46 
rev: 178c3fbc045a0cbdbe098db08307503cce952081 
Muon: 7.1.3 
OS Release: 4.13.0-46-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Tor: 0.3.3.7 (git-035a35178c92da94) 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.87

### Website problems only:  
- Does the issue gets fixed with Brave Shields disabled? 
- Does the issue reproduces on Chrome?

**Comment by srirambv** [comment]
This is a duplicate issue is for browser-laptop which is captured here https://github.com/brave/browser-laptop/issues/7646. This repository is for the new brave-core only. Please track the issue in https://github.com/brave/browser-laptop/issues/7646
