### ISSUE TITLE
show/hide background images on New Tab Page

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#4523]
## Description
Provide users with the ability to show/hide background images on the New Tab page.

## Designs
Add a new icon on the NTP that represents Dashboard settings:

![r0 background images 1](https://user-images.githubusercontent.com/2388823/58122376-5f09ef00-7bbe-11e9-83cb-d08afd352532.png)

Clicking or tab selecting the icon shows a menu with dashboard settings:

![r0 background images 2](https://user-images.githubusercontent.com/2388823/58122647-f2dbbb00-7bbe-11e9-8ca1-c94cb7f23c18.png)

Clicking or tab selecting the toggle keeps the menu open while turning off the background image:

![r0 background images 4](https://user-images.githubusercontent.com/2388823/58122691-0b4bd580-7bbf-11e9-870a-741ba624365f.png)

Clicking anywhere outside the menu closes it:

![r0 background images 5](https://user-images.githubusercontent.com/2388823/58122782-3afadd80-7bbf-11e9-8e1d-35c02adc2229.png)

## Design Specs
![r0 background images specs](https://user-images.githubusercontent.com/2388823/58129049-cb401f00-7bcd-11e9-8086-e2a29dcf107c.png)

The Dashboard Settings menu should support dark theme set at the OS level:
![r0 background images dark theme](https://user-images.githubusercontent.com/2388823/58124541-52d46080-7bc3-11e9-88b4-47ee2b40e8e9.png)

Abstract link for more CSS/layout: https://share.goabstract.com/9563ae1d-93af-40ef-811b-4c3f384fe8f4

**Comment by karenkliu** [comment]
@imptrx reach out to @rossmoody for guidance on front-end components in our design system

**Comment by srirambv** [comment]
@karenkliu with no background image is it going to be the gradient colour? or is that customized to pick the system colour scheme because Windows and Mac now supports dark theme to be used?

**Comment by karenkliu** [comment]
@srirambv to start the no background image will be a gradient color. We will of course be supporting more options for the background image in the future (pick your own image, set to a solid color, pick a solid color from color picker, pick a different gradient) etc.

**Comment by srirambv** [comment]
Huge +1 for custom colour picker for new tab page.

**Comment by petemill** [comment]
@karenkliu There are now 4 buttons here that look the same, but do very different things - one unintrusively pops up a toggle, the others load whole different pages. Can we make it intuitive that 3 of them are links to different pages, and 1 of them will lead to a menu? Perhaps by putting an arrow on that button.

**Comment by karenkliu** [comment]
@petemill We can temporarily resolve that by making new icons for Settings, Bookmarks, and History that has an arrow on them. 
Or, we can wait for planned updates to the Top Sites behavior, where the user can add/remove any site, including browser pages such as Settings, Bookmarks, and History, to that section. At this point we would remove the persistent icons at the bottom right, leaving just the Dashboard Settings icon. Need to discuss with @rebron whether we want to invest in the stopgap solution (new icon) or be OK with this discrepancy for now while waiting for fixes to the Top Sites widget.

**Comment by rebron** [comment]
@karenkliu Stopgap with new icons per @petemill's suggestion.

**Comment by karenkliu** [comment]
@rebron I created a separate issue #4930 to update the icons.

**Comment by bsclifton** [comment]
Updated labelling to help with QA and edited original post to link to test plan 👍

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.106 Chromium: 76.0.3809.62 (Official Build) dev (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/2668

![image](https://user-images.githubusercontent.com/38657976/61587119-570c0280-aba1-11e9-9814-fbd5ecf62953.png)

- Verified New tab page by changing the Theme and Brave color
