### ISSUE TITLE
Force Sync Feature Request

### ISSUE THREAD

**Issue by marc1uk** [brave/brave-browser#4536]
## Description 
The idea of sync is that it allows a user to maintain continuity when switching devices.
Often, one is wrapping up a session and performs bookmarking as a final action before shutting down, such that the session can be picked up later on a different device.
But without a 'force sync' ability, this frequently results in disappointment and frustration.

## Steps to Reproduce
   1. Start work on device 1
   2. Reach end of day / meeting time / lunch / whatever else, and realise one must save the session to continue later
   3. Bookmark a number of pages
   4. Later, open brave on another device

## Actual result:
Bookmarks are not synced. Time is wasted, both in the pointless saving of pages, and the re-finding of those saved pages. Anguish. Disappointment. Despair. Sadness.

## Expected result:
Bookmarks are synced. Perhaps as a result of a final 'force sync' action immediately prior to shutting down. Pages are retrieved on the other device, life goes on, all is right with the world.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)
Revision | e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}
OS | Linux

## Version/Channel Information:
- Can you reproduce this issue with the current release? yes (latest in debian repos anyway)
- Can you reproduce this issue with the beta channel? ~~
- Can you reproduce this issue with the dev channel? ~~
- Can you reproduce this issue with the nightly channel? ~~
... sorry, but i don't have time to install 4 different versions of the browser to see if one of them works. 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  ~~

## Miscellaneous Information:
This feature was requested back in 2017 https://github.com/brave/browser-laptop/issues/7954
but the feature was closed....

**Comment by srirambv** [comment]
Is your first device still online when you add bookmarks? Any change in bookmarks does trigger an sync so if you add a bookmark then it should instantly try to sync it. If both of your devices are online at the same time then the sync will go on smooth.

**Comment by marc1uk** [comment]
I didn't have both of my devices on when I performed the bookmark. I couldn't see anything on the Brave sync page that suggests that would be necessary - I assumed they would be synced through some cloud service or such. Do both devices need to be on at the same time then?

**Comment by Huitziii** [comment]
I am meeting the same issue.

1. It's not always possible to have all devices online when adding bookmarks. For example in the case of a dual-boot computer. I often want to switch OS but "transfer" bookmarks the same way @marc1uk explained.

2. Even when devices are online, sync is not instant at all. I'm currently trying to "transfer" bookmarks, and I can see on my phone that the bookmark folder I added is not sync there. When will it be? I don't know.

**Comment by GJSchaller** [comment]
In the case of remote devices (i.e. - a home laptop which is off or asleep while you are at work), having all devices online at the same time may not be feasible.  This is also the case for phones or tablets that may not have Brave at the forefront, and active, when changes are made on another device.

**Comment by bavalpey** [comment]
This is very necessary.  I tried to force sync to happen by removing the out-dated device from the chain and re entering but this did not fix it.  I see no way of forcing a device that is behind on the sync to get up to speed with other devices.

**Comment by vuongggggg** [comment]
I'm pretty sure and already double check that my devices are still online. But can't sync and no ways to check status of sync process...

**Comment by webash** [comment]
In lieu of a 'force' button, being able to see when each device last synced from the sync device list page would be useful. This then at least lets us know "oh the latest changes aren't on the cloud from that device".

**Comment by bavalpey** [comment]
So I had an issue on my device where all of my bookmarks were duplicated every time I turned the device on.  I had to remove it from the sync chain.  This 'bookmark' syncing feature seems to be horribly broken.

**Comment by Feromrk** [comment]
The sync feature does not work at all for me. It is pretty broken.

Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) unknown (64-bit)

**Comment by talltoo** [comment]
> The sync feature does not work at all for me. It is pretty broken.
> 
> Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) unknown (64-bit)

Same issue for me: Version 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)

**Comment by kyeotic** [comment]
@srirambv Having all devices online is an unreasonable expectation. A far more reasonable expectation is that only _one_ device will be online when bookmarks change: the device initiating the change.

**Comment by bavalpey** [comment]
@srirambv I just tried this and the sync feature doesn't work _even when all devices are online_

**Comment by bsclifton** [comment]
I believe this is possible now with brave://sync-internals/ since Sync v2 was released in 1.12

**Comment by darkdh** [comment]
Yeah, we can close this with sync v2
