### ISSUE TITLE
Support Tips for new Twitter site

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#4548]
Issue:
It seems Twitter is A/B testing multiple sets of pages for users who are willing to opt in to those. One of those pages is mobile.twitter.com which is the responsive version. Our current solution for Twitter tipping breaks on the new site.

Solve:
Preferably fix prior to release. 
Old site works reliably so far.

cc @emerick @NejcZdovc @alexwykoff

**Comment by jonathansampson** [comment]
Regarding selectors: `[data-testid="tweet"]` matches only Tweets elements on the mobile twitter. `[role="group"]` matches only the action elements beneath Tweets.

**Comment by emerick** [comment]
That's really helpful! The other half of the puzzle would be gathering the various metadata associated with the tweet. We currently gather the following pieces of metadata:

- User ID of tweet author
- Real name of tweet author
- Twitter handle of tweet author
- Unique tweet ID
- Tweet timestamp
- Tweet text

Haven't looked in depth, but hoping it's not too hard to gather those once we have the tweet itself.

**Comment by jonathansampson** [comment]
New DOM doesn't make things easy. The following gathers most of the data, but the numerical user ID does not appear to be retrievable from the DOM.

```js
const getMetaData = tweet => {

    const names = tweet.getElementsByTagName("a")[1].textContent.split("@")
    const status = tweet.querySelector("a[href*='/status/']")

    return {
        name: names[0],
        screenName: `@${names[1]}`,
        userId: "",
        tweetId: status.href.match(/\d+/)[0],
        tweetTimestamp: status.querySelector('time').dateTime,
        tweetText: tweet.querySelector('[lang]').textContent
    }
}
```

**Comment by mandar-brave** [comment]
@emerick move this to P1; we need to hotfix this in to current release.
@NejcZdovc FYI

**Comment by emerick** [comment]
@mandar-brave It looks like promoted tweets don't contain a timestamp link, which also happens to be where we scrape the tweet ID from. We need the tweet ID in order to quote the tweet when tweeting about our tip (it may be used elsewhere too, but that was the main place I saw it being used).

I would suggest for now that we disallow tipping promoted tweets on new Twitter, as I'm not sure we currently have a viable workaround for this. Let me know what you think, however.

**Comment by mandar-brave** [comment]
@emerick i am good with getting what we can; we should get a PR out without tipping promoted tweets ATM; leave the issue open to see if we can find a fix for the remain topics.

@davidtemkin for his opinion!

**Comment by GeetaSarvadnya** [comment]
@emerick For `Promoted` tweets inline Tip link is NOT shown. Is this expected?. Thanks!

![image](https://user-images.githubusercontent.com/38657976/61867051-fc054300-aef3-11e9-8548-c5ac6f7f98f5.png)

**Comment by emerick** [comment]
@GeetaSarvadnya Yes, for technical reasons (basically, we're unable to retrieve the tweet ID for promoted tweets) we don't allow tipping promoted tweets and thus don't show the tip icon for them.

**Comment by GeetaSarvadnya** [comment]
Verification passed on




- Verified the test plan from https://github.com/brave/brave-core/pull/2943
- Verified there is no inline Tip icon when Rewards is NOT enabled

![image](https://user-images.githubusercontent.com/38657976/61867786-97e37e80-aef5-11e9-8cbb-d5a7d4c522c0.png)

- Verified inline Tip icon display when Rewards is enabled
![image](https://user-images.githubusercontent.com/38657976/61867921-e8f37280-aef5-11e9-8e2c-79c5ce4c9a37.png)

- Verified Tip icon disappear from twitter feed when uncheck "Twitter" checkbox in Tips Settings

![image](https://user-images.githubusercontent.com/38657976/61868042-2e17a480-aef6-11e9-9b82-c16abd3bb835.png)

- Verified Tip icon appear again in twitter feed when checking "Twitter" checkbox in Tips Settings

![image](https://user-images.githubusercontent.com/38657976/61868132-5c957f80-aef6-11e9-84fc-d4d2ea5af2df.png)

- Verified Tip icon display in newly loaded tweets when infinite scroll into the twitter feeds

- Verified the tipping banner after clicking on the Tip icon in the twitter feed
![image](https://user-images.githubusercontent.com/38657976/61868314-c746bb00-aef6-11e9-8b21-6a06add3363b.png)

Tipping twitter user works as expected.
