### ISSUE TITLE
Suggestion for developer mode extension warning popup

### ISSUE THREAD

**Issue by Mr-Mondragon** [brave/brave-browser#4549]
Following up on issue https://github.com/brave/brave-browser/issues/4349 (developer mode extension) warning that has been extensively discussed:

> We have this issue on the board and prioritized. We have more than enough feedback (been very helpful) as a requested issue to address. We'd like to move forward with discussing implementation details with future comments as we need to start discussing UI/UE/text etc.

_Originally posted by @rebron in https://github.com/brave/brave-browser/issues/4349#issuecomment-494188366_

I would like to propose the following UI approach.

Normally the warning popup looks like this: (posting thumbnails here, with links to full size images)

![screenshot 1](https://i.imgur.com/i3bmJHIt.png) &rarr; https://i.imgur.com/i3bmJHI.png

By default, it stays this way, unless you manually enable a config setting, for example like this:

![screenshot 2](https://i.imgur.com/Zh0HRX6t.png) &rarr; https://i.imgur.com/Zh0HRX6.png

The warning popup then has extra 'Advanced' button:

![screenshot 3](https://i.imgur.com/ce54RD4t.png) &rarr; https://i.imgur.com/ce54RD4.png

And if you click that, you will see:

![screenshot 4](https://i.imgur.com/7oKR7Yft.png) &rarr; https://i.imgur.com/7oKR7Yf.png

(by default the checkbox is DISabled of course)

Considerations:
* By only showing this option after manually enabling it in the config settings, and clicking the Advanced button, we are very sure nobody will 'accidentally' click this.
* By suppressing the warning only for the current version of a particular extension, we are very sure no unwanted extensions will accidentally slip through and go unnoticed.

**Comment by tomlowenthal** [comment]
Unfortunately, we can't rely on any local state to determine whether this notice is shown. Any malicious attempt to install an unwanted extension could also manipulate that state.
