### ISSUE TITLE
Bookmarks toolbar, large list, no scroll

### ISSUE THREAD

**Issue by defcon1776** [brave/brave-browser#455]
## Description 

Large listing of bookmarks (80) do not scroll down from toolbar, available only from bookmarks page.

Since current version update.

No extensions except PDF viewer enabled.

## Brave version (about:brave info) 

Brave | 0.23.19
-- | --
V8 | 6.7.288.46
rev | 178c3fb
Muon | 7.1.3
OS Release | 6.1.7601
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Tor | 0.3.3.7 (git-035a35178c92da94)
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.87

### Website problems only:  
- Does the issue gets fixed with Brave Shields disabled? no
- Does the issue reproduces on Chrome? no

### Additional Information

Apologies if this is out of order, I'm not a tech guy.

**Comment by eljuno** [comment]
Thanks for reporting! But this is a wrong repo. :smile:
Added your +1 to the issue brave/browser-laptop#14606
