### ISSUE TITLE
Revert features to correct state after disabling field trials

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#4552]
## Description

Follow-up issue to https://github.com/brave/brave-browser/issues/4283

- [x] EV status should be set to lock instead of secure chip
- [x] Remove features from brave_main_delegate.cc that were enabled/disabled because of field trials
- [x] Set `kExtensionsInstallVerification` to enforce-strict for `BravePDFDownloadTest.VerifyChromiumPDFExntension`

## Test Plan
Specified here: https://github.com/brave/brave-core/pull/2471

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.109 Chromium: 76.0.3809.62 (Official Build) dev (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/2471

Only Lock is displayed
![image](https://user-images.githubusercontent.com/34715963/61835448-03890580-ae7c-11e9-8364-a5600ca4d75c.png)
