### ISSUE TITLE
On Twitter is repeated twice on BR panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4554]
## Description 

On Twitter is repeated twice on BR panel

## Steps to Reproduce

   1. Enable rewards on `0.67.51`
   2. Upgrade to `0.67.55`
   3. Visit a verified Twitter publisher
   4. `on Twitter` is repeated twice in the panel 

## Actual result:

![Screenshot from 2019-05-23 12-20-28](https://user-images.githubusercontent.com/17010094/58270295-6a445280-7d57-11e9-86ad-813d7cc3f8db.png)

## Expected result:
Should not duplicate the platform name on the panel

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.67.55 Chromium: 75.0.3770.38 (Official Build)nightly (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?  N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

## Miscellaneous Information:

cc: @NejcZdovc

**Comment by LaurenWags** [comment]
On a clean profile, the @ handle is in parenthesis, but no double 'on Twitter' observed:
![Screen Shot 2019-05-23 at 12 42 37 PM](https://user-images.githubusercontent.com/28145373/58271247-a1b3fe80-7d59-11e9-89ff-9a0a3d20cfa7.png)

**Comment by NejcZdovc** [comment]
I can't reproduce this one the latest nightly `Version 0.67.62 Chromium: 75.0.3770.38 (Official Build) nightly (64-bit)`

![image](https://user-images.githubusercontent.com/9574457/58430799-2d57c300-80ab-11e9-8f98-8b289155c1b7.png)

**Comment by NejcZdovc** [comment]
@srirambv @LaurenWags can you please try again on a clean profile?

**Comment by srirambv** [comment]
I can reproduce on a clean profile of last nightly 

Brave | 0.67.62 Chromium: 75.0.3770.38 (Official Build)nightly (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}


![image](https://user-images.githubusercontent.com/17010094/58431115-590e8500-807a-11e9-8868-37c943aec607.png)
![image](https://user-images.githubusercontent.com/17010094/58431131-67f53780-807a-11e9-81bd-d890e2f94dec.png)


Two different behaviour on different profiles. Also notice how the image is shrinked when Twitter handle is included with  the publisher name

**Comment by NejcZdovc** [comment]
@srirambv which OS is this? I am trying to find what is a difference

**Comment by srirambv** [comment]
@NejcZdovc  
![image](https://user-images.githubusercontent.com/17010094/58431337-43e62600-807b-11e9-8815-6cd3e9fdfbf3.png)

**Comment by LaurenWags** [comment]
@NejcZdovc my comment above reproduces on a clean profile with

Brave | 0.67.62 Chromium: 75.0.3770.38 (Official Build) nightly(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X


![Screen Shot 2019-05-28 at 9 41 22 AM](https://user-images.githubusercontent.com/28145373/58484437-0f807180-8130-11e9-86b2-d5628c63df1b.png)

**Comment by LaurenWags** [comment]
Had a call with @NejcZdovc to discuss this one - he noticed that if handle starts with a capital letter, we're not parsing correctly. Here are some examples:
https://twitter.com/kamiljozwiak
![Screen Shot 2019-05-28 at 9 41 22 AM](https://user-images.githubusercontent.com/28145373/58487057-f9c17b00-8134-11e9-9969-e16ac5084d5b.png)

https://twitter.com/bravesampson
![Screen Shot 2019-05-28 at 10 39 30 AM](https://user-images.githubusercontent.com/28145373/58487080-03e37980-8135-11e9-9f96-2fc9f031ae5e.png)

And when the handle starts with lower case letter:
https://twitter.com/bvsriram
![Screen Shot 2019-05-28 at 10 39 45 AM](https://user-images.githubusercontent.com/28145373/58487111-12319580-8135-11e9-802c-1e42b45255bb.png)

https://twitter.com/emerick
![Screen Shot 2019-05-28 at 10 39 51 AM](https://user-images.githubusercontent.com/28145373/58487146-1d84c100-8135-11e9-999d-42aeea443a3e.png)

https://twitter.com/bravelaurenwags
![Screen Shot 2019-05-28 at 10 39 38 AM](https://user-images.githubusercontent.com/28145373/58487169-26759280-8135-11e9-94f3-99ff5397f63b.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.106 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2516
* Visited twitter pages listed in https://github.com/brave/brave-browser/issues/4554#issuecomment-496546410 and they displayed as expected
![Screen Shot 2019-07-10 at 5 05 20 PM](https://user-images.githubusercontent.com/28145373/61004881-f412a400-a334-11e9-8393-d06d94f73192.png)
![Screen Shot 2019-07-10 at 5 05 31 PM](https://user-images.githubusercontent.com/28145373/61004884-f5dc6780-a334-11e9-8ade-cd70a489eced.png)
