### ISSUE TITLE
inline tip panel contains Make this monthly checkbox

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4556]
## Description 
When accessed from an inline twitter tip, the tip panel has the 'Make this monthly' checkbox, but spec screenshots do not have this option for inline tips.

## Steps to Reproduce

   1. Install build equipped with twitter tips
   2. Enable Rewards
   3. Navigate to a twitter site, click on Tip button for a tweet.

## Actual result:
Twitter tip banner is displayed with Make this monthly option.
![Screen Shot 2019-05-23 at 12 54 36 PM](https://user-images.githubusercontent.com/28145373/58272899-8a771000-7d5d-11e9-9882-0d1607ba6298.png)

## Expected result:
Twitter tip banner is displayed without Make this monthly option.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.67.55 Chromium: 75.0.3770.38 (Official Build) nightly(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the dev channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @brave/legacy_qa @mandar-brave @alexwykoff @jenn-rhim

**Comment by NejcZdovc** [comment]
closing as we want to have monthly on inline tips as well

**Comment by LaurenWags** [comment]
@mandar-brave @jenn-rhim @alexwykoff please make sure the spec is updated accordingly.

cc @kjozwiak
