### ISSUE TITLE
Tip option on a twitter thread takes time to show up 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4558]
## Description 

Tip option on a twitter thread takes time to show up 

## Steps to Reproduce

   1. Open a tweet which has a good number of replies
   2. Tip option doesn't show up for a good 3-4 secs
   3. 

## Actual result:

Tip option on a twitter thread takes time to show up. The lag is pretty noticeable 

## Expected result:
Tip option should show up when a tweet thread is opened

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.67.55 Chromium: 75.0.3770.38 (Official Build)nightly (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @alexwykoff @mandar-brave @jenn-rhim

**Comment by NejcZdovc** [comment]
this is intentional as we have timer to do it every 3s

**Comment by kjozwiak** [comment]
> this is intentional as we have timer to do it every 3s

Regarding the above, does this mean Twitter in general? Or just Twitter threads? Assuming threads as the buttons are loaded instantly when you visit Twitter. Just out curiosity, what's the reasoning for waiting 3s for the tip button to appear when viewing threads?

**Comment by NejcZdovc** [comment]
@kjozwiak more info here https://github.com/brave/brave-core/pull/2195#discussion_r285692776

**Comment by kjozwiak** [comment]
@NejcZdovc thanks 👍
