### ISSUE TITLE
can't disable content-level tips

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4559]
## Description 
Unable to disable content-level tips.

## Steps to Reproduce

   1. Install twitter tip enabled nightly.
   2. Enable Rewards
   3. Navigate to brave://rewards page
   4. Click on settings in Tips panel.
   5. Try to uncheck Twitter.

## Actual result:
Unable to uncheck Twitter.

## Expected result:
Able to uncheck Twitter.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.67.55 Chromium: 75.0.3770.38 (Official Build) nightly(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the dev channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @brave/legacy_qa @mandar-brave @alexwykoff @jenn-rhim

**Comment by emerick** [comment]
@NejcZdovc I think the problem is in the `ON_INLINE_TIP_SETTINGS_CHANGE` reducer, where it makes this check:

```
if (!value || value === '') {
  break
}
```

Seems like that will prevent a false value from ever being allowed...

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.106 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified STR above and test plan from https://github.com/brave/brave-core/pull/2503
