### ISSUE TITLE
Add support for Twitter AC

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#4560]
## Description 

verified twitter pub is not added to auto contribution table

## Steps to Reproduce

 1. Enable rewards on 0.67.14
 2. Upgrade to 0.67.55
 3. Open verified twitter pubs in new tab
 4. Verify a-c table

## Actual result:

verified twitter pub is not added to auto contribution table

![image](https://user-images.githubusercontent.com/38657976/58273444-5e37af80-7dae-11e9-91b7-6976e29d24ce.png)

## Expected result:
verified twitter pub should be added to auto contribution table

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.67.55 Chromium: 75.0.3770.38 (Official Build) nightly (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
This one is not a bug as we don't have support for AC for Twitter yet

**Comment by emerick** [comment]
This was fixed a while back via Greaselion.
