### ISSUE TITLE
a-c table is not being correctly updated when excluding publishers

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#4561]
## Description 

unable to exlude site from a-c table

## Steps to Reproduce

1. Enable rewards on 0.67.14
2. Upgrade to 0.67.55
3. Open verified twitter pubs in new tab
4. try to exclude the site from a-c table

## Actual result:

unable to exlude site from a-c table

![Twitter- unable to exclude site from a-c table](https://user-images.githubusercontent.com/38657976/58274012-87a50b00-7daf-11e9-97ac-09463417788c.gif)

## Expected result:

Should be able to exclude a site from a-c table
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 0.67.55 Chromium: 75.0.3770.38 (Official Build) nightly (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc

**Comment by LaurenWags** [comment]
@GeetaSarvadnya does this only happen with Twitter or does it happen with other sites as well?

**Comment by srirambv** [comment]
Reproduced on Linux nightly build `0.67.55`. This is not specific to Twitter. Happens to all the sites. 
Reproduced with same steps on Linux for both twitter and other pages

**Comment by srirambv** [comment]
+1 from @jdkuki via #4601. @jdkuki mentioned a fix in the issue #4601.

**Comment by bbondy** [comment]
Please feel free to put a pretty high priority and regression label if they apply.

**Comment by GeetaSarvadnya** [comment]
@LaurenWags Issue is reproducible for other websites also.

**Comment by NejcZdovc** [comment]
So site is actually excluded/removed correctly, only UI is not updated

**Comment by srirambv** [comment]
@NejcZdovc yes. The UI doesn't immediately update when you delete the publisher from ac list. Its a regression

**Comment by NejcZdovc** [comment]
@srirambv yes, @jdkuki is on it

**Comment by jdkuki** [comment]
Fix in PR brave-core/pull/2520

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.116 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/2520
- Verified adding removing Twitter/Sites/Reddit sites
- Verified adding removing YT and Twitch videos
