### ISSUE TITLE
tipping a retweet

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4563]
## Description 
When you go to tip someone who has retweeted someone else's tweet, what is the expected result? 

There is a line in the spec reads:
"When the tweet doesn’t contain any extractable text, but only another tweet, an image, or video" (followed by a screenshot of the expected tipping banner)
I took the "only another tweet" to mean, a user is retweeting someone else's tweet. So after reading the case above - I expected the tip to go to the person who retweeted, not the original tweet author.

What is happening is if I go to tip a retweeted item, the tip is going to the original author of the tweet, not the person who retweeted. 

If this is expected, please close and update spec for clarity.

## Steps to Reproduce

   1. Install twitter tipping build.
   2. Enable Rewards and navigate to a twitter page.
   3. Click on Tip button inline for a retweeted item from a user.

## Actual result:
![retweet](https://user-images.githubusercontent.com/28145373/58275002-10955580-7d62-11e9-986b-6d5f7f7325e5.gif)

## Expected result:
Spec seems to indicate tip should go to the person who retweeted, not the original author.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.67.55 Chromium: 75.0.3770.38 (Official Build) nightly(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the dev channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @mandar-brave @alexwykoff @jenn-rhim

**Comment by LaurenWags** [comment]
Based on some discussions in slack it seems as though we want to stick with current behavior which makes sense, so updating the spec is probably the thing to do.

**Comment by emerick** [comment]
@mandar-brave @davidtemkin From what I recall, we decided to update the spec to reflect this...

**Comment by NejcZdovc** [comment]
closing as current behavior is what we want

**Comment by LaurenWags** [comment]
@mandar-brave @alexwykoff @jenn-rhim please make sure the spec clearly reflects desired behavior.

**Comment by davidtemkin** [comment]
@LaurenWags updated the spec per above
