### ISSUE TITLE
Tipping Promoted Tweets?

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#4565]
## Description 
Brave presently supports tipping of _any_ tweet, including promotional/ad tweets.

## Steps to Reproduce
1. Go to twitter.com in 0.67.55+
2. Scroll down until you see a promoted tweet
3. Note the Tip button

## Actual result:
Brave supports tipping promoted tweets

## Expected result:
Brave does not support promoted tweets?

## Reproduces how often: 
Always

## Brave version (brave://version info)
0.67.55

## Other Additional Information:
Promoted tweets have a `.promoted-tweet` class, meaning we could easily opt them out:

```ts
const getTweetMetaData = (tweet: Element): RewardsTip.TweetMetaData | null => {
  if (!tweet || tweet.matches('.promoted-tweet') {
    return null
  }
```

**Comment by kjozwiak** [comment]
@mandar-brave @davidtemkin thoughts?

**Comment by NejcZdovc** [comment]
with new twitter design we don't support promoted tweets anymore
