### ISSUE TITLE
Shields should offer a shortcut to allow all scripts once

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#4567]
Task split of https://github.com/brave/brave-browser/issues/2996

### Test Plan

1. Go to Shields
2. Block all scritps
3. Click "allow scripts once"
4. All scripts should be allowed
5. Block all scripts
6. Option to "allow scripts once" should not be visible

Once user toggle noScript `on`, an option to allow all scripts once should appear in the main panel. 

<img width="410" alt="Screen Shot 2019-05-23 at 17 07 32" src="https://user-images.githubusercontent.com/4672033/58282864-48f65d00-7d7d-11e9-911a-2104e4601ef6.png">

**Comment by rebron** [comment]
Removed 67.x milestone label as this wasn't closed/completed. Let me know if I'm wrong. Completed issues should only be moved into the appropriate milestone (unless it's a release blocker).

**Comment by srirambv** [comment]
This issue is superseded by #5342. Although implementation is done as per design there is still a functionality bug that needs to be fixed as part of #5342. @rebron removing this issue from QA/Yes #5342 should be fixed and uplifted to beta

**Comment by btlechowski** [comment]
Removed QA/Yes per above comment
