### ISSUE TITLE
Branding work for Ethereum wallet

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#4569]
These should just be copied by gulp to the brave extension build directory

[images.zip](https://github.com/brave/brave-browser/files/3214006/images.zip)

**Comment by bbondy** [comment]
Fixed here: 
https://github.com/brave/ethereum-remote-client/pull/6

**Comment by btlechowski** [comment]
@bbondy Could you add `QA/Yes` or `QA/No` label to this issue?

**Comment by kjozwiak** [comment]
Going to label this as `QA/No` as there's so test plan nor any STR. @bbondy if there's anything else that needs to be done here, please relabel is as `QA/Yes`.
