### ISSUE TITLE
Add ability to group scripts by same origin on Shields

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#4570]
task split from https://github.com/brave/brave-browser/issues/2996

### Test Plan

1. Go to https://tmz.com
2. Open Shields
3. Go to scripts detail view
4. Scripts that share the same origin should be grouped

Scripts that share the same origin should be grouped:

<img width="408" alt="Screen Shot 2019-05-23 at 17 17 23" src="https://user-images.githubusercontent.com/4672033/58283430-a6d77480-7d7e-11e9-93e0-3c7833c28b31.png">

**Comment by kjozwiak** [comment]
Removed `0.67.x - Dev` as this issue hasn't been closed/completed and still needs to land in `nightly`. @cezaraugusto once the PR for this issue lands in `nightly`, let's add all needed labels and move the issue into the appropriate milestone at that point 👍

**Comment by btlechowski** [comment]
Awesome work!

Verification passed on

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Ubuntu 18.04 LTS

Used test plan from https://github.com/brave/brave-core/pull/2485
Used test plan from the description.

![4570](https://user-images.githubusercontent.com/34715963/62175484-392b6400-b33e-11e9-812b-e1cdb3657010.gif)
