### ISSUE TITLE
blocking a script should take effect immediately

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#4572]
Task split of https://github.com/brave/brave-browser/issues/2996

### Test plan

1. Go to https://brianbondy.com
2. Block all scripts
3. Assert that page is blank
4. Go to scripts detail view
5. Allow the script
6. Script should show "allowed once" remaining under "blocked" list
7. Go back, blur, or close shields
8. Open scripts detail view
9. Script should be under "allowed" list

After blocking a script, action should take effect immediately and tab should refresh reflecting the new state.

A new intermediary state "blocked once"/"allowed once" will be created to reflect user interaction:

<img width="408" alt="Screen Shot 2019-05-23 at 17 25 26" src="https://user-images.githubusercontent.com/4672033/58283850-c6bb6800-7d7f-11e9-8347-edf01933d959.png">

**Comment by kjozwiak** [comment]
Removed `0.67.x - Dev` as this issue hasn't been closed/completed and still needs to land in `nightly`. @cezaraugusto once the PR for this issue lands in `nightly`, let's add all needed labels and move the issue into the appropriate milestone at that point 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Ubuntu 18.04 LTS

Used test plan from https://github.com/brave/brave-core/pull/2485
Used test plan from the description.

Verified that it is possible to `Allow script once` in main view
![image](https://user-images.githubusercontent.com/34715963/62174860-aee20080-b33b-11e9-9b1e-362bb18cc888.png)

Verified that it is possible to `Allow script once` in detailed view
![image](https://user-images.githubusercontent.com/34715963/62175001-48111700-b33c-11e9-99ee-12bc5e6ca0ff.png)

Verified that after closing and opening the same page, the blocked scripts are reset to initial state and that `Allow script once` is shown.
