### ISSUE TITLE
Update npm deps and upstream for Ethereum Wallet

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#4573]
Metamask deps are very outdated, it'd be great to get them updated and to uplift the fixes.

**Comment by diracdeltas** [comment]
npm audit should return 0 warnings

<img width="658" alt="Screen Shot 2019-05-24 at 11 02 55 AM" src="https://user-images.githubusercontent.com/549654/58348009-3844f600-7e14-11e9-9906-4bcfe7421f25.png">

**Comment by ryanml** [comment]
@diracdeltas @bbondy PR up to remove unused deps (Reduces total vulns by ~1k) up here:

https://github.com/MetaMask/metamask-extension/pull/6688

A metamask member has begun to update the deps overall in this PR: https://github.com/MetaMask/metamask-extension/pull/6686 - it's a breaking change (which I also encountered when doing massive updates) so it's best to have there help on that.

**Comment by bbondy** [comment]
This is rebased to node v10 so I'm going to close this.
