### ISSUE TITLE
Shields interface should handle different locales gracefully

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#4575]
Task split of https://github.com/brave/brave-browser/issues/2996

### Test Plan:

1. Change OS locale to Russian or any other language with long words
2. Shields interface should look good without words breaking the interface

The interface should accommodate long strings when translated. For example, the strings in the Shields panel translated to Russian should wrap like this:

<img src="https://user-images.githubusercontent.com/2388823/52826771-1b5f9080-3077-11e9-9362-406eac5bf351.png">

**Comment by cezaraugusto** [comment]
needs https://github.com/brave/brave-core/pull/2485

**Comment by kjozwiak** [comment]
Removed `0.67.x - Dev` as this issue hasn't been closed/completed and still needs to land in `nightly`. @cezaraugusto once the PR for this issue lands in `nightly`, let's add all needed labels and move the issue into the appropriate milestone at that point 👍

**Comment by rebron** [comment]
Closing as stale as we're moving over to a new design. cc: @nullhook
