### ISSUE TITLE
component updater should not be tied to extensions or brave_shields

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#4577]
The brave component updater is coupled to extensions and brave shields which causes problems for android

**Comment by bridiver** [comment]
Test Plan:
1. Verify that ad block is working - (slashdot.org or other site with shields on/off)
2. Verify https everywhere is working - (http://www.http2demo.io/ should be upgraded)
3. Verify autoplay whitelist is working - (??)
4. Verify referrer whitelist is working - (??)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.67.115 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Ubuntu 18.04 LTS

Used test plan from https://github.com/brave/brave-browser/issues/4577#issuecomment-495382236
Https upgrade was tested with `http://https-everywhere.badssl.com/`. `http://www.http2demo.io/` doesn't seem to work correctly even over https.

**Comment by LaurenWags** [comment]
@bridiver as @btlechowski noted, `http://www.http2demo.io/` isn't working - site is not being upgraded to https. however, `http://https-everywhere.badssl.com/` is though. let us know if this is acceptable, thanks.

**Comment by bridiver** [comment]
this change shouldn't affect which sites are upgraded, only whether upgrades work or not and http://www.http2demo.io/ doesn't get upgraded for me on release either

**Comment by diracdeltas** [comment]
according to https://github.com/EFForg/https-everywhere/search?q=http2demo.io&unscoped_q=http2demo.io and https://atlas.eff.org//?http2demo.io, http2demo.io isn't on the current ruleset list. i usually use https://https-everywhere.badssl.com/ for testing.
