### ISSUE TITLE
Add a menu item for triggering WebUI for the Ethereum wallet

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#4579]
This should only be on when the feature flag from https://github.com/brave/brave-browser/issues/4578 is on.

**Comment by LaurenWags** [comment]
@bbondy @ryanml since 0.67.x packaged builds are official builds - is it enough to ensure that the menu item specified in test plan (https://github.com/brave/brave-core/pull/2496) is not available and that visiting brave://wallet does not work?

**Comment by bbondy** [comment]
I think we should just for now make sure that it doesn't show up in the builds.  Then when we release the feature we should probably look at all the closed issues that were behind a flag.

**Comment by kjozwiak** [comment]
Verification **PASSSED** on `macOS 10.14.5 x64` using the following build:

Brave | 0.67.117 Chromium: 76.0.3809.62 (Official Build) (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

* ensured that `Crypto Wallet` isn't visible under `brave://settings`
* ensured that `Crypto Wallet` isn't visible anywhere under the hamburger menu
* ensured that `Crypto Wallet` isn't visible anywhere under the user profile menu
* ensured that `brave://wallet` can't be reached/resolved
* ensured that `chrome://wallet` can't be reached/resolved
* ensured that `chrome://wallet` isn't listed under `brave://about/`

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

* ensured that both `brave://wallet` & `chrome://wallet` loads the crypto page without issues
* ensured that `Crypto Wallets` under the `hamburger menu` loads the crypto page without issues
* ensured that `Crypto Wallets` under the `brave://settings` header loads the crypto page without issues
* ensured that `chrome://wallet` isn't listed under `brave://about` (same behaviour has `chrome://rewards which also isn't listed)
