### ISSUE TITLE
Settings bar to have Wallets entry

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#4581]
This bar should have a Wallets entry (exact name we can tweak later).
The extra button would only show up when the feature flag is on from https://github.com/brave/brave-browser/issues/4578

<img width="1147" alt="Screen Shot 2019-05-23 at 4 52 11 PM" src="https://user-images.githubusercontent.com/831718/58285762-65919580-7d7b-11e9-87b6-49a32a7e4404.png">

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | macOS Version 10.14.6 (Build 18G95)
JavaScript | V8 7.7.299.11

<img width="1326" alt="Screen Shot 2019-09-20 at 12 21 33 AM" src="https://user-images.githubusercontent.com/2602313/65299647-5f9b9d80-db3e-11e9-8814-535be9a22a63.png">

* ensured that `Crypto Wallets` is displayed via `brave://settings` on a new `0.69.x` install
* ensured that `Crypto Wallets` is displayed via `brave://settings` when updating from `0.68.139 CR: 77.0.3865.90` --> `0.69.128 Chromium: 77.0.3865.75` (replacing executable and using the same profile)
