### ISSUE TITLE
incorrect tip banner text for tipping an image/video

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4583]
## Description 
Per spec, when tipping a tweet without any extractable text, you should see something like the image below, however, that's not what's occurring.
<img width="634" alt="Screen Shot 2019-05-23 at 4 54 02 PM" src="https://user-images.githubusercontent.com/28145373/58285765-675b5900-7d7b-11e9-877e-1bcb1db031ff.png">

## Steps to Reproduce

   1. Locate a tweet with just an image (can use this one if needed, should work for both staging and prod: https://twitter.com/bravelaurenwags/status/1131664248856354816)
   2. Click on Tip button

## Actual result:
![Screen Shot 2019-05-23 at 4 52 44 PM](https://user-images.githubusercontent.com/28145373/58285833-89ed7200-7d7b-11e9-83da-1e85361fee8c.png)

## Expected result:
Expecting to see text that said 'Tip @bravelaurenwags for their tweet!' instead of empty tweet box.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.67.55 Chromium: 75.0.3770.38 (Official Build) nightly(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the dev channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @brave/legacy_qa @mandar-brave @alexwykoff @jenn-rhim 

https://twitter.com/bravelaurenwags/status/1131664248856354816 - there's also a reply tweet on this thread which contains a gif that acts the same as the image.

**Comment by NejcZdovc** [comment]
This is what we it would look like now:

![image](https://user-images.githubusercontent.com/9574457/58429272-a8b67600-80a5-11e9-841b-4a312fd8cd81.png)

**Comment by LaurenWags** [comment]
@NejcZdovc to confirm, even if the twitter user you're trying to tip has a custom banner, in this case you still want it to show the default text?  Here's what I'm doing:
(using staging)
1. Navigate to https://twitter.com/bravelaurenwags/status/1131664248856354816
2. Click on in-line tip button
3. See this banner - note, it shows default text in the body (text from #4616)
![Screen Shot 2019-07-10 at 6 14 00 PM](https://user-images.githubusercontent.com/28145373/61008832-b31f8d00-a33e-11e9-90a1-514229da02c5.png)
4. Close banner, navigate to just twitter.com/bravelaurenwags
5. Click on panel, click on Send a Tip
6. Here, the entire custom banner is shown, even custom text in the body of the banner:
![Screen Shot 2019-07-10 at 6 14 17 PM](https://user-images.githubusercontent.com/28145373/61008880-d64a3c80-a33e-11e9-9739-02cf77cc741b.png)

Just want to confirm we are expecting different body text in the two places when tipping an image/gif.

**Comment by NejcZdovc** [comment]
title is different yes if you tip from inline tip or from panel tip

**Comment by LaurenWags** [comment]
ok, thanks!

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.67.108 Chromium: 75.0.3770.100 (Official Build) beta (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/2505
- Verified the STR from the description

In-line tip:
![image](https://user-images.githubusercontent.com/38657976/61198864-639fdf00-a6f9-11e9-9867-e8a9c780bb78.png)

Tip from BR panel:

![image](https://user-images.githubusercontent.com/38657976/61198910-87fbbb80-a6f9-11e9-94b8-e2a9fff7eb76.png)
