### ISSUE TITLE
Update brave-core-crx-packager to upload the packaged extension

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#4585]
Talk to @emerick for technical guidance on here. 
He can help with how to setup the private key and where to store it.
And he can advise on how to do npm scripts for it. 

The repo is here https://github.com/brave/brave-core-crx-packager

**Comment by mihaiplesa** [comment]
Have added the following Jenkins jobs to be executed on demand:

https://staging.ci.brave.com/view/all-extensions/job/brave-core-ext-ethereum-remote-client-update-publish-dev/
https://staging.ci.brave.com/view/all-extensions/job/brave-core-ext-ethereum-remote-client-update-publish/

They both have finished successfully just now.
