### ISSUE TITLE
Figure out where to pass in derived from sync seed data for seed key generation in metamask

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#4589]
cc @diracdeltas in case you can help with this one.

Our forked repo is here:
https://github.com/brave/ethereum-remote-client

We'd probably add an API similar to `common/extensions/api/_api_features.json`  that we only expose to the our forked extension ID to pass the data.

**Comment by diracdeltas** [comment]
sgtm
it will also need to pass in the rewards seed if one exists (at least according to the current spec)

**Comment by diracdeltas** [comment]
though actually right now the seeds are stored unencrypted on disk somewhere so the eth client could just get it from there (until https://github.com/brave/brave-browser/issues/2555 is fixed)

**Comment by bbondy** [comment]
I think this is part of https://github.com/brave/brave-browser/issues/4697 so closing. LMK if I'm not correct!
