### ISSUE TITLE
thank you banner no longer auto dismisses after about 3 seconds

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4590]
## Description 
Tip thank you banner (displayed after giving a tip) does not auto dismiss on Nightly. On other channels, (Dev, etc) it dismisses after about 3 seconds.

## Steps to Reproduce

   1. Give a tip.
   2. Get thank you banner.
   3. Wait for it to go away automatically.

## Actual result:
Thank you banner does not go away without user interaction.

![ty-banner-nightly](https://user-images.githubusercontent.com/28145373/58289403-49debd00-7d84-11e9-9f4f-421ced26ac3c.gif)

## Expected result:
Tip banner would auto dismiss after a certain amount of time - in other channels that is about 3 seconds.

![ty-banner-dev](https://user-images.githubusercontent.com/28145373/58289418-4fd49e00-7d84-11e9-9902-0558663d1963.gif)

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.67.55 Chromium: 75.0.3770.38 (Official Build) nightly(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the dev channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

**Comment by btlechowski** [comment]
Reproduced on

Brave | 0.67.55 Chromium: 75.0.3770.38 (Official Build) nightly (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Windows 10 OS Version 1803 (Build 17134.523)

**Comment by rossmoody** [comment]
I think this is intentional with the addition of the sharing functionality.

**Comment by LaurenWags** [comment]
@rossmoody could be - I didn't see it specified anywhere though that this was changing. Wasn't sure if it shouldn't autodismiss at all (currently how it's working) or if we would give a bit more time before autodismiss so users could click on the Tweet button (5s? 7s?).

**Comment by emerick** [comment]
Yeah, we did remove the auto-dismiss now that the tweet button is there.

@mandar-brave @davidtemkin any thoughts on this one?

**Comment by srirambv** [comment]
+1 from @agentofuser via #4607

**Comment by davidtemkin** [comment]
Auto-dismiss behavior was removed to accommodate social sharing options. 

The banner should still be dismissed either upon clicking its close box or clicking outside the banner, but not without a user action.

**Comment by NejcZdovc** [comment]
closing this one as this behaviour is intentional. We have this one for tracking outside click close problem https://github.com/brave/brave-browser/issues/1743

**Comment by agentofuser** [comment]
Is there any evidence to support the trade-off being made here?

That is, a small amount of user hostility in favor of a supposed large amount of social sharing growth?

I would posit that making the tipping experience as frictionless as possible leads to more tips which leads to happier content creators which leads to their desire for Brave to grow and thus a lot more genuine endorsements, word of mouth, and spontaneous mentions in their influential channels.

**Comment by davidtemkin** [comment]
@agentofuser -- thanks for engaging. are you most interested in streamlining the process of tipping a single content creator multiple times? Or generally the experience of sending a tip to any creator, following your first/introductory tip? 

Also: To what extent is the current lack of keyboard navigability / accessibility getting in the way? I'm looking at the Rewards popup panel, and am seeing that one cannot navigate to the "send a tip..." button at all via tabbing.

**Comment by mandar-brave** [comment]
@NejcZdovc reopening for the moment. Pushing to P1.
We are going to revert back to auto-dismiss. @davidtemkin will add details.

**Comment by agentofuser** [comment]
@davidtemkin thank you for getting back. I would like to streamline the tipping experience in general. The repeat-tipping idea was just one way I thought would be helpful, but I think the interaction can be driven down to 1 click in the first-tip scenario as well.

Every `tip` button could come with a default inconsequential amount, like 1 BAT, with the option to change. I'm putting together a little document with my thoughts on the subject that I think will communicate better what I have in mind.

Regarding keyboard accessibility, it is a big impediment.

I issue an average of 20 twitter likes per day (not taking into account tons of other web browsing outside twitter). I do that with the help of Vimium by typing `f` and then hitting the key assigned to the target I want. That's ~ 2 keystrokes per like, most of the time without moving my fingers from the homerow. 

If I want to tip every time I like (which I do), at the moment that's an extra 100 mouse clicks per day I have to do. That doesn't represent the amount of actual effort though, which is easily 2 or 3 orders of magnitude higher _for each click_ as opposed to a homerow keypress. I have to use my shoulders, move my whole arm around to reach for the touchpad, etc., as opposed to moving a finger 2 millimeters down from its resting position. That would be like 10,000 keypress-equivalent movements per day though, which is enough of an impediment for me to just not bother tipping on 90% of occasions.

**Comment by davidtemkin** [comment]
@agentofuser Excellent! Appreciate the drive toward efficiency. I'm interested to see the document. We can talk here -- and/or via email / phone. I'm at david@brave.com.

**Comment by agentofuser** [comment]
@davidtemkin would love to help. Here are my notes: https://github.com/agentofuser/curling-generosity

I'll email you my number.

**Comment by davidtemkin** [comment]
many thanks @agentofuser! responded via email.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.118 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/2539

![4590](https://user-images.githubusercontent.com/34715963/62490032-a91b6d80-b7c8-11e9-9d02-ce297d734eca.gif)
