### ISSUE TITLE
Twip button should be disabled on private tabs and private tab with Tor

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4593]
## Description 

Twip button should be disabled on private tabs and private tab with Tor

## Steps to Reproduce

   1. Login to Twitter account in a private window
   2. Tip button is shown on tweets
   3. Clicking it doesn't do anything

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/58290467-d474eb80-7d87-11e9-8723-24e3ea7e2303.png)

## Expected result:
Twipping should be only available on normal tabs/windows

## Reproduces how often: 

Easy 

## Brave version (brave://version info)

Brave | 0.67.55 Chromium: 75.0.3770.38 (Official Build)nightly (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

## Miscellaneous Information:

cc: @emerick @mandar-brave @alexwykoff @jenn-rhim @brave/legacy_qa

**Comment by emerick** [comment]
@simonhong See how we currently handle `rewardsEnabled` and `inlineTipSetting` in `components\brave_rewards\resources\extension\brave_rewards\background.ts`. I was thinking we could combine all three checks (rewards enabled, inlineTips enabled, and incognito not active) into a single message called `tippingEnabled`. Up to you, though!

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.107 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified no in-line tip button on Twitter for both private and Tor windows.
* Verified there is in-line tip button on Twitter for normal windows.
