### ISSUE TITLE
Add a tip counter next to the button to indicate how many tips the tweet received and/or an indication that I already tipped this tweet.

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#4596]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
@jenn-rhim please create shorter title and add more info how all of this should work in the ticket

**Comment by NejcZdovc** [comment]
closing as stale
