### ISSUE TITLE
Move navigator.connection behind shields

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#4598]
`navigator.connection`
https://wicg.github.io/netinfo/

Allows websites to read the current network state, and track changes.  Fingerprint / tracking risk

We ship, other browsers don't use currently

**Comment by snyderp** [comment]
part of https://github.com/brave/brave-browser/issues/2655

**Comment by tomayac** [comment]
Hey @pes10k and Brave folks,

I found this issue and see that you're considering to move the current Network Information API implementation behind shields. Coincidentally, I have rebooted the API recently. This is all in a relatively early stage, but I thought now would be a good time to get your feedback on the proposal: 

- Motivational doc: https://docs.google.com/document/d/1RDA23zSNdDuIcxZTX9Xo3zlD2fxf8dZg9-e0YaJQv0g/edit?usp=sharing
- Explainer: https://github.com/tomayac/netinfo/blob/relaunch/README.md
- Spec draft: https://ghcdn.rawgit.org/tomayac/netinfo/relaunch/index.html

Here is the short version:

```js
// Is the current network a metered network according to the OS-level setting
// in, e.g., Android or Windows, i.e., _without_ the UA guesstimating it. The UA
// may provide its own (override) setting, though:
navigator.connection.metered;
// false

// What is the sustained connection speed, as measured on the OS-level (à la
// `nettop`) for a sliding window and bucketed in buckets of exponentially
// growing size in bit per second, e.g., 25,000,000 (25 Mbit/s), 50,000,000
// (50 Mbit/s). It's fine to report `Infinity` if the user agent doesn't want to
// reveal more, or if the sustained speed isn't known yet.
navigator.connection.metered;
// 50000000

// Changes to either of the attributes are exposed via an event:
navigator.connection.addEventListener("change", (event) => {
  console.log(event);
});
```

Each of the attributes is accompanied by a client hint header that reflects the attribute:

```bash
Sec-CH-Metered-Connection: 1
Sec-CH-Sustained-Speed: 50000000
```

Thanks in advance for your thoughts, here, or in the motivational document.

Cheers,
Tom

**Comment by pes10k** [comment]
closing this in favor of `https://github.com/brave/brave-browser/issues/20122`
