### ISSUE TITLE
Modify postinstall script to allow non-release channel builds to inject referral codes into browser state for osx

### ISSUE THREAD

**Issue by aekeus** [brave/brave-browser#4600]
## Test plan
See https://github.com/brave/brave-core/pull/2549

## Description
Please modify the postinstall script to allow non-release channel builds to inject referral codes into browser state for osx.

**Comment by aekeus** [comment]
cc @bsclifton @emerick @simonhong

**Comment by bsclifton** [comment]
Checking this out now...

**Comment by bsclifton** [comment]
Fix completed, ready for review 😄 
https://github.com/brave/brave-core/pull/2549

**Comment by btlechowski** [comment]
It seems to be macOS only issue. I added the proper label.

**Comment by LaurenWags** [comment]
Verified passed with

Brave	0.67.112 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
Revision	7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS	Mac OS X

* Verified STR from description, verified promo code in promoCode file and on brave://local-state

![Screen Shot 2019-07-24 at 2 26 11 PM](https://user-images.githubusercontent.com/28145373/61819200-841a1880-ae20-11e9-93de-a81b2976fa5e.png)

![Screen Shot 2019-07-24 at 2 27 49 PM](https://user-images.githubusercontent.com/28145373/61819208-87150900-ae20-11e9-8962-932fee988922.png)


Brave	0.68.104 Chromium: 75.0.3770.100 (Official Build) dev (64-bit)
Revision	cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS	Mac OS X

* Verified STR from description, verified promo code in promoCode file and on brave://local-state

![Screen Shot 2019-07-24 at 2 30 12 PM](https://user-images.githubusercontent.com/28145373/61819217-8b412680-ae20-11e9-889f-8d09885eabd7.png)

![Screen Shot 2019-07-24 at 2 31 18 PM](https://user-images.githubusercontent.com/28145373/61819225-8e3c1700-ae20-11e9-9c4d-a2e68bb14901.png)


Brave	0.69.77 Chromium: 76.0.3809.62 (Official Build) nightly (64-bit)
Revision	7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS	Mac OS X

* Verified STR from description, verified promo code in promoCode file and on brave://local-state

![Screen Shot 2019-07-24 at 2 32 29 PM](https://user-images.githubusercontent.com/28145373/61819236-9300cb00-ae20-11e9-938b-4771d1bd3cdc.png)

![Screen Shot 2019-07-24 at 2 33 20 PM](https://user-images.githubusercontent.com/28145373/61819242-95fbbb80-ae20-11e9-8544-b55c8801daec.png)

cc @kjozwiak for a second check on macOS

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.5 x64` using the following builds:

Installed `0.70.6 Chromium: 76.0.3809.62` via `Brave-Browser-Nightly-RED194.pkg` and ensured the following
* `~/Library/Application\ Support/BraveSoftware/Brave-Browser-Nightly/promoCode` was created
* `promoCode` displayed `RED194`
* `promoCode` was removed when starting `0.70.6 Chromium: 76.0.3809.62`
* `"promo_code": "RED194"` was visible under `brave://local-state`

Installed `0.69.91 Chromium: 76.0.3809.62` via `Brave-Browser-Dev-KAM253.pkg` and ensured the following
* `~/Library/Application\ Support/BraveSoftware/Brave-Browser-Dev/promoCode` was created
* `promoCode` displayed `KAM253`
* `promoCode` was removed when starting `0.69.91 Chromium: 76.0.3809.62`
* `"promo_code": "KAM253"` was visible under `brave://local-state`

Installed `0.68.109 Chromium: 76.0.3809.62` via `Brave-Browser-Dev-KAM159.pkg` and ensured the following
* `~/Library/Application\ Support/BraveSoftware/Brave-Browser-Dev/promoCode` was created
* `promoCode` displayed `KAM159`
* `promoCode` was removed when starting `0.68.109 Chromium: 76.0.3809.62`
* `"promo_code": "KAM159"` was visible under `brave://local-state`

Installed `0.67.117 Chromium: 76.0.3809.62` via `Brave-Browser-BRA194.pkg` and ensured the following
* `~/Library/Application\ Support/BraveSoftware/Brave-Browser/promoCode` was created
* `promoCode` displayed `BRA194`
* `promoCode` was removed when starting `0.67.117 Chromium: 76.0.3809.62`
* `"promo_code": "BRA194"` was visible under `brave://local-state`
