### ISSUE TITLE
odd tip banner display when publisher have a custom banner

### ISSUE THREAD

**Issue by eljuno** [brave/brave-browser#4602]
## Description 

If publishers have a custom tip banner set for all their channel, when user try to tip a tweet, it show `username on Twitter` text in front of the banner.

## Steps to Reproduce

   1. Set custom banner on publisher account
   2. Enable "Same banner content for all channels" (may or may not necessary -- I have this option enabled)
   3. Try to tip a tweet e.g. https://twitter.com/eljuno_/status/755536392042586112

## Actual result:

![twip-banner](https://user-images.githubusercontent.com/25360853/58355577-0331b580-7e9f-11e9-8bf2-cab023bd186e.png)

## Expected result:
Only custom banner that shown on tipping banner

## Reproduces how often: 

Easy

## Brave version (brave://version info)

0.67.55 Chromium: 75.0.3770.38

## Version/Channel Information:

- Can you reproduce this issue with the current release? NDA
- Can you reproduce this issue with the beta channel? NDA
- Can you reproduce this issue with the dev channel? NDA
- Can you reproduce this issue with the nightly channel? YES

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Tipping banner shown properly if user try to sent tip via Rewards panel

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.106 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2504
![Screen Shot 2019-07-10 at 5 53 40 PM](https://user-images.githubusercontent.com/28145373/61007890-08a66a80-a33c-11e9-93f2-dfd2bb1a9d0a.png)

* Verified that tipping from panel continues to show banner as expected (no `username on Twitter` text displayed) for custom banners.
![Screen Shot 2019-07-10 at 5 56 42 PM](https://user-images.githubusercontent.com/28145373/61007916-18be4a00-a33c-11e9-80f7-8b888175b4d8.png)
