### ISSUE TITLE
CDM utility process not starting when tab triggers Widevine install in new profile

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4604]
## Description 
Unable to stream Netflix on a clean profile. Works on Release channel. Does not work on Beta, Dev, Nightly.

## Test plan / Steps to Reproduce

   1. Clean profile - install C75 version of Beta, Dev, Nightly.
   2. Navigate to netflix.com and login.
   3. Enable widevine and try to stream something.
   4. You will get error as below.
   5. If you restart the browser or reload netflix in a new tab , it will work.

Note - after restart the widevine component updates.

## Actual result:
![Screen Shot 2019-05-24 at 5 28 05 PM](https://user-images.githubusercontent.com/28145373/58357575-537e2880-7e49-11e9-9c12-64fd7e557af0.png)

## Expected result:
Able to stream Netflix.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.65.110 Chromium: 75.0.3770.38 (Official Build) beta(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

Brave | 0.66.75 Chromium: 75.0.3770.38 (Official Build) dev(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

Brave | 0.67.55 Chromium: 75.0.3770.38 (Official Build) nightly(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, does not occur on 0.64.77
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? n/a - Rewards not enabled.
- Is the issue reproducible on the latest version of Chrome? no, could not reproduce with

Google Chrome | 75.0.3770.51 (Official Build) beta (64-bit)
-- | --
Revision | 0d407327777ca67c0f1874f3b198de4e177eecab-refs/branch-heads/3770@{#762}
OS | Mac OS X

## Miscellaneous Information:

cc @brave/legacy_qa @rebron

**Comment by LaurenWags** [comment]
Not sure if it's important, but this is what I see on brave://components for Widevine:
![Screen Shot 2019-05-24 at 5 36 10 PM](https://user-images.githubusercontent.com/28145373/58357855-71985880-7e4a-11e9-8283-8cd6917f36ff.png)

**Comment by LaurenWags** [comment]
Updated issue with additional details - a restart fixes the issue. Seems to be installed with component version 4.10.1146.0 and after restarting the component is updated to 4.10.1196.0. Note - just going to brave://components and updating the component doesn't work, a restart is required.
Thanks @kjozwiak for helping sort out these details 👍

**Comment by srirambv** [comment]
No issue on Linux with clean profile on Nightly. Able to install Widevine and stream videos instantly. Widevine component is not shown on Linux which is a known issue (#3955)

**Comment by bbondy** [comment]
Can we remove p1 and blocker now since restarting the browser fixes it?
Is there anything for us to do for this issue?
Sri for Linux it's not installed as a component so that's expected.

**Comment by kjozwiak** [comment]
> Can we remove p1 and blocker now since restarting the browser fixes it?

Was removed ~3 days ago by @LaurenWags when we realized that restarting the browser fixes the issue. I'm going to change it to a `P3`. Please change if there's any objections.

@simonhong mentioned that switching tabs also fixes this problem which I confirmed. @simonhong mentioned that when you initially launch netflix.com in a new tab that triggers the Widevine install, the CDM process doesn't get started.

@simonhong please add more information if I've missed something 👍

**Comment by simonhong** [comment]
@kjozwiak Perfect! 👍

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.65.113 Chromium: 75.0.3770.38 (Official Build) beta(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

* Verified STR from description.
