### ISSUE TITLE
WhatsApp Web not working on nightly (works on dev)

### ISSUE THREAD

**Issue by agentofuser** [brave/brave-browser#4608]
## Description 

WhatsApp Web tell me to "update Chrome" when I try to open it on Nightly.

## Steps to Reproduce

   1. https://web.whatsapp.com

## Actual result:

![image](https://user-images.githubusercontent.com/45322175/58371693-7cea9300-7ee1-11e9-9490-81514a1ef0c7.png)

## Expected result:
Opens WhatsApp Web.

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

0.67.55 Chromium: 75.0.3770.38 (Official Build) nightly (64-bit)
Revision	3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS	Mac OS X
JavaScript	V8 7.5.288.16
Flash	(Disabled)
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.38 Safari/537.36

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Not sure.
- Can you reproduce this issue with the beta channel?
Not sure.
- Can you reproduce this issue with the dev channel?
No. It works on Dev.
- Can you reproduce this issue with the nightly channel?
Yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No.
- Does the issue resolve itself when disabling Brave Rewards?
No.
- Is the issue reproducible on the latest version of Chrome?
No.

**Comment by bsclifton** [comment]
Possibly related to our recent UA change
cc: @bbondy @simonhong

**Comment by srirambv** [comment]
Confirmed due to the new Brave UA. Even adding a full major/minor version to Brave doesn't fix the issue. Only way is to remove Brave UA

**Comment by kjozwiak** [comment]
+1 to get this fixed. Heavy WhatsApp desktop user.

**Comment by Sberla996** [comment]
+1 really need Whatsapp web to work!

**Comment by kjozwiak** [comment]
+1 from https://twitter.com/torgo/status/1135085452317331456

**Comment by kjozwiak** [comment]
Went through the following using `macOS 10.14.5 x64`:

* `0.68.6 Chromium: 75.0.3770.38` (nightly) - Reproducible
* `0.67.72 Chromium: 75.0.3770.38` (dev) - Reproducible
* `0.66.80 Chromium: 75.0.3770.38` (beta) - Currently not reproducible
* `0.65.116 Chromium: 75.0.3770.38` (release RC) - Currently not reproducible

Looks like `0.68.x` (nightly) & `0.67.x` (dev) are affected.

**Comment by kjozwiak** [comment]
@rebron this issue is getting more attention, we should get this fixed sooner than later.

**Comment by bsclifton** [comment]
@kjozwiak this is tied to the UA. We have an issue proposing a fix here (which is what you want to thumbs up / prioritize):
https://github.com/brave/brave-browser/issues/4641

**Comment by bsclifton** [comment]
Marked as `QA/No` since this feature was introduced and then reverted

**Comment by GeetaSarvadnya** [comment]
+1 from https://community.brave.com/t/whatsapp-web-doesnt-work-on-latest-brave/62444/10

**Comment by vitorHoller** [comment]
Another Whatsapp issue;
![wpp issue](https://user-images.githubusercontent.com/58081540/97989110-d0daf600-1dbc-11eb-927f-f018e19c9f5e.png)
