### ISSUE TITLE
[Feature Request] Firefox like Awesomebar feature & Separate address-box/search-box

### ISSUE THREAD

**Issue by p32929** [brave/brave-browser#4610]
Recently I switched from Firefox to brave & I'm loving it. The only thing I'm missing in Brave is the Firefox AwesomeBar & separate address-box/search-box. So, I'm requesting these two features for Brave:
1. Ability to have separate address-box and search-box (like firefox)
2. Firefox like awesomebar feature.
( the text below is for those, who don't know what awesome bar is: 
Suppose, you entered an IP address like "192.168.0.109:1111"
In firefox, if you write "109", it will show "192.168.0.109:1111" as a suggestion to go/enter. But Brave don't )

Thanks :)

**Comment by rebron** [comment]
Closing as wontfix/invalid. Hi @p32929. For item #1, we're not going to separate address bar and search bar like Firefox. We're going to keep them together. 

For item #2, we do have autocomplete in the address bar. If you have that IP address as bookmarks or history, it should show up as a suggestion.

**Comment by p32929** [comment]
Okay, don't separate the addressbar and search bar. But for #2, here's two screenshot below.
From firefox:
![Screenshot (4)](https://user-images.githubusercontent.com/6418354/58530309-18407880-8200-11e9-91ae-b32ca906ec8b.png)

and from brave:
![Screenshot (5)](https://user-images.githubusercontent.com/6418354/58530314-1e365980-8200-11e9-99e0-0945498c9195.png)

I hope, you can see the difference. Brave autocomplete not even showing the IP address.
