### ISSUE TITLE
Forks of Brave may Interrupt Brave Ads Flow

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#4611]
## Description
I noticed a couple days ago that Brave Ads ceased to appear. I still received the occasional Ad Notification on the desktop, but clicking that notification didn't create a new ad tab in Brave. It only dismissed the notification. Ads continued to work in my Nightly, Dev, and Beta builds as far as I am aware.

To confirm the issue, I opened Brave and navigated to lichess.org. When it's your turn to move, but lichess is blurred, a notification is displayed. When clicked, that notification returns you to the game tab. When Dissenter is installed, that notification triggers dissenter instead of the active game tab in Brave.

## Steps to Reproduce
1. Install Dissenter (then close, and return to Brave)
2. Wait for an ad notification to appear
3. Click the ad notification

## Actual result:
Nothing happens (besides the dismissal of the notification)

## Expected result:
An ad is displayed in Brave

## Reproduces how often: 
Always

## Brave version (brave://version info)
0.64.77

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Miscellaneous Information:
It's possible that Dissenter (which is a fork of Brave) mistakenly registers itself somewhere in Windows as "Brave", thus intercepting these Brave Ads messages.

**Comment by rebron** [comment]
cc: @rebron to reproduce.

**Comment by jonathansampson** [comment]
I just reproduced this again (after installing Dissenter last night).

**Comment by jonathansampson** [comment]
I found out what causes this. Dissenter (as a fork of Brave) re-uses Brave's "toast activator" CLSID. Brave specifies various CLSIDs for the Release, Beta, Dev, and Nightly builds in [chromium_install_modes.cc](https://github.com/brave/brave-core/blob/9972dbdb29df509049c74ffee6b540a585ed57fd/chromium_src/chrome/install_static/chromium_install_modes.cc):

      {06C9646D-2807-44C0-97D2-6DA0DB623DB4}  // Brave-Browser.
      {9560028D-0CCA-49F0-8D47-EF22BBC40BA7}  // Brave-Browser-Beta.
      {20B22981-F63A-47A6-A547-691CC94CAEE0}  // Brave-Browser-Dev.
      {F2EDBC59-7217-4DA5-A259-0302DA6A00E1}  // Brave-Browser-Nightly.

The CLSID is stored in Windows' registry, where it holds a path to `notification_helper.exe`:

    HKCU\Software\Classes\CLSID\{06C9646D-2807-44C0-97D2-6DA0DB623DB4}\LocalServer32

When Dissenter is installed, the path to `notification_helper.exe` is overwritten, pointing away from Brave's copy and to Dissenter's copy. If a user were to run Dissenter first, and later install Brave, I believe it would also cause issues.

## Solution

To resolve this issue, search the Windows Registry for the above path. Update the reference to point to Brave's `notification_helper.exe`. This should be all that is needed.
