### ISSUE TITLE
Brave is closed on SketchUp running

### ISSUE THREAD

**Issue by edSarti** [brave/brave-browser#4614]
## Description 

Sketchup (free online version) suddenly closes Brave, including other open instances / windows.

## Steps to Reproduce

   1. Open SketchUp (https://app.sketchup.com/app?hl=en) on a separated Brave window.
   2. The problem occurs both continuously using SketchUp and when the SketchUp window is left idle for a few hours.
   3. The behavior happens randomly and does not always occur. So it's hard to catch it.

## Actual result:
Brave is completely closed (including separated other windows of Brave).

## Expected result:
Brave never closed.

## Reproduces how often: 
This issue happened 3 times in about 100 hours of use of SketchUp (free online version). 
From the user's point of view, the occurrence is random. That is, there is no special event related to this issue.

## Brave version (brave://version info)

Brave | 0.64.77 Chromium: 74.0.3729.169 (Versão oficial) 64 bits
-- | --
Revisão | 78e4f8db3ce38f6c26cf56eed7ae9b331fc67ada-refs/branch-heads/3729@{#1013}
SO | Windows 10 OS Build 17134.766
JavaScript | V8 7.4.288.28
Flash | (Desativada)
Agente do usuário | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Do not tested.
- Can you reproduce this issue with the dev channel? Do not tested.
- Can you reproduce this issue with the nightly channel? Do not tested.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Do not tested. 
- Does the issue resolve itself when disabling Brave Rewards? Do not tested.
- Is the issue reproducible on the latest version of Chrome? No.

## Miscellaneous Information:

No additional information.

**Comment by rebron** [comment]
@edSarti Do you have any crash reports when you run into this issue? Need some more info for this one. Can you go to brave://crashes and go ahead and send the crash report, report back here with the id?

**Comment by iefremov** [comment]
@edSarti please reopen if you ever hit it again
