### ISSUE TITLE
Update default tipping banner text

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#4616]
**Current text:**
![image](https://user-images.githubusercontent.com/9574457/58430327-33e53b00-80a9-11e9-9b90-9000aa54dbd9.png)

```
You can support this site by sending a tip. It’s a way of thanking them for making great content. Verified content creators get paid for their tips during the first week of each calendar month.

If you like, you can schedule monthly tips to support this site on a continuous basis.
```

**New text:**
```
You can support this content creator by sending a tip. It’s a way of thanking them for making great content. Verified creators get paid for their tips during the first week of each calendar month.

If you like, you can schedule monthly tips to support this creator on a continuous basis.
```

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.106 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2506 (using staging environment)
![Screen Shot 2019-07-10 at 5 47 49 PM](https://user-images.githubusercontent.com/28145373/61007509-fe37a100-a33a-11e9-83f8-cc63e482c1f8.png)
