### ISSUE TITLE
Scrolling fails to function as expected using Google Maps

### ISSUE THREAD

**Issue by IdlePhysicist** [brave/brave-browser#4617]
## Description 

When I use Google Maps the two finger trackpad scrolling is hyper sensitive and makes zooming in/out impossible to use practically. This does not occur in Firefox, Chromium, or Safari.

## Steps to Reproduce

   1.  Install Brave
   2. Go to Google Maps with shields up.
   3. Zoom using trackpad.

## Actual result:
Zooming/scrolling is hyper sensitive to movement on the trackpad. Makes for poor user experience. 

Deactivating shields, allows for a better user experience, the zooming is somewhat less sensitive but it is still jumpy and not smooth compared to the other browsers mentioned above.

## Expected result:
Smooth zooming like in the browsers mentioned above. 

## Reproduces how often: 
Easily reproduced, this happens whenever I use Google Maps in Brave.

## Brave version (brave://version info)
I am running Brave 0.64.77 on a Mid-2012 MacBook Pro with macOS Mojave 10.14.5

```
Brave | 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)
Revision | 78e4f8db3ce38f6c26cf56eed7ae9b331fc67ada-refs/branch-heads/3729@{#1013}
```

## Version/Channel Information:

I only use the stable release and have not yet tested with the development releases.

- Can you reproduce this issue with the current release? - Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
    - In part yes, it becomes more usable. But the scrolling is still jumpy compared with the other browsers mentioned above.
- Does the issue resolve itself when disabling Brave Rewards? - N/A
- Is the issue reproducible on the latest version of Chrome? - No

**Comment by rebron** [comment]
@IdlePhysicist Can you try in brave://settings/system and turning off hardware acceleration to see if that changes the behavior?

**Comment by IdlePhysicist** [comment]
@rebron I use Brave with hardware acceleration turned off.

**Comment by IdlePhysicist** [comment]
Yesterday I turned on hardware acceleration on and raised shields, this fixed the smooth scrolling. 

But I have also tried to reproduce the error with an external mouse (HW acc. off) and it is not producible. This leads me to believe that there is some issue between the Mac's trackpad and Brave.

**Comment by rebron** [comment]
@IdlePhysicist How is it working with hardware acceleration on and shields down? Any difference? I'm thinking this is a hardware acceleration issue only.

**Comment by bsclifton** [comment]
@IdlePhysicist makes sense - we have a few other trackpad issues I believe... will try to find/link them

**Comment by IdlePhysicist** [comment]
@rebron Sorry it took a little while to get back to you. I can now confirm that Brave exhibits expected behaviour with hardware acceleration enabled, and shields down.

**Comment by maximbaz** [comment]
I have a suspicion that this issue is caused by canvas fingerprint protection, and if it was spoofed instead of blocked (#5196), this wouldn't be an issue. I think this because I had used an extension to spoof canvas fingerprint in Chromium, and as far as I remember Google Maps worked smoothly (that extension is currently broken so I cannot easily verify).

**Comment by romant** [comment]
using Google's Maps is very choppy compared to Chrome, and even Safari

.. and this is with HW accel turned on, and shield completely down for it.

any other workarounds ?

thanks !

**Comment by greenspoon** [comment]
This issue is still present. Tested with Brave v0.68.139 with macOS 10.14.6 - MacBook Pro (15-inch, 2017).
Also I can confirm that disabling the shields resolves in a kind of better experience, but still choppy scrolling.
Playing further with the shield settings I found a setting that will prevent the scrolling from jumping.

<img width="369" alt="Screenshot 2019-09-23 at 10 18 46" src="https://user-images.githubusercontent.com/7674211/65411133-5e8f9800-ddec-11e9-881b-70837a8f6291.png">

But if you enable "Cross-site trackers blocked" and or "Device recognition attempts blocked" the jumping appears again.

I hope this helps you.

**Comment by panchalkalpesh** [comment]
Following fixed this issue / worked for me:

### 1. [Enable Hardware Acceleration](brave://settings/?search=hardware+acceleration)

<a href="brave://settings/?search=hardware+acceleration" target="_blank">Open this Setting<a> or enter the following in the address bar:
```
brave://settings/?search=hardware+acceleration
```
![Screenshot 2020-05-23 at 7 06 16 PM](https://user-images.githubusercontent.com/1808686/82742182-b76f5180-9d28-11ea-95df-fbb9248c3654.png)

### 2. Set Shield to block cross-site fingerprinting and cross-site cookies

![Screenshot 2020-05-23 at 7 04 56 PM](https://user-images.githubusercontent.com/1808686/82742184-b807e800-9d28-11ea-9e5a-af4e0505ea2e.png)


#### Tested on:
```
Brave version 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)
macOS Mojave 10.14.3
```


Hope this helps others. 
Cheers!!

**Comment by bsclifton** [comment]
Since there haven't been concrete steps to reproduce and this has been open for a while, I'm going to close. Def suggest trying the work-around above 😄

**Comment by michaeltrollan** [comment]
For anyone who ends up in this issue and none of the other solutions are working, here is a short guide:

First, try going to Google Maps in an incognito window. (File > New Private Window). If the scrolling is smooth there, then likely it's a settings issue, and you might be seeing the "lite" version of Google Maps.

This YouTube video has 9 possible solutions. https://www.youtube.com/watch?v=n5skrIePo50

(For me, it was solution #2 that permanently fixed it in Brave.)
