### ISSUE TITLE
Brave Software Brave help  needs to changed to Brave Help

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4618]
## Description 

Brave Software Brave help  needs to changed to Brave Help

## Steps to Reproduce

   1. Open settings page
   2. Search for an in-existent functionality like `test` 
   3. Help center link has a weird text says `Brave Software Brave Help`

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/58436245-63d51400-8092-11e9-8484-d138bebb12d6.png)

## Expected result:
Should just say Brave help

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.65.107 Chromium: 75.0.3770.38 (Official Build) beta(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

**Comment by bbondy** [comment]
Does title casing depend on the OS?

**Comment by srirambv** [comment]
Actually looks like Linux only. I don't see it on Windows/mac release version

Windows:
![image](https://user-images.githubusercontent.com/17010094/58508072-27bcb480-8161-11e9-87b1-76f4cd9fcb7c.png)
macOS:
<img width="1440" alt="Screen Shot 2019-05-28 at 3 56 42 PM" src="https://user-images.githubusercontent.com/17010094/58508125-533f9f00-8161-11e9-9cec-779cf2b27593.png">

**Comment by srirambv** [comment]
Issue happens when locale is set to anything else apart from English (US). Setting it to English(Canada) reproduces the issue

**Comment by btlechowski** [comment]
Reproduced on Windows 7 x64 

Brave | 1.3.85 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Windows 7 Service Pack 1 (Build 7601.24530)

**Comment by LaurenWags** [comment]
Reproduces on macOS also (Australian English)

Brave | 1.3.86 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | macOS Version 10.14.6 (Build 18G103)

<img width="1178" alt="Screen Shot 2020-01-08 at 4 22 16 pm" src="https://user-images.githubusercontent.com/28145373/72022201-dc619d00-323d-11ea-8af7-77584f1398b1.png">

**Comment by kjozwiak** [comment]
@rebron @bsclifton not sure how important it is to be displaying `Brave Software Brave help` vs `Brave help` but as mentioned above, most locales that aren't US will see the above.

Maybe we would reconsider the `P4` rating and move it to a `P3`?

**Comment by bsclifton** [comment]
Looks like somewhere along the line (maybe Chromium 80 upgrade?) this was resolved:
<img width="924" alt="Screen Shot 2020-03-04 at 3 27 00 PM" src="https://user-images.githubusercontent.com/4733304/75928898-a0594b80-5e2c-11ea-8e83-386f2b40d6de.png">

**Comment by rebron** [comment]
Tried in 1.4.95 for Windows Australian English and again in Canadian English/Canada eh ;-) and saw only Brave Help.
