### ISSUE TITLE
No audio output in Google Meet (blocked by autoplay)

### ISSUE THREAD

**Issue by jameshalsall** [brave/brave-browser#4621]
## Description 
When joining Google Meet there is no audio output. If I join using Google Chrome then I hear audio no problem. I have compared Google Meet settings between Brave and Chrome and they are identical, so this points to a problem with Brave itself.

It has always worked for me in the past but the recent updates to Google Meet that were released may have caused this issue to occur.

## Steps to Reproduce

   1. Open up https://meet.google.com/_meet in Brave
   2. Click the settings cog in the top right
   3. Press "Test" next to the Speakers setting and you should hear no output

## Actual result:
Audio should work in Google Meet.

## Expected result:

No audio is output in the speakers when using Google Meet.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
```
Brave    | 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)
Revision | 78e4f8db3ce38f6c26cf56eed7ae9b331fc67ada-refs/branch-heads/3729@{#1013}
OS       | Mac OS X
```

## Version/Channel Information:
~I have not tried.~
I can reproduce this issue in the Beta version too.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? No.

**Comment by YvanDaSilva** [comment]
I had the same problem, and by switching default sound cards now I have the opposite problem.
I have audio output but not audio input.

I can hear everyone clearly.
People are not able to hear me. The input icon shows the microphone line as active (the little spectrum moves up and down).

I also disabled every "Brave" feature to see if it changes anything, it ends with the same result.

This is not reproducible on the latest version of chrome with the same exact settings and accounts.
Note: I can switch inputs as much as I want on Chrome it doesn't effect my ability to have output and input sound. However on Brave, even after a full restart the outcome is always uncertain.

**Comment by Aracki** [comment]
Same problem here with: 
Brave | 0.64.77
OS | MacOS Mojave

**Comment by rebron** [comment]
@rebron to reproduce.

**Comment by YvanDaSilva** [comment]
What more info do you need ?

**Comment by mdczaplicki** [comment]
Same here 
Version 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
Linux Mint 19

**Comment by paride5745** [comment]
I had the same issue, then I disabled Brave Shield and everything works fine.

Brave Version 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
Manjaro KDE

**Comment by cmer** [comment]
Thanks @JacobMuchow, confirmed working for me too!

**Comment by fmarier** [comment]
`meet.google.com` is [already whitelisted](https://github.com/brave/autoplay-whitelist/blob/6e87f7244e23885c7fe7e96f1266886d06394092/data/autoplay.json#L27) so there might be another hostname/domain that needs to be whitelisted.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified STR from the description
- Verified that click "Test" output the audio
![image](https://user-images.githubusercontent.com/38657976/75869568-c2a09880-5e2f-11ea-93e5-f7c0f1319aed.png)

**Comment by Tectract** [comment]
Bump / reopen please. I'm experiencing this issue with the latest Brave and autoplay / shields settings is having no effect for me. Google meet will NOT play any sound, other sites play sound just fine.

**Comment by bsclifton** [comment]
@Tectract you might visit brave://settings/socialBlocking and then enable `Allow Google login buttons on third party sites`. Let us know if that helps

**Comment by sp** [comment]
Same problem here, just started in the last couple weeks.

Version 1.17.75 Chromium: 87.0.4280.88 (Official Build) (x86_64)
macOS Mojave 10.14.6

**Comment by Hansie020** [comment]
On macOS Catalina 10.15.7 and Version 1.18.70 Chromium: 87.0.4280.101 (Official Build) (x86_64) I have the same issue.

**Comment by posita** [comment]
I'm also seeing this with Catalina 10.15.7 and Version 1.22.70 Chromium: 89.0.4389.105 (Official Build) (x86_64) with autoplay allowed globally (no site-specific settings).

**Comment by Tectract** [comment]
> Allow Google login for extensions

Hmmmmm this seems to be weakening my security to try and route around a bug?

Can we just get the issue fixed for this one site somehow without me needing to do that? Can we make it so google login can only access extensions published by google?

**Comment by zigojacko** [comment]
Experiencing this issue in Jan 2022 still !!

Couldn't figure it out so switched to a different browser just to use Google Meet which worked fine. It's definitely something to do with the Brave Shields tracking but nothing I tried resolved it.

**Comment by fmarier** [comment]
I used Google Meet in Brave (beta) yesterday and it worked fine. Are you sure you gave it all of the permissions it needs?
![Screenshot from 2022-01-06 13-38-57](https://user-images.githubusercontent.com/167821/148455796-c4380b5b-f471-4064-a372-0dc0bb199c8e.png)

**Comment by ccollova** [comment]
I have the same problem but - strange enough - it happens on all chromium-based browsers where i am logged in, not only on one computer, but cross-devices...  ¯\_(ツ)_/¯   I mean: I have a MacBook Pro, three Chromebooks, one Windows machine. Wherever (i.e. from any device using a chromium-based browser) I access Google Meet, I get no sound output. It works on Firefox though. Which leads me to think that (1) being Firefox not based on Chromium that makes it work (2) the problem should lie in some chromium-based extension or setting that is synched cross platform whenever I access my account.
