### ISSUE TITLE
brave://version doesn't show our custom UA properly

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#4623]
As https://github.com/brave/brave-core/pull/2442 merged, `brave://version` also should display custom UA.
Note: `navigator.userAgent` api displays our custom UA properly.

Steps to reproduce:
1. Launch browser and load `brave://version`
2. Check ua contains `brave/xx`

**Comment by bsclifton** [comment]
Marking as `QA/No` and `release-notes/exclude` as test plan was updated in https://github.com/brave/brave-core/pull/2442

General functionality covered by https://github.com/brave/brave-browser/issues/1052 which is labelled appropriately

**Comment by bsclifton** [comment]
Milestone removed after this was reverted. Test plan was already updated in https://github.com/brave/brave-core/pull/2442 and revert squashed both commits together
