### ISSUE TITLE
add a feature flag for enabling translation

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#4626]
## Description 
Add a feature flag for enabling translation service. Translation prompt/icon should not show in the url bar and translation context menu "Translate to 'language'" should not appear.  

Feature flag for translation should be enabled for beta/dev/nightly channel.
Feature flag for translation should be disabled for release channel.

## Brave version (brave://version info)
Feature flag should be disabled for release channel starting with 65.x.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.5 x64` using the following build:

Brave | 0.65.115 Chromium: 75.0.3770.38 (Official Build) (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

* went through the test plan outlined under https://github.com/brave/brave-core/pull/2542
* ensured that the the translate model and `Offer to translate pages that aren't in a language you read` are still available under the other channels

* **`0.65.115 Chromium: 75.0.3770.38` Example:**

<img width="703" alt="Screen Shot 2019-05-31 at 2 11 19 AM" src="https://user-images.githubusercontent.com/2602313/58685398-98262a00-8349-11e9-91d6-55b5aec931bd.png">

* **`0.68.5 Chromium: 75.0.3770.38` & `0.66.80 Chromium: 75.0.3770.38` Example:**

<img width="709" alt="Screen Shot 2019-05-31 at 2 11 26 AM" src="https://user-images.githubusercontent.com/2602313/58685428-b4c26200-8349-11e9-94e0-b33d6b6fe95c.png">

<img width="454" alt="Screen Shot 2019-05-31 at 2 14 12 AM" src="https://user-images.githubusercontent.com/2602313/58685475-de7b8900-8349-11e9-8d15-de1903e46b87.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.65.116 Chromium: 75.0.3770.38 (Official Build) (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Linux

* Verified test plan and no option to `Offer to translate` shown in languages
* Found issue on all channel so logged #4664
