### ISSUE TITLE
Rewards notification to try Ads is incorrectly showing - Follow up to 4339

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4627]
## Description 
Originally reported as part of #4339 

In some cases Ads were being turned off on upgrade- when this happened users were given a Rewards notification (visible via BAT logo) to enable Ads.

After #4339 was fixed (Ads are not disabled when updating from 0.64.26 to 0.67.63 on Nightly), but I still get a notification on BAT logo to try Ads in this upgrade scenario.

## Steps to Reproduce

   1. Install 0.64.26 on Nightly.
   2. Enable Rewards
   3. View an Ad. If brave://rewards page is open, close it.
   4. Update to 0.67.63.

## Actual result:
There is a notification on your BAT logo telling you that Brave Ads have arrived. If you go to brave://rewards, you will see that Ads are on and the notification goes away (without interaction from you).

![4339-test-nightly064x](https://user-images.githubusercontent.com/28145373/58495950-c8ea4180-8146-11e9-8888-0a05456ab017.gif)

## Expected result:
No notification on BAT logo to try Ads as Ads should still be enabled.

## Reproduces how often: 
easily

## Brave version (brave://version info)
0.64.26 updated to 0.67.63

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? unsure (4339 has not been uplifted to this channel yet)
- Can you reproduce this issue with the dev channel? unsure (4339 has not been uplifted to this channel yet)
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @brave/legacy_qa @jsecretan @ryanml

**Comment by GeetaSarvadnya** [comment]
The issue is Reproducible - Upgraded `0.64.10` to `0.67.66` - There is Turn On Ads notification even though Ads switch is enabled in brave://rewards

Brave | 0.67.66 Chromium: 75.0.3770.38 (Official Build) nightly (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Windows 10 OS Version 1803 (Build 17134.523)

**Comment by tmancey** [comment]
@LaurenWags This ticket will be superseded and subsequently fixed by #4383, are you happy for us to close this ticket please?

**Comment by LaurenWags** [comment]
sure @tmancey  - if we're doing additional notifications per https://github.com/brave/brave-browser/issues/4383 then I think this can be closed.
