### ISSUE TITLE
How to export .deb or .exe file after make my chnages

### ISSUE THREAD

**Issue by XtreemSolution** [brave/brave-browser#4635]
I have make all my changes and want to rebrand it for my internal use. I did all the changes but now I'm not sure how to export .deb file or .exe file from the source. 

I have tested my code by using

`npm run build`
`npm start`

Above both 2 command are working well but now I'm unable to find the correct command to export it as an installer for my other PCs

**Comment by bsclifton** [comment]
Hey there - you'll want to follow the guide here:
https://github.com/brave/brave-browser/wiki

Be sure to install all the pre-reqs. After that, you should be able to run:
```
npm run build -- Release
npm run create_dist -- Release
```

**Comment by XtreemSolution** [comment]
@bsclifton  Thank you !!

But still I'm facing an issue when trying to run 

`npm run create_dist -- Release`

But npm run build is working OK

`Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: the DIE at offset 0x62a5f1ba has a DW_AT_abstract_origin attribute referring to the die at offset 0x62a5f417, which either was not marked as an inline, or comes later in the file
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: warning: function at offset 0x62a5f1ba has no name
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: the DIE at offset 0x62a5fa19 has a DW_AT_abstract_origin attribute referring to the die at offset 0x62a6127a, which either was not marked as an inline, or comes later in the file
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: the DIE at offset 0x62a601c3 has a DW_AT_abstract_origin attribute referring to the die at offset 0x62a611e4, which either was not marked as an inline, or comes later in the file
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: in compilation unit '../../headless/lib/browser/headless_print_manager.cc' (offset 0x62a6323e):
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: warning: failed to demangle _strtod
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: warning: failed to demangle _strtof
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: warning: failed to demangle _system
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: warning: failed to demangle _strerror
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: warning: failed to demangle _fputs
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: warning: failed to demangle _fwrite
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: warning: failed to demangle _fopen
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: warning: failed to demangle _freopen
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: warning: failed to demangle _wcsftime
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: warning: failed to demangle _clock
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: warning: failed to demangle _mktime
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: warning: failed to demangle _strftime
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: the DIE at offset 0x62a6c822 has a DW_AT_abstract_origin attribute referring to the die at offset 0x62a6c847, which either was not marked as an inline, or comes later in the file
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: warning: function at offset 0x62a6c822 has no name
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: the DIE at offset 0x62a6c8ac has a DW_AT_abstract_origin attribute referring to the die at offset 0x62a6c8f8, which either was not marked as an inline, or comes later in the file
Brave Browser Framework.dSYM/Contents/Resources/DWARF/Brave Browser Framework: warning: function at offset 0x62a6c8ac has no name
**ninja: build stopped: subcommand failed.
null
null**
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave@0.68.18 create_dist: `node ./scripts/commands.js create_dist "Release"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the brave@0.68.18 create_dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/xtreem/.npm/_logs/2019-06-18T10_17_11_243Z-debug.log
Xtreems-Mac-mini:brave-browser xtreem$ `

**Comment by bsclifton** [comment]
@XtreemSolution running `create_dist` is going to try to do signing, which is something you can't really do (at least not authoritative signing)

You should be able to edit the .GN files to remove the signing requirement
