### ISSUE TITLE
DomDistiller debug level is outputted into the console

### ISSUE THREAD

**Issue by MRVDH** [brave/brave-browser#4636]
## Description 
Console outputs `DomDistiller debug level: 0` on all pages

## Steps to Reproduce
1. Navigate to any page.
2. Open the dev console.

## Actual result:
![Console](https://i.imgur.com/NgakpfI.png "Console")

## Expected result:
No debug messages. This is an official build.

## Brave version (brave://version info)
Version 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by cherurg** [comment]
Also, sometimes I get 

`VM77078:140  Exception happened in EmbedExtractors: (TypeError) : Cannot read property 'getAttribute' of null`

when I use certain functions from `rxjs`.

**Comment by kaleazy** [comment]
I second this, how do we remove?

**Comment by nikahmadz** [comment]
It's superbly annoying

**Comment by MRVDH** [comment]
I don't understand why this has been labeled as priority/P5. As a web developer I use Brave to test and debug applications. It's annoying to keep seeing this message. Besides that, things like these should be in beta versions of Brave, not in public releases.

**Comment by nikahmadz** [comment]
Still at P5? and now came up a new annoying log on all page console.

> [Deprecation] HTML Imports is deprecated and will be removed in M80, around February 2020. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.

**Comment by Lorkios** [comment]
Hey, anything planned for this "issue" :yum: ?

**Comment by Coupz** [comment]
Bump, because this is also on production version with `gridsome build` on Netlify.

**Comment by GMModded** [comment]
Still an open issue..?
Would like to remove this debug message

**Comment by rafaelcastrocouto** [comment]
over a year ... time to "fix" this

**Comment by bsclifton** [comment]
With latest version (`1.4.95`) which uses Chromium 80, I'm not seeing this anymore. I know it can be frustrating, but compared to the other backlog of issues this one didn't qualify as high priority

@rafaelcastrocouto @GMModded @Coupz @louislefebvre can you update to latest and confirm if you see the issue? I've made sure to pick `All levels` in console and I'm not seeing it

**Comment by rafaelcastrocouto** [comment]
Yes it still happens.
![Untitled](https://user-images.githubusercontent.com/422159/75725675-b72e5f80-5cbf-11ea-816a-e25b8e1895bd.png)

**Comment by bsclifton** [comment]
Closing as I believe this is now fixed on all release channels (latest is on Chromium 84)
