### ISSUE TITLE
follow up - CDM utility process not starting when tab triggers Widevine install in new profile

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#4646]
Follow up to https://github.com/brave/brave-browser/issues/4604
The automatic reload implemented in https://github.com/brave/brave-core/pull/2514 does not fix the issue on Windows

## Description 
Unable to stream Netflix on a clean profile. Works on Release channel. 

## Test plan / Steps to Reproduce

   1. Clean profile
   2. Navigate to netflix.com and login.
   3. Enable widevine and try to stream something.

Note - fixes after manual page reload

## Actual result:
![Screen Shot 2019-05-24 at 5 28 05 PM](https://user-images.githubusercontent.com/28145373/58357575-537e2880-7e49-11e9-9c12-64fd7e557af0.png)
The automatic reload implemented in https://github.com/brave/brave-core/pull/2514 is triggered.
Widevine component is not updated

## Expected result:
Able to stream Netflix.

## Reproduces how often: 
easily

## Brave version (brave://version info)
Brave | 0.65.114 Chromium: 75.0.3770.38 (Official Build) (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Windows 10 OS Version 1803 (Build 17134.765)

cc @brave/legacy_qa @rebron @simonhong @bsclifton

**Comment by simonhong** [comment]
I think this can be happen because reloading is requested right after requesting install widevine.
This should be improved like this - reloading after widevine component install is finished.
This can be happened on MacOS also.

**Comment by GeetaSarvadnya** [comment]
The issue is Reproducible consistently on Windows 10 x64 - `0.65.114`.

**Comment by bsclifton** [comment]
@GeetaSarvadnya do you know if the issue happens also with our current release version? (0.64.x?) Given that a refresh fixes this, maybe we had never noticed before

NOTE: I ran into the same issue when testing... but when using Netflix's  `<-` back button (in their UI - not the browser back button) and picking the same program again, it works 🤷‍♂

**Comment by kjozwiak** [comment]
I went through this a bit last night/today and got mixed results as well. It usually works pretty well but sometimes you'll still get the `Missing Component` message and you'll need to refresh the page or open a new tab. `macOS x64` seems to be working a a lot smoother. @LaurenWags and myself confirmed that we're not getting the `Missing Component` message anymore via https://github.com/brave/brave-browser/issues/4604. But on Win, there's maybe some type of race condition that happens and the refresh doesn't happen in time?

> NOTE: I ran into the same issue when testing brave/brave-core#2514... but when using Netflix's <- back button (in their UI - not the browser back button) and picking the same program again, it works.

It's pretty easy to recover from the error, you can usually do the following whenever you run into the above:

* refresh the Netflix page and the error goes away
* open a new tab and re-load Netflix
* restart the browser

**Comment by simonhong** [comment]
@kjozwiak I think it's not strange for getting `Missing Component` message after enabling widevine on MacOS and Windows both.
The reason is our current implementation is reloading request is issued right after requesting registering widevine. If widevine registering is completed synchronously, we can't see this. but it would be in async.

**Comment by simonhong** [comment]
If this is started to happen since C75 or 65.x, I'm not sure but I assume there would be some modification in component update logic.(upstream side or our side..)

**Comment by simonhong** [comment]
I think we can fix this but seems not urgent issue for now because just reloading again can fix this :)

**Comment by kjozwiak** [comment]
> I think we can fix this but seems not urgent issue for now because just reloading again can fix this :)

Agreed 100%. Really easy to fix by simply refreshing, opening a new tab or restarting the browser 👍

**Comment by GeetaSarvadnya** [comment]
https://github.com/brave/brave-browser/issues/4646#issuecomment-497229141

@bsclifton when the issue was raised, I have verified this issue on both 0.64.x and 0.65.x. I was unable to reproduce the issue consistently in 0.64.77. @btlechowski was unable to reproduce the issue in 0.64.77 either.
https://bravesoftware.slack.com/archives/GAA4017R7/p1559197011001000?thread_ts=1559174016.115100&cid=GAA4017R7

Today, I have tested again the issue is Reproducible continuously in 0.64.x also.

**Comment by btlechowski** [comment]
@GeetaSarvadnya Thanks for checking. I tested few more times and was also able to repro the issue on 0.64.77.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.7.78 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Ubuntu 18.04 LTS

Verified Linux install steps still work
1. Install Widevine
![image](https://user-images.githubusercontent.com/34715963/77964929-49864b00-72e0-11ea-9d41-802a3988a79d.png)

2. Restart browser
![image](https://user-images.githubusercontent.com/34715963/77965104-a1bd4d00-72e0-11ea-8683-28a3744a1665.png)

3. Verified netflix streams without problems
