### ISSUE TITLE
getting stuck while try install at "waiting to download"

### ISSUE THREAD

**Issue by fakirpic** [brave/brave-browser#4647]
![image](https://user-images.githubusercontent.com/5578194/58605940-4ececf80-82a2-11e9-9866-e8f0e3a9351e.png)

it keeps stucking at here. i tried other builds its same for me, my internet connection is fine

**Comment by bsclifton** [comment]
Hi @fakirpic - what version of Windows are you running? 

Do you have anything Brave related in your host file? (some Muon users would make the update server unroutable, to avoid automatic updates). Lastly, curious if you can try with Windows Firewall disabled?

**Comment by fakirpic** [comment]
> Hi @fakirpic - what version of Windows are you running?
> 
> Do you have anything Brave related in your host file? (some Muon users would make the update server unroutable, to avoid automatic updates). Lastly, curious if you can try with Windows Firewall disabled?

i just removed everything in my hosts file  and disabled firewall completely still same error,but i tried it my second computer in same network windows 8.1 it just works, what could be the reason
...

update! while writing these lines it just installed after waiting a couple of minutes at waiting download section. maybe it tried alternative hosts to download? not sure. but my connection speed is not slow its around 90mbps it should not take that much time

![image](https://user-images.githubusercontent.com/5578194/58715150-ee897c00-83ce-11e9-9219-ab7f4b8fc0d1.png)

**Comment by mbacchi** [comment]
This looks like a possible updates server outage at the time of the original problem. I'll close for now, but if this persists please reopen.
