### ISSUE TITLE
Browser Tests (BraveAppMenuBrowserTest && BraveRewardsBrowserTest) failing on master

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#4648]
`brave-browser-build-darwin-test-browser - #402 Failure after 1 min 33 sec (Open)
2 Failed Tests:
    BraveAppMenuBrowserTest.BasicTest after 1.3 sec
    BraveRewardsBrowserTest.PanelShowsCorrectPublisherData after 2.3 sec`

**Comment by NejcZdovc** [comment]
This was introduced with https://github.com/brave/brave-core/pull/2491, so we need to fix it in 67 as well

**Comment by NejcZdovc** [comment]
`BraveAppMenuBrowserTest.BasicTest` was introduced with https://github.com/brave/brave-core/pull/2496
