### ISSUE TITLE
Feature: Verified Twitter publishers should display "verified" icon/branding per-tweet

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#4649]
## Description 

Currently, verified Twitter publishers display "verified" icon on their twitter page: 
![image](https://user-images.githubusercontent.com/3299098/58614391-1234b100-826d-11e9-988e-511906b56b03.png)

Verified Twitter publishers should display the verified icon per-tweet, so users can tell they're verified from their home page/feed:

![image](https://user-images.githubusercontent.com/3299098/58614121-5ffce980-826c-11e9-93a8-f0139a496e10.png)

@mandar-brave @petemill @rebron 

## Miscellaneous Information:
 
There was a design discussion surrounding visibility and "blending" too heavily into twitter UI -- this approach would be simple and avoids these concerns:
https://bravesoftware.slack.com/archives/C07HD31EZ/p1557279876080500

**Comment by RetroCraft** [comment]
This should also be generalized to Reddit and other future integrations.

**Comment by Brave-Matt** [comment]
A few +1s from Reddit:
https://www.reddit.com/r/brave_browser/comments/cn1pvu/suggestion_hide_the_tip_button_on_social_media/

**Comment by Miyayes** [comment]
Last time we discussed this, I don't think it would be feasible. Since we would have to check our API for every single creator. This was more practical back in the day when the browser just downloaded the full set of creators.
