### ISSUE TITLE
Sync UI paddings

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#4650]
## Description 

Paddings of boxes on Sync UI page became zero.

## Steps to Reproduce

   1. Open brave://sync/
## Actual result:

![Screenshot from 2019-05-30 12-38-26](https://user-images.githubusercontent.com/24739341/58629438-2a481700-82e5-11e9-9c76-6995d889a8dc.png)
![Screenshot from 2019-05-30 12-36-37](https://user-images.githubusercontent.com/24739341/58629439-2a481700-82e5-11e9-8c51-620ac60df8f2.png)

## Expected result:
How it looked before
![Screenshot from 2019-05-30 14-14-53](https://user-images.githubusercontent.com/24739341/58629513-59f71f00-82e5-11e9-95e6-0ee57256211f.png)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 0.67.69 Chromium: 75.0.3770.38 (Official Build)nightly (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the dev channel? no 
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by btlechowski** [comment]
Reproduced on 

Brave | 0.67.73 Chromium: 75.0.3770.38 (Official Build) dev (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Windows 7 Service Pack 1 (Build 7601.24465)

![image](https://user-images.githubusercontent.com/34715963/59140556-ac000a80-899f-11e9-89ff-7e9d0d1a47eb.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.106 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified STR from description
![Screen Shot 2019-07-10 at 2 24 50 PM](https://user-images.githubusercontent.com/28145373/60994484-9f642e80-a31e-11e9-806c-8fcf582e7291.png)
![Screen Shot 2019-07-10 at 2 24 07 PM](https://user-images.githubusercontent.com/28145373/60994488-a25f1f00-a31e-11e9-8e6b-7294e96891c3.png)
