### ISSUE TITLE
Shortcut is not working on Windows

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#4654]
Shortcuts created by app menu (`Move Tools` -> `Create Shortcut...`) doesn't start application.

https://github.com/brave/brave-browser/issues/3750 is original issue that reported this error.
Created this issue for easier PR managing because macos also has same issue but each one will be handled by separate PRs.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.66.87 Chromium: 75.0.3770.80 (Official Build) beta (64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Windows 7 Service Pack 1 (Build 7601.24465)

Used test plan from https://github.com/brave/brave-core/pull/2544. Created shortcuts for different domains.
