### ISSUE TITLE
Offer to translate button is missing on Linux

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4664]
## Description 

Found while testing #4626, Linux doesn't show an option for `Offer to translate` under language settings

## Steps to Reproduce

   1. Install any channel build which has https://github.com/brave/brave-core/pull/2542 in it
   2. Open Settings and navigate to language option
   3. Doesn't show an option to enable/disable `Offer to translate` 

## Actual result:

![image (2)](https://user-images.githubusercontent.com/17010094/58725498-50d18500-83ad-11e9-9a76-5b4ddf26edad.png)
![image (1)](https://user-images.githubusercontent.com/17010094/58725500-50d18500-83ad-11e9-9447-bfe9f7d16c40.png)

## Expected result:
Should show an option to offer to translate on all channels except release

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All versions that have https://github.com/brave/brave-core/pull/2542 in them

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

## Miscellaneous Information:

@rebron @kjozwiak need to consider pulling this into 65.x release

**Comment by cg505** [comment]
Using Arch Linux with the binary release .zip (`brave-v0.xx.xx-linux-x64.zip`), everything works as expected. Tested release, beta, and nightly.

**Comment by yrliou** [comment]
Works as expected for me on all channels by installing .deb using Ubuntu 18.04.
Version 0.68.6 Chromium: 75.0.3770.38 (Official Build) nightly (64-bit)
Version 0.66.80 Chromium: 75.0.3770.38 (Official Build) beta (64-bit)
Version 0.67.72 Chromium: 75.0.3770.38 (Official Build) dev (64-bit)
Version 0.65.116 Chromium: 75.0.3770.38 (Official Build) (64-bit)

**Comment by yrliou** [comment]
@srirambv Could you make sure Language is clicked? Otherwise it won't have that item.
<img width="677" alt="Screen Shot 2019-05-31 at 12 36 45 PM" src="https://user-images.githubusercontent.com/4730197/58730456-119d3700-83a1-11e9-9070-36c8f0f96186.png">
There should be `^` next to Language if you opened it.

**Comment by srirambv** [comment]
Yup able to see the options when the language section is expanded. We should probably expand it by default. Spell check has an option outside the language dropdown which might cause confusion
