### ISSUE TITLE
webusb support

### ISSUE THREAD

**Issue by mrose17** [brave/brave-browser#4669]
_sadly, webusb appears to be table stakes..._

## Description 
The browser does not support webusb.

## Steps to Reproduce
   1. Connect to a service that requires webusb, e.g., beta.shapeshift.com
   2. Attempt to pair your KeepKey

## Actual result:
<img width="370" alt="Screen Shot 2019-05-31 at 14 00 16" src="https://user-images.githubusercontent.com/400552/58728789-4616f000-83ad-11e9-9312-af5e4856858e.png">

## Expected result:
Success

## Reproduces how often: 
100%

## Brave version (brave://version info)
```Brave is up to date
Version 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)```

## Version/Channel Information:
- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? yes
- Does the issue resolve itself when disabling Brave Rewards? yes
- Is the issue reproducible on the latest version of Chrome? no, it supports webusb

## Miscellaneous Information:
None.

**Comment by simonhong** [comment]
Brave returns `undefined` for `navigator.usb`.

**Comment by kjozwiak** [comment]
Similar findings under https://github.com/brave/brave-browser/issues/3120#issuecomment-467736609.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.5 x64` using the following build:

Brave | 0.66.88 Chromium: 75.0.3770.87 (Official Build) beta(64-bit)
-- | --
Revision | 9dc58a2353af60ab2b48bab98a25bc43ed59085d-refs/branch-heads/3770@{#982}
OS | Mac OS X

* ensured that `navigator.usb` isn't returning `undefined`
* connected to https://connect.trezor.io with the `Trezor` and updated the FW without any issues
* connected to https://mycrypto.com with the `Trezor` without any issues
* connected to https://mycrypto.com with the `Ledger Nano S` without any issues

<img width="1558" alt="Screen Shot 2019-06-12 at 11 24 27 PM" src="https://user-images.githubusercontent.com/2602313/59401765-ce13d700-8d69-11e9-8852-be9e6789ad4c.png">

<img width="1350" alt="Screen Shot 2019-06-12 at 11 30 09 PM" src="https://user-images.githubusercontent.com/2602313/59401876-3a8ed600-8d6a-11e9-8150-b4b554dc0356.png">

<img width="1518" alt="Screen Shot 2019-06-12 at 11 30 54 PM" src="https://user-images.githubusercontent.com/2602313/59401879-3e225d00-8d6a-11e9-9095-f9a8c337ea42.png">
