### ISSUE TITLE
Installed app from dmg doesn't start on MacOS

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#467]
## Description 

Installed app quitted immediately

## Steps to Reproduce
   1.  Install from dmg
   2. Run brave app from launcher
   3. 

## Actual result:

Quitted right after running

## Expected result:
Running w/o quit

## Reproduces how often: 

Always

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Mac OS X

@LaurenWags mind double checking this one as well before we mark it as passed?
