### ISSUE TITLE
Sync screen in distorted in Dev and Nightly channels

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#4670]
## Description 

Sync screen in distorted in Dev and Nightly channels

## Steps to Reproduce

   1. Clean profile Dev/Nightly
   2. Select sync option from Hamburger menu
   3. Establish sync between the desktop through sync code

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/58729073-0c260800-8406-11e9-93d1-5d76bdf0e270.png)

![image](https://user-images.githubusercontent.com/38657976/58729110-24962280-8406-11e9-8072-7b1e1f388657.png)

## Expected result:
Alignment of objects is completely distorted

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.67.72 Chromium: 75.0.3770.38 (Official Build) dev (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Windows 10 OS Version 1803 (Build 17134.523)

Brave | 0.68.2 Chromium: 75.0.3770.38 (Official Build) nightly (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa

**Comment by rebron** [comment]
@AlexeyBarabash @cezaraugusto Can you guys take a look?

**Comment by AlexeyBarabash** [comment]
This duplicates https://github.com/brave/brave-browser/issues/4650 .
