### ISSUE TITLE
Google Calendar Extension won't authenticate

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#4672]
## Description 

When installing the Google Calendar extension, authorization is required independently from browser auth. This takes place from within the app itself. After selecting "Authorize...", extension process halts and gets stuck on `Authorizing`:

![image](https://user-images.githubusercontent.com/3299098/58735485-66e04500-83af-11e9-9bf5-c7f921d20874.png)

No options found in Settings, Shields or ext. settings resolve the issue or change behavior. Console view on extension background page has no output. 
Tested on both macOS Mojave (latest) and Windows 10 OS.

## Steps to Reproduce

   1. Download the [Google Calendar extension](https://chrome.google.com/webstore/detail/google-calendar/gmbgaklkmjakoegficnlkhebmhkjfich)
   2. Install and click `Authorize Google Calendar`

## Actual result:

Auth process halts, hangs on `Authorizing` message

## Expected result:
Google Calendar to authorize and authenticate my account. 

## Reproduces how often: 

Always 

## Brave version (brave://version info)

0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)
--
Revision | 78e4f8db3ce38f6c26cf56eed7ae9b331fc67ada-refs/branch-heads/3729@{#1013}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? ✅ 
- Can you reproduce this issue with the beta channel? ✅ 
- Can you reproduce this issue with the dev channel? ✅ 
- Can you reproduce this issue with the nightly channel? ✅ 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

Users reporting the same behavior -- not the first time I've seen it. Worth addressing given it's popularity.
https://community.brave.com/t/google-calendar-by-manas-tungare-will-not-authorise-with-google-in-brave/50628

**Comment by rebron** [comment]
cc: @ryanb Can you take a look?

**Comment by phelix001** [comment]
bump

**Comment by glyko** [comment]
Up again! This is the one thing keeping me from switching to Brave completly.
@ryanb

**Comment by dchaebae** [comment]
Bump! thought this would be fixed for 1.0

**Comment by bsclifton** [comment]
cc: @jumde - is this related to the work you did w/ https://github.com/brave/brave-core/pull/3784?

**Comment by jumde** [comment]
@bsclifton - this is unrelated, will investigate.

**Comment by richmahn** [comment]
@jumde Any news on this? Not able to authenticate as well.

**Comment by Wizardling** [comment]
Yeah, this has been a lingering incompatibility since I switched to Brave a year ago. It's the only extension left that I want to use, but cannot.

**Comment by ryanbr** [comment]
Similar (and maybe related) to the issue with https://github.com/brave/brave-browser/issues/3650   Enabling `Use Google Services for Push Messaging` makes no difference.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.14.66 Chromium: 85.0.4183.83 (Official Build) dev (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
- Verified STR from the description
- Google calendar is authorized using Gmail account without any hanging or freezing
- Verified able to open Google calendar and create an event in the calender

**Comment by GalianFuria** [comment]
Still hapening in - Versión 1.14.84 Chromium: 85.0.4183.121 (Build oficial) (64 bits).

Unable to sign in in Google Calendar Extension and unable to sign in with "Checker Plus for Google Calendar" - Reports Network Error

**Comment by jumde** [comment]
@GalianFuria - Could you try enabling `Allow Google login for extensions` in `brave://settings/extensions` and check if it works for you. Thanks!
