### ISSUE TITLE
Allow video play when using container APIs

### ISSUE THREAD

**Issue by Sondro** [brave/brave-browser#4673]
## Description 

Not sure if this is a duplicate of #2792, but both Chrome and Safari mobile allow you to use APIs to build your own video container interface to play videos.

Right now the autoplay block catches the playing event.

## Steps to Reproduce

API examples provided here: https://ginpei.github.io/html5-youtube.js/

**Comment by rebron** [comment]
Yes. Closing. Dupe of #2792 Thanks for additional examples.
