### ISSUE TITLE
Cannot Signup on Yesware

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#4675]
## Description 
Users cannot sign up to the free trial of Yesware.

## Steps to Reproduce
1. Navigate to https://www.yesware.com/sign-up/
2. Attempt to sign up 

## Actual result:
Nothing happens.

## Expected result:
Form is submitted and user moves to another page.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
0.64.77

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  No

## Miscellaneous Information:
Stable (0.64.77) shows the following blocked scripts:
- https://event-tag.yesware.com/analytics.js/v1/0lBUpy1Asj7cbodrTbGsEAWxRtKAtbXG/analytics.min.js
- https://cdn.evgnet.com/beacon/yesware/engage/scripts/evergage.min.js
- https://p.typekit.net/p.gif

**Comment by ryanbr** [comment]
So clicking on "https://www.yesware.com/sign-up/'
selecting the Gmail.com option; then select Get started. 

Got forwarded to the 'accounts.google.com' that seemed okay? well it worked for me. Note; I didn't go through the entire signup process.

**Comment by jonathansampson** [comment]
@ryanbr Did you have shields down?

**Comment by ryanbr** [comment]
I see it now, seems the site signin feature is forcing it to go through doubleclick.net->accounts.google.com (maybe related)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e66f43bc0313fc92e55e684d5ba19fb2f04ef6e0

Took a bit too debug, but this should fix it.

**Comment by bsclifton** [comment]
Closing as this should be fixed... @jonathansampson can you confirm?

**Comment by jonathansampson** [comment]
@bsclifton Appears to work!
