### ISSUE TITLE
How to fix lifecycle Failed to exec init script

### ISSUE THREAD

**Issue by ErwinDecenternet** [brave/brave-browser#4676]
## Description 
I tried to build Brave Browser from the latest version in the git repo and followed this instructions
https://github.com/brave/brave-browser/wiki
the last command i entered was: npm run init

## Steps to Reproduce

   1. intall all prerequisites in https://github.com/brave/brave-browser/wiki
   2. git clone https://github.com/brave/brave-browser.git
   3. npm run init

## Actual result:
Downloading 6 files took 50.281000 second(s)
Hook ''C:\BraveClone\brave-browser\vendor\depot_tools\win_tools-2_7_13_chromium7_bin\python\bin\python.exe' src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --num_threads=4 --bucket chromium-binary-patching/zucchini_testdata --recursive -d src/components/zucchini' took 59.20 secs
Running hooks:  96% (75/78) bootstrap
________ running 'C:\BraveClone\brave-browser\vendor\depot_tools\win_tools-2_7_13_chromium7_bin\python\bin\python.exe src/brave/script/bootstrap.py' in 'C:\BraveClone\brave-browser'
npm WARN tarball tarball data for typescript@3.3.3333 (sha512-JjSKsAfuHBE/fB2oZ8NxtRTk5iGcg6hkYXMnZ3Wc+b2RSqejEqTaem11mHASMnFilHrax3sLK0GDzcJrekZYLw==) seems to be corrupted. Trying one more time.
npm ERR! path C:\BraveClone\brave-browser\src\brave\node_modules\.staging\typescript-1cb16b6b\lib\typescriptServices.js
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\BraveClone\brave-browser\src\brave\node_modules\.staging\typescript-1cb16b6b\lib\typescriptServices.js'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\BraveClone\brave-browser\src\brave\node_modules\.staging\typescript-1cb16b6b\lib\typescriptServices.js'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\BraveClone\brave-browser\src\brave\node_modules\.staging\typescript-1cb16b6b\lib\typescriptServices.js'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path: 'C:\\BraveClone\\brave-browser\\src\\brave\\node_modules\\.staging\\typescript-1cb16b6b\\lib\\typescriptServices.js' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\BraveClone\\brave-browser\\src\\brave\\node_modules\\.staging\\typescript-1cb16b6b\\lib\\typescriptServices.js\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\BraveClone\\brave-browser\\src\\brave\\node_modules\\.staging\\typescript-1cb16b6b\\lib\\typescriptServices.js',
npm ERR!   parent: 'brave-core' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Winux\AppData\Roaming\npm-cache\_logs\2019-06-01T02_10_29_628Z-debug.log

Traceback (most recent call last):
  File "src/brave/script/bootstrap.py", line 79, in <module>
    sys.exit(main())
  File "src/brave/script/bootstrap.py", line 33, in main
    update_node_modules('.')
  File "src/brave/script/bootstrap.py", line 69, in update_node_modules
    execute_stdout(args, env)
  File "C:\BraveClone\brave-browser\src\brave\script\lib\util.py", line 187, in execute_stdout
    execute(argv, env)
  File "C:\BraveClone\brave-browser\src\brave\script\lib\util.py", line 175, in execute
    raise e
subprocess.CalledProcessError: Command '['npm.cmd', 'install']' returned non-zero exit status -4048
Error: Command 'C:\\BraveClone\\brave-browser\\vendor\\depot_tools\\win_tools-2_7_13_chromium7_bin\\python\\bin\\python.exe src/brave/script/bootstrap.py' returned non-zero exit status 1 in C:\BraveClone\brave-browser
Hook ''C:\BraveClone\brave-browser\vendor\depot_tools\win_tools-2_7_13_chromium7_bin\python\bin\python.exe' src/brave/script/bootstrap.py' took 379.13 secs
null
null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave@0.68.5 init: `node ./scripts/sync.js --init`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brave@0.68.5 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Winux\AppData\Roaming\npm-cache\_logs\2019-06-01T02_10_58_484Z-debug.log

## Expected result:
It should have exit 0 without any issues and next will proceed with the build
npm run build

## Reproduces how often: 
only tried once. since it took overnight to download all the other files during npm run init

## Brave version (brave://version info)
Bump version 0.68.7
https://github.com/brave/brave-browser/commit/8a0a86b7b64573ee8267a8178d363c5a6bd71475

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
@ErwinDecenternet you should be able to try again (without having to download everything again) by running the following:
`npm run sync -- --all`

Can you please try that and let us know if you still get an error 😄

**Comment by slavko993** [comment]
> @ErwinDecenternet you should be able to try again (without having to download everything again) by running the following:
> `npm run sync -- --all`
> 
> Can you please try that and let us know if you still get an error smile

Hello,
I had the same issue, but after running it with python2 inside virtual envairment, it was fixed. Now I am getting similar error, but instead on beggining of init, it's happening at the end of it.

`Error: Command '/home/slavko/temp-python/bin/python src/third_party/binutils/download.py' returned non-zero exit status 1 in /home/slavko/brave-browser
Hook '/home/slavko/temp-python/bin/python src/third_party/binutils/download.py' took 27.15 secs
null
null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave@0.68.22 init: `node ./scripts/sync.js --init`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the brave@0.68.22 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/slavko/.npm/_logs/2019-06-06T17_38_04_690Z-debug.log
`
I have tried running `npm run sync -- --all`, but same issue is happening.

**Comment by ErwinDecenternet** [comment]
Hi,

I tried again, and it worked! It seems one of the download was just corrupted and have to be retried as you said.

I also tried to build it and it works.

Question though, if i need to make changes/adjustments, What IDE should i  use? If its visual studio, why I don't see .sln file to open the entire project. I only see .sln for submodules.

Thanks for the help.

Erwin

**Comment by ErwinDecenternet** [comment]
> > @ErwinDecenternet you should be able to try again (without having to download everything again) by running the following:
> > `npm run sync -- --all`
> > Can you please try that and let us know if you still get an error smile
> 
> Hello,
> I had the same issue, but after running it with python2 inside virtual envairment, it was fixed. Now I am getting similar error, but instead on beggining of init, it's happening at the end of it.
> 
> `Error: Command '/home/slavko/temp-python/bin/python src/third_party/binutils/download.py' returned non-zero exit status 1 in /home/slavko/brave-browser Hook '/home/slavko/temp-python/bin/python src/third_party/binutils/download.py' took 27.15 secs null null npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! brave@0.68.22 init: `node ./scripts/sync.js --init`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the brave@0.68.22 init script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /home/slavko/.npm/_logs/2019-06-06T17_38_04_690Z-debug.log
> `
> I have tried running npm run sync -- --all, but same issue is happening.

In my case the error happened because the file downloaded was corrupted (perhaps because of my intermittent internet connection). I never setup an virtual env. I just used my global settings latest updates on all which should patche all known bugs. 
I just retried installation/download with the command as suggested:

npm run sync -- --all

Hopefully you'll able to fix it too.
