### ISSUE TITLE
RelChannel Browser cannot join sync chain with Beta/Dev browsers

### ISSUE THREAD

**Issue by brianddk** [brave/brave-browser#4678]
## Description 

When creating a sync-chain with android, desktop-dev and desktop-beta browsers, the desktop-rel browser cannot join the chain.  Attempting to add it just results in a no action when clicking "Confirm sync Code".  Only way to dismiss the dialog is to click "Cancel"

## Steps to Reproduce

1. Install Dev channel of Brave.
2. Start a sync channel with brave-dev.
3. Install Brave on Android.
4. Add android to sync channel.
5. Install Beta channel of Brave.
6. Add brave-beta to the sync channel.
7. Install Release channel of Brave
8. Add brave-rel to sync channel.
9. Observe that Sync Code dialog won't dismiss after entering code.

## Actual result:

![image](https://i.redd.it/09m2bsbbdt131.jpg)

Clicking confirmation does not dismiss dialog

## Expected result:

I expect the behavior to either produce an error, or accept the code and dismiss the dialog.

## Reproduces how often: 

Reproduces every time in the desktop-rel browser, and not at all in desktop-beta or desktop-dev browsers

## Brave version (brave://version info)

* **Brave** 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)
* **Revision** 78e4f8db3ce38f6c26cf56eed7ae9b331fc67ada-refs/branch-heads/3729@{#1013}

## Version/Channel Information:

- Can you reproduce this issue with the current release? **Yes**
- Can you reproduce this issue with the beta channel? **No**
- Can you reproduce this issue with the dev channel? **No**
- Can you reproduce this issue with the nightly channel? **Unknown**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **No**
- Does the issue resolve itself when disabling Brave Rewards? **No**
- Is the issue reproducible on the latest version of Chrome? **N/A**

## Miscellaneous Information:

Perhaps this is related to the order added.  Perhaps only two desktop version can be on one chain.  Perhaps desktop-beta, desktop-dev, desktop-rel all share the same settings database.

**Comment by brianddk** [comment]
Note... sync code which is obscured is **NOT** my actual sync code.  It was just randomly generated for the screen shot.

**Comment by brianddk** [comment]
[Reddit post of this issue](https://www.reddit.com/r/brave_browser/comments/bvpw0w/relchannel_browser_cannot_join_sync_chain_with/)

**Comment by rebron** [comment]
cc: @rossmoody Will need to account for cross-channel (e.g. Brave Beta macOS, Brave Dev on Windows) sync via detection and error dialog, since we're not supporting cross-channel sync. Primary use case is release channel sync across all platforms.

**Comment by rebron** [comment]
@brianddk Are you still running into this issue? We were thinking maybe a firewall issue?

**Comment by brianddk** [comment]
I can't verify, I had to remove Brave because of: https://github.com/brave/brave-browser/issues/4904 .  I can go ahead and close since I no longer have a platform to test it on.

**Comment by tmanderson** [comment]
@rebron I'm currently getting this issue. I enter my sync code, as provided from another computer that has all my bookmarks and, when I click "confirm sync code" nothing happens.

**Comment by sparke16** [comment]
I've got the same issue. Confirm sync code doesn't work when trying to come over from mobile. Funny as when I clicked setup Mobile it crashes the browser each time so desktop setup was the last option. Nailed it!

**Comment by palunel** [comment]
Hey there, same issue here. Clicking the `Confirm Sync` button has no effect.  I am not coming from mobile but from my other Windows machine.

Version 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)
Windows 10 Home 1809 OS Build 17763.914

**Comment by Palik-ua** [comment]
I think i defeat it! Just try to enter incorrect words (i accidentally paste the combination twice) and hit Sync. Browser will show an error? than correct the combination and sync again.

**Comment by nama1510** [comment]
Same issue here, I have my laptop and my android device on a chain but when i try to add my desktop computer and click confirm it does nothing.
Brave Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)

**Comment by codesnippy** [comment]
Same issue here. I have my laptop and my android device on a chain. When I try my second laptop and click confirm it does nothing.
Brave Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
Debian 10

**Comment by aherstein** [comment]
This does not work for me. I am on Pop_OS (Linux) trying to sync to iOS. Both Brave versions are release

**Comment by 71walceli** [comment]
I have an issue with Sync. I can't leave a sync chain on my computer. The reason is that it stopped working altogether on my PC. It's broken since a few days ago, it's completely outdated. I was able to leave the chain from my phone though.

Every time I try to do it, Brave asks me for confirmation. I accept. As soon as I do, it gets to the general settings page (brave://settings/braveSync). I go back to it, and then it's all as it was, as if I didn't touch anything. It's like this when I try to toggle any setting, getting dismissed. whenever brave://settings/braveSync/setup loads. 

System info: 

Linux Mint 18.3
kernel: Linux HP-ProBook-6470b 4.15.0-122-generic #124~16.04.1-Ubuntu SMP Thu Oct 15 16:08:36 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
GPU: 00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09) (prog-if 00 [VGA controller])

I was unable to find issues similar to mine, I couldn't find it in the issues of this project either...

Should I create an issue about this? 

Thanks in advance...

**Comment by sujay1844** [comment]
same issue as @71walceli. It happens when I try to sync between Windows and Arch

**Comment by 71walceli** [comment]
I resorted to deleting, creating a new profile and copying every file to that other profile, then deleting all data. A very nasty workaround, which deleted every addon and every other Brave setting. What a workaround!
