### ISSUE TITLE
Cannot tip to Twitch channels

### ISSUE THREAD

**Issue by EthanCentaurai** [brave/brave-browser#4680]
## Description 

It looks like #1814 has appeared again as attempting to send a tip via Twitch shows "Twitch.tv" as the tip recipient instead of the channel. YouTube and Website tipping appears to be working as expected however.

## Steps to Reproduce

   1. Visit any Twitch channel.
   2. Click on Brave Rewards button.

## Actual result:

![image](https://user-images.githubusercontent.com/8914/58759627-f9562500-8524-11e9-8b78-524ffbae8eec.png)

## Expected result:
Rewards popup to show if the streamer is verified or not with a button to send a tip.

## Reproduces how often: 

Easily reproduced on Windows, macOS, and Android.

## Brave version (brave://version info)

- Brave | 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)
- Revision | 78e4f8db3ce38f6c26cf56eed7ae9b331fc67ada-refs/branch-heads/3729@{#1013}
- OS | Windows 10 OS Build 18362.116

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Haven't tested yet
- Can you reproduce this issue with the dev channel? Haven't tested yet
- Can you reproduce this issue with the nightly channel? Haven't tested yet

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by LaurenWags** [comment]
@EthanCentaurai Are you trying to tip while watching a VOD? if so, you're probably encountering this issue: https://github.com/brave/brave-browser/issues/3590 (for macOS, Windows, Linux).

Note, Twitch tipping is not implemented for Android yet, that's logged here: https://github.com/brave/browser-android-tabs/issues/1301

**Comment by EthanCentaurai** [comment]
Hello there. I am watching a live streamed video; not a VOD or a hosted channel or rerun.

**Comment by LaurenWags** [comment]
Thanks @EthanCentaurai 😄 Looks like I can reproduce with the following versions:

Brave | 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)
-- | --
Revision | 78e4f8db3ce38f6c26cf56eed7ae9b331fc67ada-refs/branch-heads/3729@{#1013}
OS | Mac OS X


Brave | 0.65.116 Chromium: 75.0.3770.38 (Official Build) (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X


Brave | 0.66.79 Chromium: 75.0.3770.38 (Official Build) beta(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X


Brave | 0.67.72 Chromium: 75.0.3770.38 (Official Build) dev(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

cc @NejcZdovc

**Comment by btlechowski** [comment]
Reproduced on Windows 10 x64

Brave | 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)
-- | --
Revision | 78e4f8db3ce38f6c26cf56eed7ae9b331fc67ada-refs/branch-heads/3729@{#1013}
OS | Windows 10 OS Build 17134.765


Brave | 0.65.116 Chromium: 75.0.3770.38 (Official Build) (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Windows 10 OS Version 1803 (Build 17134.765)




Brave | 0.66.79 Chromium: 75.0.3770.38 (Official Build) beta (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Windows 10 OS Version 1803 (Build 17134.765)


Brave | 0.67.72 Chromium: 75.0.3770.38 (Official Build) dev (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Windows 10 OS Version 1803 (Build 17134.765)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.65.120 Chromium: 75.0.3770.90 (Official Build) (64-bit)
-- | --
Revision | a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}
OS | Windows 7 Service Pack 1 (Build 7601.24468)

Verified test plan from https://github.com/brave/brave-core/pull/2618.

![image](https://user-images.githubusercontent.com/34715963/59521285-41355e80-8ecc-11e9-81e6-e8b2469f712a.png)
