### ISSUE TITLE
Brave becomes unresponsive — stale Helper processes

### ISSUE THREAD

**Issue by mwdiers** [brave/brave-browser#4689]
Over an extended period of time, usually several days, Brave will eventually stop responding to all input. All tools become grayed out. The UI in general still functions, i.e., you can switch tabs, scroll, etc. However, no links work. No Developer tools will open.

Restarting Brave at this point will result in a broken UI, with no working controls. This must be force-closed.

Restarting Brave once more will bring everything back to normal. However, all saved tabs / windows are gone.

When Brave reaches the state described above in the first paragraph and is first quit, the process monitor shows multiple Brave Browser Helper processes in a zombie state. If these processes are force closed before attempting to restart Brave, everything will be back to normal, and all saved tabs / windows will also be restored. This leads me to believe that the problem must be related to the Browser Helper.

## Steps to Reproduce
   1. Use Brave over the course of several days, opening and shutting down Brave as normal.
   2. Eventually the Developer tools will be disabled, no links will work, etc.
   3. Restart Brave. This will result in a broken UI missing bookmarks, etc.
   4. Restart Brave a second time. All functionality will be restored, but saved tabs and windows will be lost

## Reproduces how often: 
The problem is intermittent, and usually only manifests over the course of several days without a reboot.

## Brave version (brave://version info)
Brave | 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)
-- | --
Revision | 78e4f8db3ce38f6c26cf56eed7ae9b331fc67ada-refs/branch-heads/3729@{#1013}
OS | Mac OS X
JavaScript | V8 7.4.288.28
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

**Comment by AnthonyIV** [comment]
I am experiencing this as well, I did not read this before dealing with today's crash so I lost all saved tabs for a second time. The crash id for my crash is: 786d3027-8270-43ce-a811-523149a48d6d

macOS 10.14.5


Brave | 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)
-- | --
Revision | 78e4f8db3ce38f6c26cf56eed7ae9b331fc67ada-refs/branch-heads/3729@{#1013}
OS | Mac OS X
JavaScript | V8 7.4.288.28
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko)

**Comment by iefremov** [comment]
@mwdiers @AnthonyIV @mralexho please reopen if you experience this again
