### ISSUE TITLE
Launcher only shows one kind of channel app on MacOS

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#469]
When different channel's apps are installed, only one brave app is visible in launcher.
But, all apps are visible in application folder.
I tested this with my pending PR  - https://github.com/brave/brave-core/pull/208.

**Comment by simonhong** [comment]
Do we want to install different channel apps simultaneously? @bbondy @darkdh 
Also i'm not an expert about mac app.
So, I'm not sure this is possible or not. need help from macos expert.

**Comment by bbondy** [comment]
Yes we want to install different channels simultaneously.  We just have to make sure each app is named differently though.

**Comment by simonhong** [comment]
dmg from latest trunk has different app name(`Brave-Browser-Dev.app`, `Brave-Browser-Nightly.app`) and each have different `CrProductDirName`.
But, still launcher shows only one app that installed at first.
Did some test by changing some elements in `Plist.info` such as identifier, bundle name to make different on different app. but same result.

Need to investigate..

**Comment by simonhong** [comment]
To create proper app/dmg, https://github.com/brave/brave-browser/issues/153 should be resolved first. Each channel needs different BRANDING files.

**Comment by simonhong** [comment]
Before starting #153 , I tried with below BRANDING file in `chrome/app/theme/brave/` for `dev` channel with this [working branch](https://github.com/brave/brave-core/tree/mac_multiple_channel_install)
```
COMPANY_FULLNAME=Brave Software, Inc.
COMPANY_SHORTNAME=Brave Software
PRODUCT_FULLNAME=Brave-Browser-Dev
PRODUCT_SHORTNAME=Brave
PRODUCT_INSTALLER_FULLNAME=Brave Installer
PRODUCT_INSTALLER_SHORTNAME=Brave Installer
COPYRIGHT=Copyright 2016 The Brave Authors. All rights reserved.
MAC_BUNDLE_ID=org.brave.Brave.dev
MAC_CREATOR_CODE=Cr24
```

`yarn build Release --channel=dev --no_branding_update` is completed.
Running is failed with below error.
```
simon-home:src simonhong$ ./out/Release/Brave-Browser-Dev.app/Contents/MacOS/Brave-Browser-Dev
[0709/111111.524532:ERROR:icu_util.cc(114)] icudtl.dat not found in bundle
[0709/111111.525656:ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received.
Trace/BPT trap: 5
```
`yarn create_dist Release --channel=dev --no_branding_update` is failed during signing.

**Comment by RyanJarv** [comment]
So glancing through this I suspect this is related to the identifier not changing between releases.

```
  <key>CFBundleIdentifier</key>
  <string>org.brave.Brave</string>
```

Chromium uses the following:
```
com.google.Chrome
com.google.Chrome.beta
com.google.Chrome.dev
com.google.Chrome.canary
```
Unsure of the source but faintly recalling something along the lines of 'bad things happen' on this not being updated correctly.

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - PASSED

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

Brave | 0.56.1 Chromium: 70.0.3538.22 (Official Build) dev (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

* ensured that `Brave BETA` is being installed under `/Applications/Brave\ Browser\ Beta.app/`
* ensured that `Brave Dev` is being installed under `/Applications/Brave\ Browser\ Dev.app/`
* ensured that `Brave BETA` profiles are being saved under `~/Library/Application\ Support/BraveSoftware/Brave-Browser-Beta/`
* ensured that `Brave Dev` profiles are being used under `~/Library/Application\ Support/BraveSoftware/Brave-Browser-Dev`
* ensured that `Brave BETA` launches and uses the correct icon from `Applications`
* ensured that `Brave Dev` launches and uses the correct icon from `Applications`
* ensured that `Brave BETA` launches and uses the correct icon via `Spotlight Search`
* ensured that `Brave Dev` launches and uses the correct icon via `Spotlight Search`
* ensured that `Brave BETA` launches and uses the correct icon via a `dock` shortcut
* ensured that `Brave Dev` launches and uses the correct icon via a `dock` shortcut
* ensured that `Brave BETA` launches and uses the correct icon via `Launch Pad`
* ensured that `Brave Dev` launches and uses the correct icon via `Launch Pad`
* ensured that `Brave Dev` & `Brave BETA` are named correctly

@simonhong please let me know if the above is sufficient enough for verification.

**Comment by simonhong** [comment]
@kjozwiak Perfect!
