### ISSUE TITLE
creating shortcuts with "Open as window" selected launched empty windows

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#4694]
## Description 

When creating shortcuts using `Open as window` via `More Tools --> Create Shortcut...` on macOS, you'll get an empty window with NTP rather than the intended website.

## Steps to Reproduce

   1. Launch `0.68.9 Chromium: 75.0.3770.38` and load brave.com in a new tab
   2. Create a shortcut for brave.com using `Hamburger Menu --> More Tools --> Create Shortcut..` and ensure that `Open as window` is selected and create the shortcut
   3. You'll notice that the new window that was opened will only include the NTP and not brave.com as expected.
    4. Attempt to open the shortcut via `brave://apps` (same result, empty window)

## Actual result:

![shortcutmacOS](https://user-images.githubusercontent.com/2602313/58830996-a27e4780-8619-11e9-9bcb-183534bd03de.gif)

## Expected result:

![shortcutsWorking](https://user-images.githubusercontent.com/2602313/58831364-8b8c2500-861a-11e9-9aea-fc526f86d62c.gif)

## Reproduces how often: 

100% reproducible when going through the above STR.

## Brave version (brave://version info)

Brave | 0.68.9 Chromium: 75.0.3770.38 (Official Build) nightly(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? No, not reproducible
- Can you reproduce this issue with the beta channel? Yes (once https://github.com/brave/brave-core/pull/2558 lands)
- Can you reproduce this issue with the dev channel? Yes (once https://github.com/brave/brave-core/pull/2558 lands)
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  Yes, works with `Chrome 75.0.3770.66`

## Miscellaneous Information:

CCing @simonhong CCing @brave/legacy_qa

**Comment by simonhong** [comment]
Interesting bug. I checked with nightly dmg built locally(`yarn create_dist Release --channel=nightly --skip_signing`) and it works well. Signing can makes this difference? :/

**Comment by simonhong** [comment]
Logs when I run installed shortcut(window mode). It looks like signing issue.
```
simon-home:Chrome Apps.localized simonhong$ ./Twitter.app/Contents/MacOS/app_mode_loader
[0606/154231.205772:ERROR:app_mode_loader_mac.mm(139)] Couldn't load framework: dlopen(/Applications/Brave Browser Nightly.app/Contents/Frameworks/Brave Browser Nightly Framework.framework/Versions/75.0.68.22/Brave Browser Nightly Framework, 1): Library not loaded: @loader_path/../../Libraries/libchallenge_bypass_ristretto.dylib
  Referenced from: /Applications/Brave Browser Nightly.app/Contents/Frameworks/Brave Browser Nightly Framework.framework/Versions/75.0.68.22/Brave Browser Nightly Framework
  Reason: no suitable image found.  Did find:
	/Applications/Brave Browser Nightly.app/Contents/Frameworks/Brave Browser Nightly Framework.framework/Versions/75.0.68.22/../../Libraries/libchallenge_bypass_ristretto.dylib: code signature in (/Applications/Brave Browser Nightly.app/Contents/Frameworks/Brave Browser Nightly Framework.framework/Versions/75.0.68.22/../../Libraries/libchallenge_bypass_ristretto.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/Applications/Brave Browser Nightly.app/Contents/Frameworks/Brave Browser Nightly Framework.framework/Versions/75.0.68.22/../../Libraries/libchallenge_bypass_ristretto.dylib: code signature in (/Applications/Brave Browser Nightly.app/Contents/Frameworks/Brave Browser Nightly Framework.framework/Versions/75.0.68.22/../../Libraries/libchallenge_bypass_ristretto.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/Applications/Brave Browser Nightly.app/Contents/Frameworks/Brave Browser Nightly Framework.framework/Versions/75.0.68.22/../../Libraries/libchallenge_bypass_ristretto.dylib: stat() failed with errno=1
[0606/154231.206075:ERROR:app_mode_loader_mac.mm(166)] Loading Chrome failed, launching Chrome with command line
```

**Comment by simonhong** [comment]
@mkarolin According to the above error log, I assume this error comes from unsigned `libchallenge_bypass_ristretto.dylib`. Can you help for signing this libs?

**Comment by mkarolin** [comment]
@simonhong, yes we can add it to the list of libs that need to be signed. Would need to patch the `dylibs` list in `chrome/installer/mac/signing/signing.py` function `get_parts`.

**Comment by simonhong** [comment]
@mkarolin Great thanks!!! works perfect 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.5 x64` using the following build:

Brave | 0.68.25 Chromium: 75.0.3770.80 (Official Build) (64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Mac OS X

* ensured that https://github.com/brave/brave-browser/issues/4694#issue-451670290 worked as expected
* ensured that clicking on the shortcut icon correctly opens Brave when it's completely closed
* ensured that you can open shortcuts via `brave://apps`
* ensured that you can remove shortcuts via `brave://apps`
* ensured that creating shortcuts using `Open as Window` and without works correctly
