### ISSUE TITLE
Support importing bookmarks, history, cookies, and saved passwords for Chrome

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#47]
importing bookmark, history, cookies, saved password from Chrome

**Comment by garrettr** [comment]
Importing saved passwords from Chrome was implemented in https://github.com/brave/brave-core/pull/77 and a unit test was added in https://github.com/brave/brave-core/pull/82.

**Comment by garrettr** [comment]
Importing cookies from Chrome was implemented in brave/brave-core#93.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux
