### ISSUE TITLE
Shields should not show badge when block count is 0

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#470]
## Description 

Shields should not show badge when block count is 0

## Steps to Reproduce
   1. Open a new tab
   2. Shows disabled shields icon but shows active 0 count 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/42170368-5479b79c-7de4-11e8-9751-bf29a443bd8a.png)

## Expected result:
Should be similar to b-l. No badge count should be shown when nothing is blocked

## Reproduces how often: 

100%

## Brave version (about:brave info) 

e71fc40 

### Reproducible on current release: 

Yes

### Website problems only:  
- Does the issue gets fixed with Brave Shields disabled? 
- Does the issue reproduces on Chrome? 

### Additional Information
Follow up to #240

**Comment by GeetaSarvadnya** [comment]
Verified on Version 0.54.2 Chromium: 69.0.3497.42 (Official Build) dev (64-bit)
