### ISSUE TITLE
Invalid shortcut path and displayed name of installed pwa 

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#4701]
After creating shortcuts, pwa app (by using nightly) is installed in `~/Applications/Chrome Canary Apps.localized` dir. and displayed as `Brave Apps` like below.

<img width="1265" alt="Screen Shot 2019-06-04 at 3 42 31 PM" src="https://user-images.githubusercontent.com/6786187/58857298-d1f78780-86df-11e9-8826-96cc1010c590.png">

This should be `~/Applications/Brave Browser Nightly Apps.localized` in filesystem and displayed like `Brave Browser Nightly Apps` for Nightly.

STR:
1. Create shortcuts from app menu
2. Check its path in terminal and finder
3. It's path should be `Brave Browser XXX Apps.localized` in terminal and `Brave Browser XXX Apps` in finder in en_us locale.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.5 x64` using the following build:

Brave | 0.66.89 Chromium: 75.0.3770.87 (Official Build) beta(64-bit)
-- | --
Revision | 9dc58a2353af60ab2b48bab98a25bc43ed59085d-refs/branch-heads/3770@{#982}
OS | Mac OS X

Ensured that creating shortcuts placed them under the following directory:

```
Kamils-MBP:Brave Browser Beta Apps.localized kjozwiak$ pwd
/Users/kjozwiak/Applications/Brave Browser Beta Apps.localized
```
