### ISSUE TITLE
Cannot sync

### ISSUE THREAD

**Issue by AoiYui** [brave/brave-browser#4706]
## Description 

when attempting to sync it tells me I have an invalid sync code when I typed it correctly

## Steps to Reproduce

   1. go to preference
   2. selected sync
   3. click "I have an existing sync code"
   4. Input sync code
   5. click "setup sync"

## Actual result:

get error: 
> Brave says
> Invalid input code; please try again or create a new profile.

## Expected result:
syncs

## Reproduces how often: 

always

## Brave version (brave://version info)

I used your snap version becuase the repo is unsigned

Brave | 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Linux

## Version/Channel Information:

I'll get back to you on that I don't feel like going through the headache of trying to get an uncooperative installer to work multiple times atm.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
    - brave shield is disabled in the sync window
- Does the issue resolve itself when disabling Brave Rewards?
    - I do not have brave rewards enabled
- Is the issue reproducible on the latest version of Chrome? 
    - Chrome is not available on my OS

## Miscellaneous Information:
I have tried typing it by hand and transfering the code from my phone to my pc via pastebin

**Comment by rebron** [comment]
@AoiYui Can you try again? Are you still running into this issue?

**Comment by AoiYui** [comment]
@rebron working now I reinstalled it using the repo method since I finally figured it out. I had used the snap method previously. No offense but having the words "UBUNTU_CODENAME" in the repo path is really confusing. That may have fixed it or maybe it just blew over.
