### ISSUE TITLE
Background Sync should be disabled by default

### ISSUE THREAD

**Issue by snyderp** [brave/brave-browser#4709]
## Test plan
See https://github.com/brave/brave-core/pull/2802

## Description
Looks like [Background Sync](https://wicg.github.io/BackgroundSync/spec/) snuck back into being enabled by default.

https://deanhume.github.io/Service-Workers-BackgroundSync/ gives an example / demo of the functionality working

and it appears as enabled by default in permissions / settings (Version 0.66.79 Chromium: 75.0.3770.38 (Official Build) beta (64-bit)) 
![screen_shot_2019-06-03_at_5 01 58_pm](https://user-images.githubusercontent.com/76526/58904882-4d940d00-86bd-11e9-9ce5-993c7eedb22a.png)

**Expected behavior**
Background Sync should be disabled by default

**Possible regressions of:**
- https://github.com/brave/brave-browser/issues/515
- https://github.com/brave/brave-browser/issues/366

**Possible duplicate of:**
- https://github.com/brave/brave-browser/issues/852

**Comment by bsclifton** [comment]
cc: @rebron

**Comment by bsclifton** [comment]
@snyderp would your recommendation be to have this move to `Ask` or `Block` by default?

**Comment by snyderp** [comment]
I thinks users will have no idea at all what it does, so I suggest `Block` by default

**Comment by fmarier** [comment]
Looks pretty trivial: https://github.com/bromite/bromite/blob/master/build/patches/disable-background-sync-by-default.patch

**Comment by bsclifton** [comment]
Re-opening after https://github.com/brave/brave-core/pull/2802 was reverted with https://github.com/brave/brave-core/pull/3517

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.72.110 Chromium: 78.0.3904.70 (Official Build) dev (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from https://github.com/brave/brave-core/pull/2802
<img width="1126" alt="4709" src="https://user-images.githubusercontent.com/28145373/67720236-c7e56680-f9a9-11e9-8263-030fd06bbdcd.png">
<img width="1068" alt="both" src="https://user-images.githubusercontent.com/28145373/67720244-c9af2a00-f9a9-11e9-8d69-6e256835a71e.png">
