### ISSUE TITLE
advanced options toggle should be a global option instead of per site

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#471]
to make this `shieldsPanelTypes.CONTROLS_TOGGLED` should not set the state as a per-site setting but rather a global setting.

**Comment by bsclifton** [comment]
@cezaraugusto do you have more information about this? I'm not sure what you mean in your original post

When visiting a site with the v1 shields, the advanced settings were being saved on a per-site basis. When we re-work the shields with https://github.com/brave/brave-browser/issues/1196, it should still work like that right?

**Comment by cezaraugusto** [comment]
ya I meant that if you toggle the advanced options visibility in one site the option should be toggled across all sites but this will be fixed by the new version of shields as the option will be removed

**Comment by bsclifton** [comment]
@cezaraugusto I marked as `QA/No`; if any manual QA is required (I can't think of any?), please update original issue to include some test steps (or what to look for) and mark it as `QA/Yes`. Thanks 😄
