### ISSUE TITLE
Updating Sliders to be Clearer

### ISSUE THREAD

**Issue by EyanGoldman** [brave/brave-browser#4712]
The horizontal part of switches remain gray when on (see images below). This is confusing because on android, the horizontal part of switches are gray when off and change to the button color when on. Some users are confused when they begin to see ads on Desktop (link below). A clearer on indication switch will make when Rewards are on/off much clearer. Please coordinate UI / color change with mobile team to keep consistent

Android OS Switches (on example + off example):
![AndroidSwitches.png](https://images.zenhubusercontent.com/5cf5a25c96db72707b4b2784/fcb046d4-c796-4ab5-8d35-e68672939f85)

Brave Switches (on example):
![BraveSwitches.png](https://images.zenhubusercontent.com/5cf5a25c96db72707b4b2784/58dc0c81-aa3b-40ed-8108-dfd14e331bb6)

Reddit Link:
https://www.reddit.com/r/BATProject/comments/bwd3lb/my_2_cents/?utm_source=share&utm_medium=ios_app

**Comment by rebron** [comment]
cc: @rossmoody Can you take a look?

**Comment by rossmoody** [comment]
I can help fix this one up when we're ready but we need new visual direction from @bradleyrichter or @jenn-rhim

**Comment by NejcZdovc** [comment]
closing as this will be fixed with https://github.com/brave/brave-browser/issues/6848
