### ISSUE TITLE
Tipping banner should be auto-focused when shown so it can be dismissed by pressing ESC

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#4715]
Any time the tipping banner is invoked, it should grab focus, so the user can dismiss it by pressing ESC.

This should work in two cases:

1. When the user starts from the Rewards panel , and presses "send tip" -- that invokes the tipping banner. At that point, if the user presses ESC, the banner should be dismissed.

2. In the case of an in-page Twitter tip (which directly invokes the tipping banner directly) -- the user should also be able to press the ESC key to dismiss the tipping banner.

**Comment by mandar-brave** [comment]
@NejcZdovc moved it to P1 for the moment.

**Comment by NejcZdovc** [comment]
it's already working like this
