### ISSUE TITLE
Reconsider schedule for publisher list fetches

### ISSUE THREAD

**Issue by riastradh-brave** [brave/brave-browser#4720]
Currently we refetch the publisher list every 24h with essentially no variance in the delays:

https://github.com/brave/brave-core/blob/7e8a4cb35d3dd5395e117ac7db36fcec15d1c6c6/vendor/bat-native-ledger/src/bat/ledger/internal/ledger_impl.cc#L935-L980

```
// 24 hours in seconds
static const uint64_t _publishers_list_load_interval = 24 * 60 * 60;
```
https://github.com/brave/brave-core/blob/767deafc7fc91962ed7c4c3688b997931361cfb0/vendor/bat-native-ledger/src/bat/ledger/internal/static_values.h#L110-L111

Since the delay is not randomized, this can serve as a 24h beacon for each user's IP address to the server hosting the publisher list.  By default, we might choose the delay between downloads to be exponentially distributed with an average of 24h, so that the timing and IP address gives no information.  However:

 - We have a hard deadline for when the publisher list will be stale and we must redownload it.

   With an exponential distribution, we could make the average delay shorter so that the probability of missing the deadline is very small.

 - We want to avoid downloading it much more often than once every 24h because the publisher list is many megabytes and especially mobile users pay a lot for each megabyte.

   With an exponential distribution, we could make the average delay longer so that the probability of downloading twice is very small.

 - The exponential distribution on delays is the _only_ distribution that is memoryless so that timing gives no information.

Obviously, these goals are in conflict.  Some alternatives we could consider:

1. Truncated exponentials: min(28h, 20h + exponential(4h))
2. Uniform within an interval: uniform(20h, 28h)
3. Uniform within a day: 24h*ndays + uniform(0, 24h)

We should have some analysis of how much information this leaks.  Obviously, there will also be some leakage when the browser is not running (unless, of course, our users all decide to run Brave 24/7!).

**Comment by NejcZdovc** [comment]
note we changed this to 3 days now

**Comment by NejcZdovc** [comment]
we do not fetch pub list anymore, closing
