### ISSUE TITLE
BAT logo notification not displayed when Ad grant available

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4731]
## Description 
BAT logo did not have red notification bubble when I had an Ad grant waiting for me. 

## Steps to Reproduce

Unsure how to reproduce, this is the general outline of how I was browsing when I noticed it:

- Had Dev installed and running overnight (I updated my version yesterday I believe). Also, I hadn't accessed BAT logo at all today.
- Been opening new tabs, navigating as normal - no indication on BAT logo about any notifications.
- Saw message internally (via slack) about Ad grant, clicked on BAT logo, had notification displayed, but still no red bubble.
- Closed panel without dismissing notification, still no red bubble.
- Opened a new tab, new tab had BAT logo with red bubble.
- Going back to any other already opened tab shows BAT logo with red bubble.

## Actual result:

BAT logo did not have red notification bubble when I had an Ad grant waiting for me.

## Expected result:

BAT logo should have had a red notification bubble when I had an Ad grant waiting for me.

## Reproduces how often: 
unsure

## Brave version (brave://version info)

Brave | 0.67.72 Chromium: 75.0.3770.38 (Official Build) dev(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? unsure
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? experienced with dev, unsure if I can repro
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
@LaurenWags is this still a problem?

**Comment by LaurenWags** [comment]
I haven't experienced this in awhile. Will close for now and reopen if I run into it.
