### ISSUE TITLE
Remove First Run Time dialog, Google's logo from a new tab page

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#4732]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
superseeded by https://github.com/brave/brave-browser/issues/7841
