### ISSUE TITLE
various security issues in deps

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#4736]
github / npm audit are showing security alerts

- [x] https://github.com/brave/brave-extension/network/alerts (archived)
- [ ] https://github.com/brave/brave-ui/network/alerts
- [x] ad-block (already fixed, just needs DEPS update)
- [x] bloom-filter-cpp (already fixed, just needs DEPS update)
- [x] hashset-cpp (already fixed, just needs DEPS update)

test plan:
`npm run audit_deps` should exit cleanly

**Comment by diracdeltas** [comment]
re: sec alert in brave-ui, i tracked it down to `tools/icon-component-generator`. the problem is that the issue comes from `@balajmarius/svg2jsx` which hasn't published an update to address the security issue in its own deps

that repo needs to update to latest svgo: https://github.com/svg/svgo/blob/master/package.json#L3

we may have to fork it

**Comment by bbondy** [comment]
I just archived minutes ago, later realized you opened a PR.
