### ISSUE TITLE
Adblock restricts copy/paste option on Google Docs

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#474]
## Description 

Adblock restricts copy/paste option on Google Docs

## Steps to Reproduce
   1. Login to Google account and open Google Docs
   2. Copy some text/image into clipboard and paste in Google Docs, doesnt paste 
   3. Right click and paste, Asks to install Docs offline extension
   4. Disable shields, both keyboard and right click paste works and allows to paste images/text 

## Actual result:

Adblock restricts copy/paste option on Google Docs

## Expected result:
Should allow copy/paste option without having to disable Adblocker

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Packaged and Release build

### Website problems only:  
- Does the issue gets fixed with Brave Shields disabled? 
- Does the issue reproduces on Chrome? 

### Additional Information

cc: @lukemulks

**Comment by rebron** [comment]
@srirambv can you recheck to see if this is still an issue?

**Comment by srirambv** [comment]
This looks fine when you copy text from any page via keyboard shortcut or via context menu and paste in Google docs via `Ctrl+V`. Right click paste asks to install extension or use keyboard shortcuts.

Copy any image and paste via keyboard short cut works as well but when you copy an image from slack via context menu and paste it in Google docs, it doesn't actually paste the image but whatever is already in clipboard is pasted. Its the same behaviour on Chrome as well with respect to copy image from Slack which looks like a Slack issue for copying image from the app. In general this looks fixed on the release build so closing the issue for now.
