### ISSUE TITLE
Social media options being ignored 0.67.x and above until toggled

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#4743]
## Description 

[Recent refactoring](https://github.com/brave/brave-core/pull/2484) creates a new instance of the adblock engine and so it doesn't preserve the tags which were set on startup.

```

template<typename T>
LoadDATFileDataResult<T> LoadDATFileData(
    const base::FilePath& dat_file_path) {
  DATFileDataBuffer buffer;
  GetDATFileData(dat_file_path, &buffer);
  std::unique_ptr<T> client;  
  client = std::make_unique<T>();  <------ Problem
```

On startup the tags are not applied.
However if you go into settings and manually toggle them it worked.

## Steps to Reproduce

   1. Start Brave
   2. Load Load  https://fmarier.github.io/brave-testing/social-widgets.html

## Actual result:

Things like Facebook are not loaded

## Expected result:

Things like Facebook should be loaded

## Reproduces how often: 

Always 0.67.x and 0.68.x

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.67.110 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Ubuntu 18.04 LTS

Verified steps from the description.

Reproduced the issue on 0.67.79
![image](https://user-images.githubusercontent.com/34715963/61458398-b16f4e00-a96a-11e9-9d6f-50cb2ec91cd6.png)

Verified that is fixed:
![image](https://user-images.githubusercontent.com/34715963/61458589-2c386900-a96b-11e9-944f-00cf51c7b9ec.png)
