### ISSUE TITLE
Implement Reddit Panel For Tipping

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#4745]
## Description 

Implement Reddit panel tipping for Rewards

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.114 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/2624
- Verified the pubs name is displayed properly in BR panel and tipping banner for verified and unverified pubs in new Reddit layout
Reddit pubs

![image](https://user-images.githubusercontent.com/38657976/62345445-1355b900-b510-11e9-9563-052c3088ba6f.png)

![image](https://user-images.githubusercontent.com/38657976/62345615-a0990d80-b510-11e9-998d-f52426e9d055.png)




old.reddit.com

![image](https://user-images.githubusercontent.com/38657976/62345482-3b451c80-b510-11e9-850a-5f993ef921f2.png)

**Comment by DimitrisHol** [comment]
Is there a way to disable the icon on the frontpage?

**Comment by NejcZdovc** [comment]
@DimitrisHol there is option to disable it, but just all or nothing. Sadly you can't disable just portions of the inline tipping on Reddit
