### ISSUE TITLE
Allow Google Analytics

### ISSUE THREAD

**Issue by brhaka** [brave/brave-browser#4746]
## Description 
Maybe Brave should not block Google Analytics cookies? (Option)

## Steps to Reproduce

   1. Just opened my website (Than i can see real-time users)
   2. Check Google Analytics app

## Actual result:

I wasn't there

## Expected result:
I see myself on Google Analytics

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)
-- | --
Revision | 78e4f8db3ce38f6c26cf56eed7ae9b331fc67ada-refs/branch-heads/3729@{#1013}
OS | Windows 10 OS Build 17763.503

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

I know that Google Analytics didn't work because Brave blocks cookies, but, if there's a way to allow... Google Analytics is such a amazing tool, and a lot of peoples have their lives based on this data (like blogs), so, might be good to allow Google Analytics cookies.
Brave is a amazing browser, and i just found this issue.

[This might help.](https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage)

Best regards!

**Comment by Jacalz** [comment]
Well the reason people use a privacy browser is to NOT be tracked by tools like google analytics. If you wish to have it work for you, then you just turn off the shields. I think this issue should be closed...

**Comment by bbondy** [comment]
I think you actually want a network filter exception which you can add in about:adblock
