### ISSUE TITLE
Switching Ads off and then back on stops Ad notifications from showing unless you quit the browser

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#4748]
## Description 

Switching Ads off and then back on stops Ad notifications from showing unless you quit the browser

## Steps to Reproduce

   1. Enable Ads (unless already enabled)
   2. Disable Ads
   3. Enable Ads

## Actual result:

Ads are no longer shown unless you restart the browser

## Expected result:
Ads should continue to be shown

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

0.63 and above

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? Yes
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.116 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/2625
