### ISSUE TITLE
brave still blocking third party cookies even if allowed or shield is down

### ISSUE THREAD

**Issue by kindjacket** [brave/brave-browser#4751]
Similar to https://github.com/brave/brave-browser/issues/2095. The resolution of this is unclear.

## Description 
Some third party cookies are blocked even when the shield is set to allow all cookies.
The same occurs when I remove the shield.

## Steps to Reproduce

   1. install Grammarly chrome extension https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen?hl=en
   2. Go to a webpage with text entry, could try the slack web app
   3. Log into Grammarly in the Grammarly extension
4. write a sentence in the text input
5. click the Grammarly button - this will take you to a pop-up.

## Actual result:
the third party cookies will be blocked, reducing the capability of grammarly.

<img width="449" alt="Screen Shot 2019-06-06 at 12 46 24" src="https://user-images.githubusercontent.com/7778402/59062601-152a3580-885b-11e9-865f-87b486f418a3.png">
<img width="651" alt="Screen Shot 2019-06-06 at 12 22 27" src="https://user-images.githubusercontent.com/7778402/59062620-1ce9da00-885b-11e9-8c55-4d6b9f05df2b.png">
<img width="361" alt="Screen Shot 2019-06-06 at 12 46 35" src="https://user-images.githubusercontent.com/7778402/59062625-207d6100-885b-11e9-9e61-fab0a1cfad97.png">
<img width="444" alt="Screen Shot 2019-06-06 at 13 07 29" src="https://user-images.githubusercontent.com/7778402/59063026-0d1ec580-885c-11e9-998a-db5968233de5.png">

## Expected result:
No blocking of cookies

## Reproduces how often: 
Every time

## Brave version (brave://version info)
0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment]
We need a consistent experience with Shields cross site trackers settings and Chromium's individual cookie control UI.
cc: @tomlowenthal

**Comment by tomlowenthal** [comment]
I think this is the same work as in #4285 — fundamentally, they're both about unifying the experience and state between Shields and the native Chromium site settings and managers.
