### ISSUE TITLE
Checkout flow breaks on Merch Direct powered sites

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#4752]
The Merch Direct API created modal checkout dialog is busted, unusably, when shields are up.

Specifically, the "submit payment" button doesn't appear and the dialog is collapsed.

When shields are up: 
![Screen Shot 2019-06-06 at 1 38 08 PM](https://user-images.githubusercontent.com/76526/59064933-5a9d3180-8860-11e9-9567-eff4db472881.png)

Without shields:
![Screen Shot 2019-06-06 at 1 38 52 PM](https://user-images.githubusercontent.com/76526/59064965-76a0d300-8860-11e9-9337-a07438185713.png)

To recreate:

1. Go to https://www.thisischon.com/products/65682-chon-lp
2. Click "Add to" button
3. Select "United States" and "standard" shipping (shouldn't matter specific values)
4. click "checkout"
5. Observed the next page is goofed

**Comment by ryanbr** [comment]
I'll need to debug it more; but blocking one of these url's will cause issues. 

```
https://api.ipinfodb.com/
https://m.stripe.network/
```

**Comment by ryanbr** [comment]
Seems to affect many sites. (from a quick google) it'll be a generic whitelist.

```
https://www.jmtstore.com/
https://www.tokenhiphop.com/store
```

**Comment by ryanbr** [comment]
Okay, the easy fix here will be just allow all cookies rather than 3rd-party. which will fix this.

**Comment by ryanbr** [comment]
Safe to close?,  domain `thisischon.com` is dead. The other sample domains `https://www.jmtstore.com/` & `https://www.tokenhiphop.com/store` isn't using this template

**Comment by bsclifton** [comment]
Let's close it out 😄 @pes10k - please re-open if there is still an issue
