### ISSUE TITLE
Nightly doesn't have channel string in `chrome://settings/help`

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#4753]
<img width="826" alt="Screen Shot 2019-06-07 at 09 41 47" src="https://user-images.githubusercontent.com/6786187/59076221-e3bf7180-890f-11e9-9b09-d1ff63b13228.png">

`/Applications/Brave\ Browser\ Nightly.app/Contents/Info.plist` doesn’t have `KSChannelID` key.

It is set by `brave_app_list` target in `brave/BUILD.gn` and only channel key is omitted. Others are set properly.
This could cause many side-effect because of wrong channel.
```
brave_tweak_info_plist("brave_app_plist") {
    info_plist = "$root_gen_dir/chrome/chrome_app_plist_tweaked.plist"

    args = [
      "--brave_channel=" + brave_channel,
      "--brave_product_dir_name=" + brave_product_dir_name,
      "--brave_feed_url=" + brave_feed_url,
      "--brave_dsa_file=" + brave_dsa_file,
    ]

    deps = [
      "//chrome:chrome_app_plist",
    ]
  }
```

Only reproduced in nightly channel for now.
I think the reason why this only happens in nightly is other channels are not yet release after we bumped cr version.

**Comment by simonhong** [comment]
`//build/mac/tweak_info_plist.py` has code that removes `KSChannelID` key.
However, `chrome_info_plist` target is in deps list of `brave_info_plist` target.
So, that removing code can't be run after `brave_info_plist` target add `KSChannelID`.

**Comment by bsclifton** [comment]
@rebron has confirmed on Nightly:
![image](https://user-images.githubusercontent.com/4733304/59143006-67fb0e80-897b-11e9-926f-72c0efb7392f.png)

Leaving issue as 0.66.x (even though it's merged back to 0.65.x) so that it can be verified via manual QA on BETA channel. I don't believe channel will show on release (only beta/dev/nightly)

**Comment by btlechowski** [comment]
Worth checking on all platforms.

Verification passed on

Brave | 0.66.87 Chromium: 75.0.3770.80 (Official Build) beta (64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Windows 7 Service Pack 1 (Build 7601.24465)

![image](https://user-images.githubusercontent.com/34715963/59270937-0248a400-8c53-11e9-8c87-240049cf9de5.png)

**Comment by bsclifton** [comment]
Removed verification labels - since we'll have a 0.65.x hotfix (Chromium version) we can re-verify the fixes with an RC 😄

**Comment by kjozwiak** [comment]
@simonhong re: the release channel, is the following expected?

<img width="597" alt="Screen Shot 2019-06-14 at 10 18 24 AM" src="https://user-images.githubusercontent.com/2602313/59515730-c8171680-8e8d-11e9-9a35-bf70799dc195.png">

Should it be `(Official Build) release (64-bit)` or is what we're seeing in the release channel the correct format? I'm assuming it's correct but would appreciate the double check just in case 👍

**Comment by simonhong** [comment]
@kjozwiak Yup, It's expected - empty channel name for stable channel.

**Comment by kjozwiak** [comment]
Perfect! Thanks @simonhong 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.5 x64` using the following build:

Brave | 0.65.120 Chromium: 75.0.3770.90 (Official Build) (64-bit)
-- | --
Revision | a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}
OS | Mac OS X

<img width="1060" alt="Screen Shot 2019-06-14 at 10 25 47 AM" src="https://user-images.githubusercontent.com/2602313/59516192-cac63b80-8e8e-11e9-94e0-f5566756e03c.png">

**Comment by btlechowski** [comment]
Moving back to 0.66.x as it is beta/dev/nighly only issue.
