### ISSUE TITLE
Reddit pubisher not displaying when account set to hide from robots

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#4754]
## Description 

When visiting a Reddit account that has the option to hide from robots turned on, that publisher doesn't show in publisher panel

## Steps to Reproduce

   1. Open Brave with Rewards enabled
   2. Visit a reddit user account page that has hide from robots enabled (use https://www.reddit.com/u/jsadler-brave)
   3. Open publisher panel

## Actual result:

Only wallet summary is displayed

## Expected result:
Publisher info should be displayed

## Reproduces how often: 

easily with particular publisher

## Brave version (brave://version info)

0.68 (nightly)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/2635
- Logged #5448 
 
![image](https://user-images.githubusercontent.com/38657976/62131959-d1532a00-b2f9-11e9-8b64-fd184fb80726.png)
![image](https://user-images.githubusercontent.com/38657976/62131992-dfa14600-b2f9-11e9-97d0-78cddce3f692.png)
![image](https://user-images.githubusercontent.com/38657976/62132027-ed56cb80-b2f9-11e9-92c7-ff58641dc344.png)
