### ISSUE TITLE
Integration with Microsoft to allow contribution to GitHub

### ISSUE THREAD

**Issue by alexanderjwoods** [brave/brave-browser#4755]
## Description 
With the announcement (https://www.businessinsider.com/github-sponsors-open-source-financial-support-2019-5) that Microsoft is allowing sponsors for open source projects, this seems like a very good chance to partner with a major company and get Brave to the masses.

## Expected result:
Brave is listed as a payment option for sponsoring open source projects.

**Comment by bsclifton** [comment]
Relayed to our bizdev team- thanks! 😄
