### ISSUE TITLE
multiple Insufficient Funds due to pending tips notification - follow up to 3741

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4757]
## Description 
Found while testing #3741 

After running thru the test plan in https://github.com/brave/brave-core/pull/2512, I navigated to an unverified site and clicked 'Refresh Status'. I got a second notification for "Insufficient Funds - You have pending tips due to insufficient funds". 

Per https://github.com/brave/brave-browser/issues/3741#issuecomment-492336298 I was only expecting this once (one bullet pt in comment says "if tips fail due to lack of funds, notify first time ONLY when users retry"), however I get it each time I click on 'Refresh Status' when there is a pending contribution for a verified site. That's going to get really annoying, really quickly for users.

Just to re-iterate, this only occurs when you have a verified publisher in your pending list.

## Steps to Reproduce

1. enable rewards on staging
2. close browser
3. go to publisher_list and change second value for 3zsistemi.si to false from ["3zsistemi.si",true,false.... to ["3zsistemi.si",false,false....
4. start the browser (be sure you're on staging again)
5. add tip to unverified site
6. add tip for 10, 10, 5 and 10 to 3zsistemi.si
7. add another tip to unverified site
8. go to 3zsistemi.si, open panel and click check again
9. go to settings page and observe the page after couple of minutes 3 pending contributions (10, 10, 5) should be processed and you should have two notifications (new publisher verified and out of funds)
10. open pending contributions dialog and make sure that you see 3 tips (2 to your unverified site and one to newly verified 3zsistemi for 10)
11. Go to an unverified site, open panel, and click Refresh Status.

## Actual result:
Get another notification for 'Insufficient Funds - You have pending tips due to insufficient funds' message as you did in step 9 already.
![Screen Shot 2019-06-07 at 3 15 40 PM](https://user-images.githubusercontent.com/28145373/59129078-cbfce300-8939-11e9-968a-250fd08c430c.png)

## Expected result:
Not to get this notification a second time per comment in #3741.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.68.26 Chromium: 75.0.3770.80 (Official Build) (64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the dev channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @brave/legacy_qa @NejcZdovc @mandar-brave @alexwykoff

**Comment by mandar-brave** [comment]
@LaurenWags at the moment this is spec'd as anticipated; i think the issue that there "may" be too many notifications is fair. Will look at the use case again.
@davidtemkin for discussion.

**Comment by GeetaSarvadnya** [comment]
Unable to Reproduce the issue on `Windows 10 x64 - 0.67.108` - Getting single insufficient funds notification

**Comment by NejcZdovc** [comment]
closing as stale
