### ISSUE TITLE
'Learn More' link in brave://rewards points to old brave.com faq URL

### ISSUE THREAD

**Issue by bkero** [brave/brave-browser#4758]
## Description 

There is an old FAQ URL referenced on the aforementioned page. It currently points to brave.com/faq-rewards/#unclaimed-funds. @jonathansampson suggests that this would be better pointed to brave.com/faq/#unclaimed-funds instead.

## Steps to Reproduce

   1. Open brave browser.
   2. Load up brave://rewards
   3. At the text section ```Your browser will keep trying to contribute until they verify, or until 90 days have passed. Learn more.``` click the ```Learn more``` link. 

## Actual result:

A 404 page is shown since this page does not exist.

## Expected result:
The FAQ page is shown with browser scrolling to the unclaimed funds section

## Reproduces how often: 

Always

## Brave version (brave://version info)

At least 0.66.79

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by bkero** [comment]
I've added a redirect as a temporary fixfix, but this should still be fixed in the browser.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.106 Chromium: 76.0.3809.62 (Official Build) dev (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/2642
![image](https://user-images.githubusercontent.com/38657976/61587385-1616ec80-aba7-11e9-9ac8-8bb9e122377e.png)
