### ISSUE TITLE
Notification badge is retained even after closing the notification in BR Panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4759]
## Description 

Notification badge is retained even after closing the notification in BR Panel

## Steps to Reproduce

   1. Keep using the profile 
   2. Wait for the notifications to show up
   3. Open BR panel and dismiss notification, badge is still retained even though actual notification is closed

## Actual result:

<img width="400" alt="Screenshot 2019-06-07 at 5 25 55 PM" src="https://user-images.githubusercontent.com/17010094/59135006-5dc11c00-894b-11e9-830e-d699b6e44365.png">

## Expected result:
Notification badge should be removed when actual notification is closed

## Reproduces how often: 

You have to be lucky to see this or reproduce this

## Brave version (brave://version info)

Brave | 0.67.73 Chromium: 75.0.3770.38 (Official Build) dev(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Mac OS X / Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes. Seen it on Linux
- Can you reproduce this issue with the dev channel? Yes, seen it on both macOS and Linux
- Can you reproduce this issue with the nightly channel? Yes but not used it on both OS

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N.A
- Is the issue reproducible on the latest version of Chrome?  N/A

## Miscellaneous Information:

#4731 could be related. But I have seen the issue on Linux and macOS without having to put the device to sleep.

**Comment by NejcZdovc** [comment]
@srirambv could you please provide more info.

Tried this steps and it's working correctly:
- clean profile
- enable rewards through settings page
- open panel
- close grant notification
- notification is dismissed

**Comment by srirambv** [comment]
@NejcZdovc mine wasn't a clean profile. It was an existing profile that I have been using for quite sometime. I've been using the profile on Linux since April. This is what is shown on brave://local-state/ for 
Linux
![image](https://user-images.githubusercontent.com/17010094/59197910-78201300-8b60-11e9-84b2-75d8e30c7162.png)

maOS
![image](https://user-images.githubusercontent.com/17010094/59197871-68083380-8b60-11e9-80ab-7979d943bb1e.png)

I doubt it happens on a clean install you will have to have a decent browsing profile updating from multiple versions I guess. I do think this is a bug because its happening on both macOS and Linux for existing profiles that update over a period of time.

**Comment by srirambv** [comment]
Btw I forgot to mention it in the steps, the notifications that I received were for Ads grant and backup wallet notification on both profiles.

**Comment by NejcZdovc** [comment]
@srirambv if you reopen the panel are notifications back so you could dismiss it again?

**Comment by srirambv** [comment]
@NejcZdovc nope. Close and reopen browser fixed it. Even switching between tabs had not fixed that as far as I can remember

**Comment by NejcZdovc** [comment]
@srirambv when you say fixed it, are they gone now?

**Comment by srirambv** [comment]
Yes there is no notification badge after restart. But while the browser was active I did have the notification badge remain even after manually closing the notification in the panel

**Comment by bsclifton** [comment]
I have this problem- it's always stuck at 29 for me ☹️ Not sure if there's a way to clear. Shoot me a message if you'd like me to share profile details 😄

**Comment by srirambv** [comment]
@NejcZdovc i just saw this on Linux again. Switching tab fixes the notification badge. So that particular tab doesn't remove the badge once notifications are closed

**Comment by srirambv** [comment]
@NejcZdovc  here's a recording of the issue to make it more clear. 
https://youtu.be/JPGSdyia4fQ

**Comment by NejcZdovc** [comment]
@srirambv is this still a problem?

**Comment by Miyayes** [comment]
Closing as stale. Can file anew if we still observe this. There are some other issues already filed regarding notification badges too.
