### ISSUE TITLE
App fails to launch on when upgrading using setup installer on Windows

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#476]
## Description 
App fails to launch on upgrade

## Steps to Reproduce
   1. Install older build using full setup file and ensure browser launches
   2. Install updated build from the full setup file (not the stub installer)
   3. Browser window doesn't relaunch after update

## Actual result:

App fails to launch on upgrade

## Expected result:
Should launch

## Reproduces how often: 

100%

### Website problems only:  
- Does the issue gets fixed with Brave Shields disabled? 
- Does the issue reproduces on Chrome? 

### Additional Information
Discussed the issue on slack initially with @RyanJarv  cc @simonhong  
Issue on Windows

**Comment by srirambv** [comment]
Packaged build doesn't launch upon running setup if browser-laptop window is already opened

**Comment by bbondy** [comment]
still an issue?

**Comment by emerick** [comment]
@srirambv In step 2, are you updating manually (i.e., double-clicking an install file) or are you initiating the update in some other way? I wasn't able to repro on Windows, but I'm not sure that I'm following your steps correctly. In fact, no matter which older version I download the latest version installs.

**Comment by srirambv** [comment]
@emerick yes when i run the setup manually to upgrade it doesn't launch. I can test this when the next build comes out.

**Comment by emerick** [comment]
@sri Yep, there have been a lot of changes to the installer so I think that makes sense.

**Comment by srirambv** [comment]
@emerick I don't think this issue is testable unless we get the setup installer. The stub installer is going to point to the recent build so running that would launch it correctly. Logged #687 which might supersede this issue.

**Comment by srirambv** [comment]
I tested manually with `0.53.0` and `0.53.1` setup installer. Still doesn't launch. Also found that the setup which i got installed release build(Orange lino) instead of dev build(blue lion). Here's the recording of it
https://youtu.be/m73miOuEe80


cc: @bbondy @RyanJarv @mbacchi

**Comment by srirambv** [comment]
Closing in favour of #688

**Comment by btlechowski** [comment]
Deleting QA/Needed because this issue was closed in favor of #688

**Comment by srirambv** [comment]
This still needs to be tested once the offline installers are available. We need to verify this once #688 is implemented. So marking it as QA/Needed
