### ISSUE TITLE
Nightly on Win10 doesn't have `Same as Windows` option in `Brave colors` setting

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#4760]
This is regression of recent disabling of field trial.

Dark mode on Windows is disabled by default in C75 and we enabled it by field trial implicitly.
See `kDarkMode` in `ui_base_features.cc` is disabled by default in C75.
After disabling field trial, it is disabled again. So, `Same as Windows` option is hidden on Nightly.
`Same as Windows` option is only visible when `kDarkMode` feature is enabled.

Upstream enabled dark mode by default in C76. (https://chromium-review.googlesource.com/c/chromium/src/+/1597930)

Should we leave it until we rebase on C76 or cherry-pick in advance?

cc: @bbondy @bsclifton @mkarolin @rebron

**Comment by simonhong** [comment]
This will be resolved when we finish C76 rebasing (https://github.com/brave/brave-core/pull/2722/commits/6ac41756da09e097c0e26cbf07634da0410c74e9)

**Comment by rebron** [comment]
Closing. Version 0.69.54 Chromium: 76.0.3809.62 (Official Build) nightly (64-bit)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.121 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the description mentioned in the issue
