### ISSUE TITLE
google translator voice input not working 

### ISSUE THREAD

**Issue by oshanz** [brave/brave-browser#4763]
## Description 
cannot turn on voice input in google translate. 

## Steps to Reproduce
   1. https://translate.google.com
   2. select a input language
   3. click the mic button

## Actual result:
mic button will get turned off in a second later

## Expected result:
mic button stays enable, and start recording.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
The issue is Reproducible in Windows 10 x65 - `0.65.118`


Brave | 0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Windows 10 OS Version 1803 (Build 17134.523)

**Comment by lakshanwd** [comment]
Yup same here
I'm using `Version 0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)`

**Comment by bsclifton** [comment]
Possibly related:
- Brave Browser Desktop unable to use microphone with Duolingo #3725
- Google search-by-voice displays "no internet connection" #2690

**Comment by rebron** [comment]
cc: @tomlowenthal for api-key

**Comment by tomlowenthal** [comment]
This Google Speech API topic spans multiple issues on this repo. I'm working on it in brave/internal#608. When I resolve things there, I'll come back here with the next technical steps.

**Comment by bsclifton** [comment]
Closing as duplicate of https://github.com/brave/brave-browser/issues/3725

**Comment by ahmet-kok** [comment]
Could you find the solution?

**Comment by aploftus** [comment]
Any movement on this issue?
