### ISSUE TITLE
Temporarily allow javascript on a website

### ISSUE THREAD

**Issue by ZeerakW** [brave/brave-browser#4765]
## Description 

Are there plans for/would it be possible to have temporary (say until the tab/window/browser closes) unblocks of javascript? Currently the only options are permanently unblocking or leaving a website permanently blocked.

## Steps to Reproduce

   1. Turn on Javascript blocking
   2. Go to website which uses JS
   3. Open the menu of how to deal with it: options given are permanently unblock or leave 
blocked.
## Brave version (brave://version info)

Version 0.65.118

**Comment by srirambv** [comment]
This is available via shields.
1. Turn on JS blocking in shields setting
2. Open any site and see the scripts blocked
3. Open shields (Lion icon)
4. Click on Scripts blocked to see the domains blocked
5. Select which ever script you want run and click Allow and click `Apply once`. Page reloads and runs the scripts which you have allowed. This is only applicable until the tab/window is closed
