### ISSUE TITLE
Block history.pushState() more than 100 times per 30 seconds

### ISSUE THREAD

**Issue by irlcatgirl** [brave/brave-browser#4766]
## Description 
A malicious website can abuse `history.pushState()` to freeze Brave. Apple Safari mitigates this with a sensible limit. We should follow.

## Steps to Reproduce
```
<!-- Code extracted from CrashSafari.com -->
<!DOCTYPE html>
<html>
    <body>
        <h1>What were you expecting?</h1>
                <script>
                    var total = "";
                    for( var i = 0; i < 100000; i++ ) {
                        total = total + i.toString();
                        history.pushState(0,0, total );
                    }
                </script>
            </body>
        </html>
```

## Actual result:
Brave gets very slow and freezes up

## Expected result:
Brave to copy Apple Safari's mitigation.
<img width="1084" alt="Screen Shot 2019-06-08 at 3 43 02 PM" src="https://user-images.githubusercontent.com/8227641/59151627-63c70380-8a04-11e9-8230-43f693fc086b.png">

## Reproduces how often: 
Always

## Brave version (brave://version info)
N/A

## Version/Channel Information:
N/A

## Other Additional Information:
N/A

## Miscellaneous Information:
N/A

**Comment by RyuuOujiXS** [comment]
Please add an option to block the history.pushState() function, and any others that manipulate search history, completely. I have yet to see this function used for anything that benefits the user. I've only seen it used in situations where developers want to force the user to do something they don't want to.
