### ISSUE TITLE
removeddit.com does not connect to reddit properly with Shields Up

### ISSUE THREAD

**Issue by devingoodman** [brave/brave-browser#4767]
## Description 
When logging onto the site https://www.removeddit.com, the site does not load properly. The site gives the user an error message, "Could not connect to Reddit."

This occurs on both the landing page and also any other post or comment link.

## Steps to Reproduce

   1. Open up Brave Browser
   2. Ensure Shields are up
   3. Go to https://www.removeddit.com/

## Actual result:
Please see attached screenshot
<img width="1312" alt="Screen Shot 2019-06-08 at 3 14 18 PM" src="https://user-images.githubusercontent.com/7727156/59152779-3c6e3780-8a00-11e9-9e2e-b2f1b8fb4b15.png">

## Expected result:
The proper landing page of https://www.removeddit.com, which points to https://www.reddit.com/r/all

## Reproduces how often: 
Easily reproduced. Happens every time, without exception.

## Brave version (brave://version info)

Brave | 0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
N/A
- Can you reproduce this issue with the dev channel?
N/A
- Can you reproduce this issue with the nightly channel?
N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
Yes
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by WorldLanguages** [comment]
https://www.reddit.com/api/v1/access_token is considered a 3rd party tracker

**Comment by rebron** [comment]
Need to retest once the adblock rust lands on Nightly.

**Comment by bsclifton** [comment]
Closing as this website seems to be down now
