### ISSUE TITLE
Settings on Private Windows with Tor.

### ISSUE THREAD

**Issue by Victorio115** [brave/brave-browser#4768]
## Description 

I remember that in previous versions of Brave, I could manage my search engines, enable or disable bulit-in extensions of Brave, and other settings, for Private Windows with Tor.  
    
Recelty, in [one of updates of brave browser](https://twitter.com/brave/status/1136705873978376192), a new design for settings page has been released.  
  
It was looking good, until to the moment that I decide to open a Private Window with Tor, with the current version.  

## Steps to Reproduce

   1. Open Brave.
   2. Open a New Private Window with Tor.
   3. Writte `brave://settings` on Address Bar.

## Actual result:

![image](https://user-images.githubusercontent.com/50971728/59156261-e8d60b00-8a4c-11e9-9df5-33e071041f8e.png)

## Expected result:
Something like this.  
  
![image](https://user-images.githubusercontent.com/50971728/59156423-e1fcc780-8a4f-11e9-9d91-9d1f3c0da5d1.png)
  
But in a Private Window with Tor, and not with all settings sections that are available on a normal window.  

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

Brave | 0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Mac OS X
JavaScript | V8 7.5.288.22
Flash | 32.0.0.192 /Library/Internet Plug-Ins/PepperFlashPlayer/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=NewExtensionUpdaterService,DesktopPWAWindowing --disable-features=AutofillServerCommunication,DefaultEnableOopRasterization,AudioServiceOutOfProcess,AutofillSaveCardSignInAfterLocalSave,NetworkService,UnifiedConsent,LookalikeUrlNavigationSuggestionsUI,TranslateUI --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/VictorioAcosta/Library/Application Support/BraveSoftware/Brave-Browser/Default
Variations | 5040e8a-5040e8ac134752e-f685ead32c707b42-dcf7018a411b6d4e-3f4a17dfd01ab0d3-60c33fc08927cedd-3f4a17df16e0dd70-3f4a17df414bf2d2-3f4a17dfba11b117-5b05287a551157b-3f4a17dff88a4127-2874767e4b8c3f4-3f4a17dfb7e2524c-c92d551c411c711e-3f4a17df6c18ba9d-3f4a17df8f029c91-3f4a17df8982496f-3f4a17df61832c80-3f4a17dfcc20827f-77c422c591560a-29acad49853922b-3f4a17df776de70c-e0278d3ded9149a9-3f4a17df34d450b1-3f4a17dfc70841c8-a256700714bdbe54-e8c7a65bd8343fa3-3f4a17dfb517d646-3f4a17df8ee5ed19-c3125ea274658432-fa79b94c4f9b5d89-3f4a17dfc36cdb78-3f4a17df652e14d1-f4950e995274eb09-3f4a17dfd6d4ee9a-3f4a17df2729b628-3f4a17df44827ee5-3f4a17df332a4d9b-8e8e4a2b6a116980-3f4a17df3f79ac13-3d47f4f48f1e27f-3f4a17df6cb3969e-3f4a17df40de7b13-1aa41b589b4c4257-3f4a17df43f62d3b-3f4a17df9e5c75f1-30e1b12b2594bdf4-3f4a17df6fa07eb4-7282ca762981bcb4-3f4a17df5139837c-3f4a17df4934552d-3f4a17df7f8176d9-3f4a17df6c66bd8d-b204717823a898eb-fc93cf742b08b14-3f4a17df7a5ba892-3f4a17dfd1cd70a5-3f4a17df4ea303a6-3f4a17dfac8d4708-5460eccbeb221b68-eb221b68b19465ab-b19465ab6e6e0c7e-3f17a7d895876445-2b71ffe42b33233e-881ca6c94da5ae82-3f4a17df56302f8c-2f882e70fd56acdf-3f4a17dfed846e24-3f4a17dfb2612322-8a9180b23dba712-a2d707c6ad6d27cc-85d38e8dcec9a952-9a6c5085f56e0452-3f4a17df8576baf1-3f4a17df2e7f6029-88947c67d00fcbde-3f4a17dfd840bbac-3f4a17df930e30f5-3f4a17df732f0134-3f4a17df9a2f4e5b-9ded16b91354da85-522c33b8494d8760-3f4a17dff9e5da91-508355f5b1ceb06f-6b7b34d7a5ae46f-7a5ae46fb0ea13bc-3f4a17df47a2af3f-3f4a17df94e68624-803f8fc4cc73f8a1-3f4a17dfb4e8892d-a2d707c67e91b7bd-c6da37cb6204e469-3f4a17df41ddf744-c78ce173

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? I didn't use Brave on Beta Channel, so I don't know if that occurs on it.
- Can you reproduce this issue with the dev channel? I didn't use Brave on Dev Channel, so I don't know if that occurs on it.
- Can you reproduce this issue with the nightly channel? I didn't use Brave on Nightly Channel, so I don't know if that occurs on.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Brave Shields aren't enabled on Settings Page.
- Does the issue resolve itself when disabling Brave Rewards? Brave Rewards aren't available in Private Windows with Tor.
- Is the issue reproducible on the latest version of Chrome? Yes, I think.

**Comment by GeetaSarvadnya** [comment]
This is expected behavior in Private windows withTor tabs. Please find the issue for your reference.

https://github.com/brave/brave-browser/issues/2306

Thanks!
