### ISSUE TITLE
Show BAT by default on main Wallet UI

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#4773]
Currently only Ethereum is listed, we should pre-add BAT as well.

<img width="892" alt="Screen Shot 2019-06-10 at 10 26 50 AM" src="https://user-images.githubusercontent.com/831718/59202387-59267e80-8b6a-11e9-9015-2b8bc08911ba.png">

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/ethereum-remote-client/pull/3
![image](https://user-images.githubusercontent.com/38657976/65514707-73a71c80-defb-11e9-9094-f500be6bd37c.png)
