### ISSUE TITLE
User wallet: Contributions

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#4775]
Once connected to the Uphold wallet (Verified or Unverified), if there is a balance in the BAT Card for contributions, the transactions will go through.

User wallet -> a/c will now need authorized user wallet token to sign transaction from user wallet to settlement wallet.

User wallet -> tips will now need authorized user wallet token to sign transaction from user wallet to publisher wallet.

User wallet -> tips will also have separate protocol change tracked in another issue.

**Comment by mandar-brave** [comment]
@evq FYI for tracking changes.
@alexwykoff

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.121 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2696
* Verified able to contribute when the user had never connected an uphold account, had connected an uphold account but it wasn't KYC'd, and when a KYC'd uphold account was connected. Additional details on those scenarios can be found here: https://github.com/brave/brave-browser/issues/4774#issuecomment-527707552
