### ISSUE TITLE
User wallet: Protocol changes (Tips)

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#4776]
Cross referencing: https://github.com/brave/brave-browser/issues/4775

User wallets -> Tips has a protocol change per TOS;
a) 95% of the payment will go the publishers
b) 5% of the payment will go to the settlement wallet as the fee

@evq for protocol specific changes.
@alexwykoff

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.121 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2696
* Verified this is what shows in uphold when tipping from Verified/KYC'd account (95/5% split):
![Screen Shot 2019-09-03 at 5 16 12 PM](https://user-images.githubusercontent.com/28145373/64209470-9b601300-ce6e-11e9-85bd-131fbfcd07fe.png)
* Verified still able to tip if you never connect to uphold at all and tip from anon Brave wallet.
* Verified able to tip if you had BAT in your anon wallet and then connected a non-KYC'd Uphold account (note, this could be funded with crypto as allowable by local laws). BAT in anon wallet is used prior to any BAT in the Brave Browser card.
