### ISSUE TITLE
Implement Android Ads on the current browser-android-tabs

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#4777]
Implement Android Ads

**Comment by bbondy** [comment]
I think this is done, so closing.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.58 x64 beta build
- Verified Ads is enabled when rewards is enabled via onboarding
![image](https://user-images.githubusercontent.com/17010094/73103310-c7ce0780-3ec1-11ea-9162-9f5dc3f4471a.png)
- Verified able to set ads per hour setting 
![image](https://user-images.githubusercontent.com/17010094/73103250-abca6600-3ec1-11ea-873c-0e7ddf4788d5.png)
- Verified sample ad notification is shown when rewards is enabled and wallet is created
![image](https://user-images.githubusercontent.com/17010094/73103289-bbe24580-3ec1-11ea-8f46-b2e69bdd9263.png)
- Verified an actual ad is shown when catalog is matched
![image](https://user-images.githubusercontent.com/17010094/73103319-d0bed900-3ec1-11ea-8b53-2357321af548.png)
-------
Verification passed on Samsung Tab A with Android 9 running 1.5.58 x64 beta build
- Verified Ads is enabled when rewards is enabled via onboarding
![image](https://user-images.githubusercontent.com/17010094/73103945-3a8bb280-3ec3-11ea-82de-980ea2ea8c69.png)
- Verified able to set ads per hour setting 
![image](https://user-images.githubusercontent.com/17010094/73103956-40819380-3ec3-11ea-9ba7-1def51da0037.png)
- Verified sample ad notification is shown when rewards is enabled and wallet is created
- Verified an actual ad is shown when catalog is matched
![image](https://user-images.githubusercontent.com/17010094/73103966-45dede00-3ec3-11ea-9edb-98e3a2eeedba.png)

-------
