### ISSUE TITLE
User wallet: Add fund flow

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#4779]
Old add funds flow needs to go.
Only users with Uphold wallets can add funds.
Add funds is handed off to Uphold for managing transfers in initial release

@NejcZdovc 
@jenn-rhim for UI/UX changes.
cc @alexwykoff

**Comment by mandar-brave** [comment]
For Add-funds, the link should take user to Uphold site with the right URL to allow user to add funds on Uphold site
For With-funds, the link should take user to Uphold account

![image](https://user-images.githubusercontent.com/35932307/59899889-44888880-93ab-11e9-9b06-33ad1dc05bdf.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.121 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2696
* Verified if you've never connected an uphold account, Add Funds and Withdraw Funds take you to onboarding modal
![Screen Shot 2019-09-03 at 5 40 27 PM](https://user-images.githubusercontent.com/28145373/64210691-f0e9ef00-ce71-11e9-85cf-04211a28ae76.png)

* Verified if you connect an account that is not KYC'd, and you click on Add Funds, you are taken to your Add Funds page for your Brave Browser Card (note - without KYC not all options will be available to the user)
![Screen Shot 2019-09-03 at 5 42 11 PM](https://user-images.githubusercontent.com/28145373/64210809-39a1a800-ce72-11e9-96f7-c80706946038.png)

* Verified if you connect an account that is not KYC'd and you click on Withdraw Funds, you are taken to a page to complete KYC
![Screen Shot 2019-09-03 at 5 42 28 PM](https://user-images.githubusercontent.com/28145373/64210834-4de5a500-ce72-11e9-97a2-15c985061d8c.png)

* Verified if you connect a KYC'd Uphold account and click on Add Funds, you are taken to your Add Funds page for your Brave Browser Card
![Screen Shot 2019-09-03 at 5 44 21 PM](https://user-images.githubusercontent.com/28145373/64210928-97ce8b00-ce72-11e9-94e8-6aa0fd98eebb.png)

* Verified if you connect a KYC'd Uphold account and click on Withdraw Funds, you are taken to the 'Use Funds' page for your Brave Browser card:
![Screen Shot 2019-09-03 at 5 44 35 PM](https://user-images.githubusercontent.com/28145373/64210966-b03ea580-ce72-11e9-827b-d750632c2a26.png)
