### ISSUE TITLE
Pinned tab mutes when clicked on tab 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#478]
## Description 
Pinned tab gets muted when clicked on tab 

## Steps to Reproduce
   1. Login to Slack in a tab and pin it
   2. Wait for a notification to arrive so that the tab shows the speaker icon
   3. Icon stays long enough with fade out animation during which time if the tab is clicked it mutes that tab

## Actual result:
Pinned tab gets muted when clicked on tab 

## Expected result:
Should not mute tab when a pinned tab is selected

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Release and packaged build

### Reproducible on current release:

N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
Not sure when - but we did fix this 😄
