### ISSUE TITLE
Show bookmarks bar on New Tab Page only

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#4782]
## Description 
Some users only want to see the bookmarks bar on the New Tab page and nowhere else. We need to create a preference to support this behavior. Off by default.

This is a follow up to this issue: https://github.com/brave/brave-browser/issues/1306#issuecomment-500262489 that supports the View "Always Show Bookmarks Bar" setting on every window including the New Tab page.

## Design
[placeholder]

**Comment by simonhong** [comment]
@rebron  I set milestone as `0.68.x nightly` because https://github.com/brave/brave-browser/issues/1306 is merged into `0.68.x`. I assume that many users will say about this if don't have a fix this this.

**Comment by rebron** [comment]
cc: @petemill may have suggestions on how this should look (where setting should go).

**Comment by rebron** [comment]
Can we check that with this fix, on Windows 10, bookmarks bar shows up in full screen mode?
cc: @Brave-Matt

**Comment by Brave-Matt** [comment]
Bookmarks bar spacing issue in Fullscreen mode looks like this:
![image](https://user-images.githubusercontent.com/3299098/63288176-ec69e780-c270-11e9-9776-4d40c1da0cd6.png)

As opposed to:
![image](https://user-images.githubusercontent.com/3299098/63288222-05729880-c271-11e9-8dfb-a3006b783dfb.png)

Occurs on Release (67.125 - nightly)

**Comment by srirambv** [comment]
Verification passed on 


Brave | 0.69.119 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Linux


* Verified test plan from https://github.com/brave/brave-core/pull/3244
