### ISSUE TITLE
Set Shields simple and advanced view as global default in Settings

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#4784]
## Description
Allow users to set their global default view of the Shields panel. Follow-up to #1196. 

## Designs
Surface an option in Shields settings to set the global default view of Shields:

![shields settings default view](https://user-images.githubusercontent.com/2388823/59471387-c72fa780-8def-11e9-86cb-61ec9d88eac9.png)

The global default view applies to any site the user has not previously clicked to switch views (that count as a site-specific customization and will be retained). Turning on or off Shields does not affect the site-specific view. 

![user flows - simple and advanced global customization](https://user-images.githubusercontent.com/2388823/59471395-ca2a9800-8def-11e9-976f-2ba630c039df.png)

Assets available in this zipped folder: [assets.zip](https://github.com/brave/brave-browser/files/3288338/assets.zip)
SVG assets : [svg assets.zip](https://github.com/brave/brave-browser/files/3443883/svg.assets.zip)

#### Settings --> Shields
1. Go to `brave://settings/shields`
2. Select Simple View
3. Go to a website
4. Open Shields
--> **Expected:** Chceck shields view is Simple

5. Go to `brave://settings/shields` again
6. Select Advanced View
7. Go to a website
8. Open shields
--> **Expected:** Chceck shields view is Advanced (larger)

#### Shields --> Settings
0. Clean profile
1. Go to a website
2. Open shields
--> **Expected:** Shields opens in Simple view (clean profile defaults to "simple")

3. Toggle option to "Advanced view" inside shields popup
4. Visit `brave://settings/shields` in another window or tab
--> **Expected:** "Default view" has 'Advanced view' selected

5. Visit website again
6. Open Shields
7. Click 'Simple View' inside shields popup
8. Switch back to Settings tab / window
--> **Expected:** "Default view" has 'Simple view' selected

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.121 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Ubuntu 18.04 LTS

- Verified test plan from https://github.com/brave/brave-browser/issues/4784#issue-454355225
