### ISSUE TITLE
Implement "allow once" for each Shields option

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#4785]
Let's add back-end support to allow each Shields choice to be allowed "once" — either until the browser is closed, or until the tab is closed.

- [ ] trackers blocked
- [ ] https connection
- [ ] cookie
- [ ] device recognition

**Comment by bsclifton** [comment]
@tomlowenthal how do we want this to look? Can we get a mock up / spec?

**Comment by tomlowenthal** [comment]
I'd like this issue just to be about adding the functionality to the back-end. We can work on the front-end separately.

**Comment by simonhong** [comment]
I think this should be postponed after migrating to network service because shields features are tied with `NetworkDelegate` that will be disappeared during the migration.
cc: @bsclifton @iefremov

**Comment by bsclifton** [comment]
@simonhong good call - I'll mark this as blocked

cc: @tomlowenthal

**Comment by rebron** [comment]
Closing as stale.
