### ISSUE TITLE
Disable motion sensors on desktop

### ISSUE THREAD

**Issue by snyderp** [brave/brave-browser#4789]
## Test plan
See https://github.com/brave/brave-core/pull/2802

## Description
Currently Brave enables the motion sensor APIs by default
![Screen Shot 2019-06-10 at 3 17 18 PM](https://user-images.githubusercontent.com/76526/59230613-dc5bca80-8b92-11e9-81cc-39ca1197f7e6.png)

Brave blocks motion sensors on Android by default currently (https://github.com/brave/browser-android-tabs/issues/1669).  Would be good to disable on desktop too by default.  Most of the time it'll be a no-op, but would be relevant on some systems (e.g. tablets).

Low web compat risk since most other browsers don't support: https://caniuse.com/#search=sensor

**Comment by fmarier** [comment]
Looks like this is a trivial fix:See https://github.com/bromite/bromite/issues/319

**Comment by bsclifton** [comment]
Re-opening after https://github.com/brave/brave-core/pull/2802 was reverted with https://github.com/brave/brave-core/pull/3517

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.72.110 Chromium: 78.0.3904.70 (Official Build) dev (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/2802
![image](https://user-images.githubusercontent.com/34715963/67679509-88a71d80-f989-11e9-90b9-9ba2d450249e.png)
![image](https://user-images.githubusercontent.com/34715963/67679679-e89dc400-f989-11e9-85b9-938a9d8ee10c.png)

Verified that Motion Sensors are off by default on clean profile and upgrade from 0.70.x
![image](https://user-images.githubusercontent.com/34715963/67679224-e9822600-f988-11e9-9536-6c7f5aa4ae31.png)
