### ISSUE TITLE
Use new adblock-rust library

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#4793]
## Description 

Replace brave/ad-block with the new Rust based library.

Use https://github.com/brave/adblock-rust via https://github.com/brave/adblock-rust-ffi

## Test plan

We should re-test a lot of the recently closed ad-block webcompat fixes.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified that the sites are working fine and there are no web compact issues:
- Verified Ad blocking is working as expected
- Verified that ads and trackers count is increased in stats when ads & trackers are blocked in a site
https://techcrunch.com/
https://www.godlikeproductions.com/
https://www.boston.com/
https://www.chicagotribune.com/
https://www.aftonbladet.se/
https://www.expressen.se/
https://www.notebookcheck.com/
https://www.foxnews.com/
https://www.foxbusiness.com/
https://cnn.com/
https://Amazon.com/
