### ISSUE TITLE
Wallet is in a persisted bad state until wallet recovery is complete

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#4794]
## Description 

Wallet is recovered in two separate stages. Payment id and then the private key. If the application crashes or other logic is added in the future (such as confirmations) the wallet will need to be recovered again (until successful) or transactions will fail.

## Steps to Reproduce

   1. Recover wallet
   2. Quit browser

## Actual result:
Wallet payment id and private key are persisted separately

## Expected result:
Wallet should only be persisted once both payment id and private key are known

## Reproduces how often: 

Easily reproducible for confirmations Ads Rewards (issues/4330)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? Yes
- Is the issue reproducible on the latest version of Chrome? No

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Linux

* Verified restoring a wallet with grants and cashed in tokens are retained on the new profile
* Verified restoring the wallet with ads grant/UGP grant is retained 
* Verified restoring the wallet corrects the amount of the pending rewards
