### ISSUE TITLE
Refactor wallet public_key to private_key and remove logging of private key to console

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#4796]
Refactor Confirmations wallet `public_key` to `private_key` and remove logging of private key to console

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Linux

* Verified ads viewed and confirmations are redeemed
* Verified `private key` is masked in logs
![image](https://user-images.githubusercontent.com/17010094/60310398-b9664000-9920-11e9-8b20-9a0fbc945dcd.png)
