### ISSUE TITLE
Fix ads should only be sustained after the page has fully loaded

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#4798]
## Description 

Fix Ads should only be sustained after the page has fully loaded

## Steps to Reproduce

   1. View an Ad

## Actual result:

Ad is sustained 10 seconds after page starts to load

## Expected result:
Ad should be sustained 10 seconds after page has fully loaded

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No 
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.116 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Windows 10 OS Version 1803 (Build 17134.523)



- Verified the test plan from https://github.com/brave/brave-core/pull/2658
![image](https://user-images.githubusercontent.com/38657976/62473449-62c11100-b7be-11e9-84d2-26999822c9d2.png)
