### ISSUE TITLE
Get geolocations to work with our endpoint

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#48]
See in muon:
`git grep google_api_endpoint`
`git grep google_api_key`

See brave/brave:
`git grep antimuon_google_api_endpoint`
`git grep antimuon_google_api_key`

**Comment by bbondy** [comment]
QA notes: just make sure geolocations works.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

* Verified geolocation shown on https://browserleaks.com/geo
* Verified geolocation shown on https://html5demos.com/geo/
* Verified geolocation shown on https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation
* Verified geolocation shown on https://maps.google.com/ when your location button is clicked
