### ISSUE TITLE
Fix fuzzy favicons on NTP Top Site tiles

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#480]
## Description
Currently the icons on the top sites tiles on NTP are fuzzy and low-res.  Implement new spec for favicons in newtab page top sites to make them high res.

see [this link]( https://docs.google.com/document/d/1xkmag07xvO4P9PgUQM8s6doTtON5Ox_McOpzTXqLVvM/edit) for spec (courtesy of @jamesmudgett.)

**Comment by bsclifton** [comment]
@cezaraugusto @karenkliu @rebron is this still something we'd like to do?

**Comment by cezaraugusto** [comment]
@bsclifton yes per last convo I had with @karenkliu. I'm planning to make this one after the top sites refactor and along with https://github.com/brave/brave-browser/issues/6642

**Comment by karenkliu** [comment]
bump ☝️ Let's get higher res icons on NTP Top Site tiles!

**Comment by bsclifton** [comment]
We should be able to read out (when loading the page or via a handler, like FaviconSource) the `apple-touch-icon` element/value and store in Favicon cache:
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by meejle** [comment]
Came here looking for this, apple-touch-icons were going to be my suggestion! (I assume that's what the iOS "Favourites" uses already.)

Glad it's in the works! 😁

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/14485
