### ISSUE TITLE
Fix retry failed confirmations only if we are not currently retrying

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#4801]
## Description 

Fix retry failed confirmations only if we are not currently retrying

## Steps to Reproduce

   1. View an Ad (using Charles Proxy to rewrite the confirmation request so that it fails)

## Actual result:

Failed confirmations are retried every-time a token is successfully redeemed

## Expected result:
Failed confirmations should only retry if we are not already retrying

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.68.130 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2662.
