### ISSUE TITLE
Split big bat_contribution file in ledger

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#4807]
Contribution file in native ledger is too big. We should split it into 4 pieces

- contribution
- phase_one
- phase_two
- unverified

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.68.119 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2654
* Verified test plan for auto-contribute and auto-contribute+recurring monthly tips
