### ISSUE TITLE
[Suggestion] Add an anti-adblock detection system

### ISSUE THREAD

**Issue by AoiYui** [brave/brave-browser#4808]
This isn't really an issue in the normal sense but I feel like it deserves some attention.
A frequent issue I have if I'm using a website is adblock detection most websites can do it nowadays and many will refuse you services. I get that a lot of sites use ad revenue but being forced to sit through 10+ minutes of ads videos to watch and 20 minute video stream (cough crunchyroll cough cough) is inexcusable. Bad jokes aside it would be really nice to have a way to get past those without disabling the adblocker especially since this browser is advertised as an adblocking browser.

Sorry about the weird way of labeling it I'm not sure how to add a label.

**Comment by srirambv** [comment]
Do you have a list of sites where the anti-adblocker is shown? 

cc: @ryanbr

**Comment by ryanbr** [comment]
Some depend on cosmetic filtering;  (so when when we implement it, it'll be hit). Example below is Admiral.

```
https://www.politicususa.com/
https://www.al.com/ 
https://www.nuvo.net/
https://www.pinknews.co.uk/
```


Others use simple javascript/image checks.

```
stream2watch.ws
dreamdth.com
```

And there will be others that'll check for both / multiple scripts/url being loaded.

`ondemandkorea.com`

see; https://www.reddit.com/r/uBlockOrigin/comments/benkio/ondemandkoreacom_blocking_the_contents_for/

**Comment by ryanbr** [comment]
a few more; sample anti-adblock urls

```
https://poststar.com/
http://www.games.co.uk/game/bubble-shooter-classic
https://www.wcvb.com/article/the-week-in-review-politics-edition-1560083971/27860693 
https://www.glamourmagazine.co.uk/?international 
https://knowyourmeme.com/memes/bart-i-dont-want-to-alarm-you

```

**Comment by AoiYui** [comment]
> Do you have a list of sites where the anti-adblocker is shown?
> 
> cc: @ryanbr

I don't think it's humanely possible for there to be a list of every anti-adblocker website but I can list a few streaming sites I know of.

**Comment by srirambv** [comment]
@AoiYui  definitely not a comprehensive list of sites. Which ever you have come across or the popular ones you have seen it on. Always good to have a list to start fixing them

**Comment by srirambv** [comment]
@ryanbr adding `https://thehindu.com/` to the list as well.  Site loads without issue with adblock disabled
<img width="1201" alt="Screenshot 2019-06-11 at 7 25 25 PM" src="https://user-images.githubusercontent.com/17010094/59313380-b9a6e000-8c7e-11e9-9dec-36028dc37396.png">

**Comment by AoiYui** [comment]
If I find any more I'll come back and add them to the op

**Comment by ryanbr** [comment]
`@@||thgim.com/static/js/ads.min.js$script,domain=thehindu.com` 

would fix this.
