### ISSUE TITLE
Ads Rewards Grant Panel changes!

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#4814]
Horizontal claim (Change text): Your rewards from Ads are here!

![image](https://user-images.githubusercontent.com/35932307/59311919-05965c80-8c60-11e9-9cb1-392e5eb848fe.png)

Vertical claim (Change text): 
Replace 'It's your lucky day!' to 'Brave Ads Rewards!'
Replace 'Your token grant is on its way' to " Your rewards grant from Brave Ads is on its way"
Replace: 'Free Token Grant' to " Your Brave Ads Token Grant'

![image](https://user-images.githubusercontent.com/35932307/59312006-442c1700-8c60-11e9-915d-bfc3d4f91e1f.png)

Cross-reference: #4330 
@tmancey @alexwykoff

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.104 Chromium: 75.0.3770.100 (Official Build) dev (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the STR from the description
  - Verified that the Horizontal claim text changed to "Your rewards from Ads are here!"
![image](https://user-images.githubusercontent.com/38657976/61523129-5ce2d600-aa31-11e9-8e0b-e43966c70e04.png)

  - Verified that the Vertical claim text  'It's your lucky day!' changed to 'Brave Ads Rewards!'
  - Verified that 'Your token grant is on its way' changed to " Your rewards grant from Brave Ads is on its 
  - Verified that 'Free Token Grant' changed to " Your Brave Ads Token Grant'
    
  
![image](https://user-images.githubusercontent.com/38657976/61523145-653b1100-aa31-11e9-8a96-def85f16f2a8.png)
