### ISSUE TITLE
alert dialog box will not change color when switched to Light mode

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#4815]
Follow up to https://github.com/brave/brave-core/pull/2352

## Steps to Reproduce

1. Clean install
2. Launch Browser
3. Change `Brave colors` to `Dark` under `brave://settings/appearance`
4. Open `https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_alert` and click `Try it` (leave alert dialog open)
5. Change `Brave colors` to `Light` under `brave://settings/appearance`
6. Check alert dialog from 4.

Important: Closing the dialog and opening it again will show proper color
Note: Light-Dark theme switch works OK

## Actual result:

Alert dialog did not change the color.
Alert dialog remains `Dark` themed

![image](https://user-images.githubusercontent.com/34715963/59318434-5e4d1000-8cc7-11e9-9ce2-c3fd6b60c1a1.png)

## Expected result:
Alert dialog is `Light` themed

![image](https://user-images.githubusercontent.com/34715963/59318464-7755c100-8cc7-11e9-994d-e9f0ef4ed36a.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.66.87 Chromium: 75.0.3770.80 (Official Build) beta (64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Windows 7 Service Pack 1 (Build 7601.24465)

cc @brave/legacy_qa @simonhong

**Comment by kjozwiak** [comment]
Reproduced on `macOS 10.14.5 x64` using the following build:

Brave | 0.68.60 Chromium: 75.0.3770.90 (Official Build) nightly(64-bit)
-- | --
Revision | a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}
OS | Mac OS X

<img width="499" alt="Screen Shot 2019-06-19 at 10 39 59 AM" src="https://user-images.githubusercontent.com/2602313/59775151-b1523480-927e-11e9-89b4-7155b648df5f.png">
