### ISSUE TITLE
Follow up - Verified sites need a different BAT logo 

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#4817]
Follow up to: https://github.com/brave/brave-browser/issues/4043

## Steps to Reproduce

 1. Clean install
 2. Enable Rewards
 3. Do not dismiss Grant notification
 4. Go to a verified publisher 

Note: tested on staging server

## Actual result:

Verified Rewards icon in URL bar
![image](https://user-images.githubusercontent.com/34715963/59321420-37e0a200-8cd2-11e9-8168-d3818cfd4b89.png)

## Expected result:
Notification Rewards icon in URL bar
![image](https://user-images.githubusercontent.com/34715963/59321495-8a21c300-8cd2-11e9-98f7-7b948c700d46.png)
Notification + verified publisher = Notification Rewards icon per spec: 
![Rewards Verified Toolbar](https://user-images.githubusercontent.com/29072694/56379243-285a4680-61c4-11e9-922e-4b0816e74b9e.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.66.87 Chromium: 75.0.3770.80 (Official Build) beta (64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Windows 7 Service Pack 1 (Build 7601.24465)

cc @brave/legacy_qa @NejcZdovc @rossmoody

**Comment by GeetaSarvadnya** [comment]
Reproduce on Linux

Brave | 0.66.87 Chromium: 75.0.3770.80 (Official Build) beta (64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Linux

**Comment by rebron** [comment]
Speaking with @david and @mandar-brave, this issue maybe invalid and we'll need to update the spec.

Once a user has seen a notification, we can return to showing the verified/unverified status icon. A user does not have to dismiss the notification before showing the verified/unverified status icon again.

"Notification icon" supersedes "site verified icon" when a notification hasn't been viewed/is pending. Once viewed, can reset and go back to display "site verified icon".

**Comment by kjozwiak** [comment]
> Once a user has seen a notification, we can return to showing the verified/unverified status icon. A user does not have to dismiss the notification before showing the verified/unverified status icon again

@rebron what about the the case where someone hasn't seen a notification yet but still visits a verified website? Example:

* launch brave using `--rewards=staging=true`
* enable rewards via the rewards panel (dismiss right away)
* after a few seconds, you'll see another notification icon due to a grant being available
* visit duckduckgo.com <-- verified icon is being displayed even though the grant notification wasn't viewed by the user

**Comment by NejcZdovc** [comment]
we don't track if user already saw notification but didn't dismiss it

**Comment by NejcZdovc** [comment]
this is working as expected now (image in the original report)
