### ISSUE TITLE
Bug that lets me view balance of any unverified website

### ISSUE THREAD

**Issue by kirkins** [brave/brave-browser#482]
Hello, I seem to have found a glitch on the publisher dashboard.

I have 0.26 BAT balance on my account.

I recently connected my uphold and got this pop-up for the first time.

![screenshot from 2018-07-04 16-20-07](https://user-images.githubusercontent.com/9503662/42293326-60fbd74c-7fa7-11e8-9fe6-bb5ee50c8caf.png)

After I click "confirm" it updates my balance and gives a completely wrong number.

![screenshot from 2018-07-04 16-21-03](https://user-images.githubusercontent.com/9503662/42293335-780cecaa-7fa7-11e8-89e2-00c2f97398ab.png)

# My theory on why this happens

Something unique about my account. Before I added my YouTube channel as the main site, I tried adding my blog which is on https://steemit.com/@kirkins

I couldn't complete the process since I don't actually own the steemit.com domain. I also didn't remove the failed attempt. So I think have it on my dashboard as a site I own.

I'm thinking after the balance updates on selecting the currency type the balance shows both verified and non-verified websites.

# Confirming theory

To confirm I removed steemit.com and added google.com without actually doing the verification.

I can now see the unclaimed balance that google.com has:

![screenshot from 2018-07-04 16-34-15](https://user-images.githubusercontent.com/9503662/42293449-49e58e3a-7fa8-11e8-93e4-979acee69ec1.png)

With this method I can keep removing the failed sites and adding new ones to check the balance of any website.

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/brave-browser/issues/482

**Comment by kirkins** [comment]
Cool feel free to send one of those BAT promo codes or swag my way 😉
