### ISSUE TITLE
Add DDG search engines custom UA

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#4822]
This task is just to verify the custom HTTP headers work on Android as they do on Desktop.

**Comment by emerick** [comment]
Used remote debugging to confirm that `User-Agent` header includes `Brave Chrome` when visiting duckduckgo.com and just `Chrome` when visiting other sites. Will attach screenshots.

**Comment by emerick** [comment]
Closing as it appears to be working as intended on Android.
