### ISSUE TITLE
Global switches for ad blocking, HTTPSE, and fingerprinting protection

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#4830]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bbondy** [comment]
FYI @simonhong, @yrliou is going to take this one.

**Comment by bsclifton** [comment]
@bbondy not sure how helpful this is- but we had an old PR for making each of these toggleable via command line flag (by @iefremov):
https://github.com/brave/brave-core/pull/1492
