### ISSUE TITLE
Brave stats on New Tab Page

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#4836]
- [x] Stub UI: https://github.com/brave/brave-browser/issues/5982
- [x] Set real stats to UI

**Comment by simonhong** [comment]
Need to find the way how to add string or color values w/o direct modification of resource files like `android_chrome_strings.grd`

**Comment by SergeyZhukovsky** [comment]
About colors. I don't know any way how to do it for now without patching chromium's xml files.
