### ISSUE TITLE
Google access permission for account message on reboot

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#4837]
Currently we have a message to sing in to a Google account on each device reboot. We need to remove that attempt and the message.
https://github.com/brave/browser-android-tabs/commit/a045fabc25f04f71eac4933be1c4e6fd099aaa1c

**Comment by AlexeyBarabash** [comment]
Closed by merge of https://github.com/brave/brave-core/pull/2823

**Comment by AlexeyBarabash** [comment]
There is a complain notification arrives sometimes
