### ISSUE TITLE
Turn off search suggestions by default, use top 500 Alexa sites

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#4840]
It's probably already in the brave-core, so just check it first.

**Comment by bbondy** [comment]
Test Plan:

- Type some characters like `s` and make sure alexa top 500 sites come up.
- Type some characters like `brendan eich` and make sure no search suggestions come up

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.57 x64 nightly build
- Verified typing a single character bring up suggestions from Alexa top 500 sites
- Verified typing a word doesn't bring up any search suggesions
--------
Verification passed on Samsung Tab A with Android 9 running 1.5.57 x64 nightly build
- Verified typing a single character bring up suggestions from Alexa top 500 sites
- Verified typing a word doesn't bring up any search suggesions
