### ISSUE TITLE
User referral program

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#4841]
Add support for compiling Android with `enable_brave_referrals` set and verify that:

- Referral headers are downloaded as expected
- Offer URL page is launched, if specified
- `X-Brave-Partner` header is added when visiting partner sites

**Comment by emerick** [comment]
Looked at this briefly and noticed a few things we'll want to address:

1. Need to set `enable_brave_referrals` to true for android in `buildflags.gni`
1. Need to update `GetPlatformIdentifier` to support `OS_ANDROID`
1. Need to find a different approach to opening offer page in new tab, as we can't include `browser.h`
1. Need to find a different approach to tracking first run, as `first_run.cc` doesn't get compiled into the binary on Android

**Comment by emerick** [comment]
Just to follow up on this comment (https://github.com/brave/brave-browser/issues/4841#issuecomment-521730121) all of the items mentioned there are addressed in this PR now.
