### ISSUE TITLE
Verified Publisher Rewards icon is not updated after publishers list update

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#4846]
## Steps to Reproduce

Test case 1
1. Clean install
2. Open `kjozwiak.github.io`
3. Enable rewards through Rewards Panel
4. Open Rewards Panel
5. Click `Refresh Status`

Test case 2
1. Clean install
2. Enable rewards
3. Make sure publishers list is downloaded
4. Close Brave
5. Delete `kjozwiak.github.io` entry from `publishers_list`
6. Run Brave 
7. Open `kjozwiak.github.io`
8. Open Rewards Panel
9. Click `Refresh Status`

Note: Reload of the page will show proper icon

## Actual result:

Regular Rewards(BAT) icon is shown in the URL bar
![image](https://user-images.githubusercontent.com/34715963/59322661-85abd900-8cd7-11e9-9ffb-b67bcbb15cd6.png)

![rewards_check_again](https://user-images.githubusercontent.com/34715963/59322549-e686e180-8cd6-11e9-8694-c7620c64b79c.gif)

## Expected result:
Verified publisher Rewards(BAT) icon is shown in the URL bar
![image](https://user-images.githubusercontent.com/34715963/59322576-10d89f00-8cd7-11e9-9990-b3bef418e328.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.66.87 Chromium: 75.0.3770.80 (Official Build) beta (64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Windows 7 Service Pack 1 (Build 7601.24465)

cc @brave/legacy_qa @NejcZdovc @rossmoody

**Comment by NejcZdovc** [comment]
@btlechowski is this still a problem on the latest Nightly?

**Comment by NejcZdovc** [comment]
closing as stale

**Comment by btlechowski** [comment]
@NejcZdovc Sorry I must have missed the message. 

The issue still reproduces. 

Brave | 1.15.14 Chromium: 85.0.4183.83 (Official Build) nightly (64-bit)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/91447435-f86f8880-e878-11ea-8649-830b5d8ee428.png)

Note: just like in OP, the issue is fixed after page reload

**Comment by zenparsing** [comment]
This is likely due to the state caching strategy used by the panel.

**Comment by Miyayes** [comment]
Likely resolved already with WebUI Rewards panel, and prefix list.
