### ISSUE TITLE
Update paper buttons to spec

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#4852]
Related: https://github.com/brave/brave-browser/issues/3633

Full button spec can be found here: https://share.goabstract.com/22f7c7af-fa47-404f-aeca-b896f0c58b4b

![image](https://user-images.githubusercontent.com/29072694/59327847-a22c1f00-8c9f-11e9-8b1b-23c27c443641.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.119 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2778
