### ISSUE TITLE
Github's conflict resolution tool doesn't work w/ shields up

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#4854]
Just endlessly spins.  Dropping shields fixes.

<img width="1634" alt="Screen Shot 2019-06-11 at 11 50 20 PM" src="https://user-images.githubusercontent.com/76526/59329431-b1ad6700-8ca3-11e9-83e8-7fdd2fcc574a.png">

You can access the page by clicking "resolve conflicts" in the below page

<img width="790" alt="Screen Shot 2019-06-11 at 11 52 40 PM" src="https://user-images.githubusercontent.com/76526/59329570-081aa580-8ca4-11e9-91d0-397c37297b71.png">

Oddly, reloading the page _with_ shields up fixes…

**Comment by ryanbr** [comment]
Is this still a problem @pes10k  ? I recently did a conflict resolution in https://github.com/brave/referrer-whitelist/pull/34 without issue

**Comment by pes10k** [comment]
I am not able to reproduce either.  If you can't get it to trigger, I think this is safe to close
