### ISSUE TITLE
ads earnings notification partially translated

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#4861]
## Steps to Reproduce

1. Change language to `Norwegian`
2. Show ads earnings notification

Note: also reproducible for `German`
TODO: check other languages.

## Actual result:

`Your earnings from ads are available.` is not translated
![image](https://user-images.githubusercontent.com/34715963/59356362-faf3ca00-8d28-11e9-8f1c-c382d3229404.png)

![image](https://user-images.githubusercontent.com/34715963/59359442-a2273000-8d2e-11e9-9c1a-7f8d0d627d80.png)

German:
![image](https://user-images.githubusercontent.com/34715963/59361806-ba00b300-8d32-11e9-8ebe-45c321657f97.png)

## Expected result:
`Your earnings from ads are available.` is translated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Verification passed on

Brave | 0.66.88 Chromium: 75.0.3770.87 (Official Build) beta (64-bit)
-- | --
Revision | 9dc58a2353af60ab2b48bab98a25bc43ed59085d-refs/branch-heads/3770@{#982}
OS | Windows 7 Service Pack 1 (Build 7601.24465)

cc @bsclifton @brave/legacy_qa

**Comment by tmancey** [comment]
@anthonypkeane this ticket will need resolving to fix localization issues on the next uplift from brave-core to android

**Comment by rebron** [comment]
@NejcZdovc We're not seeing this string in transifex to be localized.

**Comment by btlechowski** [comment]
No longer reproducible on

Brave | 1.2.11 Chromium: 78.0.3904.108 (Official Build) dev (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/69744109-d9a06200-113f-11ea-99f9-33dfcc7a2a7e.png)
![image](https://user-images.githubusercontent.com/34715963/69744130-e2913380-113f-11ea-9312-2b6eafa18753.png)

**Comment by btlechowski** [comment]
Verified passed with

Brave | 1.2.11 Chromium: 78.0.3904.108 (Official Build) dev (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

Verified test plan from the description.
German language:
![image](https://user-images.githubusercontent.com/34715963/69744366-55021380-1140-11ea-8e64-60780d870f41.png)
![image](https://user-images.githubusercontent.com/34715963/69744398-61866c00-1140-11ea-8971-c87496858768.png)
