### ISSUE TITLE
Investigate arm64 build failure because of rust dependencies

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#4863]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by simonhong** [comment]
Compileted arm 64 build with `npm run build --  --target_os=android --target_arch=arm64` w/o rust dependency error. During the arm64 build, link error was found (https://github.com/brave/brave-browser/issues/6397) but it's not related with this issue.
