### ISSUE TITLE
"Brave Verified Creator" & "Refresh Status" are not translated in Brave Panel

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#4865]
## Steps to Reproduce

   1. Change language to `German`
   2. Open a verified creator page
   3. Open Brave Panel

Note: also reproducible for Norwegian
Not reproducible: Polish
TODO: check other languages

## Actual result:
`Brave Verified Creator` is not translated in Brave Panel

![image](https://user-images.githubusercontent.com/34715963/59361806-ba00b300-8d32-11e9-8ebe-45c321657f97.png)

## Expected result:
`Brave Verified Creator` is translated in Brave Panel

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.66.88 Chromium: 75.0.3770.87 (Offizieller Build) beta (64-Bit)
-- | --
Überarbeitung | 9dc58a2353af60ab2b48bab98a25bc43ed59085d-refs/branch-heads/3770@{#982}
Betriebssystem | Windows 7 Service Pack 1 (Build 7601.24465)

Brave | 0.68.36 Chromium: 75.0.3770.87 (Offisiell delversjon)nightly (64-bit)
-- | --
Versjon | 9dc58a2353af60ab2b48bab98a25bc43ed59085d-refs/branch-heads/3770@{#982}
OS | Windows 7 Service Pack 1 (Build 7601.24465)

cc @brave/legacy_qa @bsclifton @NejcZdovc

**Comment by kjozwiak** [comment]
Example of the "Refresh Status" string not being translated while using the Norwegian locale:

![Skjermbilde 2019-06-12 kl  20 50 27](https://user-images.githubusercontent.com/2602313/59402645-547de800-8d6d-11e9-814b-18c94fd0dc7a.png)

**Comment by rebron** [comment]
This should be fixed with the next translation pull. cc: @mkarolin

**Comment by mkarolin** [comment]
@rebron the localization files pulled in with c76 do have it translated. So should be in the master/Nightly at this point.
