### ISSUE TITLE
Fix staging/production environment support for Android Ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#4867]
## Description 

Fix staging/production environment support for Android Ads as staging is used for production and production is used for staging

## Steps to Reproduce

   1. Enable Ads

## Actual result:

Getting signed tokens fails

## Expected result:
Getting signed tokens should succeed

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by kjozwiak** [comment]
@tmancey assuming this should be `QA/Yes` and checked by QA? Is there more detailed cases that we can run through? Is this basically making sure ads are working on both `staging` and `production`?

**Comment by tmancey** [comment]
@kjozwiak This is just basically making sure staging/production work as expected, thanks

**Comment by kjozwiak** [comment]
Labelling this as `QA/No`. QA has been checking `ads` on both production & staging on desktop/android.
