### ISSUE TITLE
`SEND TIPS` is not translated in Brave Panel for some locales

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#4868]
## Steps to Reproduce

   1. Change language to `Norwegian`
   2. Open a verified creator page
   3. Open Brave Panel

Not reproducible in: Polish

## Actual result:
`SEND TIPS` is not translated in Brave Panel

![image](https://user-images.githubusercontent.com/34715963/59367992-88d9b000-8d3d-11e9-9ed8-3d0e3ff9718a.png)

## Expected result:
`SEND TIPS` is translated in Brave Panel

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.66.88 Chromium: 75.0.3770.87 (Offizieller Build) beta (64-Bit)
-- | --
Überarbeitung | 9dc58a2353af60ab2b48bab98a25bc43ed59085d-refs/branch-heads/3770@{#982}
Betriebssystem | Windows 7 Service Pack 1 (Build 7601.24465)

Brave | 0.68.36 Chromium: 75.0.3770.87 (Offisiell delversjon)nightly (64-bit)
-- | --
Versjon | 9dc58a2353af60ab2b48bab98a25bc43ed59085d-refs/branch-heads/3770@{#982}
OS | Windows 7 Service Pack 1 (Build 7601.24465)

cc @brave/legacy_qa @bsclifton @NejcZdovc

**Comment by LaurenWags** [comment]
Still occurs with 1.1.20:

Brave | 1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)
-- | --
Revision | 99b6d241cf84f7fa7434ae8a59f9e74eb1464280-refs/branch-heads/3945@{#888}
OS | macOS Versjon 10.13.6 (bygg 17G5019)

<img width="395" alt="Screen Shot 2019-12-10 at 5 40 42 pm" src="https://user-images.githubusercontent.com/28145373/70575314-3f471200-1b74-11ea-912b-c23fdcb63675.png">

**Comment by btlechowski** [comment]
This is still reproducible in 1.4.x. However in google translate `Send tip` translates to `Send tips`.
![image](https://user-images.githubusercontent.com/34715963/75438929-266f2100-5959-11ea-8242-31796bc48438.png)

I don't know if this is proper way to translate it though.

Brave | 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

![image](https://user-images.githubusercontent.com/34715963/75438823-f293fb80-5958-11ea-87ee-cb768cd84052.png)

Not reproducible in Polish and German.

**Comment by rebron** [comment]
@btlechowski Is this still an issue with 1.11.97 and latest transifex pull or are we saying this is a wontfix based on last comment?

**Comment by btlechowski** [comment]
Still reproducible, but let's close it as wontfix.


Brave | 1.11.97 Chromium: 84.0.4147.89 (Offisiell delversjon) (64-bit)
-- | --
Versjon | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Windows 7 Service Pack 1 (Build 7601.24544)



![image](https://user-images.githubusercontent.com/34715963/88282387-c4d59780-cce9-11ea-929d-8b9c2b158197.png)
