### ISSUE TITLE
`No activities yet` in Brave Panel ends with an unicode character code in Norwegian locale

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#4870]
## Steps to Reproduce

   1. Change language to `Norwegian`
   2. Open a verified creator page
   3. Open Brave Panel
   4. Show summery

Not reproducible in: Polish, German
TODO: check other languages

## Actual result:
`Ingen aktiviteter enda &#8230;`

![image](https://user-images.githubusercontent.com/34715963/59368045-a9096f00-8d3d-11e9-9388-49daf0ecc852.png)

## Expected result:
`Ingen aktiviteter enda ...`

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.66.88 Chromium: 75.0.3770.87 (Offizieller Build) beta (64-Bit)
-- | --
Überarbeitung | 9dc58a2353af60ab2b48bab98a25bc43ed59085d-refs/branch-heads/3770@{#982}
Betriebssystem | Windows 7 Service Pack 1 (Build 7601.24465)

Brave | 0.68.36 Chromium: 75.0.3770.87 (Offisiell delversjon)nightly (64-bit)
-- | --
Versjon | 9dc58a2353af60ab2b48bab98a25bc43ed59085d-refs/branch-heads/3770@{#982}
OS | Windows 7 Service Pack 1 (Build 7601.24465)

cc @brave/legacy_qa @bsclifton @NejcZdovc

**Comment by atsyed87** [comment]
This should be fixed now the next time we pull from Tfex -- I re-reviewed the string and removed the ellipsis that was being displayed as a unicode character.  Will leave issue open until we confirm it's fixed. cc @NejcZdovc

**Comment by rebron** [comment]
@mkarolin When you get a chance can you confirm?

**Comment by mkarolin** [comment]
Checked on master and it is fixed:

![image](https://user-images.githubusercontent.com/41635752/62991657-6ab42d00-be1e-11e9-93de-9d01cf97ef61.png)
