### ISSUE TITLE
Tipping Banner doesn't appear for YouTube/Twitter/Twitch

### ISSUE THREAD

**Issue by AasmundEndresen** [brave/brave-browser#4872]
I've added my channels - but when I visit my channel it only says 'YouTube is not a verified Creator', etc  - instead of showing the actual tipping banner and my channel as a verified creator.

I have no idea how to even begin to look for the error really so any pointers would be helpful...

**Comment by NejcZdovc** [comment]
@AasmundEndresen when you add your channels you need to wait at least 2h for this change be reflected on the server. After that I would suggest that you go to your channel open rewards panel and click check again / Refresh status. This will pull the latest info and you should be verified.

Let me know if this works

**Comment by AasmundEndresen** [comment]
@NejcZdovc I verified my channels ~1 month ago, they show up as succesful at my Brave Publishers page, but when I try to visit them to see how it looks it defaults to YouTube/Twitter/Twitch as the 'publisher/creator' instead of my channel in the rewards/tipping panel.

**Comment by NejcZdovc** [comment]
@AasmundEndresen can you please tell me url's to your channels

**Comment by NejcZdovc** [comment]
and which version of brave are you using?
