### ISSUE TITLE
Loading certain site semi-crashes all brave windows (Possible potential for abuse)

### ISSUE THREAD

**Issue by ChildishGiant** [brave/brave-browser#4877]
## Description 
Loading a certain site forces all windows to go black for around a second before refreshing.

## Steps to Reproduce
Loading the site when full screen seems to always reproduce this result. I'm not gonna provide the site until it's cleared by brave staff

## Actual result:
Here's a horribly censored version as I'm not sure if this could be abused.
https://youtu.be/4U7uSLkVrTM

## Expected result:
Site should load without affecting other windows/tabs.

## Reproduces how often: 
Always

## Brave version (brave://version info)
Discovered on:
Brave: 0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)
Revision: 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS: Windows 10 OS Version 1803 (Build 17134.472)

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? There's no way to disable Brave Rewards to test?
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by scotm-gxg** [comment]
I've noticed this as well. When I leave the tab open and switch focus to another window for awhile and go back to browser (usually Gmail), it'll be black for a second or two or until the browser regains focus.

running same OS (Version 1903 though) and browser version as OP.

**Comment by rebron** [comment]
@ChildishGiant and @scotm-gxg. Are you still having this issue with 0.65.121, current release?

**Comment by scotm-gxg** [comment]
Yes, it still seems to be an issue with 0.65.121

**Comment by ChildishGiant** [comment]
Yes, stable 0.65.121 through nightly 0.68.72 all still have this issue.

**Comment by bsclifton** [comment]
@ChildishGiant @scotm-gxg are you experiencing this still? If so, maybe you can disclose the URL to us securely
cc: @diracdeltas @fmarier

**Comment by ChildishGiant** [comment]
The site that had this issue has since changed and I've tried using the wayback machine but it's not how it was in my memory or the video so I can't check if it's reproducible. I only ever experienced it with this one site so I imagine it was something odd about the way it worked.

**Comment by iefremov** [comment]
seems not really actionable
