### ISSUE TITLE
Protect Rewards APIs from replay attacks

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#4878]
The existing interactions between the client (brave-browser) and the server (ads-serve) currently rely on TLS for any kind of replay protection (i.e. if someone were to perform a successful MITM, that attacker could mount replay attacks).

In particular, we are signing requests without including an element that will expire or vary over time (e.g. a counter or a timestamp). In some cases, the payload we are signing in the API request is [empty](https://github.com/brave/brave-core/pull/2609/files#diff-4be58c322c615db274fd1beda5441559R37).

There are multiple ways to fix this, but one of the simplest ones would be to include a timestamp in the body of all requests.

This will of course require the matching server-side changes.

**Comment by NejcZdovc** [comment]
cc @evq for visibility

**Comment by fmarier** [comment]
Here are some options/ideas from @riastradh-brave.

### Option 1: Timestamps

Have browser include a timestamp in the body, and have server reject it if too old.

Pros:
- Simple
- Stateless

Cons:
- Requires browser and server to agree on what time it is, reasonably closely.

### Option 2: Challenge/response

1. Browser sends request.
2. Server sends challenge with timestamp and authenticator under secret key.
3. Browser signs challenge.
4. Browser rejects if authenticator fails or if timestamp is too old.

Pros:
- No longer relies on browser and server to agree on what time it is, only requires browser to answer in a short period of time.
- Stateless.

Cons:
- Extra round-trip, which is kind of silly because TLS _already_ has these round-trips, and we're really just looking for client authentication like TLS can already do. (However, integrating into TLS client authentication is likely a pain.)

Potential optimization:
- Server returns new challenge in each response.

### Option 3: Sequential transaction ids

1. Server stores for each user a most recent transaction ID (`txid`).
2. On startup, browser asks for current `txid`.
3. For each query, browser signs request with `txid++`.
4. Server rejects query if `txid++` is stale.

Pros:
- Only one extra round-trip per browsing session.

Cons:
- Server needs to keep state.
- Potential privacy leak in that server will tell just anyone how many transactions have happened.

### Option 4: ephemeral public encryption keys

1. Browser sends signed _ephemeral public encryption key_.
2. Server verifies signature and encrypts answer to browser.

Anyone who replays it _without_ the ephemeral private key gets undecipherable nonsense as an answer.

Pros:
- No timestamps or round-trips involved.
- Stateless.

Cons:
- About 2X the computational cost per request. 

Potential optimizations:
- Client could reuse ephemeral key pair many times in a session to reduce computational cost.
- Server could also cache map from client's public key to client/server shared secret and nonce to reduce server's computational cost for repeated queries.
- Client specifies requested nonce in signed request so server need not remember it to avoid nonce reuse -- all this only if it is worthwhile for client to reuse a key pair across many requests, of course.

**Comment by evq** [comment]
There are two ads APIs which require signatures currently:
`POST /confirmation/payment/{paymentId}` - which is not vulnerable to replay attacks by nature of the cryptographic protocol it is implementing
`GET /confirmation/payment/{paymentId}` - you would only be able to see the amount of confirmations this wallet has

**Comment by fmarier** [comment]
Based on https://github.com/brave/brave-browser/issues/4878#issuecomment-501887462 and a discussion with @evq, it doesn't look like a high-priority to fix this given that the impact is minimal or that replay attacks are already mitigated somewhere else.
