### ISSUE TITLE
{{balancse}} being displayed when restoring wallet under Norwegian locale

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#4880]
## Description 

Once you've imported a wallet within Brave using the Norwegian locale, the success message will display `{{balanse}}` instead of the BAT balance that was restored.

## Steps to Reproduce

   1. ensure that your region and language is set to Norwegian
   2. import a brave wallet with a balance

## Actual result:

<img width="422" alt="Screen Shot 2019-06-12 at 11 48 47 PM" src="https://user-images.githubusercontent.com/2602313/59402933-8ba0c900-8d6e-11e9-83c2-bed3f87887ac.png">

## Expected result:

When restoring a wallet within Brave, it should display the correct balance being restored rather than `{{balanse}}`.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.66.88 Chromium: 75.0.3770.87 (Official Build) beta(64-bit)
-- | --
Revision | 9dc58a2353af60ab2b48bab98a25bc43ed59085d-refs/branch-heads/3770@{#982}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes, 0.65.118 CR: 75.0.3770.80`
- Can you reproduce this issue with the beta channel? `Yes, using 0.66.88 CR: 75.0.3770.87`
- Can you reproduce this issue with the dev channel? `Yes, using 0.67.79 CR: 75.0.3770.80`
- Can you reproduce this issue with the nightly channel? `Yes, using 0.68.39 CR: 75.0.3770.87`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @brave/legacy_qa

**Comment by NejcZdovc** [comment]
this needs to be fixed on transifix site as someone translated what is in curly brackets. In there should be `{{balance}}`. Because it was translated now we can't replace placeholder with a value

**Comment by kjozwiak** [comment]
@NejcZdovc who usually fixes issues on `transifix`?

**Comment by NejcZdovc** [comment]
@kjozwiak not sure

**Comment by kjozwiak** [comment]
@mkarolin mind taking a look at this?

**Comment by mkarolin** [comment]
Fixed on `Transifex`.

**Comment by bsclifton** [comment]
@mkarolin SGTM! 😄

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.5 x64` using the following build:

Brave | 0.65.120 Chromium: 75.0.3770.90 (Official Build) (64-bit)
-- | --
Revision | a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}
OS | Mac OS X

![Skjermbilde 2019-06-14 kl  07 36 58](https://user-images.githubusercontent.com/2602313/59517868-82108180-8e92-11e9-9005-42e321d1775e.png)

**Comment by srirambv** [comment]
* Verification passed on 

Brave | 0.65.120 Chromium: 75.0.3770.90 (Official Build) (64-bit)
-- | --
Revision | a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}
OS | Linux


![image](https://user-images.githubusercontent.com/17010094/59533333-2b6a6e00-8eb9-11e9-9227-2abc1a4b3bc5.png)
