### ISSUE TITLE
Processing ballots is not working

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#4881]
## Description 

Currently you need to restart browser to finish contribution.

## Steps to Reproduce

   1. Enable rewards
   2. Claim grant
   3. Tip a verified user

## Actual result:

Ballots are not processed

## Expected result:
Ballots should be processed without browser restart

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Introduced with https://github.com/brave/brave-core/pull/2654

**Comment by GeetaSarvadnya** [comment]
Verification passed on 

Brave | 0.68.116 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/2680 (ballots are processed after 2 mins of auto contribution)

![image](https://user-images.githubusercontent.com/38657976/62486377-bd696580-b7dc-11e9-86d3-9db332ee8641.png)
