### ISSUE TITLE
Photos from Photos.app do not show up in dialog box

### ISSUE THREAD

**Issue by athanasiospap** [brave/brave-browser#4889]
## Description 

My photos do not show up in open file dialogs boxes. Instead, I get this message: "Open Photos to see your photos in this list."

## Actual result:

<img width="801" alt="Screenshot" src="https://user-images.githubusercontent.com/25813948/59449044-00c3db00-8e0f-11e9-96ee-ec91fca81443.png">

## Brave version (brave://version info)

Brave | 0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Mac OS X

**Comment by ryanbr** [comment]
@athanasiospap   Hey, is this still an issue with current Brave Release, if so whats the best steps to reproduce this?

**Comment by athanasiospap** [comment]
@ryanbr Hey! It is working as expected in the latest version.

**Comment by ryanbr** [comment]
thanks for confirming @athanasiospap  much appreciated
