### ISSUE TITLE
Uninstall app shows Google Chrome support page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#489]
## Description 

Uninstall app shows Google Chrome support page

## Steps to Reproduce

   1. Install packaged build
   2. Uninstall from Settings->Apps 
   3. Once uninstalls, opens up chrome uninstalled page

## Actual result:

https://bravesoftware.slack.com/archives/C7VLGSR55/p1530813891000170

## Expected result:
Should not show the page

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Packaged build

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
cc: @bbondy @simonhong

**Comment by yrliou** [comment]
The IE with google support page is opened by https://cs.chromium.org/chromium/src/chrome/installer/util/google_chrome_distribution.cc?type=cs&q=DoPostUninstallOperations&sq=package:chromium&g=0&l=129-133

**Comment by yrliou** [comment]
We don't have uninstall survey AFAIK, so I'll remove the behavior of navigating to an uninstall survey URL directly instead of replacing urls.

**Comment by btlechowski** [comment]
Verification passes on

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

@GeetaSarvadnya Can you check on Win10?
