### ISSUE TITLE
Non-functional ad-earning notification

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#4900]
Version 0.68.36 Chromium: 75.0.3770.87 (Official Build) nightly (64-bit) [MacOS]

Clicked on the BR pyramid in the URL bar. Clicked the claim button: nothing happens. Closed out the notification and headed straight to `chrome://rewards/`. No grant.

<img width="375" alt="Screen Shot 2019-06-13 at 13 14 58" src="https://user-images.githubusercontent.com/639937/59464558-9f374880-8ddd-11e9-815c-ef2be830b62c.png">

**Comment by tmancey** [comment]
Cannot reproduce on latest versions
