### ISSUE TITLE
Tor control switch in the extensions area of settings

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#4904]
This poor soul accidentally opened a private window with Tor when they only meant to open a regular private window, and were hounded by grumpy sysadmins for their error. https://www.reddit.com/r/brave_browser/comments/bxncmt/so_long_guys_back_to_firefox_im_afraid/ 

We could let people avoid this mistake by adding a toggle in the extensions area of settings to disable Tor. Not a security feature, just a convenience feature if you know that you definitely never want Brave to use Tor.

**Comment by brianddk** [comment]
@tomlowenthal , Thank you, yes I am that unfortunate soul.  I'm on my sysadmin's "watch list" and I had to purge Brave from my network instances until I can be assured they won't "beacon" again in the future.

More than willing to compile a DLL, or hack a flag or registry setting to disable Tor.  Other users might want something a bit more accessible.

**Comment by BrendanEich** [comment]
I have DMs from folks who want this. If easy, we should knock it out, for adoption upside. Thanks.

**Comment by riastradh-brave** [comment]
Entails:

- [ ] a switch of some kind: settings, command-line
- [ ] removing / greying out menu items -- if it's a settings switch, requires browser restart to take effect
- [ ] prevent downloading the tor component
- [ ] maybe delete the component if the switch is flipped

**Comment by eddiedunn** [comment]
It would be great to see some form of this implemented.
