### ISSUE TITLE
Allow enabling of flash permnantly for some sites

### ISSUE THREAD

**Issue by Aphexus** [brave/brave-browser#4906]
Every time I restart brave I have to enable the flash for the site... This may seem like a non-issue but I use it on a site that is very slow to load so I have to click the enable text then wait for it to reload again unnecessarily. The site is trust worthy so I don't see why I have to keep doing the same enabling every time I restart.

**Comment by Aphexus** [comment]
Possibly not reloading the page would help since that is the reason why it is slow(it takes about 3 mins to reload a page simply to get flash working... which is a total of 6min rather than 3 since it occurs twice... and that is every time I open the browser).

**Comment by tomlowenthal** [comment]
This is not something that we're going to implement. We're more likely to go in the other direction and disable Flash entirely.

**Comment by Aphexus** [comment]
Are you kidding? Why? Why do you want to alienate people for no reason? There are still sites that require flash so you will be forcing people to use another browser simply because of why? Because you want to kill off flash? When you do so you also kill off everyone that is forced to use flash. There is no point in doing so. Since you are not effected by it, of course, you don't care do you? I guess I should simply stop using Brave now as I see the direction it is going...

**Comment by Aphexus** [comment]
Are you kidding? Why? Why do you want to alienate people for no reason? There are still sites that require flash so you will be forcing people to use another browser simply because of why? Because you want to kill off flash? When you do so you also kill off everyone that is forced to use flash. There is no point in doing so. Since you are not effected by it, of course, you don't care do you? I guess I should simply stop using Brave now as I see the direction it is going...

**Comment by bsclifton** [comment]
cc: @rebron

**Comment by tomlowenthal** [comment]
Yes, we want to remove Flash from the web platform because it's a substantial security and privacy risk for everyone who installs and uses it. And especially because it has a relatively hazardous update lifecycle which is going to be over at the end of next year — at which point it'll be an even riskier tool to use on the web.
