### ISSUE TITLE
Twitter metadata needs to be generalized for other media publishers

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#4907]
## Description 

twitterMetaData for Brave Rewards needs to be generalized so that it can be used for other media publishers (Reddit, GitHub)

No issue to reproduce as this is a dev concern as follow up to brave/brave-core#2665

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/2665
- Verified Inline Tip is shown when Reddit box is checked
![image](https://user-images.githubusercontent.com/38657976/65511926-e0b7b380-def5-11e9-9663-429b37534475.png)
- Verified Inline Tip is NOT shown when Reddit box is unchecked
![image](https://user-images.githubusercontent.com/38657976/65511967-fcbb5500-def5-11e9-9142-2d1a00f52c2c.png)
- Verified tipping banner for verified and unverified pubs
![image](https://user-images.githubusercontent.com/38657976/65512065-2c6a5d00-def6-11e9-9a67-98b5e7d7cde9.png)
![image](https://user-images.githubusercontent.com/38657976/65512092-3b510f80-def6-11e9-905d-87e0ce678bad.png)
