### ISSUE TITLE
Introduce build time flag for building Sparkle framework

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#4908]
Most of devs doesn't need to build Sparkle framework for debug build.

**Comment by bridiver** [comment]
QA should check to make sure updater works correctly

**Comment by LaurenWags** [comment]
Verified passed with:

Brave | 0.68.116 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

* Updated from 0.67.112 to 0.68.116 without issue.
* Updated from 0.68.114 to 0.68.116 without issue.

cc @kjozwiak to check on Mojave.
