### ISSUE TITLE
macOS: Add option to Open New Private Window with Tor directly from the Dock

### ISSUE THREAD

**Issue by Victorio115** [brave/brave-browser#4910]
## Description 

On Windows 10, and Older Versions of Windows, There is a way to open a New Private Window, directly from the taskbar without needing to have Brave Browser opened.  

But isn't there a way on Mac, to open a New Private Window, or a New Private Window with Tor, directly form the dock without needing to have Brave Browser opened.

## Steps to Reproduce

A way to open a New Private Window on Brave Browser, I have to...
   1. Open Brave Browser.
   2. Click on the Brave Menu.
   3. Click on "New Private Window".

## Actual result:

![image](https://user-images.githubusercontent.com/50971728/59482084-27d4d980-8e1c-11e9-9ecf-5bf84697a3f3.png)
This is the menu that Brave Browser shows when you click, with two fingers using the trackpad, on a MacBook.

## Expected result:
![image](https://user-images.githubusercontent.com/50971728/59482106-4044f400-8e1c-11e9-990a-bcdf13d56579.png)
Having something like this menu, but without needing to have Brave opened.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

Brave | 0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Mac OS X
JavaScript | V8 7.5.288.22
Flash | 32.0.0.207 /Library/Internet Plug-Ins/PepperFlashPlayer/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=NewExtensionUpdaterService,DesktopPWAWindowing --disable-features=AudioServiceOutOfProcess,DefaultEnableOopRasterization,UnifiedConsent,AutofillSaveCardSignInAfterLocalSave,NetworkService,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,TranslateUI --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/VictorioAcosta/Library/Application Support/BraveSoftware/Brave-Browser/Default
Variations | 5040e8a-5040e8ac134752e-f685ead32c707b42-dcf7018a411b6d4e-3f4a17dfd01ab0d3-60c33fc08927cedd-3f4a17df16e0dd70-3f4a17df414bf2d2-3f4a17df551157b-3f4a17dff88a4127-2874767e4b8c3f4-3f4a17dfb7e2524c-c92d551c411c711e-3f4a17df8f029c91-3f4a17df8982496f-3f4a17df61832c80-3f4a17dfcc20827f-77c422c591560a-29acad49853922b-3f4a17df776de70c-e0278d3ded9149a9-3f4a17df34d450b1-3f4a17dfc70841c8-a256700714bdbe54-e8c7a65bd8343fa3-3f4a17dfb517d646-3f4a17df8ee5ed19-c3125ea274658432-fa79b94c4f9b5d89-3f4a17dfc36cdb78-3f4a17df5274eb09-3f4a17dfd6d4ee9a-3f4a17df2729b628-3f4a17df44827ee5-3f4a17df332a4d9b-8e8e4a2b6a116980-3f4a17df3f79ac13-3d47f4f48f1e27f-3f4a17df6cb3969e-3f4a17df40de7b13-1aa41b589b4c4257-3f4a17df43f62d3b-3f4a17df9e5c75f1-30e1b12b2594bdf4-3f4a17df6fa07eb4-7282ca762981bcb4-3f4a17df5139837c-3f4a17df4934552d-3f4a17df7f8176d9-3f4a17df6c66bd8d-b204717823a898eb-fc93cf747a5ba892-3f4a17dfd1cd70a5-3f4a17df4ea303a6-3f4a17dfac8d4708-5460eccbb19465ab-b19465ab6e6e0c7e-3f17a7d895876445-2b71ffe42b33233e-881ca6c94da5ae82-3f4a17df56302f8c-2f882e70fd56acdf-3f4a17dfed846e24-3f4a17dfb2612322-8a9180b23dba712-a2d707c6ad6d27cc-85d38e8dcec9a952-9a6c5085f56e0452-3f4a17df8576baf1-3f4a17df2e7f6029-88947c67d00fcbde-3f4a17dfd840bbac-3f4a17df930e30f5-3f4a17df732f0134-3f4a17df9a2f4e5b-9ded16b91354da85-522c33b8494d8760-3f4a17dff9e5da91-508355f5b1ceb06f-6b7b34db0ea13bc-3f4a17df47a2af3f-3f4a17df94e68624-803f8fc4cc73f8a1-3f4a17dfb4e8892d-a2d707c67e91b7bd-c6da37cb6204e469-3f4a17df41ddf744-c78ce173

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes, I do.
- Can you reproduce this issue with the beta channel? I haven't used the Beta Channel of Brave.
- Can you reproduce this issue with the dev channel? I haven't used the Dev Channel of Brave.
- Can you reproduce this issue with the nightly channel? I haven't used the Nightly Channel of Brave.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Having Brave Shields enabled, is irrelevant for this issue.
- Does the issue resolve itself when disabling Brave Rewards? Having Brave Rewards enabled, is irrelevant for this issue.
- Is the issue reproducible on the latest version of Chrome? The version of Chrome is irrelevant for this issue.

## Miscellaneous Information:

No additional information, I think.

**Comment by TheAresjej** [comment]
+1 • Windows 10 (1809)
![Win10](https://i.imgur.com/v5SSTmw.png)

**Comment by LaurenWags** [comment]
@sangwoo108 could you add a test plan for this? I'm not sure how to enable it as I don't see it available by default.

<img width="330" alt="Screenshot 2024-03-04 at 1 48 56 PM" src="https://github.com/brave/brave-browser/assets/28145373/7240d5ee-dbec-45f6-8a04-d6efaa72343e">

Labelling as `QA/Blocked` until there's more info 👍🏻 

cc @rebron @kjozwiak

**Comment by stephendonner** [comment]
@LaurenWags I think it only appears when `Brave Beta` is active/launched

<img width="902" alt="Screenshot 2024-03-04 at 3 30 56 PM" src="https://github.com/brave/brave-browser/assets/387249/32d8816e-d2b4-47da-b319-6cca8f472a69">

**Comment by sangwoo108** [comment]
@LaurenWags  Sorry for the delayed response. @stephendonner is right. Updated test plan.

> Having something like this menu, but without needing to have Brave opened."?
#35591  I'm not sure but I haven't seen any applications do that. Maybe it's not possible.

**Comment by LaurenWags** [comment]
thanks for the extra info @sangwoo108 👍🏻

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.64.102 Chromium: 122.0.6261.111 (Official Build) beta (x86_64)
-- | --
Revision | c9343c77bd5dee3524fc45f89721ce0bf4c09b8d
OS | macOS Version 13.6.4 (Build 22G513)
```
