### ISSUE TITLE
Dobreprogramy.pl Crash every time on Brave (win10)

### ISSUE THREAD

**Issue by TheAresjej** [brave/brave-browser#4914]
## Description 
Dobreprogramy.pl Crash every time on Brave.

## Steps to Reproduce

   1.  Go [link](https://www.dobreprogramy.pl/AMD-tlumaczy-Procesory-Zen-2-sa-odporne-na-wszystkie-znane-luki-sprzetowe,News,102339.html)
   2. Scroll
   3. Crash

## Actual result:
Brave is not responding 😢

## Expected result:
Page works? 🙃 

## Reproduces how often: 
100%

## Brave version (brave://version info)
Version 0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)
Windows 10 1809 (.557)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 👍
- Can you reproduce this issue with the beta channel? 🤔
- Can you reproduce this issue with the dev channel? 🤔
- Can you reproduce this issue with the nightly channel? 🤔

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 🤔
- Does the issue resolve itself when disabling Brave Rewards? 🤔
- Is the issue reproducible on the latest version of Chrome?  🤔

**Comment by btlechowski** [comment]
Reproduced on 

Brave | 0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)
-- | --
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Windows 7 Service Pack 1 (Build 7601.24468)

The page goes into infinity loop. 
Disabling Shields solves the issue.

**Comment by rebron** [comment]
@btlechowski Can you paste in the crash report?

**Comment by btlechowski** [comment]
@rebron First I get `Page unresponsive` modal, then the page crashes.

![image](https://user-images.githubusercontent.com/34715963/59723978-9359e500-9228-11e9-8c7b-657ecce0ba6d.png)

Crash reports:
```
Uploaded Crash Report ID 6c2a07fd9251f9d9 (Local Context: e9af4e00-d550-47d4-bbf6-8b57b04450e5)
Uploaded Crash Report ID e6029bbf92ba38af (Local Context: 73983935-246d-4bbb-9366-088751cc2978)
```

Reproducible when connecting from Europe. Unable to reproduce when connecting through US VPN. Probably a GDPR related issue.
Disabling Shields solves the issue.

**Comment by ryanbr** [comment]
@TheAresjej does this occur still? Just tested from an EU IP, in a private window. Seems to be fine, no lockups so far.

**Comment by bsclifton** [comment]
cc: @btlechowski to verify (not tied to a milestone, since it was done via adblock-list update)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Ubuntu 18.04 LTS

The fix also blocks actual content on the page. Logged https://github.com/brave/brave-browser/issues/5456
