### ISSUE TITLE
Implement Reddit inline tipping for flat menu

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#4915]
## Description 

Implement Reddit inline tipping for menu that appears at bottom of posts/comments (flat menu)

New feature request

**Comment by GeetaSarvadnya** [comment]
In tipping banner the username is displayed as `u/unsociali` should it be displayed as `@u/unsociali`?

![image](https://user-images.githubusercontent.com/38657976/61814897-b64e6900-ae66-11e9-8286-82bd07a55707.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.106 Chromium: 76.0.3809.62 (Official Build) dev (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/2665
  - Verified the inline tip link for Reddit posts
     
![image](https://user-images.githubusercontent.com/38657976/61815588-36c19980-ae68-11e9-8a90-c9cea7cd8417.png)
  - Verified user can send a tip by clicking on inline tip link in Reddit posts
  - Verified Tip link is not shown when `Reddit` checkbox is unchecked in Tips panel in brave://rewards
  - Verified Tip link is not shown when brave://rewards is not enabled
