### ISSUE TITLE
Option to clear history/cache when browser closed/quit

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#492]
## Test plan
See https://github.com/brave/brave-core/pull/1213

## Description
Brave-core doesn't have an option to clear browsing history/cache upon browser exit. It would be great to have this option to bridge parity between browser-laptop and brave-core

![screen shot 2018-09-09 at 1 31 51 am](https://user-images.githubusercontent.com/4733304/45262671-4b23b180-b3d0-11e8-88a0-fd2b252db976.png)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/clear-data-on-close-missing/33647?u=eljuno

**Comment by diracdeltas** [comment]
+1 from me, i use this in b-l

**Comment by NumDeP** [comment]
For your information, when this feature is implemented, create numerous tests to check whether selected data has actually cleared on exit. On the Muon-Linux version, I had to manually click the orange 'Clear Browsing Data Now...' for it to prompt Restart Browser Now and clicking it every time for it to actually erase data on exit, which it did afterwards but never did clean/erase it before then.

One way I noticed is when certain sites would show familiar content and another easy way to deduce it was checking to see if recent links on startpage.com were still highlighted (purple)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/clear-cache-and-cookies-on-application-exit-does-version-0-55-still-have-this-feature/36938?u=eljuno

**Comment by NejcZdovc** [comment]
+1 from me

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/auto-clear-browsing-data/38042?u=eljuno

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/download-muon-version-025/38181/

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/bring-back-clear-on-close/38214

**Comment by srirambv** [comment]
@kjozwiak @rebron @bbondy we need to prioritize this as well. Been seeing a lot of +1's from community.

**Comment by kjozwiak** [comment]
Thanks @srirambv 👍 We'll triage this Tuesday during our `b-c triage` meeting when we go through all the GH boards.

**Comment by Brave-Matt** [comment]
Just added one to that very thread

**Comment by diracdeltas** [comment]
note that due to https://github.com/brave/brave-browser/issues/2400, clearing all history could clear the shield settings

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/clear-cookies-on-exit/39920?u=eljuno

**Comment by FrederickDavies** [comment]
+1
In fact I am not using Brave Core until this is implemented and it works (I have seen stuff being left behind after I close Brave Muon despite the "delete on exit" options being enabled).

**Comment by gpklinedinst** [comment]
+1
Please implement this feature ASAP. It is critical to working in a secure manner. Relying on the user to click through the "delete cookies" after every visit to a social media site is unrealistic and error prone. I've gotten used to just closing the browser and having a "clean slate" when I start it again. I'm going to try to find an old version of Brave until this is remedied.

**Comment by FatOrangutan** [comment]
To people leaving `+1` comments: could you not 👍 the original post?
To community moderators leaving `+1 from community [link]` comments: could you not edit one of your earlier similar comments to include the latest community link?

Subscribing to issues on any of the Brave repos is kind of frustrating because these two comments make for the majority of notifications I receive. Thanks and sorry for yet another useless notification.

**Comment by FrederickDavies** [comment]
FatOrangutan,
Now done.
FD

**Comment by alvinsight** [comment]
+1 from me too

**Comment by JoeBloggs2345** [comment]
Can't wait for this!

**Comment by gabrielhug** [comment]
The 'clear browsing history on exit' doesn't currently override the brave://settings/onStartup setting. If onStartup is set to "Continue where you left off" any open tabs are still remembered and re-opened on startup even if browsing history is cleared on exit. Perhaps this is intended for now, but it doesn't seem completely intuitive to me.

**Comment by rebron** [comment]
@gabrielhug I don't think 'Clear browsing history on exit' should override that on start up setting. People can change that setting back to New Tab page or a page/set of pages they want instead.

**Comment by FrederickDavies** [comment]
Is something like this (options to delete stuff on exit) going to be implemented on the Android version of Brave?

FD

**Comment by bsclifton** [comment]
@FrederickDavies good question -
cc: @anthonypkeane @SergeyZhukovsky

**Comment by FrederickDavies** [comment]
How do you find out when the fix is due to come out into the Brave Core auto-update stream?

FD

**Comment by kjozwiak** [comment]
> How do you find out when the fix is due to come out into the Brave Core auto-update stream?
> 
> FD

Here's a few methods/checks that you can use to see where a certain fix is landing:

* Check the milestone of the issue. In this case, it's set as `0.63.x`. If you take a look at https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule, `0.63.x` will be released on ~`April 23, 2019`
* Same as above, check the milestone on the PR that fixed this issue. In this case, https://github.com/brave/brave-core/pull/1213 is labelled as `0.63.x` as well. As mentioned above, `0.63.x` is slated to be released on `April 23, 2019`.

With the above information, you know that it's landing in `0.63.x`, as a double check, you can make sure that the PR is appearing in the `0.63.x` tree:

* https://github.com/brave/brave-core/tree/0.63.x

**Comment by FrederickDavies** [comment]
Thank you!

                FD

**Comment by babbage1986** [comment]
There is a Chrome extension, Click&Clean, which does this job perfectly but it does not run on Brave (I think it does run on the Dev release).  Please can we activate this extension and solve the issue.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.63.20 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/54935051-eb1cd480-4ef5-11e9-9322-32f347a03ee5.png)

**Comment by babbage1986** [comment]
Thanks!  Click&Clean now works.  Better still the new settings illustrated above are the ideal solution.

**Comment by balupton** [comment]
What's the latest for this?

**Comment by babbage1986** [comment]
This is pretty much out of date.  I no longer use the Click&Clean extension, the settings in Brave do what I need, i.e., on exit delete all cookies except those I explicitly specify.  If Safari had this option I'd switch but it doesn't.

**Comment by FrederickDavies** [comment]
It seems the Android ticket has disappeared; anyone know if there is something like this (options to delete stuff on exit) on the Android version of Brave?

FD

**Comment by WilliamShockleyfake** [comment]
I want this feature on android brave as well

**Comment by kjozwiak** [comment]
> I want this feature on android brave as well

Added a +1 from you via https://github.com/brave/brave-browser/issues/7487 which is the issue tracking the work for implementing the above on `Android`.

**Comment by WilliamShockleyfake** [comment]
When will you guys add this feature on android. I am done waiting. Is it so hard to implement?

**Comment by anthonypkeane** [comment]
It is available on the Beta version now and we should have it on the main app in a few weeks @WilliamShockleyfake

**Comment by kencastell** [comment]
Wish we could select which data we wanted to erase on exit, and not just one option to "erase everything".

**Comment by AdamGeo** [comment]
Any idea when this is coming? There's been 2 updates recently but still no option for this, unless it's hidden somewhere
