### ISSUE TITLE
incorrect Twitch link in auto contribute and tips tables

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#4921]
## Description 
When visiting a twitch page (ex. twitch.tv/psherotv), the channel is correctly added to the AC table, however the link for the channel is incorrect. The link should be https://www.twitch.tv/psherotv/videos however it is actually https://www.twitch.tv/psherotv/videos/videos. If you continue to revisit the page (either in a new tab or refresh the existing tab) another `/videos` will be appended to the link, so it's pretty easy to end up with a link like https://www.twitch.tv/psherotv/videos/videos/videos/videos/videos.

This is occurring on release channel version 0.65.120 but not on 0.65.118 (currently released version).

## Steps to Reproduce

   1. Install 0.65.120 and enable Rewards.
   2. Visit a twitch channel such as https://www.twitch.tv/psherotv (I think this has to do with live streams, but should check VODs as well)
   3. Wait for channel to be added to AC table.
   5. On https://www.twitch.tv/psherotv/ refresh the page a couple of times. 

## Actual result:
View your AC table and hover over the entry for psherotv:
<img width="334" alt="Screen Shot 2019-06-14 at 11 14 44 AM" src="https://user-images.githubusercontent.com/28145373/59520171-63f95000-8e97-11e9-8db5-1f8d1b92843b.png">

## Expected result:
Link should not change when you refresh or revisit the page.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.65.120 Chromium: 75.0.3770.90 (Official Build) (64-bit)
-- | --
Revision | a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? 0.65.120 yes, but 0.65.118 no
- Can you reproduce this issue with the beta channel? 0.66.88 no
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
Reproduced on macOS and Win by @kjozwiak

**Comment by LaurenWags** [comment]
Issue did not reproduce with 0.66.88 on Beta:

Brave | 0.66.88 Chromium: 75.0.3770.87 (Official Build) beta(64-bit)
-- | --
Revision | 9dc58a2353af60ab2b48bab98a25bc43ed59085d-refs/branch-heads/3770@{#982}
OS | Mac OS X

**Comment by LaurenWags** [comment]
Looks like twitch doesn't redirect https://www.twitch.tv/psherotv/videos/videos, but will redirect something like https://www.twitch.tv/psherotv/videos/videos/videos/videos/videos/videos.

Link is still wrong, but it seems to have less of an impact.

**Comment by LaurenWags** [comment]
Same issue occurs in Tips table:
![Screen Shot 2019-06-14 at 11 59 21 AM](https://user-images.githubusercontent.com/28145373/59522127-e7b53b80-8e9b-11e9-927f-d2b4fbbe82ff.png)

**Comment by btlechowski** [comment]
Reproduced on Windows

Brave | 0.65.120 Chromium: 75.0.3770.90 (Official Build) (64-bit)
-- | --
Revision | a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}
OS | Windows 7 Service Pack 1 (Build 7601.24468)

**Comment by btlechowski** [comment]
It seems that `publisher_info_db` becomes corrupted with the wrong url.
![image](https://user-images.githubusercontent.com/34715963/59523130-cae72b00-8ed0-11e9-8a75-8d0a247f4dfa.png)

**Comment by LaurenWags** [comment]
Additional way to reproduce:
Watch a livestream. As the attention % on your AC table increases, another `/videos` will be added to the URL.

**Comment by GeetaSarvadnya** [comment]
The issue is Reproducible on.
Brave | 0.66.97 Chromium: 75.0.3770.100 (Official Build) beta (64-bit)
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Linux

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya this problem is on release (0.65) and all version except 68 where fix already landed

**Comment by srirambv** [comment]
Verification passed on

Brave | 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Linux

* Verified twitch link doesn't add extra `/videos` at the end of the link
* Verified db isn't corrupted with extra `/videos`
![image](https://user-images.githubusercontent.com/17010094/60311080-a2751d00-9923-11e9-8e2a-342a771e2979.png)
* Logged #5062
