### ISSUE TITLE
For Uphold wallet integration, we should protect against malicious extensions

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#4928]
## Description 
To prevent attacks by malicious extensions in our new sign in process for the integrated Uphold wallet, we should block access to our specific integrated wallet sign in URL to extensions.  This URL from Uphold is going to be specifically dedicated to the purpose of our wallet integration, so blocking that URL should have no effect on legitimate extensions.  This will include access through the WebRequest API and to sign in page generally (this includes scripting access to the page).

Misuse of the WebRequest API is something Chrome itself has to contend with - there are already blocks in place for the chrome web store. We should be able to look to https://cs.chromium.org/chromium/src/extensions/browser/api/web_request/web_request_permissions.cc?rcl=a367b3f7bd249d6e3feb13ee250b83baf821f3f3&l=238 as a way to implement blacklisting of the particular linking / redirect URL.

For blocking page level / scripting access we may be able to make use of the “withheld” permissions functionality that already exists for user granted host permissions for extensions. Currently you can set an extension to be granted permission to a particular site upon a user clicking the icon in the toolbar. It would be ideal if we can set an override so that all* extensions require on-click permissions for the uphold authorization pages, no matter their global permission setting.

This on-click permission facility seems like it would strike a good balance between us protecting the user and them being able to override for legitimate extensions. Since there is no associated request notification (the extension icon in the toolbar is simply shown within a differently colored circle) a user is unlikely to grant permissions by clicking the icon unless they have a legitimate need for that extension on this page.

*: A small whitelist for known password managers would likely be desirable

cc: @evq

**Comment by kjozwiak** [comment]
Labelling as `QA/Yes` as there's STR/Test Cases in https://github.com/brave/brave-core/pull/2946.

**Comment by GeetaSarvadnya** [comment]
@fmarier step 2 from the test plan https://github.com/brave/brave-core/pull/2946 is redirecting to the page below In Windows `0.69.128 Chromium: 77.0.3865.75`

![image](https://user-images.githubusercontent.com/38657976/65625631-d1b22d80-dfe9-11e9-8125-6b4618e280d7.png)

**Comment by fmarier** [comment]
I updated the test plan at https://github.com/brave/brave-core/pull/2946. The expected landing page is now `fmarier.org` due to a [recent change](https://github.com/fmarier/webrequest-demo/commit/0c236d044c2ff832e3afef7cce79ba4cebbe05b3) I made to my testing extension.

**Comment by GeetaSarvadnya** [comment]
Discussed with @fmarier and he has updated the test plan 
![image](https://user-images.githubusercontent.com/38657976/65633946-d03d3100-dffa-11e9-8af2-eb834f7c4c0c.png)

**Comment by kyeotic** [comment]
@jsecretan  This is really frustrating as it disables password managers. There is no indication in the UI that the disabling is intentional, and I just spend 20 minutes trying to figure out why Bitwarden wouldnt work on the uphold.com account creation page.

A way to re-enable extensions would be nice. In lieu of the ability to control what my browser does, an explanation about why would be appreciated.

**Comment by evq** [comment]
@kyeotic if clicking the extension and the `reload page to use this extension` prompt doesn't work then that is a bug. we explicitly hooked into the extension permission system to enable such a use case

@fmarier should we create a new issue or track here?

**Comment by kyeotic** [comment]
@evq Ah, good to know its a bug. I will open an issue for it.
