### ISSUE TITLE
Add "Customize" text to NTP dashboard settings icon to make it more discoverable

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#4930]
## Description
Currently, the icons in the bottom right of the Dashboard look like this:

![Screen Shot 2020-03-26 at 5 22 03 PM](https://user-images.githubusercontent.com/2388823/77708795-51fc2000-6f86-11ea-8f62-08996709817e.png)

Additionally we're heard feedback about them:

> ...look the same, but do very different things - one unintrusively pops up a toggle, the others load whole different pages. Can we make it intuitive that 3 of them are links to different pages, and 1 of them will lead to a menu? Perhaps by putting an arrow on that button.

## Designs
Text paired with images improves comprehension by up to 89%. Add the text "Customize" next to the dashboard settings icons to make the settings more discoverable:

![customize dashboard icon](https://user-images.githubusercontent.com/2388823/77708876-8ec81700-6f86-11ea-9f25-24e0d1fc68f0.jpg)

Update the title of the panel to say "Customize Dashboard" to make the connection with "Customize" button text.

![customize dashboard panel title](https://user-images.githubusercontent.com/2388823/77708920-ba4b0180-6f86-11ea-885c-0df5ba20765c.jpg)

**Comment by karenkliu** [comment]
@rossmoody  I remember a long time ago you wrote out a guide for how to get new icons into our Design System. I wasn't able to find this doc in our repos - what's the best process to get icon assets over to the dev?

**Comment by karenkliu** [comment]
Closing this issue as it's out of date - we have a new design for these icons on the NTP.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.8.71 Chromium: 81.0.4044.92 (Official Build) dev (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified for clean and upgrade profiles:

<img width="544" alt="Screen Shot 2020-04-10 at 10 11 59 AM" src="https://user-images.githubusercontent.com/28145373/78997081-ec766a80-7b13-11ea-9091-55dbcf4b60dc.png">
