### ISSUE TITLE
Twitter tips don't work for me

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#4933]
I verified my [Twitter username](https://twitter.com/fmarier) on Publishers:

![publishers-dashboard](https://user-images.githubusercontent.com/167821/59543738-aafc3b00-8ec1-11e9-994f-6805ac86fc2e.png)

but it's not showing up as verified on Nightly or release:

![profile-not-verified](https://user-images.githubusercontent.com/167821/59543734-a46dc380-8ec1-11e9-92eb-e28a8311f0a1.png)

I tried tipping myself 1 BAT but it ended up in the "to be tried again later" section:

> You’ve designated 2.0 BAT for creators who haven’t yet signed up to receive contributions. Your browser will keep trying to contribute until they verify, or until 90 days have passed.

## Reproduces how often: 
Everytime

## Brave version (brave://version info)
Any from the looks of it, but here's I've tried it in:

```
Brave | 0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)
Revision | 9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2-refs/branch-heads/3770@{#948}
OS | Linux
```

**Comment by NejcZdovc** [comment]
@fmarier what happens if you click on Refresh status?

**Comment by fmarier** [comment]
Interesting, it seems to be working in Nightly and Dev:
![Screenshot_from_2019-06-17_09-51-29](https://user-images.githubusercontent.com/167821/59622438-6a313b80-90e6-11e9-83b8-afeabeabc1d7.png)

but not on my local build:
![Screenshot_from_2019-06-17_09-32-07](https://user-images.githubusercontent.com/167821/59622459-73baa380-90e6-11e9-89be-ad710dd43906.png)

Sorry for the noise!

**Comment by NejcZdovc** [comment]
@fmarier on local build you are connecting to the staging where publisher is list is different, so you are just probably not on staging list
