### ISSUE TITLE
Designated balance call

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#4945]
Currently we are getting balance based on wallet properties that we are getting them from the server. With Gemini we need to handle multiple wallets meaning that we need to have designated call to get balance which will combine wallet properties with other wallet balances. In this phase we should just prepare this call with returning balance from wallet properties only. 

We need to remove balance and rates from wallet properties so that people would not use old API anymore.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/2715 (Staging env)
