### ISSUE TITLE
Webcompat issue on https://www.virginatlantic.com/us/en

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#4949]
## Description 

Trying to book a flight on https://www.virginatlantic.com/us/en
After searching for flights, the site loops back to the start and displays the below error message

## Steps to Reproduce

   1. Open https://www.virginatlantic.com/us/en and try to book a flight

## Actual result:

![Webcompat-2](https://user-images.githubusercontent.com/7606853/59624827-abc4e500-90ec-11e9-9f69-0303b8555624.png)

![Webcompat-1](https://user-images.githubusercontent.com/7606853/59624841-b54e4d00-90ec-11e9-966f-373037b88cec.png)

## Expected result:
User should be able to book a flight

## Reproduces how often: 

Easy on https://www.virginatlantic.com/us/en

## Brave version (brave://version info)

65 on Mac

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by anthonypkeane** [comment]
Can't reproduce on my work Mac with shields up

**Comment by ryanbr** [comment]
`https://www.virginatlantic.com/air-shopping/searchFlights.action?action=startOver&alerts=101767&cacheKey=31d2db8c-077f-4e7c-80c6-953f781d69e6`

Does this page work? (apart from no seats found)

**Comment by ryanbr** [comment]
The most questionable filter listed will be ensighten.com, which may be causing the issue

**Comment by ryanbr** [comment]
I re-tested this, seems to be okay? @anthonypkeane  Can you confirm?

https://secure.fanboy.co.nz/gif/virginatlantic.gif

Might've been an server-side issue.

**Comment by anthonypkeane** [comment]
confirmed working with shields up
