### ISSUE TITLE
`ebay.co.uk` site favicon is hidden by 3rd party trackers and ads

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#4956]
## Description 

`ebay.co.uk` site favicon is hidden by 3rd party trackers and ads. The issue is Reproducible in the following versions:

`0.65.118` - `Reproduced`
`0.64.77`  - `Reproduced`
`0.63.55`  - `Reproduced`

## Steps to Reproduce

   1. Clean profile 0.65.120
   2.  Open ebay.co.uk
   3. Open Shield 
   4. Verify that no favicon displayed in the URL bar and shield

**Note**: If I disable 3rd party ads and trackers in the shield, the favicon is displayed.

## Actual result:

no favicon displayed in the URL bar and shield.

![image](https://user-images.githubusercontent.com/38657976/59669432-d2137f00-91d7-11e9-95df-0f986a2f02b2.png)

## Expected result:
The favicon should be displayed in the URL bar and shield

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.65.120 Chromium: 75.0.3770.90 (Official Build) (64-bit)
-- | --
Revision | a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

The issue is reported by community user https://community.brave.com/t/ebay-co-uk-icon-classed-an-ad/66121
@brave/legacy_qa @bbondy

**Comment by tomlowenthal** [comment]
Looks like this is working as intended. The favicon is a cross-site request which is often used for tracking. Who knows, maybe it's even being used for tracking here.

**Comment by ryanbr** [comment]
Maybe fixed in future.  What I currently use (and affects these sites).

`/favicon.ico$image,third-party,domain=~bt.com|~ebay.com.au|~ebay.com|~go.com|~github.com|~stackexchange.com|~stackoverflow.com|~askubuntu.com|~reddit.com|~4chan.org|~twitter.com|~live.com|~espn.com
`

**Comment by ryanbr** [comment]
The issue in these cases isn't necessarily tracking, they use a various regional domains and cdn's with different domain suffiix's.

**Comment by kjozwiak** [comment]
@ryanbr mind creating an issue about implementing/looking into the above eventually? You can use this issue as a reference for an example of the problem happening.
