### ISSUE TITLE
Scrolling behaviour macOS Client in Java lists uncontrollable

### ISSUE THREAD

**Issue by Gitchiel** [brave/brave-browser#4960]
## Description 
Scrolling behaviour macOS Client (Brave v. 0.65.120) in lists in Java applications, like Vjoon K4, uncontrollable. It scrolls right down to the bottom / top of the list, almost impossible to scroll to a position midway. The application at hand here isn't publicly available, so I can't post a link; I suppose it's reproducable in all lists in Java apps though.
This is most obvious, when using an Apple magic mouse; when using a Logitech mouse, it's less noticeable (movement is slower), but still there (so scrolling doesn't stop, when the actual movement of the scrolling wheel stops, continues to scroll to the end of the list).

## Steps to Reproduce
Not relevant; see description above.

## Actual result:
Scrolling doesn't stop, when the actual movement of the scrolling wheel stops, continues to scroll to the end of the list. Scrolling is too fast, which makes it uncontrollable.

## Expected result:
Normal scrolling behaviour (so behaviour should be directly related to the movement of the scrolling wheel and well controllable of course).

## Reproduces how often: 
Always, it's unfortunately the default Brave-behaviour, since at least 1 year, probably 2 / more.

## Brave version (brave://version info)
0.65.120

## Version/Channel Information:
As mentioned it's unfortunately the default Brave-behaviour, since at least 1 year, probably 2 / more.

## Other Additional Information:
The issue is partly reproducible on the latest version of Chrome - so the fact, scrolling doesn't stop automatically is default for Chrome as well; but it's slower and easier to control (like in Firefox as well).

## Miscellaneous Information:
macOS 10.14.5 (18F132), fast / recent hardware.

**Comment by rebron** [comment]
@Gitchiel Without steps to reproduce and example applications to point to, we can't really address this issue.

**Comment by Gitchiel** [comment]
@rebron I understand - unfortunately I can't provide a public app or access for now; probably it's not concerning many users anyway, so I guess we can close this then.

**Comment by rebron** [comment]
@Gitchiel No worries. If there is a sample app you run across that you can share and it reproduces, please file this again.
