### ISSUE TITLE
Change date format for Contributions and Tips to match Ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#4975]
Change date format for Contributions and Tips to match Ads, i.e. from "05/01/2019" to "Jan 5" (format should be consistent for locale, i.e. "Jan 5" for United States. "5 Jan" for United Kingdom etc.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.106 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2772
* Verified on clean and upgrade profiles
* Verified formatting uses `Aug 5` for US and `5 Aug` for UK locales.
US: 
![Screen Shot 2019-07-10 at 1 43 53 PM](https://user-images.githubusercontent.com/28145373/60994031-a474ae00-a31d-11e9-8239-c4d6585ba842.png)

UK: 
![Screen Shot 2019-07-10 at 13 50 08](https://user-images.githubusercontent.com/28145373/60994049-ae96ac80-a31d-11e9-9bfb-3bf842dc0d13.png)
