### ISSUE TITLE
Open Ads in private windows

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#4980]
Open Ads in private windows

**Comment by tmancey** [comment]
https://github.com/brave/brave-core/pull/2355

**Comment by tomlowenthal** [comment]
Is this a change to the default behavior when you click an ad notification to open the landing in a new private window rather than in a regular window?

**Comment by tmancey** [comment]
@tomlowenthal I was testing this change, and if it worked I was then going to reach out to yourself and product to see if it is something we want implement

**Comment by tomlowenthal** [comment]
It's a pretty weird change. I'm not the PM for Rewards, so I'll let @mandar-brave chime in. But I'm not sure what the goal is here?

**Comment by bridiver** [comment]
I don't think it's a weird change, particularly for people who might unintentionally open the landing page. What would be the downside to it?

**Comment by bridiver** [comment]
even if I click intentionally, I might still want to keep that separated from the rest of my browsing

**Comment by tmancey** [comment]
I agree as we have had users complaining about random sites appearing in it history so private tabs would resolve this

**Comment by mandar-brave** [comment]
@tmancey @bridiver Not sure if i agree with this; the user has opted in to BR and is paid to receive ads. I think the default window behavior is what we owe back to the advertiser. Let's discuss this on channel as there are more opinions needed.
