### ISSUE TITLE
[info] What does brave use for its (html5) multimedia needs?

### ISSUE THREAD

**Issue by pitsi** [brave/brave-browser#4985]
## Description 
I just installed brave and, as I do on every chromium based browser, I first check its html5 support, especially for h264. H264 is a proprietary format, so most browsers on linux rely on the system's ffmpeg libraries (libavcodec, libavformat, libavutil) to play the relevant content.

I am also using another chromium based browser, which does not use the above libraries and instead has a libffmpeg.so for the job, which supports only open formats like webm etc.

I think it is this flag in chromium's code that decides whether the build will use the system's ffmpag libs (when set to true) or create a libffmpeg for the job (when set to false)

`USE_SYSTEM_FFMPEG=true or false`

## Steps to Reproduce
Install brave on a linux distro and visit html5test.com or youtube.com/html5.
On html5test.com, check the ticked boxes under multimedia, especially the one about h264.
On youtube.com/html5, check the 2 middle boxes about h264.

## Actual result:
Boxes are ticked, thus h264, although being a proprietary format, is supported!

## Expected result:
Same as the actual one!

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
Brave: 0.65.120 Chromium: 75.0.3770.90 (Official Build) (64-bit)
Revision: a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}
OS: Linux

## Version/Channel Information:
No idea about the other channels, but I assume it will be the same on beta and dev channels.

## Other Additional Information:
None 

## Miscellaneous Information:
I use debian testing x64 and I installed brave via the deb package provided on this github repo.
If brave does use the forementioned libraries, please consider adding them as dependencies on the deb package.

Thank you in advance :)

p.s. Where does brave get those beautiful wallpapers from, the ones for the new tab page ?

**Comment by srirambv** [comment]
cc: @simonhong @iefremov

**Comment by simonhong** [comment]
@pitsi There are two gn args for this - `proprietary_codecs` and `ffmpeg_branding`.
Brave sets `proprietary_codecs = true` and `ffmpeg_branding = "Chrome"`
See https://github.com/brave/brave-browser/blob/master/lib/config.js#L80

**Comment by pitsi** [comment]
Thank you :)
It seems I have to forget that (old?) flag and look for those new ones.
