### ISSUE TITLE
Ignore pinned tabs when closing with ⌘W

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#4988]
Feature/usability proposal. [Noticed a twitter comment](https://twitter.com/tolmasky/status/1140699118517358593?s) propose a warning on closing pinned tabs when using `CMD + W`. I think it would be a lot more useful to give users the option to have pinned tabs ignore `CMD + W` entirely. I miss pinned tabs almost every time I accidentally close them. 

![Persistent pinned tabs](https://user-images.githubusercontent.com/29072694/59792231-87057480-9288-11e9-89d5-801b914657b8.png)

**Comment by bsclifton** [comment]
Related https://github.com/brave/brave-browser/issues/4963

**Comment by rebron** [comment]
closing as dupe of #4963. I like the location of the setting. Maybe match the language of CMD + Q, something like Show warning before closing pinned tabs with CMD + Q

**Comment by rossmoody** [comment]
Is this the same behavior as #4963?

**Comment by rebron** [comment]
Sorry. Closing again. Let's solve it in #4963 and we can either go with an ignore pref as you're suggesting or warning pref.

**Comment by gustavotrott** [comment]
I created an extension as a workaround to prevent pinned tabs from being closed accidentally:

https://github.com/gustavotrott/brave-lock-pinned-tabs

Feel free to use if it can help you guys to tackle this issue!
