### ISSUE TITLE
User wallet: Ads Rewards paid directly to user wallets

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#4989]
Feature:
For the initial phase of user wallets, for browsers that will create/claim their own wallet and KYC (verify), we will be paying users for their ad rewards.

Pre-condition:
- User has verified (KYC'd) their wallet prior to end of the month
- User has any ads rewards payments

Expected behavior:
- User will automatically have balance updated (as in the server will create a transaction to send ads rewards to user wallet)
- The client will send a one time notification to the user that their earnings are in the user wallet (only close out action)

Exception use cases 
- If the same wallet is being used in multiple browsers, the user will be notified only once. However, the balance will be updated in all of the browsers

**Comment by mandar-brave** [comment]
@NejcZdovc @evq

**Comment by mandar-brave** [comment]
Notification text:
Your Ads rewards have been deposited to your wallet! 
Action: Close (X)

No UI besides the notification.

**Comment by NejcZdovc** [comment]
we deposit ad earnings to KYC wallet
