### ISSUE TITLE
Add copyright (c) symbol in About Brave

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#4990]
## Test plan
See https://github.com/brave/brave-core/pull/3881

## Description 
Change current: Copyright 2019 Brave Software Inc. All rights reserved.
To new: Copyright © 2019 Brave Software Inc. All rights reserved.

## Screenshot of Issue
![image](https://user-images.githubusercontent.com/5951041/59792614-67bb1700-9289-11e9-996d-9afc7c70a3d1.png)

**Comment by rebron** [comment]
cc: @bradleyrichter

**Comment by fmarier** [comment]
Same missing (C) in `brave://version`:
![Screenshot from 2019-10-23 14-19-54](https://user-images.githubusercontent.com/167821/67435073-3e482a00-f5a0-11e9-9864-2399fc9b3df4.png)

**Comment by petemill** [comment]
Can I ask why this is a requirement and worth diverting from Chromium on? Copyright law seems to say that you either need the word `Copyright` _or_ the copyright symbol `©`. The fix we have more than likely works, but there's always risk for symbols not working in certain scenarios and I'm not sure what the point is.

**Comment by bradleyrichter** [comment]
@petemill 

Chrome is the first app I have ever seen that doesn't include the © symbol. Normally apps include both, or only the © symbol.

But if adding in this common symbol to the string takes a lot more time that it took me to snap these screen shots, then don't bother. We can be unique like Chrome.  ;   )

![image](https://user-images.githubusercontent.com/13509546/68241616-d47a4800-ffc3-11e9-8e10-46eb2f71d08e.png)

**Comment by tomlowenthal** [comment]
I'm not a lawyer. Copyright law doesn't require any statement whatsoever: you don't need the word "Copyright", you don't need "©". Anything fixed in a tangible medium of expression is covered, and that includes all software. This is a cosmetic and æsthetic change, not a legal one.

**Comment by bradleyrichter** [comment]
Agree 100%. It's purely cosmetic. Like changing a blue button to orange. ;   )

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.38 Chromium: 78.0.3904.108 (Official Build) nightly (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3881

![image](https://user-images.githubusercontent.com/34715963/69808278-71a55680-11e7-11ea-9f49-999edb09c3aa.png)
