### ISSUE TITLE
add theme setting as an inline option to onboarding process

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#4992]
## Description 
Currently, when users get to the 'Choose your color theme' during our onboarding process, selecting Choose Your Theme sends them to brave://settings in a new tab. 

We should offer the same drop down list from settings (instead of the 'Choose your theme button'):
same as [OS]
Light 
Dark

and let the user make this choice inline during the onboarding process.

## Current Screen
<img width="646" alt="Screen Shot 2019-06-19 at 12 14 43 PM" src="https://user-images.githubusercontent.com/5951041/59793793-4871b900-928c-11e9-95b1-4b73f1aaf7e0.png">

**Comment by rebron** [comment]
cc: @rossmoody

**Comment by imptrx** [comment]
@rossmoody Do we have an updated visual spec on how the new screen should look?

**Comment by rossmoody** [comment]
Yeah, that would be amazing if we could have the theme change like it does in settings. The behavior would follow the same pattern as import and search. Disabled button to start, placeholder read "Select a theme" and then any available options, if an option is selected then the button auto proceeds to the next screen. 

![Welcome Light](https://user-images.githubusercontent.com/29072694/60067165-64c38a80-96be-11e9-9108-a32367f39942.jpg)

**Comment by bsclifton** [comment]
@imptrx I can help with the C++ side of this change 😄

**Comment by petemill** [comment]
@rebron @rossmoody when reviewing the PR I had some notes about the UX / spec for this and maybe simplifying. I'm semi-concerned about getting in the state where a percentage of users have unnecessarily overridden the 'Same as xyzOS' feature.

https://github.com/brave/brave-ui/pull/512#issuecomment-510268430

> One concern I have with this UX @rossmoody is that the user may feel that they *have to* pick a theme, and not know that 'Same as {macOS,Windows}' is the default. Therefore they may explicitly choose Light / Dark, and not know that they could have it follow the OS when they changed it.
>
>To be honest, I think having this choice on the welcome screen had high value, before we matched system theme, especially if it wasn't a drop-down but was a visual choice, but now it seems confusing perhaps.
>
>I don't know if there's a way we can offer this tri-state in a way that doesn't prompt users to override the default unnecessarily?
>
>![image](https://user-images.githubusercontent.com/741836/61011647-4e5d3600-a330-11e9-8c15-6fc47f20da25.png)
>
>
>**Edit:** Perhaps the choices in this welcome screen could be different to what's offered in the Settings page, in that we offer 2 choices: Dark or Light (ideally graphically). The choice is pre-selected to whatever the system theme is (or Light if not on an OS which supports dark mode). Only if the user changes to a theme that the OS is not currently on, do we save a setting as specificall 'Light' or 'Dark'. Otherwise, we leave it at 'System'. WDYT @rossmoody ?
