### ISSUE TITLE
Ad totals should update on month roll over without fetching latest balances from server

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#4994]
## Description 

Ad totals should update on month roll over without fetching latest balances from server

## Steps to Reproduce

   1. Navigate to 
   2. Wait for month to roll over 

## Actual result:

"Estimated pending rewards", "Next payment date" and "Ad notifications received this month" are not updated when month rolls over unless browser is restarted

## Expected result:
"Estimated pending rewards", "Next payment date" and "Ad notifications received this month" should be updated when month rolls over (if user is viewing Ad rewards panel then they must refresh the page)

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Linux

* Verified ads total update correctly when month roll over happens 
* Verified pending rewards balance updates correctly after month roll over happens
