### ISSUE TITLE
show background image should be default on

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#4995]
## Description 
With fix for https://github.com/brave/brave-browser/issues/4523, background images is defaulted off. 

Background images should be shown by default. 

It's a jarring change for existing users, who had background images previously.

Will need to test on upgrade that user preference is maintained. 
1) If user selects background images off, on upgrade, background images should still be off. 
2) If user selects background images on (default state but if users toggle back to background images on after previously selecting background images off), background images should still be on. 

## current screen for new users and existing user's updating
<img width="963" alt="Screen Shot 2019-06-19 at 10 17 41 PM" src="https://user-images.githubusercontent.com/5951041/59820343-1c802300-92e0-11e9-8e19-10ec2425c0d7.png">

## expected screen for new users and existing user's updating (but with their stats/top tiles info intact)
<img width="1367" alt="Screen Shot 2019-06-19 at 10 20 50 PM" src="https://user-images.githubusercontent.com/5951041/59822659-b6e06680-92e0-11e9-89fc-bcd23f37e969.png">

**Comment by srirambv** [comment]
The new setting to disable background image isn't intuitive and can be easily missed. @karenkliu how about adding a one time focus with tooltip is shown on opening a new tab after the fix goes into the release?

**Comment by karenkliu** [comment]
@srirambv Originally I wanted the panel to actually be open the first time a user landed on the page, but @bradleyrichter decided it's better to let user discovery take its course.

**Comment by GeetaSarvadnya** [comment]
Verification passed on 

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 10 OS Version 1803 (Build 17134.523)


- Verified the test plan from https://github.com/brave/brave-core/pull/2756
  - Verified that background images ON in NTP when the profile is upgraded from 0.67.115 to 0.68.113
![image](https://user-images.githubusercontent.com/38657976/62150649-33248b80-b31c-11e9-846e-7ee904925038.png)
  - Verified that background images ON in NTP by default in a new profile 0.68.113
