### ISSUE TITLE
[feature request ] Sync other data types rather than just bookmark

### ISSUE THREAD

**Issue by kid101** [brave/brave-browser#4997]
Right now Brave only seems to sync `bookmarks` not history,password,etc.
when is the support for other data type sync planned?
I plan to replace chrome in all my devices but can't do just yet.

**Comment by jfmherokiller** [comment]
giving it the ability to share tabs like in firefox would be amazing as well.

**Comment by bsclifton** [comment]
Related:
- Extension Syncing #4094
- Open tabs don't sync across devices. #4412

**Comment by vstokesjr** [comment]
BRAVE not being able to sync PASSWORDS is a show stopper. I use multiple devices and BRAVE missing this convenience is very inconvenient.This is where Google Chrome shines. Please consider prioritizing this Sync feature.

**Comment by JohnEricson** [comment]
I'd like to see this prioritized higher as well.
For now LastPass is a good alternative for syncing your passwords between computers and phone. It works across different browsers as well.

**Comment by entepe85** [comment]
I wouldn't [trust any browser with sensitive data](https://palant.de/2018/03/13/can-chrome-sync-or-firefox-sync-be-trusted-with-sensitive-data/) and rely on tools like 1Password or [Bitwarden](https://bitwarden.com/) instead to sync my passwords.

**Comment by JohnEricson** [comment]
@entepe85 Good point and article. Still I believe it's important for Brave to have feature parity with other dominant browsers such as Chrome and Firefox. So some kind of way for syncing passwords would be useful. Perhaps Brave could just recommend extensions to a couple of third party solutions if you decide in the Sync option that you would like to sync passwords as well? Or just have an explanatory description on why sync of passwords are not included and recommended best practice for the user to solve this?

**Comment by entepe85** [comment]
@JohnEricson I think the latter would be a pretty practical solution as it would save the devs the headache of ensuring password security.

**Comment by kid101** [comment]
I hope we really get this feature as an end-user I would love it.

**Comment by adultswimCA** [comment]
Me: Spends 10 minutes installing Brave to Mac Desktop and setting up sync.
Also Me: "#@%$" !!! Where the bloody hell is the button to sync tabs?!! :(

**Comment by twhitson** [comment]
This is seriously a dealbreaker for me when it comes to Brave. I desperately want to use Brave but the fact that it _only_ syncs bookmarks is a huge problem. As far as I'm concerned, this should be priority number 1. For this exact reason, I'm stuck with Firefox and having to deal with poor website support.

**Comment by gweilolaowai** [comment]
Cloud isn't free, the architecture overview is here:
https://www.chromium.org/developers/design-documents/sync
So effectively you're asking for a bunch of PaaS to be designed and stood up to handle this, with scaling, responsiveness, availability and security built-in. The fact that Brave already runs some of this for the sync currently is pretty good of them.
Agreed in principle it would be a great feature to have, but Google can do this as they own their own public Cloud.

**Comment by twhitson** [comment]
@gweilolaowai The fact that they already have this set up for bookmarks means adding history, extensions, etc. should be trivial. Storage space is pretty cheap now. Besides, isn't Brave's ad network supposed to pay for these things? Not trying to start an argument here, but it seems like you're missing the point of this issue. Sync tasks are already on the backlog, we just want them prioritized. It's something every major browser has and if Brave wants to be a serious player, this needs to be addressed.

**Comment by gweilolaowai** [comment]
@twhitson Not so sure it's trivial. Check the architecture of current bookmark sync:
https://github.com/brave/sync/wiki
This is very different from the use of XMPP to send messages for any and all changes, and I very much doubt the current sync will scale to meet demand of the additional functionality we all want, and be comparable to Chrome's instant design (obviously depending on how Brave gains adoption - I for one tell everyone I know about it and many have already switched).
Agreed to prioritise it, and it's a great feature, just conscious of the gain adoption vs. invest in functionality balance that they need to maintain

**Comment by PierBover** [comment]
I agree with @gweilolaowai it's not trivial but not being able to sync passwords and tabs is the biggest issue I face daily with Brave.

I agree with @twhitson it should be priority number 1 and it would certainly help to gain adoption.

**Comment by bsclifton** [comment]
We are working on a Sync v2 (maybe @jsecretan can share more info) - I'll assign the appropriate folks to reflect that work in progress 😄 

This effort underway should cover most (if not all) of the types that Google Account sync provides sync for. If you use Chrome and have sync setup, you can get a flavor for what those types are here:
https://chrome.google.com/sync

**Comment by jsecretan** [comment]
Yeah right now what we are trying to do is bring up most of what Chrome supports for desktop and Android.  For iOS, it will take some more extensive integration but we will start working on that right after the initial release.

**Comment by jsecretan** [comment]
Confirming that bookmarks, history, settings, tabs, passwords and more were implemented in sync v2.
