### ISSUE TITLE
Artifact on one of the image in the new tab page

### ISSUE THREAD

**Issue by AnthonyLenglet** [brave/brave-browser#4998]
## Description 
One of the image in the new tab page has a weird artifact(?) in it

## Steps to Reproduce
   1. Open a new tab

## Actual result:
![image](https://user-images.githubusercontent.com/36004334/59859765-ae8a3900-937d-11e9-8638-ca69b7703316.png)

Its ink! its dirt on my screen!
No!
It's an artifact that is in the original image!

https://unsplash.com/photos/prSogOoFmkw

## Expected result:
To not scare me for a second thinking this might be on my screen 😅

## Reproduces how often: 
Intermittent issue, depends on when the image is gotten

Not the biggest issue in the world, but damn if it doesn't trip me up everytime I see it 😄

**Comment by rebron** [comment]
cc: @rossmoody I can reproduce. It's the Napali coast image but looks like it's part of the original image as @AnthonyLenglet mentions.

**Comment by AnthonyLenglet** [comment]
Are the images shown in the new tabs page a curated list of images from unsplash ? if it is, another possible fix is to remove or replace the image from the list, no idea how this part is handled
