### ISSUE TITLE
Notify browser when user wallets are available

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#4999]
When the browser hits the version where user wallets are supported; here are the two use cases.

New user:
Once BR is launched and a new wallet is created, after an hour, the BAT logo should have notification ON 

Existing user (opted in to BR):
On upgrade, turn ON notification as soon as browser is up and running.

**Comment by mandar-brave** [comment]
![image](https://user-images.githubusercontent.com/35932307/59899543-f6bf5080-93a9-11e9-8b0f-d9f68d710194.png)

Edit: Accept token rewards without a CAPTCHA
Replace: Accept Ad rewards without a CAPTCHA

If/when the user comes back (or ignores), the user can come back in.

- no Uphold account state (default BR)
- Uphold + unverified (no KYC)
- Uphold  + verified (KYC)

Considering that Uphold will take some time to verify wallets we can expect that the user will start in Uphold + unverified state to start with.

![image](https://user-images.githubusercontent.com/35932307/59899658-587fba80-93aa-11e9-93d7-ae29cc8515f5.png)

@LaurenWags

**Comment by NejcZdovc** [comment]
closing as stale
