### ISSUE TITLE
User wallet: Notification reminders

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#5004]
First time an Uphold wallet shows as connected but unverified show the following notification (one time);
![image](https://user-images.githubusercontent.com/35932307/59900185-253e2b00-93ac-11e9-9866-b8445dfef038.png)

First time an Uphold wallets shows as verified, show the following notification (one time)

![image](https://user-images.githubusercontent.com/35932307/59900205-3edf7280-93ac-11e9-9a24-0d1d83cc6553.png)

First time an Uphold wallet is disconnected outside of the context of a transaction (one time);

![image](https://user-images.githubusercontent.com/35932307/59900239-5dde0480-93ac-11e9-841d-381cc52cfb6b.png)

**Comment by NejcZdovc** [comment]
@mandar-brave for the first one I don't see any point as soon as you are connected you are redirected to the second step

**Comment by LaurenWags** [comment]
Were all of these notifications implemented @NejcZdovc @mandar-brave ? The only one I've seen is the 'Your wallet is unreachable' one (third one) which I logged an issue for re: text updates https://github.com/brave/brave-browser/issues/5816. 

The test plan in https://github.com/brave/brave-core/pull/2696 makes no reference to these notifications. 

Please confirm if the first two notifications should be available/tested.

**Comment by LaurenWags** [comment]
Per discussion with @NejcZdovc first notification for Connected, Unverified was not implemented.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.121 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Per https://github.com/brave/brave-browser/issues/5004#issuecomment-526373425, the first notification for Connected, Unverified was not implemented.
* Following the steps from https://github.com/brave/brave-browser/issues/5004#issuecomment-526373425 did yield a notification, but it is missing text and generally not displaying properly. Logged #5874 
![Screen Shot 2019-09-03 at 3 48 51 PM](https://user-images.githubusercontent.com/28145373/64204636-369fbb00-ce64-11e9-92bb-99471ddeadb9.png)

* Verified Disconnected notification was observed, but had wording issues. Logged https://github.com/brave/brave-browser/issues/5816 for that.
![Screen Shot 2019-09-03 at 4 03 21 PM](https://user-images.githubusercontent.com/28145373/64204732-5fc04b80-ce64-11e9-809e-f771097b9738.png)
