### ISSUE TITLE
Handling Uphold wallet Connect/Disconnect

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#5005]
![image](https://user-images.githubusercontent.com/35932307/59900304-a8f81780-93ac-11e9-81c6-1c1b53197b7a.png)

@NejcZdovc this is optional for the first phase of user wallets.
Link 1: Just jump to the Uphold wallet
Link 2: Just remove the auth_token and put wallet to disconnect state (if there is an API to de-auth the token, make that call)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.121 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2696
* Verified that `Go to my Uphold account` opens Uphold dashboard in same tab
* Verified that `Disconnect from Brave Rewards` disconnects you. Green verified button changes to gray disconnected button. Clicking on it reauthorizes you.
![Screen Shot 2019-09-03 at 5 12 25 PM](https://user-images.githubusercontent.com/28145373/64209321-35738b80-ce6e-11e9-9a23-3e39942da749.png)
