### ISSUE TITLE
Brave Rewards nav-bar item is not translated

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#5006]
There is no dynamic translation string for the `Brave Rewards` item:

https://github.com/brave/brave-core/blob/master/ui/webui/resources/br_elements/br_toolbar/br_toolbar.html#L129

**Comment by LaurenWags** [comment]
@ryanml does this require manual QA? if so, could you add a test plan?

**Comment by btlechowski** [comment]
@ryanml Could add label QA/Yes or QA/No? Thanks!

**Comment by ryanml** [comment]
Sorry for the delay @LaurenWags @btlechowski , qa/no has been added. This string was just hardcoded. We don't attempt to translate the phrase `Brave Rewards` now, but perhaps that will change in the future.

**Comment by LaurenWags** [comment]
thanks @ryanml 👍
