### ISSUE TITLE
Make component updater compatible with NetworkService

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#5007]
(For more context see the parent issue https://github.com/brave/brave-browser/issues/2351)
(To run the browser with enabled NetworkService use `--enable-features=NetworkService`)

The component updater problem is rooted at `BraveSystemNetworkDelegate`. Here we do some hardcoded URL rewrites. It seems that `BraveSystemNetworkDelegate` is not going to be refactored in the parent issue and should be treated separately. Probably, the way to fix the problem is to make yet another custom `URLLoader` and/or `URLLoaderFactory`

**Comment by btlechowski** [comment]
Reproduced on 

Brave | 0.67.111 Chromium: 75.0.3770.100 (Official Build) beta (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

The tor binary is not downloaded with NetworkService flag enabled

**Comment by kjozwiak** [comment]
Reproduced on `macOS 10.14.5 x64` using the following build:

Brave | 0.67.115 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

STR:

* launch brave using `--enable-features=NetworkService`
* open a `Tor window` and you'll notice that the component isn't being downloaded

<img width="812" alt="Screen Shot 2019-07-24 at 4 45 15 PM" src="https://user-images.githubusercontent.com/2602313/61827400-7077ad80-ae32-11e9-81c9-2490709ddec5.png">
