### ISSUE TITLE
In windows 8.1 Brave ads notification popup has chrome favicon instead of brave

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5008]
## Description 

Brave ads notification popup has chrome favicon instead of brave

## Steps to Reproduce

   1. Clean profile 0.65.120
   2.  View ad ad
   3. Verify the ads notification popup

## Actual result:

Brave ads notification popup has chrome favicon instead of brave
![image (1)](https://user-images.githubusercontent.com/38657976/59918999-e65bb400-9443-11e9-9759-e65574398955.png)

## Expected result:
Ads notification should have Brave favicon

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.65.120 Chromium: 75.0.3770.90 (Official Build) (64-bit) 
-- | --
Revision | a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}
OS | Windows 8.1 (Build 9600.19377)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @tmancey

**Comment by LaurenWags** [comment]
I reproduced this when looking at some Ads stuff on Win 10 x64 today. Nightly versions 0.68.39 and 0.69.7.

**Comment by LaurenWags** [comment]
Verified passed with `macOS 10.13.6 x64` using

Brave | 0.69.119 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified Brave logo is displayed on both native and non-native notifications:
<img width="1392" alt="Screen Shot 2019-08-29 at 5 07 51 PM" src="https://user-images.githubusercontent.com/28145373/63976760-0cbf5080-ca80-11e9-929c-e692b8f0d5ad.png">
<img width="1394" alt="Screen Shot 2019-08-29 at 5 09 26 PM" src="https://user-images.githubusercontent.com/28145373/63976770-1052d780-ca80-11e9-8d2e-4f26af6905e6.png">
