### ISSUE TITLE
Progressive Apps Cannot be Pinned to Taskbar, Open Brave Window

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#5009]
## Description 
PWAs cannot be pinned to the taskbar. Doing so switches their icon back to the Brave icon, and opening them simply opens a default Brave window.

## Steps to Reproduce
1. Navigate to mobile.twitter.com
2. Click the ⋮ and select _Install Twitter_
3. Right-click resulting window icon in taskbar and select _Pin_

## Actual result:
Note that icon has changed to Brave icon. Clicking opens a Brave window.

## Expected result:
Icon should remain the Twitter icon. Clicking should open a Twitter window.

## Reproduces how often: 
Easily, always.

## Brave version (brave://version info)
0.65.121

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel?

On nightly, you can pin the PWA and the icon doesn't change. However, clicking the PWA icon will call out to chrome_proxy.exe, which results in a new Chrome window rather than a Brave window, or the actual PWA window.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  No

## Miscellaneous Information:
You may need to lower shields for the _Install Twitter_ option to present itself.

**Comment by jonathansampson** [comment]
nwjs appears to have had a similar issue (now patched): https://github.com/nwjs/chromium.src/commit/de885926da88265af6d9bad51f5e5dbfc03e42f8

**Comment by rebron** [comment]
@jonathansampson We fixed a bunch of PWA issues in 66.x. Can you take a look and see if this is still an issue for you?

**Comment by jonathansampson** [comment]
@rebron This issue still reproduces in 0.66.99. Repro can be a little tough, the option to _Install Twitter_ doesn't always appear. I had to refresh a couple times on the new Twitter UI to get the option.

**Comment by veyselerden** [comment]
It still reproduces in v1.5.123. On Linux, icons and pinning is OK but it opens a new Brave window instead of opening the app itself. You can only launch the PWA by going through `brave://apps` and click the icon there.

**Comment by MikeBishop** [comment]
Interestingly, Twitter now seems to work properly, but doing the same thing with messages.google.com launches... _Chrome_.  It can be launched via brave://apps, but something is remembering that the site used to be installed with Chrome.  (It no longer is.)

**Comment by bsclifton** [comment]
Definitely working now (tested on Windows with 1.15.20) 😄
