### ISSUE TITLE
Alarms in Tradingview doesn't load or work at all

### ISSUE THREAD

**Issue by sajklan** [brave/brave-browser#5010]
Since I changed to Brave from Chrome, the alarm function in Tradingview has stopped working, it won't load the list, let me edit or delete any on the alarms, so this causes old alarms to go of now and then. I have to start Chrome to do this part and I wanted to drop Chrome once and for all.
Printscreens 
http://prntscr.com/o4ug3u
http://prntscr.com/o4ugq2

## Steps to Reproduce

   1. Set an alarm, edit one, try go to the alarm list, basically everything that has to do with the alarms.
   2. Get respons from tradingview:  "connection issue"
   3. 

## Actual result:
http://prntscr.com/o4ug3u
http://prntscr.com/o4ugq2

## Expected result:
That the list is there, alarms are set etc.

## Reproduces how often: 
Been like this permanently since I changed to Brave from Chrome, works fine in Chrome.

## Brave version (brave://version info)

Brave | 0.65.120 Chromium: 75.0.3770.90 (Officiell version) (64 bitar)
-- | --
Version | a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}
OS | Mac OS X
JavaScript | V8 7.5.288.23
Flash | 32.0.0.192 /Library/Internet Plug-Ins/PepperFlashPlayer/PepperFlashPlayer.plugin

Running on Mojave OSX

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No, have all shields off and it still does the same
- Does the issue resolve itself when disabling Brave Rewards?
No still the same issue, no change
- Is the issue reproducible on the latest version of Chrome? 
Works fine in Chrome

**Comment by ryanbr** [comment]
I had no issues creating an alert; https://secure.fanboy.co.nz/gif/tradingview.gif

**Comment by rebron** [comment]
@ryanbr What version are you using? Are you using Nightly?

**Comment by ryanbr** [comment]
I was testing on Brave stable

**Comment by ryanbr** [comment]
@sajklan  Is this working in the current Brave release?

**Comment by ryanbr** [comment]
Wasn't able to replicate this, no further comments. Re-open this @sajklan if it's still causing issue.
