### ISSUE TITLE
Ads Rewards should be refreshed after redeeming tokens

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#5011]
## Description 

Ads Rewards should be refreshed after redeeming tokens

## Steps to Reproduce

1. Clean profile on 0.68.71. Launch with parameters `--enable-logging=stderr --vmodule=brave_ads=3 --brave-ads-staging --rewards=staging=true` to view logs.
2. Enable Reward with today's date.
3. Viewed a page, waited, received an Ad. Ads panel shows expected info: 0.05 BAT pending, payment date of Jul 5, 1 ad notification viewed.
4. Closed Brave.
5. Changed system date to Jul 1.
6. Relaunched Brave.
7. Viewed Ads panel.
8. Shows 0.05 BAT pending (expected). Payment date of Aug 5 (presumed expected since I jumped forward to July 1). Ad notifications received this month still says 1 (should be 0 - see #5012). Refreshing the page, close and reopen rewards page, nothing changes the counter.
9. Watch logs to see when token is redeemed for ad viewed in previous month.
10. Once token is redeemed, try refreshing page and close/reopen. No change.
11. Close and relaunch Brave.
12. Estimated Pending Rewards = 0.05 BAT, Next Payment Date = Jul 5, Ad notifications received this month = 0.

## Actual result:

Ads Rewards were not updated to reflect redeemed tokens, i.e. Next payment date

## Expected result:
Ads Rewards should be updated to reflect redeemed tokens

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

0.68.69

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Workaround is to restart the browser or claim an ad grant

**Comment by LaurenWags** [comment]
When checking this issue we also need to test case described in https://github.com/brave/brave-browser/issues/5390

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.67.119 Chromium: 76.0.3809.72 (Official Build) (64-bit)
-- | --
Revision | 5a04c669126f657f98824b436555cae41b8f4146-refs/branch-heads/3809@{#897}
OS | Windows 10 OS Version 1803 (Build 17134.523)
