### ISSUE TITLE
Ad notifications received should only include unredeemed tokens for the current month

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#5012]
## Description 

Ad notifications received should only include unredeemed tokens for the current month

## Steps to Reproduce

   1. View an Ad
   2. Change system clock to following month

## Actual result:

Ad notifications received still shows 1

## Expected result:
Ad notifications received should show 0 as the Ad was viewed in the previous month

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

0.68.69

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Linux
