### ISSUE TITLE
Multiple ad grants cause display issue in wallet summary

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5013]
## Description 
If you have multiple Ad grants, the first one claimed appears to double in the wallet summary display, but the correct amount is reflected on the 'it's your lucky day!' banner and wallet balance. 

## Steps to Reproduce

   1. Clean profile (used staging).
   2. Restore a wallet with two Ad grants (will need to get this from ledger team). It's helpful if this wallet has 0 balance to start, makes the issue easier to see.
   3. Claim first Ad grant.

## Actual result:
"It's your lucky day!" banner says one value, summary says another. Close this. Wallet balance reflects banner value, but summary still says incorrect (doubled) value. See below, banner says 3.5, but below that you can see Ad earnings show 7.0 BAT.  
![Screen Shot 2019-06-21 at 5 26 54 PM](https://user-images.githubusercontent.com/28145373/59953136-b06efd80-944c-11e9-8cbb-705b10fc8480.png)

Close banner, you will see wallet balance reflects 3.5. 
![Screen Shot 2019-06-21 at 5 27 44 PM](https://user-images.githubusercontent.com/28145373/59953165-cd0b3580-944c-11e9-8e40-e55c4cbb7f66.png)

## Expected result:
'Earnings from Ads' in summary should be accurate and the same as wallet balance in this case.

## Reproduces how often: 
easy, but only if you have two ad grants.

## Brave version (brave://version info)
0.65.121 (Release channel) and 0.68.71 (Nightly)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? unsure but probably yes
- Can you reproduce this issue with the dev channel? unsure but probably yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
Found on Nightly and reproduced on Release channel.

**Comment by tmancey** [comment]
@LaurenWags Can we please retest as I cannot reproduce on 1.10, thanks

**Comment by tmancey** [comment]
I can now reproduce so have reopened the ticket

**Comment by NejcZdovc** [comment]
@tmancey can you please send me steps or profile as you were able to reproduce. Thank you

**Comment by tmancey** [comment]
@NejcZdovc I followed steps from @LaurenWags

**Comment by Miyayes** [comment]
I think this is resolved, especially with new Rewards panel. Can refile in future.
