### ISSUE TITLE
Widget menu for new tabs page elements

### ISSUE THREAD

**Issue by imptrx** [brave/brave-browser#5015]
## Description 

Related issue: https://github.com/brave/brave-browser/issues/4510
Currently showing and hiding widgets in NTP is available soon via the Dashboard Settings Menu. We should also be able to control these options via opening a "widget" menu that shows up via menu button or right clicking the widget.

Hover or tab over the  Brave Stats widget to highlight it and display an icon representing menu options:

![r1 toggle widgets - stats 1](https://user-images.githubusercontent.com/2388823/58129372-7224bb00-7bce-11e9-851b-58bcf9d1a68d.png)

Clicking/selecting the icon shows a menu with widget options:

![r1 toggle widgets - stats 2](https://user-images.githubusercontent.com/2388823/58129382-781a9c00-7bce-11e9-8d40-62b5fa268e99.png)

Hover or tab over the Clock widget to highlight it and display an icon representing menu options:

![r1 toggle widgets - clock 1](https://user-images.githubusercontent.com/2388823/58129486-af894880-7bce-11e9-9801-fe4b1910eeed.png)

Clicking/selecting the icon shows a menu with widget options:

![r1 toggle widgets - clock 2](https://user-images.githubusercontent.com/2388823/58129501-b31ccf80-7bce-11e9-8ec5-a5babfc3cb77.png)

Hover or tab over the Top Sites widget to highlight it and display an icon representing menu options:

![r1 toggle widgets - top sites 1](https://user-images.githubusercontent.com/2388823/58129511-b912b080-7bce-11e9-96c2-b61b5dcaacdf.png)

Clicking/selecting the icon shows a menu with widget options:

![r1 toggle widgets - top sites 2](https://user-images.githubusercontent.com/2388823/58129516-bd3ece00-7bce-11e9-8d7f-d5ea639a93be.png)

**Comment by yodaross** [comment]
Unsubscribe

**Comment by imptrx** [comment]
Test Plan:
**Widget Behaviour** 
- Hover over widgets should produce a hover effect and an icon beside it
- Clicking on the icon for each widget should open up a menu (clicking again will toggle)
- If menu is open, moving the cursor away from the widget wouldn’t remove the hover effect
- If menu is closed, moving the cursor away from the widget removed hover effects
- If menu is open clicking outside the menu will close the menu and disable toggle
- Clicking remove from each widget menu will remove the widget from the page
- When re-enabling the widget(via the customization menu at the bottom right/left side of page) - widget menu should be closed, no hover effect

**Icon placement:**
- On large screen, widget icon will appear towards the center of the page (away from edge)
- On smaller screens, widget icon will appear towards the right (or left depending on locale)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.70.97 Chromium: 77.0.3865.65 (Official Build) beta (64-bit)
-- | --
Revision | 87a331a3169cab563505fb44011058b904011ba1-refs/branch-heads/3865@{#726}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan mentioned in https://github.com/brave/brave-browser/issues/5015#issuecomment-520612267
- Logged #6084 #6085 #6086

**Comment by btlechowski** [comment]
@kjozwiak This feature is not implemented in 0.69.128. It works well in 0.70.100.

**Comment by bsclifton** [comment]
Moving milestones to 0.70.x
cc: @cezaraugusto

**Comment by kjozwiak** [comment]
@bsclifton thanks for moving, was this supposed to be in `0.69.x`? Just want to make sure we haven't missed anything important when we did the merge 👍 Maybe @cezaraugusto can comment with more context.

**Comment by rebron** [comment]
@kjozwiak This issue didn't need to go into 0.69.x. Incremental fixes for new tab page are riding the trains so this fix in 0.70.x.

**Comment by LaurenWags** [comment]
Verified passed with 

Brave | 0.70.110 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from https://github.com/brave/brave-browser/issues/5015#issuecomment-520612267
<img width="1195" alt="Screen Shot 2019-10-08 at 1 43 14 PM" src="https://user-images.githubusercontent.com/28145373/66419631-6e090680-e9d2-11e9-8eb5-88d8916f9db3.png">
<img width="1189" alt="Screen Shot 2019-10-08 at 1 43 23 PM" src="https://user-images.githubusercontent.com/28145373/66419646-72352400-e9d2-11e9-9fd6-ec3b82af724f.png">
<img width="1193" alt="Screen Shot 2019-10-08 at 1 43 33 PM" src="https://user-images.githubusercontent.com/28145373/66419655-74977e00-e9d2-11e9-8adc-489d7bc15a91.png">

* Per test plan, for small screens, L->R languages (ex. English) menu widget is on Right and for R->L languages (ex. Hebrew) menu widget is on Left.
<img width="902" alt="Screen Shot 2019-10-08 at 1 44 35 PM" src="https://user-images.githubusercontent.com/28145373/66419796-b7f1ec80-e9d2-11e9-8194-f6728653955e.png">
<img width="901" alt="Screen Shot 2019-10-08 at 1 48 01 אח׳" src="https://user-images.githubusercontent.com/28145373/66419800-b9bbb000-e9d2-11e9-95d4-5526459b554b.png">
