### ISSUE TITLE
Awaiting for my Brave Rewards

### ISSUE THREAD

**Issue by Victorio115** [brave/brave-browser#5016]
## Description 

I'm still waiting for my Brave Ads.

## Steps to Reproduce

   1.  Open Brave Browser.
   2. Write `chrome://rewards/` on Address Bar.

## Actual result:

![image](https://user-images.githubusercontent.com/50971728/59957021-69cbd400-9449-11e9-9aab-2efedadd2b46.png)

## Expected result:
![image](https://user-images.githubusercontent.com/50971728/59957044-8e27b080-9449-11e9-97f4-ebc44b557d39.png)
Screenshot taken from [a StartPage Image Search](https://www.startpage.com/do/search?lang=en&language=espanol&query=Brave+Rewards&cat=pics&t=nite).  
[Exact Link](https://browse.startpage.com/do/show_picture.pl?l=english&rais=1&oiu=https%3A%2F%2Fwhatisbat.com%2Fwp-content%2Fuploads%2F2019%2F04%2Fenable_ads_06.png&sp=3c87a0b3110f6ed4dabdad13fe405619&t=nite)

## Reproduces how often: 

Depends the region.

## Brave version (brave://version info)

Brave | 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X
JavaScript | V8 7.5.288.23
Flash | 32.0.0.207 /Library/Internet Plug-Ins/PepperFlashPlayer/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser -psn_0_61455 --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=NewExtensionUpdaterService,DesktopPWAWindowing --disable-features=DefaultEnableOopRasterization,AudioServiceOutOfProcess,NetworkService,AutofillSaveCardSignInAfterLocalSave,UnifiedConsent,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,TranslateUI --flag-switches-begin --flag-switches-end --restore-last-session
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/VictorioAcosta/Library/Application Support/BraveSoftware/Brave-Browser/Default
Variations | 5040e8a-5040e8ac134752e-f685ead32c707b42-dcf7018a411b6d4e-3f4a17dfd01ab0d3-60c33fc08927cedd-3f4a17df16e0dd70-3f4a17df414bf2d2-3f4a17df551157b-3f4a17dff88a4127-2874767e4b8c3f4-3f4a17dfb7e2524c-c92d551c411c711e-3f4a17df6c18ba9d-3f4a17df8f029c91-3f4a17df8982496f-3f4a17df61832c80-3f4a17dfcc20827f-77c422c591560a-29acad49853922b-3f4a17df776de70c-e0278d3ded9149a9-3f4a17df34d450b1-3f4a17dfc70841c8-a256700714bdbe54-e8c7a65bd8343fa3-3f4a17dfb517d646-3f4a17df8ee5ed19-c3125ea274658432-fa79b94c4f9b5d89-3f4a17dfaacdc39d-80f9a33ec36cdb78-3f4a17df652e14d1-f4950e995274eb09-3f4a17dfd6d4ee9a-3f4a17df2729b628-3f4a17df44827ee5-3f4a17df332a4d9b-8e8e4a2b6a116980-3f4a17df3f79ac13-3d47f4f48f1e27f-3f4a17df6cb3969e-3f4a17df40de7b13-1aa41b589b4c4257-3f4a17df43f62d3b-3f4a17df9e5c75f1-30e1b12b2594bdf4-3f4a17df6fa07eb4-7282ca762981bcb4-3f4a17df5139837c-3f4a17df4934552d-3f4a17df7f8176d9-3f4a17df6c66bd8d-b204717823a898eb-fc93cf742b08b14-3f4a17df7a5ba892-3f4a17dfd1cd70a5-3f4a17df4ea303a6-3f4a17dfac8d4708-5460eccbb19465ab-b19465ab6e6e0c7e-3f17a7d895876445-2b71ffe42b33233e-881ca6c94da5ae82-3f4a17df56302f8c-2f882e70fd56acdf-3f4a17dfed846e24-3f4a17dfb2612322-8a9180b2ad6d27cc-85d38e8dcec9a952-9a6c5085f56e0452-3f4a17df8576baf1-3f4a17df2e7f6029-88947c67d00fcbde-3f4a17dfd840bbac-3f4a17df930e30f5-3f4a17df732f0134-3f4a17df9a2f4e5b-9ded16b91354da85-522c33b8494d8760-3f4a17dff9e5da91-508355f5b1ceb06f-6b7b34db0ea13bc-3f4a17df47a2af3f-3f4a17df94e68624-803f8fc4cc73f8a1-3f4a17dfb4e8892d-a2d707c67e91b7bd-c6da37cb6204e469-3f4a17df41ddf744-c78ce173

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes, I do.
- Can you reproduce this issue with the beta channel? I haven't used beta channel.
- Can you reproduce this issue with the dev channel? I haven't used dev channel.
- Can you reproduce this issue with the nightly channel? i haven't nightly channel.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Brave Shields are irrelevant for this issue.
- Does the issue resolve itself when disabling Brave Rewards? No, It doesn't.
- Is the issue reproducible on the latest version of Chrome? Yes, I'm using the lastest version of Chrome.

## Miscellaneous Information:

I'm Brave Browser on Mexico, from [a MacBook Air](https://support.apple.com/kb/SP700?locale=en_US&viewlocale=en_US) with MacOS Mojave.

**Comment by srirambv** [comment]
>I'm Brave Browser on Mexico, 

Ads are currently not available in your region.

**Comment by Victorio115** [comment]
> > I'm Brave Browser on Mexico,
> 
> Ads are currently not available in your region.

![image](https://user-images.githubusercontent.com/50971728/60160884-32dc2200-97ab-11e9-93fb-47c1e95aca99.png)
This Windows Computer, is located on Mexico too, and It seems Brave Rewards.  
Does it depend of Operative System?
  
Brave://Version  
  
Brave | 0.65.120 Chromium: 75.0.3770.90 (Official Build) (64-bit)
-- | --
Revision | a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}
OS | Windows 10 OS Version 1803 (Build 17134.829)
JavaScript | V8 7.5.288.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=NewExtensionUpdaterService,DesktopPWAWindowing --disable-features=AutofillServerCommunication,AudioServiceOutOfProcess,DefaultEnableOopRasterization,UnifiedConsent,AutofillSaveCardSignInAfterLocalSave,NetworkService,LookalikeUrlNavigationSuggestionsUI,TranslateUI --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\victo\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | 5040e8a-5040e8ac134752e-f685ead32c707b42-dcf7018a411b6d4e-3f4a17dfd01ab0d3-60c33fc08927cedd-3f4a17df16e0dd70-3f4a17df414bf2d2-3f4a17df4ca682fe-3f4a17df551157b-3f4a17dff88a4127-2874767e4b8c3f4-3f4a17dfb7e2524c-c92d551c411c711e-3f4a17df8f029c91-3f4a17df61832c80-3f4a17dfcc20827f-77c422c591560a-29acad42db4845-ace4e13874785582-3f4a17df9853922b-3f4a17df7f1537dd-2589618c3c6ddce9-74eaaf0941e765a5-3f4a17dfab3d6cfd-3f4a17df776de70c-e0278d3ded9149a9-3f4a17dfa5cb8590-3f4a17df34d450b1-3f4a17df6c6c4f61-3f4a17df76b48ab8-d4bd105cc70841c8-a256700714bdbe54-e8c7a65bd8343fa3-3f4a17dfb517d646-3f4a17df8ee5ed19-c3125ea274658432-fa79b94cc36cdb78-3f4a17df652e14d1-f4950e99591576c8-3f4a17df5274eb09-3f4a17dfd6d4ee9a-3f4a17df2729b628-3f4a17df44827ee5-3f4a17df8ca44045-3f4a17df3f79ac13-3d47f4f48f1e27f-3f4a17dfde47491b-3f4a17df1beda558-1beda55840de7b13-1aa41b589b4c4257-3f4a17df8fa604e0-ace4e13843f62d3b-3f4a17df9e5c75f1-30e1b12b2594bdf4-3f4a17df6fa07eb4-7282ca762981bcb4-3f4a17df5139837c-3f4a17df4934552d-3f4a17df7f8176d9-3f4a17df73a8d7f1-1b1a7908f7217a71-b204717823a898eb-fc93cf747a5ba892-3f4a17dfd1cd70a5-3f4a17df4ea303a6-3f4a17dfac8d4708-5460eccbb19465ab-b19465abe5373d71-e23a25d96e6e0c7e-3f17a7d895876445-2b71ffe42b33233e-881ca6c94da5ae82-3f4a17df56302f8c-2f882e70e3981599-8feffd69fd56acdf-3f4a17dfed846e24-3f4a17dfb2612322-8a9180b2cac0a91c-3f4a17dfad6d27cc-85d38e8dcec9a952-9a6c5085f56e0452-3f4a17df8576baf1-3f4a17dff3ea30a0-3f4a17df2e7f6029-88947c67d00fcbde-3f4a17dfd840bbac-3f4a17df930e30f5-3f4a17df732f0134-3f4a17df9a2f4e5b-9ded16b91354da85-f1a864dc6844d8aa-669a04e0494d8760-3f4a17dff9e5da91-508355f5b1ceb06f-6b7b34d3a4029d-d7f231f3b0ea13bc-3f4a17df47a2af3f-3f4a17df94e68624-803f8fc4cc73f8a1-3f4a17dfb4e8892d-a2d707c67e91b7bd-c6da37cb6204e469-3f4a17dfbb61e032-bb61e03241ddf744-c78ce173
