### ISSUE TITLE
Get a bottom navigation bar

### ISSUE THREAD

**Issue by antoine373** [brave/brave-browser#5017]
## Description 
Add a third possibility to deal with navigation bar position

## Actual result:
Today there are two ways to modify display :
- Only the navigation bar at the top with brave rewards icon (or not), tab manager and 3 dots menu
- Add a tool bar at the bottom with homepage , bookmarks, tab manager and 3 dots menu. In this configuration navigation bar remains at top with more space. 

## Expected result:
It could be nice to get a third choice : 
- Only the navigation bar (+ tab manager and 3dots menu) at the BOTTOM!! 

Reason why it should be an improvement : 
- Only the navigation bar leave more space to the page
- When we hold a smartphone in our hand it's easier to access the bottom of the screen. 

## modification needed : 
This improvements needs to deal with keyboard display : 
- When typing in search bar no problem 
- When typing in web pages contents, the navigation should dissappear.

**Comment by bbondy** [comment]
I believe this is implemented, so closing.
