### ISSUE TITLE
Full screen for website parameters

### ISSUE THREAD

**Issue by antoine373** [brave/brave-browser#5018]
**DESCRIPTION**
Add a new parameter for website : Fullscreen. 

**WHY?** 
Because it could be usefull when we use a website from a desktop shortcut. In this use case, we want to use a website like an app and get the full screen. 

**WHEN?** 
Activate Fullscreen only when we come from a desktop shortcut.

**Comment by srirambv** [comment]
Can you please add more context to the issue? Please stick to the issue template when adding details. Makes it easier for us to understand the issue better.

**Comment by bsclifton** [comment]
Closing as there isn't enough info to be actionable
