### ISSUE TITLE
eBay sell page broken by shields

### ISSUE THREAD

**Issue by ChildishGiant** [brave/brave-browser#5019]
## Description 
Cannot make an eBay listing with shields up

## Steps to Reproduce

   1.  Go to https://www.ebay.co.uk/sl/sell
   2. Type something in.
   3. Nothing will happen unless shields are down.

## Actual result:
Both hitting Go and the dropdown suggestions don't work.
Sheilds up:
![image](https://user-images.githubusercontent.com/13716824/59964505-a3f4ae80-94f9-11e9-82a7-d6dfd5409c0c.png)

## Expected result:
Shields down:
![image](https://user-images.githubusercontent.com/13716824/59964502-9b03dd00-94f9-11e9-92a3-e55fac45d200.png)

## Reproduces how often: 

100%

## Brave version (brave://version info)
0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit)
Windows 10 OS Version 1803 (Build 17134.472)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

**Comment by ryanbr** [comment]
@ChildishGiant Does this work now?

**Comment by ChildishGiant** [comment]
Still reproduced on Nightly but I'm not sure if this push is in the latest nightly build

**Comment by rebron** [comment]
@ryanbr Can you take another look?

**Comment by ryanbr** [comment]
Just tested in Brave stable and Nightly, seems to work here.

**Comment by ChildishGiant** [comment]
I'm guessing nightly doesn't auto update then? It does seem that my nightly last updated today. On my nightly build, I'm still having the same issue. 
![image](https://user-images.githubusercontent.com/13716824/60760214-865f3300-a029-11e9-86c8-bc408b9252dd.png)

**Comment by ryanbr** [comment]
Okay, re-tested in Nightly. 

https://secure.fanboy.co.nz/gif/ebay2.gif

**Comment by ChildishGiant** [comment]
Ah yea, it's working for me now. Seems fixed
