### ISSUE TITLE
Update widevine version to 4.10.1440.18 on linux

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#5022]
4.10.1440.18 is ready to use.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Ubuntu 18.04 LTS

Talked to @simonhong and the test plan in https://github.com/brave/brave-browser/pull/5023 is only valid for debug build.

We agreed to check if widevine is actually downloaded and placed in the proper folder. Which it did.
