### ISSUE TITLE
Gh

### ISSUE THREAD

**Issue by Zovaxis** [brave/brave-browser#5024]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
Closing as there is no actual info here. Please re-open with details if there's something we can help with 😄

**Comment by Zovaxis** [comment]
Hy

**Comment by Zovaxis** [comment]
Ggt
