### ISSUE TITLE
Brave Ads seem to display on touch of mouse post long idle

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#5029]
Issue: Some users are noticing that after a large idle time (10 minutes or thereabouts), when they click a mouse an Ad notice drops in. 

Specification/Expectation: Original specification was suggesting we display Ads only when user is active -> goes to idle for 15 seconds -> ad is displayed if app was in foreground. This is derived from user is active on Brave but has ended an activity to capture notice at a precise time.

Fix: We only display ads per specification at the moment. 

@tmancey @jsecretan 

Reference to customer tweet (issue raised):
https://twitter.com/benespen/status/1142512674728579072?s=12

**Comment by mandar-brave** [comment]
@tmancey please make this 2 minutes.
so ad delivers between 15 s - 120 s; if not clock resets.

**Comment by tmancey** [comment]
#5090

**Comment by tmancey** [comment]
@jsecretan Assigning until a decision has been made whether we close or merge, thanks

**Comment by tmancey** [comment]
@jsecretan Is this change still required? Thanks

**Comment by tmancey** [comment]
Closing issue as won't fix
