### ISSUE TITLE
Shields should not be clickable on about pages (Follow up to #169)

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#503]
## Description 

Shields should not be clickable on about pages (Follow up to #169)

## Steps to Reproduce

   1. Install build
   2. Open settings page
   3. Shields looks disabled but still clickable

## Actual result:
Shields should not be clickable on about pages 

## Expected result:
Should not be clickable. Should have same behaviour as browser-laptop

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Packaged build

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
#169

**Comment by srirambv** [comment]
Not sure how it is possible since shields is an extension and all extensions are clickable and opens extension page on about pages as well.

**Comment by GeetaSarvadnya** [comment]
Verification PASS on:

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows
