### ISSUE TITLE
specify pinsets on a per-domain basis

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#5031]
Right now for cert pinning, we pin all the hosts in the list to the entire pinset. We should split pinsets on a per-domain basis to make pinning more strict.

**Comment by fmarier** [comment]
I missed this issue when I was working on updating the pins for Brave.

We can definitely do this by creating different pinsets, but this will be a lot harder to maintain, both on the devops side (e.g. migrating services) and also on iOS which isn't yet sync'ed with the brave-core list.

Given that our pinset now only includes three CAs (Amazon, GlobalSign and Let's Encrypt), @diracdeltas do you think that's still worth doing?

**Comment by diracdeltas** [comment]
> Given that our pinset now only includes three CAs (Amazon, GlobalSign and Let's Encrypt), @diracdeltas do you think that's still worth doing?

@fmarier probably not worth the complexity. i'll close this out for now.
