### ISSUE TITLE
Cannot open Brave Browser via taskbar icon on Ubuntu

### ISSUE THREAD

**Issue by mhatvan** [brave/brave-browser#5034]
## Description 

Brave can be openend through Dash or by executing "brave" in a terminal window, but clicking on Brave taskbar icon doesn't open the browser.

Tested with Ubuntu 18.04 and 19.04.

## Steps to Reproduce

   1. Start Brave Browser via Ubuntu Dash
   2. Right-click Brave icon and "Add to Favorites"
   3. Close Brave Browser 
   4. Click Brave icon and nothing happens

## Actual result:

Nothing happens

## Expected result:
Brave Browser opens

## Brave version (brave://version info)

Version 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)

**Comment by srirambv** [comment]
Works fine for me on both Ubuntu 18.04 and 19.04. How did you install the build? Was it via snap or deb? Also, you seem to be installing a really old version of the browser. Can you try following the steps mentioned [here](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux)?

For launching from terminal `brave` will not launch. You need to run `brave-browser` from terminal to launch

**Comment by mhatvan** [comment]
I am using the snap version (and am aware that it is outdated a bit), it can definitely be launched with running `brave`. The issue doesn't affect the deb version, I was able to install and run it without any issues right now, but would still prefer to use the snap version, which hopefully gets an update soon.

**Comment by fmarier** [comment]
The snap version is unofficial and unsupported. We recommend using our official packages instead.

**Comment by mhatvan** [comment]
Yeah, too bad.
I switched over to the .deb version, no issues encountered so far ;)

This issue can be closed imo.

**Comment by kjozwiak** [comment]
As @fmarier mentioned, the snap versions are unofficial and unsupported. It's also pretty behind in terms of updates as it's still on `0.63.48 CR 74.0.3729.108` and the official release version is `0.66.101 CR: 75.0.3770.142`.

**Comment by kjozwiak** [comment]
Closing the issue. If anyone is experiencing this issue with an official build, please re-open 👍

**Comment by superyair** [comment]
happening to me now on Ubuntu 18.04.3 LTS
Machine: MSI PS63 Modern
Brave Version 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)
