### ISSUE TITLE
Hideous Task Manager in Dark Mode

### ISSUE THREAD

**Issue by PunnyBoi** [brave/brave-browser#5035]
## Description 

The task manager doesn't adapt to the dark mode of the browser which makes it look ugly.

## Steps to Reproduce

   1. Open brave (with dark mode on).
   2. Press Shift+Esc.
   3. The middle part of the task manager is white which looks very clumsy.

## Actual result:

![image](https://user-images.githubusercontent.com/42476181/60091568-87a77a80-9762-11e9-93cb-0417dc6fd253.png)

## Expected result:
The middle part of the task manager should be dark when dark mode is on.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

Windows: 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No

**Comment by rebron** [comment]
Doesn't affect macOS. Reproducible on Windows 10 though.
