### ISSUE TITLE
New tab page overflow

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#5038]
New tab page is getting scrollbars from overflow around 920px -> 1120px widths. Should have it just be responsive without the scrollbars. 

![image](https://user-images.githubusercontent.com/29072694/60117489-fff44880-972e-11e9-99e5-03cde978d275.png)

**Comment by imptrx** [comment]
Test Plan:
1. Open New tabs page
2. Slowly shrink window and see if horizontal/vertical scroll bars appear

*Note*: Beyond a certain size, shrinking will always produce vertical scroll bars since the page doesn't fit the elements

**Comment by imptrx** [comment]
Closed by: https://github.com/brave/brave-core/pull/2566 as it pulled in the fix from brave-ui.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.119 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

Verified test plan from https://github.com/brave/brave-browser/issues/5038#issuecomment-506547487

Logged https://github.com/brave/brave-browser/issues/5844

![image](https://user-images.githubusercontent.com/34715963/64027835-d813cd80-cb41-11e9-8d7c-316b4d8ff47d.png)
![image](https://user-images.githubusercontent.com/34715963/64027890-f4176f00-cb41-11e9-976e-57efd34f6219.png)
![image](https://user-images.githubusercontent.com/34715963/64027914-fc6faa00-cb41-11e9-92fb-91205ce71f09.png)
