### ISSUE TITLE
New Tabs Page settings menu needs to be keyboard accessible

### ISSUE THREAD

**Issue by imptrx** [brave/brave-browser#5041]
## Description 

If you go through the page you should be able to access the new tabs page settings via keyboard. The settings icon at the bottom left should be selectable.

## Steps to Reproduce

   1. Go to new tabs page
   2. Press tab 

## Actual result:

The setting button will be skipped over when pressing tab but the other options will not be.
<img width="244" alt="Screen Shot 2019-06-25 at 12 29 27 PM" src="https://user-images.githubusercontent.com/9125231/60127401-f7a70800-9744-11e9-8ab0-bbdc623bc8af.png">

## Expected result:
- The settings button should be selectable and should open the setting menu when `space` or `enter` is hit

## Reproduces how often: 

Always reproducible. 

## Test plan:

- Go to new tabs page 
- Press tab 
- There should be an outline when you reach the settings icon at the bottom left of the page
- Pressing `space` or `enter` will open the setting menu
- Pressing tab will allow you to select the setting menu icon again
- Pressing `space` or `enter` will open the setting menu

**Comment by imptrx** [comment]
Marked as blocked until: https://github.com/brave/brave-core/pull/2857 is merged in.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.115 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/2814
