### ISSUE TITLE
Block all fingerprinting

### ISSUE THREAD

**Issue by markwylde** [brave/brave-browser#5043]
## Description 
When you change the Fingerprinting Protection field in chrome://settings/shields the change doesn't save when you restart the browser.

## Steps to Reproduce

   1. Goto chrome://settings/shields
   2. Change Fingerprinting Protection from "Block 3rd party fingerprinting" to "Block all fingerprinting"
   3. Restart Brave
   4. Goto chrome://settings/shields
   5. See Fingerprinting Protection has reverted back to "Block 3rd party fingerprinting"

## Actual result:
<img width="1175" alt="Screenshot 2019-06-26 at 19 04 56" src="https://user-images.githubusercontent.com/5929807/60166888-4dfb7000-9845-11e9-9098-5bbf8c1e0c8b.png">

## Reproduces how often: 
Happens every time

## Brave version (brave://version info)
Brave | 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit)
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

**Comment by tomlowenthal** [comment]
Can't reproduce. @brave/legacy_qa @kjozwiak — could you try?

**Comment by eljuno** [comment]
How about other shields settings?

Did you have "Clear on exit" enabled under `chrome://settings/clearBrowserData`? If yes, maybe related to #2400 and #3926

**Comment by markwylde** [comment]
@eljuno yes, I do have "Clear on exit" enabled. It looks like this is to do with clearing browser data.
