### ISSUE TITLE
Fix payment balances not called after first run of application

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#5046]
## Description 

Fix payment balances not called after first run of application

## Steps to Reproduce

   1. Fresh install
   2. Launch app
   3. Search console log for `GetPaymentBalance` (which should exist)
   4. Quit app
   5. Launch app
   6. Search console log for `GetPaymentBalance`
  

## Actual result:

`GetPaymentBalance` does not exist

## Expected result:
`GetPaymentBalance` should exist

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

0.68.2

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Linux

* Verified `OnGetPaymentBalance` is logged on a clean profile 
![image](https://user-images.githubusercontent.com/17010094/60311742-99d21600-9926-11e9-9e3f-52acddf255b5.png)
* Verified quitting browser and relaunching still logs `OnGetPaymentBalance`
