### ISSUE TITLE
Tor Window Triggers Cloudflare Verification Screen

### ISSUE THREAD

**Issue by foodfan** [brave/brave-browser#5047]
## Steps to Reproduce
   1. Visit https://beebom.com
   2. See the "One More Step" verification screen

## Brave version (brave://version info)
Version 0.66.93 Chromium: 75.0.3770.90 (Official Build) beta (64-bit)

## Version/Channel Information:
every channel

**Comment by CoVoCre** [comment]
I get it too ! But this would obviously come from cloud flare detecting some unusual activity !

**Comment by tomlowenthal** [comment]
CloudFlare is notoriously persnickety about Tor. We're working on adding PrivacyPass (#1677), but otherwise, this is CloudFlare's call, not Brave's.
