### ISSUE TITLE
Shields sometimes shows disabled on a tab even when its enabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#505]
## Description 

Shields sometimes shows disabled on a tab even when its enabled

## Steps to Reproduce

   1. Build from 2ae4e74b14ee322ec8d417dcff53e8cbc1dd08ed
   2. Launch browser and switch to an inactive tab 
   3. Page loads, shields shows disabled icon but badge is shown
   4. Click shields, shows enabled but icon looks disabled (see screenshot)

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/42411168-3aafc808-81c5-11e8-83ec-7cbb96d77060.png)

## Expected result:
Should not show disabled icon when shields is enabled for a site

## Reproduces how often: 

100% on 2ae4e74b14ee322ec8d417dcff53e8cbc1dd08ed

## Brave version (about:brave info) 

2ae4e74b14ee322ec8d417dcff53e8cbc1dd08ed

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @cezaraugusto @bbondy

**Comment by bbondy** [comment]
I've noticed this happen too

**Comment by srirambv** [comment]
I can reproduce this issue on all tabs which are inactive upon browser launch. Here's the correct steps 
1. Open 4 tabs and visit a different site on each of them 
2. Keep tab 1 active and close and relaunch browser
3. Switch to inactive tab 2 and let the page load
4. Shields shows active badge but shields icon itself looks disabled but is clickable
5. Switch to tab 1 and switch back to tab 2, shields shows correct enabled icon

**Comment by cezaraugusto** [comment]
seems like a lifecycle issue I'll be on it next week as soon I finish sync ui

**Comment by srirambv** [comment]
This behaviour is changed on the latest build. After relaunch, shields looks disabled like before but clicking on it doesn't bring the shields menu. Changing tab focus enables the shields button again.

![shields1](https://user-images.githubusercontent.com/17010094/44936762-fdf66e80-ad43-11e8-8b4e-9246c202ea7f.gif)

**Comment by Liunkae** [comment]
STR:
1. Open a new window and navigate to any website with a link.
2. Right click any link and click Open Link in New Tab.
3. Wait until the page has finished loading.
4. Switch to the new tab. Now the shields button is disabled.

![](https://user-images.githubusercontent.com/19424103/45395255-df715c80-b5fa-11e8-971c-17feb4bec082.gif)

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows
