### ISSUE TITLE
Disable outgoing SSDP requests when Chromecast support is disabled

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#5057]
Users have reported that Brave makes outgoing connections on the local network to port 1900 (apparently [ignoring any proxy settings](https://bugs.chromium.org/p/chromium/issues/detail?id=860308)):
- https://news.ycombinator.com/item?id=20294150
- https://community.brave.com/t/why-is-brave-issuing-upnp-discovery-requests/46500

This appears related to the [SSDP protocol required for Chromecast support](https://blog.g3rt.nl/allow-google-chromecast-host-firewall-iptables.html) but we should make sure that these connections are turned off when that feature (see #209) is disabled.

Apparently turning off `load-media-router-component-extension` and `media-router-cast-allow-all-ips` in `chrome://flags` doesn't help.

**Comment by fmarier** [comment]
[This bug](https://bugs.chromium.org/p/chromium/issues/detail?id=859359) mentions an [enterprise policy](https://www.chromium.org/administrators/policy-list-3#EnableMediaRouter) (also mentioned in [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=665572)) for disabling Chromecast entirely by adding a json file in `/etc/opt/chrome/policies/managed/` containing the following:
```
{
  "EnableMediaRouter": false
}
```

**Comment by tomlowenthal** [comment]
Is #5070 the more specific version of this?

**Comment by jumde** [comment]
@tomlowenthal - yes

**Comment by blacktop** [comment]
Is this happening again?

**Comment by jumde** [comment]
Hi @blacktop - Are you seeing this again? Could you please share the Brave Browser version and OS that you are using? Are you interacting with the `Cast` option when you see these requests or is this happening at start?

**Comment by blacktop** [comment]
I am not using the cast option and do not own any ChromeCasts. However, it stated happening all the time after I updated a week ago maybe?

I just now checked for an update and pulled down 1.29.77 and It's still doing it.

**Comment by blacktop** [comment]
<img width="657" alt="Screen Shot 2021-09-03 at 2 04 52 PM" src="https://user-images.githubusercontent.com/6118188/132060237-b740b38e-89f1-4885-a605-76daeb277754.png">

**Comment by jumde** [comment]
Thanks for your help @blacktop. We'll try to address this quickly. Issue tracked here - https://github.com/brave/brave-browser/issues/17873
