### ISSUE TITLE
Please provide option to DISABLE preview tab

### ISSUE THREAD

**Issue by kdawg1406** [brave/brave-browser#506]
I strongly dislike the Tab Preview feature.  Even with time set to long, its WAY too short.

This is very distracting when my mouse is moved over a tab and the browser UI changes.

Please either make an option for VERY LONG - 10 seconds or provide an option to disable.

**Comment by srirambv** [comment]
You can disable preview by toggle preview switch under tabs.
![image](https://user-images.githubusercontent.com/17010094/42419603-7518a28c-8286-11e8-94e8-99bdfd0c9798.png)

Also please log any browser-laptop related issues in https://github.com/brave/browser-laptop/issues/. This repo is for brave-core only.

**Comment by kdawg1406** [comment]
@srirambv thank you very much.  Apologies for missing this setting.
