### ISSUE TITLE
Linux crash on brave://version

### ISSUE THREAD

**Issue by cg505** [brave/brave-browser#5060]
## Description 

Browser crashes upon visiting `brave://version` with
```
[26380:26380:0627/180347.485937:WARNING:resource_bundle.cc(941)] unable to find resource: 16474
[26380:26380:0627/180347.486005:FATAL:resource_bundle.cc(942)] Check failed: false. 
```

Note: Happen only on debug build.

## Steps to Reproduce

   1. Open browser
   2. Visit `brave://version`

## Actual result:

Browser crashes

## Expected result:
Browser should show version info page

## Reproduces how often: 

100% on Linux

## Brave version (brave://version info)

hahahaha

## Version/Channel Information:

Dev builds on current master only (not Nightly or any other channel builds)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by fmarier** [comment]
It doesn't crash for me on Release:
```
Brave | 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit)
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Linux
```

Beta:
```
Brave | 0.67.95 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Linux
```

Dev:
```
Brave	0.68.85 Chromium: 75.0.3770.100 (Official Build) dev (64-bit)
Revision	cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS	Linux
```
or Nightly:
```
Brave | 0.69.14 Chromium: 75.0.3770.100 (Official Build)nightly (64-bit)
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Linux
```
That's on Ubuntu 18.04.

**Comment by cg505** [comment]
Yeah, it only seems to crash when building a Debug build (`npm run bulid && npm start`)

**Comment by bsclifton** [comment]
@cg505 is this still happening?

**Comment by simonhong** [comment]
Not reproduced on latest master.
