### ISSUE TITLE
Hosted twitch videos adds two publishers to ac list

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5062]
## Description 

Hosted twitch videos adds two publishers to ac list. Found while testing #4921

## Steps to Reproduce

   1. Copy https://www.twitch.tv/psherotv and visit the link
   2. View the stream for a couple of mins (if it's interesting else wait for 10sec)
   3. Check ac table, has two entries for twitch, one for the actual pub you visited and one for the user that is being hosted in the channel
   4. Attention % is added to the hosted twitch user and not the one you visited (see screenshot)

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/60311149-f97af200-9923-11e9-8f94-609a008400a9.png)
![image](https://user-images.githubusercontent.com/17010094/60311161-07c90e00-9924-11e9-9b53-ad0a364d2777.png)

## Expected result:
Not sure whats the expected result is 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? May be not checked but will be when 66.x goes to release
- Can you reproduce this issue with the beta channel? mostly yes
- Can you reproduce this issue with the dev channel? mostly yes 
- Can you reproduce this issue with the nightly channel? mostly yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
@srirambv that is expected as we are checking actual video playing. So if twitch is reporting hosting video back we will save that video as well
