### ISSUE TITLE
New tab page background setting should be a profile preference

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#5064]
## Test plan
See https://github.com/brave/brave-core/pull/2831

## Description
The backgrounds on the new tab page were made toggleable with https://github.com/brave/brave-core/pull/2668, however the setting is persisted only in local storage

## Additional notes
This setting should be defaulted to ON

When https://github.com/brave/brave-core/pull/2668 was implemented, it defaulted to OFF. This was fixed with https://github.com/brave/brave-core/pull/2756... but users that got this (between versions 68.64 and 68.72) would still have backgrounds OFF

Adding this new setting will fix those users

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.109 Chromium: 76.0.3809.62 (Official Build) dev (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Ubuntu 18.04 LTS

Used test plan from https://github.com/brave/brave-core/pull/2831

![5064](https://user-images.githubusercontent.com/34715963/61757027-23a6bf00-adbf-11e9-92a3-12ecb3b3ade3.gif)
