### ISSUE TITLE
Settings page of guest(also tor) is empty

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#5065]
Can repro all channels from master(0.69.x) to stable (0.65.x)
Settings page of guest window should have search engine part.

Note: master debug build shows search engine part properly.

**Comment by btlechowski** [comment]
Still reproducible

Brave | 1.1.22 Chromium: 79.0.3945.79 (Official Build) (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/71086406-2b199b00-219a-11ea-86b6-33826da8868e.png)

cc @brave/legacy_qa

**Comment by btlechowski** [comment]
Marking as QA/Blocked - need a new build to test, 1.11.92 or newer.

**Comment by LaurenWags** [comment]
Removing `QA/Blocked`, https://github.com/brave/brave-browser/releases/tag/v1.11.92 is available

**Comment by LaurenWags** [comment]
@simonhong @petemill is there a test plan for this one? brave://settings page now displays on a guest window, but I'm not sure which sections should be available. Currently Shields, Social media blocking, and Search engine settings are accessible - is this ok? Should there be more settings or fewer settings?

Also, brave://settings does not display for a Tor window - should it? (per issue title, Tor is mentioned as well)

Any extra info for QA on what we're trying to fix/accomplish with this issue would be helpful, thanks! cc @rebron @kjozwiak @bsclifton 

re-adding `QA/Blocked` until this is sorted.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 x64` using the following build:

```
Brave | 1.11.92 Chromium: 84.0.4147.68 (Official Build) dev (64-bit)
-- | --
Revision | e7b7234037639b407e69c5428c891ce018cd6c0d-refs/branch-heads/4147@{#772}
OS | macOS Version 10.15.5 (Build 19F101)
```

* ensured that clicking on `Settings` via the hamburger menu in a `Guest` window correctly opened `brave://settings`
  * ensured that typing `brave://settings` into the URL in a `Guest` window correctly opened the settings page
* ensured that only `Shields`, `Social media blocking` and `Search engine` were visible.
* ensured that clicking on the three options on the navigation list correctly focuses the correct section
* Created https://github.com/brave/brave-browser/issues/10635 and https://github.com/brave/brave-browser/issues/10665

<img width="578" alt="Screen Shot 2020-07-08 at 5 40 49 PM" src="https://user-images.githubusercontent.com/2602313/86974250-fd9b3b80-c143-11ea-8e6c-8453c08a9d2a.png">
