### ISSUE TITLE
Options to suppress Widevine notification

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#5068]
The Widevine install notification should have more options to dismiss it so that someone isn't [constantly barraged](https://community.brave.com/t/is-there-a-way-to-automatically-block-widevine-pop-up-on-facebook-each-time-on-brave-mac-os/65381) by Widevine install notifications on a site they know they don't want to see.

[This section subject to design adjustment. Specifics can change, functionality should remain].
Add a checkbox on the Widevine prompt, with a drop-down picker:
`[ ] Never ask me again [ on this site | on any site ]`

If checked, "this site" means any page under this eTLD+1.

We also need a way to undo this choice in settings. If you really want to undo it, you probably don't want to be prompted again, so it should just be an option to install Widevine directly. In the _Extensions_ section of settings:

Legend: `Install the Widevine DRM module  >`
Explanation: `Widevine is a piece of copy protection software from Google which some sites use to play protected video.`

Clicking this option gives you a modal dialog (like the one for _Reset Settings_):

Title: `Install Widevine`
Body: `Google's Widevine is a piece of copy protection software sometimes euphemistically called "digital rights management" or DRM. Brave doesn't own or control Widevine, we can't inspect it, and we can't promise it's safe to use. Some sites require Widevine in order to play back protected video. You have to agree to the Widevine [Terms of Use] from Google before installing it.`
Buttons: `[ Cancel ] [[ Install Widevine ]]`

**Comment by shapeshifterincontext** [comment]
Yes please.
Example: using a website like Aliexpress, where I can have 50 tabs open in a matter of minutes, drives me absolutely insane!

**Comment by tinfever** [comment]
I'd like to second this request. Aliexpress asks for this on every tab. It'd be great to be able to say "No" and have an option for the domain to not ask again.

**Comment by misterkatanga** [comment]
I love this browser but I need to use Aliexpress for my business so this bug is a dealbreaker for me.  Aliexpress is one of the most frequented online shopping sites.  Not addressing this in any way is a bad sign to me.  I can already see this issue was brought up some time ago and was summarily closed with zero attempt to fix the issue.  

I really hope I am wrong and this is addressed soon.

**Comment by simonhong** [comment]
PR for simple version that just added `don't ask again` in install prompt because more specifications are needed for this issue. I'll handle when it's done.

**Comment by whraglyn** [comment]
Hi Simon,
Plz excuse this probably unnecessary query from an old 100% disabled man  who lives to newsurf, and is getting pretty damn tired of continual widevine notices.

Any progress on 'do not ask again'/'never ask' checkbox for such notices?

Many thx for all your hard work on Brave, Simon, as to all who are with you, Sir.

Scotty :-)

![WIDEVINE](https://user-images.githubusercontent.com/48482829/65522109-df639800-deaf-11e9-8b17-af1eb817e100.PNG)

**Comment by simonhong** [comment]
@whraglyn You will see 'Don't ask again` check box in the next release (`0.69.x`) :)
https://github.com/brave/brave-core/pull/2980

**Comment by whraglyn** [comment]
Thx much, Sir!

Sorry I just cannot make sense of thread info, jargon, etc.

Would you be so kind as to tell me how to do the 'fix'/'workaround'
referred to below"

[image: SIMON FIX.PNG]
in that top line it says
'User can turn it off from settings page or prompt dialog.

Fix brave/brave-browser#5341
<https://github.com/brave/brave-browser/issues/5341>'

Yet, when i click link, it goes to
[image: Capture.PNG]

Which to this old man is just incomprehensible techspeak among which I find
nothing remotely relevant to the 'fix' to which the link referred?

Am I missing something obvious to those more skilled/knowledgeable than I?
I see nothing regarding how to 'fix' the widevine notice.

All fine if waiting til 0.69 is only option, just confused so checking with
experts to see if I can shut down the damn thing now.

Again, many thx for your time, consideration, and any insight you may
offer, sir!

Very Best Regards,
OldManScotty :-)

**Comment by simonhong** [comment]
@whraglyn Sorry for your inconvenience.
Waiting to next stable release is only the option.
We are planning to release it at `October 1, 2019`. [release schedule](https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule)
After that, you can shut down it from dialog or settings.
Thanks!

**Comment by whraglyn** [comment]
No worries at all, Sir; and many thx again for your patience!
:-)

**Comment by Techguyprivate** [comment]
https://www.youtube.com/watch?v=OD2i0lY6lv0&feature=youtu.be
