### ISSUE TITLE
media_router::DialServiceImpl should not initiate UpNP connections by default

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#5070]
### Test Plan 

specified here: https://github.com/brave/brave-core/pull/2836

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.5 x64` using the following build:

Brave | 0.66.100 Chromium: 75.0.3770.142 (Official Build) (64-bit)
-- | --
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Mac OS X

* Went through the test case outlined under https://github.com/brave/brave-core/pull/2836
* Ensured when `Load Media Router Component Extension` was disabled via `brave://flags`, the following packets weren't being captured under Wireshark

<img width="443" alt="Screen Shot 2019-07-16 at 12 18 38 PM" src="https://user-images.githubusercontent.com/2602313/61312206-f017d380-a7c5-11e9-9704-7d629470711d.png">
