### ISSUE TITLE
Clean up theme patches (after Chromium 76)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#5072]
## Description 
Chromium 76 made updates to `ui/views/widget/widget.cc` specifically in this commit:
https://chromium.googlesource.com/chromium/src/+/1033fac9187e2f68e8d87c2ac07354eb8fbdaa74

These changes broke the dark/light mode implementations we have in place, because we use `ui::NativeThemeDarkAura::instance()` (same as incognito) as a way to deliver the dark theme.

The suggested cleanup would be to instead remove these patches (see `brave/browser/ui/views/frame/brave_browser_frame.cc`) and patch / subclass functionality so that the check (for user preference) can instead be made in `base_theme->SystemDarkModeEnabled()`

**Comment by simonhong** [comment]
Closed because these cleanup is merged together with C76 rebase.
