### ISSUE TITLE
skype not working

### ISSUE THREAD

**Issue by morriswinkler** [brave/brave-browser#5073]
#### Version

Brave is up to date
Version 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit)

#### Problem

https://web.skype.com doesn't detect microphone, speakers or camera

I explicitly allowed  access via site settings.

<img width="896" alt="Screenshot 2019-06-29 at 14 51 29" src="https://user-images.githubusercontent.com/4302527/60384424-c8aed000-9a7d-11e9-87c0-5bd3093a15b7.png">

**Comment by tomlowenthal** [comment]
I bet that this is fingerprinting protection. Open Shields and allow device recognition?

**Comment by oshanz** [comment]
@tomlowenthal you are correct. after disabling the fingerprint protection now it works.

**Comment by tomlowenthal** [comment]
Sounds like this is just working as expected.

**Comment by morriswinkler** [comment]
Is it possible to enable fingerprinting for only one site?

**Comment by tomlowenthal** [comment]
Yes, when you change a Shields preference in the panel, that's just for the site you're visiting.

**Comment by morriswinkler** [comment]
thanks
