### ISSUE TITLE
https://www.cosmolex.com/login/ fails to render correctly

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#5078]
## Description 
Site https://www.cosmolex.com/login/ doesn't render correctly (right hand side). Was reported here: https://community.brave.com/t/cant-see-portion-of-websites-login-home-page-unless-ad-control-is-turned-off/67266

## Steps to Reproduce

   1.  Open https://www.cosmolex.com/login/
   2.  Right side (in blue) doesn't show
   3.  Disabling Sheilds doesnt help

## Actual result:
https://imgur.com/a/JUNYI3L

Site seems to only work if Safescript extension is enabled, not sure if its a referrer issue here.

## Expected result:
Display right side correctly.

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
(Version 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit))

- Can you reproduce this issue with the beta channel?
Actually No. (The site rendered correctly)
(Version 0.67.95 Chromium: 75.0.3770.100 (Official Build) beta (64-bit))

- Can you reproduce this issue with the nightly channel?
Yes
(Version 0.69.17 Chromium: 75.0.3770.100 (Official Build) nightly (64-bit))

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:

Tried disabling/Enabling various features of Safescript extension to see which option was the cause of the fix. I couldn't find out,

**Comment by houruomu** [comment]
No problem loading the right portion here.
Windows 10
Version 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit)
With Privacy Badger, Ublock Origin, decentralyeyes

**Comment by rebron** [comment]
@ryanbr Can you reproduce in Nightly?

**Comment by ryanbr** [comment]
I can, producible in Nightly. Some how its related to blocking of https://ipinfo.io/json?token=

https://secure.fanboy.co.nz/gif/cosmolex.gif

**Comment by Yamboy1** [comment]
Can not reproduce in Brave nightly `0.72.3 Chromium: 76.0.3809.132 (Official Build) nightly (64-bit)`
![brave_wOgsEJcm21](https://user-images.githubusercontent.com/37413895/64481365-b7790100-d22e-11e9-8138-df58c4105541.png)

**Comment by bsclifton** [comment]
Seems to be working great now 😄
