### ISSUE TITLE
Global preferences file (change defaults for all profiles)

### ISSUE THREAD

**Issue by bleepnetworks** [brave/brave-browser#5079]
hi brave folks,

I'm using the people feature to organise my browsing into multiple buckets. I can see there are per-profile preferences files in ~/Library, is there a global settings file somewhere though?

~/Library/Application\ Support/BraveSoftware/Brave-Browser/Profile\ [n]/Preferences 
~/Library/Application\ Support/BraveSoftware/Brave-Browser/Profile\ [n/Secure\ Preferences

Ideally I'd be able to edit ~/.brave/[foo] or ~/Library/Application\ Support/BraveSoftware/Brave-Browser/[bar] and set a bunch of keys to change the defaults across all profiles at once.

**Comment by rebron** [comment]
Closing. Could be addressed with sync later.
