### ISSUE TITLE
Changing volume in windows shows a large media window blocking content 'brave.exe' is source

### ISSUE THREAD

**Issue by niico100** [brave/brave-browser#5081]
## Description 

Changing volume in windows shows a large media window blocking content 'brave.exe' is source. Usually audio apps like Spotify provide this, but let you turn it off, now a large part of my screen is covered.

## Steps to Reproduce

   1. Install Brave
   2. Change windows volume
   3. 

## Actual result:
![IMG_6704b](https://user-images.githubusercontent.com/28755726/60397846-a4bcbe80-9b51-11e9-9344-2a40168b6543.jpeg)

## Expected result:
Only vlume shown, instead a huge square is shown with media controls covering much of the work I'm doing. I have to wait 5 seconds each time I change the volume before I can access that part of the screen again. Extremely annoying.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit)

## Version/Channel Information:
Only tried with this version

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
This isn't even useful, it provides me dia controls (forward back) that are greyed out. I change volume through normal use 10 or 20 times per hour at least.

**Comment by srirambv** [comment]
I think this is a Windows feature for any media that is playing. Can you check if the behaviour is the same or different on Chrome?

cc: @GeetaSarvadnya to check on Windows and confirm

**Comment by niico100** [comment]
I never saw Chrome doing this before, but I just tested it and it does seem to be doing it. However, Spotify also does it but there's a setting in Spotify itself to disable it, so looks like it needs to be disabled on a per app basis (unless you know of a global setting?)

**Comment by niico100** [comment]
I've found a way to disable it in Chrome and Brave: https://www.tenforums.com/tutorials/134484-enable-disable-chrome-exe-volume-control-media-key-handling.html

**Comment by srirambv** [comment]
Perfect. I think it's because of the media keys implementation on Chromium that these are showing up. Since its behind flags not sure if they would end up on release or not or at what point in time. 

cc: @rebron to take call on keeping the issue open/close

**Comment by bsclifton** [comment]
We can close this one out - apologies for the unpleasant experience.  We had this tracked with https://github.com/brave/brave-browser/issues/3807 and then resolved the issue (in 0.68.x) by updating our field trial config

Fix should be live in release channel ~Aug 20th 😄 The work-around you posted @niico100 is perfect- that's what I was going to recommend. Thanks for sharing here

Closing as issue has been resolved in future channels (Dev/Nightly)
