### ISSUE TITLE
Feature: Users should be able to whitelist sites that they want to save data when using "clear on exit"

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#5089]
## Description 

As it is now, users have the option to use `Clear browsing data --> On Exit` to erase browsing data once the browser is closed. The problem is that this removes any selected type of data from _all sites_ when the browser is exited.

![image](https://user-images.githubusercontent.com/3299098/60468331-1fe3aa80-9c0e-11e9-968a-ae1350d68e46.png)

It would be worth implementing a feature wherein the user may add a whitelist/exclude list for the `On Exit` menu so that anything they do wish to save can be preserved.

For example, if a user wants to Clear data on exit for all sites _except for duckduckgo_, they would simply add DDG to the exclude list, then all site data would be wiped on exit with the exception of DDG.

**Comment by rebron** [comment]
Could possibly switch between profiles as a way to handle this. The UE for this could be fairly complicated/confusing.
