### ISSUE TITLE
hide profile icon until second profile icon is added

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#5091]
## Description 

Only show profile icon in the nav bar if 2 or more profiles are available. Otherwise, hide the profile icon.

## Test plan (@petemill)

0. Fresh profle
1. Open 1 or more windows
 --> Profile button is now shown
2. Open the guest window
 --> Profile button is shown

3. Open incognito / tor window
 --> Profile button is shown

4. Create a new profile (on macos use the System menu, on other OS wait until https://github.com/brave/brave-core/pull/3096 provides the app menu action!)
 ---> Profile button is shown on original profile window
 ---> Profile button is shown on new profile window

5. Delete profile (click on profile button, then Manage profiles, then the menu button on one of the profiles, then remove profile, then confirm!)
 ---> Profile button is not shown on existing remaining profile window

**Comment by Valinwolf** [comment]
+1, this is one of two gripes I have about brave... no way to hide the profile icon when I don't even use profiles.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | macOS Version 10.14.6 (Build 18G95)

* ensured that the Guest window profile image is always being displayed when opening Guest windows (even when there's multiple profiles created)
* ensured that the Tor window profile image is always being displayed when opening Tor windows (even when there's multiple profiles created)
* opened several windows and created a new profile and ensured the default profile image appears on all opened windows
* changed the name/icon of the active profile under `brave://settings/manageProfile` and ensured that the change propagates through all the current open windows that belong to that specific profile
* Removed all profiles via the `Profile Manager` and ensured the profile icon is removed from all currently opened windows
* Ensured that removing a profile closes/deletes all opened windows that are currently associated with that specific profile
