### ISSUE TITLE
F12 should open Developer Console

### ISSUE THREAD

**Issue by SharmaHarsh7** [brave/brave-browser#5094]
## Description 
**F12** (instead of Ctrl + Shift + I) should open the developer console.

## Steps to Reproduce

   1. Open browser
   2. Press F12
  
## Expected result:
It should open the developer console.

**Comment by srirambv** [comment]
F12 works perfectly and opens Developer tools. Closing as an invalid issue and lack of proper information.

**Comment by SharmaHarsh7** [comment]
@srirambv Thanks, it was not working earlier.
                   Working now, tested.
