### ISSUE TITLE
macOS UI freezes often if 3 or more windows are open

### ISSUE THREAD

**Issue by tiagosiebler** [brave/brave-browser#5095]
## Description 

Recently I've seen a number of macOS freezes, and today Brave became my primary suspect. They're not a complete system lockdown, here's a summary of symptoms:
- The whole UI will lock up system-wide, *except* the mouse. Music continues playing too. Seems purely visual.
- When the freeze ends, it's like all UIs refresh. Sometimes this happens when I get a notification from anywhere, sometimes it just happens. 

So far this doesn't sound like a brave issue, I know. Originally I thought my hardware was starting to fail on me, but I did an experiment after reading something online. 

I remember reading that others were seeing lock-downs if they had too many (tabs * windows) open in Brave, which I did too, the last time this was happening like crazy. So I've closed all but 2 windows, and tried to keep the tab count trimmed to max 5 per window (max 10 in total, across 2 windows in Brave). The system freezes stopped happening.

Today I opened another window while needing to check something quickly, and the issue started happening again. Once while working in Atom, twice while I received a Slack notification.

I've closed the 3rd window again, so far so good. Seems weird to imagine brave could cause this, but the correlation seems too much to be coincidence. 

Will update this post if it happens again with the 3rd window closed. If it doesn't happen in again in the next day (it happens very regularly when it does), I'll reopen a 3rd window with some tabs to experiment. What can I do to collect more useful information? 

Has anyone else seen something similar? This is on an older 2015 macbook pro, on 10.14.5.

## Steps to Reproduce

   1.  Open brave up with at least 3 windows, at least 5 tabs per window on any website.
   2. (still confirming) receive slack notification | (still confirming) do stuff in atom
  

## Actual result:

System will lock up, but mouse still moves and music continues. System will unfreeze within a few minutes.

## Reproduces how often: 

2-3 times per hour when it happens.

## Brave version (brave://version info)
```
Brave | 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X
JavaScript | V8 7.5.288.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

```

## Version/Channel Information:

- Can you reproduce this issue with the current release? y
- Can you reproduce this issue with the beta channel? tbc
- Can you reproduce this issue with the dev channel? tbc
- Can you reproduce this issue with the nightly channel? tbc

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  
- Does the issue resolve itself when disabling Brave Rewards? tbc
- Is the issue reproducible on the latest version of Chrome? tbc

## Miscellaneous Information:

- definite, have multiple tabs open with js intensive pages (tradingvue, facebook, youtube).
- tbc, slack & atom open.
- tbc, receive slack notification (with slack in background)
- tbc, keep brave open with at least 3 windows, 5+ tabs per window.

**Comment by bsclifton** [comment]
@tiagosiebler thanks for the report - sorry we didn't respond in a timely manner

Are you still experiencing this? If so, can you try either our Developer or Nightly channels? We fixed some bugs when upgrading our Adblock library (it's possible the problem was solved- would be great to verify)

**Comment by tiagosiebler** [comment]
I'll try to test that, though this has been happening for weeks (and a few Brave updates happened in the meantime), or was your set of bug fixes pushed in the last few days?

I'm looking for patterns each time this system freeze happens, so far:

This showed in the system.log shortly before a freeze, lasted roughly 1 minute (no messages for 1 minute after this):
```
Aug  7 13:22:55 tsbook com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.Brave Browser H.72199): Path not allowed in target domain: type = pid, path = /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/75.0.65.121/XPCServices/AlertNotificationService.xpc error = 147: The specified service did not ship in the requestor's bundle, origin = /Applications/Brave Browser.app/Contents/Frameworks/Brave Browser Framework.framework/Versions/75.0.65.121/Helpers/Brave Browser Helper.app
```

Also noticed:
- if I open a tab to a javascript-heavy website, I see a freeze system-freeze (except mouse) almost always (tradingview.com is an example)
- if I change a video on facebook to "expanded" (not fullscreen, but filling the whole tab), I see a freeze like this too. Lasts up to a few minutes.

Not sure how much value this has in getting closer to what might be leading up to and causing this. 

I'm still not 100% sure if Brave is the cause, but it seems more often the workflow leading to the freeze is an action happening in brave (opened a tab / went to a site / clicked something like a video), more often than a freeze following an action that started somewhere else (message notification from slack / navigation to Atom). Really weird behaviour...will try nightly when I can.
