### ISSUE TITLE
Dark Mode broken on Linux

### ISSUE THREAD

**Issue by Leon0402** [brave/brave-browser#5098]
## Description 
On Linux, settings page, brave rewards etc. is still displayed in light theme.
It's unlikely that is has to do something with global settings as it's reproducible on different Linux distros with different desktop environments (gnome, kde, xfce). 
See: https://community.brave.com/t/dark-theme-is-broken-or-incomplete/  

## Steps to Reproduce

   1. Open settings page of brave on Linux (or brave rewards etc.)

## Actual result:
![Screenshot_20190702_170153](https://user-images.githubusercontent.com/33933142/60523459-09f7e780-9ceb-11e9-8b62-608abcab23f2.png)

## Expected result:

Should be dark. 

## Reproduces how often: 
Always

## Brave version (brave://version info)
Current release and beta release (0.66.x)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

**Comment by smcatala** [comment]
should the default ERR_CONNECTION_REFUSED page be dark as well ?
![image](https://user-images.githubusercontent.com/3369203/60572823-b206c280-9d76-11e9-8cde-3d5ee6241016.png)

**Comment by simonhong** [comment]
@smcatala No, that page is not dark-mode aware yet.

**Comment by bsclifton** [comment]
@simonhong does dark mode not work on Linux? I thought the Polymer pages would properly get the setting on all platforms... starting with Chromium 75?

The rewards page for sure is not done, but that is captured with https://github.com/brave/brave-browser/issues/4229

**Comment by simonhong** [comment]
@bsclifton On linux, only our native ui dark mode works and not the webui because linux os doesn't have dark mode setting like mac/windows. But, I think I can handle it

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.117 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Ubuntu 18.04 LTS

Verified STR from the description.

![image](https://user-images.githubusercontent.com/34715963/63815285-5569f300-c934-11e9-84f9-50089cd87e03.png)
![image](https://user-images.githubusercontent.com/34715963/63815289-5a2ea700-c934-11e9-8797-3b63d73b5317.png)
![image](https://user-images.githubusercontent.com/34715963/63815317-70d4fe00-c934-11e9-8cde-7216fddd2960.png)
![image](https://user-images.githubusercontent.com/34715963/63815337-89451880-c934-11e9-9b3e-e78d40b8349b.png)
