### ISSUE TITLE
I'm automatically logged out of my SoundCloud account after logging in

### ISSUE THREAD

**Issue by BlueMiaou** [brave/brave-browser#5099]
## Description 
When I try to log into SoundCloud with an imported password from my previous browser, Chrome, it automatically logs me out.

## Steps to Reproduce

   1. Try to log into SoundCloud using the saved passwords that were imported from Google
   2. Press the "Log In" button

## Actual result:

It automatically logs you out after a split second of being logged in

## Expected result:
Staying logged in and the account being remembered

## Reproduces how often: 

Every time I try to log into SoundCloud with the saved account

## Brave version (brave://version info)

Brave | 0.65.121 Chromium: 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1803 (Build 17134.829)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? I don't have the beta channel
- Can you reproduce this issue with the dev channel? I don't have the dev channel
- Can you reproduce this issue with the nightly channel? I don't have the night channel

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
I imported all my passwords directly from Chrome and started using Brave the day I'm reporting this issue

**Comment by rebron** [comment]
Can you clear out your cookies and see if this is still an issue?

**Comment by BlueMiaou** [comment]
Hi rebron, thanks for responding! I cleared my cookies, and it worked. Thanks!

**Comment by rebron** [comment]
@BlueMiaou. Awesome, glad that worked out.
