### ISSUE TITLE
Browser crash when changing shields settings

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#51]
Browser crash when changing shields settings

1. Visit http://cartoonhd.zone (used this because it detects adblockers)
2. Enable FP and Block Phishing from shields
3. Watch some video 
4. Open shields, FP and Block phishing was disabled, tried enabling again and browser crashed

Note: You might have to watch couple of videos for the adblocker to be detected on the site and show up anti-adblocker message

**Comment by bbondy** [comment]
@srirambv fixed?

**Comment by srirambv** [comment]
Yes looks fixed. No crash on shields settings toggle.

**Comment by GeetaSarvadnya** [comment]
Validated the issue on:

Brave | 0.54.2 Chromium: 69.0.3497.42 (Official Build) dev (64-bit)
-- | --
Revision | 9c4613c66dfeb2b76ef6dd4b15884c15db3b4969-refs/branch-heads/3497@{#655}
OS | Windows
JavaScript | V8 6.9.427.14
Flash | 30.0.0.154
