### ISSUE TITLE
Take into account top level frame domain when doing same-origin comparisons for blockable resources

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#5105]
Currently in tracking protection, trackers are allowed if they're first-party relative to their owning frame. In Firefox, trackers are [also allowed if they're first-party relative to the page itself](https://bugzilla.mozilla.org/show_bug.cgi?id=1108017) (i.e. the top-level "frame").

It's not possible to express using the EasyList syntax so this is something that needs to be implemented in the code that uses the matches found by the adblock parser.

**Comment by fmarier** [comment]
The investigation needed here is to confirm whether or not we do the same first-party checks as Firefox in our blocking.

Example test case:

* on `www.facebook.com`
* there is an iframe pointing to `superawesomefacebookgame.com`
* that iframe loads `connect.facebook.com/sdk.js`

Two things to note:

- The first-party check is based on ETLD+1 (i.e. `www.facebook.com` and `connect.facebook.com` are considered same-origin).
- We check requests originating from iframes against the domain of the iframe **and** the domain of the page (and allow if **one of those** matches).

**Comment by fmarier** [comment]
@pes10k Did that get fixed? If so, which PR / issue was that related to?

**Comment by pes10k** [comment]
@fmarier Sorry was going to fast here.  I closed bc i dont think we should do this anymore, and that i think we should mark as `wontfix`.  We should keep making 1p/3p determinations relative to only the immediate frame, since thats the storage area they'd have access to, other resources they could collaborate with, etc.

What do you think?  Good to keep closed, or reopen?
