### ISSUE TITLE
brave://wallet should appear as a Brave secure page (if possible)

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#5109]

**Comment by bbondy** [comment]
This is working as long as you use brave://wallet to load the extension. So closing it.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.1006)


![image](https://user-images.githubusercontent.com/38657976/65449293-4c4b4380-de58-11e9-9c1f-092da4670cb1.png)

![image](https://user-images.githubusercontent.com/38657976/65449401-916f7580-de58-11e9-9e21-f356719f30c2.png)
