### ISSUE TITLE
Minimize patches for {Chrome,Brave}Importer

### ISSUE THREAD

**Issue by garrettr** [brave/brave-browser#511]
## Description 

Follow-up for brave/brave-core#185.

@darkdh suggested some ideas for minimizing the patches currently required for the Chrome and Brave importers in his review comments for https://github.com/brave/brave-core/pull/185. After a discussion we agreed the tradeoffs between changing the patch strategies deserved more careful consideration and it was more of a priority to ship BraveImporter and BraveProfileLock. This issue is meant as a reminder to reconsider and potentially implement some or all of those suggestions at a later date.

**Comment by garrettr** [comment]
@bridiver has some more suggestions for minimizing these patches in comments on https://github.com/brave/brave-core/commit/1581d1fffa1d1580b5a3342f44d9cd16606b2141

**Comment by bsclifton** [comment]
Closing as @simonhong did some great cleanup on here recently 😄
