### ISSUE TITLE
No subframe should be present when ethereum-remote-client is installed

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#5110]
<img width="1094" alt="Screen Shot 2019-07-03 at 12 05 17 AM" src="https://user-images.githubusercontent.com/831718/60562653-64fb0000-9d26-11e9-93f6-d64c90e4dd77.png">

Subframe to metamask.github.io should not be there.

`app/scripts/lib/setupMetamaskMeshMetrics.js:  testingContainer.src = 'https://metamask.github.io/mesh-testing/'`

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

* ensured that `Subframe: metamask.github.io` wasn't appearing under `Task Manager` when launching a new profile
* ensured that `Subframe: metamask.github.io` wasn't appearing under `Task Manager` when loading `brave://wallet`

<img width="691" alt="Screen Shot 2019-09-26 at 9 00 39 PM" src="https://user-images.githubusercontent.com/2602313/65734633-f1a52800-e0a1-11e9-8896-ac0fa7d19083.png">
<img width="692" alt="Screen Shot 2019-09-26 at 9 00 12 PM" src="https://user-images.githubusercontent.com/2602313/65734636-f1a52800-e0a1-11e9-9809-5c1b0ba00eb9.png">
