### ISSUE TITLE
Map ethereum-remote-client extension path to brave://wallet

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#5117]
Loading the Ethereum Remote Client extension page should work from the hamburger menu and display as brave://wallet
Loading brave://wallet should work
Loading chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/home.html should map to brave://wallet.

**Comment by kjozwiak** [comment]
@bbondy looks like loading `chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/home.html` maps to `brave://wallet` but doesn't load the page. Instead, you'll get the following:

<img width="932" alt="Screen Shot 2019-09-20 at 12 45 27 AM" src="https://user-images.githubusercontent.com/2602313/65300019-f61c8e80-db3f-11e9-95a4-c6519c798351.png">

Went through the following STR:

* ensure that `brave://wallet` loads without any issues via `Hamburger Menu` -> `Crypto Wallets` using a new profile
* ensure  that entering `brave://wallet` into the URL loads without any issues using a new profile
* ensure that `chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/home.html ` maps to `brave://wallet` and loads without any issues using a new profile

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | macOS Version 10.14.6 (Build 18G95)

* Verified the STR/Cases outlined under https://github.com/brave/brave-browser/issues/5117#issue-463790272

**Comment by kjozwiak** [comment]
Confirmed with @bbondy via Slack that https://github.com/brave/brave-browser/issues/5117#issuecomment-533403572 is expected and not an issue.
