### ISSUE TITLE
Auto install ethereum-remote-client and add for usage on first access of brave://wallet

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#5118]
task manager should not show the process until you load brave://wallet.
But extension dir should exist shortly after first run without any actions: `~/Library/Application\ Support/BraveSoftware/Brave-Browser-Development/odbfpeeihdkbihmopkbjmoonfanlbfcl`

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

* ensured that launching brave for the first time doesn't have the `Extensions: Crypto Wallets` process running via the `Task Manager`
* ensured that `odbfpeeihdkbihmopkbjmoonfanlbfcl` isn't being created in a new profile unless opening `brave://wallet` for the first time
* ensured that once `brave://wallet` is opened, the `Extensions: Crypto Wallets` process is visible via the `Task Manager`

<img width="1085" alt="Screen Shot 2019-09-26 at 3 51 22 PM" src="https://user-images.githubusercontent.com/2602313/65728439-fb6e6180-e088-11e9-8d15-0ad4c0c1d0f3.png">

<img width="1203" alt="Screen Shot 2019-09-26 at 6 11 36 PM" src="https://user-images.githubusercontent.com/2602313/65728476-19d45d00-e089-11e9-8065-5d03a42199ef.png">
