### ISSUE TITLE
Ad notifications received this month should not include transaction count from server

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#5119]
## Description 

Ad notifications received this month should not include transaction count from server

## Steps to Reproduce

   1. Cash-in confirmations in July
   2. Wait for pay out in August

## Actual result:

Ad notifications received this month is calculated from the transaction count from server and any unredeemed transactions

## Expected result:
Ad notifications received this month should be calculated by how many ads were seen on a particular month irrespective if they were redeemed

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.117 Chromium: 76.0.3809.62 (Official Build) (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2851
