### ISSUE TITLE
Disable chrome settings that send user data to google

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#512]
Disable:

- use a web service to resolve navigation errors
- prediction service to load pages quickly
- use of web service to help resolve navigation errors

**Comment by yrliou** [comment]
Haven't dig deep into details, just a quick update for the prefs that could control these settings.
- use a web service to resolve navigation errors: prefs.alternate_error_pages.enabled
- prediction service to load pages quickly: prefs.net.network_prediction_options

@jumde Is there a typo in the third item? Do you mean "Use a web service to help resolve spelling errors"? If so, controlled by prefs.spellcheck.use_spelling_service

**Comment by yrliou** [comment]
@jumde The prediction service seems only processing data locally mainly for prefetch, prerender, preresolve, and preconnect, I didn't see it sends data out to google in the chrome/browser/net/predictor.[cc|h], maybe we don't need to explicitly disable that pref and could keep this feature usable?

I also checked https://support.google.com/chrome/answer/114836?visit_id=1-636668839787347351-4200605008&p=settings_privacy&rd=1 and https://www.google.com/chrome/privacy/index.html, seems all local to me too, please let me know if there are other docs suggest it does.

**Comment by yrliou** [comment]
@jumde Should we make sure these two are also disabled?
- Use a prediction service to help complete searches and URLs typed in the address bar
- Automatically send some system information and page content to Brave to help detect dangerous apps and sites

**Comment by jumde** [comment]
@yrliou - 

Re: the network prediction service, I looked at the code and I think the data is only sent if the `LearnFromNavigation` observers are set. We can keep this setting enabled if the processing is happening locally. Thanks for checking.

Re: Search Suggestions, we should disable them by default since user history will be sent to the default search engine.

Re: web service to help resolve navigation errors: navigate to - chrome://settings/?search=navigation%20errors

<img width="695" alt="screen shot 2018-07-11 at 12 44 55 am" src="https://user-images.githubusercontent.com/1903815/42557562-b6c26e74-84a3-11e8-88e2-491089354f1f.png">

Re: Dangerous Apps/Sites -  kSafeBrowsingExtendedReportingOptInAllowed only works if Safe Browsing is enabled which as of now is not, but it would be great to disable this reporting by default.

**Comment by srirambv** [comment]
@jumde @yrliou  any QA test plan for this?

**Comment by jumde** [comment]
@srirambv - The test plan is specified here: https://github.com/brave/brave-core/pull/244

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux
