### ISSUE TITLE
GitHub Auto Contribution

### ISSUE THREAD

**Issue by jdkuki** [brave/brave-browser#5120]
## Description 
Feature Request:
Viewing content on a user's profile should track auto contribution for the user instead
of the tld website.

## Steps to Reproduce

 
   1. Clean profile and join rewards
   2. Browse to a user's profile on github (https://github.com/jdkuki)
   3. Stay on their profile for at least 8 seconds
   4. Open brave://rewards
   5. (user_name) on GitHub should appear in AC table

## Actual result:

n/a

## Expected result:
![image](https://user-images.githubusercontent.com/8422122/60613261-6dcbf000-9d7f-11e9-8475-096dd85a4b9d.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.1.1 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified STR mentioned in the description (tested in staging env)
![image](https://user-images.githubusercontent.com/38657976/68953987-1340a700-07e9-11ea-9af9-733476e48922.png)
