### ISSUE TITLE
gs.statcounter.com broken because of Shields' HTTPS upgrade

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#5124]
The graphs on https://gs.statcounter.com don't show up unless the HTTPS upgrade part of Shields is disabled.

![Screenshot from 2019-07-03 20-29-15](https://user-images.githubusercontent.com/167821/60638031-a7c5e200-9dd1-11e9-8865-32d4cf1aafc8.png)

The following shows up in the devtools console:

```
Failed to load resource: net::ERR_TOO_MANY_REDIRECTS
gs_movePlatformList-inline.jquery.js:1 Failed to load resource: net::ERR_TOO_MANY_REDIRECTS
fusioncharts.maps-bc24f1d161.js:7 Uncaught ReferenceError: FusionCharts is not defined
    at fusioncharts.maps-bc24f1d161.js:7
gsNewsletterSubscribePanel-inline.js:1 Failed to load resource: net::ERR_TOO_MANY_REDIRECTS
gs.statcounter.com/:1 Access to XMLHttpRequest at 'https://gs.statcounter.com/chart.php?device=Desktop%20%26%20Mobile%20%26%20Tablet%20%26%20Console&device_hidden=desktop%2Bmobile%2Btablet%2Bconsole&multi-device=true&statType_hidden=browser&region_hidden=ww&granularity=monthly&statType=Browser&region=Worldwide&fromInt=201806&toInt=201906&fromMonthYear=2018-06&toMonthYear=2019-06&hideCaption=true&bottomLegend=true&siteStyling=true&siteChartMargins=true&setChartTitle=Browser%20Market%20Share%20Worldwide' (redirected from 'http://gs.statcounter.com/chart.php?device=Desktop%20%26%20Mobile%20%26%20Tablet%20%26%20Console&device_hidden=desktop%2Bmobile%2Btablet%2Bconsole&multi-device=true&statType_hidden=browser&region_hidden=ww&granularity=monthly&statType=Browser&region=Worldwide&fromInt=201806&toInt=201906&fromMonthYear=2018-06&toMonthYear=2019-06&hideCaption=true&bottomLegend=true&siteStyling=true&siteChartMargins=true&setChartTitle=Browser%20Market%20Share%20Worldwide') from origin 'http://gs.statcounter.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
```

## Brave version (brave://version info)
```
Brave	0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)
Revision	cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS	Linux
```

## Other Additional Information:

It works fine in Firefox with HTTPS Everywhere and that makes sense since there's an [exclusion for `gs.statcounter.com` upstream](https://github.com/EFForg/https-everywhere/blob/57a41c2edd22e4ee60c61691dba3c210085ee1e8/src/chrome/content/rules/Statcounter.xml#L33). While that exclusion in our list too, it doesn't look like we honor the exclusion.

**Comment by fmarier** [comment]
The first thing to do here would be to confirm that:

- this is still broken, and that
- the exception from the ruleset does make it to the leveldb database generated by `brave/https-everywhere-builder`.

If that's ignored, then it means that the bug lies in the Shields code which applies the HTTPS Everywhere rulesets.

**Comment by pipboy96** [comment]
@fmarier thanks, will look into that.

**Comment by pipboy96** [comment]
Navigating to https://gs.statcounter.com/ didn't trigger the issue on current stable Brave version.

**Comment by fmarier** [comment]
You're right, it does work. Maybe there was something else wrong with the rulesets after all. I upgraded the ruleset to the latest after merging your signature-checking PR.
