### ISSUE TITLE
Move RewardsInternalsInfo to mojo interface

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#5132]
We need to move `RewardsInternalsInfo` in `vendor/bat-native-ledger/include/bat/ledger/rewards_internals_info.h` into mojo interface. 

Example how to do this https://github.com/brave/brave-core/pull/2432

**Comment by cg505** [comment]
This requires #5131.

**Comment by NejcZdovc** [comment]
@cg505 let's do #5131 and #5132 in the same PR
