### ISSUE TITLE
Add callback to GetGrantCaptcha

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#5140]
We need to add callback to `GetGrantCaptcha` inside `vendor/bat-native-ledger/include/bat/ledger/ledger.h`.

When adding callback be carful what is called inside this functions. Make sure that you handle all use cases that they were previous handled via `ledger_client.h` functions that then called client back.

**Comment by btlechowski** [comment]
Could you add QA/Yes or QA/No label to the issue?
