### ISSUE TITLE
Disable Background Sync by default

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#515]
chrome://settings/content/backgroundSync

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows
