### ISSUE TITLE
Wire SaveRecurringTip through ledger

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#5152]
We need to wire all UI triggered functions through ledger code. What `SaveRecurringTip` we save it directly into db.

Take example of `GetRecurringTipsUI` on how it should be done.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/2962
![image](https://user-images.githubusercontent.com/38657976/65509017-1d33e100-deef-11e9-89d2-9430ede342f8.png)

- After changing the recurring tip value from BR panel, the updated recurring monthly value reflected in DB under recurring donation table
![image](https://user-images.githubusercontent.com/38657976/65508977-042b3000-deef-11e9-8bac-e979f85f2d15.png)
