### ISSUE TITLE
Enable Brave ads for Australia, New Zealand and Ireland

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#5153]
In preparation of testing out Brave ads in Australia, New Zealand, and Ireland, we need to enable users in those regions to turn on ads, and provide them a notification of the availability

**Comment by ryanbr** [comment]
I approve :)

**Comment by dynamicdolphin** [comment]
Eagerly awaiting this...
Still saying "Sorry! Ads are not yet available in your region."

**Comment by tmancey** [comment]
> Eagerly awaiting this...
> Still saying "Sorry! Ads are not yet available in your region."

Merged with master and will be in the next nightly build, any feedback would be much appreciated

**Comment by tmancey** [comment]
> I approve :)

Merged with master and will be in the next nightly build, any feedback would be much appreciated

**Comment by dynamicdolphin** [comment]
When can we expect Ads to be available for Australia?
Still not showing, I'm running Version 0.66.99

**Comment by tmancey** [comment]
> When can we expect Ads to be available for Australia?
> Still not showing, I'm running Version 0.66.99

Currently this change has only be merged with Nightly, if you install our nightly build you will be able to use Ads.

**Comment by dynamicdolphin** [comment]
Still saying No Ads Available in Nightly 0.69.44..?

**Comment by tmancey** [comment]
> Still saying No Ads Available in Nightly 0.69.44..?

Apologies I should have mention this was added to 0.69.66, so once 0.69.66 or above is available the feature will be enabled, thanks

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.117 Chromium: 76.0.3809.62 (Official Build) (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

1. Clean install of 0.67.117 (configured appropriately). Enabled Rewards, verified Ads were enabled, no “Sorry” message on Ads panel. Verified I was served an ad as expected. Ads panel info incremented as expected. *PASS for AUS, NZ, IRL*
2. Installed 0.66.101 (configured appropriately). Enabled Rewards. Upgraded on test channel to 0.67.117. Verified I was notified about Ads via BAT logo notification. Verified I was able to turn on Ads and was served an ad as expected. Ads panel info incremented as expected. *PASS for AUS, NZ, IRL*
3. Installed 0.66.101 (configured appropriately). Enabled Rewards. Upgraded on test channel to 0.67.117. Verified I was notified about Ads via BAT logo notification. I did not enable Ads and browsed around a bit to verify I was not served any ads. *PASS for AUS, NZ, IRL*
4. Installed 0.66.101 (configured appropriately). Did not enable Rewards but did click on BAT logo to make red notification bubble go away. Upgraded on test channel to 0.67.117. Saw red notification dot on BAT logo. Inquired about it, but it seems to be expected for now. Note - notification bubble did go away after a bit. Saw same results for all 3 regions: AUS, NZ, IRL
5. Installed 0.62.51 (configured appropriately). Enabled Rewards. Upgraded on test channel to 0.67.117. Verified I was notified about Ads via BAT logo notification. *PASS for AUS, NZ, IRL*
6. Installed 0.62.51 (configured appropriately). Did not enable Rewards but did click on BAT logo to make red notification bubble go away. Upgraded on test channel to 0.67.117. Saw red notification dot on BAT logo. Inquired about it, but it seems to be expected for now. Note - notification bubble did go away after a bit. Saw same results for all 3 regions: AUS, NZ, IRL
- Also spot checked ads in existing regions (US, UK)
- Also confirmed that ads were not on in some other regions as expected (Belgium, etc)
- Test cases from https://github.com/brave/brave-core/pull/2865

**Comment by Flash-ZA** [comment]
Please South Africa next 😫 Been hyped for this for way too long now

**Comment by Durry-Duck** [comment]
I am totally keen for this. what an awesome browser so far.

**Comment by tmancey** [comment]
> I am totally keen for Australian Ads. What an awesome browser so far.

Australian Ads are now in the release channel, please update to the latest version.

**Comment by tmancey** [comment]
> Please South Africa next 😫 Been hyped for this for way too long now

We are working to add more countries, keep an eye on Reddit, GitHub etc. for latest updates
