### ISSUE TITLE
Feature request: Add Quick Access

### ISSUE THREAD

**Issue by Leon0402** [brave/brave-browser#5154]
## Description 

Opera offers a quick access panel. As soon as you click in the address bar, a small panel opens (see screenshot) with the ability to do certain tasks. I find especially useful to have direct access to the bookmarks and personally find this approach more beautiful than having a bookmark topbar. But also the option to copy the address instantly or download the page as pdf etc. is quite useful. 

![Screenshot 2019-07-04 at 15 06 55](https://user-images.githubusercontent.com/33933142/60668928-6551e300-9e6d-11e9-8e9d-beea494d04cc.png)

![Screenshot 2019-07-04 at 15 15 00](https://user-images.githubusercontent.com/33933142/60669416-8e26a800-9e6e-11e9-892c-ce8d5b59169e.png)

**Comment by rebron** [comment]
Closing. wonftix. Thanks for the suggestion.

**Comment by rebron** [comment]
@Leon0402 Also, if you have further feature suggestions, sometimes it's better if you start the discussion/conversation at community.brave.com and then issues can get filed from there.

**Comment by Leon0402** [comment]
@rebron Yeah I thought about publishing my ideas in the forum, but  (and I might be wrong) it seemed to me like those suggestion don't get much attention by the developer and also not quite much by the users. I just looked through all posts again from the last two month in the section and most posts have not even 100 views and mostly no comment at all. Whereas here, the suggestions/issues get noticed by the developers and users and usually ranked by priority. I kinda had the feeling that you would actually prefer github for those, as you work a lot with "projects", "milestones", "labels" ... so it just easier to work here than it is on the forum. 

I would also be interested, why the suggestion is just completely rejected. No offence, you probably have your reasons! But if it's "we have more important things to do" than you could give it lowest priority. Just want to make you understand that it's not very nice to reject a user's suggestions for all time, without giving any reason (at least it's a project for the community (?) and therefore the user's suggestions should be taken seriously). Again, I appreciate your work on this great project! But perhaps this a new view on the things, you haven't yet noticed, just let me know what you think :)

**Comment by rebron** [comment]
@Leon0402 Best to publish your ideas in the forum. A screenshot of a competitor's feature with the driveby request to "implement this" will almost always will be marked closed/wontfix. Ideas are great in the community forum where they can be discussed and on github, we'd like issues to be more actionable and less suggestion (though smaller in scope feature requests do come through).

**Comment by Chealer** [comment]
> @rebron Yeah I thought about publishing my ideas in the forum, but (and I might be wrong) it seemed to me like those suggestion don't get much attention by the developer and also not quite much by the users. I just looked through all posts again from the last two month in the section and most posts have not even 100 views and mostly no comment at all. Whereas here, the suggestions/issues get noticed by the developers and users and usually ranked by priority. I kinda had the feeling that you would actually prefer github for those, as you work a lot with "projects", "milestones", "labels" ... so it just easier to work here than it is on the forum.


@Leon0402 I have no opinion on this request, but as a general note, requests should be made via tickets, not via forums, indeed. It is correct that closing a ticket without explanation is "not very nice", to put it mildly. I found this request when doing a search about Opera and opened the hit by curiosity since a colleague mentioned Brave as a browser option earlier this week, and for sure I won't be trying it anytime soon after seeing such an outcome.

If I can make a small contribution to this request, I have no idea what Opera feature you are referring to. I am using Opera 64.0.3417.73 on Windows 10, and nothing particular happens when I click the address bar.
