### ISSUE TITLE
Change Ubuntu/Mint Linux installation instructions to use $VERSION_CODENAME

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#5156]
As mentioned in https://github.com/brave/brave-browser/issues/5111#issuecomment-508556787, we might be able to directly support Debian in our [official instructions](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux) by changing the variable we use to pick the right repository.

Instead of `$UBUNTU_CODENAME`, we could use `$VERSION_CODENAME`.

**Comment by fmarier** [comment]
This seems to work on recent distros:

Ubuntu 18.04 and Pop!_OS 18.04:
```
$ echo $UBUNTU_CODENAME
bionic
$ echo $VERSION_CODENAME
bionic
```

Debian unstable:
```
$ echo $UBUNTU_CODENAME

$ echo $VERSION_CODENAME
buster
```

but not older ones:

Debian 9 stretch:
```
$ echo $UBUNTU_CODENAME

$ echo $VERSION_CODENAME

```

**Comment by fmarier** [comment]
It also won't work on recent versions of Mint:
```
$ echo $UBUNTU_CODENAME
xenial
$ echo $VERSION_CODENAME
sylvia
```

**Comment by fmarier** [comment]
The following however, will work with Debian 10+, Ubuntu 16.04+ and Mint 18+:
```
echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ `(test -z "$UBUNTU_CODENAME" && echo $VERSION_CODENAME) || echo $UBUNTU_CODENAME` main"
```

**Comment by fmarier** [comment]
For Ubuntu 14.04, Mint 17 and Debian 9, we can use the [Mint 17 instructions](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#mint-17).

**Comment by pitsi** [comment]
As I have mentioned in #5111, what about using 'lsb_release -sc' ? I think it works the same under all those situations.

**Comment by fmarier** [comment]
We used to use `lsb_release -sc`, but it caused some problems on Debian/Ubuntu derivatives (see #2343).

**Comment by srirambv** [comment]
+1 from @jkhgvfgvsth  for Debian install instructions via #5161

**Comment by jkhgvfgvsth** [comment]
@fmarier @srirambv They key issue is that users do not know to follow "Mint 17+" steps.

**Comment by pitsi** [comment]
Small notice.
Now that debian 10 (buster) is released as stable, development will shift to debian 11 (bullseye) and that codename will be used in the new /etc/os-release... once base-files (the package containing /etc/os-release) gets updated in the next days or weeks.
So, you will probably need to make one more folder in the repo.

**Comment by pitsi** [comment]
The package base-files was updated today, for the first time after the release of debian 10, and it now /etc/os-release contains only these :(
```
# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by pitsi** [comment]
A big thank you for updating all the repos so as to mention debian 11 (bulleye) as another debian release :)

**Comment by pitsi** [comment]
As it seems, ubuntu did not update base-files to v11 for 19.10, so the $VERSION_CODENAME variable remains
```
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan

```

**Comment by pitsi** [comment]
Has anything changed for the repos of beta, dev and nightly? These are their urls last time I checked
```
deb https://brave-browser-apt-beta.s3.brave.com/ <CODENAME> main
deb https://brave-browser-apt-dev.s3.brave.com/ <CODENAME> main
deb https://brave-browser-apt-nightly.s3.brave.com/ <CODENAME> main
```

**Comment by fmarier** [comment]
Yes, you should be able to use `stable` instead of the Debian/Ubuntu codename in all repos. No need to change it when you upgrade to the latest version of your distro :)
