### ISSUE TITLE
Sync between Android & Windows stops working after a few days. Some bookmarks get deleted.

### ISSUE THREAD

**Issue by smartfonreddit** [brave/brave-browser#5159]
## Description 

Bookmarks between Android and Windows stop syncing after a few days of inactivity. Sometimes this will happen with the Sync chain looking as if it's dropped on Android, but present on Windows. Sometimes it will be accompanied by **all bookmarks being removed from Android**. Other users have reported bookmarks being removed from desktop.

## Steps to Reproduce

Android 9.0 (Galaxy S10 or OnePlus 6T) with a Windows 10 laptop. Configure a sync. Import 2,000 bookmarks into Windows Brave from an HTML file. Wait an hour and verify it's all synced to Android - it is. Randomly remove or add bookmarks on either device, it's synced properly.

Stop modifying bookmarks in order not to trigger a sync for a few days.

## Actual result:

Bookmark something on Android. It doesn't sync on Windows.
In the worst scenario (happened twice), bookmarking something on Android then launching Brave on Windows will cause all the bookmarks on Android to disappear. 

## Reproduces how often: 

Every time a new sync chain is set up, after few days of using (or not using) it. Bookmarks disappearance is rare.

## Brave version (brave://version info)

All versions in the past 2 months.

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Can't test
- Can you reproduce this issue with the nightly channel? Can't test

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

Related

https://community.brave.com/t/sync-chain-breaks-after-updating/65668

https://community.brave.com/t/brave-sync-is-really-buggy/48125/48

https://community.brave.com/t/sync-seems-really-unreliable/65887

https://www.reddit.com/r/brave_browser/comments/bvobcq/why_doesnt_sync_remove_deleted_bookmarks_across/

https://www.reddit.com/r/brave_browser/comments/c1xova/bookmarks_missing/

https://www.reddit.com/r/brave_browser/comments/bpn735/any_android_90_pie_users_who_have_been_able_to/

https://community.brave.com/t/bookmarks-history-vanish-after-phone-stop/66960

https://community.brave.com/t/last-call-for-help-with-sync-on-mobile/57539

https://community.brave.com/t/another-sync-issue/64295

https://community.brave.com/t/sync-not-working-on-iphone/67897

https://community.brave.com/t/sync-is-dealbreaker-for-me/65456

https://community.brave.com/t/brave-syncing-beta-version/51842

**Comment by masparrow** [comment]
Can confirm as of Brave OSX & Windows Version 1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit)

With the following setup; 

- Sync chain configured on 3 x Windows, 2 x OSX, 1 x iPad, 1 x Android Phone
- Small set of 'existing' bookmarks synced across all installs
- Import ~1300 bookmarks from Google Chome on Windows install
- Sync to all installs 
- Checked all is well on each
- Some days later, all installs have lost nearly all the bookmarks (down to ~30) _apart from_ the one I imported on, which still seems to have the entire collection

I can leave everything as it is for a while, if anyone wants to DM me for diagnostics/more info.

**Comment by jsecretan** [comment]
Likely irrelevant with sync v2 coming
