### ISSUE TITLE
Documentation | Add Debian Instalation Steps

### ISSUE THREAD

**Issue by jkhgvfgvsth** [brave/brave-browser#5161]
**Feature**: Add Debian Channel to [documentation](https://brave-browser.readthedocs.io).

https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

**Why?**: Debian is undeniably the most used standard for Linux. With other distros like Arch and Slackware following closing behind. It is a shame that it does not yet have official installation steps, handicapping a significant portion of Free Software users.

**Comment by srirambv** [comment]
Will be done once #5156 is fixed
