### ISSUE TITLE
Add OpenBSD Install to Downloads

### ISSUE THREAD

**Issue by jkhgvfgvsth** [brave/brave-browser#5162]
**Feature**: Add OpenBSD Installation Option to Downloads.
**Question**: How to install on OpenBSD and forks like LibertyBSD?

https://brave-browser.readthedocs.io/en/latest/installing-brave.html

**Comment by ryanbr** [comment]
LibertyBSD seems dead, git, http/ftp links aren't working. and last update was early last year

**Comment by rebron** [comment]
Close. Wontfix.

**Comment by job** [comment]
Why is this a wontfix? OpenBSD not considered interesting? Chromium builds easily on OpenBSD - thanks to OpenBSD there are a lot of security improvements to chromium
