### ISSUE TITLE
Vimeo - Videos and live stream videos are not getting added to a-c table

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5165]
## Description 

Vimeo - Videos and live stream videos are not getting added to a-c table

## Steps to Reproduce

   1. Clean profile 0.69.2
   2. Open Vimeo.com
   3. Play some videos (Videos and Live stream videos)
   4. Videos are not getting added a-c table, the only domain name is added to a-c table

## Actual result:

Videos and live stream videos are not getting added to a-c table
https://vimeo.com/343329245
https://vimeo.com/343329224
https://vimeo.com/307787245
https://vimeo.com/306445977
https://vimeo.com/blog/post/nab-2018-awards-new-products-live-streaming/

## Expected result:
Videos and live stream videos are not getting added to a-c table

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.69.2 Chromium: 75.0.3770.100 (Official Build) nightly (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
works for me

![image](https://user-images.githubusercontent.com/9574457/60784578-c4567700-a14f-11e9-9eea-4b86b73916a2.png)

**Comment by GeetaSarvadnya** [comment]
Closing the issue. I was in the wrong assumption that the blog post videos should also get added to a-c table. Clarified with @LaurenWags as well. Thanks!

**Comment by LaurenWags** [comment]
I see the same as @NejcZdovc - videos from blogs are being added to my ac table.
