### ISSUE TITLE
Vimeo- Verified pubs name is not displayed in BR Panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5166]
## Description 

Vimeo- Verified pubs name is not displayed in BR Panel

## Steps to Reproduce

   1. Clean profile 0.69.2
   2. Open Vimeo.com
   3. Open any verified pubs video
   4. Open BR panel and verify the publisher name
   5. The publisher name is not displayed just domain name is displayed

## Actual result:

Vimeo- Verified pubs name is not displayed in BR Panel

https://vimeo.com/blog/post/deliver-monetize-live-video-ott-branded-apps/
https://vimeo.com/blog/post/video-for-corporate-communications/

![image](https://user-images.githubusercontent.com/38657976/60777602-d1c03100-a150-11e9-99a3-5e23e106d9e4.png)

## Expected result:
Verified pubs name should be displayed in BR Panel

## Brave version (brave://version info)

Brave | 0.69.2 Chromium: 75.0.3770.100 (Official Build) nightly (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya which url are you using for testing. Links that you pasted are blog links

**Comment by NejcZdovc** [comment]
it works for me. https://vimeo.com/user3261383

![image](https://user-images.githubusercontent.com/9574457/60784004-6e80cf80-a14d-11e9-841f-817dbe2a0361.png)

**Comment by GeetaSarvadnya** [comment]
Closing the issue. I was expecting the blog post video pubs name displayed in BR panel, clarified it with @LaurenWags. Thanks.
