### ISSUE TITLE
Vimeo - one time tip/monthly tip is sent to the domain instead of a verified publisher

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5167]
## Description 

one-time tip/monthly tip is sent to the domain instead of a verified publisher

## Steps to Reproduce

   1. Clean profile 0.69.2
   2. Open Vimeo.com
   3. Open any verified publisher https://vimeo.com/blog/post/deliver-monetize-live-video-ott-branded-apps/
   4. Send a one-time tip and monthly tip to it
   5. Verify the tips panel
   6. Tips panel is recorded domain name instead of actual publisher names

## Actual result:

one-time tip/monthly tip is sent to the domain instead of a verified publisher

![image](https://user-images.githubusercontent.com/38657976/60778045-ec93a500-a152-11e9-9ab2-45b9f22c736f.png)

## Expected result:
Tips panel should record the actual verified publisher names instead of domain name

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.69.2 Chromium: 75.0.3770.100 (Official Build) nightly (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
works for me. https://vimeo.com/user91022604 (on staging) or https://vimeo.com/user3261383 (on production)

![image](https://user-images.githubusercontent.com/9574457/60784107-e9e28100-a14d-11e9-939f-60806883e619.png)

**Comment by GeetaSarvadnya** [comment]
I was sending tips to the blog post videos and expecting two diff pubs name in Tips panel. Clarified with @LaurenWags. Closing the issue.
