### ISSUE TITLE
Vimeo - Monthly recurring tip set for one pubs is assigned to all the verified pubs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5168]
## Description 

Vimeo - Monthly recurring tip set for one pub is assigned to all the verified pubs

## Steps to Reproduce

   1. Clean profile 0.69.2
   2. Open Vimeo.com
   3. Open a verified publisher https://vimeo.com/blog/post/video-for-corporate-communications/
   4. Send a monthly tip 5 BAT 
   5. Open BR panel and ensure that monthly tip 5 BAT is populated in dropdown
   6. Open any other verified pub in a new tab https://vimeo.com/blog/post/deliver-monetize-live-video-ott-branded-apps/
   7. Open BR panel and see 5 BAT is populated in the dropdown which is wrong

   

## Actual result:

Vimeo - Monthly recurring tip set for one pub is assigned to all the verified pubs

## Expected result:
Monthly recurring tip set for one pub should not be assigned to all the verified pubs

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.69.2 Chromium: 75.0.3770.100 (Official Build) nightly (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
works for me with video links. I see that you have blog post links.

**Comment by kjozwiak** [comment]
@GeetaSarvadnya can you go through this one as well and do a quick double check? Noticed that a few other ones were closed due to using blog post links as @NejcZdovc mentioned above.

**Comment by NejcZdovc** [comment]
closing as stale
