### ISSUE TITLE
Insecure script modal links to google support page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#517]
## Description 

Insecure script modal links to google support page

## Steps to Reproduce

   1. Visit https://mixed-script.badssl.com/
   2. Click insecure script in URL
   3. Click on Learn More open google support page

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/42540739-aec394ea-846d-11e8-89a4-4bd202aad220.png)

**Comment by btlechowski** [comment]
Verification passes on

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

Opens https://community.brave.com/
