### ISSUE TITLE
Vimeo - Open and close the BR panel decreases the attention percentage value in BR panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5172]
## Description 

Vimeo - Open and close the BR panel decreases the attention percentage value in BR panel

## Steps to Reproduce

   1. Clean profile 0.69.2
   2. Open Vimeo.com 
   3. Play Vimeo video `https://vimeo.com/willchristiansen`
   4. Open the BR panel and note down the attention rate (logged #5294)
   5. Navigate to brave://rewards and make sure the attention value displayed in BR panel and a-c table is the same
   6. Open the BR panel again where the video is playing
   7. Attention percentage got reduced in both BR panel and a-c table
   8. Repeat step 6 and 7( any number of times), the attention rate decreases gradually

## Actual result:

Attention percentage got reduced in both BR panel and a-c table

## Expected result:
Attention percentage should not get reduced

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.69.2 Chromium: 75.0.3770.100 (Official Build) nightly (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya gif is cropped 
![image](https://user-images.githubusercontent.com/9574457/60791383-d93d0580-a163-11e9-8d7f-c993e912ef2d.png)

**Comment by GeetaSarvadnya** [comment]
Apologies, please find the attached recorded file. 

https://drive.google.com/open?id=1NB1jSfGIg0b5qAwZ3BeyToIPGNd0mMih

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya can you please split your windows and try again. I assume this happens because you are switching between tabs and vimeo.com is gaining visit time every time that you switch while video doesn't record time that often

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc Please find the attached recording
https://drive.google.com/open?id=15nhnnQyk25jNN5tvGhrLQbGvNHZQzkz4

**Comment by NejcZdovc** [comment]
that is expected as what you are doing is losing focus on a window so we record vimeo.com time for AC, that's why it goes down. You can see at 35s of you video that Patagoina goes up as it recorded video duration in the table
