### ISSUE TITLE
Failed payment balances do not retry unless browser is restarted or ad grant is claimed

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#5175]
## Description 

Failed payment balances fail to retry unless browser is restarted or ad grant is claimed

## Steps to Reproduce

   1. Disconnect network connection
   2. Launch browser
   3. Wait 10 minutes

## Actual result:

Log shows "Start retrying in # seconds", and after # seconds have passed `GetPaymentBalance` should be retried however the retry is cancelled and then restarted without retrying to get the payment balance.

## Expected result:
Log shows "Start retrying in # seconds", and after # seconds have passed `GetPaymentBalance` should be shown in the log. You can re-connect the network connection to make sure the payment balance is retrieved.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Workaround is to restart the browser or wait until a user claims an ad grant

**Comment by LaurenWags** [comment]
Verified passed with LG Nexus 5 with Android 5.1 running 1.1.0 rc2 BraveModernarm.apk

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.117 Chromium: 76.0.3809.62 (Official Build) (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

* Verified first test case listed in description and test plan from https://github.com/brave/brave-core/pull/2878
* Second test plan in description failed and was logged under #5390, however, it will be resolved by uplifting #5011 and retested with that uplift.
