### ISSUE TITLE
New Tab Page: move components from brave-ui to brave-core

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#5178]
The NTP components are specific to brave-core. It will be more productive to have these inside the brave-core repo rather than in a separate repo (brave-ui).

Reasoning and steps explained in https://github.com/brave/brave-browser/issues/2335

### NTP works
- Open NTP
- Check renders and no console errors

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.114 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

* Verified test plan from description
