### ISSUE TITLE
enable certificate revocation

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#518]
https://revoked.badssl.com should show up as revoked on all platforms. this is the same issue as https://github.com/brave/browser-laptop/issues/12510 but for brave-browser.

the underlying problem is that we don't use chrome's crlsets

**Comment by jumde** [comment]
Spoke too soon:

On Windows:  `Brave 0.54.0 Chromium: 69.0.3497.32 (Official Build) dev (64-bit) `

<img width="1151" alt="screen shot 2018-08-16 at 1 12 20 pm" src="https://user-images.githubusercontent.com/1903815/44232528-34ce6100-a156-11e8-9f5a-7e941fc5366d.png">

Same on Linux: 
<img width="683" alt="screen shot 2018-08-16 at 1 28 00 pm" src="https://user-images.githubusercontent.com/1903815/44233288-4add2100-a158-11e8-806a-bb2fc3c51add.png">

**Comment by bridiver** [comment]
@diracdeltas is this just the timeout for security features like HSTS?

**Comment by bridiver** [comment]
I'm pretty sure that's the issue because I just tried it on a local build and it worked fine

**Comment by diracdeltas** [comment]
No, it's the issue of CRLsets in Brave which are not enabled by default for embedders.

**Comment by diracdeltas** [comment]
@bridiver the test case works on high sierra; AFAIK it doesn't work on linux and windows

**Comment by bridiver** [comment]
I'll look, but I haven't found anything in the code that is different for google chrome builds

**Comment by diracdeltas** [comment]
@bridiver let me forward you an email thread from google security

**Comment by diracdeltas** [comment]
this is also a problem on MacOS - the test case might not work though depending on your system TLS settings

**Comment by bbondy** [comment]
FYI should update issue milestone to match where it is landed. Thanks!

**Comment by jumde** [comment]
Reverted: https://github.com/brave/brave-core/pull/986 (master and 0.58.x)

**Comment by bbondy** [comment]
Removing versioned milestone until relanded.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta(64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Linux

* Verified test plan from https://github.com/brave/brave-core/pull/652
* Verified Cert error message is shown on visiting the page
* Verified going into Advance info doesn't allow you to load the page

**Comment by PoorPocketsMcNewHold** [comment]
This seems to doesn’t be the case anymore. I can access both of this website, and the [url=https://www.grc.com/revocation.htm]grc revocation test[/url].
![image](https://user-images.githubusercontent.com/13170204/68022211-f910b000-fca3-11e9-8ced-5e85e0cdcc5c.png)
![image](https://user-images.githubusercontent.com/13170204/68022260-20677d00-fca4-11e9-82ca-5334798147fe.png)
Version 0.71.106 Chromium: 78.0.3904.70 (Official Build) beta (64 bits).

**Comment by jumde** [comment]
Thanks for the report @PoorPocketsMcNewHold. 

1. Which OS are you using?
2. Are you able to reproduce this with a clean profile?  
3. Can you navigate to brave://components, manually update crlsets and check if that works for you?

With a clean profile on `0.71.106 Chromium: 78.0.3904.70 (Official Build) beta (64-bit)` : 

I see that revoked.badssl.com gives the correct error:

<img width="1032" alt="Screen Shot 2019-11-01 at 9 43 18 AM" src="https://user-images.githubusercontent.com/1903815/68040777-408b4200-fc8c-11e9-8c27-2517e1e93fdf.png">

and I see the same error page for revoked.grc.com:

<img width="995" alt="Screen Shot 2019-11-01 at 9 45 35 AM" src="https://user-images.githubusercontent.com/1903815/68041215-4cc3cf00-fc8d-11e9-88aa-c22cdd1c77fb.png">

**Comment by brokoler** [comment]
Please reopen this issue.
Cert revocation checks are not working with Windows build.

Websites tested:
https://www.grc.com/revocation.htm
https://revoked.badssl.com

All websites are opened, instead Brave should warn based on CRLsets that these are revoked.
