### ISSUE TITLE
Ad matching for ads that are not categorized

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#5183]
## Description 
There are some Brave Ads that we want to be able to serve without having to match against specific categorized content.  There are two use cases here:

1) For our existing content/language models, being able to specify that, if we have nothing in the catalog that fits the content interest, we can show the given ad.
2) For new markets where we are still developing/tuning language models, being able to enter them more quickly by allowing ads to short circuit the content model.

To do this, we should make the following code changes to how the native libraries activate ads:

1) In setting up eligible countries, we should be able to mark them with a special flag that indicates they should short circuit the language model.
2) When it goes to execute content categorization, it should simply inject the "untargeted" category into the list.
3) To use this where we have valid language models but still want to be able to easily enable these ads, we should also inject "untargeted" into the list when we have found no other matching categories.

**Comment by GeetaSarvadnya** [comment]
Ad triggers from parent category: `"technology & computing-software"`

![image](https://user-images.githubusercontent.com/38657976/65790757-efb09700-e17d-11e9-9fb2-f8d2114e9613.png)

**Comment by tmancey** [comment]
This is correct as we first check the parent child and if no match we check the parent and when no ads are found for the parent we check for untargeted ads
