### ISSUE TITLE
Caret mode toggle

### ISSUE THREAD

**Issue by Breina** [brave/brave-browser#5185]
## Description 
Firefox features caret browsing (toggled with F7) which puts a text cursor on the page which can be manipulated with the standard text manipulation keyboard buttons. This feature is vital for ergonomics when since you can omit using the mouse to copy commands from the browser.

## Steps to Reproduce

   1. Press F7

## Actual result:

No caret browsing mode is activated.

## Expected result:

Caret browsing mode is activated.

## Brave version (brave://version info)
0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)

**Comment by mp3foley** [comment]
This now works for me when pressing F7 key.
Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (x86_64)

**Comment by Breina** [comment]
Confirmed. Props to the dev team!

**Comment by AFlyingBird90** [comment]
This caret browsing in accessibility is available in Google Chrome. I wish it will be available in Brave.

**Comment by Breina** [comment]
@AFlyingBird90 You should update update to the newest version. I tested it and it does work.

**Comment by AFlyingBird90** [comment]
> @AFlyingBird90 You should update update to the newest version. I tested it and it does work.

Hey, thanks, I just tested it and it works.
