### ISSUE TITLE
Weird almost bluescreen crash

### ISSUE THREAD

**Issue by mendel3** [brave/brave-browser#5189]
## Description 

I was watching youtube on Brave Dev, and all of a sudden, my browser and Discord crashed at the exact same time. My computer made the looping sound that happens before a bluescreen when there is audio playing and then resolution changed to 1024x768 and the sound stopped. I have attached an event viewer log of the related events, and I noticed that a minute before the crash, the event log reported that I had very little RAM remaining. My laptop is a MSI GX63VR 7RF with a 7700HQ and a 1070. 
I am also reporting this issue to the Discord developers.

## Steps to Reproduce

Unfortunately, I have no idea

## Actual result:
N/A

## Expected result:

N/A
## Reproduces how often: 
N/A

## Brave version (brave://version info)

Brave | 0.68.96 Chromium: 75.0.3770.100 (Official Build) dev (64-bit)
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1803 (Build 17134.829)

## Version/Channel Information:
- Can you reproduce this issue with the current release?
N/A
- Can you reproduce this issue with the beta channel?
N/A
- Can you reproduce this issue with the dev channel?
N/A
- Can you reproduce this issue with the nightly channel?
N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
N/A
- Does the issue resolve itself when disabling Brave Rewards?
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A

## Miscellaneous Information:

I uploaded a crash report with the id of 818b1904b799a4c2. I also have Windows event viewer logs, but am not sure how I can privately send then to you

**Comment by rebron** [comment]
Closing as stale. @mendel3 Let us know if this is still happening on 1.7.x or later.
