### ISSUE TITLE
Chrome logo is shown in chrome://version and default_browser_infobar

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#519]
## Description 
chrome://version
<img width="1058" alt="screen shot 2018-07-10 at 8 25 38 pm" src="https://user-images.githubusercontent.com/4730197/42549139-84186e16-847f-11e8-8245-54c43ffd9a9b.png">

infobar:
<img width="1439" alt="screen shot 2018-07-10 at 5 07 47 pm" src="https://user-images.githubusercontent.com/4730197/42549143-9101f8ae-847f-11e8-8d21-692da8bf4450.png">

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows
