### ISSUE TITLE
eBay image upload broken by shields

### ISSUE THREAD

**Issue by ChildishGiant** [brave/brave-browser#5190]
## Description 
When attempting to upload a photo to a listing on eBay.co.uk, the upload fails with "Upload failed, There was an error uploading this file. Please try again."
![image](https://user-images.githubusercontent.com/13716824/60899776-f86e8c80-a262-11e9-8c79-e7038fc7bfb6.png)

## Steps to Reproduce

   1.  Start a listing at https://www.ebay.co.uk/sl/sell?sr=wnstart
   2. Attempt to upload a local image

## Actual result:
https://gfycat.com/sphericalfaithfulcony
![sphericalfaithfulcony](https://thumbs.gfycat.com/SphericalFaithfulCony-size_restricted.gif)

## Expected result:
Upload to work as usual

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

**Brave**: 0.66.99 
**Chromium**: 75.0.3770.100
**Revision**: cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
**OS**: Windows 10 OS Version 1809 (Build 17763.557)

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not attempted
- Can you reproduce this issue with the dev channel? Not attempted
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by ChildishGiant** [comment]
Also it seems that eBay has a few compat issues 😉 #5019

**Comment by bsclifton** [comment]
I get this one all the time - it should work if you go shields down. Basically, it seems to happen when eBay needs to resize the image (ex: if you upload a smaller image, it should work fine)

@ChildishGiant can you try toggling shields to narrow down what is causing the problem? ex: is it HTTPS upgrading that is blocking it?

**Comment by ChildishGiant** [comment]
It's under 3rd-party trackers

**Comment by ryanbr** [comment]
Hey @ChildishGiant can you confirm everything is working?

**Comment by ChildishGiant** [comment]
All good on my end 😄
