### ISSUE TITLE
Separate JavaScript shields for incognito and general tabs

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#5192]
Currently our JavaScript shields settings applies on both tabs. We need to separate them.

**Comment by simonhong** [comment]
When private window is created, it inherits shields settings from its original profile's.
That means, initial settings are same with original profile when private window is created.
Then, changing shields setting at normal and private window works separately.
This is same as desktop behavior. WDYT? @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
That's awesome. I probably just checked the initial settings. That works!
