### ISSUE TITLE
Block cross-site requests to localhost

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#5193]
As the recent Zoom sitch shows, letting every site make requests to `localhost` is not necessarily the best. We should probably restrict this.

**Comment by diracdeltas** [comment]
i believe this was blocked in muon if you selected the firewall option in prefs: https://github.com/brave/browser-laptop/pull/13119

so it's a parity with muon issue

**Comment by diracdeltas** [comment]
closing as it's being handled via adblock filters now
