### ISSUE TITLE
Re-clicking an ad going to the same landing page should refocus on already open landing page tab

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#5195]
## Description 
When a user already has landing page open from previously clicking and ad or visiting the landing page, we should not create a new tab.  Instead, we should look for open tabs matching the landing page and refocus on that tab.  We should still send the additional click confirmation.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.123 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified Ads with the same URL as an open tab, bring focus to the already opened tab and do not open a new tab
- Verified the confirmations  `View` and `Click` recorded in confirmation.json for the duplicate ad (ad with the same URL)
- Verified `Estimated pending Rewards` amount and `Ads notification received` count reflect in the Ads panel for the duplicate ad
- Verified tokens redeemed at server-side for the duplicate ads also (Used Ephoch TS)
![image](https://user-images.githubusercontent.com/38657976/64321624-86a28d00-cfde-11e9-9dd3-66865c883134.png)
