### ISSUE TITLE
Spoof instead of blocking canvas fingerprinting

### ISSUE THREAD

**Issue by maximbaz** [brave/brave-browser#5196]
## Description 

A blocked canvas fingerprint detection is in itself a fingerprinting method, because regular users don't block this.

Please consider spoofing canvas fingerprinting instead, for example by generating a random noise every time browser is restarted.

## Steps to Reproduce

- https://browserleaks.com/canvas reports "Signature: n/a", but should report a signature that is preserved during page reload, but changed after a browser restart.
- https://www.deviceinfo.me/ reports "Canvas fingerprinting: Blocked" but should report "Spoofed"

Here's a (currently broken) Chrome extension that implemented canvas spoofing: [Canvas Defender](https://chrome.google.com/webstore/detail/canvas-defender/obdbgnebcljmgkoljcdddaopadkifnpm)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Latest stable: 0.66.99 Chromium: 75.0.3770.100 (Official Build)

**Comment by pes10k** [comment]
Closing since this approach is already implemented (see https://brave.com/privacy-updates-4)
