### ISSUE TITLE
customization panel should not be open by default on New Tab page

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#5199]
## Description
Currently, the customization panel is open by default on New Tab page. 
<img width="1509" alt="Screen Shot 2019-07-09 at 5 24 04 PM" src="https://user-images.githubusercontent.com/2388823/60931439-771cf700-a26e-11e9-9cfe-742866dcc364.png">

Fix this so that the panel is not open by default.

**Comment by imptrx** [comment]
The first time someone opens NTP the settings menu would be off. I believe the current behavior you are experiencing is:
- you visit NTP 
- the settings menu is turned on
- you don't close it via clicking outside/button toggle
If that's the case, the menu would persist over to the next NTP session.
If we don't want to preserve the last session of NTP, that would be a different issue altogether, could you confirm if that's the case?

**Comment by rebron** [comment]
@imptrx That's the case. Don't preserve the last session of the settings menu when user opens up a new tab page. Should always show closed.

**Comment by imptrx** [comment]
Test Plan: 
1. Open new tabs page
2. Open customization menu at the bottom right corner 
3. Open another NTP and assert customization menu is closed
4. Close browser with customization menu open; NTP on a fresh browser instance should be closed

**Comment by petemill** [comment]
@imptrx I suggest you use component state and not redux state for the openness of the menu, or just delete the redux property when the redux state is saved to localStorage

**Comment by imptrx** [comment]
> @imptrx I suggest you use component state and not redux state for the openness of the menu, or just delete the redux property when the redux state is saved to localStorage

@petemill I currently have a "close menu" action attached to NTP component mount but I'll probably move that logic out of redux as you suggest 👍

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.115 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/2814
