### ISSUE TITLE
Fingerprint Protection and Block Phishing shields settings are not saved on a domain

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#52]
Fingerprint Protection and Block Phishing shields settings are not saved on a domain

STR
1. Open any page
2. Enable Fingeprint Protection and Block Phishing switch. page doesn't reload with the settings being saved for that page

**Comment by bbondy** [comment]
I think this is probably working now, could you verify @srirambv ?

**Comment by srirambv** [comment]
Yes this is fixed for FP.

**Comment by GeetaSarvadnya** [comment]
Verified on:

Brave | 0.54.2 Chromium: 69.0.3497.42 (Official Build) dev (64-bit)
-- | --
Revision | 9c4613c66dfeb2b76ef6dd4b15884c15db3b4969-refs/branch-heads/3497@{#655}
OS | Windows
JavaScript | V8 6.9.427.14
Flash | 30.0.0.154
