### ISSUE TITLE
Making backup for Brave config/profiles (Windows)

### ISSUE THREAD

**Issue by themattgabriel** [brave/brave-browser#5200]
This is _not_ an issue. I'm using Windows 10. I only have the following questions:

- Is `%USERPROFILE%\AppData\Local\BraveSoftware` the correct path for where the Brave browser config/profiles live?
- If that's the correct path, can I make a copy of everything in that directory as backup?
- Since Brave is Chromium-based, does it have any `Singleton*` files?
- If it does have `Singleton*` files, where are they located so I can add them to my backup excludes list? 

Thank you. 

PS: I will be using WSL to do the backup via rsync.

**Comment by bsclifton** [comment]
- on Windows, that path is correct - there will be a folder in that path for the specific version of Brave you're using (ex: release channel is `brave-browser`, nightly channel is `brave-browser-nightly`). Backing this up is a great idea 😄 

- Yup- there will be `Singleton*` files, just like Chrome

- Singleton* files are at the root of the folder. For example, `%USERPROFILE%\AppData\Local\BraveSoftware\brave-browser\Singleton*`

**Comment by themattgabriel** [comment]
Thank you for clarifying.
