### ISSUE TITLE
Detailed Ad Rewards Summary Log

### ISSUE THREAD

**Issue by samc05** [brave/brave-browser#5202]
## Description 
As a user, I wish to be able to view a detailed log of each advert that appears on my screen. This log would detail the date and time the advert was displayed and the reward received for the advert.

I have found that around payout time, the Estimated pending rewards is not consistent. 
For example:
4th of July, Estimated pending rewards is 15.6 BAT. 
5th of July, Paid out 12.55 BAT, Estimated pending rewards is now 3.05
10th of July, Estimated pending rewards is now 0.6 BAT

I don't know what has happened to the missing BAT and I am 100% certain that I have received more than 14 Adverts in the last 5 days

If the browser provided a log, I would be able to confirm the error.

## Brave version (brave://version info)
Brave | 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

## Miscellaneous Information:
This is more of a feature request than a bug report, as I cannot confirm the missing BAT without the log.

**Comment by kjozwiak** [comment]
Going to close this off as we're already discussing internally on adding more logging information into the browser to make debugging easier for Rewards/Ads. @srirambv added a +1 under #3538. @samc05 please feel free to add your concerns/request into #3538.
