### ISSUE TITLE
Ad notifications should be clearly marked to identify Brave Ads

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#5205]
## Description 

As a User I want to identify Brave Ads as such, and have easily accessible help and unsubscribe links. 

## Steps to Reproduce

   1. Enable Brave Ads
   2. Receive Brave Ad Notification in Windows 10
   3. Open the Notification Bar

## Actual result:

![image](https://user-images.githubusercontent.com/632448/60983841-b13ad700-a308-11e9-980d-db8038c3f8e6.png)

Sidebar:
![image](https://user-images.githubusercontent.com/632448/60984005-f5c67280-a308-11e9-9217-745d13494074.png)

## Expected result:
Clear marking of the notification as a Brave as, and quick links to Rewards settings

## Reproduces how often: 

Every ad

## Brave version (brave://version info)

Version 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)

## Miscellaneous Information:
https://community.brave.com/t/clearly-mark-all-brave-ads-as-brave-ads/69603

**Comment by tmancey** [comment]
Blocked until https://github.com/brave/brave-browser/issues/9592 is implemented

**Comment by tmancey** [comment]
Blocked as issue will be closed once https://github.com/brave/brave-browser/issues/9592 has been implemented

**Comment by tmancey** [comment]
Closing issue as superseded by https://github.com/brave/brave-browser/issues/9592
