### ISSUE TITLE
hide Chromium icons and replace with Brave profile icons

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#5207]
## Description 
Hide Chromium icons and replace with our Brave profile icons.

## Current Experience:
Existing Chromium provided profile icons should not be displayed to our users. 
![Screen Shot 2019-07-10 at 2 42 17 PM](https://user-images.githubusercontent.com/5951041/61007247-329e6380-a321-11e9-8269-96668a0def20.png)

## New Profile icons:
[placeholder, design in progress]

![image](https://user-images.githubusercontent.com/5951041/61007304-59f53080-a321-11e9-8420-26c2281b16da.png)

**Comment by doom777** [comment]
why not?

**Comment by KrackerKarakas** [comment]
I would prefer to simply upload my own icon from my local file system. Please make this an option.

**Comment by rebron** [comment]
@KrackerKarakas Uploading icons or placing them in the right folder so they're picked up in the UI are options we're exploring. We know people want to be able to use their own icons/avatars.

**Comment by bradleyrichter** [comment]
BTW - any people/profile icons you were already using will be retained so that you don't lose your muscle memory for those.

**Comment by CupCakeArmy** [comment]
How does one change the current name or icon? I can only set it wen I create a new profile

**Comment by LaurenWags** [comment]
Per discussion with @rebron this one is `QA/Blocked` until some changes are implemented. @rebron can you provide the follow up issue with the changes once you have it? Thanks!

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.70.117 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3165

**Comment by LaurenWags** [comment]
Removed `QA Pass-Win64` label per discussion with @GeetaSarvadnya since we are still waiting on changes for this issue.

@rebron @petemill any updates to the expected changes?

**Comment by LaurenWags** [comment]
Removing `QA/Blocked` label as we now have a build with https://github.com/brave/brave-browser/issues/6443

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from https://github.com/brave/brave-core/pull/3165
* Confirmed when upgrading: placeholder image is changed, but previously selected images are not
0.69.135:
<img width="1192" alt="3165-1" src="https://user-images.githubusercontent.com/28145373/67413539-5bc0c800-f58f-11e9-9d6d-4338af1932f1.png">

After upgrade to 0.70.121:
<img width="1123" alt="3165-2" src="https://user-images.githubusercontent.com/28145373/67413546-5fece580-f58f-11e9-8058-2d3c61eb3116.png">

* Confirmed Initial profile is created with Brave placeholder

<img width="315" alt="3165-4" src="https://user-images.githubusercontent.com/28145373/67413579-7004c500-f58f-11e9-97b7-8b2d96f3e21b.png">


* Confirmed Subsequent profiles are created with random images

<img width="183" alt="3165 - 3" src="https://user-images.githubusercontent.com/28145373/67413593-77c46980-f58f-11e9-8796-a3971f7eb442.png">
<img width="303" alt="3165-5" src="https://user-images.githubusercontent.com/28145373/67413596-7a26c380-f58f-11e9-86de-bd057d91f25c.png">


* Confirmed User can select brave icons in Settings

<img width="1193" alt="6" src="https://user-images.githubusercontent.com/28145373/67413609-7e52e100-f58f-11e9-8ab1-dfdadec42bdd.png">
<img width="1194" alt="7" src="https://user-images.githubusercontent.com/28145373/67413619-80b53b00-f58f-11e9-9e9b-aee39fb81f52.png">
<img width="342" alt="8" src="https://user-images.githubusercontent.com/28145373/67413622-83179500-f58f-11e9-92e0-b41b747ea634.png">


* Confirmed User can select brave icons in Manage Profiles popup

<img width="794" alt="9" src="https://user-images.githubusercontent.com/28145373/67413630-86ab1c00-f58f-11e9-88f8-325c206eb1f8.png">
<img width="795" alt="10" src="https://user-images.githubusercontent.com/28145373/67413633-87dc4900-f58f-11e9-9736-3ee062722d51.png">
<img width="796" alt="11" src="https://user-images.githubusercontent.com/28145373/67413635-89a60c80-f58f-11e9-9e75-69033539854f.png">
<img width="1194" alt="12" src="https://user-images.githubusercontent.com/28145373/67413641-8b6fd000-f58f-11e9-970e-bc06dd5ea106.png">
