### ISSUE TITLE
Add Profile Manager items to App menu

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#5212]
## Description 
Add Profile Manager items to the hamburger menu.
1) 'Create New Profile' -> creates a new profile and launches into brave://welcome with that new profile.
2) 'Open Guest Window' -> launches into a new Guest Window

## Design
![browser_menu](https://user-images.githubusercontent.com/5951041/62468704-abce9080-b7d1-11e9-92a8-14157fe6a865.png)

**Comment by rebron** [comment]
@bradleyrichter Can we get an updated mock with Extensions pulled out from More Tools and proper re-ordering of Hamburger menu. Let's get it all sorted out with this issue.

**Comment by bradleyrichter** [comment]
@rebron looks good

**Comment by petemill** [comment]
@bradleyrichter @rebron can I ask to confirm the ellipses (or lack of) in the mockup.

`Create a New Profile…` and `Open Guest Window` _(and `New X Window` for that matter)_ all do the same thing - open another window, so I'm not sure why _Create New Profile_ would be the only one ending with an ellipsis. Please could you explain?

**Comment by rebron** [comment]
I believe it means more options will be showing and more info will be needed whereas without the ellipses a user will be going to that thing and no other info is needed.

**Comment by petemill** [comment]
@rebron sure, but in this case the user is not prompted for more information, the new profile simply opens. See the existing macOS system menu Profile - Add Profile option

**Comment by rebron** [comment]
@bradleyrichter We should remove the ellipsis in this case then and it should just be Create a New Profile.

**Comment by GeetaSarvadnya** [comment]
@petemill https://github.com/brave/brave-core/pull/3096 - Would need some clarifications regarding the test plan, should it be as mentioned below?
1. The `Create New Profile` item available only n Normal and Private/Incognito windows Not in Guest and Tor windows 
2. The `Guest Window` item available only in Normal and Private/Incognito windows Not in Guest and Tor windows

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3096
- Verified that `Create a New Profile` from the settings menu launches brave://welcome onboarding flow with a new profile
- Verified `Create New Profile` item available only in Normal and Private/Incognito windows Not in Guest and Tor windows
- Verified `Guest Window` item available only in Normal and Private/Incognito windows Not in Guest and Tor windows
- Verified `Open Guest Window` opens the guest window
- Verified `Create New Profile` and `Open Guest Window` items are in the disabled mode in Guest and Tor windows
