### ISSUE TITLE
update profile manager menu

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#5213]
## Description 
Update profile manager menu.
1) Remove Passwords, Payment methods, Addresses and more
~2) Add 'Create New Profile' -> creates new profile and launches into brave://welcome~ https://github.com/brave/brave-browser/issues/5834
3) Replace 'Manage People' label with 'Manage Profiles'
4) Remove 'Open Tor Window' 

## Design
![image](https://user-images.githubusercontent.com/5951041/61013842-41911000-a339-11e9-9b59-2919fc3b2b3d.png)

**Comment by petemill** [comment]
- [ ] Remove Passwords, Payment methods, Addresses and more
- [ ] Add 'Create New Profile' -> creates new profile and launches into brave://welcome
- [ ] Replace 'Manage People' label with 'Manage Profiles'
- [ ] Remove 'Open Tor Window'

**Comment by petemill** [comment]
@rebron Right now it's difficult to add 'Create New Profile' item without patching chromium quite a bit. However, in the next version of chromium which we'll be rebasing on, the code is much nicer to insert an item in to. So let's separate that in to a different issue. Everything else is catered for in https://github.com/brave/brave-core/pull/3292

**Comment by rebron** [comment]
@petemill Let's add it back when it's easier to insert.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.109 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Verified test plan from the description.

Before upgrade from 0.69.132
![image](https://user-images.githubusercontent.com/34715963/66360535-cc56ca80-e97b-11e9-85eb-6903e9329037.png)
After Upgrade to 0.70.x
![image](https://user-images.githubusercontent.com/34715963/66360598-02944a00-e97c-11e9-985d-12643d9dd21f.png)
