### ISSUE TITLE
date format is not as expected for Locale UK

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5214]
## Description 

date format is not as expected for Locale UK

## Steps to Reproduce

   1.  Clean profile `0.67.106`
   2. Change the locale to UK in `Region & Language` settings 
   3. Launch the browser
   4. date format is displayed as `Aug 5` instead of `5 Aug` in Ads panel, Auto contribution panel and Tips panel

## Actual result:

date formate is displayed as `Aug 5`
![image](https://user-images.githubusercontent.com/38657976/61032670-81aace00-a3df-11e9-9850-5353d0567697.png)

![image](https://user-images.githubusercontent.com/38657976/61032650-78216600-a3df-11e9-8b14-2fa3e87274da.png)

## Expected result:

date formate should be `5 Aug` instaed of `Aug 5`
## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.67.106 Chromium: 75.0.3770.100 (Official Build) beta (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @tmancey

**Comment by tmancey** [comment]
Locale is based off the browser locale and not the system locale, @GeetaSarvadnya can you please recheck and close as a non issue if you agree, thanks

**Comment by GeetaSarvadnya** [comment]
Got confused with OS locale and browser locale. Working as expected hence closing the issue.

@tmancey Thanks for the clarification!

![image](https://user-images.githubusercontent.com/38657976/61037936-b0c63d00-a3e9-11e9-8b73-25af72039cae.png)


Thanks1
