### ISSUE TITLE
Elements not blocked by selector when tab loaded in background

### ISSUE THREAD

**Issue by wooque** [brave/brave-browser#5215]
## Description 
Elements that are blocked by selector are blocked if tab is loaded in current tab, but not if tab is loaded in background.

## Steps to Reproduce

   1. Block any element via selector on any page
   2. Bookmark page
   3. Open that bookmark with 'Open link in new tab'

[more detailed STR in PR]

## Actual result:
Element not blocked when tab opened in background

## Expected result:
Element blocked

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 0.66.99 Chromium: 75.0.3770.100 (Official Build)unknown (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? /

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Reproduced the issue in 0.68.141. 
Verified test plan from https://github.com/brave/brave-core/pull/3121
