### ISSUE TITLE
creator name and favicon not showing on panel and brave://rewards page

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5217]
## Description 
Structure of YT channel page changed, so in some cases YouTube publisher/creator name and/or favicon are not displaying on the panel and brave://rewards page (AC and tips tables).

## Steps to Reproduce

Scenario 1
   1. Clean profile
   2. Enable Rewards (I used staging).
   3. Navigate to https://www.youtube.com/channel/UCD7siefto4I33L4U61IU5LQ
   4. Click on BAT logo. Publisher name is not in panel, you see ' on Youtube' with verified logo/wording. Also, default YT icon is shown.
   5. View a video from this creator. Click on BAT logo. Still creator name is not in panel, you see ' on Youtube' with verified logo/wording. Also, default YT icon is shown.
   6. If you navigate to brave://rewards page, you will see that the AC table (and tips table if you tip the pub) show ' on Youtube' with verified icon as well.

Scenario 2
1. Clean profile
2. Enable Rewards (I used staging).
3. Navigate directly to a video by previous creator: https://www.youtube.com/watch?v=_x80LdPDxIo
4. Click on BAT logo. Creator name is now shown in panel, but default YT icon is shown.
5. If you navigate to brave://rewards page, you will see that the AC table (and tips table if you tip the pub) will show default YT icon.

## Actual result:
![Screen Shot 2019-07-11 at 11 44 41 AM](https://user-images.githubusercontent.com/28145373/61067429-82d6fd80-a3d5-11e9-967e-8b78b2b8e9c5.png)

![Screen Shot 2019-07-11 at 11 44 58 AM](https://user-images.githubusercontent.com/28145373/61067515-b4e85f80-a3d5-11e9-99f3-5e5911fce8d3.png)

## Expected result:
Creator name should always be shown correctly in panel and on brave://rewards. If verified creator (as in the case above) then their specific favicon should be displayed. If not a verified creator, then generic YT favicon should be displayed.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

Brave | 0.67.106 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
reproduced by @kjozwiak

**Comment by GeetaSarvadnya** [comment]
Unable to Reproduce the issue on Windows 10 x65 - `0.67.108` tested on both prod and staging environments.

**Comment by NejcZdovc** [comment]
I can't reproduce either

**Comment by LaurenWags** [comment]
Unable to reproduce now. Possibly YT was doing some testing of this change. Closing issue for now, will reopen if it occurs again.
