### ISSUE TITLE
Improving UX of IPFS in Address Bar

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#5218]
> Related to IPFS Integration - Roadmap and discussion: #819 

# UX challenges

Loading IPFS from public gateways falls under regular HTTP/HTTPS and that is okay.
However when user is running  IPFS node on their own machine (provided by [ipfs-desktop](https://github.com/ipfs-shipyard/ipfs-desktop) or [experimental embedded js-ipfs+chrome.sockets](https://github.com/ipfs-shipyard/ipfs-companion/issues/716)), they effectively replace HTTP with IPFS transport and it would be beneficial if Browser UI reflected that.

#### Current state

When content is loaded from IPFS via HTTP Gateway running on the localhost the UX around address bar is pretty rough:

- URL with IPFS path for a content identified by a [CID](https://docs.ipfs.io/guides/concepts/cid/):
  > ![2019-07-11--15-24-19](https://user-images.githubusercontent.com/157609/61054571-fe45a880-a3ef-11e9-8bb3-7e87ce8cef8c.png)
- URL with IPNS path for a website with [DNSLink](https://docs.ipfs.io/guides/concepts/dnslink/):
  > ![2019-07-11--15-26-52](https://user-images.githubusercontent.com/157609/61054758-64cac680-a3f0-11e9-9451-47caa98a0e59.png)

Problems:

- raw IP of local gateway is highlighted, but it does not provide any meaning to non-technical user
- content identifier (CID) is long, faded-out and takes a lot of space 
- `http://127.0.0.1` location does not make much sense for content-addressed context
- security indicator is confusing:
  Browser assumes regular `http://` (no encryption/integrity guarantees) while IPFS provides a different set of guarantees that are not reflected in UI:
  - transport encryption between you and your peers
  - payload integrity (hashed payload blocks needs to match requested CID)

# Potential improvements

Below are some ideas I discussed with various people (including IPFS Camp).
This is by no means a final design: the goal of this issue is to start the conversation about the UX in address bar and find a sweet spot between what is technically feasible and what would produce good UX. Please provide feedback in the comments.

## Prerequisite: detect requests to local gateway

Brave should be able to tell when local Origin is backed by IPFS.

One way to implement this is to leverage IPFS Companion extension. When it is installed, the address of local gateway can be read from its `browser.storage.local`: the URL is under a key named `customGatewayUrl` (eg. `http://127.0.0.1:8080`).

## (1) Hide local gateway from address bar

Low hanging fruit is to detect that content was loaded from IPFS and change the way address bar shows address to the user. Prior art from [Beaker Browser](https://beakerbrowser.com):
> ![2019-07-11--16-16-39](https://user-images.githubusercontent.com/157609/61058340-5502b080-a3f7-11e9-935c-2cfb1581c9e7.png)

In content-addressed contexts the location of local gateway does not bring any additional meaning. I documented initial exploration of how IPFS addresses could look like if we drop local gateway from the UI:

- We know content comes from trusted local gateway. Let's show only the IPFS path:
![2019-07-11--15-24-19](https://user-images.githubusercontent.com/157609/61056913-85951b00-a3f4-11e9-9ac7-921cb4837783.png)
- CID indicates the content root, so we want to highlight it:
![2019-07-11--15-24-19](https://user-images.githubusercontent.com/157609/61057572-de18e800-a3f5-11e9-952a-60d0e8630d1a.png)
- At the same time CID is not human-readable, so we may just show short version by default:
  ![2019-07-11--15-24-19](https://user-images.githubusercontent.com/157609/61057290-44513b00-a3f5-11e9-8d50-fc44df9da4cd.png)
  which gives more space for content paths after it:
  ![61057290-44513b00-a3f5-11e9-8d50-fc44df9dacd](https://user-images.githubusercontent.com/157609/61064307-d2cbb980-a401-11e9-9eb6-2e029be7cb51.png)
  - for CID we care about first 2 (familiarity) and last 4+ characters 
    (this gives user low quality uniqueness for quick eyeballing)
  - this is similar to what Github does with commit hashes
- Path-addressing can be replaced with regular protocol-looking `ipfs://` and `ipns://` if it makes implementation easier:
  ![61059362-2b4a8900-a3f9-11e9-9f93-8981b86c9d92](https://user-images.githubusercontent.com/157609/61064603-64d3c200-a402-11e9-8e53-9de625053011.png)
  - Note: if this is more than visual tweak and `ipfs://` becomes a real protocol handler, we get proper Origin-based separation per CID and can mark all IPFS pages loaded from local node as [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts)

## (2) Enable user to inspect transport details

Right now the default warning indicator for unencrypted `http://` is displayed, and clicking on it shows this message:

> ![2019-07-11--16-39-21](https://user-images.githubusercontent.com/157609/61060325-a496ab80-a3fa-11e9-83a5-06c55fa17144.png)

Instead, an icon could indicate IPFS transport was used for loading the site:

> ![61059923-21755580-a3fa-11e9-9502-c79ac35cb5c7](https://user-images.githubusercontent.com/157609/61064558-4b327a80-a402-11e9-84e8-4d2a40dc3c23.png)

Clicking on it could open small popup informing user about IPFS details.
Initially it could be info about the gateway we removed from address bar:

> ![2019-07-11--16-39-21](https://user-images.githubusercontent.com/157609/61067102-1aa10f80-a407-11e9-837d-4ec80caf4a71.png)

For the MVP just showing the URL of local gateway should be enough. In the future this popup could be a place that shows more details about the protocol, eg. include information about payload integrity, type of encrypted transports, state of peers, DHT (public/private) etc. 

-----

@bbondy  @yrliou @autonome @olizilla

**Comment by RubenKelevra** [comment]
This is superseeded by recent changes in the IPFS-Daemon/IPFS-Plugin and can be closed. :)
