### ISSUE TITLE
Add a way to forget "Shields Down" on exit

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#5224]
@BrendanEich mentioned that he forgot a site on "Shields Down" and so didn't think of reporting it as a webcompat bug. If we had an option to clear the "Shields Down" state at browser exit, we could ensure that this doesn't happen and that we more easily notice the unfixed webcompat issues.

Maybe that could be added to Clear Private Data on exit:
![Screenshot from 2019-07-11 12-53-29](https://user-images.githubusercontent.com/167821/61080908-ea437c00-a3da-11e9-89c3-2ece8aff0ace.png)

or maybe it's already part of "Site settings"?

**Comment by bsclifton** [comment]
@fmarier it should be part of Site Settings already. Do you think having a more granular option makes sense?

**Comment by fmarier** [comment]
Ah interesting. It does seem to work, however I note two things:

- Clearing "Site Settings" also removes Slack's desktop notifications permission.
- The number of sites underneath the "Site Settings" heading does not include any settings from Shields. For example, in my case, it showed "1 site" whereas it should have been 2 (slack permission, override for `gs.statcounter.com`).

**Comment by fmarier** [comment]
I will file a separate issue for the counter, but we can close this one as a dupe of #3926.
