### ISSUE TITLE
Shields site settings are not included in the "site settings" counter

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#5225]
## Description 
The number of sites shown under "Site Settings" in the Advanced tab of `chrome://settings/clearBrowserData` does not include any Shields override added by a user even though those will get cleared.

## Steps to Reproduce

1. Open `chrome://settings/clearBrowserData` and clear Site Settings in Advanced (All time).
2. Open Slack and give it the permission to do desktop notifications.
3. Open http://gs.statcounter.com/ and click on Shields Down.
4. Visit `chrome://settings/clearBrowserData`.

## Actual result:
1 site:

![Screenshot from 2019-07-11 14-34-00](https://user-images.githubusercontent.com/167821/61086902-f7676780-a3e8-11e9-93f0-3e81cab84ea8.png)

## Expected result:

2 sites

## Reproduces how often: 

Perfectly reproducible.

## Brave version (brave://version info)
```
Brave	0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)
Revision	cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS	Linux
```

**Comment by rebron** [comment]
@tomlowenthal Should we have shield settings have its own listing here instead of bundling it with site settings?

**Comment by fmarier** [comment]
> Should we have shield settings have its own listing here instead of bundling it with site settings?

There's already a bug (from Tom) for that (#3926) and if we decided to do that then we wouldn't have to fix the incorrect count.

**Comment by tomlowenthal** [comment]
Closing this in favor of #3926. Let me know if that doesn't seem right.
