### ISSUE TITLE
contribution does not go thru in some cases - follow up to 3707, 4090

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5230]
## Description 
Follow up to https://github.com/brave/brave-browser/issues/4090, https://github.com/brave/brave-browser/issues/3707 and https://github.com/brave/brave-core/pull/2208

In the issues described above, the PR made it so that if your wallet balance covers the contribution/recurring tips for verified sites, you won't get the Insufficient funds message. However, in this case your contribution will not go through. Per the issues above, especially #3707, I was expecting the AC and recurring tips to go thru and be deducted from my balance accordingly, however, this did not happen.

## Steps to Reproduce

1. Start Brave clean profile with `--rewards=reconcile-interval=20,staging=true` (or some other value less than 4320 [3 days])
2. Visit a mix of verified and unverified sites. Add at least two recurring monthly tips - one for verified site and one for unverified site.
3. Accept grant (at present time 30 BAT)
4. Go to Rewards page and set AC budget to 50 BAT
5. Quit browser and restart to reinitiate timer
6. Wait a few moments and make sure that you don't see 'Insufficient Funds' notification
7. Make sure that your wallet balance (mine is 30 BAT) will cover the contribution to verified sites in AC and recurring tips.
8. Wait until contribution happens.

## Actual result:
Contribution does not go thru. 
In my case I had a wallet balance of 30 BAT and a monthly budget of 50 BAT.
My amount for auto-contribution to verified sites is 22.5 BAT.
My amount for recurring monthly tips to verified sites is 1 BAT.
In total, they are less than 30 BAT (22.5 + 1 = 23.5)

![Screen Shot 2019-07-12 at 12 21 56 pm](https://user-images.githubusercontent.com/28145373/61143986-aff0e200-a4a1-11e9-83a3-e58b09392b86.png)

![Screen Shot 2019-07-12 at 12 22 57 pm](https://user-images.githubusercontent.com/28145373/61144000-b5e6c300-a4a1-11e9-8ba2-67bf37b97759.png)

However, my contribution did not go thru:
![pr2208](https://user-images.githubusercontent.com/28145373/61144006-b97a4a00-a4a1-11e9-9477-ee9714e5981c.gif)

## Expected result:
My AC and recurring tip contributions to verified pubs should have been deducted from my wallet balance and displayed in my transactions accordingly, leaving me with 6.5 BAT remaining in my wallet (30-22.5-1 = 6.5) and 32.5 BAT in pending contributions. (pending contribution number comes from 27.5 BAT for unverified publishers in AC and 5 BAT for monthly recurring tip to unverified publisher)

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.67.108 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @brave/legacy_qa @NejcZdovc @mandar-brave @alexwykoff

**Comment by LaurenWags** [comment]
note - I did confirm that a "normal" contribution - that is, when monthly budget and total of all recurring tips is less than wallet balance - goes thru as expected.
![contrib](https://user-images.githubusercontent.com/28145373/61144852-0bbc6a80-a4a4-11e9-90d4-f068a999a6dd.gif)

**Comment by NejcZdovc** [comment]
@LaurenWags this is not a bug, we still didn't decide what to do with it and the current logic is correct one

**Comment by LaurenWags** [comment]
so we removed the informative notification - the one telling you why your contribution wouldn't go thru? that seems like an odd choice.

**Comment by NejcZdovc** [comment]
@LaurenWags no, we didn't remove this notification. Insufficient notification checks for an actual contribution and it doesn't just do AC amount + recurring. It actually checks for verified in AC and verified in recurring list and compare it to your balance

**Comment by NejcZdovc** [comment]
@LaurenWags I think this is not a problem anymore as we completely changed how monthly contribution works. Can we close it?

**Comment by LaurenWags** [comment]
@NejcZdovc yes, I think we can close this one due to the re-working of AC/recurring tips.
