### ISSUE TITLE
Update Crypto Wallet icons in settings toolbar

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#5235]
Crypto Wallets is currently using settings icon. Should be updated to be a crypto wallet icon. 

![image](https://user-images.githubusercontent.com/29072694/61162776-251ee000-a4bf-11e9-8d5b-e81d77bac0f0.png)

**Comment by bsclifton** [comment]
@rossmoody was this closed with https://github.com/brave/brave-core/pull/2912?

**Comment by rossmoody** [comment]
@bsclifton Looks like at the moment the icon is being served in two places so I think the latest PR should close it.
