### ISSUE TITLE
Downloading PDF using Keyboard Shortcut

### ISSUE THREAD

**Issue by alapo** [brave/brave-browser#5236]
*Feature Enhancement Suggestion*
Love the browser, wanted to submit a request for an enhancement. 
A shortcut for "Download PDF" as shown in the image below would be very useful. Not sure if anyone has accomplished a workaround using AutoHotKey.

![img](https://i.imgur.com/Ltr26YZ.png)

**Comment by rebron** [comment]
We have a new pdf version using pdfium (vs pdfjs). It's in dev channel now. Closing and can reopen if there's still a shortcut issue using pdfium.
