### ISSUE TITLE
When installed as normal user, two windows open after install

### ISSUE THREAD

**Issue by traffisco** [brave/brave-browser#5239]
## Description 

When installed as normal user, two brave browser windows open after install.
One welcome page window and another one with new tab.

## Steps to Reproduce

   1. Delete installed brave browser if already installed
   2. Run installer in normal user mode(I actually set the needsadmin=False parameter in the installer meta tag)

## Actual result:

Two brave browser windows open after install.

## Expected result:
Only one browser window should open with welcome page.

## Reproduces how often: 

On fresh installs only. Need to remove old install first

## Brave version (brave://version info)

All versions

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Yes
- Can you reproduce this issue with the dev channel?
Yes
- Can you reproduce this issue with the nightly channel?
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
Yes

**Comment by traffisco** [comment]
Passing --do-not-launch-chrome to the installer(omaha server install action) solves it

**Comment by bsclifton** [comment]
@traffisco that is a great work-around that I used in the past (when automating the install of Brave Core from the Muon version of the product) 😄On our side, we could adjust the builds to embed this as a tag when creating the Omaha installers for folks. I forget what the behavior is when needsAdmin=true though...

**Comment by kjozwiak** [comment]
Closing in favour of https://github.com/brave/brave-browser/issues/1833.
