### ISSUE TITLE
Exception rules in custom filters don't work.

### ISSUE THREAD

**Issue by scorpion1201** [brave/brave-browser#5240]
## Description 

Exception rules in custom filters don't work.

## Steps to Reproduce

   1. Install Brave Browser.
   2. Add a exception rules in a custom filter box on `brave://adblock`
   3. Visit the site for which the custom filter was added, be still blocked!

## Actual result:

Exception rules in custom filters don't work.

## Expected result:
Exception rules work well.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
N/A
- Can you reproduce this issue with the dev channel?
N/A
- Can you reproduce this issue with the nightly channel?
N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
N/A
- Does the issue resolve itself when disabling Brave Rewards?
N/A
- Is the issue reproducible on the latest version of Chrome?
N/A

**Comment by bsclifton** [comment]
@scorpion1201 do you have an example of the rule you tried?

cc: @ryanbr

**Comment by scorpion1201** [comment]
Yes, the exception rule to blocked filters on 'tv.kakao.com' is below.
``@@||t1.daumcdn.net/tiara/js/v1/tiara.min.js``

It's not working!

**Comment by scorpion1201** [comment]
@bsclifton 

Yes, the exception rule to blocked filters on 'tv.kakao.com' is below.
``@@||t1.daumcdn.net/tiara/js/v1/tiara.min.js``

It's not working!

**Comment by ggirard07** [comment]
Same issue here with an exception rule...
But as this is my first custom filter, I am not sure if this is actually an issue or a bad usage from myself...

**Comment by ggirard07** [comment]
Wondering if this issue could be linked in any way to https://github.com/brave/adblock-lists/pull/45

**Comment by bsclifton** [comment]
cc: @ryanbr @pes10k

**Comment by pes10k** [comment]
thank you for the issue.  Closing in favor of https://github.com/brave/brave-browser/issues/5440

**Comment by efolio** [comment]
Any news on this… I still have the issue…

**Comment by pes10k** [comment]
@efolio the live version of this issue is https://github.com/brave/brave-browser/issues/5440, but as good news, its coming up next in our queue, so we hope to have an answer soon
