### ISSUE TITLE
Tab specific socks proxy

### ISSUE THREAD

**Issue by changesgnationalservice** [brave/brave-browser#5244]
## Description 
Suggestion - Would the dev team be able to add in tab-specific http/socks proxy for each tab when on incognito mode?

## Steps to Reproduce
NA

## Actual result:
NA

## Expected result:
NA

## Reproduces how often: 
NA

## Brave version (brave://version info)
Latest

**Comment by bsclifton** [comment]
cc: @riastradh-brave

**Comment by tomlowenthal** [comment]
Sorry, we're not building features which put tabs in different security or privacy context. It's just too error prone, and relying on people never to make mistakes is an unreasonable ask.
