### ISSUE TITLE
Rewards : Reddit : Tipping interaction not shown on comments if user is not logged in

### ISSUE THREAD

**Issue by alexwykoff** [brave/brave-browser#5259]
## Description 
Reproduced on 0.69.44 (Nightly)

When observing the tip interaction on Reddit, it was noticed that logged out users do not see the tip interaction on comments. Logged in users can see the interaction.

## Steps to Reproduce

   1.  Visit a thread on Reddit as a logged in user.
   2.  Observe the tip interaction on comments.
   3.  Log out of Reddit.
   4. Observe the lack of tip interaction on comments.

## Actual result:
Tip interaction not shown.

## Expected result:
Tip interaction is shown.

## Reproduces how often: 
Reproduced on multiple machines with same STR.

## Brave version (brave://version info)
0.69.44 (Nightly) MacOS was used on either device.

## Version/Channel Information:
Currently only tested on Nightly.

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

**Comment by masparrow** [comment]
So, my findings are that when you are not logged into Reddit, there are no 'actions' along the bottom of the Comments, these are used to hang the 'Tip' button (when logged in). 

Logged in:
![Screenshot 2019-09-26 at 16 57 02](https://user-images.githubusercontent.com/11368284/65710713-759fe580-e08b-11e9-829a-d8cc5fe4dbe5.png)

Logged out:
![Screenshot 2019-09-26 at 16 58 39](https://user-images.githubusercontent.com/11368284/65710738-7df82080-e08b-11e9-8932-b5755656910a.png)

@NejcZdovc I'd imagine we need to get design involved here?

**Comment by NejcZdovc** [comment]
@alexwykoff @jenn-rhim what we would like to do?

**Comment by NejcZdovc** [comment]
closing as stale
