### ISSUE TITLE
promoCode file and Brave folder created when downloading .pkg file for channels other than Release

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5264]
## Description 
Found while testing #4519 and per comment from @emerick could be related to https://github.com/brave/brave-browser/issues/4600 as well.

When Nightly, Dev, Beta are installed from .pkg file, an extra `Brave` folder is created under `BraveSoftware` (`~/Library/Application Support/BraveSoftware`) which contains a promoCode file. This shouldn't happen as per discussion on #4519.

## Steps to Reproduce

   1. Make sure you don't have Nightly installed.
   2. Install latest Nightly from .pkg file.
   3. Navigate to `~/Library/Application Support/BraveSoftware`.
   4. You will see a `Brave` folder here, and in it, a promoCode file that says  "Browser-Nightly". 
   5. Repeat for Dev and Beta channels.

## Actual result:

![Nightly](https://user-images.githubusercontent.com/28145373/61325270-57438100-a7e2-11e9-92f5-213d453cc96f.png)

## Expected result:
No extra `Brave` folder with promoCode file.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.49 Chromium: 75.0.3770.100 (Official Build)nightly (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

Brave | 0.68.98 Chromium: 75.0.3770.100 (Official Build) dev(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

Brave | 0.67.106 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, does not occur on Release channel
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @aekeus @emerick @kjozwiak

**Comment by kjozwiak** [comment]
@rebron probably something we want fixed before `0.67.x` moves into release. We definitely don't want the `pkg` executables creating `~/Library/Application Support/BraveSoftware/Brave` folders that include a `promoCode` file with the channel being installed. Could cause issues down the road.

**Comment by kjozwiak** [comment]
Verification **PASSED** using the following build:

Brave | 0.71.66 Chromium: 76.0.3809.132 (Official Build) nightly (64-bit)
--- | ---
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* installed Brave using `Brave-Browser-Nightly.pkg` and ensured that `promoCode` wasn't created under `Brave-Browser`
* installed Brave using `Brave-Browser-Nightly-KAM527.pkg` and ensured `promoCode` was created via `/BraveSoftware/Brave-Browser-Nightly` (checked `brave://local-state and ensured `KAM527` was being used)
* installed Brave using `Brave-Browser-Nightly-foo-bar.pkg` and ensured `promoCode` was created via `/BraveSoftware/Brave-Browser-Nightly` (checked `brave://local-state and ensured `foo-bar` was being used)
* ensured that `promoCode` was removed when Brave launched

Brave | 0.70.89 Chromium: 76.0.3809.132 (Official Build) dev (64-bit)
--- | ---
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* installed Brave using `Brave-Browser-Dev.pkg` and ensured that `promoCode` wasn't created under `Brave-Browser`
* installed Brave using `Brave-Browser-Dev-RED194.pkg` and ensured `promoCode` was created via `/BraveSoftware/Brave-Browser-Dev` (checked `brave://local-state and ensured `RED194` was being used)
* installed Brave using `Brave-Browser-Dev-foo-bar.pkg` and ensured `promoCode` was created via `/BraveSoftware/Brave-Browser-Dev` (checked `brave://local-state and ensured `foo-bar` was being used)
* ensured that `promoCode` was removed when Brave launched

Brave | 0.69.122 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
--- | ---
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* installed Brave using `Brave-Browser-Beta.pkg` and ensured that `promoCode` wasn't created under `Brave-Browser`
* installed Brave using `Brave-Browser-Beta-KJO037.pkg` and ensured `promoCode` was created via `/BraveSoftware/Brave-Browser-Beta` (checked `brave://local-state and ensured `KJO037` was being used)
* installed Brave using `Brave-Browser-Beta-foo-bar.pkg` and ensured `promoCode` was created via `/BraveSoftware/Brave-Browser-Beta` (checked `brave://local-state and ensured `foo-bar` was being used)
* ensured that `promoCode` was removed when Brave launched

**Comment by kjozwiak** [comment]
@emerick two quick questions regarding the above fix:

* `Brave-Browser-Nightly-foo-bar.pkg` seems to be working but should `Brave-Browser-Nightly-red-194.pkg` or `Brave-Browser-Nightly-RED-194.pkg` also work? In both cases, the `promoCode` file and associated directories are not being created

* When there's no `promoCode` in the filename, we're using `BRV001` as the default, is this expected behaviour? I remember us adding default referral codes but double checking in case something changed.

**Comment by emerick** [comment]
Hi @kjozwiak No, neither RED-194 nor red-194 should be considered a promo code. The only valid promo codes are in one of two formats:

1. XXXYYY, where X is any letter and Y is any number and the entire promo code is 6 characters long
2. XXXXX-XXXXX where X is any letter (no digits allowed) and there is no length limit in either component

And yep, we use `BRV001` as the default promo code now. See https://github.com/brave/brave-browser/issues/2547 for more details.

**Comment by kjozwiak** [comment]
awesome, thanks @emerick 👍
