### ISSUE TITLE
PDF viewer URL shows chrome extension

### ISSUE THREAD

**Issue by rislam** [brave/brave-browser#5266]
## Description 

PDF url is adding prefix `chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/` for every PDF

## Steps to Reproduce

   1. click any available pdf for viewing i.e. https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf
   2. The URL will now become `chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf`
 

## Actual result:

<img width="688" alt="Screen Shot 2019-07-16 at 10 30 47 PM" src="https://user-images.githubusercontent.com/1030787/61349592-845f5600-a819-11e9-92a3-2d0e85eaa1a2.png">

## Expected result:
The expected result should remove the `chrome-extension://oemmndcbldboiebfnladdacbdfmadadm` part from the viewer

## Brave version (brave://version info)

Brave | 0.66.100 Chromium: 75.0.3770.142 (Official Build) (64-bit)
-- | --
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Mac OS X
JavaScript | V8 7.5.288.30
Flash | 32.0.0.223 /Library/Internet Plug-Ins/PepperFlashPlayer/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=NewExtensionUpdaterService,DesktopPWAWindowing --disable-features=AudioServiceOutOfProcess,UnifiedConsent,NetworkService,AutofillSaveCardSignInAfterLocalSave,DefaultEnableOopRasterization,LookalikeUrlNavigationSuggestionsUI,AutofillServerCommunication,TranslateUI --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | ~/Library/Application Support/BraveSoftware/Brave-Browser/Default
Variations | 5040e8a-5040e8ac134752e-f685ead32c707b42-dcf7018a411b6d4e-3f4a17dfd01ab0d3-60c33fc08927cedd-3f4a17df16e0dd70-3f4a17dfba11b117-5b05287a4ca682fe-3f4a17df551157b-3f4a17dff88a4127-2874767e4b8c3f4-3f4a17dfb7e2524c-c92d551c411c711e-3f4a17df8f029c91-3f4a17df8982496f-3f4a17df61832c80-3f4a17dfcc20827f-77c422c9853922b-3f4a17df776de70c-e0278d3ded9149a9-3f4a17dfc70841c8-a256700714bdbe54-e8c7a65bd8343fa3-3f4a17dfb517d646-3f4a17df8ee5ed19-c3125ea274658432-fa79b94c4f9b5d89-3f4a17dfaacdc39d-80f9a33ec36cdb78-3f4a17df5274eb09-3f4a17dfd6d4ee9a-3f4a17df2729b628-3f4a17df44827ee5-3f4a17df332a4d9b-8e8e4a2b6a116980-3f4a17df3f79ac13-3d47f4f48f1e27f-3f4a17df6cb3969e-3f4a17df40de7b13-1aa41b589b4c4257-3f4a17df43f62d3b-3f4a17df9e5c75f1-30e1b12b2594bdf4-3f4a17df6fa07eb4-7282ca762981bcb4-3f4a17df5139837c-3f4a17df4934552d-3f4a17df7f8176d9-3f4a17df73a8d7f1-1b1a79086c66bd8d-b204717823a898eb-fc93cf747a5ba892-3f4a17dfd1cd70a5-3f4a17df4ea303a6-3f4a17dfac8d4708-5460eccbb19465ab-b19465ab6e6e0c7e-3f17a7d895876445-2b71ffe42b33233e-881ca6c94da5ae82-3f4a17df56302f8c-2f882e70fd56acdf-3f4a17dfb2612322-8a9180b23dba712-a2d707c6ad6d27cc-85d38e8dcec9a952-9a6c5085f56e0452-3f4a17df8576baf1-3f4a17df2e7f6029-88947c67d00fcbde-3f4a17dfd840bbac-3f4a17df930e30f5-3f4a17df732f0134-3f4a17df9a2f4e5b-9ded16b91354da85-522c33b8494d8760-3f4a17dff9e5da91-508355f5b1ceb06f-6b7b34db0ea13bc-3f4a17df47a2af3f-3f4a17df94e68624-803f8fc4cc73f8a1-3f4a17df7e91b7bd-c6da37cb6204e469-3f4a17df41ddf744-c78ce173

## Version/Channel Information:

- Can you reproduce this issue with the current release? **Yes**
- Can you reproduce this issue with the beta channel? **I haven't tried it**
- Can you reproduce this issue with the dev channel? **I haven't tried it**
- Can you reproduce this issue with the nightly channel? **I haven't tried it**

**Comment by jeroen7s** [comment]
This is normal behavior because of the PDFjs plugin they use
should be gone after the switch to PDFium -> https://github.com/brave/brave-browser/issues/3846
should be in beta/stable soon

**Comment by bsclifton** [comment]
Yup- you are correct, @jeroen7s 😄 Closing as this is fixed in developer channel (will be in release/stable on Aug 20th)
