### ISSUE TITLE
Disable gaia in brave-core

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#527]
On startup, Brave gets a list of the google accounts from gaia, which connects to accounts.google.com. Disable gaia to avoid these connections.

**Comment by diracdeltas** [comment]
could you list which domains are from gaia?  i'm seeing some which might not be

**Comment by diracdeltas** [comment]
can this issue be fixed by setting the gaia URL constants to `about:blank`?

**Comment by jumde** [comment]
That might be a good solution, there may be side effects though. I can take a shot at this.

**Comment by jumde** [comment]
No connections are made to the gaia domains on `browser-laptop`

**Comment by notDavid** [comment]
fyi, on 0.55.2 i see (after installing, on first startup, without any browsing):

```
www.gstatic.com
ssl.gstatic.com
www.googleapis.com
updates.googleapis.com
clients2.google.com
accounts.google.com
clients2.googleusercontent.com
```
[(See screenshot here)](https://gist.githubusercontent.com/notDavid/6a98e98be19667f771dd53f96dc59d5b/raw/6b81a451efc6967190c4cc596d25d182b2f05c58/Screenshot%25202018-09-08%2520at%252023.07.50.png)

**Comment by bbondy** [comment]
Gaia URL will effectively always go to no-thanks.invalid which is a non resolve-able invalid host.
I'll keep this issue open for now though so we can work on seeing if we can not even compile the gaia code.

**Comment by LaurenWags** [comment]
Using 

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

This is what I see with LittleSnitch:
![screen shot 2018-10-16 at 3 00 44 pm](https://user-images.githubusercontent.com/28145373/47040622-aa55ae00-d154-11e8-8ec6-137249f1b199.png)

**Comment by diracdeltas** [comment]
@LaurenWags i think those are all for extension updates (PDFJS), not Gaia related. 

cc @tomlowenthal

**Comment by tomlowenthal** [comment]
Per discussion in slack, we're planning to serve PDFJS from the go-updater server rather than letting the browser connect to Google.

**Comment by tomlowenthal** [comment]
Moved this PDFJS sitch to its own issue: #1669 (nice).

**Comment by fusionneur** [comment]
Sorry if not posting in the right issue, but i saw this old one still open so I thought it would be good to share my findings from 2020. Brave still opens connections even with addons disabled and safebrowsing disabled, as follows:

upon startup:
	+p.ssl.fastly.net / 199.232.197.7 / 199.232.193.7(on startup + 1 minute after + on quit)
	+update.googleapis.com / 172.217.18.67, 216.58.214.227
	+dualstack.f4.shared.global.fastly.net / 151.101.2.110 / 151.101.194.110 (on startup + on quit?)

seen rarely at random times:
	+play.google.com
	+www.gstatic.com / 172.217.18.67
	+ssl.gstatic.com
	+googlehosted.l.googleusercontent.com
	+gstaticadssl.l.google.com

**Comment by bsclifton** [comment]
cc: @jumde on above comments

We should be blocking GAIA, unless you have the `Allow Google login for extensions` option enabled. When it is used, it will be proxied. DICE (browser login) should be disabled

Should this be closed?

**Comment by jumde** [comment]
This is controlled by the flag `Allow Google login for extensions`, which is disabled by default.
