### ISSUE TITLE
combine Trackers Blocked and Ads Blocked on NTP

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#5273]
## Description 
On the new tab page, Trackers Blocked and Ads Blocked should be combined into a single count and labeled appropriately. For the backend, tracking-protection lib will move into the ad-block lib so good time to simplify and relabel this metric.

## Current result:

<img width="779" alt="Screen Shot 2019-07-17 at 11 44 07 AM" src="https://user-images.githubusercontent.com/5951041/61402543-36ce0200-a888-11e9-8d9e-b6707d0119e0.png">

## Expected result:
Single metric with label
[Count]
Ads & Trackers Blocked

**Comment by rebron** [comment]
cc: @tomlowenthal for label text for this metric.

**Comment by tomlowenthal** [comment]
I'd like to just collapse into "Trackers blocked".

**Comment by EyanGoldman** [comment]
Question that is probably unlikely, but what happens when you get to 1M + ads blocked, do the numbers dynamically shift to make space? Is there a risk of overlapping? This is especially relevant if we are merging ads and trackers as that number will grow much faster...

**Comment by cezaraugusto** [comment]
@EyanGoldman yes, the stats row expands to fit larger numbers

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.68.118 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

* Verified with clean profile:
![Screen Shot 2019-08-05 at 6 04 28 PM](https://user-images.githubusercontent.com/28145373/62498115-24baf180-b7ac-11e9-9d96-949d5e471671.png)
* Verified with upgraded profile. This is from 0.67.x:
![Screen Shot 2019-08-05 at 6 08 00 PM](https://user-images.githubusercontent.com/28145373/62498138-313f4a00-b7ac-11e9-9670-09da28a75841.png)
And after upgrading to 0.68.x the Ads/Trackers were combined as expected:
![Screen Shot 2019-08-05 at 6 08 59 PM](https://user-images.githubusercontent.com/28145373/62498155-3d2b0c00-b7ac-11e9-88e8-667c6ab701b4.png)
