### ISSUE TITLE
npm audit failure

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#5274]
```
18:33:46  NETWORK AUDIT FAIL: http://redirector.gvt1.com/edgedl/release2/chrome_component/MqW12EitHyhz-XzwLwmB3w_5275/EiI3phPlDF5Vw5uzk0UNbQ
18:33:46  NETWORK AUDIT FAIL: http://redirector.gvt1.com/edgedl/release2/chrome_component/MqW12EitHyhz-XzwLwmB3w_5275/EiI3phPlDF5Vw5uzk0UNbQ
18:33:46  NETWORK AUDIT FAIL: http://r4---sn-nx5s7n7s.gvt1.com/edgedl/release2/chrome_component/MqW12EitHyhz-XzwLwmB3w_5275/EiI3phPlDF5Vw5uzk0UNbQ?cms_redirect=yes&mip=52.34.19.133&mm=28&mn=sn-nx5s7n7s&ms=nvh&mt=1563355817&mv=m&mvi=3&pl=14&shardbypass=yes
```

### Test Plan

Specified here: https://github.com/brave/brave-core/pull/2942

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
-- | --
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2942
* Verified no connections to `*.gvt1.com` on clean profile:
![Screen Shot 2019-07-22 at 3 51 02 PM](https://user-images.githubusercontent.com/28145373/61661051-37580580-ac99-11e9-9161-466d281332fb.png)
* Verified CRLSets updated on `brave://components`
![Screen Shot 2019-07-22 at 3 51 36 PM](https://user-images.githubusercontent.com/28145373/61661078-450d8b00-ac99-11e9-8da2-4488336920b4.png)
