### ISSUE TITLE
URL is hidden when searching

### ISSUE THREAD

**Issue by leggett** [brave/brave-browser#5283]
## Description 
When I search Google, the URL is hidden showing only my search term. This is redundant with the search box on the page (see attached screenshot) and hides the URL making sharing the results page harder. I finally found how I can right click on the URL bar and select "Show URL" but this is hard to find and annoying. 

## Steps to Reproduce

   1. Do a search in the URL bar with Google set as the default search engine
   2. Observe the URL is not shown. Instead, only the search is shown.
   3. Right click on the URL bar and select "Show URL" to see the URL

## Actual result:

<img width="850" alt="Screen Shot 2019-07-18 at 8 17 48 AM" src="https://user-images.githubusercontent.com/8763662/61480347-a6a4c100-a94a-11e9-8d5e-d85316c868fc.png">

## Expected result:

The URL is shown as it is with other search engines and in Chrome making sharing the results really easy.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Haven't tested
- Can you reproduce this issue with the dev channel? Haven't tested
- Can you reproduce this issue with the nightly channel? Haven't tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by rebron** [comment]
Hi @leggett thanks for filing. I verified that we have this fixed in 68.x. I believe it was via https://github.com/brave/brave-browser/issues/4283

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.68.114 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

* Installed 0.67.123 (current release version) and verified I could reproduce the issue. Using 0.68.114 verified I did not see the issue.
![Screen Shot 2019-08-01 at 5 47 43 PM](https://user-images.githubusercontent.com/28145373/62329675-916c7e00-b484-11e9-9a21-de4feefb2cc3.png)

**Comment by jacobjuul** [comment]
is there a way to disable this behaviour in version 0.67 ?

**Comment by LaurenWags** [comment]
@jacobjuul this will be fixed in 0.68.x, which is currently expected to be released next week. There will not be a fix for it in 0.67.x.

**Comment by bsclifton** [comment]
@jacobjuul I believe you can visit:
chrome://flags/#omnibox-ui-hide-steady-state-url-path-query-and-ref

And then choose `Disabled`. As @LaurenWags mentioned, we'll also have a release next week fixing it 😄 (changing it to disabled ahead of time won't break anything)

**Comment by jacobjuul** [comment]
@bsclifton I thought so, but unfortunately it doesn't

**Comment by svasil** [comment]
> @jacobjuul I believe you can visit:
> chrome://flags/#omnibox-ui-hide-steady-state-url-path-query-and-ref
> 
> And then choose `Disabled`. As @LaurenWags mentioned, we'll also have a release next week fixing it 😄 (changing it to disabled ahead of time won't break anything)
It doesn't help in Brave Version 0.67.125 Chromium: 76.0.3809.100
