### ISSUE TITLE
Brave crashes a lot

### ISSUE THREAD

**Issue by PunnyBoi** [brave/brave-browser#5288]
## Description 

The latest version of the brave browser is crashing a lot. It particularly happens when I open youtube. It starts lagging and then it doesn't respond. Soon after that, it crashes. I checked in the task manager how much memory it takes when it shows such behaviour. The memory shoots from 400 MB to 2 GB in almost 5 seconds. The CPU usage also increases. 

## Steps to Reproduce

   1. Open youtube.com.
   2. After 5 seconds, brave starts not responding.

## Reproduces how often: 

Intermittent issue

## Brave version (brave://version info)

0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@PunnyBoi Can you provide more details on your platform, OS and OS version?

**Comment by rebron** [comment]
@PunnyBoi Also, can you check brave://crashes paste the crash id here as well as sending over the crash report.

**Comment by kjozwiak** [comment]
@PunnyBoi thanks for the information! Unfortunately, the above `id`'s are only the local ones. You'll need to submit the report to us which will create a `Crash Report ID`.

Example of a report that hasn't been reported:

<img width="481" alt="Screen Shot 2019-07-19 at 11 19 23 AM" src="https://user-images.githubusercontent.com/2602313/61548179-0e2a4180-aa1b-11e9-9ef5-aec1b811f2b2.png">

Example of a report that has been reported and uploaded:

<img width="697" alt="Screen Shot 2019-07-19 at 11 19 35 AM" src="https://user-images.githubusercontent.com/2602313/61548178-0e2a4180-aa1b-11e9-9594-fb422f59a002.png">

@PunnyBoi once you've submitted the reports, can you reply with `Crash Report ID`? Thanks!

**Comment by PunnyBoi** [comment]
Sure.

1) Crash Report ID 43f2cb190e3ebc27 (Local Context: d9b05d04-f9cb-4a7f-8016-777efc52310b)
2) Crash Report ID d4a6286f9bebfe19 (Local Context: 4914e2af-8a36-4a30-84dc-f524d92f41a0)
3) Crash Report ID 8c81034e1db08a8b (Local Context: e1475b33-29b2-4592-a2a9-d797cd66552f)

Let me know if you need any additional information. Thanks.

**Comment by bsclifton** [comment]
Possibly related: https://github.com/brave/brave-browser/issues/5312

**Comment by PunnyBoi** [comment]
Hello, I am observing that whenever I remove or add a bookmark, brave starts taking a lot of memory. Also, I am syncing the bookmarks across my mobile and laptop. I am beginning to think that maybe this problem is created by bookmark sync. Whenever I add or remove bookmark, the browser tries to sync it across devices and during that process, it takes a lot of memory. After a minute or so, it reverts to normal. This do need more information and testing. Currently, I am turning off the sync and trying to confirm the above observation. In the meantime, if possible, can you look into the syncing process and its code to look for some possible bug?

**Comment by bsclifton** [comment]
Likely the same issue as https://github.com/brave/brave-browser/issues/6091

**Comment by bsclifton** [comment]
I believe this issue is now resolved - @PunnyBoi please let us know if you're still experiencing this with the latest version (0.68.142). Thanks! 😄
