### ISSUE TITLE
Create anonymous address for Uphold browser card and use v2 claim endpoint

### ISSUE THREAD

**Issue by evq** [brave/brave-browser#5291]
## Description 
This issue is for follow up coming out of the Gemini user wallet security review. 

The browser should create an anonymous address corresponding to the linked Uphold card that it creates when performing Uphold user wallet linking. It will then include the resulting address in the request to the claim your wallet endpoint, which will be enabled by the v2 of that API.

See:
https://github.com/brave-intl/bat-ledger/issues/668

**Comment by NejcZdovc** [comment]
closing as it was done with this issue https://github.com/brave/brave-browser/issues/5547
