### ISSUE TITLE
Global shield settings - Device recognition options are not aligned with dropdown

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5293]
## Description 

Global shield settings - Device recognition options are not aligned with dropdown

## Steps to Reproduce

   1.  Open brave 0.68.104
   2.  Navigate to `chrome://settings/shields`
   3. Click on Device recognition dropdown

## Actual result:

Device recognition dropdown options displayed beyond the frame
![image](https://user-images.githubusercontent.com/38657976/61524195-8dc40a80-aa33-11e9-967c-e233cde99dcf.png)

## Expected result:
Dropdown options should be aligned with device recognition dropdown

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.68.104 Chromium: 75.0.3770.100 (Official Build) dev (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @cezaraugusto

**Comment by cezaraugusto** [comment]
we could expand the select size to prevent this but will eventually happen with other locales and would likely need to change other select boxes as well. not sure it's worth it. cc @rossmoody @petemill

**Comment by rossmoody** [comment]
Unless I have the wrong idea here this is behaving as intended from an accessibility standpoint. It's not overflowing oddly or hiding any text. Seems to align differently based on OS but at least on Mac it even extends past the browser window to facilitate legibility: 

![image](https://user-images.githubusercontent.com/29072694/61830038-1ae5d580-ae1f-11e9-9e44-95cfe6f7d9f7.png)

I'd defer to @karenkliu and @tomlowenthal but one easy consideration to help this example specifically would be to keep the locale dry and go with:

### Device recognition attempts

- Block cross-site
- Block all
- Allow all

**Comment by petemill** [comment]
I’d vote to close this issue as won’t fix. This is not a bug really, it’s working exactly how system drop down menus are meant to: show the entire text when interacted with.

**Comment by kjozwiak** [comment]
@karenkliu @tomlowenthal @rebron are guys okay closing this off as a `wontfix`?
