### ISSUE TITLE
Vimeo - Attention % is NOT increased in BR panel even after watching video for 30 secs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5294]
## Description 

Play any Vimeo video for more than 30+ secs and open BR panel shows attention rate as 0%. close the BR panel and navigate to brave://rewards shows site added to a-c table and the attention % increased (shows some value)  for viewed video. Go back to the tab where the video is running and click on the BR panel shows the attention rate which was reflected in the a-c table. Switch the tabs or open and close the BR panel multiple times decrease the attention rate which is addressed in issue #5172

For YT and Twitch videos, attention rate starts increasing after watching the video for 10 secs, which is NOT happening for Vimeo videos.

## Steps to Reproduce

   1. Open brave 0.68.104
   2. Enable rewards
   3. Play Vimeo video for 30 secs `https://vimeo.com/mickmon`
   4. Click on BR panel shows the attention rate as 0%

## Actual result:

Attention % is NOT increased in BR panel even after watching video for 30 secs

https://drive.google.com/open?id=1OYzYzMq0BBWLpA88-wfaNG2hgn2KcwEC

## Expected result:
Attention %  should start increasing in BR panel after watching the video for 10 secs

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.68.104 Chromium: 75.0.3770.100 (Official Build) dev (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya vimeo has later ping than others, so it can happen after 5s or a minute. When you close tab, pause, etc. time is logged

**Comment by kjozwiak** [comment]
> @GeetaSarvadnya vimeo has later ping than others, so it can happen after 5s or a minute. When you close tab, pause, etc. time is logged

@GeetaSarvadnya can you go through the above again and double check to make sure that attention % is being logged after 5s-1min as per @NejcZdovc comment above?

**Comment by GeetaSarvadnya** [comment]
@kjozwiak Retested. As per the above @NejcZdovc comments, after one minute % rate is increased in BR panel without closing BR panel or switching the tabs.

**Comment by kjozwiak** [comment]
Thanks for the double check @GeetaSarvadnya 👍
