### ISSUE TITLE
Vimeo - Can't play multiple videos at a time.

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5295]
## Description 

When the user plays multiple videos in multiple tabs, the video which is played in the last tab is only streaming other videos are paused. Restart the browser is making all videos to pause.

In Youtube, user can play any number of videos at a time and restart browser will not pause videos.

## Steps to Reproduce

   1. Open brave 0.68.104
   2. Play a video in 1st tab https://vimeo.com/maqvoadora 
   3. Play another video in the 2nd tab https://vimeo.com/willchristiansen 
   4. Navigate to brave://rewards page and make sure both the videos got added to a-c table
   5. Verify the Attention % rate in a-c table for both videos
   6. Attention % rate for the video playing in the 2nd tab is increasing and the Attention rate for the 1st video is not increasing
   7. Navigate to tab1 and tab 2 and observe that the video which is playing in 1st tab is paused.

## Actual result:

Vimeo - Can't play multiple videos at a time, the video which is played last is only streaming.

https://drive.google.com/open?id=1qvqrVKezGyWPvIqJ7SehjagYsYiElZXD

## Expected result:
User should be able to play multiple videos at a time

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.68.104 Chromium: 75.0.3770.100 (Official Build) dev (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? Yes

## Miscellaneous Information:

@brave/legacy_qa @NejcZdovc 

I am not seeing this behavior in YT. This is happening only for Vimeo videos, If it's expected behavior please close the issue.

**Comment by NejcZdovc** [comment]
this is not a bug on our side, I guess this is how Vimeo works. Could you please verify that the same thing happens in other browsers

**Comment by GeetaSarvadnya** [comment]
Verified chrome, the behavior is same in chrome as well.
