### ISSUE TITLE
Backend support for playlists

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#5296]
* Functions
  * `chrome.playlist.requestDownload `
      * create playlist item for passed media `url`
  * `chrome.playlist.getAllPlaylistItems `
      * returns all playlist items
  * `chrome.playlist.getPlaylistItem`
      * returns specific playlist for current profile by id
  * `chrome.playlist.deletePlaylistItem`
      * Delete specific item by id
  * `chrome.playlist.deleteAllPlaylistItems`
      * Delete all items
  * `chrome.playlist.recoverPlaylistItem`
      * Try to recover incomplete playlist item that failed to fetch thumbnail or generate media file
  * `chrome.playlist.playItem`
      * play the given item  
* Events
  * `chrome.playlist. onPlaylistItemStatusChanged `
      * Fired whenever playlist item's status changed (ex, new item is added, deleted, ready to play or ready to use thumbnail ..)

cc: @bbondy @bsclifton @pilgrim-brave

**Comment by pilgrim-brave** [comment]
This is a great start. Here are a few things we should nail down before the implementation phase:

 - Content & format of the return values of each method. Not just "use JSON" (although we will probably do that), but what is the schema for each type? What is a "playlist" object as returned by `getPlaylist`? Is it the same type as the ones returned by `getAllPlaylists` (just a list of them), or does the `getAll` method return just a list of IDs that then need to be queried separately to get the details?
 - Who gets to call these methods? Just our own "blessed" extension? Do other extensions get to call a subset (maybe just the read methods, not the add/update/delete methods)?
 - I am assuming (but please specify it one way or the other) that creating a playlist from a media URL list triggers automatic background downloading and caching of all the media assets required to play offline. This is asynchronous (`createPlaylist` will return immediately, while downloading will continue in the background), so there will need to be some sort of `onPlaylistReady` callback notification when all assets are successfully downloaded, some sort of `onPlaylistError` callback notification if some assets can not be downloaded and the background download service has given up entirely, and some sort of query-able property to ask whether a specific playlist is actually ready to be played offline. This could be part of the object returned by `getPlaylist`; I don't think it needs to be a separate call.
 - I am assuming (but please specify it one way or the other) that deleting a playlist always deletes all associated local media assets, and also that the only way to free up the space used by a playlist is to delete the playlist.
 - Local file deletion (presumably triggered by `deletePlaylist` or `deleteAllPlaylists`) will happen in the background, so `deletePlaylist` will return immediately while the file I/O will continue asynchronously on another thread.
 - What happens if the browser crashes after we delete a playlist but before we complete deleting the local media assets? Will there be a periodic sweep to find and remove orphaned local files? Should this be handled internally or should we add an explicit method for it?

**Comment by simonhong** [comment]
@pilgrim-brave 
> * Content & format of the return values of each method. Not just "use JSON" (although we will probably do that), but what is the schema for each type? What is a "playlist" object as returned by `getPlaylist`? Is it the same type as the ones returned by `getAllPlaylists` (just a list of them), or does the `getAll` method return just a list of IDs that then need to be queried separately to get the details?

Please see `getPlaylist` or `getAllPlaylists` below schemes 
> * Who gets to call these methods? Just our own "blessed" extension? Do other extensions get to call a subset (maybe just the read methods, not the add/update/delete methods)?

I think `blessed` Shields extension and `newtab` page can call those apis.
AFAIK, `newtab` will show playlist. but not sure we will add another player.
> * I am assuming (but please specify it one way or the other) that creating a playlist from a media URL list triggers automatic background downloading and caching of all the media assets required to play offline. This is asynchronous (`createPlaylist` will return immediately, while downloading will continue in the background), so there will need to be some sort of `onPlaylistReady` callback notification when all assets are successfully downloaded, some sort of `onPlaylistError` callback notification if some assets can not be downloaded and the background download service has given up entirely, and some sort of query-able property to ask whether a specific playlist is actually ready to be played offline. This could be part of the object returned by `getPlaylist`; I don't think it needs to be a separate call.

Returned object from `getPlaylist` or `getAllPlaylists` will have `ready` property for whether this playlist is ready to play or not. If not is not ready, it can be played after receiving `onPlaylistsChanged` with `Ready` status. Also `onPlaylistsChanged` with `Cancelled` event will be delivered when backend can't complete making playlist.
> * I am assuming (but please specify it one way or the other) that deleting a playlist always deletes all associated local media assets, and also that the only way to free up the space used by a playlist is to delete the playlist.
> * Local file deletion (presumably triggered by `deletePlaylist` or `deleteAllPlaylists`) will happen in the background, so `deletePlaylist` will return immediately while the file I/O will continue asynchronously on another thread.
> * What happens if the browser crashes after we delete a playlist but before we complete deleting the local media assets? Will there be a periodic sweep to find and remove orphaned local files? Should this be handled internally or should we add an explicit method for it?

I'll implement all operations that needs file i/o in background like create playlist or delete (all)playlists. and I'm planning to notify about finishing those operations by `onPlaylistsChanged`.
Of course, deleting playlist also delete all media assets from file system.
If browser shutdown before deleting assets, it will be cleaned up at next launching by playlists controller.

```
[
  {
    "namespace": "bravePlaylists",
    "description": "Use the <code>chrome.bravePlaylists</code> API to get/set playlist",
    "compiler_options": {
      "implemented_in": "brave/browser/extensions/api/brave_playlists_api.h"
    },
    "events": [
      {
        "name": "onPlaylistsChanged",
        "type": "function",
        "description": "Fired when playlists is changed",
        "parameters": [
          {
            "name": "status",
            "type": "string",
            "description": "Playlists change status(Added, Deleted, Ready, Empty)"
          },
          {
            "name": "id",
            "type": "string",
            "optional": true,  // When Empty status, id is not needed.
            "description": "id of added or deleted playlist"
          }
        ]
      },
      {
        "name": "onInitialized",
        "type": "function",
        "description": "Fired when playlists backend is initialized",
      }
    ],
    "functions": [
      {
        "name": "initialized",
        "type": "function",
        "description": "For checking whether playlists backend are initialized",
        "parameters": [
          {
            "name": "callback",
            "type": "function",
            "parameters": [
              {
                "name": "initialized",
                "type": "boolean",
                "description": "Whether playlists backend is initialized or not"
              }
            ]
          }
        ]
      },
      {
        "name": "createPlaylist",
        "type": "function",
        "description": "create new playlist",
        "parameters": [
          {
            "type": "object",
            "name": "data",
            "properties": {
              "media_file_urls": {
                "type": "array",
                "items": {
                  "type": "object",
                  "description": "Data for each media file in this playlist",
                  "properties": {
                    "url": {
                      "type": "string",
                      "description": "Url for this media file"
                    },
                    "title": {
                      "type": "string",
                      "description": "Title for this media file"
                    }
                  }
                }
               },
              "thumbnail": {
                "type": "string",
                "description": "The url for thumbnail image for this playlists",
                "optional": true
              },
              "name": {
                "type": "string",
                "description": "Playlist name"
              }
            }
          }
        ]
      },
      {
        "name": "getAllPlaylists",
        "type": "function",
        "description": "Get all playlists",
        "parameters": [
          {
            "name": "callback",
            "type": "function",
            "description": "Function called when all playlists are fetched",
            "parameters": [
              {
                "type": "array",
                "name": "playlists",
                "items": {
                  "type": "object",
                  "description": "The list of playlist",
                  "properties": {
                    "id": {
                      "type": "string",
                      "description": "id for each playlist"
                    },
                    "name": {
                      "type": "string",
                      "description": "Name for playlist"
                    },
                    "titles": {
                      "type": "array",
                      "itmes": {
                        "type": "string",
                        "description": "Title for each media file"
                      }
                    },
                    "thumbnail": {
                      "type": "string",
                      "description": "url of thumbnail for playlist",
                      "optional": true
                    }
                  }
                }
              }
            ]
          }
        ]
      },
      {
        "name": "getPlaylist",
        "type": "function",
        "description": "Get specific playlist",
        "parameters": [
          {
            "name": "id",
            "type": "string",
            "description": "id for fetching a playlist",
          },
          {
            "name": "callback",
            "type": "function",
            "parameters": [
              {
                "name": "playlist_name",
                "type": "string",
                "description": "Name for playlist"
              },
              {
                "name": "titles",
                "type": "array",
                "items": {
                  "type": "string",
                  "description": "Title for each media file"
                }
              },
              {
                "name": "ready",
                "type": "boolean",
                "description": "Whether this playlist can be played or not"
              }
              {
                "name": "thumbnail",
                "type": "string",
                "description": "url of thumbnail for playlist",
                "optional": true
              }
            ]
          }
        ]
      },
      {
        "name": "deletePlaylist",
        "type": "function",
        "description": "Delete specific playlist and free all its data",
        "parameters": [
          {
            "name": "id",
            "type": "string",
            "description": "id for deleting playlist",
          }
        ]
      },
      {
        "name": "deleteAllPlaylists",
        "type": "function",
        "description": "Delete all playlists",
      }
    ]
  }
]
```

**Comment by pilgrim-brave** [comment]
This looks great. Let's make it!

**Comment by bsclifton** [comment]
Closing as stale - we have a lot of newer work landed! 😄
