### ISSUE TITLE
Shields panel doens't shrink to fit when advance options is hidden

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#53]
![shields-advcontrol](https://user-images.githubusercontent.com/17010094/34930038-6f73bc4e-f9ed-11e7-9d10-52d126eedfba.gif)

**Comment by bbondy** [comment]
If spending more than a day on this, I'd just remove the advanced collapsable feature.

**Comment by GeetaSarvadnya** [comment]
Verified on:

Brave | 0.54.2 Chromium: 69.0.3497.42 (Official Build) dev (64-bit)
-- | --
Revision | 9c4613c66dfeb2b76ef6dd4b15884c15db3b4969-refs/branch-heads/3497@{#655}
OS | Windows
JavaScript | V8 6.9.427.14
Flash | 30.0.0.154
