### ISSUE TITLE
Brave high CPU usage on local domains

### ISSUE THREAD

**Issue by pentacore** [brave/brave-browser#530]
When visiting local domains using brave they are extremely slow loading/Sluggish, or sometimes just stop responding all together, this issue doesnt seem to show itself whilst visiting the page directly with the IP address.

As an example; my freenas page hogs about 30-40% of my cpu when using domain name, but only >2% if using IP-Address.

## Steps to Reproduce

   1. Open local webpage using domain name thats on the same network

## Actual result:
The page is either extremely slow or totally unresponsive, both in CSS and JS triggers, CPU usage high.

## Expected result:
Quick and responsive experience, CPU Usage way lower than actual result

## Reproduces how often: 
Any time and on any of my pages hosted on my local network

## Brave version (about:brave info) 
0.23.31 Windows 10

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
Yes
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by bbondy** [comment]
This was meant for brave/muon and works in brave-core which we'll have soon. So no need to track this here. Thanks for the report though!
