### ISSUE TITLE
Sync: stop resend if not required

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#5300]
## Description 

Sync resends bookmarks records even if it is not required.

## Steps to Reproduce

   1. Establish sync between two browsers
   2. Add bookmark A1.com on device A and B1.com on device B
   3. Wait > 20 minutes
   4. Open inspector and sync extension

## Actual result:

   5. Possible to see `"send-sync-records" category_name="BOOKMARKS" records=...` messages even if bookmarks were not changed.

## Expected result:
   5. No bookmarks records sent if no were changed.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 0.69.72 Chromium: 76.0.3809.62 (Developer Build) (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Linux
JavaScript | V8 7.6.303.20

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? yes

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
-- | --
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Mac OS X

* Followed STR from description. Used `0.66.101` for device A and `0.67.112` for device B. (device B is using a version that does not have this fix yet). Verified device A (with the fix) did not show `"send-sync-records" category_name="BOOKMARKS" records=...` in the logs multiple times, whereas device B did. Screenshot below - left is device B, right is device A.
![Screen Shot 2019-07-22 at 3 42 29 PM](https://user-images.githubusercontent.com/28145373/61660355-a59bc880-ac97-11e9-87aa-0c9a6c7d9641.png)

**Comment by AlexeyBarabash** [comment]
Forgot to mention, for more comfortable understanding, it is possible to switch timestamps in Inspector by kebab menu => Settings => Console => Show timestamps.
