### ISSUE TITLE
Incorrect Hyperlink on https://brave.com/brave-rewards/

### ISSUE THREAD

**Issue by Surakshith-S** [brave/brave-browser#5308]
## Description 
The hyperlink for AIRSWAP is entered incorrectly and set for HOMECHEF
Not sure if this is the right place to report this. 

## Steps to Reproduce
   1.  Access https://brave.com/brave-rewards/
   2.  Under a few of our Advertisers > Clicking on AIRSWAP takes to HOMECHEF site 
`<a href="https://www.homechef.com/" target="_blank"><span class="et_pb_image_wrap "><img src="https://brave.com/wp-content/uploads/2019/04/airswap-white-1.png" alt="" /></span></a>`

**Comment by kjozwiak** [comment]
Thanks for the report @Surakshith-S 👍 I've created https://github.com/brave/brave-com-resources/issues/43 and mentioned this issue. Closing this off as it will be tracked in the issue mentioned above. Again, thanks for the report!

CCing @w0ts0n @rossmoody
