### ISSUE TITLE
BraveImporter fails to import cookies and passwords from browser-laptop installed via Snap on Linux

### ISSUE THREAD

**Issue by garrettr** [brave/brave-browser#531]
## Description 

BraveImporter successfully imports cookies and passwords from browser-laptop when it is installed via [.deb](https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md#debian-jessie-stretch-and-ubuntu-artful-zesty-yakkety-xenial-and-trusty-amd64) on Debian-based Linux, but fails to do so when browser-laptop is installed via [Snap](https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md#snapcraft).

Related to brave/browser-laptop#14586.

## Steps to Reproduce

1. `snap install brave`. Ensure you are using the Snap-provided Brave (`which brave`) before continuing.
2. Start Brave browser-laptop.
3. Log in to some sites, clicking **Allow** when prompted to save passwords.
4. Quit Brave browser-laptop.
5. `yarn start`
6. Open the main menu (e.g. **Brave** on macOS) and choose **Import Bookmarks and Settings...**
7. Choose your test Brave profile from the dropdown menu of browser profiles and click **Import**.
8. Visit the sites you visited in the earlier browser-laptop session.

## Actual result:

You will not be logged in to the sites you had logged in to in your browser-laptop session. If you try to log in, you will not be prompted to autofill the login form with the username and password you used in your browser-laptop session.

## Expected result:

You should still be logged in to the sites you visited, because cookies were imported. If you log out and try to log in again, you should be prompted to autofill your username and password, because passwords were imported.

## Reproduces how often: 

100%.

**Comment by bsclifton** [comment]
Closing as the Muon import was removed 😄
