### ISSUE TITLE
Please provide direct links to stable releases

### ISSUE THREAD

**Issue by andr222** [brave/brave-browser#5310]
## Description 
There is no direct link to download stable releases, particularly for Linux.
Unfortunately none of the indirect links provided will work with my distro.
So users of distributions not provided by brave can not easily find an appropriate build, even though most distros could use a package made for either redhat/fedora (.rpm) or ubuntu/debian (.deb), or a .zip version without installer.
In my case, using Mageia, generally a redhat/fedora package (.rpm) installs nicely.  However the download options do not work with the version of rpm installed on my system.
If the .rpm package won't install properly, a .zip version would  almost surely work (albeit with more effort to install).
I need to use a stable version, to avoid potential problems.

## Steps to Reproduce
The download page has no direct links

## Actual result:
Can't use Brave.

## Expected result:
Like most open source software, where the download page gives direct links to at least the stable versions.

## Version/Channel Information:
This problem would affect many (if not most) users of Linux.

- Can you reproduce this issue with the current release?
That is exactly what I'm looking for.

## Other Additional Information:
- Is the issue reproducible on the latest version of Chrome? 
No : easy to download Chrome.

**Comment by kjozwiak** [comment]
@andr222 have you tried grabbing releases from https://github.com/brave/brave-browser/releases/? One of the easiest way to grab the latest release is using https://github.com/brave/brave-browser/blob/master/CHANGELOG.md. Clicking on the version header will take you to the appropriate GitHub page where you can download `deb`, `rpm` and `zip` files.

Are you having issues installing Brave using the `deb` or `rpm` packages on `Mageia`?

**Comment by andr222** [comment]
"https://github.com/brave/brave-browser/releases/"
seems to give nightly releases, which I assume are pre-beta.
I'm looking for a stable release.  (Let me know if I'm mistaken.)
The link for Linux on that page goes to the download page, which gives instructions for rpm packages which do not work on my distribution.  (Mageia, which uses rpm for packages.)
However most .rpm packages will install on Mageia, although sometimes it is difficult to find dependancies not already installed, as they often have somewhat different names (from redhat/fedora).

"https://github.com/brave/brave-browser/blob/master/CHANGELOG.md."
gives a liste of packages, which seem to be nightly releases.
A link on the download page to a list of stable releases (identified as such) would be very convenient, and is what this issue is asking for.

Since I haven't yet found what I recognize as a stable release, I haven't yet installed brave.
(It could be an .rpm version, or a .zip package without installer.)

**Comment by kjozwiak** [comment]
Anything listed on https://github.com/brave/brave-browser/blob/master/CHANGELOG.md is a stable release that's released to the entire Brave population (at least the ones on the release channel).

Quick example: If you take a look at https://github.com/brave/brave-browser/blob/master/CHANGELOG.md, you'll notice that the last entry is `0.66.101`. You can find out this release is the latest using several methods:

* use https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#current-channel-information to find out what version each channel is on. Release is currently on `0.66.x`.
* Go into https://github.com/brave/brave-browser/releases/ and look for the latest `0.66.x` build which in this case, it's `0.66.101`

If you download a build from https://brave.com/download/, you'll get `0.66.101` right now. The first entry in https://github.com/brave/brave-browser/blob/master/CHANGELOG.md is always the latest stable release that's currently released.

**Comment by fmarier** [comment]
@andr222 Could you please open a new issue with the problems you run into when you try to install the RPM using say the Fedora instructions on https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux. Please include the exact distro version as well.

If there's something we can easily fix on our end to make the existing RPMs compatible with your distro, then we should do it.

**Comment by andr222** [comment]
> There's definitely room for improvement in terms of letting users know which version is the latest stable build though  But for now, using https://github.com/brave/brave-browser/blob/master/CHANGELOG.md is probably your best bet

Thanks for the info :)
That solves my problem.
Hopefully soon better info/links on the download page (or similar location) will inform users of distros/os's that are not now explicitly supported on the download page.
To help spread the usage of the brave navigator.

**Comment by kjozwiak** [comment]
Going to close this off @andr222. As per the above request from @fmarier, if you're having issues installing Brave on your distro, please create a new issue and include as much information as possible so @fmarier or another developer can investigate 👍 

Please re-open if you feel this shouldn't be closed off.
