### ISSUE TITLE
.google.com cookie mismatch after import

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#5313]
## Description
Import cookies from Chrome/Firefox will cause cookie mismatch error on google.com

## Steps to Reproduce
1. Clean cookies on Chrome/Firefox and login in google account
2. Import cookies from Chrome/Firefox to Brave
3. Login google account on Brave

## Actual result:
![image](https://user-images.githubusercontent.com/4733304/61608676-6d00de00-ac08-11e9-8bf6-9569c78b533b.png)

## Expected result:
No cookie mismatch error

## Reproduces how often: [What percentage of the time does it reproduce?]
100%

**Comment by bsclifton** [comment]
recently reported by @johnnyryan - here's the fix we did in Muon:
https://github.com/brave/browser-laptop/pull/11647/files

**Comment by bsclifton** [comment]
Needs to be retested after https://github.com/brave/brave-core/pull/3804 was merged... will try this out soon

**Comment by simonhong** [comment]
I tested with the fix(https://github.com/brave/brave-core/pull/3804).
After importing chrome's cookie, I loaded google.com and  brave is logged in state w/o any error.

**Comment by bsclifton** [comment]
This is great news! Let's close this issue for now- we can always re-open if we get reports

**Comment by LaurenWags** [comment]
`QA/Blocked` until we get a new build. Will be available in 0.71.107` and above.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.71.106 Chromium: 78.0.3904.70 (Official Build) beta (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified STR from description
* Verified test plan from https://github.com/brave/brave-core/pull/3804
* Verified I could import cookies for a single Google account and navigate to gmail, etc without error
* Verified I could import cookies for two Google accounts and navigate to gmail, etc with error
* Verified after importing cookies for two Google accounts I could add a third and navigate to gmail, etc without error
