### ISSUE TITLE
Create a "Developer" version of Brave

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#5315]
## Description 
There might be configuration options that would be more useful to developers (ex: people making extensions, web pages, etc)

At the moment, there's not enough requirements for us to take action. In the meantime, Brave can be compiled from source with the desired config / options:
https://github.com/brave/brave-browser/wiki

Suggestions and discussion welcome! 😄 

## Potential features
- [ ] Don't show the side-loaded extensions warning (or have a toggle for it) https://github.com/brave/brave-browser/issues/5063

- [ ] ??

**Comment by rebron** [comment]
wontfix
