### ISSUE TITLE
Please implement a cookie banner blocker that works like "I don't care about cookies"

### ISSUE THREAD

**Issue by szaimen** [brave/brave-browser#5318]
Please implement a cookie banner blocker that works like "I don't care about cookies"
Official Website: https://www.i-dont-care-about-cookies.eu/
I think the consent policy for installing cookies is also really nice. 
Look here: https://www.i-dont-care-about-cookies.eu/notices/3.0.2/
and here: https://www.i-dont-care-about-cookies.eu/cookie-installing-permission-header/

**Comment by ryanbr** [comment]
`I don't care about cookies` isn't that optimised. But it would be handy to block cookie notices as an option.

**Comment by szaimen** [comment]
I don't know, if it's optimized or not, but in my experience espacially the chrome extension works really well! The best thing about this extension is, that I do not have make script blocking in brave to the default, because it just destroys most of the websites I visit and I don't see any cookie notice at all.

BTW: this chrome extension is available under GPL 3.0 as stated inside the license-file in the chrome-extension-folder.

**Comment by rebron** [comment]
@snyderp can you take a look at triaging this one?

**Comment by rebron** [comment]
cc: @anthonypkeane

**Comment by szaimen** [comment]
Any update here? Would be really handy to get this option out of the box!

**Comment by BrendanEich** [comment]
Stirring the pot on this with @ryanbr.

**Comment by ryanbr** [comment]
@szaimen We're still investigating the possibility of using a cookie list. watch this space :)

https://github.com/easylist/easylist/tree/master/fanboy-addon

`fanboy_cookie_general_block.txt`
`fanboy_cookie_general_hide.txt`
`fanboy_cookie_international_specific_block.txt`
`fanboy_cookie_international_specific_hide.txt`
`fanboy_cookie_specific_block.txt`
`fanboy_cookie_specific_hide.txt`
`fanboy_cookie_thirdparty.txt`
`fanboy_cookie_whitelist.txt`
`fanboy_cookie_whitelist_general_hide.txt`

**Comment by snyderp** [comment]
Panpap and Hammed and I have plans to discuss some options at the London event next week

**Comment by rebron** [comment]
Requires: https://github.com/brave/brave-browser/issues/5381

**Comment by snyderp** [comment]
@anthonypkeane

**Comment by Brave-Matt** [comment]
A couple +1s from Community:
https://community.brave.com/t/block-cookie-consent-popups-cookie-policy-is-already-set-locally-with-brave/98876/3

**Comment by ryanbr** [comment]
+1
https://community.brave.com/t/block-cookie-banners/113665/2

**Comment by szaimen** [comment]
🎉

**Comment by bsclifton** [comment]
Although a fix is merged with https://github.com/brave/adblock-rust/pull/82, we have a few more steps before this is live in Brave:
- [ ] update https://github.com/brave/adblock-rust-ffi to pull in latest from https://github.com/brave/adblock-rust/pull/82
- [ ] update https://github.com/brave/brave-core/blob/master/DEPS to point at commit from `adblock-rust-ffi` with the fix

cc: @AndriusA @ryanbr

**Comment by bsclifton** [comment]
@ryanbr are there test steps that can be added to original post? What does QA look like for this?

**Comment by ryanbr** [comment]
Functionality isn't changing from the previous list, just a supported list instead.

**Comment by bsclifton** [comment]
@kjozwiak @LaurenWags release notes for this could be `Switch from "Prebake Cookie" to "Easylist Cookie" list`

**Comment by kjozwiak** [comment]
@bsclifton yup, sounds good! Much appreciated.

**Comment by szaimen** [comment]
🎉

**Comment by RichyHBM** [comment]
Hello, has this been implemented in the android browser? Or will it be coming to android?

**Comment by rmaliqi** [comment]
where can I check if this function is available in my browser (windows and iOS)? I feel like I have to still click away those notifications all the time

**Comment by ryanbr** [comment]
@rmaliqi windows (desktop) does support hiding cookie notices via `brave://adblock` , unfortantly iOS doesn't support cosmetic filter just yet which would limit its effectiveness.

Related to iOS:
https://github.com/brave/brave-ios/issues/2683
https://github.com/brave/brave-ios/issues/1358

**Comment by jakedavidson** [comment]
Has this been implemented in the Android browser yet? Just want to confirm as the last update had mentioned potentially shipping this in June, so want to make sure I didn't just miss it. 

> @RichyHBM the list is being shipped on Android currently. So right now the network half of the list should be applied in all versions of the android browser.
> 
> The brave android browser doesn't currently apply cosmetic rules though, the way the desktop version of Brave does. This is bc the android version doesn't yet support extensions. Android support for extensions is currently being worked on, and we hope to have it good to go by the end of June, 2020

**Comment by tbrodbeck** [comment]
I am still getting Cookie banners on macOS - banners that Adguard is able to block (Adguard Annoyances Filter).

I have tested this for example on this site: https://www.cookiepro.com/knowledge/how-do-i-test-cookie-blocking-implementation/

**Comment by ryanbr** [comment]
@tbrodbeck tested here: enabling `Easylist cookie` via `brave://adblock`  Seems fine here.

https://gif.fanboy.co.nz/gif/test-cookiepro.gif

**Comment by tbrodbeck** [comment]
> @tbrodbeck tested here: enabling `Easylist cookie` via `brave://adblock` Seems fine here.
> 
> https://gif.fanboy.co.nz/gif/test-cookiepro.gif

Thanks! That works. Maybe there was some interference because I had all the other annoyances filters activated as well?!

**Comment by bartosz-jarmuz** [comment]
For me it does not work on that very same site.

**Comment by alfredonodo** [comment]
Brave just released [Blocking annoying and privacy-harming cookie consent banners](https://brave.com/privacy-updates/21-blocking-cookie-notices/). However, it works in the same way as ublock origin via a filter list ([Easylist-Cookie List - Filter Obtrusive Cookies Notice](https://easylist.to/)) and it does not work on google website (search, youtube, etc.).
In this case, an extension like [I still don't care about cookies ](https://github.com/OhMyGuus/I-Dont-Care-About-Cookies) (a fork of [I don't care about cookies](https://www.i-dont-care-about-cookies.eu/) recently acquired by avast) is still needed. Would it be possible for brave to implement something similar?

**Comment by pes10k** [comment]
hi @alfredonodo , let me ping @ryanbr who does most of the filter list work at Brave (and does a great job doing it).

I just wanted to note though that we decided to not go with the "I {still} don't care about cookies" approach in general because its less privacy-protecting than the filter list approach.  There are some cases though that won't work with the filter list approach (at least, not easily) for compat reasons.  This might be one of them.  We'll see what can be done using Brave's approach for the google example you mentioned and get back to you.  Thanks for raising the issue!

**Comment by ryanbr** [comment]
@alfredonodo investigating some snippet options regarding google/youtube. Not easy with standard filter options. IDCAC filterlist has the same issue.

**Comment by alfredonodo** [comment]
Unfortunately, according to [this](https://github.com/easylist/easylist/tree/master/easylist_cookie#the-following-sites-have-no-current-workaround), at the moment there is no solution.Unfortunately, based on this, there is currently no solution.
