### ISSUE TITLE
Nightly : BAT Panel shows "Wallet creation failed" for existing profiles

### ISSUE THREAD

**Issue by alexwykoff** [brave/brave-browser#5322]
## Description 
The BAT panel shows 'Wallet creation failed' for existing profiles in Nightly (reproduced on MacOS and Win10)

All other Brave Rewards functions appear fine, Brave Rewards setting page shows accurate information.

## Steps to Reproduce

   1.  Have an existing wallet in the Nightly build.
   2. Open the BAT panel.

## Expected result:
BAT panel should display normally

## Reproduces how often: 
Unsure how to accurately reproduce, but occurs 100% of the time thereafter.

## Brave version (brave://version info)
Version 0.69.77 Chromium: 76.0.3809.62 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by NejcZdovc** [comment]
so the thing about this one is that you shouldn't see this overlay in the first place. Wallet creations of course fails as you already have a wallet

**Comment by NejcZdovc** [comment]
closing as stale
