### ISSUE TITLE
WebTorrent: Certain file types do not render correctly

### ISSUE THREAD

**Issue by feross** [brave/brave-browser#5326]
*Reposting an issue mentioned in a comment:*

Certain file types which the browser does not know how to open just appear as gibberish in a text box, and there is no UI option to "save as".  The "save" only works with media files that the browser knows should be rendered in the media player.  For example try downloading a torrent with an m4b file in it in brave on macos.  I get this:  
![image](https://user-images.githubusercontent.com/37491881/52894656-715d3280-3162-11e9-97ff-4c004ec4d073.png)

_Originally posted by @matt812 in https://github.com/brave/brave-browser/issues/1436#issuecomment-464290259_

**Comment by feross** [comment]
## Test Plan 

1. Visit this URL: https://ia800301.us.archive.org/14/items/art_of_war_librivox/art_of_war_librivox_archive.torrent
2. Start the torrent download
3. Click on file 1 "ArtOfWar-64kb_librivox.m4b" and confirm that the audio file plays.
4. Click on file 2 "Art_War_1107.jpg" and confirm that an image shows up.
5. Click on file 3 "Art_War_1107.pdf" and confirm that the PDF viewer loads with a PDF inside.
6. Click on file 11 "art_of_war_01-02_sun_tzu.ogg" and confirm that the audio file plays.
7. Click on file 12 "art_of_war_01-02_sun_tzu.png" and confirm that the image shows up.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.126 Chromium: 77.0.3865.65 (Official Build) (64-bit)
-- | --
Revision | 87a331a3169cab563505fb44011058b904011ba1-refs/branch-heads/3865@{#726}
OS | macOS Version 10.14.6 (Build 18G95)

* Verified the test plan that was outlined under https://github.com/brave/brave-browser/issues/5326#issuecomment-516645276

**Comment by kjozwiak** [comment]
@feross I noticed that the background usually goes completely black when opening files as per:

![backgroundIssue](https://user-images.githubusercontent.com/2602313/65121632-94341b80-d9bd-11e9-961c-52246bab88ee.gif)

All the files are opening correctly, but after ~5s or so, the background goes black. Is this expected behaviour? Why not keep the background white? Let me know if this is an issue and I can create a new GH bug 👍

**Comment by feross** [comment]
You can open a new GH bug for this. It shouldn't take this long to make the background black. The goal was to ensure that media files have a black background. But the main torrent interface has a white background, so this is handled in the Redux state. But it seems like this can take a really long time to run in your case. That's not good. Also, the black background makes this image completely unviewable. I'd like to check in Chromium and see if this image has the same viewability problem, since they also use a black background.

**Comment by kjozwiak** [comment]
@feross thanks for the summary 👍 Created https://github.com/brave/brave-browser/issues/6094.
