### ISSUE TITLE
Individual Cookie Management

### ISSUE THREAD

**Issue by flamsmark** [brave/brave-browser#533]
Replaces brave/browser-laptop#1991

Rough minimal features
- list all cookies grouped by origin
- allow cookies to be edited/deleted individually
- delete all cookies by origin
- ability to add origins to the 3rd party cookie whitelist

**Comment by bbondy** [comment]
I think we have this already in the URLbar, can you confirm and close if it's missing something @flamsmark ?

**Comment by flamsmark** [comment]
Quite right 👍🏻

**Comment by timolson** [comment]
> I think we have this already in the URLbar, can you confirm and close if it's missing something @flamsmark ?

How exactly can I delete the cookies for a specific site?  I only see content controls for new content, and no way to manage cookies other than "Delete ALL of them for the last {hour, day, week}"  I need to be able to clear specific cookies.  I want to delete Google's cookies but keep the ones for my bank, for example, without removing the entire history of all sites I browsed during the period.

**Comment by cndouglas** [comment]
@timolson Go to **Site Settings > Cookies > All cookies and site data** or the URL `brave://settings/siteData`. You'll see a list of cookies by site.
![image](https://user-images.githubusercontent.com/19424103/56070960-b19af480-5d50-11e9-9841-cf2cc71be3e1.png)

**Comment by timolson** [comment]
I can get there with the URL you provided, but there is no "Site Settings" under Settings.  Is my version old?

Version 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)

**Comment by cndouglas** [comment]
Click Advanced at the bottom of Settings:
![](https://user-images.githubusercontent.com/19424103/56071266-e9a33700-5d52-11e9-98fc-6f68fc9050df.png)
Near the bottom of the **Privacy and security** section:
![image](https://user-images.githubusercontent.com/19424103/56071297-0d667d00-5d53-11e9-9884-6350362a6911.png)

**Comment by timolson** [comment]
@cndouglas Nope, mine looks entirely different.  Linux.  No "Site Settings."

![image](https://user-images.githubusercontent.com/1697115/56072236-af816780-5d49-11e9-85b6-aab39aeddda1.png)

AHH but under _Content Settings_ I finally found "See all cookies and site data."

Thanks for the PEBKAC support

**Comment by cndouglas** [comment]
Looks like the name was recently changed from "Content settings" to "Site settings". (I am running the nightly version — currently 0.65.50.)

**Comment by genio** [comment]
Any way to control individual third-party cookies on a given site like the built-in way in Chrome? I block all third party cookies by default, the browser bar indicates when the browser has blocked cookies for a specific site with a cookie icon and red X on it. If I click that cookie icon, I can then choose to allow specific third-party cookies for this site or continue blocking them.

**Comment by cndouglas** [comment]
@genio That same feature can be found in Brave by clicking the lock icon in the URL bar and then clicking Cookies:
![](https://user-images.githubusercontent.com/19424103/59140845-df737280-8968-11e9-879f-ff4a430fa717.png)
