### ISSUE TITLE
A quicker clear/delete/erase history button

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#5335]
Have you searched for similar issues? Yes

## Description 
Some of us are flippant with features on the browser and doing several clicks just to get to one simple function can be laborious. So naturally I was thinking wouldn't it be viable to practically embed a button similarly to the BAT and Brave icon and perhaps actually in-line with those features but with an option to enable and disable it for visibility like the toggle for the Rewards button.

I understand there are really good extensions that a lot of effort has been put into creating them for _**Chrome**_ for situations like this but I wish the Brave team contemplates doing something a bit more efficient, so as to cut the use of any memory but for other factors as well. Naturally I suspect this is what most of us wish with features like these and others like the screenshot function in Firefox.

If you do happen to think this is a neat option, perhaps you can have the -  
**Hide Clear data button**
**Hides the Clear data button from the location bar**
next to the **Cancel** - **Clear data buttons** in the 'Clear browsing data' screen.

## Expected result: 
After preferred functions are set by the user, the one-click button would either simply perform the functions previously set by the user when toggling the feature or one-click and exit. Given the one-click's button is to do everything effectively in one-click, perhaps to allow the one-click and exit function, the team could code the button to clear/delete/erase and exit if the button is held for anymore than a second.

## Other Additional Information:
One other reason upon consideration by the team and those that are tasked for this feature is that it would prove valuable in the long-run as the team can make enhancements to its functionality along the way as of when the Session-Tabs feature is finally implemented. This is to say that I'm almost positive that private _**Chrome designed**_ extensions will quite likely throw up errors or just wont do what a Brave user wants it do. Finally, I sort of like the recycling sign for this button; I wonder if green/teal and orange go together.

**Comment by NumDeP** [comment]
Honestly what is so crap about this feature? 

I can't be the only one that wants to avoid the repetitive task of 3 or 5 clicks just to clean and continue browsing or clear and exit browsing much more efficiently.

**Comment by tomlowenthal** [comment]
Adding a top level button to do something which most people use occasionally and some people want to do all the time sounds like the ideal use for an extension rather than a core browser feature.
