### ISSUE TITLE
Rewards popup doesn't show on Nightly

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5336]
## Description 

Rewards popup doesn't show on Nightly

## Steps to Reproduce

   1. Install an older version of nightly 
   2. Update to the current nightly public build (0.69.77)
   3. Click on rewards panel, doesn't show the panel just a small box

## Actual result:

![Screenshot from 2019-07-23 09-42-36](https://user-images.githubusercontent.com/17010094/61718178-6f5e5780-ad30-11e9-907b-da7372fe8e53.png)

## Expected result:
Panel should be shown

## Reproduces how often: 

Easy on my machine

## Brave version (brave://version info)

Brave | 0.69.77 Chromium: 76.0.3809.62 (Official Build) nightly (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  N/A

## Miscellaneous Information:

Close and restart browser doesn't fix the issue

**Comment by LaurenWags** [comment]
This is easily reproducible when you have a notification on the BAT logo.
Steps I used to reproduce:
1. Install 0.69.47 with staging variables set
2. Enable rewards.
3. Restore a wallet that will produce a notification (ad grant, back up wallet, insufficient funds, etc).
4. Don't dismiss notification.
5. Upgrade to 0.69.77.
6. Click on BAT logo --> panel doesn't open, see white box instead.
![Screen Shot 2019-07-23 at 10 19 21 AM](https://user-images.githubusercontent.com/28145373/61719665-5b682500-ad33-11e9-9947-d3e703d927a0.png)

**Comment by GeetaSarvadnya** [comment]
I have seen this issue once in Beta channel 0.68.114. 
Steps which I have followed to reproduce the issue:

1. clean profile 0.68.113 (Staging env, reconcile interval was set to 2 mins)
2. claim grants
3. added few sites to a-c table (verified+non verified)
4. kept browser idle for a couple of hours 
5. got 29 counter-notification on BAT logo
6. upgraded profile to 0.68.114
7. after upgrade click on BAT logo did not open up the rewards panel

![image](https://user-images.githubusercontent.com/38657976/62211408-fa3bf380-b3bb-11e9-97d8-b1f52921b38e.png)

**Comment by LaurenWags** [comment]
@NejcZdovc we've got a report of this in from community as well: https://community.brave.com/t/unable-to-open-brave-rewards-with-triangle-icon-in-internet-search-box/75914

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/problem-mounting-rewards-panel/76917

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.115 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- The issue is reproducible in the old builds 0.68.113/0.68.116/0.69.77, now the issue is fixed.
- Verified the STR from the description
- Verified the test plan from https://github.com/brave/brave-core/pull/3201
- Verified the STR from https://github.com/brave/brave-browser/issues/5336#issuecomment-514230608 and https://github.com/brave/brave-browser/issues/5336#issuecomment-516825310 - the issue is fixed and working fine

**Comment by devcshort** [comment]
I'm getting this issue on version 0.68.132 / Windows 10

**Comment by jonathansampson** [comment]
@devcshort Can you inspect that window, and see what the console says? I suspect there's a problem calling .toString off an object somewhere. Would love your assistance in confirming.

**Comment by devcshort** [comment]
@jonathansampson 
![image](https://user-images.githubusercontent.com/13677134/64129974-43dd7c80-cd74-11e9-81c3-f63b8ac00e6c.png)

**Comment by jonathansampson** [comment]
@devcshort Thank you. I suspect you're seeing the same issue as another user. I just did a quick debugging session with them, and we found that `l.total` was undefined in the render method. I've shared this with the team, and we'll be working on a fix for 0.69.x.
 
![image](https://user-images.githubusercontent.com/815158/64133732-0ee61f80-cd9e-11e9-903e-c132e1beae02.png)

**Comment by LaurenWags** [comment]
See https://github.com/brave/brave-browser/issues/5987#issuecomment-530364300 for ways to trigger white box from panel on `0.68.134`.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.138 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
- Verified the test plan from https://github.com/brave/brave-core/pull/3201
- Verified https://github.com/brave/brave-browser/issues/5336#issuecomment-530369362 and https://github.com/brave/brave-browser/issues/5336#issuecomment-530831439 - white popup issue no longer exists
