### ISSUE TITLE
Search box overlaps on Crypto wallet 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5337]
## Description 

Search box overlaps on Crypto wallet 

## Steps to Reproduce

   1. Update to `0.69.77`
   2. Open settings page
   3. Increase browser size so that the icons change to texts, search box gets overlapped on the new `Crypto Wallet` setting

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/61719336-b6e5e300-ad32-11e9-81c6-3e48f052a737.png)

## Expected result:
No overlapping buttons 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.69.77 Chromium: 76.0.3809.62 (Official Build) nightly (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

cc: @petemill @brave/design

**Comment by kjozwiak** [comment]
Reproducible on `macOS 10.14.5` using the following build:

Brave | 0.69.77 Chromium: 76.0.3809.62 (Official Build) nightly (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

Example of the issue occurring:

<img width="1100" alt="Screen Shot 2019-07-23 at 10 23 39 AM" src="https://user-images.githubusercontent.com/2602313/61720075-24deda00-ad34-11e9-943d-f4035428af61.png">

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.70.93 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description, increase browser size changes the texts to icons so no overlapping of search icon on crypto wallet

![image](https://user-images.githubusercontent.com/38657976/65024457-8bf2c680-d952-11e9-923c-b19f9fd21d88.png)

**Comment by kjozwiak** [comment]
@bbondy @rebron @ryanml the above is still an issue when the window is minimized to the following dimensions:

* `window.outerWidth` --> `501`
* `window.outerHeight` --> `444`

I'll create a new issue but not sure if it's even worth fixing/addressing.

Example:

<img width="531" alt="Screen Shot 2019-09-18 at 2 14 49 AM" src="https://user-images.githubusercontent.com/2602313/65119590-68fbfd00-d9ba-11e9-86a5-958b6178cf84.png">
