### ISSUE TITLE
Cannot navigate back to shields from blocked script details view

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5338]
## Description 

Cannot navigate back to shields from blocked script details view

## Steps to Reproduce

   1. Visit any site 
   2. Enable `Block script` in shields
   3. Click on `Scripts blocked` 
   4. Click on `Go Back` button in details view, doesn't work

## Actual result:

https://youtu.be/ISjDaoY_f7A

## Expected result:
Should take back to shields overview when `Go Back` button is clicked in detailed view

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.69.77 Chromium: 76.0.3809.62 (Official Build) nightly (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? N/A
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @cezaraugusto @karenkliu

**Comment by GeetaSarvadnya** [comment]
The issue is reproducible on Windows `10 x64 - 0.69.77`

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.110 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3034
Verified steps from the video https://youtu.be/ISjDaoY_f7A
