### ISSUE TITLE
[QUESTION] Extending "Sync" to other areas - timeline?

### ISSUE THREAD

**Issue by willstocks-tech** [brave/brave-browser#5340]
Hi guys,

Hope you're well!

This is a question (as opposed to an issue/bug/FR) that I didn't know the best place to put - is there a timeline anywhere of sync functionality _beyond_ that of bookmarks across devices? I'm talking:
- Passwords
- History
- Open tabs
- Rewards Wallet
- Settings(?)

Is there a dedicated timeline for these features? I know a few questions have been asked in community, but haven't really gotten much traction since the initial sync features (bookmarks) rolled out. I'm also aware of the [project](https://github.com/brave/brave-browser/projects/14) however this doesn't appear to have changed too much or indicate a timeline for any of these extra sync areas.

Thanks,

Will

**Comment by rebron** [comment]
Hi @willstocks-tech. I don't have a specific timeline that I can provide but all those items passwords, history, open tabs, rewards wallet, and settings are all part of the plan. We're addressing sync across desktop, android, iOS and users with multiple devices on those platforms. As soon as we have a timeline, we'll share it. 

Our attention is on the server side and as we're adding many more users we want to make sure we're serving our users well. Thanks for your patience. Sync with all these items is a feature that we want to use ourselves.

I'm going to close this out. Please post in community if you want to discuss more.
