### ISSUE TITLE
Add option for hiding widevine install prompt

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#5341]
With this new option from settings or widevine install dialog, user can choose whether widevine install prompt will be visible or not.

This is simple version of https://github.com/brave/brave-browser/issues/5068.

**Comment by GeetaSarvadnya** [comment]
@simonhong looks like step 7 should be notification `Turn off` and 8 should be `Turn on`. Please clarify

**Comment by simonhong** [comment]
@GeetaSarvadnya Done. You're right.
Initially setting was `Don't ask ...`. but it was changed to `Ask ...`.
I forgot to update it :) Thanks for checking 👍

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.70.97 Chromium: 77.0.3865.65 (Official Build) beta (64-bit)
-- | --
Revision | 87a331a3169cab563505fb44011058b904011ba1-refs/branch-heads/3865@{#726}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/2980
