### ISSUE TITLE
Brave apt repository requires an https-capable version of apt

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#5343]
From https://github.com/brave/brave-browser/issues/5111#issuecomment-514157514:

> I saw that brave's apt repo uses https, so, in order for apt to access it, apt should be "https=capable".
>
> Apt natively supports https in version 1.6.0 and newer, but it needs apt-transport-https to support it on version 1.5.x and older.
>
> This means that apt-transport-https must also be installed for ubuntu 14.04 (and mint 17.x, both eol by now), ubuntu 16.04 (and mint 18.x) and debian 9 (codenamed stretch). So please, add it as an additional step on the instructions for each distro.

**Comment by fmarier** [comment]
To keep things simple, I think I'll just add `apt install apt-transport-https` to all of the Debian-based distro instructions, regardless of the version.

More knowledgeable users are free to remove the empty transitional packages afterwards if they want or to skip that step entirely.

**Comment by fmarier** [comment]
According to the description for `apt-transport-https`, this package was integrated into `apt` 1.5, not 1.6:

>  This is a dummy transitional package - https support has been moved into the apt package in 1.5. It can be safely removed.

**Comment by kjozwiak** [comment]
@fmarier can you add the appropriate milestone on both the PR and issue?

**Comment by fmarier** [comment]
There's no milestone, it's just the docs on https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux and they're fixed now.
