### ISSUE TITLE
data:application items blocked by shields can't be allowed to run

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5346]
## Description 

data:application items blocked by shields can't be allowed to run

## Steps to Reproduce

   1. Install `0.69.77`
   2. Visit `https://theverge.com` and block scripts
   3. Click `Allow scripts once` until all first and third party scripts are loaded
   4. Open scripts detailed view, shows 1 item blocked for `data:application/` which cannot be allowed to run

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/61732969-d427ab00-ad4c-11e9-9606-7ee39e12693b.png)

## Expected result:
Should not list something that cant be allowed to run via shields settings

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.69.77 Chromium: 76.0.3809.62 (Official Build) nightly (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by cezaraugusto** [comment]
@yrliou thoughts on this? AFAIK we can only block scripts via origin

**Comment by bsclifton** [comment]
In older builds (0.67.x and earlier), this was showing up before as `null`:
<img width="275" alt="screen shot 2018-10-29 at 9 50 45 pm" src="https://user-images.githubusercontent.com/4733304/47696594-b9147a00-dbc4-11e8-95ae-fa7dbb5110bc.png">

0.68.x and newer, this issue properly captures the bugged behavior

Discussion was had with @cezaraugusto, @yrliou, @bbondy, @AndriusA 

Proposed fix would be:
Update blocking logic to allow for origin (existing behavior) OR full URL (covers this case)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.123 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Ubuntu 18.04 LTS

Verified the test plan from the description
![5884](https://user-images.githubusercontent.com/34715963/64303533-ef5f1a80-cf88-11e9-9ea5-46f164fc2e1a.gif)
