### ISSUE TITLE
Update crypto wallets icon

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#5348]
Followup to https://github.com/brave/brave-browser/issues/5235

Icon styling has been updated per @tomlowenthal direction. Should match:

<img width="576" alt="Screen Shot 2019-07-23 at 11 30 53 AM" src="https://user-images.githubusercontent.com/29072694/61737672-91120b80-ad3d-11e9-8bf0-6600800f9682.png">

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.70.97 Chromium: 77.0.3865.65 (Official Build) beta (64-bit)
-- | --
Revision | 87a331a3169cab563505fb44011058b904011ba1-refs/branch-heads/3865@{#726}
OS | Windows 10 OS Version 1803 (Build 17134.1006)


- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/65074284-26cebd80-d9b2-11e9-96be-5a8fcd3499a9.png)
