### ISSUE TITLE
Disintermediate Outbound Links

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#535]
Popular sites — search engines, social networks — often rewrite outbound links for tracking purposes. We should disintermediate these links and let users just head straight to their destinations. https://www.eff.org/deeplinks/2018/05/privacy-badger-rolls-out-new-ways-fight-facebook-tracking

Replaces brave/browser-laptop#14163

**Comment by fmarier** [comment]
We took a different approach with the query string filter to block tracking from search engines and Facebook. I believe the bulk of the privacy harms are already mitigated there.

Additionally, disintermediating all of these redirects is likely to have security implications (Facebook does perform checks against outbound links) and interfere with how search engines count clicks and improve their search results. They could always monitor their pages for clicks anyways, so it's not clear these redirects are giving them much extra tracking capabilities.
