### ISSUE TITLE
Show All button for download bar not visible with dark theme or on Tor window

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5350]
## Description 
When download bar is displayed on Tor window (or on regular window with dark theme), the Show All button is a white box. 

Note - private window it displays fine. 

This did not occur in 0.66.x (currently released version).

## Steps to Reproduce

   1. Open a Tor window.
   2. Start a download. --> Show All button is a white box.
   3. Repeat for normal window with light theme, Show All button displays fine.
   4. Repeat for normal window with dark theme, Show All button is white box.
   5. Repeat for private window, Show All button displays fine.
   6. Repeat for guest window, Show All button displays fine.

## Actual result:
Dark theme:

![Screen Shot 2019-07-23 at 3 32 19 PM](https://user-images.githubusercontent.com/28145373/61742364-f4f9fb80-ad60-11e9-8e9a-5349c1d494b1.png)

Light theme:
![Screen Shot 2019-07-23 at 3 32 55 PM](https://user-images.githubusercontent.com/28145373/61742390-0216ea80-ad61-11e9-9984-ad55562403a3.png)

## Expected result:
Show All button should not be a white box in any case.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.67.112 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes, 0.67.112
- Can you reproduce this issue with the dev channel? unsure 
- Can you reproduce this issue with the nightly channel? no, did not reproduce with 0.69.77 on nightly

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @kjozwiak to try with 'same as macOS' setting for theme.

**Comment by LaurenWags** [comment]
For reference, this is how these windows look in 0.66.101:
Dark Theme:
![Screen Shot 2019-07-23 at 3 51 29 PM](https://user-images.githubusercontent.com/28145373/61742767-d8aa8e80-ad61-11e9-906a-a5025413d657.png)

Light theme:
![Screen Shot 2019-07-23 at 3 52 35 PM](https://user-images.githubusercontent.com/28145373/61742800-ea8c3180-ad61-11e9-892f-87f55bdeb6c3.png)

**Comment by rebron** [comment]
cc: @simonhong

**Comment by simonhong** [comment]
I think https://github.com/brave/brave-core/pull/2905 can fix this.
How about uplifting it to 67.x?

**Comment by kjozwiak** [comment]
Used the following cases for each version and couldn't reproduce what @LaurenWags is seeing:

`Case #1`:

* launch brave (new profile)
* go into `chrome://settings/appearance` and change `Brave colors` --> `Dark`
* visit https://www.thinkbroadband.com/download and download `Extra Small File (5MB)`

`Case #2`:

* launch brave (new profile)
* change macOS theme to `Dark`
* go into `chrome://settings/appearance` and ensure that `Brave colors` --> `Same as macOS`
* visit https://www.thinkbroadband.com/download and download `Extra Small File (5MB)`

Builds being used:

* `0.67.114 Chromium: 76.0.3809.62` - Couldn't reproduce both cases
* `0.68.108 Chromium: 76.0.3809.62` - Couldn't reproduce both cases
* `0.69.77 Chromium: 76.0.3809.62` - Couldn't reproduce both cases

I wonder if this only happens on macOS versions older than `Mojave`? @rebron are you seeing the above on your end? Mind checking with the latest `beta`?

@LaurenWags is there specific steps I should be using or the cases that I mentioned above should have reproduced the issue?

**Comment by rebron** [comment]
Hmm. I'm not able to reproduce with 0.67.112 on macOS Tor window. Looks ok. Let me try on a couple different mac versions though.

**Comment by simonhong** [comment]
I found some regressions with C76 rebase because C76 rebase included some brave theme refactoring. Because of this, this regression happens current Beta...
I'm working on this.
------------------------

* WebUI theme is changed to dark when tor window is created
    * Set os theme as Dark
    * Launch browser
    * Set browser theme as Light
    * Launch Tor window
    * Check settings page theme is changed to Dark
    * Cause: When Tor window is created its BraveThemeService set system theme as a dark
    * Fix: Don’t set system theme type when tor/guest profile is created

* Tor/Guest window native theme(download bar) is changed when brave theme in normal window is changed
    * Launch browser
    * Launch Tor Window and load settings page
    * Change Brave theme from settings in normal window
    * Tor Window theme should not be changed and only normal window should be changed
    * Cause: Tor/Guest window uses sam ui::NativeTheme::GetInstanceForNativeUi()
    * Fix: Tor/Guest window should use NativeThemeDarkAura

* Tor window Show All button is white
    * Launch browser
    * Launch Tor window and download anything
    * Change brave theme to Light in normal window settings
    * Show All button is white in Tor window
    * Cause: Tor/Guest window uses same ui:NativeTheme::GetInstanceForNativeUi()
    * Fix: Tor/Guest window should use NativeThemeDarkAura

* Normal window with dark mode has White Show All button on Beta
    * Need to investigate (seems happening only old MacOS)
    * Launch Beta browser (0.67)
    * Set brave theme as a dark
    * Launch Tor window
    * Download from normal window and View all button is white

**Comment by LaurenWags** [comment]
@kjozwiak yep, your `Case #1` from https://github.com/brave/brave-browser/issues/5350#issuecomment-514443105 reproduces for me. I can't try `Case #2` because I'm on High Sierra. But as @simonhong noted in https://github.com/brave/brave-browser/issues/5350#issuecomment-514599908 some items are only affecting older macOS versions.

In addition to your case 1, here are some cases I tried where I can reproduce every time:
A.
1. Clean profile. (don't adjust any settings)
2. Launch Tor window. 
3. Download a file in Tor window. --> show all button is white.

B.
1. Clean profile. (don't adjust any settings)
2. Download a file in normal window, don't dismiss download bar.
3. Change theme to dark. --> show all button is white.

**Comment by srirambv** [comment]
This is not an issue on Linux. Download bar is always dark, irrespective of the theme set (I guess this is expected) and the `Show All` button is always dark with white text irrespective of theme set. Same behaviour on both Normal and Tor windows

**Comment by simonhong** [comment]
@srirambv Still button is normal after setting Light theme?

**Comment by srirambv** [comment]
@simonhong yes. Changing the theme and relaunching Tor window doesn't make a difference. Looks like the issue is probably only for mac. I'll check on Windows and update

**Comment by srirambv** [comment]
Windows do have the white button issue. Here's what I did
1. Download file on a normal window
2. Change theme to Same as window/Light uses white download bar with dark text button (expected)
3. Change theme to dark uses dark download bar with dark button with white text (expected)
4. Download file on Tor window
5. Dark theme uses dark download bar with the white button (expected)
6. Light/Same as windows uses a dark download bar with a white button and invisible text (problem)

![download](https://user-images.githubusercontent.com/17010094/61800699-84ec8380-adfb-11e9-8341-9676d661286f.gif)

**Comment by simonhong** [comment]
@srirambv Thanks for checking.
I pushed https://github.com/brave/brave-core/pull/2992 and I think it will fix all the above issues. :)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.69.130 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

* Verified `Show all` button is not white on both dark/light theme on normal window
* Verified `Show all` button is not white on Private windows
* Verified `Show all` button is not white on Tor windows
* Verified `Show all` button is not white on Guest window
