### ISSUE TITLE
WebTorrent: Show torrent name when possible

### ISSUE THREAD

**Issue by feross** [brave/brave-browser#5351]
## Description 

Torrent name should be preferred over the name of the torrent file, when possible. We show the torrent file name (big-buck-bunny.torrent) but we should attempt to show the torrent name (e.g. Big Buck Bunny) when it is available which is usually once the torrent has been started and metadata has been fetched transfer has started.

## Steps to Reproduce

   1. Visit https://webtorrent.io/free-torrents
   2. Click Big Buck Bunny (torrent file)
   3. Start download
   4. See that title shows up as "big-buck-bunny.torrent" instead of "Big Buck Bunny"

## Actual result:

![Screen Shot 2019-07-23 at 1 03 45 PM](https://user-images.githubusercontent.com/121766/61743844-e30d5e00-ad4a-11e9-8a16-40de340d2f6f.png)

## Expected result:
![Screen Shot 2019-07-23 at 1 03 40 PM](https://user-images.githubusercontent.com/121766/61743850-e6084e80-ad4a-11e9-86b0-b2a472f60326.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Version 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.96 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/2985

![image](https://user-images.githubusercontent.com/34715963/65102445-605ff280-d9cb-11e9-80d3-f7d9c15cc94a.png)
