### ISSUE TITLE
WebTorrent: Stats remain stuck after download finishes

### ISSUE THREAD

**Issue by feross** [brave/brave-browser#5352]
## Description 

When a torrent finishes, the stats stop updating and stay stuck on the last state, which may show that e.g. there's still a download rate of 2.4 MB/s (when in fact the download rate is 0 MB/s) as can be seen here:

![Screen Shot 2019-07-23 at 1 16 19 PM](https://user-images.githubusercontent.com/121766/61744445-2e743c00-ad4c-11e9-8808-5fb3971342f4.png)

## Steps to Reproduce

   1. Visit https://webtorrent.io/free-torrents
   2. Click Big Buck Bunny (torrent file)
   3. Start torrent download
   4. Wait for the download to complete and look at the stats

## Actual result:

Stats freeze

## Expected result:

Stats continue updating when download is complete

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No 
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.96 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3004

![image](https://user-images.githubusercontent.com/34715963/65102695-2a6f3e00-d9cc-11e9-86d9-893b2daf3dde.png)
