### ISSUE TITLE
WebTorrent: Torrents stats layout issues

### ISSUE THREAD

**Issue by feross** [brave/brave-browser#5353]
## Description 

Spacing of the torrents stats is uneven. Appears to be using table cells that are equal size which leads to uneven spacing and wrapping on the time remaining cell as can be seen here:

![Screen Shot 2019-07-23 at 1 17 56 PM](https://user-images.githubusercontent.com/121766/61744537-65e2e880-ad4c-11e9-85e1-bb7e06c99093.png)

## Steps to Reproduce

   1. Visit https://webtorrent.io/free-torrents
   2. Click Big Buck Bunny (torrent file)
   3. Start downloading torrent
   4. Look at the stats

## Actual result:

Spacing is uneven and wrapping occurs on time remaining

## Expected result:

Spacing is event and no wrapping occurs

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No 
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.96 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3003

![image](https://user-images.githubusercontent.com/34715963/65102445-605ff280-d9cb-11e9-80d3-f7d9c15cc94a.png)
