### ISSUE TITLE
WebTorrent: Rename "Save File" button to make functionality clearer

### ISSUE THREAD

**Issue by feross** [brave/brave-browser#5354]
## Description 

When clicking on a .torrent file, the button "Save File" that appears implies to me that the torrent's contents can be saved by clicking it. In fact, this button downloads the .torrent file.

I recommend naming this "Save .torrent File" instead. Feedback from the design team is welcome.

## Steps to Reproduce

   1. Visit https://webtorrent.io/free-torrents
   2. Click Big Buck Bunny (torrent file)
   3. Start downloading torrent
   4. Look at the "Save File" button

## Actual result:

![Screen Shot 2019-07-23 at 1 36 05 PM](https://user-images.githubusercontent.com/121766/61745651-d985f500-ad4e-11e9-8638-c0aa69ced76f.png)

## Expected result:

"Save .torrent File"

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No 
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by rebron** [comment]
cc: @rossmoody

**Comment by feross** [comment]
@rossmoody's mocks for the redesign we're discussing in https://github.com/brave/brave-browser/issues/5402 and on Slack in `#webtorrent` use this new copy, so let's go ahead with it.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.96 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3036
During downloading
![image](https://user-images.githubusercontent.com/34715963/65102811-a10c3b80-d9cc-11e9-91f0-ad11ce2fece0.png)

Downloading is finished
![image](https://user-images.githubusercontent.com/34715963/65102772-7e7a2280-d9cc-11e9-8ff1-5cbf1837c124.png)
