### ISSUE TITLE
Shields read-only view should show real resources blocked

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#5355]
At the moment it shows a hard-coded version of resources.

### Test Plan

1. Fresh profile
2. Open Shields
3. Click "Learn more"
4. Click any resource blocked

### What happens
Stats are hard-coded at 2. A hard-coded resource blocked is shown.

### What should happen
Should show a list of resources blocked on the current site

**Comment by kjozwiak** [comment]
@cezaraugusto once this is closed, please add either `QA/Yes` or `QA/No` as needed 👍

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.69.113 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/2987
- Verified that the blocked resources count is not hardcoded
- Verified that resources or scripts blocked are referred to a current website

![image](https://user-images.githubusercontent.com/38657976/63767042-1fa01c80-c8ea-11e9-9a2d-d6a03342a7c2.png)
