### ISSUE TITLE
WebTorrent: Video streaming is broken since upgrade to WebTorrent v0.105.0

### ISSUE THREAD

**Issue by feross** [brave/brave-browser#5358]
## Description 

It appears that WebTorrent video playback is broken on Nightly, ever since the upgrade to WebTorrent v0.105.0.

The `URL` constructor is undefined on this line in `webtorrent/lib/server.js`:

https://github.com/webtorrent/webtorrent/blob/78d98d9fa45598b63fb0fec013036e35d167f6c3/lib/server.js#L80

The reason appears that webpack replaces this line:

https://github.com/webtorrent/webtorrent/blob/78d98d9fa45598b63fb0fec013036e35d167f6c3/lib/server.js#L6

with:

```
const URL = __webpack_require__(/*! url */ "./node_modules/url/url.js").URL
```

and the `url` package doesn't export `URL` as `url.URL` even though it exists in the chrome extension environment. I can fix this on the `webtorrent` side and publish a new version.

cc @yrliou

## Steps to Reproduce

   1. Go to https://webtorrent.io/free-torrents
   2. Click on Big Buck Bunny (torrent file)
   3. Start download
   4. Right click on "Big Buck Bunny.mp4" and "Open Link in New Tab" (to workaround #3966)
   5. The video does not load.
   6. Check the WebTorrent extension background process (via `brave://inspect/#extensions`) to see the exception.

## Actual result:

![Screen Shot 2019-07-23 at 3 37 52 PM](https://user-images.githubusercontent.com/121766/61752246-dc3d1600-ad5f-11e9-89ac-75f835131157.png)

## Expected result:

Video plays

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Nightly. Version 0.69.77 Chromium: 76.0.3809.62 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

**Comment by feross** [comment]
There's a new release of `webtorrent` with the fix. Version 0.105.1. We just need to pull it into Brave.

**Comment by feross** [comment]
Re-opening until https://github.com/brave/brave-core/pull/2989 is merged.

**Comment by kjozwiak** [comment]
Moving this into the `0.70.x - Nightly` milestone as per https://github.com/brave/brave-core/pull/2989.

**Comment by yrliou** [comment]
This is fixed in 0.69.x too now because we upgrade WebTorrent to 0.105.1 in 0.69.x.

**Comment by feross** [comment]
@yrliou Thank you for debugging this issue!

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Ubuntu 18.04 LTS

Verified test plan from the description.

Was able to stream the video
![image](https://user-images.githubusercontent.com/34715963/64353003-44d50f00-cffd-11e9-84f5-4e013d49dcd0.png)
No exception in the console(only warnings):
![image](https://user-images.githubusercontent.com/34715963/64353138-8960aa80-cffd-11e9-98ab-de6585b20b3d.png)
