### ISSUE TITLE
Brave should not intercept non-navigation .torrent file requests

### ISSUE THREAD

**Issue by feross** [brave/brave-browser#5361]
## Description 

If a web page embeds the WebTorrent client-side JS library and attempts to load a `.torrent` file using an XHR request or `fetch`, Brave will intercept the `.torrent` file load and replace it with the `chrome-extension` HTML, breaking the site. This is true not just for the WebTorrent JS library but for any request to fetch a `.torrent` file.

There's a CodePen that demonstrates this here: https://codepen.io/yciabaud/pen/XdOeWM

## Steps to Reproduce

   1. Visit https://codepen.io/yciabaud/pen/XdOeWM
   2. The torrent demo should fail with an error in the console.
   3. Now, disable the WebTorrent extension in Brave settings.
   4. The demo now works.

## Actual result:

```
Uncaught Error: Error downloading torrent: XHR error
    at VM37 webtorrent.min.js:5
    at t.exports.<anonymous> (VM37 webtorrent.min.js:7)
    at t.exports.t (VM37 webtorrent.min.js:5)
    at t.exports.r.emit (VM37 webtorrent.min.js:4)
    at XMLHttpRequest.c.onerror (VM37 webtorrent.min.js:7)
```

## Expected result:

Brave should not intercept requests for `.torrent` files unless they are top-level navigation requests.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by feross** [comment]
WebTorrent users reporting the issue here: https://github.com/webtorrent/webtorrent/issues/1649

**Comment by feross** [comment]
This also fixes this old issue: https://github.com/brave/browser-laptop/issues/10672

**Comment by kjozwiak** [comment]
@feross just a quick double check. When opening https://codepen.io/yciabaud/pen/XdOeWM while `WebTorrent` is enabled, it looks like the client-side JS library loads the `.torrent` and starts downloading it as per:

<img width="1345" alt="Screen Shot 2019-09-18 at 1 40 29 AM" src="https://user-images.githubusercontent.com/2602313/65114994-61862500-d9b5-11e9-8dc6-08f897f72974.png">

Is the above the expected behaviour? When you have WebTorrent either enabled or disabled, you'll get the above and Brave will start loading the `.torrent`.

**Comment by feross** [comment]
@kjozwiak Yep, this is expected behavior. This is JavaScript code running on the website itself and has nothing to do with the built-in WebTorrent implementation in Brave. It's supposed to work in both cases -- when the WebTorrent extension is enabled or disabled.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

* ensured that https://codepen.io/yciabaud/pen/XdOeWM works when `WebTorrent` is both enabled and disabled as per https://github.com/brave/brave-browser/issues/5361#issuecomment-532529740
