### ISSUE TITLE
Bitcoin Cash and Dash missing as funding option under rewards add-funds.

### ISSUE THREAD

**Issue by greatwolf** [brave/brave-browser#5363]
Are there any plans to add these two coins as a funding mechanism for Brave? According to Brendan Eich's tweet: https://twitter.com/brendaneich/status/1142230515728056320 these two should already be there. But I am not seeing it as an option in Brave even with the nightly build release.

**Comment by NejcZdovc** [comment]
thank you for the issue. We added support for two way wallet, where you are adding funds via uphold page where you have a lot of options.
