### ISSUE TITLE
minute cherry trial surround midnight hold famous pupil lyrics offer achieve slow rescue maid maple dirt afford evoke fame choice either broccoli blossom race

### ISSUE THREAD

**Issue by Ithan007** [brave/brave-browser#5365]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
@Ithan007 looks like you pasted either sync keywords or your wallet keywords publicly 🙀Wanted to share in case you needed to take any action on your part (create a different sync group, create a new wallet, etc)
