### ISSUE TITLE
Claim is not working

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#5366]
## Description 

Claim process for anon user funds doesn't work.

## Steps to Reproduce

   1. enable rewards
   2. recover old wallet with some user funds (no grants)
   3. connect uphold KYC'd wallet

## Actual result:

nothing happens

## Expected result:
user funds should be transfer into connected uphold wallet

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with


Brave | 0.69.114 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

(all testing completed on Staging env)
* Verified test plan from https://github.com/brave/brave-core/pull/2996 
* Verified BAT from anon wallet moved to my verified, KYC'd `Brave Browser` card on Uphold. Verified if I started a clean profile and restored the previous anon wallet, it showed a 0 balance on restore as the BAT had been moved. Confirmed on balance-staging and ledger-staging servers.
* Verified BAT from anon wallet was not to my verified, un-KYC'd `Brave Browser` card on Uphold. Verified if I started a clean profile and restored the previous anon wallet, it showed a non-0 balance on restore as the BAT had not been moved. Confirmed on balance-staging and ledger-staging servers.
* Note, https://github.com/brave/brave-browser/issues/5344 is logged for if you do the steps out of order from test plan (verify wallet and then restore anon wallet with balance)
