### ISSUE TITLE
Tor window continues to download even if you exit 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5367]
## Description 

Tor window continues to download even if you exit 

## Steps to Reproduce

   1. Open Tor window and start downloading a large file 
   2. Close the Tor window
   3. A warning shows up asking to `Continue download` or `Exit`
   4. Click on Exit and close the Tor window
   5. Launch a new Tor window and close it, you get the same download warning message
   6. Open downloads page you can see the download is in progress
   7. Close the main browser window, shows the same download warning message even though download was triggered in Tor window

## Actual result:

Tor window continues to download even if you exit 

## Expected result:
Download should be cancelled if Tor window is closed and not wait for the main browser window to be closed to cancel

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
-- | --
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

cc: @tomlowenthal @riastradh-brave

**Comment by kjozwiak** [comment]
Reproduced on `macOS 10.14.5 x64` using the following builds:

Brave | 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
-- | --
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Mac OS X

Brave | 0.69.77 Chromium: 76.0.3809.62 (Official Build) nightly (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

**Comment by diracdeltas** [comment]
is this the same for non-tor private windows?

**Comment by riastradh-brave** [comment]
Also, is it the same for guest windows?

**Comment by srirambv** [comment]
@diracdeltas It doesn't reproduce on Private window. Exit cancels the download and is not shown in downloads page

@riastradh-brave yes reproduces on Guest windows. Exit doesn't cancel the download. Opening a new Guest window and closing it prompts the warning again to continue to download or exit.

**Comment by tomlowenthal** [comment]
Sounds like this is a problem with Guest windows and it'll be fixed when we implement #2307.

**Comment by yrliou** [comment]
I just tried it in Nightly, appears to be fixed as a part of fixing #2307 .

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.72.110 Chromium: 78.0.3904.70 (Official Build) dev (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

Verified test plan from the description.
Verified that the file can be fully downloaded.
Verified that the download in canceled after exiting tor window.
Verified that the the file being downloaded is not listed in `brave://downloads` after reopening tor window.
Verified that the file being downloaded is deleted after exiting tor window
