### ISSUE TITLE
Chromium incognito icons used in Private and Tor window for downloads

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5368]
## Description 

Chromium incognito icons used in Private and Tor window for downloads

## Test plan / Steps to Reproduce
   1. Download a file in Private window or Tor window
   2. Open downloads page 
   3. Shows Chromium incognito icon next to the downloaded file and tool tip shows `Downloaded in Incognito`

## Actual result:

![Screenshot from 2019-07-24 10-34-48](https://user-images.githubusercontent.com/17010094/61802591-bca8fa80-adfe-11e9-8c99-bf20757312b6.png)

## Expected result:
Should not use any Chromium branding 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
-- | --
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by kjozwiak** [comment]
Appears as `Downloaded in Private` on `macOS`. Example:

<img width="716" alt="Screen Shot 2019-07-24 at 12 01 54 PM" src="https://user-images.githubusercontent.com/2602313/61809320-0e578200-ae0b-11e9-8221-dec88d5984d8.png">

**Comment by rebron** [comment]
cc: @rossmoody @simonhong Can you guys take a look, I know you guys fixed something similar just recently?

**Comment by rossmoody** [comment]
@simonhong Found it: https://cs.chromium.org/chromium/src/chrome/browser/resources/downloads/images/incognito_marker.svg?sq=package:chromium&g=0

Any idea how we'd replace that since it isn't a SKIA swap?

**Comment by simonhong** [comment]
@rossmoody To replace `incognito_marker.svg` with ours, we just need to copy from `brave/browser/resources/downloads/images/incognito_marker.svg`
`chrome/browser/resources/downloads/images/incognito_marker.svg
` like https://github.com/brave/brave-browser/blob/master/lib/util.js#L174.

**Comment by rossmoody** [comment]
Nice, I didn't know that file existed. This should do the trick. 
```
<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><path d="M2.212 7.54c.092.299.276 2.029.827 2.528.568.514 2.713.506 3.123.283.92-.498 1.292-2.107 1.454-2.812C7.708 7.14 8 7.14 8 7.14s.308 0 .4.4c.163.704.519 2.318 1.437 2.815.41.223 2.555.231 3.125-.282.55-.5.734-2.235.826-2.534.091-.299.551-.598.643-.698.092-.1.092-.498 0-.598-.184-.2-2.352-.377-4.686-.1-.466.055-.643.2-1.746.2-1.102 0-1.28-.145-1.745-.2-2.333-.277-4.501-.1-4.685.1-.092.1-.092.499 0 .599.092.1.551.399.643.698z" id="a"/></defs><g fill="none" fill-rule="evenodd"><path d="M8 0C3.578 0 0 3.578 0 8c0 4.422 3.578 8 8 8 4.422 0 8-3.578 8-8 0-4.422-3.578-8-8-8z" fill="#5F6368" fill-rule="nonzero"/><use fill="#FFF" xlink:href="#a"/></g></svg>
```

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.5.102 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified STR from description for both Private and Tor windows using both light and dark themes. 

<img width="1195" alt="Screen Shot 2020-02-27 at 11 09 56 AM" src="https://user-images.githubusercontent.com/28145373/75462784-c4132200-5952-11ea-8f1b-4605fd9202d7.png">

<img width="1196" alt="Screen Shot 2020-02-27 at 11 10 09 AM" src="https://user-images.githubusercontent.com/28145373/75462791-c5dce580-5952-11ea-8f67-208e71942af7.png">

<img width="1193" alt="Screen Shot 2020-02-27 at 11 14 22 AM" src="https://user-images.githubusercontent.com/28145373/75462797-c7a6a900-5952-11ea-90f7-284318e83170.png">

<img width="1192" alt="Screen Shot 2020-02-27 at 11 14 07 AM" src="https://user-images.githubusercontent.com/28145373/75462805-c9706c80-5952-11ea-9f48-22dc837dd2a3.png">
