### ISSUE TITLE
Test for unexpected non-user-initiated network activity

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#537]
We should ensure that any network request Brave makes without user interaction is deliberate. With a whitelist of expected network requests, we can test Brave build candidates to ensure that they don't make other network requests.

Replaces brave/browser-laptop#12690

**Comment by diracdeltas** [comment]
i think this was done with https://github.com/brave/brave-browser/pull/1682 and AFAIK the audit command is running in the build pipeline now
