### ISSUE TITLE
brave://welcome page background needs to be adjusted for RTL languages

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5377]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/3574

Background of the brave://welcome page for right to left languages (such as Hebrew or Arabic) doesn't match those of left to right languages (English, etc).

When brave://welcome is displayed for a RTL language, the background image is only on half the page. Additionally, when you go thru the onboarding pages, the background is white, so you have a white box on a white background.  

## Steps to Reproduce

   1. Set language to a RTL one such as Arabic or Hebrew
   2. Clean profile, launch Brave

## Actual result:
See how background is on half the page. Additionally, as you move thru the flow, the background is white on each box.
![onboarding-arabic](https://user-images.githubusercontent.com/28145373/61825020-73bc6a80-ae2d-11e9-8529-4a60ae8c93e2.gif)

## Expected result:
Should be like the LTR languages:
![onboarding-english](https://user-images.githubusercontent.com/28145373/61825035-7ae37880-ae2d-11e9-86c8-c5fe6dc55e77.gif)

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
-- | --
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Mac OS X

Brave | 0.67.112 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? unsure but probably
- Can you reproduce this issue with the nightly channel? unsure but probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment]
cc: @rossmoody I believe this was fixed in 70.x?

**Comment by rossmoody** [comment]
I'd say this is worth closing because the background doesn't exist like that anymore.

**Comment by rebron** [comment]
Closing. Fixed in 70.x

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
