### ISSUE TITLE
Errors related to TFuel collection on sliver.tv

### ISSUE THREAD

**Issue by snyderp** [brave/brave-browser#5380]
Currently users on sliver.tv are unable to collect tfuel.com.  This error was reported by sliver.tv and resulted to in this error in the logs:

```Request URL: https://prod-testnet-grouping.thetatoken.org:8700/socket.io/?EIO=3&transport=polling&t=Mlzrc4y&sid=iS5gQHlvkirp3-7YCETV
Request Method: POST
Status Code: 400 
Remote Address: 3.13.194.243:8700
Referrer Policy: no-referrer-when-downgrade

**Comment by bsclifton** [comment]
@snyderp do you have some steps QA can try for this?

**Comment by snyderp** [comment]
@bsclifton Here are the steps and communication between @lukemulks and the Sliver.tv folks, describing the issue.  My testing was just to make sure the error the sliver.tv folks reported disappeared, but I believe @lukemulks confirmed w/ the site that it addresses the below problem:

from @lukemulks 

> Apologies in advance if this seems a little dense on my behalf, but I just performed the following tasks: 
> 
> 1. Signed up through the Sliver website
> 2. Claimed my 1000 coins on signup. 
> 3. Started watching video streams. 
> 4. My Coins have incremented up from 1000 to 1430 during the duration. 
> 
> I realize that a network call is being blocked, and the console looks a little off, but that aside, it appears that I'm earning coins as I watch streams. 
> 
> Is the issue around the error messages in the console, or around the ability to earn being broken by our shields? I've been able to earn over 400 coins in less than 10min by watching streams. 

Sliver.tv reply

> Hey, quick clarification, coins are earned by watching, which is our free currency.
> 
> Our premium currency, Theta Fuel (TFuel), is earned by peering with others in the network to relay video streams. It is TFuel earning that is the issue, not coins.

I hope this helps!

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.5 x64` using the following build:

Brave | 0.67.119 Chromium: 76.0.3809.72 (Official Build) (64-bit)
-- | --
Revision | 5a04c669126f657f98824b436555cae41b8f4146-refs/branch-heads/3809@{#897}
OS | Mac OS X

* ensured that I received regular coins when watching streams
* ensured that I received `TFUEL` coins when watching `TFUEL` enabled streams
* ensured that `PENDING EARNINGS` & `EARNINGS THIS SESSION` were being updated
* ensured that ~10 minutes, my earned `TFUEL` were being submitted to the `Theta Blockchain`

<img width="1311" alt="Screen Shot 2019-07-29 at 3 20 09 PM" src="https://user-images.githubusercontent.com/2602313/62076106-d5594c00-b214-11e9-936a-22f32c4f47da.png">

**Comment by srirambv** [comment]
Verification passed on

Brave | 0.67.119 Chromium: 76.0.3809.72 (Official Build) (64-bit)
-- | --
Revision | 5a04c669126f657f98824b436555cae41b8f4146-refs/branch-heads/3809@{#897}
OS | Linux 

* Verified regular coins were added to profile while viewing videos
* Verified streaming TFuel videos added  token to profile
* Verified pending earning and earnings this session is updated correctly 
![image](https://user-images.githubusercontent.com/17010094/62083962-19a11800-b226-11e9-8889-2e79bbe82534.png)
