### ISSUE TITLE
Implement cosmetic blocking [tracking]

### ISSUE THREAD

**Issue by snyderp** [brave/brave-browser#5381]
Would be great to support EasyList and similar cosmetic filter rules.  Much of this work has already been done in https://github.com/brave/adblock-rust.  This issue is a tracking issue to keep track of all the branches and changes needed across multiple projects to land this in brave-browser.

**Comment by antonok-edm** [comment]
Relevant tracking issue in `adblock-rust`: https://github.com/brave/adblock-rust/issues/38

**Comment by antonok-edm** [comment]
Relevant tracking issue in `adblock-rust-ffi`: https://github.com/brave/adblock-rust-ffi/issues/3

**Comment by bsclifton** [comment]
When another fix is attempted, we'll want to link to test plan if manual QA is required. If not and everything is covered by automation, we can change label to `QA/No`

**Comment by szaimen** [comment]
So I have enabled the cosmetic filtering option over brave://flags. But as soon as I visit a website, brave nightly crashes on Windows 10. I also cannot find any additional option concerning cosmetic filtering in the brave settings after relaunch after I enabled the flag.

Is there something I have missed to enable this option?

**Comment by antonok-edm** [comment]
@szaimen crashes on Windows should be fixed as of https://github.com/brave/brave-core/pull/4540.

Currently there are no additional settings regarding cosmetic filtering; this work supports the cosmetic filters that will soon be shipped from our filter lists.

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` label for now.

Per discussion with @rebron not all PRs needed for this are currently in 1.5.x so this needs some sorting before QA can test.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.5.109 Chromium: 80.0.3987.132 (Official Build) beta (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from description

https://enpt.dict.cc/ without cosmetic blocking flag enabled:
<img width="964" alt="Screen Shot 2020-03-11 at 4 36 03 PM" src="https://user-images.githubusercontent.com/28145373/76461763-dfe8e000-63b6-11ea-9b87-15e824e7c2fa.png">

https://enpt.dict.cc/ after cosmetic blocking flag enabled:
<img width="1190" alt="Screen Shot 2020-03-11 at 4 37 03 PM" src="https://user-images.githubusercontent.com/28145373/76461812-f858fa80-63b6-11ea-8562-fedb7b3835c8.png">

* Also did a spot check of some other sites, no majorly noticeable issues. Display of some sites, such as buzzfeed.com improved. 

buzzfeed.com without cosmetic blocking flag enabled:
<img width="1193" alt="Screen Shot 2020-03-11 at 4 36 33 PM" src="https://user-images.githubusercontent.com/28145373/76461822-fee77200-63b6-11ea-8361-27e6772cfe40.png">

buzzfeed.com with cosmetic blocking flag enabled:
<img width="1193" alt="Screen Shot 2020-03-11 at 4 37 23 PM" src="https://user-images.githubusercontent.com/28145373/76461833-0444bc80-63b7-11ea-93da-ca07d0484dcc.png">
