### ISSUE TITLE
Crypto Wallets menu item is present on official builds

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#5383]
In the settings toolbar, It should only be in unofficial builds for now, to match `brave_wallet_enabled`

1. In official build, navigate to `brave://settings`

## Expected Behavior
2. `Crypto Wallets` menu item is not present

## Actual Behavior
2. `Crypto Wallets` menu item is present and leads to missing page

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

* ensured that `Crypto Wallets` appeared under `brave://settings` without any issues
* ensured that clicking on `Crypto Wallets` opened `brave://wallets` on new profiles without issues
