### ISSUE TITLE
Unable to uninstall wildvine

### ISSUE THREAD

**Issue by AlexCombas** [brave/brave-browser#5385]
I installed the deb package spotify-client from spotify and it asked to install "wildvine" from Google. 
I accepted and installed it. 
Now I would like to uninstall it, but it is not listed among the extension, and I do not see an option anywhere even showing that it is installed. 
How can I uninstall wildvine from the Brave browser?

**Comment by simonhong** [comment]
Hi @AlexCombas,
You can delete it from user dir like `rm -rf ~/.config/BraveSoftware/Brave-Browser/WidevineCdm` if you are using stable version.
Please make sure it's not deleting the whole user dir.
Then, you will see Widevine install prompt again after launching brave.
We have an issue for install/uninstall Widevine from settings.(https://github.com/brave/brave-browser/issues/2791)
Hope this helps!

**Comment by kjozwiak** [comment]
@AlexCombas hopefully the instructions that @simonhong mentioned worked for you and you were able to remove Widevine from your system. As @simonhong mentioned above, we have #2791 filed to give users the ability to disable/enable and remove Widevine. You can addd a +1 or any other information regarding being able to remove Widevine in #2791.

**Comment by AlexCombas** [comment]
Thank you.

**Comment by TheArchsage** [comment]
This seems to no longer be a viable option for removal.
The "WidevineCDM" no longer seems to be accessible
