### ISSUE TITLE
Issue Reporting Method For Brave.Com Problems

### ISSUE THREAD

**Issue by Golutazem** [brave/brave-browser#5386]
A method of reporting problems with Brave.Com sites, including the WWW forum is needed. That could be by designating a GITHub project to be used for filing issues.  Using an issue tracker would probably be the most manageable way.

Registration of a new account at the forum is failing without any error message. I attempted to register in order to make this request at the forum.
I have multiple issues to report.

**Comment by kjozwiak** [comment]
@Golutazem are you having issues registering on https://community.brave.com? CCing @Brave-Matt for assistance if that's the case.

@w0ts0n what do you think of opening up a public repo that users can use to submit issues for the various Brave web properties?

**Comment by w0ts0n** [comment]
As @kjozwiak has mentioned, can you get a little bit more detail about which site you are struggling to register for?

And yes, I think that's a great idea. ```brave-websites``` or something similar.

**Comment by kjozwiak** [comment]
> And yes, I think that's a great idea. brave-websites or something similar.

Awesome, once we get a public repo going, lets share it in this issue so @Golutazem can report the issues he's found 👍

**Comment by rebron** [comment]
Thanks for the report. If you have any issues please use community. This is more for reporting product issues.

**Comment by bsclifton** [comment]
@Golutazem this GitHub repo is for tracking problems with the Desktop product itself; if there are issues with the website, can you please sign up on community.brave.com and report there? Thanks! 😄

**Comment by Golutazem** [comment]
@bsclifton as you can read in the first post to this issue, I am unable to do that.
