### ISSUE TITLE
Twitter verified pubs info is not displayed in BR panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5388]
## Description 

Twitter verified pubs info is not displayed in BR panel. Please note YT and Twitch verified pubs info is displayed as expected in the BR panel. The issue is only with Twitter verified pubs.

## Steps to Reproduce

   1. Open brave 0.67.117
   2. Enable rewards
   3. Open verified pubs in new tab
   4. Open BR panel
   5. Verified pubs info is not displayed in BR panel

## Actual result:

https://twitter.com/kamiljozwiak
https://twitter.com/jonathansampson
https://twitter.com/brave

Twitter verified pubs info is not displayed in BR panel

![image (3)](https://user-images.githubusercontent.com/38657976/61877139-029fb480-af0c-11e9-938f-d28e5059efba.png)

![image (2)](https://user-images.githubusercontent.com/38657976/61877147-08959580-af0c-11e9-871d-ed33c9b131e7.png)

![image (1)](https://user-images.githubusercontent.com/38657976/61877156-0d5a4980-af0c-11e9-914b-7aba3849b270.png)

![image](https://user-images.githubusercontent.com/38657976/61877167-11866700-af0c-11e9-956f-04ecf3abf1d5.png)

## Expected result:

Twitter verified pubs info should be displayed in BR panel

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.67.117 Chromium: 76.0.3809.62 (Official Build) (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @emerick

**Comment by LaurenWags** [comment]
Reproduced using STR from description (clean profile). Note - Clicking `Refresh Status` didn't help - panel still came back with twitter.com and not the verified twitter publisher.


Brave | 0.67.117 Chromium: 76.0.3809.62 (Official Build) (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

![Screen Shot 2019-07-25 at 9 26 18 AM](https://user-images.githubusercontent.com/28145373/61878286-bbd79d80-aebe-11e9-94e3-cca20b515c6e.png)

**Comment by btlechowski** [comment]
Reproducible on Linux

Brave | 0.67.117 Chromium: 76.0.3809.62 (Official Build) (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Ubuntu 18.04 LTS
