### ISSUE TITLE
Estimated pending rewards drops to 0 after tokens redeemed

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5390]
## Description 
Found while testing #5175 

Estimated pending rewards dropped to 0 after tokens were redeemed on the server.

## Steps to Reproduce

1. Start from a clean profile and trigger an ad
2. Quit the browser.
3. Go to something like https://www.unixtimestamp.com/ and find a timestamp a couple of minutes from now
4. Under Default/rewards_service/confirmations.json change the field "next_token_redemption_date_in_seconds" to have that new time.  This will force a payment token cash in sooner.
5. Start the browser back up and wait until after the timestamp
6. If you have Rewards page open, note that your estimated pending rewards doesn't change once tokens are cashed in.
7. Refresh Rewards page.

## Actual result:
Estimated pending rewards gets reset to 0

## Expected result:
Estimated pending rewards should not get reset to 0

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.67.117 Chromium: 76.0.3809.62 (Official Build) (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
The issue is Reproducible on Windows 10 x64


Brave | 0.67.117 Chromium: 76.0.3809.62 (Official Build) (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 10 OS Version 1803 (Build 17134.523)

![image](https://user-images.githubusercontent.com/38657976/61887733-cece8a00-af1f-11e9-982e-2d061199cea4.png)

**Comment by LaurenWags** [comment]
Added milestone and assignment per discussion with @jsecretan and @tmancey - if needed please adjust these.

cc @kjozwiak

**Comment by LaurenWags** [comment]
Should be solved by #5011 . We need to recheck this issue once uplift of #5011 is complete.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.119 Chromium: 76.0.3809.72 (Official Build) (64-bit)
-- | --
Revision | 5a04c669126f657f98824b436555cae41b8f4146-refs/branch-heads/3809@{#897}
OS | Mac OS X

* Verified STR in description
