### ISSUE TITLE
'Verify Your Wallet' needs copy updates

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#5399]
## Description
The "Verify Your Wallet" panel text needs to be revised:

<img width="385" alt="Screen Shot 2019-07-25 at 5 28 57 PM" src="https://user-images.githubusercontent.com/2388823/61917529-7210a680-af02-11e9-82aa-66afa76a650a.png">

-  "Keep your Ad Rewards tokens" is awkward to say and leaves the user questioning if their tokens may/may not be theirs. 
- "Add tokens using credit card" has incorrect grammar

## Designs
Update the bullet points with clearer copy.
- Remove "And manage your funds easily!" (this text is unnecessary as the bullet points below illustrate this)
- Change "A verified wallet allows you to:" to "Verify your wallet to:"
- Change "Keep your Ad Rewards tokens" to "Withdraw earnings from ads"
- Change "Add tokens using credit card" to "Add tokens using a credit card or other currencies"
- Change "Withdraw tokens" to "Withdraw tokens added to your wallet previously"
- Remove "Please have your government issued ID available."

**Comment by NejcZdovc** [comment]
One thing that I would add is I would remove government issues ID from this on boarding as you really don't need it if you just want to work with crypto. You can easily create non KYC'd account with uphold and add/withdraw crypto. You only need to KYC to do credit card stuff

**Comment by NejcZdovc** [comment]
closing as this was redone
