### ISSUE TITLE
Browser shows error icon for browser peek preview on Windows

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#54]
![image](https://user-images.githubusercontent.com/17010094/34938606-f313ce2e-fa0e-11e7-8aa1-e61c2cd98ecf.png)

**Comment by bbondy** [comment]
cc @yrliou

**Comment by srirambv** [comment]
Looks fixed

**Comment by GeetaSarvadnya** [comment]
Verified on:

Brave | 0.54.2 Chromium: 69.0.3497.42 (Official Build) dev (64-bit)
-- | --
Revision | 9c4613c66dfeb2b76ef6dd4b15884c15db3b4969-refs/branch-heads/3497@{#655}
OS | Windows
JavaScript | V8 6.9.427.14
Flash | 30.0.0.154
