### ISSUE TITLE
skepticalscience.com causes 100% CPU usage leading to browser becoming unresponsive

### ISSUE THREAD

**Issue by claudiosv** [brave/brave-browser#5406]
## Description of the issue:

Visiting a specific website causes Brave to quickly start using 100% CPU, leading to an unresponsive browser UI, and eventually a nearly unresponsive system UI.

## Steps to Reproduce (add as many as necessary):

1. Install Brave Beta on macOS Mojave. Ensure the Fingerprinting Shield is set to block 3rd party or all. There is no issue when Fingerprinting Shield is disabled!
a. Open an incognito window to make sure there are no extensions interfering/causing this.
2. Visit https://skepticalscience.com/empirical-evidence-for-co2-enhanced-greenhouse-effect.htm
3. Enjoy using Force Quit

## Actual Result (gifs and screenshots are welcome!):
Pretty clear. Fans start blowing like crazy, nothing is usable.

## Expected result:
Load the page without freezing the machine, like Chrome does (works fine!), Safari, and Firefox.

## Reproduces how often:
Every time.

## Brave Version(See the About Brave page in the main menu):
Version 0.67.112 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)

## Reproducible on current live release (yes/no):
On current beta, yes

## Version/Channel Information:
- Can you reproduce this issue with the current release?
Did not test.
- Can you reproduce this issue with the beta channel?
Yes
- Can you reproduce this issue with the dev channel?
Did not test.
- Can you reproduce this issue with the nightly channel?
Did not test.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
Yes! See reproduction steps.
- Does the issue resolve itself when disabling Brave Rewards?
No.
- Is the issue reproducible on the latest version of Chrome? 
No.

## Miscellaneous Information:
All steps provided in reproduction.

**Comment by kjozwiak** [comment]
Managed to reproduce this pretty easily which basically crippled my entire machine and made Brave none-responsive. As @claudiosv mentioned above, opening `skepticalscience.com` and waiting a few minutes is enough to reproduce. Used the following builds:

* `0.67.117 Chromium: 76.0.3809.62 (Official Build)` - Reproduced
* `0.69.93 Chromium: 76.0.3809.62 (Official Build) dev` - Reproduced
* `0.68.111 Chromium: 76.0.3809.62 (Official Build) beta` - Reproduced
* `0.70.9 Chromium: 76.0.3809.72 (Official Build) nightly` - Reproduced

I tried profiling using the dev tools but the entire browser becomes unresponsive.

**Comment by claudiosv** [comment]
@kjozwiak Thanks for reproducing! I do wonder what causes this, first thought was to use dev tools but I faced the same issue as you did.

**Comment by bsclifton** [comment]
Possibly an issue with the way we stub methods used for fingerprinting (ex: canvas methods)
cc: @diracdeltas

**Comment by justsee** [comment]
Just ran into this and lost 5 minutes trying to determine which tab was hammering the CPU after using 'Restore Pages'.

Had to toggle away from app to even force quit Brave, and did this 3 or 4 times before determining it was https://skepticalscience.com.

It's a site regularly recommended by leading climate scientists, so I imagine a lot of non-technical Brave users interested in climate science will hit this and figure Brave is flaky and uninstall.

https://en.wikipedia.org/wiki/Skeptical_Science

> Marine biologist Ove Hoegh-Guldberg has described it as "the most prominent knowledge-based website dealing with climate change in the world",[20] and The Washington Post has praised it as the "most prominent and detailed" website to counter arguments by global warming deniers.[21

**Comment by kjozwiak** [comment]
CCing @rebron @bsclifton maybe we can prioritize this as a `P2`? It basically bricks/cripples the entire browser.

**Comment by d-tomerini** [comment]
Reproduced on Ubuntu 19.04 and 18.10, running Brave 0.69.135 Chromium: 77.0.3865.120

**Comment by rebron** [comment]
cc: @jsecretan Can you take a look? Heard you were looking for cases with 100% CPU issues.

**Comment by ryanbr** [comment]
Wasn't aware of this ticket, but discovered a script causing it

`https://skepticalscience.net/widgets/heat_widget/js/heat_content.js`

The quick and dirty fix would to be block the script in Brave, which would allow the website to load without hanging. The only downside, it'll break the widget.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/adblock-lists/pull/314 - but we'll want to revert that and use cosmetic filters once https://github.com/brave/brave-core/pull/4269 lands

@ryanbr do you want to keep the issue open until then? Might be a good idea, as cosmetic filter functionality is tied to a proper milestone, which this can track

**Comment by bsclifton** [comment]
Closing as this appears to be resolved 😄👍
