### ISSUE TITLE
logic for shield settings is located in multiple places and none of them are shareable with android

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#5416]
Shields setting logic needs to be consolidated so it is consistent everywhere

**Comment by bridiver** [comment]
QA - this affects all shield settings for both defaults and site settings. Extensive unit tests have been added, but it still needs a pass for all settings.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Verified `Bravery settings` and `Fingerprint Tests` from our manual testrun

Shields Panel
- verified turning on/off shields works
- verified https upgrading works
- verified ads and trackers blocking
- verified script blocking
- verified cookies blocking
- verified fingerprint protection 
- verified simple and advanced view
- verified that the settings are retained after browser restart
- verified that the settings are retained after closing and reopening the page

NTP stats
- verified ads and trackers blocked stats are increasing 
- verified https upgrade stats are increasing
- verified that the stats are retained after browser restart.

Global Shields Settings
- verified https upgrading works
- verified ads and trackers blocking
- verified script blocking
- verified cookies blocking
- verified fingerprint protection 
- verified toggling simple and advance view works
- verified that the settings are retained after browser restart

Verified following Upgrade scenarios from 0.68.141
- NTP stats are retained
- Shields Panel settings are retained
- Global Shields Settings are retained
