### ISSUE TITLE
Uphold wallet creation fails

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5418]
## Description 

Uphold wallet creation fails

## Steps to Reproduce

   1. Upgrade to nightly 0.70.3
   2. Enable rewards and click on Verify button
   3. New tab opens with trying to navigate to uphold but fails and asks to retry

## Actual result:

https://youtu.be/6G6gobByJWw

## Expected result:
Should create wallet and user should be able to allowed to KYC on uphold 

## Reproduces how often: 

Easy on my machine. Not so sure about others. 

## Brave version (brave://version info)

Brave | 0.70.3 Chromium: 76.0.3809.62 (Official Build) nightly (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

@brave/legacy_qa  to try on other platforms
cc: @NejcZdovc

**Comment by NejcZdovc** [comment]
Problem with this one is that user is still in pending state and we want to create card for him. Until he clears that state we can't create it

**Comment by kjozwiak** [comment]
@NejcZdovc is this similar to https://github.com/brave/brave-browser/issues/5426?

**Comment by NejcZdovc** [comment]
yup #5426 will fix this one. Will close it
