### ISSUE TITLE
WindowsOS window control buttons hover shape is square (was circle)

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5419]
## Description 

Button hover is changed on nightly 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/61999441-e24c3300-b08e-11e9-9d8f-b428b795b72d.png)

## Expected result:
Should probably not use Chromium hover 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.70.3 Chromium: 76.0.3809.62 (Official Build) nightly (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @petemill

**Comment by rebron** [comment]
We're going to follow upstream here, not a differentiator.

**Comment by petemill** [comment]
Just realized this is not Windows, but some flavor of Linux. Not sure which, as this is not what it looks like in Ubuntu.
