### ISSUE TITLE
Request user confirmation before opening all external applications

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#542]
STR:

- Load: 

```
<script>
  document.location = 'mailto://test@test.com';
</script>
```

**Comment by jumde** [comment]
Works for `news:` protocol as well

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/50589199-b6c3ea00-0eab-11e9-9ab5-6c6d95eb0d33.png)
