### ISSUE TITLE
In Google Sheets, cell alignment is broken (webcompat)

### ISSUE THREAD

**Issue by julienben** [brave/brave-browser#5421]
## Description 

Hey there!

As can be seen in the screenshot below, cell alignment is broken in Google Sheets.

Left alignment seems fine but center and right alignment push the content outside of the cell.

![image](https://user-images.githubusercontent.com/8948127/62005329-4546d400-b13a-11e9-8fb6-54a96aa9423f.png)

## Steps to Reproduce

Open [this Google Sheets demo](https://docs.google.com/spreadsheets/d/1D77C8s416Bq3ipthpuruxt1UpWcPd62ZI52EZpl-Jzk/edit?usp=sharing) using Brave

Or create a new sheet (by going to https://sheets.new), enter some text in a cell and set its alignment to center or right. (Format > Align > Pick one)

## Actual result:

The content will be shifted to the right, partially or even fully outside of the cell where it's supposed to appear.

## Expected result:

The content should remain within its cell and align itself as expected.

## Reproduces how often: 

Consistently reproducible. At least on my computer, I've seen this same issue on every sheet I've opened.

### Brave
0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
### Revision
8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
### OS
Mac OS X

## Version/Channel Information:

Are users who report issues supposed to install every channel to test if their issues reproduces for each one? I can do it if necessary but that seems like a lot to ask.

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Nope [EDIT: My bad, it works with device recognition enabled.]
- Does the issue resolve itself when disabling Brave Rewards? Nope
- Is the issue reproducible on the latest version of Chrome? Nope

## Miscellaneous Information:

Obviously, the simple workaround is to set all the cells to left alignment but that can be a hassle given that number cells align themselves to the right automatically.

**Comment by srirambv** [comment]
Can you try setting `Cross-site device recognition blocked` in shields and check?

**Comment by julienben** [comment]
Hey @srirambv,

By cross-site, I assume you mean 3rd-party?

That does fix the issue! Thanks!

With my default option of `Device recognition blocked`, 1 recognition appears to have been blocked.

With the `3rd-party device recognition blocked` option, no recognitions are blocked.

I'm not sure if this information is actionable for Brave? Even as a web developer I didn't think of changing the device recognition setting but maybe you have a system to warn users that a site will be broken under certain Shields settings?

**Comment by srirambv** [comment]
@julienben  yes that is correct. The labels are updated now so `3rd party fingerprinting` is `cross-site device recognition`. 

I think once https://github.com/brave/brave-browser/issues/4247 is done it would be more interactive and users would find it easy to change shields settings per site

cc: @karenkliu for thoughts

**Comment by julienben** [comment]
I had in mind something site-specific where Shields would know that Google Sheets is incompatible with blocked device recognition but that doesn't seem very scalable. #4247 does indeed seem like a smarter solution.

**Comment by srirambv** [comment]
Closing the issue as fixed. Can continue the discussion here or on #4247. @julienben feel free to add your ideas or suggestion in #4247 so that @karenkliu can take inputs.

**Comment by aleqx** [comment]
I'm getting this again now with Brave Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (32-bit)
