### ISSUE TITLE
Duckduckgo is not directly accessible in mainland China, but Brave recommends it in the incognito window.

### ISSUE THREAD

**Issue by zaoqi** [brave/brave-browser#5422]
## Description 

Duckduckgo is not directly accessible in mainland China, but Brave recommends it in the incognito window.

## Other Additional Information:

DoH+esni can fix it.
I've tested it on DoH+esni-enabled GNU IceCat.
https://github.com/brave/brave-browser/issues/1864
https://github.com/brave/brave-browser/issues/1851

https://baike.baidu.com/item/Duck%20Duck%20Go/7218557#9

**Comment by rebron** [comment]
cc: @tomlowenthal

**Comment by rebron** [comment]
Fixed in 1.42.x.
with https://github.com/brave/brave-browser/issues/22566 and with https://github.com/brave/brave-browser/issues/23091
