### ISSUE TITLE
hamburger menu unreadable in dark mode on High Sierra (macOS)

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5423]
## Description 
Hamburger menu is unreadable when using dark mode on macOS High Sierra. Probably related to the fix for https://github.com/brave/brave-browser/issues/4637 as this appears to only affect 0.69.x and higher versions.

Originally reported via https://twitter.com/nyzrox_dnb/status/1155274197809160193?s=12

## Steps to Reproduce

   1. Set Brave to use Dark theme if not already using.
   2. Click on hamburger menu.
   3. 

## Actual result:
Menu is unreadable unless you hover over an item.
<img width="1265" alt="Screen Shot 2019-07-28 at 1 37 14 PM" src="https://user-images.githubusercontent.com/28145373/62010853-0286fb00-b13e-11e9-9a8c-1e55717f453c.png">

![Screen Shot 2019-07-28 at 1 41 02 PM](https://user-images.githubusercontent.com/28145373/62010867-424de280-b13e-11e9-8c52-821d37079ca4.png)

## Expected result:
Menu should be dark, but readable, i.e. light text on dark background as it appears on Mojave:
<img width="432" alt="Screen Shot 2019-07-27 at 9 10 22 PM" src="https://user-images.githubusercontent.com/28145373/62010903-08c9a700-b13f-11e9-83e8-d72d9715fbd8.png">

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.94 Chromium: 76.0.3809.62 (Official Build) dev (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

Brave | 0.70.3 Chromium: 76.0.3809.62 (Official Build) nightly (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, does not reproduce on 0.66.x or 0.67.x (RC)
- Can you reproduce this issue with the beta channel? no, does not reproduce on 0.68.x
- Can you reproduce this issue with the dev channel? yes, reproduces on 0.69.x
- Can you reproduce this issue with the nightly channel? yes, reproduces on 0.70.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

## Miscellaneous Information:
@kjozwiak  unable to reproduce on Mojave, Windows. @GeetaSarvadnya unable to reproduce on Windows 10.

cc @bradleyrichter @rebron

**Comment by bsclifton** [comment]
cc: @simonhong

**Comment by simonhong** [comment]
@LaurenWags yes, this is the regression of https://github.com/brave/brave-browser/issues/4637
With https://github.com/brave/brave-browser/issues/4637, brave that runs on platforms that doesn't have dark mode support can have aligned theme for native/webui/base UI(such as menu dialog).
I think only high sierra has this regression. That's the only platform I can't test.
All others like linux/win7/win8 don't have this regression.
I assume chromium has another checks for coloring on high sierra.
Will check.

**Comment by kjozwiak** [comment]
@LaurenWags you'll need to verify this one as I'm on `Mojave` and unfortunately don't have a VM that's on `High Sierra`.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.123 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified STR from description (clean install)
* Installed 0.68.132 (current release build). Set theme to dark. Closed Brave and renamed profile to be for Beta. Verified hamburger menu was dark with light, readable text as expected after launching with 0.69.123.
* Installed 0.69.122 (previous beta build which had issue as described). Set theme to dark. Upgraded to 0.69.123. Verified hamburger menu was dark with light, readable text as expected after launching with 0.69.123.
* Verified toggling back and forth between light/dark had the hamburger menu displaying appropriate colors/readability.

![Screen Shot 2019-09-04 at 10 18 59 AM](https://user-images.githubusercontent.com/28145373/64263739-263c1e80-cefe-11e9-885c-e44fbd33ac60.png)
