### ISSUE TITLE
User wallets: Pending wallet with Uphold

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#5426]
In the current user wallet creation flow, Brave is not checking if user's registration information is fully update; Uphold throws a pending user state when registration data is incomplete.

In such a state, when we try to create the BAT card, it fails causing the entire flow to fail.

Brave client needs to handle this state and prevent user from accessing add-funds or withdraw-funds in such a state. If a user is in pending state, the wallet will display BR in default anon wallet state.

cc @NejcZdovc @kjozwiak

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.113 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/3042

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.114 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/3042
