### ISSUE TITLE
User wallets: brave browser creating multiple wallets

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#5427]
For every single browser instance, currently the Brave browser is creating a new BAT card causing too many cards to be created against the same account.

Change asked for;
- Create card and set it to position-0 (starred)
- Card name set to "Brave Browser"
- Before creation, check 2 pages of account to see if BAT card called "Brave Browser"
- If no card exists, create card (there will be an issue if user renames card)

cc @NejcZdovc @kjozwiak

**Comment by mandar-brave** [comment]
@NejcZdovc besides starring the card, set position to 1 when card is created.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.113 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/3072
- Verified `Brave Browser` card created when verifying wallet with new uphold account.
- Verified that no new `Brave Browser` card is created when verifying wallet with existing uphold account 
- Verified `Brave Browser` card is picked from the list when connecting uphold with new/existing account
