### ISSUE TITLE
Update Safe Browsing API key

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#543]
The dev safe browsing key is limited to 2000 requests per day. Reach out to google to get an updated key with increased request quota per day. cc: @flamsmark

**Comment by w0ts0n** [comment]
Generated the key. 
Will be double checking the proxy is working on Monday.
will work with team to make sure the key is used in future CI builds for all channels.

**Comment by bbondy** [comment]
What's the current status on this one @w0ts0n ? Thanks!

**Comment by jumde** [comment]
The new key has been generated, we have upgraded the quota for the key as well. @mbacchi and @RyanJarv are working on setting up key in the proxy. Issue tracked here: https://github.com/brave/devops/issues/208

cc: @tomlowenthal

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux
