### ISSUE TITLE
Incorrect header text is overlapping in Tipping banner

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5430]
## Description 

Incorrect header text is overlapping in Tipping banner

## Steps to Reproduce

   1. Open brave 0.67.119
   2. Enable rewards
   3. Open https://twitter.com/ErrataRob
   4. Click on inline Tip link

## Actual result:

Header text is overlapping in Tipping banner

![image](https://user-images.githubusercontent.com/38657976/62045783-e5c4f300-b223-11e9-9209-315d2d067355.png)

## Expected result:

Header text should not be overlapping in Tipping banner

Dev Channel:
![image](https://user-images.githubusercontent.com/38657976/62046582-e52d5c00-b225-11e9-9582-d89284bdd1fe.png)

Nightly:

![image](https://user-images.githubusercontent.com/38657976/62046599-f4140e80-b225-11e9-89cb-65f6a6b0069a.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.67.119 Chromium: 76.0.3809.72 (Official Build) (64-bit)
-- | --
Revision | 5a04c669126f657f98824b436555cae41b8f4146-refs/branch-heads/3809@{#897}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
can't reproduce this problem
