### ISSUE TITLE
Change to 'Add to Brave' instead of 'Add to Chrome' on Private/Tor/Guest follow up to #790

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5431]
## Description 

Change to 'Add to Brave' instead of 'Add to Chrome' on Private/Tor/Guest

## Steps to Reproduce

   1. Open chrome store on Private/Tor/Guest window
   2. Shows `Add to Chrome` button even though disabled

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/62051173-cb1d5a80-b1e0-11e9-84c3-a3f3acafa471.png)

## Expected result:
Should show `Add to Brave` even if its disabled

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.70.3 Chromium: 76.0.3809.62 (Official Build) nightly (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by bsclifton** [comment]
Should have been fixed with https://github.com/brave/brave-core/pull/2845 - the extension should be loading in these window types also. Curious why this doesn't work

**Comment by rebron** [comment]
![Screen Shot 2021-06-01 at 10 07 47 AM](https://user-images.githubusercontent.com/5951041/120363740-5aa26180-c2c1-11eb-862d-a0a96deda3a5.png)
I'm seeing this working properly now in private window and private window with Tor.

**Comment by rebron** [comment]
Closing this one as fixed/stale.
