### ISSUE TITLE
Chromium incognito icon used in profile dropdown 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5432]
## Description 

Chromium incognito icon used in profile dropdown 

## Steps to Reproduce

   1. Open a private window
   2. Click on the incognito button next to hamburger menu
   3. Shows Chromium incognito icon instead of Brave private icon

## Actual result:

![Screenshot from 2019-07-29 09-02-07](https://user-images.githubusercontent.com/17010094/62051384-43841b80-b1e1-11e9-8257-a0afee1ab471.png)

## Expected result:
Should not use Chromium branding icons/name anywhere in the product

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
-- | --
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

## Miscellaneous Information:

Must have regressed sometime back which went unnoticed. 
cc: @rossmoody

**Comment by btlechowski** [comment]
Not reproducible on Windows

Brave | 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
-- | --
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

![image](https://user-images.githubusercontent.com/34715963/62174084-de433e00-b338-11e9-8091-3fd5ef70083e.png)

Not reproducible on Linux

Brave | 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
-- | --
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/62174010-87d5ff80-b338-11e9-9ec0-6e8264ee8cd3.png)

@srirambv Can you recheck on 0.66.101? It works for me.

**Comment by srirambv** [comment]
@btlechowski  I think you got confused with the title. I see Chromium incognito icon on both of your screenshots for Windows and Linux.

**Comment by simonhong** [comment]
yes, above hat image is chromium's icon. I think we want use brave icon instead of it.

**Comment by srirambv** [comment]
However I do see Incognito on all the channels on my machine instead of Private. I think there is an issue logged for that will link it here

**Comment by simonhong** [comment]
@rossmoody We need to add our `incognito_profile.icon` file to`brave/vector_icons/chrome/app/vector_icons/` to override https://cs.chromium.org/chromium/src/chrome/app/vector_icons/incognito_profile.icon.

**Comment by rossmoody** [comment]
@simonhong  This should do the trick. 

```
CANVAS_DIMENSIONS, 40,
MOVE_TO, 20, 40,
CUBIC_TO, 8.95f, 40, 0, 31.05f, 0, 20,
CUBIC_TO_SHORTHAND, 8.95f, 0, 20, 0,
R_CUBIC_TO, 11.05f, 0, 20, 8.95f, 20, 20,
R_CUBIC_TO, 0, 11.05f, -8.95f, 20, -20, 20,
CLOSE,
MOVE_TO, 8.13f, 18.42f,
R_CUBIC_TO, 0.19f, 0.66f, 0.57f, 4.51f, 1.7f, 5.62f,
R_CUBIC_TO, 1.17f, 1.14f, 5.57f, 1.12f, 6.41f, 0.63f,
R_CUBIC_TO, 1.89f, -1.11f, 2.65f, -4.68f, 2.98f, -6.25f,
R_CUBIC_TO, 0.19f, -0.89f, 0.79f, -0.89f, 0.79f, -0.89f,
R_CUBIC_TO, 0, 0, 0.63f, 0, 0.82f, 0.89f,
R_CUBIC_TO, 0.33f, 1.57f, 1.06f, 5.15f, 2.95f, 6.26f,
R_CUBIC_TO, 0.84f, 0.5f, 5.24f, 0.51f, 6.41f, -0.63f,
R_CUBIC_TO, 1.13f, -1.11f, 1.51f, -4.96f, 1.69f, -5.63f,
R_CUBIC_TO, 0.19f, -0.66f, 1.13f, -1.33f, 1.32f, -1.55f,
R_CUBIC_TO, 0.19f, -0.22f, 0.19f, -1.11f, 0, -1.33f,
R_CUBIC_TO, -0.38f, -0.44f, -4.82f, -0.84f, -9.61f, -0.22f,
R_CUBIC_TO, -0.95f, 0.12f, -1.32f, 0.44f, -3.58f, 0.44f,
R_CUBIC_TO, -2.26f, 0, -2.63f, -0.32f, -3.58f, -0.44f,
R_CUBIC_TO, -4.78f, -0.61f, -9.23f, -0.22f, -9.61f, 0.22f,
R_CUBIC_TO, -0.19f, 0.22f, -0.19f, 1.11f, 0, 1.33f,
R_CUBIC_TO, 0.19f, 0.22f, 1.13f, 0.89f, 1.32f, 1.55f,
CLOSE
```

**Comment by bsclifton** [comment]
😎

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description

![image](https://user-images.githubusercontent.com/38657976/65276621-b9ec2c80-db45-11e9-9f00-365138ee57a0.png)
