### ISSUE TITLE
Netflix doesn't work on clean profile - macOS only

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5433]
## Description 
Netflix does not work on a clean profile. When trying to view a video I get a message about missing component.

@kjozwiak and I verified that this is not an issue on chromium `76.0.3809.62` versions of Brave (i.e. 0.67.112 (Beta) and 0.67.117 (RC)), issue seems to have appeared after the bump from 76.0.3809.62 to 76.0.3809.72.

## Steps to Reproduce

   1. Clean profile
   2. Navigate to Netflix. 
   3. Login.
   4. Allow widevine install.
   5. Try to view a video

## Actual result:
<img width="649" alt="Screen Shot 2019-07-29 at 10 10 48 AM" src="https://user-images.githubusercontent.com/28145373/62057465-b4c9cb80-b1ed-11e9-8b37-121c77048d64.png">

Additionally, if you check the console, there is an error:

```
80195725?trackId=141…157b6e31d67f_ROOT:1 Uncaught (in promise) 
b {code: 7702, wc: 1003, Gf: undefined, Zx: undefined, Op: undefined, …}
Gf: undefined
Op: undefined
Rjb: undefined
T: false
Zx: undefined
alert: undefined
code: 7702
data: DOMException: Failed to execute 'createMediaKeys' on 'MediaKeySystemAccess': CreateCdmFunc not available.
jC: "Failed to execute 'createMediaKeys' on 'MediaKeySystemAccess': CreateCdmFunc not available.↵Error: Failed to execute 'createMediaKeys' on 'MediaKeySystemAccess': CreateCdmFunc not available."
message: "Unable to create MediaKeys. Failed to execute 'createMediaKeys' on 'MediaKeySystemAccess': CreateCdmFunc not available."
tk: undefined
wc: 1003
__proto__: b
```

## Expected result:
Able to view video without issue

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.67.119 Chromium: 76.0.3809.72 (Official Build) (64-bit)
-- | --
Revision | 5a04c669126f657f98824b436555cae41b8f4146-refs/branch-heads/3809@{#897}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? RC candidate
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @rebron

**Comment by rebron** [comment]
Reproduced on 10.14.5 
0.67.119 Chromium: 76.0.3809.72 (Official Build) (64-bit)

**Comment by bsclifton** [comment]
Appears that upgrade to 76.0.3809.72 must have broken the signing scripts. There isn't a `.sig` file generated so Widevine host verification (VMP) fails

**Comment by bsclifton** [comment]
Actually 0.67.x and earlier are not generating .sig files (that is 0.68.x and above, captured with https://github.com/brave/brave-browser/issues/944). So this has to be something else

**Comment by LaurenWags** [comment]
Verified passed with `macOS x64 10.13.6` and

Brave | 0.67.122 Chromium: 76.0.3809.72 (Official Build) (64-bit)
-- | --
Revision | 5a04c669126f657f98824b436555cae41b8f4146-refs/branch-heads/3809@{#897}
OS | Mac OS X

* Verified STR from description 5x, no issue playing videos on Netflix.
cc @kjozwiak for check on Mojave
