### ISSUE TITLE
[Desktop] Brave issuing "Flash player will no longer be supported after December 2020" message after update

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#5436]
## Description 

After updating to the Dev build - v0.69.94 - and relaunching, this banner notification appears:
![image](https://user-images.githubusercontent.com/3299098/62074122-eeeb9b00-b1f6-11e9-8a42-0a3210cddb25.png)

While this is true and inherently  a good warning to have, the `Learn more` link in the banner links to a Google product page explaining why Flash is being depreciated:
https://www.blog.google/products/chrome/saying-goodbye-flash-c

We should decide whether or not we want to display this banner at all and, if so, should have our own support article/doc that addresses the issue with Flash rather than the link pointing to Google's support page. 

cc @rebron cc @tomlowenthal

**Comment by tomlowenthal** [comment]
It seems like a useful notice, so I think we should show it. @Brave-Matt can you get started on the document?

**Comment by thezeroalpha** [comment]
Could it perhaps be possible to disable the notice after seeing it once (a "don't show again" type of functionality)? [See here for a discussion of why it might be a good idea.](https://support.google.com/chrome/thread/11549634?hl=en). 

AFAIK this comes from the new build of Chromium, but I don't think Google will change anything about it, and I thought it might be possible to change it for Brave at least. Personally, I find having to dismiss this message every time I open the browser annoying, and I'm sure other users do too.

**Comment by bsclifton** [comment]
bumping down to a P3 since there hasn't been any work done

@Brave-Matt do we have any documentation on this? If so, we can update the `Learn more` link. Otherwise, I think we should close as `wontfix`

**Comment by Brave-Matt** [comment]
@bsclifton Sorry for the late reply -- I'm drafting this document today and should have it done by EoD 👍

**Comment by rebron** [comment]
@Brave-Matt Do we have a link for this article yet?

**Comment by toddbluhm** [comment]
Hello, any chance we could get a "don't show again" on this Flash notification? It is getting really annoying seeing it so frequently. Maybe there is a turn off all notifications option instead?

**Comment by kjozwiak** [comment]
@rebron just a heads up, the `Learn More` in the above message points to https://www.blog.google/products/chrome/saying-goodbye-flash-chrome. I'm not sure if we want to create our own document via our support page or just keep it for now. It's been like this for a while so maybe not even worth updating?

**Comment by Brave-Matt** [comment]
@kjozwiak @rebron -- I did go ahead and make our own, condensed, version of that page on our Help Center if you want to change the link. I think it would definitely be better to have them land on a page that is ours rather than a Google page.

Link to HC content: https://support.brave.com/hc/en-us/articles/360035598412-Sunsetting-Flash

**Comment by kjozwiak** [comment]
CCing @bsclifton @rebron ☝️ Should get this into the next release if possible now that we have a wiki created.

**Comment by kjozwiak** [comment]
@rebron I think we can close this one unless we're planning on fixing this in `1.18.x` which seems a bit too late at this point.

**Comment by bsclifton** [comment]
Good call @kjozwiak - closing as `wontfix`
