### ISSUE TITLE
Remove Advanced/Simple View links from Shields DOWN state

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#5438]
## Description 
Currently, the Shields DOWN state in both Simple and Advanced views contains an unnecessary bottom link:
![Screen Shot 2019-07-29 at 1.48.28 PM.png](https://images.zenhubusercontent.com/5d27a1d54700b71fc19fe1d8/3a58c7da-ae4d-4900-8577-d641e3a6d2ce)
![shields off advanced.png](https://images.zenhubusercontent.com/5d27a1d54700b71fc19fe1d8/f30d2f0f-c94d-4c7f-9288-251dd3cbc0af)

## Designs
Remove Advanced/Simple View links when the Shields state is DOWN since this clicking this link does not immediately change their view:
![shields off.png](https://images.zenhubusercontent.com/5d27a1d54700b71fc19fe1d8/e762a5e8-a573-4033-a842-01bb1732f2ce)
The Shields DOWN state will be the same for both Simple and Advanced views; the user must bring Shields UP to switch views.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3151
![image](https://user-images.githubusercontent.com/38657976/65529244-67c75480-df13-11e9-8f35-f2d631ec3c0a.png)
