### ISSUE TITLE
Exception rules in brave://adblock or regional lists are ignored

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#5440]
Currently exception rules added in brave://adblock and in regional lists are ignored, because of how filter logic is applied (main set of rules is queried, then regional, then custom, in order, until one of them has a match).  This means an exception in a later list won't correctly except a rule from a previous set, and that `important` wont override an exception from a previous set.

**Comment by ryanbr** [comment]
@antonok-edm do we have an update on this?

**Comment by snyderp** [comment]
@antonok-edm isn't currently working on this, so we'll need to figure out internally whats best here.

I believe @bbondy and @AndriusA had a plan for tagging rules so that they could all be part of a single engine, of having the layered engines (which is what causes the issue).  When either of you have a chance, could you say if the above (tag the rules) approach is still the official plan of action, and if so, if anyone is currently working on it (or if its in the backlog)?

**Comment by AndriusA** [comment]
the last I know of this is a conversation with @antonok-edm where we discussed a couple of approaches and their trade-offs and agreed that he'd post it up for discussion

**Comment by snyderp** [comment]
@antonok-edm i know you're working on other things at the moment, but could you just update the issue here with where the conversation ended (if a conclusion was reached) and we'll figure out how best to go forward

**Comment by stephendonner** [comment]
Verified `FIXED` using the testplan from https://github.com/brave/brave-core/pull/7666 on 

Brave | 1.21.47 Chromium: 88.0.4324.152 (Official Build) beta (x86_64)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | macOS Version 11.2 (Build 20D64)

**Case 1:** defaults Shields settings, `https://knowyourmeme.com` - **NO** ad(s)
<details>
<img width="1017" alt="Screen Shot 2021-02-08 at 4 52 23 PM" src="https://user-images.githubusercontent.com/387249/107300534-940f4280-6a2e-11eb-8836-0d75dfbedf81.png">
</details>

**Case 2:** default Shields settings, `https://knowyourmeme.com`, added `@@*$domain=knowyourmeme.com` to the Custom Filters section in `brave://adblock` - **1 ad** (bottom of the page)
<details>
<img width="1023" alt="Screen Shot 2021-02-08 at 4 50 47 PM" src="https://user-images.githubusercontent.com/387249/107300528-91ace880-6a2e-11eb-8af1-3aaa51794bc2.png">
</details>

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.21.64 x64 beta build 

- Verified test plan from https://github.com/brave/brave-core/pull/7666

Default shields (no exception rule) | Exception rule in chrome://adblock
-- | --
![image](https://user-images.githubusercontent.com/17010094/108843199-479d3880-75d2-11eb-8a33-fdcc4c50d039.png) | ![image](https://user-images.githubusercontent.com/17010094/108843187-41a75780-75d2-11eb-8e08-f1fb40e5552a.png)
