### ISSUE TITLE
"Continue with Brave Browser" button under Uphold banner doesn't work

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#5442]
## Description 

After verifying your Uphold account via the `brave://rewards` panel for the first time, a new tab will automatically open that loads your Uphold account. Within this page, you'll see the following banner:

<img width="1182" alt="Screen Shot 2019-07-27 at 11 38 12 PM" src="https://user-images.githubusercontent.com/2602313/62097296-5a178a80-b254-11e9-88d5-f72dde013ca7.png">

Clicking on `CONTINUE WITH BRAVE BROWSING` will result in the following error via the browser console:

```
uphold.2efb0668718a6c9cbf22.js:108 Not allowed to load local resource: brave://rewards/
value @ uphold.2efb0668718a6c9cbf22.js:108
(anonymous) @ vendors.881f2e84a56366ea6afe.js:50
r @ vendors.881f2e84a56366ea6afe.js:50
i @ vendors.881f2e84a56366ea6afe.js:50
$eval @ vendors.881f2e84a56366ea6afe.js:50
$apply @ vendors.881f2e84a56366ea6afe.js:50
(anonymous) @ vendors.881f2e84a56366ea6afe.js:50
dispatch @ vendors.881f2e84a56366ea6afe.js:34
v.handle @ vendors.881f2e84a56366ea6afe.js:34
```

## Steps to Reproduce

   1. launch brave and verify a wallet using the Uphold process

## Actual result:

Pressing on the `CONTINUE WITH BRAVE BROWSING` button via Uphold doesn't do anything and produces the console error mentioned above.

## Expected result:

From the looks of the console message added above, clicking on `CONTINUE WITH BRAVE BROWSING` should open `brave://rewards`.

## Reproduces how often: 

I'm not 100% sure but @NejcZdovc mentioned that Uphold also reported this error via Slack.

## Brave version (brave://version info)

Brave | 0.70.9 Chromium: 76.0.3809.72 (Official Build) nightly (64-bit)
-- | --
Revision | 5a04c669126f657f98824b436555cae41b8f4146-refs/branch-heads/3809@{#897}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

CCing @brave/legacy_qa @NejcZdovc @mandar-brave

**Comment by NejcZdovc** [comment]
problem with this one is that Uphold wants to redirect to rewards internal page which of course we block. We will provide new url to them to which they can redirect

**Comment by ruipenso** [comment]
We'll remove the button.

**Comment by NejcZdovc** [comment]
closing as fixed on Uphold side
