### ISSUE TITLE
changing about brave icon under "brave://settings" so it matches correct channel

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#5443]
## Description 

We should change the Brave icon that's displayed at the bottom left corner next to `About` under `brave://settings/` so it matches the correct channel.

## Steps to Reproduce

   1. open a `nightly` or a `dev` version of Brave
   2. visit `brave://settings/` and you'll notice that the Brave icon next to About is the official icon which is used for the release channel

## Actual result:

<img width="969" alt="Screen Shot 2019-07-29 at 11 17 03 PM" src="https://user-images.githubusercontent.com/2602313/62098360-f727f280-b257-11e9-9dcc-42d9ec70cc60.png">

<img width="896" alt="Screen Shot 2019-07-29 at 11 31 55 PM" src="https://user-images.githubusercontent.com/2602313/62098632-2c811000-b259-11e9-8764-0d1b8407c487.png">

## Expected result:

Probably a good idea to use the correct channel icon rather than the official release icon

## Reproduces how often: 

100% reproducible using the above STR

## Brave version (brave://version info)

Brave | 0.70.9 Chromium: 76.0.3809.72 (Official Build) nightly (64-bit)
-- | --
Revision | 5a04c669126f657f98824b436555cae41b8f4146-refs/branch-heads/3809@{#897}
OS | Mac OS X

Brave | 0.69.95 Chromium: 76.0.3809.62 (Official Build) dev (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by bsclifton** [comment]
This has been fixed at some point 😄
