### ISSUE TITLE
Reddit non-verified pubs name is not displayed in BR panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5448]
## Description 

Reddit non-verified pubs name is not displayed in BR panel

## Steps to Reproduce

   1. Open 0.68.113
   2. Open https://www.reddit.com/r/brave_browser/
   3. Tap on inline Tip link on any Reddit post
   4. Click on BR panel
   5. Instead of non-verified pubs name, Reddit.com is displayed in BR panel 

## Actual result:

Reddit not-verified pubs name is not displayed in BR panel
![image](https://user-images.githubusercontent.com/38657976/62129933-86371800-b2f5-11e9-9aee-8b4951abe9d1.png)

## Expected result:

not verified pubs name should be displayed like this in BR panel

![image](https://user-images.githubusercontent.com/38657976/62130099-e3cb6480-b2f5-11e9-9641-3c1144c40085.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya we don't support pages, but only user pages. Closing as it works as expected
