### ISSUE TITLE
PDFium shows Brave Software Drive in save as pdf modal

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5450]
## Description 

PDFium shows Brave Software Drive in save as pdf modal

## Steps to Reproduce

   1. Install beta
   2. Open any page and try to print
   3. On the save file dropdown, shows `Save to Brave Software Drive` which is not a valid option

## Actual result:

![Screenshot from 2019-07-30 10-51-40](https://user-images.githubusercontent.com/17010094/62139951-24a48880-b2b8-11e9-9b76-07dca525ad77.png)

## Expected result:
![Screenshot from 2019-07-30 10-51-21](https://user-images.githubusercontent.com/17010094/62139963-2c642d00-b2b8-11e9-8884-64e4525c1238.png)

## Brave version (brave://version info)

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

cc: @simonhong @bsclifton 
@rebron added P3 so that it can ride the trains. Please change the priority if you think it's required

**Comment by kjozwiak** [comment]
Reproduced on `macOS 10.14.5 x64` using the following build:

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

Example on macOS:

<img width="425" alt="Screen Shot 2019-07-30 at 11 54 55 AM" src="https://user-images.githubusercontent.com/2602313/62145174-f24b5900-b2c0-11e9-9d45-1b0a65656b5f.png">

**Comment by LaurenWags** [comment]
Reproduces on 0.67.125 also:

Brave | 0.67.125 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

![Screen Shot 2019-08-15 at 5 19 31 PM](https://user-images.githubusercontent.com/28145373/63127656-eb8b3a00-bf80-11e9-8e61-d4a065670c0e.png)

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/what-is-save-to-brave-software-drive/83298/3

**Comment by ivanhercaz** [comment]
It happens to me in:

Brave | 1.0.1 Chromium: 78.0.3904.108 (Build oficial) (64 bits)
-- | --
Revisión | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Linux (Debian 10)


![brave_software_drive](https://user-images.githubusercontent.com/8690921/69585807-ab544280-0fd8-11ea-8b45-2d46ae59fc2d.png)

**Comment by Jacalz** [comment]
I can reproduce this too on the latest version 1.2.42 on Windows 10.

Brave | 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)
-- | --
OS | Windows 10

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.5.102 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/75460158-20079600-59a7-11ea-9d52-bfdf848101c4.png)
![image](https://user-images.githubusercontent.com/38657976/75460802-e8e5b480-59a7-11ea-8acc-8f3142c47098.png)
