### ISSUE TITLE
the default search engine should be selected when visiting onboarding

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#5453]
## Description 

We should be displaying the default search engine in the dropdown when visiting `brave://welcome` instead of `Select a search engine`.

## Steps to Reproduce

**Test Case 1:**

   1. install brave and go through the onboarding process via `brave://welcome`
   2. notice that `Select a search engine` is selected instead of the default search engine

**Test Case 2:**

   1. install brave and go through the onboarding process via `brave://welcome`
   2. select a different search engine from the drop down as default and complete onboarding
   3. go back into `brave://welcome` and notice the default isn't selected

## Actual result:

<img width="738" alt="Screen Shot 2019-07-30 at 12 47 18 PM" src="https://user-images.githubusercontent.com/2602313/62148695-31c97380-b2c8-11e9-84bc-6b48d28c2966.png">

<img width="519" alt="Screen Shot 2019-07-30 at 12 35 12 PM" src="https://user-images.githubusercontent.com/2602313/62148268-638e0a80-b2c7-11e9-93ff-edf0c3a33498.png">

## Expected result:

Default search engine should be selected in the dropdown instead of `Select a search engine`

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @rebron

**Comment by rebron** [comment]
wontfix. Working as designed.
