### ISSUE TITLE
Allow theme dropdown in onboarding flow

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5454]
## Description 

As @rossmoody mentioned in https://github.com/brave/brave-browser/issues/4992#issuecomment-505266596 there should be a dropdown option 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/62148045-e1054b00-b2c6-11e9-808b-712f4ed2df33.png)

## Expected result:
Stole @rossmoody image from https://github.com/brave/brave-browser/issues/4992#issuecomment-505266596 
![Welcome Light](https://user-images.githubusercontent.com/29072694/60067165-64c38a80-96be-11e9-9108-a32367f39942.jpg)
> In the case of themes the user can see their theme change in real time so that’s the confirmation. 
Onboarding flow should also has a dark mode( #3911)  which can be a good indication of how it looks when dark mode is enabled. 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @rossmoody @rebron

**Comment by kjozwiak** [comment]
Isn't this already implemented in `nightly` via https://github.com/brave/brave-core/pull/2909? Checked the the latest nightly and see the following using `0.70.18 Chromium: 76.0.3809.72`:

<img width="1116" alt="Screen Shot 2019-07-30 at 1 44 11 PM" src="https://user-images.githubusercontent.com/2602313/62152243-22e6bf00-b2d0-11e9-9b7b-cd08436b4a82.png">

**Comment by srirambv** [comment]
#4992 didn't have the actual implementation which is why i logged this issue. I had not checked the PR which had the new implementation.
