### ISSUE TITLE
Dobreprogramy.pl videos are blocked

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#5456]
Follow up to https://github.com/brave/brave-browser/issues/4914. The fix also blocks actual content on the pages. 

## Steps to Reproduce

   1. Clean install
   2. Open video: https://www.dobreprogramy.pl/Instalujemy-Ferro-Backup-System.-Archiwizacja-danych-w-kilku-krokach,Wideo,102811.html

Note: dobreprogramy is the most popular polish website serving software related content

## Actual result:

Video is blocked due to fix in https://github.com/brave/brave-browser/issues/4914
![image](https://user-images.githubusercontent.com/34715963/62154952-18481c00-b308-11e9-8866-5989e1a9bd2d.png)

## Expected result:
Video is shown
![image](https://user-images.githubusercontent.com/34715963/62154998-2e55dc80-b308-11e9-87ff-6b31a6451bc0.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

Brave | 0.67.117 Chromium: 76.0.3809.62 (Official Build) (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

cc @brave/legacy_qa @snyderp @rebron @bsclifton

**Comment by kjozwiak** [comment]
Reproduced on `macOS 10.14.5 x64` using the following build:

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Mac OS X

Brave | 0.70.18 Chromium: 76.0.3809.72 (Official Build) nightly (64-bit)
-- | --
Revision | 5a04c669126f657f98824b436555cae41b8f4146-refs/branch-heads/3809@{#897}
OS | Mac OS X

Seeing the following error via the console:

<img width="673" alt="Screen Shot 2019-07-30 at 2 55 48 PM" src="https://user-images.githubusercontent.com/2602313/62157098-66462b00-b2da-11e9-8516-857851f55877.png">

**Comment by GeetaSarvadnya** [comment]
The issue is Reproducible on Windows 10 x64 - 0.68.114

![image](https://user-images.githubusercontent.com/38657976/62242032-f29a4000-b3f7-11e9-9de6-6538c85df656.png)

**Comment by LaurenWags** [comment]
Reproduced on macOS 10.13.6 with

Brave | 0.68.114 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

**Comment by bsclifton** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
A fix has been submitted, just needs to be approved. Thanks for the report.

**Comment by bsclifton** [comment]
@snyderp @ryanbr looks like this was fixed with https://github.com/brave/adblock-lists/pull/146 and then reverted (but not merged) with https://github.com/brave/adblock-lists/pull/147

Are we safe to close it out?

**Comment by snyderp** [comment]
This is just waiting for a fresh commit from @ryanbr tying the commit to the brave issue being fixed.  Once thats done, this can be merged and closed

**Comment by ryanbr** [comment]
Disconnect list removed `wp.pl` a while back, found another issue ^ Will re-check, it'll probably safe to close this report.

**Comment by btlechowski** [comment]
Good work, I am able to play the video

Verification passed on

Brave | 1.7.70 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

![image](https://user-images.githubusercontent.com/34715963/77380968-ec891300-6d7c-11ea-9079-be2dd5d2e7ea.png)
