### ISSUE TITLE
Exclude toggle crash

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#5457]
## Steps to Reproduce

   1.  Enable rewards
   2.  Go to a site
   3.  Open panel
   4. toggle auto include

## Actual result:

You can't exclude site

## Expected result:
You can exclude site

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on

Brave | 0.68.140 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3044 (verified in both clean and upgraded profile)
- Logged https://github.com/brave/brave-browser/issues/6142
