### ISSUE TITLE
New Setting navigation

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#5458]
New UI for Settings panel navigation that includes Extensions and Crypto Wallets list items. Padding, spacing, sizing and font-size reduced to accommodate more content.

`font-size: 14px;`

![image](https://user-images.githubusercontent.com/29072694/62159420-8f5cc080-b2c6-11e9-9602-2234f44d7055.png)

![image](https://user-images.githubusercontent.com/29072694/62159729-43f6e200-b2c7-11e9-8d1c-806cf2b1d2d4.png)

@petemill @bradleyrichter @karenkliu @rebron

**Comment by rebron** [comment]
Closing. @karenkliu reopen if this issue still applies.
