### ISSUE TITLE
[Security] Mitigate DNS rebinding flaw

### ISSUE THREAD

**Issue by feross** [brave/brave-browser#5460]
Mitigate the WebTorrent DNS rebinding flaw disclosed in HackerOne. Low security/privacy risk.

Original issue: https://github.com/brave/browser-laptop/issues/12616
Original Brave PR: https://github.com/brave/browser-laptop/pull/13844
Original WebTorrent PR: https://github.com/webtorrent/webtorrent/pull/1260
Fixed WebTorrent PR: https://github.com/webtorrent/webtorrent/pull/1678

The fix is already published in `webtorrent@0.105.2`. We should update to this version.

**Comment by feross** [comment]
## Test Plan

1. Go to https://webtorrent.io/free-torrents
2. Select Sintel (magnet link)
3. Start the download
4. Hover your mouse over the download link (the downward-facing arrow) and observe the link's port number. It should be something like e.g. 58630.
5. Run the following command in Terminal (tested on Mac):
  - `cat <(echo -en 'GET / HTTP/1.1\r\nHost: attacker.com\r\n\r\n') - | nc localhost 58630`
  - Note: be sure to replace `58630` in the command with the actual port number you observed in Step 4.
6. The command should hang without outputting anything to Terminal at all. 
  - If you see an HTTP response or HTML, then this is *broken*. Nothing should be output.

**Comment by diracdeltas** [comment]
hackerone issue: https://hackerone.com/reports/663729

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.126 Chromium: 77.0.3865.65 (Official Build) (64-bit)
-- | --
Revision | 87a331a3169cab563505fb44011058b904011ba1-refs/branch-heads/3865@{#726}
OS | macOS Version 10.14.6 (Build 18G95)

* Verified STR outlined under https://github.com/brave/brave-browser/issues/5460#issuecomment-516586163

<img width="1205" alt="Screen Shot 2019-09-18 at 12 52 44 PM" src="https://user-images.githubusercontent.com/2602313/65169330-4eef0880-da14-11e9-9588-4724a184ed46.png">

<img width="1208" alt="Screen Shot 2019-09-18 at 12 53 31 PM" src="https://user-images.githubusercontent.com/2602313/65169336-51516280-da14-11e9-92aa-14b50dca9a4a.png">

**Comment by GeetaSarvadnya** [comment]
@feross  what is the command for windows? I have used the below command in windows and I have got command not found error. 
![image](https://user-images.githubusercontent.com/38657976/65536067-4751c700-df20-11e9-9f82-c0ec189eb3dc.png)

**Comment by yrliou** [comment]
Talked to @GeetaSarvadnya through DM about testing on Windows, note here for future references.
On Windows, we could install nmap from https://nmap.org/ncat/.
When testing, change to the installation folder, such as `c\Program Files (x86)\Nmap`, and run 
`cat <(echo -en 'GET / HTTP/1.1\r\nHost: attacker.com\r\n\r\n') - | ./ncat.exe localhost 49976` (Replace port with the result of previous step.)
