### ISSUE TITLE
Theme change doesn't update URL bar until mouse over

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5462]
## Description 

Theme change doesn't update URL bar until mouse over

## Steps to Reproduce

   1. Upgrade to `0.68.113`
   2. Change theme in settings
   3. URL bar theme changes only when you mouse over or tab focus is changed

## Actual result:

![urltheme](https://user-images.githubusercontent.com/17010094/62165387-52a3c000-b2ec-11e9-963f-fb993f594634.gif)

## Expected result:
Should automatically change when theme is changed

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Sort of different issue  #5464
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by simonhong** [comment]
This can be fixed by https://github.com/brave/brave-core/pull/2905 that already in `0.69.x`

**Comment by simonhong** [comment]
Closed because this was fixed by https://github.com/brave/brave-core/pull/2905

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.119 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified STR from description. 
* Encountered https://github.com/brave/brave-browser/issues/5423
