### ISSUE TITLE
Using user wallets with withdraw funds from a restored wallet doesn't work

### ISSUE THREAD

**Issue by zavan** [brave/brave-browser#5463]
## Description
I downloaded the latest nightly version to test the new withdraw feature but it didn't work, uphold shows my "Brave Browser" card as empty.

I originaly opened #5398 for this issue, where I was told this should be fixed in the next nightly release, but it didn't so I'm reopening.

## Steps to Reproduce
   1. Download latest version of Brave Browser nightly and install it
   2. Recover your funded wallet from the seed of the stable version
   3. Click "Withdraw" on the Rewards page
   4. Login into a verified uphold account, linking it to the Brave Wallet

## Actual result:
A new card called "Brave Browser" is created on Uphold, but it shows 0 funds.

<img width="388" alt="Screen Shot 2019-07-25 at 19 22 05" src="https://user-images.githubusercontent.com/1722965/61913687-45fe2100-af14-11e9-913e-5434eaeb14b5.png">
<img width="362" alt="Screen Shot 2019-07-25 at 19 22 16" src="https://user-images.githubusercontent.com/1722965/61913690-48607b00-af14-11e9-88ca-7295612e11d9.png">

## Expected result:
Funds show on "Brave Broswer" card on Uphold.

## Reproduces how often:
I tried deleting Nightly and its data dir, reinstalling the latest version, restoring the wallet and clicking withdraw again. Same result.

## Brave version (brave://version info)

Brave | 0.70.12 Chromium: 76.0.3809.72 (Official Build) nightly (64-bit)
-- | --
Revision | 5a04c669126f657f98824b436555cae41b8f4146-refs/branch-heads/3809@{#897}
OS | Mac OS X
JavaScript | V8 7.6.303.22
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.72 Safari/537.36
Command Line | /Applications/Brave Browser Nightly.app/Contents/MacOS/Brave Browser Nightly --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-features=NewExtensionUpdaterService,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,NetworkService,UnifiedConsent --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser Nightly.app/Contents/MacOS/Brave Browser Nightly
Profile Path | /Users/zavan/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/Default
Variations | d74ef32b-c7113149

**Comment by NejcZdovc** [comment]
@zavan would love to jump on a call and check it out. If you are up for it, please send me email on nejc[@]brave.com. Thank you

**Comment by kjozwiak** [comment]
Thanks for refiling @zavan 👍 CCing @kjozwiak (myself) to see if I can reproduce.

**Comment by NejcZdovc** [comment]
closing as stale

**Comment by HTransistor** [comment]
@NejcZdovc Why are you closing all issues where withdrawing is not working without fixing it. Every 2 weeks somebody reopens that. You should just fix that!
