### ISSUE TITLE
Theme change only updates webUI and not URL bar

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5464]
## Description 

Theme change only updates webUI and not URL bar

## Steps to Reproduce

   1. Upgrade to 0.69.94
   2. Toggle theme from dark to light
   3. Only webui theme changes, URL bar remains dark

## Actual result:

![devtheme](https://user-images.githubusercontent.com/17010094/62165872-64399780-b2ed-11e9-8aa2-5a8dee38bbb1.gif)

## Expected result:
Should change both webui and URL bar theme accordingly 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.69.94 Chromium: 76.0.3809.62 (Official Build) dev (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? #5462
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Similar to https://github.com/brave/brave-browser/issues/5462

**Comment by simonhong** [comment]
@srirambv  When user choose `GTK+` theme instead of `Classic`, gtk theme is used instead of brave theme by https://github.com/brave/brave-core/pull/2905.
So, native ui such as url bar will not be changed by changing brave theme option.
With `Classic` theme, brave theme change will change webui & native ui both.

**Comment by rebron** [comment]
@simonhong This doesn't sound like a bug. Working as expected?

**Comment by simonhong** [comment]
@rebron yes, this is expected behavior.

**Comment by srirambv** [comment]
@simonhong  should we close if this is the expected behaviour? (Its still weird that you have to mouse over for the change to happen and not automatic)

**Comment by simonhong** [comment]
@srirambv This can be closed. After changing theme option, native ui(ex, omnibox) doesn't change at all. I can't see ui change during the mouse hover?
