### ISSUE TITLE
Enable STP by default

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#5468]
## Description 
Smart Tracking Protection is disabled by default on master, verify that there are no webcompat issues with using this minimal list:

https://github.com/brave/tracking-protection/blob/master/data/StorageTrackingProtection.dat

and enable the build time and runtime flags by default.

https://github.com/brave/brave-browser/blob/446e8f6e99bfc5a7cb329a6a1de7233b165c410e/lib/start.js#L52

https://github.com/brave/brave-core/blob/7cdda52dc9f31e29d4f4ee0e43aadaedcd06f301/components/brave_shields/browser/buildflags/BUILD.gn#L7

**Comment by pes10k** [comment]
@jumde can we close this, now that STP in its current form doesn't seem likely to be deployed?

**Comment by jumde** [comment]
@pes10k - Please do, but we need two more follow issues:

1. To remove the current STP code.
2. Re-implement STP to prevent bounce tracking.

**Comment by pes10k** [comment]
Sounds good, will close now. If you dont already have issues for 1 and / or 2 above, and would like me to create them, just let me know :)
