### ISSUE TITLE
Add SoundCloud Panel support

### ISSUE THREAD

**Issue by jdkuki** [brave/brave-browser#5469]
## Description 

Feature request:

Add panel tipping support for SoundCloud

## Steps to Reproduce

n/a

## Actual result:

n/a

## Expected result:
![image](https://user-images.githubusercontent.com/8422122/62170842-b2489e00-b2e1-11e9-876c-fa4475f7c66c.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
CCing @NejcZdovc & @alexwykoff ☝️
