### ISSUE TITLE
brave shields extension action toggles are broken

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#5470]
## Description 
None of the toggles for brave shields settings take effect

## Steps to Reproduce
   1. Go to google.com
   2. Turn off brave shields for google.com

## Actual result:
Nothing changes and the page doesn't reload

## Expected result:
Settings should change and reload the page

## Reproduces how often: 
Always

## Brave version (brave://version info)
0.70.16

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.69.121 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Linux

* Verified shields up/down causes the page to reload
* Verified all individual switch on shields causes page to reload when toggled
