### ISSUE TITLE
WebTorrent: Autoplay is sometimes blocked if media metadata is not ready yet

### ISSUE THREAD

**Issue by feross** [brave/brave-browser#5471]
## Description 

If the media element does not have metadata available immediately when the media viewer loads, then autoplay will fail with a `DOMException`.

## Steps to Reproduce

   1. Load the torrent from https://ia802608.us.archive.org/18/items/gd1975-06-17.aud.unknown.87560.flac16/gd1975-06-17.aud.unknown.87560.flac16_archive.torrent
   2. Start the download. 
   3. Scroll to the bottom of the file list and select the last MP3 file in the list (file number 111). (This is so that the file data is not likely to be downloaded by webtorrent yet.)
   4. The file should eventually start playing. There should be no warning that autoplay was blocked.

## Actual result:

Media sometimes does not autoplay.

## Expected result:
Media should always autoplay.

## Reproduces how often: 

Intermittent issue

## Brave version (brave://version info)

`master`

**Comment by kjozwiak** [comment]
@feross looks like this is still happening here and there. It takes a few tries to reproduce on a new profile, but you'll eventually run into the following:

<img width="1090" alt="Screen Shot 2019-09-19 at 10 19 24 PM" src="https://user-images.githubusercontent.com/2602313/65294192-e430f080-db2b-11e9-9339-5394d70d9c2d.png">

Used the following build:

Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | macOS Version 10.14.6 (Build 18G95)

I couldn't reproduce the above using https://webtorrent.io/torrents/wired-cd.torrent though. Maybe it's based on timing? I was running through the case pretty quickly. We can definitely label this as verified as it's a big improvement compared the previous behaviouor. @feross thoughts?

**Comment by feross** [comment]
Yeah, I noticed this as well. The fix felt a little hacky, but it now works like 95% of the time, which is better than 0%. I wish there was some easy way to just disable autoplay policy for the WebTorrent extension. I wonder if @yrliou has any ideas how to do this or who to ask.

**Comment by rebron** [comment]
@darkdh suggestions for this one?

**Comment by darkdh** [comment]
We have autoplay whitelist (https://github.com/brave/autoplay-whitelist) but it only support url host right now (https://github.com/brave/autoplay-whitelist/blob/master/data/autoplay.json)
Maybe we can make it support extension id like webtorrent's case
`chrome-extension://lgjmpdmojkpocjcopdikifhejkkjglho/extension/brave_webtorrent.html?https://webtorrent.io/torrents/wired-cd.torrent`

**Comment by darkdh** [comment]
For example, I added webtorrent to autoplay content setting like this
<img width="533" alt="Screen Shot 2019-09-19 at 20 40 08" src="https://user-images.githubusercontent.com/11330831/65297703-bd6bbd80-db1d-11e9-96cf-24ae2f34414c.png">
<img width="696" alt="Screen Shot 2019-09-19 at 20 40 56" src="https://user-images.githubusercontent.com/11330831/65297732-d07e8d80-db1d-11e9-8c47-2476b32d7890.png">
This allows any media from webtorrent to autoplay.

**Comment by kjozwiak** [comment]
I can confirm that adding `chrome-extension://lgjmpdmojkpocjcopdikifhejkkjglho/` into the auto play content settings fixes what I ran into https://github.com/brave/brave-browser/issues/5471#issuecomment-533377729. Couldn't reproduce the issue after several attempts.

**Comment by kjozwiak** [comment]
@rebron @darkdh should we create a new issue for adding the ability to add extensions into the autoplay whitelist? We can continue verifying this one as it works ~95% of the time and can address the issue in more detail in another GH. Thoughts?

**Comment by feross** [comment]
> should we create a new issue for adding the ability to add extensions into the autoplay whitelist?

Didn't you say that you were already able to add the WebTorrent extension URL into the whitelist? So shouldn't the issue actually be to add WebTorrent to the list by default?

**Comment by darkdh** [comment]
The thing we added above is "Content Setting", the brave autoplay list is beyond that.
Every time autoplay permission request coming, we check brave autoplay whitelist first and then check content setting if host doesn't match anything in the whitelist

**Comment by feross** [comment]
@darkdh Thanks for explaining the distinction. Makes sense!

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3052

![image](https://user-images.githubusercontent.com/34715963/65767175-683b3780-e12d-11e9-9afb-b19ce599aafc.png)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

The issue still reproduces. Logged https://github.com/brave/brave-browser/issues/6195.
![image](https://user-images.githubusercontent.com/34715963/65767953-c5d08380-e12f-11e9-9ec3-2797612d0504.png)
