### ISSUE TITLE
Possible to select text in Shields Menu by double clicking the blocked scripts

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#5472]
Follow up to https://github.com/brave/brave-browser/issues/4570

Important: Not sure if it is by design or an actual issue

## Steps to Reproduce

   1. Open `https://www.buzzfeed.com`
   2. Block the scripts in Shields
   3. Go to `Scripts blocked` detailed view
   4. Double click the blocked script

## Actual result:

The script text is selected
![5472](https://user-images.githubusercontent.com/34715963/62212667-87be1a00-b3a1-11e9-9828-a9815ad8054a.gif)

## Expected result:
The script text is not selected

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Ubuntu 18.04 LTS

Not reproducible in

Brave | 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
-- | --
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @cezaraugusto @karenkliu

**Comment by ryanbr** [comment]
I use Ctrl-A, Ctrl-C. is this possible in the new screen?

**Comment by btlechowski** [comment]
@ryanbr This is about detailed view of `Scripts blocked`. This is not about detailed view of `Cross-site trackers blocked`. You can still copy list of trackers blocked from detailed view of `Cross-site trackers blocked`. The functionality didn't change there.

![image](https://user-images.githubusercontent.com/34715963/62211481-e766f600-b39e-11e9-84eb-785f57f31cc1.png)

**Comment by ryanbr** [comment]
Ah right

**Comment by srirambv** [comment]
It used to be the same behaviour before. May have regressed where you couldn't select it but now it's working correctly. You should be allowed to highlight the blocked URLs to see the actual link since shields only have limited visibility for the URLs'

**Comment by cezaraugusto** [comment]
hi @btlechowski thanks for reporting. we intent to implement a copy/paste interface in the future but for now this is expected behavior. closing as wontfix
