### ISSUE TITLE
Unrecoverable crash loop after hibernate

### ISSUE THREAD

**Issue by latonv** [brave/brave-browser#5473]
## Description 

I hibernated my Windows 10 machine with Brave open (and a number of other applications), as I often do. Upon resuming from hibernation, Brave crashed within a minute or so with no interaction from me -- it was just sitting open in the background. Now, whenever I try to open Brave again, it stays open for about 4 seconds, showing the "Restore pages" bubble, but then crashes again. I've also tried opening only a private window, and the result is the same: almost immediate crash.

I think there were only a few tabs open at the time that I hibernated... one was a Google Sheet, don't remember the others.

## Steps to Reproduce

I have to admit, I'm not really sure what made this crash happen. I'm only speculating that it had something to with resuming from hibernation. But here's more or less what I did:

First crash:
   1. Run Brave
   2. Hibernate
   3. Resume from hibernation
   4. Crash

Subsequent crashes after first:
   1. Open Brave, do nothing
   2. Crash within a few seconds

## Actual result:

Immediate crash

## Expected result:
No crash

## Reproduces how often: 

The subsequent crashes are happening with 100% reliability on my end. As for the initial crash, I don't know.

## Brave version (brave://version info)

Brave: 75.0.66.101 (according to the list of installed programs)
OS: Windows 10 Pro (64-bit), Version 1903, Build 18362.175

## Version/Channel Information:

- Can you reproduce this issue with the current release? **Yes (I'm on the current release, right?)**
- Can you reproduce this issue with the beta channel? **Haven't tried**
- Can you reproduce this issue with the dev channel? **Haven't tried**
- Can you reproduce this issue with the nightly channel? **Haven't tried**

## Other Additional Information:
I can't disable or change any settings, because Brave won't stay open long enough for me to try.

- Does the issue resolve itself when disabling Brave Shields? **Can't try**
- Does the issue resolve itself when disabling Brave Rewards? **Can't try**
- Is the issue reproducible on the latest version of Chrome? **Chrome was open too when this started, haven't had any issues with it**

## Miscellaneous Information:

I have Crashpad dumps for every crash, but can't access brave://crashes to upload them...

Every crash corresponds to a warning in the Windows Event Viewer that looks something like this:
```The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user <redacted> from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.
```
Not sure if that's related to Brave starting up or it crashing though.

**Comment by kjozwiak** [comment]
@latonv mind taking a look under `brave://crashes` and see if there's any recorded crashes?

**Comment by latonv** [comment]
I would, but I can't actually get into `brave://crashes` because the browser always crashes before I can get there. However, there do seem to be crash dump files in `%LOCALAPPDATA%\BraveSoftware\Brave-Browser\User Data\Crashpad\reports` for every crash so far. How can I get them to you?

**Comment by simonhong** [comment]
@latonv I think this issue seems similar with https://github.com/brave/brave-browser/issues/4764.
Can you test with [nightly](https://www.brave.com/download-nightly) or [dev](https://www.brave.com/download-dev) release?

**Comment by latonv** [comment]
I'm unable to reproduce the crash in a fresh install of the dev release; it may well be the same issue.

**Comment by simonhong** [comment]
@latonv Thanks for checking! 👍
