### ISSUE TITLE
"Wallet provided by" strings need to accommodate localization.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#5477]
Strings like `Our wallet service is provided by` or `Brave wallet is managed by` are intended to be followed by the company name which is bolded in the UI. However, in certain languages the company name isn't placed at the end. For example, if the sentence is like "Your Brave wallet is powered by ABC" then the translation would be "आपका Brave वॉलेट ABC द्वारा संचालित है".

We need to allow for localizing such string, perhaps by providing a second (empty) string where the localizers could move words that go after the company name.

cc: @NejcZdovc

**Comment by NejcZdovc** [comment]
@mkarolin do you maybe have list of strings that are problematic?

**Comment by mkarolin** [comment]
@NejcZdovc no, sorry. I believe I just ran into it accidentally in Transifex, but it's not something I actively tracked.

**Comment by NejcZdovc** [comment]
ok will fix `Our wallet service is provided by` in this issue and if we find anything else we can just open an issue for it
