### ISSUE TITLE
Revert Enable Brave ads for Australia, New Zealand and Ireland from 0.67.x

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#5481]
Reverts https://github.com/brave/brave-core/pull/2865

**Comment by kjozwiak** [comment]
@bsclifton @rebron removing this from the `0.67.x` milestone. @tmancey we might want to close this off as per earlier discussions on Slack.

**Comment by tmancey** [comment]
No longer required as agreed to release feature
