### ISSUE TITLE
Issue: In page Uphold flow vs. using tabs

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#5482]
To reduce in tab errors and managing workflows to send user back, it would be good to have the Uphold flow in-page vs. via creating new tab for every single call (auth, reg, kyc, etc.).

The current UX on this is bad; Prioritizing to land within 0.69 dev timeframe!

@NejcZdovc

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.113 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/3069
- Verified uphold page displayed in the same tab when verifying wallet by clicking on `Verify wallet` in the brave://rewards page 
- Verified uphold page displayed in the same tab when verifying wallet by clicking on `Add funds` in the brave://rewards page 
- Verified uphold page displayed in the same tab when verifying wallet by clicking on `Withdraw Funds` in the brave://rewards page
![image](https://user-images.githubusercontent.com/38657976/63547124-16f5c200-c549-11e9-9e45-aed6515cee65.png)
