### ISSUE TITLE
Shields menu not visible after allowing all scripts

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5483]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/4570

Shields menu not visible after allowing all scripts

## Steps to Reproduce

STR1:

   1. Clean profile 0.68.114
   2. Open buzzfeed.com in a new tab
   3. Click on Shield 
   4. Turn ON `Scripts blocked` option
   5. Click on `Scripts blocked` in the shield
   6. Click on `Allow All` in Blocked scripts
   7. Click on `Allow All` again in Blocked scripts
   8. Shields menu not visible after allowing all scripts

STR2:
  1. Clean profile 0.68.114
  2. Open buzzfeed.com in a new tab
  3. Click on shield panel
  4. Turn ON scripts
  5. Click on Cross-site trackers blocked
  6. `Allow scripts once` link is reflected in cross-site trackers list
  7. Click on `Allow scripts once` link multiple times which is reflected in cross-site trackers list
  8. Click on `Scripts blocked` in the shield
  9. Shield menu is NOT visible

  
## Actual result:

Shields menu not visible after allowing all scripts

![image](https://user-images.githubusercontent.com/38657976/62231505-cffd2c80-b3e1-11e9-9bc8-bc3f6d5266a1.png)

Recorded file:
https://drive.google.com/open?id=1D9c7nyl-N0iB4ULng47pLIahIrbG1HDw

## Expected result:
Shields menu should be displayed after allowing all scripts

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.68.114 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @cezaraugusto @karenkliu @rebron

**Comment by LaurenWags** [comment]
Reproduced with macOS

Brave | 0.68.118 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

**Comment by btlechowski** [comment]
Reproduced on Ubuntu

Brave | 0.68.118 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Ubuntu 18.04 LTS

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.121 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the STR from the description
