### ISSUE TITLE
`Allow scripts once` is reflected in cross-site trackers list after enabling the scripts

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5486]
## Description 

Found while testing #4570 

`Allow scripts once` is reflected in cross-site trackers list after enabling the scripts

## Steps to Reproduce

   1. Clean profile 0.68.114
   2. Open buzzfeed.com in a new tab
   3. Click on shield panel
   4. Turn ON scripts
   5. Click on `Cross-site trackers blocked`
   6. `Allow scripts once` is reflected in cross-site trackers list

## Actual result:

`Allow scripts once` is reflected in cross-site trackers list after enabling the scripts

![image](https://user-images.githubusercontent.com/38657976/62235186-0a6ac780-b3ea-11e9-8dc6-177c8bbfc656.png)

## Expected result:

`Allow scripts once` should not reflect in cross-site trackers list after enabling the scripts
## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.68.114 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @cezaraugusto @karenkliu

**Comment by LaurenWags** [comment]
Reproduced with macOS

Brave | 0.68.118 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

**Comment by btlechowski** [comment]
Reproduced on Ubuntu

Brave | 0.68.118 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Ubuntu 18.04 LTS

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.113 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/3066
