### ISSUE TITLE
WebTorrent: server serves files with "Content-Type: null"

### ISSUE THREAD

**Issue by feross** [brave/brave-browser#5489]
If the file extension is unrecognized, the webtorrent HTTP server will use a `Content-Type` header with a value of `null`, which is invalid.

**Comment by feross** [comment]
This is fixed in `webtorrent@0.105.3`. We need to update the version, but I'll hold off until https://github.com/brave/brave-browser/issues/5490 is fixed so we can update just once.

**Comment by feross** [comment]
Once we bump the version of `webtorrent`, this issue will be fixed.

**Comment by yrliou** [comment]
Upgrade reverted by https://github.com/brave/brave-core/pull/3136

**Comment by btlechowski** [comment]
Could add `QA/Yes` or `QA/No` label?

**Comment by feross** [comment]
Sure. I just added `QA/No`.
