### ISSUE TITLE
New window is created when trying to move a tab from the end of the tab list

### ISSUE THREAD

**Issue by misku** [brave/brave-browser#5493]
## Description 

OS: Ubuntu Linux 18.04 LTS
When I try to move a tab from the end of a tab list (horizontal movement) it creates a new window. It is really odd as it only happens when trying to move one of the 3-4 last tabs (on the right). Total tabs open: 20.

When I try to move a tab from a left side, I can move it through almost all of the tabs to the right, but around a 3-4th tab from the right Brave creates a new window. Result: I cannot drag the tab to e.g. the end of the tab list.

## Steps to Reproduce

   1. Open 6 tabs in a new window.
   2. Try to drag the one before last tab (5th) to the last position.
 
   1. Open 6 tabs in a new window.
   2. Try to drag the last tab (6th) to the one before last position (5th).

## Actual result:

A new window is opened with the tab being dragged.

## Expected result:
Tab moves to the proper place in the list and changes its position without opening any new windows.

## Reproduces how often: 

Every single time.

## Brave version (brave://version info)

Version 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
**Yes**
- Can you reproduce this issue with the beta channel?
**N/A**
- Can you reproduce this issue with the dev channel?
**N/A**
- Can you reproduce this issue with the nightly channel?
**N/A**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
**No**
- Does the issue resolve itself when disabling Brave Rewards?
**No**
- Is the issue reproducible on the latest version of Chrome?
**No. In Chrome it works fine. Version 75.0.3770.142 (Official Build) (64-bit)**

## Miscellaneous Information:

Linux 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

**Comment by srirambv** [comment]
Could you record the steps you are doing? If the tab moves a little out of tabs bar it will tear off into a new window which is expected. I am unable to reproduce this on Ubunutu 18/19

**Comment by misku** [comment]
Thanks for a quick answer. I'm carefully trying not to move my cursor vertically as like you said, then it definitely should jump into the new window.
Here's a screen cast (mp4 H.264), I hope it'll help: https://anonymousfiles.io/4Fw4R5Cd/

**Comment by srirambv** [comment]
Well that is weird. I am not able to reproduce the issue at all. @brave/legacy_qa to try to reproduce the issue

**Comment by misku** [comment]
Looks like `404` to me.
