### ISSUE TITLE
Udemy videos do not play with Shields OFF

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#5497]
## Steps to Reproduce

   1. Go to https://www.udemy.com/the-complete-javascript-course/learn/lecture/5869076#overview
   2. Hit play on the video
   3. Infinite Loop (video doesn't play and console gets spammed)
   4. Console shows:
       ```
        VIDEOJS: WARN: Problem encountered with the current HLS playlist. HLS request errored at URL: HTTPS://h.udemycdn-a.com/851712/13059092/2018-06-20_14-09-58-c0ee9005191996b8b7a78bca8a0d912a/hls/hls_480/aa00ace74f03aa29f7b4bd0558ea42ff3b427.ts Switching to another playlist.
        ```
   5. Chrome & Firefox doesn't have this issue and console doesn't log these warnings in both.
   6. Disable Shields (shields down, you're browsing this site without privacy protection...): It still happens.
   7.  Enable ALL cookies in "Global Shield Defaults" and refresh the page.. The site will load.

To reproduce the issue multiple times, clear your cookies and try the steps above.

## Actual result:
<img width="1428" alt="Screen Shot 2019-08-01 at 10 18 47 AM" src="https://user-images.githubusercontent.com/1530031/62301145-079dc000-b446-11e9-806c-e3f6a3611bf8.png">

## Expected result:
It should load the page with `"Shields Down"` and not force the user to disable `"Global Shields"`.

## Reproduces how often: 
Easily Reproduced.

## Brave version (brave://version info)

Brave | 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
-- | --
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Mac OS X
JavaScript | V8 7.5.288.30
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=NewExtensionUpdaterService,DesktopPWAWindowing --disable-features=LookalikeUrlNavigationSuggestionsUI,AutofillServerCommunication,AudioServiceOutOfProcess,DefaultEnableOopRasterization,UnifiedConsent,AutofillSaveCardSignInAfterLocalSave,NetworkService,TranslateUI --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/*******/Library/Application Support/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:
Not sure what this means but happens on every version of Brave.

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

Yes. Can reproduce on all of the above.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? - No.
- Does the issue resolve itself when disabling Global Shields? - Yes.
- Does the issue resolve itself when disabling Brave Rewards? - No.
- Is the issue reproducible on the latest version of Chrome?  - No.

**Comment by kjozwiak** [comment]
CCing @ryanbr. Mind taking a look at this when you have some time? Thanks!

**Comment by ryanbr** [comment]
Just Allow all cookies, that should fix it.

**Comment by Brandon-T** [comment]
@ryanbr 

<img width="1440" alt="Screen Shot 2019-08-05 at 7 59 57 PM" src="https://user-images.githubusercontent.com/1530031/62502087-c8f86480-b7bb-11e9-83cf-c61948c6321c.png">

**Comment by ryanbr** [comment]
Re-tested it in Brave Release, (thanks Jimmy for the login). 

https://secure.fanboy.co.nz/gif/udemy.gif

Seems to work

**Comment by ryanbr** [comment]
I did notice 3rd-party device recognition being hit, does allowing all devices help?

**Comment by noslenac** [comment]
This issue also seems to affecting even viewing courses now. No amount of preference changes seem to correct the issue. 

Globally allowing all device recognition, cross-site trackers, and cross-site cookies does nothing to allow access to site content.

**Comment by wejesuss** [comment]
I am also having this problem, I tried everything, but just changing the browser worked.

**Comment by ryanbr** [comment]
> I am also having this problem, I tried everything, but just changing the browser worked.

Do you have `brave://settings/?search=widevine` enabled? (Maybe disable, restart browser and then re-enable widevine)

Have had report extensions causing issues (Chrome dark mode?) on udemy also. @wejesuss

**Comment by wejesuss** [comment]
> > I am also having this problem, I tried everything, but just changing the browser worked.
> 
> Do you have `brave://settings/?search=widevine` enabled? (Maybe disable, restart browser and then re-enable widevine)
> 
> Have had report extensions causing issues (Chrome dark mode?) on udemy also. @wejesuss

I do not have widevine enabled, but it's strange because a few days ago the udemy website was working fine with widevine disabled and it stopped working suddenly, I think that something changed on udemy website.

**Comment by ryanbr** [comment]
Yeah, something may've changed. But I was troubleshooting udemy a few days back and noticed widevine is being used by the site now

**Comment by ryanbr** [comment]
Is it working for you @Brandon-T ? (if you enable widevine)

**Comment by ryanbr** [comment]
Closing ticket, Widevine just needs to be enabled here.
