### ISSUE TITLE
Rewards server not responding

### ISSUE THREAD

**Issue by whenm00n** [brave/brave-browser#5498]
## Description

Rewards server is not responding

## Actual result:
![image](https://user-images.githubusercontent.com/35568825/62302342-139f7700-b472-11e9-9250-6b6d31b5ebbf.png)

## Brave version
Version 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No

**Comment by NejcZdovc** [comment]
@whenm00n thank you for the report. We have some problems with the server and will fix it asap. You can track it here https://status.brave.com/incidents/33q8y5bk3yzs
