### ISSUE TITLE
Change alert icon in rewards panel

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#5501]
Adjust the icon from an `X` to a `!` to avoid users thinking they can click it. 
@bradleyrichter @jenn-rhim @alexwykoff 

### Current

![image](https://user-images.githubusercontent.com/29072694/62317884-74698800-b44f-11e9-97d6-89226b43e898.png)

### New

![image](https://user-images.githubusercontent.com/29072694/62318228-37ea5c00-b450-11e9-8481-529d361bcb3c.png)

**Comment by rossmoody** [comment]
@NejcZdovc are there outstanding parts of this that still need fixed after the latest merge?

**Comment by NejcZdovc** [comment]
this was done in https://github.com/brave/brave-ui/pull/521

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.71.82 Chromium: 77.0.3865.90 (Official Build) dev (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

* Verified `x` is replaced with `!` on rewards panel and in brave://rewards
![Screenshot from 2020-05-01 11-20-00](https://user-images.githubusercontent.com/17010094/65976103-a4c4a700-e43d-11e9-891b-b9237e6544ea.png)
![image](https://user-images.githubusercontent.com/17010094/65976202-c9208380-e43d-11e9-9edc-2249df2d0d8f.png)
