### ISSUE TITLE
improve accessibility on welcome experience

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#5504]
## Description 
Tabbing currently prompts some pretty odd formatting and behavior bugs. I didn't deep dive into the causes or solves but it looks like you can tab through all the slides at once. Would be nice to give each interactive element a tab index and limit it to what's visible on the page. 

## Steps to Reproduce

   1. go to brave://welcome on nightly
   2. Press tab 4-7 times
   3. Behold

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.1.2 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3300
`Tab` now jumps around select-able elements.
