### ISSUE TITLE
WebTorrent: Use friendly URLs for download links

### ISSUE THREAD

**Issue by feross** [brave/brave-browser#5506]
## Description 

We should like to a friendly filename instead of a file named `/0` or `/1`. This will make the torrent links look less sketchy.

## Steps to Reproduce

   1. Go to https://webtorrent.io/free-torrents
   2. Start Big Buck Bunny (torrent)
   3. Start download
   4. Hover over the "Save File" link (looks like a downward-facing arrow)

## Actual result:

![Screen Shot 2019-08-01 at 2 08 37 PM](https://user-images.githubusercontent.com/121766/62327681-172d0100-b466-11e9-82c2-43d59e154f3c.png)

## Expected result:
A URL with the actual file name in it.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

All versions.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.126 Chromium: 77.0.3865.65 (Official Build) (64-bit)
-- | --
Revision | 87a331a3169cab563505fb44011058b904011ba1-refs/branch-heads/3865@{#726}
OS | macOS Version 10.14.6 (Build 18G95)

<img width="318" alt="Screen Shot 2019-09-18 at 1 03 45 PM" src="https://user-images.githubusercontent.com/2602313/65169557-c755c980-da14-11e9-992f-79ff8678379e.png">
<img width="407" alt="Screen Shot 2019-09-18 at 1 03 27 PM" src="https://user-images.githubusercontent.com/2602313/65169558-c755c980-da14-11e9-895c-9dd6c474bac4.png">
<img width="359" alt="Screen Shot 2019-09-18 at 1 03 05 PM" src="https://user-images.githubusercontent.com/2602313/65169560-c755c980-da14-11e9-9abf-4848780dd258.png">
