### ISSUE TITLE
Brave ads mobile delivery policy change

### ISSUE THREAD

**Issue by EyanGoldman** [brave/brave-browser#5507]
Ads delivery policy change on mobile, will need to be taken into consideration for bat-native-ads library for brave-core.
Linked to: https://github.com/brave/browser-android-tabs/issues/1913

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.130 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from https://github.com/brave/brave-core/pull/3080
* Verified 2x per hour and 5x per hour frequencies.
* Verified switching frequency setting was honored without having to restart the browser.
