### ISSUE TITLE
Remove confirm button from changing theme option in onboarding

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5509]
## Description 

Remove confirm button from changing theme option in onboarding

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/62338912-3f3d5400-b4a8-11e9-9501-b04351ff9bb0.png)

## Expected result:
No confirm button required as the drop-down makes the visual change instantly 

cc: @simonhong @rebron @rossmoody

**Comment by kjozwiak** [comment]
Also mentioned via https://github.com/brave/brave-browser/issues/1548#issuecomment-516484377 where we had a discussion regarding removing both of the `Confirm` buttons for both `Search` and `Themes`.

Agreed that the confirm button seems a but redundant for theme selection. However, @rossmoody made some good points via https://github.com/brave/brave-browser/issues/1548#issuecomment-516498115. However, might be more applicable to the `Confirm` button for `Search`.

**Comment by srirambv** [comment]
I feel instead of having the confirm button, we can just add a text label that says `New search engine set` if user changes the default from dropdown. The button placement looks odd to me. Adding the text makes visual confirmation as well and avoids awkward button placement as well. Just a thought but will leave decision upto the design team

**Comment by kjozwiak** [comment]
CCing @rossmoody to update the above with a possible new implementation discussed on Slack.

**Comment by rossmoody** [comment]
I think the direction of this one can stay as-is. Removing the confirm button for this panel is non-detrimental and users can use the next button.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3088
- Verified the STR from the description
