### ISSUE TITLE
Add switch to disable WebRTC

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#551]

**Comment by bbondy** [comment]
Is this different from fingerprinting protection which I think already does this?

**Comment by jumde** [comment]
`Block All fingerprinting` does disable WebRTC but, after a reddit discussion the webrtc options was moved to a site setting in case the user does not `Block All Fingerprinting` since it does break some known sites. See: https://github.com/brave/browser-laptop/issues/13668

**Comment by yrliou** [comment]
`Block All fingerprinting` does not disable WebRTC entirely, it only make methods that could be causing IP leaks act similar as no-op.
I suppose the original idea of adding this switch in browser-laptop is users could have a way to disable WebRTC without turning on `Block All Fingerprinting` which might break sites.

I just quickly checked the website, the result is as follows.
<img width="464" alt="screen shot 2018-07-16 at 5 37 04 pm" src="https://user-images.githubusercontent.com/4730197/42790252-e5f3de9c-891e-11e8-937d-cad1e84daa0c.png">
It does prevent IP leakage and has the same result of `Block All fingerprinting` in browser-laptop.
@jumde Could you point me where the test showing us having the WebRTC leak so I could check on my end?

**Comment by jumde** [comment]
WebRTC is blocked on `whoer.net`, I think the page did not reload correctly, and so it was still showing the IP address. Sorry about that.

Re: - 
```
I suppose the original idea of adding this switch in browser-laptop is users could have a way to disable WebRTC without turning on Block All Fingerprinting which might break sites.
``` 
We should probably do the same in `brave-core`

**Comment by jumde** [comment]
This is available on `browser-laptop`

<img width="652" alt="screen shot 2018-08-16 at 1 51 53 pm" src="https://user-images.githubusercontent.com/1903815/44234526-ac52bf00-a15b-11e8-8ce2-2b3021c0e762.png">

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/any-suggestion-to-stop-webrtc-leak-with-brave-dev-browser/32114/3

**Comment by yrliou** [comment]
Please see brave/brave-core#538 for the test plan, thanks.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

* Verified WebRTC policy is listed under Privacy settings
* Verified Default WebRTC setting shows IP as expected
* Verified `Default public and private interfaces` setting shows IP as expected
* Verified `Disable non-proxied UDP` blocks all IP as expected
