### ISSUE TITLE
Minimize and Maximize buttons not visible in Ubuntu 18.04

### ISSUE THREAD

**Issue by serpro69** [brave/brave-browser#5511]
## Description 
Since updating to one of the latest versions I noticed that Minimize and Maximize buttons have disappeared from the top panel. Only Close button is present.

## Actual result:
![image](https://user-images.githubusercontent.com/22973227/62348585-64a87d00-b4fd-11e9-8dba-ace94f50f3e5.png)

## Expected result:
![image](https://user-images.githubusercontent.com/22973227/62348599-70943f00-b4fd-11e9-9812-2e73de9d9526.png)

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
-- | --
Revision | 8d93477bd18154c67a70a67019cb8032382c55dd-refs/branch-heads/3770@{#1160}
OS | Linux

**Comment by kjozwiak** [comment]
@serpro69 we just released `0.67.123 Chromium: 76.0.3809.87` today. Could you update and see if you can still reproduce?

**Comment by serpro69** [comment]
Hi @kjozwiak, thanks for prompt response. I've just tried on the latest version `0.67.123 Chromium: 76.0.3809.87 (Official Build) (64-bit)` and still have the same issue.

**Comment by srirambv** [comment]
@serpro69  Which desktop environment are you on? Have you tried enabling the maximize and minimize buttons via the tweak tool? By default maximize and minimize is disabled.
![image](https://user-images.githubusercontent.com/17010094/62372126-a7218800-b504-11e9-94fd-874b0915ffc8.png)

**Comment by serpro69** [comment]
@srirambv I'm on gnome. I have those buttons enabled and they're showing fine in other apps (i.e. Firefox). 

![image](https://user-images.githubusercontent.com/22973227/62408478-0dbca980-b5ca-11e9-9b23-c7aab7c6ebdd.png)

![image](https://user-images.githubusercontent.com/22973227/62408493-393f9400-b5ca-11e9-98be-75eabf7e1c8f.png)

**Comment by serpro69** [comment]
OK, I think I've figured it out. The buttons will show if I enable "Use system title bar and borders", and if it's disabled then only Close button shows. If this is the correct behavior then this issue can be closed.

**Comment by Deozaan** [comment]
@serpro69 Your screenshot of the tweak tool only shows the close button, whereas @srirambv's shows the min/max buttons as well. This looks like an OS configuration issue to me, not a Brave issue.

**Comment by serpro69** [comment]
@Deozaan Not exactly, I do have those buttons, just look closer :) 
![image](https://user-images.githubusercontent.com/22973227/62443195-83f01600-b75a-11e9-9898-908044b579a2.png)


But as I mentioned in the comment above, the issue seems to be related to "Use system title bar and borders" option of Brave. I do not know if this is the correct behavior though. 

"Use system title bar and borders" is disabled 
![image](https://user-images.githubusercontent.com/22973227/62443290-c9acde80-b75a-11e9-80fa-997046f52cc7.png)

And when it's enabled:
![image](https://user-images.githubusercontent.com/22973227/62443344-f660f600-b75a-11e9-9632-35bcf2d9e704.png)

**Comment by serpro69** [comment]
I think you might be right there :) Closing this issue. Thanks!
