### ISSUE TITLE
Add a verified logo in the tip banner

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#5517]
For inline tipping, there is no way for a tipper who clicks on the logo to know if the receiver is verified (or not). And very few folks read the disclaimer.

Add the verified logo to the tip banner so add some visual symbol of verification -- the tip panel is working great if a user starts there.

Illustration:
![image](https://user-images.githubusercontent.com/35932307/62379153-3c1f8380-b4fb-11e9-86c0-cc09c23085ca.png)

**Comment by mandar-brave** [comment]
@NejcZdovc

**Comment by Brave-Matt** [comment]
@mandar-brave,
Is this method being chosen _over_ the initial method proposed in #4649 ( no offense taken :) ) -- or maybe in tandem? I ask because this particular methodology seems "clunky" UX wise. 

For example, a user scrolling through their Twitter feed wants to Tip another verified user. If the verified logo appears in the tip banner, without #4649 in place as well, the user is _required_ to click the `Tip` and load the banner to learn whether or not the user they want to tip is verified.

**Comment by NejcZdovc** [comment]
@Brave-Matt problem with #4649 is that would mean that we would need to fetch data for every publisher that is displayed on the page and could mean some lagging while scrolling. This is first step that we will do (to have the same UI) and then we will investigate how we can do #4649 performance efficient

**Comment by mandar-brave** [comment]
@Brave-Matt #4659 is what we would prefer; but seems like a lot of heavy weight lifting - a compromise but allows for some symbolism of verification!

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.123 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/3283
* Ensured that connected and verified publishers show the verified icon on the tip banner. 
* Ensured that unverified publishers do not show the verified icon on the tip banner.
* Checked the following types of verified publishers: regular sites, YouTube, Twitter, Twitch, Reddit, Vimeo, Github.
* Ensured verified icon displays if publisher has custom banner images/text
* Ensured verified icon displays if publisher does not have custom banner.

Verified publisher tip banner on Staging:
![Screen Shot 2019-09-04 at 1 58 20 PM](https://user-images.githubusercontent.com/28145373/64280241-b5592e80-cf1e-11e9-94ef-b08b7c307ea9.png)

Connected, not verified publisher tip banner on Staging:
![Screen Shot 2019-09-04 at 1 58 52 PM](https://user-images.githubusercontent.com/28145373/64280251-b8541f00-cf1e-11e9-8a79-dde0fc9d3ae1.png)

Unverified publisher tip banner on Staging:
![Screen Shot 2019-09-04 at 1 59 09 PM](https://user-images.githubusercontent.com/28145373/64280265-bab67900-cf1e-11e9-8580-d6f6fb912e32.png)

Verified publisher tip banner on Prod:
![Screen Shot 2019-09-04 at 2 14 26 PM](https://user-images.githubusercontent.com/28145373/64280272-bd18d300-cf1e-11e9-98a9-b79ed7e54b01.png)

Connected, not verified publisher tip banner on Prod:
![Screen Shot 2019-09-04 at 2 15 05 PM](https://user-images.githubusercontent.com/28145373/64280275-c0ac5a00-cf1e-11e9-9f13-34d61f3807a7.png)

Unverified publisher tip banner on Prod:
![Screen Shot 2019-09-04 at 2 15 23 PM](https://user-images.githubusercontent.com/28145373/64280281-c3a74a80-cf1e-11e9-8a68-0318f7affbff.png)
