### ISSUE TITLE
opened PDFs no longer render after switching to PDFium

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5519]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/3846

If you have PDFs open before updating to 0.68.x, when you open them you basically get an error loading the page because PDFjs is no longer being used to open PDFs.

## Steps to Reproduce

   1. Install build like 0.67.112 on beta (or any build on another channel where PDFjs is being used.
   2. Open at least one PDF.
   3. Update to a version using PDFium (I used 0.68.114 on beta).
   4. Navigate to the PDF you opened.

## Actual result:
PDF doesn't display.
![Screen Shot 2019-08-02 at 10 17 36 AM](https://user-images.githubusercontent.com/28145373/62384251-e4dfda00-b51f-11e9-90e1-5eadebcbdb54.png)

Note - you can just modify the URL to remove the part about the extension, but I don't know that everyone knows that.

## Expected result:
PDF would load using PDFium instead of PDFjs which is no longer available.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.68.114 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? not yet
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? unsure but probably
- Can you reproduce this issue with the nightly channel? unsure but probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
cc @rebron

**Comment by kjozwiak** [comment]
Quick work around if you run into this issue after upgrading to `0.68.x` from `0.67.x`:

* Find tabs that have PDF's opened (most likely failing to refresh/load)
* remove `chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/`
* once the above portion of the URL is removed, the PDF should load correctly

**Comment by rebron** [comment]
wontfix. We'll handle via support.

**Comment by rebron** [comment]
cc: @Brave-Matt
