### ISSUE TITLE
Welcome Page Scroll Bar Appearing

### ISSUE THREAD

**Issue by imptrx** [brave/brave-browser#5520]
## Description 
Welcome page has a scroll bar when animating the footer graphic. 

## Steps to Reproduce

   1. In system preferences => General => Show Scroll Bars => Always
   2. Open brave for the first time or go to `brave://welcome`

## Actual result:

- welcome page is scrollable
- scroll bar is apparent
<img width="764" alt="Screen Shot 2019-08-02 at 10 33 05 AM" src="https://user-images.githubusercontent.com/9125231/62388080-3cc31480-b511-11e9-99ab-e06a4fac0678.png">

## Expected result:
- Scroll bars should always be hidden

## Reproduces how often: 
- Always 

## Miscellaneous Information:
- Scroll bar must be turned on in OS settings

**Comment by GeetaSarvadnya** [comment]
@cezaraugusto Is this specific to macOS?

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Ubuntu 18.04 LTS

Not sure about turning on the scrollbars, but by the scrollbars are not visible on welcome page.

**Comment by cezaraugusto** [comment]
hi @GeetaSarvadnya I updated the test plan
