### ISSUE TITLE
Glitches on canvas

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [brave/brave-browser#5521]
This issue is persistent since brave browsers launch. Websites like soundcloud and other graphic intense websites constantly cause artefacts and flashing geometry on HTC One series.
![Screenshot_2019-08-02-21-10-08](https://user-images.githubusercontent.com/45887282/62393406-517fc680-b56a-11e9-952b-6a44a561d330.png)

**Comment by bsclifton** [comment]
cc: @SergeyZhukovsky @samartnik @AlexeyBarabash

**Comment by AlexeyBarabash** [comment]
Tried on all devices I have: I could see a behavior with graphic artifacts on the old tablet with Android 4.4 , but it was not similar to the screenshots above and the image has been normalized in several seconds. The Chrome acts in the same way on that device. 

@hp8wvvvgnj6asjm7 , can you see the artifacts if you open that site with Chrome?
