### ISSUE TITLE
Brave fails to load https://www.mixcloud.com/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#5523]
## Description 
Create a login for mixcloud, load https://www.mixcloud.com/ This will lock up the browser if Sheilds is enabled.  Was reported here; https://github.com/brave/brave-browser/issues/4155

## Steps to Reproduce

   1. Sign in the Mixcloud
   2. load www.mixcloud.com

## Actual result:

![mixcloud](https://user-images.githubusercontent.com/1659004/62403700-487f0b80-b5e3-11e9-81ff-6fafe1cfce93.png)

## Expected result:

Load Website without issues.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Tested in Brave Release and Nightly.

## Other Additional Information:

If ubo is enabled, with the following filter;

`||googletagservices.com/tag/js/gpt.js`

It'll let the site render correctly. We have disconnect already blocking googletagservices.com but its not showing up on mixcloud blocked items list.

**Comment by Brave-Matt** [comment]
+1 from Twitter:
https://twitter.com/thenicomsd/status/1157411550673690625

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/mixcloud-not-loading-slow-to-respond/63069

**Comment by Brave-Matt** [comment]
+1:
https://community.brave.com/t/mixcloud-page-doesnt-load/53940

**Comment by Brave-Matt** [comment]
+1:
https://community.brave.com/t/mixcloud-never-finishes-loading/40474

**Comment by rebron** [comment]
@ryanbr Would an explicit block option help here?

**Comment by ryanbr** [comment]
I'm not sure whats going on, page seems to lock up when sheilds is enabled. And if I whitelist the 2 scripts being listed, it doesn't help. The other strange thing, it works okay when UBO is enabled.

**Comment by ryanbr** [comment]
Still an issue. I'm trying to reach out to the site. But I'm gathering its more related to anti-adblock on the site.

**Comment by kjozwiak** [comment]
Still reproducible using `1.1.20 Chromium: 79.0.3945.74`. Looks like it eventually recovers if you leave it opened for ~2-3minutes. However, as the above report states, it locks up/slows down the browser when initially loading the page.

Looks like the website loads about 2.1GB worth of data when initially loading. Maybe it's the reason the page starts locking up?

<img width="377" alt="Screen Shot 2019-12-12 at 12 32 41 AM" src="https://user-images.githubusercontent.com/2602313/70685357-207d7400-1c77-11ea-8008-f6ba0ebd4fb8.png">

**Comment by ryanbr** [comment]
Testing

`https://www.mixcloud.com/evil_concussion/skrillex-owsla-big-beat-records-fuji-rock-festival-2%C3%9F18-naeba-ski-resort-yuzawa-28072018/`

`https://www.mixcloud.com/discover/skrillex-nero/` 

Seems they've fixed it.  Reaching out to the community.

**Comment by ryanbr** [comment]
Seems to be resolved @kjozwiak , might've been a serverside change, unsure to be honest.

**Comment by ryanbr** [comment]
Closing, site was redesigned, and re-checked. everything is working,.

**Comment by cameronroe** [comment]
I'm having issues loading any mix on MixCloud in Brave. It's not working for me.

Currently running `[Version 1.45.118 Chromium: 107.0.5304.91 (Official Build) (arm64)](https://brave.com/latest/)`

![image](https://user-images.githubusercontent.com/1614348/200168658-28a7030b-4d0d-4d69-8e00-b1f69ff5ecef.png)

<img width="1429" alt="Screen Shot 2022-11-06 at 1 47 01 PM" src="https://user-images.githubusercontent.com/1614348/200168715-c6910280-7f86-429b-8e12-99baa646125f.png">

**Comment by ryanbr** [comment]
Should create a new report @cameronroe   But I took a quick look, with default shields, no extensions.  No issues with playback/seek of: https://www.mixcloud.com/deadmau5/deadmau5-presents-mau5trap-radio-213/    

https://gif.fanboy.co.nz/gif/mixcloud-brave.gif

Re-test in private window mode, disable any extensions or vpn's also.
