### ISSUE TITLE
No publisher is showing as verified

### ISSUE THREAD

**Issue by cndouglas** [brave/brave-browser#5525]
## Description 
Verified publishers are not showing as verified in the Brave Rewards panel.

## Steps to Reproduce
   1. Start Brave with a fresh profile
   2. Go to brave.com
   3. Open the Brave Rewards panel
   4. Click Join Rewards

## Actual result:
brave.com shows as not verified (I'm pretty sure Brave's own website is a verified publisher):
![](https://user-images.githubusercontent.com/19424103/62404529-9bf94700-b55a-11e9-83ab-54af1982d7d4.png)

## Expected result:
The website should show that it is verified.

## Reproduces how often: 
Always

## Brave version (brave://version info)
Brave | 0.70.22 Chromium: 76.0.3809.87 (Official Build) nightly (64-bit)
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

## Version/Channel Information:
- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Not applicable
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? Not applicable

## Miscellaneous Information:

**Comment by bsclifton** [comment]
Thanks for the report 😄 This is expected with recent changes we did

Publisher properties will only show as verified if the publisher has setup an Uphold account and gone through the verification process (the KYC/know your customer process). In this case, we didn't do that yet for brave.com (whoops!). I've notified the appropriate people who will get that sorted out 😄

**Comment by infoxvvids** [comment]
> Thanks for the report  This is expected with recent changes we did
> 
> Publisher properties will only show as verified if the publisher has setup an Uphold account and gone through the verification process (the KYC/know your customer process). In this case, we didn't do that yet for brave.com (whoops!). I've notified the appropriate people who will get that sorted out

It seems not true, at lest for me. I have a Verified Uphold account AND only some of my Channel Are "Not Yet Verified" since 1 August in the Brave panel
For instance xanyvids.net is Verified (on Brave Release and Brave Dev) Twitter account Maharetrh_73 is Verified on Brave Release but Not Yet verified on Brave Dev and so on
Cheers
Daniela
