### ISSUE TITLE
Old Reddit tipping not showing up

### ISSUE THREAD

**Issue by RetroCraft** [brave/brave-browser#5527]
## Description 
The current logic for deciding whether we're on old or redesigned Reddit is by using the url (old.reddit.com vs www.reddit.com). However, if you opt out of the redesign through personal preferences, you have old Reddit on the www subdomain. Tipping does not show up.

## Steps to Reproduce

   1. Sign in to Reddit
   2. Opt out of the redesign if not done already by going to Settings > Accounts > Beta tests > Opt out of the redesign
   3. Observe that there are no more tipping buttons

## Actual result:

![2019-08-03_15-02-32](https://user-images.githubusercontent.com/6295913/62415928-f698ae80-b5ff-11e9-8df8-3aab765bd4cb.gif)

## Expected result:
Like on old.reddit.com, the tipping button shows up.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.69.98 Chromium: 76.0.3809.87 (Official Build) dev (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Windows 10 OS Version 1809 (Build 17763.615)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? ...
- Is the issue reproducible on the latest version of Chrome? Not applicable

**Comment by Brave-Matt** [comment]
+1 https://www.reddit.com/r/brave_browser/comments/d52h23/cant_tip_on_reddit_old_design/

**Comment by NejcZdovc** [comment]
@alexwykoff should we handle this use case?

**Comment by Miyayes** [comment]
File anew if this is still an issue.
