### ISSUE TITLE
Chinese characters in tabs shown as squares / rectangles?

### ISSUE THREAD

**Issue by ehouarn-perret** [brave/brave-browser#5529]
## Description 
When running Brave in Linux, Chinese characters **in tabs** are rendered as squares / rectangles (the content of the page is fine even if contains Chinese characters).

Also it seems that even if the tab does not show the Chinese characters properly, the window title related to the current tab shows the Chinese characters properly in the menu bar in my OS.

It's worth noting that this is just applicable to tabs, I've noticed the same issue in chrome-like browser: Google Chrome, Opera and Brave. It's fine in Vivaldi and Firefox.

My OS (Manjaro / XFCE variant) has support for Chinese fonts and input (even have Chinese names for files and folders).

## Steps to Reproduce

   1. Open Brave in Linux
   2. Go to https://www.douban.com/
   3. Check out the tab

## Actual result:

![image](https://user-images.githubusercontent.com/11332444/62416739-7a728b00-b640-11e9-982e-2b6abc796689.png)

## Expected result:
Something more like Firefox:

![image](https://user-images.githubusercontent.com/11332444/62416764-f4a30f80-b640-11e9-994c-61978bb489cb.png)

## Reproduces how often: 
Systematically

## Brave version (brave://version info)
Version 0.67.119 Chromium: 76.0.3809.72 (Official Build) unknown (64-bit)

**Comment by Goran00** [comment]
You have to install adobe-source-han-sans-jp-fonts or  adobe-source-han-sans-otc-fonts and problem solved

**Comment by ehouarn-perret** [comment]
Alright will try this out, thanks!

**Comment by ehouarn-perret** [comment]
Works like a charm! Thanks!
I close the issue.

**Comment by SteveBetter** [comment]
what happened to the Chinese Fonts in Brave recently? (1.57.53 in use currently, maybe introduced two versions earlier) It is displayed in Japanese type. After changing settings to use the Noto CJK SC Font explicitly, the problem remains in the title bar and website box. Can Brave just follow ubuntu system setting, which is solved by put Noto CJK SC ahead of Noto CJK JP in /etc/fonts/conf.d/64-language-selector-prefer.conf.

![Screenshot from 2023-08-25 15-21-35](https://github.com/brave/brave-browser/assets/22906431/308718a2-e62c-460c-898d-ad548bc87adb)
![Screenshot from 2023-08-25 15-24-53](https://github.com/brave/brave-browser/assets/22906431/82853e3e-150e-4624-9a65-55b0b463ef3c)
![Screenshot from 2023-08-25 15-39-10](https://github.com/brave/brave-browser/assets/22906431/61a35cfb-9680-46e4-a696-01fe306e3dc1)
