### ISSUE TITLE
Follow up to there is no ads enable alert, ads are enabled by default when upgrading build from 0.62.51 to 0.67.119

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#5531]
## Description 

There is no ads enable alert, ads are enabled by default when upgrading build from 0.62.51 to 0.67.119

## Steps to Reproduce

Pre-requisites: VPN is connected to US region and language is set to English(US)
   1. clean profile 0.62.51
   2. enable rewards
   3. upgrade to 0.67.119

## Actual result:

There is no ads enable alert, ads are enabled by default when upgrading build from 0.62.51 to 0.67.119

## Expected result:

Ads enable alert should be shown on BAT logo and ads should not be enabled by default

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.67.119 Chromium: 76.0.3809.72 (Official Build) (64-bit)
-- | --
Revision | 5a04c669126f657f98824b436555cae41b8f4146-refs/branch-heads/3809@{#897}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @tmancey 
Also see https://github.com/brave/brave-browser/issues/5434

**Comment by GeetaSarvadnya** [comment]
Blocked due to https://github.com/brave/brave-browser/issues/6148

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

* Test cases listed in https://github.com/brave/brave-browser/issues/5434#issuecomment-537287155 cover the Ads enable alert
* Logged follow up issue https://github.com/brave/brave-browser/issues/6270 for some unexpected enable ads alerts.
