### ISSUE TITLE
Website looks bad since last update today

### ISSUE THREAD

**Issue by Riggie1000** [brave/brave-browser#5532]
## Description 
Hello.
Since last update today (2019/08/05) I have a website that has now a bad looking. It looks like one site (febbit.com/miner) is scrolled down so the upside is out of the window, but there is no scrolling on that site. I think it's because of an ad upside, that is blocked by the shield, but deblocking doesn't put the site to the old look.

## Steps to Reproduce

   1. open febbit.com
   2. sign in to that game with google
   3. go to febbit.com/miner

## Actual result:
https://drive.google.com/file/d/1lt1xURebgsXb0FVhV7_P-iAYqddDvmZB/view?usp=sharing

## Expected result:
This is from chrome.
https://drive.google.com/file/d/1bjN3aDyWO051-hXJyg2uzqapKSKLypdW/view?usp=sharing

## Reproduces how often: 
everytime

## Brave version (brave://version info)
Version 0.67.123 Chromium: 76.0.3809.87 (official build) (64-Bit)
Windows 10 Enterprise 1903

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

## Miscellaneous Information:

I noticed this issue immediately after last update.

**Comment by fishmi** [comment]
I have a similar problem:
After the update the following page doesn't render correctly (the box "Nützliches für den Alltag" is usually on the far right):
https://www.datev.de/fanshop/
In all other browsers, including the latest version of Chrome (Version 76.0.3809.87, 64-Bit), the page is displayed correctly.

**Comment by Riggie1000** [comment]
>(the box "Nützliches für den Alltag" is usually on the far right):
> https://www.datev.de/fanshop/
> In all other browsers, including the latest version of Chrome (Version 76.0.3809.87, 64-Bit), the page is displayed correctly.

Yes, confirmed. "Kinder" also.

**Comment by fishmi** [comment]
Not "Kinder" but "Nützliches für die Kanzlei" (behind "Kinder")

**Comment by ryanbr** [comment]
Whats the issue here? screen shot of comparison between Chrome and Brave?

**Comment by Riggie1000** [comment]
> Whats the issue here? screen shot of comparison between Chrome and Brave?

In Brave is a big fat black space on the bottom. There should be none. When you look at the clouds, you should expect, that the site is scrolled down, but there is no scrollbar. Yes the website works. No, the website doesn't look good.

**Comment by fishmi** [comment]
![brave](https://user-images.githubusercontent.com/105578/63017636-23b64e00-be97-11e9-9f2c-e8682935bb5e.png)
![chrome](https://user-images.githubusercontent.com/105578/63017638-23b64e00-be97-11e9-8c11-712bc0d485aa.png)

**Comment by fishmi** [comment]
Two, different problems

**Comment by ryanbr** [comment]
Brave on the left, Chrome on the right. Struggling to see a difference between the two

![datev](https://user-images.githubusercontent.com/1659004/63050577-8d823680-bf2f-11e9-93f9-0a2630defb0d.png)

**Comment by fishmi** [comment]
Well, I guess that's a problem that only shows up with me, for whatever reason. In any case, nothing looks correct with me.
But if this cannot be reproduced, then it will probably not be solved. Too bad, Brave should become my standard browser. Then I have to look further.

**Comment by fishmi** [comment]
Brave on the left, Chrome on the right. It's not so hard to see the difference :-)

![screenshot_20190814_214814](https://user-images.githubusercontent.com/105578/63051305-48351900-bedd-11e9-9996-72a817f6fb6c.png)

**Comment by fishmi** [comment]
![image](https://user-images.githubusercontent.com/105578/63051432-83cfe300-bedd-11e9-9786-cf1e20b87b03.png)

This screenshot was not edited either :-)

**Comment by fishmi** [comment]
![image](https://user-images.githubusercontent.com/105578/63052066-c2b26880-bede-11e9-8af0-d168386affb4.png)

Unfortunately no current Windows update, my computer refuses this stubbornly.

**Comment by Riggie1000** [comment]
Brave:
[https://drive.google.com/file/d/1IEz_972OuX7LmnRV1jGvYTuRdFHF7LzQ/view?usp=sharing](url)

Chrome:
[https://drive.google.com/file/d/15Ruk5af6aYf2QxG-_sKTioE1e5Wmckf6/view?usp=sharing](url)

[https://drive.google.com/file/d/1OuUrDOSj-BJYUG6TiCsQQ9zDaXc05osy/view?usp=sharing](url)

[https://drive.google.com/file/d/1RFKeIPbzSoWkrLlgmQi9jNXBHOdNjBpP/view?usp=sharing](url)

[https://drive.google.com/file/d/1JK-TXlw34GOxYKOaKUgPtAn3FabkvSBk/view?usp=sharing](url)

**Comment by Riggie1000** [comment]
Brave:
![Brave](https://user-images.githubusercontent.com/33362740/63052804-9ac40480-bee0-11e9-83b6-1cbc7e698632.JPG)

Chrome:
![Chrome](https://user-images.githubusercontent.com/33362740/63052822-a31c3f80-bee0-11e9-9263-1732c27e941f.JPG)

![Brave version](https://user-images.githubusercontent.com/33362740/63052836-a7485d00-bee0-11e9-8f0e-aabf3880b9fc.JPG)

![Chrome version](https://user-images.githubusercontent.com/33362740/63052844-ab747a80-bee0-11e9-85b1-42386a076de9.JPG)

![Windows](https://user-images.githubusercontent.com/33362740/63052871-b3341f00-bee0-11e9-9a4f-32f39b235e0e.JPG)

**Comment by ryanbr** [comment]
It could be a possibility that the ads elements extend the page out, so when we block them it'll collapse the ad elements making the screen/div smaller. If you use uBo + Chrome, does it do the same thing?

**Comment by Riggie1000** [comment]
What is uBo? Is it an extension in Chrome? Do u mean uBlock Origin? I tried and now here is the result:

Chrome + uBlock
![Chrome uBlock](https://user-images.githubusercontent.com/33362740/63175780-058e5080-c045-11e9-95af-dd15c3c14cdc.JPG)

Brave + uBlock
![Brave with uBlock without Shield](https://user-images.githubusercontent.com/33362740/63175809-12ab3f80-c045-11e9-8550-e30229e27384.JPG)

Brave + uBlock + Shield
![Brave with Shield + uBlock](https://user-images.githubusercontent.com/33362740/63175855-222a8880-c045-11e9-87f9-b92f274c55b5.JPG)

No matter to the rock. It's ingame.

A closer look shows up, that there is no dirt in Brave, but bushes.

**Comment by Riggie1000** [comment]
What I can say, is, that sometimes also in Chrome there are less ads. There are a max of 2 ads on the sides and one upside as you can see in my first post.

**Comment by rebron** [comment]
@Riggie1000 @ryanbr with shields down, are we rendering the same as Chrome?

**Comment by Riggie1000** [comment]
As I said before and as you can see on my 5 pics above, there is no difference between shields up or down. Yes, with shields no ads, but the background is not nice as with shields down.

**Comment by ryanbr** [comment]
@fishmi   seems everything is fixed now? regarding https://www.datev.de/fanshop/

@Riggie1000   Unable to login/test on https://febbit.com/ . Site seems to have issues/or just down according to the cloudflare errors.

**Comment by ryanbr** [comment]
Closing ticket, `https://www.datev.de/fanshop/`  now works, we can re-open if there is an issue that I haven't picked up.
