### ISSUE TITLE
Display Channel Type During Tipping Banner Customization

### ISSUE THREAD

**Issue by Deozaan** [brave/brave-browser#5535]
## Description 

I'm trying to have a custom tipping banner for each of my various linked channels, but I can't tell which one I'm editing because the tipping banner just shows `✅ Deozaan` on each of them. This is not helpful. I can't tell if I am editing my `Github` or `Twitter` or `Twitch` or `YouTube` channel, etc., which all have the same username.

## Steps to Reproduce

   1. Link various channels that all have the same username.
   2. Try to customize the tipping banner individually for each of them. I.e., disable `Same banner content for all channels` option.
   3. Be confused as to which channel the banner you're currently editing is for.

## Actual result:

No website name is listed to let the creator know which specific channel/site the banner currently being edited is for.

## Expected result:

When editing the banner content, in the place where it shows the checkmark and the name of the channel it also needs to display which site the banner being edited belongs to.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

```
Brave | 0.67.123 Chromium: 76.0.3809.87 (Official Build) (64-bit)
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Windows 10 OS Version 1903 (Build 18362.267)
```

## Temporary Workarounds

1. For new users who haven't linked a bunch of channels yet, it would be wise to add a channel and then immediately customize it before adding any others, and repeat this for each additional linked channel. This way the custom text and images should provide the clues necessary to distinguish which site each banner is for.
2. Another option for those who already have various channels linked is to make a note of the order in which each channel is listed on your dashboard. That's the order they will cycle through, starting from the top and going down the list.

**Comment by NejcZdovc** [comment]
moved to correct repo https://github.com/brave-intl/publishers/issues/2161
