### ISSUE TITLE
Allow Creators to Reorder Linked Channels

### ISSUE THREAD

**Issue by Deozaan** [brave/brave-browser#5536]
## Description 

I linked my more popular channels first, and as Brave has added more and more sites that can be linked, I've added those as well. Many of the new ones I've added don't get much traffic and thus don't get any rewards.

Now I must scroll down the page to the bottom of the list to see pending payouts to my most popular linked channels.

It would be nice if the list of linked channels was or could be sorted somehow differently. My preference is to either by allow creators to manually rearrange the channels, or to sort by the greatest amount of pending payouts at the top.

## Steps to Reproduce

   1. Link multiple channels, starting with most popular ones (which earn more rewards monthly) first.
   2. Add more, less popular (lower or no monthly rewards) channels last.
   3. Frown at all the  `0.00 BAT` payouts on the screen until you scroll down to see the more popular channels with `> 0 BAT` pending payouts.

## Actual result:

Channels are currently sorted in order they were added, with the most recently added channels at the top.

## Expected result:

Almost any other method of sorting would be preferable.

## Reproduces how often: 

Easily reproduced. 

## Brave version (brave://version info)

```
Brave | 0.67.123 Chromium: 76.0.3809.87 (Official Build) (64-bit)
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Windows 10 OS Version 1903 (Build 18362.267)
```

**Comment by NejcZdovc** [comment]
moved to correct repo https://github.com/brave-intl/publishers/issues/2160
