### ISSUE TITLE
Add nsp check as a pre-push hook

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#554]
- [ ] brave-browser
- [ ] brave-core
- [ ] ad-block
- [ ] brave-extension
- [ ] tracking-protection

**Comment by mbacchi** [comment]
For reference: https://nodesecurity.io/

**Comment by diracdeltas** [comment]
this should be npm audit, not nsp check.

since this would be fixed by https://github.com/brave/brave-browser/pull/1854, going to close in favor of https://github.com/brave/brave-browser/issues/1853
