### ISSUE TITLE
Add link to 'Get more extensions' in Settings

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#5540]
## Test plan
See https://github.com/brave/brave-core/pull/3166

## Description 
Create a new line directly under Manage extensions in brave://settings/extensions to give users another access point to get extensions.

Should read:
Get more extensions
Open Web Store [with icon showing external link]

Link should point to: 
https://chrome.google.com/webstore/category/extensions?hl=en

See below for an example
<img width="656" alt="Screen Shot 2019-08-05 at 10 27 11 PM" src="https://user-images.githubusercontent.com/5951041/62468313-b89eb480-b7d0-11e9-9f65-da130ae101da.png">

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.113 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/3166
![image](https://user-images.githubusercontent.com/38657976/63503080-71146a00-c4ec-11e9-8dbb-c4c9f7d4277c.png)
