### ISSUE TITLE
User earns rewards while native macOS notifications are suppressed

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#5541]
## Description 

When notifications are disabled for the browser, ad notifications still register as having been displayed and the user is able to earn BAT in spite of never having seen a notification or ad.

## Steps to Reproduce

   1. Enable Brave Rewards and Ads
   2. Visit _System Preferences > Notifications_  in macOS Settings
   3. Disable notifications for Brave

## Actual result:

The browser believes it is showing ad notifications from time to time.

## Expected result:
The browser ceases to show notifications, or is aware that they aren't visible.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

0.70.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/BATProject/comments/d10w4g/brave_bug_on_macos/

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/BATProject/comments/dgh2md/macos_catalina_receiving_rewards_but_no/ Catalina

**Comment by tmancey** [comment]
Resolved by https://github.com/brave/brave-browser/issues/3651

**Comment by tmancey** [comment]
Reopening issue as #3651 did not resolve the issue as we need to wait until chromium notifications are transitioned to UNUserNotificationCenter

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/BATProject/comments/f4a4eg/im_getting_bat_without_seeing_ads/

**Comment by tmancey** [comment]
Blocked until https://github.com/brave/brave-browser/issues/9592 is implemented or until Chromium macOS notifications use the new Apple APIs

**Comment by tmancey** [comment]
Closing issue as superseded by https://github.com/brave/brave-browser/issues/9592
