### ISSUE TITLE
Rewards : User Wallets - Verified wallet visual indicator is causing confusion versus verified publishers

### ISSUE THREAD

**Issue by alexwykoff** [brave/brave-browser#5543]
## Description 
As noted internally, there is a visual conflict between the verified indicator for a user wallet versus the verified indicator for a publisher in the BAT panel.

## Steps to Reproduce

   1.  Verify your user wallet
   2.  Open the BAT panel

## Actual result:
<img width="396" alt="Screen Shot 2019-08-05 at 9 04 11 AM" src="https://user-images.githubusercontent.com/1434040/62479744-bf4b0e80-b773-11e9-8efc-f856b7d95bef.png">

## Expected result:
There should not be confusion between a verified user wallet and a verified publisher.

## Reproduces how often: 
N/A

## Brave version (brave://version info)
 0.70.34

## Version/Channel Information:
Only occurs on Nightly currently, but will follow train as user wallets move.

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
N/A

**Comment by bradleyrichter** [comment]
@petemill  The design solution is as follows:

![image](https://user-images.githubusercontent.com/13509546/64985777-81fd9480-d87a-11e9-8918-f7c94b40e346.png)

Wallet Verified button style should be changed to a clear background.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

-  Verified the test plan from https://github.com/brave/brave-core/pull/3458
- The connected verified wallet is no longer green but has a transparent background, verified both panel and rewards settings page
![image](https://user-images.githubusercontent.com/38657976/65628835-e0034800-dfef-11e9-9f6d-b6f8e72dfd94.png)

- The connected unverified wallet doesn't have (?) next `Verify Wallet` ad mentioned in https://github.com/brave/brave-browser/issues/5543#issuecomment-531915625
![image](https://user-images.githubusercontent.com/38657976/65629276-ab43c080-dff0-11e9-834f-9986f56fe518.png)
