### ISSUE TITLE
Follow up - Shields Panel and Rewards Panel are not translated to Norwegian on Windows

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#5546]
Follow up to https://github.com/brave/brave-browser/issues/3425
Still reproducible on Windows. Works on MacOS.

## Steps to Reproduce

   1. Change Brave language to `Norwegian` 
   2. Open Brave Shields
   3. Open Rewards Panel

## Actual result:

Shields panel is not translated
![image](https://user-images.githubusercontent.com/34715963/62498626-28686b80-b7e0-11e9-8e4f-1bca754c03ca.png)

Rewards Panel is not translated:
![image](https://user-images.githubusercontent.com/34715963/62498635-2ef6e300-b7e0-11e9-9891-e9427967d520.png)

## Expected result:
Shields panel is translated
Rewards Panel is translated:

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.68.118 Chromium: 76.0.3809.87 (Offisiell delversjon) beta (64-bit)
-- | --
Versjon | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

Brave | 0.70.36 Chromium: 76.0.3809.87 (Offisiell delversjon) nightly (64-bit)
-- | --
Versjon | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

cc @brave/legacy_qa @mkarolin @bsclifton

**Comment by rebron** [comment]
@btlechowski Can you take a look? Is this already fixed?

**Comment by btlechowski** [comment]
Still reproducible on all channels


Brave | 0.69.130 Chromium: 77.0.3865.90 (Offisiell delversjon) (64-bit)
-- | --
Versjon | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 7 Service Pack 1 (Build 7601.24519)



Brave | 0.70.104 Chromium: 77.0.3865.90 (Offisiell delversjon) beta (64-bit)
-- | --
Versjon | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 7 Service Pack 1 (Build 7601.24519)

Brave | 0.71.74 Chromium: 77.0.3865.75 (Official Build) dev (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 7 Service Pack 1 (Build 7601.24519)

Brave | 0.72.62 Chromium: 77.0.3865.90 (Official Build) nightly (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 7 Service Pack 1 (Build 7601.24519)



![image](https://user-images.githubusercontent.com/34715963/65999614-0b79ad00-e49e-11e9-8cc7-a18ab687246c.png)
![image](https://user-images.githubusercontent.com/34715963/65999712-3f54d280-e49e-11e9-9b60-bd40cb496e5a.png)
![image](https://user-images.githubusercontent.com/34715963/65999830-8216aa80-e49e-11e9-9e56-215fd456f5c6.png)
![image](https://user-images.githubusercontent.com/34715963/65999865-8e026c80-e49e-11e9-846e-f2c36105b058.png)

**Comment by bsclifton** [comment]
@mkarolin @atsyed87 is there a way to verify that we DO have translations for Norwegian on desktop (in Transifex)? Maybe there's a bug with pulling them? I'd have to think we've gotten some by now

**Comment by atsyed87** [comment]
Yes, we definitely have Norwegian translations present in Transifex. Not
sure what else could be going wrong.

https://www.transifex.com/brave/brave/language/no/

**Comment by mkarolin** [comment]
As far as I recall, we have proper localization for the browser chrome and webUI, but not for the Shields/Rewards extensions, so this is likely to do with how the JS side requests strings for the given locale. 
The strings come down from Transifext as locale 'no' and we rename it to 'nb' when we package resources (see components/brave_extension/extension/brave_extension/BUILD.gn and components/brave_rewards/resources/extension/BUILD.gn). 
It would be useful to check what locale is being specified when strings are requested from the extensions.

**Comment by btlechowski** [comment]
No longer reproducible

Brave | 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

![image](https://user-images.githubusercontent.com/34715963/75441664-5c62d400-595e-11ea-86a3-858fedfac7da.png)
![image](https://user-images.githubusercontent.com/34715963/75441773-8ae0af00-595e-11ea-96a8-3091ce82eeb8.png)
