### ISSUE TITLE
Client needs to create private address for user wallets

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#5547]
We should add private address to claim user funds call. If private address is not created we need to create it and hit claim api even if user funds is 0.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/3329
