### ISSUE TITLE
panel is broken for twitch - unable to tip twitch publishers

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5549]
## Description 
This has happened before, see https://github.com/brave/brave-browser/issues/4680

When visiting a twitch channel and clicking on the BAT logo, the panel shows twitch.com, not the publisher information, so you are unable to tip twitch publishers.

## Steps to Reproduce

1. Clean profile with 0.67.x release or 0.68.x beta
2. Enable Rewards
3. Visit twitch channel page (ex. twitch.tv/bobross)
4. Click on BAT logo after page is fully loaded --> panel shows twitch.tv, not BobRoss on Twitch. Try a few more times, same result.
5. Watch a video. During video click on BAT logo. --> panel shows twitch.tv, not BobRoss on Twitch. Try a few more times, same result.

## Actual result:
Panel shows twitch.com, not something like BobRoss on Twitch
![twitchpanel](https://user-images.githubusercontent.com/28145373/62545462-bd468580-b82f-11e9-987d-158c28cb181c.gif)

## Expected result:
Panel should show publisher info (including favicon IF publisher is verified)

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.67.123 Chromium: 76.0.3809.87 (Official Build) (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

Brave | 0.68.119 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

Brave | 0.69.99 Chromium: 76.0.3809.87 (Official Build) dev (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? unsure but probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @NejcZdovc @alexwykoff @mandar-brave @rebron @brave/legacy_qa

**Comment by btlechowski** [comment]
Reproduced on Windows

Brave | 0.67.123 Chromium: 76.0.3809.87 (Official Build) (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

https://www.twitch.tv/toyzttv

![image](https://user-images.githubusercontent.com/34715963/62546967-bdad4380-b864-11e9-8d83-18e1978beede.png)

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/BATProject/comments/cnoa8c/twitch_account_not_showing_as_verified/

**Comment by edsonayllon** [comment]
https://community.brave.com/t/brave-wallet-does-not-recognize-twitch-channels/74936

**Comment by mandar-brave** [comment]
Moving up the stack; below the 0.69 needs but should fix right after.
@alexwykoff

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.123 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/3295
* Ensured information displayed for verified, connected, and non-verified publishers (using prod env only).
* Encountered https://github.com/brave/brave-browser/issues/5848 for the verified icon on the BAT logo - it only displays once you open the panel. Also encountered https://github.com/brave/brave-browser/issues/3330#issuecomment-526723875 for favicon - verified pubs are showing the generic Twitch favicon on panel, AC, tips, etc.

Panel for Verified Twitch Publisher:
![Screen Shot 2019-09-04 at 5 36 35 PM](https://user-images.githubusercontent.com/28145373/64294441-d4ff4f80-cf3c-11e9-8cb8-3df3525350ea.png)

Panel for Connected, not verified Twitch Publisher:
![Screen Shot 2019-09-04 at 5 42 24 PM](https://user-images.githubusercontent.com/28145373/64294432-d0d33200-cf3c-11e9-83b2-093d888f7a85.png)

Panel for unverified Twitch Publisher:
![Screen Shot 2019-09-04 at 5 35 17 PM](https://user-images.githubusercontent.com/28145373/64294446-d761a980-cf3c-11e9-80fa-cf08ee3fea22.png)
