### ISSUE TITLE
Password not saved for SeedboxWS with Brave password manager

### ISSUE THREAD

**Issue by Bundesderick** [brave/brave-browser#555]
Did you search for similar issues before submitting this one?
Yes

Describe the issue you encountered:
User reported password is not saved for https://s51.rutorrent.seedboxws.com/ with Brave password manager

Expected behavior:
Should save id/password with default builtin password manager

Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

Brave Version:
Brave | 0.23.31
V8 | 6.7.288.46
rev | 3148ace
Muon | 7.1.5
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.103

Steps to reproduce:

Visit https://s51.rutorrent.seedboxws.com/
Set Brave password manager in security
Login with valid credentials, Doesn't offer to store password
Screenshot if needed: https://imgur.com/a/YRTVFfO

Any related issues:
None
![2018-07-14 11_33_01-window](https://user-images.githubusercontent.com/41230986/42723205-0f9bc21c-875a-11e8-9c68-645e3244eb6a.jpg)

**Comment by bsclifton** [comment]
Thanks for the report, @Bundesderick - this repository is for the new (unreleased) version of the Brave browser. I went ahead and created an issue for you for our live Muon based product (browser-laptop):
https://github.com/brave/browser-laptop/issues/14802
