### ISSUE TITLE
disabling content level tips for Reddit doesn't remove tip button from in-line menu until page refresh

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5551]
## Description 
When you disable content-level tips for Twitter, after a few seconds the tip button is removed from the in-line menu. If you do this for Reddit, the tip button doesn't go away until you refresh the page.

## Steps to Reproduce

   1. Clean profile
   2. Enable Rewards
   3. Visit reddit
   4. See tip button in the in-line menu.
   5. Open brave://rewards in a new tab and disable content level tips for Reddit.
   6. Go back to reddit page and wait. In-line tip button is never removed.
   7. Refresh page. Now in-line tip button is removed.
   8. Go back to brave://rewards and enable content level tips for Reddit.
   9. Go back to reddit page and wait. In-line tip button appears after a few seconds.
   10. Also occurs on old.reddit.com.

This works as expected for Twitter content level tips.

## Actual result:
Need to refresh Reddit to remove content level tips after they are disabled.
![disblereddittips](https://user-images.githubusercontent.com/28145373/62552137-25e72f80-b83b-11e9-9b24-76c05efa2fcd.gif)

## Expected result:
Should behave as Twitter does (no need to refresh page):
![disabletwittertips](https://user-images.githubusercontent.com/28145373/62552165-30092e00-b83b-11e9-960b-c8a7d6b29beb.gif)

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.68.119 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

Brave | 0.69.99 Chromium: 76.0.3809.87 (Official Build) dev (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? unsure but probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

**Comment by hmert** [comment]
I've same issue.

**Comment by Miyayes** [comment]
I'm surprised the tip buttons disappear after a page refresh. Historically, a browser restart was required to get the setting to actually take effect. Perhaps that has changed?

**Comment by Miyayes** [comment]
It now prompts for browser restart.
