### ISSUE TITLE
reorder items in the App menu

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#5552]
## Description 
App menu should be ordered like the following:
- Brave Rewards
- History ->
- Bookmarks ->
- Downloads
- Crypto Wallets [new]
- Extensions [pulled out from More Tools sub-menu]
- Sync
- Brave Ad Block [for now and may move into Settings in the future]

## Design
<img width="754" alt="Screen Shot 2019-08-07 at 3 57 12 AM" src="https://user-images.githubusercontent.com/5951041/62568116-82902c00-b8c7-11e9-931f-ec846836331f.png">

**Comment by rebron** [comment]
For now, pull 'Extensions' out of sub-menu, use 'Extensions' label and place under Crypto Wallets per the screenshot.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.4.66 Chromium: 79.0.3945.130 (Official Build) dev (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

* Verified Normal Window
<img width="1196" alt="5552-NormalWindow" src="https://user-images.githubusercontent.com/28145373/72934328-6414d480-3d31-11ea-9d18-501a86b04597.png">

* Verified Private Window
<img width="1194" alt="5552-PrivateWindow" src="https://user-images.githubusercontent.com/28145373/72934333-68d98880-3d31-11ea-938b-a2c810492b2a.png">

* Verified Tor Window
<img width="1196" alt="5552-TorWindow" src="https://user-images.githubusercontent.com/28145373/72934341-6d05a600-3d31-11ea-90f0-f337a640d0c2.png">

* Verified Guest Window
<img width="1194" alt="5552-GuestWindow" src="https://user-images.githubusercontent.com/28145373/72934354-70992d00-3d31-11ea-8438-689088ae0d23.png">
