### ISSUE TITLE
No video playback on Mixer.com in brave browser

### ISSUE THREAD

**Issue by jrizz43** [brave/brave-browser#5553]
## Description 

When loading a channel on mixer.com (mixer.com/ninja for example) the video playback does not work. Still screen.

## Steps to Reproduce

   1. Go to mixer.com/ninja
   2. Issue is apparent
   3. 

## Actual result:

No video playback

## Expected result:
Video stream playback

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Version 0.67.123 Chromium: 76.0.3809.87

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@jrizz43 Does this happen with Shields down?
cc: @ryanbr

**Comment by ryanbr** [comment]
I had no issues here; 

https://secure.fanboy.co.nz/gif/mixer.gif

**Comment by ryanbr** [comment]
Closing this, re-check in Brave Release (1.4.96) and Brave Nightly (Version 1.7.50). Working as tested in August. Re-comment if its still a problem @jrizz43
