### ISSUE TITLE
Open profile manager causes entire browser UI to go dark

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5557]
## Description 

Open profile manager causes entire browser UI to go dark

## Steps to Reproduce

   1. Upgrade to 0.70.34
   2. Set Brave colour to light, On Linux set theme to use classic
   3. Open Manage people from profile manager, entire webui goes Dark 
   4. Close manage people and launch again, no change
Note: This only happens the first time you try after browser launch and is reproducible each time after the browser is launched.
## Actual result:

https://youtu.be/RzhdOvTW2wk

## Expected result:
WebUI Colour should not change when manage people window is opened

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.70.34 Chromium: 76.0.3809.87 (Official Build) nightly (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

cc: @simonhong

**Comment by simonhong** [comment]
Same issue with https://github.com/brave/brave-browser/issues/5373.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.4.86 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description 
- Verified the test plan from https://github.com/brave/brave-core/pull/4210
- Verified that theme changes WebUI according to theme selection no matter the Profile manager is opened.

**Light Theme**
![image](https://user-images.githubusercontent.com/38657976/74427527-47297800-4e7d-11ea-8244-49fc3cd82102.png)
