### ISSUE TITLE
Top sites algorithm is broken

### ISSUE THREAD

**Issue by markg85** [brave/brave-browser#5558]
Hi,

I'm using Brave version 0.67.123 on Arch Linux.

So here's the situation. There are a couple of sites i visit daily, say 5.
With daily i mean open it, spend there between 30 minutes till a few hours, depending on the content of the day.

Yet only one of them appears in the top 6 sites.

Now for the kicker, just the other day i spend a few hours on a wallpaper site to, well, find a new wallpaper :) That site is surprisingly in my top sites!

Then for the bonus. Another site (one of my router) that i only visited once a few weeks ago is STILL in my top sites.

With that observation i'm guessing the algorithm used for the top sites is either non-existent or quite broken. That along with more issues in the top sites (like the time still being shown wrongly and nearly no customization for it like pinning additional sites) is a quite persistent annoyance for me in using Brave. I still keep using it, but it annoys me every time.

Is there any plan on fixing the current situation?

Cheers,
Mark

**Comment by bbondy** [comment]
Do you have any of the tiles pinned? My top sites are accurately the top sites I visit.
We'll be adding the ability to add more sites.   You can also click on the x to get rid of one if you don't want it there.

**Comment by markg85** [comment]
> Do you have any of the tiles pinned? My top sites are accurately the top sites I visit.
> We'll be adding the ability to add more custom sites. You can also click on the x to get rid of one if you don't want it there.

It is really far from accurate for me. Some sites i visit, say, once a week are in there seemingly persistently and sites i visit very often keep ketting appearing and being kicked out seemingly randomly.

I have no sites pinned.
I had no sites closed, but i did do that now. But that too is very wonky at best. As i tried to close about 5 at which point i now just have just one tile less (just 5 instead of the already sparse 6). I'm guessing the top sites list to chose from is 10 entries in the backend? If that's the case, that's a really low nasty limit! And - i think - not required at all from a technical reason. As i assume the site visits are probably stored in some internal database structure (sqlite?) so why not just re-query the top 10 after each delete?

I don't get why this needs to be so problematic at all though. There is brave for mobile which has just the top sites as it looks like in chrome and there it works perfectly. On the desktop, not so much. Why don't you folks add an opt-out of the current new tab page to let the users revert back to the chrome version of the top sites?

**Comment by markg85** [comment]
So, all of a sudden it struck me how the current algorithm must work that isn't working for me.
I bet it's currently based on clicks! So if i click a site a 100 times it probably appears in my top x sites. I could be off though. But i bet this metric has a high deciding factor.

Now what if i open some sites just a few times a day but stay on them for hours?
And other sites i open lots of times a day but close relatively quickly (making their total time/day not even minutes long).

What would happen with the top sites in that usecase?

I'm guessing those that i click often will be in my top sites, those that i click just a few times but stay on for long periods of time simply get less clicks (say reading a news site) thus (i assume) are less important for the top site ranking.

**if this is true**, which is surprisingly difficult to verify, then the brave metric should take time spend on a site into account. 

Note: I think brave has different logic for desktop topsites as opposed to mobile topsites.
My mobile topsites are fine and as i would expect them.
My desktop topsites are totally wrong if i don't interfere (like closing a few). Sites that i haven't visited for like a MONTH are even still in there.

**Comment by rebron** [comment]
@markg85 I'm going to close this one out as we don't have anything actionable here. We're using the same top site algorithm as Chrome and same as mobile but different usage for the different platforms will yield different results. 

We will be adding more tiles than just the six at some point but in the mean time closing out tiles or pinning tiles should help fine tune the sites you want to see there.

**Comment by markg85** [comment]
@rebron Sorry for the late response.

Are you **absolutely sure** that the **desktop** brave browser uses the exact same logic for determining the topsites? As yesterday i had to visit ebay (i hardly ever visit that) and now it's right at my no.3 position. I do admit, i did hang around on ebay for a while so if time is a factor in determining those sites then it might have had an effect. It kicked out a site i visit **multiple times a day** and read articles on.

I do believe if you say that **the mobile brave** mobile uses the same logic as mobile chromium as i have no issue there. But desktop.. well, they need a lot of work there to get right.

**Comment by bsclifton** [comment]
@markg85 correct, we are using the Chromium top sites API:
https://developer.chrome.com/extensions/topSites

You can see our usage of it here:
https://github.com/brave/brave-core/blob/3e5dc38f909d1d00bd5269bd9bd719fc0a35cdd7/components/brave_new_tab_ui/api/topSites/index.ts#L13-L15
