### ISSUE TITLE
Brave Ads still show when app are in full-screen mode

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#5559]
## Description 
Brave Rewards ads still show when watching a full-screen video on Youtube or VLC.

## Steps to Reproduce

   1. Go to youtube.com
   2. Select a video to watch
   3. Open full-screen mode

## Expected result:
Brave Rewards ads should not appear when apps are in full-screen mode.

## Reproduces how often: 
Easily reproduced.

## Brave version (brave://version info)

Release Version 0.67.123 Chromium: 76.0.3809.87

**Comment by tmancey** [comment]
@srirambv As discussed I cannot reproduce, could you please update ticket with your findings too. Also @karenkliu if we could arrange a screen share if the issue re-occurs so we can diagnose the problem

**Comment by srirambv** [comment]
I am not seeing any ads when I have YT playing video in focused tab. No ads were shown when video was playing in full screen or as a standard player.

**Comment by jsecretan** [comment]
So, I can actually get this to reproduce when doing other full screen activities, like looking at a presentation.  To reproduce do the following.  Go to:

https://www.slideshare.net/MohammadImtiyazAhmed/the-deep-learning-technology-on-coco-framework?qid=10bdae56-cbcd-40ac-a450-1be20f377532&v=&b=&from_search=3

And select the arrows to make this full screen.

And then wait 15 seconds.  Move the mouse again and an ad should appear.  We should avoid ads in these cases.

**Comment by tmancey** [comment]
@jsecretan but we would need to classify a page on whether a user is working, casual browsing, shopping etc. Right now we can only detect if video or audio is playing. And only block ad notifications if video is playing in the current tab.

**Comment by karenkliu** [comment]
Okay, I found some examples:

1. _Crunchyroll is an American distributor, publisher, licensing company and international online community focused on video streaming East Asian media including anime, manga, drama, music, electronic entertainment, and content._

<img width="1680" alt="crunchyroll" src="https://user-images.githubusercontent.com/2388823/63472758-fb46ca80-c427-11e9-9691-07938aacc57c.png">



2. _Putlocker is an online index of hosted files and a website used for streaming entertainment media such as films and television series._

<img width="1680" alt="torrent streaming" src="https://user-images.githubusercontent.com/2388823/63472762-fda92480-c427-11e9-91cb-4da9a3fa5faa.png">


Both of these sites showed Brave Ads *while* the video was playing.

**Comment by rebron** [comment]
Clearing milestone.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.1.4 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3380
- Verified Streaming CNBC.com, Cnet.com, Sports news, Music, and entertainment media such as films and television series and ensured there are no brave ads shown while the app is in full mode
