### ISSUE TITLE
[MacOS] Restricted flag should be set to yes

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#556]
<img width="797" alt="screen shot 2018-07-13 at 4 49 44 pm" src="https://user-images.githubusercontent.com/1903815/42741628-e3634f2a-8868-11e8-91a6-2d5647864d1b.png">

**Comment by jumde** [comment]
Verified this is fixed on `Brave | 0.53.3 Chromium: 69.0.3497.12 (Official Build) dev (64-bit)`

<img width="799" alt="screen shot 2018-08-16 at 12 30 50 pm" src="https://user-images.githubusercontent.com/1903815/44230567-575d7b80-a150-11e8-8f4b-b4266725bf34.png">

**Comment by jumde** [comment]
I would tag this as an enhancement, the `tor` source code does not have a `sandbox profile`. I think  we should create a new issue for that.  cc: @kjozwiak

**Comment by LaurenWags** [comment]
Using the same test cases as @kjozwiak I see the same in my Activity Monitor. 
 
![screen shot 2018-09-26 at 5 32 31 pm](https://user-images.githubusercontent.com/28145373/46110649-50e00c00-c1b2-11e8-9e69-99393aff383d.png)

Used the following cases & build:

* open several `normal windows` with a few tabs loaded in each window
* opened an `incognito window` with a tabs
* opened a `guest window` with a few tabs
* opened a `tor window` a few tabs

Went through verification using the following build under `macOS 10.12.6 x64` - pass

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Mac OS X

**Comment by kjozwiak** [comment]
> I would tag this as an enhancement, the `tor` source code does not have a `sandbox profile`. I think we should create a new issue for that. cc: @kjozwiak

Perfect, thanks @jumde 👍Marking this as passed as everything else is working as expected. Issue #1307 will cover the Tor case.
