### ISSUE TITLE
Offer to install Google Translate extension in translate bubble

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#5561]
Repurpose translate UI to offer Google Translate extension installation as a translate solution that could work on all desktop channels.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.115 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/3103
- Logged https://github.com/brave/brave-browser/issues/5796
- Encountered https://github.com/brave/brave-browser/issues/208

**Comment by GeetaSarvadnya** [comment]
@yrliou Google translate option is not available in the context menu in Windows. Is this expected? whereas I could see `Google translate` option in macOS https://github.com/brave/brave-core/pull/3103#issuecomment-523247106. 

![image](https://user-images.githubusercontent.com/38657976/63649867-bb058600-c760-11e9-858b-0ea12d1911b6.png)

**Comment by yrliou** [comment]
@GeetaSarvadnya Could you try the extension in Chrome and see if it shows up in Chrome's context menu on Windows? Thanks.

**Comment by GeetaSarvadnya** [comment]
@yrliou Nope, in chrome `Google translate` option is not available in the context menu in Windows.

Thanks!

**Comment by crogonint** [comment]
Here's your missing translate service. Upvote this:
https://yahoo.uservoice.com/forums/341361-yahoo-homepage/suggestions/40044514-bring-back-babelfish

**Comment by dtantono** [comment]
@crogonint is babelfish also open-source similar like aspell?

**Comment by crogonint** [comment]
Babelfish was the original translate engine. I would be shocked if some
derivative of it wasn't open source.

**Comment by NayamAmarshe** [comment]
I think it's better to use this extension than the one Brave currently suggests.
This extension has context menu entries and has better customizability than Google's, it's also better for privacy.
https://github.com/FilipePS/Traduzir-paginas-web

**Comment by dtantono** [comment]
@NayamAmarshe I know this project and the developer said that the porting process from the firefox to chrome is underway. So, we need to be patient.

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe I know this project and the developer said that the porting process from the firefox to chrome is underway. So, we need to be patient.

I'm actually using this right now on Brave and it works just fine.

**Comment by dtantono** [comment]
@NayamAmarshe so you use Firefox xpi file on chrome. Is that so?

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe so you use Firefox xpi file on brave. Is that so?

Of course not. The extension is easily available for install in Chromium browsers. You just need to clone the git, rename chrome_manifest to just manifest and install it as an unpacked extension in Brave.
The author has already provided the steps to install the extension in Chromium browsers: https://github.com/FilipePS/Traduzir-paginas-web#to-install-the-extension-on-a-browser-other-than-firefox-follow-these-steps

**Comment by dtantono** [comment]
The developer (https://github.com/FilipePS/Traduzir-paginas-web/issues/55) wants to port the extension to the chrome store natively and I think it is a good idea because the update process will become automated from the chrome store rather than recompile the code manually which is quite time-consuming. Besides, I chatted with brave tech support that they seriously considered the translation feature on the brave browser and there is no ETA yet 
So, I hope this feature can be realised someday because personally, I don't really like to depend on the extension too much for memory consumption reason.
