### ISSUE TITLE
Sync wallet balances

### ISSUE THREAD

**Issue by leshacat** [brave/brave-browser#5566]
## Description 

I have Brave on Mobile, but the wallets function separately. They need to be the same wallet I want all my tokens accesible from desktop AND mobile.

## Steps to Reproduce

   1. Install brave on CPU
   2. Install brave on Mobile
   3. Receive ad rewards on both, but in separate wallets per device

## Actual result:

Wallet balances are not combined and accessible across all devices.

## Expected result:
Wallet balances should be combined and accessible across all devices.

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Brave | 0.67.123 Chromium: 76.0.3809.87 (Official Build) (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Linux

## Version/Channel Information:

- Can reproduce this issue with the current release

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:
I had 3 BAT I had to tip to myself to get it to my main wallet on Desktop. Please make this a combined balance, or a easy way to transfer across sync'd devices.

Thanks

**Comment by kjozwiak** [comment]
@leshacat thank you for the suggestion 👍Having Brave sync different type of Brave Rewards information on multiple devices is on the roadmap but there's currently no hard set date.

However, with user wallets being released in `0.69.x` (September 10, 2019) and eventually making it into android, you'll be able to use an uphold account on multiple devices so you'll be able to share your BAT across devices.

Going to close this off for now. CCing @rebron in case he has more information he can share 👍

**Comment by Afrikok** [comment]
Now almost 2022 and the wallets cannot be used as written above?
