### ISSUE TITLE
Bookmark is not working on new tab

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#558]
## Test plan
See https://github.com/brave/brave-core/pull/541

## Description 

If you click on star on new tab site, site is not bookmarked

## Steps to Reproduce

   1. clean profile
   2. try bookmarking one site
   3. bookmark one site regularly and then try to un-bookmark it on new tab

## Actual result:

nothing happens

## Expected result:
Bookmark should be added/removed

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Version 0.50.9 Chromium: 67.0.3396.103 (Developer Build) (64-bit)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux
