### ISSUE TITLE
Set default shields mode depending on whether it is a new or existing Brave user

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#5582]
## Test plan
See https://github.com/brave/brave-core/pull/3154

## Description
In recent versions of Brave, there is a new "simple" shields view, as well an "advanced" view. The "advanced" view is very similar to the pre-existing single-view version. 

In light of that:

* Existing Brave users should receive the advanced view by default.

* New Brave users should see the simple view by default (and with one click, they can switch to the advanced view, for all sites). 

(*IMPORTANT NOTE*: The two-mode shields implementation is already in Dev. This particular fix should be uplifted so that by the time the two-mode shields panel hits release, or even Beta, we have already made this change, to keep things familiar for existing users.)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/3154
