### ISSUE TITLE
Brave should depend on upstream WebTorrent; Create de-facto "chromeapp" field in package.json spec

### ISSUE THREAD

**Issue by feross** [brave/brave-browser#5587]
To resolve #856 and obviate the need for Brave to use a WebTorrent fork, I'm attempting to make a defacto standard for specifying Chrome App dependency substitutions using the `"chromeapp"` field in `package.json`.

The `"chromeapp"` field is just like the [`"browser"` field in `package.json`](https://github.com/defunctzombie/package-browser-field-spec) except it's intended for Chrome Apps instead of a generic browser environment. Bundler tools like `browserify` or `webpack` can be configured to look for the `"chromeapp"` field instead of the `"browser"` field when doing a build for a Chrome App.

In the case of WebTorrent running in a Chrome App context in Brave, we can use raw sockets, so we want to replace e.g. `require('net')` with `require('chrome-net')` and similar.

I'm sending PRs to all dependent projects:

- https://github.com/jscissr/http-node/pull/2
- https://github.com/webtorrent/webtorrent/pull/1691
- https://github.com/webtorrent/torrent-discovery/pull/45
- https://github.com/mafintosh/k-rpc-socket/pull/17
- https://github.com/webtorrent/bittorrent-tracker/pull/328

Once this is complete, we should be able to depend directly on upstream WebTorrent.

**Comment by feross** [comment]
All PRs have been merged, except for the one to `http-node`. I'm going to make `webtorrent` itself temporarily depend on an `http-node` fork so that we can make progress on this issue.

I'm about to send a PR to make Brave depend on upstream `webtorrent`, which should now have all the necessary `chromeapp` fields. 🎉

(I'll be responsible for updating `webtorrent` to use upstream `http-node` once they merge the PR.)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.126 Chromium: 77.0.3865.65 (Official Build) (64-bit)
-- | --
Revision | 87a331a3169cab563505fb44011058b904011ba1-refs/branch-heads/3865@{#726}
OS | macOS Version 10.14.6 (Build 18G95)

* Verified the test case outlined under https://github.com/brave/brave-core/pull/3134
