### ISSUE TITLE
Tip Panel seems inconsistent or broken

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#5590]
see image ----
![image](https://user-images.githubusercontent.com/35932307/62678644-e87fc080-b966-11e9-82c4-28ee35b6ce3b.png)

Went to a YT video (did this with multiple videos) and tried to tip; two issues
a) the Tip Panel verified status is not reflecting correctly (might be a server issue)
b) big issue is BR panel does not show for a lot of YT channels (intermittent only)

@NejcZdovc -- 0.69.x

**Comment by mandar-brave** [comment]
This is on nightly V70.34
Not reproducing on latest developer V69.100

**Comment by NejcZdovc** [comment]
It works for me. Steps that I did:
- clean profile
- enable rewards
- go to https://www.youtube.com/watch?v=SQrzu1Q1IE8

![image](https://user-images.githubusercontent.com/9574457/68927612-70584080-0788-11ea-9f98-db7e3bef0eb0.png)

**Comment by NejcZdovc** [comment]
closing as stale
