### ISSUE TITLE
Ads are showing when user is engaging with browser (typing, etc)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#5591]
## Description 
The Ads system notification might be shown to users while they are on a given page typing into an input box, etc. It may also be showing if they are interacting with the browser chrome (dragging window, trying to close window, etc)

I typically get the notifications shown when the browser is brought back into focus after being blurred. It's possible the user is using keyboard shortcuts to switch to Brave and the ads are being shown then

Originally reported here https://twitter.com/Harry_snvb/status/1159268822903336960

## Steps to Reproduce
Exact steps are not known. But it may look something like this:

1. Fresh profile
1. Enable rewards and verify ads is enabled
1. Visit a page
1. Put cursor into an input box
1. Wait for some period of time (possibly switch to another app, and then back again)
1. Type into the box

**Comment by mandar-brave** [comment]
@tmancey can you test if you have a windows machine handy -- not sure if something broke or the delegate to the system notification engine is delayed. We can make it a P2 once you return on the findings.

**Comment by tmancey** [comment]
@mandar-brave This is due to the browser becoming un-idle when the app is brought to the foreground or user input is detected. Would you like me to investigate removing key stroke detection for idle/un-idle events?

**Comment by tmancey** [comment]
On the latest macOS build key presses reset the idle timer, can you please let me know if this is improved. Thanks

**Comment by mandar-brave** [comment]
@tmancey seems reasonable that it was genuinely brought back from idle.

**Comment by tmancey** [comment]
@bsclifton @jsecretan When the browser is brought into focus ads may be triggered by design. Ads are not triggered if the user is typing on desktop/android

**Comment by tmancey** [comment]
https://github.com/brave/brave-browser/issues/5090

**Comment by tmancey** [comment]
https://github.com/brave/brave-browser/issues/5029
