### ISSUE TITLE
Enable dcheck_always_on for CI and developer release builds

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#5592]
It seems that at the moment we do not enable DCHECKs on CI builds - we can miss a lot of potential crashes and bugs because of this. So we should always enable DCHECKs for everything that is not shipped to the end users.

**Comment by iefremov** [comment]
Also its worth to enable `is_component_build` for all dev / CI builds, since many engineers get stuck when trying to work with Release locally.

**Comment by iefremov** [comment]
https://github.com/brave/brave-browser/blob/master/lib/config.js#L104

**Comment by bridiver** [comment]
We definitely should not be setting `is_component_build` for CI builds

**Comment by bsclifton** [comment]
cc: @petemill @iefremov

**Comment by bridiver** [comment]
I'm fine with keeping DCHECK on PR builder if it doesn't cause too many spurious failures which can happen from upstream code as well as our own

**Comment by iefremov** [comment]
> We definitely should not be setting `is_component_build` for CI builds. The build configurations define the flags, not the other way around. If we want some other configuration then we should create a new configuration type like `Default` that it used by chromium

This way, `Release` is something obsolete because neither developers, nor buildbots should disable `is_component_build`. Rather we want an "official build" configuration that disables it for production builds.

**Comment by iefremov** [comment]
If we can't build componentized release browser on build bots, how engineers are expected to build it? :)

**Comment by bridiver** [comment]
Release is the official build configuration. Why would you have a configuration called “Release” that wasn’t for release builds?

**Comment by bridiver** [comment]
The primary purpose of ci is to ensure that code changes build and run for release channels. If we build PRs as component builds, they may fail when merged into master. It would be great if we could run every configuration in ci, but we don’t have the resources for that and I’m not even sure if Google runs multiple configurations for their buildbot. PR builder configurations should match release channel configurations to ensure that the code will build correctly for release when it is merged into master. Separately we can address dev build/run speed with a Default configuration
