### ISSUE TITLE
Start page is shown as new tab in shields

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#56]
Clean install brave
Click continue on the start page which opens up Google.com
Click on shields, page title shows as `newtab`
![image](https://user-images.githubusercontent.com/17010094/34970063-2e7f01a2-fa98-11e7-91df-56563db27ab4.png)

**Comment by srirambv** [comment]
This looks fixed on c84b457. Not seeing the google launch page on start.

**Comment by GeetaSarvadnya** [comment]
Verified on:

Brave | 0.54.2 Chromium: 69.0.3497.42 (Official Build) dev (64-bit)
-- | --
Revision | 9c4613c66dfeb2b76ef6dd4b15884c15db3b4969-refs/branch-heads/3497@{#655}
OS | Windows
JavaScript | V8 6.9.427.14
Flash | 30.0.0.154
