### ISSUE TITLE
Pull in Japan localization  

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#5601]
## Description 

Please pull in the Japan localization from transifex which was recently updated

**Comment by rebron** [comment]
@mkarolin Already added in?

**Comment by mkarolin** [comment]
@rebron should be pulling the latest for 0.68.x today.

**Comment by bsclifton** [comment]
@anthonypkeane @mkarolin any QA or verification needed?

**Comment by anthonypkeane** [comment]
@chkk525 can you please verify?

**Comment by bsclifton** [comment]
@chkk525 we can ping you when there's a build which uses these 😄
