### ISSUE TITLE
Social media blocking does not work

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#5603]
## Steps to Reproduce

1. Clean install
2. Go to `brave://settings/socialBlocking`
3. Disable all `Allows ...`
4. Go to `https://fmarier.github.io/brave-testing/social-widgets.html`

## Actual result:

Social media content is not blocked
![image](https://user-images.githubusercontent.com/34715963/62747546-3ffc5a00-ba55-11e9-879a-3c2516681443.png)

## Expected result:
Social media content is blocked
![image](https://user-images.githubusercontent.com/34715963/62747542-37a41f00-ba55-11e9-841b-b283817b80b6.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

**Reproducible on**

Brave | 0.68.120 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Ubuntu 18.04 LTS

Brave | 0.68.120 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

Brave | 0.70.49 Chromium: 76.0.3809.100 (Official Build) nightly (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

**Not reproducible on release**

Brave | 0.67.124 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Ubuntu 18.04 LTS

Brave | 0.67.124 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

cc @brave/legacy_qa @fmarier @rebron

**Comment by LaurenWags** [comment]
Reproduced on macOS:

Brave | 0.68.128 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

**Comment by rebron** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/5651
