### ISSUE TITLE
WebTorrent extension is broken

### ISSUE THREAD

**Issue by feross** [brave/brave-browser#5604]
## Description 

The last update we did to `bittorrent-tracker` broke the WebTorrent extension. I confirmed it's broken in Nightly.

The issue is that the `URL` constructor is buggy Chromium. https://bugs.chromium.org/p/chromium/issues/detail?id=734880

We switched to `URL` from `require('url')` in `bittorrent-tracker@9.13.0`. Commit: https://github.com/webtorrent/bittorrent-tracker/commit/93b41391a95546b11bceb1ee0d5b44f4c6a71592

This code path was not exercised by `bittorrent-tracker`'s tests because UDP trackers are normally only used in a Node.js environment. Brave run the code in a Chrome extension environment which we don't test.

## Steps to Reproduce

   1. Open https://webtorrent.io/torrents/sintel.torrent
   2. Click start torrent

## Actual result:

Torrent does not start downloading 

## Expected result:
Torrent should start downloading

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Nightly

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? Yes

**Comment by feross** [comment]
Fixed in bittorrent-tracker@9.14.1.

**Comment by feross** [comment]
Fixed by:

- https://github.com/brave/brave-core/pull/3136
- https://github.com/brave/brave-core/pull/3137
- https://github.com/brave/brave-core/pull/3138

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.129 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Ubuntu 18.04 LTS

Tested on https://webtorrent.io/free-torrents. Checked torrents and magnet links.
