### ISSUE TITLE
WebTorrent: Remove DNS shim

### ISSUE THREAD

**Issue by feross** [brave/brave-browser#5606]
All the shims and forks required for WebTorrent have been removed in 

but we still have a shim for `require('dns')`, here: https://github.com/brave/brave-core/blob/d1875987afa0f872cf7d896b1d325c4331aaa8aa/components/webpack/webpack.config.js#L17

```
    alias: {
      'brave-ui': path.resolve(__dirname, '../../node_modules/brave-ui/src'),
      // TODO(feross): Publish chrome-dns and add to "chromeapp" package.json
      // field so this isn't required anymore
      dns: path.resolve(__dirname, '../common/dns.ts')
    },
```

This issue is a reminder to replace this with an npm-published shim of `dns` that works in chrome apps.

**Comment by feross** [comment]
I just published `chrome-dns`: https://github.com/feross/chrome-dns

**Comment by feross** [comment]
I just shimmed the `dns` api in the one place that it was used in the `webtorrent` dependency tree. https://github.com/mafintosh/k-rpc-socket/commit/9b1e40460c7b5d53526e9234fc79c28af3cda0c0

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.126 Chromium: 77.0.3865.65 (Official Build) (64-bit)
-- | --
Revision | 87a331a3169cab563505fb44011058b904011ba1-refs/branch-heads/3865@{#726}
OS | macOS Version 10.14.6 (Build 18G95)

* Verified STR outlined under https://github.com/brave/brave-core/pull/3145
