### ISSUE TITLE
Edit shields settings and Reload buttons in shields doesn't work

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#561]
## Description 

Edit shields settings and Reload buttons in shield doesn't work

## Steps to Reproduce

   1. Open a new tab and visit any site
   2. Open shields
   3. Edit shields/Reload buttons doesn't work

## Actual result:

Edit shields settings and Reload buttons in shield doesn't work

## Expected result:
Should work similar to b-l 

## Reproduces how often: 

100%

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows
