### ISSUE TITLE
Stackoverflow Tipping

### ISSUE THREAD

**Issue by jdkuki** [brave/brave-browser#5616]
## Description 

Tipping support for StackOverflow should be added via panel and inline button below upvote button. 

## Actual result:

n/a

## Expected result:
![image](https://user-images.githubusercontent.com/8422122/62827611-0fb4d880-bb87-11e9-9d1d-431b0965bb02.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by MenachemICTBIT** [comment]
Any update on this?

**Comment by bsclifton** [comment]
cc: @Miyayes

**Comment by Miyayes** [comment]
We have a list of different platforms we want to support moving forward. However, we will open GitHub issues for those implementations once there are actual plans on deck. Stackoverflow is a platform we're looking at.
