### ISSUE TITLE
Typescript (.ts and .tsx) files have no syntax highlighting when opened in the dev tools Sources tab

### ISSUE THREAD

**Issue by tamj0rd2** [brave/brave-browser#5618]
## Description 

I'm developing a website using Typescript. When I open the dev tools, go to the Sources tab and click any `.ts` or `.tsx` files, there is no syntax highlighting.

## Steps to Reproduce

Requires node/npm to be installed

   1. Run `npx create-react-app myappname --typescript`
   2. `cd myappname`
   3. `npm start`
   4. Open `localhost:3000` in brave
   5. Go to DevTools > Sources tab
   6. Open index.tsx or any other ts/tsx file

## Actual result:

No syntax highlighting although the debugger still works

![image](https://user-images.githubusercontent.com/20561445/62831224-99aa8300-bc13-11e9-9d46-9731f2abfb24.png)

## Expected result:
Syntax highlighting, shown in Chrome

![image](https://user-images.githubusercontent.com/20561445/62831232-bd6dc900-bc13-11e9-897a-d384b99c35aa.png)

## Reproduces how often: 

Easily reproduced. I've never seen it working correctly

## Brave version (brave://version info)

Brave | 0.67.124 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1809 (Build 17763.615)

Chrome for comparison:

Google Chrome | 76.0.3809.100 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1809 (Build 17763.615)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tried
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Not tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment]
Possibly blocking a script from Google that's doing the styling.

**Comment by tamj0rd2** [comment]
But I would think that whatever's responsible for providing syntax highlighting for files in the devtools would be shipped with Brave?

**Comment by ksbrar** [comment]
Bump.

**Comment by rguillaume** [comment]
That would be great

**Comment by alexichepura** [comment]
This stopped me as a web developer to use brave as main browser. Three times =(

**Comment by bsclifton** [comment]
This may be fixed now; with Nightly (and it'll work its way down through channels), you can enable remote debugging under brave://settings/privacy. When this is enabled, it should fetch sources

@ksbrar @rguillaume @alexichepura and others: can you please try Nightly and confirm it works? (with Remote Debugging enabled?)

**Comment by alexichepura** [comment]
@bsclifton thanks for the update! It works for me after enabling remote debugging and browser restart.

**Comment by bsclifton** [comment]
Closing as this is fixed with https://github.com/brave/brave-core/pull/4044
