### ISSUE TITLE
Meta issue for supporting multi channel install on MacOS

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#562]
- [ ] Support `branding_path_component` (https://github.com/brave/brave-browser/issues/153)
- [x] Enable multi channel install (https://github.com/brave/brave-browser/issues/469)

To support multi-channel we should have different `BRANDING` file for different channel.
Other platforms already support multi channel install.

**Comment by simonhong** [comment]
I completed multi channel install on MacOS w/o branding_patch_component.

**Comment by LaurenWags** [comment]
@simonhong is the testing done for https://github.com/brave/brave-browser/issues/469 sufficient for this issue as well? cc @kjozwiak

**Comment by simonhong** [comment]
@LaurenWags Yep, I think you can ignore this issue. #469 is sufficient.
