### ISSUE TITLE
View selection of Brave Ads at a brave:// url

### ISSUE THREAD

**Issue by jakecoble** [brave/brave-browser#5621]
Brave Rewards ads currently come to the user at intervals through the operating system's notifications. It's preferable to be able to spend attention in exchange for BAT deliberately instead of having attention taken from you every so often.

A list of selected ads could be displayed at a dedicated brave:// url (such as brave://ads), which would permit the user to decide when they want to spend their attention. This list might pay out BAT upon viewing with an hour of cooldown between views.

**Comment by bsclifton** [comment]
This is definitely something we want to do (and have some plans around)
cc: @mandar-brave

**Comment by mandar-brave** [comment]
Thanks @bsclifton @jakecoble 
Noted to add to the current work-stream.
We are going to provide an Ads history/bookmark option (slated in 0.70, i believe).

@alex can you point out the details re: history and feedback.

**Comment by alexwykoff** [comment]
I believe this is already solved with our history & feedback modal located at Rewards Settings (brave://rewards/) -> Ads Setting Card -> '7-day Ads History'

**Comment by jakecoble** [comment]
The history keeps a record of delivered ads, but it's not the way the ads are delivered. I'm proposing that ads are only considered delivered to the user (and thereby making the user eligible for a BAT reward) until they're viewed in a dedicated location in the browser.

**Comment by tmancey** [comment]
Closing as there is now 7 days of ads history viewable at brave://rewards
