### ISSUE TITLE
Assertion on startup when using old ads history JSON data

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#5623]
@tmancey mentioned that the ads history related changes are throwing an assertion with his profile due to a JSON-related problem. Upon investigating, noticed that the old `ads_shown_history` format was an array of timestamps (vs. the new format which is an array of objects). Unfortunately, `document.Parse` wasn't returning an error and instead a later call to `HasMember` was asserting.

Spoke with @tmancey and we decided to just look explicitly for a uint64_t and, if found, move on to the next member (as it was always expected that a user's ad history would reset with this upgrade anyway).

**Comment by btlechowski** [comment]
@emerick This issue is set to `QA/Blocked`. I am not sure why. If it is something that can not be tested by QA, just add `QA/No` label.

**Comment by emerick** [comment]
@btlechowski Sorry, must have hit the wrong tag - fixed now!

**Comment by GeetaSarvadnya** [comment]
Unable to test the issue due to https://github.com/brave/brave-browser/issues/6148.
Open an old profile is removing Ads panel. There are no ads viewed data in the panel.

![image](https://user-images.githubusercontent.com/38657976/65685639-0f619580-e080-11e9-9dc8-247eb93688e2.png)
