### ISSUE TITLE
ad notifications do not display in Notification Center on macOS

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5628]
## Description 
Ads which are not clicked or dismissed are not being shown in the Notification Center.

## Steps to Reproduce

   1. Have Ads enabled on your profile.
   2. Be sure you have `Show in Notification Center` checked in OS settings and are not set to 'Do not disturb'.
   3. View an ad notification but do not click on it to open or dismiss it. Let the notification sit and go away (2 min)
   4. Open Notification Center. 

## Actual result:
No ad notification in Notification Center.

## Expected result:
Ad notification in Notification Center.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.102 Chromium: 76.0.3809.100 (Official Build) dev (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
I'm using High Sierra, but @kjozwiak is using Mojave and is also seeing this, although it did work at one time for him.

**Comment by tmancey** [comment]
@LaurenWags Can you demonstrate this to me as I just tested and notifications are appearing, thanks

**Comment by LaurenWags** [comment]
Yes, happy to. Let's get on a call when you're available.

**Comment by tmancey** [comment]
@LaurenWags Can this ticket be closed as on our call we discovered your OS was older than Windows 10 build 17134 which does not support native notifications in Chromium, therefore you were seeing Chromium Message Center notifications which are not added to the notification center

**Comment by LaurenWags** [comment]
Since @kjozwiak experienced it on Mojave I think it merit further research or perhaps a call with him - I understand why it's happening on High Sierra, but my understanding is that it should be working on Mojave.

**Comment by tmancey** [comment]
@LaurenWags agreed.

@kjozwiak can you let me know when you would be available to diagnose if this is an issue or working as expected. Thanks

**Comment by kjozwiak** [comment]
@tmancey I ran into the above while going through https://github.com/brave/brave-browser/issues/6466. Added some notes:

When selecting `Banners` via `Notifications` under macOS's `System Preferences`, the ad notification will disappear into the notifications tray within ~5s of being displayed. After ~2mins, the ad notification will be removed from the notification tray due to `"notificationType":"timeout"` and you'll get the following via the terminal:

```[22769:775:1104/161506.563648:INFO:ads_service_impl.cc(1969)] AdsService Event Log: {"data":{"type":"notify","stamp":"2019-11-04T16:15:06Z","notificationType":"timeout","notificationClassification":["arts & entertainment"],"notificationCatalog":"0b8b4425-2590-44c5-8c87-70167a3fda59","notificationUrl":"https://motille.com/path/lp.php?trvid=10008&trvx=518abffe&var1=21_entertainment"}}```

On the other hand, when selecting `Alerts` via `Notifications` under macOS's `System Preferences`, the ad notification will disappear after ~2mins due to `"notificationType":"timeout"` as mentioned above. Because the ad notification/alert was already visible for ~2mins, it doesn't go into the notification tray and basically disappears.

So it looks like ad notifications are disappearing once they hit `"notificationType":"timeout"` after ~2mins, even if they're in the notification tray.

**Comment by tmancey** [comment]
@kjozwiak Discussed with @jsecretan and unfortunately to fix notifications will no be added to the notification tray as to make them timeout we need to close the notification

**Comment by tmancey** [comment]
@kjozwiak Please see https://github.com/brave/brave-core/pull/3850 and Test Plan as I left a note explaining this. Thanks

**Comment by LaurenWags** [comment]
@tmancey per your comment above (https://github.com/brave/brave-browser/issues/5628#issuecomment-549758942) and reference to the test plan in https://github.com/brave/brave-core/pull/3850 - are we ok to mark this one as `wontfix` since the note on the PR referenced says
```

**Comment by LaurenWags** [comment]
Per discussion with @tmancey marking this as `wontfix` with current implementation of ad notifications. removing other labels and milestone as well.
