### ISSUE TITLE
Crash browser after going to the "Brave Rewards" page

### ISSUE THREAD

**Issue by Geradot** [brave/brave-browser#5629]
## Description 

The browser just crashing.

## Steps to Reproduce

   1. Go to the "Settings"
   2. Select tab "Brave Rewards"

## Actual result:

The browser closing.

## Expected result:
Opening "Brave Rewards" page.

## Brave version (brave://version info)

Brave | 0.70.57 Chromium: 76.0.3809.100 (Официальная сборка) nightly (64 бит)

## Version/Channel Information:

It does only in Nightly version after re-installing the browser.

**Comment by NejcZdovc** [comment]
hi, thank you for the report. This one was fixed with https://github.com/brave/brave-browser/issues/5623. Should be all good in the latest nightly that should arrive really soon.
