### ISSUE TITLE
Remove Sign-In to manage passwords

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#563]
STR:

1. Sign in to github.com
2. Save Password to Brave's password manager
3. Click Sign-In

<img width="355" alt="screen shot 2018-07-16 at 6 05 31 pm" src="https://user-images.githubusercontent.com/1903815/42791066-21015d44-8923-11e8-83f9-cc83836bc3ce.png">

<img width="838" alt="screen shot 2018-07-16 at 6 02 03 pm" src="https://user-images.githubusercontent.com/1903815/42791067-229bb8ca-8923-11e8-91b3-57b9ed2d401f.png">

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows
