### ISSUE TITLE
Verified support for user wallet release (0.69)

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#5631]
Change in release 0.69 already on nightly and developer builds;

Original change requested for user wallet release was to have a verified creator as one that is;
- verified with Brave
- verified with Uphold

Ask:
Keep original creator verification intact (as supported pre 0.69)
- Create verified with Brave
- OK not to be verified with Uphold

There are changes needed at the client end (and the protocol/API end to support this ask) 

1) UI change: treat all creators verified with Brave as verified (vs. only ones that are verified with Uphold)

2) Auto-contribute changes: support auto-contribute for all Brave verified creators
Support auto-contribute for all verified creators (verified with Uphold irrespective of their status with Uphold)

3) Change needed: Tipping with user wallets
When a user decides to tip with a user verified wallet, only if the creator is a user verified brave account with a verified Uphold account can the tip go through.

There are two text changes required for a user wallet tipping a verified Brave creator but unverified with Uphold. The transaction will be held at the browser end till the creator is verified with Uphold

Text changes:
In the tip-panel and the tip-banner; see images below
![image](https://user-images.githubusercontent.com/35932307/62898300-09029e80-bd0a-11e9-9d65-c632d7487539.png)

![image](https://user-images.githubusercontent.com/35932307/62898833-4e739b80-bd0b-11e9-8bb7-308c9969f5e3.png)

Change the warning text from unverified to: 
This Brave Verified Creator has not yet configured their account to receive contributions from Brave Users. Any tips you send will remain in your wallet until they complete this process

from @davidtemkin  -----------

 all publishers in semi-verified state remain shown as “verified” in address bar
• when a user attempts to contribute to one of these publishers in this intermediate state , via tipping or A-C, the contribution is held in the browser, retried for 90 days waiting for full verification should it occur. This is exactly the same as the unverified flow, except we make two small changes to the text / messaging, as follows:
1. The address bar shows these publishers as verified
Screen Shot 2019-08-12 at 12.37.54 PM.png 
Screen Shot 2019-08-12 at 12.37.54 PM.png

2. The Brave Rewards panel shows them as verified:
Screen Shot 2019-08-12 at 12.38.58 PM.png 
Screen Shot 2019-08-12 at 12.38.58 PM.png

2a. But we still show the grey unverified warning, just with slightly modified text. Current text: same images posted above.

The new text presented in this case will say something along the lines of “This Brave Verified Creator has not yet configured their account to receive contributions from Brave Users. Any tips you send will remain in your wallet until they complete this process.”
3. Similar changes will be made to the tipping dialog. Current version looks like this (edited) 

The new version will feature a change to the text in the white box, along the lines of: “This Brave Verified Creator has not yet configured their account to receive contributions from Brave users. Your browser will keep trying to contribute until they verify, or until 90 days have passed”.

@NejcZdovc @evq @corymcdonald

**Comment by davidtemkin** [comment]
@mandar-brave Unsure re: A-C comment above -- seems to me that A-C has to go through the same semi-verified process as do tips (i.e. put the A-C contributions in pending list if a creator isn't fully verified w/Uphold; recheck for full verified status for 90 days) since we cannot pay creators until they are fully verified.

**Comment by mandar-brave** [comment]
@davidtemkin per our chat, i am leaving the auto-contribute to every verified (Brave creator verified) account intact.

**Comment by LaurenWags** [comment]
@mandar-brave @NejcZdovc for the "warning" text (see red box on images below), I was expecting slightly different text than what is displayed. I got this expected text from the description above. Please confirm what should be displayed - the text from the description above or what is currently being shown.


For Panel
Expected text: This Brave Verified Creator has not yet configured their account to receive contributions from Brave Users. Any tips you send will remain in your wallet until they complete this process.
Actual text: This creator has not yet signed up to receive contributions from Brave users. Any tips you send will remain in your wallet until they verify.
![Screen Shot 2019-08-30 at 6 17 31 PM](https://user-images.githubusercontent.com/28145373/64177439-7d25f300-ce2d-11e9-9f3d-c60a7f465f65.png)


For Tipping Banner
Expected text: This Brave Verified Creator has not yet configured their account to receive contributions from Brave users. Your browser will keep trying to contribute until they verify, or until 90 days have passed.
Actual text: This creator has not yet signed up to receive contributions from Brave users. Your browser will keep trying to contribute until they verify, or until 90 days have passed.
![Screen Shot 2019-08-30 at 6 17 40 PM](https://user-images.githubusercontent.com/28145373/64177537-b1011880-ce2d-11e9-9c32-695d91979f01.png)

**Comment by mandar-brave** [comment]
This is an error - the text should be different for a verified Brave, unverified Uphold user. @NejcZdovc

**Comment by LaurenWags** [comment]
https://github.com/brave/brave-browser/issues/5868 logged for text on panel/tip banner

**Comment by LaurenWags** [comment]
@mandar-brave @NejcZdovc 

Since the description contains a lot of information, some of it conflicting, can one of you please confirm if the following encompasses this issue and what QA needs to test:

1. All creators verified with Brave (regardless of their KYC status with Uphold) should show the verified icon in the UI. No change to unverified creators.

2. Auto contribute will be allowed for Connected (not KYC'd with Uphold) and Verified (KYC'd with Uphold) creators. No AC contributions will go to Pending Contributions list for any creator who is verified with Brave. No change to how unverified creators are handled (their AC contributions will still go to Pending list).

3. Tips will only be allowed for Verified (KYC'd with Uphold) creators. Any tips, one time or recurring, to Connected (not KYC'd with Uphold) creators will go to Pending list. No change to how unverified creators are handled (their tips will still go to Pending list).

**Comment by NejcZdovc** [comment]
That is correct

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.123 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/3217
![Screen Shot 2019-09-04 at 11 19 30 AM](https://user-images.githubusercontent.com/28145373/64271742-de23f880-cf0b-11e9-9132-067baf199589.png)
![Screen Shot 2019-09-04 at 11 20 59 AM](https://user-images.githubusercontent.com/28145373/64271767-eaa85100-cf0b-11e9-8fbf-6eea0d8264f7.png)
![Screen Shot 2019-09-04 at 11 21 19 AM](https://user-images.githubusercontent.com/28145373/64271788-f72ca980-cf0b-11e9-86a9-c59c640ef66e.png)

Also verified the following (using staging env):

a. Un-verified publishers
- ex. google.com
- no verified checkmark anywhere in UI
- shows message about how they haven't signed up to receive tips in panel and tipping banner
- tips to these pubs go to 'Pending Contributions' list and BAT does not leave wallet (both one time and recurring tips)
- auto contribute to these pubs goes to 'Pending Contributions' list and BAT does not leave wallet 

b. Connected publishers (joined Brave Publishers but did not KYC their Uphold account)
- ex. twitch.tv/ilikeblueturtles
- shows verified checkmark in UI (panel, tip banner, ac table, tips table, etc)
- but also shows message about how they haven't signed up to receive tips in panel and tipping banner
- tips to these pubs go to 'Pending Contributions' list and BAT does not leave wallet (both one time and recurring tips)
- auto contribute to these pubs goes thru and BAT does leave wallet

c. Verified/KYC'd publishers
- ex. laurenwags.github.io (for AC) and twitter.com/bravelaurenwags (for tips)
- shows verified checkmark in UI (panel, tip banner, ac table, tips table, etc)
- does not show any message about how they haven't signed up to receive tips in panel or tipping banner
- tips to these pubs go thru and BAT does leave wallet (both one time and recurring tips)
- auto contribute to these pubs goes thru and BAT does leave wallet

AC table prior to contribution. As expected, publishers verified with Brave have verified check mark, regardless of KYC status.
![Screen Shot 2019-09-04 at 11 38 58 AM](https://user-images.githubusercontent.com/28145373/64271858-204d3a00-cf0c-11e9-8915-95b5dd26f128.png)

Tips table. As expected, publishers verified with Brave have verified check mark, regardless of KYC status.
![Screen Shot 2019-09-04 at 11 39 04 AM](https://user-images.githubusercontent.com/28145373/64271879-293e0b80-cf0c-11e9-9278-c8eb704371a7.png)

Pending Contributions table after AC/recurring tips reconcile. As expected, all tips and AC for the unverified publisher are displayed in this table. All tips for Connected (not KYC'd) publisher are displayed in this table but AC for this publisher is not. No tips or AC for Verified (KYC'd) publisher are displayed in this table.
![Screen Shot 2019-09-04 at 12 05 22 PM](https://user-images.githubusercontent.com/28145373/64271949-51c60580-cf0c-11e9-84d4-821fb0276688.png)

**Comment by davidtemkin** [comment]
@LaurenWags @mandar-brave @NejcZdovc Looks like the text for Brave-verified, but not Uphold-verified publishers is incorrect, based on the above: "but also shows message about how they haven't signed up to receive tips in panel and tipping banner" -- wording for unverified case and not-KYC'd case should not be the same.

**Comment by LaurenWags** [comment]
@davidtemkin https://github.com/brave/brave-browser/issues/5868 was logged yesterday for the text. Thanks for the double check! 👍
