### ISSUE TITLE
Remove theme step from welcome experience

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#5632]
Per direction from @davidtemkin, it's time to omit the theme selection panel from the Welcome experience. 

@rebron

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/brave-core/pull/3242

(thanks for closing, @rossmoody! 👋😄)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.1.10 Chromium: 78.0.3904.108 (Official Build) beta (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

Verified that theme step is removed from `brave://welcome`
