### ISSUE TITLE
Fails to load top banner https://www.dmm.com/

### ISSUE THREAD

**Issue by chkk525** [brave/brave-browser#5634]
## Description 

Brave keeps loading top banner.

## Steps to Reproduce

   1. access to https://www.dmm.com/

## Actual result:

Left: Chrome
Right: Brave
![image](https://user-images.githubusercontent.com/3054915/62910275-de245300-bdba-11e9-9572-2822154a8ea5.png)

## Expected result:
Load top banner. 

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.70.54 Chromium: 76.0.3809.100 (Official Build) nightly （64 ビット）
-- | --
変更履歴 | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
`https://www.dmm.com/js/marketing/display_ad.js`

Is used to load the advert carousel at the top, just need a whitelist of this to make it work.

Lists will updated in the next 24-48hrs.

**Comment by ryanbr** [comment]
Does this work now @chkk525 ? (may need to clean cookies first)

**Comment by chkk525** [comment]
@ryanbr on Nightly, it still showing loading animation forever but on release (0.67.125 Chromium: 76.0.3809.100) it loads correctly.

**Comment by ryanbr** [comment]
Just tested in Nightly; Version 0.71.17 Chromium: 76.0.3809.100 (Official Build) nightly (64-bit)  Seems to work okay here. Force an update of the browser ?

**Comment by chkk525** [comment]
On Brave | 0.71.21 Chromium: 76.0.3809.100 (Official Build) nightly, it still can't load the banner after super-reload and clearing cache. @ryanbr 

![image](https://user-images.githubusercontent.com/3054915/63421494-a31dc180-c443-11e9-95c8-527a4508fe36.png)

**Comment by ryanbr** [comment]
Okay, removed a suspect filter. https://github.com/easylist/easylist/commit/a10e2ad2a9eefeaf331a7435a908b30b6a8fab78

However, I did breifly see the issue. I just reloaded the page and it came right. and reload again, and saw it. It was really intermittent. It could be a server side issue?

**Comment by ryanbr** [comment]
I've been refreshing this site, and it's been such an intermittent issue.

**Comment by ryanbr** [comment]
Okay, https://github.com/easylist/easylist/commit/eafb3ac64e8f9a3cc01dd8067780b19de27a84d9 maybe help. 24-48hrs should see update

**Comment by chkk525** [comment]
This one still remains.... 
images like below are blocked and this causes page layout break.
https://p.dmm.com/p/bnr/ad/rotation/book01_g.jpg

**Comment by ryanbr** [comment]
Missed this, dmm.com item ^ couldn't be blocked because its a first-party item.

**Comment by ryanbr** [comment]
Seems okay now @chkk525  The site is a bit buggy (the occasional constant refreshing), just refreshing the site works for me.

**Comment by bsclifton** [comment]
Looks like this is still happening

**Comment by ryanbr** [comment]
Seems the site is now working @chkk525 @bsclifton

**Comment by ryanbr** [comment]
Just removed the closed tag, waiting on confirmation.

**Comment by chkk525** [comment]
@ryanbr That is still happening for me. Wait for a while, and resizing the window shows the carousel part. Not sure what is causing that but at least not happening on Chrome.

**Comment by bsclifton** [comment]
Looks like banner is still showing for me on Nightly ☹️

**Comment by ryanbr** [comment]
Working for me, safe to close @chkk525  ?

**Comment by ryanbr** [comment]
CLosing. WFM
