### ISSUE TITLE
Gyazo edit doesn't work well

### ISSUE THREAD

**Issue by chkk525** [brave/brave-browser#5636]
## Description 

 - In screen capture edit page, the original image isn't loaded.

## Steps to Reproduce

   1. Login to gyazo.com
   2. Take a screenshot
   3. Go to screen shot gyazo page
   4. Edit the screen capture

## Actual result:

Left: Chrome <-> Brave: Right
https://i.gyazo.com/28352e1fac86285ce190d01e0206a47c.mp4

## Expected result:
- It should work like in Chrome

## Reproduces how often: 

- Easily reproduce

## Brave version (brave://version info)

Brave	0.70.54 Chromium: 76.0.3809.100 (Official Build) nightly （64 ビット）
変更履歴	ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS	Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
got a test user/pass?

**Comment by chkk525** [comment]
@ryanbr i sent test user/pass via slack

**Comment by ryanbr** [comment]
Can confirmed its not a sheilds issue.  Chrome works fine.

**Comment by SvenVer** [comment]
I have the same issue. (Version 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)
I just got a new computer, on previous computer im quite sure it worked fine on Brave.

**Comment by ryanbr** [comment]
I've re-tested this site (using the free trial) so I can edit the images. seems to be okay now. if @SvenVer  @chkk525  can re-test?

Tested in Brave Release (1.4.96)

**Comment by SvenVer** [comment]
@ryanbr Everything works again already since a few months :) But thanks for updating.

**Comment by ryanbr** [comment]
Thanks!
