### ISSUE TITLE
Failed to load search result on Expedia

### ISSUE THREAD

**Issue by chkk525** [brave/brave-browser#5638]
## Description 

- Keep loading when I search on Expedia.co.jp

## Steps to Reproduce

   1. Go to https://www.expedia.co.jp/tour
   2. Perform a search there
   3. Wait for result

## Actual result:

<-Chrome : Brave->
https://gyazo.com/4a8905aa0dffc2c67231993de73608eb

## Expected result:
- Brave should get the result page like Chrome does

## Reproduces how often: 

- It happens every time.

## Brave version (brave://version info)

Brave	0.70.54 Chromium: 76.0.3809.100 (Official Build) nightly （64 ビット）
変更履歴	ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS	Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
Seems both scripts are being used;
`https://a.travel-assets.com/platform-analytics-prime/1/platform-analytics-prime-amd.js`
`https://a.travel-assets.com/platform-analytics-prime/1/dctk-compatibility-amd.js`

Which is affecting the page to load. Give it 24-48hrs for lists to update and it should be fixed.

**Comment by karamara** [comment]
@ryanbr 
can you please add https://b.travel-assets.com/datacapture/2/js/analytics-core-bundle-min.js to the white list as well? 
this forum is not getting replied yet but it will block expedia hotel result page to load half of time.
https://forums.lanik.us/viewtopic.php?f=64&t=43359

**Comment by ryanbr** [comment]
Can you give me an example where that script is broken?

**Comment by chkk525** [comment]
@karamara @ryanbr is there any update on this issue?

**Comment by ryanbr** [comment]
Seems okay now @chkk525  can confirm ?

**Comment by ryanbr** [comment]
@chkk525  safe to close this?

**Comment by chkk525** [comment]
@ryanbr Yes, it seems working now.

**Comment by ryanbr** [comment]
thanks
