### ISSUE TITLE
Developer tool doesn't load with remote devices in brave-browser (Desktop) 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5640]
## Test plan
See https://github.com/brave/brave-core/pull/4044

## Description 

Developer tool doesn't load with remote devices in brave-browser (Desktop). Verified couple of brave versions, the issue persists on all the versions including latest released version.

`0.67.125` - Dev tool doesn't load with remote devices
`0.66.101` - Dev tool doesn't load with remote devices
`0.65.121` - Dev tool doesn't load with remote devices

## Steps to Reproduce

   1. Clean or upgraded profile
   2. Connect Android device to Desktop
   3. Open `brave://inspect#devices` in Desktop
   4. Visit a site on brave Android
   5. Ensure the site lists on brave://inspect#devices
   6. Click on `inspect` under the device name in desktop
   7. Developer tool window launches but never loads

## Actual result:

Developer tool window launches but never loads

![image](https://user-images.githubusercontent.com/38657976/62915923-d319f480-bdb3-11e9-90f6-2ef55459cf6b.png)

## Expected result:
Should load developer tool with remote devices

## Reproduces how often: 

Always

## Brave version (brave://version info)

All brave versions

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa

**Comment by bsclifton** [comment]
@GeetaSarvadnya this may be intentional

@pilgrim-brave would this be happening because remote debugging was disabled with https://github.com/brave/brave-browser/issues/1736 ?

**Comment by pilgrim-brave** [comment]
Very likely.

**Comment by GeetaSarvadnya** [comment]
Click on `inspect fallback` opens up devtool.

![image](https://user-images.githubusercontent.com/38657976/63360583-40b5ba00-c38c-11e9-99f4-bc01de577860.png)

**Comment by rebron** [comment]
We want to re-enable this by proxy. Does this sound ok? @diracdeltas 
cc: @jumde

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/brave-remote-debugging-is-not-working/83109?u=eljuno

**Comment by gokujy** [comment]
How to Clean or upgraded profile?????

**Comment by TheBird956** [comment]
Any idea when we can get this feature back? Removing this is an absolute dealbreaker for most developers (including myself).

I feel like this was disabled for no good reason. At least let us decide if we want to download an extra package from Google but have it disabled by default.

**Comment by bsclifton** [comment]
@jumde this would be a great one for you to check out, when you have cycles 😄 (noticed you had already self-assigned). I think the big problem was that files are being fetched remotely. We can likely proxy those... and/or we could put this feature behind a flag

PR that disabled this: https://github.com/brave/brave-core/pull/790

**Comment by neuronetio** [comment]
Please re-enable remote debug :cry:

**Comment by diracdeltas** [comment]
@rebron i think we should re-enable this with proxy (sorry for the delay)

**Comment by diracdeltas** [comment]
actually enabling behind a flag would be fine if this is easier

**Comment by nicholasengleman** [comment]
I am a developer and will be switching back to chrome if there is not a way for me to re-enable this. This breaks the Lighthouse Audit for me and who knows what else. When I'm developing, I can't risk any issues coming from my tools and making debugging even more complicated.

**Comment by nicholasengleman** [comment]
This is an absolute deal breaker for any developer. Will be moving back to chrome and not recommending brave to anymore developers till we can re-enable this.

**Comment by salmankhilji** [comment]
+1. Please bring this feature back.

**Comment by bsclifton** [comment]
Taking a look at this now... I believe we'll be able to add a config flag for this (defaulted to OFF) which allows you to opt-in to the feature. I can make sure a clear log happens in case it's disabled (to make it more obvious). We'll need to have this go through security review too

**Comment by bsclifton** [comment]
Fixed! Will be in our next Nightly (1.3, which is due to ship Feb 4th). We may uplift to 1.2 if there's enough support for it and if no problems are discovered 😄

**Comment by salmankhilji** [comment]
I confirm that this works with Nightly 1.33.3 against a WebView running in React Native on a Nexus 6P device.

Thank you!

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` label per https://github.com/brave/brave-browser/issues/3199#issuecomment-567045246

**Comment by bsclifton** [comment]
Fixed in 1.2; waiting for a new BETA build before it can be tested again

**Comment by btlechowski** [comment]
Should be fixed in 1.2.30.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.2.30 Chromium: 79.0.3945.79 (Official Build) beta (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Ubuntu 18.04 LTS

Verified using test plan from brave/brave-core#4044 for this issue.

![image](https://user-images.githubusercontent.com/34715963/71364987-f6dd1a80-259d-11ea-8132-1fed82f63f40.png)

**Comment by varora1406** [comment]
Checked it at Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)
And it's not working.

Plus not able to find `Remote debugging` option in flags of Brave desktop browser

**Comment by Javalenciab90** [comment]
Checked Last version 
About Brave
v 1.59.117
- Does not work for devices, only for Web.
- Says _**Remote browser is newer than client browser. Try `inspect fallback` if inspection fails.**_

![Screenshot 2023-10-18 at 8 55 08 AM](https://github.com/brave/brave-browser/assets/56521677/7923c392-2129-449c-9a77-f8d618419332)

**Comment by vivek-np** [comment]
> Checked Last version About Brave v 1.59.117
> 
> * Does not work for devices, only for Web.
> * Says _**Remote browser is newer than client browser. Try `inspect fallback` if inspection fails.**_
> 
> ![Screenshot 2023-10-18 at 8 55 08 AM](https://user-images.githubusercontent.com/56521677/276276759-7923c392-2129-449c-9a77-f8d618419332.png)

Having the same issue..!!

**Comment by GeetaSarvadnya** [comment]
@vivek-np Please use `inspect fallback` to inspect on the webpage it should work. 

>Says Remote browser is newer than client browser. Try inspect fallback if inspection fails.

if you use same version on Desktop and Android you may not get this message above

**Comment by vivek-np** [comment]
> @vivek-np Please use `inspect fallback` to inspect the objects on the webpage it should work.
> 
> > Says Remote browser is newer than client browser. Try inspect fallback if inspection fails.
> 
> If you use same CR version on Desktop and Android you may not get this message above

i am not getting this option.
my system is Fedora linux
Please guide .
