### ISSUE TITLE
Create a 3rd-party device recognition whitelist json 

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#5642]
From something similar for 3rd-party cookies; https://github.com/brave/brave-browser/issues/5314

Need to create/implement a 3rd-party device recognition whitelist, for problematic sites where if we block 3rd-party cookies it causes issues.

~~https://community.brave.com/t/scrolling-issues-at-yahoo-com/75325/ Which was reported  device recognition was causing issues.~~

Create a .json of any problematic sites where blocking 3rd party sites can be added, avoiding the need for notifying customers they need to allow all device recognition for these specific sites. 

Similar to the https://github.com/brave/referrer-whitelist but for 3rd-party device recognition.

**Comment by rebron** [comment]
cc: @pilgrim-brave

**Comment by bsclifton** [comment]
cc: @jumde who has been looking at a different approach for fingerprint detection / avoidance

**Comment by tomlowenthal** [comment]
The issue title & summary make this sound like a list of sites where fingerprinting protections wouldn't be applied even if someone has configured their Shields settings to apply them. Is that the case, or is the goal somewhat different?

**Comment by tomlowenthal** [comment]
Closed in favor of farbling. Please reopen if there are still issues once farbling ships.
