### ISSUE TITLE
Yahoo rendering of right-hand column is breaking

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#5643]
## Description 
Visiting www.yahoo.com (US) articles, when scrolling the right-hand column is displayed will be sent to the left side. breaking reflow.

## Steps to Reproduce

   1. Visit`https://www.yahoo.com/news/shocking-act-of-road-rage-caught-on-camera-125914432.html`
   2. Ensure you have the right-hand sub-articles links.
   3. scroll down the page to watch the sub-articles links move to the left
   4. Some pages are more prone that others, Going through and browsing/scrolling through articles on the front page of www.yahoo.com will be good idea (the right-hand side is a bit variable)

## Actual result:

**Brave release: Version 0.67.125 Chromium: 76.0.3809.100 (Official Build) (64-bit)**
![brave-release-yahoo](https://user-images.githubusercontent.com/1659004/62938637-8241e480-be23-11e9-9982-bafa2877e915.png)

**Brave Nightly: Version 0.70.57 Chromium: 76.0.3809.100 (Official Build) nightly (64-bit)**
![brave-nightly-yahoo](https://user-images.githubusercontent.com/1659004/62938676-97b70e80-be23-11e9-83e6-75712dfe1f36.png)

## Expected result:
**Chrome Release**
![chrome-release-yahoo](https://user-images.githubusercontent.com/1659004/62938930-27f55380-be24-11e9-8814-4fe7d1bc659f.png)

## Reproduces how often: 
Easily (will depend on what Yahoo shows on the right-side), Sheilds on/off has no affect on it.

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes

- Can you reproduce this issue with the nightly channel?
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 
No.

**Comment by mgn2312** [comment]
I am having this same issue on Chrome.  Updated Chrome, Updated windows, reinstalled Chrome, I can't figure this out

**Comment by ryanbr** [comment]
I can't reproduce this in Brave release (1.4.96) and Brave nightly. Seems to working well now. Can you retest @mgn2312 ?
