### ISSUE TITLE
Crash when clicking on the Brave or Brave Rewards icons with `extensions-toolbar-menu` enabled

### ISSUE THREAD

**Issue by mcamou** [brave/brave-browser#5646]
## Description 

Brave crashes whenever I click on the Brave or Brave Rewards icons on the address bar. `brave://crashes` is empty.

## Steps to Reproduce

   1. Open Brave
   2. Click on the Brave or Brave Rewards icon

## Actual result:

Brave crashes

## Expected result:

Brave should not crash. The proper dialog (either the Shields dialog or the Brave Rewards dialog, depending on which icon was clicked) should show up.

## Reproduces how often: 

Happens every time

## Brave version (brave://version info)

Brave: 0.67.124 Chromium: 76.0.3809.100 (Official Build) (64-bit)
Revision: ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS: Linux
Window manager: KDE Plasma 5.16.4-0ubuntu1

```
$ lsb_release -a
LSB Version:    core-10.2019031300ubuntu1-noarch:printing-10.2019031300ubuntu1-noarch:security-10.2019031300ubuntu1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco
You                                                                                                                                                            

$ uname -a
Linux tumbolia 5.0.0-23-generic #24-Ubuntu SMP Mon Jul 29 15:36:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## Version/Channel Information:

I have not tried it on any other channels. However, it happened on the previous version I got from the https://brave-browser-apt-release.s3.brave.com PPA, possibly on even earlier versions, but I haven't been keeping track of how often it is updated. It has been happening for a few weeks now.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?

I cannot disable Brave Shields due to this issue

- Does the issue resolve itself when disabling Brave Rewards?

I cannot disable Brave Rewards due to this issue

- Is the issue reproducible on the latest version of Chrome? 

Does not apply to Chrome, this is Brave-specific functionality

**Comment by NejcZdovc** [comment]
@mcamou could you please send us crash ID from chrome://crashes/ (note that you need to upload it first). Thank you

**Comment by mcamou** [comment]
As mentioned in the issue, brave://crashes is empty (no crash information).

**Comment by NejcZdovc** [comment]
@mcamou just want to be double sure. When you say browser crashes, you mean that panel (from clicking on BAT logo) is blank or browser is closed?

**Comment by mcamou** [comment]
The browser closes completely and when restarting I get the "reopen tabs" dialog. I just did it now and restarted the browser. Here's the screenshot from `brave://crashes`:
![image](https://user-images.githubusercontent.com/87200/63521950-0d267d00-c4bd-11e9-8af5-2420705fdbac.png)

**Comment by mcamou** [comment]
Right now I just started it up from the terminal and made it crash. Here's the complete stdout:

```
$ brave-browser
[22509:22509:0822/091356.165122:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
[22509:22509:0822/091356.358689:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[1]    22477 segmentation fault (core dumped)  brave-browser
```

The two first lines come up when the browser starts, then when I clicked on the Brave Rewards icon I just got the core dump message.

**Comment by mcamou** [comment]
While this is diagnosed and hopefully fixed... is there a workaround to turn Shields on/off for specific domains without using the normal Shields popup?

**Comment by mcamou** [comment]
One more data point: I just realized that at some point I had enabled the `chrome://flags/#extensions-toolbar-menu` flag. I disabled it and now the Brave Rewards and Shields popups work correctly, so the issue is related to that.

**Comment by NejcZdovc** [comment]
@mcamou thank you very much for this details, we will investigate

**Comment by Brave-Matt** [comment]
I can confirm and reproduce that, when the `#extensions-toolbar-menu` flag is enabled, attempting to access either Shields or Rewards via icon in address bar will crash the browser. I have a +1 here and will drop in others i've seen:
https://community.brave.com/t/pressing-the-shield-button-crashes-brave/81943/3

**Comment by NejcZdovc** [comment]
+1 from https://github.com/brave/brave-browser/issues/5619

**Comment by srirambv** [comment]
Here's a crash report for investigation https://stats.brave.com/dashboard#crash/5d9898980a9f46001fbeccab

**Comment by Mhowser** [comment]
I have the same crash when the aforementioned flag is enabled. Zorin OS 15 with latest stable version.
![image](https://user-images.githubusercontent.com/24195572/66699776-65e4eb80-ec9e-11e9-91db-d7310980fdf9.png)

**Comment by JMK19** [comment]
Same error when `chrome://flags/#extensions-toolbar-menu` is enabled

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.81 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4065
Tested on Brave Shields button and Rewards button.
