### ISSUE TITLE
Fix adblock-rust social blocking

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#5651]
Nightly, Dev, Beta, and probably Release RC1 has an issue where the social blocking options in settings are not respected and they are always allowed. 

To test you can go to this site:
https://fmarier.github.io/brave-testing/social-widgets.html

Turning down the shields should work like 0.67.x does.

**Comment by kjozwiak** [comment]
Example of breakage can be found via https://github.com/brave/brave-browser/issues/5603 if QA needs a reference.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.68.130 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

* Verified STR from https://github.com/brave/brave-browser/issues/5603
