### ISSUE TITLE
Add support for Japan to ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#5656]
Add support for Japan to ads

**Comment by LaurenWags** [comment]
`QA/Blocked` until there are ad campaigns available for this region.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.70.113 Chromium: 77.0.3865.90 (Official Build) beta （64 ビット）
-- | --
変更履歴 | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS バージョン10.13.6（ビルド17G5019）

* Verified enabling Rewards on fresh install for Japan locale enabled Ads
<img width="1184" alt="Screen Shot 2019-10-11 at 17 57 49" src="https://user-images.githubusercontent.com/28145373/66687857-42944f00-ec52-11e9-8bcd-b54b50a0ab9a.png">

* Verified upgrading from 0.69.135 with Rewards on and was not prompted via BAT logo notification to alert user that Ads have arrived. Ads were on by default. Logged #6449
* Verified Japan ad catalog was downloaded
* Verified untargeted Ad notifications were served
* Verified `view`, `click`, `dismiss`, `landed` in `confirmations.json`.
* Verified was able to redeem tokens with the server.

**Comment by LaurenWags** [comment]
Removing from release notes as this is covered under #5655
