### ISSUE TITLE
Disable "translate this page" popup in Tor mode too

### ISSUE THREAD

**Issue by rulatir** [brave/brave-browser#5657]
I unchecked "Offer to translate pages in this language" (note: this is a back-translation of the UI string from Polish, the English original may be slightly different) for every content language added in settings.

I have also disabled the global setting, "Offer to translate pages in foreign languages" (also backtranslated).

These settings are ignored in Tor mode. The request is simple: make them NOT ignored in Tor mode. The "Install Google Translate extension to translate this page?" popup is a persistent annoyance.

**Comment by bsclifton** [comment]
cc: @yrliou

**Comment by yrliou** [comment]
Since right now we don't support extensions in Tor and we don't support setting this pref in Tor through settings page either, I think we should make this pref to be false in Tor automatically so we won't prompt users in Tor windows when they visited a page not in their language.

**Comment by yrliou** [comment]
cc @rebron per ^^

**Comment by Jamscare** [comment]
It's hard to get in,  I don't understand.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.115 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/3236
