### ISSUE TITLE
Inaccessible site menus at artstation.com

### ISSUE THREAD

**Issue by keerah** [brave/brave-browser#5658]
## Description 

The site functionality is broken,
the menu items are inaccessible even with the shields/rewards off
Update: This occurs only on one of my devices. Not sure why, its a notebook with touch and digitiser, at the same time everything is fine on my desktop

## Steps to Reproduce

   1.  Navigate to https://www.artstation.com
   2.  Click user menu, notification menu or 3dots menu and try to click an item, they behave as if they're blocked

## Actual result:

No action

## Expected result:

Supposed to navigate to

## Reproduces how often: 
constant issue

## Brave version (brave://version info)

Brave | 0.67.125 Chromium: 76.0.3809.100 (Official Build) (64-bit)
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1903 (Build 18362.295)

## Other Additional Information:

Disabling shields/rewards has no effect
Works fine in any other browser

**Comment by rebron** [comment]
@keerah Could you provide more information? As you mentioned in works fine on your desktop and this looks device specific? What are the specs for your device?

Are you navigating via touchscreen and that's why it's not working?

**Comment by keerah** [comment]
Thank you @rebron for your response, but the problem has already gone as mysteriously as it appeared. Not sure it might be the recent Brave update.

**Comment by rebron** [comment]
Good too hear. Will close this issue out then.
