### ISSUE TITLE
User feedback loop crash if ads are disabled or region is not supported

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#5659]
## Description 

User feedback loop crash if ads are disabled or region is not supported

## Steps to Reproduce

   1. Change device locale to an unsupported region
   2. Launch browser

## Actual result:

Browser crashes

## Expected result:
The browser should not crash

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 0.70.54 Chromium: 76.0.3809.100 (Developer Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3173
- Logged https://github.com/brave/brave-browser/issues/6148
