### ISSUE TITLE
brave-browser crashes with no error message (linux)

### ISSUE THREAD

**Issue by zelea2** [brave/brave-browser#5664]
## Description 

brave-browser crashes  with no error message

$ brave-browser-stable
Trace/breakpoint trap
$ brave-browser-beta
Trace/breakpoint trap

strace isn't very helpful either:
27483 --- SIGTRAP {si_signo=SIGTRAP, si_code=SI_KERNEL} ---

last successful thing before the trap was:
27483 openat(AT_FDCWD, "/proc/", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 17
27483 newfstatat(17, "self/task/", {st_mode=S_IFDIR|0555, st_size=0, ...}, 0) = 0
27483 close(17)

Starting the browser with the -no-sandbox switch works fine

The OS is debian testing with custom kernel:
$ uname -a
Linux xxx 4.14.129 #1 SMP Mon Jun 24 21:12:35 BST 2019 x86_64 GNU/Linux
$ zgrep "_\(NAME\|NS\)" /proc/config.gz | grep =y
CONFIG_NAMESPACES=y
CONFIG_USER_NS=y
CONFIG_X86_FEATURE_NAMES=y

## Brave version (brave://version info)
$ dpkg -l | grep brave-browser
ii  brave-browser                             0.67.125                             amd64        The web browser from Brave
ii  brave-browser-beta                        0.68.121                             amd64        The web browser from Brave

**Comment by fmarier** [comment]
Did you enable user namespaces before starting Brave?

On my machine, I added this to `/etc/sysctl.d/00-local-userns.conf`:

    kernel.unprivileged_userns_clone = 1

before running `sysctl -p /etc/sysctl.d/00-local-userns.conf`.

I assume that your custom kernel has that module compiled in. If not, you'll have to add it in.

**Comment by fmarier** [comment]
> $ zgrep "_(NAME|NS)" /proc/config.gz | grep =y
> CONFIG_NAMESPACES=y
> CONFIG_USER_NS=y
> CONFIG_X86_FEATURE_NAMES=y

That's interesting, you do have user namespaces enabled. The sandbox should work. Unless `kernel.unprivileged_userns_clone = 1` is another option which hasn't been enabled in your kernel.

I can think of two other things to try:

1. Try compiling it as a module and enabling it using `kernel.unprivileged_userns_clone = 1` to see whether that's any different.
2. Try installing the official Google Chrome packages and seeing if they work (to rule out any Brave-specific problems).

**Comment by zelea2** [comment]
$ sysctl -w kernel.unprivileged_userns_clone=1
sysctl: cannot stat /proc/sys/kernel/unprivileged_userns_clone: No such file or directory

Isn't that /proc/sys/kernel/ entry specific to Debian compiled kernels? My kernel is plain vanilla but as I stated above the namespaces  are compiled and enabled. I Haven't tried to compile them as modules yet. Maybe when I'll do the next kernel upgrade.

**Comment by fmarier** [comment]
> Isn't that /proc/sys/kernel/ entry specific to Debian compiled kernels?

It's not just in Debian, it's also available in Fedora 29:

```
[francois@fedora29 ~]$ cat /proc/sys/kernel/unprivileged_userns_clone
1
```
