### ISSUE TITLE
rename instances of "People"/"Person" to "Profile"

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#5665]
## Description 
Change instances of People/Persons to Profile.
1) For the menu on macOS, menu item should be relabeled Profile.
2) 'Add person' should be changed to 'Create a New Profile'.

Example:

<img width="322" alt="Screen Shot 2019-08-14 at 10 13 23 PM" src="https://user-images.githubusercontent.com/2602313/63068335-c9da7600-bee0-11e9-98da-2a815acaa9fa.png">

**Comment by rebron** [comment]
related: https://github.com/brave/brave-browser/issues/5213

**Comment by petemill** [comment]
I'm also guessing we also want to migrate anyone's existing profile with the default name of 'Person 1' to 'Profile 1'. There is existing code in place to do this from the older chromium versions:
> ```js
>   // Migrate any legacy default profile names ("First user", "Default Profile")
>   // to new style default names ("Person 1").
> ```

**Comment by rebron** [comment]
Yes, migrate existing Person 1 to Profile 1.

**Comment by Xyncgas** [comment]
No I don't think you need to switch to profile
Then brave will be the same as google chrome
I like the way this is so it gives me a feeling that brave is not storing some account as applicable "profiles" in the cloud.fogs and instead keeping things local like person A and person B

**Comment by petemill** [comment]
Migration of existing profiles is addressed with https://github.com/brave/brave-browser/issues/5814

**Comment by LaurenWags** [comment]
@rebron This is how the macOS menu looks on 0.69.132:
<img width="1126" alt="Screen Shot 2019-10-07 at 5 37 37 PM" src="https://user-images.githubusercontent.com/28145373/66350535-91c44200-e929-11e9-886b-a22a4419fe27.png">

This is on 0.70.109:
<img width="1182" alt="Screen Shot 2019-10-07 at 5 38 55 PM" src="https://user-images.githubusercontent.com/28145373/66350545-9852b980-e929-11e9-9483-a9f448a67b19.png">

Menu item was renamed to Profile as per the description, but `Add Person` was not changed to `Create a New Profile`. Is this ok?

**Comment by rebron** [comment]
Just 'Add Profile...' is fine. macOS only and will be one less issue for l10n.

**Comment by LaurenWags** [comment]
Verified passed with `macOS x64 10.13.6` using

Brave | 0.70.109 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified for both clean and upgrade profiles.

cc @kjozwiak for a second check on macOS

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.70.116 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

* Verified the STR/Case outlined under https://github.com/brave/brave-browser/issues/5665#issue-480844327
* Verified using both clean and updated profiles and ensured that `Profiles` was being used instead of `People/Person`.
