### ISSUE TITLE
Feature request : add version re-rolling in about page

### ISSUE THREAD

**Issue by Xyncgas** [brave/brave-browser#5669]
It would be nice to have the option to re-roll to the previous version if anything goes wrong or the user doesnt like where brave is going, and can let the user to have the option to pause download, even to join in for future update or security alerts if they would like or maybe let them to have the ability to select versions/branches of the brave browser to continue on

**Comment by rebron** [comment]
Hi @Xyncgas. Thanks for the suggestion. If you have suggestions for features please start out at community.brave.com. We need to keep our github issues/stories specific, actionable and something that makes sense for our users. 

Closing and marking wontfix.

**Comment by Xyncgas** [comment]
Thank you
