### ISSUE TITLE
Add a switch to disable Brave Wallet

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#5673]
Add a switch in preferences alongside the IPFS and WebTorrent one to disable Brave Wallet functionality. This will prevent it from being loaded and even installed if one navigates to brave://wallet.

If you disable it should not show the option in the hamburger menu for the wallet. It should also fail to load if you go direct to brave://wallet, it should say blocked.

There's a distinction that's important to understand between enabled and installed.

By default Brave rewards is enabled (and can be installed implicitly by selecting the menu item or by navigating to brave://wallet).  If you do a new profile and go directly to settings, you'll see it enabled, because the functionality is available. 
You can disable right away on a new profile, in which case the hamburger menu won't be available and requests will be blocked.

**Comment by kjozwiak** [comment]
@bbondy @ryanml is this the same as the switch that's currently available in the `0.69.x` release via `brave://settings`? Example:

<img width="699" alt="Screen Shot 2019-10-03 at 9 23 05 PM" src="https://user-images.githubusercontent.com/2602313/66174636-06466a80-e624-11e9-9241-68b626c9dee9.png">

When enabling/disabling the above, it will remove `Crypto Wallets` from the hamburger menu but won't remove the header button via `brave://settings`.

If this is different, can we get a test plan? Thanks!

**Comment by PaulRBerg** [comment]
A suggestion for MetaMask users: automatically set "Crypto Wallet" to false. I was debugging my dapp and I thought there was a problem with my code but there were just too many web3 providers.

**Comment by kjozwiak** [comment]
@PaulRBerg we're discussing how to handle the above better when MM is also installed. CCing @tomlowenthal.

**Comment by LaurenWags** [comment]
`QA/Blocked` pending response to https://github.com/brave/brave-browser/issues/5673#issuecomment-538191262

**Comment by kjozwiak** [comment]
Talked to @bbondy re: the above. This already landed in `0.69.x` as per https://github.com/brave/brave-browser/issues/5673#issuecomment-538191262.
