### ISSUE TITLE
Misplaced page elements on theguardian.com

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#5675]
Original report: https://community.brave.com/t/messes-up-top-menu-strange-indenting-or-paragraphs-and-site-wont-load/75254

Note: theguardian.com is a verified publisher

## Steps to Reproduce

Note: the reproducibility of this issue depends on viewport size.

   1. Open `https://www.theguardian.com/uk/lifeandstyle`
   2. Resize browser window (I resized to 1116x543)
   3. Click `More` in the top navigation bar few times.
   4. Repeat 2 and 3

![theguardian](https://user-images.githubusercontent.com/34715963/63103487-897d0580-bf7d-11e9-87dc-d0dcfda43d03.gif)

Note: turning off shields didn't fix the issue

## Actual result:

the text in the menu overlaps
![image](https://user-images.githubusercontent.com/34715963/63103535-a3b6e380-bf7d-11e9-95fd-938c28736140.png)

## Expected result:
The text in the menu does not overlap
![image](https://user-images.githubusercontent.com/34715963/63103862-322b6500-bf7e-11e9-870d-ee77d611691f.png)

## Reproduces how often: 

Depends on viewport resolution. 

## Brave version (brave://version info)

Brave | 0.68.129 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

Brave | 0.71.5 Chromium: 76.0.3809.100 (Official Build) nightly (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

Not reproducible in Chrome: 76.0.3809.100 (Official Build) (64-bit)

cc @brave/legacy_qa @ryanbr

**Comment by ryanbr** [comment]
I wonder if its similar to reflow breakage reported on yahoo https://github.com/brave/brave-browser/issues/5643

**Comment by ryanbr** [comment]
Hey @btlechowski I just re-tested in Brave-Release 1.4.96, seems to be better? Also tested in Nightly (which seemed to have smoother reflow). Has it been fixed?

**Comment by ryanbr** [comment]
Closing ticket, site renders fine in Brave release.

**Comment by btlechowski** [comment]
Thanks @ryanbr. Looks good.

Verification passed on

Brave | 1.12.82 Chromium: 84.0.4147.68 (Official Build) beta (64-bit)
-- | --
Revision | e7b7234037639b407e69c5428c891ce018cd6c0d-refs/branch-heads/4147@{#772}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

![image](https://user-images.githubusercontent.com/34715963/87142243-8f21bf00-c2a4-11ea-97a0-f6dfa15d5894.png)
