### ISSUE TITLE
Scrolling while loading causes page contents to become unanchored

### ISSUE THREAD

**Issue by stefanmendoza** [brave/brave-browser#5676]
## Description 

Scrolling while loading allows the page contents to become unanchored.

## Steps to Reproduce

1. Start at a webpage
2. Attempt to navigate to another webpage
3. Start scrolling immediately when you click to navigate to another webpage
4. The page will become unanchored and will allow scrolling past the page both above and beyond. This also seems to carry over when navigating to other websites once one page has become unanchored unless you refresh.

## Actual result:

<img width="1680" alt="Screen Shot 2019-08-15 at 11 17 23 AM" src="https://user-images.githubusercontent.com/6325996/63109399-bf56c580-bf4e-11e9-860b-ee20691dd849.png">

## Expected result:

You can't scroll past the top of the page and you can't scroll past the bottom of the page.

## Reproduces how often: 

Frequently.

## Brave version (brave://version info)

```

Brave | 0.67.125 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X
JavaScript | V8 7.6.303.29
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=NewExtensionUpdaterService --disable-features=AutofillServerCommunication,AudioServiceOutOfProcess,DefaultEnableOopRasterization,NetworkService,UnifiedConsent,LookalikeUrlNavigationSuggestionsUI,TranslateUI --flag-switches-begin --flag-switches-end
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? **N/A**
- Can you reproduce this issue with the beta channel? **N/A**
- Can you reproduce this issue with the dev channel? **N/A**
- Can you reproduce this issue with the nightly channel? **N/A**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **No.**
- Does the issue resolve itself when disabling Brave Rewards? **Not enabled.**
- Is the issue reproducible on the latest version of Chrome? **N/A**

## Miscellaneous Information:

N/A

**Comment by rebron** [comment]
We'll need to retest on Chrome. @stefanmendoza Not applicable in Chrome?

**Comment by stefanmendoza** [comment]
@rebron I only use Brave 😁 

I'll download Chrome and try to test this out. 👍

**Comment by bsclifton** [comment]
@stefanmendoza thanks for the update - are you still experiencing this with the latest version (0.68.132?)

**Comment by matmunn** [comment]
I still have this problem in version 0.68.139.

![image](https://user-images.githubusercontent.com/65853/65288099-f2612a00-db88-11e9-9bdf-3c75c792398f.png)

**Comment by stefanmendoza** [comment]
I started seeing this again, but it's not as consistent.
