### ISSUE TITLE
Options in the download bar being whited out

### ISSUE THREAD

**Issue by MagicalDrizzle** [brave/brave-browser#5681]
## Description 
When download a file, options in the download bar will have a solid white color.

## Steps to Reproduce

   1. Initiate a download.

## Actual result:

![downloadbar](https://user-images.githubusercontent.com/49761211/63116614-48f4aa80-bfc4-11e9-90c7-124e5a378e64.jpg)

## Expected result:
Options should show normally.
![dbar2](https://user-images.githubusercontent.com/49761211/63116628-527e1280-bfc4-11e9-8ab3-c343b87ffd1c.jpg)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave: 0.67.125 Chromium: 76.0.3809.100 (Official Build) (32-bit)
Revision: ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS: Windows 7 Service Pack 1 (Build 7601.24417)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

Every options on the download bar will be whited out. If I download a theme, the "discard" option will be whited out along with the "show all" option.

**Comment by diposs** [comment]
Problem Fixed 
Brave version (brave://version info)
Brave
 0.68.130 Chromium: 76.0.3809.100 (Official Build)
![Screenshot (85)](https://user-images.githubusercontent.com/23644736/63220416-df6ccb80-c17e-11e9-9e18-07937e4102fc.png)

**Comment by GeetaSarvadnya** [comment]
could be same as #3381

**Comment by rebron** [comment]
@srirambv for linux @btlechowski for windows 7 Can you guys take a look to see if this is fixed?

**Comment by MagicalDrizzle** [comment]
The issue returns in Brave 0.68.131:
![Untitled](https://user-images.githubusercontent.com/49761211/63651298-6d4b4680-c77d-11e9-88bd-e4f8097c1958.png)

**Comment by bsclifton** [comment]
cc: @simonhong

**Comment by simonhong** [comment]
Hmm, there was no theme related changed in `0.68.x`. I think this is regression from upstream change. looking at it.

**Comment by srirambv** [comment]
Don't see any theme issue on Linux running `0.68.132`

**Comment by MagicalDrizzle** [comment]
Not reproducible on 0.69.128. I'll close the issue for now.
