### ISSUE TITLE
Tipping a user's likes on Twitter results in incorrect username in tweet message

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#5685]
## Steps to Reproduce

1. Visit twitter.com/brave/likes
1. Click tip button on any Tweet
1. Click the Tweet button after tipping

## Expected result

>I just tipped `@correctuser` using the Brave Browser. Check it out at https://brave.com/tips. #TipWithBrave

## Actual result

>I just tipped `@likes` using the Brave Browser. Check it out at https://brave.com/tips. #TipWithBrave

Reported by @jonathansampson. Also occurs with twitter.com/brave/with_replies and twitter.com/brave/media, so we should handle all of these properly.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.34 Chromium: 86.0.4240.99 (Official Build) nightly (x86_64)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Verified STR from description for:
- https://twitter.com/brave/with_replies
- https://twitter.com/brave/media
- https://twitter.com/brave/likes

Note - need to be logged in to Twitter to access the above pages.

Confirmed after clicking on an in-line tip button for a tweet on each page and tipping that tweet, when I clicked on the Twitter icon from the tipping banner, the canned tweet was pre-populated correctly.

<details>
<summary>Screenshots</summary>
<img width="622" alt="Screen Shot 2020-10-15 at 2 39 49 PM" src="https://user-images.githubusercontent.com/28145373/96172962-26765e00-0ef5-11eb-9d3f-cea6fa35a378.png">
<img width="632" alt="Screen Shot 2020-10-15 at 2 42 34 PM" src="https://user-images.githubusercontent.com/28145373/96172973-29714e80-0ef5-11eb-8e86-55ce7eed6ad9.png">
<img width="625" alt="Screen Shot 2020-10-15 at 2 41 33 PM" src="https://user-images.githubusercontent.com/28145373/96172976-2aa27b80-0ef5-11eb-9228-7521da4a93ad.png">

</details>
