### ISSUE TITLE
Localization not working with Brave Wallet.

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#5686]
Things are not being translated per one report on Slack.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

* Verified text coming from MM is translated
* Logged #6289 for custom text not being translated
