### ISSUE TITLE
sometimes generic world favicon displayed instead of generic reddit favicon

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5687]
## Description 
Sometimes the generic "world" favicon is displayed in the panel instead of the generic reddit favicon.

Maybe similar/related to https://github.com/brave/brave-browser/issues/4016 - unsure.

## Steps to Reproduce

1. Clean profile.
2. Enable Rewards
3. I visited https://www.reddit.com/u/jsadler-brave, opened the panel. Verified correct info.
4. Closed panel.
5. Clicked on `alex_the_brave` link on jason's page
6. Opened panel from alex's page.. 

## Actual result:

![Screen Shot 2019-08-16 at 9 24 26 AM](https://user-images.githubusercontent.com/28145373/63173074-17ec9800-c00d-11e9-855b-de0940ffac8f.png)

## Expected result:

![Screen Shot 2019-08-16 at 9 52 15 AM](https://user-images.githubusercontent.com/28145373/63173086-2044d300-c00d-11e9-822f-be87d74accb0.png)

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.68.130 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? released 0.67.x no, RC 0.68.x yes
- Can you reproduce this issue with the beta channel? 0.69.x yes
- Can you reproduce this issue with the dev channel? unsure but probably
- Can you reproduce this issue with the nightly channel? unsure but probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
@kjozwiak and @GeetaSarvadnya reproduce

**Comment by NejcZdovc** [comment]
this happens if reddit page didn't finis loading. So if you see this, wait for page to finish loading and then open panel again. We can't really do anything about it except of having static assets. This behaviour  is the same for every site, not just reddit
