### ISSUE TITLE
Session restore shows brave://wallet as a blank page

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#5688]
If you leave brave://wallet open then close and open the browser, it only loads a blank page. You have to refresh and then it works.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.109 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Verified test plan from the description. 
Verified for initial `brave://wallet` page.
Verified `brave://wallet` for already created wallet.
