### ISSUE TITLE
Add key for brave services

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#5690]
## Description 
Requests to brave services will use the brave services key

**Comment by kjozwiak** [comment]
@jumde assuming this should be labelled as `QA/Yes` as there's a test case outlined in https://github.com/brave/brave-core/pull/3198#issue-308171434?

**Comment by jumde** [comment]
Updated the label @kjozwiak

**Comment by btlechowski** [comment]
Verified passed with

Brave | 1.2.8 Chromium: 78.0.3904.108 (Official Build) dev (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3198
Verified `BraveServiceKey` for following domains
`https://static1.brave.com`
![image](https://user-images.githubusercontent.com/34715963/69433116-4e882c00-0d3b-11ea-8753-f7315d32962a.png)
`https://crlsets.brave.com`
![image](https://user-images.githubusercontent.com/34715963/69433226-842d1500-0d3b-11ea-8b04-2754c6e5ab2d.png)
`https://crlsets.brave.com` en-us-8-0.bdic - does not have BraveServiceKey
![image](https://user-images.githubusercontent.com/34715963/69433316-ade63c00-0d3b-11ea-8c17-1a64148e7bed.png)
`https://laptop-updates.brave.com` - does not have it
![image](https://user-images.githubusercontent.com/34715963/69433518-04ec1100-0d3c-11ea-88b0-7824d0d3200d.png)
`https://static.brave.com`
![image](https://user-images.githubusercontent.com/34715963/69433599-2e0ca180-0d3c-11ea-8b96-1d878347b4ca.png)
`https://go-updater.brave.com`
![image](https://user-images.githubusercontent.com/34715963/69433671-4c729d00-0d3c-11ea-85f6-8670120e3a5b.png)
`https://componentupdater.brave.com`
![image](https://user-images.githubusercontent.com/34715963/69433708-68763e80-0d3c-11ea-953b-4c076371ed43.png)
`https://brave-core-ext.s3.brave.com`
![image](https://user-images.githubusercontent.com/34715963/69433778-8fcd0b80-0d3c-11ea-88f1-623a07314161.png)
`https://p3a.brave.com`
![image](https://user-images.githubusercontent.com/34715963/69433868-c0ad4080-0d3c-11ea-97b6-e05e2134afef.png)
`https://safebrowsing.brave.com`
![image](https://user-images.githubusercontent.com/34715963/69433909-d4f13d80-0d3c-11ea-8fb1-710c1dd94dff.png)
`https://ads-serve.brave.com`  - does not have it
![image](https://user-images.githubusercontent.com/34715963/69434106-4204d300-0d3d-11ea-98d6-772429370c6b.png)
