### ISSUE TITLE
Freeze on alt+tab

### ISSUE THREAD

**Issue by champsilva** [brave/brave-browser#5692]
<!-- Have you searched for similar issues? Before submitting this issue, please check the open issues and add a note before logging a new issue. 

## Description 
When alt tab, and back to Brave create a freeze for a couple of seconds. 

## Steps to Reproduce

   1. Open Brave and open a couple tabs
   2. Alt+tab for another program, ie: Photoshop
   3. Back to Brave

## Expected result:
Small freeze.

## Reproduces how often: 
Everyday

## Brave version (brave://version info)

Brave | 0.67.125 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1903 (Build 18362.239)

**Comment by rebron** [comment]
Closing. Please use the template when creating issues.
