### ISSUE TITLE
New yubikeys don't work with stable version

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#5697]
## Description 
Upstream fix here: https://chromium-review.googlesource.com/c/chromium/src/+/1757608

## Steps to Reproduce
   1.  Use the new YubiKeys to register/authenticate with GitHub

Also see https://github.com/brave/brave-core/pull/3199

## Actual result:
Fails

## Expected result:
Should succeed

## Reproduces how often: 
Easily

## Brave version (brave://version info)
Version 0.67.125 Chromium: 76.0.3809.100 (Official Build) (64-bit)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.122 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

<img width="1144" alt="Screen Shot 2019-09-03 at 11 56 16 PM" src="https://user-images.githubusercontent.com/2602313/64224821-fada1500-cea6-11e9-8545-fbb6bc4f9a1b.png">

<img width="772" alt="Screen Shot 2019-09-03 at 11 56 22 PM" src="https://user-images.githubusercontent.com/2602313/64224822-fdd50580-cea6-11e9-9ebb-9e0015d2f496.png">

* Went through verification using the outlined test case via https://github.com/brave/brave-browser/issues/5697#issue-481736831
* Went through verification using the outlined test case via https://github.com/brave/brave-core/pull/3199
* Added/Registered a new `yubikey` that's running `FW >= 5.2.3` via GH without issues
* Used the newly registered/added `yubikey` to login into GH without any issues
