### ISSUE TITLE
support restoring from metamask words in crypto-wallet

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#5698]
it should have an option for restore from metamask

**Comment by bbondy** [comment]
@diracdeltas are you working on this one?

**Comment by diracdeltas** [comment]
@bbondy haven't gotten around to it yet but i will today

**Comment by kjozwiak** [comment]
This isn't working correctly. Restoring a `12 word` seed phrase from MM really screws up `brave://wallet` and puts it into an unstable state. Example:

<img width="1162" alt="Screen Shot 2019-10-02 at 5 55 00 PM" src="https://user-images.githubusercontent.com/2602313/66085119-58ad5b80-e53e-11e9-9065-eb49b2fa7e27.png">

<img width="564" alt="Screen Shot 2019-10-02 at 5 55 40 PM" src="https://user-images.githubusercontent.com/2602313/66085129-619e2d00-e53e-11e9-9f1a-0d2e18cc7459.png">

Once you're in the above state, `brave://wallets` doesn't load correctly at times. Some of the buttons completely stop working so you can't even restore another wallet. If someone attempts to restore a MM seed phrase, they'll basically put `brave://wallet` into a bad state/unusable state.

**Comment by kjozwiak** [comment]
@diracdeltas I don't think this is working as per https://github.com/brave/brave-browser/issues/5698#issuecomment-537727121. Current version of MM generates a `12 word` seed but our UI mentions that it's not `16 words` after you try importing:

<img width="735" alt="Screen Shot 2019-10-02 at 8 23 47 PM" src="https://user-images.githubusercontent.com/2602313/66090745-b21f8580-e552-11e9-8032-cee66a3a06a9.png">

<img width="758" alt="Screen Shot 2019-10-02 at 8 23 58 PM" src="https://user-images.githubusercontent.com/2602313/66090744-b21f8580-e552-11e9-836b-00f529eafa85.png">

**Comment by diracdeltas** [comment]
@kjozwiak got it - were you able to restore from 12 words sometimes (see https://github.com/brave/brave-browser/issues/5698#issuecomment-537727121) or not at all?

**Comment by srirambv** [comment]
@diracdeltas i was able to use the 12 words but it broke the wallet login and started showing `MetamaskController - No HD Key Tree found`

**Comment by diracdeltas** [comment]
i'll dig into this today. worst case we can change the UI back to not support metamask restoring?

**Comment by diracdeltas** [comment]
this might be broken because https://github.com/brave/eth-hd-keyring/pull/4 was never merged. @bbondy or @ryanml mind re-approving and merging it?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using https://github.com/brave/ethereum-remote-client/releases/tag/0.1.15 via the following build:

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

* created a wallet within `MM` and sent `0.0117 ETH` & `10 BAT`. Once the funds made into the wallet, restored the same wallet using the `12 word seed phrase` from `MM` into `CW` and ensured the worked as expected. Once the wallet was restored within `CW`, sent `5 BAT` into my Uphold account and ensured the transaction went through without issues.
* created a wallet within `MM` and sent `0.025 ETH` & `25 BAT`. Once the funds made into the wallet, restored the same wallet using the `12 word seed phrase` from `MM` into `CW` and ensured the worked as expected. Once the wallet was restored within `CW`, sent `10 BAT` into my Uphold account and ensured the transaction went through without issues.
* created a wallet within `MM` and sent `1 ETH` using the `Ropsten` network and `3 ETH` using the `Rinkeby` network. Once the funds made it into the wallet, restored the same wallet using the `12 word seed phrase` from `MM` into `CW` and ensured the worked as expected.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

* Sent BAT/ETH to `MM account`. Restored the same wallet in `Brave CW` and the balance was restored in `Brave CW`
* Created an empty wallet on `MM`. Restored the same wallet on Brave CW. Sent `BAT/ETH` to `MM account`, balance showed up on `Brave CW`
* Verified sending 3 BAT to uphold account was successfull on a restored `MM wallet` on `Brave CW`
