### ISSUE TITLE
[SOLVED] Malformed entry 1 - failed install - UBUNTU 19.04 

### ISSUE THREAD

**Issue by BMACCRYPTO** [brave/brave-browser#5703]
## Description 
New install Ubuntu Disco Dingo 19
I used instructions from:
https://support.brave.com/hc/en-us/articles/360018666072-How-do-I-install-Brave-on-Linux-using-the-terminal-

> 
sudo apt install apt-transport-https

curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -

source /etc/os-release

echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ $UBUNTU_CODENAME main" | sudo tee /etc/apt/sources.list.d/brave-browser-release-${UBUNTU_CODENAME}.list

sudo apt update

> 
The Result when attempting to "sudo apt update" are:
$ sudo apt update
E: Malformed entry 1 in list file /etc/apt/sources.list.d/brave-browser-release-.list (Component)
E: The list of sources could not be read.

## Steps to Reproduce

   1. sudo apt install apt-transport-https
   2. curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
   3. source /etc/os-release
   4. echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ $UBUNTU_CODENAME main" | sudo tee /etc/apt/sources.list.d/brave-browser-release-${UBUNTU_CODENAME}.list
    5. sudo apt update

## Actual result:
E: Malformed entry 1 in list file /etc/apt/sources.list.d/brave-browser-release-.list (Component)
E: The list of sources could not be read.
![Screenshot from 2019-08-16 18-38-10](https://user-images.githubusercontent.com/54191629/63202048-f5cb3800-c055-11e9-9ef3-2d2516644920.png)

## Expected result:
Install brave browser successfully

## Reproduces how often: 
Repeats every attempt.

## Version/Channel Information:
Ubuntu 16.04+ and Mint 18+
![Screenshot from 2019-08-16 18-47-16](https://user-images.githubusercontent.com/54191629/63202127-4f336700-c056-11e9-8c56-495106f3e864.png)

**Comment by BMACCRYPTO** [comment]
**I have resolved this issue:**
I received the following failure on brave browser installation attempt:
`$ sudo apt update
E: Malformed entry 1 in list file /etc/apt/sources.list.d/brave-browser-release-.list (Component)
E: The list of sources could not be read.
`
![Screenshot from 2019-08-17 15-47-20](https://user-images.githubusercontent.com/54191629/63216765-98dc8a00-c108-11e9-936d-9653328f7d9f.png)

**Resolution was achieved by the following steps:**
1.  get distro name
`$ lsb_release -sc`

2. Then clear the problem by deleting those files with malformed apt entries:
`$ sudo rm /etc/apt/sources.list.d/brave.list`

3.Add Key
`$ curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key add -`

4. Added my distro name "disco main"
`$ echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ disco main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list`

5. 
`$ sudo apt update`

6.
` $ sudo apt install brave-browser `

![Screenshot from 2019-08-17 16-04-55](https://user-images.githubusercontent.com/54191629/63216791-d4775400-c108-11e9-9ac7-a18d515e9c6d.png)

**Comment by BMACCRYPTO** [comment]
`$ sudo apt install brave-browser 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  brave-keyring
The following NEW packages will be installed:
  brave-browser brave-keyring
0 upgraded, 2 newly installed, 0 to remove and 212 not upgraded.
Need to get 72.9 MB of archives.
After this operation, 236 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://brave-browser-apt-release.s3.brave.com disco/main amd64 brave-keyring all 1.3 [3,400 B]
Get:2 https://brave-browser-apt-release.s3.brave.com disco/main amd64 brave-browser amd64 0.67.125 [72.9 MB]
Fetched 72.9 MB in 20s (3,653 kB/s)                                                                         
Selecting previously unselected package brave-keyring.
(Reading database ... 172133 files and directories currently installed.)
Preparing to unpack .../brave-keyring_1.3_all.deb ...
Unpacking brave-keyring (1.3) ...
Selecting previously unselected package brave-browser.
Preparing to unpack .../brave-browser_0.67.125_amd64.deb ...
Unpacking brave-browser (0.67.125) ...
Setting up brave-keyring (1.3) ...
OK
Setting up brave-browser (0.67.125) ...
update-alternatives: using /usr/bin/brave-browser-stable to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/brave-browser-stable to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
update-alternatives: using /usr/bin/brave-browser-stable to provide /usr/bin/brave-browser (brave-browser) in auto mode
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for gnome-menus (3.32.0-1ubuntu1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for desktop-file-utils (0.23-4ubuntu1) ...
`

**Comment by Shirshak-Ach** [comment]
Thanks! It helped
