### ISSUE TITLE
Issues on itch.io

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#5704]
## Description 
Visit `https://cnnmon.itch.io/kittyclinic` or `https://broken-arms.itch.io/vegaman` With Sheilds up (Will prevent these sites from loading correctly)

## Steps to Reproduce

   1.  Visit and let `https://cnnmon.itch.io/kittyclinic`
   2. Wait and watch for the error to generate.
   2. ![itchio](https://user-images.githubusercontent.com/1659004/63205022-527c3080-c0f2-11e9-910a-199c9a745caf.png) 
  

## Actual result:

`UnityLoader.js:4 [UnityCache] 'https://v6p9d9t4.ssl.hwcdn.net/html/1192387/KittyClinic/Build/KittyClinic.wasm.framework.unityweb' successfully downloaded but not stored in the indexedDB cache due to the error: Error: indexedDB access denied`

## Expected result:

The site to work fine with Sheilds enabled.

## Brave version (brave://version info)
Version 0.67.125 Chromium: 76.0.3809.100 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
YES
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
Yes
- Can you reproduce this issue with the nightly channel?
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
Yes
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:
Allowing all Device-recognition does fix this, can we make a work around.

Attempted to adjusted the Referrer whitelist list for "https://*.hwcdn.net/*" this didn't work.

**Comment by silbinarywolf** [comment]
I see a similar issue here with LocalStorage as well:
https://drazillion.itch.io/as-cold-as-the-grave

Currently I just have to use Chrome if I want to play itch.io games!

**Comment by ryanbr** [comment]
I don't think it was a IndexdDB issue, but my patch should help?

**Comment by ryanbr** [comment]
has been resolved, closing ticket

**Comment by ryanbr** [comment]
Okay, not quite.

**Comment by ryanbr** [comment]
Okay, confirmed, each of the test sites are now working. closing.
