### ISSUE TITLE
Brave shields: Script blocking doesn't remember selections permanently

### ISSUE THREAD

**Issue by snives** [brave/brave-browser#5705]
## Description 
Using Brave Shields, enabling script blocking, and then selecting the mix of scripts I wish to allow, does not permanently remember this selection for this website.  In effect, the site is broken without enabling a certain set of scripts, thus because brave only remembers these settings "one time", the site will always be broken (unless I disable all script blocking of course, which is not what I want).

## Expectation
My expectation and desire is that it DOES remember these settings permanently for this website.

**Comment by bsclifton** [comment]
Thanks for the report, @snives - we're tracking this feature request with https://github.com/brave/brave-browser/issues/1889

I'll give it a bump on your behalf 😄 Be sure to subscribe if you would like updates
