### ISSUE TITLE
Request: Expand sync to search engines and general app settings 

### ISSUE THREAD

**Issue by ChildishGiant** [brave/brave-browser#5706]
I have lots of custom search engines and a certain setup for my browser. I think it'd fit well into the brave sync eco system for brave settings, including search engines to be synced. Other candidates for sync adoption would be extensions and maybe even brave wallets but I know that the latter is likely to never happen due to the nature of wallets.

**Comment by rebron** [comment]
We have plans to add search engines and settings in sync in a separate issue.

**Comment by killtux** [comment]
> We have plans to add search engines and settings in sync in a separate issue.

what happend to these plans? 🙂
