### ISSUE TITLE
Bug: Download manager shows nothing!

### ISSUE THREAD

**Issue by Joe23232** [brave/brave-browser#5707]
When downloading something, when I press `ctrl+j` it opens Brave's download manager but it shows nothing but if I make the window smaller and then make the window maximised again, then it shows all the previous downloads and what you are downloading.

I am running Windows 10, and I am using the dark theme.

**Comment by bsclifton** [comment]
Thanks for the report, @Joe23232!

This is a known issue which has been reported with https://github.com/brave/brave-browser/issues/5330

I haven't had time to look into a fix yet... but we have some clues (@mkarolin is working on upgrade to Chromium 77 and the issue no longer happens there). Closing this issue- you can subscribe to https://github.com/brave/brave-browser/issues/5330 for updates
