### ISSUE TITLE
Bookmark bar no longer shows on new tab page

### ISSUE THREAD

**Issue by coleberhorst** [brave/brave-browser#5708]
## Description 
In Chrome and Brave when you hid the Bookmark bar to increase viewing area, the bar still shows on a new tab page. The current change within a couple of days makes the hidden bookmark bar always hidden, rendering it useless.

This change occurs is new chrome build, so I guess this is a feature request to diverge from Chrome UI slightly.

## Steps to Reproduce

   1. Hide the bookmark bar <Ctrl> <Shft> <B>
   2. Open new tab page <Ctrl> <T>
   3. Observe lack of bookmark bar.

## Actual result:
Lack of bookmark bar

## Expected result:
Hidden bookmark bar should should in new tab page only, otherwise entire bookmark system isn't very useful when bar is hidden.

## Reproduces how often: 
Always

## Brave version (brave://version info)
```
Brave	0.68.129 Chromium: 76.0.3809.100 (Official Build) (64-bit)
Revision	ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS	Windows 10 OS Version 1903 (Build 18362.295)
JavaScript	V8 7.6.303.29
Flash	(Disabled)
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Command Line	"C:\Users\coleb\AppData\Local\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extensions-install-verification=enforce_strict --enable-features=NewExtensionUpdaterService,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,NetworkService,UnifiedConsent,TranslateUI --flag-switches-begin --flag-switches-end
Executable Path	C:\Users\coleb\AppData\Local\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\coleb\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
```

## Version/Channel Information:
- Can you reproduce this issue with the current release?
Yes

- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
N/A, shields don't apply to new tab page.

- Does the issue resolve itself when disabling Brave Rewards?

- Is the issue reproducible on the latest version of Chrome? 
Yes

**Comment by bsclifton** [comment]
Thanks for the report @coleberhorst! We already have this captured with https://github.com/brave/brave-browser/issues/4782 and @simonhong is working on a fix (which you can check out here: https://github.com/brave/brave-core/pull/2869)

Closing as duplicate
