### ISSUE TITLE
New tab page has an extraneous zero

### ISSUE THREAD

**Issue by cndouglas** [brave/brave-browser#5710]
## Description 
On the new tab page, there is an extraneous zero between the stats and time.

It seems to be a part of the stats section because turning off "Show Brave Stats" makes the zero disappear.

## Steps to Reproduce
   1. Open a new tab. You may want to disable the background image to see the zero easier.

## Actual result:
![](https://user-images.githubusercontent.com/19424103/63231895-e4199a00-c1e7-11e9-8da4-147820315e51.png)

## Expected result:
There shouldn't be an extraneous zero.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
Brave | 0.71.15 Chromium: 76.0.3809.100 (Official Build) nightly (64-bit)
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

## Version/Channel Information:
- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? Yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Not applicable.
- Does the issue resolve itself when disabling Brave Rewards? Not applicable.
- Is the issue reproducible on the latest version of Chrome? Not applicable.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.112 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3297

![image](https://user-images.githubusercontent.com/34715963/66789130-85705400-eeea-11e9-8569-94d543afa7b0.png)
