### ISSUE TITLE
[Feature request] Option to bookmark all tabs

### ISSUE THREAD

**Issue by kangarooo** [brave/brave-browser#5711]
## Description 
Android, IOS, Windows option to bookmark all tabs.
I didn't know that cant sync bookmarks, so want to bookmark all, but currently can only one by one and then sync bookmarks on Windows Brave to export.
Needed to then at least to bookmark all tabs option so save all not to lose productivity.

## Expected result
Button under menu [Bookmark all tabs]

**Comment by bbondy** [comment]
This option exists already on Desktop browsers in the hamburger menu, go to Bookmarks, then Bookmark open pages. 

Feel free to post an issue for Android or iOS though on these repos:
https://github.com/brave/browser-android-tabs
https://github.com/brave/brave-ios

**Comment by githubmarker** [comment]
https://github.com/brave/browser-android-tabs/issues/1413

**Comment by Poopooracoocoo** [comment]
Here's the new issue #9443
