### ISSUE TITLE
Google spreadsheet keep loading("Working") on Nightly

### ISSUE THREAD

**Issue by chkk525** [brave/brave-browser#5714]
## Description 

Google Spreadsheet keep loading(saying "Working") forever in Nightly.

## Steps to Reproduce

   1. Open a google spreadsheet file (i.e. https://docs.google.com/spreadsheets/d/1YSuOsDeZDU_xSJiAJtMJ3aiSPbR8R-t9Lxh4pkGvlGc/edit#gid=0)
   2. Keep loading forever

## Actual result:

The message "処理中" says it's "Working"
![image](https://user-images.githubusercontent.com/3054915/63247752-c3f9e180-c2a0-11e9-855f-fdc707693b4f.png)

## Expected result:
- The message should disappear after  a while

## Reproduces how often: 

- Easily reproduced

## Brave version (brave://version info)

Brave | 0.71.15 Chromium: 76.0.3809.100 (Official Build) nightly （64 ビット）
-- | --
変更履歴 | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X
JavaScript | V8 7.6.303.29

## Version/Channel Information:

- Can you reproduce this issue with the current release?
No
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
Couldn't replicate this. https://secure.fanboy.co.nz/gif/googledocs.gif  (with a few refreshes) 

Tested in Version 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)

**Comment by chkk525** [comment]
It seems ok now. Thank you!

**Comment by chkk525** [comment]
@ryanbr I re-opened this as it should be working without refreshes like in Chrome or Brave Release build. Could you please dig into this issue again?

**Comment by ryanbr** [comment]
@chkk525 is this still an issue? (test in Brave beta also?)

**Comment by rebron** [comment]
Closing as stale. I'm not able to reproduce in latest version.
