### ISSUE TITLE
Top banner area unexpectedly removed on viz.com on Nightly

### ISSUE THREAD

**Issue by chkk525** [brave/brave-browser#5715]
## Description 

- Top banner is removed in viz.com

## Steps to Reproduce

   1. Open https://www.viz.com/

## Actual result:

![image](https://user-images.githubusercontent.com/3054915/63248999-85b1f180-c2a3-11e9-853b-5b729e88a896.png)

## Expected result:
- The page should be like on Chrome

## Reproduces how often: 

- Easily reproduced

## Brave version (brave://version info)

Brave	0.71.15 Chromium: 76.0.3809.100 (Official Build) nightly （64 ビット）
変更履歴	ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS	Mac OS X
JavaScript	V8 7.6.303.29
Flash	（無効）
ユーザー エージェント	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
コマンドライン	/Applications/Brave Browser Nightly.app/Contents/MacOS/Brave Browser Nightly -psn_0_57358 --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-features=NewExtensionUpdaterService,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,NetworkService,UnifiedConsent --flag-switches-begin --load-media-router-component-extension=1 --flag-switches-end --restore-last-session
実行ファイルのパス	/Applications/Brave Browser Nightly.app/Contents/MacOS/Brave Browser Nightly
プロフィール パス	/Users/chikaki/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/Profile 1
バリエーション	d74ef32b-f693abd7

## Version/Channel Information:

- Can you reproduce this issue with the current release?
No 
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by ryanbr** [comment]
Just tested this; https://secure.fanboy.co.nz/gif/viz.gif

Brave on Left, Chrome on right. Seems okay?

Tested in: Version 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)

**Comment by chkk525** [comment]
@ryanbr thank you. It seems okay!
