### ISSUE TITLE
Brave browser blocks screen saver when not minimized

### ISSUE THREAD

**Issue by GaWdLy1** [brave/brave-browser#5716]
## Description 
If the Brave browser is left maximized, screensaver will not trigger, screens will not sleep. It doesn't seem to matter what tab is visible-if I do not minimize, my screens never sleep.

## Steps to Reproduce

   1. Fail to minimize
   2. Wait <time> for screensaver to kick in
   3. No screensaver
   4. Minimize Brave
   5. Screensaver kicks in

## Actual result:
Screensaver does not turn on and screens do not sleep

## Expected result:
After <time>, expect screensavers to engage, and screens to eventually sleep

## Reproduces how often: 
Any time Brave is not minimized. Not reproducible on Chrome.

## Brave version (brave://version info)
Version 0.67.125 Chromium: 76.0.3809.100 (Official Build) (64-bit)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
   - Not tested, but assume this is unrelated
- Does the issue resolve itself when disabling Brave Rewards?
   - Not tested, but assume this is unrelated
- Is the issue reproducible on the latest version of Chrome? 
   - No

**Comment by rebron** [comment]
@GaWdLy1 Can you tell us what OS and version you're running?

**Comment by GaWdLy1** [comment]
$ cat /etc/redhat-release 
Fedora release 30 (Thirty)

Note that I have also reproduced this with some success on Windows 10. Though not as regularly as with my Fedora box. That is reproducible 100% of the time. If Brave has focus, my monitors will stay on and never go to sleep.

**Comment by GaWdLy1** [comment]
Update:

I updated and relaunched Brave tonight, and this problem appears to have possibly been resolved. The relaunched version is:

Version 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)

Will close the bug if the problem does not re-appear.

-SR

**Comment by GaWdLy1** [comment]
I am closing this issue for now. I saw the screens hang for a few hours once, but that seemed to be linked to a GIF on a twitter page. I will re-open if the issue re-occurs.

-SR
