### ISSUE TITLE
Don't see the URL in URL bar when I do google search

### ISSUE THREAD

**Issue by mikhoul** [brave/brave-browser#5718]
## Description 

Don't see the URL in URL bar when I do google search

## Steps to Reproduce

   1.   Make sure you have Google as default search engine
   2. Enter `île de Grande Canarie` in the url bar to search and press enter
   3.  Look in the URL bar you don't see the real URL but only the search query.

## Actual result:

![image](https://user-images.githubusercontent.com/5678673/63265667-24b2fb00-c25c-11e9-81e8-cd7405727c99.png)

With another search query it's the same result:

![image](https://user-images.githubusercontent.com/5678673/63265593-fcc39780-c25b-11e9-9486-0de3d035a599.png)

## Expected result:

See the real URL and not the search term.

## Reproduces how often: 

Every time

## Brave version (brave://version info)

![image](https://user-images.githubusercontent.com/5678673/63265511-c7b74500-c25b-11e9-85d4-1f4a52461518.png)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome?  IDK

**Comment by rebron** [comment]
@mikhoul Can you try again with the latest version? You can upgrade from here: chrome://settings/help
This should be fixed in version 68.x.

**Comment by mikhoul** [comment]
It work fine with the latest version.
