### ISSUE TITLE
Cryptowallets should not be allowed to work on Tor Windows

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5723]
## Description 

Cryptowallets should not be allowed to work on Tor Windows

## Steps to Reproduce

   1. Install Dev/Nightly build
   2. Create a crypto wallet in normal window
   3. Open Tor window, type in brave://wallet, opens wallet creation page and you are able to create a second wallet on tor windows

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/63287196-c13ec280-c287-11e9-9c98-0e813943bc10.png)

## Expected result:
Should not allow creating a wallet on Tor window similar to Private/Guest window

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.70.68 Chromium: 76.0.3809.100 (Official Build) dev (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

cc: @bbondy

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.70.109 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- The original issue is reproduced in 0.70.68
![image](https://user-images.githubusercontent.com/38657976/66335954-b801d600-e959-11e9-8132-2a37bf127a93.png)
- Verified the STR from the description, brave://wallet is blocked in TOR tabs now.
![image](https://user-images.githubusercontent.com/38657976/66336017-da93ef00-e959-11e9-9c4b-cba2a673b5b7.png)
