### ISSUE TITLE
seek (forward or backward) on vimeo video messes up entire AC table

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5725]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/4017

If you watch a vimeo video normally, your AC table is fine. However, if you start seeking (forward or backward), the AC table gets really messed up.

## Steps to Reproduce

1. Clean profile on 0.68.x
2. Enable Rewards (keep this open in one window)
3. Open a second window and visit some sites - a mix: regular sites, youtube videos, etc.
4. Watch a vimeo video. See it added to AC table. Note its percentage. If you check `publisher_info_db` at this point, you see normal values for duration, score, etc.
![Screen Shot 2019-08-19 at 1 59 25 PM](https://user-images.githubusercontent.com/28145373/63288711-6018ee00-c28b-11e9-8ce5-abd49d711257.png)

5. Once it's added to the table, move the slider bar forward (essentially fast forwarding the video)
6. See the % for vimeo video increased on brave://rewards page without actually watching since you fast forwarded. This shouldn't happen.
![Screen Shot 2019-08-19 at 1 59 54 PM](https://user-images.githubusercontent.com/28145373/63288718-66a76580-c28b-11e9-96d5-3ee9da10b2bc.png)

7. Move slider bar close to the beginning of the video. See vimeo video removed from AC table. If you check `publisher_info_db` at this point, you could see a negative value for duration (depending on how much of the video you had watched). This shouldn't happen.

![Screen Shot 2019-08-19 at 2 00 07 PM](https://user-images.githubusercontent.com/28145373/63288734-7626ae80-c28b-11e9-95d7-5b029492c56b.png)

![Screen Shot 2019-08-19 at 2 00 53 PM](https://user-images.githubusercontent.com/28145373/63288746-7aeb6280-c28b-11e9-9f1c-e3b202539433.png)

8. Watch vimeo video for a bit. It will get added back to AC table but it is now at 100%, all other sites that were there previously are gone. If you check `publisher_info_db` at this point, you will see a normal looking duration, but your score is extremely high.

![Screen Shot 2019-08-19 at 2 04 27 PM](https://user-images.githubusercontent.com/28145373/63288761-8474ca80-c28b-11e9-9816-a4229c97c90f.png)
![Screen Shot 2019-08-19 at 2 06 27 PM](https://user-images.githubusercontent.com/28145373/63288768-88a0e800-c28b-11e9-989b-287533df24d5.png)

9. If you try to add sites to your auto contribute table at this point, they won't add. I'm guessing bc the score for the vimeo video is so high.

Note - I could not reproduce this with a YouTube video in place of vimeo video.

## Actual result:
Seek (forward/backward) on vimeo video screws up ac table.

## Expected result:
AC table not wiped out, duration to be accurately recorded.

## Reproduces how often: 
Seems to reproduce easily with seek forward/backward

## Brave version (brave://version info)

Brave | 0.68.130 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? 0.67.x n/a, 0.68.x yes
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
If you watch vimeo normally this doesn't appear to happen.

**Comment by LaurenWags** [comment]
Note - if at step 8 you remove this publisher from your AC table, your previous entries come back.

**Comment by btlechowski** [comment]
Reproduced on Ubuntu

Brave | 0.68.130 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/63289843-5fe71580-c2c0-11e9-8886-ebf540942e0a.png)

**Comment by GeetaSarvadnya** [comment]
The issue is Reproducible in windows `10 x64 -0.68.130`. The issue is NOT 100% reproducible on all Vimeo videos, Vimeo video has to be forward and backward multiple times only then the issue is reproducible.

**Comment by LaurenWags** [comment]
Additional notes:
1. You don't need to go forward first for this to happen. Moving the seek bar back will cause the large `score` value and screw up your AC table. (making the vimeo pub the only entry)
2. Moving the seek bar forward only does not increase the `score` value in `publisher_info_db`. It does inflate your `duration` though (so you are getting an inaccurate amount of time viewed). This does not screw up your entire AC table though.
3. If you Pause before moving seek bar back towards beginning of the video, you don't get the large `score` value and your AC table doesn't get messed up.

**Comment by LaurenWags** [comment]
@NejcZdovc here are some simpler steps:
1. clean profile, enable rewards
2. visit some sites so you have a few in your ac table
3. view a vimeo video
4. once it's added to your ac table, move the slider bar back toward the beginning of the video (doesn't have to be right at the start)
5. wait a bit, your ac table will clear and you'll only have one entry - the vimeo publisher at 100%. checking your `publisher_info_db` will show an insanely high `score` value. mine was 36million.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/3209
* Verified STR from description
* Existing AC table entries were not wiped out when seeking (fwd or back) on vimeo video
* No unusual score or duration observed in `publisher_info_db` activity table.
* Verified using verified and non-verified vimeo publishers
