### ISSUE TITLE
Address bar stuck in search-mode (after enter-execute)

### ISSUE THREAD

**Issue by corona-nova** [brave/brave-browser#5731]
## Description 

when typing in address bar, 
(if it contains a space character it goes into search mode instead of url _) 
after doing a url-search,
the address bar still shows the search query,
instead of the current URL, pressing esc or ctrl+z (undo
does not mitigate that

## Steps to Reproduce

   1. type in search bar (non-url)
   2. press enter
   3. note that address bad stuck in searhc mode or previous search query

## Actual result:

![image](https://user-images.githubusercontent.com/54251501/63313362-27e8ce00-c2d2-11e9-9b6b-84eba4bd6652.png)

## Expected result:
since the url changed, i expect the url bar to show the current url
and for the bar not to be stuck in that search mode 
(with the search query still displayed)

it is disruptive to workflow, cant even see the current url,
this persists for that tab even after clicking links (url change),

## Reproduces how often: 

- happens every time (for now, seems)
- it only affects the tab where that occurred

## Brave version (brave://version info)

Version 0.67.124 Chromium: 76.0.3809.100 (Official Build) (64-bit)

## Version/Channel Information:

this is release channel haven tested on other channels
release channel, linux
linux

## Other Additional Information:
i don't think it happened with previous versions of brave,
 i have not tested that [to verify]

if i don't execute the search <press enter>,
ctrl+z or Esc-key, exits out of that state

## Miscellaneous Information:

probably is a separate issue, when typing url's with spaces in them
if i don't escape them to `%20`'s they are interpreted as spaces
and this is annoying, made worse by this bug

**Comment by rebron** [comment]
Can you provide a screenshot of the entire browser and tell us what your default search engine is? There might be some issue with the search engine you chose.

**Comment by bsclifton** [comment]
Closing as there hasn't been any more information. Let's re-open if there is additional info we can provide
