### ISSUE TITLE
Decouple business logic from the Rewards service to reduce the risk of regressions on iOS and Android

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#5739]
Decouple business logic from the following functions in `RewardsServiceImpl::` to the ledger library:

- [ ] FetchPublisherActivityFromURL
- [x] GenerateGUID - https://github.com/brave/brave-browser/issues/8785
- [ ] GetContentSiteList
- [ ] GetExternalWallets
- [ ] GetGrantCaptcha
- [ ] GetPublisherActivityFromUrl
- [ ] LoadActivityInfo
- [ ] LoadLedgerState
- [ ] LoadMediaPublisherInfo
- [ ] LoadPanelPublisherInfo
- [ ] LoadPublisherInfo
- [ ] LoadPublisherList
- [ ] MaybeShowAddFundsNotification
- [ ] MaybeShowBackupNotification
- [ ] OnActivityInfoLoaded
- [ ] OnBackground
- [ ] OnContributeUnverifiedPublishers
- [ ] OnFetchBalance
- [ ] OnForeground
- [ ] OnGrantFinish
- [ ] OnLoad
- [ ] OnPostData
- [ ] OnPublisherListLoaded
- [ ] OnReconcileComplete
- [ ] OnTip
- [ ] OnUnload
- [ ] OnWalletInitialized
- [ ] OnXHRLoad
- [ ] ProcessRewardsPageUrl
- [ ] SaveActivityInfo
- [ ] SaveExternalWallet
- [ ] SaveLedgerState
- [ ] SavePublisherInfo
- [ ] SaveRecurringTip
- [ ] SaveRecurringTipUI
- [ ] SetContributionAmount
- [ ] SetPublisherExclude
- [ ] SetPublisherExclude

**Comment by Miyayes** [comment]
@tmancey Still relevant? Seems very old. Can close out this issue and file anew. Also, in general, I am not a fan of meta-issues, and this one seems like more of a meta-issue.

**Comment by tmancey** [comment]
@Miyayes, this can be closed out, thanks

**Comment by tmancey** [comment]
Closing as stale
