### ISSUE TITLE
Brave API keys notification Learn more points to Chromium page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#574]
## Description 

Brave API keys notification Learn more points to Chromium page

## Steps to Reproduce

   1. Install 0.50.11
   2. Click on Learn more on the Brave API keys message
   3. Open a Chromium link

## Actual result:
Brave API keys notification Learn more points to Chromium page

## Expected result:
Should not show the notification on first launch

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Release and packaged build

**Comment by bbondy** [comment]
QA notes: Should just go to community.brave.com for now

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux
