### ISSUE TITLE
Add reset data / delete account option to Crypto Wallets

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#5741]
## Description 

Crypto wallets should feature an option to reset all data, or delete accounts. At the moment, there is only a pull request to allow disabling/enabling, but not for resetting or deleting data.

**See:** https://www.reddit.com/r/brave_browser/comments/cszx7s/how_do_i_delete_my_cryptowallet_settings_and/

**Comment by bbondy** [comment]
I think you can add a second account then delete the first.

**Comment by bbondy** [comment]
Maybe a clear all extension state would be nice though.

**Comment by ryanml** [comment]
This will amount to an action in the Advanced settings tab. There definitely should be a confirmatory modal letting the users know that they are essentially going to reset Crypto Wallets to how it was when they first made an account. cc: @tomlowenthal && @jamesmudgett for copy and any extra UX we may need.

**Comment by tomlowenthal** [comment]
Will this work from the password-entry screen — that seems like the most important place to support a reset.

**Comment by dbarev** [comment]
manual workaround is to delete the following folder (under windows):
%profile data%/[Default]\Local Extension Settings\odbfpeeihdkbihmopkbjmoonfanlbfcl
whereas %profile data% is the path to the brave data folder for the currently logged user (in windows) and [Default] is the profile username in Brave

**Comment by Michael-A-Heuer** [comment]
Is there a workaround for macOS too?

**Comment by thechadc** [comment]
to remove from console.

rmdir %localappdata%/BraveSoftware\Brave-Browser\User Data\Default\Local Extension Settings\odbfpeeihdkbihmopkbjmoonfanlbfcl

**Comment by thechadc** [comment]
> manual workaround is to delete the following folder (under windows):
> %profile data%/[Default]\Local Extension Settings\odbfpeeihdkbihmopkbjmoonfanlbfcl
> whereas %profile data% is the path to the brave data folder for the currently logged user (in windows) and [Default] is the profile username in Brave

to remove wallet from command line.

cd %localappdata%\BraveSoftware\Brave-Browser\User Data\Default\Local Extension Settings
rmdir /Q /S odbfpeeihdkbihmopkbjmoonfanlbfcl

**Comment by thechadc** [comment]
> manual workaround is to delete the following folder (under windows):
> %profile data%/[Default]\Local Extension Settings\odbfpeeihdkbihmopkbjmoonfanlbfcl
> whereas %profile data% is the path to the brave data folder for the currently logged user (in windows) and [Default] is the profile username in Brave

After deleting, Im getting an error KeyringController - No account found on keychain reset when creating a new local wallet. Any way to reset this?

**Comment by jaclas** [comment]
> After deleting, Im getting an error KeyringController - No account found on keychain reset when creating a new local wallet. Any way to reset this?

I have the same problem and the same error.
Is there a way to delete/restart "Crypto Wallets" in Brave?

**Comment by dbarev** [comment]
@jaclas, @thechadc  I tried to reproduce your issue but failed. Here is what I do:

1. Download portable brave (I do not want to mess my existing install) from https://portapps.io/app/brave-portable/
2. Start and initialize wallet.
3. Shutdown Brave
4. Execute steps in the above post for the workaround
5. Restart Brave - wallet can be re-initialized.

This works consistently under Windows on different machines. Do not have time to test under Linux but should work similarly.

**Comment by jaclas** [comment]
@dbarev 
The portable version of brave doesn't have a directory:

\BraveSoftware\Brave-Browser\User Data\Default\Local Extension Settings\odbfpeeihdkbihmopkbjmoonfanlbfcl

but only:

\BravePortable\data\odbfpeeihdkbihmopkbjmoonfanlbfcl

which is different from the directory specified in the solution.

Try with fully installed Brave Browser and correct directory.

**Comment by jolestar** [comment]
I just remove ~/Library/Application Support/BraveSoftware/Brave-Browser/Default/Local Extension Settings/odbfpeeihdkbihmopkbjmoonfanlbfcl at Mac. 
The wallet can be re-initialized.
Please backup before remove.

**Comment by jrogers512** [comment]
> Is there a workaround for macOS too?

`rm -r ~/Library/Application\ Support/BraveSoftware/Brave-Browser/odbfpeeihdkbihmopkbjmoonfanlbfcl/`

**Comment by srirambv** [comment]
Moving to 1.0.18 as per triage discussion

**Comment by kirkins** [comment]
Anyway to reset crypto wallets now?

**Comment by kirkins** [comment]
I see it now. I just had to lock my account and where you would enter your password there is a link to import from seed.

**Comment by rapkyt** [comment]
> > After deleting, Im getting an error KeyringController - No account found on keychain reset when creating a new local wallet. Any way to reset this?
> 
> I have the same problem and the same error.
> Is there a way to delete/restart "Crypto Wallets" in Brave?

I created my wallet with a random password that I thought I've sa.ved but I didn't, now I want to create a new one from scratch, but I can't.

**Comment by gszep** [comment]
This is still a problem in Version 1.23.75 Chromium: 90.0.4430.93 (Official Build) (64-bit)
