### ISSUE TITLE
Add testing wiki page in brave/ethereum-remote-client

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#5742]
Extension updates for brave/ethereum-remote-client will be done out of line from brave/brave-browser releases, and they will apply to all channels at the same time.

This issue is to create a wiki page on the above repo so that QA can give sign off before we publish new versions.

**Comment by ryanml** [comment]
Testing wiki page has been established here: https://github.com/brave/ethereum-remote-client/wiki/Testing

It will be continually updated as we make more modifications to current behavior

cc: @kjozwiak

**Comment by kjozwiak** [comment]
@bbondy @ryanml should the move this into `0.69.x` or will this wiki be a work of progress as we improve/implement new `Crypto Wallets` features?

Maybe add it into `0.69.x` so we can run through the above?
