### ISSUE TITLE
Remove unsupported sync w/ mobile option in Brave wallet

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#5748]
1. Go to Crypto wallet page
2. Settings -> Advanced

<img width="394" alt="Screen Shot 2019-08-20 at 6 04 33 PM" src="https://user-images.githubusercontent.com/831718/63388038-14db0a00-c375-11e9-8f65-6b41380a901c.png">

This should be hidden.

**Comment by kjozwiak** [comment]
Labelling as `QA/No` as this was checked and QA'd via https://github.com/brave/brave-browser/issues/6272.
