### ISSUE TITLE
third_party/blink/renderer/modules/encryptmedia deps problem

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#5749]
https://staging.ci.brave.com/job/brave-browser-build-pr/job/brave-syncer-0.69.x/1/execution/node/454/log/?consoleFull
```
17:34:25  C:\jenkins\workspace\ser-build-pr_brave-syncer-0.69.x\src\brave\chromium_src\third_party\blink\renderer\modules\encryptedmedia\navigator_request_media_key_system_access.cc(18,10): fatal error: 'brave/components/brave_drm/brave_drm.mojom.h' file not found
17:34:25  #include "brave/components/brave_drm/brave_drm.mojom.h"
17:34:25           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
17:34:25  1 error generated.
```

The original commit was https://github.com/brave/brave-core/commit/c79e89867724ae583ba74e8a1090d7e90e5321c7
and then https://github.com/brave/brave-core/commit/386b9ff1a74f69000a3794f8cc8a5c8fccf45c06 which remove `public_deps`

We should either 
~~1. keep `public_deps` so `encryptedmedia` doesn't have to list `//brave/components/brave_drm` as direct deps for extensibility because we might add more than `brave_drm` into it in the future~~
~~2. Or put `//brave/components/brave_drm` as deps in `third_party/blink/renderer/modules/encryptmedia/BUILD.gn` and remove patched deps `third_party/blink/renderer/modules/BUILD.gn` since no one is using it right now~~
3. https://github.com/brave/brave-browser/issues/5749#issuecomment-526376621

cc @bridiver

**Comment by bridiver** [comment]
I think the real problem is that it's in the wrong target to start with and should be in `"//third_party/blink/renderer/core"`

**Comment by darkdh** [comment]
And @bridiver mentioned in slack that `blink_modules_sources` template has these deps
```
   deps = [
      "//third_party/blink/renderer/core",
      "//third_party/blink/renderer/modules:make_modules_generated",
      "//third_party/icu",
    ]
```
so `"//third_party/blink/renderer/core"` seems like the right place for submodules
