### ISSUE TITLE
Empty Downloads Page

### ISSUE THREAD

**Issue by leshacat** [brave/brave-browser#5756]
Downloads are empty even when currently downloading....

Latest Brave browser

**Comment by leshacat** [comment]
nevermind ...

clicking three dots on DL page and then "CLEAR ALL" fixes this... It must be a GUI bug.

**Comment by chkk525** [comment]
This was happening to me as well. (also @leshacat 's CLEAR ALL solution also worked for me)

**Comment by rebron** [comment]
Closing. This should be fixed 68.x. 
@leshacat You can update from here: brave://settings/help
