### ISSUE TITLE
WordPress Jetpack Statistics tracker script not being blocked

### ISSUE THREAD

**Issue by willstocks** [brave/brave-browser#5759]
## Description 

I run a WordPress blog. On that blog, I have Jetpack installed and I'm using the [Jetpack Stats module](https://jetpack.com/support/wordpress-com-stats/) enabled, which adds a little script to my frontend: https://stats.wp.com/e-201934.js

Looking at Shields, this script/tracker is blocked (rightly so):
![image](https://user-images.githubusercontent.com/43744514/63494531-c7b28180-c4b5-11e9-9651-61cae7db16f9.png)

HOWEVER... on every page view, I can see my stats counter increasing in my backend. I quickly tested this on a dev version of my site, where I am the only visitor and I still see the backend counter increasing... even though Shields is showing that the script/tracker has been blocked?

## Steps to Reproduce

   1. Setup a basic WP site with Jetpack enabled (connected to wp.com) and the stats module enabled
   2. Logout of wp-admin and visit that site (Private Mode, non-Private mode) 
   3. Log back in to wp-admin and see the stats counter has increased. Same is reflected on 

## Actual result:

Not an easy way for me to grab a screenshot... but I refreshed my page/visited every single one of my blog posts consecutively and every single one of those page views was reflected in Jetpack stats

## Expected result:
Shields shows it has been blocked... so those page views shouldn't be recorded? When I used Google Analytics, Brave page views weren't recorded there - this is the same in principle? If the script is actually allowed, it shouldn't show as blocked?

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

Brave | 0.67.125 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1809 (Build 17763.615)

Please note: I have seen this across multiple Brave versions, not just this version.

## Version/Channel Information:

- Can you reproduce this issue with the current release? - Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
I could be a embedded javascript, rather the `https://stats.wp.com/` thats still monitoring/tracking users.

**Comment by willstocks** [comment]
Hi @ryanbr,
The only bit of inline JS I can find that's related is:

```html
<script type="text/javascript">
	_stq = window._stq || [];
	_stq.push([ 'view', {v:'ext',j:'1:7.6',blog:'123359122',post:'0',tz:'1',srv:'willstocks.co.uk'} ]);
	_stq.push([ 'clickTrackerInit', '123359122', '0' ]);
</script>
```

It's right after the `https://stats.wp.com/` request and is dependent on that file (that's where `_stq` comes from/is used as far as I can tell):

```html
<script type="text/javascript" src="https://stats.wp.com/e-201934.js" async="async" defer="defer"></script>
<script type="text/javascript">
	_stq = window._stq || [];
	_stq.push([ 'view', {v:'ext',j:'1:7.6',blog:'123359122',post:'0',tz:'1',srv:'willstocks.co.uk'} ]);
	_stq.push([ 'clickTrackerInit', '123359122', '0' ]);
</script>
```

Assuming my source isn't too dynamic, see `https://willstocks.co.uk/` -> View Source -> Lines 670 to 675

**Comment by ryanbr** [comment]
Hard to say, possibly that ^ and/or its planting a cookie and tracking that way.

**Comment by willstocks** [comment]
But in theory, Shields is blocking that script (stats.wp.com) from being loaded (or at least, that's what it implies) yet I'm seeing it in my network waterfall still? 
Is it only preventing cross-site, or should it be preventing any stats collection at all (which is how I understood it/saw in Google Analytics when I _used_ to use that).
I don't see any cookies being added/removed and the stats.wp.com js doesn't _appear_ to do anything cookie related. They try to do something with a tracking pixel, but I don't think that's in effect either...

Or am I misunderstanding something here?

**Comment by willstocks** [comment]
Question - if a script is "blocked" in Shields... what does that actually mean? Should that show as a "cancelled" resource in the DevTools network tab? Or does it mean that it has downloaded, but it's now being blocked "calling home"?

**Comment by ryanbr** [comment]
Loaded 5 various sites: **stats.wp.com** is blocked in Site Trackers in shields:

`https://indianexpress.com/`
`https://nesn.com/`
`https://www.rvcj.com/`
`https://heavy.com/`
`https://metro.co.uk/`

Can you confirm @willstocks ?

**Comment by willstocks** [comment]
Always shows as blocked for me in shields, but I see my WP stats increase on each visit and in the Network tab of devtools, the request still appears to succeed, which led me to become a little confused.

Might be a redherring?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ryanbr** [comment]
Yeah, possibly. Just checked network tab. its being showen as blocked there also, and also checked cookies, nothing from wp.com.

**Comment by ryanbr** [comment]
Closing this, seem fine here. We're blocking it at network level.

**Comment by willstocks** [comment]
Hmm... weird @ryanbr because I'm not seeing the same behaviour in the Network tab (which may be what's throwing me off here?):

I see this in Shields:
![image](https://user-images.githubusercontent.com/43744514/73538674-7d014200-4423-11ea-8dae-c0ba72375d53.png)

But still this in the Network tab:
![image](https://user-images.githubusercontent.com/43744514/73538651-6eb32600-4423-11ea-9eee-0dd4259c4638.png)

This has been consistent for me throughout Brave versions, from the one logged to now: Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)

I'm on Windows 1909 now as well.

**Comment by willstocks** [comment]
@ryanbr any other thoughts on this one? Just still seems a bit weird?

**Comment by willstocks** [comment]
@ryanbr I'm going to reopen this as a fresh issue - I've just been sat monitoring my network and I can see a DNS request going out to stats.wp.com despite Shields showing it's blocked
