### ISSUE TITLE
Recent update shows extensions removed message

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5767]
## Description 

Post upgrade to `0.68.131`, got a message saying 3 out of 5 extensions installed are removed. However, they were still active and worked just fine. 
![image](https://user-images.githubusercontent.com/17010094/63534446-35be6f00-c4dd-11e9-8589-7e09945dcfd6.png)

All the extensions were installed by visiting the developer homepage and navigating to the Chrome Store from their home page. 

Extensions Installed:
1. Dark Reader
2. Zenhub
3. 1Password X
4. Grammarly
5. Evernote

The error message only mentioned 3 extensions(1Password X/Grammarly/Evernote). 

As a test I created a local unpacked extension and installed 1Password X on `0.67.123` and then upgraded to `0.68.131` via `sudo apt update && sudo apt-get install --only-upgrade brave-browser` and there was no warning shown about extensions being removed.

## Expected result:
No warning message when extensions are installed via webstore

## Reproduces how often: 

When you are the chosen one. 
![image](https://az705183.vo.msecnd.net/onlinesupportmedia/onlinesupport/media/skype/fa300xx/ninja_40x40_1.gif)

## Brave version (brave://version info)

Brave | 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Maybe
- Can you reproduce this issue with the dev channel? Maybe
- Can you reproduce this issue with the nightly channel? Maybe

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Probably similar to #5761 
cc: @bbondy

**Comment by rebron** [comment]
cc: @tomlowenthal for prioritization

**Comment by GeetaSarvadnya** [comment]
Add extensions in 0.68.32 and update it to latest 0.68.33 is showing the extension removed popup message

![image (3)](https://user-images.githubusercontent.com/38657976/64611978-57ca5380-d3f0-11e9-9014-ffab80e69f1a.png)

**Comment by GeetaSarvadnya** [comment]
Further investigation on the issue, observations are mentioned below:

1a: Adobe Acrobat is causing this issue, Acrobat was installed in windows as soon as I upgrade the brave build to 0.68.133, Adobe Acrobat is installed in brave and showing the popup message as `Unsupported extensions disabled` 

STR
1. Clean profile 0.68.132
2. Upgrade to 0.68.133
3. `Unsupported extensions disabled` popup is displayed

![image](https://user-images.githubusercontent.com/38657976/64638307-1d2dde80-d423-11e9-8bc2-f1a5bb6bf13f.png)

1b: Issue is not reproducible in a clean profile for `0.68.131` `0.68.132` and `0.68.133`

1c: Issue is not reproducible when upgrading build from `068.131` to `0.68.132`

**Comment by bsclifton** [comment]
@GeetaSarvadnya @srirambv have either of you seen this recently? If not, can we close it out?

**Comment by srirambv** [comment]
This happens on Fedora at least. Reason: Fedora adds a UA extension when you install which isn't from Extension store. Happens on clean install

**Comment by srirambv** [comment]
This seems to be fixed on Fedora at least. Closing the issue for now, can reopen/add a new one if this happens again.
