### ISSUE TITLE
sync bookmarks are out of order after created

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#5770]
## Description 

Initial sync between devices breaks bookmark order

## Steps to Reproduce

1. deviceA: A1, A2
2. deviceB: B1, B2
3. deviceC: no bookmarks
4. create chain on deviceA
5. connect deviceB to chain
6. connect deviceC to chain

## Actual result:

![image](https://user-images.githubusercontent.com/11330831/63552219-f3e8f500-c4eb-11e9-9c67-1515497d07dd.png)

## Expected result:
Three devices should have A1, A2, B1, B2

## Reproduces how often: 

100%

## Brave version (brave://version info)

0.71.28 (Nightly)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by darkdh** [comment]
We can also test extra steps after original STR passed

7. Add a folder "F" on device B
8. Move A1, A2 into "F"
9. After a while, all devices should have 
<img width="277" alt="Screen Shot 2019-08-22 at 15 01 06" src="https://user-images.githubusercontent.com/11330831/63552860-b5543a00-c4ed-11e9-8c57-33f38ad49204.png">

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.121 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the STR from the description

![image](https://user-images.githubusercontent.com/38657976/64156844-27644180-ce53-11e9-8208-fe7ac3e1e62e.png)

**Comment by Riggie1000** [comment]
Found an issue.

Creating bookmarks per button works with sync by waiting about a minute. But I wanna have the same bookmark twice in another directory. So I moved the cursor the the first bookmark, copied it per rightclick and pasted it into the other directory. Now sync doesn't work.
