### ISSUE TITLE
URL doesn't update after closing Verify modal

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5771]
## Description 
When accessing the user wallet onboarding/verify modal from the rewards panel (accessed via BAT logo), the URL remains brave://rewards#verify. After closing the modal I expected it to go back to brave://rewards. This doesn't happen if you access the modal from brave://rewards page itself. 

## Steps to Reproduce

   1. Clean install 0.69.x
   2. Enable Rewards
   3. Navigate to brave://rewards
   4. Access onboarding verify modal (click on Verify Wallet, Add Funds, Withdraw Funds, or (verify) in wallet pane footer.
   5. Modal is displayed, URL shown still says brave://rewards.
   6. Close this page, open a new page.
   7. Click on BAT logo, click on Verify Wallet or Add Funds.
   8. brave://rewards/#verify is opened. Close the modal. URL remains brave://rewards/#verify.

## Actual result:

![verify-URL](https://user-images.githubusercontent.com/28145373/63552657-37505d00-c506-11e9-9fd4-f3f08153de60.gif)

![Screen Shot 2019-08-22 at 5 54 57 PM](https://user-images.githubusercontent.com/28145373/63552585-fd7f5680-c505-11e9-84e8-267d7b6cd435.png)

## Expected result:
![Screen Shot 2019-08-22 at 5 55 21 PM](https://user-images.githubusercontent.com/28145373/63552601-0839eb80-c506-11e9-91d8-0f15f944405b.png)

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.113 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @mandar-brave

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.70.109 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
