### ISSUE TITLE
unable to disconnect from Uphold if KYC is not completed

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5772]
## Description 
If you connect an uphold account but don't KYC, you are unable to disconnect from Uphold within Rewards.

## Steps to Reproduce

1. Clean profile or upgrade to 0.69.x
2. Enable Rewards.
3. Click on Verify wallet from somewhere, then proceed to uphold.
4. Create an account, don't complete KYC.
5. Go back to Rewards Settings.
6. Clicking on 'Verify Wallet' button doesn't give you the option to disconnect, just directs you to Uphold to complete KYC.

## Actual result:
Clicking on 'Verify Wallet' takes you to Uphold to complete KYC.

## Expected result:
Some way to disconnect from within Brave. If you've verified and KYC'd, clicking on 'Verify' gives you the option to disconnect:
![image (1)](https://user-images.githubusercontent.com/28145373/63552783-ad54c400-c506-11e9-96cf-876994bf61d6.png)

Not sure if we want this in the same place or somewhere different.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.113 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @mandar-brave

**Comment by NejcZdovc** [comment]
this is a problem because we removed connected state. We need to decide if we want to add it back or just add dialog which you get when you are KYC'ed

**Comment by NejcZdovc** [comment]
We should display this

![image](https://user-images.githubusercontent.com/9574457/64072187-e4577200-cc8a-11e9-8193-7845ae7a1dc0.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.123 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/3322
* Verified clicking on `Complete wallet verification` took me to Uphold in the same tab to complete my KYC
* Verified clicking on `Go to my Uphold account` took me to my Uphold dashboard in the same tab
* Verified clicking on `Disconnect from Brave Rewards` put me in disconnected state.
* Verified from brave://rewards and panel
* Encountered and logged #5888
