### ISSUE TITLE
Crypto Wallets Setup - local wallet description - text correction

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#5774]
## Description 

There is a typo in the copy for the local wallet option in the Crypto Wallets setup (brave://wallet)

> New Local Wallet
> Create a new Brave local wallet to access dApps and store crypto and collectibles securely. Trade tokens **annonymously** with no trading fees

"annonymously" should be updated to: anonymously
.

## Steps to Reproduce

   1. from a clean profile, navigate to `brave://wallet/`
   2. locate local wallet option
   3. *annonymously* appears in the second sentence of local wallet description copy. 

## Expected result:
anonymously

## Reproduces how often: 

100%

## Brave version (brave://version info)
```
Brave | 0.70.72 
Chromium: 76.0.3809.100 (Official Build) dev (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS 
Version 1803 (Build 17134.950)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? unknown
- Can you reproduce this issue with the beta channel? unknown
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

* Verified misspelt word is corrected on component version 1.0.9
![image](https://user-images.githubusercontent.com/17010094/66081963-264c3000-e537-11e9-9dfd-0d1a3c6b9cb9.png)

Verification passed on 

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1903 (Build 18362.30)

* Verified misspelt word is corrected on component version 1.0.9
![image](https://user-images.githubusercontent.com/17010094/66082091-60b5cd00-e537-11e9-88c4-f2e94f5950e1.png)
