### ISSUE TITLE
"Chrome" browser references in brave://about page

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#5775]
## Description 

"Chrome" is displayed for all of the URLs and browser references within the brave://about page 

## Steps to Reproduce

   1. navigate to brave://about
   2. observe Chrome used in the page, title, tab and urls
   3. 

## Expected result:
All instances of "Chrome" should be replaced with "Brave"

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 0.70.72 
Chromium: 76.0.3809.100 (Official Build) dev (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 
OS Version 1803 (Build 17134.950)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? unknown
- Can you reproduce this issue with the beta channel? unknown
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by lukemulks** [comment]
@rebron assigned you on this one - suspect you'd likely know the best path forward in queue.

**Comment by srirambv** [comment]
+1 from @bershanskiy via #6438

**Comment by bershanskiy** [comment]
@srirambv Thank you for closing my duplicate.

**Comment by bershanskiy** [comment]
@rebron Have you started working on this yet? If not, may I make a PR and tag you on it?

**Comment by rebron** [comment]
@bershanskiy go ahead and grab, that would be great.

**Comment by aussiechief** [comment]
While just cosmetic, this is also the case in brave://settings, brave://rewards, brave://history, brave://bookmarks, brave://downloads, etc. All cross-referencing links are still using the chrome:// protocol.

**Comment by srirambv** [comment]
+1 from @rahulsnkr  via #15357

**Comment by srirambv** [comment]
+1 from @bcat1023 via #15876

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.27.62 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. new profile
2. loaded `chrome://about`
3. confirmed I was redirected to `brave://about/`
4. confirmed page title is `Brave URLs`
5. confirmed page heading is `List of Brave URLs`
6. confirmed although links go to `chrome://` they are internally redirected to their respective `brave://` counterpart
7. confirmed that manually entering `chrome://crash` and `brave://crash` end at up `brave://crash` - did this for several other internal URL schemes

example | example
---------|---------
<img width="1193" alt="Screen Shot 2021-06-14 at 1 40 51 PM" src="https://user-images.githubusercontent.com/387249/121957076-c7cce280-cd16-11eb-8f76-05ce81e255f2.png"> | <img width="694" alt="Screen Shot 2021-06-14 at 1 47 38 PM" src="https://user-images.githubusercontent.com/387249/121957355-22663e80-cd17-11eb-810f-8dfa0d66f5ae.png">

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 11.27.75 x64 Beta build
- Verified all entries in `chrome://about` page is referenced as `brave://`
- Verified manually typing `brave://components` loads page as `brave://component`
- Logged followup issue #16565

  <img width=400 src=https://user-images.githubusercontent.com/17010094/123050321-7b5d6300-d3f8-11eb-902b-64050619c45d.png>

-----------
Verification passed on Samsung Tab A with Android 10 running 11.27.75 x64 Beta build
- Verified all entries in `chrome://about` page is referenced as `brave://`
- Verified manually typing `brave://components` loads page as `brave://component`
- Encountered #16565

  <img width=400 src=https://user-images.githubusercontent.com/17010094/123050238-64b70c00-d3f8-11eb-8873-03f7635ab804.png>
