### ISSUE TITLE
Ads not blocked on ecommerce-platforms.com

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5777]
## Description 

Ads not blocked on ecommerce-platforms.com

## Steps to Reproduce

   1. Visit an article on ecommerce-platforms.com
   2. Ad banners are shown at the top of the article and in other places

## Actual result:

Looks like first party advertising linking to a third party site
![image](https://user-images.githubusercontent.com/17010094/63593891-019d8980-c583-11e9-88f5-a5d74a73ab12.png)
![image](https://user-images.githubusercontent.com/17010094/63593921-1843e080-c583-11e9-9146-ce72c00b3037.png)
![image](https://user-images.githubusercontent.com/17010094/63593943-2bef4700-c583-11e9-8678-b5f4c1afc520.png)

![image](https://user-images.githubusercontent.com/17010094/63593231-969f8300-c581-11e9-817b-5a9b7b871f58.png)

## Expected result:
Ads blocked

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.69.113 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? Yes with uBlock Origin banner ad is blocked but inline ad isn't
![image](https://user-images.githubusercontent.com/17010094/63594010-517c5080-c583-11e9-8444-f3023384c337.png)
![image](https://user-images.githubusercontent.com/17010094/63594078-7ec8fe80-c583-11e9-8647-f8169f50b77c.png)

## Miscellaneous Information:

cc: @ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/124be68a78ef786008351b5ccc5bdea8183f41c5

Should fix it.

**Comment by bsclifton** [comment]
I think this is indeed fixed 😄 Thanks, @ryanbr!
