### ISSUE TITLE
Make visible bookmark bar on NTP by default

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#5781]
As https://github.com/brave/brave-core/pull/2869 is merged, user can choose whether bookmark bar is visible or not on NTP regardless of bookmark show option.

By default bookmark bar is off on NTP.
It should be visible by default.

**Comment by rebron** [comment]
Flagged this as a p2 to evaluate. We may want to include as part of hotfix with 68.x.
@kjozwiak @bsclifton

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.121 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 10 OS Version 1803 (Build 17134.523)


- Verified the test plan from https://github.com/brave/brave-core/pull/3251

**Comment by jernejml** [comment]
This setting's default value should be set to off.
Scenario:
- you are preparing to share your screen (for example: presentation to your business partners or coworkers)
- you disable show bookmarks
- during presentation you open new tab
- your coworkers suddenly realize you like to read tabloid about celebrities or even worse <pick one>
