### ISSUE TITLE
Ads are no longer blocked on many sites

### ISSUE THREAD

**Issue by warwickmm** [brave/brave-browser#5782]
## Steps to Reproduce
After upgrading to 0.68.131, ads are no longer blocked on many sites.  Version 0.67.123 was able to block ads without any issues.

   1. Upgrade to Version 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit) on Windows 7.
   2. Ensure that all shields are up.  Brave Rewards is not enabled.
   3. Visit www.sfgate.com, or www.nytimes.com

Also, on sites where ads do appear to be blocked, the shield icon is not indicating that elements are being blocked, and the stats on the new tab page are no longer being updated.

## Actual result:
![image](https://user-images.githubusercontent.com/17345532/63600341-3bb55e00-c578-11e9-8ed3-6fe35613d57a.png)

## Expected result:
The page should load with no ads

## Reproduces how often:

 100% of the time

## Brave version (brave://version info)

Version 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
<img width="1339" alt="Screen Shot 2019-08-23 at 10 20 45 AM" src="https://user-images.githubusercontent.com/5951041/63610985-b178f400-c58f-11e9-9a18-47eea47d7168.png">

@warwickmm I'm seeing ads blocked on SFGate with your same steps to reproduce.

Can you tell me what you have set for: 
brave://settings/shields

**Comment by warwickmm** [comment]
![image](https://user-images.githubusercontent.com/17345532/63611225-411ea280-c590-11e9-8cd4-6e8fee0c66b8.png)

I've also cleared all site settings and still see ads.

Perhaps related, I noticed that the stats on the new tab page do not seem to be updating anymore.

**Comment by rebron** [comment]
@warwickmm can you try a few more websites for me: maybe tmz.com, theverge.com, and espn.com. 
Do you also see ads on those websites with shields up?

And on SFGate, can you screenshot how many items you have blocked? I have mine showing 25 items blocked.

**Comment by warwickmm** [comment]
Ads appear to be blocked on theverge.com and espn.com (I didn't try tmz.com since I'm at work).  However, the shields icon indicates that no items are blocked:

![image](https://user-images.githubusercontent.com/17345532/63614008-dcb31180-c596-11e9-82a0-9ae5202b8aad.png)

![image](https://user-images.githubusercontent.com/17345532/63614034-ec325a80-c596-11e9-9558-915240d84fcb.png)

For sfgate.com, the shields icon indicates that 1 item is blocked:

![image](https://user-images.githubusercontent.com/17345532/63614083-0c621980-c597-11e9-8f47-57baa2edbfb2.png)

**Comment by rebron** [comment]
<img width="1509" alt="Screen Shot 2019-08-23 at 11 27 27 AM" src="https://user-images.githubusercontent.com/5951041/63615057-4b916a00-c599-11e9-9708-6600d6ec7511.png">
TMZ.com ads should be blocked for you, sorry for that request. 

One more thing, can you screenshot what you've got for shields settings like the two below.
I'm trying to figure what that one thing is that you're blocking and why 25 or so aren't showing up.
<img width="378" alt="Screen Shot 2019-08-23 at 11 31 08 AM" src="https://user-images.githubusercontent.com/5951041/63615197-9dd28b00-c599-11e9-98ef-9b9b2b2df427.png">
<img width="370" alt="Screen Shot 2019-08-23 at 11 31 15 AM" src="https://user-images.githubusercontent.com/5951041/63615208-a034e500-c599-11e9-857f-80fd8a47f15c.png">

**Comment by warwickmm** [comment]
![image](https://user-images.githubusercontent.com/17345532/63615331-f43fc980-c599-11e9-911a-ef5652782f04.png)

![image](https://user-images.githubusercontent.com/17345532/63615358-06ba0300-c59a-11e9-9882-b313889df220.png)

**Comment by warwickmm** [comment]
It's interesting that you have 25 "Cross-site trackers" blocked, while the only thing I have blocked is "Cross-site device recognition".

**Comment by rebron** [comment]
@warwickmm Does clearing sfgate cookies/permissions from here: brave://settings/content/siteDetails?site=https%3A%2F%2Fwww.sfgate.com and then reload the page help? Assuming you're ok with doing that. I'm not blocking tpc.googlesyndication.com I need to investigate some more.

**Comment by warwickmm** [comment]
Unfortunately, clearing sfgate cookies/permissions does not help.

**Comment by ryanbr** [comment]
Just tested sfgate; https://secure.fanboy.co.nz/gif/sfgate.gif

Seems fine, getting atleast 25+ blocked items (Brave Version 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit))

**Comment by warwickmm** [comment]
I tried renaming `%APPDADTA%\Local\BraveSoftware` and then installing a new instance.  Still encountering the same issues:
* www.sfgate.com shows ads
* www.cnn.com appears to have ads blocked, but the shields icon shows that zero elements are blocked
* Also, it seems that no stats are updated.  There are sites where I'm certain ads are being blocked (cnn, espn).  However, the shield icon shows zero elements being blocked, and the new tab page shows that 0 elements have been blocked.

**Comment by warwickmm** [comment]
Is it possible that my company's network is interfering with Brave's ad blocking capabilities?  I had a coworker install it and they experienced the same issues described above.  Downgrading (by using the portable version from portapps.io) to Version 0.67.124 Chromium: 76.0.3809.100 didn't exactly fix the issue.  However, if I then copied over the user data folder from an older install (possibly Version 0.62.27 Chromium: 73.0.3683.75), then the ads no longer appear.

**Comment by warwickmm** [comment]
I'm convinced that the issue was due to my company's network.  Something changed (again), and I can no longer reproduce the issue.  Sorry for the trouble.
