### ISSUE TITLE
Transfering Old Wallet to Brave Dev Wallet

### ISSUE THREAD

**Issue by DJavireX** [brave/brave-browser#5783]
## Description 
Transfering from Old Brave Wallet to New Brave Wallet

## Steps to Reproduce

   1. i copy my recovery key
   2. paste it into new brave (dev)

## Actual result:
0 BAT are Shown

## Reproduces how often: 
always

**Comment by DJavireX** [comment]
what kind of info do you need?

**Comment by rebron** [comment]
Can you tell me what versions you have for each, what version you had for the old brave wallet and the new version you're looking to import to?

**Comment by DJavireX** [comment]
> Can you tell me what versions you have for each, what version you had for the old brave wallet and the new version you're looking to import to?


Brave | 0.27.3
-- | --
V8 | 6.9.427.23
rev | 2df8cb1
Muon | 8.1.8
OS Release | 10.0.17134

the actual Brave Dev i would like to import the wallet
Update Channel | Veröffentlichung
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 69.0.3497.100

**Comment by DJavireX** [comment]
Can Anyone Help me??

**Comment by bsclifton** [comment]
@DJavireX you should be able to use the old Brave (0.27.3) and do the following:
- visit about:preferences#payments
- click the gear in the top right
- click the `backup your wallet` button
- copy the keywords shown to a file

In your new version of Brave... which should be 0.68.x or newer, you can then:
- visit brave://rewards/
- click the gear in the top right
- hit toggle for `restore`
- paste your keywords copied from old browser and then click `Restore` button

This should get you fixed up 😄 Please let us know if you have any trouble with these steps

cc: @Brave-Matt @hollons

**Comment by DJavireX** [comment]
I tried again, again 0 BAT: Brave is up to date
Version 0.70.80 Chromium: 76.0.3809.132 (Official Build) dev (64-bit)

**Comment by GeetaSarvadnya** [comment]
@DJavireX I am attaching a recorded file which may help, I am just following the same steps which @bsclifton mentioned above.

![Restore key from Muon to Brave core Dev profile](https://user-images.githubusercontent.com/38657976/64148012-ca12c500-ce3f-11e9-9d7a-bfead13ad076.gif)

**Comment by DJavireX** [comment]
> @DJavireX What is your wallet balance in the muon version `0.27.3`?
> I am attaching a recorded file which may help, I just followed the same steps which @bsclifton mentioned above.
> ![Restore key from Muon to Brave core Dev profile](https://user-images.githubusercontent.com/38657976/64148139-21b13080-ce40-11e9-9a01-6c30185c5f04.gif)

Yes thats exactly the way i tried to. After pressing import the Brave DEV Wallet Shows 0.0 BAT. On Brave 0.23 are 70.x Bat.

Yes it was in the Main Version von 0.27.3 exactly this version: (

Brave | 0.27.3
-- | --
V8 | 6.9.427.23
rev | 2df8cb1
Muon | 8.1.8
OS Release | 10.0.17134

)

**Comment by DJavireX** [comment]
i Dont know what im doing wrong, i also tried to import only the key words (with and without admin rights)

![2019-09-03 19_22_39-Rewards - Brave](https://user-images.githubusercontent.com/54446791/64194831-580ea000-ce80-11e9-9b46-103775f1142d.png)
![2019-09-03 19_22_46-Einstellungen](https://user-images.githubusercontent.com/54446791/64194832-580ea000-ce80-11e9-9ebb-50575f00ab48.png)
![2019-09-03 19_23_17-Settings - About Brave - Brave](https://user-images.githubusercontent.com/54446791/64194833-580ea000-ce80-11e9-9cdf-e46836bad7ee.png)
![2019-09-03 19_23_27-Über Brave](https://user-images.githubusercontent.com/54446791/64194834-58a73680-ce80-11e9-8d6f-7e8fc29c46f2.png)

**Comment by kjozwiak** [comment]
@DJavireX could you create an account via https://community.brave.com and message either https://community.brave.com/u/Asad or https://community.brave.com/u/mattches/. Mention this issue and tell them that you need help extracting the `payment_id`. Once you send over your `payment_id`, we can use that to see what's going on on our back-end and help you 👍
