### ISSUE TITLE
Profiles should be generated with 'Profile X' instead of 'Person X' name

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#5789]
## Description 

When creating a new profile, use 'Profile X' template.

## Steps to Reproduce

   1. Create new profile via App Menu

## Actual result:

New profile is called 'Person 2' in whatever language user is in.

## Expected result:
New profile is called 'Profile 2' in whatever language user is in.

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.70.109 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
- Logged #6339
