### ISSUE TITLE
Check all version related file when builds

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#579]
`brave-browser/package.json`, `chrome/VERSION` and `brave-core/package.json`
All these files must use same brave version.

If they have different value, unexpected behavior will be happened. (ex, install)

I think using more than one file is error prone.

**Comment by bbondy** [comment]
We're going to stop using `brave-core/package.json` and just keep it at 0.0.1

**Comment by bsclifton** [comment]
We should be good to go on this now 😄 Checks in place and most logic moved to brave-core
