### ISSUE TITLE
https://glitch.com/ is blank.

### ISSUE THREAD

**Issue by maxgrass** [brave/brave-browser#5792]
## Description 
Web site not working.

## Steps to Reproduce
   1. Login to https://glitch.com/
   2. Create new project.

## Actual result:
Blank page.

## Expected result:
Code Editor view.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the beta channel?
yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
not using shields / they are disabled.
- Does the issue resolve itself when disabling Brave Rewards?
not using rewards / they are disabled.
- Is the issue reproducible on the latest version of Chrome? 
no.

**Comment by maxgrass** [comment]
Upd: reproducible with the latest chrome version.

**Comment by bsclifton** [comment]
Confirmed this works good for me in Brave (tested using Nightly) 👍
