### ISSUE TITLE
degiro.nl is not working

### ISSUE THREAD

**Issue by maxgrass** [brave/brave-browser#5793]
## Description 
No site live content updates (ticker, numbers).
(Presumably) [Background]-Worker not working. 

## Steps to Reproduce
   1. Login to degiro.nl

## Actual result:
Static numbers and many not loaded numbers.

## Expected result:
Numbers updating every second.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Windows+Mac

Brave 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)
Revision	ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS Mac OS X

## Version/Channel Information:
rep. in all channels

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
not using b.s. (shields are disabled with the cmd argument switch)

- Does the issue resolve itself when disabling Brave Rewards?
not using b.r. (brave rewards are disabled with the cmd argument switch)

- Is the issue reproducible on the latest version of Chrome? 
no.

## Miscellaneous Information:
Sent an Email on brave support - got no answer.
As the website is a finance sensitive - I cannot do screenshots or give any credentials to test, sorry.

**Comment by ryanbr** [comment]
So Disabling sheilds helps? Could you DM on twitter @fanboynz with login details to test with?

**Comment by maxgrass** [comment]
Unfortunately sharing login details is not possible. Updated info about shields to be more clear.

The error reads:
"The resource "xxx-worker.558a610ff877ed6e2da1.js" was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally."

**Comment by varelasaraiva** [comment]
Same symptoms in version 1.1.20 macOS. Shields are down.

**Comment by niccolosanarico** [comment]
Same issue here on macOS v10.15.2 & Brave 1.1.23, nothing changes with either the shields up or down - realtime values on the dashboard do not get updated. I'm attaching two screenshots, comparing Firefox and Brave.
 
![firefox](https://user-images.githubusercontent.com/950062/71526773-b0a6f480-28d8-11ea-85be-e707ecfb5e97.png)
![brave](https://user-images.githubusercontent.com/950062/71526774-b0a6f480-28d8-11ea-9b1b-aeeb60e9fb5f.png)

Same error reported by @maxgrass on the Brave console.

**Comment by aluzardo** [comment]
Same issue here.

**Comment by aluzardo** [comment]
This is the warning in the console:

DevTools failed to parse SourceMap: chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/sourcemaps/contentscript.js.map
DevTools failed to parse SourceMap: chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/sourcemaps/inpage.js.map

**Comment by marec2000** [comment]
Same problem here.

It seems that the two files mentioned by aluzardo are missing in Brave.

**Comment by ryanbr** [comment]
Confirmed Brave Release/Beta and Nightly affected (still), Issue not related to shields.

**Comment by bsclifton** [comment]
`odbfpeeihdkbihmopkbjmoonfanlbfcl` is the ID for Crypto Wallet - @ryanml could you check this out?

**Comment by dhamit** [comment]
Still got this issue!

**Comment by ryanbr** [comment]
Just been ping'd:  https://twitter.com/tmvln/status/1239848228755050498

**Comment by ryanbr** [comment]
+1
https://community.brave.com/t/getting-real-time-updates-from-my-stock-broker/114072

**Comment by tollvam** [comment]
It seems to work now !
Brave Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit) // macOS 10.14.6

**Comment by bsclifton** [comment]
Anyone else able to give it a go?
cc: @dhamit, @marec2000, @maxgrass, @varelasaraiva, @niccolosanarico

**Comment by aluzardo** [comment]
working as expected. Thank you.
