### ISSUE TITLE
No speaker icon display for some languages

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5796]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/5561

No speaker icon display for some languages - `Malayalam`, `Kannada`, `Samoan`,`Telugu`, `Amharic` 

## Steps to Reproduce

   1. Navigate to brave://settings
   2. Visit https://www.deutschland.de/de 
   3. Install and add google translate extension to brave
   4. Click on the extension 
   5. Enter any text in the translate text box (e.g Language)
   6. Select the language 
   7. Click on the Translate button

## Actual result:

No speaker icon display for some languages

![image](https://user-images.githubusercontent.com/38657976/63649514-2c8f0580-c75c-11e9-8fe8-3247101a3d68.png)

## Expected result:
speaker icon should be displayed for all languages
## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.69.115 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

@brave/legacy_qa @yrliou

**Comment by yrliou** [comment]
I think we could close this as non actionable since this is just the behavior of Google Translate extension itself, they probably just don't support it for some languages, I tried Malayalam and it behaves the same in Chrome.
