### ISSUE TITLE
NTP `Dashboard settings` tooltip is not shown on mouse hover 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5797]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/5041
NTP `Dashboard settings` tooltip is not shown on mouse hover 

## Steps to Reproduce

   1. Open brave 0.69.115
   2. Open NTP
   3. Tooltip for settings is not shown on mouse hover

## Actual result:

NTP `Dashboard settings` tooltip is not shown on mouse hover 

![image](https://user-images.githubusercontent.com/38657976/63652478-2e69c080-c77e-11e9-8109-0669b0a2020e.png)

## Expected result:

Should show `Dashboard settings` tooltip  on mouse hover

![image](https://user-images.githubusercontent.com/38657976/63652487-480b0800-c77e-11e9-9b84-753c19c78ab5.png)

## Brave version (brave://version info)

Brave | 0.69.115 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa

**Comment by bsclifton** [comment]
cc: @cezaraugusto

**Comment by btlechowski** [comment]
Reproduced on Ubuntu

Brave | 0.69.116 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Ubuntu 18.04 LTS

**Comment by kjozwiak** [comment]
Reproduced on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.121 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

**Comment by GeetaSarvadnya** [comment]
Verification passed on

Brave | 0.70.109 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description, verified in both a clean and upgraded profile.
