### ISSUE TITLE
verified UI on rewards panel is confusing

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5798]
## Description 
Some users have reported that the UI on the Rewards panel is confusing. Specifically, around 'Verified'. The panel is telling you two things around verification:
1. If your wallet is verified (upper left corner)
2. If the publisher's page you are visiting is verified (in the middle)

In the image below users could be confused because they see Verified and unverified on the same screen. It's not immediately clear to the user that these are two different items which each have their own verification status.

<img width="373" alt="Screenshot 2019-08-26 at 10 07 14" src="https://user-images.githubusercontent.com/28145373/63697789-90144400-c7eb-11e9-9d95-03b9120f8391.png">

Would be nice if we could re-work panel UI to show all relevant information but make it clearer for the user. I believe this was brought up internally, but has also been mentioned by users outside of the org.

## Steps to Reproduce

   1. Have a verified KYC'd wallet connected to Brave Rewards.
   2. Visit a publisher who is not verified.
   3. View panel.

## Actual result:
See multiple messages on panel about Verified.

## Expected result:
Design team works their magic to make this clear for user. Maybe Rewards panel needs a simplified and advanced view like shields is getting.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.71.36 Chromium: 76.0.3809.100 (Official Build) nightly (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? yes
- Is the issue reproducible on the latest version of Chrome?  n/a

## Miscellaneous Information:
cc @brave/design @mandar-brave

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/5875
