### ISSUE TITLE
user wallets - NY loop

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5799]
## Description 
Reported by Uphold:

Users from NY enter a loop when they authorize Brave Browser.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

![jJQmP088sV](https://user-images.githubusercontent.com/28145373/63700816-a7eec680-c7f1-11e9-9006-35ae1992d304.gif)

## Expected result:
No loop. There should be some kind of error/information for NY users.

## Reproduces how often: 
unsure

## Brave version (brave://version info)
0.71.35 (Nightly)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, user wallets not on release 0.68.x
- Can you reproduce this issue with the beta channel? unsure but probably
- Can you reproduce this issue with the dev channel? unsure but probably
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @mandar-brave

**Comment by mandar-brave** [comment]
Replace Title" your request...." to "Error creating Brave Browser BAT card"
refer URL: https://uphold.com/en/brave/support

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/3282 - created a non KYC'd Uphold acct in NY (sandbox env). Then enabled rewards and tried to link that account. Verified when I was returned to brave://rewards page I saw the error message.
* Verified `here` links to an Uphold support page: https://uphold.com/en/brave/support
* Verified message text and title from https://github.com/brave/brave-browser/issues/5799#issuecomment-525343619 and https://github.com/brave/brave-browser/issues/5799#issuecomment-526023316
![Screen Shot 2019-09-05 at 1 48 44 PM](https://user-images.githubusercontent.com/28145373/64366512-607feb80-cfe4-11e9-85f2-5c55b2aec1b5.png)
* Verified that BAT can still be used in the anon state (verified I could tip a KYC'd publisher after trying to sign up with a NY account).
