### ISSUE TITLE
Add version string to brave_installer.exe

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#580]
It would be good to add version to installer executable name like `brave_intaller_67_0_50_11.exe`

**Comment by LaurenWags** [comment]
@simonhong does this need manual QA? if so, can you provide a test plan?

**Comment by simonhong** [comment]
@LaurenWags Oops! I forgot to tag. This doesn't need manual QA.

**Comment by LaurenWags** [comment]
great, thanks @simonhong 😄
