### ISSUE TITLE
default shield prevents uploading image for Uphold KYC

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5800]
## Description 
Follow up to https://github.com/brave/brave-browser/issues/4139

When I go to upload an image to complete KYC on Uphold, I get a message that I'm not uploading a supported file type. However, if I change my default FP setting to allow, then I can proceed.

## Steps to Reproduce

   1. Go to uphold.
   2. Create an acct and begin KYC.
   3. When you go to upload an image of your driver's license, you will be told your file type is incorrect.
Note - when testing this, do complete the entire KYC process (uploading all docs and a selfie, and any other information as needed).

## Actual result:
![kyc-1](https://user-images.githubusercontent.com/28145373/63715022-f3fd3380-c810-11e9-9df4-0f81d5cb1938.png)

When I go to shields I see this:
![kyc-2](https://user-images.githubusercontent.com/28145373/63715039-fb244180-c810-11e9-8135-9c406cdd5f2b.png)

![kyc-3](https://user-images.githubusercontent.com/28145373/63715052-ffe8f580-c810-11e9-8979-ec5dc897aa80.png)

## Expected result:
KYC should work easily without shield changes for users.

## Reproduces how often: 
easily

## Brave version (brave://version info)
0.69.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? probably
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? yes
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @rebron @mandar-brave @kjozwiak - we probably want this in 0.69.x due to the increased volume of users who would encounter this. I added labels per the originally reported issue. Please adjust if necessary.

Assigning to @diracdeltas per discussion with them.

**Comment by ryanbr** [comment]
We need to whitelist netverify.com on uphold.com

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.123 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3276
Works on Production.
Fails on Staging. Logged https://github.com/brave/brave-browser/issues/5891
