### ISSUE TITLE
Replace 5% settlement card with an anon address

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#5808]
Transactions sent to the non-anon card are displaying the sender.
Replace these:
const char kFeeAddressStaging[] = "7ab330ae-b7a6-4845-8f07-baab68848e4e";
const char kFeeAddressProduction[] = "532857d5-ff8b-4ca7-b9ef-5b1e40178340";

@NejcZdovc

**Comment by GeetaSarvadnya** [comment]
Verification passed on

- Verified the test plan from https://github.com/brave/brave-core/pull/3267
- 5% card balance before sending One time tip to a verified pub from fully KYC'd uphold account
![image](https://user-images.githubusercontent.com/38657976/65069352-24676600-d9a8-11e9-8611-81dd3cb1f924.png)
- After sending one time tip to verified pubs from fully KYC'd uphold account and the transaction history doesn't show name in the transaction
![image](https://user-images.githubusercontent.com/38657976/65069770-05b59f00-d9a9-11e9-897c-58223a060527.png)

![image](https://user-images.githubusercontent.com/38657976/65069874-339ae380-d9a9-11e9-9996-e981cf7635c0.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.130 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

* Requested team member with access to 5% prod card to review our tips and confirm that the 5% fee was anonymized as expected.
* Confirmed on staging 5% card that the 5% fee was anonymized as expected.
