### ISSUE TITLE
regression for sliver.tv

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#5809]
https://github.com/brave/brave-browser/issues/5380 regressed with https://github.com/brave/brave-core/pull/3130

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.122 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* ensured that I received regular coins when watching streams
* ensured that I received `TFUEL` coins when watching `TFUEL` enabled streams
* ensured that `PENDING EARNINGS` & `EARNINGS THIS SESSION` were being updated
* ensured that ~10 minutes, my earned `TFUEL` were being submitted to the `Theta Blockchain`

![Screen Shot 2019-09-03 at 8 24 02 PM](https://user-images.githubusercontent.com/2602313/64216930-1df5cc00-ce89-11e9-831d-75a2aa5338d9.png)
