### ISSUE TITLE
Migrate "Person X" default profile name to "Profile X" for all languages

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#5814]
## Description 

Related to https://github.com/brave/brave-browser/issues/5789 (generate new profiles with "Profile X" name instead of "Person X")
Related to https://github.com/brave/brave-browser/issues/5665 (rename instances of "People"/"Person" to "Profile"

## Test plan / Steps to Reproduce

   1. With a previous version of Brave
   2. Create a new profile
   3. Observe that first and new profile are created in the format "Person X" (in the user's language)
   4. Quit Brave
   5. Open the version of Brave with a fix for this issue, against that user directory used in the previous steps.
   6. Open Profiles menu in Toolbar
    ---> Observe that all profiles are now in the format "Profile X"

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.109 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS


Verified that `Person x` is renamed to `Profile x`
Before upgrade from 0.69.132
![image](https://user-images.githubusercontent.com/34715963/66359748-96641700-e978-11e9-8c0d-62a630a2b503.png)
After Upgrade to 0.70.x
![image](https://user-images.githubusercontent.com/34715963/66359776-b562a900-e978-11e9-9172-1f1f9aa5156f.png)

Verified that profiles with custom name are not renamed

Logged https://github.com/brave/brave-browser/issues/6345
