### ISSUE TITLE
Brave not working on Coinbase with shields up

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#5822]
## Description 

With shields up, the graph on coinbase is not working. 

![Coinbase](https://user-images.githubusercontent.com/7606853/63810268-35591600-c8d9-11e9-89ea-95aadd68f4d8.gif)

## Step

**Comment by ryanbr** [comment]
Tested this in Version 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit)

`https://www.coinbase.com/price/ethereum`

The graph seems to load okay

**Comment by ryanbr** [comment]
what domain is blocked in the device recognition (in sheilds)

**Comment by bsclifton** [comment]
@anthonypkeane is this still happening for you?

**Comment by anthonypkeane** [comment]
Yes

**Comment by ryanbr** [comment]
It's been a while, Just checked on a clean Brave release profile, looks good @anthonypkeane? 

![coinbase-check](https://user-images.githubusercontent.com/1659004/101604622-0a5eeb00-3a66-11eb-8c2f-bd4d5ff1a14e.gif)

**Comment by ryanbr** [comment]
Safe to close @anthonypkeane  ?
