### ISSUE TITLE
[deps issue]: 'third_party/widevine/cdm/buildflags.h' file not found

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#5825]
https://staging.ci.brave.com/job/brave-browser-build-pr/job/brave-syncer-0.69.x/8/execution/node/454/log/?consoleFull
```
14:07:45  In file included from ../../brave/browser/extensions/brave_extension_management.cc:11:
14:07:45  ../..\brave/browser/brave_browser_process_impl.h(16,10): fatal error: 'third_party/widevine/cdm/buildflags.h' file not found
14:07:45  #include "third_party/widevine/cdm/buildflags.h"
14:07:45           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
14:07:45  1 error generated.
```

`//brave/browser/extensions` doesn't have `//brave/browser/browser_process` listed as deps

cc @simonhong

**Comment by mherrmann** [comment]
This is so old and we're building with widevine daily; I don't believe this can still be an issue.
