### ISSUE TITLE
remove twitter panel support

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5828]
## Description 
Due to https://github.com/brave/brave-browser/issues/5580 we discussed removing panel support if that issue cannot be resolved in time for 0.69.x release.

This is to track that discussion.

## Miscellaneous Information:
@kjozwiak and @LaurenWags to verify that tipping only via in-line tip button (not using the panel at all) does not result in mismatch/tipping incorrect twitter user.

Placed this into 0.69.x milestone per discussion with @rebron - please move out if necessary.

**Comment by LaurenWags** [comment]
Closing this as I was able to reproduce twitter mismatch without ever utilizing (opening) the panel. I followed the steps in #5580 and tipped verified and unverified twitter users entirely with in-line tipping and was still able to reproduce a mis-match.

**Comment by LaurenWags** [comment]
cc @rebron @kjozwiak

**Comment by LaurenWags** [comment]
Per request, I also checked this without using in-line tips and ONLY tipped via panel. Still received mismatch:
1. Clean profile on 0.69.x
2. Enable Rewards
3. Navigate to twitter.com and login
4. Navigate to a page, tip thru panel. (user was unverified, not sure if this matters)
5. Navigate to another twitter page.
6. Open panel --> see mismatch on panel, shows previous user info.
![Screen Shot 2019-08-29 at 1 12 10 PM](https://user-images.githubusercontent.com/28145373/63961500-efc65580-ca5e-11e9-9625-50ca852aae7b.png)

7. Ignore and click on send tip anyway.
8. Tip banner opens --> still mismatch. URL says kamiljozwiak but banner says different user.
![Screen Shot 2019-08-29 at 1 09 05 PM](https://user-images.githubusercontent.com/28145373/63961507-f523a000-ca5e-11e9-8681-7801f5cb6472.png)

**Comment by kjozwiak** [comment]
Awesome work @LaurenWags 👍 Thanks for investigating! Looks like we'll need to basically fix Twitter tipping as it's completely broken right now as @LaurenWags proved above.

@rebron @davidtemkin @NejcZdovc @bsclifton we'll need to fix https://github.com/brave/brave-browser/issues/5580 to get Twitter into a working state.
