### ISSUE TITLE
Brave connects to translate.googleapis.com

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#5829]
## Description 
Brave proxies many requests, but one may have slipped by.

## Steps to Reproduce
1. Launch Brave from a new profile
2. Visit brave://settings

## Actual result:
Brave contacts translate.googleapis.com

## Expected result:
Brave contacts translate.brave.com (if any connection is necessary to begin with)

## Reproduces how often: 
Always (on a fresh profile)

## Brave version (brave://version info)
0.69.113

## Miscellaneous Information:

![image](https://user-images.githubusercontent.com/815158/63875485-2fbb0900-c989-11e9-8df1-22e52aa49588.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.122 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Reproduced the original issue using `0.69.119`

<img width="468" alt="Screen Shot 2019-09-03 at 10 00 25 PM" src="https://user-images.githubusercontent.com/2602313/64220613-f823f380-ce97-11e9-9134-de83a0b590a8.png">

* Verified that going into `brave://settings` doesn't contact `translate.googleapis.com`:

<img width="473" alt="Screen Shot 2019-09-03 at 10 10 45 PM" src="https://user-images.githubusercontent.com/2602313/64220592-e80c1400-ce97-11e9-84fb-18a1c65165f7.png">
