### ISSUE TITLE
Text boxes In Google drive

### ISSUE THREAD

**Issue by harooporks** [brave/brave-browser#5833]
## Description 
When device recognition shield is set to block all device recognition attempts text boxes in Google drive (Drawing and slides) break.

## Steps to Reproduce
   1. Set Brave to block all device recognition attempts.
   2. Create a text box within Google drawings, slides or even a drawing in a doc.
   3. Type a word, watch the curser stay at the front of the word
 4.Hit space and type another word, watch the words layer up on top of each other 

## Actual result:
Words are layered on top of each other.
![image](https://user-images.githubusercontent.com/37671527/63897281-b551be00-ca48-11e9-8dcb-a757d255eee0.png)
![image](https://user-images.githubusercontent.com/37671527/63897354-f2b64b80-ca48-11e9-9474-bb094cbb7258.png)

## Expected result:
The words should not layer on top of each other.
Here is the exact same document but opened on Firefox rather than brave.
![image](https://user-images.githubusercontent.com/37671527/63897589-c7802c00-ca49-11e9-85ba-0c6d62fe1adf.png)

## Reproduces how often: 
This is easily reproduced, every time a text box is loaded while brave is blocking all device recognition attempts this will happen.

## Brave version (brave://version info)
Brave | 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 10 OS Version 1903 (Build 18362.295)

This also happened before I updated to 0.68.131

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Not sure
- Can you reproduce this issue with the dev channel?
Yes
- Can you reproduce this issue with the nightly channel?
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
yes - If device recognition is set to block only cross site or allow all, text boxes work as usual.
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
I refuse to download chrome, but there is no block device recognition option so no.

## Miscellaneous Information:
Nothing else to say here

**Comment by srirambv** [comment]
Try `All device recognition attempts allowed` in shields and check if it solves the problem

**Comment by harooporks** [comment]
> Try `All device recognition attempts allowed` in shields and check if it solves the problem

Thanks, I will update the issue. I still wish to block all device recognition attempts.

**Comment by rebron** [comment]
As @srirambv mentioned you'll need to set All device recognition attempts allowed in shields for this text box feature to work.

Closing. Marking wontfix.
