### ISSUE TITLE
Add ability for users to upload their own image or pick a color for new tab background

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#5838]
##  Description 
Users should be able to upload their own image from their desktop to use as the background for their New Tab page. 

Users should be able to undo this action and go back to their previous background, as well as choose another option if they decide the background they uploaded isn't what they wanted.

Users should be able to choose a solid or gradient color to use as their background if they don't want to upload an image.

## Design [placeholder]

**Comment by btlechowski** [comment]
Another cool feature would be to have the same background as in your OS.

**Comment by b00f** [comment]
Another interested feature can have an extension to get Nat-Geo photo of the day as background. Or other similar websites.

**Comment by bartekurbanski** [comment]
it would be awesome if you could integrate with https://unsplash.com as well :)

**Comment by StefanLobbenmeier** [comment]
Also please consider chrome-extensions that provide a different new tab background. The one I tested did not overwrite the brave backgrounds, and hiding the brave background only showed the brave gradient background.

**Comment by b00f** [comment]
I think brave is going to earn money from the home page by getting some advertisements. It can be fair, we get rid of adds in other pages but in the home page we see same boring stuff.
no advertisement, no browser!

**Comment by MONaH-Rasta** [comment]
Wow! What speed! More than a year has passed, and there is still no possibility of changing default gradient background with theme or user custom image in a new tab! Great job!

**Comment by bsclifton** [comment]
@MONaH-Rasta there are a lot of competing priorities and only a set number of devs to help accomplish those goals. I did some recent work on NTP with https://github.com/brave/brave-core/pull/6584 which would make it easier to tie into InstantService to set backgrounds. This issue here is something I do intend to look at - currently working through a few other items at the moment. Next NTP related item I have planned to grab when I have free time is https://github.com/brave/brave-browser/issues/7493

**Comment by srirambv** [comment]
+1 from @Amanraj13 via #13715

**Comment by ArtexJay** [comment]
Nearly two years later and nothing on this. This should be easy for the devs to implement.

**Comment by MONaH-Rasta** [comment]
Please, take your time, no rush. We can wait another 10 years, no problem xD

**Comment by EliazBobadilla** [comment]
This is why I went back to Chrome

**Comment by ariel103856** [comment]
Hi,
is there any expectation when this option will be available?

**Comment by EricDriussi** [comment]
@ariel103856 I think [this](https://github.com/brave/brave-browser/issues/353) is the main thread. At least it's the one the NTP project links to. But other than chenkig it every once in a while I can't really see any expected date. 

Seems like it's taking quite a while, I kinda wish I could help.

**Comment by rebron** [comment]
cc: @edkazcarlson

@karenkliu Can you post the updated designs.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/15252 - see issue for updated designs (and subscribe if interested!)
