### ISSUE TITLE
People / Profile menu shows `Sync` status

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#5839]
## Description 
Starting with 0.69.x, the `People` menu is broken. It's showing Sync status:
![image](https://user-images.githubusercontent.com/4733304/63981064-6456bf80-ca72-11e9-85ef-b4e51ffedb96.png)

## Steps to Reproduce

   1. Download 0.69.x, 0.70.x, or 0.71.x
   2. If on 0.70.x or 0.71.x, you'll need to create a new profile first
   2. Click the person icon (next to hamburger) and you'll see problem (see pic above)

## Actual result:
![image](https://user-images.githubusercontent.com/4733304/63981064-6456bf80-ca72-11e9-85ef-b4e51ffedb96.png)

## Expected result:
<img width="313" alt="Screen Shot 2019-08-29 at 3 36 17 PM" src="https://user-images.githubusercontent.com/4733304/63981153-c4e5fc80-ca72-11e9-8272-47ecff4ea7f9.png">

## Reproduces how often: 
100%

## Brave version (brave://version info)
0.69.x and newer

## Version/Channel Information:

- Can you reproduce this issue with the current release? N
- Can you reproduce this issue with the beta channel? Y
- Can you reproduce this issue with the dev channel? Y
- Can you reproduce this issue with the nightly channel? Y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by petemill** [comment]
What is this meant to show before this error started showing up - does it ever show our sync status, or does it / should it never show anything ever to do with sync @rebron @bsclifton @darkdh

**Comment by rebron** [comment]
We shouldn't show the sync section at all here.

**Comment by bsclifton** [comment]
Link to PR where sync was originally removed:
https://github.com/brave/brave-core/pull/1035

**Comment by bsclifton** [comment]
Yikes - I wonder if this is related to https://github.com/brave/brave-browser/issues/5849 ?

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.125 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified STR from description
![Screen Shot 2019-09-09 at 4 45 28 PM](https://user-images.githubusercontent.com/28145373/64565211-4403ec00-d321-11e9-98fb-91d860f8707b.png)
