### ISSUE TITLE
Welcome tab needs a favicon

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#584]
## Actual result:

![image](https://user-images.githubusercontent.com/17010094/42895287-62860ba6-8a87-11e8-9a44-fe1b949f96e2.png)

**Comment by bsclifton** [comment]
master 5bacae988dc7306cf719932eab5106b616dbfbbc
0.56.x d49727e436869560d9572b4dd31ccbf4f45f8238
0.55.x dd40976a9587a5516fa6f516eb2546143ce7b264

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/46503744-bc049080-c7f9-11e8-9a20-521562bc2421.png)
