### ISSUE TITLE
PWA window closing upon clicking any links.

### ISSUE THREAD

**Issue by cocoonkid** [brave/brave-browser#5842]
## Description 

Twitter PWA and Dev.to PWA. When clicking any links they simply close.
Righ-click open link in new tab works though.

## Steps to Reproduce

   1. Install twitter or dev.to PWA
   2.  Open any 
   3. Click any link.

## Actual result:
PWA window/app is closing

## Expected result:
Link gets opened in Brave.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
yes

## Other Additional Information:

- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by rebron** [comment]
@cocoonkid Are you seeing anything in brave://crashes? If so, can you send those reports over.

**Comment by cocoonkid** [comment]
@rebron unfortunately no crash report or similar is generated. The pwa window is just closing.

**Comment by rebron** [comment]
@cocoonkid. Can you tell me what OS and version you're using?

**Comment by cocoonkid** [comment]
Brave is up to date
Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)
and
MacOS Mojave 10.14.6

I tried it on a fresh OS Install and only brave installed which results in the same problem.

**Comment by ya-d** [comment]
I experience a similar bug when using [lehrmeister.eu PWA](app.lehrmeister.eu) PWA. It repeatedly (and reproducibly) crashes when moving the window. No crash report is generated. Working stable in Chrome.

Version 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)
MacOS Catalina 10.15.2

**Comment by benlc** [comment]
Same thing with all my PWAs- it's been crashing for several version whenever I move the window on Mac. No crashes showing up in brave://crashes

Mac OS Mojave 10.14.6
Version 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)

**Comment by mstrcrz** [comment]
I am having PWA apps crash just by moving the window (clicking links is working for me).

Mac 10.14.6
Version 1.3.108 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)

**Comment by benlc** [comment]
Still happening on:
Mac OS Mojave 10.14.6
1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)

**Comment by oky2abbas** [comment]
Brave Version : `1.5.123`
OS: `macOS 10.15.4`

@rebron Unfortunately, the problem report is not received in brave: // crashes.
For more information, see: #9006

**Comment by bsclifton** [comment]
possibly related: https://github.com/brave/brave-browser/issues/7205

**Comment by iefremov** [comment]
duplicate https://github.com/brave/brave-browser/issues/7205
