### ISSUE TITLE
Incognito mode shouldn't use my history / bookmarks ?

### ISSUE THREAD

**Issue by Grafikart** [brave/brave-browser#5843]
## Description 

With Brave you merged "browse as a guest" and "incognito" but the two mode were a bit different and it's now impossible to quckly browse with blank data

## Steps to Reproduce

   1. Navigate with your main profile
   2. Open private browsing
   3. Start typing things in the omnibox, 

## Actual result:

Omnibox displays entries from the main profile history / bookmarks

## Expected result:

Incognito mode shouldn't use my profile history or bookmarks.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

0.68.132 Chromium: 76.0.3809.132

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES

## Miscellaneous Information:

You may wonder, **"what's the use case for this ?"**
- When doing a presentation you don't want your history or bookmarks shown to everyone. Having to delete / create a new profile everytime you browse with someone watching the screen is a bit annoying.
- It can be confusing for the user to see his history / bookmarks in a private browsing session.

**Comment by rebron** [comment]
Closing. Won't fix. You can use a new profile for private browsing for your desired use case.
