### ISSUE TITLE
New Tab background is cropped when vertical scrollbar is visible

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#5844]
## Steps to Reproduce

   1. Open new tab 
   2. Resize browser window so that vertical scrollbar is visible
   3. Scroll down

## Actual result:

The background is cropped at the bottom
![image](https://user-images.githubusercontent.com/34715963/64028864-b87da480-cb43-11e9-8729-90ec6d1c6b99.png)
Sometimes the settings icons are not visible
![image](https://user-images.githubusercontent.com/34715963/64028900-d1865580-cb43-11e9-8031-e32f3b744cf3.png)

## Expected result:
The background is not cropped

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.71.44 Chromium: 76.0.3809.132 (Official Build) nightly (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 7 Service Pack 1 (Build 7601.24511)

Brave | 0.70.78 Chromium: 76.0.3809.132 (Official Build) dev (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 7 Service Pack 1 (Build 7601.24511)

cc @brave/legacy_qa @cezaraugusto @imptrx

**Comment by btlechowski** [comment]
Also reproducible on beta and release, but only the background overlay is cropped

Brave | 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 7 Service Pack 1 (Build 7601.24511)

Brave | 0.69.119 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

![image](https://user-images.githubusercontent.com/34715963/64029230-799c1e80-cb44-11e9-9aa7-f0c73ccb3b82.png)
 

cc @bsclifton @rebron

**Comment by btlechowski** [comment]
Reproducible on Ubuntu 18.04

Brave | 0.69.121 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/64135647-bf7a1080-cdea-11e9-94bf-cef7e8a0d6f8.png)


Brave | 0.71.35 Chromium: 76.0.3809.100 (Official Build) nightly (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Ubuntu 18.04 LTS


![image](https://user-images.githubusercontent.com/34715963/64135654-e6d0dd80-cdea-11e9-8b49-3fd149b52a6c.png)

**Comment by BlakeJanes** [comment]
I'd like to take a crack at fixing this issue.

**Comment by btlechowski** [comment]
@BlakeJanes That's awesome! 

If you have any questions, don't hesitate to ask. 
I assigned the issue to you. If you decide not to proceed just unsigned yourself.

Good luck!

**Comment by bsclifton** [comment]
cc: @cezaraugusto who may be able to provide guidance 😄 Although not merged yet, I have some contributor guidelines which may help you get started with things
https://github.com/brave/brave-browser/pull/6265

**Comment by karenkliu** [comment]
Does this issue still apply to current images?

**Comment by btlechowski** [comment]
No longer reproducible in 0.71.x and above. Closing the issue.
Added it to 0.71.x so that it can be checked on all platforms.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.71.111 Chromium: 78.0.3904.87 (Official Build) (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Ubuntu 18.04 LTS

Verified STR from the description.

![image](https://user-images.githubusercontent.com/34715963/68349544-c7617400-00fd-11ea-85d2-f233b5ee9a1a.png)
