### ISSUE TITLE
Parent tab switching- remove or allow control

### ISSUE THREAD

**Issue by dlewand691** [brave/brave-browser#5846]
## Description 

This has also been submitted to the community forum but received no replies. 

I would like to request the option to turn off the feature of switching back to the parent tab when a tab is closed. This just started happening in the latest update and has become severely frustrating…enough so that I’m considering switching back to Chrome. It seems the “Tabs” preference section has been removed. Please add it back ASAP.

If there is a fix, please share.
If it’s a bug, please fix ASAP.
If neither, please add the option to turn off.

I’m not a fan of it and it’s frustrating to have to constantly be jumping back and forth rather than just going to the next/previous tab.

I also tried the beta version and the tabs were performing as expected.

## Steps to Reproduce

**Scenario A:**
From site #1, command-click a link to open tab #2
Close tab #1 and go to tab #2 (on the right)
Command-click link in tab #2 to open tab #3
Close tab #2 and go to tab #3 (on the right)

**Scenario B:**
From a pinned tab, command-click links to tabs #2 & #3
Got to tab #2, close it, goes to tab #3.

## Actual result:

Tabs jump back to the "parent" tab. 

## Expected result:
When closing a tab, just go to the next one to the right.

## Reproduces how often: 

What’s happening with this new behavior is that I have to keep jumping back and forth between parent and child tabs, and some times if I click on another tab that was already created beforehand, that becomes the new parent. Or if I have many tabs open, close a few, the "parent" tab from several previous tabs is selected. So it’s super frustrating to expect to go down the list of tabs but instead, jump around to parents without knowing what the parent is.

## Brave version (brave://version info)

MacOS, Brave Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
No
- Can you reproduce this issue with the dev channel?
Haven't tried
- Can you reproduce this issue with the nightly channel?
Haven't tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by bsclifton** [comment]
Thanks for the feature request, @dlewand691! This is something we did actually have in our older Electron (Muon) based browser. The version on that would be like 0.25.304 or similar

The existing behavior you're seeing is what we inherit from Chromium. As far as I know, there isn't a preference that can be changed. We could look into adding a setting, similar to what we had before

**Comment by bsclifton** [comment]
@dlewand691 I'm going to close this in favor of https://github.com/brave/brave-browser/issues/5855 where I took screenshots of the older version of Brave

Feel free to subscribe to that issue for updates or leave additional comments. Thanks! 😄

**Comment by dlewand691** [comment]
@bsclifton thanks! Having that setting added back would be fantastic if possible. I'll reach out to the Chromium team as well. Love Brave and want to keep using it but this is beyond frustrating. I'll definitely subscribe to the other issue.
