### ISSUE TITLE
Browser offers to "Sign in to Brave" when saving passwords

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#5849]
## Description 

Brave prompts users to "sign in to" Brave to get your passwords on all devices when saving a new password to the built-in PW manager. This is likely triggered due to Chrome's Sync functionality. 

![image](https://user-images.githubusercontent.com/3299098/64047287-367d8380-cb23-11e9-8547-06c8dd140b2c.png)

## Steps to Reproduce

   1. Visit a website you have an account on or register for an account
   2. When credentials are entered, select `Save` when asked if you'd like to save creds.
   3. Observe notification pictured above.

## Actual result:

[See image]

## Expected result:
Should _not_ see the prompt to "sign in to Brave".

## Reproduces how often: 

Easily/Always

## Brave version (brave://version info)

Version 0.70.78 Chromium: 76.0.3809.132 (Official Build) dev (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? ❌
- Can you reproduce this issue with the beta channel? ❌
- Can you reproduce this issue with the dev channel? ✅
- Can you reproduce this issue with the nightly channel? ❌

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes (cause Chrome has Sync)

**Comment by LaurenWags** [comment]
Reproduced with 

Brave | 0.68.141 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

**Comment by arisAlexis** [comment]
clicking sign-in redirects you to : https://no-thanks.invalid/signin/chrome/sync?ssp=1&continue=https%3A%2F%2Fwww.google.com%2F which is very confusing for new users

**Comment by bsclifton** [comment]
cc: @darkdh I think this may have regressed when landing the Syncer work (similar to how https://github.com/brave/brave-browser/issues/5839 regressed)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3566
- Verified the STR from the description

- The issue is reproducible in Beta `0.70.104 Chromium: 77.0.3865.90` and  Dev `0.71.74 Chromium: 77.0.3865.75`
