### ISSUE TITLE
Bookmarks bar only on new tab pages

### ISSUE THREAD

**Issue by Bamwempan1** [brave/brave-browser#5853]
Before we can do "Bookmarks bar only on new tab pages" I would like to know if is bug in my browser version or if this options was deleted ? 

If is delete can you embed again ?

Thanks for this job.

Brave Version : Version 0.68.132 Chromium: 76.0.3809.132 (Build officiel) (64 bits)

**Comment by bsclifton** [comment]
@Bamwempan1 thanks for checking with us - this was something that was changed. We have added back the expected behavior and that will be live in the 0.69.x version which is expected to ship ~September 10th
