### ISSUE TITLE
Items using 127.0.01:port not cached with "disable cache" off

### ISSUE THREAD

**Issue by rkeet** [brave/brave-browser#5860]
## Version
Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)

## Description 
With "dev tools" open & option "disable cache" turned _off_, items are not being cached.

Developing on 127.0.0.1:8000. 

## Steps to Reproduce

Open Dev Tools, disable option "disable cache" (so, "yes", cache it all please)

See result in screenshot (removed currently sensitive names / hashes, but left the types). Screenshot is the so-manieth refresh (3rd... 5th? plenty anyway)

![image](https://user-images.githubusercontent.com/3327864/64117628-f3771680-cd95-11e9-8a57-b530dd150da6.png)

## Actual result:
Items are still being requested each time they're needed

## Expected result:
Cached items

## Reproduces how often: 
Easy, follow reproduction steps above

## Brave version (brave://version info)
See first thing

## Version/Channel Information:

- Can you reproduce this issue with the current release?
yes, downloaded via site, possibly has had an update

- Can you reproduce this issue with the beta channel?
did not check

- Can you reproduce this issue with the dev channel?
did not check

- Can you reproduce this issue with the nightly channel?
did not check

**Comment by bsclifton** [comment]
@rkeet looks like you're using a local web server for code you're writing (node? Python?) versus having nginx or Apache setup. Are those web servers smart enough to detect ETags, cache control headers, etc? That's the only way you'd get a 304 as far as I know

I think this is working as expected. Let me know what you think 😄

**Comment by rkeet** [comment]
It actually is a local machine, [Symfony Server](https://symfony.com/doc/current/setup/symfony_server.html) ;) 

However, I'm using Brave as a "off-normal" test browser (also, we're integrating Google ads (yea yea, I know, hence Brave usage :p )). 

But, the exact same requests in Chrome / Firefox (and, sorry, Edge) are caching all of the icon gunk, so this is definitely a thing in just Brave.
