### ISSUE TITLE
Moving wallet state to browser wallet: multiple states land to this state

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#5862]
Issue: in certain fail states, the user has to move the browser to a browser (anon) wallet state. Here all are all of the states when the brave rewards system goes back to default state;

a) When trying to register for Uphold, if the registration (not KYC) fails, the browser should keep the brave rewards system in default (anon wallet) state
b) When a user disconnects (in verified / unverified Uphold state), the browser should move the wallet to default (anon wallet) state 

In this state, the brave rewards client always treats user as anon;
- all of the BR rewards moved to the verified wallet are now not accessible
- no ability to add funds
- only grants are available in this state

Part 2
User can sign on using a different account once in default state

@NejcZdovc

**Comment by NejcZdovc** [comment]
This is what you see when you disconnect 
![image](https://user-images.githubusercontent.com/9574457/64274433-ac2e8880-cf43-11e9-9e8b-632d0c88a495.png)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Ubuntu 18.04 LTS

Verified test plan from the description
Verified test plan from https://github.com/brave/brave-core/pull/3336

**Connected wallet (not KYCed)**
Panel
![image](https://user-images.githubusercontent.com/34715963/64353624-55d25000-cffe-11e9-8dd7-11ea54a30cb3.png)
`brave://rewards`
![image](https://user-images.githubusercontent.com/34715963/64353635-5bc83100-cffe-11e9-9fc7-3be369166002.png)

**Disconnected wallet (not KYCed)**
Panel
![image](https://user-images.githubusercontent.com/34715963/64354627-16a4fe80-d000-11e9-95d2-f8663bd05e08.png)

`brave://rewards`
![image](https://user-images.githubusercontent.com/34715963/64354600-0b51d300-d000-11e9-8329-34aff803d3f5.png)

Verified that by clicking `Disconnected`, uphold page was opened to reconnect the wallet. 
Verified that reconnecting wallet was successful.
