### ISSUE TITLE
Ads history is limited to 99 entries

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#5863]
## Description 

Ads history is limited to 99 entries

## Steps to Reproduce

   1. View over 99 ads

## Actual result:

Only up to 99 ads viewed during 7 days are shown in the history

## Expected result:
All ads viewed during 7 days should be shown in the history

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

See `kMaximumEntriesInAdsShownHistory` in `vendor/bat-native-ads/src/bat/ads/internal/static_values.h`

**Comment by btlechowski** [comment]
This issue is blocked on https://github.com/brave/brave-browser/issues/7743

**Comment by LaurenWags** [comment]
Marked `release-notes/exclude` and `QA/No` per discussions with @kjozwiak and @rebron 
Logged follow up issue #8046 so this can be retested with 1.4.x milestone where the blocking issue (#7743) is resolved by #6757
