### ISSUE TITLE
Limited options: tipping with default and monthly recurring tips

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#5864]
Tracking issue for two topics that are related on Brave Rewards;

a) Make default values of 1, 5, 10 to support all pre-canned values if sender is generous (this is a workflow change)

b) users are unable to tip recurring twice - we should allow users to tip twice recurring and just aggregate the values in the table.

@alexwykoff @jenn-rhim @bradleyrichter @NejcZdovc

**Comment by NejcZdovc** [comment]
@mandar-brave can you elaborate on a. What would that list be?

**Comment by NejcZdovc** [comment]
closing as stale

**Comment by agentofuser** [comment]
Would it be possible for the dropdown to continue with multiples of the top amount (currently 10 BAT) up until my full balance for instance, or some much higher amount, or infinitely scroll to N multiples?

**Comment by agentofuser** [comment]
Context: https://twitter.com/agentofuser/status/1270065308439625728

**Comment by mandar-brave** [comment]
@agentofuser bear with us - we have changed the underlying structure for how payments work. I will leave your comments here but soon enough we will work towards the notion of a custom payment; not there yet but trying to get there. Thanks
