### ISSUE TITLE
Rewards panel fails to open in 0.68.x

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#5865]
Some users are unable to open their Brave Rewards panel due to a missing `total` property. I suspect other properties are missing as well (it looks as though the `l` object wasn't initialized properly).
 
![image](https://user-images.githubusercontent.com/815158/64145832-18907700-cde0-11e9-832f-0f83ac2e0115.png)

![image](https://user-images.githubusercontent.com/815158/64133732-0ee61f80-cd9e-11e9-903e-c132e1beae02.png)

_Originally posted by @jonathansampson in https://github.com/brave/brave-browser/issues/5336#issuecomment-527245107_

**Comment by NejcZdovc** [comment]
Based on this error log, https://github.com/brave/brave-browser/issues/5336 should actually fix it. Let's wait for 69 to be released and see if this fixes them. If not we can fix it in 70 or hotfix it
