### ISSUE TITLE
3rd device doesn't show `This Device` entry in the sync chain

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5866]
## Description 

Found while testing #5770 
When three devices are in sync, the 3rd device doesn't show `This device` entry in the sync chain.

## Device

Device A: Beta (0.69.121)
Device B: Dev (0.70.80)
Device C: Nightly (0.71.57)
## Steps to Reproduce

   1. Create a sync chain in Device A
   2. Add Device B to sync chain through Sync code
   3. Add Device C to sync chain through Sync code
   4. All the 3 devices listed in the sync chain for both Device A and Device B, But `This Device` entry isn't listed in Device C 

## Actual result:

3rd device doesn't show `This Device` entry in the sync chain

![image](https://user-images.githubusercontent.com/38657976/64167853-eb87a700-ce67-11e9-9408-b784e1dc6a29.png)

## Expected result:

All the 3 devices should be displayed in the sync chain for all the three devices

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.71.57 Chromium: 76.0.3809.132 (Official Build) nightly (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @AlexeyBarabash @darkdh

**Comment by btlechowski** [comment]
Not able to reproduce on 

Brave | 0.69.121 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Ubuntu 18.04 LTS

Tried to repro 5 times.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.71.70 Chromium: 76.0.3809.132 (Official Build) dev (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 10 OS Version 1803 (Build 17134.523)

Brave | 0.72.6 Chromium: 77.0.3865.65 (Official Build) nightly (64-bit)
-- | --
Revision | 87a331a3169cab563505fb44011058b904011ba1-refs/branch-heads/3865@{#726}
OS | Windows 10 OS Version 1803 (Build 17134.523)

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the STR from the description
- Verified the sync between all the 4 channels (R-B-D-N), devices listed in each device as expected
- Verified the BM's synced in all the 4 devices
Sync between Release-Dev-Nightly
![image](https://user-images.githubusercontent.com/38657976/64491311-f9cd2d00-d284-11e9-88df-a62ce345b79e.png)

Sync between Release-Beta-Dev-Nightly
![image](https://user-images.githubusercontent.com/38657976/64491417-069e5080-d286-11e9-83c9-c8c78517e04c.png)
