### ISSUE TITLE
warning text on panel/tip banner for connected publishers - follow up to 5631

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5868]
## Description 
Follow up to https://github.com/brave/brave-browser/issues/5631#issuecomment-527459962

Warning text on panel/tip banner for a connected publisher (verified with Brave, not KYC'd with Uphold), should be different than what is currently displayed.

## Steps to Reproduce

   1. Staging profile
   2. Navigate to 3zsistemi.si
   3. Open panel and then tip banner.

## Actual result:
See text in red boxes
![Screen Shot 2019-08-30 at 6 17 31 PM](https://user-images.githubusercontent.com/28145373/64177952-806dae80-ce2e-11e9-9305-f655aad82a2c.png)
![Screen Shot 2019-08-30 at 6 17 40 PM](https://user-images.githubusercontent.com/28145373/64177961-82d00880-ce2e-11e9-8ac6-03de9caa47b1.png)

## Expected result:
For Panel
Expected text: This Brave Verified Creator has not yet configured their account to receive contributions from Brave Users. Any tips you send will remain in your wallet until they complete this process.

For Tipping Banner
Expected text: This Brave Verified Creator has not yet configured their account to receive contributions from Brave users. Your browser will keep trying to contribute until they verify, or until 90 days have passed.

## Reproduces how often: 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @mandar-brave to confirm exact text to be displayed

**Comment by mandar-brave** [comment]
Text should say ---
This verified creator has yet to verify (KYC) their account to receive tips from your verified wallet. Tips will remain in your wallet until they complete verification.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/3335 - verified text for connected publisher matches https://github.com/brave/brave-browser/issues/5868#issuecomment-527469384 on both panel and tipping banner
![Screen Shot 2019-09-05 at 12 01 43 PM](https://user-images.githubusercontent.com/28145373/64358821-265b1d80-cfd5-11e9-8eaf-a78d52aeb234.png)
![Screen Shot 2019-09-05 at 12 01 54 PM](https://user-images.githubusercontent.com/28145373/64358827-2824e100-cfd5-11e9-8476-908509b2bdcc.png)

* Verified warning text for unverified publisher did not change
![Screen Shot 2019-09-05 at 12 01 22 PM](https://user-images.githubusercontent.com/28145373/64358831-29eea480-cfd5-11e9-9486-4d07bf81946b.png)
![Screen Shot 2019-09-05 at 12 01 29 PM](https://user-images.githubusercontent.com/28145373/64358833-2bb86800-cfd5-11e9-9fec-62a74097684c.png)

* Verified that a fully KYC'd, verified publisher does not display warning text
![Screen Shot 2019-09-05 at 12 04 15 PM](https://user-images.githubusercontent.com/28145373/64358918-560a2580-cfd5-11e9-913a-dd71306e86c6.png)
![Screen Shot 2019-09-05 at 12 04 23 PM](https://user-images.githubusercontent.com/28145373/64358923-57d3e900-cfd5-11e9-8f99-16b168c05cf2.png)
