### ISSUE TITLE
Tip banner text alignment is messed on default window size

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#5870]
## Description 

Tip banner text alignment is messed on default window size

## Steps to Reproduce

   1. Clean profile on 0.69.121
   2. Do not change the default browser window size (important step)
   3.Enable Rewards
   4. Visit reddit.com/r/basicattentiontoken/
   5. Tip on different threads, see horrible text alignment

## Actual result:

:nauseated_face: 
![Screenshot from 2019-09-03 12-38-48](https://user-images.githubusercontent.com/17010094/64193818-92aa1580-ce4b-11e9-8eee-6f9a92c9c0bd.png)
![Screenshot from 2019-09-03 12-39-00](https://user-images.githubusercontent.com/17010094/64193819-92aa1580-ce4b-11e9-938b-41641d0d9750.png)

## Expected result:
Properly align the tip banner based on the size of browser window

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.69.121 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
--|--
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? most likely yes
- Can you reproduce this issue with the nightly channel? most definitely yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

May be side effect of https://github.com/brave/brave-browser/issues/2015
cc: @NejcZdovc @brave/rewards @brave/legacy_qa

**Comment by Miyayes** [comment]
Closing as stale since this is old tipping banner design.
