### ISSUE TITLE
Shield View is NOT same in Normal and TOR tab for the same site

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5872]
## Description 

Shield View is NOT same in Normal and TOR tab for the same site

## Steps to Reproduce

   1. Clean profile 0.69.121
   2. Open Buzzfeed.com in a normal tab
   3. Click on Advanced view
   4. Open TOR window and load Buzzfeed.com in a new Tor tab
   5. Shield view is Simple in TOR tab
 
   

## Actual result:

Shield View is NOT same in Normal and TOR tab for the same site

![image](https://user-images.githubusercontent.com/38657976/64195970-653b8700-cea0-11e9-8244-2d92ad5d5bd8.png)

## Expected result:

Shield View should be same in Normal and TOR tab for the same site

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.69.121 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @karenkliu @cezaraugusto

**Comment by bsclifton** [comment]
Root cause is because of this PR (will be on 0.69.x and newer):
https://github.com/brave/brave-core/pull/2973

@tomlowenthal @karenkliu is simple view OK for Tor users? This is consistent with what new users experience (they are defaulted to simple view, until they change it).

**Comment by karenkliu** [comment]
I don't remember the details of when we talked about this a long time ago...Should browsing in TOR remember the user's site-specific Shields preferences (UP/DOWN state, toggles, etc.)?

If not, then defaulting to simple view is OK.

**Comment by rebron** [comment]
cc: @tomlowenthal Should we default to Advanced View in Tor Windows?

**Comment by tomlowenthal** [comment]
I think the view shown in private/Tor should be the same as the regular session. And changing the view in private/Tor should propagate back to regular settings because it doesn't reflect anything site-specific.

**Comment by antonok-edm** [comment]
@GeetaSarvadnya I believe this is resolved - could you confirm?
