### ISSUE TITLE
Need to change 'Verified' to 'Wallet Verified' for kyc'd user

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#5875]
## Description 

Adding 'Wallet' to the wallet status 'Verified' in order to prevent the confusion with the verified creator status. Attaching the screen reference. @NejcZdovc 

![image](https://user-images.githubusercontent.com/4369856/64206267-d4888b00-ce4e-11e9-9b12-f5c6c3b6012d.png)

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/3333
![Screen Shot 2019-09-05 at 10 33 25 AM](https://user-images.githubusercontent.com/28145373/64351823-fdcd2680-cfc8-11e9-993f-b4e5a90af16f.png)
