### ISSUE TITLE
Replace Uphold logo with their updated version. 

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#5876]
## Description 

Uphold refreshed their logo with the single color version. The rainbow ballon is an old one and needs to be replaced. 

[old]
![image](https://user-images.githubusercontent.com/4369856/64206481-511b6980-ce4f-11e9-89d7-7daaf8fd67b9.png)

[new]

![image](https://user-images.githubusercontent.com/4369856/64206553-7e681780-ce4f-11e9-8fe6-d90039dcd700.png)
  

logo file:
![img-uphold-logo](https://user-images.githubusercontent.com/4369856/64206572-89bb4300-ce4f-11e9-811a-d079d6d9aa96.png)

@NejcZdovc 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
@jenn-rhim I need svg

**Comment by NejcZdovc** [comment]
svg version send by @jenn-rhim 
[uphold-logo-only.svg.zip](https://github.com/brave/brave-browser/files/3615051/uphold-logo-only.svg.zip)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.130 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

`brave://rewards` page
![image](https://user-images.githubusercontent.com/34715963/65823661-c44faa00-e25a-11e9-8987-133b747eece2.png)
![image](https://user-images.githubusercontent.com/34715963/65823662-c87bc780-e25a-11e9-8f00-7d7e0f29f238.png)
Brave Rewards Panel
![image](https://user-images.githubusercontent.com/34715963/65823664-d7fb1080-e25a-11e9-9f54-caa9635fc8b2.png)
`brave://rewards/#verify`
![image](https://user-images.githubusercontent.com/34715963/65823674-0ed12680-e25b-11e9-8fd4-5bbb280a9912.png)
