### ISSUE TITLE
Account logout on clicking link on same site

### ISSUE THREAD

**Issue by jdparkinson93** [brave/brave-browser#588]
## Description 
When log in to [Medium](https://medium.com), either by directly logging in or via Google sign-in, I am automatically logged out whenever I click on something else on the site.

So far this has only happened on the above site (it is not happening on GitHub as I'm writing this, for example).

## Steps to Reproduce
   1. Visit https://medium.com
   2. Sign in
   3. Click on something (e.g. the "my profile" section)

## Actual result:
The website asks me to log in.

## Expected result:
The page loads normally.

## Reproduces how often: 
Easily - every time. 
EDIT: After taking the shields down and putting them back up, the issue has not persisted. Now the issue does not reproduce when taking the above steps.

## Brave version (about:brave info) 
Brave: 0.23.31 
V8: 6.7.288.46 
rev: 3148acef36dba0fce89108638bb27927c4937f90 
Muon: 7.1.5 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

### Reproducible on current release:
I am using the downloadable dmg file release from the Brave browser website on macOS High Sierra 10.13.6.

### Website problems only:  
Issue is resolved when shields are lowered.
Issue is not reproducible on my Chrome browser.

### Additional Information
N/A

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/browser-laptop/issues/14781. 

Please use https://github.com/brave/browser-laptop/issues/ for current release build issues.

**Comment by jdparkinson93** [comment]
@srirambv Thanks for the link! Sorry to post in the wrong place!
