### ISSUE TITLE
Japan support: Put user-wallet (funds) and add/withdraw-funds functionality behind a flag

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#5883]
Previously, for Japan GEO we had limited crypto-in via Add-Funds to BAT only.
We, however, need further changes after 0.69 lands.

a) We have to remove any notion of user-wallet-connect via Uphold 
b) We need to have no ability to add or withdraw crypto in Japan GEO
c) Remove the Uphold logo and powered by Uphold text
d) Remove the Add-Funds in BR panel
e) Only browser wallets can be supported as per 0.68 w/o a and b functionality

Creating an umbrella issue since all of the above issues are inter-related.
cc @NejcZdovc @jsecretan

**Comment by mandar-brave** [comment]
Tagging as P1 as it is a blocker for Japan GEO at the moment.
Not prioritized for 0.69.

**Comment by mandar-brave** [comment]
@NejcZdovc this feature (no UI changes at this point) needs to land in 0.69.
One other ask is to see if we can a flag to put JPY instead of USD for Japan GEO.

cc @rebron @davidtemkin

**Comment by mandar-brave** [comment]
For Japan, remove the 
a) Uphold logo
b) Powered by Uphold branding at the bottom

@NejcZdovc

**Comment by kjozwiak** [comment]
> @NejcZdovc re: feature: no UI changes
> 
> One other ask is to see if we can a flag to put JPY instead of USD for Japan GEO (optional and can be moved to another tracking issue)
> 
> cc @rebron @davidtemkin

It doesn't seem like this has been implemented in this PR. Default currency is still appearing as `USD` rather than `JPY`. @NejcZdovc @rebron @davidtemkin expected? Do we have an issue filed for @mandar-brave request re: the above? I don't see one linked in this issue.

**Comment by davidtemkin** [comment]
@kjozwiak JPY not a requirement for this release

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.130 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from https://github.com/brave/brave-core/pull/3444#issue-317957099
<img width="1532" alt="5883-tp1-ss1" src="https://user-images.githubusercontent.com/28145373/65902497-8d77b200-e388-11e9-975f-50e6ef57df66.png">
<img width="399" alt="5883-tp1-ss2" src="https://user-images.githubusercontent.com/28145373/65902499-8f417580-e388-11e9-922c-549a811b6013.png">
<img width="393" alt="5883-tp1-ss3" src="https://user-images.githubusercontent.com/28145373/65902514-98cadd80-e388-11e9-8b0a-f9246b224d3c.png">


* Verified test plan from https://github.com/brave/brave-core/pull/3444#issuecomment-535293498
<img width="399" alt="Screen Shot 2019-09-30 at 12 59 29" src="https://user-images.githubusercontent.com/28145373/65902540-a84a2680-e388-11e9-9361-4cd0bc1834e2.png">

<img width="400" alt="Screen Shot 2019-09-30 at 12 59 20" src="https://user-images.githubusercontent.com/28145373/65902530-a3857280-e388-11e9-9db7-9c3a970e743c.png">

* Verified that Add Funds buttons are gone on upgrade, however, also encountered https://github.com/brave/brave-browser/issues/6148#issuecomment-536582997
