### ISSUE TITLE
MISSING: walletGoToVerifyPage on Verify Wallet drop down from panel - follow up to 5772

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5888]
## Description 
Follow up to #5772 

When clicking on the Verify Wallet drop down from the panel when you have a connected but not KYC'd wallet, shows:
![Screen Shot 2019-09-04 at 2 49 52 PM](https://user-images.githubusercontent.com/28145373/64282509-98732a00-cf23-11e9-814f-9d7c6272e88c.png)

It should match brave://rewards page which says 'Complete wallet verification'

## Steps to Reproduce

   1.  Clean profile 0.69.123
   2. Enable rewards, create Uphold acct or link a non-KYC'd account
   3. Click on BAT logo
   4. Click on 'Verify Wallet'

## Actual result:
![Screen Shot 2019-09-04 at 2 49 52 PM](https://user-images.githubusercontent.com/28145373/64282606-ceb0a980-cf23-11e9-92e2-61a739119c24.png)

## Expected result:
![Screen Shot 2019-09-04 at 2 45 18 PM](https://user-images.githubusercontent.com/28145373/64282609-d1130380-cf23-11e9-8212-8de82165bc1b.png)

## Reproduces how often: 
easily

## Brave version (brave://version info)
0.69.123

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? unsure, probably yes
- Can you reproduce this issue with the nightly channel? unsure, probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @mandar-brave @NejcZdovc

**Comment by NejcZdovc** [comment]
closing as it was fixed with https://github.com/brave/brave-core/pull/3336

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Ubuntu 18.04 LTS

Verified test plan from the description
Verified test plan from https://github.com/brave/brave-core/pull/3336

**Connected wallet (not KYCed)**
Panel
![image](https://user-images.githubusercontent.com/34715963/64353624-55d25000-cffe-11e9-8dd7-11ea54a30cb3.png)
`brave://rewards`
![image](https://user-images.githubusercontent.com/34715963/64353635-5bc83100-cffe-11e9-9fc7-3be369166002.png)

**Disconnected wallet (not KYCed)**
Panel
![image](https://user-images.githubusercontent.com/34715963/64354627-16a4fe80-d000-11e9-95d2-f8663bd05e08.png)

`brave://rewards`
![image](https://user-images.githubusercontent.com/34715963/64354600-0b51d300-d000-11e9-8329-34aff803d3f5.png)

Verified that by clicking `Disconnected`, uphold page was opened to reconnect the wallet. 
Verified that reconnecting wallet was successful.
