### ISSUE TITLE
Follow up: default shield prevents uploading image for Uphold KYC

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#5891]
Follow up to https://github.com/brave/brave-browser/issues/5800

## Steps to Reproduce

   1. Go to uphold.
   2. Create an acct and begin KYC.
   3. When you go to upload an image of your driver's license, you will be told your file type is incorrect.

## Actual result:

Unable to upload the image
![image](https://user-images.githubusercontent.com/34715963/64285962-dfc9dc80-cf5c-11e9-91a3-33131d170803.png)

## Expected result:
Able to upload an image

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.69.123 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @jumde @rebron

**Comment by GeetaSarvadnya** [comment]
I am facing the same issue in `Windows - 0.69.124` staging environment:

![image](https://user-images.githubusercontent.com/38657976/64340791-9f259e00-d004-11e9-842e-e7b78c29ed69.png)

**Comment by bsclifton** [comment]
I believe @jumde has a fix for this - specifically happening because it's sandbox.uphold.com, I believe

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.72.110 Chromium: 78.0.3904.70 (Official Build) dev (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3381

![image](https://user-images.githubusercontent.com/34715963/67812557-c4cca200-fa9f-11e9-9eaa-a3e0a01b3292.png)
