### ISSUE TITLE
relabel profile icons to be l10n friendly

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#5892]
## Description 
In chrome://settings/manageProfile 
change profile label names to be l10n friendly.
<img width="684" alt="Screen Shot 2019-09-04 at 1 33 31 PM" src="https://user-images.githubusercontent.com/5951041/64289484-1bdb4e00-cf19-11e9-88a9-7d2f93ec7b6a.png">

First row (left to right): Brave Orange, Orange, Yellow, Green, Light Blue
Second row (left to right): Blue, Purple, Black, Orange Dot, Yellow Slice
Third row (left to right): Green Circles, Light Blue Stripe, Blue Stripe, Purple Stripes, Black Stripes

## Steps to Reproduce

   1. On hover of each profile icon, the labels should match the description as outlined above.

**Comment by bradleyrichter** [comment]
Looks good except for a few missing CAPS.

**Comment by rebron** [comment]
Updated description with capitalized text.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.70.110 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified STR from description
<img width="1188" alt="Screen Shot 2019-10-08 at 4 08 06 PM" src="https://user-images.githubusercontent.com/28145373/66429328-d57c8180-e9e5-11e9-87a0-b3a0cf8f53fd.png">
