### ISSUE TITLE
All browser tests crashing in macOS Release builds

### ISSUE THREAD

**Issue by garrettr** [brave/brave-browser#590]
## Steps to Reproduce

1. `yarn test brave_browser_tests Release` on macOS

## Actual result:

```
[ RUN      ] NavigatorGetBatteryDisabledTest.IsDisabled
[1320:775:0718/111026.557812:ERROR:brave_extension_provider.cc(110)] Extension will not install  ID: mhjfbmdgcfjbbpaeojofohoefgiehjai,  Name: Chromium PDF Viewer
[1320:775:0718/111026.620475:FATAL:exception_processor.mm(98)] Terminating from Objective-C exception: SUNoFeedURL: You must specify the URL of the appcast as the SUFeedURL key in either the Info.plist or the user defaults!
<snip ... same ERROR/FATAL pair occurs for every subsequent test>
57 tests crashed:
```

## Expected result:

All tests pass with no crashes.

## Reproduces how often: 

Easily reproduced.

## Brave version (about:brave info) 

be15b73e1d3f11dade7425b9e7955b060815ab56

**Comment by garrettr** [comment]
Possibly related to https://github.com/sparkle-project/Sparkle/issues/1139, since Sparkle was recently integrated?

**Comment by RyanJarv** [comment]
@simonhong worked on that, he may have thoughts on the best way to handle this.

**Comment by garrettr** [comment]
Yeah, I was planning on assigning it to him if I hadn't figure it out by EOD today

**Comment by RyanJarv** [comment]
We can add it to the plist file as a work around for now if you want just as long as it's the same as what's set in the code.

**Comment by garrettr** [comment]
I've been trying to figure out how to add the missing entry to the brave_browser_tests `Info.plist`. Seems like there should be a way to use the `brave_app_plist` GN target from `brave_browser_tests`, but I haven't been able to get it working yet.

**Comment by RyanJarv** [comment]
Ah yeah should be something using `https://github.com/brave/brave-core/blob/master/build/mac/tweak_info_plist.py.`

This flag seems to be meant for changing that
> https://github.com/brave/brave-core/blob/master/build/mac/tweak_info_plist.py#L58

But seems like it's supposed to be set here.. wonder if python None doesn't equal "" in gn
> https://github.com/brave/brave-core/blob/master/brave_init_settings.gni

**Comment by RyanJarv** [comment]
Oh sorry I see what your saying, can ignore that last comment.

**Comment by simonhong** [comment]
I think this is the regression of https://github.com/brave/brave-core/pull/242/files#diff-f1d14171b87b94a6bb90877469822df3R14.
With above, sparkle update is enabled by default in official build.
We should disable update feature like https://github.com/brave/brave-browser/pull/576.
