### ISSUE TITLE
Crypto Wallets should contain Rewards disclosure statement during on-boarding

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#5901]
Concept:
![Crypto Wallets onboarding state (1)](https://user-images.githubusercontent.com/8732757/64317001-42c27000-cf6b-11e9-84f2-f5214619964d.png)

Text should be:
**Welcome to Brave Crypto Wallets**
Crypto Wallets in Brave is completely separate from Brave Rewards. This is a standalone component which lets you send, receive, and use BAT and other Ethereum assets and collectibles — as well as interacting with Ðapps and other smart contracts. This feature is meant for people who are already familiar with Ethereum or are excited to learn. If that doesn't sound like you, head over to [Brave Rewards](chrome://rewards).

Test plan:
1. Navigate to `brave://wallets` with a fresh profile
2. Dismiss disclosure modal by clicking `X`
3. Reload page
4. Click `I understand` in the disclosure modal
5. Reload and confirm the notice is gone.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

* Verified clicking on `x` button and reloading the page brings back the disclosure statement
* Verified clicking `I understand` and reloading the page doesn't show the disclosure statement again
[Linux.zip](https://github.com/brave/brave-browser/files/3683284/5901.zip)

Verification passed on 

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1903 (Build 18362.30)

* Verified clicking on `x` button and reloading the page brings back the disclosure statement
* Verified clicking `I understand` and reloading the page doesn't show the disclosure statement again
![image](https://user-images.githubusercontent.com/17010094/66080558-50502300-e534-11e9-81e5-09bc8b606ccd.png)
