### ISSUE TITLE
Username is NOT displayed in BR panel when GH profile name is empty

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5904]
## Description 

Follow up of #4987 
Username is NOT displayed in the BR panel when GH profile name is empty in the `https://github.com/settings/profile` page

## Steps to Reproduce

   1. Clean profile 0.69.124
   2. Enable Rewards
   3. Open https://github.com/Geetasarvadnya
   4. Open the BR panel
   5. Text on panel displayed as  "on GitHub"

## Actual result:

 Username is NOT displayed in BR panel when GH profile doesn't have name mentioned
![image](https://user-images.githubusercontent.com/38657976/64347027-d8640b00-d010-11e9-9183-a490ff8681eb.png)

## Expected result:
Username should be displayed in BR panel when GH profile name is empty

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA - this shows github.com in panel
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @alexwykoff

**Comment by LaurenWags** [comment]
Reproduced on macOS 

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

**Comment by btlechowski** [comment]
Reproduced on Ubuntu

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Ubuntu 18.04 LTS

**Comment by rebron** [comment]
@alexwykoff Can you take a look? How should we proceed here?

**Comment by NejcZdovc** [comment]
if name is not present we should display username

**Comment by masparrow** [comment]
@GeetaSarvadnya @LaurenWags I tried reproducing on the dev codeline (0.72.8) and the username is shown as expected (see attached picture).

Nb. I was able to reproduce on the current release (Version 0.68.132 Chromium: 76.0.3809.132), so it looks like it's been fixed/resolved since. Could you verify/recheck? Thanks!

<img width="1200" alt="Screenshot 2019-09-11 at 10 10 44" src="https://user-images.githubusercontent.com/11368284/64684198-9148a080-d47c-11e9-9d32-4d3f36155c27.png">
