### ISSUE TITLE
Optimization of publisher list db

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#5907]
1) make sure that banner is only populated if something is in it (right now we save empty rows)
2) after wallet is initialized we call download again (we should call it only once)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.125 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/3369

Verified, KYC'd publishers with custom banners:
![Screen Shot 2019-09-09 at 5 24 28 PM](https://user-images.githubusercontent.com/28145373/64568226-33a33f80-d328-11e9-9701-10b6390194e9.png)
![Screen Shot 2019-09-09 at 5 24 52 PM](https://user-images.githubusercontent.com/28145373/64568232-3736c680-d328-11e9-9897-251082927ac3.png)

Connected, no KYC publishers with custom banners:
![Screen Shot 2019-09-09 at 5 23 38 PM](https://user-images.githubusercontent.com/28145373/64568253-4584e280-d328-11e9-8d03-69052e4b0f8d.png)
![Screen Shot 2019-09-09 at 5 24 02 PM](https://user-images.githubusercontent.com/28145373/64568255-47e73c80-d328-11e9-82f4-44d12b137175.png)
![Screen Shot 2019-09-09 at 5 26 17 PM](https://user-images.githubusercontent.com/28145373/64568265-4d448700-d328-11e9-8246-d6937d535f0e.png)

Unverified publisher, no custom banner:
![Screen Shot 2019-09-09 at 5 25 07 PM](https://user-images.githubusercontent.com/28145373/64568281-59c8df80-d328-11e9-9df0-ad1d6c9edfc8.png)
