### ISSUE TITLE
Hootsuite site image editor won't render properly in Brave 

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#5911]
## Description 

https://hootsuite.com/ users are unable to edit any images/assets uploaded using the in-site editor do to constant flickering and unresponsiveness when using Brave. Images upload without issue, but attempting to edit them causes the editor to flicker wildly as shown below.
Setting `Hardware Acceleration`= `Disabled` and Shields down/allow all does not have any effect. This issue is reproducible on both macOS and Windows 10 systems.

![hootsuite](https://user-images.githubusercontent.com/3299098/64391026-ebb8ab80-cffb-11e9-98d3-1d11a87cd896.gif)

## Steps to Reproduce

   1. Visit hootsuite.com and signup/login-- they have a [free version you can use for testing ](https://hootsuite.com/plans/free-offerings)
   2. Add at least 1 social account and proceed to dashboard
   3. Click `New Post --> Upload media --> Edit Image`
   4. Attempt to transform, change or otherwise edit the newly uploaded image and observe frustrating flickering in the editor.  

## Actual result:

Image editor flickers and almost entirely unresponsive.

## Expected result:
Should be able to use the editor to adjust images and post without flickering.

## Reproduces how often: 

Always

## Brave version (brave://version info)

v0.68.132

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes ✅
- Can you reproduce this issue with the beta channel? Yes ✅ 
- Can you reproduce this issue with the dev channel? Yes ✅
- Can you reproduce this issue with the nightly channel? Yes ✅

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

Initial user report:
https://community.brave.com/t/hootsuite-display-problems/80358/2

**Comment by ryanbr** [comment]
@Brave-Matt Can you confirm its okay? I played with a few filters today:

![hoot](https://user-images.githubusercontent.com/1659004/72941574-2fa72400-3dd6-11ea-9d13-ffea61a7b392.png)

**Comment by ryanbr** [comment]
@Brave-Matt safe to close this, just wanting confirmation

**Comment by ryanbr** [comment]
Closing, we can re-open if there is any issues
