### ISSUE TITLE
Why not support non-Chinese web page translation？

### ISSUE THREAD

**Issue by git10135405** [brave/brave-browser#5912]
## Description 

I like Chinese and study very much, and I really like the brave browser. But if I can't support it or don't plan to support it, I am very sorry that I can only give up, and finally struggle!

## Steps to Reproduce

   1. 
   2. 
   3. 

## Brave version (brave://version info)

all

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
Closing. Fixed with https://github.com/brave/brave-browser/issues/5561
