### ISSUE TITLE
Notifications cannot be dismissed if `currentNotification` is not in list

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#5913]
## Description 
There may be situations (legacy, debugging, etc) where a notification was shown and is somehow stored as `state.currentNotification` in the Rewards extension.

## Steps to Reproduce

   1. Ask @bsclifton for profile if needed
   2. Put profile in place
   3. See 33 notification count on Rewards extension
   4. Click rewards extension
   5. No notification shows up

## Actual result:
No notification shown in popup

## Expected result:
Notification should be shown in the popup

**Comment by btlechowski** [comment]
Asked @bsclifton for the profile. Added QA/Blocked.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.71.93 Chromium: 77.0.3865.90 (Official Build) dev (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

Verified that notification is shown
![image](https://user-images.githubusercontent.com/34715963/66831791-c69f4d00-ef58-11e9-9e34-332b66852396.png)
Verified that user can click `OK` to dismiss the notification
Verified that user can click `x` to dismiss the notification
Verified that number of notifications is decreasing when dismissed
