### ISSUE TITLE
Google Drive Download Shared & Own Files 

### ISSUE THREAD

**Issue by rhalp10** [brave/brave-browser#5914]
## Description 

When I'm using a brave browser I always receive an error
 "**_Access to doc-0o-b0-docs.googleusercontent.com was denied you don't have authorization to view this page.
HTTP ERROR 403_**"
Even my own file still the same.

But if I select multiple files and download, the selected files will be compressed in rar. when the preparation is complete the file will download successful via self_reload when accepting js alert 
"_**Do you want to leave this page. (yes , no)**_".

## Steps to Reproduce
Download Single Shared File 
## Installed
**Browser**: Brave Version 0.67.125 Chromium: 76.0.3809.100 (Official Build) (64-bit)
**OS**: Win10 v1803(OS Build 17134.885)

**Comment by kjozwiak** [comment]
Closing as this was labelled as `closed/duplicate` in 2019! There's no need for the above to remain opened.
