### ISSUE TITLE
error tipping some publishers from KYC'd, verified wallet

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5919]
## Description 
When tipping some publishers you get an error back saying that your contribution could not be completed. Per investigation of logs by @NejcZdovc it looks like the registered publisher is not allowed to receive BAT (likely due to their region/area).

## Steps to Reproduce

   1. Clean profile on staging, enable rewards, connect KYC'd verified wallet with BAT on Brave Browser card.
   2. Visit https://www.youtube.com/watch?v=bKQ2tU6YY0o&feature=youtu.be and attempt to tip. (this publisher is verified, KYC'd on staging)
   3. You will get an error notification. 
   4. Visit https://www.youtube.com/watch?v=l2_z20o64no and attempt to tip. (this publisher is verified, KYC'd on staging)
   5. Tip goes thru.

## Actual result:
<img width="1277" alt="Screenshot 2019-09-06 at 13 56 27" src="https://user-images.githubusercontent.com/28145373/64434132-e99f2d00-d08d-11e9-8feb-150bfa266e84.png">

See this in the logs:
```
[ RESPONSE - OnCreateTransaction ]
> time: 1567778112
> result: Failure
> response: {"code":"validation_failed","errors":{"destination":{"code":"validation_failed","errors":{"currency":[{"code":"invalid","message":"This value is not valid"}]}}}}
> headers cf-ray: 5120f071afa7c5d8-EWR
> headers content-length: 161
> headers content-security-policy: default-src "none"
> headers content-type: application/json; charset=utf-8
> headers date: Fri, 06 Sep 2019 13:55:12 GMT
> headers expect-ct: max-age=0
> headers expect-staple: max-age=0; report-uri="https://uphold.report-uri.com/r/d/staple/reportOnly"
> headers rate-limit-remaining: 29993
> headers rate-limit-reset: 1567778377
> headers rate-limit-total: 30000
> headers request-id: 5120f071afa7c5d8-EWR
> headers server: cloudflare
> headers status: 400
> headers strict-transport-security: max-age=31536000; includeSubDomains
> headers vary: Origin
> headers x-content-type-options: nosniff
> headers x-frame-options: DENY
> headers x-xss-protection: 1; mode=block
[ END RESPONSE ]
```

## Expected result:
No error after tipping

## Reproduces how often: 
easily for noted publisher

## Brave version (brave://version info)

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? 0.68.x no, but 0.69.x yes
- Can you reproduce this issue with the beta channel? unsure, probably yes
- Can you reproduce this issue with the dev channel? unsure, probably yes
- Can you reproduce this issue with the nightly channel? unsure, probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @mandar-brave

**Comment by NejcZdovc** [comment]
uphold is investigating

**Comment by NejcZdovc** [comment]
this is working now, just tested it on 1.9.x
