### ISSUE TITLE
UGP grants displayed twice when ads grants are restored in staging evironment

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5921]
## Description 

UGP grants displayed twice when ads grants are restored

## Steps to Reproduce

   1. Clean profile 0.69.x - staging env
   2. Claim UGP grants
   3. Restore Ads grants
   4. UGP grants displayed twice in brave://rewards page 
   5. Refresh the page removed the duplicate UGP grants from brave://rewards

Note: This is happening only in staging env
## Actual result:

UGP grants displayed twice when ads grants are restored
![image (1)](https://user-images.githubusercontent.com/38657976/64439437-94900500-d0e7-11e9-84ae-31a9af780cd1.png)

## Expected result:
UGP grants should be displayed once

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? not sure - don't have enough ads grants to check
- Can you reproduce this issue with the dev channel? not sure
- Can you reproduce this issue with the nightly channel? not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya still a problem?
