### ISSUE TITLE
inline tip button does not work for some reddit pages

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5923]
## Description 
Originally found by @srirambv 

On certain pages, clicking on the in-line tip button on Reddit does not open the tip banner as expected.

## Steps to Reproduce

   1. Have rewards on and content level tips for Reddit enabled.
   2. Visit https://www.reddit.com/r/BasicAttentionToken/comments/cvqxnp/thanks_bat/
   3. Click on the in-line tip button

## Actual result:
Nothing happens on page above. Going to other reddit pages, the in-line tip button brings up the tip banner.
![reddit-tip](https://user-images.githubusercontent.com/28145373/64452576-af955180-d0b4-11e9-8eea-d4436f006097.gif)

## Expected result:
Tip banner should open

## Reproduces how often: 
easily on that page

## Brave version (brave://version info)

Brave | 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

Brave | 0.71.70 Chromium: 76.0.3809.132 (Official Build) dev (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @brave/legacy_qa

**Comment by masparrow** [comment]
@LaurenWags Would you happen to have another reddit comment page with a valid user which reproduces this issue? The link above now has a user [deleted]. Thanks in advance!

**Comment by LaurenWags** [comment]
@masparrow unfortunately I don't. maybe @srirambv does since he had originally reported this issue?

**Comment by masparrow** [comment]
hi @srirambv - would you be able to help with the above? thanks in advance!

**Comment by srirambv** [comment]
@masparrow sorry for the delayed response. I can still reproduce the issue on https://www.reddit.com/r/BasicAttentionToken/comments/cvqxnp/thanks_bat/. May be because the content is deleted but clicking `Tip` on the post doesn't bring up the tipping panel. Not sure if we should show tip if the post content is deleted but thats a different issue. Also on random links I find the response of the tipping panel is quite slow.
Here's a recording of it [5923.zip](https://github.com/brave/brave-browser/files/3729019/5923.zip)

**Comment by masparrow** [comment]
@srirambv that's great :) I have a potential fix so I'll raise a PR and let you know.
