### ISSUE TITLE
Issue (0.69): Default state for connected creators needs backward compatibility

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#5925]
Context:
When the user wallets were introduced, we originally asked creators to be Brave-Connected (signed up with brave) and Uphold verified (KYC'd) to get tips (V2 API)

Midway through 0/69, we updated the release to support backward where minimally the Creators that were connected were shown as verified. However, the transactions for supporting the Brave-Connected creators were not in sync with the updated change (V2 -> V3 API).

Issue:
Creators that are Brave-connected but not verified are not getting any tips via users that are on browser wallet. They are held at the browser in escrow.

Fix: 
1. Users on browser (anon) wallets should be able to tip creators that are Brave connected but not Uphold KYC'd (supporting backward compatibility).
2. Only users that are KYC'd should see the Creator-not-KYC'd message; else everyone should see creator-unverified message (so message needs to be state managed)

cc @NejcZdovc @LaurenWags @rebron @BrendanEich @davidtemkin

**Comment by mandar-brave** [comment]
Use this message when User has a user wallet (verified) encounters a connected creator but no KYC.

“For Panel
Expected text: This Brave Verified Creator has not yet configured their account to receive contributions from Brave Users. Any tips you send will remain in your wallet until they complete this process.

For Tipping Banner
Expected text: This Brave Verified Creator has not yet configured their account to receive contributions from Brave users. Your browser will keep trying to contribute until they verify, or until 90 days have passed.”

@NejcZdovc

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from https://github.com/brave/brave-core/pull/3399
   * Plan 1 & 2 passed, but encountered and logged #6182 
   * Plan 3 passed:
<img width="416" alt="plan3-ss1" src="https://user-images.githubusercontent.com/28145373/65719045-e981c400-e072-11e9-84ad-23393efc106b.png">
<img width="1195" alt="plan3-ss2" src="https://user-images.githubusercontent.com/28145373/65719049-ec7cb480-e072-11e9-983d-22b16e14f322.png">
<img width="973" alt="plan3-ss3" src="https://user-images.githubusercontent.com/28145373/65719056-ee467800-e072-11e9-9135-d8ecd0a3074e.png">
   * Plan 4 passed:
<img width="401" alt="plan4-ss1" src="https://user-images.githubusercontent.com/28145373/65719073-f7374980-e072-11e9-8a84-47ba8474eb17.png">
<img width="1194" alt="plan4-ss2" src="https://user-images.githubusercontent.com/28145373/65719079-f9010d00-e072-11e9-9b60-3f9bdd34cbf4.png">
<img width="1194" alt="plan4-ss3" src="https://user-images.githubusercontent.com/28145373/65719088-fd2d2a80-e072-11e9-940f-f089d761085f.png">
   * Plan 5 passed:
<img width="412" alt="Screen Shot 2019-09-26 at 2 57 08 PM" src="https://user-images.githubusercontent.com/28145373/65719120-12a25480-e073-11e9-926b-cbd404b1efca.png">
<img width="1193" alt="Screen Shot 2019-09-26 at 2 57 20 PM" src="https://user-images.githubusercontent.com/28145373/65719121-13d38180-e073-11e9-8255-1f4ed9c06748.png">
<img width="653" alt="Screen Shot 2019-09-26 at 2 57 39 PM" src="https://user-images.githubusercontent.com/28145373/65719123-1635db80-e073-11e9-8bc1-6bab0ccf1a3b.png">
<img width="1174" alt="Screen Shot 2019-09-26 at 2 58 02 PM" src="https://user-images.githubusercontent.com/28145373/65719128-17ff9f00-e073-11e9-8f7a-c5a930865951.png">
<img width="1173" alt="Screen Shot 2019-09-26 at 2 58 29 PM" src="https://user-images.githubusercontent.com/28145373/65719132-19c96280-e073-11e9-98d2-4426f0af34b1.png">
* Also verified that non-verified creators still display the non-verified message on panel/tip banner and tip goes to Pending list:
<img width="408" alt="Screen Shot 2019-09-26 at 3 36 05 PM" src="https://user-images.githubusercontent.com/28145373/65719266-73319180-e073-11e9-88ff-51d6991d124e.png">
<img width="1189" alt="Screen Shot 2019-09-26 at 3 36 13 PM" src="https://user-images.githubusercontent.com/28145373/65719267-7462be80-e073-11e9-8002-ec63d86ed041.png">
<img width="953" alt="Screen Shot 2019-09-26 at 3 36 30 PM" src="https://user-images.githubusercontent.com/28145373/65719271-762c8200-e073-11e9-8722-b5c6793fe163.png">
