### ISSUE TITLE
datawrapper.de maps being blocked

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#5926]
## Description 
`https://www.fresnobee.com/news/california/yosemite/article234793507.html` Maps are being blocked by Cross-site device recognition.

## Steps to Reproduce

   1.  Browse to `https://www.imidaily.com/`
   2.  Expect maps at the bottom of the site.
   3.  Need to allow all device recognition to allow to work.
   4. Blocking "https://datawrapper.dwcdn.net/" by sheilds breaks some of these sites.

## Actual result:
Blocks Maps

## Expected result:
Show Maps.

## Reproduces how often: 
Easily reproducible, if sheilds is enabled, if cross site device recognition is blocked enabled.

## Brave version (brave://version info)
`Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release?  **Yes**
- Can you reproduce this issue with the beta channel? **Yes**
- Can you reproduce this issue with the nightly channel? **Yes**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **Yes**
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
A few sites seem to implement similar urls; and some sites are affected (while others seem unaffected)

https://publicwww.com/websites/datawrapper.dwcdn.net/

`https://www.vsemirnyjbank.org/ru/news/immersive-story/2019/07/29/build-employ-and-protect-using-social-protection-to-invest-in-people-in-a-changing-world`
`https://cookpolitical.com/analysis/house/minnesota-house/mn-07-peterson-moves-lean-democratic-toss`
`https://www.imidaily.com/`

**Comment by rebron** [comment]
@ryanbr can you take a look?

**Comment by ryanbr** [comment]
Just an update, can confirm this still an issue in Release (Version 1.4.96) and Nightly (Version 1.7.50)

**Comment by ryanbr** [comment]
Can confirm this is now working. Closing.
