### ISSUE TITLE
Linking Brave Creator for Github Pages

### ISSUE THREAD

**Issue by dijonkitchen** [brave/brave-browser#5930]
## Description 

Users don't need to add `.nojekyll` file since they sidesteps the whole static site compilation process via Jekyll. 

In addition to adding the `.well-known` directory for verification, people also need to whitelist the directory so it doesn't get ignored in compilation. 

Details here: https://dcroote.github.io/2019/07/18/github-pages-brave.html

## Steps to Reproduce
Follow instructions given to creators for github page website. 

## Actual result:

Site breaks and can't verify token. 

## Expected result:
Site remains the same and token is verified. 

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```

Brave | 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X
JavaScript | V8 7.6.303.29
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extensions-install-verification=enforce_strict --enable-features=NewExtensionUpdaterService,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,NetworkService,UnifiedConsent,TranslateUI --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/jonchen/Library/Application Support/BraveSoftware/Brave-Browser/Default
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Didn't try.
- Can you reproduce this issue with the dev channel? Didn't try.
- Can you reproduce this issue with the nightly channel? Didn't try.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

N/A

**Comment by ChildishGiant** [comment]
I had to put my verification at the root site (childishgiant.github.io) and not the site I was targeting (childishgiant.github.io/example) this'll then verify all sites on that domain.

**Comment by dijonkitchen** [comment]
Yeah, there's definitely a workaround, but I couldn't find the source for the website that had the documentation. That documentation just needs to be updated.

**Comment by rebron** [comment]
Closing. Moved this issue here -> https://github.com/brave-intl/publishers/issues/2260
