### ISSUE TITLE
3rd-party cookie issues on https://freshdesk.com/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#5932]
## Description 
A couple of users on the forums have indicated 3rd-party cookie issues on https://freshdesk.com/

`https://community.brave.com/t/freshdesk-com-needs-3rd-party-cookies-enabling-but-i-cant-find-them-in-brave/81552`
`https://community.brave.com/t/freshworks-cookies-issue/77569`

## Steps to Reproduce

   1.  I haven't been able to reproduce it myself. But have noticed we are blocking a few 3rd-party cookie elements, which maybe causing issues going by the user reports

   2. Attached is a screenshot  With the following blocked.
`wchat.freshchat.com`
`freshworks.webpush.freshchat.com`
`api.freshworks.com`
`rts-us.freshworksapi.com`
`pubsub.rtschannel.com`

## Actual result:
![freshdesk](https://user-images.githubusercontent.com/1659004/64487405-597c0600-d28e-11e9-90ca-2d63b89fab5b.png)

## Expected result:

Let the site work/perform okay, not blocking these cookies the site uses.

**Comment by ryanbr** [comment]
Re-checked this (to confirm its an issue still), with `Enable Ephemeral Storage` in `Version 1.24.76 Chromium: 90.0.4430.85` (Brave Beta)

Created a temp login
![freshworks](https://user-images.githubusercontent.com/1659004/116957087-108e8600-aceb-11eb-8e70-a7e1af782f15.png)

**Comment by pes10k** [comment]
@ryanbr is this still a live issue?  Can this be closed?

**Comment by ryanbr** [comment]
Looks good, tested in Brave Nightly, Investing a new issue. Signup not working correctly. Safely close this
