### ISSUE TITLE
Redirect AMP to HTML

### ISSUE THREAD

**Issue by ChildishGiant** [brave/brave-browser#5933]
Here is a fairly good explanation as to why this would be good: https://www.reddit.com/r/AmputatorBot/comments/c88zm3/why_did_i_build_amputatorbot/

That post also includes a link to this extension that I imagine could be shipped as default:
https://github.com/da2x/amp2html

**Comment by rebron** [comment]
@ChildishGiant What platform were you looking at for this? Android?

**Comment by ChildishGiant** [comment]
Yea android was what I had in mind but also iOS if applicable.

**Comment by rebron** [comment]
cc: @AndriusA Already working on this in another issue right?

**Comment by fmarier** [comment]
Dupe of #8720, which came later but has a few more links.
