### ISSUE TITLE
Limit HSTS fingerprinting in 1p context

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#5936]
For https://github.com/brave/brave-browser/issues/3419, we blocked setting HSTS for third parties. 

HSTS fingerprinting can also be achieved in first party context, we should limit setting HSTS headers for the loaded hostname and eTLD+1 similar to: https://webkit.org/blog/8146/protecting-against-hsts-abuse/

**Comment by syverson** [comment]
Note that the countermeasures described in https://webkit.org/blog/8146/protecting-against-hsts-abuse/ do nothing to address the first party tracking and censorship described in "HSTS Supports Targeted Surveillance" (paper at https://www.usenix.org/system/files/conference/foci18/foci18-paper-syverson.pdf  code at https://github.com/pastly/satis-hsts-tracking ).

**Comment by fmarier** [comment]
A proposal from Mike West: https://github.com/mikewest/strict-navigation-security

**Comment by pes10k** [comment]
Closing this in favor of https://github.com/brave/brave-browser/issues/18830
