### ISSUE TITLE
Implement time based/navigation based expiry for site permissions

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#5937]
Currently site-permissions persist forever, implement a time-based/navigation-based expiry for site permissions like location (#5946), camera, microphone.

**Comment by iefremov** [comment]
@jumde @pes10k it seems we can close this one as this is implemented?

**Comment by pes10k** [comment]
Yep! I think you're right @iefremov .  Closing this in favor of https://github.com/brave/brave-browser/issues/14126
