### ISSUE TITLE
Show fingerprinting API on the advanced Device Recognition modal

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#5939]
The detailed `Device Recognition` modal shows a list of third parties for which fingerprinting was blocked. We should consider showing the fingerprinting API that initiated the block to give more details to the developers atleast in `dev` or `nightly` channels.

<img width="372" alt="Screen Shot 2019-09-08 at 12 35 43 PM" src="https://user-images.githubusercontent.com/1903815/64493486-910a9400-d235-11e9-9d22-4bc5490cb9e0.png">

**Comment by pes10k** [comment]
Closing this since we no longer report "device recognition attempts" since (post farbling) we get way too many false positives (since its in the 1p context too) for the info to be useful. Since this drop down is going to be removed all together, going to close this to just help keep things tidy
