### ISSUE TITLE
Brave Sync is causing crashes and bookmark duplication

### ISSUE THREAD

**Issue by mpaluta** [brave/brave-browser#5942]
## Description 
In the past ~24 hours, Brave Sync has started crashing my Brave Beta Browser on Linux repeatedly ~20 seconds after loading (repeatable 10+ times). It also duplicates bookmarks sometimes. 

Temporarily disabling Bookmark sync made the browser stable, so I can now use it. Re-enabling Bookmark syncing began the crashes again. 

See possibly related recent discussion threads [here](https://community.brave.com/t/duplicate-and-empty-bookmarks/79584) and [here](https://community.brave.com/t/brave-0-70-80-crashing-after-2-minutes/80307).

## Steps to Reproduce
(Not sure if reproducible on all Linux machines)

   1. Open Brave Beta, wait 20 seconds
   2. Browser crashes
   3. Re-open Brave Beta and disable Sync
   4. Stable
   5. Re-enable Brave Sync, wait 20 seconds
   6. Browser crashes

## Actual result:
Crashes, duplicates bookmarks and bookmark folders. Interestingly not all bookmarks/folders are affected. I have some that are duplicated 0, 1, 2, or 3 times. When the folders duplicate, sometimes the contents inside do and sometimes they do not.

Bookmarks have not been duplicated on Windows or iOS. Duplication issue appears to be local to this Linux machine only for now.

## Expected result:
Sync without crashing or duplication.

## Reproduces how often: 
Every time for me on Linux, never on Windows machine or iOS

## Brave version (brave://version info)

Brave | 0.69.119 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Linux

## Version/Channel Information:
Have not tried other versions on Linux and am not planning to unless needed. Other versions wouldn't be part of my sync chain anyway if I understand Sync limitations correctly.

## Other Additional Information:
Also in my sync chain are 2 Windows machines and 1 iOS.

## Miscellaneous Information:
Here is an example crash report. I have dozens more if needed. Let me know.
`f3083bd71ed7090e`

**Comment by mpaluta** [comment]
[Possibly related thread](https://community.brave.com/t/sync-cant-confirm-sync/81057). I see that message as well on both Linux (unstable) and Windows (stable).

[Very likely related thread](https://community.brave.com/t/brave-dev-crashes-when-it-tries-to-update-sync/80601)

**Comment by mpaluta** [comment]
Crashing and Sync error issues were fixed for me with build `Version 0.70.93 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)`. Duplicate bookmarks remain and are isolated to my Linux machine, which is a bit strange?

Will post in the cited community threads now and see if any of the noted problems persist for others.

**Comment by michaeladler** [comment]
I also had the problem of duplicated bookmarks. Crashing isn't fixed though with 0.70.93, at least on my machine. I have disabled sync now, which prevents the crashes. FWIW, I've used an extension called SuperSorter to get rid of the duplicated bookmarks.

**Comment by mpaluta** [comment]
Issue has now returned for me in `Version 0.70.97 Chromium: 77.0.3865.65 (Official Build) beta (64-bit)`

Disabling sync still works as a temporary fix to the crashes. Bookmarks were again duplicated and reordered.

**Comment by bsclifton** [comment]
This is definitely a known issue - thanks for the report! @darkdh is looking into this now and is working on some fixes

I'm going to close this issue in favor of the main tracking issue that we have:
https://github.com/brave/brave-browser/issues/6091
