### ISSUE TITLE
error compiling some shader when enabling brave shield

### ISSUE THREAD

**Issue by oToToT** [brave/brave-browser#5944]
## Description 

I got an error while viewing a website which use WebGL, while I view that website normally in Chrome or Firefox.

## Steps to Reproduce

   1. open console
   2. visit https://www.glowscript.org/#/user/GlowScriptDemos/folder/Examples/program/Bumpmaps-VPython
   3. then you would get lots of alert displaying `null`

## Actual result:

```
Uncaught Error: Shader compile error
    at makeShader (sandbox.glowscript.org/package/glow.2.9.min.js:1)
    at shaderProgram (sandbox.glowscript.org/package/glow.2.9.min.js:1)
    at subrender (sandbox.glowscript.org/package/glow.2.9.min.js:1)
    at WebGLRenderer.render (sandbox.glowscript.org/package/glow.2.9.min.js:1)
    at trigger_render (sandbox.glowscript.org/package/glow.2.9.min.js:1)
```

## Expected result:
No error occured

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Name | Description
-- | --
Brave | 0.68.132 Chromium: 76.0.3809.132 (正式版本) (64 位元)
修訂版本 | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
作業系統 | Windows 10 OS Version 1903 (Build 18362.295)
JavaScript | V8 7.6.303.29
Flash | (已停用)
使用者代理程式 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
命令列 | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extensions-install-verification=enforce_strict --enable-features=NewExtensionUpdaterService,SimplifyHttpsIndicator --disable-

## Version/Channel Information:

- Can you reproduce this issue with the current release?
yes
- Can you reproduce this issue with the beta channel?
not sure
- Can you reproduce this issue with the dev channel?
not sure
- Can you reproduce this issue with the nightly channel?
not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
yes
- Does the issue resolve itself when disabling Brave Rewards?
no
- Is the issue reproducible on the latest version of Chrome? 
no

**Comment by bsclifton** [comment]
Seems to be resolved now 😄
