### ISSUE TITLE
No landed Brave Ads confirmation in confirmations.json when focusing an already opened tab - follow up to 5195

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5949]
## Description 
Follow up to #5195 

While testing above issue, @GeetaSarvadnya noticed that she's not getting `landed` in confirmations.json when navigated to an opened tab. Per discussion with @jsecretan we probably should be getting a `landed` confirmation here (assuming criteria are met).

## Steps to Reproduce

   1. Browse such that you get Ads and open each one you get.
   2. When you get the same ad, and you open it, if there is already a tab opened for it, that tab is focused (a new tab is not opened). 
   3. Look at your confirmations.json / logs if you launched with them. You have another `view` and another `click` confirmation for this duplicate ad.

## Actual result:
no `landed` confirmation in confirmations.json when an existing tab is focused.

## Expected result:
`landed` confirmation for duplicate ad.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a on 0.68.x, yes on 0.69.x
- Can you reproduce this issue with the beta channel? unsure, probably yes
- Can you reproduce this issue with the dev channel? unsure, probably yes
- Can you reproduce this issue with the nightly channel? unsure, probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @tmancey

**Comment by stephendonner** [comment]
Verified FIXED using 

Brave | 1.20.90 Chromium: 88.0.4324.96 (Official Build) dev (x86_64)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 11.1 (Build 20C69)

Steps:
1. launched Dev using staging rewards + ads endpoints: `--args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6,"*/brave_user_model/*"=6 --brave-ads-staging --brave-ads-debug --rewards=staging=true,reconcile-interval=5`
2. opened tab with `msn.com` (far left)
3. opened `facebook.com` (right)
4. viewed and clicked on "This is a test" ad for `brave.com`, which opened and focused a new tab with `brave.com`, to the right of `facebook.com`
5. navigated back to `facebook.com` tab (now focused, in middle, with `msn.com` on left and `brave.com` on right) and waited
6. received another "This is a test" ad, which I viewed, and clicked on it
7. the tab with `brave.com` took focus (right-most tab), and in the `confirmations.json` file I see:

```
"transaction_history": {
    "transactions": [
      {
        "confirmation_type": "view",
        "estimated_redemption_value": 0.01,
        "timestamp_in_seconds": "1611797608"
      },
      {
        "confirmation_type": "click",
        "estimated_redemption_value": 0.0,
        "timestamp_in_seconds": "1611797611"
      },
      {
        "confirmation_type": "view",
        "estimated_redemption_value": 0.025,
        "timestamp_in_seconds": "1611798345"
      },
      {
        "confirmation_type": "click",
        "estimated_redemption_value": 0.0,
        "timestamp_in_seconds": "1611798383"
      },
      {
        "confirmation_type": "landed",
        "estimated_redemption_value": 0.0,
        "timestamp_in_seconds": "1611798393"
      }
    ]
```
