### ISSUE TITLE
C77 - "Distill page" button shows in omnibox

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#5951]
## Description 
Starting with Chromium 77, a "Distill page" button is shown in the omnibox
<img width="152" alt="Screen Shot 2019-09-09 at 12 29 16 PM" src="https://user-images.githubusercontent.com/4733304/64560502-77348400-d2fd-11e9-9917-ead1adcd13df.png">

This is used to provide a reader view of a given page. However, when using on internal pages like brave://welcome, it breaks:
![image](https://user-images.githubusercontent.com/4733304/64560556-90d5cb80-d2fd-11e9-9d7b-5e16967117e2.png)

## Steps to Reproduce

   1. Have a build with Chromium 77 in it
   2. Visit any page; verify `Distill page` button shows in omnibox
   3. Visit brave://welcome
   4. Click the `Distill page` button

## Actual result:
Error (as pictured in description)

## Expected result:
Either:
- no button
OR
- don't show button on internal pages

## Reproduces how often: 
100%

**Comment by rebron** [comment]
Let's hide the distill button in all cases.

**Comment by bridiver** [comment]
```
  // TODO(gilmanmh): Display icon for only those pages that are likely to
  // render well in Reader Mode.
  SetVisible(true);
```
I think we can do a chromium_src override of `ReaderModeIconView` in `OmniboxPageActionIconContainerView` and override Update to 
```
bool ReaderModeIconView::Update() {
    SetVisible(false);
    return false;
 }
```

**Comment by petemill** [comment]
Reminder for myself and @bsclifton  - this still needs uplift to 69, 70 and 71

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.134 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.523)
- Verified the test plan from https://github.com/brave/brave-core/pull/3397
- Verified the STR and test plan mentioned in the issue description
