### ISSUE TITLE
C77 - Errors logging into Uphold/Coinbase/etc

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#5952]
## Test plan
1. Navigate to coinbase.com
2. Login and verify the dashboard shows up.

Optional test plan
- run through the steps for the Coinbase partner promo
- verify the promo is able to complete

## Description 
The `x-brave-partner` header is causing requests to fail because this header is not in `Access-Control-Allow-Headers` sent by the server.

This is only happening with Chromium 77

## Steps to Reproduce

   1. Visit https://uphold.com/login?returnTo=%2Fdashboard
   2. Have a prod account (user/pass). Type this in
   3. Click `Sign In`

## Actual result:
Login doesn't work; Console shows errors

![image](https://user-images.githubusercontent.com/4733304/64560816-24a79780-d2fe-11e9-9685-db2e8401cfa8.png)

## Expected result:
Login should work

## Brave version (brave://version info)
(macOS) Version 0.72.9 Chromium: 77.0.3865.65 (Official Build) nightly (64-bit)

## Version/Channel Information:
- Can you reproduce this issue with the current release? N
- Can you reproduce this issue with the beta channel? N
- Can you reproduce this issue with the dev channel? N
- Can you reproduce this issue with the nightly channel? Y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N
- Does the issue resolve itself when disabling Brave Rewards? N
- Is the issue reproducible on the latest version of Chrome?  N

**Comment by bsclifton** [comment]
Header gets inserted via https://github.com/brave/brave-core/blob/master/browser/net/brave_referrals_network_delegate_helper.cc

List of headers fetched via https://github.com/brave/brave-core/blob/13101cfa06fef3a0df39ddbf0c68c23ea10d1db8/components/brave_referrals/browser/brave_referrals_service.cc#L450

(thanks to @pilgrim-brave and @jumde for helping me debug)

**Comment by bsclifton** [comment]
Reproduced locally on 0.68.x with Chromium 77. Investigating...

**Comment by bsclifton** [comment]
@aekeus removed Uphold from the list which fixes this particular use-case. However, it can still be a problem on other sites if they use `Access-Control-Allow-Headers`

**Comment by bsclifton** [comment]
I don't think there's any action we can take... unless there is a bug. It seems this is working as expected

The commit changing this behavior can likely be found here:
https://chromium.googlesource.com/chromium/src/+log/76.0.3809.132..77.0.3865.65/?pretty=fuller&n=10000

@mandar-brave @rebron per our triage meeting, can you check with the partner sites we support (see https://github.com/brave/brave-browser/wiki/Custom-Headers) to see if any others have breakage?

The fix (if there is breakage) would be for the folks to edit their code to add `X-Brave-Partner` to the value for the `Access-Control-Allow-Headers` header

**Comment by rebron** [comment]
@bsclifton I'll check the partner sites from here https://github.com/brave/brave-browser/wiki/Custom-Headers and see if there's breakage first and will notify via BD if there's action to be taken.

**Comment by bsclifton** [comment]
Marking this as `QA/Yes` since our latest build does have a fix for this. Will update to include test steps

**Comment by bsclifton** [comment]
Fixed in 0.68.x with https://github.com/brave/brave-core/commit/fc75c684e5e7825e8ff2ee529f0ee6c6f24b178e

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.138 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- The original issue is reproduced in 0.72.9 wherein https://www.coinbase.com/dashboard login is throwing error logs in the console
![image](https://user-images.githubusercontent.com/38657976/64942392-8c259000-d886-11e9-98ba-e441a3eda2c3.png)
 
- Verified the test plan mentioned in the issue, able to login https://www.coinbase.com/dashboard and https://uphold.com/login?returnTo=%2Fdashboard successfully
