### ISSUE TITLE
Tips should be split in to two panels on brave://rewards

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#5957]
There should be separate tables for monthly recurring and one time tips

<img width="803" alt="Screen Shot 2019-09-09 at 7 10 53 PM" src="https://user-images.githubusercontent.com/8732757/64578854-9222ea80-d335-11e9-8570-325d515a428f.png">

<img width="839" alt="Screen Shot 2019-09-09 at 7 10 46 PM" src="https://user-images.githubusercontent.com/8732757/64578856-95b67180-d335-11e9-86b0-a4cbb7d03af1.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.72.124 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3394

![image](https://user-images.githubusercontent.com/34715963/68861674-4c472180-06ec-11ea-9492-a11e61db0d17.png)
![image](https://user-images.githubusercontent.com/34715963/68861583-23bf2780-06ec-11ea-9313-798e5b62cf5c.png)
![image](https://user-images.githubusercontent.com/34715963/68861807-8c0e0900-06ec-11ea-89f9-7464b28d31a3.png)
