### ISSUE TITLE
Embed shown as empty block w/o message

### ISSUE THREAD

**Issue by tjcrowder** [brave/brave-browser#5959]
## Description 

I'm not sure if this is a bug or just an effect of using Shields. Going to [this page](https://medium.com/@jasvir/monoglots-when-a-subset-is-not-1604e3a51d9), the CodeSandBox.io embeds under "Success" near the end of the article show as blank dark grey boxes in Brave. (If you have DNT turned on, you have to click a Show Embed button first.) They work correctly in Chrome and Firefox.

Apologies in advance if this is just an expected effect of using Shields.

## Steps to Reproduce
   1. Go to https://medium.com/@jasvir/monoglots-when-a-subset-is-not-1604e3a51d9
   2. Scroll down to the "Success" section
   3. If the embeds are showing a DNT message, click the Show Embed button

## Actual result:
You get dark grey boxes rather than the CodeSandBox.io embeds.

## Expected result:
Seeing the CodeSandBox.io embeds.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)

**Brave**: 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)
**Revision**: fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
**OS**: Linux

## Version/Channel Information:

Sorry, I can't try other channels/releases at the moment.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?

Yes.

- Does the issue resolve itself when disabling Brave Rewards?

Didn't try it, looks like a Shields issue (or just an effect of using Shields).

- Is the issue reproducible on the latest version of Chrome? 

No

**Comment by rebron** [comment]
@tjcrowder Not able to reproduce on 72.x which is Nightly channel with Shields up. Do you have your global shield settings set to block all cookies or block all for device recognition?

**Comment by tjcrowder** [comment]
@rebron - I can't replicate it any more with Brave Version 0.68.140 Chromium: 77.0.3865.90, so figure it got fixed. :-)
