### ISSUE TITLE
Add refresh status to connected publisher

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5964]
## Description 

Add refresh status to connected publisher

## Steps to Reproduce

   1. Staging profile 0.69.124
   2. Enable rewards and connect existing fully KYC'd staging uphold wallet
   3. Open staging publisher website
   4. Connect fully KYC'd uphold account to your publisher account
   5. Open any of your channel which was added in publisher account
   6. Click on BR panel, panel shows the publisher is not KYC'd
   

## Actual result:

Verified publisher list is NOT pulled when KYC'd uphold is connected to the publisher account
![image (2)](https://user-images.githubusercontent.com/38657976/64599488-15e0e380-d3d7-11e9-9b3e-3cc5facdd6fc.png)

## Expected result:
Discussed with @NejcZdovc 
@NejcZdovc is going to introduce `Refresh` button in the panel to get the latest pubs list  

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.69.124 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @NejcZdovc @mandar-brave

**Comment by NejcZdovc** [comment]
this is not related to publisher status. Thing is that your list was not updated yet. What we need to do is to add refresh status option for connected publishers as well.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.90 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Ubuntu 18.04 LTS

Verified test plan from the description. `Refresh status` was added to the connected publisher. Clicking on the `Refresh status` button re-downloads whole publisher list from the server.

![image](https://user-images.githubusercontent.com/34715963/72303661-416a2800-366e-11ea-9752-69c8d4be884b.png)
