### ISSUE TITLE
NetworkServicification follow-up

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#5965]
After https://github.com/brave/brave-browser/issues/2351 some work should be done to polish the migration.
 * Initialize our URLLoader proxy before the WebRequest one in `BraveContentBrowserClient`
 * Migrate `BraveRequestHandler` and callbacks to the UI thread where possible.
 * Fix many TODOs (will update this point later)

**Comment by bsclifton** [comment]
@iefremov any QA needed for this issue? (any specific recommended tests?)

**Comment by iefremov** [comment]
@bsclifton nothing specific, but it would be nice to retest shileds/site hacks/etc

**Comment by kjozwiak** [comment]
@btlechowski @GeetaSarvadnya lets go through the following for each OS as per the above:

### Bravery settings

- [ ] Verify that HTTPS Everywhere works by loading http://https-everywhere.badssl.com/
- [ ] Turning HTTPS Everywhere off and shields off both disable the redirect to https://https-everywhere.badssl.com/
- [ ] Verify that toggling `Ads and trackers blocked` works as expected
- [ ] Visit https://testsafebrowsing.appspot.com/s/phishing.html, verify that Safe Browsing (via our Proxy) works for all the listed items
- [ ] Visit https://brianbondy.com/ and then turn on script blocking, page should not load. Allow it from the script blocking UI in the URL bar and it should load the page correctly
- [ ] Test that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/9/ when 3rd party cookies are blocked and not blank when 3rd party cookies are unblocked

### Fingerprint Tests

- [ ] Visit https://jsfiddle.net/bkf50r8v/13/, ensure 3 blocked items are listed in shields. Result window should show `got canvas fingerprint 0`  and  `got webgl fingerprint 00`
- [ ] Test that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ only when `Block all fingerprinting protection` is on
- [ ] Test that Brave browser isn't detected on https://extensions.inrialpes.fr/brave/
- [ ] Test that https://diafygi.github.io/webrtc-ips/ doesn't leak IP address when `Block all fingerprinting protection` is on

### Content tests

- [ ] Open a page with an input control and type some misspellings on a textbox, make sure they are underlined
- [ ] Make sure that right clicking on a word with suggestions gives a suggestion and that clicking on the suggestion replaces the text
- [ ] Test that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run)

**Comment by kjozwiak** [comment]
@bsclifton @iefremov other than the above cases for each OS, is there specific site hacks that we should go through?

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.139 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-browser/issues/5965#issuecomment-533153715

**Comment by bsclifton** [comment]
Reverted from release/beta
0.68.x https://github.com/brave/brave-core/pull/3523
0.69.x https://github.com/brave/brave-core/pull/3524
0.70.x https://github.com/brave/brave-core/pull/3525

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.71.93 Chromium: 77.0.3865.90 (Official Build) dev (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-browser/issues/5965#issuecomment-533153715
Verified that Shields global settings are applied
