### ISSUE TITLE
OSX - Crash when returning to Brave from 1Password

### ISSUE THREAD

**Issue by masparrow** [brave/brave-browser#5970]
## Description 
With two tabs open in Brave, I opened 1Password to manually copy/paste my GitHub account password. On returning to Brave, the browser crashed. See the attached logs & callstacks

## Steps to Reproduce

1. Launch Brave (code build, `npm start`)
2. Open https://www.reddit.com/r/BasicAttentionToken/
3. In another tab, open https://github.com/login
4. Enter a GitHub username
5. Select the Password field
6. Launch 1Password
7. Use the 'Copy' facility to obtain a password (I suspect any will do)
8. Return to Brave
[2019-09-10.zip](https://github.com/brave/brave-browser/files/3596388/2019-09-10.zip)

## Actual result:
Brave crashed instantly on return to it.

## Expected result:
User should be able to paste their password into the Password field with 'Paste' or CMD+V

## Reproduces how often: 
Intermittent issue - though it crashed 2 / 3 times

## Brave version (brave://version info)
Version 0.72.8 Chromium: 77.0.3865.65
(master hash: ef4d434663483f9de1936f533956e5fc25de9fb3)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No (Beta Channel v0.69.123)
- Can you reproduce this issue with the dev channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Not tested
- Does the issue resolve itself when disabling Brave Rewards? Not tested
- Is the issue reproducible on the latest version of Chrome? Not tested

**Comment by kjozwiak** [comment]
Can't seem to reproduce the issue using the following production builds:

* `0.68.133 Chromium: 77.0.3865.65`
* `0.72.10 Chromium: 77.0.3865.65`

@NejcZdovc @masparrow can you guys reproduce this with the latest production builds from https://github.com/brave/brave-browser/releases/? Or does this only happen with local builds only?

**Comment by kjozwiak** [comment]
Talked to @NejcZdovc via Slack, seems like this is only reproducible via local debug builds. Several folks attempted to reproduce this under production without any luck.

@NejcZdovc please correct me if I'm wrong 👍

**Comment by kjozwiak** [comment]
Waiting for results from @mkarolin to determine if this needs to go into `0.68.x` or if we can remove it from `0.68.x` and fix it in another release.

**Comment by mkarolin** [comment]
Tried to repro on both master and c77_0.68.x branches with debug build and I am not getting any crashes. Perhaps something else on your machines playing into the crash that I don't have installed?

For now un-targeting from 0.68.x-HF2

**Comment by rebron** [comment]
@masparrow can you  give us your local crash id? you're using a debug build?

**Comment by masparrow** [comment]
@rebron Alas, as a newbie I didn't capture any crash ID at the time as I was unaware of them. I was using a local debug build. 

FYI, as of Version 0.72.52 Chromium: 77.0.3865.90 (Developer Build) (64-bit) I can no longer reproduce the crash. The chances are the issue has been resolved since. @NejcZdovc have you seen it since I reported it?

**Comment by bsclifton** [comment]
Closing - let's re-open if it happens again 😄
