### ISSUE TITLE
Chromium WebUI buttons are over-eagerly re-styled for brave style

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#5977]
Our c77 rebase includes a new technique for re-styling chromium's buttons which now affect every button, not just in the components that are pre-decided.

The negative side-effect of this is that there are other instances of the `button` element which don't actually look like buttons, such as avatars:

![image](https://user-images.githubusercontent.com/741836/64641356-dc04e280-d3c0-11e9-9451-8cbe0a9b852b.png)

## Steps to Reproduce

   1. Open chrome://settings
   2. Click 'Profile name and icon'

## Actual result:

Rounded squares and image disappears on hover

## Expected result:
Circles with no hover effect

## Reproduces how often: 

100%

## Brave version (brave://version info)

70, 71, 72 with c77

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.70.110 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified STR from description
<img width="1196" alt="Screen Shot 2019-10-08 at 3 56 16 PM" src="https://user-images.githubusercontent.com/28145373/66428571-491d8f00-e9e4-11e9-9a88-435de142026a.png">
