### ISSUE TITLE
Bring in latest l10n for c77

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#5978]
We did an additional localization run to cover

• https://github.com/brave/brave-browser/issues/5816
• https://github.com/brave/brave-browser/issues/5875
• https://github.com/brave/brave-browser/issues/5862
• https://github.com/brave/brave-browser/issues/5868

cc: @kjozwiak

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.71.103 Chromium: 78.0.3904.70 (Official Build) beta (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | macOS Version 10.13.6 (Build 17G5019)

* Confirmed "Wallet Unreachable" message from #5816 is translated (used French and German to verify)
<img width="394" alt="5816-French" src="https://user-images.githubusercontent.com/28145373/67711800-248c5580-f999-11e9-8068-c5ecbd0a0bb6.png">
<img width="411" alt="5816-German" src="https://user-images.githubusercontent.com/28145373/67711804-25bd8280-f999-11e9-86a9-490e6235c4fc.png">

* Confirmed "Wallet Verified" message from #5875 is translated (used French and German to verify)
<img width="791" alt="5875-French" src="https://user-images.githubusercontent.com/28145373/67711818-2a823680-f999-11e9-852d-172c1e8d484c.png">
<img width="760" alt="5875-German" src="https://user-images.githubusercontent.com/28145373/67711823-2c4bfa00-f999-11e9-8c95-da85ddd3d59a.png">

* Confirmed "Disconnected" message from #5862 is translated (used French and German to verify)
<img width="806" alt="5862-French" src="https://user-images.githubusercontent.com/28145373/67711844-3e2d9d00-f999-11e9-82df-4a5a65cafc94.png">
<img width="794" alt="5862-German" src="https://user-images.githubusercontent.com/28145373/67711850-42f25100-f999-11e9-821c-be129435a785.png">

* Confirmed warning text on panel/tip banner for connected creators from #5868 is translated (used French and German to verify)
<img width="405" alt="5868-French" src="https://user-images.githubusercontent.com/28145373/67711877-484f9b80-f999-11e9-918f-5d009891a9f5.png">
<img width="405" alt="5868-2-French" src="https://user-images.githubusercontent.com/28145373/67711879-4980c880-f999-11e9-99f3-797634dfe426.png">
<img width="971" alt="5868-3-French" src="https://user-images.githubusercontent.com/28145373/67711883-4b4a8c00-f999-11e9-9fe8-ad421ac7cb88.png">
<img width="404" alt="5868-German" src="https://user-images.githubusercontent.com/28145373/67711884-4c7bb900-f999-11e9-8ed6-3a87143a7dde.png">
<img width="399" alt="5868-2-German" src="https://user-images.githubusercontent.com/28145373/67711887-4e457c80-f999-11e9-9f55-e2c961d8926a.png">
<img width="944" alt="5868-3-German" src="https://user-images.githubusercontent.com/28145373/67711889-4ede1300-f999-11e9-9f47-d4462114213f.png">
