### ISSUE TITLE
C77 - torrent links do not work in 0.68.133

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5979]
## Description 
Torrent links do not work in `0.68.133` (Chromium 77) but they do work in `0.68.132` (Chromium 76). Note, magnet links still work.

@GeetaSarvadnya reproduced and found that torrent links work on Nightly 0.72.11 with Chromium 77, but Nightly has a different webtorrent version.

## Steps to Reproduce

   1. Using 0.68.133 navigate to webtorrent.io/free-torrents
   2. Click on a torrent link.
  
## Actual result:
![Screen Shot 2019-09-10 at 3 25 57 PM](https://user-images.githubusercontent.com/28145373/64645898-e71d3a00-d3e3-11e9-841a-e113cceccbc3.png)

## Expected result:
(this is from Nightly)
![Screen Shot 2019-09-10 at 3 59 29 PM](https://user-images.githubusercontent.com/28145373/64645959-04ea9f00-d3e4-11e9-9a97-6fb7e3061fc8.png)

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.68.133 Chromium: 77.0.3865.65 (Official Build) (64-bit)
-- | --
Revision | 87a331a3169cab563505fb44011058b904011ba1-refs/branch-heads/3865@{#726}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 0.68.132 no, 0.68.133 yes
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? no for `0.71.72 Chromium: 76.0.3809.132 (Official Build) dev` (note, chromium 76 on dev)
- Can you reproduce this issue with the nightly channel? no for `0.72.11 Chromium: 77.0.3865.65 (Official Build) nightly` (note chromium 77 for nightly)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @brave/legacy_qa @rebron @bsclifton 

@GeetaSarvadnya noted that Nightly has webtorrent version 1.1.0 where as release channel has 1.0.0

**Comment by yrliou** [comment]
https://github.com/brave/brave-core/pull/2988/commits/70b5ff2f8ff952e80c853b8c0711e608a615dfbe
Network service uplift PR in 0.69.x and 0.68.x missed the above commit.
I cherry-pick the missing commit into c77_0.68.x, will open an uplift PR to fix it in 0.69.x too.

**Comment by yrliou** [comment]
0.69.x is soon going to be replaced by current 0.70.x so I guess it's fine to skip the uplift PR.

**Comment by btlechowski** [comment]
Reproduced on Ubuntu

Brave | 0.68.133 Chromium: 77.0.3865.65 (Official Build) (64-bit)
-- | --
Revision | 87a331a3169cab563505fb44011058b904011ba1-refs/branch-heads/3865@{#726}
OS | Ubuntu 18.04 LTS

**Comment by yrliou** [comment]
Confirmed it works after cherry-pick the missing commit into C77 0.68.x WIP branch.
cherry-pick commit: https://github.com/brave/brave-core/pull/3385/commits/55c6f6cccd8f85735690bcf3f79546617fbcf1be

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.134 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the STR from the description

![image](https://user-images.githubusercontent.com/38657976/64687566-5fe5ca00-d4a8-11e9-903a-631b74b5a194.png)
