### ISSUE TITLE
C77 - Brave safebrowsing proxy is not being used in all cases

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5980]
## Description 
While testing the safebrowsing proxy test cases for C77 update, I found a case where we were connecting to google.com instead of brave.com.

## Steps to Reproduce

   1. Have little snitch open (macOS), clear out any info for Brave Browser or Brave Browser via Brave Browser Helper.
   2. Open 0.68.133 with a clean profile.
   3. Wait until the connection to safebrowsing.brave.com has been made (about 8 minutes).
   4. Visit https://testsafebrowsing.appspot.com/
   5. Click on the link next to Desktop Download Warnings > 1. Should show a "malicious" warning, based on content and download the file.
   6. File download is blocked in download bar.
   7. Look at Little Snitch.

## Actual result:
See connection to sb-ssl.google.com

![Screen Shot 2019-09-10 at 5 21 51 PM](https://user-images.githubusercontent.com/28145373/64651904-906a2d00-d3f0-11e9-9747-133cf07693dd.png)

## Expected result:
Should see connection to sb-ssl.brave.com as you do on 0.68.132:
![Screen Shot 2019-09-10 at 5 36 07 PM](https://user-images.githubusercontent.com/28145373/64652331-9b718d00-d3f1-11e9-84b0-0ef176c4a533.png)

## Reproduces how often: 
easily

## Brave version (brave://version info)
0.68.133

## Version/Channel Information:

- Can you reproduce this issue with the current release? 0.68.132 no, but 0.68.133 yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @brave/legacy_qa @rebron @bsclifton

**Comment by fmarier** [comment]
This is a regression of #4328.

**Comment by LaurenWags** [comment]
Same result when clicking the second link under Desktop Download Warnings:
![Screen Shot 2019-09-10 at 5 48 14 PM](https://user-images.githubusercontent.com/28145373/64653037-577f8780-d3f3-11e9-92dd-dd494a687c7a.png)

**Comment by fmarier** [comment]
I verified that https://github.com/brave/brave-core/pull/2377 is present in the branch, including the unit test. After building it, I was able to confirm that the unit test passes. I checked that the unit test actually runs and it does. So I'm not sure what's wrong, but it's probably at a higher level.

**Comment by LaurenWags** [comment]
Issue also reproduces on Nightly

Brave | 0.72.11 Chromium: 77.0.3865.65 (Official Build) nightly (64-bit)
-- | --
Revision | 87a331a3169cab563505fb44011058b904011ba1-refs/branch-heads/3865@{#726}
OS | macOS Version 10.13.6 (Build 17G5019)

![Screen Shot 2019-09-11 at 3 13 55 PM](https://user-images.githubusercontent.com/28145373/64727513-03ce7600-d4a7-11e9-8c1b-a73149002498.png)
