### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by sushihangover** [brave/brave-browser#5983]
## Description 

"Physically" Clicking (or using "Tap to Click" trackpad option) the Like (❤️) button causes Instagram to display the following "Action Blocked" dialog:

![Screen Shot 2019-09-10 at 11 41 11 PM](https://user-images.githubusercontent.com/1294194/64674002-8530f480-d424-11e9-9b46-bf6560e5be6d.png)

Note: this is w/ or w/o the "Shields Up" feature enabled for the IG site.

Performing the same function using Safari|Firefox|Edge with the same IG account on the same Mac, the Like function works without error dialog.

## Steps to Reproduce

   1.  Load IG site (logged in)
   2. Click a Like button 

## Actual result:

![Screen Shot 2019-09-10 at 11 41 11 PM](https://user-images.githubusercontent.com/1294194/64674002-8530f480-d424-11e9-9b46-bf6560e5be6d.png)

## Reproduces how often: 

Always reproducible 

## Brave version (brave://version info)

```
Brave	0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)
Revision	fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS	Mac OS X
JavaScript	V8 7.6.303.29
Flash	(Disabled)
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
Command Line	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extensions-install-verification=enforce_strict --enable-features=NewExtensionUpdaterService,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,TranslateUI,NetworkService,UnifiedConsent --flag-switches-begin --flag-switches-end
Executable Path	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path	/Users/sushi/Library/Application Support/BraveSoftware/Brave-Browser/Default

```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?

No

- Does the issue resolve itself when disabling Brave Rewards?

No

- Is the issue reproducible on the latest version of Chrome? 

YES

Google Chrome is up to date
Version 77.0.3865.75 (Official Build) (64-bit)

**Comment by rebron** [comment]
@sushihangover This seems like this might be a policy issue on the instagram? We would need some more info on this anyhow such as screenshots or screen vid of the issue?

**Comment by ryanbr** [comment]
Just tested some likes on current Brave Release `Version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)`  Seems to be working here. @sushihangover  can you re-check?

**Comment by ryanbr** [comment]
Closing ticket, given the age. Everything seems to be working here
