### ISSUE TITLE
One-time tip data reset to Zero after upgrade/browser restart

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#5987]
## Description 

One-time tip data reset to Zero after upgrade/browser restart, refresh brave://rewards page resolves the issue
This issue is only happening with chromium 77. The issue is Reproducible in both Nightly and Release 

`0.68.134 Chromium: 77.0.3865.75 -Release` - Reproduced
`0.72.11 Chromium: 77.0.3865.65-Nightly` - Reproduced
`0.68.132 Chromium: 76.0.3809.132- Released` - Not Reproducible
`0.71.72 Chromium: 76.0.3809.132- Dev` - Not Reproducible
`0.70.93 Chromium: 76.0.3809.132 -Beta` - Not Reproducible
## Steps to Reproduce

STR1:

     1. Clean profile 0.68.134
     2. Enable rewards and restore a key which has the balance
     3. Send a one time tip to verified pubs
     4. Click on `Exit` in the hamburger menu
     5. Restart the browser
     6. Tip data reset to zero in both tips panel as well as in rewards summary section
     7. Refresh brave://rewards page
     8. Tip data is shown as expected   
STR2:

     1. Clean profile 0.68.132
     2. Enable rewards and restore a key which has the balance
     3. Send a one-time tip to a verified publisher
     4. Upgrade to 0.68.134
     5. One-time tip data reset to Zero after upgrade
     6. Refresh brave://rewards page
     7. Tip data is shown as expected

## Actual result:

Tip panel:

![image](https://user-images.githubusercontent.com/38657976/64688342-cd462a80-d4a9-11e9-8c41-f9a41084d226.png)

Rewards summary:

![image](https://user-images.githubusercontent.com/38657976/64688371-dd5e0a00-d4a9-11e9-8411-f4dce3f5e048.png)

## Expected result:

One-time tip data shouldn't reset to Zero after upgrade/browser restart

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.68.134 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @NejcZdovc

**Comment by LaurenWags** [comment]
If I don't have the brave://rewards page open on upgrade this doesn't reproduce for me. If my brave://rewards page is open, the issue does reproduce. However, refreshing the brave://rewards page doesn't fix it for me, I need to close and reopen that page.

The steps I used were:
 1. Clean profile 0.68.134
 2. Enable rewards and restore a key which has the balance
 3. Send a one time tip to verified pubs
 4. Keep Rewards page open and in focus. Close Brave from top menu bar or cmd+Q (macOS).
 5. Restart the browser
 6. Tip data reset to zero in rewards summary section
 7. Close and reopen brave://rewards page
 8. Tip data is shown as expected

**Comment by LaurenWags** [comment]
Also, I encountered https://github.com/brave/brave-browser/issues/5336 ** a lot** while trying to reproduce this issue. Unsure if maybe the white box is easier to get on this version, or if it was my steps, but here's what I was doing:

 1. Clean profile 0.68.134
 2. Enable rewards and restore a key which has the balance
 3. Send a one time tip to verified pubs
 4. Keep Rewards page open and in focus. Close Brave from top menu bar or cmd+Q (macOS as there is no Exit in hamburger menu on macOS).
 5. Restart the browser
 6. Tip data reset to zero in rewards summary section
 7. Click on panel.
--> Error message shown over wallet balance on brave://rewards and white box for panel. Error message goes away, but white box on panel is permanent and cannot be recovered from.

**Comment by NejcZdovc** [comment]
@LaurenWags 5336 was fixed in 69, so maybe worth talking about pulling it into 68 + 77

**Comment by GeetaSarvadnya** [comment]
@LaurenWags I have encountered the issue #5336 twice today, STR is mentioned below.

1. Clean profile 0.68.132 staging flags
2. Complete the a-c 
3. Upgrade to 0.68.134
4. Restart the browser and launch using staging flags
5. Click on BR panel showing the white popup
6. Complete the a-c in .134
7. Click on BR panel unable to see a-c summary in BR panel due to white popup

**Comment by kjozwiak** [comment]
Removing from the `0.68.x` release but we should definitely fix this sooner than later. Users might get confused when the state doesn't update right away whenever Rewards is being used.

**Comment by kjozwiak** [comment]
@NejcZdovc moving this back into `0.68.x`. With `0.68.136 Chromium: 77.0.3865.75`, restarting will clear all the data via `Activity Summary` as mentioned above but this time around, refreshing `brave://rewards` won't restore the lost data. Example of the issue occurring:

![rewardsIssue](https://user-images.githubusercontent.com/2602313/64892637-f64df300-d642-11e9-97ac-2d89ceb0fa73.gif)

**Comment by kjozwiak** [comment]
@NejcZdovc as per the above, once the data disappears via `Activity Summary`, you won't be able to get it back with a refresh of `brave://rewards`.

**Comment by bsclifton** [comment]
Fixed in 0.68.x with https://github.com/brave/brave-core/pull/3432

That patch needs to be PRed against master / 0.71.x / 0.70.x / 0.69.x

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.138 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR mentioned in the issue
- Verified the STR from the https://github.com/brave/brave-browser/issues/5987#issuecomment-530360875 - Tip data is displayed as expected after browser restart
- Verified the https://github.com/brave/brave-browser/issues/5987#issuecomment-530364300 and 
https://github.com/brave/brave-browser/issues/5987#issuecomment-530437455 - BR panel is displayed as expected there is no white popup
