### ISSUE TITLE
Yahoo doesn't scroll properly

### ISSUE THREAD

**Issue by gcdef** [brave/brave-browser#5988]
Windows 10, Brave Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)

Yahoo displays 5 or 6 stories, then a big gap where I assume an ad is, then starts again at the top of the stories.  Won't go past the ad

**Comment by rebron** [comment]
@gcdef Are you still seeing this? We're not able to reproduce. Yahoo! has made some changes recently. Can you try again?

**Comment by bsclifton** [comment]
Closing - let's re-open if it's still an issue 😄 Thanks!
