### ISSUE TITLE
Option to disable Google Translate extension popup

### ISSUE THREAD

**Issue by silvertreesystems-div** [brave/brave-browser#5989]
Each time I open a page in foreign language I see annoying popup that asks for installing google translate extension. I don't need translation, but, unfortunately, I did not find option to disable this 'feature'.

Thanks.

**Comment by silvertreesystems-div** [comment]
Had to upgrade to recent version first. Issue disappeared. Sorry for bother.

**Comment by The-Clockmaker** [comment]
How did you manage to get rid of it? My brave is up to date and this popup is just spamming the living shit out of me, every damn page "would you like to install google translate extension?". It's driving me insane and making me seriously consider dumping brave. Is there really no way at all to disable this crap?

**Comment by FrancescoMussi** [comment]
Thanks @The-Clockmaker. It was very annoying!

**Comment by iHani** [comment]
> How did you manage to get rid of it? My brave is up to date and this popup is just spamming the living shit out of me, every damn page "would you like to install google translate extension?". It's driving me insane and making me seriously consider dumping brave. Is there really no way at all to disable this crap?
> 
> Edit: nvm, found it burried under settings -> additional settings -> languages -> language -> offer to translate pages that aren't in a language you read.
> Seriously guys what the hell, way too intrusive, not good!

I don't see this option there "offer to translate pages that aren't in a language.."!

I'm using Brave Version 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)

Any suggestions?

**Comment by FrancescoMussi** [comment]
@iHani you have to click the dropdown at the right
