### ISSUE TITLE
create wallet spinner on panel doesn't show on second monitor

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#5990]
## Description 
When joining Rewards from the panel, the 'Join Rewards' button should turn to 'Creating wallet' button with a spinner. This happens on my main laptop screen with both 0.68.132 (C76) and 0.68.134 (C77). However, if I do this on my second monitor, the button does not change when using 0.68.134.

## Steps to Reproduce

   1. Using a second monitor, launch a clean profile with 0.68.134
   2. Click on panel
   3. Click on Join Rewards

## Actual result:
Button text does not change, spinner does not show:
![createwalletspinner-068134](https://user-images.githubusercontent.com/28145373/64703517-97d61880-d47a-11e9-8165-f3f284c445aa.gif)

## Expected result:
Behaves as it does in 0.68.132:
![createwalletspinner-068132](https://user-images.githubusercontent.com/28145373/64703531-9efd2680-d47a-11e9-84a9-cef0a86276b9.gif)

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.68.134 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 0.68.132, no 0.68.134 yes
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
cc @bsclifton @rebron since related to c77

**Comment by NejcZdovc** [comment]
@LaurenWags still a problem?

**Comment by LaurenWags** [comment]
no longer an issue. closing this one.
