### ISSUE TITLE
Add new Monthly Contribution banner for publishers

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#5996]
Design: 
<img width="841" alt="Screen Shot 2019-09-11 at 6 55 52 PM" src="https://user-images.githubusercontent.com/8732757/64748110-d93fe580-d4c5-11e9-98fb-e0554c47293f.png">

Prompt within the panel:
<img width="505" alt="Screen Shot 2019-09-11 at 6 56 59 PM" src="https://user-images.githubusercontent.com/8732757/64748143-f4aaf080-d4c5-11e9-8c8b-9a42ab7d76a0.png">

Test Plan:
1. Enable Brave Rewards, Deposit BAT
2. Navigate to a verified publisher, hit the rewards icon
3. Click the `Send a Tip` button
4. Confirm that the regular tip banner shows up as expected, with no option to check monthly.
5. Complete the tip and confirm that it processes via the tip table
6. Navigate to the above publisher (or another verified publisher)
7. Click the `Send` button in the Monthly Contribution row
8. Confirm the new monthly tip banner variant appears
9. Complete the contribution and verify that it shows up as a monthly contribution
10. Navigate back to the last publisher, hit the rewards icon
11. Confirm that you can change the monthly contribution amount via the panel

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.1.4 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan mentioned in the issue.
