### ISSUE TITLE
Private & Tor tabs should "Reopen closed tab" and the tabs should open in the order they were closed

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#5997]
Have you searched for similar issues? Yes.

## Description 
Currently Private and Tor windows don't allow users to reopen any closed tab. 

## Steps to Reproduce
Pretty obvious.

## Actual result:
"Reopen closed tab" is not available to click and thus can't reopen any tab.

## Expected result:
"Reopen closed tab" should be available and when reopening closed tabs, the tabs should open in the order they were closed

## Reproduces how often: 
Easily reproduced.

## Brave version (brave://version info)
Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit) (on OpenSuse)

## Other Additional Information:

The part of reopening tabs in the order they were closed should also be the same for normal browsing as well. Right now they seem to open in a different order.

The same issue also used to occur with the Muon version, I figured it would have automatically been fixed with the Chromium push.

Thanks for looking.

**Comment by rebron** [comment]
Closing. We're going to wait for this implementation upstream.

**Comment by NumDeP** [comment]
Hi @rebron I've never know this for sure but when the team says the're going to wait for an upstream implementation, do they mean a fix that naturally comes with the integration of the latest version of Chromium?

This issues wasn't an issue before, as I can remember reopening tabs in private tabs at least I'm a little sure. It's been so long that I've actually forgotten and as you can probably tell I created this issue over a year ago and not being able to reopen closed tabs is so frustrating.
