### ISSUE TITLE
Switch to 24 hour ad payment token cash ins

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#5999]
## Description 
Right now, after a user sees ads, the browser will wait an exponentially distributed time averaging 7 days.  This was chosen initially to safely keep the two token streams distinct and unlinkable.  However, after analysis of a few months of data, our current scale is more than enough to keep these two streams unlinkable even with 24 hour check ins.

There are some tangible benefits to this.  This will make sure that tokens are kept protected and accounted server side sooner in the case of client data loss.  It will also payouts less confusing because they will more accurately reflect the monthly cycle.

We have run this by @evq and @riastradh-brave to make sure we are good but we should file an official security review issue when this work is complete.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.1.1 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

* Per discussion with @tmancey ,
   * Confirmed on a clean profile that after enabling Rewards, the `next_token_redemption_date_in_seconds` in `confirmations.json` was set to be in 24h (confirmed via epochconverter.com)
   * Confirmed on an upgrade profile that after tokens were redeemed/cashed in, the `next_token_redemption_date_in_seconds` in `confirmations.json` was set to be in 24h (confirmed via epochconverter.com)
