### ISSUE TITLE
Prevent extensions from intercepting Safe Browsing and updates requests

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#6003]
Chromium has [code](https://cs.chromium.org/chromium/src/extensions/browser/api/web_request/web_request_permissions.cc?rcl=a367b3f7bd249d6e3feb13ee250b83baf821f3f3&l=319-329) to prevent extensions from tampering with Chrome Store, updates, or Safe Browsing URLs which is based on these hard-coded lists of [Safe Browsing](https://cs.chromium.org/chromium/src/extensions/common/extension_urls.cc?l=105-111&rcl=a367b3f7bd249d6e3feb13ee250b83baf821f3f3) and [updates](https://cs.chromium.org/chromium/src/chrome/common/extensions/chrome_extensions_client.cc?l=180-191&rcl=eef03ba00533a95a5b3b0ee5eb81c71ef1a0cc60) URLs.

However, since we [proxy Safe Browsing requests](https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs), an extension could intercept the final URLs (`sb-ssl.brave.com`, `safebrowsing.brave.com`, or [`safebrowsing2.brave.com`](https://github.com/brave/brave-browser/issues/4674)).

**Comment by bridiver** [comment]
Safebrowsing requests use a different network context (similar to the system network context) that is not connected to extensions. This should be double-checked after @jumde merges the safe browsing changes for network service just to be 100% sure.

**Comment by fmarier** [comment]
Safe Browsing was changed to a different network context in https://github.com/brave/brave-core/pull/3415.

**Comment by jumde** [comment]
> Safebrowsing requests use a different network context (similar to the system network context) that is not connected to extensions. This should be double-checked after @jumde merges the safe browsing changes for network service just to be 100% sure.

Discussed this with @fmarier offline, needs some more testing to see if this is still a problem with different NetworkContextManagers in place. 

@fmarier - brave/brave-core#3415 just ads a proxy for SafeBrowsing requests. SafeBrowsing network context is set here: https://cs.chromium.org/chromium/src/chrome/browser/safe_browsing/safe_browsing_service.cc?l=111

**Comment by fmarier** [comment]
I have just confirmed that this is not needed. My [webRequest-based extension](https://github.com/fmarier/webRequest-demo) wasn't able to intercept the Safe Browsing update requests.
