### ISSUE TITLE
Enable Cayman Islands and some other protectorates/territories for Brave Ads

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#6006]
## Description 
Need to enable some additional territories/protectorates for Brave Ads, including the following country codes:

KY

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` label pending discussion about testing cc @kjozwiak

**Comment by LaurenWags** [comment]
Per discussion with @jsecretan and @kjozwiak I am marking this as `QA/No` since QA could not test this one. However, as a sanity check, confirmed with Brave staff in KY that ad notifications are being generated for them.
