### ISSUE TITLE
Add fingerprinting exception for 1password.com

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#6007]
`map.1passwordservices.com` uses WebGL, add a temporary fingerprinting exception for 1password.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.72.112 Chromium: 78.0.3904.70 (Official Build) dev (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3425

![image](https://user-images.githubusercontent.com/34715963/67856503-f9c70c00-fb14-11e9-8a6d-5c192d6b11e6.png)
