### ISSUE TITLE
Fix Canvas Fingerprinting in third-party context

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#6008]
Canvas apis are used for valid reasons in third-party context. Instead of blocking the APIs completely in third-party context we should insert noise to avoid reliable fingerprinting by trackers. 

Remove fingerprint exceptions for uphold and sandbox.uphold once this is fixed: https://github.com/brave/brave-core/blob/master/common/shield_exceptions.cc#L45

**Comment by pes10k** [comment]
fixed by https://github.com/brave/brave-core/pull/4792

**Comment by pes10k** [comment]
@jumde can the exceptions you mentioned be removed now?
