### ISSUE TITLE
Fix WebGL Fingerprinting in third-party context

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#6009]
WebGL apis are used for valid reasons in third-party context. Instead of blocking the APIs completely in third-party context we should insert noise to avoid reliable fingerprinting by trackers.

Remove fingerprint exceptions for 1password.com in shield_exceptions.cc once this is fixed.

**Comment by pes10k** [comment]
@jumde This will be merged extremely shortly. I'm not familiar with the 1password.com exception though; could you pull it once the below PR lands?

https://github.com/brave/brave-core/pull/4792/files

**Comment by pes10k** [comment]
Fixed by https://github.com/brave/brave-core/pull/4792
