### ISSUE TITLE
Configurable default tip amounts

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#6011]
Make default tip values configurable via server.
a) one set of values for one-time contributions https://github.com/brave-intl/bat-ledger/pull/721
b) another set of values for monthly recurring contributions https://github.com/brave-intl/bat-ledger/pull/723

**Comment by evq** [comment]
server implemented in https://github.com/brave-intl/bat-ledger/pull/721

**Comment by NejcZdovc** [comment]
@mandar-brave based on the fact that we are splitting monthly contribution and tip flow, should we have two defaults? One set for monthly and one for tip?

**Comment by mandar-brave** [comment]
Yes; my understanding was that monthly a/c had a default that could be controlled by the server?

**Comment by NejcZdovc** [comment]
@mandar-brave I am talking about monthly contributions not AC. @evq me and @mandar-brave discussed this via DM and could you please add monthly contribution default amounts as well. Flow will split on desktop so we need to have defaults separate. Thank you

**Comment by mandar-brave** [comment]
Yes, we should have both amounts for monthly contributions (tips) available as server set!

**Comment by evq** [comment]
merged in https://github.com/brave-intl/bat-ledger/pull/723

**Comment by kjozwiak** [comment]
@evq @NejcZdovc is there anything that we should check on the server side of things? Or is running through https://github.com/brave/brave-core/pull/3848#issue-335190551 sufficient enough to call this verified?

**Comment by NejcZdovc** [comment]
@kjozwiak nothing that I can think of
