### ISSUE TITLE
Rewards panel shows white popup

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#6012]
## Description 

Discussed with @NejcZdovc over the call, this issue is slightly different from the issue #5336, The white popup issue gets resolved if we restart the browser/profile where we encountered the BR panel white popup issue. Hence opened the new issue

## Steps to Reproduce

STR1:
   1. Clean profile 0.68.132 with staging flags
   2. Enable rewards, add a site to a-c table and complete the auto contribution
   3. Upgrade to 0.68.135
   4. Close the brave by selecting `Exit` from the hamburger menu
   5. Restart the browser using staging flags
   6. Click on BR panel shows the white popup
   6. Add a site to a-c table and complete the auto contribution in 0.68.135
   7. Click on BR panel unable to see a-c summary in BR panel due to white popup
   8. Repeat steps 4 and 5
   9. BR panel white popup issue resolves, Join rewards popup displayed

STR2:

    1. Clean profile 0.68.135
    2. Join rewards from the panel but don't visit brave://rewards page.
    3. Close Brave by selecting `Exit` from the hamburger menu
    4. Restart the browser
    5. Click on panel.
    6. The panel shows white popup
    7. Repeat the steps 3 and 4
    8. BR panel white popup issue resolves, Join rewards popup displayed

STR 3:

    1. Clean profile 0.68.135
    2. Enable rewards and restore a key which has the balance
    3. Send a one time tip to verified pubs
    4. Keep Rewards page open and in focus. Close the brave by selecting `Exit` from the hamburger menu
    5. Restart the browser
    6. Tip data reset to zero in rewards summary section
    7. Click on panel.
    8. The error message is shown over wallet balance on brave://rewards and white box for the panel. Error message goes away, but the white box on the panel is permanent and cannot be recovered from.
    9. Close the browser by clicking on Exit in the hamburger menu
    10. Restart the browser
    11. Click on panel 
    12 BR panel white popup issue resolves, Join rewards popup displayed

## Actual result:

Rewards popup shows white popup, restart the browser resolves the issue and displayed Join rewards popup

Recorded files:
https://drive.google.com/open?id=1k6c-Dm9eSlTb50SvO4VN_otIfLMuwCu2
https://drive.google.com/open?id=1tz6CeS9Wxtt5OGWGix5HoucpKOzIOS0b
https://drive.google.com/open?id=1jqc0kacHipgOE_MCAOShPMkWiZmJeZOi

## Expected result:

White popup shouldn't be shown in the BR panel

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.68.135 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@NejcZdovc @brave/legacy_qa

**Comment by NejcZdovc** [comment]
Fixed in 0.68.x with brave/brave-core#3432

That patch needs to be PRed against master / 0.71.x / 0.70.x / 0.69.x

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.138 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
