### ISSUE TITLE
"Join Rewards" is being displayed in the rewards panel when restarting Brave

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6015]
## Description 

Reported by both @GeetaSarvadnya and @rebron, whenever you restart `0.68.136 Chromium: 77.0.3865.75` the rewards panel will default to `Join Rewards` even though rewards has been enabled. Because a restart is required when Brave is updated, a good % of our user base has the potential to run into the above.

## Steps to Reproduce

**`Test Case 1`**

   1. launch `0.68.136 Chromium: 77.0.3865.75`
   2. enable `rewards` via the panel
   3. once enabled/wallet created, restart the browser
   4. click on the reward panel and you'll see "Join Rewards" even though the wallet is created

You can repeat the above several times and you'll notice that the panel keeps reverting back to "Join Rewards"

**`Test Case 2`**

   1. launch `0.68.132 Chromium: 76.0.3809.132` (current release)
   2. enable `rewards` via the panel
   3. once enabled/wallet created, update to `0.68.136 Chromium: 77.0.3865.75`
   4. click on the reward panel and you'll see "Join Rewards" even though the wallet is created

## Actual result:

![rewardsIssue](https://user-images.githubusercontent.com/2602313/64893530-46c65000-d645-11e9-9f41-afec68b0dac1.gif)

<img width="1275" alt="Screen Shot 2019-09-13 at 4 43 10 PM" src="https://user-images.githubusercontent.com/2602313/64893646-96a51700-d645-11e9-9b1f-96041de62763.png">

## Expected result:

Once you've joined rewards and created a new wallet, the panel shouldn't be displaying "Join Rewards" after a restart.

## Reproduces how often: 

100% reproducible when going through the above STR.

## Brave version (brave://version info)

Brave | 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release? No, not reproducible using `0.68.132 Chromium: 76.0.3809.132 (Official Build`
- Can you reproduce this issue with the beta channel? No, not reproducible using `0.70.93 Chromium: 76.0.3809.132 (Official Build) beta`
- Can you reproduce this issue with the dev channel? Yes, reproducible using `0.71.73 Chromium: 77.0.3865.75 (Official Build) dev`
- Can you reproduce this issue with the nightly channel? Yes, reproducible using `0.72.23 Chromium: 77.0.3865.75 (Official Build) nightly`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @rebron @GeetaSarvadnya @NejcZdovc @bsclifton

**Comment by bsclifton** [comment]
Fixed in 0.68.x with https://github.com/brave/brave-core/pull/3432

That patch needs to be PRed against master / 0.71.x / 0.70.x / 0.69.x

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.138 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description

**Comment by rebron** [comment]
Fix looks good on 0.68.138 Chromium: 77.0.3865.75 (Official Build) (64-bit), macOS with old and new profile.
