### ISSUE TITLE
SSB - "Single Site Browser" Brave Browser

### ISSUE THREAD

**Issue by ylluminate** [brave/brave-browser#6019]
An enormous surprise for many people over the last several years has been how SSBs were hushed and swept under the rug by so many of the primary innovators that were at first talking about them and had been huge proponents of the concept.

At the end of the day, after talking to a lot of people, it was interesting to find out that the main reason that the "Single Site Browser" concept was swept under the rug and hushed so effectively was due to the high value of cookies and cross pollination.  I won't go into any more details, but Brave sure seems to be an ideal candidate to appreciate the situation and simultaneously appreciate the extremely high value of being able to use a browser as an SSB.

Over the last few years I've been using a project called [Epichrome](https://github.com/dmarmor/epichrome) that has been amazing.  I've been able to consolidate my web usage behavior to certain to topics / categories and down to specific sites when desired.  For example, I can keep eBay and all of its associated information in an eBay browser, Amazon the same, and many others.  I can also consolidate everything that pertains to a specific customer into a single instance of Chrome or the same with a project or any other such manner of organization.  I then use the "History Trends Unlimited" extension to stop Chrome from losing my history every quarter. 

That has made my life a lot easier in some regards, but Chrome itself has made my life more complicated at the same time.  Chrom(e|ium) is not made for this kind of usage.  Even though I have a lot of system memory, I find that Chrome eats memory like nothing I've ever seen.  It has a lot of other bugs and the "Great Wall of Google" makes it nigh impossible to get meaningful feedback to and FROM developers - even with Chromium.  I hate it and it makes me angry since I have so many issues, that if resolved, could make everyone's lives better.  these are issues that result from the way I use the browser and vs the (unreasonable) expectations they have or want to force on users. 

Brave may be a fork of Chromium, but I believe it's better in a few ways: 1) it's more transparent and collaborative, 2) it's goal is safety, protection and compartmentalization for users, and 3) it tries to reduce bloat by removing unnecessary and insecure aspects.

In this regard Brave is a perfect fit for the SSB concept since its very concept and goals lines up with all of these goals.

As far as this concept goes, there are two paths (and perhaps both should be followed):
1) Fork [Epichrome](https://github.com/dmarmor/epichrome) > Epibrave. This works relatively well, but there are issues with memory consumption and process management between the helpers that spawn, etc.

2) Develop a mechanism that allows a single shared library of Brave to be used across all instances of dedicated Brave SSBs so as to minimize the memory requirements. While this is not exactly the solution I'm thinking of, [this excellent article by Electrino's creator](https://medium.com/dailyjs/put-your-electron-app-on-a-diet-with-electrino-c7ffdf1d6297) gives some great understanding of the situation and possible solutions.

Ultimately Brave could take an enormous place on every person's desktop if it could become a viable SSB solution provider and furthermore could address the bloat issue that comes from Electron.  It seems as though if there were a way to share libraries across each instantiation of Brave then it could be possible to use it as an Electron and even (Epi)Chrome alternative.

**Comment by bsclifton** [comment]
@ylluminate have you looked at PWA (progressive web apps)? These are currently supported by Brave (and of course, Chrome/Chromium). For example, you can go to Twitter and save a shortcut to the "Twitter app". This basically makes a desktop app you can run, which uses Brave. Much like the single site browser you're mentioning

More info here:
https://developers.google.com/web/progressive-web-apps/desktop

**Comment by ylluminate** [comment]
Hi @bsclifton, thanks for the suggestion...  Unfortunately I don't really understand how this applies to my remarks.  Could you please elaborate?  I'm not drawing a correlation between the usage pattern I outlined vs PWAs that don't really exist for 99% of the sites that I use...

**Comment by bsclifton** [comment]
@ylluminate sorry for the extra large turn-around here; my fault for losing track of this

I think the concept of SSB is something we won't be able to address. Projects like Epichrome seem to be the right type of answer for that problem.

Without forking, I was trying to share that PWAs allow you to pin a website (like Twitter) as it's own application. I don't know if this sandboxes the sites on a per-app basis though, it's likely using the default profile and the behavior inherited there
