### ISSUE TITLE
Disable new extension APIs for non-brave extensions

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#602]
New APIs defined here should be available for only brave blessed_extensions - `common/extensions/api/brave_shields.json`

**Comment by bbondy** [comment]
QA steps:
Go to the background page of any extension, check in the console if this is defined: `chrome.braveShields` it should be undefined but `chrome` should be defined.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux
--|![image](https://user-images.githubusercontent.com/17010094/46036327-3e42d580-c0d3-11e8-9bb4-933f84d4b2e0.png)
