### ISSUE TITLE
Overflow-x occuring in Brave, but not Chrome browser.

### ISSUE THREAD

**Issue by orro3790** [brave/brave-browser#6027]
Brave does not seem to recognize the overflow-x: hide css feature, although it works fine when tested in Chrome.

**Comment by rebron** [comment]
@orro3790 can you attach a test case?

**Comment by bsclifton** [comment]
Closing as there hasn't been a response (yet). I wonder if this is new to Chromium 77? If so, we have released since this issue was created 😄
