### ISSUE TITLE
Enable strict site isolation by default

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#603]
https://github.com/brave/browser-laptop/issues/14766

**Comment by bbondy** [comment]
We have this enabled by default now with C68

**Comment by diracdeltas** [comment]
@bbondy it shows up still as disabled in chrome://flags/#enable-site-per-process
![screen shot 2018-07-30 at 8 36 34 pm](https://user-images.githubusercontent.com/549654/43436257-6ab7482a-9438-11e8-9001-901556e75fa3.png)


tested on MacOS Version 0.53.0 Chromium: 68.0.3440.68 (Official Build) dev (64-bit)

**Comment by bbondy** [comment]
Per the steps here:
https://www.chromium.org/Home/chromium-security/site-isolation#TOC-Verifying

I believe it's enabled. I think the chrome://flags setting is no longer used. 
You can also see a quick recap on chrome://process-internals which shows it working. 
I verified with Chrome's task manager with the test case they describe above though and it seems to be working correctly. 

Let me know if I'm missing something or not though, it wouldn't be hard to also enable that flag. But I think the UI for the flag will be removed in an upcoming Chromium version. Unless I'm not understanding that the flag does something extra.  Please lmk @diracdeltas.  Thanks for checking!

**Comment by diracdeltas** [comment]
if the listed test plan works, closing this sgtm.

if there is a more general issue that chrome://flags in brave doesn't reflect reality, maybe we should either fix that or just don't display the flags for release.

**Comment by btlechowski** [comment]
Verification passes on

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

Checked chrome://process-internals and test case from https://www.chromium.org/Home/chromium-security/site-isolation#TOC-Verifying
