### ISSUE TITLE
Hide rewards button doesn't work

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#6033]
## Steps to Reproduce

   1. Go to chrome://settings/appearance
   2. Click on Hide Brave Rewards button

## Actual result:

Nothing happens

## Expected result:
BAT logo in url should hide

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by masparrow** [comment]
chrome://settings/appearance redirects to brave://settings/appearance (as you'd expect)
Clicking on 'Hide Brave Rewards button' the Rewards icon in the URL bar hides immediately _before_ enabling rewards...
If you then show rewards, enable rewards, and then try to Hide Rewards, the icon no longer hides.

**Comment by NejcZdovc** [comment]
@masparrow thank you for the research. Now I remember about this one. @davidtemkin is this correct behaviour that you can only hide BAT logo if rewards are off? I think that we said that we want it like this.

**Comment by NejcZdovc** [comment]
talked with product and this one is not valid
