### ISSUE TITLE
Metamask icons in connect hardware screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6038]
## Description 

Metamask icons in connect hardware screen

## Steps to Reproduce

   1. Create account on Crypto Wallet
   2. Go to profile and connect hardware
   3. Connect hardware screen uses Metamask icons in welcome screen

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/64988093-ac5e4a80-d898-11e9-80e2-5058ca7079ba.png)

## Expected result:
Should use Brave branding 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.70.93 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

cc: @jamesmudgett

**Comment by ryanml** [comment]
cc: @jamesmudgett for replacement iconography

**Comment by bbondy** [comment]
ping @jamesmudgett

**Comment by jamesmudgett** [comment]
[Archive.zip](https://github.com/brave/brave-browser/files/3727310/Archive.zip)

**Comment by jamesmudgett** [comment]
Replacements attached
![Artboard](https://user-images.githubusercontent.com/318119/66799616-77fd9e80-eed7-11e9-8e25-b1f55f21a3fe.png)


[Archive.zip](https://github.com/brave/brave-browser/files/3727324/Archive.zip)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | Linux

* Verification passed on component `0.1.17`
![image](https://user-images.githubusercontent.com/17010094/67046501-54686d00-f0fe-11e9-9c54-45eecfa9a38a.png)


Verification passed on 

Brave | 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | Windows 10 OS Version 1903 (Build 18362.388)

* Verification passed on component `0.1.17`
![image](https://user-images.githubusercontent.com/17010094/67046545-706c0e80-f0fe-11e9-8b3b-255d37888a49.png)
