### ISSUE TITLE
Get help link on connect hardware points to Metamask support page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6039]
## Description 

Get help link on connect hardware points to Metamask support page

## Steps to Reproduce

   1. Create account for crypto wallet
   2. Go to profile and connect hardware
   3. Scroll down and click on get help, opens Metamask support page

## Actual result:

Get help link on connect hardware points to Metamask support page

## Expected result:
Should go to dedicated Brave support page

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.70.93 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

cc; @Brave-Matt  to have a place holder support page created for this

**Comment by ryanml** [comment]
blocked awaiting support page

**Comment by rebron** [comment]
@Brave-Matt to put on your radar?

**Comment by bbondy** [comment]
Closing this as it's fixed with https://github.com/brave/ethereum-remote-client/pull/93

**Comment by srirambv** [comment]
Verification passed on 


Brave | 1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Linux
Component | `0.1.32`

* Verified `Get Help` links to https://support.brave.com/hc/en-us/articles/360034535452-How-can-I-add-my-other-Crypto-Wallets-to-Brave-

------
