### ISSUE TITLE
Make tor feature disable at runtime

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#6044]
To control tor by admin policy(https://github.com/brave/brave-browser/issues/454), it should be disabled at startup.

**Comment by notoriousturtle** [comment]
Any updates?

**Comment by simonhong** [comment]
@notoriousturtle Not yet started. Our tor framework refactoring is in-progress now.
After finishing it, I think we can start on this issue.

**Comment by bsclifton** [comment]
@simonhong marked as `QA/No` since test plan should be covered in https://github.com/brave/brave-browser/issues/454

Please update this issue if I missed something and we would like specific tests done (and then change label to `QA/Yes`) 😄
