### ISSUE TITLE
Ask for user permission before switching to full-screen mode

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#605]

**Comment by jumde** [comment]
This is available on `browser-laptop`.

<img width="1428" alt="screen shot 2018-08-16 at 1 48 02 pm" src="https://user-images.githubusercontent.com/1903815/44234291-1cad1080-a15b-11e8-9e56-acbb96b8fea3.png">

**Comment by bbondy** [comment]
Is this actually needed since there's UI that informs the user of them being in full screen in Chromium?

**Comment by jumde** [comment]
Even on `browser-laptop` the UI informs the user that the user is in full screen. 
<img width="1440" alt="screen shot 2018-08-16 at 2 27 21 pm" src="https://user-images.githubusercontent.com/1903815/44236193-fa1df600-a160-11e8-8287-bd9e25101ff1.png">

AFAIK, the motivation behind this permission request is to avoid phishing attacks like the one feross highlighted here.

https://feross.org/html5-fullscreen-api-attack/

**Comment by bbondy** [comment]
Is it still a phishing attack even with the message though? I just know a lot of people find it annoying to have the prompt.

**Comment by diracdeltas** [comment]
i prefer having the prompt but most people probably are just annoyed by it. fine with matching chrome.
