### ISSUE TITLE
Chrome Issue 1003358: Basic Auth Credentials Box Flashes, Disappears, and Results in 401 (Apache 2.2 server)

### ISSUE THREAD

**Issue by ViktorNacht** [brave/brave-browser#6054]
Looks like you guys implemented this known bug:

https://bugs.chromium.org/p/chromium/issues/detail?id=1003358&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by kjozwiak** [comment]
Thanks for the issue @ViktorNacht 👍This will get fixed once we update all our channels to `77.0.3865.90` which we're currently doing. Verified that the issue doesn't happen anymore with the latest Chrome running `77.0.3865.90`.

STR (copied from the above CR bug @ViktorNacht posted):

1. visit a url with basic auth like https://www.nyu.edu/emd-bin/access/submit.cgi (this uses ldap as a provider)
2. authentication box flashes and disappears

Example:

![authFlashing](https://user-images.githubusercontent.com/2602313/65190975-8b385e00-da40-11e9-944e-6bfa17d9664b.gif)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


- The original issue is reproduced in `0.68.138 Chrome version: 77.0.3865.75`
- Verified the STR from https://github.com/brave/brave-browser/issues/6054#issuecomment-532888445 - Now the authentication popup stay until user enter credentials
![image](https://user-images.githubusercontent.com/38657976/65232689-330c6500-daef-11e9-9724-0bbc36f2d39c.png)
