### ISSUE TITLE
Korean language menu translation error

### ISSUE THREAD

**Issue by jiyongwoo** [brave/brave-browser#6057]
## Description 
In Shields panel,
All cookies allowed --Korean--> 모든 쿠키 차단됨(x)
                                --Korean--> 모든 쿠키 허용됨(o)

## Actual result:
"모든 쿠키 차단됨" menu
![image](https://user-images.githubusercontent.com/41583431/65147142-78ca1e80-da58-11e9-8df2-ccbe8f2d7f07.png)

## Expected result:
"모든 쿠키 허용됨" menu

## Brave version (brave://version info)
Brave | 0.68.138 Chromium: 77.0.3865.75 (공식 빌드) (64비트)
OS | Windows 10 OS Version 1903 (Build 18362.356)

**Comment by rebron** [comment]
cc: @simonhong For a quick glance on translation correctness. @atsyed87 will take care of the rest.

**Comment by rebron** [comment]
@atsyed87 It looks like the translations are reversed.

**Comment by atsyed87** [comment]
Taking a look now

**Comment by simonhong** [comment]
@rebron @atsyed87 Oops, sorry forgot to reply.
Yes, they are reversed.

`All cookies allowed`  should be  `모든 쿠키 허용됨`

**Comment by atsyed87** [comment]
@simonhong I can't locate these strings inside Transifex. By any chance would you have a link to the corresponding Transifex issues?

**Comment by simonhong** [comment]
@atsyed87 I'm also finding where `brave_extension/_locales/ko/messages.json` came from Transifex. but can't find now. Maybe other person knows about this? cc @bbondy

**Comment by atsyed87** [comment]
cc @cezaraugusto if he knows where these might be lurking :)

**Comment by mkarolin** [comment]
https://www.transifex.com/brave/brave/translate/#ko/brave_extension/167257144?q=text%3A'cookies+allowed'

**Comment by simonhong** [comment]
@mkarolin Thanks! I modified its translation. Do we just need to wait next release for applying it into brave-core?

**Comment by mkarolin** [comment]
Could do an `npm run pull_l10n` to get the latest localization and uplift. cc: @bsclifton

**Comment by bsclifton** [comment]
@mkarolin let's do it! I believe you've already requested one with 0.78 😄

**Comment by bsclifton** [comment]
Fixed in 0.69.x with https://github.com/brave/brave-core/pull/3660

@mkarolin this will be fixed in master/0.71/0.70 when translations are pulled for Chromium 78, right?

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.134 Chromium: 77.0.3865.120 (Official Build) (64-bit)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | Windows 10 OS Version 1803 (Build 17134.1006)


- Verified the test plan mentioned in the description
![image](https://user-images.githubusercontent.com/38657976/66632344-dac80f00-ec25-11e9-8f86-1b007bdc2bd4.png)
