### ISSUE TITLE
embedded loom video disappears

### ISSUE THREAD

**Issue by chkk525** [brave/brave-browser#6058]
## Description 

Embedded loom video(https://www.loom.com/) doesn't show up.

## Steps to Reproduce

   1. Open https://docs.autify.com/ja/getting-started

## Actual result:

< Brave ---- Chrome>
![image](https://user-images.githubusercontent.com/3054915/65147904-04907a80-da5a-11e9-908b-76c264fcb799.png)

## Expected result:
- Embedded video should show up like in Chrome

## Reproduces how often: 

- Easily reproduce

## Brave version (brave://version info)

Brave | 0.68.132 Chromium: 76.0.3809.132 (Official Build) （64 ビット）
-- | --
変更履歴 | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X
JavaScript | V8 7.6.303.29
Flash | （無効）
ユーザー エージェント | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
コマンドライン | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extensions-install-verification=enforce_strict --enable-features=NewExtensionUpdaterService,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,TranslateUI,NetworkService,UnifiedConsent --flag-switches-begin --flag-switches-end
実行ファイルのパス | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
プロフィール パス | /Users/chikaki/Library/Application Support/BraveSoftware/Brave-Browser/Profile 1
バリエーション | d74ef32b-ca7d8d80

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Yes
- Can you reproduce this issue with the dev channel?
Yes
- Can you reproduce this issue with the nightly channel?
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
Yes
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by ryanbr** [comment]
@rebron @chkk525 should be fixed when this lands in the next 24-48hrs.

**Comment by ryanbr** [comment]
My Err, This was a cookie issue. Allowing `All Cookies` should fix this. Initial fix is still valid on other sites however.

**Comment by ryanbr** [comment]
@chkk525 does this site work correctly? I am getting video playback with site-cookies=enabled/Shields=On

**Comment by ryanbr** [comment]
Closing this, working for me. with default shields enabled
