### ISSUE TITLE
Rewards Panel cached information needs to expire/refresh

### ISSUE THREAD

**Issue by masparrow** [brave/brave-browser#6059]
## Description 
As noted in #5720 - if a user has previously attempted to contribute/contributed to a Vimeo publisher - they will have cached the site favicon, instead of the publishers portrait/favicon. This favicon is shown in several places.

We should expire the cache after 30 days generally so we can re-pull other site information as well.  This will also fix some previous cases where some incorrect channel information was cached.  For safety, we should expire the cache on the next upgrade as well.

## Steps to Reproduce

See #5720 for the initial steps - and reproduce using a release build prior to the fix from https://github.com/brave/brave-core/pull/3464
Using the build containing the fix from https://github.com/brave/brave-core/pull/3464, revisit the same publisher and attempt to contribute.

## Actual result:
The site favicon is shown.

## Expected result:
The publisher portrait favicon should be shown. 

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
This issue will only be evident once https://github.com/brave/brave-core/pull/3464 is released in a build.

## Version/Channel Information:
This issue will only be evident once https://github.com/brave/brave-core/pull/3464 is released in a build.

## Other Additional Information:
- using the build containing  https://github.com/brave/brave-core/pull/3464, on visiting a new, verified publisher, you should see (and therefore cache) the publisher portrait favicon
 
## Miscellaneous Information:
Should Vimeo ever change the portrait ID information we scrape, the issue reported in #5720 would reoccur, and any fix would result in the same 'stale cache' issue noted in this ticket. 
As such, we need to ensure these favicons can be updated as and when future changes occur.

**Comment by Miyayes** [comment]
Refiled here for freshness: https://github.com/brave/brave-browser/issues/20980
