### ISSUE TITLE
Global Shields Settings restyle

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#606]
Shield settings are available per site as of now.

**Comment by jumde** [comment]
This is available in `browser-laptop`

**Comment by rebron** [comment]
<img width="716" alt="global-shield-settings" src="https://user-images.githubusercontent.com/5951041/45198073-7adc8900-b219-11e8-8be9-5b0042e4a75f.png">

See #955 for placement

**Comment by rebron** [comment]
<img width="927" alt="site-permissions" src="https://user-images.githubusercontent.com/5951041/45198379-22a68680-b21b-11e8-8a43-178d04d8db4d.png">
For Site permissions, moving parts of content settings into this section.

**Comment by rebron** [comment]
<img width="798" alt="allow-block-list" src="https://user-images.githubusercontent.com/5951041/45198547-e7588780-b21b-11e8-8909-9d9d84d910c3.png">
Allow and Block list.

**Comment by bbondy** [comment]
Moved to 1.0 because we have the functionality for global shields available here with existing looking settings UI: https://github.com/brave/brave-browser/issues/1288 

I think we could probably move this even past 1.0 if needed because of timing.

**Comment by rebron** [comment]
Closing in favor of newer design.
