### ISSUE TITLE
piece-length not found when building WebTorrent extension on windows-x64(0.69.x)

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#6066]
14:54:05  Built at: 09/18/2019 6:54:04 PM
14:54:05   2 assets
14:54:05  Entrypoint brave_webtorrent = brave_webtorrent.bundle.js
14:54:05  Entrypoint brave_webtorrent_background = brave_webtorrent_background.bundle.js
14:54:05    [4] (webpack)/buildin/global.js 472 bytes {0} {1} [built]
14:54:05   [23] (webpack)/buildin/module.js 497 bytes {0} {1} [built]
14:54:05   [30] ./components/brave_webtorrent/extension/background/store.ts + 4 modules 13.3 KiB {1} [built]
14:54:05        |    5 modules
14:54:05   [66] ./components/brave_webtorrent/extension/background/actions/tabActions.ts + 1 modules 1.23 KiB {1} [built]
14:54:05        |    2 modules
14:54:05   [89] (webpack)/buildin/harmony-module.js 573 bytes {0} {1} [built]
14:54:05  [388] load-ip-set (ignored) 15 bytes {1} [built]
14:54:05  [439] os (ignored) 15 bytes {1} [built]
14:54:05  [504] ./components/brave_webtorrent/extension/brave_webtorrent.tsx + 49 modules 113 KiB {0} [built]
14:54:05        |    50 modules
14:54:05  [505] ./components/brave_webtorrent/extension/background.ts + 4 modules 2.7 KiB {1} [built]
14:54:05        |    5 modules
14:54:05      + 673 hidden modules
14:54:05  
14:54:05  ERROR in ./node_modules/create-torrent/index.js
14:54:05  Module not found: Error: Can't resolve 'piece-length' in 'C:\jenkins\x64-release\src\brave\node_modules\create-torrent'
14:54:05   @ ./node_modules/create-torrent/index.js 3:24-47
14:54:05   @ ./node_modules/webtorrent/index.js
14:54:05   @ ./components/brave_webtorrent/extension/background/webtorrent.ts
14:54:05   @ ./components/brave_webtorrent/extension/background/events/torrentEvents.ts
14:54:05   @ ./components/brave_webtorrent/extension/background.ts
14:54:05  npm ERR! code ELIFECYCLE
14:54:05  npm ERR! errno 2
14:54:05  npm ERR! brave-core@0.69.127 web-ui: `webpack --config components/webpack/webpack.config.js --progress --colors "--mode=production" "--output-public-path=/extension/out/" "brave_webtorrent=C:/jenkins/x64-release/src/brave/components/brave_webtorrent/extension/brave_webtorrent.tsx" "brave_webtorrent_background=C:/jenkins/x64-release/src/brave/components/brave_webtorrent/extension/background.ts"`
14:54:05  npm ERR! Exit status 2
14:54:05  npm ERR! 
14:54:05  npm ERR! Failed at the brave-core@0.69.127 web-ui script.
14:54:05  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
14:54:05  
14:54:05  npm ERR! A complete log of this run can be found in:
14:54:05  npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-09-18T18_54_05_162Z-debug.log
14:54:05  
14:54:05  Traceback (most recent call last):
14:54:05    File "../../brave/script/transpile-web-ui.py", line 115, in <module>
14:54:05      sys.exit(main())
14:54:05    File "../../brave/script/transpile-web-ui.py", line 34, in main
14:54:05      args.public_asset_path)
14:54:05    File "../../brave/script/transpile-web-ui.py", line 95, in transpile_web_uis
14:54:05      execute_stdout(args, env)
14:54:05    File "C:\jenkins\x64-release\src\brave\script\lib\util.py", line 187, in execute_stdout
14:54:05      execute(argv, env)
14:54:05    File "C:\jenkins\x64-release\src\brave\script\lib\util.py", line 175, in execute
14:54:05      raise e
14:54:05  subprocess.CalledProcessError: Command '['npm.cmd', 'run', 'web-ui', '--', '--mode=production', '--output-public-path=/extension/out/', 'brave_webtorrent=C:/jenkins/x64-release/src/brave/components/brave_webtorrent/extension/brave_webtorrent.tsx', 'brave_webtorrent_background=C:/jenkins/x64-release/src/brave/components/brave_webtorrent/extension/background.ts']' returned non-zero exit status 2

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/brave-core/pull/3475
