### ISSUE TITLE
Disable DNS Prefetching

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#607]
DNS prefetching has privacy concerns as highlighted here: https://www.usenix.org/legacy/event/leet10/tech/full_papers/Krishnan.pdf

**Comment by simonhong** [comment]
This is also resolved by https://github.com/brave/brave-core/pull/340

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

* Verified prediction service is removed from privacy settings
