### ISSUE TITLE
Grants displayed as "Earnings from ads"

### ISSUE THREAD

**Issue by treebeard** [brave/brave-browser#6070]
## Description 
BAT from grants are displayed in the UI as "Earned from ads" and "Earnings from ads" whereas the actual earnings from ads is (total BAT balance - "earned from ads")

## Steps to Reproduce
   1. Receive BAT from both ad earnings and grants

## Actual result:
![wallet](https://user-images.githubusercontent.com/11672497/65190670-54624800-da40-11e9-86b6-25268776d00f.png)
![uphold](https://user-images.githubusercontent.com/11672497/65190669-54624800-da40-11e9-871d-91dcf0af2c17.png)

## Expected result:
The grants tab should display the text "earned from grants", and the earnings pane should show actual ad earnings as viewed in Uphold, not grant earnings. 

## Reproduces how often: 
No steps to reproduce, constant.

## Brave version (brave://version info)
Version 0.70.97 Chromium: 77.0.3865.65 (Official Build) beta (64-bit)

## Version/Channel Information:
This happens in the current release. I have not had the chance to test this in the other channels (as it would take a matter of a month or two).

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No.

## Miscellaneous
Link to a [Reddit thread](https://www.reddit.com/r/BATProject/comments/bb49pg/first_month_using_brave_with_ads_1917_better_than/ekgvca4/) where other users have had this issue in the past.

**Comment by treebeard** [comment]
#5345 is a similar issue. If the capability of displaying the wallets separately is not there, could the wording be fixed to show "earnings from grants" instead?

**Comment by NejcZdovc** [comment]
not sure that I understand the whole situation. Did you get your ad grant via captcha flow? If so then it's correct. We are currently not depositing ad grants directly in Uphold card.

**Comment by ayongs1997** [comment]
https://github.com/brave/brave-browser/projects/5#card-26641946

**Comment by NejcZdovc** [comment]
closing as stale
