### ISSUE TITLE
Camera and microphone don't work

### ISSUE THREAD

**Issue by SilencerWeb** [brave/brave-browser#6079]
## Description 
Tried to use websites for calling/video calling, neither the camera or microphone doesn't work

## Brave version (brave://version info)
`0.68.138 Chromium: 77.0.3865.75 (Official Build) (64-bit)`
But it works like that for a long time

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? What is it?
- Is the issue reproducible on the latest version of Chrome? No, it works OK in Chrome

**Comment by rebron** [comment]
@SilencerWeb Can you tell us what websites you're using where this isn't working?

**Comment by SilencerWeb** [comment]
@rebron,
https://duo.google.com/
https://hangouts.google.com
https://omegle.com

**Comment by rebron** [comment]
likely related to: https://github.com/brave/brave-browser/issues/6083

**Comment by ANKerD** [comment]
I had a similar issue by trying to send an image at facebook.

**Comment by bsclifton** [comment]
Camera and mic should work in regular cases; there is a known issue where Speech to Text is not working: https://github.com/brave/brave-browser/issues/3725

**Comment by Ken-g6** [comment]
Having a similar issue with Webex.  https://[organization].webex.com:443 is whitelisted for the microphone, but the Webex site still says, "No microphone or camera is detected".

**Comment by sujanchegu** [comment]
Having the exact same issue on meet.google.com just today

```
Brave version: 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)
OS: Fedora Workstation 33 Gnome
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
```

**Comment by ryanbr** [comment]
Tested https://www.omegle.com/   Allowed Video and Camera (when the popup came up). Had a brief conversation with a random user without issue. 
Using a Condenser Mic + Logitech c920 in Windows, Is everything okay now @SilencerWeb

**Comment by pes10k** [comment]
Closing since it looks like this has been addressed.  Thanks everyone!
