### ISSUE TITLE
canvas.toDataURL() returns an empty string

### ISSUE THREAD

**Issue by nothingismagick** [brave/brave-browser#6081]
## Description 

`canvas.toDataURL()` returns an empty string

## Steps to Reproduce

   1.  load an img into a canvas
   2. render the canvas to data url with jpg or png

## Actual result:
returned value is empty

## Expected result:
a base64 encoded string

## Reproduces how often: 
No problem in chrome / firefox

## Brave version (brave://version info)

Brave | 0.68.138 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | `201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}`
macOS  | Version 10.12.6 (Build 16G2128)

**Comment by rebron** [comment]
In shields do you have the 3rd party device recognition setting turned on? Can you toggle that off and see if that's working?

**Comment by oleg-andreyev** [comment]
Had the same issue and after disabling "shield" everything started to be okay.

**Comment by bsclifton** [comment]
Closing as there hasn't been an update. By default, Brave is only blocking 3rd party device recognition. Device recognition can be turned off on a per-site basis, which should fix any problems found (click the lion, pick `All device recognition attempts allowed`, which will only apply to that site).
<img width="419" alt="Screen Shot 2019-10-28 at 9 56 35 AM" src="https://user-images.githubusercontent.com/4733304/67699360-3f46d600-f969-11e9-9931-accdbef76f73.png">
