### ISSUE TITLE
Hide People / Profile Icon

### ISSUE THREAD

**Issue by TCB13** [brave/brave-browser#6082]
Hello,

Chrome and other derivates have a setting called "Show profile switching button" that will hide the People / Profile Icon at the right side of the URL bar.

I can't find this option in Brave, is there any flag related to this or a way around it?

Thank you.

**Comment by rebron** [comment]
Hi @TCB13 We're hiding the profile icon by default if users don't want to use profiles. https://github.com/brave/brave-browser/issues/5091

You can test this out in our beta channel or dev and nightly channel version now.

We'll only show the profile icon if users use the profile feature. If users do use multiple profiles we don't currently have plans to have a setting to show/hide the profile button. It's hard to use multiple profiles without that icon.

**Comment by TCB13** [comment]
Thank you for the quick feedback!
