### ISSUE TITLE
Unnecessary space in `Remove` button for widget menus in NTP

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#6085]
## Description 

Unnecessary space in `Remove` button for widget menus  in NTP

## Steps to Reproduce

   1. Open brave 0.70.97
   2. Open a few websites so that top tiles shown in NTP
   3. Open an NTP 
   4. Click on Widget icon for `Remove`
   5. Unnecessary space in `Remove` button for widget menus

## Actual result:

Unnecessary space in `Remove` button for widget menus  in NTP
![image](https://user-images.githubusercontent.com/38657976/65269875-a8038d00-db37-11e9-8bcf-1454c39a9b98.png)

![image](https://user-images.githubusercontent.com/38657976/65269897-b356b880-db37-11e9-9b4c-af540da12df4.png)

![image](https://user-images.githubusercontent.com/38657976/65269912-bc478a00-db37-11e9-82e3-6dbace2c80bd.png)

## Expected result:

Trim the `Remove` button

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.70.97 Chromium: 77.0.3865.65 (Official Build) beta (64-bit)
-- | --
Revision | 87a331a3169cab563505fb44011058b904011ba1-refs/branch-heads/3865@{#726}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @karenkliu

**Comment by karenkliu** [comment]
Hi Geeta - this is to design spec. There will eventually be more options in this menu, and that is the expected top/bottom padding, not extra space..
