### ISSUE TITLE
Ads history shows date of 12/31/1969

### ISSUE THREAD

**Issue by mbacchi** [brave/brave-browser#6088]
## Description 
Brave ads history page shows the date of 12/31/1969 for ads in the past 7 days:

![image](https://user-images.githubusercontent.com/6763301/65274112-a2368900-daf0-11e9-80ce-761f78217426.png)

## Steps to Reproduce

   1. Enable ads
   2. Go to 7 day ad history

## Actual result:
Screenshot above

## Expected result:
Date of each ad shown is unique, and more recent than the start of the epoch counter.

## Reproduces how often: 
Always

## Brave version (brave://version info)
Development version Version 0.71.74 Chromium: 77.0.3865.75 (Official Build) dev (64-bit)
OS: Linux

## Version/Channel Information:
Unsure, only use ads on dev channel at the moment.

- Can you reproduce this issue with the current release? Ads not currently enabled, will enable them to test now.
- Can you reproduce this issue with the beta channel? Ads not currently enabled, will enable them to test now.
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Ads not currently enabled, will enable them to test now.

**Comment by btlechowski** [comment]
Reproduced on 

Brave | 0.70.116 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

Date is 1970/1/1 though.


![image](https://user-images.githubusercontent.com/34715963/66875344-3ee42d80-efae-11e9-94bc-c4e1f9c1226c.png)

cc @brave/legacy_qa

**Comment by LaurenWags** [comment]
cc @alexwykoff

**Comment by btlechowski** [comment]
Reproduced on 

Brave | 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | Linux

![image](https://user-images.githubusercontent.com/34715963/66876559-7fde4100-efb2-11e9-88b2-d112863d4332.png)

Could be Linux only issue. cc @GeetaSarvadnya @LaurenWags to check on other platforms.

**Comment by GeetaSarvadnya** [comment]
1+ from https://community.brave.com/t/brave-rewards-has-incorrect-ads-history-date/95133/2

**Comment by atharvan** [comment]
Reproduced on 
Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Linux

Date 01/01/1970

**Comment by tmancey** [comment]
Closing issue as should be resolved by https://github.com/brave/brave-browser/issues/6757

@LaurenWags can you please test as part of https://github.com/brave/brave-browser/issues/6757

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.4.84 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Ubuntu 18.04 LTS

Verified steps from the description

![image](https://user-images.githubusercontent.com/34715963/74381240-6081e400-4deb-11ea-9d8a-3ba9781e34c6.png)
