### ISSUE TITLE
Linux package changelog refers to Chrome

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#6093]
Here's the latest entry in the `brave-browser` Debian package:

```
brave-browser (0.68.139) stable; urgency=low

  * Build spec: https://chromium.googlesource.com/chromium/src.git/+/0.68.139/
  * Release Notes:
    http://googlechromereleases.blogspot.com/search/label/Stable%20updat
    es

 -- Brave Software <support+laptop@brave.com>  Tue, 03 Feb 2009 14:54:35 -0800
```

Expected:
- build spec refers to https://github.com/brave/brave-browser/releases/tag/v0.68.139
- release notes point to https://brave.com/latest/
- email address should be `support@brave.com` like on the Play Store
- (ideally) the date should not be a hard-coded one from the past

**Comment by fmarier** [comment]
> * (ideally) the date should not be a hard-coded one from the past

The date is [hardcoded in Chromium](https://cs.chromium.org/chromium/src/chrome/installer/linux/debian/changelog.template?l=5&rcl=0dd98c7f7c3c2b715efce9a552ae9954f58447d0) and not configurable or auto-generated. It's probably not worth patching.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.1.11 Chromium: 78.0.3904.108 (Official Build) beta (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3506

![image](https://user-images.githubusercontent.com/34715963/69689805-35300880-10ca-11ea-8125-25b764c04daf.png)
