### ISSUE TITLE
profile icons going blank/white when hovering over them

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6095]
## Description 

When hovering over profile icons, the icon will blank/turn white making it hard to see what's being picked.

## Steps to Reproduce

   1. launch brave and visit `brave://settings/manageProfile`
   2. hover over the icons and you'll notice they'll go blank

## Actual result:

![flashingWhiteSelection](https://user-images.githubusercontent.com/2602313/65295746-54417580-db30-11e9-8567-c39f12e42a94.gif)

## Expected result:

Profile icon shouldn't blank/turn white when hovering over them.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | macOS Version 10.14.6 (Build 18G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `No` doesn't reproduce

## Miscellaneous Information:

CCing @rebron @brave/legacy_qa @petemill

**Comment by btlechowski** [comment]
Reproduced on Ubuntu

Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/65554130-f72b3280-df28-11e9-9c8f-4a3357463df3.png)

**Comment by bsclifton** [comment]
@petemill is this one you can check out?

**Comment by kjozwiak** [comment]
@petemill duplicate of https://github.com/brave/brave-browser/issues/5977?

**Comment by bsclifton** [comment]
@kjozwiak not a duplicate - but this will go away with 0.70.x, as that has been reworked. Maybe we can close this as `wontfix`?

**Comment by kjozwiak** [comment]
@bsclifton sure 👍 Was wondering if it was a dupe due to the following via the original report:

```
Rounded squares and image disappears on hover
```
