### ISSUE TITLE
Add the ability to set a different default search engine for private tabs

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#61]
See how it works in browser-laptop for working spec.

Muon spec:
In private tab, user can turn on/off duckduckgo. If user turns it off, search engine of normal mode is used.
In tor enabled private tab, only duckduck can be used. User can't change it.
- [x] Implement C++ modules and prefs for toggle different search engine
- [x] Connect prefs with webui

**Comment by simonhong** [comment]
Search engine list is managed by `TemplateURLService`.
`TemplateURLServiceFactory` creates this service by using original profile.
That means incognito mode uses same service with normal mode.

To use different default search engine in incognito mode, incognito profile should be used by factory.

**Comment by srirambv** [comment]
Is this only the DDG search in incognito tab or will have a seperate section in `chrome://settings/search` to set it similar to b-l?

**Comment by GeetaSarvadnya** [comment]
1. When user turn on DDG in private tab, search engine is using DDG
2. When user turn on DDG in private tab, click on Refresh button is making DDG off @srirambv already logged an issue #1235. 
3. In Tor enabled private tab, search engine is NOT DDG, its still using google.
#1226.

**Comment by srirambv** [comment]
@GeetaSarvadnya  step 4 is not an issue. Its just delay in downloading the Tor binaries which makes it not list it on the welcome tab. If you wait till the Tor binaries are downloaded it will show option on the welcome screen itself.

**Comment by srirambv** [comment]
Thanks for the update @simonhong . #1186 is logged for separate search settings.

**Comment by srirambv** [comment]
QA Blocked on #1186

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

* Based on https://github.com/brave/brave-browser/issues/61#issuecomment-425229567, verified DDG is set as default search engine when the DDG switch is toggled
