### ISSUE TITLE
Metamask should be removed from successful message on completing the challenge

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6100]
## Description 

Metamask should be removed from the successful message on completing the challenge

## Steps to Reproduce

   1. Create a new browser profile 
   2. Open brave://wallet and click on Ledger/Trezor
   3. Create an account 
   4. Copy the secret code
   5. Finish selecting the code words to complete the challenge
   6. Upon completion, congratulations message is shown that says `Metamask`
   7. `Learn more` at the end of the message links to [Metamask page](https://metamask.zendesk.com/hc/en-us/articles/360015489591-Basic-Safety-Tips)

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/65331622-20e00480-db8b-11e9-9e12-df08b859fe13.png)

## Expected result:
No Metamask branding on wallet pages

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.71.75 Chromium: 77.0.3865.75 (Official Build) dev (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

cc: @Brave-Matt @atsyed87  to create Brave page similar to https://metamask.zendesk.com/hc/en-us/articles/360015489591-Basic-Safety-Tips that needs to be linked in the message after rebranding
cc: @bbondy @tomlowenthal

**Comment by ryanml** [comment]
This is fixed client side as of: https://github.com/brave/ethereum-remote-client/commit/b2d03a4a4689a8d2fc81839c87bfce85a512b0fe

This will be reflected in the browser when we do next version bump cc: @srirambv

**Comment by ryanml** [comment]
This is fixed in latest release

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

Used `Crypto Wallets - Version: 1.0.9` and verified the following:

<img width="1005" alt="Screen Shot 2019-10-07 at 1 24 23 AM" src="https://user-images.githubusercontent.com/2602313/66286900-6b5ac400-e8a1-11e9-9c87-96200fdbd4a6.png">
