### ISSUE TITLE
About wallet page has links to MM 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6101]
## Description 

About wallet, page has links to MM 

## Steps to Reproduce

   1. Enable crypto wallet
   2. Open profile and go to info
   3. All link to MM pages

## Actual result:

Privacy Policy -> https://metamask.io/privacy.html
Attributions -> https://metamask.io/attributions.html
Visit our Support Center -> https://support.metamask.io/
Visit our web site -> https://metamask.io/
Email us! -> mailto:help@metamask.io?subject=Feedback

## Expected result:
Have Brave specific links 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.71.75 Chromium: 77.0.3865.75 (Official Build) dev (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

cc: @Brave-Matt @atsyed87  for help center pages
cc: @tomlowenthal @bbondy

**Comment by ryanml** [comment]
This is awaiting deployment via: https://github.com/brave/ethereum-remote-client/pull/57 && https://github.com/brave/ethereum-remote-client/pull/56

The About settings tab is removed, as well as the `Info & Help` link which goes out to it. We can update with the proper links once we have full coverage cc: @srirambv

**Comment by bbondy** [comment]
Should be fixed in the latest ethereum-remote-client extension update. Please try again @srirambv

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

* Verified no About wallet section shown in Settings

Verification passed on 

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1903 (Build 18362.30)

* Verified no About wallet section shown in Settings
