### ISSUE TITLE
Order a Trezor link contains Metamask affiliate link

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6102]
## Description 

Order a Trezor link contains Metamask affiliate link

## Steps to Reproduce

   1. Enable crypto wallet
   2. Go to profile and connect hardware
   3. `Oder a Trezor` hyperlink uses MM affiliate link `https://shop.trezor.io/?a=metamask`

## Actual result:

![Screenshot from 2019-09-20 09-58-55](https://user-images.githubusercontent.com/17010094/65332785-5554c000-db8d-11e9-8e84-67c1e315f902.png)

## Expected result:
No MM links 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.71.75 Chromium: 77.0.3865.75 (Official Build) dev (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @bbondy @tomlowenthal @ryanml

**Comment by bbondy** [comment]
This should be fixed with the latest ethereum-remote-client extension update. Could you test again @srirambv ?
