### ISSUE TITLE
Import wallet learn more links to MM help page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6103]
## Description 

Import wallet learn more links to MM help page

## Steps to Reproduce

   1. Enable crypto wallet
   2. Go to profile and connect hardware
   3. Select `Import`, Learn more links to [MM help page](https://metamask.zendesk.com/hc/en-us/articles/360015289932)

## Actual result:

Import wallet learn more links to MM help page

## Expected result:
Should link to Brave support page on helpcenter

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.71.75 Chromium: 77.0.3865.75 (Official Build) dev (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

## Miscellaneous Information:

cc: @Brave-Matt @atsyed87  to create Brave specific page
@bbondy @tomlowenthal

**Comment by bbondy** [comment]
This one is not fixed yet so moving it to the next milestone. FYI @ryanml

**Comment by ryanml** [comment]
<img width="428" alt="Screen Shot 2020-01-26 at 5 29 19 PM" src="https://user-images.githubusercontent.com/8732757/73144282-6c3a8000-4061-11ea-94ee-38b50cc65ca0.png">

`here` now links to a Brave article as of: https://github.com/brave/ethereum-remote-client/pull/101

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.3.105 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Linux
Component | `0.1.37`

- Verified Import wallet learn more links to Brave [Support Article](https://support.brave.com/hc/en-us/articles/360035488071-How-do-I-manage-my-Crypto-Wallets-)
