### ISSUE TITLE
DevTools "Chrome" branding

### ISSUE THREAD

**Issue by willstocks** [brave/brave-browser#6106]
## Description 

Remove Chrome branding in DevTools

## Steps to Reproduce

   1. Upgrade Brave 67 -> 68 (or whenever we went from Chromium 76 -> 77)
   2. Open DevTools
   3. See that it says "Highlights from the Chrome 77 update" in the "What's New" tab

## Actual result:

![image](https://user-images.githubusercontent.com/43744514/65337233-b09fa600-dbbf-11e9-8211-14aa7c070cfc.png)

## Expected result:
I know this only applies to a few people browsing this particular area, but it'd be nice to see the "Chrome" removed from here. 
I'd also suggest maybe removing the "Audits" tab, because Lighthouse (only mentioned because I saw it in the "What's New" can't run in anything other than Chrome it seems (#3199)!

## Reproduces how often: 

Every time there's a Chromium upgrade!

## Brave version (brave://version info)

Version 0.68.138 Chromium: 77.0.3865.75

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yep
- Can you reproduce this issue with the beta channel? Yep
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Nope
- Does the issue resolve itself when disabling Brave Rewards? Nope
- Is the issue reproducible on the latest version of Chrome? It's a Chrome thing, so yep

**Comment by bsclifton** [comment]
@rebron is this something we want to do?

**Comment by rebron** [comment]
Close. wontfix. We're not creating a specific What's New page for devtools.

**Comment by xanzhu** [comment]
No need to create a specific page, simply remove the "What's new" tab and display the console instead.
