### ISSUE TITLE
Needs sync status functionality

### ISSUE THREAD

**Issue by noslenac** [brave/brave-browser#6109]
## Description 

Started having issues with Brave crashing due to sync which appears to be common in the latest issues. This seems to affect most recent release for both Linux and Windows. I don't use Mac and can't verify the issue there.

I thought it may have been as a result of making significant changes to bookmarks on one of the four computers in my sync chain. I removed every device, backed up and deleted all bookmarks, and created a new sync chain only to discover that nothing will sync. There should be a way to view sync status to view successful and/or failed sync jobs. 

## Steps to Reproduce

   1. Make changes to bookmarks
   2. Open Brave on another device
   3. Syncing appeared to stop working
   4. Removed all devices from sync chain
   5. Backed up and deleted all bookmarks from every device
   6. Recreated new sync chain and added all devices
   7. Imported backup bookmarks and waited an hour with still no sync

## Actual result:

Nothing

## Expected result:
Bookmarks should start showing up and sync status should always be user accessible.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.68.139 Chromium: 77.0.3865.90 (Official Build) (64-bit)
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1803 (Build 17134.1006)
OS | Ubuntu Linux 18.04LTS

## Version/Channel Information:

Current release. Have not tried other releases as this is most important for production builds.

**Comment by bsclifton** [comment]
With our new sync functionality (1.12 and newer), there's a detailed UI where you can see the sync status and do debugging / watch events happen live. It's available at brave://sync-internals
