### ISSUE TITLE
Create test readthedocs.org account for documentation

### ISSUE THREAD

**Issue by mbacchi** [brave/brave-browser#611]
Documentation is on the GitHub Wiki currently, there are some downsides to this. We want the ability to use PRs for reviews and to track history and the wiki doesn't provide this.

readthedocs.org is a common tool for open source projects, and it can build docs automatically (nightly) or with webhooks whenever a commit is merged to the repository.

We should setup a test branch of brave-browser with a docs directory and an account on readthedocs.org to see how this looks and validate the process is acceptable to the team.

Todo items:

- [x] create branch and add some .rst files to render in docs directory
- [x] register devops account on readthedocs.org and import the project
- [x] document process to perform doc updates
- [x] get feedback from team
- [x] hold demo session for developers to better understand how reStructuredText, Sphinx, and readthedocs work
- [x] if acceptable setup webhooks to perform updates every time a git commit happens (vs. the nightly default)

**Comment by Jacalz** [comment]
Another option would be to have a page like https://solus-project.com/help-center/categories/ where the actuall docs are in a github repository and then automatically updated on the website with ever new change. Take a look at: https://github.com/solus-project/help-center-docs

The good thing is that users and developers that are used to GitHub can easily use it, and it’s all open source this way...

**Comment by mbacchi** [comment]
Created branch `readthedocs`: https://github.com/brave/brave-browser/tree/readthedocs

Linked ReadTheDocs account Brave to use the branch above.

Build of first test commit available to view here: https://brave-browser.readthedocs.io/en/latest/

**Comment by mbacchi** [comment]
Looking for comments on the usability of this tool. If folks would take a look and let me know if its too complex or reStructuredText is too confusing, I'm willing to chat if you have concerns or questions. @bridiver @bsclifton @bbondy @Jacalz @bkero @RyanJarv @w0ts0n

**Comment by mbacchi** [comment]
I'm closing this and calling it done, we have this configured to build every time a commit occurs on the brave-browser repo.
