### ISSUE TITLE
adding UI to deal with "TransportError: Failed to sign with Ledger device" or "Access Denied"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6110]
## Description 

When attempting to connect the Ledger Nano with Brave using `Mint 19.1 x64`, you'll get the following error message when using the extension inspector:

```
Uncaught (in promise) TransportError: Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE
```

When you run into the above, you'll get the infinite loading spinner when connecting too either . `MM` or `Brave`. If you attempt to connect to https://mycrypto.com, you'll get an "Access Denied". After doing some research, found the following:

* https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues

You'll basically need to add the following into the `plugdev` group within `/etc/group`:

```
wget -q -O - https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh | sudo bash
```

Once you add the above, `MM`, `Brave` and  https://mycrypto.com will work as expected.

I'm not 100% sure if this affects all Linux installations though.

## Steps to Reproduce

N/A (basically try connecting to either MM, Brave or https://mycrypto.com with a new Mint installation and you won't be able to connect unless the above is done.

## Actual result:

When connecting, you'll receive the following via the extension inspector:

```
Uncaught (in promise) TransportError: Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE
```

If you attempt to connect to https://mycrypto.com, you'll get "Access Denied"

## Expected result:

Some type of UI/Error indicating that access was denied and perhaps a suggestion on how to fix the issue. This affects MM as well so it would be nice to get it fixed upstream.

## Reproduces how often: 

100% reproducible until rule is added into `plugdev` group within `/etc/group`

## Brave version (brave://version info)

Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
--- | ---
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A (didn't try Chrome + MM)

## Miscellaneous Information:

CCing @bbondy @rebron @tomlowenthal @brave/legacy_qa

**Comment by bbondy** [comment]
Same as MetaMask?

**Comment by bbondy** [comment]
Might be related to https://github.com/brave/brave-browser/issues/6105

**Comment by bbondy** [comment]
This no longer applies since we changed away from the U2F transport to webHID.
