### ISSUE TITLE
Not properly blocking popups ads

### ISSUE THREAD

**Issue by silviolobo** [brave/brave-browser#6112]
## Description 
Not properly blocking popups ads from RARBG

## Steps to Reproduce
   1.  Access: https://rarbgproxied.org/torrents.php
   2. Try to hover the mouse on the movie covers to see a tooltip with some info. If won't appear the tooltip, then their "ad script" is activated and If you click anywhere on the page, it should open another tab with some ad.
   3. Wait after seconds to make the script execute again (after you open some ads, stops happening). Or try to enter the website on a private window to reproduce again.

## Actual result:
Doesn't block the script that created the ad.
If you disable the scripts (Shields), won't happen but you will lose some of the website functionalities

## Expected result:
Using Chrome + uBlock Origin (default settings) works properly (maintaining all JavaScript functionalities and no popups)

## Reproduces how often: 
It happens whenever you access the website after a while.

## Brave version (brave://version info)
Brave: 0.68.139 Chromium: 77.0.3865.90 (Official Build) (64-bit)

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Yes.
- Can you reproduce this issue with the dev channel? Yes.
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? With adblocking extension, no.

**Comment by rebron** [comment]
cc: @ryanbr Cosmetic filter issue?
