### ISSUE TITLE
OIDC issue in incognito mode

### ISSUE THREAD

**Issue by RemiKalbe** [brave/brave-browser#6115]
## Description 

See https://github.com/ory/hydra/issues/1573 and https://github.com/IdentityModel/oidc-client-js/issues/952

## Brave version (brave://version info)

0.68.139 Chromium: 77.0.3865.90

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Yes
- Can you reproduce this issue with the dev channel?
Yes
- Can you reproduce this issue with the nightly channel?
Yes

## Other Additional Information:

The shield is disabled.
And I didn't have this issue yesterday or the day before.

**Comment by rebron** [comment]
We need some more context. Not sure what you're requesting.

**Comment by bsclifton** [comment]
Closing due to lack of information
