### ISSUE TITLE
Tweekdeck doesn't load with Shields enabled (needs Cookies enabled)

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#6117]
## Description 
Visiting `https://tweetdeck.twitter.com/` If sheilds is enabled, won't allow the user to use tweetdeck. Only working with Cookies is enabled.

Previous bug report;
https://github.com/brave/brave-browser/issues/3495

## Steps to Reproduce

   0. With Sheilds enabled (site cookies)
   1. Visiting `https://tweetdeck.twitter.com/` 
   2. Expect tweetdeck screen
   3. Get a twitter login and then standard twitter page

## Expected result:
Show tweetdeck correctly, not the standard twitter screen.

## Reproduces how often: 
Easily when sheilds is enabled / when cross-site cookies is enabled. 

## Brave version (brave://version info)
Version 0.68.139 Chromium: 77.0.3865.90 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Yes
- Can you reproduce this issue with the nightly channel?
No.

## Miscellaneous Information:
3 cookies are set from;
`twitter.com`
`api.twitter.com`
`tweetdeck.twitter.com`

Not sure how any of these are considered 3rd-party cookies

**Comment by ryanbr** [comment]
Confirmed with user, this isn't occurring in Nightly. 

https://twitter.com/MBobnificent/status/1175630119865659392

**Comment by rebron** [comment]
@ryanbr Is this working in other channels now or is there a specific fix we need to uplift?

**Comment by ryanbr** [comment]
Just confirming with the user via twitter, thanks for the reminder @rebron  :)

It seems fine now. I was able to use tweetdeck

**Comment by kjozwiak** [comment]
@rebron can we close this off?

**Comment by ryanbr** [comment]
Yup, resolved. 

Fixed was removing all *.twitter.com from Preferences json then let Brave rebuild it again. Not sure caused the issue, but its resolved.
