### ISSUE TITLE
Brave Browser Won't load Whatsapp web.

### ISSUE THREAD

**Issue by DrDanik** [brave/brave-browser#6128]
Description
WhatsApp Web will not load anymore. The QR code never shows.

Steps to Reproduce
`https://web.whatsapp.com`
Actual result:
![image](https://user-images.githubusercontent.com/55684977/65408113-b1655180-dde4-11e9-9b25-948ccd775416.png)

Expected result:
Opens WhatsApp Web.

Reproduces how often:
Every time.

Brave version (brave://version info)

Brave | 0.70.97 Chromium: 77.0.3865.65 (Official Build) beta (64-bit)
-- | --
Revision | 87a331a3169cab563505fb44011058b904011ba1-refs/branch-heads/3865@{#726}
OS | Windows 10 OS Version 1809 (Build 17763.678)
JavaScript | V8 7.7.299.10
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.65 Safari/537.36

Version/Channel Information:
Can you reproduce this issue with the current release?
yes
Can you reproduce this issue with the beta channel?
Not Sure.
Can you reproduce this issue with the dev channel?
Not Sure.
Can you reproduce this issue with the nightly channel?
Yes.
Other Additional Information:
Does the issue resolve itself when disabling Brave Shields?
No.
Does the issue resolve itself when disabling Brave Rewards?
No.
Is the issue reproducible on the latest version of Chrome?
No.

**Comment by Skarlso** [comment]
FFW I'm on OSX and it's working right now 🤔. 
Version:
Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)
Guess I'm one version behind.

**Comment by DrDanik** [comment]
:(

**Comment by Skarlso** [comment]
Still not? I'm guessing you probably tried re-installing, clearing cache and cookies and such?

**Comment by DrDanik** [comment]
I did. I did.
Uninstalled, reinstalled, etc etc
It really doesn't work.
:(

**Comment by rebron** [comment]
@DrDanik Can you take a look at your Shields settings and see if you have 'cross-site device recognition blocked' and not 'device recognition attempts blocked'?  That's likely blocking the QR code.

**Comment by CJCombrink** [comment]
I have the same issues, it did work before an update:
```
Brave is up to date
Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
```

Other information:
Does the issue resolve itself when disabling Brave Shields? **No**
Does the issue resolve itself when disabling Brave Rewards? **No**
Is the issue reproducible on the latest version of Chrome? **No**

**Comment by bsclifton** [comment]
@DrDanik @CJCombrink is this still an issue for you all?

**Comment by rebron** [comment]
I tried on 1.4.95 on Windows and 1.7.40 on macOS and I'm able to see the QR code with shields up and was able to login properly.

**Comment by timecop97** [comment]
Was running into issues with the QR not loading despite shields down and cross-site device recognition allowed, but it loaded after leaving the site open for a couple minutes. 

Version 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit)

**Comment by rebron** [comment]
Closing as fixed. Looks like `https://web.whatsapp.com` is working.

**Comment by lvbaal** [comment]
The QR-code is show all right, however the app on mobile does not read it. When I do the same on firefox, the code is read and I am logged in to web.wahtsapp.com.

**Comment by AdrienGentizon** [comment]
I am using an extension to block/unblock CORS when it's active which means allowing for CORS action You'll never see any QR code so you have to turn off in order to WhatsApp Web to work again.
So, for me it was the CORS issue as @DrDanik said.

**Comment by dingop** [comment]
The QR Code is not loading fully. This is still an issue. After sometime, you get a message "click to reload QR code
version: V1.20.103

**Comment by dingop** [comment]
> The QR Code is not loading fully. This is still an issue. After sometime, you get a message "click to reload QR code
> version: V1.20.103

Somehow, after a restart, I tried again. It seems to be working now.
