### ISSUE TITLE
Leaving sync does not propagate the event to other devices

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6131]
## Steps to Reproduce

Note: All devices are clean installs

1. Create sync on Nightly
2. Sync Beta
3. Sync Dev
4. Wait for all devices to be synced  
5. Leave sync with Nightly

## Actual result:

Beta and Dev have 3 synced devices
Nightly was not removed from all synced devices 
![image](https://user-images.githubusercontent.com/34715963/65439096-ed210b00-de26-11e9-90c7-2584d237a09f.png)

## Expected result:
Beta and Dev have 2 synced devices
Nightly was removed from all synced devices 

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Beta:

Brave | 0.70.97 Chromium: 77.0.3865.65 (Official Build) beta (64-bit)
-- | --
Revision | 87a331a3169cab563505fb44011058b904011ba1-refs/branch-heads/3865@{#726}
OS | Windows 7 Service Pack 1 (Build 7601.24519)

Dev:

Brave | 0.71.74 Chromium: 77.0.3865.75 (Official Build) dev (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 7 Service Pack 1 (Build 7601.24519)

Nightly

Brave | 0.72.44 Chromium: 77.0.3865.90 (Official Build) nightly (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 7 Service Pack 1 (Build 7601.24519)

**Not reproducible on release**:

Brave | 0.68.140 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 7 Service Pack 1 (Build 7601.24519)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

cc @brave/legacy_qa  @darkdh @SergeyZhukovsky @rebron

**Comment by kjozwiak** [comment]
@GeetaSarvadnya mind going through the above one more time now that the sync issues have been resolved with the various `0.69.x` HF's? As per @SergeyZhukovsky, everything was reenabled via server side so changes should be propagating now.

**Comment by btlechowski** [comment]
The issue is no longer reproducible

Brave | 0.72.60 Chromium: 77.0.3865.90 (Official Build) nightly (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 7 Service Pack 1 (Build 7601.24519)

Brave | 0.71.74 Chromium: 77.0.3865.75 (Official Build) dev (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 7 Service Pack 1 (Build 7601.24519)

Brave | 0.70.104 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 7 Service Pack 1 (Build 7601.24519)

![image](https://user-images.githubusercontent.com/34715963/65943815-ad62b080-e430-11e9-99d2-f6c9578921a0.png)

It would be good to verify the issue again in 0.70.x milestone.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.110 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Verified STR from the description.
