### ISSUE TITLE
Browser crypto wallet still gets detected as Metamask on websites

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6135]
## Description 

Browser crypto wallet still gets detected as Metamask on websites

## Steps to Reproduce

   1. Enable crypto wallet on browser
   2. Visit https://cryptokitties.co/
   3. Site detects wallet as Metamask

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/65447347-517ea300-de04-11e9-97f6-3afa62558772.png)
![image](https://user-images.githubusercontent.com/17010094/65447360-5e02fb80-de04-11e9-9e1d-796c2214d3d7.png)
Also has Metamask icon  in the connect popup window
Learn more links to https://medium.com/metamask/introducing-privacy-mode-42549d4870fa
Once signed in Shows `Connected wallet: Metamask`
![image](https://user-images.githubusercontent.com/17010094/65447428-9276b780-de04-11e9-9e6e-f6e6e4f1d840.png)

## Expected result:
No Metamask branding anywhere and sites shouldnt detect it as Metamask

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.70.97 Chromium: 77.0.3865.65 (Official Build) beta (32-bit)
-- | --
Revision | 87a331a3169cab563505fb44011058b904011ba1-refs/branch-heads/3865@{#726}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @ryanml @bbondy @tomlowenthal

**Comment by bbondy** [comment]
Is this our UI @ryanml or is it the UI of the page?

**Comment by bbondy** [comment]
At least for now I don't think we're going to add an isBrave type of function. Websites should not assume and they should feature detect instead of using something like a user agent.
