### ISSUE TITLE
Ads are not shown due to compressed resources failing to load

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#6139]
## Description 

Ads are not shown due to compressed resources failing to load

## Steps to Reproduce

   1. Visit a website
   2. Idle

## Actual result:

Ads are not shown

## Expected result:
Ad should be shown

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

0.72.18 or above

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by GeetaSarvadnya** [comment]
1+ from https://community.brave.com/t/not-getting-any-ads/83189

**Comment by GeetaSarvadnya** [comment]
1+ from https://community.brave.com/t/another-case-of-ads-not-coming-in/85107

**Comment by diposs** [comment]
It has been fixed on current nightly

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.112 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3515

![image](https://user-images.githubusercontent.com/34715963/66789698-0e888a80-eeed-11e9-951d-a4fd324c925b.png)
![image](https://user-images.githubusercontent.com/34715963/66789730-2b24c280-eeed-11e9-8095-b78db5b3a94e.png)
