### ISSUE TITLE
disable chrome.webstore.install for inline extensions

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#614]
context: https://blog.chromium.org/2018/06/improving-extension-transparency-for.html

inline extensions are a huge malware risk. we should disable them in Brave.

AFAIK it is sufficient to disable the chrome.webstore.install method

note that in c71,  chrome will disable it as well (possibly with a redirect to CWS which would be slightly better UX than silently failing).

**Comment by bbondy** [comment]
Noting possibly the right thing is to redirect instead of remove the API.

**Comment by bbondy** [comment]
@AilinLiao @bsclifton after this lands you'll have to rebase your patch I think.

**Comment by bbondy** [comment]
QA note: zenhub has an extension on their page which uses this API.

**Comment by btlechowski** [comment]
Verification passes on

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

redirected to ZenHub for GitHub on chrome web store
