### ISSUE TITLE
Font-family: sans-serif showing Times New Roman instead of Arial

### ISSUE THREAD

**Issue by dalmo3** [brave/brave-browser#6140]
## Description 

Since last week I've been getting this issue where some websites would start rendering Times New Roman fonts. 

Upon inspection, all 'broken' websites use `font-family: sans-serif` or some combinations of it. 

## Steps to Reproduce

   1. Open www.google.com or any website that uses `font-family: sans-serif`
   2. See that font is not Arial (In my case, Times New Roman)

## Actual result:

![Screen Recording 2019-09-24 at 11 27 48 80 AM](https://user-images.githubusercontent.com/33860060/65470984-81d84700-dec1-11e9-9869-87037720dd7c.gif)

## Expected result:
This taken from Chrome while Brave was broken:
![Screen Recording 2019-09-24 at 11 25 57 31 AM](https://user-images.githubusercontent.com/33860060/65470993-8ac91880-dec1-11e9-9c0d-476f78ab893b.gif)

## Reproduces how often: 

Intermittent. 
Once it breaks, restarting windows fixes it. 
Once it breaks, it breaks all user profiles, guest mode etc.
(Next time I should check if a brave://restart fixes it as well.)

## Brave version (brave://version info)

Brave | 0.68.139 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1903 (Build 18362.356)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **No**
- Does the issue resolve itself when disabling Brave Rewards? **No**
- Is the issue reproducible on the latest version of Chrome? **No, there's no problem on chrome**

**Comment by rebron** [comment]
We would need more info to reproduce this? Is there anything else you did with fonts or accessibility settings on your Windows machine that may have caused this?

**Comment by dalmo3** [comment]
Nothing that I remember, sorry. 

To be fair it hasn't happened again since I reported.

**Comment by bsclifton** [comment]
Closing - but let's re-open if it happens again. I'm curious if any system settings affected this (Chromium will respect the system and accessibility settings)
