### ISSUE TITLE
Stub installer fails to download the build on Windows 7

### ISSUE THREAD

**Issue by Atheist3** [brave/brave-browser#6141]
https://github.com/brave/brave-browser/issues/2129

This has NOT been resolved as I cannot download/install brave.

In fact, I didn't even know if the installer ran or not, as when I ran it I got ABSOLUTELY NOTHING on my screen that showed that it HAD run!!!!

Only after choosing "run as administrator" did it show the graphic shown in the other thread. (The 2 images showing showing "Egads!..." and "The download failed.".

"Oh, okay, duuuuhhhh, i guess it don't works on mys computer".

This is PRECISELY WHY, EVEN in September 2019.... people CAN'T/AREN'T able to use computers......

NOT
USE
FRIENDLY
!!!!!!

**Comment by bsclifton** [comment]
cc: @btlechowski can you try this out? I know you use Windows 7; curious if you've had any issues

also cc: @GeetaSarvadnya

**Comment by btlechowski** [comment]
The stub installers work fine on Windows 7 x64 and Windows 7 x86.

Tested on 

Brave | 0.68.141 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 7 Service Pack 1 (Build 7601.24519)

![image](https://user-images.githubusercontent.com/34715963/65732584-d13d9380-e0ca-11e9-8392-4b13b0684737.png)
![image](https://user-images.githubusercontent.com/34715963/65732601-d7cc0b00-e0ca-11e9-9ec1-8f2f273552fa.png)

Maybe something blocked the installer from downloading the build

@Atheist3 Do you have Windows 7 64 bit or 32 bit? Do you have a fire wall install or/and antivirus?

**Comment by kjozwiak** [comment]
Double checked again on `Win 7 x64` via VM and installed Brave without any issues. @Atheist3 are you still having issues? Maybe you hit some networking issues? We've had a few issues in the past where the back-end that was serving builds was down. Or as @btlechowski suggested, something might be blocking Win from connecting?

**Comment by bsclifton** [comment]
Closing as this is not reproducible and there hasn't been any response from original poster

**Comment by tominterval** [comment]
I'm having this exact same problem, and no one seems to know how to fix it. I opened a separate string. I'm trying to install Brave for the first time on Windows 8.1. The installer starts, but then I get the "Egads..." and "The download failed" boxes. This has been going on for three days. No luck.
![downloadfailed01](https://user-images.githubusercontent.com/58096621/134661979-f19500b4-78c1-494d-b2e1-cdf25a81f93c.jpg)
![downloadfailed02](https://user-images.githubusercontent.com/58096621/134661981-e75e7d91-2eec-4222-b7d2-618769b4283e.jpg)

**Comment by tominterval** [comment]
And I checked my McAfee, which tells me permissions have already been added. So I don't think McAfee is blocking it.
