### ISSUE TITLE
Native ledger lib should use GCD for iOS for concurrency

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#6143]
## Description 

https://github.com/brave/brave-core/pull/3491 Introduces a fix for a crash due to using base's `PostTaskAndReplyWithResult` on iOS. This solution is only specific to the Proof batching and should be generalized to be used wherever concurrency is needed

**Comment by NejcZdovc** [comment]
@kylehickinson can you look in this one?

**Comment by kylehickinson** [comment]
This will be fixed when we background all ledger tasks for iOS

**Comment by kylehickinson** [comment]
@Miyayes It was never done in one go but we've replaced as needed. This can be closed as stale/won't do
