### ISSUE TITLE
404 service - archived page recommendation

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#6144]
When users encounter a 404 error, present them with an option to look up an archived version of the web page (using wayback machine api).

## Design
[placeholder]

## Test Plan
[placeholder]

**Comment by simonhong** [comment]
@cezaraugusto I'll start to implement infobar UI :)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.4.84 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from  https://github.com/brave/brave-core/pull/3561
- Verified the test plan in Guest/Private/TOR - works as expected
- Bookmark an archived page `brave.com/bo` and click on bookmark link shows up archived page upon clicking on `Check saved version`
- Verified that archived page is not shown when `Show Wayback...` switch is turned OFF
- Verified that archived page is shown in Profile2 even when Wayback switch is turned OFF in Profile 1
- Verified that archived page `brave.com/bo` isn't shown when network/wifi is turned OFF
