### ISSUE TITLE
Ads panel disappeared from brave://rewards page after upgrade (0.68.140 to 0.69.128)

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#6148]
## Description 

Ads panel disappeared from brave://rewards page after upgrade (0.68.140 to 0.69.128)

## Steps to Reproduce

Prerequisites: VPN is connected to the United States and language is set to English (US)

   1. Clean profile 0.68.140
   2. Enable rewards
   3. Make sure ads switch is enabled by default
   4. Disable Ads switch
   5. Upgrade to 0.69.128
   6. Navigate to brave://rewards page and observe Ads panel is completely removed

## Actual result:

Ads panel disappeared from brave://rewards page after upgrade (0.68.140 to 0.69.128)

![Ads panel disappered](https://user-images.githubusercontent.com/38657976/65545398-ec759b00-df32-11e9-9ed2-42f4d8f349fb.gif)

![image](https://user-images.githubusercontent.com/38657976/65544579-2180ee00-df31-11e9-8e24-b82954d5898e.png)

## Expected result:
Ads should panel should not be removed and it should be in disabled state after upgrade

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @tmancey @jsecretan @rebron @brave/legacy_qa

**Comment by LaurenWags** [comment]
Reproducible on macOS.


Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | macOS Version 10.13.6 (Build 17G5019)

Noticed that 0.69.128 is a minor chromium version behind 0.68.140 - unsure if that could be causing an issue?

**Comment by LaurenWags** [comment]
Reproduces with latest 0.68.x (0.68.141) and upgrading to 0.69.129.


Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

**Comment by GeetaSarvadnya** [comment]
Issue persists in one ore scenario, open any old profile where ads are Cashed in/ Viewed. Ads panel is removed.

![image](https://user-images.githubusercontent.com/38657976/65685880-ac243300-e080-11e9-822d-9733a418f1db.png)

**Comment by yodaross** [comment]
Stop lying like you are unaware of what you are causing problems with in
brave, america, and elsewhere.  You are not Cia, they are a defunded
terrorist branch in america solely because you work for them.

**Comment by GeetaSarvadnya** [comment]
The issue is still reproducible in `0.69.130`


Brave | 0.68.141 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

**Comment by LaurenWags** [comment]
When QA verifies this issue, we should also check the following scenario:
Have a profile with Rewards On in a region where Ads are not enabled.
Upgrade to version with the fix.
Verify Ads panel is displayed with the "Sorry" message.

**Comment by ryanml** [comment]
@LaurenWags @GeetaSarvadnya just to note this is still waiting uplift approval

**Comment by LaurenWags** [comment]
@ryanml do you believe your fix will also resolve the steps I outlined in: https://github.com/brave/brave-browser/issues/6148#issuecomment-536582997 ?

**Comment by ryanml** [comment]
@LaurenWags I believe so yes, what my fix resolved was an explicit code return that would not show the panel, so with that gone the panel should continue to function as expected, with state for non-supported region showing appropriately

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified original STR from description. After update to `0.69.131` Ad panel is shown with Ads off as expected.
* Verified scenario from https://github.com/brave/brave-browser/issues/6148#issuecomment-536582997 . After update to `0.69.131` Ad panel is shown with 'Sorry' message as expected. Verified using Japan region.
* Verified on a clean install of `0.69.131`, when Rewards are enabled the Ads panel is shown. Ads increment on the panel as expected.
* Verified when Ads are on and have been viewed with `0.68.142`, after update to `0.69.131` Ad panel is shown with Ads on as expected. Data is retained after upgrade. Verified Ads panel increments when ads are shown after upgrade.
