### ISSUE TITLE
Update Chromecast (Media Router) restart UI 

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#6149]
Update Chromecast (Media Router) restart UI to match inline `Relaunch` buttons

**Current**
![image](https://user-images.githubusercontent.com/1903815/65548489-6fb1d500-ded0-11e9-9b41-e5e3be3acd72.png)

**Expected**
![image](https://user-images.githubusercontent.com/1903815/65548523-78a2a680-ded0-11e9-8748-10fb29100b65.png)

**Comment by bsclifton** [comment]
This is fixed now! 😄
