### ISSUE TITLE
Strict Site Isolations Breaks U2F 2FA

### ISSUE THREAD

**Issue by stefanperson** [brave/brave-browser#615]
## Description 

Enabling "Strict Site Isolation" breaks Yubikey U2F 2FA.

## Steps to Reproduce

   1. Enable Strict Site Isolation
   2. Login to ex) google mail
   3. Enter username
   4. Enter password
   5. Enter 2FA. Prompts user with error. See attached pics.

## Actual result:

![screen shot 2018-07-20 at 1 31 29 pm](https://user-images.githubusercontent.com/8204597/43024117-0ef92e40-8c22-11e8-9333-1b1bee734d0f.png)
![screen shot 2018-07-20 at 1 30 54 pm](https://user-images.githubusercontent.com/8204597/43024118-0f1003c2-8c22-11e8-97f8-446a98ff7899.png)

## Brave version (about:brave info) 

![screen shot 2018-07-20 at 1 38 13 pm](https://user-images.githubusercontent.com/8204597/43024148-2e49d862-8c22-11e8-9baf-beb292d93e58.png)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

Nope.

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/browser-laptop/issues/14794. @stefanperson please track issue on browser-laptop repo. This repository is for brave-core only
