### ISSUE TITLE
Tipping Thank You/Confirmation should be inline

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#6151]
<img width="747" alt="Screen Shot 2019-09-24 at 2 54 39 PM" src="https://user-images.githubusercontent.com/8732757/65553280-5febbe00-dedb-11e9-9443-6fb26e9e48df.png">

Test Plan:
1. Enable Rewards
2. Opening the tipping banner for a publisher.
3. Send a Tip
4. Confirm that the old overlay does not show and instead the new inline confirmation shows up
5. Confirm that share links work as expected

**Comment by ryanml** [comment]
@jenn-rhim do we have a design for the new Monthly variant's confirmation? Not sure if we wanted to show one with the orange scheme. cc: @NejcZdovc

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.2.7 Chromium: 78.0.3904.108 (Official Build) dev (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3789
- Logged https://github.com/brave/brave-browser/issues/7047
