### ISSUE TITLE
Add link to brave.com/latest in "About Brave" section

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#6152]
## Description 

Users should be able to easily navigate to release notes page from the browser. inserting a link to brave.com/latest in the `About Brave` section in `Settings` would resolve this:

![image](https://user-images.githubusercontent.com/3299098/65556793-c37ae900-dee5-11e9-802a-fe8b9ba3e76c.png)

@bradleyrichter @rebron

**Comment by Brave-Matt** [comment]
Just to clarify -- I don't think the link need be underlined. _Maybe_ on hover? But the underlined segment in my mock above is just the area/text that should be clickable.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3828
![image](https://user-images.githubusercontent.com/38657976/68582775-92f50b80-04a1-11ea-97fb-b53c4dd53d12.png)
