### ISSUE TITLE
Mouseover text/ Alt text fading too quickly? 

### ISSUE THREAD

**Issue by stortzm** [brave/brave-browser#6153]
## Description 
when you hover your mouse over a link or button, the alt text should display a box with the text, normally a description of the hyperlink. The box with the text instantly disappears after mileseconds.  

## Steps to Reproduce

   1. Mouseover a link
   2. Wait for the alt text to show
   3. Alt text disappears before you can read it/ move the mouse away

## Brave version (brave://version info)
Version 0.68.140 Chromium: 77.0.3865.90 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by stortzm** [comment]
this issue has been resolved in Brave 0.70.121

**Comment by bsclifton** [comment]
@stortzm thanks for confirming and closing 😄👍
