### ISSUE TITLE
Don't send sync update on favicon change

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#6158]
Currently chromium sync triggers favicon update on every bookmark visit and we resend a record. We shouldn't do that.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Other device was Windows 7 with 0.69.131

Verified test plan from https://github.com/brave/brave-core/pull/3526

Verified that only `"action":0` entries are listed
![image](https://user-images.githubusercontent.com/34715963/66001599-15051400-e4a2-11e9-95ce-dc83816f4476.png)
Verified that clicking on the bookmark on device A or device B does not trigger any send event

**Comment by kjozwiak** [comment]
Looks like this was never added into the `0.69.x` milestone.

**Comment by bsclifton** [comment]
@kjozwiak whoops - sorry about that! Thanks for catching 😄
