### ISSUE TITLE
Mouse Cursor for Password Manager Browser Extension Text Entry Does Not Activate

### ISSUE THREAD

**Issue by stefanperson** [brave/brave-browser#616]
## Description 

For the Brave Browser + Bitwarden Password Manager Extension:

The mouse cursor for text entry is not active by default. It requires an additional mouse click to begin typing my master password to enter the vault.

It would be more convenient when entering the password (especially while using a Yubikey) if the cursor text entry was active by default.

It is active by default with Chrome.

## Steps to Reproduce

   1. Enable Bitwarden browser extension
   2. Click on extension to enter password
   3. The text field cursor does not active and requires another click here.

## Actual result:

![42836574-49da806e-89b0-11e8-86ee-1f5f940a10ab](https://user-images.githubusercontent.com/8204597/43024329-d8174ee2-8c22-11e8-80e7-0cbde1244183.png)

## Expected result:

The mouse cursor should active after clicking on extension.

## Reproduces how often: 

Every time

## Brave version (about:brave info) 

![screen shot 2018-07-20 at 1 38 13 pm](https://user-images.githubusercontent.com/8204597/43024355-ecbaac86-8c22-11e8-8e48-d0972218607a.png)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

No

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/browser-laptop/issues/14795. @stefanperson please track the issue on browser-laptop repo. This repository is for brave-core only.
