### ISSUE TITLE
launching "Connect Hardware Wallet" after creating local wallet if user initially selected "Connect" on either "Ledger || Trezor"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6160]
## Description 

When a new user either selects `Ledger` or `Trezor` to connect to their HW via `brave://wallet`, you'll initially need to create a local wallet before you can attempt to connect to whatever HW is connected. However, once you've created the local wallet, the user will still need to select `Connect Hardware Wallet`.

This might confuse users as the original UI under `brave://wallet` specifies that those two options are for connecting to HW wallets which doesn't initially happen.

## Steps to Reproduce

   1. launch `0.69.128 CR: 77.0.3865.75` and open `brave://wallet`
   2. select `Connect` on either `Ledger` or `Trezor`
   3. enter your password and click on `Remind me later` under `Secret Backup Phrase`

You'll notice that the local wallet is created but nothing else happens even though you've selected `Connect` from one of the HW choices.

## Actual result:

Once you've created the local wallet, the `Connect Hardware Wallet` doesn't launch even though you've selected `Connect` on one of the HW choices.

## Expected result:

When a user initially selects `Connect` via `brave://wallet`, we should launch the `Connect Hardware Wallet` UI after the local wallet has been created.

## Reproduces how often: 

100% reproducible when going through the above STR.

## Brave version (brave://version info)

Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | macOS Version 10.14.6 (Build 18G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A` (technically not released)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @ryanml @brave/legacy_qa

**Comment by srirambv** [comment]
Verification passed on 

Brave |  Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

* Verified `Connect Hardware Wallet` prompt is shown immediately after the local wallet is created
* Verified works on component version: 1.0.9
[6160.zip](https://github.com/brave/brave-browser/files/3683244/6160.zip)

Verification passed on 

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1903 (Build 18362.30)

* Verified `Connect Hardware Wallet` prompt is shown immediately after the local wallet is created
* Verified works on component version: 1.0.9
