### ISSUE TITLE
removing "Cancel" & "Save" buttons for ETH networks that have already been created and can't be edited

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6161]
## Description 

When going into `brave://wallet` --> `Settings` --> `Networks`, you'll notice that there's `Cancel` & `Save` buttons for each network that's already created by default. However, you can't edit those networks. We should only be displaying `Cancel` & `Save` for custom networks that have been added by going through `Add Network`.

## Steps to Reproduce

   1. launch `0.69.128 CR: 77.0.3865.75` and open `brave://wallet`
   2. click on `Create` under `New Local Wallet`
   3. enter your password and click on `Remind me later` under `Secret Backup Phrase`
   4. click on the `My Accounts` avatar --> `Settings` --> `Networks`

You'll notice `Cancel` & `Save` buttons that can't be used for the networks that have already been created.

## Actual result:

<img width="1089" alt="Screen Shot 2019-09-24 at 11 49 20 PM" src="https://user-images.githubusercontent.com/2602313/65568492-0cec2800-df28-11e9-9665-bab68d20da22.png">

## Expected result:

Shouldn't be displaying `Cancel` & `Save` buttons for the networks that have already been created as you cannot edit them.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.69.128 Chromium: 77.0.3865.75 (Official Build) (64-bit)
-- | --
Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS | macOS Version 10.14.6 (Build 18G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A` (technically not released)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @brave/legacy_qa

**Comment by bbondy** [comment]
can we upstream too?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using https://github.com/brave/ethereum-remote-client/releases/tag/1.0.10 via the following build:

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

* ensured that you can't edit/remove the default networks from `Settings -> Networks`
* ensured that you can create/edit and delete a custom network

<img width="1072" alt="Screen Shot 2019-10-07 at 1 43 23 PM" src="https://user-images.githubusercontent.com/2602313/66335445-0dfa5d80-e909-11e9-9ffd-d50891bb83a4.png">

<img width="1061" alt="Screen Shot 2019-10-07 at 1 42 53 PM" src="https://user-images.githubusercontent.com/2602313/66335450-0e92f400-e909-11e9-80fe-246091880030.png">

<img width="1304" alt="Screen Shot 2019-10-07 at 1 45 17 PM" src="https://user-images.githubusercontent.com/2602313/66335536-32563a00-e909-11e9-89b6-24147b286a8a.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

* Verified existing pre-loaded networks can't be edited using `1.0.10` via sideload
* Verified new network added can be saved/edited/deleted
![image](https://user-images.githubusercontent.com/17010094/66394280-b7416200-e9a2-11e9-9ed8-0f8c3f5825ad.png)
![image](https://user-images.githubusercontent.com/17010094/66394355-eb1c8780-e9a2-11e9-83f9-0bf9f361d953.png)
