### ISSUE TITLE
Brave shown as Google Brave in Android settings

### ISSUE THREAD

**Issue by Ravendwyr** [brave/brave-browser#6165]
## Description 

Brave is shown as "Google Brave" at the top of Brave's storage settings.

## Steps to Reproduce

   1. Navigate to Brave in Android's app management.
   2. Click on Storage.
   3. Click on Clear Storage.

## Actual result:

![Screenshot_20190924-222846](https://user-images.githubusercontent.com/8914/65578838-80188d00-df6e-11e9-9c5a-bb727732eefb.jpg)

## Expected result:
No reference to Google.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version info page not available. Android app management says "1.3.2" however.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not available for Android
- Can you reproduce this issue with the dev channel? Not available for Android
- Can you reproduce this issue with the nightly channel? Not available for Android

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

My phone is a OnePlus 6 running the latest version of Android OS, Oxygen OS, and OnePlus Launcher. Other phone setups may not be affected.

**Comment by bsclifton** [comment]
This has been fixed!
