### ISSUE TITLE
Extension URL for Crypto Wallets should not be added to history

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#6167]
Test Plan:

1. Fresh Profile
2. Navigate to `brave://wallet`
3. Create/Restore an account, move around the extension
4. Navigate to `brave://history/`
5. Confirm that no entries with the scheme `chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl` exist.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.1.4 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from description for both new wallets and restored wallets
