### ISSUE TITLE
P3A for android

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#6176]
To launch P3A on android we have to properly inform users about this feature.
Until then, P3A service is disabled in the code for android (see `BraveBrowserProcessImpl::brave_p3a_service()` usages.

**Comment by davidtemkin** [comment]
Added @anthonypkeane to drive mobile UX for notification and onboarding for existing and new users -- should parallel desktop, but will have to be custom-designed.

**Comment by bsclifton** [comment]
Let's use this issue to capture the Android specific work needed to get P3A working on Android. https://github.com/brave/brave-browser/issues/6688 captures the UI changes needed

**Comment by srirambv** [comment]
@AlexeyBarabash any reason why the issue is marked as QA/No? Shouldn't we test the changes for P3A? The associated PR has a proper test plan mentioned in it

**Comment by AlexeyBarabash** [comment]
at that time it required modified apk, which would hard to provide to QA team, and also the task wasn't complete without UI part, so it was marked QA/No

With new changes at https://github.com/brave/brave-browser/issues/12723 it requires a new test plan
