### ISSUE TITLE
Disabled Crypto Wallets Injects Code?

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#6181]
## Description 
Crypto Wallets is reportedly still injecting code into pages even when disabled. Other users were unable to reproduce the issue (https://twitter.com/GregJeanmart/status/1177222741239488514).

## Steps to Reproduce
See https://github.com/brave/brave-browser/issues/6181#issuecomment-535524669 below.

## Actual result:
MetaMask detects injected code.

## Expected result:
No code is injected when CryptoWallets is disabled.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
0.70.100 Chromium: 77.0.3865.90

## Miscellaneous Information:
Reported on Twitter: https://twitter.com/bitfalls/status/1177219557712388104

![image](https://user-images.githubusercontent.com/815158/65695510-4c586880-e03d-11e9-91dd-7ae20ff1a63d.png)

**Comment by Swader** [comment]
Version 0.70.100 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
Windows.

- Disable crypto wallets in settings
- Visit web3 page
- above error shows up.

Gif:

![bravemm](https://user-images.githubusercontent.com/1430603/65696282-38caf300-e079-11e9-89fb-184646d3bfde.gif)

**Comment by kjozwiak** [comment]
@bbondy looks you'll need to restart the browser when disabling `Brave Wallet`. If `Brave Wallet` was enabled and you disable it but still have MM installed, you'll still get the following error as mentioned above:

<img width="1400" alt="Screen Shot 2019-10-03 at 4 31 11 AM" src="https://user-images.githubusercontent.com/2602313/66111433-ddc45f00-e596-11e9-8330-c4060ae56605.png">

Once you restart the browser and refresh https://uniswap.exchange/swap, you'll get the following:

<img width="1387" alt="Screen Shot 2019-10-03 at 4 31 44 AM" src="https://user-images.githubusercontent.com/2602313/66111465-f03e9880-e596-11e9-834b-32f3c7814a83.png">

@bbondy went through the above using `0.69.132 CR: 77.0.3865.90` which is the latest RC. However, I'm seeing the same behaviour with `0.69.131 CR: 77.0.3865.90` regarding restarting the browser so not really sure if this was really fixed. Thoughts?
