### ISSUE TITLE
tip banner has message for connected publisher when panel does not - follow up to 5925

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6182]
## Description 
Found while testing #5925 

When executing test plan 1 & 2 from https://github.com/brave/brave-core/pull/3399, the panel does not contain a message but the tip banner does. Neither panel nor tip banner should have a message in the scenarios described below.

## Steps to Reproduce

Scenario 1 (from https://github.com/brave/brave-core/pull/3399)
1. Clean profile with 0.69.129 (staging env)
2. Enable Rewards
3. Claim Grant. Do not connect to Uphold at all - remain in anon wallet state
4. Navigate to a connected publisher - kjozwiakstaging.github.io
5. Click on panel - no message
6. Click on Send a tip button

Scenario 2 (from https://github.com/brave/brave-core/pull/3399)
1. enable rewards
2. claim grant
3. connect to uphold account that is not KYC
4. got to connected publisher
5. open a panel and make sure that you don't see any notice
6. Click on send a tip button.

## Actual result:
Message displayed on tip banner but not on panel:
<img width="1066" alt="Screen Shot 2019-09-26 at 10 50 40 AM" src="https://user-images.githubusercontent.com/28145373/65700176-32bf1d00-e04d-11e9-96ca-210e9bf69112.png">

## Expected result:
Panel and tip banner should be the same in regards to whether a message is displayed or not. In this case, there shouldn't be a message on either since I am trying to tip a connected (non-KYC'd) publisher with Brave controlled (UGP grant) BAT.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

Brave | 0.72.55 Chromium: 77.0.3865.90 (Official Build) nightly (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 0.68.x no, 0.69.x yes
- Can you reproduce this issue with the beta channel? unsure, probably yes
- Can you reproduce this issue with the dev channel? unsure, probably yes
- Can you reproduce this issue with the nightly channel? yes - 0.72.55

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @mandar-brave @NejcZdovc @brave/legacy_qa @rebron

**Comment by LaurenWags** [comment]
Note - occurs whether the publisher has a custom banner (image, amounts, etc) or not. Here is an example with a default banner:
<img width="1193" alt="Screen Shot 2019-09-26 at 11 07 56 AM" src="https://user-images.githubusercontent.com/28145373/65700634-f93ae180-e04d-11e9-9d40-1a33337bc537.png">

**Comment by GeetaSarvadnya** [comment]
The issue is reproducible in windows 10 - 0.69.129

![image](https://user-images.githubusercontent.com/38657976/65704113-907e5400-e0a3-11e9-87ce-92af047d38a9.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.70.109 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified scenario 1 from description
<img width="1199" alt="6182-scenario1" src="https://user-images.githubusercontent.com/28145373/66402047-2b373680-e9b2-11e9-8998-6754d75fdd39.png">

* Verified scenario 2 from description
<img width="1196" alt="6182-scenario2" src="https://user-images.githubusercontent.com/28145373/66402075-325e4480-e9b2-11e9-96c6-330d9363ebe2.png">

* Verified that same site does show the expected messaging when trying to tip using user BAT (BAT from an uphold connected wallet):
<img width="1196" alt="6182-regression" src="https://user-images.githubusercontent.com/28145373/66402182-70f3ff00-e9b2-11e9-88c7-58556914dec7.png">

* Verified no messaging is shown for a fully KYC'd publisher:
<img width="1196" alt="6182-reg2" src="https://user-images.githubusercontent.com/28145373/66402212-7f421b00-e9b2-11e9-8924-1a3603053500.png">
