### ISSUE TITLE
brave://welcome jank when resizing (specifically dark mode)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6183]
## Description 

When resizing the `brave://welcome` page, you'll notice that it's pretty janky/sluggish. Easily noticeable when using the `dark` theme. Sometimes it will also leave a light border at the bottom as the screen doesn't full repaint when it's resized quickly.

## Steps to Reproduce

   1. launch `0.69.129 CR: 77.0.3865.90` (make sure you're using dark theme)
   2. open `brave://welcome` and start resizing the window

## Actual result:

![welcomeJanky](https://user-images.githubusercontent.com/2602313/65710301-c0f0ce80-e060-11e9-9b6e-30e080a33505.gif)

## Expected result:

Resizing `brave://welcome` shouldn't be this janky/sluggish and should finish repainting the entire window once resized.

## Reproduces how often: 

100% reproducible when using the above STR.

## Brave version (brave://version info)

Brave | 0.72.53 Chromium: 77.0.3865.90 (Official Build) nightly (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)
JavaScript | V8 7.7.299.11

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A` (hasn't been released yet)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

## Miscellaneous Information:

CCing @brave/legacy_qa

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.110 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Verified test plan from the description
![6183](https://user-images.githubusercontent.com/34715963/66442355-beb44a00-ea3a-11e9-86d4-fe1ae49be1ed.gif)
