### ISSUE TITLE
panel does not show message about connected publisher when it should - follow up to 5925

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6184]
## Description 
Found while testing #5925 

When I have a completely empty wallet (anon or connected to Uphold but not KYC'd), and I visit a connected (not KYC'd) publisher, the panel doesn't show the expected message but the tip banner does.

## Steps to Reproduce

   1. Clean profile 0.69.129 (I used staging env)
   2. Enable Rewards
   3. Don't claim any grants or add any funds, keep wallet completely empty.
   4. Visit a connected publisher (kjozwiakstaging.github.io works)
   5. Click on the panel.

## Actual result:
No message on the panel for this publisher, but the message is displayed on the tip banner:
<img width="1202" alt="Screen Shot 2019-09-26 at 3 44 42 PM" src="https://user-images.githubusercontent.com/28145373/65720362-d02e4700-e075-11e9-8dec-3cca960e9775.png">

## Expected result:
In this case, the message should be displayed on both the panel and the tip banner.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

Brave | 0.72.55 Chromium: 77.0.3865.90 (Official Build) nightly (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 0.68.x no, 0.69.x yes
- Can you reproduce this issue with the beta channel? unsure, probably yes
- Can you reproduce this issue with the dev channel? unsure, probably yes
- Can you reproduce this issue with the nightly channel? yes 0.72.55

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @NejcZdovc @mandar-brave @rebron @brave/legacy_qa

**Comment by NejcZdovc** [comment]
@LaurenWags did you connect to uphold or not? Can't see it in your steps. If you didn't then we shouldn't display any message

**Comment by NejcZdovc** [comment]
closing as stale
