### ISSUE TITLE
Always provide application id and intention

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#6185]
For wallets that are pending we should add application id and intention to redirect url as well (like we do for connected wallets)

**Comment by LaurenWags** [comment]
`QA/Blocked` until we have an Uphold environment to test with (@mandar-brave is working on this)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.70.112 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3547
Staging Environment - Connected wallet (not KYC'd)
![image](https://user-images.githubusercontent.com/38657976/66586828-ef18f700-eba6-11e9-8580-52c86353a2de.png)


Prod Environment - Connected wallet (not KYC'd)
![image](https://user-images.githubusercontent.com/38657976/66586755-cc86de00-eba6-11e9-8719-ca41c4ebf905.png)
