### ISSUE TITLE
Brave Ads with the same URL as an open tab do not bring focus to the already opened tab instead opening a new tab

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#6186]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/5183
Ads with the same URL as an open tab doesn't bring focus to the already opened tab instead open a new tab

## Steps to Reproduce

   1. Open brave 0.69.129
   2. Enable rewards
   3. Set 5 ads per hour
   4. View an ad (I have received `https://www.expressvpn.com/vpn-server/us-vpn/buy ` ad)
   5. View 2nd ad
   6. I have received same ad as in step 4
   7. View 2nd ad opened a new tab instead of focusing on the already opened ad tab
  
Attached profile for further investigation
https://drive.google.com/open?id=1egDl6G1nGHeo9UgPSKVdtPitVnaEx-8c

## Actual result:

Ads with the same URL as an open tab doesn't bring focus to the already opened tab instead open a new tab

![Ad with same URL opened in new tab](https://user-images.githubusercontent.com/38657976/65721379-91c17800-e0c7-11e9-840e-0b46e75ad2c7.gif)

## Expected result:

Ads with the same URL as an open tab, bring focus to the already opened tab and do not open a new tab

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not sure
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the dev channel? Not sure
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @tmancey @jsecretan 

I have viewed both ads and stayed on ads page for more than 10secs even then `landed` confirmation is not recorded could be due to #4026 . `click ` and `view` confirmation types are recorded in confirmation.json file

![image](https://user-images.githubusercontent.com/38657976/65721896-a18d8c00-e0c8-11e9-92a1-3193f70067d0.png)

**Comment by tmancey** [comment]
@GeetaSarvadnya @anthonypkeane Chromium has not implemented functionality to allow this, so only desktop has this functionality at this time

**Comment by tmancey** [comment]
@GeetaSarvadnya Resolved with https://github.com/brave/brave-browser/issues/5195, can you please retest
