### ISSUE TITLE
Installer should not download on Windows 32bit

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#619]
## Description 

Installer should not download on Windows 32bit

## Steps to Reproduce
   1. Run setup installer on a Windows 32bit
   2. Splash screen shows downloading and installing 
   3. Throws error after trying to install

## Actual result:
Installer downloads unnecessarily setup and tries to install a 64bit version on 32bit. 

## Expected result:
Installer should warn that its not supported similar to when a 64bit setup is run on 32bit OS

## Reproduces how often: 

100%

## Brave version (about:brave info) 

0.50.14

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @RyanJarv @mbacchi

**Comment by bbondy** [comment]
Or rather it should download the right build.

**Comment by bbondy** [comment]
Moving to the backlog since if you go to brave.com/download-dev you should get he right version now.

**Comment by srirambv** [comment]
@bbondy I think this is invalid now. Now that we have both x86 and x64 setups and downloads the correct version
