### ISSUE TITLE
Lots of whitespace on www.dia.net.au

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6190]
Follow up to: https://github.com/brave/brave-browser/issues/4338
Original report: https://community.brave.com/t/page-rendering-issue/58045

## Steps to Reproduce

   1. Open `www.dia.net.au`

## Actual result:

![image](https://user-images.githubusercontent.com/34715963/65731300-72c1e680-e0c5-11e9-8f16-24c52e5c3b47.png)

Note: the white space is where ads used to be.

## Expected result:
No white space

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

cc @Brave-Matt @brave/legacy_qa

**Comment by kjozwiak** [comment]
Reproducible on `macOS 10.14.6 x64` as well using the following build:

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

<img width="1445" alt="Screen Shot 2019-09-26 at 8 09 21 PM" src="https://user-images.githubusercontent.com/2602313/65732840-a850da80-e099-11e9-9cc3-c3f99af077b5.png">

**Comment by GeetaSarvadnya** [comment]
Reproducible in `Windows 10 x64 - 0.69.129`

![image](https://user-images.githubusercontent.com/38657976/65755670-31ffb700-e131-11e9-8e89-1bed88d2edee.png)

**Comment by ryanbr** [comment]
```
fanboy@ubunutu:~/git/easylist/easylist$ grep -r 728x90.png *
easylist_general_block_dimensions.txt:728x90.png|
```

Which does block the `https://www.dia.net.au/wp-content/uploads/2018/09/DreamsIntoAction728x90.png` But not sure whats causing the whitespace issue.

**Comment by ryanbr** [comment]
Seems the site is fine, @btlechowski  can you confirm Brave Release is rendering this site okay? No obvious whitespace issues.

**Comment by ryanbr** [comment]
Re-testing before closing. Tested in Brave Release/Beta and Nightly. No more space issues @btlechowski 

Re-open ticket if I've missed something, but it seems fine now.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.7.70 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

![image](https://user-images.githubusercontent.com/34715963/77381129-5c979900-6d7d-11ea-89cc-113f9f975b53.png)
