### ISSUE TITLE
Add Search engine section in main settings screen

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#6191]
Search engine section in main settings screen will have `Standard Tab` and `Private Tab` subsection that for managing each one's search engine.
And needs to manage both independently.

**Comment by simonhong** [comment]
I'm trying to re-implement search engine configuration instead of using current implementation.
Basic idea is set proper DSE whenever normal or private tab is activated.
With this, I think we can add our dual search engine option w/o much patching.

**Comment by simonhong** [comment]
@emerick I found that we have a PR that conflict each other :)
My PR https://github.com/brave/brave-core/pull/3537 also patched `MainPrefererences.java`.
and I'm trying to add `Search engine` category into main settings screen and logic for handling dual DSE prefs. I think this work also will add conflict with your draft PR. 
How to manage this conflict?
If you're ok, can you wait my work? after that, you can implement private ntp on top of that.
WDYT? cc: @SergeyZhukovsky

**Comment by emerick** [comment]
@simonhong Sure, I can wait on that. Will check in with @SergeyZhukovsky on what I could work on in the meantime.
