### ISSUE TITLE
add ability to add extensions to autoplay whitelist (specifically WebTorrent)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6199]
## Description 

As per the conversation between @darkdh & @feross, we should add the ability to add extensions into the autoplay whitelist so we don't run into https://github.com/brave/brave-browser/issues/6195. Even with the fix from https://github.com/brave/brave-browser/issues/5471, autoplay still blocks media that has been downloaded from WebTorrent.

## Steps to Reproduce

* Go through https://github.com/brave/brave-browser/issues/5471#issue-474876804 several times and you'll notice that autoplay will eventually block the media that has been downloaded via WebTorrent.

## Actual result:

Media that's been downloaded from WebTorrent's gets blocked due to autoplay at times.

## Expected result:

Media that's been downloaded via WebTorrent shouldn't be blocked via autoplay.

## Reproduces how often: 

Using the STR, it takes a few attempts to run into the above issue.

## Brave version (brave://version info)

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A` https://github.com/brave/brave-browser/issues/5471 hasn't landed in release yet
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @rebron @darkdh @feross @brave/legacy_qa

**Comment by iefremov** [comment]
we don't have the autoplay whitelist anymore @kjozwiak ;)

**Comment by kjozwiak** [comment]
> we don't have the autoplay whitelist anymore @kjozwiak ;)

Definitely hasn't been in Brave for a while now. Thanks @iefremov, closing this off.
