### ISSUE TITLE
Decouple Android related code into OS specific files

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#6200]
This issue is created as a follow up to this PR https://github.com/brave/brave-core/pull/3499
To speed up PR merging, Android related code needs to be moved into OS specific files in a separate PR.

Also from https://github.com/brave/brave-core/pull/3499:
1. SAFETYNET_ERROR_CODE should be kSafetyNetErrorCode, due to namespace issues Chromium changed the style guide where all new code should use kFooBar style for enums
https://github.com/brave/brave-core/pull/3499/files#r329274188

**Comment by NejcZdovc** [comment]
closing as this will be done with https://github.com/brave/brave-core/pull/3918
