### ISSUE TITLE
Brave Ads history popup tooltip text needed

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6204]
## Description 
Ads History panel has tool tip text on one icon, but not others. Per discussions in slack, there was some confusion about what the UI elements did and tool tip text could help with understanding. Or if tool tip text is not desired, we should have some other way of helping users understand what the various icons do.

## Steps to Reproduce

   1. Navigate to Ads History popup.
   2. Hover over various icons (thumbs up, thumbs down, heart, etc)
   3. 

## Actual result:
Only one icon has tooltip text

## Expected result:
Tooltip text for icons, or some other way of clarifying what each icon does. This is the only one implemented at the moment:
<img width="972" alt="Screen Shot 2019-09-27 at 5 47 31 PM" src="https://user-images.githubusercontent.com/28145373/65804193-11465a00-e14f-11e9-90d9-6f6cdd13a3d2.png">

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @alexwykoff

**Comment by btlechowski** [comment]
Reproduced on Ubuntu 18.04

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

![6204](https://user-images.githubusercontent.com/34715963/66002223-7bd6fd00-e4a3-11e9-8b53-774864876769.gif)

**Comment by rebron** [comment]
cc: @alexwykoff

**Comment by tmancey** [comment]
Blocked as need Copy. I have messaged @jenn-rhim @karenkliu

**Comment by tmancey** [comment]
Closing issue as stale, however making @Miyayes aware for future consideration in new ongoing design changes
