### ISSUE TITLE
Ads History popup shows 2 entries for the same ad (even if only served once)

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6205]
## Description 
The Ads History popup shows an entry each time you View, Click, or Dismiss an Ad. So if you Click on an Ad, you have two entries: one for view, one for click. The same thing happens if you Dismiss an ad - again, you get two entries, one for view, one for dismiss.

One entry per ad should be sufficient, these extra entries just take up space/clutter the view. So if you Click on an Ad, it would make more sense to just have one entry for click, instead of the duplicate one for view - and similarly for dismiss. Basically, just show an entry for the last action completed. If you never click or dismiss an ad, then you could have the one for view.

Per discussion with @alexwykoff this is expected for now, however this could be considered for future implementation.

## Steps to Reproduce

   1. Click and dismiss some ads.
   2. View Ad History popup
   3. 

## Actual result:
<img width="954" alt="Screen Shot 2019-09-27 at 10 13 23 AM" src="https://user-images.githubusercontent.com/28145373/65804512-27a0e580-e150-11e9-98d0-612e08a50ca2.png">

## Expected result:
One entry per ad showing the last action (view, click, or dismiss - not an entry for each action)

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @alexwykoff

**Comment by btlechowski** [comment]
Reproduced on Ubuntu. Indeed this is weird. Giving thumbs up to one entry, changes the other also.

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

![6205](https://user-images.githubusercontent.com/34715963/66002411-f0aa3700-e4a3-11e9-8b5a-96ea7ba33d32.gif)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.50 Chromium: 79.0.3945.56 (Official Build) nightly (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Ubuntu 18.04 LTS

Verified test plan from the description. Verified `viewed`, `dismissed` and `clicked` states

![image](https://user-images.githubusercontent.com/34715963/70094486-e4b52f80-1622-11ea-926a-695186896828.png)
