### ISSUE TITLE
Brave Ads history popup data appears to clear out in certain cases, reopen fixes it

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6206]
## Description 
If you are viewing 'Saved' ads on the Ads History popup and you remove all saved ads, the Ads History popup data appears to be cleared out. However, if you close and reopen the popup, all data is there as expected.

## Steps to Reproduce

   1. View/click/dismiss some ads.
   2. View Ad History popup.
   3. Mark at least one ad as saved.
   4. Click on Saved.
   5. The popup switches to showing only the Saved ad in the view.
   6. Remove the ad from Saved (click on hamburger menu > remove)

## Actual result:
All data is cleared:
![adspanel-blank](https://user-images.githubusercontent.com/28145373/65805525-e3afdf80-e153-11e9-8d6d-9648ab9a7506.gif)

## Expected result:
I was expecting to be directed back to the main view and see all my ad history.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

## Miscellaneous Information:
cc @alexwykoff

**Comment by btlechowski** [comment]
Reproduced on Ubuntu. 

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/66002520-2a7b3d80-e4a4-11e9-89a3-c771264c6000.png)

**Comment by jeffbum** [comment]
@LaurenWags if this is an issue, I would like to work on this.

**Comment by LaurenWags** [comment]
Hi @jeffbum! Let me get confirmation this issue still reproduces before you start on it.

**Comment by LaurenWags** [comment]
Looks like this one no longer reproduces using the below version. Thanks for your interest @jeffbum. Please feel free to review the other open issues and see if one looks interesting to you.

```
Brave | 1.36.44 Chromium: 97.0.4692.71 (Official Build) nightly (x86_64)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | macOS Version 11.6.1 (Build 20G224)
```
