### ISSUE TITLE
brave://rewards needs to be refreshed to show 7-day Brave Ads history link

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6207]
## Description 
Sometimes the `7-day Ads History` link isn't shown on brave://rewards until you refresh the page.

## Steps to Reproduce

Scenario 1
   1. Clean profile
   2. Enable Rewards
   3. Visit brave://rewards page (can leave open or close tab)
   4. Visit some sites and generate an ad
   5. Click or Dismiss Ad
   6. Go to brave://rewards page.

Scenario 2
   1. Upgrade from previous version with Rewards enabled/ads viewed.
   2. View an ad. Click or Dismiss.
   3. Navigate to brave://rewards page

## Actual result:
7-day Ads History link is not in Ads panel. Need to refresh the page.

## Expected result:
Link should be displayed without needing to refresh.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @alexwykoff

**Comment by btlechowski** [comment]
Reproduced on Ubuntu

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

**Comment by btlechowski** [comment]
Reproduced on 

Brave | 0.72.103 Chromium: 78.0.3904.50 (Official Build) nightly (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Linux

**Comment by tmancey** [comment]
Closing issue as stale due to https://github.com/brave/brave-browser/issues/16902
