### ISSUE TITLE
Saved ads on Brave Ads history popup is not intuitive

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6208]
## Description 
When I saved an Ad from Ad History popup, I was expecting the Ad to remain in my saved list until I removed it. However, the Ad was removed after 7 days. Per discussion with @alexwykoff this could be intentional as this is only intended as a 7 day history. However, as a user, when I save something I'm not expecting it to be removed unless I say so.

Closest example I can think of at the moment, I save items to a wishlist with an online retailer. I go away and come back later. Retailer notifies me that some items are no longer available, but does not remove the items from my wishlist. 

Not sure if we need to notify users, but would be nice if we didn't pull the items out from under them.

## Steps to Reproduce

   1. View/Click/Dismiss some ads.
   2. Go into Ad History and Save some.
   3. Wait over a week (or advance your computer date over a week)
   4. Go to view Saved ads.

## Actual result:
Unable to view, Saved list is empty/not available.

## Expected result:
Expected to be able to view saved ads.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel?yes 
- Can you reproduce this issue with the dev channel?yes
- Can you reproduce this issue with the nightly channel?yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @alexwykoff

**Comment by tmancey** [comment]
Closing as raised in 2019 and 30-day ads history is already in discussion to be redesigned. cc @Miyayes
