### ISSUE TITLE
Brave Ads history link only shows on upgrade after an ad is served, previous history not displayed

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6209]
## Description 
If you upgrade from a profile with Ads viewed/clicked/dismissed, when you go to brave://rewards the `7-day Ad History` link is not available to you. It will not be shown until you are served an ad on the upgraded version.

Additionally, once you do get the link, information from previous version is not displayed in the history.

## Steps to Reproduce

   1.  Have a profile on 0.68.x with ads viewed/clicked/dismissed
   2. Upgrade to 0.69.x
   3. Navigate to brave://rewards
--->   4. No Ad History link.
   5. Browse until you are served an Ad.
   6. Go back to brave://rewards, refresh page (#6207)
   7. Click on link

## Actual result:
Only the ad(s) viewed/clicked/dismissed on the upgraded version are shown. You are not shown your ad history from the past 7 days.

## Expected result:
Previous ad history to be shown.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @alexwykoff

**Comment by tmancey** [comment]
@LaurenWags Discussions with @jsecretan and @emerick where that we would not show older history and this feature would only work for new ads due to the time it would take to add migration paths

**Comment by LaurenWags** [comment]
@tmancey thanks for the info - afaik this was not spelled out anywhere, would be good to have this documented. 

so, if this is intentional and we don't plan to change it, then I agree. 
cc @kjozwiak

**Comment by tmancey** [comment]
Blocked until the specification is updated

**Comment by tmancey** [comment]
@LaurenWags Spec updated at https://docs.google.com/document/d/1XusXB1li8I7Q-3PAk3-2BcdujwZ0Y6oD0yNvhsahZgc, see **Known Issues** section, thanks
