### ISSUE TITLE
When installing Brave on linux, you must change the mint download to xenial for it to get the repo

### ISSUE THREAD

**Issue by Xenios91** [brave/brave-browser#621]
When installing Brave, you must change the repo to Xenial for it to find it on Linux Mint

After it finds it, it downloads the following version:

Name | Version
-- | --
Brave | 0.23.39
V8 | 6.7.288.46
rev | 3ee14b0
Muon | 7.1.6
OS Release | 4.15.0-29-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.103

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/browser-laptop/issues/14799. Please post browser-laptop related issues on https://github.com/brave/browser-laptop/issues/. This repo is for brave-core only.
