### ISSUE TITLE
Crypto Wallets: text correction

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#6210]
## Description 

There is a typo in the Crypto Wallets copy, and a comma should be added. It's a bug with teeth. See below.

## Steps to Reproduce

   1. Navigate to `brave://wallet`
   2. Within: *New Local Wallet*
   3. Trade tokens **annonymously** with no trading fees.

## Actual result:

Trade tokens **annonymously** with no trading fees.

## Expected result:
Trade tokens *anonymously,* with no trading fees.

## Reproduces how often: 

100%

## Brave version (brave://version info)

```

Brave | 0.72.58 Chromium: 77.0.3865.90 (Official Build) nightly (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1809 (Build 17763.737)
JavaScript | V8 7.7.299.11
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

```

## Version/Channel Information:

- Can you reproduce this issue with the current release? unknown
- Can you reproduce this issue with the beta channel? unknown
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanml** [comment]
This is awaiting version bump for `ethereum-remote-client` https://github.com/brave/ethereum-remote-client/blob/master/brave/app/_locales/en/messages.json#L20

<img width="640" alt="Screen Shot 2019-09-30 at 5 30 50 PM" src="https://user-images.githubusercontent.com/8732757/65926049-17834300-e3a8-11e9-99c4-477f9decf7aa.png">

cc: @bbondy

**Comment by lukemulks** [comment]
Thanks!

**Comment by bbondy** [comment]
Hrm this looks like it wasn't fixed yet @ryanml in the new update. I'll just push an update now.

**Comment by bbondy** [comment]
oh I see it's just not updated in the translations.

**Comment by bbondy** [comment]
Fixed on each locale in transifex then pulled down string update to get the updates in code.
https://github.com/brave/ethereum-remote-client/commit/6b11301db2a8b308a4a9177cc8aabd56047416f4

Note to QA:
It won't appear fixed until the next deploy that I will do which should also has dark mode.

**Comment by ryanml** [comment]
This is fixed in the latest release

**Comment by kjozwiak** [comment]
@ryanml spelling looks like it was fixed but we're still missing the comma as per @lukemulks:

<img width="1000" alt="Screen Shot 2019-10-06 at 9 56 59 PM" src="https://user-images.githubusercontent.com/2602313/66280366-69363c80-e884-11e9-95a8-2a0ec3ff645d.png">

Checked using `Crypto Wallets - Version: 1.0.9` via `0.69.132 CR: 77.0.3865.90`.

**Comment by bbondy** [comment]
@lukemulks I fixed the spelling but my bad on missing the comma. I think it's ok without, but lmk if you want me to do another issue and commit for the comma.

**Comment by kjozwiak** [comment]
Going to continue verification. @lukemulks as per @bbondy, please create a new issue if we need the comma 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using https://github.com/brave/ethereum-remote-client/releases/tag/1.0.10 via the following build:

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

<img width="1066" alt="Screen Shot 2019-10-07 at 1 22 38 PM" src="https://user-images.githubusercontent.com/2602313/66334090-5a906980-e906-11e9-823e-da26f1f88bdc.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

* Verified by side loading `1.0.10` on a new profile 
![image](https://user-images.githubusercontent.com/17010094/66393815-8280db00-e9a1-11e9-8b92-b501d24bbde4.png)
