### ISSUE TITLE
How to delete/remove/clear autofill/autocomplete username/email/phone options? 

### ISSUE THREAD

**Issue by jtheletter** [brave/brave-browser#6213]
If I visit https://zoom.us/signin, and when I click the mouse pointer in the "email address" text input, or if I press the <kbd>tab</kbd> key to move my cursor there and begin typing, a list of email addresses and phone numbers appears. Some of these I no longer use. 

How do I delete them? 

They don't appear in Chrome, Safari, or Firefox, they only appear in Brave. 

They don't appear in brave://settings/autofill (investigating all options under passwords, payment methods, and addresses). 

Brave Version 0.68.142 Chromium: 77.0.3865.90 (Official Build) (64-bit)

macOS 10.14.6 (18G95) Mojave

![1](https://user-images.githubusercontent.com/49571924/65820900-7e0b3400-e1e3-11e9-994b-9f6f6e409fae.png)

**Comment by rebron** [comment]
Hi @jtheletter. Y
You can go here -> brave://settings/clearBrowserData select Advanced and select the checkbox 'Autofill Form Data'. Remember to choose your time range too.

**Comment by jtheletter** [comment]
Your suggestion would clear all valid autofill form data. I'm asking how to clear outdated data. 

Why did you close this issue?

**Comment by bsclifton** [comment]
@jtheletter you can clear single entries by using Shift + Delete 😄 Use the up/down arrows to select the outdated entry that you want to delete and then do Shift + Delete. If you're on a mac laptop, you may need to do Fn + Shift + Backspace

Let me know if this works for you! Thanks 😄 👍

**Comment by jtheletter** [comment]
I can't test it anymore because your suggestion wiped all my autofill data.

**Comment by bsclifton** [comment]
oh no! sorry about that ☹️

**Comment by rebron** [comment]
@jtheletter Sorry for closing too early. 
There are few auto form test online to use to test e.g. https://rsolomakhin.github.io/autofill/
use placeholder/fake info there and then you can try clifton's suggestion
or just go back to places you autofilled some data.

**Comment by jtheletter** [comment]
The problem recurred, and the suggestion to press <kbd>fn</kbd><kbd>shift</kbd><kbd>delete</kbd> solved it. Thank you for that. I wish the UI could suggest it somehow, and/or the data could be located and removed from Brave app prefs.
