### ISSUE TITLE
Error message not shown when creating a new uphold account for unsupported region (like NY)

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6214]
Follow up to https://github.com/brave/brave-browser/issues/5799

In https://github.com/brave/brave-browser/issues/5799 linking existing uphold account with Brave resulted with a loop. This is fixed by showing an error message. This error message is not shown when linking a new uphold account with Brave.

## Steps to Reproduce

   1. Clean profile on staging env
   2. Enable rewards
   3. Go to `brave://rewards`
   4. Click `Verify wallet`
   5. Create a new account with uphold. Use USA and New York.

## Actual result:

Error message is not shown, despite being in unsupported region

## Expected result:
Error message is shown for unsupported region

![image](https://user-images.githubusercontent.com/34715963/65823745-a125fa00-e25c-11e9-98db-25fbc6813809.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Verification passed on

Brave | 0.69.130 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @mandar-brave @rebron @NejcZdovc

**Comment by kjozwiak** [comment]
@LaurenWags mind taking a look and see if you can reproduce when you have some time? This is something we probably want fixed sooner than later if it's broken was was supposed to be released/addressed in `0.69.x`.

**Comment by LaurenWags** [comment]
I did not reproduce with

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

STR:
Clean profile
Enable Rewards
Click on Verify Wallet --> directed to Uphold
Create a new profile, choosing US and NY
Once I choose NY (before submitting the form), I see this messaging which is expected and fairly prominent:
<img width="449" alt="Screen Shot 2019-10-07 at 8 50 41 AM" src="https://user-images.githubusercontent.com/28145373/66313147-dd51fe00-e8df-11e9-9ee2-0954bd3a3d4f.png">
Then, once I submit, I am redirected back to brave://rewards and I see the expected message:
<img width="976" alt="Screen Shot 2019-10-07 at 8 54 29 AM" src="https://user-images.githubusercontent.com/28145373/66313282-23a75d00-e8e0-11e9-8c90-e62d505d7f30.png">

@btlechowski can you please try again?

**Comment by kjozwiak** [comment]
Went through the original STR outlined under https://github.com/brave/brave-browser/issues/6214#issue-499835332 and the STR @LaurenWags outlined via https://github.com/brave/brave-browser/issues/6214#issuecomment-538996459 and couldn't reproduce the issue. Used the following build:

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
--- | ---
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

#### `Selecting New York from the Uphold Signup`

![newyork1](https://user-images.githubusercontent.com/2602313/66528066-91b07780-eacc-11e9-83c1-17ca052970cb.png)

#### Leaving New York selected and submitting registration via Uphold

![newyork2](https://user-images.githubusercontent.com/2602313/66528118-c8868d80-eacc-11e9-939f-373a215cad68.png)

**Comment by NejcZdovc** [comment]
@btlechowski could you please check it again. Thank you

**Comment by btlechowski** [comment]
Not reproducible. Closing the issue.

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/66577398-98e18f00-eb79-11e9-82dd-2b9092dfb5a6.png)
