### ISSUE TITLE
twitter.com has the "Tip" button, but tweetdeck.twitter.com doesn't?

### ISSUE THREAD

**Issue by dead-claudia** [brave/brave-browser#6215]
## Description 

Twitter has the "Tip" button next to each tweet, but I don't see this on TweetDeck.

## Steps to Reproduce

   1. Go to https://tweetdeck.twitter.com while signed into Twitter.
   2. Look for "Tip" button.

## Actual result:

I'm using narrow columns for context. (It's why it's so small.)

![Screen Shot 2019-09-29 at 12 18 42 AM](https://user-images.githubusercontent.com/4483844/65826227-fe1ab380-e24e-11e9-8594-f6f9cd60016e.png)

## Expected result:

Something more in line with this:

![Screen Shot 2019-09-29 at 12 18 56 AM](https://user-images.githubusercontent.com/4483844/65826225-f22ef180-e24e-11e9-824e-913e64a4b29f.png)

## Reproduces how often: 

100%, and I noticed it instantly.

## Brave version (brave://version info)

Brave: 0.68.138 Chromium: 77.0.3865.75 (Official Build) (64-bit)
Revision: 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS: macOS Version 10.13.6 (Build 17G8030)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by emerick** [comment]
Closing as this has been superseded by https://github.com/brave/brave-browser/issues/33783

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.62.87 Chromium: 120.0.6099.35 (Official Build) nightly (x86_64)
-- | --
Revision | e0cd7777fe0c2b5f4fe9e1bc27cedd1f87eac37f
OS | macOS Version 13.6.1 (Build 22G313)
```
