### ISSUE TITLE
Offer setting to disable tab groups

### ISSUE THREAD

**Issue by Valinwolf** [brave/brave-browser#6216]
## Description 

Tab groups are annoying and I want a setting to turn them off.

## Steps to Reproduce

   1. Right click a link
   2. Select "Open in New Tab"
   3. Be annoyed at the hideous purple color on your tabs and the massive whole-tab width label

## Actual result:
![Screenshot from 2019-09-28 23-23-36](https://user-images.githubusercontent.com/5161459/65826253-27cfdc80-e247-11e9-9dcd-33ad266f888a.png)

## Expected result:
![Screenshot from 2019-09-28 23-25-21](https://user-images.githubusercontent.com/5161459/65826260-58b01180-e247-11e9-9641-100b24bd40ed.png)

## Reproduces how often: 
Every time without fail

## Brave version (brave://version info)
```
Brave	0.72.56 Chromium: 77.0.3865.90 (Official Build) unknown (64-bit)
Revision	58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS	Linux
JavaScript	V8 7.7.299.11
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Command Line	/usr/lib/brave-nightly-bin/brave --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-features=NewExtensionUpdaterService,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AudioServiceOutOfProcess,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,UnifiedConsent --flag-switches-begin --allow-insecure-localhost --extension-content-verification=enforce --load-media-router-component-extension=1 --pull-to-refresh=2 --enable-features=NewExtensionUpdaterService,WebUIDarkMode,SimplifyHttpsIndicator,CloudPrinterHandler,HistoryManipulationIntervention,IntentPicker,LazyFrameLoading,LazyImageLoading,MarkHttpAs,NativeNotifications,OmniboxMaterialDesignWeatherIcons,OmniboxRichEntitySuggestions,OmniboxSpeculativeServiceWorkerStartOnQueryInput,OmniboxSuggestionTransparencyOptions,OmniboxUIExperimentHideSteadyStateUrlPathQueryAndRef,OmniboxUIExperimentShowSuggestionFavicons,ParallelDownloading,SaveEditedPDFForm,ScrollableTabStrip,TabGroups,WebRtcHideLocalIpsWithMdns --disable-features=AudioServiceOutOfProcess,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,UnifiedConsent,AutomaticPasswordGeneration,HappinessTrackingSurveysForDesktop,WebRtcRemoteEventLog --flag-switches-end --
Executable Path	/usr/lib/brave-nightly-bin/brave
Profile Path	/home/wolf/.config/BraveSoftware/Brave-Browser/Default
Variations	2729b628-70ea8f25
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Haven't tried
- Can you reproduce this issue with the beta channel? Haven't tried
- Can you reproduce this issue with the dev channel? Haven't tried
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No (well maybe?)

**Comment by rebron** [comment]
hi @Valinwolf Field trials are off by default so I'm not sure how you got this feature turned on. You can toggle it off here though. brave://flags/#tab-groups

**Comment by bsclifton** [comment]
Woah, this is crazy

@Valinwolf you didn't enable this yourself? I'm curious how this got set?

**Comment by bsclifton** [comment]
cc: @bridiver @iefremov @jumde @darkdh  - we shouldn't be pulling field trials at run-time, but I had to admit I don't fully understand that behavior (is it possible we missed a spot with the network service refactor?). IIRC, the preferences are tied to the profile which we did change with the Syncer reworking

**Comment by iefremov** [comment]
For some reason, `TabGroups` are enabled from the command line (see `brave:://version` info) above. Hopefully, field trials are not involved.

**Comment by bsclifton** [comment]
@iefremov weird- definitely not the case for me on macOS... I checked on Linux also and I didn't see the flag there (or any variations listed on brave://version).

**Comment by Valinwolf** [comment]
@rebron Thank I'll try that when I get home
@bsclifton nope, I just updated brave-nightly-bin from AUR and it was there.
