### ISSUE TITLE
Run Brave extension packaging upload scripts in jenkins on daily schedule

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#622]
@emerick to fill in details
If wanted, @bsclifton can help with how this is done in the old jenkins.

CC @w0ts0n

**Comment by emerick** [comment]
@mbacchi We have a special repo (`brave/brave-core-crx-packager`) for packaging the extensions that we ship with Brave. This includes the component extensions AdBlock (default and regional versions), HTTPS Everywhere, and Tracking Protection, as well as our theme extensions.

The packaging process for the component extensions involves three steps:

1. Generate the DAT files used by the extension (not needed for themes)
1. Package the extension into a CRX file
1. Upload the CRX file(s) to S3

Each step is implemented as a command-line node script and the `README.md` has full details on how to run the scripts. You'll need to have the PEM keys on the build machine (for signing the CRX files). Also see the end of the `README.md` regarding configuring your credentials for S3. You will need to have read/write access to the `brave-extensions` bucket on S3.

I think that should get you started, but please let me know if you have any questions.

**Comment by mbacchi** [comment]
@emerick I have a few questions, maybe you can assist:

1. Does vault-updater need special read access to S3 brave-extensions bucket or are individual files granted read access by the world?
2. Is brave-extensions S3 bucket used for both browser-laptop and brave-browser or is this for the new brave-browser only?
3. Intention is to create an S3 bucket for staging, do I need to copy all files from production brave-extensions bucket over? (is the vault-updater process accumulative?)
4. Does this need to run on an AWS instance or can it be a docker container? Do you know how resource intensive this build process is and how long it takes today?
5. I would like to use IAM roles vs. access/secret keys exposed as environment variables for access to the S3 bucket. Is there any opposition to changing that methodology if it requires no manual intervention (i.e. done through terraform configuration?)

**Comment by emerick** [comment]
> Does vault-updater need special read access to S3 brave-extensions bucket or are individual files granted read access by the world?

I believe that vault-updater does have special access to that bucket, see:
https://github.com/brave/vault-updater/blob/master/src/controllers/extensions.js#L4

> Is brave-extensions S3 bucket used for both browser-laptop and brave-browser or is this for the new brave-browser only?

My understanding is the S3 bucket is currently used by both, but @aekeus can probably tell us definitively. Vault-updater has a manifest file which tells it which extensions are stored in S3 and then brave-browser makes requests for only a small subset of those at the moment.

https://github.com/brave/vault-updater/blob/master/data/stable/extensions/extensionManifest.json

> Intention is to create an S3 bucket for staging, do I need to copy all files from production brave-extensions bucket over? (is the vault-updater process accumulative?)

Yes, vault-updater has more extensions/versions over time from what I've gathered.

> Does this need to run on an AWS instance or can it be a docker container? Do you know how resource intensive this build process is and how long it takes today?

I would think a Docker container is fine. Regarding resource intensity, it's pretty minimal. The node scripts build a few C++ modules (mostly for tracking protection, from what I recall) and then generate and upload the CRX files. It's been a while since I've run the whole process, but it would probably take no more than 10 minutes (if that) to do everything.

> I would like to use IAM roles vs. access/secret keys exposed as environment variables for access to the S3 bucket. Is there any opposition to changing that methodology if it requires no manual intervention (i.e. done through terraform configuration?)

No opposition from me. @aekeus?

**Comment by bbondy** [comment]
Here's what has to be run to update on schedule, the parameters need to be adjusted accordingly:

If there is any errors, it should fail the whole Jenkins job.
Each command will have a 0 return code on success.


```
npm run data-files-ad-block
npm run data-files-https-everywhere
npm run data-files-tracking-protection

npm run package-ad-block -- --binary "/Applications/Google\\ Chrome\\ Canary.app/Contents/MacOS/Google\\ Chrome\\ Canary" --keys-directory /Users/brianbondy/Desktop/key --set-version 1.0.3
npm run package-https-everywhere -- --binary "/Applications/Google\\ Chrome\\ Canary.app/Contents/MacOS/Google\\ Chrome\\ Canary" --key-file  /Users/brianbondy/Desktop/key/https-everywhere-updater.pem --set-version 1.0.1
npm run package-tracking-protection -- --binary "/Applications/Google\\ Chrome\\ Canary.app/Contents/MacOS/Google\\ Chrome\\ Canary" --key-file  /Users/brianbondy/Desktop/key/tracking-protection-updater.pem --set-version 1.0.1
npm run package-themes -- --binary "/Applications/Google\\ Chrome\\ Canary.app/Contents/MacOS/Google\\ Chrome\\ Canary" --keys-directory /Users/brianbondy/Desktop/key --set-version 1.0.0
npm run package-tor-client -- --binary "/Applications/Google\\ Chrome\\ Canary.app/Contents/MacOS/Google\\ Chrome\\ Canary" --keys-directory /Users/brianbondy/Desktop/key --set-version 1.0.0

npm run upload-ad-block -- --crx-directory ./build/ad-block-updater/ --vault-updater-path /Users/brianbondy/projects/brave/vault-updater/data/
npm run upload-https-everywhere --  --crx-directory ./build/https-everywhere-updater/ --vault-updater-path /Users/brianbondy/projects/brave/vault-updater/data/
npm run upload-tracking-protection   -- --crx-directory ./build/tracking-protection-updater/ --vault-updater-path /Users/brianbondy/projects/brave/vault-updater/data/
npm run upload-themes --  --crx-directory ./build/themes/ --vault-updater-path /Users/brianbondy/projects/brave/vault-updater/data/
npm run upload-tor-client -- --crx-directory ./build/tor-client-updater/ --vault-updater-path /Users/brianbondy/projects/brave/vault-updater/data/
```

**Comment by bbondy** [comment]
cc @mbacchi

**Comment by bbondy** [comment]
We should probably fix https://github.com/brave/brave-core-crx-packager/issues/20 before we automate this in devops, otherwise we'd only be re-generating the same version each time.

**Comment by bbondy** [comment]
Note that you will need to have go-update s3 and dynamodb privileges in an `AWS_PROFILE`, in the examples below I have it in an AWS_PROFILE named `extensions`

## Ad Block data files extension:

I need this to be able to kick off manually and on demand.
Please clear cache as well for the crx files so they are served right away after running.
Fail on non zero return codes for each command.

```
npm run data-files-ad-block

AWS_PROFILE=extensions npm run package-ad-block -- --binary "/Applications/Google\\ Chrome\\ Canary.app/Contents/MacOS/Google\\ Chrome\\ Canary" --keys-directory /Users/brianbondy/Desktop/key

AWS_PROFILE=extensions npm run upload-ad-block -- --crx-directory ./build/ad-block-updater/ --vault-updater-path /Users/brianbondy/projects/brave/vault-updater/data/
```


## HTTPS Everywhere data files extension:

I need this to be able to kick off manually only.
Please clear cache as well for the crx files so they are served right away after running.
Fail on non zero return codes for each command.

```
npm run data-files-https-everywhere

AWS_PROFILE=extensions npm run package-https-everywhere -- --binary "/Applications/Google\\ Chrome\\ Canary.app/Contents/MacOS/Google\\ Chrome\\ Canary" --key-file  /Users/brianbondy/Desktop/key/https-everywhere-updater.pem 

AWS_PROFILE=extensions npm run upload-https-everywhere --  --crx-directory ./build/https-everywhere-updater/ --vault-updater-path /Users/brianbondy/projects/brave/vault-updater/data/
```

## Tracking protection data files extension:

I need this to be able to kick off manually only.
Please clear cache as well for the crx files so they are served right away after running.
Fail on non zero return codes for each command.

```
npm run data-files-tracking-protection

AWS_PROFILE=extensions npm run package-tracking-protection -- --binary "/Applications/Google\\ Chrome\\ Canary.app/Contents/MacOS/Google\\ Chrome\\ Canary" --key-file  /Users/brianbondy/Desktop/key/tracking-protection-updater.pem 

AWS_PROFILE=extensions npm run upload-tracking-protection   -- --crx-directory ./build/tracking-protection-updater/ --vault-updater-path /Users/brianbondy/projects/brave/vault-updater/data/
```

## Tor extension:

I need this to be able to kick off manually only.
Please clear cache as well for the crx files so they are served right away after running.
Fail on non zero return codes for each command.

```
AWS_PROFILE=extensions npm run package-tor-client -- --binary "/Applications/Google\\ Chrome\\ Canary.app/Contents/MacOS/Google\\ Chrome\\ Canary" --keys-directory /Users/brianbondy/Desktop/key 

AWS_PROFILE=extensions npm run upload-tor-client -- --crx-directory ./build/tor-client-updater/ --vault-updater-path /Users/brianbondy/projects/brave/vault-updater/data/
```



## Themes extensions:

I need this to be able to kick off manually only.
Please clear cache as well for the crx files so they are served right away after running.
Fail on non zero return codes for each command.

```
AWS_PROFILE=extensions npm run package-themes -- --binary "/Applications/Google\\ Chrome\\ Canary.app/Contents/MacOS/Google\\ Chrome\\ Canary" --keys-directory /Users/brianbondy/Desktop/key 

AWS_PROFILE=extensions npm run upload-themes --  --crx-directory ./build/themes/ --vault-updater-path /Users/brianbondy/projects/brave/vault-updater/data/
```

**Comment by mihaiplesa** [comment]
Added 5 Jenkins jobs as requested, with ad block running daily, everything looks good so far so feel free to close when desired.

**Comment by bbondy** [comment]
Closing, verified I get the new version, verified that logs appear on #build-bot in Slack, and verified that I can run the jobs now.
