### ISSUE TITLE
Consider renaming "good first bug" label to "good first issue"

### ISSUE THREAD

**Issue by humphd** [brave/brave-browser#6220]
I notice that you have [good first bug](https://github.com/brave/brave-browser/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+bug%22) issues, which is great.  I think you should consider renaming this to "good first issue," since GitHub has a bunch of automatic discovery that happens when you use their preferred label for such issues.

**Comment by bsclifton** [comment]
@humphd really good suggestion! 😄 Done! 
https://github.com/brave/brave-browser/labels/good%20first%20issue
