### ISSUE TITLE
Cannot tweet after inline tipping on reddit

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6223]
Cannot tweet after inline tipping on reddit. This is recent regression.

## Steps to Reproduce

   1. Clean profile (used staging env)
   2. Enable rewards
   3. Open `https://www.reddit.com/user/jsadler-brave`
   4. Use inline Tip button on the page
   5. Tweet about the tip   

Note: first noticed by @masparrow when working on https://github.com/brave/brave-browser/issues/5516

## Actual result:

Nothing happens, the page to tweet is not shown

## Expected result:
 the page to tweet is shown
![image](https://user-images.githubusercontent.com/34715963/65875434-8dc37d80-e387-11e9-9a1c-a242adcae0f4.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

**Reproduced on**

Brave | 0.69.130 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Not reproducible on Twitter(inline tipping), youtube(https://www.youtube.com/user/JJDSampson) and regular page
This is not linked to publisher being connected as https://www.youtube.com/user/JJDSampson works fine.

**Not reproducible on**

Brave | 0.68.142 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 7 Service Pack 1 (Build 7601.24519)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

cc @brave/legacy_qa @NejcZdovc

**Comment by LaurenWags** [comment]
Reproduces with

Brave | 0.69.130 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

But did not reproduce with

Brave | 0.68.142 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.72.110 Chromium: 78.0.3904.70 (Official Build) dev (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

Verified STR from the description. Verified new and old reddit. Tested on staging env.

![image](https://user-images.githubusercontent.com/34715963/67797727-94c2d600-fa82-11e9-9e8b-85db1f7383db.png)
![image](https://user-images.githubusercontent.com/34715963/67797849-d6ec1780-fa82-11e9-8489-80c7cf2b016f.png)
