### ISSUE TITLE
sometimes drop down options from Verify Wallet are not displayed - follow up to 5772

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6224]
## Description 
Sometimes the expected outcome of #5772 is not displayed for me (https://github.com/brave/brave-browser/issues/5772#issuecomment-526888626) on a connected (not KYC'd) wallet.

Others (@GeetaSarvadnya @kjozwiak ) have not been able to reproduce but this occurs about half the time for me. First noticed with 0.69.129, but also occurs with 0.69.130.

## Steps to Reproduce

1. Clean profile 0.69.x
2. Enable Rewards.
3. Click on Verify wallet from somewhere, then proceed to uphold.
4. Create an account, don't complete KYC. Make sure you click on the link in the confirm email from Uphold as well.
5. Go back to Rewards Settings.
6. Clicking on 'Verify Wallet' button doesn't give you the option to disconnect, just directs you to Uphold Dashboard.

## Actual result:

![5772-followup](https://user-images.githubusercontent.com/28145373/65880749-4aa1e400-e360-11e9-9275-804284ad5269.gif)

Note - UI around Verify wallet doesn't change either, so maybe my wallet isn't connecting correctly?

## Expected result:

Options when clicking on Verify Wallet like in https://github.com/brave/brave-browser/issues/5772#issuecomment-526888626

## Reproduces how often: 
intermittent, seems like about half the time.

## Brave version (brave://version info)

Brave | 0.69.130 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 0.68.x no, 0.69.x yes
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

## Miscellaneous Information:
cc @mandar-brave @NejcZdovc @brave/legacy_qa

**Comment by NejcZdovc** [comment]
@LaurenWags is this still a problem?

**Comment by LaurenWags** [comment]
haven't seen this in a long time. closing for now, will re-open if I experience it again.
