### ISSUE TITLE
Ads panel appears to be missing after upgrade in some cases but refresh of page fixes it

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6226]
## Description 

Sometimes after upgrade if you have Ads viewed/estimated BAT on your Ads panel, the panel isn't displayed on brave://rewards page. However, a refresh of the page fixes this.

This is not the same issue as #6148 but could be related?

## Steps to Reproduce

1. Have a profile where you've viewed ads with 0.68.x (so ads are ON). Leave brave://rewards page open.
2. Upgrade to 0.69.x
3. Navigate to brave://rewards page

## Actual result:
No Ads panel is displayed. Refresh of the page fixes it though.

## Expected result:
Ads panel should be displayed. Should not need to refresh page to see Ads panel.

## Reproduces how often: 
easy

## Brave version (brave://version info)
Originally encountered with 0.69.129, but also reproduces with

Brave | 0.69.130 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 0.68.x no, 0.69.x yes
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @brave/legacy_qa @NejcZdovc @rebron @ryanml

**Comment by NejcZdovc** [comment]
@LaurenWags I would say it's the same as #6148. Let's verify it when it lands in 69

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified STR from description.
