### ISSUE TITLE
Change Auto-Contribute to use "up to" budgeting, and to only contribute to verified content creators

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#6228]
spec can be found in #spec

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.70.118 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Windows 10 OS Version 1803 (Build 17134.1006)



- Verified the test plan from https://github.com/brave/brave-core/pull/3564
- Verified “Up to” text added to the left of the selected BAT amount for Monthly Payment dropdown items in Auto-Contribute panel
- Verified auto-contribution happens only for verified pubs when verified and non-verified sites are added into a-c table, also non-verified pubs will not be listed in pending contribution list anymore
- Verified auto-contributions will not happen when only non-verified creators are added into a-c table, wallet balance will not change and non-verified pubs will not be listed in pending contribution list anymore
- Verified the text change “The Brave Verified sites you visit will receive your contributions automatically, based on your attention as measured by Brave” in the Auto-Contribution panel
- Verified few label changes are not yet done. Encountered #6483
- Verified that one-time tip and recurring monthly tip for non-verified pubs still displayed in the pending contribution list table 
- Verified that the upgraded profile Pending contribution list has Auto contribute entry for non-verified pubs
