### ISSUE TITLE
Welcome screen shows escaping (`\`) in string

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#623]
## Description 

Escaping used in string is actually shown

## Steps to Reproduce

   1.  Fresh install of Brave Core
   2. Launch
   3. See welcome screen

## Actual result:
`Brave is so much more than a browser. Let\'s show you how to make the most of it`

![screen shot 2018-07-22 at 12 49 02 am](https://user-images.githubusercontent.com/4733304/43043465-2a712434-8d49-11e8-8945-7f37ece66bb9.png)

## Expected result:
`Brave is so much more than a browser. Let's show you how to make the most of it`

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bbondy** [comment]
Oops, re-opening, this is not fixed yet.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows
