### ISSUE TITLE
Please fix the file permissions in the brave-keyring Debian package

### ISSUE THREAD

**Issue by morfikov** [brave/brave-browser#6230]
When I installed `brave-browser` from the `https://brave-browser-apt-release.s3.brave.com/` APT repository on my Debian system, it pulled the `brave-keyring` package as a dependency. There's `control.tar.gz` and `data.tar.xz` archives in this package (as usual), and all files in the archives are owned by `bkero/bkero`. This has some implications when installing this kind of a package. Basically `apt`/`aptitude`/`apt-get` call `dpkg-deb`, which (because of the wrong file permissions) wants couple of additional [capabilities](http://man7.org/linux/man-pages/man7/capabilities.7.html) (`chown`, `fowner`, `fsetid`). To avoid this, all the files in the `.deb` package have to be owned by root/root. Please fix this, thanks.

**Comment by bsclifton** [comment]
cc: @fmarier @mbacchi

**Comment by fmarier** [comment]
I guess there's something wrong with the [call to `dpkg-deb --build`](https://github.com/brave/brave-release/blob/093b3c15bb5096b608abeaea11b32c2de6566657/deb/make-dists.sh#L5).

**Comment by fmarier** [comment]
@morfikov We think that we may have fixed this, but we're having problems testing it.

I tried inspecting the archive:
```
$ ar tv brave-keyring_1.3_all.deb 
rw-r--r-- 0/0      4 Jun 26 11:25 2019 debian-binary
rw-r--r-- 0/0    488 Jun 26 11:25 2019 control.tar.gz
rw-r--r-- 0/0   2720 Jun 26 11:25 2019 data.tar.xz
```
or extracting it:
```
$ ar x brave-keyring_1.3_all.deb 
$ ls -lh
total 16K
-rw-r--r-- 1 francois francois 3.4K Oct 18 10:28 brave-keyring_1.3_all.deb
-rw-r--r-- 1 francois francois  488 Oct 18 10:29 control.tar.gz
-rw-r--r-- 1 francois francois 2.7K Oct 18 10:29 data.tar.xz
-rw-r--r-- 1 francois francois    4 Oct 18 10:29 debian-binary
```

but I'm not seeing the `bkero`s you're seeing.

**Comment by fmarier** [comment]
Never mind, @bkero found it:
```
$ tar tvf control.tar.gz
drwxr-xr-x bkero/bkero       0 2019-06-26 10:51 ./
-rw-r--r-- bkero/bkero       0 2019-04-09 15:50 ./conffiles
-rw-r--r-- bkero/bkero     183 2019-06-26 09:08 ./control
-rwxr-xr-x bkero/bkero     278 2019-04-17 11:10 ./postinst
```

**Comment by morfikov** [comment]
Also, you don't need `chown` and `chmod` (which caused the issue) in the postinst script now:

```
chown root:root /etc/apt/trusted.gpg.d/brave-browser-release.gpg
chmod 0644 /etc/apt/trusted.gpg.d/brave-browser-release.gpg
```

**Comment by bkero** [comment]
Thanks for bringing this to our attention. I've removed the `chown` and `chmod` operations from the postinst, as well as removed the `.gitignore`. Expect a new release of the keyring package coming soon.

**Comment by fmarier** [comment]
The new keyring package with this fix was released last week.

**Comment by morfikov** [comment]
Yes, it works well now.
