### ISSUE TITLE
improving the "web3" prompt/modal to include more context/info

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6233]
## Description 

We should eventually add more information in the modal/prompt that is displayed when visiting a website that supports `web3`. A good example is the `Widevine` modal/prompt that includes context. Users that don't understand what `Crypto Wallet` means might be confused on why a website is requesting an extension to be installed.

I wouldn't consider this a `0.69.x` blocker but would be a nice to have eventually 👍 

## Steps to Reproduce

   1. visit https://www.cryptokitties.co in a new profile (or any `web3` website)

## Actual result:

<img width="1038" alt="Screen Shot 2019-09-30 at 1 57 27 PM" src="https://user-images.githubusercontent.com/2602313/65904975-a6369680-e38d-11e9-92b6-e134a17b188f.png">

## Expected result:

We should probably add more information/context similar to `Widevine` in the DApp modal/prompt regarding `web3` integration. Example of `Widevine`:

<img width="483" alt="Screen Shot 2019-09-30 at 2 19 35 PM" src="https://user-images.githubusercontent.com/2602313/65904899-6bccf980-e38d-11e9-8e81-f20daa9112e1.png">

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A` (not released)
- Can you reproduce this issue with the beta channel? `N/A`
- Can you reproduce this issue with the dev channel? `N/A`
- Can you reproduce this issue with the nightly channel? `N/A`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

## Miscellaneous Information:

CCing @bbondy @mbacchi @ryanml @brave/legacy_qa

**Comment by bbondy** [comment]
I think we can close this now with the improvements from the infobar. I don't think we're going to add another alternate UI from that.   Let me know if you disagree.
