### ISSUE TITLE
Keep Getting Logged Out Of Sessions

### ISSUE THREAD

**Issue by timbeiko** [brave/brave-browser#6234]
## Description 
Over the past few days, Brave has started logging me out of my sessions across websites almost every time I visit again. I've used Brave for almost a year now and this did not happen. I started noticing it last week, and today it has gotten even worse. 

## Steps to Reproduce

   1. Log into a website using Brave 
   2. Leave website/close Brave/etc.
   3. Go back to website, logged out. 

## Actual result:
Logged out of websites and applications using a browser window to log in (i.e. Gitter using "Log in with Github").

## Expected result:
Stays logged into my sessions. 

## Reproduces how often: 
No steps to reproduce, except going back to a previously logged-in website. 

## Brave version (brave://version info)

Brave | 0.68.142 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)
JavaScript | V8 7.7.299.11
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser -psn_0_65552 --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extensions-install-verification=enforce_strict --enable-features=NewExtensionUpdaterService,SimplifyHttpsIndicator,WebUIDarkMode --disable-features=AudioServiceOutOfProcess,TranslateUI,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,UnifiedConsent --flag-switches-begin --flag-switches-end --restore-last-session
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/timbeiko/Library/Application Support/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:
No idea. 
- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No. 
- Does the issue resolve itself when disabling Brave Rewards? Don't know. 
- Is the issue reproducible on the latest version of Chrome? Don't know.

## Miscellaneous Information:

**Comment by rebron** [comment]
@timbeiko Can you provide just a few websites we can try out? The latest version of the browser 69.132, in brave://settings/help Would be helpful to us if you can upgrade to the latest version first.

**Comment by bsclifton** [comment]
Without examples, I don't think we can troubleshoot

There aren't any known issues. I would suggest checking if you have clearing cookies on exit enabled
