### ISSUE TITLE
web3 prompt/modal appearing for sites that don't have web3 integrated

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6238]
## Description 

Some websites are triggering the `Crypto Wallets` prompt/modal even though they don't have `web3` integrated.

## Steps to Reproduce

   1. launch `0.69.129 Chromium: 77.0.3865.90`
   2. visit wnyc.org and you'll receive a `web3` modal/prompt

## Actual result:

![web3](https://user-images.githubusercontent.com/2602313/65907993-712d4280-e393-11e9-97c3-3bd1a10dafd3.gif)

## Expected result:

The `web3` prompt/modal shouldn't be appearing on websites that haven't integrated `web3`

## Reproduces how often: 

100% reproducible when using the above STR on a release build.

## Brave version (brave://version info)

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

Brave | 0.72.60 Chromium: 77.0.3865.90 (Official Build) nightly (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A` (feature not released yet)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

## Miscellaneous Information:

CCing @bbondy @ryanml @mbacchi @brave/legacy_qa

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

* visited `https://www.wnyc.org` and ensured the `Crypto Wallets` prompt wasn't visible
* visited several popular websites that are not DApps and ensured the prompt wasn't displayed
* visited `https://www.cryptokitties.co` and ensured the `Crypto Wallets` prompt is being displayed
* visited `https://metamask.io` and ensured the `Crypto Wallets` prompt is being displayed
* visited `https://dozerbird.io` and ensured the `Crypto Wallets` prompt is being displayed
* ensured that selecting `Allow` opens `brave://wallet`
* ensured that selecting `Block` dismisses the prompt and doesn't open `brave://wallet`

**Comment by jonathansampson** [comment]
This issue doesn't appear to be resolved in 0.69.132 according to [some user reports](https://twitter.com/cryptoM1nd/status/1179859379761418244).
