### ISSUE TITLE
Refactor reset state business logic to be part of the Brave ads service

### ISSUE THREAD

**Issue by gdregalo** [brave/brave-browser#6239]
## Description 

Issue about `Reset state` logic.
PR:  https://github.com/brave/brave-core/pull/3499
Logic to reset state should be part of bat-native-ads so that same business logic can be used cross-platform, i.e. iOS, Android and desktop
https://github.com/brave/brave-core/pull/3499#discussion_r327736763

Please also update reset logic for Rewards service:
https://github.com/brave/brave-core/pull/3499/files#r330222132

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by tmancey** [comment]
Closing issue as resolved by https://github.com/brave/brave-browser/issues/10064
