### ISSUE TITLE
When choosing to save password, passwords are not being saved

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#624]
## Description 
Saving passwords with the built in manager does not work. Possibly related to https://github.com/brave/brave-browser/issues/563

Found looking to see if https://github.com/brave/browser-laptop/issues/1857 is an issue in Brave Core

## Steps to Reproduce

   1. Visit a site which requires credentials to login (ex: https://trac.torproject.org/projects/tor/login)
   2. Login
   3. Verify you see prompt to save
   4. Click `Save` (you may need to dismiss the confirmation `Sign-In` modal by clicking the `X` in top right)
   5. Visit `chrome://settings/passwords` OR click the key in the URL bar
   6. Notice that no password was actually saved

## Actual result:

![password-not-saving](https://user-images.githubusercontent.com/4733304/43043619-6e88ab8a-8d4c-11e8-9ad5-d846ab4d6b18.gif)

## Expected result:
Passwords should be saved

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Works for me on Windows

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/4061

I haven't experienced this in a very long time personally
