### ISSUE TITLE
brave silent setup is not silent

### ISSUE THREAD

**Issue by NZ-HIPS** [brave/brave-browser#6240]
## Description 
A silent setup is hardly silent as it results in starting the brave browser at the end of the installation process. This hinders some applications, like unattended deployment, as the synchronous installation process can not proceed until a user closes the window.

## Steps to Reproduce
1. Download a silent installer from https://github.com/brave/brave-browser/releases
2. (Silently) Install
3. Observe browser being executed at the end of silent installation

## Actual result:
<img src="https://i.ibb.co/ckGzXWh/bug.png" alt="bug" border="0">
(brave silent setup doesn't return to command line)

## Expected result:
Would install, then return to the command line.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 0.72.60 Chromium: 77.0.3865.90 (Official Build) nightly (64-bit)
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1809 (Build 17763.1)

## Version/Channel Information:
Occurs at least in both the release and nightly channels.

- Can you reproduce this issue with the current release?
Yes. (v0.68.142)

- Can you reproduce this issue with the beta channel?
Didn't try.

- Can you reproduce this issue with the dev channel?
Didn't try.

- Can you reproduce this issue with the nightly channel?
Yes. (v0.72.60)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
N/A
- Does the issue resolve itself when disabling Brave Rewards?
N/A
- Is the issue reproducible on the latest version of Chrome? 
No (using msi with /q switch).

**Comment by bsclifton** [comment]
@mbacchi we did have a version that doesn't auto-launch (which we used for the Muon upgrade). We don't still package that though, do we?

**Comment by cascadeth** [comment]
Saw a comment on [the community post](https://community.brave.com/t/msi-file-for-deployment-by-gpo-sccm-availible-or-any-way-to-make-this-possible/102210) about if requesting an MSI installer.  +1'ing that.

**Comment by runout-at** [comment]
any news on that?

we want to deploy brave with ansible on windows.

**Comment by HorNet505** [comment]
google for the "BraveBrowserStandaloneSilentBetaSetup.exe"

**Comment by mbacchi** [comment]
I've opened issue https://github.com/brave/brave-browser/issues/9418 to provide an MSI package for unattended installation. I'll leave this issue open for the moment, to track the initial request.

**Comment by haavarstein** [comment]
Any updates? Looking forward to the MSI file

**Comment by kjozwiak** [comment]
CCing @mihaiplesa ☝️

**Comment by Apfelwurm** [comment]
Hi, i would deploy all my friends machines with Brave in the future if someday a silent installation is possible! This would be really cool!

**Comment by mherrmann** [comment]
The problem still occurs with Nightly v1.24.17. That is, `BraveBrowserStandaloneNightlySetup.exe` launches a browser window.

**Comment by mherrmann** [comment]
There also do not seem to be command-line arguments that can be passed to `BraveBrowserStandaloneSilentNightlySetup.exe` to prevent the browser window from opening. In particular, `/silent`, `/silent /install` and `--silent` all produce errors.

The reason for this seems to be the following: The silent standalone installer passes its command line arguments on to Brave's auto-update framework Omaha. Specifically: Without any arguments, the installer invokes `BraveUpdate.exe /silent /install "appguid={Brave's UID}&..."`. With arguments, it passes those into the command line instead of /silent /install. Additionally, it passes &silent. So `/foo` invokes `BraveUpdate.exe /foo "appguid=...&silent&..."`. BraveUpdate.exe is Omaha's binary that installs and uninstalls apps and Omaha. I don't see an easy way how this could be used to suppress the opening of a window. My suspicion is that it's not Omaha that opens the window but Brave's own installer.

People looking for a workaround can follow the instructions [here](https://silentinstallhq.com/brave-browser-silent-install-how-to-guide/). They happen to work at the moment, but are currently not officially supported. Also, this way of installing Brave does not set up Brave's auto-update mechanism.

**Comment by bsclifton** [comment]
We have manually worked around this in the past - basically when tagging the installer, we can include the silent attribute. There is a launch after install attribute - maybe @mihaiplesa still has a link to the patch we used. The only use-case we had for this originally was for Muon when migrating to Brave Core (we wanted to install browser without launching; as first launch did the import). I'll dig through notes and see what I can find

Having a proper silent install would be great until we're able to look at MSI (captured with https://github.com/brave/brave-browser/issues/9418)

**Comment by bsclifton** [comment]
@mherrmann found it - here's a PR (example) that we used to prevent it from launching. It would be great if the silent installer was created using this:
https://github.com/brave/omaha/pull/13/files

**Comment by mherrmann** [comment]
@bsclifton my PRs above fix StandaloneSilentSetup.exe but not SilentSetup.exe. The technique I'm using won't work to fix SilentSetup.exe and I don't see an easy way to fix SilentSetup.exe. I'm wondering if SilentSetup.exe is required at all if StandaloneSilentSetup.exe is available. Can I pose the radical question and ask whether we can simply no longer offer SilentSetup.exe?

Some technical detail: The difference between SilentSetup.exe and StandaloneSilentSetup.exe is that the former is just a small 1 MB online installer that downloads the latest version of Brave from the update server. The reason why my technique won't work is that the _update server_ determines whether the installer launches a browser window. Specifically, the server would have to respond "invoke the internal Brave installer with argument --do-not-launch-chrome". But the update server doesn't know whether the installation is to be performed silently. So it can either never open a browser window (also for normal, non-silent installations), or always. The reason why StandaloneSilentSetup works is that this binary is created by essentially hard-coding a server response. In this hard-coded response, it is possible to supply `--do-not-launch-chrome`.

I can only think of hacky not-nice workarounds to prevent SilentSetup from opening a browser window. Hence my question whether this installer is really needed :-)

**Comment by mherrmann** [comment]
Actually, there might be a way to prevent SilentSetup.exe from opening a browser window: It is possible to encode an `installdataindex` in SilentSetup.exe that is then sent by Omaha to the server. This lets the server return a `master_preferences` file, which is supposed to support a property `"skip_first_run_ui" : true` that suppresses the browser window. I'd be happy to look into this approach, but am still wondering whether it is worth the effort.

**Comment by bsclifton** [comment]
I think removing `SilentSetup.exe` would be just fine 😄  Most folks wanting a silent install (ex: MSI) want to distribute / install the package themselves so they can avoid multiple machines fetching the same data / eating up network

**Comment by mihaiplesa** [comment]
Yes, les's look into a proper silent installer until we have the bandwidth to look into MSI (or till next Omaha protocol version comes out).

**Comment by mherrmann** [comment]
Hey @mihaiplesa, I'm afraid I don't understand your comment in the context of this discussion. @bsclifton and I were talking about getting rid of `SilentSetup.exe` (1 MB online installer, opens a browser window) because after my PR above the existing `StandaloneSilentSetup.exe` will be truly silent. Do you agree that it's okay to remove `SilentSetup.exe` because people can use `StandaloneSilentSetup.exe` instead?

**Comment by mihaiplesa** [comment]
Re-reading again now it makes sense to remove the silent online installer and fix the offline one, thanks.

**Comment by sachinmarathe** [comment]
Excuse me, but the installation is not silent yet. tried this on Windows 10 by double clicking 1.22.72.exe, as well as using command line. A new page still pops up at the end. furthermore if it is included in the windows 10 installation iso, the resulting brave installation does not work. it does not launch, and needs to be reinstalled.

**Comment by mherrmann** [comment]
@sachinmarathe I think this fix is first included with 1.25.x nightly snapshots. What you wrote seems to indicate you're using 1.22. Or am I missing something?

**Comment by sachinmarathe** [comment]
no you are not missing anything. i guess i missed some:) i thought this was merged with the stable version as well. i did try nightly in the meantime. works flawlessly.

**Comment by mherrmann** [comment]
Happy to hear it's working! :)

**Comment by cahalpin** [comment]
Will the truly silent install be included in a stable release soon? Wanting to deploy Brave silently across my organization but do not want to use a Nightly release in production environment.

**Comment by mihaiplesa** [comment]
@cahalpin it will be in the next beta and dev releases and naturally uplifted to stable channel in less that 3 weeks.

**Comment by cahalpin** [comment]
Great, thanks!

**Comment by bsclifton** [comment]
Nice work @mherrmann 😄👍

**Comment by mherrmann** [comment]
Thanks @bsclifton! :smile:

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

<!--StartFragment-->
Brave | 1.25.66 Chromium: 91.0.4472.70&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | fe095368270a32c92959403754bf6fd357dd9953-refs/branch-heads/4472@{#1172}
OS | Windows&nbsp;10 OS Version 2004 (Build 19041.985)

<!--EndFragment-->


```
- Verified the test plan from https://github.com/brave/brave-core/pull/8364

Ensured stand-alone installers (BraveBrowserStandaloneSetup.exe) are working as expected 
Ensured stand-alone installers (BraveBrowserStandaloneSilentSetup.exe) are working as expected

**Comment by andrewww** [comment]
As of today and the latest stable build:
https://github.com/brave/brave-browser/releases/download/v1.29.77/BraveBrowserStandaloneSilentSetup.exe

the silent installer opens Brave at the end of an otherwise silent install.

**Comment by mherrmann** [comment]
@andrewww I cannot reproduce this behavior. What I did:

 1. Install Brave 1.29.77 with the standalone silent installer. As expected, Brave is installed silently and I can afterwards launch it on my system.
 2. Run the installer again. As expected, Brave does not open. It's still on my system and I can launch it as usual.

**Comment by VioletionChaos** [comment]
Please an msi/msix release of brave, that would be awesome.

**Comment by Fchen48** [comment]
2023 and still no MSI available???

**Comment by BitshapedRob** [comment]
2024 and still no MSI available?

**Comment by PC-SPEZIALIST** [comment]
2025 and still no MSI available?

**Comment by MartinSusky** [comment]
2026 and still no MSI available?

**Comment by PC-SPEZIALIST** [comment]
> 2026 and still no MSI available?

Did you try [WinGet](https://winstall.app/apps/Brave.Brave) or [Chocolatey](https://community.chocolatey.org/packages/brave/), @MartinSusky?
