### ISSUE TITLE
Brave Shields not disabling under local html files

### ISSUE THREAD

**Issue by jefetienne** [brave/brave-browser#6243]
## Description 

After developing a web application offline using localStorage, I got an error from the console, disallowing my web app to read/write to localStorage, but then after going to Brave Settings and setting Cookie Control from "block 3rd party cookies" to  "Allow all Cookies", my program started working.

I was unable to use the Brave Shields icon in the URL bar to allow all cookies because the icon was disabled, most likely because I was viewing an html file locally on my computer. I believe the disabled icon was supposed to mean that the shields were disabled, even though they actually were not.

## Steps to Reproduce

   1. Open Brave Browser
   2. Go to brave://settings and set Brave Shields Defaults -> Cookie Control to "Block 3rd Party Cookies"
   3. Create an html file locally with this script using localStorage:

```html
<!doctype HTML>
<html>
	<head>
		<title>Test</title>
		<script>
			if (typeof(Storage) !== "undefined") {
	  			localStorage.setItem("hello", "world");
	  		}
		</script>
	</head>
	<body>
	</body>
</html>
```
   2.  Open that html file with Brave Browser

## Actual result:

Open the console (ctrl-shift-C -> 'Console' tab) and observe the error: 

> Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document. 

The 3rd party cookie blocking on brave shield defaults prevents a local html file from writing to localStorage, even though it appears that Brave Shields should be disabled according to the disabled Brave Shields icon to the far right of the URL bar.

## Expected result:

Expected Brave Shields to be disabled and allow localStorage to be written.

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

Brave | 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Linux

## Version/Channel Information:

I only tested it on the official release.

**Comment by bsclifton** [comment]
@jefetienne do you have a way to upgrade to a newer version? The version of Brave you're using is quite old... we're up to 0.68.142 at the moment

I suspect you may be using Ubuntu Snaps, which aren't officially supported (we haven't had an update in a while). Would be good to know if this is still an issue on current versions.

See our install instructions here:
https://brave-browser.readthedocs.io/en/latest/installing-brave.html

**Comment by bsclifton** [comment]
I strongly believe we have fixed this - in particular, localhost with a port number. This behavior didn't work as expected before. 

I'll go ahead and close the issue for now, but please re-open if you still encounter the issue after trying on the latest version. Thanks 😄

**Comment by jefetienne** [comment]
Sorry about that, I retested it on the latest version with my windows machine and I still have the issue. I reopened it here:

https://github.com/brave/brave-browser/issues/6278
