### ISSUE TITLE
Login with Twitter OAUTH doesn't work

### ISSUE THREAD

**Issue by sirjorj** [brave/brave-browser#6251]
I noticed this breaking a few releases ago (On Sept 18th, IIRC).  I have always had to have 'shields down' for this to work, but not it doesn't even work that way. 

## Description 
Trying to log in on this site - https://raithos.github.io/ - using twitter as the OAUTH source no longer works.

## Steps to Reproduce
   1. go here https://raithos.github.io/
   2. hit the 'Log In' icon at the top
   3. use twitter

## Actual result:
After attempting to log in, you get returned to the site but you are not logged in.

## Expected result:
Should be logged in.

## Reproduces how often: 
Every time.  It works on Safari on iPadOS so i don't think it is the site.

## Brave version (brave://version info)

Brave | 0.68.142 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux
JavaScript | V8 7.7.299.11
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Command Line | /usr/bin/brave-browser-stable --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extensions-install-verification=enforce_strict --enable-features=NewExtensionUpdaterService,SimplifyHttpsIndicator,WebUIDarkMode --disable-features=AudioServiceOutOfProcess,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,TranslateUI,UnifiedConsent --flag-switches-begin --flag-switches-end
Executable Path | /opt/brave.com/brave/brave-browser
Profile Path | /home/sirjorj/.config/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:
- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?
I have only used the most recent releases.

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 
Previously, it only worked when shields were down.  Now it doesn't work at all.

**Comment by bsclifton** [comment]
@jumde possibly related to https://github.com/brave/brave-browser/issues/5869?

I wonder if the new preflight-headers check affects either of these?

**Comment by MarkMurphy37** [comment]
Having issues with Twitter login on IndieHackers.com as well.

**Comment by guylepage3** [comment]
+1 on this issue as well

**Comment by sirjorj** [comment]
This works now with 0.70.121.  Thanks!

**Comment by MarkMurphy37** [comment]
Resolved my IndieHackers.com issue. Great work and thank you!

**Comment by rebron** [comment]
Closing. Looks like this is working now.
