### ISSUE TITLE
in line tipping for reddit does not show the post you are trying to tip - follow up to 4907

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6252]
## Description 
Found while testing #4907 

If I am on reddit and click on the inline tip button for a comment, the tip banner should show the post I'm tipping. The post is not shown in the tip banner on 0.69.x.

## Steps to Reproduce

   1. Enable Rewards
   2. Navigate to https://www.reddit.com/user/jonathansampson
   3. Click on in-line tip button for a comment/post.

## Actual result:
Post you are tipping is not shown on tip banner:
<img width="1198" alt="Screen Shot 2019-10-01 at 11 04 32 AM" src="https://user-images.githubusercontent.com/28145373/65974652-4bf40f00-e43b-11e9-9fae-5b8ef3826ca9.png">

## Expected result:
Should show post being tipped like in 0.68.142:
<img width="1193" alt="Screen Shot 2019-10-01 at 10 59 34 AM" src="https://user-images.githubusercontent.com/28145373/65974447-f9b2ee00-e43a-11e9-9dab-4eee4243f205.png">

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.130 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 0.68.x no, 0.69.x yes
- Can you reproduce this issue with the beta channel? unsure, probably yes
- Can you reproduce this issue with the dev channel? 0.71.x yes
- Can you reproduce this issue with the nightly channel? 0.72.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

## Miscellaneous Information:
cc @NejcZdovc @brave/legacy_qa @rebron

**Comment by masparrow** [comment]
Related to #6223

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.72.110 Chromium: 78.0.3904.70 (Official Build) dev (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

Verified STR from the description. Verified new and old reddit. Tested on production and staging env.

![image](https://user-images.githubusercontent.com/34715963/67796703-c5a20b80-fa80-11e9-87f3-802a692c7f62.png)
![image](https://user-images.githubusercontent.com/34715963/67796893-1ade1d00-fa81-11e9-9bde-37e4d3d61db6.png)
![image](https://user-images.githubusercontent.com/34715963/67797080-6ee90180-fa81-11e9-9851-7c57d868b70d.png)
