### ISSUE TITLE
Allow multiple matched segments to trigger ads

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#6256]
## Description 
Currently, there are complaints from users about seeing ads repetitively.  Some of this may be owing to the "winner-take-all" way that targeting functions.  When a category is found to be the highest scoring during a particular ads session, it searches the catalog *only* for ads matching that category.  It can therefore focus too narrowly on that dominant category, causing both too much repetition and limiting the breadth of ads the user can see.

We should therefore expand the breadth of targeting to include matching to the top 3 segments.

**Comment by tmancey** [comment]
iOS failed, restarting iOS build

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.92 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Ubuntu 18.04 LTS

For the same ad

On 1.2.42 - only one segment is used:
![image](https://user-images.githubusercontent.com/34715963/72486255-9a6ec300-380a-11ea-93ee-a4cd95f8fed7.png)


On 1.3.92 - 3 segments are used

![image](https://user-images.githubusercontent.com/34715963/72486163-5bd90880-380a-11ea-89e4-b4bceab92148.png)

Also made sure that other segments are also used to show ads
![image](https://user-images.githubusercontent.com/34715963/72486332-e3267c00-380a-11ea-8b0a-f08ef16d11e3.png)
