### ISSUE TITLE
Allow user to tip any server-allowed amount from Rewards panel, Tipping banner, and Monthly contribution banner

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#6262]
For the new "accelerated" tipping / contribution flows, users should be able to tip any permitted amount, even if the amount is not among the three default (or creator-selected) tipping amounts.

This applies to all screens where tipping/contributions can be sent: the rewards panel; the tipping banner and the monthly contribution banner. 

**The amounts displayed on this menu should be pulled from the server as we may change them over time.**

**Comment by bradleyrichter** [comment]
@NejcZdovc what is the list that the server would return?  (how many items and what are they?)

**Comment by NejcZdovc** [comment]
1 | 5 | 10 | 20 | 50 | 100

![image](https://user-images.githubusercontent.com/9574457/66002562-d434dd00-e458-11e9-99ae-f64ceeb311bf.png)

**Comment by NejcZdovc** [comment]
@bradleyrichter how are we looking on this one?

**Comment by 141** [comment]
A creator set their minimum tip for 10BAT, so now I can't give them anything. I want custom amounts of my choosing, not the publisher's choice. Also a tip all, might be a good option with a confirmation. When will this be implemented?

**Comment by LaurenWags** [comment]
Closing issue as we have custom tipping available.
