### ISSUE TITLE
VAAPI errrors at startup

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#6263]
#4039 introduced the following console error at startup on Ubuntu 18.04:

    [5630:5630:1001/113429.604319:ERROR:vaapi_wrapper.cc(420)] The system version 1.1 should be greater than or equal to 1.3

Reverting the PR makes the error go away.

**Comment by fmarier** [comment]
I don't know whether it's the cause of the crashes I've seen on one of my Linux desktops, but #1024 has link to some scary reports. However it's apparently not a problem unless you run Brave with `--ignore-gpu-blacklist` too.

This is live in Beta and Dev and about to get into release 0.69 so it might be worth to keep in mind and/or investigate further if we see an uptick in crashes with that release.

**Comment by bsclifton** [comment]
cc: @akarshanbiswas @maximbaz @cg505 

Console log being shown - possibly causing a crash, not enough info. We may need to revert https://github.com/brave/brave-browser/pull/4039 if the crashes are related

**Comment by akarshanbiswas** [comment]
@fmarier What's your system libva version? 

This is not a crash. It's a warning that libva has failed to initialize because libva version installed on the system is not compatible with the chromium(brave).

**Comment by fmarier** [comment]
This is the version on my machine:
```
$ dpkg -l libva2  | grep libva2
ii  libva2:amd64   2.1.0-3      amd64        Video Acceleration (VA) API for Linux -- runtime
```

So this warning presumably means that VAAPI is not being used?

**Comment by akarshanbiswas** [comment]
@fmarier Yes. Even if you turn on the --ignore-gpu-blacklist flag, it will use software decoding.

**Comment by fmarier** [comment]
Ok it's probably unrelated to the frequent crashes we are seeing on Linux then.

**Comment by akarshanbiswas** [comment]
@bsclifton Should we close this? Since this issue is not related to vaapi but simply a warning that vaapi is not being initialised?

**Comment by bsclifton** [comment]
@akarshanbiswas yup! that is fair 😄 Thanks for helping debug!
