### ISSUE TITLE
Tip button is only shown on stars tab of user profile when logged in to github

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6266]
Follow up to: https://github.com/brave/brave-browser/issues/5040
Tip button on stars tab of user profile only shows when logged in to github

## Steps to Reproduce

   1. Clean profile
   2. Enable rewards
   3. Open `https://github.com/feross?tab=stars`

Note: after login in to github, the Tip button is shown

## Actual result:

Tip button on stars tab of user profile is not shown
![image](https://user-images.githubusercontent.com/34715963/66005101-c8720680-e4aa-11e9-9993-09e88cf7fd7f.png)

## Expected result:
Tip button  is shown even when not logged in to github
![image](https://user-images.githubusercontent.com/34715963/66004574-72509380-e4a9-11e9-9ac5-97176d2424b8.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @NejcZdovc @jdkuki

**Comment by NejcZdovc** [comment]
@alexwykoff this happens because we tight it to star button. What should we do in this case?
