### ISSUE TITLE
Re-enable download protection remote lookups

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#6267]
In #4341, we disabled download protection entirely due to its leaking URLs to a remote server.

Once we have reduced the metadata sent to the reputation server, we should re-enable this protection in Brave.

Security review: https://github.com/brave/security/issues/180

**Comment by fmarier** [comment]
Documentation updated: https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)/_compare/925a8b29de3ac9867c986fcc3445e3a7328aebf1...aa7d5fa3c157f344818f36e19a3040600a97ef41

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.55 Chromium: 86.0.4240.111 (Official Build) dev (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.14.6 (Build 18G6032)
```

Verified test plan from https://github.com/brave/brave-core/pull/6763

Confirmed files listed in the PR are allowed/blocked as expected:
<img width="1198" alt="Screen Shot 2020-10-29 at 7 46 44 AM" src="https://user-images.githubusercontent.com/28145373/97568057-46aa2080-19bd-11eb-8539-a50c61145bf5.png">

Confirmed files from `Desktop Download Warnings` section of https://testsafebrowsing.appspot.com/ are blocked as expected:
<img width="1198" alt="Screen Shot 2020-10-29 at 7 50 42 AM" src="https://user-images.githubusercontent.com/28145373/97568416-5e81a480-19bd-11eb-9cf9-a04b4bb64409.png">

Ran Fiddler Everywhere while attempting downloads above and confirmed only observed the proxied calls to `sb-ssl.brave.com`.

-------------
