### ISSUE TITLE
[RFE] Allow manual site whitelisting in shield settings

### ISSUE THREAD

**Issue by tonyjames** [brave/brave-browser#6268]
Running Brave version  0.68.142 it would be useful to have an option under settings to manually edit the shields whitelist.  For example, home.nest.com does not work right now without manually setting the global shield setting for cookies to "allow all cookies".  If there was a way to manually allow cookies from "accounts.google.com" that would solve the issue.

**Comment by bsclifton** [comment]
Thanks for the report, @tonyjames! I think we have this covered by https://github.com/brave/brave-browser/issues/2723, so I'm going to close this as a duplicate

Also, we have some reported login issues for Google Auth which @jumde is looking into (captured with https://github.com/brave/brave-browser/issues/5869). Hoping we make some progress there soon 😄
