### ISSUE TITLE
removing "about" tab from "Settings" page

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6271]
## Description 

We should remove the `About` tab from the `Settings` page under `brave://wallet` as per https://github.com/brave/ethereum-remote-client/wiki/Testing, specifically the following:

```
 There should be no About tab present
```

Most of these links are pointing to MM pages.

## Steps to Reproduce

   1. launch brave and create a crypto wallet under `brave://wallet`
   2. once you've created the wallet, click on the profile avatar and select `Settings`

## Actual result:

<img width="1000" alt="Screen Shot 2019-10-02 at 12 45 48 AM" src="https://user-images.githubusercontent.com/2602313/66018799-8cd93b80-e4ae-11e9-8846-199e78428655.png">

## Expected result:

As per https://github.com/brave/ethereum-remote-client/wiki/Testing, we should remove the `About` tab from `Settings` under `brave://wallet`. Or we should at least remove/change the links so they're pointing to Brave websites.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A` (not released yet)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @ryanml @bbondy @rebron @tomlowenthal @brave/legacy_qa

**Comment by srirambv** [comment]
possible dupe of https://github.com/brave/brave-browser/issues/6101

**Comment by kjozwiak** [comment]
Yup, worded differently but definitely a dupe as per https://github.com/brave/brave-browser/issues/6101#issuecomment-533829674.
