### ISSUE TITLE
removing "Mobile Sync" from "Settings -> Advanced"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6272]
## Description 

We should remove the `Sync with Mobile` feature/setting from `Settings -> Advanced` via `brave://wallet` as per https://github.com/brave/ethereum-remote-client/wiki/Testing, specifically the following:

```
Under the advanced tab, there should be no prompt for Mobile Sync
```

## Steps to Reproduce

   1. open brave and create a crypto wallet via `brave://wallet`
   2. once you've created the wallet, click on the profile avatar and select `Settings -> Advanced` and you'll notice that `Sync with Mobile` is available

## Actual result:

<img width="1021" alt="Screen Shot 2019-10-02 at 12 55 52 AM" src="https://user-images.githubusercontent.com/2602313/66019172-1fc6a580-e4b0-11e9-9235-7a3227860e58.png">

## Expected result:

We should remove `Sync with Mobile` from `Settings -> Advanced` as per https://github.com/brave/ethereum-remote-client/wiki/Testing, specifically the following:

```
Under the advanced tab, there should be no prompt for Mobile Sync
```

## Reproduces how often: 

100% reproducible using the STR mentioned above.

## Brave version (brave://version info)

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A` (not released)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @ryanml @bbondy @tomlowenthal @rebron @brave/legacy_qa

**Comment by kjozwiak** [comment]
@bbondy not sure if the above should be removed, but https://github.com/brave/ethereum-remote-client/wiki/Testing, specifically the following sounded like `Sync with Mobile` should be removed:

```
Under the advanced tab, there should be no prompt for Mobile Sync
```

**Comment by bbondy** [comment]
I think this is fixed with the latest ethereum-remote-client extension update

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1903 (Build 18362.30)

* Verified `Mobile Sync` section is removed from advanced settings for component 1.0.9
![image](https://user-images.githubusercontent.com/17010094/66078490-2137b280-e530-11e9-8572-541c68e4f378.png)


Verification passed on 

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

* Verified `Mobile Sync` section is removed from advanced settings for component 1.0.9
![image](https://user-images.githubusercontent.com/17010094/66078634-5f34d680-e530-11e9-947c-6ff24e0a85c1.png)
