### ISSUE TITLE
remove "Info & Help" from the main settings menu

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6273]
## Description 

We should remove the `Info & Help` item from the main `Setting` dropdown via `brave://wallet` as per https://github.com/brave/ethereum-remote-client/wiki/Testing, specifically the following:

```
The Info & Help tab should not be present in the main dropdown menu
```

## Steps to Reproduce

   1. launch brave and create a crypto wallet under `brave://wallet`
   2. once you've created the wallet, click on the profile avatar

## Actual result:

<img width="440" alt="Screen Shot 2019-10-02 at 1 06 55 AM" src="https://user-images.githubusercontent.com/2602313/66019493-b182e280-e4b1-11e9-9803-0271071ff991.png">

## Expected result:

We should remove the `Info & Help` item from the main `Setting` dropdown via `brave://wallet` as per https://github.com/brave/ethereum-remote-client/wiki/Testing, specifically the following:

```
The Info & Help tab should not be present in the main dropdown menu
```

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A` (not released yet)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @ryanml @bbondy @rebron @tomlowenthal @brave/legacy_qa

**Comment by bbondy** [comment]
I think this is fixed with the latest update to ethereum-remote-client extension

**Comment by srirambv** [comment]
Verification passed on 
Brave| 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

Verified no Info & Help button on component version : 1.0.9
![image](https://user-images.githubusercontent.com/17010094/66078022-2d6f4000-e52f-11e9-934b-901e24da1f59.png)


Verification passed on 
Brave| 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1903 (Build 18362.30)

Verified no Info & Help button on component version : 1.0.9
![image](https://user-images.githubusercontent.com/17010094/66078297-c1d9a280-e52f-11e9-977e-91fdc2122848.png)
