### ISSUE TITLE
downloaded seed phrase backup named "MetaMask Secret Backup Phrase"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6275]
## Description 

When downloading/backing up the seed phrase via downloading, the file that's saved is named `MetaMask Secret Backup Phrase.txt` but should be named `Brave Secret Backup Phrase.txt`.

## Steps to Reproduce

   1. open brave and create a wallet via `brave://wallet`
   2. select the `Download phrase` under `Secret Backup Phrase`

<img width="1090" alt="Screen Shot 2019-10-02 at 2 22 18 AM" src="https://user-images.githubusercontent.com/2602313/66022287-7be2f700-e4bb-11e9-8dd4-ad220ca693dc.png">

## Actual result:

<img width="721" alt="Screen Shot 2019-10-02 at 2 03 44 AM" src="https://user-images.githubusercontent.com/2602313/66022095-db8cd280-e4ba-11e9-85b2-ed3526b900f2.png">

## Expected result:

Backup that's being downloaded should be named `Brave Secret Backup Phrase.txt` and not `MetaMask Secret Backup Phrase.txt`.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A` (not released yet)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @ryanml @bbondy @rebron @tomlowenthal @brave/legacy_qa

**Comment by kjozwiak** [comment]
Fixed via https://github.com/brave/brave-browser/issues/5694. Going to close this one off and use this as the main issue for `QA` verification as it includes STR and examples 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

* Verified download seed phrase backup name is `Crypto Wallets Secret Backup Phrase.txt`
* Verified on component version 1.0.9
![image](https://user-images.githubusercontent.com/17010094/66082682-a1621600-e538-11e9-8912-d23ef30500cc.png)


Verification passed on 

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1903 (Build 18362.30)

* Verified download seed phrase backup name is `Crypto Wallets Secret Backup Phrase.txt`
* Verified on component version 1.0.9
![image](https://user-images.githubusercontent.com/17010094/66082848-0ae22480-e539-11e9-8efb-181a19b12177.png)
