### ISSUE TITLE
Congratulations page uses emoji that looks different on different platforms

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6280]
## Description 

Congratulations page uses emoji that looks different on different platforms

## Steps to Reproduce

   1. Finish setting up the wallet on the device
   2. Congratulations message shows use platform-specific emoji

## Actual result:

Linux:
![image](https://user-images.githubusercontent.com/17010094/66054860-a015f680-e502-11e9-8fe5-44a3af4470c2.png)

Windows:
![image](https://user-images.githubusercontent.com/17010094/66054877-a5734100-e502-11e9-9e93-53a02a2944b4.png)

## Expected result:
Should use svg so that it looks same on all platforms

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
--| --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bbondy** [comment]
Not sure if we care to differentiate on this, assuming it's the same on MetaMask?

**Comment by kjozwiak** [comment]
@bbondy same results on MM (checked `macOS` vs `Windows`):

### Windows

<img width="749" alt="Screen Shot 2019-10-07 at 3 51 35 AM" src="https://user-images.githubusercontent.com/2602313/66293950-d910eb00-e8b5-11e9-9c23-f10265406bcd.png">

### macOS

<img width="765" alt="Screen Shot 2019-10-07 at 3 45 10 AM" src="https://user-images.githubusercontent.com/2602313/66293969-e332e980-e8b5-11e9-914d-5b4e4f7c80e8.png">

**Comment by kjozwiak** [comment]
Closing after discussing with @bbondy. Basically the same as MM. I don't think this is worth fixing. Please re-open if someone feels differently.
