### ISSUE TITLE
Save state logs uses MetaMask in download file name

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6281]
## Description 

Save state logs uses MetaMask in download file name

## Steps to Reproduce

   1. Create a crypto wallet and do some transaction
   2. Open Settings -> Advanced -> Download State Logs
   3. Download file name contains Metamask

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/66056875-cab57e80-e505-11e9-810c-017545bab90b.png)

## Expected result:
Should have Brave branding 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.69.131 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by kjozwiak** [comment]
@bbondy should we move this into https://github.com/brave/brave-browser/milestone/55 as we're going to need a new build for https://github.com/brave/brave-browser/issues/5698 and possibly https://github.com/brave/brave-browser/issues/5106?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using https://github.com/brave/ethereum-remote-client/releases/tag/0.1.15 via the following build:

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

* ensured that downloading the `State Log` is being saved as `Brave State Logs.json` on both new wallets and restored wallets.

<img width="1218" alt="Screen Shot 2019-10-09 at 12 24 28 AM" src="https://user-images.githubusercontent.com/2602313/66451751-cf10f880-ea2b-11e9-9a4f-39d3a5b22af0.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

* Verified on `0.1.16` component
* Verified on both new wallet and restored wallet
![image](https://user-images.githubusercontent.com/17010094/66512110-45ead780-eaa6-11e9-8ba9-d04a1b5a8dae.png)
