### ISSUE TITLE
P3A follow up

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#6284]
## Description 
The implementation of Privacy Preserving Product Analytics (P3A) landed with https://github.com/brave/brave-core/pull/3242

More details on our blog here:
https://brave.com/privacy-preserving-product-analytics-p3a/

Detailed list of the questions here:
https://github.com/brave/brave-browser/wiki/P3A

This was a larger scope project and there was some good feedback and discussions in the pull request. This issue is to track asks that were made there and to make sure we follow through with those asks

## P1 Issues
- [ ] Probably wrong capturing of balance https://github.com/brave/brave-antibot/commit/eb1692afeb0e9de4e6007d721045d07806fb9e1a#r34791133
- [ ] https://github.com/brave/brave-core/pull/3242#discussion_r321149497
- [ ] Follow up on mention of tests - https://github.com/brave/brave-core/pull/3242#discussion_r329813917

## P2 Issues
- [ ] Discussion about `LedgerClient::RecordMetric` generic metric interface - https://github.com/brave/brave-core/pull/3242#discussion_r321153036
- [ ] Convert `BraveShieldsOnShieldsPanelShownFunction` to a generic P3A extension API call - https://github.com/brave/brave-core/pull/3242#discussion_r322337766
- [ ] Code organization comment - https://github.com/brave/brave-core/pull/3242#discussion_r329770687
- [ ] Refactoring / code splitting comment - https://github.com/brave/brave-core/pull/3242#discussion_r329771467
- [ ] Make `BraveP3AService` non-refcounted
- [ ] Rename `prochlo` -> `pyxis`

**Comment by iefremov** [comment]
Crossed out some completed items and added another one

**Comment by bsclifton** [comment]
@iefremov can we close this issue out and create specific issues for the must have items (that are still relevant, called out above under P1 / P2)?

**Comment by rillian** [comment]
It looks like this has been covered by specific implementation issues with tracking through @mattmcalister's spreadsheet and the project board.
