### ISSUE TITLE
Privacy Preserving Product Analytics (P3A)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#6285]
## Description 
The implementation of Privacy Preserving Product Analytics (P3A) landed with https://github.com/brave/brave-core/pull/3242

More details on our blog here:
https://brave.com/privacy-preserving-product-analytics-p3a/

Detailed list of the questions here:
https://github.com/brave/brave-browser/wiki/P3A

Follow ups captured with:
https://github.com/brave/brave-browser/issues/6284

Android side captured with:
https://github.com/brave/brave-browser/issues/6176

## Test plan
TBD

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/brave-core/pull/3242

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` label pending overview

**Comment by kjozwiak** [comment]
Removing `QA/Blocked`. Had a meeting with @bsclifton & @aekeus and should have enough information to go through P3A and ensure it's working as expected.

**Comment by GeetaSarvadnya** [comment]
@bsclifton Can we update the wiki to reflect the values for Q.5 as below?

0-5
6-20
21-100
Over 100

**Comment by LaurenWags** [comment]
Proposed general P3A test plan:
- Verify new user messaging as per https://github.com/brave/brave-core/pull/3242
- Verify upgraded user messaging as per https://github.com/brave/brave-core/pull/3242
- Verify each question and answer shows in local-state file
- Verify answers to questions update in local-state (ex. if you open a Tor window for the first time, the response to that particular question should update. Similarly for all other questions)
- Verify answers send to stats
- Verify stats displays data for P3A

cc @bsclifton could you review the above and let me know if there any additions/changes you think should be made?

**Comment by bsclifton** [comment]
@GeetaSarvadnya yes! I just updated, let me know what you think:
https://github.com/brave/brave-browser/wiki/P3A

**Comment by bsclifton** [comment]
@LaurenWags LGTM! 👍

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.1.18 Chromium: 79.0.3945.56 (Official Build) (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

-  Verified the new user messaging as per brave/brave-core#3242
  - Verified that users are notified about P3A in the welcome screen in a clean profile 
![image](https://user-images.githubusercontent.com/38657976/70318494-38ec2980-1846-11ea-86f4-41bb87831c7d.png)
- Verified the upgraded user messaging as per brave/brave-core#3242
  - Verified that existing users will see P3A info bar brave upon upgrade and launch to 1.1.x
  - Verified that info bar remains until acknowledged (even after relaunching)
  - Verified that click `Disable` and will immediately disable the service and close the info bar
  - Verified that Hitting `Got it` or clicking the `X` will acknowledge this and close the info bar
  - Verified click on `Learn more` redirects to the blog post
![image](https://user-images.githubusercontent.com/38657976/70319953-933ab980-1849-11ea-8400-5f0ccafddc5f.png)
