### ISSUE TITLE
Change monthly contribution/payment sequencing

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#6288]
When the time comes to do monthly contributions, the sequence should be as follows:

* Pay each monthly tip in sequence until there is insufficient funds. Never pay a partial monthly tip.
* After either (a) all monthly tips have been paid, or (b) there are not enough funds to handle the next monthly tip, move to handling Auto-Contribute
* For Auto-Contribute, take the remaining funds, up to the user-specified monthly A-C budget, and contribute that amount to verified publishers only, in proportion to the attention they received.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.70.120 Chromium: 78.0.3904.70 (Official Build) (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3658
- Verified the STR's from https://github.com/brave/brave-core/pull/3658#issuecomment-543834535
- Encountered https://github.com/brave/brave-browser/issues/6546 and https://github.com/brave/brave-browser/issues/6545
