### ISSUE TITLE
Export Password creates file name as Chrome Passwords

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#629]
## Description 

Export Password creates file name as Chrome Passwords

## Steps to Reproduce

   1. Login to any site and save the password
   2. Go to `chrome://settings/password` and click on hamburger menu item on Save password
   3. Click export password, save file prompts and defaults the file name to `Chrome Passwords`

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/43079814-1e003c4e-8e5c-11e8-8c64-9c7e95e427af.png)

## Expected result:
Should say `Brave Passwords`

## Reproduces how often: 

100%

## Brave version (about:brave info) 

0.50.14

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.38 Chromium: 78.0.3904.108 (Official Build) nightly (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

Verified test plan from the description. Verified that the passwords are actually store in the file.

![image](https://user-images.githubusercontent.com/34715963/69796081-a7d5dc80-11cd-11ea-88ee-e122745912ff.png)
