### ISSUE TITLE
Unable to import passwords from chrome on Android device

### ISSUE THREAD

**Issue by manishsb** [brave/brave-browser#6297]
## Description 
When I install Brave browser from play store, I am not able to import passwords from other browsers

## Steps to Reproduce

   1.  Install the Brave app from Play store on Android.
   2. Settings > Passwords > 3 dots --- can only see exports password.
   3. No option to Import from other browsers.

## Expected result:
Should be able to allow to import passwords from other browsers

## Reproduces how often: 
No Feature is present

## Brave version (brave://version info)
Brave 1.4.0

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No

**Comment by kjozwiak** [comment]
@manishsb mind creating a new issue via https://github.com/brave/browser-android-tabs/issues? https://github.com/brave/brave-browser/ is used for the development of Brave on the desktop (for now).
