### ISSUE TITLE
Missing Translation for `Secrete Backup Phrase` screen content

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#6298]
## Description 

 Found while testing #5686
Missing Translation for `Secrete Backup Phrase` screen content
## Steps to Reproduce

   1. Set device locale to Spanish
   2. Create a new profile and launch Crypto wallet
   3. Navigate to `Secrete Backup Phrase`
   4. `Secrete Backup Phrase` content isn't translated to Spanish

## Actual result:

Missing Translation for `Secrete Backup Phrase` screen content
![image](https://user-images.githubusercontent.com/38657976/66114646-ea73a200-e5ec-11e9-8e5c-da3f016fbdb4.png)

## Expected result:

`Secrete Backup Phrase` content should be translated to Spanish

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bbondy @kjozwiak

**Comment by GeetaSarvadnya** [comment]
Missing translation for `Backup now` button - It's not translated to spanish

![image](https://user-images.githubusercontent.com/38657976/66115556-b305f500-e5ee-11e9-955e-910a5d358cbc.png)

**Comment by kjozwiak** [comment]
@bbondy possible that MM missing some translations on Spanish?

**Comment by bbondy** [comment]
This should be fixed as part of https://github.com/brave/brave-browser/issues/13191

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.19.74 Chromium: 87.0.4280.101 (Official Build) beta (64-bit)
-- | --
Revision | `9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}`
OS | Linux
Component | `1.0.19 Dev`

- Verified text is translated on `Secret Backup Phrase` screen
- ![image](https://user-images.githubusercontent.com/17010094/103887001-4b383700-50da-11eb-84ee-20a0ec922376.png)
- Verified text is translated on `Backup Now` button
![image](https://user-images.githubusercontent.com/17010094/103887040-5ab78000-50da-11eb-9b7e-72b7b13f36a5.png)

-------
Verification passed on 

Brave | 1.18.77 Chromium: 87.0.4280.101 (Official Build) (64-bit)
-- | --
Revision | `9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}`
OS | Windows 10 OS Version 2009 (Build 19042.685)
Component | `1.0.19 Dev`

- Verified text is translated on `Secret Backup Phrase` screen
![image](https://user-images.githubusercontent.com/17010094/103888189-3c528400-50dc-11eb-8392-3b24b5879a06.png)

- Verified text is translated on `Backup Now` button
![image](https://user-images.githubusercontent.com/17010094/103888217-4b393680-50dc-11eb-93f3-5da64b01088a.png)

------

Verification passed on 

Brave | 1.20.58 Chromium: 88.0.4315.7 (Official Build) nightly (x86_64)
-- | --
Revision | `9b020863b2987261f6dcd018c6b388041c035f98-refs/branch-heads/4315@{#15}`
OS | macOS Version 10.15.7 (Build 19H114)
Component | `1.0.19 Dev`

- Verified text is translated on `Secret Backup Phrase` screen
![image](https://user-images.githubusercontent.com/17010094/103887773-8d15ad00-50db-11eb-83e8-b66121d6ba9c.png)

- Verified text is translated on `Backup Now` button
![image](https://user-images.githubusercontent.com/17010094/103887820-9c94f600-50db-11eb-9263-b6c7b2ab366c.png)
