### ISSUE TITLE
Testing Brave Beta too complicated for average (but technical) users

### ISSUE THREAD

**Issue by raarts** [brave/brave-browser#6299]
## Description 

I saw that chromecast support was added to Brave Beta. So - being a developer myself - decided that I'd switch to Brave Beta which (by the looks of it) would still be stable enough for my daily use. But it turns out it's a completely separate installation from Brave production, so I either need to copy a bunch of config file (and worse: keep them in sync) or switch to Brave Beta altogether which could increase the chance of me in the future being blocked by a bug, and needing to migrate to production again.

So maybe this is a feature request: let Brave Beta you the configuration of Brave production, and just disallow them from being used together. Or create a switch for it.

If this is already possible, make this feature more discoverable (maybe a FAQ entry) because I didn't encounter it.

## Steps to Reproduce

Run Brave Beta

## Actual result:

It starts up completely empty

## Expected result:

Runs with my Brave configuration.

## Reproduces how often: 

Every time

## Brave version (brave://version info)

0.68

## Version/Channel Information:

Beta channel

## Other Additional Information:

n/a
## Miscellaneous Information:

Note I *am* a developer myself, but only want to get involved in the community as someone who just runs the Beta channel in his daily routine, and can give meaningful answer when developers ask questions about bugs.

**Comment by DurgadeviAvatarae** [comment]
4221414

**Comment by DurgadeviAvatarae** [comment]
#

**Comment by DurgadeviAvatarae** [comment]
Boom

**Comment by jhhlim** [comment]
Hi, has this been resolved yet? I would also like to know how I can test brave beta. I'm a CS student right now studying open source and was unable to get this to run on my local machine since I'm using putty and school server. There's many prerequisites such as installing sdk, updating js, python, npm, etc but there's no clear instruction on how to actually run the program after all has been installed. How do I combine all the software I downloaded in prerequisites (I'm using windows) to run the program?

**Comment by bsclifton** [comment]
@jhhlim running Brave Beta is just as easy as downloading from https://brave.com/download-beta

To address comment in the original post - maybe we can create some more noise in https://github.com/brave/brave-browser/issues/1357.  Being able to import from other channels would be a huge help

Another solution: you can use sync v2 and join the same sync group across all channels. This should be a super easy solution which gets just about all of your data synced.

Given there is a solution (sync) and also an issue for importer, I'll close this issue out. Thanks!
