### ISSUE TITLE
import stats (trackers, ads, https upgrades, time saved.) from browser-laptop > brave-browser

### ISSUE THREAD

**Issue by w0ts0n** [brave/brave-browser#630]
## Description 
We should allow users who are importing bookmarks etc from browser-laptop > brave-browser to also import their stats
![image](https://user-images.githubusercontent.com/2603015/43101132-554ab2b8-8e7c-11e8-804e-0c97c2ecf20c.png)

CC @garrettr

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on
Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows
