### ISSUE TITLE
Browser crash when trying to login on a suspended tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#631]
## Description 

Browser crash when trying to login on a suspended tab

## Steps to Reproduce
   1. https://bravesoftware.slack.com/archives/C7VLGSR55/p1532436274000065

## Actual result:

Browser crashes every time you try to login

## Expected result:
Should successfully login without crashing the browser

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Release build

## Additional Information
Tabs are lost and shows restore button when browser is relaunched
cc: @bbondy please move the issue to backlog milestone if required

**Comment by bbondy** [comment]
@srirambv can you get a crash ID for this?

**Comment by srirambv** [comment]
@bbondy cant reproduce now on Release build or packaged build. Closing the issue for now. Will reopen if i am able to crash and get the crash id.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows
