### ISSUE TITLE
How do I download this?

### ISSUE THREAD

**Issue by InternetDownloader** [brave/brave-browser#6315]
## Description 
<img width="1135" alt="screenshot" src="https://user-images.githubusercontent.com/26020638/66226439-aa193000-e68f-11e9-8d69-2430914b1501.png">

Trying to download a link. Not sure how:
https://tinyurl.com/2fcpre6

## Steps to Reproduce

   1. Try link
   2. ???
   3. 

## Actual result:
I could download it

## Expected result:
Not sure how to download it

## Reproduces how often: 
100%

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@InternetDownloader Works fine for me on current release build 0.69.132 on macOS Catalina 10.15

@LaurenWags You mind taking a look on High Sierra or Mojave? notarization issue?

**Comment by LaurenWags** [comment]
Unable to reproduce on High Sierra using

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

Navigated to https://download.cnet.com/MacX-YouTube-Downloader/3000-2071_4-76641301.html with default shields set. Clicking on the `Download Now` button directed me to a new page and after a couple of seconds, I received the dialog prompting me to choose my download location.

@kjozwiak could you check Mojave?

**Comment by kjozwiak** [comment]
I'm too scared to hit https://tinyurl.com/2fcpre6. I have a feeling nothing good will come from it.
