### ISSUE TITLE
Android `Rewards settings` page: switch to core implementation instead of using a separate one.

### ISSUE THREAD

**Issue by gdregalo** [brave/brave-browser#6316]
## Description 

Android uses `Brave Rewards settings` (at https://github.com/brave/browser-android-tabs/tree/base-76.0.3809.132/components/brave_rewards_ui) which is a separate implementation of what Desktop has (https://github.com/brave/brave-core/tree/master/components/brave_rewards/resources).  Please make core implementation usable on Android. 
Another solution is to switch to native UI.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
closing as we will switch to native UI
