### ISSUE TITLE
adblocker doesn't work on golem.de when not disabling scripts

### ISSUE THREAD

**Issue by szaimen** [brave/brave-browser#6317]
1. adblocker is activated
2. scripts are allowed.
3. golem.de looks like this:
![image](https://user-images.githubusercontent.com/42591237/66244758-4f70ea00-e70a-11e9-9edc-dbde76b7a4d2.png)
But there shouldn't be any adverts.

I am using Brave on Windows 10: Version 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)

**Comment by srirambv** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
Just waiting on review :)

**Comment by szaimen** [comment]
If you need a review, maybe you could guide me how to review this?
I am no developer unfortunately and don't know where to start and what I need to do to test your PR :(

**Comment by szaimen** [comment]
I tried golem.de again with cosmetic blocking enabled and it still shows first party ads. Is there something I am missing?

**Comment by bsclifton** [comment]
@szaimen I don't think first party ads are removed

cc: @antonok-edm @snyderp for confirmation

It should be possible to block these though using the brave://adblock page and adding the selector

**Comment by ryanbr** [comment]
https://github.com/brave/adblock-lists/pull/329 Should fix this.

**Comment by bsclifton** [comment]
Seems to be working great- going to close 😄 Let's re-open if there is still a problem
