### ISSUE TITLE
Icon for Auto-Contribute disappears when Ads is enabled 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#6321]
## Description 

If Ads is enabled but A-C is disabled, then the icon for A-C will disappear.

![image](https://user-images.githubusercontent.com/11497541/66251853-948b2f80-e78f-11e9-821c-7780d327e453.png)

## Steps to Reproduce

   1. Go to brave://rewards
   2. Enable Ads
   3. Disable A-C

## Reproduces how often: 

100% of the time.

## Brave version (brave://version info)

Version 0.72.72 Chromium: 77.0.3865.90 (Official Build) nightly (64-bit)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.2.5 Chromium: 78.0.3904.97 (Official Build) dev (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified STR from description
<img width="646" alt="issue6321" src="https://user-images.githubusercontent.com/28145373/69276976-6c278b00-0bad-11ea-8372-e302000a9cb9.png">
