### ISSUE TITLE
Icons for frequently used pages are not rendering properly in New Tab page

### ISSUE THREAD

**Issue by mayankDhiman** [brave/brave-browser#6322]
## Description 
In the new tab, browser displays a list of pages which are used frequently. The icons for these pages are not rendered properly. If it matters, I am using Brave browser on Ubuntu 18.04 with Gnome Desktop Environment. 

## Steps to Reproduce
   1. Access a web-page frequently
   2. Once it starts appearing in frequently used pages, it's icon is not rendered properly.

## Actual result:
![Screenshot from 2019-10-05 15-54-40](https://user-images.githubusercontent.com/32799055/66253590-838af000-e788-11e9-87ec-6a7af34d357f.png)

## Expected result:
Above icons should be rendered properly

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
**Brave:** 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
**Revision:** 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
**OS:** Linux

## Version/Channel Information:
I only observed this issue with above mentioned version.

- Can you reproduce this issue with the current release?
Yes

- Can you reproduce this issue with the beta channel?
Not tried
- Can you reproduce this issue with the dev channel?
Not tried

- Can you reproduce this issue with the nightly channel?
Not tried

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields?
No

- Does the issue resolve itself when disabling Brave Rewards?
No

- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:
I am not sure if this is occurring on my machine only or this is reproducible on other machines as well.

**Comment by rebron** [comment]
Duping to #480
