### ISSUE TITLE
Please also provide search-engine-settings for private and tor windows

### ISSUE THREAD

**Issue by szaimen** [brave/brave-browser#6324]
Is https://github.com/brave/brave-browser/issues/2158 going to be addressed now as https://github.com/brave/brave-core/pull/3319 is merged?
Maybe you could make https://github.com/brave/brave-browser/issues/2158 accessible again? It is not open for comments and liking...

**Comment by srirambv** [comment]
#2158 isn't locked. You can add a comment in the issue. #2158 isn't yet implemented via https://github.com/brave/brave-core/pull/3319.
