### ISSUE TITLE
Disable Offer to install Google Translate extension in translate bubble

### ISSUE THREAD

**Issue by pongraczi** [brave/brave-browser#6326]
In the #6295 (Verzió: 0.69.132 Chromium: 77.0.3865.90 (Hivatalos verzió) (64 bites)) I got an annoying bubble on every page which is not in my native language. I find it very annoying.

![Kijelölés_193](https://user-images.githubusercontent.com/5891983/66258440-9bbd3800-e7a5-11e9-9241-0fe1a7d4d1db.png)

Is that possible to disable somehow this annoying "Offer to install Google Translate extension in translate bubble.(#5561)" ?

I did not find option in the menu/settings or right-click context menu.

Thanks.

**Comment by yrliou** [comment]
Hi @pongraczi, yes there is an option to disable this.
Please go to brave://settings/languages, and click on `Language` drop down, and find the `Offer to translate pages that aren't in a language you read` option as below to disable this, thanks.
<img width="698" alt="Screen Shot 2019-10-05 at 10 42 03 AM" src="https://user-images.githubusercontent.com/4730197/66258664-cb941d80-e75c-11e9-8583-8fd4e992727b.png">

**Comment by yrliou** [comment]
Closing this because there is an existing option in brave://settings.

**Comment by pongraczi** [comment]
Thanks, you were right, indeed.  
Unfortunately the menu confused me and I did not realized the small arrow shape need to click.  
I think the design is too minimalist for me.

![Kijelölés_194](https://user-images.githubusercontent.com/5891983/66270716-f2367f00-e856-11e9-9ba5-03ba796405a6.png)
