### ISSUE TITLE
Google-Translate-extention Pop-Up

### ISSUE THREAD

**Issue by GraOrigin** [brave/brave-browser#6329]
## Description 
Since v0.69.132 I'm being plagued by a new pop-up on every english site, asking me to install google-translate-extention to translate this site. Since I've not found a option to disable it in settings and somehow "brave://config" does not exist anymore (where did this go to?) I'm wondering how to disable it. 

## Brave version (brave://version info)
macOS Version 0.69.132 Chromium: 77.0.3865.90 (Offizieller Build) (64-Bit)

**Comment by psisavant** [comment]
Issue also occurs on the linux build
Linux Version 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)

**Comment by TCB13** [comment]
Same problem under Windows, does anyone test this browser? lol

Who was the bright person that decided to make it popup in every f* website, really guys.

**Comment by srirambv** [comment]
@GraOrigin @psisavant  @TCB13   What language is set on the browser?

**Comment by TCB13** [comment]
> @GraOrigin @psisavant @TCB13 What language is set on the browser?

Portuguese, but that's kind of irrelevant, the browser should not show a popup on every website. It should have something on the options that allows me to pick if I want translations or not.

**Comment by Numline1** [comment]
Same thing's happening to me, 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit) mostly on websites that are non-english (my browser's set to english, so is my OS).

I've used https://aktuality.sk as an example (slovak news portal).

![image](https://user-images.githubusercontent.com/12192684/66271004-89043b00-e859-11e9-9296-dad032d3ac1e.png)

**Comment by psisavant** [comment]
@srirambv 
Happens on non-English browser locale while trying to view English sites but as @TCB13 wrote that's indeed not the point. The popups are very obnoxious and there's no clear way of disabling them. I didn't install the extension because it was not clear to me whether I could disable it later.

**Comment by yrliou** [comment]
@GraOrigin @psisavant @TCB13 @Numline1 
The option to disable the popups is in the `Language` drop down at `brave://settings/languages`.
Please see below for screenshot of the `Offer to translate pages that aren't in a language you read` option, thanks.
<img width="698" alt="google_translate" src="https://user-images.githubusercontent.com/4730197/66274148-67428e00-e830-11e9-8748-ab6c525318b9.png">
And yes, the extension can be disabled through `brave://extensions` if you do decide to install it.

**Comment by dschwank** [comment]
Oh boy - that setting is really hard to find. Thanks @yrliou - this worked for me.

**Comment by psisavant** [comment]
@yrliou 
Seems like that dropdown was well-hidden for me due to non-dark GUI chosen.
Everything's been working fine after adjusting these options.
Nevertheless, making the popup less aggressive or otherwise capable of taking the user to the translation options could make it more accessible.

**Comment by vincentdeity** [comment]
I suggest the popup adds a button "Never ask again" that will toggle the setting on brave://settings/languages

**Comment by andreabenetton** [comment]
> brave://settings/languages

I'm on Linux Version 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit), Italian language set and the option isn't there. 
![image](https://user-images.githubusercontent.com/6141792/66378256-5d956380-e9b3-11e9-96b9-1104ea71ec83.png)

**Comment by yrliou** [comment]
<img width="335" alt="Screen Shot 2019-10-11 at 12 11 20 PM" src="https://user-images.githubusercontent.com/4730197/66678256-5030e100-ec20-11e9-8dea-e1d9b526bc97.png">
With today's release (Version 0.69.135), the prompt contains a button `Don't ask me again` for users to disable the prompt.
The setting could still be changed through `Language` dropdown in `brave://settings/languages` after that.
I'm going to close this issue since it's now addressed, thanks.
