### ISSUE TITLE
applescript/JXA interpreter only reacts to "Brave" on macos while system reports "Brave Browser" as name

### ISSUE THREAD

**Issue by ubuntudroid** [brave/brave-browser#6330]
## Description 
When asking macos for the name of the Brave Browser app it reports `Brave Browser`. However when trying to issue commands to the app via applescript it only responds to `Brave`. Unifying this would ease automation (e.g. with Alfred, see [this issue](https://github.com/vitorgalvao/alfred-workflows/issues/91#issuecomment-538693186)) a lot.

## Steps to Reproduce

   1. Check the name of the app (e.g. via finder). It is `Brave Browser`.
   2. Attempt to issue commands to `Brave Browser` via applescript.
   3. Attempt to issue commands to `Brave` via applescript.

## Actual result:
Step 2 will result in Brave not responding to the commands. Step 3 works.

## Expected result:
Brave should use the same app name as it uses to recognize applescript commands. So either the app name should be changed to `Brave` instead of `Brave Browser` or Brave should respond to applescript commands issued to `Brave Browser` instead of `Brave`.

For backwards compatibility it would possibly make sense to make sure that both applescript commands to `Brave` and `Brave Browser` do work. I am not an applescript expert, so I don't know whether this is technically possible.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 0.68.142 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? didn't check
- Can you reproduce this issue with the dev channel? didn't check
- Can you reproduce this issue with the nightly channel? didn't check

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no, as it is a Brave specific issue

## Miscellaneous Information:
I'm only here because I was redirected by the maker of the PinPlus workflow for Alfred which doesn't work for Brave. The related issue I created on their end is https://github.com/vitorgalvao/alfred-workflows/issues/91. I don't know a lot about applescript thus my explanations might prove incomplete or inaccurate, but I will try to aid in debugging when guided into the right direction.

**Comment by rebron** [comment]
@ubuntudroid Do you have the older version of Brave installed?

**Comment by ubuntudroid** [comment]
@rebron My version as of today is Version 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)

**Comment by vitorgalvao** [comment]
This can be closed; the bug seems to no longer be present.

@ubuntudroid You can confirm it by testing the Alfred Workflow again and seeing `pa` now works. Don’t forget to activate `View → Developer → Allow JavaScript from Apple Events` first.

**Comment by ubuntudroid** [comment]
Looking good indeed! 😍
