### ISSUE TITLE
Balance difference in rewards settings page and BR panel 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#6335]
## Description 

Found while testing #5780 

Balance difference in rewards settings page and BR panel 

## Steps to Reproduce

   1. Clean profile 0.70.109 
   2. Join Rewards
   3. Turn OFF the brave rewards switch in the rewards settings page
   4. Verify wallet with existing KYC'd uphold account
   5. Wallet balance is displayed in the settings page but not in BR panel
   

## Actual result:

Balance difference in rewards settings page and BR panel 
![image (1)](https://user-images.githubusercontent.com/38657976/66316110-ac4fe880-e934-11e9-84da-43519740c95e.png)

## Expected result:

The balance should be the same in both places
## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.70.109 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? can't test due to #5780 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @mandar-brave @NejcZdovc @brave/legacy_qa

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.2.41 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4006 and from https://github.com/brave/brave-browser/issues/6335#issuecomment-539548655

![image](https://user-images.githubusercontent.com/34715963/71755909-56380600-2e8d-11ea-88c0-31b6ff67a2b7.png)
![image](https://user-images.githubusercontent.com/34715963/71755916-5d5f1400-2e8d-11ea-839d-2e392fd57625.png)
