### ISSUE TITLE
`Rewards settings` in BR panel is not accessible in 0.70.x and above

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#6336]
## Description 

`Rewards settings` button is not accessible in 0.70.x and above versions

## Steps to Reproduce

   1. Clean profile 0.70.109
   2. Join rewards
   3. Turn OFF brave rewards switch in the rewards settings page
   4. Verify wallet with existing KYC'd uphold account
   5. Navigate to brave://rewards page
   6. Open the BR panel and click on the `Rewards settings` 
   7. Click on `Rewards settings` don't open `brave://rewards` page in a new tab
   8. Open a new tab, click on BR panel click on `Rewards Settings` in BR panel
   9. `brave://rewards` page isn't opened in a new tab
  

## Actual result:

Click on `Rewards settings` don't open `brave://rewards` page in a new tab
![image](https://user-images.githubusercontent.com/38657976/66316941-3b113500-e936-11e9-889d-fba4fbf857d9.png)

## Expected result:

Click on `Rewards settings` should open `brave://rewards` page in a new tab
## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.70.109 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @mandar-brave @NejcZdovc @brave/legacy_qa

**Comment by LaurenWags** [comment]
Reproduced on macOS 

Brave | 0.70.110 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

Using these STR:
1. Clean profile on above build
2. Enable Rewards
3. Navigate to brave://rewards (when Rewards are ON, the `Rewards Settings` button in the panel works.
4. Disable Rewards and close tab.
5. Open a new tab.
6. Click on BAT logo. 
7. Click on Rewards Settings in panel.
--> Nothing happens.

**Comment by btlechowski** [comment]
Reproduced on Ubuntu

Brave | 0.70.109 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.70.118 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
- Verified the test plan mentioned in https://github.com/brave/brave-core/pull/3631
- Verified in both new and upgraded profile
