### ISSUE TITLE
Updates are broken on OpenSUSE

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#6338]
## Description 

While installation on OpenSUSE 15 works fine following our [official instructions](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#opensuse-15), updates do not work.

## Steps to Reproduce

   1. Install OpenSUSE 15 in a VM.
   2. Follow the [installation instructions](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#opensuse-15)
   3. Update the repository using `zypper ref`.

## Actual result:
```
# zypper ref
Problem retrieving files from 'brave-browser'.
Permission to access 'https://brave-browser-rpm-release.s3.brave.com/x86_64/media.1/media' denied.
Please see the above error message for a hint.
Skipping repository 'brave-browser' because of the above error.
Repository 'google-chrome' is up to date.                                                                       
...                           
Some of the repositories have not been refreshed because of an error.
```

**Comment by fmarier** [comment]
It appears that our repository is not fully compatible with `zypper`, but we haven't yet figured out what needs to be done to fix it.

**Comment by fcrozat** [comment]
https://github.com/brave/brave-browser/issues/1900#issuecomment-512660903 give the explanation: 
https://brave-browser-rpm-release.s3.brave.com/x86_64/media.1/media should return 404 instead of 403.

**Comment by fmarier** [comment]
> [#1900 (comment)](https://github.com/brave/brave-browser/issues/1900#issuecomment-512660903) give the explanation:
> https://brave-browser-rpm-release.s3.brave.com/x86_64/media.1/media should return 404 instead of 403.

We tried making the bucket public a few weeks ago, but it didn't seem to help. I got this error message:

```
Repository 'brave-browser' is invalid.
[brave-browser|https://brave-browser-apt-staging-release-test.s3-us-west-2.amazonaws.com/x86_64/] Repository type can't be determined.
Please check if the URIs defined for this repository are pointing to a valid repository.
Warning: Skipping repository 'brave-browser' because of the above error.
Some of the repositories have not been refreshed because of an error.
```

instead of the usual:

```
Problem retrieving files from 'brave-browser'.
Permission to access 'https://brave-browser-rpm-release.s3.brave.com/x86_64/media.1/media' denied.
Please see the above error message for a hint.
Warning: Skipping repository 'brave-browser' because of the above error.
Some of the repositories have not been refreshed because of an error.
```

**Comment by tneo** [comment]
The first error tells you what is wrong. RPM expects a tag to identify the type of repository that it is. I'm not a packager, but shouldn't the repo have the label "type=rpm-md" in there?

Maybe this can help you a bit: https://help.sonatype.com/repomanager2/rpm-packages-and-yum-repositories

**Comment by othyro** [comment]
If the fix is simple, can we get an ETA on it? OpenSUSE users aren't getting critical browser security updates because of this.

**Comment by fmarier** [comment]
The problem is that we don't know how to fix this yet. The solutions that have been proposed so far have not worked in our testing.

This is the script we use to create the RPM repository, in case someone can figure out what's missing for OpenSUSE: https://github.com/brave/brave-core/blob/master/script/upload_to_rpm_repo

**Comment by fmarier** [comment]
While working on a different RPM problem (#3982), we discovered that the lack of signature on `repomd.xml` is also the root cause for this `zypper ref` failure, despite the unhelpful error messages I pasted above.

A fix is being worked on in https://github.com/brave/brave-core/pull/3877.

**Comment by fmarier** [comment]
Updates are now working on all channels, though there is still an "unsigned repo" warning that needs to be ignored (#3982).
