### ISSUE TITLE
Adding "Never Ask Again" under Google Translate popup

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6340]
## Description 

When we released the Google Translate popup feature in `0.69.x` via https://github.com/brave/brave-browser/issues/5561, it made using Brave more inconvenient for none-english peaking users as they constantly get the popup when visiting English websites. Some examples of user concerns: https://github.com/brave/brave-browser/issues/6326, https://github.com/brave/brave-browser/issues/6329, https://github.com/brave/brave-browser/issues/208#issuecomment-538279280, https://github.com/brave/brave-browser/issues/208#issuecomment-538537499.

We should add a `Never ask again` or a `Don't ask again` checkbox under the prompt that would control the `Offer to translate pages that aren't in a language you read` setting via `brave://settings/languages`.

## Steps to Reproduce

   1. install and launch `0.69.132 Chromium: 77.0.3865.90`
   2. depending on your locale, visit a website that's in a different language so you get the Google Translate prompt.

## Actual result:

<img width="385" alt="Screen Shot 2019-10-07 at 1 06 18 PM" src="https://user-images.githubusercontent.com/2602313/66332697-4dbe4680-e903-11e9-876b-61df0ce676cf.png">

## Expected result:

Should be similar to what we implemented with Widevine. Example:

<img width="360" alt="Screen Shot 2019-10-07 at 12 38 27 AM" src="https://user-images.githubusercontent.com/2602313/66332757-6cbcd880-e903-11e9-9cfe-33be4d8dd2de.png">

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @rebron @bsclifton @bbondy @davidtemkin @yrliou @brave/legacy_qa

**Comment by rebron** [comment]
@bradleyrichter @karenkliu  Do we even need a mock? I think we can simply go with the: 
 [ ] Don't ask again 
check box like what @kjozwiak linked to above.

**Comment by bradleyrichter** [comment]
2 options:

![image](https://user-images.githubusercontent.com/13509546/66338021-1fd20580-e8f5-11e9-8f63-24812463f37b.png)


or

![image](https://user-images.githubusercontent.com/13509546/66338045-2ceef480-e8f5-11e9-97f8-cbbade96f285.png)

**Comment by karenkliu** [comment]
How about this:

![install google translate](https://user-images.githubusercontent.com/2388823/66348114-a218f480-e90a-11e9-9a81-4e1abd9e0232.png)

**Comment by yrliou** [comment]
Test plan specified in https://github.com/brave/brave-core/pull/3617#issue-325513717.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.134 Chromium: 77.0.3865.120 (Official Build) (64-bit)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3617
- Logged https://github.com/brave/brave-browser/issues/6428
