### ISSUE TITLE
Lazy load WebTorrent component

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#6342]
## Description 
Currently the WebTorrent component and its background page is loaded when the browser starts. It could save ~20MB and a process if we use a network throttle to detect .torrent and magnet URLs, and only enable it once one of those 2 things are loaded.

## Steps to Reproduce

   1. Fresh profile
   2. Navigate to https://webtorrent.io/free-torrents
   3. Pick a magnet URL
   4. Repeat step 1-3 but with a .torrent file link

## Actual result:
Torrent loads, but process exists as soon as you open the browser with a fresh profile.

## Expected result:
Torrent still loads correctly, but process only starts once you load a torrent.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

All versions.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.112 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Reproduced on 0.69.x
![image](https://user-images.githubusercontent.com/34715963/66788527-2f021600-eee8-11e9-8bb2-7fa7e121337c.png)

Verified that Webtorrent extension is not launched on clean profile
![image](https://user-images.githubusercontent.com/34715963/66787606-9e760680-eee4-11e9-8cd5-613861bb7c9a.png)
Verified that Web-torrent extension is lazy loaded when torrent file is opened
![image](https://user-images.githubusercontent.com/34715963/66787688-e301a200-eee4-11e9-929c-a821c8f09744.png)
Verified that the torrent is downloaded
Verified opening downloaded files works
Verified saving downloaded files to disk works
Verified that it is possible to download more than one torrent concurrently
Verified that torrent is blocked in Private Window. Encountered https://github.com/brave/brave-browser/issues/3098
Verified that torrent is blocked in Tor Window
