### ISSUE TITLE
Refactor and migrate Rewards category from category to type

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#6350]

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` until the test plan is understood better. Additional detail/clarification requested from @tmancey .

**Comment by LaurenWags** [comment]
Test plan on PR updated, removed `QA/Blocked` label. Thanks @tmancey !

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.70.120 Chromium: 78.0.3904.70 (Official Build) (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from https://github.com/brave/brave-core/pull/3630
* Confirmed Auto Contributions (AC and recurring tips) work as expected after an upgrade from 0.69.135 to 0.70.120
* Confirmed Pending Contributions (adding sites to the pending list) works as expected after an upgrade from 0.69.135 to 0.70.120
* Confirmed Auto Contributions (AC and recurring tips) work as expected for a fresh install of 0.70.120
* Confirmed Pending Contributions (adding sites to the pending list) works as expected for a fresh install of 0.70.120.
<img width="1192" alt="Screen Shot 2019-10-22 at 3 31 05 PM" src="https://user-images.githubusercontent.com/28145373/67323861-03cb8800-f4e1-11e9-887b-4a546e682c1d.png">
<img width="970" alt="Screen Shot 2019-10-22 at 3 31 18 PM" src="https://user-images.githubusercontent.com/28145373/67323865-05954b80-f4e1-11e9-9c42-ebfb725531bf.png">
