### ISSUE TITLE
Refactor loadFromJson from RapidJSON to base::JSONReader

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#6351]

**Comment by tmancey** [comment]
Properties have been renamed to prepare for https://github.com/brave/brave-browser/issues/6352 after this ticket has been merged

**Comment by btlechowski** [comment]
@tmancey Is this issue `QA/Yes` or `QA/No`?

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.3.94 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.14.6 (Build 18G103)

Upgrade paths
* Installed 1.2.42 and confirmed the following states:
1. Rewards On, Ads On, AC On —> Upgrade to 1.3.x —> states preserved
2. Rewards On, Ads Off, AC On —> Upgrade to 1.3.x —> states preserved
3. Rewards On, Ads On, AC Off —> Upgrade to 1.3.x —> states preserved
4. Rewards On, Ads Off, AC Off —> Upgrade to 1.3.x —> states preserved
5. Rewards Off but had been on previously —> Upgrade to 1.3.x —> state preserved
6. Rewards never On —> state preserved
* Installed 1.2.42 and confirmed the following data is set up:
7. Rewards On, anon wallet has balance, Ads panel has data, AC panel has data, Monthly Contributions panel has data, Tips panel has data —> Upgrade to 1.3.x —> data is preserved
8. Rewards On, KYC’d Uphold user wallet connected, Ads panel has data, AC panel has data, Monthly Contributions panel has data, Tips panel has data —> Upgrade to 1.3.x —> data is preserved

Clean install checks:
* Installed 1.3.x and confirmed the following states:
1. Rewards OFF. Close and relaunch Brave. State preserved.
2. Rewards On, and then toggle off. Close and relaunch Brave. State preserved.
3. Rewards On, Ads On, AC On. Close and relaunch Brave. States preserved.
4. Rewards On, Ads Off, AC On. Close and relaunch Brave. States preserved.
5. Rewards On, Ads On, AC Off. Close and relaunch Brave. States preserved.
6. Rewards On, Ads Off, AC Off. Close and relaunch Brave. States preserved.
* Installed 1.3.x and confirmed the following data is set up:
7. Rewards On, anon wallet has balance, Ads panel has data, AC panel has data, Monthly Contributions panel has data, Tips panel has data. Close and relaunch Brave. Data is preserved. (Note, encountered issue #7526 as noted below, so Tips panel did not have data)
8. Rewards On, KYC’d Uphold user wallet connected, Ads panel has data, AC panel has data, Monthly Contributions panel has data, Tips panel has data. Close and relaunch Brave. Data is preserved.
* Encountered https://github.com/brave/brave-browser/issues/7526 during testing.
