### ISSUE TITLE
no longer able to claim Ad Rewards from panel

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6357]
## Description 
Found while testing #5578 

Ad Rewards can no longer be claimed from the panel/BAT logo notification. There is an `OK` button instead of `Claim`. Clicking on `OK` dismisses the notification and does not bring up the captcha.

In 0.69.x, the `Claim` button, when clicked, displays the captcha so the Ad Rewards can be claimed from the panel.

## Steps to Reproduce

   1. Clean profile 0.70.x
   2. Enable Rewards
   3. Restore a wallet with Ad Rewards available for claiming
   4. Click on BAT logo.
   5. View Notification.

## Actual result:
See notification:
<img width="1196" alt="Screen Shot 2019-10-08 at 11 39 07 AM" src="https://user-images.githubusercontent.com/28145373/66410547-49a42e80-e9c0-11e9-9c16-91cb76d8ca9e.png">

Click OK. Notification is dismissed, no captcha to claim Ad Rewards is shown. Need to claim from brave://rewards page.
<img width="1195" alt="Screen Shot 2019-10-08 at 11 40 02 AM" src="https://user-images.githubusercontent.com/28145373/66410609-6476a300-e9c0-11e9-8d2d-6eee9c7df012.png">

## Expected result:
For the flow to be as it is on 0.69.x (wording may be slightly different due to above issue):
<img width="1199" alt="Screen Shot 2019-10-08 at 11 27 51 AM" src="https://user-images.githubusercontent.com/28145373/66410266-d3073100-e9bf-11e9-95c1-ddd34fb335f1.png">

Click Claim, complete Captcha, then get message like this:
<img width="1197" alt="Screen Shot 2019-10-08 at 11 28 07 AM" src="https://user-images.githubusercontent.com/28145373/66410281-db5f6c00-e9bf-11e9-9d75-da710b7eac7b.png">

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.70.110 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, does not reproduce with 0.69.132 (Released version)
- Can you reproduce this issue with the beta channel? yes, reproduces with 0.70.110
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @NejcZdovc @brave/legacy_qa @rebron @mandar-brave

**Comment by kjozwiak** [comment]
Nice find @LaurenWags 👍 Thanks for calling this out!

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.115 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3640

![image](https://user-images.githubusercontent.com/34715963/66750620-36480600-ee8d-11e9-97a6-106909be0248.png)
![image](https://user-images.githubusercontent.com/34715963/66750634-3b0cba00-ee8d-11e9-97f1-d2911b5472f9.png)
![image](https://user-images.githubusercontent.com/34715963/66750650-43fd8b80-ee8d-11e9-8f5b-cc44da32a549.png)
![image](https://user-images.githubusercontent.com/34715963/66750658-47911280-ee8d-11e9-88b0-719c2e9e7d1a.png)

Also verified that I can claim grant through `brave://rewards`
