### ISSUE TITLE
Speaker button on tabs should be hidden on pinned tabs

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#6358]
## Description 
Follow up for https://github.com/brave/brave-browser/issues/2025

## Steps to Reproduce

   1. Play a music video on YouTube or a music stream on your favorite site
   2. Pin the tab
   3. Try to switch to and from that pinned tab without muting tab

## Actual result:
Tab is accidentally muted because the click area is extremely tiny, since most of the hit box is for the mute button

## Expected result:
Should be able to switch to the pinned audio tab without muting

## Brave version (brave://version info)
0.69.x and higher

**Comment by bsclifton** [comment]
Related https://github.com/brave/brave-browser/issues/5837#issuecomment-539407431

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/remove-the-sound-icon-on-a-pinned-tab/94643?u=eljuno

**Comment by JoeriTheGreat** [comment]
+1 Really frustrating!!

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.2.41 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Ubuntu 18.04 LTS

Verified test plan from the description. Also verified that the speaker button is clickable on normal tabs.

![image](https://user-images.githubusercontent.com/34715963/71764581-cb392900-2ee9-11ea-9e57-0fbb9765e68a.png)

**Comment by saasseckin** [comment]
I was using that :( 
Is expanding pinned tab when you hover over it not an option? @bsclifton

**Comment by bsclifton** [comment]
@saasseckin I don't think so, unfortunately. But it will show `Mute Site` when you right click the pinned tab. Not as easy, but at least it's still possible

**Comment by Michael82548** [comment]
Please just add an option or flag to disable it in brave://flags

**Comment by snintendog** [comment]
> Please just add an option or flag to disable it in brave://flags

This should be a default for ALL Features no matter what.
