### ISSUE TITLE
Change text displayed during Ad earning claim process - follow up to 5578

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6359]
## Description 
Follow up to #5578 

Per discussion on slack, @mandar-brave and @jsecretan to provide the correct text to be displayed during the Ad earning claim process. This includes:
1. Text displayed on BAT logo Notification
2. Text displayed after captcha is correctly solved to claim Ad rewards from the panel/notification (issue #6357 was resolved in 0.70.115, screenshot added below)
3. Text displayed on claim banner on brave://rewards page
4. Text displayed after captcha is correctly solved to claim Ad rewards on brave://rewards page
5. Any other text that needs to be changed

See screenshots in https://github.com/brave/brave-browser/issues/5578#issuecomment-539538024

## Steps to Reproduce

   1. Set up ad earnings to be claimed
   2. Claim from panel/brave://rewards page to confirm that text is correct.
 

## Actual result:
1. Text displayed on BAT logo Notification
<img width="415" alt="1" src="https://user-images.githubusercontent.com/28145373/66417000-1320e080-e9cd-11e9-83ac-39ee4b227fc6.png">

2. Text displayed after captcha is correctly solved to claim Ad rewards from the panel/notification (issue #6357 was fixed)
<img width="396" alt="Screen Shot 2019-10-14 at 10 48 02 AM" src="https://user-images.githubusercontent.com/28145373/66760448-1e15be00-ee70-11e9-95dd-7d085894fba2.png">

3. Text displayed on claim banner on brave://rewards page
<img width="404" alt="3" src="https://user-images.githubusercontent.com/28145373/66417017-1e740c00-e9cd-11e9-9c3a-0862a091a8af.png">

4. Text displayed after captcha is correctly solved to claim Ad rewards on brave://rewards page
<img width="410" alt="4" src="https://user-images.githubusercontent.com/28145373/66417025-216efc80-e9cd-11e9-8b8f-2aac29c94781.png">

## Expected result:
TBD by @mandar-brave and @jsecretan 

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.70.110 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanml** [comment]
Update text provided

![image (9)](https://user-images.githubusercontent.com/8732757/66982886-0a36ab80-f06c-11e9-9050-5fb9649e1612.png)

**Comment by NejcZdovc** [comment]
@ryanml what about notification screen in the panel and on settings page? are they ok?

**Comment by bradleyrichter** [comment]
@NejcZdovc @mandar-brave @ryanml 

Corrected mockup:

![image](https://user-images.githubusercontent.com/13509546/67034998-9d53fd80-f0cd-11e9-9702-f7a1d7472ba6.png)

**Comment by LaurenWags** [comment]
`QA/Blocked` until we get a new build. Will be available in 0.71.107` and above.

**Comment by LaurenWags** [comment]
Removed `QA/Blocked` as build `0.71.107` is available.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

Brave | 0.71.108 Chromium: 78.0.3904.87 (Official Build) beta (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3729
  - Text displayed after captcha is correctly solved to claim Ad rewards from the panel/notification is displayed as mentioned in the https://github.com/brave/brave-browser/issues/6359#issuecomment-543024103
![image](https://user-images.githubusercontent.com/38657976/68107561-42af0400-ff0b-11e9-8d4f-4aa8cda0a590.png)
  - Text displayed after captcha is correctly solved to claim Ad rewards from the brave://rewards page is displayed as mentioned in the https://github.com/brave/brave-browser/issues/6359#issuecomment-543024103
![image](https://user-images.githubusercontent.com/38657976/68107984-7c343f00-ff0c-11e9-85a1-29acb3208d8b.png)
