### ISSUE TITLE
login credentials persists across private windows

### ISSUE THREAD

**Issue by jstefani** [brave/brave-browser#6360]
## Description 
Logging into an account (example: google account (gmail, youtube, etc.)) will persist across multiple private windows (not tabs). Appears to be as designed but I think users might expect that a new private window (not a new private tab in same window) would clear any cookie, etc. relating to logged in session in other private windows.

## Steps to Reproduce

   1. new private window
   2. login to account (google, etc.)
   3. verify logged in
   4. new private window
   5. go directly to a "logged in" page for that account (not the login page)

## Actual result:

private window #2 is logged into account from private window #1

## Expected result:

private window #2 request login credentials 

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)
Version 0.69.132 Chromium: 77.0.3865.90

## Other Additional Information:

same in chrome so likely as designed. still something which likely does not perform as a typical user may expect.

**Comment by rebron** [comment]
Closing out. This is working as designed.
