### ISSUE TITLE
Change maximum ads on Android/iOS to 20

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#6362]
## Description 
The maximum ads per day on Android/iOS should match desktop at 20.  This will allow users who are requesting greater ads rewards to see them.

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` label pending discussion about testing cc @kjozwiak

**Comment by LaurenWags** [comment]
Removing `QA/Blocked` label as we have received assistance from @tmancey on how to test this one.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.1.18 Chromium: 79.0.3945.56 (Official Build) (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified using file provided to QA and test plan shared with QA. If you need the test plan DM me.
