### ISSUE TITLE
Invalid memory access after WaitableEvent timed out

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#6367]
reopen https://github.com/brave/brave-browser/issues/6169
and extra crash reports
https://stats.brave.com/dashboard#crash/5d9ce39d13e758001f81da76
https://stats.brave.com/dashboard#crash/5d9cadeb997f1a001fb9b5fa

STR:
1. Open Brave with `--enable-logging`
2. Establish sync chain
3. Open `chrome://inspect#extensions`, make sure you see `"sync-debug" message="success"`
4. Make OS go offline
5. Monitor `chrome_debug.log` in user profile or console log from terminal until you see `[...WARNING:syncer.cc(37)] WaitableEvent timed out` (About 3-4 mins)
6. Make OS go online after seeing the step 5 message

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.69.134 Chromium: 77.0.3865.120 (Official Build) (64-bit)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3636

![image](https://user-images.githubusercontent.com/38657976/66629904-b3227800-ec20-11e9-8bb7-737c6a525fed.png)

![image](https://user-images.githubusercontent.com/38657976/66629876-9be38a80-ec20-11e9-9e24-a9c421563d96.png)


![image](https://user-images.githubusercontent.com/38657976/66629809-78b8db00-ec20-11e9-87d5-7ec28c51d8b5.png)
