### ISSUE TITLE
Brave should block extensions from being able to modify extensions.brave.com

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#637]
or whatever the hostname for https://github.com/AilinLiao/brave-extension-store is

chrome blocks chrome extensions from being able to modify/intercept content/requests on the chrome web store so that extensions cannot mess with installation of other extensions. we should do the same for the Brave extensions store.

**Comment by jumde** [comment]
This works as expected on `chrome`.

**Comment by bbondy** [comment]
Moving this to 1.0 since I don't know we'll even have an extensions.brave.com for 0.55.x. If we do have one though then this will be moved back into this milestone.

**Comment by bbondy** [comment]
Removing this from 1.0 project blockers because we don't have such a site yet.

**Comment by bsclifton** [comment]
Closing as https://github.com/brave/brave-browser/issues/28 has been closed. I linked to this issue in case we'd like to revive the work 😄
