### ISSUE TITLE
Brave Rewards widget for New Tab Page

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#6370]
## Description 
Add Brave Rewards widget on New Tabs page to add further usage and engagement of Brave Rewards. Users will be able to Turn on Brave Rewards and Ads if haven't already. Widget will also display current wallet amount as well as pending tips and contributions if users are opted into Brave Reward.

## Design
<img width="661" alt="Screen Shot 2019-10-08 at 8 10 31 PM" src="https://user-images.githubusercontent.com/5951041/66448926-17b6ba80-ea08-11e9-9118-21c5ece4fc00.png">

Additional screens to be added.

## Test Plan:
1. Build Browser from PR, navigate to `brave://newtab`
2. Confirm that Rewards widget is initially present and can be toggled on and off via the widget menu
3. Turn on Rewards via the widget
4. Confirm that initial tip/ads amounts are shown in the widget after Rewards is turned on
5. Confirm that Ads/Rewards can be toggled two ways between `brave://newtab` <-> `brave://rewards`
6. Resore your Rewards wallet via `brave://rewards` with a wallet that is set to receive a grant
7. Navigate to `brave://newtab`, wait and confirm that grant notification is shown
8. Dismiss notification, reload page and ensure it does not show again
9. With claimed grant funds, tip a fully connected and verified publisher
10. Confirm on `brave://newtab` after some time that monthly tip amount increments appropriately
11. Browse and serve yourself a Brave Ad
12. Confirm on `brave://newtab` after some time that ads estimated earnings increments correctly

**Comment by rebron** [comment]
@user1313 There will be a way to hide the Brave Rewards widget, similar to all the other New Tab page elements as you can do know in the current release 69.132.

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.71.111 Chromium: 78.0.3904.87 (Official Build) (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan mentioned in the description
![image](https://user-images.githubusercontent.com/38657976/68124691-ef9e7680-ff35-11e9-9545-ec58d3638a59.png)
![image](https://user-images.githubusercontent.com/38657976/68124848-4a37d280-ff36-11e9-8f80-c78ffe33d16c.png)
![image](https://user-images.githubusercontent.com/38657976/68125751-40af6a00-ff38-11e9-8901-e1da47c2ea23.png)

**Comment by Zoooook** [comment]
> @user1313 There will be a way to hide the Brave Rewards widget, similar to all the other New Tab page elements as you can do now in the current release 69.132.

This is the only New Tab page element that I do not have a way to hide. Did we forget that bit?
