### ISSUE TITLE
WebTorrent extension should be non-persistent

### ISSUE THREAD

**Issue by AndriusA** [brave/brave-browser#6372]
## Description 

Currently the WebTorrent extension loads when browser starts and remains persistently on, whether or not there are any torrents active. It could save ~20MB and a process if we make the extension non-persistent and subscribe it to a smaller subset of pre-filtered events that wake it up, letting the browser unload it when not in use.

## Steps to Reproduce

   1. Fresh profile
   2. Navigate to https://webtorrent.io/free-torrents
   3. Pick a magnet URL
   4. Repeat step 1-3 but with a .torrent file link
   5. Inspect Window > Task Manager for "Extension: Brave WebTorrent" task
   6. Close torrent tabs, inspect Task Manager until "Extension: Brave WebTorrent" task disappears (should be 10-20 seconds)

## Actual result:

Torrent loads, but process exists as soon as you open the browser with a fresh profile.

## Expected result:

Torrent still loads correctly, but process only starts once you load a torrent. Process disappears after closing all active torrent tabs.

## Reproduces how often: 

Always

## Brave version (brave://version info)

All versions

## Version/Channel Information:

Can you reproduce this issue with the current release? Yes
Can you reproduce this issue with the beta channel? Yes
Can you reproduce this issue with the dev channel? Yes
Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  No

## Miscellaneous Information:

This needs changing which events the extension subscribes to and subsequently the logic/data representation that currently relies on window and tab IDs.

**Comment by btlechowski** [comment]
Verified passed with

Brave | 1.2.8 Chromium: 78.0.3904.108 (Official Build) dev (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

Verified STR from the description
Verified Webtorrent extension is not launched on clean profile
Verified Webtorrent extension is launched after opening magnet link
Verified Webtorrent extension is launched after opening torrent link
Verified Webtorrent extension is unloaded when not in use
