### ISSUE TITLE
Bookmark import/export on Android 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6378]
## Description 

Bookmark import/export on Android is one of the most frequently requested feature that is missing. This is to bridge feature between desktop and mobile. It would be good to have this feature done for the first release or on the second. Having this feature allows users to export bookmarks and reinstall brave if they wish to.  

## Miscellaneous Information:

cc: @anthonypkeane @brave/android @bridiver

**Comment by srirambv** [comment]
Related issues https://github.com/brave/browser-android-tabs/issues/150

**Comment by srirambv** [comment]
+1 request from https://community.brave.com/t/bookmark-backup-support-missing/88224/2

**Comment by osakanwolf** [comment]
So in other words this will likely never be an option. Brave is just not ready to be taken seriously.

**Comment by bridiver** [comment]
I'm sorry that you don't think Brave is ready to be taken seriously because we didn't want to exactly copy Chrome's unusual bookmark structure. Brave may be based on Chromium, but we have no intentions of just being a Chrome clone.

**Comment by bridiver** [comment]
> So in other words this will likely never be an option. Brave is just not ready to be taken seriously.

What is it about a ticket being opened by a Brave employee to fix this issue makes you think this is not likely to ever be an option? The beta version of the android app ported to brave-core isn't even available yet.

**Comment by bridiver** [comment]
If we had no intentions of implementing this we would close it as "won't fix", not open a new ticket for brave-core. There are a limited number of resources to implement features and things have to be prioritized. If enough users were asking for this I guarantee the priority would be bumped up. If you don't think other browsers like Chrome have very old tickets that a lot of users are asking for then you haven't spent enough time looking at them. We're also happy to look at contributions for this functionality.

**Comment by Dreamulet** [comment]
Came upon this thread when I was searching how to export my bookmarks from Brave which I just downloaded.  And thought I should save my bookmarks while I'm at it.  I couldn't find the answer, so I went back over to Chrome to save them and thought I should try the same location for Brave and it was!  So just click on the 3 lines for drop down menu in the upper right hand corner, click bookmarks>Bookmark manager.  Then click the 3 dots on the right top area and there it is! import and export along with a few other things.  Y'all probably figured this out already.  But I wanted to post this comment for anyone new coming over as I still didn't quite see this answer.  Hope this helps!

**Comment by srirambv** [comment]
@Dreamulet your steps are for Desktop. This issue is for Android browser where we currently don't have import/export option

**Comment by Dreamulet** [comment]
> @Dreamulet your steps are for Desktop. This issue is for Android browser where we currently don't have import/export option

Oh ok, thanks for the clarification.  (I did wonder that, after I posted of course :)

**Comment by sdkane** [comment]
Is there a method to manually extract the bookmarks using adb? This could work as an immediate holdover.

**Comment by sigfreud** [comment]
> If we had no intentions of implementing this we would close it as "won't fix", not open a new ticket for brave-core. There are a limited number of resources to implement features and things have to be prioritized. If enough users were asking for this I guarantee the priority would be bumped up. If you don't think other browsers like Chrome have very old tickets that a lot of users are asking for then you haven't spent enough time looking at them. We're also happy to look at contributions for this functionality.
> […](#)
> On Jan 10, 2020, at 3:55 AM, Osakan Wolf ***@***.***> wrote: ﻿ @bridiver Probably due to the fact this has been an issue or request since 2017 from another thread/issue (whatever). I don't make a habit of trolling github. I have been however, patiently waiting over 1.5 years while using this browser, alot. How long should I keep waiting my dears, until I just use Firefox? I mean Brave is terrible on MXLinux which I use on desktop, but that's another story. In the meantime, I and others are devising slow workaround methods to manage bookmarks. Some have given up and moved on. These issues lead me to believe they/you/whomever aren't serious or don't care to implement this feature. Forgive me if I'm overlooking something obvious that would reason not to have this feature on browsers since like 1987. Therefore, I can't take Brave seriously until this. I appreciate you enjoy working on your project and maybe I'm sorry I feel this way. I guess now I need to apologize that I may have hurt your/his/their feelings about this issue. I won't. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
Not enough users are asking for this feature because nobody is using brave. At least to the last users give us a way to take with us our precious bookmarks, please.

**Comment by listsatjanirnet** [comment]
No one is asking for a special implementation. Just point out where and how we can extract our bookmarks from Brave android app as we can retrive bookmarks until Sync is fixed. I went nearly 4 months of saving bookmarks  on my phone before I reailzed they were no longer being synced. I have way too many to be able to sort out old ones from whats new on my phone b4 recording them. There are more of u out here that just need some guidance as to how to extra them from the phone.

**Comment by grossetti** [comment]
This would be great to have as a workaround for the sync issue; I am sure it is quicker to implement than it is to fix sync :).

I have a dying phone and I realized sync no longer works (even after installing the latest versions on Android and PC and re-enabling sync). I just want to be able to export my bookmarks so this would be great. At this point I am also open to workarounds.

Thanks!

**Comment by artella-coding** [comment]
With large numbers of bookmarks I have found sync slow and sometimes unreliable. It would be great if we could either export or atleast access the bookmark file on android (right now I think it is located in the data folder, which can only be accessed on a rooted phone). I agree with @grossetti that all this must be easier to implement than ironing out all the issues with sync, which people have been working on for a long time. Thanks

**Comment by k-kruglov** [comment]
Please, make it happen. There's no sync, at least let us import/export bookmarks on android.

**Comment by grossetti** [comment]
Sync is starting to work for me, please see here:
https://community.brave.com/t/how-does-brave-sync-work/122117/8

**Comment by Poopooracoocoo** [comment]
Bromite has a patch for this: https://github.com/bromite/bromite/blob/master/build/patches/Add-bookmark-import-export-actions.patch

**Comment by NM-E** [comment]
Very surprised to see there is no offline bookmark/import export option in any major android browsers except Bromite...

**Comment by shadow-42** [comment]
Bookmarks stuck in Brave Android and can't sync out.  Possible fix is to enable the ability to do ADB Backup, easy fix for developer: it is required to set android:allowBackup to true in the AndroidManifest.xml.

**Comment by Poopooracoocoo** [comment]
just another reminder that bromite has a patch for this that brave can easily integrate. it's been MORE THAN A YEAR since this issue was created and many more years since we've been asking for it.

**Comment by bridiver** [comment]
@Poopooracoocoo that patch would require significant changes to be integrated into Brave. Chromium patches have a real cost associated with them and at times they've held us back from keeping up with upstream releases that contain important security fixes. We very tightly control what gets patched and how. As one of the patch reviewers, there is absolutely no way I could approve that patch as-is. It would create far too much of a burden on our chromium update team who already have a difficult job keeping up with upstream changes. That doesn't mean that export couldn't be implemented in a way that didn't require such extensive patching, but just pulling that patch into Brave is not a viable option.

**Comment by Poopooracoocoo** [comment]
Thank you very much for the response.

**Comment by natevw** [comment]
The comment at https://github.com/brave/brave-browser/issues/6378#issuecomment-688038508 could be a possible easier fix for the Brave developers? I.e. if Brave allowed `adb backup` the community could probably find a way to extract the bookmarks manually.

There's a similar request at https://community.brave.com/t/allow-application-adb-backup/88060 as well even specifically mentioning this use case.

**Comment by p3yot3** [comment]
I simply can't believe that I can't import/export bookmarks with this browser - WTF? I mean, it's supposed to be a browser, isn't it?

**Comment by tp0** [comment]
> I simply can't believe that I can't import/export bookmarks with this browser - WTF? I mean, it's supposed to be a browser, isn't it?

You are implying as if it was common to have this feature. HTML file import/export has never been standard feature of mobile browsers.

I can name just two mobile browsers that have it. The aforementioned Bromite and one other Chromium fork (probably Kiwi Browser, not even sure).

**Comment by p3yot3** [comment]
More than two. Anyway, without the import/export feature it's a no-go for me - Bromite it is then. Installed & imported my bookmarks in minutes. Easy.
If Brave implement it, I might consider trying it again.

**Comment by SergeyZhukovsky** [comment]
Just to reiterate so everyone is on the same page and I hope agreed with a current statement:
1. Brave on Android cannot just pull bookmarks from Chrome on Android. Why? As they don't store them on a device, they don't provide any export on mobile for that from a browser.
2. It's possible to export to a file from Chrome on a laptop/desktop.
3. It's possible to export to a file using that service https://takeout.google.com/settings/takeout?pli=1. Where you can pick Chrome and pick bookmarks. You have to be signed in with your gmail account there.

We can do a functionality to import from the provided file. Is that what everyone wants?
