### ISSUE TITLE
Manual test run on Linux for Ethereum Remote Client

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6384]
- [x] ensure that you can create a new wallet without any issues
- [x] ensure that you can restore a previous CW wallet without any issues
- [x] ensure that you can restore a previous MM wallet without any issues
- [x] ensure that you can create a transaction (sending crypto) with a CW wallet
- [x] ensure that you can create a transaction (sending crypto) using a restored MM wallet

**Comment by srirambv** [comment]
Looks good
