### ISSUE TITLE
Hover card shows chrome:// on brave:// pages (C78)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#6385]
## Description 
With Chromium 78, hover cards are enabled by default. When you move the mouse over a tab, it shows a bubble which has the title and some text.

When viewing brave:// pages, it'll show `chrome://` in the hover card.

Related: https://github.com/brave/brave-browser/issues/1973 and https://github.com/brave/brave-browser/issues/3545

## Steps to Reproduce
   1. Use a build which has Chromium 78
   2. Have a few tabs open
   3. Move your mouse over the different tabs

## Actual result:
<img width="606" alt="Screen Shot 2019-10-09 at 11 12 58 AM" src="https://user-images.githubusercontent.com/4733304/66509453-eda4dd00-ea87-11e9-8372-c3adb3e586dc.png">

## Expected result:
URL shown should be `brave://settings`

## Reproduces how often: 
100%

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.70.119 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified STR from description
* Verified test plan from https://github.com/brave/brave-core/pull/3687
* Verified for several brave:// pages (settings, bookmarks, history, rewards, downloads, crypto wallet, etc)
<img width="603" alt="Screen Shot 2019-10-21 at 9 46 41 AM" src="https://user-images.githubusercontent.com/28145373/67211004-07c7af00-f3e8-11e9-840b-8fd68304a07e.png">
<img width="574" alt="Screen Shot 2019-10-21 at 9 46 48 AM" src="https://user-images.githubusercontent.com/28145373/67211011-09917280-f3e8-11e9-8b48-808fb05a2843.png">
<img width="817" alt="Screen Shot 2019-10-21 at 9 47 58 AM" src="https://user-images.githubusercontent.com/28145373/67211017-0d24f980-f3e8-11e9-85bf-987524dbec78.png">
