### ISSUE TITLE
Cannot open GMail conversation <In new window>

### ISSUE THREAD

**Issue by rokahn** [brave/brave-browser#6388]
## Description 
In Brave for Windows, cannot open Google Mail (GMail) links "In new window" (requested window doesn't open).

## Steps to Reproduce
   1. Open conversation in GMail
   2. In conversation upper-right corner, activate control "In new window"

## Actual result:
Nothing happens

## Expected result:
This should open conversation in a new browser window

## Reproduces how often: 
Always reproduces

## Brave version (brave://version info)
Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit) 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1903 (Build 18362.356)

- Can you reproduce this issue with the current release? YES

**Comment by rebron** [comment]
Hi @rokahn, can you screenshot what you're looking at? I'm in Gmail now and I'm not sure what you're referencing "In conversation upper-right corner, activate control "In new window"

**Comment by rokahn** [comment]
Here's a screenshot indicating the location of the "In new window" control
![in new window](https://user-images.githubusercontent.com/6007576/66595021-fad8cf00-eb4e-11e9-9737-f278e5ed9ba5.png)

**Comment by rokahn** [comment]
The function now works. I'm unsure when/how but Brave now allows this control to open a new browser window. I'll close the issue.
