### ISSUE TITLE
global shields setting for blocking all cookies isn’t being applied

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6389]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/5740

If you change your default shield setting for cookies to be `Block all cookies` it does not work. Shields show `Cookies Blocked` but not all cookies are being blocked.

Note - default value of `Only block cross-site cookies` and `Allow all cookies` both work as the global setting.

This was working with 0.68.132 (last released C76 version). It appears to be broken with 0.68.138 (first released C77 version) and later versions.

## Steps to Reproduce

1. Install a C77 version (0.68.138 on release channel or newer)
2. Go to settings, change default shield setting to 'Block all Cookies'
3. Open a new tab, go to http://www.whatarecookies.com/cookietest.asp
4. Page says cookies are Enabled.
5. Open shields, shields shows 'Cookies Blocked'
6. Change to 'Cross-site cookies blocked'
7. Page refreshes, still shows cookies Enabled.
8. Open shields, change back to 'Cookies Blocked'
9. Now page shows cookies are Disabled.

## Actual result:
Step 4, page shows cookies Enabled
<img width="1194" alt="Screen Shot 2019-10-09 at 4 17 31 PM" src="https://user-images.githubusercontent.com/28145373/66517023-543df100-eab0-11e9-971f-776b0fcdfd30.png">

If I click on 'Not Secure' in URL bar, it shows 2 cookies:
<img width="1190" alt="Screen Shot 2019-10-09 at 4 23 35 PM" src="https://user-images.githubusercontent.com/28145373/66517524-450b7300-eab1-11e9-92c3-c0740b234b06.png">

## Expected result:
Page should show cookies are Disabled.
<img width="1194" alt="Screen Shot 2019-10-09 at 4 18 26 PM" src="https://user-images.githubusercontent.com/28145373/66517098-7e8fae80-eab0-11e9-8f5b-03ec8e9a23bc.png">

<img width="1195" alt="Screen Shot 2019-10-09 at 4 24 50 PM" src="https://user-images.githubusercontent.com/28145373/66517556-56ed1600-eab1-11e9-8a35-6243371a4715.png">

## Reproduces how often: 
easily

## Brave version (brave://version info)
reproduces on 0.68.138

also reproduces with

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

Brave | 0.70.111 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

Brave | 0.72.83 Chromium: 77.0.3865.90 (Official Build) nightly (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes 
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel?  yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @brave/legacy_qa @rebron

**Comment by btlechowski** [comment]
Reproduced on

Brave | 0.70.111 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

**Comment by bsclifton** [comment]
Root cause / fix might be similar to https://github.com/brave/brave-core/pull/3405
cc: @bridiver

**Comment by GeetaSarvadnya** [comment]
Reproduced on


Brave | 0.70.112 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.70.118 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified STR from description, on step 4 page showed cookies as 'Disabled' as expected.
<img width="1192" alt="Screen Shot 2019-10-17 at 12 20 58 PM" src="https://user-images.githubusercontent.com/28145373/67028074-b910d100-f0d8-11e9-8f8c-aff99f6512bf.png">
<img width="1196" alt="Screen Shot 2019-10-17 at 12 20 40 PM" src="https://user-images.githubusercontent.com/28145373/67028079-bb732b00-f0d8-11e9-9cfb-7871d7b89706.png">
