### ISSUE TITLE
Tor process is gone when close and reopen a Tor window.

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#6390]
## Description 
This is a bug caused by https://github.com/brave/brave-core/pull/3597/commits/882c011fa7430a9add84fcf44cde8e3b303402f8.
With this commit, Tor process will be killed when we close all tor windows, and it won't be relaunched if we create one again.

Before the above commit, we're creating separate TorProfileService instances for dummy regular Tor profile and its incognito Tor profile, so Tor process is killed only when the last one, the dummy Tor regular profile, is shutting down when closing the browser.
Before Tor profile rework, Tor process is only shutting down when closing the browser too because the guest profile is shutting down when closing the browser too.

This issue is to fix the Tor process relaunch bit when you close and reopen tor windows.
We should kill Tor process when no Tor window is opened, and relaunch Tor process when the user open a Tor window again.

## Steps to Reproduce
   1. Open a Tor window and close it.
   2. Open a Tor window again.
   3. Visit https://check.torproject.org/

## Actual result:
<img width="639" alt="Screen Shot 2019-10-09 at 1 26 17 PM" src="https://user-images.githubusercontent.com/4730197/66517673-66ac3080-ea98-11e9-8598-b0fa6ed39190.png">

## Expected result:
The page should be shown normally.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
Nightly (0.72.x)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.72.110 Chromium: 78.0.3904.70 (Official Build) dev (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

Verified test plan from the description.
Verified that tor process is closed when tor window is closed. 
Verified that tor process is opened when tor window is opened.
