### ISSUE TITLE
Dark mode does not work for the new tab Remove menu

### ISSUE THREAD

**Issue by cndouglas** [brave/brave-browser#6395]
## Test plan
See https://github.com/brave/brave-core/pull/4423

## Description 
Follow up to #5014

The new tab Remove menu does not work with dark mode.

## Steps to Reproduce
   1. Open Settings and set `Brave colors` to `Dark`.
   2. Open the new tab page and click one of the drop down buttons next to one of the new tab page elements.

## Actual result:
The menu is light even when dark mode is enabled.
![](https://user-images.githubusercontent.com/19424103/66532667-beb55800-ead5-11e9-8022-3a2f00c62e4d.png)

## Expected result:
The menu should be dark, like the settings popup.
![](https://user-images.githubusercontent.com/19424103/66532743-22d81c00-ead6-11e9-893e-8a31004c4734.png)

## Reproduces how often: 
Always.

## Brave version (brave://version info)
Brave | 0.72.83 Chromium: 77.0.3865.90 (Official Build) nightly (64-bit)
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.15 (Build 19A583)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? Yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Not applicable.
- Does the issue resolve itself when disabling Brave Rewards? Not applicable.
- Is the issue reproducible on the latest version of Chrome? Not applicable.

## Miscellaneous Information:

**Comment by rebron** [comment]
@cezaraugusto Can you take a look?

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.7.65 Chromium: 80.0.3987.132 (Official Build) dev (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4423

Light theme

![image](https://user-images.githubusercontent.com/34715963/77010594-6464d100-696a-11ea-94d3-885f74b59c38.png)
![image](https://user-images.githubusercontent.com/34715963/77010541-44cda880-696a-11ea-929e-75ca3b9d3e0a.png)
![image](https://user-images.githubusercontent.com/34715963/77010559-4d25e380-696a-11ea-8dbd-1db47a73102c.png)
![image](https://user-images.githubusercontent.com/34715963/77010568-51ea9780-696a-11ea-9400-5e095ced4aad.png)
![image](https://user-images.githubusercontent.com/34715963/77010827-d9d0a180-696a-11ea-98bd-cea5cc1e3224.png)

Dark theme
![image](https://user-images.githubusercontent.com/34715963/77010693-924a1580-696a-11ea-97e9-52248dfb257e.png)
![image](https://user-images.githubusercontent.com/34715963/77010704-99712380-696a-11ea-8f88-92fe9e539c37.png)
![image](https://user-images.githubusercontent.com/34715963/77010718-9fff9b00-696a-11ea-9565-5e842836d04d.png)
![image](https://user-images.githubusercontent.com/34715963/77010725-a55ce580-696a-11ea-9a2e-6e92dba2b614.png)
![image](https://user-images.githubusercontent.com/34715963/77010784-c9202b80-696a-11ea-9480-8568f5b27349.png)
