### ISSUE TITLE
Pull recent small fixes from Android old repository

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#6407]
Check on that link what we need to port:
https://github.com/brave/browser-android-tabs/pulls?page=1&q=is%3Apr+author%3Adeeppandya+is%3Aclosed

(Note: Below does not covers all PRs from above link, just ones that I already checked.)

Not yet ported:
- Update icons for http status
- Update check for X86 devices for BAT icon
- creating NTP automatically when last tab is closed and "Closing all tabs closes Brave" is disabled
- new tab context menu always dark
- Update share option in settings

Already ported:
- Update text color for brave rewards.
- Update UI for dark mode
- Create setting to manually enable Dark Mode
- Update dark mode color for brave rewards grant panel
- Replay Welcome Tour back button
- Dark Mode / Light Mode / Private
- Move "Close last tab closes Brave" in settings
- Android onboarding
- Move "Close last tab closes Brave" in settings (https://github.com/brave/browser-android-tabs/pull/1974)
- Refactor warn message on for sync (https://github.com/brave/browser-android-tabs/pull/1958)
- Remove hard shadow from brave rewards popup panel (https://github.com/brave/browser-android-tabs/pull/1956)
- Video background play options (https://github.com/brave/browser-android-tabs/pull/1785)

**Comment by emerick** [comment]
Currently working on:
- Make DDG the default search engine in the following new countries (https://github.com/brave/browser-android-tabs/pull/2058)

Finished:
- _None yet_

**Comment by yrliou** [comment]
Currently working on:
- TBD
Finished:
- Issue-1495 Remove 'Set as default browser' from the settings menu (https://github.com/brave/browser-android-tabs/pull/1734); Already covered by https://github.com/brave/brave-core/pull/3724

**Comment by SergeyZhukovsky** [comment]
That is done mostly. @gdregalo has a list of rewards issues and I ported everything not rewards related.

**Comment by SergeyZhukovsky** [comment]
Closing that issue as related tasks and issues are pulled from the old repo.
