### ISSUE TITLE
Sync consider merge bookmark folders

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#6409]
## Description 

Currently, if deviceA and deviceB have the bookmark folders with the same name, it will be duplicated after the sync chain creation. 
Maybe we should merge the same folders to avoid the duplication.

## Steps to Reproduce

   1. Create bookmark folder `FolderA` and the bookmark `A.com` inside on the device A
   2. Create bookmark folder `FolderA` and the bookmark `B.com` inside on the device B
   3. Establish the sync chain and wait for syncing to complete
  
## Actual result:

   Two duplicating folders `FolderA` on each device.

## Expected result:
Maybe it is better to have them merged into a single `FolderA`

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @anthonypkeane Is this something we want to do? If we're merging duplicate folders we run into the issue of bookmark ordering.

**Comment by anthonypkeane** [comment]
Not right now, we can leave the folders as duplicated.
Merging these folders is messy as we'll have a bigger problem with duplicate bookmarks and ordering as you say @rebron 

@AlexeyBarabash what naming structure do we use for duplicate folders? Do the folder names have to be unique? If **No**, duplicate the folders and keep the name the same.

**Comment by AlexeyBarabash** [comment]
@anthonypkeane 
No, folder names don't have to be unique, duplicates are allowed.

Understand, thanks, so closing this issue.
