### ISSUE TITLE
Please let us install WebAPKs (PWAs) like Chrome is able to do on Android

### ISSUE THREAD

**Issue by szaimen** [brave/brave-browser#6412]
Please let us install WebAPK (PWAs) like Chrome is able to do on Android:
So e.g. when I visit web.telegram.org with brave android, I get asked, whether I want to install it and if I click okay, it gets automatically added to the app-drawer and I also can uninstall it like a normal app, etc.
Currently it doesn't work in brave for android: https://github.com/brave/browser-android-tabs/issues/645

**Comment by srirambv** [comment]
Once we move to Android-core we will go through the list of open issues and port them over here which will be implemented.

**Comment by srirambv** [comment]
Closing in favour of #7357. @szaimen lets use the other issue for tracking
