### ISSUE TITLE
CFBundleIdentifier should be unique for each channel on OSX

### ISSUE THREAD

**Issue by RyanJarv** [brave/brave-browser#642]
## Description 
From what I recall (will follow up with sources) problematic issues can come up if two apps have the same `CFBundleIdentifier` value.

## Steps to Reproduce
   1. Install the dev build
   2. Install the beta build (unavailable currently)

## Actual result:
`CFBundleIdentifier` is set to `org.brave.Brave` for both dev/beta builds

I suspect it may also be causing this issue:
* https://github.com/brave/brave-browser/issues/469

## Expected result:
`CFBundleIdentifier` is different for the dev and beta builds

## Brave version (about:brave info) 
master branch

### Additional Information
Needs updating:
* Brave.app Info.plist
  * https://github.com/brave/brave-core/blob/775ab495e2f88a04890d4c8f760f5330edb03211/BUILD.gn#L320
* codesign requirements arg during app signing
  * https://github.com/brave/brave-core/blob/41e2cab673447bb9aa5bb2c4cbada91c456186f3/patches/chrome-installer-mac-sign_app.sh.in.patch#L19

**Comment by simonhong** [comment]
I think I fixed this by https://github.com/brave/brave-core/pull/298/commits/94b48944ce33d897a660a12ad05fbc2fd2f1dcd1
