### ISSUE TITLE
Browser crash when new private window is opened in German locale

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6421]
Found while testing https://github.com/brave/brave-browser/issues/6187

## Steps to Reproduce

   1. Set system locale to German/Germany
   2. Clean profile
   3. Open New private window

## Actual result:

Crash

Uploaded Crash Report ID ad9fefcf0c82c402 (Local Context: 81524cdd-7e63-4ba4-bc71-e3bb80e51514)
Uploaded Crash Report ID a28ccf2265fd35b3 (Local Context: e58dd7e4-0be4-4804-97ed-5422b23bd0ff)

## Expected result:
No Crash

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.70.112 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1903 (Build 18362.175)

Brave | 0.70.112 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

cc @brave/legacy_qa @rebron @bsclifton

**Comment by bsclifton** [comment]
Great catch - looking into this now... Should be able to provide a fix tonite

**Comment by LaurenWags** [comment]
Applies to Tor and Guest windows as well, we need to check them as well when verifying this issue.


Brave | 0.70.115 Chromium: 77.0.3865.90 (Offizieller Build) beta (64-Bit)
-- | --
Überarbeitung | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
Betriebssystem | macOS Version 10.13.6 (Build 17G5019)

**Comment by GeetaSarvadnya** [comment]
The issue is Reproducible in windows 10 x64 - 0.70.113 - Open PT/TOR/Guest windows crashes the browser

**Comment by bsclifton** [comment]
@GeetaSarvadnya new beta has been released which has the fix, if you wanted to give it a go 😄

**Comment by GeetaSarvadnya** [comment]
@bsclifton Sure! Thanks for the update

**Comment by GeetaSarvadnya** [comment]
@bsclifton Issue is still reproducible in 0.70.116 for US locale, Checking other locales.

**Comment by LaurenWags** [comment]
I couldn't reproduce for US/UK locales, but I did reproduce crashes with:
Germany (Tor window only)
Australia (Private/Guest/Tor windows)
New Zealand (Private/Guest/Tor windows)
Ireland (Tor window only)

Logged follow up issue: https://github.com/brave/brave-browser/issues/6476 with crash report IDs in that issue.

**Comment by LaurenWags** [comment]
Since issue is still occuring, marking as `QA/No`. Will be retested with new issue 6476.
