### ISSUE TITLE
Forced ads on autobild.de

### ISSUE THREAD

**Issue by szaimen** [brave/brave-browser#6422]
visit this link with enabled adblocker: `https://www.autobild.de/artikel/vw-golf-8-2020-premiere-15733047.html`
it looks like this:
![image](https://user-images.githubusercontent.com/42591237/66610431-d23aee80-ebbb-11e9-97b0-16006e023aaa.png)
but there shouldn't be any ads.

Sry for reporting this, but rightclicking on the ad -> select "brave" -> select "block via selector" doesn't work.

BTW: the same applies to spiegel.de but I think you are aware of this.

**Comment by srirambv** [comment]
The images are from first party hence not blocked. 

cc: @ryanbr

**Comment by szaimen** [comment]
I tried the link again with cosmetic blocking enabled and it still shows first party ads. Is there something I am missing?

**Comment by bsclifton** [comment]
@szaimen I don't think first party ads are removed

cc: @antonok-edm @snyderp for confirmation

**Comment by ryanbr** [comment]
Somehow I missed this ticket, plenty of the german sites are using common Anti-adscripts, this will fix it.
