### ISSUE TITLE
C78 buttons, tabs and Location Bar have lost brave-style corners

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#6426]
## Description 

C78 update has caused a layout regression. Toolbar buttons, tabs and Location Bar now have chromium-style border radius and not brave-style.

## Steps to Reproduce

   1. Open a Brave window
   2. Observe the Location Bar, and hover state on toolbar buttons

## Actual result:

![image](https://user-images.githubusercontent.com/741836/66624068-6a78a980-eba3-11e9-9eee-3349e4a0a863.png)

## Expected result:
![image](https://user-images.githubusercontent.com/741836/66624082-7bc1b600-eba3-11e9-8e0d-f0ec16c91902.png)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Version 0.72.90 Chromium: 78.0.3904.50 (Official Build) nightly (64-bit)

## Version/Channel Information:

Only C78

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.70.119 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified STR from description
<img width="1198" alt="Screen Shot 2019-10-21 at 11 44 34 AM" src="https://user-images.githubusercontent.com/28145373/67220869-8c222e00-f3f8-11e9-843a-77dfd026e0b7.png">
<img width="1191" alt="Screen Shot 2019-10-21 at 11 45 15 AM" src="https://user-images.githubusercontent.com/28145373/67220876-8d535b00-f3f8-11e9-8f66-dfa3e0ce26b0.png">

**Comment by srevinsaju** [comment]
I dunno if its okay to ask. :sweat_smile: , but is it possible to make Brave look like this?

![Image](https://user-images.githubusercontent.com/741836/66624068-6a78a980-eba3-11e9-9eee-3349e4a0a863.png)

not by default, but as a per user configuration? Or is it set at build time?

**Comment by LaurenWags** [comment]
@srevinsaju if you're on desktop and you go to brave://settings/newTab, there is a "New tab page shows" option. You can change that to "Blank page". If you are on dark theme it will make your new tab show like this:

<img width="1036" alt="Screen Shot 2021-01-25 at 7 21 30 AM" src="https://user-images.githubusercontent.com/28145373/105705264-f835f080-5edd-11eb-8443-7a51301692cf.png">

**Comment by srevinsaju** [comment]
Oh oops, I mean, the `border-radius`. I wanted to know if I could increase brave's border radius so that it looks more like chrome :sweat_smile:

**Comment by LaurenWags** [comment]
ah, gotcha @srevinsaju. I don't believe we have any such setting. cc @rebron

**Comment by srevinsaju** [comment]
It would be nice to have any type of configuration, like editing a css file, or a `brave://flags`, except building brave from sources. (wishlist :sparkles: )
