### ISSUE TITLE
unable to use 'sign up with google on any website'

### ISSUE THREAD

**Issue by ishank-dev** [brave/brave-browser#6431]
## Description 

Web apps cannot be logged into using Brave if the user uses a Google account for it's login. Selecting the "Sign up with Google" option offered on the pages like skillenza.com or https://www.geeksforgeeks.org/, results in a separate window being launched, which asks for choosing the google account for sign up, after clicking on one of the accounts message displays 'one moment please' and then the popup window closes without signing up with google.
In Chrome/Firefox: selecting "Sign Up in with Google" opens a separate window in which active Google accounts are displayed as a list, and an appropriate set of credentials can be selected. The window then closes and loading of the web app as a logged in user .

## Steps to Reproduce

   1. Navigate to https://skillenza.com/
   2. Click 'login' or 'get started'
   3. Select connect with Google

## Actual result:

Pop up window closes right after choosing the appropriate account

## Expected result:
Pop up window closes and page should reload as a logged in user

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by srirambv** [comment]
Probably due to third party cookies being blocked. Can you try enabling `Allow all cookies` on the site via shields and check?

**Comment by ishank-dev** [comment]
Cool it worked!
Thanks a lot :+1:

**Comment by bsclifton** [comment]
cc: @jumde (similar to the other Google sign in issues; such as https://github.com/brave/brave-browser/issues/5869)
