### ISSUE TITLE
Sync failed DCHECK crash on initialization after Chromium update 78

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#6435]
## Description 

Starting with version `Version 0.72.89 Chromium: 78.0.3904.50 (Developer Build) (64-bit)` browser crashes right after enabling sync if there is any created bookmark .

## Steps to Reproduce

   1. Get a clean profile
   2. Create bookmark A1.com
   3. Go to `brave://sync`
   4. Create sync chain and wait

## Actual result:

Failed DCHECK crash  with stack of
```
[25896:25896:1011/171732.684433:INFO:syncer_helper.cc(105)] [BraveSync] AddBraveMetaInfo 000 node=A1.com
[25896:25896:1011/171732.684490:INFO:syncer_helper.cc(106)] [BraveSync] AddBraveMetaInfo stack=#0 0x7f1eb69dad8f base::debug::CollectStackTrace()
#1 0x7f1eb671662d base::debug::StackTrace::StackTrace()
#2 0x7f1eb67165e8 base::debug::StackTrace::StackTrace()
#3 0x55c65f7a500e brave_sync::AddBraveMetaInfo()
#4 0x55c66510f1b2 sync_bookmarks::BookmarkChangeProcessor::UpdateSyncNodeProperties()
#5 0x55c665110b21 sync_bookmarks::BookmarkChangeProcessor::CreateSyncNode()
#6 0x55c665122742 sync_bookmarks::BookmarkModelAssociator::BuildAssociations()
#7 0x55c665120ad2 sync_bookmarks::BookmarkModelAssociator::BuildAssociations()
#8 0x55c665120017 sync_bookmarks::BookmarkModelAssociator::AssociateModels()
#9 0x55c665117f7f syncer::FrontendDataTypeController::Associate()
```

## Expected result:
No crash and sync works

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.72.89 Chromium: 78.0.3904.50 (Developer Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?
Only on Nightly

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 
NA

## Miscellaneous Information:

NA

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.118 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3681
No crash.
