### ISSUE TITLE
Migrate brave sync to USS bookmarks

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#6437]
https://www.chromium.org/developers/design-documents/sync/unified-sync-and-storage-overview

https://chromium.googlesource.com/chromium/src/+/8554331912828c09f8a26a33ddd52d7838f722b0
is landed in C78 which causes our bookmarks sync doesn't work
(https://github.com/brave/brave-browser/issues/6435 which will be addressed by [workaround](https://github.com/brave/brave-core/pull/3681/) adding `kSyncUSSBookmarks` to disable feature list in `BraveMainDelegate`)

We have to prepare for the case before `BookmarkChangeProcessor` and  `BookmarkModelAssociator` and other related things will be completely deprecated

**Comment by darkdh** [comment]
According to https://bugs.chromium.org/p/chromium/issues/detail?id=933756
They will be removed in 80.0.3947.0

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.110 Chromium: 80.0.3987.78 (Official Build) (64-bit)
-- | --
Revision | cb5aa81cb0a3a2c674b93bc7ffb34a86cd3b4802-refs/branch-heads/3987@{#752}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4324#issue-360251085
Also test by switching the devices.

[Pass] Add (1)
[Pass] Add with existing bookmarks (2)
[Pass] Add with same order (3)
[Pass] Move
[Pass] Modify
[Pass] Reorder (1)
[Pass] Reorder (2)
[Pass] Delete
[Pass] Migration/Upgrade - Verified Move, Delete, Modify, Reorder(1), Reorder(2)
