### ISSUE TITLE
Massive Performance Issues On Latest Nightly Build (MacOS)

### ISSUE THREAD

**Issue by theowenfarmer** [brave/brave-browser#6439]
## Description 

Browser constantly freezes and pages fail to load very frequently.

## Steps to Reproduce

   1. Open Brave Nightly
   2. Use Browser
   3. Experience Performance Hit

## Actual result:

Freezing, major performance issues.

## Expected result:
The regular browser experience(?).

## Reproduces how often: 

Every 5-10 seconds.

## Brave version (brave://version info)

Brave | 0.72.90 Chromium: 78.0.3904.50 (Official Build) nightly (64-bit)
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | macOS Version 10.14.6 (Build 18G59b)

## Version/Channel Information:

- Can you reproduce this issue with the current release? - No
- Can you reproduce this issue with the beta channel? - No
- Can you reproduce this issue with the dev channel? - No
- Can you reproduce this issue with the nightly channel? - Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? - No
- Does the issue resolve itself when disabling Brave Rewards? - No
- Is the issue reproducible on the latest version of Chrome? - No

## Miscellaneous Information:

I have no extra extensions installed, Shield enabled, Rewards enabled.

**Comment by jsecretan** [comment]
@theowenfarmer can you right click on the top bar of your browser, select "Task Manager" and include the output of that?  Thanks!

**Comment by bsclifton** [comment]
Closing as there hasn't been any updates (yet)

@theowenfarmer if you're still experiencing this, let's re-open and include a snapshot of the task manager. It should look something like this:
<img width="510" alt="Screen Shot 2019-10-30 at 11 00 38 PM" src="https://user-images.githubusercontent.com/4733304/67922810-1e4cd380-fb69-11e9-9acf-f3f5124d6cb8.png">

It's in the hamburger menu under `More Tools` => `Task Manager`
<img width="555" alt="Screen Shot 2019-10-30 at 11 01 16 PM" src="https://user-images.githubusercontent.com/4733304/67922918-623fd880-fb69-11e9-98d7-864df055c709.png">
