### ISSUE TITLE
Expose Brave UA String via navigator.userAgent on select origins

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#6441]
## Description 
Brave currently exposes a custom user agent string in the HTTP request headers for select domains. This does not, however, change the value stored in `navigator.userAgent` for those same origins.

https://github.com/brave/brave-core/blob/66ceaf3491778f7d9a62f215c8fb47b318c9b181/browser/net/brave_site_hacks_network_delegate_helper.cc#L66-L74

## Steps to Reproduce
Go to a whitelisted domain (e.g. duckduckgo.com) and log `navigator.userAgent` in the console.

## Actual result:
_Brave_ token not present.

## Expected result:
_Brave_ token should be present, as it is in the request header for the document.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
0.69.132

## Other Additional Information:
I believe the requested behavior was present in earlier Muon builds.

**Comment by bsclifton** [comment]
Need to verify- but I think we can close this in favor of https://github.com/brave/brave-browser/issues/8216
