### ISSUE TITLE
Update Brave profile icons

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#6443]
## Description
Update our current not-scalable solid color Brave profile icons with new pattern/color ones.

## Designs
These are the new ones:
![profile icons-rainbow ref](https://user-images.githubusercontent.com/2388823/66676566-ab60d480-ec1c-11e9-86c9-d8d912b28d9a.jpg)

## Assets
[profile-icons-names.txt](https://github.com/brave/brave-browser/files/3719206/profile-icons-names.txt)
[assets.zip](https://github.com/brave/brave-browser/files/3719359/assets.zip)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from https://github.com/brave/brave-core/pull/3771
* Confirmed only new icons are displayed when choosing a new profile avatar in Settings
<img width="939" alt="Screen Shot 2019-10-23 at 10 14 11 AM" src="https://user-images.githubusercontent.com/28145373/67407001-d6381a80-f584-11e9-9184-6ffd52db6e6a.png">

* Confirmed all 35 icons are selectable (including the default).
* Confirmed when a 2nd profile is created after a fresh user data directory is used, the first profile uses the new default icon (the first icon in set above). Subsequent profiles uses random other icons in set.
<img width="339" alt="Screen Shot 2019-10-23 at 10 15 19 AM" src="https://user-images.githubusercontent.com/28145373/67407153-14cdd500-f585-11e9-82a2-1f5d42be2918.png">

* Confirmed when a user data directory from the previous Brave browser version is used which has multiple profiles with brave avatar icons selected, those profiles still maintain their existing icon. 
Set up in 0.69.135:
<img width="257" alt="Screen Shot 2019-10-23 at 10 38 09 AM" src="https://user-images.githubusercontent.com/28145373/67407200-2c0cc280-f585-11e9-9d9d-544b6542bd18.png">

After upgrade to 0.70.121:
<img width="311" alt="Screen Shot 2019-10-23 at 10 40 06 AM" src="https://user-images.githubusercontent.com/28145373/67407234-375fee00-f585-11e9-9f54-f0537876391f.png">
