### ISSUE TITLE
Brave crashes once an hour with 1Password extensions installed

### ISSUE THREAD

**Issue by YoucefHQ** [brave/brave-browser#6446]
## Description 
Brave crashes once an hour. It looks like it's started after I've installed 1Password X extension. Also tried with 1Password Extension but the same problem is happening. I've submitted multiple crash reports but no answers or fixes so far.

I'm not sure if this is a bug that should be fixed on Brave or 1Password. However, I assume that an extension shouldn't be able to crash an entire browser?

The full crash report is here: https://pastebin.com/fcy9EHdA

Somebody already posted this on the forum. https://community.brave.com/t/barve-crashing-on-1password-extension-over-and-over-and-over-again/79257

## Steps to Reproduce

   1. Install 1Password X or 1Password Extension
   2. Use Brave normally
   3. Wait until it crashes

## Actual result:
Crashes randomly out of the blue even if I'm not actively using 1Password.

## Expected result:
No crash.

## Reproduces how often: 
Easily reproduced.

## Brave version (brave://version info)

`

Brave | 0.68.142 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)
JavaScript | V8 7.7.299.11
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extensions-install-verification=enforce_strict --enable-features=NewExtensionUpdaterService,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AudioServiceOutOfProcess,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,TranslateUI,UnifiedConsent --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/youcef/Library/Application Support/BraveSoftware/Brave-Browser/Profile 2

`

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Only tried here.
- Can you reproduce this issue with the beta channel?
Didn't test.
- Can you reproduce this issue with the dev channel?
Didn't test.
- Can you reproduce this issue with the nightly channel?
Didn't test.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No.
- Does the issue resolve itself when disabling Brave Rewards?
No.
- Is the issue reproducible on the latest version of Chrome? 
No.

## Miscellaneous Information:
I can reproduce this in both my Macbook Pros.

Thanks for your help!

**Comment by bsclifton** [comment]
@YoucefHQ can you please try updating to the most recent version of Brave? It should be version 0.69.135

Let us know if this helps (it has several crash fixes).  Thanks! 😄

**Comment by YoucefHQ** [comment]
Oops, sorry I thought I was on the latest version already. Just did, will report back!

**Comment by bsclifton** [comment]
@YoucefHQ how is everything looking? Hoping you're resolved 😄

**Comment by YoucefHQ** [comment]
@bsclifton Thanks for the follow-up. First day in a while that I didn't have any crashes. So it's all fixed. Thank you so much!
