### ISSUE TITLE
Disabling "Install Google Translate to translate this page"

### ISSUE THREAD

**Issue by WorldLanguages** [brave/brave-browser#6448]
How do I disable that popup, it's so annoying, it appears in English pages even tho that's my browser UI language.

**Comment by WorldLanguages** [comment]
Turning off "Offer to translate pages that aren't in a language you read" on settings seemed to work

**Comment by kameko** [comment]
This should really be default. A lot of us are using Brave to escape Google's spyware and malware, we shouldn't be berated by it even here. And in such a hidden section of the settings, no less.

**Comment by rebron** [comment]
Hi @kameko. The translate feature presents itself as an option if a user wants to install it or not and we've added a 'Don't ask me again' dialog to improve visibility of turning this feature awareness pop-up off. 

We recognize there are a lot of Brave users who want to escape Google's services. We do want to provide users an option who do need to translate a web page.
