### ISSUE TITLE
ads enabled by default for Japan on upgrade

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6449]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/5656

Upgrading from 0.69.135 on Japan profile when Rewards are on - when I open 0.70.x I expect to see a BAT logo notification alerting me that Ads have arrived. However, I don't get this. If I go to brave://rewards page I see that Ads are enabled by default. As I browse, I am served Ads.

I should not have been opted into Ads by default on upgrade.

## Steps to Reproduce

pre-req: have system set up for Japan locale/language
   1. Clean profile 0.69.135 (Release Channel)
   2. Enable Rewards.
   3. Note, there is the "Sorry" message at the bottom of the Ads panel.
   4. Open a new tab, close Rewards page.
   5. Close Brave. Rename profile to be a Beta profile.
   6. Launch with 0.70.113.

## Actual result:
No BAT logo notification alerting user about Ads.
Navigating to brave://rewards shows that Ads are enabled on upgrade.
If you browse, you will be served (untargeted) ads.
<img width="1201" alt="Screen Shot 2019-10-11 at 18 03 59" src="https://user-images.githubusercontent.com/28145373/66687689-85095c00-ec51-11e9-97cb-52e7403f90fe.png">

## Expected result:
BAT logo notification alerting user about Ads.
Navigating to brave://rewards shows that Ads are NOT enabled by default on upgrade.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.70.113 Chromium: 77.0.3865.90 (Official Build) beta （64 ビット）
-- | --
変更履歴 | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS バージョン10.13.6（ビルド17G5019）

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @tmancey @jsecretan @brave/legacy_qa @rebron

**Comment by LaurenWags** [comment]
Probably also occurs for regions listed in #5655 as well.

**Comment by GeetaSarvadnya** [comment]
Reproduce in windows 10 x64- 0.70.113.

**Comment by btlechowski** [comment]
Reproduced on Ubuntu

Brave | 0.70.115 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.70.118 Chromium: 78.0.3904.50 (Build ufficiale) (a 64 bit)
-- | --
Revisione | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
Sistema operativo | macOS Versione 10.13.6 (Build 17G5019)

* Verified STR from description (Japan region). Verified was prompted via BAT logo notification to alert user that Ads have arrived. Ads were off by default.
<img width="1196" alt="Screen Shot 2019-10-17 at 12 36 37" src="https://user-images.githubusercontent.com/28145373/67031820-558aa180-f0e0-11e9-911c-85163b762fa7.png">

* Verified test plan from https://github.com/brave/brave-core/pull/3691
* Confirmed ads are not enabled by default for upgrade paths for new regions. Sorry message still displayed on Ads panel after upgrade. No BAT logo notification. (checked with Bulgaria and Slovakia)
* Confirmed ads are not enabled by default for fresh installs if a region is not supported and rewards are enabled. Sorry message displayed on Ads panel. (checked with Bulgaria and Slovakia)
* Confirmed ads are enabled by default for fresh installs if a region is supported and rewards is enabled. Ads panel UI is displayed, no Sorry message. (checked with US, Australia, Japan)
* Confirmed on-boarding is shown for upgrade paths (from 0.69.135) for new regions (checked with Japan and Italy. Additional regions will be checked with https://github.com/brave/brave-browser/issues/5655). Verified was prompted via BAT logo notification to alert user that Ads have arrived. Ads were off by default.
<img width="1198" alt="Screen Shot 2019-10-17 at 13 21 32" src="https://user-images.githubusercontent.com/28145373/67032181-0f820d80-f0e1-11e9-9f87-540f2facf492.png">
