### ISSUE TITLE
Relaunch button changes shape on multiple toggle

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#6450]
## Description 
Relaunch button changes from `round` to `square` on toggle

## Steps to Reproduce

   1. Navigate to `brave://settings/?search=hardware` and toggle the `Use hardware acceleration when available` setting
   2. The Relaunch button is Round
   3. Toggle it twice and the relaunch button changes to square

## Actual result:
Square relaunch button

## Expected result:
Round button

## Reproduces how often: 
Easily

## Brave version (brave://version info)
0.72.90 Chromium: 78.0.3904.50 (Official Build) nightly (64-bit)

**Comment by bsclifton** [comment]
Looks like this first started happening in 0.70.x; works just fine in 0.69.x. Not a Chromium 78 regression

**Comment by bsclifton** [comment]
This was fixed somewhere along the way 😄
