### ISSUE TITLE
Tor profile button now includes "private" (C78)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#6451]
## Description 
I believe there is a chromium_src override that may be missing. In the profile button (shown at the top right, if you have more than one profile or are in a Tor window), it now has `Private   Tor` (instead of just `Tor`)

## Steps to Reproduce
   1. Use Nightly (0.72.x)
   2. Open a Tor window
   3. Look at profile button in top right

## Actual result:
<img width="377" alt="Screen Shot 2019-10-11 at 4 02 52 PM" src="https://user-images.githubusercontent.com/4733304/66689728-f5f44800-ec40-11e9-8b61-36f65aef199c.png">

## Expected result:
<img width="307" alt="Screen Shot 2019-10-11 at 4 03 04 PM" src="https://user-images.githubusercontent.com/4733304/66689732-f987cf00-ec40-11e9-9489-1714af3c6bd1.png">

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 0.72.90 Chromium: 78.0.3904.50 (Official Build) nightly (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | macOS Version 10.14.6 (Build 18G87)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n
- Can you reproduce this issue with the beta channel? n
- Can you reproduce this issue with the dev channel? n
- Can you reproduce this issue with the nightly channel? y

**Comment by bsclifton** [comment]
Uplifted to 0.71.x with https://github.com/brave/brave-core/pull/3693
Uplifted to 0.70.x with https://github.com/brave/brave-core/pull/3695

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.70.118 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from https://github.com/brave/brave-core/pull/3686
<img width="355" alt="Screen Shot 2019-10-17 at 12 01 58 PM" src="https://user-images.githubusercontent.com/28145373/67026574-0f304500-f0d6-11e9-92da-9d6d073221a3.png">
