### ISSUE TITLE
Warn users when they use/save a vulnerable password

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#6452]
We could make use of the HIBP [Pwned Passwords API](https://haveibeenpwned.com/API/v3#PwnedPasswords) to warn users when they enter a vulnerable password in a password field or when they save one in the password manager.

1Password includes this functionality as part of their "Watchtower":

![Screenshot from 2019-10-11 16-16-21](https://user-images.githubusercontent.com/167821/66690051-7bc4c300-ec42-11e9-8f63-ad0307c17dbc.png)

A vulnerable password is one that is present in the data dumps from one of the password leaks tracked by [Have I Been Pwned](https://haveibeenpwned.com/Passwords).

This does not require a back-end service as long as we're comfortable with the [k-anonymity guarantees](https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/) of the public API.

**Comment by BrendanEich** [comment]
I like this idea. Even better if we can assist users in changing to better passwords, although that sounds complicated.

**Comment by fmarier** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/12001.
