### ISSUE TITLE
Rewards "wallet verified" visual treatment is incorrect in 0.71

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#6460]
In the current dev channel build, the "wallet verified" indicator is bright green. 

This is incorrect -- it should match the simpler (white text on purple background) treatment in 0.69 (release) and 0.72 (nightly). 

Version 0.71.74 Chromium: 77.0.3865.75 (Official Build) dev (64-bit)

Note: I did not check 0.70 (beta channel).

**Comment by NejcZdovc** [comment]
this is because dev was not updated correctly. Fresh download fixes it
