### ISSUE TITLE
Make Brave Rewards extension non-persistent

### ISSUE THREAD

**Issue by bershanskiy** [brave/brave-browser#6462]
## Description 

Make Brave Rewards extension non-persistent via manifest key `persistent: false`, allowing extension to be unloaded when not in active use (read when the popup UI is not shown). This should save one process and ~19MB of RAM.

## Steps to Reproduce

   1. Open browser
   2. Open task manager
   3. Observe the process called "Extension: Brave Rewards"

## Actual result:

![rewards](https://user-images.githubusercontent.com/45960703/66725888-4f1cd100-ee25-11e9-96a0-16d9a2c50343.png)

## Expected result:
Brave Rewards process is not running, since the popup is closed.

## Reproduces how often: 

All the time.

## Brave version (brave://version info)

Brave	0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
Revision	58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS	Linux
JavaScript	V8 7.7.299.11
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Command Line	/usr/bin/brave-browser-stable --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-features=NewExtensionUpdaterService,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AudioServiceOutOfProcess,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,UnifiedConsent --flag-switches-begin --flag-switches-end
Executable Path	/opt/brave.com/brave/brave-browser
Profile Path	/home/anton/.config/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Yes.
- Can you reproduce this issue with the dev channel? Yes.
- Can you reproduce this issue with the nightly channel? Yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A, but yes.
- Does the issue resolve itself when disabling Brave Rewards? Yes.
- Is the issue reproducible on the latest version of Chrome? N/A.

## Miscellaneous Information:

The following bugs are related:
 - #3436 Rewards extension process needs to be terminated when disabled, Follow up to #1475  
   It's about what happens when the Rewards are  entirely disabled
 - #6372 WebTorrent extension should be non-persistent
   Different extension, the same challenges

**Comment by petemill** [comment]
Right now this is difficult to achieve because the extension:
- Uses the `webRequest` API (due to inline tipping). Once this is removed to a different extension, this will be further possible.
- Keeps data required in-memory without re-syncing from primary source of data. This is unneccessary. Should be re-architected to retrieve data when needed, and not try to keep a secondary source of data in-sync.

**Comment by bershanskiy** [comment]
> Uses the webRequest API (due to inline tipping). Once this is removed to a different extension, this will be further possible.

By inline tipping you mean tipping to users on large platforms like GitHub, YouTube, etc., right?

Another challenge is fixing the way icon is handled. Right now, the icon seems to be controlled by the script because it's hidden when the extension is unloaded. Instead, I think, the icon should determine when the extension UI is loaded.

> Instead, #3436 is more achievable and achieves the result of non-rewards users not having rewards-related memory use.

Well, in a way, this encourages people to disable Rewards for the performance benefits, right? :)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.18.59 Chromium: 87.0.4280.67 (Official Build) dev (x86_64)
Revision	0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}
OS	macOS Version 10.14.6 (Build 18G6042)
```

Verified test plan from https://github.com/brave/brave-core/pull/6978. Each of the below cases/sub cases was completed using a fresh profile.

<details>
<summary>Website - laurenwags.github.io</summary>

1. Rewards panel test

- Confirmed onboarding shown on clean profile via panel
- After dismissing onboarding, claimed UGP with clean (staging) profile
- Confirmed able to tip via panel using UGP
- Confirmed tip showed on brave://rewards Tip section, Monthly Statement, and brave://rewards-internals Contributions tab

<img width="1197" alt="Screen Shot 2020-11-23 at 10 33 43 AM" src="https://user-images.githubusercontent.com/28145373/99981507-7ad3ef80-2d77-11eb-9ac0-1cadb2a3c3bf.png">
<img width="652" alt="Screen Shot 2020-11-23 at 10 34 00 AM" src="https://user-images.githubusercontent.com/28145373/99981510-7b6c8600-2d77-11eb-8594-17514b296a16.png">
<img width="406" alt="Screen Shot 2020-11-23 at 10 34 07 AM" src="https://user-images.githubusercontent.com/28145373/99981514-7c9db300-2d77-11eb-97b4-744996a9e876.png">
<img width="1189" alt="Screen Shot 2020-11-23 at 10 34 19 AM" src="https://user-images.githubusercontent.com/28145373/99981521-7dcee000-2d77-11eb-9f78-11ac69963f86.png">

2. N/A (Inline tipping test)

3. Extension test

- Confirmed only Brave extension is running on a clean profile

<img width="1197" alt="Screen Shot 2020-11-23 at 10 37 01 AM" src="https://user-images.githubusercontent.com/28145373/99982213-4ad91c00-2d78-11eb-94b6-5dead6fde554.png">
<img width="1655" alt="Screen Shot 2020-11-23 at 10 37 45 AM" src="https://user-images.githubusercontent.com/28145373/99982279-5c222880-2d78-11eb-85c5-723c86ad7ef3.png">

- Confirmed clicking on the BAT logo in URL bar to open the panel started the Rewards extension

<img width="1436" alt="Screen Shot 2020-11-23 at 10 39 19 AM" src="https://user-images.githubusercontent.com/28145373/99982298-604e4600-2d78-11eb-90a6-d82e12b9ec94.png">

</details>
