### ISSUE TITLE
.xsession-errors contains MANY "ERROR:latency_info.cc(163)] Surface::TakeLatencyInfoFromFrame, LatencyInfo vector size 102 is too big."

### ISSUE THREAD

**Issue by walkjivefly** [brave/brave-browser#6463]
Yes, searched for similar issues. Found https://github.com/brave/browser-laptop/issues/14814 which was closed wontfix. 

## Description 
.xsession-errors is full of messages like
```
[17298:17298:1014/141031.935335:ERROR:latency_info.cc(163)] Surface::TakeLatencyInfoFromFrame, LatencyInfo vector size 101 is too big.
[17298:17298:1014/141042.067038:ERROR:latency_info.cc(163)] Surface::TakeLatencyInfoFromFrame, LatencyInfo vector size 102 is too big.
[17298:17298:1014/141043.757404:ERROR:latency_info.cc(163)] Surface::TakeLatencyInfoFromFrame, LatencyInfo vector size 102 is too big.
```
which appear to be generated by running Brave browser.

## Steps to Reproduce
   1. Start Brave browser 
   2. watch the messages appear in .xsession-errors
   3. 

## Actual result:
.xsession-errors is full of error messages from Brave browser

## Expected result:
Browser runs without continuously generating a gazillion error messages

## Reproduces how often: 
Continuously

## Brave version (brave://version info)
```
mark@x230:~$ apt-cache policy brave
brave:
  Installed: 0.23.79-1
  Candidate: 0.23.79-1
  Version table:
 *** 0.23.79-1 100
        100 /var/lib/dpkg/status
```

Brave: 0.23.79 
V8: 6.8.275.24 
rev: 51b49051a779f0db94fbcfd0df5faca781299ea0 
Muon: 8.0.7 
OS Release: 4.15.0-1-amd64 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

## Version/Channel Information:
Haven't tried any other channels

**Comment by srirambv** [comment]
@walkjivefly  you are still on the older muon browser which isn't supported any more. Request you to download the currently supported version from https://brave.com/download. 

Closing the issue for now

**Comment by walkjivefly** [comment]
Nice. This IS the currently supported Release Channel version.
You have a funny idea of what's supported and what isn't.

**Comment by srirambv** [comment]
@walkjivefly the version you are running was on release channel when we were supporting muon. Muon has been deprecated so even if it says release version it's not currently supported. You can see currently supported versions install instructions here https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

**Comment by walkjivefly** [comment]
Oh, I see! There is brave and brave-browser. My mistake, sorry. I have both installed but have been running brave, not brave-browser. Have to say I prefer the interface on the old version but brave-browser isn't writing gazillions of errors in .xsession-errors so I'll get used to this one.

Thanks for straightening me out.

**Comment by insaner** [comment]
I don't know if this is useful to anyone, but I ran into this bug report by searching my problem. I get the:

`ERROR:latency_info.cc(144)] Surface::TakeLatencyInfoFromFrame, LatencyInfo vector size 102 is too big.`

on Chromium 71.0.3578.98
NVIDIA Driver Version: 390.129

My strong suspicion is that this is related to Nvidia drivers, but if any ATI users confirm the presence of this bug, that at least narrows it down a little.
