### ISSUE TITLE
Disabled shields for a website are ignored by cookie service

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#6464]
## Description 
Disabling shields does not allows 3p cookies (if cookie preference was not changed for a given website).

## Steps to Reproduce
   1. Open https://www.whatismybrowser.com/detect/are-third-party-cookies-enabled
   2. Shields down
   3. 3p cookies are still blocked

## Reproduces how often: 
Always

## Brave version (brave://version info)
Brave | 0.70.112 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.70.118 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | macOS Version 10.13.6 (Build 17G5019)

* Reproduced the issue using 0.70.117. 
* Verified STR from description with 0.70.118.

<img width="1088" alt="Screen Shot 2019-10-17 at 12 09 56 PM" src="https://user-images.githubusercontent.com/28145373/67027158-1015a680-f0d7-11e9-88a6-105214813f1f.png">
