### ISSUE TITLE
Ad notifications are not displayed on macOS Catalina

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#6466]
## Steps to Reproduce

Prerequisite: Install macOS Catalina

   1. Enable Ads
   2. Navigate to www.brave.com

## Actual result:

Ad notification is not shown

## Expected result:
Ad notification should be shown

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Ad notifications are displayed as native notifications using an XPC service, allowing different types of alert styles to be displayed.

The XPC service is incompatible with macOS Catalina for different types of alert styles.

A workaround is to disable native notifications for Brave Browser on macOS Catalina until the native notifications platform bridge has been updated to support this new operating system.

Custom notifications are displayed if brave://flags/#enable-native-notifications is `Disabled` or the operating system does not support native notifications.

Additional sanity testing is required to make sure Ad notifications work as expected with custom notifications.

Custom notifications will not be displayed in the macOS Notification Center, which is likely less of a concern due to Ads history is available from the Rewards panel.

**Comment by eljuno** [comment]
+1 from Twitter https://twitter.com/IceBlueDesigns/status/1183856104029057024?s=09

**Comment by Brave-Matt** [comment]
From Community -- several users reporting:
https://community.brave.com/t/upgrade-to-catalina-stopped-rewards/87211/8

**Comment by tmancey** [comment]
TODO(crbug.com/1007418): Show all notifications as alerts on macOS as a temporary workaround. NSUserNotificationAlertStyle has been changed to "alert" in "src/chrome/app/app-info.plist". If the notification is non-persistent remove the notification after 5 seconds to emulate banners, as a side-effect notifications will not minimize to the notification centre. Brave ads are dismissed within AdsServiceImpl

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.1 x64` using the following build:

Brave | 0.71.111 Chromium: 78.0.3904.87 (Official Build) (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | macOS Version 10.15.1 (Build 19B88)

* ensured that ad notifications are being displayed when using `Banners` from `Notifications` via the macOS `System Preferences`:

<img width="677" alt="Screen Shot 2019-11-04 at 4 06 18 PM" src="https://user-images.githubusercontent.com/2602313/68159296-83187d00-ff1f-11e9-9496-41702c56a98d.png">

* ensured that ad notifications are being displayed when using `Alerts` from `Notifications` via the macOS `System Preferences`:

<img width="674" alt="Screen Shot 2019-11-04 at 4 01 04 PM" src="https://user-images.githubusercontent.com/2602313/68157806-629af380-ff1c-11e9-9067-0cb562275a9f.png">

* ensured that ad notifications are being displayed when using `None` from `Notifications` via the macOS `System Preferences`:

<img width="684" alt="Screen Shot 2019-11-05 at 12 49 04 AM" src="https://user-images.githubusercontent.com/2602313/68181640-20969f80-ff66-11e9-893f-9f34f491c932.png">

Noticed that ad notifications disappear from the notification tray after ~2mins. This has been an issue for a while and not related to this change. Added comments via https://github.com/brave/brave-browser/issues/5628#issuecomment-549670555.
