### ISSUE TITLE
Private window w/ Tor shows "new private window"

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#6467]
## Description 
While testing https://github.com/brave/brave-core/pull/3686, I noticed a weird regression - cc: @yrliou who has done Tor work in Nightly (it may be due to that work? or Chromium 78? not sure)

Basically, in Dev channel for example (C77), when in a private window with Tor, you're not given the option to create a regular private window
- via the hamburger menu
    <img width="411" alt="Screen Shot 2019-10-14 at 9 27 54 AM" src="https://user-images.githubusercontent.com/4733304/66767526-8317e680-ee65-11e9-85e9-4663be5907c5.png">
- via the menu (macOS)
    <img width="366" alt="Screen Shot 2019-10-14 at 9 30 17 AM" src="https://user-images.githubusercontent.com/4733304/66767566-94f98980-ee65-11e9-8a06-4455bb3f6262.png">

On master/Nightly, when in a private window with Tor, you're shown the option to open a new private window. If you do choose this, it opens a private window with Tor, NOT a regular private window.
- hamburger menu
    <img width="386" alt="Screen Shot 2019-10-14 at 9 28 07 AM" src="https://user-images.githubusercontent.com/4733304/66767663-c5d9be80-ee65-11e9-91c7-13e6ccb49678.png">
- via the menu (macOS)
    <img width="353" alt="Screen Shot 2019-10-14 at 9 30 37 AM" src="https://user-images.githubusercontent.com/4733304/66767689-d427da80-ee65-11e9-88df-a38d8ee7fa44.png">

## Steps to Reproduce
   1. Launch master / Nightly
   2. Open a new private window with Tor
   3. Use hamburger menu, pick `New Private Window`

## Actual result:
A new private window with Tor is shown

## Expected result:
Menu option should not be there (see screenshot)

## Reproduces how often: 
100%

## Brave version (brave://version info)
master/Nightly (0.72.x)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n
- Can you reproduce this issue with the beta channel? n
- Can you reproduce this issue with the dev channel? n
- Can you reproduce this issue with the nightly channel? y

**Comment by btlechowski** [comment]
Reproduced on Ubuntu 

Brave | 0.72.110 Chromium: 78.0.3904.70 (Official Build) dev (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/67684459-85189400-f993-11e9-85f0-aeedf96f57bf.png)

cc @brave/legacy_qa

**Comment by yrliou** [comment]
Had a discussion with @tomlowenthal and @bsclifton through slack, we will keep the `New private window` in Tor windows but tweak its behavior to open a private window in its parent profile instead of Tor profile.

**Comment by btlechowski** [comment]
Because of https://github.com/brave/brave-browser/issues/6646 if this issue is fixed as intended in https://github.com/brave/brave-browser/issues/6467#issuecomment-547144297, there will be no way of opening a new private window with tor from private window with tor.

**Comment by yrliou** [comment]
@btlechowski Right, I think I'll also fix the `New window` to open the regular window in the same PR to fix these two together.

**Comment by yrliou** [comment]
See https://github.com/brave/brave-core/pull/3813#issue-333822010 for the test plan.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.72.124 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3813

regular window
![image](https://user-images.githubusercontent.com/34715963/68859989-d68d8680-06e8-11ea-8bf8-bc39ed85644a.png)

private window
![image](https://user-images.githubusercontent.com/34715963/68860111-1eaca900-06e9-11ea-8f9d-b44acd7d3f53.png)

private window with Tor
![image](https://user-images.githubusercontent.com/34715963/68860129-28361100-06e9-11ea-8769-4fa184e4aac9.png)
