### ISSUE TITLE
changing default SE doesn't change SE in Guest window

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6470]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/6187

When the default SE is changed, it doesn't change the SE on a Guest window. Google is still the default. However, on the tab there is a toggle to use DDG (since Guest windows use Private theme).

Not sure if this is related to #5065 - the settings page on a Guest window is empty.

## Steps to Reproduce

   1. Launch with a clean profile
   2. Change default SE.
   3. Open a Guest window.

## Actual result:
Google is the default SE.

## Expected result:
Default SE to be what you had chosen in settings.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | macOS Version 10.13.6 (Build 17G5019)

Brave | 0.70.115 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

Brave | 0.72.99 Chromium: 78.0.3904.50 (Official Build) nightly (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Reproduced on Ubuntu

Brave | 0.70.115 Chromium: 77.0.3865.90 (Official Build) beta (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows 10 x64 - 0.70.116

**Comment by rebron** [comment]
Closing. Working as expected. Should use default search engine not one chosen by user in main profile.
