### ISSUE TITLE
Browser crash when Tor/Guest/Private window is opened in some locales - follow up to 6421

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6476]
## Description 
Follow up to #6421 

When opening a Tor (or Guest or Private) window in some locales the browser crashes.

Germany - reproduced for Tor window. Example crash ID:
   * ID des hochgeladenen Absturzberichts: 28023ed33f3592c6 and ID des hochgeladenen Absturzberichts: fa92b9b0790c870d (a single tor window crash produced both of these)

Australia - reproduced for Private/Guest/Tor windows
   * Uploaded Crash Report ID 8696051c26a70879 (private window)
   * Uploaded Crash Report ID 6d17b8290e5946bd (guest window)
   * Uploaded Crash Report ID 7255cac588bfacd8 and Uploaded Crash Report ID e34ccf71f1365423 (a single tor window crash produced both of these)

New Zealand - reproduced for Private/Guest/Tor windows. Example crash ID:
   * Uploaded Crash Report ID 1fa0f102d8f4a37e (private window)
   * Uploaded Crash Report ID 2f5440506ed480f4 (guest window)
   * Uploaded Crash Report ID 0859b8564f4ac137 and Uploaded Crash Report ID 7cbea791ea099826 (a single tor window crash produced both of these)

Ireland - reproduced as well but forgot to save crashes. If you need them let me know and I'll generate more.

Could not reproduce with US/UK locales.

## Steps to Reproduce

   1. Set system to an affected locale/language.
   2. Clean profile with 0.70.116.
   3. Open a Tor/Private/Guest window.

## Actual result:
Crash

## Expected result:
No crash

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.70.116 Chromium: 77.0.3865.90 (Offizieller Build) beta (64-Bit)
-- | --
Überarbeitung | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
Betriebssystem | macOS Version 10.13.6 (Build 17G5019)

Brave | 0.72.100 Chromium: 78.0.3904.50 (Offizieller Build) nightly (64-Bit)
-- | --
Überarbeitung | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
Betriebssystem | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no (using 0.69.135)
- Can you reproduce this issue with the beta channel? yes using 0.70.116
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? yes using 0.72.100

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @bsclifton @rebron @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
I am seeing the crash for Guest/PT/TOR in US locale. Please find the attached recorded files

TOR window - https://drive.google.com/open?id=1t8RslWkFhQ1Nu_TCpVSsw3UYvmaRh0Zy
Private window - https://drive.google.com/open?id=1CdBx7AfZIu-MDUN5IsjuAg3vMKS6Ic2T
Guest window - https://drive.google.com/open?id=1a3wopbb006-0h7o68L5OU1rtS5KtcUd2

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.119 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3738
Verified no crashes for following locales: en_AU, en_NZ, en_IE, ga_IE, de_DE, en_US, en_GB, pl_PL

**Comment by LaurenWags** [comment]
Per discussion with @kjozwiak - removing `QA Pass-Linux` and marking as `QA/Blocked` until https://github.com/brave/brave-browser/issues/6565 is resolved.

cc @brave/legacy_qa @rebron

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.70.120 Chromium: 78.0.3904.70 (Official Build) (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
- Verified the locales the US, UK, New Zealand, Ireland, Germany, and Austalia. - No crash in PT/TOR/Guest windows
- Verified both clean and upgraded profile
- Verified no crash in PT/TOR/Guest windows, kept each window open for 20 secs and observed there is no crash

**Comment by LaurenWags** [comment]
Removed `QA/Blocked` label as issue from https://github.com/brave/brave-browser/issues/6476#issuecomment-544543354 was included in `0.70.120` so this issue can be tested now.
