### ISSUE TITLE
Infobar has blue brave logo

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#6478]
![image](https://user-images.githubusercontent.com/741836/66856618-79ac7e00-ef3a-11e9-926b-6620ade19df0.png)

STR:
- Fresh profile
- Launch Brave
- Quit Brave
- Launch Brave again
- An infobar is shown about Brave being the default browser
- Expected: Brave logo is red and white
- Actual: Brave logo is blue and transparent

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.71.108 Chromium: 78.0.3904.87 (Official Build) beta (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/68106997-683b0e00-ff09-11e9-9d11-4461a2a071fa.png)
