### ISSUE TITLE
Brave extension should be lazy and less memory intensive

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#6479]
## Description 

Brave extension background process is always in-memory, using up from 30mb - 150mb. This should be:
- Only ever 30mb in size, and not grow.
- Quit when not needed (not persistent)

In order for this to happen:
 - Everything needs to be ok with the extension's memory being wiped out in-between events (i.e. persist stuff)
 - Not load everything all at one time in to memory (i.e. every blocked resource list for every open tab)

**Comment by rebron** [comment]
cc: @cezaraugusto

**Comment by NejcZdovc** [comment]
+1 from https://github.com/brave/brave-browser/issues/10702

**Comment by petemill** [comment]
Assigining multiple people as hopefully some of us can look at it after https://github.com/brave/brave-core/pull/13638 with regards to greaselion / rewards API usage which prevent the extension process exiting periodically

**Comment by Miyayes** [comment]
I think this is resolved with the new WebUI-based Rewards panel? https://github.com/brave/brave-browser/issues/22423 @petemill
