### ISSUE TITLE
BAT Points support

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#6480]
Spec posted - please refer.

cc @NejcZdovc @kjozwiak @rebron @mattmcalister

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.71.108 Chromium: 78.0.3904.87 (Official Build) beta (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3751
- Encountered https://github.com/brave/brave-browser/issues/6654#issuecomment-548078955
- Encountered #6684 and #6685
