### ISSUE TITLE
update tip panel wording - follow up to 6228

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6484]
## Description 
With the changes in #6228 and #6288, and a new `Monthly Contribution` panel on brave://rewards, should the Tip panel text which mentions recurring monthly tips be updated?

## Steps to Reproduce

   1. Clean profile 0.72.102
   2. Navigate to brave://rewards page
   3. Enable Rewards
   4. Scroll to Tips panel. Panel text mentions "You can also set up recurring monthly tips so you can support sites continuously." and "Support your favorite sites with recurring monthly tips."
   5. Refresh page.
   6. View Tips panel. Panel tex mentions "You can also set up recurring monthly tips so you can support sites continuously."

## Actual result:
<img width="662" alt="Screen Shot 2019-10-15 at 3 29 21 PM" src="https://user-images.githubusercontent.com/28145373/66863990-336b1500-ef62-11e9-85e7-7c1660d61d22.png">
<img width="677" alt="Screen Shot 2019-10-15 at 3 28 16 PM" src="https://user-images.githubusercontent.com/28145373/66863993-3534d880-ef62-11e9-9d5c-8ce9f8267764.png">

## Expected result:
Unsure if text should be updated or removed.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.72.102 Chromium: 78.0.3904.50 (Official Build) nightly (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the dev channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @davidtemkin @NejcZdovc @rebron @kjozwiak

**Comment by LaurenWags** [comment]
For reference, this is what the current Monthly Contributions (monthly recurring tips) panel looks like:
<img width="653" alt="Screen Shot 2019-10-15 at 3 45 50 PM" src="https://user-images.githubusercontent.com/28145373/66864332-eb002700-ef62-11e9-97fa-a76f34533a04.png">
<img width="647" alt="Screen Shot 2019-10-15 at 3 46 00 PM" src="https://user-images.githubusercontent.com/28145373/66864338-ec315400-ef62-11e9-93fb-b0415cca2d1d.png">

**Comment by LaurenWags** [comment]
cc @jenn-rhim

**Comment by bradleyrichter** [comment]
@LaurenWags @ryanml @mandar-brave 

Here is the new text:

![image](https://user-images.githubusercontent.com/13509546/66967568-3f280b80-f036-11e9-9eb5-9e280ca4e7b9.png)



**Monthly Contributions**
Set up recurring monthly contributions so you can support sites continuously.

Your monthly contributions will be sent every 30 days.
__________

**Tips**
Tip content creators directly as you browse by using the Rewards Panel, or by using the inline tip button on various sites including Twitter, Reddit and GitHub.

Tip on the spot as you find gems.

If you like, let people know with a quick tweet.

**Comment by btlechowski** [comment]
@bsclifton @ryanml @kjozwiak Should this be uplifted to 0.71.x? 0.71.x uses old Rewards layout. It doesn't even have `Monthly Contributions` section in `brave://rewards`.

**Comment by bradleyrichter** [comment]
@rebron ^

**Comment by NejcZdovc** [comment]
again I don't know why this was uplifted to 0.71 as original implementation was done in 0.72. What we now uplifted in not relevant to .71

**Comment by LaurenWags** [comment]
Verified Tips panel text with

Brave | 0.71.111 Chromium: 78.0.3904.87 (Official Build) (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | macOS Version 10.13.6 (Build 17G5019)

![rewards-disabled-tip-text](https://user-images.githubusercontent.com/28145373/68251636-93009180-fff1-11e9-9898-f6da587070d1.png)
<img width="680" alt="Screen Shot 2019-11-05 at 5 23 19 PM" src="https://user-images.githubusercontent.com/28145373/68251641-972caf00-fff1-11e9-843d-f72a8f2deb04.png">

Verified Monthly Contributions panel text with 0.72.x as it is not available in 0.71.x:

Brave | 0.72.117 Chromium: 78.0.3904.87 (Official Build) dev (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | macOS Version 10.13.6 (Build 17G5019)

<img width="686" alt="Screen Shot 2019-11-05 at 5 22 12 PM" src="https://user-images.githubusercontent.com/28145373/68251685-ac094280-fff1-11e9-93e6-fba11de5840e.png">
<img width="661" alt="Screen Shot 2019-11-05 at 5 23 29 PM" src="https://user-images.githubusercontent.com/28145373/68251691-ad3a6f80-fff1-11e9-9c07-f94ec3e7b09d.png">
