### ISSUE TITLE
https://brave.com/cryptocurrency-risk links to a 404 page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6485]
## Description 

 https://brave.com/cryptocurrency-risk isn't available which is linked to risk disclosure on disclaimer message

## Actual result:

404 page not found

## Expected result:
Link to an active page with proper content

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @bbondy @tomlowenthal @ryanml

**Comment by kjozwiak** [comment]
Example of where the link is being displayed as @btlechowski @GeetaSarvadnya and @LaurenWags haven't QA'd Crypto Wallets so they might now know where the location of the links are. Also might help developers:

<img width="1210" alt="Screen Shot 2019-10-15 at 4 12 57 PM" src="https://user-images.githubusercontent.com/2602313/66866964-5d273a80-ef68-11e9-8d85-702bdc31978e.png">
<img width="1184" alt="Screen Shot 2019-10-15 at 4 11 53 PM" src="https://user-images.githubusercontent.com/2602313/66866965-5d273a80-ef68-11e9-9e99-a679c1bce897.png">

@tomlowenthal do you know if there's any other locations where a link to https://brave.com/cryptocurrency-risk might be displayed?

**Comment by srirambv** [comment]
Should be on
- Create wallet page
- Restore wallet page

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | Linux

* Verification passed on component `1.0.11`
* Verified updated disclosure text on first launch
![image](https://user-images.githubusercontent.com/17010094/67046215-d3a97100-f0fd-11e9-8335-44feab18203f.png)
* Verified risk disclosure text/link is not shown on create wallet page 
![image](https://user-images.githubusercontent.com/17010094/67045453-50d3e680-f0fc-11e9-87f4-cff02d93b0b2.png)
* Verified risk disclosure text/link is not shown on restore wallet page 
![image](https://user-images.githubusercontent.com/17010094/67045564-8d074700-f0fc-11e9-9a72-87b1de6d307e.png)

Verification passed on 

Brave | 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | Windows 

* Verification passed on component `1.0.11`
* Verified updated disclosure text on first launch
![image](https://user-images.githubusercontent.com/17010094/67046127-a3fa6900-f0fd-11e9-9df8-fd7acf2bc4ee.png)
* Verified risk disclosure text/link is not shown on create wallet page
![image](https://user-images.githubusercontent.com/17010094/67046010-64cc1800-f0fd-11e9-9667-5282ca4efc37.png)
 * Verified risk disclosure text/link is not shown on restore wallet page 
![image](https://user-images.githubusercontent.com/17010094/67046033-72819d80-f0fd-11e9-9929-ee4956498074.png)
