### ISSUE TITLE
Use an OS-chosen port number for tor socks proxy

### ISSUE THREAD

**Issue by riastradh-brave** [brave/brave-browser#649]
Currently, in browser-laptop, we use port 9250, 9260, 9270, 9280, or 9290 for the tor socks proxy, depending on the release channel.  This allows a standard release of Brave to coexist with a beta release to coexist with a local development build, but not more than one of each kind at a time, and if anything happens to be using the port number when Brave starts, it just fails.  We should let the tor daemon ask the OS to choose an unused port number and use that instead.

This requires an extra step from what we currently do in browser-laptop.  Specifically, currently, we:

1. Pick the port number, say 9250.
2. Create a Tor browser context with a Tor socks proxy config pointing at `socks5://127.0.0.1:9250`.
   - (The Tor socks proxy config is customized to use a unique username and password per first-party origin, per per fresh load.)
3. Start tor with `--socksport 9250`.

Instead, we should:

1. Create a Tor browser context with an uninitialized Tor socks proxy config that blocks all requests.
2. Start tor with `--socksport 0`.
3. Learn the port number from the tor control channel: `GETINFO net/listeners/socks`.
4. Configure the Tor socks proxy config with the port number we learn from that.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.16.50 Chromium: 86.0.4240.55 (Official Build) dev (x86_64)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4802

Verified `OS-chosen port for tor`
Opened Tor Window the first time
![image](https://user-images.githubusercontent.com/34715963/95049582-539f6100-06ea-11eb-9362-3d73b28c196c.png)

Opened Tor Window the second time
![image](https://user-images.githubusercontent.com/34715963/95049650-76ca1080-06ea-11eb-80b7-89502ab0cdd6.png)

Rest of the verification done in https://github.com/brave/brave-browser/issues/359#issuecomment-703459303
