### ISSUE TITLE
Make dapp detection accurate

### ISSUE THREAD

**Issue by tmcw** [brave/brave-browser#6491]
## Description 

Detecting 'Installing a Crypto Wallet' by using a getter on window.web3 is inaccurate and misleading to users. For sites like ours, we want to keep track of globals, and something as simple as

```js
Object.getOwnPropertyNames(window).forEach(key => window[key])
```

Triggers this message, which recurs even if a user clicks 'Deny'. It's a product that has nothing to do with crypto and this message is incorrect at least and a problem for user trust.

You could:

- Make the property non-enumerable
- Drop this check

Or something else. For now we'll have to hardcode a workaround into our app to make it avoid web3.

## Steps to Reproduce

   1. `Object.getOwnPropertyNames(window).forEach(key => window[key])`

## Actual result:

A dapp is detected.

## Expected result:

A dapp is not detected.

## Reproduces how often: 

Always

## Brave version (brave://version info)

All

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

---

Pulled from #718

**Comment by srirambv** [comment]
cc: @bbondy @tomlowenthal

**Comment by bbondy** [comment]
@tmcw I think this is no longer an issue, can you confirm?

**Comment by tmcw** [comment]
I can confirm that it is still an issue, still replicable with the one-line trigger. https://gainful-beechnut.glitch.me/

**Comment by wighawag** [comment]
I would like to add that even for dapp, no popup should be triggered just by accessing window.ethereum. This is not user friendly

Brave should follow https://eips.ethereum.org/EIPS/eip-1102

"window.ethereum existence" check is useful to check if a user browser can support dapp.

**Comment by ryanml** [comment]
We are going to be removing the dapp infobar for the time being, so closing this for now. ref: We are going to be removing the dapp infobar for the time being, so closing this for now, but in future iterations this will be top priority for the feature, thanks! ref: https://github.com/brave/brave-core/pull/7321
