### ISSUE TITLE
Crash reporting switch state not retained between relaunches

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#6496]
## Description 

Crash reporting switch turned to OFF state after browser restart even though it's turned ON

## Steps to Reproduce

   1. Clean profile 0.70.117
   2. Navigate to Additional settings under `chrome://settings/`
   3. Make sure `Automatically send crash reports to brave` switch is Turned OFF by default
   4. Click on the switch to make it ON (1st click doesn't do anything 2nd click makes switch enable)
   5. Click on `Restart` button
   6. Afte browser restart crash report switch is Turned OFF again

## Actual result:

After browser restart, the switch is turned OFF
![crash report toggle issue](https://user-images.githubusercontent.com/38657976/66891739-864ad800-f007-11e9-8e3d-ca063e25d5b8.gif)

## Expected result:
After enabling toggle the switch `Automatically send crash reports to brave` should be in ON state after every browser restart

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.70.117 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? - The switch is turned ON by default
- Can you reproduce this issue with the dev channel? - The switch is turned ON by default
- Can you reproduce this issue with the nightly channel? Yes- reproduced

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @bsclifton @kjozwiak

**Comment by btlechowski** [comment]
Reproduced on Ubuntu 18.04

Brave | 0.70.117 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Linux

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

Verified STR from the description.
Verified the ability to change the switch state.
Verified that the crash report was automatically sent to the server.

![image](https://user-images.githubusercontent.com/34715963/67395258-ead8da80-f5a5-11e9-96e0-2d956590a6fa.png)
