### ISSUE TITLE
widevine not working on certain websites (Netflix/Amazon Prime)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6497]
## Description 

Looks like Netflix and other websites that are using Widevine stopped working with builds using `78.0.3904.50`. Examples:

* Netflix - currently broken and doesn't play media
* Amazon Prime Video - currently broken and doesn't play media
* YouTube - seems to be working

## Steps to Reproduce

**`Case #1`**

   1. launch `0.70.117 CR: 78.0.3904.50` and login into netflix.com
   2. install Widevine and attempt to play content

**`Case #2`**

   1. launch `0.70.117 CR: 78.0.3904.50` and login into https://www.primevideo.com
   2. install Widevine and attempt to play content

## Actual result:

<img width="1214" alt="Screen Shot 2019-10-16 at 2 31 03 AM" src="https://user-images.githubusercontent.com/2602313/66895799-993ab980-efc1-11e9-84c0-27b14f475cb8.png">

<img width="1022" alt="Screen Shot 2019-10-16 at 2 33 30 AM" src="https://user-images.githubusercontent.com/2602313/66895797-993ab980-efc1-11e9-99cb-f69285e50c54.png">

<img width="1158" alt="Screen Shot 2019-10-16 at 3 07 14 AM" src="https://user-images.githubusercontent.com/2602313/66896444-ca67b980-efc2-11e9-9732-8999f19825e9.png">

## Expected result:

Netflix should be working and playing content without any issues/errors.

## Reproduces how often: 

100% reproducible when using the above STR.

## Brave version (brave://version info)

Brave | 0.70.117 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | macOS Version 10.14.6 (Build 18G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

## Miscellaneous Information:

CCing @rebron @bsclifton @brave/legacy_qa

**Comment by btlechowski** [comment]
@kjozwiak does page reload fixes the issue?

Similar issue https://github.com/brave/brave-browser/issues/4646

Not reproducible on Ubuntu. Maybe because on Linux user is forced to restart browser after installing Widevine.

Brave | 0.70.117 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Linux

![image](https://user-images.githubusercontent.com/34715963/66928445-aa231380-f031-11e9-9371-4d89727aad95.png)

**Comment by simonhong** [comment]
@btlechowski No, reloading doesn't help. This is Widevine VMP(Verified Media Path) issue.
And VMP is not enabled on linux. So, linux should not have this issue.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified Widevine install for Netflix on clean profile. Confirmed able to stream video without error.
* Verified Widevine install for Amazon Prime on clean profile. Confirmed able to stream video without error.
* Verified Widevine install for YouTube on clean profile. Confirmed able to stream video without error.
