### ISSUE TITLE
Turn OFF Ads switch and restart browser will remove viewed ads history completely.

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#6499]
## Description 

Turn OFF Ads switch and restart browser will remove viewed ads history completely.

## Steps to Reproduce

   1. Clean profile 0.70.117
   2. Enable rewards and set 4 ads per hour in ads panel
   3. View an ad
   4. Reload brave://rewards and verify ads history
   5. Turn OFF ads switch and restart the browser
   6. Turn on Ads switch
   7. Ads history link is not shown in ads panel even after multiple page reloads
   8.  View 2nd ad
   9. Ads history link is shown but it has 2nd ads history only, 1st ads history completely vanished

## Actual result:

Turn OFF Ads switch and restart browser will remove viewed ads history completely.

Viwed three ads
![image](https://user-images.githubusercontent.com/38657976/66900540-a1731300-f01a-11e9-91a2-7041c513b42c.png)

Due to above issue only 3rd ad history is available
![image](https://user-images.githubusercontent.com/38657976/66900558-ab951180-f01a-11e9-81ea-2a60b9ceb8ee.png)

## Expected result:
Ads history should not be removed

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.70.117 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not sure
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the dev channel? Not sure
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @tmancey @jsecretan @rebron

**Comment by jsecretan** [comment]
I think this is probably expected behavior for now.
