### ISSUE TITLE
Opening Non-Brave URL Links UnMaximizes Full Screen

### ISSUE THREAD

**Issue by joesixpack** [brave/brave-browser#6501]
Clicking on any URL link provided in other applications to open up in Brave will open a new tab but also undo the maximize/full screen, i.e. it goes back to windowed mode at the (smaller) size settings it was last used at.

![image](https://user-images.githubusercontent.com/23145642/66908020-48c25c80-efbf-11e9-8113-902fdcad40c2.png)

**Comment by srirambv** [comment]
Not sure I understand the issue clearly. Could you please record the behaviour and share?

**Comment by rebron** [comment]
Closing. We can reopen when we get more info.

**Comment by joesixpack** [comment]
Sorry for the delay.  Here's a short edited video.  Maximized, Click URL Link, Windowed.

[Brave.zip](https://github.com/brave/brave-browser/files/4497183/Brave.zip)
