### ISSUE TITLE
Some websites refuse to connect in Brave when shields are up

### ISSUE THREAD

**Issue by phanirithvij** [brave/brave-browser#6507]
## Description 

Some websites open on chrome but won't open on brave
Examples: 
 1. `https://pasteboard.co/ICimXkq.png`
 2. `https://twist.moe/a/one-punch-man/first`

## Steps to Reproduce

   1. Visit `https://pasteboard.co/ICimXkq.png` in brave
   2. Visit `https://pasteboard.co/ICimXkq.png` in chrome/firefox

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

```

Brave | 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | Windows 10 OS Version 1903 (Build 18362.418)
JavaScript | V8 7.7.299.13
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-features=NewExtensionUpdaterService,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AudioServiceOutOfProcess,UnifiedConsent,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\Rithvij\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by phanirithvij** [comment]
**Note**: Those sites does not have any ads/anti adblocking scripts but the main content itself is not visible when shields are up.
This makes those websites not useful when visiting through Brave.
Some whitelisting needs to be done?
Or do the users needs to sheilds down for those websites?

**Comment by rebron** [comment]
@phanirithvij Will need to use shields down for those websites. Not going to whitelist these sites.

**Comment by rebron** [comment]
@phanirithvij Going to close this issue out as non-actionable. Shields down is the solution here.
