### ISSUE TITLE
Ads remain blocked even when shields are down

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#651]
## Description 
Ads remain blocked even when shields are down. Suspect this also affects HTTPS Everywhere and Tracking Protection.

## Steps to Reproduce

   1. Disable shields
   2. Restart browser
   3. Visit a site with banner ads

## Actual result:
Ads remain blocked.

## Expected result:
Ads should be visible.

## Reproduces how often: 
Always.

## Brave version (about:brave info) 
Current master

**Comment by emerick** [comment]
I suspect the problem may be related to this comment:

https://github.com/brave/brave-core/blob/693cf450922e98fed28e69a56be5289e67ca819d/components/brave_shields/browser/brave_shields_util.cc#L68

**Comment by emerick** [comment]
What I'm seeing is a bit more subtle than the description indicates. The correct thing is happening when shields are up or down (or, more specifically, when ad blocking is enabled or disabled). You can see via DevTools that requests for ad-based resources are cancelled as expected.

The issue is that when ads are allowed, some types of ads remain blocked on certain sites. Via debugging, it seems that it's not the ad blocker that's blocking these ads but some other component.

**Comment by bbondy** [comment]
QA notes:
I tested on slashdot.org and could reproduce before the fix.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

I have checked several sites. Could not reproduce the issue.
