### ISSUE TITLE
Grant Details Button Text/Style Update

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#6510]
Per @bradleyrichter the grant details dropdown in the wallet panel should updated to the following copy and color scheme: 

<img width="379" alt="Screen Shot 2019-10-16 at 1 42 56 PM" src="https://user-images.githubusercontent.com/8732757/66964004-1e59b900-f02a-11e9-94f1-b254dec51c67.png">

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.71.108 Chromium: 78.0.3904.87 (Official Build) beta (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the description mentioned in the issue.
![image](https://user-images.githubusercontent.com/38657976/68109053-a3d8d680-ff0f-11e9-9df4-9f9b50b5bfe7.png)
![image](https://user-images.githubusercontent.com/38657976/68109067-ac311180-ff0f-11e9-8a41-000ceb9cff71.png)
