### ISSUE TITLE
Disabled Rewards Settings Pane Icons should be smaller

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#6511]
These currently display too large and close to the text, it should look more like: 

![image (8)](https://user-images.githubusercontent.com/8732757/66964182-bbb4ed00-f02a-11e9-96d2-7e874b62de50.png)

**Comment by btlechowski** [comment]
@ryanml 0.71.x uses the old icons and I think the old icons are too small. What do you think?

![image](https://user-images.githubusercontent.com/34715963/68123881-5b6ce900-ff0e-11e9-92e6-95a6f6658861.png)
![image](https://user-images.githubusercontent.com/34715963/68123900-66277e00-ff0e-11e9-8261-097881e691e1.png)

It comparison, this is how 0.73.x looks like with new icons:
![image](https://user-images.githubusercontent.com/34715963/68124050-b6064500-ff0e-11e9-8515-1a3ff9d06372.png)
![image](https://user-images.githubusercontent.com/34715963/68124078-be5e8000-ff0e-11e9-8a73-6ad2b501f526.png)

**Comment by mandar-brave** [comment]
@bradleyrichter  @ryanml

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.71.111 Chromium: 78.0.3904.87 (Official Build) (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Ubuntu 18.04 LTS

Verified STR from the description, the icons are smaller but they are old icons. Logged https://github.com/brave/brave-browser/issues/6756
