### ISSUE TITLE
restore tab context menu items

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#6513]
https://bugs.chromium.org/p/chromium/issues/detail?id=515930

## Description 
Chromium 78 removed items from the tab context menu. We should restore those menu items back. 

## Actual result:
<img width="197" alt="Screen Shot 2019-10-16 at 4 41 40 PM" src="https://user-images.githubusercontent.com/5951041/66966989-1868d580-f034-11e9-9007-7a2a0bc80ee0.png">

## Expected result:
<img width="258" alt="Screen Shot 2019-10-16 at 4 43 43 PM" src="https://user-images.githubusercontent.com/5951041/66967014-30405980-f034-11e9-862b-b582aaead323.png">

## Brave version (brave://version info)
Introduced in 70.x with Chromium 78 update.
Version 0.70.117 Chromium: 78.0.3904.50

**Comment by rebron** [comment]
cc: @petemill

**Comment by fmarier** [comment]
It's still available, but only with right-clicking on the tab bar, right of the "new tab" button (plus sign):
![Screenshot_from_2019-10-25_10-06-38](https://user-images.githubusercontent.com/167821/67590406-d3b5fc00-f70f-11e9-933e-6e099c38556b.png)

**Comment by petemill** [comment]
Closing groups of tabs can now be done with multi-selecting tabs via ctrl / cmd, which allows for more selective options than simply "other" tabs.

Re-opening tabs can now be done with the 'History' menu, which provides more than just the most-recently-closed tab. Keyboard shortcut is also unaffected.

Not saying we shouldn't restore, just that there are new ways which are more powerful UX to begin to instruct users about.

**Comment by fasterthan** [comment]
> Closing groups of tabs can now be done with multi-selecting tabs via ctrl / cmd, which allows for more selective options than simply "other" tabs.
> 
> Re-opening tabs can now be done with the 'History' menu, which provides more than just the most-recently-closed tab. Keyboard shortcut is also unaffected.
> 
> Not saying we shouldn't restore, just that there are new ways which are more powerful UX to begin to instruct users about.

There seem to be a lot of people on the internet, myself included, wanting the previous items in the context menu to be restored.

**Comment by rebron** [comment]
@fasterthan I'm in that group. This one is already in progress.

**Comment by bsclifton** [comment]
Reverted with https://github.com/brave/brave-core/pull/3874

**Comment by simonhong** [comment]
@rebron @bsclifton, chromium re-added `Close Other tabs` menu to c79.
I think most users concerned that menu and chrome team decided to re-add it.
Is it ok to wait c79?
Or adding in advance to master?
Also, do we want all other items such as `bookmark all tabs` and `reopen closed tab/window`?

I pushed PR(https://github.com/brave/brave-core/pull/3875) but it should be modified according to our decision.

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` until comment from https://github.com/brave/brave-browser/issues/6513#issuecomment-549642802 is addressed.

Also, this issue is marked as 1.2.x but PR is in 1.3.x - should milestone for this issue be moved @rebron ?

**Comment by fasterthan** [comment]
> @rebron @bsclifton, chromium re-added `Close Other tabs` menu to c79.
> I think most users concerned that menu and chrome team decided to re-add it.
> Is it ok to wait c79?
> Or adding in advance to master?
> Also, do we want all other items such as `bookmark all tabs` and `reopen closed tab/window`?
> 
> I pushed PR([brave/brave-core#3875](https://github.com/brave/brave-core/pull/3875)) but it should be modified according to our decision.

Is this the best place for a user to provide feedback? If so, I'd prefer "reopen closed tab" to return to the menu :)

**Comment by bsclifton** [comment]
@fasterthan it's coming back! 😄 We recently fixed with https://github.com/brave/brave-core/pull/3875 and it'll be working its way through the channels

**Comment by rebron** [comment]
For https://github.com/brave/brave-browser/issues/6513#issuecomment-549642802 @LaurenWags 
yes we want `Reopened Close Tab` and `Bookmark All Tabs...` back. We can wait until 1.3 for it. 

`Close Other Tabs` was restored with 1.0.1 and Chromium 78.0.3904.108

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.38 Chromium: 78.0.3904.108 (Official Build) nightly (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3875
Verified that the Menu options actually work.

![image](https://user-images.githubusercontent.com/34715963/69794828-41e85580-11cb-11ea-930c-20de313c1469.png)
