### ISSUE TITLE
store.google.com won’t be displayed correctly

### ISSUE THREAD

**Issue by thommesborg** [brave/brave-browser#6517]
## Description 
 as of today I realized that Brave Mobile on iOS won’t display store.google.com correctly. 80% of all imaginary on this site won’t load. 

## Steps to Reproduce

   1.   Use Version 1.12.1 (19.09.20.23)
   2.  Goto store.google.com
   3.  See no images

## Expected result:
 A completely loaded and displayed site. 

## Reproduces how often: 

Always. Also after a reset of Brave with all data cleared.

**Comment by srirambv** [comment]
Have you tried disabling fingerprint? This repository is for desktop only. Please try disabling fingerprinting and check if it fixes the issue. If not please open a new issue in bravehttps://github.com/brave/brave-ios/issues/

**Comment by thommesborg** [comment]
Did so, new issue report can be found here: https://github.com/brave/brave-ios/issues/1715
