### ISSUE TITLE
Refresh status progress indicator is overlapping on pub name

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#6520]
## Description 

Refresh status progress indicator is overlapping on pub name

## Steps to Reproduce

   1. Open brave 0.70.117
   2. Enable rewards
   3. Open any publisher who has large name (two-liner)
   4. Open BR panel and click `Refresh Status`
   5. Refresh status progress indicator is overlapping on pub name

## Actual result:

Refresh status progress indicator is overlapping on pub name

![image](https://user-images.githubusercontent.com/38657976/67018716-3c521700-f119-11e9-829a-d5269e68ab04.png)

## Expected result:
Refresh status progress indicator shouldn't overlap pub name

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.70.117 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @NejcZdovc @brave/legacy_qa

**Comment by btlechowski** [comment]
Reproduced on Ubuntu

Brave | 0.70.120 Chromium: 78.0.3904.70 (Official Build) (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/67343695-4e2b2400-f536-11e9-9f40-362105337396.png)
