### ISSUE TITLE
Firefox no longer appearing in list of browsers to import from

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6521]
## Description 
Updated my FF version and it no longer appears in the list of browsers to choose from for import in settings. 

@kjozwiak has encountered this on macOS as well.

## Steps to Reproduce

   1. Update/install/clean profile with FF 69.0.3
   2. Set up data (bookmarks, etc)
   3. Launch Brave
   4. Go to brave://settings/importData (either from Settings page or using macOS menu - Brave > Import Bookmarks and Settings).
   5. Firefox is not listed in drop down.

## Actual result:
<img width="1050" alt="Screen Shot 2019-10-17 at 10 38 41 AM" src="https://user-images.githubusercontent.com/28145373/67019959-73014080-f0cb-11e9-8d2e-66ed3d84eddb.png">

<img width="1199" alt="Screen Shot 2019-10-17 at 10 24 59 AM" src="https://user-images.githubusercontent.com/28145373/67019970-7694c780-f0cb-11e9-91b5-ca4c6c309f0f.png">

Note - Firefox does not appear in the list if it is closed either. Screenshot is just to show that Firefox is installed.

## Expected result:
Firefox should be listed in the drop down.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | macOS Version 10.13.6 (Build 17G5019)

Brave | 0.70.117 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | macOS Version 10.13.6 (Build 17G5019)

Brave | 0.71.94 Chromium: 77.0.3865.90 (Official Build) dev (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a 
- Is the issue reproducible on the latest version of Chrome? yes - 77.0.3865.120 (Official Build) (64-bit)

## Miscellaneous Information:
cc @rebron @bsclifton @kjozwiak 

cc @btlechowski @GeetaSarvadnya for other OSes

**Comment by GeetaSarvadnya** [comment]
The issue is NOT reproducible in Windows 10 x64 - 0.70.117 and 

![image](https://user-images.githubusercontent.com/38657976/67023278-2dbb2e00-f120-11e9-8b30-a9489c2b8c95.png)

**Comment by btlechowski** [comment]
Reproduced on Linux.

Brave | 0.70.117 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Linux

After installing the new version of FF 69.0.3, I got this message: 
![image](https://user-images.githubusercontent.com/34715963/67023392-073aca00-f103-11e9-8832-76d6c93a2389.png)

**Comment by rebron** [comment]
@Brave-Matt for how many users this might be affecting?

**Comment by Brave-Matt** [comment]
@rebron still trying to discern how wide spread this is but I'm still getting reports of various Firefox data that does **not** get imported:
https://community.brave.com/t/not-import-from-firefox/88691

**Comment by iefremov** [comment]
Doesn't reproduce with 
Brave | 0.73.41 Chromium: 78.0.3904.70 (Developer Build) (64-bit)

and FF 70 on linux

**Comment by iefremov** [comment]
So apparently there are some different issues:
1) Firefox is not visible in the list of browsers for import
2) The user can start import, but something is not imported (mentioned in Community https://github.com/brave/brave-browser/issues/6521#issuecomment-546415029).

Regarding the first problem, probably backporting this can help https://chromium.googlesource.com/chromium/src/+/5e3cc0612e21ce260f29cb702b0e83289f32cda2

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.1.7 Chromium: 78.0.3904.108 (Official Build) beta (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified STR from description using Firefox 70.0.1.
* Reproduced issue using 1.0.1 (currently released version) - FF was not available in import list
<img width="448" alt="Screen Shot 2019-11-21 at 10 14 07 AM" src="https://user-images.githubusercontent.com/28145373/69351681-b52d1d00-0c49-11ea-81e8-065524385b55.png">
<img width="541" alt="Screen Shot 2019-11-21 at 10 14 20 AM" src="https://user-images.githubusercontent.com/28145373/69351684-b65e4a00-0c49-11ea-9f9b-9b707b167c6a.png">

* Upgraded profile to 1.1.7 and verified FF was now appearing in the list on both brave://welcome and brave://settings/importData.
<img width="429" alt="Screen Shot 2019-11-21 at 10 20 32 AM" src="https://user-images.githubusercontent.com/28145373/69351723-c0804880-0c49-11ea-8757-e8fb9aff7be8.png">
<img width="550" alt="Screen Shot 2019-11-21 at 10 20 45 AM" src="https://user-images.githubusercontent.com/28145373/69351728-c24a0c00-0c49-11ea-9d40-72e335342705.png">

* Verified FF appears in the import list on both brave://welcome and brave://settings/importData for clean profile as well.
* Verified able to import History, Bookmarks, and Cookies from FF. Encountered https://github.com/brave/brave-browser/issues/2198 for importing Passwords, Search Engine, and Autofill data.
