### ISSUE TITLE
How to change (or help to change) browser's translate on my language?

### ISSUE THREAD

**Issue by Geradot** [brave/brave-browser#6524]
How to change (or help to change) browser's translate on my language? Has it some interface or service for translate?

**Comment by rebron** [comment]
Hi @Geradot We offer the Google Translate extension when you visit a page where you need translating. You can also download directly from here `https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb/RK%3D2/RS%3DBBFW_pnWkPY0xPMYsAZI5xOgQEE-`

**Comment by Geradot** [comment]
No, I mean not pages. For example, the title of Ctrl + W is "Close" (in context menu on tab), but in Russian it translated not correct.

**Comment by bsclifton** [comment]
@Geradot thanks for the report and sorry it took so long to reply back; I'm just now seeing this in GitHub notifications

We have a website which you can sign up for, to help provide translations:
https://www.transifex.com/brave/brave/

@mkarolin has fixed a few translations, possibly including this one. Once you sign up, you can reply back here with your Transifex username and we can help get you added to the Russian language translators
