### ISSUE TITLE
brave wallet scroll

### ISSUE THREAD

**Issue by maikelmclauflin** [brave/brave-browser#6528]
## Steps to Reproduce

unsure if this is all that is needed to reproduce. there may be someone else triggering, but i'm not modifying the browser code itself. was able to reproduce on ropsten network. have not tried mainnet

   1. open up new browser
   2. go to brave://wallet
   3. make enough transactions to fill up the list (~6-7 on a mac)

## Actual result:

unable to scroll through history of txs

## Expected result:
to be able to scroll

## Reproduces how often: 

every time brave://wallet is pulled up on screen

## Brave version (brave://version info)

tested on nightly and dev

```
Brave 0.73.6 Chromium: 78.0.3904.50 (Official Build) nightly (64-bit)
Revision 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS macOS Version 10.14.6 (Build 18G103)
JavaScript V8 7.8.279.14
Flash (Disabled)
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.50 Safari/537.36
Command Line /Applications/Brave Browser Nightly.app/Contents/MacOS/Brave Browser Nightly --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=NewExtensionUpdaterService,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,SyncUSSBookmarks,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,UnifiedConsent --flag-switches-begin --flag-switches-end
Executable Path /Applications/Brave Browser Nightly.app/Contents/MacOS/Brave Browser Nightly
Profile Path /Users/michaelmclaughlin/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/Default
```
```
Brave Software Inc
Copyright 2019 Brave Software Inc. All rights reserved.
Brave 0.71.74 Chromium: 77.0.3865.75 (Official Build) dev (64-bit)
Revision 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
OS macOS Version 10.14.6 (Build 18G103)
JavaScript V8 7.7.299.11
Flash (Disabled)
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36
Command Line /Applications/Brave-Browser-Dev.app/Contents/MacOS/Brave Browser Dev --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-features=NewExtensionUpdaterService,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=UnifiedConsent,AudioServiceOutOfProcess,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI --flag-switches-begin --flag-switches-end
Executable Path /Applications/Brave-Browser-Dev.app/Contents/MacOS/Brave Browser Dev
Profile Path /Users/michaelmclaughlin/Library/Application Support/BraveSoftware/Brave-Browser-Dev/Profile 6
```

## Version/Channel Information:

- Can you reproduce this issue with the current release?
yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
yes
- Can you reproduce this issue with the nightly channel?
yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanml** [comment]
Closed via: https://github.com/brave/ethereum-remote-client/pull/89

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Linux
Component | `0.1.29`

* Expanded transaction view for ETH
![image](https://user-images.githubusercontent.com/17010094/69460167-737f9d80-0d41-11ea-9df9-682afa8521c3.png)
* Collapsed view for ETH
![image](https://user-images.githubusercontent.com/17010094/69460023-1552ba80-0d41-11ea-8aa3-1f965761d48f.png)
* Expanded transaction view for ERC20 Token
![expanded_transacton](https://user-images.githubusercontent.com/17010094/69459329-86916e00-0d3f-11ea-9152-842f4713385d.png)
* Collapsed view for ERC20 Token
![image](https://user-images.githubusercontent.com/17010094/69460072-34514c80-0d41-11ea-8cb2-fa5a4ca46433.png)
