### ISSUE TITLE
Remove/Replace MetaFox icon from connect wallet popup

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6534]
## Description 

Remove/Replace MetaFox icon from connect wallet popup

## Steps to Reproduce

   1. Create a wallet
   2. Connect wallet popup shows MetaFox icon

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/67048533-61875b00-f102-11e9-88a1-80d3a9cc58c1.png)

## Expected result:
No Metamask branding 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel?Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@ryanbr @bbondy was this merged into https://github.com/brave/ethereum-remote-client/releases/tag/v0.1.18? I'm still seeing the MM icon in the popup windows, examples:

<img width="927" alt="Screen Shot 2019-10-30 at 11 07 04 PM" src="https://user-images.githubusercontent.com/2602313/67915901-818b3580-fb6a-11e9-9700-d21d2c3f913f.png">

<img width="955" alt="Screen Shot 2019-10-30 at 11 04 58 PM" src="https://user-images.githubusercontent.com/2602313/67915902-818b3580-fb6a-11e9-92cf-93aaef80141e.png">

@srirambv are you seeing the same thing?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
--|--
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Linux
Component | `0.1.29`

* Verified MetaFox icon is not shown on connect wallet popup
![image](https://user-images.githubusercontent.com/17010094/69283836-2b367300-0bbb-11ea-9e27-8f454ae777df.png)
