### ISSUE TITLE
Deposit transactions are not listed 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6535]
## Description 

Deposit transactions are not listed on wallet

## Steps to Reproduce

   1. Create wallet 
   2. Do a successful transaction and send ETH to a different wallet
   3. Wallet that received doesn't show deposit transaction only shows sent transactions

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/67049550-77961b00-f104-11e9-970d-e4669522913e.png)

## Expected result:
Should list both sent/deposit transactions similar to MM
![image](https://user-images.githubusercontent.com/17010094/67050190-f6d81e80-f105-11e9-8cc3-df66af6e3728.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | Linux

Component `0.1.17` and `1.0.11`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows 10 x64 - 0.70.122

![image](https://user-images.githubusercontent.com/38657976/68044447-5d139280-fcfd-11e9-844c-cc9e14ed610c.png)

**Comment by ryanml** [comment]
This is fixed in the latest upstream rebase and will be part of the next client release: https://github.com/brave/ethereum-remote-client/commits/master

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.2.41 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Linux
Component | `0.1.34`

- Verified ETH deposits shows up as expected
![image](https://user-images.githubusercontent.com/17010094/72021549-437e5200-323c-11ea-86ff-53141f98240e.png)
- Verified deposit for ERC20 Tokens is not shown (Same behaviour on MM as well)
