### ISSUE TITLE
Improve context of string (subhead) for BR Wallet Verification Dialog

### ISSUE THREAD

**Issue by bradleyrichter** [brave/brave-browser#6537]
old string (subhead)

![image](https://user-images.githubusercontent.com/13509546/67056697-fdfd2d80-f101-11e9-8566-6eb370697a02.png)

text: Verification is not necessary to earn rewards for creator contributions

New subhead text:
Verification is not necessary to contribute your rewards to creators

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` label as this has not yet been uplifted to 0.71.x

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.71.105 Chromium: 78.0.3904.70 (Official Build) beta (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | macOS Version 10.13.6 (Build 17G5019)

* Confirmed updated wording in UI is expected (note - it is slightly different than above and in the PR)
* Confirmed updated wording is shown when accessing modal from brave://rewards page `Verify Wallet` button, `Add Funds` button, `Withdraw Funds` button, and `verify` link in wallet panel footer.
* Confirmed updated wording is shown when accessing modal from panel `Verify Wallet` button and `Add Funds` button
<img width="720" alt="Screen Shot 2019-10-30 at 10 13 44 AM" src="https://user-images.githubusercontent.com/28145373/67865890-7995ac00-fafe-11e9-8491-3e6175a9a576.png">
