### ISSUE TITLE
Importing bookmarks and passwords not working

### ISSUE THREAD

**Issue by dacomboman** [brave/brave-browser#6538]
Have tried many times to import bookmarks and passwords from Firefox or Edge and even if a confirmation message popups to say it was successful, nothing really happens.

Can import from html but that's not what i want to do.

**Comment by dacomboman** [comment]
What is odd... importing from Firefox on Solus went just fine!

**Comment by rebron** [comment]
closing dupe of https://github.com/brave/brave-browser/issues/2198

**Comment by dacomboman** [comment]
Latest edition has Firefox import all fixed up!
Thank you! ;)

**Comment by bsclifton** [comment]
Awesome, thanks for confirming, @dacomboman 😄👍
