### ISSUE TITLE
Untranslated text on connect hardware screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6539]
## Description 

Untranslated text on connect hardware screen

## Steps to Reproduce

   1. Install component `0.1.17`
   2. Connect hardware option from profile
   3. Connect Trezor with desktop, untranslated text show up 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/67058628-9eb01500-f123-11e9-89d1-fe31c8cbbd9a.png)

## Expected result:
Should have all text translated

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | Linux

Component `0.1.17`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Reproduced the issue 2 times on Trezor

**Comment by srirambv** [comment]
Reproduced on Windows as well. Doesn't seem to be intermittent as I previously thought.  
![image](https://user-images.githubusercontent.com/17010094/67092857-4fe39900-f17e-11e9-87f8-91391f05c116.png)

**Comment by srirambv** [comment]
Steps to reproduce the issue
- Create a wallet 
- Connect hardware
- Select Trezor
- Click connect, new tab opens to export public keys 
- Close the tab and go back to wallet page
- Connect hardware page has the untranslated text

You can alternately use a VM and disconnect the USB device from VM to reproduce the issue

**Comment by kjozwiak** [comment]
Changing this to a `P2`. I think we need to fix sooner than later. You'll need to download the `Trezor Bridge` if you want to use the Trezor. The current UX flow is pretty confusing:

* Connect to the Trezor and you'll be taken to https://wallet.trezor.io/ 
* Click on `Install Bridge` and nothing happens but you'll be returned to `brave://wallet` and you'll notice the `[object object]` error.

**Comment by bbondy** [comment]
@srirambv is this working now?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.5.76 Chromium: 80.0.3987.66 (Official Build) nightly (64-bit)
-- | --
Revision | 56ea77d65c47ecbb1180b99f860d85b51117864a-refs/branch-heads/3987@{#662}
OS | Linux
Component | `0.1.37`

- No untranslated text is shown on connect hardware screen
![image](https://user-images.githubusercontent.com/17010094/73638269-1fbdf880-4690-11ea-87d6-5715fb83e102.png)
