### ISSUE TITLE
Icon bug on Congratulations bit during Crypto Wallet creation

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#6542]
Have you searched for similar issues? Yes.

## Description 
I didn't know whether the bit above congratulations was a translation issue but it's typically what shows up when certain foreign languages aren't supported in brave. In addition, I don't expect to remove and re-create the wallet again so there wouldn't be a way for me to check if it was fixed after the next couple of updates, thus didn't want it to be missed.

## Steps to Reproduce

   1. Head to Crypto Wallet 
   2. Create a new wallet
   3. Complete creation of wallet

## Actual result:
![image](https://user-images.githubusercontent.com/31957540/67071344-2aed2700-f17a-11e9-879b-931fba7db968.png)

## Brave version (brave://version info)
Version 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit) (Linux-OpenSuse)

**Comment by srirambv** [comment]
This specific to OS. OpenSuse doesn't have that icon. Same behaviour with Metamask as well
![image](https://user-images.githubusercontent.com/17010094/67133539-489ea880-f1db-11e9-8e8d-aa71e87faa8c.png)

This most possibly be wontfix.
cc: @ryanml @bbondy

**Comment by rebron** [comment]
Closing. This looks like a distribution issue. They don't have the icon or possibly renamed differently. We'll wait for an upstream Metamask fix for this one.
