### ISSUE TITLE
receiving Insufficient Funds/AC can't be completed messages incorrectly - follow up to 6288

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6546]
## Description 
Found while testing #6288 

While testing 6288, if I restart my browser, upon reopening I get a message that I have insufficient funds. I have 30 BAT in my wallet and we have changed the logic as described in #6288 and #6228. 

Additionally, recurring tips and AC are completed with my wallet balance, however, after auto contribute completes, I get a message saying that AC couldn't be completed and we will try again in 30 days. This is not true as AC was just completed.

## Steps to Reproduce

1. enable rewards with short contribution interval on staging
2. claim grant (30 BAT)
3. set AC amount to `Up to 20 BAT`
4. add verified and unverified publishers to AC table
5. add recurring tips for verified publishers in this order (5, 10, 10, 10)
6. Restart browser
---> See notification about Insufficient Funds. Dismiss it.
7. wait for monthly contribution to trigger
8. you should see 25 BAT goes through for monthly and 5 BAT from AC
---> Get notice that AC couldn't be completed, will try again in 30 days message. 
Note - both AC and recurring tips appear to have been contributed.

## Actual result:
This is the first message I receive, before AC/recurring tip contribution starts:
<img width="429" alt="6288-msg1" src="https://user-images.githubusercontent.com/28145373/67111531-1ffabc80-f1a3-11e9-938b-6cc6985c6ea9.png">

This is the message I receive after AC has contributed (in addition to the expected one which indicates AC was successful):
<img width="470" alt="6288-msg2" src="https://user-images.githubusercontent.com/28145373/67112420-30ac3200-f1a5-11e9-8a83-e98f5457b3c9.png">

## Expected result:
No messages. I do not have insufficient funds and AC did complete.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.73.8 Chromium: 78.0.3904.50 (Official Build) nightly (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the dev channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @NejcZdovc @rebron @brave/legacy_qa

**Comment by LaurenWags** [comment]
Here's a gif picking up with step 6 (note, I did pause in the middle because I accidentally set my reconcile time to 30 minutes). After the pause (at about 1min 30s), the gif picks up just before monthly recurring tip/AC contribution in step 7 and then is shown in real-time.
![notification-gif](https://user-images.githubusercontent.com/28145373/67112767-fd1dd780-f1a5-11e9-8afb-854ffc13d2c9.gif)

**Comment by LaurenWags** [comment]
Per discussion in today's Rewards/Ads Mtg, here is some information for historical purposes. 

The first notification - the one for Insufficient Funds - is expected and there won't be any change to this.

The second notification - the one stating that AC could not be completed and will try again in 30 days - is what needs a wording change.

@NejcZdovc @mandar-brave please correct if the above is incorrect.

**Comment by mandar-brave** [comment]
@davidtemkin here is my suggestion for the second notification change. The first one is correct. Here is the image ---
![image](https://user-images.githubusercontent.com/35932307/67236100-706d5680-f3fd-11e9-8cf3-48ec743fa71b.png)


Instead of "Your scheduled...", reword to " Some of your.." I would add action at a later date to check statements when we are ready with them!

cc @NejcZdovc

**Comment by mandar-brave** [comment]
@NejcZdovc can we eliminate any error messages for a/c completely and never show a/c in the error message?
And then use the "Some of your monthly Tips" for the error.

**Comment by NejcZdovc** [comment]
well we will only show AC error if your balance is 0

**Comment by NejcZdovc** [comment]
closing as stale
