### ISSUE TITLE
Weird highlighting performance on StackOverflow

### ISSUE THREAD

**Issue by derekantrican** [brave/brave-browser#6547]
## Description 
I've seen this for a while now, but there seems to be weird highlighting performance when attempting to click and drag to highlight a **scrollable code block** on StackOverflow.com

Here is a screenshot:

![screenshot](https://i.imgur.com/6lucupN.gif)

## Steps to Reproduce

   1. Go to this page: https://stackoverflow.com/a/14906422/2246411
   2. Attempt to highlight all code in the scrollable code block by clicking and dragging *(Note that the weird behavior only seems to happen once the mouse moves such that the code block starts scrolling)*
   3. Notice that it is very difficult to highlight the whole code block with this method

## Actual result:

(Screenshot above)

## Expected result:

Should be work as highlighting usually does in any other browser

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.68.141 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Windows 10 OS Version 1809 (Build 17763.805)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by user1313** [comment]
As well as in Brave 0.69.135 here, I get the same weird highlighting issues on the link you provided while using Chrome Canary 79.0.3944.0. Are you sure this is Brave-specific?

**Comment by derekantrican** [comment]
I've never seen this issue while using Chrome and I'm add developer so I use stackoverflow all the time. But I also haven't used a canary build of Chrome

**Comment by bsclifton** [comment]
I believe this was fixed upstream - unable to reproduce
