### ISSUE TITLE
Make silent installation package on Windows

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#655]
Carried over from https://github.com/brave/browser-laptop/issues/2222

Basically, like an MSI package. Something for easily deploying on a corporate infrastructure

**Comment by JonasDralle** [comment]
also helpful for #1006

**Comment by bsclifton** [comment]
Closing as this has been completed by @mbacchi 🎉 You should see silent install binaries on our [releases page](https://github.com/brave/brave-browser/releases)
