### ISSUE TITLE
Implement client side changes of sync compaction

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#6552]
There will be a compaction API that closes
https://github.com/brave/sync/issues/341

Client will call compaction API every week

**Comment by btlechowski** [comment]
Blocked on https://github.com/brave/brave-browser/issues/6941

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as both https://github.com/brave/brave-core/pull/4407 & https://github.com/brave/brave-core/pull/4408 have been merged. Once we get a new `1.3.x` build that's `> 1.3.100`, QA should be able to verify this issue.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.3.113 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3749

**Update**
![image](https://user-images.githubusercontent.com/38657976/74036159-bcaac980-49e1-11ea-9ff2-cc41bdd4a814.png)

![image](https://user-images.githubusercontent.com/38657976/74036130-adc41700-49e1-11ea-9110-cf16fa16632a.png)

**Delete**

**Comment by AlexeyBarabash** [comment]
@GeetaSarvadnya I was able to verify **Delete** case:
seeing exactly `"sync-debug" message="got 1 decrypted records in BOOKMARKS after 0"`
![image](https://user-images.githubusercontent.com/24739341/74042758-cd067880-49d0-11ea-8fbb-336852ae7972.png)
