### ISSUE TITLE
Ads / Ads History: "untargeted" category - suggested change

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#6553]
## Description 

For the Ads History panel, we currently show an "untargeted" category. 

Suggest changing the category name from "untargeted" to "general" or "run of browser." 

The reason: we're moving away from traditional advertising models, including terminology, to make for a more inclusive, people-first experience. 

The current landscape outside of Brave treats people as users, and targets. Users are addicted to a clickbait-addled web, where they're targeted and mowed over with ads. 

People aren't targeted with ads in Brave Ads; Brave Ads are matched based on the opportunity within the client. 

With the way that the "untargeted" ads are being deployed, going with something like  "general" or "run of browser" would 1) be a better fit with the ad model and 2) be a better optic fit for people and brands. 

That's the other piece here. We're selling to brands based on our local matching model. By bucketing under "untargeted", advertisers might view that classification in a negative light, given the value prop they were presented. 

## Steps to Reproduce

   1. Open brave://rewards
   2. Go to Ads History
   3. (hopefully) see an ad that was matched to the "untargeted" category

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by tmancey** [comment]
Blocked awaiting final Copy

**Comment by jenn-rhim** [comment]
Agree on your points, @lukemulks. I’d vote for ‘General’.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.8.71 Chromium: 81.0.4044.92 (Official Build) dev (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/5012
* Verified for clean profile with 1.8.x:
<img width="1141" alt="Screen Shot 2020-04-10 at 9 52 07 AM" src="https://user-images.githubusercontent.com/28145373/78995720-03678d80-7b11-11ea-8dd3-cf9ed3dca410.png">

* Verified for upgrade profile:
1.7.x:
<img width="1195" alt="Screen Shot 2020-04-10 at 9 49 10 AM" src="https://user-images.githubusercontent.com/28145373/78995754-167a5d80-7b11-11ea-8a82-9fac90d34ddd.png">

after upgrading to 1.8.x:
<img width="1196" alt="Screen Shot 2020-04-10 at 9 48 51 AM" src="https://user-images.githubusercontent.com/28145373/78995747-14b09a00-7b11-11ea-850e-9810aab5b37a.png">
