### ISSUE TITLE
Netflix Broken on 72.106 Dev

### ISSUE THREAD

**Issue by TDeisinger** [brave/brave-browser#6554]
## Description 

When loading any option for streaming on Netflix.com, an error pops up -  M7121-1331

This is essentially the "Browser Unsupported" Error

This occurred on two different PCs with version 72.106 installed. Both erred the same way.

## Steps to Reproduce

   1. Log on to Netflix.com
   2. Select any streaming title
  

## Actual result:

![image](https://user-images.githubusercontent.com/36009507/67134647-ca410700-f1d8-11e9-8b72-60f7a377bc8c.png)

## Expected result:

Title working correctly - as it does on current Chrome version

## Reproduces how often: 

100% on version 72.106

## Brave version (brave://version info)

Version 0.72.106 Chromium: 78.0.3904.50 (Official Build) dev (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by M1ch431** [comment]
Can confirm that this happens on Nightly as well.

**Comment by docloulou** [comment]
same here even with .108 :(

**Comment by bsclifton** [comment]
Thanks for the report folks 😄 This is a known issue and was captured with https://github.com/brave/brave-browser/issues/6497

Should be fixed with https://github.com/brave/brave-core/pull/3766 - I'll start a new build so that you all get the fix 😄 (hang tight - this could take a few hours)

**Comment by bsclifton** [comment]
Quick update - this should be fixed on Nightly
cc: @M1ch431

**Comment by TDeisinger** [comment]
Can confirm netflix now works on 72.109
