### ISSUE TITLE
Less expensive upgrade process on macOS (delta installer)

### ISSUE THREAD

**Issue by jromero2k** [brave/brave-browser#6555]
## Description 

About every 7 days, my (macOS 10.14, desktop) Brave upgrades to a (usually minor) new version. From my experience so far, it's about a 100MB download. In my country (🇨🇺) that's ends up costing around *USD $7 monthly* for cellular data. Considering that the average salary here is $30-$40, that's way too much (and no, there's no free wi-fi..)

## Steps to Reproduce

   1.  Use Brave
   2. Periodically it will consume about 100MB downloading updates
   3. 

## Actual result:

Using the theoretically free Brave browser costs about USD $7 every month

## Expected result:

1. The upgrade process should be a separate application that can be easily blocked, if needed.

2. The settings should allow control of the update process (eg, only update for major versions, notify when a high-priority security upgrade is needed, upgrade only when not metered, etc.) Currently the only thing we can do is restart the upgrade from chrome://settings/help

3. The update process should be more efficient (smaller downloads by using a vX-to-vCURRENT patch like Google does, the download is fully resumable, and only corrupt fragments are redownloaded-as-needed like torrents can do)

## Reproduces how often: 

Usually every week

## Brave version (brave://version info)

Any current or previous version

**Comment by rebron** [comment]
cc: @bkero. We should probably define this in a different issue for patch upgrades.

**Comment by jromero2k** [comment]
Please, if enhancing the update infrastructure is not a priority, at least provide a way to pause updates or ask for user's consent before downloading. It's costing more than $10/monthly. Too much for a product that's supposed to be free, not to mention there are much better ways to spend that amount (than supporting a state monopoly)

**Comment by bsclifton** [comment]
@jromero2k it definitely is a priority - @simonhong is working on this now 😄 We're tackling Windows first with https://github.com/brave/brave-browser/issues/9565. I believe he was able to get a delta installer created that was only 3MB in size

@simonhong is Sparkle (macOS) able to take advantage of these changes too? Or just Omaha?

**Comment by simonhong** [comment]
Currently my work is only for windows installer.
Need to investigate it's possible to enable delta installer on macOS.

**Comment by simonhong** [comment]
Sparkle's `BinaryDelta` treats directory symlink as a file instead of directory.
 and it generates files delta only for same file path.
Due to this, different versioned two browser apps will have huge delta file. (App will have different versioned framework bundle). 
Currently, I'm trying to generate only delta for files in `/Contents/Frameworks/Brave Browser Framework.framework/Versions/Current/` because `Current` occupies of most if app's data size.

**Comment by simonhong** [comment]
Verified Below process works

* Delta creation step (by running `BinaryDelta create ...`
  * Generate delta from all files in `Brave Browser.app` bundle except `Brave Browser.app//Contents/Frameworks/Brave Browser Framework.framework/Versions/`.
  * Generate delta from all files in `Brave Browser.app//Contents/Frameworks/Brave Browser Framework.framework/Versions/Current`
 
* Delta applying step (by running `BinaryDelta apply ...`
  * Applying delta files generated from above step.
  * Then all files are updated and only `Brave Browser Framework.framework/Versions/86.1.18.3` directory name is not changed yet
  * Just rename `86.1.18.3` to `86.1.18.4`

With these two steps, newly patched App from `86.1.18.3` with delta files has same hash with `86.1.18.4`

**Comment by mihaiplesa** [comment]
All related work has been merged and production has been updated.

Nightly users on 1.18.41 and up will be served delta updates.
