### ISSUE TITLE
Brave blocking Bitwarden from properly working when using "On Click" activation

### ISSUE THREAD

**Issue by dirad** [brave/brave-browser#6557]
## Description 
Bitwarden extension is being prevented from creating new items when using it in "On Click" mode.

## Steps to Reproduce

   1. Go to extension manage page and switch Bitwarden to "On Click" mode
   2. Open a new tab or refresh any tab and open the Bitwarden popup
   3. Make a new login item in Bitwarden and click save

## Actual result:
 A error citing "Failed to fetch" appears.

## Expected result:
A new item is being created and saved.
Allowing the extension to run "On all sites" allows it to work properly.

## Reproduces how often: 
Every time

## Brave version (brave://version info)

Brave | 0.72.106 Chromium: 78.0.3904.50 (Official Build) dev (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Windows 10 OS Version 1809 (Build 17763.805)
JavaScript | V8 7.8.279.14
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.50 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser-Dev\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=NewExtensionUpdaterService,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,UnifiedConsent,SyncUSSBookmarks --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser-Dev\Application\brave.exe

## Version/Channel Information:

I am using Dev and did not test other channels but others have, and some commentators mention Brave in the comments.

https://www.reddit.com/r/Bitwarden/comments/bj4953/local_selfhosting_raspberry_pi_3_failed_to_fetch/
https://www.reddit.com/r/Bitwarden/comments/ap9iyr/failed_to_fetch_errors_on_desktop_app/

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No, it works fine

**Comment by rebron** [comment]
@dirad Can you check your global shields settings? In cookies, set it to allow all and see if that works.

**Comment by thefirstofthe300** [comment]
I am trying out Brave for the first time and ran into this issue as well.

In settings under Shields, I set "Cookies" to "Allow all cookies" and Bitwarden was then able to autofill fields.

**Comment by bsclifton** [comment]
@thefirstofthe300 welcome - hope you're enjoying so far 😄 

When you say you had to adjust shield settings, did you have to adjust just once (and then it worked)? Or do you have to adjust for all sites that you'd like to use Bitwarden on?

**Comment by thefirstofthe300** [comment]
I only had to adjust the settings once. Since then, I've turned tracking back on, and I haven't had an issue with autofill.

**Comment by dirad** [comment]
@rebron - The issue persists even when the cookies shield are set to "Allow all cookies" .
The only way it works for me is setting the extension to "read and change site data - _on all sites_"


Regarding @thefirstofthe300 's comment - the issue isn't with autofill but with creating new entries.

**Comment by ryanbr** [comment]
Hey @dirad   Is this still an issue, I'm a regular user of Bitwarden. I haven't needed to change any shield settings

**Comment by dirad** [comment]
@ryanbr Just tested, it is still an issue.
In order to confirm: Try switching ot "On Click" activation
Open a new tab with any website
click the Bitwarden logo to activate [allow reload tab]
then try to save any detail. For example a secure note .  
You should see an error message.

**Comment by ryanbr** [comment]
I don't see "On Click" or "On Click activation" in my Bitwarden settings @dirad

**Comment by ryanbr** [comment]
Also checked that "Autofill" in Bitwarden, works fine without adjusting shield settings

**Comment by dirad** [comment]
It isn't a bitwarden feature, but a brave one.
It allows you to control when the extension runs.
You can choose this setting in the extension management preferences, or by
right-clicking on the extension icon in the menu.

**Comment by ryanbr** [comment]
Just tested this (using random chars in both Brave/Chrome), @dirad 
![test-bw](https://user-images.githubusercontent.com/1659004/115481610-1626ad80-a2a1-11eb-9830-8aebead08b82.png)

It occurs in Chrome also. https://github.com/bitwarden/browser/issues/1747

**Comment by ryanbr** [comment]
Closed, was fixed upstreeam
