### ISSUE TITLE
"Include in Auto-Contribute" is turned off for a few websites

### ISSUE THREAD

**Issue by ranjanagit** [brave/brave-browser#6558]
## Description 
"Include in Auto-Contribute" is turned off for a few websites

## Steps to Reproduce

   1.  Open a new profile
   2. Enable rewards
   3. Visit Amazon.in in a new tab.
   4. Click on the BAT icon on the browser window
   5. Notice that ""Include in Auto-Contribute" is turned off by default

## Actual result:
"Include in Auto-Contribute" is turned off by default for the below few websites
amazon.in
flipkart.com
https://www.pepperfry.com/
https://www.urbanladder.com

![Include in auto-contribute](https://user-images.githubusercontent.com/56768759/67149865-33ef0d00-f2ce-11e9-8575-a7b683e0f16e.png)

## Expected result:
"Include in Auto-Contribute" should be turned on by default for all the websites

## Reproduces how often: 
Can be reproduced 

## Brave version (brave://version info)
v 0.69.135

## Version/Channel Information:
this issue happens for few websites

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
some e-commerce and gov sites are excluded by default
