### ISSUE TITLE
Some ads regions are unavailable on Ubuntu after changing system locale

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6560]
Follow up to https://github.com/brave/brave-browser/issues/5655

Important: the issue does not reproduce when Clean installed Ubuntu thus majority of users will not be affected. More info https://github.com/brave/brave-browser/issues/6560#issuecomment-544678432

On Ubuntu System language determines the ads region.
Limited number of locales makes it impossible to enable ads.
This is most prominent for `Spanish` locale, which will disable ads for all Spanish speaking countries.

## Steps to Reproduce

1. Setup system locale on Ubuntu (check below for instructions)
2. Clean install Brave
3. Run Brave
4. Enable rewards
5. Open `brave://rewards`

**Setting up system locale:**
1. Open `Language Support` in Ubuntu
![image](https://user-images.githubusercontent.com/34715963/67169531-1bedbb00-f3ac-11e9-9326-392b496c6cb8.png)
2. Install `Spanish` language
3. Make `Spanish` default system locale
![image](https://user-images.githubusercontent.com/34715963/67169627-9b7b8a00-f3ac-11e9-974d-90dada3405a9.png)
4. Click `Apply System-Wide`
5. Click `Regional Formats` at the top
![image](https://user-images.githubusercontent.com/34715963/67169645-c960ce80-f3ac-11e9-9199-bcf5864beef2.png)
6. Change the `Regional Formats` to `Espanol(Argentina)`
7. Click `Apply System-Wide`
8. Restart system

Affected locales:
Argentina es_AR
Chile es_CL
Colombia es_CO
Ecuador es_EC
Mexico es_MX
Peru es_PE
Venezuela es_VE

## Actual result:

ads are unavailable in this region
The `locale` command shows the following
![image](https://user-images.githubusercontent.com/34715963/67169770-d205d480-f3ad-11e9-8b82-6101620b4837.png)
Locale used to show ads is `en_ES`
Since `en_ES` is not supported ads region, the ads are unavailable
![image](https://user-images.githubusercontent.com/34715963/67169831-43458780-f3ae-11e9-8ed3-f2982cffd7e6.png)

Note: It is possible to manually overwrite the system locale before launching Brave (clean install) and that fixes the issue.
`LANG=es_AR.UTF-8 LANGUAGE=es_AR  /usr/bin/brave-browser`

Note: the most obvious way to fix it is to use `Regional Formats` which allows to set the right region.

## Expected result:
ads are available
Locale used to show ads is `es_AR`

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.70.118 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Ubuntu 18.04 LTS

## Miscellaneous Information:

cc @tmancey @rebron @brave/legacy_qa

**Comment by srirambv** [comment]
Try running `sudo dpkg-reconfigure locales` and then select whichever locale you need. This should allow you to configure locales on Linux
![image](https://user-images.githubusercontent.com/17010094/67202773-794b3180-f3d7-11e9-94be-ca02619b08aa.png)

**Comment by btlechowski** [comment]
Dupe of https://github.com/brave/brave-browser/issues/2147

**Comment by btlechowski** [comment]
Followed the STR from the description. 
Attached logs per discussion with @tmancey.
[locale.txt](https://github.com/brave/brave-browser/files/3752028/locale.txt)
[chrome_debug.log](https://github.com/brave/brave-browser/files/3752017/chrome_debug.log)

Brave | 0.70.119 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Ubuntu 18.04 LTS

**Comment by btlechowski** [comment]
Thanks @srirambv, but it didn't work for me, even after system restart. The output from `locale` is the same as before your suggestion. Also ads are unavailable. Used locale `es_AR`. Has that actually worked for you?

**Comment by btlechowski** [comment]
Good news. 

The issue does not reproduce when I clean installed Ubuntu.

Clean installed Ubuntu 19.10, Argentina.
Locale is set properly to `es_AR`
![image](https://user-images.githubusercontent.com/34715963/67237238-2e6b0180-f44b-11e9-8bfb-cd01a9a8cc73.png)
Ads are available:
![image](https://user-images.githubusercontent.com/34715963/67237328-52c6de00-f44b-11e9-8885-a1fb46916182.png)

Clean installed Ubuntu 18.04 LTS, Argentina.
Locale is set properly to `es_AR`
![image](https://user-images.githubusercontent.com/34715963/67237385-6f631600-f44b-11e9-984a-7816ed4af346.png)
Ads are available:
![image](https://user-images.githubusercontent.com/34715963/67237943-8f470980-f44c-11e9-8a4a-e208875f74f8.png)

This issue only reproduces when locale is change to another locale which I think most user will not do.

cc @tmancey

**Comment by rebron** [comment]
@btlechowski I'm going to go ahead and close this one per your last comment.
