### ISSUE TITLE
allow users to enable Brave Rewards via 1-click during onboarding

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#6563]
## Description 
For the new onboarding flow, users should be able to enable Brave Rewards with 1-click and not kick-off to brave://rewards.

Related to https://github.com/brave/brave-browser/issues/6562

## Design
![welcome br 1](https://user-images.githubusercontent.com/2388823/69581083-e12b0400-0fa3-11ea-89f9-d23d14692a7f.jpg)
![welcome br 2](https://user-images.githubusercontent.com/2388823/69581084-e12b0400-0fa3-11ea-9a08-4c30b5868985.jpg)
![welcome br 3](https://user-images.githubusercontent.com/2388823/69581085-e1c39a80-0fa3-11ea-8978-b585ee7e0c5d.jpg)
![welcome br error](https://user-images.githubusercontent.com/2388823/69660243-e2187000-104d-11ea-8a95-ef25cc4793d0.jpg)

## Assets
preview: https://lottiefiles.com/share/6RkxWM
json file: https://assets3.lottiefiles.com/packages/lf20_6RkxWM.json
implementation info: http://airbnb.io/lottie/#/web

**Comment by karenkliu** [comment]
Designs added. ☝️

**Comment by NejcZdovc** [comment]
@karenkliu can you please add error flow as well (if wallet creation failed)

**Comment by karenkliu** [comment]
@NejcZdovc Error state added!

**Comment by rebron** [comment]
@karenkliu still a valid issue? we can reframe this existing issue for short term fix or open a new one.

**Comment by karenkliu** [comment]
@rebron We can probably reframe this as turn on Brave Ads + A/C in one button if we do the BR on by default anytime soon

**Comment by rebron** [comment]
Closing as stale.
