### ISSUE TITLE
Incognito branding is used for some English locales

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6564]
Incognito Window branding instead of Private Window is used.

## Steps to Reproduce

   1. Set locale to en_GB/en_AU/en_NZ
   2. Run Brave
   3. Open Private Window

## Actual result:

`Incognito Window` branding is used in Hamburger Menu and in Private Window
![image](https://user-images.githubusercontent.com/34715963/67199803-70238a00-f402-11e9-8c50-3ae8e2970e59.png)

## Expected result:
`Private Window` branding is used in Hamburger Menu and in Private Window

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.70.119 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @rebron

**Comment by srirambv** [comment]
Dupe of https://github.com/brave/brave-browser/issues/738#issuecomment-515979872

**Comment by btlechowski** [comment]
This is not a dupe. https://github.com/brave/brave-browser/issues/738 is Linux only based on https://github.com/brave/brave-browser/issues/738#issuecomment-515979872 and this issue reproduces on Windows

Reproduced on Windows for English(New Zealand) locale

Brave | 0.70.119 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Windows 7 Service Pack 1 (Build 7601.24530)

![image](https://user-images.githubusercontent.com/34715963/67208857-95ba8e80-f416-11e9-95e3-7b59d603fdcf.png)

**Comment by btlechowski** [comment]
Some English locales are not affected. For example `en_US` is fine:

![image](https://user-images.githubusercontent.com/34715963/67209850-67d64980-f418-11e9-8e43-602b6fa01bf2.png)

Brave | 0.70.119 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Ubuntu 18.04 LTS

**Comment by btlechowski** [comment]
Dupe of https://github.com/brave/brave-browser/issues/2147
