### ISSUE TITLE
Native notifications on Linux not working

### ISSUE THREAD

**Issue by RatanRSur** [brave/brave-browser#6569]
## Description 

I went to brave://flags and enabled native notifications but I still see the chromium styles ones.

## Steps to Reproduce

   1. Get a notification, such as a brave ad

## Actual result:

Chromium styled notification

## Expected result:
My custom styled notifications using 
https://wiki.archlinux.org/index.php/Dunst

## Reproduces how often: 

Every time

## Brave version (brave://version info)

0.69.135 Chromium: 77.0.3865.120 (Official Build) unknown (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

If I remember correctly the experimental flag worked in a previous version but not anymore. I can't remember which version that was unfortunately

**Comment by fmarier** [comment]
> 0.69.135 Chromium: 77.0.3865.120 (Official Build) unknown (64-bit)

I don't see anything about "native notifications" in `brave://flags` if I search for "notif" in 0.70, the current stable Brave version.

I have however been running Brave Ads with dunst without any problems since it launched a few months ago, without doing anything special configuration-wise. So I'm not sure what's different between your machine and mine other than the distro (Ubuntu 18.04 v. Arch).

Can you take a screenshot of the notifications you see in Brave 0.70?

Is dunst running (try `pgrep dunst`)?

**Comment by RatanRSur** [comment]
I definitely had it in one of the recent versions! But yes, it's not in the options any longer. `dunst` is running but if the option for native notifications was removed then it's not surprising it doesn't work. Could that be added back as an experimental feature?

**Comment by fmarier** [comment]
I'm not sure exactly what we would add because it's working fine for me using default options:
![Screenshot from 2019-10-31 11-20-03](https://user-images.githubusercontent.com/167821/67974913-766af080-fbd0-11e9-9c26-dc419dce08f0.png)

**Comment by bsclifton** [comment]
@RatanRSur if it's not showing in brave://flags, there may not be a straight-forward way to toggle the flag (it may have been removed with Chromium 78)

**Comment by RatanRSur** [comment]
I can't repro this in chromium :/ The native notifications work fine there.

**Comment by rebron** [comment]
cc: @jsecretan @tmancey

**Comment by tmancey** [comment]
@rebron I am investigating and will update when I found out more information. Thanks

**Comment by mcamou** [comment]
I'm seeing this same problem on `1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)`

**Comment by elcrec** [comment]
I do not experience this problem - `dunst` notifications work for all kind of websites: `slack`, `whatsapp` etc.

```
$ brave --version
Brave Browser 79.1.2.42 unknown
```

```
$ pacman -Qi brave
Targets         : brave-browser
Name            : brave-bin
Version         : 1:1.2.42-2
Description     : Web browser that blocks ads and trackers by default (binary release).
Architecture    : x86_64
URL             : https://brave.com/download
Build Date      : Di 14 Jan 2020 21:41:57 CET
```

```
$ pacman -Qi dunst
Name            : dunst
Version         : 1.4.1-1
Description     : Customizable and lightweight notification-daemon
Architecture    : x86_64
URL             : https://dunst-project.org/
Provides        : notification-daemon
Build Date      : Sa 06 Jul 2019 21:30:40 CEST
```

**Comment by mcamou** [comment]
In my case, I'm running KDE Plasma 5.17.5 on top of Ubuntu 19.10 (not Kubuntu, a normal Ubuntu with `apt install plasma-desktop`). All Chrome notifications (WhatsApp, GMail, Slack, etc) show up as Chrome notifications instead of KDE notifications.

**Comment by tmancey** [comment]
Brave Ads support Chrome notifications which do not support KDE. Closing issue as https://github.com/brave/brave-browser/issues/9592 will resolve this issue.

**Comment by jakbyte** [comment]
I'm using sway and mako on Arch Linux and this recently started happening.

**Comment by BachoSeven** [comment]
I use dunst and experienced the following Issue on Arch Linux, Brave Nightly build: without native notifications enabled, I was seeing ads notifications from dunst but was not able to click them; with the native notifications flag, I was able to see and click notifications.

**Comment by fmarier** [comment]
> I was seeing ads notifications from dunst but was not able to click them

To click on ads from dunst, I use the following (default?) key binding: `Ctrl`+`Shift`+`.`

**Comment by BachoSeven** [comment]
Yea that one was not working and still doesn't, however, Middle click also triggers the action by default, and that one is now working.
