### ISSUE TITLE
Look into if CRXElevator should be enabled

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#6570]
https://github.com/brave/brave-core/commit/189b9685e0c89980dc0786b54a4dd879f89da757#diff-27acf0a1e2667eec5672cd81934e5193R212

Currently it is not since `GOOGLE_CHROME_BUILD` is not defined.

**Comment by bsclifton** [comment]
Closing - we are now using Elevation Service after the recent VPN changes in 1.64.x for Windows
