### ISSUE TITLE
white text is being used in certain area's making it hard to read when using light theme

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6573]
## Description 

As per @petemill, looks like the 'prominent' button text colour value is being used in more locations than just the 'prominent' button.

Also reported by @Brave-Matt via Slack 👍 

## Steps to Reproduce

**`Case #1`**

   1. launch brave (`0.73.12 CR: 78.0.3904.50` in this instance)
   2. visit http://brianbondy.com and block JavaScript via Shields
   3. click on the "lock" icon via URL and notice that the JS setting is blank/using white text

**`Case #2`**

   1. launch brave (`0.73.12 CR: 78.0.3904.50` in this instance)
   2. login into https://stats.brave.com and save the password
   3. once you've saved the password, logout and reload the website
   4. click on the username to auto-fill and you'll notice that the username is using white text

** `Case #3` **
From https://github.com/brave/brave-browser/issues/6630

## Actual result:

<img width="347" alt="Screen Shot 2019-10-21 at 8 43 23 PM" src="https://user-images.githubusercontent.com/2602313/67253230-a5e96280-f444-11e9-837a-2e0eefceb10a.png">

<img width="502" alt="Screen Shot 2019-10-21 at 8 37 04 PM" src="https://user-images.githubusercontent.com/2602313/67253240-ae419d80-f444-11e9-9743-7713300629f9.png">

<img width="430" alt="Screen Shot 2019-10-21 at 8 37 10 PM" src="https://user-images.githubusercontent.com/2602313/67253246-b1d52480-f444-11e9-817d-945607e7ac36.png">

<img width="470" alt="Screen Shot 2019-10-22 at 12 14 53 PM" src="https://user-images.githubusercontent.com/2602313/67309377-c5769e80-f4c9-11e9-9122-6539c45eb71b.png">

## Expected result:

Text should be black and readable when using the light theme.

## Reproduces how often: 

100% reproducible when using the above STR.

## Brave version (brave://version info)

Brave | 0.73.12 Chromium: 78.0.3904.50 (Official Build) nightly (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | macOS Version 10.14.6 (Build 18G95)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @brave/legacy_qa @petemill @rebron @Brave-Matt

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` until new build is done. This will be available in 0.71.107 and above.

**Comment by GeetaSarvadnya** [comment]
The fix https://github.com/brave/brave-core/pull/3801 is merged in 0.73.107 hence removed QA blocked

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.71.107 Chromium: 78.0.3904.70 (Official Build) beta (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description

 - Test plan 1 - JS settings white box is removed now
![image](https://user-images.githubusercontent.com/38657976/68019168-0b4d1700-fcc1-11e9-90f0-8bffff787a01.png)
