### ISSUE TITLE
details translation missing in Rewards panel

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6577]
## Description 
On the Brave Rewards panel the translation for 'Details' is missing.

## Steps to Reproduce

   1. Clean profile on staging
   2. Enable Rewards
   3. Claim a Grant
   4. View panel

## Actual result:
<img width="399" alt="Screen Shot 2019-10-22 at 8 59 04 AM" src="https://user-images.githubusercontent.com/28145373/67288472-0a3f0d00-f4ab-11e9-9291-1e949a18044a.png">

Note - this is working as expected on brave://rewards page.

## Expected result:
Should have a translated value - it used to say 'Grants' but I think it is changing so it will say 'Details' now as it does on brave://rewards page.
<img width="1104" alt="Screen Shot 2019-10-22 at 9 19 29 AM" src="https://user-images.githubusercontent.com/28145373/67289752-1926bf00-f4ad-11e9-9492-e45ee46c7f5d.png">

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.73.17 Chromium: 78.0.3904.50 (Official Build) nightly (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no (0.70.120
- Can you reproduce this issue with the beta channel? no (0.71.101)
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @brave/legacy_qa  @mandar-brave

**Comment by NejcZdovc** [comment]
@ryanml will this be fixed with BAT points PR?

**Comment by ryanml** [comment]
@NejcZdovc it will yes, I will link the issue

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.71.108 Chromium: 78.0.3904.87 (Official Build) beta (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
`BR panel`
![image](https://user-images.githubusercontent.com/38657976/68108894-1f865380-ff0f-11e9-942a-6b5477187ccc.png)
`Brave rewards page`
![image](https://user-images.githubusercontent.com/38657976/68108938-39279b00-ff0f-11e9-975e-75af5d81b54e.png)
