### ISSUE TITLE
Create bookmarks from chrome API in 'Bookmarks bar' instead 'Other bookmarks'

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#6578]
## Description 

With https://developers.chrome.com/extensions/bookmarks#method-create bookmarks are being created in `Other bookmarks` permanent node.
Since `Other bookmarks` node is hidden and moved for all platforms sync-consistency (https://github.com/brave/brave-browser/issues/5158), bookmark should be created in `Bookmarks bar`  

Found while looking on https://github.com/brave/brave-core/pull/3749

## Steps to Reproduce

STR:
1. Launch clean profile
2. Open brave://bookmarks 
3. Open inspector 
4. Run `chrome.bookmarks.create({'title': 'TITLE', 'url': 'https://URL.com'});` in console

## Actual result:

5. See error  
```
Error in event handler: TypeError: Cannot read property 'children' of undefined
    at Object.NodeState.createBookmark (chrome://bookmarks/reducers.js:215:36)
    at Object.NodeState.updateNodes (chrome://bookmarks/reducers.js:313:26)
    at Store.reduceAction [as reducer_] (chrome://bookmarks/reducers.js:475:24)
    at Store.reduce_ (chrome://resources/js/cr/ui/store.js:141:24)
    at chrome://resources/js/cr/ui/store.js:121:9
    at Store.dispatchInternal_ (chrome://resources/js/cr/ui/store.js:129:7)
    at Store.dispatchAsync (chrome://resources/js/cr/ui/store.js:110:12)
    at Store.dispatch (chrome://resources/js/cr/ui/store.js:120:12)
    at dispatch (chrome://bookmarks/api_listener.js:71:35)
    at onBookmarkCreated (chrome://bookmarks/api_listener.js:91:5)
```
6. Reload brave://bookmarks/ page
7. See bookmark is created in `Other bookmarks` permanent folder

## Expected result:
No error, bookmark is created in `Bookmarks bar`

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.73.18 Chromium: 78.0.3904.70 (Developer Build) (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the dev channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by AlexeyBarabash** [comment]
CC @darkdh

**Comment by darkdh** [comment]
<img width="912" alt="Screen Shot 2019-10-22 at 09 59 20" src="https://user-images.githubusercontent.com/11330831/67310485-b1737280-f4b2-11e9-964e-09906d8baa56.png">
default is set to other bookmarks if we want it in bookmark bar we have to manually specify
'parentId': BOOKMARKS_BAR_ID

Or should we change the default location, @bridiver ?

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.2.5 Chromium: 78.0.3904.97 (Official Build) dev (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified STR from description
<img width="1193" alt="Screen Shot 2019-11-20 at 4 45 57 PM" src="https://user-images.githubusercontent.com/28145373/69280894-4605e900-0bb5-11ea-88bc-bbb78fb0839f.png">

* Verified test plan from https://github.com/brave/brave-core/pull/3778

1. Create with default parent
<img width="1321" alt="Screen Shot 2019-11-20 at 4 35 58 PM" src="https://user-images.githubusercontent.com/28145373/69280930-5918b900-0bb5-11ea-86f1-fbc2fb66080f.png">
   2. Create with other_node specified
<img width="1426" alt="Screen Shot 2019-11-20 at 4 37 14 PM" src="https://user-images.githubusercontent.com/28145373/69280990-78174b00-0bb5-11ea-9f62-35214874d325.png">
   3. Move
<img width="603" alt="Screen Shot 2019-11-20 at 4 38 44 PM" src="https://user-images.githubusercontent.com/28145373/69281005-7cdbff00-0bb5-11ea-8df7-2276fe3988b7.png">
<img width="1352" alt="Screen Shot 2019-11-20 at 4 42 46 PM" src="https://user-images.githubusercontent.com/28145373/69281009-7ea5c280-0bb5-11ea-931b-845f88012626.png">
