### ISSUE TITLE
Add the possibility to remove Tor

### ISSUE THREAD

**Issue by Doomfang3** [brave/brave-browser#6584]
## Description 
Hi, I didn't find an issue about this so I'm opening it.
As much as I like using Tor I think it should be possible to deactivate/remove it. The main issue is for parental control using the hosts file as it seems to completely by-pass it.

## Steps to Reproduce

   1. Change the hosts file to reroute a site (like "www.google.com") to 0.0.0.0
   2. Try to access the site via a normal
   3. Try to access the site with a private
   4. Try to access the site with a Tor window

## Actual result:

   While accessing the site via a normal window it's blocked
   While accessing the site with a private window it's blocked
   While accessing the site with a Tor window it's **not** blocked

## Expected result:

   While accessing the site via a normal window it's blocked
   While accessing the site with a private window it's blocked
   While accessing the site with a Tor window it's blocked

		**OR**

	Get the possiblity to remove/block Tor

## Reproduces how often: 

   [Easily reproduced]

## Brave version (brave://version info)

Brave | 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | Linux
JavaScript | V8 7.7.299.13
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
Command Line | /snap/brave/60/opt/brave.com/brave/brave-browser --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-features=NewExtensionUpdaterService,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AudioServiceOutOfProcess,UnifiedConsent,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI --flag-switches-begin --flag-switches-end
Executable Path | /snap/brave/60/opt/brave.com/brave/brave-browser
Profile Path | /home/doomfang/snap/brave/60/.config/BraveSoftware/Brave-Browser/Default

**Comment by daehruoydeef** [comment]
really looking forward for this feature. 
@Doomfang3 I think the Title should be phrased more like a bug: "Tor does not respect host file" since I would like the Tor mode to be enabled but would like it even more if it respects the host file.

**Comment by bsclifton** [comment]
We have some progress made towards this-
https://github.com/brave/brave-core/pull/3692 allows this to be controlled by group policy and I also believe it allows run-time disable of Tor

@Doomfang3 what would be the preferred way to see this solved? Group policy works for enterprise situations, but I'm not sure how easy that is for someone setting up a home network (and of course, it's a Windows only solution)

cc: @rebron

**Comment by Doomfang3** [comment]
I think something like @daehruoydeef is saying, that when Tor is used it's still need to respect the hosts file as for a home network it's easy to set up and only the person with root privileges could change it.

Or it could be that, if possible, Tor to be handled like an extension and create an "extensions blacklist" for users within a certain group or with root privileges that could set the extensions they don't want other users to install/remove/use/modify.

I'm not really a Linux power user so I don't know the limitations on this part but that would be the way I see it.

**Comment by stevespringett** [comment]
Ideally, a separate distribution without Tor would be available. brave/brave-core#3692 doesn't address non-Windows platforms. For example, jamf is a widely used management solution for macOS, but it doesn't appear that Brave can be managed through it. Therefore, orgs can/will automatically delete Brave upon startup solely because the inclusion of Tor violates company policy.

**Comment by rebron** [comment]
Possibly can do via referral code. cc: @tomlowenthal 
Could also add an option for Tor in extensions to toggle on/off.

**Comment by dfreilich** [comment]
@tomlowenthal #3692 didn't address non-Windows OS's, which is still an open problem. Can we reopen it?

**Comment by tomlowenthal** [comment]
As of now, Tor is not packaged with Brave — it's downloaded on first run from `tor.bravesoftware.com`. If you want Brave without Tor, you can nullroute `tor.bravesoftware.com`, and the Tor component will never be installed.

**Comment by cosmicvarion** [comment]
@tomlowenthal is there a way to remove Tor after installation as well? Thanks in advance!

**Comment by mrbluecoat** [comment]
Two years later and still no option to block Tor in non-Windows environments after Brave has been installed? I guess the solution is to block `tor.bravesoftware.com` then uninstall Brave and reinstall it.
