### ISSUE TITLE
Disclaimer popup isn't responsive when browser window is small

### ISSUE THREAD

**Issue by jhreis** [brave/brave-browser#6595]
## Description 

Using a view height of ~600px wallet info creation popup has some hidden content and the "I Understand" button is unreachable, as the content is not scrollable.

## Steps to Reproduce

   1. Visit a Dapp
   2. Receive prompt to install wallet
   3. Install wallet
   1. Receive popup (see screenshot below), where some content is not visible (page is not scrollable)

## Actual result:

Hidden content without ability to scroll:
![hidden content](https://user-images.githubusercontent.com/2781690/67447943-347af280-f5b1-11e9-8730-c81542e5cf5b.png)

## Expected result:

The ability to scroll and see all of the content.

- Also, it seems odd that this has an "X" on it to dismiss...

## Reproduces how often: 

🤷‍♀ not easy to re-try AFAIK.

## Brave version (brave://version info)

0.69.135

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes 
- Can you reproduce this issue with the beta channel? unknown
- Can you reproduce this issue with the dev channel? unknown
- Can you reproduce this issue with the nightly channel? unknown

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? unknown
- Does the issue resolve itself when disabling Brave Rewards? unknown
- Is the issue reproducible on the latest version of Chrome? no

**Comment by srirambv** [comment]
+1 from @SoaringMoon via #7825

**Comment by srirambv** [comment]
Moving to 1.10.x Beta as brave/brave-core#5624 is uplifted

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.10.74 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/83020761-94a1ad80-a046-11ea-9bfa-20d35790a50e.png)
- Logged https://github.com/brave/brave-browser/issues/9964
