### ISSUE TITLE
Rewards should not be enabled when user has chosen to hide rewards button in URL 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6596]
## Description 
Rewards should not be enabled when user has chosen to hide rewards button in URL

## Steps to reproduce 

   1. Clean install Brave from playstore
   2. Open Settings -> Appearance -> Enable `Hide rewards in URL` switch
   3. Select `Later` in the relaunch prompt
   4. Rewards button is still shown on URL bar
   5. Open rewards panel and click on `Create Wallet`
   6. Relaunch browser prompt is shown again
   7. Restart, wallet is created even though rewards button was supposed to be hidden 

## Actual result 
![androidrewards](https://user-images.githubusercontent.com/17010094/67435757-d5ba7680-f5ba-11e9-8658-53c5a9150f67.gif)

## Expected result
Should not create wallet, Should prompt to relaunch browser again and hide the button. Only allow wallet creation when user enables rewards in URL bar

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 9.0
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

https://github.com/brave/browser-android-tabs/issues/2175

**Comment by NejcZdovc** [comment]
I don't see this as a problem. User selected later, meaning that current setting is still that we should show icon.
