### ISSUE TITLE
couldn't be verified because the public key is not available

### ISSUE THREAD

**Issue by aborigines** [brave/brave-browser#6597]
## Description 

> ubuntu@ubuntu.local:~$ sudo apt update
Hit:1 http://mirror1.totbb.net/ubuntu eoan InRelease
Hit:2 http://mirror1.totbb.net/ubuntu eoan-updates InRelease                                                                                                    
Hit:3 http://mirror1.totbb.net/ubuntu eoan-backports InRelease                                                                                                                  
Hit:4 http://mirror1.totbb.net/ubuntu eoan-security InRelease                                                                                                                   
Get:5 https://brave-browser-apt-release.s3.brave.com disco InRelease [3,166 B]                                                                                                  
Hit:6 http://archive.canonical.com/ubuntu eoan InRelease                                                                                                                        
Hit:7 http://ppa.launchpad.net/libreoffice/ppa/ubuntu eoan InRelease
Err:5 https://brave-browser-apt-release.s3.brave.com disco InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A8580BDC82D3DC6C
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://brave-browser-apt-release.s3.brave.com disco InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A8580BDC82D3DC6C
W: Failed to fetch https://brave-browser-apt-release.s3.brave.com/dists/disco/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A8580BDC82D3DC6C
W: Some index files failed to download. They have been ignored, or old ones used instead.

## Steps to Reproduce

   1. sudo apt update

## Expected result:
can be update the repository

## Brave version (brave://version info)
>
Brave | 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
-- | --
Revision | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
OS | Linux
JavaScript | V8 7.7.299.13
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
Command Line | /usr/bin/brave-browser-stable --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-features=NewExtensionUpdaterService,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AudioServiceOutOfProcess,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,UnifiedConsent --flag-switches-begin --flag-switches-end
Executable Path | /opt/brave.com/brave/brave-browser
Profile Path | /x/.config/BraveSoftware/Brave-Browser/Default

**Comment by toppk** [comment]
just broke on fedora as well, package signed with same unknown key.
Signature   : RSA/SHA512, Thu 24 Oct 2019 11:22:32 AM EDT, Key ID a8580bdc82d3dc6c

**Comment by srirambv** [comment]
This is being investigated. Thanks for the report

**Comment by pitsi** [comment]
Same thing on debian testing x64. I reinstalled the brave-keyring package and I downloaded the key and installed it by hand, but the problem persists.
```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://brave-browser-apt-release.s3.brave.com bullseye InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A8580BDC82D3DC6C
W: Failed to fetch https://brave-browser-apt-release.s3.brave.com/dists/bullseye/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A8580BDC82D3DC6C
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by pizzadude** [comment]
Same here on Fedora 31.

**Comment by pitsi** [comment]
Wow, you guys are quick!
Issue just got fixed here and apt just upgraded brave to v70!

**Comment by srirambv** [comment]
This is fixed. Please try running the update again. Going to close this as fixd

**Comment by atrauzzi** [comment]
@srirambv - Just tried installing on Pop_Os now and am encountering this error.

```
W: GPG error: https://brave-browser-apt-release.s3.brave.com eoan InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A8580BDC82D3DC6C
```

**Comment by pitsi** [comment]
There was an update on brave-keyring a few hours ago...
I will look it up when I get home.

**Comment by pitsi** [comment]
So, make sure you have v1.7 of brave-keyring and the message will go away.
