### ISSUE TITLE
NTP BR widget needs to be BAT points compatible

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#6598]
For locales where BAT Points are to be needed, the NTP widget needs to support BAT Points where applicable.

cc @mattmcalister @NejcZdovc

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.1 x64` using the following build:

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.15.1 (Build 19B88)

<img width="323" alt="Screen Shot 2019-11-11 at 3 14 15 PM" src="https://user-images.githubusercontent.com/2602313/68618186-ce3e0d00-0496-11ea-8980-ab9eb8bc6326.png">

<img width="299" alt="Screen Shot 2019-11-11 at 3 22 05 PM" src="https://user-images.githubusercontent.com/2602313/68618380-2b39c300-0497-11ea-97b2-2a60900bf308.png">

<img width="318" alt="Screen Shot 2019-11-11 at 3 19 31 PM" src="https://user-images.githubusercontent.com/2602313/68618192-d138fd80-0496-11ea-87f9-0c357b63bd61.png">
