### ISSUE TITLE
Shields content should be specific to the page that the panel is opened from

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#6601]
## Description 

Currently, the Shields content changes based on which web site, opened in a separate window, you bring focus into the foreground, resulting in the mismatch of the Shields results with a wrong web page. 

## Steps to Reproduce

   1. Open multiple browser windows, each of which points to a web page
   2. Click the Lion icon in the address bar to open Shields panel
   3. While the Shields panel is open, change the focus to another browser window by clicking it.

## Actual result:

Shields panel from a window dynamically change its content for the site in focus in another window.  See attached. 
![Screen Shot 2019-10-24 at 11 07 58 AM](https://user-images.githubusercontent.com/4369856/67514102-fd5c1e00-f650-11e9-9091-0225ca3d3c3a.png)
![Screen Shot 2019-10-24 at 11 08 05 AM](https://user-images.githubusercontent.com/4369856/67514113-064cef80-f651-11e9-9125-b9ca319e39a5.png)
![Screen Shot 2019-10-24 at 11 10 37 AM](https://user-images.githubusercontent.com/4369856/67514118-08af4980-f651-11e9-8e95-5a55cdf1b6af.png)
![Screen Shot 2019-10-24 at 11 14 37 AM](https://user-images.githubusercontent.com/4369856/67514121-0c42d080-f651-11e9-803b-7a1f3a4c94be.png)

## Expected result:
Shields panel should retain the content specific to the site from which it was open, and not auto-changed to the content for the site in the foreground. 

## Reproduces how often: 

every time

## Brave version (brave://version info)

Version 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @cezaraugusto

**Comment by cezaraugusto** [comment]
Labelled `release-notes/exclude` as I think this is how the feature should work since forever. QA, please change the label if I'm wrong. Thanks!

**Comment by btlechowski** [comment]
Not reproducible on Ubuntu 18.04 as Brave shield panel is always made hidden when changing Windows. Added proper labels.

Brave | 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Ubuntu 18.04 LTS

Brave | 1.5.102 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Ubuntu 18.04 LTS

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.5.106 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
- Shields panel retains the content specific to the site and not auto-changed to the content for the site in the foreground.
![image](https://user-images.githubusercontent.com/38657976/75802351-9985f680-5da2-11ea-91cf-b8fee85e2c0f.png)
![image](https://user-images.githubusercontent.com/38657976/75802407-a60a4f00-5da2-11ea-89a8-3d28662ba686.png)
![image](https://user-images.githubusercontent.com/38657976/75802827-5bd59d80-5da3-11ea-83d5-8fa6f9df8643.png)
![image](https://user-images.githubusercontent.com/38657976/75802850-68f28c80-5da3-11ea-8161-356d0e68ecc7.png)

**Normal win and Private win**

![image](https://user-images.githubusercontent.com/38657976/75803117-e4543e00-5da3-11ea-8d25-121d4439594c.png)
