### ISSUE TITLE
Improve our copyright statement

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#6605]
Our existing license notice (in `chrome://settings/help`):
![67339412-10031580-f4e0-11e9-9f36-65939450e4fd](https://user-images.githubusercontent.com/167821/67534955-63fb2f00-f685-11e9-9147-2c75c6bcb83f.png)

neither mentions the fact that Brave is under the MPL nor links to the [license](https://mozilla.org/MPL/2.0/).

For comparison, here's how Firefox does it (in `about:license`):
![67339499-33c65b80-f4e0-11e9-91df-f04b600c9a0e](https://user-images.githubusercontent.com/167821/67534960-678eb600-f685-11e9-9ed6-15942b3124bb.png)

Ideally, we should link to the exact version tag on GitHub instead of linking just to `https://github.com/brave/brave-browser`.

Related improvements to the same page: #4990, #6152

**Comment by fmarier** [comment]
@tomlowenthal Could you please review this proposed copy:
![screenshot_from_2019-10-23_14-43-09](https://user-images.githubusercontent.com/167821/67535031-afadd880-f685-11e9-93a5-213b3183b448.png)

**Comment by tomlowenthal** [comment]
🚢 ship it.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.1006)
- Verified the copyright statemet mentioned in https://github.com/brave/brave-browser/issues/6605#issuecomment-546155129
![image](https://user-images.githubusercontent.com/38657976/68595609-ce063780-04bf-11ea-8972-160181da4fd0.png)

**Comment by GeetaSarvadnya** [comment]
@fmarier Copyright statement is slightly different, In https://github.com/brave/brave-browser/issues/6605#issuecomment-546155129  `The Brave Authors` mentioned but in 0.71.114 it's replaced by `Brave Software Inc`, which one is correct, could you please confirm?

**Comment by kjozwiak** [comment]
Assuming `Brave Software Inc` is the correct one as using `The Brave Authors` wouldn't make sense in a copyright sentence IMO. I'll let @fmarier comment though 👍

**Comment by tomlowenthal** [comment]
I don't think that Brave Software Inc. is right here. We didn't actually write the whole thing.

**Comment by kjozwiak** [comment]
@tomlowenthal can you create a follow up issue with the correct wording that needs to be used? We usually don't use the same issue and associate multiple PR/fixes to minimize confusion.

**Comment by tomlowenthal** [comment]
@kjozwiak I'm not proposing a change. I'm just suggesting that the fix should match what @fmarier wrote above.

**Comment by kjozwiak** [comment]
> @kjozwiak I'm not proposing a change. I'm just suggesting that the fix should match what @fmarier wrote above.

Thanks @tomlowenthal. Created https://github.com/brave/brave-browser/issues/6883 so we can unblock QA and address the issue in another release.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.1 x64` using the following build:

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.15.1 (Build 19B88)

* ensured that clicking on the version number opens https://brave.com/latest/
* ensured that `Mozilla Public License 2.0` opens https://www.mozilla.org/en-US/MPL/2.0/
* ensured that `open source software` opens `brave://credits/`
* ensured that `instructions on how to download and build for yourself` opens https://github.com/brave/brave-browser/wiki
* ensured that `source code used to create this copy` opens https://github.com/brave/brave-browser/releases/tag/v0.71.114 (should match the version installed)

Example:

<img width="713" alt="Screen Shot 2019-11-11 at 9 30 25 PM" src="https://user-images.githubusercontent.com/2602313/68636744-820cc000-04ca-11ea-875c-685c8ba28f80.png">
