### ISSUE TITLE
Tab hovers should be easier to turn off

### ISSUE THREAD

**Issue by Interinactive** [brave/brave-browser#6606]
## Description 
Tab hovers have suddenly appeared in the browser but offer no value. I don't know how this is beneficial. I can already see the two things being highlighted in the tooltip: https://i.imgur.com/szULq2i.png

Unless I have ~30 tabs open and cannot see the labels, this is useless, and I can't find a way to switch it off. I searched for 'tabs' and a bunch of other terms in the browser search area, but nothing relevant allows me to disable this.

## Steps to Reproduce

   1. Hover over a tab to see a tooltip appear

## Actual result:
https://i.imgur.com/szULq2i.png

## Expected result:
Nothing. I found an old article telling users how to turn this off but the setting to do so no longer exists.

## Brave version (brave://version info)
0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)

**Comment by GustavoMorais** [comment]
same here, I was even reviewing the settings trying to find an option to shut down but we can only wait for developers to make this function available

**Comment by AnthoniG** [comment]
Thank you, thank you, thank you.
This was driving me nuts.
Especially how it had suddenly appeared.
There *should* be a setting somewhere to toggle these on and off

**Comment by derekantrican** [comment]
May be related to #6609

**Comment by srirambv** [comment]
We should probably improve upon the tab hover cards by implementing #275 with tab previews.

**Comment by GustavoMorais** [comment]
@srirambv this already exists in settings

**enable these two options**
`chrome://flags/#tab-hover-cards`
`chrome://flags/#tab-hover-card-images`

![download](https://user-images.githubusercontent.com/14141025/67607142-e2290580-f759-11e9-82f2-81146f2b3857.png)

**Comment by srirambv** [comment]
@GustavoMorais that option just shows a snapshot of the page that is loaded. I am suggesting of live tab preview we had as part of muon. #275 has more details in there

**Comment by GustavoMorais** [comment]
oh yes I got it, sorry for the mistake

**Comment by NotAmaan** [comment]
I'm wondering if this feature really adds enough value to warrant an override of the native OS tooltips simultaneously making its behaviour unforgiving towards a cursor just passing by; not intending to trigger a tooltip. It is good to know that this can atleast be disabled via a flag unlike https://github.com/brave/brave-browser/issues/6358
Would love to read any discussion surrounding this, if this was really something the community here asked for, I'll definitely try using it for sometime as well.

**Comment by bsclifton** [comment]
Disabling can be done via flags `chrome://flags/#tab-hover-cards` (set to `Disabled`)

This flag was enabled by default with Chromium 78 (the regular version; there's also a B and C version?). Thanks for creating an issue! Good to see what folks think about it. We always could provide an option in our regular settings UI to configure this (so folks don't have to dig through flags)

**Comment by bsclifton** [comment]
Looks like this was disabled with the latest Chromium bump (`78.0.3904.87`); already rolled out to Release and Nightly... will be on Beta and Dev soon

**Comment by rebron** [comment]
Follow-up issues: https://github.com/brave/brave-browser/issues/9906 and https://github.com/brave/brave-browser/issues/9509
