### ISSUE TITLE
Flash is being shown as on by default even know it is not

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#661]
On a fresh download of https://github.com/brave/brave-browser/releases/tag/v0.53.0, i went to chrome://settings/content/flash and noticed flash is on by default:
![screen shot 2018-07-30 at 7 47 20 pm](https://user-images.githubusercontent.com/549654/43434724-cc25d68c-9431-11e8-84ee-1bd4ced7acea.png)

Even Chrome sets it off by default:
![screen shot 2018-07-30 at 7 51 01 pm](https://user-images.githubusercontent.com/549654/43434756-ea5b416e-9431-11e8-8493-0089b12796f9.png)

@bbondy i assume this is not intentional behavior?

**Comment by bbondy** [comment]
We're actually more restrictive than Chrome, you need to first enable it for the site, then you get to click to play. I think this is probably showing as on though because we use content-settings with different resource_ids for other shield types, and chrome only has a single content-settings for plugins for all resource ids.  

Leaving this open to fix the display of it though and to find out for sure why it's showing as on even know it is off.

**Comment by bbondy** [comment]
btw I find the changing label in Chrome's UI here very confusing to know what it means.

**Comment by darkdh** [comment]
Flash is actually disabled. The text next to the toggle means its real status, you can turn it on/off to see the text changes. For flash it has two global setting, ASK or BLOCK
That said
![image](https://user-images.githubusercontent.com/11330831/43795521-7b3c9462-9a36-11e8-9606-236c1ef7fc3d.png)
means
<img width="696" alt="screen shot 2018-08-07 at 11 31 17" src="https://user-images.githubusercontent.com/11330831/43795540-86e4c9d8-9a36-11e8-9281-33757c1c5431.png">
and another one means
<img width="688" alt="screen shot 2018-08-07 at 11 34 15" src="https://user-images.githubusercontent.com/11330831/43795560-945a3bd4-9a36-11e8-9055-27991641a6bc.png">

**Comment by bbondy** [comment]
@darkdh is right, there is confusing UI here but that's how Chrome shows Flash disabled too. 
I thought the report was right originally but I tested wrong as I had a Flash site in my allowed list. 

Closing this, @diracdeltas please let me know if you disagree with anything.

**Comment by diracdeltas** [comment]
wow super confusing. thanks for looking into it, @darkdh !
