### ISSUE TITLE
Infura interactions should be behind fastly proxy cache

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#6614]
Server side work completed by @bkero here: https://github.com/brave/devops/pull/1936
Caching should be enabled for each supported network.

**Test Plan:**
Testing this involves a general regression test of crypto wallet functionality. This includes:
* Sending/Receiving assets
* Adding ERC-20 tokens
* Connecting to and interacting with dApps
* Ensuring that balances/conversions are accurate and up to date.

**Comment by kjozwiak** [comment]
@ryanml just curious if there's a reason this is in the `Dupe / Invalid / Not actionable` milestone?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using https://github.com/brave/ethereum-remote-client/releases/tag/v0.1.18 with the following build:

Brave | 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | macOS Version 10.14.6 (Build 18G95)

* Restored a MM wallet and sent both ETH/BAT into the wallet without issues
* Restored a Crypto wallet and sent both ETH/BAT into the wallet without issues
* ensured that the conversions where correct when sending/receiving ETH/ERC-20 tokens
* Purchased meme using ETH via https://memefactory.io/ (example below)
   * https://etherscan.io/tx/0x92f36e275c503c5e695e9dba3822def42cd647b088abe39f05799b9ef570ede2
* Also went through the manual passes via https://github.com/brave/brave-browser/issues/6679 which covers a lot general functionality cases

Examples:

<img width="376" alt="Screen Shot 2019-10-30 at 11 44 27 PM" src="https://user-images.githubusercontent.com/2602313/67917704-3ffd8900-fb70-11e9-9c14-8cf6b567c5df.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Linux

* Verified using remote component `0.1.18`
* Verified ETH/BAT is sent into a restored MM wallet
* Verified ETH/BAT is sent into a restored Crypto Wallet
* Verified sending conversion for ETH/ERC-20 tokens is correct
* Verified buying via CW works on https://memefactory.io/ with [transaction](https://etherscan.io/tx/0x18a73390b1135c22aa839a01330b257f206536d4f4f0e4eebe6aed1486b50a8e)
![image](https://user-images.githubusercontent.com/17010094/67943776-30526480-fbb1-11e9-8ac6-7de3f3ba2645.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x64` using https://github.com/brave/ethereum-remote-client/releases/tag/v0.1.18 with the following build:

Brave | 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)
--- | ---
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Windows 10 OS Version 1809 (Build 17763.805)

* Restored a MM wallet and sent both ETH/BAT into the wallet without issues
* Restored a Crypto wallet and sent both ETH/BAT into the wallet without issues
* ensured that the conversions where correct when sending/receiving ETH/ERC-20 tokens
* Purchased meme using ETH via https://memefactory.io/ (example below)
   * https://etherscan.io/tx/0x4bb9700b22de9fcd76295dd90adbc65f21195d0c33174d39729d741dd2ccf4ba
* Also went through the manual passes via https://github.com/brave/brave-browser/issues/6679 which covers a lot general functionality cases

Examples:

![Annotation 2019-10-31 155534](https://user-images.githubusercontent.com/2602313/67984616-80efaf00-fbfd-11e9-99dc-96bb2566b7db.jpg)
