### ISSUE TITLE
[Windows] Crash when opening Tor window when user have multiple profiles

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#6617]
## Description 
Browser crashes when openning Tor window in Windows, if users have multiple profiles.
```
Thread 0 (crashed)
 0  chrome.dll!ProfileAttributesEntry::GetName() [profile_attributes_entry.cc : 99 + 0xe]
    rax = 0x8001a10045842db9   rdx = 0x0000009739dfbf08
    rcx = 0x000001e3836196f8   rbx = 0x0000009739dfbf90
    rsi = 0x0000009739dfbdf0   rdi = 0x000001e3836196f8
    rbp = 0x0000009739dfbef0   rsp = 0x0000009739dfbd20
     r8 = 0x9ddfea08eb382d69    r9 = 0x752e735cc2eeb0a1
    r10 = 0x19e5a845456bef3d   r11 = 0x6dda72c39c561999
    r12 = 0x0000009739dfbf40   r13 = 0x000001e3f5fa6300
    r14 = 0x0000009739dfbef0   r15 = 0x0000009739dfbf28
    rip = 0x00007fff1d0891d7
    Found by: given as instruction pointer in context
 1  chrome.dll!ProfileShortcutManagerWin::GetShortcutProperties(base::FilePath const &,base::CommandLine *,std::__1::basic_string,std::__1::allocator > *,base::FilePath *) [profile_shortcut_manager_win.cc : 792 + 0x15]
    rbp = 0x0000009739dfbef0   rsp = 0x0000009739dfbd60
    rip = 0x00007fff1d8a5d3a
    Found by: stack scanning
...
```
Sample crash: https://stats.brave.com/dashboard#crash/5db152f32718ab001f7a4cb2

## Steps to Reproduce
   1. Create a new profile to have multiple profiles
   2. Open a Tor window

## Actual result:
Browser crashes

## Expected result:
Should not crash

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
In 0.72.x and after.

**Comment by kjozwiak** [comment]
Moving this into `0.72.x - Dev` as it was uplifted via https://github.com/brave/brave-core/pull/3795.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress


Brave | 0.72.124 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified STR from the description
