### ISSUE TITLE
Be able to customize number of top sites shown on Dashboard (new tab page)

### ISSUE THREAD

**Issue by chetanpm** [brave/brave-browser#6619]
## Description 

Block space for frequently visited sites (div class="sc-bbmXgH fIpoOp"> ) if made to adapt responsively and expand to full width depending on how many sites users might want to see there. 

## Brave version (brave://version info)

Brave	0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)
Revision	edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS	macOS Version 10.14.6 (Build 18G95)
JavaScript	V8 7.8.279.17
Flash	(Disabled)
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
Command Line	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=NewExtensionUpdaterService,PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,SyncUSSBookmarks,UnifiedConsent --flag-switches-begin --flag-switches-end
Executable Path	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path	/Users/chetanpm/Library/Application Support/BraveSoftware/Brave-Browser/Default

**Comment by rebron** [comment]
cc: @cezaraugusto Can you triage this one? Not clear what the feature request is here. Looks like @chetanpm wants more top sites?

**Comment by chetanpm** [comment]
Yes more website icons like the bookmarked ones and top visited sites.

**Comment by bsclifton** [comment]
Updated the title to be more specific and linked to this from the large parent issue https://github.com/brave/brave-browser/issues/353

**Comment by johnnypoll** [comment]
More top sites will be great, also don't just use favicon as some sites don't have a favicon, then all the top site links look identical. Add title text below each box like chrome perhaps.

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/is-10-the-maximum-of-top-sites/132083/2

**Comment by aaronsantamaria** [comment]
+1 from Community:
https://community.brave.com/t/more-than-6-top-sites/138108

**Comment by aaronsantamaria** [comment]
+1 from Community:
https://community.brave.com/t/more-quick-sites-on-start-page-please/153935

**Comment by bsclifton** [comment]
cc: @karenkliu @bradleyrichter @rebron - I can't remember if the new top sites spec had ability to do two rows...

**Comment by karenkliu** [comment]
@bsclifton Yep! For user-curated mode people can have unlimited top sites tiles; it starts paging after 2 rows. For frecency mode we're still keeping it at 6.

**Comment by stefankeys** [comment]
Yeah that would be nice. I would rather not have to resort to yet another awful newtab extension.

**Comment by Goddard** [comment]
Firefox new tab topsites is one of my favorite features.

I turn off everything on the new tab and just have all my top sites on it.  I extend it to have like 20 rows by changing about:config

Would be great if I had this option in Brave.  One of the few features keeping me from switching.

**Comment by aaronsantamaria** [comment]
+1 from Community:
https://community.brave.com/t/incrementar-el-numero-de-top-sites/165058

**Comment by aaronsantamaria** [comment]
+1 from Community:
https://community.brave.com/t/increase-the-amount-of-pinnable-top-site-please/166118

**Comment by bsclifton** [comment]
The experience is a bit better now after merging https://github.com/brave/brave-core/pull/7859

For frequently visited sites (default), it still only shows 6. When switching to customize mode you can have up to 12

**Comment by wzxu** [comment]
Trying Brave for the first time today, I'm liking that it has a built-in speed dial like Safari and Firefox, but surprised to find I can't add more than 12 shortcuts, which was annoying enough I started searching for solutions, and landed here. So I guess 12 is the current limit… 

Hopefully the number of rows will be able to be customized in the future (for example 1~4 rows, that'd be 6, 12, 18, 24 icons, which should be enough for most). In the meantime, installing another speed dial extension I go…

**Comment by bsclifton** [comment]
cc: @karenkliu on above comment by @wzxu ^^

Right now, the # of tiles is limited... should we allow this to be further configurable? (ex: number of rows?)

**Comment by sheikh-azharuddin** [comment]
While this topic is for desktop...we want more top sites in android similar to Vivaldi..please add the feature 🙏

**Comment by adrianinsaval** [comment]
Any progress on this? It would be nice if the number of rows and lines could be configured

**Comment by bsclifton** [comment]
+1 from @lok1205 via https://github.com/brave/brave-browser/issues/17480
> Currently up to twelve， i need more
> and i hope mobile ,too

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/adding-more-slots-to-the-home-screen/283603

**Comment by suredream** [comment]
+1. need more, if possible want to see them in groups.

**Comment by DmitryTestOne** [comment]
Any updates on this?
2-4 additional rows would help a lot. Especially taking into account that ui is already adapted for it.

**Comment by drawingthesun** [comment]
Even if the setting is not exposed in the UI, is there a config flag we can change to add more rows to frequent/top sites? I think being able to see at least 12 sites is important as 6 just seems too low.

**Comment by DmitryTestOne** [comment]
It could be something like a slider, to scroll the item's rows, like: 12 items in 2 rows, slide right, next 2 rows, slide right, next 2, slide back and etc.
The size of the block stays the same, more icons are added.

**Comment by fallaciousreasoning** [comment]
This should be in Nightly in the next few days

**Comment by stephendonner** [comment]
## Verified `PASSED` using

Brave | 1.43.58 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 13.0 (Build 22A5311f)


### pagination appears
<details>

* confirmed adding 12th site makes pagination appear (at which point the `Add site` widget populates the 2nd "page")

<img width="1312" alt="Screenshot 2022-08-07 at 11 08 00 AM" src="https://user-images.githubusercontent.com/387249/183304942-35fefbdf-602b-48d0-92e1-1609e52798e1.png">

</details>

### pagination disappears
<details>

* confirmed pagination disappears when going from 12 -> 11 Favorites
* confirmed the `Add site` widget returns to the bottom-right position

<img width="1312" alt="Screenshot 2022-08-07 at 11 07 51 AM" src="https://user-images.githubusercontent.com/387249/183304952-50c9dcdc-b1bf-4615-b7a8-ce7aab9a3284.png">

</details>

### keyboard navigation/accessibility
<details>

* can tab to elements {site icon/placeholder}
* spacebar acts as click event

</details>

### favorites (bookmarks)
<details>

max # = 48

confirmed `Add site` widget disappears once you reach `48` bookmarks

<img width="1312" alt="Screenshot 2022-08-07 at 10 57 03 AM" src="https://user-images.githubusercontent.com/387249/183304733-74d8f8c8-7aaa-42b5-ab30-293704d11c13.png">

confirmed `Add site` widget reappears once you reach `47` (or fewer) bookmarks

<img width="1312" alt="Screenshot 2022-08-07 at 10 57 17 AM" src="https://user-images.githubusercontent.com/387249/183304834-032513e9-9109-4993-918e-38a4b6a08301.png">

</details>

### frequently visited sites
<details>

max # = 6

<img width="1312" alt="Screenshot 2022-08-07 at 10 59 46 AM" src="https://user-images.githubusercontent.com/387249/183304673-bd046b21-89be-4ff6-941e-c26e5f36ccaa.png">

</details>

### migration
<details>

`1.42.88` -> `1.43.58`
* installed `1.42.88` and populated `12` favorites
* confirmed no pagination or ability to add additional ones
* upgraded to `1.43.58`
* confirmed pagination with 2nd page including `Add site` widget


`1.42.88` | `1.43.58` | `Add site`
----------|-----------|----------
<img width="1312" alt="Screenshot 2022-08-07 at 11 35 22 AM" src="https://user-images.githubusercontent.com/387249/183306208-f82a51dc-de5c-40c9-85cc-f2089d8ebfc8.png"> | <img width="1312" alt="Screenshot 2022-08-07 at 11 37 51 AM" src="https://user-images.githubusercontent.com/387249/183306193-b50a6113-e745-4cbc-a305-4934afa0a32d.png"> | <img width="1312" alt="Screenshot 2022-08-07 at 11 48 29 AM" src="https://user-images.githubusercontent.com/387249/183306479-c2b887c1-d54d-456b-aca2-3c1feb3b0880.png">



</details>

### Brave News
<details>

* tested with and without Brave News enabled
* ensured no layout or functionality issues

</details>

**Comment by dportela** [comment]
How is this closed and marked as if it is available in the 1.43.x release, when in fact nothing has changed? There is still a limit of 12 icons per "page". Most of my dashboard is unused because of this, and having more sites there would greatly improve my efficiency. If an option has indeed been added to increase the maximum number of sites, I can't find it.

**Comment by Dzmitry-One** [comment]
> How is this closed and marked as if it is available in the 1.43.x release, when in fact nothing has changed? There is still a limit of 12 icons per "page". Most of my dashboard is unused because of this, and having more sites there would greatly improve my efficiency. If an option has indeed been added to increase the maximum number of sites, I can't find it.

Check once again, it was fixed many times ago.
Update browser and add 12 site, u should see a scroll  for the next tab, 4 tabs in total is the current maximum

**Comment by dportela** [comment]
> Check once again, it was fixed many times ago. Update browser and add 12 site, u should see a scroll for the next tab, 4 tabs in total is the current maximum

You're right that part of the requests made in the discussion above were met, but the name of the ticket is "[Add ability to customize number of top sites shown on Dashboard (new tab page)](https://github.com/brave/brave-browser/issues/6619#top)". It seems clear that while the number of top sites was changed to 12 and a few tabs added, no **_customization_** as to the number of top sites shown on Dashboard was added at all. We are still unable to display more than 12 sites on a NTP or to adjust this display in any way (set horizontal limit for rows, for instance). Most of our Dashboard is empty and we'd like to be able to reclaim that real estate with more visible sites. So we still require **_customization_**, which is what this ticket was all about.

**Comment by dportela** [comment]
> Check once again, it was fixed many times ago. Update browser and add 12 site, u should see a scroll for the next tab, 4 tabs in total is the current maximum

You're right that part of the requests made in the discussion above were met, but the name of the ticket is "[Add ability to customize number of top sites shown on Dashboard (new tab page)](https://github.com/brave/brave-browser/issues/6619#top)". It seems clear that while the number of top sites was changed to 12 and a few tabs added, no **_customization_** as to the number of top sites shown on Dashboard was added at all. We are still unable to display more than 12 sites on a NTP or to adjust this display in any way (set horizontal limit for rows, for instance). Most of our Dashboard is empty and we'd like to be able to reclaim that real estate with more visible sites. So we still require **_customization_**, which is what this ticket was all about.

**Comment by DanielTheBard** [comment]
> > Check once again, it was fixed many times ago. Update browser and add 12 site, u should see a scroll for the next tab, 4 tabs in total is the current maximum
> 
> You're right that part of the requests made in the discussion above were met, but the name of the ticket is "[Add ability to customize number of top sites shown on Dashboard (new tab page)](https://github.com/brave/brave-browser/issues/6619#top)". It seems clear that while the number of top sites was changed to 12 and a few tabs added, no **_customization_** as to the number of top sites shown on Dashboard was added at all. We are still unable to display more than 12 sites on a NTP or to adjust this display in any way (set horizontal limit for rows, for instance). Most of our Dashboard is empty and we'd like to be able to reclaim that real estate with more visible sites. So we still require **_customization_**, which is what this ticket was all about.

Agreed. Want to see more than 12 max at once. My ADHD needs immediate vision to remember sites and there's so much wasted space on the new tab that could be used for more than 12 top sites at once.

**Comment by Venkatvin** [comment]
Jira story title: Make the number of rows and columns flexible on the new tab customization page for top sites. 
Note: Do not hard code, do not make users click on a bread crump where you have copy-pasted the widget card. Do not give us pre-determined max rows and columns with 12 cells as max. If you want to hardcode, hardcode to 12x12 top sites.

**Comment by AdamK222** [comment]
Still waiting for the fix

**Comment by Goddard** [comment]
> 

No point in waiting.  It is closed.  Just use Firefox.

**Comment by fallaciousreasoning** [comment]
You could open a new issue and link it to here, so people can find it. @rebron what do you think?

**Comment by Venkatvin** [comment]
Unless the architecture cannot handle this feature, it should not be
closed, imho. I think having unlimited landing pages like the Vivaldi
browser is very helpful.

**Comment by adrianinsaval** [comment]
Brave doesn't want the starting page to be filled with icon because the ads would not be seen, it hurts their business model, it won't happen

**Comment by Venkatvin** [comment]
What part of this is ad? Brave talk? [image: image.png]
Are we talking about the same thing?

**Comment by Ferk** [comment]
Brave has an option to  use Sponsored images as background, which contributes to your Brave Rewards payout.

It makes sense for them to want to prevent too much clutter blocking the ads in the background.

If you don't want to earn coins by having a sponsored background, just use one of the many extensions that replace the dashboard... like say [Humble New Tab Page](https://chrome.google.com/webstore/detail/humble-new-tab-page/mfgdmpfihlmdekaclngibpjhdebndhdj/).

**Comment by metablaster** [comment]
Why is this closed when there is still no option to customize how many top sites are shown?

**Comment by DaisukeDaisuke** [comment]
I ran encountering this problem today with v1.78.94 (windows stable) and have created a method that is a general solution
If using some method (chrome extension) and injecting the following css into `Brave://newtab/`, you can remove the limit on the number of pin stops that can be displayed at one time

**If you don't know how to use this, don't try this workaround**

**style.css**
```css
[class^="GridPagesContainer-sc-"] {
    max-width: none !important;
    flex-wrap: wrap !important;
    flex-direction: row !important;
    justify-content: center !important;
    --grid-columns: initial !important;
}

[class^="GridPagesContainer-sc-"] > [class*="List-sc-"]  {
    display: contents !important;
}

@media screen and (min-width: 870px) {
    [class^="GridPagesContainer-sc-"] {
        display: grid !important;
        grid-template-columns: repeat(auto-fill, var(--grid-column-width, 72px)) !important;
        max-width: 900px !important;
        flex-wrap: nowrap !important;
    }
}
```
**manifest.json**
```json
{
  "manifest_version": 3,
  "name": "Brave NewTab - Unlimited Top Sites",
  "version": "1.0",
  "description": "Brave's new tab (NTPv2) now removes the limit on the number of top sites displayed and supports wrapping widgets.",
  "content_scripts": [
    {
      "matches": ["chrome://newtab/*"],
      "css": ["style.css"],
      "run_at": "document_idle"
    }
  ]
}
```
Please note that css injection with extensions to newtab requires `chrome://flags/#extensions-on-chrome-urls` to be enabled, which is a very risky choice for those using multiple extensions
**Enabling extensions-on-chrome-urls allows extensions to change browser settings, steal password managers, etc. this is very dangerous.**

This css injection allows you to display 11 pins in one column, and probably removes the vertical limit

<details>

<summary>Image</summary>

![Image](https://github.com/user-attachments/assets/bee36229-4cee-4b16-8ce5-388505ea3cfb)


</details>

**Comment by DaisukeDaisuke** [comment]
The update has increased the number of columns, why can't I specify the number of columns?

<img width="943" height="218" alt="Image" src="https://github.com/user-attachments/assets/3199558a-c133-4a9e-98a4-8868bb43b99d" />

To do that, just set display: block to top-site-tiles-mask

<img width="948" height="309" alt="Image" src="https://github.com/user-attachments/assets/953203db-2c65-4f5c-9405-2f265f37ff3b" />

```css
/** >= Brave 1.83.112 */

.top-site-tiles-mask {
    display: block !important;
}
```

**Comment by tryingoutstuff** [comment]
How do I enable this? My default changed from 2rows x 6colums to 1 row by 6 columns.

**Comment by DaisukeDaisuke** [comment]
@tryingoutstuff

If you want to extend it, do this:

<img width="2557" height="397" alt="Image" src="https://github.com/user-attachments/assets/d78f4330-2888-4d46-9c32-7152f779db0c" />

<img width="307" height="225" alt="Image" src="https://github.com/user-attachments/assets/a1507503-b4d6-461b-8923-0ea2fcdb9cb0" />

If you don't have random extensions enabled and want to extend beyond the 3rd column, follow this guide
(Side Party)
https://github.com/DaisukeDaisuke/Brave_Unlimited_TopSites?tab=readme-ov-file#brave-unlimited-top-sites
