### ISSUE TITLE
Add first class support for .eth domains (ENS)

### ISSUE THREAD

**Issue by hugecheese** [brave/brave-browser#6622]
![image](https://user-images.githubusercontent.com/56557725/67628693-55a54280-f840-11e9-9e82-c5386852fa80.png)
vs
![image](https://user-images.githubusercontent.com/56557725/67628698-6d7cc680-f840-11e9-8fb5-d6b9a97ee6d4.png)
Even with the crypto wallet enabled, Brave will always try and search `.eth` URLs. It should be recognized as a first class gTLD (the current workaround is to prefix the URL with `https://`).

Furthermore, `.eth` domains should be supported even if you don't have the Brave wallet enabled. If we are trying to decentralize the web, that would apply to all of the web, not just the parts that depend on cryptocurrency transactions.

There are plenty of valid use cases where you wouldn't to use the Brave wallet but you would still want `.eth` domains to work. There are over 300,000 registered `.eth` domains. To put that in context, there are 500,000 `.io` domains.

**Comment by abueide** [comment]
is there any plan/update for this? it would be awesome to not have to type http://x.eth every time. Willing to tip $10 in bat to whoever submits a PR for this.

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/brave_browser/comments/i3aq0k/this_would_be_awesome_have_native_support_for_in/ cc: @yrliou @ryanml

**Comment by lukemulks** [comment]
+1 this would be excellent. I will also tip $10 in bat on PR submit. :-)

**Comment by lukemulks** [comment]
I'm raising the stakes on this one. 

I'll tip **100 BAT** on PR submit. ;-)

**Comment by rebron** [comment]
Closing. Duplicate.
