### ISSUE TITLE
Github comments cannot be sent

### ISSUE THREAD

**Issue by afxgroup** [brave/brave-browser#6624]
I've noticed that i cannot send a comment on Github.
I mean i can write and send the comment but the comment is not published. And i have no error.
If i use chrome i have no problem

Brave on Windows 10 64bit

**Comment by afxgroup** [comment]
Let me test..

**Comment by afxgroup** [comment]
Well it seems it doesn't work on some projects.,. like https://github.com/sba1/adtools/issues/77

**Comment by bsclifton** [comment]
@afxgroup do you have more information about the version you're on?

For example, can you visit brave://version and copy/paste some of the version information there?

**Comment by afxgroup** [comment]
Brave | 0.69.135 Chromium: 77.0.3865.120 (Build ufficiale) (a 64 bit)
-- | --
Revisione | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
Sistema operativo | Windows 10 OS Version 1903 (Build 18362.418)
JavaScript | V8 7.7.299.13
Flash | (Disabilitata)
User-agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
Riga di comando | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --disable-chrome-google-url-tracking-client --disable-domain-reliability --disable-features=UnifiedConsent,AudioServiceOutOfProcess,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI --enable-dom-distiller --enable-features=NewExtensionUpdaterService,WebUIDarkMode,SimplifyHttpsIndicator --extension-content-verification=enforce_strict --extensions-install-verification=enforce --no-pings --enable-features=SimplifyHttpsIndicator,WebUIDarkMode,NewExtensionUpdaterService --disable-features=LookalikeUrlNavigationSuggestionsUI,AutofillServerCommunication,AudioServiceOutOfProcess,UnifiedConsent --flag-switches-begin --flag-switches-end
Percorso eseguibile | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Percorso profilo | C:\Users\andre\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default

**Comment by bsclifton** [comment]
Great- thanks for sharing @afxgroup 😄 

It may not make a difference, but are you able to upgrade to 0.70.121? (latest version) and try again?

**Comment by afxgroup** [comment]
No.. just tried to comment on the same post and same problem.. The comment is removed from textbox, the "Comment" button is again disabled due the empty text but the comment is not sent

**Comment by afxgroup** [comment]
A funny thing (maybe is the problem). With chrome and adblocker i receive the message "You can't comment at this time". Disabling it fix the problem. Could be something into brave that cause the same problem?

**Comment by afxgroup** [comment]
Yes i can confirm that disabling brave checks on that page fix the problem. So it seems the same problem is on chrome. But on chrome a message is display while on brave nothing is shown

**Comment by bsclifton** [comment]
@afxgroup maybe we can check the shield settings for GitHub.com

Here's how mine look - important ones being the cross-site cookies and cross-site device recognition. If those are too strict, you may be seeing the problem
<img width="374" alt="Screen Shot 2019-11-04 at 10 11 41 PM" src="https://user-images.githubusercontent.com/4733304/68180230-28e3e000-ff50-11e9-8b97-b02d6c0595bf.png">

**Comment by afxgroup** [comment]
Well, latest version seems to fix the problem. I'll close it for now.
