### ISSUE TITLE
Washington post crashing

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#6625]
## Description 
Visiting `https://www.washingtonpost.com/arts-entertainment/2019/10/27/snl-brings-back-alec-baldwin-take-trump-supporters/` with sheilds on, will cause the Brave to crash.

## Steps to Reproduce

   1. `https://www.washingtonpost.com/arts-entertainment/2019/10/27/snl-brings-back-alec-baldwin-take-trump-supporters/`
   2. Open and refresh a few times, click on the header and a few articles to show crash.
   3. The browser will redraw the screen, and eventually crashing it.

## Actual result:
Hard exit, a crash.

## Expected result:
Not to crash.

## Reproduces how often: 
Was seen by myself, and another user https://community.brave.com/t/washington-post/89412/2

## Brave version (brave://version info)
`Version 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No.
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
I believe the script `https://www.washingtonpost.com/notification-sw.js` is causing the issue. If you enable UBO, with sheilds on, it seems to stop the crashing. the moment you whitelist `@@||washingtonpost.com/notification-sw.js` the browser will start crashing when you browse on wpo.

**Comment by bsclifton** [comment]
Having some trouble reproducing this... @ryanbr do you need to be logged in? As a guest, I browsed a bunch of articles and now I'm getting the paywall (so hard to test further, without clearing cookies, etc)

**Comment by ryanbr** [comment]
Maybe an extension issue, just investigating.

**Comment by ryanbr** [comment]
Yeah, it was an extension issue. "Bypass Paywalls" extension was causing the crash.
