### ISSUE TITLE
Media rendering / playback borked | v0.70.121

### ISSUE THREAD

**Issue by Yoostin** [brave/brave-browser#6626]
## Description 
Immediately following upgrade to v0.70.121 video (& gifs) won't play and  cause a full screen glitch & repaint even outside the brave window. This happens on page load when there is a media element in the viewport and on any attempt to play the media. This has been apparent on twitter, tweetdeck, and Facebook. YouTube is so far unaffected (Vimeo is). Disabling Brave Shield does not remedy the issue. Autoplay is disabled on the listed sites.

## Steps to Reproduce
   1. Load a webpage containing a video element.
   2. Playing a video/media element

## Actual result:
   1. Video/media element does not display or play the media.
   2. The entire screen, even outside the browser window, glitches & repaints.
   3. CPU activity spikes for a moment.

## Expected result:
   1. The video/media element displays a posterframe or thumbnail.
   2. The video/media element plays the media when hitting play on the element.

## Reproduces how often: 
Ever time since update to v0.70.121.

## Brave version (brave://version info)

Brave | 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Windows 7 Service Pack 1 (Build 7601.24312)
JavaScript | V8 7.8.279.17
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36

## Version/Channel Information:
Only tested on the current release channel.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
System - Dell XPS15z, i7-2640M, Intel HD Graphics 3000 (integrated), DirectX 10.1

*Will switch to discrete graphics to see if reproduced - Nvidia GeForce GT 525M

**Comment by Yoostin** [comment]
# Addendum
## Miscellaneous Information:
The issue is not reproduced when running Brave pinned to the discrete GPU - Nvidia GeForce GT 525M.
I don't really want to run on the discrete GPU for web browsing is I can help it - the fan noise would drive me mental if not for the saving grace of it draining the battery in 1/4 of the usual running time.

### Thank you for all your work on Brave, by the way. Appreciate you all.

**Comment by Yoostin** [comment]
# Fixed on my system.

## Miscallaneous Information:

While tracing the fault Google Chrome decided to go and update itself and suddenly the same issue manifested itself in the latest Chrome release, Version 78.0.3904.70 (Official Build) (64-bit). Switching to the discrete GPU also resolved the issue in Chrome.

## The Probable Issue:

DirectX 10.1 in an outdated driver for Intel HD 3000 integrated graphics processor. I guess Chromium now requires DirectX 11?

## The Fix:

Managed to hunt down a new driver for Intel HD 3000 integrated graphics - Intel's driver update utility must have been asleep at the switch... "You had one job, Dagnamit!". The "new" driver had DirectX 11 and all is well with the world.

### Again, Thank You for Brave - Everyone.

#### Closing issue, cool?

**Comment by Yoostin** [comment]
# Pure Curiosity OT Question:

How come YouTube was immune to this issue that appears to have been an outdated DirectX issue. How could YouTube's video element sidestep a graphics driver snafu? Weird, right?

**Comment by bsclifton** [comment]
@Yoostin thanks for capturing the issue and also how you fixed it (new driver update). Did you download the driver from Intel's site directly? Also, how did you make the OS choose the discrete GPU? (this would be a good troubleshooting step)

@Brave-Matt Finding the latest driver is an important step which may resolve a lot of the folks having GPU issues. We may want to create a support article and include that as a starting point. The driver which Windows bundles or finds via Windows Update may have issues

**Comment by Yoostin** [comment]
@bsclifton Yes, I got the Intel driver from downloadcentre.intel.com.

To temporarily switch the GPUs Nvidia's bundled GPU settings application exposes the switch on the contextual menu of programs in the start menu. Start -> All Programs -> Brave (Right Click -> Run with graphics processor -> High performance NVIDIA processor). The switch can be affected within the Nvidia settings application to set the default GPU on a per program basis.

Thank you, All.

**Comment by bsclifton** [comment]
Great! Added notes here:
https://github.com/brave/brave-browser/wiki/GPU-issues---incident-reports
