### ISSUE TITLE
Inconsistent naming: Site Settings vs Content settings

### ISSUE THREAD

**Issue by computersaysyes** [brave/brave-browser#6627]
The `Advanced` and `On exit` tabs on the `Clear browsing data` window have respectively a `Site Settings` and `Content settings` checkbox for the same thing.
Brave 0.70.121 Windows

**Comment by bsclifton** [comment]
@computersaysyes just want to make sure I understand your concern- it's for these two tabs, right?

`Advanced` has `Site settings`
<img width="488" alt="Screen Shot 2019-10-27 at 9 37 58 PM" src="https://user-images.githubusercontent.com/4733304/67652437-1e976580-f902-11e9-86c6-7bd437413a5c.png">

`On exit` has `Content settings`
<img width="493" alt="Screen Shot 2019-10-27 at 9 37 48 PM" src="https://user-images.githubusercontent.com/4733304/67652441-22c38300-f902-11e9-8fc7-ab9c6f2a6625.png">

cc: @mkarolin

**Comment by rebron** [comment]
@mkarolin Can we double check, are we deleting everything from `site settings` that's in `content settings` is that why we have the difference in naming or is this just a labelling issue?

**Comment by mkarolin** [comment]
Looks like this is just a labeling issue. There used to be a flag that flipped between "Content Settings" and "Site Settings". The flag was removed upsteam (https://chromium.googlesource.com/chromium/src/+/a3f57021dd6ac0f0df8e473da36f874d4132819f). Because of that our code ended up defaulting to the "Content Settings" label.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.85 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Ubuntu 18.04 LTS

Verified https://github.com/brave/brave-browser/issues/6627#issuecomment-546788174

![image](https://user-images.githubusercontent.com/34715963/72039944-2c287e80-32a7-11ea-9c59-7b262f4c57c0.png)
![image](https://user-images.githubusercontent.com/34715963/72039965-3f3b4e80-32a7-11ea-8a24-ea0de41aaa2c.png)
