### ISSUE TITLE
Text in find bar is not visible in light theme mode

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#6630]
Text in find bar is not visible when text is not selected.
This only happened with light theme option.
<img width="872" alt="Screen Shot 2019-10-28 at 3 03 47 PM" src="https://user-images.githubusercontent.com/6786187/67655534-47683b00-f994-11e9-9f32-19b610d0b786.png">
<img width="553" alt="Screen Shot 2019-10-28 at 3 05 15 PM" src="https://user-images.githubusercontent.com/6786187/67655577-7383bc00-f994-11e9-8963-30c6fe758b93.png">

Reproduced on dev(0.72.x) and nightly(0.73.x).

**Comment by bsclifton** [comment]
I believe this is a dupe of https://github.com/brave/brave-browser/issues/6573

**Comment by simonhong** [comment]
@bsclifton Yes, I think so.
