### ISSUE TITLE
force closing

### ISSUE THREAD

**Issue by Th3-A6add0n** [brave/brave-browser#6632]
Browser is closing itself automatically when I opened "Limetorrent"
happened 5 times.
I'm unable to understand the reason.

**Comment by srirambv** [comment]
Please use the issue template to add details. Just saying browser is crashing doesn't give enough information. Please edit the issue and add browser details and any specific link that is causing the crash.

**Comment by bsclifton** [comment]
@Th3-A6add0n as @srirambv states, can you give us more information?

I loaded up https://www.limetorrents.info/ and it works great for me. Do you have a specific link?

What version of Brave are you using? You can visit brave://version to see and copy/paste

Also, what OS and version are you running?

**Comment by Th3-A6add0n** [comment]
> @Th3-A6add0n as @srirambv states, can you give us more information?
> 
> I loaded up https://www.limetorrents.info/ and it works great for me. Do you have a specific link?
> 
> What version of Brave are you using? You can visit brave://version to see and copy/paste
> 
> Also, what OS and version are you running?

limetorrents.asia
Eztv.ag
(Currently I only checked these 2 sites)
Brave version - 0.70.122
OS - Windows 10 (1809) x64

**Comment by Th3-A6add0n** [comment]
> > @Th3-A6add0n as @srirambv states, can you give us more information?
> > I loaded up https://www.limetorrents.info/ and it works great for me. Do you have a specific link?
> > What version of Brave are you using? You can visit brave://version to see and copy/paste
> > Also, what OS and version are you running?
> 
> limetorrents.asia
> Eztv.ag
> (Currently I only checked these 2 sites)
> Brave version - 0.70.122
> OS - Windows 10 (1809) x64

Extensions installed :
Adblock Plus
Disconnect
Duckduckgo privacy essential
Dark reader
Aha music
Emoji keyboard
Honey
Google translate
Grammarly
Fair ad blocker by Stands
Privacy Badger
Pushbullet
Web of Trust

**Comment by rebron** [comment]
@Th3-A6add0n Can you check brave://crashes and send/submit  and post here.

**Comment by Th3-A6add0n** [comment]
> @Th3-A6add0n Can you check brave://crashes and send/submit and post here.

The problem seems to be gone after v1.0

**Comment by bsclifton** [comment]
@Th3-A6add0n great, thanks for reporting back! 😄 I'll close this issue out, but please check back in here if you encounter it again and we can help troubleshoot. The crash reports are going to be what we need to see (specifically, the uploaded report ID field- not the local id)
