### ISSUE TITLE
'Relaunch' button re-toggles 'Push Messaging' feature before relaunching

### ISSUE THREAD

**Issue by LesterCovax** [brave/brave-browser#6633]
## Test plan
See https://github.com/brave/brave-core/pull/4042

## Description 

After enabling or disabling `Use Google Services for Push Messaging`, clicking the `Relaunch` button prompt toggles the setting back to its original state before relaunching the browser.  After the browser restarts, the setting is in its original state.  Running `chrome://restart` in a separate tab after toggling the setting circumvents the issue.

## Steps to Reproduce

   1. `chrome://settings/privacy`
   2. Toggle `Use Google Services for Push Messaging`
   3. Click `Relaunch`

## Actual result:

The setting is visibly toggled back to its original state when `Relaunch` is clicked, followed by the browser restarting.

**Toggling on...**

![BravePushToggle02](https://user-images.githubusercontent.com/34850610/67662333-959c2080-f939-11e9-99a3-ceab1b38c07c.gif)

**Toggling off...**

![BravePushToggle01](https://user-images.githubusercontent.com/34850610/67662416-b95f6680-f939-11e9-8839-e50132ccd78f.gif)

## Expected result:
The setting should maintain its current state when `Relaunch` is clicked.

**The Dream...**

![BravePushToggle03](https://user-images.githubusercontent.com/34850610/67663189-4fe05780-f93b-11e9-832d-868770cb6b73.gif)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

```
Brave: 0.72.110 Chromium: 78.0.3904.70 (Official Build) dev (64-bit)
Revision: edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS: Windows 10 OS Version 1903 (Build 19002.1)
```
## Version/Channel Information:

The setting is not available in release/beta channels currently and I don't have nightly installed.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

:no_mouth:

**Comment by srirambv** [comment]
Awesome GIFS. :clap:

**Comment by bsclifton** [comment]
cc: @jumde

**Comment by jumde** [comment]
Thanks for the report @LesterCovax, investigating this.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.2.41 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4042

![image](https://user-images.githubusercontent.com/34715963/71754847-4f5ac480-2e88-11ea-9fb8-3e0229a61c25.png)
