### ISSUE TITLE
P3A notification should be a dialog box to make it more prominent than notification bar

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6634]
## Description 

The current implementation of P3A notification is a notification bar that only appears on the first tab where its shown. It could be easily confused as a website notification rather than a browser notification and user may dismiss it without giving attention. 

## Steps to Reproduce

   1. Upgrade to a build that has P3A implemented (dev/nightly)
   2. Relaunch browser
   3. P3A notification is only shown on the first active tab and not on all tabs

## Actual result:

![p3a (1)](https://user-images.githubusercontent.com/17010094/67678812-e7ef3880-f95d-11e9-9fe4-52635c6deaf9.gif)

## Expected result:
Either of the two implementation
1. Should show as a prompt that clearly gets the user attention on the active tab 
![image](https://user-images.githubusercontent.com/17010094/67679489-92b42680-f95f-11e9-8b18-0fe6ff2ca0d9.png)

2. If we want to continue using the browser notification bar then it should be shown on all the tabs so that user knows that its a browser notification and not a webpage notification

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All channels that has P3A code

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

cc: @davidtemkin @bsclifton @bbondy @rebron Should probably consider this for 71.x

**Comment by bsclifton** [comment]
Closing as `wontfix`. This wasn't called out in spec when implementing

cc: @tomlowenthal and @rebron, in case you all wanted to alter the spec
