### ISSUE TITLE
All tabs crash with "Aw snap" page

### ISSUE THREAD

**Issue by threedaysmore** [brave/brave-browser#6635]
## Description 

Ever since the upgrade at the end of last week (normal release channel) any tab I try to open (even settings or About Brave) crash with the "Aw snap" page.

## Steps to Reproduce

   1. Open Browser
   2. Watch pages crash immediately
   3. 

## Reproduces how often: 

Every time I open the browser, can't use it currently

## Brave version (brave://version info)

I cannot get to brave://version since no tabs will load in the browser [v0.70.1221](https://github.com/brave/brave-browser/releases/tag/v0.70.121) is the release that started this for me though. Win 10 64 bit.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? I don't get the option to turn them off
- Does the issue resolve itself when disabling Brave Rewards? I don't get the option to turn them off
- Is the issue reproducible on the latest version of Chrome? Chrome is working fine

**Comment by threedaysmore** [comment]
Shoot, I swear I looked for a duplicate.  Must have missed it, thanks for the redirect @bsclifton

**Comment by bsclifton** [comment]
@threedaysmore you're very welcome! And no worries about a dupe- that's what I'm here to help with! 😄 

Curious: do you have Symantec installed?
