### ISSUE TITLE
New tab page top sites need to have an opaque, white background

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#6642]
## Description
Currently, the background for the top sites tiles are translucent:

<img width="1582" alt="Screen Shot 2019-10-28 at 2 56 09 PM" src="https://user-images.githubusercontent.com/2388823/67721198-33700980-f993-11e9-8156-da83abcc650f.png">

Screenshot taken from Version 0.73.26 Chromium: 78.0.3904.70 (Official Build) nightly (64-bit), but the issue is across all channels.

Top sites tiles need to be updated with opaque white backgrounds to improve contrast.

## Designs
![desktop sccreenshot dark-min](https://user-images.githubusercontent.com/2388823/67721433-bbeeaa00-f993-11e9-8034-37e020a144fd.png)

**Comment by karenkliu** [comment]
bump ☝️

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.5.102 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Ubuntu 18.04 LTS

Reproduced on 1.4.95
![image](https://user-images.githubusercontent.com/34715963/75499730-2f98d600-59cb-11ea-91e2-948f5d776a39.png)

Verified the test plan from the description
![image](https://user-images.githubusercontent.com/34715963/75499764-4b9c7780-59cb-11ea-9544-175a8a2f2361.png)
