### ISSUE TITLE
crash in "service_worker_loader_helpers::CreateHttpResponseInfoAndCheckHeaders"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6644]
## Description 

Originally reported by @jonathansampson. We're getting some reports from the community about the `service worker` crashing. Example: retrieved from `stats.brave`:

```Framework!content::service_worker_loader_helpers::CreateHttpResponseInfoAndCheckHeaders(network::ResourceResponseHead const&, blink::ServiceWorkerStatusCode*, network::URLLoaderCompletionStatus*, std::__1::basic_string, std::__1::allocator >*) [service_worker_loader_helpers.cc : 24 + 0x0]```

Crashes retrieved from `stats.brave` (there's ~20 total reports):

* https://stats.brave.com/dashboard#crash/5db78d78dc2063001fec4b92
* https://stats.brave.com/dashboard#crash/5db6c496fa54a9001f5b0d0e
* https://stats.brave.com/dashboard#crash/5db7526ffa54a9001f5dafb9

## Steps to Reproduce

* Currently don't have any STR as these crashes where mentioned via socials/the community.

## Actual result:

Brave crashing in some instances via `CreateHttpResponseInfoAndCheckHeaders`

## Expected result:

Brave shouldn't be crashing.

## Reproduces how often: 

N/A

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `not 100% sure`
- Can you reproduce this issue with the dev channel? `not 100% sure`
- Can you reproduce this issue with the nightly channel? `not 100% sure`

## Miscellaneous Information:

CCing @rebron @bsclifton @jonathansampson @brave/legacy_qa

**Comment by kjozwiak** [comment]
@jonathansampson please addd any other information you might have from users reporting on the various socials (specifically Twitter).

**Comment by bsclifton** [comment]
Crash IDs I'm seeing here:
## 0.70.122
- 23e3f2bed8467d9c

(will continue to update this comment as more are found)

**Comment by bsclifton** [comment]
Not seeing this on version 1.0.0 or newer 🎉 Let's re-open if any occurrences show up

**Comment by kjozwiak** [comment]
> Not seeing this on version 1.0.0 or newer 🎉 Let's re-open if any occurrences show up

Quickly went through the latest crashes and it looks like they're coming from `0.70.123`, `0.70.122` or `0.70.121`. Pretty sure this has been fixed or we would have seen this appear in newer builds. There's only ~25 crashes so the volume doesn't seem to be high.
