### ISSUE TITLE
AspNetCore Identity Cookie is Ignored

### ISSUE THREAD

**Issue by buehler** [brave/brave-browser#6645]
## Description 
When using AspNetCore with IdentityCookies, the default name of the cookie is `.AspNetCore.Identity.Application`. As stated in the issue here: https://github.com/aspnet/AspNetCore/issues/16626 when using this default name, the cookie does not get set. With other browsers (see in the referenced issue), this works like a charm.

Brave does ignore the cookie even with shields down and extensions disabled.

## Steps to Reproduce

   1. Create a dotnet webapp with individual authentication (as stated in the aspnetcore issue)
   2. Run it
   3. Try to login

## Actual result:

The identity cookie is returned by the server but ignored by brave.

## Expected result:
The identity cookie is set as "required" for the application. So this cookie mustn't be ignored.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

```
Brave | 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Windows 10 OS Version 1903 (Build 18362.10024)
JavaScript | V8 7.8.279.17
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=NewExtensionUpdaterService,PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,SyncUSSBookmarks,LookalikeUrlNavigationSuggestionsUI,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,UnifiedConsent --flag-switches-begin --flag-switches-end -- http://localhost:3000/
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? not tried
- Can you reproduce this issue with the dev channel? not tried
- Can you reproduce this issue with the nightly channel? not tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? not tried
- Is the issue reproducible on the latest version of Chrome?  no, it works with chrome

**Comment by buehler** [comment]
Nobody? :-|

**Comment by rebron** [comment]
cc: @fmarier Can you take a look at this one?

**Comment by fmarier** [comment]
@buehler Sorry for the delay in getting back to you.

Looking at the screenshots you provided, I noticed that the first cookie is `samesite=lax`:
![Default cookie name](https://user-images.githubusercontent.com/1067213/67746050-fa34a980-fa25-11e9-943d-e61b77a47679.png)

whereas the second one isn't:
![Renamed cookie](https://user-images.githubusercontent.com/1067213/67747359-d161e380-fa28-11e9-8393-39390c61e948.png)

and so I wonder whether it's only an issue with same-site cookies.

Is there a test site you can point me to where I could see the problem? I don't have the required software to put up a dotnet webapp.

**Comment by buehler** [comment]
Hey @fmarier 

I did try it with lax, strict and none (all the possible values of samesite as I'm aware of).

Hmm. good question, I'll have a look. Maybe I can just deploy a sample app for you. Let me check.

Regards

**Comment by buehler** [comment]
Alright, I'm trying to deploy two apps to now (zeit.co) where you can see what happens. One will use the default cookie name, and the other will use a custom cookie name.

**Comment by buehler** [comment]
Ok "now" deprecated docker deployments :-/
Funny enough, I tested the issue locally and it seems to be fixed 🤔 

I deployed an application just now and the issue is gone as well (with https & samesite-lax)

Therefore closing this issue for now.

Thanks for investigating though!
Cheers

**Comment by fmarier** [comment]
Thanks @buehler , glad to know it's working!
