### ISSUE TITLE
`New window` in private window with tor no longer opens new window with tor

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6646]
`New window` in private window with tor used to open a new window with tor. This is no longer the case.

## Steps to Reproduce

   1. Clean install
   2. Open a private window with tor
   3. In `private window with tor` click `New window` from Hamburger menu

## Actual result:

Normal new window is opened
![image](https://user-images.githubusercontent.com/34715963/67778414-726d9000-fa63-11e9-8343-87b14d3b42e1.png)

Important: if https://github.com/brave/brave-browser/issues/6467 is fixed as intended in https://github.com/brave/brave-browser/issues/6467#issuecomment-547144297, there will be no way of opening a new private window with tor from private window with tor.

## Expected result:
New private window with tor is opened 
![image](https://user-images.githubusercontent.com/34715963/67778444-7c8f8e80-fa63-11e9-9aa1-87477306ada2.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.72.110 Chromium: 78.0.3904.70 (Official Build) dev (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel?

cc @brave/legacy_qa @bsclifton @rebron @yrliou @tomlowenthal

**Comment by yrliou** [comment]
From slack discussion, our goal is to have the ability to open any type of new windows(regular/private/private with Tor) in Tor window. So I'll fix this issue by showing `New Window`, `New Private Window`, and `New Private Window with Tor` in the hamburger menu and opening the corresponding type of window for each option.

**Comment by yrliou** [comment]
See brave/brave-core#3813 (comment) for the test plan.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.72.124 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3813

regular window
![image](https://user-images.githubusercontent.com/34715963/68859989-d68d8680-06e8-11ea-8bf8-bc39ed85644a.png)

private window
![image](https://user-images.githubusercontent.com/34715963/68860111-1eaca900-06e9-11ea-8f9d-b44acd7d3f53.png)

private window with Tor
![image](https://user-images.githubusercontent.com/34715963/68860129-28361100-06e9-11ea-8769-4fa184e4aac9.png)
