### ISSUE TITLE
BAT Points follow-up to #6480 - Changes for Japan

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#6654]
Two changes that need to make it for the BAT Points fix;

a) All areas where we have text Tokens, needs to replaced with Points (search and replace)
b) Any BAT designation (tipping panel., etc.) needs to be replaced with BAP (Basic Attention Points)

see image below for b) ----
![image](https://user-images.githubusercontent.com/35932307/67807006-32051680-fa51-11e9-92fb-dc1385812218.png)

As example the Tip values in the panel would say 1.0 BAP, 5.0 BAP, and 10.0 BAP respectively

cc @jsecretan @NejcZdovc

**Comment by mattmcalister** [comment]
See spec doc for more details

**Comment by kjozwiak** [comment]
Running through https://github.com/brave/brave-core/pull/3751 before approving the PR into `0.72.x` and `0.71.x` and noticed the following using BAT as @mandar-brave mentioned above. Adding examples so it's easier to QA once this lands in Nightly and is ready for QA:

**`Tipping banner`**:

<img width="1237" alt="Screen Shot 2019-10-30 at 2 48 29 PM" src="https://user-images.githubusercontent.com/2602313/67889710-b628ce00-fb25-11e9-9b9b-cecb3640c678.png">

**`Confirmation banner once tip goes through`**:

<img width="635" alt="Screen Shot 2019-10-30 at 2 48 59 PM" src="https://user-images.githubusercontent.com/2602313/67889913-1a4b9200-fb26-11e9-887a-a3595f0034ff.png">

**`Monthly tipping banner`**:

<img width="1196" alt="Screen Shot 2019-10-30 at 3 27 40 PM" src="https://user-images.githubusercontent.com/2602313/67892018-36513280-fb2a-11e9-9560-5b582877f07f.png">

**`Confirmation banner once monthly tip has been set`**:

<img width="596" alt="Screen Shot 2019-10-30 at 3 28 27 PM" src="https://user-images.githubusercontent.com/2602313/67892103-600a5980-fb2a-11e9-8e29-9f55dd48c45d.png">

**`Ads panel`**:

<img width="663" alt="Screen Shot 2019-10-30 at 3 06 38 PM" src="https://user-images.githubusercontent.com/2602313/67890522-3c91df80-fb27-11e9-83df-b5c62e4917cc.png">

**`Auto-contribution panel`**:

<img width="738" alt="Screen Shot 2019-10-30 at 3 06 03 PM" src="https://user-images.githubusercontent.com/2602313/67890628-71059b80-fb27-11e9-906d-876251e89427.png">

**`Tipping panel`**:

<img width="687" alt="Screen Shot 2019-10-30 at 3 03 10 PM" src="https://user-images.githubusercontent.com/2602313/67891090-423bf500-fb28-11e9-9293-983b4c707390.png">

**`Monthly contribution tipping panel`**:

<img width="465" alt="Screen Shot 2019-10-30 at 3 28 17 PM" src="https://user-images.githubusercontent.com/2602313/67892240-ad86c680-fb2a-11e9-848b-992b97ac66a8.png">

**`Balance Summary under brave://rewards`**:

<img width="428" alt="Screen Shot 2019-10-30 at 3 24 32 PM" src="https://user-images.githubusercontent.com/2602313/67892354-ef177180-fb2a-11e9-8c54-0dbe2a0096f7.png">

**`Join Rewards panel`**:

<img width="439" alt="Screen Shot 2019-10-30 at 3 17 49 PM" src="https://user-images.githubusercontent.com/2602313/67892423-14a47b00-fb2b-11e9-8eca-a4c7208badf5.png">

**Comment by GeetaSarvadnya** [comment]
All the issues mentioned in the https://github.com/brave/brave-browser/issues/6654#issuecomment-548078955 are reproduced in windows 10 x64 -`0.71.111`

**Comment by bsclifton** [comment]
Fixed in 0.71.x with https://github.com/brave/brave-core/pull/3884

**Comment by GeetaSarvadnya** [comment]
Verification is in-Progress


Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/3884

`Tipping Banner`
![image](https://user-images.githubusercontent.com/38657976/68601498-715c4a00-04ca-11ea-9622-2e368f12cd00.png)

`No enough funds in tipping banner`
![image](https://user-images.githubusercontent.com/38657976/68601592-a2d51580-04ca-11ea-9b8a-18490ad92e09.png)

`Confirmation banner once tip goes through`
![image](https://user-images.githubusercontent.com/38657976/68601766-019a8f00-04cb-11ea-8883-70c7d4c08d7c.png)

`Confirmation banner once the monthly tip has been set`
![image](https://user-images.githubusercontent.com/38657976/68601832-2a228900-04cb-11ea-9894-d86220dacb6d.png)

`Ads panel`
![image](https://user-images.githubusercontent.com/38657976/68601918-55a57380-04cb-11ea-87d8-e87482bd4683.png)

`Auto-contribution panel`
![image](https://user-images.githubusercontent.com/38657976/68601998-84bbe500-04cb-11ea-98b6-815c7a1a046a.png)

`Tipping panel under brave://rewards`
![image](https://user-images.githubusercontent.com/38657976/68602084-af0da280-04cb-11ea-9506-ae4e761ee065.png)

`Monthly contribution tipping panel`
![image](https://user-images.githubusercontent.com/38657976/68602141-d3697f00-04cb-11ea-8c99-67d2289480f2.png)

`Join Rewards panel`
![image](https://user-images.githubusercontent.com/38657976/68602308-1cb9ce80-04cc-11ea-883d-9c701fd555fa.png)

`Pending Contributions`
