### ISSUE TITLE
Nav / Layout misaligned

### ISSUE THREAD

**Issue by Sondro** [brave/brave-browser#6656]
## Description 

<= LEFT: BRAVE Version 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)
=> RIGHT: BRAVE Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)

((The latest mobile version also has the same misalignment.))

<img src ="https://u.cubeupload.com/Sondro/bravelayout00.jpg" />

Firefox, and Safari, and old Chrome don't have this layout issue on desktop or mobile.

NOTE: updated Chrome portable and replicated the same issue, so I'm closing this.

## Steps to Reproduce

   1. Go to https://christophercoggins.com
   2. Resize browser to smallest width or use Brave mobile version.
   3. Look at top nav.

**Comment by Sondro** [comment]
Updated Chrome portable and replicated the same issue, so I'm closing this.

**Comment by Sondro** [comment]
Just letting everyone know I worked through this with the Chrome devs and this was layout regression bug was patched and I assumed rolled into Brave as well: https://bugs.chromium.org/p/chromium/issues/detail?id=1025715

**Comment by bsclifton** [comment]
Thanks for the update, @Sondro 😄 And thanks for working to get it resolved, very much appreciated ❤️
