### ISSUE TITLE
aliyun sms send error:  can't click

### ISSUE THREAD

**Issue by samcaicn** [brave/brave-browser#6658]
can't clidk
![image](https://user-images.githubusercontent.com/3318094/67828371-20357900-fb0e-11e9-92dc-b7c510b75884.png)

**Comment by samcaicn** [comment]
chrome is ok

**Comment by samcaicn** [comment]
![image](https://user-images.githubusercontent.com/3318094/67828696-56272d00-fb0f-11e9-82b7-fbf852f74a47.png)

**Comment by samcaicn** [comment]
![image](https://user-images.githubusercontent.com/3318094/67918880-2ba1a680-fbd9-11e9-9fba-a07d22570fb2.png)

**Comment by bsclifton** [comment]
This may be happening because we explicitly disabled SMS receiver:
https://github.com/brave/brave-core/blob/b205cf828b965126e2fdb7c2ad4f3a36197abd69/app/brave_main_delegate.cc#L175

cc: @snyderp @jumde

**Comment by bsclifton** [comment]
@jumde @snyderp is there a way to enable SMS receiver on a per-site basis? (ex: is it a site setting?). I didn't see it under content settings. I'm thinking there isn't

**Comment by snyderp** [comment]
@bsclifton I dont think we should enable this.  Its not standardized (or even implemented outside origin trials in Chrome).  Its also less privacy respecting that Apple's similar proposal (which doesn't deliver full SMS text to the website, or even notify the website of SMS communication at all).

So, its possible, but my two cents is its a bad road to go down.  My vote is to not enable the feature at all, and push against its standardization.

**Comment by bsclifton** [comment]
@snyderp I agree 😄 Am I correct in thinking this is an overall feature (ex: it's tied to a feature flag) and not a content setting? I didn't see anything in chrome://flags for SMS receiver, so I had forgotten if there is a way users can toggle

Unless there is a painful way to enable (we don't want it on by default by above reasoning), I think we'll want to close this feature as a `wontfix`.  I'll go ahead and close and if there is a work-around, we can describe here

**Comment by snyderp** [comment]
@bsclifton i might be a dummy here, us `content setting` the same thing as origin trial?  If so, then my understanding of the API is that its currently behind origin trial, and so google turns it on for some users, for some origins.  If content setting ~= origin trial, then we might be 100% on the same page :)

Re: https://www.chromestatus.com/feature/5873577578463232

**Comment by snyderp** [comment]
The only change we might want to make here though is to see if there is some UA modification, or Web API modification we need to make, to have sites that expect to be treated special in Chrome b/c of google - site agreements not take these code paths (so that they don't break in brave)

**Comment by bsclifton** [comment]
Good question - I'm not sure if origin trials get stored as content settings. I don't believe so; they should be separate. The content settings (I think now called `Site settings`) I was thinking of are just the ones which show when you go to the lock in the omnibox and pick `Site settings`. I'm not sure if there are other permissions being hidden (of course, we have custom ones too, like our shields)

We have field trials disabled (which also covers origin trials), so we're covered there 👍
