### ISSUE TITLE
Profile corrupted, "some features may not work"

### ISSUE THREAD

**Issue by Mitsunee** [brave/brave-browser#6659]
## Description 
My extension settings were purged and I can't seem to get any of my bookmarks have their favicon anymore, even for my own website.

## Steps to Reproduce
No clue what I did to be honest. I restarted brave due to a graphical glitch (might be nvidia driver related, no clue, every application can have it happen), then had a tab from the extension Tampermonkey pop up. I didn't check my bookmarks then as I just wanted to watch something and sleep and noticed the little message box saying something like that my profile was corrupted and some features may not work.

EDIT: I also just noticed the extension Better TweetDeck has become completely unuseable as it can't seem to save any setting anymore since all extension settings were purged.

## Actual result:
None of my bookmarks have favicons, my extension settings were gone, probably more stuff.

## Expected result:
Everything working as normal? :\

## Reproduces how often: 
Can't tell as I don't know what happened

## Brave version (brave://version info)
```
Brave	0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)
Revision	edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS	Linux
JavaScript	V8 7.8.279.17
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
Command Line	/opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=NewExtensionUpdaterService,PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,UnifiedConsent,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,LookalikeUrlNavigationSuggestionsUI,SyncUSSBookmarks --flag-switches-begin --flag-switches-end
Executable Path	/opt/brave.com/brave/brave
Profile Path	/home/mitsunee/.config/BraveSoftware/Brave-Browser/Default
```

## Version/Channel Information:
Can't know.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
    - No it seems entirely unrelated to shields.
- Does the issue resolve itself when disabling Brave Rewards?
    - Also nope, it's not a recurring issue, so...uhh
- Is the issue reproducible on the latest version of Chrome? 
    - I'd rather not give Chrome my profile even if it's possibly corrupted.

## Miscellaneous Information:
Not really information, but I'd really really really like to know a good way to back up my bookmarks as a file, not through Brave Sync.

**Comment by Mitsunee** [comment]
Managed to get a hold of the messagebox again:
![image](https://user-images.githubusercontent.com/19474909/67852507-d26c4100-fb0c-11e9-9047-e33da270070e.png)
This appears on startup along with all of my extension settings (and userscripts) being gone.

**Comment by bsclifton** [comment]
@Mitsunee sorry for the super long turn-around time here; for future reference, you might try our support forums: https://community.brave.com/c/support-and-troubleshooting

Definitely sucks losing settings- without more information about what caused the problem, it's almost impossible to troubleshoot

However, I can share: this is what I do to backup my profile (has helped me many times with FF/Chrome/Brave over the years)

I'll create a shortcut to `%USERPROFILE%\AppData\Local\BraveSoftware\Brave-Browser\User Data\` and then periodically zip this up. You can also setup a scheduled task to do that once a week too (which is great for restoring back to a certain date)
