### ISSUE TITLE
Change first ad to appear after 2 minutes for iOS/Android

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#6661]
See iOS/Android tickets for steps to reproduce and testing as this does not affect the desktop. It would be worth just making sure ads are delivered as expected on the desktop to make sure nothing regressed.

https://github.com/brave/browser-android-tabs/issues/2213
https://github.com/brave/brave-ios/issues/1825

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.2.7 Chromium: 78.0.3904.108 (Official Build) dev (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | macOS Version 10.13.6 (Build 17G5019)

* Performed basic regression test of Ads per description
* Confirmed ads were delivered as expected per the max number of ads per hour setting
* Confirmed `view`, `click`, `landed`, `dismiss` in `confirmations.json`
* Confirmed able to redeem tokens on the server
