### ISSUE TITLE
inline 'Tip' text does not change style on hover on old.reddit.com - follow up

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6662]
Follow up to https://github.com/brave/brave-browser/issues/5702.
Tipping is supported on `www.reddit.com` and `old.reddit.com`. https://github.com/brave/brave-browser/issues/5702 has been fixed for `www.reddit.com`, but not for `old.reddit.com`

## Steps to Reproduce

   1. Enable rewards
   2. Open `https://old.reddit.com/r/BasicAttentionToken/`
   3. Hover over `Tip`

## Actual result:

Tip text does not change style
![image](https://user-images.githubusercontent.com/34715963/67851994-e95e6380-fb0b-11e9-995c-646d3a28c4a6.png)

## Expected result:
Tip text changes style
![image](https://user-images.githubusercontent.com/34715963/67851959-da77b100-fb0b-11e9-8f38-f8346853f202.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.72.110 Chromium: 78.0.3904.70 (Official Build) dev (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @masparrow @NejcZdovc

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows 10 x64 - 1.1.1 beta version
