### ISSUE TITLE
BAT icon in URL bar is misplaced when not rewards user and screen is 100% scaling

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6663]
This is a recent regression

## Steps to Reproduce

   0. Set display to 100% scaling (and quit Brave)
   1. Clean install
   2. Run Brave

## Actual result:

BAT icon in URL bar is misplaced 
![image](https://user-images.githubusercontent.com/34715963/67853159-38a59380-fb0e-11e9-9da1-92b23be3ebef.png)
![image](https://user-images.githubusercontent.com/34715963/67853002-d2207580-fb0d-11e9-83ac-e9b97bb4aa94.png)

Note: issue is not fixed after restarting the browser
## Expected result:
BAT icon is not misplaced 
![image](https://user-images.githubusercontent.com/34715963/67853409-c97c6f00-fb0e-11e9-8b08-6053f935369a.png)

![image](https://user-images.githubusercontent.com/34715963/67853362-b23d8180-fb0e-11e9-8082-cb8982bc4ed7.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

**Reproducible in**

Brave | 0.71.105 Chromium: 78.0.3904.70 (Official Build) beta (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

Brave | 0.72.112 Chromium: 78.0.3904.70 (Official Build) dev (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

**Not reproducible in** 

Brave | 0.72.111 Chromium: 78.0.3904.70 (Official Build) dev (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

cc @NejcZdovc 
cc @brave/legacy_qa to check on other platforms

**Comment by btlechowski** [comment]
Reproduces on Beta on Ubuntu

Brave | 0.71.105 Chromium: 78.0.3904.70 (Official Build) beta (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/67880707-7078ff00-fb3f-11e9-9a46-13b440419871.png)

**Comment by petemill** [comment]
Likely introduced with https://github.com/brave/brave-core/pull/3698

**Comment by petemill** [comment]
hmm, I'm so far _not_ able to reproduce on ubuntu (or any platform)

![image](https://user-images.githubusercontent.com/741836/67885669-3ab72480-fb05-11e9-86bd-5092fe7085a1.png)

**Comment by petemill** [comment]
I **can** reproduce this now. Happens only when scaling is 100%, but does happen on all platforms. This is macOS:

![image](https://user-images.githubusercontent.com/741836/67886544-dac17d80-fb06-11e9-8a5f-3f8a890c236c.png)

Modifying title appropriately.

**Comment by LaurenWags** [comment]
`QA/Blocked` until 0.71.108 or above.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.71.111 Chromium: 78.0.3904.87 (Official Build) (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Ubuntu 18.04 LTS

Verified STR from the description.

![image](https://user-images.githubusercontent.com/34715963/68128533-32e9ec80-ff18-11e9-8026-23fa57c7c856.png)
