### ISSUE TITLE
Fix ads locale_helper crash on Windows/Linux/Android

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#6666]
## Description 

Ads locale_helper crashes on Windows/Linux/Android

## Steps to Reproduce

   1. Launch browser

## Actual result:

Browser crashes

## Expected result:
Browser should not crash

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by btlechowski** [comment]
Verified passed with

Brave | 1.2.11 Chromium: 78.0.3904.108 (Official Build) dev (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

Verified test plan from the description and https://github.com/brave/brave-core/pull/3825. No crash
