### ISSUE TITLE
Brave Nightly does not start

### ISSUE THREAD

**Issue by Geradot** [brave/brave-browser#6668]
I try to start Brave Nightly. Two processes appear in Task manager, but not more than 26 MB. The normal version of Brave runs without problems.

The problem arose for no reason. Rebooting the PC did not help. Today the browser still worked.

I use Windows 10.

**Comment by bsclifton** [comment]
Hey there folks! Sorry that this happened- this was a mistake on our part. We have a new (working) version of Nightly being built right now

Because it crashes on launch, you'll have to download a new version from https://brave.com/download-nightly when it's ready (stay tuned!)

**Comment by bsclifton** [comment]
OK folks - issue resolved 😄 Sorry to those impacted; unfortunately, you'll have to download/install again. It's safe to install over the existing install (nothing will get lost; your profile data is stored in a separate location)

cc: @Blahx @Geradot

**Comment by Geradot** [comment]
> OK folks - issue resolved  Sorry to those impacted; unfortunately, you'll have to download/install again. It's safe to install over the existing install (nothing will get lost; your profile data is stored in a separate location)
> 
> cc: @Blahx @Geradot

Now it's not working after reinstall the new package...

**Comment by Geradot** [comment]
It works, thanks!

**Comment by bsclifton** [comment]
For posterity, this crash was caused by https://github.com/brave/brave-core/pull/3770

Bug we had captured (ex: root cause of the crash): https://github.com/brave/brave-browser/issues/6666

And was then fixed with:
- https://github.com/brave/brave-core/pull/3825
- https://github.com/brave/brave-core/pull/3827
