### ISSUE TITLE
Notification issue (BR) for backup and restore

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#6670]
Issue#1
The backup and restore notification, when OK'd or closed never removes the BAT logo notification and needs to clear the notification immediately.

This issue is consistent across (0.70, release, 0.71 beta, 0.72 dev) and can be reproduced 100% after a backup and restore. 

The issue itself is not a big deal but it causes users to completely ignore the logo notification when important notifications like ads earning show up.

Notification for BAT logo clears only when Rewards Settings are clicked; it should clear when notification is acknowledged or closed out from panel.

Issue#2: Backup and Restore ideally should stop showing for user wallets.

cc @NejcZdovc @LaurenWags

**Comment by mandar-brave** [comment]
@LaurenWags really no particular steps;
all 3 builds have been used and upgraded over the past few months
All 3 got the backup and restore notification
Clicked the BAT logo
Opened Panel, acknowledged the notification
Closed Panel and BAT logo notification would not clear

**Comment by NejcZdovc** [comment]
closing as stale
