### ISSUE TITLE
Cross site tracker blocked - Filename heatmap.js

### ISSUE THREAD

**Issue by parmindersk** [brave/brave-browser#6673]
## Description 
We run an internal web application that loads a lot of JS files including a file named heatmap.js. When the page loads, brave browser complains that Cross-Site tracker blocked and marks this file. Everything else loads fine. 

1. We tried emptying out the file and loading the page - same issue - Brave complains again
2. We renamed the file to hm.js and left the original contents in there - No issue - Brave is fine

## Steps to Reproduce

   1. Create an HTML file with these contents: <script src="heatmap.js"></script><h1>Hello</h1>
   2. Create an empty file heatmap.js or put any valid JS code in there.
   3. Run an HTTP server from where you can serve these files
   4. When you open the html file from the browser you'll see the file being marked with cross-site tracker blocked

## Actual result:

![image](https://user-images.githubusercontent.com/1111139/67885250-9ee5e280-fb1d-11e9-8d6e-a4668aa8dbe9.png)

file bein
## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @ryanbr Can you take a look?

**Comment by ryanbr** [comment]
@parmindersk the easier way to fix this, would be to rename the "heatmap.js". 

Just some background on why its blocked:
`"heatmap" tracking, is a term where a site monitors mouse movement and clicks creating a heatmap of the users history on a webpage. Which is why its blocked.`

**Comment by parmindersk** [comment]
You have to understand that heatmap is a common term used with graphing
libraries. We download these dependencies with NPM as I mentioned earlier
and having to rename them just adds another step for us.

We'll figure a way. However, being a programmer, putting in a rule based on
a file name doesn't sound like the best option.

**Comment by ryanbr** [comment]
I understand it's not ideal. I can issue a whitelist the specific script (when its public/testable site, rather than internal). heatmap tracking is so heavily used, which is why we had to be heavy handed. 

We have 6 heatmap whitelists in Easyprivacy, we can add yours if need be. Just need a publicly testable site

**Comment by ryanbr** [comment]
Somewhat resolved. If heatmap isn't used for tracking @parmindersk renaming the filename will fix it. Or I can whitelist if the site is public.
