### ISSUE TITLE
FollowUp: NTP responsive design

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#6677]
Look should resemble this on widths of < 1150px. Some adjustments may need to be made to respect the grid layout used on the new tab page so the widget can cleanly break down like so:

<img width="498" alt="Screen Shot 2019-10-30 at 5 02 09 PM" src="https://user-images.githubusercontent.com/8732757/67908019-183dff00-fb37-11e9-8be7-934225affdeb.png">

**Comment by rebron** [comment]
@NejcZdovc Is this a pr associated with this issue already? Has this been fixed? Can you remove the milestone if work isn't completed yet?

**Comment by NejcZdovc** [comment]
closing as this is not valid anymore. We re-did widgets for NTP, so now we don't have only one
