### ISSUE TITLE
Move Shields extension button to URL bar

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#668]
## Description 
Move from `BrowserActions` area to `PageActions` area.
Clicking should still invoke the extension popup.
Button should have the following states:
- Shields on (with notification count)
- Shields off
- Non-shield compatible page

![image](https://user-images.githubusercontent.com/741836/44356267-ac0c3980-a463-11e8-805a-aef6b32b0818.png)

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux
--|![image](https://user-images.githubusercontent.com/17010094/46030394-041e0780-c0c4-11e8-9951-92b3798cf5a4.png)
