### ISSUE TITLE
Alignment issue for `Token grants claimed` in BR panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#6684]
## Description 

Alignment issue for `Token grants claimed` in BR panel

## Steps to Reproduce

   1. Launch nightly build 0.73.42 / 0.73.44 with staging flags
   2. Enable rewards and claim grants 
   3. Add few verified sites to a-c table
   4. Send one-time tip and monthly tip to a verified pubs
   5. Wait for auto contribution to complete
    

## Actual result:

Alignment issue for `Token grants claimed` in BR panel

After claiming grants:

![image](https://user-images.githubusercontent.com/38657976/67934076-1df61c00-fbed-11e9-84d3-3698b2f5ca38.png)

After auto contribution:

![image](https://user-images.githubusercontent.com/38657976/67946310-18a5cb00-fc07-11e9-9443-b8e86a4a4539.png)

## Expected result:

Token grants claimed should be aligned in BR panel
## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.73.44 Chromium: 78.0.3904.70 (Official Build) nightly (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? Not sure
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc

**Comment by LaurenWags** [comment]
Reproducible with

Brave | 0.71.112 Chromium: 78.0.3904.87 (Official Build) beta (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | macOS Version 10.13.6 (Build 17G5019)

**Comment by GeetaSarvadnya** [comment]
The issue is reproducible in Windows 10 x64 -0.71.113

![image](https://user-images.githubusercontent.com/38657976/68540687-0c1a3300-03bc-11ea-968b-5649fb91fa84.png)

**Comment by btlechowski** [comment]
Reproduced on

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/68578830-13e8de80-0473-11ea-9d83-4aa317719f72.png)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.50 Chromium: 79.0.3945.56 (Official Build) nightly (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Ubuntu 18.04 LTS

Verified test plan from the description.
English
![image](https://user-images.githubusercontent.com/34715963/70095556-5ee6b380-1625-11ea-896c-383e82737b9e.png)
Polish
![image](https://user-images.githubusercontent.com/34715963/70095613-7faf0900-1625-11ea-96ea-1e97955982b7.png)
German, still reproduces, logged https://github.com/brave/brave-browser/issues/7198
![image](https://user-images.githubusercontent.com/34715963/70095730-ca308580-1625-11ea-949f-3d61fb3f14fb.png)
