### ISSUE TITLE
BAT Points - BR panel flickering in the nightly build

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#6685]
## Description 

Seen this issue while testing https://github.com/brave/brave-browser/issues/6480. Please note this issue is happening only when I follow the test plan from https://github.com/brave/brave-core/pull/3751. I am not seeing this issue in general when I perform auto-contribution in Nightly builds 0.73.x. In #6480 test plan, we are changing the Preference file and updating country id to Japan, I am not sure is that the reason for the issue.

## Steps to Reproduce

   1. Launch nightly build 0.73.42 / 0.73.44 with staging env flags with a-c timestamp
   2. Follow the steps from https://github.com/brave/brave-core/pull/3751, continue till step 7
   3. After claiming grants add few verified sites to A-C table
   4. Send a one-time tip and monthly tip to a verified pubs
   5. Wait for auto contribution to complete
   6. Click on BR panel, BR panel starts fluctuating
   

## Actual result:

 BR panel flickering in the nightly build

![BAT Points - BR Panel Rewards summary](https://user-images.githubusercontent.com/38657976/67947716-46404380-fc0a-11e9-9d53-be6e07cec265.gif)

## Expected result:
Click on BR panel should display steady panel

## Reproduces how often: 

Always only with test plan from #6480 

## Brave version (brave://version info)

Brave | 0.73.44 Chromium: 78.0.3904.70 (Official Build) nightly (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? Not sure
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron @ryanml @mattmcalister

**Comment by GeetaSarvadnya** [comment]
STR:

1. Install 0.68.42 - staging environment
2. Enable rewards and accept the grants
3. Add verified and non- verified pubs to a-c table
4. Send one-time tip and monthly tip to verified pubs
5. Wait for the auto contribution to complete
6. Click on BR panel and verify auto contribution notification 
7. Don't dismiss the auto contribution notification from BR panel
8. Upgrade to 0.71.111
9. Click on BR panel start flickering the BR panel

The important step is step7 - without this issue is not reproducible
@ryanml Issue is reproducible without updating the `Preference` file.

**Comment by ryanml** [comment]
@GeetaSarvadnya are you able to reproduce this on latest nightly?

**Comment by GeetaSarvadnya** [comment]
@ryanml The issue isn't reproducible latest nightly build 1.3.28.

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya thank you for the test. Closing this issue
