### ISSUE TITLE
brave-browser : Depends: libappindicator3-1 but it is not installable

### ISSUE THREAD

**Issue by Hardik500** [brave/brave-browser#6686]
## Steps to Reproduce

   1. Install brave from the official website
   2. Then run sudo apt-get install brave-browser

## Actual result:

This is the result after running `sudo apt update`

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 brave-browser : Depends: libappindicator3-1 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

## Expected result:
Should run without any error

## Reproduces how often: 

Easily reporoduced

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@Hardik500 What's the distribution you're using?

**Comment by pawcijo** [comment]
I guess it is kali linux 64, i have the same problem.

**Comment by Hardik500** [comment]
I have kubuntu Eoan release. I fixed the issue by removing the adding the ubuntu port and fixed this issue by adding the `deb http:// eoan main universe` line in the `/etc/apt/sources.list file`.
