### ISSUE TITLE
Selecting to use Crypto Wallets over MetaMask (MM) should disable MM

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#6687]
<img width="1014" alt="Screen Shot 2019-10-24 at 2 58 54 PM" src="https://user-images.githubusercontent.com/831718/67516562-da406700-f66e-11e9-8c52-aca89f09bc3a.png">

Currently if the user selects to use Crypto Wallets we disable Crypto Wallets, but we don't actively disable MM the other way around. We should make this symmetric and disable it if the user selects that way.

**Comment by srirambv** [comment]
@bbondy Instead of completely disabling MM we should prompt the user to import from MM. Clicking `Use Crypto Wallets` should automatically trigger the restore wallet button to allow the user to enter the 12 code words to import wallet

**Comment by bbondy** [comment]
@srirambv pls post the suggestion as a separate issue. I think unbreaking for now is more important for the short term and we'd be able to get this done vs what you are suggesting faster.

**Comment by bbondy** [comment]
This will be deprecated with this work, so I'm closing this issue:
https://github.com/brave/brave-browser/issues/7503
