### ISSUE TITLE
Create or enable P3A UI for Android

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#6688]
Same as on desktop but for Android, we'll get the underlying functionality for free once we're on core. 

We need:
- [ ] To notify the user about it and tell them they can turn it off.
- [ ] Add the option to turn it off.

**Comment by bsclifton** [comment]
related https://github.com/brave/brave-browser/issues/6176

**Comment by anthonypkeane** [comment]
Ui should only be dismissible via one of the two options.
Pressing the HW back button should do anything unless that closes the app. 

![p3a](https://user-images.githubusercontent.com/7606853/68344000-eda5f600-00a2-11ea-852f-50dac1c527a7.png)

cc @bradleyrichter

**Comment by deeppandya** [comment]
Closing this issue as we have covered it in https://github.com/brave/brave-browser/issues/12723
