### ISSUE TITLE
Please add flags omnibox-ui-hide-steady-state-url-trivial-subdomains and omnibox-ui-hide-steady-state-url-scheme again

### ISSUE THREAD

**Issue by buffoon86** [brave/brave-browser#6689]
## Description 
In Version 78 it is no longer possible to show https:// and www part again

## Steps to Reproduce

   1. Install Brave
   2. open brave://flags
   3. Options brave://flags/#omnibox-ui-hide-steady-state-url-trivial-subdomains and brave://flags/#omnibox-ui-hide-steady-state-url-scheme are no longer present

On my knowledge there's no other way to always show the https:// and www parts of the url then installing the Suspicious Site Reporter from Google. I'm using brave to actually prevent installing extensions and such from Google

## Expected result:
Have a Flag/Option to show the full url and therefore prevent the strange hopping when editing urls

## Reproduces how often: 
On every new Installation

## Brave version (brave://version info)
Brave	0.70.121 Chromium: 78.0.3904.70 (Offizieller Build) (64-Bit)
Überarbeitung	edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
Betriebssystem	Linux
JavaScript	V8 7.8.279.17
Flash	(Deaktiviert)
User-Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
Befehlszeile	/opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=NewExtensionUpdaterService,PasswordImport,SimplifyHttpsIndicator,WebUIDarkMode --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,UnifiedConsent,SyncUSSBookmarks --flag-switches-begin --disable-smooth-scrolling --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,UnifiedConsent,SyncUSSBookmarks,OmniboxUIExperimentHideSteadyStateUrlScheme,OmniboxUIExperimentHideSteadyStateUrlTrivialSubdomains --flag-switches-end
Ausführbarer Pfad	/opt/brave.com/brave/brave
Profilpfad	/home/PRISMBZ/christoph/.config/BraveSoftware/Brave-Browser/Default

This happens also on Windows

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? Yes
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by fysiks1** [comment]
I just spent an hour trying to figure out why I couldn't show these parts of the URL.  It is EXTREMELY disappointing that this was removed.  I don't want an obfuscated truth.  It's on par with Microsoft's decision to hide file extensions by default (which is a security flaw IMO).

**Comment by ssa3512** [comment]
You can bring these back by enabling `#temporary-unexpire-flags-m76` but it looks like chromium is planning to permanently remove these at some point.
Chromium discussion here, closed as wontfix https://bugs.chromium.org/p/chromium/issues/detail?id=1019020

It would be great if brave would revert this change

**Comment by rebron** [comment]
Closing wontfix. cc: @diracdeltas Do you agree?

**Comment by DFNCTSC** [comment]
Sad and pathetic. All educated users have been leaving Chromium-based browsers and it will only continue to do so.

**Comment by bsclifton** [comment]
@DFNCTSC more discussion at https://github.com/brave/brave-browser/issues/7449 if you wanted to give it a +1 and leave a comment

**Comment by kasumiru** [comment]
UP. add the flag!
