### ISSUE TITLE
Brave Rewards button

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#669]
## Description 
A new button in the BraveActions area, along with the Shields button (see #668).
This button should have the following states:
- Rewards On
- Rewards Off
- Non-Rewards page

Clicking the button should invoke a web-ui popup which displays overall Rewards status (balance, etc) and actions for the active Tab. TBD whether this is an extension page or webui page.

**Comment by NejcZdovc** [comment]
There is one more stage, rewards on with notification

**Comment by petemill** [comment]
Here's my current thoughts on how we should do the data for this button:

- Create a browser class very similar to [ExtensionAction](https://cs.chromium.org/chromium/src/chrome/browser/extensions/extension_action.h?sq=package:chromium&g=0&l=79), `RewardsAction`. This can have per-tab data for icon and badge text, falling back to global values if no per-tab value is set. It will be the central class for the Rewards service to update the icon data (based on the navigation events it needs to monitor), and the UI layer to read the data from. It will store:
   - Which icon state to be in, per-tab. We can use an enum value instead of an exact Image here.
   - Badge text

As already decided, clicking the button will open a WebUI page in a popup. If we need to vary the exact URL that should open based on the tab publisher state or otherwise (which I don't think we will want to do atm) then `RewardsAction` can also store the URL which should open.

Since you've been working on the Rewards service so far and and I haven't looked at the branch yet @bridiver @NejcZdovc please let me know if you think this is something the Rewards service can send the data to for each tab.

**Comment by NejcZdovc** [comment]
@petemill update. We will only have enable and disable state. There will not be verified state

**Comment by bridiver** [comment]
actually we should look at component actions too

**Comment by petemill** [comment]
Sure @bridiver we can probably use another extension - I believe in a previous discussion @bbondy may have mentioned WebUI was preferable. I forget the reasons, but possibly due to ease of specific data access and providing events, though obviously we do that for shields.

I have already subclassed `ExtensionActionViewController` for the shields button in order to give it a different style to the other extensions.

**Comment by bridiver** [comment]
I think creating a popup view that displays a webui is probably going to be more complicated, but we can potentially subclass ExtensionActionViewController to do that as well

**Comment by petemill** [comment]
@bridiver I did a cursory look and the popup accepts a GURL pretty early on in the call stack

**Comment by bridiver** [comment]
you can't just pass any url to it. It creates an extension host and you can't open a webui in an extension process

**Comment by NejcZdovc** [comment]
**update**: we will just have on state and notification indicator if there will be one

**Comment by NejcZdovc** [comment]
![image](https://user-images.githubusercontent.com/9574457/45049262-6617be00-b07e-11e8-891b-3384d587ace1.png)

![image](https://user-images.githubusercontent.com/9574457/45049270-6a43db80-b07e-11e8-901f-236737bd7840.png)

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

* Verified Rewards On
![image](https://user-images.githubusercontent.com/17010094/46504186-29fd8780-c7fb-11e8-8523-e2311bf612ca.png)
* Verified Rewards Off
![image](https://user-images.githubusercontent.com/17010094/46504191-31249580-c7fb-11e8-9d2f-e834e340c0eb.png)
* Verified Non-Rewards page (still needs to be verified on device for  #1429)
![image](https://user-images.githubusercontent.com/17010094/46504162-10f4d680-c7fb-11e8-8d6f-ab2c3138b4bc.png) 
* #1424  logged for missing translations text
