### ISSUE TITLE
General UI colors - Dark, Light, PrivateDark, PrivateLight

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#670]
## Description 
Provide built-in theme properties. These are mainly toolbar colors. https://cs.chromium.org/chromium/src/chrome/browser/themes/theme_properties.cc?q=theme_prop&sq=package:chromium&g=0&l=1

**Comment by srirambv** [comment]
On Linux the command line switch doesn't make any changes to theme. @kjozwiak also was not able to see changes using the command line switch. Manually setting the Brave colour works just fine.

**Comment by bsclifton** [comment]
@srirambv do other command line options work OK on Linux? ex: disable hardware acceleration, etc

**Comment by kjozwiak** [comment]
@srirambv did we create a new issue regarding command line options not working?

I tried going through the following under `Ununtu 18.04 x64` using `0.55.10 Chromium: 70.0.3538.22` but couldn't get the command line options to work:

* `brave-browser-beta --disable_gpu`
* `brave-browser-beta --ui_mode=dark`
* `brave-browser-beta --ui_mode=light`

I also tried on macOS on `0.55.x` that was built form source but couldn't get that working either. Tried the following:

`src/out/Debug/Brave\ Browser\ Development.app/Contents/MacOS/Brave\ Browser\ Development --ui_mode=light --disable_gpu`

@bsclifton @petemill are we doing something wrong here or is this broken and requires a new issue?

**Comment by srirambv** [comment]
No issue logged yet. I will test from source on Linux with those command line parameters and then log it.

**Comment by LaurenWags** [comment]
@petemill does this need to be tested with the command line parameters or can it be tested by switching between the themes in settings?

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.17 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux

* Verified launching browser with `npm run start -- --ui_mode=light` had omnibar and dropdown in light 
* Verified launching browser with `npm run start -- --ui_mode=dark` had omnibar and dropdown in dark
