### ISSUE TITLE
auto refresh page when selecting 'Always allow autoplay on..." setting

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#6700]
## Description 
When users have autoplay blocked, we'll show the autoplay icon. However, if selecting 'Always allow autoplay on ..." nothing happens. A user needs to manually refresh the page. We should automatically refresh the page after a user selects 'Always allow autoplay on...' setting and hits done.

## Steps to Reproduce

   1. Go to `https://www.tesla.com/model3` or a page you know will trigger autoplay
   2. Select autoplay icon.
   3. Notice that you'll need to manually refresh page in order for 'Always allow autoplay' setting to actually work.

![Screen Shot 2019-10-31 at 4 37 50 PM](https://user-images.githubusercontent.com/5951041/67993299-7208fc80-fbfd-11e9-9baf-e388f4f48dd6.png)

## Expected result:
Autorefresh of page after selecting `Always allow autoplay on ...' and hitting done or enter.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.2.5 Chromium: 78.0.3904.97 (Official Build) dev (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified STR from description
