### ISSUE TITLE
Error when run build code on Windows

### ISSUE THREAD

**Issue by pidzvnese** [brave/brave-browser#6702]
## Description 
I am trying to build brave-browser source code. But, when I am run `npm run build` have a error.

## Steps to Reproduce

   1.  clone code (done) : git clone git@github.com:brave/brave-browser.git
   2. run install and init (done)
   3. try to npm run build

## Actual result:

> 0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.12.0
3 info using node@v12.13.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle brave@0.73.46~prebuild: brave@0.73.46
6 info lifecycle brave@0.73.46~build: brave@0.73.46
7 verbose lifecycle brave@0.73.46~build: unsafe-perm in lifecycle true
8 verbose lifecycle brave@0.73.46~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\brave-browser\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NGX;D:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\bin;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\nodejs\;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\libexec\git-core;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;D:\brave-browser\vendor\depot_tools;D:\brave-browser\vendor\depot_tools\win_toolchain;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64;C:\Python27;C:\Users\nhpov\AppData\Local\Microsoft\WindowsApps;C:\Users\nhpov\AppData\Roaming\Composer\vendor\bin;C:\Users\nhpov\AppData\Roaming\npm;C:\Users\nhpov\AppData\Local\Programs\Microsoft VS Code\bin
9 verbose lifecycle brave@0.73.46~build: CWD: D:\brave-browser
10 silly lifecycle brave@0.73.46~build: Args: [ '/d /s /c', 'node ./scripts/commands.js build' ]
11 silly lifecycle brave@0.73.46~build: Returned: code: 1  signal: null
12 info lifecycle brave@0.73.46~build: Failed to exec build script
13 verbose stack Error: brave@0.73.46 build: `node ./scripts/commands.js build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid brave@0.73.46
15 verbose cwd D:\brave-browser
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.13.0
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 1
22 error brave@0.73.46 build: `node ./scripts/commands.js build`
22 error Exit status 1
23 error Failed at the brave@0.73.46 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

## Reproduces how often: 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? not tried
- Can you reproduce this issue with the dev channel? not tried
- Can you reproduce this issue with the nightly channel? not tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? not tried
- Does the issue resolve itself when disabling Brave Rewards? not tried
- Is the issue reproducible on the latest version of Chrome?  not tried

**Comment by rebron** [comment]
cc: @bsclifton

**Comment by bsclifton** [comment]
@pidzvnese can you try installing VS 2019? I think there was an upgrade required and our documentation is out of date. Going to verify what I have installed...

**Comment by bsclifton** [comment]
Closing as there hasn't been a response. Above recommendation should resolve it (installing VS 2019)
