### ISSUE TITLE
UA

### ISSUE THREAD

**Issue by FatBirdie** [brave/brave-browser#6704]
I have searched, and I understand Brave have excluded 'Brave' from the UA for fingerprint reasons. I have sympathy for this but do also think it would be better to give the user an option to change their UA instead.

## Expected result:
As a site owner, I want to be able to help people find Brave, not by spamming but by targeting.
Please re-add 'Brave' to the UA string.

**Comment by bsclifton** [comment]
Thanks for the report, @FatBirdie - we do have plans to re-add the user-agent 😄 This is being tracked with https://github.com/brave/brave-browser/issues/1052

We also do have an issue open to allow customizing of the UA - although, that might be better handled with an extension: https://github.com/brave/brave-browser/issues/1056
