### ISSUE TITLE
Wrong grant type in the response to `Grants::FetchGrants` is resolved as Ads grant and presented on UI so.  

### ISSUE THREAD

**Issue by gdregalo** [brave/brave-browser#6711]
## Description 

If server by mistake sends unexpected value in grant.type in response to `FetchGrants`, then it will be resolved as ads grant and presented to a user so.
https://github.com/brave/brave-core/blob/master/components/brave_rewards/browser/rewards_notification_service_impl.cc#L337.
It would be good if we have a check for acceptable grants types when parsing json.

## Steps to Reproduce

   1.  Modify grant type when parsing json response to `FetchGrants`.
   2. 
   3. 

## Actual result:

The Ads grants is presented on UI. 
Observable on Android.

## Expected result:
Check for acceptable grants types when parsing json response. Ignore corrupted response or log it and add to  statistics sent back to Brave. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
this one should be addressed with https://github.com/brave/brave-core/pull/3918
