### ISSUE TITLE
Youtube occasionally requires refresh to play videos

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#6712]
Have you searched for similar issues? Yes.

## Description 
I'm positive this is as a result of Shields as I've noticed it for over a year now. The issue is when entering a link manually or clicking on another video on youtube sort of goes to that video but doesn't play it. In addition, the screen which doesn't automatically play shows the video of the previous page (like a screenshot) and pressing play presents the previous video, not the video you pressed enter to or clicked on.

## Steps to Reproduce

It's difficult to reproduce as it happens occasionally and I don't know what exactly triggers the issue. Though I should mention I've noticed the issue in Tor and normal windows but I don't think I've ever noticed it in private windows though I'm not to sure. **Update** - yes it does also occur in private tabs.

## Actual result:
I'll update when the issue occurs again. **Update** - 

![Screenshot_20191110_190935](https://user-images.githubusercontent.com/31957540/68553096-47e1e680-0416-11ea-8e26-295ab5607a75.png)

## Reproduces how often: 
Occasionally.

## Brave version (brave://version info)
`1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit) (openSuse)`
To be honest I've noticed the issue carry on from the Muon version, which leads me to suggest it's related to Shields. I'm often on the latest stable Release on Linux (openSuse).

## Other Additional Information:

The issue resolves itself when hitting refresh.

**Comment by rebron** [comment]
cc: @ryanbr and @Brave-Matt Are you guys seeing this with some of the other YouTube issues?

**Comment by ryanbr** [comment]
@NumDeP does this occur in Brave 1.0.1? Also, could you toggle the site-trackers in shields?

**Comment by NumDeP** [comment]
It still occurs in `1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit) (openSuse)` 

 I'll try toggling the site-trackers in shields. However, as a force of habit for quite a while now I've become accustomed to pressing F5 almost instantly.

**Comment by NumDeP** [comment]
Toggling site-trackers does load the page and present the video but I don't see how that would be different from hitting refresh anyway.

I should mention still on a related topic, issues like the screenshot below I noticed that hitting refresh does not fix the issue Tor. In this case it was a normal window but in Tor it simply does not work.

![Screenshot_20191207_173726](https://user-images.githubusercontent.com/31957540/70380457-e6893680-1933-11ea-8ed3-1fa37a5cd398.png)

**Comment by ryanbr** [comment]
Try clearing the cookies for youtube.com, and then restarting the browser @NumDeP   Leaving Site-trackers in Shields enabled should still be fine also.

**Comment by ryanbr** [comment]
How is it looking @NumDeP ? Did clearing the cookies help?

**Comment by NumDeP** [comment]
@ryanbr I typically on every browser/system shutdown manually clear most data types on just before shutdown and this has occurred on different occasions.

The only types that aren't selected for clearing on exit is passwords, site settings and hosted app data.

Cookies and other site data is of course cleared as well but the issue is still apparent.

**Comment by bsclifton** [comment]
@NumDeP was this still an issue for you? or have you not seen it for a while?

**Comment by NumDeP** [comment]
I have not seen the issue persist in a while @bsclifton
