### ISSUE TITLE
A/C goes through despite being turned OFF

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#6716]
Auto contributions are going through in all current releases (0.71, 0.70, 0.69) and the latest nightly even if the user has turned off the A/C switch.

cc @NejcZdovc

**Comment by eljuno** [comment]
+1s from Community 

https://community.brave.com/t/random-auto-contribute-even-though-it-was-off/90845?u=eljuno

**Comment by SaltwaterC** [comment]
> You sent 5 BAT to @BravePublishers

This has been automatically executed on a Windows installation of Brave.

TX id: 5d8ef5ca-d073-4fd5-9dc1-a3966c1b3882

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from https://github.com/brave/brave-core/pull/3915
* Confirmed if AC table contains verified publishers and AC is toggled OFF, AC does not go thru.
* Confirmed if AC table contains verified publishers and AC is toggled OFF and recurring monthly tips are set up, AC does not go thru but recurring monthly tips are contributed as expected.
* Confirmed if AC table contains verified publishers and Rewards is toggled OFF (but AC is **not** explicitly toggled off), AC does not go thru.
* Confirmed if AC table contains verified publishers and recurring monthly tips are set up and Rewards is toggled OFF (but AC is **not** explicitly toggled off), AC does not go thru AND recurring monthly tips are not contributed. Works as expected.
* Confirmed if Rewards are ON, AC is ON (and contains verified publishers) and recurring monthly tips are set up, AC and recurring monthly tips are contributed as expected.
