### ISSUE TITLE
Video commercials aren't blocked on music.youtube.com

### ISSUE THREAD

**Issue by johnmhm** [brave/brave-browser#6717]
## Description 
Video commercials are no longer blocked on music.youtube.com.

## Steps to Reproduce
   1. Go to `https://music.youtube.com` 
   2. Start a playlist, album or track.

## Actual result:
Instead of ad-free experience, video commercials preface and/or interrupt music.
![image](https://user-images.githubusercontent.com/13797130/68046133-6855c680-fcdb-11e9-9bdd-05af5cc4cf6c.png)

## Expected result:
Listening to music without commercial interruptions.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Version 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)
Windows 10, ver. 1903, build 18362.418

**Comment by johnmhm** [comment]
I can temporarily fix it by _blocking scripts_ and then unblocking them again. Before I do this the Brave pop-up shows 0 items blocked on music.youtube.com, and after I switch script blocking on & off, it rapidly grows to 50+ items blocked, and no video commercials are shown.

This unfortunately means I can't have music.youtube.com running as a Brave app, as there isn't any interface to adjust brave ad block settings in the app menu.

**Comment by anotherzen** [comment]
I can confirm, having the same issue as OP.

Brave version:
Version 0.70.123 Chromium: 78.0.3904.97 (Official Build) (64-bit)

**Comment by johnmhm** [comment]
Still an issue on Version 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)

**Comment by jakjothi** [comment]
I'm also facing same issue

**Comment by rebron** [comment]
cc: @ryanbr and @Brave-Matt Are you guys seeing this with some of the other YouTube issues? Dupe?

**Comment by kjozwiak** [comment]
I can reproduce this pretty easily by simply watching anything under `https://music.youtube.com`. Looks like ads being blocked under `https://www.youtube.com` but not `https://music.youtube.com`.

Build being used to reproduce the issue:

Brave | 1.3.22 Chromium: 78.0.3904.108 (Official Build) nightly (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | macOS Version 10.15.1 (Build 19B88)

Example of the issue occurring:

<img width="1197" alt="Screen Shot 2019-11-23 at 6 18 34 PM" src="https://user-images.githubusercontent.com/2602313/69486873-ed398900-0e1e-11ea-8cd9-569386c12cf2.png">

**Comment by ryanbr** [comment]
@kjozwiak I tried this the other day; https://secure.fanboy.co.nz/gif/google-music.gif  can you re-test? toggle the cross-site trackers

**Comment by johnmhm** [comment]
Still an issue on Version 1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)

**Comment by ryanbr** [comment]
@johnmhm Can you clear you cookies and cache, and re-test with shields enabled? (see my gif previously, since I couldn't reproduce it last time I tested)

**Comment by johnmhm** [comment]
@ryanbr No problem. I have cleared cookies and cache for 'all time' and issue persists
![image](https://user-images.githubusercontent.com/13797130/70681849-21c19780-1c9d-11ea-841a-eb5a4f7c33f6.png)

**Comment by johnmhm** [comment]
It is now completely impossible to listen to songs on music.youtube.com with shields up. 

Client tries loading a song (and a bunch of xs trackers) for 10 seconds, and then tries to load the next song on the playlist.

Only remedy is to turn off shields or use different browser.

Version 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)

**Comment by johnmhm** [comment]
The issue persists on Android versions of Brave, if someone wants to look for clues.

**Comment by johnmhm** [comment]
The issue has returned on desktop. Please see attached gif for more detail:
![2020-03-25 05-38-43](https://user-images.githubusercontent.com/13797130/77502822-444a7b80-6e5c-11ea-9dd6-078eea52490f.gif)

**Comment by ryanbr** [comment]
Can you test in Brave Beta?

I just re-tested this: https://secure.fanboy.co.nz/gif/musicyoutube.gif (as of today)

**Comment by ryanbr** [comment]
Just for the record, this the error messages i'm getting: ![yt](https://user-images.githubusercontent.com/1659004/77518043-f24c3900-6ee1-11ea-8c07-47b553e28525.png)

**Comment by johnmhm** [comment]
Same behavior in Brave Beta with shields up. But with shields down the music still doesn't play, which 1.5 did fine. 

![2020-03-25-14-47-28](https://user-images.githubusercontent.com/13797130/77543674-4fc39400-6ea8-11ea-93b3-1d65882cb5fc.gif)

I now realize that I wasn't logged in when testing Brave Beta. Let me know if you need me to test that scenario.

**Comment by johnmhm** [comment]
Also, I don't know anything about how the Youtube Music dev team works, but I guess it could be possible that they're serving different clients to different segments of users? A/B split testing, covert beta testing etc. Is there an easy and meaningful way to ensure we're running the same client when testing?

**Comment by ryanbr** [comment]
What is the error messages in the console @johnmhm ?

**Comment by johnmhm** [comment]
`Access to XMLHttpRequest at 'https://www.youtube.com/get_video_info?html5=1&video_id=tNideOigKaI&cpn=FzYhfpVnLpFXpQPw&eurl&el=detailpage&hl=en_GB&list=RDMMlpExvx7pbuI&sts=18346&lact=6786&c=WEB_REMIX&cver=0.1&cplayer=UNIPLAYER&itct=CGkQyCAYASITCOHD1YvItugCFQ5NmwodHPMC6jIDQkZhSKGY74iFgK_bygE%3D&autoplay=1&autonav=1&playerretry=1' from origin 'https://music.youtube.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

and 


`2 www.youtube.com/get_video_info?html5=1&video_id=tNideOigKaI&cpn=FzYhfpVnLpFXpQPw&eurl&el=detailpage&hl=en_GB&list=RDMMlpExvx7pbuI&sts=18346&lact=6786&c=WEB_REMIX&cver=0.1&cplayer=UNIPLAYER&itct=CGkQyCAYASITCOHD1YvItugCFQ5NmwodHPMC6jIDQkZhSKGY74iFgK_bygE%3D&autoplay=1&autonav=1&playerretry=2:1 GET https://www.youtube.com/get_video_info?html5=1&video_id=tNideOigKaI&cpn=FzYhfpVnLpFXpQPw&eurl&el=detailpage&hl=en_GB&list=RDMMlpExvx7pbuI&sts=18346&lact=6786&c=WEB_REMIX&cver=0.1&cplayer=UNIPLAYER&itct=CGkQyCAYASITCOHD1YvItugCFQ5NmwodHPMC6jIDQkZhSKGY74iFgK_bygE%3D&autoplay=1&autonav=1&playerretry=2 429`

The last one is interesting - error 429. Maybe this isn't a Brave issue after all, but a Youtube Music vs me issue?

**Comment by johnmhm** [comment]
Just tested again through a VPN, and everything works as before. Apparently Youtube thinks I listen to too much music :( 

Sorry I didn't catch this earlier, and thanks for the help @ryanbr

**Comment by ryanbr** [comment]
Does it still fail when you're not using a VPN? or which country/location is failing?

**Comment by ryanbr** [comment]
We did roll out fixes recently, could be related to the fact the browser hasn't updated them yet

https://github.com/easylist/easylist/commit/a621dca8b2a0521b6b51c215ab6a0b27a8351522

**Comment by johnmhm** [comment]
It still fails without VPN. 

With VPN I don't get any Error 429 messages (Too many connections).

**Comment by ryanbr** [comment]
We've been working to get youtube ads fixed which would affect this. @johnmhm has the latest Brave build fixed any of these issues?

**Comment by johnmhm** [comment]
Indeed, they do seem to have fixed the latest regression! Thank you!
