### ISSUE TITLE
rewards NTP widget isn't updating with estimated ad earnings

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6722]
## Description 
`Estimated earnings so far this month` is not updating on NTP widget.

## Steps to Reproduce

   1. Clean profile
   2. Enable Rewards
   3. View some ads

## Actual result:
NTP widget does not update
<img width="1163" alt="Screen Shot 2019-11-01 at 5 56 25 PM" src="https://user-images.githubusercontent.com/28145373/68059309-6a675780-fcd2-11e9-90bd-79a04bc77478.png">

## Expected result:
NTP widget should update

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.73.51 Chromium: 78.0.3904.87 (Official Build) nightly (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the dev channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @mandar-brave @ryanml

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.71.111 Chromium: 78.0.3904.87 (Official Build) (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/68127234-77d34a80-ff3b-11e9-9151-b2402a07c911.png)
