### ISSUE TITLE
[Follow-Up] deps of brave/browser/importer target

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#6726]
In https://github.com/brave/brave-core/pull/3833, we covered most of the missing deps from brave/browser/importer target to fix intermittent CI build error.
There are still some deps missing at the moment after that PR.
This is a follow up to fix them.

By running gn check on the brave/browser/importer target, current missing deps are:
1. `chrome/browser:browser`
We can't depend on this target because of circular dependency.
@bridiver suggested that we should refactor our patch of `chrome/browser/BUILD.gn` to have something like:
```
sources += brave_browser_sources
deps += brave_browser_deps
```
Then add all the sources currently in `brave browser_process` target into `brave_browser_sources`.
After above, we could just add `chrome/browser:browser` into `brave/browser/importer` target's deps.

2. `brave/browser:browser_process`
We can't depend on browser_process target because of circular dependency. 
To solve this, we probably just need to move at least brave/browser/search_engines/search_engine_provider_util.cc/h into its own target.

3. `brave/utility`
Not added yet because of the following error on Windows build,
```
21:31:00  lld-link: error: undefined symbol: public: __cdecl ChromeContentUtilityClient::ChromeContentUtilityClient(void)
21:31:00  >>> referenced by ../../brave/utility/brave_content_utility_client.cc
21:31:00  >>>               obj/brave/utility/utility/brave_content_utility_client.obj
21:31:00  
21:31:00  lld-link: error: undefined symbol: public: virtual __cdecl ChromeContentUtilityClient::~ChromeContentUtilityClient(void)
21:31:00  >>> referenced by ../../brave/utility/brave_content_utility_client.cc
21:31:00  >>>               obj/brave/utility/utility/brave_content_utility_client.obj
21:31:00  
```

**Comment by bsclifton** [comment]
Closing as stale - we removed the Brave importer and have added more importers, each passing lint and gn check 👍
