### ISSUE TITLE
Rewards NTP "Way to Go!" popup covers rewards widget

### ISSUE THREAD

**Issue by mbacchi** [brave/brave-browser#6727]
## Description 
On first using the new tab page on Nightly on Linux, it showed the "Way to Go!" popup covering 2/3s of the Brave Rewards widget. I would think the popup would provide more room to display the full widget.

## Steps to Reproduce
Open Nightly Version 0.73.51 for the first time on Linux.

## Actual result:
![image](https://user-images.githubusercontent.com/6763301/68062212-4d855100-fcdf-11e9-9a61-711a7ebb5ade.png)

## Reproduces how often: 
Only on initial startup of the browser with the widget enabled in the NTP. If I kill and then restart nightly, open a new tab, it does not occur.

## Brave version (brave://version info)
Version 0.73.51 Chromium: 78.0.3904.87 (Official Build) nightly (64-bit)

```
Brave	0.73.51 Chromium: 78.0.3904.87 (Official Build) nightly (64-bit)
Revision	20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS	Linux
JavaScript	V8 7.8.279.19
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
Command Line	/opt/brave.com/brave-nightly/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=NewExtensionUpdaterService,PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,AudioServiceOutOfProcess,SmsReceiver,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,UnifiedConsent,SyncUSSBookmarks --flag-switches-begin --flag-switches-end
Executable Path	/opt/brave.com/brave-nightly/brave
Profile Path	/home/mbacchi/.config/BraveSoftware/Brave-Browser-Nightly/Default
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
this was fixed, so that it covers numbers as well. @mbacchi what would be your suggestion on how to improve this?

**Comment by mbacchi** [comment]
Looks good, thanks!
