### ISSUE TITLE
Suggestion: reproducible builds for Brave

### ISSUE THREAD

**Issue by hugecheese** [brave/brave-browser#6728]
https://reproducible-builds.org/

I believe this would greatly improve the security of the Brave Browser.  The majority of users will simply use Brave from a binary blob downloaded from the web. There is no way to independently verify that the release has not been tampered with relative to the source code on GitHub.

It would be great if the following were possible:
```bash
git checkout 79.0.3945.16
npm run build Release
wget <binary blob url>
# the hash of brave's blob and the local build are verifiably the same
```

**Comment by bsclifton** [comment]
Definitely something we want - I know @mbacchi had heard about a way to do deterministic builds for Chromium (don't remember the details, unfortunately)

**Comment by brianddk** [comment]
> I know @mbacchi had heard about a way to do deterministic builds for Chromium (don't remember the details, unfortunately)

Perhaps a reference to [issue #5830](https://github.com/brave/brave-browser/issues/5830)
