### ISSUE TITLE
Endless loading // Webpage won't load from URL

### ISSUE THREAD

**Issue by pilsnerbeer** [brave/brave-browser#6730]
## Description 
Approx. 1 times out of 10, Brave will not load a webpage from URL. It will load endlessly, like so:

![Screenshot_1](https://user-images.githubusercontent.com/36133540/68072740-18cdd400-fd89-11e9-9cbe-ec6c5c05d607.png)

.. with "processing request" on the bottom.

## Steps to Reproduce

   1. Use brave normally
   2. Type URL in the top bar
   3. Once in a while it will freeze.
Note: web searches work fine, it is the URLs that never load.

## Reproduces how often: 
Once every few requests.

## Brave version (brave://version info)

Brave | 0.70.122 Chromium: 78.0.3904.87 (Official Build) (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Windows 10 OS Version 1903 (Build 18362.418)

## Other Additional Information:

I have the shields ON including fingerprint protection and use the following extensions:
- ublock origin
- privacy badger
- cookie autodelete
- privacy possum
- decentraleyes

So far I havent tried to disable them as they never caused any problems before on Brave or any other browser. I will try to investigate though

**Comment by Gagala** [comment]
Same here, just using Linux. That 'hanging' happens on some sites, not all. 
Current temporary solution: **Pressing F5**, then the connection works again.
 I hope this will turn back to normal with the next update.

**Comment by pilsnerbeer** [comment]
@Gagala do you by any chance use similar extensions?

**Comment by Gagala** [comment]
[Brave Version](http://firegoon.com/u/172h2.jpg)
[Own Extensions](http://firegoon.com/u/3cywc.jpg)
[Brave Extensions (all off)](http://firegoon.com/u/9taey.jpg)

**Comment by zaknesler** [comment]
I have been having this same issue. Try disabling Ghostery, @Gagala, because that worked for me. Now to figure out *why*...

**Comment by Gagala** [comment]
Ghostery is an extension that I have installed since I'm using Brave more than a half year ago and until the penultimate update of Brave the described 'hanging' problems never appeared, so something at Brave must have been changed that causes these problems. But on the other hand I haven't watched if there has been an update on Ghostery as well and that is causing problems. So **I removed Ghostery and it seems Brave works better again now**. It's sad, I liked Ghostery. 
Thanks for the hint!

**Comment by bsclifton** [comment]
@Gagala thanks for the update! 😄 

@pilsnerbeer did you get a chance to try disabling extensions, to see if it helps?

I can definitely see how a problem might occur. Brave (the shields, for example) has an extension built in which will run content scripts. It's possible there's a conflict

You may be able to diagnose by going to chrome://inspect/#extensions and then clicking `Inspect` under each extention to open up the console logs. There may be errors showing there which have information that could help us identify the problem

**Comment by pilsnerbeer** [comment]
@bsclifton Yes, I selectively disabled custom extensions to find out it is 'Privacy Possum' which is causing trouble. I haven't been able to reproduce the issue with this extension disabled. 
Oddly enough, I have no such problems on Linux, only Windows.

**Comment by rebron** [comment]
cc: @Brave-Matt Heads up on this one. Maybe an article that encompasses some extension issues, e.g. turning it off if running into issues like this one. 

Closing this one as wontfix.
