### ISSUE TITLE
Rewards NTP widget notification/enable button style

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#6732]
Per @bradleyrichter the following updates should occur:

1. The notification to claim a grant should start just below the BAT logo + Brave Rewards title, text should not be cut off
2. The notification button to claim a grant should be color `#1DB100`
3. The notification button, button to turn on ads, and button to turn on rewards should have no border at all. (A light gray border is currently present)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1903 (Build 18362.418)

* Claim ads grant message
![image](https://user-images.githubusercontent.com/17010094/68615345-dd21c100-0490-11ea-8930-0e36d521e447.png)
* Background colour of button is set to `#1DB100`
![image](https://user-images.githubusercontent.com/17010094/68615545-49042980-0491-11ea-8ecc-fb939bcac20a.png)
* New tab message before rewards is enabled for the first time
![image](https://user-images.githubusercontent.com/17010094/68615665-8799e400-0491-11ea-90ac-fcd2b15e6034.png)
![image](https://user-images.githubusercontent.com/17010094/68615776-badc7300-0491-11ea-81f6-d562412e61c5.png)
