### ISSUE TITLE
Ethereum Phishing Detection: cannot "continue at own risk"

### ISSUE THREAD

**Issue by ryzr** [brave/brave-browser#6734]
## Description 

I'm building a website locally under a .test domain (crypto.test), which seems to be fuzzymatching blacklisted domains on the Metamask Eth Phishing Detection extension (built-in to Brave, it appears?). There is a link to continue at own risk, but clicking it doesn't appear to do anything.

## Steps to Reproduce

   1. Visit a site with a name that fuzzy matches "mycrypto.com". You could try "http://mcrypto.com/"
   2. Click `a#unsafe-continue` "continuing at your own risk"
<img width="1227" alt="Screen Shot 2019-11-03 at 12 57 57 PM" src="https://user-images.githubusercontent.com/9389421/68079469-06f83980-fe3a-11e9-8315-de4e7991e48f.png">

## Actual result:
Nothing happens

## Expected result:
Remove warning page and continue to the intended site.

## Reproduces how often: 
100%

## Brave version (brave://version info)

Brave | 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | macOS Version 10.14.6 (Build 18G95)
JavaScript | V8 7.8.279.17
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No attempt
- Can you reproduce this issue with the dev channel? No attempt
- Can you reproduce this issue with the nightly channel? No attempt

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

I have "Safe Browsing (protects you and your device from dangerous sites)" disabled and I've also tried disabling Brave Wallet, but this did not fix the issue.

**Comment by srirambv** [comment]
Confirmed an issue with Crypto wallet. Doesn't navigate to the site. If MM is installed and CW not enabled, visiting the site gets blocked by MM page, clicking the anchor tag redirects to CW Etherum phishing link which again blocks and doesn't redirect. 

cc: @bbondy

**Comment by srirambv** [comment]
+1 from @Arcbot-ArcusBD  via #7610

**Comment by ryanml** [comment]
This is fixed in `1.0.15`, added to milestone

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.2.41 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Linux
Component | `0.1.34`

- Verified on `http://mycrypto.com` and `https://www.arcus.mx/` 
- Verified clicking on `continuing at your own risk.` on the phishing page navigates to the landing page properly
