### ISSUE TITLE
Brave crashes when paywalls raised on Washington Post when PrivacyBadger (or other paywall extensions) installed

### ISSUE THREAD

**Issue by tbpassin** [brave/brave-browser#6735]
## Description 
With Brave V 0.70.122 and the previous version on Windows 10 v1903, opening www.washingtonpost.com consistently crashes my installation, including after a re-install.  The page appears to open correctly, but then the browser silently closes.

## Steps to Reproduce
   1.  Type www.washingtonpost.com into the URL bar.
   2. Observe the page open and apparently display.
   3.  Observe the browser close without any message.

## Expected result:
The page should open and stay readable.

## Reproduces how often: 
Every time on my system.

## Brave version (brave://version info)

0.70.122 Chromium: 78.0.3904.87 (Official Build) (64-bit)
--
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Windows 10 OS Version 1903 (Build 18362.418)

## Version/Channel Information:
NA
- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
NA
- Can you reproduce this issue with the dev channel?
NA
- Can you reproduce this issue with the nightly channel?
NA

## Other Additional Information:
Same thing happened on the previous release, but before that behavior was normal.
- Does the issue resolve itself when disabling Brave Shields?
Untried.
- Does the issue resolve itself when disabling Brave Rewards?
Not in use.
- Is the issue reproducible on the latest version of Chrome? 
No problem on "Version 78.0.3904.87 (Official Build) (64-bit)"

**Comment by bsclifton** [comment]
@tbpassin do you have any extensions installed? Specifically, any that are blocking paywalls?

There was a recent issue report where an extension did break and cause a crash.  Let us know 😄

**Comment by tbpassin** [comment]
> @tbpassin do you have any extensions installed? Specifically, any that are blocking paywalls?
> 
> There was a recent issue report where an extension did break and cause a crash. Let us know 😄

Ha! It stopped quitting after I disabled Privacy Badger.  Thanks for the suggestion - I forgot I had added any extensions.  I don't know that a paywall was involved, since I can ordinarily browse the Post without logging in on another browser with a javascript blocker and Privacy Badger (specifically Vivaldi).  Well, maybe it started with a version update to Privacy Badger;  I probably wouldn't have remembered.

**Comment by bsclifton** [comment]
@tbpassin thanks for the update! 😄 

Definitely seems like a bug on our side too - even if the extension is raising the error. Let me re-open the issue and reword things a bit 😄

**Comment by iefremov** [comment]
appears to be fixed, @tbpassin could you recheck?

**Comment by tbpassin** [comment]
I have checked using 

Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)

And even after installing Privacy Badger I no longer get crashes on the Washington Post page.

Thank you!
