### ISSUE TITLE
Intelligently load bookmarks and session-storage-1, s-s-2 etc. files without duplicates

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#6737]
Have you searched for similar issues? Yes. I think #6461 is the closest issue but this is slightly different.

## Description 

I think the titles speaks for itself but I'll go on to clarify the addition.

I would really like it if the team allowed a drag and drop functionality in the bookmark area that basically allowed as many bookmarks and previous session-storage files to be uploaded into the browser without any duplicates or at least notifying the user of duplicates if in case they're intended but differently categorised.

I don't know if you remember but the Muon version used to have many crashes and because the Muon version didn't have a restore tabs function, some of us were told that the tabs weren't lost, at least up until you open a fresh browser and that we could save lost tabs via the session-storage-1 files in the brave folder.

The big problem with the session-storage files were that it used to create multiple links of the same site and when you opened the file via notepad it wasn't sequenced.

Getting droves of users from other browsers, there has to be an ease in the migration process that is really good. Please fix this soon. It seems what everybody is hooked on is Rewards; it's understandable that you would be considering it's one of Brave's major USP. However, some of us would really like it now if some of the Muon features made it back again.

Thanks

**Comment by rebron** [comment]
Closing out. We're removing the importer for Muon and we would need a better formed description here as well.
