### ISSUE TITLE
Rewards NTP widget is not reflecting AC

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6740]
## Description 
Auto contribute amount is not being reflected on NTP widget.

## Steps to Reproduce
Unsure. @ryanml has a profile where issue is occurring, but QA should check the following scenarios:
1. profile where AC has already occurred for the month --> upgrade to version with NTP widget. Is AC reflected on NTP widget?
2. profile where AC has not yet occurred for the month --> upgrade to version with NTP widget. Have AC go thru. Is AC reflected on NTP widget?
3. Clean profile with NTP widget.  Have AC go thru. Is AC reflected on NTP widget?
4-6. Repeat above cases but with recurring monthly tips

## Actual result:
(image from @AndriusA )
![image (1)](https://user-images.githubusercontent.com/28145373/68091766-e045fd00-fe51-11e9-93f5-86ab56222b6a.png)

## Expected result:
NTP widget should reflect tips, monthly tips, and auto contributions.

## Reproduces how often: 
unsure

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @mandar-brave @brave/legacy_qa

**Comment by LaurenWags** [comment]
Looks like this might be localized to auto contribute only, monthly recurring tip was reflected on the widget:
<img width="876" alt="Screen Shot 2019-11-03 at 4 44 21 PM" src="https://user-images.githubusercontent.com/28145373/68092453-4f731f80-fe59-11e9-8c34-db66c3e0e3c3.png">

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows 10 x64 - 0.71.111 

![image](https://user-images.githubusercontent.com/38657976/68123428-e65fda80-ff32-11e9-80b8-6e445d300643.png)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.50 Chromium: 79.0.3945.56 (Official Build) nightly (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Ubuntu 18.04 LTS

Verified the test plan from the description.
Upgraded profile from 1.2.x:
![image](https://user-images.githubusercontent.com/34715963/70053286-5feff480-15d5-11ea-9b71-03664f3183ce.png)

Clean profile:
![image](https://user-images.githubusercontent.com/34715963/70052343-60878b80-15d3-11ea-8d17-7d04262bd0f7.png)
