### ISSUE TITLE
Thank you banner for monthly contribution

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#6744]
Follow up from https://github.com/brave/brave-browser/issues/6151

Currently we display this fo monthly contribution 

![](https://user-images.githubusercontent.com/8732757/67465805-bba08880-f5fa-11e9-8bc3-aecf801f276c.png)

We should display different text.

cc @alexwykoff @davidtemkin @jenn-rhim please provide resolution for it

**Comment by jenn-rhim** [comment]
the wording needs to reflect 'monthly contribution', which is scheduled for being sent on the same contribution date with the amount the user designated. See below.

![mc-confirmation](https://user-images.githubusercontent.com/4369856/68618936-44367a00-047f-11ea-8e98-c7eedb75a2ef.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.3.75 Chromium: 79.0.3945.88 (Official Build) dev (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Encountered https://github.com/brave/brave-browser/issues/7185
- Logged https://github.com/brave/brave-browser/issues/7526
- Verified the test plan from https://github.com/brave/brave-core/pull/3998
One-time tip
![image](https://user-images.githubusercontent.com/38657976/71509529-a7566180-28b1-11ea-8f4a-62359d1b48a1.png)
Monthly tip
![image](https://user-images.githubusercontent.com/38657976/71509554-c228d600-28b1-11ea-923e-11208c191fef.png)
