### ISSUE TITLE
fix background padding on top sites

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#6746]
## Description 
Background padding is too high when mousing over top sites widget caused by Brave Rewards widget being on.

## Steps to Reproduce
1. On New Tab page, mouseover top sites with Brave Rewards widget on.

## Actual result:
<img width="1309" alt="Screen Shot 2019-11-02 at 5 36 41 PM" src="https://user-images.githubusercontent.com/5951041/68110803-84f02b00-fea2-11e9-9f60-3e082abaf2f3.png">

## Expected result:
<img width="719" alt="Screen Shot 2019-11-02 at 5 36 25 PM" src="https://user-images.githubusercontent.com/5951041/68110778-7a359600-fea2-11e9-9c23-83d724310e1f.png">

## Brave version (brave://version info)
71.111
73.55

**Comment by rebron** [comment]
cc: @cezaraugusto

**Comment by kjozwiak** [comment]
Reproducible on `macOS 10.15.1` using the following build:

Brave | 0.73.55 Chromium: 78.0.3904.87 (Official Build) nightly (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | macOS Version 10.15.1 (Build 19B88)

Example:

<img width="663" alt="Screen Shot 2019-11-04 at 4 25 42 AM" src="https://user-images.githubusercontent.com/2602313/68113348-a44a8080-fec1-11e9-9c7c-dffbbc07c312.png">

**Comment by bsclifton** [comment]
Updated milestone to be 0.72 after https://github.com/brave/brave-core/pull/3938 was merged 👍

**Comment by bsclifton** [comment]
Added missing labels (so that this will be QA-ed/included in release notes)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.71.115 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified STR from description
* Verified when Rewards widget is on and off
<img width="1195" alt="Screen Shot 2019-11-12 at 9 51 57 AM" src="https://user-images.githubusercontent.com/28145373/68682135-a2706500-0532-11ea-974f-89e0a0a8561a.png">
<img width="1195" alt="Screen Shot 2019-11-12 at 9 52 16 AM" src="https://user-images.githubusercontent.com/28145373/68682163-a8fedc80-0532-11ea-8d2f-82f88453dcf4.png">

**Comment by LaurenWags** [comment]
Changing to `release-notes/exclude` as this was a regression introduced with the Rewards NTP widget which is new to 0.71.x, so this issue does not occur in 0.70.x.
