### ISSUE TITLE
Migrate widevine all prefs from profile to local_state

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#6747]
After widevine cdm is installed, any user(profile) can use cdm library.
so, it doesn't make sense to ask again whenever new profile is created.

Reproduce step:
1. Launch browser with clean profile
2. Install widevine cdm (via https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;panel=HOME;build=uncompiled)
3. Create new profile
4. Load again(https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;panel=HOME;build=uncompiled)
5. Check widevine prompt is displayed again

Result: prompt is displayed again. (Regardless of allow/deny, user can play contents)
Expected: prompt should not be displayed.

**Comment by simonhong** [comment]
`kAskWidevineInstall` should be managed with same manner.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.85 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Ubuntu 18.04 LTS

Verified test plan from the description. The widevine prompt is not shown again.
