### ISSUE TITLE
Ad notifications do not close when clicking the close or view buttons or after the notification times out

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#6748]
## Description 

Clicking close or view buttons on ad notifications does not close the notification or view an ad

## Steps to Reproduce

a.
   1. View an ad
   2. Click the Close button

b.
   1. View an ad
   2. Click the View button

c.
  1. View an ad
  2. Wait for ad notifcation to timeout

## Actual result:

Clicking the Close button does not close the notification
Clicking the View button does not close the notification
The notification does not timeout after 2 minutes

## Expected result:
Clicking the Close button should close the notification
Clicking the View button should close the notification
The notification should timeout after 2 minutes

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

0.72 and 0.73

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Regression occurred with https://github.com/brave/brave-core/pull/3499/files

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.72.124 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from description
* Verified able to view ads by clicking on the ad notification text as well, not just the 'View' button.
* Verified view, dismiss, click, landed events in `confirmations.json` file corresponding to the action taken.
* Verified with staging env.
