### ISSUE TITLE
Toggle Brave rewards shows `Turn On Brave Ads` in the Rewards widget even though Ads are in ON state

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#6749]
## Description 

Toggle Brave rewards shows `Turn On Brave Ads` in the Rewards widget even though Ads are in ON state

## Steps to Reproduce

   1. Clean profile 0.71.111
   2. Open an NTP and turn on rewards through Rewards widget
   3. Click on BAT logo and open Brave://rewards page
   4. Turn OFF the Brave Rewards in brave://rewards and quit the browser
   5. Relaunch the browser
   6. Enable rewards from the `Welcome Back!` panel
   7. Make sure rewards is enabled along with Ads in brave://rewards page
   8. Click on NTP which was opened in step 2, NTP shows `Turn On Brave Ads` in the Rewards widget

## Actual result:

Already opened NTP shows `Turn On Brave Ads` in the Rewards widget

## Expected result:
Already opened NTP should not show `Turn On Brave Ads` in the Rewards widget

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 0.71.111 Chromium: 78.0.3904.87 (Official Build) (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @ryanml @NejcZdovc

**Comment by LaurenWags** [comment]
@GeetaSarvadnya if you open a different new tab, is the widget correct?

**Comment by GeetaSarvadnya** [comment]
@LaurenWags Yup, open different new tabs are showing the expected result (NOT showing the `Turn On Brave Ads` option in rewards widget)

**Comment by LaurenWags** [comment]
hm, could be happening because the widget isn't updated instantaneously. will let @ryanml chime in :)

**Comment by tmancey** [comment]
@petemill @ryanml

**Comment by tmancey** [comment]
@kjozwiak @LaurenWags Could we please retest as I cannot reproduce on latest builds, thanks
