### ISSUE TITLE
Combine Ledger and Ads into a single utility process

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#6752]
Combine Ledger and Ads into a single utility process

![image](https://user-images.githubusercontent.com/1188719/68126807-822a2000-ff0c-11e9-876f-d7c7fb0a695d.png)

**Comment by NejcZdovc** [comment]
we should not do that as ledger process need to run with rewards everywhere all the time, while ads can be lazy loaded later on

**Comment by tmancey** [comment]
Closing issue based upon https://github.com/brave/brave-browser/issues/6752#issuecomment-613285525 cc @bridiver

**Comment by bridiver** [comment]
> we should not do that as ledger process need to run with rewards everywhere all the time, while ads can be lazy loaded later on

That rationale makes no sense to me, why would we lazy load a process we don't need to load at all? I'm reopening this.
