### ISSUE TITLE
unable to claim grant from NTP widget

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6754]
## Description 
Clicking on `Claim my Rewards` from NTP widget does not open the panel to show captcha for claim. 

Note - this only happens on 0.71.111, this does not reproduce on Nightly 0.73.55.

## Steps to Reproduce

   1. Clean profile (staging)
   2. Open new tab page.
   3. Join Rewards from widget.
   4. Refresh page or open another new tab.
   5. Click on `Claim my Rewards` on widget.

## Actual result:
message closes, but then panel does not pop open with captcha

![071111](https://user-images.githubusercontent.com/28145373/68131091-70378580-feea-11e9-9f4e-2b22e4f28c9e.gif)

## Expected result:
message should close andpanel should open and show captcha to solve
![07355](https://user-images.githubusercontent.com/28145373/68131082-6ca3fe80-feea-11e9-8fae-8cf45536c67a.gif)

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 0.71.111 Chromium: 78.0.3904.87 (Official Build) (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a for 0.70.x, but yes for 0.71.111 preview
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the dev channel? n/a
- Can you reproduce this issue with the nightly channel? no 0.73.55

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @mandar-brave @rebron @ryanml @brave/legacy_qa

**Comment by bsclifton** [comment]
We missed an uplift! Fixed when https://github.com/brave/brave-core/pull/3872 was merged 😄

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.71.113 Chromium: 78.0.3904.87 (Official Build) (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
![Claim grants from NTP_0 71 113](https://user-images.githubusercontent.com/38657976/68540649-8dbd9100-03bb-11ea-9c0d-2779ae956212.gif)
