### ISSUE TITLE
Old icons are used in Disabled Rewards Settings

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6756]
Follow up from https://github.com/brave/brave-browser/issues/6511. The fix was for new icons. Old icons looks too small with the fix per https://github.com/brave/brave-browser/issues/6511#issuecomment-549351306. We need new icons.

## Steps to Reproduce

   1. Clean profile
   2. Open `brave://rewards`
   3. Join the rewards

## Actual result:

Icons are old and are too small
![image](https://user-images.githubusercontent.com/34715963/68123881-5b6ce900-ff0e-11e9-92e6-95a6f6658861.png)
![image](https://user-images.githubusercontent.com/34715963/68123900-66277e00-ff0e-11e9-8261-097881e691e1.png)

## Expected result:
![image](https://user-images.githubusercontent.com/34715963/68124050-b6064500-ff0e-11e9-8515-1a3ff9d06372.png)
![image](https://user-images.githubusercontent.com/34715963/68124078-be5e8000-ff0e-11e9-8a73-6ad2b501f526.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.71.111 Chromium: 78.0.3904.87 (Official Build) (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Ubuntu 18.04 LTS

Not reproducible in 0.72.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? no
- Can you reproduce this issue with the nightly channel? no

cc @ryanml @rebron @brave/legacy_qa

**Comment by ryanml** [comment]
Closed via: https://github.com/brave/brave-core/pull/3873

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` until build 0.71.113 or above.

**Comment by LaurenWags** [comment]
on hold pending investigation by @ryanml as to why this isn't showing in 0.71.x

**Comment by LaurenWags** [comment]
Moving milestone per discussion with @rebron @ryanml

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.72.124 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified STR from the description
- Verified on both clean and upgraded profile

Rewards ON:
![image](https://user-images.githubusercontent.com/38657976/68854698-9c30e300-0702-11ea-9801-aaf98bbd2589.png)
![image](https://user-images.githubusercontent.com/38657976/68854723-ab179580-0702-11ea-8717-1b656fc8cf29.png)
