### ISSUE TITLE
Ads History should be displayed in reverse chronological order

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#6757]
## Description 
Currently Ads History is shown with older entries toward the top.  It should be instead organized with the most recent dates first.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.4.85 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.14.6 (Build 18G103)

Reproduced on 1.3.115:
<img width="953" alt="Screen Shot 2020-02-12 at 4 47 18 PM" src="https://user-images.githubusercontent.com/28145373/74380586-de2bfc80-4db7-11ea-8bed-9096ed23438f.png">

Confirmed changed with 1.4.85:
<img width="958" alt="Screen Shot 2020-02-12 at 4 37 59 PM" src="https://user-images.githubusercontent.com/28145373/74380601-e4ba7400-4db7-11ea-8d42-0cb61df47e0c.png">
