### ISSUE TITLE
Some functions not works in some websites

### ISSUE THREAD

**Issue by iowbeoibewio** [brave/brave-browser#6758]
## Steps to Reproduce
   1. check this video https://streamable.com/uanqk
   2. try to up/down/mute volume (won't work)
   3. try to jump to other seconds/minutes on timeline (won't work)

## Actual result:
- up/down/mute volume not work's
- jumping to other seconds/minutes on timeline not work's

## Expected result:
All functions in website must works

## Reproduces how often: 
Always happens

## Brave version (brave://version info)
**Brave** 0.71.111 Chromium: 78.0.3904.87 (Official Build) (64-bit)
**OS** Windows 10 Version 1809

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No, website in Chrome works 100%

**Comment by bsclifton** [comment]
Thanks for the report, @iowbeoibewio! Can you please try going to brave://flags/#hardware-media-key-handling and enabling?

We tried the stream above and manual (ex: using mouse) adjustment (volume, position, etc) works fine 😄

**Comment by bsclifton** [comment]
Going to close as recommendation was given. We can re-open issue if the above does not help

**Comment by salehif** [comment]
Hi, using latest Brave 1.8.90 on Windows 10 version 1809 64-bit

it's works ONLY using keyboard
The problem still exists, I tried as bsclifton wrote with restarting browser, but no changes, FYI problem is on Brave only.

and I want to mention, most of problem is fixed in latest version of Brave with new features, really impressed by brave team work 👍 💯

thank you

**Comment by salehif** [comment]
@bsclifton Final update
streamable.com works fine now for me with and w/o Brave Shield on Brave 1.8.96

I checked 1.8.95 and 1.8.96 change log and nothing related to this issue.

thank you to everyone
