### ISSUE TITLE
NTP Widget should indicate when Ads are not supported in the users region

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#6759]
Design:
<img width="621" alt="Screen Shot 2019-11-04 at 7 29 51 PM" src="https://user-images.githubusercontent.com/8732757/68173837-7e60c280-ff39-11e9-9a6e-1fcae0d7b081.png">

Test plan:
1. Start Browser
2. Enable Rewards
3. Ensure that toggling Ads on and off shows no regressions in behavior for the NTP widget
4. Close browser
5. Open Preferences file and search for countryid_at_install
6. Replace value with a country id where ads are not supported
7. Restart Browser
8. Confirm that the NTP widget shows the unsupported messaging

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.74.11 Chromium: 78.0.3904.87 (Official Build) nightly (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan mentioned in the description
- Verified `Sorry, ads not supported` message displayed in NTP widget for ads not supported country `Bulgaria` in a clean profile
![image](https://user-images.githubusercontent.com/38657976/68490383-dd427680-026e-11ea-91c7-8a4b1c2b00b4.png)
- Verified `Sorry, ads not supported` message displayed in NTP widget for ads not supported country `Bulgaria` in an upgraded profile

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)


* Verified NTP widget shows `Sorry!...` message on clean install of non-ads region (Bulgaria). Verified `Tips and contributions...` increments as expected.
* Verified NTP widget shows `Sorry!...` message on upgraded profile (from 0.70.123) for non-ads region (Bulgaria). Verified `Tips and contributions...` showed as expected on upgrade. Verified it also incremented after use on upgrade as well.
* Verified that turning off rewards and exiting Brave, the enable rewards message is shown in NTP. Clicking on it enables the rewards and ads not supported message is displayed as expected in NTP widget as well as in Ads panel.

<img width="317" alt="Screen Shot 2019-11-11 at 10 29 33" src="https://user-images.githubusercontent.com/28145373/68600958-64f7d300-0471-11ea-821c-6026970bd64c.png">
<img width="637" alt="Screen Shot 2019-11-11 at 10 29 46" src="https://user-images.githubusercontent.com/28145373/68600960-675a2d00-0471-11ea-9b8e-9351fa2805e3.png">
<img width="316" alt="Screen Shot 2019-11-11 at 10 31 25" src="https://user-images.githubusercontent.com/28145373/68600967-6923f080-0471-11ea-8a08-e155265932b2.png">
