### ISSUE TITLE
Missing translation for Rewards widget

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#6760]
## Description 

Missing translation for Rewards widget

## Steps to Reproduce

   1. Set device locale to Germany/France/Australia/Japan
   2. Clean profile 0.71.111
   3. Enable rewards
   4. Open a NTP

## Actual result:

Missing translation for Rewards widget

![image](https://user-images.githubusercontent.com/38657976/68156183-52f9ca00-ff71-11e9-8ed9-cde0c194734f.png)

![image](https://user-images.githubusercontent.com/38657976/68155774-622c4800-ff70-11e9-8926-d7b7a994bb52.png)

## Expected result:
 Rewards widget should be translated 

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.71.111 Chromium: 78.0.3904.87 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
Betriebssystem | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @ryanml @rebron @NejcZdovc @mandar-brave

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya this is expected as we didn't order new translations yet

**Comment by rebron** [comment]
@GeetaSarvadnya Is this looking ok now with 1.1?

**Comment by LaurenWags** [comment]
Looks good with 1.1.20:

Brave | 1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)
-- | --
Revision | 99b6d241cf84f7fa7434ae8a59f9e74eb1464280-refs/branch-heads/3945@{#888}
OS | macOS Version 10.13.6 (Build 17G5019)

German:
<img width="400" alt="Rewards NTP Widget - German" src="https://user-images.githubusercontent.com/28145373/70575093-afa16380-1b73-11ea-8f02-a3562aaaf667.png">

French:
<img width="376" alt="French" src="https://user-images.githubusercontent.com/28145373/70575096-b334ea80-1b73-11ea-9539-48635cee2afc.png">

Australian English:
<img width="287" alt="English-Australian" src="https://user-images.githubusercontent.com/28145373/70575099-b5974480-1b73-11ea-8077-3d94d44295fc.png">

Japanese:
<img width="258" alt="Japanese" src="https://user-images.githubusercontent.com/28145373/70575103-b7f99e80-1b73-11ea-9b59-5557cebf855e.png">
