### ISSUE TITLE
twitter tip button doesn't show on selected tweet when viewing thread

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6762]
## Description
When you click on a tweet to view it/the associated thread, the selected tweet does not have the Tip button, but other tweets in the thread do.

Note - this works with the old twitter layout (when you're not logged in) but does not work with the newer twitter layout. 

## Steps to Reproduce

   1. Clean profile
   2. Enable Rewards
   3. Navigate to twitter.com and login (logging in is important so you get the new layout)
   4. Navigate to twitter.com/brave - note tweets have the Tip button. 
   5. Click on a tweet 
   6. Note tweet does not contain the tip button, but replies/tweets in the thread do.
   7. Click on one of the replies
   8. Note now this tweet does not contain the tip button, but other tweets in the thread do.

## Actual result:
Step 6:
<img width="629" alt="Screen Shot 2019-11-04 at 3 17 51 PM" src="https://user-images.githubusercontent.com/28145373/68155932-bacff680-ff18-11e9-9909-9112e7ff77f1.png">

Step 8:
<img width="623" alt="Screen Shot 2019-11-04 at 3 35 55 PM" src="https://user-images.githubusercontent.com/28145373/68156006-e05d0000-ff18-11e9-9376-c93dc21e3233.png">

## Expected result:
All tweets would have the tip button.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.71.111 Chromium: 78.0.3904.87 (Official Build) (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
This is an existing issue in release version.
@kjozwiak also encountered this while testing

**Comment by NejcZdovc** [comment]
@LaurenWags is this still a problem on the latest nightly?

**Comment by LaurenWags** [comment]
yes, reproduces with 

Brave | 1.9.15 Chromium: 81.0.4044.92 (Official Build) nightly (64-bit)
-- | --
Revision | 32921c79b6f01a0fb2deef0e1d45b42f96581051-refs/branch-heads/4044@{#883}
OS | macOS Version 10.14.6 (Build 18G3020)

**Comment by emerick** [comment]
It appears that this no longer works:

```
let tweets = document.querySelectorAll('[data-testid="tweet"], [data-testid="tweetDetail"]')
```

It used to find tweets in the regular stream (`data-testid="tweet"`) and tweets in the detail view (`data-testid="tweetDetail"`). We would need to adjust the Twitter content script to account for the new HTML, possibly using the `article` role.

**Comment by jonathansampson** [comment]
Recently received a +1 on Twitter regarding this: https://twitter.com/brianoflondon/status/1261577925943611392

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.45 Chromium: 86.0.4240.99 (Official Build) dev (x86_64)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Verified STR from description. Confirmed main tweet shows Tip button.

<img width="802" alt="Screen Shot 2020-10-21 at 2 20 50 PM" src="https://user-images.githubusercontent.com/28145373/96766188-b4948d80-13a8-11eb-9a01-6bc526582cc4.png">

Confirmed clicking on this button shows the appropriate twitter publisher and selected tweet on the tip banner:
<img width="1195" alt="Screen Shot 2020-10-21 at 2 21 57 PM" src="https://user-images.githubusercontent.com/28145373/96766292-d857d380-13a8-11eb-8cc1-67fd7ec23aad.png">

-----------
