### ISSUE TITLE
Rewards service should be disabled when switching off Rewards

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#6765]
## Description 

Rewards service should be disabled when switching off Rewards

## Steps to Reproduce

   1. Enable Rewards
   2. Disable Rewards

## Actual result:

Rewards service continues to run (see console logs)

## Expected result:
Rewards service should stop running

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Should work like ads service where the service starts/stops

**Comment by NejcZdovc** [comment]
closing as we will not have disable button anymore with https://github.com/brave/brave-browser/issues/9130
