### ISSUE TITLE
"Close" is translated as "Близко" which is Russian word for "Nearby/Near"

### ISSUE THREAD

**Issue by ilyaigpetrov** [brave/brave-browser#6767]
## Description 

In the right click menu of a tab "Close" command is translated as "Близко" (Nearby).

## Steps to Reproduce

   1. Install Brave on Russian Linux distro or use other ways to launch Brave in Russian.
   2. Open new tab.
   3. Right-click on tab to open its menu.
   4. See "Близко (Ctrl + W)" (wrong translation) instead of "Закрыть (Ctrl + W)" (right translation) for the "Close" menu item.

## Actual result:

I see "Близко (Ctrl + W)".
![brave-blizko](https://user-images.githubusercontent.com/1090811/68199900-ca9e1800-ffb6-11e9-9998-24a280e94295.png)

## Expected result:
I should see "Закрыть (Ctrl + W)".

## Brave version (brave://version info)

```
Brave | 0.73.51 Chromium: 78.0.3904.87 (Официальная сборка) nightly (64 бит)  
Версия | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}  
ОС | Linux  
JavaScript | V8 7.8.279.19
```
## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by nicodimuscanis** [comment]
Here is the place in the code
https://github.com/brave/brave-core/blob/1dc6576421d1021cad6aa11d5628c64f365ac176/components/resources/strings/brave_components_resources_ru.xtb#L9

**Comment by bsclifton** [comment]
Translations can be updated in our Transifex interface:
https://www.transifex.com/brave/brave/

@mkarolin could you manually updated this one? 😄

**Comment by mkarolin** [comment]
Updated. Will keep this open until the localization is pulled in.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/brave-core/pull/3922

**Comment by LaurenWags** [comment]
`QA/Blocked` until 0.71.114 or above

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.71.114 Chromium: 78.0.3904.97 (Официальная сборка) (64 бит)
-- | --
Версия | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
ОС | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/68563880-07fe1c00-0475-11ea-97cd-46f634e3eb7a.png)
