### ISSUE TITLE
[Linux] - Brave crashes on open

### ISSUE THREAD

**Issue by Davincible** [brave/brave-browser#6769]
Brave just crashes after being opened for 5 seconds on Pop OS (Ubuntu) 19.10. 
Brave version: not sure, can't check in the browser, but everything is up to date.

Following error: `/usr/bin/brave-browser: line 48: 11057 Segmentation fault      (core dumped) "$HERE/brave" "$@"`

**Comment by Davincible** [comment]
Turns out it was due to a Aliexpress tab, when I closed a couple Ali tabs the browser started working again... very strange

**Comment by bsclifton** [comment]
@Davincible just to recap, you got this when having a few tabs for https://www.aliexpress.com/ open?

What version of Brave are you running?

**Comment by rebron** [comment]
Closing. @Davincible Please reopen if you're still experiencing crash issues.

**Comment by AMHOL** [comment]
I get a similar error on Ubuntu 19.10:

```sh
➜  ~ /usr/bin/brave-browser-stable https://google.com
[21706:21706:0210/211750.280204:ERROR:vaapi_wrapper.cc(417)] vaInitialize failed: unknown libva error
/usr/bin/brave-browser-stable: line 48: 21678 Segmentation fault      (core dumped) "$HERE/brave" "$@"
```

**Comment by kapindra** [comment]
I got this error:

**Comment by bsclifton** [comment]
@AMHOL @kapindra can you please follow https://github.com/brave/brave-browser/issues/10331? I think that's the issue you're experiencing
