### ISSUE TITLE
CW buttons should use Brave brand style

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6770]
## Description 
Similar to #6398

Crypto Wallet buttons should use Brave brand styling.

## Steps to Reproduce

   1. Navigate to Crypto Wallets
   2. Enable and confirm buttons use Brave brand style

## Actual result:
Crypto wallet buttons do not use Brave brand style (some screenshots of all buttons can be seen here: https://github.com/brave/brave-browser/issues/6398#issuecomment-548767502 )

## Expected result:
Crypto wallet buttons should use Brave brand style

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.71.111 Chromium: 78.0.3904.87 (Official Build) (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bbondy** [comment]
This won't be worked on since we are deprecating the extension in favor of the new Brave Wallet. Closing.
