### ISSUE TITLE
Ads Settings should display BAT with 1 decimal place

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#6774]
Test plan:
1. Enable Rewards
2. Navigate to brave://rewards

**Expected**:
Estimated pending rewards displays as `0.0 BAT`

**Actual**: 
<img width="649" alt="Screen Shot 2019-11-05 at 2 51 18 PM" src="https://user-images.githubusercontent.com/8732757/68249315-d05a2480-ffdb-11e9-82c1-0e216653f327.png">

**Comment by LaurenWags** [comment]
@ryanml @NejcZdovc I'm not finding this in 1.2.x but it is merged into master (1.3.x) per https://github.com/brave/brave-core/commits/master?after=0342c2949a9ea06ff3ea146ba0c51665549c91e1+279. Can the milestone be adjusted to reflect 1.3.x or are you going to be requesting uplift to 1.2.x?

**Comment by btlechowski** [comment]
Any updates on the concerns raised by @LaurenWags ?

**Comment by NejcZdovc** [comment]
@LaurenWags yup this was marked wrongly, changed to 1.3

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.81 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Ubuntu 18.04 LTS

Verified test plan from the description. Also verified other instances of BAT values and made sure they all have 1 decimal place

![image](https://user-images.githubusercontent.com/34715963/71763378-9cb45180-2edb-11ea-8780-fa5cab4880b5.png)
