### ISSUE TITLE
react-chrome-redux is deprecated

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#6777]
According to https://www.npmjs.com/package/react-chrome-redux:

![Screenshot from 2019-11-05 17-06-31](https://user-images.githubusercontent.com/167821/68259417-aa8a4b00-ffee-11e9-8235-e2355092038b.png)

we should now be using https://www.npmjs.com/package/webext-redux.

**Comment by bsclifton** [comment]
cc: @cezaraugusto
