### ISSUE TITLE
Support searching for multiple words on all engines

### ISSUE THREAD

**Issue by Therealskythe** [brave/brave-browser#6779]
## Description 
When searching for multiple words in a custom search engine, Brave (or the target website?) will sometimes concatenate those words in the URL in a way that doesn't lead to the desired outcome (a search for those words).

## Steps to Reproduce

   1. Add Rotten Tomatoes to your custom search engines (https://www.rottentomatoes.com/search/?search=%s)
   2. Search for "true detective"

## Actual result:
Brave goes to https://www.rottentomatoes.com/search/?search=true+detective and says:

> Sorry, no results found for "true+detective"

## Expected result:
Brave should go to https://www.rottentomatoes.com/search/?search=true%20detective and find 1 result.

## Brave version (brave://version info)
Brave | 0.70.122 Chromium: 78.0.3904.87 (Official Build) (64-bit)
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Windows 10 OS Version 1809 (Build 17763.805)

## Other Additional Information:
You can search for "star wars" or "star trek" or any other multi word search phrase, too, of course. The results will always be different because "aaa+bbb" is not the same as "aaa bbb".

## Miscellaneous Information:
I'm not saying it's a bug with Brave. It's probably got to do with the way Rotten Tomatoes handles those requests. Metacritic (https://www.metacritic.com/search/all/%s/results) for example does _not_ have this problem.

Maybe there is a fix for this I'm not aware of? Otherwise it would be nice if we could get a way to control how those URLs are built (with Opera you could choose between GET and POST requests for example).

**Comment by rebron** [comment]
@Therealskythe Can you report to Rotten Tomatoes? This also happens in other browsers and the fix will need to come from the Rotten Tomatoes side.
