### ISSUE TITLE
Have ledger library use production's publisher channel list for staging environments for testing

### ISSUE THREAD

**Issue by yachtcaptain23** [brave/brave-browser#6784]
## Description 
I spoke with @kylehickinson who suggested we'd allow for 1:1 comparison of the publishers channel by pointing to
https://publishers-distro.basicattentiontoken.org/api/v3/public/channels

**Comment by kylehickinson** [comment]
@NejcZdovc Fine with just setting the `BuildUrl` method to return production URL for staging for the pub list?

**Comment by NejcZdovc** [comment]
why would we like to do this? We have wallets created on staging and then we have publisher list that also points to staging. If we have production list which has production wallets and we are sending money from staging to production we will have a lot of problems. Also while developing I don't want to download the whole thing every time.

**Comment by kylehickinson** [comment]
@NejcZdovc When it was brought up, I believe it was because QA/Product wants staging to be a mirror of production, therefore expect it to have the same publisher lists so they can conduct all the same tests & flows as they would on production.  Basically that we should use dev instead for when we want a small list :)

**Comment by NejcZdovc** [comment]
not see how this is possible, because then we need production wallets as well

**Comment by kylehickinson** [comment]
This might be hard stopper then. @yachtcaptain23 I assume it's not possible to setup staging wallets for all prod publishers (or at least worth doing)? Perhaps we should ask QA to list out which publishers they want in staging and we can simply add them

**Comment by NejcZdovc** [comment]
@kylehickinson what is the use case/request for this change? I don't understand where this is coming from based on the fact that it was working ok for the last year 😃

**Comment by yachtcaptain23** [comment]
@kylehickinson would it be better to create an easter egg if QA wanted to benchmark against prod's publishers list? Otherwise I agree with @NejcZdovc, and we can just close this issue.

**Comment by kylehickinson** [comment]
👆 @srirambv

**Comment by srirambv** [comment]
My understanding is even if you try to send tips/ac from staging wallet to prod publishers it would fail. So there wont be an issue having the same list on both staging and prod. But it would be good to a little more publishers added to staging so that its easy for qa during testing.

**Comment by NejcZdovc** [comment]
> So there wont be an issue having the same list on both staging and prod.
It would be a problem as staging wouldn't be useful as you can't do contribution at all

**Comment by NejcZdovc** [comment]
I would say best approach for staging and dev is to just add more publishers in

**Comment by srirambv** [comment]
> I would say best approach for staging and dev is to just add more publishers in 

Sounds good to me. Adding a few more publishers would help

**Comment by yachtcaptain23** [comment]
Seems like this is resolved. Closing.
