### ISSUE TITLE
Mouse Back / Forward buttons do not work in Brave

### ISSUE THREAD

**Issue by holaymolay** [brave/brave-browser#6785]
I have a logitech M705 mouse. It has back/forward buttons on the side. In Chrome, they navigate forward and backward in history with no issues. In Brave, they don't work at all.

I see that this issue has been brought up before, but in a now archived repo:
[Go back/forward in browser history with mouse buttons #3101](https://github.com/brave/browser-laptop/issues/3101)

Disabling the Brave shield has no effect on the functionality (or lack thereof) of this feature.

```
Version 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
MacOS Catalina 10.15.1 (19B88)
```

**Comment by bsclifton** [comment]
@holaymolay I believe you need to check for updates 😄 This should have been fixed in the recent Chromium 78 upgrade (latest version of Brave should be 0.70.122)

You can update via the `Brave` menu => `About Brave` (give it a min and it'll find an update 😄)

Please let us know if this works!

**Comment by holaymolay** [comment]
@bsclifton Yep that did it. I had actually downloaded and installed the update, but I didn't realize that I needed to click the "relaunch" button for the update to take effect. Interestingly, I had restarted my computer multiple times since I clicked the update button via the "customize and control" hamburger button, but it never occurred to me that I had to take one more step before the changes took effect.

Thanks for your quick response.

**Comment by bsclifton** [comment]
@holaymolay my pleasure! 😄 Thanks for updating so that others with the same problem know what the solution was 😄

**Comment by SwaySway** [comment]
Is anyone else still running into this issue? Occasionally it stops working for me and I have to create a new window to get it working again.

**Comment by cusxio** [comment]
@SwaySway yup, it seems like an issue that happens intermittently.
