### ISSUE TITLE
Add Reader view for pages

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#679]
Carried over from https://github.com/brave/browser-laptop/issues/517

This could be implemented as an extension (as some have suggested):
> @thechild 
> One other option would be to just include this chrome extension (https://mercury.postlight.com/reader/) to get a great reader view.

Some browsers have this built-in

**Comment by Jacalz** [comment]
I would prefer to see this built in instead of as an extension. There isn’t any good open source reader extension and I really like Mozilla’s readability. Having it built in is the way to go in my opinion...

**Comment by wayfarer-jr** [comment]
I had just assumed a reader view would already be built-in, as it's such a standard thing these days and it's already built into the mobile version. Especially as someone with relatively poor vision, it would be of great benefit. Beggars can't be choosers and all that, but I would really appreciate the inclusion in future updates.

**Comment by wkuckro** [comment]
+1 for built-in to control the experience and limit extension overload

**Comment by HeraKumi** [comment]
+1 on this feature to be implement or moved up on the priority list

**Comment by monte-hayward** [comment]
The feature is built into Chromium via `dom-distiller`.

It shows up in `brave-core`. Could it be exposed as a convenient toolbar or address bar option?
https://github.com/brave/brave-core/search?q=distill&unscoped_q=distill

For now, it can be enabled manually, and then is under the hamburger menu:
https://gist.github.com/monte-hayward/ca63e053664436c587e9882881e326b3

**Comment by DTrejo** [comment]
Another option for using dom distiller: chrome://dom-distiller/ aka brave://dom-distiller: copy url; click bookmarklet, paste, read

**Comment by drunkenblueberry** [comment]
Hi, I'm new to Brave and Github, and I want to say I love Brave after just 2 days of using it (coming from Chrome). I want to bump this feature request because I've found the dom-distiller doesn't always work.  It doesn't really work on Tor windows, and I feel like Readability is much more customizable. Thanks

**Comment by tycho01** [comment]
`dom-distiller` can be enabled from `chrome://flags`.

**Comment by rebron** [comment]
Closing, fixed with https://github.com/brave/brave-variations/pull/264 on May 17, 2022
`https://support.brave.com/hc/en-us/articles/360045031392-What-is-SpeedReader`
