### ISSUE TITLE
How to restore extensions from a clone to a rebuilt macOS machine?

### ISSUE THREAD

**Issue by jtheletter** [brave/brave-browser#6791]
I have a clone on an external drive of my primary machine, presently in for repairs. I copied all user library files from the clone to my rebuild. Upon launching Brave, I get a prompt reading…

    Some settings were reset
    Brave detected that some of your settings were corrupted by another program and reset them to their original defaults. Learn more

…And all items disappear from `~/Library/Application Support/BraveSoftware/Brave-Browser/Default/Extensions`. 

I see my name and icon under menubar "Profiles". I see my old/primary device under `brave://sync/` (and it's described as "this device"). 

How do I restore my extensions? How even do I find at least a text or GUI list of my extensions to reinstall manually? 

* Version 0.70.122 Chromium: 78.0.3904.87 (Official Build) (64-bit)
* macOS Catalina 10.15.1 (19B88)

**Comment by luckman212** [comment]
Did you figure this out @jtheletter ?
I was trying to set up Brave on a 2nd Mac after having everything configured "just right" on the 1st one. I figured I could use a similar technique (copy App Support profile) but since it doesn't seem to work, I am hoping for a better way...

**Comment by jtheletter** [comment]
I didn't find a solution, and now, eleven days later, I have my primary machine back from hardware repairs, with its data thankfully fully intact. 

I would still consider the need to export/import or sync of browser extensions to be a critical issue for any web browser. Apple's Migration Assistant and Time Machine are too limited in my experience, so I always end up rebuilding my machines from clones.

**Comment by bsclifton** [comment]
Good question, @jtheletter - the extensions themselves can be seen at brave://extensions

But if your profile gets corrupted, they may not be shown there. Glad you got your situation sorted, but you bring about a good point with the extension sync.  Let me see if we have an issue tracking that

**Comment by bsclifton** [comment]
@jtheletter we have an issue here, if you want to give it a +1 - this is for enabling extension sync for Brave: https://github.com/brave/brave-browser/issues/4094

**Comment by bsclifton** [comment]
OK I believe I found where you can see the extensions... this would be in the Profile directory for your platform (ex: `%USERPROFILE%\AppData\Local\BraveSoftware\Brave-Browser\User Data\` or `~/Library/Application Support/BraveSoftware/Brave-Browser/Default/`)

In there, you can see the `Preferences` file, which is a JSON blob. Under `extensions`, there should be a section `install_signature` which will then list the ID for the extensions (which is a long blob of text like `aomjjhallfgjeglblehebfpbcfeobpgk`)

You can then do a search for that ID on the Chrome Web Store and re-add the extension:
https://chrome.google.com/webstore/search/

**Comment by jtheletter** [comment]
Thanks for you reply. 

Nothing showed in `chrome://extensions/` on my new machine after copying my user library files from clone to rebuild. 

The `Preferences` file (726,944 minified characters) indeed has the IDs you specify, and those IDs do result in extension names when searching the Chrome Store, thank you for that. 

I've upvoted the linked ticket. Cheers.

**Comment by nhuesmann** [comment]
@bsclifton I just wanted to thank you, your solution helped me get my extensions back after a Time Machine restore did not recover them automatically. Found the JSON file in the stated location in the backup and looked up each id in the Chrome extensions store. Thanks!

**Comment by bsclifton** [comment]
Super glad to hear, @nhuesmann 😄 Thanks for confirming this worked great. Hope the rest of the Time Machine restore went OK 😄

**Comment by voska** [comment]
I had this issue recently too. I was migrating from one mac to another using the Migration Assistant. All of my other apps migrated properly, but Brave migrated without its extensions and I don't know why. 

I had to migrate to another machine about a week later and had the same issue. It was really annoying.

**Comment by raine** [comment]
A one liner for opening previously installed extension in Chrome Web Store, so that one can easily add them to Brave.

```sh
cat "$HOME/Library/Application Support/BraveSoftware/Brave-Browser/Default/Preferences" \
  | jq -r '.extensions.toolbar[]' \
  | xargs -L1 -I{} open -a Brave\ Browser 'https://chrome.google.com/webstore/detail/{}'
```

Needs `jq`.

**Comment by NoX1De** [comment]
> A one liner for opening previously installed extensions in Chrome Web Store, so that one can easily add them to Brave.
> 
> ```shell
> cat "$HOME/Library/Application Support/BraveSoftware/Brave-Browser/Default/Preferences" \
>   | jq -r '.extensions.toolbar[]' \
>   | xargs -L1 -I{} open -a Brave\ Browser 'https://chrome.google.com/webstore/detail/{}'
> ```
> 
> Needs `jq`.

The above returns this for me:

`jq: error (at <stdin>:0): Cannot iterate over null (null)`

This no longer works with newer versions of Brave it seems...I got the command to run using the following (below) but it's still broken and I haven't the time to mess with this.  

**Brave is TOO HELPFUL in a very annoying and time wasting fashion, when someone migrates from one Mac to another using Migration Assistant Brave thinks it's doing someone a favor by removing/resetting all or some of the Brave settings and removes all of your extensions.  This is ridiculous default behavior and should NOT be happening without at least asking the user if they wish to proceed with reseting anything and killing previously installed extensions.**

`cat "$HOME/Library/Application Support/BraveSoftware/Brave-Browser/Default/Preferences" \
  | jq -r '.extensions.toolbar // []' \
  | xargs -L1 -I{} open -a Brave\ Browser 'https://chrome.google.com/webstore/detail/{}'`
  
  @bsclifton

**Comment by wqh0109663** [comment]
> Thanks for your reply.
> 
> Nothing showed in `chrome://extensions/` on my new machine after copying my user library files from clone to rebuild.
> 
> The `Preferences` file (726,944 minified characters) indeed has the IDs you specify, and those IDs do result in extension names when searching the Chrome Store, thank you for that.
> 
> I've upvoted the linked ticket. Cheers.

yes it works
