### ISSUE TITLE
Global Shields toggle for cookies does not work

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#6804]
## Steps to Reproduce
   1. Toggle global shield settings to block all cookies
   2. Navigate to https://www.whatismybrowser.com/detect/are-third-party-cookies-enabled
   3. You should see `No`
   4. Re-toggle the global shield settings to block-only-cross-site setting
   5. Navigate to https://www.whatismybrowser.com/detect/are-third-party-cookies-enabled

## Actual result:
Third party cookies are not blocked

## Expected result:
Third party cookies should be blocked

## Reproduces how often: 
Easily

## Brave version (brave://version info)
0.73.60 Chromium: 78.0.3904.87 (Official Build) nightly (64-bit) - Nightly
0.70.122 Chromium: 78.0.3904.87 (Official Build) (64-bit) - Release

**Comment by bridiver** [comment]
I can't replicate this in 0.70.122

**Comment by jumde** [comment]
Transition from `Block all` -> `Block 3rd parties` does not work

**Comment by bridiver** [comment]
I was able to replicate that specific transition so it does depend on the exact sequence and other transitions work correctly.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.38 Chromium: 78.0.3904.108 (Official Build) nightly (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3903

`Only block only cross-site cookies`
![image](https://user-images.githubusercontent.com/34715963/69793745-5592bc80-11c9-11ea-8769-08c7e9c1b879.png)
`Allow all cookies`
![image](https://user-images.githubusercontent.com/34715963/69793788-66dbc900-11c9-11ea-9afd-e70aae83d574.png)
