### ISSUE TITLE
Flash deprecation banner disappears on launch

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#6805]
## Description 

The banner that warns users that Flash will be deprecated appears in Brave, but immediately disappears again:

![dsafsdfcasdfasdfasdfasdfs](https://user-images.githubusercontent.com/3299098/68347144-e256c880-00aa-11ea-936f-7d0b383d4441.gif)

## Steps to Reproduce

   1. Quit/Relaunch Brave while `Flash` site setting = `Ask`

## Expected result:
Banner should not disappear until dismissed.

## Reproduces how often: 

Always

## Brave version (brave://version info)

0.70.122

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

**Comment by bsclifton** [comment]
Disappears _in a Flash_

**Comment by ryanbr** [comment]
Safe to close @Brave-Matt (since flash is now removed)

**Comment by srirambv** [comment]
Closing as stale/invalid
