### ISSUE TITLE
On Oct 31st, my in-browser wallet started with ~110 BAT, I tipped someone 45 BAT, then had 0 BAT remaining

### ISSUE THREAD

**Issue by RickSayd** [brave/brave-browser#6806]
## Description 
On Oct 31st, my in-browser wallet started with ~110 BAT, I tipped someone 45 BAT and had 0 BAT left (in 4 increments of 10 BAT and once for 5 BAT since you can only tip 1,5, or 10 BAT at a time in the UI).

A couple of hours later I checked my wallet and I find that I have exactly 0 BAT left in my wallet when I expected ~65 BAT remaining. It's also weird because I would expect to have some fraction of 1 BAT left over; not exactly 0.

There were some error messages while tipping so I tried to tip 10 BAT many times but in my tip summary it shows I only tipped 45 and the person (tonyforthenguyen on Youtube) I tipped only received 45 (I didn't take a screenshot since I thought nothing of them and just kept tipping). **So even though tonyforthenguyen received 45, I spammed the tipping several times.**

Today, November 6th, I still don't have any grants for November 5th nor do I have a 20 BAT grant that I heard people were given. I think my wallet is stuck in some weird state?

## Steps to Reproduce
I can't really reproduce this because I have 0 BAT left.

   1. Visit https://www.youtube.com/watch?v=hcddeJgHhVE
   2. Send a Tip...
   3. Select 10 BAT tip amount
   4. Click Send Tip

## Actual result:
I started with ~110 BAT
I donate 45 BAT
I have 0 BAT left

I received error messages saying that something went wrong, to try again later. Sometimes it worked sometimes it didn't. 

Both my UI and the recipient Uphold wallet shows only 45 was transferred. My browser wallet shows that I have 0 BAT.

I don't have a screenshot of my UI because it was in October 31st and that tip history seems to get wiped at the beginning of every month.

![image](https://user-images.githubusercontent.com/38052038/68347536-1ed6f400-00ac-11ea-8846-afcf58d53575.png)

## Expected result:
I started with ~110 BAT
I donate 45 BAT
I should have 65 BAT left

## Reproduces how often: 
Intermittent issue, I cannot reproduce because I have 0 BAT remaining.

## Brave version (brave://version info)
![image](https://user-images.githubusercontent.com/38052038/68347666-92790100-00ac-11ea-8c57-50a881184cc1.png)

Brave	0.70.122 Chromium: 78.0.3904.87 (Official Build) (64-bit)
Revision	20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS	macOS Version 10.14.6 (Build 18G103)
JavaScript	V8 7.8.279.19
Flash	(Disabled)
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
Command Line	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=NewExtensionUpdaterService,PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,SyncUSSBookmarks,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,UnifiedConsent --flag-switches-begin --flag-switches-end
Executable Path	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path	/Users/antonguy/Library/Application Support/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:
Only using current release

- Can you reproduce this issue with the current release?
 I cannot reproduce because I have 0 BAT remaining.
- Can you reproduce this issue with the beta channel?
No
- Can you reproduce this issue with the dev channel?
No
- Can you reproduce this issue with the nightly channel?
No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:
Wallet Payment ID: f91777ec-9bb7-4ee8-9c10-a26891e19dea

**Comment by bsclifton** [comment]
@RickSayd thanks for the report - I had shared this with the team shortly after you created. If you haven't had a response yet, can you create an issue in https://community.brave.com/c/support-and-troubleshooting/desktop-support and link to this? Thanks! 😄

**Comment by RickSayd** [comment]
Sure, I've recreated the topic here: https://community.brave.com/t/bat-balance-went-to-0-after-tipping-forwarding-issue-from-github-repo/92389
