### ISSUE TITLE
Add tor switch option in settings

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#6808]
## Test plan
See https://github.com/brave/brave-core/pull/4046

## Description
That setting can enable/disable tor on runtime.
After changing that option, new option will be in effect after restarting.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.4.84 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4046
Tor enabled by default
![image](https://user-images.githubusercontent.com/34715963/74294255-923c7180-4d3d-11ea-840a-ec31218d22c3.png)
Tor off
![image](https://user-images.githubusercontent.com/34715963/74294274-a2545100-4d3d-11ea-8aab-e73dcd122c44.png)
Task manager after closing Tor window
![image](https://user-images.githubusercontent.com/34715963/74294352-ddef1b00-4d3d-11ea-991d-2850be6bdd32.png)
