### ISSUE TITLE
Add missing dependencies to brave://credits

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#6809]
The `chrome://credits/` page is generated by a [script](https://cs.chromium.org/chromium/src/tools/licenses.py?type=cs&q=about_credits&sq=package:chromium&g=0&l=241) based on the licensing info included in specific directories.

**Comment by GeetaSarvadnya** [comment]
@fmarier `autoplay-whitelist` entry is not present under brave://credits in `Window 10 x64 brave version 0.71.114`. As per the test plan https://github.com/brave/brave-core/pull/3899, the entry should be available in brave://credits. Can you check it from your end and confirm?

**Comment by kjozwiak** [comment]
Same result as @GeetaSarvadnya on `macOS 10.15.1 x64`. I'm not seeing `autoplay-whitelist` listed under `brave://credits` as per https://github.com/brave/brave-core/pull/3899.

**Comment by kjozwiak** [comment]
Created the following two issues as follow ups which will be addressed separately:

* `Muli` being listed twice under "brave://credits" - #6881
* "autoplay-whitelist" missing from "about://credits" - #6882

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.1 x64` using the following build:

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.15.1 (Build 19B88)

Ensured that the following entries appeared under `brave://credits`:

* `Background images`, `Bluebird`, `boto`, `Brave Sync`, `Bulgarian adblock list`, `EasyList`, `Muli (listed twice)`, `PROCHLO`, `Tor`, `TweetNaCl`, `ZXing`

Also ensured that both `show license`/`hide license` and `homepage` worked for each of the above entries.
