### ISSUE TITLE
Ad Iframes not collapsing

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#6810]
## Description 
Visiting `http://itest.5ch.net/egg/test/read.cgi/mac/1562707026`  I expect the iframes we block should be collapsing (like other adblock extensions) 

## Steps to Reproduce

   1. Visit `http://itest.5ch.net/egg/test/read.cgi/mac/1562707026`
   2. Whitespace occurs still in middle
   3. (see screenshot)

## Actual result:
We block in brave-unbreak the related adserver `thench.net` (iframe). But its not collapsing the iframe when we block it.

![shields-on](https://user-images.githubusercontent.com/1659004/68355300-b18e9600-0173-11ea-9896-0443d586008b.png)

## Expected result:
![ubo-on](https://user-images.githubusercontent.com/1659004/68355306-b5221d00-0173-11ea-89d8-39b9c5df582c.png)

## Reproduces how often: 
Easily.

## Brave version (brave://version info)
Version 0.70.122 Chromium: 78.0.3904.87 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Miscellaneous Information:
We block ||thench.net^$third-party in brave-unbreak.txt list, 

The specific url's being used in the middle (of the screenshots);

`https://stab.thench.net/threads/thread_top_left_300x250`
`https://stab.thench.net/threads/thread_top_right_300x250`

**Comment by pes10k** [comment]
I think this should be solved now that cosmetic filtering is in.  I'm going to close, but please reopen if it comes up agian
