### ISSUE TITLE
[Android] Port "Cap the number of ads allowed in the notification tray" from browser-android-tabs

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#6813]
Issue: https://github.com/brave/browser-android-tabs/issues/1932
Ref Android PR: https://github.com/brave/browser-android-tabs/pull/2054.

**Comment by bridiver** [comment]
can we please update this to point to the original issue? We absolutely do not want to port that code from the browser-android-tabs PR. The number of ads should be managed by the AdsService, not inside the notification display service

**Comment by srirambv** [comment]
Skipping this after discussing with @bbondy  and @SergeyZhukovsky. Catalog is pretty limited and unable to crate wallet on staging so needs to be tested again for release.
