### ISSUE TITLE
[Android] Port `Turn off haptics for Brave Ads Notifications.` from android-browser-tabs

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#6814]
Port https://github.com/brave/browser-android-tabs/pull/1888 into brave-core.

**Comment by srirambv** [comment]
Verification passed on OnePlust 6T with Android 10 running 1.5.111 x64 stable build
- Verified ad notification doesn't use haptics
- Verified other notification still uses haptics
-------
Verification passed on Samsung Tab A with Android 9.0 running 1.5.111 x64 stable build
- Verified ad notification doesn't use haptics
- Verified other notification still uses haptics
