### ISSUE TITLE
Remove macOS changes for "Fix user earns while native Windows and macOS notifications are suppressed"

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#6818]
Remove macOS changes for "Fix user earns while native Windows and macOS notifications are suppressed" as until we transition from NSUserNotificationCenter to UNUserNotificationCenter notifications will not appear. I will comment out the code ready for re-implementation at a later date once we are using UNUserNotificationCenter

**Comment by btlechowski** [comment]
Based on the test plan from https://github.com/brave/brave-core/pull/3907, this issue is macOS only. Added proper flags.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.2 x64` using the following build:

Brave | 1.3.92 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.15.2 (Build 19C57)

Going to label this as `QA Pass-macOS` as ad notifications were checked via https://github.com/brave/brave-browser/issues/6786#issuecomment-575248593.
