### ISSUE TITLE
Update 0.71.x with the latest localization.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#6821]
QA:
Verify that the known localization gaps have been corrected.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/brave-core/pull/3922

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Logged #6866
