### ISSUE TITLE
google keep is slow and freezes the browser

### ISSUE THREAD

**Issue by joejoejo** [brave/brave-browser#6822]
Description 

when going to google keep it loads and then becomes unresposive and it can freeze and make the browser unresposive.

## Steps to Reproduce

   1. go to keep.google.com
Actual result:
keep is slow and freezes the browser

Expected result:
keep should be responsive and not freeze the browser

Reproduces how often: 

the severaty of how is freezes and how it is slow chanmges but it freezes and slows down everytime

Brave version (brave://version info)

Brave | 0.72.119 Chromium: 78.0.3904.87 (Official Build) beta (64-bit)
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Windows 10 OS Version 1909 (Build 18363.449)

Version/Channel Information:

has been going on for while now but it has gotten worse resently

Other Additional Information:

Does the issue resolve itself when disabling Brave Shields?
yes
Does the issue resolve itself when disabling Brave Rewards?
yes
Is the issue reproducible on the latest version of Chrome? 
no

**Comment by mih0vil** [comment]
I have the same issue in both Google Chrome and Brave browsers. Native Android app works fine.

**Comment by gootchassassin** [comment]
> I have the same issue in both Google Chrome and Brave browsers. Native Android app works fine.

+1 exact same issues here

**Comment by mailmesjp** [comment]
I had this for years; until today. I had 3 active notes and hundreds of archived notes. One of the active notes had around 1000 'checked' items.

I resolved it by "deleting all checked", now keep on chrome opens in seconds, rather than minutes.

**Comment by bsclifton** [comment]
possibly related https://github.com/brave/brave-browser/issues/3650

**Comment by rebron** [comment]
@joejoejo Are you still having issues with Google Keep with a more current version of Brave? We're on Brave 1.1 right now (and will be releasing 1.2 soon).

**Comment by joejoejo** [comment]
I am on the beta. It is working better then before it loads much after and does not freeze the browser for as much.

**Comment by bsclifton** [comment]
@joejoejo great! Did you see the comment by @mailmesjp? Do you have a large number of archived notes?

**Comment by joejoejo** [comment]
Yes i do have alot of notes but before it was freezing while loading them and freezing after loading them. Now it only freezes after loading them.

**Comment by vkuznet** [comment]
which notes are you talking about? Where to find them and how to delete them. My Brave periodically freezes and it is slow when I open a new tab and enter something in URL field. The autocomplete takes almost a minute sometime.

**Comment by ryanbr** [comment]
@joejoejo Just retested this (In Brave Release), creating and deleting notes. Seems everything is okay? Can you confirm?

**Comment by ryanbr** [comment]
Given we've had many different Brave releases since. Re-tested this, @joejoejo  seems okay so far, from a clean profile Google Keep is performing similar (same) as Chrome. Closing this request,  Feel free to reopen this ticket if it's still an issue and prod me.
