### ISSUE TITLE
 Crypto Wallets add tokens to account button hidden in side-bar

### ISSUE THREAD

**Issue by zirs3d** [brave/brave-browser#6824]
## Description 

On Crypto Wallets, the "Add tokens" to account Button hidden in footer of sidebar

## Steps to Reproduce

   1. Open Crypto Wallets Account 1
   2. Browse the list of tokens in side-bar
   3. Add more than 3-5 tokens to the list of tokens
   4. If there is more than 3-5 tokens, the "add tokens" to account button is hidden
in footer of sidebar, unable to scroll beyond the currently visible token items.
   

## Actual result:

With more than 3-5 tokens, the add tokens to account button is hidden in footer of sidebar, 
unable to scroll beyond the items.

## Expected result:
For more than 3-5 tokens, the add tokens to account button should be visible in overflow scrolling area.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave: 0.70.122 Chromium: 78.0.3904.87 (Official Build) (64-bit)
Revision: 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS: Windows 10 OS Version 1903 (Build 18362.418)

## Version/Channel Information:
Current release

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
nope
- Does the issue resolve itself when disabling Brave Rewards?
nope
- Is the issue reproducible on the latest version of Chrome? 
nope

**Comment by srirambv** [comment]
Reproduced on BCW. Doesn't happen with MM

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Linux

* Verified able to scroll tokens in list using component `0.1.29`
![image](https://user-images.githubusercontent.com/17010094/69283076-b878c800-0bb9-11ea-9e55-7b8b8eb0507c.png)
