### ISSUE TITLE
Duplicate copies of Google fonts in the repo

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#6832]
We have two copies of the Muli and Poppins fonts in `brave-core`:
- https://github.com/brave/brave-core/tree/master/components/fonts
- https://github.com/brave/brave-core/tree/master/ui/webui/resources/fonts

Presumably one of these could refer to the other one.

**Comment by fmarier** [comment]
This causes Muli to appear twice in `brave://credits` (#6881).

**Comment by fmarier** [comment]
The two `muli.css` files [aren't identical](https://gist.github.com/fmarier/8d48281c97ae3dedc1e2b7086f0f3ab6) but from what I can see the only difference is that the one in `ui/webui` defines more sizes.

**Comment by btlechowski** [comment]
@fmarier It seems that test plan from https://github.com/brave/brave-core/pull/4004 requires dev environment. Is there a way to test without it?

https://github.com/brave/brave-browser/issues/6881 has already been verified. Maybe it is enough?

**Comment by fmarier** [comment]
> It seems that test plan from brave/brave-core#4004 requires dev environment. Is there a way to test without it?

The alternative is to look at the various pages (listed in the PR) where we use the fonts and check that they "look right". I thought I wouldn't necessarily notice if the fonts had changed which is why I hacked the colors in my test.

Maybe someone with a good eye for fonts can double-check that everything looks right in Beta?

**Comment by btlechowski** [comment]
I tried to see but I am blind!

Verified to the best of my ability (https://github.com/brave/brave-browser/issues/6832#issuecomment-571254730)

Verification passed on

Brave | 1.3.85 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Ubuntu 18.04 LTS

I used dev tools to check fonts.
