### ISSUE TITLE
Improve some P3A metrics

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#6841]
1. `DefaultBrowser.State` should have only 2 buckets instead of 4 as in Chromium, so we should replace it with a custom one.
2. `Brave.Rewards.AdsState` Doesn't check if the wallet already exists while recording the very first value.

(For reference see https://github.com/brave/brave-browser/wiki/P3A)

**Comment by bsclifton** [comment]
@iefremov does this issue need manual QA testing? If so, can we add a test plan and label as `QA/Yes`. Thanks! 😄

**Comment by iefremov** [comment]
test plan:

The second issue can be tested the same way as https://github.com/brave/brave-browser/issues/7253

The first one: new metric called `Brave.Core.IsDefault` is added. It should work the same way as DefaultBrowser.State and always emit 0 or 1

@LaurenWags

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.4.84 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the scenarios from https://github.com/brave/brave-core/pull/3931#issuecomment-575746819
