### ISSUE TITLE
Different windows take same Zoom properties in same website

### ISSUE THREAD

**Issue by elementyys** [brave/brave-browser#6842]
## Description 
When a tab is opened in a page and you open the page in an different window if you try to zoom-in that zoom will apply to both windows.

## Steps to Reproduce

   1. Open browser in website
   2. Open new window in same website
   3. Zoom-in 
   4. See the effect taking place in both windows

## Actual result:
Both windows take the same zoom.

## Expected result:
Keep the zoom only in zoomed window not elsewhere

## Reproduces how often: 
Easily reproduced even in private mode

## Brave version (brave://version info)
Desktop Version 0.70.123

**Comment by srirambv** [comment]
This is expected. Zoom level is saved on domain basis not browser window wise. If you visit the same site in different tabs the zoom level will be changed on both tabs. Dont think its possible to do a window based zoom.
