### ISSUE TITLE
Refactor logging in Brave Rewards to support Chromium log verbosity

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#6845]
After enabling rewards the browser emits a bunch of logs that are too verbose. We may want to move some of this logging to `VLOG`.

In particular, the following files are quite noisy:
`ledger_impl.cc`, `confirmations_impl.cc`, `ads_rewards.cc`, `ads_impl.cc`, `ads_service_impl.cc`

**Comment by jsecretan** [comment]
Bumping this back up because I think this is a prerequisite to better user debugging panel.

**Comment by tmancey** [comment]
Closing issue as resolved as part of https://github.com/brave/brave-browser/issues/7242
