### ISSUE TITLE
Brave Rewards are disabled even when there is network error on SafetyNet check. Needs to be fixed.

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#6849]
This is duplicate issue for https://github.com/brave/browser-android-tabs/issues/2242
Created just for PR

**Comment by btlechowski** [comment]
@samartnik Could you add `QA/Yes` or `QA/No` label?

**Comment by samartnik** [comment]
@btlechowski test steps are the same as in https://github.com/brave/browser-android-tabs/issues/2242
To test, on device without network try to join rewards. It should show try later toast, and Brave icon should be still available.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.58 x64 beta build
- Verified toast message is shown to try again later
![image](https://user-images.githubusercontent.com/17010094/73104319-26948080-3ec4-11ea-8442-9af5421d2f11.png)
- Verified rewards button isn't removed from URL bar
- Verified able to join rewards once network is available
------
Verification passed on Samsung Tab A with Android 9 running 1.5.58 x64 beta build
- Verified toast message is shown to try again later
![image](https://user-images.githubusercontent.com/17010094/73104344-344a0600-3ec4-11ea-9a65-4149e60c2acc.png)
- Verified rewards button isn't removed from URL bar
- Verified able to join rewards once network is available
