### ISSUE TITLE
Crash on Extension Install

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#685]
## Description 
Immediately upon installing v0.53.1 I set out to install the LastPass extension from the Chrome Web Store. Upon installing, the icon briefly appeared in the browser chrome, and then the browser crashed immediately. I started it back up and it prompted to me restore my previous state, which I did. LastPass didn't appear to be installed, so I went to install it again (partly curious to see if it would crash again). This time it did not crash. LastPass now appears to be working.

## Steps to Reproduce
1. First-time install (not sure how important this is) v0.53.1
2. Install LastPass (4.16.0) from the Chrome Web Store

## Actual result:
Browser crashes.

## Expected result:
Extension installs and is immediately available.

## Reproduces how often: 
Only once.

## Brave version (about:brave info) 
Version 0.53.1 Chromium: 69.0.3497.12 (Official Build) dev (64-bit)

### Reproducible on current release:
Repros on v0.53.1

**Comment by srirambv** [comment]
Couldn't reproduce this on my machine with a clean install

**Comment by jonathansampson** [comment]
I haven't experienced this in quite a while.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.17 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux

* Verified no crash while installing extension when testing #1628
