### ISSUE TITLE
panel doesn't immediately show twitch publisher info

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6851]
## Description 
The rewards panel doesn't immediately show Twitch publisher info when opened. Need to restart Brave to get the panel to show pub info.

Reproduced with 0.71.x, 0.74.x
Does not reproduce on 0.70.x

## Steps to Reproduce

   1. Clean profile 0.71.113
   2. Enable Rewards
   3. Visit a twitch publisher (twitch.tv/ilikeblueturtles for example)
   4. Wait for page to load.
   5. Click on panel. 
   6. Panel just shows twitch.tv (not ilikeblueturtles on twitch). Refresh of page, close reopen tab does not help.
   7. Close and restart Brave.
   8. Open panel again.
   9. Now twitch publisher info is shown on panel.

## Actual result:
<img width="979" alt="Screen Shot 2019-11-08 at 4 19 34 PM" src="https://user-images.githubusercontent.com/28145373/68513277-9d689880-0248-11ea-91c4-4432a716acdc.png">

## Expected result:
<img width="1054" alt="Screen Shot 2019-11-08 at 4 55 00 PM" src="https://user-images.githubusercontent.com/28145373/68513280-9f325c00-0248-11ea-8166-3e6e4840baa6.png">

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.71.113 Chromium: 78.0.3904.87 (Official Build) (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | macOS Version 10.13.6 (Build 17G5019)

Brave | 0.74.9 Chromium: 78.0.3904.87 (Official Build) nightly (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? not on 0.70.123
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? yes, 0.74.9

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @NejcZdovc @mandar-brave @brave/legacy_qa

**Comment by btlechowski** [comment]
Reproduced on 

Brave | 0.71.113 Chromium: 78.0.3904.87 (Official Build) (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Windows 7 Service Pack 1 (Build 7601.24530)

The issue stops reproducing after browser restart
Also reproduced with steps from https://github.com/brave/brave-browser/issues/3417

**Comment by btlechowski** [comment]
This issue still reproduces. 

Brave | 1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Windows 7 Service Pack 1 (Build 7601.24530)

**Comment by GeetaSarvadnya** [comment]
The issue is still reproducible in 

```
Brave | 1.16.68 Chromium: 86.0.4240.111 (Official Build) (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Windows 10 OS Version 1903 (Build 18362.1139)

```
```

Brave | 1.17.52 Chromium: 86.0.4240.111 (Official Build) dev (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Windows 10 OS Version 1903 (Build 18362.1139)


```

**Comment by Miyayes** [comment]
Let's refile anew if we see still see this.
