### ISSUE TITLE
Create a repository for commonly-used licenses

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#6856]
#6809 introduces a number of copies of the same licenses in our repository.

Some licenses are almost always customized (e.g. MIT, BSD), but others (MPL, GPL, Unlicense, CC, OFL, Apache) are always exactly the same. For the latter, we could create a new `src/brave/common-licenses/` and refer to files in there from the relevant `README.chromium` files.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.38 Chromium: 78.0.3904.108 (Official Build) nightly (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4000
@fmarier `advblock` is not listed in `brave://credits`, typo?

Examples:
![image](https://user-images.githubusercontent.com/34715963/69808950-0066a300-11e9-11ea-8c75-b84521cc9e8c.png)
![image](https://user-images.githubusercontent.com/34715963/69808986-12e0dc80-11e9-11ea-8c13-bb9a310be0b6.png)
![image](https://user-images.githubusercontent.com/34715963/69809012-22602580-11e9-11ea-95ea-cf43d726d82a.png)

**Comment by GeetaSarvadnya** [comment]
@fmarier I can see the following items in brave://credits. Except for these 4 items, I don't have remaining licenses in window 10. Is this platform-specific or some items are missing in windows?

PROCHLO (Apache-2.0)
HTTPS Everywhere (GPL-2.0)
Muli (OFL-1.1)
Poppins (OFL-1.1)

**Comment by btlechowski** [comment]
@GeetaSarvadnya I can see the licenses on 1.3.87 on Windows 7 x64 and Windows 10 x64
![image](https://user-images.githubusercontent.com/34715963/72152806-5d3ea700-33ac-11ea-9ac6-225182b89a4a.png)
![image](https://user-images.githubusercontent.com/34715963/72152823-6f204a00-33ac-11ea-8935-e84cdef94f16.png)
![image](https://user-images.githubusercontent.com/34715963/72152865-8eb77280-33ac-11ea-932d-f479475eae27.png)
![image](https://user-images.githubusercontent.com/34715963/72152890-9f67e880-33ac-11ea-9eaa-33d2a4016cd8.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.3.88 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.14.6 (Build 18G103)

* Verified test plan from https://github.com/brave/brave-core/pull/4000
* Note, only `PROCHLO`, `Brave HTTPS Everywhere`, `Muli`, and `Poppins` are available on `brave://credits` without having to expand anything
* You need to expand `Brave Ad Block` or `Brave Local Data` to see the remainder of the licenses from https://github.com/brave/brave-core/pull/4000
