### ISSUE TITLE
Detect new node modules added to brave-core without a LICENSE

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#6857]
In order for node module dependencies to show up in `brave://credits`, a developer needs to add a `README.chromium` in `brave/third_party/`.

We could rely on the `brave/third_party/npm_<module name>` pattern and write an automate check which parses `brave/package.json` and looks for missing `brave/third_party/npm_<module name>` directories.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.92 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5561
<img width="1059" alt="Screen Shot 2020-07-17 at 9 14 01 AM" src="https://user-images.githubusercontent.com/28145373/87790113-11166880-c80e-11ea-99aa-138f527be792.png">
<img width="1035" alt="Screen Shot 2020-07-17 at 9 14 30 AM" src="https://user-images.githubusercontent.com/28145373/87790120-1378c280-c80e-11ea-9332-9ffbe83a68f9.png">
<img width="1039" alt="Screen Shot 2020-07-17 at 9 14 58 AM" src="https://user-images.githubusercontent.com/28145373/87790127-15428600-c80e-11ea-9632-e56885a9f675.png">

-----

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.111 x64 build
- Verified following credits are listed 

array-move | parse-domain  | React Sortable HOC
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/89895171-3f038880-dbd3-11ea-9c93-eeeffb18c19f.png) | ![image](https://user-images.githubusercontent.com/17010094/89895155-3448f380-dbd3-11ea-8fff-a5492422e598.png) | ![image](https://user-images.githubusercontent.com/17010094/89895194-4a56b400-dbd3-11ea-95f2-a0c541d03bf1.png)

-------

Verification passed on Samsung Tab A with Android 10 running 1.12.111 x64 build
- Verified following credits are listed 

array-move | parse-domain  | React Sortable HOC
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/89895332-8c7ff580-dbd3-11ea-9ab5-366c870e3621.png) | ![image](https://user-images.githubusercontent.com/17010094/89895350-9144a980-dbd3-11ea-81e2-f5d94d5a76aa.png) | ![image](https://user-images.githubusercontent.com/17010094/89895367-96a1f400-dbd3-11ea-8696-a3e06f2ca1e5.png)
