### ISSUE TITLE
Amazon Prime & Netflix not working Windows 10

### ISSUE THREAD

**Issue by vinayg-cp** [brave/brave-browser#6859]
I think overnight an update was pushed to my browser, 
Since then I am not able to play netflix/amazon prime video on my Windows 10 machine. 

Prime Video Error:
![image](https://user-images.githubusercontent.com/43405939/68527403-6bb90580-030c-11ea-9d41-f92254afd4e6.png)

Netflix error: 
![image](https://user-images.githubusercontent.com/43405939/68527406-82f7f300-030c-11ea-8b96-4c9bff37863c.png)

About Brave Browser: 
![image](https://user-images.githubusercontent.com/43405939/68527413-96a35980-030c-11ea-8723-92f033cb95fd.png)

**Comment by bsclifton** [comment]
@vinayg-cp can you please go to brave://components and then click `Check for updates` under `Widevine Content Decryption Module`

There may have been a bad version of Widevine pushed (for sure there was on macOS, see https://github.com/brave/brave-browser/issues/6836), but it may be fixed now

**Comment by vinayg-cp** [comment]
Yes it got fixed. Thanks

**Comment by bsclifton** [comment]
@vinayg-cp awesome! thanks for verifying 😄
