### ISSUE TITLE
Can't see fullscreen videos on YouTube

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#686]
## Description 
Videos aren't visible on YouTube when viewing in fullscreen.

## Steps to Reproduce
1. Navigate to a video (https://www.youtube.com/watch?v=70JIXsey2iI)
2. When the video begins, click the YouTube fullscreen button

## Actual result:
Audio, but no video.

## Expected result:
Fullscreen video.

## Reproduces how often: 
100%

## Brave version (about:brave info) 
Brave | 0.53.1 Chromium: 69.0.3497.12 (Official Build) dev (64-bit)
-- | --
Revision | e8e14b69c41a5a461c15fa5d1065ec28c49890ac-refs/branch-heads/3497@{#54}
OS | Windows
JavaScript | V8 6.9.427.5
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.12 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser-Dev\Application\brave.exe" --enable-tab-audio-muting --disable-domain-reliability --disable-chrome-google-url-tracking-client --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser-Dev\Application\brave.exe
Profile Path | C:\Users\jjdsa\AppData\Local\BraveSoftware\Brave-Browser-Dev\User Data\Default

### Reproducible on current release:
Reproduces on v0.53.1

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? **No**
- Is the issue reproducible on the latest version of Chrome? **No**

### Additional Information
Calling the fullscreen method directly on the video element works:
```js
document.querySelector('video').webkitRequestFullScreen()
```

**Comment by srirambv** [comment]
Couldn't reproduce this issue on my machine with clean install

**Comment by jonathansampson** [comment]
I also cannot repro today.
