### ISSUE TITLE
Brave Isn't Your Default Browser

### ISSUE THREAD

**Issue by pilsnerbeer** [brave/brave-browser#6860]
## Description 

I cannot set Brave as the default browser and and this popup keeps showing each time I fire it up:

![Screenshot_20191109_180615](https://user-images.githubusercontent.com/36133540/68532314-0e2cb500-031c-11ea-8ea2-835f7f509fee.png)

I use MANJARO Linux with KDE desktop. this is the setting for setting default applications:

![Screenshot_20191109_180652](https://user-images.githubusercontent.com/36133540/68532335-4502cb00-031c-11ea-8390-a98dfc551072.png)

I have Brave set as the default browser here. But it doesn't seem to be working as the popup keeps coming back.

## Reproduces how often: 
Each time browser starts

## Brave version (brave://version info)

Brave | 0.68.141 Chromium: 77.0.3865.90 (Official Build) unknown (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Linux

**Comment by RsPlayer** [comment]
I use Arch Linux with KDE and I had same issue. this is what I did to solve it:
1- create an empty html file (ex: file.html)
2- Right click -> Open with -> Other Application... -> chose brave & tick remember application -> Ok

**Comment by pilsnerbeer** [comment]
Thanks. I just tried it - the links now always open in Brave without prompt but the pop-up still won't disappear..

**Comment by RsPlayer** [comment]
> Thanks. I just tried it - the links now always open in Brave without prompt but the pop-up still won't disappear..

try to re-click on `set as default` and it will be solved.

**Comment by pilsnerbeer** [comment]
I did that but nothing seems to be happening.

**Comment by RsPlayer** [comment]
> I did that but nothing seems to be happening.
> It disappears but pops up again on browser start.

You can ignore it forever by clicking on the `X` button on the right, it won't pop up again. my solution will make brave default for opening links and files so everything will be fine even if brave doesn't detect itself as default browser.

**Comment by pilsnerbeer** [comment]
That's good - after closing it seems it doesn't come back up. Thanks!
