### ISSUE TITLE
brave://flags/#dns-over-https is not an available flag on Nightly or Dev

### ISSUE THREAD

**Issue by brianddk** [brave/brave-browser#6861]
## Description 

The suggest flags setting for DoH doesn't exist in Nightly or Dev builds of Brave

## Steps to Reproduce

   1. Browse to `brave://flags/#dns-over-https`
   2. Observe no flag setting there.

## Actual result:

No flag setting there

## Expected result:

Expected to be able to enable DoH there.

## Reproduces how often: 

Everytime

## Brave version (brave://version info)

Brave  0.74.7 Chromium: 78.0.3904.87 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the dev channel?  ***Yes*** version 78.0.72.106
- Can you reproduce this issue with the nightly channel? ***Yes*** version 78.0.74.7

## Miscellaneous Information:

![78.0.74.7.img](https://i.redd.it/2taeqkgi7px31.jpg "78.0.74.7")

**Comment by bsclifton** [comment]
This was pulled into Chromium 78 with the latest Chromium update... we don't have new binaries yet for DEV or BETA, but I can confirm this is in Nightly 😄

**Comment by bsclifton** [comment]
Closing as we'll have this available soon- just waiting for CI to finish on DEV/BETA before we can merge and start new builds

Pull requests available here:
- DEV (0.73) https://github.com/brave/brave-browser/pull/6852
- BETA (0.72) https://github.com/brave/brave-browser/pull/6853

Thanks for reporting 😄

**Comment by bsclifton** [comment]
Bigger discussion happening here, in case you wanted to take part @brianddk 😄 
https://github.com/brave/brave-browser/issues/1864

**Comment by Johann999** [comment]
The dns-over-https flag is also not under theStable version available.

**Comment by c-rilaun** [comment]
So, we don't have it anywhere in fact. Any idea when this one will come out ?

**Comment by bsclifton** [comment]
@c-rilaun I'm running version 1.1.22 and it's showing for me under brave://flags/#dns-over-https

What version are you on? Also curious, which OS?

**Comment by brianddk** [comment]
@bsclifton is it perhaps tracking Windows Group Policies?  The flag does not show up on my Windows 7 laptop on my company domain behind my company firewall.  But the flag does show up on my Windows 10 home PC.  Both running Brave 79.1.1.22.

Interesting...

**Comment by bsclifton** [comment]
@brianddk that is definitely possible! You might be able to see some info if you go to brave://policy
