### ISSUE TITLE
Weird double loading image on simple html page.

### ISSUE THREAD

**Issue by nikahmadz** [brave/brave-browser#6863]
I am developing a website page on brave when I noticed unnecessary request were made to the server. So I have tried narrowing the case down to this demo over here to reproduce the weird behavior.

## Expectation
A standard `<img src="..." />` tag should request the said resources **only once**.

## The problem
> **The page request the same URI twice.**  

Each request you see on this image below returned 2 different image. Only the first one were rendered on the screen. Yet The second request do fetch another completely different image from the server.

![Annotation 2019-11-10 102409](https://user-images.githubusercontent.com/7868782/68538348-d8d0a780-03ad-11ea-9237-eb9cea0d2a8a.png)

## The weird part
The problem **only happen** when the `<img>` tag is in between two heading / paragraph tag. And it will only happen when the first paragraph **has more than 4 word**. The problem does not happen if the first paragraph has fewer words. That is for me is weird. Yet, this situation is likely to happen on a regular web document.

## Reproducing
A simple web page should be able to reproduce the case.

  <!DOCTYPE html>
  <html lang="en">

    <head>
      <meta charset="utf-8">
      <title>Images</title>
      <meta name="date.modified" content="Sun, 10 Nov 2019 03:01:15 GMT" />
    </head>

    <body>
      <p>0 1 2 3 4</p>
      <img src="https://placeimg.com/160/120" />
      <p>0</p>
    </body>

  </html>

## Brave version
I am using Brave is up to date
Version 0.70.123 Chromium: 78.0.3904.97 (Official Build) (64-bit)

PS: I hope this issue get solved quickly. Because it may cause large image to be loaded multiple times more than necessary.

**Comment by nikahmadz** [comment]
have someone look into this mater?

**Comment by rebron** [comment]
@nikahmadz We need some more help testing this one out. Can you check if this is still an issue with a more current version of Brave. The latest Brave is version 1.1. Can you also check to see if this is happening in the latest version of Chrome.

**Comment by nikahmadz** [comment]
> @nikahmadz We need some more help testing this one out. Can you check if this is still an issue with a more current version of Brave. The latest Brave is version 1.1. Can you also check to see if this is happening in the latest version of Chrome.

You can view a test page I have setup here. Yes the problem still persist. The image was loaded twice. First by index.html and the other one by brave VM.

**Test page**: https://nikahmadz.github.io/brave/

![Annotation 2020-01-11 125729](https://user-images.githubusercontent.com/7868782/72199183-5d55aa00-3473-11ea-8be8-8dabf7a216dc.png)

**Comment by nikahmadz** [comment]
Brave version 1.35 does not have this problem anymore.
