### ISSUE TITLE
Localization is not applied for NTP rewards widget in German locale

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#6866]
## Description 

Found while testing #6821 
Localization is not applied for NTP rewards widget in German locale.  Verified Germany and France locales in both locales NTP rewards widget isn't localized, this issue could be there in other locales also.

## Steps to Reproduce

   1. Set OS locale to Germany
   2. Clean profile 0.71.114
   3. Open an NTP
   4. Rewards widget in an NTP is  not localized 
   5. Click on the Dashboard settings icon in NTP
   6. `Show Brave Rewards` setting isn't localized

## Actual result:

Localization is not applied for NTP rewards widget in German locale
![image](https://user-images.githubusercontent.com/38657976/68564680-38df5080-0477-11ea-84f9-ca6329bc8c93.png)

![image](https://user-images.githubusercontent.com/38657976/68564704-514f6b00-0477-11ea-8577-de52118e8727.png)

![image](https://user-images.githubusercontent.com/38657976/68565316-2403bc80-0479-11ea-9dbb-9d820bb4e8fd.png)

## Expected result:

Brave rewards widget should be localized
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 0.71.114 Chromium: 78.0.3904.97 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
Betriebssystem | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @mandar-brave @rebron @mkarolin @bsclifton @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Strings are not translated in Enable ads rewards widget

![image](https://user-images.githubusercontent.com/38657976/68565148-9d4edf80-0478-11ea-8eca-42c7ca47d229.png)

**Comment by btlechowski** [comment]
Same for Polish locale (PL)

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/68591126-48b75e80-0490-11ea-9b93-1597f68a0bf7.png)

**Comment by LaurenWags** [comment]
Reproduced for Bulgaria as well:

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

NTP widget has partial translations
<img width="350" alt="Screen Shot 2019-11-11 at 10 56 03" src="https://user-images.githubusercontent.com/28145373/68601250-f6ffdb80-0471-11ea-9f2f-dc9d58155dda.png">
<img width="311" alt="Screen Shot 2019-11-11 at 10 56 20" src="https://user-images.githubusercontent.com/28145373/68601256-f9facc00-0471-11ea-8d04-116d5c00abda.png">
<img width="336" alt="Screen Shot 2019-11-11 at 10 56 33" src="https://user-images.githubusercontent.com/28145373/68601260-fbc48f80-0471-11ea-8789-481821fb7afd.png">

**Comment by rebron** [comment]
cc: @mkarolin ping to double check on this one when translations are ordered/come in for 1.3 round.

**Comment by btlechowski** [comment]
No longer reproducible

Brave | 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

German locale:
![image](https://user-images.githubusercontent.com/34715963/75439226-b745fc80-5959-11ea-87c5-3d8542c0f0ab.png)
![image](https://user-images.githubusercontent.com/34715963/75439330-de043300-5959-11ea-9788-80193be2bd6f.png)
![image](https://user-images.githubusercontent.com/34715963/75439350-e6f50480-5959-11ea-977c-7dcca48c493c.png)

Bulgarian
![image](https://user-images.githubusercontent.com/34715963/75441263-a303fe80-595d-11ea-8e52-e2f129691fbb.png)
![image](https://user-images.githubusercontent.com/34715963/75441296-b2834780-595d-11ea-8a75-e437fc785a74.png)
![image](https://user-images.githubusercontent.com/34715963/75441318-c038cd00-595d-11ea-8848-d437663acf0d.png)
