### ISSUE TITLE
ads panel description on brave://rewards is not translated

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6868]
Important: not reproducible on 0.70.x nor on 0.74.x

## Steps to Reproduce

   1. Open Brave in Polish locale
   2. Open `brave://rewards`

## Actual result:

ads panel description is not translated
![image](https://user-images.githubusercontent.com/34715963/68591825-e3fd0380-0491-11ea-9ee1-9d8e26588b1f.png)

## Expected result:
ads panel description is translated
![image](https://user-images.githubusercontent.com/34715963/68591809-d8114180-0491-11ea-9534-4ae0c5f992e6.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

**Reproducible on**

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Ubuntu 18.04 LTS

**Not Reproducible on 0.70.x, nightly**

Brave | 0.70.123 Chromium: 78.0.3904.97 (Oficjalna wersja) (64-bitowa)
-- | --
Wersja | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
System operacyjny | Windows 7 Service Pack 1 (Build 7601.24530)

Brave | 0.74.7 Chromium: 78.0.3904.87 (Oficjalna wersja) nightly (64-bitowa)
-- | --
Wersja | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
System operacyjny | Windows 7 Service Pack 1 (Build 7601.24530)

cc @brave/legacy_qa @rebron @mkarolin @ryanml

**Comment by btlechowski** [comment]
@rebron @mkarolin This is a recent regression introduced between 0.70.111/0.70.112 and 0.70.113.

The issue started to reproduce on 0.70.113.

**Comment by LaurenWags** [comment]
Reproduces with other languages (Russian) as well.

Brave | 0.71.114 Chromium: 78.0.3904.97 (Официальная сборка) (64 бит)
-- | --
Версия | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
ОС | macOS Версия 10.13.6 (Выпуск 17G5019)

<img width="642" alt="Screen Shot 2019-11-11 at 9 27 29 ДП" src="https://user-images.githubusercontent.com/28145373/68594444-894db280-0465-11ea-9ade-35942d0396f1.png">

**Comment by mkarolin** [comment]
Fixed via brave/brave-core#3979

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.71.115 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Ubuntu 18.04 LTS

Verified STR from the description

tokens - Polish
![image](https://user-images.githubusercontent.com/34715963/68673671-92697d00-0554-11ea-9d15-78d3e08aab65.png)

tokens - English
![image](https://user-images.githubusercontent.com/34715963/68673959-32bfa180-0555-11ea-8f04-da785a62cd1f.png)

points - English
![image](https://user-images.githubusercontent.com/34715963/68673871-fab85e80-0554-11ea-8faf-9f60cc0390d8.png)

points - Japanese
![image](https://user-images.githubusercontent.com/34715963/68674033-5a166e80-0555-11ea-8810-055a4d234ece.png)
