### ISSUE TITLE
`Remove` on NTP widgets is not translated

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6869]
## Steps to Reproduce

   1. Change locale to Polish 
   2. Open New Tab
   3. Edit a NTP widget

## Actual result:

`Remove` is not translated
![image](https://user-images.githubusercontent.com/34715963/68592443-689c5180-0493-11ea-9b75-653fdba635aa.png)

![image](https://user-images.githubusercontent.com/34715963/68592429-5fab8000-0493-11ea-9f29-e9e1a21b100c.png)

## Expected result:
`Remove` is translated

## Reproduces how often: 

Always

## Brave version (brave://version info)

**Reproducible on**

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Ubuntu 18.04 LTS

Brave | 0.71.112 Chromium: 78.0.3904.87 (Oficjalna wersja) beta (64-bitowa)
-- | --
Wersja | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
System operacyjny | Windows 7 Service Pack 1 (Build 7601.24530)

Brave | 0.74.7 Chromium: 78.0.3904.87 (Oficjalna wersja) nightly (64-bitowa)
-- | --
Wersja | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
System operacyjny | Windows 7 Service Pack 1 (Build 7601.24530)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

cc @brave/legacy_qa @rebron @mkarolin @ryanml

**Comment by LaurenWags** [comment]
Reproduced for the languages I retested which were: Polish, French, German, Japanese

Brave | 1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)
-- | --
Revision | 99b6d241cf84f7fa7434ae8a59f9e74eb1464280-refs/branch-heads/3945@{#888}
OS | macOS バージョン10.13.6（ビルド17G5019）

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.5.102 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified STR from description for the following languages:

Polish
<img width="1286" alt="Polish" src="https://user-images.githubusercontent.com/28145373/75464182-d0987a00-5954-11ea-804c-05c2c11ce311.png">

French
<img width="1351" alt="French" src="https://user-images.githubusercontent.com/28145373/75464165-caa29900-5954-11ea-9409-54fa60ba4a51.png">

German
<img width="1112" alt="German" src="https://user-images.githubusercontent.com/28145373/75464149-c5dde500-5954-11ea-993c-1130a0c090ae.png">

Japanese
<img width="1113" alt="スクリーンショット 2020-02-27 午前11 31 00" src="https://user-images.githubusercontent.com/28145373/75464139-c2e2f480-5954-11ea-8d42-6aae32284c24.png">
