### ISSUE TITLE
Decouple filter for 'Last 7 Days' of Brave Ads history

### ISSUE THREAD

**Issue by masparrow** [brave/brave-browser#6870]
## Description 
The code for finding the last seven days of Ads to show in the Rewards Settings page can now be refactored into a stand alone filter (see 'AdHistoryFilter')

This makes it unit testable, and allows more filters to be applied in the future as needed.

**Comment by tmancey** [comment]
Closing issue as fixed as part of https://github.com/brave/brave-browser/issues/6757
