### ISSUE TITLE
Save Dialog Filter Doesn't Display All Jpeg Files

### ISSUE THREAD

**Issue by cwmke** [brave/brave-browser#6871]
## Description 
When saving images, already saved .jpg files are not shown by default. Only .jpeg files are visible.

## Steps to Reproduce

   1. Right click on an image and click 'save image as...'
   2. Dialog pops up with the '*.jpeg' filter' (if the image is a .jpeg file)

## Actual result:
Must switch to 'All Files' filter to view .jpg files. The same happens in reverse with saving .jpg files.

## Expected result:
Whether the extension is .jpg or .jpeg, the filter should show both as they are the same type of file.

## Reproduces how often: 
Easily reproduced. Duckduckgo's image search is a good place to find .jpeg files. Wikipedia has some .jpg.

## Brave version (brave://version info)

Brave | 0.70.122 Chromium: 78.0.3904.87 (Official Build) (64-bit)
-- | --
Revision | 20c21f4010010f32462ea8e1d6af30cef66d48c8-refs/branch-heads/3904@{#840}
OS | Linux

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Unknown

**Comment by bsclifton** [comment]
Reproduced on Linux and Windows (may happen on macOS too; didn't check)

If GTK (specifically, with [GtkFileChooserDialog](https://developer.gnome.org/gtk3/stable/GtkFileChooserDialog.html)) supports multiple file extensions (like I know Win32 does, with [GetSaveFileName](https://docs.microsoft.com/en-us/windows/win32/api/commdlg/nf-commdlg-getsavefilenamea)), we could possibly patch Chromium (or fix upstream) to add custom code to look at `.jpeg` extensions and manually change them to `*.jpg,*.jpeg`, but I don't think that would be a good idea

I'm going to close this and suggest we open a bug in Chromium instead:
https://bugs.chromium.org/p/chromium/issues/list

I didn't find any existing (open or closed) issues for this, but I suspect it would be closed as a `wontfix`
