### ISSUE TITLE
sometimes Private/Private Window is not capitalized 

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6872]
## Description 
While testing #2147 I noticed that the capitalization of `Private Window` isn't consistent across translations. 

For example, here is English (US). Private/Private Window is capitalized as I would expect:
hamburger menu:
<img width="1174" alt="EN-US1" src="https://user-images.githubusercontent.com/28145373/68597684-61f9e400-046b-11ea-9a90-4bf7d71ffb46.png">

on the window:
<img width="1176" alt="EN-US2" src="https://user-images.githubusercontent.com/28145373/68597708-6920f200-046b-11ea-8f62-d3725615a113.png">

from Brave menu (macOS):
<img width="380" alt="EN-US3" src="https://user-images.githubusercontent.com/28145373/68597719-70480000-046b-11ea-94f9-d3ba5688a38e.png">

right click:
<img width="299" alt="EN-US4" src="https://user-images.githubusercontent.com/28145373/68597732-75a54a80-046b-11ea-8448-d140d0771088.png">

Compared to English (UK), only 2 of the 4 items above are capitalized correctly - Hamburger menu and Brave menu (macOS):
<img width="1341" alt="EN-UK1" src="https://user-images.githubusercontent.com/28145373/68597875-b735f580-046b-11ea-9751-f8fa88156ee0.png">
<img width="371" alt="EN-UK4" src="https://user-images.githubusercontent.com/28145373/68597884-ba30e600-046b-11ea-8f0f-f10bda23a510.png">

On the window and right click, Private/Private Window is not capitalized as I would expect:
<img width="1338" alt="EN-UK2" src="https://user-images.githubusercontent.com/28145373/68597983-ddf42c00-046b-11ea-8d26-8276bfc79120.png">
<img width="309" alt="EN-UK3" src="https://user-images.githubusercontent.com/28145373/68597985-df255900-046b-11ea-8b69-d2d43337291b.png">

## Steps to Reproduce

Use a language other than English (US).
   1. Launch Brave with a clean profile.
   2. View the following places:
   * hamburger menu
   * Private Window
   * right click on a link to view context menu
   * Brave menu (macOS/Linux)
   3. See inconsistencies across capitalization.

## Actual result:
English (AU) - is similar to English UK:
<img width="1171" alt="EN-AU1" src="https://user-images.githubusercontent.com/28145373/68598227-6a9eea00-046c-11ea-8fe7-ebd598c5366a.png">
<img width="1176" alt="EN-AU2" src="https://user-images.githubusercontent.com/28145373/68598233-6bd01700-046c-11ea-9cb5-b9eb353ca8da.png">
<img width="381" alt="EN-AU3" src="https://user-images.githubusercontent.com/28145373/68598237-6d99da80-046c-11ea-959b-b3701dc0b6d1.png">
<img width="321" alt="EN-AU4" src="https://user-images.githubusercontent.com/28145373/68598248-6f639e00-046c-11ea-8ae4-a7573d1085c2.png">

DE - a little different, sometimes Private isn't capitalized, but Window is
<img width="1175" alt="DE1" src="https://user-images.githubusercontent.com/28145373/68598333-94581100-046c-11ea-82aa-168cb90a8179.png">
<img width="1174" alt="DE2" src="https://user-images.githubusercontent.com/28145373/68598336-9621d480-046c-11ea-8c87-87aa2d7f6f2f.png">
<img width="409" alt="DE3" src="https://user-images.githubusercontent.com/28145373/68598341-97530180-046c-11ea-9d91-38d7a92275e8.png">
<img width="331" alt="DE4" src="https://user-images.githubusercontent.com/28145373/68598343-991cc500-046c-11ea-83cc-c2af6623780a.png">

## Expected result:
Consistency in capitalization for Private/Private Window

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
cc: @petemill (I know you fixed the hamburger menu usage of this via https://github.com/brave/brave-core/pull/3922)

**Comment by petemill** [comment]
🤦‍♂

**Comment by bsclifton** [comment]
Fixed in 0.71.x with https://github.com/brave/brave-core/pull/3970 (other versions will get fixed when pulling translations for C79)

**Comment by LaurenWags** [comment]
To confirm, https://github.com/brave/brave-core/pull/3970 will only fix English (UK) correct, no other languages?

**Comment by bsclifton** [comment]
@LaurenWags that is correct! 😄

**Comment by petemill** [comment]
@LaurenWags with regards to other languages, I learnt (when dealing with the translations for these strings, although it would apply to many other strings we have) that different languages do not _do_ 'title case'. So, we'd need to take it on a case-by-case basis as to whether the translation for a specific language is was correctly translated to title-case when appropriate for that language.

**Comment by LaurenWags** [comment]
That's fair. Mostly wanted to clarify so when @brave/legacy_qa goes to test this one, they don't bother with the other languages I had listed. We can do as you suggest and deal with them on a case by case basis and log issues appropriately as they come up. cc @kjozwiak @rebron

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.71.115 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified STR from description
hamburger menu
<img width="1242" alt="Screen Shot 2019-11-12 at 10 14 24 AM" src="https://user-images.githubusercontent.com/28145373/68685502-3bee4580-0538-11ea-8ceb-1ff636623ce8.png">

Private Window - logged #6890
<img width="1241" alt="Screen Shot 2019-11-12 at 10 15 05 AM" src="https://user-images.githubusercontent.com/28145373/68685587-588a7d80-0538-11ea-931d-a16a6fd117e1.png">

right click on a link to view context menu - logged #6891 
<img width="1243" alt="Screen Shot 2019-11-12 at 10 15 33 AM" src="https://user-images.githubusercontent.com/28145373/68685626-62ac7c00-0538-11ea-9cc2-496f35b51683.png">

Brave menu (macOS/Linux)
<img width="379" alt="Screen Shot 2019-11-12 at 10 15 48 AM" src="https://user-images.githubusercontent.com/28145373/68685636-67713000-0538-11ea-8663-5cb2877818aa.png">
