### ISSUE TITLE
remove "add funds" message from tipping panel

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6874]
## Description 

When tipping a publisher via the `Rewards` panel, you'll get a `Not enough points. Please add funds` message.

## Steps to Reproduce

  1. Open browser
  2. Wait for initialization
  3. Close browser
  4. Open Preferences file and search for `countryid_at_install`
  5. Replace current value with `19024`
  6. Restart Browser
  7. Navigate to a website and attempt to tip more BAP than you currently have

## Actual result:

<img width="1219" alt="Screen Shot 2019-11-11 at 1 14 47 PM 1" src="https://user-images.githubusercontent.com/2602313/68610445-c3c74780-0485-11ea-802d-9561d78ab7ec.png">

## Expected result:

Should remove the `Not enough points. Please add funs` part of the message.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.15.1 (Build 19B88)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @mandar-brave @rebron @mattmcalister @brave/legacy_qa

**Comment by NejcZdovc** [comment]
We should just remove `Please add funds`

**Comment by bsclifton** [comment]
Fixed in 0.71.x with https://github.com/brave/brave-core/pull/3969

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.71.115 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR mentioned in the description
![image](https://user-images.githubusercontent.com/38657976/68669782-614b7580-0571-11ea-8063-e8fbf2618cf6.png)
