### ISSUE TITLE
ads disappearing after ~5s instead of the expected ~2mins using Catalina

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6876]
## Description 

Ad notifications are being dismissed after ~5seconds on the latest `0.71.114 CR: 78.0.3904.97` RC. This was QA'd on `0.71.111 CR: 78.0.3904.87` as per https://github.com/brave/brave-browser/issues/6466#issuecomment-549673347  but looks like it regressed.

Example of the timeout after ~5s:

```[87996:775:1111/142007.642067:INFO:ads_service_impl.cc(1969)] AdsService Event Log: {"data":{"type":"notify","stamp":"2019-11-11T14:20:07Z","notificationType":"timeout","notificationClassification":["technology & computing"],"notificationCatalog":"3ee3fc5d-01b7-44e5-857e-c680f59ed535","notificationUrl":"https://motille.com/path/lp.php?trvid=10017&trvx=1d35ebd8&var1=29_technology"}}```

Regression range:

* `0.71.114 CR: 78.0.3904.97` - Reproduced
* `0.71.113 CR: 78.0.3904.87` - Working as expected

Most likely regressed with the `78.0.3904.97` bump.

## Steps to Reproduce

   1. launch `0.71.114 CR: 78.0.3904.97` using `--enable-logging=stderr`
   2. enable `Rewards` and ensure `Ads` are also enabled
   3. visit brave.com and go idle for ~30s or so
   4. move the mouse and you'll get an ad notification that disappears in ~5s

## Actual result:

Ads notifications are being dismissed after ~5s even if `Alerts` is selected under the `Notifications` preferences.

## Expected result:

Ads notifications should be displayed for ~2mins when `Alerts` is selected under the `Notifications` preferences.

## Reproduces how often: 

100% reproducible using the STR mentioned above.

## Brave version (brave://version info)

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.15.1 (Build 19B88)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @brave/legacy_qa @bsclifton @rebron @tmancey

**Comment by LaurenWags** [comment]
While using High Sierra my ads displayed on screen for 2minutes before timing out without interaction from me.


Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

**Comment by bsclifton** [comment]
Fixed in 0.71 with https://github.com/brave/brave-core/pull/3976

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.1 x64` using the following build:

Brave | 0.71.115 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.15.1 (Build 19B88

* ensured that ad notifications are visible for ~2mins when set as `Alerts` via `Notifications` under macOS `Preferences`
* ensued a second ad notifications is displayed after ~12mins when the first ad notifications disappears due to hitting the ~2min timeout
* ensued that `Ad notifications received this month` is correctly being updated when ad notifications are displayed
* ensured both `Close` & `View` work on ad notifications that are using `Alerts` via `Notifications` under macOS `Preferences`
* ensured both `Close` & `View` work on ad notifications that are using `Banners` via `Notifications` under macOS `Preferences`
* ensured ad notifications are not being displayed when using `None` via `Notifications` under macOS `Preferences`
* ensured that `Banner` ad notifications are added into the notifications tray and timeout/clear after ~2mins
* ensured that click on an ad notifications that's queued in the notifications tray
