### ISSUE TITLE
Target is sometimes not shown fully on panel captcha

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6879]
## Description 

Target is sometimes not shown fully on panel captcha. Probably similar to #2956 but device DPI settings were 100%. 

## Steps to Reproduce

   1. Set locale to Japan and device DPI to 100%(default)
   2. Set env to staging to trigger grant
   3. Open panel, sometimes one of the target is not fully shown due to extra padding on message for other locales

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/68625824-0b5ecb00-04a8-11ea-874c-28c1ec91a398.png)

## Expected result:
Should always show the targets fully 

## Reproduces how often: 

Easy but needs a few retries of failed attempts

## Brave version (brave://version info)

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1903 (Build 18362.388)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Probably yes
- Can you reproduce this issue with the beta channel? Probably yes
- Can you reproduce this issue with the dev channel? Probably yes
- Can you reproduce this issue with the nightly channel? Probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
see same problem on macOS, so I think it's not scaling issue

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.81 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Ubuntu 18.04 LTS

The issue still reproduces. Logged https://github.com/brave/brave-browser/issues/7597 per our process.
