### ISSUE TITLE
Ads service will crash if a user previously had ads history and triggers OnUnIdle before Brave ads are initialized

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#6880]
## Description 

Ads service will crash if a user previously had ads history and triggers OnUnIdle before Brave ads are initialized

## Steps to Reproduce

   1. View an ad
   2. Quit the browser
   3. Launch the browser
   4. Wait for "Browser state changed to unidle" to appear in the console log
   5. Move the mouse (this must occur before Brave ads are initialized)

## Actual result:

Ads service crashes

## Expected result:
Ads service should not crash

## Reproduces how often: 

Intermittent issue

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

If the ads service crashes, it will restart. The browser will not crash

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.50 Chromium: 79.0.3945.56 (Official Build) nightly (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Ubuntu 18.04 LTS

Verified test plan from the description. No crash.

**Comment by kjozwiak** [comment]
Quickly talked to @tmancey and unfortunately there's no way to slow down ad initialization so Brave's state can change to `unidle` before initialization is completed.

So QA we'll basically make sure that retrieving ads doesn't crash/cause any issues.
