### ISSUE TITLE
`Muli` being listed twice under "brave://credits"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6881]
## Description 

Looks like `Muli` is being listed twice under `brave://credits` using `0.71.114 CR: 78.0.3904.97` which should have included `88c9110` as per https://github.com/brave/brave-core/commits/0.71.x.

## Steps to Reproduce

   1. launch brave (used `0.71.114 CR: 78.0.3904.97` in this instance)
   2. visit `brave://credits` and search for `Muli`

## Actual result:

<img width="1219" alt="Screen Shot 2019-11-11 at 8 36 02 PM" src="https://user-images.githubusercontent.com/2602313/68634483-a4e7a600-04c3-11ea-9daa-86d78f61930b.png">

## Expected result:

`Muli` should only be listed once under `brave://credits`

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.15.1 (Build 19B88)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

## Miscellaneous Information:

CCing @brave/legacy_qa @rebron @bsclifton @fmarier

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows 10 x64 - `0.71.114`

**Comment by fmarier** [comment]
The root cause for this is https://github.com/brave/brave-browser/issues/6832.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.38 Chromium: 78.0.3904.108 (Official Build) nightly (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

![image](https://user-images.githubusercontent.com/34715963/69808640-4d964500-11e8-11ea-963a-45f95ca781e9.png)
