### ISSUE TITLE
"autoplay-whitelist" missing from "about://credits"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6882]
## Description 

As per https://github.com/brave/brave-browser/issues/6809, `autoplay-whitelist` should have been added into `brave://credits` but is currently missing.

## Steps to Reproduce

   1. launch brave (used `0.71.114 CR: 78.0.3904.97` in this instance)
   2. visit `brave://credits` and search for `autoplay-whitelist`

## Actual result:

`autoplay-whitelist is missing from `brave://credits` as per https://github.com/brave/brave-browser/issues/6809.

## Expected result:

`autoplay-whitelist` should be listed under `brave://credits` as per https://github.com/brave/brave-browser/issues/6809.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.15.1 (Build 19B88)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

## Miscellaneous Information:

CCing @brave/legacy_qa @rebron @bsclifton @fmarier

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows 10 x64 - 0.71.114

**Comment by fmarier** [comment]
This was done in https://github.com/brave/autoplay-whitelist/pull/23 and it will show up automatically in brave-core once we update the `DEPS` file to point to the latest version of autoplay-whitelist: https://github.com/brave/brave-core/blob/6ae7924b1635a5888ac1cb392280995428ffe2e8/DEPS#L5

**Comment by fmarier** [comment]
Apologies for using that in the verification steps for #6605, I should have used one of the vendored dependencies that actually worked so that it could be verified easily.

I think we can safely ignore this issue for two reasons:
1. It will be fixed automatically once we update the version of the autoplay-whitelist in brave-core.
2. This is Brave code under the same license as the browser, so we're not going to get complaints about missing attribution from a third party.

**Comment by rebron** [comment]
Closing.
