### ISSUE TITLE
"Brave Software Inc" shouldn't be used for copyright via "chrome://settings/help" (Windows/Mac)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#6883]
## Description 

As per @tomlowenthal via https://github.com/brave/brave-browser/issues/6605#issuecomment-552664500, the current copyright statement is incorrect and needs to be changed. The original issue mentions `The Brave Authors` but we're using `Brave Software Inc`.

@tomlowenthal please provide the correct string/text.

## Steps to Reproduce

   1. launch brave (used `0.71.114 CR: 78.0.3904.97` in this instance)
   2. load `chrome://settings/help`

## Actual result:

<img width="745" alt="Screen Shot 2019-11-11 at 9 21 11 PM" src="https://user-images.githubusercontent.com/2602313/68636379-4de4cf80-04c9-11ea-93d6-b08eb09b86f5.png">

## Expected result:

@tomlowenthal please provide the correct string/text.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.15.1 (Build 19B88)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

## Miscellaneous Information:

CCing @brave/legacy_qa @tomlowenthal @bsclifton @rebron @fmarier

**Comment by fmarier** [comment]
Interesting, it shows up as Brave Authors on Linux:
![Screenshot from 2019-11-13 11-42-24](https://user-images.githubusercontent.com/167821/68798125-b38ca500-060a-11ea-8595-861b258e888d.png)

Also that part of the copyright box wasn't actually changed in brave/brave-core#3828 so I'm guessing it's always been like this (and different on Mac v. Linux?).

**Comment by fmarier** [comment]
Windows shows "Brave Software" like Mac:
![Screenshot from 2019-11-13 13-18-03](https://user-images.githubusercontent.com/167821/68805168-189ac780-0618-11ea-9049-c64b46cac891.png)

**Comment by yrliou** [comment]
FYI I would think it was replaced by this line, and has been around for quite some time: https://github.com/brave/brave-browser/blob/master/lib/l10nUtil.js#L163, but not sure why it's not the case on Linux.

**Comment by fmarier** [comment]
I'll include a fix for that as part of https://github.com/brave/brave-browser/pull/6771 / https://github.com/brave/brave-core/pull/3881.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.38 Chromium: 78.0.3904.108 (Official Build) nightly (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3881

![image](https://user-images.githubusercontent.com/34715963/69808278-71a55680-11e7-11ea-9f49-999edb09c3aa.png)
