### ISSUE TITLE
Fresh install, signed-in to Uphold and balance is not shown until brave://rewards page is refreshed

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#6886]
## Description 

Fresh install, signed-in to Uphold and balance is not shown until brave://rewards page is refreshed

## Steps to Reproduce

   1. Fresh install
   2. Sign-in to previously verified Uphold account

## Actual result:

The balance is not updated until brave://rewards page is refreshed

## Expected result:
The balance should be updated

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.81 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4007

![image](https://user-images.githubusercontent.com/34715963/71755547-618a3200-2e8b-11ea-99de-396f1c9ce448.png)
