### ISSUE TITLE
co2

### ISSUE THREAD

**Issue by SustDig** [brave/brave-browser#6887]
## Description 
on brave-startup, an optional page is shown, enabling you to see how much ads and trackers were blocked until now. so far so great. 
wouldnt it be nice if **an additional info** would show you **how much co2 were saved** through this? this is not a trivial thing, sure, even if it sounds that way.  a current trend in european computing is to quantify exactly an average co2-footprint-scenario of each everyday-online-things (streaming, social-networks) a.s.o. - why not do so for tracking-/ad-networks?

- a first hint could be studies on the average co2-footprint of each mail you sent (studies by greenpeace and others)
- another hint is a firefox-extension: https://github.com/supertanuki/Carbonalyser
- if the first real studies here should appear - and brave-development could be avantgarde here, not only in the problem-constitution, but also in the solution - it would be highly expectable that real figures from the networks itself could appear and could be incorporated (in the long run even leading to some form of low-carbon-footprint-certificates for ad-/tracking-networks - and you could lead their development too).
- nice next steps could be imagined: what is the exact carbon-footprint of the current you-do-it-for-me-attitude of incorporating all this bunch of google-analytics, external fonts, external javascript-libraries in nearly all internet-pages
- while being one of the top privacy browsers currently, you could gain leadership in an not-yet-really-existing field of greenbrowsing - or you could even be the first coining the term.

## Steps to Reproduce
   1. open the app, co2-footprint of browsing is not shown

## Actual result:
co2-footprint of blocked Ads and trackers not shown.

## Expected result:
co2-footprint of blocked Ads and trackers should be calculated here

## Reproduces how often: 
infinite until new feature

## Brave version (brave://version info)
git latest beta channel

## Version/Channel Information:
same

## Other Additional Information:
none

**Comment by rebron** [comment]
@SustDig Thanks for the suggestion and your energy around this topic. Closing as wontfix though as this would be better suited (and tested out more) as an Extension. Those who are passionate about tracking co2 savings can then use that extension. 

As far as marketing as a "green browser", not something we're planning on doing and would confuse our messaging. If you'd like to keep this discussion going or have other ideas, https://community.brave.com/ is a good place for it.

**Comment by SustDig** [comment]
from a technical perspective, you could simply cross-check each opened site locally by including the information https://www.websitecarbon.com delivers for this site and add its information to an internal data which could be shown as a sum in the dashboard. This should be done in max. 1 hour - if you have the will to do so. 
The Dashboard could be a nice place for an option to show this information - as part of the stats, after you enabled "'co2-footprint-overview'-option in stats", f.e.
