### ISSUE TITLE
Missing notEnoughTokensLink string in tipping panel

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6888]
This is a very recent regression , introduced between 0.71.114 and  0.71.115

## Steps to Reproduce

   1. Clean install
   2. Open Brave
   3. Enable Rewards
   4. Open `kjozwiak.github.io`
   5. Open tip panel
   6. Select more BAT than you currently have

## Actual result:

![image](https://user-images.githubusercontent.com/34715963/68674640-854d8d80-0556-11ea-9fe4-2baa45ce5a9d.png)
![image](https://user-images.githubusercontent.com/34715963/68674650-8bdc0500-0556-11ea-8037-e5ee24d4f24b.png)

## Expected result:
![image](https://user-images.githubusercontent.com/34715963/68674867-0016a880-0557-11ea-9312-a6c849328f81.png)
![image](https://user-images.githubusercontent.com/34715963/68674853-fa20c780-0556-11ea-86f1-dcb6696c80b8.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Reproducible on

Brave | 0.71.115 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Ubuntu 18.04 LTS

Not reproducible on

Brave | 0.71.114 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}

cc @brave/legacy_qa @rebron @mkarolin @ryanml  @mandar-brave

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows 10 x64 - `0.71.115`

**Comment by LaurenWags** [comment]
Reproduced on macOS

Brave | 0.71.115 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

<img width="991" alt="Screen Shot 2019-11-12 at 9 26 14 AM" src="https://user-images.githubusercontent.com/28145373/68679800-8cf93c00-052e-11ea-9076-195aaf34e81f.png">

**Comment by kjozwiak** [comment]
@NejcZdovc once this is fixed, can someone do a quick check locally that it actually works before uplifting?

**Comment by NejcZdovc** [comment]
@kjozwiak @mkarolin confirmed that it worked on slack

**Comment by NejcZdovc** [comment]
done in https://github.com/brave/brave-core/pull/3981

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.71.116 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified STR from description
English (US):
<img width="1179" alt="EN-US" src="https://user-images.githubusercontent.com/28145373/68718790-44667080-0578-11ea-8333-2071b3710e6d.png">

English (UK):
<img width="1019" alt="Screen Shot 2019-11-12 at 6 09 05 PM" src="https://user-images.githubusercontent.com/28145373/68718787-429cad00-0578-11ea-92f6-4c7bee2d7ea1.png">

Russian:
<img width="1191" alt="Russian" src="https://user-images.githubusercontent.com/28145373/68718781-3fa1bc80-0578-11ea-9185-d4db4e00dedb.png">

* Confirmed Japanese still does not show the link
<img width="1181" alt="Japanese" src="https://user-images.githubusercontent.com/28145373/68718770-3d3f6280-0578-11ea-98ee-343e86296d78.png">
