### ISSUE TITLE
Please allow custom UI element colors

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#689]
Possibly a duplicate of https://github.com/brave/brave-browser/issues/670 (cc: @petemill)

Carried over from https://github.com/brave/browser-laptop/issues/2057

> Vivaldi has recently added a very nice theme function which includes rounding tab corners/UI elements and adding different colors to different UI elements.
> 
> This would be cool to have in Brave too.
> 
> Take a look to the way Vivaldi team has done it as inspiration ;)
> 
> https://vivaldi.net/en-US/teamblog/121-snapshot-1-3-501-6-customizable-ui-themes

**Comment by petemill** [comment]
How does this differ from normal theme extensions which allow custom colors? Note, that the Vivaldi link is not working - it just redirects to the Vivaldi blog homepage.

**Comment by bsclifton** [comment]
@petemill good question- there were also some posts in community. Likely we can close this issue as we should have theming support; and it appears #670 covers things which may be missing from theme support
- https://community.brave.com/t/gray-is-so-depressing/2091
- https://community.brave.com/t/add-dark-theme-please/3432 
- https://community.brave.com/t/persona-theme-skin/7450
