### ISSUE TITLE
right click option for Private Window - consider updating UK English capitalization - follow up to 6872

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#6891]
## Description 
Found while testing #6872 

When right clicking on a link to get context menu, consider capitalizing 'Link' and 'Window' to match other options displayed (also would match US English).

## Steps to Reproduce

   1. Clean profile UK English
   2. Navigate to a site with a link.
   3. Right click on link.

## Actual result:
'Link' and 'Window' for 3rd option are not capitalized but they are capitalized in adjacent options.
<img width="1243" alt="Screen Shot 2019-11-12 at 10 15 33 AM" src="https://user-images.githubusercontent.com/28145373/68685097-93d87c80-0537-11ea-97b8-2785e45e03e0.png">

## Expected result:
<img width="307" alt="Screen Shot 2019-11-12 at 10 32 31 AM" src="https://user-images.githubusercontent.com/28145373/68685201-c4201b00-0537-11ea-8d64-11636a5b6b0e.png">

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.71.115 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @petemill

**Comment by GeetaSarvadnya** [comment]
Verified in Windows 10 x64 - 0.71.115 - In windows `p` and `w` are small letters in both Hamburger menu and context menu

Hamburger menu:
![image](https://user-images.githubusercontent.com/38657976/68694888-054c1580-05a0-11ea-8808-caf4a5cfebdd.png)

Context menu
![image](https://user-images.githubusercontent.com/38657976/68694962-21e84d80-05a0-11ea-91e5-4b49a3b035d9.png)

**Comment by bsclifton** [comment]
Fixed in 0.71 with https://github.com/brave/brave-core/pull/3982

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.71.116 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified STR from description
<img width="1275" alt="Screen Shot 2019-11-12 at 6 04 50 PM" src="https://user-images.githubusercontent.com/28145373/68718349-f309b180-0576-11ea-862e-7f13ec98e9f2.png">
