### ISSUE TITLE
Extra space between refresh icon & bookmark icon AND rewards icon & plugins icon

### ISSUE THREAD

**Issue by praneethkumarpidugu** [brave/brave-browser#6892]
## Description 

From a User Experience Perspective, there is an extra space
1. between refresh icon and bookmark icon
2. between brave rewards icon and any plugins installed.

## Steps to Reproduce

   1.  Just install any plugin for example metamask.
   2. View the extra space mentioned in the description above.

## Actual result:

As pointed with white arrows in the below screenshot, I am seeing extra space 
![extra space in from User experience perspective](https://user-images.githubusercontent.com/10872354/68691840-6ba24b00-0542-11ea-8dc3-e9b5e1808a77.jpg)

## Expected result:
- It would be ideal if we don't see any extra space at the following UI Components :-
1. between refresh icon and bookmark icon
2. between brave rewards icon and any plugins installed.

## Reproduces how often: 

Every time I open a new window I still the see the extra space issue

## Brave version (brave://version info)

Brave | 0.70.123 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.12.6 (Build 16G29)
JavaScript | V8 7.8.279.23
Flash | (Disabled)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes, this is not from github releases but I downloaded this version from https://brave.com/download/
- Can you reproduce this issue with the beta channel?
N/A
- Can you reproduce this issue with the dev channel?
N/A
- Can you reproduce this issue with the nightly channel?
N/A
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
@praneethkumarpidugu there is an option under brave://settings/appearance where you can enable a `Wide address bar`. This will fill that empty area 😄 
<img width="1107" alt="Screen Shot 2019-11-12 at 10 22 38 AM" src="https://user-images.githubusercontent.com/4733304/68694539-925a8480-0536-11ea-85a4-d9bdc188ac01.png">

Does this solve the issue for you?

**Comment by praneethkumarpidugu** [comment]
@bsclifton Yes :D Sorry for raising this is as an issue. Because when I first downloaded it I saw the wide address bar by default.

**Comment by bsclifton** [comment]
@praneethkumarpidugu I personally would prefer the wide address bar by default 😄 I'm curious what others think

cc: @bradleyrichter @karenkliu @rebron

**Comment by karenkliu** [comment]
I'm not opinionated enough about the width of the address bar to change the default; since I'm a big bookmarks user the chrome area up top feels information dense no matter how the address bar looks.

I guess I would say that if a lot of people think this 'extra space' looks like a bug, then we need the extra space to be more purposeful than it is now. In other words, the design doesn't seem to communicate why there is extra space around the sides. So if we need really want the extra space to "help the address bar breath" and "differentiate us from other browsers", then we need to go bolder with the design treatment. maybe have an *even bigger* address bar with breathing space around the sides. Maybe move some buttons around.

**Comment by efjacobson** [comment]
Just started using brave on my desktop, definitely thought it was a bug. Mine is wider than the provided original. Still not sure what it would be used for.

![Capture](https://user-images.githubusercontent.com/6315388/70963997-0ceb5800-203f-11ea-9384-e515537ff0c5.PNG)
