### ISSUE TITLE
Not enough tokens message is overlapping on the monthly tip text in the Spanish locale

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#6898]
## Description 

Not enough tokens message is overlapping on the monthly tip text in the Spanish locale
## Steps to Reproduce

   1. Set OS locale to Spanish (Spain)
   2. Clean profile 0.70.123 or 0.71.116
   3. Enable rewards and open kjozwiak.github.io in a new tab
   4. Open tip panel
   5. Select more BAT than you currently have

## Actual result:

Not enough tokens message is overlapping on the monthly tip text in the Spanish locale
![image](https://user-images.githubusercontent.com/38657976/68747574-d1650480-0620-11ea-91cb-9d9d0a5223b3.png)

## Expected result:

Not enough tokens message should not overlap on the monthly tip text in the Spanish locale
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 0.71.116 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
closing as we don't have this UI anymore
