### ISSUE TITLE
Setting: use Tor for all private tabs

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#690]
Carried over from https://github.com/brave/browser-laptop/issues/14637
> I've been using Brave + Tor for only a couple of days and I already find it tiring to enable Tor-mode for every time I open a new private tab. More importantly, I sometimes forget about turning it on, only to find out when it's already too late.
>
> Having a check box under the Tor mode toggle button that remembers my choice would be super duper!

**Comment by lukemulks** [comment]
Dreaming a bit here - but do we have enough data/feedback to just use Tor for all private tabs (by default)?

Seems like the feature has been around for long enough to make a case for default adoption, and it's a beautiful differentiator for us.

**Comment by tomlowenthal** [comment]
Private tabs and private tabs with Tor are available side by side everywhere. There's no need for a toggle behavior — reaching either one is equally easy.

**Comment by bbondy** [comment]
Marking invalid milestone since no code was accepted for this issue.
