### ISSUE TITLE
chrome://wallet is blocked when Brave Wallet is disabled

### ISSUE THREAD

**Issue by aussiechief** [brave/brave-browser#6903]
## Description 
The chrome://wallet (brave://wallet) page is blocked if Brave Wallet is turned off in Extension options.

## Steps to Reproduce
   1. Go to chrome://settings/extensions
   2. Switch"Brave Wallet" to off
   3. Click "Crypto Wallets" in the top Settings navigation menu _OR_ go to chrome://wallet

## Actual result:
`ERR_BLOCKED_BY_CLIENT`

[Link to screenshot 1](https://i.imgur.com/UrttMJ4.png)
[Link to screenshot 2](https://i.imgur.com/7TFjNpi.png)

## Expected result:
The "Crypto Wallets" Settings navigation menu item should be hidden when Brave Wallets is disabled (#6393). Chrome://wallet should redirect to chrome://rewards or a different page.

## Reproduces how often: 
Each time

## Brave version (brave://version info)
Brave: 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)
Revision: 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS: Windows 10 OS Version 1903 (Build 18362.476)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes (Version 1.0)
- Can you reproduce this issue with the beta channel?
Not checked
- Can you reproduce this issue with the dev channel?
Not checked
- Can you reproduce this issue with the nightly channel?
Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
NA

**Comment by szaimen** [comment]
I would also like to see this implemented. 
It is a little bit annoying that the button on the top doesn't get hidden automatically. 
Also when disabling Brave Wallet, it should ask for a restart: https://github.com/brave/brave-browser/issues/6902

**Comment by bbondy** [comment]
This will be deprecated with this work so closing this issue since it'll be handled there:
https://github.com/brave/brave-browser/issues/7503
