### ISSUE TITLE
NTP Fall 2019 wallpapers

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#6904]
## Description
Swap out all of our current wallpapers on the new tab with a fresh set of images. Purpose:
- prevent the images from feeling stale
- give other photographers/creators a chance to showcase their work
- it's fun

## Designs
![wallpaper preview](https://user-images.githubusercontent.com/2388823/68795010-efbd0700-0604-11ea-9584-4d5a2624c437.jpg)

## Assets
compressed JPG and WEBP 
[image assets.zip](https://github.com/brave/brave-browser/files/3843014/image.assets.zip)

photo creds + links
[attribution.pdf](https://github.com/brave/brave-browser/files/3843017/attribution.pdf)

## Test plan
Images should match those shown in https://docs.google.com/document/d/1Le1F2G4m04ui-D3GbDkYttKY9q4Hjy-JCOEVujYTyxM/edit
(ones in red should not be showing)

**Comment by karenkliu** [comment]
Maybe apply this .webp compression method in https://github.com/brave/brave-core/pull/3735 as well

**Comment by jhreis** [comment]
I put all the data together in a JSON file. @karenkliu if you could review this data, just for a second pair of eyes that would be great.

Also, do we have a website for "Louis Kim"?

[ntp-data.json.zip](https://github.com/brave/brave-browser/files/3865799/ntp-data.json.zip)

**Comment by karenkliu** [comment]
@jhreis We're still waiting on a link from Louis Kim; he's been traveling and says he can get it to us "tonight". So I'll post that link here tomorrow.

I checked out the JSON file and noticed a couple things:

- They all have center set at '0' except for `xavier-balderas-cejudo.jpg`, which set at `2560`; is that a mistake?
- I'd like to help determine what should be the portrait center for these images, how do I do that?
- `oliwier gesla.jpg` is the only file name with a space in it; is that going to be a problem? My bad for overlooking that when I was exporting stuff.

**Comment by jamesmudgett** [comment]
```center points for mobile portrait:

A - 1280
B - 1630
C - 1277
D - 1975
E - 815
F - 1160
G - 988
H - 682
I - 0
J - 480
K - 1200
L - 780
M - N/A
N - 2185
O  - 1205
P - 1330
```

**Comment by jhreis** [comment]
I updated the above JSON file with the center points. Thanks @jamesmudgett

**Comment by karenkliu** [comment]
@jhreis The attribution link for Louis Kim is  `louiskimphotography.com`

**Comment by deeppandya** [comment]
@karenkliu link **louiskimphotography.com** doesn't work. can you check with the artist ?

**Comment by karenkliu** [comment]
Sure, I sent them a message. Will post when they get back to me.

**Comment by karenkliu** [comment]
@deeppandya Please go ahead and use that same link. Louis said:

> There was a problem with domain mapping. I checked again with my hosting service and they did a manual intervention. Should be up in 24-48 hours.

**Comment by fmarier** [comment]
@karenkliu Do you still have a record of the URLs where you downloaded the images?

I'm asking because, in addition to the photographer's attribution link, we now also keep track of the image URL and the license: https://github.com/brave/brave-core/blob/master/components/brave_new_tab_ui/data/LICENSE

(This is now visible in `brave://credits` under "Background images".)

**Comment by karenkliu** [comment]
@fmarier Sure, here you go:
[2019-11 photo attribution and license.pdf](https://github.com/brave/brave-browser/files/3893914/2019-11.photo.attribution.and.license.pdf)

**Comment by fmarier** [comment]
Thanks @karenkliu . In terms of the URLs in the LICENSE file (as opposed to the attribution link, which you've got covered already in your PDF), it's best to use the ones where we got the image from.

For this batch of images, here's what I was able to find:

1: https://unsplash.com/photos/uwbajDCODj4
2: https://unsplash.com/photos/mawU2PoJWfU
3: https://unsplash.com/photos/4knR_YzeUVc
*4: (https://unsplash.com/photos/C9jP5AlgcuQ or https://unsplash.com/photos/ivU6tleiHN4?)*
5: https://unsplash.com/photos/sfgH9dXcMRw
6: https://www.benkarpinski.com/iceland/nrbhh4tavlgx7hvpyro9b9b8uhr05l
7: https://gradivis.com/wp-content/uploads/2019/01/SanDiego-32-small.jpg
8: https://unsplash.com/photos/4xv3lqnanYc
*9: (not sure, website is down)*
10: https://unsplash.com/photos/veMnvjmfoxw
11: https://www.instagram.com/p/BwgJrCZg2of/
*12: (doesn't appear to be on Instagram anymore? closest one is https://www.instagram.com/p/BxfxyiJoBiU/)*
13: https://www.instagram.com/p/BRUB7ZSB5cK/
14: https://www.instagram.com/p/BjbiL0ElxdR/
15: https://unsplash.com/photos/kxIE049IZ1g

**Comment by karenkliu** [comment]
@fmarier Ah okay, got it - I'll do that for next time. This is what I think is right:

1: https://unsplash.com/photos/uwbajDCODj4
2: https://unsplash.com/photos/mawU2PoJWfU
3: https://unsplash.com/photos/4knR_YzeUVc
4: https://unsplash.com/photos/C9jP5AlgcuQ
5: https://unsplash.com/photos/sfgH9dXcMRw
6: Contributor sent the hi-res version through email
7: Contributor sent the hi-res version through email
8: https://unsplash.com/photos/4xv3lqnanYc
9: Contributor sent the hi-res version through email
10: https://unsplash.com/photos/veMnvjmfoxw
11: Contributor sent the hi-res version through email
12: Contributor sent the hi-res version through email
13: Contributor sent the hi-res version through email
14: Contributor sent the hi-res version through email
15: https://unsplash.com/photos/kxIE049IZ1g

As you can see, the URLs in the license file are only available for Unsplash images. The images we selected from direct contributor submissions were not acquired through a link - the contributor supplied us with a high-resolution image to use directly through email. A lot of times the images shown on a photographer's site are not high enough resolution for us to use as a wallpaper because they don't want unauthorized use of their images, so we reached out to them directly to acquire those images. I don't think a URL in the license file would be applicable for those direct contributor submissions.

**Comment by fmarier** [comment]
> A lot of times the images shown on a photographer's site are not high enough resolution for us to use as a wallpaper because they don't want unauthorized use of their images, so we reached out to them directly to acquire those images. I don't think a URL in the license file would be applicable for those direct contributor submissions.

Ah good point. I didn't realize they were emailing them to us directly.

I wonder what would be most useful to show in the LICENSE file then. Maybe the low-res image from the photographer's website/Instagram so that people can see where we sourced the images (understanding it may not the exact version that we put in Brave)? The nice thing about having a URL is that you can discover other photos from that photographer or comment on it, but I guess people already do that with the attribution link after finding the exact photo.

Anyways, the point of this is not to create more work for ourselves, just to keep track of where things are from. What would you think about this (for next time):

1. If we find a photo (low-res or high-res) on a website / Instagram, then we can link to it from the LICENSE file -- we basically just note the URL where we originally found it.
2. If we get emailed a photo directly (i.e. we didn't find it, it came to us), then we can list it as "sent by contributor through email".

**Comment by karenkliu** [comment]
@fmarier That sounds good to me! For this round I think "sent by contributor through email" would suffice

**Comment by cezaraugusto** [comment]
@fmarier do you think we should update some file/license file after this work lands? I should have a PR open soon with this update.

**Comment by fmarier** [comment]
> Do you think we should update some file/license file after this work lands? I should have a PR open soon with this update.

Yes, you can simply update the licensing info in https://github.com/brave/brave-core/blob/master/components/brave_new_tab_ui/data/LICENSE within the same PR.

**Comment by cezaraugusto** [comment]
@fmarier thanks, PR is up https://github.com/brave/brave-core/pull/4264, tagged you as reviewer as well.

**Comment by bsclifton** [comment]
Reverted with https://github.com/brave/brave-core/pull/4357

Better quality images provided with https://github.com/brave/brave-core/pull/4327

Still a few that need fixing though

**Comment by karenkliu** [comment]
Here are updated versions of the 4 images that people mentioned as having been over-compressed:
JPG and WEBP assets
[image assets_quality.zip](https://github.com/brave/brave-browser/files/4055602/image.assets_quality.zip)


![annie-spratt-min](https://user-images.githubusercontent.com/2388823/72288847-c87fb780-35fe-11ea-8432-fb1d2b938147.jpg)
![louis-kim-min](https://user-images.githubusercontent.com/2388823/72288848-c87fb780-35fe-11ea-9082-02769fdef0e3.jpg)
![oliver gesla-min](https://user-images.githubusercontent.com/2388823/72288849-c87fb780-35fe-11ea-9590-a970c2f25f56.jpg)
![xavier-balderas-cejudo-min](https://user-images.githubusercontent.com/2388823/72288850-c9184e00-35fe-11ea-9273-383de5d4d2af.jpg)

File sizes are larger than original but hopefully with less noticeable compression artifacts.

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` for now since https://github.com/brave/brave-core/pull/4398 was reverted.

**Comment by bsclifton** [comment]
@LaurenWags it should be there actually- I did open a revert, but we fixed a different way 😄 Let me make a note there (my bad)

**Comment by kjozwiak** [comment]
@bsclifton @rebron @cezaraugusto @karenkliu just double checking, these are the expected images correct?

```* https://raw.githubusercontent.com/brave/brave-core/8c4bcfee376033fe8d5528f00657b3b603c16d8c/components/img/newtab/backgrounds/anders-jilden.webp
* https://raw.githubusercontent.com/brave/brave-core/8c4bcfee376033fe8d5528f00657b3b603c16d8c/components/img/newtab/backgrounds/andreas-gucklhorn.webp
* https://raw.githubusercontent.com/brave/brave-core/8c4bcfee376033fe8d5528f00657b3b603c16d8c/components/img/newtab/backgrounds/andy-mai.webp
* https://raw.githubusercontent.com/brave/brave-core/8c4bcfee376033fe8d5528f00657b3b603c16d8c/components/img/newtab/backgrounds/anton-repponen.webp
* https://raw.githubusercontent.com/brave/brave-core/8c4bcfee376033fe8d5528f00657b3b603c16d8c/components/img/newtab/backgrounds/ben-karpinski.webp
* https://raw.githubusercontent.com/brave/brave-core/8c4bcfee376033fe8d5528f00657b3b603c16d8c/components/img/newtab/backgrounds/joe-gardner.webp
* https://raw.githubusercontent.com/brave/brave-core/8c4bcfee376033fe8d5528f00657b3b603c16d8c/components/img/newtab/backgrounds/matt-palmer.webp
* https://raw.githubusercontent.com/brave/brave-core/8c4bcfee376033fe8d5528f00657b3b603c16d8c/components/img/newtab/backgrounds/svalbard-jerol-soibam.webp
* https://raw.githubusercontent.com/brave/brave-core/8c4bcfee376033fe8d5528f00657b3b603c16d8c/components/img/newtab/backgrounds/will-christiansen-glacier-peak.webp
* https://raw.githubusercontent.com/brave/brave-core/8c4bcfee376033fe8d5528f00657b3b603c16d8c/components/img/newtab/backgrounds/will-christiansen-ice.webp```

**Comment by rebron** [comment]
* https://raw.githubusercontent.com/brave/brave-core/8c4bcfee376033fe8d5528f00657b3b603c16d8c/components/img/newtab/backgrounds/anders-jilden.webp

**Comment by kjozwiak** [comment]
Thanks @rebron 👍Missed it when copying/pasting the list I pasted into the uplift channel on Slack.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.3 x64 Catalina` using the following build:

```
Brave | 1.7.76 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.15.3 (Build 19D76)
```

* Went through https://docs.google.com/document/d/1Le1F2G4m04ui-D3GbDkYttKY9q4Hjy-JCOEVujYTyxM/edit and ensured that all the correct images were appearing and ensured that the correct links were being used
* ensured that the images that were removed weren't being displayed/cycled through
* `Will Christiansen` credit links are not working as per https://github.com/brave/brave-browser/issues/8848

**Comment by kjozwiak** [comment]
@rebron @SergeyZhukovsky @aekeus should these make their way into `Android` as well? If so, can you please add the `OS/Android` tag for this issue?

**Comment by rebron** [comment]
NTP wallpapers are already updated on Android, so no additional work for android here.
