### ISSUE TITLE
Security: brave-extension CSP permissions are not very restrictive

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#691]
https://github.com/brave/brave-extension/blob/master/app/manifest.dev.json#L22 - why does this require `unsafe-eval`?

https://github.com/brave/brave-extension/blob/master/app/manifest.prod.json#L22 - does this need style-src set to `*`? are we loading stylesheets from arbitrary origins?

cc @cezaraugusto

**Comment by bbondy** [comment]
I don't think there's any reason not to make it more restrictive.  It probably came in from a Chrome extension with redux template.

**Comment by Snuupy** [comment]
cc: https://github.com/brave/brave-extension/pull/55#issuecomment-415213073
