### ISSUE TITLE
Add adp-xfiles license

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#6910]
Now that abp-xfiles has added a LICENSE file to the repo (https://github.com/gioxx/xfiles/issues/7), we should add it to brave-core.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.38 Chromium: 78.0.3904.108 (Official Build) nightly (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3991

![image](https://user-images.githubusercontent.com/34715963/69795171-f2eef000-11cb-11ea-9f4c-1637d18fd5f8.png)

**Comment by LaurenWags** [comment]
@fmarier not seeing this on macOS, is this expected? not sure if this license is OS specific?
<img width="1193" alt="Screen Shot 2020-01-07 at 11 38 38 AM" src="https://user-images.githubusercontent.com/28145373/71911759-4f85e900-3142-11ea-8151-e823a6772cb6.png">


Brave | 1.3.85 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | macOS Version 10.14.6 (Build 18G103)

**Comment by fmarier** [comment]
@LaurenWags The behavior when https://github.com/brave/brave-browser/issues/7150 got fixed and uplifted.

The license for ABP X Files is now in the "Brave Ad Block" section:

![Screenshot from 2020-01-07 11-14-58](https://user-images.githubusercontent.com/167821/71922045-02544800-313f-11ea-9405-b7b492e7aad6.png)

**Comment by LaurenWags** [comment]
gotcha, thanks @fmarier !
