### ISSUE TITLE
Updating Brave removes repo file

### ISSUE THREAD

**Issue by sasannnn** [brave/brave-browser#6912]
## Description 

Every time I update Brave, post-install script removes the repo file I've put in `/etc/apt/sources.list.d/brave-browser.list`

## Steps to Reproduce

   1. Install brave with repo file named `brave-browser.list`
   2. Brave won't update since `brave-browser.list` has been removed

## Brave version (brave://version info)

```
Brave | 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Linux
```

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by bsclifton** [comment]
cc: @mbacchi @fmarier

**Comment by fmarier** [comment]
I was able to reproduce this.

I found that the [function which removes the repo](https://cs.chromium.org/chromium/src/chrome/installer/linux/common/apt.include?l=268-277&rcl=2635bf008a465f50402cbddf727ab6ebf83286d3) gets [called from the `postrm` script](https://cs.chromium.org/chromium/src/chrome/installer/linux/debian/postrm?l=32-33&rcl=2635bf008a465f50402cbddf727ab6ebf83286d3).

Given that we disabled the addition of that repo in #1084, we also need to disable its removal.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.5.106 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4291

Before installing Brave
![image](https://user-images.githubusercontent.com/34715963/75788135-134cbe80-5d68-11ea-8c35-a099901fa429.png)

After installing Brave
![image](https://user-images.githubusercontent.com/34715963/75789450-03ce7500-5d6a-11ea-8437-8eb3f3504425.png)
