### ISSUE TITLE
`Set Contribution` button border/edge is shown when wallet balance is zero

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#6914]
## Description 

`Set Contribution` button border is shown when wallet balance is zero. `Set Contribution` button edge needs to be removed.

## Steps to Reproduce

   1. Clean profile
   2. Open DDG
   3. Open BR panel
   4. Click on Monthly Contributions button `Set...`
    

## Actual result:

`Set Contribution` button border/edge is shown when wallet balance is zero
![image](https://user-images.githubusercontent.com/38657976/68847710-178b9800-06f5-11ea-82c2-ea2dc968a5d6.png)

## Expected result:
`Set Contribution` button border is shown when wallet balance is zero. `Set Contribution` button edge needs to be removed.

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.72.124 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @NejcZdovc @brave/legacy_qa

**Comment by NejcZdovc** [comment]
it overlaps as you can't set monthly contribution if you don't have enough funds. This is not a bug. We have same logic on one time tip

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc Agree with you. changing the subject of the issue. In case of one-time tip, `Send Tip` button isn't shown completely when wallet balance is zero (as shown in below screenshot)
![image](https://user-images.githubusercontent.com/38657976/68848953-2e32ee80-06f7-11ea-8c53-7f1071d9ae97.png)

In case of monthly tip `Set Contribution` button border is shown, that looks odd that should be removed.

**Comment by LaurenWags** [comment]
cc @mandar-brave @alexwykoff as this relates to the tipping efficiency changes

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.9.44 Chromium: 81.0.4044.122 (Official Build) dev (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/5218 
![image](https://user-images.githubusercontent.com/38657976/80701842-b23e2e80-8afd-11ea-9884-631d9ea18104.png)
