### ISSUE TITLE
`Send Tip` alignment issue in beta build 0.72.x

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#6915]
## Description 

`Send Tip` alignment issue in beta build 0.72.x

## Steps to Reproduce

   1. Clean profile staging
   2. Enable rewards and claim grants
   3. Open DDG 
   4. Open BR panel and click on `SEND A TIP`
   5. `Send Tip` button isn't aligned with other Tip amount buttons

## Actual result:

`Send Tip` button isn't aligned with other Tip amount buttons
![image](https://user-images.githubusercontent.com/38657976/68846857-b7482680-06f3-11ea-8ed6-462393d705ba.png)

## Expected result:
`Send Tip` button should be aligned with other Tip amount buttons

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.72.124 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @NejcZdovc @brave/legacy_qa

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya tip is aligned to center with new design

**Comment by GeetaSarvadnya** [comment]
cc: @bradleyrichter @karenkliu

**Comment by karenkliu** [comment]
@jenn-rhim

**Comment by NejcZdovc** [comment]
closing as this is the latest design
