### ISSUE TITLE
Change InsertOrUpdate to batch insert

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#6917]
Right now we have a lot of `InsertOrUpdate` in database folder. This are one of inserts. We see on multiple places that we would need batch insert. To keep things consistent let's change all of them into batch insert. This way you can have vector with one record or million .

**Comment by yachtcaptain23** [comment]
Inside `publisher_server_list.cc`, 

```

  for (auto& item : *publishers) {
    base::ListValue* values = nullptr;
    if (!item.GetAsList(&values)) {
      continue;
    }

    auto publisher = ledger::ServerPublisherInfo::New();
```

Repeatedly calls malloc. I don't have benchmarks but seems like a major culprit too.

**Comment by yachtcaptain23** [comment]
In `database_server_publisher_info.cc`, we can optimize the kind of inserts we're doing, which from past experience will make a huge difference

```
void DatabaseServerPublisherInfo::InsertOrUpdatePartialList(
    const std::vector<ledger::ServerPublisherPartial>& list,
    ledger::ResultCallback callback) {

  const std::string query = base::StringPrintf(
      "INSERT OR REPLACE INTO %s "
      "(publisher_key, status, excluded, address) "
      "VALUES (?, ?, ?, ?)",
      table_name_);

  auto transaction = ledger::DBTransaction::New();
  for (const auto& info : list) {
    auto command = ledger::DBCommand::New();
    command->type = ledger::DBCommand::Type::RUN;
    command->command = query;

    BindString(command.get(), 0, info.publisher_key);
    BindInt(command.get(), 1, static_cast<int>(info.status));
    BindBool(command.get(), 2, info.excluded);
    BindString(command.get(), 3, info.address);

    transaction->commands.push_back(std::move(command));
  }
```

Unless I'm mistaken, these are multiple inserts in one transaction rather than 1 insert
https://stackoverflow.com/questions/12365992/sql-insert-multiple-rows/12366023
