### ISSUE TITLE
Feature request: Paid subscription option

### ISSUE THREAD

**Issue by gatewaynode** [brave/brave-browser#6918]
I'd like to support the project/company and continue to see the browser succeed but the clever BAT system isn't at all appealing.  But I would happily pay a yearly subscription of $5 or $10 a year (maybe more?) just to ensure I have a privacy focused browsing solution that stays up to date and continues to evolve.

**Comment by rebron** [comment]
Closing. Forwarding to the team, thanks for the suggestion.
