### ISSUE TITLE
Would you please provided us bittorrent download brave browser?

### ISSUE THREAD

**Issue by netroby** [brave/brave-browser#6920]
Would you please provided us bittorrent download brave browser?

We want to download brave browser, but our network seems blocked aws download, and it's very hard to download your brave browser.

would you please provided bt download torrent. let us download brave browser more easy and quickly?

I am using windows 10 x64, need a magnet or .torrent to download brave browser.

**Comment by bsclifton** [comment]
cc: @mihaiplesa

**Comment by hspencer77** [comment]
Something that could work here - if we wanted to, we could leverage AWS S3 for this (especially given that `brave-browser-downloads bucket` is in `us-east-1`) - ref: https://docs.aws.amazon.com/AmazonS3/latest/dev/S3Torrent.html

**Comment by netroby** [comment]
Good to go, please provided it. thanks. Leave us an magnet link, we download it

**Comment by mihaiplesa** [comment]
@netroby `https://brave-browser-downloads.s3.brave.com/latest/BraveBrowserSetup.exe?torrent`

**Comment by netroby** [comment]
@mihaiplesa It works, And this one is just installer  1.23MB, need the offline installer , so we can install it without download package from the slow internet.

**Comment by mihaiplesa** [comment]
@netroby we currently only upload those to https://github.com/brave/brave-browser/releases, will discuss with the team.

Has the file completed download successfully?

**Comment by mihaiplesa** [comment]
Have added `https://brave-browser-downloads.s3.amazonaws.com/latest/BraveBrowserStandaloneSetup.exe?torrent` manually, will discuss with team about automation priority.

**Comment by rebron** [comment]
Closing. Discussed internally, we're not going to be doing this at this time. If we receive more requests we can reconsider.
