### ISSUE TITLE
Import from Chrome keep asking to close the browser

### ISSUE THREAD

**Issue by JacopoSciampi** [brave/brave-browser#6923]
## Description 
When trying to import the settings from Chrome a popup tell the user to close all the Chrome istances opened. Even with a sudo killall chrome the popup won't let me to import the data.

## Steps to Reproduce
1. Go to settings
2. import bookmarks and settings
3. select a profile from chrome

## Actual result:
As I said, even with no chrome istance open the popup just doesn't allow me to import those settings.

## Expected result:
I expect the settings to be imported

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Linux
JavaScript | V8 7.8.279.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=NewExtensionUpdaterService,PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,UnifiedConsent,AudioServiceOutOfProcess,SmsReceiver,SyncUSSBookmarks --flag-switches-begin --flag-switches-end
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/jacopo/.config/BraveSoftware/Brave-Browser/Default

**Comment by bsclifton** [comment]
@JacopoSciampi can you try the following?
Delete the file `~/.config/google-chrome/SingletonLock` and then try again

I'm not sure why, but sometimes this file gets left behind, which will prevent import. Only way to fix is to manually delete

We're tracking the automatic fixing of this with https://github.com/brave/brave-browser/issues/2049 😄
