### ISSUE TITLE
"Hide Brave Rewards Icon" now fails on iPad Pro

### ISSUE THREAD

**Issue by mcDingleHead** [brave/brave-browser#6924]
Turning on the "Hide Brave Rewards Icon" switch in Settings fails to eliminate the nag notification in the toolbar. This only seems to be an issue on my iPad Pro. The icon is properly hidden on my iPhone and desktop versions.

If this issue is permanent, I'd like to know so I can uninstall Brave. If it's a bug, any ETA on fix?

**Comment by bsclifton** [comment]
@mcDingleHead toggling that in Settings on iOS only hides if you disable rewards

You can disable rewards by clicking the Rewards triangle icon and then clicking "settings"
![IMG_0200](https://user-images.githubusercontent.com/4733304/68917333-a95bcb00-071e-11ea-8acf-76e29df0cf6d.jpg)

Another user was having trouble with this too, so I created an issue in the iOS GitHub repository (this is for the desktop product): https://github.com/brave/brave-ios/issues/1966

Let me know if that works! I'll close the issue, but you can continue to respond here

**Comment by kylehickinson** [comment]
@mcDingleHead Sorry, it's definitely unintentional and has been since fixed (https://github.com/brave/brave-ios/issues/1954) and will be available in the next version!  Thanks for reporting :)

**Comment by mcDingleHead** [comment]
thanks, bud. I'll wait for the update.
