### ISSUE TITLE
Please let us disable the adblocker with a new switch

### ISSUE THREAD

**Issue by szaimen** [brave/brave-browser#6927]
## Description 
Please let us disable the adblocker with a new switch.
When I want to only allow ads on one side but not trackers, I would like to change the behavior for ads apart from trackers and the whole shield.
To allow ads I don't want to be forced to disable shields completely.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Expected result:
it could look like this:
![image](https://user-images.githubusercontent.com/42591237/68881089-c8e9f800-070c-11ea-8db1-fbc5b25a3562.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by tomlowenthal** [comment]
Brave only blocks invasive ads and the trackers which go with them. The process of fetching the ads is part of what allows you to be tracked. Separating them doesn't really make sense.

**Comment by szaimen** [comment]
@tomlowenthal So maybe the spelling then has to improve:
I wouldn't know that the "tracker" toggle also blocks ads so that I am able to see ads if I disable it because it doesn't have the word "ads" in it. 
Shall I open a new issue to track it seperately?

**Comment by tomlowenthal** [comment]
I'm afraid not.
