### ISSUE TITLE
Brave 1.0.0 - Not Works Windows 8 (not 8.1)

### ISSUE THREAD

**Issue by liskaaaaaaaaaa** [brave/brave-browser#6930]
## Description 
brave browser dont works

## Steps to Reproduce

   1. install 
   2. done
   3. brave dont works

## Actual result:
[https://i.imgur.com/CO4ysQX.png](https://i.imgur.com/CO4ysQX.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Yes
- Can you reproduce this issue with the dev channel?
Yes
- Can you reproduce this issue with the nightly channel?
Yes

## Other Additional Information:
- Is the issue reproducible on the latest version of Chrome? 
No. Google Chrome is works. 

Windows 8 (not 8.1) 64bit
Please fix

**Comment by bsclifton** [comment]
@liskaaaaaaaaaa are you not able to upgrade to Windows 8.1? I believe Microsoft has completely stopped support of Windows 8, with extended support only available for 8.1

**Comment by liskaaaaaaaaaa** [comment]
@bsclifton 
brave support windows 8 [https://i.imgur.com/jqwqcVn.png](https://i.imgur.com/jqwqcVn.png)
Im from poland , many people have Windows 8 please fix problem ;///////

**Comment by bsclifton** [comment]
@liskaaaaaaaaaa what site is that? that doesn't look like brave.com?

I would ask that you upgrade to version 8.1 and try again please. This is the officially supported version by Microsoft and should be working
