### ISSUE TITLE
Brave 1.0.0 DNS over HTTPS flag missing from official release

### ISSUE THREAD

**Issue by magus186** [brave/brave-browser#6932]
## Description 
Was previously using the script "--enable-features="dns-over-https<DoHTrial" --force-fieldtrials="DoHTrial/Group1" --force-fieldtrial-params="DoHTrial.Group1:server/https%3A%2F%2F1.1.1.1%2Fdns-query/method/POST" to enable DNS over HTTPS, since rollout to 1.0.0 I am unable to get this script to work, also the flag is not available from brave://flags/#dns-over-https

## Steps to Reproduce

   1. Brave auto updated on last exit
   2. DNS over HTTPS is not functioning, flag is missing
   3. 

## Actual result:
![DNS](https://user-images.githubusercontent.com/55805616/68890448-c28b5a00-06d3-11ea-89bc-f8f17a212ac3.PNG)

## Reproduces how often: 
Everytime

## Brave version (brave://version info)

Brave | 1.0.0 Chromium: 78.0.3904.97 (Official Build) (32-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.950)

## Miscellaneous Information:
Using on a PC locked by admin, so unable to uninstall the release to try an older version. Any tips as to how to get DoH working again would be VERY much appreciated, thank you.

**Comment by fmarier** [comment]
We're hoping to enable the DoH "experiment" for all users soon: https://github.com/brave/brave-browser/issues/1864#issuecomment-548933021

**Comment by bsclifton** [comment]
Main feature request for DNS over HTTP tracked here:
https://github.com/brave/brave-browser/issues/1864

For what it's worth, it does show for me? 
<img width="907" alt="Screen Shot 2019-11-17 at 9 30 11 PM" src="https://user-images.githubusercontent.com/4733304/69024781-7cf3b900-0981-11ea-8ea2-5628a3c04797.png">

We should have field trials disabled, so all of the values in brave://flags should be the same, across installs

**Comment by bsclifton** [comment]
@magus186 can you visit brave://version and share? there shouldn't be any `variations` showing. If there are any, it's possible that either field trials was enabled? or that group policy is restricting things

Also, you should be able to view under the Hamburger menu (top right). If the very bottom says `Managed by your organization` then you know it's being locked down

**Comment by magus186** [comment]
Hi there, sure here is the version info in complete. 


Brave | 1.0.0 Chromium: 78.0.3904.97 (Official Build) (32-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.950)
JavaScript | V8 7.8.279.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Command Line | "C:\Users\XXXX\AppData\Local\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-features=dns-over-https<DoHTrial --force-fieldtrials=DoHTrial/Group1 --force-fieldtrial-params=DoHTrial.Group1:server/https%3A%2F%2F1.1.1.1%2Fdns-query/method/POST --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,NewExtensionUpdaterService,SimplifyHttpsIndicator,dns-over-https<DoHTrial --disable-features=AutofillServerCommunication,UnifiedConsent,AudioServiceOutOfProcess,SmsReceiver,LookalikeUrlNavigationSuggestionsUI,SyncUSSBookmarks,NotificationTriggers --flag-switches-begin --flag-switches-end

minus the paths. But there is something there that I just noticed looks off, "-https<DoHTrial --disable-"   So I just changed the target back to normal and here is the result


Brave | 1.0.0 Chromium: 78.0.3904.97 (Official Build) (32-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.950)
JavaScript | V8 7.8.279.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Command Line | "C:\Users\XXXX\AppData\Local\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,NewExtensionUpdaterService,SimplifyHttpsIndicator --disable-features=AudioServiceOutOfProcess,LookalikeUrlNavigationSuggestionsUI,SmsReceiver,AutofillServerCommunication,UnifiedConsent,NotificationTriggers,SyncUSSBookmarks --flag-switches-begin --flag-switches-end

But the flag is still missing. 

My version is not managed by group policy since I installed it myself (no mark on the Hamburger menu either), somehow I was able to get DoH to work by forcing the trial but now that doesn't seem to work anymore. I can still connect to 1.1.1.1 via traceroute so I know I haven't been blocked by group policy or something, so it's just strange...for comparison, my home PC has the flag as normal, same Brave build and version as I use at work.

**Comment by magus186** [comment]
Just a guess, but it may be possible that because the DNS settings on this computer are locked and managed by group policy, that Chromium doesn't allow the flag to be present. But it still worked before for quite a while since this DoH is only implemented through the browser, so hopefully there is another way to "force" the implementation.

**Comment by kontrolldkaos** [comment]
Any plans to include the list of resolvers from the Chromium experiment? https://www.chromium.org/developers/dns-over-https

```
**Providers in the mapping table**
For the experiment, we’ve intentionally kept the list small but reasonably diverse.
Here are the providers that we have selected in alphabetical order:
Cleanbrowsing
Cloudflare
Comcast
DNS.SB
Google
OpenDNS
Quad9
```

**Comment by fmarier** [comment]
Yes, as a first step we're planning to roll out the experiment to all Brave users without changing the list of supported resolvers from what Chrome is using.

**Comment by kontrolldkaos** [comment]
I do see Comcast is missing, https://github.com/brave/browser-android-tabs/blob/0538e1ba8e9f6278d31f088242a20a3741cfe79f/net/dns/dns_util.cc , are there plans to put Comcast's DoH endpoint as a DoH resolver?

**Comment by fmarier** [comment]
@kontrolldkaos Let's continue that discussion on the main issue we have open for DoH: https://github.com/brave/brave-browser/issues/1864#issuecomment-557217092

**Comment by rebron** [comment]
Closing. Per last comment let's move this over to #1864
