### ISSUE TITLE
`Toggle distilled page content` option is shown in all types of windows

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#6933]
## Description 

By default the `Toggle distilled page content` option is shown in all types of windows in brave. In chrome, the option is shown in the hamburger menu only when the extension is enabled from chrome://flags, after enabling reader mode extension, the toggle distilled page content option is shown in all the windows in chrome ( Normal/Guest/ incognito)

## Steps to Reproduce

   1. Open brave 0.72.x
   2. Open Normal window or Guest window or Private window or Private window with Tor
   3. Click on the hamburger menu
   4. `Toggle distilled page content` option is shown in all types of windows

## Actual result:

`Toggle distilled page content` option is shown in all types of windows
![image](https://user-images.githubusercontent.com/38657976/68890789-a6280580-0745-11ea-8640-a8255ab634f4.png)

## Expected result:
![image](https://user-images.githubusercontent.com/38657976/68890703-80026580-0745-11ea-8a88-ceda03168b99.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.72.124 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Even after enabling reader view extension in brave://flags the page content is not displayed in the reader view could be related to https://github.com/brave/brave-browser/issues/679

cc: @brave/legacy_qa @rebron @bsclifton

**Comment by bsclifton** [comment]
cc: @petemill who hid this before in C77 with https://github.com/brave/brave-core/pull/3397 (original issue was https://github.com/brave/brave-browser/issues/5951)

**Comment by rebron** [comment]
Closing. We're keeping the menu item.
