### ISSUE TITLE
Add migration flow for old grants to new promotions

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#6937]
Now that we switched to new promotions we need to migrate old promotions. 

What needs to happen is when in native lib we fetch promotions we need to add additional parameter to the fetch url `migrate=true`. This will fetch old promotions as well. After that we need to check parameter `legacyClaimed` and if it's true we skip attestation flow and just trigger claim process. Promotion should be automatically claimed.

**Comment by btlechowski** [comment]
Added `QA/Yes` as it contains test plan in https://github.com/brave/brave-core/pull/4101

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.3.92 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.14.6 (Build 18G103)

Scenario 1:
* Verified test plan from https://github.com/brave/brave-core/pull/4101 when claiming only a UGP grant on 1.0.0:
<img width="1192" alt="1 0 0-Claim UGP Grant only" src="https://user-images.githubusercontent.com/28145373/72463879-3d3f2700-37a2-11ea-87db-67ee1277f55c.png">

* Confirmed on upgrade to 1.3.x that BAT value remains the same:
<img width="1194" alt="1 0 0 ugp claim upgrade to 1 3 x" src="https://user-images.githubusercontent.com/28145373/72463892-43cd9e80-37a2-11ea-98c7-c546f7ed43e2.png">

* Also confirmed the parameters from the description showed in terminal:
`migrate=true` parameter:
```
[ REQUEST ]
> url: https://grant.rewards.bravesoftware.com/v1/promotions?migrate=true&paymentId=359a11cc-b2b6-4d76-9d5c-4845b9335275&platform=osx
> method: UrlMethod::GET
> content: 
> contentType: 
[ END REQUEST ]
```

`legacyClaimed` parameter:
```
[ RESPONSE - OnFetch ]
> time: 1579110026
> result: Success
> http code: 200
> response: {"promotions":[{"id":"36baa4c3-f92d-4121-b6d9-db44cb273a02","createdAt":"2019-10-30T23:17:15.681226Z","expiresAt":"2020-02-29T23:17:15.681226Z","version":5,"suggestionsPerGrant":70,"approximateValue":"17.5","type":"ugp","available":true,"platform":"desktop","publicKeys":["vNnt88kCh650dFFHt+48SS4d4skQ2FYSxmmlzmKDgkE="],"legacyClaimed":true}]}

> headers accept-ranges: bytes
> headers content-length: 344
> headers content-type: application/json
> headers date: Wed, 15 Jan 2020 17:40:26 GMT
> headers request-id: bofkt2ni3l06m1b56c60
> headers status: 200
> headers via: 1.1 varnish
> headers x-cache: MISS
> headers x-cache-hits: 0
> headers x-ratelimit-limit: 1
> headers x-ratelimit-remaining: 0
> headers x-ratelimit-reset: 1
> headers x-served-by: cache-lga21941-LGA
[ END RESPONSE ]
```

* Also confirmed that once the grant is virtualized, restoring the wallet on a new profile, 0 BAT is restored (confirming 1 way conversion).

Scenario 2:
* Verified test plan from https://github.com/brave/brave-core/pull/4101 when claiming only an ad grant on 1.0.0:
<img width="1193" alt="1 0 0-Claim ad grant only" src="https://user-images.githubusercontent.com/28145373/72463904-4cbe7000-37a2-11ea-9998-57c021cfb6d6.png">

* Confirmed on upgrade to 1.3.x that BAT value remains the same (note, discussed discrepancy with @NejcZdovc - confirmed this looks like a rounding discrepancy):
<img width="1192" alt="1 0 0 ad claim upgrade to 1 3 x" src="https://user-images.githubusercontent.com/28145373/72463931-5e077c80-37a2-11ea-9326-5d1b59693336.png">

* Also confirmed the parameters from the description showed in terminal:
`migrate=true` parameter:
```
[ REQUEST ]
> url: https://grant.rewards.bravesoftware.com/v1/promotions?migrate=true&paymentId=1aea8f10-406e-4e53-98f8-7b2fd92a0083&platform=osx
> method: UrlMethod::GET
> content: 
> contentType: 
[ END REQUEST ]
```

`legacyClaimed` parameter:
```
[ RESPONSE - OnFetch ]
> time: 1579113472
> result: Success
> http code: 200
> response: {"promotions":[{"id":"1502b3cd-d1a7-45db-8380-f405f2fc787d","createdAt":"2019-04-19T03:25:29Z","expiresAt":"2020-04-17T03:25:29Z","version":5,"suggestionsPerGrant":11,"approximateValue":"2.75","type":"ads","available":true,"platform":"","publicKeys":["gG28CWWzZG2F/390LA0jxhO67TVV4y1v5uE1evyz/3Y="],"legacyClaimed":true},{"id":"36baa4c3-f92d-4121-b6d9-db44cb273a02","createdAt":"2019-10-30T23:17:15.681226Z","expiresAt":"2020-02-29T23:17:15.681226Z","version":5,"suggestionsPerGrant":70,"approximateValue":"17.5","type":"ugp","available":true,"platform":"desktop","publicKeys":["vNnt88kCh650dFFHt+48SS4d4skQ2FYSxmmlzmKDgkE="],"legacyClaimed":false}]}

> headers accept-ranges: bytes
> headers content-length: 651
> headers content-type: application/json
> headers date: Wed, 15 Jan 2020 18:37:52 GMT
> headers request-id: boflo07i3l06m1b56e70
> headers status: 200
> headers via: 1.1 varnish
> headers x-cache: MISS
> headers x-cache-hits: 0
> headers x-ratelimit-limit: 1
> headers x-ratelimit-remaining: 0
> headers x-ratelimit-reset: 1
> headers x-served-by: cache-ewr18134-EWR
[ END RESPONSE ]
```

* Also confirmed that once the grant is virtualized, restoring the wallet on a new profile, 0 BAT is restored (confirming 1 way conversion).

Scenario 3: 
* Verified test plan from https://github.com/brave/brave-core/pull/4101 when claiming both an ad grant and a UGP grant on 1.0.0:
<img width="1191" alt="1 0 0-Claim UGP and Ad Grant" src="https://user-images.githubusercontent.com/28145373/72463944-68297b00-37a2-11ea-9c3b-d1aafd1a5b2c.png">

* Confirmed on upgrade to 1.3.x that BAT value remains the same (note, discussed discrepancy with @NejcZdovc - confirmed this looks like a rounding discrepancy):
<img width="1193" alt="1 0 0 ugp and ad claim upgrade to 1 3 x" src="https://user-images.githubusercontent.com/28145373/72463959-6eb7f280-37a2-11ea-8b6f-fe915eea2b20.png">

* Also confirmed the parameters from the description showed in terminal:
`migrate=true` parameter:
```
[ REQUEST ]
> url: https://grant.rewards.bravesoftware.com/v1/promotions?migrate=true&paymentId=d6812b86-1f88-48e6-a0e1-f4f94c396159&platform=osx
> method: UrlMethod::GET
> content: 
> contentType: 
[ END REQUEST ]
```

`legacyClaimed` parameter:
```
[ RESPONSE - OnFetch ]
> time: 1579114077
> result: Success
> http code: 200
> response: {"promotions":[{"id":"1502b3cd-d1a7-45db-8380-f405f2fc787d","createdAt":"2019-04-19T03:25:29Z","expiresAt":"2020-04-17T03:25:29Z","version":5,"suggestionsPerGrant":14,"approximateValue":"3.5","type":"ads","available":true,"platform":"","publicKeys":["gG28CWWzZG2F/390LA0jxhO67TVV4y1v5uE1evyz/3Y="],"legacyClaimed":true},{"id":"36baa4c3-f92d-4121-b6d9-db44cb273a02","createdAt":"2019-10-30T23:17:15.681226Z","expiresAt":"2020-02-29T23:17:15.681226Z","version":5,"suggestionsPerGrant":70,"approximateValue":"17.5","type":"ugp","available":true,"platform":"desktop","publicKeys":["vNnt88kCh650dFFHt+48SS4d4skQ2FYSxmmlzmKDgkE="],"legacyClaimed":true}]}

> headers accept-ranges: bytes
> headers content-length: 649
> headers content-type: application/json
> headers date: Wed, 15 Jan 2020 18:47:57 GMT
> headers request-id: boflsndna6ah13u8thj0
> headers status: 200
> headers via: 1.1 varnish
> headers x-cache: MISS
> headers x-cache-hits: 0
> headers x-ratelimit-limit: 1
> headers x-ratelimit-remaining: 0
> headers x-ratelimit-reset: 1
> headers x-served-by: cache-ewr18121-EWR
[ END RESPONSE ]
```

* Also confirmed that once the grant is virtualized, restoring the wallet on a new profile, 0 BAT is restored (confirming 1 way conversion).
