### ISSUE TITLE
Expand contributon_info table

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#6942]
Right now this is how table looks like:

![image](https://user-images.githubusercontent.com/9574457/68940829-7d832880-07a4-11ea-9eba-6268bbcfa7b0.png)

We will need to expand it so that we can handle retry logic and logging an actual contribution data, so that we don't need ledger_state logging anymore. Because VG simplified things a lot, tables should be quite clean. For now VG don't need any special data that needs to be stored so we don't need dumping table for it.

This is a current proposal:
  
![image](https://user-images.githubusercontent.com/9574457/69225199-36b77900-0b7e-11ea-8867-3c0d81222217.png)

**Comment by NejcZdovc** [comment]
blocked on https://github.com/brave/brave-browser/issues/6544

**Comment by LaurenWags** [comment]
@NejcZdovc what should be manually QA'd with this issue?

**Comment by NejcZdovc** [comment]
@LaurenWags test plan could be that you do couple of contributions and make sure that this two tables are populated correctly

**Comment by LaurenWags** [comment]
mix of AC, one time tips and recurring tips?

**Comment by NejcZdovc** [comment]
yup

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` label until https://github.com/brave/brave-browser/issues/7844 and https://github.com/brave/brave-browser/issues/7526 are resolved, encountering both of these issues while testing.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.3.106 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

* Verified 1 time tip, recurring tip, and AC using previously self-funded anon wallet:
<img width="667" alt="anon-6942" src="https://user-images.githubusercontent.com/28145373/73571997-c52d5e00-443d-11ea-9f84-3f7b331b25f4.png">
<img width="503" alt="anon-6942pt2" src="https://user-images.githubusercontent.com/28145373/73572001-c65e8b00-443d-11ea-9248-17b839dec204.png">

* Verified 1 time tip, recurring tip, and AC using anon wallet funded via UGP (virtual) grant:
<img width="672" alt="Screen Shot 2020-01-31 at 3 49 59 PM" src="https://user-images.githubusercontent.com/28145373/73573451-65d14d00-4441-11ea-8b3b-1f7b613ffc70.png">
<img width="477" alt="Screen Shot 2020-01-31 at 3 50 16 PM" src="https://user-images.githubusercontent.com/28145373/73573456-679b1080-4441-11ea-9663-b25eb2b09d07.png">

* Verified 1 time tip, recurring tip, and AC using KYC'd user wallet:
<img width="665" alt="KYCd-6942" src="https://user-images.githubusercontent.com/28145373/73577661-843c4600-444b-11ea-888c-12529eb5f2df.png">
<img width="482" alt="KYCd-6942pt2" src="https://user-images.githubusercontent.com/28145373/73577664-86060980-444b-11ea-9e46-91b9804b4acb.png">
