### ISSUE TITLE
Promotion expiration

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#6947]
UGP promotions has expiration date so we need to handle it. Every time that we call fetch we need to go through list of promotions that we get from the db and check if any of it expired. If so we need to mark promotion is `OVER` and delete all unblinded tokes related to this promotion if any exists.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.90 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4035

![image](https://user-images.githubusercontent.com/34715963/72304350-9c9d1a00-3670-11ea-9b51-ad98bb5f04b3.png)
![image](https://user-images.githubusercontent.com/34715963/72304422-ca825e80-3670-11ea-98a8-c66333bb111a.png)
