### ISSUE TITLE
Dino Game has issues on dark mode

### ISSUE THREAD

**Issue by bobrobot1** [brave/brave-browser#6958]
## Description 

When the browser is in dark theme, the dino in the offline dino game does not display nighttime correctly, and the dino image has issues

## Steps to Reproduce

   1. set theme to dark
   2.  go to chrome://dino
   3. Issues occur when game turns to night, and when dino is ducking (down arrow key)

## Reproduces how often: 

Easily Reproduced

## Brave version (brave://version info)

Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}

OS | macOS Version 10.15.1 (Build 19B88)

## Version/Channel Information:

i don't know
- Can you reproduce this issue with the current release?
yes
- Can you reproduce this issue with the beta channel?
i don't know
- Can you reproduce this issue with the dev channel?
i don't know
- Can you reproduce this issue with the nightly channel?
i don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
no
- Does the issue resolve itself when disabling Brave Rewards?
no
- Is the issue reproducible on the latest version of Chrome? 
no

## Miscellaneous Information:

Night comes at around 700 points
dino image issue is a blinking line behind the dino while ducking, and the black border around the dino at any time.

**Comment by bsclifton** [comment]
Reproduces in Chrome; verified issues

1. Seems colors get swapped (ex: day mode is dark, night mode is light) when in dark mode
<img width="1599" alt="Screen Shot 2019-11-18 at 5 39 39 PM" src="https://user-images.githubusercontent.com/4733304/69106194-d5cb5c00-0a2a-11ea-8d03-c3c8fe6b9416.png">

2. Artifacts around dino when ducking
<img width="190" alt="Screen Shot 2019-11-18 at 5 40 25 PM" src="https://user-images.githubusercontent.com/4733304/69106202-e11e8780-0a2a-11ea-9026-305e9a41c234.png">

**Comment by kjozwiak** [comment]
@bobrobot1 probably worth creating an issue under https://bugs.chromium.org/p/chromium/issues/. I tried searching for `dina page`, `dino game`, `dino color`, `dino theme` but couldn't find an issue.

**Comment by bsclifton** [comment]
Reported officially here:
https://bugs.chromium.org/p/chromium/issues/detail?id=1026136

Thanks @bobrobot1

**Comment by bsclifton** [comment]
Submitted a fix upstream: https://chromium-review.googlesource.com/c/chromium/src/+/1923907

**Comment by bsclifton** [comment]
and awesome- my patch was accepted/merged 🎉 
https://chromium.googlesource.com/chromium/src/+/9bf6154b3ac9ff3fcf789d6dd2078ef50d70b72b

I'll go ahead and close this out (will be coming in a future Chromium version). Thanks for the report
