### ISSUE TITLE
Use System default fonts

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#696]
Carried over from https://github.com/brave/browser-laptop/issues/2324

@stanleyxu2005:
> I'm using Brave 0.10.4 on Win7. I really love this application. I notice one optical issue: The font of Win7 is usually "Segoe UI 9pt", but I guess Brave uses "Arial" or something else overall on Tab, Menu, Adressbar and Bookmark Toolbar.
>
> Do you mind to use system font by default?

@leavehouse:
> +1 from me. Chrome and all Chrome-based alternative browsers (like Brave) have this defect, and it's quite annoying. I'm on Ubuntu and use a system font size of 14, but Brave doesn't respect this for tab titles or the address bar, so the text is unreadably small.

**Comment by tomlowenthal** [comment]
Font rendering and customization provide additional info which can be used for fingerprinting. Let's be careful not to make things worse when we implement this.

**Comment by petemill** [comment]
AFAIK we are using default system fonts for the UI. The difference may be that we are not scaling the whole UI per a system font setting, or even a built-in scale setting. If that is indeed a feature request then that can probably be opened separately.
