### ISSUE TITLE
YT publisher name not shown on ac list and rewards panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6960]
### Description: 
YT publisher name not shown on ac list

### Steps to Reproduce 
  1. Enable rewards
  2. Visit a YT publisher page 
  3. Check ac list, publisher name is missing only `on YouTube` is shown

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/66863593-5cd77100-ef61-11e9-847b-2932bac8a249.png)

**Expected result:**
Should show the publisher name correctly

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy 

**Brave Version:** 
1.13

**Device details:** 
iPhone Xr

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
This is an issue in the library parsing data, moved issue as this does not pertain to iOS specifically.

cc'ing @NejcZdovc

**Comment by NejcZdovc** [comment]
is this reproducible on Android as well?

**Comment by NejcZdovc** [comment]
closing as stale
