### ISSUE TITLE
Unable to open brave ads from notification on Ubuntu 19.10

### ISSUE THREAD

**Issue by atharvan** [brave/brave-browser#6962]
## Description 
When clicking brave notification ads, the notification closes without opening the ad 

## Steps to Reproduce

   1. open brave
   2. brave ads showing as a push notification.
   3. Click the ad notification

## Actual result:
1. notifications closes without opening the ad

## Expected result:
1. it should open the Ads

## Reproduces how often: 
always

## Brave version (brave://version info)

Brave | 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel?Not tested
- Can you reproduce this issue with the dev channel?Not tested
- Can you reproduce this issue with the nightly channel?Not tested

**Comment by fmarier** [comment]
I also ran into that problem back when I was getting ad notifications (before #6973).

**Comment by fmarier** [comment]
I also noticed that problem using dunst as the notification manager. This is what's in my logs:

    dunst[5266]: WARNING: Invoking action 'default' not supported. Notification already closed.

This has worked in the past, so something must have changed.

**Comment by bsclifton** [comment]
Related: https://github.com/brave/brave-browser/issues/6569

**Comment by fmarier** [comment]
> Related: #6569

Probably vaguely related, but definitely different since I can't repro #6569 but I can repro this issue 100% of the time.

**Comment by fmarier** [comment]
Hm, I have working "clickable" notifications on my work laptop (Brave 1.1 beta, Ubuntu 18.04) but not on my personal laptop (Brave 1.0 release, Debian unstable), both using "dunst" as the notification daemon. I wonder whether it has something to do with how my default browser is setup.

**Comment by tmancey** [comment]
@fmarier I am installing Ubuntu 19.10 to test. With regards to Debian @bsclifton  do we officially support?

**Comment by tmancey** [comment]
I have tested ad notifications on Ubuntu 19.10 and they are working as expected (I have not tested with Dunst, please see below question).

@bsclifton @fmarier should we be supporting third party notification plug-ins?

**Comment by fmarier** [comment]
I checked my default browser settings and they all point to Brave:
```
$ xdg-mime query default x-scheme-handler/http
brave-browser.desktop
$ xdg-mime query default x-scheme-handler/https
brave-browser.desktop
$ xdg-settings get default-web-browser
brave-browser.desktop
```
and opening a URL using one of these opens it in Brave:

- `sensible-browser http://example.com`
- `xdg-open http://example.com`

The only difference I can see between these two machines, other than the version of dunst, is that the Debian one is using Brave release and the Ubuntu one is using Brave Beta. Two more things I can do test to try and isolate the problem:

- setting Brave Release as the default on Ubuntu
- installing an older version of dunst on Debian

**Comment by fmarier** [comment]
> @bsclifton @fmarier @alexwykoff @jsecretan should we be supporting third party notification plug-ins?

I moved my issue to #7089 since it is separate from supporting the default notification manager on Ubuntu.

**Comment by atharvan** [comment]
After brave 1.1.22 update its working for me.  


Brave | 1.1.22 Chromium: 79.0.3945.79 (Official Build) (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Linux
JavaScript | V8 7.9.317.31

**Comment by fmarier** [comment]
Thanks for the confirmation @atharvan . It also works for me so I'm going to close this issue.

**Comment by vip20** [comment]
Same issue exists again in 
Version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
with Ubuntu 19.10 #

**Comment by tmancey** [comment]
@vip20 Are you using third party notification services?
