### ISSUE TITLE
fonts-liberation is an absolute dependency on Debian

### ISSUE THREAD

**Issue by sdgn** [brave/brave-browser#6964]
## Description 

The Brave browser binary packages for Debian have `fonts-liberation` as an absolute dependency in their control files.

`fonts-liberation` should be a recommended package, i.e. in the `Recommends` control field.

See `chromium-common`, for example:
https://tracker.debian.org/media/packages/c/chromium/control-72.0.3626.122-1deb9u1

## Steps to Reproduce
```bash
$ apt download brave-browser-beta
$ dpkg -f *.deb Depends | grep -o fonts-liberation
fonts-liberation
```

## Actual result:
`fonts-liberation` is in the `Depends` control field.

## Expected result:
`fonts-liberation` is in the `Recommends` control field.

**Comment by fmarier** [comment]
The proprietary `google-chrome-stable` packages also, like Brave, depend on `fonts-liberation`:
```
Package: google-chrome-stable
Version: 78.0.3904.97-1
Architecture: amd64
Maintainer: Chrome Linux Team <chromium-dev@chromium.org>
Installed-Size: 218935
Pre-Depends: dpkg (>= 1.14.0)
Depends: ca-certificates, fonts-liberation, libappindicator3-1, libasound2 (>= 1.0.16), libatk-bridge2.0-0 (>= 2.5.3), libatk1.0-0 (>= 2.2.0), libatspi2.0-0 (>= 2.9.90), libc6 (>= 2.16), libcairo2 (>= 1.6.0), libcups2 (>= 1.4.0), libdbus-1-3 (>= 1.5.12), libexpat1 (>= 2.0.1), libgcc1 (>= 1:3.0), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.31.8), libgtk-3-0 (>= 3.9.10), libnspr4 (>= 2:4.9-2~), libnss3 (>= 2:3.22), libpango-1.0-0 (>= 1.14.0), libpangocairo-1.0-0 (>= 1.14.0), libuuid1 (>= 2.16), libx11-6 (>= 2:1.4.99.1), libx11-xcb1, libxcb1 (>= 1.6), libxcomposite1 (>= 1:0.3-1), libxcursor1 (>> 1.1.2), libxdamage1 (>= 1:1.1), libxext6, libxfixes3 (>= 1:5.0), libxi6 (>= 2:1.2.99.4), libxrandr2 (>= 2:1.2.99.3), libxrender1, libxss1, libxtst6, lsb-release, wget, xdg-utils (>= 1.0.2)
Recommends: libu2f-udev
Provides: www-browser
Section: web
Priority: optional
Description: The web browser from Google
 Google Chrome is a browser that combines a minimal design with sophisticated technology to make the web faster, safer, and easier.
```

Did you find the reason why Debian deviated from Google's packages? Is the dependency causing a problem on Debian?

**Comment by sdgn** [comment]
Interesting! I hadn’t looked at `google-chrome-stable`.

So, in contrast to Chromium, both Brave and Chrome have an absolute dependency on the Liberation fonts. Unfortunately, I was unable to determine when or why this deviation happened, since there is no public history for Google’s packages. The `Recommends: fonts-liberation` in Chromium was added in January 2016[1]. The oldest Chrome package I could find was a bit newer than that and already had the absolute dependency.

The dependency is causing problems for users that prefer not to have these fonts installed automatically. Granted, that’s a small minority. However, Brave works perfectly fine without the Liberation fonts (as does Chromium), which also suggests that `Recommends` is the better choice here.[2]

I understand that this change would be a deviation from the dependencies set forth by Google Chrome. But since `apt` installs recommended packages anyway (since 2008) **and** Brave does not need `fonts-liberation`, the risk is virtually zero. It would be great if Brave adopted the more flexible Chromium approach.

1: https://salsa.debian.org/chromium-team/chromium/commit/becb1fa8f845d4c1d1c11e46391aa3879fb399ff

2: All three browsers depend on Fontconfig, which has a direct path to a number of OpenType and TrueType fonts, so even on a minimal installation, there is no risk of a blank display due to missing fonts:
```
Depends: libfontconfig1
→ Depends: fontconfig-config
  → Depends: fonts-dejavu-core | ttf-bitstream-vera | fonts-liberation | fonts-freefont
```

**Comment by fmarier** [comment]
Apparently it was added upstream for PDFium: https://cs.chromium.org/chromium/src/chrome/installer/linux/debian/additional_deps?sq&g=0&rcl=21254bb31538d38a5af388d4e9aab94227934a2b&l=10

and it is still used there: https://cs.chromium.org/search/?q=Liberation+case:yes+pdfium&sq=package:chromium&type=cs

So I'm not sure it's worth deviating from upstream here. It sounds like removing these fonts could degrade the rendering of PDFs.

**Comment by sdgn** [comment]
Nice find! The way I understand `Depends` vs. `Recommends`, I am not sure I’d change my opinion about this issue. I mean, the fonts will still be installed for all users that haven’t deliberately modified their apt settings (see below), and personally I haven`t seen any PDF rendering issues. But I fully understand your desire to keep dependencies aligned with Chrome, rather than adopting _some_ Chromium practices.

https://www.debian.org/doc/debian-policy/ch-relationships.html
> Depends
> […] The Depends field should be used if the depended-on package is required for the depending package to provide a significant amount of functionality.
>
> Recommends
> This declares a strong, but not absolute, dependency.
> The Recommends field should list packages that would be found together with this one in all but unusual installations.

**Comment by fmarier** [comment]
I agree with you that changing to `Recommends` would have very little impact on users since those packages are treated in a very similar way to mandatory dependencies and so I think your suggestion is a very good one.

From a practical point of view, it's a little complicated because our [patches](https://github.com/brave/brave-core/tree/master/patches) to the Chrome packaging is already a little out of control and we are trying to reduce the number of differences in order to make merging new Chromium versions easier.

So on balance I think the benefits of making a small dependency optional are probably less than the cost of adding yet another patch to the upstream code. I think we'll keep it for the time being.

**Comment by sdgn** [comment]
Makes sense – thank you for looking into this!
