### ISSUE TITLE
Fast Scrolling Speed

### ISSUE THREAD

**Issue by markomijaljevic** [brave/brave-browser#6968]
## Description 

Too fast scrolling speed when using laptops touchpad.

## Steps to Reproduce

   1. Search something
   2. Scroll
   3. 

## Reproduces how often: 

Always and everywhere

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
Closing. We need quite a bit more information than what's been provided.
