### ISSUE TITLE
mailto links are asking to open google chrome

### ISSUE THREAD

**Issue by deadrow** [brave/brave-browser#6969]
## Description 

mailto links are asking to open google chrome

## Steps to Reproduce

   1.  Open any mailto link
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by fmarier** [comment]
Which operating system and version of Brave are you using?

**Comment by deadrow** [comment]
MacOS Catalina 10.15.1

**Comment by bsclifton** [comment]
@deadrow can you please check `brave://settings/handlers`? You should see an entry in there (if Brave is set to be a handler for mail). The "Allow sites to ask" should be enabled too

The handler is configured by Mail.app (even if you don't use Mail.app). Launch into there and check preferences. You can then see the default configured for your OS:
<img width="786" alt="Screen Shot 2019-11-19 at 9 25 51 AM" src="https://user-images.githubusercontent.com/4733304/69165392-c42b9800-0aae-11ea-8409-495aab2875fb.png">

**Comment by deadrow** [comment]
Thanks. Didn't know that the preference is controlled by mail app.
