### ISSUE TITLE
Greasemonkey support

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#697]
Carried over from https://github.com/brave/browser-laptop/issues/1676

As far as I know, this is a Firefox only extension:
https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/

There are Chromium extensions available with somewhat comparable functionality, such as [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en)

**Comment by kneekoo** [comment]
[Tampermonkey](https://tampermonkey.net/) is indeed a good solution, considering its wide availability: Chrome, Microsoft Edge, Safari, Firefox, Opera Next, Dolphin Browser, UC Browser. The Brave developers could [contact](https://tampermonkey.net/imprint.php?ext=dhdg) the Tampermonkey developer and work something out.

**Comment by derjanb** [comment]
Just contact me if help is needed. :)

**Comment by hackles** [comment]
Lack of userscript support is the only reason I gave up on using Brave.

**Comment by kneekoo** [comment]
Shouldn't this issue be closed? Brave can now use extensions from the official Chrome store, and this includes Tampermonkey and everything else.

**Comment by bsclifton** [comment]
@kneekoo good call 😄 And kudos to @derjanb for chiming in here.  Please comment here if you're still experiencing an issue 😄
