### ISSUE TITLE
Linux (Ubuntu) malformed entry during install of Brave browser prevents update

### ISSUE THREAD

**Issue by EarlGreystoke** [brave/brave-browser#6970]
## Description 
---------------------------------------------------------------------------

During install (following the directions at: https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux) I get a malformed entry error when trying to update just prior to installation of the Brave browser. Terminal text of the entry error:
<pre><font color="#8AE234"><b>user@Linux</b></font>:<font color="#729FCF"><b>~</b></font>$ echo &quot;deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/$UBUNTU_CODENAME main&quot; | sudo tee /etc/apt/sources.list.d/brave-browser-release-${UBUNTU_CODENAME}.list
deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ main
<font color="#8AE234"><b>user@Linux</b></font>:<font color="#729FCF"><b>~</b></font>$ sudo apt update
E: Malformed entry 1 in list file /etc/apt/sources.list.d/brave-browser-release-.list (Component)
E: The list of sources could not be read.
</pre>

My Linux build refuses to update until I (root) delete the offending entry (at which point it updates as normal). 
Assuming the $UBUNTU_CODENAME command was malfunctioning, I replaced those instances with the codename of the build I'm currently running (Bionic Beaver), with identical results.

What am I missing?

## Steps to Reproduce

   1. In terminal, complete commands:
 sudo apt install apt-transport-https curl

curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -

source /etc/os-release

echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ $UBUNTU_CODENAME main" | sudo tee /etc/apt/sources.list.d/brave-browser-release-${UBUNTU_CODENAME}.list

sudo apt update

## Actual result:
E: Malformed entry 1 in list file /etc/apt/sources.list.d/brave-browser-release-.list (Component)
E: The list of sources could not be read.

## Expected result:
Creation of an appropriately formed entry file which could then be updated and would direct the next step (sudo apt install brave-browser). 

## Reproduces how often: 
Every attempt.

## Brave version (brave://version info)
Incomplete installation - N/A

## Version/Channel Information:
Incomplete installation - N/A

## Other Additional Information:
Incomplete installation - N/A

**Comment by fmarier** [comment]
Which version of Ubuntu are you trying to install Brave on?

We're working on making installation on Linux easier, but in the meantime, [these instructions](https://github.com/brave/brave-browser/issues/6522#issuecomment-545672208) should work.

**Comment by EarlGreystoke** [comment]
I'm running the latest Bionic Beaver.
Yep, that was it. Browser is up and running now.

The only difference (and what worked) is the single space in the 3rd line here:
echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ bionic main...

I had been trying:
echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/bionic main...

I appreciate the help!

**Comment by fmarier** [comment]
Glad to know it worked!
