### ISSUE TITLE
ShortCut on Ubuntu 19.10 Dock

### ISSUE THREAD

**Issue by Garoli** [brave/brave-browser#6971]
## Description 
After adding to favs brave and adding it to the ubuntu dock, doesn't open on click

## Steps to Reproduce

   1. Open Brave
   2. Right Click on app on dock and click on "add to favorites"
   3. Close Brave
   4. Click on brave shortcut on dock

## Actual result:

Brave doesn't open. 

## Expected result:

Open a new Brave window. 
## Reproduces how often: 
Easily reproduced 

## Brave version (brave://version info)
Version 0.69.135 Chromium 77.0.3865.120 (64 bits)

#Miscellaneous 

Works on different computer..

**Comment by fmarier** [comment]
> ## Brave version (brave://version info)
> Version 0.69.135 Chromium 77.0.3865.120 (64 bits)

That's a pretty old version of Brave, did you install it using [our official instructions](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux)?

**Comment by rebron** [comment]
Closing. We provided some new instructions, should be working now.
