### ISSUE TITLE
Update Widevine version to 4.10.1582.2

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#6974]
Other platforms are already uses `4.10.1582.2`.

Note for QA:
See the test steps at https://github.com/brave/brave-browser/pull/6975.
Brave doesn't expose current Widevine version via UI.
To check Widevine is update, I think the only way is via debug log or binary check whether user-dir/WidevineCdm/libwidevinecdm.so` is changed.
After c79 bump, we can check more easily because we will also store Widevine's manifest.json also.
Before that, only debug log or binary check could be used.

**Comment by bsclifton** [comment]
Marking as `QA/No` since building in debug is a bit detailed. I did verify the new version works great, I'll go through your test plan and (as a developer) verify things work as they should 😄

**Comment by bsclifton** [comment]
Manually verified test plan! Works beautifully! Thanks, @simonhong 😄👍
