### ISSUE TITLE
Display glitch when OOP rasterization is enabled (default value)

### ISSUE THREAD

**Issue by gingerlime** [brave/brave-browser#6979]
## Description 
Weird display artifacts showing on some elements, moving around when moving the mouse. It happens on several websites / pages.

See animated gif on Github

![brave display glitch](https://user-images.githubusercontent.com/524274/69069449-c34f2380-0a26-11ea-9e49-6e8ca0897edf.gif)

![Screen Shot 2019-11-18 at 17 20 12](https://user-images.githubusercontent.com/524274/69070000-bd0d7700-0a27-11ea-93d5-7ca8e927c41d.png)

## Steps to Reproduce

Just move the mouse around. But even without moving it, some "empty" spots are showing from time to time.

## Actual result:
see gif

## Expected result:
no glitches? :)

## Reproduces how often: 
Happens all the time since upgrading. 

## Brave version (brave://version info)
Version 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)

## Other Additional Information:

Doesn't happen in other apps/browsers on the same computer (Macbook air 11" 2015, running High Sierra 10.13.6). Does not happen in Firefox, Safari or Chrome (Version 78.0.3904.97 (Official Build) (64-bit)).

**Comment by bsclifton** [comment]
Thanks for reporting, @gingerlime! Can you please try opening this URL up and changing the value of the flag to `Disabled`?
brave://flags/#enable-oop-rasterization

If that doesn't fix things (you'll likely have to restart), then I would suspect this to be the issue:
https://github.com/brave/brave-browser/issues/6506

**Comment by gingerlime** [comment]
@bsclifton yep, disabling the flag seems to fix it. 👍 Thank you!

**Comment by bsclifton** [comment]
cc: @bbondy - as this deviates from Chromium and does cause a graphics glitch

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.90 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4318

![image](https://user-images.githubusercontent.com/34715963/72305609-9d37af80-3674-11ea-9193-3244792f5a0b.png)
