### ISSUE TITLE
Offer a jump list when right clicking Brave (when pinned to taskbar)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#698]
Carried over from https://github.com/brave/browser-laptop/issues/2627

When right clicking Chrome (which I have pinned), I get this:
![screen shot 2018-08-06 at 10 56 03 pm](https://user-images.githubusercontent.com/4733304/43757027-3b4740b0-99cc-11e8-9cf2-101860b05458.png)

However, Brave (brave-core) is not showing anything in the jump list:
![screen shot 2018-08-06 at 10 58 53 pm](https://user-images.githubusercontent.com/4733304/43757056-59ba58d4-99cc-11e8-85d3-a72c74fb706d.png)

**Comment by srirambv** [comment]
Looks like its out-of-box-feature on brave-core too.

![image](https://user-images.githubusercontent.com/17010094/43774861-98396d9c-9a18-11e8-9b68-d7f2043f3790.png)

**Comment by srirambv** [comment]
This is an issue on Linux 
![image](https://user-images.githubusercontent.com/17010094/43898871-32101754-9bae-11e8-8edd-3d05210144e8.png)

**Comment by bsclifton** [comment]
We have this now 😄 Closing
