### ISSUE TITLE
Rename Ads and trackers to Ads & trackers to match mobile

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#6982]
## Description 

Based on @karenkliu comment on https://github.com/brave/brave-ios/issues/1575#issuecomment-555152231, desktop should match what's on mobile and replace `Ads and Trackers blocked` to `Ads & Trackers blocked`

## Actual result:

 `Ads and Trackers blocked` 

## Expected result:
`Ads & Trackers blocked`

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
Closing as stale. We're consistent across all platforms as Trackers & ads Blocked. We're lower case `ads` on desktop though.

**Comment by karenkliu** [comment]
Yes, consistent on all platforms as `Trackers & ads blocked`. Only iOS retains Title Case - `Trackers & Ads Blocked`
