### ISSUE TITLE
Add a fingerprinting exception for veriff.me for uphold

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#6983]
## Test plan
See https://github.com/brave/brave-core/pull/4012

## Description 
Uphold needs veriff.me for KYC, veriff.me uses Canvas APIs. Add a fingerprinting exception to allow veriff.me to access these APIs in 3p context.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.87 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4012. I used new credentials. The selfie option worked without problems. After the process I got message: `Processing your ID document`

![image](https://user-images.githubusercontent.com/34715963/72069747-256e2b80-32e8-11ea-9a2c-826e8abde274.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.3.87 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.14.6 (Build 18G103)

* Reproduced the issue with 1.0.0 Chromium: 78.0.3904.97
<img width="683" alt="Screen Shot 2020-01-09 at 12 09 25 PM" src="https://user-images.githubusercontent.com/28145373/72088964-32375300-32d9-11ea-8a5f-f5290e151e8b.png">
<img width="372" alt="Screen Shot 2020-01-09 at 12 09 47 PM" src="https://user-images.githubusercontent.com/28145373/72088994-3bc0bb00-32d9-11ea-86f6-26010f3ffecf.png">
<img width="356" alt="Screen Shot 2020-01-09 at 12 10 06 PM" src="https://user-images.githubusercontent.com/28145373/72089020-48ddaa00-32d9-11ea-9776-3719d68ec808.png">

* Verified test plan from https://github.com/brave/brave-core/pull/4012
* Confirmed no issues taking selfies/using webcam to take picture of my document (after allowing access to camera/mic)
<img width="669" alt="Screen Shot 2020-01-09 at 12 20 19 PM" src="https://user-images.githubusercontent.com/28145373/72089656-7119d880-32da-11ea-8191-14babf712d88.png">
<img width="384" alt="Screen Shot 2020-01-09 at 12 20 13 PM" src="https://user-images.githubusercontent.com/28145373/72089660-72e39c00-32da-11ea-8db5-851abdbf2842.png">

**Comment by LaurenWags** [comment]
Note - updated `release-notes/include` to be `release-notes/exclude` per discussion with @kjozwiak since this was actually included in 1.1.x.
