### ISSUE TITLE
Consider renaming Crypto Wallets to Crypto Wallet

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#6988]
Wallet in general is a bad analogy for what it is, but it's commonly known and used.
But "Wallets" is worse IMHO. Most people don't walk around with multiple wallets in their pockets.
cc @tomlowenthal for thoughts.

**Comment by BrendanEich** [comment]
We may want to use "wallet" singular, same way mult-coin/blockchain wallet apps do. But before we rename, let's look at the big picture and consider the "crypto" prefix too.

Are we integrating user-owns-keys wallets? No. Are we integrated proxied fullnodes for different blockchains that come with availability and consistency quality of service guarantees? I hope so (Infura won't cut it under load, from all I know). Even in the proxied fullnode case, who has the key or keys is independent.

BitGo multisig wallets for Bitcoin and other chains enable 2of3 signing to send while avoiding regulation of anyone having only one key. I think may we want this for any return of a Bitcoin "crypto wallet" (we had this in the "Brave Payments" beta for Brave Rewards), provided the 3rd key can be kept by a reliable party.

So what we're talking about is integrated cryptocurrency/token accounts, not based on custodial accounts, e.g., at Coinbase or Uphold. I'm not suggesting "Crypto accounts", for sure. But having written this comment, I wonder if we wouldn't be better off just using "Cryptocurrencies/Tokens" (yeah, awkward) or "Digital Assets" (argh) or something that avoids the wallet trope.

**Comment by bbondy** [comment]
I think either of "Cryptocurrencies/Tokens" or "Digital Assets" is better.  It's just the thing in the hamburger menu that opens our MetaMask fork UI.  Which is currently an ethereum-remote-client only, but will likely eventually have integration from exchanges too. 

Crypto Wallets doesn't make sense to me.  For example in my wallet I have credit cards from different banks. I don't need a different wallet for each one.

**Comment by tomlowenthal** [comment]
I'm not totally satisfied with the name either. How about "**Crypto Assets**" — it combines the "crypto" prefix which communicates the general nature of the goods, and "assets", which is a sort of general description of all the things encompassed here?
