### ISSUE TITLE
consider using upstream https-everywhere chrome extension instead of our custom one

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#700]
benefits: rulesets stay up-to-date without us needing to manually update
downsides: may be less performant

https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp

**Comment by diracdeltas** [comment]
this is blocked on doing some perf tests to see if there is a meaningful difference between using the extension vs native

**Comment by fmarier** [comment]
Apparently the performance of the extension has improved thanks to a new Rust/WebAssembly library (see #5280).

**Comment by tomlowenthal** [comment]
Closed in favor of #5280.
