### ISSUE TITLE
Android - support AutoFill API

### ISSUE THREAD

**Issue by MadsBen** [brave/brave-browser#7007]
On Android, please support the AutoFill API, to allow the use of 3rd party password managers, like Keepass2Android.

https://developer.android.com/guide/topics/text/autofill

Related:
https://github.com/PhilippC/keepass2android/issues/1044

**Comment by mrtumnus** [comment]
This is a duplicate of #7355

**Comment by fallaciousreasoning** [comment]
Closing this because it duplicates #7355 (thanks @mrtumnus)
