### ISSUE TITLE
Low resolution icon in Brave Rewards overflow

### ISSUE THREAD

**Issue by aksa** [brave/brave-browser#7008]
## Description 
Images/icons/favicons of current web displayed on Brave Rewards are in pretty low quality

## Steps to Reproduce
   1.  Visit any website
   2. Click on Brave Rewards icon in address bar

## Actual result:
Low-res image

![image](https://user-images.githubusercontent.com/1129007/69143552-88ea9280-0ac9-11ea-8c37-1915c7497b6b.png)

## Expected result:
Retina grade image

## Reproduces how often: 
every time

## Brave version (brave://version info)
1.0.0

**Comment by NejcZdovc** [comment]
for sites we are using favicons that are used in tabs as well. We are using existing favicon system from chromium. Based on that it looks like that site has low res favicon
