### ISSUE TITLE
Crypto site raises CPU usage to an abnormal level

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#7015]
Have you searched for similar issues? Yes.

## Description 
I think Brave has protections against behind the scene mining, though it isn't advertised as such. Going to the brave ad site energi.world gets the browser at an abnormal cpu usage. 

## Steps to Reproduce

   1. www.energi.world
 

## Actual result:
This was yesterday though it was the same maybe slightly higher today. 
![Screenshot_20191118_030058](https://user-images.githubusercontent.com/31957540/69177725-003b1900-0b00-11ea-8421-85bab7d9cd26.png)

## Reproduces how often: 
I've been able to reproduce it twice.

## Brave version (brave://version info)
Version 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit) (openSuse)

## Miscellaneous Information:
![Screenshot_20191119_185632](https://user-images.githubusercontent.com/31957540/69177826-41332d80-0b00-11ea-9d4c-a7383ef5406d.png)

**Comment by bsclifton** [comment]
cc: @snyderp @ryanbr

**Comment by snyderp** [comment]
@ryanbr If this takes anything more complicated than a new rule to the brave coinminer list, let me know and I'm happy to dig in and help figure out a solution
