### ISSUE TITLE
Toggling bookmark bar affects other profiles

### ISSUE THREAD

**Issue by hailwood** [brave/brave-browser#7016]
## Description 
When toggling the bookmark bar it also toggles it for any other open profiles.

## Steps to Reproduce
1. Create multiple profiles
2. Open both profiles in separate windows
3. Toggle bookmark bar in one profile

## Actual result:
Bookmark bar is shown/hidden in both profiles

## Expected result:
Bookmark bar is shown/hidden in only the profile of the active window

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Linux

## Version/Channel Information:
- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?
Have not tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:
Possibly related - Bookmark bar is always visible in "Private" window, attempting to toggle bookmark bar toggles it in the main window but leaves it visible in the "Private" window.

**Comment by rebron** [comment]
I can't reproduce this in both release 1.2.x and beta 1.3.x. 
Have two profiles open, focus on one, toggle show bookmarks in prefs on and off and notice that it only effects profile in focus.

Reporter is on Linux. cc: @srirambv can you try?

**Comment by rebron** [comment]
<img width="1409" alt="Screen Shot 2020-01-17 at 9 08 44 AM" src="https://user-images.githubusercontent.com/5951041/72631355-ff104780-3908-11ea-8304-ad483649e287.png">

**Comment by hailwood** [comment]
I can confirm that this is no longer an issue in the latest version.
