### ISSUE TITLE
Error in event handler: TypeError: Cannot read property 'find' 

### ISSUE THREAD

**Issue by mbacchi** [brave/brave-browser#7021]
## Description 
Starting nightly build `v1.3.17` on Linux from the command line frequently emits the error:

```
[6638:6638:1119/213133.232253:ERROR:CONSOLE(0)] "Error in event handler: TypeError: Cannot read property 'find' of undefined
    at chrome://newtab/brave_new_tab.bundle.js:46:483718
    at Array.forEach (<anonymous>)
    at Gt (chrome://newtab/brave_new_tab.bundle.js:46:483491)
    at chrome://newtab/brave_new_tab.bundle.js:1:36746
    at Object.m [as dispatch] (chrome://newtab/brave_new_tab.bundle.js:1:34788)
    at Object.onPromotions (chrome://newtab/brave_new_tab.bundle.js:1:36873)
    at chrome://newtab/brave_new_tab.bundle.js:46:486948", source: chrome://newtab/ (0)
```

## Steps to Reproduce

   1. Install nightly `v1.3.17`
   2. Run `brave-browser-nightly` from terminal

## Actual result:

The browser runs, but emits the above error in the terminal.

## Expected result:
The browser runs without errors in the terminal.

## Reproduces how often: 

Always. Started and restarted multiple times to verify it wasn't a single occurrence.

## Brave version (brave://version info)

```
Brave	1.3.17 Chromium: 78.0.3904.108 (Official Build) nightly (64-bit)
Revision	4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS	Linux
JavaScript	V8 7.8.279.23
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
Command Line	/opt/brave.com/brave-nightly/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=NewExtensionUpdaterService,PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=SmsReceiver,AudioServiceOutOfProcess,LookalikeUrlNavigationSuggestionsUI,AutofillServerCommunication,UnifiedConsent,NotificationTriggers,SyncUSSBookmarks --flag-switches-begin --flag-switches-end
Executable Path	/opt/brave.com/brave-nightly/brave
Profile Path	/home/mbacchi/.config/BraveSoftware/Brave-Browser-Nightly/Default
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by NejcZdovc** [comment]
@mbacchi could you please click on the link and paste code where it fails. (Please also click on `{}` in dev tools so that code will be formatted. Thank you
