### ISSUE TITLE
Migrate user settings from JSON to Preferences

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#7024]
We still have some settings in `ledger_state` and `publisher_state`. This should be migrated to state api

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.11.82 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | Windows 10 OS Version 1903 (Build 18362.900)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/5417
- Encountered https://github.com/brave/brave-browser/issues/10438
