### ISSUE TITLE
Ad notifications not working on macOS Catalina

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#7026]
## Description 

Ad notifications not working on macOS Catalina

## Steps to Reproduce

   1. View an ad

## Actual result:

Ad notification does not appear

## Expected result:
Ad notification should appear

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by tmancey** [comment]
@jsecretan I can no longer reproduce (only reproduced once) and then tried upgrade paths etc. which all worked as expected

**Comment by jsecretan** [comment]
Thanks @tmancey I'll keep my ear to the ground on community to see if they see this happening

**Comment by tmancey** [comment]
Closing issue as no longer occurs, will re-open if we see issue again
