### ISSUE TITLE
Ads region on iOS is unsupported if users Calendar is set to a non-default option

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#7029]
## Description 

In iOS/macOS we use `NSLocale` to determine the users current locale and feed this into the ads library. If an iOS user sets a non-default calendar for their region (For example switching from `Gregorian` to `Japanese`) the identifier reported by `NSLocale` ends up looking like this `en_US@calendar=japanese` which then is not parsed correctly by bat-native-ads since it is looking for `en_US` specifically.

Currently unknown whether or not this issue happens in macOS as well (Chromium may not use `NSLocale.identifier` directly as iOS does)

**Comment by tmancey** [comment]
@kylehickinson Thinking about this it would be better if we pass an ISO code to the library, which can be concatenated using `NSLocaleLanguageCode` and `NSLocaleCountryCode` which are part of `[NSLocale currentLocale]`

**Comment by tmancey** [comment]
@kylehickinson This issue also affects macOS, I am fixing the issue for macOS as above, as ideally, the client should pass an IOS date in the en_US format

**Comment by kylehickinson** [comment]
Preferred Languages won't work here either, as it returns the incorrect format. Example:

```
(lldb) po Locale.preferredLanguages()
["en-JP"]
(lldb) po Locale.current.identifier
en_JP@calendar=japanese
```
