### ISSUE TITLE
Crypto Wallets does not have latest proxy caching

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#7032]
It needs to pull in latest eth-json-rpc-infura, related to: https://github.com/brave/brave-browser/issues/6614

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Linux
Component | `0.1.29`

- Verified using remote component 0.1.29
- Verified console doesn't log any errors for transactions
- Verified ETH/BAT is sent into a restored MM wallet
- Verified ETH/BAT is sent into a restored Crypto Wallet
- Verified sending conversion for ETH/ERC-20 tokens is correct
- Verified buying via CW works on https://memefactory.io/ with transaction
![image](https://user-images.githubusercontent.com/17010094/69462166-5dc0a700-0d46-11ea-8e23-762ac1445ecb.png)
