### ISSUE TITLE
Failed to detect webcam on https://whereby.com/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#7037]
## Description 
Video conferencing fails on https://whereby.com/ . No option to detect camera, even with Sheilds down.

## Steps to Reproduce

   1. Create account on https://whereby.com/
   2. Create Room.
   3. Join room, click on Cam/Mic (open another browser, join room to test)

## Actual result:
**Brave:**
![whereby-brave](https://user-images.githubusercontent.com/1659004/69276778-edc9f800-0c43-11ea-834b-c800a7e57305.png)
**Chrome:**
![whereby-chrome](https://user-images.githubusercontent.com/1659004/69276810-03d7b880-0c44-11ea-9fdd-3e6cf80999c8.png)

## Expected result:
Expect Camera to be detected and working

## Reproduces how often: 
Easily, 

## Brave version (brave://version info)
Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
Shields has no affect on the site

**Comment by fmarier** [comment]
Seems to work fine but you need to enable these site permissions first:
- autoplay
- sound

We should probably add that site to https://github.com/brave/autoplay-whitelist/blob/master/data/autoplay.json.

**Comment by VictorAlagwu** [comment]
I am currently having the same issue
