### ISSUE TITLE
Overlapping text in table in Google Slides

### ISSUE THREAD

**Issue by georgiamoon** [brave/brave-browser#7039]
## Description 
Using a table in a Google Slide, the text within the table displays as overlapped.

## Steps to Reproduce
   1. Start a presentation in Google Slides
   2. Add a table on a slide
   3. Type in the cell in the table

## Actual result:
<img width="1012" alt="Screen Shot 2019-11-20 at 1 26 43 PM" src="https://user-images.githubusercontent.com/941210/69278885-2c62a280-0bb1-11ea-94b6-b3bfc3315979.png">

## Expected result:
Readable text

## Reproduces how often: 

Easily Reproduced (for us this morning!)

## Brave version (brave://version info)

Brave: Version 0.70.122 Chromium: 78.0.3904.87 (Official Build) (64-bit)

## Other Additional Information:
Does the issue resolve itself when disabling Brave Shields? YES
Does the issue resolve itself when disabling Brave Rewards? Rewards not enabled
Is the issue reproducible on the latest version of Chrome? The issue was not happening on Chrome for other users on the same Google Slide deck.

**Comment by rebron** [comment]
<img width="1366" alt="Screen Shot 2020-01-17 at 9 14 48 AM" src="https://user-images.githubusercontent.com/5951041/72631840-da689f80-3909-11ea-95b8-ae33a5917742.png">
I'm unable to reproduce this one. Still happening with the current release of Brave? Current version is  1.2.x..
I have it working with shields up. This might be font related?

If you have a doc to share, would be happy to look at it.

**Comment by rebron** [comment]
Hi @georgiamoon, Can you try again with an updated version of Brave? 0.70.122 is a bit old, current version is 1.2.43.

**Comment by georgiamoon** [comment]
I was reporting this for someone else, so I'd need to try to retest or
reach out to them. I can reach out but seems from your screenshot like it's
fixed!

>

**Comment by rebron** [comment]
@georgiamoon Could be a font issue or a gpu issue on their end? Would need to know more if it's still an issue.

**Comment by Vimru** [comment]
I can also confirm this on Brave 1.4.96. Turning off shields fixes the issue.

**Comment by bsclifton** [comment]
@Vimru does this happen in latest? If so, do you have an example link we can try and quickly tell if there's a problem?

**Comment by Vimru** [comment]
@bsclifton I just checked and this is no longer an issue for me in latest.
