### ISSUE TITLE
Android should use full Chromium version instead of brave-core versioning scheme

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7040]
## Description 

Android should use full Chromium version instead of brave-core versioning scheme

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/69278859-2240a400-0bb1-11ea-91e7-885dc9b36075.png)

## Expected result:
Similar to current release build
![image](https://user-images.githubusercontent.com/17010094/69278961-5caa4100-0bb1-11ea-8696-778794aea580.png)

## Reproduces how often: 

Easy

**Comment by emerick** [comment]
We probably need to call `GetBraveVersionNumberForDisplay` instead of `version_info::GetVersionNumber` in our `chromium_src` override.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 9.0 running 1.5.46 nightly build. 
![image](https://user-images.githubusercontent.com/17010094/72825519-2e92bd00-3c45-11ea-82b5-051c185f48af.png)
- Logged follow up issue #7842 for missing Brave version number from CI builds
