### ISSUE TITLE
Chrome/Firefox importers should not import cookies

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#7044]
Currently, we appear to be [importing all Chrome cookies](https://github.com/brave/brave-core/blob/00c5caf684aec24668e4e54c68974ea763c5eeb1/utility/importer/chrome_importer.cc#L351-L402) into Brave when a user chooses to import cookies (presumably the same is true for Firefox and any other browsers we import from).

To avoid importing any tracking cookies, we should:
1. avoid importing cookies that were set in a third-party context
2. impose a 6-month limit to any cookies we import (to match the limit we impose on new cookies)

I'm not sure whether there's a way to tell third-party cookies or not, but a larger question (for @tomlowenthal) is: should we import cookies at all?

Importing legitimate login cookies does reduce the friction involved in migrating to a  new browser, but perhaps migrating saved passwords is good enough to reduce the pain of having to relogin.

**Comment by tomlowenthal** [comment]
I don't think we need to import cookies. Let's just drop that.

**Comment by iefremov** [comment]
@tomlowenthal I assume we should still import cookies from Brave profiles?

**Comment by bsclifton** [comment]
Updated title, per https://github.com/brave/brave-core/pull/4121#issuecomment-563394176

**Comment by bsclifton** [comment]
Bumping up to P2 after recent conversations with @BrendanEich

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.1.22 Chromium: 79.0.3945.79 (Official Build) (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified importing from Firefox and Chrome via brave://welcome flow does not import cookies
* Verified importing from Firefox and Chrome via brave://settings/importData does not import cookies
* Verified there is no checkbox to import Cookies when importing from Firefox or Chrome on brave://settings/importData
<img width="533" alt="Screen Shot 2019-12-16 at 3 25 35 PM" src="https://user-images.githubusercontent.com/28145373/70941134-ce8f7200-2019-11ea-8280-be8d974546a2.png">
<img width="527" alt="Screen Shot 2019-12-16 at 3 25 44 PM" src="https://user-images.githubusercontent.com/28145373/70941138-d0593580-2019-11ea-959f-66b9d87e323e.png">

* Cookies can still be imported via Brave (old), but this will be removed with https://github.com/brave/brave-browser/issues/7403

**Comment by Srini-B** [comment]
Removing such a useful feature now made me not use this browser, it would take me a lot of time to log back in on all sites

**Comment by KillzTheSpy2** [comment]
why remove such a useful feature?
we need to revert this
