### ISSUE TITLE
Wallet backup screen should be responsive to browser size 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7045]
## Description 

Wallet screen should be responsive to browser size 

## Steps to Reproduce

   1. Have a small browser window than regular 
   2. Click on backup code and verify it
   3. All the code words are not shown as the wallet is not responsive to browser window

## Actual result:

![crypto_zoom](https://user-images.githubusercontent.com/17010094/69283095-c29ac680-0bb9-11ea-83e1-f30a01c24b8b.gif)

## Expected result:
Should be responsive so that the UI is always visible irrespective of browser window size

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
--|--
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Linux
Crypto Wallet Component: | `0.1.29`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by srirambv** [comment]
@bbondy @tomlowenthal  can we prioritize this a little higher and have it fixed for the next release?

**Comment by kjozwiak** [comment]
Ran into this as well on my Win laptop making it almost impossible to complete the verification portion when creating a new wallet. You'll basically have to zoom out to get the entire screen visible.

#### Example of the default Zoom:

![Annotation 2019-12-19 122338](https://user-images.githubusercontent.com/2602313/71197899-9cbc1c80-2260-11ea-9586-14ee954c3d93.jpg)

#### Example of the screen once you zoomed out:

![Annotation 2019-12-19 130734](https://user-images.githubusercontent.com/2602313/71197926-b198b000-2260-11ea-909a-fb5ea7c3bdf8.jpg)

**Comment by srirambv** [comment]
+1 from @SoaringMoon via #7825

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.5.73 Chromium: 80.0.3987.66 (Official Build) nightly (64-bit)
-- | --
Revision | 56ea77d65c47ecbb1180b99f860d85b51117864a-refs/branch-heads/3987@{#662}
OS | Linux
Component | `0.1.37`

- Verified wallet backup screen is responsive to browser window height and shows vertical scrollbars
