### ISSUE TITLE
Wallet balance is not updated dynamically after sending a tip

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7047]
## Description 

Wallet balance is not updated dynamically after sending a tip
## Steps to Reproduce

   1. Clean profile 1.2.7
   2. Claim grants
   3. Send a one-time tip to verified pubs
   4. After sending a tip, wallet balance isn't updated dynamically in `Tip Sent` banner

## Actual result:

Wallet balance is not updated dynamically after sending a tip
![image](https://user-images.githubusercontent.com/38657976/69338147-88e4c100-0c88-11ea-83a6-14cc1581b012.png)

## Expected result:
Wallet balance should be updated dynamically after sending a tip

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.2.7 Chromium: 78.0.3904.108 (Official Build) dev (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc @brave/legacy_qa @ryanml @NejcZdovc

**Comment by btlechowski** [comment]
Reproduced on Ubuntu 

Brave | 1.2.6 Chromium: 78.0.3904.97 (Official Build) dev (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/69419955-f131b200-0d1d-11ea-92fd-23f544499f4a.png)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.81 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Ubuntu 18.04 LTS

Verified test plan from the description.

![image](https://user-images.githubusercontent.com/34715963/71763578-d1290d00-2edd-11ea-939f-e9420aaa57c2.png)
