### ISSUE TITLE
Brave sends mysterious data to clients4.brave.com

### ISSUE THREAD

**Issue by alexpirine** [brave/brave-browser#7048]
##  Description 

While using Gmail, I noticed some connections to clients4.brave.com.

What is this about?

That's the request I saw in DevTools -> Network:

https://clients4.brave.com/invalidation/lcs/client?xpc=%7B%22cn%22%3A%22Gv-redacted-%22%2C%22tp%22%3Anull%2C%22osh%22%3Anull%2C%22ppu%22%3A%22https%3A%2F%2Fhangouts.google.com%2Frobots.txt%22%2C%22lpu%22%3A%22https%3A%2F%2Fclients4.google.com%2Frobots.txt%22%7D

_(the -redacted- part represents the redacted by me)_

I am sorry, but I can not share any more info.

clients4.brave.com is a valid domain, and there is nothing I can find about it.

I think that I, and many other people, would appreciate an explanation about this.

**Comment by jumde** [comment]
Hi @alexpirine, to prevent direct connections to google endpoints we proxy some URLs through *.brave.com which remove some user identifiable information like X-Forwarded-* headers. You can find more info about these endpoints here: https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs.

**Comment by alexpirine** [comment]
@jumde thank you for the explanation! Before we close this, can this feature be disabled?

P.S. A Google search for "clients4.google.com" unfortunately doesn't lead to any meaningful result…

![image](https://user-images.githubusercontent.com/1610035/69358471-33f47b00-0c87-11ea-98a7-de163be89ea7.png)

**Comment by bsclifton** [comment]
@alexpirine you're wanting the proxying of the call to be disable-able? (ex: so browser reaches directly out to Google services?)

**Comment by alexpirine** [comment]
> @alexpirine you're wanting the proxying of the call to be disable-able? (ex: so browser reaches directly out to Google services? able to get your IP, etc)

Yes… this is not an option?

**Comment by alexpirine** [comment]
What does Brave do with the proxied data?

Is it documented on the [privacy policy](https://brave.com/privacy/) page? (I quickly went through and can't find anything about this proxy service)

**Comment by tomlowenthal** [comment]
There's nothing about this in the privacy policy because these proxies don't record any personal info.

**Comment by alexpirine** [comment]
So, the proxies don't record IP addresses? (which - although it was subject to debate - are now, by European laws, considered as personal info (since identification is quite easy in most cases) thanks to RGPD)

It's a bit strange: if there is no personal info in these requests, why hide them from Google in the first place? If there is some personal info, there should be a policy stating how this info is handled...

**Comment by bsclifton** [comment]
@alexpirine there is no personal information recorded by US, with regards to the proxy servers. If you don't use the proxy, Google can use the information provided in any way (ex: doing a geolocate based on your IP, etc)

**Comment by chickahoona** [comment]
I assume that we cannot get rid of these calls completely?

**Comment by bsclifton** [comment]
@chickahoona not without disabling the feature completely... I am not 100% sure, but I believe the URL called out (`https://clients4.brave.com/invalidation/lcs/client`... which is proxied to `https://clients4.google.com/invalidation/lcs/client`) is used for Safe Browsing

If you'd like to turn off Safe Browsing, you can. I wouldn't recommend it (as it's a nice feature), but if you want to, you can in settings under `brave://settings/privacy`:
<img width="982" alt="Screen Shot 2019-11-24 at 11 14 35 PM" src="https://user-images.githubusercontent.com/4733304/69516862-40d7cf80-0f10-11ea-91c2-be436dfc7cc6.png">

**Comment by rebron** [comment]
Closing. Looks like this question has been answered.
