### ISSUE TITLE
Ads crash when getting winner over time category in iOS

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#7049]
## Description 

Getting a few crash reports in ads lib (Crash log attached) in `AdsImpl::GetWinnerOverTimeCategory` method in Brave iOS 1.13

[crash logs.zip](https://github.com/brave/brave-browser/files/3875733/crash.logs.zip)

**Comment by tmancey** [comment]
Fixed by https://github.com/brave/brave-browser/issues/6880
