### ISSUE TITLE
Facebook videos don't play

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#705]
## Description 

Browser doens't use fallback HTML5 video player when flash is blocked

## Steps to Reproduce

   1. Install 0.53.1, ensure Flash is installed on the machine
   2. Visit this page in a new tab https://www.facebook.com/peopleareawesome/videos/vb.305140869535098/918408738208305/?type=2&theater
   3. Click play, shows error for flash player, doesn't use fallback HTML5 video player

## Actual result:

Complains about flash player

## Expected result:
Should use fallback HTML5 video player, similar to browser-laptop, instead of Flash

## Reproduces how often: 

100%

## Brave version (about:brave info) 

```
Brave	0.53.1 Chromium: 69.0.3497.12 (Official Build) dev (64-bit) 
Revision	e8e14b69c41a5a461c15fa5d1065ec28c49890ac-refs/branch-heads/3497@{#54}
OS	Windows
JavaScript	V8 6.9.427.5
Flash	30.0.0.134 C:\WINDOWS\system32\Macromed\Flash\pepflashplayer64_30_0_0_134.dll
```
### Reproducible on current release:

No. browser-laptop uses HTML5 player even if flash is installed on the machine

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @diracdeltas @bridiver

**Comment by srirambv** [comment]
Facebook videos fail to play as a result of this. Page just reloads but doesn't play video

**Comment by LaurenWags** [comment]
Video plays if shields are disabled.

**Comment by GeetaSarvadnya** [comment]
QA PASSED on windows.

Brave | 0.54.3 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | Windows
