### ISSUE TITLE
C79 bump breaks debug build on Linux

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#7055]
This maybe different for various flavors of Linux, I am building on `Mint Cinnamon 19.2`

When building debug build on Linux, the build itself succeeds, but the executable cannot run.
The following error is shown:
<pre>
brave-browser/src/out/Debug/brave: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by brave-browser/src/out/Debug/brave)
</pre>

This is due to the following Chromium change:
https://chromium.googlesource.com/chromium/src/+/695245c
(also see https://bugs.chromium.org/p/chromium/issues/detail?id=1012850)
which rolls sysroots from GLIBC_2.27 (which is what my OS has) to GLIBC_2.29.

See `src/build/linux/debian_sid_amd64-sysroot` libraries.

* Reverting this commit:
`src> git revert 695245cf8ad88b73cac7ccd4f5bcda88fc16bf83`
* Then, running 
`src> ./build/linux/sysroot_scripts/install-sysroot.py --arch=amd64`
* Then, rebuilding - fixes the error (the libraries in the `src/build/linux/debian_sid_amd64-sysroot` are rolled back to 2.27).

cc: @iefremov @simonhong @bsclifton

**Comment by bridiver** [comment]
it really shouldn't matter what your OS has because it bundles everything it needs afaik other than the things installed by `install-build-deps.sh`, but I don't see any changes to `install-build-deps.sh` in that commit? Maybe they happened somewhere else?

**Comment by NejcZdovc** [comment]
same think happened to me on ubuntu

**Comment by mkarolin** [comment]
Reopening because this issue refers specifically to debug builds, whereas brave/brave-core#4255 fixes the issue that appeared in release builds. The issue with debug builds was present before cosmetic filtering changes.

**Comment by mkarolin** [comment]
It is quite likely, though, that the reason the debug build breaks is the same - rust linking with GLIBC in Chromium's sysroot.

**Comment by bsclifton** [comment]
Re-opening as I believe this was closed on accident

**Comment by bsclifton** [comment]
Closing as stale

**Comment by bridiver** [comment]
we still have a problem that needs to be addressed here with glibc

**Comment by kjozwiak** [comment]
@bridiver going to remove the `closed/stale` label as this was reopened a while ago. If this isn't an issue anymore, can you label it with the needed `closed/[x]` label and close the issue? Thanks!

**Comment by bridiver** [comment]
I believe this was fixed by removing the dependency on glibc in rust. @antonok-edm ?
