### ISSUE TITLE
[Meta] Migrate old Mojo bindings types to new ones

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#7056]
Chromium is moving from old mojo binding types to new ones (https://bugs.chromium.org/p/chromium/issues/detail?id=955171), we should migrate ours too.
Cheat sheet for the type migration:
https://docs.google.com/document/d/1Jwfbzbe8ozaoilhqj5mAPYbYGpgZCen_XAAAdwmyP1E/edit#

Our services that would need the migration:

- [x] TorLauncher https://github.com/brave/brave-browser/issues/7116
- [x] Ads https://github.com/brave/brave-browser/issues/7856
- [ ] Rewards

**Comment by bsclifton** [comment]
Lightning talk that a few of us attended, by Julie Kim of Igalia regarding the topic:
https://youtu.be/z3EjkpvEWC4?t=420

**Comment by bsclifton** [comment]
Rewards work done in https://github.com/brave/brave-core/pull/5924
