### ISSUE TITLE
Blank page for magnet links on clean install

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#7061]
magnet protocol is handled by WebTorrent extension. Magnet link is not opened on first page load on clean profile.

Important: This is a regression in 1.2.x
Note: this issue is very similar to https://github.com/brave/brave-browser/issues/6472

## Steps to Reproduce

   1. Clean profile
   2. Open [https://webtorrent.io/free-torrents](https://webtorrent.io/free-torrents)
   3. Click a magnet link

Note: the issue is fixed after page reload
Note: not reproducible for torrent files.

## Actual result:

Empty page
![image](https://user-images.githubusercontent.com/34715963/69426999-d3207d80-0d2e-11ea-9de1-766e34670f60.png)

## Expected result:
Webtorrent extension view for that magnet link
![image](https://user-images.githubusercontent.com/34715963/69427022-e03d6c80-0d2e-11ea-9d6b-6d99112f6377.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

**Reproducible on**

Brave | 1.2.8 Chromium: 78.0.3904.108 (Official Build) dev (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

**Not reproducible on**

Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

Brave | 1.1.7 Chromium: 78.0.3904.108 (Official Build) beta (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel?

cc @brave/legacy_qa @feross @tomlowenthal @AndriusA

**Comment by GeetaSarvadnya** [comment]
Reproduced in windows


Brave | 1.2.10 Chromium: 78.0.3904.108 (Official Build) dev (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

**Comment by rebron** [comment]
cc: @yrliou Can you take a look?

**Comment by LaurenWags** [comment]
Reproduced on macOS

Brave | 1.2.23 Chromium: 79.0.3945.70 (Official Build) beta (64-bit)
-- | --
Revision | 65868db27916cebde51fc2465c9b34761e6383e2-refs/branch-heads/3945@{#869}
OS | macOS Version 10.13.6 (Build 17G5019)

**Comment by btlechowski** [comment]
Still reproducible

Brave | 1.13.77 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | 4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}
OS | Ubuntu 18.04 LTS


![image](https://user-images.githubusercontent.com/34715963/90762219-f9d30b00-e2e4-11ea-9e79-4e21b56ca987.png)

**Comment by fallaciousreasoning** [comment]
Should be fixed by https://github.com/brave/brave-core/pull/14568
