### ISSUE TITLE
Buy BAT with USD

### ISSUE THREAD

**Issue by SephReed** [brave/brave-browser#7064]
## Description 
This is the best guide I've found to buying BAT with USD:

 https://medium.com/@hikeemhigh/the-quickest-way-to-buy-basic-attention-token-bat-with-usd-e0ecd7b73364

I'd like to be able to buy more BAT so I can tip sites I like, content on youtube, or github users who are helpful.  

## Steps to Reproduce

   1. Open BAT wallet
   2. See that it's empty
   3. Search for a way to add money to it

## Actual result:
There is no easy way to add money to it

## Expected result:
I would be able to use PayPal or a card to add a few bucks.

## Actual Ask:
Is there a legal reason you guys can't do this?  I searched for maybe a regulation that blocks it, but found nothing.

**Comment by Ravendwyr** [comment]
Brave Rewards uses Uphold, which is somewhat similar to Coinbase.

Signing up for an Uphold account and linking your Brave Rewards wallet (known as "verifying" in the browser) will allow you to buy BAT through Uphold.  This can then be sent via Brave Rewards.

**Comment by SephReed** [comment]
As a feature request, it would be really nice to have the account creation flow available without leaving the brave BAT settings, and the connection between the two easily automated.

I'm totally capable of doing the work to set up some accounts and link them together, but for the sake of putting in 3 bucks and sending a quarter or two to random people here and there... it's a bit involved.

I'm not that worried about the security of $5-10.

**Comment by mandar-brave** [comment]
There is no easy way to buy BAT w/o having an exchange involved at the moment (and hence their account and requirements) . Also with the integrations we are also mandating the ID check - something we can change. Good feedback, however. There is work going on integrating crypto wallets so you can have the freedom to just move BAT there.

**Comment by mikedotexe** [comment]
In addition to Uphold, you can also send BAT from Coinbase or other exchanges, as I've done. I'm trying to participate in helping Brave, and think this issue can be closed to declutter things. I think https://community.brave.com is a better destination for Q&A.

**Comment by SephReed** [comment]
Feel free to move it wherever.

I'm probably not going to go through any of these methods, but I'd love to start sending money through your system once it becomes easy to do so.

**Comment by rebron** [comment]
Closing per last few comments, thanks @mikedotexe . We can move further discussion over to community.brave.com.
