### ISSUE TITLE
Hover over emoji on GitHub comment does not display tooltip with information

### ISSUE THREAD

**Issue by mbacchi** [brave/brave-browser#7066]
## Description 
Hovering over an emoji in a Github issue (ex: https://github.com/brave/brave-browser/issues/3982) doesn't show the tooltip (for lack of a better term) with the information about who added the emoji(screenshot below).

![image](https://user-images.githubusercontent.com/6763301/69447974-d73fa180-0d14-11ea-9ecb-41b62a832a89.png)

Chrome Version 78.0.3904.108 also displays this behavior (screenshot below).

![image](https://user-images.githubusercontent.com/6763301/69448005-e888ae00-0d14-11ea-8b7e-a73c5a8f918d.png)

In Firefox this works as expected (screenshot below).

![image](https://user-images.githubusercontent.com/6763301/69448042-fd654180-0d14-11ea-9bbc-14491183e54d.png)

## Steps to Reproduce

   1. Use Brave Nightly, Dev, Beta or Release
   2. Open Github issue https://github.com/brave/brave-browser/issues/3982
   3. Hover mouse over emoji in comment

## Actual result:
No tooltip (for lack of a better term) is shown.

## Expected result:
Tooltip is shown as in Firefox.

## Reproduces how often: 

100% reproducible

## Brave version (brave://version info)

```
Brave | 1.3.25 Chromium: 78.0.3904.108 (Official Build) nightly (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Linux
JavaScript | V8 7.8.279.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
Command Line | /opt/brave.com/brave-nightly/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=NewExtensionUpdaterService,PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,SyncUSSBookmarks,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,LookalikeUrlNavigationSuggestionsUI,UnifiedConsent --flag-switches-begin --flag-switches-end
Executable Path | /opt/brave.com/brave-nightly/brave
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by bsclifton** [comment]
Works great on 1.0.1 - can you please re-test, @mbacchi?

**Comment by mbacchi** [comment]
I still see it on Brave 1.0.1 even with shields down:

![image](https://user-images.githubusercontent.com/6763301/69745489-86a6ba80-10ff-11ea-899f-e8cfde54931b.png)

**Comment by bsclifton** [comment]
Weird- works for me on macOS, Windows, and even Ubuntu 18? Pic from Ubuntu 18
<img width="362" alt="Screen Shot 2019-11-27 at 10 23 27 AM" src="https://user-images.githubusercontent.com/4733304/69745809-2e23ed00-1100-11ea-9d5b-82a52238bdf0.png">


@mbacchi you're using Fedora right? What's the window manager? (GNOME?)

**Comment by mbacchi** [comment]
Yes, Fedora 30, using Gnome (with Wayland). Wayland may be the factor here, will test on Xorg in a moment.

**Comment by mbacchi** [comment]
Ok, indeed the issue was Wayland, as I should have expected. This works normally on Gnome using Xorg (the tried and true display server,) Wayland is the default on Fedora 30 but still has some shortcomings. I will close this as it obviously also affects Chrome on Wayland as well as Brave.

Screenshot below.

![image](https://user-images.githubusercontent.com/6763301/69752455-74804880-110e-11ea-970e-a319b21e9327.png)
