### ISSUE TITLE
MetaFox icon is not removed on upgrade[Followup to #6534]

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7069]
## Description 

MetaFox icon is not removed on upgrade[Followup to #6534]

## Steps to Reproduce

   1. Install older component version where MetaFox icon is shown 
   2. Upgrade to `1.0.13`
   3. Popup still shows MetaFox icon

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/69468443-2bb94000-0d5a-11ea-92b8-a151a6087461.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/69468456-37a50200-0d5a-11ea-8e47-e85119cbcd56.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Ethereum Remote Component `0.1.29`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by ryanml** [comment]
@srirambv can you double check this one? I don't think it's an issue anymore.

**Comment by srirambv** [comment]
Waiting for the device to be shipped. Will check and update the issue

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.6.18 Chromium: 80.0.3987.87 (Official Build) nightly (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
Component | `0.1.43`

- Verified installing component `1.0.10` shows MetaFox icon. Upgrading to component `0.1.43` removes the MetaFox icon
![image](https://user-images.githubusercontent.com/17010094/74306490-a6599080-4d88-11ea-9d1d-538f9b883e36.png)

--------
Verification passed on 

Brave | 1.3.91 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Windows 10 OS Version 1809 (Build 17763.914)
Component | `0.1.43`

- Verified installing component `1.0.10` shows MetaFox icon. Upgrading to component `0.1.43` removes the MetaFox icon
![image](https://user-images.githubusercontent.com/17010094/74313585-fa20a580-4d99-11ea-9176-e289cfc59890.png)

--------
Verification passed on 

Brave | 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Linux
Component | `0.1.43`

- Verified installing component `1.0.10` shows MetaFox icon. Upgrading to component `0.1.43` removes the MetaFox icon
![image](https://user-images.githubusercontent.com/17010094/74313925-98147000-4d9a-11ea-9c20-255aeb13223b.png)
