### ISSUE TITLE
Clicking on brave icon Crashes browser

### ISSUE THREAD

**Issue by aliglelo** [brave/brave-browser#7072]
# Description 
When ever i clicks brave icon in address bar for checking that which script is being blocked on any website by brave the browser crashes..

## Steps to Reproduce

   1. Open browser 
   2. visit any Website
   3. Click on brave Icon

## Expected result:
The Browser Crashes..

## Reproduces how often: 
Every time i do so

## Brave version (brave://version info)
Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)

## Version/Channel Information:
Stable channel I have

**Comment by simonhong** [comment]
@aliglelo  Thanks for the report :)
Did you enable `Extensions Toolbar Menu` feature  from brave://flags?

**Comment by aliglelo** [comment]
> @aliglelo Thanks for the report :)
> Did you enable `Extensions Toolbar Menu` feature from brave://flags?

yes..
But when I set it to default Problem was solved ...
Thanks for help

**Comment by simonhong** [comment]
Duplicated with https://github.com/brave/brave-browser/issues/5646.

@aliglelo Thanks for checking 👍 
FYI, I pushed https://github.com/brave/brave-core/pull/4065 for fixing this crash.
If my PR is merged, you will not see this crash with extension toolbar menu.
