### ISSUE TITLE
[Feature Request] Please Enable Password sync for Brave

### ISSUE THREAD

**Issue by aliglelo** [brave/brave-browser#7073]
Hello sir,
I am a die hard fan of Brave browser and want to request you to enable sync for passwords as is available for bookmarks across various devices..
Thanks!

**Comment by Merith-TK** [comment]
I second this, would make it much easier to have my passwords everywhere

**Comment by bsclifton** [comment]
+1 from https://twitter.com/joelatwar/status/1214768232998952966

**Comment by joel-g** [comment]
This is the only thing stopping me from uninstalling Chrome and Firefox

**Comment by bavalpey** [comment]
> Hello sir,
> I am a die hard fan of Brave browser and want to request you to enable sync for passwords as is available for bookmarks across various devices..
> Thanks!

I hope they don't do it as they do for the bookmarks across devices, considering that feature doesn't work.

**Comment by bsclifton** [comment]
Happy to share this will be addressed with Sync v2 😄 For folks wanting to follow along, check out https://github.com/brave/brave-browser/issues/9241 and hit the subscribe button

**Comment by aliglelo** [comment]
> Happy to share this will be addressed with Sync v2 smile For folks wanting to follow along, check out #9241 and hit the subscribe button

Thanks a lot .
Excited to view this change
