### ISSUE TITLE
Enable extension toolbar menu causes app crash

### ISSUE THREAD

**Issue by maharjanaman** [brave/brave-browser#7074]
## Description 

After enabling `Extensions Toolbar Menu` from `brave://flags` and then visiting any website and clicking on the Brave Shields icon causes the app to crash.

## Steps to Reproduce

   1. Go to `brave://flags`
   2. Search for `Extensions Toolbar Menu` and enable it.
   3. Visit any website and click the Brave Shields icon.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes

**Comment by simonhong** [comment]
Duplicated issue with https://github.com/brave/brave-browser/issues/5646
