### ISSUE TITLE
Video Full Screen, Big Delay?

### ISSUE THREAD

**Issue by n-8yte** [brave/brave-browser#7075]
_

> Have you searched for similar issues? Before submitting this issue, please check the open.
> - Yes i did, found nothing or overseen this a few times.

_
**Video Full Screen, Big Delay?**
Why is this so? when i double click a video on youtube(or other sides) its have a big delay to set it on fullscreen.. well thats ok.. but if i do it again to minimize it.. i need wait maybe 3-5 seconds again.. and when the video is still playing its more then annoying..

**Comment by rebron** [comment]
Closing. We're noting your feedback. Please follow the new issue template. We need much more detail to be able to address this issue.
