### ISSUE TITLE
[IDEA/Feature Request] When clicking on `.onion` address, offer to open in Tor Tab

### ISSUE THREAD

**Issue by Merith-TK** [brave/brave-browser#7078]
## Description 
So the idea kinda follows along the lines of this
when you click on a tornet link,  (`.onion`), or enter a .onion address in your browser, have a small popup that asks if you want to actually go to this adress, and if the user clicks "Yes" open a tortab with that URL

Or maybe set a default page or persistance book marks

**Comment by bsclifton** [comment]
Great suggestion, @Merith-TK 😄 I believe this is captured with https://github.com/brave/brave-browser/issues/806

I'll give that a bump and include your text above 😄
