### ISSUE TITLE
Browser webview crash when navigating back on any page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#708]
## Description 
Open Web store page from Show Apps option, click on go back button twice on web store page is causing browser crash

## Steps to Reproduce

   1. Open Brave Core with clean profile from CLI
   2. Click on 'Skip welcome tour' on welcome page
   3. Click on More Apps icon
   4. Observe web store page display
   5. Click on go back < button twice on web store page

## Actual result:
Browser crashes:

Crash Id:
Crash ID 304e326a-1be1-4b2a-abe2-2a95c37a55a1
![brave core - browser crash issue](https://user-images.githubusercontent.com/38657976/43858540-efc76e8e-9b6b-11e8-814a-37ee93980a41.gif)

## Expected result:
Browser should not crash

## Reproduces how often: 
Always

## Brave version (about:brave info) 
Version 0.53.1 Chromium: 69.0.3497.12 (Official Build) dev (64-bit)

### Reproducible on current release:
No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? - No
- Is the issue reproducible on the latest version of Chrome? -No

### Additional Information
cc: @bbondy

**Comment by srirambv** [comment]
Console log for the crash 
```
$ npm run start Release

> brave@0.54.0 start C:\brave-browser
> node ./scripts/commands.js start "Release"

C:\brave-browser\src\out\Release\brave.exe --enable-logging --v=0 --disable-brave-update
[11192:15496:0808/082640.122:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.
[11192:12096:0808/163945.628:ERROR:socket_stream.cc(210)] Closing stream with result -100
[11192:12096:0808/170053.364:ERROR:socket_stream.cc(210)] Closing stream with result -100
[11192:15496:0808/170415.690:ERROR:media_internals.cc(102)] Cannot get RenderProcessHost
null
null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave@0.54.0 start: `node ./scripts/commands.js start "Release"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brave@0.54.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Owner\AppData\Roaming\npm-cache\_logs\2018-08-08T21_28_50_288Z-debug.log
```

**Comment by srirambv** [comment]
I can consistently reproduce the crash with following str as well
1. Open a new tab
2. Visit duckduckgo.com 
3. Use mouse back button to navigate back
4. Tab crashes but still navigates back to new tab

**Comment by GeetaSarvadnya** [comment]
Issue still persists hence reopening the issue.

Crash Id:
Uploaded Crash Report ID a95cccd79d4dbc34 (Local Crash ID: cfc29331-1645-452f-9e28-80a013ab9d52)
Crash report captured on Tuesday, August 21, 2018 at 12:37:39 PM, uploaded on Tuesday, August 21, 2018 at 12:38:30 PM
![browser crash_click back button](https://user-images.githubusercontent.com/38657976/44386171-5ad17800-a53f-11e8-9788-41f4d6d8bf84.gif)

**Comment by srirambv** [comment]
This needs to be tested on the next build. Fix is not part of 0.54.x build.

**Comment by srirambv** [comment]
Able to crash the browser when navigating back. Console logs `Segmentation Fault` 
Crash ID  4256b899aed41f09 
![708](https://user-images.githubusercontent.com/17010094/44597323-34107d00-a79d-11e8-9172-73d5006223c3.gif)


cc: @bbondy

**Comment by GeetaSarvadnya** [comment]
Issue still persists. Please find the below crash id:
 Crash Report ID fbbb40e8d0ba1e18
