### ISSUE TITLE
Enable widevine cdm component updater in linux

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#7081]
With C79, linux can component updater for widevine cdm.
Currently, we use our own widevine updater. So, need to integrate both.

In linux, brave://components should have widevine component entry.

**Comment by rebron** [comment]
@simonhong Is this one still needed? or a dupe?

**Comment by simonhong** [comment]
@rebron This issue is still valid.
We don't use component updater for widevine for now. This is is for using component updater.

**Comment by mherrmann** [comment]
I want to mention my PR https://github.com/brave/brave-core/pull/7164 here. Maybe it is related.

If I read Chromium's code correctly, then components are installed by registering them with version 0.0.0.0 and then waiting for an automatic update to install the correct version. Automatic updates are (currently broken in Brave)[https://github.com/brave/brave-browser/issues/10464] for those components that are not hosted on Brave's own component update server. Brave seems to implicitly rely on this to prevent unwanted components from being installed: By not hosting them, the automatic update check fails and the component isn't installed.

The Widevine plugin is an exception to the above. It is not hosted on Brave's server for licensing reasons. However, to still be installed, it has a workaround in brave-core to perform an immediate on-demand update check. Unlike automatic updates, on-demand update checks do work and so Widevine is installed:

    void RegisterAndInstallWidevine() {
      // This code is similar to RegisterWidevineCdmComponent_ChromiumImpl
      // but that ignores the callback, and we handle it so we can force
      // an on demand update.
      ...

@simonhong does the above have any implications on your work on this issue? In particular, will your code still work once automatic component updates work again?

More info about exactly why and how automatic component updates are currently broken can be found at https://github.com/brave/brave-browser/issues/10464#issuecomment-727839960.

**Comment by simonhong** [comment]
@mherrmann Thanks for sharing. I didn't know why we do explicit on-demend update.
I think your work will not affect my work for current issue. With your PR, widevine will also can get update in background. :)
Then, I think we can remove explicit on-demand update.

**Comment by mherrmann** [comment]
Okay, great! :)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.20.86 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/7228
**Test with clean profile**
Verified widevine is not available from `brave://components` on clean profile
![image](https://user-images.githubusercontent.com/34715963/105392923-0ead2500-5c1c-11eb-84ad-d0ea554ce55c.png)
Verified widevine is available from `brave://components` after installation
![image](https://user-images.githubusercontent.com/34715963/105393445-a579e180-5c1c-11eb-8a0e-320fbac1cea7.png)
Verified able to watch netflix:
![image](https://user-images.githubusercontent.com/34715963/105393273-71062580-5c1c-11eb-9f87-771260ef7ee8.png)

**Test with old profile(widevine enabled)**
Verified widevine is available from brave://components and it's version is 4.10.1610.0
![image](https://user-images.githubusercontent.com/34715963/105394280-ad865100-5c1d-11eb-8020-ea7e517a4aab.png)
Verified able to watch netflix:
![image](https://user-images.githubusercontent.com/34715963/105394357-c262e480-5c1d-11eb-9fe3-9f719da6518b.png)
