### ISSUE TITLE
Blue frame on top of the screen when viewing fullscreen video

### ISSUE THREAD

**Issue by pilsnerbeer** [brave/brave-browser#7084]
## Description 
A blue frame on top of the screen can be observed when playing fullscreen videos using the in-built video player.

I think the visibility of the frame depends on the ratio of the video - meaning not all video files will be shown with this frame but movies with black bars on top & bottom have this issue.

## Steps to Reproduce

   1. Play a video with standard movie aspect ratio (with black bars on top and bottom)
   2. Go fullscreen
   3. Blue lines can be observed on top of the screen.

## Actual result:

![IMG_20191123_235535](https://user-images.githubusercontent.com/36133540/69540589-47edf480-0f87-11ea-8278-fd80e7a53c31.jpg)

## Reproduces how often: 
Always on certain aspect ratios

## Brave version (brave://version info)

Brave | 1.0.0 Chromium: 78.0.3904.97 (Official Build) unknown (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Linux

**Comment by pilsnerbeer** [comment]
edit: The frame is also visible on the bottom part of the screen (Didnt notice because of video controls that overlap the frame but when they hide you can see it).

**Comment by bsclifton** [comment]
@pilsnerbeer can you try toggling this flag please?
brave://flags/#enable-oop-rasterization

I'm curious if there's any difference. May require a restart after changing the value

**Comment by pilsnerbeer** [comment]
Issue still present after toggling #enable-oop-rasterization.

**Comment by bsclifton** [comment]
@pilsnerbeer ok great thanks for reporting back! You can set that back to on (it does increase performance, so best to have on if there are no graphical issues)

**Comment by pilsnerbeer** [comment]
I should've noted that the issue is observed across both Linux and Windows. The PC for Linux (Manjaro, KDE) runs Intel CPU with integrated graphics chip and the other PC (Windows 10 Pro) uses an Nvidia Geforce GPU.

**Comment by bsclifton** [comment]
@pilsnerbeer great, thanks for the additional info. Stupid question (just want to make sure): do you have the most recent drivers on both platforms?

**Comment by pilsnerbeer** [comment]
Yes, I do. I've had more problems with the video player ( see #7053 ) and I'm not sure what the cause is.

**Comment by rebron** [comment]
@pilsnerbeer Is this still happening with a latest version? we're on 1.2.43. Are your drivers the latest version?

**Comment by bsclifton** [comment]
Closing as stale since there hasn't been a response. Please do re-open if this is still happening with the latest version (1.5.115)
