### ISSUE TITLE
Brave for Mac crashes always and almost immediately as of today.

### ISSUE THREAD

**Issue by jtheletter** [brave/brave-browser#7086]
Config:
- Brave Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
- macOS 10.15.1 (19B88) Catalina

Steps to produce:
- Launch Brave, navigate somewhere (eg google "test"), click a link—CRASH.
- Launch Brave, navigate somewhere (eg google "test"), open a second tab, navigate somewhere—CRASH.

Troubleshooting:
- I've downloaded and reinstalled the latest version. 
- I've deleted the sync chain. 
- I've deleted all cookies and storage. 
- I've disabled all extensions.
- I've disabled start-where-left-off-upon-launch.
- I've tried incognito. 
- Problem didn't exist before today. 
- I've tried the latest Nightly version 78.1.3.30, problem exists there too. 
- I've tried an older Dev version 78.1.2.2, problem exists there too.
- I've tried an older Brave version 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit), problem exists there too. I see that it tries to auto-update its version, and it appears stuck on that, not sure if that's a factor, and I don't see how to disable that. 
- I've tried an even older Brave version 78.0.70.121 (released October 23), Apple won't let me launch it, saying: "“Brave Browser.app” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information."—with no option to override in System Preferences. 
- After downloading the above alternative versions, I've deleted all Brave app from `/Applications/` and downloaded the latest default version again, and the problem still exists.

**Comment by jtheletter** [comment]
Issue seems resolved now by running Disk Utility app's First Aid on "Macintosh HD - Data" volume.

**Comment by bsclifton** [comment]
@jtheletter thanks for the update!
cc: @Brave-Matt
