### ISSUE TITLE
Vertical lines display in the URL pop up when user hit gmail in the URL bar

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#709]
## Description 
Vertical lines display in the URL pop up when user hit gmail in the URL bar

## Steps to Reproduce

   1. Open Brave core
   2. Enter gmail.com in the URL bar
   

## Actual result:
![image 1](https://user-images.githubusercontent.com/38657976/43859724-1a28047e-9b6f-11e8-9f3c-31aa6dff09d1.png)

## Expected result:
There should not be any vertical lines display 

## Reproduces how often: 
Always

## Brave version (about:brave info) 
Version 0.53.1 Chromium: 69.0.3497.12 (Official Build) dev (64-bit)

### Reproducible on current release:
No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? - No
- Is the issue reproducible on the latest version of Chrome? - No

### Additional Information
cc: @bbondy

**Comment by GeetaSarvadnya** [comment]
@rebron Apologies for the delay in reply. I am not seeing this issue in recent builds (Verified on 0.58.16 0.58.18 and 0.59.20 and dev build 0.60.6)

**Comment by kjozwiak** [comment]
Closing the issue as I haven't ran into the issue and haven't heard of any reports from the community. @GeetaSarvadnya if you experience this again, please re-open 👍
