### ISSUE TITLE
[Android] Replace home button with new tab button when homepage is disabled

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#7090]
## Description 
1. Disable Home button through homepage preference, it should be replaced by a New Tab button.
2. Long click on the new tab button should show a popup menu. 
![Screenshot_20200225-142959](https://user-images.githubusercontent.com/4730197/75293600-60b2b400-57db-11ea-8d69-a7165ecf37ed.png)

original issues: 
https://github.com/brave/browser-android-tabs/issues/1707 
https://github.com/brave/browser-android-tabs/issues/1894

ref PRs
https://github.com/brave/browser-android-tabs/pull/1963
https://github.com/brave/browser-android-tabs/pull/2032

**Comment by yrliou** [comment]
Just found that there is a prerequisite (https://github.com/brave/browser-android-tabs/pull/1397) we have to port first in order to port this issue, I'll probably re-scope this issue to port these two together. cc @SergeyZhukovsky

**Comment by yrliou** [comment]
Opened https://github.com/brave/brave-browser/issues/7215 for adding accessibility labels to toolbars first.

**Comment by yrliou** [comment]
Test plan specified in https://github.com/brave/brave-core/pull/4746

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.110 x64 stable build
- Verified disabling home button shows New tab button
![image](https://user-images.githubusercontent.com/17010094/76405070-9a73e500-63ad-11ea-983a-a89d93f0670a.png)
- Verified long press on new tab button shows context menu for new tab and private tab
![image](https://user-images.githubusercontent.com/17010094/76405054-95169a80-63ad-11ea-8b1c-a75bbbbfc4f7.png)
