### ISSUE TITLE
Brave browser lockups

### ISSUE THREAD

**Issue by Raycoms** [brave/brave-browser#7092]
# Description 

Fairly regularly when loading and rendering a page, brave locks my entire computer.

## Steps to Reproduce

   1.  Surf normally
   2. Switch between tabs and load new tabs
   3. "lag" on the entire computer level

## Actual result:

I've noticed that at these moments of lag in htop the CPU usage spikes heavily.

## Expected result:
Of course I'd expect it to not lag at all.

## Reproduces how often: 

Intermittent issue

## Brave version (brave://version info)

1.0.0-1

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Yes
- Can you reproduce this issue with the dev channel?
Not tried
- Can you reproduce this issue with the nightly channel?
Not tried
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:

I think this gist is interesting since it seems to show what is happening.
https://gist.github.com/Raycoms/d8cd1b9397fe6187483e4c09a14068ba

**Comment by fusionneur** [comment]
Looks like your cpu is getting hot. You should first analyze the rest of the processes. Don't think it's an issue caused by brave..

**Comment by Raycoms** [comment]
All other things run fine though, and it doesn't happen with chrome.

**Comment by Raycoms** [comment]
![image](https://user-images.githubusercontent.com/6438347/69641186-82669880-103e-11ea-9571-a0170ab064fb.png)

This is from htop.

**Comment by Martina-Neumayer** [comment]
@Raycoms Give us please output from:
inxi -Fxz

**Comment by Raycoms** [comment]
```
System:    Host: ray-laptop Kernel: 4.19.85-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.2.0 Desktop: Xfce 4.14.1 
           Distro: Manjaro Linux 
Machine:   Type: Laptop System: Notebook product: N8xEJEK v: N/A serial: <filter> 
           Mobo: Notebook model: N8xEJEK serial: <filter> UEFI: American Megatrends v: 5.13 date: 04/13/2018 
Battery:   ID-1: BAT0 charge: 36.8 Wh condition: 38.4/59.9 Wh (64%) model: Notebook BAT status: Charging 
CPU:       Topology: 6-Core model: Intel Core i7-8750H bits: 64 type: MT MCP arch: Kaby Lake rev: A L2 cache: 9216 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 53004 
           Speed: 800 MHz min/max: 800/4100 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 800 5: 800 6: 800 7: 800 8: 800 
           9: 800 10: 800 11: 800 12: 800 
Graphics:  Device-1: Intel UHD Graphics 630 vendor: CLEVO/KAPOK driver: i915 v: kernel bus ID: 00:02.0 
           Device-2: NVIDIA GP107M [GeForce GTX 1050 Ti Mobile] vendor: CLEVO/KAPOK driver: nvidia v: 430.64 bus ID: 01:00.0 
           Display: x11 server: X.org 1.20.5 driver: modesetting,nvidia resolution: <xdpyinfo missing> 
           OpenGL: renderer: GeForce GTX 1050 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 430.64 direct render: Yes 
Audio:     Device-1: Intel Cannon Lake PCH cAVS vendor: CLEVO/KAPOK driver: snd_hda_intel v: kernel bus ID: 00:1f.3 
           Device-2: NVIDIA GP107GL High Definition Audio driver: snd_hda_intel v: kernel bus ID: 01:00.1 
           Sound Server: ALSA v: k4.19.85-1-MANJARO 
Network:   Device-1: Intel Wireless-AC 9560 [Jefferson Peak] driver: iwlwifi v: kernel port: 5000 bus ID: 00:14.3 
           IF: wlo1 state: up mac: <filter> 
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: CLEVO/KAPOK driver: r8169 v: kernel 
           port: 3000 bus ID: 03:00.1 
           IF: enp3s0f1 state: down mac: <filter> 
           IF-ID-1: br-d57b4d7ef0d3 state: down mac: <filter> 
           IF-ID-2: docker0 state: down mac: <filter> 
Drives:    Local Storage: total: 465.77 GiB used: 134.14 GiB (28.8%) 
           ID-1: /dev/sda vendor: Western Digital model: WDS250G2B0B-00YS70 size: 232.89 GiB 
           ID-2: /dev/sdb vendor: Samsung model: SSD 850 EVO mSATA 250GB size: 232.89 GiB 
Partition: ID-1: / size: 143.69 GiB used: 134.11 GiB (93.3%) fs: ext4 dev: /dev/sda5 
Sensors:   System Temperatures: cpu: 54.0 C mobo: N/A gpu: nvidia temp: 50 C 
           Fan Speeds (RPM): N/A 
Info:      Processes: 322 Uptime: 1h 24m Memory: 15.52 GiB used: 7.18 GiB (46.3%) Init: systemd Compilers: gcc: 9.2.0 
           clang: 9.0.0 Shell: bash v: 5.0.11 inxi: 3.0.36 
```

**Comment by Raycoms** [comment]
This is still happening with Brave, and I had to switch temporarily to chrome now because it doesn't temporarily lock up my computer while browsing.

**Comment by bsclifton** [comment]
There is a known GPU issue we have [which we're fixing](https://github.com/brave/brave-core/pull/4318)- I'd like to ask if folks can try changing a config value

@Raycoms can you please try visiting brave://flags/#enable-oop-rasterization and then DISABLING this flag? May require a restart of Brave after changing. But worth a shot. Please let us know!

**Comment by Raycoms** [comment]
I feel like it is happening a little bit less again now, but it is still happening.

**Comment by Raycoms** [comment]
Correction, it doesn't happen less. Just seemed like this for a few minutes.

**Comment by Martina-Neumayer** [comment]
@Raycoms Update your kernel.. 4.19 is a bit old one as for the Arch based system ;)
Btw.. You can also look here..
https://github.com/brave/brave-browser/issues/6098

**Comment by Martina-Neumayer** [comment]
For me disabling the OOP rasterization changes nothing. Hangs are still there.

**Comment by Raycoms** [comment]
Oh nice, didn't know there was another open issue yet. Similarly to how you described it, it started after an Nvidia driver update for me. But it doesn't happen with any other browser at all (At least not with chrome or firefox) so it must be something brave specific.

**Comment by Martina-Neumayer** [comment]
@Raycoms Yes.. Seems that it happened every time the nvidia driver update is released. I think the entire Chromium base is affected as well from this issue.

**Comment by bsclifton** [comment]
Closing this issue as stale - for folks experiencing this, I'd recommend checking out one of these two issues:
- Brave freezes or hangs on launch #9481
- https://github.com/brave/brave-browser/issues/8436
