### ISSUE TITLE
Brave Rewards : Monthly Contribution : Copy Updates

### ISSUE THREAD

**Issue by alexwykoff** [brave/brave-browser#7093]
Monthly Contributions are about to migrate from Beta to production. 

There are 3 spots for copy updates noticed in Nightly (1.3.30) which would reduce confusion and are being requested for implementation and uplift ahead of the migration.

The 3 locations are : 
- [ ] Monthly Contribution Banner
- [ ] Rewards Settings : Monthly Contribution Panel
- [ ] Rewards Settings : Pending Contributions Modal

Details are available in https://docs.google.com/document/d/19NAnjY9-TpsK2W0VN6GWAHIsrIrroAN45yERKqbcFBk/edit

**Comment by NejcZdovc** [comment]
partially implemented, wait for spec to be finalized

**Comment by NejcZdovc** [comment]
Implemented completely

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.2.29 Chromium: 79.0.3945.79 (Official Build) beta (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from https://github.com/brave/brave-core/pull/4086
Banner for Unverified Publisher:
<img width="1186" alt="Screen Shot 2019-12-18 at 2 42 03 PM" src="https://user-images.githubusercontent.com/28145373/71120258-07f6e780-21aa-11ea-9c58-8a3f4b7bc5f1.png">

Banner for Verified Publisher (not custom):
<img width="1193" alt="Screen Shot 2019-12-18 at 2 42 40 PM" src="https://user-images.githubusercontent.com/28145373/71120263-0a594180-21aa-11ea-98fd-0359e4aa30bb.png">

Custom banner for Verified Publisher:
<img width="1190" alt="Screen Shot 2019-12-18 at 2 42 59 PM" src="https://user-images.githubusercontent.com/28145373/71120270-0cbb9b80-21aa-11ea-8922-8bb0b28c7433.png">

Monthly Contributions panel:
<img width="657" alt="Screen Shot 2019-12-18 at 3 15 45 PM" src="https://user-images.githubusercontent.com/28145373/71120276-104f2280-21aa-11ea-9bd0-a9dde070caed.png">

Pending Contributions list:
<img width="974" alt="Screen Shot 2019-12-18 at 3 19 49 PM" src="https://user-images.githubusercontent.com/28145373/71120278-1218e600-21aa-11ea-9705-d7bb4a0d737c.png">
