### ISSUE TITLE
[Android] Port `Update onboarding for rewards with TOS`

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#7096]
Port https://github.com/brave/browser-android-tabs/pull/2191 into brave-core.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 x64 build
- Verified there is no check box for rewards
- Verified `Turn on` button is shown for rewards onboarding screen
- Verified `ToS` links to Brave Rewards TOS on `basicattentiontoken.org/user-terms-of-service/`
![image](https://user-images.githubusercontent.com/17010094/73097858-2a210b00-3eb6-11ea-8e62-d7184502a0c4.png)

-------
Verification passed on OnePlus 6T with Android 10 x64 build
- Verified there is no check box for rewards
- Verified `Turn on` button is shown for rewards onboarding screen
- Verified `ToS` links to Brave Rewards TOS on `basicattentiontoken.org/user-terms-of-service/`
![image](https://user-images.githubusercontent.com/17010094/73097907-43c25280-3eb6-11ea-87ad-f49da92ffbaa.png)

-------
