### ISSUE TITLE
Can't recover wallet after recovery key length change

### ISSUE THREAD

**Issue by tlivings** [brave/brave-browser#7100]
## Description 

I am trying to import an older wallet from when the recovery key was 16 words long. I am unable to import.

Similar to this older issue I found: https://github.com/brave/browser-laptop/issues/14856

## Steps to Reproduce

Try to import a backed up wallet from 2017.

## Actual result:

The import button is inactive and the error message "Seed phrases are 24 words long" is displayed.

## Expected result:

Backward compatibility with older wallets.

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

Brave | 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.14.6 (Build 18G95)
JavaScript | V8 7.8.279.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36

## Miscellaneous Information:

I have several hundred dollars in this wallet so it would be nice to be able to recover.

**Comment by bsclifton** [comment]
Sorry that you ran into an issue, @tlivings - would you be able to create a thread on https://community.brave.com/c/brave-rewards ? You can just link here for the details - folks should be able to help

Do you know offhand if the wallet was bitcoin? or BAT? We did remove some of the code which handled bitcoin wallets, so I could see that being a problem

**Comment by tlivings** [comment]
It was BAT.

Thanks.
