### ISSUE TITLE
Change copy to clarify that Verifying wallet is an optional task

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#7102]
## Description 

Please change the wording in the dialog below. @NejcZdovc 

![dialog-verify-3](https://user-images.githubusercontent.com/4369856/69661696-b8544e80-1037-11ea-806a-e285f1bb14c4.png)

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.3.85 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | macOS Version 10.14.6 (Build 18G103)

* Verified test plan from https://github.com/brave/brave-core/pull/4099
* Verified when accessing the wallet modal from `Verify Wallet` button, `Add Funds`, `Withdraw Funds`, and `verify` links on brave://rewards
* Verified when accessing the wallet modal from `Verify Wallet` button and `Add Funds` from BR panel

<img width="695" alt="Screen Shot 2020-01-07 at 10 41 07 AM" src="https://user-images.githubusercontent.com/28145373/71907825-d0d97d80-313a-11ea-8252-fcd49a1ebbdd.png">
