### ISSUE TITLE
Use the DuckDuckGo "Smarter Encryption" list

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#7105]
DuckDuckGo recently released an expanded version of the HTTPS Everywhere list: https://spreadprivacy.com/duckduckgo-smarter-encryption/

The crawler which generates the list is [Open Source](https://github.com/duckduckgo/smarter-encryption) but the [list](http://staticcdn.duckduckgo.com/https/smarter_encryption_latest.tgz) itself would probably require talking to them since it's CC-BY-NC-SA.

The list format is different from HTTPS Everywhere though, it's just a list of hostnames, one per line. Also, it's 253 MB (112 MB gzipped) so we probably wouldn't want to have all users download it.

**Comment by pipboy96** [comment]
@fmarier I'll try to look how large this list would be if compressed using a radix trie, possibly combined with gzip/zstd/LZMA/some better algorithm you possibly suggest. Also only entries that are not upgraded by HTTPSE or HSTS preloading should be included, which would make the list even smaller.

**Comment by fmarier** [comment]
Until we have permission to use the list from DDG, we can't proceed with this.

**Comment by fmarier** [comment]
We are now focusing on https-by-default and so we won't be changing lists for the HTTPS Everywhere feature.
