### ISSUE TITLE
Tips panel is not updated after sending a one-time tip and monthly tips to pubs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7106]
## Description 

Tips panel is not updated after sending a one-time tip and monthly tips to pubs

## Steps to Reproduce

   1. Clean profile 2.0.0
   2. Enable rewards and fund the wallet
   3. Send a one-time tip and monthly tip to a verified pub
   4. After sending a tip, pubs are not reflected in Tips panel and total tips for this month is not updated
   5. Reload brave://rewards page, Tips panel is still empty

## Actual result:

After sending a tip, pubs are not reflected in Tips panel and total tips for this month is not updated

## Expected result:
Pubs should be reflected in tips panel and Total tips for this month should be reflected

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave 2.0.0 Chromium 78.1.3.15

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @emerick @yrliou @SergeyZhukovsky

**Comment by srirambv** [comment]
This issue is still reproducible. Logged #7912  as a follow up issue. Marking this as qa/no and moving out of milestone
