### ISSUE TITLE
Wallet balance isn't reflected in rewards settings page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7107]
## Description 

Wallet balance isn't reflected in rewards settings page
## Steps to Reproduce

   1. Clean profile 2.0.0 
   2. Enable rewards
   3. Fund the wallet through uphold.com
   4. Wallet balance isn't reflected in the rewards settings page 
   5. Click on BR panel and observe balance is reflected in BR panel
   6. Restart the browser and observe balance isn't reflected in the rewards settings page
   7. Send a one-time tip to a verified pub and see balance is reflected in the rewards settings page  
   
   

## Actual result:

Wallet balance isn't reflected in the rewards settings page
![Screenshot_2019-11-27-00-46-23](https://user-images.githubusercontent.com/38657976/69668457-f55f2600-10b5-11ea-9107-5ece79230c6e.png)
![Screenshot_2019-11-27-00-46-34](https://user-images.githubusercontent.com/38657976/69668466-fa23da00-10b5-11ea-8ed1-7570f4e30928.png)

## Expected result:
After funding wallet, the balance should get reflected in the rewards settings page

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave 2.0.0 Chromium 78.1.3.15
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @emerick @yrliou @SergeyZhukovsky

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.58 x64 build
- Verified panel and wallet summay shows correct wallet balance
- Verified tipping a publisher still shows balance on both panel and wallet summary on rewards page
![image](https://user-images.githubusercontent.com/17010094/73109494-3feff980-3ed1-11ea-8ec7-68dcd5c2d416.png)

------
Verification passed on Samsung Tab A with Android 9 running 1.5.58 x64 build
- Verified panel and wallet summay shows correct wallet balance
- Verified tipping a publisher still shows balance on both panel and wallet summary on rewards page
![image](https://user-images.githubusercontent.com/17010094/73109488-3b2b4580-3ed1-11ea-8d8f-900e9bd60de2.png)
