### ISSUE TITLE
Brave breaks Norwegian Bank ID authentication system

### ISSUE THREAD

**Issue by atombender** [brave/brave-browser#7108]
## Description 

This issue affects all systems that use the Bank ID system (e.g. banks like [Sbanken](https://sbanken.no/) and [Storebrand](https://nettbank.storebrand.no/)), including the big Norwegian government portal, [Altinn](https://altinn.no/).

In my opinion, **blocking all banks and government agencies in a single country is not okay**.

The issue has persisted since whatever release was done in October. It was working fine before. Chrome works fine.

## Steps to Reproduce

   1. Go to any Bank ID site
   2. Try logging in

## Actual result:

Brave blocks the cookies necessary to fulfill login, even with "Shields" turn off.

## Expected result:

Brave should work, at least with "Shields" off.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

```
Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | macOS Version 10.15.1 (Build 19B88)
```

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? Didn't try
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by atombender** [comment]
This seems to be resolved in 1.1.23.

**Comment by bsclifton** [comment]
Thanks for following up, @atombender - I'll close this out for now. Please re-open if the problem happens again 😄

**Comment by arnholm** [comment]
Hello, I am experiencing this exact problem now with several Norwegian banks, all requiring Bank ID. Logging in is not possible, however it works fine using Waterfox for these banks. This  happens for both Windows and Linux Kubuntu:

Brave	1.10.90 Chromium: 83.0.4103.97 (Official Build) (64-bit)
Revision	326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS	Linux

Brave	1.9.80 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision	8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS	Windows 10 OS Version 2004 (Build 19041.329)

I have recently started using Brave, so I don't know when this problem resurfaced.
