### ISSUE TITLE
Rewards summary is showing `Your Balance` instead of `Your Wallet`

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7109]
## Description 

Rewards summary is showing `Your Balance` instead of `Your Wallet`

## Steps to Reproduce

   1. Clean profile 2.0.0
   2. Enable rewards
   3. Check rewards settings page and rewards summary page
   4. Rewards summary is showing `Your Balance` instead of `Your Wallet`
   

## Actual result:

Rewards summary is showing `Your Balance` instead of `Your Wallet`
![image](https://user-images.githubusercontent.com/38657976/69669290-926e8e80-10b7-11ea-8979-72c8f10039d5.png)

![image](https://user-images.githubusercontent.com/38657976/69669088-29871680-10b7-11ea-9321-258a0ece3fb1.png)

![image](https://user-images.githubusercontent.com/38657976/69669348-ae723000-10b7-11ea-9e28-be90e3fe5dd4.png)

## Expected result:
`Your Wallet` should be shown in rewards setting page, summary page, and BR panel to maintain the consistency 

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave 2.0.0 Chromium 78.1.3.15

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @emerick @yrliou @SergeyZhukovsky

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.58 x64 build
- Verified `Your Wallet` is consistently used in Panel/Wallet summary and Rewards page
![image](https://user-images.githubusercontent.com/17010094/73107281-6d39a900-3ecb-11ea-84b4-ae5edee539be.png)

-----
Verification passed on OnePlus 6T with Android 10 running 1.5.58 x64 build
- Verified `Your Wallet` is consistently used in Panel/Wallet summary and Rewards page
![image](https://user-images.githubusercontent.com/17010094/73107291-732f8a00-3ecb-11ea-8bc5-82aa3091497a.png)
