### ISSUE TITLE
Site favicons are not displayed for the pubs which are added in a-c table

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7111]
## Description 

Site favicons are not displayed for the pubs which are added in a-c table
## Steps to Reproduce

   1.  Clean profile 2.0.0
   2.  Enable rewards 
   3. Add few verified and not-verified pubs into a-c table
   4. Site favicons are not displayed for the pubs in a-c table

## Actual result:

Site favicons are not displayed for the pubs which are added in a-c table
![image](https://user-images.githubusercontent.com/38657976/69672960-390a5d80-10bf-11ea-85e2-d3dac5e42f67.png)

## Expected result:
Site favicons should be displayed for the pubs which are added in a-c table

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave 2.0.0 Chromium 78.1.3.15
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @emerick @yrliou @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
We have such thing in our old repo to make favicons work https://github.com/brave/brave-core/blob/master/browser/ui/webui/brave_rewards_page_ui.cc#L293. But I had a link error on a brave-core based app. We need to figure out why

**Comment by emerick** [comment]
It looks like `favicon_source.cc` is no longer built on Android, as it wasn't being used on that platform in Chromium:

https://chromium-review.googlesource.com/c/chromium/src/+/1651114

Will see if I can reinstate it in our build.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.58 x64 build
- Verified favicon is listed for verified publishers
- Verified favicon is listed for non-verified publishers
- Verified favicon is listed for verified YT publishers
- Verified generic favicon is listed for sites without favicon
![image](https://user-images.githubusercontent.com/17010094/73107745-a1619980-3ecc-11ea-913b-1642ce7f4db5.png)
-----
Verification passed on Samsung Tab A with Android 9 running 1.5.58 x64 build
- Verified favicon is listed for verified publishers
- Verified favicon is listed for non-verified publishers
- Verified favicon is listed for verified YT publishers
- Verified generic favicon is listed for sites without favicon
![image](https://user-images.githubusercontent.com/17010094/73107774-b4746980-3ecc-11ea-88b9-be1fd01c0a32.png)
-----
