### ISSUE TITLE
Excluded sites cannot be re-added to a-c table

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7112]
## Description 

Excluded sites cannot be re-added to a-c table
## Steps to Reproduce

   1. Clean profile 2.0.0
   2. Enable rewards 
   3. Add a few sites to a-c table
   4. Exclude a site from a-c table
   5. Visit the excluded site and spend min time
   6. Site isn't getting added to a-c table

## Actual result:

Excluded sites cannot be re-added to a-c table
## Expected result:
Excluded sites should be readded to a-c table

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave 2.0.0 Chromium 78.1.3.15

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @emerick @yrliou @SergeyZhukovsky

**Comment by emerick** [comment]
@GeetaSarvadnya @NejcZdovc Wouldn't this be working as expected? I would think if you explicitly exclude a site it won't be readded into the auto-contribution table until you remove it from the exclusions, but maybe I'm wrong.

**Comment by LaurenWags** [comment]
I wonder if @GeetaSarvadnya is missing a step, maybe between steps 4 and 5 it should be deleted from the Excluded Sites list (thus making it eligible to be re-added to AC list).

@GeetaSarvadnya when you're back, can you take a look at this one again?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.58 x64 build
- Verified excluded publisher can be readded back when include is enabled via panel
-----------
Verification passed on Samsung Tab A with Android 9 running 1.5.58 x64 build
- Verified excluded publisher can be readded back when include is enabled via panel
-----------
