### ISSUE TITLE
Can't uncheck the Tip settings for Reddit, Twitter and GitHub

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7113]
## Description 

Can't uncheck the Tip settings for Reddit, Twitter and GitHub
## Steps to Reproduce

   1. Clean profile 2.0.0
   2. Enable rewards
   3. Navigate to Tips settings page
   4. Try to uncheck the checkbox for Reddit, Twitter and GitHub
   5. Can't uncheck the Tip settings for Reddit, Twitter and GitHub

## Actual result:

Can't uncheck the Tip settings for Reddit, Twitter and GitHub
![image](https://user-images.githubusercontent.com/38657976/69674224-0dd53d80-10c2-11ea-859d-8c304e4fa841.png)

## Expected result:
Should be able to uncheck the Tip settings for Reddit, Twitter and GitHub

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave 2.0.0 Chromium 78.1.3.15
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @emerick @yrliou @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
not sure we have that at all on old version, maybe we need to hide it for now?

**Comment by emerick** [comment]
It was just a missing case in the reducer, so I added it.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.58 x64 build
- Verified individual platform can be unchecked
![image](https://user-images.githubusercontent.com/17010094/73107897-f8676e80-3ecc-11ea-8ae2-e0eca26efbf0.png)

-------
Verification passed on OnePlus 6T with Android 10 running 1.5.58 x64 build
- Verified individual platform can be unchecked
![image](https://user-images.githubusercontent.com/17010094/73107906-fc938c00-3ecc-11ea-8f1d-a1b5177090f2.png)
