### ISSUE TITLE
`Show All` link isn't shown in a-c table after excluding a publisher from table

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7114]
## Description 

`Show All` link isn't shown in a-c table after excluding a publisher from table

## Steps to Reproduce

   1. Clean profile 2.0.0
   2. Enable rewards
   3. Add few verified and not verified pubs into a-c table
   4. Exclude a pubs from table
   5. Show All link isn't shown in a-c table

## Actual result:

`Show All` link isn't shown in a-c table after excluding a publisher from table

## Expected result:

`Show All` link should be shown in a-c table after excluding a publisher from table
## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave 2.0.0 Chromium 78.1.3.15

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @emerick @yrliou @SergeyZhukovsky

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya please don't add android issues to Rewards project.

cc @brave/legacy_qa

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.5.58 x64 build
- Verified excluding a side, shows `Show all` button below the ac list
![image](https://user-images.githubusercontent.com/17010094/73110253-b130ac00-3ed3-11ea-812c-546e3289a414.png)

------
Verification passed on OnePlus 6T with Android 10 running 1.5.58 x64 build
- Verified excluding a side, shows `Show all` button below the ac list
![image](https://user-images.githubusercontent.com/17010094/73110255-b55cc980-3ed3-11ea-916c-b5adef1120cf.png)
