### ISSUE TITLE
Follow up to #5158 - Bookmark from `Other Bookmarks` moved to `Bookmark bar` after sync

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#7115]
Follow up to #5158. On initial sync `Other Bookmarks` folder is moved to `Bookmark Bar` which is expected. After sync, when a bookmark is added to `Other Bookmarks` on old brave (1.0.1), it is the moved to `Bookmark Bar` rather than to `Bookmark Bar\Other Bookmarks`

## Steps to Reproduce

   1. Create a sync between old Brave (1.0.x) and new Brave (1.2.x)
   2. Wait for the sync
   3. Add a bookmark to `Other Bookmarks` on old Brave
   4. Wait for sync

## Actual result:

The bookmark is moved to `Bookmark Bar` on New Brave
![image](https://user-images.githubusercontent.com/34715963/69684501-255bf880-10b9-11ea-8494-6e3e68785e6e.png)

The bookmark remains in `Other Bookmarks` on Old Brave
![image](https://user-images.githubusercontent.com/34715963/69684468-0d847480-10b9-11ea-8249-80ba67218d4e.png)

## Expected result:
The bookmark is moved to `Bookmark Bar\Other Bookmarks` as it happens on initial sync
New Brave
![image](https://user-images.githubusercontent.com/34715963/69684535-41f83080-10b9-11ea-8023-06c816412d2e.png)

Old Brave
![image](https://user-images.githubusercontent.com/34715963/69684555-5805f100-10b9-11ea-8871-25a6364d5cd9.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Old Brave

Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Windows 7 Service Pack 1 (Build 7601.24530)

New Brave

Brave | 1.2.11 Chromium: 78.0.3904.108 (Official Build) dev (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @darkdh @rebron @AlexeyBarabash @jsecretan

**Comment by darkdh** [comment]
That is expected, we only migrate what exist in current local “Other bookmarks”,  it will be migrated when old Brave upgrade to new version.
Create a “Other bookmarks” folder for those bookmarks before upgrade will introduce inconsistency between mapping which will result old Brave have a permanent  “Other bookmarks” and “Other bookmarks” folder coexist.

**Comment by bsclifton** [comment]
@darkdh if this is expected, can we close this?

**Comment by bsclifton** [comment]
Closing!
