### ISSUE TITLE
Migrate mojo types for TorLauncher service

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#7116]
This is part of the migration https://github.com/brave/brave-browser/issues/7056, create this to track the Tor part more easily.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.4.82 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.14.6 (Build 18G103)

* Verified test plan from https://github.com/brave/brave-core/pull/4083
* Also verified:
   - able to do a hard refresh (cmd+shift+R) and get a new Tor connection/IP
   - able to click on the hamburger menu, select 'New Tor Connection For This Site' and get a new Tor connection/IP
