### ISSUE TITLE
Optionally align tabs to center of tab bar

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#7119]
## Description 
On some displays, tabs may be uncomfortably far from other window buttons in the chrome. This request asks for an optional flag to center-align tabs (see image below). This feedback was originally received on Twitter from [@1LimeAtATime](https://twitter.com/1LimeAtAtime/status/1199534722424033280).

## Other Additional Information:

![image](https://user-images.githubusercontent.com/815158/69695323-955e8480-10a1-11ea-8a19-01114c3f118d.png)

**Comment by rebron** [comment]
Closing wontfix. We shared with the team and this isn't a design direction we're going to go with for tab UI/UE.
