### ISSUE TITLE
Verify check is shown on top of notification counter

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#7121]
## Steps to Reproduce

   1.  start browser on staging
   2. enable rewards
   3. don't claim promotion, but make sure that you see it
   4. visit verified publisher

## Actual result:

Verified checkmark is shown.

## Expected result:
Notification counter should be still shown until you clear it. This way user can't miss important notifications while browsing verified site.

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.4.66 Chromium: 79.0.3945.130 (Official Build) dev (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

* Verified test plan from https://github.com/brave/brave-core/pull/4160
* Verified STR from description
<img width="1019" alt="Screen Shot 2020-01-22 at 4 35 57 PM" src="https://user-images.githubusercontent.com/28145373/72936597-83adfc00-3d35-11ea-9945-e84413dc19af.png">
<img width="417" alt="Screen Shot 2020-01-22 at 4 36 09 PM" src="https://user-images.githubusercontent.com/28145373/72936602-86a8ec80-3d35-11ea-9891-af9b6ffc24e3.png">
<img width="417" alt="Screen Shot 2020-01-22 at 4 36 53 PM" src="https://user-images.githubusercontent.com/28145373/72936607-890b4680-3d35-11ea-9795-e3f206e1798e.png">
