### ISSUE TITLE
Baookmarks import from Safari on macOS doesn't work

### ISSUE THREAD

**Issue by ZaJarv** [brave/brave-browser#7123]
Hei!👋
As title says, bookmarks import from Safari on macOS doesn't work. What is interesting, for me it doesn't work for different macOS and Brave versions, i started to notice this issue few month ago. Back then i used macOS Mojave. Now i am using macOS Catalina with latest Brave Browser version with same issue. It says that everything is ok, bookmarks is imported, but it doesn't. It only works if i export bookmarks from Safari to html and then load it via import option in Brave, only in this case it works as expected.

macOS Catalina 10.15.1
Safari 13.0.3
Brave 1.0.1

Cheers✌️

**Comment by bsclifton** [comment]
Thanks for the report, @ZaJarv  😄This is a known issue being tracked with https://github.com/brave/brave-browser/issues/2710

We should be able to look into it soon. I'm going to close this issue as a duplicate
