### ISSUE TITLE
DATE column isn't necessary in Monthly Contributions panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7134]
## Description 

DATE column isn't necessary in Monthly Contributions panel. Under date column, the recurring text is displayed there is no date display in the column, would be better to remove DATE column

## Steps to Reproduce

   1. Clean profile 1.1.7
   2. Enable rewards 
   3. Send a monthly tip to a pubs
  
## Actual result:

DATE column isn't necessary in Monthly Contributions panel
![image](https://user-images.githubusercontent.com/38657976/69747323-2c900e80-116c-11ea-937a-f085fed5d0bf.png)

## Expected result:
Under date column, the recurring text is displayed there is no date display in the column, would be better to remove DATE column

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.1.7 Chromium: 78.0.3904.108 (Official Build) beta (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron @karenkliu @bradleyrichter

**Comment by Miyayes** [comment]
Blocking this for now as we rethink Monthly Tip feature.

**Comment by Miyayes** [comment]
Doing individualized monthly tips. https://github.com/brave/brave-browser/issues/28173
