### ISSUE TITLE
Update stats text colour to match desktop

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7135]
## Description 

Update stats text colour to match desktop

## Steps to Reproduce

   1. Clean profile 2.0.0
   2. Open a new tab
   3. HTTPS Upgrade and Est. Time saved stats color is not the same as desktop stats

## Actual result:

HTTPS Upgrade and Est. Time saved stats color is not the same as desktop stats
![image](https://user-images.githubusercontent.com/38657976/69748385-34e94900-116e-11ea-9c7f-1d6912361449.png)

## Expected result:
Update stats text colour to match desktop
![image](https://user-images.githubusercontent.com/38657976/69748398-3fa3de00-116e-11ea-8c7f-444b03e5631f.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave 2.0.0 Chromium 78.1.3.15

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @emerick @yrliou @SergeyZhukovsky

**Comment by srirambv** [comment]
This is fixed on current nightly build 
![image](https://user-images.githubusercontent.com/17010094/73005930-ca543280-3dd7-11ea-9a65-e89b61b624af.png)
![image](https://user-images.githubusercontent.com/17010094/73005941-ce805000-3dd7-11ea-985a-e91f9d06b783.png)
