### ISSUE TITLE
Chromium links are shown on toptiles on clean launch

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7136]
## Description 

Chromium links are shown on top tiles on clean launch

## Steps to Reproduce

   1. Clean profile 2.0.0
   2. Skip onboarding flow
   3. Chromium links are shown on top tiles

## Actual result:

Chromium links are shown on top tiles on clean launch

![image](https://user-images.githubusercontent.com/38657976/69749077-b5f51000-116f-11ea-881b-4aefef196497.png)

## Expected result:
Chromium links shouldn't be shown on top tiles on clean launch

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave 2.0.0 Chromium 78.1.3.15

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @emerick @yrliou @SergeyZhukovsky

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.57 x64 nightly build
- Verified no Chromium top tiles are shown on clean install 
-----
Verification passed on Samsung Tab A with Android 9 running 1.5.57 x64 nightly build
- Verified no Chromium top tiles are shown on clean install 
-----
