### ISSUE TITLE
No space between `Total tips this month` and BAT USD value in small screen devices

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7138]
## Description 

No space between `Total tips this month` and BAT USD value in small screen devices
## Steps to Reproduce

   1. Clean profile 2.0.0
   2. Enable rewards
   3. Navigate to tips panel
   4. No space between `Total tips this month` and BAT USD value in small screen devices

## Actual result:

No space between `Total tips this month` and BAT USD value in small screen devices
![image](https://user-images.githubusercontent.com/38657976/69749707-1f295300-1171-11ea-82e3-0a9338b8b5c8.png)

## Expected result:
There should be some space between `Total tips this month` and BAT USD value in small screen devices
## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave 2.0.0 Chromium 78.1.3.15
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @emerick @yrliou @SergeyZhukovsky

**Comment by Miyayes** [comment]
Should be resolved with new responsive Rewards settings page. If not, refile anew.
