### ISSUE TITLE
Ads are served even when Ads are not yet supported

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7139]
## Description 

Ads are served even when Ads are not yet supported

## Steps to Reproduce

   1. Clean profile 2.0.0
   2. Enable rewards
   3. Verify sample ad is shown after enabling rewards
   4. Verify that, Ads panel isn't shown and Sorry! Ads not available message is shown in panel
   5. Ads are served even though ads are not yet supported

Note: ipleak.net shows IP as India. Language set in the device is English (US)
## Actual result:

Ads are served even when Ads are not yet available

![image](https://user-images.githubusercontent.com/38657976/69751724-b690a500-1175-11ea-89a6-42ea3d14c928.png)

![image](https://user-images.githubusercontent.com/38657976/69751725-b690a500-1175-11ea-8c12-6285b26fdf7b.png)

## Expected result:
Ads should not be served when Ads are not yet supported

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave 2.0.0 Chromium 78.1.3.15

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @emerick @yrliou @SergeyZhukovsky

**Comment by yrliou** [comment]
I think the root cause of this is the same as https://github.com/brave/brave-browser/issues/7572.
In this case, I think ads backend will return it is supported based on locale, but frontend (the rewards page) currently has a bug that did not report the most up-to-date info for ads data so it is shown as unsupported.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.58 x64 build 
- Verified Ads is enabled for supported region when enabled via rewards panel 
- Verified Ads is enabled for supported region when enabled via rewards page 
- Verified Ads is enabled for supported region when enabled via onboarding
------- 
Verification passed on Samsung Tab A with Android 9 running 1.5.58 x64 build 
- Verified Ads is enabled for supported region when enabled via rewards panel 
- Verified Ads is enabled for supported region when enabled via rewards page 
- Verified Ads is enabled for supported region when enabled via onboarding
-------
