### ISSUE TITLE
Persistent command window shown when launching from console

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#714]
## Description 

Persistent command window shown when launching from console

## Steps to Reproduce

   1. Build from master and launch by running `npm run start Release` in  a `git bash` window
   2. Empty command prompt window pops up which is persistent 
   3. Close the command prompt, opens another one 
   4. Sometimes closing the command prompt causes a tab to have webview crash

## Actual result:

![annoying command prompt](https://user-images.githubusercontent.com/17010094/43914251-5bb599e0-9bd5-11e8-860e-0c7ef6aa7774.gif)

## Expected result:
Should not retain the command prompt. after browser is launched

## Reproduces how often: 

100% on Windows

## Brave version (about:brave info) 

master

### Reproducible on current release:

N/A

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @emerick @bbondy

**Comment by darkdh** [comment]
The root cause is 
Audio Service get launched as unsandboxed out of process service.
see `services/service_manager/sandbox/win/sandbox_win.cc`
It is supposed to be in process on all platforms for Chrome and Chromium
```
// Runs the audio service in a separate process.
const base::Feature kAudioServiceOutOfProcess{
    "AudioServiceOutOfProcess", base::FEATURE_DISABLED_BY_DEFAULT};

// Enables audio service sandbox.
// (Only causes an effect when feature kAudioServiceOutOfProcess is enabled.)
const base::Feature kAudioServiceSandbox{"AudioServiceSandbox",
                                         base::FEATURE_DISABLED_BY_DEFAULT};
```
But the feature is enabled only on Windows, I printed out the value in
```
bool AudioServiceOutOfProcess() {
  // Returns true iff kAudioServiceOutOfProcess feature is enabled and if the
  // embedder does not provide its own in-process AudioManager.
  return base::FeatureList::IsEnabled(features::kAudioServiceOutOfProcess) &&
         !GetContentClient()->browser()->OverridesAudioManager();
}
```
And I can't find the where the feature get enabled in the code. Although we can manually disable it in `BraveMainDelegate::BasicStartupComplete`, @bbondy suggested we should find out how it get changed.

**Comment by darkdh** [comment]
it is because 
```
    "AudioService": [
        {
            "platforms": [
                "windows"
            ],
            "experiments": [
                {
                    "name": "AudioProcess_LaunchOnStartup_v6",
                    "params": {
                        "teardown_timeout_s": "0"
                    },
                    "enable_features": [
                        "AudioServiceAudioStreams",
                        "AudioServiceLaunchOnStartup",
                        "AudioServiceOutOfProcess"
                    ]
                }
            ]
        },
```  
in testing/variations/fieldtrial_testing_config.json

**Comment by emerick** [comment]
I feel like we should skip field trials in Brave, otherwise we'll end up with hard-to-repo scenarios.

**Comment by darkdh** [comment]
https://github.com/brave/brave-core/pull/531#issuecomment-425981021

**Comment by darkdh** [comment]
```
    "AudioService": [
        {
            "platforms": [
                "linux"
            ],
            "experiments": [
                {
                    "name": "AudioProcess_LaunchOnStartup_v6",
                    "params": {
                        "teardown_timeout_s": "0"
                    },
                    "enable_features": [
                        "AudioServiceAudioStreams",
                        "AudioServiceLaunchOnStartup",
                        "AudioServiceOutOfProcess"
                    ]
                }
            ]
        },
        {
            "platforms": [
                "mac",
                "windows"
            ],
            "experiments": [
                {
                    "name": "AudioProcess_LaunchOnStartup_Sandboxed_APM_v8",
                    "params": {
                        "teardown_timeout_s": "0"
                    },
                    "enable_features": [
                        "AudioServiceAudioStreams",
                        "AudioServiceLaunchOnStartup",
                        "AudioServiceOutOfProcess",
                        "AudioServiceSandbox",
                        "WebRtcApmInAudioService"
                    ]
                }
            ]
        },
...
]
```
now it is all platforms

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows 7

Used Test Plan from https://github.com/brave/brave-core/pull/945

`Utility: Audio Service` was not found in `Task Manager`

![image](https://user-images.githubusercontent.com/34715963/50614532-65365200-0ee1-11e9-90f0-a96a5ddcaef2.png)
