### ISSUE TITLE
Cannot approve DAI loan using connected Crypto wallet in Brave

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#7141]
## Description 

There appears to be an overflow/scroll issue on the Crypto wallets page when attempting approve DAI transactions. The user that brought this to my attention provided the following image of the bug:
![image](https://user-images.githubusercontent.com/3299098/69762502-3a6b7280-111f-11ea-9eae-f1eb8fade6e6.png)

The area the user needs to access seems to be off-screen with no way to scroll to it. 

## Steps to Reproduce

[User provided steps]

> Repro:
> 1. Open a Vault in Maker Oasis. Take a DAI loan.
> 2. 
> 3. Go to uniswap and try to swap the DAI. It has to be unlocked first.

## Actual result:

No scroll bar appears to access the needed area of the screen.

## Expected result:
To be able to scroll to required area on the page when necessary. 

## Reproduces how often: 

N/A

## Brave version (brave://version info)

Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
Windows 10 

## Miscellaneous Information:

Initial user report:
https://www.reddit.com/r/brave_browser/comments/e2l0f3/how_do_i_approve_this_transaction_theres_no_scroll/

**Comment by ivan-prodanov** [comment]
Let me know if you’ve got any questions. I’m the user who reported this on reddit.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.7.16 Chromium: 80.0.3987.122 (Official Build) nightly (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Linux
Component | `0.1.47`

- Verified able to scroll the popup connection windows
