### ISSUE TITLE
DB general improvements

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#7145]
This issue is related to all filed in **database folder**

1. Check variables `table_name_`  to  and `kTableName`

2.  `const char* table_name_ = "media_publisher_info";` -> `const char table_name[] = "media_publisher_info";`

3. make sure that all pointers that come in are checked with DCHECK and if

**Comment by masparrow** [comment]
@NejcZdovc blocked until DB migration https://github.com/brave/brave-core/pull/4252 is finished
