### ISSUE TITLE
Add is-abp license

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#7148]
I have heard back from the author of the is-abp list by email and the list will be licensed under the usual [EasyList license](https://easylist.to/pages/licence.html).

We can update our licensing information.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.1 x64` using the following build:

Brave | 1.1.19 Chromium: 79.0.3945.70 (Official Build) (64-bit)
-- | --
Revision | 65868db27916cebde51fc2465c9b34761e6383e2-refs/branch-heads/3945@{#869}
OS | macOS Version 10.15.1 (Build 19B88)

* went through the STR mentioned via https://github.com/brave/brave-core/pull/4103 
* ensured that all references of `EasyList` have been removed from `brave://credits`
* ensured that `Disconnect` has been removed from `brave://credits`
* ensured `HTTPS Everywhere` was removed and `Brave HTTPS Everywhere` was added instead
* ensured that `Brave Sync` is still being listed under `brave://credits`
* ensured that the following items have been added into `brave://credits` as per https://github.com/brave/brave-core/pull/4103 
   * Brave Ad Block
      * ensured https://github.com/brave/brave-core-crx-packager was opened
   * Brave Ethereum Remote Client Extension
      * ensured https://github.com/brave/ethereum-remote-client was opened
   * Brave HTTPS Everywhere
      * ensured https://github.com/brave/https-everywhere-builder was opened
   * Brave Local Data
      * ensured https://github.com/brave/brave-core-crx-packager was opened
   * Brave Tor Client
      * ensured https://github.com/brave/tor_build_scripts was opened
