### ISSUE TITLE
Handle AMP links correctly for Rewards

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#7149]
Ref iOS ticket: https://github.com/brave/brave-ios/issues/1824

## Description 
Visiting an AMP link in iOS (and likely Android) doesn't extract the publisher

## Actual result:
`google.com` becomes the publisher that is visible in the panel and gets A/C activity and tipping

## Expected result:
The underlying publisher should get show on the panel for A/C and tipping

**Comment by rebron** [comment]
cc: @srirambv
