### ISSUE TITLE
Hiding the setting of collecting URLs of your visited pages

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#715]
<img width="695" alt="screen shot 2018-08-09 at 10 30 36" src="https://user-images.githubusercontent.com/11330831/43915610-1750415c-9bc0-11e8-9af3-e1ad1591a370.png">
We should hide this in `chrome://settings/privacy` and make sure it is truly disabled

**Comment by yrliou** [comment]
- turn off url_keyed_anonymized_data_collection.enabled pref
- looks like patching would be needed for hiding this element in personalization_options.html
ref: https://cs.chromium.org/chromium/src/chrome/browser/resources/settings/privacy_page/personalization_options.html?type=cs&q=urlKeyedAnonymizedDataCollection&sq=package:chromium&g=0&l=81

**Comment by bbondy** [comment]
Option seems to be gone, so marking this as invalid for now.
