### ISSUE TITLE
Move currentTime in bat_helper to time_util

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#7152]
Right now we have `currentTime` function in `bat_helper`. We should move it into `time_util` file. We should also change implementation.

Current:
```
uint64_t currentTime() {
  return time(0);
}
```

New one:
```
uint64_t GetCurrentTimeStamp() {
  return static_cast<uint64_t>(base::Time::Now().ToDoubleT());
}
```

Also find all references to this snippet of the code and replace it with this new function.

**Comment by kushthedude** [comment]
@NejcZdovc Can I help in this following issue ?

**Comment by NejcZdovc** [comment]
@kushthedude sure. Let me know if I can help in any way
