### ISSUE TITLE
Can we have fake DRM implemented?

### ISSUE THREAD

**Issue by Joe23232** [brave/brave-browser#7157]
Can we put a fake DRM system in place to trick certain websites that require DRM into thinking Brave actually has DRM? And we can then control what the website thinks we have?

**Comment by bsclifton** [comment]
@Joe23232 do you have any example websites which are detecting DRM?

I did some quick searching to see how you could try to detect widevine/etc support and found this:
https://stackoverflow.com/questions/35086625/determine-drm-system-supported-by-browser

Presumably we could fake this out / randomize what is found

cc: @diracdeltas

**Comment by Joe23232** [comment]
@Joe23232 

Hi, so Netflix, Amazon Prime etc those websites detect if you have DRM.

Thanks I will check out the link :)

**Comment by diracdeltas** [comment]
what would be the benefit of faking DRM? pretty sure the video on Netflix would not play unless you had the real widevine installed.
