### ISSUE TITLE
Conceal system fonts from web sites

### ISSUE THREAD

**Issue by riastradh-brave** [brave/brave-browser#716]
System fonts are a standard fingerprinting vector.  Web sites that need specific fonts can bundle them with the site; otherwise they will look different, and likely bad, on different computers anyway.  We should always set the system fonts -- as available for use by name in CSS, and anywhere else they might appear -- to some standard baseline set so that users cannot be distinguished by it.

I would like to do this always, but if there is a compelling reason it has to be limited to when fingerprinting protection is enabled, so be it.

**Comment by tomlowenthal** [comment]
Even though this one came first, I'm duping this into #816 because there's more discussion there.
