### ISSUE TITLE
BRLive website doesn't work - ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by hallzy** [brave/brave-browser#7160]
## Description 

When I visit https://live.bleacherreport.com/ I am unable to watch any of the streams or replay videos.

I am also unable to select any of the options under "Popular on B/R Live" such as NLL.

I see a lot of ERR_BLOCKED_BY_CLIENT in the console which I assume is the main problem here.

## Steps to Reproduce

   1.  Visit https://live.bleacherreport.com/
   2. Also try to visit https://live.bleacherreport.com/lacrosse/national-lacrosse-league/50 - The page loads but it is completely empty
   3. Go back to https://live.bleacherreport.com/ and try clicking on any of the live events - You will be taken to an error page.

In all cases  Note all the ERR_BLOCKED_BY_CLIENT errors on this page.

## Actual result:

I am taken to error pages or empty pages when reproducing the issue as above

## Expected result:

I don't expect to be taken to empty pages or error pages (again probably caused by all the blocked by client errors)

When clicking on a live event I should either see the live event or get some information about paying to see it depending on the event.

## Reproduces how often: 

100% of the time

## Brave version (brave://version info)

Brave: 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)
Revision: 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS: Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Haven't Tried
- Can you reproduce this issue with the dev channel?  Haven't Tried
- Can you reproduce this issue with the nightly channel?  Haven't Tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  No

## Miscellaneous Information:

I allowed full permissions for the site as well to see if that would help, and it did not.

Sometimes when visiting the site the page complains that I am not in the USA, even though it is supposed to work elsewhere (like Canada, which is where I am), so that is something that may happen when testing. I am going to assume that this issue isn't an issue with the browser though and is an issue with the website. I have reached out to their support team about this but they just dismissed it.

**Comment by hallzy** [comment]
I apologize. I just tried disabling all of my extensions and the site is working. Turns out, my VPN's extension has it's own ad blocking etc built in that I didn't know about.

**Comment by bsclifton** [comment]
@hallzy thanks for confirming 😄 Would you be willing to share the name of the extension? (in case someone else runs into this problem too)

**Comment by hallzy** [comment]
@bsclifton Sure, it was the Windscribe VPN extension.

The full name of the extension is 'Windscribe - Free Proxy and Ad Blocker' (the 'Ad Blocker' part should have been the giveaway).
