### ISSUE TITLE
[Improvement] Reduce Memory Usage

### ISSUE THREAD

**Issue by MrTeeXD** [brave/brave-browser#7162]
## Description 

So, since Brave Version 1.0 came out and I am bvery stoked for the following releases, I was wondering if the Memory usage can be lowered and I know its just Chromium but the Memory usage can be greatly reduced.

## Actual result:

![Taskmgr_Bt08DwHR6f](https://user-images.githubusercontent.com/37266538/69920912-38464280-1496-11ea-85bf-cfa9e4daa778.png)

## Expected result:
The memory usage should be lowered to a stable amount sinvce a PC can be struggling to keep up to speed and Stability

## Reproduces how often: 

Everytime when Brave is opened for a new session

## Brave version (brave://version info)

Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Windows 10 OS Version 1909 (Build 18363.476)

## Version/Channel Information:

- Can you reproduce this issue with the current release? : Yes
- Can you reproduce this issue with the beta channel? : Yes
- Can you reproduce this issue with the dev channel? : Yes
- Can you reproduce this issue with the nightly channel? : Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? : No
- Does the issue resolve itself when disabling Brave Rewards? : No
- Is the issue reproducible on the latest version of Chrome? : Yes, always

## Miscellaneous Information:

N/A

**Comment by bsclifton** [comment]
There are a decent number of specific issues tracking memory:
- Brave extension should be lazy and less memory intensive #6479
- 32-bit Brave eats most of the memory in Windows 7 #3996
- Rewards extension background pages should not be running when Rewards is disabled #5429
- Extensions other users don’t unload on exit #4118

**Comment by MrTeeXD** [comment]
Adding to this, Brave somewhat for some reason, uses your Disk when it is not downloading anything

**Comment by soundarrr** [comment]
+1 from #10702

**Comment by johnkennyuk** [comment]
Did anything ever come out from this issue I.E. a solution / fix??  My Brave has always been a serious memory hog but lately im at the point i need to find a solution to reduce its memory footprint???
