### ISSUE TITLE
PDFs Always Open Internally Only

### ISSUE THREAD

**Issue by GuardianMajor** [brave/brave-browser#7164]
## Description 

When you click on a PDF document link, it should prompt you to save it externally or open it with an outside tool, but it will always and without fail open internally and there is no way to stop it despite the setting being set but it is not honoring it.

![image](https://user-images.githubusercontent.com/5274181/69921462-9e0ade00-1446-11ea-89d3-a85df04731b9.png)

## Steps to Reproduce

   1. Turn off PDF opening as above
   2. Click on any PDF link you find, matters not what
   3. It will open internally - always

## Actual result:

PDF is opened inside Brave and not externally as configured.

## Expected result:
It should open externally with say Acrobat or prompt to save, either way.

## Reproduces how often: 

All the time, every time and without fail.

## Brave version (brave://version info)

![image](https://user-images.githubusercontent.com/5274181/69921498-f8a43a00-1446-11ea-9e78-f0be16747996.png)

## Version/Channel Information:

I have honestly not tried because I don't want to run a bunch of different versions when the release should just work.

- Can you reproduce this issue with the current release? **YES**
- Can you reproduce this issue with the beta channel? **DON'T KNOW**
- Can you reproduce this issue with the dev channel? **DON'T KNOW**
- Can you reproduce this issue with the nightly channel? **DON'T KNOW**

given this option has been in Chrome for a very very long time, I suppose if it is breaking on release, it is broken in the rest too but that's just an educated guess.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **No way to disable, see https://github.com/brave/brave-browser/issues/7163 but as I have it now, nope**
- Does the issue resolve itself when disabling Brave Rewards? **Apparently not since it is already disabled**
- Is the issue reproducible on the latest version of Chrome? **Don't know honestly and I have no interest in installing Chrome to find out, this was supposed to be the better alternative but if it is copying Chrome, then probably**

## Miscellaneous Information:

Don't know what else to provide that would help you but if you need something, let me know and I will be happy to provide it.

Thank you in advance.

**Comment by rebron** [comment]
@GuardianMajor Can you toggle that setting the other way and try again? The screenshot you're showing  has it set so that pdf files are always viewed internally in the browser. Toggling the other way should download the .pdf file. 

If that's not the case, if possible can you link to the .pdf file that you're trying to download.

**Comment by Clubspeed-Mike** [comment]
@rebron So this would be the desired setting to download it?

![image](https://user-images.githubusercontent.com/55165479/71535943-361dab00-28bf-11ea-9364-3a15eb165cc3.png)

It appears to be the cause and so it was my misunderstanding. Normally the text on the options is what is being done, when you toggle you get a different behavior listed but in this case that seems not the case, thank you.

**Comment by rebron** [comment]
@Clubspeed-Mike Yes. That's the right setting to download the pdf files which you would have to toggle on. We default to showing pdfs in browser.

We can look into making this clearer.

**Comment by GuardianMajor** [comment]
Seems like I fell for a common misunderstanding, I believe making it clearer would be nice, but point taken and understood, thank you.
