### ISSUE TITLE
Satellite view in maps.google.com does not operate when shields are up

### ISSUE THREAD

**Issue by aekeus** [brave/brave-browser#717]
## Description 
Satellite view in maps.google.com does not operate when shields are up

## Steps to Reproduce

   1. Navigate to maps.google.com
   2. Switch to satellite view

## Actual result:
Black screen

## Expected result:
Satellite view

## Reproduces how often: 
Always

## Brave version (about:brave info) 
0.53.2

### Reproducible on current release:
No

### Website problems only:  
Resolves when lowering shields

**Comment by srirambv** [comment]
Works with `Allow Ads and tracking`

**Comment by srirambv** [comment]
same issue on http://radio.garden/ as well

**Comment by srirambv** [comment]
Fixed on 0.55.6 for both https://maps.google.com and http://radio.garden/

**Comment by LaurenWags** [comment]
Verified passed with 

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

- checked https://maps.google.com loads when satellite view is selected
- checked http://radio.garden loads without issue
