### ISSUE TITLE
Reward claiming captcha is a huge accessibility barrier

### ISSUE THREAD

**Issue by pitermach** [brave/brave-browser#7174]
## Description 

The current Captcha implementation used while claiming brave ad rewards requiring an image to be dragged onto a target is impossible to solve by users with disabilities, IE using screen readers.

I'm blind, so I use my computer exclusively with the keyboard and a screen reader for speech output.
Using Brave 1.0.1 on Windows 10 X64 with the free [NVDA](https://nvaccess.org/) Screen reader.

I got a notification that ad rewards for this month were ready to claim and wanted to do it, only to be confronted with a screen asking me to drag a bat icon onto the target. There's no way someone with no vision can get through this screen on their own, though this also extends to other disabilities. People with limited dexterity who use a keyboard or a single switch, or those using speech recognition software like Dragon or Voice Control that was recently added to Mac OS Catalina would run into the same problem and also be locked out. This is really unfortunate, as the BAT rewards program was one of the reasons whhy I chose to use Brave and keep the ads turned on.

AS far as solutions I could suggest, this captcha needs to be replaced. I'm guessing Recaptcha is out of the question due to privacy implications. A more traditional image Captcha with an audio alternative would be better, though people with hearing impairments would still find it challenging and outright impossible if they're deaf blind. The best way I can think of that some sites use is answering a text question like a simple math problem. That way it can be read by Screen readers and also displayed on a Braille Display, and shouldn't pose as many problems with localising into other languages

**Comment by marrie** [comment]
I have to agree. I myself am visually impaired, I'm not going to use [aira](aira.io) every time I want to claim tokens. I would also be in favor of the math question. I did this on some websites I ran over the years.

**Comment by Miyayes** [comment]
Rewards claims no longer relevant since we are deprecating vBAT.
