### ISSUE TITLE
Add Dapp detection

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#718]
We should give a notification prompt to ask the user to install MetaMask if they visit a Dapp like cryptokitties.

See:
https://github.com/brave/browser-laptop/blob/master/app/browser/reducers/dappReducer.js

**Comment by lukemulks** [comment]
Would it be possible for us to preload MetaMask, as we do with b-l? 

We provided a security and blockchain advantage in the market when we shipped with MM pre-installed (and inactive). 

Recalling when the extension store recently removed the legit MM along with some duplicates - Brave had the advantage and benefit of being able to confirm to our user base (and the public) that our pre-loaded MM extension was authentic and up to date. 

Also allows for Brave to state that we ship a web3-ready browser. 

There may be some reason I'm unaware of why it's better not to do this, but mentioning as I found myself looking for MM in the dev channel.

**Comment by bbondy** [comment]
We never pre-installed metamask, but we just made it really easy to install via the Dapp detection and by having an option directly in settings to download and install it in 1 step.

**Comment by bsclifton** [comment]
When looking at this, please see this issue regarding the integration done with the Muon version of Brave:
https://github.com/brave/browser-laptop/issues/15221

**Comment by simonhong** [comment]
* Add Dapp detection preference (If it is enabled, installs extension for dapp detection)
* Implement extension for detecting whether webpage tries to access window.web3
* Implement extension API such as `braveDapp.dapp_available` for notifying to browser from detecting extension when extension detects current page is Dapp
* Implement permission request for installing a extension (our fork of MetaMask)

**Comment by tomlowenthal** [comment]
@simonhong we're currently developing a separate cryptocurrency wallet based on MetaMask. The Ðapp-detection should be integrated with that rather than prompting for a separate MetaMask install.

**Comment by simonhong** [comment]
@tomlowenthal Yup, modified (I know that but forgot to mention about it) :)

**Comment by bsclifton** [comment]
@bbondy could you put together a quick test plan? 😄

**Comment by bbondy** [comment]
added test plan

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.6 x64` using the following build:

Brave | 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | macOS Version 10.14.6 (Build 18G95)

* Verified STR/Cases outlined under https://github.com/brave/brave-browser/issues/718#issue-349235343
* Verified STR/Cases outlined under https://github.com/brave/brave-browser/issues/6238#issuecomment-537759135

**Comment by tmcw** [comment]
Because my previous bug got folded into this one, let me summarize:

Detecting 'Installing a Crypto Wallet' by using a getter on window.web3 is inaccurate and misleading to users. For sites like ours, we want to keep track of globals, and something as simple as

```js
Object.getOwnPropertyNames(window).forEach(key => window[key])
```

Triggers this message, which recurs even if a user clicks 'Deny'. It's a product that has nothing to do with crypto and this message is incorrect at least and a problem for user trust.

You could:

- Make the property non-enumerable
- Drop this check

Or something else. For now we'll have to hardcode a workaround into our app to make it avoid web3.

**Comment by srirambv** [comment]
@tmcw your previous issue was on muon (legacy browser) Would you mind adding a new issue and we can have that triaged.
