### ISSUE TITLE
Decouple Brave Ads browser tests from Rewards

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#7183]
Right now ads browser tests are in `rewards_service_browsertest`. This should be moved into ads folder.

**Comment by tmancey** [comment]
@NejcZdovc Is there a separate ticket to decouple common functionality to use across both rewards_service_browsertest and ads_service_browsertest?

**Comment by NejcZdovc** [comment]
@tmancey no

**Comment by tmancey** [comment]
> @tmancey no

https://github.com/brave/brave-browser/issues/7186
