### ISSUE TITLE
Brave Rewards notification not reflecting processed 'Auto Contribute' amount correctly

### ISSUE THREAD

**Issue by AndriusA** [brave/brave-browser#7185]
## Description 

Notification in the rewards dialog does not correctly reflect the contribution just made. Rewards was set to auto-contribute 50.0 BAT and Uphold sent a notification that 50 BAT was sent.

## Steps to Reproduce

   1. Previous period auto-contirbution amount was set to 50.0 BAT
   2. The wallet is connected to Uphold
   3. Uphold email notification sent on the same date includes correct amount

## Actual result:

![image (3)](https://user-images.githubusercontent.com/145422/70044791-e77c3a00-15ba-11ea-8380-4aa009b9f98a.png)

## Expected result:

The notification should show the 50.0 BAT contributed

## Reproduces how often: 

No steps to reproduce

## Brave version (brave://version info)

Brave | 1.3.44 Chromium: 78.0.3904.108 (Official Build) nightly (64-bit)
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | macOS Version 10.14.6 (Build 18G1012)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows 10 x64 - 1.3.50 nightly build

![image](https://user-images.githubusercontent.com/38657976/70045654-79e80200-15ea-11ea-9c74-155dc984a681.png)

**Comment by masparrow** [comment]
@GeetaSarvadnya @AndriusA Hi both - I just want to check the following if that's ok; 

a) Do you have the Rewards panel already open when the contribution notification occurs
b) Are you are launching Brave and then opening the Rewards panel _after_ the contribution notification 
c) if a) or b) - if you quit Brave and relaunch, does Rewards show the correct contribution amount?

TIA!

**Comment by AndriusA** [comment]
Sure, though probably not very helpful:

a) no - clicked on the BAT icon because I saw an indicator showing unread notifications, dismissed another notification before seeing the one with 0 amount
b) Probably not, I think I last restarted Brave the day before, after an update
c) Not sure how to view previous notifications, this one already dismissed

**Comment by masparrow** [comment]
Thanks @AndriusA that is actually helpful - it's not a stale view of the total amount. Cheers!

**Comment by GeetaSarvadnya** [comment]
@masparrow Please find my comments inline

a) Do you have the Rewards panel already open when the contribution notification occurs - `Nope, after auto contribution, I have opened the rewards panel`
b) Are you are launching Brave and then opening the Rewards panel after the contribution notification - `I am not relaunching the brave after the auto contribution, in the same session I am viewing the panel after the auto contribution`
c) if a) or b) - if you quit Brave and relaunch, does Rewards show the correct contribution amount? - `
Nope balance Auto contribution value remains 0.0 BAT even after the browser relaunch

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress


Brave | 1.3.97 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/4133
- Verified auto contributed amount is displayed correctly in the ac notification in a clean profile (verified in staging env)
![image](https://user-images.githubusercontent.com/38657976/72805063-fe184680-3c77-11ea-88d0-5a6d45f708f9.png)
- Verified auto contributed amount is displayed correctly in the ac notification in a clean profile (verified in staging env)
