### ISSUE TITLE
Tips sent to Reddit verified pubs isn't displayed in Tips panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7188]
## Description 

Tips sent to Reddit verified pubs isn't displayed in Tips panel

## Steps to Reproduce

   1. Clean profile 1.3.50 - launch brave with staging flags
   2. Enable rewards
   3. Send a one-time tips to a verified Reddit pub `https://www.reddit.com/user/alex_the_brave/`
   4. Reddit pub isn't listed in Tips panel

   

## Actual result:

Tips sent to Reddit verified pubs isn't displayed in Tips panel

![image](https://user-images.githubusercontent.com/38657976/70054703-0d76fe00-15fe-11ea-9e05-e700de16440a.png)

## Expected result:
Tips sent to Reddit verified pubs should be displayed in Tips panel

![image](https://user-images.githubusercontent.com/38657976/70054802-39927f00-15fe-11ea-9add-60fc2f527005.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.3.50 Chromium: 79.0.3945.56 (Official Build) nightly (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron

**Comment by NejcZdovc** [comment]
I can't reproduce this one on the latest master.

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc The issue is reproducible in the latest nightly build version 1.4.1.

**Comment by LaurenWags** [comment]
@GeetaSarvadnya can you recheck this one on 1.3.x when all necessary PRs (4399 and 4372) have been uplifted to that version.

**Comment by NejcZdovc** [comment]
closing as stale

**Comment by LaurenWags** [comment]
@GeetaSarvadnya please check this one also, as it was only reproducible for you on Windows and I could not reproduce on macOS
