### ISSUE TITLE
Tipping banner isn't showing verified pubs image

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7189]
## Description 

Tipping banner isn't showing verified pubs image

## Steps to Reproduce

   1. Clean profile 1.3.50 - launch brave with staging flag
   2. Enable rewards
   3. Send a one time tip to a verified Reddit pub `https://www.reddit.com/user/alex_the_brave/`
   4. Tipping banner isn't showing verified pubs image

## Actual result:

Tipping banner isn't showing verified pubs image
![image](https://user-images.githubusercontent.com/38657976/70054344-64300800-15fd-11ea-86fc-f73c79090da5.png)

## Expected result:
Tipping banner should show verified pubs image
![image](https://user-images.githubusercontent.com/38657976/70054214-161b0480-15fd-11ea-8d9c-b35bde4b6d4c.png)

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.3.50 Chromium: 79.0.3945.56 (Official Build) nightly (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes
 
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron

**Comment by LaurenWags** [comment]
Looks like the title on the banner is showing incorrectly as well. It shouldn't say `reddit#channel:11ncas` it should probably say something like `alex_the_brave on Reddit`.

**Comment by NejcZdovc** [comment]
I can't reproduce this one on the latest master.

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc The issue is reproducible in the latest nightly build version 1.4.1.

**Comment by NejcZdovc** [comment]
tried on 1.4.1, still can't reproduce will ping you on slack

**Comment by NejcZdovc** [comment]
I can reproduce on Windows, so it's windows specific

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya still a problem?
