### ISSUE TITLE
Hide minor version numbers in user-agent string with fingerprinting protection enabled

### ISSUE THREAD

**Issue by riastradh-brave** [brave/brave-browser#719]
Either we should pick some full Chromium version number and stick to it, or use our own Brave version number string that specifies at most only the major version number.  For comparison, the Tor Browser specifies `Firefox 52.0` right now, and generally just the major version number of the LTS release of Firefox that it is based on.

**Comment by pes10k** [comment]
closing in favor of https://github.com/brave/brave-browser/issues/9190
