### ISSUE TITLE
Follow up to #6684 - Alignment issue for `Token grants claimed` in BR panel

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#7198]
With #6684 English locale was fixed. But there are still locales that the issue reproduces

## Steps to Reproduce

Test case 1
   1. Launch Brave in `German` locale on staging
   2. Enable rewards
   3. Claim grant

Test case 2
   1. Launch Brave in `German` locale on staging
   2. Enable rewards and claim grants 
   3. Add few verified sites to a-c table
   4. Send one-time tip and monthly tip to a verified pubs
   5. Wait for auto contribution to complete

## Actual result:

`Token grants claimed` is misaligned
![image](https://user-images.githubusercontent.com/34715963/70095730-ca308580-1625-11ea-949f-3d61fb3f14fb.png)

## Expected result:
Like in English locale
![image](https://user-images.githubusercontent.com/34715963/70095556-5ee6b380-1625-11ea-896c-383e82737b9e.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.3.50 Chromium: 79.0.3945.56 (Official Build) nightly (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Ubuntu 18.04 LTS

@NejcZdovc @ryanml @brave/legacy_qa @rebron

**Comment by NejcZdovc** [comment]
I think what we should do is reduce line-height so that it looks nice even in two rows as we can't handle all languages in one line

**Comment by LaurenWags** [comment]
Can also use Portuguese to verify this issue per https://github.com/brave/brave-browser/issues/6684#issuecomment-561392008

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.4.82 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.14.6 (Build 18G103)

* Verified TC1 and 2 from description:
<img width="392" alt="Bildschirmfoto 2020-02-11 um 11 01 51 AM" src="https://user-images.githubusercontent.com/28145373/74254831-03890f80-4cbf-11ea-9a60-c38d2b7175cc.png">
<img width="392" alt="Bildschirmfoto 2020-02-11 um 11 09 03 AM" src="https://user-images.githubusercontent.com/28145373/74254838-04ba3c80-4cbf-11ea-9821-2ea56b9275f3.png">
