### ISSUE TITLE
Harden contribution flow

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#7201]
We got some reports that contribution flow is triggered multiple times where user only triggered it once. 

So we should check multiple places:
- contribution query
- transaction retry
- make sure that at no point we add new current reconcile to the list except if user/ac triggers it

Reports:
- https://github.com/brave/brave-browser/issues/6867
- @bbondy experienced this as well

cc @Brave-Matt if you have any more reports about this one

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as this was merged into `1.2.x` as per https://github.com/brave/brave-core/pull/4285 and added into https://github.com/brave/brave-browser/releases/tag/v1.2.40.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.2.40 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | macOS Version 10.14.6 (Build 18G103)

* Verified test plan from https://github.com/brave/brave-core/pull/4132
* Confirmed AC contributed as expected (wallet balance decreased accordingly, AC was recorded in wallet panel on brave://rewards)
* Confirmed monthly recurring tips were contributed as expected (wallet balance decreased accordingly, tips were recorded in wallet panel on brave://rewards)
* Confirmed one time tips were contributed as expected (wallet balance decreased accordingly, tips were recorded in wallet panel on brave://rewards)
* Confirmed on both staging and prod environments

**Comment by wizonesolutions** [comment]
Is there a way to fix excessive contribution retries one-time, basically to reset the number if it has gotten really high due to the old bug? Besides closing the popup. 9,000x :) Cc @NejcZdovc

**Comment by NejcZdovc** [comment]
@wizonesolutions will fix it in https://github.com/brave/brave-browser/issues/7239 to clear local storage. You will also need to do this step https://github.com/brave/brave-browser/issues/6867#issuecomment-561520119
