### ISSUE TITLE
Keyboard media controls in macOS

### ISSUE THREAD

**Issue by maharjanaman** [brave/brave-browser#7202]
## Description 

Brave is taking all media controls from the keyboard even when other media app is focused.

## Steps to Reproduce

   1. Open Brave browser and play any media
   2. Open any other media app
   3. Try to change(play/pause) while other media app is focused from an external keyboard

## Actual result:

Play/pause on brave browser only.

## Expected result:
Play/pause on other media app when that app is focused.

## Reproduces how often: 

All the time

## Brave version (brave://version info)

Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | macOS Version 10.15.1 (Build 19B88)

**Comment by bsclifton** [comment]
@maharjanaman can you please try visiting chrome://flags/#hardware-media-key-handling and DISABLING this flag? I think that is what was causing the problem

This may have been resolved when upgrading to Chromium 79 which I believe changed the default value

**Comment by maharjanaman** [comment]
Oh okay.
