### ISSUE TITLE
Brave should still pay unverified companies

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#7203]
Have you searched for similar issues? For the first time I couldn't be bothered checking. To be honest didn't know what keywords to enter to find issue.

## Description 
I don't why, it must have been because of the texts presented previously that I got the impression that Brave used a back-end service to communicate sort of like an in-house version of email extractor and basically contacted publishers in an automated way to accept the funds that have been allocated for them by users. Obviously I was wrong. 

There are understandably many site that are not verified and perhaps may not wish to be verified ever, either because of the additional account creation, registrations via content creators, not liking Uphold, not into handling crypto because it's rather much of a hassle and not to mention regulations.

So I would really like it if Brave developed a system (not necessarily automated) in which it allowed `'Not yet verified'` sites to still be paid but in a different manner, even though they haven't created an account and perhaps this will make them succumb to being verified later on. This isn't to say that this should be the basic traditional Brave USP from now on but a better method of actually getting money paid to unverified creators/sites in general as well as getting them on-board as they consistently continue to receive fund via this additional new method.

My method or I should say my advice in the manner in which this should work is re-implement Brave servers to continue to hold contributed BAT on behalf of those unverified publishers that is accessible by the Admin/Financial Controlling team and have them manually transfer the funds. I know this sounds rather a laborious task and process but I honestly think this can be presented and applied properly as well as gain greater recognition. 
I realise this will be a little less seamless as to how Brave wishes to operate with the crypto/fiat side of things but I really think this would be advantageous to those organisations and outlets that rely on donations.

## Actual result:
I think everyone is sort of aware that it's held withing the browser for 90 days which is ridiculous; if companies wish to adopt a crypto payment system, it doesn't make sense for Brave to push for the 90 day policy. I think that's why I assumed Brave used an email extraction service to communicate and pressure publishers to adopt Uphold because you extended the verification period to 90 days. 
If they didn't sort it out within the first 30 days of contribution, you're technically waiting 270 days before you realise they're not going to adopt Brave Payments or still haven't come across it.

## Steps to Create
   1. Re-implement Brave servers to continue to hold contributed BAT on behalf of those unverified publishers. 
   2. Allocate all the funds linked to their designated publishers/content providers for a month.
   3. Manually transfer the funds sent by Brave, Inc via fiat of course to their donations platform on their website. 

## Additional Information:
I think large companies often adopt remedial measures such as automation for efficiency and we forget that employing specific people (though not a highly paid vacancy) can improve a product and a companies' plans and goals in more ways than one.

**Comment by NejcZdovc** [comment]
cc @mandar-brave @alexwykoff
