### ISSUE TITLE
--window-position and --window-size command line switches not supported

### ISSUE THREAD

**Issue by derekantrican** [brave/brave-browser#7206]
## Description 
Chrome has the following command line options: https://peter.sh/experiments/chromium-command-line-switches . The two I am looking at in particular: `--window-position=x,y` and `--window-size=height,width` are not supported by Brave

## Steps to Reproduce
Run the following (using the Windows Run utility):
`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe --window-position=50,50 --window-size=300,300`

`C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe --window-position=50,50 --window-size=300,300`

Note how the first command controls the size and position of the browser window that is launched, but the second does not.

## Expected result:
Brave browser should support these command line parameters

## Reproduces how often: 
Every time

## Brave version (brave://version info)

Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Windows 10 OS Version 1909 (Build 18363.476)
JavaScript | V8 7.8.279.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --profile-directory=Default --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=NewExtensionUpdaterService,PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,UnifiedConsent,SyncUSSBookmarks --flag-switches-begin --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,UnifiedConsent,SyncUSSBookmarks,NativeNotifications --flag-switches-end
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\derek.antrican\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by rebron** [comment]
Need to verify if this is reproducible on Chrome.

**Comment by derekantrican** [comment]
Works as expected on Chrome (at least from my testing). As long as all chrome windows are closed first* then the command `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe --window-position=50,50 --window-size=300,300` works as expected.

**I say "as long as all chrome windows are closed first because there is a known issue where chrome doesn't respect these arguments for the new window if there is already a Chrome window open https://bugs.chromium.org/p/chromium/issues/detail?id=823991&q=window-position&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified#makechanges*

**Comment by bsclifton** [comment]
Looks like this is fixed; I ran command as stated in original (ok, slightly different! `%PROGRAMFILES%\BraveSoftware\Brave-Browser\Application\brave.exe --window-position=50,50 --window-size=300,300`) and it worked as expected

If I already had a window open then it doesn't work, which is captured with https://bugs.chromium.org/p/chromium/issues/detail?id=823991
