### ISSUE TITLE
network-audit is terminated before logs finish writing

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#7207]
## Description 
While investigating [parsing errors for network-audit](https://github.com/brave/brave-browser/issues/6189) and during code review w/ @bridiver ([for a band-aid patch I had](https://github.com/brave/brave-browser/pull/7182)), it became clear that we need to wait until the logs are written out in their entirety to ensure integrity of the network-audit

`SIGTERM` / `SIGKILL` were added with https://github.com/brave/brave-browser/pull/4036 which may have introduced the problem. Because the stream for the logger isn't flushed, there are missing line endings. The first band-aid patch was done for this with https://github.com/brave/brave-browser/pull/2787

## Steps to Reproduce
   1. Run `npm run network-audit` on the platform of your choice
   2. Open `network_log.json` in a text editor

## Actual result:
Notice how this is likely not proper JSON. It's missing the `]` to close `events: [` and then the closing `}` tag for the entire JSON blob (possibly missing more).

## Expected result:
Log should be valid JSON; no "hack" should be needed to parse the file. There might be missing entries- the process needs to complete the log on its own.

**Comment by diracdeltas** [comment]
i think the proper fix is probably to understand why SIGKILL is needed on build machines only and then try to restore it to SIGTERM

**Comment by bsclifton** [comment]
@diracdeltas that's definitely one approach; another which @bridiver proposed would be to create a new test suite, something like `npm run test brave_network_audit` which could wait a predetermined amount of time (or possibly run navigation tests) and then logs would be checked as a final part of the test

**Comment by bridiver** [comment]
yea, I think the best fix for this is to turn it into a browser test that runs with a separate command. I pointed @bsclifton to `LogNetLogTest` which tests the basic functionality so we can use that as a template and add our checks. I think it's also better because we can do navigation, etc... that might trigger other requests

**Comment by tomlowenthal** [comment]
Alternative suggestion: what if we change the network audit test script so that it either runs a dozen times and returns a success if it gets a success at any point, but if it hits a dozen tries without a success it's a fail?

**Comment by bridiver** [comment]
@tomlowenthal the network audit script will never be a great solution because it just starts the browser and does nothing. With an actual browser test we can navigate around and do stuff to make sure other calls aren't made as a result

**Comment by tomlowenthal** [comment]
@bridiver For sure! But until we write that, this is what we have, and it's valuable to make sure that we can run it as close to the initial commit as we can.

**Comment by wknapik** [comment]
Keeps repeating over and over https://bravesoftware.slack.com/archives/CA5FPHWLF/p1626175837322900.

**Comment by rebron** [comment]
cc: @mariospr

**Comment by bridiver** [comment]
I think it's long past time we converted this to a browser test

**Comment by mariospr** [comment]
Started working on this today, based on LogNetLogTest, as suggested by @bridiver
