### ISSUE TITLE
Flags Page Defaults to Serif Font

### ISSUE THREAD

**Issue by kuesa** [brave/brave-browser#7208]
## Description 

The flags page (brave://flags) defaults to a serif font. This is because in Chromium, the Roboto font is provided as a resource, but it is not included in the Brave browser (at least on the flags page). Since the styling for the flags page _only_ specifies Roboto as the font family, and the body style overrides the default text CSS, and since Roboto is not provided, the font defaults to being the default serif font.

## Steps to Reproduce

   1. Open Brave Browser on Desktop
   2. Navigate to brave://flags

## Actual result:

The body fonts are in a serif font family.
![](https://i.imgur.com/jprzAhQ.png)

## Expected result:
The body fonts to be in a sans-serif font family, to be consistent with the rest of the UI:
![](https://i.imgur.com/Tv5zbUH.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Windows 10 OS Version 1903 (Build 18362.476)

## Version/Channel Information:

- Can you reproduce this issue with the current release? You Betcha
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No (since Chrome provides Roboto)

## Miscellaneous Information:

This might be an issue to bring up with the Chromium repo, since it might be bad practice to only specify one font, and not alternatives.

**Comment by kuesa** [comment]
Submitted a PR to fix this issue in the Chromium repo: [#33](https://github.com/chromium/chromium/pull/33)

**Comment by rebron** [comment]
@kuesa Thanks for taking this one on. We'll wait for this fix to come through via upstream.

**Comment by bsclifton** [comment]
Closing as there is no action we can take here. @kuesa I've never submitted a patch through Chromium GitHub repo- I've only seen work accepted when going through https://chromium-review.googlesource.com/

Let me know if you need help getting started contributing upstream; There's a great guide here which goes over creating a CL, etc
https://chromium.googlesource.com/chromium/src/+/master/docs/contributing.md
