### ISSUE TITLE
ad notifications no longer have a View button

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7211]
## Description 
On C79 versions the ad notifications no longer have a `View` button, just one large `Close` button.

For reference, I'm using High Sierra on macOS.

## Steps to Reproduce

   1. Enable Rewards
   2. Browse until an ad is served.
   3. 

## Actual result:
<img width="368" alt="Screen Shot 2019-12-04 at 4 21 00 PM" src="https://user-images.githubusercontent.com/28145373/70183196-4f15b080-16b3-11ea-95c5-5d698179365a.png">

## Expected result:
<img width="357" alt="Screen Shot 2019-12-04 at 4 26 31 PM" src="https://user-images.githubusercontent.com/28145373/70183200-51780a80-16b3-11ea-8ed0-d81254f8f33a.png">

## Reproduces how often: 
easily

## Brave version (brave://version info)
1.1.18

## Version/Channel Information:

- Can you reproduce this issue with the current release? not on 1.0.1
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @bsclifton @mkarolin @rebron @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
@LaurenWags Could be specific to macOS and Linux (not sure about Linux) - from the beginning, there is no View option in ads notification in Windows OS.

**Comment by LaurenWags** [comment]
Adding 1.1.x milestone as this is likely a C79 regression we may want resolved before releasing.

**Comment by lukemulks** [comment]
This actually improves consistency across desktop operating systems. 

Linux (Fedora/Gnome): No view button. 
Win10: No view button.

**Comment by bsclifton** [comment]
Closing as `wontfix` after sharing with team and getting verbal approval from @jsecretan

**Comment by jsecretan** [comment]
Confirming the above

**Comment by btlechowski** [comment]
Not reproducible on Linux. Adding `QA/macOS` label.
