### ISSUE TITLE
when Auto Contribute is disabled there is no way to set a Monthly Tip

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7214]
## Description 
When you toggle AC off, the section in the panel which contains the ability to access the Monthly Contribution banner is removed. 

In previous versions (1.0.x and before), you set your monthly tip from the same banner as one-time tip. However, with #5996 we added the separate Monthly Contribution banner. Before, even if AC was off, you could still select the checkbox on the one time tip banner to set a monthly tip. Now you are unable to do this.

## Steps to Reproduce

   1. Enable Rewards
   2. Visit a site (verified or not)
   3. View panel, see `Monthly Contribution` label and `Set` button.
   4. Toggle AC off.
   5. Visit a site.
   6. View panel.

## Actual result:
No way to set a Monthly tip:
<img width="395" alt="Screen Shot 2019-12-04 at 5 28 16 PM" src="https://user-images.githubusercontent.com/28145373/70187720-e6333600-16bc-11ea-8351-6f756da7fe3f.png">

<img width="1182" alt="Screen Shot 2019-12-04 at 5 38 45 PM" src="https://user-images.githubusercontent.com/28145373/70187741-f3e8bb80-16bc-11ea-8a78-e7502feb8274.png">

## Expected result:
Probably should move the Monthly Contribution/Set button out of the section that gets removed when AC is toggled off.
<img width="399" alt="Screen Shot 2019-12-04 at 5 28 00 PM" src="https://user-images.githubusercontent.com/28145373/70187832-298da480-16bd-11ea-82aa-14e413ad6788.png">

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 1.1.18 Chromium: 79.0.3945.56 (Official Build) (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @alexwykoff @mandar-brave @ryanml

**Comment by LaurenWags** [comment]
note - if you already have a monthly tip for a publisher set before disabling AC, this section does display in the panel:

<img width="409" alt="Screen Shot 2019-12-04 at 6 55 36 PM" src="https://user-images.githubusercontent.com/28145373/70191759-ce14e400-16c7-11ea-8e71-5a6a488ac804.png">


<img width="658" alt="Screen Shot 2019-12-04 at 6 56 23 PM" src="https://user-images.githubusercontent.com/28145373/70191755-c9e8c680-16c7-11ea-9d96-8727e1a0fef5.png">

**Comment by alexwykoff** [comment]
@NejcZdovc consensus from product team is that this is P1

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows 10 x64 - 1.1.8

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified STR from description
* Verified able to update and remove monthly tips from panel when AC is off
* Verified able to remove monthly tips from brave://rewards when AC is off
<img width="408" alt="Screen Shot 2019-12-19 at 5 51 02 PM" src="https://user-images.githubusercontent.com/28145373/71216328-364af480-2288-11ea-91de-2ea67a6f90b5.png">
<img width="410" alt="Screen Shot 2019-12-19 at 5 51 15 PM" src="https://user-images.githubusercontent.com/28145373/71216332-3814b800-2288-11ea-89b9-091d308a09bd.png">
<img width="645" alt="Screen Shot 2019-12-19 at 5 51 23 PM" src="https://user-images.githubusercontent.com/28145373/71216337-39de7b80-2288-11ea-9935-4683a303704d.png">
