### ISSUE TITLE
[Android] Add accessibility labels to toolbars

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#7215]
Android PR: https://github.com/brave/browser-android-tabs/pull/1397

**Comment by yrliou** [comment]
Please check https://github.com/brave/brave-core/pull/4140#issue-349229397 for the test plan.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.57 x64 nightly build
- Verified accessibility labels are shown for all items on toolbar
- Shields
![image](https://user-images.githubusercontent.com/17010094/73100488-a23dff80-3ebb-11ea-8a72-1fdffe52c5c3.png)
- Rewards
![image](https://user-images.githubusercontent.com/17010094/73100457-94887a00-3ebb-11ea-8575-d9aae5a96749.png)
- Home 
![image](https://user-images.githubusercontent.com/17010094/73100533-bbdf4700-3ebb-11ea-85cb-d3f1c4560db1.png)
- Bookmark
![image](https://user-images.githubusercontent.com/17010094/73100504-ac5ffe00-3ebb-11ea-9932-0375b2155325.png)
- Search
![image](https://user-images.githubusercontent.com/17010094/73100475-9baf8800-3ebb-11ea-8b97-6c976b791664.png)
- Open tabs
![image](https://user-images.githubusercontent.com/17010094/73100516-b2ee7580-3ebb-11ea-9e08-e8b8a7c9b4f1.png)
------
Verification passed on Samsung Tab A wiht Android 9.0 running 1.5.57 x64 nightly build
- Verified accessibility labels are shown for some items on toolbar
- Home
![image](https://user-images.githubusercontent.com/17010094/73100769-3d36d980-3ebc-11ea-8e75-e08d89f2ea53.png)
- Refresh
![image](https://user-images.githubusercontent.com/17010094/73100727-23959200-3ebc-11ea-91bb-4a1f006293db.png)
- Bookmark
![image](https://user-images.githubusercontent.com/17010094/73100752-33ad7180-3ebc-11ea-9aec-3217812c9e8f.png)
- Download 
![image](https://user-images.githubusercontent.com/17010094/73100740-2abca000-3ebc-11ea-9100-3e3a7a6e9ce3.png)
- Logged #7906 for missing labels for Rewards/Shields
- Logged #7907 for incorrect label for Home button
