### ISSUE TITLE
Next payment date appearing as 4th instead of 5th for a user in Australia

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#7218]
## Description 

Next payment date appearing as 4th instead of 5th for a user in Australia

![image](https://user-images.githubusercontent.com/1188719/70235669-48427880-175b-11ea-8db4-946f688d8f6f.png)

## Steps to Reproduce

   1. Change timezone on the device to GMT+11:00 (i.e. Lord Howe Daylight Time)
   2. Change time on the device to 01:00

## Actual result:

Next payment date of 4th

## Expected result:
Next payment date of 6th (as we payout on the 5th of each month based upon the UTC timezone)

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by tmancey** [comment]
@alexwykoff @mandar-brave @jsecretan The next payment dates are based on a UTC timestamp, therefore as the above time zone is 11 hours ahead they would get paid out on the 4th. Your thoughts please as I believe this is working as expected?

**Comment by mandar-brave** [comment]
My preference and as spec, should be using local time @tmancey; considering Rewards uses local time, it makes sense to follow that.

**Comment by tmancey** [comment]
@mandar-brave We are using local time, which is working as expected on macOS and iOS. I am going to change the way we format the date and retest on Android (only difference I see with this particular date is we use `FromString` which should be using local time). I will refactor the code to not use `FromString` as we do not use this call elsewhere

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.4.86 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/4176
Australia, India and Central European Standard Time
![image](https://user-images.githubusercontent.com/38657976/74468572-0bb09d00-4ec1-11ea-83c5-faf099251599.png)

Central US and Canada Time Zone:
![image](https://user-images.githubusercontent.com/38657976/74468715-4b778480-4ec1-11ea-854c-b3f4143d5604.png)
