### ISSUE TITLE
users are prompted to Sign into Brave after saving credit card info

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7219]
## Description 
On C79 builds users are being asked to 'Sign into Brave' after saving credit card info. Similar to https://github.com/brave/brave-browser/issues/1363.

On C78 builds this does not occur.

## Steps to Reproduce

   1. Navigate to a site such as https://mqi.ie/donate/
   2. Enter information and submit
   3. Save Credit Card info when prompted from URL bar

## Actual result:
This should not appear after saving credit card info:
<img width="342" alt="Screen Shot 2019-12-05 at 11 13 54 AM" src="https://user-images.githubusercontent.com/28145373/70253220-ca796f80-1750-11ea-81ec-0752321948bf.png">

And when you click on the credit card icon in the URL Bar:
<img width="334" alt="Screen Shot 2019-12-05 at 11 14 28 AM" src="https://user-images.githubusercontent.com/28145373/70253242-d2391400-1750-11ea-84b5-61edf4411d95.png">

![creditcard-test1118](https://user-images.githubusercontent.com/28145373/70253265-dfee9980-1750-11ea-8f96-e2b925d08303.gif)

## Expected result:
No prompt to sign in to Brave after saving CC info.

When you click on credit card icon in URL bar, there shouldn't be a message at the bottom of the popup asking you to sign in:
<img width="348" alt="Screen Shot 2019-12-05 at 11 11 22 AM" src="https://user-images.githubusercontent.com/28145373/70253349-0f050b00-1751-11ea-805a-88d99278e78a.png">

This is how this works on 1.0.1 C78:
![creditcard-test101](https://user-images.githubusercontent.com/28145373/70253366-16c4af80-1751-11ea-81aa-31a582ff98a1.gif)

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 1.1.18 Chromium: 79.0.3945.56 (Official Build) (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, not with 1.0.1
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? yes, reported by @AndriusA 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? yes

## Miscellaneous Information:
Originally reported by @AndriusA on Nightly.

I also checked passwords, saving passwords on 1.1.18 does not prompt you to sign into Brave after saving them.

cc @mkarolin @bsclifton @rebron @brave/legacy_qa

**Comment by LaurenWags** [comment]
Adding 1.1.x milestone as this is likely a C79 regression we want resolved before releasing.

**Comment by bsclifton** [comment]
I believe this is a bug upstream; I filed https://bugs.chromium.org/p/chromium/issues/detail?id=1031307

Looking at an easy fix for us 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.1 x64` using the following build:

Brave | 1.1.19 Chromium: 79.0.3945.70 (Official Build) (64-bit)
-- | --
Revision | 65868db27916cebde51fc2465c9b34761e6383e2-refs/branch-heads/3945@{#869}
OS | macOS Version 10.15.1 (Build 19B88)

* ensured that saving CC info via https://dump-truck.appspot.com/usecase-address_and_cc_on_same_page/address_and_cc.html doesn't display the `Sign in to Brave` text.
* ensured that clicking on `X` dismisses the modal but is still available via the URL
* ensured that clicking on 
* ensured CC info isn't being saved under `brave://settings/payments` when selecting `No Thanks`
* ensured CC info is being saved correctly under `brave://settings/payments` when selecting `Save` and ensuring a `Card Saved` message is being displayed in the URL
* ensured `Manage addresses` correctly opens `chrome://settings/addresses`
* ensured `Manage payment methods` correctly opens `chrome://settings/payments`

Example of notification/modal without `Sign in to Brave` being displayed:

<img width="1051" alt="Screen Shot 2019-12-09 at 2 14 24 AM" src="https://user-images.githubusercontent.com/2602313/70415380-79a49800-1a2a-11ea-833e-cac05980971c.png">
