### ISSUE TITLE
Locale choices are fingerprinting vectors

### ISSUE THREAD

**Issue by riastradh-brave** [brave/brave-browser#722]
Accept-Language, &c.  We should decide what to do about them.

(If we already do something appropriate with fingerprinting protection enabled, we can close this -- I haven't checked.)

**Comment by riastradh-brave** [comment]
https://github.com/brave/browser-laptop/issues/12479

**Comment by bsclifton** [comment]
Closing as we've tackled this recently
cc: @pes10k @pilgrim-brave
