### ISSUE TITLE
brave://version page shows Chromium logo/name on dark theme

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7221]
## Description 
C79 builds show 'Chromium' name and logo on brave://version page, but only on dark theme.

Does not reproduce with C78 builds.

## Steps to Reproduce

   1. Have theme set to light.
   2. Navigate to brave://version
   3. See Brave name/logo/info as expected.
   4. Change theme to dark.
   5. Navigate to brave://version

## Actual result:
See Chromium name/logo
<img width="1196" alt="Screen Shot 2019-12-05 at 12 09 58 PM" src="https://user-images.githubusercontent.com/28145373/70257827-14feea00-1759-11ea-9923-4e000951b22d.png">

## Expected result:
For it to be the same as light theme:
<img width="1195" alt="Screen Shot 2019-12-05 at 12 10 11 PM" src="https://user-images.githubusercontent.com/28145373/70257844-20eaac00-1759-11ea-9231-430f55cfc462.png">

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 1.1.18 Chromium: 79.0.3945.56 (Official Build) (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, not with 1.0.1
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @bsclifton @mkarolin @rebron @brave/legacy_qa 

Does not reproduce for 1.0.1 with C78 (although 1.0.1 does not have the version background page as dark for High Sierra).
Dark:
<img width="1193" alt="Screen Shot 2019-12-05 at 12 12 00 PM" src="https://user-images.githubusercontent.com/28145373/70258247-df0e3580-1759-11ea-9fab-51735062aefe.png">

Light:
<img width="1195" alt="Screen Shot 2019-12-05 at 12 11 48 PM" src="https://user-images.githubusercontent.com/28145373/70258261-e6cdda00-1759-11ea-8633-878879d082a7.png">

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows 10 x64 -1.1.18

![image](https://user-images.githubusercontent.com/38657976/70297071-95cdec80-1812-11ea-88c4-d30bde52f4d0.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.1 x64` using the following build:

Brave | 1.1.19 Chromium: 79.0.3945.70 (Official Build) (64-bit)
-- | --
Revision | 65868db27916cebde51fc2465c9b34761e6383e2-refs/branch-heads/3945@{#869}
OS | macOS Version 10.15.1 (Build 19B88)

Ensured that the correct icon is being displayed under `brave://version` when going through the following:

* switching between `light` & `dark` themes via `chrome://settings/appearance`
* ensuring that `Same as macOS` is selected and using `light` as the OS theme
* ensuring that `Same as macOS` is selected and using `dark` as the OS theme
* ensured that restarting the browser while in dark mode still retains the correct image

#### **`Examples:`**

<img width="1030" alt="Screen Shot 2019-12-08 at 7 11 25 PM" src="https://user-images.githubusercontent.com/2602313/70399098-55779580-19ef-11ea-850f-27610f9d32fa.png">

<img width="1048" alt="Screen Shot 2019-12-08 at 7 12 33 PM" src="https://user-images.githubusercontent.com/2602313/70399097-55779580-19ef-11ea-82c8-2efc65dd4692.png">
