### ISSUE TITLE
Tokens fail to retry due to empty nonce

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#7222]
## Description 

Tokens fail to retry due to empty nonce

## Steps to Reproduce

   1. View an ad

## Actual result:

The console log shows tokens have been exceeded
`Response: {"error":"Number of allowed tokens exceeded","statusCode":429}
`
## Expected result:
The console log should show that tokens were successfully created (where 50 may vary)
`Added 50 unblinded tokens, you now have 50 unblinded tokens
`

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Caused by https://github.com/brave/brave-core/pull/4106

**Comment by btlechowski** [comment]
`QA/Blocked` on https://github.com/brave/brave-browser/issues/7666

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.3.92 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.14.6 (Build 18G103)

* Verified STR from description
```
[27506:775:0115/113336.485560:INFO:refill_tokens.cc(50)] Refill
[27506:775:0115/113336.485573:INFO:refill_tokens.cc(75)] RequestSignedTokens
[27506:775:0115/113336.485584:INFO:refill_tokens.cc(78)] No need to refill tokens as we already have 49 unblinded tokens which is above the minimum threshold of 20
[27507:775:0115/113336.489917:INFO:client.cc(574)] Successfully saved client state
```

**Comment by parasudilip** [comment]
If this thread is still active then i have the same issue

**Comment by parasudilip** [comment]
Also what is the meaning of wallet data is empty

**Comment by tmancey** [comment]
@parasudilip Which version of the browser are you using please? And are you seeing failed to refill tokens? (Please DO NOT paste or share your logs)

**Comment by parasudilip** [comment]
Version 1.14.46 Chromium: 85.0.4183.69 (Official Build) nightly (64-bit). This is from About Brave page. I am sorry for not posting the clear info the first time. The below lines are something which matches something about refill tokens.

Number of allowed tokens exceeded , statusCode : 429

Failed to refill unblinded tokens

Failed to request signed tokens

**Comment by tmancey** [comment]
@parasudilip Do you have multiple browsers using the same wallet, and if so how many please. If you could email me directly with this information that would be great.

**Comment by parasudilip** [comment]
I have mailed to the mail in your profile.. Do check it

**Comment by tmancey** [comment]
@parasudilip Running multiple instances with the same wallet id is not recommended at this time. I would recommend Joining Rewards for each instance until this is supported. Thank you

**Comment by Yanik39** [comment]
Just updated to this version. I had same error with previous version also.
```
Brave | 1.31.88 Chromium: 95.0.4638.69 (Official Build) (64-bit)
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | Linux
JavaScript | V8 9.5.172.25
User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
```

I am getting this error;
```
[30 Oct 2021, 12:21:41.8 am:INFO:refill_unblinded_tokens.cc(178)] OnRequestSignedTokens
[30 Oct 2021, 12:21:41.8 am:VERBOSE6:refill_unblinded_tokens.cc(180)] URL Response:
  URL: https://ads-serve.brave.com/v1/confirmation/token/XXX
  Response Status Code: 429
  Response: {"error":"Number of allowed tokens exceeded","statusCode":429}
[30 Oct 2021, 12:21:41.8 am:INFO:refill_unblinded_tokens.cc(184)] Failed to request signed tokens
[30 Oct 2021, 12:21:41.8 am:INFO:refill_unblinded_tokens.cc(385)] Retry refilling unblinded tokens in 0 hours, 58 minutes, 43 seconds at 01:20
```

And no more ads;
```
[[30 Oct 2021, 12:38:00.7 am:VERBOSE2:permission_rule_util.cc(25)] You do not have enough unblinded tokens
[30 Oct 2021, 12:38:00.8 am:INFO:ad_notification_serving.cc(101)] Ad notification not served: Not allowed due to permission rules
```

Is there a solution? 
Thanks
