### ISSUE TITLE
Feature Request: Appify any url

### ISSUE THREAD

**Issue by SephReed** [brave/brave-browser#7223]
## Why?
Because using electron to package a web app seems really ridiculous compared to users being able to just "appify" any page themselves.  Further, any webpage you typically have many tabs open of would be easier to keep tidy if those tabs were in a separate browser with a visually different taskbar icon.

## Description 
This is a new feature I longed to see for many years now.  It goes:

1. Click `Tab > Appify Tab Domain`

2. Follow Prompts
```
Automatic updates? [enabled | ask | disabled]
Icon? [use favicon | custom image]
Urls? [open tabs domain | custom url list]
Where would you like to save this app? [choose location]
```

3. An "app" is created.  When ran, the app opens up in the task bar as a separate "browser" with the specified icon.   Like Electron but even easier.

## Details of Use
- Any links which don't share a domain with the "appified" site (external links) would be opened in an external browser (similar to clicking a link in any other application).
- Optionally disable URL bar or tab bar.  Would make full screen web apps look like actual applications.
- If one appified browser crashes, others do not.
- Updates from the site are treated as "app updates."  The changes are made apparent.

## Sites I personally would appify
- GitHub <-- so many tabs
- Gmail
- Internet Radio (tired of it crashing when things go wrong with other pages)

## Inevitability
In any case, it's only a matter of time before one browser creates this feature, then every other one will do so.  Then every site will be begging you to appify it, yada yada.  But the point is, you guys can (and should) be first.  You're doing a great job of pushing the internet forwards, Electro apps are obviously taking over the world, and you're in a position to do one better than that.

**Comment by SephReed** [comment]
I should mention, this is not meant to be a replacement for Electron and all its features.  It's just a better way of managing sites which take up many many icons and are practically full on applications.

**Comment by bsclifton** [comment]
@SephReed users can already do this with PWA (progressive web apps). In the hamburger menu, you can pick `Create shortcut`
<img width="549" alt="Screen Shot 2020-01-13 at 12 46 16 AM" src="https://user-images.githubusercontent.com/4733304/72239391-2c25c880-359e-11ea-871d-0bc31b1aba66.png">

**Comment by SephReed** [comment]
Huh.  This is really neat, and I appreciate the link, but neither the current implementation nor any forseeable future implementation meets the use case I was talking about.

This really seems like a corporate first approach, not something with any amount of control from the user.

**Comment by bsclifton** [comment]
@SephReed PWA is a large effort and is continuing to gain features and support. I think that would be the right area to focus your feedback. It's supported not only on Desktop, but on mobile. Some Brave users avoid apps completely on their phone and pin everything as a PWA

I don't see us deviating from that, to accommodate specific use cases. We just don't have the resources to do this and I personally don't see this receiving priority over any existing development

**Comment by SephReed** [comment]
> I personally don't see this receiving priority over any existing development tasks

Thank you for being honest.

I personally would like to use PWAs instead of apps as well, but am not a fan of the complete lack of user control on how they're generated... I'll open a different more specific feature request for that.

**Comment by cclambie** [comment]
Just wanted to say thanks for this PWA is exactly what I have been looking for a solution for.
I was asking for a way to change the app icon in the taskbar to the favicon on a tab (if a single tab was open in a window) and Boom! You, the great Brave have done it! Total convert now! Thanks!
