### ISSUE TITLE
Brave Ads server retry logic should backoff exponentially with a ceiling

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#7226]
Brave Ads server retry logic should backoff exponentially with a ceiling, as currently there are infinite retries without backing off which can cause performance issues and reduce battery life on mobile devices

**Comment by GeetaSarvadnya** [comment]
Verification is in progress


Brave | 1.8.84 Chromium: 81.0.4044.122 (Official Build) (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/5197
1. Verified catalog downloads at browser startup
