### ISSUE TITLE
P3A - Extensions value isn't updated after installing extensions

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7228]
## Description 

Found while testing #6285
Extensions value isn't updated after installing extensions

## Steps to Reproduce

   1. Clean profile 1.1.18
   2. Install an extension
   3. See brave://local-state file
   4. Extensions value isn't updated after installing extensions

## Actual result:

Extenions value isn't updated after installing extensions

## Expected result:

The value should be based on the no of extensions installed

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.1.18 Chromium: 79.0.3945.56 (Official Build) (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @bsclifton @rebron @mattmcalister

**Comment by GeetaSarvadnya** [comment]
The restart browser is showing the expected value. Please close the issue if it's expected. Thanks!

**Comment by iefremov** [comment]
@GeetaSarvadnya Yep, this is expected. The value is recorded on a startup.

**Comment by LaurenWags** [comment]
@mattmcalister we probably want to keep specs updated with info like this - meaning, if certain data isn't dynamically updated but only captured on start up like extensions, this should be noted in the spec somewhere otherwise QA is unsure where/when/how this information is obtained. cc @kjozwiak

**Comment by bsclifton** [comment]
@LaurenWags since the wiki is public facing (linked to from our blog), I went ahead and updated question 16 with `only queried on program start` 😄 I'll make similar edits for any others (just flag me!)

**Comment by LaurenWags** [comment]
great idea - updating the wiki! thanks @bsclifton!
