### ISSUE TITLE
Set time zone to UTC with fingerprinting protection enabled

### ISSUE THREAD

**Issue by riastradh-brave** [brave/brave-browser#723]
```
<!DOCTYPE html>
<html>
<body>
<p id="foo">foo</p>
<script>
document.getElementById('foo').innerHTML = new Date(Date.now()).toLocaleString()
</script>
</body>
</html>
```

This should report UTC.  (If you set your locale to UTC, or if you live in Iceland or Liberia, make sure to set it to something else before testing this.)  Any other time zone vectors should be fixed to UTC.

**Comment by riastradh-brave** [comment]
https://github.com/brave/browser-laptop/issues/10247

**Comment by pes10k** [comment]
closing in favor of https://github.com/brave/brave-browser/issues/8574
