### ISSUE TITLE
P3A- Tab stats along with it's value isn't displayed in logs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7230]
## Description 

Found while testing #6285 
P3A- Tab stats along with it's value isn't displayed in logs

## Steps to Reproduce

   1. Clean profile 1.1.18
   2. Open 11 tabs and load any sites
   3. Tab stats along with value isn't displayed in logs
   4. Reload brave://local-state file and restart the browser didn't help

## Actual result:

P3A- Tab stats along with it's value isn't displayed in logs
![image](https://user-images.githubusercontent.com/38657976/70271718-f33f4a80-17cc-11ea-93fc-4c9bb4df8063.png)

## Expected result:
Tab stats along with its value should be displayed in logs. 

![image](https://user-images.githubusercontent.com/38657976/70272389-2b935880-17ce-11ea-85ee-58370b7d5ba7.png)

## Reproduces how often: 

Intermittent

## Brave version (brave://version info)

Brave | 1.1.18 Chromium: 79.0.3945.56 (Official Build) (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? Not sure
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @bsclifton

**Comment by iefremov** [comment]
@GeetaSarvadnya This is probably expected, the metric is recorded every 5 minutes. Could you please re-check?

**Comment by LaurenWags** [comment]
It looks like this does appear after about 5 minutes. we can probably close this one as it's expected.

@iefremov am I correct in thinking that the 5 minutes also applies to `Brave.Core.WindowCount` as well? any others?

@bsclifton think this is a good candidate to include in the wiki?

**Comment by bsclifton** [comment]
@LaurenWags absolutely 😄

**Comment by iefremov** [comment]
@LaurenWags yes :)

**Comment by bsclifton** [comment]
Closing as expected 👍
