### ISSUE TITLE
Brave Dev has "Chromium" branding on "Manage People" menu

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#7234]
## Description 

In Dev build:
```
Brave | 1.3.56 Chromium: 79.0.3945.56 (Official Build) dev (64-bit)
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | macOS Version 10.15.1 (Build 19B88)
```
`Manage People` menu looks like this:
![image](https://user-images.githubusercontent.com/3299098/70286052-7c7b6080-177e-11ea-94d5-8b5186a0faa9.png)

## Steps to Reproduce

   1. Open Profile Manager screen in Brave Dev

## Actual result:

Shows "Chromium" 

## Expected result:
Should show "Brave"

## Reproduces how often: 

Always

**Comment by rebron** [comment]
<img width="1186" alt="Screen Shot 2020-01-06 at 3 06 33 PM" src="https://user-images.githubusercontent.com/5951041/71855532-24de5680-3096-11ea-8d40-25cc0e5488dd.png">
@Brave-Matt Can you try again in Beta? see screenshot above.

**Comment by rebron** [comment]
Closing. Looks like this issue isn't happening any longer.
