### ISSUE TITLE
Why am I not seeing Ads?

### ISSUE THREAD

**Issue by spiritbird86** [brave/brave-browser#7236]
I am New  on Brave  and ads not working  and  no bar despite  that my Wallet Verified ?? and  Notification on ?

it's same  problem on both mobile and desktop devices??  

plz help  

![image](https://user-images.githubusercontent.com/26479716/70290251-fb54b580-17df-11ea-98c6-2cb524719e05.png)

**Comment by Landris18** [comment]
that's brave

**Comment by bsclifton** [comment]
cc: @NejcZdovc @tmancey

**Comment by tmancey** [comment]
@spiritbird86 Can you please let us know where you are located, and the region settings on your devices. Thank you

**Comment by tmancey** [comment]
@Landris18 If you could let us know the issues you are experiencing so we can help? Thank you

**Comment by spiritbird86** [comment]
located on Palestine

**Comment by bsclifton** [comment]
@jsecretan @tmancey is this a supported region?

**Comment by tmancey** [comment]
@bsclifton This is not a supported region at this time, thanks

**Comment by tmancey** [comment]
@spiritbird86 Palestine is being added in a future version of Brave which is being tracked by https://github.com/brave/brave-browser/issues/7817
