### ISSUE TITLE
Disable opening Tor in guest window

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#7237]
## Description 
Currently UI items for opening private window in a guest window is disabled, we should behave the same to not allow opening Tor window in a guest window too to be consistent.

## Steps to Reproduce
   1. Open a guest window and visit brave.com
   2. Open hamburger menu, file menu (macOS)
   3. Open context menu by right click on a link in the website.

## Actual result:
Hamburger menu:
<img width="370" alt="Screen Shot 2019-12-06 at 2 00 25 PM" src="https://user-images.githubusercontent.com/4730197/70299801-d8062680-1830-11ea-91b1-4b3264cdc3a2.png">

File menu (macOS):
<img width="275" alt="Screen Shot 2019-12-06 at 2 00 32 PM" src="https://user-images.githubusercontent.com/4730197/70299823-ece2ba00-1830-11ea-8812-df37fc48fb49.png">

Context menu:
<img width="305" alt="Screen Shot 2019-12-06 at 2 00 43 PM" src="https://user-images.githubusercontent.com/4730197/70299838-f79d4f00-1830-11ea-8d7b-ccc0331174fa.png">

## Expected result:
Hamburger menu:
<img width="364" alt="Screen Shot 2019-12-06 at 8 52 11 AM" src="https://user-images.githubusercontent.com/4730197/70299891-1bf92b80-1831-11ea-9a5f-e93c11be8406.png">

File menu (macOS):
<img width="278" alt="Screen Shot 2019-12-06 at 8 52 17 AM" src="https://user-images.githubusercontent.com/4730197/70299895-1e5b8580-1831-11ea-88f2-f5b35ad64ad9.png">

Context menu:
<img width="303" alt="Screen Shot 2019-12-06 at 8 52 37 AM" src="https://user-images.githubusercontent.com/4730197/70299910-29161a80-1831-11ea-8d14-f61c0524c773.png">

## Reproduces how often: 
Always.

## Brave version (brave://version info)
For all versions after 1.1.x.

**Comment by LaurenWags** [comment]
@yrliou looks like the option for `New Private Window with Tor` is still displayed in the hamburger menu but is grayed out. Test plan in PR specifies that this shouldn't be there though. Can you confirm if what we should be seeing?

<img width="383" alt="Screen Shot 2019-12-16 at 3 02 57 PM" src="https://user-images.githubusercontent.com/28145373/70939470-57a4aa00-2016-11ea-89df-af79f93e11c8.png">

Brave | 1.2.27 Chromium: 79.0.3945.79 (Official Build) beta (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | macOS Version 10.13.6 (Build 17G5019)

**Comment by bsclifton** [comment]
@LaurenWags this behavior should be good 😄 I believe this is properly fixed in 1.4 with https://github.com/brave/brave-core/pull/4235 (see screenshots)

**Comment by yrliou** [comment]
@LaurenWags There are something that my PR was built upon which is only in 1.3 and later. I only uplift my own PR to make changes minimum, we should be fine in later versions.

**Comment by LaurenWags** [comment]
thanks for confirming @bsclifton and @yrliou 😄

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.2.28 Chromium: 79.0.3945.79 (Official Build) beta (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4155
Encountered https://github.com/brave/brave-browser/issues/7237#issuecomment-566223195

![image](https://user-images.githubusercontent.com/34715963/71086663-bd21a380-219a-11ea-924e-5bd87bd4a63f.png)
![image](https://user-images.githubusercontent.com/34715963/71086677-c448b180-219a-11ea-95f1-5ebba0d5e324.png)
