### ISSUE TITLE
[Feature request] Also sync extensions across devices

### ISSUE THREAD

**Issue by vladrusu** [brave/brave-browser#7238]
The original discussion/feature request is here: https://community.brave.com/t/sync-extensions-across-devices/41222

The issue is that currently Brave only syncs _bookmarks_.
It would be also very nice if we were be able to also **sync extensions** we have installed, so we can for example share the same extensions at home and at work.

**Comment by vdrover** [comment]
Important feature.

**Comment by itisafrickinhighlander** [comment]
This would also enable other features, such as an ability to have cloud synced custom Filters/Rules list in extensions such as uBlock Origin or uMatrix. From my experience I have to say this is an extremely time-consuming thing doing outside browser extension sync (Chrome and Firefox support this).

**Comment by vinismarques** [comment]
Would love to have this feature. It is one feature that is very behind when comparing against competitors.

**Comment by M0E-lnx** [comment]
The lack of this feature is keeping me from switching to brave.  I still have to fire up FF when I need to access data saved in my sync account there.

**Comment by hugotrsd** [comment]
Possible duplicate of #4094

**Comment by bsclifton** [comment]
Thanks for catching that, @hugotrsd 😄 This is indeed a duplicate of https://github.com/brave/brave-browser/issues/4094

Will close this in favor of that issue

**Comment by rubencg195** [comment]
THIS IS ESSENTIAL. PASSWORD SYNCING IS ANOTHER.
