### ISSUE TITLE
Refactor logging in Brave Rewards/Ads/Confirmations to support Chromium log verbosity

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#7242]
Original issue: https://github.com/brave-intl/bat-native-ads/issues/126

**Comment by tmancey** [comment]
Closing issue as it is a duplicate of https://github.com/brave/brave-browser/issues/6845

**Comment by LaurenWags** [comment]
@tmancey since logging changed so much, could @brave/legacy_qa get a list of flags that we should check and a wiki update for https://github.com/brave/brave-browser/wiki/Rewards#logging ? Thanks!

**Comment by LaurenWags** [comment]
Discussed briefly with @tmancey. Test plan is to use `--args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6` and confirm that you see `ads_impl.cc`, `ledger_impl.cc` and `confirmations_impl.cc` in the logs.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.85 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-browser/issues/7242#issuecomment-653049458
* Clean profile, launched with appropriate flags. Enabled Rewards. Confirmed I saw expected information in the logs. Here are some examples (others exist):

```
[18687:775:0702/104246.972816:VERBOSE1:ads_impl.cc(126)] Initializing ads
```

```
[18687:775:0702/104246.973186:VERBOSE5:ledger_impl.cc(452)] 
```

```
[18687:775:0702/104246.976381:VERBOSE3:confirmations_impl.cc(782)] Confirmations state does not exist, creating default state
```
