### ISSUE TITLE
Refreshing page after clicking an ad causes multiple landed confirmations

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#7249]
## Description 

Refreshing page after clicking an ad causes multiple landed confirmations

## Steps to Reproduce

   1. Click an ad
   2. Refresh page (multiple times)

## Actual result:

Multiple landed confirmations are sent to ads-serve

## Expected result:
Should only send a single landed confirmation to ads-serve

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.4.85 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.14.6 (Build 18G103)

* Reproduced the issue on 1.3.115
* Verified STR from description
