### ISSUE TITLE
Pin browser to taskbar changes browser icon 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#725]
## Description 

Pin browser to taskbar changes browser icon 

## Steps to Reproduce

   1. Download the windows installer and install the latest dev build
   2. Wait for browser to launch on install, ensure it shows the Blue lion icon with dev text
   3. Without closing the browser window, pin the browser icon to taskbar, Icon changes to Orange release build icon

## Actual result:

Pin browser to taskbar changes browser icon 
![ping](https://user-images.githubusercontent.com/17010094/43924386-8654c7d0-9bf2-11e8-93f5-7e5213192e0b.gif)

## Expected result:
Should retain the dev build icon

## Reproduces how often: 

~Intermittent. Happens on the first install on Desktop but wasn't able to reproduce it on VM as it already had the install before. Will update issue after checking on a second VM~
Update: Happens on clean install as per recorded screen recording)

## Brave version (about:brave info) 

0.53.2

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Looks like an issue with cache from previous install. Doesn't reproduce on a clean VM.

**Comment by darkdh** [comment]
I saw this yesterday on my clean VM instance, installed 0.54 from stub installer.
But I uninstalled it and install it again today from stub installer, the problem went away.

**Comment by srirambv** [comment]
Reopening the issue. Still reproducible with Nightly build. @jonathansampson was also able to reproduce the issue on his machine.

**Comment by rebron** [comment]
@srirambv @jonathansampson I can't reproduce this with 1.9.x. Let me know if this is still an issue.

**Comment by jonathansampson** [comment]
@rebron I cannot reproduce either.
