### ISSUE TITLE
Sync missing bookmarks after chain creation

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#7251]
## Description 

I made a regression in PR https://github.com/brave/brave-core/pull/3988/files#diff-ab344835b09fb6ac1c601af787b116bbL223 

there is a discussion of that changes and I missed point 3 which was addressed by `pending_send_records_` : device can switch to SQS , but lambda didn't yet discover that records, so such records could be missed. This happens after sync initialization, if there are some records created right after device connected to chain.

`pending_send_records_` - fixed that when there are two devices in chain, so 1st device didn't send records until be sure 2nd device created SQS  queue and the queue is discovered by lambda. But with 3 devices this approach could not work, though with 3rd device it is extremly hard to reproduce such case.

## Steps to Reproduce

   1. Get deviceA with bookmarks A1.com, A2.com and deviceB with bookmarks B1.com, B2.com
   2. Enable sync on deviceA, copy sync code to deviceB to establish the chain
   3. Don't wait until chain is fully created and on deviceA create in bookmarks folder `folderA` and the bookmark `AA.com` as soon as you can after step2

## Actual result:

   4. `AA.com` and `folderA` will never be created on deviceB. Any bookmarks created later on deviceA will be synced well.

## Expected result:
4. `AA.com` and `folderA` will be created on deviceB on the next sync cycle

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.4.3 Chromium: 79.0.3945.56 (Developer Build) (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? Probably yes, because of migrated https://github.com/brave/brave-core/pull/3988
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by AlexeyBarabash** [comment]
As uplift https://github.com/brave/brave-core/pull/4203 was merged to 1.3.x, modified the milestone.

**Comment by btlechowski** [comment]
Added `QA/Blocked` as testing is blocked on https://github.com/brave/brave-browser/issues/6941

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as both https://github.com/brave/brave-core/pull/4407 & https://github.com/brave/brave-core/pull/4408 have been merged. Once we get a new `1.3.x` build that's `> 1.3.100`, QA should be able to verify this issue.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.111 Chromium: 80.0.3987.85 (Official Build) (64-bit)
-- | --
Revision | 583b05dfa4ffc657f0f7c5cc13f53aa17c9a5bcf-refs/branch-heads/3987@{#791}
OS | Ubuntu 18.04 LTS

Verified test plan from the description. First `A1.com, A2.com, B1.com, B2.com` were synced, then folder `a` and bookmark `aaa`. Verified 5 times. Also switched devices.

![image](https://user-images.githubusercontent.com/34715963/73876517-69a50b00-4857-11ea-82ef-75c5e5f5a2ed.png)
