### ISSUE TITLE
P3A - Ads response value isn't updated correctly in upgraded profile

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7253]
## Description 

Found while testing #6285
Ads response value isn't updated correctly in an upgraded profile. Found while testing Q17

Q17: Have you enabled Brave Ads?
(Brave.Rewards.AdsState)

1. No wallet created
2. Wallet created, ads not enabled
3. Wallet created and ads enabled
4. Wallet created, ads enabled, then disabled, while Brave Rewards remains on
5. Wallet created, ads enabled, then disabled, Brave Rewards disabled

## Steps to Reproduce

   1. Clean profile 1.0.1
   2. Enable rewards
   3. Disable Ads
   4. Upgrade profile to 1.1.18
   5. Wait for 5 mins to see Ads state in the local state file
   6. Ads stats response value is displayed as `0` instead of `1`
   

## Actual result:

Ads response value isn't updated correctly in upgraded profile

## Expected result:
Ads response value should be updated correctly in upgraded profile

## Reproduces how often: 

Always
## Brave version (brave://version info)

1.1.18

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @brave/legacy_qa @iefremov @bsclifton @rebron

**Comment by LaurenWags** [comment]
I waited 20+ minutes and this question - Q17, didn't appear in my upgraded profile. It seemed like questions were slowly being added to my upgraded local-state file. I eventually got up to 14 questions and then they seemed to stop appearing in local-state.

After following the STR in description, upgrading, and waiting the 20 minutes, I toggled Ads on and off again in brave://rewards and then the question displayed in local-state. When I did this I got the expected value of `3` which corresponds to `Wallet created, ads enabled, then disabled, while Brave Rewards remains on` per stats.

**Comment by GeetaSarvadnya** [comment]
@LaurenWags There is a change in your STR.
>I toggled Ads on and off again in brave://rewards and then the question displayed in local-state.

I haven't performed this step in the original issue. I have enabled wallet and disabled ads in 1.0.1. After upgrade to 1.1.18, it should have recorded the value as 1 instead of 0

**Comment by LaurenWags** [comment]
@GeetaSarvadnya I added that step bc after waiting 20+ minutes the question never appeared on my upgraded profile 😞

**Comment by iefremov** [comment]
@LaurenWags should be fixed here https://github.com/brave/brave-core/pull/3931

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.4.84 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/74223153-11995900-4cdc-11ea-802d-d0c80b53e290.png)
