### ISSUE TITLE
info icon on P3A info bar should be updated

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7257]
## Description 

Found while testing #6285 

The info "i" icon on the P3A notification bar is blue. This should be updated per discussion with @karenkliu 

## Steps to Reproduce

   1. Have a profile on 1.0.1
   2. Update to 1.1.x
   3. See P3A info bar

## Actual result:
<img width="1194" alt="Screen Shot 2019-12-06 at 4 02 51 PM" src="https://user-images.githubusercontent.com/28145373/70357603-52d93c80-1845-11ea-9e89-d16b9adc72ba.png">

## Expected result:
info icon should be updated to be Brave style:
[icon-info.svg.zip](https://github.com/brave/brave-browser/files/3934098/icon-info.svg.zip)

## Reproduces how often: 
easily

## Brave version (brave://version info)
1.1.18

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @bsclifton @rebron @brave/legacy_qa

**Comment by kjozwiak** [comment]
Removing this from the `1.1.x` milestone after discussing it with @bsclifton @rebron. This seems like a minor problem that can be fixed in the next version if needed. We don't have time to get this fixed and into a new RC as we're releasing tomorrow.

**Comment by bsclifton** [comment]
Closing as stale - P3A has been rolled out and the infobar isn't shown for new users. It would only be shown for people that had installed Brave 1.0 and then upgrade to whatever the current version is
