### ISSUE TITLE
P3A - Response value isn't displayed correctly for default browser set after upgrade

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7259]
## Description 

Found while testing #6285
The response value isn't displayed correctly for default browser set after upgrade

Q2: Have you made Brave your default browser?
(DefaultBrowser.State)

1. No
2. Yes

## Steps to Reproduce

   1. Clean profile 1.0.1
   2. Upgrade to 1.1.18
   3. Restart the browser, click on set default notification
   4. Set Brave as a default browser in 1.1.18
   5. The response value is displayed as 0 instead of 1

Note: Waited for more than 10 mins to see the correct value reload the local-state file didn't help
## Actual result:

The response value is displayed as 0 instead of 1

## Expected result:
The response value should be displayed correctly

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.1.18 Chromium: 79.0.3945.56 (Official Build) (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Reproduced by @srirambv 

cc: @brave/legacy_qa @iefremov @bsclifton @rebron

**Comment by LaurenWags** [comment]
This did not reproduce for me on macOS. Followed STR from description and `DefaultBrowser.State` updated for me on an upgrade profile. 


Brave | 1.1.18 Chromium: 79.0.3945.56 (Official Build) (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | macOS Version 10.13.6 (Build 17G5019)

**Comment by iefremov** [comment]
Basically, this is recorded on a browser startup. So @GeetaSarvadnya could you please retest, making sure that the browser is restarted after setting it as default?

**Comment by GeetaSarvadnya** [comment]
@iefremov: I have restarted the browser after setting the default browser but response value is still displayed as `0` instead of `1`  - This could be windows specific issue.

**Comment by GeetaSarvadnya** [comment]
@iefremov This issue is fixed and working fine in 1.5.43
