### ISSUE TITLE
Confirm spell check works (multiple languages)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#726]
I believe the setting for this was disabled when solving https://github.com/brave/brave-browser/issues/512 (with https://github.com/brave/brave-core/pull/244). It's hard for me to tell if spelling corrections are coming from my operating system (macOS) or from Brave Core

`browser-laptop` supports multiple languages:
![screen shot 2018-08-09 at 1 56 03 pm](https://user-images.githubusercontent.com/4733304/43925390-fef43d90-9bdb-11e8-83eb-4d7d3c51ee1f.png)

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/spell-check-not-available-for-selected-country/35995/3

**Comment by F0rt1s** [comment]
![image](https://user-images.githubusercontent.com/5212636/49731418-92456b00-fc7b-11e8-8b77-038136e7ce26.png)

Still disabled in the latest release.

**Comment by Brave-Matt** [comment]
Still disabled for languages other than English (US) in release build (v0.58.18). +1 from Community:
https://community.brave.com/t/brave-spell-check-in-other-languages/41378

**Comment by Musiphilos** [comment]
Still not working on 2020. Spell check in non-English dictionaries is a vital feature for me.

**Comment by tobwen** [comment]
Same here: Version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)

I wonder what's more important in a modern browser: spelling support for human input or a crypto wallet?!

**Comment by marcNY** [comment]
Is that issue fixed? I am not able to get spell suggestions for French but I have them for English.

**Comment by tobwen** [comment]
Nope, still no German dictionary (and maybe others missing, too) .

**Comment by oliver-thirtyone** [comment]
Still not working in 2021 😞 
I just moved my mail, calendar and note tabs to Brave and I'm **very** surprised that this feature is lacking.
This might be (the only) reason I won't use the Brave browser...

**Comment by FrancoisMentec** [comment]
This is perfectly working for me right now:
![image](https://user-images.githubusercontent.com/22057576/118655516-ead4a700-b7e9-11eb-8a58-d12aa22b8f98.png)
As you can see in this screenshot, I have spell checking enabled for both English and French, and it's working just fine.
This issue should be closed.

**Comment by sergeG** [comment]
What version of Brave do I need to have working spell check?

> As you can see in this screenshot, I have spell checking enabled for both English and French, and it's working just fine.
> This issue should be closed.

**Comment by tobwen** [comment]
> What version of Brave do I need to have working spell check?

I'm in v1.25.68 and do have German spell checking now. But I cannot add additional languages, like English. This is shown in the screenshot of @FrancoisMentec

**Comment by sergeG** [comment]
OK, I succeed to add American English to my default Russian

It seems that general "English" do not have a dictionary. 

Brave Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit), linux

**Comment by Tonev** [comment]
The default English language at brave://settings/languages doesn't have its own dictionary. You have to manually add "English (United States)" and/or "English (United Kingdom)" if you want a spell check support for either or both of them.

**Comment by vokiel-too** [comment]
Brave Version Version 1.25.72 Chromium: 91.0.4472.101

This is not working for jock.  Add to the bug: review the UI because this is hidden by something else and the screenshot posted above is some fantasy pic. Thanks.

**Comment by FrancoisMentec** [comment]
@vokiel-too all languages don't have spell check, I have no idea why it's like this, or where you can find a list of the ones which does. If you want spellcheck for french you can use regular french or French (France), and for English, you can use English (US).

**Comment by vokiel-too** [comment]
@FrancoisMentec  I see, this is a UI issue, you don't even see the English (US) enable/disable check until you add a language with an associated dictionary. The Spell check list needs to be displayed at all time, regardless of the languages set above imho

![image](https://user-images.githubusercontent.com/83961851/122464773-3dd68100-cf85-11eb-9f30-e51c08d5daca.png)

**Comment by bsclifton** [comment]
This should be good to go 😄 As users have noted, you have to add the languages in the settings page. There is then a spell check option and which languages to do spell check for

**Comment by FrancoisMentec** [comment]
Hello @bsclifton 
This is an old issue, so I do not remember everything, and stuff may have changed since. But the issue is more with the UI than the spellcheck itself. It is unclear in the interface that you have to add languages to enable spell check for them. Many people assume that adding languages is for translating the interface and that it has nothing to do with spellcheck. Also, some languages do not support spellcheck, this should be indicated. For example, Windows shows icons on languages to indicate what is supported:
![image](https://github.com/brave/brave-browser/assets/22057576/bcada31b-4b59-4cfa-8694-6d129a49a5de)
I do not think this issue needs to be re-opened, but a different issue specifically targeting the UI should be IMHO. Just my grain of salt.
Best regards.
