### ISSUE TITLE
Brave read wrong registrykeys.

### ISSUE THREAD

**Issue by Johann999** [brave/brave-browser#7264]
## Description 
Brave read wrong registrykeys.
Brave read the registrykeys from Chromium browser.

![brave registry](https://user-images.githubusercontent.com/53431361/70375642-52ea4280-1900-11ea-911e-6e83af7de255.png)

## Steps to Reproduce

   1. start Brave 
   2. 
   3. 

## Actual result:
Brave read the registrykeys from Chromium browser.

## Expected result:
Brave shouldn't read the registrykeys form Chromium browser.

## Reproduces how often: 
Allways

## Brave version (brave://version info)
Brave	1.0.1 Chromium: 78.0.3904.108 (Offizieller Build) (32-Bit)
Betriebssystem	Windows 10 OS Version 1809 (Build 17763.195)

## Miscellaneous Information:
other Chromium-based browsers  (Chrome, Vivaldi, Yandex, etc.) work correct.

**Comment by bsclifton** [comment]
Thanks for reporting, @Johann999 😄 

This is expected behavior for now - however we did fix with https://github.com/brave/brave-core/pull/3692 (version 1.3 and later)

The new registry key would be `HKLM\SOFTWARE\Policies\BraveSoftware\Brave` 😄
