### ISSUE TITLE
Constant Freezes

### ISSUE THREAD

**Issue by MrTeeXD** [brave/brave-browser#7268]
## Description 

So, I have been using Brave for a while now and I constantly get freezes everytime I open a new tab and its infuriating me to the point where its unbearable. Even when I first open Brave for the first time today, it freezes.

## Steps to Reproduce

   1. Open Brave
   2. Open a few tabs
   3. Brave should freeze the moment a tab has finished loading

## Expected result:
Brave should not freeze when I open a few tabs or Start Brave for the first time.

## Reproduces how often: 

It happens alot everyday

## Brave version (brave://version info)

Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Windows 10 OS Version 1909 (Build 18363.476)

## Version/Channel Information:

- Can you reproduce this issue with the current release? : Yes
- Can you reproduce this issue with the beta channel? : Yes
- Can you reproduce this issue with the dev channel? : Yes
- Can you reproduce this issue with the nightly channel? : Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? : No
- Does the issue resolve itself when disabling Brave Rewards? : No
- Is the issue reproducible on the latest version of Chrome? : Yes

**Comment by MrTeeXD** [comment]
So, this issue keeps re-appearing and theres no way to get around but by ending the process and starting Brave up again.

**Comment by bsclifton** [comment]
@MrTeeXD sorry that we missed this issue! Are you still using Brave / still experiencing this issue?

- Curious if you have Sync enabled? If so, you can leave the sync chain to see if this fixes the problem (captured with https://github.com/brave/brave-browser/issues/6098)
- Another option you can try would be visit brave://flags/#enable-oop-rasterization and DISABLING this option (captured with https://github.com/brave/brave-browser/issues/7581, fixed in our next release, 1.3)

**Comment by Nuc1eoN** [comment]
@MrTeeXD make sure to restart the browser after leaving the chain (if you are indeed using sync currently)

**Comment by ilyaigpetrov** [comment]
I experience freezes too during working with Gmail and other sites.
I tried both options offered by @bsclifton but none worked.

Some details (please, confirm if you get the same behavior):

1. During a freeze mouse pointer is movable but it doesn't react to underlying elements (doesn't change from sharp pointer to hand and back).
2. During a freeze you may still switch from tab to tab. And if you quickly switch to another tab and then back then freezing is gone for a short time.

**Comment by rebron** [comment]
@ilyaigpetrov and @MrTeeXD Can you update to the current release of the browser, 1.3.113 and let us know if you're still running into these freeze issues? Is it specific websites too?

**Comment by MrTeeXD** [comment]
Only when I open the browser for the first time.

**Comment by ilyaigpetrov** [comment]
@rebron No, no specific sites, all sites used to freeze. But currently they don't for a whole day in my Brave Nightly 1.6.9:
```
Brave | 1.6.9 Chromium: 80.0.3987.87 (Официальная сборка) nightly (64-bit)
-- | --
Версия | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
ОС | Linux
JavaScript | V8 8.0.426.16
```

**Comment by MrTeeXD** [comment]
Issue still exists and it is really annoying me now

**Comment by curtisshipley** [comment]
It happens to me, too. Several times day.

**Comment by MrTeeXD** [comment]
After some more testing, the culprit seems to be the Hardware Acceleration option doing this. Disabling the Hardware Acceleration Option will stop Brave from freezing.

**Comment by Nuc1eoN** [comment]
Currently no severe freezes in Brave for me.

However sync is obviously disabled, as well as HW accelaration since it was causing video issues for me, see #7706
