### ISSUE TITLE
Brave Fingerprint very unique

### ISSUE THREAD

**Issue by Justin-CB** [brave/brave-browser#7269]
Brave Nightly on OS X 10.14 has a fingerprint with at least 17.96 bits of identifying information(according to panopticlick). This is just 0.01 bit less than the release version of Google Chrome on the same platform. To reduce this, it might help to spoof/hide the plugin details and exclude some fonts for reduced entropy.

**Comment by Justin-CB** [comment]
Firefox &amp; Brave
![Captura de Pantalla 2019-12-08 a la(s) 12 41 29](https://user-images.githubusercontent.com/55590227/70393548-2fcf9980-19b9-11ea-8804-5ebd739ad233.png)
Chrome &amp; Brave
![Captura de Pantalla 2019-12-08 a la(s) 12 45 53](https://user-images.githubusercontent.com/55590227/70393549-31995d00-19b9-11ea-910c-b806c2c39bfd.png)



I know that the Nightly build's UA gives more info. b/c it's 1 ver. ahead, which is less used. That might just be the price to pay for using a testing version. Also, it might make sense to map languages to the most common online variant: for example mapping en-AU, en-GB, and en-US to en-US, or mapping es, es-419, and es-ES to whichever one is the most common.

**Comment by bsclifton** [comment]
cc: @diracdeltas @fmarier

**Comment by fmarier** [comment]
Indeed, we have a similar issue to [reduce our fingerprintability using fingerprint.js 2](https://github.com/brave/brave-browser/issues/2471) and [one specifically for fonts](https://github.com/brave/brave-browser/issues/816).

We're also considering [spoofing some values](https://github.com/brave/brave-browser/issues/5614) that can't be removed / hard-coded.

Thanks for sharing the panopticlick results!
