### ISSUE TITLE
Bring in latest l10n for c79.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#7271]
Pull latest l10n for Chromium 79.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)
-- | --
Revision | 99b6d241cf84f7fa7434ae8a59f9e74eb1464280-refs/branch-heads/3945@{#888}
OS | macOS Version 10.13.6 (assemblage 17G5019)

* Verified 1.1.x test plan items in French from https://github.com/brave/brave-core/pull/4183

Setting for Google push messaging:
<img width="711" alt="French-google setting" src="https://user-images.githubusercontent.com/28145373/70552656-cc27a680-1b47-11ea-9fed-ff855874298e.png">

Rewards changes:
<img width="390" alt="French-Send Tip and Set button" src="https://user-images.githubusercontent.com/28145373/70552667-d0ec5a80-1b47-11ea-84a0-70cd4af02fd7.png">
<img width="637" alt="French-Monthly Contribution text" src="https://user-images.githubusercontent.com/28145373/70552678-d34eb480-1b47-11ea-8cf2-eced14bb5769.png">

P3A:
<img width="1196" alt="French-P3A banner" src="https://user-images.githubusercontent.com/28145373/70552687-d8abff00-1b47-11ea-962e-063a35d97964.png">
<img width="705" alt="French-P3A Setting" src="https://user-images.githubusercontent.com/28145373/70552692-d9dd2c00-1b47-11ea-82ef-6be398fed1ff.png">
