### ISSUE TITLE
Add id with auto increment to pending contribution

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#7275]
We should add `id` in  pending contribution table. This way we don't need to send 3 params to determinate which one is which. It's also less error prone as in theory we could have record with the same 3 keys, meaning we would be deleting too much data.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.4.86 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/4177
![image](https://user-images.githubusercontent.com/38657976/74463370-c176ee00-4eb7-11ea-881b-64907d8784a0.png)
