### ISSUE TITLE
Hover/Focus effect on tab close button is too small

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#7276]
## Test plan
Hovering over the close button should look like this:
<img width="39" alt="Screen Shot 2019-12-09 at 10 39 04 AM" src="https://user-images.githubusercontent.com/4733304/70460455-974a1f80-1a73-11ea-8bdd-9bc8a444c2b7.png">

NOT like this:
<img width="32" alt="Screen Shot 2019-12-09 at 10 38 40 AM" src="https://user-images.githubusercontent.com/4733304/70460459-9c0ed380-1a73-11ea-9ea2-54fc59d97d44.png">

## Description
<img width="204" alt="Screen Shot 2019-12-09 at 8 31 56 PM" src="https://user-images.githubusercontent.com/6786187/70433996-6cd58200-1ac6-11ea-8087-145e0fad9cc3.png">

This looks regression from C79 bump.
Only `1.0` is fine. `1.2`, `1.3` and `1.4` all have this issue.
`1.1` could have same issue.

**Comment by bsclifton** [comment]
Pulling into 1.1 since this is a regression

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)
-- | --
Revision | 99b6d241cf84f7fa7434ae8a59f9e74eb1464280-refs/branch-heads/3945@{#888}
OS | macOS Version 10.13.6 (Build 17G5019)

<img width="322" alt="Screen Shot 2019-12-10 at 8 48 10 AM" src="https://user-images.githubusercontent.com/28145373/70534865-f1a5b780-1b29-11ea-9bfd-b7ae8bb30762.png">

<img width="337" alt="Screen Shot 2019-12-10 at 8 48 24 AM" src="https://user-images.githubusercontent.com/28145373/70534872-f4081180-1b29-11ea-9ca1-1875fb4de1cf.png">
