### ISSUE TITLE
Add up to to AC settings

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#7277]
Right now we don't have `up to` in AC settings, where we have it on default view. We need to add it

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.3.85 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | macOS Version 10.14.6 (Build 18G103)

* Verified test plan from https://github.com/brave/brave-core/pull/4179
<img width="653" alt="Screen Shot 2020-01-07 at 10 37 21 AM" src="https://user-images.githubusercontent.com/28145373/71907344-d2567600-3139-11ea-8b53-424d4a114adb.png">
<img width="637" alt="Screen Shot 2020-01-07 at 10 37 31 AM" src="https://user-images.githubusercontent.com/28145373/71907348-d4203980-3139-11ea-9135-0af51bc54fc6.png">
