### ISSUE TITLE
Brave fees need notes for user wallet transactions

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#7278]
When a user wallet -> Creator wallet transaction happens, at the moment the transaction is split --
95% goes directly to the creator
5% goes to Brave Software

We should add a note to the 5% transaction calling it as a "5% transaction fee"

cc @davidtemkin for text
@NejcZdovc @lukemulks @evq

**Comment by mandar-brave** [comment]
Uphold can't yet make fix available to us. 
Note: 5% transaction fee collected by Brave Software International

@NejcZdovc ready to ship!

**Comment by NejcZdovc** [comment]
expected:
![image](https://user-images.githubusercontent.com/9574457/70526410-c8951f00-1b49-11ea-9f8a-0d21190458bf.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from https://github.com/brave/brave-core/pull/4201
Message about 5% transaction fee displays in the email and on sandbox.uphold.com:
<img width="715" alt="Screen Shot 2019-12-13 at 9 11 20 AM" src="https://user-images.githubusercontent.com/28145373/70806222-cec50e80-1d88-11ea-9230-068ef55ca93d.png">
<img width="1166" alt="Screen Shot 2019-12-13 at 9 11 38 AM" src="https://user-images.githubusercontent.com/28145373/70806228-d08ed200-1d88-11ea-9c9c-a82e27c24960.png">
