### ISSUE TITLE
Brave TOS (user and creator) should add explicit fee collection 

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#7279]
@tomlowenthal our TOS should include the 5% fees we collect against every contribution.
If this is already included, please close the issue.

cc @davidtemkin

**Comment by tomlowenthal** [comment]
Terms for both [users](https://basicattentiontoken.org/user-terms-of-service/) and [publishers](https://basicattentiontoken.org/publisher-terms-of-service/) already say this.

> The total amount of Brave Rewards User contributions assigned to each site is calculated approximately every calendar month. Contributions are sent from User Wallets and made available to sites that are Brave Verified Publishers through a process facilitated by our third-party wallet provider, Uphold. This process is typically completed by the 8th day of the following calendar month. For operating the Service, we charge Brave Verified Publishers a fee equal to 5% of the contributions assigned to them.

Please re-open if this isn't sufficient.
