### ISSUE TITLE
Google Map embed not render

### ISSUE THREAD

**Issue by chinkung** [brave/brave-browser#7280]
## Description 

Brave has a problem with website embed Google Map content with API restricted by [HTTP referrers](https://cloud.google.com/docs/authentication/api-keys?hl=th&visit_id=637115068251990352-2979131502&rd=1#api_key_restrictions)

## Steps to Reproduce

   1. Use Brave browser to navigate to https://www.zaolong.in.th/branch/st-louis/

## Actual result:

The error is show up on embed map area

> Google Maps Platform rejected your request. This IP, site or mobile application is not authorized to use this API key. Request received from IP address 184.22.230.174, with referer: https://www.google.com/

## Expected result:
Static Map is rendered on the browser

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.0.1 Chromium: 78.0.3904.108 (Official Build) (32-bit)
-- | --
Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
OS | Windows 10 OS Version 1909 (Build 18363.476)
JavaScript | V8 7.8.279.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
Command Line | "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --profile-directory=Default --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=WebUIDarkMode,NewExtensionUpdaterService,SimplifyHttpsIndicator,PasswordImport --disable-features=AutofillServerCommunication,UnifiedConsent,AudioServiceOutOfProcess,SyncUSSBookmarks,NotificationTriggers,SmsReceiver,LookalikeUrlNavigationSuggestionsUI --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
Yes
- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:

1. This issue can be mitigated on client side by disable Brave Shield
1.  This issue can be mitigated on server side by add https://www.google.com/* to [Google Map API's HTTP referrers](https://cloud.google.com/docs/authentication/api-keys?hl=th&visit_id=637115068251990352-2979131502&rd=1#api_key_restrictions) list

**Comment by doom777** [comment]
To further drill down, you can resolve the issue by allowing all cookies

**Comment by rebron** [comment]
I think we need a new Social Media blocking pref for this or fold into "Allow Google logins".
@ryanbr Do you have suggestions for rules for this one?

**Comment by pes10k** [comment]
fixed with https://github.com/brave/brave-browser/issues/8696
