### ISSUE TITLE
Sync chain is reset but still shows other devices in list

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7283]
## Description 

Sync chain is rest but still shows other devices in list

## Steps to Reproduce

1. Create sync chain on desktop
2. Sync iPhone 1 to chain
3. Add boookmarks on both devices gets sync'd
4. Remove iPhone 1 from chain on desktop, resets on desktop too
5. Reinstall 1.14 build on iphone
6. Recreate sync chain on desktop and use iPhone 2 to sync
7. Bookmarks from desktop are not sync'd to iPhone 2
8. Add iPhone 1 to the chain 
9. No bookmarks form desktop go to either phones
10. Add a bookmark on either of the phones, all devices get bookmarks
11. Remove desktop on iPhone 2, sync is not reset on desktop instead it still shows sync enabled

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/70462574-36c5dd00-1a89-11ea-9ce9-f9c8a2163aa1.png)
![image](https://user-images.githubusercontent.com/17010094/70462591-3d545480-1a89-11ea-83c2-fa99feea8c01.png)
![image](https://user-images.githubusercontent.com/17010094/70462605-41807200-1a89-11ea-80a9-3bd275bfde13.png)

## Expected result:
Should reset sync on desktop 

## Reproduces how often: 

Pretty easy as @kjozwiak  was also able to reproduce it

## Brave version (brave://version info)

Desktop -  1.0.1 Release build
iPhone 1 - 1.14 dev build
iPhone 2 - 1.14 dev build

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @AlexeyBarabash @darkdh

**Comment by darkdh** [comment]
@srirambv is it reproducible if you replace 2 iPhone with 2 Android phones?
Or with 2 desktops?

**Comment by AlexeyBarabash** [comment]
Closing as the issue was for Sync v1
