### ISSUE TITLE
P3A enabled status not updated in all windows when toggled

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#7289]
## Description 
Found while addressing review feedback in https://github.com/brave/brave-core/pull/4044

If P3A status changes while the UI is open, the page is not notified / updated in real time.

## Steps to Reproduce
   1. Have two windows open
   2. Open brave://settings/privacy in both
   3. In one window, toggle the value for `Automatically send completely private product analytics to Brave`

## Actual result:
Toggle doesn't happen in both windows. It only affects the window you did it from.

## Expected result:
The other window should get notified of the change and update also.

## Reproduces how often: 
100%

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.4.82 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.14.6 (Build 18G103)

* Verified STR from description
