### ISSUE TITLE
Brave Sec Issue

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#7291]
https://github.com/brave/internal/issues/671

**Comment by btlechowski** [comment]
@ryanml Could you add `QA/Yes` or `QA/No` label to the issue?

**Comment by kjozwiak** [comment]
Definitely a `QA/Yes` as this is a security issue. The test plan can be found via https://github.com/brave/internal/issues/671#issuecomment-563459417.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.2.29 Chromium: 79.0.3945.79 (Official Build) beta (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/internal/issues/671#issuecomment-563459417
