### ISSUE TITLE
Suggestion : make a snap for brave browser (linux)

### ISSUE THREAD

**Issue by chemel9** [brave/brave-browser#7293]
Hi , i have a suggestion , could you make a snap for brave browser?
in this way all users can install brave browser, regardless of the linux distribution
please, thank you

https://snapcraft.io/

**Comment by srirambv** [comment]
Dupe of  #1007

**Comment by w0ts0n** [comment]
Currently community support. But please see:
https://snapcraft.io/brave

@chemel9

**Comment by chemel9** [comment]
thanks , but i think that they should put the link on their website .
there is not a link for snap . 
https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

**Comment by w0ts0n** [comment]
Due to the way snap is setup in a container, some of the core features of Brave (rewards, sandboxing) are not possible in snap. For this reason, the methods listed on 
https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux
are recommended and it won't be added to the website.
