### ISSUE TITLE
Broken formatting of Monthly Contributions in brave://rewards for some locales

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#7296]
The formatting of `Monthly Contributions` in `brave://rewards` in broken for Polish locale

## Steps to Reproduce

   1. Clean profile
   2. Open Brave in Polish locale
   3. Enable Rewards
   4. Open `brave://rewards`

## Actual result:

Broken formatting of Monthly Contributions. It looks squeezed.
![image](https://user-images.githubusercontent.com/34715963/70526578-2e81a680-1b4a-11ea-8c23-78d731fc61cb.png)

## Expected result:
![image](https://user-images.githubusercontent.com/34715963/70526655-5e30ae80-1b4a-11ea-8185-7f0e4c1a36ad.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)
-- | --
Revision | 99b6d241cf84f7fa7434ae8a59f9e74eb1464280-refs/branch-heads/3945@{#888}
OS | Ubuntu 18.04 LTS

Brave | 1.2.20 Chromium: 79.0.3945.56 (Official Build) beta (64-bit)
-- | --
Revision | 73cc6bf591f792b99f8fc7cdfb8addedbd084bf8-refs/branch-heads/3945@{#788}
OS | Ubuntu 18.04 LTS

cc @NejcZdovc @bradleyrichter @karenkliu @rebron @brave/legacy_qa

**Comment by NejcZdovc** [comment]
this can be also reproduced if you change description of the box to one word

![image](https://user-images.githubusercontent.com/9574457/70528425-773b5e80-1b4e-11ea-9a13-e0610e299a7c.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.4.81 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.14.6 (Build 18G103)

* Reproduced the issue using 1.3.113

* Verified test plan from https://github.com/brave/brave-core/pull/4211
<img width="661" alt="Screen Shot 2020-02-07 at 5 47 17 PM" src="https://user-images.githubusercontent.com/28145373/74071474-f70c6a80-49d1-11ea-8900-2cc820bbca5c.png">

* Verified the STR from description
<img width="651" alt="Zrzut ekranu 2020-02-7 o 5 51 31 PM" src="https://user-images.githubusercontent.com/28145373/74071640-8154ce80-49d2-11ea-936b-bb085af1c6ae.png">
