### ISSUE TITLE
Add claim date to promotion

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#7297]
Right now we don't track when user claimed a promotion. We need this info for monthly statement, so we should start logging it in DB.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.4.84 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

 - Verified that `claimed_at` parameter is NOT available in 1.3.x and previous versions
 - Verified that `claimed_at` parameter is added in the `promotion` table in 1.4.x
 - Verified that `claimed_at` parameter is showing timestamp value as `0` before claiming UGP grants
 - Verified that `claimed_at` parameter is showing grants claimed timestamp after claiming UGP grants

**Before claiming UGP grants:**
![image](https://user-images.githubusercontent.com/38657976/74236614-a0679f00-4cf7-11ea-9221-b97f32fb22d8.png)

**After claiming UGP grants:**
![image](https://user-images.githubusercontent.com/38657976/74236519-64343e80-4cf7-11ea-845f-d3a022169a89.png)

- Logged https://github.com/brave/brave-browser/issues/8180
