### ISSUE TITLE
Provide same list of Search Engines as browser-laptop with engine go key 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#731]
## Test plan
See https://github.com/brave/brave-core/pull/516

## Description 
Provide same list of Search Engines as browser-laptop with engine go key 

## Actual result:
![image](https://user-images.githubusercontent.com/17010094/43965571-9f3e2c64-9c8d-11e8-83df-1bbc8f037db7.png)

## Expected result:
Same list but probably without `:` in Engine go key
![image](https://user-images.githubusercontent.com/17010094/43966410-cd3a8a20-9c8f-11e8-9794-cec315fbb2f9.png)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/features-search-engine-go-keys-missing-colored-tabs-bookmarks-bar/33485?u=eljuno

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

* Verified all scenarios mentioned in test plan and works great
