### ISSUE TITLE
Camera access doesn't work in Brave even with shields down (Bitpay)

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#7311]
## Description 

When requesting higher limits from BitPay, it asks for a selfie and requests camera access.
If you allow it, even with shields down, the camera is blocked. 

On Chrome it works though.

<img width="880" alt="Screen Shot 2019-12-10 at 2 05 11 PM" src="https://user-images.githubusercontent.com/831718/70561195-0436e580-1b58-11ea-8ec2-a3088ae6b023.png">
<img width="879" alt="Screen Shot 2019-12-10 at 2 05 21 PM" src="https://user-images.githubusercontent.com/831718/70561197-04cf7c00-1b58-11ea-9f41-251b5f7e0fa1.png">

## Steps to Reproduce

   1. Create a BitPay account or login to yours if you already have one
   2. Click on "Unlock Higher Limits"
   3. Click on Proceed
   4. Upload your passport and go to the next step
   5. When asked to take a selfie, allow
   6. Optionally repeat for the same results with shields down.

## Actual result:

Doesn't allow camera access

## Expected result:

Should allow camera access

## Reproduces how often: 

Always

## Brave version (brave://version info)
Version 1.3.39 Chromium: 78.0.3904.108 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  I think so
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

Chrome works!

cc @jumde, pls take a look.
cc @bsclifton fyi.

**Comment by lucasfijen** [comment]
Does this happen to be on Ubuntu?
#9451 might be the same issue, there was a possible [fix posted there.](https://github.com/brave/brave-browser/issues/9451#issuecomment-623940993)
