### ISSUE TITLE
dismissed Rewards notifications come back after browser restart

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7313]
## Description 
I have 5 Rewards notifications that I dismiss from the BAT logo. However, once I restart my browser to receive an update, the 5 notifications are back. Again, I can dismiss them but once I restart they show up again.

## Steps to Reproduce

Not sure. I don't even know why there was a problem processing my contribution.

## Actual result:
In the gif below, I had already dismissed the notifications. I then relaunched Nightly (it takes some time, I have 100's of tabs 😄). Then on relaunch, the notifications are back. So I dismissed them again. Relaunch again and you can see the notifications have magically returned.

![magicallyreappearingnotifications](https://user-images.githubusercontent.com/28145373/70563313-026f2100-1b5c-11ea-9fd3-dd51f54e97b6.gif)

## Expected result:
Notifications should not reappear once dismissed.

## Reproduces how often: 
easily

## Brave version (brave://version info)

I experienced it on Nightly since that's my daily driver

Brave | 1.4.16 Chromium: 79.0.3945.74 (Official Build) nightly (64-bit)
-- | --
Revision | 99b6d241cf84f7fa7434ae8a59f9e74eb1464280-refs/branch-heads/3945@{#888}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? unsure
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @NejcZdovc 

This is my personal profile, not a test profile, so I will not be posting it to GH. If you need specific info from my ledger_state or another file let me know.

**Comment by NejcZdovc** [comment]
@LaurenWags is this still a problem?

**Comment by LaurenWags** [comment]
yes, happens to me each time I restart my current profile (Dev 1.8.66 currently). I can't reproduce it on a clean profile, so something in my profile is probably jacked.

**Comment by bsclifton** [comment]
@LaurenWags just about time for the yearly checkup 😂 Is this still happening for you?

The notices can definitely be profile specific. There's a JSON blob in there with each of them (if you're able to repro, you can share w/ me and I can help narrow down). I got into this same situation too and had over 50 un-dismissible messages 😛

**Comment by LaurenWags** [comment]
@bsclifton unfortunately that profile is long gone 😭 I'll close this issue and reopen if I see it happening again 👍🏻
