### ISSUE TITLE
Add road-block adblock list license

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#7322]
Now that the road-block list LICENSE has been specified (https://github.com/tcptomato/ROad-Block/issues/55), we should update the Brave Ad Block license notice.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.4.66 Chromium: 79.0.3945.130 (Official Build) dev (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

* Verified test plan from https://github.com/brave/brave-core/pull/4209
<img width="615" alt="Screen Shot 2020-01-22 at 4 40 58 PM" src="https://user-images.githubusercontent.com/28145373/72936854-0c2c9c80-3d36-11ea-8c68-73b930fe7f44.png">
