### ISSUE TITLE
Internal Error, ordering was unable to handle the media swap

### ISSUE THREAD

**Issue by CryptoRotator** [brave/brave-browser#7323]
## Steps to Reproduce

sudo apt install --fix-missing brave-browser brave-keyring
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Следующие НОВЫЕ пакеты будут установлены:
  brave-browser brave-keyring
Обновлено 0 пакетов, установлено 2 новых пакетов, для удаления отмечено 0 пакетов, и 15 пакетов не обновлено.
Необходимо скачать 76,7 MB архивов.
После данной операции объём занятого дискового пространства возрастёт на 241 MB.
Ошб:1 https://brave-browser-apt-release.s3.brave.com bionic/main amd64 brave-keyring all 1.7
  Не удалось соединиться с brave-browser-apt-release.s3.brave.com:443 (151.101.2.217). - connect (111: В соединении отказано)
Ошб:2 https://brave-browser-apt-release.s3.brave.com bionic/main amd64 brave-browser amd64 1.1.20
  Невозможно соединиться с brave-browser-apt-release.s3.brave.com:https:
E: Не удалось получить https://brave-browser-apt-release.s3.brave.com/pool/main/b/brave-keyring/brave-keyring_1.7-1.deb  Не удалось соединиться с brave-browser-apt-release.s3.brave.com:443 (151.101.2.217). - connect (111: В соединении отказано)
E: Не удалось получить https://brave-browser-apt-release.s3.brave.com/pool/main/b/brave-browser/brave-browser_1.1.20_amd64.deb  Невозможно соединиться с brave-browser-apt-release.s3.brave.com:https:
E: Internal Error, ordering was unable to handle the media swap

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
Closing. Can you go to https://community.brave.com and ask for support, we'll be able to respond to this one better over there.
