### ISSUE TITLE
Enabling IPFS support causes crash

### ISSUE THREAD

**Issue by nate2014jatc** [brave/brave-browser#7325]
## Description 

When changing the IPFS setting in `brave://settings/`, toggling it to "ON" will cause the browser to crash after a few seconds.

## Steps to Reproduce

   1. Open Settings.
   2. Toggle IPFS.
   3. Wait 1 - 3 Seconds.
   4. Crash.

## Actual result:

![Cinnamon-Dec-10-2019_22:39:32pm](https://user-images.githubusercontent.com/11836893/70595220-0de43b80-1ba0-11ea-929b-d5e54792a7fe.gif)

## Expected result:
Not crashing would be ideal.

## Reproduces how often: 

Every time

## Brave version (brave://version info)

1.1.20 Chromium: 79.0.3945.74

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? To be Tested
- Can you reproduce this issue with the dev channel? To be Tested
- Can you reproduce this issue with the nightly channel? To be Tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? I don't believe Chrome has that toggle

## Miscellaneous Information:

Linux Mint 19.1, using the Bionic branch of Ubuntu core, and using the Bionic apt repo to install

**Comment by srirambv** [comment]
Can you enable crash reporting and then toggle the setting to trigger a crash. You can copy the crash upload id and share here so that we can check the cause of crash

**Comment by nate2014jatc** [comment]
Sorry for the delay, 
It should be crashes `86d9a22d21b5c0de` and `f96134c3e3d57874`

**Comment by danrobi11** [comment]
Same here. 
Crash dump id:   90b027bf6ac95da1 
OS: Debian GNU/Linux 10 (buster) x86_64 
Kernel: 4.9.182-antix.1-amd64-smp 
Version 1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)

**Comment by srirambv** [comment]
cc: @bbondy Its pretty easily reproducible on Linux. Running from terminal produces this 
```
/usr/bin/brave-browser: line 48:  3492 Segmentation fault      (core dumped) "$HERE/brave" "$@"
```
Here's the crash reports which @nate2014jatc mentioned in https://github.com/brave/brave-browser/issues/7325#issuecomment-564968671
https://stats.brave.com/dashboard#crash/5df22431f1bfdf001f6bfd86
https://stats.brave.com/dashboard#crash/5df063426c097d001fb311df

**Comment by danrobi11** [comment]
same thing with version stable 1.1.21

**Comment by nate2014jatc** [comment]
Brave | 1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}

Upload ID: 3d8f019624a194e3

**Comment by nate2014jatc** [comment]
Causes issues on Beta channel as well.

Brave | 1.2.23 Chromium: 79.0.3945.70 (Official Build) beta (64-bit)
Revision | 65868db27916cebde51fc2465c9b34761e6383e2-refs/branch-heads/3945@{#869}



Uploaded Crash Report ID c256728621abce0e

**Comment by nate2014jatc** [comment]
Also buggy on Dev channel;

Brave | 1.3.65 Chromium: 79.0.3945.79 (Official Build) dev (64-bit)
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}

Crash ID: d049a526888b26e8

**Comment by nate2014jatc** [comment]
Another crash in 1.1.22 (Chromium 79.0.3945.79)
Crash Report ID f7b5e789f65570e4

Please let me know if me updating this with this level of frequency is more of a bother than a help.

**Comment by srirambv** [comment]
+1 from @Grathium-Industries  via #7584

**Comment by danrobi11** [comment]
Crash dump id: e74122cbb425eaf9
Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)
OS: MX x86_64 
Kernel: 4.19.0-6-amd64

**Comment by jpalczewski** [comment]
Crash dump id: a8a91f76ed1c1964
Brave | 1.2.42 Chromium: 79.0.3945.117 (Official Build) unknown (64-bit)
Installed via AUR,package brave-bin
os: Arch
Kernel: 5.4.10-arch1-1 #1 SMP PREEMPT Thu, 09 Jan 2020 10:14:29 +0000 x86_64 GNU/Linux

**Comment by danrobi11** [comment]
IPFS extension working here now
Brave version 1.3.115
OS: MX x86_64 
Kernel: 4.19.0-6-amd64

**Comment by rebron** [comment]
@nate2014jatc Sending the crash reports over is a help! Thanks.

**Comment by nate2014jatc** [comment]
@rebron :+1:

**Comment by dltwyman** [comment]
crashes here as well :  Linux , Version 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)

**Comment by Cristian-Bejan** [comment]
@srirambv @rebron Same issue on version 1.4.95
SegvReason - reading NULL VMA
/usr/bin/brave-browser-stable: line 48: 12927 Segmentation fault      (core dumped) "$HERE/brave" "$@"

[logMessages.txt](https://github.com/brave/brave-browser/files/4255152/logMessages.txt)

**Comment by lidel** [comment]
Hi folks, just to confirm this one is cause by the toggle logic and not the extension: are you able to install IPFS Companion via https://chrome.google.com/webstore/detail/ipfs-companion/nibjojkomfdiaoajekhjakgkdhaomnch without a problem?

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.8.76 Chromium: 81.0.4044.92 (Official Build) dev (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | Ubuntu 18.04 LTS

Reproduced the crash on 1.7.95.

Verified test plan from https://github.com/brave/brave-core/pull/5205
Verified ipfs extension installed without issues
![image](https://user-images.githubusercontent.com/34715963/79400027-46988500-7f85-11ea-97e0-8c7ef23c6e5d.png)
![image](https://user-images.githubusercontent.com/34715963/79400134-9b3c0000-7f85-11ea-89e2-cdc6663e6d0b.png)

**Comment by SCBuergel** [comment]
I reproduced the crash on 
Version 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)
running on Ubuntu 18.04 that is just freshly installed

thus IMO this issue is not closed.

**Comment by btlechowski** [comment]
@SCBuergel The issue is fixed in 1.8.x.

**Comment by SCBuergel** [comment]
Thank you @btlechowski - it seems the [install instructions](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux) linked on the brave website is not installing the latest version and also wont auto-upgrade via apt.

**Comment by btlechowski** [comment]
@SCBuergel 1.8.x has not been published on `Release` channel yet.

You can try this build on `Developer` channel: https://github.com/brave/brave-browser/releases/download/v1.8.82/brave-browser-dev_1.8.82_amd64.deb

**Comment by SCBuergel** [comment]
thank you @btlechowski - i was actually trying to figure out why my brave wouldnt update to the latest version before reading your reply. got it now and also realized that i'm on the same version as my macOS. Thanks for your support!
