### ISSUE TITLE
Flags do not save on relaunch.

### ISSUE THREAD

**Issue by FozzieHi** [brave/brave-browser#7326]
## Description 
`brave://flags` do not save when relaunching or manually reopening browser.

## Steps to Reproduce
   1. Change `Omnibox UI Hide Steady-State URL Scheme` to Enabled or Disabled.
   2. Relaunch
   3. Go back to `brave://flags` and the flag has not changed.

## Actual result:
The flag value didn't change. change.

## Expected result:
The flag value would change.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Version 1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Didn't test
- Can you reproduce this issue with the dev channel? Didn't test
- Can you reproduce this issue with the nightly channel? Didn't test

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by Johann999** [comment]
I have no such flag neither in Brave 1.1.20 nor in Google Chrome 79.0.3945.79.

**Comment by FozzieHi** [comment]
@Johann999 My mistake, I forgot you needed to enable `Temporarily unexpire M76 flags.` to view this flag, this might actually be related to the issue of the flags not working after the Chromium 79 update (maybe flag settings got changed?).

**Comment by rebron** [comment]
Closing. I think this need to be addressed in the Chromium bug system.

**Comment by FozzieHi** [comment]
It doesn't occur in Chrome though, surely this is Brave's implementation of Chromium?

**Comment by bsclifton** [comment]
@FozzieHi the flag you mentioned in the original post doesn't exist anymore; do you have another example I can try? All of the flags seem to be working fine for me

What platform are you on? (do you have OS specifics?)

**Comment by FozzieHi** [comment]
@bsclifton I don't have any other flags to try, it's possible this behaviour could be replicated by using other Expired flags that are shown when the "Temporarily unexpire M<version> flags." flag is enabled, if not the issue is probably obsolete.
