### ISSUE TITLE
Wiki changes: Add source code links to P3A wiki page

### ISSUE THREAD

**Issue by dionyziz** [brave/brave-browser#7337]
I've added a couple of source code links to the wiki page pertaining to P3A metrics. Here is my wiki fork:

https://github.com/dionyziz/brave-browser-wiki/tree/src_links

As I cannot open up a Pull Request for the wiki, you will have to merge this manually. However, here is the diff for your convenience:

https://github.com/dionyziz/brave-browser-wiki/pull/1

**Comment by bsclifton** [comment]
@dionyziz I should be able to help you with this soon 😄

**Comment by bsclifton** [comment]
@dionyziz sorry it took so long to respond here - I think I got distracted on the holidays, definitely my bad

I updated the page now with your suggested text- looks great! 😄 Thanks for the patch
