### ISSUE TITLE
Popups on ThePirateBay

### ISSUE THREAD

**Issue by GaryEarthling** [brave/brave-browser#7338]
## Description
ThePirateBay opens popup advertising tabs unexpectedly.

## Steps to Reproduce
1. Navigate to thepiratebay.org
2. Perform a search
3. Click on the first search result

## Actual result:
A new advertising tab is created unexpectedly.

## Expected result:
No popup or popunder advertising tabs.

## Reproduces how often:
Always

## Brave version (brave://version info)
Brave	1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)
Revision	99b6d241cf84f7fa7434ae8a59f9e74eb1464280-refs/branch-heads/3945@{#888}
OS	Windows 10 OS Version 1909 (Build 18363.535)

## Other Additional Information:
- Related issue: [Popups and Popunders on ThePirateBay #13730](https://github.com/brave/browser-laptop/issues/13730)

**Comment by ryanbr** [comment]
@GaryEarthling  should be looking better, can you confirm everything is working?

**Comment by ryanbr** [comment]
Closing this issue report, re-checked the site. No ads or popups seen. Looking good

Re-open if you see any issues @GaryEarthling
