### ISSUE TITLE
Disable Dashboard (NTP) gradient background color

### ISSUE THREAD

**Issue by zmni** [brave/brave-browser#7340]
## Description
Provide an option to disable dashboard (ntp) gradient background color.

## Steps to Reproduce

   1. Open Dashboard (ntp)
   2. Click Dashboard Settings
   3. There is no way to disable the gradient color.

## Actual result:
![brave-gadient](https://user-images.githubusercontent.com/841523/70715008-ed40f080-1d1b-11ea-8935-90001d2ffcac.jpg)

## Expected result:
![brave-solid](https://user-images.githubusercontent.com/841523/70715018-f3cf6800-1d1b-11ea-8ce9-431a9339f3f3.jpg)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

```
Brave:    1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)
Revision: 99b6d241cf84f7fa7434ae8a59f9e74eb1464280-refs/branch-heads/3945@{#888}
OS:       Windows 8.1 (Build 9600.19573)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Not tested`
- Can you reproduce this issue with the dev channel? `Not tested`
- Can you reproduce this issue with the nightly channel? `Not tested`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

This should be added to #353 .

**Comment by bsclifton** [comment]
Thanks for the report, @zmni 😄 This is a dupe of https://github.com/brave/brave-browser/issues/4509 which I just added! It could also be solved with https://github.com/brave/brave-browser/issues/2999

**Comment by zmni** [comment]
![brave](https://user-images.githubusercontent.com/841523/70774023-a00c5f80-1dab-11ea-9d57-d74374ebc1a3.jpg)

Oh my, sorry, I've read that issue, but completely missed that line. Thank you for planning it. :+1:
