### ISSUE TITLE
Embedded Twitter Videos Not Playing When Shields are Up

### ISSUE THREAD

**Issue by EyanGoldman** [brave/brave-browser#7351]
Embedded twitter videos are blocked from playing when Shields are up.
Shields Up (before play is clicked):
![Screenshot_20190605-100845.png](https://images.zenhubusercontent.com/5cf5a25c96db72707b4b2784/6bb00faa-9d35-44b6-a87e-3132c3b32fe0)

Shields Up (after play is clicked):
![Screenshot_20190605-095457.png](https://images.zenhubusercontent.com/5cf5a25c96db72707b4b2784/51ae3c74-7502-4792-9581-c869b0f8bdaa)

Error Reads: The person who set up this computer has chosen to block this site

## Steps to reproduce 

   1. Go to: https://www.nytimes.com/2019/06/05/world/europe/piers-morgan-donald-trump-interview.html (although works on any site with embedded twitter video)
   2. Play Video

**Comment by ryanbr** [comment]
Hey @EyanGoldman just tested this in the latest Brave for Android (1.6.0) with default shield settings, seems to be okay now, the embedded twitter and also the playback was working. Possible to re-test?

**Comment by EyanGoldman** [comment]
@ryanbr unfortunately don't have an Android device to test on anymore! Sorry I can't be more helpful. 
cc: @anthonypkeane

**Comment by anthonypkeane** [comment]
Tested on 1.6.1 and it works fine
