### ISSUE TITLE
[Android] add Brave section to Settings panel, and rearrange various existing settings

### ISSUE THREAD

**Issue by bradleyrichter** [brave/brave-browser#7352]
Because Brave adds a lot of specific and important functionality over the Chrome base set, we need to pull the Brave shields and regroup them into Brave specific sections.

(then rename to match desktop and iOS in a second task)

![image](https://cloud.githubusercontent.com/assets/13509546/21035429/de6da6da-bd73-11e6-8252-9f21ce5c5520.png)

Future sync items are shown but those will be defined separately.

**Comment by DragoCubed** [comment]
should this be closed?

**Comment by anthonypkeane** [comment]
closing as the new settings page will resolves this
