### ISSUE TITLE
[Android] Option to disable top site tiles on new tab page

### ISSUE THREAD

**Issue by eljuno** [brave/brave-browser#7358]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
From community https://community.brave.com/t/recent-sites-on-homepage/23048?u=eljuno
User request for option to disable the top site tiles on new tab page

**Any related issues:**
Also logged for desktop version brave/browser-laptop#6042

**Comment by srirambv** [comment]
This can be done by disabling Top Sites widget
