### ISSUE TITLE
[Android] Replace desktop icon with Mobile icon for devices list

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7359]
## Test plan
See https://github.com/brave/brave-core/pull/25464

## Description
Remove desktop icon with Mobile icon for devices list

## Device Details
   - Install Type(ARM, x86): All
   - Device(Phone, Tablet, Phablet): All
   - Android Version: All

## Actual Behavior
![image](https://user-images.githubusercontent.com/17010094/47301841-e9b94a00-d5ed-11e8-8f4d-5b3d651ecf2c.png)

**Comment by AlexeyBarabash** [comment]
Yes, can reproduce, thanks for finding this @srirambv .

**Comment by bsclifton** [comment]
Updated assignment - @bradleyrichter @aguscruiz, this could be a good one 😄 

Would be a nice touch to have a mobile icon for Android and iOS

**Comment by aguscruiz** [comment]
In Nala icons we have: 

`smartphone`
![image](https://github.com/user-attachments/assets/f908aa65-4da9-49e7-8ef3-0b5e67aab91f)


`laptop`
![image](https://github.com/user-attachments/assets/e50d9d33-1e64-4769-ae66-708607d14166)



`monitor`
![image](https://github.com/user-attachments/assets/2e49ed2c-c506-417e-9a2e-38a0e7df0feb)



We can use those

**Comment by deeppandya** [comment]
@aguscruiz we have 3 types for device. phone, tablet, desktop/laptop
for phone, i am using `smartphone`
for tablet, i am using `tablet`
for dektop/laptop, i am using `monitor`
Please let me know if i should change anything

**Comment by aguscruiz** [comment]
Ah ok, phone and tablet great, for desktop/laptop, I'd use `laptop` instead.

**Comment by deeppandya** [comment]
> Ah ok, phone and tablet great, for desktop/laptop, I'd use `laptop` instead.

@aguscruiz  Addressing the change here : https://github.com/brave/brave-browser/issues/40936
