### ISSUE TITLE
Hide QR code control for 'Add a Computer device' option

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7361]
**Did you search for similar issues before submitting this one?**

**Description:**
Hide QR code control for 'Add a Computer device' option

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): iPhone8
   - Android Version: 5.1.0
    
**Brave Version:**
Sync Build

**Steps to reproduce:**
    1. Start new sync chain (Android to iOS)
    2. Select "Add a Computer"
    3. Observe that QR code control is displayed for "Add a Computer" option

**Actual Behavior**
QR code control should be removed for "Add a Computer" option

![screenshot_2018-10-22-23-27-03](https://user-images.githubusercontent.com/38657976/47315520-756cbe00-d662-11e8-9d7c-9ee18603cc19.png)

**Expected Behavior**
Behavior should be same on both Android and iOS

![img-20181022-wa0004](https://user-images.githubusercontent.com/38657976/47315629-c8467580-d662-11e8-9b49-adda721a72e1.jpg)

**Comment by jsecretan** [comment]
Going to prioritize this low, because we may some day decide to keep this and make it actually work.

**Comment by anthonypkeane** [comment]
Sync v2 solves this
