### ISSUE TITLE
Brave Ads while offline/poor connection

### ISSUE THREAD

**Issue by RossClelland** [brave/brave-browser#7364]
## Description
On occasion I have recieved a brave ad notification when my 3g/4g connection was very poor (0 bars) which means I'm unable to visit the offer page.  

## Steps to reproduce 

   1. Whenever an ad is shown while signal is very poor for a long period of time
   2. 
   3. 

## Actual result 
Unable to view offer website when clicking on ad notification 

## Expected result
Should be able to view website 

## Issue reproduces how often
The situations I'm referring to are not ones in which I have a good connection and then suddenly lose connection after an ad is displayed. Nor am i referring situations were signal is intermittent.

The situations are where I'm in a low connection area for a longish period of time (5-10 mins) where my phone shows a 4g connection but in reality I'm not able to download/upload. I've confirmed this by checking that, while my phone (s10) says 4g, my VPN is only downloading a minuscule amount of data.

When I get ads are shown in these circumstances and I click on them, I'm unable to reach the website which is a very poor experience. The website doesn't even try to load, it goes straight to the "no connection" page 

## Issue happens on 
   Latest builds

## Device details
   - Install type (ARM, x86): unknown 
   - Device (Phone, Tablet, Phablet): phone, s10
   - Android version: latest
   
## Brave version

Latest on the play store

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? N/a

### Additional information

No

**Comment by anthonypkeane** [comment]
@tmancey is there an API we can use to check the cell signal strength?

**Comment by tmancey** [comment]
@anthonypkeane Unfortunately not, without using private APIs and then our app would be rejected. We can detect the type of connection though, such as Edge, 3G, WiFi etc.

**Comment by tmancey** [comment]
Closing issue as won't fix due to "If we go down this route the ad may have been displayed while a good connection was detected, and clicking the ad would have the same issue if the connection dropped"
