### ISSUE TITLE
1st part ads show up as webview crash 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7370]
## Description 
1st part ads show up as webview crash 

## Steps to Reproduce 

   1. Visit https://amazon.in
   2. Search for any product and scroll down. I used this [link](https://www.amazon.in/JOPASU-Jopasu-Car-Duster/dp/B00RJQ8XHU/ref=sr_1_4?ie=UTF8&qid=1547479227&sr=8-4&keywords=car+cleaner)
   3. You'll see a webview crash where a 1st party Amazon ad is shown on the page

## Actual result: 
![image](https://user-images.githubusercontent.com/17010094/51121507-a1e93e00-183d-11e9-9118-58f8c5485177.png)

## Expected result:
Should show the first party ad 

## Issue happens on: 
   - Current Playstore version? Yes
   - Beta build?

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: Android 9
   
## Brave version:
Play store build

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
Not seeing it here, can you re-test from a different location (using a vpn?)

**Comment by srirambv** [comment]
Seems to be fixed. The issue was migrated from Android repo. Thanks for the double check @ryanbr . Closing the issue for now can reopen if it happens again.
