### ISSUE TITLE
Page scroll doesn't load articles

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7371]
## Description 
Reported via community. https://community.brave.com/t/instapundit-blog-on-mobile-cant-see-older-posts-by-scrolling-with-mobile-experience/43479
Page scroll doesn't load articles

## Steps to Reproduce 

   1. Visit instapundit.com
   2. Scroll down, wait for the page to dynamically load once
   3. Scroll down further, keep waiting as dynamic page load fails

## Actual result: 
Page scroll doesn't load articles

## Expected result:
Page should load as long as the scroll ends

## Issue reproduces how often: 
Easy

## Issue happens on: 
   - Current Playstore version?
Yes
   - Beta build?

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet):
   - Android Version:8.0
   
## Brave version:
1.0.72

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/5a155c02d641cae05b41bb40fa22ffb11fb68478

Should fix this.

**Comment by ryanbr** [comment]
Was resolved in December, just confirmed the fix is working. Closing ticket
