### ISSUE TITLE
New feature. Change width in distilled page

### ISSUE THREAD

**Issue by SubinDenis** [brave/brave-browser#7373]
Hello! Your distilled page content is amazing feature! But column with content is too narrow for me. What if user will able to change standard column width in settings? (Sorry! I don't know where I should write my idea) =)

**Comment by rebron** [comment]
Hi @SubinDenis Thanks for the suggestion. Best way to provide more feedback and develop ideas more is at community.brave.com. I'm going to close this one out in github and hope to see you over there in our community site.
