### ISSUE TITLE
BAT for auto contribute, but no BAT for tip

### ISSUE THREAD

**Issue by SephReed** [brave/brave-browser#7374]
I have BAT
<img width="459" alt="Screen Shot 2019-12-13 at 8 04 00 AM" src="https://user-images.githubusercontent.com/14002040/70805713-3e360080-1d7f-11ea-9c94-c7d7fbddc413.png">

I do not have BAT
<img width="418" alt="Screen Shot 2019-12-13 at 8 04 16 AM" src="https://user-images.githubusercontent.com/14002040/70805714-3e360080-1d7f-11ea-9981-e4939731555f.png">

How do I tip the BAT I have?

**Comment by SephReed** [comment]
Maybe the word "pending" needs to be added somewhere?  I'm unable to figure out what's going on here.

**Comment by NejcZdovc** [comment]
@SephReed sorry, I don't follow. In top section is says that you have 0 BAT (this is your balance)

![image](https://user-images.githubusercontent.com/9574457/70810505-30569e80-1dc4-11ea-95b5-73472644da06.png)

**Comment by SephReed** [comment]
What about the earnings from ads?  Where does that go?

**Comment by NejcZdovc** [comment]
@SephReed is this still a problem?

**Comment by SephReed** [comment]
I still don't know how I have 0 BAT if my earnings is 47 and my auto-contribute is 12

**Comment by Miyayes** [comment]
@SephReed If you disconnect from Uphold (remove the "verified") does a BAT balance show up?
