### ISSUE TITLE
[Feature request] Full screen mode without going fullscreen

### ISSUE THREAD

**Issue by pstorozenko** [brave/brave-browser#7375]
## Description 

Hi, I think that it would be very useful to add a full-screen functionality without going full screen i.e. full-screen mode with hidden tabs and address bar but without changing the size of the window.
This issue is somehow related to #373 (feature request: tab tiling)

Maybe that feature is easier to implement then 373 tab tilling and gives similar capabilities just with multiple windows opened.

## Brave version (brave://version info)

Brave | 1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)
-- | --
Revision | 99b6d241cf84f7fa7434ae8a59f9e74eb1464280-refs/branch-heads/3945@{#888}
OS | Linux
JavaScript | V8 7.9.317.29
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.74 Safari/537.36

**Comment by rebron** [comment]
Wontfix. We're not planning on implementing this feature. Possible we may get a fix upstream.
