### ISSUE TITLE
Source Map doesn't have syntax highlighting

### ISSUE THREAD

**Issue by TheCodersPlayground** [brave/brave-browser#7380]
## Description 
 Source map doesn't have proper syntax highlighting.

## Steps to Reproduce
   1. Open DevTools and go to source tab (on a site with sourcemap).
   2. Open a js file.
   3. Expect to see syntax highlighting.
   4. Try to place a break point and when it stops execution at that point, none of the variables in scope can be inspected on hover.

## Actual result:
Brave
![image](https://user-images.githubusercontent.com/33334137/70831371-6560f200-1dc0-11ea-80fe-9b049e4b3abb.png)

## Expected result:
Chrome
![image](https://user-images.githubusercontent.com/33334137/70831380-6d209680-1dc0-11ea-85e9-544093f4c0f3.png)

## Reproduces how often: 
Happens all the time across all websites.

## Brave version (brave://version info)
Brave	1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)
Revision	99b6d241cf84f7fa7434ae8a59f9e74eb1464280-refs/branch-heads/3945@{#888}
OS	Windows 10 OS Version 1803 (Build 17134.1130)
JavaScript	V8 7.9.317.29
Flash	(Disabled)
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.74 Safari/537.36

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by bsclifton** [comment]
Thanks for the report, @TheCodersPlayground! 

We recently did a fix for this in 1.3 and higher (just merged to 1.2 also, which will ship ~Jan 6 and is our Beta channel at the moment). 

Basically, in a build that has it- you can go to brave://settings/privacy and enable `Remote Debugging`. Once enabled, it should work great! 😄 

Fixed with https://github.com/brave/brave-core/pull/4044

**Comment by TheCodersPlayground** [comment]
![image](https://user-images.githubusercontent.com/33334137/71673256-54175f80-2d46-11ea-80ff-96cd1dff495e.png)

Couldn't find the option to enable `Remote Debugging` - Brave version 1.1.23

**Comment by bsclifton** [comment]
@TheCodersPlayground it's only in 1.2 and above; we're expecting to ship 1.2 next week

If you wanted to try it a little early, you can download the Beta version of Brave here:
https://brave.com/download-beta/
