### ISSUE TITLE
Experimental 3box feature should be disabled

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#7381]
At this time you should not be able to toggle on this feature:

Test Plan:
1. Go to Settings > Advanced
2. At the bottom of the options under `Auto-Logout Timer (minutes)`, there should be no option to enable 3box

Current behavior:
<img width="683" alt="Screen Shot 2019-12-13 at 2 20 42 PM" src="https://user-images.githubusercontent.com/8732757/70833025-f7163280-1db3-11ea-96bd-1a055c1b441c.png">

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.1 x64` using https://github.com/brave/ethereum-remote-client/releases/tag/0.1.32 with the following:

Brave | 1.1.22 Chromium: 79.0.3945.79 (Official Build) (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | macOS Version 10.15.1 (Build 19B88)

<img width="1073" alt="Screen Shot 2019-12-18 at 12 17 59 AM" src="https://user-images.githubusercontent.com/2602313/71057831-f838be00-212b-11ea-8aa6-8e89b663a56f.png">
