### ISSUE TITLE
Crash the Nightly version

### ISSUE THREAD

**Issue by Geradot** [brave/brave-browser#7382]
## Description 
There are open tabs. I launch a new one (its contents do not matter), make several transitions there and the browser closes. Reopen Brave. And if I don’t have time to close the problem tab before loading it, the browser will close again.

## Steps to Reproduce

   1. Open a new tab with any site.
   2. Do something on it.
   3. After few actions Brave Nightly closes.

## Brave version (brave://version info)

1.4.21 Chromium: 79.0.3945.74 (Official Build), nightly (64-bit)

## Version/Channel Information:

I reproduce this issue with the stable release, but it works well.

## Other Additional Information:

The Brave Shields don't affect on the problem.
I have to keep one tab for the browser to work, which is obviously very inconvenient (at least I didn’t notice that the browser closes with one tab).

**Comment by srirambv** [comment]
What platform are you running?

**Comment by Geradot** [comment]
> What platform are you running?

Windows 10

**Comment by Geradot** [comment]
If anything, the latest update did not help.

**Comment by NejcZdovc** [comment]
@Geradot do you have rewards and ads enabled?

**Comment by NejcZdovc** [comment]
could be related to https://github.com/brave/brave-browser/issues/7363

**Comment by Geradot** [comment]
> @Geradot do you have rewards and ads enabled?

Yes, I have

**Comment by bsclifton** [comment]
Hi folks - can you please visit brave://crashes and then look for the Crash ID (not the local context)? Sharing that could be very useful for debugging 😄 

If there's a `Send now` button, please click that. You may need to quick/relaunch browser for crash reports to be sent

**Comment by Geradot** [comment]
> Hi folks - can you please visit brave://crashes and then look for the Crash ID (not the local context)? Sharing that could be very useful for debugging 😄
> 
> If there's a `Send now` button, please click that. You may need to quick/relaunch browser for crash reports to be sent

c262619c-08bd-41c3-92d5-f01cb1f41676

**Comment by NejcZdovc** [comment]
@Geradot thank you for the ID, yup this is dupe of #7363

**Comment by bsclifton** [comment]
Per https://github.com/brave/brave-browser/issues/7363, there is a fix for this and it's coming soon to Nightly 😄 Subscribe to https://github.com/brave/brave-browser/issues/7363 for more info
