### ISSUE TITLE
Download full sources without npm

### ISSUE THREAD

**Issue by figue** [brave/brave-browser#7385]
## Description 
I'm maintaining brave package for Archlinux distribution and recently I discussed the possibility to use the Opensuse build service to build brave, as proposed by the old maintainer maximbaz. But this service can't download anything in the build time because it's a network isolated virtual instance. My question is if there is a way to download all needed sources without having to use "npm run init" or "npm run sync".

Maybe provide an source tarball that already contains everything needed to build the app could be a great idea and it is important for reproducible builds effort.

Thank you

**Comment by rebron** [comment]
cc: @fmarier Can you take a quick look?

**Comment by fmarier** [comment]
We'd have to change our build system for this. I suspect it's not something we'll have the resources to do in the near future, but we should keep that use case in mind next time we make changes there because it's quite common for build infrastructure to be disconnected from the Internet (Debian's is the same).

**Comment by figue** [comment]
Thank you anyway. Instead I don't know if we could simplify the download, for example pulling chromium from the tarball, for instance:

https://commondatastorage.googleapis.com/chromium-browser-official/chromium-80.0.3987.106.tar.xz

Then apply brave patches etc... So with a few sources will be possible to have full sources.

**Comment by bsclifton** [comment]
I don't think this would be feasible, as we are reaching out to the Chromium git repo and cloning the entire thing (including all history) during `npm run init`

You can however tar up this directory and run `npm run sync -- --all` occasionally (and then re-tar). That would be a good solution to stay up to date and have a semi-disconnected environment
