### ISSUE TITLE
The buttons should be customizable

### ISSUE THREAD

**Issue by mohistmen** [brave/brave-browser#7386]
Well, what I want to do is just hide the "Bookmark this tab" button between the "Home" button and the address bar. Actually I almost don't use bookmark functions. I just need the "Home" button besides the address bar, without any buttons between them. Thanks

**Comment by bsclifton** [comment]
Thanks for the suggestion, @mohistmen! I'm going to close this issue as a duplicate of https://github.com/brave/brave-browser/issues/774 and give that issue a bump on your behalf 😄
