### ISSUE TITLE
Brave Shield block Google Account login to Agar.io 😕

### ISSUE THREAD

**Issue by TheAresjej** [brave/brave-browser#7388]
## Description 
Maybe it's just "https://imasdk.googleapis.com/js/sdkloader/ima3.js" ?🤨 

## Steps to Reproduce

   1. Go to https://agar.io
   2. Login with Google Account

## Actual result:
You cannot login with security enabled.

## Expected result:
Protection allows you to sign in with a Google Account but blocks other tracking scripts.

## Reproduces how often: 
**100%**

## Brave version (brave://version info)
Version 1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)
(**Currently the latest stable version**.)

## Version/Channel Information:
- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel? -
- Can you reproduce this issue with the dev channel? -
- Can you reproduce this issue with the nightly channel? -

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? YES
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? NO

## Miscellaneous Information:
Use only Cross-site trackers blocked &  Cross-site cookies blocker.

**Comment by srirambv** [comment]
This is probably as third party cookie being blocked. Does allow all cookie work?

**Comment by TheAresjej** [comment]
Okay, I can connect, but it's lagging... 😕 @srirambv

**Comment by TheAresjej** [comment]
Nope. Brave blocks Google's authorizations by default. So after one death, you can't connect anymore.
