### ISSUE TITLE
"Recently Closed" taskbar menu is not deleted when all history is cleared

### ISSUE THREAD

**Issue by rmangino** [brave/brave-browser#7389]
## Description 

Right-clicking on Brave's Taskbar icon displays "recently closed" tabs that should have been deleted. [screenshot](https://imgur.com/qE1fR8i)

## Steps to Reproduce
   1. Launch Brave
   2. Open several tabs
   3. Go to: chrome://settings/clearBrowserData
   4. Select every option in Basic, Advanced, and On exit
   5. Set Time range to "All time" for Basic, Advanced, and On exit
   6. Click the "Clear data" button
   7. Exit Brave
   8. Launch Brave
   9. Right-click on Brave's Taskbar icon

## Actual result:
The "Recently closed" section still displays tabs that should have deleted.

## Expected result:
The "Recently closed" section should show nothing

## Reproduces how often: 
Always

## Brave version (brave://version info)
```
Brave | 1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Windows 10 OS Version 1903 (Build 18362.535)
```

## Version/Channel Information:
Untested

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Untested
- Can you reproduce this issue with the dev channel?
Untested
- Can you reproduce this issue with the nightly channel?
Untested

**Comment by bsclifton** [comment]
Unable to reproduce

@rmangino do you know if this is still occurring? Do you have more than one instance of Brave installed?

I cleared on Windows 10 using `All time`:
<img width="338" alt="Screen Shot 2019-12-31 at 12 21 25 PM" src="https://user-images.githubusercontent.com/4733304/71631867-75524180-2bc8-11ea-99df-0d484587e6ef.png">

And can confirm it did clear entries, as expected. I also confirmed there WERE `Recently closed` items before clearing
<img width="301" alt="Screen Shot 2019-12-31 at 12 22 48 PM" src="https://user-images.githubusercontent.com/4733304/71631885-9024b600-2bc8-11ea-870b-7d405a67f5af.png">

**Comment by rmangino** [comment]
@bsclifton This might be user error. Somehow I had "Continue where you left off" selected under Settings->"Get Started":

<img width="1186" alt="Screen Shot 2020-01-01 at 9 01 28 AM" src="https://user-images.githubusercontent.com/82423/71642183-81480d00-2c75-11ea-93d4-83105e386dc1.png">

This setting seems to override anything I do with "clear browsing data". That may be by design.

Choosing Settings->"Get started"->"On startup"->"Open the New Tab page" does what I want.
