### ISSUE TITLE
Window manager shows Chrome icon for items handled with Brave

### ISSUE THREAD

**Issue by Allespro** [brave/brave-browser#7392]
1. I download PDF file
   2. I see google-chrome icon
   3. I use Brave (?)
   4. I create issue because I want no google on my PC

![image](https://user-images.githubusercontent.com/4733304/71194685-a25a3800-2249-11ea-9970-eaa310b919c4.png)

## Brave version

Brave | 1.3.65 Chromium: 79.0.3945.79 (Official Build) unknown (64-bit)
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}

## System

OS | Arch Linux
Kernel | 5.4.3-arch1-1
Desktop | KDE 5.17.4, Qt 5.13.2

Please, remove google from brave

**Comment by thijstriemstra** [comment]
😆  I'm sure Google's really happy that developers of this project distribute their software including their trademark.

@Allespro if you don't want Google, don't use Brave. Ever.

**Comment by Allespro** [comment]
Yeah, but that is Google chrome browser [icon](https://user-images.githubusercontent.com/39953296/70942173-200e2000-205f-11ea-9df2-f593e88e05e2.png) and that is Brave browser [icon](https://user-images.githubusercontent.com/39953296/70942108-fe149d80-205e-11ea-8e29-1bcf6fa0ff02.png)

And I think that Brave and Google-chrome is not same.
Browser icon in notifiaction must be from browser which I use, not from another.

**Comment by bsclifton** [comment]
@Allespro it seems the screenshot you've shared features your window manager showing a `.ODT` file as having a Chrome icon for the handler. Can you confirm you do not have Chrome installed?

I'm not familiar offhand how handlers are configured under KDE... but there may be a `Default Programs` type of app you can launch. If you go in there, I'm curious what does it say ODT is handled by?

**Comment by Allespro** [comment]
@bsclifton, hello, I just installed Arch, there is only Konqeror and Brave. I will try that with another file types and write answer.

**Comment by bsclifton** [comment]
@Allespro great, thanks! 😄 

Given that, it does sound like we "missed a spot" and may have Chrome resources somewhere (ex: icon used when showing what handles those files)

**Comment by bsclifton** [comment]
Updated issue title and put screenshot inline (to make it easier to see) 😄

**Comment by Allespro** [comment]
Hello again.
Here is proof that I have no chrome:
![image](https://user-images.githubusercontent.com/39953296/71204723-de28e800-22b1-11ea-8352-8288a987f5bb.png)

Here is what about `.apk`:
![image](https://user-images.githubusercontent.com/39953296/71204975-7cb54900-22b2-11ea-9df0-d87835e47038.png)

I can show many such pictures with different extensions, but I think that this is not necessary.

P.s. I try to find chrome logo at sources, but nothing. I can`t solve that problem too.

**Comment by Allespro** [comment]
Bruh...
I solve, that was beacouse Plasma Integration applet, which was immediately in the browser, think that Brave is Chrome 🤖.

**Comment by bsclifton** [comment]
Awesome, thanks for the follow up, @Allespro! 😄 I'll go ahead and close this

Is there a project page for the applet (so we can open a bug there)? I'm happy to help provide info
