### ISSUE TITLE
Emoji not displaying correctly

### ISSUE THREAD

**Issue by Mitsunee** [brave/brave-browser#7397]
# EDIT:
See comments for where this issue is still surfacing. It's definitely not limited to just me.

## Description 
Emoji do not appear anymore at all, a blank rectangle is displayed instead.

## Work-around
See https://github.com/brave/brave-browser/issues/7397#issuecomment-572756439

## Steps to Reproduce
Open any website with emoji such as Twitter. Emoji can also be copypasted from Emojipedia. I had one in a bookmark which is also not displaying correctly anymore.

## Actual result:
![image](https://user-images.githubusercontent.com/19474909/70865982-0e941d80-1f64-11ea-93c3-4adb5255cccb.png)

## Expected result:
orange heart emoji

## Reproduces how often: 
always

## Brave version (brave://version info)
```
Brave	1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)
Revision	29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS	Linux
JavaScript	V8 7.9.317.31
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36
Command Line	/opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,LookalikeUrlNavigationSuggestionsUI,WebXR,WebXrGamepadModule,UnifiedConsent,AllowPopupsDuringPageUnload,SyncUSSBookmarks --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service
Executable Path	/opt/brave.com/brave/brave
Profile Path	/home/mitsunee/.config/BraveSoftware/Brave-Browser/Default
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? I do not have Chrome, the issue does not appear in Discord (Client) if that helps.

## Miscellaneous Information:
I don't know if graphics drivers are related to fonts in any way but I recently updated to nvidia driver 430, tho I have noticed a broken emoji in bookmarks about 2 brave updates prior.

**Comment by srirambv** [comment]
You need to install fonts that support special characters like emoji. The browser will pick up the system font to show it. You might want to install `fonts-symbola` for your distro using the package manager or use [Ubuntu package](https://packages.ubuntu.com/search?keywords=fonts-symbola). This should support most if not all types of font emoji.

**Comment by bsclifton** [comment]
Going to close this out - but @Mitsunee please let us know if @srirambv 's suggestion fixes the issue 😄 If not, we can re-open and investigate more

**Comment by Mitsunee** [comment]
This issue is not caused by a specific font-family. Emojis stopped working with a recent update in Brave only. Other software can display emoji just fine, even bash and gedit can.
![image](https://user-images.githubusercontent.com/19474909/71035325-7fca0100-211b-11ea-93cc-003b9d88f4b1.png)
The same emoji pasted into brave does not display anywhere, I tried this very input field I'm typing into right now, the devtools and bookmarks.

**Comment by bsclifton** [comment]
It's re-opened (and you have ability to reopen)

**Comment by Mitsunee** [comment]
for future reference, I upgraded to Kubuntu19.10:
```
Brave	1.1.22 Chromium: 79.0.3945.79 (Official Build) (64-bit)
Revision	29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS	Linux
JavaScript	V8 7.9.317.31
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36
Command Line	/opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,SyncUSSBookmarks,AllowPopupsDuringPageUnload,WebXR,AudioServiceOutOfProcess,SmsReceiver,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,WebXrGamepadModule,UnifiedConsent --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service
Executable Path	/opt/brave.com/brave/brave
Profile Path	/home/mitsunee/.config/BraveSoftware/Brave-Browser/Default
```
Issue still unchanged, no emoji display in any textboxes, bookmarks or anything while they do display in most other software (spotify doesn't, but that's the smallest issue that software has on linux...)

**Comment by aparedero** [comment]
+1 in Brave Browser 1.1.23 and Ubuntu 19.04

Previous versions of Brave Browser had emojis working, since last two updates (updates 1.1.x) stopped working.

![emojis](https://i.imgur.com/ACrpHI1.png)

**Comment by gondyb** [comment]
+1 on Ubuntu 19.10 and Brave 1.1.23

![Capture](https://user-images.githubusercontent.com/35400568/71489686-15097b80-2827-11ea-9e19-5fe3ae04d212.png)

Whereas in Firefox:

![Capture d’écran de 2019-12-26 21-30-49](https://user-images.githubusercontent.com/35400568/71489702-2e122c80-2827-11ea-8b7a-39b5e62b4646.png)

**Comment by chrsengel** [comment]
I had the same issue with the latest release (on Ubuntu 19.10) and fixed it by removing and reinstalling `fonts-noto-color-emoji`. Might help you guys.

**Comment by aparedero** [comment]
I realised this problem also occurs on Google Chrome, so is something realted to Chromium. 

The solution from @chrsengel seems to work. I tried `sudo apt-get reinstall fonts-noto-color-emoji` , I closed all Brave / Google Chrome Windows and now is working in both browsers

**Comment by bsclifton** [comment]
@Mitsunee can you try the above suggestion please?

**Comment by Mitsunee** [comment]
I already put a like reaction to show that I tried it and it worked. As I don't know *how* it worked I didn't leave a comment.

**Comment by Mitsunee** [comment]
update: I keep having to repeat the workaround after every new update and/or reboot, which is especially annoying because I have to reboot a lot due to a problem with the nvidia drivers...

**Comment by charbelnicolas** [comment]
Anyone know why Brave tabs display some emojis as outlines? I downloaded the Noto Color Emoji font and almost everything works correctly but the tabs still show some outline icons. Is this a brave bug or how does one fix it?

Please check the attached image:

![2021-05-22-223408_359x799_scrot](https://user-images.githubusercontent.com/14960414/119247351-4c7c7480-bb4e-11eb-8e64-4021bb5ff6f1.png)

**Comment by Mitsunee** [comment]
I'll reopen the issue then

**Comment by markatcristorey** [comment]
Having the issue here in Windows. Happens on Chrome, Edge, and Brave so it's a Chromium issue it would seem. Been having this happen in some sites and not others. In Trello is where I noticed it specifically. Looks like there's something to do with font-weight being applied. At a font-weight of 500 or lower everything is fine. At 600 or higher, the outlines show instead of the font itself.

![image](https://user-images.githubusercontent.com/9884522/145618230-11b06287-53b1-483c-8a97-1979e76f3913.png)
![image](https://user-images.githubusercontent.com/9884522/145618257-5a7ffb8d-db55-4901-9f21-795aafc0de7f.png)

**Comment by Mitsunee** [comment]
closing this again as there's not been any activity and I stopped using this software. If anyone here still has emoji issues I'd recommend opening a new Issue for that specific case. 

I'd like to note that it seems a good portion of the emoji-related issues are coming from chromium and aren't specific to Brave (I lost my bookmark emojis during the transition to a different browser), so possibly try recreating the problem in Chromium and reporting it there instead.

**Comment by tsarquis88** [comment]
I solved this on AlmaLinux 9.3 by installing `google-noto-emoji-color-fonts` and `google-noto-emoji-fonts` through `dnf`.

**Comment by waldyrious** [comment]
> closing this again as there's not been any activity and I stopped using this software. If anyone here still has emoji issues I'd recommend opening a new Issue for that specific case.

This sounds odd to me. The whole reason for using a public issue tracker (instead of private reports via email or whatnot) is to allow all users to collaborate on resolving issues. I don't see an issue as relating solely (or primarily) to the OP's particular situation.

That said, I no longer experience the issue I reported [above](https://github.com/brave/brave-browser/issues/7397#issuecomment-938499363) so I'm not commenting to suggest that this issue be reopened (though if others are still experiencing the problem, then that would be my stance). I'm just sharing my view about issue management, since that may be relevant to similar situations in the future.

**Comment by Mitsunee** [comment]
> This sounds odd to me. The whole reason for using a public issue tracker (instead of private reports via email or whatnot) is to allow all users to collaborate on resolving issues. I don't see an issue as relating solely (or primarily) to the OP's particular situation.

My issue was solved prior to me switching browsers. I had closed the issue at the time. Please cease commenting on a closed issue from 2019 that has been solved and closed multiple times as this causes email spam for everyone on this ticket for no good reason.

As I've said above I do no longer use or support any software made by this company and do not wish to host a discussion on an issue that was solved previously and appears in software that I do not use nor wish to reinstall ever again.

If any maintainer reads this please lock this thread and consider setting up automation for locking issues that have been closed as completed for a significant amount of time.

**Comment by enessmr** [comment]
Happens on me too. I have DejaVu fonts and Noto.

**Comment by BonifacioCalindoro** [comment]
Happens to me on windows, latest brave version. Also happens to a coworker using windows + brave
