### ISSUE TITLE
'Delete' button doesn't appear on brave://history when using the search bar at the top

### ISSUE THREAD

**Issue by onmyouji** [brave/brave-browser#7398]
## Description 

Normally when you check the box next to an item on brave://history, the 'Delete' button will appear at the top right.

![Image 001](https://user-images.githubusercontent.com/8424198/70869936-75dfbb00-1fc0-11ea-92b3-078ed8557c04.png)

But when you search something specific using the search bar, the 'Delete' button doesn't appear when you check the box. I initially thought that I have to delete the checked items one by one. But turns out I can still delete multiple items by using 'Delete' key on my keyboard. Still this is not really good in terms of UI and can be confusing for users.

![Image 002](https://user-images.githubusercontent.com/8424198/70870002-028a7900-1fc1-11ea-835a-772fdb6d62bd.png)

For comparison, on Chrome the 'Delete' button still appears when you use the search bar.

![Image 003](https://user-images.githubusercontent.com/8424198/70870168-86913080-1fc2-11ea-94d8-0dd610a4984a.png)

## Steps to Reproduce

   1. Open History (Ctrl+H) or type brave://history
   2. Click the Search button at top right, then type your search query. It will display the search results.
   3. Check the box next to an item. The 'Delete' button doesn't appear.

## Actual result:
The 'Delete' button doesn't appear.

## Expected result:
The 'Delete' button should appear.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave: 1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)
Revision: 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS: Windows 10 OS Version 1809 (Build 17763.864)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Haven't tested
- Can you reproduce this issue with the dev channel?
Haven't tested
- Can you reproduce this issue with the nightly channel?
Haven't tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by bsclifton** [comment]
cc: @petemill

**Comment by colinhemphill** [comment]
Just encountered this one and had to go to inspect mode to access the `Cancel` and `Delete` options for my selections. Looks like the `cr-toolbar-selection-overlay` should take index priority over the `cr-toolbar #main-toolbar`.

**Comment by bsclifton** [comment]
I believe this is happening because the `br_toolbar` Polymer component is on top of the `Cancel` and `Delete` buttons (and the UI showing how many items matched search)

**Comment by eljuno** [comment]
+1s from Community

https://community.brave.com/t/brave-history-search-option-covers-the-delete-button/114008?u=eljuno

https://community.brave.com/t/cant-delete-selected-item-browsing-history-while-searching/116928?u=eljuno

https://community.brave.com/t/delete-bulk-history/131142?u=eljuno

**Comment by mhidro** [comment]
Sup. Is this being worked on?

**Comment by nickspaargaren** [comment]
I'm getting tired changing the z-index on `<cr-toolbar-selection-overlay/>` every time I need to clear parts of my history :)

**Comment by KarlisZ** [comment]
It is now may 2021. This can't be that difficult. please.

**Comment by stephendonner** [comment]
Verified `FIXED` using 


Brave | 1.28.31 Chromium: 91.0.4472.124 (Official Build) nightly (x86_64)
-- | --
Revision | 7345a6d1bfcaff81162a957e9b7d52649fe2ac38-refs/branch-heads/4472_114@{#6}
OS | macOS Version 11.4 (Build 20F71)

Steps:
1. clean profile
2. launched Brave
3. loaded `search.brave.com` and searched for `dog`
4. clicked `History` -> `Show Full History` (`brave://history/`)
5. clicked on the magnifying glass icon
6. typed `dog`
7. clicked on the `[ ]` checkbox to the left of the search result
8. in the pop-up UI at the top, clicked on `Delete`
9. confirmed I got a prompt to remove selected items
10. clicked on `Remove` and confirmed history result was deleted
11.  also clicked on `Cancel` and the `X` icon while on step 8, and confirmed I was returned to the history-search view, with term in-place

example | example | example | example
---------|----------|---------|----------
<img width="1016" alt="Screen Shot 2021-06-25 at 9 43 25 AM" src="https://user-images.githubusercontent.com/387249/123459799-9caa8480-d59b-11eb-834f-1e9b215abc25.png"> | <img width="1016" alt="Screen Shot 2021-06-25 at 9 43 34 AM" src="https://user-images.githubusercontent.com/387249/123459801-9ddbb180-d59b-11eb-8d89-dac6be56db66.png"> | <img width="1016" alt="Screen Shot 2021-06-25 at 9 54 57 AM" src="https://user-images.githubusercontent.com/387249/123459807-9f0cde80-d59b-11eb-957b-d459860da0b5.png"> | <img width="1016" alt="Screen Shot 2021-06-25 at 9 55 29 AM" src="https://user-images.githubusercontent.com/387249/123459811-9fa57500-d59b-11eb-80ea-5567ca1b048d.png">

**Comment by mhidro** [comment]
When can we expect this in stable?

**Comment by stephendonner** [comment]
> When can we expect this in stable? Also on Windows.

Per https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule, August 10th.

**Comment by levicki** [comment]
@rebron Sorry for slight offtopic, is there a way to bulk delete site history which doesn't involve doing that by searching for site name, pressing Ctrl+A, clicking Delete, clicking Remove, waiting for 150 entries to be delete, and for next 150 entries to be shown?

Is this the best we can do in 2024?
