### ISSUE TITLE
Private windows with Tor does not work

### ISSUE THREAD

**Issue by williamgh2019** [brave/brave-browser#7399]
## Description 

Even search by duckduckgo does not load and access.
If compare to Tor Browser in the same laptop it work good but Brave Private Windows dose not work

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Please add device details and version details. Issue is too generic without any info. Will have to close the issue as insufficient info. Please edit the issue and add details to the template and reopen the issue.
