### ISSUE TITLE
Seconds missing in new tab stats

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#74]
![image](https://user-images.githubusercontent.com/17010094/36081644-9a50be40-0fc7-11e8-8e8e-4b34c803a4a4.png)

**Comment by GeetaSarvadnya** [comment]
Verified on:


Brave | 0.54.2 Chromium: 69.0.3497.42 (Official Build) dev (64-bit)
-- | --
Revision | 9c4613c66dfeb2b76ef6dd4b15884c15db3b4969-refs/branch-heads/3497@{#655}
OS | Windows
JavaScript | V8 6.9.427.14
Flash | 30.0.0.154
