### ISSUE TITLE
Add default top tiles to new tab page similar to browser-laptop

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#740]
## Description 

Change default top tile from showing Chrome webstore

## Steps to Reproduce

   1. Launch browser and open a new tab
   2. Single top tile icon shown which links to Chrome Webstore 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/43991575-fa97b6d8-9d3d-11e8-8ef4-059bea6c28b6.png)
![image](https://user-images.githubusercontent.com/17010094/43991586-1fe555ee-9d3e-11e8-807c-c732dc4c7ba2.png)

## Expected result:
Should be similar to b-l and have custom top tiles at startup

## Additional Information
cc: @simonhong @bbondy

**Comment by rebron** [comment]
cc: @bradleyrichter 

New Tab Page defaults in muon:
1) twitter.com/brave
2) facebook.com/BraveSoftware
3) youtube.com/bravesfotware
4) brave.com
5) https://itunes.apple.com/app/brave-web-browser/id1052879175?mt=8
6) https://play.google.com/store/apps/details?id=com.brave.browser&hl=en_US

**Comment by srirambv** [comment]
Do we still want to keep the top tiles feature? We should probably look into other options like speedial or some other customisation on new tab.

**Comment by rebron** [comment]
@srirambv we'll likely do something different in this space. For the time being, I want to add (muon) default tiles for now and get rid of the CWS tile as the only item that shows up on first run.

**Comment by cezaraugusto** [comment]
un-assigning myself and assigning @imptrx since it's related to the new NTP bundle. 

cc @rebron please coordinate as needed

**Comment by bsclifton** [comment]
Closing as stale. Let's re-open if we have specific requirements that we'd like to implement
