### ISSUE TITLE
remove muon / Brave (old) from importer

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7403]
## Description 
Per internal discussions, we decided to remove muon from the list of browsers to import from. It has been over a year since we did the migration from muon. Additionally, it is confusing to some users as they think they can import from other channels.

## Steps to Reproduce

   1. Launch Brave
   2. Go to brave://settings
   3. Pick importer
   4. Also can check from other places where import can be done (brave://welcome, etc)

## Actual result:
Brave (old) is in the list to import from.
<img width="555" alt="Screen Shot 2019-12-16 at 11 27 41 AM" src="https://user-images.githubusercontent.com/28145373/70924228-2cf72900-1ff7-11ea-967b-5eaede320462.png">

## Expected result:
Brave (old) should not be in the list.

## Reproduces how often: 

easily

## Brave version (brave://version info)

all

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
at least one internal suggestion for this occurred here, but there were other discussions as well. 
https://bravesoftware.slack.com/archives/C20HMJ62H/p1575914247322000
cc @bsclifton @rebron @brave/legacy_qa

**Comment by iefremov** [comment]
Thanks for filing this @LaurenWags !

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.8.71 Chromium: 81.0.4044.92 (Official Build) dev (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan/STR from description
* Using 1.7.x, confirmed that with Brave muon installed/a muon profile present, you see `Brave (old)` in the importer drop down.
<img width="572" alt="Screen Shot 2020-04-10 at 2 31 10 PM" src="https://user-images.githubusercontent.com/28145373/79014005-fad67d80-7b37-11ea-82db-4eb5ff66c709.png">
<img width="643" alt="Screen Shot 2020-04-10 at 2 31 50 PM" src="https://user-images.githubusercontent.com/28145373/79014035-088c0300-7b38-11ea-8876-9ebf4156814b.png">

* Confirmed on 1.8.x with Brave muon installed, you do not see `Brave (old)` in the importer drop down.
* Confirmed on the following screens:
   * brave://welcome
   * Navigating to brave://settings/importData directly in URL bar
   * Navigating to brave://settings and then clicking on "Import bookmarks and settings" option, which opens brave://settings/importData
   * Navigating to hamburger menu > Bookmarks > Import Bookmarks and Settings, which opens brave://settings/importData
   * (macOS only) From macOS file menu opening Brave > Import Bookmarks and Settings..., which opens brave://settings/importData

<img width="1192" alt="Screen Shot 2020-04-10 at 2 26 46 PM" src="https://user-images.githubusercontent.com/28145373/79013941-d4184700-7b37-11ea-9516-547a059ecf70.png">
<img width="1195" alt="Screen Shot 2020-04-10 at 2 27 08 PM" src="https://user-images.githubusercontent.com/28145373/79013945-d67aa100-7b37-11ea-8c3d-d503154c74a3.png">

* Confirmed other import options still displayed and functioned as expected. (Safari, Firefox, Chrome, Bookmarks HTML file)
