### ISSUE TITLE
remove ability to import "Cookies" when importing into Brave from IE

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#7405]
## Description 

We need to remove the ability to import `Cookies` from IE when importing data into Brave. This is a follow up to https://github.com/brave/brave-browser/issues/7044 which removed `Cookies` import from both Firefox and Chrome.

## Steps to Reproduce

**`Test Case #1`**

   1. visit `brave://welcome`
   2. go into the `Import bookmarks and settings` section of the onboarding experience
   3. ensure that cookies are not being imported when selecting `Microsoft Internet Explorer`

**`Test Case #2`**

   1. visit `brave://settings/importData`
   2. ensure that `Cookies` isn't being listed under `Select items to import:`

## Actual result:

![cookiesIE](https://user-images.githubusercontent.com/2602313/70930958-65513400-2004-11ea-90dc-7a9a367c8eed.PNG)

## Expected result:

`Cookies` should be removed from the list of available options for IE.

## Reproduces how often: 

100% reproducible when using the STR mentioned above.

## Brave version (brave://version info)

Brave | 1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)
--- | ---
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Windows 10 OS Version 1909 (Build 18363.535)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @bsclifton @rebron @brave/legacy_qa

**Comment by kjozwiak** [comment]
Waiting on a decision re: if we need to include this in the HF. We'll move this out into `1.2.x` if we only need to worry about Firefox and Chrome for this particular HF/release.

**Comment by bsclifton** [comment]
We don't import cookies anymore for any browser
