### ISSUE TITLE
 Update onboarding with ads regions

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#7407]
## Description 

This ticket is to update onboarding changes with core changes related to ads region. It will make desktop app and android in sync for ads regions.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Expected result:
Desktop app and android app should be in sync for ads regions.

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by tmancey** [comment]
@deeppandya I believe this has been resolved? if so, could you, please close the ticket

**Comment by deeppandya** [comment]
@tmancey it's been resolved. closing this.

**Comment by tmancey** [comment]
Work completed in 1.6.1 of `browser-android-tabs`
