### ISSUE TITLE
Some translated strings have `amp;` added. Wrong translation parsing?

### ISSUE THREAD

**Issue by iccub** [brave/brave-browser#741]
## Description 

Some strings on toolbar have `amp;` string appended which is not correct for Polish language. I have not checked other locales.

## Steps to Reproduce

   1. Set your os locale to Polish
   2. Launch the app

## Actual result:

See the highlighted toolbar item.
<img width="723" alt="zrzut ekranu 2018-08-11 o 18 33 14" src="https://user-images.githubusercontent.com/6950387/43993964-5b1e99b6-9d95-11e8-89c2-15ec67478054.png">

## Expected result:
Strings without `amp;`

## Reproduces how often: 

Easy

## Brave version (about:brave info) 

0.53.3

### Reproducible on current release:

No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by jsparknz** [comment]
This appears to also be an issue with en_AU. Please see attached screenshot.

![screenshot from 2018-08-23 18-58-14](https://user-images.githubusercontent.com/13808826/44512466-c3bb1a80-a70e-11e8-9591-4ec0072fa270.png)

**Comment by bbondy** [comment]
I know what this is from, I'll work on a fix after being on Chromium 70

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/45889230-ea13ba80-bd8d-11e8-9eeb-481f24059b07.png)
