### ISSUE TITLE
Sync crashes browser with "std::__1::basic_string, std::__1::allocator >::assign(char const*, unsigned long)" after re-creation of sync chain

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#7412]
## Description 

Re-creating a sync chain causes a browser crash.

## Steps to Reproduce

1. Create a sync chain
2. Delete the chain
3. Try re-creating it

## Actual result:

Browser crash

## Expected result:
It should not crash

## Reproduces how often: 

Always

## Version/Channel Information:

- Can you reproduce this issue with the current release? **no**
- Can you reproduce this issue with the beta channel? **no**
- Can you reproduce this issue with the dev channel? **no**
- Can you reproduce this issue with the nightly channel? **yes**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **n/a**
- Does the issue resolve itself when disabling Brave Rewards? **n/a**
- Is the issue reproducible on the latest version of Chrome? **n/a**

**Comment by kjozwiak** [comment]
Added some crash reports that will hopefully narrow down the issue:

** Release

 * https://stats.brave.com/dashboard#crash/5df1a8d631d93a001fe1a8fc - `std::__1::basic_string, std::__1::allocator >::assign(char const*, unsigned long)`
 * https://stats.brave.com/dashboard#crash/5df3ec6658e5df001f57e34d - `std::__1::basic_string, std::__1::allocator >::assign(char const*, unsigned long)`

 * Nightly

* https://stats.brave.com/dashboard#crash/5df79f3de1515d001f17b6aa - 	`std::__1::basic_string, std::__1::allocator >::assign(char const*, unsigned long)`
* https://stats.brave.com/dashboard#crash/5df79f7fe1515d001f17b842 - 	`std::__1::basic_string, std::__1::allocator >::assign(char const*, unsigned long)`

**Comment by AlexeyBarabash** [comment]
The crash is related to patch https://github.com/brave/brave-core/blob/master/patches/components-sync_device_info-device_info_sync_bridge.cc.patch .

Reverting this patch avoids the crash, but then it is impossible to recreate the chain and the browser hangs on quit.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.3.117 Chromium: 80.0.3987.106 (Official Build) (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | macOS Version 10.14.6 (Build 18G3020)

* After enabling the sync flag, verified the STR from the description
* After enabling the sync flag, verified the test plan from https://github.com/brave/brave-core/pull/4281
* Confirmed no crashes observed when re-creating sync chains
* Confirmed able to sync as expected (added bookmarks, folders, moved bookmarks, deleted bookmarks, etc) on re-created sync chain when second device was added
* Encountered and logged https://github.com/brave/brave-browser/issues/8314 while testing - sometimes an empty sync chain (no devices) is created.
