### ISSUE TITLE
Unable to send test Eth via facucet.metamask.io

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7415]
## Description 

Unable to send test Eth via facucet.metamask.io

## Steps to Reproduce

   1. Load component `0.1.32`
   2. Switch to Ropsten network
   3. Try sending Eth via faucet.metamask.io

## Actual result:

![Ropsten Test Eth](https://user-images.githubusercontent.com/17010094/70948177-e1f60980-2028-11ea-875e-c020ee68bb40.png)

## Expected result:
Should be able to sent test Eth. Works fine with faucet.ropsten.be

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Component `0.1.32`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/ethereum-remote-client/pull/100

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.4.55 Chromium: 79.0.3945.117 (Official Build) dev (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Linux
Component | `0.1.35`

- Verified sending test ether from https://faucet.metamask.io/ works 
- Verified sending test ether from https://faucet.ropsten.be/ works

---------

Verification passed on 

Brave | 1.4.55 Chromium: 79.0.3945.117 (Official Build) dev (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Windows 10 OS Version 1803 (Build 17134.523)
Component | `0.1.35`

- Verified sending test ether from https://faucet.metamask.io/ works 
- Verified sending test ether from https://faucet.ropsten.be/ works
