### ISSUE TITLE
Selecting BAT automatically selects ETH

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7418]
## Description 

Selecting BAT automatically selects ETH

## Steps to Reproduce

   1. Install component `0.1.32`
   2. Create a new profile
   3. Select BAT from token list automatically selects ETH as well
   4. Selecting ETH doesn't highlight the entry

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/70949539-099aa100-202c-11ea-9e5a-095d5dd31c9c.png)

## Expected result:
Should highlight the correct token 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Component `0.1.32`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by kjozwiak** [comment]
You'll also run into this issue when creating a new wallet. Both `ETH` & `BAT` are selected right away without any interaction when initially creating a new wallet.

Also happens when restoring a wallet using either a CW or MM seed.

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/ethereum-remote-client/pull/100

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.4.55 Chromium: 79.0.3945.117 (Official Build) dev (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Linux
Component | `0.1.35`

- Verified selecting BAT only selects it 
![image](https://user-images.githubusercontent.com/17010094/72085663-b25aba00-32d3-11ea-80d8-32574a960cac.png)
- Verified selecting ETH only selects it
![image](https://user-images.githubusercontent.com/17010094/72085700-c43c5d00-32d3-11ea-9c4c-56346bb49862.png)

-------

Verification passed on 

Brave | 1.3.87 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}

- Verified selecting BAT only selects it 
![image](https://user-images.githubusercontent.com/17010094/72085825-fb127300-32d3-11ea-981c-ea589805e7ba.png)
- Verified selecting ETH only selects it
![image](https://user-images.githubusercontent.com/17010094/72085836-01085400-32d4-11ea-8d89-7dc704944b75.png)

-------
