### ISSUE TITLE
(Crypto Wallet) Create account UI issue

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7419]
## Description 

Create account UI issue

## Steps to Reproduce

   1. Install component `0.1.32`
   2. Create an account and login
   3. Select account and select `Create` tab, UI is squished together

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/70950907-eb36a480-202f-11ea-903f-5dd87fad02db.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/70951022-3f418900-2030-11ea-9a77-e89c0bdb5040.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Component `0.1.32`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by ryanml** [comment]
Closed via: https://github.com/brave/ethereum-remote-client/pull/97

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.4.55 Chromium: 79.0.3945.117 (Official Build) dev (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Linux
Component | `0.1.35`

- Verified new account can be created without having to enter password

-------

Verification passed on 

Brave | 1.3.87 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Windows 10 OS Version 1803 (Build 17134.523)
Component | `0.1.35`

- Verified new account can be created without having to enter password
-------
