### ISSUE TITLE
Possible issue with Google login on Zillow.com

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#7420]
## Description 
Potentially related to https://github.com/brave/brave-browser/issues/3534

## Steps to Reproduce

   1. Visit https://www.zillow.com/homedetails/5203-W-Megan-St-Chandler-AZ-85226/8262555_zpid/
   2. Notice content shows really quickly, then disappears
   3. Put shields down
   4. It works now

## Reproduces how often: 
100%

## Brave version (brave://version info)
Brave | 1.4.25 Chromium: 79.0.3945.79 (Official Build) nightly (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}

## Version/Channel Information:
*Appears to only happen in 1.3 and above*

- Can you reproduce this issue with the current release? N
- Can you reproduce this issue with the beta channel? N
- Can you reproduce this issue with the dev channel? Y
- Can you reproduce this issue with the nightly channel? Y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Y
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? N

**Comment by rebron** [comment]
@bsclifton Still an issue with 1.4.x?

**Comment by bsclifton** [comment]
@rebron works great now! 😄 Closing
