### ISSUE TITLE
5% fee not always sent

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7425]
## Description 
If you tip several sites in quick succession, before the 5% is deducted for each one, the 5% will not be sent. 5% is only sent for the last site tipped.

## Steps to Reproduce

   1. Clean profile on staging - I launched with `--rewards=staging=true --brave-ads-staging --enable-logging=stderr --vmodule=*rewards*=6 --log-level=2`
   2. Enable Rewards (don't claim grant)
   3. Connect your verified, KYC'd, staging account. Be sure you have enough BAT to tip several publishers.
   4. Tip a verified, KYC'd publisher once (I used 3zsistemi.si)
   5. Navigate to Uphold and confirm on your Uphold Activity account page that both the tip and 5% fee were sent (see `A` in screenshot).
   6. Open 3-4 verified, KYC'd publisher sites in tabs. (I uses laurenwags.github.io, vimeo.com/bravelaurenwags, twitter.com/bravelaurenwags, github.com/laurenwags).
   7. Tip one, move quickly to the next, tip again, repeat until you've tipped all 3-4 publishers from step 6. 
   8. Go to Uphold, open the Activity page for your Brave Browser card and confirm that all tips (not the 5%) were made.
   9. Wait a few minutes. Only the 5% for the last tip sent will be posted to this page. Even if you wait more time, the additional 5% fees are not sent.

## Actual result:

<img width="1272" alt="Screen Shot 2019-12-17 at 9 48 23 AM" src="https://user-images.githubusercontent.com/28145373/71006285-1b735700-20b3-11ea-86ea-90ce656bd29b.png">

## Expected result:
5% fees to be sent even when tipping in rapid succession

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 1.1.22 Chromium: 79.0.3945.79 (Official Build) (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
Reproduced several times
cc @NejcZdovc @brave/legacy_qa

**Comment by kjozwiak** [comment]
@NejcZdovc @rebron any updates on this one? It's labelled as a `P1` and was moved into the ` 1.2.x` milestone. We'll probably want to get this fixed before the Jan 6th release.

**Comment by rebron** [comment]
Removed from 1.2.x milestone. Need to investigate this one a bit more.

**Comment by masparrow** [comment]
Verified the behaviour on Mac OSX - sending 4 tips in quick succession, only one 5% BAT contribution was made. I took records of the Uphold activity over the space of an hour;

<img width="1309" alt="Screenshot 2020-01-13 at 15 04 44" src="https://user-images.githubusercontent.com/11368284/72266450-469b8880-3616-11ea-8da5-cd3562659e11.png">

Now investigating the cause.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.5.106 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified STR from description
<img width="1171" alt="Screen Shot 2020-03-03 at 11 54 17 AM" src="https://user-images.githubusercontent.com/28145373/75799290-eab3cd00-5d45-11ea-9825-3b0ba262cfc3.png">
