### ISSUE TITLE
make sure real time phishing protection option is always disabled

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#7429]
## Description 

Chrome is rolling out a real time phishing protection option, which is off by default. It sends URLs visited to Google, so we should disable it for now. https://security.googleblog.com/2019/12/better-password-protections-in-chrome.html?m=1

## Expected result:

The "Send URLs of the pages you visit to Google" checkbox seen in https://twitter.com/campuscodi/status/1206759987118247936/photo/1
should not exist in Brave, and the underlying setting should be off.

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
cc: @mkarolin @jumde
