### ISSUE TITLE
Shields button always shows the counts of active tab of active windows

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#743]
## Description 

Shield text always shows the count of active tab of active window

## Steps to Reproduce

   1.  Create new window with new tab
   2.  Create new window with www.github.com
   3.  

## Actual result:

All shield button shows the count of active window's

## Expected result:
Shield button in each window should show the count of it's active tab

## Reproduces how often: 

Easily reproduced

## Brave version (about:brave info) 

Master

### Reproducible on current release:

No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7
