### ISSUE TITLE
Ads history: arrow colors

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#7437]
In the ad history, user preference selections ---

Up arrow should be green
Down arrow should be red

See image for issue ----

![image](https://user-images.githubusercontent.com/35932307/71031840-0c979f00-20c9-11ea-886e-2a3543f25e63.png)

@jenn-rhim @NejcZdovc

**Comment by NejcZdovc** [comment]
so down should stay as is, but up should be green?

**Comment by darrylbutcher** [comment]
created PR to change color [here](https://github.com/brave/brave-core/pull/4267) if someone could have a look at it please

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.5.102 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified with clean profile:
<img width="939" alt="Screen Shot 2020-02-27 at 11 02 08 AM" src="https://user-images.githubusercontent.com/28145373/75461363-b2c91600-5950-11ea-9d71-9909431b2171.png">

* Reproduced with 1.4.95:
<img width="934" alt="Screen Shot 2020-02-27 at 11 02 15 AM" src="https://user-images.githubusercontent.com/28145373/75461391-bc527e00-5950-11ea-8db4-3743ea747908.png">

and verified on upgrade to 1.5.x:
<img width="946" alt="Screen Shot 2020-02-27 at 11 04 00 AM" src="https://user-images.githubusercontent.com/28145373/75461489-df7d2d80-5950-11ea-9b9e-4956df8dace6.png">
