### ISSUE TITLE
Ads on/off toggle for different profiles causes confusion when using profile with Ads off

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7441]
## Description 
Originally reported here: https://www.reddit.com/r/brave_browser/comments/ec0xfh/ads_are_off_still_seeing_brave_ads/

@Miyayes surfaced the above thread. While discussing it and attempting to reproduce, it was determined that if a user has a profile with ads/rewards on and one with ads/rewards off, even if a window is not open for the profile with ads on, ad notifications are still presented to the user. Per internal discussions we probably want to limit this to only show ads when there is a window open for the profile which is ads enabled. cc @jsecretan @rebron @mandar-brave @kjozwiak who were also part of the discussion.

## Steps to Reproduce

   1. Clean profile (Profile A).
   2. Enable Rewards. Now disable Rewards. Leave window for this profile open.
   3. Add another profile (Profile B).
   4. Enable Rewards, set ads to show 5x per hour.
   5. Visit a site like brave.com in Profile B window and then after page loads, close the window for Profile B.
   6. Browse normally on window for Profile A.

## Actual result:
You will be served ad notifications.

## Expected result:
Per discussion, we should respect the profile you are using and not serve ad notifications.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 1.1.22 Chromium: 79.0.3945.79 (Official Build) (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | macOS Version 10.13.6 (Build 17G5019)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? probably
- Can you reproduce this issue with the dev channel? probably
- Can you reproduce this issue with the nightly channel? probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? on all profiles yes.
- Is the issue reproducible on the latest version of Chrome?  n/a

## Miscellaneous Information:
cc @tmancey

**Comment by Brave-Matt** [comment]
Another user reporting similar behavior on Community:
https://community.brave.com/t/having-problem-with-2-profiles-at-the-same-time/100756/3

**Comment by GeetaSarvadnya** [comment]
Currently, ads are not shown in 1.11.x.  QA blocked until PR https://github.com/brave/brave-core/pull/5751 is uplifted

**Comment by GeetaSarvadnya** [comment]
PR #5751 is uplifted to 1.11.x hence removing QA blocked label

**Comment by LaurenWags** [comment]
Verified using

```
Brave | 1.11.90 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Issue as described still reproduces. Logged https://github.com/brave/brave-browser/issues/10588 as a followup.

**Comment by LaurenWags** [comment]
Note, since issue is not resolved, removed the `release-notes/include` tag. Please adjust if necessary @rebron @kjozwiak .
