### ISSUE TITLE
Missing closing brace in CSS for cosmetic `style` rules

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#7442]
The `generateCosmeticBlockingStylesheet` method appears to mistakenly omit a closing brace whenever custom style rules are added to a stylesheet that will be injected into a page.

Existing browser tests perform as expected -- it appears an implicit closing brace is added at the end of the stylesheet. Although custom style rules are uncommon within filter lists; if more than one were added, the stylesheet would become malformed.

The missing closing brace is located [here](https://github.com/brave/brave-core/commit/7512da5fff038e2c2c0f8d9c6b06ba6a1bba24a0#diff-3493bfe26c7890d60718508a5969519aR15). A unit test should be added to ensure `generateCosmeticBlockingStylesheet` builds correctly formatted stylesheets when one or more custom style rules are used.

**Comment by snyderp** [comment]
@antonok-edm can this be closed?
