### ISSUE TITLE
can't accept grants due to "statusCode":400,"error":"Bad Request","message":"Invalid request payload input"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#7443]
## Description 

Looks like `Release` & `Beta` have regressed and users can't accept grants and are getting the `Ooops, something is wrong. Please try again later`. I've reproduced the issue on staging for both `UGP` & `Ad` grants.

@evq took a look at the backend and mentioned the issue is most likely client based. Sounds like the client is passing the wrong format to the backend when attempting to accept grants.

There's also been several reports via the community and internally as well.

## Steps to Reproduce

**`Test Case #1`**

   1. launch `1.1.22 CR: 79.0.3945.7` using `--enable-logging=stderr --rewards=staging=true`
   2. enable `rewards` via the panel or `brave://rewards`
   3. attempt to accept the UGP grant on `staging`

**`Test Case #2`**

   1. launch `1.1.22 CR: 79.0.3945.7` using `--enable-logging=stderr --rewards=staging=true`
   2. enable `rewards` via the panel or `brave://rewards`
   3. restore an internal wallet that has a `ad` grant and attempt to accept it

## Actual result:

<img width="440" alt="Screen Shot 2019-12-17 at 8 31 18 PM" src="https://user-images.githubusercontent.com/2602313/71048436-41c5e080-210d-11ea-8ddc-ffd1d365291f.png">

```
[ RESPONSE - SetGrantCallback ]
> time: 1576631356
> result: Failure
> response: {"statusCode":400,"error":"Bad Request","message":"Invalid request payload input"}
> headers accept-ranges: bytes
> headers cache-control: no-cache
> headers content-length: 82
> headers content-type: application/json; charset=utf-8
> headers date: Wed, 18 Dec 2019 01:09:16 GMT
> headers server: Cowboy
> headers status: 400
> headers via: 1.1 varnish
> headers x-cache: MISS
> headers x-cache-hits: 0
> headers x-served-by: cache-yyz4532-YYZ
[ END RESPONSE ]
```

## Expected result:

Users should be able to accept grants without any issues.

## Reproduces how often: 

100% reproducible when using the above STR.

## Brave version (brave://version info)

* `1.1.22 CR: 79.0.3945.79` (Release) - **Reproduced**
* `1.2.28 CR: 79.0.3945.79` (Beta) - **Reproduced**
* `1.3.67 CR: 79.0.3945.79` (Dev) - **Couldn't reproduce**
* `1.4.25 CR: 79.0.3945.79` (Nightly) - **Couldn't reproduce**

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @NejcZdovc @rebron @bsclifton @LaurenWags @mandar-brave

**Comment by kjozwiak** [comment]
This was fixed via a server side fix as discussed in Slack 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.1 x64` using the following:

* `1.1.22 CR: 79.0.3945.79` (release) - Claimed both a UGP & Ad grant on staging without any issues
* `1.2.28 CR: 79.0.3945.79` (Beta) - Claimed both a UGP & Ad grant on staging without any issues
* `1.3.67 CR: 79.0.3945.79` (Dev) - Claimed both a UGP & Ad grant on staging without any issues
* `1.4.25 CR: 79.0.3945.79` (Nightly) - Claimed both a UGP & Ad grant on staging without any issues

**Comment by doctord919** [comment]
w
