### ISSUE TITLE
"Learn more" under "Congratulations" screen pointing to MM Zenhub

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#7444]
## Description 

Looks like this was originally supposed to be addressed via https://github.com/brave/brave-browser/issues/4772 but it was closed without it ever being resolved. I looked around and couldn't find an issue under :

```is:open label:feature/crypto-wallets https://metamask.zendesk.com/hc/en-us/articles/360015489591-Basic-Safety-Tips```

## Steps to Reproduce

   1. launch brave and open `brave://wallet`
   2. click on `Restore` and restore a wallet (MM or CW)
   3. click on `Learn more.` and you'll be taken to https://metamask.zendesk.com/hc/en-us/articles/360015489591-Basic-Safety-Tips

## Actual result:

Shouldn't be using https://metamask.zendesk.com/hc/en-us/articles/360015489591-Basic-Safety-Tips

## Expected result:

<img width="1030" alt="Screen Shot 2019-12-18 at 12 44 58 AM" src="https://user-images.githubusercontent.com/2602313/71059191-3506b400-2130-11ea-8c61-f48274be2529.png">

Should open a help page that's located on https://support.brave.com and not https://metamask.zendesk.com.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 1.1.22 Chromium: 79.0.3945.79 (Official Build) (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | macOS Version 10.15.1 (Build 19B88)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @ryanml @srirambv

**Comment by srirambv** [comment]
This is a regression of  #6100

**Comment by rebron** [comment]
cc: @Brave-Matt for url for article.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.4.55 Chromium: 79.0.3945.117 (Official Build) dev (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Linux
Component | `0.1.35`

- Verified `Learn More` points to [Brave Support article](https://support.brave.com/hc/en-us/articles/360034535452-How-can-I-add-my-other-Crypto-Wallets-to-Brave-)

---

Verification passed on 

Brave | 1.3.87 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Windows 10 OS Version 1809 (Build 17134.523)
Component | `0.1.35`

- Verified `Learn More` points to [Brave Support article](https://support.brave.com/hc/en-us/articles/360034535452-How-can-I-add-my-other-Crypto-Wallets-to-Brave-)
