### ISSUE TITLE
Add setting in brave://settings/appearance to display full URL in address bar

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#7449]
## Description 

```
#omnibox-ui-hide-steady-state-url-trivial-subdomains
#omnibox-ui-hide-steady-state-url-scheme
```
The above flags, which controlled whether or not the entire URL was displayed in the address bar, have been removed from the Chromium code. _Many_ users have requested these options be returned to the browser. Further, it's also something users would frequently ask how to do even before the flags were removed. I believe there are enough users interested in having this option available to warrant consideration for bringing it back.
![image](https://user-images.githubusercontent.com/3299098/71107967-fea05780-2176-11ea-8dc1-3acf0a838839.png)

## Miscellaneous Information:

**User reports:**

- https://www.reddit.com/r/brave_browser/comments/e6n98g/chromium_removed_flags_related_to_displaying_full/
- https://community.brave.com/t/i-want-to-see-the-full-url-in-the-address-bar-omnibox-options-missing-in-brave-flags/95466
- https://community.brave.com/t/display-full-url/89775/24
- https://www.reddit.com/r/brave_browser/comments/e9e7vv/req_bring_back_the_option_to_show_https_and_www/
- https://www.reddit.com/r/brave_browser/comments/bi6y3c/double_clicking_in_the_in_the_address_bar_shows/
- https://community.brave.com/t/address-bar-with-full-link-instead-of-search-keyword/74117
- https://community.brave.com/t/www-subdomain-permanently-hidden-in-address-bar/97918

**Comment by rebron** [comment]
cc: @tomlowenthal @petemill for thoughts

**Comment by Madis0** [comment]
This option should mainly toggle the [old elisions in Chromium](https://github.com/bromite/bromite/blob/master/build/patches/Disable-omission-of-URL-elements-in-Omnibox.patch) (protocol hiding, trailing slash, username-password, possibly punycode display). 
The subdomain "www" should always be displayed as the contents can and do differ in several sites, including sites that just don't work without www. See also web developers' arguments: https://bugs.chromium.org/p/chromium/issues/detail?id=883038

**Comment by Renerick** [comment]
Temporary workaround for this issue is in the discussion as well: https://bugs.chromium.org/p/chromium/issues/detail?id=883038#c203 (download the file, put it in some directory and install as unpacked extension)

Nevertheless, this behavior is still a problem for many users and I think it should be addressed ASAP

**Comment by bsclifton** [comment]
cc: @diracdeltas

**Comment by Brave-Matt** [comment]
Some more users here requesting this feature:
https://community.brave.com/t/display-full-url/89775/30

**Comment by Madis0** [comment]
The option is now upstream (canary), behind a flag. https://bugs.chromium.org/p/chromium/issues/detail?id=1061576

**Comment by Sa-Ja-Di** [comment]
@Brave-Matt How about following user interests and user suggestions? People want customization, features and choice and not simplicity - old Brave with it's custom UI offered that, Brave now offers almost nothing.

When do you guys bring back finally some features and customization? Where is your support for power and advanced users?

**Comment by Brave-Matt** [comment]
Another +1 from Community:
https://community.brave.com/t/display-full-url/89775/34?u=mattches

**Comment by rebron** [comment]
brave://flags/#omnibox-context-menu-show-full-urls This flag when enabled, starting in Chromium 83 should show an option via context menu to display the full address bar.

**Comment by stefankeys** [comment]
Vivaldi and Opera seem to have implemented this feature.

**Comment by EricReuss** [comment]
I've been looking for this feature not for security reasons but for UX ones - when I go to edit a portion of a URL, it's really frustrating to have the text shift out from under the mouse cursor as I double-click.

I'm glad it's coming down the pipe, though I have to say that "set a special flag to enable a context menu item to provide the desired functionality" sounds like a pain... especially if it only sets it for one window (I can't tell from the comment).

**Comment by Madis0** [comment]
@EricReuss 
> I'm glad it's coming down the pipe, though I have to say that "set a special flag to enable a context menu item to provide the desired functionality" sounds like a pain... especially if it only sets it for one window (I can't tell from the comment).

Chromium flags are for previewing new features that get enabled for all at some point or for experimenting with some UI changes that might get enabled for all. This is the first one, as a direct response to users' request. So this will be enabled for all at some point (M83? M84?), will not stay behind a flag.

If you want to suggest a more visible option in Settings, however, that's a different thing. (As for now this only appears in the context menu.)

**Comment by bsclifton** [comment]
Per https://github.com/brave/brave-browser/issues/9884 - @Poopooracoocoo is asking if this would be available for Android too

**Comment by amiremami** [comment]
Please add this feature in settings, that we can see the complete URL. For now I'm using this plugin:

https://chrome.google.com/webstore/detail/suspicious-site-reporter/jknemblkbdhdcpllfgbfekkdciegfboi/

I hope Brave can add it in the settings that I can remove that extension.

**Comment by diracdeltas** [comment]
i think this would be good to add as a pref ("Show full URLs in URL bar") in brave://settings/appearance. Turning the pref on should both show the URL scheme and "trivial" subdomains like www. 

cc @darkdh

**Comment by amiremami** [comment]
Any update on this?

**Comment by Poopooracoocoo** [comment]
Was this added to the Android version too?

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.13.76 Chromium: 85.0.4183.69 (Official Build) dev (64-bit)
-- | --
Revision | 4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/6116
- Verified that github.com URL is elided when "Always Show Full URLs" option is disabled in `brave://settings/appearance`
![image](https://user-images.githubusercontent.com/38657976/90516074-22da8b00-e181-11ea-9df3-5744b67fb4a6.png)
- Verified that the omnibox shows full URL for github.com when "Always Show Full URLs" option is enabled in `brave://settings/appearance`
![image](https://user-images.githubusercontent.com/38657976/90516256-5ddcbe80-e181-11ea-81c6-369c603e63fe.png)
- Verified that context menu from Omnibox shows the option "Always Show Full URLs" in checked mode
![image](https://user-images.githubusercontent.com/38657976/90516433-98def200-e181-11ea-86ec-bc7ad9aa5ca5.png)

**Comment by dentistformyeye** [comment]
Could this be added to the Android version, too?
