### ISSUE TITLE
Error in RPC when trying to connect Crypto Wallet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7452]
## Description 

Error in RPC when trying to connect Crypto Wallet

## Steps to Reproduce

   1. Create a new account in `0.1.32` component
   2. Open Cryptokitties.co and try to connect
   3. Selecting done shows error in console

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/71110202-d4f62900-2194-11ea-8517-13f9f45f5106.png)

## Expected result:
Should bring the popup to connect the site 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Component `0.1.32`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

## Miscellaneous Information:

Possibly related to #7415 since it keeps asking to unlock even though the account is unlocked

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/ethereum-remote-client/pull/100

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.4.55 Chromium: 79.0.3945.117 (Official Build) dev (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Linux
Component | `0.1.35`

- Verified no errors on console when trying to connect wallet
