### ISSUE TITLE
Webview crash on `dobreprogramy.pl`

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#7453]
Crash reproduced on all channels.

## Steps to Reproduce

Note: The webview crash is not immediate.

   1. Clean install
   2. Open [https://www.dobreprogramy.pl/Jak-obnizyc-temperatury-lub-zwiekszyc-wydajnosc-procesora-Poradnik-do-ThrottleStop,News,91886.html](https://www.dobreprogramy.pl/Jak-obnizyc-temperatury-lub-zwiekszyc-wydajnosc-procesora-Poradnik-do-ThrottleStop,News,91886.html)
   3. Wait 60 seconds
   4. Scroll the page

## Actual result:

Page is frozen, cannot scroll the page
`Page is unresponsive` modal is shown
Page Crashes after pressing `Exit page` on `Page is unresponsive` modal

Uploaded Crash Report ID d0d311d2522656ce (Local Context: 21fc7363-69f9-4164-80cc-d4d82d5818b1)

## Expected result:
No Page freeze
No Crash

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.1.22 Chromium: 79.0.3945.79 (Official Build) (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Windows 7 Service Pack 1 (Build 7601.24530)

Brave | 1.1.22 Chromium: 79.0.3945.79 (Official Build) (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Ubuntu 18.04 LTS

Brave | 1.2.29 Chromium: 79.0.3945.79 (Official Build) beta (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Windows 7 Service Pack 1 (Build 7601.24530)

Brave | 1.3.67 Chromium: 79.0.3945.79 (Official Build) dev (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Windows 7 Service Pack 1 (Build 7601.24530)

Brave | 1.4.25 Chromium: 79.0.3945.79 (Official Build) nightly (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Windows 7 Service Pack 1 (Build 7601.24530)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

cc @rebron @bsclifton @brave/legacy_qa

**Comment by btlechowski** [comment]
Does not reproduce on Chrome

Google Chrome | 79.0.3945.79 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | Windows 7 Service Pack 1 (Build 7601.24530)

**Comment by LaurenWags** [comment]
Reproduced webview crash on macOS:

Brave | 1.2.29 Chromium: 79.0.3945.79 (Official Build) beta (64-bit)
-- | --
Revision | 29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS | macOS Version 10.13.6 (Build 17G5019)

<img width="775" alt="Screen Shot 2019-12-18 at 2 56 26 PM" src="https://user-images.githubusercontent.com/28145373/71118742-aed98480-21a6-11ea-9fce-aca78ed152b9.png">

Noticed on if I visit this page with Chrome I'm being prompted to allow notifications, but Brave doesn't get to that point. Not sure if related?
<img width="986" alt="Screen Shot 2019-12-18 at 2 58 24 PM" src="https://user-images.githubusercontent.com/28145373/71118841-e21c1380-21a6-11ea-995c-66c23a27727c.png">

**Comment by ryanbr** [comment]
This change https://github.com/brave/adblock-lists/commit/80a338c0c4619f3040e2fc1073da419233839a3d would affect this. wp.pl was removed from the disconnect list. Can you re-test @btlechowski ? does it still occur?

**Comment by rebron** [comment]
cc: @btlechowski can you retest?

**Comment by btlechowski** [comment]
No longer reproducible. I will close it and add it to 1.3.x milestone so it can be checked by other QAs

Verification passed on

Brave | 1.3.85 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Ubuntu 18.04 LTS

Verified test plan from the descriptin
