### ISSUE TITLE
Issues with Brave starting

### ISSUE THREAD

**Issue by BennyAK99** [brave/brave-browser#7454]
## Description 

Brave fails to open from Finder and from Launchpad. It was working fine for the past couple of months until today. I've tried to use tricks from other threads to open a browsing window but they have failed. I have redownloaded Brave twice and erased previous copies to no avail. I would have written this in the community website but it would never send an activation email 

## Steps to Reproduce

   1.  Downloaded
   2. Installed
   3. Tried to open

## Actual result:

https://youtu.be/KAbsnOV94LI

## Expected result:
I expected the browser to open

## Reproduces how often: 

Everytime

## Brave version (brave://version info)

Current release for MacOS Catalina, I can't access the version details because I can't open a browser window

## Version/Channel Information:

- Can you reproduce this issue with the current release? I've only tried this release
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? No - I'm currently using Chrome

## Miscellaneous Information:

I've tried to open the Execution file from the Contents/MacOS/ and the terminal opened with these errors:

Last login: Wed Dec 18 14:35:13 on ttys000
/Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser ; exit;
Ben@Benjamins-MacBook-Pro ~ % /Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser ; exit;
[1218/144843.801224:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffee5f23000, 0x2000): (os/kern) invalid address (1)
[1218/144843.916596:WARNING:system_snapshot_mac.cc(42)] sysctlbyname kern.nx: No such file or directory (2)
[1218/144843.929118:WARNING:crash_report_exception_handler.cc(239)] UniversalExceptionRaise: (os/kern) failure (5)
[1655:775:1218/144843.934655:ERROR:child_thread_impl.cc(227)] Invalid PlatformChannel receive right
[1654:775:1218/144843.935394:ERROR:child_thread_impl.cc(227)] Invalid PlatformChannel receive right
[1218/144843.936938:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffeef014000, 0x2000): (os/kern) invalid address (1)
zsh: segmentation fault  /Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser

[Process completed]

**Comment by Brave-Matt** [comment]
@BennyAK99 -- can you try running from the terminal with the `--args --disable-gpu` flag appended at the end of the command?

**Comment by dmirubtsov** [comment]
@BennyAK99 

the same issue for me, it's related to tor mode,

please try to delete tor profile from brave directory

```
rm -rf ~/Library/Application\ Support/BraveSoftware/Brave-Browser/Tor\ Profile
```

**Comment by rebron** [comment]
@BennyAK99 Can you try installing 1.3.x our latest release and let us know if you're still having problems with launching Brave?

**Comment by BennyAK99** [comment]
@rebron  Yes I've downloaded it and tried opening Brave, it still quit unexpectedly

**Comment by BennyAK99** [comment]
@Brave-Matt I tried running the executable with the args this is was the response from terminal:
 Last login: Sun Feb 16 13:22:24 on ttys000
/Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser ; exit;
Ben@Benjamins-MacBook-Pro ~ % /Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser ; exit;
chrome_crashpad_handler: --database is required
Try 'chrome_crashpad_handler --help' for more information.
[0216/132343.183404:ERROR:file_io.cc(89)] ReadExactly: expected 8, observed 0
[0216/132343.184149:ERROR:crash_report_database_mac.mm(96)] mkdir : No such file or directory (2)
zsh: trace trap  /Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser

[Process completed]

**Comment by ffd8** [comment]
Just want to chime in I've also had strange issues with Brave refusing to open (crashing immediately upon opening) in MacOS 10.13.6 and the only thing that solves it is to restart the computer. Maybe a cache/dump building up? A couple weeks ago when it happened I re-downloaded etc to no avail – but the restart solved it. Just ran into same issue now and restart worked. Perhaps something is cleared on restart that needs to be cleared on quit/open?

**Comment by BennyAK99** [comment]
@ffd8 thank you but a restart of my MacBook and a new download of Brave did not work either

**Comment by ffd8** [comment]
@BennyAK99 Sorry to hear – restarting still works for me (had to repeat multiple times the past days each time I quit and wanted to reopen). Would be great to find a fix for this issue..

**Comment by BennyAK99** [comment]
Hi, I just want to check in. Brave is working now. I redownloaded Brave Browser just now and its working, I don't know how but this issue is resolved
