### ISSUE TITLE
"Always request desktop website" feature no longer works on numerous websites.

### ISSUE THREAD

**Issue by kirilloffs** [brave/brave-browser#7468]
## Description 

A lot of sites serve mobile version, while Desktop mode is enabled globally for all sites ( Settings -> Site settings -> Desktop Mode). For sites which load mobile version Desktop mode checkbox is active (three vertical dots in lower right corner -> desktop mode) meaning Desktop veersion should be served, but that`s not happening. 

Affected websites include, but not limited to 4pda.ru ; rbc.ru ; android.stackexchange.com (SE subdomains not the original site)

Hiding Brave to background and reopening works as one-time remedy for the page.
Also switching Desktop mode via page checkbox  (three vertical dots in lower right corner -> desktop mode) off and on makes correct version to be served (desktop version).

## Steps to reproduce 

   1. Enable serve Desktop globally for all sites ( Settings -> Site settings -> Desktop Mode)
   2. Create new empty tab
   3. Type one of the affected websites URL (4pda.ru for example)
   4. Mobile version is served initially

## Actual result 

Before temporal remedy (minimizing\maximizing Brave or reloading Desktop mode)
![before reopening 1](https://user-images.githubusercontent.com/40706324/63649289-53414200-c744-11e9-8007-026ecad5e4c6.jpg)
![before reopening 2](https://user-images.githubusercontent.com/40706324/63649290-53414200-c744-11e9-9fef-6a81aefbfc5f.jpg)

After temporal remedy (minimizing\maximizing Brave or reloading Desktop mode)
![after reopening 1](https://user-images.githubusercontent.com/40706324/63649287-52a8ab80-c744-11e9-9308-e2e9e8c485d0.jpg)
![after reopening 2](https://user-images.githubusercontent.com/40706324/63649288-53414200-c744-11e9-8360-64e61950445a.jpg)

## Expected result

Site should be opened in desktop mode right away without need for additonal actions.

## Issue reproduces how often 

Issue reproduced every time for affected websites

## Issue happens on 
Google Play latest version

## Device details
Testes on two ARM phones:
Android 8.0.0 Lg v30+
Android 9 Oneplus 7 Pro

   
## Brave version
Latest Brave  1.2.0 Chromium 76.0.3809.111 (but the bug has beed around for a while)

### Website problems only
Issue persists with shileds turned off. Chrome lacks always desktop mode feature.

### Additional info:
Related bug:
https://github.com/brave/browser-android-tabs/issues/740
This bug is related, but different in a sense that issue 740 depicts case when sites dont open Desktop version at all and my ticket raises situation when Brave is capable of opening Desktop verson and does so but only after additional external input.

Related ticket:
https://github.com/brave/browser-android-tabs/issues/124

**Comment by kirilloffs** [comment]
> 
> 
> Not sure if this helps, but another thing that makes a new tab display the full desktop version of a page is going to your phones app switcher and then clicking on Brave again. Changing to another app and then returning to Brave also results in the full desktop page being displayed. The user agent always seem to be set on desktop, the problem seems related to the window not being "set" to a desktop resolution width, which somehow gets set when switching back to Brave after doing something else or simply when deactivating/activating desktop mode in the drop-down as detailed above.

Unfortunately is seems that brave team would not fix this anytime soon if ever at all. What did the job for me is switching to Opera as they properly handle desktop mode.

**Comment by Imerion** [comment]
Hi again! Is there anything I can do to help with this issue?

Having to switch in and out of the page for every new tab just to get rid of these terrible mobile pages is getting really annoying - especially since Brave worked so great before this bug appeared. Since it works on the first tab, I guess it must be something about what settings new tabs get. Perhaps they don't get the width they should have? I'm thinking since when I first load a page I get the single column view and then when I switch out of the Brave and back again it seems like the page re-renders or rearranges itself to fit a wider width.

**Comment by kirilloffs** [comment]
BTW: The reason for this bug is simple: sites detect screen resolution and forcefully serve mobile version despite desktop user agent preset active. 

So the fix should be rather simple - while sending desktop user agent screen resolution info should also be changed to correspond to that of a desktop.

**Comment by kirilloffs** [comment]
@deeppandya, seems the reason for this bug is simple: sites detect screen resolution (discover that screen proportion is mobile phone proportion) and forcefully serve mobile version despite desktop user agent preset active.

So the fix should be rather simple - while sending fake desktop user agent, also to send fakescreen resolution info to correspond to that of a desktop screen proportions.

@SergeyZhukovsky @srirambv @LaurenWags may be it worth reopening ticket https://github.com/brave/browser-android-tabs/issues/124 as it in fact #124 no longer passes QA checks 3 and 5 stated in that ?

**Comment by gbiryukov** [comment]
Workaround so far is to reduce font size in your mobile browser settings

**Comment by kirilloffs** [comment]
> 
> 
> Workaround so far is to reduce font size in your mobile browser settings


For me workaround was to switch to Opera. Why bother using browser if developers not in mood to fix it.

**Comment by samartnik** [comment]
This has been fixed in the context of https://github.com/brave/brave-browser/issues/20963
