### ISSUE TITLE
Check if ledger doesn't call `FetchGrants` on V4 endpoints after virtual grants are implemented.

### ISSUE THREAD

**Issue by gdregalo** [brave/brave-browser#7473]
## Description 
There is a small issue when periodically (24h) checking for grants availability on Android browser.  
(in https://github.com/brave/brave-core/blob/master/vendor/bat-native-ledger/src/bat/ledger/internal/ledger_impl.cc#L729)
The `Grants::FetchGrants` requires a `safety_net` token which can be retrieved trough ledger's client (rewards_service).
Otherwise this call is useless.
I'm planning to add a function `GetSafetyNetToken` to `LedgerClient` interface and make it available for Android build only with preprocessor directives.
There was a quick discussion about hiding a device attestation functionality like SafetyNet and DeviceCheck behind one interface but for now I don't think it's possible. 

https://bravesoftware.slack.com/archives/CB0KCRCQN/p1572551230286600

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
not sure if this one is needed as we moved to VG now. And when you fetch promotions with VG no safetynet token is needed
