### ISSUE TITLE
same bug with sync function.. again...

### ISSUE THREAD

**Issue by sviluppoSoftware** [brave/brave-browser#7480]
## Description 
I tried to sync 3 devices: a linux pc a windows pc and brave for android, the bookmarks to sync are around 1800, first step was to synchronize linux with android, I had to run 5 attempts because the android browser didn't load all the bookmarks, sometimes it only loaded around 20 % other times around 60%, randomly in short, didn't respect the order, I also had to force the sync in android by opening and closing the app with the "exit" button several times otherwise it fails to download all the bookmarks at once.
the synchronization with the windows pc was totally unsuccessful: it didn't respect the order of the bookmarks, some folders contained less than half of the bookmarks that should have been there, other folders weren't really downloaded, I also tried to reinstall brave on windows and delete all bookmarks to re-import them using an .html file but it didn't work.
unfortunately the synchronization function is still light years behind firefox sync, these problems I had encountered months ago ..

## Steps to reproduce 

   1. start sync between linux pc and android or linux pc and windows etc..

## Actual result 
 in android and windows fails to download all the bookmarks at once, don't respect the bookmarks order, some folders aren't sync other folders are only partially sync

## Expected result
synchronize your bookmarks in one step without having to close and open the app or program on a PC, respecting the order of the bookmarks

## Issue reproduces how often 
always

## Issue happens on 
   - Current Play Store version?  17.8-16 and earlier
   - Beta build? don't test

## Device details
   - Install type (ARM, x86): arm
   - Device (Phone, Tablet, Phablet): phone
   - Android version: 9 and 8.1 probably either earlier
   
## Brave version
all brave versions since the synchronization function was also introduced in version 1.6

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? no
- Is the issue reproducible on the latest version of Chrome? don't know

**Comment by anthonypkeane** [comment]
@jsecretan more sync info here.
