### ISSUE TITLE
BR Panel should show Rewards settings instead of settings

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7483]
## Description 
BR Panel should show Rewards settings instead of settings

## Actual result: 
![screenshot_20190302-165638](https://user-images.githubusercontent.com/17010094/53688541-8fef2c00-3d13-11e9-8a61-29ce07ca8d76.png)

## Expected result:
should be same as desktop

## Issue reproduces how often: 
Easy

**Comment by anthonypkeane** [comment]
@bradleyrichter for comment? Mobile says Settings, Desktop Rewards Settings

**Comment by Miyayes** [comment]
Superseded with new panel.
