### ISSUE TITLE
[Android] Clear cache, cookies, history automatically/manually with on exit option

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#7487]
## Designs

![Frame 1](https://user-images.githubusercontent.com/2388823/116753019-4403a480-a9bb-11eb-99a1-3d504bcd5029.png)

## Assets

Figma: https://www.figma.com/file/QqaIjdrXobryTT3Zd9wcKM/?node-id=0%3A1

**Comment by marc-gg** [comment]
3 years later, why is this still not a thing?

**Comment by johnlunney** [comment]
Installed Brave to get this feature, discovered it's still not in Android, uninstalled.

**Comment by R4cc** [comment]
Any update on this? Doesn't seem too hard to implement + It has been requested many times more than 3 years ago... Basically the only reason I don't use the android version.

**Comment by jonathansampson** [comment]
Recent +1 from Twitter: https://twitter.com/hoofhearted4/status/1233193606627897344?s=19.

**Comment by Pavbc** [comment]
3 years, is there still hope? Just a option to link the "clear data" button to the *already existing* exit button on android

**Comment by srirambv** [comment]
+1 from @Gor3pig via #9346

**Comment by Pavbc** [comment]
Anything?

**Comment by ArneTR** [comment]
+1 from @ArneTR

**Comment by RobVerduijn** [comment]
+1
please do let me know when this is done, sticking with duckduckgo until then

**Comment by srirambv** [comment]
@anthonypkeane @bsclifton @bbondy we should prioritize this issue and get it in soon.

**Comment by srirambv** [comment]
+1 from @silvershadowcc  via #11479

**Comment by Brave-Matt** [comment]
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/ik3am6/how_can_i_make_the_mobile_browser_clear_all_data/

**Comment by machiav3lli** [comment]
Maybe adding "default to incogneto tabs" option could be a good companion to this feature.

**Comment by DiGiTal1133** [comment]
นี่เป็นช่วงเวลาที่ฉันว่าง:


จ. ก.ย. 28



9:00 am - 9:30 am (GMT+7)




ใช้งานง่ายขึ้นโดย Outlook<https://aka.ms/Dcupce>



ดาวน์โหลด Outlook for iOS<https://aka.ms/o0ukef>
________________________________
จาก: machiav3lli <notifications@github.com>
ส่ง: Monday, September 28, 2020 8:34:21 AM
ถึง: brave/brave-browser <brave-browser@noreply.github.com>
สำเนาถึง: Subscribed <subscribed@noreply.github.com>
ชื่อเรื่อง: Re: [brave/brave-browser] [Android] Clear cache, cookies, history on exit option (#7487)


Maybe adding "default to incogneto tabs" option could be a good companion to this feature.

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/no-auto-clear-data-on-exit-for-brave-mobile-browser/166195

**Comment by aaronsantamaria** [comment]
+1
https://community.brave.com/t/automatically-delete-brave-android-browser-data-on-exit/176259

**Comment by 0ANIMEFREAK0** [comment]
+1 from me

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/auto-delete-history/200048

**Comment by Brave-Matt** [comment]
@anthonypkeane can we get an update on where we are at with this?

**Comment by cbwee** [comment]
I also need an option to clear search and browsing history, while keeping cookies, on exit, like the PC version does.

**Comment by alexsafe** [comment]
@jamesmudgett Do we need any UI specs or mocks for this? Like for Settings?

**Comment by karenkliu** [comment]
Designs added!

**Comment by kjozwiak** [comment]
+1 from https://github.com/brave/brave-browser/issues/492#issuecomment-816749129.

**Comment by AnirudhJambunathan** [comment]
Clearing browser data on exit is a really important feature. Please provide it at the earliest.

**Comment by Brave-Matt** [comment]
+1 community:
https://community.brave.com/t/hard-page-refresh/242472/5

**Comment by WilliamShockleyfake** [comment]
Plz add this. Waiting for ever

**Comment by anthonypkeane** [comment]
It is available on the Beta version now and we should have it on the main app in a few weeks @WilliamShockleyfake

**Comment by WilliamShockleyfake** [comment]
> It is available on the Beta version now and we should have it on the main app in a few weeks @WilliamShockleyfake
> 
> 

Downloading cant fucking wait. Hate YouTube and websites tracking me based on cookies

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.26.53 x64 Beta Build
- Verified enabling `Clear browsing data on exit` removes all data upon exit
- Verified enabling setting doesn't clear any existing tabs
- Verified tab navigation history is cleared on restart when clear data on exit is enabled
- Verified saved passwords are removed on restart when clear data on exit is enabled
- Verified saved card info is removed on restart when clear data on exit is enabled
- Verified saved address info is removed on restart when clear data on exit is enabled
- Verified site specific settings are reset to default on restart when clear data on exit is enabled
- Encountered  #16259 & #16260
----------------
Verification passed on Samsung Tab A with Android 10 running 1.26.53 x64 Beta Build
- Verified enabling `Clear browsing data on exit` removes all data upon exit
- Verified enabling setting doesn't clear any existing tabs
- Verified tab navigation history is cleared on restart when clear data on exit is enabled
- Verified saved passwords are removed on restart when clear data on exit is enabled
- Verified saved card info is removed on restart when clear data on exit is enabled
- Verified saved address info is removed on restart when clear data on exit is enabled
- Verified site specific settings are reset to default on restart when clear data on exit is enabled
- Encountered  #16259 & #16260

**Comment by bridiver** [comment]
@srirambv `Verified site specific settings are reset to default on restart when clear data on exit is enabled` - not sure how that got included in the list of things to check, but it is incorrect. Also it I don't see that clearing of cookies/cache was verified.

**Comment by srirambv** [comment]
@bridiver its mentioned in the test plan to check for site settings to be cleared https://github.com/brave/brave-core/pull/8790. I missed adding the cookie/cache note but I did login to a site and then quit the browser with the setting and upon restart I was logged out. Updated the notes

**Comment by bridiver** [comment]
Yes, I did see afterwards that site settings were listed in the PR. There is a new PR to correct this.

**Comment by newuser-web** [comment]
It cleared all my data of previous sessions.

**Comment by newuser-web** [comment]
All data of the previous session are deleted after enabling it. It should delete the data of the current session only.

**Comment by pyrocto** [comment]
I disagree.  If you want only a single session to be deleted, use a private window.

**Comment by newuser-web** [comment]
But it shouldn't delete the data of previous months or years. I don't want only a single session to be deleted. As long as clear data on exit is enabled( it may be 1 week or 1 month) it should delete the data.
