### ISSUE TITLE
Add the ability for users to give their email address to us so we can keep in touch

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#7489]
## Description 

Users tell us that they would like to keep in touch with Brave and receive the odd email newsletter / update. 

This ticket is to enable a way that users, can if they wish, provide their email.

Exact Spec: TBD

- [ ] Implement design
- [ ] Implement endpoint

Linked to: Linked to: brave/internal#753

## Designs

Show a "Get privacy tips" banner the first time user visits a search results page.

![image](https://user-images.githubusercontent.com/2388823/107405904-acc63980-6abc-11eb-869a-a28b09ba125f.png)

Show banner one time only.

Dark theme is the same as light theme.

## Assets
Figma: https://www.figma.com/file/atoL4LN2kd8ILnPGwohUoV/?node-id=2154%3A26868

**Comment by karenkliu** [comment]
Designs added!

**Comment by deeppandya** [comment]
@anthonypkeane where do send users response ? I think we would need an api similar to rate brave. And we should add an option in the menu if user wants to send email again

**Comment by deeppandya** [comment]
@anthonypkeane where do we stand on this issue ? is it worth exploring ? 
CC @bsclifton
