### ISSUE TITLE
3rd party storage allowed from `a.domain.com` if `b.domain.com` includes an iframe from `a.domain.com` 

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#749]
## Description 
3rd party storage allowed from `a.domain.com` if `b.domain.com` includes an iframe from `a.domain.com`.

## Steps to Reproduce

   1. Open `http://dustiest-limitation.000webhostapp.com/first_party.html`
   2. Navigate to Inspector > Application > Storage

## Actual result:
You can see localStorage/webStorage/IndexDb/WebSQL for peltate-worth.000webhostapp.com.

## Expected result:
Storage attempts from peltate-worth.000webhostapp.com should be blocked

## Reproduces how often: 
100%

## Brave version (about:brave info) 

Brave | 0.53.3 Chromium: 69.0.3497.12 (Official Build) dev (64-bit)

### Reproducible on current release:
Yes

Full discussion here - https://bravesoftware.slack.com/archives/C6YNM6Y5S/p1534202254000056?thread_ts=1533842503.000122&cid=C6YNM6Y5S

**Comment by jumde** [comment]
This works as expected on `browser-laptop`.

**Comment by ltilve** [comment]
The test case at http://dustiest-limitation.000webhostapp.com/first_party.html seems not usable, as the iframe is currently commented out, but I was able to reproduce the issue locally defining `domain.com`, `a.domain.com` and `b.domain.com` virtualhosts.

With the provided patch we are also checking that the cookies can only be accessed all the host string is a subset of the domain one, and not just TLD+1.

**Comment by srirambv** [comment]
The commit https://github.com/brave/brave-core/pull/417/commits/a7f54b35797c886560c139cc96ea5fe875e94517 is breaking major functionalities. Images uploaded on slack isn't shown. 
![image](https://user-images.githubusercontent.com/17010094/45493230-48acb900-b73c-11e8-995c-168b60bf03e4.png)

Shows a broken image. Gmail functionality works but get a warning message
![image](https://user-images.githubusercontent.com/17010094/45493132-14d19380-b73c-11e8-8788-0466886c86f0.png)

**Comment by srirambv** [comment]
cc: @jumde @diracdeltas

**Comment by ltilve** [comment]
It seems that these sites might need accessing cookies sharing more than `TLD+1`.

For the case of `gmail`, not allowing the `a.domain.com` - `b.domain.com` was blocking several as `apis.google.com`, `contacts.google.com`, `hangouts.google.com`, etc, that are apparently necessary.

**Comment by bbondy** [comment]
After talking with @diracdeltas and @jumde, we're going to keep it the way it is for now and close this.
