### ISSUE TITLE
[help]how to build brave apk with widevine support

### ISSUE THREAD

**Issue by cw4219** [brave/brave-browser#7494]
## Description 
Hi there, 
When I visit https://bitmovin.com/demos/drm using Brave apk  downloaded from Google Play, the site tell me that this browser supports widevine drm.
But when I build it myself, it does not support widevine.

I would appreciate it if anyone could tell me how to enable widevine in Brave apk?

**Comment by srirambv** [comment]
Component needs to be signed for it to work.

**Comment by cw4219** [comment]
That's right, thanks.
I enabled "proprietary_codecs" in build/config/features.gni to make it work.
