### ISSUE TITLE
sign in with google fails, even with shields down

### ISSUE THREAD

**Issue by doom777** [brave/brave-browser#7495]
I searched the issue, and it shows up many times, but no resolution

## Description 

When I sign in with google in my website, I get the google sign in popup, but the success callback is blocked

## Steps to Reproduce

   1. Setup a google sign in button following https://developers.google.com/identity/sign-in/web/build-button
   2. Click sign in
   3. Select profile and optionally authenticate
   4. Success callback not called

## Actual result:

Nothing happens

## Expected result:
Success callback called with google user, allowing your js to proceed.

## Reproduces how often: 

Easily reproduced. 

## Brave version (brave://version info)

Brave | 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Windows 10 OS Version 1809 (Build 17763.914)
JavaScript | V8 7.9.317.32

## Version/Channel Information:

Did not try
- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  No, only brave

## Miscellaneous Information:

Many issues are opened on this, but get closed even though the issue is not resolved

**Comment by rebron** [comment]
@doom777 Can you update to 1.3.x? Can you also check if you disabled Google login in the Social Network blocking setting. You can check via brave://settings/socialBlocking 

If this doesn't work, what's the website you're signing into.

**Comment by ryanbr** [comment]
This should be resolved @doom777 can you re-confirm in the latest Brave?
