### ISSUE TITLE
Provide option to connect Crypto Wallet to be connected via private windows only

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7496]
## Description 

Current implementation, Crypto wallet page only opens in normal window(#6706 . Even though the component works on Private tabs by default, when trying to connect to a Dapp it still launches the normal window to connect

## Steps to Reproduce

   1. Enable CW on normal window
   2. Open a private tab and visit cryptokitties.co
   3. Connect wallet on private tab, connect account popup opens in a normal tab

## Actual result:

Provide option to connect Crypto Wallet to be connected via private windows only

## Expected result:
Should open popup window on private tab when the connection was initiated in a private tab

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All component versions

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Related #6637 
When MM is enabled to work on PT, it allows a popup on private tab itself 
![image](https://user-images.githubusercontent.com/17010094/71261288-5ecc0080-2313-11ea-87af-8810ef62d03e.png)

**Comment by bbondy** [comment]
This does not apply anymore since CW is loaded as an extension and not a component. Closing.
