### ISSUE TITLE
Crypto wallet extension button should be shown when enabled 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7497]
## Description 

Crypto wallet extension button should be shown when enabled 

## Steps to Reproduce

   1. Enable CW via settings page
   2. Open a private tab 
   3. No extension button is shown which allows browser action window to show up 

## Actual result:

No extension button with browser action window

## Expected result:
Similar to MM
![image](https://user-images.githubusercontent.com/17010094/71261406-a9e61380-2313-11ea-8ccf-e0138db992e7.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All CW components

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome?  NA

**Comment by woodydeck** [comment]
It's really sad to see Brave do so much good work and to have such a crappy third web experience. The current crypto wallet does not conform to standards for authentication, and does not work very well as simply an authenticator.

Web3 authentication doesn't require a user to have any Ether. It requires a user to prove they control an address with a signature. This is the most powerful feature by far. Forget the write only database of the blockchain.

The current iteration of the crypto wallet hurts Brave's reputation. Throwing invalid address errors is annoying enough, to not have any sort of notification outside the console means I  cannot recommend Brave browser to anyone, and have to note how to work around Brave browser.

**Comment by bsclifton** [comment]
Thanks for the feedback, @woodydeck - the crypto wallet was started as a fork of Metamask. Folks have been (and are actively) working to add features and improve the experience (tie it more closely to Brave)

To make sure we address your feedback, can you create an issue with details about the specific concern? For example, your concern about Web3 auth. This issue in particular (that we're commenting on) is only about the extension button being enabled/disabled in the browser

I'm also curious what you mean about no notification outside the console. What would be the expected behavior you'd like to see? (is there an extension or software which does this right? or maybe you can just describe the expected experience?). It would be good to create another issue for this too. I can help with creating issues (let me know!)

**Comment by woodydeck** [comment]
I just now saw this. Apologies for the long delay. 

MetaMask is an even bigger mess with all the miscommunication between them and the web3 team. I'm very frustrated, but refreshed by your attitude in your reply.

I don't know how best to explain it without showing you what I'm doing, so I will send you an email now. I am not using the Ethereum blockchain for anything but signing and simple Tx is the gist. The macro is that while I am a huge Brave evangelist to friends, I have to now qualify sharing my application with "don't use Brave".  It's too confusing to tell people to disable the native wallet and install MetaMask. Having native wallet capabilities should make it my first choice!

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.12.98 Chromium: 84.0.4147.89 (Official Build) beta (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{# 852}
OS | Linux

- Verified browser action button is shown component is downloaded and enabled
- Verified closing browser and relaunching doesn't retain the browser action button
- Verified setting `Load Crypto Wallets on startup` retains the browser action button between restarts
- Verified closing CW tab doesn't remove the button 
- Verified visiting a Dapp and triggering CW via info bar loads the browser action button
