### ISSUE TITLE
Time saved decrements and then increases after clean install

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#75]
After clean install and launch, all stats were 0. 
Visited slashdot.org and stats showed up. Time saved showed 7 
Visited theverge.com and stats got updated but time saved shows 3
Subsequent visits to page increased the time saved to 4

**Comment by bbondy** [comment]
@srirambv still a problem?

**Comment by srirambv** [comment]
This specific issue doesn't happen but the blocked items is wrong so overall stats doesn't show correctly. Will log a separate issue for incorrect blocked items
