### ISSUE TITLE
Brave Rewards : Copy Change on Settings

### ISSUE THREAD

**Issue by alexwykoff** [brave/brave-browser#7500]
Per feedback : https://twitter.com/gridinoc/status/1207874459547385857

Please change “ads in” to “ad notifications with” on the Rewards Settings page, Ads Settings panel.

**Comment by mandar-brave** [comment]
Making this easier.
Earn tokens by viewing Brave Ads (instead of Earn tokens by viewing Ads in Brave).

cc @jenn-rhim @alexwykoff

**Comment by darrylbutcher** [comment]
created a PR for the fix for English strings in browser and android

**Comment by LaurenWags** [comment]
@mandar-brave per https://github.com/brave/brave-browser/issues/7500#issuecomment-568160182 you have `Ads` capitalized. It is currently not capitalized in 1.5.102. Please confirm if current implementation is ok:

<img width="654" alt="Screen Shot 2020-02-27 at 10 25 17 AM" src="https://user-images.githubusercontent.com/28145373/75458518-ebb2bc00-594b-11ea-9f6f-d48c83df407c.png">


Brave | 1.5.102 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)

**Comment by mandar-brave** [comment]
Brave ads should be Brave Ads .

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.5.102 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)

* Reproduced original text on Ads panel using 1.4.95:
<img width="653" alt="Screen Shot 2020-02-27 at 12 20 13 PM" src="https://user-images.githubusercontent.com/28145373/75487669-d5712400-597c-11ea-8eb4-58797ad01a12.png">

* Verified text is updated in 1.5.x:
<img width="654" alt="ads" src="https://user-images.githubusercontent.com/28145373/75487677-dbff9b80-597c-11ea-94a0-cdb78a9c5d95.png">

* Logged #8449 for incorrect case/capitalization from https://github.com/brave/brave-browser/issues/7500#issuecomment-592049338
