### ISSUE TITLE
Improve compatibility with MetaMask and allow web3 provider selection

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#7503]
# Objective

In Brave, if the user has MetaMask installed, we currently show an infobar on a Dapp page that asks the user to disable one of either Crypto Wallets or MetaMask. 

<img width="626" alt="Screen Shot 2019-12-20 at 12 08 58 PM" src="https://user-images.githubusercontent.com/831718/71272249-8a55e780-2321-11ea-8c7f-036a0ffbebe9.png">

This is over disabling functionality that we don’t need to, when really we should just be asking which web3 provider they want to use for that page. The current implementation also allows for various edge cases where users can be in a stuck broken state when trying to use Dapps.

This is intended to allow Crypto Wallets to remain enabled, and to improve the frustrations that users encounter by having two web3 providers installed.  It also enables us to keep other future functionality enabled as we enhance Crypto Wallets for things like exchange integrations.

# Future enhancements / iterations

Explicitly not part of this spec:

- Supporting web3 providers outside of MetaMask and Crypto Wallets.
- Later work not part of this spec will likely add P3A reporting for which web3 provider is used

# Targeted platforms

- Desktop, mobile doesn’t have Crypto Wallets at all yet.

# Description

The work can be cleanly divided into 4 areas:

1. Settings work: Remove the setting in preferences which disables Crypto Wallets. There will be no need for this setting anymore.  Replace this setting with an option to pick your web3 provider. 
2. Migration work: How the existing user choice works into the new functionality.
3. Infobar work: Repurpose our MetaMask infobar to ask the user which Web3 provider to use.
4. Adding an API to obtain the web3 provider: An API will be made available to both MetaMask and Crypto Wallets to be able to check which web3 provider should be used.

## Settings work

The old settings switch to turn off Crypto Wallets will be removed.  See the next section on Migration work to see how the existing user choice will be handled. 

<img width="626" alt="Screen Shot 2019-12-20 at 12 09 30 PM" src="https://user-images.githubusercontent.com/831718/71272482-9b9ef400-2321-11ea-8472-0e18e5c3cca9.png">

The options for the drop down menu will be: `Ask`, `None`, `Crypto Wallets`, and `MetaMask` if it is installed.  The default will be `Ask` until an explicit option is set.  The new preference will be stored with the pref name of `brave.wallet.web3_provider` in per-profile prefs which are visible in chrome://prefs-internals/.  If the user explicitly uses Brave wallet first and opts in and the setting is set to Brave, then even installing MetaMask later won’t change the setting from Brave.

If `Ask` is selected, UI will be shown as per the section on Infobar work
If `None` is selected, the entire extension will always be lazy loaded, even if it is installed.
If `Crypto Wallets` is selected, only Crypto Wallets will be used as a web3 provider.
If `MetaMask` is selected, only MetaMask will be used as a web3 provider.

## Migration work

Some users in the past had seen the old infobar and selected either to use MetaMask or Crypto Wallets. We have only in the past actively disabled Crypto Wallets, so no one will have MetaMask disabled by us.

A one time migration will be done to determine which value should be used for the new setting `brave.wallet.web3_provider`.  

- If Crypto Wallets was disabled and MetaMask is installed, it will be set to MetaMask.
- If Crypto Wallets is diabled, and MetaMask is not installed, None will be set.
- If Crypto Wallets is enabled, and MetaMask is still installed, it will be set to Brave.
- If CryptoWallets is enabled and it has been installed (i.e. was lazy loaded before), but MetaMask is not installed, Brave will be used.
- If CryptoWallets is enabled and it has not been installed yet (due to lazy loading), and MetaMask is not installed, Ask will be set. 

An automated test will be added for each of these migration cases to ensure they work correctly.

Migration code will be added in `chrome/browser/prefs/browser_prefs.cc` via `MigrateObsoleteBrowserPrefs`.

## Infobar work

If MetaMask is not installed, the existing UX will continue to be valid:

<img width="622" alt="Screen Shot 2019-12-20 at 12 10 17 PM" src="https://user-images.githubusercontent.com/831718/71273130-ca1ccf00-2321-11ea-9654-25356b51e98a.png">

If MetaMask is installed, the existing infobar UX highlighted in the Objective section will be repurposed to the following.

<img width="623" alt="Screen Shot 2019-12-20 at 12 11 17 PM" src="https://user-images.githubusercontent.com/831718/71273554-e6b90700-2321-11ea-91e9-36df3ec459f3.png">

Closing the infobar will use neither provider, it will keep the setting mentioned in the last section to “Ask”.

If the user’s setting is “None”, no infobar will be shown.

Depending on which option is selected, the setting mentioned above will be set to either “Crypto Wallets” or “MetaMask”.  “None” can only be set from the settings page.
Adding an API to obtain the web3 provider
A new API will be exposed to both Crypto Wallets and MetaMask:
`chrome.cryptoWallets.getWeb3Provider((extensionId) => {})`

The other APIs available within `chrome.cryptoWallets` will NOT be accessible to MetaMask.

It will return the `extensionId` for the provider to use or a blank string.
A web3 provider should only inject existing MetaMask code that provides web3 to the page if its extensionId matches the return value from `chrome.cryptoWallets.getWeb3Provider`.

Possible values for the `extensionId` in the above callback will be:
- `nkbihfbeogaeaoehlefnkodbefgpgknn` (metamask)
- `odbfpeeihdkbihmopkbjmoonfanlbfcl` (Brave)
- A blank string which signals that no explicit web3 provider was set, and Brave will show native UI.  Note that a blank string will also be returned if the user explicitly went to settings and selected None.

## QA plan

Test plan being added in wiki here
https://github.com/brave/qa-resources/wiki/%5BWIP%5D-Multiple-Web3-provider-support-test

## Open Questions
None at this time.

**Comment by mikedotexe** [comment]
This is such a well-written issue, holy cow.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

Brave | 1.5.109 Chromium: 80.0.3987.132 (Official Build) beta (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan mentioned in the description

**Clean profile:**
- Verified that the drop-down menu has `Ask`, `None` and `Crypto Wallets` options when MM isn't installed. By default the `Ask` option is selected
![image](https://user-images.githubusercontent.com/38657976/76427407-3fa0b480-63d2-11ea-81e9-a4a6b95d1bb3.png)

**Comment by GeetaSarvadnya** [comment]
@kjozwiak @srirambv I don't see new pref name `brave.wallet.web3_provider` in `chrome://prefs-internals/` - I have verified both clean and upgraded profiles. Please check this from your end, please log if it's an issue. let me know if I am missing anything.
