### ISSUE TITLE
Brave block mod_pagespeed or pagespeed-nginx beacons as intersite trackers.

### ISSUE THREAD

**Issue by eldk** [brave/brave-browser#7504]
## Description 

Brave block mod_pagespeed or nginx_pagespeed beacons as intersite trackers.

## Steps to Reproduce
   1. Go to this page with brave shields enabled : https://www.modpagespeed.com/examples/lazyload_images.html?ModPagespeed=on&ModPagespeedFilters=lazyload_images
   2. Check intersite blocked urls : https://www.modpagespeed.com/mod_pagespeed_beacon?url=https%3A%2F%2Fwww.modpagespeed.com%2Fexamples%2Flazyload_images.html

## Actual result:

https://www.modpagespeed.com/doc/config_filters#beacons - see comment about disabling beacons

## Expected result:

Don't block them.

 (if https://www.modpagespeed.com/doc/filter-lazyload-images#lazyload-blank-url don't use https://www.gstatic.com/psa/static/1.gif ?)

## Reproduces how often: 

Always on Apache/mod_pagespeed or Nginx/pagespeed-nginx servers with one or all of those filters enabled : 
- https://www.modpagespeed.com/doc/filter-lazyload-images
- https://www.modpagespeed.com/doc/filter-inline-preview-images
- https://www.modpagespeed.com/doc/reference-image-optimize#inline_images

## Brave version (brave://version info)

Brave | 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Linux
JavaScript | V8 7.9.317.32
Chrome/79.0.3945.88 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,SimplifyHttpsIndicator,WebUIDarkMode --disable-features=AudioServiceOutOfProcess,SmsReceiver,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AutofillServerCommunication,WebXR,WebXrGamepadModule,UnifiedConsent,AllowPopupsDuringPageUnload,SyncUSSBookmarks --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
Yes

- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:
Webpage will be displayed but maybe not with the benefit of lazyload pictures, inline small images ...

**Comment by ryanbr** [comment]
Beacons, event trackers,, performance monitoring are still monitoring the enduser and should stay blocked. Even 'helpful infomation' for the server, is still tracking/monitoring the end user.

**Comment by eldk** [comment]
Hello,

@ryanbr : they are not intersite beacons, but first party one. So, why block them ? 
Block them if they are from a third party domain is OK.

Some Brave team member should look at this ?

Thanks,

Eric

**Comment by rebron** [comment]
@ryanbr This is first party and we shouldn't be blocking it. Is there another reason why we're blocking this? Matching an easylist rule or something else?

**Comment by ryanbr** [comment]
Similar to blocking of matomo and pwik scripts, I do understand some scripts can be helpful, but they are sending analytics/events/checks/errors/etc is still tracking. We're blocking 1p tracking scripts for the sake of user privacy.

On a slightly different note, we now have to be careful since there are now some sites with 1st party scripts hiding 3rd-party elements.

**Comment by eldk** [comment]
Hello,

I think you missed some elements : if the 1.gif is delivered from the domain (https://domain/folder/1.gif), why is it reported as a tracker ?

I may count https://domain/folder/whatyouwant.gif  and this will not be blocked.

Thanks,

Eric
