### ISSUE TITLE
spreedly.com credit card form not working on RioTickets.ca

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#7505]
## Description 
It's not possible to build movie tickets on https://riotheatretickets.ca/ because the `spreedly.com` form doesn't show up.

## Steps to Reproduce

1. Go to https://riotheatretickets.ca/.
2. Pick a movie and click on "Find Tickets"
3. Select a quantity of 1 in the drop down inside the left hand pane.
4. Click "Find Tickets", then click "Continue"
5. Create an account with your email address, enter fake billing address (e.g. H0H0H0 as the postal code).
6. Click "Continue" until you get to "Step 3: Payment".

## Actual result (Shields ON):
![Screenshot from 2019-12-20 10-43-19](https://user-images.githubusercontent.com/167821/71283822-1b26c600-2316-11ea-8961-44f3395fe37a.png)

## Expected result (Shields OFF):
![Screenshot from 2019-12-20 10-47-39](https://user-images.githubusercontent.com/167821/71283844-27ab1e80-2316-11ea-879d-626540343769.png)

## Brave version (brave://version info)

```
Brave	1.2.28 Chromium: 79.0.3945.79 (Official Build) beta (64-bit)
Revision	29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}
OS	Linux
```

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? YES
- Is the issue reproducible on the latest version of Chrome? No

**Comment by ryanbr** [comment]
'Allow all cookies' should help here
