### ISSUE TITLE
Feature/Suggestion: Option to move UI/Address bar to bottom of screen 

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#7511]
## Description 
This is an updated consolidated issue for the "Bottom address bar" feature commonly requested by mobile users (#54, brave/brave-browser#7356).

**Reasoning**: Users should be offered this option for several reasons - the main one being the high variability of device types and screen sizes that a user may be browsing on. Having the same uniform layout across all devices works, but is not practical from a UX standpoint. 

Someone that downloads and uses a Samsung Galaxy Tab A to browse Brave inherits this burden by default based only on the device they're using - this is inflexible and furthermore, is something few  other browsers offer as an option. Including this option reflects well on us as it's implementation is (almost entirely) user interest focused.

**Alternative option**: At the same time, space on-screen is limited and there's no way to comfortably include every option/UI element on screen at once. One solution to this issue would be to include an option/button that jumps focus to the address bar when pressed. This way, the address bar itself needn't be moved, but users can still easily access it without having to reach to the top of their device every time (like our friend with the Galaxy Tab A).

This solution still involves "adding" something to the UI which is still the core issue (screen real estate). To solve, I would propose the following solution:

**Toggle between Search and New Tab button**

1. When browsing, Search button/icon is shown
2.  If the user wants to search, tapping "Search" moves focus into address bar (keyboard is displayed)
    -  ![image](https://user-images.githubusercontent.com/3299098/53906850-c7eebb80-4000-11e9-83c0-824352cf93d4.png)
4. When focus is given to address bar: "Search" icon flips to "New Tab" button:
    - ![image](https://user-images.githubusercontent.com/3299098/53906909-e9e83e00-4000-11e9-8d80-ffe10ffd2114.png)
6. When on New Tab Page: "New Tab" button flips back to "Search" icon - if you're already on a new tab, its unlikely you're going to want to open _another_ new tab.

Toggling this way increases users ease of access and overall experience without compromising screen space or moving any additional UI elements.

**Comment by srirambv** [comment]
+1 from @Morkowski  via https://github.com/brave/browser-android-tabs/issues/2389

**Comment by Brave-Matt** [comment]
Closing this, as this issue is old and the feature has already been implemented. 🎉

**Comment by rtcarey** [comment]
I don't see that this feature has been implemented, unless you consider the search icon on the bottom a compromise.

**Comment by SolarDesalination** [comment]
Naver Whale, Vivaldi, Yandex, Kiwi all offer this feature. Would be real nice for us with short thumbs..

**Comment by theshatterstone** [comment]
Hello, @brave can we get some update on this? Are we ever going to get a bottom address bar on mobile (a simple way to do it would just be a toggle to flip the top and bottom bars, while keeping the ability to disable that other bar), or should I just stick with Vivaldi?
