### ISSUE TITLE
Page tabs cannot be accessed on WebMD

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7512]
**Description of the issue:**
Tabs and Buttons not working WebMD URL:
`https://www.webmd.com/drugs/2/drug-64439/abilify-oral/details`

The Tab names at the top of this website named: "Side Effects Precautions Interactions Overdose Images Reviews" as well as the "Next >" button at the bottom of the page do not advance to any page when clicked. No error message is displayed.
These tabs work fine in Chrome for Android, Brave and Chrome on the Desktop.

**How can this issue be reproduced?**

1. Access WebMD site: `https://www.webmd.com/drugs/2/drug-64439/abilify-oral/details` using Brave for Android
2. Tap any of the named Tabs near the top of the page: "Side Effects Precautions Interactions Overdose Images Reviews".
3. Scroll to the bottom of the page and tap the "Next>" button.

**Expected result:** Clicking Tabs and Next> should advance to the appropriate pages.

**Brave Version( check `About Brave`):**
Brave for Android v1.6.0, Chromium 78.0.3904.108 

**Mobile Device details**
OnePlus 7 Pro GM1917 International version (using in United State)
Android Version: 9 Build/PKQ1.190110.001
Wireless connected device

**Additional Information:**
This site works as expected in Chrome for Android but exhibits the same results as in Brave using the Edge for Android browser version 42.0.4.4057

Original report from user https://community.brave.com/t/webmd-next-button-and-tabs-do-not-navigate-on-brave-for-android-v1-6-0-chromium-78-0-3904-108/99278/

**Comment by ryanbr** [comment]
Looking into this. Its caused by the instart ads. blocking these scripts seems to be causing issues.

**Comment by ryanbr** [comment]
@srirambv  fix rolling out in the next 24-48hrs, hopefully fixing this

**Comment by bsclifton** [comment]
@srirambv can we retest this? (I need to get an Android device setup!)

**Comment by srirambv** [comment]
Verified. Looks fixed :+1:
