### ISSUE TITLE
Switch from Uphold to a more free platform

### ISSUE THREAD

**Issue by mohammadrafigh** [brave/brave-browser#7513]
## Description 
Uphold completely destroys anonymity and doesn't allow to verify account from a lot of countries.
I like Brave just because it's safe and designed with privacy in mind. But currently to collect Brave rewards it relies on Uphold which needs photo ID, phone and address verification etc. I think Uphold actually doesn't fit in Brave and Cryptocurrency policies and concepts. currently I was not able to verify my account at Uphold.

## Steps to Reproduce
   1. Create an account on Uphold
   2. Try to verify your account

## Actual result:
In many cases and in many countries the user couldn't withdraw Brave rewards.

## Expected result:
Brave could replave Uphold with another platform which respects user privacy and supports all countries.

## Brave version (brave://version info)
all versions

**Comment by flyingscot5** [comment]
Is there even plans to move away from uphold at all? I’m not a huge fan of there high fees either.

**Comment by mandar-brave** [comment]
Lot of issues raised;

1. The ID check requirement is mandated requirement only for cash-out; No one is required to use 
 any custodian or ID check to use Brave or Brave Rewards. However, allowing bots/attacks to capture BAT w/o humanity checks is a challenge. We will keep working on upgrades and paths that make this easier.

2. Let's be clear again; No Brave Rewards users need to use Uphold or an ID check  to keep and use their rewards to award content. Cash out has restrictions and will continue to be the case.

3. Uphold does work very closely with us to ensure privacy boundaries - Brave has no way to get your personal data, including your original Uphold account ID. We work closely to ensure Brave's privacy promises hold between Brave and Uphold; as a custodian they are obligated to do what they need to to run their business within regulatory and compliance boundaries.

4. The final topic is custodians that can fulfill the promise of API based transactions, privacy guarantees, and support the Brave ecosystem at its current scale, are limited and focused on trading vs. wallet/transactional aspects.

Hope this helps; Thank you for listening.

**Comment by mohammadrafigh** [comment]
@mandar-brave you are right using brave rewards is not required for a user but I already registered my website as content creator and received some BAT donations I wanted to show my love to Brave by linking brave on my website also I suggested some startup founders to promote brave using badges. But when I tried to receive BATs in my wallet or exchange it with a Cryotocurrency Uphold says you need to verify your account, when I tried to verify my account they blocked my account because I'm located in Iran! Is it what Brave really can ignore?

**Comment by mandar-brave** [comment]
@mohammadrafigh your concern is genuine. 

Brave cannot support OFAC list of countries at this point per https://www.treasury.gov/resource-center/sanctions/pages/default.aspx; same goes for Uphold as well. Your BAT will be held in your account and will be earmarked for you when the status changes; that much we can promise.

**Comment by mandar-brave** [comment]
Closing issue for comment; easier addressed on community.
