### ISSUE TITLE
Clear STEP_NO when browser starts

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#7514]
Right now we don't have any logic that covers contribution that were added, but not a single step was triggered. This data can be deleted as we don't restart it from that point

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.4.84 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/4286 ( tested in staging env)
- Verified in clean and upgraded profile
