### ISSUE TITLE
Add DCHECK to Brave Ads Mojo bridges

### ISSUE THREAD

**Issue by masparrow** [brave/brave-browser#7516]
- [ ] Ensure all local variables are initialised
- [ ] Ensure all function argument pointers are valid before using/dereferencing

Examples highlighted below - but this is not exhaustive - please check all bridges!

<img width="787" alt="Screenshot 2019-12-20 at 16 09 58" src="https://user-images.githubusercontent.com/11368284/71369439-b59b3980-25a2-11ea-9670-19520c604db0.png">

**Comment by masparrow** [comment]
Split into https://github.com/brave/brave-browser/issues/7823 for ledger, and changed this to be for Ads

**Comment by tmancey** [comment]
@masparrow Based upon Google Style Guide I have added `DCHECK` but not defensive `if (!foo)` as discussed
