### ISSUE TITLE
Javascript debugging no longer has color highlighting(Inspect Element)

### ISSUE THREAD

**Issue by czzplnm** [brave/brave-browser#7517]
## Description 
When using Inspect Element to debug JavaScript code, the code is no longer color coded. Variables, scope, etc.

## Steps to Reproduce
Use Inspect Element and look at JavascriptCode

   1. Open a webpage that has Javascript
   2. Use Inspect Element
   3. View sources of a JavaScript file and all of its text will be black.

## Actual result:

![image](https://user-images.githubusercontent.com/5511418/71373605-a7322b00-256c-11ea-9f59-36cd94584c9e.png)

## Expected result:
![image](https://user-images.githubusercontent.com/5511418/71373636-ba44fb00-256c-11ea-96c4-3528e35b44c1.png)

## Reproduces how often: 
Always

## Brave version (brave://version info)
Brave | 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Linux
JavaScript | V8 7.9.317.32
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=LookalikeUrlNavigationSuggestionsUI,SyncUSSBookmarks,AllowPopupsDuringPageUnload,AutofillServerCommunication,NotificationTriggers,WebXrGamepadModule,UnifiedConsent,AudioServiceOutOfProcess,SmsReceiver,WebXR --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/hschultz/.config/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:
Not Sure

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? Not Sure
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
There must be other developers that hit this issue. 

Is there a setting I have disabled or something?

**Comment by srirambv** [comment]
Does enabling `Remote Debugging` under `brave://settings/privacy`help fix it? Do note this is only available on Dev and Nightly right now

**Comment by czzplnm** [comment]
> Does enabling `Remote Debugging` under `brave://settings/privacy`help fix it? Do note this is only available on Dev and Nightly right now

Don't have those installed, can you check if you have it downloaded?

**Comment by eljuno** [comment]
Per https://github.com/brave/brave-browser/issues/7372#issuecomment-565320651 the setting will available from v.1.2.x

**Comment by czzplnm** [comment]
> Per [#7372 (comment)](https://github.com/brave/brave-browser/issues/7372#issuecomment-565320651) the setting will available from v.1.2.x

So they removed a feature, just to readd it later? I've been using Brave to debug since it launched and it had code highlighting.

**Comment by bsclifton** [comment]
@czzplnm it was removed in early versions of Brave (0.59 I believe) and then yes, we allow it to be enabled in 1.2 and above

Some more detailed info can be found here:
https://github.com/brave/brave-browser/issues/7372#issuecomment-569130105
