### ISSUE TITLE
build brave-browser 1.4.45 error

### ISSUE THREAD

**Issue by zfoxzero** [brave/brave-browser#7524]
`FAILED: chrome.dll chrome.dll.lib chrome.dll.pdb
ninja -t msvc -e environment.x64 -- ../../third_party/llvm-build/Release+Asserts/bin/lld-link.exe /nologo "-libpath:C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\ATLMFC\lib\x64" "-libpath:C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\lib\x64" "-libpath:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "-libpath:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "-libpath:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" /IMPLIB:./chrome.dll.lib /DLL /OUT:./chrome.dll /PDB:./chrome.dll.pdb @./chrome.dll.rsp
lld-link: error: duplicate symbol: public: static class network::SystemRequestHandler * __cdecl network::SystemRequestHandler::GetInstance(void) in obj/brave/services/network/public/cpp/cpp/system_request_handler.obj and in network_cpp.dll
lld-link: error: duplicate symbol: public: struct network::ResourceRequest __cdecl network::SystemRequestHandler::OnBeforeSystemRequest(struct network::ResourceRequest const &) in obj/brave/services/network/public/cpp/cpp/system_request_handler.obj and in network_cpp.dll
lld-link: error: duplicate symbol: public: void __cdecl network::SystemRequestHandler::RegisterOnBeforeSystemRequestCallback(class base::RepeatingCallback<struct network::ResourceRequest __cdecl(struct network::ResourceRequest const &)> const &) in obj/brave/services/network/public/cpp/cpp/system_request_handler.obj and in network_cpp.dll
ninja: build stopped: subcommand failed.`
windows 10 x64,  visual studio 2019
npm run build  error
npm run build Release not found error

**Comment by bridiver** [comment]
this is happening because `//brave/services/network/public/cpp/BUILD.gn` is defined as a source set, but it exports `class COMPONENT_EXPORT(NETWORK_CPP) SystemRequestHandler` so in a component build it will be exported from everything that has a dep on it. It should be defined as a `jumbo_component` or `component` instead

**Comment by ShihChinYang** [comment]
Hi,  bridiver:
I am new to Brave code and having the same issue. Could you give me more details on how to fix this error?
I appreciated it,
Shih-Chin

> this is happening because `//brave/services/network/public/cpp/BUILD.gn` is defined as a source set, but it exports `class COMPONENT_EXPORT(NETWORK_CPP) SystemRequestHandler` so in a component build it will be exported from everything that has a dep on it. It should be defined as a `jumbo_component` or `component` instead

**Comment by zfoxzero** [comment]
> 
> 
> Hi, bridiver:
> I am new to Brave code and having the same issue. Could you give me more details on how to fix this error?
> I appreciated it,
> Shih-Chin
> 
> > this is happening because `//brave/services/network/public/cpp/BUILD.gn` is defined as a source set, but it exports `class COMPONENT_EXPORT(NETWORK_CPP) SystemRequestHandler` so in a component build it will be exported from everything that has a dep on it. It should be defined as a `jumbo_component` or `component` instead

run npm run build Release   
or
brave\services\network\public\cpp\BUILD.gn
del:  defines = [ "IS_NETWORK_CPP_IMPL" ]
brave\services\network\public\cpp\system_request_handler.h
del:  COMPONENT_EXPORT(NETWORK_CPP)
npm run build

**Comment by ShihChinYang** [comment]
Thank you, zfoxzero, that helped solve the issue.

Shih-Chin Yang

**Comment by bridiver** [comment]
The fix is merged into master  https://github.com/brave/brave-core/pull/4304

**Comment by bsclifton** [comment]
Closing as this is fixed in master, per above 😄
