### ISSUE TITLE
Brave browser window keeps blinking on startup.

### ISSUE THREAD

**Issue by Talmann** [brave/brave-browser#7525]
**The Brave browser window keeps blinking on startup.** 

## Steps to Reproduce

   1.  **Opening a Browser window. Starts blinking and I'm unable to stabilise a window**
   2. 
   3. 

## Actual result:
**The Brave browser window keeps blinking on startup.** 

## Expected result:

**Browser window should open**

## Reproduces how often: 

**Always happens. I am now not able to use Brave**

## Brave version (brave://version info)

**Brave version is 79.1.1.23. Unable to get the version from the browser itself.**

## Other Additional Information:

**Initially on start up, Brave would start blinking and I could position the curser over the three menu bars icon, the menu displays ok and click on open another window in tor. The new window would open normally and the original window stopped blinking. All good.**

**Now blinking continues and opening a new window in the above manner either continues to blinking or presents with a nice white screen. Happens on both displays 1 and 2. I have tried Task Manager under More tools option and a Task Manager window opens but still blinks and nothing is displayed. Cannot access other settings - setting page blinks with a white screen or anything else seemingly.**

**Uninstall and reinstalled Brave brower, no change.**

**Ran a dxdiag no errors.**

**Tried CONTROL + SHIFT + WIN + B to reset the graphics adaptor. No change.** 

**Blinking does not occur in Chrome or Opera browsers.**

**Comment by bsclifton** [comment]
@Talmann were you able to resolve the issue? If you weren't, I'd like to keep the issue open

Thanks for providing the details. Let us know 😄

**Comment by Talmann** [comment]
Thanks for replying. Still not resolved.

**Comment by Talmann** [comment]
Closing the issue as I have raised this on the Brave support website

**Comment by Talmann** [comment]
For closure, work around involves turning off hardware acceleration. The Windows solution offered by Brave support was to go to the Brave desktop shortcut, right-click --> Properties, edit the Target field and append **--disable-gpu** (or) **--disable-brave-sync** at the end of the target path, after the quotations.

After that, go to Settings --> Additional --> System --> Hardware Acceleration and turn the feature off there, manually. After this, you can remove the flag from the Target path (if you’d like).

Thanks and kudos to the Brave support.
