### ISSUE TITLE
Monthly tip set isn't shown in monthly contributions dropdown in panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7529]
## Description 

Found while testing #6744 
Monthly tip set isn't shown in monthly contributions dropdown in panel

## Steps to Reproduce

   1. Clean profile 1.3.76 staging env
   2. Open https://duckduckgo.com/
   3. Click on BR panel and set 5 BAT monthly tip
   4. Click on `Set Contributions` and close the banner
   5. Click on BR panel for DDG, 5 BAT monthly tip set isn't shown in panel dropdown

## Actual result:

Monthly tip set isn't shown in monthly contributions dropdown in panel
![monthly tip](https://user-images.githubusercontent.com/38657976/71529253-fd56f380-2909-11ea-876b-f77d6a39684f.gif)

## Expected result:

Monthly tip set should be shown in monthly contributions dropdown in panel

## Reproduces how often: 

80% reproducible rate
## Brave version (brave://version info)

Brave | 1.3.76 Chromium: 79.0.3945.88 (Official Build) dev (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @ryanml @rebron

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya is this still a problem on 1.4?

**Comment by NejcZdovc** [comment]
closing as stale
