### ISSUE TITLE
Not syncing well

### ISSUE THREAD

**Issue by vitormilagres1992** [brave/brave-browser#7533]
Hi everyone, 

Apparently the sync feature is not working well. I am running Linux Mint 19

I have 3 instances of the browser running on different computers, and when I first synced it, the bookmarks settings seemed to sync well, so I had all my bookmarks correctly labeled for all the 3 instances.

However, the changes I have made from that moment on do not seem to take effect in the other instances. Say for example, if I bookmark a new website, or if I create a new folder and group multiple websites in it, these changes would NOT be reflected in the other instances.

It seemed like the sync feature only worked when I used it for the first time in a new computer, but did not work afterwards.

How do I fix this?
Is there a folder I could backup on my computer so all the settings will be automatically adjusted if I restore it on another computer?

**Comment by bsclifton** [comment]
@vitormilagres1992 yes - you can definitely backup your profile directory (referred to in Chromium as the `user-data-dir`). On Linux, this should be at `~/.config/BraveSoftware/Brave-Browser`.  Unless you're using a Snap; that puts the information somewhere else

cc: @anthonypkeane @darkdh @AlexeyBarabash for the technical problem with the Sync feature

**Comment by vitormilagres1992** [comment]
Thanks for your help!

I didn't understand this: "cc: @anthonypkeane @darkdh @AlexeyBarabash for the technical problem with the Sync feature"
I am new to github. Is there a way to contact those people?

Thanks

**Comment by vitormilagres1992** [comment]
> @vitormilagres1992 yes - you can definitely backup your profile directory (referred to in Chromium as the `user-data-dir`). On Linux, this should be at `~/.config/BraveSoftware/Brave-Browser`. Unless you're using a Snap; that puts the information somewhere else
> 
> I manually back this directory up and restore when I run into issues. But having to rsync this (or otherwise manually sync) is not ideal
> 
> cc: @anthonypkeane @darkdh @AlexeyBarabash for the technical problem with the Sync feature

Wonderful!

I managed to get a hold of @darkdh, thanks @bsclifton

**Comment by bsclifton** [comment]
@vitormilagres1992 great, @darkdh is one of our developers working on Sync! 😄

Just by me mentioning the folks' usernames in the issue (cc = Carbon Copy, kind of a English specific email thing) they are notified via GitHub alerts and can easily find this issue

As you've gotten ahold of @darkdh, I'll go ahead and close this issue. We can re-open with more specific feedback or steps to reproduce. Or perhaps he can help you create a new issue (whatever makes sense)

Thanks for reporting and following up 😄👍
