### ISSUE TITLE
Audit feature of developer tools fails on brave.com

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#7534]
![image](https://user-images.githubusercontent.com/815158/71434301-68ee5600-26a9-11ea-926b-9dfc24cb95f7.png)

Protocol error (Runtime.evaluate): Promise was collected
```
Channel: DevTools
Initial URL: https://brave.com/
Chrome Version: 79.0.3945.88
Stack Trace: Error: Protocol error (Runtime.evaluate): Promise was collected
    at Function.fromProtocolMessage (devtools://devtools/remote/serve_file/@c2a58a36b9411c80829b4b154bfcab97e581f1f3/audits_worker/audits_worker_module.js:1634:121)
    at eval (devtools://devtools/remote/serve_file/@c2a58a36b9411c80829b4b154bfcab97e581f1f3/audits_worker/audits_worker_module.js:1232:246)
```

_Originally posted by @jonathansampson in https://github.com/brave/brave-browser/issues/3199#issuecomment-568844995_

**Comment by GeetaSarvadnya** [comment]
Seeing the same issue in windows 10 x64 - Brave beta `1.2.37`

![image](https://user-images.githubusercontent.com/38657976/71591139-303ef880-2b51-11ea-976f-95f008d3ecf3.png)

**Comment by bsclifton** [comment]
hmm... not sure what's special about my situation. Both brave.com and clifton.io work for me on Windows 10 x64 when Remote Debugging is enabled:
<img width="542" alt="Screen Shot 2019-12-30 at 11 13 01 AM" src="https://user-images.githubusercontent.com/4733304/71594547-a01f9580-2af5-11ea-8e95-7ae4b0d356e7.png">
<img width="539" alt="Screen Shot 2019-12-30 at 11 14 04 AM" src="https://user-images.githubusercontent.com/4733304/71594557-a3b31c80-2af5-11ea-9a4d-ea3a85150211.png">

I tested both while on and off VPN, both situations worked great. I tested with a fresh profile

**Comment by rebron** [comment]
@jonathansampson Are you using 1.2 or later with 'remote debugging' pref enabled?

**Comment by jonathansampson** [comment]
@rebron I just tried 1.5.10 again on brave.com, and it worked.
