### ISSUE TITLE
Brave for Android switches to dark theme when battery is low and loses changes to web pages

### ISSUE THREAD

**Issue by LorenzoVonMatterhom** [brave/brave-browser#7535]
## Description 

Brave for Android switches to dark theme when battery is low and it loses changes to web pages because it reloads without asking for permission.

## Steps to Reproduce

   1. Enable battery saver
   2. Resume brave

## Expected result:
Brave should ask for permission to reload web page.

## Reproduces how often: 
Everytime you enable disable battery saver.

**Comment by anthonypkeane** [comment]
@IlToro do you see this on Chrome too? Thanks

**Comment by anthonypkeane** [comment]
Expected Android behavior so won't fix
