### ISSUE TITLE
Replace help link with Brave support link 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7545]
## Description 

Replace help link with Brave support link 

## Steps to Reproduce

   1. Install beta build
   2. Open settings page
   3. Top right hand corner has help info button which opens Google support page

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/71589938-baa53f00-2af4-11ea-8eb7-6c8d40473edb.png)

## Expected result:
Help button should point to Brave community page

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Android-core Beta

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Info button should be replaced with close button to exit settings.

cc: @deeppandya

**Comment by bridiver** [comment]
this seems a bit odd to me, why would we remove a help button?

**Comment by bridiver** [comment]
@srirambv is there a ticket from browser-android-tabs we can link this to? Would at least be helpful to have some background on why we want this change

**Comment by emerick** [comment]
It looks like the help button was removed here:
https://github.com/brave/browser-android-tabs/commit/b09ff2f2f6a0c26ba1199ab80c9f9b2b29e1680e#diff-b5fd4c3e23b0882b32fc548be5e505a6L173

and this PR was for adding the close button:
https://github.com/brave/browser-android-tabs/pull/2030

**Comment by bridiver** [comment]
after discussion with @bbondy it seems better to just change the help link like we do for desktop. The original ticket was to add a close button, but no close button exists anymore

**Comment by srirambv** [comment]
Updated title and issue based on https://github.com/brave/brave-browser/issues/7545#issuecomment-574394522

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.57 x64 nightly build
- Verified clicking on help button on settings sheet opens community home page
------
Verification passed on OnePlus 6T with Android 10 running 1.5.57 x64 nightly build
- Verified clicking on help button on settings sheet opens community home page
------
