### ISSUE TITLE
Disable Home button should replace New Tab button

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7547]
## Description 

Disable Home button should replace New Tab button

## Steps to Reproduce

   1. Install Android beta
   2. Disable Home button from settings
   3. Doesn't replace it with New Tab button

## Actual result:

Disable Home button doesn't replace New Tab button

## Expected result:
Disable Home button should replace New Tab button

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Android-core beta

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @deeppandya  @SergeyZhukovsky should be fixed as part of first release to maintain feature parity of GPS build

**Comment by yrliou** [comment]
This is a part of "New behaviour for bottom toolbar buttons" issue (https://github.com/brave/browser-android-tabs/issues/1707) which is captured with
 https://github.com/brave/brave-browser/issues/7090 already, closing this one as duplicate.
