### ISSUE TITLE
Remove Sync and Brave Software services under privacy

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7549]
## Description 

Remove Sync and Brave Software services under privacy

## Steps to Reproduce

   1. Install Android-core beta
   2. Open Privacy settings
   3. Shows section for Brave software Services

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/71591414-3655ba80-2afa-11ea-8215-72cfadb04653.png)
![image](https://user-images.githubusercontent.com/17010094/71591454-62713b80-2afa-11ea-918a-8a90e563bdd6.png)

## Expected result:
Update settings as per whats needed

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Android-Core Beta

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @jumde @SergeyZhukovsky @bbondy we may want to move certain options out and have them at root level rather than a nested setting

**Comment by szaimen** [comment]
@srirambv where can I download the Android-core beta to test it out? Is it a public beta?

**Comment by kjozwiak** [comment]
> @srirambv where can I download the Android-core beta to test it out? Is it a public beta?

It's currently still pretty early and only available internally. However, we're planning on making it public in the near future. Just need to address/fix some major issues before making it available.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.57 x64 nightly build
- Verified no `Sync and Brave Software services` under privacy 
![image](https://user-images.githubusercontent.com/17010094/73092874-6c911a80-3eab-11ea-8e33-4c0d5ed2792e.png)

------
Verification passed on OnePlus 6T with Android 10 running 1.5.57 x64 nightly build
- Verified no `Sync and Brave Software services` under privacy 
![image](https://user-images.githubusercontent.com/17010094/73092887-70bd3800-3eab-11ea-9372-613b52fb5c68.png)
