### ISSUE TITLE
Increase size of Shields and Rewards button in URL bar

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7550]
## Description 

Increase size of Shields and Rewards button in URL bar

## Steps to Reproduce

   1. Install Android-core beta
   2. URL bar icons are smaller compared to current playstore release

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/71592803-9f8bfc80-2aff-11ea-80db-5cac3d6d729f.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/71592797-9733c180-2aff-11ea-881d-ded1b8183407.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Android-Core Beta

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Android-related changes done in https://github.com/brave/browser-android-tabs/issues/1384
cc: @deeppandya

**Comment by jamesmudgett** [comment]
The correctly sized logos are attached in brave/browser-android-tabs#1384, if conflicts exist let me know.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 
- Verified shields and rewards icons are bigger on nightly as compared to beta 
Beta
![image](https://user-images.githubusercontent.com/17010094/74422638-ed24b480-4e74-11ea-99cd-ae3035c8424d.png)
Nightly
![image](https://user-images.githubusercontent.com/17010094/74422706-07f72900-4e75-11ea-9eec-6e51411be0a7.png)
------
Verification passed on Samsung Tab A with Android 9.0 
- Verified shields and rewards icons are bigger on nightly as compared to beta 
Beta
![image](https://user-images.githubusercontent.com/17010094/74430233-81e1df00-4e82-11ea-97ed-d1914e018551.png)
Nightly
![image](https://user-images.githubusercontent.com/17010094/74430220-7bebfe00-4e82-11ea-99b6-852708525e30.png)
