### ISSUE TITLE
'popstate' does not work as expected

### ISSUE THREAD

**Issue by SephReed** [brave/brave-browser#7557]
## Description 

Google decided not to support popstate anymore.  This kind of breaks Single Page Apps.  

https://stackoverflow.com/questions/57339098/chrome-popstate-not-firing-on-back-button-if-no-user-interaction

## Steps to Reproduce

   1.  
```
<html><body>
  Hello World
  <script>window.addEventListener('popstate', function(event) {
    alert('test');
  });</script>
</body></html>
```
   2. Open page
   3. Select some text, click around
   4. Click back button

## Actual result:

No alert comes up

## Expected result:
Alert should come up

## Reproduces how often: 

Easily reproduced

## Miscellaneous Information:

I get that this is a built in "feature" but it's a mistake.   I can't think of a single website I regularly visit that abuses `popstate`.  Just because Google decided to punish every single developer for the actions of a few, does not mean you have to.  I would really appreciate it if Brave treated `popstate` the way it's meant to be treated.  I don't like having SPAs refresh with every nav event and use Brave specifically to not be treated like a mindless user.

**Comment by rebron** [comment]
Not going to deviate from chromium here. Please consider filing an issue on Chromium's bug system.

**Comment by SephReed** [comment]
Lame.
