### ISSUE TITLE
Red border when any UI Element is tapped

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7558]
## Description 

Red border when any UI Element is tapped

## Steps to Reproduce

   1. Install Android-core beta
   2. Tap on UI elements (Setting/Search button/Settings button)
   3. Red border flashes when UI elements are tapped

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/71629198-33c29600-2bca-11ea-9646-9b444918c217.png)

## Expected result:
No red border when UI elements are tapped

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Android-Core Beta

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
I'm seeing the same thing happen pretty often on my `Samsung S10+`. Clicking on some UI elements will produce a quick orange border that makes it appear like Brave is flickering. Quick example of the issue occurring:

* https://youtu.be/B7jPLqJJUg0

**Comment by anthonypkeane** [comment]
closing as haven't see it in a long time

**Comment by rezajax** [comment]
i have this problem, can you help me?
