### ISSUE TITLE
Cannot drag and drop certain URLs to create bookmarks on desktop

### ISSUE THREAD

**Issue by kevinlawler** [brave/brave-browser#756]
## Description 
Cannot drag and drop certain URLs to create bookmarks on desktop

## Steps to Reproduce

![screen shot 2018-08-16 at 8 02 14 am](https://user-images.githubusercontent.com/376238/44209982-b3150e00-a12a-11e8-8fe7-27e59761de22.png)

   1. Visit https://twitter.com
   2. Drag the section left of the address bar labeled "Secure" to the desktop
   3. Bookmark created
   4. Visit https://twitter.com/VitalikButerin/status/1029900695925706753
   5. Drag "Secure" to Desktop

## Actual result:
6. No bookmark created

## Expected result:
6. Bookmark created

## Reproduces how often: 
Always

## Brave version (about:brave info) 
Latest macOS

### Reproducible on current release:
Yes

**Comment by AlexeyBarabash** [comment]
Also reproduced on Linux `Version 0.54.0 Chromium: 69.0.3497.32 (Developer Build) (64-bit)`

**Comment by srirambv** [comment]
Reproduced on Windows as well `Version 0.55.0 Chromium: 69.0.3497.32 (Official Build) (64-bit)`

**Comment by bbondy** [comment]
Does this reproduce with Chrome 69?

**Comment by srirambv** [comment]
Reproduces on Chrome 69 as well.

**Comment by bbondy** [comment]
Likely will be fixed on a chromium upgrade.

**Comment by bsclifton** [comment]
Somewhere along the way, this was fixed 😄 Maybe a Chromium upgrade
