### ISSUE TITLE
Wallet often fails to load the transaction history + balance + tokens

### ISSUE THREAD

**Issue by canselcik** [brave/brave-browser#7560]
## Description 
The wallet at `brave://wallet`, more often than not, fails to load the transaction history, balances and the owned tokens. Switching to another network and back sometimes (but rarely) fixes the issue and everything is fetched. Until everything is fetched correctly, none of the apps using the `web3` API function properly.

![image](https://user-images.githubusercontent.com/1923255/71636633-8bbbc580-2be7-11ea-8071-91aa3ead325d.png)

I am using a hardware wallet but it shouldn't be a problem. I tried with the Trezor attached (although it shouldn't need to be attached for the data to be fetched) and even in that scenario it didn't work.

## Steps to Reproduce
   1. Make sure you've initialized the wallet. Maybe set up a hardware wallet with Trezor.
   2. Go to `brave://wallet` and check if everything is loaded properly. If it looks like it does in the screenshot above, you've reproduced the issue. `Loading Tokens...` doesn't disappear and only the ETH balance is shown (although it is stale). 

## Actual result:
Tokens, transaction history and updated balances should be shown. 
`web3` API should work.

## Expected result:
None of the tokens, transaction history or the updated balances are shown. 
`web3` API doesn't work when in this state.

## Reproduces how often: 
Easily reproduced when the wallets are in this state. In fact it is really hard to get it out of this state once it is reproduced.

Restarting the browser or trying the next day, it is not rare for the issue to resolve itself. However it always comes back.

## Brave version (brave://version info)
```
Brave | 1.1.23 Chromium: 79.0.3945.88 (Official Build) unknown (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Linux
JavaScript | V8 7.9.317.32
Flash | 32.0.0.303 /usr/lib/PepperFlash/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
Command Line | /usr/lib/brave-bin/brave --ppapi-flash-path=/usr/lib/PepperFlash/libpepflashplayer.so --ppapi-flash-version=32.0.0.303 --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=NotificationTriggers,AutofillServerCommunication,AudioServiceOutOfProcess,SmsReceiver,LookalikeUrlNavigationSuggestionsUI,WebXR,WebXrGamepadModule,UnifiedConsent,AllowPopupsDuringPageUnload,SyncUSSBookmarks --flag-switches-begin --load-media-router-component-extension=1 --flag-switches-end --disable-webrtc-apm-in-audio-service
Executable Path | /usr/lib/brave-bin/brave
Profile Path | /home/main/.config/BraveSoftware/Brave-Browser/Default
```

## Version/Channel Information:
- Can you reproduce this issue with the current release?
Yes, happens on current release.
- Can you reproduce this issue with the beta channel?
Yes, I tried it a few weeks ago hoping beta channel would have this fixed. Experienced the same issue.
- Can you reproduce this issue with the dev channel?
Haven't tried but likely.
- Can you reproduce this issue with the nightly channel?
Haven't tried but likely.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:
Hardware wallet is the only thing potentially non-standard in the configuration. Needless to say, everything works as expected on Chrome with Metamask.

Let me know if you have any questions.

Thanks.

**Comment by ryanml** [comment]
Fixed with: https://github.com/brave/devops/pull/2322

**Comment by ryanml** [comment]
@canselcik thanks for reporting! Let us know if you experience any other issues, functionality should be normal now.
