### ISSUE TITLE
[Wiki-Documentation] Linux Development Environment -> system requirements not found

### ISSUE THREAD

**Issue by reis-victor** [brave/brave-browser#7561]
## Description 

System Requirements page is not found

## Steps to Reproduce

   1. Navigate to https://github.com/brave/brave-browser/wiki/Linux-Development-Environment
   2.  Click the [system requirements](https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md#system-requirements) link

## Actual result:

```
NOT_FOUND: Requested entity was not found.

[type.googleapis.com/google.rpc.LocalizedMessage]
locale: "en-US"
message: "Object is not found"

[type.googleapis.com/google.rpc.RequestInfo]
request_id: "190cfb19fbe349a38b09e78791ac8125"
```

## Expected result:

Documentation found [here](https://github.com/chromium/chromium/blob/master/docs/linux/build_instructions.md#system-requirements)

## Reproduces how often: 

Always

**Comment by rebron** [comment]
https://github.com/brave/brave-browser/wiki/Linux-Development-Environment
Closing. Fixed. Thanks for the report @reis-victor.
