### ISSUE TITLE
Can't delete profiles on Brave

### ISSUE THREAD

**Issue by luxintra** [brave/brave-browser#7567]
How do we delete profiles created on Brave? This is driving me nuts. I can't find the option anywhere! It should be on the "Manage Profiles" pages but there is NOTHING. Sorry I am a little bit frustrated. 
Using Linux version.

**Comment by luxintra** [comment]
Okay I found the 3 dots but only because I saw someone mention them. They are almost impossible to see on my screen.

**Comment by srirambv** [comment]
If you have multiple profiles just click on the profile icon and then select Manage profiles. This should bring a popup window where it lists the profiles created. And you should be able to delete the profile by clicking on the menu button 
![image](https://user-images.githubusercontent.com/17010094/71667915-080fef00-2d35-11ea-8bed-ee06ba154b50.png)

**Comment by rebron** [comment]
Closing.

**Comment by timelessthee** [comment]
The "Manage Profile" button does not exist in the MacOS release as at Version 1.2.43 Chromium: 79.0.3945.130.
Please advise as the above solution does not solve the issue.

**Comment by bsclifton** [comment]
If you have multiple profiles and have the dialog above (showing the profile pictures), you can trigger the menu by clicking the `...` in the top right of the tile.
<img width="428" alt="Screen Shot 2020-03-29 at 10 17 48 PM" src="https://user-images.githubusercontent.com/4733304/77877657-3eadb680-720b-11ea-83bd-e934dbc075d2.png">


I've confirmed this works in the latest release version 1.5.115
![profile-delete](https://user-images.githubusercontent.com/4733304/77877582-01492900-720b-11ea-94bd-707c9b518817.gif)

**Comment by timelessthee** [comment]
> @timelessthee If you have multiple profiles and have the dialog above (showing the profile pictures), you can trigger the menu by clicking the `...` in the top right of the tile.
> <img alt="Screen Shot 2020-03-29 at 10 17 48 PM" width="428" src="https://user-images.githubusercontent.com/4733304/77877657-3eadb680-720b-11ea-83bd-e934dbc075d2.png">
> 
> I've confirmed this works in the latest release version 1.5.115
> ![profile-delete](https://user-images.githubusercontent.com/4733304/77877582-01492900-720b-11ea-94bd-707c9b518817.gif)

As mentioned above, **the dialog above in not accessible**. 

> The "Manage Profile" button does not exist in the MacOS release as at Version 1.2.43 Chromium: 79.0.3945.130.

**Comment by bsclifton** [comment]
@timelessthee if you have more than one profile, you would click the profile icon itself. I'm on macOS and it shows for me
<img width="361" alt="Screen Shot 2020-03-31 at 1 02 27 AM" src="https://user-images.githubusercontent.com/4733304/78001952-4cd30400-72eb-11ea-8b65-ad51325f0119.png">

If you're not seeing this then you only have one profile. If you're wanting to delete your default profile, you should be able to create a new one with the Hamburger menu => `Create a New Profile`. Then you can delete your old profile
