### ISSUE TITLE
Month/Year is repeated twice on rewards panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7570]
## Description 

Month/Year is repeated twice on rewards panel

## Steps to Reproduce

   1. Install Android-core beta build
   2. Enable rewards
   3. Open panel see duplicated values

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/71694513-68c31a00-2d7d-11ea-999e-884dc5ae0ed6.png)
![image](https://user-images.githubusercontent.com/17010094/71694524-6f519180-2d7d-11ea-9114-dc0ae1ac9c8e.png)

## Expected result:
No duplicated values

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Android-core beta build

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by yrliou** [comment]
FYI I didn't see it acting like this on master, it looks normal on my end without duplicate values.

**Comment by yrliou** [comment]
Weird, I installed brave beta from play store today and didn't see the duplicated values either.

**Comment by SergeyZhukovsky** [comment]
I can replicate it on both versions. I'm taking that issue.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.57 x64 build
- Verified panel shows values correctly 
![image](https://user-images.githubusercontent.com/17010094/73092366-7c5c2f00-3eaa-11ea-9eb6-ce4cbc533d4c.png)
------
Verification passed on OnePlus 6T with Android 10 running 1.5.57 x64 build
- Verified panel shows values correctly 
![image](https://user-images.githubusercontent.com/17010094/73092448-a7df1980-3eaa-11ea-985d-7e65d64f55f0.png)
