### ISSUE TITLE
Use Beta icon for ad notification to distinguish between release and beta ads

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7571]
## Description 

Use Beta icon for ad notification to distinguish between release and beta ads

## Steps to Reproduce

   1. Install Android-core and release
   2. Enable rewards on both
   3. Wait for ad notification to show up from beta

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/71914516-bd80df00-3147-11ea-974d-e83670f92042.png)

## Expected result:
Should have beta icon to distinguish ad notifications

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Android-core beta

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @anthonypkeane @jamesmudgett @SergeyZhukovsky

**Comment by bsclifton** [comment]
Notifications are being reworked right now - marking as blocked while folks work through https://github.com/brave/brave-core/pull/6451

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.25.51 x64 beta build
- Verified ad notifications use Beta icon
![image](https://user-images.githubusercontent.com/17010094/117299547-95ef7300-ae70-11eb-8649-ec4c5d0a466e.png)

-------
Verification passed on Samsung Tab A with Android 10 running 1.25.51 x64 beta build
- Verified ad notifications use Beta icon
![image](https://user-images.githubusercontent.com/17010094/117299562-9a1b9080-ae70-11eb-9060-64f73622f25d.png)

**Comment by stephendonner** [comment]
Removing `blocked` label, as https://github.com/brave/brave-core/pull/6451 is now closed.
