### ISSUE TITLE
Ads not available is shown for supported region

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7572]
## Description 

Ads not available is shown for supported region

## Steps to Reproduce

No clear STR. Install/Reinstall sometimes causes the issue 
## Actual result:

![image](https://user-images.githubusercontent.com/17010094/71695393-f7389b00-2d7f-11ea-998b-5eea0f71b72f.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/71695396-fbfd4f00-2d7f-11ea-9ae8-605a15b3570a.png)

## Reproduces how often: 

Easy if you are unlucky

## Brave version (brave://version info)

Android-core beta

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @yrliou @SergeyZhukovsky

**Comment by kjozwiak** [comment]
Seeing the same thing on my `S10+` running `Android 10` within Canada which is a supported ad region. Example of the issue:

![Screenshot_20200103-005849_Brave - Beta](https://user-images.githubusercontent.com/2602313/71709428-fece6300-2dc4-11ea-8a97-6ec33a434c8a.jpg)

**Comment by yrliou** [comment]
I think I found STR to reproduce it,
1. Open a new install brave
2. Use rewards panel to join rewards
3. Open rewards page

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.58 x64 build 
- Verified Ads is enabled for supported region when enabled via rewards panel 
- Verified Ads is enabled for supported region when enabled via rewards page 
- Verified Ads is enabled for supported region when enabled via onboarding
------- 
Verification passed on Samsung Tab A with Android 9 running 1.5.58 x64 build 
- Verified Ads is enabled for supported region when enabled via rewards panel 
- Verified Ads is enabled for supported region when enabled via rewards page 
- Verified Ads is enabled for supported region when enabled via onboarding
-------
