### ISSUE TITLE
Update private tab page to Brave private tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7576]
## Description 

Update private tab page to Brave private tab

## Actual result:

Uses Chromium incognito page
![Image from iOS (1)](https://user-images.githubusercontent.com/17010094/72027071-ad522800-324b-11ea-886c-06c0a0a85b99.jpg)

## Expected result:
Should use Brave private tab page
![Image from iOS](https://user-images.githubusercontent.com/17010094/72027076-af1beb80-324b-11ea-9d62-f5380df8fa92.jpg)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Android-Core beta

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @jamesmudgett @deeppandya

**Comment by srirambv** [comment]
@yrliou does it work with current master?

**Comment by yrliou** [comment]
@srirambv nope, it looks like we haven't ported private theme from android-browser-tabs.

**Comment by yrliou** [comment]
Android PR to port for this issue: https://github.com/brave/browser-android-tabs/pull/2193

**Comment by srirambv** [comment]
Also need to test the rewards button is removed from private tab

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.57 x64 nightly build
- Verified private tab uses Brave theme and private tab icon
-----
Verification passed on Samsung Tab A with Android 9 running 1.5.57 x64 nightly build
- Verified private tab uses Brave theme and private tab icon
