### ISSUE TITLE
Refactor & cleanup widevine sig file generation process on Windows

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#7578]
Currently, widevine sig file generation is done separately right after `build` is finished. https://github.com/brave/brave-browser/blob/master/lib/build.js#L113

Sig file generation script runs with system python because it was hard to resolve external dependencies(`cryptography`) that is not available from chromium packaged python. 

If we can do this  during the `create installer` step during the `create_dist`, it would be much simpler.
We can try this by installing additional dependencies to `brave/vendors`.

**Comment by mihaiplesa** [comment]
@simonhong is this still an issue today on Windows? On macOS vpython3 has `cryptography` installed.

**Comment by simonhong** [comment]
@mihaiplesa Oh! yeah, it's still an issue. it would be great if `cryptograhpy` is available also on Windows!

**Comment by mherrmann** [comment]
This issue is obsolete; We are now generating the sig files only in `create_dist`.
