### ISSUE TITLE
Contribution queue is not cleared

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#7579]
## Description 

Some users reported that their balance was reduced to 0 and multiple contributions happened. We don't have steps, but while debugging with @yachtcaptain23 I saw this error
```
[11430:11447:0101/233510.990260:ERROR:database.cc(1581)] publisher_info_db sqlite error 1, errno 0: no such table: main.publisher_info_old, sql: DELETE FROM contribution_queue WHERE contribution_queue_id = ?
```

Based on this error I investigated more and found that problem is in foreign key, that was not migrated correctly and is referencing table that doesn't exist (in the example `"publisher_info_old"`). Example of corrupted schema:

```
CREATE TABLE contribution_queue_publishers (contribution_queue_id INTEGER NOT NULL,publisher_key TEXT NOT NULL,amount_percent DOUBLE NOT NULL,CONSTRAINT fk_contribution_queue_publishers_publisher_key     FOREIGN KEY (publisher_key)     REFERENCES "publisher_info_old" (publisher_id),CONSTRAINT fk_contribution_queue_publishers_id     FOREIGN KEY (contribution_queue_id)     REFERENCES contribution_queue (contribution_queue_id)     ON DELETE CASCADE);
```

To fix this we will drop foreign key constrain and manually delete publishers related to the queue

## Steps to Reproduce
NA

## Actual result:

Queue is not deleted

## Expected result:
Queue should be deleted

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.2 x64` using the following build:

Brave | 1.2.41 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | macOS Version 10.15.2 (Build 19C57)

* Verified the test case outlined via https://github.com/brave/brave-core/pull/4303
* Verified the test cases outlined via https://github.com/brave/brave-core/pull/4303#issuecomment-570674309
