### ISSUE TITLE
Remove variations from Android core and Windows

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7582]
## Description 

Remove variations from Android core

## Steps to Reproduce

   1. Install Android-core beta
   2. Open chrome://version
   3. Shows variations

## Actual result:

Shows variations in chrome://version. More internal discussion here https://bravesoftware.slack.com/archives/CM17J5QMU/p1578007012032400

## Expected result:
No variations details in browser version info

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Android-core beta

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @bridiver @iefremov @SergeyZhukovsky @jumde

**Comment by jumde** [comment]
Variations are disabled on master, verified on v1.5.15

**Comment by srirambv** [comment]
Reopening the issue as CI builds are showing variations on master now.
![image](https://user-images.githubusercontent.com/17010094/72829729-54bc5b00-3c4d-11ea-83de-7bc5083a9325.png)

**Comment by bbondy** [comment]
The variations in @srirambv 's post above are no longer being shown, but one remains. 
I checked in a debug build what it was and it is: `MetricsAndCrashSampling:InreportingSample`
I'm going to remove the `android-core-release` label since it isn't related to just Android nor new.  Android tabs repo Release channel has it too. Our Windows Release channel has it too.

See: `chrome/browser/chrome_browser_field_trials.cc`

```
// Create a field trial to control metrics/crash sampling for Stable on
// Windows/Android if no variations seed was applied.
void CreateFallbackSamplingTrialIfNeeded(base::FeatureList* feature_list) {
#if defined(OS_WIN) || defined(OS_ANDROID)
  ChromeMetricsServicesManagerClient::CreateFallbackSamplingTrial(
      chrome::GetChannel(), feature_list);
#endif  // defined(OS_WIN) || defined(OS_ANDROID)
}
```

And `components/metrics_services_manager/metrics_services_manager_client.cc`:

```
// static
void ChromeMetricsServicesManagerClient::CreateFallbackSamplingTrial(
    version_info::Channel channel,
    base::FeatureList* feature_list) {
  // The trial name must be kept in sync with the server config controlling
  // sampling. If they don't match, then clients will be shuffled into different
  // groups when the server config takes over from the fallback trial.
  static const char kTrialName[] = "MetricsAndCrashSampling";
  scoped_refptr<base::FieldTrial> trial(
      base::FieldTrialList::FactoryGetFieldTrial(
          kTrialName, 1000, "Default", base::FieldTrial::ONE_TIME_RANDOMIZED,
          nullptr));

  // On all channels except stable, we sample out at a minimal rate to ensure
  // the code paths are exercised in the wild before hitting stable.
  int sampled_in_rate = 990;
  int sampled_out_rate = 10;
  if (channel == version_info::Channel::STABLE) {
    sampled_in_rate = 100;
    sampled_out_rate = 900;
  }

  // Like the trial name, the order that these two groups are added to the trial
  // must be kept in sync with the order that they appear in the server config.
  // For future sanity purposes, the desired order is:
  // OutOfReportingSample, InReportingSample

  static const char kSampledOutGroup[] = "OutOfReportingSample";
  AppendSamplingTrialGroup(kSampledOutGroup, sampled_out_rate, trial.get());

  static const char kInSampleGroup[] = "InReportingSample";
  AppendSamplingTrialGroup(kInSampleGroup, sampled_in_rate, trial.get());

  // Setup the feature. This must be done after all groups are added since
  // GetGroupNameWithoutActivation() will finalize the group choice.
  const std::string& group_name = trial->GetGroupNameWithoutActivation();
  feature_list->RegisterFieldTrialOverride(
      metrics::internal::kMetricsReportingFeature.name,
      group_name == kSampledOutGroup
          ? base::FeatureList::OVERRIDE_DISABLE_FEATURE
          : base::FeatureList::OVERRIDE_ENABLE_FEATURE,
      trial.get());
}
```

cc @jumde @bridiver @iefremov

**Comment by bsclifton** [comment]
@bbondy that one variation was found by @jonathansampson and is captured with https://github.com/brave/brave-browser/issues/8272

Since the other variations are not showing, I'll go ahead and close this issue out 😄
