### ISSUE TITLE
Update Crypto Wallet to reflect Old DAI changing to SAI

### ISSUE THREAD

**Issue by Pentagrade** [brave/brave-browser#7583]
## Description 
The latest versions of Metamask now show Single-Collateral DAI as "SAI" in the wallet and will automatically display Multi-Collateral DAI also if any is contained in the wallet.

Currently to achieve the same result in Crypto Wallet I have to add Multi-Collateral DAI manually. Single-Collateral DAI does appear with the SAI logo however, but uses "DAI" as its token symbol creating confusion as there are now two "DAI" symbols in my wallet.

Please could the behavior from Metamask be pulled across to Crypto Wallet?

## Steps to Reproduce

   1. Import a wallet containing Single-Collateral DAI (SAI) and Multi-Collateral DAI (DAI)
   2. Wallet displays DAI (but is actually SAI)

## Actual result:
![image](https://user-images.githubusercontent.com/5777172/71721883-cf4c4480-2e1e-11ea-9de5-7e6f1cee6c2d.png)

A picture from Metamask for comparison after importing the same wallet:
![image](https://user-images.githubusercontent.com/5777172/71722528-0ae80e00-2e21-11ea-8ac5-ee8ada8ccc6b.png)

## Brave version (brave://version info)

Brave | 1.4.50 Chromium: 79.0.3945.88 (Official Build) dev (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Windows 10 OS Version 1903 (Build 18362.476)

## Version/Channel Information:

- Can you reproduce this issue with the current release? **Yes, 1.1.23**
- Can you reproduce this issue with the beta channel? **Yes, 1.3.81** 
- Can you reproduce this issue with the dev channel? **Yes, 1.4.50**
- Can you reproduce this issue with the nightly channel? **Yes, 1.5.9**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **No**
- Does the issue resolve itself when disabling Brave Rewards? **No**
- Is the issue reproducible on the latest version of Chrome? **When using the latest version of Metamask, No**

**Comment by srirambv** [comment]
cc: @ryanml does the MM rebase on component `0.1.31` fix this as well?

**Comment by bbondy** [comment]
I think this should be included in the next release, please re-open if not @srirambv.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.2.41 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Linux
Component | `0.1.34`

![image](https://user-images.githubusercontent.com/17010094/72022401-572ab800-323e-11ea-8501-47e5046dd693.png)
