### ISSUE TITLE
Browser crashes when opening a new private tab from home screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7585]
## Description 

Browser crashes when opening a new private tab from home screen

## Steps to Reproduce (May not be accurate)

   1. Install Android-core beta
   2. Long press on Brave beta on home screen and select new private tab
   3. Close the private tab 
   4. Open tab tray
   5. Tap on three dots and open a new private tab
   6. Private tab closes and crashes 
   7. Try opening private tab a couple more times browser crashes and starts showing App stopped working 

## Actual result:

Browser crashes when opening a new private tab from home screen

## Expected result:
No crash no matter how private tabs are opened

## Reproduces how often: 

Intermittent

## Brave version (brave://version info)

Android-Core beta

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @SergeyZhukovsky @samartnik

**Comment by anthonypkeane** [comment]
fixed via another issue
