### ISSUE TITLE
Brave breaks Eclipse CHE

### ISSUE THREAD

**Issue by gattytto** [brave/brave-browser#7586]
## Description 

eclipse Che is a web-based cloud-native development IDE, some of its components can be managed using terminal emulators that have same background/text colors in brave web broser, rendering terminal text invisible.

## Steps to Reproduce

go to che.openshift.io and start some workspace.. if it manages to open, try open a terminal to any of the available cli containers, css breaks on terminals and shows same color for text and background so it's invisible

## Actual result:

![image](https://user-images.githubusercontent.com/407397/71728376-ac6c6100-2e1b-11ea-8586-508211782043.png)
![image](https://user-images.githubusercontent.com/407397/71728424-ca39c600-2e1b-11ea-9633-a37a63ebd79c.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by gattytto** [comment]
can I bump this?

**Comment by bsclifton** [comment]
@gattytto is there any difference if you put shields down? (ex: Lion icon in top right, toggle to off)

**Comment by gattytto** [comment]
@bsclifton that did it, thank you very much
