### ISSUE TITLE
Tapping Ad notification doesn't launch beta app

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7588]
## Description 

Tapping Ad notification doesn't launch beta app

## Steps to Reproduce

   1. Install Android-core beta and enable rewards
   2. Wait for an acutal ad notification to show up (not the sample ad notification)
   3. Close Brave-beta from recent apps 
   4. Open notification center and tap on the ad notification, Doesn't launch Brave-beta

## Actual result:

Tapping Ad notification doesn't launch beta app

## Expected result:
Should launch Brave-Beta if app is not running in memory

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Android-Core beta

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @gdregalo @samartnik

**Comment by emerick** [comment]
@srirambv Are you also seeing this behavior in the nightlies? I'm having trouble reproducing it, not sure if I'm missing a step...? When I exit the browser and tap on an ad, the browser relaunches with the ad (although there is a 2-3 second pause between tapping the ad and the browser launching).

**Comment by srirambv** [comment]
Haven't checked it on nightly will run through it. Will check it on nightly and update here

**Comment by emerick** [comment]
@srirambv Sounds good, thank you!

**Comment by srirambv** [comment]
@emerick I can reproduce this on Nightly CI build as well. Both with sample and actual ad notification as well

**Comment by emerick** [comment]
@srirambv OK, thanks for confirming - trying the nightly now, just waiting for an ad to show up...

**Comment by emerick** [comment]
@srirambv Finally got back to this and it's not happening for me with the latest nightly v1.6.21. If you can still repro, can you make a video showing how it happens from beginning to end? If not possible, maybe we can jump on a video call to do the same?

**Comment by srirambv** [comment]
@emerick  shared logs and video of issue reproducing on slack

**Comment by emerick** [comment]
@srirambv I tried with a locally built `BraveMonoarm64.apk` running on Android 10 and with the previous beta version (`1.5.97`). In both scenarios, clicking notifications when Brave wasn't running correctly launched Brave. I think there must be some other difference we're missing here. Is the behavior intermittent for you? Any other differences you can think of?

**Comment by SergeyZhukovsky** [comment]
I use Beta as my daily driver on my main device and ads clicks work as expected for me. @srirambv do you see it on some particular device or you can replicate on all Android devices you have?

**Comment by srirambv** [comment]
@SergeyZhukovsky  I see the issue on my OnePlus 6T with Android 10. I've shared the recording of the issue with @emerick and the logs. 

I don't seem to see any other difference apart from installing the apk. I haven't made any changes to notifications as well at device level

**Comment by srirambv** [comment]
I can see this issue happen on current GPS build as well

**Comment by GeetaSarvadnya** [comment]
Could not reproduce the issue in Samsung Galaxy J3 version 5.1.1 running Android stable 1.5.100 and GPS version 1.5.6

**Comment by emerick** [comment]
I wasn't able to repro with a OnePlus 6T device, unfortunately. I tried with Android 9 (which it shipped with) and Android 10 (after installing the updates). I tried debug and release builds and regular ARM and Monoarm64 builds with no luck.

**Comment by emerick** [comment]
Spoke with @SergeyZhukovsky and we're going to move this out of the upcoming 3/17 release as it also happens in browser-android-tabs per https://bravesoftware.slack.com/archives/GUA24E92P/p1582872239001400 and https://github.com/brave/brave-browser/issues/7588#issuecomment-592390442.

**Comment by kjozwiak** [comment]
I can't seem to reproduce this on my `Samsung Galaxy S10+` using `1.5.109 CR: 80.0.3987.132` either. Went through the following:

* had three different ad notifications listed under the notifications tray from Beta
* closed `1.5.109`, tapped on the first notification and `1.5.109` oepened
* repeated the above three times and `1.5.109` opened every single time

>  @srirambv do you see it on some particular device or you can replicate on all Android devices you have?

@srirambv can you reproduce this on other devices? Or just on the `OnePlus 6T` device?

**Comment by bsclifton** [comment]
cc: @srirambv to try latest beta and update status

NOTE: this will be obsolete with the custom notifications (currently locked down to Nightly)

**Comment by srirambv** [comment]
This seems to be working now. Closing the issue for now. Will reopen if I see the bug again.
