### ISSUE TITLE
Cyrpto wallets block number calls returning 429 Too many requests

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#7590]
## Description 
Calls going through our proxy for caching the block number are getting results of 429 Too many requests.

I wonder if it's possible that someone called the endpoint wrong without a project ID, and then that is now being cached and served? Or even with a misconfigured client from anyone's local build where they don't have a project ID specified locally.

Perhaps we can check to make sure what's being cached has the right project ID

## Steps to Reproduce

Per @ryanml that noticed it, but I think just in your console you will see 429 errors periodically for any usage.

## Reproduces how often: 
80% of the time?

## Brave version (brave://version info)
All

## Version/Channel Information:
- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? Yes 
- Can you reproduce this issue with the nightly channel? Yes

**Comment by ryanml** [comment]
This has been fixed with: https://github.com/brave/devops/pull/2322
