### ISSUE TITLE
Login to outlook.live.com does not log you into bing.com

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#7592]
From here: https://github.com/brave/brave-browser/issues/3082#issuecomment-570439809

##### `Case #1`

* visit https://outlook.live.com/
* login into your account (works without any issues)
* visit https://www.bing.com and you'll notice that you're not logged in
* click on `Sign In` and you'll be logged in automatically. You should be logged into Bing Rewards if you've already opted-in.

##### `Case #2`

* visit https://outlook.live.com/
* login into your account (works without any issues)
* visit https://www.bing.com and you'll notice that you're not logged in
* click on the `Rewards` button under Bing and select `Sign In`
* you'll be redirected to https://account.microsoft.com/rewards/ and will be logged in
* visit https://www.bing.com and you'll notice that you're not logged in/using out Outlook account
* click on `Sign In` and you'll be logged in automatically. You should be logged into Bing Rewards and view the panel if you've already opted-in.

The above two cases work on Chrome without any issues.

**Comment by ryanbr** [comment]
@jumde   Testing this, seems to be working better. I was able log between bing and outlook without too much issue. The only bug I saw was `msn.com` showed me as logged in, and wouldn't log me out.

**Comment by rebron** [comment]
Closing as stale/works for me. Looks like this is working now. Tried both test cases in a current build of 1.36 in release.
