### ISSUE TITLE
how to debugging use Visual Studio IDE

### ISSUE THREAD

**Issue by zfoxzero** [brave/brave-browser#7602]
i want debugging use Visual Studio IDE 
Please tell me how to do it
thanks

**Comment by bsclifton** [comment]
Hi @zfoxzero 

I'd recommend checking out the Chromium docs, as the experience will be similar
- https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md
- https://www.chromium.org/developers/how-tos/debugging-on-windows

Basically, once you compile in debug mode (`npm run build -- --debug`), you should be able to start using `npm start` and then sue Visual Studio and attach to the existing process
