### ISSUE TITLE
Desktop Chromium: save pages for offline reading like in mobile

### ISSUE THREAD

**Issue by DaniellMesquita** [brave/brave-browser#7604]

**Comment by srirambv** [comment]
@DaniellMesquita Please add details in the issue else will be closed as wontfix. We'll need some sort of information to know what the feature request is for. Is this one not  similar to the #7598?

**Comment by DaniellMesquita** [comment]
Yes, it is related.

Page saving is desktop Chromium is old. While in mobile, it saves the pages exactly as they're displayed.

For example, Medium articles. Saving is desktop gives 404. Saving the same Medium article on mobile just works.

My request is to port the same page saving from mobile to desktop. Good if it is also requested upstream.

**Comment by rebron** [comment]
Closing. Wontfix. We're not adding any extra offline features to desktop, we'll be matching Chrome here. You can save as web page already or look into using an extension for this feature.
