### ISSUE TITLE
Core: page for manage IPFS, integration with APIs of pinning services, showing user's pin list

### ISSUE THREAD

**Issue by DaniellMesquita** [brave/brave-browser#7605]

**Comment by DaniellMesquita** [comment]
Reference: https://github.com/brave/brave-browser/issues/819

**Comment by srirambv** [comment]
Please add more info to the issue

**Comment by DaniellMesquita** [comment]
![Screenshot_20200106-145807](https://user-images.githubusercontent.com/6765277/71837395-39c6e400-30ae-11ea-992d-23c3a026e756.png)

This feature is also what I thought for my Internet Cat browser.

Even relying on IPFS Companion (could communicate with the go daemon or JS IPFS), it could have a chrome://ipfs page like rewards have.

This page could contain all user's local pins, and also option for user putting Pinata API keys (a only IPFS pin could have the local and Pinata badges showing where it is pinned).

Also, user could see and manage its own peer ID. And a tab with the Chromium's offline downloaded pages.

**Comment by rebron** [comment]
Closing. Please follow the issue template when creating new issues.
