### ISSUE TITLE
[Feature Request] Add extension support on android

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7606]
Issue reported by @thepcwiz101

Kiwi browser (a chromium based browser) has added extension support on android. It's hard to believe and i have tested it. It is exclusive to the xda-developers forums for the next 24 hours. kiwi browser has a github repository too. I have screenshots i will be uploading to the issue in a few minutes.

![Screenshot_20190416-004149](https://user-images.githubusercontent.com/31826503/56184880-5c294680-5fe1-11e9-8acc-882317d8fbc3.png)
![Screenshot_20190416-004212](https://user-images.githubusercontent.com/31826503/56184888-64818180-5fe1-11e9-84ae-fb029c96b4f6.png)

**Comment by srirambv** [comment]
+1 from @DI555 via https://github.com/brave/browser-android-tabs/issues/1870
```
Since the kiwi extensions support patch is appeared, it would be great to fork it and investigate to goal of provide that patch be workable!!!

https://github.com/kiwibrowser/privacy_patches/blob/master/Add-support-for-extensions-on-Android.patch
And imo it should be developing more and polishing!
I grabed it here:
https://github.com/kiwibrowser/privacy_patches
```
---------

+1 from @D0ve and @avently  for adding support for Extenstions API on Android via https://github.com/brave/browser-android-tabs/issues/316

**Comment by GitHubUserNameDuck** [comment]
In December 2019, one Brave developer [posted a comment on reddit](https://www.reddit.com/r/brave_browser/comments/ebdg9n/will_there_be_a_possibility_to_add_extensions_on/fb51w5n/?utm_source=share&utm_medium=web2x) expressing his hope that extension support would be added to Brave on Android in 2H2020. As far as I know, there's no new info for the time being (March 2020).

**Comment by thepcwiz101** [comment]
i don't anticipate any ETA for the foreseeable future tbh. COVID-19 is to blame for that along with other more important priorities that the devs have.

**Comment by GitHubUserNameDuck** [comment]
### **Hooray!**
Today Brendan Eich confirmed in a tweet that extension support in Android will come soon! (still no ETA 🤷‍♂️)
https://twitter.com/BrendanEich/status/1248644666888609794
https://www.reddit.com/r/brave_browser/comments/fyj3f2/brendan_eich_confirms_extension_support_in/

**Comment by srirambv** [comment]
Closing in favour of #4493

**Comment by vehosah** [comment]
> Closing in favour of #4493

Which is only available to collaborators

**Comment by vehosah** [comment]
> Any updates about this?

Wish I knew
