### ISSUE TITLE
tips not going thru when tokens are not standardized to 0.25 value

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7608]
## Description 
If you have a wallet with VG and other BAT, tips are not going through. I experienced this on Nightly, @NejcZdovc experienced this on Dev.

## Steps to Reproduce
This is my scenario, @NejcZdovc has one that might be different
   1. Have Rewards enabled and have non-VG BAT in your anon wallet.
   2. Claim Ad grant (VG).
   3. Attempt to tip.
   4. Tip does not show up in Tips panel on brave://rewards. Wallet balance does not go down.

## Actual result:
Tip does not go thru

## Expected result:
Tip should go thru.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 1.5.10 Chromium: 79.0.3945.88 (Official Build) nightly (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | macOS Version 10.14.6 (Build 18G103)

@NejcZdovc reproduced on Dev as well.

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? yes (@NejcZdovc ) - 1.4.x
- Can you reproduce this issue with the nightly channel? yes (@LaurenWags ) - 1.5.10

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @NejcZdovc to add his details/scenario

**Comment by LaurenWags** [comment]
Reproduced in Dev using the following scenario:

Clean profile Dev (1.4.x) enable Rewards (staging)
Restore a wallet from Ad grant spreadsheet
Claim Ad grant
Claim UGP grant
Attempt to tip 3sistemi 1BAT.
Tip does not go thru and is not listed on brave://rewards

Profile for this scenario provided to @NejcZdovc 


Brave | 1.4.52 Chromium: 79.0.3945.88 (Official Build) dev (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | macOS Version 10.14.6 (Build 18G103)

**Comment by GeetaSarvadnya** [comment]
Using (https://github.com/brave/brave-browser/issues/7608#issuecomment-571364127)-Reproduced the issue in Windows 10 x64 - `1.4.52`

**Comment by GeetaSarvadnya** [comment]
The issue is reproduced in Windows 10 x64 -  1.3.85

1. Clean profile staging env 
2. Claim UGP grants
3. Send a one-time tip to a verified pubs
4. Send a monthly tip to a verified pubs
Actual:  - One-time and monthly tips are not displayed in the `Tips` panel
             - Monthly tip isn't displayed in `Monthly contributions` panel (https://github.com/brave/brave-browser/issues/7529)
             - Wallet balance is displayed correctly

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.2 x64` using the following build:

Brave | 1.3.94 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.15.2 (Build 19C57)

* Verified that all the cases under https://github.com/brave/brave-core/pull/4317#issuecomment-572756624 worked as expected

#### Example of VG + UGP grant:

<img width="1131" alt="Screen Shot 2020-01-17 at 3 46 07 PM" src="https://user-images.githubusercontent.com/2602313/72644989-7f05d400-3940-11ea-99ce-10bfcfd75121.png">
