### ISSUE TITLE
ESC does not close tip banner after tipping

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7609]
## Description 
If you open the tip banner and don't make any changes (tip), then ESC closes the banner. However, if you tip, ESC no longer closes the banner. Note, you can tab around in the banner for a bit before you encounter https://github.com/brave/brave-browser/issues/6986.

## Steps to Reproduce

   1. Have rewards enabled and BAT in your wallet.
   2. Go to a verified publisher.
   3. Open tip banner.
   4. Press ESC --> Tip banner closes.
   5. Open tip banner again.
   6. Tip site (note, thank you is "in line" in 1.2.x and above)
   7. Press ESC to close banner.

## Actual result:
Banner does not close, need to click on x to close banner.

## Expected result:
Banner should close with ESC

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 1.2.41 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | macOS Version 10.14.6 (Build 18G103)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a 1.1x as the "thank you" was not in-line for this version, but yes for 1.2.x
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @alexwykoff @mandar-brave

**Comment by GeetaSarvadnya** [comment]
Not reproducible in Windows 10 x64 - 1.2.41
![ESC key closes the tipping banner](https://user-images.githubusercontent.com/38657976/71888050-5c680400-3165-11ea-818c-96ff9510f7d2.gif)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.7.71 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4736
Verified for one time tip and monthly tip
