### ISSUE TITLE
Neowin.net webview crashes on first launch.

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#761]
## Description 
Neowin.net webview is getting crashed on first launch. When page gets refreshed it works as expected,

## Steps to Reproduce

   1. Launch Brave with clean profile from CLI
   2. Open Neowin.net website
   

## Actual result:
Neowin.net webview crashes on first launch
![neowin webview crash](https://user-images.githubusercontent.com/38657976/44273195-5c0f5600-a25c-11e8-8fb5-611e68ca5511.gif)

![image](https://user-images.githubusercontent.com/38657976/44272698-2d44b000-a25b-11e8-9f88-b8fa6e09bb97.png)

Console Error:
![image](https://user-images.githubusercontent.com/38657976/44272629-0b4b2d80-a25b-11e8-9389-78a6e18a9583.png)

## Expected result:
Webview should not crash

## Reproduces how often: 
100% Reproducible rate

## Brave version (about:brave info) 
Version 0.54.0 Chromium: 69.0.3497.32 (Official Build) dev (64-bit)

### Reproducible on current release:
No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? - No
- Is the issue reproducible on the latest version of Chrome?  - No

### Additional Information
cc: @bbondy

**Comment by bbondy** [comment]
I don't reproduce.

**Comment by bbondy** [comment]
on macOS, both the last developer channel build and on my local dbug build.

**Comment by bbondy** [comment]
@GeetaSarvadnya could you press on Send now on the crash and then copy and paste the crash report here? Thank you!

**Comment by GeetaSarvadnya** [comment]
@bbondy Please find the crash report below:

Crash reporting is disabled.
Crash reporting is not available in Brave.

Crashes (6)
Local Crash ID c044f73f-9442-45d2-a3a1-641130265ef5
Crash report captured on Friday, August 17, 2018 at 8:34:18 PM (upload requested by user, not yet uploaded)

Local Crash ID 1b4588bb-2a39-445d-8458-f2342cafe26d
Crash report captured on Friday, August 17, 2018 at 8:34:18 PM (upload requested by user, not yet uploaded)

Local Crash ID 7c9c1975-a632-4f71-9528-52b945ed5a95
Crash report captured on Friday, August 17, 2018 at 8:34:18 PM (upload requested by user, not yet uploaded)

Local Crash ID 6f77631c-c273-4b23-9bd0-14784095e525
Crash report captured on Friday, August 17, 2018 at 8:34:17 PM (upload requested by user, not yet uploaded)

Local Crash ID 20d90713-c50b-4705-8191-fb6db699e049
Crash report captured on Friday, August 17, 2018 at 8:34:17 PM (upload requested by user, not yet uploaded)

Local Crash ID 3734973c-c4e7-4313-96aa-b64cb5aed206
Crash report captured on Friday, August 17, 2018 at 8:34:17 PM (upload requested by user, not yet uploaded)

**Comment by GeetaSarvadnya** [comment]
Tested the above issue on latest build 0.54.1. Issue still persists,please find the crash id below:
Crash Report ID b81e7e125679caa0
cc: @bbondy

**Comment by GeetaSarvadnya** [comment]
@bbondy : Crash Report ID ae29bfa656f299d6

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7
