### ISSUE TITLE
Rewards: ModalContribute needs a custom mobile design

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#7613]
As part of https://github.com/brave/brave-core/pull/4275, @NejcZdovc mentioned that the `ModalContribute` box in Rewards needs a custom mobile design for Android. Need to talk to the design folks as far as how this should look/behave on mobile.

**Comment by anthonypkeane** [comment]
@NejcZdovc is this needed for Android now, to line up with 1.5 Desktop

**Comment by NejcZdovc** [comment]
@emerick @anthonypkeane how does it look right now?

**Comment by emerick** [comment]
Just needs some tweaks for mobile:

![device-2020-02-13-095836](https://user-images.githubusercontent.com/5033691/74447562-93f25c00-4e47-11ea-8854-a584e622c7c2.png)
![device-2020-02-13-095853](https://user-images.githubusercontent.com/5033691/74447571-96ed4c80-4e47-11ea-9a04-039069bc8be5.png)

**Comment by NejcZdovc** [comment]
@anthonypkeane based on what @emerick posted (thank you) I would say that we need to adjust it for 1.5

**Comment by anthonypkeane** [comment]
@jamesmudgett can you please knock out a fix for this design?

**Comment by SergeyZhukovsky** [comment]
@jamesmudgett any design update for that?

**Comment by anthonypkeane** [comment]
iOS does the below



![IMG_55E24D0CD2E3-2](https://user-images.githubusercontent.com/7606853/76259123-3537bc80-6212-11ea-8fe7-880ed7363bc7.jpeg)
![IMG_55E24D0CD2E3-3](https://user-images.githubusercontent.com/7606853/76259129-3832ad00-6212-11ea-9c16-53c5f0954349.jpeg)
![IMG_55E24D0CD2E3-4](https://user-images.githubusercontent.com/7606853/76259132-38cb4380-6212-11ea-894f-d4190c9b5315.jpeg)
![IMG_55E24D0CD2E3-5](https://user-images.githubusercontent.com/7606853/76259135-38cb4380-6212-11ea-93bf-7e60ca2a1687.jpeg)
![IMG_55E24D0CD2E3-1](https://user-images.githubusercontent.com/7606853/76259136-3963da00-6212-11ea-913e-9a3e8d596769.jpeg)

**Comment by SergeyZhukovsky** [comment]
@anthonypkeane I think it's fine to move out the issue for March 17th release as we are going to rewrite it after that. wdyt?

**Comment by SergeyZhukovsky** [comment]
as discussed in DM, we are pushing out that issue till we have a new design for settings page

**Comment by bsclifton** [comment]
This will be covered in https://github.com/brave/brave-browser/issues/10472 which will rework in native UI
