### ISSUE TITLE
Page refresh is causing the Browser Crash

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#762]
## Description 
Page refresh is causing the Browser Crash

## Steps to Reproduce

   1. Launch brave with clean profile
   2. Click on Skip Welcome tour link
   3. Click on Brave web store 
   4. Click on Last Pass extension, observer the pop up and close it
   5. Click on Hoeny extension
   6. Click on Refresh icon twice observe Honey pop up refreshed twice
   7. Click on Browser back button twice and observer Last Pass extension pop up
   8. Click on Refresh icon ( sometimes crash happens on 1st refresh, sometimes on 2nd crash)
   9. Observe the browser crash

## Actual result:
Page refresh is causing the Browser Crash
![page refresh causes browser crash](https://user-images.githubusercontent.com/38657976/44277485-75b69a80-a268-11e8-8b95-5d38aa35e782.gif)

Crash ID:
Uploaded Crash Report ID ed8d5514e59baea0 (Local Crash ID: 90642fdd-f635-4668-b236-5923fbd435d9)
Crash report captured on Friday, August 17, 2018 at 9:52:11 PM, uploaded on Friday, August 17, 2018 at 9:54:06 PM

## Expected result:
Browser should not crash

## Reproduces how often: 
Easily

## Brave version (about:brave info) 
Version 0.54.0 Chromium: 69.0.3497.32 (Official Build) dev (64-bit)
### Reproducible on current release:
No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? - No
- Is the issue reproducible on the latest version of Chrome?  - No

### Additional Information
cc: @bbondy

**Comment by GeetaSarvadnya** [comment]
Re-validated the issue against new build 0.54.1. Brave crashes on step 6 after first refresh.
Please find the crash id below:
Crash Report ID 6a447afd1ef04754

**Comment by GeetaSarvadnya** [comment]
@bbondy : Brave crashes on step 6 after first refresh.
Please find the crash id - Crash Report ID ac318e853176edf6

**Comment by GeetaSarvadnya** [comment]
Issue is fixed and working fine on 0.55.1. Hence closing the issue

**Comment by GeetaSarvadnya** [comment]
Issue is reproducible on 0.55.13. Hence reopening the issue.
![brave crashes on 0 55 13_reload chrome web store page](https://user-images.githubusercontent.com/38657976/46907712-55d3e800-cf34-11e8-95cc-64edce9322a1.gif)

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

* Verified the steps from issue and no crash
