### ISSUE TITLE
both the "magnify glass" & "+" buttons look like they're always selected

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#7620]
## Description 

Both the `magnify glass` icon that focuses the URL bar and the `+` button that creates new tabs look like they're always selected due to the light grey background that's always displayed. When I first saw the light grey background, I thought I ran into a state where the UI didn't update after the buttons have been tapped/clicked on.

## Steps to Reproduce

   1. install & launch latest `Brave-Beta` (brave-core build from GPS)
   2. you'll notice that both the `magnify glass` and `+` buttons have a permanent grey background

## Actual result:

![Screenshot_20200105-223134_Brave - Beta](https://user-images.githubusercontent.com/2602313/71856277-70522e00-30b1-11ea-8374-7b610eb2d3fb.jpg)

![Screenshot_20200105-223142_Brave - Beta](https://user-images.githubusercontent.com/2602313/71856278-70eac480-30b1-11ea-9654-05f6f81f7ddb.jpg)

## Expected result:

![Screenshot_20200106-182538_Brave](https://user-images.githubusercontent.com/2602313/71856872-5fa2b780-30b3-11ea-93af-5d232c5fdf4d.jpg)

![Screenshot_20200106-182532_Brave](https://user-images.githubusercontent.com/2602313/71856873-5fa2b780-30b3-11ea-9c0d-085ec0831441.jpg)

## Reproduces how often: 

100% reproducible when using the STR mentioned above.

## Brave version (brave://version info)

* Using the latest `Brave-Beta CR: 79.0.3945.88` (Unfortunately there isn't any versioning available)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No, only occurs with the brave-core beta`
- Can you reproduce this issue with the beta channel? `N/A`
- Can you reproduce this issue with the dev channel? `N/A`
- Can you reproduce this issue with the nightly channel? `N/A`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @SergeyZhukovsky @anthonypkeane @srirambv

**Comment by Madis0** [comment]
It is reproducible in the latest version of Chrome (`chrome://flags#enable-chrome-duet`) because that's where Brave got it - from upstream. Presumably it is made to highlight the most important function of the bar (like a FAB), but I can see why OP got confused.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.110 x64 stable build
