### ISSUE TITLE
crash when navigating through articles via https://www.cbr.com or enabling/disabling shield

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#7624]
## Description 

Brave will sometimes crash when navigating through https://www.cbr.com articles. It will also crash when disabling/enabling `Brave Shields` while viewing articles on https://www.cbr.com.

## Steps to Reproduce

**`Case #1`**

   1. install & launch latest `Brave-Beta` (brave-core build from GPS)
   2. visit https://www.cbr.com/star-wars-stormtroopers-ranked/
   3. tap on `Start Now ->` and navigate through the rankings using the `Next` button within the page

**`Case #2`**

   1. install & launch latest `Brave-Beta` (brave-core build from GPS)
   2. visit https://www.cbr.com/star-wars-stormtroopers-ranked/
   3. browse though the article by pressing `Next` a few times
   4. disable and enable `Shields` and you'll eventually run into the crash

## Actual result:

Examples of Brave crashing:

* https://youtu.be/uf-LYHs4uKI (Crashing right from the start when tapping `Next ->` button)
* https://youtu.be/o5gYzHHzSBw (Crash when pressing `Next` while navigating through the article
* https://youtu.be/dza6KTXhzns (Crash when disabling & enabling `Shields`)

## Expected result:

Brave shouldn't be crashing.

## Reproduces how often: 

It's not 100% but you'll eventually run into a few crashes if you attempt it enough times. I would say it's about ~30% or so reproducible. Sometimes you might get it right away and sometimes it takes a bit.

## Brave version (brave://version info)

* Using the latest `Brave-Beta CR: 79.0.3945.88` (Unfortunately there isn't any versioning available)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No, couldn't reproduce with 1.6.2 CR: 79.0.3945.93`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `N/A`
- Can you reproduce this issue with the nightly channel? `N/A`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `Yes, crash looks related to Shields`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

## Miscellaneous Information:

CCing @SergeyZhukovsky @anthonypkeane @srirambv

**Comment by AlexeyBarabash** [comment]
Cannot reproduce both on GPS version or on my local master build.

**Comment by AlexeyBarabash** [comment]
Same message as https://github.com/brave/brave-browser/issues/7686#issuecomment-577876386 @kjozwiak 
```Tried on both my phones. Probably I cannot reproduce  because of other region of ads being blocked. 
So @kjozwiak could you please try it when we will have a new build. Maybe https://github.com/brave/brave-core/pull/4418 will help.```

**Comment by kjozwiak** [comment]
Couldn't reproduce the issue using the following build:

```
Brave Beta - 1.5.59 CR:  79.0.3945.130
```

Using the URL mentioned via https://github.com/brave/brave-browser/issues/7624#issue-546057709, ensured the following:

* ensured loading the URL directly within Brave didn't cause any issues
  * ensured that scrolling the website didn't cause any crashes
  * ensured that refreshing the website several times didn't cause any crashes
* ensured that opening the URL via a third party applications using `Custom Tabs` didn't cause crashes
* ensured that opening the URL via a third party application directly in Brave didn't cause any crashes

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.5.111 BraveModernx86.apk
- no crashes observed when running thru case 1 from the description
- no crashes observed when running thru case 2 from the description
