### ISSUE TITLE
automatic tab being opened that points to cell providers customer home page

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#7626]
## Description 

When initially installing `Brave Beta` from the GPS, it opens a new tab with the following website:

* https://www.rogers.com/consumer/home/android-mobile?defaultpageload=mobile&setLanguage=en

Looks like there's some code that checks which cell provider I'm using and opens the related website? I'm not seeing this on our current `1.6.2 CR: 79.0.3945.93` release. I'm also not seeing this happen on my `Pixel 2 XL` running `Android 10` which has no SIM/Cell provider.

There's a `My Rogers` application that automatically installs once you insert the SIM card into the phone but disabling that didn't make a difference. Either way, this was never an issue our current android browser.

## Steps to Reproduce

   1. install & launch latest `Brave-Beta` (brave-core build from GPS)
   2. run through the onboarding experience

You'll notice that a new tab is automatically opened with the above mentioned link.

## Actual result:

Example of the issue occurring: https://youtu.be/AsLTcJ0P0CQ

![Screenshot_20200107-005324_Brave - Beta](https://user-images.githubusercontent.com/2602313/71872039-2f760b80-30e9-11ea-9b40-70eb76b7ef62.jpg)

## Expected result:

Brave shouldn't be opening new tabs that are associated with the users cell provider.

## Reproduces how often: 

100% reproducible on my `Samsung S10+` running `Android 10` which is using a mobile network but I can't reproduce it on my `Pixel 2 XL` running `Android 10` that doesn't have a SIM inserted.

## Brave version (brave://version info)

* Using the latest `Brave-Beta CR: 79.0.3945.88` (Unfortunately there isn't any versioning available)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `N/A`
- Can you reproduce this issue with the nightly channel? `N/A`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `Can't check as I can't remove Chrome`

## Miscellaneous Information:

CCing @SergeyZhukovsky @anthonypkeane @srirambv

**Comment by srirambv** [comment]
Cant reproduce this on my device. Moving it out of beta release for now

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 10` using `1.5.111 CR: 80.0.3987.132`:

* ensured that https://www.rogers.com/consumer/home/android-mobile?defaultpageload=mobile&setLanguage=en isn't being opened once you've completed onboarding
* ensured that https://www.rogers.com/consumer/home/android-mobile?defaultpageload=mobile&setLanguage=en isn't being opened when skipping onboarding

**Comment by marian980** [comment]
Telenor Quiz [https://www.mytelenorquiz.com.pk/](https://www.mytelenorquiz.com.pk/) Today gives users a fun way to answer daily questions and test their general knowledge. It can include questions from different topics, making each quiz interesting and engaging. By checking the quiz regularly, users can enjoy a quick knowledge challenge and learn something new each day.
