### ISSUE TITLE
removing the "Welcome to Brave" dialog on first launch

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#7627]
## Description 

We should remove the `Welcome to Brave` dialog that asks the user if they would like to submit usage data. Brave currently has no end points to collect this data. It's still going to Google. We basically just replace the `Google` text with `Brave`.

## Steps to Reproduce

   1. install & launch latest `Brave-Beta` (brave-core build from GPS)

## Actual result:

![Screenshot_20200107-000920_Brave - Beta](https://user-images.githubusercontent.com/2602313/71873355-f2137d00-30ec-11ea-8bf8-05dd0cd2a06e.jpg)

## Expected result:

Shouldn't be showing the `Welcome to Brave` dialog on initial launch.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

* Using the latest `Brave-Beta CR: 79.0.3945.88` (Unfortunately there isn't any versioning available)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `N/A`
- Can you reproduce this issue with the nightly channel? `N/A`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @SergeyZhukovsky @anthonypkeane @srirambv

**Comment by SergeyZhukovsky** [comment]
Something is strange with that dialog:

**Comment by SergeyZhukovsky** [comment]
Closing and will reopen if it appears again.

**Comment by srirambv** [comment]
Super seeded by #7841
