### ISSUE TITLE
warning when changing between advanced vs simple shields view isn't visible when using dark more

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#7628]
## Description 

The warning when switching between `Simple` vs `Advanced` mode under `Shields` isn't visible when using dark mode as per the example below.

## Steps to Reproduce

   1. install & launch `1.5.13 CR: 79.0.3945.88`
   2. visit https://brave.com and click on the `Brave Shield`
   3. select `Advanced View`

## Actual result:

<img width="438" alt="Screen Shot 2020-01-07 at 2 20 28 AM" src="https://user-images.githubusercontent.com/2602313/71876600-1c693880-30f5-11ea-9f90-72a9e8db9b47.png">

## Expected result:

<img width="508" alt="Screen Shot 2020-01-07 at 2 19 30 AM" src="https://user-images.githubusercontent.com/2602313/71876604-1ffcbf80-30f5-11ea-9214-20b338beffcc.png">

## Reproduces how often: 

100% reproducible when using the above STR.

## Brave version (brave://version info)

Brave | 1.5.13 Chromium: 79.0.3945.88 (Official Build) nightly (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | macOS Version 10.15.2 (Build 19C57)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Not reproducible using 1.2.41 CR: 79.0.3945.88`
- Can you reproduce this issue with the beta channel? `Reproducible using 1.3.85 CR: 79.0.3945.88`
- Can you reproduce this issue with the dev channel? `Reproducible using 1.4.52 Chromium: 79.0.3945.88`
- Can you reproduce this issue with the nightly channel? `Reproducible using  1.5.13 CR: 79.0.3945.88`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @brave/legacy_qa @bsclifton @rebron

**Comment by bsclifton** [comment]
@cezaraugusto is this because of a Brave UI change?

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.5.101 Chromium: 80.0.3987.116 (Official Build) beta (64-bit)
-- | --
Revision | dc00a510e4c2ae25c4d084cc3d946fc782249224-refs/branch-heads/3987@{#917}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4328
<img width="404" alt="Screen Shot 2020-02-26 at 5 01 39 PM" src="https://user-images.githubusercontent.com/28145373/75392556-47cd0000-58ba-11ea-93ad-dc50f4d65caf.png">
