### ISSUE TITLE
can not update

### ISSUE THREAD

**Issue by git10135405** [brave/brave-browser#7629]
what is the problem？
![image](https://user-images.githubusercontent.com/35558611/71880566-95a37280-316b-11ea-8ad8-53758c751ce6.png)

**Comment by bsclifton** [comment]
@git10135405 if you quit and restart Brave, is it able to find a newer version?

If not, I suspect something may be wrong with the install. Are you on Windows? Curious if the installer needs admin privileges to do the update. You can rule that out by starting Brave as administrator (should be an option when you right click the Brave executable)

**Comment by rebron** [comment]
Closing. Please reopen if it happens again.
