### ISSUE TITLE
Disable Chromecast support

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#763]
From: https://github.com/brave/brave-browser/issues/13

<img width="893" alt="screen shot 2018-08-17 at 10 33 09 am" src="https://user-images.githubusercontent.com/1903815/44280380-6ce2ac00-a209-11e8-83ee-c0508e1cecef.png">

**Comment by srirambv** [comment]
Doesn't this contradict support request mentioned in #209?

**Comment by jumde** [comment]
See discussion here: https://github.com/brave/brave-browser/issues/13#issuecomment-350367101

If possible, the plan is to have `chromecast` as an extension.

**Comment by bbondy** [comment]
Is there a security threat having this is causing? Just wondering since it seems to block even beta builds and might be seen as a step back for overall support.  If so that's cool.

**Comment by diracdeltas** [comment]
It's not a security threat per se, just additional vulnerability surface area I wasn't convinced we needed to have. If there are a  lot of requests for it then I'm fine with closing this.

**Comment by jumde** [comment]
I just checked the chrome web store and its not available as an extension. Closing this issue since there are sufficient requests from users for cast support.
