### ISSUE TITLE
Brave Wallet "Confirm your Secret Backup Phrase" should be sorted.

### ISSUE THREAD

**Issue by MicahZoltu** [brave/brave-browser#7630]
## Description 
When creating a new Brave Wallet, it gives me a seed phrase to note and then asks me to confirm it by selecting words from a list in the order the appeared in the seed phrase.  The problem is the list of words is unordered, so when I try to find the next word in my seed phrase I have to painstakingly search the word list one word at a time.  The list should be sorted in alphabetical order so it is easy to find the next word via a mental binary search (the way humans naturally try to search sorted lists).

## Steps to Reproduce
   1. Settings > Crypto Wallets > New Wallet
   2. Write down seed.
   3. Try to confirm.

## Actual result:
Pain and suffering that make me want to not use the feature.

## Expected result:
Delight at using modern financial technology.

## Reproduces how often: 
100%.

## Brave version (brave://version info)
Brave | 1.2.41 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Windows 10 OS Version 1903 (Build 18362.535)

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Unknown
- Can you reproduce this issue with the dev channel? Unknown
- Can you reproduce this issue with the nightly channel? Unknown

**Comment by srirambv** [comment]
I think this is by design that the words are not sorted. Probably a suggestion to considered upstream 

cc: @danfinlay @bbondy @ryanml

**Comment by MicahZoltu** [comment]
@srirambv I can't think of any reason the words would be unsorted by design.  There are no security benefit from random sort from alphabetical sort, and it makes UX noticeably worse.

Is the Brave wallet just a thin fork of MetaMask?  I haven't created a new account in MetaMask for some time, so maybe Brave is just using the same UI and I should file a bug over there?

**Comment by ryanml** [comment]
@MicahZoltu in this case MetaMask has the same behavior, we just use 24 word secret phrases as opposed to MM's 12. I think if you'd like to escalate this it'd be worth filing over at https://github.com/MetaMask/metamask-extension to get the team's thoughts on it.

**Comment by MicahZoltu** [comment]
Closing this in favor of new MetaMask bug https://github.com/MetaMask/metamask-extension/issues/7799.
