### ISSUE TITLE
Implement P3A metric "Q11: What is the state of your Brave Rewards wallet"

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#7634]
Implement as defined in https://github.com/brave/brave-browser/wiki/P3A

See `Brave.Rewards.WalletBalance` as example.

**Comment by mattmcalister** [comment]
I believe the purpose of this question was resolved with the v2 wallet questions recently released. Unless someone wants to look at this again I'm going to close this issue.

**Comment by iefremov** [comment]
@mattmcalister hmm I don't actually think so - which question can substitute this one?

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```


<!--StartFragment-->
Brave | 1.26.43 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Windows&nbsp;10 OS Version 2004 (Build 19041.985)

<!--EndFragment-->


```
- Verified the test plan from https://github.com/brave/brave-core/pull/8641

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.26.63 x64 Beta Build

<details>
<summary>Scenario 1: Check the response value when Rewards is not enabled </summary>
<br/>

- Confirmed there is no `Brave.Rewards.WalletState` stats display in `brave://local-state` when rewards isn't enabled
<img width=300 src=https://user-images.githubusercontent.com/17010094/122346899-5f157e00-cf41-11eb-9899-dbc9ddf24b6a.png>

</details>
<details>
<summary>Scenario 2: Check the response value when Rewards is enabled</summary>
<br/>

- Confirmed that the response value for `Brave.Rewards.WalletState` is displayed as `1` (Wallet created; no grants claimed; no funds added) when rewards is enabled
<img width=300 src=https://user-images.githubusercontent.com/17010094/122346982-75bbd500-cf41-11eb-88ed-b92d3cb4d509.png>

</details>
<details>
<summary>Scenario 3: Check the response value when UGP grants is claimed</summary>
<br/>

- Confirmed that the response value for `Brave.Rewards.WalletState` is displayed as `2` (Wallet created; grant(s) claimed; no funds added) when UGP grants is claimed
<img width=300 src=https://user-images.githubusercontent.com/17010094/122346928-663c8c00-cf41-11eb-834e-67e18333da04.png>

</details>
<details>
<summary>Scenario 4: Check the response value when Rewards is disabled (Ads and AC switches are off)</summary>
<br/>

- Confirmed that the response value for `Brave.Rewards.WalletState` is displayed as `5` (Wallet disabled after having been created (Brave Rewards switched off)) when UGP grants is claimed and rewards is disabled
<img width=300 src=https://user-images.githubusercontent.com/17010094/122346951-6ccb0380-cf41-11eb-9efe-3b5b507f1570.png>

</details>

- Encountered #16483
