### ISSUE TITLE
Switchmark extension freezes/crashes browser

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#7638]
## Description 

The Chrome extension Switchmark installs in Brave without issue but cannot be used. Clicking on the extension to switch between bookmark "bars" forces an infinite loading wheel (on macOS) that renders the browser unresponsive until force quitting.
GIF: https://imgur.com/a/ggxiq5m

## Steps to Reproduce

   1. Install [Switchmark](https://chrome.google.com/webstore/detail/switchmark/bnocffbiglfjjcgmifcampfmcbkfbhgc?hl=en-US) from Chrome webstore
   2. Click on Switchmark extension icon 
   3. Observe the browser locking up.

## Actual result:

Browser freezes

## Expected result:
Bookmarks bar should swap as is the intended function of the extension. 

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

Brave | 1.4.52 Chromium: 79.0.3945.88 (Official Build) dev (64-bit)
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | macOS Version 10.15.2 (Build 19C57)

## Version/Channel Information:

Occurs on all Brave channels.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No 

## Miscellaneous Information:

User on Community brought this to my attention:
https://community.brave.com/t/problem-with-bookmark-extension-switchmarks/101180

**Comment by bsclifton** [comment]
Wonder if this is related to the "Other bookmarks" change:
https://github.com/brave/brave-browser/issues/7639

**Comment by bridiver** [comment]
whatever is going on with Brave and "Other bookmarks", it shouldn't even be possible for an extension to freeze the browser so we should investigate and find out how it's happening and possibly fix the upstream issue independently of the bookmarks change

**Comment by bsclifton** [comment]
I don't think this is a problem anymore, as we restored `other bookmarks`. There is likely still a bug - but for now, I'll close as stale. We can re-open / revisit if this happens again
