### ISSUE TITLE
Remote debugging should be proxied and enabled by default

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#7645]
## Background 
Starting with Brave v1.2, users can enable the remote debugging option which allows for:
- service calls to be made out to Google (fetching syntax highlighting data, etc)
- Lighthouse audits
- actual remote debugging (connecting to phone, etc)

This setting is in brave://settings/privacy and is DISABLED by default. A more detailed description of this (including the Google network annotation) can be found here:
https://github.com/brave/brave-browser/issues/7372#issuecomment-569130105

There is no alert (infobar, etc) when the setting is disabled, so users are left thinking there is a bug

## Feature request
1. The calls made out to Google services for remote debugging should be proxied to remove user identifiable information (ex: IP address)
2. The `Remote Debugging` feature should be defaulted to ENABLED

## Steps to Reproduce

   1. Fresh profile
   2. Visit https://brave.com
   3. Open developer tools
   4. Go to audit tab
   5. Run Lighthouse audit

## Actual result:
It fails and there is no UI notifying you ☹️ 

If you opened via the command line, you WILL see stdout logging which suggests going to brave://settings/privacy and enabling `Remote Debugging`

## Expected result:
It should just work

## Reproduces how often: 
100%

cc: @jumde @rebron

**Comment by bsclifton** [comment]
per @xPaw via https://github.com/GoogleChrome/lighthouse/issues/9484#issuecomment-584571058
> I have adblock running on my local network, and chrome-devtools-frontend.appspot.com is blocked in AdAway list, whitelisting that has fixed lighthouse for me.
>
> Lighthouse ought to have a proper error message when it's unable to fetch from there.

**Comment by jumde** [comment]
Upstream bug is triggered by enabling this: https://bugs.chromium.org/p/chromium/issues/detail?id=1036525.  

Work in progress, stay tuned!

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.10.87 Chromium: 83.0.4103.61 (Official Build) (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | Ubuntu 18.04 LTS

Reproduced the original issue on 1.9.80. Lighthouse audit is stuck

![image](https://user-images.githubusercontent.com/34715963/84224433-d289e180-aadc-11ea-9c82-1e5b7d18d8dd.png)

Verified test plan from https://github.com/brave/brave-core/pull/5500 and description

Verified `Remote debugging` is turned on in settings
![image](https://user-images.githubusercontent.com/34715963/84224793-ade23980-aadd-11ea-83f1-d4f3f55ab1ba.png)

Verified Lighthouse audit was successful
![image](https://user-images.githubusercontent.com/34715963/84224724-88edc680-aadd-11ea-826d-62c32fa6cf08.png)

Verified on clean install and upgrade.
Encountered https://github.com/brave/brave-browser/issues/9715

**Comment by francoism90** [comment]
It would be great if a description could be added for this setting:

![image](https://user-images.githubusercontent.com/5028905/85683148-41fef400-b6cd-11ea-9663-7e97629ae9b5.png)

Does this need a new ticket?

**Comment by bsclifton** [comment]
@francoism90 I think we're going to remove that setting, as it's now defaulted to on

You can follow https://github.com/brave/brave-browser/issues/9715 for updates

**Comment by rg-3** [comment]
@bsclifton I don't want to use `Remote debugging` and I would prefer to keep it off. I was surprised to learn this is enabled by default. Anything that allows remote access to my browser (as I understand this feature) is not okay with me and I don't want it on nor do I want to use services that rely on it.
