### ISSUE TITLE
Disable QUIC

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#765]
From: https://github.com/brave/brave-browser/issues/13#issuecomment-349455506

## Steps to Reproduce

   1.  Navigate to `chrome://net-internals/#quic`.
   2.  Open `maps.google.com` or `mail.google.com` in a new tab to see all QUIC events in the previous tab.

## Actual result:
QUIC is not disabled.

## Expected result:
QUIC should be disabled.

## Reproduces how often: 
100%

## Brave version (about:brave info) 
`0.54.0 Chromium: 69.0.3497.32 (Official Build) dev (64-bit)`

### Reproducible on current release:
Yes

<img width="863" alt="screen shot 2018-08-17 at 11 24 48 am" src="https://user-images.githubusercontent.com/1903815/44282983-afa88200-a211-11e8-8381-83c4f335e9f5.png">

**Comment by bbondy** [comment]
This is a dupe of https://github.com/brave/brave-browser/issues/190 and we decided to close. Let me know if you disagree with that, and if so for what reason.
