### ISSUE TITLE
videos not working on Twitter

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#7651]
## Description 

Looks like videos are not working under https://mobile.twitter.com/home. Whenever you tap on a video, you'll eventually get a `The media could not be played.`

Possibly related to https://github.com/brave/brave-browser/issues/7600.

## Steps to Reproduce

   1. install & download the latest android-core-releae from GPS (using `79.0.3945.88` in this case)
   2. visit https://mobile.twitter.com/home and attempt to play any video
   3. once you tap on a video in a tweet, you'll receive `The media could not be played.`

## Actual result:

* Video example of the issue occurring on Twitter: https://youtu.be/WQeYq519JPY

![Screenshot_20200107-163532_Brave - Beta](https://user-images.githubusercontent.com/2602313/71949749-bf2bc080-31a2-11ea-82e4-8b2c54c21cbe.jpg)

## Expected result:

Viewing videos on Twitter should be working in Brave.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

* Using the latest `Brave-Beta CR: 79.0.3945.88` (Unfortunately there isn't any versioning available)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No, working in the current release of Brave`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `N/A`
- Can you reproduce this issue with the nightly channel? `N/A`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `No, still reproducible`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

## Miscellaneous Information:

CCing @SergeyZhukovsky @anthonypkeane @srirambv

**Comment by anthonypkeane** [comment]
We had that here also https://github.com/brave/brave-browser/issues/7351 but it was resolved in 1.6.1

**Comment by srirambv** [comment]
Need to verify if  #7878 fixes this as well

**Comment by yrliou** [comment]
Tried using Bravearm.apk on pixel3 using master and it seems it is already fixed by #7878 , please feel free to reopen if not. Thanks.

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm 1.5.110.apk`
