### ISSUE TITLE
Tweet message for "tweet about your tip" for GitHub contributors doesn't link to origin

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#7652]
## Description 

When I tip a contributor on Github and click to tweet about my tip, the message in the tweet does not link back to the origin event. 

Without linking back to the origin event, the message we tweet about the engagement points to a page that is not related to the event. It appears that we're directing people to "Check it (the thing i tipped) out at brave.com/tips", where we don't display the event that was tipped. 

If we're unable to link back to the origin when tweeting about tips that took place outside of Twitter,  suggest we hide the option to tweet about tips that take place outside of Twitter to avoid confusion or negative feedback.

## Steps to Reproduce

   1. Go to a github issue
   2. Tip the github user 
   3. Click to tweet about the tip

## Actual result:

The pre-written message in the tweet displays as: 
```
I just tipped Sriram using the Brave Browser. Check it out at https://brave.com/tips. #TipWithBrave
```

## Expected result:
```
I just tipped Sriram using the Brave Browser. Check it out at <INSERT GH ISSUE || COMMENT || COMMIT || PR ORIGIN URL>. Learn more at https://brave.com/tips #TipWithBrave
```

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.4.50 Chromium: 79.0.3945.88 (Official Build) dev (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? TBD
- Can you reproduce this issue with the beta channel? TBD
- Can you reproduce this issue with the dev channel? Confirmed
- Can you reproduce this issue with the nightly channel? TBD

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @alexwykoff
