### ISSUE TITLE
Internal server error 500 can cause Confirmations to get stuck in the retry queue

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#7654]
## Description 

Internal server error 500 can cause Confirmations to get stuck in the retry queue as there is no way of knowing if the server successfully created a Confirmation or not. To fix this issue, we fetch the payment token, and if we receive an HTTP_NOT_FOUND response, we then re-create the confirmation.

## Steps to Reproduce

   1. View a Brave Ads ad notification

## Actual result:

POST /v1/confirmation/{confirmation_id}/{credential} end-point returns response status code 400 (Credential is invalid, Duplicate Redemption)

## Expected result:
Confirmations should not be re-created if they already exist on the server

## Reproduces how often: 

Intermittent issue

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Console log showing error:

  Response Status Code: 400
  Response: {"error":"Credential is invalid, Duplicate Redemption","statusCode":400}
  Headers:
    accept-ranges: bytes
    access-control-allow-origin: *
    connection: keep-alive
    content-length: 72
    content-type: application/json; charset=utf-8
    date: Sat, 04 Jan 2020 14:25:07 GMT
    etag: W/"48-0RAp6ZrZWv+9N0i5xv78QPEAr/g"
    via: 1.1 varnish
    x-cache: MISS
    x-cache-hits: 0
    x-powered-by: Express
    x-served-by: cache-fty21370-FTY
 Failed to create confirmation

**Comment by kjozwiak** [comment]
Because this is going to be hard to go through in terms of verification, QA will basically run through the ad regression passes to ensure that ads are still working as expected.
