### ISSUE TITLE
Sometimes TOR doesn't work on 1.2.41

### ISSUE THREAD

**Issue by roshan8** [brave/brave-browser#7655]
Hey Folks,

Really great work on brave-browser, Protecting users privacy is much needed when every other services are trying to spy on you!

TOR window is really slow compare to TOR browser and sometimes it even don't open the page as well. 

TOR in incognito mode is the major reason for switching to Brave, Would be great if this issue gets addressed!

**Comment by srirambv** [comment]
What platform are you running? Are you behind VPN?

**Comment by roshan8** [comment]
I'm using this on Mac, not using any VPN

**Comment by rebron** [comment]
cc: @tomlowenthal

**Comment by jumde** [comment]
@roshan8 - Are you still seeing this? If so, what version of Brave Browser are you using? Can you also share the `Tor Client Updater` version. You can find this out by navigating to `brave://components`.

**Comment by bsclifton** [comment]
Closing as stale
