### ISSUE TITLE
Browser crashes when tipping on Android

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#7657]
## Description 

Brave-core version of Android crashes when tipping a publisher.

## Steps to Reproduce

   1. Clean profile
   2. Enable rewards and fund the wallet
   3. Send a one-time to a publisher

## Actual result:

Browser crashes and exits

## Expected result:
Tip should complete and browser continues to run

## Reproduces how often: 

Always
## Brave version (brave://version info)
Master

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by emerick** [comment]
Issue is related to the favicon source code. This code was removed from Android in Chromium as it was unused there. We needed to reinstate it in Brave, as Rewards relies on it. When tipping, however, the favicon code tries to reference the native theme instance which is a `nullptr` on Android leading to the crash.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.58 x64 build
- Verified tipping a verified publisher isn't causing the browser to crash 
------
Verification passed on Samsung Tab A with Android 9 running 1.5.58 x64 build
- Verified tipping a verified publisher isn't causing the browser to crash
