### ISSUE TITLE
No verified rewards icon for verified publishers in URL bar

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#7663]
## Description 
When visiting a verified publisher on brave-core Android, the Rewards panel icon doesn't show the "verified" checkmark.

## Steps to Reproduce

   1. Clean profile
   2. Enable rewards
   3. Visit verified publisher

## Actual result:
No checkmark icon in Rewards panel icon in URL bar

## Expected result:
Checkmark icon overlay should appear on Rewards panel URL bar icon

## Reproduces how often: 

Always

## Brave version (brave://version info)

`master`

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by anthonypkeane** [comment]
Pls check if this is on staging or Prod

**Comment by emerick** [comment]
I tried on staging using the site laurenwags.github.io. When I visit this site on Android, the Rewards panel icon in the URL bar doesn't show the checkmark overlay. However, if I display the pulldown the Rewards panel does show the icon. So I think we're detecting that the site is a verified publisher, we're just not updating the URL bar icon correctly to reflect it.

**Comment by yrliou** [comment]
Target PR to port: https://github.com/brave/browser-android-tabs/pull/2316

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernam 1.5.110.apk`
![image](https://user-images.githubusercontent.com/38657976/76309748-6b00a200-62f3-11ea-8d6b-02841f86a322.png)
![image](https://user-images.githubusercontent.com/38657976/76309805-8b306100-62f3-11ea-95cf-5ddd90bdd8eb.png)
