### ISSUE TITLE
Unable to get ad tokens if tokens are not ready with 1.3.x, 1.4.x and 1.5.x

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7666]
## Description 
When launching 1.3.x, 1.4.x or 1.5.x with a clean profile via terminal (with flags) I can see that I get the following message:

```
[11022:775:0107/121325.957157:ERROR:refill_tokens.cc(260)] Failed to verify and unblind tokens
```

and then a bit further down you will see a `Failed to refill tokens` message.

Because I can't get ad tokens, I can't receive ad notifications.

## Steps to Reproduce

   1. Launch 1.3.x with clean profile and the following flags: `--enable-logging=stderr --vmodule=brave_ads=3 --log-level=2 --rewards=staging=true --brave-ads-staging` (note, you don't need the staging flags, this reproduces with production as well)
   2. Enable Rewards
   3. Watch terminal

## Actual result:
attempts to get ad tokens are made, but ad tokens are not verified as per message above.

## Expected result:
should be getting ad tokens so ad notifications can be received.

## Reproduces how often: 
easily (intermittent for @tmancey) however every time for @NejcZdovc and @LaurenWags

## Brave version (brave://version info)

Brave | 1.3.86 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | macOS Version 10.14.6 (Build 18G103)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a with 1.2.x
- Can you reproduce this issue with the beta channel? yes with 1.3.x
- Can you reproduce this issue with the dev channel? yes with 1.4.x
- Can you reproduce this issue with the nightly channel? yes with 1.5.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @tmancey @rebron @kjozwiak @jsecretan 
reproduced on Linux by @btlechowski

**Comment by LaurenWags** [comment]
full logs: https://gist.github.com/LaurenWags/a2b88143eaf9b27838989494794f083d

**Comment by btlechowski** [comment]
Reproduced on Ubuntu 18.04 LTS

Brave | 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Ubuntu 18.04 LTS

[chrome_debug.log](https://github.com/brave/brave-browser/files/4036794/chrome_debug.log)

**Comment by LaurenWags** [comment]
Removing `QA/Blocked` as this can be tested on 1.3.92 and above

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.3.92 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.14.6 (Build 18G103)

* Verified test plan from https://github.com/brave/brave-core/pull/4334
* Verified scenarios from https://github.com/brave/brave-core/pull/4334#issuecomment-574262938 and terminal logging info was shown as expected.
* Verified on a clean profile: verified ad tokens were received and I was able to view an ad notification. (Staging and production)
* Verified on upgraded profile: reproduced the issue on 1.3.86. Upgraded to 1.3.92 and verified ad tokens were received and I was able to view an ad notification. (Staging)
