### ISSUE TITLE
Ability to tell whether the browser running the Chrome Extension is Brave or not

### ISSUE THREAD

**Issue by mayeaux** [brave/brave-browser#7667]
Hi there, I'm developing a Chrome Extension that is somewhat specific to Brave users. Based upon that I would like to be able to tell if the browser that the user is running the extension with is Brave Browser or not. I haven't seen any documentation about this online so I figured I would ask the question here.

Also, I'd like to point out some incomplete markup on this page:
https://support.brave.com/hc/en-us/articles/360017909112-How-can-I-add-extensions-to-Brave-

You can see a sentence ends randomly with no further info.
`If you would like to request further assistance, get more information or this article didn't address your issue, please reach out to us on our .`

Just pointing that out, looks like it wasn't completed before it was pushed live. Thanks!

**Comment by rebron** [comment]
We're exposing a way to detect Brave in #8216. Closing as duplicate.
