### ISSUE TITLE
Crypto Wallets add multiple tokens in Search Tab has 'next' button disabled

### ISSUE THREAD

**Issue by zirs3d** [brave/brave-browser#7669]
## Description
On Crypto Wallets, when adding multiple tokens in Search Tab, the "Next" Button is disabled.

## Steps to Reproduce
Open Crypto Wallets Account 1
Click "add tokens" to account button in side-bar
In Search Tab, for example search for "bat..."

After browsing the list of tokens in Search Tab
Selecting 1 or more tokens from the search list of tokens 
Click on "next" button to proceed.

## Actual result:
Not able to click on disabled "next" button to proceed.

## Expected result:
Clicking on "next" button to proceed to adding selected tokens from search bar listing
Source: https://metamask.zendesk.com/hc/en-us/articles/360015489031
![image](https://user-images.githubusercontent.com/46602939/72049005-06c46080-32f9-11ea-9bd0-b5e96e87d4b2.png)

## Reproduces how often:
Easily reproduced

## Brave version (brave://version info)
Brave: 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)
Revision: 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS: Windows 10 OS Version 1909 (Build 18363.535)

## Version/Channel Information:
Current release

## Other Additional Information:
Does the issue resolve itself when disabling Brave Shields?
nope
Does the issue resolve itself when disabling Brave Rewards?
nope
Is the issue reproducible on the latest version of Chrome?
nope

## Miscellaneous Information:

**Comment by srirambv** [comment]
Works fine for me. Could you possibly do a screen recording of your steps?

**Comment by bbondy** [comment]
This is working with the next release going out soon.

**Comment by srirambv** [comment]
This is working as expected
![tokens](https://user-images.githubusercontent.com/17010094/72186440-4a839c80-33c3-11ea-90ef-b860a2ac9cae.gif)
