### ISSUE TITLE
[Android] Port `Implement NTP images`

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#7670]
## Description 

Port https://github.com/brave/browser-android-tabs/issues/2176 into brave-core

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running custom x64 build
- Verified background SI update when campaign updates in the backend without having to restart the app
- Verified background SI is removed when a campaign ends without having to restart the app
- Verified migrating from tabs to android-core components upgrade correctly and SI is shown for an active campaign
- Verified for non-ads regions no SI is shown
- Verified for non-campaign regions no SI is shown 
- Verified landing pages work for on all SI
- Verified modal links work for ToS and PP
- Verified able to turn on rewards via SI modal 
- Verified able to turn off SI via modal immediately updates tab image to stock images
--------
Verification passed on Samsung Tab A with Android 9.0 running custom x64 build
- Verified background SI update when campaign updates in the backend without having to restart the app
- Verified background SI is removed when a campaign ends without having to restart the app
- Verified migrating from tabs to android-core components upgrade correctly and SI is shown for an active campaign
- Verified for non-ads regions no SI is shown
- Verified for non-campaign regions no SI is shown 
- Verified landing pages work for on all SI
- Verified modal links work for ToS and PP
- Verified able to turn on rewards via SI modal 
- Verified able to turn off SI via modal immediately updates tab image to stock images
