### ISSUE TITLE
Device frame not visible when activated in developer tools

### ISSUE THREAD

**Issue by vinkla** [brave/brave-browser#7671]
## Description 

The device frame in developer tools not visible when activated.

## Steps to Reproduce

1. Visit any website.
2. Open developer tools and toggle device toolbar.
3. Select device such as iPhone 6/7/8.
4. Open dropdown and select show device frame.

## Actual result:

![image](https://user-images.githubusercontent.com/499192/72065270-2c903c00-32de-11ea-9ca3-5a594bedef0c.png)

## Expected result:

There should be a device mockup/image around the viewport.

## Reproduces how often: 

Every time.

## Brave version (brave://version)

Brave | 1.2.41 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
OS | macOS Version 10.15.2 (Build 19C57)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

N/A

## Miscellaneous Information:

N/A

**Comment by rebron** [comment]
Expected result on Chrome.
<img width="726" alt="Screen Shot 2020-02-21 at 10 05 37 AM" src="https://user-images.githubusercontent.com/5951041/75059399-bad90f80-5491-11ea-816f-63e271770c4d.png">

**Comment by vinkla** [comment]
This is working in the latest version of Brave: 1.25.72

**Comment by joeyfigaro** [comment]
This issue has re-surfaced in `1.41.100 Chromium: 103.0.5060.134 (Official Build) (arm64)`

**Comment by SauelAlmonte** [comment]
When I choose show device frame nothing shows up, why? I am using chrome

**Comment by suther** [comment]
A real pain with this issue. When will it be solved finally?

**Comment by fanckush** [comment]
same issue in 2024..

**Comment by nagyalex** [comment]
Not sure if it fixes issue in Brave, but seems there is a workaround which worked for me: https://www.reddit.com/r/edge/comments/k94r0m/comment/i9mtws4/

Only for soem devices though (I tested with iPhone 5/SE).

**Comment by jmorallos** [comment]
still an issue September 2025 Brave
