### ISSUE TITLE
WebRTC connection in iframe is treated as a cross-site device recognition attempt

### ISSUE THREAD

**Issue by smithki** [brave/brave-browser#7674]
## Description 
I am not 100% sure, but this could be similar/related to #5374

If you have an application inside an iframe which uses a WebRTC connection to another page on that same domain, the WebRTC connection is blocked by shields as a "cross-site device recognition attempt"—even though the domains are the same. Here's my best attempt to illustrate the connection I'm trying to make:

```
+------------------------------+                +---------------------------+
|         example1.com         |                |                           | 
|                              |                |                           | 
|   +--iframe--------------+   |                |                           | 
|   | example2.com/receive |<~~|~~~~~WebRTC~~~~>|     example2.com/send     | 
|   +----------------------+   |                |                           | 
|                              |                |                           | 
+------------------------------+                +---------------------------+
```

## Steps to Reproduce

   1. Shields up!
   2. With an application containing the architecture above, attempt to make a WebRTC connection from `example2.com/send` to `example2.com/receive`. I was using [PeerJS](https://peerjs.com/) for this, but I doubt that makes a difference.

## Actual result:
WebRTC connection blocked
<img width="730" alt="Screen Shot 2020-01-09 at 9 51 29 AM" src="https://user-images.githubusercontent.com/22753882/72087425-a831bf00-32c5-11ea-9863-6b135bad9f27.png">

## Expected result:
WebRTC connection should be allowed because `example2.com/receive` is sandboxed within an iframe.

## Reproduces how often: 
Consistently with shields up (specifically with the "cross-site device recognition" fingerprinting protection).

## Brave version (brave://version info)

Brave | 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.15.2 (Build 19C57)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **Yes**
- Does the issue resolve itself when disabling Brave Rewards? **No**
- Is the issue reproducible on the latest version of Chrome? **No**

**Comment by pes10k** [comment]
Closing because we soon will no longer report anything in this field (bc of high false positive rates since enabling fingerprinting protections 1p post farbling)
