### ISSUE TITLE
Allow shields to whitelist an entire site, including subdomains

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#7680]
## Description 
Discussion on how to whitelist/adjust shields on all subdomains came up. So give the user an option to whitelist *.domain.com Currently shields is on a per-domain basis.

## Steps to Reproduce

   1. Turn off Shields on `logmein.com`
   2. Open new tab on `accounts.logmein.com`
   3. Expect Shields to be disabled on `accounts.logmein.com`

## Actual result:
Shields is enabled still, even though we turned it off on the main domain

## Expected result:
An option in Shields to allow whitelisting (or disable certain shield settings) for the entire site if the user wishes. Is use usefull if the subdomain is changing.

## Miscellaneous Information:

Discussion came from this:

https://www.reddit.com/r/brave_browser/comments/cmciur/how_do_i_whitelist_certain_pages_for_the_adblock/

I wouldn't make it default, but offering a shields option to whitelist an entire site might be useful. Not sure if CDN's will cause issues here?

**Comment by Brave-Matt** [comment]
Some additional reports:

- https://community.brave.com/t/shields-is-blocking-webgl-on-itch-io/81402
- https://community.brave.com/t/how-to-widen-scope-of-saved-site-exceptions/13715
- https://community.brave.com/t/cant-deny-all-and-whitelist-cookies-in-version-0-57-18/39166/2
- https://community.brave.com/t/bravew-shields-league-of-legends/78761
- https://community.brave.com/t/a-manually-edited-whitelist-of-sites/89953
- https://community.brave.com/t/testing-brave-shields/39899/3
- https://www.reddit.com/r/brave_browser/comments/bwt4sw/whitelist_with_wildcard/

Happy to find/add more if necessary.

**Comment by vortensis** [comment]
If anyone else is having problems with the LogMeIn remote control app and the "save credentials" button, I was able to fix that by disabling "Block cross-site trackers" globally in the shields section. Still, white-listing should be a pretty basic feature to any kind of ad-blocking.

**Comment by bsclifton** [comment]
Closing as a dupe of https://github.com/brave/brave-browser/issues/5290

Will edit that issue, as I think this title is better 😄

**Comment by Barrel-Cactus** [comment]
Answering the question about how to whitelist one site at a time on the Brave browser
- Simply click on Brave's shield icon while in the browser
- From there, go to (change global shield defaults) in the drop down menu (settings)
- Click on the drop down menu labeled (additional settings) and select (privacy and security.)
- Go to (Site And Shield Settings)
- Go to (view permissions and data stored across site)
- clicking on any of the sites listed should allow you to individually allow permissions that other sites will still not have
- I hope this finds you well and resolves the problems you have encountered
