### ISSUE TITLE
Removes foreign keys from rewards database

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#7682]
Based on https://github.com/brave/brave-browser/issues/7579 and talk with @bsclifton and @bbondy we decided to completely remove  foreign keys and keep it simple.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.5.106 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4354

Scenario 1:
   * Installed 1.0.0 and enabled Rewards
   * Restored a wallet with a balance
   * Viewed at least one ad, updated Ads panel settings
   * Set up AC table, had one AC go thru. Set up AC table again. Modified AC settings.
   * Set up recurring tip
   * Did a one time tip
   * Updated Tips panel settings
   * Set up pending tips to non-verified publishers
   * Updated to 1.5.x
   * Confirmed all data (settings updates, AC table, tips tables, pending tips, wallet balance, wallet summary items, etc) was intact

Scenario 2:
   * Installed 1.0.0 and enabled Rewards
   * Restored a wallet with a balance
   * Viewed at least one ad, updated Ads panel settings
   * Set up AC table, had one AC go thru. Set up AC table again. Toggled AC OFF.
   * Set up recurring tip
   * Did a one time tip
   * Updated Tips panel settings
   * Set up pending tips to non-verified publishers
   * Updated to 1.5.x
   * Confirmed all data (settings updates, tips tables, pending tips, wallet balance, wallet summary items, etc) was intact
   * Confirmed AC still toggled OFF
   * Confirmed AC did not occur (however recurring tip was contributed as expected)

Scenario 3:
   * Installed 1.0.0 and enabled Rewards
   * Toggle Ads OFF
   * Update to 1.5.x
   * Confirm Ads still toggled OFF

Scenario 4:
   * Installed 1.0.0 and enabled Rewards
   * Toggle Rewards OFF
   * Update to 1.5.x
   * Confirm Rewards still toggled OFF
