### ISSUE TITLE
crash when clicking on "Shows" under https://www.crunchyroll.com when shields enabled

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#7686]
## Description 

Brave will sometimes crash when you click on "Shows" at the top of https://www.crunchyroll.com.

## Steps to Reproduce

   1. install & download the latest android-core-releae from GPS (using `79.0.3945.88` in this case)
   2. visit https://www.crunchyroll.com/
   3. click on `View full site`
   4. once the desktop version loads, click on `Shows`

Repeat step **`#4`** a few times if you can't reproduce on the first attempt.

## Actual result:

Brave will eventually crash. Video example of the issue occurring: https://youtu.be/sPaUGrOm4NI

## Expected result:

Brave shouldn't be crashing when loading/using websites.

## Reproduces how often: 

Reproducible about ~60-70% of the time using the above STR.

## Brave version (brave://version info)

* Using the latest `Brave-Beta CR: 79.0.3945.88` (Unfortunately there isn't any versioning available)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Couldn't reproduce with android-tabs`
- Can you reproduce this issue with the beta channel? `Yes, reproducible as per the above`
- Can you reproduce this issue with the dev channel? `N/A`
- Can you reproduce this issue with the nightly channel? `N/A`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `Yes, can't seem to reproduce the issue once Shields have been disabled`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @SergeyZhukovsky @anthonypkeane @srirambv

**Comment by AlexeyBarabash** [comment]
Cannot reproduce both on GPS version or my local master build.

**Comment by AlexeyBarabash** [comment]
Tried on both my phones. Probably I cannot reproduce  because of other region of ads being blocked. 
So @kjozwiak could you please try it when we will have a new build. Maybe https://github.com/brave/brave-core/pull/4418 will help.

**Comment by kjozwiak** [comment]
Couldn't reproduce the issue using on `Samsung S10+` running `Android 10` using the following build:

```
Brave Beta - 1.5.59 CR:  79.0.3945.130
```
I went through the original STR mentioned via https://github.com/brave/brave-browser/issues/7686#issue-547858962 and couldn't reproduce the crash after trying for ~10mins.

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm1.5.110.apk`
