### ISSUE TITLE
Windows Security modal appears/disappears several times mentioning MM when connecting to Nano Ledger

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#7687]
## Description 

When connecting to the `Nano Ledger` on Windows, you'll get a modal from `Windows Security` appearing/disappearing several times before CW connects to the `Nano Ledger`. Example:

![Untitled](https://user-images.githubusercontent.com/2602313/72131773-3c923500-334b-11ea-9623-44ad5def005b.png)

This also happens with the current CW release.

## Steps to Reproduce

   1. launch `1.5.22 CW: 79.0.3945.117` and load `brave://wallet`
   2. click on `I understand` on the `Welcome to Brave Crypto Wallets` modal
   3. create a new wallet and skip the `Secret Backup Phrase` verification via `Remind me later`
   4. make sure you have a nano ledger connected and select `Connect Hardware Wallet`

You'll notice the `Windows Security` modal when you go through the steps to connect the `Ledger`

## Actual result:

![CW](https://user-images.githubusercontent.com/2602313/72132044-f9849180-334b-11ea-917e-28aac088309d.gif)

## Expected result:

Shouldn't be receiving the `Windows Security` modal. If it's something new Windows implemented, it should appear once rather than being spammed multiple times.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)
--- | ---
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Windows 10 OS Version 1909 (Build 18363.535)
Component | `0.1.36` via https://github.com/brave/ethereum-remote-client/releases/tag/0.1.36

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @rebron @ryanml @srirambv

**Comment by srirambv** [comment]
Reproduced it on Windows 10 VM but not on the device
![image](https://user-images.githubusercontent.com/17010094/72153431-ea1d3c80-337b-11ea-8c5e-741bd4e23c9e.png)
Issue happens on MM as well so this is not wallet related but OS related
![image](https://user-images.githubusercontent.com/17010094/72153493-28b2f700-337c-11ea-9539-440c81543736.png)

Am not sure if this is something that we can avoid or have it fixed. Something at OS level

**Comment by bbondy** [comment]
@danfinlay this also happens in MetaMask, do you know more about this?

**Comment by kjozwiak** [comment]
Seems like this is still happening and it's due to a Windows update. There's a "workaround" via https://support.ledger.com/hc/en-us/articles/360023190873-Fix-for-Windows-10-security-popup but I couldn't get it to work on my machine. It keeps interrupting the transactions making it very difficult to use on Windows.

There's also a blog post as per https://www.ledger.com/your-ledger-device-and-the-upcoming-windows-10-update/.

@bbondy should we close this off or keep it opened so users have some info if they run into the above? Either way works. Leaving it opened probably a better idea.

**Comment by ryanml** [comment]
@srirambv @kjozwiak - just curious, can you guys check this out on the latest release? Thanks

**Comment by srirambv** [comment]
This seems to be still an issue even on the dev component 1.0.25
![image](https://user-images.githubusercontent.com/17010094/110323652-cb144c00-800c-11eb-99c4-8921c9bfaad2.png)

It keeps popping up a few times and then connects the H/W wallet.

**Comment by srirambv** [comment]
This is fixed by https://github.com/brave/ethereum-remote-client/pull/243 and verified on `1.0.30 dev` component. Verified it while going through https://github.com/brave/brave-browser/issues/16481#issuecomment-865890608
