### ISSUE TITLE
Settings page in private window doesn't show buttons properly

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#7689]
## Description 

Menu button is not visible when light mode.

## Steps to Reproduce

   1.  Open private window and load brave://downloads/
   2. change to light mode
 

## Actual result:

![image](https://user-images.githubusercontent.com/6786187/72138221-bcfa7980-33cf-11ea-9e8e-bf1f61abb723.png)

## Expected result:
Buttons should be visible easily

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Version 1.2.41 Chromium: 79.0.3945.88 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@simonhong I followed the steps. This look like it works properly now in 1.4.x. Can you check with latest RC (1.4.93 or latest)

**Comment by simonhong** [comment]
@rebron Yes, I also can't see any issue with latest RC(1.4.94) and other channels. Closed.
