### ISSUE TITLE
Follow up of #6755 - Grant notification is not dismissed from NTP rewards widget after claiming it from brave://rewards or Rewards Panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7690]
## Description 

Follow up of #6755 - Grant notification is not dismissed from NTP rewards widget after claiming it from brave://rewards or Rewards Panel

## Steps to Reproduce

Case 1: Claim grants from Panel

   1. Clean profile 1.3.87 staging environment
   2. Enable rewards and claim grants from BR panel
   3. Navigate to brave://rewards settings page to see claimed grants display
   4. Open a new tab
   5. Claim grants notification isn't dismissed from NTP rewards widget 

Case 2: Claim grants from brave://rewards page

   1. Clean profile 1.3.87 staging environment
   2. Enable rewards
   3. Click on Hamburger menu and select `Brave Rewards` 
   4. Claim grants from brave://rewards settings page
   5. Open a new tab
   6. Claim grants notification isn't dismissed from NTP rewards widget 

## Actual result:

![6755](https://user-images.githubusercontent.com/38657976/72145454-9123c780-33c0-11ea-8a51-690279212e37.gif)

Grant notification is not dismissed from NTP rewards widget after claiming it from brave://rewards or Rewards Panel

## Expected result:
Grant notification should be dismissed from NTP rewards widget after claiming it from brave://rewards or Rewards Panel

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.3.87 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Not sure
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron

**Comment by kjozwiak** [comment]
Reproduce on `macOS 10.15.2 x64` using the following build:

Brave | 1.3.91 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.15.2 (Build 19C57)

Example of the issue occurring on `macOS`:

![grantsClaiming](https://user-images.githubusercontent.com/2602313/72388369-baf82980-36f3-11ea-9f91-0fa251c4a0a8.gif)

**Comment by rebron** [comment]
Is this still an issue on 1.5.62?

**Comment by btlechowski** [comment]
Reproduced on 1.5.62

Brave | 1.5.62 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

![image](https://user-images.githubusercontent.com/34715963/73219982-a426ed80-415d-11ea-84f8-9370918a93ad.png)

**Comment by GeetaSarvadnya** [comment]
@Miyayes Verified the issue against the build `1.42.86` and the issue is not reproducible anymore. Hence closing the issue.
