### ISSUE TITLE
Sync changes of move bookmarks are not reflected

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#7691]
## Description 

Found while looking on https://github.com/brave/brave-core/pull/4324 . Move operation right after the chain creation is not reflected .

## Steps to Reproduce

1. Add A1.com and A2.com on device A before sync chain creation
2. Create sync chain on device A and connect device B
3. A1.com and A2.com should appear on device B instantly
4. Add folder A on device A
5. Move A1.com and A2.com into folder A
6. On device B changes are not reflected; sometimes on deviceA one bookmark is moved back to Bookmarks folder.

## Expected result:
6. Changes should be reflected on device B 

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? On Stable 1.2.42 - no
- Can you reproduce this issue with the beta channel? On Beta 1.3.87 - yes 
- Can you reproduce this issue with the dev channel? On Dev 1.4.55 - yes
- Can you reproduce this issue with the nightly channel? On Nightly 1.5.21 - yes 

## Other Additional Information:
According to logs deviceB gets CREATE A1, CREATE A2, UPDATE A1, UPDATE A2, which resolves to empty changes list.

**Comment by ggirard07** [comment]
Same issue here while doing the bookmark move from my Android device. The change does not reflect on either of my Windows instances.

**Comment by bavalpey** [comment]
Have been having this issue with brave for an incredibly long time.  The 'sync' option may as well not exist, since it doesn't sync passwords and the bookmark sync is almost completely broken.
Should disable the feature until it works as expected.

**Comment by asolopovas** [comment]
in my case, I went throw all my bookmarks sorted them, remove unnecessary ones spend couple of hours going through more than 200 bookmarks, The next day I open the browser and it completely synced it with older versions from other devices. Lovely project but sad that sync is totally useless.
