### ISSUE TITLE
Does the chrome.identity api work in chrome extensions in brave?

### ISSUE THREAD

**Issue by ZYinMD** [brave/brave-browser#7693]
## Description 
I'm a chrome extension developer. In my extension I call `chrome.identity.getAuthToken()` to do oAuth, this normally pops up a sign-in window in Chrome. The identity API is what made oAuth possible in extensions. However, in Brave, the popup doesn't appear, and in the console it shows `Unchecked runtime.lastError: The user turned off browser signin`.

So is `chrome.identity` supported in Brave?

## Steps to Reproduce

   1. call `chrome.identity.getAuthToken()` in an extension. (if you want to try with an existing extension, try the extension "Full Screen for Google Tasks".

## Actual result:

No oAuth window appears. In the console it shows `Unchecked runtime.lastError: The user turned off browser signin`.

## Expected result:

oAuth window appears.

## Brave version (brave://version info)

Brave | 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Windows 10 OS Version 1903 (Build 18362.295)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by bsclifton** [comment]
@ZYinMD I believe this is expected behavior, as we do disable browser sign in. Any calls made to GAIA are non-routable

@jumde can you confirm?

cc: @pilgrim-brave @tomlowenthal

**Comment by pilgrim-brave** [comment]
Confirmed. GAIA is unavailable in Brave in any context.

**Comment by ZYinMD** [comment]
Thanks!

**Comment by jamesturnernz** [comment]
Hi, just wondering if there is an alternative please?

If I can't use GAIA chrome.identity.getAuthToken() in my extension, but still want to offer Google Auth, how can I do this please?

Thanks

**Comment by bsclifton** [comment]
Quick update - @jumde is looking at getting some of this functionality working in Brave (put behind a flag of course)

**Comment by ss87codes** [comment]
@jumde @bsclifton any update on this pls? We are looking to provide Google Auth via chrome extn on brave.

**Comment by jumde** [comment]
Hi @ss87codes - You should be able to use this api by enabling `Allow Google login for extensions` in `brave://settings/extensions`. If you are running into any issues, let us know.

**Comment by ss87codes** [comment]
Thank you @jumde

**Comment by kospl** [comment]
@jumde I have enabled Google sign in
![image](https://user-images.githubusercontent.com/26386660/107887511-5703ee00-6f0f-11eb-90fa-8fb4fe80efe7.png)
but each time extension calls `chrome.identity.getAuthToken`, browser asks me reauthenticate with my Google email and password. Even after this I am getting 
> The user is not signed in.
error. 

How can I get this working?

**Comment by jumde** [comment]
@kospl - We noticed an issue in the recent builds a few days back: https://github.com/brave/brave-browser/issues/14041 - we are working on a fix.

**Comment by jumde** [comment]
@MoeBazziGIT - Update here: https://github.com/brave/brave-browser/issues/15754#issuecomment-920514585

We haven't found any extensions where `chrome.identity` API is used with 3p Google APIs. So we've paused the work here: https://github.com/brave/brave-core/pull/10103

**Comment by dcow** [comment]
> @MoeBazziGIT - Update here: [#15754 (comment)](https://github.com/brave/brave-browser/issues/15754#issuecomment-920514585)
> 
> We haven't found any extensions where `chrome.identity` API is used with 3p Google APIs. So we've paused the work here: [brave/brave-core#10103](https://github.com/brave/brave-core/pull/10103)

Writing in to let you know that our browser extension does use other oauth scopes with the identity api. We request gmail.readonly and gmail.modify and have been approved by Google.

**Comment by bsclifton** [comment]
cc: @ShivanKaul

**Comment by dcow** [comment]
@bsclifton neat I'll test our extension out on Brave. Came across this thread in a discussion with another chrome-embedder's team about supporting the identity api and it wasn't clear what the resolution was here. Thanks for the update!

**Comment by zereraz** [comment]
I have extension working in chrome using `chrome.identity.getAuthToken` specifically https://developer.chrome.com/docs/extensions/how-to/integrate/oauth case but when I call it in Brave I get

`Access blocked: <Name> request is invalid.`
```
Error 400: invalid_request
Custom URI scheme is not supported on Chrome apps.
```
Is this not supported?

**Comment by jacekzlowocki** [comment]
Hi!
Have the same problem as @zereraz here. 

We are using Chrome Identity API in our extension (`chrome.identity.getAuthToken()`), but Brave seem to still send redirect URL with the custom URI scheme, which is no longer supported by Google

The "Allow Google login in extensions" setting doesn't make any difference

You can replicate with our [Meeting Timer for Google Meet](https://chromewebstore.google.com/detail/meeting-timer-for-google/kgnglpankjpapbedabaccgimldphaehf) extension

Please consider reopening the issue

<img width="1110" alt="Zrzut ekranu 2024-05-4 o 18 31 37" src="https://github.com/brave/brave-browser/assets/4518168/67eb8766-dcea-4fa5-80a7-2e8175706b9c">

**Comment by kunal-mansukhani** [comment]
Yes, please reopen the issue. Having the same problem

**Comment by bsclifton** [comment]
Just to recap this issue real quick:
By design, the 1st party sign in will never work unless you use Chrome (ex: what is used w/ Google Keep). What we've pulled into Brave with https://github.com/brave/brave-core/pull/14069 is a 3rd party sign in, recommended in Chromium with https://chromium-review.googlesource.com/c/chromium/src/+/2704571. We just did a simple test with an extension to make sure it worked but don't actively have any code using it.

We should make a new issue describing the new problem. I can help with that - just need help narrowing down the issue.

Sounds like basically extensions trying to do 3rd party authentication in Brave are getting a 400 error.

In our code, specifically in `IdentityGetAuthTokenFunction::StartWebAuthFlow` the call is made out to `https://accounts.google.com/o/oauth2/v2/auth` with parameters `client_id`, `redirect_uri`, `token`, and `scope`. Per @jacekzlowocki, it seems the `redirect_uri` param is no longer supported.

I'll see if I can find more information about this API

When it comes time to solve this issue, the patch (as written in https://github.com/brave/brave-core/pull/14069) has been reworked and you can see the logic here:
https://github.com/brave/brave-core/blob/master/chromium_src/chrome/browser/extensions/api/identity/identity_get_auth_token_function.cc

Which calls into `StartWebAuthFlow` here:
https://github.com/brave/brave-core/blob/master/browser/extensions/api/identity/brave_web_auth_flow.cc

**Comment by bsclifton** [comment]
OK I think I understand the issue. When looking at https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow#handlingresponse

The `redirect_uri` param is supported. However, it seems custom URI support was dropped. There's a note:

> Note : Custom URI schemes are no longer supported on Chrome apps and are disabled by default on Android. [Learn more](https://developers.google.com/identity/protocols/oauth2/native-app#redirect-uri_custom-scheme) about custom scheme alternatives for Android and Chrome apps.

Following that `Learn more` link, there's another note:

> Important: Custom URI schemes are no longer supported on new Chrome apps and are disabled by default on new Android clients due to the risk of app impersonation.

We're not going to change this behavior in Brave - especially given the concern shared. However, the page does seem to have some alternatives to try. One of them mentions:

> Use the [Chrome Identity API](https://developer.chrome.com/docs/extensions/mv3/tut_oauth/) which delivers the OAuth 2.0 response directly to your app, eliminating the need for a redirect URI.

The `redirect_uri` param is required and it seems the default value we assign might be causing a problem. Here's the pertinent part of our code:

```cpp
std::vector<std::string> client_id_components = base::SplitString(
      oauth2_client_id, ".", base::TRIM_WHITESPACE, base::SPLIT_WANT_NONEMPTY);
std::reverse(client_id_components.begin(), client_id_components.end());
GURL redirect_url = GURL(base::JoinString(client_id_components, ".") + ":/");
```

Using the example client ID from [Google's OAuth 2.0 extension docs](https://developer.chrome.com/docs/extensions/how-to/integrate/oauth) `yourExtensionOAuthClientIDWillGoHere.apps.googleusercontent.com`. Our code above will do a split on this and put into an array. 

For example (in JSON):

```json
[
  "yourExtensionOAuthClientIDWillGoHere",
  "apps",
  "googleusercontent",
  "com"
]
```

This is then reversed and a new string is created (with `:/` appended) which would be:
`com.googleusercontent.apps.yourExtensionOAuthClientIDWillGoHere:/`

I guess we'd need to know what this value should be? If it's not supposed to be this. The Google docs do say:

> If this value doesn't match an authorized redirect URI for the provided client_id you will get a redirect_uri_mismatch error.

Does the Google API console show what `redirect_uri` is supposed to be? Knowing that would help

**Comment by phalgun** [comment]
Was there ever a fix for this? I have been trying to use chrome.identity.getAuthToken() in my browser extension which works on Brave and it still doesn't work.

**Comment by bsclifton** [comment]
@phalgun only 3rd party auth would work. And as you can see above, there have been issues with custom URI support.

Google ultimately owns the authentication mechanism. Does your extension work in other non-Chrome browsers? (ex: MS Edge or Opera)

**Comment by phalgun** [comment]
hi @bsclifton yes, my extension is working on MS Edge on Mac. 

I understand browsers like Brave & Arc do not support chrome.identity.getAuthToken() because of how Google has designed it. 

I'm contemplating switching between .getAuthToken() and .launchWebAuthFlow() based on which browser the user is on. 

Is there a way to detect if .getAuthToken() works in the browser the user is currently on? 

I cannot even use the user agent or window.navigator objects to detect if the browser is Brave, as authentication runs on the background page of the extension where `chrome.window` does not exist.
