### ISSUE TITLE
disconnected uphold doesn't reflect

### ISSUE THREAD

**Issue by madhums** [brave/brave-browser#7699]
Hi, I have closed my uphold account, when I go to brave rewards, I don't get an option to remove the connection. It still says "disconnected". Shouldn't this say "Connect" and remove the previously connected connection?

<img width="373" alt="Screenshot 2020-01-11 at 00 06 43" src="https://user-images.githubusercontent.com/123815/72192615-b2a7a200-3406-11ea-83ef-b8047458ea1e.png">

**Comment by NejcZdovc** [comment]
Disconnected just indicates that you had previously connected a wallet. If you click on it you will be able to connect again.

cc @mandar-brave @jenn-rhim @alexwykoff for additional comments
