### ISSUE TITLE
[ win10 ] Small lion/shield site-level settings icon scaling 

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#770]
## Description 

On win10 x64, the scale of the brave lion icon for the site-level shield settings is very small. 

The block count that displays over the lion icon is larger than `browser-laptop`. 

This combination is causing the lion icon to become less distinguishable. 

The combo we have for `browser-laptop` has great proportions. May be difficult for us to match exactly, but worth exploring if we aren't already. 

Comparison: 
`browser-laptop`
![brave-browser-laptop-shield-icon-08182018](https://user-images.githubusercontent.com/8979240/44301439-8815f000-a2cb-11e8-9d95-4fe1ea5fe56f.PNG)

`brave-browser`
![brave-core-shield-icon-08182018](https://user-images.githubusercontent.com/8979240/44301440-9106c180-a2cb-11e8-9e12-358f44b81389.PNG)

full screen width comparison
`browser-laptop`
![brave-browser-laptop-shield-icon-full-width-08182018](https://user-images.githubusercontent.com/8979240/44301474-65d0a200-a2cc-11e8-9719-84678f5908fa.PNG)

`brave-browser`
![brave-core-shield-icon-full-width-08182018](https://user-images.githubusercontent.com/8979240/44301479-73862780-a2cc-11e8-83f0-fad192254a27.PNG)

## Steps to Reproduce

   1. open browser-laptop
   2. open brave-browser
   3. compare

## Brave version (about:brave info) 

```
Brave is up to date
Version 0.54.0 Chromium: 69.0.3497.32 (Official Build) dev (64-bit)
```

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bbondy** [comment]
Thanks for posting @lukemulks this one will be handled within the context of this one though:
https://github.com/brave/brave-browser/issues/668.  Given that I'm going to close this in favour of #668.
