### ISSUE TITLE
Brave browser can't show the words while typing in terminal of CS50 online IDE

### ISSUE THREAD

**Issue by ydcjeff** [brave/brave-browser#7702]
## Description 

Brave can't show the words I typed in the terminal of the CS50 online IDE.
I tried opening another terminal window and it didn't show up either.
So, I tried Firefox and Chrome and it works well.

Is it the Brave bug?

On Brave:
![Screen Shot 2020-01-11 at 18 55 52](https://user-images.githubusercontent.com/32727188/72204342-1385b780-34a5-11ea-9cf2-fa29b0329845.png)

On Chrome:
![Screen Shot 2020-01-11 at 18 56 14](https://user-images.githubusercontent.com/32727188/72204343-1385b780-34a5-11ea-86cf-52808db098fd.png)

Thank you!

**Comment by zezkin** [comment]
Same here

**Comment by zezkin** [comment]
Hey, just disable the shield and it will works perfectly.

**Comment by rebron** [comment]
@ydcjeff We don't have a way to reproduce or test this. It sounds like disabling shields work here.
