### ISSUE TITLE
Some words in Greek language looks "cutted" in download box.

### ISSUE THREAD

**Issue by giwrgosmant** [brave/brave-browser#7705]
Some words in Greek language looks "cutted" while downloading in bottom "download box". Seems it needs better calibration.
![2020-01-12 19_19_27-Ρυθμίσεις](https://user-images.githubusercontent.com/51835189/72222929-a93b4880-3572-11ea-82c4-7cda6bbaab1b.png)
![2020-01-12 19_36_18-](https://user-images.githubusercontent.com/51835189/72222958-e30c4f00-3572-11ea-9371-d2694a53e683.png)

**Comment by rebron** [comment]
@giwrgosmant What version are you running? Can you follow the template also when filing issues? Thanks.

**Comment by giwrgosmant** [comment]
> @giwrgosmant What version are you running? Can you follow the template also when filing issues? Thanks.

Hello,

I am running always the latest version. 
Sorry about the template filing, I thought via screenshots is more easy to understand the issue.
Atm I don't have access to my PC since I am not in my hometown and I will not be for few months, so I can't give more infos atm.
I will reply back when I go back and I will check if the issue still exists.

Thanks.

**Comment by giwrgosmant** [comment]
I am back on my PC after long time.
I've tested the latest version of Brave and problem seems to be fixed.
![2020-05-06 09_18_09-](https://user-images.githubusercontent.com/51835189/81147818-c366bf80-8f83-11ea-9a0b-f6bc17f857c0.png)
Keep it up!👍
