### ISSUE TITLE
Option to disable reader mode / simplified view

### ISSUE THREAD

**Issue by oshanz** [brave/brave-browser#7708]
## Description 

In android brave app "show simplified view" is so annoying and useless to me.
I'll attach screenshot how bad it is.

So I used to disable that from chrome flages. Using the setting reader mode.
```
chrome://flags/#enable-reader-mode
```
But I update to latest brave and now again I can see that bar popping.
And chrome 79 seems remove that option to disable reader mode.
Please give and option to disable show simplified view button.

![Screenshot_20200113-075505](https://user-images.githubusercontent.com/5364479/72233398-f80ecf80-35be-11ea-8ebc-2e6a698095b4.png)
![Screenshot_20200113-075440](https://user-images.githubusercontent.com/5364479/72233405-ff35dd80-35be-11ea-8b91-a91a48db5bd6.png)

## Brave version (brave://version info)

Brave | 1.6.2 chrome: 79.0.3945.93 (Official Build) (32-bit)
-- | --
OS | Android 7.1.1; SM-J510FN Build/NMF26X

**Comment by oshanz** [comment]
I'm using brave 1.7.0 and I can't find the issue anymore

**Comment by oshanz** [comment]
ok Its not fixed. I found this on some webpages again today.

* https://www.healthline.com/health-news/high-tempo-music-may-help-your-workout
* https://pradeeploganathan.com/architecture/event-driven-architecture/

**Comment by bsclifton** [comment]
@oshanz we have upgraded code-bases; if you get the latest version this should not be a problem anymore. Please try it and let us know 😄
