### ISSUE TITLE
entire a-c not going through due to missing delays

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#7709]
## Description 

The entire a-c amount not going through because it's being blocked server side due to missing delays.

Example:

* received `2.5 BAT` from ad grant
* received `17.5 BAT` from UGP grant
* Total BAT: `20 BAT`
* a-c setup as `Up to 15 BAT` via `brave://settings`

Only `8 BAT` went through rather than the `15 BAT`

Created issues for iOS & Android:

* iOS - https://github.com/brave/brave-ios/issues/2200
* Android - https://github.com/brave/browser-android-tabs/issues/2442

## Steps to Reproduce

**`Case #1`**

* launch Brave using `--enable-logging=stderr --rewards=staging=true,reconcile-interval=5`
* set `Monthly Payment` to `10 BAT` (should be already selected as the default)
* accept the UGP grant
* spend ~1.5mins on https://duckduckgo.com/ and ensure it's being displayed in the a-c table
* spend ~1.5mins on https://laurenwags.github.io/ and ensure it's being displayed in the a-c table
* spend ~1.5mins on https://yachtcaptain23.github.io and ensure it's being displayed in the a-c table
* ensure that a-c goes through and the correct amount is deducted from the total
* ensured that the correct amount of BAT has been deducted from Brave

**`Case #2`**

* https://github.com/brave/brave-browser/issues/7709#issuecomment-573787104

#### `Using UGP without any ad grants:`

![Screen Shot 2020-01-13 at 12 00 56 AM](https://user-images.githubusercontent.com/2602313/72239608-8713eb80-35af-11ea-8ae4-780899937090.png)

#### `Using UGP without any ad grants:`

<img width="417" alt="Screen Shot 2020-01-12 at 11 35 59 PM" src="https://user-images.githubusercontent.com/2602313/72239633-9e52d900-35af-11ea-99a8-a07e3831b81f.png">

## Expected result:

If the user has the required funds, the entire a-c should go through.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 1.5.27 Chromium: 79.0.3945.117 (Official Build) nightly (64-bit)
--- | ---
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.15.2 (Build 19C57

Brave | 1.3.89 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.15.2 (Build 19C57)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Couldn't reproduce with 1.2.42 CR: 79.0.3945.117`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @brave/legacy_qa @evq @NejcZdovc @rebron @mandar-brave

**Comment by kjozwiak** [comment]
Labeling as `release/blocking` for now till @evq and @NejcZdovc investigate.

**Comment by LaurenWags** [comment]
This should also be checked in conjunction with AC and a monthly tip (monthly contribution). So something like:
* launch Brave using `--enable-logging=stderr --rewards=staging=true,reconcile-interval=5`
* set `Monthly Payment` to `10 BAT` (should be already selected as the default)
* accept the UGP grant
* set up a monthly tip for a site like 3zsistemi.si, confirm it is shown on Monthly Contributions panel on brave://rewards
* spend ~1.5mins on https://duckduckgo.com/ and ensure it's being displayed in the a-c table
* spend ~1.5mins on https://laurenwags.github.io/ and ensure it's being displayed in the a-c table
* spend ~1.5mins on https://yachtcaptain23.github.io and ensure it's being displayed in the a-c table
* ensure monthly tip goes thru and correct amount is deducted from the total
* ensure that a-c goes through and the correct amount is deducted from the total

**Comment by LaurenWags** [comment]
@GeetaSarvadnya also ran into the following scenario, which sounds related to this issue and should be retested once this issue is resolved:
1. Clean profile with 1.2.x, launch with staging parameters & quick reconcile
2. Set up data for AC, but before AC occurs upgrade to 1.3.x
--> After upgrade AC is not occurring but wallet balance is being reduced

@GeetaSarvadnya please update this scenario with any additional relevant details so we can retest once this issue is resolved 👍

**Comment by GeetaSarvadnya** [comment]
AC and monthly Tip values are not reflected in Panel/Summary/NTP widget after the auto contribution

Case 1: 
1. Clean profile 1.2.39 - launch brave with staging flag and short reconcile interval
2. Claim UGP grants
3. Set monthly Tip for https://duckduckgo.com/
4. Send a one-time tip to https://duckduckgo.com/
5. Before the auto contribution upgrade profile to 1.3.91
6. Wait until auto contribution completes

Actual: 
- AC is going through and correct balance getting deducted but it's not shown in panel or summary or NTP widget
- Monthly tip is processing and the correct amount is deducted but the monthly tip isn't shown in panel or summary or NTP widget
- There is no AC notification
- AC table is getting cleared only after brave://rewards page reload

**Comment by LaurenWags** [comment]
reproduced https://github.com/brave/brave-browser/issues/7709#issuecomment-574223737 on macOS 


Brave | 1.3.91 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.14.6 (Build 18G103)

@NejcZdovc will the fix for this issue also address @GeetaSarvadnya finding that the summary (panel and on brave://rewards) is not reflecting the Auto-Contribute and Monthly Contribution amounts? For example, in the below image, the AC and Monthly Contribution amounts were from 1.2.39. When I upgraded to 1.3.91 and AC occurred again, the AC and Monthly Contribution amounts should have increased (5--> 10 and 1--> 2), however they did not. 

Please let us know if this should be logged separately.

cc @kjozwiak

**Comment by NejcZdovc** [comment]
@LaurenWags if I understand correctly just UI is not updated, but everything else works as expected?

**Comment by NejcZdovc** [comment]
could be this issue https://github.com/brave/brave-browser/issues/7526?

**Comment by LaurenWags** [comment]
I think so. will add comment on that issue as well. thanks @NejcZdovc !

**Comment by GeetaSarvadnya** [comment]
One-time tips are not shown in the Tips panel.

Case 1: https://github.com/brave/brave-browser/issues/7608#issuecomment-571646553

Case 2: 
1. Clean profile 1.3.94 - launch Brave using --enable-logging=stderr --rewards=staging=true
2. Restore Ads grants
3. Claim Ads grants
4. Claim UGP grants
5. Open  https://duckduckgo.com/
6. Send a one-time tip of 1 BAT to DDG
7. One-time is not displayed under Tips panel reload brave://rewards multiple times didn't help

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.3.108 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

* Verified test plans from https://github.com/brave/brave-core/pull/4372
Test Plan 1:
<img width="759" alt="7709-PR-TestPlan1" src="https://user-images.githubusercontent.com/28145373/73690406-48e58580-469e-11ea-9cd6-5193ee7e04a6.png">

Test Plan 2:
<img width="663" alt="7709-PR-TestPlan2-pt1" src="https://user-images.githubusercontent.com/28145373/73690411-4c790c80-469e-11ea-8d4e-982d8af3579a.png">
<img width="428" alt="7709-PR-TestPlan2-pt2" src="https://user-images.githubusercontent.com/28145373/73690413-4e42d000-469e-11ea-953b-56c60610c4aa.png">

* Verified Case 1 from description:
<img width="715" alt="7709-case1" src="https://user-images.githubusercontent.com/28145373/73690431-5569de00-469e-11ea-8a42-c9952cace2f8.png">

* Verified Case 2 from description:
<img width="712" alt="7709-case2" src="https://user-images.githubusercontent.com/28145373/73690442-5bf85580-469e-11ea-8df6-781d8e66eca1.png">

* Verified example from description:
<img width="750" alt="7709-example case" src="https://user-images.githubusercontent.com/28145373/73690461-6286cd00-469e-11ea-8b07-18fe040cf170.png">

Additional testing notes can be found here: 
   - https://github.com/brave/brave-browser/issues/6078#issuecomment-580958330
   - https://github.com/brave/brave-browser/issues/6942#issuecomment-580930621
   - https://github.com/brave/brave-browser/issues/7526#issuecomment-580931129
