### ISSUE TITLE
Shields extra padding show up when clicked on blocked count

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#771]
## Description 
As a follow up to #222 

## Steps to Reproduce

   1. Build from master
   2. Open any page with blocked count
   3. Click on blocked item in shields to expand view, shields panel expands and shows extra padding
   4. No extra padding shown when the block item is collapsed

## Actual result:
![shields](https://user-images.githubusercontent.com/17010094/44303115-77cf3680-a306-11e8-9fff-63660ad39092.gif)

## Expected result:
Should not show extra padding irrespective of expanding the blocked item view

## Reproduces how often: 
100%

## Brave version (about:brave info) 

Brave | 0.55.1 Chromium: 69.0.3497.42 (Official Build) (64-bit)
-- | --
Revision | 9c4613c66dfeb2b76ef6dd4b15884c15db3b4969-refs/branch-heads/3497@{#655}
OS | Windows
JavaScript | V8 6.9.427.14
Flash | (Disabled)

### Reproducible on current release:

No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
cc: @lukemulks based on https://github.com/brave/brave-browser/issues/222#issuecomment-414072256

**Comment by btlechowski** [comment]
Extra padding in not shown even when clicked on blocked element
![222_pass](https://user-images.githubusercontent.com/34715963/45879605-6e256c80-bda5-11e8-82d0-41c936488d0a.gif)

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

**Comment by cezaraugusto** [comment]
@srirambv per @btlechowski last screenshot this seems to be solved. is this still an issue?

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.56.8 Chromium: 70.0.3538.77 (Official Build) (64-bit)
-- | --
Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}
OS | Mac OS X

* Verified shields design is updated and when expanding blocked items with new shields design, extra padding is not displayed.

**Comment by kjozwiak** [comment]
Because this was fixed with the new shield design, labelling this as `release-notes/exclude`. https://github.com/brave/brave-browser/issues/1339 will cover the new shield design in the release notes.
