### ISSUE TITLE
Changing scope for Uphold

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#7713]
As a future plan to support add-funds to Uphold user wallets via top-up, and eventually monthly subscribed top-ups, we need to ask user authorization for new scopes (manifest changes) when we authenticate against Uphold.

This feature will allow us;
- to be authorized to take a credit card and fund user wallet
- and directly transfer BAT to the user wallet 

Feature to support future payments projects and subscription projects requires this change. Since re-auth is 90 days, it would be good to get the manifest change in as early as possible.

cc @NejcZdovc @rebron @jumde @evq

**Comment by kjozwiak** [comment]
Both https://github.com/brave/brave-core/pull/4409 and https://github.com/brave/brave-core/pull/4410 and have been uplifted. This should be available for QA in the next build.

**Comment by LaurenWags** [comment]
Needs fixes from https://github.com/brave/brave-core/pull/4372 uplifted to fully test this per https://github.com/brave/brave-core/pull/4379#issuecomment-578190490. Once those are uplifted this can be retested.

**Comment by LaurenWags** [comment]
Verified passed using

Brave | 1.3.106 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

* Verified test plan from https://github.com/brave/brave-core/pull/4379
* Verified testing done in https://github.com/brave/brave-core/pull/4379#issuecomment-578190490
<img width="775" alt="KYC-panelsummary" src="https://user-images.githubusercontent.com/28145373/73663461-9bf21500-466b-11ea-984a-7d34f58b4825.png">
<img width="661" alt="KYC-tippanels" src="https://user-images.githubusercontent.com/28145373/73663486-a3192300-466b-11ea-8c73-859274bcf7f6.png">
<img width="665" alt="KYC-contrib_info-table" src="https://user-images.githubusercontent.com/28145373/73663468-9e546f00-466b-11ea-83de-8fa7909f98e9.png">
<img width="482" alt="KYC-contrib_info_pub-table" src="https://user-images.githubusercontent.com/28145373/73663474-9f859c00-466b-11ea-91c3-97078e2464b3.png">

* See Scenario 5 & 7 from https://github.com/brave/brave-browser/issues/6078#issuecomment-580958330 for details on additional testing done with KYC'd Uphold wallets
* Encountered #7999 for connected, non-KYC'd wallet issues with Uphold wallets
