### ISSUE TITLE
Soundcloud sound stats don't work with Brave Shields

### ISSUE THREAD

**Issue by jjech** [brave/brave-browser#7714]
## Description 
Soundcloud (http://www.soundcloud.com) is an online music playback and hosting service. Normally, when a listener plays a song, the song's stats will be updated. However, if the playback is via Brave browser with Brave Shields enabled, the song's stats are not updated.

## Steps to Reproduce
*Requirement: Brave Shields must be enabled.*
   1. Play a song on Soundcloud for 5 or more seconds.
   2. Observe that the play count for the song has incremented by 1.
   3. Refresh the page. The play count reverts to its original value prior to playback.

*Note: the ideal song for reproduction should have a low play count and a small number of active listeners. If another listener who doesn't have Brave Shields enabled happens to play the same song during the small window of the reproduction procedure, that user's sound stats will influence the results.*

## Actual result:
Song stats are not updated.

While listening (reproduction step 1-2):
![while_listening](https://user-images.githubusercontent.com/3535684/72282988-755c3380-3603-11ea-889e-65086917ccd8.PNG)

After refresh (reproduction step 3):
![after_refresh](https://user-images.githubusercontent.com/3535684/72283013-80af5f00-3603-11ea-9b31-e0015449f54a.PNG)

## Expected result:
Song stats are updated.

## Reproduces how often: 
Easily reproduced. 100% reproduction rate.
*Only reproducible when Brave Shields are enabled.*

## Brave version (brave://version info)
Brave | 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Windows 10 OS Version 1709 (Build 16299.1565)

## Version/Channel Information:
- Can you reproduce this issue with the current release? *Yes.*
- Can you reproduce this issue with the beta channel? *Not sure / untested.*
- Can you reproduce this issue with the dev channel? *Not sure / untested.*
- Can you reproduce this issue with the nightly channel? *Not sure / untested.*

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? *Yes.*
- Does the issue resolve itself when disabling Brave Rewards? *No.*
- Is the issue reproducible on the latest version of Chrome? *No.*

## Miscellaneous Information:
I anticipate that this issue is "functions as designed" as far as Brave is concerned, so I've opened an issue with Soundcloud (reference number 1015710). Normally, there is information collected about the user that is included in sound stats such as geographic location based on IP address, the listener's Soundcloud profile (if applicable), and possibly more.

Most likely, the appropriate solution for this issue is for Soundcloud to change something on their end to work with Brave Shields and respect the user's privacy settings (if they want to update the stats... which I'm sure they will, since providing paid access to sound stat data is one of their primary means of revenue).

**Comment by rebron** [comment]
@jjech Let us know when you hear back from Soundcloud.

**Comment by jjech** [comment]
SoundCloud responded on January 16 and closed the ticket.

-----------------------------------------------------
> SoundCloud ticket (reference #1015710):
> 
> It looks like Soundcloud stats don't update when the listener is using Brave browser (http://www.brave.com). Is this a known issue?
> 
> I am a software developer and I am interested in working on a fix for this, but it's not clear to me yet if the issue needs to be addressed in the Brave project or in Soundcloud.
----------------------------------------------------------
> From: Jay Jech <<jjech@protonmail.com>>
> Monday, January 13, 2020 2:19 PM
> To: SoundCloud Support <<support@support.soundcloud.com>>
> 
> I did some more testing, and opened an issue with Brave Browser: https://github.com/brave/brave-browser/issues/7714
> 
> As you'll see in the details there, the issue is that Brave Shields is preventing sound stats from being submitted to Soundcloud. This is a good thing as far as Brave is concerned, since Brave Shields is designed to protect the user's privacy, and sound stats include some identifying information such as geographical location and Soundcloud profile. But it's a bad thing for Soundcloud, since paid access to sound stats is one of the primary means of revenue for Soundcloud.
> 
> You'll likely want to investigate how to implement (possibly limited) support for Soundcloud stats when Brave Shields are enabled. Brave Shields are enabled by default and the browser is rapidly growing in market share (though this is difficult to track since it currently masks its User Agent as Chrome or Firefox). I could easily see it as the dominant browser within the next few years.
--------------------------------------------------
> From: SoundCloud Support <<support@support.soundcloud.com>>
> Thursday, January 16, 2020 10:16 AM
> To: jjech <<jjech@protonmail.com>>
> 
> Hi there,
> 
> Thanks for getting in touch and for your suggestion.
> 
> Although we unfortunately can't assure you that it's going to be in our roadmap at the moment, we really value our users feedback and I'll be happy to pass it to the relevant team so it can be taken into account for future releases.
> 
> We appreciate that you are taking the time to help shape the future of SoundCloud.
> 
> Best regards,
> Jonas

**Comment by bsclifton** [comment]
@jjech I know it's been a while - but would you be able to try this with a newer version of Brave? I'm curious if recent improvements we've made are helping. If Release version doesn't work, you may try Nightly (https://brave.com/download-nightly)

**Comment by jjech** [comment]
@bsclifton I just tested with Brave `Version 1.11.101 Chromium: 84.0.4147.89 (Official Build) (64-bit)`

The issue is not reproducible with this version of Brave. Closing the issue as it appears to be resolved.
