### ISSUE TITLE
macOS no window buttons when creating new window in fullscreen

### ISSUE THREAD

**Issue by DeathsGun** [brave/brave-browser#7718]
## Description 
If you have one window in fullscreen and want open another window, the new window will be in fullscreen and have no window buttons to minimize or close

## Steps to Reproduce

   1. Open Brave
   2. Make the window fullscreen
   3. Open a new window using `File -> New Window`
   4. Try to close the new window using window buttons

## Actual result:
![error](https://user-images.githubusercontent.com/13536793/72351026-d8bb9380-36df-11ea-90b8-ccaa646ab835.png)
## Expected result:
<img width="2012" alt="normal" src="https://user-images.githubusercontent.com/13536793/72351109-01dc2400-36e0-11ea-9620-fd61e3e09e08.png">

## Reproduces how often: 
This happen quite often while playing a video on youtube

## Brave version (brave://version info)

Brave | 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.15.2 (Build 19C57)
JavaScript | V8 7.9.317.32
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,WebXR,UnifiedConsent,WebXrGamepadModule,AllowPopupsDuringPageUnload,SyncUSSBookmarks --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/deathsgun/Library/Application Support/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

I did not test other versions

## Other Additional Information:
Video of the bug:
https://youtu.be/IBjp1_12jPE

**Comment by rebron** [comment]
@DeathsGun Can you try with our latest 1.4.95 and see if this is still an issue?

**Comment by rebron** [comment]
Do you have any extensions installed that you think might be causing this?

**Comment by rebron** [comment]
Closing. Please re-open if you can provide more info if it's still happening.
