### ISSUE TITLE
C80 followup: [Android]: Fix bottom toolbar accessibility labels

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#7727]
This is a followup issue for #7255.

Chromium 80 change https://chromium.googlesource.com/chromium/src/+/2a77e07a61c243be136ddbe8ff78c8e548897243 removed wrappers around bottom toolbar buttons which we used to display accessibility labels when long clicked. To make the code build for now I used the actual buttons instead of the wrappers, but I don't believe the buttons implement View.OnLongClickListener, so this functionality is likely broken. Relevant commit `[Android] Bottom toolbar button wrappers have been removed.`

cc: @SergeyZhukovsky @bsclifton

**Comment by SergeyZhukovsky** [comment]
That issue depends on that one https://github.com/brave/brave-browser/issues/8030. So waiting for the PR to be merged
