### ISSUE TITLE
Intermittent crash if Confirmations library is called before being instantiated

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#7728]
## Description 

Intermittent crash if Confirmations library was called from the ads or ledger libraries before being instantiated, this is due to a race condition.

## Steps to Reproduce

   1. Unable to reproduce

## Actual result:

Ledger library intermittently crashes if Confirmations has been not initialized when fetching transaction history or a timed event is triggered due to a race condition

## Expected result:
Ledger library should fail gracefully if Confirmations is not initialized

## Reproduces how often: 

No steps to reproduce

## Brave version (brave://version info)

Version 1.5.29 Chromium: 79.0.3945.117 (Developer Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.5.109 Chromium: 80.0.3987.132 (Official Build) beta (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/4370
