### ISSUE TITLE
Stuck at: Running hooks:  80% (67/83) bootstrap 

### ISSUE THREAD

**Issue by MuhammadTausif** [brave/brave-browser#7730]
**

## Steps to Reproduce

   1. After this commond,  `sh scripts/getThirdParties.js`
   2. `Syncing projects:  99% (303/306) src/third_party/angle/third_party/vulkan-validation-layers/src                 
[0:01:14] Still working on:
[0:01:14]   src/brave

[0:01:24] Still working on:
[0:01:24]   src/brave
3>Syncing projects:  94% (305/322)                                                               
[0:01:27] Still working on:
[0:01:27]   src/brave
Syncing projects: 100% (323/323), done.                                              
Running hooks:  24% (20/83) lastchange       
________ running 'vpython src/build/util/lastchange.py -o src/build/util/LASTCHANGE' in '/home/tausif/Documents/browser-android-tabs'
ERROR:root:Failed to get version info: Git command 'git log -1 --format=%H %ct --grep=^Change-Id: HEAD' in /home/tausif/Documents/browser-android-tabs/src failed: rc=0, stdout='' stderr=''
Running hooks:  25% (21/83) gpu_lists_version
________ running 'vpython src/build/util/lastchange.py -m GPU_LISTS_VERSION --revision-id-only --header src/gpu/config/gpu_lists_version.h' in '/home/tausif/Documents/browser-android-tabs'
ERROR:root:Failed to get version info: Git command 'git log -1 --format=%H %ct --grep=^Change-Id: HEAD' in /home/tausif/Documents/browser-android-tabs/src failed: rc=0, stdout='' stderr=''
Running hooks:  80% (67/83) bootstrap`
   3. Stuck at this line of code `Running hooks:  80% (67/83) bootstrap`  

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
@MuhammadTausif do you have more information about your setup? What OS are you running? Have you gone through the setup guide?
https://github.com/brave/brave-browser/wiki
