### ISSUE TITLE
Connected message in the panel VG

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#7739]
Connected message right now check if user has brave funds and based on that we show a message. If you have funds (more then 0) we don't show connected message for connected publisher even if you have uphold wallet. Thing that was missed when doing VG is that now we need to compute anon amount and tokens amount as total and check that if more then 0.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.5.106 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4378, there is no message on the panel, but there is a message on the tip banner. Logged https://github.com/brave/brave-browser/issues/8512 for message on tip banner.
<img width="1192" alt="SS1" src="https://user-images.githubusercontent.com/28145373/75821498-66c10b80-5d6c-11ea-9416-3c2c04001252.png">

* Confirmed that even though message is displayed on the tip banner, tips will be contributed until the ugp grant has been spent. 
<img width="650" alt="SS2" src="https://user-images.githubusercontent.com/28145373/75821514-704a7380-5d6c-11ea-9d00-2e76d274ca28.png">
<img width="395" alt="SS3" src="https://user-images.githubusercontent.com/28145373/75821518-72143700-5d6c-11ea-9063-2788e30ed13f.png">

* Confirmed after ugp grant is spent both he panel and tip banner show the expected connected messaging.
<img width="1185" alt="SS4" src="https://user-images.githubusercontent.com/28145373/75821531-76405480-5d6c-11ea-8aee-0085baacc86a.png">

* Confirmed if I try to tip with user funds from my verified, KYC'd user wallet, the tips will be shown in the pending contributions table.
<img width="957" alt="SS5" src="https://user-images.githubusercontent.com/28145373/75821571-835d4380-5d6c-11ea-962a-4839a1e49c43.png">

* Also confirmed non-connected publishers show correct messaging on both panel and tip banner. Confirmed tips to non-connected publishers are shown in the pending contributions table.
<img width="1187" alt="SS6" src="https://user-images.githubusercontent.com/28145373/75821580-87896100-5d6c-11ea-8a3f-bf6734536bf8.png">
<img width="948" alt="SS7" src="https://user-images.githubusercontent.com/28145373/75821592-8a845180-5d6c-11ea-80ac-575a6398a3de.png">

* Also verified that fully verified, KYC'd publishers do not show any kind of messaging on panel or tip banner. Confirmed tips to fully verified KYC'd publishers are deducted from wallet balance and displayed in Uphold.
<img width="1187" alt="SS8" src="https://user-images.githubusercontent.com/28145373/75821600-8e17d880-5d6c-11ea-9f58-79767c0e200a.png">
<img width="653" alt="SS9" src="https://user-images.githubusercontent.com/28145373/75821603-8fe19c00-5d6c-11ea-9608-2ce7e6595c63.png">
<img width="1176" alt="SS10" src="https://user-images.githubusercontent.com/28145373/75821606-91ab5f80-5d6c-11ea-9995-b21551678a18.png">
