### ISSUE TITLE
Problem when trying to start browser.

### ISSUE THREAD

**Issue by AdamKearn** [brave/brave-browser#7740]
When trying to start my locally built version of Brave I get the following error.
(Sorry for the screenshot.  I can't copy the text as I am connected into a VPS I have running via RDP)

If you open the below screenshot into a new tab it's a little easier to read.
![image](https://user-images.githubusercontent.com/30593259/72465738-9b363380-37cf-11ea-88bc-24890ae84770.png)

I have built the source using `npm run build` and I tried to start it and got the same error.  I then ran `npm run build Release` and still got the above error.

I have tried starting it with all options `npm start [Release|Component|Static|Debug]`  and still get the error.

What do you think could be going wrong???

I am not sure if I could be missing a component within my GUI as I have only installed `ubuntu-desktop` and `xrdp` on my VPS so I could access it remotely.  Do I require any other packages to get the browser running?

Also, what is the command to cross-compile for windows so I could try running it on my PC?

**Comment by bsclifton** [comment]
@AdamKearn what version of NPM are you using? You likely need to update this as it looks like you're on an old one

As far as next steps:
- Upgrade npm using `npm install -g npm@latest`
- Sounds like you have - but just to verify. Did you run `npm run init` to download all of the Chromium sources? This will take about an hour and then it'll apply the Brave specific patches
- Did the build actually work? or did it have similar errors. Running `npm run build` will build all of the source. On a high spec laptop, this can take ~6 hours so patience is appreciated 😄 
- `Component` is default for build/start commands and is a good choice for you. You only need to provide type when it's different, and type would be provided like `npm run start -- Release` or `npm run start --Debug`
- Once build finishes, you can then run `npm run start`
