### ISSUE TITLE
Ads enabled by default on upgrade for new ad regions

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7741]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/6825

If a user in one of the new Ad regions from #6825 has Rewards enabled and upgrades from 1.2.42 to 1.3.x, there should be a BAT logo notification alerting the user that Ads are now available for their region. When the user goes to brave://rewards Ads should be OFF so that the user has to opt-in.

What is happening is that on upgrade to 1.3.x there is no BAT logo notification and Ads are enabled by default on upgrade. (this happened previously when new ad regions were added as well: https://github.com/brave/brave-browser/issues/6449 which specifies Japan but also applies to all other regions added with that release version).

## Steps to Reproduce

Set up to be in a new region (I tested below with Belgium and Russia)
   1. Install 1.2.42 release version for a new ads region from https://github.com/brave/brave-browser/issues/6825.
   2. Enable Rewards, verify "Sorry" message on ads panel
   3. Upgrade to 1.3.x

## Actual result:
   - no notification on BAT logo to enable Ads
   - Navigate to brave://rewards and Ads are enabled by default

## Expected result:
   - notification on BAT logo to enable Ads
   - Navigate to brave://rewards and Ads are not enabled by default

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 1.3.92 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Версия 10.14.6 (Выпуск 18G103)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? probably
- Can you reproduce this issue with the nightly channel? probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @tmancey @jsecretan @rebron @brave/legacy_qa

**Comment by tmancey** [comment]
@LaurenWags Merged with 1.5, so we can test on nightly, once tested can then request an uplift to 1.3 and 1.4 (as release blocking)

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as both https://github.com/brave/brave-core/pull/4393 and https://github.com/brave/brave-core/pull/4394 have been merged. Once we get a new `1.3.x` build that's `> 1.3.100`, QA should be able to verify this issue.

**Comment by kjozwiak** [comment]
@brave/legacy_qa because @LaurenWags already ran through all the cases on Nightly via https://github.com/brave/brave-core/pull/4392#issuecomment-578291555, please run through a few of the upgrade cases in `1.3.x` due to time constraints. Maybe picking ~3 versions and ensuring those upgrades worked as expected.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.3.108 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (assemblage 18G103)

* Per https://github.com/brave/brave-browser/issues/7741#issuecomment-578589563, verified a subset of the test plan from https://github.com/brave/brave-core/pull/4392

1. Upgrade path for unsupported locale to supported locale
   - **PASS** Installed 1.0.1 for Belgium. Enabled Rewards. Confirmed “Sorry” message on Ads panel. Upgraded to 1.3.x (renamed profile). After upgrade worked as expected: ads were not enabled by default and there was a BAT logo notification notifying the user that Brave Ads are now available in their region.
   - **PASS** Installed 1.1.23 for Belgium. Enabled Rewards. Confirmed “Sorry” message on Ads panel. Upgraded to 1.3.x (renamed profile). After upgrade worked as expected: ads were not enabled by default and there was a BAT logo notification notifying the user that Brave Ads are now available in their region.
   - **PASS** Installed 1.2.43 for Belgium. Enabled Rewards. Confirmed “Sorry” message on Ads panel. Upgraded to 1.3.x (renamed profile). After upgrade worked as expected: ads were not enabled by default and there was a BAT logo notification notifying the user that Brave Ads are now available in their region.

2. Upgrade path for unsupported locale to unsupported locale
   - **PASS** Installed 1.0.1 for Aruba. Enabled Rewards. Confirmed “Sorry” message on Ads panel. Upgraded to 1.3.x (renamed profile). After upgrade worked as expected: still see "Sorry" message and there is no BAT logo encouraging user to try Ads.
   - **PASS** Installed 1.1.23 for Aruba. Enabled Rewards. Confirmed “Sorry” message on Ads panel. Upgraded to 1.3.x (renamed profile). After upgrade worked as expected: still see "Sorry" message and there is no BAT logo encouraging user to try Ads.
   - **PASS** Installed 1.2.43 for Aruba. Enabled Rewards. Confirmed “Sorry” message on Ads panel. Upgraded to 1.3.x (renamed profile). After upgrade worked as expected: still see "Sorry" message and there is no BAT logo encouraging user to try Ads.

3. Upgrade path for supported locale (with Ads enabled) to supported locale
   - **PASS** Installed 1.0.1 for US. Enabled Rewards and viewed an Ad. Upgraded to 1.3.x (renamed profile). After upgrade worked as expected: Ads still on after upgrade, Ads panel displays expected data, can still receive ad notifications.
   - **PASS** Installed 1.1.23 for US. Enabled Rewards and viewed an Ad. Upgraded to 1.3.x (renamed profile). After upgrade worked as expected: Ads still on after upgrade, Ads panel displays expected data, can still receive ad notifications.
   - **PASS** Installed 1.2.43 for US. Enabled Rewards and viewed an Ad. Upgraded to 1.3.x (renamed profile). After upgrade worked as expected: Ads still on after upgrade, Ads panel displays expected data, can still receive ad notifications.
