### ISSUE TITLE
Brave Browser Nightly Download Toolbar icon.

### ISSUE THREAD

**Issue by BraveBrowserFan** [brave/brave-browser#7749]
## Description 
After downloaded Brave Browser nightly, the Brave Browser Nightly icon in the toolbar at the bottom it shows brave browser icon. , 

## Steps to Reproduce

   1. Download Brave Browser nightly 
   2. After download  Brave Browser nightly 
   3. it show brave browser icon in the toolbar

## Actual result:
![Brave Browse Nightly](https://user-images.githubusercontent.com/59948001/72494424-ad689f80-37d8-11ea-9d77-217d331f10a2.png)

## Expected result:

It shows brave browser logo icon in the toolbar.

## Reproduces how often: 

Everytime

## Brave version (brave://version info)

Brave
Brave is up to date
Version 1.5.36 Chromium: 79.0.3945.117 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the dev channel? no
- Can you reproduce this issue with the nightly channel? yes

**Comment by bsclifton** [comment]
@BraveBrowserFan can you try un-pinning this from your start menu and then re-pinning it?

There was a commit I merged which may have introduced this. It should have been reverted before a new Nightly happened, but maybe it wasn't

Re-pinning should solve the problem though 😄 Let us know!

**Comment by rebron** [comment]
Closing.
