### ISSUE TITLE
[Android] Remove detailed device information from Android user agent string

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#7758]
Exciting news: we have enough users on Android that it probably makes sense to use a ~~*Brave*~~ user-agent string! Unlike the temporary fix in brave/browser-android-tabs#130, we no longer need to fake details (Android version, device, build…) that we don't want to disclose.

Here's the new template:
`````
Mozilla/5.0 (Linux; Android) like AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.111 Mobile Safari/537.36 Brave
`````

Those Webkit, Chrome, and Safari versions need to stay current — they should match the equivalent Chrome versions. We won't be presenting a Brave version number because we think that feature-detection should be based on actually detecting features, not divination based on tables of version strings.

**Comment by ristein** [comment]
any news on this?

**Comment by wodim** [comment]
Ping? You can't say with a straight face that your browser has "fingerprinting protection" and then reveal the mobile model in the user agent string.

https://github.com/brave/browser-android-tabs/issues/2333

**Comment by jumde** [comment]
Dupe of - https://github.com/brave/brave-browser/issues/12638 - Will be doing more than just hiding the mobile device model.
