### ISSUE TITLE
When have multiple grants, claiming one deletes the next one on the html settings page

### ISSUE THREAD

**Issue by gdregalo** [brave/brave-browser#7760]
## Description 

When have multiple grants, claiming one deletes the next one on the html settings page.
Please fix in branch: `base-79.0.3945.116`.

## Steps to reproduce 

   1.  Create a wallet.
   2.  Add multiple grants.
   3. Open chrome://rewards and claim a grant.
   4. Once completed, observe the grant you just claimed and the next one are deleted from the 
       page.
   5. To see the deleted (unclaimed) grant again, the page has be refreshed.

## Expected result
Claiming a grant removes only the grant which was successfully claimed. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by gdregalo** [comment]
@ryanml please check video at:
https://github.com/brave/brave-browser/issues/7498

**Comment by Miyayes** [comment]
I think this is resolved. Haven't seen this reproduce myself.
