### ISSUE TITLE
Click on `JOIN REWARDS` displays please try again later message - Unable to enable rewards through BR panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7765]
## Description 
Click on `JOIN REWARDS` displays please try again later message - Unable to enable rewards through BR panel

## Steps to Reproduce 

   1. Clean profile 1.0.86
   2. Click on `JOIN REWARDS`
  

## Actual result: 

Click on `JOIN REWARDS` displays please try again later message - Unable to enable rewards through BR panel

https://drive.google.com/open?id=1Em2pupu4oMcwrMzKcPXzeWHvISN7OLjX

## Expected result:
Able to enable rewards through BR panel

## Issue reproduces how often: 
Intermittent issue
## Issue happens on: 
   - Current Playstore version? no
   - Beta build?yes

## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android Version: 5.1
   
## Brave version:
1.0.86

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by bsclifton** [comment]
@GeetaSarvadnya is this a problem on Android Core?

**Comment by Miyayes** [comment]
I also think this is superseded with the new panel.
