### ISSUE TITLE
custom tipping banners not displayed 

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7766]
## Description 
When I go to a site that is verified on staging with a custom tip banner, the custom banner is not displayed when I go to tip the site.

## Steps to Reproduce 

   1. Navigate to a site like kjozwiakstaging.github.io using 1.0.85.
   2. Open panel, you can see that the site is verified on the panel.
   3. Tap on Send a Tip

## Actual result: 
Custom tip banner is not displayed:
![tipbanner-notcustom](https://user-images.githubusercontent.com/28145373/53917973-ca1e3d80-4033-11e9-82ca-c4ec80fc693e.jpg)

## Expected result:
Custom tip banner should be displayed if it exists for site. This is the banner that is displayed on desktop for same site:
![screen shot 2019-03-06 at 5 08 46 pm](https://user-images.githubusercontent.com/28145373/53917665-15841c00-4033-11e9-96ef-c43207ad8e96.png)

## Issue reproduces how often: 
easily

## Issue happens on: 
   - Current Playstore version? no
   - Beta build? Rewards Beta

## Device Details:
   - Install Type(ARM, x86): all
   - Device(Phone, Tablet, Phablet): all
   - Android Version: all
   
## Brave version:
1.0.85 (BR_5)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by GeetaSarvadnya** [comment]
Custom tipping amounts are also not shown correctly in Android. Reproduced in 1.17.x

Desktop:
![image](https://user-images.githubusercontent.com/38657976/99682523-4d502300-2aa5-11eb-914c-4efe17793cf1.png)

Android:
![image](https://user-images.githubusercontent.com/38657976/99682563-5ccf6c00-2aa5-11eb-9ede-d03c71bac061.png)

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya android never had custom banners

**Comment by Miyayes** [comment]
Closing in favor of fresher https://github.com/brave/brave-browser/issues/17070.
