### ISSUE TITLE
Brave Rewards: Default tipping amt and accidental tipping

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#7767]
## Description 
I accidentally tipped ~$1.59 USD worth of BAT to Coinmarketcap.com today. 

The default tipping amt of 5 BAT being preselected, along with the "Send my tip" button being placed very close to the native buttons on the bottom of the screen made it pretty easy to accidentally tip the site. 

## Steps to reproduce 

   1. Go to site
   2. Open tip dialogue
   3. Look at placement

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet): phone, LG V40
   - Android version:
   
## Brave version
1.0.89

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

![Screenshot_2019-04-02-17-01-40](https://user-images.githubusercontent.com/8979240/55444532-a7684180-556b-11e9-9b04-292d00565bd0.png)

**Comment by anthonypkeane** [comment]
Flow should follow iOS here

**Comment by Miyayes** [comment]
I think this will be resolved with: https://github.com/brave/brave-browser/issues/17070, which will improve overall UI/UX

**Comment by Miyayes** [comment]
https://github.com/brave/brave-browser/issues/17070

**Comment by Miyayes** [comment]
Solution: Let's not make any pre-selected value in the tipping case on Android. @sujitacharya2005

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm.apk_1.49.116`

- Confirmed that the new tipping banner doesn't have the default tipping amount selected for one-time/monthly tip
- Confirmed that user can select the default/custom tipping amount in the tipping banner
- Confirmed that one-time tip is shown in tips panel, rewards summary, BR panel, brave://rewards-internals page

Example | Example | Example | Example | Example | Example | Example | Example | Example | Example | Example | Example | Example  | Example 
----------|----------|-----------|----------|-----------|-----------|-----------|----------|-----------|---------|---|---|--|--
![Screenshot_20230303-180707_Brave - Beta](https://user-images.githubusercontent.com/38657976/222729387-6b379995-e7bf-4ed6-a1a8-eae09945981a.jpg) | ![Screenshot_20230303-180801_Brave - Beta](https://user-images.githubusercontent.com/38657976/222729394-63e22277-8166-4e75-8320-2c9aa9767418.jpg) | ![Screenshot_20230303-180810_Brave - Beta](https://user-images.githubusercontent.com/38657976/222729398-c145e452-0b2f-4afc-b580-a8e178bcc3bd.jpg) | ![Screenshot_20230303-181641_Brave - Beta](https://user-images.githubusercontent.com/38657976/222729401-ad7edd2f-9776-478a-8533-9d65e67fafbe.jpg) | ![Screenshot_20230303-181649_Brave - Beta](https://user-images.githubusercontent.com/38657976/222729408-fdac42ec-ff26-4e4d-8f09-c78f73570129.jpg) | ![Screenshot_20230303-181657_Brave - Beta](https://user-images.githubusercontent.com/38657976/222729411-1dff8360-3527-4cdb-ac7c-a4fd1315b354.jpg) | ![Screenshot_20230303-181736_Brave - Beta](https://user-images.githubusercontent.com/38657976/222729415-647115a0-4d68-4ad4-8a38-fce7df69f4ac.jpg) | ![Screenshot_20230303-181757_Brave - Beta](https://user-images.githubusercontent.com/38657976/222729418-ea00d0f9-0090-4fe4-a682-623ab934f77a.jpg) | ![Screenshot_20230303-181808_Brave - Beta](https://user-images.githubusercontent.com/38657976/222729423-fafdcd58-e088-460f-b253-020286e96b98.jpg) | ![Screenshot_20230303-181823_Brave - Beta](https://user-images.githubusercontent.com/38657976/222729428-d3021efd-134c-451a-8b39-3a81013fe196.jpg) | ![Screenshot_20230303-181829_Brave - Beta](https://user-images.githubusercontent.com/38657976/222729431-206a271d-1a7c-48a8-ac6c-9458bdae032b.jpg) | ![Screenshot_20230303-181837_Brave - Beta](https://user-images.githubusercontent.com/38657976/222729437-a79ce0fd-74d6-4a12-8540-964d748f2986.jpg) | ![Screenshot_20230303-183431_Brave - Beta](https://user-images.githubusercontent.com/38657976/222729439-b6177db8-e80c-4c95-82f1-e688a45eb0f3.jpg) | ![Screenshot_20230303-183643_Brave - Beta](https://user-images.githubusercontent.com/38657976/222729441-505779e3-9229-4c80-a484-0814508683e5.jpg)
