### ISSUE TITLE
Exclude this site tool tip persist when a site is deleted and not fully visible

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7769]
## Description 
Exclude this site tool tip persist when a site is deleted and not fully visible

## Steps to Reproduce 

   1. Have a bunch of sites in a-c
   2. Tap on trashbin icon to exclude a publisher
   3. Tool tip for delete persists on the screen and is not fully shown 

## Actual result: 
![image](https://user-images.githubusercontent.com/17010094/54314185-5f2fb200-45b1-11e9-9a98-0f66354be2bd.png)

## Expected result:
Should not persist the tool tip and should properly show the tool tip 

## Issue reproduces how often: 
Easy
### Additional Information

Reproduced by @kjozwiak and @LaurenWags

**Comment by Miyayes** [comment]
If we notice this still happening in most recent version of Android, please file a new issue as this one is kind of old and a lot has changed on this page since then. Thanks. cc: @srirambv
