### ISSUE TITLE
Tip button not shown on certain videos

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7770]
## Description 
Issue found by @jamesmudgett 
Tip button not shown on certain videos.

## Steps to Reproduce 
Scenario 1
   1. Open YT
   2. Search for "texaswest"
   3. Tap on channel name 
   4. Open the fist video, no tip button shown for the publishers on br panel

Scenario 2
   1. Copy https://m.youtube.com/watch?v=UvJl202PlNI
   2. Open new tab and paste the video url
   3. Tip button doesn't show on the video
   4. Go to user channel and load any other video, tip button shows up

## Actual result: 
Tip button not shown on certain videos

## Expected result:
Tip button should be shown on all links irrespective of how its opened

## Issue reproduces how often: 
Easy

## Issue happens on: 
   - Current Playstore version?
   - Beta build?

## Device Details:
   - Install Type(ARM, x86):
   - Device(Phone, Tablet, Phablet):
   - Android Version:
   
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
I think this is resolved with the new Rewards panel. If not, can file anew.
