### ISSUE TITLE
[Android] Page favicon is missing

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#7771]
We should display bat logo for rewards page

![screenshot_20190219-093806](https://user-images.githubusercontent.com/9574457/53001078-1fe6c900-342a-11e9-9d71-3e584040816c.png)

Desktop
![image](https://user-images.githubusercontent.com/9574457/53001085-26754080-342a-11e9-8494-4f5d4548af30.png)

**Comment by Miyayes** [comment]
@srirambv Does this still repro on Android?

**Comment by srirambv** [comment]
Now it looks like this similar to other `brave://` pages
![image](https://user-images.githubusercontent.com/17010094/182773329-69b35112-7adf-4e86-b8e9-32eb3b0da5e1.png)
