### ISSUE TITLE
[Android] Spacing should be bigger

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#7773]
![screenshot_20190219-082940](https://user-images.githubusercontent.com/9574457/52998048-88ca4300-3422-11e9-8549-de1dde0cbe79.png)

Spacing between Grants button and date should be bigger.

Desktop:
![image](https://user-images.githubusercontent.com/9574457/52998084-a0a1c700-3422-11e9-9401-197ac98c7b32.png)

**Comment by Miyayes** [comment]
Superseded with new Rewards panel on Android in 1.35.
