### ISSUE TITLE
tips table should act like auto contribute table

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7774]
## Description 
Currently Auto-Contribute table only shows 5 entries unless you select the 'Show All' link. The Tips table should behave the same way.

On b-c Auto Contribute and Tips tables behave in the same way, although it is different from Android.

## Steps to Reproduce 

   1. Visit more than 5 sites for min time so they are added to ac table.
   2. Set up more than 5 recurring/one-time/mix of tips
   3. Navigate to chrome://rewards
   4. Tap on View Details on a-c
   5. Only first 5 are shown. You have to tap Show All to see all sites.
   6. Go back to chrome://rewards
   7. Tap on View Details for tips.

## Actual result: 
All tips are shown.
![tips-pixel](https://user-images.githubusercontent.com/28145373/54057621-72add800-41c1-11e9-949b-a1aab629974f.png)

## Expected result:
Only the first 5 shown.

## Issue reproduces how often: 
easily

## Issue happens on: 
   - Current Playstore version? no
   - Beta build? Rewards Beta

## Device Details:
   - Install Type(ARM, x86): all
   - Device(Phone, Tablet, Phablet): all
   - Android Version: all
   
## Brave version:
1.0.85 (BR_5)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by Miyayes** [comment]
This should be resolved with the new Rewards page per zenparsing.
