### ISSUE TITLE
Foot note on wallet summary pop up should use a brighter font to be more readable

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7777]
## Description 
Foot note on wallet summary pop up should use a brighter font to be more readable

## Steps to Reproduce 

   1. Enable rewards
   2. Open wallet summary
   3. Foot note on rewards is not very clear to read and on Mobile there is no foot note shown because of size of the wallet summary panel

## Actual result: 
![image](https://user-images.githubusercontent.com/17010094/54125768-4c17b900-43dc-11e9-8cdc-112cde16ee91.png)
Text is not visible on Mobile
![Screenshot_20190311-090051](https://user-images.githubusercontent.com/17010094/54125777-52a63080-43dc-11e9-9fe2-f49740f32a0a.png)

## Expected result:
Should be readable and shown on all device form factor

## Issue reproduces how often: 
Easy
## Issue happens on: 
   - Current Playstore version?
No
   - Beta build?
Yes
## Device Details:
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Both
   - Android Version: 9.0
   
## Brave version:
1.0.86

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
Superseded with new Rewards settings page on Android.
