### ISSUE TITLE
[Android] Wallet height is too big

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#7778]
Height of that purple area should be reduced.

![screenshot_20190219-091202](https://user-images.githubusercontent.com/9574457/52999726-d0eb6480-3426-11e9-9677-43cc59c44ae5.png)

Desktop:
![image](https://user-images.githubusercontent.com/9574457/52999733-d779dc00-3426-11e9-9a46-3c5b07c00b30.png)

**Comment by jamesmudgett** [comment]
Agree, it looks to be taller. Actually, based on shape of triangles in BG looks like it is being stretched, as well.

**Comment by Miyayes** [comment]
Superseded with new Rewards panel on Android in 1.35.
