### ISSUE TITLE
Show monthly tip amount for creators in rewards panel

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#7779]
Missing feature: 

When tipping and checking making this tip monthly we need to show screen as seen below:

<img width="442" alt="54729754-80a91480-4b42-11e9-953e-6b7a023c6085" src="https://user-images.githubusercontent.com/318119/54829258-07b1d600-4c84-11e9-8ebc-f65e545aadc7.png">
<img width="483" alt="54729755-8272d800-4b42-11e9-810a-ef6367a670ef" src="https://user-images.githubusercontent.com/318119/54829268-0aacc680-4c84-11e9-8343-8e5d4c88b616.png">

**Comment by Miyayes** [comment]
Superseded by new panel.
