### ISSUE TITLE
Estimated bandwidth savings in NTP

### ISSUE THREAD

**Issue by AndriusA** [brave/brave-browser#7783]
## Description 

NTP currently shows estimated time saving, but shields have a significant impact on bandwidth saved as well.

We have done some modelling to estimate it based on basic page load metrics and blocked resources ([blog post](https://brave.com/accurately-predicting-ad-blocker-savings/)) and could implement it to show the details in NTP as well as report as highly aggregated stats across the userbase with P3A.

## Steps to Reproduce

 Not applicable

## Actual result:

 Not applicable

## Expected result:

![image](https://user-images.githubusercontent.com/145422/72570283-694acd00-38b4-11ea-928f-5c74e0d3cc76.png)

## Reproduces how often: 

 Not applicable

## Brave version (brave://version info)

 Not applicable

## Version/Channel Information:

 Not applicable

## Other Additional Information:

 Not applicable

**Comment by LaurenWags** [comment]
@rebron @srirambv should this one be marked `OS/Android` as it's no longer on desktop per https://github.com/brave/brave-browser/issues/8256 ?

**Comment by rebron** [comment]
Yes just OS/Android

**Comment by LaurenWags** [comment]
awesome, thanks @rebron!

**Comment by srirambv** [comment]
Moving the issue to Android 1.7.x milestone as this is Android related

**Comment by srirambv** [comment]
@samartnik could you confirm if this is part of 1.7.99 beta build or does this needs to be moved out to 1.8.x milestone?

**Comment by samartnik** [comment]
on android it is in 1.9.x milestone, not sure about desktop

**Comment by srirambv** [comment]
This is only on Android as per https://github.com/brave/brave-browser/issues/7783#issuecomment-603350029. Will create a 1.9.x milestone for Android and move it

**Comment by samartnik** [comment]
We have separate issue for android https://github.com/brave/brave-browser/issues/8845
I generally don't understand it. We currently hide on desktop, bit still want it on Android?

**Comment by AndriusA** [comment]
we want to re-enable it on desktop as well: https://github.com/brave/brave-browser/issues/8969

It's on my todo, but not sure about correct milestones

**Comment by srirambv** [comment]
Marking as dupe of #8845 and also desktop specific issue is done in #8969
