### ISSUE TITLE
Estimated bandwidth savings in NTP for Android

### ISSUE THREAD

**Issue by AndriusA** [brave/brave-browser#7784]
## Description 

We should extend the functionality from #7783 to Android builds when sufficiently stable

## Steps to Reproduce

Not Applicable

## Actual result:

Not Applicable

## Expected result:

![image](https://user-images.githubusercontent.com/145422/72570212-2852b880-38b4-11ea-9fde-87346f88f041.png)

## Reproduces how often: 

Not Applicable

## Brave version (brave://version info)

Not Applicable

## Version/Channel Information:

Not Applicable

## Other Additional Information:

Not Applicable

**Comment by bsclifton** [comment]
Closing as this is implemented 😄 Picture taken from Beta (1.9.69)
![android](https://user-images.githubusercontent.com/4733304/82526960-1e52f780-9aea-11ea-93fa-ada221b8d15b.png)

**Comment by srirambv** [comment]
Marking as dupe of #8845
