### ISSUE TITLE
'Block all HTTP' mode

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#779]
Carried over from https://github.com/brave/browser-laptop/issues/1576
> HTTPS Everywhere has a global 'Block all HTTP' mode where no HTTP requests are allowed. It was pretty well-received and easy to add so we should add it

**Comment by tomlowenthal** [comment]
We'd need a mockup of the click-through-to-HTTP page to ship this.

**Comment by diracdeltas** [comment]
just noting this should probably try to upgrade requests to HTTPS before blocking them

**Comment by diracdeltas** [comment]
Chrome is adding a feature like this: https://www.bleepingcomputer.com/news/security/google-chrome-will-get-an-https-only-mode-for-secure-browsing/

We should consolidate it with HTTPS Everywhere shields UX. cc @karenkliu @pes10k
