### ISSUE TITLE
Removing "Choose a type to set up" from brave://wallet

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#7791]
## Description 

As discussed earlier on Slack, we should probably remove the `Choose a type to set up:` text from `brave://wallet`. It's obvious that the user needs to select one of the below options. The options also have detailed descriptions. Seems like unnecessary text that can be removed.

This will also resolve part of the translation issue mentioned via https://github.com/brave/brave-browser/issues/6533.

## Steps to Reproduce

   1. launch brave and visit `brave://wallet`
   2. Select `I understand` under the `Welcome to Brave Crypto Wallets` modal

## Actual result:

<img width="989" alt="Screen Shot 2020-01-10 at 2 13 39 PM" src="https://user-images.githubusercontent.com/2602313/72589857-68bd3100-38ca-11ea-8bc1-39163fe7f87f.png">

## Expected result:

The `Choose a type to set up:` should be removed.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 1.3.92 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | macOS Version 10.15.2 (Build 19C57)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `N/A`
- Can you reproduce this issue with the dev channel? `N/A`
- Can you reproduce this issue with the nightly channel? `N/A`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

## Miscellaneous Information:

CCing @ryanml @srirambv

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.5.73 Chromium: 80.0.3987.66 (Official Build) nightly (64-bit)
-- | --
Revision | 56ea77d65c47ecbb1180b99f860d85b51117864a-refs/branch-heads/3987@{#662}
OS | Linux
Component | `0.1.37`

- Verified `Choose a type to set up` text is removed 
![image](https://user-images.githubusercontent.com/17010094/73626095-af9e7b00-466d-11ea-9042-fdb28408c7b3.png)
