### ISSUE TITLE
New Tab Page Rewards Widget think Ads are off when rewards are re-enabled

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#7807]
## Description 

New Tab Page Rewards Widget think Ads are off when rewards are re-enabled

## Steps to Reproduce

   0. Rewards and ads are on
   1. Go to chrome://rewards and turn Rewards OFF
   2. Open a new New Tab
   3. Turn ON rewards (from NTP or from Rewards page), but **don't** refresh NTP

## Actual result:

The "Enable Ads" button is shown. I.e. the widget thinks Ads are off
![image](https://user-images.githubusercontent.com/741836/72654145-166c2680-3943-11ea-93de-3ce25c3bd609.png)

## Expected result:
The estimated ads earnings are shown. The widget does not offer ads to be turned on.
![image](https://user-images.githubusercontent.com/741836/72654122-ef155980-3942-11ea-82b0-017cdb532a0e.png)

## Reproduces how often: 

100%

## Brave version (brave://version info)

1.3

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc @ryanml

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.3.108 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

* Reproduced issue using 1.2.43
* Verified STR from description
