### ISSUE TITLE
Crash in release mode on Settings

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#7810]
There is a crash on Android in release mode when you hit Settings menu item.

**Comment by srirambv** [comment]
Verification passed on OnePus 6T with Android 10 running 1.5.57 x64 nightly build
- Verified no crash when settings is opened
------
Verification passed on Samsung Tab A with Android 9.0 running 1.5.57 x64 nightly build
- Verified no crash when settings is opened
