### ISSUE TITLE
Browser responds late when switched from another application on Ubuntu

### ISSUE THREAD

**Issue by rishabh96b** [brave/brave-browser#7811]
## Description 
The browser responds after consuming a short period of time when switched from another application on my Ubuntu 19.10. So suppose I am using my text editor and I press `Alt+Tab` to switch to Brave browser, it opens after 2-3 seconds of delay.

## Steps to Reproduce

   1. Install the Brave browser on Ubuntu 19.10.
   2. Open the browser with other applications.
   3. Switch to Brave from any other application.

## Actual result:
Takes 2-3 secs of delay to open(switch to browser window) up.

## Expected result:
Should be switched immediately.

## Reproduces how often: 
Regularly.

## Brave version (brave://version info)

Brave | 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Linux

## Version/Channel Information:
I am using a stable version.

## Other Additional Information:

This issue doesn't happen with the latest version of Chrome browser. It is not affected by brave shields or any other browser extension.

**Comment by rebron** [comment]
@rishabh96b Are you able to reproduce this consistently? Can you try with our latest 1.4.96?

**Comment by rishabh96b** [comment]
Hi @rebron , updating to the latest version`1.4.96` fixed the issue. Thanks for the help and please feel free to close the issue.
