### ISSUE TITLE
Extensions UI does not change (e.g. switch/toggle components)

### ISSUE THREAD

**Issue by ertugrulcetin** [brave/brave-browser#7813]
## Description 

A couple of extensions ui does not change, when I try to change on/off switch button (Grammarly extension) nothing happens but it works on Chrome itself. Also happens in other extensions too.

## Steps to Reproduce

   1. Install Grammarly extension try to on/off the current tab/URL check switch button.
   2. 
   3. 

## Actual result:

On/off does not change (it shows always on)

## Expected result:
On/off should change

![Screenshot 2020-01-19 at 00 40 25](https://user-images.githubusercontent.com/8271291/72670952-c2e9fd80-3a54-11ea-9cdb-a85f76480fd7.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @ryanbr Another Grammarly related issue.

**Comment by ertugrulcetin** [comment]
It seems okay now, closing the issue.

**Comment by rebron** [comment]
Thanks @ertugrulcetin
