### ISSUE TITLE
"Sorry! Ads are not yet available in your region." is shown if Regional Format is set to English (Europe)

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#7815]
## Description 

"Sorry! Ads are not yet available in your region." is shown if Regional Format is set to English (Europe)

## Steps to Reproduce

   1. Set Settings > Region to "Algeria"
   2. Set Settings > Region > Regional format to "English (Europe)"
   3. Open "Rewards settings"

## Actual result:

"Sorry! Ads are not yet available in your region." is shown

## Expected result:
Brave Ads should be available in this region

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

A workaround is to use another regional format such as "English (United States)"

**Comment by tmancey** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/1188719/72671684-ccb83480-3a45-11ea-8c44-483d73adb391.jpg)

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/BATProject/comments/evpite/ad_rewards_available_in_spain/

**Comment by tmancey** [comment]
@Miyayes Can you please let me know which version of the desktop browser you are running, as Spain is available from version 1.3. Thanks

**Comment by tmancey** [comment]
Notes: See https://docs.microsoft.com/en-us/windows/win32/intl/locale-names

**Comment by LaurenWags** [comment]
@tmancey looks like `English (Europe)` isn't an option on macOS. Is this issue Windows only? Should I use a different language to test on macOS? these are the ones I have available to me:
<img width="356" alt="Screen Shot 2020-05-01 at 8 02 49 AM" src="https://user-images.githubusercontent.com/28145373/80804165-5b2e6d00-8b82-11ea-9034-91ebc85744e5.png">

**Comment by tmancey** [comment]
@LaurenWags Apologies this issue can only be tested on Windows at this time, thanks

**Comment by GeetaSarvadnya** [comment]
Verification passed on
```

Brave | 1.9.62 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/81560207-8e58d380-93ae-11ea-953c-e03ab2f9f498.png)
