### ISSUE TITLE
Additional phase of Brave Ads regions

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#7817]
Add the following regions to Brave Ads:

Afghanistan | AF
American Samoa | AS
Andorra | AD
Angola | AO
Anguilla | AI
Antarctica | AQ
Antigua and Barbuda | AG
Armenia | AM
Aruba | AW
Bahamas | BS
Bahrain | BH
Barbados | BB
Belarus | BY
Belize | BZ
Benin | BJ
Bermuda | BM
Bhutan | BT
Bolivia | BO
Bonaire | BQ
Bosnia and Herzegovina | BA
Botswana | BW
Bouvet Island | BV
British Indian Ocean Territory | IO
Brunei Darussalam | BN
Burkina Faso | BF
Burundi | BI
Cameroon | CM
Cape Verde | CV
Central African Republic | CF
Chad | TD
Christmas Island | CX
Cocos (Keeling) Islands | CC
Comoros | KM
Congo | CG
Democratic Republic of the Congo | CD
Cook Islands | CK
Costa Rica | CR
Curacao | CW
Cyprus | CY
Cote d'Ivoire | CI
Djibouti | DJ
Dominica | DM
Dominican Republic | DO
El Salvador | SV
Equatorial Guinea | GQ
Eritrea | ER
Estonia | EE
Ethiopia | ET
Falkland Islands (Malvinas) | FK
Faroe Islands | FO
Fiji | FJ
French Guiana | GF
French Polynesia | PF
French Southern Territories | TF
Gabon | GA
Gambia | GM
Georgia | GE
Ghana | GH
Gibraltar | GI
Greenland | GL
Grenada | GD
Guadeloupe | GP
Guam | GU
Guatemala | GT
Guernsey | GG
Guinea | GN
Guinea-Bissau | GW
Guyana | GY
Haiti | HT
Heard Island and McDonald Islands | HM
Holy See (Vatican City State) | VA
Honduras | HN
Iceland | IS
Isle of Man | IM
Jamaica | JM
Jersey | JE
Jordan | JO
Kazakhstan | KZ
Kenya | KE
Kiribati | KI
Kuwait | KW
Kyrgyzstan | KG
Lao People's Democratic Republic | LA
Latvia | LV
Lebanon | LB
Lesotho | LS
Liberia | LR
Libya | LY
Liechtenstein | LI
Luxembourg | LU
Macao | MO
Macedonia, the Former Yugoslav Republic of | MK
Madagascar | MG
Malawi | MW
Maldives | MV
Mali | ML
Malta | MT
Marshall Islands | MH
Martinique | MQ
Mauritania | MR
Mauritius | MU
Mayotte | YT
Micronesia, Federated States of | FM
Moldova, Republic of | MD
Monaco | MC
Mongolia | MN
Montenegro | ME
Montserrat | MS
Mozambique | MZ
Myanmar | MM
Namibia | NA
Nauru | NR
Nepal | NP
New Caledonia | NC
Nicaragua | NI
Niger | NE
Niue | NU
Norfolk Island | NF
Northern Mariana Islands | MP
Norway | NO
Oman | OM
Palau | PW
Palestine, State of | PS
Panama | PA
Papua New Guinea | PG
Paraguay | PY
Pitcairn | PN
Puerto Rico | PR
Qatar | QA
Rwanda | RW
Reunion | RE
Saint Barthelemy | BL
Saint Helena | SH
Saint Kitts and Nevis | KN
Saint Lucia | LC
Saint Martin (French part) | MF
Saint Pierre and Miquelon | PM
Saint Vincent and the Grenadines | VC
Samoa | WS
San Marino | SM
Sao Tome and Principe | ST
Senegal | SN
Seychelles | SC
Sierra Leone | SL
Sint Maarten (Dutch part) | SX
Solomon Islands | SB
Somalia | SO
South Georgia and the South Sandwich Islands | GS
South Sudan | SS
Sri Lanka | LK
Sudan | SD
Suriname | SR
Svalbard and Jan Mayen | SJ
Swaziland | SZ
Tajikistan | TJ
United Republic of Tanzania | TZ
Timor-Leste | TL
Togo | TG
Tokelau | TK
Tonga | TO
Trinidad and Tobago | TT
Tunisia | TN
Turkmenistan | TM
Turks and Caicos Islands | TC
Tuvalu | TV
Uganda | UG
United States Minor Outlying Islands | UM
Uruguay | UY
Uzbekistan | UZ
Vanuatu | VU
British Virgin Islands | VG
US Virgin Islands | VI
Wallis and Futuna | WF
Western Sahara | EH
Yemen | YE
Zambia | ZM
Zimbabwe | ZW

**Comment by jwchong** [comment]
Pls add Malaysia into the region list.

**Comment by eljuno** [comment]
@jwchong Malaysia is already supported (#6825) -- https://brave.com/transparency/

**Comment by jsecretan** [comment]
For privacy reasons, we should put the follow country codes together under a country code for Other "OT":

AS
AI
AQ
AG
BQ
BV
IO
CF
TD
CX
CC
KM
CK
GQ
ER
FK
TF
GL
GW
HM
VA
KI
LR
MH
YT
FM
MS
NR
NU
NF
MP
PW
PN
BL
SH
KN
MF
PM
WS
SM
ST
SX
SB
GS
SS
SJ
TJ
TL
TK
TM
TC
TV
UM
VU
VG
WF
EH

**Comment by GeetaSarvadnya** [comment]
QA Blocked: Cannot verify the issue as catalog is empty for additional ad regions, for more details please refer https://bravesoftware.slack.com/archives/CJL3G0S95/p1588687877157000

**Comment by LaurenWags** [comment]
Test Plan:
- follow plan outlined in https://github.com/brave/brave-core/pull/4427 for 2-3 new regions above. Each OS should check different regions. (confirmed plan with @jsecretan)
- additionally, spot check previously added regions (using google doc list, message me if you need the list) to confirm they are still supported as expected.

**Comment by LaurenWags** [comment]
Verified passed using

```
Brave	1.9.70 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision	8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS	macOS Version 10.14.6 (Build 18G3020)
```

* Verified the following for new regions (Estonia, Moldova)
   * Clean install of 1.9.x. Enable Rewards. Confirmed Ads are enabled by default. Confirmed able to view an ad.
   * Installed 1.8.96. Enabled Rewards. Confirmed Ads are not available. Upgraded to 1.9.70. Confirmed notification displayed on BAT logo to alert user that ads are now available in their region. Confirmed Ads are not enabled by default on upgrade. Confirmed able to enable ads and view an ad.

Estonia on 1.8.96:
<img width="658" alt="Estonia 1 8 x" src="https://user-images.githubusercontent.com/28145373/82381712-aeb10f80-99f8-11ea-8ac1-8ebd0d08b977.png">

Estonia after upgrade to 1.9.x:
<img width="416" alt="estonia upgrade 1" src="https://user-images.githubusercontent.com/28145373/82381718-b1ac0000-99f8-11ea-9838-f2e88afb4bdd.png">
<img width="647" alt="estonia upgrade 2" src="https://user-images.githubusercontent.com/28145373/82381724-b2dd2d00-99f8-11ea-9579-8d539c05f49a.png">

Confirming ad panel updates for Estonia when ads are enabled and an ad notification has been served:
<img width="652" alt="estonia ad panel updates" src="https://user-images.githubusercontent.com/28145373/82381739-b83a7780-99f8-11ea-92c1-61cc7081ea02.png">

Moldova on 1.8.96:
<img width="654" alt="Moldova 1 8 x" src="https://user-images.githubusercontent.com/28145373/82381749-bc669500-99f8-11ea-9097-98d1c155d94f.png">

Moldova after upgrade to 1.9.x:
<img width="410" alt="Moldova upgrade 1" src="https://user-images.githubusercontent.com/28145373/82381761-bffa1c00-99f8-11ea-90f8-47ead395e4a0.png">
<img width="662" alt="Moldova upgrade 2" src="https://user-images.githubusercontent.com/28145373/82381768-c12b4900-99f8-11ea-8289-3401f36de785.png">

Confirming ad panel updates for Moldova when ads are enabled and an ad notification has been served:
<img width="650" alt="Moldova ad panel updates" src="https://user-images.githubusercontent.com/28145373/82381820-d7390980-99f8-11ea-9618-1f73330a986c.png">


* Also per https://github.com/brave/brave-browser/issues/7817#issuecomment-630381585, spot checked previously enabled ad regions: US, Ireland, Russia and confirmed the following scenarios:
   * Clean install of 1.9.x. Enable Rewards. Confirmed Ads are enabled by default.
   * Installed 1.8.96. Enabled Rewards. Disabled Ads. Upgraded to 1.9.x. Confirmed Ads are still off after upgrade. No notification that ads are available.
   * Installed 1.8.96. Enabled Rewards. Upgraded to 1.9.x. Confirmed Ads are still on after upgrade. No notification that ads are available.
