### ISSUE TITLE
Geolocation allowed in search engines

### ISSUE THREAD

**Issue by angelog0** [brave/brave-browser#7818]
I just installed the last Brave (1.7.0 - Chromium-79.0.3945.116) for Android and noticed that, after clearing the browsing history, the settings for the search engine (for any search engine I choose) show the string (in RED): `The geolocation and notification are allowed` (just a translation). 

Even clearing the permissions and denying them `for current search engine`, at the next clearing of the browsing history, the string shows up again..

It is not clear if this is an issue, if there is some setting to apply or what else...

Thanks.

**Comment by bsclifton** [comment]
@angelog0 do you have more information? Where does this warning show? Is this on a Brave page (in settings? for default search?) or is this on the search engine itself (ex: you're logged in)

**Comment by angelog0** [comment]
Please, read my post: in the settings, for any search engine, there is/was the string in RED: **The geolocation and notification are allowed**

I uninstalled Brave and I cannot say it is still there that string.

**Comment by anthonypkeane** [comment]
![Release](https://user-images.githubusercontent.com/7606853/86836860-fcd6ac80-c052-11ea-8e0d-4ba8d4c671fc.jpg)

**Comment by SergeyZhukovsky** [comment]
Fixed in part of this issue https://github.com/brave/brave-browser/issues/10713
