### ISSUE TITLE
Compat issue with poliigon

### ISSUE THREAD

**Issue by ChildishGiant** [brave/brave-browser#7819]
## Description 
Search broken by shields on [poliigon.com](https://www.poliigon.com/)

## Steps to Reproduce
Visit https://www.poliigon.com/search?type=texture

## Actual result:
![image](https://user-images.githubusercontent.com/13716824/72684710-e6578b80-3ada-11ea-979c-05f4fe59bb9e.png)

## Expected result:
![image](https://user-images.githubusercontent.com/13716824/72684714-fa9b8880-3ada-11ea-8a79-45e89f570f85.png)

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1903 (Build 18362.592)

Brave | 1.5.43 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1903 (Build 18362.592)

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?Untested
- Can you reproduce this issue with the dev channel? Untested
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by ryanbr** [comment]
Cookie issues. Seems to be blocking the site cookies.

![poliigon-cookies](https://user-images.githubusercontent.com/1659004/76130106-6e372c00-606e-11ea-9e87-acd0a8a68a4f.png)
