### ISSUE TITLE
Option to hide download bar

### ISSUE THREAD

**Issue by ffd8** [brave/brave-browser#7820]
## Description 

It would be great to add a toggle in the preferences/settings to disable the 'download bar' aka shelf – sometimes you want it, sometimes you don't. When using a webapp that offers downloads, it can be annoying if the whole screen resizes and bar appears.

There's a [minimal extension](https://github.com/ivan7237d/disable-downloads-bar/blob/master/background.js) that covers this – if others like the idea, maybe one knows how/where to implement?

It essentially alters these settings:
```
'use strict';

let disableShelf = () => chrome.downloads.setShelfEnabled(false);
chrome.runtime.onInstalled.addListener(disableShelf);
chrome.runtime.onStartup.addListener(disableShelf);
```

**Comment by rebron** [comment]
Closing, wontfix. 

Hi @ffd8 thanks for filing the issue. We do get a lot of requests asking for prefs but we don't want to expose one here to disable the download bar. Via extension, like you suggested, looks like the way to go. 

The extension system is setup for this scenario where you can create this feature/setting and other settings you may want.
