### ISSUE TITLE
brave://flags/#enable-force-dark does not work

### ISSUE THREAD

**Issue by akshay-soni** [brave/brave-browser#7822]
## Description 
Unable to launch the browser when brave://flags/#enable-force-dark is enabled

## Steps to Reproduce

   1. Goto - brave://flags/#enable-force-dark
   2. Choose - enable option
   3. Press button "Relauch"

## Actual result:

Brave browser application fails to launch

## Expected result:
The browser should function as usual 

## Reproduces how often: 

Always

## Brave version (brave://version info)

Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Haven't' tested
- Can you reproduce this issue with the dev channel?
Haven't' tested
- Can you reproduce this issue with the nightly channel?
Haven't' tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No - This issue isn't related to Brave Shields
- Does the issue resolve itself when disabling Brave Rewards?
No - This issue isn't related to Brave Rewards
- Is the issue reproducible on the latest version of Chrome? 
Yes

**Comment by rebron** [comment]
Is this still happening with 1.4.96?

**Comment by bsclifton** [comment]
Closing as stale. I verified it works as expected for me on macOS - although it does take a while for the close and relaunch to actually happen. It took about 30 seconds
