### ISSUE TITLE
[Android] Verified Twitch account doesn't show verified in BR panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7826]
## Description 
Verified Twitch account doesn't show verified in BR panel

## Steps to Reproduce 

   1. Open verified twitch account on staging
   2. Check the BR panel, shows non-verified
   3. Open a-c list, shows as verified

## Actual result: 
![screenshot_20190302-165531](https://user-images.githubusercontent.com/17010094/53688423-a6948380-3d11-11e9-9028-b2750ca39076.png)
![screenshot_20190302-165543](https://user-images.githubusercontent.com/17010094/53688424-a6948380-3d11-11e9-9072-90dd227643c6.png)

## Expected result:
Should show verified in all places

## Issue happens on: 
   - Current Playstore version?
   - Beta build?

## Device Details:
   - Install Type(ARM, x86):ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 9.0
   
## Brave version:
1.0.85

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/creator-verified-not-working-on-mobile-browser/119851?u=eljuno

**Comment by jammersdublin** [comment]
+1 on this, having the issue with https://bitcoinsinireland.com. Verified on desktop, not verified on mobile (iOS)

**Comment by astroajay** [comment]
+1 over here too, it's been over a week since I got verified and it works fine on iOS and Desktop, but it's messed up on Android.

https://community.brave.com/t/creator-verified-not-working-on-mobile-browser/119851/14?u=astroajay

**Comment by aaronsantamaria** [comment]
+1 from community 
https://community.brave.com/t/creator-account-showing-not-verified-on-android-ios-brave/252576

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/wallet-doesnt-recognize-twitch-channels-for-tipping-in-mobile/260434

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/cannot-tip-creator-on-android/267417?u=eljuno

**Comment by nikahmadz** [comment]
+1 Cannot tip verified Github Pages either. my githubpages [nikahmadz.github.io](//nikahmadz.github.io) was verified publisher on Brave Desktop but not on Brave Mobile.

**Comment by Miyayes** [comment]
This is just due to general lack of support for Twitch on Android at this time.
