### ISSUE TITLE
Geolocation doesn't show user location

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#783]
## Description 

Geolocation doesn't show user location

## Steps to Reproduce

   1. Clean install `0.54.0`
   2. Visit https://browserleaks.com/geo in a new tab
   3. Click allow to capture location, doesn't work

## Actual result:

![geo](https://user-images.githubusercontent.com/17010094/44354207-37db9100-a477-11e8-9e36-7043d647ba0b.gif)

## Expected result:
Should show user location when access to location is allowed

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Brave | 0.54.0 Chromium: 69.0.3497.32 (Official Build) dev (64-bit)
-- | --
Revision | bf910299d07564d66b36991ebc7dbdc7e26fe897-refs/branch-heads/3497@{#514}
OS | Windows
JavaScript | V8 6.9.427.14
Flash | (Disabled)

### Reproducible on current release:

No, b-l shows proper location

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No still fails on shields down
- Is the issue reproducible on the latest version of Chrome? Chrome shows user location when allowed

### Additional Information
#48

**Comment by mbacchi** [comment]
I've added (the equivalent of) this to all 3 platform build jobs:

```
export npm_config_brave_google_api_endpoint="https://location.services.mozilla.com/v1/geolocate?key="
```

**Comment by GeetaSarvadnya** [comment]
Re-validated the issue on latest build 0.54.2. The web view is getting crashed for step 2.
Please find the crash ID below:
Crash Report ID 10c6e5933aeb78fb

**Comment by bbondy** [comment]
This is working for me now on macOS, so resolving.
Thanks @mbacchi!

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

Also checked:
https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation
https://html5demos.com/geo/

**Comment by felipenmoura** [comment]
Hi.
I might be missing something here!
I'm currently using version `Version 1.16.76 Chromium: 86.0.4240.198 (Official Build) (x86_64)`.
I see the browser asking for permissions.
I allow access to my location.
The JavaScript promise takes a long time and then fails catching the error:

```
{
  "message": "Network location provider at 'https://www.googleapis.com/' : No response received.",
  "code": 2
}
```

By these last comments, it should be also using Mozilla's geolocation and should be working, right?

The same code works on chrome.
