### ISSUE TITLE
Update Widevine version to 4.10.1610.0 on linux

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#7831]
Chrome already uses Widevine `4.10.1610.0` but that version is not yet opened to partners.
Usually, it is opened to others 1~2 weeks later after deploying it in chrome.

**Comment by rebron** [comment]
@simonhong Is 4.10.1610.0 ready? Still a valid issue?

**Comment by simonhong** [comment]
@rebron I think it's nor ready because component updater in mac & windows are still using `4.10.1582.2`.
