### ISSUE TITLE
Support puppetlabs::apt installations by pushing Linux signing keys to a keyserver

### ISSUE THREAD

**Issue by bill-mcgonigle** [brave/brave-browser#7832]
## Description 

The keyservers don't have subkey:
9BD198A2D848C482E3550697A8580BDC82D3DC6C

the last key that was uploaded has, as its last subkey:
E85FFA8E2E90B40B33ED39274FE13824E3FFC656

This breaks our puppet deployment method (and leaves other users without keyserver functionality for validation).

## Steps to Reproduce

Try to install latest version via apt, signed with new key.

## Actual result:

Apt fails because the signing key cannot be found on the keyservers an imported.

## Expected result:

Apt is happy.

## Reproduces how often: 

Always since new key.

## Brave version (brave://version info)

Brave | 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Linux

## Version/Channel Information:

only tested release

## Other Additional Information:
n/a

## Miscellaneous Information:

Thank you.

**Comment by bsclifton** [comment]
cc: @fmarier @mbacchi @bkero

**Comment by fmarier** [comment]
@bill-mcgonigle Can you describe your puppet deployment workflow?

Which keyserver do you use? https://keys.openpgp.org/?

Are you querying the key using a fingerprint or an email address? Are you expecting any signatures on it?

**Comment by bill-mcgonigle** [comment]
> @bill-mcgonigle Can you describe your puppet deployment workflow?
> Are you querying the key using a fingerprint or an email address? Are you expecting any signatures on it?

Basically it's just using puppetlabs::apt to create a repo definition and the current Brave signing subkey is specified as a valid signer.  This allows a machine to securely bootstrap the package download using apt's signature validation.

> Which keyserver do you use? https://keys.openpgp.org/?

Any of them should be fine - we've been using keyserver.ubuntu.com as it's pretty quick to respond, but AIUI they all synchronize and should work.

Here's the old key working:

```
$ gpg --search --keyserver hkp://sks-keyservers.net 4FE13824E3FFC656
gpg: data source: http://sks-keyservers.net:11371
(1)     Brave Software <support@brave.com>
          4096 bit RSA key 0BB75829C2D4E821, created: 2018-10-15, expires: 2020-02-05
Keys 1-1 of 1 for "4FE13824E3FFC656".  Enter number(s), N)ext, or Q)uit > q
gpg: error searching keyserver: Operation cancelled
gpg: keyserver search failed: Operation cancelled

$ gpg --search --keyserver hkp://keyserver.ubuntu.com 4FE13824E3FFC656
gpg: data source: http://162.213.33.8:11371
(1)     Brave Software <support@brave.com>
          4096 bit RSA key 0BB75829C2D4E821, created: 2018-10-15
Keys 1-1 of 1 for "4FE13824E3FFC656".  Enter number(s), N)ext, or Q)uit > q
gpg: error searching keyserver: Operation cancelled
gpg: keyserver search failed: Operation cancelled

$ gpg --search --keyserver hkp://keys.gnupg.net 4FE13824E3FFC656
gpg: data source: http://[2001:67c:26b4::98:0]:11371
(1)     Brave Software <support@brave.com>
          4096 bit RSA key 0BB75829C2D4E821, created: 2018-10-15, expires: 2020-02-05
Keys 1-1 of 1 for "4FE13824E3FFC656".  Enter number(s), N)ext, or Q)uit > q
gpg: error searching keyserver: Operation cancelled
gpg: keyserver search failed: Operation cancelled

$ gpg --search --keyserver hkp://keys.openpgp.org 4FE13824E3FFC656
gpg: data source: http://keys.openpgp.org:11371
(1)       4096 bit RSA key 0BB75829C2D4E821, created: 2018-10-15
Keys 1-1 of 1 for "4FE13824E3FFC656".  Enter number(s), N)ext, or Q)uit > q
gpg: error searching keyserver: Operation cancelled
gpg: keyserver search failed: Operation cancelled
```

and the new key not working: 

```
$ gpg --search --keyserver hkp://keys.gnupg.net A8580BDC82D3DC6C
gpg: data source: http://[2001:67c:26b4::98:0]:11371
gpg: key "A8580BDC82D3DC6C" not found on keyserver
gpg: keyserver search failed: Not found

$ gpg --search --keyserver hkp://keyserver.ubuntu.com A8580BDC82D3DC6C
gpg: data source: http://162.213.33.8:11371
gpg: key "A8580BDC82D3DC6C" not found on keyserver
gpg: keyserver search failed: Not found

$ gpg --search --keyserver hkp://keyserver.ubuntu.com A8580BDC82D3DC6C
gpg: data source: http://162.213.33.8:11371
gpg: key "A8580BDC82D3DC6C" not found on keyserver
gpg: keyserver search failed: Not found

$ gpg --search --keyserver hkp://keys.openpgp.org A8580BDC82D3DC6C
gpg: data source: http://keys.openpgp.org:11371
gpg: key "A8580BDC82D3DC6C" not found on keyserver
gpg: keyserver search failed: Not found

$ gpg --search --keyserver hkp://sks-keyservers.net A8580BDC82D3DC6C
gpg: data source: http://sks-keyservers.net:11371
gpg: key "A8580BDC82D3DC6C" not found on keyserver
gpg: keyserver search failed: Not found

```

It appears somebody did `gpg --send-keys` when the previous signing subkeys were created (thank you) but not with this one.

**Comment by fmarier** [comment]
> > Which keyserver do you use? https://keys.openpgp.org/?
> 
> Any of them should be fine - we've been using keyserver.ubuntu.com as it's pretty quick to respond, but AIUI they all synchronize and should work.

The reason why I asked is that the existing keyserver infrastructure has more-or-less collapsed last year due to [targeted attacks](https://dkg.fifthhorseman.net/blog/openpgp-certificate-flooding.html) and that, by design, the next-generation keyserver `hkps://keys.openpgp.org` (now the default in Debian) doesn't sync with any of the other keyservers since they are not abuse-resistant.

So if we were to `gpg --send-keys` our new keys to `keys.openpgp.org`, would that work for you?

**Comment by bill-mcgonigle** [comment]
> So if we were to gpg --send-keys our new keys to keys.openpgp.org, would that work for you?

Sure thing.  Thanks for the tip.

**Comment by fmarier** [comment]
It's now available from https://keys.openpgp.org/search?q=D8BAD4DE7EE17AF52A834B2D0BB75829C2D4E821 and https://keys.openpgp.org/search?q=support@brave.com.
