### ISSUE TITLE
Upgrade from 0.63.x to 1.3.x resets Ads viewed count to zero, AC switch OFF and wallet creation failed

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7833]
## Description 

Upgrade from 0.63.x to 1.3.x resets Ads viewed count to zero, AC switch OFF and wallet creation failed.

## Steps to Reproduce

   1. Clean profile 0.63.35
   2. Enable rewards and view an ad
   3. Upgrade to 1.3.94
   4. After upgrade, Ads viewed count resets to 0.0 BAT and Auto contribution switch is turned OFF and wallet creation is failed.

## Actual result:

After upgrade, Ads viewed count resets to 0.0 BAT and Auto contribution switch is turned OFF and wallet creation is failed.
0.63.35 -->1.3.94
![Ads count resets to zero after upgrade](https://user-images.githubusercontent.com/38657976/72776363-eb7e1d00-3c37-11ea-9001-c28e948039b7.gif)

0.63.55-->1.2.43 - Works fine
![Ads upgrade 0 63 55 to release channel](https://user-images.githubusercontent.com/38657976/72777090-7829da80-3c3a-11ea-9ae4-d6c5c83f577e.gif)

## Expected result:
Ads count should not be reset to zero and AC and rewards should be in ON state after upgrade

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.3.94 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 0.63.55 -->1.2.42 - works fine 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Not sure
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @tmancey @jsecretan @rebron

**Comment by tmancey** [comment]
State is resetting due to `WALLET_PROPERTIES_ST` JSON changes in `e3b5f827c2756cd19eee0c01ba15eea803a4db25` as there is no migration path.

@GeetaSarvadnya With regards to the ads issue where "Ad notifications received this month" are reset to 0, can you please raise a separate issue for `feature/ads` as it is unrelated

**Comment by LaurenWags** [comment]
Reproduced when going from 0.63.55 --> 1.5.53 (Nightly)

Brave | 1.5.53 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

Per @tmancey note https://github.com/brave/brave-browser/issues/7833#issuecomment-576617941 that this will occur for any upgrade before 0.65.59, we should decide if we're going to fix this one since that is a fairly old version.

cc @kjozwiak @rebron

**Comment by LaurenWags** [comment]
Could not reproduce with 1.2.x. Steps:
1. Install 0.63.55 (Release)
2. Enable Rewards, trigger an Ad
3. Upgrade using brave://settings/help to 1.2.43
4. Relaunch
5. Navigate to brave://rewards
---> no issues on brave://rewards page. Ads panel is displayed as expected, nothing is toggled off, no error messages.

0.63.55 Before upgrading to 1.2.43:
<img width="1195" alt="0 63 55-before upgrade to 1 2 x" src="https://user-images.githubusercontent.com/28145373/73085352-90992f80-3e9c-11ea-8edb-64a5bf9a4a55.png">

After upgrading to 1.2.43:
<img width="1196" alt="1 2 43 after upgrade from 0 63 x" src="https://user-images.githubusercontent.com/28145373/73085389-a1e23c00-3e9c-11ea-9b7a-b934c676cb1b.png">

------
Reproduced with 1.3.x:
1. Install 0.63.55 (Release)
2. Enable Rewards, trigger an Ad
3. Close. Rename profile to Beta.
4. Launch Beta 1.3.99
5. Navigate to brave://rewards
---> multiple issues on page:
   - Uh Oh message on wallet panel
   - Ads viewed this month is reset to 0/Estimated pending shows 0
   - No date for Ads payout
   - AC is toggled off
   - if I scroll down, my 'Monthly Contributions' panel date is screwed up (says Dec 31)

0.63.55 before upgrading to 1.3.99:
<img width="1194" alt="0 63 55 before" src="https://user-images.githubusercontent.com/28145373/73085518-d1914400-3e9c-11ea-8e35-7e6840e0bf1f.png">

after upgrade to 1.3.99:
<img width="1194" alt="1 3 99 after relaunch" src="https://user-images.githubusercontent.com/28145373/73085538-d7872500-3e9c-11ea-8b89-df23f68df850.png">

Toggling Rewards off/on resets the Ads panel visually at least. However, it doesn't fix the 'Uh oh' message. Additionally, when doing this, then i see the "Wallet Creation Failed" on the panel:
<img width="1787" alt="1 3 99 after Rewards toggle" src="https://user-images.githubusercontent.com/28145373/73085576-e7066e00-3e9c-11ea-93d7-bfb210d596d6.png">


Brave | 1.3.99 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.3.107 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
- Verified https://github.com/brave/brave-browser/issues/7833#issuecomment-578202969
 **Before upgrade 0.63.55** 
![image](https://user-images.githubusercontent.com/38657976/73672314-a85d8880-46d2-11ea-8d1d-b145e9be65f4.png)
**After upgrade 1.3.107**
![image](https://user-images.githubusercontent.com/38657976/73672431-db078100-46d2-11ea-80cb-319592b92693.png)
