### ISSUE TITLE
no AC notifications in certain cases

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7836]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/7185

In certain cases there is no auto contribute notification on the BAT logo. Note, AC is not being recorded in the summary as well, but this is logged with #7526 

## Steps to Reproduce

Scenario 1:
   1. Launch 1.3.x with staging flags and short reconcile interval.
   2. Enable Rewards (do not claim UGP grant). Connect KYC'd (sandbox) Uphold account. Add BAT to Brave Browser card if empty.
   3. Set up AC table to have a mix of verified and non verified sites. Choose monthly budget based on your wallet (mine was 5 BAT)
   4. Wait for AC to go thru.

Scenario 2:
   1. Launch 1.2.43 (release) with staging flags and short reconcile interval
   2. Enable Rewards (do not claim UGP grant). Restore/have a self-funded anon wallet (if you need info on this, DM me)
   3. Set up AC table to have a mix of verified and non verified sites. Choose monthly budget based on your wallet (mine was 15 BAT)
   4. Close 1.2.x before AC can occur.
   5. "Upgrade" (rename profile to Beta) to 1.3.x
   6. Wait for AC to go thru.

## Actual result:
Wallet balance decreases by AC amount, but no AC notification on BAT logo.

## Expected result:
There should be an AC notification on the BAT logo to indicate that AC has processed as there was in 1.2.x:
<img width="1194" alt="Screen Shot 2020-01-21 at 9 44 54 AM" src="https://user-images.githubusercontent.com/28145373/72814288-cd61ee00-3c32-11ea-8a8c-0aad54e3b694.png">

<img width="669" alt="Screen Shot 2020-01-21 at 9 45 20 AM" src="https://user-images.githubusercontent.com/28145373/72814299-d2bf3880-3c32-11ea-9f10-28f46b627910.png">

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 1.3.97 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

## Miscellaneous Information:
cc @NejcZdovc @rebron @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
The auto contribution is not happening in one more scenario:

1. Clean profile 1.2.43 launch with --rewards=staging=true,reconcile-interval=2
2. Enable rewards and connect KYC'd uphold account
3. Add a verified site to a-c table and wait for AC to complete
4. AC has happened and wallet balance deducted correctly and AC notification is shown
5. Upgrade to 1.3.97
6. Add a verified site to a-c table and wait for auto contribution

Actual: AC did not happen and there is no AC notification on BAT logo

**Comment by LaurenWags** [comment]
Retested on Nightly after https://github.com/brave/brave-core/pull/4372 and https://github.com/brave/brave-core/pull/4399 were merged. Could not reproduce. Moving to 1.3.x milestone so this can be retested on 1.3.x after those PRs are uplifted. Adding `QA/Blocked` label until they are uplifted.


Brave | 1.5.53 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.3.105 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

* Verified STR from description

Scenario 1:
<img width="760" alt="7836-scenario1" src="https://user-images.githubusercontent.com/28145373/73463364-21638580-434b-11ea-9e6e-e00fb8a6b1b9.png">

Scenario 2:
<img width="789" alt="7836-scenario2" src="https://user-images.githubusercontent.com/28145373/73463357-1f99c200-434b-11ea-8a0b-8d4fff14783c.png">
