### ISSUE TITLE
Remove light mode on second launch

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7839]
## Description 
Remove light mode on second launch

## Steps to reproduce 

   1. Install beta/nightly build 
   2. Change a setting to trigger relaunch or manually quit and relaunch the browser
   3. Lite mode message is shown which is a Chrome feature

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/72820397-e53e6f80-3c3c-11ea-9752-9503e9e10240.png)

## Expected result
No lite mode

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 9.0
   
## Brave version
1.5.46 Nighlty build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional information

cc: @bbondy @anthonypkeane @SergeyZhukovsky please move this to `android-core-release` if required

**Comment by yrliou** [comment]
I'm not able to reproduce this from my end in arm or arm64 builds.

**Comment by srirambv** [comment]
@yrliou could be arm64 specific

**Comment by yrliou** [comment]
I could not reproduce this one using arm64 apk on Pixel 3. :(

**Comment by emerick** [comment]
Didn't we disable the FRE? I think this is considered a FRE component.

**Comment by yrliou** [comment]
We did disable FRE already, @srirambv could you try again to see if you could reproduce this since I couldn't? Thanks.

**Comment by SergeyZhukovsky** [comment]
That one is different, it was disabled here https://github.com/brave/brave-core/pull/4455

**Comment by SergeyZhukovsky** [comment]
Removed in that PR https://github.com/brave/brave-core/pull/4455

**Comment by srirambv** [comment]
Verification passed on OnePlust 6T with Android 10 running 1.6.24 nightly x64 build
- Verified light mode is not shown when app is relaunched 
-----
Verification passed on Samsung Tab A with Android 9.0 running 1.6.24 nightly x64 build
- Verified light mode is not shown when app is relaunched 
-----
