### ISSUE TITLE
After excluding a site from A-C table `Show All` link is not shown in ac table

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7840]
## Description 

After excluding a site from A-C table `Show All` link is not shown

## Steps to Reproduce

   1. Clean profile 1.3.97
   2. Enable rewards
   3. Add a site to a-c table
   4. Exclude the added site by clicking on Trash icon 
   5. After excluding a site from A-C table `Show All` link is not shown

## Actual result:

After excluding a site from A-C table `Show All` link is not shown in ac table
![Show all link missing](https://user-images.githubusercontent.com/38657976/72822942-f026ed80-3c98-11ea-9302-e858049ffab0.gif)

## Expected result:

After excluding a site from A-C table `Show All` link should be shown in a-c table

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.3.97 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron

**Comment by btlechowski** [comment]
Not reproducible on Ubuntu. Maybe a timing problem?

Brave | 1.3.97 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Ubuntu 18.04 LTS

![7840](https://user-images.githubusercontent.com/34715963/72824844-40408880-3c76-11ea-9109-91652b1eb67d.gif)

**Comment by kjozwiak** [comment]
Seems like this specific to Windows. I couldn't reproduce the issue using `macOS 10.15.2 x64` but easily reproduced with `Win 10 x64` using the STR @GeetaSarvadnya provided.

#### Couldn't reproduce on `macOS 10.15.2 x64`:

Brave | 1.3.97 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.15.2 (Build 19C57)

#### Reproduced on `Win 10 x64`:

Brave | 1.3.97 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
--- | ---
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1909 (Build 18363.592)

**Comment by kjozwiak** [comment]
@rebron @NejcZdovc this is a regression we might want to consider fixing this on `1.3.x` as it affects the most popular platform.

**Comment by btlechowski** [comment]
This issue is not reproducible on 1.5.57 on Windows 7 x64 and Windows 10 x64

![image](https://user-images.githubusercontent.com/34715963/73086088-374af380-3ed0-11ea-83dd-b3d107a822f2.png)

Brave | 1.5.57 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.5.57 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1909

We should retest when https://github.com/brave/brave-core/pull/4372 and https://github.com/brave/brave-core/pull/4399 are uplifted.

**Comment by kjozwiak** [comment]
Believe we should be able to QA this now that https://github.com/brave/brave-core/pull/4448 & https://github.com/brave/brave-core/pull/4438 have been uplifted into `1.3.x`.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.3.110 Chromium: 80.0.3987.78 (Official Build) (64-bit)
-- | --
Revision | cb5aa81cb0a3a2c674b93bc7ffb34a86cd3b4802-refs/branch-heads/3987@{#752}
OS | Windows 10 OS Version 1803 (Build 17134.1006)
- Verified SR from the description
- The issue is still not fixed logged a follow-up issue https://github.com/brave/brave-browser/issues/8071
