### ISSUE TITLE
Remove welcome splash screen on first launch

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7841]
## Description 
Remove welcome splash screen on first launch. Follow up to  #4732

## Steps to reproduce 

   1. Clean install nightly build
   2. Launch browser
   3. Spalsh screen is shown

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/72823853-55032900-3c42-11ea-9458-42ce3653a90c.png)

## Expected result
No splash screen

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? On Nightly 

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 9.0
   
## Brave version
1.5.46 Nightly 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome?  NA

### Additional information

cc: @emerick @yrliou

**Comment by yrliou** [comment]
Note that it is working on arm builds but not arm64 builds at the moment. https://github.com/brave/brave-core/pull/4419 will fix the arm64 case.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.57 x64 nightly build
- Verified clean install doesn't show splash screen and start onboarding right away
- Verified updating from older version doesn't show splash screen as well
------
Verification passed on Samsung Tab A with Android 9 running 1.5.57 x64 nightly build
- Verified clean install doesn't show splash screen and start onboarding right away
- Verified updating from older version doesn't show splash screen as well
