### ISSUE TITLE
CI builds doesn't contain Brave version number

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7842]
## Description 
CI builds doesn't contain Brave version number

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/72825190-98f72d80-3c44-11ea-92f8-25b6dffda672.png)

## Expected result
Brave version should be properly populated

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 9.0
   
## Brave version
1.5.46 nightly

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by emerick** [comment]
Looking at the Jenkins log file for this build, I think this may be the issue (from the `gn` parameters at the beginning of the build):

```android_override_version_name=\"0.0.0\"```

I'm not quite sure how the versioning works on the standard brave-core releases, but for Android we expect this value to be set to the desired version number. We can probably tweak that if it's unacceptable (although I'm not sure exactly how much flexibility we have there...)

cc: @mihaiplesa @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
@emerick yes, we don't provide it on CI, @mihaiplesa is working on that.

**Comment by srirambv** [comment]
- Verification passed on OnePlus 6T with Android 10 
![image](https://user-images.githubusercontent.com/17010094/73089586-9430b480-3ea4-11ea-852a-4d1f9c15c52b.png)
- Verification passed on Samsung Tab A 
![image](https://user-images.githubusercontent.com/17010094/73089998-70ba3980-3ea5-11ea-85a6-7da74d26a058.png)
