### ISSUE TITLE
apt update via Ubuntu showing public key error

### ISSUE THREAD

**Issue by willstocks** [brave/brave-browser#7843]
## Description 

`sudo apt update` on Ubuntu 19.10 results in the following error:

```
Get:6 https://brave-browser-apt-release.s3.brave.com eoan InRelease [3,162 B]  
Err:6 https://brave-browser-apt-release.s3.brave.com eoan InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A8580BDC82D3DC6C


W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://brave-browser-apt-release.s3.brave.com eoan InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A8580BDC82D3DC6C
W: Failed to fetch https://brave-browser-apt-release.s3.brave.com/dists/eoan/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A8580BDC82D3DC6C

```

## Steps to Reproduce

   1. Open terminal
   2. sudo apt update
   3. See error

## Actual result:

```
Get:6 https://brave-browser-apt-release.s3.brave.com eoan InRelease [3,162 B]  
Err:6 https://brave-browser-apt-release.s3.brave.com eoan InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A8580BDC82D3DC6C


W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://brave-browser-apt-release.s3.brave.com eoan InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A8580BDC82D3DC6C
W: Failed to fetch https://brave-browser-apt-release.s3.brave.com/dists/eoan/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A8580BDC82D3DC6C
```

## Expected result:
No error, Brave should update

## Reproduces how often: 

I only have one Ubuntu machine available and can't get around it so far

## Brave version (brave://version info)

Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by BachoSeven** [comment]
I can reproduce the issue with the Beta Channel; in fact the key missing is exactly the same one when doing sudo apt update.

This is also related: https://askubuntu.com/questions/1180355/how-do-i-install-brave-browser-if-my-key-is-expired-and-wont-update

**Comment by willstocks** [comment]
Hi guys,
Any luck/advice please? Still unable to upgrade on Ubuntu, stuck on v1.0.1!
@srirambv (apologies, you added the label) is there a fix/solution/workaround?

**Comment by rebron** [comment]
@willstocks can you try this and see if it works with this command? After that can you apt update and see if that works.

`curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -`

cc: @mbacchi @fmarier

**Comment by willstocks** [comment]
@rebron  - THANK YOU!! :grin: 

That has done the trick and I'm now getting updates again. I had tried pulling in keys via other means (off of the back of good old Google searches) to no avail. But this has resolved the issue for me and I'm now on 1.4.96 :+1: 

Might be worth adding this to some documentation somewhere, just in case?

**Comment by rebron** [comment]
@willstocks Glad that worked!

Documentation here: https://brave-browser.readthedocs.io/en/latest/installing-brave.html
If you have suggestions to clarify the docs, please feel free to create a new issue.

**Comment by willstocks** [comment]
Hey @rebron 
Sorry, just wanted to check - I've just upgraded from Ubuntu 19.10 -> 20.04 and I've suddenly started seeing this key error again.
Is there a particular process that needs to be followed for Brave when upgrading Ubuntu?

**Comment by BachoSeven** [comment]
Hi, i also recently upgraded 18.04=>20.04. The upgrade automatically
disables all PPAs, so I guess it might have disabled the gpg key as well. I
would suggest just follow the installation instructions again and it should
work

**Comment by bsclifton** [comment]
what @BachoSeven said - try the steps from https://brave-browser.readthedocs.io/en/latest/installing-brave.html again @willstocks and let us know if that squares away the issue 😄 Maybe the keys were invalidated on upgrade? or it's possible the old package with the keychain was removed during the upgrade

**Comment by SQReder** [comment]
Just bumped into this when following [installation instructions](https://brave.com/linux/#release-channel-installation) on Ubuntu 20.04. 
```
Get:2 https://brave-browser-apt-release.s3.brave.com stable InRelease [4,317 B]                                                                                                                           
Hit:3 https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3003 focal InRelease                                                                               
Err:2 https://brave-browser-apt-release.s3.brave.com stable InRelease                                                    
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A8580BDC82D3DC6C
```

**Comment by fmarier** [comment]
@SQReder Did this step succeed?
```
sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
```
Do you get the same output as me if you run the following?
```
$ md5sum /usr/share/keyrings/brave-browser-archive-keyring.gpg
54024f7bfef85749173de7ef859ca68b  /usr/share/keyrings/brave-browser-archive-keyring.gpg
```

**Comment by SQReder** [comment]
The solution was `sudo chmod 644 /usr/share/keyrings/brave-browser-archive-keyring.gpg`
By some reason key was stored with `600` permissions, so apt just can't read the content

**Comment by mfskanpur** [comment]
sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg  
This command works and has solved the problem
