### ISSUE TITLE
Remove conversion tracking from ads setting page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7845]
## Description 
Remove conversion tracking from ads setting page

## Steps to reproduce 

   1. Install 1.5.46 nightly build
   2. Enable rewards and open ads settings page
   3. Has Chromium conversion option

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/72829129-28540f00-3c4c-11ea-87ef-22384aca17f1.png)

## Expected result
No conversion option

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? yes on 1.5.46 nightly

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 9.0
   
## Brave version
1.5.46 x64 nightly build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional information

Need to check if this is shown on CI build for beta

**Comment by yrliou** [comment]
@srirambv I think it's our own feature implemented in https://github.com/brave/brave-core/pull/4253 instead of chromium stuff.

**Comment by SergeyZhukovsky** [comment]
yeah it's definitely not from Chromium as the page is ours

**Comment by srirambv** [comment]
Thanks @yrliou. There was no mention of this for Android in the issue nor there was an issue logged specifically for Android so I wasn't aware. Going to close as expected.
