### ISSUE TITLE
Weave Sync 1.1

### ISSUE THREAD

**Issue by smnthermes** [brave/brave-browser#7846]
## Description 

It would be great to adopt Weave Sync 1.1, which is time-tested and more secure than that currently adopted by Firefox.

**Comment by srirambv** [comment]
Can you add more info on this? This is more of a generalised suggestion without any details.

**Comment by bsclifton** [comment]
Based on a quick search, I don't think this is something we can support. This appears to be a specific  Firefox extension?
https://weave-sync.en.uptodown.com/windows
