### ISSUE TITLE
Toolbar Buttons should be squarer

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#785]
Circle -> Square, see design spec for specific detail.

![image](https://user-images.githubusercontent.com/741836/44355971-e6c1a200-a462-11e8-97a0-c37ac28ae3bf.png)

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux
