### ISSUE TITLE
`Choose Device Type` modal is not shown after going offline and back online

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#7854]
Found when testing new sync UI changes https://github.com/brave/brave-browser/issues/6941.

## Steps to Reproduce

   1. Open `brave://sync`
   2. Go offline
   3. Click `Start a new Sync Chain`
   4. Wait a minute
   5. Go online
   6. Wait till `Choose Device Type` modal is shown

IMPORTANT: after page reload, the modal is shown

## Actual result:

`Choose Device Type` modal is not shown
The UI is stuck on sync creation
![image](https://user-images.githubusercontent.com/34715963/72851559-45202f00-3cac-11ea-8796-cbee1a903d4c.png)

## Expected result:
`Choose Device Type` modal is shown
![image](https://user-images.githubusercontent.com/34715963/72851616-63862a80-3cac-11ea-90d9-9741bcd8b520.png)

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.5.46 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @rebron @cezaraugusto @AlexeyBarabash @jsecretan

**Comment by cezaraugusto** [comment]
@AlexeyBarabash do you think we can intercept offline requests in the back-end? Doing this with JavaScript is not reliable since there's no native listener in WebAPIs for offline events.

**Comment by AlexeyBarabash** [comment]
@cezaraugusto I agree, doing this with javascript  in UI is not an option.
I think we have the error event for such case but I need to check why it isn't passed to UI.

**Comment by AlexeyBarabash** [comment]
This is not applicable now, because with Sync v2 when we press `Start a new Sync Chain` - then the passphase is generated but there is no any communication with the server, so offline/online doesn't have any effect on this.

And even I would do:
1. go offline 
2. create sync chain
3. go online
- then the chain gets created.

So I am closing this issue.
