### ISSUE TITLE
Move top sites widget to the top when stats are hidden regardless of clock

### ISSUE THREAD

**Issue by wooque** [brave/brave-browser#7855]
## Description 
When stats are hidden, top sites don't move to the top unless clock widget is hidden also.

## Steps to Reproduce

   1. Open new tab page 
   2. Hide Brave stats 

## Actual result:

![2020-01-22-002445_1919x412_scrot](https://user-images.githubusercontent.com/1936195/72852030-a268b000-3cad-11ea-97df-d2c6076edcb6.png)

## Expected result:
Top sites are on top even with clock widget shown, something like in pic related
![2020-01-22-002552_1919x253_scrot](https://user-images.githubusercontent.com/1936195/72852154-09866480-3cae-11ea-89f1-c269c7ef3c00.png)

## Reproduces how often: 

Always reproduced

## Brave version (brave://version info)

Brave | 1.2.43 Chromium: 79.0.3945.130 (Official Build) unknown (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Linux
JavaScript | V8 7.9.317.33
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Command Line | /usr/lib/brave-bin/brave --enable-features=OverlayScrollbar --disable-features=TabHoverCards --disable-smooth-scrolling --enable-gpu-rasterization --ignore-gpu-blacklist --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator,OverlayScrollbar --disable-features=LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AutofillServerCommunication,UnifiedConsent,WebXrGamepadModule,AllowPopupsDuringPageUnload,SyncUSSBookmarks,WebXR,AudioServiceOutOfProcess,SmsReceiver,TabHoverCards --flag-switches-begin --disable-oop-rasterization --flag-switches-end --disable-webrtc-apm-in-audio-service
Executable Path | /usr/lib/brave-bin/brave
Profile Path | /home/vuk/.config/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? /
- Does the issue resolve itself when disabling Brave Rewards? /
- Is the issue reproducible on the latest version of Chrome? /

**Comment by bsclifton** [comment]
cc: @cezaraugusto

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.3.108 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

* Reproduced the issue using 1.2.43:
<img width="1193" alt="Screen Shot 2020-02-04 at 3 18 47 PM" src="https://user-images.githubusercontent.com/28145373/73783504-cc1bdf80-4761-11ea-8d4c-d59f7ae017e1.png">

* Verified STR from description:
<img width="1197" alt="Screen Shot 2020-02-04 at 3 19 27 PM" src="https://user-images.githubusercontent.com/28145373/73783564-e81f8100-4761-11ea-8e8e-c2eed08192d9.png">

* Verified top sites move back down when stats are re-enabled

* Verified for clean and upgrade profiles
