### ISSUE TITLE
Migrate mojo types for Ads service

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#7856]
This is a part of the migration #7056, please see the meta issue for more details.

**Comment by yrliou** [comment]
Test plan is specified in the PR.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.5.109 Chromium: 80.0.3987.132 (Official Build) beta (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/4224
