### ISSUE TITLE
CI skips audit_deps for everything in vendor/

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#7857]
If you look at the output of `npm run audit_deps` in CI, for instance https://ci.brave.com/job/brave-browser-build-pr/job/PR-7847/2/consoleText, you will see a lot of lines like:

```
Skipping audit of ... /vendor/foobar
```

which indicate that `/vendor/foobar` doesn't contain a node_modules/, package.json, and package-lock.json. This is expected for directories that aren't node packages, but it should be running for vendor/hashset-cpp and vendor/bloom-filter-cpp, which are indeed node packages.

This suggests that maybe audit_deps is running before npm install has run in the vendor directories. 

Expected result:
- `npm run audit_deps` output in CI should show `Auditing ... /vendor/{hashset, bloom-filter}-cpp` instead of skipping. Which is the result if you run it locally.

**Comment by bsclifton** [comment]
Closing as this sounds like expected behavior per convo with @diracdeltas and @bbondy - some of the content under there is referenced, but not used in a node.js context
