### ISSUE TITLE
Location Bar border style

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#786]
Outset shadow, border radius, focus color

![image](https://user-images.githubusercontent.com/741836/44356197-7f582200-a463-11e8-8d02-1b2d9632d648.png)

**Comment by btlechowski** [comment]
Verification passes on

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

Checked Light and Dark theme
