### ISSUE TITLE
Connect to wallet popup needs to be responsive to browser window size 

### ISSUE THREAD

**Issue by DaniellMesquita** [brave/brave-browser#7862]
![brave align error](https://user-images.githubusercontent.com/6765277/72858566-07b5a480-3ca0-11ea-8eac-6b7b698b12b1.png)

**Comment by srirambv** [comment]
Can you please add component version and browser version? What is the default resolution set at?

**Comment by DaniellMesquita** [comment]
Versions and resolution doesn't matter. It is on MetaMask itself. I suggest changing it upstream.

To simply explain, the MetaMask popup's design have a fixed size. It should be fluid. See the bottom buttons. It should be responsible instead of fixed heights.

**Comment by srirambv** [comment]
Was checking if the default zoom level is at a higher %. May also be fixed with #7045

**Comment by srirambv** [comment]
Closing in favour of #7882 which has more details
