### ISSUE TITLE
Application crashes when calculating the winning page classification category

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#7866]
## Description 

Application crashes when calculating the winning page classification category to decide which ads to show to the user

## Steps to Reproduce

   1. Change the OS locale to "United States"
   2. View a Brave Ad
   3. Quit the browser
   4. Change the OS locale to an untargeted locale (such as Denmark)
   5. Launch the browser
   6. View a Brave Ad

## Actual result:

The application crashes when calculating the winning page classification category
Application crashes

## Expected result:
The application should not crash when calculating the winning page classification category
Brave Ad should be shown and application should not crash

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by tmancey** [comment]
Issue has been reproduced on Android https://github.com/brave/brave-browser/issues/8415#event-3075046350, awaiting state files from @SergeyZhukovsky to reproduce

**Comment by tmancey** [comment]
Raised this issue to fix crashes 4 and 7 for https://github.com/brave/browser-android-tabs/issues/2435

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified STR from the description
