### ISSUE TITLE
Investigate Chromium XPC service native notification changes for macOS Catalina

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#7867]
Investigate Chromium XPC service native notification changes for macOS Catalina as it would appear they are working again. This was highlighted by @bridiver as he had two entries in Preferences > Notifications > Brave Browser under Chrome

**Comment by bridiver** [comment]
correction: I had to entries for Chrome

**Comment by tmancey** [comment]
> correction: I had to entries for Chrome

Thanks, I have updated the description

**Comment by tmancey** [comment]
Investigated and Chromium now supports the XPC service for Alert notifications on macOS Catalina. I have raised https://github.com/brave/brave-browser/issues/9998
