### ISSUE TITLE
3rd-party cookie shield prevents slideshare.net navigation 

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#7868]
## Description 
Visit: `https://support.blogactiv.eu/2015/04/24/how-to-embed-slideshare/` Embedded Slideshare doesn't navigate.

## Steps to Reproduce

   1. `https://support.blogactiv.eu/2015/04/24/how-to-embed-slideshare/`
   2.  Click arrow buttons, nothing happens
   3. 

## Actual result:
Non-functional slideshare.net element

## Expected result:
Allow Slideshare.net navigation element to work

## Reproduces how often: 
Easily.

## Brave version (brave://version info)
`Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
Blocking 3rd-party cookies for slideshare.net will prevent naviagtion, `Allow All Cookies` will fix this.

**Comment by ryanbr** [comment]
2 domains being used;

```
"https://*.slideshare.net/*"
"https://*.slidesharecdn.com/*"
```

**Comment by ryanbr** [comment]
Shot in the dark from https://github.com/brave/brave-core/compare/fix-google-drive-autoplay-bj  But I could be wrong.

`constexpr char kSlideshare[] = "https://[*.]slideshare.net/*";`
`constexpr char kSlidesharecdn[] = "https://[*.]slidesharecdn.com/*";`

`          {
            ContentSettingsPattern::FromString(kSlideshare),
            ContentSettingsPattern::FromString(kSlidesharecdn)},
          {
            ContentSettingsPattern::FromString(kSlidesharecdn),
            ContentSettingsPattern::FromString(kSlideshare)
          },
`

**Comment by pes10k** [comment]
I see this in the logs

```Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://public.slidesharecdn.com/ss_foundation/combined_player_presentation.js?1801753e9b:1:15785
```

I think the better solution here is https://github.com/brave/brave-browser/issues/8514, which would be a good, systematic level fix

**Comment by pes10k** [comment]
That being said, once https://github.com/brave/brave-core/pull/5433 lands, i'd be a-ok adding these exceptions in, but would like to mark them for removal once https://github.com/brave/brave-browser/issues/8514 lands

**Comment by ryanbr** [comment]
This is now working, closing ticket.
