### ISSUE TITLE
Duplicate Brave Ads ad history entries are missing

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#7869]
## Description 

Duplicate Brave Ads ad history entries are missing

## Steps to Reproduce

   1. View the same ad twice (clicking one of the ads)

## Actual result:

Duplicate Brave Ads ad history entries are missing

## Expected result:
Duplicate Brave Ads ad history entries should be shown

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.5.109 Chromium: 80.0.3987.132 (Official Build) beta (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4421
Verified for all ads states (clicked, dismissed, viewed)
Verified ads are shown across multiple days
Verified that ads older than 7 days are not shown

![image](https://user-images.githubusercontent.com/34715963/76262644-36daa200-625d-11ea-8711-8396a90ef131.png)
![image](https://user-images.githubusercontent.com/34715963/76263248-af8e2e00-625e-11ea-9275-5602d21f5ad0.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.5.109 Chromium: 80.0.3987.132 (Official Build) beta (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/4421
- Duplicate ads entries are shown in ads history
![image](https://user-images.githubusercontent.com/38657976/76291714-ad19eb80-62d3-11ea-8223-1c2591847bca.png)
