### ISSUE TITLE
Tab Shape

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#787]
90 degree bottom border (with no outset curve like Chromium). 4px rounded top borders.  No overlap unlike Chromium.

![image](https://user-images.githubusercontent.com/741836/44356312-d2ca7000-a463-11e8-900f-a8f6c0456d1f.png)

![image](https://user-images.githubusercontent.com/741836/44356314-d5c56080-a463-11e8-8afa-a81464cfd8b8.png)

**Comment by btlechowski** [comment]
Verification passes on

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7
