### ISSUE TITLE
Remove Download articles from Downloads section

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7872]
## Description 
Remove Download articles from Downloads section

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/72912691-03be6c80-3d0a-11ea-952a-d53f29853266.png)

## Expected result
![image](https://user-images.githubusercontent.com/17010094/72912766-20f33b00-3d0a-11ea-842e-863cdab59535.png)

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.5.50 Nightly 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
This is not fixed on 1.5.110 x64 stable build
![artcile-download](https://user-images.githubusercontent.com/17010094/76515933-7fbe7080-6480-11ea-97ec-13685733a538.gif)

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.5.111 BraveModernx86.apk
- Verified no option for download articles in downloads page
- Verified no tab for downloaded articles in downloads page
- see also https://github.com/brave/brave-browser/issues/8658#issuecomment-599335490
