### ISSUE TITLE
Unable to select allow conversion tracking option from Ads settings

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7873]
## Description 
Unable to check `Allow conversion tracking`

## Steps to reproduce 

   1. Install 1.5.50 nightly build
   2. Enable rewards and open ads settings page
   3. Unable to check allow conversion tracking checkbox

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/72829129-28540f00-3c4c-11ea-87ef-22384aca17f1.png)

## Expected result
Should be able to enable the setting 

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? 1.5.50 nightly

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.5.50 x64 nightly build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by tmancey** [comment]
@srirambv Duplicate of https://github.com/brave/brave-browser/issues/7901, if you could check and close this issue that would be great. thanks

**Comment by srirambv** [comment]
Issue is marked for 1.5.x desktop milestone. If #7901 is only for Android then we can close this one as dupe.  If its applicable to desktop as well then better to keep this issue separate for desktop and Android.

**Comment by srirambv** [comment]
Closing as dupe of #7901 after discussing with @tmancey
