### ISSUE TITLE
C80 followup: Convert to using base::flat_map instead of std::map.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#7874]
Follow up on #7255. (commit `Readded std::map and base::flat_map conversion functions.`)

In Chromium 80, conversion functions between std::map and base::flat_map (MapToFlatMap and FlatMapToMap) which used to live in mojo, have been removed since Chromium converted all code using mojo to base::flat_map instead of std::map. We should do the same.

**Comment by mariospr** [comment]
I was thinking of picking it up this issue, but I have a question: is the scope of this task to replace **all instances** of std::map inside of `src/brave/` with base::flat_map, or just those ones that are currently forcing to keep those MapToFlatMap() and FlatMapToMap() helpers around?

**Comment by mariospr** [comment]
@mkarolin Just clarified offline that only the cases that are forcing us to keep those conversions around should be targeted, so I'll focus on those ones.
