### ISSUE TITLE
C80 followup: Fix Component build

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#7875]
This is a followup issue for #7255.

Component build errors out with a number of Java Lint warnings (being converted to errors).
Debug or Release build don't show these errors.

Most of the errors are for unused import statements, similar to:
<pre>
../../brave/android/java/org/chromium/chrome/browser/toolbar/bottom/BraveBottomToolbarCoordinator.java:17: error: [RemoveUnusedImports] Unused imports
import org.chromium.base.Log;
^
    (see https://errorprone.info/bugpattern/RemoveUnusedImports)
  Did you mean to remove this line?
</pre>

or for multiple variables declarations via commas, similar to:
<pre>
../../brave/browser/brave_ads/android/java/org/chromium/chrome/browser/onboarding/BraveAdsOnboardingFragment.java:45: error: [MultiVariableDeclaration] Variable declarations should declare only one variable
    private Button btnStartBrowsing, btnDidntSeeAd;
                   ^
    (see https://google.github.io/styleguide/javaguide.html#s4.8.2.1-variables-per-declaration)
  Did you mean 'private Button btnStartBrowsing;private Button btnDidntSeeAd;'?
</pre>

However, fixing all these (removing unused imports) leads to a stream of `unknown symbol` errors all of which seem to be JNI imports. These show up in Debug/Component/Release builds once the unused imports are removed.

cc: @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
We don't use component build on Android as low end devices have a limited amount of dynamic libraries that could be loaded(around ~30) and it just crashes on such devices. It would be good to fix that but not a top priority for now
