### ISSUE TITLE
C80 followup: [Android] Build warning for using an array as a key in a map.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#7876]
When build Component build for Chromium 80 the following warning is produced by Java lint:
<pre>
../../brave/android/java/org/chromium/chrome/browser/qrreader/CameraSource.java:161: warning: [ArrayAsKeyOfSetOrMap] Arrays do not override equals() or hashCode, so comparisons will be done on reference equality only. If neither deduplication nor lookup are needed, consider using a List instead. Otherwise, use IdentityHashMap/Set, a Map from a library that handles object arrays, or an Iterable/List of pairs.
    private Map<byte[], ByteBuffer> mBytesToByteBuffer = new HashMap<>();
                                                         ^
    (see https://errorprone.info/bugpattern/ArrayAsKeyOfSetOrMap)
</pre>

The code may potentially not be working as intended since the key comparison is not done by the array value.

cc: @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
The code is used for QR code reading for sync functionality. I verified it works as expected regardless the warning. In the future we probably should switch to `zxing` lib code reader that we use already for QR code generation. The current QR reading code is old, so it will be a good switch. Closing it for now as it works as expected.
