### ISSUE TITLE
relabel menu item from 'remove' to 'hide' 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#7877]
## Description 
For New Tab page widgets, rename the 'remove' label to 'Hide' to match show/hide versus add/remove terminology.

##Current screens
![68592443-689c5180-0493-11ea-9b75-653fdba635aa](https://user-images.githubusercontent.com/5951041/72928969-c956ce80-3d0d-11ea-8834-3fb651610a52.png)

![68592429-5fab8000-0493-11ea-9f29-e9e1a21b100c](https://user-images.githubusercontent.com/5951041/72928982-cf4caf80-3d0d-11ea-8a37-a703e2f586d0.png)

**Comment by rebron** [comment]
related to https://github.com/brave/brave-browser/issues/6395

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.5.101 Chromium: 80.0.3987.116 (Official Build) beta (64-bit)
-- | --
Revision | dc00a510e4c2ae25c4d084cc3d946fc782249224-refs/branch-heads/3987@{#917}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4425
<img width="1031" alt="Screen Shot 2020-02-26 at 3 03 33 PM" src="https://user-images.githubusercontent.com/28145373/75383122-c53c4480-58a9-11ea-8e38-a58ce6e5d782.png">

* Verified test plan using other widgets on page (stats, clock, rewards)
* Verified selecting to hide the widget does hide it from view
* Verified hidden widgets can be re-displayed using the Dashboard Settings
* Encountered https://github.com/brave/brave-browser/issues/6395 for dark theme
