### ISSUE TITLE
Can't play Hulu videos.

### ISSUE THREAD

**Issue by Chilcout** [brave/brave-browser#7879]
Everyt video I try to open, I get this error code: P-Dev302. I'm on windows 7 64

**Comment by srirambv** [comment]
Mind editing the issue and adding details as per template. The oneline statement is very generic and doesn't help narrow down the issue

**Comment by rebron** [comment]
Closing this one out. @Chilcout community.brave.com will be a better place to see if we can get this resolved for you. Would you mind reposting there.
