### ISSUE TITLE
Remove page info icon for chrome pages

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7880]
## Description 
Remove page info icon for chrome pages

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/72938124-5f9fea00-3d38-11ea-99df-ae88fc70b00c.png)

## Expected result
![image](https://user-images.githubusercontent.com/17010094/72938177-7ba38b80-3d38-11ea-9d40-55b144c21f6f.png)

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet): All
   - Android version: 10
   
## Brave version
1.5.50

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome?  NA

**Comment by emerick** [comment]
@srirambv Could you retry on the latest nightly? I'm not able to repro. I visited the chrome://safe-browsing page and a few others and no "i" button shows up in the URL bar.

**Comment by emerick** [comment]
Rechecked with the latest nightly and this still looks OK to me, so closing for now. If we have a specific page that we still see this with, please list it and reopen.

**Comment by emerick** [comment]
Reopening as I didn't realize that the "i" icon shows up in the bottom toolbar on a phone, not the URL bar.

**Comment by yrliou** [comment]
I think the issue original reported is resolved already, there're no page info icon in the URL bar.
I'll open a new one to capture that we need to replace the info button in the app menu with a share button.

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version running `BraveModernarm 1.5.110.apk`
![image](https://user-images.githubusercontent.com/38657976/76307250-7ef5d500-62ee-11ea-91fe-53c04adfa423.png)
