### ISSUE TITLE
Connect to wallet popup needs to be responsive

### ISSUE THREAD

**Issue by dginovker** [brave/brave-browser#7882]
## Description 

I was trying to pay for a [Forbes](https://www.forbes.com/sites/ktorpey/2020/01/21/billionaire-investor-sees-major-flaw-in-bitcoin-investment-thesis/#2c36d6814914) article using Crypto and I got a popup asking to set up my Brave wallet. I did and ended up on this screen:

![image](https://user-images.githubusercontent.com/32943174/72951145-6c820500-3d5b-11ea-8bad-03a4683301b5.png)

If I zoom out on the browser, I can see the connect button. I was confused for a good minute though: 

![image](https://user-images.githubusercontent.com/32943174/72951165-7dcb1180-3d5b-11ea-8a0e-83e72a9e98c1.png)

Note here is my display configuration:

![image](https://user-images.githubusercontent.com/32943174/72951169-83c0f280-3d5b-11ea-8c7f-e06a35df54e4.png)

## Steps to Reproduce

   1. Set display configuration to 1366x768
   2. Go to a page that asks you to link an account (no idea how, but asking to Pay with Ether in the Forbes link above made me do this)

## Actual result:

I couldn't see the "Connect" button

## Expected result:

I would be able to easily connect the accounts

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

```
Brave	1.2.41 Chromium: 79.0.3945.88 (Official Build) unknown (64-bit)
Revision	c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS	Linux
JavaScript	V8 7.9.317.32
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
Profile Path	/home/dr_cookie/.config/BraveSoftware/Brave-Browser/Default
```
(Removed the command line note \^)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Unknown
- Can you reproduce this issue with the dev channel? Unknown
- Can you reproduce this issue with the nightly channel? Unknown

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Unrelated
- Does the issue resolve itself when disabling Brave Rewards? Unrelated
- Is the issue reproducible on the latest version of Chrome? Unrelated

## Miscellaneous Information:

**Comment by srirambv** [comment]
+1 from @DaniellMesquita via #7862. 

@ryanml is this going to be fixed with https://github.com/brave/brave-browser/issues/7045?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.5.76 Chromium: 80.0.3987.66 (Official Build) nightly (64-bit)
-- | --
Revision | 56ea77d65c47ecbb1180b99f860d85b51117864a-refs/branch-heads/3987@{#662}
OS | Linux
Component | `0.1.37`

- Verified connect wallet popup in wallet page is responsive and shows vertical scrollbars 
![image](https://user-images.githubusercontent.com/17010094/73635613-e4b8c680-4689-11ea-91b3-1570c1fcb1c2.png)

**Comment by DaniellMesquita** [comment]
It isnt very responsive. There is yet a space between the bottom text and footer buttons.
