### ISSUE TITLE
New Tab Page Grid alignment should be more dynamic

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#7884]
- Allow items to fill in gaps left by other items which are turned off
 - Allow any item to fit next to any item, even if it occupies 2 rows (e.g. Branded Wallpaper Logo item, or Rewards item)

Test plan on https://github.com/brave/brave-core/pull/4075 (Items 9 and 10)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.3 x64` using the following build:

Brave | 1.3.108 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.15.3 (Build 19D76)

* Verified cases `9` & `10` as per https://github.com/brave/brave-browser/issues/7884#issue-553971727

### **`Different window sizes`**

<img width="1087" alt="Screen Shot 2020-02-04 at 4 45 50 PM" src="https://user-images.githubusercontent.com/2602313/73790288-39357200-476e-11ea-9f86-fb7404ab9818.png">

<img width="999" alt="Screen Shot 2020-02-04 at 4 46 03 PM" src="https://user-images.githubusercontent.com/2602313/73790287-39357200-476e-11ea-96e1-2b6058f09a7e.png">

<img width="896" alt="Screen Shot 2020-02-04 at 4 46 15 PM" src="https://user-images.githubusercontent.com/2602313/73790286-39357200-476e-11ea-8ca3-53269c9c4113.png">

### **`Stats widget disabled`**

<img width="1388" alt="Screen Shot 2020-02-04 at 4 47 06 PM" src="https://user-images.githubusercontent.com/2602313/73790367-5d914e80-476e-11ea-9f02-640d468f093c.png">

<img width="567" alt="Screen Shot 2020-02-04 at 4 50 23 PM" src="https://user-images.githubusercontent.com/2602313/73790443-7863c300-476e-11ea-9e46-9acfa77eb98c.png">

<img width="841" alt="Screen Shot 2020-02-04 at 4 50 07 PM" src="https://user-images.githubusercontent.com/2602313/73790445-7863c300-476e-11ea-9ab4-a576f6490709.png">

### **`Clock widget disabled`**

<img width="1099" alt="Screen Shot 2020-02-04 at 4 50 59 PM" src="https://user-images.githubusercontent.com/2602313/73790521-9d583600-476e-11ea-8d20-809bf6bd1887.png">

<img width="961" alt="Screen Shot 2020-02-04 at 4 51 08 PM" src="https://user-images.githubusercontent.com/2602313/73790532-a0ebbd00-476e-11ea-85b7-4f5ed69ce8f4.png">

<img width="859" alt="Screen Shot 2020-02-04 at 4 51 19 PM" src="https://user-images.githubusercontent.com/2602313/73790536-a3e6ad80-476e-11ea-82e8-13598e816d8e.png">

### **`Top Sites widget disabled`**

<img width="1066" alt="Screen Shot 2020-02-04 at 4 53 25 PM" src="https://user-images.githubusercontent.com/2602313/73790782-0dff5280-476f-11ea-935d-bdde85d0c644.png">

<img width="959" alt="Screen Shot 2020-02-04 at 4 55 00 PM" src="https://user-images.githubusercontent.com/2602313/73790891-443cd200-476f-11ea-9396-81fda971fe01.png">

<img width="800" alt="Screen Shot 2020-02-04 at 4 55 08 PM" src="https://user-images.githubusercontent.com/2602313/73790894-47d05900-476f-11ea-992f-8234c5aa1c4b.png">

### **`Other variations`**

<img width="1082" alt="Screen Shot 2020-02-04 at 4 56 10 PM" src="https://user-images.githubusercontent.com/2602313/73790918-54ed4800-476f-11ea-9b11-e295afd1da1b.png">

<img width="1000" alt="Screen Shot 2020-02-04 at 4 59 40 PM" src="https://user-images.githubusercontent.com/2602313/73791143-c3320a80-476f-11ea-8b94-739c89e315e2.png">
