### ISSUE TITLE
New Tab Page Rewards Widget re-style

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#7885]
## Description 
For the New Tab Page Branded Wallpapers feature, most of the Rewards widget was re-styled. This includes colors, strings, spacing and some layout.

### Pre opt-in
![image](https://user-images.githubusercontent.com/741836/72963031-f2f21300-3d6a-11ea-87aa-84ebcbba82e3.png)

### Opted in without Ads
![image](https://user-images.githubusercontent.com/741836/72963041-fbe2e480-3d6a-11ea-85cd-df0e4955e96c.png)

### Post opt-in
![image](https://user-images.githubusercontent.com/741836/72963050-04d3b600-3d6b-11ea-9537-ecf90a2b4397.png)

### Notification
![image](https://user-images.githubusercontent.com/741836/72963125-3fd5e980-3d6b-11ea-8632-1de620e9abf9.png)

### Pre opt-in
![image](https://user-images.githubusercontent.com/741836/72963211-77449600-3d6b-11ea-8b04-e61ef73b3811.png)

### Opted in without Ads
![image](https://user-images.githubusercontent.com/741836/72963190-6dbb2e00-3d6b-11ea-8145-bca75b14a17c.png)

### Post opt-in
![image](https://user-images.githubusercontent.com/741836/72963166-58460400-3d6b-11ea-8e01-4d14b65f32d5.png)

### Notification
![image](https://user-images.githubusercontent.com/741836/72963155-4fedc900-3d6b-11ea-81a4-f56dfd77899a.png)

## Brave version (brave://version info)

1.5.42

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.3.108 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

pre-opt in to Rewards (ever):
<img width="303" alt="pre-opt in" src="https://user-images.githubusercontent.com/28145373/73792090-a1398780-4771-11ea-9fce-0321d426123e.png">

re-opt in to Rewards (after it had been toggled off):
<img width="306" alt="re-opt in" src="https://user-images.githubusercontent.com/28145373/73792108-a8f92c00-4771-11ea-8139-9f1c8bf87c54.png">

opted in with Ads toggled off:
<img width="305" alt="opt in without ads" src="https://user-images.githubusercontent.com/28145373/73792120-aeef0d00-4771-11ea-80d7-436586c835cc.png">

opted into everything (with values to show it populated):
<img width="302" alt="post opt in with values" src="https://user-images.githubusercontent.com/28145373/73792143-b6161b00-4771-11ea-910e-59f0dba5ae40.png">

notification on widget:
<img width="301" alt="UGP grant notification" src="https://user-images.githubusercontent.com/28145373/73792161-be6e5600-4771-11ea-988b-abeb0dbe5bee.png">
