### ISSUE TITLE
Data is remained  after clearing site settings 

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#7886]
## Description 

Date is remained  after clearing site settings 

## Steps to Reproduce

   1. chrome://settings/clearBrowserData
   2. In Advanced tab, check `Site Settings` with `All time` range and Clear
   3. 

## Actual result:
<img width="821" alt="Screen Shot 2020-01-23 at 4 27 56 PM" src="https://user-images.githubusercontent.com/6786187/72965534-ea97e780-3dff-11ea-84f0-df5f31b9afed.png">

## Expected result:

It should be `None` instead of `1 site` after clearing
## Brave version (brave://version info)

Version 1.5.52 Chromium: 79.0.3945.130 (Developer Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by simonhong** [comment]
FYI, it's pattern is `account.google.com`, it's source is `preference`, it's type is `TYPE_COOKIE` and it's value is `1`. I got this info from `SiteSettingsCounter::Count()`.

**Comment by bsclifton** [comment]
@jumde unassigned you for the moment as there hasn't been an update; feel free to grab this if you have more bandwidth 😄

**Comment by jumde** [comment]
@simonhong @bsclifton - I'm not seeing this on beta anymore. Let me know if I'm missing any repro steps:

<img width="512" alt="Screen Shot 2020-03-30 at 9 40 54 AM" src="https://user-images.githubusercontent.com/1903815/77938505-ac3cff80-726a-11ea-8f56-3db7c9f034aa.png">

**Comment by rebron** [comment]
Seems like this is related to https://github.com/brave/brave-browser/issues/8842 based on https://github.com/brave/brave-browser/issues/7886#issuecomment-579090525

**Comment by bsclifton** [comment]
Closing as @jumde wasn't able to repro above and this hasn't had any recent activity

**Comment by simonhong** [comment]
Sorry for late response.
However, I still see this issue with nightly.
After clearing `Site and Shields Settings` with `All time` time range, I can see `Site and Shields Settings` is not `None`.

**Comment by jumde** [comment]
@simonhong - Do you see this if `Allow Google Logins` toggle is turned off in brave://settings/socialBlocking? To allow google oauth we add a cookie exception which shows up in the site data.

**Comment by simonhong** [comment]
@jumde After `Allow Google login buttons on third party sites` is off, the value of `Site and Shields Settings` is changed from `3 sites` to `2 sites`.

**Comment by jumde** [comment]
@simonhong - Some additional exceptions were added recently: https://github.com/brave/brave-core/blob/37110161e042202ace67a2ea49991c7d97210d9c/components/content_settings/core/browser/brave_content_settings_pref_provider.cc#L327

@pes10k is working on improving the cookie exceptions. But these exceptions are needed as a stop-gap.

**Comment by simonhong** [comment]
@jumde I see! thanks for explanation. Feel free to close if you think this issue is expected behavior.
