### ISSUE TITLE
Change Copy for "Allow conversion tracking" in Brave Ads "Ads Settings"

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#7887]
Change Copy for "Allow conversion tracking" in Brave Ads "Ads Settings" from:

<img width="640" alt="Screenshot 2020-01-23 at 08 43 22" src="https://user-images.githubusercontent.com/1188719/72968955-7c7e0100-3dbc-11ea-8b08-281678cb6929.png">

to:

Allow ad conversion detection

This will anonymously let Brave know that there was a response to an ad on this browser. Enabling this will increase earnings.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.5.102 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified description from the issue
![image](https://user-images.githubusercontent.com/38657976/75685351-71be6200-5cc0-11ea-86ea-04aaf30f6f62.png)
