### ISSUE TITLE
Hide rewards button doesn't work

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7889]
## Description 
Hide rewards button doesn't work

## Steps to reproduce 

   1. Clean install nightly build
   2. Enable hide rewards button under appearance
   3. Relaunch browser via prompt, rewards button still shows up in URL bar

## Actual result 
![20-01-23-10-38-18](https://user-images.githubusercontent.com/17010094/73000099-61b48800-3dce-11ea-979e-ea293fd33ad9.gif)

## Expected result
Should hide the button after relaunch

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.5.52 Nighlty

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by yrliou** [comment]
This one is fixed by https://github.com/brave/brave-core/pull/4429 too, closing. cc @SergeyZhukovsky

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.59 x64 build
- Hide rewards button removes the button after relaunch
-----
Logged issue for tablet https://github.com/brave/brave-browser/issues/7915
