### ISSUE TITLE
Ability to switch between Dark / Light mode

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#789]
A setting option to toggle between dark and light mode. Preference value must be available to `ThemeProperties::MaybeGetDefaultColorForBraveUi`

The setting should be available on all release channels, but defaulted to Light for Release and Beta and Dark for all other.

If there is an active theme installed, this setting could still be enabled since there may be some items that do not come from the theme.

- [x] Add `kBraveThemeType` preference in C++ (https://github.com/brave/brave-core/pull/351)
- [x] Add option to setting page (https://github.com/brave/brave-core/pull/361)

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux
