### ISSUE TITLE
C80 followup: Android bookmark button

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#7891]
Followup to #7255 

There have been changes to the share button methods. Since we use that button for bookmarks we need to take a look if the new methods needs to be implemented for the button to function properly.
Changes are in the commit `[Android] Changes to Share button id/methods. `

cc: @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
I checked that and it works as expected, doing nothing here.
