### ISSUE TITLE
Add developer options to Settings

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#7892]
Port developer settings from browser-android-tabs. These are primarily used by QA for testing purposes.

Original browser-android-tabs PRs:

https://github.com/brave/browser-android-tabs/pull/1571
https://github.com/brave/browser-android-tabs/pull/2206

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.6.24 nightly x64 build
- Verified settings under developer tools work as expected
------
Verification passed on Samsung Tab A with Android 9 running 1.6.24 nightly x64 build
- Verified settings under developer tools work as expected
