### ISSUE TITLE
Some bookmarks are not synced in 1.5.x

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#7893]
Issue is reproducible in 1.5.x. Not reproducible in 1.3.x and 1.4.x

## Steps to Reproduce

   1. Clean profile DeviceA and DeviceB
   2. DeviceA: open `interia.pl` and bookmark it
   3. DeviceA: create bookmark folder named `DeviceA`
   4. DeviceB: open `youtube.com` and bookmark it
   5. DeviceB: create bookmark folder named `DeviceB`
   6. DeviceA: create sync chain and copy code words
   7. DeviceB: enter code words
   8. Wait for sync

DeviceA: Windows 7x64
DeviceB: Ubuntu 18.04LTS

## Actual result:

Some bookmarks are missing
DeviceA is missing `youtube.com` bookmark:
![image](https://user-images.githubusercontent.com/34715963/73018602-44a9a480-3e22-11ea-9361-8ee78b1de928.png)

DeviceB is missing `interia.pl` bookmark:
![image](https://user-images.githubusercontent.com/34715963/73018626-512dfd00-3e22-11ea-9feb-ebe5ed68aac5.png)

Note: Browser relaunch does not fix the issue 

## Expected result:
All bookmarks and bookmark folders are synced

## Reproduces how often: 

100% repro rate with above STR

## Brave version (brave://version info)

**Reproducible on**

Brave | 1.5.53 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.5.53 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Linux

**Not reproducible on**

Brave | 1.4.67 Chromium: 79.0.3945.130 (Official Build) dev (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.4.67 Chromium: 79.0.3945.130 (Official Build) dev (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Linux

Brave | 1.3.99 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.3.99 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Linux

cc @brave/legacy_qa @jsecretan @AlexeyBarabash @darkdh @rebron

**Comment by btlechowski** [comment]
Also reproduced with Windows 7x64 and Windows 10x64.
The same bookmarks are missing: `interia.pl` on DeviceB and `youtube.com` on DeviceA.

DeviceA:

Brave | 1.5.53 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1909

DeviceB:

Brave | 1.5.53 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

**Comment by AlexeyBarabash** [comment]
Thanks @btlechowski . I can confirm I am able to reproduce it.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.5.62 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verified STR from the description

Verification passed on

Brave | 1.5.62 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Ubuntu 18.04 LTS

Verified STR from the description

This issues needs to be retested after uplift to 1.3.x

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.109 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Ubuntu 18.04 LTS

Verification passed on

Brave | 1.3.109 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verified test plan from the description. Also verified by switching devices.

![image](https://user-images.githubusercontent.com/34715963/73785586-d9ec5780-4797-11ea-80aa-d2c1fdfc7607.png)
