### ISSUE TITLE
Error in building Brave Release for Mac - /v8_context_snapshot_generator failed with exit code -5

### ISSUE THREAD

**Issue by ShihChinYang** [brave/brave-browser#7896]
Hi,
I was able to build Brave for Mac with Component build. But when I tried to build for Release. It failed with following error

[1/427] ACTION //tools/v8_context_snapshot:gener...ontext_snapshot(//build/toolchain/mac:clang_x64)
FAILED: v8_context_snapshot.bin 
python ../../build/gn_run_binary.py ./v8_context_snapshot_generator --output_file=v8_context_snapshot.bin
./v8_context_snapshot_generator failed with exit code -5
## Steps to Reproduce

Prerequisites:
. xcode 11.3
. MacOSX10.14.sdk
. Node 10.18.1
. NPM 6.13.4
. python 2.7.16
. git 2.21.0
   1. git clone https://github.com/brave/brave-browser.git
   2. cd brave-browser
   3. npm install
   4. npm run init
   5. npm run build Release

## Actual result:

ninja: Entering directory `/Users/shih-chinyang/WuNanTech/brave/brave-browser/src/out/Release'
[1/427] ACTION //tools/v8_context_snapshot:gener...ontext_snapshot(//build/toolchain/mac:clang_x64)
FAILED: v8_context_snapshot.bin 
python ../../build/gn_run_binary.py ./v8_context_snapshot_generator --output_file=v8_context_snapshot.bin
./v8_context_snapshot_generator failed with exit code -5

## Expected result:
A successful Release build.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

https://github.com/brave/brave-browser.git
Master branch.

**Comment by bsclifton** [comment]
@ShihChinYang is this still happening? You should be able to try with latest which requires the 10.15 SDK. I believe using XCode 11.3 and SDK 10.14 is what caused the problem. I was using XCode 10.3 and SDK 10.14 to work around the problem, but Chromium team has updated requirements recently
