### ISSUE TITLE
Change to 'Add to Brave' instead of 'Add to Chrome' CWS

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#790]
## Description 
Change 'Add to Chrome' button on Chrome Web Store to display 'Add to Brave' instead in order to start Extension install process from Chrome Web Store.

## Test plan / Steps to Reproduce
Change
   1. Go to https://chrome.google.com/webstore/category/extensions?hl=en-US&utm_source=chrome-ntp-launcher
   2.  Select Extension e.g. https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen?hl=en-US&utm_source=chrome-ntp-launcher
   3. Look at the `Add to X` button.

## Actual result:
![addtochromebutton](https://user-images.githubusercontent.com/5951041/44357701-913bc400-a467-11e8-9858-6e2aaafdfec2.png)
Shows `Add to Chrome`.

## Expected result:
![addtobravebutton](https://user-images.githubusercontent.com/5951041/44357704-94cf4b00-a467-11e8-9412-04515903afed.png)
Expected results, `Add to Brave`.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Sophist-UK** [comment]
Also shows "Add to Chrome" in the search results / list of extensions, and "Remove from Chrome" after extension has been installed.

If Brave wants to be consistent, it needs to have an internal extension that changes the text as sent from the Chrome web store. This might be best implemented by including as standard (if it doesn't create security issues which it might well do) script functionality aka GreaseMonkey.

**Comment by stardust3dd** [comment]
Can I claim this issue?

**Comment by bsclifton** [comment]
@stardust3dd sure - you're welcome to grab this. Have you gotten Brave up and running locally? You can likely handle this with a content script in the Brave extension

**Comment by stardust3dd** [comment]
The chrome webstore does not allow content scripts on it's pages [since version 35](https://bugs.chromium.org/p/chromium/issues/detail?id=355677). Do we have any other way around?

**Comment by keur** [comment]
PR in https://github.com/brave/brave-core/pull/2845

**Comment by btlechowski** [comment]
LGTM. Awesome work!

Verification passed on

Brave | 0.69.110 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Ubuntu 18.04 LTS

Logged https://github.com/brave/brave-browser/issues/5730

Before adding the extension:
![image](https://user-images.githubusercontent.com/34715963/63312321-7a8dae80-c301-11e9-9b1b-9802fd491322.png)
After adding the extension:
![image](https://user-images.githubusercontent.com/34715963/63312343-8c6f5180-c301-11e9-9c5d-97e7bb57b22a.png)
