### ISSUE TITLE
Ad conversion detection switch is not selectable on Android

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#7901]
## Description 
"Allow ad conversion detection" switch is not selectable on Android

## Steps to reproduce 

   1. Launch browser
   2. Navigate to Ads Settings
   3. Toggle "Allow ad conversion detection" checkbox

## Actual result 
"Allow ad conversion detection" switch is not selectable on Android

## Expected result
"Allow ad conversion detection" switch should be selectable on Android

## Issue reproduces how often 
Easily reproduced

## Issue happens on 
   - Current Play Store version? No
   - Beta build? No

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
Affects nightly build of browser-android-tabs

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9 running 1.6.24 nightly x64 build
- Verified setting can be checked or unchecked
-----
Verification passed on Oneplus 6T with Android 10 running 1.6.24 nightly x64 build
- Verified setting can be checked or unchecked
-----
