### ISSUE TITLE
Fingerprint protection is enabled by default in shields but disabled globally

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7902]
## Description 
Fingerprint protection is enabled by default in shields but disabled globally. Found while testing  #6639 using test plan from https://github.com/brave/brave-core/pull/4052

## Steps to reproduce 

   1. Clean install 1.5.57
   2. Visit any page in a new tab
   3. Open shields, fingerprint is enabled by default but disabled in global settings

## Actual result 
![fp](https://user-images.githubusercontent.com/17010094/73095883-8897ba80-3eb1-11ea-8c02-bef8452dd88b.gif)

## Expected result
Should not be enabled by default 

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): OnePlus 6T
   - Android version: 10
   
## Brave version
1.5.57

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc: @emerick

**Comment by yrliou** [comment]
Desktop's default FP behavior is blocking third party, but current android-tab's default is allow.
@SergeyZhukovsky Do we consider following desktop's default behavior here or do we need to change it to allow for mobile specifically?

**Comment by anthonypkeane** [comment]
@jamesmudgett to help with design

**Comment by SergeyZhukovsky** [comment]
Per discussion we had on a meeting the behaviour till we have a proper design is: the switch should control 3rd party only.

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm 1.5.110.apk`
   - Verified STR from the description
   - Verified that change global shield settings reflected in site-specific shields
