### ISSUE TITLE
Shields settings are not retained during upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7903]
## Description 
Found while testing #6639. Shields settings are not retained as expected 

## Steps to reproduce 

   1. Install an older nightly build (1.5.46)
   2. Visit google.com and enable all shields settings
   3. Visit yahoo.com in a second tab and disable all shields settings
   4. Upgrade to 1.5.57 nightly build
   5. google.com has all shields settings reset to default
   6. yahoo.com has adblock enabled and others disabled

## Actual result 
Shields settings are not retained during upgrade

## Expected result
Should be retained during upgrade

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): OnePlus 6T
   - Android version: 10
   
## Brave version
1.5.46 -> 1.5.57

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by emerick** [comment]
@srirambv I wasn't able to repro with the following steps:

- Installed the `1.5.46` nightly
- Visit google.com and enable all shields settings
- Visit yahoo.com and disable all shields settings
- Upgrade to `1.5.57` using `adb install -d -r {apk}` (How are you upgrading?)
- Confirm that `1.5.57` is installed and `1.5.46` is gone
- Confirm that google.com shields are all enabled and yahoo.com are disabled

I'm guessing there's some difference with how we're upgrading?

**Comment by srirambv** [comment]
For CI builds I just run the apk via filemanager which installs it over the existing one. I can test this when the next beta comes out and see if its still an issue.

**Comment by emerick** [comment]
@srirambv That would be great, thank you.

**Comment by emerick** [comment]
@srirambv I reconfirmed using the file manager to do the upgrade and it looked OK to me. I'm probably missing a step. If you're still able to repro today and have any ability to make a video or do a video call with me to see the steps, that would be great.

**Comment by srirambv** [comment]
Closing the issue as not able to reproduce it with the same versions mentioned in the issue description. Will reopen it if I find consistent repro steps or if the issue starts to happen again
