### ISSUE TITLE
[android only] Brave connects to Google to see if a progressive web app is installable

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#7904]
cross-posted from https://github.com/brave/browser-android-tabs/issues/2479: 

according to @slightlyoff, Brave Android is pinging a Google backend when the user visits a PWA website like https://squoosh.app/ to see if it is installable. this should be checked on Android Core and the connection to Google should be blocked/proxied if it occurs.

**Comment by samartnik** [comment]
I don't see requests to Google in dev tools. A bit more discussion is here https://github.com/brave/browser-android-tabs/issues/2479
I suppose we can close this issue for now. At least till we get more info on how to check it.
