### ISSUE TITLE
Onboarding is launched when theme is changed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7905]
## Description 
Onboarding is launched when theme is changed

## Steps to reproduce 

   1. Clean install 1.5.57 
   2. Visit a few sites in a few tabs
   3. Change default theme from dark to light 
   4. Onboarding is launched the moment theme is changed

## Actual result 
Onboarding is launched when theme is changed

## Expected result
Onboarding should not be launched when theme is changed

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): OnePlus 6T and Samsung Tab A
   - Android version: 9 & 10
   
## Brave version
1.5.57

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome?  NA

### Additional information

cc: @deeppandya

**Comment by yrliou** [comment]
I'm not able to reproduce it on 1.5.59 cc @srirambv to see if there are more details to those steps or a video could be shared for me to follow, thanks.

**Comment by srirambv** [comment]
Unable to reproduce on current nightly 1.6.12. Closing the issue for now will reopen if issues reproduces or if I find consistent steps
