### ISSUE TITLE
Tab overview some times switches to grid layout 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7910]
## Description 
Tab overview some times switches to grid layout 

## Steps to reproduce (Not 100% sure)

   1. Install older beta build
   2. Visit a few sites and change shield settings on a few of them
   3. Upgrade to new version 1.5.58
   4. Open a new private tab from menu
   5. Switch to tabs overview shows grid layout 

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/73102135-3362a580-3ebf-11ea-84a0-8e290d2f5960.png)

## Expected result
Should use card layout similar to android-tabs

## Issue reproduces how often 
If you are the unlucky soul happens everytime

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): OnePlus 6T
   - Android version: 10
   
## Brave version
1.5.58

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @yrliou @emerick @SergeyZhukovsky

**Comment by anthonypkeane** [comment]
resolved
