### ISSUE TITLE
Tips panel isn't auto updated with one time tips list

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7912]
## Description 
Tips panel isn't auto updated with one time tips list. Follow up to #7106

## Steps to reproduce 

   1. Install 1.5.58 beta build
   2. Fund wallet and send an one time tip toa  verified publisher
   3. Open rewards page, tips panel is empty
   4. Switch back to a different tab and come back to rewards page shows the tip 

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/73106693-f9e36780-3ec9-11ea-91f2-455f5605afe2.png)

## Expected result
Should show the tipped publisher details instantly under the tips panel on rewards page

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone/Tablet
   - Android version:9 & 10
   
## Brave version
1.5.58

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @emerick

**Comment by emerick** [comment]
In my testing, I can repro the issue if I close the rewards page after funding the wallet. I then tip a verified site and open the rewards page and there are no tips listed.

If I keep the rewards page open when I perform the tip, I can't repro.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.110 x64 stable build
- Verified tips are listed as expected
![image](https://user-images.githubusercontent.com/17010094/76384090-f9246900-6383-11ea-8d29-4a989818deba.png)

-----------
Verification passed on Samsung Tab A with Android 9 running 1.5.110 x64 stable build
- Verified tips are listed as expected
![image](https://user-images.githubusercontent.com/17010094/76384074-edd13d80-6383-11ea-9c1d-94874459d1d6.png)
