### ISSUE TITLE
chrome:// pages don't work on x86

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7913]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/7589

chrome:// pages don't work on x86. Tried the following:
chrome://flags
chrome://about
chrome://credits

## Steps to reproduce 

   1. Navigate to one of the above pages
   2. Or retest https://github.com/brave/brave-browser/issues/7587
   3. 

## Actual result 
![Screenshot_20200124-165943](https://user-images.githubusercontent.com/28145373/73107077-04523100-3ecb-11ea-999e-94ffabf2fe64.jpg)

## Expected result
page should load

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? n/a
   - Beta build? yes

## Device details
   - Install type (ARM, x86): x86
   - Device (Phone, Tablet, Phablet): phone
   - Android version: 6
   
## Brave version
1.5.58

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information
cc @srirambv

**Comment by yrliou** [comment]
Fixed with https://github.com/brave/brave-core/pull/4577

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.6.27 Nightly BraveModernx86.apk
   - Verified STR from description
   - Verified `Verified Open source licenses link to chrome://credits` and chrome://credits page loads from https://github.com/brave/brave-browser/issues/7589
   - Verified https://github.com/brave/brave-browser/issues/7587
![Screenshot_20200213-170529](https://user-images.githubusercontent.com/28145373/74482972-83f86d80-4e83-11ea-8b9c-32eb05e88aac.jpg)
