### ISSUE TITLE
Replace Chromium icons on URL bar  with Brave icons

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7916]
## Description 
Replace Chromium icons on URL bar with Brave icons

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/73121001-5171e980-3f43-11ea-9e0b-42e718b9af78.png)

## Expected result
![image](https://user-images.githubusercontent.com/17010094/73121008-65b5e680-3f43-11ea-929a-6f64dd5572e5.png)

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Tablet
   - Android version: 9.0
   
## Brave version
1.5.59

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome?  NA

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm 1.5.110.apk`
- Verified that all the icons work in the toolbar (bookmark, refresh, download etc)
![Screenshot_2020-03-11-15-44-53](https://user-images.githubusercontent.com/38657976/76407124-dceaf100-63b0-11ea-94d6-a16e998b4cc5.png)
![Screenshot_2020-03-11-15-45-10](https://user-images.githubusercontent.com/38657976/76407150-e411ff00-63b0-11ea-86db-4b5aace0d409.png)
