### ISSUE TITLE
Ad notification shows up even when Brave-Beta is not running

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7917]
## Description 
Ad notification shows up even when Brave-Beta is not running

## Steps to reproduce 

   1. Run brave and remove from memory
   2. Ads show up even when app is removed from memory

## Actual result 
Ad notification showed up on device even when Brave-Beta wasn't running in background

## Expected result
Should not show ad notification if app isn't running

## Issue reproduces how often 
Issue happened on release build logged https://github.com/brave/browser-android-tabs/issues/2478. After upgrading to Beta reproduced on android-core as well

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Pixel 3XL
   - Android version: 10
   
## Brave version
1.5.59

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
Adding `feature/rewards` label as its related to ads and issue added to `Android-Core` project board

**Comment by LaurenWags** [comment]
++ from me

**Comment by srirambv** [comment]
Moving to Android 1.7.x milestone as this Android specific issue

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.7.102 x64 stable build
- Verified no ads show up when the app is removed from memory 
--------
Verification passed on Samsung Tab A with Android 9 running 1.7.102 x64 stable build
- Verified no ads show up when the app is removed from memory 
--------
