### ISSUE TITLE
Ads not properly skipping on Spotify

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#7919]
## Description 
Spotify ads not being skipped

## Steps to Reproduce

   1. Visit `https://open.spotify.com/`
   2. Play music until a adbreak occurs.
   3. Brave won't skip ad

## Actual result:
Should skip advert

## Expected result:
Not skipping advert

## Reproduces how often: 
May require to listen to a few tracks to get adbreak

## Brave version (brave://version info)
Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the dev channel? Didn't test
- Can you reproduce this issue with the nightly channel? Yes

## Miscellaneous Information:
The following filters are used by uBO, possibly a bug in redirect= causing it not skip the ad reliably.

`||d7zatysqm84hv.cloudfront.net/mp3-ad/$media,redirect=noopmp3-0.1s,domain=open.spotify.com`
`||akamaized.net/audio/*$media,redirect=noopmp3-0.1s,domain=open.spotify.com`
`||scdn.co/audio/*$media,redirect=noopmp3-0.1s,domain=open.spotify.com`

**Comment by ryanbr** [comment]
Can confirm it occurs in Nightly. Is this related to the snippets @antonok-edm ?

**Comment by ryanbr** [comment]
This is resolved, just re-tested in Brave release. No ads, not even a small gap for a audio ad

**Comment by chharvey** [comment]
Just out of curiosity, how does Brave do this? I heard that Spotify uses their home-grown domain for ads, to trick ad-blockers into thinking they’re just normal music. How does Brave make the distinction?
