### ISSUE TITLE
SNTP crashes for non-US region

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7928]
## Description 
Found while testing https://github.com/brave/brave-core/pull/4075

Test plan 4 from above PR fails, browser crashes when OS is set to something other that US (ex. Canada or UK)

## Steps to Reproduce

Reproduced below using Canada and UK. Note, if in a non-ads region, like Aruba, issue does not reproduce.
### 4. Blank Remote content is fetched and parsed
_(only works whilst in pre-release phase)_
0. Fresh or previous profile
0. System OS region set to "Canada"
1. Visit chrome://flags and turn on only the "Branded Wallpapers" feature flag
2. Relaunch browser
3. Refresh NTP more than 5 times. NO sponsored background image should be seen.

When retesting, retest on both clean and upgrade profiles.

## Actual result:
Brave crashes on second new tab or refresh. See Uploaded Crash Report ID `cbec1ecd57eec1da`

## Expected result:
No crash

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.5.62 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the dev channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

## Miscellaneous Information:
cc @brave/legacy_qa @petemill

**Comment by btlechowski** [comment]
Reproduced on Windows

Brave | 1.5.62 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Uploaded Crash Report ID 64b9a1ffb0cbd0ae (Local Context: 537bfd37-d0ac-4677-9842-445e0e23a298)
Uploaded Crash Report ID 80a15212603bb381 (Local Context: a6768b09-2527-4059-b8b3-d9b304bdbcfd)

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows 10 x64

Brave | 1.5.63 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

Brave | 1.3.106 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR mentioned in the description
- Verified for Canada, UK and Autralia - No crash 
- Verified both clean and upgraded profiles
