### ISSUE TITLE
Let WebUI know light / dark mode

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#793]
Brave-UI will (soon!) be able to switch between light and dark themes. This selection should be available to all the WebUIs, especially Brave Rewards.

Ideally (and maybe most importantly) Shields too, which is an extension popup at the moment.

**Comment by bbondy** [comment]
would be great to have welcome page for example use dark tone instead of white.

**Comment by petemill** [comment]
Preliminary work is done in brave-ui to support multiple themes: https://github.com/brave/brave-ui/pull/84

After that, each piece of UI (welcome, shields, rewards) needs to be refactored to use theme values. Then the `<ThemeProvider` component can choose the theme based on a property from webui.

**Comment by WA9ACE** [comment]
Chromium has an issue tracked and actively being developed for this; which is linked to a possible WebExtension API for exposing current dark mode setting to extensions. Might be good to keep an eye on to pull in for use with Shields UI.

https://bugs.chromium.org/p/chromium/issues/detail?id=850098

**Comment by simonhong** [comment]
This can be closed because api is already implemented and WebUI can use it.
Document: https://github.com/brave/brave-browser/wiki/UI-Color-Themes
https://github.com/brave/brave-browser/issues/2822 can track theme aware webui feature.
