### ISSUE TITLE
no images shown when both SNTP flags enabled

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7930]
## Description 
Found while testing https://github.com/brave/brave-core/pull/4075

Test plan 2 from above PR fails, images are not shown when both flags are enabled.

### 2. With the feature flag and demo feature flag, demo sponsored content is shown
0. Fresh or previous profile
1. Visit chrome://flags and turn on both above feature flags
2. Relaunch browser
3. Refresh NTP until sponsored background is shown. Internal demo sponsored background is the "Technikke" background with NO green lines.

When retesting, retest on both clean and upgrade profiles.

## Actual result:
blank background with `Technikke` logo
<img width="1209" alt="Screen Shot 2020-01-27 at 8 50 12 AM" src="https://user-images.githubusercontent.com/28145373/73190109-760cc380-40f3-11ea-9a0e-39da7d7a74a6.png">

## Expected result:
`Technikke` images without green lines

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.5.62 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the dev channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

## Miscellaneous Information:
cc @brave/legacy_qa @petemill

**Comment by btlechowski** [comment]
Reproduced on Windows

Brave | 1.5.62 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

![image](https://user-images.githubusercontent.com/34715963/73192691-af602600-4129-11ea-92b4-cd45b002aa08.png)

**Comment by GeetaSarvadnya** [comment]
Reproduced in windows 10 x64

Brave | 1.5.63 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

**Comment by GeetaSarvadnya** [comment]
Reproduced on Linux Mint
Brave | 1.5.63 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Linux

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.3.106 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR mentioned in the description
- Verified on both clean and upgraded profile
 Clean profile>Turn on both flags>NTP-SI is shown 
![image](https://user-images.githubusercontent.com/38657976/73528289-9feb2080-443a-11ea-8896-0a93e6ce01aa.png)
Clean profile>Enable rewards>Disable Ads>Turn on both flags>NTP-SI is shown 
![image](https://user-images.githubusercontent.com/38657976/73528568-20aa1c80-443b-11ea-8e9c-de8dea4d50e1.png)
Clean profile>Enable rewards>Disable rewards>Turn on both flags>NTP-SI is shown 
![image](https://user-images.githubusercontent.com/38657976/73528732-741c6a80-443b-11ea-8d9c-7de6727b9144.png)
Clean profile>Enable Rewards>Disable Ads>Disable Rewards widget>Turn on both flags>NTP-SI is shown 
![image](https://user-images.githubusercontent.com/38657976/73528993-e9883b00-443b-11ea-80ec-1bb29a9de069.png)
