### ISSUE TITLE
DuckDuckGo info bar isn't shown on Private tab when modal is dismissed 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#7934]
## Description 
DuckDuckGo info bar isn't shown on Private tab when modal is dismissed 

## Steps to reproduce 

   1. Clean install beta
   2. Open a new private tab
   3. Click `No` on the popup modal, DDG info bar isn't shown on private tab 

## Actual result 
DuckDuckGo info bar isn't shown on Private tab when modal is dismissed 

## Expected result
If user selects No on DDG popup private tab should have DDG info bar shown to quick set DDG as default for private tab

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.5.59 Beta

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by yrliou** [comment]
Closed by https://github.com/brave/brave-core/pull/4580.

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9 running 1.6.24 nightly x64 build
- Verified DDG info bar is shown 
- Verified selecting No on DDG modal still shows info bar
- Verified tapping on info bar brings up DDG modal and selecting yes removes the info bar
------
Verification passed on OnePlus 6T with Android 10 running 1.6.24 nightly x64 build
- Verified DDG info bar is shown 
- Verified selecting No on DDG modal still shows info bar
- Verified tapping on info bar brings up DDG modal and selecting yes removes the info bar
