### ISSUE TITLE
footer moves to top of NTP if all widgets turned off

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7937]
## Description 
Found while testing Scenario 10 from https://github.com/brave/brave-core/pull/4075

If you have your window set to be ~870 px wide or less and you toggle off all widgets, the footer (including SNTP logo if present) moves up to the top of the page.

## Steps to Reproduce

   1. Clean or existing profile
   2. Enable the flags necessary to show SNTP
   3. Relaunch
   4. On NTP, toggle off all widgets (clock, stats, rewards, top sites)

## Actual result:
Footer moves to the top of the page:
<img width="871" alt="Screen Shot 2020-01-27 at 3 20 21 PM" src="https://user-images.githubusercontent.com/28145373/73210563-8e430980-4118-11ea-8864-ce1310d1c995.png">

occurs on normal NTP as well: 
<img width="869" alt="Screen Shot 2020-01-27 at 3 22 40 PM" src="https://user-images.githubusercontent.com/28145373/73210754-e712a200-4118-11ea-9b50-5a76e0225338.png">

## Expected result:
Footer to remain at the bottom of the page (screenshot is from making the page just a bit wider):
<img width="884" alt="Screen Shot 2020-01-27 at 3 21 21 PM" src="https://user-images.githubusercontent.com/28145373/73210663-b894c700-4118-11ea-879c-40142b3f25f7.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.5.62 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, does not reproduce with 1.2.x
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? no, does not reproduce with 1.4.x
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @brave/legacy_qa @rebron @petemill

**Comment by btlechowski** [comment]
Reproduced on Window 7 and Windows 10

Brave | 1.5.62 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.5.62 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1909 (Build 18363.592)

![image](https://user-images.githubusercontent.com/34715963/73211154-fa8b3080-414b-11ea-8149-9d2e1adbaf9a.png)

**Comment by LaurenWags** [comment]
Extra problem with this is, if you are on a non-sponsored NTP and you toggle off all widgets and want to re-toggle them on, you can't do so because when you click on the icon for 'Dashboard Settings', the popup with the toggles can't be seen because it's above the icon, and the icon is already at the top of the window. 

when on a sponsored NTP at least you can see part of the popup to be able to toggle 1 item on (which fixes the footer at the top problem momentarily).
<img width="863" alt="Screen Shot 2020-01-27 at 3 29 46 PM" src="https://user-images.githubusercontent.com/28145373/73211294-f34b2f00-4119-11ea-9cdf-11570b6d19c6.png">

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows 10 x64 - `1.5.63`

![image](https://user-images.githubusercontent.com/38657976/73260256-8d30db80-41ef-11ea-8840-7553da1a017a.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.3.106 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/73560477-0c870f00-447d-11ea-98be-9957d057f63d.png)
