### ISSUE TITLE
SNTP message says to Turn on BR when Rewards are already on, should say turn on Ads

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7939]
## Description 
Found while testing test plan 10 from https://github.com/brave/brave-core/pull/4075

When Rewards are ON, Ads are OFF, and Widget is ON, the message on a SNTP says `Turn on Brave Rewards to claim your share.` however, BR are on. Per the image in test plan 10 from PR, this should say `Turn on Brave Ads to claim your share.` Button correctly identifies Brave Ads to be turned on and clicking the button does enable Brave Ads.

Also occurs when BR Widget is OFF (Scenario 2 below).

## Steps to Reproduce

Scenario 1:
   1. Clean profile
   2. Enable BR, toggle Ads off
   3. Enable flag for SNTP. Restart.
   4. Open new tab until you see a SNTP.

Scenario 2:
   1. Clean profile
   2. Enable BR, toggle Ads off. Go to NTP and toggle Rewards widget OFF.
   3. Enable flag for SNTP. Restart.
   4. Open new tab until you see a SNTP.

## Actual result:
Scenario 1:
<img width="1195" alt="Screen Shot 2020-01-27 at 4 14 05 PM" src="https://user-images.githubusercontent.com/28145373/73214689-ac146c80-4120-11ea-8f41-d4183d26c9a0.png">

Scenario 2:
<img width="1193" alt="Screen Shot 2020-01-27 at 4 45 56 PM" src="https://user-images.githubusercontent.com/28145373/73216722-825d4480-4124-11ea-97e1-8653d050be54.png">

## Expected result:
`Brave Rewards` should be `Brave Ads` on message.

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.5.62 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the dev channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
cc @brave/legacy_qa @petemill @rebron

**Comment by btlechowski** [comment]
Reproduce on Windows 7 and Windows 10

Brave | 1.5.62 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.5.62 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1909 (Build 18363.592)

![image](https://user-images.githubusercontent.com/34715963/73216842-10522300-4157-11ea-8c7d-034c3ea5318f.png)

**Comment by rebron** [comment]
cc: @petemill second order for translation on this one.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.3.106 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR mentions in the description
![image](https://user-images.githubusercontent.com/38657976/73527193-a7a9c580-4438-11ea-9b2c-c854ff56e6fb.png)
![image](https://user-images.githubusercontent.com/38657976/73527445-1129d400-4439-11ea-9862-3954033e6095.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.3.107 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1803 (Build 17134.1006)
- Verified STR's from the description
- Verified the test plan from https://github.com/brave/brave-core/pull/4447
![image](https://user-images.githubusercontent.com/38657976/73625409-b37cce00-466a-11ea-9164-bf7b840ad485.png)
![image](https://user-images.githubusercontent.com/38657976/73625454-eaeb7a80-466a-11ea-9ec0-aac13676b8b9.png)
![image](https://user-images.githubusercontent.com/38657976/73625504-2ab26200-466b-11ea-8f0c-aeda686ef042.png)
