### ISSUE TITLE
Add more details to the red "...problem processing your contribution" BR notification

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#7941]
## Description 
The UX of Brave Rewards notifications needs to be improved. Currently, notifications stack on top of one another continuously like so:
![rewardsnotificationsproblem](https://user-images.githubusercontent.com/2388823/73215037-2a184980-4108-11ea-808b-99dd726e106a.gif)

Lessen the amount of notifications and unnecessarily negative messages.

## Expected UX
The red "...problem processing your contribution" is pretty alarming due to the red visual treatment. Empower users to fix the problem by providing:

- the reason for the problem
- what they can do to fix it

The specific notification is this:
![Screen Shot 2020-01-24 at 11 01 46 AM](https://user-images.githubusercontent.com/2388823/73215583-3355e600-4109-11ea-9928-6c6f0c1f9b03.png)

It should look like:
**design TBA**

**Comment by Miyayes** [comment]
Stale due to Rewards 2.0.
