### ISSUE TITLE
Make "Insufficient funds...pending tips" BR notification have more friendly messaging

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#7942]
## Description 
The UX of Brave Rewards notifications needs to be improved. Currently, notifications stack on top of one another continuously like so:
![rewardsnotificationsproblem](https://user-images.githubusercontent.com/2388823/73215037-2a184980-4108-11ea-808b-99dd726e106a.gif)

Lessen the amount of notifications and unnecessarily negative messages.

## Expected UX
The "Insufficient funds...pending tips" message could do with some more friendly wording prodding the user to contribute. Unlike AC, tips were a conscious act of contributing to a particular website, so we should inform the user and be more personal about it. Perhaps pick a creator that the pending fund is for with a message that says "Hey, you don't have enough balance left for this month to tip Joe Rogan. You can add more funds if you still want to tip them!" 

The specific notification is this:
![Screen Shot 2020-01-24 at 11 01 56 AM](https://user-images.githubusercontent.com/2388823/73215791-98114080-4109-11ea-917a-d874a2de3c58.png)

It should look like:
**design TBA**

**Comment by Miyayes** [comment]
I think this has been resolved with Rewards 2.0 panel.
