### ISSUE TITLE
Expire BR notifications/alerts

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#7943]
## Description 
The UX of Brave Rewards notifications needs to be improved. Currently, notifications stack on top of one another continuously like so:
![rewardsnotificationsproblem](https://user-images.githubusercontent.com/2388823/73215037-2a184980-4108-11ea-808b-99dd726e106a.gif)

Lessen the amount of notifications and unnecessarily negative messages.

## Expected UX
Notification/alerts should not sit in the Brave Rewards panel and stack on top of each other forever. If the user doesn't take action on them, they should expire after 1 week.

**Comment by bsclifton** [comment]
Showing more than 1 is a bit obnoxious; but for sure requiring user to dismiss each is a PITA (especially when there is not enough context given)

@karenkliu do you know if there is a better way to present an alert? I personally think this is not a good place to put it, as they're usually only seen after the fact... and it blocks a chunk of the UI until dismissed ☹️

**Comment by karenkliu** [comment]
@bsclifton  I checked in with the Rewards team. Looks like there are designs planned in a v2 update for the BR panel that fixes this notification pile up issue. No Github issue yet though. The team is working on the v1 round of changes which does not include a fix for this issue.

**Comment by karenkliu** [comment]
Sorry - accidentally clicked close. I would say this issue is blocked for now since designs are ready but waiting for development to finish v1 changes to BR panel.

**Comment by Miyayes** [comment]
Superseded by new Rewards panel 2.0
