### ISSUE TITLE
SNTP - ads item in NTP rewards widget is shown for unsupported ads region message

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#7944]
It looks like ads item: `Sorry! Ads are not yet available in your region.` and `Estimated earnings so far this month` are shown in NTP rewards widget

This is a regression

## Steps to Reproduce

   1. Open Brave in Unsupported region (used `Luxemburg`)
   2. Enable flag for SNTP
   3. Restart
   4. Open new tab until you see a SNTP is shown

## Actual result:

Ads item is shown. 
`Sorry! Ads are not yet available in your region.` and `Estimated earnings so far this month` are shown
![image](https://user-images.githubusercontent.com/34715963/73217289-f6651000-4157-11ea-8dfc-5ce12a07d3e6.png)

## Expected result:
Ads item is not shown
![image](https://user-images.githubusercontent.com/34715963/73228534-2f60ad00-4177-11ea-847d-732f4b2db75e.png)

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.5.62 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.5.62 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1909 (Build 18363.592)

cc @brave/legacy_qa @petemill @rebron

**Comment by rebron** [comment]
cc: @bradleyrichter

**Comment by LaurenWags** [comment]
Reproduces on macOS

Brave | 1.5.62 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.3.106 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
- Verified on both clean and upgraded profile

![image](https://user-images.githubusercontent.com/38657976/73537549-b8653600-444e-11ea-9e98-a5bfc720fff0.png)
