### ISSUE TITLE
SNTP messages should only be shown the first time a SNTP is shown

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7945]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/7883

The first time a SNTP is viewed, a dismiss-able message is shown in some cases. Currently this message is only dismissed manually via the X. However, per discussion with @petemill and in the spec, this introductory message should only be shown to the user the first time they are seeing a sponsored image. 

From the spec:
```
The introductory message, which is shown only to users seeing a sponsored image for the first time. 
```

## Steps to Reproduce

Multiple scenarios, but here are two
Scenario 1
   1. Clean profile
   2. Rewards ON, Ads ON, Widget ON
   3. Enable flag for SNTP
   4. Relaunch
   5. Open NTP until SNTP is shown. Note message is displayed as expected and could be dismissed manually. Do not dismiss it. _(edit[@petemill]: Make sure page stays active for at least 4 seconds)_
   5. Open or refresh until another SNTP is shown.

Scenario 2
   1. Clean profile
   2. Rewards OFF, Widget OFF
   3. Enable flag for SNTP
   4. Relaunch
   5. Open NTP until SNTP is shown. Note message is displayed as expected and could be dismissed manually. Do not dismiss it. _(edit[@petemill]: Make sure page stays active for at least 4 seconds)_
   5. Open or refresh until another SNTP is shown.

## Actual result:
Message is shown on second SNTP.
Scenario 1:
<img width="350" alt="Screen Shot 2020-01-27 at 4 09 25 PM" src="https://user-images.githubusercontent.com/28145373/73223284-99576300-4133-11ea-933e-431dfb235b26.png">

Scenario 2:
<img width="338" alt="Screen Shot 2020-01-27 at 4 10 06 PM" src="https://user-images.githubusercontent.com/28145373/73223289-9d838080-4133-11ea-8223-5dff94657b60.png">

## Expected result:
Message should not be shown on the second SNTP

## Reproduces how often: 

easily

## Brave version (brave://version info)
1.5.62

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the dev channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

## Miscellaneous Information:
cc @brave/legacy_qa @rebron @petemill

**Comment by GeetaSarvadnya** [comment]
Reproduced in windows 10 x64

Brave | 1.5.63 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

**Comment by rebron** [comment]
@petemill I moved to 1.3.x - Release milestone.
