### ISSUE TITLE
[SNPT] Previous image is visible after changing from supported region to un-supported region

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#7946]
After changing to un supported region from supported region, ntp sponsor image should not be visible.

Repro step
1. launching brave with clean profile with US region
2. Turn on the `New Tab Page Branded Wallpapers` only and re-launch
3. Check sponsorship image is visible
4. change OS region to CA and re-launch
5. Check sponsorship image is not visible

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.108 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Ubuntu 18.04 LTS

Verified STR from the description. The sponsored images were not shown for Canada.
Used following command lines to trigger region change.
`LANG=en_US.UTF-8 LANGUAGE=en_US /usr/bin/brave-browser-beta`
`LANG=en_CA.UTF-8 LANGUAGE=en_CA /usr/bin/brave-browser-beta`
