### ISSUE TITLE
text update needed on Dashboard Settings

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7947]
## Description 
Per the spec for SNTP, `Show Background Image` should be updated to `Show Background Images`.

## Steps to Reproduce

   1. Clean profile
   2. Enable SNTP from flags, relaunch
   3. Open Dashboard Settings on NTP

## Actual result:
<img width="435" alt="Screen Shot 2020-01-27 at 7 32 55 PM" src="https://user-images.githubusercontent.com/28145373/73225841-01aa4280-413c-11ea-9c2d-f20498cc0369.png">

## Expected result:
Should say `Show Background Images`

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.5.62 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @brave/legacy_qa @rebron @petemill

**Comment by gupta437** [comment]
If no one is working actively on this issue, Can I take this issue to work on?

**Comment by bsclifton** [comment]
@gupta437 it's all yours! 😄 Let me know if you need help finding where it's stored

**Comment by edwardqiu** [comment]
Hey @gupta437, are you still working on this? If not, I would love to give this a try!

**Comment by bsclifton** [comment]
@edwardqiu go for it 😄

**Comment by edwardqiu** [comment]
Hi @bsclifton, this is my first time opening a PR here! Please let me know if there's anything I should change 😄

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.6 x64` using the following build:

```
Brave | 1.15.55 Chromium: 85.0.4183.102 (Official Build) dev (64-bit)
-- | --
Revision | ffe848af6a5df4fa127e2929331116b7f9f1cb30-refs/branch-heads/4183@{#1770}
OS | macOS Version 10.15.6 (Build 19G73)
```

* ensured that `Customize` --> `Background Images` under NTP displays `Show Background Images` when enabled & disabled
* double checked and ensured that `brave://settings/newTab` displays the correct strings

| Dashboard Settings | brave://settings |
| :----------: | :----------:|
| <img width="800" alt="Screen Shot 2020-09-17 at 11 27 42 AM" src="https://user-images.githubusercontent.com/2602313/93497446-6d653980-f8de-11ea-867f-ebbcaea87736.png"> | <img width="747" alt="Screen Shot 2020-09-17 at 11 31 08 AM" src="https://user-images.githubusercontent.com/2602313/93497475-748c4780-f8de-11ea-865a-a17d47d97421.png"> |
