### ISSUE TITLE
Moving of bookmark is not propagated to another device

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#7948]
Found while testing: https://github.com/brave/brave-core/pull/4324

The issue is also randomly reproducible with more bookmarks. My bookmarks were all messed up. Sometimes moving of bookmarks works as expected.

Important: Reproducible on 1.5.x. Not reproducible on 1.2.x, 1.3.x.

## Steps to Reproduce

   1. Clean profile DeviceA and DeviceB
   2. DeviceA: open `interia.pl`
   3. DeviceA: open `youtube.com`
   4. DeviceA: create sync chain and copy code words
   5. DeviceB: enter code words
   6. Wait for sync
   7. DeviceA: bookmark `interia.pl`
   8. DeviceA: bookmark `youtube.com`
   9. Wait till bookmarks are synced to DeviceB
   10. DeviceA:Move `interia.pl` after `youtube.com` bookmark 
   11. Wait till the change is propagated to DeviceB

DeviceA: Ubuntu 18.04LTS
DeviceB: Windows 7x64

## Actual result:

The moving of bookmark is not propagate to another device
DeviceA
![image](https://user-images.githubusercontent.com/34715963/73229788-41dce580-417b-11ea-8353-203e8fb0a7c5.png)

DeviceB
![image](https://user-images.githubusercontent.com/34715963/73229793-4bfee400-417b-11ea-855c-747e89ed8f2a.png)

## Expected result:
The moving of the bookmark is always propagated

## Reproduces how often: 

100% repro rate with above STR

## Brave version (brave://version info)

**Reproducible on**

Brave | 1.5.62 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.5.62 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Ubuntu 18.04 LTS

**Not Reproducible on**

Brave | 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Ubuntu 18.04 LTS

Brave | 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.3.102 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Ubuntu 18.04 LTS

Brave | 1.3.102 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

cc @brave/legacy_qa @jsecretan @AlexeyBarabash @darkdh @rebron

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.5.69 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verification passed on

Brave | 1.5.69 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Ubuntu 18.04 LTS

Verified test plan from the description. This fix needs to be retested after uplift to 1.3.x

**Comment by bsclifton** [comment]
Thanks for verifying, @btlechowski 😄

**Comment by btlechowski** [comment]
The issue still reproduces. Per our process I logged a new issue.

Verification passed on

Brave | 1.3.109 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Ubuntu 18.04 LTS

Issue logged: https://github.com/brave/brave-browser/issues/8065
