### ISSUE TITLE
Reword `Device recognition` as `Fingerprint`

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#7949]
## Test plan
See https://github.com/brave/brave-core/pull/4574

## Description 
The term "Fingerprinting" is becoming more mainstream. We'd like to change all references for `Device recognition` to `Fingerprint`

As an example:
`Cross-site device recognition blocked` => `Cross-site fingerprint blocked`

Let's confirm all uses with @karenkliu, @tomlowenthal, @diracdeltas, and others before closing ticket

## Miscellaneous Information:
Original issue where we changed things to `device recognition`: https://github.com/brave/brave-browser/issues/3027

**Comment by bsclifton** [comment]
@cezaraugusto is this something you'd be able to look at? 😄

**Comment by snyderp** [comment]
Fingerprint is a super overloaded term, even for the very very small number of folks who know web privacy terms.

I think “device fingerprinting” is better than fingerprinting, but I also think we should probably just get rid of this setting all together, as we move to farbling (i.e. fingerprinting protections we have high confidence will not break things)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.7.67 Chromium: 80.0.3987.149 (Official Build) beta (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/4574
**Clean profile**
Shield panel:
![image](https://user-images.githubusercontent.com/38657976/77105518-ccd3b100-6a43-11ea-905f-33e7171268b3.png)

**brave://settings/shields**
![Uploading image.png…]()

**Upgraded profile**

**Comment by karenkliu** [comment]
@GeetaSarvadnya @bsclifton It should be "fingerprinting" not "fingerprinting attempts", so the options should be this:

![image](https://user-images.githubusercontent.com/2388823/77113348-e21af200-69e7-11ea-94e4-1a9bbf19f504.png)

**Comment by cezaraugusto** [comment]
Milestone updated per https://github.com/brave/brave-core/pull/5140 addressing extra feedback per https://github.com/brave/brave-browser/issues/7949#issuecomment-601408346

**Comment by LaurenWags** [comment]
Clearing `QA Pass-Win64` label as this needs to be rechecked due to changes and landing in a new milestone.

**Comment by LaurenWags** [comment]
@karenkliu can you take a look at this one please? It looks like `attempts` was removed from brave://settings/shields:
<img width="713" alt="Screen Shot 2020-04-21 at 1 20 59 PM" src="https://user-images.githubusercontent.com/28145373/79894100-f54c2380-83d2-11ea-837d-3253bea4d174.png">

but still exists in two of the options on the panel (it's in the middle of the strings) Is this ok? afaik there are changes coming to Fingerprinting and its labels - not sure when that is though.

<img width="361" alt="Screen Shot 2020-04-21 at 1 25 20 PM" src="https://user-images.githubusercontent.com/28145373/79894579-a8b51800-83d3-11ea-8ac3-ba3b7dfa0879.png">

**Comment by karenkliu** [comment]
@LaurenWags "Attempts" need to be removed from all the fingerprinting options. I already addressed this in the comment here https://github.com/brave/brave-browser/issues/7949#issuecomment-601408346

The options should be this for both Shields panel and brave://settings/shields:
![image](https://user-images.githubusercontent.com/2388823/80018166-7c100780-848a-11ea-90a3-48aa1ff2dcda.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.8.82 Chromium: 81.0.4044.113 (Official Build) dev (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4574
* Verified test plan from https://github.com/brave/brave-core/pull/5140, however per https://github.com/brave/brave-browser/issues/7949#issuecomment-617945489 the panel should match this as well but does not. Logged follow up issue https://github.com/brave/brave-browser/issues/9399.

brave://settings/shields:
<img width="709" alt="Screen Shot 2020-04-22 at 3 04 39 PM" src="https://user-images.githubusercontent.com/28145373/80023575-bb028500-84ab-11ea-8fc6-985d3f7c8ecf.png">

panel:
<img width="359" alt="Screen Shot 2020-04-22 at 3 05 09 PM" src="https://user-images.githubusercontent.com/28145373/80023579-bd64df00-84ab-11ea-8d6f-d44f9c889026.png">
