### ISSUE TITLE
Site crashing brave

### ISSUE THREAD

**Issue by SinTan1729** [brave/brave-browser#7950]
## Description 
[This site](https://forum.manjaro.org/t/testing-update-2020-01-24-kernels-gamemode-1-5-pamac-9-3/120902) is crashing brave everytime.

## Steps to reproduce 

   1. Open this link

## Actual result 
Brave crashes.

## Expected result
Site should work perfectly.

## Issue reproduces how often 
Easily reproduced

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? No

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.5.3

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by ryanbr** [comment]
I just tested this in Android 10 (OP6) 1.5.3. No crashing here.

Can you you clear site storage for this site?
Does the same thing happen on https://community.brave.com/  (same forum cms)
Does the crash occur in Brave Beta (available via the play store)

**Comment by SinTan1729** [comment]
@ryanbr 
Clearing storage didn't work.
No. That site works well. Although, it's not that the whole Manjaro Forum is crashing. Some pages are functional (such as [this](https://forum.manjaro.org/t/cant-install-manjaro-xfce-19-0-pre3-200120-linux55-rsync-error-11/121325)).
No, it does not occur in Brave Beta.

**Comment by ryanbr** [comment]
@SinTan1729 Just re-tested in 1.5.8 (current release) on Android, is this still causing issues? I browsed the forums, couldn't see any crashes so far.

**Comment by SinTan1729** [comment]
> @SinTan1729 Just re-tested in 1.5.8 (current release) on Android, is this still causing issues? I browsed the forums, couldn't see any crashes so far.

Yes. The issue still happens.

**Comment by ryanbr** [comment]
Is there another mobile phone you can test this on? @SinTan1729

**Comment by SinTan1729** [comment]
@ryanbr Tested on Samsung M30S and Huawei Mediapad T3. Hanging on both.

**Comment by ryanbr** [comment]
We moved to Android core render, is this still an issue? retest in Brave 1.9.80 (we also have Brave Beta and Nightly on Android) @SinTan1729

**Comment by SinTan1729** [comment]
> We moved to Android core render, is this still an issue? retest in Brave 1.9.80 (we also have Brave Beta and Nightly on Android) @SinTan1729 

It doesn't outright crash anymore. But it's still very unstable and works intermittently.

**Comment by ryanbr** [comment]
If there are other issues, we should create a different ticket. I just retested the site on my OP6 (Brave 1.10.99) @SinTan1729 

But no crashing here (and browsed the site)..

![Screenshot_20200710-131848](https://user-images.githubusercontent.com/1659004/87105900-47a13000-c2b0-11ea-9454-acfeaaf79707.jpg)
