### ISSUE TITLE
zooming using ctrl+scroll is disabled 

### ISSUE THREAD

**Issue by TomSwifter** [brave/brave-browser#7952]
Nothing happens 
   3. user ctrl+(+/-) --> expected behavior 
   4. Open a chrome web browser
   5. use ctrl+scrollY. --> expected behavior

## Actual result:
Nothing happens

## Expected result:
Zoom in/out on ctrl+scroll

## Reproduces how often: 
Constantly 

## Brave version (brave://version info)
Version 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the dev channel? YES
- Can you reproduce this issue with the nightly channel? YES

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome?  NO

**Comment by rebron** [comment]
Looks like this is the same behavior in Chromium/Chrome. For this instance, we're not going to deviate from Chromium behavior. 

Closing. wontfix.
