### ISSUE TITLE
C80 followup: Use net::NetworkIsolationKey in ProxyConfigServiceTor::CircuitIsolationKey

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#7955]
from chromium 80 upgrade review comment
https://github.com/brave/brave-core/pull/4374#discussion_r369723424

upstream commit
https://chromium.googlesource.com/chromium/src/+/f04be466f426249887ac9fa2cc8040c384e8624f

cc @riastradh-brave

**Comment by mariospr** [comment]
@darkdh Sorry for requesting extra context but I wonder if you could provide more details on what should be done in here, as well as whether this is something you'd rather tackle yourself or whether is something that I could pick up and add it to my TODO for when I finish https://github.com/brave/brave-browser/issues/7874 and have a gap from rebasing work.

FWIW, I looked into `tor_profile_service_impl.cc`, `proxy_config_service_tor.cc` and `configured_proxy_resolution_service.cc` (included the override) to get a sense of what this might be about but I'm still missing quite a lot of context, so any help clarifying the scope and goal of this issue would be really helpful, if I were to help with it :smiley:

Thanks in advance!

**Comment by darkdh** [comment]
If you take a look at `ProxyConfigServiceTor::CircuitIsolationKey` closer, you will find out the logic is basically duplicate with `SwitchToRegistrableDomainAndRemovePort` in `net/base/network_isolation_key.cc`
So the idea is to remove the duplication and use `net::NetworkIsolationKey` directly so that the way we isolate the storage would be the same as we store circuit information

**Comment by mariospr** [comment]
@darkdh Thanks for the extra info, I'm now (virtually) attending BlinkOn but I'll look into this tomorrow and ask more questions if I have any (which I'm sure I will). Thanks again!
