### ISSUE TITLE
Disable Reporting API

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#7956]
Chromium includes a system called Reporting API.  Its a broad API that is currently used to allow sites to instruct the browser to send at least the following types of information (possibly others) to arbitrary parties (i.e. first or 3p):

- CSP errors
- [Network errors](https://w3c.github.io/network-error-logging/)
- Interventions (e.g. webRequest blocked something)
- Crash reports

Most of the functionality is all defined though HTTP headers, though there is a JS API that allows the site to see and edit reports as they go out).

There is a compile time flag to disable Reporting API.  We should do this.  Of the functionality that goes through Reporting API, two have possible use cases (CSP and crash reports, though Brave opinions differ on whether they're user-respecting to have on by default), and two are clearly privacy harming (network error reporting, that is a clear tracking vector, and intervention reporting, which is obviously horrible).

Regardless of whether we decide to enable CSP and crash reports, there won't be resources to do so for a while.  There is an "easy" way to disable the entire "parent" API (reporting API).  We should do so ASAP, until there are resources to possibly re-enable the non-privacy harming parts.

Information about Reporting API
- [Google Explainer](https://developers.google.com/web/updates/2018/09/reportingapi)
- [Proposed Spec](https://w3c.github.io/reporting/)

## Test Plan

Specified here: https://github.com/brave/brave-core/pull/4578

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.66 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

* Confirmed test plan from https://github.com/brave/brave-core/pull/4578 - visited https://jumde.github.io/test/reporting_observer.html and confirmed `Reporting Observers not available` does display using 1.7.x.
<img width="620" alt="Screen Shot 2020-03-19 at 2 32 05 PM" src="https://user-images.githubusercontent.com/28145373/77102241-e565ac00-69ee-11ea-8134-03ab375378d2.png">

* Also visited https://jumde.github.io/test/reporting_observer.html using 1.5.113 and confirmed `Reporting Observers not available` message does not display using 1.5.113.
<img width="680" alt="Screen Shot 2020-03-19 at 2 35 25 PM" src="https://user-images.githubusercontent.com/28145373/77102234-e39be880-69ee-11ea-8f94-ec05d7790fb0.png">
