### ISSUE TITLE
Browser crashes for cnn.com website

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#796]
## Description 
Browser crashes for cnn.com website

## Steps to Reproduce

   1. Launch Brave core with clean profile from CLI
   2. Enter cnn.com in new tab and click enter
   
## Actual result:
Browser crashes for cnn.com website
Crash Id:
Uploaded Crash Report ID 048267cad41a7268 (Local Crash ID: bcc2325c-7b6d-489f-a63d-84246d7c0727)
Crash report captured on Tuesday, August 21, 2018 at 1:25:42 PM, uploaded on Tuesday, August 21, 2018 at 1:26:33 PM
![browser crash for cnn](https://user-images.githubusercontent.com/38657976/44388759-899f1c80-a546-11e8-9463-1c16994a096b.gif)

## Expected result:
Should not be any crash

## Reproduces how often: 
Always

## Brave version (about:brave info) 
Version 0.54.0 Chromium: 69.0.3497.32 (Official Build) dev (64-bit)

### Reproducible on current release:
No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  NA
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information
cc: @bbondy

**Comment by GeetaSarvadnya** [comment]
Re-validated the issue against the new build 0.54.1. Issue still persists, please find the crash id below:
Crash Report ID b3d6937b545c4038

cc: @bbondy

**Comment by GeetaSarvadnya** [comment]
@bbondy : Crash Report ID 6b17c371d5dcc22c 
Crash Report ID d30f827305b70f0e

**Comment by btlechowski** [comment]
Verified on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

**Comment by layt40** [comment]
nothing happens there will be a solution hard work always compensates and pays off 👍
