### ISSUE TITLE
Implement the Speedreader optimizing pass over a byte stream

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#7968]
We need a custom URLLoader that will pump data of the website main frame into speedreader and proxy it forward to the network stack.

**Comment by iefremov** [comment]
Test plan:
1) launch the browser with `--enable-speedreader`
2) open bbc.com or longreads.com, click on any article.
3) the page should be distilled (there could be problems with images, layout, etc. but at this point this is OK)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.8.82 Chromium: 81.0.4044.113 (Official Build) dev (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-browser/issues/7968#issuecomment-600751272
* From bbc.com and longreads.com I navigated to a handful of articles on each page and all articles opened as expected and were displayed as distilled.
