### ISSUE TITLE
Implement the hardcoded whitelist for speedreader

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#7969]
For the first iteration we can start with the hardcoded whitelist of URLs implemented as `URLLoaderThrottle`. Whitelisted sites are proxied through the speedreader library, other stay untouched.

**Comment by LaurenWags** [comment]
@iefremov if this issue requires manual QA please add `QA/Yes` label and a test plan. If not, please add `QA/No` label. Thanks! cc @kjozwiak

**Comment by LaurenWags** [comment]
@iefremov pinging on https://github.com/brave/brave-browser/issues/7969#issuecomment-611617978 this one, could you take a look please? Thanks! cc @kjozwiak @bsclifton

**Comment by iefremov** [comment]
@LaurenWags Sorry for the delay, I think it would be better to test it together with https://github.com/brave/brave-browser/issues/8416
