### ISSUE TITLE
Web view crash for nytimes 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#797]
## Description 
Web view crash for nytimes 

## Steps to Reproduce

   1. Launch Brave core with clean profile from CLI
   2. Enter nytimes.com in new tab and click enter 

## Actual result:
Web view crash for nytimes
Crash ID:
Uploaded Crash Report ID da6c9a36a98e7f69 (Local Crash ID: b5ba49bb-4c54-458a-9d8e-36b50593b3e8)
Crash report captured on Tuesday, August 21, 2018 at 1:36:56 PM, uploaded on Tuesday, August 21, 2018 at 1:39:46 PM
![webview crash for nytimes](https://user-images.githubusercontent.com/38657976/44389191-d2a3a080-a547-11e8-96ce-217f966be283.gif)

## Expected result:
Should not be any crash

## Reproduces how often: 
Always

## Brave version (about:brave info) 
Version 0.54.0 Chromium: 69.0.3497.32 (Official Build) dev (64-bit)

### Reproducible on current release:
No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information
cc: @bbondy

**Comment by GeetaSarvadnya** [comment]
Re-validated the issue against the new build 0.54.1. Issue still persists, please find the crash id below:
Crash Report ID 61c088b83cb7e721

cc: @bbondy

**Comment by GeetaSarvadnya** [comment]
@bbondy: Report ID c1bbb361d7dd5c87
Crash Report ID 859a5332a775130b

**Comment by btlechowski** [comment]
Verified on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7
