### ISSUE TITLE
Users should be able to import Extensions

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#7974]
## Description 
Users are able to import from Chrome, Firefox, Edge, Safari (options can depend on their platform).

They can import bookmarks, passwords, etc. But there is currently no way to import extensions and extension settings

Offering this would be a great way to make Brave easier to switch to

## Steps to Reproduce
   1. Use Chrome and have a few extensions, each which may have a specific config
   2. Launch Brave and go to import

## Actual result:
No way to import extensions ☹️ 

## Expected result:
You should be able to import extensions

**Comment by simonhong** [comment]
I think chromium's extension sync logic could be helpful because chrome is syncing extension list and it installs synced list in background.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.8.82 Chromium: 81.0.4044.113 (Official Build) dev (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4672
* Confirmed if no extensions are installed on Chrome the 'Extensions' checkbox does not display on brave://settings/importData
<img width="537" alt="Screen Shot 2020-04-22 at 12 08 11 PM" src="https://user-images.githubusercontent.com/28145373/80020935-cfdd1980-84a7-11ea-9df0-430828262651.png">

* Confirmed if at least one extension is installed on Chrome the 'Extensions' checkbox does display on brave://settings/importData
<img width="538" alt="Screen Shot 2020-04-22 at 12 09 27 PM" src="https://user-images.githubusercontent.com/28145373/80020947-d23f7380-84a7-11ea-9b4a-3ce795b8afa2.png">


* Confirmed able to import extensions from Chrome using:
  * direct navigation to brave://settings/importData
  * brave://welcome import slide
  * navigating to brave://settings and selecting 'Import bookmarks and settings' (opens brave://settings/importData)
  * hamburger menu > Bookmarks > Import Bookmarks and Settings (opens brave://settings/importData)
  * (macOS only) file menu > Brave > Import Bookmarks and Settings (opens brave://settings/importData)

* Confirmed navigating to brave://extensions shows the imported extensions
* Confirmed able to remove imported extensions
* Confirmed able to interact with imported extensions
* Confirmed able to add new extensions after import

Tested using: Honey, Grammarly

Note - state is not persisted (must re-log in to all extensions), confirmed with @bsclifton. This will be covered by a separate issue https://github.com/brave/brave-browser/issues/8847.
