### ISSUE TITLE
Add proxies to handle Crowd Deny download

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#7976]
https://cs.chromium.org/chromium/src/chrome/browser/component_updater/crowd_deny_component_installer.cc 

### Test Plan

Specified here: https://github.com/brave/brave-core/pull/4482

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.3 x64` using the following build:

Brave | 1.3.113 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.15.3 (Build 19D76)

* Verified the STR outlined under https://github.com/brave/brave-core/pull/4482.

![Screen Shot 2020-02-07 at 12 32 05 PM](https://user-images.githubusercontent.com/2602313/74051468-02e23780-49a6-11ea-90c0-a025314ab328.png)

![Screen Shot 2020-02-07 at 12 29 43 PM](https://user-images.githubusercontent.com/2602313/74051476-070e5500-49a6-11ea-95d4-29b27bec4e30.png)
