### ISSUE TITLE
Web view or Browser crashes for few non secure sites in first launch

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#798]
## Description 
Web view or browser crashes for few non secure sites in first launch

## Steps to Reproduce

   1.  Launch brave with clean profile from CLI
   2.  Open espn.com in new tab
   3.  Observe the web view/Browsercrash

Note: Sometimes browser itself is getting crashed, most of the time web view is crashing.

## Actual result:
Crash ID for web view:
Uploaded Crash Report ID 017ef562c590d4ed (Local Crash ID: e070efda-6aa9-4f24-a1a6-e4f4db44a0a3)
Crash report captured on Tuesday, August 21, 2018 at 2:48:50 PM, uploaded on Tuesday, August 21, 2018 at 2:53:02 PM

![web view crash for few non secure sites in first load](https://user-images.githubusercontent.com/38657976/44393322-f7047a80-a551-11e8-82c0-bdb323a7d24a.gif)

Crash ID for browser:
Uploaded Crash Report ID 1f155e5db33398c0 (Local Crash ID: 07006a02-267f-4dd9-87c3-c4ef331a22ee)
Crash report captured on Tuesday, August 21, 2018 at 2:56:35 PM, uploaded on Tuesday, August 21, 2018 at 2:59:36 PM
![browser crash for espn](https://user-images.githubusercontent.com/38657976/44393635-dee12b00-a552-11e8-804d-16e745611358.gif)

## Expected result:
Should not be any crash

## Reproduces how often: 
80% Reproducible rate

## Brave version (about:brave info) 
Version 0.54.0 Chromium: 69.0.3497.32 (Official Build) dev (64-bit)

### Reproducible on current release:
No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information
cc : @bbondy

**Comment by GeetaSarvadnya** [comment]
Issue is reproduced on new build 0.54.1. Issue still persists. Please find the below crash id 
Crash Report ID 844f35487414e1ca
cc: @bbondy

**Comment by srirambv** [comment]
Issue reproduced on upgrade profile as well. 
Crash ID d2f45d09782387bd

**Comment by GeetaSarvadnya** [comment]
@bbondy :Crash Report ID b9760b2a758e6a15

**Comment by btlechowski** [comment]
Verified on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

**Comment by filmendless** [comment]
> Verified on
> 
> Brave	0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
> Revision	16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
> OS	Windows 7
> Verification Pass with
> 
> Brave	0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
> Revision	16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
> OS	Mac OS X
> 
> Verification Passed on
> 
> Brave	0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
> Revision	16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
> OS	Linux
