### ISSUE TITLE
extension not working with tor

### ISSUE THREAD

**Issue by satyamisme** [brave/brave-browser#7980]
## Steps to Reproduce

   1. tried reinstall still unable to load extensions in tor 
   2. search for experiminetal flags but found nothing related 
   3. enabled allow acess site and info in manage extensions section

## Brave version (brave://version info)

Brave | 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1909 (Build 18363.592)
JavaScript | V8 7.9.317.33
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

**Comment by K1ngjulien** [comment]
its probably better to not use extensions when using tor. I mean the point of tor is to not be tracked, which many extensions do.

**Comment by satyamisme** [comment]
would be happy if enabled as experimental option in chrome flags

**Comment by bsclifton** [comment]
Thanks for the report folks - I believe this is already tracked with https://github.com/brave/brave-browser/issues/2761

Unfortunately, there hasn't been any progress made on this. But you can follow that issue for updates 😄
