### ISSUE TITLE
Brave crashes when new sync chain is started at the 2nd time

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#7982]
## Description 

Brave crashes when new sync chain is started at the 2nd time
## Steps to Reproduce

Scenario1:

   1. Clean profile 1.3.x
   2. Open Sync 
   3. Click on `Start a new sync chain`
   4. Select `Phone/Tablet` option
   5. Click on `Cancel` button in the QR code modal
   6. Remove the desktop device which is listed in the `Device Name` section in brave://sync page
   7. Click on `Start a new sync chain`
   8. Brave crashes

Scenario2:
   1. Clean profile 1.3.x
   2. Open Sync 
   3. Click on `Start a new sync chain`
   4. Select `Phone/Tablet` option
   5. Click on `Cancel` button in the QR code modal
   6. Remove the desktop device which is listed in the `Device Name` section in brave://sync page
   7. Click on `I have sync code`
   8. Enter the sync code which is copied from another device
   9. Brave crashes
   

## Actual result:

Brave crashes when new sync chain is started at the 2nd time
![Sync crash issue](https://user-images.githubusercontent.com/38657976/73453082-47137d80-4391-11ea-98fc-792a484bb7ff.gif)

## Expected result:
Should not be any crash

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.3.105 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @AlexeyBarabash @darkdh @rebron @bsclifton

**Comment by AlexeyBarabash** [comment]
Thanks @GeetaSarvadnya 
This seems the same as https://github.com/brave/brave-browser/issues/7412 , fixed with https://github.com/brave/brave-core/pull/4281, now this is in 1.4.x (dev).
