### ISSUE TITLE
Sync thread sometime hangs

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#7986]
The integration of chromium sync and brave sync relies on `syncer::Syncer` to tell js sync extension to poll or commit changes. The hanging happens when polling remote records.

Sync thread will be blocked until new records or no records passed back to syncer
syncer->js sync extension (Block): https://github.com/brave/brave-core/blob/370057c4df9f726fe2a2c47c7f6672ee6488db02/chromium_src/components/sync/engine_impl/syncer.cc#L31
js extension->sync (Signal): https://github.com/brave/brave-core/blob/370057c4df9f726fe2a2c47c7f6672ee6488db02/components/brave_sync/brave_profile_sync_service_impl.cc#L569

I don't know the specific STR but when the hanging happens syncer and js sync extension are waiting for each other causing a deadlock. 
When that happens, 
1. js sync extension is idle, no new records coming in or out
2. When browser shutdown, it waits for sync thread to end but it is hanging.

cc @AlexeyBarabash @bridiver @jsecretan

**Comment by btlechowski** [comment]
I have experienced this issue few times. I was unable to relaunch the browser when this happened thus making Brave unusable.

Brave | 1.5.75 Chromium: 80.0.3987.66 (Official Build) nightly (64-bit)
-- | --
Revision | 56ea77d65c47ecbb1180b99f860d85b51117864a-refs/branch-heads/3987@{#662}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

cc @brave/legacy_qa

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.3 x64 Catalina` using the following build:

```
Brave | 1.7.79 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.15.3 (Build 19D76)
```

* Verified the STR/Cases outlined via https://github.com/brave/brave-core/pull/4550#issue-372248646 using the following combination:
  * `1.7.79 CR: 80.0.3987.149` <--> `1.5.115 CR: 80.0.3987.149` (Desktop Release)
  * `1.7.79 CR: 80.0.3987.149` <--> `1.5.116 CR: 80.0.3987.149` (Brave-Beta Android)
  * `1.7.79 CR: 80.0.3987.149` <--> `1.15 (20.03.05.14)` (iOS Release)

Once the change from https://github.com/brave/brave-core/pull/4550#issue-372248646 has been applied into `extensions/background.js`:

<img width="843" alt="Screen Shot 2020-03-31 at 2 24 34 PM" src="https://user-images.githubusercontent.com/2602313/78062643-fa323000-735c-11ea-874c-650ebc54765a.png">

Once the change from https://github.com/brave/brave-core/pull/4550#issue-372248646 has been reverted from `extensions/background.js`:

<img width="928" alt="Screen Shot 2020-03-31 at 2 32 22 PM" src="https://user-images.githubusercontent.com/2602313/78062648-fc948a00-735c-11ea-818f-eccd0ff96b3a.png">
