### ISSUE TITLE
crash after install

### ISSUE THREAD

**Issue by oivinds** [brave/brave-browser#7988]
I (re)installed Brave for osx today. 
After installation, brave displays a message dialog about restoring previous vindows for a split second then immediately crashes / closes. 

This is the beginning of the osx crash error submitting form that appears after brave crashes:

```
Process:               Brave Browser [94134]
Path:                  /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Identifier:            com.brave.Browser
Version:               79.1.2.43 (102.43)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Brave Browser [94134]
User ID:               501

Date/Time:             2020-01-30 22:54:59.987 +0100
OS Version:            Mac OS X 10.13.6 (17G10021)
Report Version:        12
..
..

Time Awake Since Boot: 510000 seconds
Time Since Wake:       2700 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000048

VM Regions Near 0x48:
...
```
I also had the same problem with a beta version.

**Comment by kjozwiak** [comment]
@oivinds mind going into `brave://crashes` see if there's any crashes that might have been logged? If you don't have `Automatically send crash reports to Brave` enabled, you'll need to send them to us via the `Send Now` button. Example:

<img width="724" alt="Screen Shot 2020-01-31 at 12 57 47 AM" src="https://user-images.githubusercontent.com/2602313/73515883-c3738400-43c4-11ea-8cb3-585fadb7a871.png">

Once you've submitted the crashes, please let us know the `Crash Report ID` of the submitted crashes.

**Comment by oivinds** [comment]
The browser window disappears before i get a crash page like your screenshot above.

**Comment by himanshubabal** [comment]
Similar problem
The browser works only using `sudo` from the terminal.
I have already posted this issue on Brave Community.
[Please have a look](https://community.brave.com/t/brave-desktop-for-mac-crashing-macos-10-15-3/105955)

**Comment by bsclifton** [comment]
@oivinds can you please try a newer version of Brave? I suspect the problem you had reported originally has been fixed

@himanshubabal what version of Brave are you using? Latest release channel is `1.3.115`

**Comment by himanshubabal** [comment]
@bsclifton Yes that was me. Apologies for a different username.
It worked. 
Thank You so much

**Comment by oivinds** [comment]
Just installed latest version from https://www.bravebrowsers.com
As before, It crash immediately. So no window is open to report a crash.
Apples mac os  crash reporter : 
```

Process:               Brave Browser [44013]
Path:                  /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Identifier:            com.brave.Browser
Version:               80.1.3.118 (103.118)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Brave Browser [44013]
User ID:               501

Date/Time:             2020-02-21 09:46:41.877 +0100
OS Version:            Mac OS X 10.13.6 (17G11023)
Report Version:        12
Anonymous UUID:        F709EF00-004A-A6C7-ABC1-8854EB3D04BC

Sleep/Wake UUID:       9C987602-BDC1-4ACB-BE5E-E9940DBF69AC

Time Awake Since Boot: 710000 seconds
Time Since Wake:       740 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000048

VM Regions Near 0x48:
--> 
    __TEXT                 000000010574b000-0000000105775000 [  168K] r-x/r-x SM=COW  /Applications/Brave Browser.app/Contents/MacOS/Brave Browser


```
