### ISSUE TITLE
gpg: no valid OpenPGP data found.

### ISSUE THREAD

**Issue by jimpriest** [brave/brave-browser#7994]
## Description 
Following installation instructions here - https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux When running this command:

```
curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
```
I get an error: gpg: no valid OpenPGP data found.

## Expected result:
To successfully install Brave browser

## Reproduces how often: 
Happens every time

## Brave version (brave://version info)
Not installed...

## Other Additional Information:
Ubuntu 18

Seems like a security issue: 
https://askubuntu.com/questions/1201434/gpg-no-valid-openpgp-data-found-while-installing-brave-browser

Either that should be addressed or the installation instructions should be modified...

**Comment by bsclifton** [comment]
cc: @mbacchi @fmarier @mihaiplesa @bkero

**Comment by mbacchi** [comment]
This works on Ubuntu 16, can you try again? We did have a problem with our GPG key at one point, and this may have been transient for you.

**Comment by rebron** [comment]
@jimpriest As per @mbacchi above, can you try again? Working now?

**Comment by ksnell88** [comment]
I am having the same issue. The .asc file, even when downloaded from the browser at the below link, is blank.


https://brave-browser-apt-release.s3.brave.com/brave-core.asc

**Comment by mbacchi** [comment]
> I am having the same issue. The .asc file, even when downloaded from the browser at the below link, is blank.
> 
> https://brave-browser-apt-release.s3.brave.com/brave-core.asc

This was a test I was doing for linux signing, that is now fixed. Sorry for the confusion, please go ahead and try to install again it should work fine, I've verified the .asc file.

**Comment by ksnell88** [comment]
Thanks. I ended up installing the snap to get by.

**Comment by fmarier** [comment]
I'm going to assume that these were temporary issues which have been resolved. Please reopen if you encounter this problem again in the future.

**Comment by Crucizer** [comment]
I'm having this same issue now

**Comment by fmarier** [comment]
@Crucizer What do you get when you run the first part of that command?

    curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc

**Comment by Crucizer** [comment]
Actually, I tried a few hours later and it just worked.

**Comment by MuhammadHaris786** [comment]
The topic is old, but I will still give you an answer. As far as I know, this is because we are referring to a non-existent file. You can try installing brave in this way:

--------------- To install Snap-Store if you haven't ---------------

        sudo rm /etc/apt/preferences.d/nosnap.pref
        sudo apt update
        sudo apt install snapd
        sudo snap install snapd

--------------- After that install brave from snap ---------------

        sudo snap install brave

**Comment by fmarier** [comment]
In our official Linux installation instructions, you will find a comment explaining why we don't currently recommend the Snap package: https://brave.com/linux/#snap (i.e. it doesn't work as well as the packages due to Snap limitations).
