### ISSUE TITLE
Define initial whitelist of URLs SpeedReader will handle

### ISSUE THREAD

**Issue by AndriusA** [brave/brave-browser#7995]
For the currently accepted SpeedReader deployment approach we need a whitelist of URLs it will be executed on when enabled:

1. Pick 100 English news sites where current content extractor works well
2. Identify site URL patterns where the extractor works/does not (e.g. do not run on landing page or video-oriented pages)

**Comment by bsclifton** [comment]
Added missing milestone; also added `QA/No` label. Please add `QA/Yes` and steps if any manual testing is required
cc: @bridiver
