### ISSUE TITLE
connected, not KYC'd user wallets cannot tip with user BAT

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#7999]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/6078

If you have a connected but not KYC'd user wallet with BAT in the Brave Browser card (on Uphold), you cannot tip, AC, etc with that BAT. 

## Steps to Reproduce

   1. Clean profile - launch with staging parameters, short reconcile interval
   2. Enable Rewards, do not claim the staging grant.
   3. Select Verify Wallet and login to uphold with a connected but not KYC'd account
   4. If necessary, add BAT to the Brave Browser card on Uphold. 
   5. Try to tip (to a verified, KYC'd publisher), auto contribute, have recurring tip (for verified, KYC'd publisher) go thru.

## Actual result:

Tip does not go thru (get generic 'problem processing error). AC and recurring tip do not go thru either.

## Expected result:
Tips and AC should go thru - be deducted from wallet balance and display on brave://rewards and panel. 

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.3.106 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

Brave | 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes, reproduces on 1.2.x
- Can you reproduce this issue with the beta channel? yes reproduces on 1.3.x
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @mandar-brave @NejcZdovc @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Reproduced on windows 

Brave | 1.3.107 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.3.108 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G103)

* Verified the following (on staging environment):
Using a connected but not KYC'd user wallet, I was able to
   - [x] do a one time tip
   - [x] a monthly tip (contribution)
   - [x] auto contribution 
   - [x] Confirmed that all transactions work as expected and are reflected accurately on the BR panel and on brave://rewards. 
   - [x] Confirmed wallet balance decreases accurately.
<img width="743" alt="Screen Shot 2020-02-04 at 11 14 18 AM" src="https://user-images.githubusercontent.com/28145373/73763613-aa116580-473f-11ea-86b3-3a8b9f3d1f4b.png">

* Also did a quick check on production by doing a 1 time tip. Verified tip was displayed on brave://rewards and in the panel, wallet balance decreased as expected.
