### ISSUE TITLE
Data folder path on Linux

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#80]
Currently production Brave (electron) stores data in folders: 
`/home/<user>/.config/brave`
and
`/home/<user>/.config/brave-beta`

Chromium-fork Brave stores in
`/home/<user>/.config/brave`
and
`/home/<user>/.config/brave-development` for non-official builds
Beta and unstable channels 
`/home/<user>/.config/brave-beta`
and
`/home/<user>/.config/brave-unstable`

This may cause a conflict.

It makes sense to rename dir to 
`/home/<user>/.config/brave-browser` until it is not released.

It is already has a patch near https://github.com/brave/browser-android-tabs/blob/master/chrome/common/chrome_paths_linux.cc#L78 .

**Comment by srirambv** [comment]
@AlexeyBarabash @garrettr Am assuming the new standard is BraveSoftware-> Brave-Browser-Dev on all platforms. So this is ok to mark as Pass ?

![image](https://user-images.githubusercontent.com/17010094/45889480-90f85680-bd8e-11e8-951a-cf385dab50b4.png)

**Comment by AlexeyBarabash** [comment]
@srirambv , yes now path is `.config/BraveSoftware/Brave-Browser-Dev` 
`/home/<user>/.config/brave` is an obsolete.
ok to mark as Pass.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux
