### ISSUE TITLE
"Safe Browsing" option in settings needs to be named "Google Safe Browsing"

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#8002]
## Description 
Currently the Safe Browsing option on the Settings page has a typo/bug; it's missing "Google" as part of the label.

## Steps to Reproduce
   1. Go to chrome://settings/privacy
   2. See the typo in "Safe Browsing" title

## Actual result:
![Screen Shot 2020-01-31 at 6 08 54 PM](https://user-images.githubusercontent.com/2388823/73585319-14cb5400-4455-11ea-91c4-82b09f639ec9.png)

## Expected result:
It should have "Google" in the title - "Google Safe Browsing".

## Reproduces how often: 
easily reproduced on all channels

**Comment by karenkliu** [comment]
@tomlowenthal  FYI

**Comment by bsclifton** [comment]
Should be an easy change; not a problem in Chrome because I don't think Safe Browsing can be disabled

**Comment by MatthewZito** [comment]
Hi, @bsclifton - I'm a big fan of Brave and believe this would be a good first issue for me to get started with contributing. Will you assign this to me? 

I'm currently reading through all of your contribution guidelines to get up to speed. Thanks!

**Comment by bsclifton** [comment]
@MatthewZito awesome- issue assigned (thanks, @rebron 😄)

Once you get setup and have something building, you might just take a peek here:
https://github.com/brave/brave-core/blob/fd90db30af93e51387b312396d0d92484cdde47a/app/settings_strings.grdp#L2998-L3000

**Comment by MatthewZito** [comment]
> @MatthewZito awesome- issue assigned (thanks, @rebron )
> 
> Once you get setup and have something building, you might just take a peek here:
> https://github.com/brave/brave-core/blob/fd90db30af93e51387b312396d0d92484cdde47a/app/settings_strings.grdp#L2998-L3000

Great, thanks! I read through the docs - it looks like this PR will just be made against this repo's `master` branch...or should I be looking for a specific version in the `Projects` area for Settings bugfixes?

**Comment by MatthewZito** [comment]
Thanks @rebron - PR opened. Please let me know if there's anything I should do differently next time ;D

**Comment by jofftiquez** [comment]
I'm curious. Why does it need to have the "Google" in it? Thanks.

**Comment by karenkliu** [comment]
cc @tomlowenthal ☝️

**Comment by rebron** [comment]
@jofftiquez We need to clarify that the Safe Browsing service is coming from Google and not a service created by Brave. https://safebrowsing.google.com/ The Safe Browsing service was put into Firefox originally and pre-dates Chrome and is used by other browsers as well.

@MatthewZito Thanks for the fix, this was great. Let's do it again!

**Comment by jofftiquez** [comment]
@rebron thanks, I understand now.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.7.67 Chromium: 80.0.3987.149 (Official Build) beta (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the description from the issue
- Verified in both clean and upgraded profiles
![image](https://user-images.githubusercontent.com/38657976/77108831-ecb9a380-6a48-11ea-8b46-812f6696f292.png)
