### ISSUE TITLE
Login button doesn't work with Shield enabled on sakei.com

### ISSUE THREAD

**Issue by chkk525** [brave/brave-browser#8003]
## Description 

Clicking login button on https://www.sankei.com/ doesn't work

## Steps to Reproduce

   1.  Go to https://www.sankei.com/
   2. Click login button(ログイン, #member_list_01 > ul > li.login) in the right top

## Actual result:

![image](https://user-images.githubusercontent.com/3054915/73586421-2f9ed680-44f0-11ea-87fe-7139c74c15ed.png)

- Got error message in the console saying 'ga is not defined'

## Expected result:
Redirect to login page

## Reproduces how often: 

Easily reproduced. Happen everytime.

## Brave version (brave://version info)

Brave | 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS バージョン10.15.2（ビルド19C57）

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
Yes

- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
This will help

https://github.com/easylist/easylist/commit/0b4564563da588c0f788f7df716d5eb85c4b266f

**Comment by bsclifton** [comment]
Looks like this is resolved now 😄 🎉
