### ISSUE TITLE
I can't withdraw funds what I earn the previous month (Ubuntu Brave Beta)

### ISSUE THREAD

**Issue by Gustbel** [brave/brave-browser#8004]
## Description 

I can't withdraw funds what I earn the previous month from Ubuntu. Actually I was able to withdraw only a part (0.3 BAT), from the Windows 10 program.
But the rest (0.6 BAT) appears only in Ubuntu Brave, and when I click on "Withdraw Funds" it redirects me to Uphold correctly but the 0.6 BAT of the browser is not debited.
In my computer Ubuntu and Windows 10 Brave brownser use the same seed wallet.

## Steps to Reproduce

   1. I go to brave://rewards/
   2. Click in Withdraw Funds (0.6 BAT earned from ads - Wallet Verified)
   3. Redirected to Uphold page. 0 BAT, the Withdraw was not made.

## Actual result:
![Screenshot from 2020-02-01 13-04-21](https://user-images.githubusercontent.com/44475146/73595122-7fcb6800-44f3-11ea-803f-d447d21b69c6.png)
![Screenshot from 2020-02-01 13-04-39](https://user-images.githubusercontent.com/44475146/73595123-85c14900-44f3-11ea-8e2a-0649820d77ee.png)

## Expected result:
Withdraw BAT in the Uphold Account like the program of Windows 10 

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 1.3.106 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Linux
JavaScript | V8 7.9.317.33
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Command Line | /opt/brave.com/brave-beta/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,WebXrGamepadModule,UnifiedConsent,LookalikeUrlNavigationSuggestionsUI,WebXR,AllowPopupsDuringPageUnload,SyncUSSBookmarks --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service
Executable Path | /opt/brave.com/brave-beta/brave
Profile Path | /home/gustavo/.config/BraveSoftware/Brave-Browser-Beta/Default

**Comment by bsclifton** [comment]
cc: @NejcZdovc

**Comment by NejcZdovc** [comment]
@Gustbel when did you connect to uphold on this computer? Did you claim ad grant on this computer?

**Comment by NejcZdovc** [comment]
closing as stale

**Comment by Gustbel** [comment]
I couldn't solve it, but it doesn't matter. I never had that problem again. Thanks
