### ISSUE TITLE
New tab wrong resolution

### ISSUE THREAD

**Issue by LucaTheHacker** [brave/brave-browser#8008]
## Description 
New tab images have a resolution that doesn't match the screen one.

## Steps to Reproduce

   1.  Get a 4k screen
   2.  Download a 4k or higher image (https://damettoluca.com/assets/images/telegramcrash.jpg)
   3.  Compare the resolutions.

## Actual result:
Actually the background resolution doesn't match with the screen one and there's an horrible effect for who loves high-quality things.

## Expected result:
Background resolution should match the screen resolution one.

## Reproduces how often: 
Easily reproduced

## Brave version:
Brave | 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1909 (Build 18363.592)

## Version/Channel Information:
- Can you reproduce this issue with the current release? y
- Can you reproduce this issue with the beta channel? y
- Can you reproduce this issue with the dev channel? y
- Can you reproduce this issue with the nightly channel? y
 
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? not releated
- Does the issue resolve itself when disabling Brave Rewards? not releated
- Is the issue reproducible on the latest version of Chrome? no (?)

**Comment by bsclifton** [comment]
@LucaTheHacker not sure I understand the complaint- when I download the image, it looks OK to me?

I do need to click the magnifying glass on the image to see the image at it's true resolution. Can you describe the problem in more detail?

**Comment by LucaTheHacker** [comment]
I'm saying that the new tab image resolution doesn't match the screen one. I used that image just to allow users to compare the resolutions

**Comment by rebron** [comment]
Closing. We upscale images on the new tab page and the images resize as you change the size of the window. We have a new set of wallpaper coming soon to look forward to!
