### ISSUE TITLE
Breakdown overuse of 'LEDGER_ERROR'

### ISSUE THREAD

**Issue by masparrow** [brave/brave-browser#8009]
Searching for where `ledger::Result::LEDGER_ERROR` is potentially returned as an error code yields almost 200 code locations (depending on the Brave version/branch searched).

From then on it seems the majority (if not all) are treated as unidentifiable error scenarios, when this is not the case.

This makes diagnosing issues related to this error extremely difficult without domain knowledge of Ledger/Rewards.

We need to evaluate the overuse of this error code, and determine;

- do all the instances require unique error codes?
-- highly unlikely
- can we better categorise/group them into new error codes?
-- we can then use diagnostic logging to capture specific outcomes within each group
- handle new error codes introduced in a better way for UX 
-- needs business / design discussion for the codes/scenarios found

**Comment by Miyayes** [comment]
@szilardszaloki has implemented a lot of specific enums so far.
