### ISSUE TITLE
[suggest] Hope to add brave shields website whitelist feature

### ISSUE THREAD

**Issue by zfoxzero** [brave/brave-browser#8010]
Hope to add brave shields whitelist feature
Support for export and import website  list
Conveniently add a list of required websites in batches
thanks

**Comment by zfoxzero** [comment]
OvO

**Comment by bsclifton** [comment]
Thanks for the feature request, @zfoxzero 😄 We have a request for this already if you'd like to give it a +1 or leave an additional comment

Please see https://github.com/brave/brave-browser/issues/7538

I'll close this as a duplicate. Thanks again!
