### ISSUE TITLE
Payment fails when i try to pay on Udemy.com and bunch of other sites

### ISSUE THREAD

**Issue by chirag-farfetch** [brave/brave-browser#8011]
Payment fails when I try to pay on Udemy.com and a bunch of other sites. On google chrome it works however on brave browser it does not work

**Comment by ryanbr** [comment]
Hey @chirag-farfetch can you re-test with `Allow all cookies` in Shields?

**Comment by chirag-farfetch** [comment]
@ryanbr , unfortunately i already made the purchase using other browser. I will do this next time i purchase and will let you know if i find the same issue. Thank you

**Comment by ryanbr** [comment]
I'll close this for the time being, just tag me again /link to this ticket if it occurs again. But Allowing Cookies should help :)
