### ISSUE TITLE
[Android] Always crash whenever loading http://www.ciokorea.com/news/17850

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#8016]
## Description 
Always crash whenever loading http://www.ciokorea.com/news/17850

## Steps to reproduce 

   1. Loading this url in android beta
   2. 
   3. 

## Actual result 
crashed

## Issue reproduces how often 
Easily reproduced

## Issue happens on 
   - Current Play Store version? no
   - Beta build? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 9
   
## Brave version
Brave - Beta 1.5.59, Chromium 79.0.3945.130

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? Can't test because crashed right after loading
- Does the issue resolve itself when disabling Brave Rewards? Can't test because crashed right after loading
- Is the issue reproducible on the latest version of Chrome? No

**Comment by SergeyZhukovsky** [comment]
I don't see any crashes on that website with the latest v1.5.100. @simonhong would you mind to check on your side?

**Comment by emerick** [comment]
Same here for me. I looked at this in the morning and couldn't repro.

**Comment by simonhong** [comment]
Yes! not crashed anymore on beta. Closed 👍

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.5.110 BraveModernx86.apk
- Confirmed no crash observed when visiting the URL from the description
