### ISSUE TITLE
Folllow up of #7526 - Unable to set monthly tips hence not shown under contribution panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8019]
## Description 

Follow up of #7526 - Unable to set monthly tips hence not shown under contribution panel
## Steps to Reproduce

   1. Clean profile 1.3.107 - launch using `brave.exe --rewards=staging=true,reconcile-interval=3`
   2. Claim the UGP grants
   3. Open https://duckduckgo.com/
   4. Open the BR panel and set the monthly contributions for https://duckduckgo.com/
   5. The monthly Tip isn't set and https://duckduckgo.com/ isn't displayed under monthly contributions panel.
 

## Actual result:

Folllow up of #7526 - Unable to set monthly tips hence not shown under contribution panel

![Monthly tips](https://user-images.githubusercontent.com/38657976/73626610-9ac2e700-466f-11ea-88b4-81f9fd33363d.gif)

## Expected result:
Should be able to set Monthly tips.

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.3.107 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? No 
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @masparrow @rebron

**Comment by LaurenWags** [comment]
@GeetaSarvadnya are you launching with a short reconcile interval? your contribution date is today by the looks of your gif. Could you try without a reconcile interval and see if the issue reproduces? Also, can you try refreshing your brave://rewards page since you had it open? wondering if it's a display problem?

**Comment by GeetaSarvadnya** [comment]
@LaurenWags Yup, I am launching brave with a short reconcile interval of 3 minutes. Issues persist with and without reconcile interval in beta. However, I am unable to reproduce the issue with Dev and Nightly channels.

**Comment by btlechowski** [comment]
I am not able to reproduce on Beta on Ubuntu

Verification passed on

Brave | 1.3.108 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/73673447-eea0f080-46ae-11ea-8032-b8ffb3bb7f64.png)

**Comment by btlechowski** [comment]
Not reproducible on Windows 7x64

Brave | 1.3.107 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

![image](https://user-images.githubusercontent.com/34715963/73673755-843c8000-46af-11ea-94a3-bf5a5d0709c7.png)

**Comment by GeetaSarvadnya** [comment]
@btlechowski Can you try it on windows 10.? The issue is consistently reproducible in windows 10 x64

**Comment by btlechowski** [comment]
Reproduced on

Brave | 1.3.113 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

![image](https://user-images.githubusercontent.com/34715963/74049713-0214ca00-49d5-11ea-811e-9e4fa078710c.png)

**Comment by GeetaSarvadnya** [comment]
The issue is working fine hence closing the issue 

Brave | 1.4.84 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.1006)
