### ISSUE TITLE
Infura key not present in debug builds

### ISSUE THREAD

**Issue by jonathanKingston** [brave/brave-browser#8020]
## Description 
When running a debug build the Crypto Wallets extension gets very noisy on the cli due to what appears to be either a rate limited server or blocked.

Perhaps rate limited would be reduced by providing the `BraveServiceKey` key mentioned in https://github.com/brave/brave-browser/issues/7062#issuecomment-570429748?

## Steps to Reproduce

   1. Download brave-browser
   2. Build a debug build.
   3. Run with npm start

  To diagnose the networks requests I was able to modify the start command in package.json to add `--show_component_extensions` and go to brave://extensions

## Actual result:

Console filled with:
```
[...:ERROR:CONSOLE(35993)] "Error: PollingBlockTracker - encountered an error while attempting to update latest block:
Error: 
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>403 Forbidden</title>
  </head>
  <body>
    <h1>Error 403 Forbidden</h1>
    <p>Forbidden</p>
    <h3>Guru Mediation:</h3>
    <p>Details: ...</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>

    at s (chrome-extension://.../background.js:39005:20)
    at Object.internal (chrome-extension://.../background.js:39016:33)
    at d (chrome-extension://.../background.js:39725:22)
    at l (chrome-extension://.../background.js:39669:27)
    at async chrome-extension://.../background.js:39739:21
```

## Expected result:

Service to work as expected and not cause so many logs

## Reproduces how often: 

Doesn't appear to happen initially, however after 20minutes or so the console is nothing but these logs.

**Comment by ryanml** [comment]
Hi @jonathanKingston - currently our Infura project credentials are not present in debug builds of the brave browser.

If you'd like to make your own project id for testing purposes, you may do so then pass it in as `BRAVE_INFURA_PROJECT_ID`, or you can also hardcode it here: https://github.com/brave/brave-core/blob/master/browser/extensions/api/brave_wallet_api.cc#L141

**Comment by jonathanKingston** [comment]
@ryanml I see I was able to get it working copying the key from my production version.

I wasn't able to get it working by creating a test project at https://infura.io is there additional steps I could be missing?

Could we make some kind of test key the default perhaps on the debug build?

**Comment by ryanml** [comment]
@jonathanKingston that's another way to go, given that in the latest infura API project ids are part of the request path it isn't hard to hunt.

A project id from a test project should work though, how did you try implementing it? Are you getting a 403 with it.

I think so, let me label this issue as one of dev-experience

**Comment by jonathanKingston** [comment]
> A project id from a test project should work though, how did you try implementing it? Are you getting a 403 with it? I think we actually may have some checks proxy-side that may render a different project id not functional.

I just exported the global variable and did the exact same thing for the live ID and that worked. I was getting the same 403 and I also verified the ID was in the URL.

**Comment by bbondy** [comment]
For debug builds you can get this working by signing up for your own infura ID. Then:

`npm config edit`

Then add:
`brave_infura_project_id=id-here`
