### ISSUE TITLE
[Android] Chromium icon used for apk's with CR 80

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8023]
## Description 
 Chromium icon used for apk's with CR 80

## Steps to reproduce 

   1. Download 1.5.76 apk

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/73658650-b4d5e700-46ba-11ea-97e8-5dad5afd83ee.png)

## Expected result
Should use Brave icon for apk

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.5.76 Nightly

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by yrliou** [comment]
Appears to be arm64 only since I can't reproduce using Bravearm.apk but can reproduce using BraveMonoarm64.apk, latest nightly (1.5.80).

**Comment by yrliou** [comment]
Weird that I can't reproduce it using my local release arm64 build, nightly icon is shown normally.

**Comment by srirambv** [comment]
This issue is partially fixed. On Android 10 it still shows chromium icon for the saved apk file but when launched shows Brave icon when apk setup is launched. No issue on Android 9.0 on Samsung Tab
![cr80](https://user-images.githubusercontent.com/17010094/74434490-8ad5af00-4e88-11ea-9dff-3e2a527a8df6.gif)
