### ISSUE TITLE
Request access to the private Apple entitlement for Chromium PWAs: com.apple.developer.associated-domains.applinks.read-write

### ISSUE THREAD

**Issue by mbacchi** [brave/brave-browser#8027]
As of Chromium 80, there is a private Apple entitlement that is used for PWA support. It caused us trouble when signing Chromium 80 last week, and we added [this patch](https://github.com/brave/brave-core/pull/4472) as a workaround for the short term to remove the entitlement. The Chromium team pointed out that they [announced this](https://groups.google.com/a/chromium.org/forum/#!topic/embedder-dev/UYsV4Yy29qE) in the Chromium Embedders google group(which many of us are now members of.)

To properly add support for this, we need to contact Apple and request to be whitelisted for the `com.apple.developer.associated-domains.applinks.read-write` entitlement.

**Comment by mbacchi** [comment]
Requested access to this entitlement via an Apple Developer portal TSI (Technical Support [request](https://developer.apple.com/support/technical/)), waiting to hear back from them.

**Comment by mbacchi** [comment]
Have not heard anything from Apple support since the initial ticket acknowledgement.

**Comment by mbacchi** [comment]
Sent a follow up email to Apple Developer Technical Support to inquire about the status of this request after chatting with an Apple employee. Will comment here as soon as I hear something.

**Comment by mbacchi** [comment]
I have not heard anything officially from Apple Developer Technical Support, but my Apple contact has said that we should have access to the entitlement now if we update our provisioning profile. I will inquire from DTS to find out if this applies to all of our channel provisioning profiles.

**Comment by mbacchi** [comment]
Received this from Apple Developer Technical Support earlier in the week:

> I confirm the entitlement has been granted. 
> ...
> You’ll need to add the entitlement to your profiles and re-generate them. Then you’ll need to rebuild your app with the newly generated profile.
> ...
> Since this entitlement is for making universal links work with the Brave browser, you need several pieces to work together. Your app will need to check if it is launched by the user when clicking on a URL, if that URL is a universal link. This is done by using the SFUniversalLink API.  If it is a universal link, the app should display UI to ask the user if they want the link opened in the linked app, or in the Brave browser. 
> 
> After rebuilding your app with the profile that contains the new entitlement, here is the process I’d use to test:
> 
> 1. Set the Brave browser (that you just built) to be the default in the System Preferences > General tab.
> 2. Install the Twitter for macOS app from the Mac App Store. Sign into your Twitter account, and make sure the app is working correctly.
> 3. In notes type “http://twitter.com” and press return.
> 4. Click the resulting link in Notes.
> 5. Brave should open with some UI that you implemented asking if the user wanted to open the link in the Twitter app.

This response includes a confirmation that our entitlement has been granted, answers to my questions about whether it was granted for all of our provisioning profiles, and instructions on how to test it is in fact working after building with the new profile(s).

I will leave this open for the moment but will shortly open an issue to require using these new entitlements.

CC: @bsclifton @bridiver

**Comment by mbacchi** [comment]
Building a nightly to test this using branch https://github.com/brave/brave-core/tree/issues/8027

**Comment by mbacchi** [comment]
This build would not start even though it builds, was signed and notarized successfully. I get the error `Unsatisfied entitlement` in the console.log, and the application will not run.

After talking to @kylehickinson about how to add the entitlement capability in the Apple Developer portal to the Identifier and Provisioning Profile, and being unable to do this with my personal Apple ID, the devops@brave.com ID and also the account holder ID dev@brave.com (attempted because [this](https://developer.apple.com/developer-id/) said it was necessary to have account holder status), I opened an Apple Technical Support Incident (TSI). The support case number with Apple is 101129783426.

I will report back here when I get a response from them.

**Comment by mbacchi** [comment]
Apple support responded asking additional questions. I responded and am awaiting their reply.

**Comment by mbacchi** [comment]
I've been emailing back and forth with the Apple support representative but their recommendations seem to indicate that I should be able to add the entitlement `com.apple.developer.associated-domains.applinks.read-write` via the Identifier page of the Certificates, Identifiers & Profiles page in the developer portal. They pointed me to [this documentation](https://help.apple.com/developer-account/#/dev4cb6dfbdb) which does not help as it indicates the capability I need should be listed in the Identifier page, but this screenshot clearly shows it is not.

![capabilities](https://user-images.githubusercontent.com/6763301/87570716-45f7b380-c686-11ea-9356-7d4eb08e5d87.png)

I will continue to talk to the support rep and try to get more information about how to enable this capability for our profiles.

**Comment by mbacchi** [comment]
Still trying to get some detailed instructions from the Apple Developer Technical Support person, as they keep insisting I just add Associated Domains as in the screenshot above, then add a domain in Xcode. But that's not how I understand the SFUniversalLinks API to work.

I also reached out to my contact via DM for any suggestions or assistance he can provide, and hope to hear back from him shortly.

**Comment by mbacchi** [comment]
My contact suggested that I didn't actually open the right type of support issue, and that instead I need to open a Technical Support Incident with the Developer Technical Support group, and then the right team would be able to triage my problem. I couldn't figure out how to do that on Friday with my own Apple developer ID, so I will try it today with the Brave Organizational developer ID.

**Comment by mihaiplesa** [comment]
Chrome has the following in `embedded.provisionprofile` from the `.app` dir:

```
<key>com.apple.developer.associated-domains.applinks.read-write</key>
<true/>
```

We get to have the below which is why any of our builds crash on startup. This comes from our provisioning profiles which need to be updated. Just replacing manually didn't work.
```
<key>com.apple.developer.associated-domains</key>
<string>*</string>
```

**Comment by mihaiplesa** [comment]
Entitlement granted, provisioning profiles updated and test builds look good (on both nightly and release channels).

**Comment by mihaiplesa** [comment]
This is going out in nightly 1.21.5 which should take out the Console app error message seen below.

<img width="938" alt="Screen Shot 2021-01-15 at 7 50 16 AM" src="https://user-images.githubusercontent.com/907672/104696769-b00d1600-5706-11eb-82c7-54807e25c492.png">

**Comment by kjozwiak** [comment]
@brave/legacy_qa will basically need to update from a previous version that doesn't have https://github.com/brave/brave-core/pull/7425 and update to a version with the PR merged. On Nightly, the STR/Cases would be as follows:

* download/Launch `1.21.2` (before https://github.com/brave/brave-core/pull/7425 was merged)
* upgrade to `1.21.25` (latest at the time) and ensure you're not getting a permission/password prompt after upgrading

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 11.1 x64` using the following build:

**`Note:`** This is checking the `BETA` channel and not the `Release` channel. We'll need to recheck the following on `1.19.x` once https://github.com/brave/brave-core/pull/7691 in `1.19.x` and we get new RC builds.

```
Brave | 1.20.91 Chromium: 88.0.4324.96 (Official Build) beta (x86_64)
--- | ---
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 11.1 (Build 20C69)
```

* **`Test Case 1`** (using `Brave-Browser-Beta-universal.dmg`) - **PASSED**
* **`Test Case 2`** (using `Brave-Browser-Beta.dmg`) - **PASSED**
* **`Test Case 3`** (using `Brave-Browser-Beta-universal.pkg`) - **PASSED**
* **`Test Case 4`** (using `Brave-Browser-Beta.pkg`) - **PASSED**

Cases used:

* downloaded & installed `1.20.89 Chromium: 88.0.4324.96`
* added a few passwords into Brave/Keychain
* changed `Info.plist` to `test-beta`
* upgraded to `1.20.91 CR: 88.0.4324.96`
* once upgraded, ensured there was no password/authentication prompt once `1.20.91 CR: 88.0.4324.96` launched
* ensured that passwords were still viisble via `brave://settings/passwords`

```
kjozwiak@Kamils-MacBook-Pro-2 ~ % spctl --assess --verbose /Applications/Brave\ Browser\ Beta.app
/Applications/Brave Browser Beta.app: accepted
source=Notarized Developer ID
```

@mihaiplesa `PKG` installs do ask for a password/authentication when upgrading but I'm assuming that's expected as you need a password when installing `PKG` files. You also need a password whenever you change anything within `/Applications/Brave\ Browser\ Beta.app`. For example, changing anything within `Info.plist` needs a password.

**`Example`** | **`Example`**
---------------|----------------
<img width="1211" alt="Screen Shot 2021-01-27 at 11 50 25 AM" src="https://user-images.githubusercontent.com/2602313/106026937-63c3bd80-6098-11eb-8949-36c881acf5f9.png"> | <img width="891" alt="Screen Shot 2021-01-27 at 11 51 14 AM" src="https://user-images.githubusercontent.com/2602313/106026968-6d4d2580-6098-11eb-8983-7e23e222950a.png">

**Comment by mihaiplesa** [comment]
@kjozwiak haven't tested PKG but your report looks good.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 11.1 x64` using the following build:

```
Brave | 1.19.88 Chromium: 88.0.4324.96 (Official Build) (x86_64)
--- | ---
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 11.1 (Build 20C69)
```

* **`Test Case 1`** (using `Brave-Browser-universal.dmg`) - **PASSED**
* **`Test Case 2`** (using `Brave-Browser.dmg`) - **PASSED**
* **`Test Case 3`** (using `Brave-Browser-universal.pkg`) - **PASSED**
* **`Test Case 4`** (using `Brave-Browser.pkg`) - **PASSED**

Cases used:

* downloaded & installed `1.19.86 CR: 88.0.4324.96`
* added a few passwords into Brave/Keychain
* changed `Info.plist` to `test`
* upgraded to ` 1.19.88 CR: 88.0.4324.96`
* ensured there wasn't any `keychain` password/authentications prompts after upgrading to ` 1.19.88 CR: 88.0.4324.96`
* ensured that passwords were still visible via `brave://settings/passwords`
* ensured that you can auto-fill saved passwords without any issues

```
kjozwiak@Kamils-MacBook-Pro-2 ~ % spctl --assess --verbose /Applications/Brave\ Browser.app/
/Applications/Brave Browser.app: accepted
source=Notarized Developer ID
```
