### ISSUE TITLE
Got update error after uploading ntp component crx

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#8037]
After uploading ntp component crx to go updater, browser sometimes gets `Update error` status for some time(maybe 10 ~ 20 mins) in `brave://components` page. Then, properly updated to newer version.

and sometimes works well w/o error.

I think state should be `Component not updated` instead of `Update error` if it's related with cache flush.

cc: @jumde @bsclifton

**Comment by petemill** [comment]
As discussed this can be fixed with uploaded to s3 before updating the dynamodb table
