### ISSUE TITLE
Add a flag to switch to use go-update production or development server

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#8039]
## Test plan
See https://github.com/brave/brave-core/pull/4754

## Description
`kBraveUpdatesExtensionsEndpoint` defines the go-update server currently being used. We should add a runtime flag for setting the go-update server to be used instead of hard coding the endpoint.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.70 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified the test plan from https://github.com/brave/brave-core/pull/4754 using Fiddler

without `--use-dev-goupdater-url` flag:
<img width="574" alt="Screen Shot 2020-03-23 at 4 42 47 PM" src="https://user-images.githubusercontent.com/28145373/77363242-c174d400-6d28-11ea-9089-ab390c130a15.png">

with `--use-dev-goupdater-url` flag:
<img width="618" alt="Screen Shot 2020-03-23 at 4 55 59 PM" src="https://user-images.githubusercontent.com/28145373/77363239-bfab1080-6d28-11ea-91ee-bb70382da843.png">
