### ISSUE TITLE
One-time tips are not displayed under tips panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8041]
## Description 

One-time tips are not displayed under tips panel

## Steps to Reproduce

   1. Clean profile 1.3.109 launch using `brave.exe --rewards=staging=true,reconcile-interval=5`
   2. Enable rewards and claim UGP grants
   2. Open a verified publisher
   3. Send a one-time tip
   4. The one-time tip is not displayed under tips panel
   5. Wallet balance is reduced by 1 BAT, the one-time tip is shown in summary and BR panel
   6. Restart or reload brave://rewards page did not fix the issue

**Note**: the temporary workaround is to set a monthly tip first, after setting monthly tip both one-time and monthly tips displayed in their respective panels. But setting a monthly tip isn't possible in single attempt due to #8019 

## Actual result:

One-time tips are not displayed under tips panel

![Tips display issue](https://user-images.githubusercontent.com/38657976/73723424-03cd5c00-474f-11ea-9d93-5159a18ceb10.gif)

## Expected result:
One-time tips should be displayed under tips panel

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.3.109 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA 

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @masparrow @rebron

**Comment by btlechowski** [comment]
Reproduced on Windows 7 x64

Brave | 1.3.110 Chromium: 80.0.3987.78 (Official Build) (64-bit)
-- | --
Revision | cb5aa81cb0a3a2c674b93bc7ffb34a86cd3b4802-refs/branch-heads/3987@{#752}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Used test plan from the description.
Note: Reload of `brave://rewards` does not fix the issue
Note: Browser restart does not fix the issue

![image](https://user-images.githubusercontent.com/34715963/73797505-876b6500-47b0-11ea-869e-bff308534dcd.png)

**Comment by GeetaSarvadnya** [comment]
The issue is working fine hence closing the issue.

Brave | 1.4.84 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.1006)
