### ISSUE TITLE
Whole browser goes blurry

### ISSUE THREAD

**Issue by TheIgnorantDev** [brave/brave-browser#8042]
## Description 

The whole brower looks like i took acid.

## Steps to Reproduce

   1. http://prntscr.com/qx8kz2
   2. http://prntscr.com/qx8m0u
   3. 

## Expected result:
Normal looks

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
Hey @TheIgnorantDev certainly very strange. Could possibly be a graphics driver issue. In the Brave Settings, does disabling `Hardware Acceleration` help?

**Comment by TheIgnorantDev** [comment]
Graphics are up to date. GTX 1080TI updated through GEFORCE Experience. Turned off hardware acceleration and it seems to have worked some. Its not as often anymore but it does still happen. Also just to be clear I am on the latest version
https://prntscr.com/qxpth1

**Comment by bsclifton** [comment]
@ryanbr good call on turning off HW accelleration

@TheIgnorantDev are you still having this problem?

**Comment by rebron** [comment]
@TheIgnorantDev Assuming you're on Windows 10 x64 are you updated to the latest drivers via: https://www.nvidia.com/Download/driverResults.aspx/158759/en-us

Also, were you able to set the flag above brave://flags/#enable-oop-rasterization
