### ISSUE TITLE
previously used wallet gets second UGP grant claim notification

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8043]
## Description 

Found by @GeetaSarvadnya 

background: VG are specific to the profile being used (per https://github.com/brave/brave-browser/issues/6937).

What it looks like is happening is if you restore a wallet that had a UGP in a previous profile, you get prompted to claim another UGP grant on a clean profile but you don't actually get the BAT from it. Seems like we shouldn't be prompted for this second UGP grant.

## Steps to Reproduce

   1. Have a self-funded wallet on staging from 1.2.x or earlier (let me know if you need information on how to do this), make sure wallet has never claimed any UGP grants. 
   2. Clean profile on 1.3.x, launch with staging parameters
   3. Restore wallet and then claim UGP grant. (starting wallet balance was 5 BAT, grant was 17.5 BAT, wallet correctly reflects 22.5 BAT as balance)
   4. Tip, etc. Wallet balance decrements as expected.
   5. Close and delete this profile
   6. Clean profile 1.3.x, launch with staging parameters
   7. Enable Rewards, restore wallet.
   8. Only self-funded portion of wallet is restored (as expected).
   9. See UGP claim banner, refresh page.
   10. UGP claim banner is still there, claim UGP grant.

## Actual result:

 successful claim, but no additional BAT is added to wallet

## Expected result:
second UGP banner should not be there, the wallet had already successfully claimed a UGP grant previously

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.3.109

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

staging paymentId: 8c2de25d-6111-4abd-8620-b62cc23aab35

If you need the profile used for testing this let @GeetaSarvadnya or @LaurenWags know

cc @brave/legacy_qa @NejcZdovc @mandar-brave

**Comment by NejcZdovc** [comment]
can this be reproduced with only VG @LaurenWags

**Comment by LaurenWags** [comment]
yes since before VG the remaining BAT from the UGP grant was not lost upon using a new profile (it would have been restored in step 7 above).

**Comment by NejcZdovc** [comment]
@LaurenWags still a problem?
