### ISSUE TITLE
C80 - unable to open PDF

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8044]
## Description 

Originally reported by @AlexeyBarabash 

Unable to open PDFs on chromium 80 versions of Brave.

## Steps to Reproduce

   1. Have C80 version installed
   2. Try to open a PDF such as: https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf

## Actual result:

PDF does not display

## Expected result:
PDF should display

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.5.81 Chromium: 80.0.3987.78 (Official Build) nightly (64-bit)
-- | --
Revision | cb5aa81cb0a3a2c674b93bc7ffb34a86cd3b4802-refs/branch-heads/3987@{#752}
OS | macOS Version 10.14.6 (Build 18G103)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the dev channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @mkarolin @rebron @brave/legacy_qa

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.111 Chromium: 80.0.3987.85 (Official Build) (64-bit)
-- | --
Revision | 583b05dfa4ffc657f0f7c5cc13f53aa17c9a5bcf-refs/branch-heads/3987@{#791}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4500. Also verified cases from manual testrun.

![image](https://user-images.githubusercontent.com/34715963/73875366-7aed1800-4855-11ea-9b3c-e7878f5265f9.png)
