### ISSUE TITLE
Ads history is limited to 99 entries - follow up to 5863

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8046]
## Description 
Originally logged with #5863 

Per discussion, logging this follow up issue so #5863 can be retested with 1.4.x milestone where blocking issue #7743 is fixed by #6757 

## Steps to Reproduce
follow steps in #5863 (see @btlechowski for file if needed)

## Actual result:

Only up to 99 ads viewed during 7 days are shown in the history

## Expected result:
All ads viewed during 7 days should be shown in the history

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.3.x

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @brave/legacy_qa

**Comment by LaurenWags** [comment]
Closing this issue as its blocking issue #7743 is fixed by #6757 in the 1.4.x milestone

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.4.85 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Talked to @tmancey about possible test cases. Max entries in ads shown history is 560.

- Used 560 entries in ads history and verified all 560 entries are shown in ads history
[client.zip](https://github.com/brave/brave-browser/files/4195009/client.zip)

![image](https://user-images.githubusercontent.com/34715963/74372326-bc903c80-4dda-11ea-8ad7-29c287df8754.png)
![image](https://user-images.githubusercontent.com/34715963/74372485-ffeaab00-4dda-11ea-9ac2-7718ac3afd7a.png)

- [FAIL] Used 3000 entries in ads history and verified only 560 are shown. 
All 3000 entries are shown.
Logged https://github.com/brave/brave-browser/issues/8213

- ads with date in the future
[client.zip](https://github.com/brave/brave-browser/files/4195005/client.zip)
Verified ads with date in the future are not shown
Ads 99 and 100 are not shown
![image](https://user-images.githubusercontent.com/34715963/74376702-e9485200-4de2-11ea-80e3-fc12f45996a6.png)

Steps:
   1. Clean profile
   2. Enable rewards
   3. View an ad
   4. Close Brave
   5. copy `client.json` to `[PROFILE]\Default\ads_service\` Note: You need to unpack client.zip
   6. Run Brave
   7. Open `brave://rewards`
   8. Reload the page few times to shown the generated ads history
