### ISSUE TITLE
`x-client-data` header should not be sent in requests

### ISSUE THREAD

**Issue by immanuelfodor** [brave/brave-browser#8049]
## Updated Issue Description (notes from @bsclifton)
Visiting sites like youtube.com will show a `x-client-data` header. This wasn't in Brave for a long time because we didn't use the variations server. This showed itself recently since we did recently create a Brave-specific variations server. This header should be disabled.

## Original Issue Description

There is an ongoing conversation about the Chrome/Chromium x-client-data header here https://github.com/bromite/bromite/issues/480 and here https://github.com/w3ctag/design-reviews/issues/467#issuecomment-581944600

Does Brave Desktop/Android send a unique client ID (x-client-data) to Google properties (google.com etc)?
This is considered a "backdoor" for Google (and google only!) to track users even without cookies.

If Brave sends this header - can it be removed?    
If Brave doesn't send this header - maybe worth mentioning in some privacy features list?

**Comment by immanuelfodor** [comment]
Also submitted this issue to https://github.com/brave/browser-android-tabs/issues/2505 but if the current repo is for the Android browser as well, feel free to close that one and keep only this one open.

**Comment by b00sher** [comment]
> If Brave sends this header - can it be removed?

Have you checked? If no, could you? Can't get hands on it rn.

**Comment by MitchellNZ** [comment]
Just did a quick test on Windows 10.
Can't see Brave sending this request header (like I can when I test on Chrome).
Tested by accessing youtube.com (with and without Brave shields - same result).

**Comment by immanuelfodor** [comment]
> Have you checked? If no, could you? Can't get hands on it rn.

I was using my phone when submitted this (evening), and I'm still on my phone (morning), I'd gladly check it otherwise 😅 If somebody has a laptop, please check it, or I'll report back later in the day when I'm with a desktop.

**Comment by immanuelfodor** [comment]
> Just did a quick test on Windows 10.
> Can't see Brave sending this request header (like I can when I test on Chrome).
> Tested by accessing youtube.com (with and without Brave shields - same result).

Great news for a start! I have a Linux OS, will see that build, too.

**Comment by Wizard13** [comment]
I find it strange that Chromium doesn't send this header, just Chrome.

**Comment by jumde** [comment]
@immanuelfodor @Wizard13 - This is related to the variations service. Since, variations are disabled in Brave, you should not be seeing the `x-client-data` header when using Google Services. I verified that this header is not sent if requests to google properties with Brave. If you're seeing this in the requests please let me know.

**Comment by immanuelfodor** [comment]
Sorry for the delay, I managed to check it finally, and it's indeed not there in Brave Desktop.

I suppose it's the same with the Android app as well if they use the same core (and I don't know how to check it there).

**Comment by Th3l5D** [comment]
Hello,

Sorry to reopen the issue, but I recently saw that Brave Desktop does use this header, at least on youtube.com

Do you know why this header is know part of Brave, and if there is any way ton disable it?

**Comment by bsclifton** [comment]
I was able to verify this header is sent via requests to youtube.com on Nightly (`1.22.6`) and Release (`1.19.92`). For example, I'm seeing:
![image](https://user-images.githubusercontent.com/4733304/107189154-b7d67800-699d-11eb-91d3-a6f3a197af95.png)

I made sure Google logins for extensions was off (it's off by default) and also I made sure to disable Google like buttons / logins for sites. I wonder if our variations server (not related to Google) is using this and sending it?

@moritzhaller @iefremov is this related to variations server implementation we have? (is our implementation re-using the Chromium code?)

cc: @jumde

**Comment by iefremov** [comment]
@bsclifton Yeah I think this our variations service. We need to explicitly disable this header

**Comment by iefremov** [comment]
Follow-up to add tests https://github.com/brave/brave-browser/issues/14053

**Comment by iefremov** [comment]
@bsclifton should we uplift?

**Comment by bsclifton** [comment]
@iefremov yes - I'll create the uplifts now. We can uplift to 1.20 (release 2)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.20.104 Chromium: 88.0.4324.152 (Official Build) (64-bit)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | Windows 10 OS Version 2004 (Build 19041.804)

```
- Verified the STR from the description

**1.20.103** | **1.20.104**
------------- | -------------
![image](https://user-images.githubusercontent.com/38657976/108198337-8437e280-7141-11eb-8fbe-d53d26c00de5.png) | ![image](https://user-images.githubusercontent.com/38657976/108198418-9ade3980-7141-11eb-8f4a-5ad9137e37f8.png)
