### ISSUE TITLE
"Show Sponsored Images" toggle under "Dashboard Settings" should look the same as others

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#8057]
## Description 

When toggling `Show Sponsored Images` under the NTP, you'll notice that it's missing the actual switch in certain cases and will only display an orange dot which might confuse some users. In some cases, the orange dot is visible when the feature has been disabled as per the example below.

## Steps to Reproduce

   1. launch brave and ensure that NTP SI has been enabled
   2. go into the `Dashboard Settings`
   3. disable `Show Sponsored Images`
   4. disable `Show Background Images`

You'll notice that the orange dot is still visible.

## Actual result:

![dashboardToggles](https://user-images.githubusercontent.com/2602313/73788431-0473eb80-476b-11ea-8f88-33909f9e437c.gif)

## Expected result:

`Show Sponsored Images` should look the same as the other toggles.

## Reproduces how often: 

100% reproducible when using the STR mentioned above. 

## Brave version (brave://version info)

Brave | 1.3.108 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.15.3 (Build 19D76)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A` (feature not released)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @rebron @petemill @brave/legacy_qa @mandar-brave

**Comment by karenkliu** [comment]
It should be styled as a disabled toggle:

![Group 11](https://user-images.githubusercontent.com/2388823/73895660-2c2f8600-4835-11ea-859c-1ea448e95d9d.jpg)

https://share.goabstract.com/6369ced8-1a0b-4fc9-a830-64cf9806dbba?mode=design&sha=f568aec916b79bb879ddac6b2bf34d58e2b07b5d

**Comment by w0ts0n** [comment]
Just wanted to note. As of today, I upgraded Brave to Version 1.3.113 Chromium: 80.0.3987.87 (Official Build) (64-bit) on MacOS 10.15.1 and I'm seeing some odd behaviour with floating sliders. 

<img width="373" alt="Screenshot 2020-02-07 at 4 30 15 PM" src="https://user-images.githubusercontent.com/2603015/74067851-28803880-49c8-11ea-8e51-d789c5b48f08.png">
<img width="554" alt="Screenshot 2020-02-07 at 4 31 49 PM" src="https://user-images.githubusercontent.com/2603015/74067857-29b16580-49c8-11ea-8b1f-55801f693ae4.png">

**Comment by srirambv** [comment]
Issue still reproducible on

Brave | 1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit)
-- | --
Revision | dc00a510e4c2ae25c4d084cc3d946fc782249224-refs/branch-heads/3987@{#917}
OS | Linux

**Comment by rebron** [comment]
Closing as stale. No longer an issue updated design.
<img width="730" alt="Screen Shot 2022-07-05 at 1 44 49 PM" src="https://user-images.githubusercontent.com/5951041/177413272-fbef5b84-891c-4267-9b33-672e5f1df386.png">
<img width="740" alt="Screen Shot 2022-07-05 at 1 45 00 PM" src="https://user-images.githubusercontent.com/5951041/177413277-faaf2084-0d91-431e-97ee-44659b2d18c7.png">
