### ISSUE TITLE
Change wayback machine endpoint to brave-api.archive.org

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#8063]
Change wayback query url from `https://archive.org/wayback/available?url="` to `https://brave-api.archive.org/wayback/available?url="`

Verification step with new endpoint.
1. Go to https://brave.com/bo
2. Check wayback infobar is shown
3. Click the check button and throbber animation is started
4. Check an archived version is loaded

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.4.89 Chromium: 80.0.3987.106 (Official Build) beta (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/4507
![image](https://user-images.githubusercontent.com/38657976/74657903-35b2d980-51b7-11ea-93ca-1e3f0609526e.png)
