### ISSUE TITLE
Follow up #7948 Moving of bookmark is not propagated to another device

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#8065]
Follow up #7948. The issue still reproduces.

Important: Reproduces on 1.3.110, 1.4.78, 1.5.82. All versions are Chromium 80.

## Steps to Reproduce

   1. Clean profile DeviceA and DeviceB
   2. DeviceA: open `interia.pl`
   3. DeviceA: open `youtube.com`
   4. DeviceA: create sync chain and copy code words
   5. DeviceB: enter code words
   6. Wait for sync
   7. DeviceA: bookmark `interia.pl`
   8. DeviceA: bookmark `youtube.com`
   9. Wait till bookmarks are synced to DeviceB
   10. DeviceA:Move `interia.pl` after `youtube.com` bookmark 
   11. Wait till the change is propagated to DeviceB

DeviceA: Ubuntu 18.04LTS
DeviceB: Windows 7x64

## Actual result:

The moving of bookmark is not propagate to another device
DeviceA
![image](https://user-images.githubusercontent.com/34715963/73796574-dc59ac00-47ad-11ea-8645-bb426bbfe051.png)

DeviceB
![image](https://user-images.githubusercontent.com/34715963/73796564-d1068080-47ad-11ea-853b-1549e70e4cdc.png)

## Expected result:
The moving of the bookmark is always propagated

## Reproduces how often: 

100% repro rate with above STR

## Brave version (brave://version info)

Brave | 1.3.110 Chromium: 80.0.3987.78 (Official Build) (64-bit)
-- | --
Revision | cb5aa81cb0a3a2c674b93bc7ffb34a86cd3b4802-refs/branch-heads/3987@{#752}
OS | Ubuntu 18.04 LTS

Brave | 1.3.110 Chromium: 80.0.3987.78 (Official Build) (64-bit)
-- | --
Revision | cb5aa81cb0a3a2c674b93bc7ffb34a86cd3b4802-refs/branch-heads/3987@{#752}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.4.78 Chromium: 80.0.3987.78 (Official Build) dev (64-bit)
-- | --
Revision | cb5aa81cb0a3a2c674b93bc7ffb34a86cd3b4802-refs/branch-heads/3987@{#752}
OS | Ubuntu 18.04 LTS

Brave | 1.4.78 Chromium: 80.0.3987.78 (Official Build) dev (64-bit)
-- | --
Revision | cb5aa81cb0a3a2c674b93bc7ffb34a86cd3b4802-refs/branch-heads/3987@{#752}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.5.82 Chromium: 80.0.3987.78 (Official Build) nightly (64-bit)
-- | --
Revision | cb5aa81cb0a3a2c674b93bc7ffb34a86cd3b4802-refs/branch-heads/3987@{#752}
OS | Ubuntu 18.04 LTS

Brave | 1.5.82 Chromium: 80.0.3987.78 (Official Build) nightly (64-bit)
-- | --
Revision | cb5aa81cb0a3a2c674b93bc7ffb34a86cd3b4802-refs/branch-heads/3987@{#752}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

cc @brave/legacy_qa @jsecretan @AlexeyBarabash @darkdh @rebron

**Comment by rebron** [comment]
I was able to reproduce on 1.3.110 Windows 10/macOS 10.15.3
I was also able to reproduce on 1.5.79 Windows 10/macOS 10.15.3 but here first bookmark move propagated, (on macOS first device) second move of same bookmark and a delete of a bookmark wasn't reflected in second device (Win10).

**Comment by btlechowski** [comment]
According to https://github.com/brave/brave-browser/issues/7948#issuecomment-580046599, this issue was fixed in 1.5.69, but know I can reproduce it on 1.5.69. Maybe it is a server side issue?

**Comment by GeetaSarvadnya** [comment]
Couldn't reproduce the issue in Window 10 x64 - `1.3.110`

Brave | 1.3.110 Chromium: 80.0.3987.78 (Official Build) (64-bit)
-- | --
Revision | cb5aa81cb0a3a2c674b93bc7ffb34a86cd3b4802-refs/branch-heads/3987@{#752}
OS | Windows 10 OS Version 1803 (Build 17134.1006)


- Verified creating folder in both Device A and Device B - folders sync works fine
- Verified adding bookmarks into folders in both Device A and Device B - BM's sync inside folders works fne
- Verified deleting folders from Device A and Device B - sync works fine deleted folders removed from both devices.

**Comment by darkdh** [comment]
It was the issue of SQS events couldn't get forwarded. 
And now it is fixed so feel free to close the issue if verification passed.

**Comment by rebron** [comment]
https://github.com/brave/brave-browser/issues/8065#issuecomment-582186493 retried after SQS fix and it working properly on 1.3.110 Windows 10 x64 and macOS, following Geeta's steps.

@btlechowski close out if it's working for you now.

**Comment by btlechowski** [comment]
Not reproducible anymore

Verification passed on

Brave | 1.3.110 Chromium: 80.0.3987.78 (Official Build) (64-bit)
-- | --
Revision | cb5aa81cb0a3a2c674b93bc7ffb34a86cd3b4802-refs/branch-heads/3987@{#752}
OS | Ubuntu 18.04 LTS

Verification passed on

Brave | 1.3.110 Chromium: 80.0.3987.78 (Official Build) (64-bit)
-- | --
Revision | cb5aa81cb0a3a2c674b93bc7ffb34a86cd3b4802-refs/branch-heads/3987@{#752}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

**Comment by btlechowski** [comment]
The test case is the same as for #7948 so I set this as `QA/No`
