### ISSUE TITLE
Cosmetic filtering should be enabled by default

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#8068]
Currently merged implementation of cosmetic filtering is off by default, new 1p/3p heuristics should allow it to be enabled by default.

**Comment by bsclifton** [comment]
@antonok-edm what is a quick way to tell if cosmetic filtering is enabled? Is there a specific page you can mention (maybe edit the original post above to provide the example as a test plan)

**Comment by szaimen** [comment]
I am wondering, too...
Also it seem to doesn't work on some sites. Or is there a learning curve?

**Comment by bsclifton** [comment]
cc: @antonok-edm @ryanbr @snyderp 

@szaimen I believe the rules are downloaded as part of the regular adblock definition download and then they should be applied.  As this was just merged, it's only enabled on Nightly

Which version of Brave are you using? If you're on Developer, it may also be available, but you'd need to go to brave://flags/#brave-adblock-cosmetic-filtering to enable it

**Comment by kjozwiak** [comment]
@bsclifton @antonok-edm is there a test plan that QA can run through to make sure this is working as expected?

**Comment by bsclifton** [comment]
@kjozwiak yup! Added 😄

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.86 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-browser/issues/5381 without changing the brave://flags/#brave-adblock-cosmetic-filtering flag
