### ISSUE TITLE
Follow up of #7840 - After excluding a site from A-C table `Show All` link is not shown in ac table

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8071]
## Description 

After excluding a site from A-C table `Show All` link is not shown in ac table

## Steps to Reproduce

   1. Clean profile 1.3.110
   2. Enable rewards
   3. Add a site to a-c table
   4. Exclude the added site by clicking on Trash icon
   5. After excluding a site from A-C table Show All link is not shown

## Actual result:

After excluding a site from A-C table Show All link is not shown in ac table
![Show All link missing _1 3 110](https://user-images.githubusercontent.com/38657976/73836547-86c8e200-4835-11ea-8799-dbe4adfa6f93.gif)

## Expected result:
After excluding a site from A-C table Show All link should be shown in a-c table

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.3.110 Chromium: 80.0.3987.78 (Official Build) (64-bit)
-- | --
Revision | cb5aa81cb0a3a2c674b93bc7ffb34a86cd3b4802-refs/branch-heads/3987@{#752}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron @masparrow

**Comment by GeetaSarvadnya** [comment]
The issue is reproducible in Windows 8.1 (VM) - `1.3.110`

**Comment by rebron** [comment]
I was able to reproduce using steps in Windows 10 - 1.3.111.
I was NOT able to reproduce using macOS 1.3.111.

**Comment by rebron** [comment]
Clearing 1.3.x milestone.

**Comment by GeetaSarvadnya** [comment]
The issue is working fine in 1.4.x beta channel hence closing the issue.

Brave | 1.4.84 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.1006)
