### ISSUE TITLE
[Desktop] Compiling brave rewards and brave sync when disabled in component extension whitelist

### ISSUE THREAD

**Issue by akshay24495** [brave/brave-browser#8072]
## Description 

When brave rewards and brave sync are disabled in the code, it is included in component_extension_whitelist/whitelist.cc. Need to be excluded by adding checks.   

## Steps to Reproduce

N/A

## Actual result:

N/A

## Expected result:
N/A

## Reproduces how often: 

N/A

## Brave version (brave://version info)

Current version: 1.6.2

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by akshay24495** [comment]
@bridiver I have doubt in brave_main_delegate.cc. How does chrome_content_browser_client_ is initialized with BraveContentBrowserClient where as the variable in chrome_main_delegate.cc is of type ChromeContentBrowserClient.

**Comment by bridiver** [comment]
@akshay24495 we overrride ChromeMainDelegate::CreateContentBrowserClient to return BraveContentBrowserClient which is a subclass of ChromeContentBrowserClient
