### ISSUE TITLE
Follow up of #7635 -Reserved BAT text isn't displayed in Rewards summary section

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8073]
## Description 

Reserved BAT text isn't displayed in Rewards summary section

## Steps to Reproduce

   1. Clean profile staging env
   2. Claim UGP grants
   3. Send a one-time tip to an unverified pub https://google.com
   4. Open BR panel for google.com, reserved BAT text is displayed in panel summary
   5. In brave://rewards settings page, reserved BAT text isn't displayed in the rewards summary section
    

## Actual result:

![Reserved BAT text display issue in summary](https://user-images.githubusercontent.com/38657976/73838618-16708f80-483a-11ea-892e-371ba3e72721.gif)

`1.3.110` and Brave beta 1.3.109 (all beta versions of 1.3.x)
![image](https://user-images.githubusercontent.com/38657976/73838229-38b5dd80-4839-11ea-8305-cf9421f4ef69.png)

Dev - `1.4.73`
![image](https://user-images.githubusercontent.com/38657976/73837999-af9ea680-4838-11ea-8ff2-51d9d0c0aaf1.png)

Nightly- `1.5.77`
![image](https://user-images.githubusercontent.com/38657976/73838313-7155b700-4839-11ea-9f8c-c4132ae37514.png)

## Expected result:
Reserved BAT text should be displayed in Rewards summary section

## Reproduces how often: 

Always
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron @masparrow

**Comment by GeetaSarvadnya** [comment]
The issue is reproducible in Windows 8.1 (VM) - `1.3.110`

**Comment by rebron** [comment]
Clearing this from 1.3.x milestone. Can address/re-triage post 1.3.x

**Comment by GeetaSarvadnya** [comment]
The issue is working fine in 1.4.x beta channel hence closing the issue 

Brave | 1.4.84 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.1006)
