### ISSUE TITLE
Desktop specific: Changes in non KYC Uphold user wallet state

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#8075]
Issue: due to new regulations coming from Uphold - enforcement coming soon- specific to any withdrawals now need IDV or ID verification. This will require that any non ID checked (unverified) accounts used for tipping or contributions cannot tip or contribute anymore.

Fixes:
- Remove support for such a state completely (numbers suggest its limited)
- Show zero balance for such user wallets (they cannot be used for contributions)
- Such wallets need to KYC/ID check to claim funds or contribute

This is now going to be the standard state support on BR going forward; User funds with ID checked wallet or anon wallets with Brave funds.

cc @NejcZdovc @jsecretan @evq

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.82 Chromium: 80.0.3987.162 (Official Build) dev (64-bit)
-- | --
Revision | f2c5dd6138153bb0658091205bd1a1717f16081a-refs/branch-heads/3987@{#1034}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4667
* Also confirmed that KYC'd accounts show balance in the browser and can tip KYC'd publishers without any issues.

Clean profile test:
1. Installed 1.7.82, enabled rewards
2. Connected same acct from upgrade test (has a balance of 4 BAT on uphold)
--> Confirmed balance displays 0 on brave://rewards and panel even though 4 BAT balance is available on Uphold
--> Confirmed I do not see `https://api-sandbox.uphold.com/v0/me/cards/"cardID"` in terminal.
--> Confirmed unable to tip same publisher I could with 1.5.115.

Upgrade test:
1. Installed 1.5.115, enabled rewards
2. Connected a non-KYC'd Uphold act
3. Added BAT to Brave Browser card of non-KYC'd Uphold acct
4. Confirmed balance updated in browser.
5. Tipped 1 BAT to verified publisher (3zsistemi.si). Tip is deducted from balance and displays on brave://rewards and in panel summaries.
6. Confirmed I do see `https://api-sandbox.uphold.com/v0/me/cards/"cardID"` in terminal.
7. Upgraded to 1.7.82
--> Confirmed balance displays 0 on brave://rewards and panel even though 4 BAT balance is available on Uphold
--> Confirmed I do not see `https://api-sandbox.uphold.com/v0/me/cards/"cardID"` in terminal.
--> Confirmed unable to tip same publisher I could with 1.5.115.

<img width="1239" alt="Screen Shot 2020-04-02 at 10 52 48 AM" src="https://user-images.githubusercontent.com/28145373/78268380-1e654c80-74d6-11ea-9da9-07dc2696ffb1.png">
<img width="403" alt="Screen Shot 2020-04-02 at 10 52 58 AM" src="https://user-images.githubusercontent.com/28145373/78268387-21603d00-74d6-11ea-9239-bae07cab3dac.png">
<img width="1238" alt="Screen Shot 2020-04-02 at 10 53 08 AM" src="https://user-images.githubusercontent.com/28145373/78268358-16a5a800-74d6-11ea-9659-54cf83a8f03a.png">
<img width="1216" alt="Screen Shot 2020-04-02 at 10 55 17 AM" src="https://user-images.githubusercontent.com/28145373/78268411-2624f100-74d6-11ea-8716-ab42611c8ea2.png">
