### ISSUE TITLE
[Android] Crash when visiting Brave license or dev options

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#8078]
## Description 

Crash when visiting Brave license or developer options on Android.

## Steps to reproduce 

   1. Install Brave
   2. Visit Settings -> About Brave -> Legal Info -> Brave License

Also occurs when visiting Developer options menu item

## Actual result 

Browser crashes

## Expected result

No crash and requested screen displays

## Issue reproduces how often 

Always

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version

Master

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.6.24 nightly x64 build
- Verified no browser crash when selecting Brave License or Developer options
-------
Verification passed on Samsung Tab A with Android 9 running 1.6.24 nightly x64 build
- Verified no browser crash when selecting Brave License or Developer options
