### ISSUE TITLE
Appears broken translate button

### ISSUE THREAD

**Issue by congard** [brave/brave-browser#8082]
## Description 
[Edited Steps to Reproduce by rebron for clarification]
When you open a site in a foreign language, a translation button appears, which when clicked does not respond.

## Steps to Reproduce

   1. Open site in a foreign language e.g. https://www.spiegel.de/ or https://www.asahi.com/
   2. Install Google translate extension
   3. Notice that icon in url bar still appears and no longer does anything. 
   4. Icon should be hidden after Google translate extension is installed.

## Actual result:
![Screenshot_20200205_234641](https://user-images.githubusercontent.com/35779485/73886253-e5ac4c80-4871-11ea-9e5d-148e45a4c5bc.png)

After clicked:
![Screenshot_20200205_234659](https://user-images.githubusercontent.com/35779485/73886255-ea710080-4871-11ea-8d71-4cfff75a86b5.png)

## Expected result:
The absence of this button or it's correct behaviour (page translation)

## Reproduces how often: 
Always.

## Brave version (brave://version info)
Brave: `1.6.2 Chromium: 80.0.3987.85`
Version: `583b05dfa4ffc657f0f7c5cc13f53aa17c9a5bcf-refs/branch-heads/3987@{#791}`
OS: Linux

## Version/Channel Information:
This can be reproduced on Brave Nightly.

## Other Additional Information:

- Q: Does the issue resolve itself when disabling Brave Shields? A: No.
- Q: Does the issue resolve itself when disabling Brave Rewards? A: No.
- Q: Is the issue reproducible on the latest version of Chrome? A: Yes.

**Comment by onmyouji** [comment]
Also happens on 1.3.113

**Comment by siznax** [comment]
Also happening on 

• Version 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit) 
• Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

example: https://github.com/2019ncovmemory/nCovMemory

**Comment by siznax** [comment]
When I try the URL above with `beta`, I am offered the G translate extension, which I installed, and then pressed `TRANSLATE THIS PAGE` on the G translate extension (not the omnibox). This causes my CPU to stress...

<img width="728" alt="Screen Shot 2020-02-25 at 2 19 41 PM" src="https://user-images.githubusercontent.com/44357/75292951-0e24c800-57da-11ea-98ab-b69db5da7615.png">

This does NOT happen with `stable`.

**Comment by rebron** [comment]
cc: @yrliou

**Comment by rebron** [comment]
@simonhong Was this added with Chromium 80? We hid this icon previously after a user installed Google Translate.

**Comment by rebron** [comment]
@kjozwiak is 1.5 the right milestone? Just 1.7.x. I think.

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` until https://github.com/brave/brave-browser/issues/8082#issuecomment-598996303 is confirmed.

**Comment by kjozwiak** [comment]
@rebron @LaurenWags it's in the wrong milestone. It was only uplifted into `1.7.x` as per https://github.com/brave/brave-core/pull/4929. I must have moved it into this milestone accidentally as everything was going into `1.5.x` including Android uplifts.

Thanks for the catch @rebron @LaurenWags 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.7.70 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Ubuntu 18.04 LTS

Verified test plan from the description.
Verified the icon is hidden after Google Translate Extension is hidden.
Verified Google Translate Extension works.

![image](https://user-images.githubusercontent.com/34715963/77382662-33790780-6d81-11ea-8fa6-381b59d414b0.png)
