### ISSUE TITLE
`Toggle distilled page contents` is really long in Bulgarian

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#8083]
Looks like translation of `Toggle distilled page contents` is really long in Bulgarian. It uses 6 distinct words. Google translate uses 4.

## Steps to Reproduce

   1. Open Brave in Bulgarian
   2. Open Hamburger Menu

## Actual result:

`Toggle distilled page contents` is really long compared to google translate
Hamburger menu is really stretched
![image](https://user-images.githubusercontent.com/34715963/73800238-6444b380-47b8-11ea-8c2e-742472365ad7.png)

## Expected result:
Closer to google translate
![image](https://user-images.githubusercontent.com/34715963/73892798-1f805180-4878-11ea-8571-44971bf9292d.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.3.111 Chromium: 80.0.3987.85 (Official Build) (64-bit)
-- | --
Revision | 583b05dfa4ffc657f0f7c5cc13f53aa17c9a5bcf-refs/branch-heads/3987@{#791}
OS | Ubuntu 18.04 LTS

Brave | 1.5.69 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Ubuntu 18.04 LTS

cc @mkarolin @rebron @bsclifton

**Comment by mkarolin** [comment]
The translation comes from Chromium. We can change, of course.

![image](https://user-images.githubusercontent.com/41635752/73902666-8562de00-4864-11ea-99d9-4c694295c400.png)

**Comment by rebron** [comment]
We should go shorter with this string. That looks bad.

**Comment by bsclifton** [comment]
I believe we're going to replace this with Speedreader. @rebron did you want to create an overall issue for enabling speedreader + disabling page distill?

**Comment by rebron** [comment]
@btlechowski Can you take a look at this again for 1.8.x later this week? `Toggle distilled page contents` is now `Toggle reader mode` in Windows and just `Reader mode` on macOS starting with chromium 81.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.8.82 Chromium: 81.0.4044.113 (Official Build) dev (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | Ubuntu 18.04 LTS

Verified test plan from the description. The string is much shorter.

![image](https://user-images.githubusercontent.com/34715963/79867063-064e6200-83de-11ea-99ca-bee469429ebf.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.8.82 Chromium: 81.0.4044.113 (Official Build) dev (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.14.6 (Build 18G3020)

English:
<img width="1194" alt="Screen Shot 2020-04-21 at 1 41 49 PM" src="https://user-images.githubusercontent.com/28145373/79896264-2548f600-83d6-11ea-862e-11a9fedc3b21.png">

Bulgarian:
<img width="1191" alt="Screen Shot 2020-04-21 at 1 43 10 PM" src="https://user-images.githubusercontent.com/28145373/79896254-22e69c00-83d6-11ea-8ab8-3a04968d7459.png">
