### ISSUE TITLE
Reduce interval between P3A pings from ~1 hour to ~1 minute

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#8084]
Currently P3A pings are separated by about an hour, with some randomness added.

Following a discussion about needing to retain the property that a given browser's pings cannot be linked/associated, the decision was made to reduce the interval between pings to 1 minute (assume with equivalent added randomness to reduce linkability)

**Comment by iefremov** [comment]
Fixed in https://github.com/brave/brave-core/pull/4531

**Comment by iefremov** [comment]
For QA:
1) Launch the browser on a clean profile
2) Check chrome://local-state, find `p3a` section
3) Wait for some time, refresh, random p3a values should be marked as `sent` one per minute

The same can be checked on existing profile by launching the browser with `--p3a-rotation-interval-seconds=5`, waiting for some time (ten seconds), closing the browser - to clear `sent` status of recorded p3a values.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

Brave | 1.3.116 Chromium: 80.0.3987.106 (Official Build) (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-browser/issues/8084#issuecomment-586204158
- Verified the existing profile without using the flag `--p3a-rotation-interval-seconds=5`
confirmed from @iefremov that flag should not be used when launching an upgraded profile https://github.com/brave/brave-browser/issues/8295#issuecomment-587435431
- Verified that local-state file is showing `sent =True` and timestamp is shown for brave stats in a clean profile
![image](https://user-images.githubusercontent.com/38657976/74747574-29994b80-528d-11ea-972a-c72d24d8a233.png)
- Verified that local-state file is showing `sent =True` and timestamp is shown for brave stats in an upgraded profile
![image (1)](https://user-images.githubusercontent.com/38657976/74747682-53eb0900-528d-11ea-92b8-260b844eb2be.png)
