### ISSUE TITLE
Implement fallback image for tipping banner 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8089]
## Description 

CR 80 broke tipping banner images (#8074). We should have some fallback generic images on tipping banner so that in case something breaks the tipping banner doesn't show blank banner (See screenshots in #8074)

## Actual result:

See screenshots in #8074 

## Expected result:
Have fallback images so that tipping banner doesn't look empty 

## Reproduces how often: 

Easy on the CR80 upgrade and hope that it doesn't reproduce in future

## Version/Channel Information:

version info copied from #8074 
Can you reproduce this issue with the current release? not on 1.2.43, but yes on 1.3.110
Can you reproduce this issue with the beta channel?
Can you reproduce this issue with the dev channel?
Can you reproduce this issue with the nightly channel? yes, reproduces on 1.5.81

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
we have fallback image if image is not provided by publisher. This specific one was that blank image was served because of this bug
