### ISSUE TITLE
Follow up of #8044 - C80 - unable to open PDF in PT and TOR tabs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8090]
## Description 

Follow up of #8044 - C80 - unable to open PDF in PT and TOR tabs

## Steps to Reproduce

   1. Clean profile `1.3.111-Chromium: 80.0.3987.85`
   2. Open a PT and TOR tab
   3. Open a PDF file in PT or TOR tab (https://basicattentiontoken.org/BasicAttentionTokenWhitePaper-4.pdf)
   4. Unable to open PDF files in PT and TOR tabs

## Actual result:

Unable to open PDF files in PT and TOR tabs
![image](https://user-images.githubusercontent.com/38657976/73915720-f09ec580-48e1-11ea-9c95-f47f14f1e8d2.png)

## Expected result:
PDF files should open in PT and TOR tabs

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.3.111 Chromium: 80.0.3987.85 (Official Build) (64-bit)
-- | --
Revision | 583b05dfa4ffc657f0f7c5cc13f53aa17c9a5bcf-refs/branch-heads/3987@{#791}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Not sure
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @bsclifton @yrliou

**Comment by kjozwiak** [comment]
Reproducible on `macOS 10.15.3 x64` using the following build:

Brave | 1.6.5 Chromium: 80.0.3987.85 (Official Build) nightly (64-bit)
-- | --
Revision | 583b05dfa4ffc657f0f7c5cc13f53aa17c9a5bcf-refs/branch-heads/3987@{#791}
OS | macOS Version 10.15.3 (Build 19D76)

Nice catch @GeetaSarvadnya 👍

**Comment by rebron** [comment]
<img width="1313" alt="screen_shot_2020-02-07_at_12 32 36_am" src="https://user-images.githubusercontent.com/5951041/74016629-98021380-4947-11ea-9d03-6e2b4912bac1.png">
Looks good, on macOS, Windows both private window and private window with Tor

Brave | 1.3.113 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.15.3 (Build 19D76)

**Comment by kjozwiak** [comment]
Awesome, thanks @rebron 👍 Labeling as passed on `macOS` & `Win x64` as per the above.
