### ISSUE TITLE
Flash object not blocked on Tor windows

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8096]
## Description 

Flash object not blocked on Tor windows

## Steps to Reproduce

   1. Clean profile `1.3.111`
   2. Open a TOR tab load http://homestarrunner.com/
   3. Make sure it's blocked
   4. Navigate to brave://settings/content/flash and enable flash
   5. Refresh the http://homestarrunner.com/ which is opened in TOR
   6. Flash gets enabled in TOR
   

## Actual result:

Flash object not blocked on Tor windows
![image](https://user-images.githubusercontent.com/38657976/73939901-67eb4e00-4910-11ea-99b2-0a274e618e7c.png)

## Expected result:
Flash should be blocked on Tor window

## Reproduces how often: 

Always

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes 1.2.43, not on C78 release 1.0.0 (CR 78.0.3904.97)
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @yrliou @riastradh-brave @tomlowenthal @rebron @jumde

**Comment by rebron** [comment]
Moving out of 1.3.x milestone. @tomlowenthal Can you take a look for priority?

**Comment by tomlowenthal** [comment]
Not a bug. When you deliberately enable flash in settings and then allow a site to run flash, it's going to be able to run flash — even in a private window with Tor. Working as expected.
