### ISSUE TITLE
NTP site removal notification interface needs improvements

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#8097]
Position doesn't look good, currently overflows stats and words are too close.

<img width="1271" alt="Screen Shot 2020-02-06 at 10 49 38 AM" src="https://user-images.githubusercontent.com/4672033/73942839-83ce0000-48ce-11ea-8136-1e3184338662.png">

Introduced with https://github.com/brave/brave-core/pull/4075/files#diff-4f7fe7112dc0ec2b5cd45ecb5f76c0cdR100-R104.

Labeling as `regression` since it deviates from previous versions interface. Please change if I'm wrong. 

cc @petemill @karenkliu

**Comment by rebron** [comment]
Closing. This was fixed with an earlier change. #8282

**Comment by rebron** [comment]
@cezaraugusto Please reopen if you meant something else with this issue.
