### ISSUE TITLE
Previous shield settings are gone after restarting the browser

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#81]
STR:
  1. open any webpage and change any shield setting of it
     (I've try toggle the shields toggle, ad control, or block scripts)
  2. restart brave
  3. change any shield settings of the same webpage

expected result:
  shield settings are the same as before we restart the browser
actual:
  shield settings are reset to default, and browser crashes when trying to change any shield settings

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7
