### ISSUE TITLE
Accessing brave:// alias doesn't forward to chrome://

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#810]
## Description 

Accessing brave:// alias doesn't forward to chrome://

## Steps to Reproduce

   1. Build from master (790d5db)
   2. Open a new tab and load `brave://version` 
   3. Does a search for the URL instead of forwarding to `chrome://version`

## Actual result:

Does a search for the URL instead of forwarding to `chrome://<URL>`

## Expected result:
Should forward to `chrome://<URL>`

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Brave | 0.55.1 Chromium: 69.0.3497.42 (Official Build) (64-bit)
-- | --
Revision | 9c4613c66dfeb2b76ef6dd4b15884c15db3b4969-refs/branch-heads/3497@{#655}
OS | Windows
JavaScript | V8 6.9.427.14
Flash | (Disabled)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
#213

**Comment by bbondy** [comment]
Moving to 1.x, not the end of the world, it is handled but it's not sorted first for autocomplete yet.

**Comment by srirambv** [comment]
@bbondy @petemill can this be closed now since https://github.com/brave/brave-core/pull/584 is already merged into 0.55.x and correctly shows `brave://` and loads correctly?

**Comment by bbondy** [comment]
yep!
