### ISSUE TITLE
Expose Tor log in `brave://tor`

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#8106]
## Description
A friend of mine told me that he's found our Tor support quite unreliable on his Linux desktop (it's possible he's running into #8076 or #8129 at the moment).

What he suggested is that we expose the tor daemon log somewhere so that tech-savvy users can more easily figure out what's wrong (and send us useful bug reports).

[Orbot](https://play.google.com/store/apps/details?id=org.torproject.android) on Android does this in a nice way, but perhaps all we need for an MVP would be to redirect the daemon log file to an in-memory structure and make it viewable from an internal URL like `brave://tor`.

## Designs
The Tor connection status is displayed prominently on the NTP with a flashing indicator to draw attention and show progress. This would give some hint that the reason why NTP is not connecting to a webpage that a user entered is because it's waiting for this Tor connection to complete. For users who are so inclined to dig into the details, `View logs` links to `brave://tor`.

The new, simplified NTP design ensures that no scrolling would occur for all but the very smallest screens - the content height is not much longer than an extension panel.

![connection](https://user-images.githubusercontent.com/2388823/94075684-7e1b2100-fdb0-11ea-95da-e247131e4c8e.gif)

### User flow

![image](https://user-images.githubusercontent.com/2388823/94075770-a276fd80-fdb0-11ea-96c2-7fa71da4e39c.png)

### Search bar
The search bar has DDG set as the default. The user can click on the search bar dropdown to select a different SE for a particular search query.
![image](https://user-images.githubusercontent.com/2388823/94075323-d6055800-fdaf-11ea-8116-66635804099c.png)

### Keyboarding
![image](https://user-images.githubusercontent.com/2388823/94075794-ab67cf00-fdb0-11ea-960c-b59d7237a804.png)
![image](https://user-images.githubusercontent.com/2388823/94075352-e1f11a00-fdaf-11ea-8e13-0e604c453561.png)

## Assets
Figma: https://www.figma.com/file/5THkuEtO2Ewn9LfqrHZP9a/Desktop-Private-and-TOR-Windows?node-id=102%3A2574

**Comment by fmarier** [comment]
@doegox Next time you encounter this problem, can you email me your `~/.config/BraveSoftware/Brave-Browser/tor/data/tor.log`?

That is BTW the location of the log file you were after :)

**Comment by doegox** [comment]
Oh thanks! Will do

**Comment by doegox** [comment]
> @doegox Next time you encounter this problem, can you email me your `~/.config/BraveSoftware/Brave-Browser/tor/data/tor.log`?

The issue still occurs.
When it occurs, there is nothing in the logs at all, as if the tor module didn't start at all.
Restarting Brave (sometimes several times) fixes the issue.

**Comment by fmarier** [comment]
@doegox I have also seen this on my machine but only the first time I opened a Tor window. In other words, what I saw was this:

1. Open a Tor window (doesn't work).
2. Close the Tor window.
3. Open a Tor window (this one works).

In your case, it also doesn't work the second time and you need to exit Brave and start it again?

Is there anything relevant in stdout/stderr? Syslog? dmesg?

**Comment by karenkliu** [comment]
Designs added!

**Comment by fmarier** [comment]
Now available at `brave://tor-internals/`.
