### ISSUE TITLE
Don't cache NTP sponsored images assets

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#8112]
When assets are updated, we should provide new assets always.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.3 x64` using the following build:

Brave | 1.3.113 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.15.3 (Build 19D76)

Example: https://bravesoftware.slack.com/archives/CQGTGBNH1/p1581065695141200

**Comment by kjozwiak** [comment]
Changing this to a `QA/No`. This is going to be hard to QA as we don't have profiles on `Linux` and `Windows` in this state. Desktop is also pointing to production which makes it more difficult. I was lucky enough to save a a profile on `macOS` so we could verify the above on at least one of the platforms.
