### ISSUE TITLE
Cosmetic filtering crashes on Windows

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#8113]
As per this report https://github.com/brave/brave-browser/issues/5381#issuecomment-582568117 and others, cosmetic filtering crashes the browser when enabled in a tab on Windows.

The crash traceback indicates an issue in `adblock-rust-ffi`.

**Comment by antonok-edm** [comment]
[This](https://github.com/brave/adblock-rust-ffi/pull/13) `adblock-rust-ffi` PR should solve the issue when merged in `brave-core`.

**Comment by LaurenWags** [comment]
@antonok-edm could you add a test plan for manual QA? if this doesn't need to be manually QA'd we can remove `QA/Yes` label and add `QA/No`. Thanks!

**Comment by antonok-edm** [comment]
@LaurenWags easy enough, updated the PR!

**Comment by LaurenWags** [comment]
great, thanks @antonok-edm!

**Comment by bsclifton** [comment]
Fixed in 1.6 with https://github.com/brave/brave-core/pull/4540
Fixed in 1.5 with https://github.com/brave/brave-core/pull/4589

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.5.106 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/4540
- Verified on clean and upgraded profile
