### ISSUE TITLE
Crash on Brave Dev channel, after update to 1.5.84

### ISSUE THREAD

**Issue by Mister36MN** [brave/brave-browser#8114]
## Description 

Upon the update to 1.5.84 Dev Channel, Brave crashes on start up. This has occurred on two different PCs. (win 10 64 bit)

Event viewer shows the following event: 

"The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user (PC)\* SID (S-1-5-21-2711341036-2121172453-3823298948-1001) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool. "

Upon checking the registry there is no key matching the above CLSID

Using Dark Theme, Dark Reader, ublock Origin as main extensions.

Attempted re-installing on one PC, had no effect on behavior.

## Steps to Reproduce

   1. update to Dev 1.5.84
   2. Start Brave
   3. 

## Actual result:

Brave crashes after about 1-2 seconds of being open

## Expected result:

Brave Opening

## Reproduces how often: 

Every time Brave starts, on two different PCs with the same version of Brave

## Brave version (brave://version info)

Dev Channel 1.5.84

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Unable to test
- Does the issue resolve itself when disabling Brave Rewards? Unable to test, but I have rewards off by default
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment]
@Mister36MN can you go into brave://crashes and send the crash report and copy and paste the id into here?

**Comment by rebron** [comment]
Just realized crash on startup so won't actually have the chance to send the report.

**Comment by Mister36MN** [comment]
Is there a manual location for the crash logs?

I'm installing 1.5.85 right now just to see if it resolves the issue.

I also installed 1.5.84 on a third machine and it *didn't* crash, so I'm trying to find the connection between the first two.

**Comment by Mister36MN** [comment]
No change with 1.5.85

**Comment by Mister36MN** [comment]
Is this perhaps related to https://github.com/brave/brave-browser/issues/8128 ?

In the brief second that I can see brave open, it says Home://newtab

**Comment by Mister36MN** [comment]
Crash stopped on one PC so far after updating to 1.5.86

**Comment by rebron** [comment]
@Mister36MN Do you have sync enabled? Can you go ahead and send your crash reports now and post the ids here e.g. Uploaded Crash Report ID f274c39e536ae154 (Local Context: 8fb72831-8f81-4f03-9f1f-d0f362f9a34c)

**Comment by Mister36MN** [comment]
Sure, here are a few, and yes I did have sync enabled.

6e08fba2-fd7f-43f9-859d-8af1af5ad112

79fe6286-a867-47a2-9567-4edc30b7f5f5

a4b82909-3245-4ff0-aac0-636e0610cecf

When I manually set to upload them, it still says "not yet uploaded" however

**Comment by bsclifton** [comment]
This should be resolved now - however, sync is now disabled. Are you able to update @Mister36MN?

If not, you can grab a copy from here (depending on your channel):
- https://brave.com/download-dev/
- https://brave.com/download-nightly/

**Comment by Mister36MN** [comment]
@bsclifton  I was able to update to 1.5.86 when it released, and have had no troubles since then.

**Comment by bsclifton** [comment]
Awesome, thanks for the update 😄
