### ISSUE TITLE
PWA Crashes on Moving Window

### ISSUE THREAD

**Issue by mstrcrz** [brave/brave-browser#8117]
## Description 

Installed Outlook PWA tried to move PWA window and it closes the window immediately.

## Steps to Reproduce

   1. Install Outlook PWA
   2. Launch PWA
   3. Click top bar (to move window)
   4. Window immediately closes (PWA no longer open)

## Actual result:

None.

## Expected result:
PWA should be able to be moved & resized 

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.3.108 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G1012)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  
Happens on current stable release as well.
Brave | 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.14.6 (Build 18G1012)

- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 
No - works on latest Chrome Canary
Google Chrome | 82.0.4050.0 (Official Build) canary (64-bit)
-- | --
Revision | cfc0c75702b4777975298ae283b75f08856d810a-refs/branch-heads/4050@{#1}
OS | macOS Version 10.14.6 (Build 18G1012)

**Comment by bsclifton** [comment]
@mstrcrz can you please try this on the latest version of Brave? Thanks! 😄

**Comment by mstrcrz** [comment]
> @mstrcrz can you please try this on the latest version of Brave? Thanks! 😄

Still happening for me!


Brave | 1.7.67 Chromium: 80.0.3987.149 (Official Build) beta (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)
JavaScript | V8 8.0.426.27
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

**Comment by ya-d** [comment]
I can confirm this still happens in current versions and for *any* PWA. See several reports over at #5842.

Version 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)
MacOS 10.15.3

**Comment by mstrcrz** [comment]
> I can confirm this still happens in current versions and for _any_ PWA. See several reports over at #5842.
> 
> Version 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)
> MacOS 10.15.3

Check out brave://version for a copy/paste table like above  :)

**Comment by ya-d** [comment]
Not quite as clean. Thats what I get:

```
Brave	1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)
Revision	5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS	macOS Version 10.15.3 (Build 19D76)
JavaScript	V8 8.0.426.27
Flash	(Deaktiviert)
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
Command Line	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,WebXR,VideoPlaybackQuality,WebXrGamepadModule --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path	/Users/yannick/Library/Application Support/BraveSoftware/Brave-Browser/Default
```

**Comment by oky2abbas** [comment]
+1

**Comment by rebron** [comment]
@mstrcrz @ya-d @oky2abbas Can you take a look at brave://crashes and see if there any reports showing up ther and please send.

**Comment by ya-d** [comment]
Thank you for further investigating this issue. Unfortunately there are no crash reports in my case.

**Comment by oky2abbas** [comment]
+1 -> in version 1.5.122

**Comment by oky2abbas** [comment]
Brave Version : `1.5.123`
OS: `macOS 10.15.4`

@rebron Unfortunately, the problem report is not received in brave: // crashes.
For more information, see: #9006

**Comment by bsclifton** [comment]
possibly related: https://github.com/brave/brave-browser/issues/7205

**Comment by thechild** [comment]
Having this on `Version 1.18.70 Chromium: 87.0.4280.101 (Official Build) (x86_64)`. Running macos 10.15.7.

I installed the Roam (roamresearch) PWA.  It works perfectly in both chrome and edge.  In brave, it opens fine, but as soon as I move or resize the window, it crashes.  Nothing in brave://crashes.  This happens 100% of the time.

However, I do get this in my system logs:

```*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSAccessibilityRemoteUIElement accessibilityTitle]: unrecognized selector sent to instance 0x7fe0a0eadbe0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3510bb57 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6df855bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3518abe7 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff350703bb ___forwarding___ + 1427
	4   CoreFoundation                      0x00007fff3506fd98 _CF_forwarding_prep_0 + 120
	5   Brave Browser Framework             0x0000000110c5b021 ChromeMain + 88239873
	6   AppKit                              0x00007fff323ae25a -[NSAccessibilityAttributeAccessorInfo getAttributeValue:forObject:] + 58
	7   AppKit                              0x00007fff3296bc29 ___NSAccessibilityEntryPointValueForAttribute_block_invoke.805 + 1674
	<…>
```

And, right before:

``` (
	0   CoreFoundation                      0x00007fff3510bb57 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6df855bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3518abe7 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff350703bb ___forwarding___ + 1427
	4   CoreFoundation                      0x00007fff3506fd98 _CF_forwarding_prep_0 + 120
	5   Brave Browser Framework             0x0000000110c5b021 ChromeMain + 88239873
	6   AppKit                              0x00007fff323ae25a -[NSAccessibilityAttributeAccessorInfo getAttributeValue:forObject:] + 58
	7   AppKit                              0x00007fff3296bc29 ___NSAccessibilityEntryPointValueForAttribute_block_invoke.805 + 1674
	8   AppKit                              0x00007fff32967a74 NSAccessibilityPerformEntryPointObject + 16
	9   AppKit                              0x00007fff3262bc01 _NSAccessibilityEntryPointValueForAttribute + 168
	10  AppKit                              0x00007fff3276d0b3 -[NSObject(NSAccessibilityInternal) _accessibilityValueForAttribute:clientError:] + 351
	11  AppKit                              0x00007fff327721ce CopyAppKitUIElementAttributeValueNoCatch + 98
	12  AppKit                              0x00007fff3276f0b2 CopyAttributeValue + 142
	13  HIServices                          0x00007fff333623f6 _AXXMIGCopyAttributeValue + 389
	14  HIServices                          0x00007fff333834cb _XCopyAttributeValue + 443
	15  HIServices                          0x00007fff33342f64 mshMIGPerform + 174
	16  CoreFoundation                      0x00007fff35090304 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	17  CoreFoundation                      0x00007fff35090250 __CFRunLoopDoSource1 + 541
	18  CoreFoundation                      0x00007fff3508ed79 __CFRunLoopRun + 2270
	19  CoreFoundation                      0x00007fff3508de3e CFRunLoopRunSpecific + 462
	20  HIToolbox                           0x00007fff33cbaabd RunCurrentEventLoopInMode + 292
	21  HIToolbox                           0x00007fff33cba7d5 ReceiveNextEventCommon + 584
	22  HIToolbox                           0x00007fff33cba579 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	23  AppKit                              0x00007fff32300039 _DPSNextEvent + 883
	24  AppKit                              0x00007fff322fe880 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
	25  AppKit                              0x00007fff322f058e -[NSApplication run] + 658
	26  Brave Browser Framework             0x000000010ef7cd0c ChromeMain + 57969644
	27  Brave Browser Framework             0x000000010ef7bad3 ChromeMain + 57964979
	28  Brave Browser Framework             0x000000010ef3914a ChromeMain + 57692202
	29  Brave Browser Framework             0x000000010ef0bbbe ChromeMain + 57506462
	30  Brave Browser Framework             0x000000010b833de1 ChromeAppModeStart_v6 + 2593
	31  app_mode_loader                     0x000000010298743d main + 3389
	32  app_mode_loader                     0x000000010298671b main + 27
	33  libdyld.dylib                       0x00007fff6f12dcc9 start + 1
) ```

And before that:

`-[NSAccessibilityRemoteUIElement accessibilityTitle]: unrecognized selector sent to instance 0x7fe0a0eadbe0 `

**Comment by iefremov** [comment]
duplicate https://github.com/brave/brave-browser/issues/7205
