### ISSUE TITLE
Web3 account is locked if no provider is set

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8119]
## Description 

Web3 account is locked if no provider is set

## Steps to Reproduce

   1. Clean profile on 1.6.7 nightly
   2. Create local CW account
   3. Set to Roptsen network and click on deposit
   4. Web3 complains that account is locked 
   5. Reload the page, notification shows up to setup 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/74011424-d03c3d00-49ad-11ea-8522-34f0e101f0f4.png)
![image](https://user-images.githubusercontent.com/17010094/74011519-15f90580-49ae-11ea-8fb4-023cf993cb41.png)

## Expected result:
Web3 provider should be prompted before the script can be injected

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.6.7 Chromium: 80.0.3987.87 (Official Build) nightly (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bbondy

**Comment by bbondy** [comment]
Closing this in favor of this: https://github.com/brave/brave-browser/issues/8120
