### ISSUE TITLE
Disable translate without user-interaction

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#812]
## Description 
Disable translate by default. On visiting a domain with a different language preference, a request is initiated for `translate.googleapis.com` without user-interaction

## Steps to Reproduce
   1. Open `https://espanol.epa.gov/` and a dialog to translate the page is displayed

## Actual result:
The translate dialog is displayed and request to `translate.googleapis.com` is initiated.

## Expected result:
The request should only be initiated on user-interaction. 

## Reproduces how often: 
100%

## Brave version (about:brave info) 
`0.54.0 Chromium: 69.0.3497.32 (Official Build) dev (64-bit)`

### Reproducible on current release:
Yes

**Comment by tomlowenthal** [comment]
Perhaps it would make sense to have an off-by-default pref to turn this back on. It's a useful feature which has a privacy cost. Some might want it on, some off — we should ship it off and lets folks turn it back on?

**Comment by srirambv** [comment]
I think #208 supersedes this issue.

**Comment by bbondy** [comment]
master: 44cd37a601ba45e27d85adb5b7892b6a029cd001
0.56.x: 565bc3a43bde5752bf0bc2c7cc725dc2d46e1890
0.55.x: 4705fb97667a46abb13df3e97c53350db08b1ebc

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

* Verified visiting the specified link doesn't offer to translate to English
* Verified other non-English sites don't offer to translate either
