### ISSUE TITLE
Selecting Setup from notification bar opens a blank wallet page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8121]
## Description 

Selecting Setup from notification bar opens a blank wallet page

## Steps to Reproduce

   1. Clean install 1.6.7
   2. VIsit cryptokitties.co and trigger notification bar to setup web3 provider
   3. Click on setup, opens a blank brave://wallet page. Need to reload the page to show the actual wallet page

## Actual result:

![web3setup](https://user-images.githubusercontent.com/17010094/74014142-109eb980-49b4-11ea-9fd4-5b5dde72e74d.gif)

## Expected result:
Should load the page on first launch

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.6.7 Chromium: 80.0.3987.87 (Official Build) nightly (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.523)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
Moving to 1.10.x Beta as brave/brave-core#5624 is uplifted

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 Catalina x64` using the following build:

```
Brave | 1.10.81 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.5 (Build 19F101)
```

* the above case was checked and verified several times via https://github.com/brave/brave-browser/issues/9757#issuecomment-638480788
