### ISSUE TITLE
embedded typeform no longer loading on brave when shields are up! 

### ISSUE THREAD

**Issue by krrisis** [brave/brave-browser#8124]
## Description 
Embedded typeform is no longer working on typeform, where it worked before. Typeform doesn't support brave, so logging here bcs it could just as well be linked to an update you guys made.

## Steps to Reproduce

   1. Go to https://commonsstack.org/apply with brave 
   2. see that the typeform is not loading :) 
   3. Go there with any other browser and you'll see that it is :) 
   4. Disable shields and it loads 

## Reproduces how often: 

always 

## Brave version (brave://version info)

V1.2.43 (tested on mac & windows 10)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
**YES**
- Is the issue reproducible on the latest version of Chrome? 
**NO**
- Is the issue reproducible on the Brave mobile? 
**YES!**

**Comment by rebron** [comment]
@krrisis Can you update to the latest 1.5.x? I just tried on the latest and it looks like it's working for me with shields down.

**Comment by krrisis** [comment]
> @krrisis Can you update to the latest 1.5.x? I just tried on the latest and it looks like it's working for me with shields down.

hey @rebron it works now, with shields up I see (that was the issue). So I'll close this issue :) thx!!
