### ISSUE TITLE
Follow up to #8031 - Missing string on NTP SI widget 

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#8126]
Follow up to #8031 - `Turn on Brave Ads to claim your share. You can also choose to hide sponsored images` is not translated into Polish

## Steps to Reproduce

   1. Clean install in Polish
   2. Enable Rewards
   3. Disable Ads
   4. Enable NTP SI Demo flag
   5. Open NTP SI

## Actual result:

 Missing string on NTP SI widget for Polish language
![image](https://user-images.githubusercontent.com/34715963/74048580-c973f100-49d2-11ea-84c7-74f90b93b486.png)

## Expected result:
`Turn on Brave Ads to claim your share. You can also choose to hide sponsored images` is translated into Polish

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.3.113 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @mkarolin @rebron @bsclifton @NejcZdovc @petemill

**Comment by rebron** [comment]
@btlechowski Can you recheck in 1.8.x when you get a chance?

**Comment by btlechowski** [comment]
No longer reproducible

Verification passed on

Brave | 1.10.74 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

Verified test plan for the description

![image](https://user-images.githubusercontent.com/34715963/83174319-82913f00-a11a-11ea-9776-76a0bc31370b.png)
