### ISSUE TITLE
Startup crash when `Bookmarks` contains duplicate object ID

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#8134]
## Description 

When the `Bookmarks` file contains a duplicate `object_id`, Brave crashes immediately at startup.

## Steps to Reproduce

1. Close the browser.
2. Overwrite `~/.config/BraveSoftware/BraveBrowser/Default/Bookmarks` with [this minimal file](https://gist.github.com/fmarier/7ffa3ffff720f3bc521f490977acfbaa)
3. Start the browser.

## Actual result:

The browser during startup, a few seconds (less than 10, probably less than 5) after the browser window appears. The background image on the newtab page doesn't have time to get displayed before the crash.

The following is printed in the terminal:

```
(brave:29059): Gtk-WARNING **: 12:07:36.017: Theme parsing error: gtk.css:6:24: The 'gtk-key-bindings' property has been renamed to '-gtk-key-bindings'
[29084:29084:0207/120736.259946:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[29089:29108:0207/120736.814457:ERROR:nss_util.cc(283)] After loading Root Certs, loaded==false: NSS error code: -8018
--2020-02-07 12:07:37--  https://laptop-updates.brave.com/1/bc-crashes
Resolving laptop-updates.brave.com (laptop-updates.brave.com)... 151.101.193.7, 151.101.1.7, 151.101.65.7, ...
Connecting to laptop-updates.brave.com (laptop-updates.brave.com)|151.101.193.7|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16 [text/html]
Saving to: '/dev/fd/4'
     0K                         
Crash dump id:  73111d625518b397
                             100% 30.2M=0s
2020-02-07 12:07:37 (30.2 MB/s) - '/dev/fd/4' saved [16/16]
--2020-02-07 12:07:37--  https://laptop-updates.brave.com/1/bc-crashes
Resolving laptop-updates.brave.com (laptop-updates.brave.com)... 151.101.65.7, 151.101.129.7, 151.101.193.7, ...
Connecting to laptop-updates.brave.com (laptop-updates.brave.com)|151.101.65.7|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16 [text/html]
Saving to: '/dev/fd/4'
Crash dump id: 18119648730048df
/usr/bin/brave-browser: line 48: 29059 Illegal instruction     (core dumped) "$HERE/brave" "$@"
```

## Expected result:

Brave 1.2.43 starts just fine with the same `Bookmarks` file.

## Reproduces how often: 

100%

## Brave version (brave://version info)
```
Brave	1.3.113 Chromium: 80.0.3987.87 (Official Build) (64-bit)
Revision	449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS	Linux
```

## Other Additional Information:

None of the following command-line switches fully fix the problem:

- `--disable-sync`
- `--disable-brave-sync`
- `--disable-gpu`

However using `--disable-sync` or `--disable-brave-sync` does change the *illegal instruction* crash into a *segmentation fault* crash:

```
(brave:64516): Gtk-WARNING **: 15:29:51.566: Theme parsing error: gtk.css:6:24: The 'gtk-key-bindings' property has been renamed to '-gtk-key-bindings'
[64542:64542:0207/152951.740559:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
--2020-02-07 15:29:51--  https://laptop-updates.brave.com/1/bc-crashes
Resolving laptop-updates.brave.com (laptop-updates.brave.com)... 151.101.193.7, 151.101.1.7, 151.101.65.7, ...
Connecting to laptop-updates.brave.com (laptop-updates.brave.com)|151.101.193.7|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16 [text/html]
Saving to: '/dev/fd/4'

     0K
Crash dump id: f3340c1db752f6d7
                                                 /usr/bin/brave-browser: line 48: 64516 Segmentation fault      (core dumped) "$HERE/brave" "$@"
```

**Comment by fmarier** [comment]
This is fixed in the [1.3.114 builds](https://github.com/brave/brave-browser/releases/tag/untagged-e04226b97f7be2c2e5e6).

**Comment by kjozwiak** [comment]
@fmarier can we close this off and move it into the https://github.com/brave/brave-browser/milestone/79?

**Comment by fmarier** [comment]
Sounds good to me.

**Comment by bsclifton** [comment]
@fmarier is this resolved now? I believe it is, but wanted to verify 😄

**Comment by fmarier** [comment]
> is this resolved now? I believe it is, but wanted to verify 

It's resolved in the default configuration (Sync disabled).

That said, if I enable "Brave Sync" in `chrome://flags` and then create a new Sync chain, then the browser crashes immediately. This is tracked in #8325 .
