### ISSUE TITLE
ERR_CONNECTION_ABORTED for https://www.binance.com & http://www.oxbtc.com/m/

### ISSUE THREAD

**Issue by MASY2000** [brave/brave-browser#8137]
## Description 
I've banned from access https://www.binance.com & http://www.oxbtc.com/m/ with this message "This site can’t be reachedThe webpage at http://www.xxxxxxx.com/ might be temporarily down or it may have moved permanently to a new web address.
ERR_CONNECTION_ABORTED".
But I've fully access to https://www.binance.us, https://www.jex.com & https://www.binance.org on Brave.

## Steps to Reproduce
   1. Shield up & down, It's still banned.
   2. Allow Flash, It's still banned.
   3. Disable Antivirus, Firewall & Windows Defender, It's still banned.

## Brave version (brave://version info)

Brave | 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1909 (Build 18363.628)
JavaScript | V8 7.9.317.33
Flash | 32.0.0.321 C:\WINDOWS\system32\Macromed\Flash\pepflashplayer64_32_0_0_321.dll
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,WebXR,WebXrGamepadModule,UnifiedConsent,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,AllowPopupsDuringPageUnload,SyncUSSBookmarks --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe

## Version/Channel Information:
This issue does happening on all release of Brave.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No, Accept Chrome Android only

**Comment by rebron** [comment]
Closing. This isn't a browser issue.  Can you check with support from your ISP or binance.com or oxbtc.com to resolve?
