### ISSUE TITLE
Include region info in ntp sponsor component name

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#8140]
With region info in component name, we can check easily which ads is used for now.

Currently, component name doesn't include region info.
![image](https://user-images.githubusercontent.com/6786187/74077663-0a1c4a80-4a65-11ea-94d7-7001577e47ef.png)

It should be good if it includes region info like below.
![image](https://user-images.githubusercontent.com/6786187/74077939-b6f7c700-4a67-11ea-8a42-c96c2398ded3.png)

**Comment by LaurenWags** [comment]
Verified passed using

Brave | 1.7.71 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4561 for several regions

United States (US)
<img width="300" alt="US" src="https://user-images.githubusercontent.com/28145373/77424136-fc1d5180-6da6-11ea-89ff-50a9f26571b8.png">

United Kingdom (GB)
<img width="313" alt="UK" src="https://user-images.githubusercontent.com/28145373/77424141-fde71500-6da6-11ea-8aad-438c54d0bc70.png">

Australia (AU)
<img width="297" alt="Australia" src="https://user-images.githubusercontent.com/28145373/77424151-00496f00-6da7-11ea-9218-375fa66a1a98.png">

Canada (CA)
<img width="301" alt="Canada" src="https://user-images.githubusercontent.com/28145373/77424158-02133280-6da7-11ea-954b-12ad2f117ea9.png">

France (FR)
<img width="305" alt="France" src="https://user-images.githubusercontent.com/28145373/77424161-03dcf600-6da7-11ea-84d1-e123dea39daf.png">
