### ISSUE TITLE
Temporarily disable sync to diagnose crashes

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#8141]
## Description 

We'll be temporarily disabling sync to diagnose several crashes and improve general stability.

## Steps to Reproduce

* Test Plan: https://github.com/brave/brave-core/pull/4565

## Actual result:

Brave is currently crashing due to several crashes which is affect user experience and stability.

## Expected result:

Temporarily disabling sync so we can diagnose the current crashes and improve stability. 

## Reproduces how often: 

We don't know how many users are currently affected but we've received numerous reports from various users on different social network platforms including Brave Community.

## Brave version (brave://version info)

Brave | 1.3.113 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}

Brave | 1.3.114 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome?  `N/A`

## Miscellaneous Information:

CCing @bbondy @rebron @anthonypkeane @ jsecretan @brave/legacy_qa

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Linux

- Verified test plan from https://github.com/brave/brave-core/pull/4565
- Verified Sync is disabled via command line flag found in brave://version
![image](https://user-images.githubusercontent.com/17010094/74128228-a760b580-4c02-11ea-84d2-2908074f6d25.png)
- Verified Sync is greyed out in hamburger menu

**Comment by kjozwiak** [comment]
Going to use https://github.com/brave/brave-browser/issues/8128 for the release notes as it has the most comments from community.
