### ISSUE TITLE
Performance auditing using Lighthouse

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#815]
Carried over from https://github.com/brave/browser-laptop/issues/9719

(This might only be applicable to WebUI pages?)

> https://developers.google.com/web/tools/lighthouse/ can probably be run on Brave's HTML resources

**Comment by jonathansampson** [comment]
Note that Lighthouse presently doesn't appear to work in Brave. It appears to hang while _warming up_:

![image](https://user-images.githubusercontent.com/815158/52983320-38b29880-33b0-11e9-8d58-28da4093ecfd.png)

This step takes, at most, a couple seconds in Chrome.

![audit-with-lighthouse](https://user-images.githubusercontent.com/815158/52983444-c7271a00-33b0-11e9-8a6c-583173cdf19f.gif)

**Comment by Brave-Matt** [comment]
+1 from Community: https://community.brave.com/t/googles-pagespeed-insights-tester-throws-error-when-run-in-brave-browser/44904/2

**Comment by Brave-Matt** [comment]
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/ay4uau/chrome_devtools_lighthouse_doesnt_work/

**Comment by llexan** [comment]
Also experiencing this issue on the latest (stable) release of Brave. Seems to also hang on "Cancelling..." when attempting to close it.

**Comment by llexan** [comment]
As a quick-fix for others running into this issue, installing the Lighthouse plugin and using that seems to work well: https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk/

**Comment by peterjaap** [comment]
+1 would love to have the Lighthouse Audit work since the plugin doesn't offer a trace.

**Comment by mserajnik** [comment]
+1 Would like this as well.

**Comment by ChrisB85** [comment]
+1 :)

**Comment by julianmejio** [comment]
+1

**Comment by agarzola** [comment]
I’d like to stay subscribed to this issue to learn about actual updates regarding the bug, but all of these `+1` emails are unnecessary noise. To everyone finding this issue:
- If you want to “upvote” an issue, I suggest reacting with a 👍 to the issue description.
- If you want to be notified of new comments and updates on the issue, click the _Subscribe_ button near the bottom of the right hand sidebar.

Thanks!

**Comment by opvasger** [comment]
I'd love to see this fixed! If there's any kind of help that I can provide, let me know! :sunny:

**Comment by lucadonnoh** [comment]
I had to redownload chrome because of this :(

**Comment by erfanimani** [comment]
+1, will need to get Chrome for this.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/3199

This was intended for us to run on our internal pages. Since our UI is no longer HTML/CSS/JavaScript (after moving to Brave Core), this is less applicable

Please give https://github.com/brave/brave-browser/issues/3199 a +1 if you'd like to see the Lighthouse / Audit feature fixed in Brave (I believe it's hanging if you try on your own pages)

**Comment by Varvus** [comment]
+1

**Comment by agarzola** [comment]
Please react with a 👍 on the original ticket description to express your interest in this ticket. If you want to be notified of updates on this ticket, use the _Subscribe_ button at the bottom of the sidebar on this ticket.

**Comment by nelth-fr** [comment]
Issue still there...

**Comment by bsclifton** [comment]
@nelth-fr are you enabling `Remote Debugging` on brave://settings/privacy?

**Comment by smathy** [comment]
Nailed it, thanks @bsclifton

**Comment by peterjaap** [comment]
@bsclifton I don't have that option under Privacy?

**Comment by Jos512** [comment]
Thank you @bsclifton ! Finally got it working with your suggestion, thanks! :slightly_smiling_face: 

----

@peterjaap The option is there, but in the Dutch version of Brave it's called "Foutopsporing op afstand":

![brave-remote-debugging-dutch](https://user-images.githubusercontent.com/13403160/78015010-090ee780-7349-11ea-921e-f80e81033b4e.png)

**Comment by peterjaap** [comment]
@Jos512 thanks, but my Brave is in English. I just needed to upgrade :man_facepalming:

**Comment by saifhalila** [comment]
just enable remote debugging in Brave Settings.

![remote-dubugging-Brave](https://user-images.githubusercontent.com/10274380/79070866-46bc2a80-7cd0-11ea-8bf6-323883c1b043.PNG)

**Comment by stopyransky** [comment]
what if i still get above error when doing lighthouse audit but the option is removed ? https://github.com/brave/brave-browser/issues/1736
