### ISSUE TITLE
Brave crashes on startup; log says "Failed to start paying out redeemed tokens due to an invalid timer"

### ISSUE THREAD

**Issue by tasdienes** [brave/brave-browser#8150]
## Description 
Yesterday I rebooted my computer.  Afterward, Brave will no longer start. When I try to start it, a window flashes briefly and disappears.

I ran it from the command line with logging and got this:
PS C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application> .\brave.exe --enable-logging
PS C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application> [19404:5928:0209/113521.293:ERROR:confirmations_impl.cc(1195)] Failed to start paying out redeemed tokens due to an invalid timer
[19404:5928:0209/113521.301:ERROR:confirmations_impl.cc(1143)] Failed to start retrying failed confirmations due to an invalid timer

## Steps to Reproduce

   1. Start Brave
   2. It crashes immediately 

## Actual result:
See above

## Expected result:
It doesn't crash

## Reproduces how often: 
Every time

## Brave version (brave://version info)
80.1.3.113 on Windows

## Version/Channel Information:

- Can you reproduce this issue with the current release? - yes
- Can you reproduce this issue with the beta channel? - I haven't tried, because I'm sure it won't occur with a clean installation
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? - I can't even try that
- Does the issue resolve itself when disabling Brave Rewards? - I can't even try that
- Is the issue reproducible on the latest version of Chrome?  - No

## Miscellaneous Information:
I had Brave Ads enabled for a while but recently disabled it.

**Comment by tasdienes** [comment]
Update to "1.3.115 Chromium: 80.0.3987.8" appears to have resolved this issue.

**Comment by bsclifton** [comment]
Thanks for the update, @tasdienes 😄
