### ISSUE TITLE
Black Corner on Gnome

### ISSUE THREAD

**Issue by qingxiang-jia** [brave/brave-browser#8155]
#7847  Description 

On Gnome 3, the browser window has a black corner next to each of its rounded corners. What's more weird is if you move it from left to right, you will see the right two corners (upper & lower) are temporarily gone. Similar behavior happens when you move it to other directions. Even more so, if there's an app behind the window, the corners are gone.

## Steps to Reproduce

   1. Open Brave on Gnome 3.

## Actual result:

With GTK+ theme, one can see black corners.
![gtk](https://user-images.githubusercontent.com/5571586/74115070-323da380-4b62-11ea-800a-479c8f4766c5.png)
With Dark theme, one can see black corners.
![dark](https://user-images.githubusercontent.com/5571586/74115075-35389400-4b62-11ea-950c-85644c0fb6bf.png)
With Light theme, one can see black corners.
![light](https://user-images.githubusercontent.com/5571586/74115078-37025780-4b62-11ea-8d41-faf6b7d86a59.png)
With any theme, when there's an app behind (even Brave itself), one doesn't see the black corners.
![light app background](https://user-images.githubusercontent.com/5571586/74115094-484b6400-4b62-11ea-87cb-bccc87e615f3.png)

## Expected result:
No corners.

## Reproduces how often: 

It happens every single time.

## Brave version (brave://version info)

Brave	1.2.43 Chromium: 79.0.3945.130 (Official Build) unknown (64-bit)
Revision	e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS	Linux
JavaScript	V8 7.9.317.33
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Command Line	/usr/lib/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=NotificationTriggers,AutofillServerCommunication,SmsReceiver,AudioServiceOutOfProcess,LookalikeUrlNavigationSuggestionsUI,WebXR,AllowPopupsDuringPageUnload,SyncUSSBookmarks,WebXrGamepadModule,UnifiedConsent --flag-switches-begin --enable-gpu-rasterization --enable-quic --enable-zero-copy --ignore-gpu-blacklist --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator,ParallelDownloading --flag-switches-end --disable-webrtc-apm-in-audio-service
Executable Path	/usr/lib/brave/brave
Profile Path	/home/****/.config/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Didn't try
- Can you reproduce this issue with the dev channel? Didn't try
- Can you reproduce this issue with the nightly channel? Didn't try

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by qingxiang-jia** [comment]
OK. Today I found a work around:
1. Open Brave.
2. `Ctrl+S`, it will prompt you to save whatever page you are on.
3. `Esc`, and observe the black corners are gone.

This workaround isn't great because one needs to do it every time one opens Brave or open a new windows of it.

**Comment by qingxiang-jia** [comment]
Good morning @bsclifton , the GNOME/Mutter team has confirmed that this bug has been fixed in GNOME 3.36. They are currently considering a port to the current stable GNOME which is 3.34. Shall we close this?
GNOME bug tracker for this issue: https://gitlab.gnome.org/GNOME/mutter/issues/1075

**Comment by bsclifton** [comment]
@qingxiang-jia very nice! Thanks for reporting the bug there and for sharing an update on the status 😄
