### ISSUE TITLE
[Android] Developer mode is enabled by default

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8157]
## Description 
 Developer mode is enabled by default

## Actual result 
Developer mode is enabled by default

## Expected result
Developer mode should not be enabled by default

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.6.12 Nighlty

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by emerick** [comment]
I think this is working as expected, per this comment:

```
    public static boolean shouldShowDeveloperSettings() {
        // Always enabled on canary, dev and local builds, otherwise can be enabled by tapping the
        // Chrome version in Settings>About multiple times.
        if (VersionConstants.CHANNEL <= Channel.DEV) return true;
        return ContextUtils.getAppSharedPreferences().getBoolean(PREF_DEVELOPER_ENABLED, false);
    }
```

**Comment by emerick** [comment]
Spoke with @srirambv and closing as expected, per the previous comment.
