### ISSUE TITLE
sync still shows as disabled in hamburger menu

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#8158]
## Description 
With 1.3.115 temporarily disabling sync, we still display Sync in the hamburger menu.. 

## Actual result:

![sync-hamburger](https://user-images.githubusercontent.com/5951041/74121795-d97c0400-4b7d-11ea-94e2-583df509f92e.PNG)

## Expected result:
No Sync in hamburger menu.

## Miscellaneous Information:
Filing as an issue as disabling Sync should remove all UI. However, showing as disabled maybe preferred versus completely disappearing.

**Comment by kjozwiak** [comment]
Looks similar on `macOS 10.15.3 x64` using the following build:

Brave | 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.15.3 (Build 19D76)

<img width="460" alt="Screen Shot 2020-02-10 at 1 01 12 AM" src="https://user-images.githubusercontent.com/2602313/74124642-fbd34900-4ba0-11ea-9824-2a55bcf2a44c.png">

Probably not a blocker as it appears disabled and users won't be able to interact with that particular element. However, we should remove it so it doesn't cause any confusions as users might wonder why they can't enable sync anymore.

**Comment by kjozwiak** [comment]
Removing this from https://github.com/brave/brave-browser/milestone/79 as per earlier conversations. This will be addressed in another release if we decide to remove `Sync` from the hamburger menu while it's temporarily disabled.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.3.116 Chromium: 80.0.3987.106 (Official Build) (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
- Verified that Sync option is completely removed from the hamburger menu in normal, PT and TOR tabs.
![image](https://user-images.githubusercontent.com/38657976/74679659-81c84300-51e4-11ea-8d48-ba73dd94f36e.png)
- Verified that Sync option is completely removed from the hamburger menu in an upgraded profile in normal, PT and TOR tabs. (upgraded from `1.3.113` to `1.3.116` and `1.3.115` to `1.3.116`)
- Additional testing is covered in https://github.com/brave/brave-browser/issues/8159#issuecomment-587115179 and https://github.com/brave/brave-browser/issues/8187#issuecomment-587100060
