### ISSUE TITLE
sync still shows as an option in settings

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#8159]
## Test plan
1. Fresh install
2. Visit brave://settings
3. Verify Sync doesn't show up on side menu or in main settings area
4. Visit brave://flags/#brave-sync
5. Enable the setting and restart the browser
6. Visit brave://settings
7. Verify Sync DOES show up on side menu and in main settings area

## Description 
Temporarily disabling sync in 1.3.115 still shows Sync menu item in preferences. Sync menu item should be gone or displayed as disabled. Sync section for setting is removed however.

## Actual result:
![sync-settings](https://user-images.githubusercontent.com/5951041/74121897-34adf680-4b7e-11ea-9db9-78010a9da452.PNG)

## Expected result:
Sync menu item should be removed or showed as disabled.

**Comment by kjozwiak** [comment]
Removing this from https://github.com/brave/brave-browser/milestone/79 as per earlier conversations. This will be addressed in another release if we decide to remove `Sync` from the hamburger menu while it's temporarily disabled. CCing @rebron

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.3.116 Chromium: 80.0.3987.106 (Official Build) (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
- Verified that by default `Sync` doesn't show up in the side menu in `brave://settings`
![image](https://user-images.githubusercontent.com/38657976/74678552-509a4380-51e1-11ea-9041-350c552f1d9f.png)
- Verified that by default sync option doesn't show up in the hamburger menu in Normal, PT and TOR tabs.
- Verified that Sync is disabled by default and it can be enabled via `brave://flags/#brave-sync`
- Verified that Sync option is shown in the hamburger menu in Normal, PT and TOR tabs when sync is enabled via `brave://flags/#brave-sync`
- Verified that `Sync` should show up in the side menu in `brave://settings` when sync is enabled via `brave://flags/#brave-sync`
