### ISSUE TITLE
Use full resolution of base::TimeDelta in randomized delays for privacy

### ISSUE THREAD

**Issue by riastradh-brave** [brave/brave-browser#8163]
We currently pick a geometrically distributed number of seconds:

```
constexpr uint64_t kAvgDelaySecs = 3 * base::Time::kSecondsPerHour;
void Component::OnPeriodicTimer()
{
  ...
  timer_->SetTimer(brave_base::random::Geometric(kAvgDelaySecs));
}
```

However, we are trying to approximate an exponentially distributed delay on a continuous time scale, on clocks that have much finer resolution than seconds.  Conceivably the jitter of the clocks is small enough, even if network jitter is included, that users could be distinguished by which millisecond (or at least centisecond or decisecond) within a second their randomly delayed events happen on.

We should convert our timers to work in units of base::TimeDelta, not in uint64_t numbers of seconds, as, e.g., base::OneShotTimer already uses:

```
constexpr base::TimeDelta kAvgDelay = base::TimeDelta::FromHours(3);
void Component::OnPeriodicTimer()
{
  ...
  timer_->SetTimer(brave_base::random::ExponentialDelay(kAvgDelay));
}
```

**Comment by tmancey** [comment]
@riastradh-brave I have raised https://github.com/brave/brave-browser/issues/8485 for Ledger and https://github.com/brave/brave-browser/issues/8484 for Brave Ads so that we refactor our code to use `brave_base::random::ExponentialDelay`
