### ISSUE TITLE
Proxy queries to the Mozilla Location Service

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#8167]
brave/devops#2457 will introduce a proxy for the location service.

We need to update our build config to make use of it:
- https://github.com/brave/devops/blob/899db2f2cfc911f040d61262d8ad42eee23063dd/jenkins/jobs/browser/brave-browser-build-android-core.yml#L693
- https://github.com/brave/devops/blob/899db2f2cfc911f040d61262d8ad42eee23063dd/jenkins/jobs/browser/brave-browser-build-linux.yml#L130
- https://github.com/brave/devops/blob/899db2f2cfc911f040d61262d8ad42eee23063dd/jenkins/jobs/browser/brave-browser-build-macos.yml#L138
- https://github.com/brave/devops/blob/899db2f2cfc911f040d61262d8ad42eee23063dd/jenkins/jobs/browser/brave-browser-build-windows-x64.yml#L154
- https://github.com/brave/devops/blob/899db2f2cfc911f040d61262d8ad42eee23063dd/jenkins/jobs/browser/brave-browser-build-windows-x86.yml#L154
- https://github.com/brave/devops/blob/899db2f2cfc911f040d61262d8ad42eee23063dd/jenkins/jobs/browser/test-brave-browser-build-android-core.yml#L694
- https://github.com/brave/devops/blob/899db2f2cfc911f040d61262d8ad42eee23063dd/jenkins/jobs/browser/test-brave-browser-build-linux.yml#L131
- https://github.com/brave/devops/blob/899db2f2cfc911f040d61262d8ad42eee23063dd/jenkins/jobs/browser/test-brave-browser-build-macos.yml#L139
- https://github.com/brave/devops/blob/899db2f2cfc911f040d61262d8ad42eee23063dd/jenkins/jobs/browser/test-brave-browser-build-windows-x64.yml#L155
- https://github.com/brave/devops/blob/899db2f2cfc911f040d61262d8ad42eee23063dd/jenkins/jobs/br-owser/test-brave-browser-build-windows-x86.yml#L155

and then make new builds in all channels and platforms.

**Comment by fmarier** [comment]
Test plan: open https://fmarier.github.io/brave-testing/geolocation.html and verify that location is as accurate as it was in older builds.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.3 x64 Catalina` using the following build:

```
Brave | 1.7.71 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.15.3 (Build 19D76)
```

* Verified the STR outlined via https://github.com/brave/brave-browser/issues/8167#issuecomment-585465660
* ensured that `location.services.mozilla.com` wasn't being used

![Screen Shot 2020-03-24 at 2 46 28 PM](https://user-images.githubusercontent.com/2602313/77472744-c00be000-6dea-11ea-8f49-58fdfdab568e.png)
