### ISSUE TITLE
`claimed_at` db timestamp value resets to zero after sending one time or recurring tip

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8180]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/7297

`claimed_at` db timestamp value resets to zero after sending one time or recurring tip

## Steps to Reproduce

   1. Clean profile 1.4.x launch brave using `brave.exe --rewards=staging=true`
   2. Enable rewards 
   3. Open `publisher_info_db` and check `promotion` shows `claimed_at` value as `0` (expected)
   5. Claim UGP grants in browser
   6. Repeat step 3 and make sure `claimed_at` value shows UGP grants claimed timestamp
   7. Send a one-time tip or recurring tip to a verified pub
   8. Repeat step 3, `claimed_at` value resets to `0`

## Actual result:

**Before claiming UGP grants: Just enable rewards**
![image](https://user-images.githubusercontent.com/38657976/74237741-40bec300-4cfa-11ea-8550-0f284a661d2c.png)
**After claiming UGP grants:**
![image](https://user-images.githubusercontent.com/38657976/74237834-72d02500-4cfa-11ea-9bff-49ecd527d1cb.png)
**After setting one-time or recurring tip**
![image](https://user-images.githubusercontent.com/38657976/74237928-a57a1d80-4cfa-11ea-9d5a-9a013a889d41.png)

## Expected result:
`claimed_at` db timestamp value should not reset to zero after sending a one-time tip or recurring tip

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.4.84 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron @bsclifton

**Comment by btlechowski** [comment]
Unable to reproduce on Ubuntu.

Brave | 1.4.86 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Ubuntu 18.04 LTS

After tipping the `claimed_at`is not set to 0 after tipping or setting monthly tip.

@GeetaSarvadnya make sure you close Brave when checking `publisher_info_db`. And close your DB program when running Brave. The DB program may keep file open and prevent the change to it.

**Comment by GeetaSarvadnya** [comment]
@btlechowski I did close brave and opened DB after every transaction to see the data in DB.

**Comment by kjozwiak** [comment]
Should be able to QA this once we get `1.3.116` which as been started 👍

**Comment by GeetaSarvadnya** [comment]
The issue is reported in 1.4.x. The PR https://github.com/brave/brave-core/pull/4202 is not merged in 13.116 hence moving the issue out of 1.3.x hotfix.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.4.93 Chromium: 80.0.3987.116 (Official Build) (64-bit)
-- | --
Revision | dc00a510e4c2ae25c4d084cc3d946fc782249224-refs/branch-heads/3987@{#917}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description

**Before claiming UGP grants:** 
![image](https://user-images.githubusercontent.com/38657976/74958461-fd1d3500-542e-11ea-9495-bece9ad34825.png)

**After claiming UGP grants:**
![image](https://user-images.githubusercontent.com/38657976/74960165-d4e30580-5431-11ea-91fb-ca6048fabce5.png)

**After setting a one-time or recurring tip**
![image](https://user-images.githubusercontent.com/38657976/74960425-520e7a80-5432-11ea-91a3-c2368286ab05.png)
