### ISSUE TITLE
Do not delete unblinded tokens

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#8181]
Right now we delete unblinded tokens when they are used. To have history we should just marked them as claimed. We need to add new column `spent_at` which should be timestamp and we insert time stamp when token is used. We also need to update query for getting all tokens as we need to return only tokens that don't have `spent_at` column populated.

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc need a small clarification reg https://github.com/brave/brave-core/pull/5017. Description of the issue say `spent_at` should it be `redeemed_at`? Also, I have sent tip of 1BAT to verified pubs in staging env. I could see records of 4 rows, what is each row indicates? 
![image](https://user-images.githubusercontent.com/38657976/83419703-1d538b80-a443-11ea-800d-00de8bc49b26.png)

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya updated issue. 1 BAT = 4 tokens (1 token  = 0.25 BAT)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.10.79 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/5017
![image](https://user-images.githubusercontent.com/38657976/83420964-001fbc80-a445-11ea-8abc-99965adea719.png)
