### ISSUE TITLE
Instructions on site are wrong

### ISSUE THREAD

**Issue by mayeaux** [brave/brave-browser#8182]
https://support.brave.com/hc/en-us/articles/360017903152-How-do-I-reset-Brave-settings-to-default-

^ On this URL it says to reset settings to default you need to go to settings then 'Go to the bottom and click Advanced'. That's actually incorrect, for me on version 1.2.4 it says 'Additional settings' not 'Advanced', was definitely confusing.

**Comment by bsclifton** [comment]
@mayeaux thanks for the report! Will share with team

**Comment by bsclifton** [comment]
@mayeaux text updated! Thanks again 😄

**Comment by mayeaux** [comment]
Hey no problem! You should check out my FOSS YouTube alternative btw if you haven't already. Tell Brendan I'd be happy to take on a sponsor if he's looking to decentralize media sharing on the web :) https://github.com/mayeaux/nodetube Cheers!
