### ISSUE TITLE
Tip Banner and Tweet Template Lack Creator Name

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#8183]
## Description 
Brave may struggle to retrieve publisher names, resulting in no string provided to the Tweet template, and/or the wrong strings being displayed in the tipping banner.

## Steps to Reproduce
1. Navigate to a video on YouTube (e.g. youtube.com/watch?v=SG_gG1j4plo)
2. Open the tipping banner
3. (Optionally, send a tip and open the Tweet template)

## Actual result:

Channel name is not displayed in Tipping banner. Instead, unique channel ID is displayed:

![image](https://user-images.githubusercontent.com/815158/74248999-1a733600-4cae-11ea-91c6-ac2d36a17579.png)

Tweet template lacks channel name as well. Note, the following image was taken while attempting to tip the WIRED YouTube channel:

![image](https://user-images.githubusercontent.com/815158/74249040-2c54d900-4cae-11ea-8f5a-5ad2cfac8894.png)

## Expected result:

Channels are properly identified.

## Reproduces how often: 
Easily

## Brave version (brave://version info)
Brave | 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1909 (Build 18363.592)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No repro on 1.4.80
- Can you reproduce this issue with the dev channel? No repro in 1.5.86
- Can you reproduce this issue with the nightly channel? No repro in 1.6.14

## Miscellaneous Information:
The Rewards Panel properly identifies the channel:

![image](https://user-images.githubusercontent.com/815158/74249515-e3515480-4cae-11ea-82bc-ab5831c6874b.png)

**Comment by jonathansampson** [comment]
Seeing this manifest itself in Tweets:

![image](https://user-images.githubusercontent.com/815158/74613859-2872ed80-50d8-11ea-94f9-8204b7ebe5f8.png)

**Comment by Miyayes** [comment]
I believe this has been resolved. Can file anew if we ever observe it again.
