### ISSUE TITLE
Move `NamedThirdPartyRegistry` initialization of blocking execution path

### ISSUE THREAD

**Issue by AndriusA** [brave/brave-browser#8186]
## Description 

https://github.com/brave/brave-core/pull/4229 implements bandwidth savings prediction using named third parties as one of the signals for the predictive model. Third parties are looked up by domain name in `NamedThirdPartyRegistry`, but `NamedThirdPartyRegistry` is a singleton that loads mappings from JSON on first use, potentially locking up the main thread. 

## Steps to Reproduce

 N/A

## Actual result:

Histogram `Brave.Savings.NamedThirdPartyRegistry.LoadTimeMS` records tame taken for initialization - simple experiment on a powerful desktop shows 4ms spent.

## Expected result:

Loading the bandwidth prediction component should not block request processing

## Reproduces how often: 

Every browser launch

## Brave version (brave://version info)

Current devevlopment, not yet landed

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

**Comment by bsclifton** [comment]
Setting missing milestone to 1.10
