### ISSUE TITLE
Flag to re-enable sync

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#8187]
## Description 
As we temporarily have Brave Sync disabled, we need to provide a flag that we can use to re-enable for internal testing.

## Brave version (brave://version info)
1.3.115

## Version/Channel Information:
Release

**Comment by Gby56** [comment]
oh so Brave Sync has been disabled for now ? Was it announced anywhere ?
I was trying to test this out but it kept crashing Brave after staying too long on "looking for devices"
Then I updated, and brave://sync isn't working, but the "Sync" link in the settings page is still there fyi

**Comment by NejcZdovc** [comment]
@Gby56 you can read more about sync begin disabled here https://community.brave.com/t/brave-sync-temporarily-disabled-on-desktop/106837

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.3.116 Chromium: 80.0.3987.106 (Official Build) (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | Windows 10 OS Version 1803 (Build 17134.1006)


- Verified the test plan from https://github.com/brave/brave-core/pull/4592
- Verified `--disable-sync` flag is appended in command line When the sync is disabled
![image](https://user-images.githubusercontent.com/38657976/74675805-62c4b380-51da-11ea-92ed-f81709383c5b.png)
- Verified `--disable-sync` flag is NOT appended in command line When the sync is enabled
![image](https://user-images.githubusercontent.com/38657976/74675990-f26a6200-51da-11ea-895b-0d12cb4e5c1d.png)
- Verified `--disable-sync` flag is appended in command line When the sync is disabled
![image](https://user-images.githubusercontent.com/38657976/74676099-3e1d0b80-51db-11ea-8f70-f0fb019efe44.png)
