### ISSUE TITLE
Translating in spanish for "close" when closing a tab is wrong

### ISSUE THREAD

**Issue by Kvothe838** [brave/brave-browser#8193]
## Description 
When right clicking on a tab, it shows "Cerca" instead of "Cerrar" for the translation of "Close" to spanish. It's understandable because "close" could also be "cerca" in spanish, but not in this context.

## Steps to Reproduce

   1. Right click on a tab having Brave in spanish
   2. See "Cerca      Ctrl + W" as an option.

## Actual result:
"Cerca" as an option.

## Expected result:
"Cerrar" as an option.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.2.43

- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by rebron** [comment]
Closing. Fixed in the latest 1.5.123

**Comment by rebron** [comment]
<img width="296" alt="Captura de Pantalla 2020-04-06 a la(s) 1 02 15 p  m" src="https://user-images.githubusercontent.com/5951041/78586521-66df7b80-77f0-11ea-9f6a-4c6842d5affc.png">
macOS 1.5.123

@btlechowski when you get a chance can you verify?

**Comment by btlechowski** [comment]
Reproducible on 1.5.12, but not on 1.9.4

Brave | 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

![image](https://user-images.githubusercontent.com/34715963/78605146-4f89a800-785b-11ea-80d1-c4334795c372.png)

Brave | 1.9.4 Chromium: 81.0.4044.83 (Official Build) nightly (64-bit)
-- | --
Revision | 5718ca617723806b9aacfb41108a0d911d1bde74-refs/branch-heads/4044@{#853}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

![image](https://user-images.githubusercontent.com/34715963/78605517-f9693480-785b-11ea-91a9-90ef2ae4a8d0.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

Brave | 1.9.49 Chromium: 81.0.4044.129 (Official Build) dev (64-bits)
-- | --
Revisión | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
Sistema Operativo | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
Normal window tab:
![image](https://user-images.githubusercontent.com/38657976/80711176-8d51b780-8b0d-11ea-8ee4-8404cd509b73.png)
Private window tab:
![image](https://user-images.githubusercontent.com/38657976/80711451-ff2a0100-8b0d-11ea-94d7-24cd86409e3f.png)

Tor Private window tab:
![image](https://user-images.githubusercontent.com/38657976/80711408-ede0f480-8b0d-11ea-832f-327b6004dbd3.png)

Guest window tab:
![image](https://user-images.githubusercontent.com/38657976/80711363-de61ab80-8b0d-11ea-8db7-f2edff8d0627.png)
