### ISSUE TITLE
Youtube turns Brave to black screen/window (worked in Chrome)

### ISSUE THREAD

**Issue by emphasis87** [brave/brave-browser#8194]
## Description 

After clicking on the channel (not subscribed) Brave turns black after the page is loaded (1s), nothing is visible. Sound works, I can also detach the tab but it remains broken. The issue seem to resolve itself after a while of playing, but once I clear cookies it returns back.

## Steps to Reproduce

   1. https://www.youtube.com/channel/UCdlniljY9Zfz990G8WeOosg?_hsenc=p2ANqtz-9hsq2pIu--OhHLnLRqe_830GtUGfa2geZmcwWCd6vFwO_rs7HY5jM_1-UC4v-UOguFTYbRZMBEOKemYZuJwBZ-O12QmrAaDVxBVKb8zKEsZa2iMPU&_hsmi=82373806
   2. Clear cookies if necessary

## Actual result:

Brave is black. The whole window.

## Expected result:

Youtube page.

## Reproduces how often: 

Every time for while, then after cca 30s of playing the sound it fixes itselfs. Once cookies are cleared the issue is back.

## Brave version (brave://version info)

Brave | 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1909 (Build 18363.592)
JavaScript | V8 8.0.426.16
Flash | (Deaktivováno)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
Command Line | "C:\Users\emphasis\AppData\Local\BraveSoftware\Brave-Browser\Application\brave.exe" --profile-directory=Default --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --disable-sync --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,AllowPopupsDuringPageUnload,WebXR,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,VideoPlaybackQuality,WebXrGamepadModule --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service
Executable Path | C:\Users\emphasis\AppData\Local\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\emphasis\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | 5e3a236d-4113a79e

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?

**NO**

- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by emphasis87** [comment]
Since then I have encountered the issue also on facebook, while scrolling the windows turns black. It seems to be connected to displaying certain visual segments.

**Comment by lucyyyyyyy** [comment]
I am also getting this

**Comment by emphasis87** [comment]
The issue seems to manifest when playing video. I noticed it on the site crunchyroll.com as well.
For the record, I have AMD GPU **Radeon NITRO+ RX 5700 XT 8G**, hopefully it isn't driver-related issue.

**Comment by bsclifton** [comment]
@emphasis87 @lucyyyyyyy to test if it might be driver related, can you please try turning off hardware acceleration? If that DOES resolve the issue, you might turn hardware acceleration back on and then share the values from brave://gpu

I do suspect this is driver related as there are no known issues with content. It might be a problem with X264 decoding

**Comment by lucyyyyyyy** [comment]
I would assume it was a hardware acceleration issue, I also have an AMD RX 5700XT, will test when I can. I should mention this only happened on Windows and not on my previous Arch install.

**Comment by lucyyyyyyy** [comment]
OK, disabling hardware acceleration does resolve the issue. Here is brave://gpu


```
Data exported | 2020-02-17T13:08:27.422Z
-- | --
Chrome version | Chrome/80.0.3987.87
Operating system | Windows NT 10.0.17763
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/449cb163497b70dbf98d389f54e38e85d4c59b43/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/449cb163497b70dbf98d389f54e38e85d4c59b43/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | 362168eb695d
2D graphics backend | Skia/80 97c9a95908bc8c7a6794259b35f366a3291e2d0f
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --disable-domain-reliability --disable-features=WebXrGamepadModule,VideoPlaybackQuality,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,WebXR,AutofillServerCommunication --disable-sync --disable-webrtc-apm-in-audio-service --enable-audio-service-sandbox --enable-dom-distiller --enable-features=SimplifyHttpsIndicator,WebUIDarkMode,PasswordImport --extension-content-verification=enforce_strict --extensions-install-verification=enforce --no-pings --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,WebXR,LookalikeUrlNavigationSuggestionsUI,AllowPopupsDuringPageUnload,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,VideoPlaybackQuality,WebXrGamepadModule --flag-switches-begin --load-media-router-component-extension=1 --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator,WebContentsForceDark --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service


```

**Comment by emphasis87** [comment]
Same here, disabling hardware acceleration seems to do the trick.
