### ISSUE TITLE
Cosmetic filtering causes a layout re-flow during page-load

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#8197]
Cosmetic filtering was enabled (behind a flag) with https://github.com/brave/brave-core/pull/4269

When enabled, it detects which potentially-hidden elements contain 1st party content vs 3rd party content. After the determination, 3rd party content is hidden and 1st party content is left alone. This causes a jump of content when elements are hidden some time after the are first displayed.

## Test Plan
0. Enable chrome://flags/#brave-adblock-cosmetic-filtering
1. Visit latimes.com
2. Visit some articles

#### Actual
Content jumps
![cosmetic-jump-brave](https://user-images.githubusercontent.com/741836/74284257-38ee2700-4cd8-11ea-8d57-64aae2abef2b.gif)

#### Expected
Content is already hidden
![cosmetic-jump-chrome](https://user-images.githubusercontent.com/741836/74284277-42778f00-4cd8-11ea-97dc-7a7d0dc8e1ef.gif)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.7.85 Chromium: 80.0.3987.162 (Official Build) dev (64-bit)
-- | --
Revision | f2c5dd6138153bb0658091205bd1a1717f16081a-refs/branch-heads/3987@{#1034}
OS | Windows 10 OS Version 1803 (Build 17134.523)
