### ISSUE TITLE
Brave after update crashing MacOS Mojave

### ISSUE THREAD

**Issue by MariuzM** [brave/brave-browser#8199]
## Description 

After update Brave is crashing cant load the app

## Steps to Reproduce

Open the app

## Actual result:

Crash

## Expected result:
To open

## Reproduces how often: 

All the time

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by MariuzM** [comment]
I have also tried removing all the files that i had on my Mac with Brave that means going into Library folder, but still crashing. Brave team how on earth are you testing your browser?

**Comment by bsclifton** [comment]
@MariuzM what version of Brave are you using? Can you try launching from the command line to see if there is any extra ouput? For example:
```
"/Applications/Brave Browser.app/Contents/MacOS/Brave Browser"
```

**Comment by bsclifton** [comment]
Closing as stale - without info we can't troubleshoot unfortunately ☹️ 

If you have more info, please do re-open this issue and reply back. Thanks! 😄
