### ISSUE TITLE
[Android] Crash when dispatching shields blocked events

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#8200]
## Description 
```
JNI DETECTED ERROR IN APPLICATION: can't call void org.chromium.chrome.browser.preferences.website.BraveShieldsContentSettings.blockedEvent(int, java.lang.String, java.lang.String) on null object
```

## Steps to reproduce 

   1. Open brave and visit any page that would generate blocked events, for example, just visit `github.com`

## Actual result 
Crash with above message. The message could only be seen in static builds, for release builds, just observe crash with a vague message.

## Expected result
No crash.

## Issue reproduces how often 
Every time.
   
## Brave version
nightly, seems to be starting to crash after C80 according to @emerick.

**Comment by srirambv** [comment]
- Verification passed on Samsung Tab A with Android 9.0 running 1.6.24 nightly x64 build
- Verification passed on OnePlus 6T with Android 10 running 1.6.24 nightly x64 build
