### ISSUE TITLE
Partner request: Sliver.tv has rebranded as Theta.tv

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#8201]
## Description 

We announced a partnership with Sliver.tv in July 2019. 
As part of the partnership, Sliver.tv had made Brave their recommended browser. 
There were a few items we had to work on to: 

1. allow for autoplay on sliver.tv in Brave (https://github.com/brave/autoplay-whitelist/issues/15)

and 

2. allow for people to earn their TFuel token while watching streams. (https://github.com/brave/brave-browser/issues/5380)

Sliver.tv has recently been rebranded as https://www.theta.tv/, and they've requested that we apply the same adjustments we made for Sliver.tv for Theta.tv so they can continue to promote Brave to their audience. 

The work/steps required for both requests are in both of the linked issues above, and should (hopefully) be the same, only with the name changed from sliver.tv to theta.tv. 

Any assistance in getting this completed would be greatly appreciated. I can post a separate issue in the autoplay-whitelist repo as well, if that would be helpful. 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
For 1. Allow list for autoplay has been removed completely via https://github.com/brave/brave-browser/issues/8408

For 2. @pes10k There was a name change from Sliver.tv to Theta.tv, so it looks like need an update here: https://github.com/brave/brave-core/commit/7626c3d565b810dfeb8273370578aca19b54b024

**Comment by pes10k** [comment]
@rebron we don't currently have any remaining exceptions for sliver.tv, they're no longer needed because of other fixes (you can see that in the current version of the file you linked to at https://github.com/brave/brave-core/blob/8d5f062c6a53b1d8d699eb57fa3aad310389aa24/common/shield_exceptions.cc).  

So, i think nothing to do here.  Close?

**Comment by rebron** [comment]
Closing. @lukemulks Due to other fixes, Sliver.tv/Theta.tv shouldn't need any exceptions to work properly. 

Thanks for confirming @pes10k
