### ISSUE TITLE
3 consecutive sync updates will result deletion

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#8203]
## Steps to Reproduce

   1.  Go to `chrome://flags/#brave-sync` and enable brave-sync on device A and B
   2.  Sync device A and B
   3. Create folder/url`1` on device A
   4. Rename folder/url `1` to `12` on device B
   5. Rename folder/url `12` to `123` on device A
   6. When device B get UPDATE record, the folder/url will be deleted

## Actual result:

folder/url `123` is deleted

## Expected result:
device B should see folder `123`

## Reproduces how often: 

100%

## Version/Channel Information:

Version 1.6.18 Chromium: 80.0.3987.87 (Developer Build) (64-bit)
- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by darkdh** [comment]
it is removed by
https://chromium-review.googlesource.com/c/chromium/src/+/1871593

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.6.24 Chromium: 80.0.3987.100 (Official Build) nightly (64-bit)
-- | --
Revision | 3f00c26d457663a424865bbef1179f72eec1b9fe-refs/branch-heads/3987@{#864}
OS | Ubuntu 18.04 LTS

Folders:
![image](https://user-images.githubusercontent.com/34715963/74450083-d6369000-4e7d-11ea-806b-247d6199cc00.png)

URLs:
![image](https://user-images.githubusercontent.com/34715963/74453408-a938ac00-4e82-11ea-861e-1793ef40ca60.png)

Experienced 2 issues while testing:
- recreating sync chain can sometimes result in an empty/broken sync chain.
- renaming the same item at the same time on different devices will discard one change.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

Brave | 1.3.116 Chromium: 80.0.3987.106 (Official Build) (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/74753653-7170a080-5296-11ea-94e0-26dfb7cc804f.png)
