### ISSUE TITLE
Scrollbar doesn't appear correctly on brave://settings page due to extra element.

### ISSUE THREAD

**Issue by Lucifer879** [brave/brave-browser#8205]
## Description 

There is an extra element [ toolbar-extra -slot-filled ] & should be removed to fix the scroll bar UI.

![Remove](https://user-images.githubusercontent.com/48880976/74305264-73fa6400-4d85-11ea-99c7-fa25e90643e9.PNG)

Removing that solvesthe problem.

![Solved](https://user-images.githubusercontent.com/48880976/74305294-8b395180-4d85-11ea-8743-d941d98a5d66.PNG)

## Steps to Reproduce

   1. Download v1.3.115 Stable Brave
   2. Open brave://settings
   3. See the top part of Scrollbar.

## Actual result:
Extra element is there.

![ExtraEle](https://user-images.githubusercontent.com/48880976/74304927-685a6d80-4d84-11ea-9a5b-f8a0cda40062.PNG)

## Expected result:
Extra element shouldn't  be there.

![ExtraElement](https://user-images.githubusercontent.com/48880976/74304823-1fa2b480-4d84-11ea-9c62-44801f8a0b92.PNG)

## Reproduces how often: 

Every Time Easily

## Brave version (brave://version info)

Brave | 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1909 (Build 18363.592)

## Version/Channel Information:

Can be produced in every release.

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by rebron** [comment]
cc: @petemill When you get chance can you take a look?

**Comment by bsclifton** [comment]
Confirmed this is still an issue on 1.9.76

**Comment by bsclifton** [comment]
I attempted a fix a while back with https://github.com/brave/brave-core/pull/5842 - but this ended up being fixed by Chromium 84 upgrade
