### ISSUE TITLE
[Question] Why "Continue running background apps when Brave is closed" is enabled by default?

### ISSUE THREAD

**Issue by Lucifer879** [brave/brave-browser#8206]
## Description 

Why Brave have toggled this option ON by default? 
I can understand chrom/ium its data hungry. But Brave is a privacy browser & this option should be disabled by default.

## Steps to Reproduce

   1. Open Brave Version 1.3.115
   2. Go to brave://settings/system
   3. This should be enabled by default.

## Actual result:

Its Enabled

![Enabled](https://user-images.githubusercontent.com/48880976/74306646-19fb9d80-4d89-11ea-94ef-56393b1d424a.PNG)

## Expected result:
Its Disabled

![Disabled](https://user-images.githubusercontent.com/48880976/74306609-0819fa80-4d89-11ea-8fdc-c30ff442b15c.PNG)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1909 (Build 18363.592)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

**Comment by rebron** [comment]
Closing. This is enabled so that we can download updates for Brave when Brave is not running.
