### ISSUE TITLE
Tokens are not successfully unblinded

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#8207]
## Steps to Reproduce

   1. Enable rewards
   2. Close rewards tab and close the browser
   2. Get payment ID and add multiple grants that has legacy flag set to true
   3. Start the browser and immediately open the panel, and reopen it multiple times right one after another

## Actual result:

Balance is not correct (unblinded token table is not populated correctly)

## Expected result:
Balance should be correct (all tokens should be converted)

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.3.x

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Should be able to QA this once we get `1.3.116` which as been started 👍

**Comment by GeetaSarvadnya** [comment]
Verification passed on

Brave | 1.3.116 Chromium: 80.0.3987.106 (Official Build) (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | Windows 10 OS Version 1803 (Build 17134.1006)



- Verified the test plan2 from https://github.com/brave/brave-core/pull/4602
- After verifying the test plan 2, ensured that the following request was made once the browser was restarted:
```
[ REQUEST ]
> url: https://grant.rewards.bravesoftware.com/v1/promotions/reportclobberedclaims
> method: UrlMethod::POST
> content: {"claimIds":["73fee529-42cb-496e-ad8a-89531f58b646"]}
> contentType: application/json; charset=utf-8
[ END REQUEST ]
```
- ensured that both the `promotion` and `promotion_creds` tables were empty in `publisher_info_db ` once the browser was restarted.
