### ISSUE TITLE
Video ads on YouTube do not have Skip button when shields are down - follow up to 2763

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8209]
## Description 
Found while testing #2763 

If you have shields down and view a YouTube video with an ad (that has a skip button), the skip button will not be shown. 

## Steps to Reproduce

   1. Navigate to youtube
   2. put shields down
   3. View a video with an ad that has a skip button (I used https://www.youtube.com/watch?v=Lam-HQoNYKU)

## Actual result:
no skip button on Ad

## Expected result:
skip button on Ad if ad is configured to have it. confirmed in Chrome and Vivaldi that the ad does have a skip button.

## Reproduces how often: 
easily

## Brave version (brave://version info)
Brave | 1.5.86 Chromium: 80.0.3987.87 (Official Build) dev (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.14.6 (Build 18G103)

Brave | 1.4.84 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.14.6 (Build 18G103)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc @brave/legacy_qa @rebron @bsclifton @ryanbr 

This was originally scheduled for fix with 1.4.x - per https://github.com/brave/brave-browser/issues/2763#issuecomment-585081422 from @ryanbr there is another fix waiting.

**Comment by ryanbr** [comment]
Is fixed in https://github.com/brave/brave-core/pull/4603

**Comment by btlechowski** [comment]
Reproduced on 

Brave | 1.4.84 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Ubuntu 18.04 LTS

**Comment by GeetaSarvadnya** [comment]
Reproduced on

Brave | 1.4.86 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.10.80 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

Verified test plan from the description.
Used URL: `https://www.youtube.com/watch?v=CFxRFOOOT44`
Verified `Skip Ads` button is shown on long video ads
Verified clicking `Skip Ads` button will skip the ad

![image](https://user-images.githubusercontent.com/34715963/83595467-5f272380-a562-11ea-8526-acd6f2dbdf8e.png)

**Comment by xameeramir** [comment]
Come on guys! It's still not fixed!

**Comment by Ladrason** [comment]
@xameeramir 

I don't know what setup you're using but it is at least fixed on Windows using the Nightly build.

**Comment by eljuno** [comment]
@xameeramir for Stable Release version it'll be fixed with 1.10.x release.

**Comment by bsclifton** [comment]
1.10 expected to release next week 😄 Thanks for your patience
