### ISSUE TITLE
MaximumEntriesInAdsShownHistory is not respected

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#8213]
Follow up to https://github.com/brave/brave-browser/issues/5863
https://github.com/brave/brave-core/pull/3906/commits/517ce8dfa98b7175d0256c442a287dcfbc6d2002
Max is set to 560, I was able to show 3000 entries

## Steps to Reproduce

   1. Clean profile
   2. Enable rewards
   3. View an ad
   4. Close Brave
   5. copy `generate_ads_history.py` to `[PROFILE]\Default\ads_service\`
   6. Run `generate_ads_history.py`
   7. Run Brave
   8. Open `brave://rewards`
   9. Reload the page few times to shown the generated ads history

[generate_ads_history.zip](https://github.com/brave/brave-browser/files/4194964/generate_ads_history.zip)

## Actual result:

3000 entries are shown

![image](https://user-images.githubusercontent.com/34715963/74376271-17796200-4de2-11ea-9da7-9b2e794afac3.png)
![image](https://user-images.githubusercontent.com/34715963/74376287-1d6f4300-4de2-11ea-9961-8f6586369e20.png)

## Expected result:
Max 560 entries are shown per https://github.com/brave/brave-core/pull/3906/commits/517ce8dfa98b7175d0256c442a287dcfbc6d2002

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.4.85 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

cc @brave/legacy_qa @tmancey @rebron

**Comment by tmancey** [comment]
@btlechowski can you please retest with 559 ads and then viewing 2 ads, to see if the limit is now 590. The code will not remove ads past 590 as the logic is if exceeding the limit after adding an ad we remove the oldest ad.
