### ISSUE TITLE
Android :: Implement "Enabling Sites to Determine Brave" Spec

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#8215]
## Description 

Please implement the "Enabling Sites to Determine Brave" Spec

Search for " "Enabling Sites to Determine Brave" in G-Drive for the Spec

cc @snyderp

**Comment by FatBirdie** [comment]
Please set default to enabled.
Otherwise this feature is more or less useless.

**Comment by bsclifton** [comment]
@FatBirdie we'll share more details as the spec (not public, it's on our G-Drive as mentioned) gets hardened

As it stands, this would be something always available 😄 No need to turn it on

**Comment by bsclifton** [comment]
Should be fixed with https://github.com/brave/brave-core/pull/4721

**Comment by SergeyZhukovsky** [comment]
It works on Android!
![Screenshot_20200306-105254](https://user-images.githubusercontent.com/12011303/76099233-d1568f00-5f98-11ea-8302-a02b0440855e.png)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.110 x64 stable build
![image](https://user-images.githubusercontent.com/17010094/76377098-00da1280-6370-11ea-9cc6-871b9b4900a2.png)
------
Verification passed on Samsung Tab A with Android 9.0 running 1.5.110 x64 stable build
![image](https://user-images.githubusercontent.com/17010094/76377122-0f282e80-6370-11ea-95bb-9c2d34bfdd44.png)
