### ISSUE TITLE
Android ::  Implement Custom Homepage

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#8217]
Please Implement Custom Homepage

Please search G-Drive for "Custom Homepage" for the spec

**Comment by SergeyZhukovsky** [comment]
moving it out from the initial brave-core based release

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm.apk 1.8.93`
- Verified the test plan from https://bravesoftware.slack.com/archives/GAA4017R7/p1588765690060600

**CHP Clean Install**
- ensured SR images are shown in all the tabs
- ensured that SR component is downloaded in brave://component
- ensured ref code is shown in brave://local-state file
- ensured QR code can be scanned using iPhone 
- ensured QR code can be shared
- ensured SR promoCode is selected in `Display-> Appearance -> Theme`
- ensured `New Tab Page` setting  isn't displayed under `Display` settings
- ensured brave default images are shown in all the tabs when `Brave Default` is enabled
- ensured toggle between SR promoCode and `Brave Default` works as expected
- ensured toggle between Dark/Light theme for SR promoCode works as expected
- ensured toggle between Dark/Light theme for `Brave Default` works as expected
- ensured there are no app crash when `Theme` and `Appearance` options are toggled
