### ISSUE TITLE
Desktop :: Implement Custom Homepage

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#8218]
## Description 

Spec: https://docs.google.com/document/d/1DlCHfQXZS3MamKnjCkEHC7yMyJfNObKlgE9X-tJhuEc/edit?ts=5e4f2ece

- [x] Browser side backed - https://github.com/brave/brave-core/pull/4866
- [x] Crx packager - https://github.com/brave/brave-core-crx-packager/pull/97
- [x] Jenkins job - https://github.com/brave/devops/issues/2750
- [x] ~Support re-install super-referrer over existing referrer install - https://github.com/brave/brave-browser/issues/8603~
- [x] NTP WebUI - https://github.com/brave/brave-core/pull/4866
- [x] Add mapping table url to whitelisted url - https://github.com/brave/brave-browser/pull/9084

**Comment by rebron** [comment]
@anthonypkeane @LaurenWags 
Suggested for release notes: `Added support for referral background images and top sites on the new tab page`

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.8.85 Chromium: 81.0.4044.122 (Official Build) (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4866

SR Install - **see issues logged/noted below**
* Confirmed able to get `Technikke` images and top site tiles on each NTP opened
* Confirmed SR component on brave://components
* Confirmed promoCode in brave://local-state
* Confirmed there is a new theme page at brave://settings/themes
* Could not disable SR images on brave://settings/themes (See logged issue below)
<img width="323" alt="Screen Shot 2020-04-28 at 4 49 21 PM" src="https://user-images.githubusercontent.com/28145373/80537634-614dff00-8972-11ea-881c-0fccd234376d.png">
<img width="1188" alt="Screen Shot 2020-04-28 at 4 49 43 PM" src="https://user-images.githubusercontent.com/28145373/80537641-63b05900-8972-11ea-9fa4-0b9bd99fb92a.png">

Non-SR Install - **PASSED**
* Confirmed new install without SR does not have brave://settings/themes page
* Confirmed only standard NTP SI component is available, no SR component

Other scenarios:
1. User has default code/non SR code - **PASSED**
* Confirmed only standard NTP SI component is available, no SR component

2. User has empty code (profile is over 90 days) - **PASSED**
* Confirmed only standard NTP SI component is available, no SR component

Logged issues
- brave://settings/themes doesn't work, can't turn off SR images - logged https://github.com/brave/brave-browser/issues/9515
