### ISSUE TITLE
Rewards claim, human test cannot be passed

### ISSUE THREAD

**Issue by J-Reis** [brave/brave-browser#8219]
## Description 
When trying to claim BAT rewards from ads, the dialogue to "Prove that you are human!" requests that you drag a token over the specified shape. Doing so produces no effect. No error or message of any kind is shown. When released, the semi-transparent drag token simply disappears. There is no way to progress beyond this point in the process.

## Steps to Reproduce
   1. open rewards, either address pop-out menu or brave://rewards
   2. choose "claim"
   3. click and drag orange token to specified shape & release
   … screencap attached (see below)

## Actual result:
Nothing happens. Challenge/response test persists unchanged, no way to progress.

## Expected result:
challenge/response test passes, proceed to claim BAT

## Reproduces how often: 
100%

## Brave version (brave://version info)
Version 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
Debian Stable (10.3)—GNU/Linux

## Version/Channel Information:
installed via apt from Brave provided repo:
	deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ buster main

- Can you reproduce this issue with the current release?
yes
- Can you reproduce this issue with the beta channel?
not attempted
- Can you reproduce this issue with the dev channel?
not attempted
- Can you reproduce this issue with the nightly channel?
not attempted

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
no
- Does the issue resolve itself when disabling Brave Rewards?
axiomatically, no
- Is the issue reproducible on the latest version of Chrome?
not applicable

## Miscellaneous Information:
There are a few posts in the community forum about the rewards CAPTCHA, but they all report receiving a message indicating that they had missed the target: "Almost, but not quite" or some variation thereof. Some seem to have been rectified by ensuring that the page zoom was reset to 100%. I am not seeing any message and adjusting page zoom has no effect.

![Peek 2020-02-12 15-50](https://user-images.githubusercontent.com/23666144/74380674-9f924400-4daf-11ea-9d1c-1f44a3865c4f.gif)

**Comment by Thomas-Negrault** [comment]
Almost the same but I have an error message saying

> Oops, something is wrong. Please try again later.
> Brave Rewards is having an issue. Please try again later.


![Feb-17-2020 21-31-36](https://user-images.githubusercontent.com/6841201/74684775-03ac7200-51cd-11ea-8e85-c55f8c3d8635.gif)

**Comment by NejcZdovc** [comment]
@J-Reis @Thomas-Negrault could you please try again?

**Comment by J-Reis** [comment]
unfortunately I cannot. Along with (or at least at the same time as) the upgrade to 1.3.118, my orange 'claim' button disappeared. So I'd need to wait until next months reward offering come up (March 5th it says).

**Comment by Thomas-Negrault** [comment]
It's ok for me ! 👍

**Comment by NejcZdovc** [comment]
closing as it's resolved

**Comment by dralibak** [comment]
i have been getting and still am getting oops something is wrong please try again later message during proving human claim reward session.  this has been going on 3 weeks now!! everyday I try, i keep updating brave, or even completely reinstalled just now.  still getting the same error!!

HELP FIX.  i can't take the BAT !!
![brave nightly reward](https://user-images.githubusercontent.com/37819428/79639548-882e5900-815a-11ea-972b-b21e45fe1dfa.jpg)
