### ISSUE TITLE
Add NextDNS's TRR to Brave's DoH

### ISSUE THREAD

**Issue by dylangerdaly** [brave/brave-browser#8221]
## Description 
Google and CloudFlare are the only 2 DoH Providers, please add NextDNS

## Brave version (brave://version info)
Desktop (Android defaults to Secure DNS)(?)

## Other Additional Information:
Judging by Mozilla's [Commit](https://hg.mozilla.org/mozilla-central/rev/efc4b4d5834e9298e51025dbb4e88153b94edd31) NextDNS's TRR URL is: `https://trr.dns.nextdns.io/`
## Miscellaneous Information:
Nil

**Comment by rebron** [comment]
cc: @fmarier can you help wiith triaging this one?

**Comment by fmarier** [comment]
We use the same list of DoH providers that Chromium uses: https://source.chromium.org/chromium/chromium/src/+/master:net/dns/public/doh_provider_list.cc?originalUrl=https:%2F%2Fcs.chromium.org%2Fchromium%2Fsrc%2Fnet%2Fdns%2Fpublic%2Fdoh_provider_list.cc

If you'd like NextDNS to get added to that list, here's the process to do that: https://docs.google.com/document/d/128i2YTV2C7T6Gr3I-81zlQ-_Lprnsp24qzy_20Z1Psw/edit

**Comment by abh-oss01** [comment]
> We use the same list of DoH providers that Chromium uses: https://source.chromium.org/chromium/chromium/src/+/master:net/dns/public/doh_provider_list.cc?originalUrl=https:%2F%2Fcs.chromium.org%2Fchromium%2Fsrc%2Fnet%2Fdns%2Fpublic%2Fdoh_provider_list.cc
> 
> If you'd like NextDNS to get added to that list, here's the process to do that: https://docs.google.com/document/d/128i2YTV2C7T6Gr3I-81zlQ-_Lprnsp24qzy_20Z1Psw/edit

Can you elaborate on this in simpler words? I do not seem to understand google's [document](https://docs.google.com/document/d/128i2YTV2C7T6Gr3I-81zlQ-_Lprnsp24qzy_20Z1Psw/edit).

**Comment by fmarier** [comment]
> Can you elaborate on this in simpler words? I do not seem to understand google's [document](https://docs.google.com/document/d/128i2YTV2C7T6Gr3I-81zlQ-_Lprnsp24qzy_20Z1Psw/edit).

What that means is that NextDNS needs to talk to the Chrome team to be added to the list. We don't add DNS providers manually in Brave, we just use the same list as Chromium.

**Comment by abh-oss01** [comment]
Ok, thanks.

**Comment by dylangerdaly** [comment]
It's now possible to add NextDNS's TRR via 'Custom' :+1:, closing this.
