### ISSUE TITLE
Feature request: view/cancel pending tips

### ISSUE THREAD

**Issue by J-Reis** [brave/brave-browser#8222]
I continually receive an "insufficient funds" notification in the rewards panel.

![2020-01-26_08-35-41pm](https://user-images.githubusercontent.com/23666144/74385844-1fbda700-4dba-11ea-8050-cda137cf883a.png)

Apparently I've designated hundreds of BAT to creators that are not set up to accept them … I did have auto-contrib enabled for a time.
**However** none of these pending tips are listed anywhere that I can find.

![2020-01-25_11-36-38am](https://user-images.githubusercontent.com/23666144/74387111-50531000-4dbd-11ea-8e94-9731b7513def.png)

I'd love to be able to view these (to see what they are). Better still would be the ability to cancel them, so i can go back to manually tipping.

**Comment by NejcZdovc** [comment]
they are listed on rewards page (chrome://rewards/)

![image](https://user-images.githubusercontent.com/9574457/75427530-f3bc2d00-5946-11ea-92f5-ac051eb318ed.png)

Just click on `Show all pending contributions` and you can edit the list there

**Comment by J-Reis** [comment]
Man, you guys are quick to close issues, without any kind of confirmation that they are actually resolved … 

"Show all pending contributions" does not show for me. A fact which is mostly demonstrated by the screencap I opened this issue with (though, I could have scrolled down a bit more). Here's a new screencapture of the chrome://rewards page. Please point out where I should be clicking.

![rewards](https://user-images.githubusercontent.com/23666144/75479047-88815380-5964-11ea-84c7-3fa639fd9cfd.png)

**Comment by NejcZdovc** [comment]
@J-Reis hope that this time close is better 😃

**Comment by J-Reis** [comment]
Sounds very promising. I'm not a good enough egg to go and test on nightly, but I won't bother you again unless it persists after your fix hits stable release.
Thanks Nejc!

**Comment by NejcZdovc** [comment]
@J-Reis no worries, ping anytime
