### ISSUE TITLE
eth_signTypedData in brave crypto wallet renders without confirm button

### ISSUE THREAD

**Issue by cloudonshore** [brave/brave-browser#8223]
## Description 
When using JSON RPC for eth_signTypedData in brave crypto wallet the wallet renders the JSON of the message to be signed, but a confirm button isn't rendered. 

<img width="936" alt="Screen Shot 2020-02-12 at 6 37 35 PM" src="https://user-images.githubusercontent.com/1197232/74387969-13404b00-4dc8-11ea-9672-c3607b4cad0e.png">

## Steps to Reproduce

   1. Initialize a wallet in brave metamask with some rinkeby ETH (https://faucet.rinkeby.io/)
   2. Navigate to https://trader.development.airswap.io, and create an order for ETH -> DAI (or ETH to any other token)
   3. When signing, the bottom of the signature gets cut off, and can not be confirmed or cancelled 

## Actual result:
When signing, the bottom of the signature gets cut off, and can not be confirmed or cancelled 

<img width="909" alt="Screen Shot 2020-02-12 at 6 52 05 PM" src="https://user-images.githubusercontent.com/1197232/74388198-cd37b700-4dc8-11ea-9dac-d0c6683a2a10.png">

## Expected result:
The confirm and cancel buttons would be displayed, as happens here when clicking "Click here to sign some typed data": https://weijiekoh.github.io/eip712-signing-demo/index.html

<img width="704" alt="Screen Shot 2020-02-12 at 6 53 21 PM" src="https://user-images.githubusercontent.com/1197232/74388256-f6584780-4dc8-11ea-87ae-0157a046936f.png">

## Reproduces how often: 
Whenever the message is too large to be displayed in the frame, the confirm and cancel buttons get cut off. It seems that the issue is a CSS issue within the wallet that doesn't account for large signTypedData payloads. 

## Brave version (brave://version info)
Brave | 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.14.5 (Build 18F132)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.7.16 Chromium: 80.0.3987.122 (Official Build) nightly (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Linux
Component | `0.1.47`

![image](https://user-images.githubusercontent.com/17010094/75444557-aa410180-5989-11ea-9e53-5bba6c72f855.png)
