### ISSUE TITLE
Incomplete Ads History

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#8224]
## Description 
Brave's Ads History view is showing an incomplete list of ads history.

## Steps to Reproduce
1. Navigate to about:rewards
2. Click '7-day ads history' within Ads panel

## Actual result:
A subset of ads shown over the previous 7 days is displayed

## Expected result:
A complete list of ads shown over the previous 7 days are displayed

## Reproduces how often: 
Always

## Brave version (brave://version info)
1.3.115

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? TBD
- Can you reproduce this issue with the dev channel? TBD
- Can you reproduce this issue with the nightly channel? TBD

## Miscellaneous Information:
While the page displays only a subset of all ads shown over the past 7 days, it does display all ads from the adsHistory in localStorage. The issue appears to be with recording ads shown, and not with displaying the history.

Only 2 ads are listed from 6 days ago. I have ads set to 4/hr, and see them often. Thought I don't recall having seen one in the past few hours.

![image](https://user-images.githubusercontent.com/815158/74388505-2dc2f600-4dc1-11ea-9574-f1869ef9b3cb.png)

**Comment by jonathansampson** [comment]
I just got an ad, but found that it wasn't included in the _7-Day History_.

**Comment by Sh1d0w** [comment]
Hey @jonathansampson do you think the issue I've reported yesterday is related https://github.com/brave/brave-browser/issues/8202

I got no response to it so far, yet a lot of users are experiencing the same since the latest update.

**Comment by jonathansampson** [comment]
@Sh1d0w I don't believe so; see my response [here](https://github.com/brave/brave-browser/issues/8202#issuecomment-585565376).

**Comment by jonathansampson** [comment]
[This user](https://twitter.com/treego14/status/1227828820448772096) also appears to have an incomplete history of ads displayed:

![image](https://user-images.githubusercontent.com/815158/74407042-b4de9100-4df6-11ea-9f0d-4eda836e8b86.png)

**Comment by btlechowski** [comment]
@jonathansampson Could be related to https://github.com/brave/brave-browser/issues/7743, which is fixed in 1.4.x.

In 1.4.x Ads history got a big rewrite and everything works much better.

**Comment by jonathansampson** [comment]
@btlechowski Note, my `adsHistory` state also didn't contain more than the 2 ads shown. Is that known to be related to #7743?

**Comment by tmancey** [comment]
@jonathansampson @Sh1d0w Closing as this issue is fixed by https://github.com/brave/brave-browser/issues/6757 and https://github.com/brave/brave-browser/issues/7869, we are uplifting to 1.4 and 1.5 for when 1.4 is released. Thanks
