### ISSUE TITLE
Critical linking issue for BR

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#8229]
The onboarding BR link is incorrect.
@NejcZdovc

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.3.116 Chromium: 80.0.3987.106 (Official Build) (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | Linux

- Verified clicking on ToS on rewards panel opens a new tab and navigates to `https://basicattentiontoken.org/user-terms-of-service/`
- Verified ToS links on `brave://rewards` page links to `https://basicattentiontoken.org/user-terms-of-service/` and opens in a new tab when clicked
