### ISSUE TITLE
Shields settings are not cleared via clear browsing dialog with non all time range

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#8231]
Shields setting is only cleared with `All time` time range.
and shields settings is not counted.
When user opens clear browsing data dialog, it shows settings count by the sub-label.
that number doesn't include shields setting.
<img width="549" alt="Screen Shot 2020-02-13 at 5 57 11 PM" src="https://user-images.githubusercontent.com/6786187/74417621-5b27a680-4e8a-11ea-8024-b3b09702412b.png">

Steps to reproduce
1. Launch browser with clean profile
2. Load www.brave.com and turn off `Cross-site trackers blocked` via shields panel
3. Launch Clear browsing data dialog via brave://settings/clearBrowserData
4. Check Site Settings have `1 Site` as a label with  `Last hour` time range
5. Push clear button and check label has `None`
6. Load www.brave.com and check `Cross-site trackers blocked` is turned

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.7.71 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

Verified 1 site is shown in `Clear browsing data` under `Site and Shield Settings`
![image](https://user-images.githubusercontent.com/34715963/77528201-d0c16200-6e8d-11ea-961c-166047843990.png)
Verified that shield settings are reverted to default after clearing browsing data for `Last` hour.
Verified that shield settings are reverted to default after clearing browsing data for `All time` hour.
Verified that clearing `Site and Shield Settings` on exit works
Verified that there is 0 entries after clearing `Site and Shield Settings`
![image](https://user-images.githubusercontent.com/34715963/77529399-d0c26180-6e8f-11ea-8ee4-122240b79ce2.png)
