### ISSUE TITLE
[Android] Shields is disabled by default on custom tabs [Follow up to #7636]

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8234]
## Description 
Shields is disabled by default on custom tabs [Follow up to #7636]

## Steps to reproduce 

Issue  1
   1.  Install Beta and Nightly side by side
   2. Set nightly as default browser
   3. Open a custom link in Brave
   4. Shields look disabled
   5. Background the app and bring in focus with custom tab, shields shows enabled

Issue  2
   1.  Install Beta and Nightly side by side
   2. Set nightly as default browser
   3. Open a custom link in Brave
   4. Shields look disabled, clicking on it doesn't open it
   5. Background app and bring to focus, shields looks enabled but still not clickable
   6. Uninstall Beta and repeat from step 3, shields is enabled even though it looks disabled when opened

Issue 3 
   1.  Install Beta and set it as default browser
   2. Install nightly and set it as default browser
   3. Open a custom link in Brave
   4. Shields is not available on custom tab
   5. Open menu shows `Open in browser`
   6. Selecting open in browser opens in nightly 

Issue 4 (reported by @SergeyZhukovsky)
   1. Open Beta and set it as the default browser
   2. Open a link in custom tab from slack or other applications which has some items that would be blocked by shields (ex: open espn.com)
   3. In the custom tab, click on the three-dot menu and select open in browser
   4. Shields panel is not showing anything blocked while things are actually blocked

## Actual result 
Recording for Issue 1:https://bravesoftware.slack.com/archives/CM17J5QMU/p1581590547241100
Screenshot for issue 2: https://bravesoftware.slack.com/archives/CM17J5QMU/p1581590604241400?thread_ts=1581590547.241100&cid=CM17J5QMU
Recording for issue 3: https://bravesoftware.slack.com/archives/CM17J5QMU/p1581592050241800

## Expected result
No shields issue on custom tabs

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes on nightly which has the shields implementation

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version:10
   
## Brave version
1.6.24

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome?  NA

### Additional information

cc: @yrliou @emerick @SergeyZhukovsky

**Comment by yrliou** [comment]
Test plan is specified in https://github.com/brave/brave-core/pull/4838#issue-383984056.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.110 x64 stable build
- Verified all scenarios from issue 


Verification passed on Samsung Tab A with Android 9 running 1.5.110 x64 stable build
- Verified all scenarios from issue
