### ISSUE TITLE
[Android] Password needs to be masked

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8236]
## Description 
Password for qa preference should be masked
## Actual result 
Plain text visible

## Expected result
masked password

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NO
   - Beta build? Yes

## Device details
   - Install type (ARM, x86):ARM
   - Device (Phone, Tablet, Phablet):All
   - Android version:All
   
## Brave version
1.6.24

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm 1.5.110.apk`
