### ISSUE TITLE
[Android] Grant notification cannot be dismissed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8237]
## Description 
Grant notifiation cannot be dismissed

## Steps to reproduce 

   1. Install 1.6.24
   2. Enable rewards on staging
   3. Open BR panel, grant notification keeps coming back after closing

## Actual result 
![grantclaim](https://user-images.githubusercontent.com/17010094/74453733-d0a26f80-4ea8-11ea-9f01-2faac91a5ef4.gif)

## Expected result
Should not show the grant message again when closed. Should only be checked for grants when the panel is opened

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version?No
   - Beta build? yes

## Device details
   - Install type (ARM, x86):ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version:10
   
## Brave version
1.6.24

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by gdregalo** [comment]
Duplicate of https://github.com/brave/brave-browser/issues/8283.
Fixed.
