### ISSUE TITLE
Rate Brave 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#8243]
## Description 

Add the ability for users to easily rate Brave

Some like https://github.com/hotchemi/Android-Rate

@jamesmudgett to help design a nice flow

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.11.98 x64 build
<details>
   <summary>Verified "Rate Brave" settings is shown under "Display" in menu</summary>
   <img width=400 src=https://user-images.githubusercontent.com/17010094/88373596-06208280-cd90-11ea-9b7b-61d0dddc1899.png>
</details>
<details>
   <summary>Verified clicking on "Rate Brave" from menu opens up the modal for feedbackVerified "Rate Brave" settings is shown under "Display" in menu</summary>
   <img width=400 src=https://user-images.githubusercontent.com/17010094/88373366-a1fdbe80-cd8f-11ea-910c-1e5d519050a0.png>
</details>
<details>
   <summary>Verified clicking sad face or neutral face on rate brave modal opens up the feedback input dialog</summary>
   <img width=400 src=https://user-images.githubusercontent.com/17010094/88373613-0b7dcd00-cd90-11ea-89b0-a6feea2dbfe8.png>
</details>
<details>
   <summary>Verified clicking on the happy face shows thankyou message and provides option to Rate on Google Play Store</summary>
   <img width=400 src=https://user-images.githubusercontent.com/17010094/88373671-29e3c880-cd90-11ea-9280-b1a0af758617.png>
</details>
<details>
   <summary>Restart and time duration</summary>
   <ul>
      <li>Verified clicking on Rate switches to PlayStore and opens up Brave listing</li>
      <li>Verified rate brave modal shows up based on specified number of restarts when the time frame is met</li>
      <li>Verified clicking on rate brave manually from settings doesn't affect the specified number of restarts and time duration</li>
      <li>Verified feedback sent via app is captured in backend</li>
   </ul>
</details>
<details>
   <summary>Translated Rate Brave models</summary>
   <table>
      <tr>
         <td>
            <details>
               <summary>Japanese</summary>
               <table>
                  <tr>
                     <td><img width=300 src=https://user-images.githubusercontent.com/17010094/88374150-28ff6680-cd91-11ea-8519-68cdc2a24af5.png></td>
                     <td><img width=300 src=https://user-images.githubusercontent.com/17010094/88374269-62d06d00-cd91-11ea-9375-d1b18c3bd6cf.png></td>
                     <td><img width=300 src=https://user-images.githubusercontent.com/17010094/88374288-69f77b00-cd91-11ea-9bb8-46b2dc9429a2.png></td>
                  </tr>
               </table>
            </details>
         </td>
         <td>
            <details>
               <summary>French</summary>
               <table>
                  <tr>
                     <td><img width=300 src=https://user-images.githubusercontent.com/17010094/88378672-5cde8a00-cd99-11ea-9e2d-bc294842a996.png></td>
                     <td><img width=300 src=https://user-images.githubusercontent.com/17010094/88378641-4c2e1400-cd99-11ea-9363-f6cab25d92ab.png></td>
                     <td><img width=300 src=https://user-images.githubusercontent.com/17010094/88378606-3f112500-cd99-11ea-957d-d232c286ff45.png></td>
                  </tr>
               </table>
            </details>
         </td>
         <td>
            <details>
               <summary>German</summary>
               <table>
                  <tr>
                     <td><img width=300 src=https://user-images.githubusercontent.com/17010094/88378545-2143c000-cd99-11ea-8b04-598d690e211b.png></td>
                     <td><img width=300 src=https://user-images.githubusercontent.com/17010094/88378520-1557fe00-cd99-11ea-9e56-195784c3e09a.png></td>
                     <td><img width=300 src=https://user-images.githubusercontent.com/17010094/88378493-02ddc480-cd99-11ea-8645-baa59f63b927.png></td>
                  </tr>
               </table>
            </details>
         </td>
      </tr>
   </table>
</details>

----------------

Verification passed on Samsung Tab A with Android 10 running 1.11.100 x64 build
<details>
   <summary>Verified "Rate Brave" settings is shown under "Display" in menu</summary>
   <img width=400 src=https://user-images.githubusercontent.com/17010094/88533876-da570400-cffe-11ea-85d2-38d4f928ed40.png>
</details>
<details>
   <summary>Verified clicking on "Rate Brave" from menu opens up the modal for feedbackVerified "Rate Brave" settings is shown under "Display" in menu</summary>
    <img width=400 src=https://user-images.githubusercontent.com/17010094/88533631-851af280-cffe-11ea-880d-7724a161274d.png>
    <img width=400 src=https://user-images.githubusercontent.com/17010094/88533945-fc508680-cffe-11ea-8cd2-071a68624d20.png>
</details>
<details>
   <summary>Verified clicking sad face or neutral face on rate brave modal opens up the feedback input dialog</summary>
   <img width=400 src=https://user-images.githubusercontent.com/17010094/88534022-24d88080-cfff-11ea-9712-a4b53829d7e4.png>
   <img width=400 src=https://user-images.githubusercontent.com/17010094/88534039-2a35cb00-cfff-11ea-9a6d-bb9d0a8d03b4.png>
</details>
<details>
   <summary>Verified clicking on the happy face shows thankyou message and provides option to Rate on Google Play Store</summary>
   <img width=400 src=https://user-images.githubusercontent.com/17010094/88534107-476a9980-cfff-11ea-951d-150c5ba153b6.png>
   <img width=400 src=https://user-images.githubusercontent.com/17010094/88534117-4d607a80-cfff-11ea-8d9c-bd56c4905884.png>
</details>
<details>
   <summary>Restart and time duration</summary>
   <ul>
      <li>Verified clicking on Rate switches to PlayStore and opens up Brave listing</li>
      <li>Verified rate brave modal shows up based on specified number of restarts when the time frame is met</li>
      <li>Verified clicking on rate brave manually from settings doesn't affect the specified number of restarts and time duration</li>
      <li>Verified feedback sent via app is captured in backend</li>
   </ul>
</details>
<details>
   <summary>Translated Rate Brave models</summary>
   <table>
      <tr>
         <td>
            <details>
               <summary>Japanese</summary>
               <table>
                  <tr>
                     <td><img width=300 src=https://user-images.githubusercontent.com/17010094/88533522-5866db00-cffe-11ea-98d0-84cfa430b857.png></td>
                     <td><img width=300 src=https://user-images.githubusercontent.com/17010094/88533509-5270fa00-cffe-11ea-855e-49a9245684ec.png></td>
                     <td><img width=300 src=https://user-images.githubusercontent.com/17010094/88533487-4be28280-cffe-11ea-8b27-dfd4fe891578.png></td>
                  </tr>
               </table>
            </details>
         </td>
         <td>
            <details>
               <summary>French</summary>
               <table>
                  <tr>
                     <td><img width=300 src=https://user-images.githubusercontent.com/17010094/88533375-235a8880-cffe-11ea-943f-0053b4a25c57.png></td>
                     <td><img width=300 src=https://user-images.githubusercontent.com/17010094/88533360-19388a00-cffe-11ea-92e4-ded6b50591fa.png></td>
                     <td><img width=300 src=https://user-images.githubusercontent.com/17010094/88533345-1178e580-cffe-11ea-8aa3-d725b2c1a58c.png></td>
                  </tr>
               </table>
            </details>
         </td>
         <td>
            <details>
               <summary>German</summary>
               <table>
                  <tr>
                     <td><img width=300 src=https://user-images.githubusercontent.com/17010094/88533422-38371c00-cffe-11ea-82c5-fc7791dde346.png></td>
                     <td><img width=300 src=https://user-images.githubusercontent.com/17010094/88533409-34a39500-cffe-11ea-9a7d-7353eb362525.png></td>
                     <td><img width=300 src=https://user-images.githubusercontent.com/17010094/88533398-31100e00-cffe-11ea-8bed-566a54d85afd.png></td>
                  </tr>
               </table>
            </details>
         </td>
      </tr>
   </table>
</details>
