### ISSUE TITLE
Stats text need to have more contrast with background images for better visibilty

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8250]
## Description 

Stats text need to have more contrast with background images for better visibilty

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/74498031-518f5480-4f05-11ea-8612-3d8ba9d085c3.png)

## Expected result:
Better visibility of text on images

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.6.24 Chromium: 80.0.3987.100 (Official Build) nightly (64-bit)
-- | --
Revision | 3f00c26d457663a424865bbef1179f72eec1b9fe-refs/branch-heads/3987@{#864}
OS | macOS Version 10.15.1 (Build 19B88)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? May be
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @GeetaSarvadnya @btlechowski  to check on other platforms as well

**Comment by srirambv** [comment]
Issue is worse on SI and when hovered over stats 
![image](https://user-images.githubusercontent.com/17010094/74500800-19404400-4f0e-11ea-891e-48d94b9cf31a.png)

**Comment by bsclifton** [comment]
@bradleyrichter @karenkliu can you advise a color change that would make sense for this? Also- `Estimated Bandwidth Saved` is new- does that look OK?

**Comment by rebron** [comment]
@srirambv @bsclifton We need to hide `Estimated bandwidth saved` for desktop as this stat will be used on mobile to replace `HTTPS Upgrades` on mobile.

@srirambv I'm going to ahead and rename this issue.

**Comment by rebron** [comment]
Actually, I'll file a separate issue and close this one out as invalid.

This is the issue that added the bandwidth stat.
https://github.com/brave/brave-browser/issues/7783

**Comment by rebron** [comment]
Related: https://github.com/brave/brave-browser/issues/8250 Still in discussion if bandwidth makes sense and replaces `HTTPS Upgrades` or if it's a different stat altogether that replaces `HTTPS Upgrades`. Net of it is we'll only have three stats to show on NTP, not four.

**Comment by srirambv** [comment]
@rebron  the issue was for Text contrast for Estimated time saved and not for `Estimated Bandwidth Saved`. The font contrast still needs to be fixed so reopening it as `Estimated Bandwidth Saved ` will be logged separately

**Comment by rebron** [comment]
@srirambv The new wallpapers seem to have addressed the text contrast issue? 
Not sure if we have more to do here. 

cc: @karenkliu in case you had other thoughts.

<img width="1274" alt="Screen Shot 2020-04-17 at 8 25 13 AM" src="https://user-images.githubusercontent.com/5951041/79585708-0b7d7b00-8085-11ea-95a4-24f1630ad6a5.png">

**Comment by karenkliu** [comment]
@rebron This issue should have been fixed with https://github.com/brave/brave-browser/issues/8256

We still have this issue open to replace HTTPS Upgrades with Bandwidth Saved but there should not be any text legibility issues with that either https://github.com/brave/brave-browser/issues/8969#event-3189101971

**Comment by rebron** [comment]
Closing. Fixed with #8969
