### ISSUE TITLE
Impossible to resolve claim captcha

### ISSUE THREAD

**Issue by wiim23** [brave/brave-browser#8255]
Hi all,
I have a problem to claim my rewards...
When i click on claim, i must resolve captcha "place bat logo on square" for example.
When i drag it on the good figure, each time, i have a wrong result... and, after some tries, "Oops, something is wrong. Please try again later."
I have two months to claim.... and brave is up to date.
Resolution of my pc : 3840x2160
zoom on windows : 250%
No zoom on brave.
No error on console dev tools.
Any help?

**Comment by jeandat** [comment]
Same thing here. A lot of claims are waiting (didn't knew I had to do it manually) but they all fail.

**Comment by nelsonkyshin** [comment]
Same here. Can't claim any rewards

**Comment by bsclifton** [comment]
cc: @NejcZdovc

**Comment by NejcZdovc** [comment]
closing as dupe of https://github.com/brave/brave-browser/issues/8277
