### ISSUE TITLE
Hide Estimated Bandwidth Stat on NTP on desktop

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#8256]
## Description 
Hide `Estimated Bandwidth` stat on NTP for desktop. This stat will be used to replace `HTTPS Upgrades` on mobile but not on Desktop.

## Actual result:
![74498031-518f5480-4f05-11ea-8612-3d8ba9d085c3](https://user-images.githubusercontent.com/5951041/74566822-36ced700-4f29-11ea-805f-1650df6b9cc5.png)

## Expected result:
<img width="1341" alt="Screen Shot 2020-02-14 at 12 55 20 PM" src="https://user-images.githubusercontent.com/5951041/74566850-46e6b680-4f29-11ea-83a5-a551abc89eb8.png">

## Version/Channel Information:

- Can you reproduce this issue with the current release? No.
- Can you reproduce this issue with the beta channel? No.
- Can you reproduce this issue with the dev channel? No.
- Can you reproduce this issue with the nightly channel? Yes. 1.6.x

**Comment by bsclifton** [comment]
Do we want to hide this? I can understand only wanting to see three

Whatever the resolution, we'll need to make sure the gray (which is low contrast and almost disappears) is not used

**Comment by kjozwiak** [comment]
If this was accidentally added into desktop and only belongs on Android, it should be removed from every channel. We shouldn't keep this visible on `Nightly`, `Dev` and `Beta` but not include it in the `Release` channel. If it doesn't belong on desktop, it needs too removed everywhere.

**Comment by rebron** [comment]
cc: @AndriusA Can we get the Bandwidth stat hidden? At minimum, we don't need this stat for `release` channel but not sure we need this for any other channels either as @kjozwiak mentioned. Sounds like you're all good for android-core though. cc: @anthonypkeane

**Comment by anthonypkeane** [comment]
@karenkliu can you please confirm a design for "Data Saved" on Android and post it here?
Thank you

**Comment by bsclifton** [comment]
If we remove for part of desktop, let's remove for all of desktop 😄 Will update issue to reflect that

**Comment by karenkliu** [comment]
> @karenkliu can you please confirm a design for "Data Saved" on Android and post it here?
> Thank you

@anthonypkeane This issue is just to remove the "Data Saved" state on desktop

**Comment by AndriusA** [comment]
> cc: @AndriusA Can we get the Bandwidth stat hidden? At minimum, we don't need this stat for `release` channel but not sure we need this for any other channels either as @kjozwiak mentioned. Sounds like you're all good for android-core though. cc: @anthonypkeane

I'm not an impartial judge for whether to keep or remove - I obviously like it, but can remove if instructed

**Comment by bsclifton** [comment]
@AndriusA let's remove - but only for Desktop 😄 As Android Core is now using this code-base, you should be able to test for Android and only use in that instance

**Comment by srirambv** [comment]
Removed `OS/Androird` label. @anthonypkeane please log a new issue for Android if it requires new design.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.7.70 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Ubuntu 18.04 LTS

Estimated Bandwidth stat on NTP is hidden

![image](https://user-images.githubusercontent.com/34715963/77381966-67532d80-6d7f-11ea-9687-5a053faf53a3.png)
