### ISSUE TITLE
Can't update Brave browser on CentOS 8

### ISSUE THREAD

**Issue by kirillt** [brave/brave-browser#8258]
## Description 
I have installed Brave browser on my CentOS 8.
I am trying to update it but there is an issue with public key.

## Steps to Reproduce
```
sudo dnf install dnf-plugins-core
sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
sudo dnf install brave-browser
```
## Actual result:
```
[kirill@lenovo ~]$ sudo dnf install brave-browser
...
Downloading Packages:
[SKIPPED] brave-browser-1.3.115-1.x86_64.rpm: Already downloaded                                                                                             
warning: /var/cache/dnf/brave-browser-rpm-release.s3.brave.com_x86_64_-d55d330619c02b48/packages/brave-browser-1.3.115-1.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 82d3dc6c: NOKEY
Public key for brave-browser-1.3.115-1.x86_64.rpm is not installed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
```
## Miscellaneous Information:
```
[kirill@lenovo ~]$ dnf repolist
...
brave-browser-rpm-release.s3.brave.com_x86_64_          created by dnf config-manager from https://brave-browser-rpm-release.s3.brave.com/x86_64/          37
```

**Comment by bsclifton** [comment]
cc: @mbacchi @bkero @fmarier

**Comment by fmarier** [comment]
I suspect your machine failed to update before our signing key expired. What I suggest is that you uninstall the existing Brave key and then reinstall it.

1. Start by checking which key is installed:

        $ sudo rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'
        ...
        gpg-pubkey-c2d4e821-5e22514c	Brave Software <support@brave.com> public key

2. Remove the key:

        $ sudo rpm -e gpg-pubkey-c2d4e821-5e22514c
3. Re-add the key:

       $ sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

**Comment by kirillt** [comment]
Thank you @fmarier ! Now it is updated successfully.

They key was the following:
```
[kirill@lenovo ~]$ sudo rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n' | grep Brave
gpg-pubkey-c2d4e821-5d13a788	gpg(Brave Software <support@brave.com>)
```
