### ISSUE TITLE
Rewards settings page on android-core has a number of issues. 

### ISSUE THREAD

**Issue by gdregalo** [brave/brave-browser#8259]
## Description 
1. Claiming a promotion doesn't work (both ugp and ads).
1.1. Once it works please test scenario with multiple claims
(similar problem in tabs repo: https://github.com/brave/brave-browser/issues/7760). 
2. `Tips Settings:  Enable content-level tips on these sites` is not available on Android yet. It has to be removed. 
3. Setting page doesn't have info on monthly tips. There is no way to remove a monthly-tip for a publisher.
4. AC "Show all" dialog has elements with text sliding out of  borders.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by gdregalo** [comment]
Item #4.
![Screenshot_20200214-165912](https://user-images.githubusercontent.com/37560650/74571875-47447900-4f4c-11ea-937d-5729afaf5c1f.jpg)

**Comment by gdregalo** [comment]
@NejcZdovc  plase assign someone with web expertise to help with this.
cc: @SergeyZhukovsky @samartnik

**Comment by NejcZdovc** [comment]
https://github.com/brave/brave-core/pull/4696 fixed everything except of #1. @gdregalo @ryanml could you please create new issue for it so that we don't loose track of it

**Comment by gdregalo** [comment]
@NejcZdovc @ryanml @SergeyZhukovsky 
Opened a new issue and gave it a P1 priority: https://github.com/brave/brave-browser/issues/8367.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Andriod 10 running 1.5.117 x64 stable build
- Verified able claim UGP and Ads grant both via BR panel and rewards page
- Verified no setting for content level tipping 
![image](https://user-images.githubusercontent.com/17010094/77667841-b7f99f00-6fa8-11ea-8453-d3c1a9732a59.png)
- Verified rewards page has a separate section for monthly contributions(tips) 
![image](https://user-images.githubusercontent.com/17010094/77667931-d069b980-6fa8-11ea-8ae2-e3f2dfbca5db.png)
- Verified "Show all" dialog elements are not overflowing 
![image](https://user-images.githubusercontent.com/17010094/77667874-c0ea7080-6fa8-11ea-8e79-608e81be142d.png)
![image](https://user-images.githubusercontent.com/17010094/77667853-bc25bc80-6fa8-11ea-9827-dc36c6da4084.png)
------------
Verification passed on OnePlus 6T with Andriod 10 running 1.5.117 x64 stable build
- Verified able claim UGP and Ads grant both via BR panel and rewards page
- Verified no setting for content level tipping 
![image](https://user-images.githubusercontent.com/17010094/77668136-07d86600-6fa9-11ea-84de-37862c3efae0.png)
- Verified rewards page has a separate section for monthly contributions(tips)
![image](https://user-images.githubusercontent.com/17010094/77668011-e5464d00-6fa8-11ea-8d1e-c354907d5a0d.png) 
- Verified "Show all" dialog elements are not overflowing 
![image](https://user-images.githubusercontent.com/17010094/77668060-f3946900-6fa8-11ea-9d43-4f732a13b2a9.png)
![image](https://user-images.githubusercontent.com/17010094/77668047-eecfb500-6fa8-11ea-802f-0cfafadc04a0.png)
