### ISSUE TITLE
Remove version mismatch check in both b-b and b-c Jenkinsfiles

### ISSUE THREAD

**Issue by mbacchi** [brave/brave-browser#8260]
The version check was used to validate that the brave-core and brave-browser branches in CI matched. It is requested that we remove it because it rarely catches legitimate errors between the two repositories and causes many more failures that require rebases than are necessary.

In brave-browser the section to remove is [here](https://github.com/brave/brave-browser/blob/master/Jenkinsfile#L884-L895).

In brave-core the section is [here](https://github.com/brave/brave-core/blob/master/Jenkinsfile#L146-L149).

**Comment by bridiver** [comment]
this is mainly a problem for PR builder, we can leave it for release channel builds
