### ISSUE TITLE
Twitter tipping success/share tweet: Twitter handle displays as a string of numbers in tweet. 

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#8265]
## Description 

I was going through the process of tweeting that I had tipped a Twitter creator, and noticed that instead of the twitter handle for the creator displaying the twitter handle as expected, instead the handle was populated by a string of numbers. 

Screenshots below show the Twitter Creator w/the proper handle, and what the "I've just tipped" Tweet populated the handle with. 
![Screenshot from 2020-02-15 08-31-46](https://user-images.githubusercontent.com/8979240/74591693-eb6f0400-4fce-11ea-9d40-5befc9e045f9.png)
![Screenshot from 2020-02-15 08-31-17](https://user-images.githubusercontent.com/8979240/74591695-eca03100-4fce-11ea-830e-874201c1440e.png)

## Steps to Reproduce

   1. Tip someone on Twitter
   2. Click the button in the rewards panel to tweet that you've tipped the creator
   3. Observe the handle replaced with a string of numbers. 

## Expected result:
Should display the Twitter handle

## Reproduces how often: 

Have not attempted more than once at this point. 

## Brave version (brave://version info)

Brave | 1.5.91 Chromium: 80.0.3987.100 (Official Build) dev (64-bit)
-- | --
Revision | 3f00c26d457663a424865bbef1179f72eec1b9fe-refs/branch-heads/3987@{#864}

## Version/Channel Information:

- Can you reproduce this issue with the current release? TBD
- Can you reproduce this issue with the beta channel? TBD
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? TBD

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
cc: @NejcZdovc @jsecretan

**Comment by rebron** [comment]
cc: @emerick

**Comment by rebron** [comment]
Looks like this only effecting certain publishers. Tested on Khan Academy and chess.com and it looks like it's working properly there.

**Comment by emerick** [comment]
That's weird, it grabbed the Tweet ID and used that instead of the name. We made several changes to the Twitter implementation recently in nightly. None were explicitly to address this, but it would make sense to retest first to make sure this is still happening. I tried tipping a few tweets to this user just now and wasn't able to repro FWIW.

**Comment by jonathansampson** [comment]
I believe @w0ts0n just ran into this too.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.45 Chromium: 86.0.4240.99 (Official Build) dev (x86_64)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Verified STR from description both when tipping via in-line tip button and tipping from the panel.

Tipped a verified and non-verified twitter publisher (using staging env). Confirmed canned tweet showed publisher name as expected.

<details>
<summary>Screenshots</summary>
Original publisher from description (not verified on staging env) - twitter.com/queentatiana:
<img width="632" alt="Screen Shot 2020-10-21 at 1 55 27 PM" src="https://user-images.githubusercontent.com/28145373/96759069-8e212300-13a5-11eb-89a2-048a15c32751.png">
<img width="617" alt="Screen Shot 2020-10-21 at 1 56 20 PM" src="https://user-images.githubusercontent.com/28145373/96759075-8eb9b980-13a5-11eb-8ee0-abda37622e3a.png">

Verified on staging publisher - twitter.com/emerick:
<img width="632" alt="Screen Shot 2020-10-21 at 1 56 50 PM" src="https://user-images.githubusercontent.com/28145373/96759084-911c1380-13a5-11eb-99ac-be305137a548.png">
<img width="619" alt="Screen Shot 2020-10-21 at 1 57 18 PM" src="https://user-images.githubusercontent.com/28145373/96759088-91b4aa00-13a5-11eb-9314-7a81fefef92a.png">

</details>

**Comment by jonathansampson** [comment]
This happened to me just now in v1.21.65 (presently Brave Beta):

> ![image](https://user-images.githubusercontent.com/815158/109101269-0a2cce00-76ec-11eb-8cb4-87daa0763ecf.png)

From https://twitter.com/kentcdodds/status/1364736650555756544, I scrolled down to the following and clicked _Tip_:

> ![image](https://user-images.githubusercontent.com/815158/109101409-3fd1b700-76ec-11eb-835b-c50dc017da1e.png)

The tipping banner did not show any issue with displaying the publisher's username:

> ![image](https://user-images.githubusercontent.com/815158/109101464-5d068580-76ec-11eb-8752-fa0f45c489ab.png)

**Comment by jonathansampson** [comment]
Still appears to be an issue. Encountered it today, repeatedly in version 1.34.80.

Steps:

1. Visit https://twitter.com/elguilhermee/status/1480608161702817793
2. Begin tipping process via ⟁ icon to the right of the address bar.
 a. If the rewards panel hasn't yet loaded the publisher name (showing twitter.com instead), try again in a few seconds.
3. Click _Send Tip_
4. Select amount
5. Click _Send Tip_
6. Click _Tweet about your support_

![image](https://user-images.githubusercontent.com/815158/148828011-bfc7c831-3d82-4b69-bf9b-5c5494208656.png)

![image](https://user-images.githubusercontent.com/815158/148828098-d88e8d15-8e76-4ede-817e-b25ec91ed214.png)

![image](https://user-images.githubusercontent.com/815158/148828170-c408d473-8f27-4684-9370-a13e9a30a06f.png)


![image](https://user-images.githubusercontent.com/815158/148827270-48e5c5ae-18c1-4c0c-bfb6-e4f4bab641b6.png)
