### ISSUE TITLE
Why is Brave not using video decoder

### ISSUE THREAD

**Issue by SrdjanKalaba** [brave/brave-browser#8268]
If you look at task manager while the video is playing you will see that your CPU and GPU 3D-engine are working harder but it is much better to use GPU video decoder engine instead.

**Comment by bsclifton** [comment]
@SrdjanKalaba do you have hardware acceleration enabled? Please visit brave://gpu and share the results for what you see there (screenshot or copying the text under `Graphics Feature Status` would work)

**Comment by SrdjanKalaba** [comment]
![Annotation 2020-02-17 195557](https://user-images.githubusercontent.com/54671367/74679960-8f1f0680-51bf-11ea-838b-5b5a08ff7ec6.png)

**Comment by rebron** [comment]
@SrdjanKalaba Are you still having issues with 1.7.92? And if you have Chrome installed, are you seeing the same behavior?

**Comment by bsclifton** [comment]
Closing as there hasn't been an update. Usually, anything disabled will be showing under `Problems Detected` in brave://gpu
