### ISSUE TITLE
Default Variation on Windows and Android

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#8272]
## Description 
_Field Trials_ are, AFAIK, disabled in Brave. That said, Brave on Windows and Android still enumerate a single variation when you visit `about:version`. This variation appears to be a fallback sampling trial, as [found here](https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/chrome_browser_field_trials.cc;l=41-48;drc=c945e1ceb5725582cc851cb0b4b72ca8ca37ea8d;bpv=1;bpt=1):

```cpp
// Create a field trial to control metrics/crash sampling for Stable on
// Windows/Android if no variations seed was applied.
void CreateFallbackSamplingTrialIfNeeded(base::FeatureList* feature_list) {
#if defined(OS_WIN) || defined(OS_ANDROID)
    ChromeMetricsServicesManagerClient::CreateFallbackSamplingTrial(
        chrome::GetChannel(), feature_list);
#endif  // defined(OS_WIN) || defined(OS_ANDROID)
}
```

## Steps to Reproduce
1. Visit `about:version`
2. Note _variations_

## Actual result:
`5e3a236d-4113a79e` is present in the Stable release:
`5e3a236d-59e286d0` is present in all other builds:

## Expected result:
Unsure, but our options are:
1) Variation should be removed
2) macOS should be included
3) We do nothing, and leave as-is

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by bsclifton** [comment]
cc: @bridiver

**Comment by jumde** [comment]
@bsclifton @bbondy - Android build is in progress, will try to wrap this up today.

**Comment by bsclifton** [comment]
Closing as stale - we now have Griffin to handle our own variations. Those should be the only ones showing up
