### ISSUE TITLE
[feature request] Use gpg for encryption on Sync, master password, etc

### ISSUE THREAD

**Issue by eloyesp** [brave/brave-browser#8273]
There were a GPG feature request before to [integrate Mailvelope][1] in the browser, and I think that it could be a good addition, but I think that the main issue is the integration of GPG on all encryption related stuff.

For example, passwords are stored encrypted when there is a master password, but that does not relay on GPG for encryption, making it duplicate that functionality. The same happens on Sync, as bookmarks are encrypted and decrypted with a password.

I would like to use of GPG for everything, allowing to use a unique passphrase for everything instead of having to remember multiple passphrase or having to manually type the password each time. GPG is already available on every platform (including android).

As far as I understand, most encryption code is inherited from Chromiun, and I think that depending on GnuPG makes much more sense.

**Comment by bsclifton** [comment]
cc: @diracdeltas @fmarier @jumde @riastradh-brave

**Comment by darkd3vil89** [comment]
Agreed, as long imaa as the encryptionalogorithm is at least on par what we use. Irmw ('preferably even sronger/safeer) and if it simultaneously makes the wholen thing more user friendly I an all for!! I love Brave m. Really the first actual honest an reliable browser in many many years * let it only gets better' and not slowly follow the others*

**Comment by fmarier** [comment]
We are currently working on migrating from our existing custom Sync system to something that is much closer to what is already built into Chromium, though with most of the same privacy properties as before (e.g. end-to-end encryption, Brave cannot see any of the Sync data sitting on servers).

If we were to base this on GPG instead, it would be a significant departure from the Sync implementation in Chromium and would likely be very expensive to maintain in the long run. Also, it would be tricky to get all of the details right and ensure that we have a secure system.

I can appreciate that it would be very convenient for GPG users like you and I, and when it's not too costly, we are happy to accommodate expert use cases. In this case though, it would be touching security-critical and fairly complex portions of the codebase, so we would be taking on a significant risk / maintenance effort.

**Comment by eloyesp** [comment]
@fmarier I understand your points, and those are valid points, but trusting "security-critical on fairly complex portions of the codebase [implementations]" on google developers doesn't seems to be a good security practice neither. This could be a good first step, but in the long run, depending on GPG for that seems like a very good practice.

To accommodate defaults for non-expert users, you could even embed GPG in the code and generate keys by default (so non expert users will not need to install that while expert users could use the system GPG).

On the other hand, if you are thinking on reusing most of the chromiun code, you could touch the endpoints of the sync (so chromiun code only touches encrypted data):

```
[UI code] <-> [GPGadapter] <-> [chromiun code] <-> [sync servers] <-> [chromiun code] <-> [GPGadapter] <-> [UI code]
```

With that you can reuse most of the current code and you are not trusting servers nor chromiun sync code _and_ allowing experts to use their keys should also be easy.

Does it makes sense?

**Comment by eloyesp** [comment]
Just to make the idea clear, the GPG adapter should translate real bookmarks and passwords to encrypted bookmarks and passwords that look like real ones (so current sync code does work transparently).

So a bookmark like "https://brave.com" could be stored as "https://asqoionxivno.crypt", and those bookmarks are stored on disk, synced between browsers, etc.

If there is any security vulnerability on the server or on the "security-critical and fairly complex portions of the codebase" that you are re-using, it can now how many bookmarks you have, but nothing else.
