### ISSUE TITLE
Brave on desktop randomly crashes

### ISSUE THREAD

**Issue by pwittchen** [brave/brave-browser#8274]
Hi,

I'm using Brave on desktop from some time and recently it started randomly crashing. Previously, it worked perfectly fine. It started happening a few days ago. By crashing I mean, favicon is turning into error icon and website is blank. It's quite annoying. It happens randomly for different websites at different time. I tried to clean browser data, history, etc. but it didn't help.

My setup:
- Brave version: Version 1.1.21 Chromium: 79.0.3945.79 (Official Build) unknown (64-bit)
- OS: Arch Linux x86_64, kernel 5.5.4-arch1-1
- WM: i3WM

I'm looking forward to your help or fixing this issue.

Regards,
Piotr

**Comment by bsclifton** [comment]
@pwittchen is there a newer version of Brave available for Arch Linux? That version is behind a bit. We've fixed several crashes for sure and have an updated Chromium in the latest version (`1.3.115`)

**Comment by pwittchen** [comment]
I was using `brave-bin` package from aur. It seems to be outdated. I'll try other packages which seems more up to date (has newer versions).

You can check them here:
https://aur.archlinux.org/packages/?O=0&K=brave

**Comment by pwittchen** [comment]
Ok, I installed `brave-nightly-bin`, which has the latest release version number.
Version 1.6.35 Chromium: 80.0.3987.106 (Official Build) unknown (64-bit).

I'll use it and see if this issue will happen in the future, but for now, I'm closing it.
