### ISSUE TITLE
Brave rewards claim broken

### ISSUE THREAD

**Issue by serp777** [brave/brave-browser#8277]
## Description 
Attempting to claim brave rewards results in the following error message:

"Brave Rewards is having an issue. Please try again later."

## Steps to Reproduce
Click on "CLAIM" in the brave rewards area

## Actual result:

Oops, something is wrong. Please try again later.
Brave Rewards is having an issue. Please try again later.

## Expected result:

Funds update in the wallet. 

## Reproduces how often: 
Reproduces every time no matter what, 

## Brave version (brave://version info)
Version 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)

Also tried latest nightly builds, dev builds, and beta builds.

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Yes
- Can you reproduce this issue with the dev channel?
Yes
- Can you reproduce this issue with the nightly channel?
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No.
- Does the issue resolve itself when disabling Brave Rewards?
The issue is with brave rewards.
- Is the issue reproducible on the latest version of Chrome? 
N/A

## Miscellaneous Information:
Attempted fixes:
1. Try a variety of different builds.
2. Reconnect uphold.
3. Clear browser of all cache.
4. Fresh reinstall.
5. Try a different computer.
6. Try claiming through a VPN.
7. Disable and re enable rewards.
8.  Restart computer.
9. Retry everyday over the course of a week.

Many people are experiencing this issue:

https://www.reddit.com/r/brave_browser/comments/f3obcj/problem_claiming_rewards/

**Comment by bsclifton** [comment]
cc: @NejcZdovc

**Comment by NejcZdovc** [comment]
@bsclifton this is expected as claim is disabled right now. We will re-enable it when we release hotfix this week
