### ISSUE TITLE
armhf.deb for Pinebook Pro please

### ISSUE THREAD

**Issue by pinebookfan** [brave/brave-browser#8280]
Please create a armhf.deb for the Pinebook Pro for Debian 9 Stretch

Thanx!

**Comment by bsclifton** [comment]
Hi @pinebookfan 

I'm not sure what you're asking for. Can you please explain what armhf.deb is and what you're looking for?

As there isn't any information here, I'll close. But please re-open if you have more infomation

**Comment by bsclifton** [comment]
Thanks for creating https://github.com/brave/brave-browser/issues/8292 with more information 😄
