### ISSUE TITLE
"DevTools failed to parse SourceMap" warning

### ISSUE THREAD

**Issue by Nuc1eoN** [brave/brave-browser#8281]
In Brave v1.3.115 if you open any page, go to the Inspector and open the console, there are the following warnings:

```
DevTools failed to parse SourceMap: chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/sourcemaps/contentscript.js.map
DevTools failed to parse SourceMap: chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/sourcemaps/inpage.js.map
```

At first I thought it's a website issue but it really seems to be tied to the brave browser.

**Comment by minaiism** [comment]
Same issue here :(

**Comment by EugenioAntonioBonanno** [comment]
I am experiencing the same issue. I thought it might be an extension problem but I've checked all my extensions and there are no issues. I am running Brave for Linux on Ubuntu.

**Comment by bsclifton** [comment]
Looks like this is caused by the Crypt Wallets extension
cc: @bbondy @ryanml

**Comment by ryanml** [comment]
@Nuc1eoN @minaiism @EugenioAntonioBonanno can you folks confirm whether or not you've navigated to `brave://wallet` at any time?

**Comment by EugenioAntonioBonanno** [comment]
I have definitely navigated there.

**Comment by vdavid** [comment]
I'm quite sure I haven't been at `brave://wallet`, and I definitely wasn't in the past 1 month. I ended up here because I'm also seeing the warnings in the console. I hope it helps.

**Comment by minaiism** [comment]
Same as @vdavid .I haven't been at brave://wallet whatsoever.

**Comment by bsclifton** [comment]
@ryanml even if you don't enable Crypto Wallets, the extension is always running. Visible in the Task Manager (Hamburger => More Tools => Task Manager)
<img width="675" alt="Screen Shot 2020-03-05 at 4 57 59 PM" src="https://user-images.githubusercontent.com/4733304/76036842-825e1a80-5f02-11ea-8e72-f98cb01f001b.png">

**Comment by bbondy** [comment]
Hey @bsclifton that's not right for a fresh profile that hasn't navigated to brave://wallet on Release channel up to Nightly. 
Nightly, Beta, and Dev also has some MetaMask compatibility work which will require you to select Crypto Wallets as your Dapp provider before it will display any warnings.

**Comment by bsclifton** [comment]
ah - ok my bad; I believe I did visit brave://wallet. I didn't realize it would run the extension even if Crypto Wallets is disabled / not used

**Comment by marcuswhybrow** [comment]
Disabling Crypto Wallets worked for me:

![Brave](https://user-images.githubusercontent.com/278456/76325366-1f43fd80-62df-11ea-9635-31930339b0b5.png)

**Comment by Enishowk** [comment]
@marcuswhybrow Thanks, it works for me too :)

**Comment by zaxbux** [comment]
There's a source map comment in the affect files, but the source maps themselves are missing. The developers should disable source map creation in their asset build process.

**Comment by cdock1029** [comment]
[Upstream issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1052872)

Looks like more errors are exposed (if source-map files are missing, error will now show where it didn't before)

And, currently source-maps from extensions aren't loaded *even if* they are provided.

I'm seeing this error for 1PasswordX extension, having disabled crypto wallets already.

**Comment by mrose17** [comment]
@rebron - may I ask that someone remove the comments referencing a source map (or install the source map files)? the warning is rather annoying and distracts me when i'm trying to debug things in the browser... thanks!

**Comment by mrose17** [comment]
Thank you!

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit)
-- | --
Revision | `0e5d92df40086cf0050c00f87b11da1b14580930-refs/branch-heads/4280@{#1441}`
OS | Linux
Component | `1.0.17 dev`

- Verified no error/warnings about SourceMap in devtools irrespective of whether Crypto Wallet was enabled or not 
------
Verification passed on

Brave | 1.19.16 Chromium: 87.0.4280.66 (Official Build) nightly (64-bit)
-- | --
Revision | `fd98a29dd59b36f71e4741332c9ad5bda42094bf-refs/branch-heads/4280@{#1432}`
OS | Windows 10 OS Version 1809 (Build 17763.1577)
Component | `1.0.17 dev`

- Verified no error/warnings about SourceMap in devtools irrespective of whether Crypto Wallet was enabled or not 
---------

Verification passed on 

Brave | 1.18.56 Chromium: 87.0.4280.60 (Official Build) dev (x86_64)
-- | --
Revision | `12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}`
OS | macOS Version 10.15.7 (Build 19H2)
Component | `1.0.17 dev`

- Verified no error/warnings about SourceMap in devtools irrespective of whether Crypto Wallet was enabled or not
