### ISSUE TITLE
Buttons on top tiles removed message needs padding

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8282]
## Description 

Buttons on top tiles removed message needs padding

## Steps to Reproduce

   1. Add top tiles
   2. Remove one of the top tiles
   3. Buttons on the top tiles removed message doesn't have padding

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/74667161-d1007a80-51c8-11ea-91d3-953e3c92e7ad.png)

## Expected result:
Should have proper padding

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.15.1 (Build 19B88)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @cezaraugusto @petemill 
@brave/legacy_qa to check on other platforms

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified STR from the description
- Top tiles removed message has proper padding, verified both clean and upgraded profile
![image](https://user-images.githubusercontent.com/38657976/75865062-f1674080-5e28-11ea-8944-453dc01f65aa.png)
