### ISSUE TITLE
Panel notification close button closes and immediately re-opens notification.

### ISSUE THREAD

**Issue by gdregalo** [brave/brave-browser#8283]
## Description 
When having multiple notifications, the panel notification close button closes and immediately re-opens notification. It covers all wallet details.  

## Steps to reproduce 

   1.   Get a several notifications (3-5). The easiest way is to have a wallet with a bunch of 
         promotions. 
   2.  Receive them when the panel is opened.
   3.  Tap close button.

## Actual result 
The notification is re-opened. 

## Expected result
Re-reading all notification should be postponed until the panel is closed and opened again.  
Tapping "close" button should remove the topmost notification from the panel.

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Andriod 10 running 1.5.117 x64 stable build
- Verified able to close all notification one by one
- Verified once notifications are closed panel doesn't show it again until BR panel is closed and reopened
--------
Verification passed on Samsung Tab A with Andriod 9.0 running 1.5.117 x64 stable build
- Verified able to close all notification one by one
- Verified once notifications are closed panel doesn't show it again until BR panel is closed and reopened
--------
