### ISSUE TITLE
If have multiple grants, after claiming one from the panel, the next one is shown without CLAIM button.

### ISSUE THREAD

**Issue by gdregalo** [brave/brave-browser#8284]
## Description 
Browser-android-tabs' issue and PR:
 https://github.com/brave/brave-browser/issues/7763. 
https://github.com/brave/browser-android-tabs/pull/2509.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.117 x64 build
- Verified test plan from #7763 
- Verified claiming multiple grants via panel works fine 
![image](https://user-images.githubusercontent.com/17010094/77664879-d8275f00-6fa4-11ea-9981-23a77881f2bb.png)
- Verified claiming multiple grants via rewards page works fine
![image](https://user-images.githubusercontent.com/17010094/77664641-8aaaf200-6fa4-11ea-99ee-d43c359433ed.png)
-------
Verification passed on Samsung Tab A  with Android 9.0 running 1.5.117 x64 build
- Verified test plan from #7763 
- Verified claiming multiple grants via panel works fine 
![image](https://user-images.githubusercontent.com/17010094/77664900-dcec1300-6fa4-11ea-8b7c-64aa5bb27821.png)
- Verified claiming multiple grants via rewards page works fine
![image](https://user-images.githubusercontent.com/17010094/77664690-9991a480-6fa4-11ea-8689-87c218677fe5.png)

-------
