### ISSUE TITLE
[Android] AC notifications doesn't show correct contribution amount.

### ISSUE THREAD

**Issue by gdregalo** [brave/brave-browser#8285]
## Description 
AC notifications doesn't show correct contribution amount. The notifications shows 0.00 BAT.

## Steps to reproduce 

   1.  After AC open the rewards panel.
   2.  Observe 0.00 BAT on successful  contribution notification.
   3. 

## Expected result
Correct amount.

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by gdregalo** [comment]
![Screenshot_20200316-111757](https://user-images.githubusercontent.com/37560650/74676087-32055f80-5183-11ea-9a40-c39705d9dfc1.jpg)

**Comment by NejcZdovc** [comment]
this was fixed on desktop here https://github.com/brave/brave-core/pull/4133

**Comment by samartnik** [comment]
This is done within this PR https://github.com/brave/brave-core/pull/4841

**Comment by kjozwiak** [comment]
Moving this into the `1.5.x` milestone as this was fixed via https://github.com/brave/brave-core/pull/4841 as per https://github.com/brave/brave-browser/issues/8285#issuecomment-595868320 which landed in `1.5.x`.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.118 x64 build
- Verified AC notification shows the correct contribution amount
![Screenshot_20200430-145618](https://user-images.githubusercontent.com/17010094/78012250-53e92900-7362-11ea-9fe7-3c4ad6286477.jpg)
-------
Verification passed on Samsung Tab A with Android 9.0 running 1.5.118 x64 build
- Verified AC notification shows the correct contribution amount
![Screenshot_20200430-152116_Brave](https://user-images.githubusercontent.com/17010094/78013606-58aedc80-7364-11ea-862f-6ff1f723056a.jpg)
