### ISSUE TITLE
To navigate, need to click any link twice on eksisozluk.com

### ISSUE THREAD

**Issue by umutcanbolat** [brave/brave-browser#8287]
## Description 

To navigate, I have to click any link twice on [eksisozluk.com](`https://eksisozluk.com`). This is one of the most visited websites in Turkey.

## Steps to Reproduce

   1. Visit [eksisozluk.com](`https://eksisozluk.com`)
   2. Click on any link to navigate. This first click won't do anything.
   3. Now click on any other link again to navigate successfully. 

## Actual result:

Brave users have to click twice on the links to navigate while chrome with uBlock origin installed works as expected.

## Expected result:
First click on the links must navigate to the target page.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

/ | version
-- | --
Brave | 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1903 (Build 18362.535)

## Version/Channel Information:

Did not try

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No. A pop-up ad is showing up when I click on any link. So I've to close it first to navigate. I think this is the cause of unexpected behavior.
- Does the issue resolve itself when disabling Brave Rewards?
No.
- Is the issue reproducible on the latest version of Chrome? 
Chrome with uBlock origin has no issue.

**Comment by rebron** [comment]
Looks like with cross-site trackers toggled off (or shields down) this is working properly. Not sure which of this is the culprit:
https://www.googleadservices.com/pagead/conversion.js
https://nativespot.com/apijs/v1.js
https://app.networkad.net/netasync.js?zid=314&hbid=1
https://app.networkad.net/netasync.js?zid=313&hbid=1
https://app.networkad.net/netasync.js?zid=317&hbid=1
https://app.networkad.net/netasync.js?zid=318&hbid=1
https://app.networkad.net/netasync.js?zid=319&hbid=1
https://app.networkad.net/netasync.js?zid=320&hbid=1
https://app.networkad.net/netasync.js?zid=321&hbid=1
https://app.networkad.net/netasync.js?zid=302&hbid=1
https://static.criteo.net/js/ld/publishertag.js
https://ads.ekstat.com/2020/nisan/alef/buton.png
https://app.networkad.net/netasync.js?zid=571
https://googleads.g.doubleclick.net/pagead/viewthroughconversion/878852058/?value=0&guid=ON&script=0
https://www.googletagmanager.com/gtm.js?id=GTM-WXV2Z47
https://www.googletagservices.com/tag/js/gpt.js
https://www.googletagmanager.com/ns.html?id=GTM-WXV2Z47

cc: @ryanbr

**Comment by ryanbr** [comment]
@umutcanbolat Can you check with the latest Brave build, is this resolved? I'm not seeing any issues with clicks on the site.

**Comment by umutcanbolat** [comment]
Hi @ryanbr. Yes, I checked now and the issue does not exist anymore. So I'm closing this thread. Thanks!
