### ISSUE TITLE
Add a parameter to be able to build Brave without Tor support

### ISSUE THREAD

**Issue by Th0masL** [brave/brave-browser#8288]
## Description 
I love the Brave browser, but I would like to find a way to be able to disable (or even not install at all) the Tor functionality, because sometimes there are some good reasons to have a web filter (OpenDNS with safemode, for example, to block most of the adult content to protect kids), and the Tor mode allow to bypass most if not any web filter.

## Steps to Reproduce
   1. Implement some sort of web filtering
   2. Install Brave
   3. Open the Tor tab
   4. Enjoy unfiltered web

## Expected result:
I was hoping there would be a way to build Brave from source, and pass a parameter during the build process to disable the Tor support (removing the Tor button in the menu could be enough actually).

I might try to clone the repo and add this functionality myself, by I'm not really a developer, so I'm not sure I'll be able to do it myself.

**Comment by bsclifton** [comment]
Similar to how we disable Tor for android, you can do the same in the `lib.config.js` file:
https://github.com/brave/brave-browser/blob/fe21b7bbf80773bded0d32c89d41e11962b25f84/lib/config.js#L251

However, you can disable Tor via DNS also - by blocking `tor.bravesoftware.com` (it tries to download there on first run). You can also disable via group policy
https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy
