### ISSUE TITLE
Command line args are listed twice after upgrade

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8290]
## Description 

Command line args are listed twice after upgrade

## Steps to Reproduce

   1. Clean profile 1.3.115
   2. Upgrade to 1.3.116
   3. Open chrome://version
   4. Command line args are listed twice after upgrade

## Actual result:

Command line args are listed twice after upgrade
![image](https://user-images.githubusercontent.com/38657976/74714168-0603e000-5250-11ea-8359-aac4c67e5adf.png)

## Expected result:

Command line args should be listed once after upgrade
## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.3.116 Chromium: 80.0.3987.106 (Official Build) (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @brave/legacy_qa @darkdh @rebron @bsclifton

**Comment by srirambv** [comment]
This happens when you set the flag to `Disabled` and then set it back to `Default`.

**Comment by LaurenWags** [comment]
Can't reproduce using STR from description on macOS, but can reproduce using https://github.com/brave/brave-browser/issues/8290#issuecomment-587325681 on both clean and upgrade profiles.


Brave | 1.3.116 Chromium: 80.0.3987.106 (Official Build) (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | macOS Version 10.14.6 (Build 18G3020)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.7.67 Chromium: 80.0.3987.149 (Official Build) beta (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified STR from the description, there is no `--disable--sync` duplicate flag
![image](https://user-images.githubusercontent.com/38657976/77103050-d22efc80-6a3f-11ea-8842-725fe6378971.png)
- Verified the test plan from https://github.com/brave/brave-core/pull/4679
