### ISSUE TITLE
Brave Beta (1.4.90) on linux loses connection to the internet after a while

### ISSUE THREAD

**Issue by hugobuddel** [brave/brave-browser#8291]
## Description 

Brave seems to lose connection to the internet after a while.

## Steps to Reproduce

   1. Start Brave.
   2. Use it for about an hour, or just keep it open.
   3. Try to visit a site.

## Actual result:

An empty page with a rotating spinner in the tab. No connection seems to be made.

## Expected result:
The site loading.

## Reproduces how often: 

Takes about an hour or so. But fails reliably the last couple of days to the point that using Brave is annoying. At least since 1.4.86.

## Brave version (brave://version info)

Brave | 1.4.90 Chromium: 80.0.3987.106 (Official Build) beta (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | Linux
JavaScript | V8 8.0.426.19
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36
Command Line | /opt/brave.com/brave-beta/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,SimplifyHttpsIndicator,WebUIDarkMode --disable-features=AllowPopupsDuringPageUnload,WebXR,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,VideoPlaybackQuality,WebXrGamepadModule --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /opt/brave.com/brave-beta/brave
Profile Path | /home/[...]/.config/BraveSoftware/Brave-Browser-Beta/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? Don't know.
- Can you reproduce this issue with the beta channel? Yes.
- Can you reproduce this issue with the dev channel? Don't know.
- Can you reproduce this issue with the nightly channel? Don't know.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? Don't know.
- Is the issue reproducible on the latest version of Chrome? Don't know.

## Miscellaneous Information:

I'm not sure how to start debugging this. Are there specific logs that I could check?

**Comment by rebron** [comment]
@hugobuddel We're on 1.8.78 on Beta now. Are you still running into this issue?

**Comment by hugobuddel** [comment]
I still had the problem last week or so, not sure what version of Brave I was running then.

I run Brave from the command line now, and take note when the problem happens, but haven't found a clear pattern yet.

One of the difficulties is that it usually happens when I'm not at the machine. I return to it, and Brave refuses to load anything. It is always on, so 90% of the time I'm not using it.

BTW, new tabs allow me to enter a page, but the page will not load. The new tabs do not get saved to the profile, because they are not there upon closing and reopening Brave.

I've also bought new network hardware (router and such) last week. I could imagine scenario's where that makes a difference. E.g. something timing out and Brave not recovering properly, or something like that.

I'll make sure to upgrade to the latest Brave (should be the case already), and comment here again if the problem happens within the next week. If not, then I'll close the issue.

**Comment by bsclifton** [comment]
Closing as stale - but please re-open if it has happened again and you have more details

Might be useful to check the /etc/hosts file just in case there was anything hardcoded there

**Comment by hugobuddel** [comment]
Still happens, but very occasionally, not enough to be annoying. And if it's just me, then well, I'll deal with it.
