### ISSUE TITLE
armhf.deb for Pinebook Pro please!

### ISSUE THREAD

**Issue by pinebookfan** [brave/brave-browser#8292]
Can you create an armhf.deb build of Brave Browser for Debian 9 Stretch Linux.
The only supported processor architecture is now x86.

With Armhf support your browser could work on a raspberry pi or the pinebook pro.
The libc6 version should be 2.24 not higher.
Arm64 is a possible option too, but in my case not necessary. 

Please don't close this topic, i'm talking about processor architecture so brave browser can run on other devices than intel or amd cpus -> Arm-Processors. If you don't know what i'm talking about, duckduckgo is your best friend ;) It should be clear for an developer what armhf.deb is!

**Comment by pinebookfan** [comment]
AppImageLauncherNow works on Pinebook Pro:
https://github.com/TheAssassin/AppImageLauncher/releases

So an armhf appimage is now possible! Make it's easier to make :)

**Comment by pinebookfan** [comment]
Maybe!

**Comment by Syping** [comment]
I would like Brave on various SBC boards like Odroid, Raspberry Pi etc. too, i tried to build my self but failed (maybe because i did not setup Cross-build properly)

**Comment by rebron** [comment]
Closing. Unfortunately we're not supporting x86 for Linux and not planning to support in the near future.
