### ISSUE TITLE
Sync is not working

### ISSUE THREAD

**Issue by Staant95** [brave/brave-browser#8293]
Hi, today I updated my system and I noticed that Sync is completely disabled. I am using ubuntu 19.10  and brave version 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit). Anyone else has this problem? Any solution?

**Comment by MrHaroldA** [comment]
> Release Notes V1.3.115
> Fixed several crashes and stability issues by temporarily disabling sync. (#7781)

**Comment by multiojuice** [comment]
I am also not able to access sync settings on MacOS desktop. I go to settings and click sync and there is no response. Nothing comes up when searching sync in settings either.

**Comment by webash** [comment]
@multiojuice see above comment by @MrHaroldA : the sync code has been completely (but temporarily) disabled in order to prevent whole-browser crashes.

**Comment by pexaorj** [comment]
Any news when the sync option is will be enabled again?

**Comment by bsclifton** [comment]
cc: @rebron @jsecretan

**Comment by probablykasper** [comment]
The release @bsclifton mentioned is out already, with the #brave-sync flag that can re-enable sync. I had to go to `chrome://settings/help` in order to update because it didn't show the green update symbol.

**Comment by MrHaroldA** [comment]
As @bsclifton mentioned, the sync option back again so this issue may be closed. I did however get all my previously deleted items back 3 times. I'm wondering if I should remove them again because they seem to multiply as zombies ;)
