### ISSUE TITLE
[P3A] Sent status is not recorded on upgrade [Follow up to #8084]

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8295]
## Description 

[P3A] Sent status is not recorded on upgrade [Follow up to #8084]

## Steps to Reproduce

1. Clean profile 1.3.115
2. Open brave://local-state
3. Check P3A stats, sent is false no timestamp is recorded  for all stats
4. Upgrade to 1.3.116
5. Close brave and launch using `brave-browser --p3a-rotation-interval-seconds=5`

## Actual result:

Sent value is not updated

## Expected result:
Sent value should be updated

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.3.116 Chromium: 80.0.3987.106 (Official Build) (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome?  NA

## Miscellaneous Information:

Issue reproduced by @GeetaSarvadnya 
cc: @iefremov @rebron

**Comment by GeetaSarvadnya** [comment]
Reproduced in windows 10 x64 - 1.3.116

**Comment by iefremov** [comment]
there is a backoff delay right after the browser start. For how long have you been waiting? @GeetaSarvadnya

**Comment by GeetaSarvadnya** [comment]
@iefremov I have waited for almost 2 mins after the browser restart

**Comment by iefremov** [comment]
ah, sorry, this is probably because of the wrong flag. No just restart browser without `--p3a-rotation-interval-seconds=5`. It doesn't let you actually send any data. I specified it in order to clean the `sent` state

**Comment by GeetaSarvadnya** [comment]
@iefremov @srirambv after upgrade without using the flag `--p3a-rotation-interval-seconds=5`. I am getting the expected results.
![image](https://user-images.githubusercontent.com/38657976/74736798-8854ca00-5279-11ea-942a-723c3d5f2d17.png)

**Comment by iefremov** [comment]
Thank you @GeetaSarvadnya

**Comment by srirambv** [comment]
Confirmed working on Linux as well when browser is launched without the command line args
![image](https://user-images.githubusercontent.com/17010094/74737459-e9c96880-527a-11ea-922e-d257ee3228c9.png)

**Comment by srirambv** [comment]
Working as expected hence closing
