### ISSUE TITLE
[P3A] Incorrect value set for Q12 / WalletBalance (Brave.Rewards.WalletBalance.2)

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8296]
## Description 

[P3A] Incorrect value set for WalletBalance [Follow up to #7633]

## Steps to Reproduce

Scenario 1:
   1. Clean install 1.3.116
   2. Open local-state
   3. `Brave.Rewards.WalletBalance.2` is set to 0 (as expected)
   4. Enable Rewards 
   5. `Brave.Rewards.WalletBalance.2` is set to 2[`10-50 BAT, excluding grants`] instead of 1[`Less than 10 BAT (0-9), excluding grants`]

Scenario 2:
   1. Clean install 1.3.116
   2. Open local-state
   3. `Brave.Rewards.WalletBalance.2` is set to 0 (as expected)
   4. Enable Rewards 
   5. `Brave.Rewards.WalletBalance.2` is set to 2[`10-50 BAT, excluding grants`] instead of 1[`Less than 10 BAT (0-9), excluding grants`]
   6. Claim UGP grant 
   7. `Brave.Rewards.WalletBalance.2` is set to 3[`Over 50 BAT, excluding grants`]  instead of 1 [`Less than 10 BAT (0-9), excluding grants`]

## Actual result:

Incorrect value set for WalletBalance

## Expected result:
Correct values for excluding grants should be set

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.3.116 Chromium: 80.0.3987.106 (Official Build) (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Incorrect value is set on current release version as well. May be related to #7235. Issue reproduced on Windows by @GeetaSarvadnya . 
cc: @iefremov @rebron

**Comment by LaurenWags** [comment]
Reproduced on macOS.


Brave | 1.3.116 Chromium: 80.0.3987.106 (Official Build) (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | macOS Version 10.14.6 (Build 18G3020)

Restored a wallet with 28 BAT (no grants). Expected "Brave.Rewards.WalletBalance.2" value to be 3 for "10-50 BAT, excluding grants", however it is still displaying 2, even after browser restart.

<img width="1015" alt="Screen Shot 2020-02-18 at 4 37 08 PM" src="https://user-images.githubusercontent.com/28145373/74780111-ec24c600-526c-11ea-87eb-b07e38383db3.png">

**Comment by GeetaSarvadnya** [comment]
In one more scenario, the wallet balance is not shown correctly.
1. Clean profile
2. Enable rewards
3. `Brave.Rewards.WalletBalance.2`  is set to `2` as expected
4. Restore a wallet ( which has balance 1)
5. Claim UGP grants of 20 BAT
6. `Brave.Rewards.WalletBalance.2` is set to `3` 10-50 BAT, excluding grants, instead of `2` Less than 10 BAT (0-9), excluding grants

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```


<!--StartFragment-->
Brave | 1.26.43 Chromium: 91.0.4472.77&nbsp;(Official Build)&nbsp;beta&nbsp;(64-bit)
-- | --
Revision | 1cecd5c8a856bc2a5adda436e7b84d8d21b339b6-refs/branch-heads/4472@{#1246}
OS | Windows&nbsp;10 OS Version 2004 (Build 19041.985)

<!--EndFragment-->

```
- Verified the test plan from https://github.com/brave/brave-core/pull/8734 and cases from the description

**Comment by GeetaSarvadnya** [comment]
@iefremov @emerick Looks like it's a common rewards library fix that is shared by both Desktop and Android, I hope this fix is applicable for Android also

@srirambv Looks like this issue is appearing in Android also, have you seen this issue while testing P3A rewards on Android?

**Comment by GeetaSarvadnya** [comment]
The issue persists on Android also hence adding Android OS label

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.26.59 x64 Beta Build


`Brave.Rewards.WalletBalance.2 = 0` | `Brave.Rewards.WalletBalance.2 = 2` | `Brave.Rewards.WalletBalance.2 = 3` | `Brave.Rewards.WalletBalance.2 = 4`
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/122038689-c9a5ad00-cdcd-11eb-8f13-82422d51d9c4.png) | ![image](https://user-images.githubusercontent.com/17010094/122038711-d0ccbb00-cdcd-11eb-8bf4-524aaadd7ff7.png) | ![image](https://user-images.githubusercontent.com/17010094/122038947-0f627580-cdce-11eb-86d1-f57734a17c75.png) | ![image](https://user-images.githubusercontent.com/17010094/122038731-d5916f00-cdcd-11eb-88f2-963ff951d5f6.png)
