### ISSUE TITLE
Get Chromium browser_tests working

### ISSUE THREAD

**Issue by jonathanKingston** [brave/brave-browser#8297]
Running `npm run test -- browser_tests` currently ends in a compiler error preventing any of the tests to run.

This means I can't verify Chromium test are broken with other changes such as: https://github.com/brave/brave-browser/issues/8184

**Comment by jonathanKingston** [comment]
Also for the record, I see a lot of test failures already when running this locally. Stuff that likely could be causing issues. I have no idea what runs in CI however it's must not be running at least for a debug build.

**Comment by bsclifton** [comment]
@jonathanKingston do you have more information about this?

You're mentioning trying to run the Brave browser tests (using `npm run test -- browser_tests`). But in the issue title you're mentioning getting Chromium browser tests working

Have you tried to run the actual Chromium unit/browser tests? I think these are only built if you try to build Chromium source. We should be able to do this (would be interesting to see if any of our patches break anything)- but currently we don't do this

**Comment by bsclifton** [comment]
OK reproduced:
```
../../chrome/browser/apps/guest_view/web_view_browsertest.cc:187:64: error: no viable conversion from 'OnceCallback<MakeUnboundRunType<void ((anonymous namespace)::ContextMenuShownObserver::*)(BraveRenderViewContextMenu *), base::internal::UnretainedWrapper<(anonymous namespace)::ContextMenuShownObserver> >>' to 'OnceCallback<void (RenderViewContextMenu_Chromium *)>'
    RenderViewContextMenu::RegisterMenuShownCallbackForTesting(base::BindOnce(
                                                               ^~~~~~~~~~~~~~~
../../base/callback.h:64:3: note: candidate constructor not viable: no known conversion from 'OnceCallback<MakeUnboundRunType<void ((anonymous namespace)::ContextMenuShownObserver::*)(BraveRenderViewContextMenu *), base::internal::UnretainedWrapper<(anonymous namespace)::ContextMenuShownObserver> > >' (aka 'OnceCallback<void (BraveRenderViewContextMenu *)>') to 'std::nullptr_t' (aka 'nullptr_t') for 1st argument
  OnceCallback(std::nullptr_t) = delete;
  ^
../../base/callback.h:69:3: note: candidate constructor not viable: no known conversion from 'OnceCallback<MakeUnboundRunType<void ((anonymous namespace)::ContextMenuShownObserver::*)(BraveRenderViewContextMenu *), base::internal::UnretainedWrapper<(anonymous namespace)::ContextMenuShownObserver> > >' (aka 'OnceCallback<void (BraveRenderViewContextMenu *)>') to 'const base::OnceCallback<void (RenderViewContextMenu_Chromium *)> &' for 1st argument
  OnceCallback(const OnceCallback&) = delete;
  ^
../../base/callback.h:72:3: note: candidate constructor not viable: no known conversion from 'OnceCallback<MakeUnboundRunType<void ((anonymous namespace)::ContextMenuShownObserver::*)(BraveRenderViewContextMenu *), base::internal::UnretainedWrapper<(anonymous namespace)::ContextMenuShownObserver> > >' (aka 'OnceCallback<void (BraveRenderViewContextMenu *)>') to 'base::OnceCallback<void (RenderViewContextMenu_Chromium *)> &&' for 1st argument
  OnceCallback(OnceCallback&&) noexcept = default;
  ^
../../base/callback.h:75:3: note: candidate constructor not viable: no known conversion from 'OnceCallback<MakeUnboundRunType<void ((anonymous namespace)::ContextMenuShownObserver::*)(BraveRenderViewContextMenu *), base::internal::UnretainedWrapper<(anonymous namespace)::ContextMenuShownObserver> > >' (aka 'OnceCallback<void (BraveRenderViewContextMenu *)>') to 'RepeatingCallback<base::OnceCallback<void (RenderViewContextMenu_Chromium *)>::RunType>' (aka 'RepeatingCallback<void (RenderViewContextMenu_Chromium *)>') for 1st argument
  OnceCallback(RepeatingCallback<RunType> other)
  ^
../../brave/chromium_src/chrome/browser/renderer_context_menu/../../../../../chrome/browser/renderer_context_menu/render_view_context_menu.h:89:56: note: passing argument to parameter 'cb' here
      base::OnceCallback<void(RenderViewContextMenu*)> cb);
                                                       ^
../../chrome/browser/apps/guest_view/web_view_browsertest.cc:2366:7: error: no viable conversion from 'OnceCallback<MakeUnboundRunType<(lambda at ../../chrome/browser/apps/guest_view/web_view_browsertest.cc:2355:39) &, base::RepeatingCallback<void ()> >>' to 'OnceCallback<void (RenderViewContextMenu_Chromium *)>'
      base::BindOnce(close_menu_and_stop_run_loop, run_loop.QuitClosure()));
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../base/callback.h:64:3: note: candidate constructor not viable: no known conversion from 'OnceCallback<MakeUnboundRunType<(lambda at ../../chrome/browser/apps/guest_view/web_view_browsertest.cc:2355:39) &, base::RepeatingCallback<void ()> > >' (aka 'OnceCallback<void (BraveRenderViewContextMenu *)>') to 'std::nullptr_t' (aka 'nullptr_t') for 1st argument
  OnceCallback(std::nullptr_t) = delete;
  ^
../../base/callback.h:69:3: note: candidate constructor not viable: no known conversion from 'OnceCallback<MakeUnboundRunType<(lambda at ../../chrome/browser/apps/guest_view/web_view_browsertest.cc:2355:39) &, base::RepeatingCallback<void ()> > >' (aka 'OnceCallback<void (BraveRenderViewContextMenu *)>') to 'const base::OnceCallback<void (RenderViewContextMenu_Chromium *)> &' for 1st argument
  OnceCallback(const OnceCallback&) = delete;
  ^
../../base/callback.h:72:3: note: candidate constructor not viable: no known conversion from 'OnceCallback<MakeUnboundRunType<(lambda at ../../chrome/browser/apps/guest_view/web_view_browsertest.cc:2355:39) &, base::RepeatingCallback<void ()> > >' (aka 'OnceCallback<void (BraveRenderViewContextMenu *)>') to 'base::OnceCallback<void (RenderViewContextMenu_Chromium *)> &&' for 1st argument
  OnceCallback(OnceCallback&&) noexcept = default;
  ^
../../base/callback.h:75:3: note: candidate constructor not viable: no known conversion from 'OnceCallback<MakeUnboundRunType<(lambda at ../../chrome/browser/apps/guest_view/web_view_browsertest.cc:2355:39) &, base::RepeatingCallback<void ()> > >' (aka 'OnceCallback<void (BraveRenderViewContextMenu *)>') to 'RepeatingCallback<base::OnceCallback<void (RenderViewContextMenu_Chromium *)>::RunType>' (aka 'RepeatingCallback<void (RenderViewContextMenu_Chromium *)>') for 1st argument
  OnceCallback(RepeatingCallback<RunType> other)
  ^
../../brave/chromium_src/chrome/browser/renderer_context_menu/../../../../../chrome/browser/renderer_context_menu/render_view_context_menu.h:89:56: note: passing argument to parameter 'cb' here
      base::OnceCallback<void(RenderViewContextMenu*)> cb);
                                                       ^
2 errors generated.
```

Going to pull your branch down and give it a go 😄

**Comment by jonathanKingston** [comment]
@bsclifton it's noisy certainly, however the `--filter` flag is useful for running certain tests. I ran the tests for roughly 4 hours. There are about 1k of tests that fail.

I'm hoping to chase down the following error lines:
>[18421:18431:0219/015138.807643:ERROR:service_manager.cc(210)] Failed to resolve service name: bat_ledger
> [18421:18431:0219/015138.807738:ERROR:service_manager.cc(210)] Failed to resolve service name: bat_ads

Which account for well over 1k of the console lines.

**Comment by bsclifton** [comment]
@jonathanKingston I think you'll need to modify `brave-browser` as well; for example, check out:
https://github.com/brave/brave-browser/blob/a3299c760abadfe4df20d028ed1e5e61136d982d/scripts/commands.js#L159-L170

and also:
https://github.com/brave/brave-browser/blob/a3299c760abadfe4df20d028ed1e5e61136d982d/lib/test.js#L40

**Comment by jonathanKingston** [comment]
> Definitely missing something- maybe the Chromium browser tests would need to be patched to include test files from Ads / Ledger (to register a stub for the service). But I did verify your patch gets it compiling :smile:

Yeah I agree, however it seems to be test specific. The error isn't in every every test and the browser appears to have the code.
It could also be a linking error from the code differences in `src/chrome/test/BUILD.gn` and `src/brave/test/BUILD.gn`

**Comment by mariospr** [comment]
Similar to what I mentioned in detail in https://github.com/brave/brave-browser/issues/8376#issuecomment-774179252 for the case of getting `unit_tests` building, I've started looking into fixing the compilation errors for `browser_test` as well, which at the moment look very similar to the ones mentioned by @bsclifton in https://github.com/brave/brave-browser/issues/8297#issuecomment-588065370.

And the **good news** is that I just got them building with a very small adjustment in the source overrides for //c/b/renderer_context_menu/render_view_context_menu.h:
```
 chromium_src/chrome/browser/renderer_context_menu/render_view_context_menu.cc | 13 +++++++++++++
 chromium_src/chrome/browser/renderer_context_menu/render_view_context_menu.h  |  9 ++++++++-
 2 files changed, 21 insertions(+), 1 deletion(-)
```
And since it's just such a small change, I've repurposed https://github.com/brave/brave-browser/issues/14001 so that it's not just about fixing the build for `unit_tests` but also for `browser_tests` and so we have already a small PR that should fix the build of both binaries, check it out here: https://github.com/brave/brave-core/pull/7899

I'm going to look next into which browser_tests are failing and which ones we could easily skip in a similar fashion to how I did it for unit_tests in https://github.com/brave/brave-core/pull/7901, but for the time being I thought a heads up was in order.

PTAL to https://github.com/brave/brave-core/pull/7899 when you have a moment, thanks!
