### ISSUE TITLE
[Android] android-core doesn't limit ads in tray to 3

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8299]
## Description 
Android Tabs limited ads in the tray to 3, Android Core should do the same. Currently, it is not. I have let ads stack up in the notification tray so that I have gotten at least 5.

## Steps to reproduce 

   1. Be in a region with lots of ads
   2. Browse normally
   3. Watch ads pile up in the notification tray

## Actual result 
See multiple ads in tray. Note, due to https://github.com/brave/brave-browser/issues/7571 you can't tell if they are from tabs or core version, so I long pressed on each one to show that they are from core/Beta:
![Screenshot_20200218-085604_One UI Home](https://user-images.githubusercontent.com/28145373/74743129-e22fa280-522d-11ea-9c99-c902f7873808.jpg)

![Screenshot_20200218-085614_One UI Home](https://user-images.githubusercontent.com/28145373/74743139-e6f45680-522d-11ea-9c8a-c94b6897ad12.jpg)

![Screenshot_20200218-085625_One UI Home](https://user-images.githubusercontent.com/28145373/74743145-ea87dd80-522d-11ea-9b45-3ac45e130236.jpg)

![Screenshot_20200218-085635_One UI Home](https://user-images.githubusercontent.com/28145373/74743151-ed82ce00-522d-11ea-877e-e7aafd1da236.jpg)

![Screenshot_20200218-085646_One UI Home](https://user-images.githubusercontent.com/28145373/74743164-f2478200-522d-11ea-8b32-d1e9b8f0c964.jpg)

![Screenshot_20200218-085657_One UI Home](https://user-images.githubusercontent.com/28145373/74743176-f6739f80-522d-11ea-8195-476a3725df84.jpg)

## Expected result
only 3 ads at a time in my notification tray

## Issue reproduces how often 
easily, every day

## Issue happens on 
   - Current Play Store version? no
   - Beta build? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.5.90 CR 80.0.3987.100

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @brave/legacy_qa

**Comment by emerick** [comment]
This seems to happen when you start Brave, wait for a couple of Ads to appear, and then kill and restart Brave. After restarting, Brave no longer recognizes the old ad notifications and is unable to close them when the cap reaches 3. The end result seems to be the cap effectively becomes 3 + number_of_old_ads.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.110 x64 stable build
- Verified only 3 ads are in tray when ads show up
- Verified with 3 ads in tray removing app and relaunching and new ads show up only 3 remain in the tray
