### ISSUE TITLE
Consider adding MDNS for local network peer/service discovery

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#830]
MetaMask requested this.
cc @diracdeltas

**Comment by crocket** [comment]
brave listens to UDP port 5353. Is this mDNS?

**Comment by diracdeltas** [comment]
@crocket yes, i believe those connections are needed by chromium to support chromecast and cloud print. https://bugs.chromium.org/p/chromium/issues/detail?id=859359

**Comment by crocket** [comment]
As far as I know, brave's IPFS companion uses mDNS.
