### ISSUE TITLE
[P3A] Brave.Rewards.TipsState.2 value 4 isn't captured when a recurring tip is set

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8301]
## Description 

[P3A] Brave.Rewards.TipsState.2 value 4 isn't captured when a recurring tip is set

## Steps to Reproduce

   1. Clean install `1.3.116`
   2. Check Brave.Rewards.TipsState.2 value is set to 0
   3. Enable rewards and claim grant
   4. Check Brave.Rewards.TipsSate.2 value is set to 2
   5. Set recurring tip to verified pub
   6. Check Brave.Rewards.TipsState.2 value is set to 2 and not to 4

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/74749316-f906e100-528f-11ea-8e3c-22a0808b90bf.png)

## Expected result:
Should update the value without delay

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.3.116 Chromium: 80.0.3987.106 (Official Build) (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome?  NA

## Miscellaneous Information:

cc: @iefremov

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.25.22 Chromium: 90.0.4430.72 (Official Build) nightly (x86_64)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | macOS Version 11.2.3 (Build 20D91)

Steps:

1. new profile
2. enabled Rewards, claimed UGP grant
3. checked and verified `Brave.Rewards.TipsState.2` value is set to `2`
4. set recurring tip to verified pub (used `https://www.youtube.com/user/JJDSampson/videos`)
5. after recurring monthly tip was process, checked `Brave.Rewards.TipsState.2 value` confirmed it was set to `4`

example | example | example
---------|---------|----------
<img width="1540" alt="Screen Shot 2021-04-16 at 1 08 28 PM" src="https://user-images.githubusercontent.com/387249/115079436-06305780-9eb6-11eb-9b1a-64d744a25372.png"> | <img width="777" alt="Screen Shot 2021-04-16 at 1 17 37 PM" src="https://user-images.githubusercontent.com/387249/115079533-2cee8e00-9eb6-11eb-9a76-fb24afddb11f.png"> | <img width="777" alt="Screen Shot 2021-04-16 at 1 12 46 PM" src="https://user-images.githubusercontent.com/387249/115079382-f284f100-9eb5-11eb-8a9d-6efc6b3e5835.png">

Note: the original steps to reproduce say "Check `Brave.Rewards.TipsState.2` value is set to `0`" *before* enabling Rewards, but this is no longer the case, as I think we purposefully don't set anything until we actually *enable* Rewards, as part of our "don't ping unless the user initiates it" edict :-)
