### ISSUE TITLE
Check/fuzz/fix old parsers

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#8303]
We have some pretty old parsers like

https://github.com/brave/extension-whitelist/blob/master/extension_whitelist_parser.cc
https://github.com/brave/autoplay-whitelist/blob/master/autoplay_whitelist_parser.cc

and probably others, that do not look quite safe - lots of raw string parsing, including `strlen`, `sscanf` and friends. Inputs for these come from the component updater, and this is a potential security risk. It looks like we should just put this code into main repo, rewrite it using appropriate tools and properly test and fuzz.

**Comment by iefremov** [comment]
cc @diracdeltas @bbondy

**Comment by diracdeltas** [comment]
@bbondy i don't think this necessarily needs to be moved into the main repos, but the benefit would be that it's more visible to hackerone reporters who are looking for this sort of issue. also if we added fuzzing checks in that repo, it would cover these files.

**Comment by diracdeltas** [comment]
also i think `strlen(extensionID)` should just be a constant - as far as i know it's always 32

**Comment by keur** [comment]
The `sscanf` is reading one byte `%x`, so I don't think that is a concern.

**Comment by iefremov** [comment]
both parsers actually convert a list of strings into an associative container. We can just rewrite it using tools from `src/base`, using 10 times less code and avoiding another dep on `/vendor`/ stuff

**Comment by bbondy** [comment]
++ on removing hashset-cpp dependency.

**Comment by keur** [comment]
Sure, removing that dependency will be fine, but the above PR is still relevant regardless of the hashset being used (most the unsafe string handling was in (de)serialization and string operations, and those won't change much even if the hashset is changed).

**Comment by keur** [comment]
Also, tangentially related, but I am pretty sure this leaks memory too (off master).

I suspect the leaks are in `node_addon/EWParserWrap.cc` and `node_addon/EWParserWrap.h`
```
# keur @ blink in ~/repos/extension-whitelist on git:master x [11:21:17] 
$ cat leak.js           
const CEWParser = require('./build/Release/ew_node_addon').CEWParser

this.addon = new CEWParser()
this.addon.addToBlacklist('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')

# keur @ blink in ~/repos/extension-whitelist on git:master x [11:20:58] 
$ valgrind node leak.js
==31314== Memcheck, a memory error detector
==31314== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==31314== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==31314== Command: node leak.js
==31314== 
==31314== 
==31314== HEAP SUMMARY:
==31314==     in use at exit: 76,331 bytes in 1,084 blocks
==31314==   total heap usage: 17,015 allocs, 15,931 frees, 31,463,162 bytes allocated
==31314== 
==31314== LEAK SUMMARY:
==31314==    definitely lost: 40 bytes in 1 blocks
==31314==    indirectly lost: 4,201 bytes in 7 blocks
==31314==      possibly lost: 304 bytes in 1 blocks
==31314==    still reachable: 71,786 bytes in 1,075 blocks
==31314==         suppressed: 0 bytes in 0 blocks
==31314== Rerun with --leak-check=full to see details of leaked memory
==31314== 
==31314== For lists of detected and suppressed errors, rerun with: -s
==31314== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by iefremov** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/27564
