### ISSUE TITLE
[Shields settings] order and relabel cookies and fingerprinting dropdown items from block most to block least

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#8306]
## Description 
The dropdown items for blocking cookies and fingerprinting in Shields should be ordered from block most to block least options.

## Steps to Reproduce

   1. Open Shields
   2. Click on the dropdown element for cookies or fingerprinting

## Actual result:
<img width="283" alt="Screen Shot 2020-02-18 at 11 14 13 AM" src="https://user-images.githubusercontent.com/2388823/74769867-0300f380-5240-11ea-8d9e-763a940f38a9.png">
<img width="287" alt="Screen Shot 2020-02-18 at 11 14 18 AM" src="https://user-images.githubusercontent.com/2388823/74769871-04322080-5240-11ea-9bb7-d2adec84188b.png">

## Expected result:
Menu items should be ordered from block most to block least options like so:

Cookies:

<img width="189" alt="Screen Shot 2020-02-18 at 11 16 46 AM" src="https://user-images.githubusercontent.com/2388823/74769954-2d52b100-5240-11ea-99a5-e3869d7305c5.png">

Fingeprinting:

<img width="232" alt="Screen Shot 2020-02-18 at 11 16 43 AM" src="https://user-images.githubusercontent.com/2388823/74769951-2c218400-5240-11ea-82fb-bb61645362e0.png">

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)
All versions

**Comment by rebron** [comment]
@tomlowenthal Are you ok with these text changes? 
cc: @cezaraugusto To put on your radar.

**Comment by karenkliu** [comment]
Fingerprinting options should use the list here that includes farbling https://github.com/brave/brave-browser/issues/9194

**Comment by karenkliu** [comment]
This has been fixed with https://github.com/brave/brave-browser/issues/9975
