### ISSUE TITLE
sometimes get 'Device list is empty' on brave://sync after creating another sync chain - follow up to 7412

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8314]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/7412

Sometimes when re-creating a sync chain, I get an empty device list on brave://sync page. Usually deleting the chain and re-creating it adds the device I'm on to the list so it is no longer empty.

## Steps to Reproduce

   1. Create a sync chain
   2. Delete the chain
   3. Start a new sync chain (without adding a second device)

## Actual result:
Sometimes after you close the QR code or words screen (without adding a second device), you get this:
<img width="849" alt="Screen Shot 2020-02-18 at 6 13 16 PM" src="https://user-images.githubusercontent.com/28145373/74786534-f1890d00-527a-11ea-837f-5be223f6b520.png">

## Expected result:
Device you are creating the sync chain on should be listed

## Reproduces how often: 

intermittent, happened about 2 out of 9-10 tries

## Brave version (brave://version info)

Brave | 1.3.117 Chromium: 80.0.3987.106 (Official Build) (64-bit)
-- | --
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @AlexeyBarabash @darkdh @brave/legacy_qa

**Comment by AlexeyBarabash** [comment]
In the case when the device hadn't appear immediately, device would appear on the next poll cycle, which would happen next 60 sec or bit more.
So need to wait ~ 1 min or bit more to allow device to appear.

**Comment by rebron** [comment]
cc: @jsecretan Closing as wontfix since this is a sync v1 issue.
