### ISSUE TITLE
Enable the prefetch-privacy-changes flag by default

### ISSUE THREAD

**Issue by Peacock365** [brave/brave-browser#8319]
## Description 

**The Brave flags "Reduce default 'referer' header granularity." and "Prefetch request properties are updated to be privacy-preserving" should be enabled by default, in order to improve the default privacy of Brave users. No website breakage is expected here, no performance degradation is expected here. I have visited several major websites so far with both of these settings enabled (Facebook, Google, YouTube, eBay, Twitter, Amazon, Instagram - you name it), and the websites do behave normally. Please consider enabling these settings by default.**

## Steps to Reproduce

   **1. Go to chrome://flags/#reduced-referrer-granularity
   2. Go to chrome://flags/#prefetch-privacy-changes**

## Actual result:

**The settings are disabled by default.**

## Expected result:

**The settings should be enabled by default.**

## Reproduces how often: 

**Easily reproduced.**

## Brave version (brave://version info)

**Brave | 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.15.3 (Build 19D76)**

**(Reproducible on other OSes as well, though.)**

## Version/Channel Information:

_Does this issue happen on any other channels? Or is it specific to a certain channel?_

**I use the release channel, but it can be reproduced on all channels.**

## Other Additional Information:

_Is the issue reproducible on the latest version of Chrome?_ 

**Yes.**

## Miscellaneous Information:

**Is there any good reason why those settings are disabled by default as it stands? Anything I am unaware of?**

**Comment by bsclifton** [comment]
cc: @snyderp @tomlowenthal

**Comment by snyderp** [comment]
I _think_ we already do this, but just w/o using the code paths Chrome uses.  We aught to just remove the flags.

**Comment by tomlowenthal** [comment]
Removing the flags is another thing that we need to maintain on rebases, so if they're redundant, ley's just ignore them. I'm personally not sure what either of the flags do. François says that the referer one is less protective than our Shields default, and Chrome is going to enable it by default if their tests pan out, so that one's easy to ignore. Looks like `#prefetch-privacy-changes` is pretty good. No reason not to enable it IMO? Is it redundant with some other protection?

**Comment by fmarier** [comment]
The referrer flag will be enabled as part of fixing https://github.com/brave/brave-browser/issues/8696. Let's keep this issue open for the prefetch changes.

**Comment by fmarier** [comment]
Here is more information about this flag:
- [Apple proposal](https://github.com/w3c/resource-hints/issues/82#issuecomment-425633915)
- [Intent to implement in Chromium](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/bSMOY-evrV4)
- [Tracking Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=988956)
- [Tracking Safari bug](https://bugs.webkit.org/show_bug.cgi?id=199162)

and the risks identified by the Chromium team:
> The compatibility risk is mostly low, but not completely clear. Changing the credentials mode for prefetch requests may cause more cache-misses and therefore double-downloads, however could also introduce a correctness problem if prefetch responses do not have the `Vary: Cookie` header attached when their content actually relies on credentials. In this case, it is possible that a user can navigate (with credentials) to a resource, and the user will be served the uncredentialed response from the HTTP cache. We don’t expect the changes to service-workers mode, referrer policy, and redirect mode to break existing content. It is likely they will cause more cache-misses and double-downloads though.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.92 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5731
* Confirmed cookies were not attached to the request
* Confirmed the redirect failed
<img width="1575" alt="Screen Shot 2020-07-17 at 2 15 45 PM" src="https://user-images.githubusercontent.com/28145373/87818242-3ddf7580-c838-11ea-935b-4d220d5d3b2c.png">
<img width="907" alt="Screen Shot 2020-07-17 at 2 16 05 PM" src="https://user-images.githubusercontent.com/28145373/87818252-4041cf80-c838-11ea-806d-bd573560e560.png">

-----

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.111 x64 build
- Verified test plan from brave/brave-core#5731
- Verified `redirect4.html` doesn't have any cookies set 
![image](https://user-images.githubusercontent.com/17010094/89894027-4cb80e80-dbd1-11ea-8fbd-451b4efaaace.png)
- Verified `get-cookies.html` is not redirected and is blocked
![image](https://user-images.githubusercontent.com/17010094/89894122-7a9d5300-dbd1-11ea-8d67-3368151c0324.png)

-----------------
Verification passed on OnePlus 6T with Android 10 running 1.12.111 x64 build
- Verified test plan from brave/brave-core#5731
- Verified `redirect4.html` doesn't have any cookies set
![image](https://user-images.githubusercontent.com/17010094/89894345-de278080-dbd1-11ea-88bb-d675602c2bba.png)
- Verified `get-cookies.html` is not redirected and is blocked
![image](https://user-images.githubusercontent.com/17010094/89894395-ec759c80-dbd1-11ea-81e8-f04ebd22e255.png)
