### ISSUE TITLE
Duplicate sync object id of bookmarks

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#8325]
## Description 

If user copy bookmark, then meta infos are also copied. That will lead to same object id for multiple bookmarks

## Steps to Reproduce

1. Go to `about:flags#brave-sync` and enable sync
2. Create a sync chain
3. Go to brave://bookmarks/
4. Add a bookmark
5. Go to `about:flags#brave-sync` and disable sync
6. COPY the bookmark
7. Go to `about:flags#brave-sync` and enable sync
8. Browser crashes and keep crashing on startup
9. There is same object id for these two bookmarks in `Bookmarks` in user profile

## Actual result:

browser crashes
```
0  Brave Browser Framework! [synced_bookmark_tracker.cc : 500 + 0x0]
1  Brave Browser Framework!sync_bookmarks::BookmarkModelTypeProcessor::OnCommitCompleted(sync_pb::ModelTypeState const&, std::__1::vector > const&) [bookmark_model_type_processor.cc : 227 + 0x8]

```
https://stats.brave.com/dashboard#crash/5e4d7b0f9562f600667c9b55

And duplicate object id for different bookmarks

## Expected result:
No crash and no duplicate object id

## Reproduces how often: 

100% reproducible

## Brave version (brave://version info)

80.1.3.118

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified STR from the description
- Verified that brave didn't crash when the sync is enabled and disabled multiple times using the flag `about:flags#brave-sync`
