### ISSUE TITLE
Adding a YubiKey to a GitHub account crashes the browser

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#8326]
## Description 

It's not possible to add a new YubiKey to a GitHub account because doing so currently crashes Brave entirely.

## Steps to Reproduce

1. Go to https://github.com/settings/two_factor_authentication/configure
2. Click "register new security key".
3. Type a name and click "add".
4. Press the YubiKey button.

## Actual result:
Browser crashes.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Release doesn't seem to be affected but Beta:
```
Brave	1.4.86 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
Revision	449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS	Linux
```

dev:
```
1.5.94 Chromium: 80.0.3987.106 (Official Build) dev (64-bit)
Revision	f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS	macOS Version 10.15.3 (Build 19D76)
```
and nightly:
```
Brave | 1.6.36 Chromium: 80.0.3987.106 (Official Build) nightly (64-bit)
Revision | f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}
OS | Linux
```
all crash.

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

It does NOT crash Chrome Canary 82.0.4062.3 (macOS 10.15.3).

**Comment by rebron** [comment]
@fmarier Can you check on beta with 81.0.4044.92?

**Comment by rebron** [comment]
cc: @jumde @tomlowenthal We believe this should be working now in 1.7.92 and also in beta channel.

**Comment by jumde** [comment]
@fmarier @rebron - Tried with `1.9.21 Chromium: 81.0.4044.92` and works without any issues.

**Comment by bsclifton** [comment]
Also works great for me (and has for a while). I use USB Yubikey to login to GitHub 😄

**Comment by fmarier** [comment]
Works for me too. :+1:

**Comment by fmarier** [comment]
> Also works great for me (and has for a while). I use USB Yubikey to login to GitHub smile

Just to be clear, this issue was about adding new YubiKeys to a GitHub account. Logging in with an existing key was never broken.

**Comment by rebron** [comment]
Closing. Looks like this is working now.
