### ISSUE TITLE
Users should be able to import payment methods

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#8329]
## Description 
Users should be able to import Payment methods (aka credit card data) from Chrome in order to ease switching from Chrome to Brave.

## Expected Results

   1. Go to Import Bookmarks and Settings.  
   2. When selecting a Chrome "Person", user should be presented with a check box default checked for "Payment methods" if payment method data is available. No check box should be present if no payment method information is available.
   3. Upon selecting Payment method checkbox and selecting Import, user should see Payment method information imported into brave://settings/payments and can now be used for payment method form autofill.

Payment method information should also default import if data is available during brave://welcome onboarding. 

## Miscellaneous Information:
Currently available in MS Edge.

**Comment by rebron** [comment]
Verified on Windows.
Brave | 1.12.108 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 2004 (Build 19041.388)

Followed STR in the PR and ensured no checkbox was available if no payment methods are available to import from Chrome and ensured that payment method checkbox is shown if available and successfully imported payment method. Note that if a payment method is part of Google Pay, those payment methods are not imported due to having to be logged in to Google Pay.

Also ensured that payment methods are imported successfully during onboarding.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.108 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Verified test plan from https://github.com/brave/brave-core/pull/5582

Confirmed no `Payment methods` checkbox if no payment methods exist in Chrome:

<img width="542" alt="Screen Shot 2020-08-07 at 1 24 52 PM" src="https://user-images.githubusercontent.com/28145373/89672058-1701e580-d8b2-11ea-9b5c-a0317184fe31.png">

Confirmed all items above imported successfully from brave://settings/importData and brave://welcome

Confirmed if at least one payment method is saved in Chrome then the `Payment methods` checkbox is shown:

<img width="550" alt="Screen Shot 2020-08-07 at 1 34 28 PM" src="https://user-images.githubusercontent.com/28145373/89672504-bfb04500-d8b2-11ea-9fde-62d00cc4e3a1.png">

Confirmed all items above imported successfully from brave://settings/importData and brave://welcome

----------

**Comment by sry9681** [comment]
Whatever happened to this feature? I would love to import my payment methods and addresses from chrome to brave

**Comment by bsclifton** [comment]
@sry9681 this should be showing... if you have payment methods populated.  I just did a test and it's showing up for me
![image](https://user-images.githubusercontent.com/4733304/129614647-877c5b7e-7c7b-4d92-b375-53965096ca59.png)

The important thing is that you need to pick the correct profile (from the drop down). There will be multiple `Chrome` profiles by default (especially if you have other versions installed, like Chrome Canary). Can you check that @sry9681?

**Comment by Dyltom** [comment]
Is this feature still working? I only have one profile and there's no option to import payment methods from Chrome. 

<img width="522" alt="Screenshot 2023-11-19 at 11 20 55 am" src="https://github.com/brave/brave-browser/assets/2175114/aef8d6b1-92ca-44ac-9efc-89791f342586">
