### ISSUE TITLE
Allowing auto-play on photos.google.com crashes browser

### ISSUE THREAD

**Issue by aekeus** [brave/brave-browser#833]
## Description 

Allowing auto-play on photos.google.com crashes browser

## Steps to Reproduce

   1. Login to Google Photos
   2. Select a video
   3. Allow autoplay

## Actual result:

Crash

## Expected result:
Video should play

## Reproduces how often: 

100% of the time

## Brave version (about:brave info) 

0.54.1

### Reproducible on current release:

No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

**Comment by ltilve** [comment]
I'm not being able to reproduce it yet on `Version 0.55.1 Chromium: 70.0.3528.4 (Developer Build) (64-bit)` on Linux. I will be testing on `0.54` and on the other OS.

**Comment by srirambv** [comment]
This looks fixed on 0.55.2 on Windows and Linux.  cc: @kjozwiak @LaurenWags to verify on mac.

**Comment by LaurenWags** [comment]
Looks resolved on macOS - verified with `0.55.3`

**Comment by LaurenWags** [comment]
Verification Pass with

Brave	0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
Revision	16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS	Mac OS X
