### ISSUE TITLE
Brave quits when scrolling using touchpad and pressing CMD on macos

### ISSUE THREAD

**Issue by q3e** [brave/brave-browser#8330]
## Description 

The browser closes when you scroll up or down on an long page and hold the cmd key while scrolling using the 2 finger scroll on the touch pad, arrow key scrolling does not cause this issue.

## Steps to Reproduce

   1. find a page thats twice as long as the viewport and scroll. 
   2. Hold CMD key as the page is scrolling (or start by holding cmd and then scroll

## Actual result:

The browser quits unexpectedly

## Expected result:
Brave should not quit

## Reproduces how often: 
always

## Brave version (brave://version info)
Brave | 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | macOS Version 10.15.3 (Build 19D76)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards? **NO**
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@q3e Is this still an issue with our latest version 1.7.92? Wondering if this was specifc to a website that caused this. 

Also, if you could check brave://crashes, send the report and post ID here that would help us to diagnose.

**Comment by q3e** [comment]
No longer happening in the current version @rebron
