### ISSUE TITLE
Upload Speed Reduction - When Browser Window is Minimized - Windows 10

### ISSUE THREAD

**Issue by desmonk** [brave/brave-browser#8332]
## Description 

Upon minimizing the browser window, the upload speed fluctuates with reduction in overall speed.

## Steps to Reproduce

   1. Install Brave.
   2. Begin a upload and watch speed with minimized and maximized window.
   3. Pull out Task Manager to visually see the issue.

## Actual result:

![Upload Speed Variation](https://user-images.githubusercontent.com/55331939/74936380-edc3ca80-53e1-11ea-9f16-7c3feb8d4eff.png)

## Expected result:
Speed should remain constant irrespective of such changes.

## Reproduces how often: 

Easily reproduced every time.

## Brave version (brave://version info)

1.2.42 , 79.0.3945.117

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes.
- Can you reproduce this issue with the beta channel?
Untested
- Can you reproduce this issue with the dev channel?
Untested
- Can you reproduce this issue with the nightly channel?
Untested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
Untested

## Miscellaneous Information:

Similar issue is also present in Firefox wherein the upload speed simply gets crippled. Although in Brave, the speed reductions are not that drastic in nature but definitely reduces average speed to about 20-30 percent.

**Comment by rebron** [comment]
@desmonk Could you test again with our latest version:

Brave | 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | macOS Version 10.15.5 (Build 19F53f)

Note that we'll also be doing an update next week with a Chromium 81.

**Comment by rebron** [comment]
@desmonk Are you seeing the same behavior in Chrome?

**Comment by desmonk** [comment]
Recent Brave/Chrome update has solved this issue. Upload/Download now in sync.

![IMG_03](https://user-images.githubusercontent.com/55331939/80229203-9b9c6100-863f-11ea-8993-a6cff5a70585.png)
