### ISSUE TITLE
Refactor Brave Ads database in preparation for merging Publisher Ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#8334]

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.78 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4698
* Verified for clean and upgrade (from 1.5.x) profiles
* Confirmed ads are displayed and data is displayed in Ads panel
<img width="644" alt="Screen Shot 2020-03-30 at 3 45 38 PM" src="https://user-images.githubusercontent.com/28145373/77958759-82ec9580-72a3-11ea-9c5f-271edad30b71.png">
<img width="946" alt="Screen Shot 2020-03-30 at 3 45 45 PM" src="https://user-images.githubusercontent.com/28145373/77958762-841dc280-72a3-11ea-9f34-0e6e0b8dd919.png">
<img width="324" alt="Screen Shot 2020-03-30 at 3 45 20 PM" src="https://user-images.githubusercontent.com/28145373/77958767-85e78600-72a3-11ea-9f00-a1c5db7c0ca1.png">
