### ISSUE TITLE
Revert catalog schema merged with #8294 (only affects 1.7) otherwise ads will not be shown

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#8335]

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.78 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4699 (staging env)
* Confirmed catalog parsed messages in terminal:

```
[9315:775:0330/084848.274380:INFO:ads_serve.cc(72)] Successfully downloaded catalog
[9315:775:0330/084848.274731:INFO:ads_serve.cc(148)] Parsing catalog
[9315:775:0330/084848.277835:INFO:catalog.cc(37)] Successfully loaded catalog
[9315:775:0330/084848.278100:INFO:ads_serve.cc(154)] Catalog parsed
```

* Confirmed able to view an ad and have the ads panel on brave://rewards reflect this:
<img width="647" alt="Screen Shot 2020-03-30 at 8 56 10 AM" src="https://user-images.githubusercontent.com/28145373/77914750-61b88480-7264-11ea-8b9a-84c1460de57b.png">
<img width="948" alt="Screen Shot 2020-03-30 at 8 56 56 AM" src="https://user-images.githubusercontent.com/28145373/77914806-6f6e0a00-7264-11ea-9667-0569a016cf74.png">
