### ISSUE TITLE
Reassess localization process to reduce storage on Transifex.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#8337]
We've uploaded a large number of Chromium strings (and their localized versions) to Transifex, which caused us to reach our limit of hosted words. Hosted Words = Source Words × Number of Target Languages (https://docs.transifex.com/account/viewing-and-managing-subscription#hosted-words).

A big portion of these strings isn't modified for Brave and likely doesn't need to be uploaded at all.

We need to consider an improvement to our localization process where only the strings that we modify get uploaded to Transifex and translated.

cc: @bsclifton @petemill @w0ts0n

**Comment by mKoonrad** [comment]
First of all I want to recommend change localization service to Crowdin. It's much more helpful for translators. Transifex is extremely uncomfortable! Transifex can't recognize strings to translate.

For example I have string:
`Do you want to fill in your &lt;ph name="CARD_DETAIL"&gt;$1&lt;ex&gt;Visa - 1234&lt;/ex&gt;&lt;/ph&gt;?`
To translate it first of all I need to decode it
`Do you want to fill in your <ph name="CARD_DETAIL">$1<ex>Visa - 1234</ex></ph>?`
Next step is deleting example text (ok, sometimes is useful)
`Do you want to fill in your <ph name="CARD_DETAIL">$1</ph>?`
and finally I can translate. It's very uncomfortable.

On Transifex also search form is uncomfortable, saving each translations (I need to wait for a second for each string). It's hard to jump between similar stings to unify texts.

Localization process is also unclear. Some texts you copy from Chromium, some texts are translated by users and some texts devs outsource to any commercial company. External translation company also isn't a good solution. They don't know exactly contexts and I often need to correct their crazy texts.

You need to unify whole process! I'd like to suggest hire proofreaders for each language but from advanced users of Brave browser only @bsclifton @petemill @w0ts0n

**Comment by bsclifton** [comment]
@bbondy did you recently resolve this?

**Comment by bbondy** [comment]
Yep we can call the original issue done, although there are some small follow up things. 
@mKoonrad for the Crowdin suggestion please post that as another issue for new consideration. Thank you!
