### ISSUE TITLE
Sync must not send records if last get-existing response has is_truncated true

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#8338]
## Description 

We can fetch max 1000 records at the time, if there are more than 1000 records, they will be fetched on the next poll cycle. 
Also first  applying remote changes and then sending ours, this happens each minute. 
It is possible we fetch 1000 records apply them and then send our changes, but we would have another portion of remote records.
We must not send our changes until completely fetched all current available portions.

## Steps to Reproduce

   1. Prepare device A with 2000 bookmarks
   2. Prepare  device B with 1 bookmark, B1.com
   3. Connect them into the chain
   4. Wait until all would be synced
   5. Open inspector on deviceB, look for Brave Sync extension console log

## Actual result:

You will see device B sends B1.com before it fetched the second 1000 of bookmarks

## Expected result:
Device B  must send B1.com after it fetched all 2000 of bookmarks.

**Comment by bsclifton** [comment]
@AlexeyBarabash is this issue still relevant? or should it be closed w/ new sync v2 implementation?

**Comment by AlexeyBarabash** [comment]
@bsclifton yes, it will be not relevant with sync v2. Thanks, marked with the label you have mentioned.
