### ISSUE TITLE
Superhuman extension 2.3.4 stopped working after V1.3.118

### ISSUE THREAD

**Issue by oluapocram** [brave/brave-browser#8339]
## Description 

After upgrading to V1.3.118 the Superhuman Chrome extension stopped working. 

Superhuman Extension: 2.3.4
Brave Latest: V1.3.118

## Steps to Reproduce

   1. Install Superhuman 2.3.4 extension
   2. Go to mail.superhuman.com (login)
   3. Page will go to "Reload" 

## Actual result:

Attached.

## Expected result:

Go to superhuman inbox. 

## Reproduces how often: 

Permanent - currently broken. 

## Brave version (brave://version info)

Brave | 1.6.46 Chromium: 80.0.3987.116 (Official Build) dev (64-bit)
-- | --
Revision | dc00a510e4c2ae25c4d084cc3d946fc782249224-refs/branch-heads/3987@{#917}
OS | macOS Version 10.15.3 (Build 19D76)
JavaScript | V8 8.0.426.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
Command Line | /Applications/Brave Browser Dev.app/Contents/MacOS/Brave Browser Dev --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --disable-databases --enable-features=PasswordImport,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning,SimplifyHttpsIndicator,MixedContentSiteSetting,DnsOverHttps --disable-features=AllowPopupsDuringPageUnload,VideoPlaybackQuality,NotificationTriggers,AutofillServerCommunication,SmsReceiver,AudioServiceOutOfProcess,WebXR,LookalikeUrlNavigationSuggestionsUI,WebXrGamepadModule --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /Applications/Brave Browser Dev.app/Contents/MacOS/Brave Browser Dev
Profile Path | /Users/mpr/Library/Application Support/BraveSoftware/Brave-Browser-Dev/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

![image](https://user-images.githubusercontent.com/28657119/74986054-ad6a4980-53ed-11ea-90ea-37c3979ef59c.png)

**Comment by ryanbr** [comment]
Not the easiest to test, since the signup process is limited. Is still occuring @oluapocram ? Have you reached out to Superhuman see if they're aware of it?

Trying to reach out. https://twitter.com/fanboynz/status/1259437018670444544

**Comment by ryanbr** [comment]
Everything resolved @oluapocram ?

**Comment by oluapocram** [comment]
This started working after a new build of Brave. Don’t recall which one specifically. You can close.
