### ISSUE TITLE
Ensure that referer-blocking can be configured with a standalone Shields toggle

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#8340]
As currently implemented, referer-blocking is [controlled by the Shields toggle for cookies](https://github.com/brave/brave-core/blob/029b47ee56a4534830656d3a74858750cf11b11c/components/brave_shields/browser/brave_shields_util.h#L49-L52). Instead, referer-blocking should be controlled by its own Shields sub-toggle.

This issue doesn't cover the design or implementation of the Shields UX to control referer-blocking. It's only about the back-end work necessary to allow that front-end work to happen.

**Comment by pes10k** [comment]
Closing this since, with the new referer policy changes, we dont expect anyone will need to turn this off
