### ISSUE TITLE
P3A: Ask for search volume and default search engine

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#8341]
**Question 1**: 
_How many times did you search last week?_
(The omnibox input doesn't resolve and triggers a search)

**Answers**: 
```
0) Never
1) 1 to 5 times
2) 6 to 10 times
3) 11 to 20 times
4) 21 to 50 times
5) 51 to 100 times
6) 101 to 500 times
7) More than 500 times 
```

**Justification**: 
The volume of search activity generated via Brave will help us identify the optimal search strategy for both product development and partnerships

**Question 2**: 
_Which is your currently selected search engine?_ 

**Answers** (edit as suggested by iefremov in the comments below): 
```
0) Other
1) Google
2) DDG
3) Startpage
4) Bing
5) Qwant
```
**Justification**: 
We need to understand people's search preferences

**Comment by iefremov** [comment]
@mattmcalister @davidtemkin Are we ok to report Question 2 "Which search engine is your default?" just once on a browser startup?

**Comment by mattmcalister** [comment]
> @mattmcalister @davidtemkin Are we ok to report Question 2 "Which search engine is your default?" just once on a browser startup?

Once per weekly round of questions, yes. Or do you mean once ever?

**Comment by davidtemkin** [comment]
I think we wanted to know what the user's default engine (based on browser default, not user-settable, but instead the same for all users in a given country at a given time) is ; and then we want to track what engine they're currently using to determine how many have switched from what default to what user-selected option.

**Comment by mattmcalister** [comment]
> I think we wanted to know what the user's default engine (based on browser default, not user-settable, but instead the same for all users in a given country at a given time) is ; and then we want to track what engine they're currently using to determine how many have switched from what default to what user-selected option.

@davidtemkin the idea here was to track the simplest data first...what is your default right now? nothing else. for marketshare purposes. the question of switching can be interpreted multiple ways depending on how you write it, so I had planned to introduce that next and separately.

**Comment by davidtemkin** [comment]
OK-- I see, terminology problem. That question should probably be phrased "what is your currently selected search engine?"

@iefremov and I both interpreted "default" in terms of the browser default search engine. I'd say a user has a currently selected search engine, while the browser has a default search engine.

**Comment by mattmcalister** [comment]
> a user has a currently selected search engine, while the browser has a default search engine.

yes, ok, that is what is intended here. _"What is your currently selected search engine?"_

Updated above.

**Comment by iefremov** [comment]
For `Question 2` I suggest to move "Other" to bucket 0, so adding new engines to the end of the list would be less confusing. That said,
```
0) Other
1) Google
2) DDG
3) Startpage
4) Bing
5) Qwant
```
@davidtemkin @mattmcalister OK?

**Comment by iefremov** [comment]
WIP PR https://github.com/brave/brave-core/pull/4771 (need to add/fix tests)

**Comment by iefremov** [comment]
Added `Brave.Search.DefaultEngine`
buckets:
0) Other
1) Google
2) DDG
3) Startpage
4) Bing
5) Qwant

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/brave-core/pull/4771

**Comment by iefremov** [comment]
This shouldn't be closed since only Question2  was implemented in the linked PR. So moving Question 1 to https://github.com/brave/brave-browser/issues/8854

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.7.78 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Windows 10 OS Version 1803 (Build 17134.1006)



- Verified the scenarios from https://github.com/brave/brave-core/pull/4771#issuecomment-603708874
