### ISSUE TITLE
Disable ScrollToTextFragment

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#8342]
https://www.theregister.co.uk/2020/02/20/chrome_deploys_deeplinking/

**Comment by jumde** [comment]
https://chromium.googlesource.com/chromium/src/+/62f8d5f096b174d05cd7f716585983df483024d7%5E%21/#F0 - This is enabled in Chromium using Finch, will be enabled by default in M81.

**Comment by LaurenWags** [comment]
@jumde if this issue requires manual QA please add `QA/Yes` label and a test plan. If not, please add `QA/No` label. Thanks! cc @kjozwiak

**Comment by jumde** [comment]
@LaurenWags - added the test plan to the description, let me know if you need more details.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.8.71 Chromium: 81.0.4044.92 (Official Build) dev (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from the description
<img width="1194" alt="Screen Shot 2020-04-10 at 11 27 34 AM" src="https://user-images.githubusercontent.com/28145373/79002585-c1454880-7b1e-11ea-9928-6e1177d085a2.png">

* Confirmed test plan from description does work in Chrome (`81.0.4044.92`) as noted.

**Comment by dylan-k** [comment]
but why? This is a useful feature and its risks are avoidable. Could it be optional at least?

**Comment by pirate** [comment]
I've opened a new issue to formally request they re-add this flag: https://github.com/brave/brave-browser/issues/42393

Please comment/vote over there as comments on closed PRs and issues likely wont get seen.
