### ISSUE TITLE
Add Brave app automatically to Full disk access panel

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#8343]
After merging https://github.com/brave/brave-core/pull/4530, brave isn't added that panel automatically.
In that PR, it checks safari folder permission by using `PathIsWritable()`.
Maybe other file access api  like `open` could add automatically.

**Comment by rebron** [comment]
For context to add Brave into the panel: https://github.com/brave/brave-core/pull/4530#issuecomment-591821251

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 x64` using the following build:

```
Brave | 1.11.80 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.15.5 (Build 19F101)
```

* went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/8343#issue-568740280
* verified that once you select `Import` when importing from `Safari`, Brave is added into `Full Disk Access` but not selected
* ensured that selecting `Open System Preferences` correctly opens `Security & Privacy`
* ensured that selecting `Cancel` closes the modal and doesn't open `Security & Privacy`
  * ensured that when cancelling, Brave is still added into `Full Disk Access` but not selected
* ensured that import from `Safari` works from once `Full Disk Access` is given to `Brave`
  * ensured that both `History` & `Bookmarks/Favourites` were being imported

<img width="705" alt="Screen Shot 2020-06-29 at 12 42 35 PM" src="https://user-images.githubusercontent.com/2602313/86033857-a2f93580-ba07-11ea-943e-e8b2e3be1cf4.png">

<img width="537" alt="Screen Shot 2020-06-29 at 12 50 33 PM" src="https://user-images.githubusercontent.com/2602313/86033866-a55b8f80-ba07-11ea-881c-ccaf43bcaf1c.png">

**Comment by LaurenWags** [comment]
Using Mojave 10.14.6 the test plan from the description is not working for me.

Steps:
1. Navigated to System Prefs > Security & Privacy > Privacy and confirmed `Brave Browser Dev` was not in the list. Closed System Prefs.
2. Clean profile w/ 1.11.x
3. Opened brave://settings/importData (Safari is default) and clicked on Import
4. Got the popup as expected:
<img width="532" alt="Screen Shot 2020-06-29 at 1 17 18 PM" src="https://user-images.githubusercontent.com/28145373/86035782-e1dcba80-ba0a-11ea-9899-c07171e92ce3.png">

5. Clicked on `Open System Preferences`.
6. System Prefs was opened but Brave Browser Dev was not in the list automatically, although I could add it manually.
<img width="690" alt="Screen Shot 2020-06-29 at 1 18 08 PM" src="https://user-images.githubusercontent.com/28145373/86035875-00db4c80-ba0b-11ea-87dd-55a0ba9c8f28.png">

```
Brave | 1.11.80 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)
```

**Comment by kjozwiak** [comment]
@rebron @simonhong could someone check to see if the above works for you on `Catalina`? @simonhong do you know if the above fix should also be working on `Mojave` or is this only for `>=Catalina`?

**Comment by simonhong** [comment]
@kjozwiak This works on my local macOS(Catalina).
This was fixed indirectly by using OS independent file open API. If application tries to open some files/folders that needs full disk access permission, catalina seems to add that application to the list automatically.
I think this behavior could be dependent on os version.
