### ISSUE TITLE
Brave rewards withdraw not working

### ISSUE THREAD

**Issue by serp777** [brave/brave-browser#8344]
## Description 
Withdraw button on brave rewards page does not work. Brave shows I have BAT, but pressing the withdraw button does nothing and uphold wallet says that I have 0.00 BAT.

## Steps to Reproduce
1. Associate a valid uphold wallet with brave rewards.
2. Get some BAT in the local brave wallet.
3. Click withdraw and see if BAT shows up in uphold

## Actual result:
![BRaveBrowser](https://user-images.githubusercontent.com/10540204/75007354-ad883a80-5429-11ea-87c5-8219afde4ddc.PNG)
![Uphold](https://user-images.githubusercontent.com/10540204/75007356-aeb96780-5429-11ea-9e51-71f51d22bea9.PNG)

## Expected result:
BAT shows up in uphold.com account

## Reproduces how often: 
Every time

## Brave version (brave://version info)

Windows 10, standard build: Version 1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit)

Brave | 1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit)
-- | --
Revision | dc00a510e4c2ae25c4d084cc3d946fc782249224-refs/branch-heads/3987@{#917}
OS | Windows 10 OS Version 1903 (Build 18362.657)
JavaScript | V8 8.0.426.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,AllowPopupsDuringPageUnload,WebXrGamepadModule,LookalikeUrlNavigationSuggestionsUI,WebXR,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,VideoPlaybackQuality --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\aruss\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | 5e3a236d-4113a79e

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Yes
- Can you reproduce this issue with the dev channel?
Yes
- Can you reproduce this issue with the nightly channel?
Yes

## Other Additional Information:

Many other people are experiencing this on reddit

**Comment by serp777** [comment]
bump

**Comment by NejcZdovc** [comment]
this will be fixed with https://github.com/brave/brave-browser/issues/8354
