### ISSUE TITLE
Can't scroll between tab header bar to view new tabs when maximum visible tab header count is exceeded

### ISSUE THREAD

**Issue by codex-dev** [brave/brave-browser#8350]
## Description 
When maximum visible tab count is reached, user cant scroll left to view newly open tabs. The only way to view them is to close tabs on their right until it become visible.

## Actual result:

![image](https://user-images.githubusercontent.com/34751193/75022322-e5d85900-54bb-11ea-884e-32d3c08a83e2.png)

## Expected result:
Showing left, right navigation arrows at the start/end of tab header bar to scroll between tabs, when maximum visible tab count reached.
![image](https://user-images.githubusercontent.com/34751193/75022956-005f0200-54bd-11ea-932d-30bed16358d2.png)

## Brave version (brave://version info)

Brave | 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1909 (Build 18363.657)
JavaScript | V8 8.0.426.16
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --disable-sync --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,WebXR,LookalikeUrlNavigationSuggestionsUI,VideoPlaybackQuality,WebXrGamepadModule,AllowPopupsDuringPageUnload,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service
Variations | 5e3a236d-4113a79e

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes

**Comment by bsclifton** [comment]
Thanks for the report, @codex-dev! We used to have a feature called Tab Pages that made this easier. We're tracking this with https://github.com/brave/brave-browser/issues/35 in case you'd like to subscribe and/or give input

I'm going to close this issue as a duplicate. Thanks again! 😄
