### ISSUE TITLE
Re-logging #5759 - WordPress Jetpack Statistics tracker script not being blocked

### ISSUE THREAD

**Issue by willstocks** [brave/brave-browser#8351]
I run a WordPress blog. On that blog, I have Jetpack installed and I'm using the [Jetpack Stats module](https://jetpack.com/support/wordpress-com-stats/) enabled, which adds a little script to my frontend: https://stats.wp.com/e-201934.js

Looking at Shields, this script/tracker is blocked (rightly so):
![image](https://user-images.githubusercontent.com/43744514/63494531-c7b28180-c4b5-11e9-9651-61cae7db16f9.png)

HOWEVER... on every page view, I can see my stats counter increasing in my backend. I quickly tested this on a dev version of my site, where I am the only visitor and I still see the backend counter increasing... even though Shields is showing that the script/tracker has been blocked?

## Steps to Reproduce

   1. Setup a basic WP site with Jetpack enabled (connected to wp.com) and the stats module enabled
   2. Logout of wp-admin and visit that site (Private Mode, non-Private mode) 
   3. Log back in to wp-admin and see the stats counter has increased. Same is reflected on 

Alternatively, visit [willstocks.co.uk](https://willstocks.co.uk) and you can see the exact same as the above there.

## Actual result:

Not an easy way for me to grab a screenshot... but I refreshed my page/visited every single one of my blog posts consecutively and every single one of those page views was reflected in Jetpack stats

Furthermore, on a network that has monitoring, I can see DNS requests successfully being made to stats.wp.com.

## Expected result:
Shields shows it has been blocked... so those page views shouldn't be recorded? When I used Google Analytics, Brave page views weren't recorded there - this is the same in principle? If the script is actually allowed, it shouldn't show as blocked?

1) Shields should be blocking this before the request is made?
2) Monitoring the Network tab in dev tools shows the request is successful as well

All of these should fail? 

## Reproduces how often: 

Every time I visit my blog [willstocks.co.uk](https://willstocks.co.uk)

## Brave version (brave://version info)

Brave | 1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit)
-- | --
Revision | dc00a510e4c2ae25c4d084cc3d946fc782249224-refs/branch-heads/3987@{#917}
OS | Windows 10 OS Version 1909 (Build 18363.657)
JavaScript | V8 8.0.426.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --profile-directory=Default --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,WebXrGamepadModule,AllowPopupsDuringPageUnload,VideoPlaybackQuality,LookalikeUrlNavigationSuggestionsUI,WebXR,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\WillStocks\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | 5e3a236d-4113a79e

_Note: Not sure why the above shows a 32-bit executable path when I have 64-bit installed?_

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes - has been on-going since 0.67.125 (see #5759)
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@willstocks Wanted to check-in to see if you're still running into this issue with our current version 1.30.87.

**Comment by ryanbr** [comment]
No response since the last response. I did check. still being blocked. Both the shields and networking showing the same network blocks.
**Shields:**
![willstocks](https://user-images.githubusercontent.com/1659004/204412499-05a688cc-c5cd-4aa3-b433-133ae9403bfa.png)
**Network:**
![willstocks2](https://user-images.githubusercontent.com/1659004/204412845-c9764f61-7ec3-438b-b2bb-2788e0df4fba.png)
