### ISSUE TITLE
"-2111914805B Estimated Bandwidth Saved"

### ISSUE THREAD

**Issue by JuliusRockeiro** [brave/brave-browser#8359]
![image](https://user-images.githubusercontent.com/4733304/75104016-9b8cd000-55c0-11ea-8ad5-dd57b69d4dcf.png)

**Comment by bsclifton** [comment]
cc: @AndriusA

**Comment by JuliusRockeiro** [comment]
Version 1.7.10 Chromium: 80.0.3987.116 (Official Build) nightly (64-bit)

**Comment by AndriusA** [comment]
I've not been able to reproduce the specific issue, but found one place where the aggregate (in bytes) as a 64 bit number was getting stuffed into a 32 bit integer, possibly causing the overflow.

The number still shouldn't have gotten high enough to overflow, but not impossible (just over 2GB prediction in aggregate would overflow). Added an addition outlier catch for individual predictions anyway

**Comment by bsclifton** [comment]
Added missing milestone for this issue

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.71 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

* Confirmed bandwidth stat does not display on NTP on desktop per https://github.com/brave/brave-browser/issues/8256
<img width="1192" alt="Screen Shot 2020-03-24 at 8 17 15 AM" src="https://user-images.githubusercontent.com/28145373/77425379-050f2280-6da9-11ea-83ef-c91df40bce58.png">
