### ISSUE TITLE
Remove 'get paid' verbiage on Sponsored Images and make BRE update

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#8360]
## Description
The word "paid" showing up in the context of seeing sponsored images was causing problems with getting our app approved by Apple. Make copy on Android consistent with iOS updates.

Include the new BRE text updates as well.

This issue can be done as part of https://github.com/brave/brave-browser/issues/9555

### State diagram

With the Brave Rewards everywhere and new onboarding update, messages on the NTP relating to sponsored images and prompting users to opt-in are reduced for both iOS and Android.

- NTP banner showing when Brave Rewards is OFF is removed
- NTP banner on a regular wallpaper prompting user to turn on Ads is removed
- NTP banner on SI prompting user to turn on “Earn & Give” has a text change
- NTP banner on SI notifying users who have already turned on “Earn & Give” that they are earning tokens has a text change

![Android Sponsored image message BRE update jpg](https://user-images.githubusercontent.com/2388823/81097062-31e04a80-8ebc-11ea-8f40-d0b21ae4799a.jpg)

### User Flow

![BRE + get paid](https://user-images.githubusercontent.com/2388823/81603494-48d2e100-9383-11ea-813d-c7309416c8d8.png)

### Assets
Figma link: https://www.figma.com/file/OM4s5mEYi3ZMKhLuHYQJfs/Sketchimport-android-sponsored-image?node-id=0%3A1

**Comment by srirambv** [comment]
Blocked on https://github.com/brave/brave-browser/issues/10795

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.11.102 64 build

### Ads on
SI tab  | Open modal
-- | --
![image](https://user-images.githubusercontent.com/17010094/88901440-af5ff080-d248-11ea-814d-5463290934dd.png)| ![image](https://user-images.githubusercontent.com/17010094/88904603-31521880-d24d-11ea-891f-e53d09f97e24.png)

### Ads off
SI tab | Open modal | ToS page
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/88904910-9443af80-d24d-11ea-8bc1-3e7c8e0ee9ed.png) | ![image](https://user-images.githubusercontent.com/17010094/88904938-9d348100-d24d-11ea-84c4-efe33b358db0.png) | ![image](https://user-images.githubusercontent.com/17010094/88907972-31ecae00-d251-11ea-9abd-4d0e7baf9bfa.png)

* Verified clicking on terms opens a custom tab and loads ToS page
* Verified Learn more and Hide sponsored image buttons works as expected
--------


### Ads on
SI Tab | Open Modal
--|--
![image](https://user-images.githubusercontent.com/17010094/88905892-b8ec5700-d24e-11ea-8c6e-f1eb826d06e8.png) | ![image](https://user-images.githubusercontent.com/17010094/88906260-239d9280-d24f-11ea-95df-c3b6515f64c6.png) | 

### Ads off
SI tab | Open modal | ToS page
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/88906617-8ee76480-d24f-11ea-821b-5ca88b81aed2.png) | ![image](https://user-images.githubusercontent.com/17010094/88906566-7d05c180-d24f-11ea-8a20-b1ae64f6458b.png) | ![image](https://user-images.githubusercontent.com/17010094/88907100-2baa0200-d250-11ea-802c-46d8f417e91d.png)

* Verified clicking on terms opens a custom tab and loads ToS page
* Verified Learn more and Hide sponsored image buttons works as expected

--------

Logged follow up issue for #11010 for ad grant notification not being shown on SI tab.
