### ISSUE TITLE
[Desktop] Decouple sponsored image messages from BR widget

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#8361]
### Description

Currently, a message about sponsored images is shown in the Brave Rewards widget the first time a user sees a sponsored image.The new updates to the Brave Rewards widget streamlines the design and makes it more contextual to the user experience by removing the message about sponsored images from the Brave Rewards widget and instead positions it above the sponsored logo. 

### Designs

With BRE and the BR widget design update, messages on the NTP relating to sponsored images are reduced and decoupled from the BR widget.

Show a message about the sponsored message above the logo the for a total viewing time of 5s when a sponsored image appears to the user:

Brave Rewards and ads on:

![image](https://user-images.githubusercontent.com/2388823/135352017-978cfacf-b4fb-4f87-9c08-55e83708b510.png)

Brave rewards and ads off:

![image](https://user-images.githubusercontent.com/2388823/135352511-942676b3-e84c-40a0-8df7-131381f0d6c7.png)

The sponsored image message can be shown independently of the Brave Rewards widget state: BR widget on/off, claim rewards notification showing or not, ads on/off, for example: 

![image](https://user-images.githubusercontent.com/2388823/135352305-738b7ca5-6624-46a1-908a-82a78a4971e0.png)

![image](https://user-images.githubusercontent.com/2388823/135352474-350c7e15-ebc5-4745-b310-eee3cc5fa27a.png)

These updates bring the desktop sponsored image messages closer to iOS/Android UX. No changes to sponsored image messages required on iOS/Android.

### Assets
Figma link: https://www.figma.com/file/oWF3SKW1KSQxFpSKPskpoh/?node-id=42%3A1943

**Comment by karenkliu** [comment]
@rebron When are we doing this? iOS/Android already merged and closed their respective issues

**Comment by rebron** [comment]
We'll see if we can get this updated for 1.7.x but we also don't have the same urgency as we're not bound by the app or android stores.

**Comment by karenkliu** [comment]
@rebron I updated this to include the BRE changes

**Comment by rebron** [comment]
@ryanml Wasn't sure how you wanted to handle the prs for v2 spec. But we have this issue open as well.
cc: @karenkliu

**Comment by rebron** [comment]
Closing. Fixed with the new BR widget.
