### ISSUE TITLE
Ad conversion detection fails if the target URL of the last shown ad matches the conversion URL pattern

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#8362]
## Description 

Ad conversion detection fails if the target URL of the last shown ad matches the conversion URL pattern

## Steps to Reproduce

   1. View an ad
   2. Navigate to a URL which matches the URL pattern as defined in the ad catalog

## Actual result:

Ad conversion is not detected

## Expected result:
Ad conversion should be detected

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.5.54+

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? Yes
- Is the issue reproducible on the latest version of Chrome? Yes

## Miscellaneous Information:

```"conversions":[ 
  { 
	 "observationWindow":86400,
	 "urlPattern":"https://travala.com/booking?check_in=*",
	 "type":"postview"
  }
],
```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.7.54 Chromium: 80.0.3987.132 (Official Build) nightly (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Ubuntu 18.04 LTS

Verified following patterns:
[FAIL] Logged https://github.com/brave/brave-browser/issues/8648
`urlPattern`:  `https://travala.com`
`targetUrl`: `https://travala.com`

[PASS] 
`urlPattern`:  `https://travala.com/`
`targetUrl`: `https://travala.com/`

[PASS]
`urlPattern`:  `https://travala.com/booking/`
`targetUrl`: `https://travala.com/*/`


Verification passed on

Brave | 1.7.54 Chromium: 80.0.3987.132 (Official Build) nightly (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verified the above patterns

**Comment by kjozwiak** [comment]
Thanks for running through this @btlechowski. Going to remove the labels as this will need to be rechecked on `1.5.x` once https://github.com/brave/brave-core/pull/4719 gets uplifted.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.5.111 Chromium: 80.0.3987.132 (Official Build) (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Ubuntu 18.04 LTS

Verification passed on

Brave | 1.5.111 Chromium: 80.0.3987.132 (Official Build) (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Ubuntu 18.04 LTS

Verified conversions for ads from different sets with matching url pattern
Catalog: [different sets matching patterns.txt](https://github.com/brave/brave-browser/files/4330762/different.sets.matching.patterns.txt)
- Verified when view->conversion were done one after another
Both ads were converted
- Verified when view was done at the same time and the conversion after the views
Both ads were converted

Verified conversions for ads from the same set with matching url pattern
Catalog: [same set matching patterns.txt](https://github.com/brave/brave-browser/files/4330911/same.set.matching.patterns.txt)
- Verified when view->conversion were done one after another
[25808:1:0313/191839.356437:INFO:ad_conversion_tracking.cc(178)] Started ad conversion timer for uuid 36c84fcb-6388-45d8-81ed-5a5d986cd7ef and creative set id de5a82e1-17d6-47e0-a368-17f8f56dfeb3 which will trigger on 2020-03-13 18:22:56.000 UTC
[25808:1:0313/192256.349896:INFO:ad_conversion_tracking.cc(143)] Ad conversion for uuid 36c84fcb-6388-45d8-81ed-5a5d986cd7ef with creative set id de5a82e1-17d6-47e0-a368-17f8f56dfeb3 triggered on 2020-03-14 17:58:56.000 UTC
First ad was converted (expected). Second ad was shown (not expected). Logged https://github.com/brave/brave-browser/issues/8645
- Verified when view->conversion were done at the same time
First ad shown, but not converted (expected). Second ad was converted.
