### ISSUE TITLE
Downloads cause tab to be unusable

### ISSUE THREAD

**Issue by gettyhub** [brave/brave-browser#8364]
## Description 
Have multiple windows/tabs open, a whole window becomes affected by a download in a single tab in that window, and the whole window becomes unusable/unresponsive, but all other windows still respond normally

## Steps to Reproduce

   1. Have multiple tabs/windows open
   2. Download a file from a webpage
   3. 

## Reproduces how often: 
Seems to intermittently freeze the entire window after downloading.

## Brave version (brave://version info)
Ongoing.  Using brave-binary (brave-bin ArchLinux)

## Version/Channel Information:
Only using current.

**Comment by rebron** [comment]
cc: @srirambv

**Comment by bsclifton** [comment]
Closing as there haven't been any updates
