### ISSUE TITLE
Settings Page Grey Square top right corner

### ISSUE THREAD

**Issue by phoogm** [brave/brave-browser#8365]
## Test plan
See https://github.com/brave/brave-core/pull/5842

## Description 

For Brave 1.3.118 on the settings page a grey square is displayed top right underneath the menu bar.

## Steps to Reproduce

   1. Using Brave desktop browser 1.3.118 for Mac, open the settings page
   2. Check the spot underneath the menu bar top right site, a grey square is displayed
   3. When the settings are show the grey square will appear on top of the scrollbar, when the about Brave panel is displayed the grey square is also displayed.

## Actual result:

![settings grey block](https://user-images.githubusercontent.com/56597375/75095469-51422980-5595-11ea-91b9-2a23595b6ec2.png)

## Expected result:
Grey Square should be removed from settings page layout.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit)
Revision | dc00a510e4c2ae25c4d084cc3d946fc782249224-refs/branch-heads/3987@{#917}
OS | macOS Version 10.15.3 (Build 19D76)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes - 1.3.118
- Can you reproduce this issue with the beta channel? Yes - 1.5.96
- Can you reproduce this issue with the dev channel? Yes - 1.6.47
- Can you reproduce this issue with the nightly channel? Yes - 1.7.7

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

## Miscellaneous Information:

Checked Brave 1.3.118 on Windows 10 and Brave 1.3.118 on Ubuntu and they have the same issue.

**Comment by rebron** [comment]
cc: @petemill One of those, once you see it, can't unsee it bugs.

**Comment by bsclifton** [comment]
Talked with @petemill and showed the bug - this should be in `br_toolbar` component. I can check this out 😄

**Comment by bsclifton** [comment]
Fixed with Chromium 84 🎉

**Comment by btlechowski** [comment]
Marking as QA/Blocked - need a new build to test, 1.11.92 or newer.

**Comment by LaurenWags** [comment]
Removing `QA/Blocked`, build https://github.com/brave/brave-browser/releases/tag/v1.11.92 is available

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.92 Chromium: 84.0.4147.68 (Official Build) dev (64-bit)
-- | --
Revision | e7b7234037639b407e69c5428c891ce018cd6c0d-refs/branch-heads/4147@{#772}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5842
* Confirmed no square in top right corner of scroll bar, checked for both light and dark themes:
<img width="99" alt="Screen Shot 2020-07-08 at 8 18 37 AM" src="https://user-images.githubusercontent.com/28145373/86918232-63f86d80-c0f4-11ea-8210-4ab8e06bff26.png">
<img width="126" alt="Screen Shot 2020-07-08 at 8 23 52 AM" src="https://user-images.githubusercontent.com/28145373/86918235-65299a80-c0f4-11ea-930a-9710f67e91f3.png">

* Confirmed brave://downloads still has ellipsis menu and it can be clicked on. Confirmed single option on menu worked as expected.
<img width="822" alt="Screen Shot 2020-07-08 at 8 19 07 AM" src="https://user-images.githubusercontent.com/28145373/86918314-8094a580-c0f4-11ea-9171-e182081f4ba1.png">
<img width="822" alt="Screen Shot 2020-07-08 at 8 19 15 AM" src="https://user-images.githubusercontent.com/28145373/86918319-825e6900-c0f4-11ea-9a63-d1403621edda.png">

* Confirmed brave://bookmarks still has ellipsis menu and it can be clicked on. Confirmed each option on menu worked as expected.
<img width="856" alt="Screen Shot 2020-07-08 at 8 19 55 AM" src="https://user-images.githubusercontent.com/28145373/86918338-8e4a2b00-c0f4-11ea-9efc-d95821edeb59.png">
<img width="853" alt="Screen Shot 2020-07-08 at 8 20 05 AM" src="https://user-images.githubusercontent.com/28145373/86918342-8ee2c180-c0f4-11ea-8d08-bad6f95d509f.png">
