### ISSUE TITLE
Uh oh! The Brave Rewards server is not responding. We will fix this as soon as possible.

### ISSUE THREAD

**Issue by kc4knc** [brave/brave-browser#8366]
I get this error message for 4 days and not fixed yet. I updated browser disabled and enabled rewards but nothing changed.

Brave | 1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit)

OS | Windows 10 OS Version 1909 (Build 18363.657)

![Annotation 2020-02-22 201048](https://user-images.githubusercontent.com/39414668/75096353-ddf9e100-55af-11ea-93c5-14480f59a6ca.png)

**Comment by bsclifton** [comment]
cc: @jsecretan @NejcZdovc

**Comment by kc4knc** [comment]
thanks for your great attention

**Comment by NejcZdovc** [comment]
@kc4knc is this still a problem? Did you maybe switch between versions? Could you send us data from brave://rewards-internals/. Thank you

**Comment by kc4knc** [comment]
Yes it is. How can I switch between versions my wallet is kinda suspended for now. I tried to restore my wallet on Nightly version but no BAT is restored.

**Comment by kc4knc** [comment]
@NejcZdovc here is the info you wanted.

Key Info Seed: Valid
Wallet Payment ID: bb7f1d9a-3c52-46ca-aa88-673c0769dfb1
Persona ID: 082d08b8-2100-47e1-b228-fe977f413b5b
User ID: 082d08b821007e1b228fe977f413b5b
Wallet created: 2/6/2020

**Comment by kc4knc** [comment]
This is what happened when I restored my wallet on Brave Beta/Nightly. ![image](https://user-images.githubusercontent.com/39414668/79009254-c4185b80-7b67-11ea-83e5-6d02e9e8c94f.png)

**Comment by jsecretan** [comment]
Seeing this report on community too: https://www.reddit.com/r/BATProject/comments/gavez3/uh_oh_the_brave_rewards_server_is_not_responding/

**Comment by kc4knc** [comment]
> Seeing this report on community too: https://www.reddit.com/r/BATProject/comments/gavez3/uh_oh_the_brave_rewards_server_is_not_responding/

Thanks. I posted there as well.

**Comment by bsclifton** [comment]
I think it's fair to say that rewards is broken for @kc4knc - there isn't a server outage. More likely, something about the ledger state is corrupt.

For example, @tmancey and I had found we can get into a broken state by enabling via brave://rewards or onboard wizard and then crashing directly after that (before it saves). This makes ledger think wallet is corrupt and also breaks ads

Are there any troubleshooting steps folks can try if they get stuck in this state?

**Comment by bsclifton** [comment]
I did some troubleshooting and was going to prepare steps to help - but then I ran into this issue myself 😄 I shared my profile with @NejcZdovc who will look at diagnosing

**Comment by NejcZdovc** [comment]
@bsclifton problem that you saw is expected as you downgraded browser versions. We don't support that as when you update schemas can change for json files or db, so when you downgrade browser is trying to get something that is not there anymore

**Comment by sympatiko04** [comment]
Brave claim rewards doesn't work on all platforms IOS MAC ANDROID Windows.

**Comment by sympatiko04** [comment]
Ok brave release an update then suddenly my BAT has been reduced!

**Comment by jsecretan** [comment]
Hi @sympatiko04 we are experiencing some server issues with the claims right now, I don't believe this has to do with updates.  Hopefully this should be resolved for you a little later in the day.  Thanks for your patience and sorry for the inconvenience.

**Comment by kc4knc** [comment]
I wouldn't believe they will give money for free maybe they do but it's certain that things are broken for me. I reinstalled browser and got a new wallet. If it crashes this time I'll keep using it because I liked the prebuilt privacy stuffs. If you use a browser to earn money, don't. I say those to who faced the same issue.

**Comment by jonathansampson** [comment]
I recently worked with a couple users who also encountered this error in their Brave Rewards page. We were able to resolve the issue by opening the Brave Rewards Panel, disconnecting their wallet, and reconnecting. Note: Unlike [other messages](https://twitter.com/BraveSampson/status/1259311676907806721), there is no ⨷ at the top-right.

![image](https://user-images.githubusercontent.com/815158/81586176-c3e3c980-937a-11ea-9e54-04f199978f64.png)

**Comment by NejcZdovc** [comment]
@jonathansampson this was fixed here https://github.com/brave/brave-browser/issues/9653

**Comment by kc4knc** [comment]
> @jonathansampson this was fixed here #9653

What if the wallet is unverified?

**Comment by NejcZdovc** [comment]
@kc4knc doesn't matter as it's the same logic for unverified and verified wallet

**Comment by kc4knc** [comment]
> @kc4knc doesn't matter as it's the same logic for unverified and verified wallet

I can't see disconnect button.

**Comment by NejcZdovc** [comment]
@kc4knc open panel and click on verify button. There should be disconnect

**Comment by jonathansampson** [comment]
@kc4knc I'm curious if you were able to resolve this following @NejcZdovc's steps above. Thanks!

**Comment by kc4knc** [comment]
> @kc4knc I'm curious if you were able to resolve this following @NejcZdovc's steps above. Thanks!

As I previously said I just reinstalled the browser and got a new wallet no issue with new wallet for now.

**Comment by kc4ca** [comment]
I am here again this time with a verified account. Now my balance doesn't appear on Uphold. I started to think Rewards is a sneaky advertisement to catch users.

**Comment by kc4ca** [comment]
@bsclifton @NejcZdovc

**Comment by kc4ca** [comment]
Even it is that's great way to take attention.

**Comment by NejcZdovc** [comment]
@kc4ca can you explain a little bit more what do you mean by balance doesn't appear on Uphold?

**Comment by kravietz** [comment]
This error is happening when you're using an old Brave installation. On Linux, if you ever installed Brave from the Beta apt channel, it will simply stop getting updated at some ancient version and show no updates are available, but this is only because the apt channel was abandoned and replaced by a new one. The solution is to go to https://brave.com/linux/ and update the apt channels using the new URLs and then you will suddenly get new versions and all works again.
