### ISSUE TITLE
[Android] Claiming a promotion from rewards settings page doesn't work (both ugp and ads).

### ISSUE THREAD

**Issue by gdregalo** [brave/brave-browser#8367]
## Description 
Claiming a promotion from rewards settings page doesn't work (for both ugp and ads promotion types).
Once it's fixed, please test scenario with multiple claims
(similar problem in tabs repo: # https://github.com/brave/brave-browser/issues/7760).

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by gdregalo** [comment]
Can not reproduce it on the latest master.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.117 x64 stable build
- Verified able to claim UGP grants via rewards page 
- Verified able to claim Ads grant via rewards page
--------
Verification passed on Samsung Tab A with Android 10 running 1.5.117 x64 stable build
- Verified able to claim UGP grants via rewards page 
- Verified able to claim Ads grant via rewards page
--------
