### ISSUE TITLE
Enforcing max-ads-per-hour at System Level

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#8368]
## Description 
Users can generate more than 5 ads per hour and 20 per day.

## Steps to Reproduce
1. Create multiple profiles in Brave (I made 4)
2. Opt all of them into Brave Rewards and Ads, and set max-per-hour to 5
3. Close all secondary profiles (I did this only after all had shown their first ad)

## Actual result:
When ads appear, they appear in multiples.

## Expected result:
Users should only see ads for active profiles.
The maximum number of ads per hour should potentially be enforced beyond the profile.

## Reproduces how often: 
Easily

## Brave version (brave://version info)
1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? TBD
- Can you reproduce this issue with the dev channel? TBD
- Can you reproduce this issue with the nightly channel? TBD

## Miscellaneous Information:
I continued to see ads delivered in sets even when only one profile instance was opened.

**Comment by jonathansampson** [comment]
Restarting the browser will return to showing only 1 ad at a time. Opening (and then closing) windows for the additional profiles will return to the buggy behavior.

**Comment by bsclifton** [comment]
Would be good to use local_state for this, versus profile settings

**Comment by tmancey** [comment]
@bsclifton @jonathansampson Related to https://github.com/brave/brave-browser/issues/7441 (however deciding whether to show an ad needs much more business logic based upon state stored in `Default/ads_service/client.json`. We are transitioning away from storing state in JSON to database(s) in https://github.com/brave/brave-browser/issues/5150 and https://github.com/brave/brave-browser/issues/5151 and can investigate how best to support multiple profiles.

**Comment by tmancey** [comment]
Fixed by https://github.com/brave/brave-core/pull/5574

**Comment by tmancey** [comment]
@jonathansampson I have raised https://github.com/brave/brave-browser/issues/9805 for "The maximum number of ads per hour should potentially be enforced beyond the profile."
