### ISSUE TITLE
[Android] Android Beta crashing on https://m.timesofindia.com/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#8369]
## Description 
Visiting `https://m.timesofindia.com/articleshow_comments/74258575.cms` causing a crash on Brave Beta

## Steps to reproduce 

   1. On clean profile/clean App settings.
   2. Open `https://m.timesofindia.com/articleshow_comments/74258575.cms`
   3. As the site loads url, it'll cause Brave to insta-crash.

## Actual result 
Crashes Beta

## Expected result
No Crash

## Issue happens on 
   - Current Play Store version? 1.5.90
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone, One Plus 6
   - Android version: Android 10
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? No

### Additional information
Brave Release on Android (1.5.5) works without crash

**Comment by SergeyZhukovsky** [comment]
Works as expected on the latest 1.5.97. Most likely it was fixed with that https://github.com/brave/brave-browser/issues/8316

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm 1.5.110.apk`
