### ISSUE TITLE
Compact navigation option

### ISSUE THREAD

**Issue by wiim23** [brave/brave-browser#8375]
Hi,
I develop a web app which be used on 10" tablet landscape.

To gain space height, is it possible to have an option on brave to compact navigation zone (chrome, before remove it, had an option for that... usefull).

I know the shortcut capability but i have on my web app some window.open.... and those open a new instance of brave with full topbar.

The perfect thing was to obtain a browser with the minimum height for adress bar and tab.  Is it possible to implement it?

**Comment by rebron** [comment]
Closing. Thanks for the report we would need some more detail on this actual feature request. I'd like to invite you to community.brave.com where you can discuss some of your ideas more before we turn it into a more actionable github issue.
