### ISSUE TITLE
Session Buddy extension doesn't work after updating Brave Dev

### ISSUE THREAD

**Issue by rudolphos** [brave/brave-browser#8378]
## Description 

After updating Brave Dev to the latest version extension Sesion Buddy doesn't work anymore, it just opens to crash description page.

## Steps to Reproduce

   1. open brave dev
   2. update to latest version
   3. download sessionbuddy extension

## Actual result:

![image](https://user-images.githubusercontent.com/4366810/75172135-71105380-5735-11ea-9e82-e2a9f9f4e5c0.png)

## Expected result:
![image](https://user-images.githubusercontent.com/4366810/75172214-92713f80-5735-11ea-8b6f-d85b20a7ec30.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.6.49 Chromium: 80.0.3987.116 (Official Build) dev (64-bit)
-- | --
Revision | dc00a510e4c2ae25c4d084cc3d946fc782249224-refs/branch-heads/3987@{#917}
OS | Windows 10 OS Version 1909 (Build 18363.657)

## Version/Channel Information:

Brave Dev

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? i don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

## Miscellaneous Information:

diagnostic details: 
```
Message: openDatabase is not defined; 
Name: ReferenceError; 
Stack: ReferenceError: openDatabase is not defined
    at new i (chrome-extension://edacconmaakjimmfgnblocblbcdcpbko/background.bundle.js:550:72)
    at new s (chrome-extension://edacconmaakjimmfgnblocblbcdcpbko/background.bundle.js:550:512)
    at Object.<anonymous> (chrome-extension://edacconmaakjimmfgnblocblbcdcpbko/background.bundle.js:667:29)
    at t (chrome-extension://edacconmaakjimmfgnblocblbcdcpbko/background.bundle.js:6:13)
    at chrome-extension://edacconmaakjimmfgnblocblbcdcpbko/background.bundle.js:8:99
    at chrome-extension://edacconmaakjimmfgnblocblbcdcpbko/background.bundle.js:8:109
```

**Comment by rudolphos** [comment]
It seems to be working now with latest dev update.

**Comment by rebron** [comment]
@rudolphos Thanks for confirming. Closing off.

**Comment by w0rldart** [comment]
The latest stable edition is now having this issue.
