### ISSUE TITLE
Offer "strip location metadata" option for image uploads (remove exif data)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#838]
Carried over from https://github.com/brave/browser-laptop/issues/6805
When uploading images on pages, users should have an option to strip out the EXIF data from images (which can contain device info, GPS coordinates, and more)

Original UI design circa January 2017:
![image](https://cloud.githubusercontent.com/assets/313317/22178270/b188180e-dfe6-11e6-9541-d27bee2f6af5.png)

**Comment by tomlowenthal** [comment]
You distracted me with that picture, so I'll note that modifying the OS file picket might be A Whole Thing. But a pref that you can flip once, or a "permission" that you can give sites…?

Possibly off-topic, but it's worth considering if there are other filetypes for which metadata removal would be valuable.

**Comment by alexiri** [comment]
This feature would be amazing! It's really easy to forget to sanitize images when uploading them and dox yourself.

**Comment by fmarier** [comment]
Let's merge with https://github.com/brave/brave-browser/issues/5238.
