### ISSUE TITLE
[Android] Safe Browsing doesn't work in android-core

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#8381]
## Description 

Safe Browsing isn't blocking anything in android core.

## Steps to reproduce 

   1. Visit https://testsafebrowsing.appspot.com/
   2. Try all of the links in the "Webpage Warnings"

## Actual result 

Not blocked.

## Expected result

Should be showing the red interstitial pages just like on desktop.

## Issue reproduces how often 

always

## Issue happens on 
   - Current Play Store version? no
   - Beta build? yes

## Device details
   - Device (Phone, Tablet, Phablet): Pixel 3a
   - Android version: 10
   
## Brave version

```
1.5.97 Chromium: 80.0.3987.116 (Official Build) beta (32-bit)
Revision	dc00a510e4c2ae25c4d084cc3d946fc782249224-refs/branch-heads/3987@{#917}
OS	Android 10; Pixel 3a Build/QQ1A.200205.002
```

**Comment by anthonypkeane** [comment]
Internal chat: https://bravesoftware.slack.com/archives/CM17J5QMU/p1583873767126500

**Comment by srirambv** [comment]
This is not working on 1.5.111 x64 stable build. Recording here https://bravesoftware.slack.com/archives/CM17J5QMU/p1584349279170400

**Comment by srirambv** [comment]
Superseded by https://github.com/brave/brave-browser/issues/8705. Moving out of milestone
