### ISSUE TITLE
Youtube (google) link don't show in the new tab [Android] 

### ISSUE THREAD

**Issue by rafaelcastrocouto** [brave/brave-browser#8382]
In the new tab most visited links, youtube never shows up. I'm guessing this has something to do with how google chrome handle their own links (seems like a way to make ppl use the app)

## Steps to reproduce 
   1. Fresh install. 
   2. Visit Youtube a few times
   3. It should appear on the new tab links

## Actual result 

It never appears.

## Issue reproduces how often 

Easily reproduced

## Device details

   - Install type (ARM, x86): ARM64
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 9
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? YES

**Comment by bsclifton** [comment]
Closing as stale - if you still run into this, please re-open. Thanks!
