### ISSUE TITLE
[Android] Disable translation service

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#8393]
Visit website http://hotnews.ro/ and see a translation dialog prompt. We need to disable it temporary until we get extensions support.

**Comment by yrliou** [comment]
Test plan specified in https://github.com/brave/brave-core/pull/4758.

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version running BraveModern arm 1.5.110.apk
   - Verified the test plan from https://github.com/brave/brave-core/pull/4758
