### ISSUE TITLE
Implement A/B Testing for Brave Ads

### ISSUE THREAD

**Issue by moritzhaller** [brave/brave-browser#8398]
For requirements search "Experiments for Brave Ads MiniSpec" on shared drive.

Devops ticket: https://github.com/brave/devops/issues/3778

**Comment by moritzhaller** [comment]
Blocked, needs scoping and defining requirements

**Comment by moritzhaller** [comment]
still finalising requirements and gathering info but starting to write boilerplate code so moving to in progress

**Comment by LaurenWags** [comment]
Testing notes from @tmancey can be found here: https://github.com/brave/brave-core/pull/6940#issuecomment-740160922

Thanks for the help with this one @tmancey 👍
