### ISSUE TITLE
Add site-hacks from browser-laptop

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#84]
Site hacks are to fix things like blocking banner ads, or to work around site restrictions.
https://github.com/brave/browser-laptop/blob/master/js/data/siteHacks.js

Implements some of the needed site-hacks for browser-laptop.

- [x] Empty data URL redirect for sp1.nypost.com
- [x] Empty data URL redirect for sp.nasdaq.com
- [x] Google tag services stub
- [x] Google tag manager stub
- [x] Block https://www.lesechos.fr/xtcore.js
- [x] Block  https://*.y8.com/js/sdkloader/outstream.js
- [x] Forbes custom cookie
- [x] Twitter NoScript redirect
- [x] Brave UA whitelist

TODO:
- [ ] Cookie exceptions
- [ ] Referrer exceptions
- [ ] Local storage exceptions

**Comment by bbondy** [comment]
Referrer, local storage, and cookie blocking site hacks will be implemented as part of: 
https://github.com/brave/brave-browser/issues/145

So closing this issue.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

* Verified data URL redirect for sp1.nypost.com and sp.nasdaq.com
* Verified Brave UA for DDG/Adobe/Netflix and Brave.com
* Verified Signing into Google Hangouts worked even with FP blocking it
* Verified `/xtscore.js` is blocked on `https://lesechos.fr`
* Verified Forbes custom cookie is set and no cookie modal is shown
* Twitter site hack doesn't work (Issue  #1240 logged)
