### ISSUE TITLE
content level tips for GH are disabled and tip button still displays

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8402]
## Description 
I have content level tips for GH disabled on brave://rewards (from Tips panel settings). However, content level tips are still showing on GH.

## Steps to Reproduce

   1. Have content level tips for GH disabled.
   2. Be logged into GH.
   3. Visit an issue (such as this one)

## Actual result:

Content level tips are still displayed:
<img width="693" alt="Screen Shot 2020-02-25 at 12 00 22 PM" src="https://user-images.githubusercontent.com/28145373/75269136-6eaa0a00-57c6-11ea-8f52-1e16f3585f43.png">

## Expected result:
Tip button should not be displayed

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.6.50 Chromium: 80.0.3987.116 (Official Build) dev (64-bit)
-- | --
Revision | dc00a510e4c2ae25c4d084cc3d946fc782249224-refs/branch-heads/3987@{#917}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? unsure
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @brave/legacy_qa

**Comment by NejcZdovc** [comment]
@LaurenWags this works for me on the latest master, could you please check it on the latest Nightly?

**Comment by LaurenWags** [comment]
@NejcZdovc seems to be working on latest nightly using both clean and upgrade profiles 👍 


Brave | 1.8.32 Chromium: 81.0.4044.69 (Official Build) nightly (64-bit)
-- | --
Revision | 6813546031a4bc83f717a2ef7cd4ac6ec1199132-refs/branch-heads/4044@{#776}
OS | macOS Version 10.14.6 (Build 18G3020)

**Comment by NejcZdovc** [comment]
@LaurenWags great, will close this one
