### ISSUE TITLE
Remove recurring flag from DoTip in rewards service in lib

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#8403]
`DoTip` has flag for recurring. Because we have `SaveRecurringTip` api now, we should remove this flag and in service call `SaveRecurringTip` if recurring. This should clear things

**Comment by GeetaSarvadnya** [comment]
Verification passed on


- Verified the test plan from https://github.com/brave/brave-core/pull/4870
Before changing the recurring tip value in panel
UI:
![image](https://user-images.githubusercontent.com/38657976/78106256-a719b500-7410-11ea-869d-982c2eac872a.png)


DB:
![image](https://user-images.githubusercontent.com/38657976/78106233-99642f80-7410-11ea-8281-fbff614ab918.png)
