### ISSUE TITLE
Remove Autoplay list, just do what chromium does

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#8408]
**Background**

Brave currently ships with a list of domains that can autoplay video and audio; sites on the list can, everyone else cannot. This is a usability / perf feature, originally put in out of dissatisfaction with how Chrome was handling autoplay.

**Problem**

This breaks a bunch of sites.  The list isn't maintained, its not anyone's direct responsibility.  Chromium has also caught up.  I super don't dig the "site engagement score" system Chromium uses for making determinations here, but since its not a privacy / security issue, I dont have strong concerns.

**Suggestion**

1. Remove Brave autoplay infrastructure
2. Just do what chromium does
3. (only if its quick) include ability for short term escape hatch, DAT-shipped settings for chromium-determined-overrides (e.g. "example.org" -> "always autoplay", "evil.org" -> "never autoplay", etc)

Spec: https://docs.google.com/document/d/16nicZYs8uf-CLNJc0FrIucwwhzajJ9IL0yUbyCpajBM/edit#

**Comment by pes10k** [comment]
cc: @rebron

**Comment by pes10k** [comment]
relevant chrome-side documentation

1. https://developers.google.com/web/updates/2017/09/autoplay-policy-changes <-- most specific
2. https://developers.google.com/web/updates/tags/autoplay <-- all of it

**Comment by BrendanEich** [comment]
Is anyone able to evaluate whether this leaves things autoplaying that shouldn't be? I'm in favor but want some kind of spot check if not audit.

**Comment by pes10k** [comment]
Talked with @ryanbr today, and he has heroically volunteered to do some manual eval of the diff.

So, sorted :)

**Comment by LaurenWags** [comment]
@pes10k @pilgrim-brave could one of you review and determine if this issue requires manual QA? if so, please add `QA/Yes` label and a test plan. If not, please add `QA/No` label. Thanks! cc @kjozwiak

**Comment by pes10k** [comment]
I believe @pilgrim-brave added automated tests, so i _think_ it shouldn't be needed, but he should confirm

**Comment by LaurenWags** [comment]
@pilgrim-brave pinging on https://github.com/brave/brave-browser/issues/8408#issuecomment-611619262 and https://github.com/brave/brave-browser/issues/8408#issuecomment-611619660 - could you take a look please? Thanks! cc @kjozwiak @bsclifton

**Comment by pilgrim-brave** [comment]
Yes, autoplay behavior is covered by automated tests.
