### ISSUE TITLE
[Android] Crash in ads winning category

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#8415]
Android beta which is based on 1.5.x branch crashes with such a call stack 
```
pid: 0, tid: 0 >>> com.brave.browser_beta <<<

Stack Trace:
  RELADDR   FUNCTION                              FILE:LINE
  00000000018d2e5e  ads::AdsImpl::GetWinningCategories()  ../../brave/vendor/bat-native-ads/src/bat/ads/internal/ads_impl.cc:886:36
```
The call stack points on that line https://github.com/brave/brave-core/blob/1.5.x/vendor/bat-native-ads/src/bat/ads/internal/ads_impl.cc#L886

**Comment by tmancey** [comment]
@SergeyZhukovsky Can you please send me the `Default/ads_service/client.json' state file please, thanks

**Comment by tmancey** [comment]
Fixed in https://github.com/brave/brave-browser/issues/7866

**Comment by SergeyZhukovsky** [comment]
that one is fixed
