### ISSUE TITLE
Add Speedreader view

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#8416]
## Description 
Give users the option to view "speedreadable" pages with an optimized layout for reading the page.

### User Flow
![speedreader user flow](https://user-images.githubusercontent.com/2388823/75905919-9ae30d80-5dfa-11ea-999d-b783e871d21f.jpg)

### States
Speedreader mode OFF:
![speadreader 1 - off](https://user-images.githubusercontent.com/2388823/75830601-1c3c9080-5d66-11ea-9f80-b1acda82a79e.png)
Speedreader mode OFF, hover + alt text:
![speadreader 2 - hover](https://user-images.githubusercontent.com/2388823/75830621-2a8aac80-5d66-11ea-8376-cddba39b041a.png)
Speedreader mode intro:
![speadreader 3 - intro](https://user-images.githubusercontent.com/2388823/75830661-3a09f580-5d66-11ea-8e1e-12c15f97e103.png)
This popover only shows the first time a user turns on Speedreader. It explains how our Speedreader differs from other browsers' reader views and why a page might not look any different even though Speedreader mode is toggled on. The user can dismiss it by clicking on the close button. It will auto-dismiss after 5 seconds if the user doesn't interact with it.

Speedreader mode ON but inactive:
![speadreader 4 - on inactive](https://user-images.githubusercontent.com/2388823/75830731-66257680-5d66-11ea-8ac3-eac6f8616825.png)
Speedreader mode ON but inactive, hover + alt text:
![speadreader 4 - on inactive hover](https://user-images.githubusercontent.com/2388823/75830746-78071980-5d66-11ea-9435-ac80df5e723f.png)

Speedreader mode ON and ACTIVE:
![speadreader 5 - on active](https://user-images.githubusercontent.com/2388823/75830809-9f5de680-5d66-11ea-917c-de56a616c18c.png)

Fonts: Times New Roman for headings and body, Arial for pictures and video captions

```
h1 {
font-size: 2em;
line-height: 1em;
}

subheading {
font-size: 1.5em;
line-height: 1em;
}

p { 
font-size: 1em;
line-height: 1.5em;
}
```
** Let's do a design review on this to tweak the CSS - these values are just a guess.

Speedreader mode ON and ACTIVE, hover + alt text:
![speedreader 6 - on active hover](https://user-images.githubusercontent.com/2388823/75830823-adac0280-5d66-11ea-9ab9-b040d73f39ba.png)

### Dark Theme

Dark theme is supported:
![dark theme 1](https://user-images.githubusercontent.com/2388823/75830560-ff07c200-5d65-11ea-8e8e-abd03c3339b6.png)
![dark theme 2](https://user-images.githubusercontent.com/2388823/75830568-0333df80-5d66-11ea-9e0d-bd0e9bb7c2cd.png)
![dark theme 3](https://user-images.githubusercontent.com/2388823/75831043-50fd1780-5d67-11ea-8dfe-70c6c87d23e5.png)
![dark theme 4](https://user-images.githubusercontent.com/2388823/75830572-04650c80-5d66-11ea-91fd-6bb505028983.png)

## Other Additional Information:
Note that the Speedreader mode is toggled on/off per browser profile. If the user switches to a different profile the Speedreader mode will be default OFF and the introductory message will show again if the user toggles it on.

related issue: https://github.com/brave/brave-browser/issues/679

## Assets
Abstract link: https://share.goabstract.com/4f3ac798-0307-429e-bc42-c356e2f5a82d?
[speedreader icon.zip](https://github.com/brave/brave-browser/files/4284297/speedreader.icon.zip)
[intro message graphic.zip](https://github.com/brave/brave-browser/files/4290319/intro.message.graphic.zip)

**Comment by karenkliu** [comment]
@AndriusA  Designs added!

**Comment by petemill** [comment]
Should the speedreader ON page use a simple dark theme in dark mode? @karenkliu

**Comment by karenkliu** [comment]
@petemill Good Q! You're right, pages that are speed-readable in dark theme should have that styling carry over to the page content. I've updated the designs.

**Comment by iefremov** [comment]
For QA: The promo bubble was not implemented in this issue (there is a separate ticket https://github.com/brave/brave-browser/issues/9262).

To enable speedreader pass `--enable-speedreader`. To whitelist certain sites use e.g. `speedreader-whitelist="https://bbc.com/*;"`

**Comment by LaurenWags** [comment]
Using 

```
Brave | 1.9.70 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Confirmed if no `--enable-speedreader` flag is used, there is no speedreader icon:
<img width="1519" alt="Screen Shot 2020-05-18 at 11 20 19 AM" src="https://user-images.githubusercontent.com/28145373/82230654-087ee000-98fa-11ea-8393-8865c9bab911.png">

Confirmed if using `--enable-speedreader` flag, speedreader icon is shown:
<img width="1521" alt="Screen Shot 2020-05-18 at 11 19 14 AM" src="https://user-images.githubusercontent.com/28145373/82230648-06b51c80-98fa-11ea-9ea4-6e985079a86d.png">

Confirmed when icon is shown, I can interact with it (click on it).
