### ISSUE TITLE
[Android] Delete Download History

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#8417]
Parity with current version https://github.com/brave/browser-android-tabs/pull/1966

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.113 x64 stable build
- Verified clear download history option is shown on clear data settings page
- Logged #8737 for issue with conflicting downloading data
------
Verification passed on Samsung Tab A with Android 9.0 running 1.5.113 x64 stable build
- Verified clear download history option is shown on clear data settings page
- Verified clear download history from Advanced settings
