### ISSUE TITLE
Wayback machine feature should be disabled in Tor windows or use Tor

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#8419]
### Problem

As reported in https://bravesoftware.slack.com/archives/C85NV6NSG/p1582256790113900 (see thread), we found that clicking the "Checked for saved version" button on a 404 page in a Tor window will send a request to `https://brave-api.archive.org/...` that doesn't go through Tor. As such, this is a privacy problem.

## Expected behavior

1. open a Tor window
2. go to https://brave.com/dfkdfjd
3. either you should **not** see a notification bar that offers to check the Wayback machine or you should see this, and clicking on the button to check the Wayback machine does not issue a request that goes over plain TLS. (check for it in a request inspector like Wireshark)

## What about private windows?

I think this feature is probably ok to keep in private windows because it uses a network context that doesn't store state on disk (https://cs.chromium.org/chromium/src/chrome/browser/net/system_network_context_manager.h?q=systemnetwork&sq=package:chromium&g=0&l=44-45) and we disallow cookies (https://github.com/brave/brave-core/pull/3561/files#diff-306f17e629f5adfd7444084d21b89193R38) for it.

However if the fix is easier to do with it disabled entirely in private windows (Tor windows included), I am pro doing that.

## underlying cause

The system network context (https://github.com/brave/brave-core/pull/3561/files#diff-6d51337a3d8e25d0c3fbb40ef046dce9R58) doesn't use the Tor window proxy setting.

**Comment by GeetaSarvadnya** [comment]
Verification passed on 

Brave | 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Issue Reproducible in 1.4.95 wherein `https://brave-api.archive.org/` is being listed in Fiddler network monitoring tool request/response
- Verified the test plan from https://github.com/brave/brave-core/pull/4763
- Verified that `https://brave-api.archive.org/` isn't being displayed in fiddler
![image](https://user-images.githubusercontent.com/38657976/75870248-bec14600-5e30-11ea-9784-93cf1931c980.png)
