### ISSUE TITLE
Crash ID isn't uploaded immediately even with setting set to send 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#842]
## Description 

Crash ID isn't uploaded immediately even with setting set to send 

## Steps to Reproduce

   1. Launch a new profile on Windows
   2. Visit `chrome://crash` in a new tab, ensure webview crashes
   3. Open `chrome://crashes` in a new tab, crash id is auto uploaded
   4. Visit https://neowin.net in a new tab, browser crashes (existing issue)
   5. Open `chrome://crasehs`, shows 6 crash reports none of them are auto uploaded
   6. Click Send now on crash id, doesn't send, restart the browser, crash id is uploaded

## Actual result:

![crashid](https://user-images.githubusercontent.com/17010094/44620390-5ec40980-a861-11e8-9038-3dde84f6eb14.gif)

## Expected result:
Should upload crash id immediately when the crash report is generated and setting is set to send crash reports

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Brave | 0.54.1 Chromium: 69.0.3497.42 (Official Build) dev (64-bit) 
-- | --
Revision | 9c4613c66dfeb2b76ef6dd4b15884c15db3b4969-refs/branch-heads/3497@{#655}
OS | Windows
JavaScript | V8 6.9.427.14
Flash | 30.0.0.154 C:\Windows\system32\Macromed\Flash\pepflashplayer64_30_0_0_154.dll

### Reproducible on current release:

No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @bridiver 
@bbondy please move it to release milestone if required and ad as blocking

**Comment by GeetaSarvadnya** [comment]
The crash ID isn't uploaded. By default send crash report is enabled in Beta even though crash ID isn't uploaded, even browser restart doesn't help


Brave | 0.69.107 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1803 (Build 17134.523)

Crash Id isn't uploaded in Release channel even after enabling send crash reports checkbox in privacy settings. 


Brave | 0.68.129 Chromium: 76.0.3809.100 (Official Build) (64-bit)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 10 OS Version 1803 (Build 17134.523)

![Crash report ID isn't uploaded](https://user-images.githubusercontent.com/38657976/63150694-247cea80-c025-11e9-8065-fab9e98e877a.gif)

**Comment by bridiver** [comment]
@GeetaSarvadnya did you restart the browser? There is throttling on the crash upload and sometimes it doesn't show up until you restart

**Comment by GeetaSarvadnya** [comment]
@bridiver I have restarted the browser also Automatic crash switch was turned on settings page

**Comment by GeetaSarvadnya** [comment]
https://github.com/brave/brave-browser/issues/10202 - logged a new issue for https://github.com/brave/brave-browser/issues/842#issuecomment-530466812

**Comment by bsclifton** [comment]
Closing as this is expected behavior
