### ISSUE TITLE
404 / Wayback Machine integration - should disable on localhost

### ISSUE THREAD

**Issue by alexwykoff** [brave/brave-browser#8420]
## Description 
As recommended by a user https://twitter.com/_rbonomo/status/1232805103175778304, when developing on localhost, the 404 / Wayback integration is not needed and may even interfere with development efforts. 

## Steps to Reproduce
   1.  Spin up a local www host
   2. Visit a local link which will 404

## Actual result:
Wayback integration is shown

## Expected result:
Local server result should be shown

## Brave version (brave://version info)
1.4.95 (latest production)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

**Comment by fmarier** [comment]
In addition to `localhost` (and `127.0.0.1`, `[::1]`), we might want to exclude `*.local`.

**Comment by StefanLobbenmeier** [comment]
The whole 127 subnet is localhost - so please also include them - i know this regex is not in the right language but this is the one I use in node.js
```typescript
    // 127.0.0.0/8 are considered localhost for IPv4.
    window.location.hostname.match(
      /^127(?:\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$/
    )
```

**Comment by StefanLobbenmeier** [comment]
Now that I think about it it also might not be enough considering you can write IPs also in octal, for example
http://127.0045.1.2:8080/index.html

But Brave currently translates it into decimal:

http://127.37.1.2:8080/index.html

So this should be fine. Please test it anyway.

**Comment by simonhong** [comment]
@StefanLobbenmeier `net::IsLocalhost()` works nicely :)
and you can see test cases https://github.com/brave/brave-core/pull/4808/files#diff-9c0cd69216d907227d0d91496b9f135aR10

**Comment by bsclifton** [comment]
Marked as `QA/No` since this is covered with automated tests 👍 
```
npm run test brave_unit_tests -- --filter=BraveWaybackMachineUtilsTest*
```
