### ISSUE TITLE
Re-enable WebXR by default

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#8424]
## Description 
See https://github.com/brave/brave-core/commit/f460ff7d782545019aa4a49eb0efa34067fa9325 for context where WebXR was disabled during the upgrade from Chromium 78 to Chromium 79

## Test plan / Steps to Reproduce
   1. Visit https://immersive-web.github.io/webxr-samples/
   1. You should see `Yes! Your browser supports WebXR and can run Virtual Reality and Augment Reality experiences if you have the appropriate hardware.`
   1. Visit https://immersive-web.github.io/webxr-samples/360-photos.html?usePolyfill=0

## Actual result:
Status reported is `Sorry, your browser does not support WebXR.` and the 360 photos page doesn't work (white background)

## Expected result:
You should see the  `Yes! Your browser supports WebXR` message and the 360 photos page should work (3D image that you can pan around inside of)

## Reproduces how often: 
100%

## Brave version (brave://version info)
1.7.13 Chromium: 80.0.3987.122 (Official Build) nightly (64-bit)

## Version/Channel Information:
All channels

- Can you reproduce this issue with the current release? y
- Can you reproduce this issue with the beta channel? y 
- Can you reproduce this issue with the dev channel? y
- Can you reproduce this issue with the nightly channel? y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N
- Does the issue resolve itself when disabling Brave Rewards? N
- Is the issue reproducible on the latest version of Chrome?  N

**Comment by bsclifton** [comment]
Privacy / security review: https://github.com/brave/security/issues/60

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.3 x64 Catalina` using the following build:

```
Brave | 1.7.71 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.15.3 (Build 19D76)
```

* Verified the STR/Test Plan outlined via https://github.com/brave/brave-browser/issues/8424#issue-571844211
* ensured that you can pan around https://immersive-web.github.io/webxr-samples/360-photos.html?usePolyfill=0

<img width="909" alt="Screen Shot 2020-03-24 at 2 21 26 PM" src="https://user-images.githubusercontent.com/2602313/77462880-1a04a980-6ddb-11ea-92f3-8bb7be0c6572.png">

<img width="911" alt="Screen Shot 2020-03-24 at 2 21 34 PM" src="https://user-images.githubusercontent.com/2602313/77462889-1d983080-6ddb-11ea-9bf3-3d13ddb71839.png">
