### ISSUE TITLE
Implement new persona creation

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#8428]
Right now when we call api server creates paymentId and wallets etc. New api should just crate payment Id and that is it. We will also remove anonize dependency with this move. As part of this effort we will also implement new settings api (https://github.com/brave/brave-browser/issues/9132).

**Comment by LaurenWags** [comment]
Marked as `QA/Blocked` pending additional test plan information (requested from @NejcZdovc )

**Comment by LaurenWags** [comment]
Confirmed additional areas outside of test plan are not required for specifically testing this issue, thanks @NejcZdovc !

**Comment by LaurenWags** [comment]
Verification in progress

```
Brave | 1.13.73 Chromium: 84.0.4147.125 (Official Build) dev (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Confirmed plan 1 from https://github.com/brave/brave-core/pull/6000 when enabling Rewards via panel, NTP widget, and brave://rewards page. Confirmed that in `Preference` file that `brave.rewards.wallet` has `payment_id` and `seed` populated.

Confirmed plan 2 from https://github.com/brave/brave-core/pull/6000. Confirmed able to restore a wallet by manually copy/paste of words and import of backup file. Both were successful. Encountered https://github.com/brave/brave-browser/issues/11235 while testing.
<img width="401" alt="Screen Shot 2020-08-17 at 3 46 54 PM" src="https://user-images.githubusercontent.com/28145373/90437944-39111a00-e0a1-11ea-9af9-7d6533b86400.png">

Confirmed plan 3 from https://github.com/brave/brave-core/pull/6000. Confirmed migration message displayed. Link in message directs user to https://brave.com/faq/#convert-old-keys.
<img width="704" alt="Screen Shot 2020-08-17 at 3 50 47 PM" src="https://user-images.githubusercontent.com/28145373/90438396-e08e4c80-e0a1-11ea-9037-812d341dc2e1.png">

TBD:
test plan 4 from https://github.com/brave/brave-core/pull/6000.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.84 x64 build
- Verified wallet is created automatically when rewards is enabled
- Verified importing wallet key restores the wallet correctly 
- Verified entering random 16 words in restore wallet doesn't restore any wallet
-----------------
Verification passed on Samsung Tab A with Android 10 running 1.13.84 x64 build
- Verified wallet is created automatically when rewards is enabled
- Verified importing wallet key restores the wallet correctly 
- Verified entering random 16 words in restore wallet doesn't restore any wallet
