### ISSUE TITLE
Allow users to disable autocomplete

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#843]
Carried over from https://github.com/brave/browser-laptop/issues/3631

Some users would like a discrete setting to disable autocomplete for the omnibox. I don't believe this is offered by Chromium/Chrome (you can only disable predictive services)

**Comment by cup** [comment]
http://github.com/brave/brave-browser/issues/843
http://github.com/brave/browser-laptop/issues/3631
http://github.com/brave/browser-laptop/issues/7628

**Comment by alego500** [comment]
Leaving comment to show interest in this feature as well.

**Comment by Brave-Matt** [comment]
+1 from Community and definitely a +1 from myself:
https://community.brave.com/t/how-do-i-turn-off-url-auto-complete/62316

**Comment by edanyal** [comment]
Please!

**Comment by Brave-Matt** [comment]
+1 from Reddit, multiple users
https://www.reddit.com/r/brave_browser/comments/b4jn8t/autocomplete_delete/epo0wd1?utm_source=share&utm_medium=web2x

**Comment by crocket** [comment]
auto-completion is a huge distraction. So, I turned it off in vivaldi web browser.

**Comment by UsedToCould** [comment]
so are you guys gonna do something about this? you've been ignoring us for over a year.

**Comment by GH-Rake** [comment]
Auto completion is an anti privacy feature.  I livestream on Youtube and Twitch and I do not need my entire internet history and every bookmark with sensitive information in the URLs being displayed to my viewers each time I do a search.  If Brave is to be "the" privacy browser then I believe this feature is important.  I guess I have to reinstall Firefox

**Comment by mjlp224** [comment]
Please make disabling autocomplete an option. It would be a good feature since many people save login credentials whose pages could be easily navigated to through autocomplete & then have their private information accessed.

**Comment by simonhong** [comment]
@mjlp224  Working on this for desktop :)

**Comment by mjlp224** [comment]
Awesome thanks Simon good to see someone on it I've been following the topic for a while. How about mobile?

**Comment by simonhong** [comment]
@rebron maybe disabling autocomplete on Mobile is another issue this?

**Comment by rebron** [comment]
@anthonypkeane for thoughts on disabling autocomplete suggestions via a mobile setting? We're doing this for desktop.

Also @simonhong related issue https://github.com/brave/brave-browser/issues/5934 likely I can just dupe that issue to this one.

**Comment by rebron** [comment]
Example of this setting in Firefox, we'll want to just disable autocomplete and not go this granularly with bookmarks, history, open tabs.
<img width="703" alt="Screen Shot 2019-11-20 at 12 58 42 PM" src="https://user-images.githubusercontent.com/5951041/69277676-89e8f600-0b95-11ea-9085-79f073c910c5.png">

**Comment by bsclifton** [comment]
Updated labels and added milestone/test plan after https://github.com/brave/brave-core/pull/4033 was merged 😄

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.81 Chromium: 79.0.3945.88 (Official Build) beta (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/4033. 
Verified that autocomplete can be re-enabled.

![image](https://user-images.githubusercontent.com/34715963/71765053-f58de500-2eef-11ea-94c6-ad390f7e4c7f.png)

![image](https://user-images.githubusercontent.com/34715963/71765042-dee78e00-2eef-11ea-818f-fa419a8abb0e.png)

**Comment by Amariithynar** [comment]
Is there a way to disable it autocompleting in the address bar directly and instead just offer suggestions? I WANT the suggestions, but I do NOT want it to shove it into my address bar!
