### ISSUE TITLE
Multiple scroll bars on crypto wallet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8438]
## Description 

Multiple scroll bars on crypto wallet

## Steps to Reproduce

   1. Install `0.1.47`
   2. Have default browser window size
   3. Do multiple transactions, shows mulitple scroll bars 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/75455462-75d84000-599f-11ea-9136-7c269f63ca23.png)

## Expected result:
Just one scrollbar

## Reproduces how often: 

Easy

## Brave version (brave://version info)

`0.1.47`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes 
- Can you reproduce this issue with the beta channel? YEs
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? na

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.3 x64` using https://github.com/brave/ethereum-remote-client/releases/tag/0.1.50.

```
Brave | 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | macOS Version 10.15.3 (Build 19D76)
```

* Went through the STR outlined via https://github.com/brave/brave-browser/issues/8438#issue-572135784 and ensured that only a single scroll bar was visible.

<img width="1209" alt="Screen Shot 2020-03-04 at 1 15 17 AM" src="https://user-images.githubusercontent.com/2602313/75852649-78310480-5dba-11ea-875f-5bc59dbc072a.png">

Verification **PASSED** on `Win 10 x64` using https://github.com/brave/ethereum-remote-client/releases/tag/0.1.50.

```
Brave | 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit)
--- | ---
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Windows 10 OS Version 1909 (Build 18363.657)
```

* Went through the STR outlined via https://github.com/brave/brave-browser/issues/8438#issue-572135784 and ensured that only a single scroll bar was visible.

![CWScrollBars](https://user-images.githubusercontent.com/2602313/75855364-18d5f300-5dc0-11ea-9267-3d26b1212d51.jpg)
