### ISSUE TITLE
Shields icon is pixelated

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#844]
![image](https://user-images.githubusercontent.com/741836/44631960-60a4d000-a928-11e8-8aa2-bad408068ba1.png)

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
