### ISSUE TITLE
Refactor Brave Ads in preparation for Publisher Ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#8445]

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.78 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4773
* Verified for clean and upgrade (from 1.5.x) profiles
* Confirmed ads are displayed and data is displayed in Ads panel
<img width="644" alt="Screen Shot 2020-03-30 at 3 45 38 PM" src="https://user-images.githubusercontent.com/28145373/77956780-7a469000-72a0-11ea-85fc-33f9b7e41f33.png">
<img width="946" alt="Screen Shot 2020-03-30 at 3 45 45 PM" src="https://user-images.githubusercontent.com/28145373/77956785-7c105380-72a0-11ea-8ab6-f08fecd46239.png">
<img width="324" alt="Screen Shot 2020-03-30 at 3 45 20 PM" src="https://user-images.githubusercontent.com/28145373/77956791-7dda1700-72a0-11ea-9d71-cb20c5a06eba.png">
