### ISSUE TITLE
Assertion thrown in debug builds when generating Brave Ads console log report

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#8446]
## Description 

Assertion thrown in debug builds when generating Brave Ads console log report

## Steps to Reproduce

   1. View an ad (in debug build)

## Actual result:

Assertion is thrown by RAPIDJSON_ASSERT due to multiple root nodes

## Expected result:
Assertion should not be thrown

## Reproduces how often: 

Easily reproduced (only occurs on first run)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by LaurenWags** [comment]
@tmancey QA doesn't generally test debug builds, we get release builds via github. Is there something that can be checked on a release build? if not, should this one be marked `QA/No`?

cc @kjozwiak

**Comment by kjozwiak** [comment]
We should label this as `QA/No` as we don't generally check crashes/assertions on debug builds that are built from source as per https://github.com/brave/brave-browser/issues/8446#issuecomment-606225759. @tmancey if there's nothing that needs to be done here, can you please label this as `QA/No`? Or just let us know and someone from QA will change the label as needed.

**Comment by tmancey** [comment]
@LaurenWags @kjozwiak We just need to make sure the fix works as:

Confirm "restart" appears within an AdsService Event Log: in the console log when viewing Brave Ad notifications, i.e.
```
AdsService Event Log: {"data":{"type":"restart","timestamp":"2020-03-31T10:08:26Z"},"data":{"type":"notify","timestamp":"2020-03-31T10:08:26Z","eventType":"clicked","classifications":["personal finance"],"adCatalog":"37f7ba07-355d-4d0f-8cdb-b9241550c0c8","targetUrl":"https://travala.com/"}}
```

Note you must also pass `--v=1` to see `AdsService Event Log`'s

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.79 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified https://github.com/brave/brave-browser/issues/8446#issuecomment-606498293 on release build. As noted in https://github.com/brave/brave-browser/issues/8446#issuecomment-606225759 and https://github.com/brave/brave-browser/issues/8446#issuecomment-606246963 QA doesn't check debug/from source builds, so this was not verified there. 

```
[11515:775:0331/094928.107220:INFO:ads_service_impl.cc(2136)] AdsService Event Log: {"data":{"type":"restart","timestamp":"2020-03-31T09:49:28Z"},"data":{"type":"notify","timestamp":"2020-03-31T09:49:28Z","eventType":"generated","classifications":["technology & computing"],"adCatalog":"61ad680e-d3d4-4e8f-b8af-09046ea0bda2","targetUrl":"https://creators.brave.com/?src=ba6"}}
```

```
[11515:775:0331/094932.456062:INFO:ads_service_impl.cc(2136)] AdsService Event Log: {"data":{"type":"restart","timestamp":"2020-03-31T09:49:32Z"},"data":{"type":"notify","timestamp":"2020-03-31T09:49:32Z","eventType":"clicked","classifications":["technology & computing"],"adCatalog":"61ad680e-d3d4-4e8f-b8af-09046ea0bda2","targetUrl":"https://creators.brave.com/?src=ba6"}}
```
