### ISSUE TITLE
update text on ads panel of brave://rewards

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8449]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/7500

`Brave ads` should be `Brave Ads` per https://github.com/brave/brave-browser/issues/7500#issuecomment-592049338

## Steps to Reproduce

   1. Enable Rewards if not already enabled
   2. Look at text on Ads panel of brave://rewards

## Actual result:

<img width="654" alt="ads" src="https://user-images.githubusercontent.com/28145373/75487315-36e4c300-597c-11ea-9aa2-ae2ccaa7e0af.png">

## Expected result:
`Brave ads` should be `Brave Ads`

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.5.102 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a, change isn't in 1.4.x
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.3 x64 Catalina` using the following build:

```
Brave | 1.7.64 Chromium: 80.0.3987.132 (Official Build) beta (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | macOS Version 10.15.3 (Build 19D76)
```

<img width="656" alt="Screen Shot 2020-03-17 at 3 11 09 PM" src="https://user-images.githubusercontent.com/2602313/76892938-d7365500-6861-11ea-80c6-5f77f5fa2e76.png">
