### ISSUE TITLE
[bug] brave ad block Additional Filters not work

### ISSUE THREAD

**Issue by zfoxzero** [brave/brave-browser#8455]
## Description 
Filters rule not have   "rs-UUID.dat" file . Additional filters not work
my browser version:
Release v1.4.95
Nightly 1.7.26

**Comment by rebron** [comment]
cc: @ryanbr @pes10k Can you triage when you have a moment?

**Comment by pes10k** [comment]
This sounds like a whole 'nother level, maybe CRX packager? @bbondy ?

**Comment by zfoxzero** [comment]
> This sounds like a whole 'nother level, maybe CRX packager? @bbondy ?

CRX file not have rs-UUID.dat

for example |  https://brave-core-ext.s3.brave.com/release/llhecljkijgcaalnbfadljdpkpbehakp/extension_1_0_494.crx
-- | --

**Comment by zfoxzero** [comment]
> This sounds like a whole 'nother level, maybe CRX packager? @bbondy ?

T_T
why not have rs file ?
https://adblock-data.s3.amazonaws.com/4/rs-11F62B02-9D1F-4263-A7F8-77D2B55D4594.dat
https://brave-core-ext.s3.brave.com/release/llhecljkijgcaalnbfadljdpkpbehakp/extension_1_0_501.crx

**Comment by zfoxzero** [comment]
A month went by.............................................

**Comment by pes10k** [comment]
apologies, but im not able to follow the question.  Is the request 
1. for the ability to subscribe to new filter lists by URL,
2. to add filter lists to the custom box in brave://adblock

or some third issue?

**Comment by zfoxzero** [comment]
> apologies, but im not able to follow the question. Is the request
> 
> 1. for the ability to subscribe to new filter lists by URL,
> 2. to add filter lists to the custom box in brave://adblock
> 
> or some third issue?

`[11512:8944:0409/205242.880:ERROR:dat_file_util.cc(22)] GetDATFileData: the dat file is not found or corrupted G:\Other\brave-browser\src\out\Data\llpoppgpcimnmhgehpipdmamalmpfbjd\1.0.540\rs-CC98E4BA-9257-4386-A1BC-1BBF6980324F.dat
[11512:12832:0409/205242.881:ERROR:ad_block_base_service.cc(226)] Could not obtain ad block data
[11512:8944:0409/205242.960:ERROR:dat_file_util.cc(22)] GetDATFileData: the dat file is not found or corrupted G:\Other\brave-browser\src\out\Data\lgfeompbgommiobcenmodekodmdajcal\1.0.538\rs-92AA0D3B-34AC-4657-9A5C-DBAD339AF8E2.dat
[11512:12832:0409/205242.961:ERROR:ad_block_base_service.cc(226)] Could not obtain ad block data`
The selected filter list is not in effect.
Can't find the correct rules list file.

**Comment by pes10k** [comment]
thank you @zfoxzero, im looking into this further now.  Its odd bc we dont have other reports of problems with those lists.  Just so that I can recreate the issue you're seeing, are you on stable, beta or nightly?

**Comment by zfoxzero** [comment]
All versions, 1.7.90release, 1.8.70beta and 1.9.13Nightly. all downloaded files like extension_1_0_494.crx cannot be unpacked to find the rules file starting with rs.
But cffkpbalmllkdoenhmdmpbkajipdjfam\1.0.535\rs-ABPFilterParserData.dat this rules file is normal, I'm not sure if it's because of this file that the problem is hidden.

**Comment by zfoxzero** [comment]
> thank you @zfoxzero, im looking into this further now. Its odd bc we dont have other reports of problems with those lists. Just so that I can recreate the issue you're seeing, are you on stable, beta or nightly?

All versions, 1.7.90release, 1.8.70beta and 1.9.13Nightly. all downloaded files like extension_1_0_494.crx cannot be unpacked to find the rules file starting with rs.
But cffkpbalmllkdoenhmdmpbkajipdjfam\1.0.535\rs-ABPFilterParserData.dat this rules file is normal, I'm not sure if it's because of this file that the problem is hidden.

**Comment by pes10k** [comment]
Gotcha, thank you for this information.  Will get this sorted ASAP and report back here.  Thank you for letting us know about this @zfoxzero

**Comment by pes10k** [comment]
@zfoxzero okay, good news!  Things should be fixed now, and you should see a fix w/in the next 24 hours.  Would you mind checking again tomorrow and letting me know if things are working well for you then?

**Comment by zfoxzero** [comment]
> @zfoxzero okay, good news! Things should be fixed now, and you should see a fix w/in the next 24 hours. Would you mind checking again tomorrow and letting me know if things are working well for you then?

Very good, the other rules can load properly, nothing wrong with that.
other
Is the default rule rs-ABPFilterParserData.dat generated from a combination of these rules?
The ability to separate as optional items, as the default rules block many sites and adding whitelists is not very convenient.
```
"EasyList" "https://easylist.to/easylist/easylist.txt",
"EasyPrivacy" "https://easylist.to/easylist/easyprivacy.txt",
"uBlock Unbreak" "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt"
"Brave Unblock" "https://raw.githubusercontent.com/brave/adblock-lists/master/brave-unbreak.txt"
"NoCoin Filter List" "https://raw.githubusercontent.com/brave/adblock-lists/master/coin-miners.txt"
```

**Comment by pes10k** [comment]
Terrific!  I'm going to close this issue then.  Thanks for help us get it sorted out!

About `rs-ABPFilterParserData.dat`, it includes those files, but more.  The full set of default filters are defined in https://github.com/brave/adblock-rust/blob/master/src/filter_lists/default.rs

I appreciate the feature request, and as a long term feature we might make them individually configurable, but for the medium term I don't think we should, mostly because the more folks change the default filter list configuration, the more identifiable they are (since the set of enabled filter lists will differ slightly from other users).  The current set aims to be broad and useful for most users.  So, there is some privacy / configurability trade off.

But, that being said, we're definitely looking into more ways to have shields be more customizable for advanced users, so this could change too.  I've created [an issue for that here](https://github.com/brave/brave-browser/issues/9144), so if anything changes, that's the place to watch.

Thanks again for your help!

**Comment by zfoxzero** [comment]
> Terrific! I'm going to close this issue then. Thanks for help us get it sorted out!
> 
> About `rs-ABPFilterParserData.dat`, it includes those files, but more. The full set of default filters are defined in https://github.com/brave/adblock-rust/blob/master/src/filter_lists/default.rs
> 
> I appreciate the feature request, and as a long term feature we might make them individually configurable, but for the medium term I don't think we should, mostly because the more folks change the default filter list configuration, the more identifiable they are (since the set of enabled filter lists will differ slightly from other users). The current set aims to be broad and useful for most users. So, there is some privacy / configurability trade off.
> 
> But, that being said, we're definitely looking into more ways to have shields be more customizable for advanced users, so this could change too. I've created [an issue for that here](https://github.com/brave/brave-browser/issues/9144), so if anything changes, that's the place to watch.
> 
> Thanks again for your help!

OK ，Thanks for the answer. 😀

**Comment by bbondy** [comment]
I also verified with the Japanese adblock list and it now includes the rs- file.
