### ISSUE TITLE
[Android] Stats and some settings are lost during upgrade from tabs to core

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8456]
## Description 
Some global settings and stats are lost when upgrading from tabs to core

## Steps to reproduce 

   1. Install GPS build 1.5.7
   2. Visit a bunch of sites to add stats on NTP
   3. Enable background video play from settings
   4. Enable Fingerprint protection from privacy
   5. Disable home button in settings
   6. Set DDG Lite for private tab SE
   7. Upgrade to 1.5.100
   8. Stats is reset to 0 
   9. Background media play is reset to disabled
  10. Home button setting is missing to enable/disable
  11. Fingerprint protection setting is retained 
  12. Private tab SE is reset to Google from DDG Lite

## Actual result 
![tabs-core](https://user-images.githubusercontent.com/17010094/75520635-ffcdea80-5a2b-11ea-81d8-55a4d670f7c7.gif)

## Expected result
Upgrade should retain stats and settings changed in older version

## Issue happens on 
   - Current Play Store version? No
   - Beta build? No

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): OnePlus 6T 
   - Android version: Android 10
   
## Brave version
GPS 1.5.7 -> 1.5.100 stable core build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by GeetaSarvadnya** [comment]
Reproduced in Samsung Galaxy J3 version 5.1.1

**Comment by SergeyZhukovsky** [comment]
Home button worked as expected and on video as well.
There were 2 more issues:
`Settings->Site Settings->Dektop view`
`Settings->Site Settings->Video playback in Brave`
were not remained.

**Comment by srirambv** [comment]
This is still an issue with respect to stats. Recording of issue reproducing https://bravesoftware.slack.com/archives/CM17J5QMU/p1583738867104900?thread_ts=1583721672.104100&cid=CM17J5QMU
