### ISSUE TITLE
[Android] Enable/Disable home button setting is missing 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8457]
## Description 
Enable/Disable home button setting is missing 

## Steps to reproduce 

   1. Install Brave-Beta from GPS
   2. Open settings
   3. Home button enable/disable option is missing as its set to enabled by default and only has the URL option. No way to turn it off

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/75521027-db264280-5a2c-11ea-86cb-a750546fa04d.png)

## Expected result
![image](https://user-images.githubusercontent.com/17010094/75521021-d6fa2500-5a2c-11ea-9571-4e1b33b77caa.png)

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10.
   
## Brave version
1.5.100 beta

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by yrliou** [comment]
This is fixed by https://github.com/brave/brave-core/pull/4746, please try again in a nightly or a newer beta, thanks.
@srirambv I’ll close it for now, but feel free to reopen it if the issue persists.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.111 x64 stable build
- Verified on clean install enabled/disable home button is shown
- Verified on upgrade from the previous version, enable/disable home button is shown
--------
Verification passed on Samsung Tab A with Android 9.0 running 1.5.111 x64 stable build
- Verified on clean install enabled/disable home button is shown
- Verified on upgrade from the previous version, enable/disable home button is shown
--------
