### ISSUE TITLE
[Android] Private tab SE is lost during update

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8458]
## Description 
Private tab SE is lost during update

## Steps to reproduce 

   1. Set DDG as SE in 1.5.7 GPS build
   2. Upgrade to 1.5.100 stable build
   3. Private tab SE is reset to Google

## Actual result 
Private tab SE is lost during update

## Expected result
Should retain SE setting during upgrades

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): OnePlus 6T
   - Android version: 10
   
## Brave version
1.5.7 ->1.5.100

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by SergeyZhukovsky** [comment]
That was fixed in the context of that issue https://github.com/brave/brave-browser/issues/8456

**Comment by srirambv** [comment]
Superseded by #8768. Removing QA/Yes
