### ISSUE TITLE
[Android] Bookmark button gets selected when tapped next to menu button

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8460]
## Description 
Bookmark button gets selected when tapped next to menu button

## Steps to reproduce 

   1. Install 1.5.100 Beta from GPS
   2. Tap on the extreme right side of the menu button
   3. Bookmark button gets highlighted 

## Actual result 
![bookmarkstap](https://user-images.githubusercontent.com/17010094/75537307-c8b40500-5a3c-11ea-934a-2cec7b75ebdc.gif)

## Expected result
No tap on bookmarks button

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NO
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): OnePlus 6T
   - Android version: 10
   
## Brave version
1.5.100 Beta

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Not a big deal but something that needs to be fixed 
cc: @bbondy @SergeyZhukovsky @anthonypkeane marked it as android-related for tirage

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/bottom-toolbar-issue/122196/5

**Comment by srirambv** [comment]
Uplift approved hence moving the issue to 1.9.x Release. Need to link the issue to Android 1.9.x release

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running BraveModernarm.apk.1.9.74
 - Reproduced the issue in 1.5.100 Android beta version
 - The issue is fixed and working fine in 1.9.74

**Comment by btlechowski** [comment]
Marked as `android-phone-specific` as Tablets don't have bottom toolbar.
