### ISSUE TITLE
Verified Twitch pubs aren't displayed as verified in BR panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8462]
## Description 

Verified Twitch pubs name isn't displayed in BR panel

## Steps to Reproduce

   1. Clean profile 1.7.24
   2. Enable rewards
   3. Open a verified twitch pub https://www.twitch.tv/jennrhim
   4. Open the BR panel
   5. Verified pub name is not displayed in the panel also  verified checkmark isn't shown in panel and URL bar

## Actual result:

Verified pub name is not displayed in the panel also  verified checkmark isn't shown in panel and URL bar
![image](https://user-images.githubusercontent.com/38657976/75552600-a92cd480-5a5c-11ea-9012-932c63f4864d.png)

## Expected result:
Verified pub name is should be displayed in the panel also verified checkmark should be shown in panel and URL bar

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.7.24 Chromium: 80.0.3987.122 (Official Build) nightly (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc

**Comment by LaurenWags** [comment]
@GeetaSarvadnya dupe of https://github.com/brave/brave-browser/issues/6851 ?

**Comment by GeetaSarvadnya** [comment]
@LaurenWags Yup, it's dup closing this issue. Thanks for identifying.
