### ISSUE TITLE
Follow up of PR #4252- Attention % value resets to zero in BR panel 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8463]
## Description 

Follow up of PR https://github.com/brave/brave-core/pull/4252- Attention % value resets to zero in BR panel 

## Steps to Reproduce

   1. Clean profile 1.7.23 PR build - Launch using `brave.exe --rewards=staging=true`
   2. Enable rewards
   3. Open a site cnn.com and spend 10 sec on the site
   4. Open BR panel for CNN.com and ensure % attention value displayed in the panel
   5. Navigate to AC table and ensure attention % value displayed in AC table
   6. Open BR panel for Cnn.com again
   7. Attention % value for Cnn.com resets to zero

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/75554413-4ccbb400-5a60-11ea-8b6b-da52ab050db1.png)

![image](https://user-images.githubusercontent.com/38657976/75554477-640aa180-5a60-11ea-857b-c811ef5658b4.png)
![image](https://user-images.githubusercontent.com/38657976/75554511-77b60800-5a60-11ea-9d02-2bc77f70dc24.png)

## Expected result:
Attention % value should be displayed in BR panel 

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.7.23 Chromium: 80.0.3987.122 (Official Build) nightly (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc

**Comment by LaurenWags** [comment]
Reproduced with YT channel as well on macOS

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.8.77 Chromium: 81.0.4044.92 (Official Build) dev (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
- Verified the test plan from https://github.com/brave/brave-core/pull/5016
![image](https://user-images.githubusercontent.com/38657976/79542351-1c3fe800-80a9-11ea-97ab-0d7d9663f281.png)
![image](https://user-images.githubusercontent.com/38657976/79542404-32e63f00-80a9-11ea-93ef-46b0b8e7d311.png)
