### ISSUE TITLE
monthly contributions not reflected on Rewards NTP widget

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8467]
## Description 

After monthly contributions (recurring tips) have been contributed, they are not reflected on the Rewards NTP widget.

## Steps to Reproduce

   1. Launch clean profile from staging with short reconcile interval
   2. Enable Rewards, add BAT to wallet (I tried with both a restored wallet and using a UGP grant)
   3. Do a one time tip, see it reflected in Rewards NTP widget
   4. Set up a recurring tip.
   5. Add sites to AC table, adjust monthly budget if necessary depending on wallet balance.
   6. Wait for reconcile.
   7. Once reconcile is complete, look at Rewards NTP widget.

## Actual result:
one time tip and AC are reflected in the widget, but recurring tips are not (bottom number on the widget should be 11, not 10):
<img width="529" alt="Screen Shot 2020-02-28 at 12 58 12 PM" src="https://user-images.githubusercontent.com/28145373/75573717-69012e00-5a2b-11ea-8ffa-2c4f77e389e4.png">

also occurs if you fund via UGP grant instead of restored wallet:
<img width="578" alt="Screen Shot 2020-02-28 at 1 09 36 PM" src="https://user-images.githubusercontent.com/28145373/75573814-9ea61700-5a2b-11ea-83a8-1123515e5326.png">

## Expected result:
one time, recurring, and AC should all be reflected in the widget

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.7.26 Chromium: 80.0.3987.122 (Official Build) nightly (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? unsure
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Good catch @LaurenWags!

Reproduced in Windows `1.7.26 -Nightly`

![image](https://user-images.githubusercontent.com/38657976/75645454-f206a800-5c6b-11ea-93dc-2a6d7f633b0b.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.71 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4801
<img width="395" alt="Screen Shot 2020-03-24 at 1 46 12 PM" src="https://user-images.githubusercontent.com/28145373/77461241-a497d980-6dd8-11ea-851a-dab238411f33.png">
<img width="390" alt="Screen Shot 2020-03-24 at 1 46 00 PM" src="https://user-images.githubusercontent.com/28145373/77461248-a5c90680-6dd8-11ea-86db-77d61d6b8788.png">

* Encountered and logged https://github.com/brave/brave-browser/issues/8841 while testing
