### ISSUE TITLE
[Android] If sent from the background, the ads notifications should not make sound and pop up on the screen.

### ISSUE THREAD

**Issue by gdregalo** [brave/brave-browser#8469]
## Description 
Duplicate of the issue for browser-android-tabs: https://github.com/brave/browser-android-tabs/issues/2419.
Please read implementation details in:
https://github.com/brave/browser-android-tabs/pull/2480.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by gdregalo** [comment]
Pr to master: https://github.com/brave/brave-core/pull/4591
PR to: 1.5: https://github.com/brave/brave-core/pull/4779
PR to 1.6: https://github.com/brave/brave-core/pull/4778.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.110 x64 build
- Verified notification showed up as `Other Notification` and went directly into notification tray when app was backgrounded
- Verified there was no notification sound when the silent notification arrived
![image](https://user-images.githubusercontent.com/17010094/76400624-985a5800-63a6-11ea-8bf1-3dbc44cde4af.png)
