### ISSUE TITLE
[Question/Feature Request] Service worker is blocked too aggressively

### ISSUE THREAD

**Issue by bigopon** [brave/brave-browser#8472]
## Description 
The main issue thread is here https://github.com/dumberjs/dumber-gist/issues/19. A TLDR version of that would be Brave is blocking `[...].example.com` even `example.com` is added to allowed list in cookies settings.

## Steps to Reproduce
   1. Add `[*.]gist.dumber.app` to allowed cookies
   2. Visit https://buttonwoodcx.github.io/doc-bcx-validation/examples/foreach-and-nested
   3. The example demos doesn't work in the iframes

## Other Additional Information:

- Turning off Brave shield doesn't give any effect
- I don't have Brave rewards on
- Chrome/Firefox both work fine after the permission config

**Comment by 3cp** [comment]
I tried to update dumber-gist to at least propagate the inner iframe error to the parent window (which is also in an iframe).

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://860fbf29a89bab9a053aa47be4982a7a.gist.dumber.local') does not match the recipient window's origin ('https://gist.dumber.local').
```

Does Brave have some implicit sandbox setting on iframe?

**Comment by 3cp** [comment]
I can reproduce the same issue in Chrome by turning off

<img width="689" alt="Screen Shot 2020-03-03 at 10 06 46 am" src="https://user-images.githubusercontent.com/1188806/75726528-b389ef80-5d36-11ea-9494-279756ca2868.png">

The issue is, brave has the it turned on by default (which is what we want), but still got error in iframe.

**Comment by rebron** [comment]
@bigopon @3cp Can you go into brave://version and let us know where you're seeing this. With shields down, the example site provided seems to be working.

e.g.

Brave | 1.8.78 Chromium: 81.0.4044.92 (Official Build) beta (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | macOS Version 10.15.5 (Build 19F62f)

**Comment by 3cp** [comment]
It worked for me with Shied off.

**Comment by bigopon** [comment]
It now works for me, probably you updated it in some recent versions?
Brave:
| Brave | 1.8.77 Chromium: 81.0.4044.92 (Official Build) dev (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | Windows 10 OS Version 1903 (Build 18362.778)

I have shield on with the following:
![image](https://user-images.githubusercontent.com/9994529/79629866-24bf1e00-8190-11ea-9294-7d5e828b0c99.png)

Now I' now sure which to delete

**Comment by 3cp** [comment]
@bigopon I guess this can be closed.

**Comment by bigopon** [comment]
@rebron thanks for checking. I guess this can be closed. Is there anything to be aware of in case of a future bug related to this?
