### ISSUE TITLE
Allow cosmetic filtering to also be applied to 1p items

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#8475]
## Description
by default we have cosmetic filtering that attempts to differentiate 1p and 3p ads, and only block the latter.

Some users would like to do the simpler, "apply all cosmetic filters, always" approach.  Basically, just do what uBO does.

This issue would be to modify the current cosmetic filtering to have an option to automatically inject all cosmetic filters, and not do party checks.  '

## Design

**Shields panel**
![cosmetic filtering](https://user-images.githubusercontent.com/2388823/82584303-2a21d680-9b49-11ea-9278-7c8867422702.png)

**brave://settings**
![cosmetic filtering shields settings](https://user-images.githubusercontent.com/2388823/82584327-33ab3e80-9b49-11ea-8d76-cd552e6e2f13.png)

Figma for CSS, layout, sizing: https://www.figma.com/file/3A6F6VrxVahiZFxLr7j7FO/Desktop-Brave-Shields?node-id=16%3A14877

**Comment by pes10k** [comment]
The implementation could be pretty simple:

1. Add a content / per-site shields setting for cosmetic filtering (off, only 3p {default}, all)
2. add a code path in the cosmetic filtering content script that, when the above is in the "all" mode, injects all matching rules (not just 3p ones)

**Comment by BrendanEich** [comment]
I like even more minimal yet viable MVPs. Per https://twitter.com/myphs/status/1233110060903075844?s=20 what many want is the "uBO me globaly please" setting. That would be a single setting, could even start with brave:flags or better internal URL and no official settings UX. But what would it flip internally?

**Comment by karenkliu** [comment]
Designs for brave://settings added and dropdown option typo fixed.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.11.89 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/5481
Verified default setting
![image](https://user-images.githubusercontent.com/34715963/86763659-c5aece00-c047-11ea-8194-2a832352ce80.png)
Verified default setting in `brave://settings/shields`
![image](https://user-images.githubusercontent.com/34715963/86763827-e6772380-c047-11ea-922f-ee7064ec6d92.png)

Verified aggressive setting in Brave Shields Panel works:
![image](https://user-images.githubusercontent.com/34715963/86764236-30600980-c048-11ea-84d3-741904acb3c3.png)
Verified aggressive setting in `brave://settings/shields` works:
![image](https://user-images.githubusercontent.com/34715963/86765111-0529ea00-c049-11ea-937d-a634b7da7f93.png)


Verified allowing all trackers and ads in Brave Shields works as expected
Verified allowing all trackers and ads in `brave://settings/shields` works as expected
Verified page is reloaded when changing the setting in Brave Shields.
