### ISSUE TITLE
Brave components not installing

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#848]
0.55.1 c70 (latest master)

## Test steps
1. Fresh profile (delete user data directory)
2. Start browser
3. Visit a site with ads
4. Observe shields counts are 0.

This is because none of the components have installed since the component updater will only verify components in the CRX3 (with publisher verification) format, whereas ours are uploaded in the CRX2 format.

In other words, the `chrome.braveShields.onBlocked` event is never firing since there is no ad block DAT file and therefore no ad-block rules.

We either need to relax this restriction in the code, or update our components to CRX3 via https://github.com/brave/brave-core-crx-packager.

CRX format detail: https://cs.chromium.org/chromium/src/components/crx_file/crx3.proto

Looks like the package we're using is currently hardcoded to v2 https://github.com/oncletom/crx/blob/master/src/crx.js#L238 so we may have to contribute v3 to that package.

Here's where someone has changed their CRX parser to support v3 from v2: https://github.com/Rob--W/crxviewer/commit/3000452ff43ba302391036926fad2a8007118cbe

**Comment by petemill** [comment]
After investigation, it seems that this issue is occurring because the Ad Block updater component is not downloading successfully.

Seems to be the case for the other brave components too.

If a user already has a data directory, or copies the component files from a previous version, the blocking works correctly. Testing on https://blockads.fivefilters.org/

**Comment by petemill** [comment]
Changed the issue to reflect that our components are being blocked locally due to not supporting CRXv3. Added some detail to the description about the differences cc @bbondy. 

The fail is at https://cs.chromium.org/chromium/src/components/crx_file/crx_verifier.cc?gsn=VLOG&g=0&l=269

The requirement for the v3 file format is at https://cs.chromium.org/chromium/src/components/component_updater/component_installer.cc?g=0&l=414

**Comment by bbondy** [comment]
Maybe we should just allow CRX2 for now?

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}

Ensured that the shield count were working as expected after removing the following directories:
* removed `~/Library/Application\ Support/BraveSoftware/`
* only removed `~/Library/Application\ Support/BraveSoftware/Brave-Browser-Dev/`
* removed everything within `~/Library/Application\ Support/BraveSoftware/Brave-Browser-Dev/` but left the folder structure in place

Each time I ensured that brave launched without any issues and that the shield count was working when visiting the following:

* https://blockads.fivefilters.org
* https://www.skysports.com/football
