### ISSUE TITLE
[Desktop] Print a selection in amazon return center does not work

### ISSUE THREAD

**Issue by huehnerlady** [brave/brave-browser#8481]
## Description 
Hi, 
I love brave as it is really nice and fast compared to the other browsers.
So far I just found one thing that doesn't work properly for me.
Already tried to disable the shields, but no luck.

When I want to return something on Amazon, I usually select the return shipping label and the label that goes inside the parcel. so I mark the part of the return site I want to print, then click 'selection only' and then save it as a PDF.

On Chrome it works fine. But on Brave the shipping label is missing.
Instead I get a window like this:
![image](https://user-images.githubusercontent.com/12533979/75630406-d4ddc500-5bea-11ea-8a98-0b00b768bc19.png)

In Chrome it looks like the real label though.

## Steps to Reproduce

   1. Go to Brave start page
   2. Mark some area, including the last opened tabs
   3. print
   4. click `selection only`

## Actual result:
the result does not contain the images of the selected area
![image](https://user-images.githubusercontent.com/12533979/75630467-4a499580-5beb-11ea-89f0-fbc93c156918.png)

## Expected result:
The result should include the selected images.
You can compare this also by removing the `selection only` option. Then it looks like this:
![image](https://user-images.githubusercontent.com/12533979/75630461-40c02d80-5beb-11ea-9c37-1cae599c461b.png)

## Reproduces how often: 
I tried it with several amazon return procedures but never got the right result. So I always have to use chrome or Firefox for that 😞 

## Brave version (brave://version info)

```
Brave | 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Windows 10 OS Version 1909 (Build 18363.657)
JavaScript | V8 8.0.426.25
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,VideoPlaybackQuality,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,SmsReceiver,AudioServiceOutOfProcess,WebXrGamepadModule,WebXR --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\<USER>\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | 5e3a236d-4113a79e
```

any idea why there is a different behaviour?

**Comment by rebron** [comment]
Was able to reproduce on macOS and Win10. Happens with selection only.

Brave | 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | macOS Version 10.15.5 (Build 19F62f)

**Comment by bsclifton** [comment]
@rebron did you try with shields down? Curious if something is being blocked? Unclear what causes the problem

If you do a regular print, does it work?

**Comment by huehnerlady** [comment]
@bsclifton first thing I tried was turning off the shield but no change.

You can already see the printing preview has no image already, so I would assume this is not to do with the PDF saving?

**Comment by rebron** [comment]
Yup. Regular print of a page works it's just the [ ] selection only part for some pages. Shields on/off doesn't matter.  

It's looking like [ ] selection only print does generally work on most websites so for this Amazon page it's not working and I don't think we need a fix for selection only print for the new tab page.

I'll see if repros in chrome.

**Comment by huehnerlady** [comment]
> I don't think we need a fix for selection only print for the new tab page.

@rebron you are completely right. I just thought it is easier reproducable with the new tab page than the refund page of amazon - and as it behaved the same I was hoping to give additional help in reproducing the problem as easy as possible 🙂
