### ISSUE TITLE
Refactor Ledger code to use ExponentialDelay instead of Geometric for calculating random delays

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#8485]
Use `brave_base::random::ExponentialDelay` instead of `brave_base::random::Geometric` for calculating random delays. See https://github.com/brave/brave-browser/issues/8163

**Comment by Miyayes** [comment]
@tmancey Is this still relevant?

**Comment by tmancey** [comment]
@Miyayes this can be closed because it was decided that https://github.com/brave/brave-browser/issues/8163 would not be fixed,thanks
