### ISSUE TITLE
Brave Ads Purchase Intent segments should not fall back to parent segments

### ISSUE THREAD

**Issue by moritzhaller** [brave/brave-browser#8486]
Not serve from parent categories when targeting on intent: would pick any from e.g. "automotive purchase intent by make" achieveing the opposite of what an advertiser intends to do?

**Comment by moritzhaller** [comment]
@jsecretan currently the default for ads notifications is to fall back to parent category if there's no creative for a sub segment in inventory. Does this still hold true for intent, e.g. if audi targets "automotive-intent-audi" should it fall back to a general "automotive-intent" creative?

**Comment by moritzhaller** [comment]
@jsecretan I assume we don't want this, example: target automotive-audi > parent fall back automotive-bmw. can you confirm?

**Comment by tmancey** [comment]
Closing issue as won't fix
