### ISSUE TITLE
[Android] Update chromium theme to brave theme

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#8489]
## Description 
Brave App should have brave theme color through out the app. 

## Steps to reproduce 

   1. 
   2. 
   3. 

## Actual result 
Brave app uses chromium theme color blue for buttons and selectors.

## Expected result
Brave app should use brave theme color orange for buttons and selectors.

## Issue reproduces how often 
Easily

## Issue happens on 
   - Current Play Store version?
   - Beta build? Yes

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@deeppandya mind adding some visual examples of the issue and what the fix should look like so QA has some idea of what needs to be checked?

Adding which areas were affected that need to be checked would also be helpful.

**Comment by bsclifton** [comment]
Definitely need a higher quality issue here - the template is completely empty. Let's try to fill in fields that are applicable and include screenshots if necessary. There needs to be enough here to accurately describe the issue and for QA to verify

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10.0 running 1.5.110 x64 stable build
![image](https://user-images.githubusercontent.com/17010094/76282564-06772000-62be-11ea-8f37-0a44a1371cc6.png)
![image](https://user-images.githubusercontent.com/17010094/76282572-0d059780-62be-11ea-9432-f7d402b978b7.png)
![image](https://user-images.githubusercontent.com/17010094/76282576-0f67f180-62be-11ea-90d1-51c48a95c6ee.png)
![image](https://user-images.githubusercontent.com/17010094/76282590-15f66900-62be-11ea-83b5-e20da0b23f67.png)
![image](https://user-images.githubusercontent.com/17010094/76282583-12fb7880-62be-11ea-8c62-f6a54951c96c.png)
![image](https://user-images.githubusercontent.com/17010094/76282593-1989f000-62be-11ea-820b-181f4d420ee4.png)
![image](https://user-images.githubusercontent.com/17010094/76282604-24448500-62be-11ea-8fec-9fed20d1c82d.png)
![image](https://user-images.githubusercontent.com/17010094/76282613-30304700-62be-11ea-835f-dcd145a82879.png)
