### ISSUE TITLE
[Android] port playback in Brave option

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#8491]
There is an option in tabs version to play video files in Brave. In Site Settings. We need to port it.
![Screenshot_20200302-152723_Brave](https://user-images.githubusercontent.com/12011303/75715130-e54d7880-5c9a-11ea-94c3-bac380ffe7e4.jpg)

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.5.110 x64 stable build
- Verified `Video playback in Brave` entry is shown under site settings
- Verified disabling the setting switched to native apps for video playback
![image](https://user-images.githubusercontent.com/17010094/76282350-7042fa00-62bd-11ea-90cf-bdc7a7b52a43.png)
-----
Verification passed on OnePlus 6T with Android 10.0 running 1.5.110 x64 stable build
- Verified `Video playback in Brave` entry is shown under site settings
- Verified disabling the setting switched to native apps for video playback
![image](https://user-images.githubusercontent.com/17010094/76282387-86e95100-62bd-11ea-8b7a-308841e4e5e8.png)
