### ISSUE TITLE
Shield menu is not visible when switching the multiple windows

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8496]
## Description 

Shield menu is not visible when switching the multiple windows

## Steps to Reproduce

   1. Clean profile 1.5.106
   2. Open two windows and load a different/same site in both windows
   3. Click on the lion icon/shield icon in the URL bar
   4. Switch between the windows and repeat step 3 in both windows for multiple times
   5. Shield menu is not visible when switching the multiple windows
## Actual result:

Shield menu is not visible when switching the multiple windows
![image](https://user-images.githubusercontent.com/38657976/75801408-1adc8980-5da1-11ea-8b5a-889026df254e.png)

![image](https://user-images.githubusercontent.com/38657976/75802688-229d2d80-5da3-11ea-9a25-0848ce5f5b9c.png)

## Expected result:
Shield menu is should be visible when switching the multiple windows

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.5.106 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron

**Comment by rebron** [comment]
@GeetaSarvadnya Windows specific?

**Comment by bsclifton** [comment]
This seems to be mostly resolved - I was able to reproduce it once... but after that happened it wouldn't happen again. Definitely looks fixed to me 👍
