### ISSUE TITLE
Add "Don't ask me again" pref to 404 Wayback machine infobar

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#8497]
## Description 
For those users who don't want to see the 404 Wayback machine notification, provide a way to disable the notification without having to go to brave://settings/braveHelpTips.

Setting "Don't ask me again" should toggle 'Show Wayback Machine prompt on 404 pages' setting.

## Steps to Reproduce

   1.  Visit https://www.brave.com/bo
   2. Notice 404 infobar prompt.
   3. Need to provide a way to not show prompt again in context.

## Designs:
[placeholder]

**Comment by PierBover** [comment]
Please yes... this Wayback Machine integration is super annoying.

**Comment by yippie** [comment]
Even worse, it seems to show up when a single resource used by the page 404s

Go to https://mdcoverage.secure.force.com/docs/metadata-coverage 

notice the page loads completely and correctly but you STILL GET THE BANNER.

**Comment by rebron** [comment]
@yippie Via devtools console, it looks like something did 404 `https://mdcoverage.secure.force.com/docs/metadata-coverage/48` 
We'll look into not showing the prompt if the main resource is loading properly.

**Comment by bsclifton** [comment]
@yippie that page is trying to redirect to https://mdcoverage.secure.force.com/docs/metadata-coverage/48 which network shows a 404 received. Brave has no way to tell if the content actually loaded, only what HTTP status code was returned. This feature can be turned off on brave://settings/braveHelpTips

![Screen Shot 2020-04-08 at 9 37 44 AM](https://user-images.githubusercontent.com/4733304/78810035-a509a600-797c-11ea-8183-0dbbd9be1d23.png)
Just turn it off there and you'll never see it again 😄

**Comment by yippie** [comment]
Oh thank you! turned it off because the Wayback has proven completely worthless for me. I have never encountered a situation where it would actually work. I have only ever gotten it in two ways:

 - A resource, but not the main page, threw a 404 <- this was super annoying
 - I was trying to access an authenticated page after my session expired. Wayback would obviously not help there.

**Comment by bsclifton** [comment]
@yippie you're welcome 😄 

cc: @rebron for feedback!

**Comment by kjozwiak** [comment]
https://www.reddit.com/r/brave_browser/comments/g3y1iw/wayback_machine_in_private_mode_with_tor/fnvorf9?utm_source=share&utm_medium=web2x

Another example of users having a hard time finding the setting that disables this feature.

**Comment by stephendonner** [comment]
**Verified `PASSED`** using the testplan from https://github.com/brave/brave-core/pull/9030 with build 

Brave | 1.27.62 Chromium: 91.0.4472.101&nbsp;(Official Build)&nbsp;nightly&nbsp;(x86_64)
-- | --
Revision | af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}
OS | macOS Version 11.4 (Build 20F71)

### Scenario 1: `Don't ask me again` button

Steps:
1. new profile
2. loaded `brave://settings/braveHelpTips`
3. confirmed `Show Wayback Machine prompt on 404 pages` was toggled by default to `On`
4. loaded `brave.com/bad-link` and confirmed I got the Wayback Machine prompt
5. clicked the `Don't ask me again` button
6. confirmed the pref toggled back to `Off`
7. reloaded `brave.com/bad-link` and confirmed I no longer got the Wayback Machine infobar

example | example | example | example
---------|----------|---------|---------
<img width="1193" alt="Screen Shot 2021-06-14 at 12 55 30 PM" src="https://user-images.githubusercontent.com/387249/121952116-aa951580-cd10-11eb-91fc-d48fdb127ed0.png"> | <img width="1193" alt="Screen Shot 2021-06-14 at 12 57 01 PM" src="https://user-images.githubusercontent.com/387249/121952118-ab2dac00-cd10-11eb-9b3d-8b1f4619ceb1.png"> | <img width="1193" alt="Screen Shot 2021-06-14 at 12 57 15 PM" src="https://user-images.githubusercontent.com/387249/121952120-ab2dac00-cd10-11eb-90e6-16b9a3f12b4a.png"> | <img width="1193" alt="Screen Shot 2021-06-14 at 12 59 09 PM" src="https://user-images.githubusercontent.com/387249/121952124-abc64280-cd10-11eb-803a-3c63b77fcb67.png">


### Scenario 2: `Check for Saved Version` button

Steps:
1. new profile
2. loaded `brave://settings/braveHelpTips`
3. confirmed `Show Wayback Machine prompt on 404 pages` was toggled by default to `On`
4. loaded `brave.com/bad-link` and confirmed I got the Wayback Machine prompt
5. clicked on `Check for saved version`
6. confirmed it checked for a saved version and printed out `Sorry, there is no saved version available` in the infobar

example | example | example
---------|----------|---------
<img width="1193" alt="Screen Shot 2021-06-14 at 12 55 30 PM" src="https://user-images.githubusercontent.com/387249/121955317-a9fe7e00-cd14-11eb-9422-d0427c5e7c9e.png"> | <img width="1193" alt="Screen Shot 2021-06-14 at 12 57 15 PM" src="https://user-images.githubusercontent.com/387249/121955361-b682d680-cd14-11eb-9dbc-116fec0b8e17.png"> | <img width="1193" alt="Screen Shot 2021-06-14 at 1 29 12 PM" src="https://user-images.githubusercontent.com/387249/121955413-c8fd1000-cd14-11eb-824d-581975f1e202.png">

**Comment by rebron** [comment]
Thanks @rahulsnkr nice job!
