### ISSUE TITLE
Some bookmarks with duplicate ids are not synced

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#8498]
Follow up to https://github.com/brave/brave-browser/issues/8325

## Steps to Reproduce

Test case 1:
1. Go to `about:flags#brave-sync` and enable sync
2. Create a sync chain
3. Go to brave://bookmarks/
4. Add a bookmark
5. Go to `about:flags#brave-sync` and disable sync
6. COPY the bookmark
7. Go to `about:flags#brave-sync` and enable sync
8. Wait till both bookmarks are synced

Test Case 2:
Instead of bookmarks, use bookmark folders

## Actual result:

Only one bookmark is synced

Note: if the bookmark that is not synced is renamed, then it will eventually be synced

## Expected result:
Both bookmarks are synced

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.7.35 Chromium: 80.0.3987.122 (Official Build) nightly (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.7.35 Chromium: 80.0.3987.122 (Official Build) nightly (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @AlexeyBarabash @darkdh @jsecretan @rebron

**Comment by darkdh** [comment]
This is not duplicate id specific issue. You can replace the step "COPY" with adding a new bookmark or modifying the existing one when sync is disabled and those changes will not reflect on the other devices. Because when sync is disabled, it doesn't track any changes.

**Comment by btlechowski** [comment]
The bookmarks are eventually synced. It just takes some time. It took me 20 minutes, @AlexeyBarabash synced after 10 minutes.

Closing as invalid.

**Comment by AlexeyBarabash** [comment]
Thanks @btlechowski  for looking on this detail.
