### ISSUE TITLE
[Android] Fix verified icon on brave rewards panel

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#8501]
Need to move fix from tabs https://github.com/brave/browser-android-tabs/pull/2183

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.110 stable x64 build
- Verified pub icon is shown on both BR panel and AC list
![image](https://user-images.githubusercontent.com/17010094/76280374-a8dfd500-62b7-11ea-9ec0-b7c011fcc608.png)
![image](https://user-images.githubusercontent.com/17010094/76280380-ac735c00-62b7-11ea-8d1d-a2920f79e866.png)
-------
Verification passed on Samsung Tab A with Android 9.0 running 1.5.110 x64 stable build
- Verified pub icon is shown on both BR panel and AC list
![image](https://user-images.githubusercontent.com/17010094/76280738-db3e0200-62b8-11ea-87da-50fc427203bc.png)
![image](https://user-images.githubusercontent.com/17010094/76280740-dda05c00-62b8-11ea-9925-7694b530f4e3.png)
