### ISSUE TITLE
tip banner has message for connected publisher when panel does not - follow up to 7739

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8512]
## Description 
Found while testing #7739 , similar to https://github.com/brave/brave-browser/issues/6182 (pre-VG)

While testing #7739, the panel does not contain a 'connected publisher message' but the tip banner does. In the scenario described below, neither the panel nor the tip banner should have this message. 

## Steps to Reproduce

   1. enable rewards on staging profile
   2. claim grant
   3. connect verified uphold wallet
   4. go to bumpsmack.com
   5. open panel, make sure that you don't see connected message
   6. open tip banner
---> there is a message but there should not be

## Actual result:
<img width="1192" alt="SS1" src="https://user-images.githubusercontent.com/28145373/75821153-c0750600-5d6b-11ea-8931-7cee70e79628.png">

when retesting, also do the following steps:
   7. spend UGP grant
   8. open both panel and tip banner, make sure that you see connected message on both places once UGP grant is all contributed.

## Expected result:
In this scenario, neither panel nor tip banner should have a message until the ugp grant is spent.

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.5.106 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? probably
- Can you reproduce this issue with the nightly channel? probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc @brave/legacy_qa

**Comment by btlechowski** [comment]
Reproduced on 

Brave | 1.5.106 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/75828937-44031700-5dad-11ea-953b-61f4781bb5f5.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.71 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4829 and steps from description:
<img width="1190" alt="Screen Shot 2020-03-24 at 12 10 29 PM" src="https://user-images.githubusercontent.com/28145373/77453058-1d913400-6dcd-11ea-8ccd-d71b18cd77a4.png">
<img width="1192" alt="Screen Shot 2020-03-24 at 12 10 45 PM" src="https://user-images.githubusercontent.com/28145373/77453060-1f5af780-6dcd-11ea-820b-7c36ae5b3687.png">

* Verified that if you don't have any Brave funds (ex. all the UGP is contributed or you did not have a UGP grant and you connected a KYC'd sandbox wallet), bumpsmack.com does show the connected publisher message as expected:
<img width="1197" alt="Screen Shot 2020-03-24 at 12 43 01 PM" src="https://user-images.githubusercontent.com/28145373/77453146-3d285c80-6dcd-11ea-9073-0ad90605ce8d.png">
<img width="1193" alt="Screen Shot 2020-03-24 at 12 43 17 PM" src="https://user-images.githubusercontent.com/28145373/77453158-3f8ab680-6dcd-11ea-9e27-07ac893054a7.png">
