### ISSUE TITLE
Give non-eTLD+1 frames site-length, ephemeral storage

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#8514]
Currently non eTLD+1 frames get do not have any storage, which means frames expecting normal acting localStorage, document.cookie, etc will have web compat problems.

non eTLD+1 frames should instead get
1. Empty storage (e.g. the frame at start doesn't see any stored values)
2. site length storage (all storage is deleted when all top-level frames pointing at the site are closed / deleted)
3. API compatible storage (e.g. document.cookie acts in the weird ways document.cookie acts, etc.)
4. Isolation from other ways of getting to the domain's normal storage (e.g. either prevent them from spinning up workers, or ensure that those workers get similar ephemeral / isolated storage)
5. partitioned-by-frame storage (two A frames under the same B frame see the same storage, but A frames under different B frames see different storage, A under B sees different storage than A under C or top-level-A)
6. (possibly) Storage Access API escape valve (sites wanting more storage can use storage access API to get global / unpartitioned storage)

**Comment by pes10k** [comment]
Note to self: check to see if this fixes https://github.com/brave/brave-browser/issues/6046 when this is closed

**Comment by pes10k** [comment]
https://fivethirtyeight.com/videos/do-you-buy-that-biden-should-pick-a-running-mate-from-a-swing-state/ is another example of a site this would unbreak

**Comment by pes10k** [comment]
This would also unbreak https://community.brave.com/t/chart-is-blank-in-brave-browser/138464

**Comment by pes10k** [comment]
Would also unbreak https://www.rdocumentation.org/packages/grid/versions/3.6.2/topics/grid.plot.and.legend

**Comment by pes10k** [comment]
W3C related conversation on the updated version of this approach / idea https://github.com/privacycg/proposals/issues/18

**Comment by pes10k** [comment]
Would remove the need for this exception: https://github.com/brave/brave-browser/issues/10494

**Comment by dlecan** [comment]
Hi,
all Rocket.chat livechat widgets are broken on any sites because they are using iframes with null storages on Brave (example: https://unikname.com)
If any, what is the release plan of this feature?

Thank you

**Comment by pes10k** [comment]
@dlecan we're getting close!  No promises, but looks like we might land an implementation in nightly in the next week or three (though the holidays might slow things down).  It'd then take two releases (~6 weeks) for it to make its way to stable unless we do an uplift (which, given the need for testing here, is unlikely)

**Comment by dlecan** [comment]
Thank you!
Tell us as soon as a nightly embeds this new feature, I'd like to test it on my sites!

**Comment by pes10k** [comment]
@dlecan just curious / double checking through, does your implementation expect all embedded widgets to see the same storage area (or would our dual-keyed approach work for you, [fingers crossed])?

Similar, does your widget depend on DOM storage being persisted across sessions?

If the answers to the above are "no" and "no", then… have i got good news for you!

Otherwise, would be glad to get to learn more about your app's needs.  I can't promise we can change Brave's policy in any particular way (we're not looking to relax privacy boundaries), but I would be useful to better understand the needs of privacy-respecting developers, to give us a better understanding of the space and tradeoffs

**Comment by dlecan** [comment]
> does your implementation expect all embedded widgets to see the same storage area
Not really.
Of course, that would be interesting if this respects the users' privacy.

> or would our dual-keyed approach work for you
I don't know what is this.

> Similar, does your widget depend on DOM storage being persisted across sessions?
Again, not really.

**Comment by pes10k** [comment]
> I don't know what is this.

Dual keyed here (or what WebKit calls partitioned storage) means that A under B sees different storage than A under C. It allows embedded frames to see storage, but see different storage for each site they're embedded on

By dual keying storage, we prevent tracking across sites.  By making the storage ephemeral, we prevent 3p tracking across time.

Hope that helps.  Happy to discuss / describe more if it'd be helpful

**Comment by dlecan** [comment]
> Dual keyed here (or what WebKit calls partitioned storage) means that A under B sees different storage than A under C. It allows embedded frames to see storage, but see different storage for each site they're embedded on

👌

> By dual keying storage, we prevent tracking across sites.

What about subdomains?

> By making the storage ephemeral, we prevent 3p tracking across time.

👌

**Comment by pes10k** [comment]
> What about subdomains?

Storage is key'ed by the site / eTLD+1, so third parties that have different subdomains, but the same eTLD+1, would see the same storage area, when embedded under the same 1p

**Comment by dlecan** [comment]
Happy New Year!
@pes10k any news about this feature? Maybe a Brave nightly to test soon?

Thank you

**Comment by pes10k** [comment]
Hi @dlecan!  Two answers:

One, you can actually test in Nightly now, but its actually a bit awkward to enable, so I suggest holding off a bit longer.  If you're feeling bold though, you can:

1. Go to brave://flags and enable Ephemeral Storage
2. Go to brave://settings/shields and set cookie blocking to "Disabled" (i.e. turn off 3p cookie blocking)

The above will globally enable ephemeral storage its not well integrated into Shields, and has some other awkwardness

However, better news, I expect we'll land a proper integration this week (famous last words). When that happens, we'll also put out a blog post describing how things work, what the exact policy is, etc.

**Comment by pes10k** [comment]
For folks following along here, this is now implemented in nightly, but behind a flag. More details here: https://brave.com/privacy-updates-7/

**Comment by dlecan** [comment]
> curious to see if / how this addresses the web compat concerns you mentioned on your site

:tada: :confetti_ball: yes, many improvements!
Basic features of Rocket.chat Livechat are working: iframe displaying, interacting with the chat

Issues:
- no data at all in "developer console->Application": localstorage, sessionstorage, cookies, indexdb ... about the domain linked to the TLD+1 frame are empty
- weird javascript errors when the iframe is running (missing properties - don't understand why - need investigation)
- 
Great work! :muscle:

**Comment by bogger33** [comment]
Sorry if I'm being a bit dense here, but would this allow a site that embeds a comment form cross-domain via an iframe, that relies on its first party cookies for login, to access those cookies from the iframe (i.e. cookies set on the domain while it was in a first party context)? 

For safari this is possible with the storage access API, albeit it has to be triggered by a user interaction (so what we do is display a login button that on safari makes a storage access request, checks for being logged in, and then refreshes the iframe to show the logged in version of the frame - or in the case of not being logged in, opens the login form in a new window). I'd like to get it working in brave as well but I'm a little unsure from the wording whether this is possible

**Comment by pes10k** [comment]
Hello @bogger33; no it would not, there is not any way for a third party frame to access its 1p / un-partitioned storage.  We also don't have any plans to implement storage access API, though we've considered it (I personally don't like the permission fatigue it seems to encourage). If the first party intends a tight coupling w/ a third-party frame like this, where the third-party needs long term storage, the best way (by design) to do this in Brave for the foreseeable future will be for the first-party to intentionally allow the 3p to use the 1p storage (and pass long term values back and forth with postMessage or similar.

That wouldn't solve the automatic login use, but, functionality wise, it would only require the user to login once per 1p.

I appreciate that this may not fulfill what you're looking for, but we think (or at least want to test whether) this will be best for our users, given the privacy/compat/convenience all the tradeoffs.

Thanks very much for your comment!

**Comment by dlongley** [comment]
@pes10k,

>  We also don't have any plans to implement storage access API, though we've considered it (I personally don't like the permission fatigue it seems to encourage). If the first party intends a tight coupling w/ a third-party frame like this, where the third-party needs long term storage, the best way (by design) to do this in Brave for the foreseeable future will be for the first-party to intentionally allow the 3p to use the 1p storage (and pass long term values back and forth with postMessage or similar.

This sounds like it would not support our use case, described here:

https://github.com/privacycg/storage-access/issues/10#issuecomment-584160969

Is there a version of the Storage Access API that Brave could implement that would not involve any prompts (presuming this is what you are concerned about with respect to permission fatigue)? Do you have any other suggestions for how to enable our use case in Brave?

**Comment by bogger33** [comment]
@pes10k 
In my case, I control both domains and they point to the same server, however one of them hosts user generated HTML, and the other one houses the comment form and the main site. This was done all the way back in the age of ie6, when you couldn't safely host user generated html on the same TLD or a subdomain without risking letting users hijack accounts, and it's not possible to change it now. Would there be any way to do this if I am in control of both domains, and they're hosted on the same server/share full data access on the backend? I can easily run arbitrary scripts on both domains, but I'm not really sure how to authenticate one from the other with the way things work in brave

>for the first-party to intentionally allow the 3p to use the 1p storage (and pass long term values back and forth with postMessage or similar.

could you elaborate what you mean by this? or do you just mean to move the login form to the first party domain that houses the comment form in the iframe currently, and then pass that on? that wouldn't work in our setup unfortunately

**Comment by pes10k** [comment]
@bogger33 If you control both frames, you can use the main / 1p site as your permanent data store, and send those persistently-stored values to the third-party frame using postMessage, and then use those values as you like in the 3p frame.  Just know (as in Safari, for example) that any values that are stored in the storage area of the 3p frame will be lost when the frame closes.

@dlongley the best I can suggest for now (besides an extension or browser integration) would be using 1p redirect, and bouncing the credentials back to the original site.  So, in your example, rp.example would have a link to authn.io (which is where the 1p auth storage is if i understand correctly).  User clicks that link, is taken to authn.io, which does what it needs to do, and redirects back to rp.example w/ the values in the URL or otherwise (basically, an oAuth flow). I think that'd work for ya, and as long as you steered clear of getting classified as a tracking origin by Firefox or Safari (as determined by Disconnect or ITP) you'd be fine in those browsers.

Brave also has upcoming plans for protecting against using the above pattern for bounce tracking, but nothing concrete yet.

Hope that helps!

**Comment by bogger33** [comment]
@pes10k I can't really do that, since hosting the login on the domain with the user generated html content is just an invitation for people to make phishing forms on that domain, and there's more than one domain the comment form gets embedded from (basically it's a site generator so people can hook up their own domain names). I guess I will also have to go with an oauth type of thing in a popup, although I was trying to avoid it since it adds a lot of friction for leaving a comment. I know it's not a simple problem to solve, but I wish there was a better way to transfer credentials accross domains that belong to the same site.

**Comment by dlongley** [comment]
@pes10k,

> the best I can suggest for now (besides an extension or browser integration) would be using 1p redirect, and bouncing the credentials back to the original site. So, in your example, rp.example would have a link to authn.io (which is where the 1p auth storage is if i understand correctly). User clicks that link, is taken to authn.io, which does what it needs to do, and redirects back to rp.example w/ the values in the URL or otherwise (basically, an oAuth flow). I think that'd work for ya, and as long as you steered clear of getting classified as a tracking origin by Firefox or Safari (as determined by Disconnect or ITP) you'd be fine in those browsers.

Unfortunately, falling back to an oauth-style flow would defeat one of the main purposes of the credential handler technology. It was created, in part, to eliminate the problem of redirection and loss of state on the relying party. The polyfill works on browsers that support the Storage Access API -- but it is sounding like there is no clear and privacy-preserving alternative means to polyfill for Brave. I do hope the Brave team will reconsider implementing the Storage Access API in the future.

**Comment by pes10k** [comment]
Closing this issue since the feature has been merged in for a while, is on by default on Beta and Nightly, and being deployed to stable through Griffin (currently ~20% enabled)

**Comment by kjozwiak** [comment]
@pes10k is there anything that QA needs to do here? If so, is there any STR/Cases?

**Comment by pes10k** [comment]
@kjozwiak nothing other than the tests https://dev-pages.brave.software/storage/ephemeral-storage.html (which I think have already been tied to another related issue IIRC; there are several issues all relating to ephemeral storage)

**Comment by kjozwiak** [comment]
Sounds good 👍 Going to label this as `QA/No`. Is this something we should mention in our release notes or has this been covered in a previous release or another issue within `1.22.x` ?

**Comment by pes10k** [comment]
I am not sure if its been mentioned in release notes (given that the roll out is being controlled by griffin), but i think a QA/No sounds 👍

**Comment by dlecan** [comment]
> Closing this issue since the feature has been merged in for a while, is on by default on Beta and Nightly, and being deployed to stable through Griffin (currently ~20% enabled)

Awesome work!
Everything is working as expected on our site with Brave stable :muscle: ... but only for the happy fews who have the "ephemeral-storage" flag enabled by default :joy: 
Do you know when this flag will be enabled for anyone?

**Comment by pes10k** [comment]
@dlecan it should be default on for all users now, as per https://github.com/brave/brave-variations/pull/13.  Are seeing otherwise?

**Comment by dlecan** [comment]
Thank you for the pointer, I haven't found anything about 'Griffin" before :)

Screenshot of https://griffin.brave.com/ a few seconds ago:

![image](https://user-images.githubusercontent.com/586631/113926980-2a70a200-97ed-11eb-830c-6504ad6e205b.png)

Beta variation is at 100%.

If I run Brave with "beta" variation (`brave-browser --fake-variations-channel=beta`), ephemeral storage is enabled.

What's wrong with release variation?

**Comment by pes10k** [comment]
thanks @dlecan , that is unexpected, i will talk to folks and get back to you shortly!

**Comment by pes10k** [comment]
Hi @dlecan looks like a task runner fell over when trying to deploy the "on for everyone" update.  If you referesh https://griffin.brave.com/ you'll see we're at 100% for all channels now.

Thanks for letting us know!

**Comment by dlecan** [comment]
Enabled for everyone this morning and working as expected :muscle: 
Thank you!
