### ISSUE TITLE
Import history from Safari

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#8515]
## Description 
Support importing 'History' from Safari and update the `Import Bookmarks & Settings...` dialog to show History option, checked by default if History in Safari is present.

## Expected Results

   1. Select `Import Bookmarks and Settings...` from the Brave app menu or from `brave://settings/getStarted`
   2. Select Safari if not already selected.
   3. User only sees Favorites/Bookmarks checkbox.
   4. User should also see a check box item [that is selected checked] for History.
   5. Upon selecting import, prompt for Full Disk access.

![75483199-31c34c00-595b-11ea-968b-185c79a99efe](https://user-images.githubusercontent.com/5951041/75832213-7c353600-5d6a-11ea-933f-273e35cd5ac9.png)

Related to: https://github.com/brave/brave-browser/issues/2710

**Comment by rebron** [comment]
cc: @simonhong

**Comment by simonhong** [comment]
Upstream code refers `History.plist` for importing `Safari` history. 
However, `Safari` doesn't use it anymore. It uses `History.db` now.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.75 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR from description
* Confirmed after allowing Full Disk Access in preferences (and restarting Brave Dev), I could import Browsing history individually, Favorites/Bookmarks individually, or both together.

<img width="551" alt="Screen Shot 2020-06-24 at 8 40 52 AM" src="https://user-images.githubusercontent.com/28145373/85558291-9b482400-b5f6-11ea-8094-485787887656.png">

cc @kjozwiak to check on Catalina
