### ISSUE TITLE
Downloading proxy script take ages

### ISSUE THREAD

**Issue by StephD** [brave/brave-browser#8523]
## Description 

Every time I open my laptop from sleep after a small period of sleep, like a night. It can be in the morning but also can be after 2 hours, don't know exactly. Brave cannot load any website for, at least, 1 minute. I can open any tab or refresh my tabs, they will keep loading state.
The only thing I notice is a message on the bottom left that they "Downloading proxy script..."

Note that I don't have this problem with firefox. If I open firefox while brave got this loading time, firefox open directly the website without any extra loading.

Edit : chrome doesn't look like to have this issue neither. Chrome download the script at the first launch, but it take like 2 second.

note: I do not use any VPN or proxy. May be from a specific wifi location, like a cafe, that might use a proxy

## Steps to Reproduce
Hard to reproduce exactly. I just notice that it happen after a small period of sleep time
   1. My computer is sleeping with brave opened. (Edit) Or a bit of time without usage
   2. I turn on my computer from sleep (Edit), not just from sleep
   3. Connect to a wifi
   4. Got a loading time

## Actual result:
![2020-03-04 11_53_13-](https://user-images.githubusercontent.com/1171858/75844057-ebb13100-5e0f-11ea-8e4d-a804b13981ee.png)

## Expected result:
No 1 minute loading

## Reproduces how often: 

Like every day

## Brave version (brave://version info)

Brave | 1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit)
-- | --
Revision | dc00a510e4c2ae25c4d084cc3d946fc782249224-refs/branch-heads/3987@{#917}
OS | Windows 10 OS Version 1909 (Build 18363.657)
JavaScript | V8 8.0.426.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36

## Version/Channel Information:

No idea

## Other Additional Information:
Did not try. I will try to download chrome again and open it when I got the issue
- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
Hi @StephD. Can you try with our latest 1.7.98 and see if you're still running into your issue. We'll also need more reproducible steps to understand what's happening here.

**Comment by StephD** [comment]
I will update and see if the problem happen again, thanks

**Comment by jens1000** [comment]
I solved this problem with the following two steps:

- Go to your Windows proxy settings (Win + i -> Network & Internet -> Proxy)
- Disable "Automatically detect settings".

**Comment by bsclifton** [comment]
As there isn't anything actionable here - I'll go ahead and close the issue. But if it happens again, please try the suggestion that @jens1000 offers (thanks for the assist!) and let us know if it still happens. If we have more information, we can re-open the issue and continue digging in. Thanks 😄

**Comment by Gareth-Rouse** [comment]
Had the same issue. @jens1000 solution appears to work.
