### ISSUE TITLE
brave://wallet alias not shown while looking up an ENS domain or on a suspicious site

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#8524]
Reproduction steps:
1. Enable Crypto Wallets via `brave://wallet`
2. Visit a site that will trigger phishing detection, a list can be found here: https://github.com/MetaMask/eth-phishing-detect/blob/master/src/hosts.txt
3. Visit an ENS url, such as `http://vitalik.eth`

Results:
<img width="1329" alt="Screen Shot 2020-03-03 at 8 04 13 PM" src="https://user-images.githubusercontent.com/8732757/75844252-4acc6280-5d8a-11ea-9000-5286a5c13e7e.png">
<img width="1328" alt="Screen Shot 2020-03-03 at 8 04 02 PM" src="https://user-images.githubusercontent.com/8732757/75844256-4e5fe980-5d8a-11ea-8e86-1a41e15e85ac.png">

Expected: `brave://wallet` to be shown in the URL bar

**Comment by btlechowski** [comment]
@ryanml For `http://vitalik.eth` I get: 
![image](https://user-images.githubusercontent.com/34715963/77381761-f7dd3e00-6d7e-11ea-9862-c3a2e39b3d39.png)

Is this expected behavior?

**Comment by ryanml** [comment]
@btlechowski yep that's the correct behavior for the final resolution. This fix just made sure that `brave://wallet` was showing when this was being redirected to. Thanks for checking.

**Comment by kjozwiak** [comment]
Quick notes for QA:

* You'll need to wait till `~/Library/Application\ Support/BraveSoftware/Brave-Browser-Dev/Safe\ Browsing` pulls the lists before attempting the STR via https://github.com/brave/brave-browser/issues/8524#issue-575123174
* You can use `http://sether.ws/` from https://github.com/MetaMask/eth-phishing-detect/blob/master/src/hosts.txt (most hosts/websites don't exist anymore).

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.3 x64 Catalina` using the following build:

```
Brave | 1.7.71 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.15.3 (Build 19D76)
```

* launched `1.7.71 CR: 80.0.3987.149` and waited for the `Safe Browsing` list to download
* visit `brave://wallet`
* visited http://sether.ws and ensured `Safe Browsing` was triggered (Deceptive website)
* visited http://vitalik.eth and ensured `brave://wallet` appeared in the URL before https://app.ens.domains/name/vitalik.eth loaded

<img width="1027" alt="Screen Shot 2020-03-24 at 12 24 40 PM" src="https://user-images.githubusercontent.com/2602313/77451054-87f4a500-6dca-11ea-9bdf-1def2bb016ee.png">
