### ISSUE TITLE
Transactions can be signed from the incorrect ledger account

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#8530]
This is a fix we need to pull in upstream via: https://github.com/MetaMask/eth-ledger-bridge-keyring/pull/14

STR:

1. Connect a Ledger account > 1 (e.g. the 2nd account)
2. Confirm that sending a transaction is signed correctly
3. Reload MetaMask (or, for non-MM, construct a new instance from serialized state)
4. Confirm that sending a transaction is signed with the 1st account on the Ledger (an incorrect account)

Expected:

1. Connect a Ledger account > 1 (e.g. the 2nd account)
2. Confirm that sending a transaction is signed correctly
3. Reload MetaMask (or, for non-MM, construct a new instance from serialized state)
4. Confirm that sending a transaction is signed with the 2nd account on the Ledger (the correct account)

**Comment by kjozwiak** [comment]
Verification *PASSED** on `macOS 10.15.3 x64 (Catalina)` using https://github.com/brave/ethereum-remote-client/releases/tag/0.1.51

```
Brave | 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | macOS Version 10.15.3 (Build 19D76)
```

* ensured that connected to a Ledger HW device worked without any issues
* ensured that sending ERC20 tokens from the Ledger into a CW and MM created account worked without any issues
* ensured that receiving ERC20 tokens from CW and MM created accounts into the Ledger HW device worked without any issues
