### ISSUE TITLE
Shields should show Simple view by default for new users + browser profiles

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#8533]
## Description 
Currently, new users and browser profile see the Advanced view of Shields by default, but it should show Simple. Seems to be a bug that broke https://github.com/brave/brave-browser/issues/1196 because it was working correctly before.

## Test plan / Steps to Reproduce

   1. Open a new browser profile or destroy your profile directory for Brave
   2. Launch into Brave
   3. Visit brave://settings/shields and confirm `Simple view` is selected
   4. Quit Brave and relaunch
   5. Visit brave://settings/shields and `Advanced view` is selected?? 🤔 

## Actual result:
User ends up seeing Advanced view for their first time ☹️ 
<img width="377" alt="Screen Shot 2020-03-04 at 11 59 34 AM" src="https://user-images.githubusercontent.com/2388823/75917980-c1f80a00-5e0f-11ea-9b39-df3097fed5c6.png">

The Shields global settings in browser preferences also shows Advanced view as the default:
<img width="682" alt="Screen Shot 2020-03-04 at 12 00 46 PM" src="https://user-images.githubusercontent.com/2388823/75918033-d76d3400-5e0f-11ea-8310-d2a9c4f41cda.png">

## Expected result:
Shields should show simple view by default:
<img width="377" alt="Screen Shot 2020-03-04 at 12 02 22 PM" src="https://user-images.githubusercontent.com/2388823/75918149-08e5ff80-5e10-11ea-8d9c-868e6da967c7.png">

## Reproduces how often: 

Always

## Brave version (brave://version info)

All versions

**Comment by bsclifton** [comment]
I made changes related to this, but it was signed off and working in 0.69.x:
https://github.com/brave/brave-core/pull/3154

Basically, when profile is checked, it will look to see if the user is on their first run (ex: no profile directory exists). If no profile directory exists, it defaults to simple mode.

**Comment by bsclifton** [comment]
@karenkliu @rebron unable to reproduce with a fresh profile. I also tried creating a new profile from inside the browser (Hamburger => Create New Profile). Both showed simple mode

I don't think there's a bug- can you verify please?

**Comment by bsclifton** [comment]
OK bug identified - let me update the steps in the original post 😄

**Comment by bsclifton** [comment]
Turns out this wasn't a regression - it was a bug. Was broken even with initial implementation

**Comment by karenkliu** [comment]
@bsclifton :scream: Ah! So Shields has been showing Advanced by default to new users for the last 5 months??

**Comment by bsclifton** [comment]
@karenkliu unfortunately, yes ☹️  As of today, this will be in Beta- so it'll be coming soon

**Comment by karenkliu** [comment]
@bsclifton ok, thanks for the update and hustling to fix it! 😬

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.13 x64 Catalina` using the following build:

```
Brave | 1.7.71 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.15.3 (Build 19D76)
```

* Verified the STR outlined via https://github.com/brave/brave-browser/issues/8533#issue-575728727
* ensured that `Simple View` was being used after several restarts
* ensured that switching to `Advanced View` via `brave://settings/shields` worked
  * ensured that the shields display the `Changing Shield settings in this view may affect web compatibility on this site.` when initially changing to `Advanced View`
   * ensured that the `Advanced View` is kept selected after restarting Brave several times
* ensured that switching between `Simple View` & `Advanced View` via the shields works as expected
  * ensured that `brave://settings/shields` also reflects the changes
* ensured that switching between `Simple View` & `Advanced View` via `brave://settings/shields`
