### ISSUE TITLE
When Ads/Rewards switch is disabled in brave://rewards page enable Ads/Rewards notification isn't shown on NTP

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8534]
## Description 

When Ads/Rewards switch is disabled in brave://rewards page enable Ads/Rewards notification isn't shown on NTP
## Steps to reproduce 

Scenario1:  Ads enable notification modal isn't shown

   1. Clean profile 1.5.4
   2. Launch brave and skip onboarding flow
   3. Exit brave and relaunch app
   4. Open a NTP-SI, 1st sponsored image is shown
   5. Enable rewards from the 1st NTP-SI notification
   6. Navigate to brave://rewards and disable Ads switch
   7. Open an NTP or NTP-SI, enable Ads notification isn't shown
   8. Repeat step 7, no ads enable notification

Scenario 2:  Rewards enable notification modal isn't shown

   1. Clean profile 1.5.3
   2. Launch brave and skip onboarding flow
   3. Upgrade to 1.5.4
   4. Open 1st SNTP, 1st sponsored image is shown
   5. Enable rewards from the 1st NTP-SI notification
   6. Navigate to brave://rewards and disable Brave Rewards switch
   7. Open an NTP or NTP-SI, enable Rewards notification isn't shown
   8. Repeat step 7, no Rewards enable notification

## Actual result 

Enable Ads/ Rewards notification isn't shown
## Expected result
Enable Ads / Rewards notification should be shown

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.5.4

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @deeppandya @mandar-brave @anthonypkeane @SergeyZhukovsky

**Comment by bsclifton** [comment]
Shouldn't be an issue anymore; BRE landed with 1.18
