### ISSUE TITLE
setting to disable ad conversion detection isn't working

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8536]
## Description 
During an overview of ad conversion with @tmancey it was discovered that the `Allow ad conversion detection` checkbox does not prevent ads with conversion settings in the catalog from displaying.

## Steps to Reproduce

   1. Launch profile with staging catalog for US
   2. Enable Rewards
   3. Uncheck the `Allow ad conversion detection` checkbox
   4. Browse such that you would trigger an ad that has conversion settings in the catalog

## Actual result:

Ad w/ conversion settings is triggered

## Expected result:
Ad w/ conversion settings should not be triggered

## Reproduces how often: 

easily

## Brave version (brave://version info)

n/a - issue was found locally on Terry's machine 

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

added `release/blocking` and `P1` labels per info from @tmancey that this was a critical issue. if it is not, please feel free to change them.

cc @jsecretan @bsclifton @kjozwiak @kjozwiak

**Comment by LaurenWags** [comment]
@jsecretan @tmancey since the setting was removed, what should we do with this issue? we can't test the fix. cc @kjozwiak

**Comment by tmancey** [comment]
@LaurenWags This issue can be ignored going forward unless UI/UX is added again in the future

**Comment by LaurenWags** [comment]
thanks @tmancey - marking as QA/No then since this can't be tested as the UI was removed. if you disagree @kjozwiak @rebron please change label back.
