### ISSUE TITLE
You have exceeded the allowed ads per hour after viewing 1 ad

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#8539]
## Description 

You have exceeded the allowed ads per hour after viewing 1 ad

## Steps to Reproduce

   1. Set "Ads per hour" to 2 in Ads Settings
   2. View an ad
   3. Click the ad
   4. Wait 30 mins

## Actual result:

The ad was not shown due to exceeding the allowed ads per hour, as all confirmation types such as viewed, clicked, dismissed count towards the history

## Expected result:
The ad should be shown (if eligible, see console logs and search for `not made:`)

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Fixed by only using views for calculating the frequency capping

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.5.111 Chromium: 80.0.3987.132 (Official Build) (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified STR from the description
* Confirmed ad notifications were being displayed based on the per hour setting in the ads panel
