### ISSUE TITLE
[Android] Move tabs PR into android-core: 2224,2393,2400.

### ISSUE THREAD

**Issue by gdregalo** [brave/brave-browser#8541]
## Description 
Please move the tab's PRs into android-core:
https://github.com/brave/browser-android-tabs/pull/2224
https://github.com/brave/browser-android-tabs/pull/2393
https://github.com/brave/browser-android-tabs/pull/2400

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 x64 stable build
- Verified BAP/BAT Points shows for Japanese install (Needs a  double check after #8873)
- Verified AC notification doesn't show 0.0 BAT 
- Verified AC shows proper amount for contribution
-------
Verification passed on Samsung Tab A with Android 9.0 x64 stable build
- Verified BAP/BAT Points shows for Japanese install (Needs a  double check after #8873)
- Verified AC notification doesn't show 0.0 BAT 
- Verified AC shows proper amount for contribution
-------
