### ISSUE TITLE
Auto format JSON - Feature Request

### ISSUE THREAD

**Issue by krynv** [brave/brave-browser#8545]
## Description 

As a developer, it's frustrating having to copy & paste raw, minified/ unformatted JSON into a JSON formatter or installing a third party app to format the JSON in a nice way - when reading from an API I'm currently developing.

I'd like to see an 'auto-format' option for JSON objects, with perhaps a built in search feature so I can easily traverse the objects I'm querying. 

For example:

    [{"id":1,"name":"House on a Hill","description":"It's a house, on a hill.","bedrooms":"2","bathrooms":"2","parking":"4","created_at":"2020-02-28T11:42:09.758Z","updated_at":"2020-02-28T11:44:55.685Z","agents":{"id":1,"name":"John Doe","number":"01234 567890","email":"john.doe@email.com","created_at":"2020-02-28T11:43:16.971Z","updated_at":"2020-02-28T11:43:16.971Z"},"image":[{"id":1,"n

Could be:
```
[
	{
		"id: 1,
		"name": "House on a Hill",
		"description": "...."
	...
```

You get the idea.

I don't want to rely on third party plugins from the google extension market, or websites that I have to manually copy & paste to.

This was posted over at community.brave.com with no traction:
https://community.brave.com/t/automatic-json-formatting/110452

**Comment by krynv** [comment]
Is that a `wontfix` - will not be implemented?

**Comment by rebron** [comment]
@krynv We won't be able to put any effort into this but happy to pick up when fixed in chromium in general  -> https://bugs.chromium.org/p/chromium/issues/list File this issue there or check if there's a dupe already.
