### ISSUE TITLE
[Android] Move rewards panel ui fixes from tabs to core

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#8548]
Move these fixes:
https://github.com/brave/browser-android-tabs/pull/2070
https://github.com/brave/browser-android-tabs/pull/2072

**Comment by bsclifton** [comment]
Updated to link to the test plans used for original testing

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.111 x64 stable build
- Verified date format is correct as per device locale. Used test plan from brave/browser-android-tabs#1309
![image](https://user-images.githubusercontent.com/17010094/76742999-f36dbf80-6797-11ea-963e-c3ddaa6e0a41.png)
--------
Verification passed on Samsung Tab A with Android 9.0 running 1.5.111 x64 stable build
- Verified date format is correct as per device locale. Used test plan from brave/browser-android-tabs#1309
![image](https://user-images.githubusercontent.com/17010094/76743062-0f716100-6798-11ea-83da-3981817e07a7.png)

==================================================================

Verification passed on OnePlus 6T with Android 10 running 1.5.111 x64 stable build
- Verified USD text colour is lighter than the BAT value text. Used test plan from brave/browser-android-tabs#1151
![image](https://user-images.githubusercontent.com/17010094/76743426-9c1c1f00-6798-11ea-869f-a3607e5f1dea.png)
---------------
Verification passed on Samsung Tab A with Android 9running 1.5.111 x64 stable build
- Verified USD text colour is lighter than the BAT value text. Used test plan from brave/browser-android-tabs#1151
![image](https://user-images.githubusercontent.com/17010094/76743437-a0483c80-6798-11ea-9776-328e83dcb3c7.png)
