### ISSUE TITLE
 tor-0.3.5.8-win32-brave-1 blocked by WindowsDefender - Trojan:Win32/Skeeyah!MTB

### ISSUE THREAD

**Issue by pat-san** [brave/brave-browser#8549]
Description 
WD block tor-0.3.5.8-win32-brave-1 file and Tor network

Steps to Reproduce

   1. Download and install Release Channel v1.4.96, BraveBrowserStandaloneSetup.exe from github
   2. Open Brave
   3. Open Tor Private Window

Actual result:
Windows defender block file and Tor network: C:\Users\USER\AppData\Local\BraveSoftware\Brave-Browser\User Data\cpoalefficncklhjfpglfiplenlpccdb\1.0.9\tor-0.3.5.8-win32-brave-1

Expected result:
Navigate Tor network

Reproduces how often: 
?

Brave version (brave://version info)
Release Channel v1.4.96

Version/Channel Information:
Did not try others channels

## Miscellaneous Information:
Windows 10 - 1909
https://www.virustotal.com/gui/file/e6cca452474b22bb1a8c45ffe6a1f77ce517fed964d18cd69eb019f411aed6d4/detection

**Comment by eDave56** [comment]
Same behavior for Beta 1.5.108, Dev 1.6.58, and Nightly 1.7.44 in Windows 10 OS Version 1909 (Build 18363.657).
![image](https://user-images.githubusercontent.com/42411509/76004354-5bd6ba00-5ed7-11ea-8cfa-029417615f98.png)

**Comment by bsclifton** [comment]
cc: @jumde for triage

**Comment by T-Nawaz** [comment]
For now, is it ok to restore this file from windows defender?

**Comment by jumde** [comment]
We submitted this file for analysis. Here is the response from Windows Defender team:

```
Analyst comments:

We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
```

**Comment by jumde** [comment]
@pat-san @eDave56 @T-Nawaz - Please let me know if you're still seeing this with the updated v1.0.10. Thank you!

**Comment by pat-san** [comment]
LGTM
thank you jumde!

**Comment by T-Nawaz** [comment]
@jumde I am not facing any more problems after the update.

**Comment by jumde** [comment]
Awesome! 👍

**Comment by eDave56** [comment]
> @pat-san @eDave56 @T-Nawaz - Please let me know if you're still seeing this with the updated v1.0.10. Thank you!

Seems to be working so far with Signatures and Tor component updates.

**Comment by Sarafian** [comment]
FYI, `Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)` has the same problem as well.

**Comment by jumde** [comment]
Hi @Sarafian, Can you navigate to `brave://components/`  and check if you are using `tor client` 1.0.11?

**Comment by Sarafian** [comment]
> Hi @Sarafian, Can you navigate to `brave://components/` and check if you are using `tor client` 1.0.11?

Yes @jumde 

> Brave Tor Client Updater (Windows) - Version: 1.0.11
> Status - Up-to-date

Anyhow, the issue got resolved after a restart of the Windows 10 operating system.

For the history, I'll put the version here and I'll mention that on the slow inner ring.

> Version 2004 (OS Build 19041.208)

**Comment by VictorTagayun** [comment]
`c:\Program Files\Windows Defender>MpCmdRun.exe -removedefinitions -dynamicsignatures

Service Version: 4.18.2004.6
Engine Version: 1.1.17100.2
AntiSpyware Signature Version: 1.317.65.0
AntiVirus Signature Version: 1.317.65.0

Starting Dynamic Signature removal.Failed! Error 0x80070005

Service Version: 4.18.2004.6
Engine Version: 1.1.17100.2
AntiSpyware Signature Version: 1.317.65.0
AntiVirus Signature Version: 1.317.65.0
CmdTool: Failed with hr = 0x80070005. Check C:\Users\Victor\AppData\Local\Temp\MpCmdRun.log for more information

c:\Program Files\Windows Defender>MpCmdRun.exe -SignatureUpdate
Signature update started . . .
ERROR: Signature Update failed with hr=8024001D
CmdTool: Failed with hr = 0x8024001D. Check C:\Users\Victor\AppData\Local\Temp\MpCmdRun.log for more information

c:\Program Files\Windows Defender>`

**Comment by VictorTagayun** [comment]
-------------------------------------------------------------------------------------
MpCmdRun: Command Line: MpCmdRun.exe  -removedefinitions -dynamicsignatures
 Start Time: ‎Thu ‎May ‎28 ‎2020 08:59:06

MpEnsureProcessMitigationPolicy: hr = 0x1
MpCmdRun: End Time: ‎Thu ‎May ‎28 ‎2020 08:59:06
-------------------------------------------------------------------------------------


-------------------------------------------------------------------------------------
MpCmdRun: Command Line: MpCmdRun.exe  -removedefinitions -dynamicsignatures
 Start Time: ‎Thu ‎May ‎28 ‎2020 08:59:43

MpEnsureProcessMitigationPolicy: hr = 0x1
Start: MpRemoveDefinitions(0)
ERROR: MpRollbackSignature failed with hr=80070005
MpCmdRun: End Time: ‎Thu ‎May ‎28 ‎2020 08:59:43
-------------------------------------------------------------------------------------


-------------------------------------------------------------------------------------
MpCmdRun: Command Line: MpCmdRun.exe  -SignatureUpdate
 Start Time: ‎Thu ‎May ‎28 ‎2020 09:00:08

MpEnsureProcessMitigationPolicy: hr = 0x1
Start: MpSignatureUpdate()
Calling MpUpdateStartEx with option 0x1
Update started 
Search Started (MU/WU update) (Path: https://fe2cr.update.microsoft.com/v6/)...
Time Info - ‎Thu ‎May ‎28 ‎2020 09:00:56 Search Completed 
Update failed with hr: 0x8024001d
Update failed with hr: 0x8024001d
Update failed with hr: 0x8024001d
Update completed with hr: 0x8024001d
ERROR: Signature Update failed with hr=8024001D
MpCmdRun: End Time: ‎Thu ‎May ‎28 ‎2020 09:00:56
-------------------------------------------------------------------------------------


-------------------------------------------------------------------------------------
MpCmdRun: Command Line: MpCmdRun.exe  -removedefinitions -dynamicsignatures
 Start Time: ‎Thu ‎May ‎28 ‎2020 09:02:35

MpEnsureProcessMitigationPolicy: hr = 0x1
Start: MpRemoveDefinitions(0)
ERROR: MpRollbackSignature failed with hr=80070005
MpCmdRun: End Time: ‎Thu ‎May ‎28 ‎2020 09:02:35
-------------------------------------------------------------------------------------

**Comment by VictorTagayun** [comment]
`-------------------------------------------------------------------------------------
MpCmdRun: Command Line: MpCmdRun.exe  -removedefinitions -dynamicsignatures
 Start Time: ‎Thu ‎May ‎28 ‎2020 08:59:06

MpEnsureProcessMitigationPolicy: hr = 0x1
MpCmdRun: End Time: ‎Thu ‎May ‎28 ‎2020 08:59:06
-------------------------------------------------------------------------------------


-------------------------------------------------------------------------------------
MpCmdRun: Command Line: MpCmdRun.exe  -removedefinitions -dynamicsignatures
 Start Time: ‎Thu ‎May ‎28 ‎2020 08:59:43

MpEnsureProcessMitigationPolicy: hr = 0x1
Start: MpRemoveDefinitions(0)
ERROR: MpRollbackSignature failed with hr=80070005
MpCmdRun: End Time: ‎Thu ‎May ‎28 ‎2020 08:59:43
-------------------------------------------------------------------------------------


-------------------------------------------------------------------------------------
MpCmdRun: Command Line: MpCmdRun.exe  -SignatureUpdate
 Start Time: ‎Thu ‎May ‎28 ‎2020 09:00:08

MpEnsureProcessMitigationPolicy: hr = 0x1
Start: MpSignatureUpdate()
Calling MpUpdateStartEx with option 0x1
Update started 
Search Started (MU/WU update) (Path: https://fe2cr.update.microsoft.com/v6/)...
Time Info - ‎Thu ‎May ‎28 ‎2020 09:00:56 Search Completed 
Update failed with hr: 0x8024001d
Update failed with hr: 0x8024001d
Update failed with hr: 0x8024001d
Update completed with hr: 0x8024001d
ERROR: Signature Update failed with hr=8024001D
MpCmdRun: End Time: ‎Thu ‎May ‎28 ‎2020 09:00:56
-------------------------------------------------------------------------------------


-------------------------------------------------------------------------------------
MpCmdRun: Command Line: MpCmdRun.exe  -removedefinitions -dynamicsignatures
 Start Time: ‎Thu ‎May ‎28 ‎2020 09:02:35

MpEnsureProcessMitigationPolicy: hr = 0x1
Start: MpRemoveDefinitions(0)
ERROR: MpRollbackSignature failed with hr=80070005
MpCmdRun: End Time: ‎Thu ‎May ‎28 ‎2020 09:02:35
-------------------------------------------------------------------------------------`
