### ISSUE TITLE
WebTorrent support of .torrent links

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#855]
Links like https://webtorrent.io/torrents/big-buck-bunny.torrent should be handled by webtorrent component extension.

**Comment by bbondy** [comment]
Moving to backlog, but please move back if a fix is supplied.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7
