### ISSUE TITLE
preserve "Show Sponsored Images" off setting when "Show Background Image" is toggled on

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#8552]
## Description 
On the New Tab Page, when going to dashboard settings and disabling "Show Sponsored Images" and "Show Background Image", "Show Sponsored Images" will get reenabled when selecting "Show Background Image". 

Only "Show Background Image" should be toggled on while "Show Sponsored Images" should continue to be toggled off.

## Steps to Reproduce

   1. Go to brave://newtab -> and select dashboard setting
   2. Toggle OFF both "Show Background Image" and "Show Sponsored Images"
   3. Toggle ON "Show Background Image".
   4. Notice that "Show Sponsored Images" is also toggled ON. This pref should stay off.

![Screen Shot 2020-03-05 at 9 57 00 AM](https://user-images.githubusercontent.com/5951041/76010414-b10acf80-5ec7-11ea-97e2-6e59231841ff.png)

**Comment by rebron** [comment]
cc: @petemill

**Comment by GeetaSarvadnya** [comment]
Verification passed on

Brave | 1.7.67 Chromium: 80.0.3987.149 (Official Build) beta (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/4875
- Encountered https://github.com/brave/brave-browser/issues/8057
![image](https://user-images.githubusercontent.com/38657976/77287867-97a5b800-6cfc-11ea-9e03-5ba56e23d971.png)
