### ISSUE TITLE
[Android] CRLSets should be enabled by default

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#8553]
## Description 
CRLSets protects against revoked certificates. This component is not installed by default on android-core

## Steps to reproduce 

   1. Navigate to brave://components, the version is 0.0.0.0
   2. Navigate to https://revoked.badssl.com/

## Actual result 
No certificate error

## Expected result
Certificate Error

## Issue reproduces how often 
Easily

## Issue happens on 
   - Current Play Store version?
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): arm
   - Device (Phone, Tablet, Phablet): Pixel 2
   - Android version: 10
   
## Brave version
1.5.105

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
This has been fixed at some point
