### ISSUE TITLE
[Android] Block Audio Context Fingerprinting

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#8555]
## Description 
From: https://github.com/brave/browser-android-tabs/issues/856

## Steps to reproduce 
1. Navigate to https://audiofingerprint.openwpm.com
2. Enable Fingerprinting Protection in Brave Shields
3. Refresh

## Actual result 
Allowed

## Expected result
Blocked

## Issue reproduces how often 
Easily

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): arm
   - Device (Phone, Tablet, Phablet): Pixel 2XL
   - Android version: 10
   
## Brave version
1.5.105

**Comment by pes10k** [comment]
addressed by https://github.com/brave/brave-browser/issues/9187
