### ISSUE TITLE
Top Level Document Blocking

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#8559]
**Problem**
uBlock Origin, Brave’s current competitor for the best blocking tool, allows filter list authors to block the top-level, first-party request.  This is useful when a page is overall harmful, but doesn’t fit SafeBrowsing’s threat model.  It’s also useful as a (not perfect, but effective) defense against phishing, bounce tracking, etc.  Similar to browser UI for cert errors, uBlock Origin allows users to “click-through” to access the blocked page.

Brave currently does not have this capability.  Brave should implement this capability.

**Proposal**
Safe-Browsing Style Interstitial 

- Add capability to adblock-rust to know about top level requests (distinct from other request types) and to reason about $document and ~document narrowing cases.
- Use existing safe-browsing interstitial to create an inert (no storage, no network request, no origin) page that allows “yes I really want to see this page” click through.  This could leverage existing chromium infrastructure.
- Create new interstitial page with Brave branding.
- Have options for going back, continuing, and "dont ask again"

## Designs
This is a full-screen HTML page and should use our web UI.

Desktop:
![image](https://user-images.githubusercontent.com/2388823/111541331-90599480-872d-11eb-9e89-8604a6e366b6.png)

Mobile:
![image](https://user-images.githubusercontent.com/2388823/111541394-abc49f80-872d-11eb-848b-f65e5d717e28.png)

## Assets
Figma: https://www.figma.com/file/aJu3WGDztEWNZgwQTD9yx2/?node-id=0%3A1

**Comment by karenkliu** [comment]
Designs and assets added!

**Comment by antonok-edm** [comment]
@pes10k is this a duplicate of https://github.com/brave/brave-browser/issues/14134? Do the designs need to be updated in the browser to match this?

**Comment by pes10k** [comment]
Yes, lets close this in favor of #14134 .
