### ISSUE TITLE
Failed to send message on Messenger.com

### ISSUE THREAD

**Issue by chkk525** [brave/brave-browser#8564]
## Description 

- When I try to send a message on messenger.com, the input area turns into error display that rejects further input.

## Steps to Reproduce

   1.  Go to messenger.com
   2.  Try to send message to someone.
   3.  After sending several messages, the error happens 

## Actual result:

![image](https://user-images.githubusercontent.com/3054915/76056498-1ccd6500-5fba-11ea-8df7-45b896bf1b30.png)

```
ErrorUtils caught an error:

Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.. [Caught in: React reported an error]
```

## Expected result:
- Message should be sent

## Reproduces how often: 

- sometimes

## Brave version (brave://version info)

Brave | 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | macOS バージョン10.15.3（ビルド19D76）
JavaScript | V8 8.0.426.25
Flash | （無効）
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,AllowPopupsDuringPageUnload,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,LookalikeUrlNavigationSuggestionsUI,WebXR,VideoPlaybackQuality,WebXrGamepadModule --flag-switches-begin --load-media-router-component-extension=1 --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator,CastMediaRouteProvider,ReaderMode --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/chikaki/Library/Application Support/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@chkk525 Any more info on this one? Still happening, specific messages, characters e.g. inserting images, etc. Look intermittent.

**Comment by seanwu1105** [comment]
I face the same problem. The issue would not occur if I type in English. It seems that the error only shows up when the users use the input method having the "editing mode". For instance, the [ibus-chewing](https://github.com/ibus/ibus/wiki/ChewingUserGuide#editing-mode) input method in my case.

## Steps to Reproduce

Assume you are using Ubuntu 18.04 or later.

1. Install [ibus-chewing](http://chewing.im/)
1. Go to [Facebook home page](https://www.facebook.com/)
1. Open a new messenger dialog and ready to type
1. Change the input method to ibus-chewing
1. Type some Chinese character
1. After press <kbd>Enter</kbd> to commit the characters in pre-edit buffer, an error occurs and the messenger dialog disappears

> You can install the input method with `apt install ibus-chewing`. Then add the input method via the _Region & Language_ settings in Ubuntu. Remember to restart ibus (or logout and login again) to apply the change.

Interestingly, the issue will not occur when I use Google Chrome with the same steps.

## Actual Result: Brave Behavior

![Peek 2020-05-16 22-01](https://user-images.githubusercontent.com/14951000/82122017-8d1b1280-97c3-11ea-8f47-6edc370d8090.gif)

## Expected Result: Chrome Behavior

![Peek 2020-05-16 22-04](https://user-images.githubusercontent.com/14951000/82122034-a6bc5a00-97c3-11ea-9a80-5e7cd0c38876.gif)

## Reproduces How Often

Always in the messenger dialog on the [Facebook home page](https://www.facebook.com/). Rarely in the [messenger page](https://www.messenger.com).

## Error Log

```
kAzdY87BG4d.js?_nc_x=r-82SUzY6AZ:204 
Stop!
kAzdY87BG4d.js?_nc_x=r-82SUzY6AZ:204 
This is a browser feature intended for developers. If someone told you to copy-paste something here to enable a Facebook feature or "hack" someone's account, it is a scam and will give them access to your Facebook account.
kAzdY87BG4d.js?_nc_x=r-82SUzY6AZ:204 
See https://www.facebook.com/selfxss for more information.
kAzdY87BG4d.js?_nc_x=r-82SUzY6AZ:204 

The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
kAzdY87BG4d.js?_nc_x=r-82SUzY6AZ:57 ErrorUtils caught an error:

Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. [Caught in: ErrorBoundary base]

Subsequent errors won't be logged; see https://fburl.com/debugjs.
b @ kAzdY87BG4d.js?_nc_x=r-82SUzY6AZ:57
reportNormalizedError @ kAzdY87BG4d.js?_nc_x=r-82SUzY6AZ:62
d.componentDidCatch @ thNdQcfhGuYTkSJu5-a01pVHV_ZLgazPa-SBws5g0Cyqf1JHy0_ma73.js?_nc_x=r-82SUzY6AZ:258
Tj.h.componentDidCatch.e.callback @ thNdQcfhGuYTkSJu5-a01pVHV_ZLgazPa-SBws5g0Cyqf1JHy0_ma73.js?_nc_x=r-82SUzY6AZ:598
Fh @ thNdQcfhGuYTkSJu5-a01pVHV_ZLgazPa-SBws5g0Cyqf1JHy0_ma73.js?_nc_x=r-82SUzY6AZ:598
Xj @ thNdQcfhGuYTkSJu5-a01pVHV_ZLgazPa-SBws5g0Cyqf1JHy0_ma73.js?_nc_x=r-82SUzY6AZ:598
dl @ thNdQcfhGuYTkSJu5-a01pVHV_ZLgazPa-SBws5g0Cyqf1JHy0_ma73.js?_nc_x=r-82SUzY6AZ:598
g.unstable_runWithPriority @ kAzdY87BG4d.js?_nc_x=r-82SUzY6AZ:194
ih @ thNdQcfhGuYTkSJu5-a01pVHV_ZLgazPa-SBws5g0Cyqf1JHy0_ma73.js?_nc_x=r-82SUzY6AZ:598
cl @ thNdQcfhGuYTkSJu5-a01pVHV_ZLgazPa-SBws5g0Cyqf1JHy0_ma73.js?_nc_x=r-82SUzY6AZ:598
Lk @ thNdQcfhGuYTkSJu5-a01pVHV_ZLgazPa-SBws5g0Cyqf1JHy0_ma73.js?_nc_x=r-82SUzY6AZ:598
(anonymous) @ thNdQcfhGuYTkSJu5-a01pVHV_ZLgazPa-SBws5g0Cyqf1JHy0_ma73.js?_nc_x=r-82SUzY6AZ:598
g.unstable_runWithPriority @ kAzdY87BG4d.js?_nc_x=r-82SUzY6AZ:194
ih @ thNdQcfhGuYTkSJu5-a01pVHV_ZLgazPa-SBws5g0Cyqf1JHy0_ma73.js?_nc_x=r-82SUzY6AZ:598
mh @ thNdQcfhGuYTkSJu5-a01pVHV_ZLgazPa-SBws5g0Cyqf1JHy0_ma73.js?_nc_x=r-82SUzY6AZ:598
lh @ thNdQcfhGuYTkSJu5-a01pVHV_ZLgazPa-SBws5g0Cyqf1JHy0_ma73.js?_nc_x=r-82SUzY6AZ:598
Vd @ thNdQcfhGuYTkSJu5-a01pVHV_ZLgazPa-SBws5g0Cyqf1JHy0_ma73.js?_nc_x=r-82SUzY6AZ:598
de @ thNdQcfhGuYTkSJu5-a01pVHV_ZLgazPa-SBws5g0Cyqf1JHy0_ma73.js?_nc_x=r-82SUzY6AZ:598
ye @ thNdQcfhGuYTkSJu5-a01pVHV_ZLgazPa-SBws5g0Cyqf1JHy0_ma73.js?_nc_x=r-82SUzY6AZ:598
applyWithGuard @ kAzdY87BG4d.js?_nc_x=r-82SUzY6AZ:63
c @ kAzdY87BG4d.js?_nc_x=r-82SUzY6AZ:63
applyWithGuard @ kAzdY87BG4d.js?_nc_x=r-82SUzY6AZ:63
c.fire @ ZizpPLqJJnfJXWk-gL_J7F2AAVGEUjCGl5u9AucvaxMslN8r8fJ_hSOiUVPNjS7Wwrv4fd9i6LW79LDauoSvdNYUhEx4zbX7FaLBT0BzmnI_tavu0Qagj2vURygaKRsIhrpdDx9YukWixM44y2l6qaTPdsTAhVqjXgQiPY04fHg7MjDWGSR_i11CcJPxaGXwAsJnMnXa28jsl3P56im7l8doLm0UCIeETrPlzWSzXS10trxQMXYBkWOSi6cZlSqQnkVIsWOHCaNp-f6yLiwHjif-4Pd6A4P3vd0QDArDkpJGy4C4yS8rZ3LDLnaqnY4EnjSHIap-YA.js?_nc_x=r-82SUzY6AZ:229
(anonymous) @ ZizpPLqJJnfJXWk-gL_J7F2AAVGEUjCGl5u9AucvaxMslN8r8fJ_hSOiUVPNjS7Wwrv4fd9i6LW79LDauoSvdNYUhEx4zbX7FaLBT0BzmnI_tavu0Qagj2vURygaKRsIhrpdDx9YukWixM44y2l6qaTPdsTAhVqjXgQiPY04fHg7MjDWGSR_i11CcJPxaGXwAsJnMnXa28jsl3P56im7l8doLm0UCIeETrPlzWSzXS10trxQMXYBkWOSi6cZlSqQnkVIsWOHCaNp-f6yLiwHjif-4Pd6A4P3vd0QDArDkpJGy4C4yS8rZ3LDLnaqnY4EnjSHIap-YA.js?_nc_x=r-82SUzY6AZ:229
applyWithGuard @ kAzdY87BG4d.js?_nc_x=r-82SUzY6AZ:63
c @ kAzdY87BG4d.js?_nc_x=r-82SUzY6AZ:63
(anonymous) @ ZizpPLqJJnfJXWk-gL_J7F2AAVGEUjCGl5u9AucvaxMslN8r8fJ_hSOiUVPNjS7Wwrv4fd9i6LW79LDauoSvdNYUhEx4zbX7FaLBT0BzmnI_tavu0Qagj2vURygaKRsIhrpdDx9YukWixM44y2l6qaTPdsTAhVqjXgQiPY04fHg7MjDWGSR_i11CcJPxaGXwAsJnMnXa28jsl3P56im7l8doLm0UCIeETrPlzWSzXS10trxQMXYBkWOSi6cZlSqQnkVIsWOHCaNp-f6yLiwHjif-4Pd6A4P3vd0QDArDkpJGy4C4yS8rZ3LDLnaqnY4EnjSHIap-YA.js?_nc_x=r-82SUzY6AZ:187
```

## Version

### Brave Version

Brave | 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Linux
JavaScript | V8 8.1.307.32
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=AutoupgradeMixedContent,PassiveMixedContentWarning,PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator,MixedContentSiteSetting,DnsOverHttps --disable-features=AutofillServerCommunication,TextFragmentAnchor,LookalikeUrlNavigationSuggestionsUI,AllowPopupsDuringPageUnload,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,VideoPlaybackQuality --flag-switches-begin --load-media-router-component-extension=1 --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/seanwu/.config/BraveSoftware/Brave-Browser/Default

## Chrome Version

Google Chrome | 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Linux
JavaScript | V8 8.1.307.32
Flash | 32.0.0.371 /home/seanwu/.config/google-chrome/PepperFlash/32.0.0.371/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Command Line | /usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service

## Other Additional Information

* Does the issue resolve itself when disabling Brave Shields? No.
* Does the issue resolve itself when disabling Brave Rewards? No.
* Is the issue reproducible on the latest version of Chrome? No.

**Comment by ryanbr** [comment]
@chkk525 is this still an issue with the current Brave release?

**Comment by chkk525** [comment]
@ryanbr @rebron  Sorry I missed the prior comment here. I am no longer experiencing this.
