### ISSUE TITLE
No internet page: Chrome instead of Brave

### ISSUE THREAD

**Issue by wooque** [brave/brave-browser#8565]
## Description 
No internet page says Chrome instead of Brave

## Steps to Reproduce

   1. Try to open page without internet
   2. 
   3. 

## Actual result:

Says: chrome will let you now when the page is ready
![Screenshot_20200306-080550_Brave](https://user-images.githubusercontent.com/1936195/76066116-3a380a00-5f8d-11ea-9d06-9ccf36c6a7d3.png)

## Expected result:
Should say: Brave will let you know when the page is ready

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave 1.5.8 at Android 9

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? ?
- Can you reproduce this issue with the dev channel? ?
- Can you reproduce this issue with the nightly channel? ?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by kjozwiak** [comment]
Thanks for bug report @wooque 👍 Which version of Brave are you using? This is being addressed via https://github.com/brave/browser-android-tabs/issues/2595 in the current released version of Brave.

@SergeyZhukovsky I believe this is also fixed in `android-core` as well?

**Comment by wooque** [comment]
I'm using 1.5.8, I see that's fixed and will be released in 1.5.9
