### ISSUE TITLE
Completely Disable all Notifications

### ISSUE THREAD

**Issue by Tectract** [brave/brave-browser#8566]
When I install an extension, I get a notification popup saying "such and such extension installed"

I don't want it. I don't want any popup notifications ever, about anything. Popups should have died in the 90's, they are bad design imho. All notifications should have the option to permanently be disabled, or even better, they should be disabled BY DEFAULT. 

So, how can I get rid of these annoying popups?

**Comment by rebron** [comment]
This one is an issue to file in Chromium bug system https://bugs.chromium.org/p/chromium/issues/list or with their feedback forum. 

We're not deviating from the chromium extension installation flows, especially when it's part of a confirmation where "such and such extension installed".
