### ISSUE TITLE
Don't allow gifs to autoplay

### ISSUE THREAD

**Issue by Tectract** [brave/brave-browser#8567]
Can we get an option to disable gifs from auto-playing? Web animations are soooooooo annoying.

**Comment by Tectract** [comment]
Ideally we could "block all animation and timers" by default and then have the option to whitelist sites where animation is allowed.

**Comment by rebron** [comment]
Closing. Please follow templates for writing new issues, otherwise community.brave.com for feedback or with help writing issues that are actionable.
