### ISSUE TITLE
Bandwidth savings predictions only report 0

### ISSUE THREAD

**Issue by AndriusA** [brave/brave-browser#8568]
## Description 

P3A reporting has been in nightly for a while but all stats are showing 0

## Steps to Reproduce

With normal usage histograms (brave://historams) should show non-0 numbers

## Actual result:

Histogram: Brave.Savings.BandwidthSavingsMB recorded 603 samples, mean = 0.0 (flags = 0x61)
0  ------------------------------------------------------------------------O (603 = 100.0%)
1  ... 

## Reproduces how often: 

No steps to reproduce

## Brave version (brave://version info)

1.7.28 Chromium: 80.0.3987.122 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the dev channel? no
- Can you reproduce this issue with the nightly channel? yes

**Comment by LaurenWags** [comment]
@bsclifton @AndriusA @rebron what milestone should this one be in? 1.7.x perhaps? if so and it needs manual QA can we get a test plan please? Thanks!  cc @kjozwiak

**Comment by bsclifton** [comment]
@LaurenWags added to 1.7 milestone 😄 Added `QA/No` and `release-notes/exclude` as this stat is now hidden 👍

**Comment by LaurenWags** [comment]
awesome, thanks @bsclifton 😄
