### ISSUE TITLE
Incorrect BAT Payouts

### ISSUE THREAD

**Issue by wavesurf432** [brave/brave-browser#8570]
## Description 
Hello, I just recieved my monthly payout from Brave Ads and I recieved about 13 more BAT than estimated pending rewards stated. I was expecting 15.8 BAT and recieved 29 BAT.

The same thing happened last month. I had about 10-15 BAT at the end of January and recieved 29 or so BAT. There was no mention of a grant under the details tab, but that's what I assumed it was.

## Steps to Reproduce

   1. Use Brave for a month
   2. Recieve BAT payout at the end of the month from ads
  

## Actual result:
Incorrect payout compared to expected amount in estimated pending rewards.

## Expected result:
Recieve stated amount of BAT in estimated pending rewards.

## Reproduces how often:
Been using Brave for 1 year; incorrect payout has only happened last two months.

## Brave version (brave://version info)

Brave | 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Linux

## Version/Channel Information:

Current public release.

## Screenshot:

I have a screenshot of Brave rewards but can't upload for some reason.

**Comment by NejcZdovc** [comment]
cc @jsecretan @tmancey

**Comment by wavesurf432** [comment]
Edit: The issue with BAT still remaining in estimated pending rewards is fixed. It reset after closing Brave.

**Comment by tmancey** [comment]
@wavesurf432 This is due to a bonus which you would have received from us, this is not an error. Thanks for using Brave

**Comment by wavesurf432** [comment]
> @wavesurf432 This is due to a bonus which you would have received from us, this is not an error. Thanks for using Brave

Thanks for the reply.

Are bonuses random, or do they have to do with browser usage over the month? Age of wallet e.t.c?

**Comment by mandar-brave** [comment]
@wavesurf432 there are two items here that in excess to your panel estimations.

a) Sponsored Image that do not estimate
b) A bonus of sorts

I can't go too much in to b) but loyalty to Brave and Brave Ads always pays! A will continue to grow and B will continue to go down.
