### ISSUE TITLE
Migrate uphold transactions to contribution table 

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#8571]
We currently for uphold transactions log things into reconcile json state. We should migrate it contribution table, so that we can track it appropriately

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.79 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4876
* Confirmed one time tip goes thru, is listed on Tips panel and in summary. Confirmed balance is reduced accordingly and tip is listed in Uphold transactions:
<img width="659" alt="Screen Shot 2020-03-31 at 11 35 00 AM" src="https://user-images.githubusercontent.com/28145373/78046048-afa4b980-7344-11ea-850e-d8bf9225ef09.png">
<img width="416" alt="Screen Shot 2020-03-31 at 11 39 05 AM" src="https://user-images.githubusercontent.com/28145373/78046073-b3d0d700-7344-11ea-95d3-663fff465342.png">
<img width="402" alt="Screen Shot 2020-03-31 at 11 39 12 AM" src="https://user-images.githubusercontent.com/28145373/78046077-b59a9a80-7344-11ea-9f76-3e2a34bf699a.png">
<img width="1167" alt="Screen Shot 2020-03-31 at 11 42 06 AM" src="https://user-images.githubusercontent.com/28145373/78046085-b7fcf480-7344-11ea-9cec-689cc9e0df78.png">
<img width="757" alt="Screen Shot 2020-03-31 at 11 40 08 AM" src="https://user-images.githubusercontent.com/28145373/78046106-bcc1a880-7344-11ea-9f08-4f3d91358126.png">

* Additionally, set up recurring monthly tips and sites for AC. Confirmed recurring tips and AC are contributed appropriately. They are listed in the summaries, on Uphold, and in the `publisher_info_db` in `contribution_info` table:
<img width="651" alt="Screen Shot 2020-03-31 at 11 38 38 AM" src="https://user-images.githubusercontent.com/28145373/78046272-f4305500-7344-11ea-87f5-ba81d95d4a0d.png">
<img width="645" alt="Screen Shot 2020-03-31 at 11 38 44 AM" src="https://user-images.githubusercontent.com/28145373/78046277-f5618200-7344-11ea-883c-8894b1d5bdd2.png">
<img width="409" alt="Screen Shot 2020-03-31 at 11 50 42 AM" src="https://user-images.githubusercontent.com/28145373/78047172-0d85d100-7346-11ea-97dc-2abb3ed8665a.png">
<img width="400" alt="Screen Shot 2020-03-31 at 11 50 50 AM" src="https://user-images.githubusercontent.com/28145373/78047182-0fe82b00-7346-11ea-9180-f7368a197c9f.png">
<img width="1175" alt="Screen Shot 2020-03-31 at 11 50 27 AM" src="https://user-images.githubusercontent.com/28145373/78047188-124a8500-7346-11ea-8c6e-4030ceda1bd8.png">
<img width="905" alt="Screen Shot 2020-03-31 at 11 53 39 AM" src="https://user-images.githubusercontent.com/28145373/78047388-46be4100-7346-11ea-9a78-748391fc9ddd.png">
