### ISSUE TITLE
GIVE US BACK THE MENU BAR

### ISSUE THREAD

**Issue by Tectract** [brave/brave-browser#8573]
You know that menu bar that is standard in all linux applications?

WE WANT IT BACK. Give us the menu bar back, even if just as an option! 

I use linux because I HATE mac design and user interface, and the lack of a menu bar is one major, major part of why I hate mac design.

**Comment by rebron** [comment]
Closing. There's https://community.brave.com/ for general feedback and an issue template and guidelines for issues. If you don't like macOS for it's design and UI, it's quite nice that you have Linux then.

**Comment by Tectract** [comment]
Why was this closed? Why is this not actionable? Why is the mac design philosophy running rampant in the Brave dev community?

**Comment by rebron** [comment]
@Tectract https://github.com/brave/brave-browser/wiki/Creating-an-issue

**Comment by Mountaingal** [comment]
There is a way to get a Menu Bar (or at least a reasonably functional version of it) added to the Brave Browser in Windows. Go to "Extensions" and search for "Proper Menubar", install it, RESTART Brave, and then the Menu Bar should appear BELOW the Bookmarks bar. You can customize the menu bar too (background, fonts, etc). It's not perfect, but better than nothing.
![BraveMenu](https://user-images.githubusercontent.com/12437861/104977963-d2d15000-59ce-11eb-969e-9e3c1c5ed6f7.jpg)

**Comment by skaendo** [comment]
This is the very reason that I don't use Brave. Using the chrome engine is great, not having functionality is a great loss. It's not like they can't do it, Vivaldi does it flawlessly. Unfortunately Vivaldi is becoming a bloated mess. I guess that the only option left is Goanna based Pale Moon.

@Mountaingal,  the "Proper Menubar" is not a "proper menubar". It only shows up on webpages, it's not a permanent functional menubar. It would have been great if it was.

Does anyone know the commit that the menubar was removed from Brave? Maybe a fork could happen?
