### ISSUE TITLE
Chrome can't handle large numbers of tabs properly

### ISSUE THREAD

**Issue by Tectract** [brave/brave-browser#8577]
Open a LOT of tabs. At some point, they just start going UNDER the new tab "plus" button, and the left-right scrolling thing that firefox has, is just not working anymore on Chrome. 

It's a HUGE bug, it limits you to only having around 40-50 tabs open and navigable, depending on your SCREEN WIDTH!

Can you guys fix this major Chrome deprecation in tab-handling?

**Comment by ylluminarious** [comment]
Absolutely agree. I was planning on moving from Firefox to Brave due to some deficiencies Mozilla keeps introducing, but this issue is making me regret the idea. I cannot stand Chrome's way of handling many tabs. I constantly operate with 100+ tabs open. I cannot work with Chrome's insane tab UI.

**Comment by bsclifton** [comment]
Thanks for the report, folks! We have an issue already tracking this. It was solved in the earlier versions of Brave, but we need to revisit after switching our UI to Chromium

I'll close the issue and here's the one you can follow / leave additional comments / +1
https://github.com/brave/brave-browser/issues/35
