### ISSUE TITLE
Allow us to MOVE the bookmarks button, and other buttons, in the top area

### ISSUE THREAD

**Issue by Tectract** [brave/brave-browser#8578]
I don't like having the bookmarks button to the left of the URL bar. I want it to the right, instead. 

Can we REGAIN the functionality to customize this top area, that the chrome devs TOOK AWAY from us?

**Comment by rebron** [comment]
Closing. @Tectract Thanks for the feedback, we do appreciate the passion. Please go to community.brave.com for future feedback of this type. There are issue templates and guidelines and we can't act on issues written in this form. I'm sorry the Chrome Devs took away the ability to move your buttons.

**Comment by Tectract** [comment]
oh man :'(

I keep hitting bookmark instead of home. Argh.
