### ISSUE TITLE
[Android] Remove menu button and url bar with rounded corners in transition animation

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#8581]
## Description 
For parity with tabs and nice looking remove menu button and url bar with rounded corners in transition animation, when switch between overview and main view.

## Steps to reproduce 

   1. Click icon with tabs count
   2. In transition between the views there are visible menu button and rounded google style url bar

![device-2020-03-06-162410](https://user-images.githubusercontent.com/30602739/76124379-86547000-5fc8-11ea-9154-059d9264cf1e.gif)

**Comment by srirambv** [comment]
- Verification passed on OnePlus 6T with Android 10 running 1.5.111 x64 stable build
![tab-transition](https://user-images.githubusercontent.com/17010094/76745538-0aaeac00-679c-11ea-94de-4e75163caaa5.gif)
