### ISSUE TITLE
[Android] Hide bookmark button in app menu footer when bottom toolbar is enabled

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#8583]
## Description 
When the bottom toolbar is enabled, the bookmark button in the app menu footer should not be shown.

ref browser-android-tabs issue: https://github.com/brave/browser-android-tabs/issues/1373

## Steps to reproduce 

   1. Open brave settings -> Appearance
   2. Make sure that "Enable bottom toolbar" switch is on
   3. Go back to the three-dot menu (app menu) at the bottom toolbar and observe the buttons shown in the footer

## Actual result 
Bookmark button is shown in the app menu footer regardless of the bottom toolbar is enabled or not.

## Expected result
Bookmark button in the app menu footer should not be shown when bottom toolbar is enabled.
![Screenshot_20200306-171704](https://user-images.githubusercontent.com/4730197/76133839-1a293a80-5fcf-11ea-9130-41479c55c3bb.png)

## Issue reproduces how often 
Always

## Issue happens on 
Android-core

## Device details
   - Install type (ARM, x86): all
   - Device (Phone, Tablet, Phablet): all
   - Android version: all

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.111 x64 stable build
- Verified when bottom toolbar is enabled there is no bookmark button in app menu
![image](https://user-images.githubusercontent.com/17010094/76738620-fca75e00-6790-11ea-9cf4-2eacdbbe10cb.png)
- Verified when bottom toolbar is disabled there is a bookmark button in app menu
![image](https://user-images.githubusercontent.com/17010094/76738653-0cbf3d80-6791-11ea-8921-83d4e4bb0da3.png)
