### ISSUE TITLE
[Android] Replace page info button with share button in app menu

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#8584]
## Description 
Replace page info button with share button in app menu.
Also we'll need to remove Share.. row in the app menu on phone and only show it on tablet.

ref tabs issue: https://github.com/brave/browser-android-tabs/issues/1718

## Actual result 
when bottom toolbar is enabled:
![Screenshot_20200306-182951](https://user-images.githubusercontent.com/4730197/76135110-f3700180-5fd8-11ea-8756-9bbd592854ff.png)

when bottom toolbar is disabled:
![Screenshot_20200306-183042](https://user-images.githubusercontent.com/4730197/76135112-f834b580-5fd8-11ea-80a7-91955e65aef0.png)

## Expected result
when bottom toolbar is enabled:
![Screenshot_20200306-183158](https://user-images.githubusercontent.com/4730197/76135126-084c9500-5fd9-11ea-8a3f-aa6e0385ffcf.png)

when bottom toolbar is disabled:
![Screenshot_20200306-183124](https://user-images.githubusercontent.com/4730197/76135124-0682d180-5fd9-11ea-90ac-89b6aff68043.png)

## Issue reproduces how often  
Always

**Comment by yrliou** [comment]
Test planed specified in https://github.com/brave/brave-core/pull/4878#issue-385093347

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.111 x64 build
- Verified no `Share...` option in app menu
![image](https://user-images.githubusercontent.com/17010094/76738355-7b4fcb80-6790-11ea-915a-1ebc0a5ad302.png)
- Verified Share button is shown both times when bottom toolbar is enabled and disabled
![image](https://user-images.githubusercontent.com/17010094/76738347-75f28100-6790-11ea-9f66-c9b3faa6c648.png)
- Verified `Share...` is not shown in landscape mode but only the share button is shown
![image](https://user-images.githubusercontent.com/17010094/76738327-6d9a4600-6790-11ea-8cd1-affa901df82b.png)
--------
Verification passed on Samsung Tab A with Android 9.0 running 1.5.111 x64 build
- Verified no `Share...` menu entry on chrome pages
![image](https://user-images.githubusercontent.com/17010094/76738410-96bad680-6790-11ea-8111-a4367f750c0c.png)
- Verified `Share...` menu option shows up only on visiting a web page
![image](https://user-images.githubusercontent.com/17010094/76738458-a803e300-6790-11ea-891b-98b4fa7a75cf.png)
