### ISSUE TITLE
[Android] Rewards page. Multiple promotions. Claiming one starts progress spinner spinning on the next promotion.

### ISSUE THREAD

**Issue by gdregalo** [brave/brave-browser#8586]
## Description 
Rewards page. Multiple promotions. Claiming one starts progress spinner spinning on the next promotion.

## Steps to reproduce 

   1.  Create a wallet and get multiple promotions on it.
   2.  Open rewards page and claim any but not last one in the list.
   3. Observe : promotion is received, wallet balance is updated. Spinner control starts spinning on the next promotion.

## Actual result 
Promotion is received, wallet balance is updated. Spinner control starts spinning on the next promotion.

## Expected result
After promotion claim is finished it has to open a windows with promotion summary and OK button (similar to UGP promotion).

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by SergeyZhukovsky** [comment]
moving it out from core release as tabs repo has a similar issue

**Comment by srirambv** [comment]
Moving to Android 1.7.x miletone as this is Android specific issue

**Comment by srirambv** [comment]
Blocked on #9524

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.7.102 x64 stable build
- Verified only once on the device, claiming one promotion doesn't start spinner on the others and doesn't claim them
