### ISSUE TITLE
[Android] Add missing landscape layout resources for site banner activity.

### ISSUE THREAD

**Issue by gdregalo** [brave/brave-browser#8587]
## Description 
Please  add missing landscape layout resources for site banner activity.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by gdregalo** [comment]
![Screenshot_20200304-181255](https://user-images.githubusercontent.com/37560650/76152040-25d93780-6089-11ea-91a2-f69db3620e99.png)

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9.0 running 1.5.111 x64 stable build
- Verified on landscape more the site banner is shown correctly 
![image](https://user-images.githubusercontent.com/17010094/76737667-370ffb80-678f-11ea-81e8-29b08907c96d.png)

--------
Verification passed on OnePlus 6T with Android 10 running 1.5.111 x64 stable build
- Verified on landscape more the site banner is shown correctly 
![image](https://user-images.githubusercontent.com/17010094/76737675-3bd4af80-678f-11ea-9b5d-09b9e25e96f8.png)
