### ISSUE TITLE
files missing

### ISSUE THREAD

**Issue by pipiscrew** [brave/brave-browser#8591]
**Release Channel v1.4.96**
 **brave-v1.4.96-win32-ia32.zip**

hi all, 

today tried, the following files are missing :
> chrome.dll
> chrome_watcher.dll
> d3dcompiler_47.dll
> eventlog_provider.dll
> libegl.dll
> libglesv2.dll

the browser is not able to start.

**Comment by rebron** [comment]
@pipiscrew Our latest is 1.8.86. https://github.com/brave/brave-browser/releases/tag/v1.8.86
Can you take a look there and reopen if this continues to be an issue.
