### ISSUE TITLE
[Android] New notification channel for background ads is not created after app is updated

### ISSUE THREAD

**Issue by gdregalo** [brave/brave-browser#8594]
## Description 
New notification channel for background ads is not created after app update.
Fix: please increment ChannelDefinitions.CHANNELS_VERSION. 

## Steps to reproduce 

   1. Install brave version which has only one notification channel `Brave ads`.
   2. Update the app with the latest version.
   3. Observe: the new notification channel for background ads is not created.

## Actual result 
the new notification channel for background ads is not created.

## Expected result
2 channels should be created after the app is updated:
-Brave ads;
-Brave ads sent when browser is in the background

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
@srirambv I moved this to the Android 1.5.x milestone, please adjust if not correct.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.111 x64 stable build
- On 1.5.1 with single notification channel 
![image](https://user-images.githubusercontent.com/17010094/76747825-c6bda600-679f-11ea-9d9c-6a37508ebfe9.png)
- After upgrade to 1.5.111 x64 build with new notification channel
![image](https://user-images.githubusercontent.com/17010094/76747838-cd4c1d80-679f-11ea-86f5-d8a3372d89d6.png)
-------
Verification passed on OnePlus 6T with Android 10 running 1.5.111 x64 stable build
- On 1.5.1 with single notification channel 
![image](https://user-images.githubusercontent.com/17010094/76748049-1ef4a800-67a0-11ea-989c-098484e60522.png)
- After upgrade to 1.5.111 x64 build with new notification channel
![image](https://user-images.githubusercontent.com/17010094/76748058-25831f80-67a0-11ea-83b6-50aa07b2ec11.png)
