### ISSUE TITLE
[Android] SafetyNet is not checked on wallet creation

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#8595]
## Description 
SafetyNet is not checked on wallet creation

## Steps to reproduce 
I was able to reproduce it on x86 debug build, where rewards are enabled. For QA we will need to find the arm device where SafetyNet fails.

**Comment by samartnik** [comment]
This should be fixed on server side for `GET /v5/grants`
@evq @maikelmclauflin please close the issue, once it is done.

**Comment by samartnik** [comment]
As per discussion with @evq we decided to move this particular check on client side.

**Comment by samartnik** [comment]
Link to discussion https://bravesoftware.slack.com/archives/C0816QH3R/p1583772074095600

**Comment by fmarier** [comment]
I tested [v1.5.117](https://github.com/brave/brave-browser/releases/tag/v1.5.117) of `BraveModernarm.apk` on an old phone running Cyanogenmod 5.1.1 and I was denied Brave Rewards:
![Screenshot_2020-03-30-14-04-36](https://user-images.githubusercontent.com/167821/77962829-2ed8b580-7291-11ea-8975-23f39e6c011b.png)
![Screenshot_2020-03-30-14-04-57](https://user-images.githubusercontent.com/167821/77962831-2f714c00-7291-11ea-8b08-07c281005844.png)

**Comment by kjozwiak** [comment]
Thanks for running through the issue @fmarier 👍 Adding the `QA Pass - Android ARM`. This is pretty much the best we can do in terms of verifications as QA doesn't have any devices that's failing the SafetyNet check.
