### ISSUE TITLE
Nessus Professional Issue

### ISSUE THREAD

**Issue by waterweasel4** [brave/brave-browser#8597]
# Description 
Nessus Professional does not work with Brave (using latest public version or the nightly version)

## Steps to Reproduce
1. Install Nessus Professional.
2. Once installed and started, bring up https://localhost:8834/#/ 
3. Brave warns you about the SSL but you cannot proceed past it accepting the risk.

## Actual result:
See screenshot. 
<img width="772" alt="Screen Shot 2020-03-09 at 2 56 16 PM" src="https://user-images.githubusercontent.com/8419327/76247577-23f0af00-6216-11ea-869d-3d43c7d3aae7.png">

## Expected result:
Expected to see the page like I can in Firefox and to be able to bypass the SSL warning if needed.

## Reproduces how often: 
Easily reproducible 

## Brave version (brave://version info)
Version 1.7.50 Chromium: 80.0.3987.132 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Unknown
- Can you reproduce this issue with the dev channel? Unknown
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  Yes

**Comment by rmathus4** [comment]
As a workaround, you can change this in brave://flags and you can see the website. 

But since it's experimental, I'd rather not allow that and run into issues.  

<img width="728" alt="Screen Shot 2020-03-09 at 2 57 59 PM" src="https://user-images.githubusercontent.com/8419327/76247779-79c55700-6216-11ea-95a8-0017ee2f87ca.png">
