### ISSUE TITLE
chrome://welcome-win10 is displayed on Windows

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#86]

**Comment by GeetaSarvadnya** [comment]
This page is removed chrome://welcome. Verified on:

Brave | 0.54.2 Chromium: 69.0.3497.42 (Official Build) dev (64-bit)
-- | --
Revision | 9c4613c66dfeb2b76ef6dd4b15884c15db3b4969-refs/branch-heads/3497@{#655}
OS | Windows
JavaScript | V8 6.9.427.14
Flash | 30.0.0.154
