### ISSUE TITLE
Bad file download from RPM repo

### ISSUE THREAD

**Issue by alethiophile** [brave/brave-browser#8601]
## Description 
Trying to install Brave using the instructions for Fedora results in a bad RPM being downloaded that fails verification.

## Steps to Reproduce

   1. Have a Brave install that is far out-of-date. (I haven't tried from a fresh machine.)
   2. Run `dnf upgrade brave-browser`

## Actual result:

Upgrade fails with NOKEY. The file downloaded has sha256sum 146a10fa8b5ffbee9a9a5dddfff8dc4c58629704a49ae9b71b8089a1bea01c5e, and differs from that downloaded via github for the same version (67dee6a71b9ef397d23146f74e3d6e3434bc9830e6b4387bf51cfd05a22bd3c5). The file is brave-browser-1.4.96-1.x86_64.rpm.

## Expected result:
Normal install.

## Reproduces how often: 

The version manually downloaded from Github installs fine using `dnf install brave-browser-1.4.96-1.x86_64.rpm`. After doing this, `dnf reinstall brave-browser` downloads the same package, but this time succeeds verification. Thus I now can't reproduce it (but the same thing happened on two different machines with far-out-of-date brave installations).

## Brave version (brave://version info)

1.4.96-1

## Version/Channel Information:

Release, haven't tried any others

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @mbacchi Can you take a look at this one when you get a chance?

**Comment by mbacchi** [comment]
The `NOKEY` error indicates you don't have the GPG key in your RPM database that was used to sign the RPM package. We changed our GPG keys around this timeframe. Please try this command:

```
sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
```

Then reinstall Brave using [these instructions](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#fedora-28-centos-rhel-8).
