### ISSUE TITLE
muted websites are saved on private navigation session

### ISSUE THREAD

**Issue by starbassma** [brave/brave-browser#8602]
Brave remember sounds settings inside private windows (mute/unmute)

# Version 
Version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
# Steps to Reproduce
   1. CTRL+SHIFT+N (open new private navigation window)
   2. CTRL+T (x2) open two tabs 
   3. inside one of the tabs visit whatever website your want and mute it (right click on the tab and "mute website")
  4. close the muted tab (CTRL+W)
  5. open the same website again inside the other tab
6. right click on that tab (you will see "Unmute site" instead of "Mute site") this is definitely not the expected behavior, this kind of information shouldn't be saved/revealed.
Regards,

**Comment by bsclifton** [comment]
hi @starbassma 

I tried a few scenarios and I'm not sure there is a problem. Here's what I did:
- I opened a private window and then also had a regular window
- Let's say I pull up a YouTube video in both regular window AND private window
- I can right click tab on regular window and pick `Mute Site`
- This will mute BOTH regular + private windows which have YouTube open
- If I quit and relaunch, the setting is saved. I need to right click tab and pick `Unmute Site` to hear again

However, the changes made in a private window do not work like that:
- reset the mute state back to default
- open YouTube video in both regular + private window
- right click and pick `Mute Site` on private window
- regular window is not affected
- If I quit and relaunch, the setting is not saved

Can you confirm this is the case for you too? There is no privacy leak happening. The private windows will inherit any site settings from your default profile, which is how the private tab can be muted when you muted regular tab

Hope this makes sense- thanks!
