### ISSUE TITLE
Support new promo code for existing install

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#8603]
For now, installing new referrer is not supported if current machine already has brave install.

We should support this for custom homepage.
If a user already uses brave and that user installs super referrer again, that user should see custom homepage.

**Comment by simonhong** [comment]
I'm trying to fix this but I'm curious we can start new referrals over existing referral install.
@aekeus @emerick WDYT?

**Comment by emerick** [comment]
@simonhong The approach you're taking seems valid, I think the main concern would be how the backend reacts to seeing a different referral code from the same user. Is that something we already handle @aekeus or would it require changes?

**Comment by simonhong** [comment]
cc @keur

**Comment by keur** [comment]
This shouldn't require huge changes on our side, but Aubrey is on PTO. Can this wait until next week?

**Comment by simonhong** [comment]
@keur I think it's fine. @anthonypkeane WDYT?

**Comment by simonhong** [comment]
Closed because super referral install is only valid for fresh user that doesn't have ref code.(no existing user data)

**Comment by kjozwiak** [comment]
Removing milestone as this has been closed and isn't being implemented as per the Slack conversation earlier on Friday.
