### ISSUE TITLE
Delete icon in cookie settings does nothing

### ISSUE THREAD

**Issue by keeganwitt** [brave/brave-browser#8604]
## Description 
Delete button on brave://settings/content/cookies (under "allow", which shows sites where the shield has been turned off), clicking the trash icon appears to do nothing.

## Steps to Reproduce
   1. Go to a site, bring the shield down for that site.
   1. Go to brave://settings/content/cookies
   1. Click the trash icon next to the allowed site.

## Actual result:
Nothing happens.

## Expected result:
Shields are brought back up for that site.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
1.6.59 

## Version/Channel Information:
- Can you reproduce this issue with the current release?  Unknown
- Can you reproduce this issue with the beta channel?  Unknown
- Can you reproduce this issue with the dev channel?  Yes
- Can you reproduce this issue with the nightly channel?  Unknown

If this is an incompletely delivered feature, feel free to let me know and close this issue.

**Comment by danielegrattarola** [comment]
I have the same issue: 

Version 1.7.92 
Chromium: 80.0.3987.163 (Official Build) (64-bit)
Linux Ubuntu 16.04.02

There are a bunch of whitelisted websites that I visited a long time ago that don't get cleared when I manually delete cookies.

**Comment by rebron** [comment]
cc: @tomlowenthal Can you take a look at this one? Toggling anything in here `brave://settings/content/cookies` shouldn't reset shields settings status up or down.

**Comment by tomlowenthal** [comment]
@rebron Not sure I follow. The issue definitely deems valid: the delete button next to those items doesn't work. Why shouldn't it?

**Comment by rebron** [comment]
@tomlowenthal You're right, I misread the issue. Expected result is site is deleted from the allowed list.

**Comment by dentistformyeye** [comment]
Also happens with the Block list. Manually created entries in the cookie settings have a menu with a Remove option that works normally, so the Clear On Exit list shouldn't be affected.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.42.69 Chromium: 103.0.5060.114 (Official Build) beta (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 12.4 (Build 21F79)
```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.42.78 Chromium: 103.0.5060.134 (Official Build) beta (64-bit)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | Ubuntu 18.04 LTS


Case 1: Set to `Allow all cookies` in `brave://settings/cookies` - PASSED
  <Details>
  
  1. Install `1.42.x`
  2. Launch Brave
  3. Open `brave://settings/cookies`
  4. Select `Allow all cookies`
  5. Visit https://www.whatismybrowser.com
  6. Click Shields icon>>Advanced Controls
  7. Verified `Allow all cookies` is selected
  8. Open dev tools in the site to verify all cookies shown
  9. Visit `brave://settings/shields` and verify `Disabled` selected - settings matched to `brave://settings/cookies` page
 10. Open `brave://settings/siteData` and verify all cookies shown

![image](https://user-images.githubusercontent.com/34715963/181516835-58d87dc5-7ac2-40a5-a09f-18d576c6956d.png)
![image](https://user-images.githubusercontent.com/34715963/181517254-e1ec3e85-6d5d-4865-9cff-b8d622d78193.png)
![image](https://user-images.githubusercontent.com/34715963/181517372-403e168f-20d8-4c97-bfc3-d154a9a61006.png)
![image](https://user-images.githubusercontent.com/34715963/181517543-c9795e25-db41-484b-87fe-42cbdca6264c.png)
![image](https://user-images.githubusercontent.com/34715963/181517681-ea0f3288-0fe0-486d-b1f1-f7c50ffeae44.png)



</details>

Case 2: Set to `Block Third-party cookies` in `brave://settings/cookies` - PASSED
<Details>

  1. Continue from case 1 and clear all cookies or do a new profile prior to doing the below steps
  2. Select `Block Third-party cookies` in `brave://settings/cookies`
  3. Visit https://www.whatismybrowser.com
  4. Verified `Block cross-site cookies` is selected in the Shields panel
  5. Visit `brave://settings/shields` and verify `Only cross-site` is selected 
  6. Load https://www.whatismybrowser.com
  7. Verified no `3rd party cookies` shown in the dev tools
 8. Verified no '3rd party cookies` shown in brave://settings/siteData 

![image](https://user-images.githubusercontent.com/34715963/181518329-ae4fe299-73d1-462c-8264-583e13dde912.png)
![image](https://user-images.githubusercontent.com/34715963/181518548-62914df3-92db-427f-95e6-780542bbf533.png)
![image](https://user-images.githubusercontent.com/34715963/181518648-f2d8f013-8671-4abb-a7c7-b95956021be5.png)
![image](https://user-images.githubusercontent.com/34715963/181518720-c22aa1a7-ac63-4c3a-8fad-103cc2709d54.png)
![image](https://user-images.githubusercontent.com/34715963/181518788-7ca2ad96-aae4-4411-8324-760eee3a0fa4.png)


</details>

Case 3: Set to `Block all cookies` in `brave://settings/cookies` - PASSED
<Details>

  1. Continue from Case 2 and clear all cookies or do a new profile prior to doing the below steps
  2. Select `Block all cookies` in brave://settings/cookies
  3. Visit https://www.whatismybrowser.com
  4. Click Shields icon>>Advanced Controls
  5. Verified `Block all cookies` is selected
  6. Visit `brave://settings/shields` and verify `All` is selected
  7. Return to https://www.whatismybrowser.com
  8. Clear cookies in dev tools and reload the site
  9. Verified no cookies shown in the dev tools
  10. Verified no cookies shown in brave://settings/siteData for the site

![image](https://user-images.githubusercontent.com/34715963/181519100-91298877-b666-49f4-bb01-96c6377d8a81.png)
![image](https://user-images.githubusercontent.com/34715963/181519313-07c8277c-173d-4c41-8808-de79a8b6aa3a.png)
![image](https://user-images.githubusercontent.com/34715963/181519486-8a5623ad-31db-46ec-879d-85dd2a74b347.png)
![image](https://user-images.githubusercontent.com/34715963/181519544-0eff5582-29e3-4ed9-adba-080dbbd10a1c.png)
![image](https://user-images.githubusercontent.com/34715963/181519242-e96cbc7c-4c18-4afe-8ae1-829d0767328b.png)


</details>

Case 4: Set to `Allow all cookies` then Shields `DOWN` - PASSED
  <Details>
  
  1. New profile
  2. Launch Brave
  3. Open `brave://settings/cookies` and select `Allow all cookies`
  4. Visit www.whatismybrowser.com site
  5. Click Shields icon and turn shields `DOWN`
  6. Visit `brave://settings/shields` and verified `Disabled` is selected to match to `brave://settings/cookies`
  7. Return to www.whatismybrowser.com to verify all cookies shown in the dev tools
  8. Verified `www.whatismybrowser.com` site entry is shown in the `Sites that can always use cookies` in `brave://settings/cookies`
  9. Verified www.whatismybrowser.com entry cannot be removed by clicking the trash icon - see https://github.com/brave/brave-browser/issues/24106

![image](https://user-images.githubusercontent.com/34715963/181520496-451893f4-ff50-4f57-a7e6-75157d29b6e3.png)
![image](https://user-images.githubusercontent.com/34715963/181521023-7f81aee0-76f1-46b4-b6bf-6df10f3ce254.png)
![image](https://user-images.githubusercontent.com/34715963/181521166-34f6385c-cc06-49ff-a558-d6c0c61ece18.png)
![image](https://user-images.githubusercontent.com/34715963/181521798-784a3b1e-64fd-49fa-89a9-f1e291626d7c.png)


</details>

Case 5: Set to `Block all cookies` in the `Shields` panel  - PASSED
<Details>

1. Continue from Case 4:
    - Keep `Allow all cookies` in `brave://settings/cookies`
    - `www.whatismybrowser.com` site entry is still shown in the `Sites that can always use cookies` in `brave://settings/cookies`
2. Visit www.whatismybrowser.com site
    - Click Shields icon and toggle `ON` for shields
    - Select `Block all cookies` in the Shields panel
3. Visit `brave://settings/shields` and verify `Disabled` selected
4. Return to www.whatismybrowser.com
5.  Clear cookies in dev tools and reload the site
6. Verified no cookies shown in the dev tools
7.  Verified `www.whatismybrowser.com` site entry is shown in the `Sites that can never use cookies` in `brave://settings/cookies`
8. Verified `www.whatismybrowser.com` site entry is removed in the `Sites that can always use cookies` in `brave://settings/cookies`

![image](https://user-images.githubusercontent.com/34715963/181522565-4b19e2da-24c7-4d27-a83e-18d354411b51.png)
![image](https://user-images.githubusercontent.com/34715963/181523422-3c636f7c-2276-478e-bf10-507667697953.png)


</details>

Case 6: Set to `Block cross-site cookies` in `Shields` panel  - PASSED
<Details>

1. Continue from Case 5:
    - Keep `Allow all cookies` in `brave://settings/cookies`
    - `www.whatismybrowser.com` site entry is still shown in the `Sites that can never use cookies` in `brave://settings/cookies`
2. Visit www.whatismybrowser.com site
    - Select `Block cross-site cookies` in the `Shields` panel
3. Open `brave://settings/shields` and verify `Disabled` is selected  to match to `brave://settings/cookies`
4. Reload www.whatismybrowser.com site
5. Verified no `3rd party cookies` shown in the dev tools
6. Verified `[*.]whatismybrowser.com` entry is shown in `Sites than can always use cookies` in `brave://settings/cookies`

![image](https://user-images.githubusercontent.com/34715963/181525063-0bcf1188-c68b-4ce5-9571-9438e1683cf9.png)
![image](https://user-images.githubusercontent.com/34715963/181525210-d795e36e-8a70-4af7-b8d4-404f21f631e8.png)
![image](https://user-images.githubusercontent.com/34715963/181525395-2c27635e-b281-4f96-9b84-8c7aceae10b2.png)
![image](https://user-images.githubusercontent.com/34715963/181525541-01424c20-49e4-4097-bc07-fc3cb83afe75.png)
![image](https://user-images.githubusercontent.com/34715963/181525875-7932196f-67e4-4e8c-bd6b-e149680fa595.png)


</details>

Case 7: Remove `first party rule` in `brave://settings/cookies` - PASSED
<Details>

1. Continue from Case 6:
    - `[*.]whatismybrowser.com` entry is still listed in `Sites than can always use cookies` in `brave://settings/cookies`
    - Keep `Allow all cookies` in `brave://settings/cookies
    - `www.whatismybrowser.com` entry is still shown in the Sites that can never use cookies in brave://settings/cookies
    - delete all cookies in dev tools (see video from PR for instruction if needed)
2. Click trash icon next to `[*.]whatismybrowser.com` to delete the entry in `Sites that can always use cookies`
3. Return to `www.whatismybrowser.com` site and verify Shield settings changed to `Block all cookies`
4. Clear cookies in dev tools and reload the site
5. Verified no cookies shown in the dev tools

![image](https://user-images.githubusercontent.com/34715963/181539037-5aa29544-91b1-449e-8e1c-13e3315f444f.png)
![image](https://user-images.githubusercontent.com/34715963/181540717-83205af6-d424-483d-8bc3-e99d703592e7.png)
![image](https://user-images.githubusercontent.com/34715963/181541543-f6c9243c-cb5b-4eac-83d3-4a245a12a779.png)
![image](https://user-images.githubusercontent.com/34715963/181543240-3dd56d48-e8d8-4ba5-b386-30365f52802f.png)
![image](https://user-images.githubusercontent.com/34715963/181543632-e216b7d0-cce6-4849-a352-06eeaa12c73b.png)


</details>

Case 8: Remove `block rule` in `brave://settings/cookies` - PASSED
<Details>

1. Continue from Case 7:
    -  `www.whatismybrowser.com` entry is still listed in `Sites that can never use cookies` in `brave://settings/cookies`
    -  Keep `Allow all cookies` in `brave://settings/cookies`
    -  Shields panel shows `Block all cookies` setting
2. Click trash icon next to `www.whatismybrowser.com` to delete the entry in `Sites that can never use cookies`
3. Return to `www.whatismybrowser.com` site and verify Shield settings changed to `Allow all cookies`
4. Reload the site
5. Verified all cookies shown in the dev tools

![image](https://user-images.githubusercontent.com/34715963/181544309-a8a0f614-3085-4350-a662-0606b68db3fa.png)
![image](https://user-images.githubusercontent.com/34715963/181544532-4d06be2b-7377-4233-a4f1-8b3e4e4fec79.png)
![image](https://user-images.githubusercontent.com/34715963/181544766-626fb2e0-e1e3-4ce7-a641-c1602c27909f.png)
![image](https://user-images.githubusercontent.com/34715963/181545176-d11b2121-39ce-4efc-8524-fcf161270161.png)
![image](https://user-images.githubusercontent.com/34715963/181545467-ed3fd5ea-c432-4728-b8ec-7532879eff8b.png)
![image](https://user-images.githubusercontent.com/34715963/181545724-a12c1cc5-b189-4d29-b0a0-07a7d58b905b.png)


</details>

Case 9: Change to default setting, `Block third-party cookies` in `brave://settings/cookies` - PASSED
<Details>

1. Continue from Case 8:
    - `Allow all cookies` in `brave://settings/cookies` is already selected
2. Select default setting of `Block third-party cookies` in `brave://settings/cookies`
3. Return to `www.whatismybrowser.com` site and verify Shield settings changed to `Block cross-site cookies`
4. Open `brave://settings/shields` and verified `Only cross-site` selected
5. Return to www.whatismybrowser.com site
6. Clear cookies in dev tools and reload the site
7. Verified no 3rd party cookies shown in the dev tools

![image](https://user-images.githubusercontent.com/34715963/181546049-2875240b-1a8b-4ca2-951a-98ccaf8581ee.png)
![image](https://user-images.githubusercontent.com/34715963/181546159-433be6a5-fb40-40cb-990e-15a68425a28a.png)
![image](https://user-images.githubusercontent.com/34715963/181546262-aa54cbef-9faa-4a18-811d-25cedc4bc2dc.png)
![image](https://user-images.githubusercontent.com/34715963/181546454-f59a6bb5-7040-4178-a3bf-1357a1b29b9b.png)
![image](https://user-images.githubusercontent.com/34715963/181546593-cb48002d-fd1d-49f3-a070-b6ffef490814.png)


</details>

Case 10: Manually add `allow all` rule in `brave://settings/cookies` - PASSED
<Details>

1. Continue from Case 9
    - Keep default setting of `Block third-party cookies` in `brave://settings/cookies`
    - Shields panel shows `Block cross-site only` setting
2. Manually add `www.whatismybrowser.com` in `Sites than can always use cookies` in `brave://settings/cookies` 
3. Check the check box of `Including third-party cookies on this site`
4. Return to `www.whatismybrowser.com` site and verify Shield settings changed to `Allow all cookies`
5. `Block third-party cookies` setting is still retained brave://settings/cookies
6. Clear cookies in dev tools and reload the site
7. Verified all cookies shown in the dev tools including 3rd cookies

![image](https://user-images.githubusercontent.com/34715963/181552110-5bd85a14-ebd7-46cf-8bb1-290b80f639ec.png)
![image](https://user-images.githubusercontent.com/34715963/181552476-8ae72cc2-f352-4309-97df-d8538a513268.png)
![image](https://user-images.githubusercontent.com/34715963/181554199-36aa6a7b-8ad3-4ade-bb30-487a305b91b5.png)
![image](https://user-images.githubusercontent.com/34715963/181554899-def9f541-dcc0-4fd4-9a4d-421f65254f58.png)
![image](https://user-images.githubusercontent.com/34715963/181555465-b7deb987-ec7c-42ce-a218-943631d884d5.png)
![image](https://user-images.githubusercontent.com/34715963/181555981-27f9b853-f21c-481e-8afe-391f881c9fae.png)


</details>

Case 11: Manually add `allow all` rule in `brave://settings/cookies` - do not check for 3rd party cookies - PASSED
<Details>

1. Continue from Case 10
  - Keep default setting of `Block third-party cookies` in `brave://settings/cookies`
  - Shields panel shows `Block cross-site only` setting
2. Remove entry from TC 10, then manually add `www.whatismybrowser.com` in `Sites than can always use cookies` in `brave://settings/cookies` 
3. Do not Check the check box of `Including third-party cookies on this site`
4. Return to www.whatismybrowser.com site and verify Shield settings changed to `Allow all cookies`
5. `Block third-party cookies` setting is still retained brave://settings/cookies
6. Clear cookies in dev tools and reload the site
7. Verified 3rd party cookies not shown in the dev tools

![image](https://user-images.githubusercontent.com/34715963/181558871-f57f4efd-5de4-4c4b-be3b-a43924ac0ec5.png)
![image](https://user-images.githubusercontent.com/34715963/181559376-88d97e9e-0625-44f5-9faf-481711a0d451.png)
![image](https://user-images.githubusercontent.com/34715963/181560211-e18d44a5-8f3d-4044-bc27-bbbe0b730220.png)
![image](https://user-images.githubusercontent.com/34715963/181563166-eefd0df8-1cc0-42ae-a310-f338593363d9.png)
![image](https://user-images.githubusercontent.com/34715963/181563542-4ad1ccb8-329c-4d3b-8e3e-210af5026889.png)


</details>

Case 12: Manually remove `allow all` and add `block all` in `brave://settings/cookies` - PASSED
<Details>

1. Continue from Case 11
    - Keep default setting of `Block third-party cookies` in `brave://settings/cookies`
    - `www.whatismybrowser.com` entry is still listed `Sites than can always use cookies` in `brave://settings/cookies` 
    - Shields panel in `whatismybrowser.com` still shows `Allow all cookies` setting
2. open brave://settings/cookies and remove the entry for the `www.whatismybrowser.com` from `Sites than can always use cookies` 
3. Add `www.whatismybrowser.com` in `Sites that can never use cookies` in `brave://settings/cookies` including checking the checkbox for 3rd party cookies
4. Return to www.whatismybrowser.com site and verify Shield settings changed to `Block all cookies`
5. Clear cookies in dev tools and reload the site
6. Verified no cookies shown in the dev tools


![image](https://user-images.githubusercontent.com/34715963/181565859-76a9369b-49d8-4568-9ace-bd30b9689dbb.png)
![image](https://user-images.githubusercontent.com/34715963/181566026-f46eb2c2-5a01-45e2-a07b-440215569432.png)
![image](https://user-images.githubusercontent.com/34715963/181566159-7108887a-6060-481a-a44b-50c0ca5b6cbe.png)


</details>

Case 13: `Disable` Shields in the Shields panel - PASSED
<Details>

1. Continue from Case 12
    - Keep default setting of `Block third-party cookies` in `brave://settings/cookies`
    - `www.whatismybrowser.com` is still listed in `Sites that can never use cookies` in `brave://settings/cookies`
3. Return to www.whatismybrowser.com site and turn shields `DOWN` in the Shields panel 
4. Verified `www.whatismybrowser.com` entry is added to `Sites than can always use cookies` in `brave://settings/cookies`   
5. When `Allow all` rule is added in Step 3 when Shields was `disabled`, 'www.whatismybrowser.com' is hidden in `Sites that can never use cookies` section 
6. Confirmed `www.whatismybrowser.com` entry cannot be deleted when clicked on delete icon 
7. Return to www.whatismybrowser.com site and clear cookies in dev tools and reload the site
8. Verified all cookies shown in the dev tools

![image](https://user-images.githubusercontent.com/34715963/181566430-b0cd04b5-72b8-4445-bf9b-f095dbaf37c7.png)
![image](https://user-images.githubusercontent.com/34715963/181566816-c75241b9-80d0-427c-99c7-900a8ee42a5d.png)
![image](https://user-images.githubusercontent.com/34715963/181567206-f8824566-d1a4-4108-9f0c-fc829b373c18.png)


</details>

Case 14: `Enable` Shields in the Shields panel - PASSED
<Details>

1. Continue from Case 13
    - Keep default setting of `Block third-party cookies` in `brave://settings/cookies` 
    -`www.whatismybrowser.com` is still hidden in `Sites that can never use cookies` in `brave://settings/cookies`
    - Shields `DOWN` for `www.whatismybrowser.com` site in the Shields panel 
    - `www.whatismybrowser.com` entry is available `Sites than can always use cookies` in `brave://settings/cookies`   
2.  Return to `www.whatismybrowser.com` site and `enable` Shields
3. `Block all cookies` setting is retained in the Shields panel
4.  `www.whatismybrowser.com` entry is removed from `Sites than can always use cookies` in `brave://settings/cookies` 
5.  `www.whatismybrowser.com` is shown in `Sites that can never use cookies` 
6.  Clear cookies in dev tools and reload the site
7.  Verified no cookies shown in the dev tools

![image](https://user-images.githubusercontent.com/34715963/181569299-0801b648-8c7c-4dad-a9a1-6608af740354.png)
![image](https://user-images.githubusercontent.com/34715963/181569396-d7274755-371f-43e6-8b74-5c46d6de5bdd.png)
![image](https://user-images.githubusercontent.com/34715963/181569927-46d053ce-5b4a-4ff8-ae37-bdce516889ac.png)
![image](https://user-images.githubusercontent.com/34715963/181570054-44bb1285-ce5f-49cc-8c3f-15f1192b5a29.png)
![image](https://user-images.githubusercontent.com/34715963/181570184-f84e3029-6562-4ae1-b310-3e480daae1d3.png)


</details>

Case 15: Change to `Block cross-site cookies` in the Shields panel - PASSED
<Details>

1. Continue from Case 14
    - Keep default setting of `Block third-party cookies` in `brave://settings/cookies` 
    - `www.whatismybrowser.com` entry is shown in `Sites that can never use cookies` 
2.  Return to `www.whatismybrowser.com` site and select `Block cross-site cookies`
4. `www.whatismybrowser.com` entry is added to `Sites than can always use cookies` in `brave://settings/cookies` 
5.  Clear cookies in dev tools and reload the site
6.  Verified no 3rd party cookies shown in the dev tools

![image](https://user-images.githubusercontent.com/34715963/181571011-a6307976-ec2d-4991-b9a7-a01e159e1965.png)
![image](https://user-images.githubusercontent.com/34715963/181571300-cad5458b-95ce-44f4-b621-c2e32d8b789f.png)
![image](https://user-images.githubusercontent.com/34715963/181571406-f37457f7-c83b-4974-aa19-e753aa93755a.png)
![image](https://user-images.githubusercontent.com/34715963/181571656-5fdb3715-3d6f-4399-aba1-cce97a3c1cac.png)


</details>

Case 16: Remove shields rules in `brave://settings/cookies` - PASSED
<Details>

1. Continue from Case 15
    - Keep default setting of `Block third-party cookies` in `brave://settings/cookies` 
    - `www.whatismybrowser.com` entry is shown in `Sites that can never use cookies` in `brave://settings/cookies`
    - `www.whatismybrowser.com` entry is shown in `Sites than can always use cookies` in `brave://settings/cookies` 
    - Shields panel shows `Block cross-site cookies` for `www.whatismybrowser.com`
2.  Delete following in `brave://settings/cookies` 
    - `www.whatismybrowser.com` entry is shown in `Sites that can never use cookies` 
    - `www.whatismybrowser.com` entry is shown in `Sites than can always use cookies` 
3.  Return to `www.whatismybrowser.com` and confirmed Shields panel shows `Block cross-site cookies`
4. Clear cookies in dev tools and reload the site
5. Verified no 3rd party cookies shown in the dev tools

![image](https://user-images.githubusercontent.com/34715963/181572079-275e79d2-b19a-4334-954d-6f5cf3123dd0.png)
![image](https://user-images.githubusercontent.com/34715963/181572182-b9056df7-72c4-4159-b1aa-25ec5935cd5d.png)
![image](https://user-images.githubusercontent.com/34715963/181572295-233e01c8-d3db-4a3e-a6be-cbf399f5f2a9.png)


</details>

Case 17: Allow all cookies in `brave://settings/cookies` - PASSED
<Details>

pre-req: clear all cookies in dev tools

1. Select `Allow all cookies` in `brave://settings/cookies` 
2. Load www.whatismybrowser.com and click on the lock icon>>Cookies>>webbrowsertests.com (the one with the 3rd party cookie)>>Block>>Done
3. Click `Reload` to reload the page
4. Verified Shields panel shows `Allow all cookies` settings
5. Confirmed `webbrowsertests.com` entry is added to `Sites that can never use cookies`
6. Return to www.whatismybrowser.com site and reload the page
7. Verified no 3rd party cookies shown in the dev tools 

![image](https://user-images.githubusercontent.com/34715963/181572735-f5bcc2ec-f61e-4ade-9446-49661acf863c.png)
![image](https://user-images.githubusercontent.com/34715963/181572804-515b246d-b458-47bc-8767-62d6047efddf.png)
![image](https://user-images.githubusercontent.com/34715963/181572883-ab2adaa0-39a5-4655-a989-97d92d17877b.png)


</details>

Case 18: Shields `Down` in the Shields panel - PASSED
<Details>

pre-req: clear all cookies in dev tools

1. Keep `Allow all cookies` in `brave://settings/cookies`
2. Return to www.whatismybrowser.com site
3. Toggle `OFF` the shields in the Shields panel
4. Verified no 3rd party cookies shown in the dev tools 

![image](https://user-images.githubusercontent.com/34715963/181573215-6ede0249-9607-4171-ac45-c78a2b2e2aaf.png)
![image](https://user-images.githubusercontent.com/34715963/181573303-a780e8ad-3fc6-4c13-a585-93ec7cb2b7a5.png)


</details>

Case 19:  Delete 3p rule from `brave://settings/cookies` - PASSED
<Details>

pre-req: clear all cookies in dev tools

1. Continue from Case 17
    -  Keep `Allow all cookies` in `brave://settings/cookies`
    - `www.webbrowsertests.com` entry is still shown to `Sites that can never use cookies`
2. Open brave://settings/cookies and remove `www.webbrowsertests.com` entry by clicking ellipsis>>Remove 
3. Return to the www.whatismybrowser.com site and clear cookies in dev tools and reload 
4. Verified all cookies shown in the dev tools

![image](https://user-images.githubusercontent.com/34715963/181573630-61f8a91c-f042-43c6-974b-2fc18ad7abc1.png)
![image](https://user-images.githubusercontent.com/34715963/181573748-1232cc11-f995-4b4b-9516-041080cfd457.png)
![image](https://user-images.githubusercontent.com/34715963/181574127-6e228601-1d92-44be-b376-88661d03473f.png)


</details>

**Comment by urbenlegend** [comment]
I am on 1.42.86 and clicking on the trash icon in the Sites that can always use cookies list still does nothing. Are we sure this has actually been fixed?

**Comment by LaurenWags** [comment]
@urbenlegend there are still cases where clicking on the trash icon does not work, see follow up issue https://github.com/brave/brave-browser/issues/24106

cc @rebron

**Comment by Robio** [comment]
Running 1.42.88 — this issue has not been resolved for me. There are _no_ circumstances under which clicking the trash icon in "Sites that can always use cookies" actually removes the site, shields up or down.

**Comment by Gelsamel** [comment]
Still experiencing this in 2024 with this version:

![image](https://github.com/brave/brave-browser/assets/47681160/ed824b32-4411-413a-be21-f08e26c456c5)

Is it not kind of inexcusable that this is an issue in a privacy/security focused browser????

**Comment by Robio** [comment]
> Is it not kind of inexcusable that this is an issue in a privacy/security focused browser????

A little bit, yeah!
