### ISSUE TITLE
Browser crash when disconnecting slack call

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#861]
## Description 

Browser crash when disconnecting slack call

## Steps to Reproduce

   1. Login to slack on an upgraded profile on 0.54.2
   2. Ask some one who is free to call you on slack
   3. Try to cancel/end the call opened in a new tab, browser crashes 

## Actual result:

Browser crash when disconnecting slack call
Crash ID: 2f8836ce017464e5 

## Expected result:
Should not crash, just close the call tab and get back to work 

## Reproduces how often: 

Happened once. Need to see if it happens consistently 

## Brave version (about:brave info) 

Brave | 0.54.2 Chromium: 69.0.3497.42 (Official Build) dev (64-bit)
-- | --
Revision | 9c4613c66dfeb2b76ef6dd4b15884c15db3b4969-refs/branch-heads/3497@{#655}
OS | Windows

### Reproducible on current release:

No, b-l doesn't crash 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc @bbondy @brave/legacy_qa

**Comment by srirambv** [comment]
Crash reproduced with the following scenario as well
1. You call someone on slack
2. Ask them to disconnect the call
3. Your browser crashes but not for the other person whom you called

Crash ID for above steps  65f43580adbb5062

**Comment by srirambv** [comment]
Issue reproduced on Windows release build (0e2e3a222bfe58f93953e665590e2b49f8e150d7) (Crash ID 88e48b203c0a8942) and on 0.55.3 (Crash ID 1ac08a59d04d0990). When call is initiated from Windows machine and the other person picks the call (irrespective of the platform they are on), the browser crashes for the person who initiated the call.

**Comment by kjozwiak** [comment]
@srirambv is this a duplicate of https://github.com/brave/brave-browser/issues/481 which we tested today?

**Comment by bsclifton** [comment]
@kjozwiak I don't think this is a duplicate- I believe it's different because the call works and this is happening when disconnecting. Is that right, @srirambv?

**Comment by srirambv** [comment]
Yes @bsclifton that is correct. #481 was only causing webview crash the moment you receive a call. This is specifically for browser crashing when trying to disconnect the call. This still happens on source btw but not on the CI builds (dev, not so sure about beta that still needs to be verified)

**Comment by kjozwiak** [comment]
> @kjozwiak I don't think this is a duplicate- I believe it's different because the call works and this is happening when disconnecting. Is that right, @srirambv?

Correct but when @srirambv and myself went through #481, we basically tested this as well by disconnecting several times on different platforms and didn't receive any crashes with the CI builds. That's why I was asking if it was a duplicate as this was basically tested with #481. Could have worded it better though!

**Comment by srirambv** [comment]
Verified the following scenarios and it works fine. No webview crash/browser crash
1. Call from Mac -> Linux, call disconnected from Mac , No crash
2. Call from Mac -> Linux, call disconnected from Linux, No crash
3. Call from Windows -> Mac, call disconnected from Mac, No crash
4. Call from Windows -> Mac, call disconnected from Windows, No crash
