### ISSUE TITLE
Nightly builds fail with licensing error

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#8615]
## Description 
When building Nightly, the following error happens:
```
14:02:50  regenerating LICENSE files...
14:02:50    - 44 sub-components added in adblock/LICENSE
14:02:50    - 5 sub-components added in local_data/LICENSE
14:02:50  Invalid license for background image ntp-fall-2019-6. It needs to be a URL or the string "used with permission".
```

## Steps to Reproduce

   1. Queue nightly build
   2. It fails
   3. Check logs

## Reproduces how often: 
100%

**Comment by bsclifton** [comment]
Would be great if this ran daily and notified us- versus breaking the build

**Comment by bsclifton** [comment]
Closing - we can make sure this is addressed with https://github.com/brave/brave-browser/pull/8560

**Comment by LaurenWags** [comment]
@bsclifton marking as `QA/No`, please update if that's incorrect.
