### ISSUE TITLE
Update Tap Network promotion copy

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#8617]
Should read:
**Redeem BAT for Gift Cards**
With TAP Network, you can redeem your BAT for popular name-brand gift cards.

<img width="433" alt="Screen Shot 2020-03-10 at 8 49 59 AM" src="https://user-images.githubusercontent.com/8732757/76331793-cd827f80-62ac-11ea-8de0-f0e1f487ea5f.png">

**Comment by LaurenWags** [comment]
@ryanml @bsclifton looks like this isn't in 1.7.x but is actually in 1.8.x per https://github.com/brave/brave-core/commits/master?before=288afddae3b0eda2bc9b1d1d9eaa5a8990f629ea+315

Could you please review and determine if this can be moved to 1.8.x or if an uplift request is needed? Marking as `QA/Blocked` until this is sorted out. Thanks!

cc @kjozwiak @rebron

**Comment by LaurenWags** [comment]
Verified passed using

Brave | 1.7.73 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4890
<img width="907" alt="Screen Shot 2020-03-25 at 3 58 52 PM" src="https://user-images.githubusercontent.com/28145373/77580087-c5802d80-6eb1-11ea-95f4-873575629a39.png">

* Also confirmed launching with a non-US region (I used Canada) did not show the TAP message
<img width="903" alt="Screen Shot 2020-03-25 at 4 03 05 PM" src="https://user-images.githubusercontent.com/28145373/77580295-23ad1080-6eb2-11ea-82aa-8240c9b7bbb7.png">
