### ISSUE TITLE
Need to re-enable generation of LICENSE files

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#8618]
https://github.com/brave/brave-browser/pull/8616 temporarily disabled license generation in order to fix a build failure (https://github.com/brave/brave-browser/issues/8615).

We need to make sure it's re-enabled (likely by https://github.com/brave/brave-browser/pull/8560) since we can't ship 1.7 without it.

**Comment by bsclifton** [comment]
Added some steps we can try when queueing the next 1.7 build 😄

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.7.70 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-browser/pull/8560
![image](https://user-images.githubusercontent.com/34715963/77338930-57116300-6d2b-11ea-9f7b-a5a9311fd9a9.png)
![image](https://user-images.githubusercontent.com/34715963/77339008-74dec800-6d2b-11ea-9e3e-9fc099ffd077.png)
