### ISSUE TITLE
Video doesn't get added to blocked list when prompt is closed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#862]
## Description 

Video doesn't get added to blocked list when prompt is closed

## Steps to Reproduce

   1. Clean profile on 0.54.2
   2. Open YouTube and play a video
   3. Autoplay prompt shows up when video is loaded, ignore it and click the play button, video starts to play
   4. Close the autoplay notification prompt, shows added to block list
   5. Open Setting->Advanced->Privacy->Content Settings->Autoplay no exception added to block list
   6. Click on Autoplay button in YouTube tab, balloon notification shows `Continue blocking video`

## Actual result:

![autoplay](https://user-images.githubusercontent.com/17010094/44730648-755fa000-aaaf-11e8-93bd-ce3c6c6c8eb3.gif)

## Expected result:
Should not play video until user clicks deny or allow in the autoplay balloon to make a choice. If user clicks Allow should autoplay, If user click block it should be click to play

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Brave | 0.54.2 Chromium: 69.0.3497.42 (Official Build) dev (64-bit)
-- | --
Revision | 9c4613c66dfeb2b76ef6dd4b15884c15db3b4969-refs/branch-heads/3497@{#655}
OS | Windows

### Reproducible on current release:

No. b-l does what the setting says

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @brave/legacy_qa to verify on other platforms as well

**Comment by LaurenWags** [comment]
Reproduces on macOS using 0.54.2 9c4613c66dfeb2b76ef6dd4b15884c15db3b4969-refs/branch-heads/3497@{#655}

**Comment by darkdh** [comment]
This is expected for all content setting. If you click prompt, nothing will be added to the block list. It just blocked it this time.
You can try other content settings which is default ask like notification or geolocation
