### ISSUE TITLE
Rewards : Allow for users to opt in to P2P referrals 

### ISSUE THREAD

**Issue by alexwykoff** [brave/brave-browser#8620]
Per the P2P referral spec, users need a means to opt into our referral program.

A card needs to be created on the Rewards Setting page, details regarding wallet connection state and UI are in the spec.

**Comment by bsclifton** [comment]
@alexwykoff @NejcZdovc are there QA steps or a test plan for this? Can we update the issue please?

**Comment by LaurenWags** [comment]
Marking as `release-notes/exclude` and `QA/No` as this issue is superseded by https://github.com/brave/brave-browser/issues/9862
