### ISSUE TITLE
[Android] Global stats are not always migrated tabs=>core [Followup to #8456]

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#8624]
## Steps to reproduce 

   1. Install current stable version from GPS
   2. Open couple websites that stats have some amount of ads and etc blocked
   3. Update to a stable version that is core based.

## Actual result 
The stats won't retain.

## Expected result
The stats should retain

## Issue reproduces how often 
1 of 5 times to me

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Follow up of #8456

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.113 x64 build
- Verified upgrade doesn't lose stats on NTP
-------
Verification passed on Samsung Tab A with Android 9.0 running 1.5.113 x64 build
- Verified upgrade doesn't lose stats on NTP
-------
