### ISSUE TITLE
Wrong amount of BAT one-time tip

### ISSUE THREAD

**Issue by onmyouji** [brave/brave-browser#8625]
## Description 

I sent a 10 BAT tip to duckduckgo, but when I checked my history, it shows that I donated twice, 5 BAT + 10 BAT. I’m pretty sure I didn’t misclick, because there’s no option for a 5 BAT donation. The only options there are 1, 10, and 100 BAT.

![6cb7217d27fe69adeb76c14bac7ba239bd606356](https://user-images.githubusercontent.com/8424198/76376970-3f75ca00-637c-11ea-8ff5-8fd80704ed26.png)

## Steps to Reproduce

I haven't tried to reproduce this, since I don’t want to lose my BAT. But here’s how I donated to duckduckgo:
   1. Visit duckduckgo.com
   2. Click on the Brave Rewards triangle icon on the right of address bar.
   3. Click “Send a Tip”. Choose 10 BAT, then send the tip.

## Actual result:

Transaction history shows that I donated 15 BAT (10 + 5).

![Image 15](https://user-images.githubusercontent.com/8424198/76376940-2b31cd00-637c-11ea-84ff-34a609659eff.png)

![08cc7adba555f2079b04a002a46c102a13798a0c](https://user-images.githubusercontent.com/8424198/76376952-31c04480-637c-11ea-8b36-e586d0766ce3.png)

## Expected result:
Brave should donate the right amount (10 BAT).

## Reproduces how often: 

I haven't tried to reproduce this, since I don’t want to lose my BAT.

## Brave version (brave://version info)

Brave:	1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
Revision:	fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS:		Windows 10 OS Version 1809 (Build 17763.1039)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Haven't tested.
- Can you reproduce this issue with the beta channel? Haven't tested.
- Can you reproduce this issue with the dev channel? Haven't tested.
- Can you reproduce this issue with the nightly channel? Haven't tested.

**Comment by NejcZdovc** [comment]
cc @LaurenWags @alexwykoff did we see something like this already?

**Comment by LaurenWags** [comment]
@NejcZdovc I have not encountered this, not sure if @alexwykoff has.

**Comment by NumDeP** [comment]
Must be related to #8895 

20 BAT was what I contributed first and later noticed 16.5 BATs as well in Rewards.


![Screenshot_20200328_122038](https://user-images.githubusercontent.com/31957540/77822950-319ba500-70ef-11ea-842e-19e7028f70ec.png)

**Comment by NejcZdovc** [comment]
this will be fixed with #8895 in 1.8.x
