### ISSUE TITLE
[Webcompat] Playstation Logins not working

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#8629]
## Description 
Visiting: `https://store.playstation.com/` Won't allow user to login.
 
## Steps to Reproduce

   1.  Visit ` https://store.playstation.com/` 
   2.  Click on Login. 
   3.  Doesn't work with default Shields

## Actual result:
Login will fail.

## Expected result:
Expect menus and login to work.

## Reproduces how often: 
Easily

## Brave version (brave://version info)
`Version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)`

## Version/Channel Information:
`Version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)`

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes 

## Miscellaneous Information:
`Allow Cookies` in shields is needed

**Comment by ryanbr** [comment]
Affecting at least 3 sony domains I'm are of:  It seems we need to allow cookies on all 3 domains.

https://my.playstation.com/  (redirects to `id.sonyentertainmentnetwork.com`)

![my-play](https://user-images.githubusercontent.com/1659004/80544403-17fabf80-8a05-11ea-9d77-1f57912da715.png)

https://store.playstation.com/
![store-play](https://user-images.githubusercontent.com/1659004/80544429-28129f00-8a05-11ea-9fd1-cb530bef7b0e.png)

https://id.sonyentertainmentnetwork.com/
![id-sony](https://user-images.githubusercontent.com/1659004/80544504-51332f80-8a05-11ea-8d70-ccab09bf3df3.png)

**Comment by ryanbr** [comment]
During the login process for playstation.com (where its failing)

**Looking at the logs.**

On the domain: `playstation.com`
We should allow: `sonyentertainmentnetwork.com`

And in reverse; 
On the domain `sonyentertainmentnetwork.com`
Allow `playstation.com`

**Comment by ryanbr** [comment]
@pes10k  thoughts?

**Comment by pes10k** [comment]
I believe this will be solved by the PR coming from https://github.com/brave/brave-core/tree/fix-google-drive-autoplay-bj, very shortly (likely w/in the next 24 hours)

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Verified the STR from the description
- Verified that login is successful with default shield settings 
**Note**: `Sign In`  option on the PlayStation website is shown only after enabling `All cookies allowed`
![image](https://user-images.githubusercontent.com/38657976/83146416-dfd5c200-a113-11ea-97c5-1e0b73935fd8.png)

**Comment by LaurenWags** [comment]
Still able to reproduce the issue of not being able to login.

1. Must allow all cookies to see `Login` button on store.playstation.com - this is mentioned in `Miscellaneous Information` section of https://github.com/brave/brave-browser/issues/8629#issue-579058593, so maybe this is ok.
2. Once I do this though, on the next page I'm still unable to login which was the originally reported issue:
<img width="452" alt="Screen Shot 2020-05-28 at 10 02 27 AM" src="https://user-images.githubusercontent.com/28145373/83154161-cb6ed680-a0cd-11ea-8e74-ac6acda8ffaf.png">

```
Brave | 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.14.6 (Build 18G3020)
```

cc @rebron @bsclifton @pes10k

**Comment by LaurenWags** [comment]
Per discussion, marking as `release-notes/exclude` and `QA/No` as issue still reproduces. Logged follow up issue for this to be addressed: https://github.com/brave/brave-browser/issues/9987.
