### ISSUE TITLE
Light/Dark should be selectable in development

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#863]
https://github.com/brave/brave-core/pull/351 introduced theme preference for built-in light / dark but did not remove the compiler flag which forces dark theme in development. This should be selectable on any build, and only the default is different.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

**Comment by kjozwiak** [comment]
@btlechowski @srirambv was this checked against a local development build that was created from source? Double checked with @petemill who mentioned this is supposed to be tested with a local build.

**Comment by srirambv** [comment]
@kjozwiak I've verified it on Windows from source.  Will update once build finishes on Linux

**Comment by srirambv** [comment]
@kjozwiak verified on Linux as well the command line flag works with development folder. Just a note, only the URL bar colour changes for Linux when switching between Light and Dark and other chrome elements retain the GTK colour scheme

**Comment by kjozwiak** [comment]
Thanks @srirambv 👍
