### ISSUE TITLE
[Webcompat] Map not showing up on https://www.gisaid.org/epiflu-applications/global-cases-covid-19/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#8630]
## Description 
Viewing `https://www.gisaid.org/epiflu-applications/global-cases-covid-19/` Map doesn't show up

## Steps to Reproduce

   1. Visit `https://www.gisaid.org/epiflu-applications/global-cases-covid-19/`
   2. Expect world map to show up
   3. 

## Actual result:
Doesn't show world map

## Expected result:
Expect world map.

## Reproduces how often: 
Easily

## Brave version (brave://version info)
`Version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes

## Miscellaneous Information:

Disabling Fingerprinting, `All device device recognition blocked` fixes this.

**Comment by rebron** [comment]
Closing. This is fixed in #8902 in 1.7.92 and current release now is 1.8.86
