### ISSUE TITLE
Add contributions to internals page

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#8633]
With removal of anonize, we also removed old reconciles. We need to plug in new system in existing internals flow. We should display all contributions from the table with status of this. This way it's easier to track everything in one place

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.11.68 Chromium: 83.0.4103.106 (Official Build) dev (64-bit)
-- | --
Revision | ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
OS | Windows 10 OS Version 1903 (Build 18362.30)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/5739
Autocontribution using **UGP**
![image](https://user-images.githubusercontent.com/38657976/85145494-3ee9ab00-b26a-11ea-8e15-840d17a3f1d3.png)
![image](https://user-images.githubusercontent.com/38657976/85145605-6e001c80-b26a-11ea-994f-041b2e2b9398.png)

Autocontribution using **Restored anon wallet**
![image](https://user-images.githubusercontent.com/38657976/85146381-32198700-b26b-11ea-8aeb-c8e0117e050d.png)
![image](https://user-images.githubusercontent.com/38657976/85146514-45c4ed80-b26b-11ea-9d5a-addab7b1a26b.png)

Autocontribution using **KYC'd uphold wallet**
![image](https://user-images.githubusercontent.com/38657976/85147401-693c6800-b26c-11ea-8ce1-c7b2f1b03aeb.png)
![image](https://user-images.githubusercontent.com/38657976/85147440-7b1e0b00-b26c-11ea-82f2-5b9e2b531a46.png)
