### ISSUE TITLE
[Desktop] Fullscreen on HiDPI screen doesn't work

### ISSUE THREAD

**Issue by ElianCodes** [brave/brave-browser#8636]
## Description 

When watching any type of video content on a HiDPI screen, the fullscreen option doesn't work. I'm able to click on it, but when I do, the screen changes to leftuppercorner and fills about 1/4th of the screen, i'm guessing it goes to 1080p

## Steps to Reproduce

   1.  go to youtube.com
   2. click any video
   3. click play - this should work fine
   4. click fullscreen -> looks as below:

## Actual result:

![image](https://user-images.githubusercontent.com/15145918/76425589-208e2c80-63aa-11ea-947e-6fa398505120.png)

## Expected result:
a normal screen filling

## Reproduces how often: 

Everytime on any type of video content

## Brave version (brave://version info)

Brave | 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Linux
JavaScript | V8 8.0.426.26
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,WebXR,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,VideoPlaybackQuality,WebXrGamepadModule --flag-switches-begin --load-media-router-component-extension=1 --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /opt/brave.com/brave/brave

## Version/Channel Information:

- Can you reproduce this issue with the current release?
yes
- Can you reproduce this issue with the beta channel?
haven't tried
- Can you reproduce this issue with the dev channel?
haven't tried
- Can you reproduce this issue with the nightly channel?
haven't tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
no
- Does the issue resolve itself when disabling Brave Rewards?
no
- Is the issue reproducible on the latest version of Chrome? 
no - it works fine in chrome

## Miscellaneous Information:

I'm using Deepin linux on a Dell XPS 13" with 4K resolution

**Comment by ronki2304** [comment]
Hello I have two 4k monitor and I have this problem only one screen, really weird.

By the way I found a workaround, go to setting and enable "Use system title bar and borders". Put your video in full screen mode and then you can disable this option, the full screen sty correctly.  But if you quit the fullscreen mode you have to do it again
