### ISSUE TITLE
Move Safe Browsing key to proxy

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#864]
Do not include the key in code or client, instead move it to the proxy. We will use an`identifier` instead of the real key in the code, modify the request at the proxy to replace the `identifier` with the `key` and add rate limiting at the proxy to avoid abuse

**Comment by fmarier** [comment]
I'm not sure when this was done, but the key is in fact on the proxy. The client only has a dummy key:
https://github.com/brave/brave-core/blob/44bbdfdd8e21a1aa79f1bd473c27c46278f664d2/build/commands/lib/config.js#L95
