### ISSUE TITLE
Remove setting for conversion/attribution confirmation

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#8640]
## Description 
Going through the conversion setting with users, it turns out this is very confusing and given the number of campaigns that will have this requirement, not a helpful distinction.  We are going to remove this setting for now.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.5.112 Chromium: 80.0.3987.132 (Official Build) (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | macOS Version 10.14.6 (Build 18G3020)

* Confirmed setting removed from Ads Settings
<img width="657" alt="Screen Shot 2020-03-17 at 11 21 16 AM" src="https://user-images.githubusercontent.com/28145373/76871499-81ea4b80-6841-11ea-9f19-d089bcf4dbf8.png">
