### ISSUE TITLE
Disable background ads on Android

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#8641]
## Description 

Please disable background ads on Android

and remove the UI from settings

![Screenshot_20200311-140635.jpg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/2daa92da-794d-4572-8cf7-531ce37c84f8)

**Comment by gdregalo** [comment]
It was decided not to remove background ads now but set them to off for all existing and new installations. And let users to explicitly turn them on if they wish.
https://bravesoftware.slack.com/archives/CB0KCRCQN/p1587149569187400

**Comment by srirambv** [comment]
I don't see any uplift PR's for this issue. The PR fix is marked for 1.10.x. We should move this one out of 1.7.x and may be put it in 1.8.x 

cc: @anthonypkeane @gdregalo @SergeyZhukovsky @kjozwiak

**Comment by srirambv** [comment]
Moving it out of 1.7.x and moving to 1.10.x

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J5 version 5.1.1 running BraveModernarm.apk 1.8.93
- Verified that the `Show Ads when Brave is not in use` is disabled by default as per (https://github.com/brave/brave-browser/issues/8641#issuecomment-618512821)
- Verified that Ads are not served when the option is disabled and the app is running in the background
- Verified that Ads are served to the user when  `Show Ads when Brave is not in use` is enabled
