### ISSUE TITLE
[Android] [FromTabs] Sync crashes when node is removed and then same objectId comes from cloud

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#8642]
## Description 
Similar to https://github.com/brave/browser-android-tabs/issues/2507 , already fixed in tabs repo, https://github.com/brave/browser-android-tabs/pull/2506. 

## Steps to reproduce 

The same as in https://github.com/brave/browser-android-tabs/issues/2507

1. Take a brave-browser desktop containing the changes from brave/brave-core#4404, version 1.8.0 is good
2. Create a chain on desktop
3. Connect Android browser to the chain
4. On desktop create folder OtherBookmark01 inside of Other bookmarks root folder
5. On desktop create a bookmark OtherBookmark01.com inside of OtherBookmark01 folder from pt2
6. Wait until OtherBookmark01 and OtherBookmark01.com appear on Android browser
7. Verify the structure of bookmarks on Android is
```
Other bookmarks
 +OtherBookmark01
    +OtherBookmark01.com
```
8. Delete folder `Other bookmarks` on Android
9. On desktop create folder OtherBookmark02 inside of Other bookmarks root folder
10. On desktop create a bookmark OtherBookmark02.com inside of OtherBookmark02 folder from pt9
11. Wait for sync to complete

## Actual result 
12. See crash on Android

## Expected result
12. No crash on Android. Bookmarks structure is
```
Other bookmarks
 +OtherBookmark02
   +OtherBookmark02.com
```

## Issue reproduces how often 
Easily

## Issue happens on 
   - Current Play Store version? yes
   - Beta build? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 9
   
## Brave version
1.5.105

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.111 x64 stable build
- Verified creating a sync with Desktop Nightly build 1.8.11 doesn't crash
- Verified steps from issue description and no crash after deleting `OtherBookmarks` folder on Android
- Verified Android had retained bookmark structure 
```
   Other bookmarks
     +OtherBookmark02
       +OtherBookmark02.com
````
----------
Verification passed on Samsung Tab A  with Android 9.0 running 1.5.111 x64 stable build
- Verified creating a sync with Desktop Nightly build 1.8.11 doesn't crash
- Verified steps from issue description and no crash after deleting `OtherBookmarks` folder on Android
- Verified Android had retained bookmark structure 
```
   Other bookmarks
     +OtherBookmark02
       +OtherBookmark02.com
````
----------
