### ISSUE TITLE
Category name is missing from ad history

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#8646]
## Steps to Reproduce

   1. View an ad notification

## Actual result:

Category name is missing from Ad History

## Expected result:
Category name should be shown on ad history

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.85 Chromium: 80.0.3987.162 (Official Build) dev (64-bit)
-- | --
Revision | f2c5dd6138153bb0658091205bd1a1717f16081a-refs/branch-heads/3987@{#1034}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified STR from description on clean profile
<img width="958" alt="Screen Shot 2020-04-03 at 12 38 28 PM" src="https://user-images.githubusercontent.com/28145373/78384362-0b22b180-75a8-11ea-9f11-7934c842e603.png">

* Verified STR from description on an upgrade profile. Viewed an ad prior to upgrade and confirmed I could see the category name in Ad History. After upgrading to 1.7.x,
   * Confirmed ad history still shows category name for ads viewed prior to upgrade
   * Confirmed ad history shows category name for ads viewed after upgrading
<img width="951" alt="Screen Shot 2020-04-03 at 12 19 56 PM" src="https://user-images.githubusercontent.com/28145373/78383119-d9105000-75a5-11ea-8b13-69fd5020115d.png">
