### ISSUE TITLE
No conversion due to lack of Slash at the end of urlPattern 

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#8648]
Found while testing https://github.com/brave/brave-browser/issues/8362

## Steps to Reproduce

   1. In the catalog set `urlPattern`  to `https://travala.com`
   2. In the catalog set `targetUrl`  to `https://travala.com`
   3. trigger the ad
   4. click on the ad to open the targetUrl

Note: if you add `/` at the end the conversion is successful

## Actual result:

No conversion due to lack of slash at the end of urlPattern.

## Expected result:
TBD

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.7.54 Chromium: 80.0.3987.132 (Official Build) nightly (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Ubuntu 18.04 LTS

Brave | 1.7.54 Chromium: 80.0.3987.132 (Official Build) nightly (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

cc @brave/legacy_qa @tmancey @jsecretan @rebron

**Comment by tmancey** [comment]
@btlechowski when visiting `https://travala.com` a slash is added at the end of the domain, this will only occur for domains URLs without a path. @jsecretan It is recommended that we enforce a `/` at the end of domains which do not have a path (I would expect this is very unlikely for conversion URLs) in the management console

**Comment by bsclifton** [comment]
@tmancey is this issue closed? (asking as I see it's in `Done` column)

**Comment by btlechowski** [comment]
@tmancey Has this issue been fixed in the management console?

**Comment by tmancey** [comment]
@btlechowski It has not been fixed server-side. Can you please raise a server-side ticket. Thanks

**Comment by btlechowski** [comment]
Logged the issue in the repo that was suggested by @jsecretan : https://github.com/brave/ads-serve/issues/990
