### ISSUE TITLE
Building on FreeBSD

### ISSUE THREAD

**Issue by brunomaximom** [brave/brave-browser#8649]
Hi, 

I'm trying to build my prefered browser on my prefered OS. Chromium is not supported by default on BSDs, so I need to use the patched Chromium from FreeBSD Ports Collection to be able to build Brave on it. 

To do this task I need to set my local path where chromium is fetched manually instead using depot_tools, then I can apply the FreeBSD patches before building Brave. How can I skip depot_tools? 

Thanks.

**Comment by bsclifton** [comment]
I believe this was asked on community.brave.com and I had tried to responded there

Closing this in favor of https://github.com/brave/brave-browser/issues/821
