### ISSUE TITLE
Improve profile Import

### ISSUE THREAD

**Issue by madvik** [brave/brave-browser#8655]
## Description 
If I began to use brave, I can import from chrome. But I can't modify profile name, it is profile 1, profile 2 etc...
And the extensions or not syncronize.

## Steps to Reproduce

   1. Install  brave
   2. Import from Chrome
   3. When I manage profile, I can't modify name

## Actual result:
 I can't modify profile name

## Expected result:
I want to sync my name and modify it in settings

## Brave version (brave://version info)
1.4.96

**Comment by rebron** [comment]
Hi @madvik for editing profile name you can go here. 
brave://settings/manageProfile

**Comment by madvik** [comment]
And how do you access it without a link in the UI ?

**Comment by rebron** [comment]
We need to add a link in the profile manager but you can get to in Settings. It's the first item under Get Started. Profile and Icon.

**Comment by programmerrush** [comment]
> And how do you access it without a link in the UI ?

By clicking on Profile icon on left side of more options > click on name
Directly goes on link

**Comment by rebron** [comment]
@madvik Profile name and icon is the first item in settings so the link to the UI is Settings in the menu.
