### ISSUE TITLE
Incorrect Web3 provider is selected in settings

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8656]
## Description 

Incorrect Web3 provider is selected in settings

## Steps to Reproduce

Scenario 1:
   1. Clean profile `1.4.89`
   2. Install MetaMask extension
   3. Upgrade to `1.5.109`
   4. Open settings page for web3 provider
   5. The `Crypto Wallet` is selected instead of `Ask` in the web3 provider dropdown 

Scenario 2:
  1. Clean profile `1.4.98`
  2. Enable CW ( just download the component don't create wallet)
  3. Install MM ( Just install don't create MM wallet)
  4. Upgrade to `1.5.109`
  5. Open settings page for web3 provider
  6. The `Crypto Wallet` is selected instead of `Ask` ( since both providers are installed Ask should be selected in the web3 providers dropdown)

Scenario 3:
  1. Clean profile `1.4.98`
  2. Create CW
  3. Install MM and create MM wallet
  4. Upgrade to `1.5.109`
  5. Open settings page for web3 provider
  6. The `Crypto Wallet` is selected instead of `Ask` ( since both providers are created Ask should be selected in the web3 providers dropdown)

## Actual result:

The `Crypto Wallet` is selected instead of `Ask` in the web3 provider dropdown 

## Expected result:

 `Ask` should be selected in the web3 provider dropdown 
## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.5.109 Chromium: 80.0.3987.132 (Official Build) beta (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Not sure
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @bbondy @ryanml @rebron

**Comment by bbondy** [comment]
@GeetaSarvadnya sorry for the late reply we have our triage meeting on Fridays and last one was canceled.  

So I think this might just be expected. Did you visit something like Crypto Kitties and select MetaMask from the infobar explicitly? If not then it is expected for it to select Crypto Wallets.

**Comment by GeetaSarvadnya** [comment]
@bbondy I have not selected MetaMask explicitly from Crypto Kitties infobar.

**Comment by bbondy** [comment]
Thanks, that's expected.

**Comment by kjozwiak** [comment]
Thanks @bbondy & @GeetaSarvadnya 👍
