### ISSUE TITLE
[Android] Menu is not hidden in the top bar after landscape mode

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#8657]
## Description 
Menu is not hidden in the top bar after landscape mode

## Steps to reproduce 

   1. On android phone go to landscape
   2. On landscape mode go to tabs overview
   3. Go back to portrait mode

## Actual result 
![Screenshot_20200311_215610_com brave browser_beta](https://user-images.githubusercontent.com/30602739/76525714-bbd2e080-6442-11ea-8a39-2a8323721fe9.jpg)

## Expected result
No menu in portrait mode in the top bar

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.111 x64 stable build 
- Verified menu is hidden when orientation is changed from landscape to portrait mode
