### ISSUE TITLE
Style HTTP links differently from HTTPS

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#866]
HTTP is a risky legacy protocol which we should do our best to deprecate. Styling HTTP and HTTPS links differently allows users to easily see what they're getting into.

**Comment by rossmoody** [comment]
I believe there is nothing blocking on the design side for these updates. A branch has been opened with de-chromed verbiage in the info strings of the modals (omitted Google links and slightly more approachable wording in some places as well). It's not sitting in the right place and we still need to update the iconography but it's a start.  Branch is called "error-updates"

**Comment by petemill** [comment]
@rossmoody I think there's some wires crossed here. I believe @tomlowenthal 's suggestion is to have links in web content styled differently so that the user is aware of the non-secureness of the page _before_ visiting the link.

**Comment by rossmoody** [comment]
Ah, you are right. I thought this was the issue regarding the HTTPS initiative.

**Comment by tomlowenthal** [comment]
Yeah, if there were a backlog for "not in v1", that's where this issue should go.
