### ISSUE TITLE
Improve farbling protections (extend to more API surface, prevent mask reuse)

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#8661]
*Problem*
Brave’s farbling protections for canvas can be circumvented by an attacker who farbles two canvases, painted with different operations, of the same size.  The attacker can recover the (effective) mask by XORing these two outputs together.

This attack is possible because (effectively) the current implementation reuses the same mask across all canvases under the same eTLD+1.

*Solution*
Generate the farbling mask with the eTLD+1 seed and the contents of the canvas.  This mask would be stored independently of the canvas contents, and reused as long as the contents of the canvas don’t change.  Storing the mask independently speeds up repeated farbles of the same contents 

Would also fix: https://github.com/brave/brave-browser/issues/8322

**Comment by LaurenWags** [comment]
@pilgrim-brave does this require manual QA? If yes, please add `QA/Yes` label and a test plan. If not, please add `QA/No` label. Thanks!

**Comment by LaurenWags** [comment]
@pilgrim-brave pinging on https://github.com/brave/brave-browser/issues/8661#issuecomment-628612893, thanks! cc @bsclifton

**Comment by pes10k** [comment]
@LaurenWags this is blocked on https://github.com/brave/devops/issues/3067

But once thats complete I can write up some manual tests for QA.  Just want all the tests to be on domains / servers that Brave owns

**Comment by LaurenWags** [comment]
thanks @pes10k - marking as `QA/Blocked` until that's ready 😄

**Comment by LaurenWags** [comment]
Per discussions w/ @pes10k here's the test plan:
Using 
- https://dev-pages.bravesoftware.com/farbling.html
- https://dev-pages.brave.software/farbling.html

Confirm that:
- with shields up, FP values are the same for each individual item (ex. WebGL Drawing) on a given page, but the values are different between the two pages above.
- with shields up, if you close and relaunch the browser, and visit the pages again the values are different (they are not retained between sessions).
- with shields down, FP values are the same for each individual item on a given page and are the same for both pages.
- with shields down, if you close and relaunch the browser, and visit the pages again, the values are the same (they are retained between sessions).

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.10.88 Chromium: 83.0.4103.97 (Official Build) (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{# 657}
OS | Linux

<details>
<summary>Verified with shields up, FP values are the same for each individual item (ex. WebGL Drawing) on a given page.</summary>

URL 1 | URL 2
-- | --
![image](https://user-images.githubusercontent.com/17010094/84490559-f4dc5480-acc0-11ea-93ff-9cbb3cdde2fd.png)  | ![image](https://user-images.githubusercontent.com/17010094/84490599-0160ad00-acc1-11ea-95ae-238d7ccd2ad4.png)

</details>

<details>
<summary>Verified with shields up, close and relaunch the browser, and visit the pages again the values are different except for WebGL Drawing - Passed</summary>

- Canvas and WebAudio has different values between relaunches

URL 1 | URL2
-- | --
![image](https://user-images.githubusercontent.com/17010094/84492452-d3309c80-acc3-11ea-82ec-b759c6489ad9.png) | ![image](https://user-images.githubusercontent.com/17010094/84492513-e479a900-acc3-11ea-9915-06029b5bcf17.png)
![image](https://user-images.githubusercontent.com/17010094/84492571-f78c7900-acc3-11ea-8a10-7f301c0298d7.png) | ![image](https://user-images.githubusercontent.com/17010094/84492644-1ab72880-acc4-11ea-8d9b-cc201bd1cf2a.png)

</details>

<details>
<summary>Verified with shields down, FP values for WebGL Drawing/Canvas/Web Audio are all the same on a given page and are the same for both pages.</summary>

URL 1 | URL2 
-- | --
![image](https://user-images.githubusercontent.com/17010094/84493026-ba74b680-acc4-11ea-8acf-d44b66df969b.png) |![image](https://user-images.githubusercontent.com/17010094/84493258-1a6b5d00-acc5-11ea-8c97-2b2b8fc16fab.png)
![image](https://user-images.githubusercontent.com/17010094/84493059-c6607880-acc4-11ea-8656-fd22dbc265c1.png) | ![image](https://user-images.githubusercontent.com/17010094/84493086-cfe9e080-acc4-11ea-8634-1fb4d0a6dacc.png)
![image](https://user-images.githubusercontent.com/17010094/84493112-daa47580-acc4-11ea-9839-e880b479fa23.png) | ![image](https://user-images.githubusercontent.com/17010094/84493141-e8f29180-acc4-11ea-8473-a3879a242e03.png)

</details>

<details>
<Summary>Verified with shields down, if you close and relaunch the browser, and visit the pages again, the values are the same (they are retained between sessions).</summary>

- No screenshots to show here
![image](https://user-images.githubusercontent.com/17010094/84494096-84d0cd00-acc6-11ea-8324-ec06c9bc1537.png)
</details>
