### ISSUE TITLE
macOS dock icon should be smaller

### ISSUE THREAD

**Issue by cperezabo** [brave/brave-browser#8662]
Could you make the app icon smaller? It doesn't look good among the rest of the icons! It's even taller than the Jetbrain icons!
![Captura de Pantalla 2020-03-12 a la(s) 15 40 38](https://user-images.githubusercontent.com/3604722/76556900-30c10d00-6479-11ea-817f-83d86c697af7.png)

**Comment by bsclifton** [comment]
cc: @bradleyrichter @karenkliu @rebron @jamesmudgett

**Comment by karenkliu** [comment]
lol it really is huge! 😂

**Comment by cperezabo** [comment]
Yeah! if you compare with the Apple icons it's a big boy!

![Captura de Pantalla 2020-03-12 a la(s) 17 02 52](https://user-images.githubusercontent.com/3604722/76562180-91edde00-6483-11ea-8cd3-7be1476edd80.png)

**Comment by karenkliu** [comment]
The design team is on it! 💪  Probably just needs a simple resize...

**Comment by cperezabo** [comment]
You are the best!

**Comment by bsclifton** [comment]
@cezaraugusto did you get a chance to check this out?

**Comment by cperezabo** [comment]
Any news about this? It's so disruptive to the dock! 🤯

**Comment by bradleyrichter** [comment]
This issue fell through the cracks but we can pick it up.


It looks like 90% is the right scale factor.

current:
![image](https://user-images.githubusercontent.com/13509546/94564655-14ba6880-021d-11eb-82f5-f085f6d76f32.png)


reduced to 90%:

![image](https://user-images.githubusercontent.com/13509546/94564713-2bf95600-021d-11eb-8f25-93f73f37d4fc.png)

While this brings its actual area down to below average, the visual weight - considering the color - is probably about right.

**Comment by cperezabo** [comment]
I think that size is ok. The base problem with the icon is that it should have gained some width because the aspect ratio does not favor it. But I am not a designer, just a developer who loves UI/UX so I could be completely wrong.

**Comment by karenkliu** [comment]
@simonhong Do you still need assets for this?

**Comment by simonhong** [comment]
@karenkliu I don't have new assets. Please attach here :)

**Comment by karenkliu** [comment]
@simonhong Just sent you a link to our GDrive where I exported the assets.

**Comment by rebron** [comment]
Verified on: 

Brave | 1.18.69 Chromium: 87.0.4280.88 (Official Build) (x86_64 translated)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | macOS Version 11.0.1 (Build 20B29)

![Screen Shot 2020-12-07 at 3 07 52 PM](https://user-images.githubusercontent.com/5951041/101416175-22840e00-389e-11eb-8808-dcf19dc08008.png)
![Screen Shot 2020-12-07 at 3 07 59 PM](https://user-images.githubusercontent.com/5951041/101416179-231ca480-389e-11eb-82eb-ecdcdb3e353f.png)

**Comment by LaurenWags** [comment]
thanks for checking this one @rebron 👍
