### ISSUE TITLE
Allow users to disable OpenSearch

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#867]
OpenSearch automatically adds search engines based on browsing the web. This can be useful for folks who don't want to spend the time carefully wrangling their own custom search operators and keywords. I like to meticulously curate those items, and find the automatic addition of other search engines frustrating. I'd like a switch to turn OpenSearch off.

**Comment by teresaejunior** [comment]
I currently use https://github.com/gregsadetsky/chrome-dont-add-custom-search-engines as a workaround.

**Comment by Madis0** [comment]
FWIW, Ungoogled Chromium [adds a flag for this.](https://github.com/Eloston/ungoogled-chromium/blob/master/docs/flags.md)
I would recommend replacing the automatic addition with an icon in the Omnibox if one is found, similar to how it works for PWA creation.

**Comment by ckujau** [comment]
This comes [up](https://www.reddit.com/r/brave_browser/comments/bu42z7/brave_automatically_adding_websites_to_my_list_of/ "Brave automatically adding websites to my list of search engines. Possible to disable this behaviour?") in [different](https://community.brave.com/t/brave-automatically-adding-websites-to-my-list-of-search-engines-possible-to-disable-this-behaviour/62644 "Brave automatically adding websites to my list of search engines. Possible to disable this behaviour?") places on the [interwebs](https://community.brave.com/t/stop-brave-from-adding-custom-search-engines/95742 "Stop Brave from adding Custom Search Engines") and I too am somewhat surprised that search engines are magically added to my browser configuration. Also, Mozilla [disabled](https://blog.mozilla.org/addons/2019/10/15/search-engine-add-ons-to-be-removed-from-addons-mozilla-org/ "Search Engine add-ons to be removed from addons.mozilla.org") [Opensearch](https://en.wikipedia.org/wiki/OpenSearch) last year.

Can't Brave do the same or at least introduce a knob to disable this behaviour? We don't want to end up like IE, back in the days, hm? :-D

![Screenshot from 2020-05-20 16-16-28](https://user-images.githubusercontent.com/822519/82506708-5c81f400-9ab5-11ea-9307-7da94efe948f.png)

**Comment by bsclifton** [comment]
@Madis0 thanks for the link to the flag - here's a patch we could consider pulling in if we wanted this feature (we'd probably do it a little differently, [via our patching guidelines](https://github.com/brave/brave-browser/wiki/Patching-Chromium)):
https://github.com/Eloston/ungoogled-chromium/blob/8d5cd3fce527462a707004b1c21212615e9561b3/patches/extra/ungoogled-chromium/add-flag-for-search-engine-collection.patch

cc: @rebron

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/disable-a-websites-ability-to-add-its-search-engine/176464?u=eljuno

**Comment by Madis0** [comment]
Good news, 1.30.69 (beta/dev) has a new default-disabled option: 

> Index other search engines
> Automatically indexes websites that follow the OpenSearch spec.

**Comment by bsclifton** [comment]
Closing - thanks for the ping @Madis0 😄 

Fixed with https://github.com/brave/brave-core/pull/9602
