### ISSUE TITLE
MEGA.NZ AND MEDIAFIRE.COM NOT WORKING ON BRAVE

### ISSUE THREAD

**Issue by krimnassim** [brave/brave-browser#8672]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@krimnassim I'm going to close this off for now as there's no information in the associated issue. Could you please create a new one and mention what exactly isn't working with the above websites?

I basically created a new account on https://mega.nz, uploaded and downloaded content from a shared link without any issues while using the default `Brave Shield` settings.

As mentioned before, please re-create a new issue with some more information so we can help you!
