### ISSUE TITLE
Balance is fetched too often

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#8674]
## Description

Balance query calls to custodian are called too frequently.

## Solution

TBD

Original proposal from Nejc:
>We should start caching balance on the client side. We should only fetch new balance when we are doing contribution as then we need latest, otherwise we should limit UI pull on something like a minute. This will reduce network calls quite a bit.

**Comment by NejcZdovc** [comment]
we could user new timers for this. We should also have a parameter that can force it like after contribution is made and things like that

**Comment by BrendanEich** [comment]
General principle is we have to show the user the last known balance anyway, so should not seem to say "insufficient funds" if we can't refresh. This implies deferring a true insufficient funds limit until later; is that going to be hard?
