### ISSUE TITLE
[Android] Verified check mark shown on rewards page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8675]
## Description 
 Verified check mark shown on rewards page

## Steps to reproduce 
Not sure about steps but I was on rewards page and backgrounded the app a couple of times after bringing it to focus and third time when I opened I got verified pub check mark on rewards page

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/76607753-84475f80-653a-11ea-9921-50eed98f9fdf.png)

## Expected result
![image](https://user-images.githubusercontent.com/17010094/76607806-9cb77a00-653a-11ea-9dce-ffbc02b13576.png)

## Issue reproduces how often 
Intermittent

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Pixel 3XL
   - Android version: 10
   
## Brave version
1.5.109 GPS Beta build 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by anthonypkeane** [comment]
closing as the new setting page will fix this
