### ISSUE TITLE
Decouple credentials logic from promotions

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#8677]
Right now we have `promotion_creds` table that handles privacy pass generation of unblinded tokens. Because we will be using this approach for other things we need to decouple it from promotions. We should take existing table rename it to `tokens_creds` and add fields `reference_id` (will be used to save promotion id or any other id's that are needed for finishing / retrying this flow. We also need to add `type` that will be used to know which flow to continue when unblinded tokens are done.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.8.82 Chromium: 81.0.4044.113 (Official Build) dev (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4960

Test plan 1:
<img width="1188" alt="PR4960-testplan1" src="https://user-images.githubusercontent.com/28145373/79911418-52a19e00-83ee-11ea-8d5a-ee08e2b6e024.png">

Test plan 2 (testing also done with https://github.com/brave/brave-browser/issues/9065#issuecomment-617390081):
<img width="1188" alt="PR4960-testplan2a" src="https://user-images.githubusercontent.com/28145373/79911462-677e3180-83ee-11ea-9c3c-2702e461cfc7.png">
<img width="1167" alt="PR4960-testplan2b" src="https://user-images.githubusercontent.com/28145373/79911472-6947f500-83ee-11ea-85ec-dddfc9f25c75.png">
<img width="389" alt="testplan2c" src="https://user-images.githubusercontent.com/28145373/79911474-6a792200-83ee-11ea-959e-5e14f1a40a83.png">

Test plan 3:
<img width="1188" alt="testplan3" src="https://user-images.githubusercontent.com/28145373/79911487-6f3dd600-83ee-11ea-8cbb-73e5fbecb2bd.png">
