### ISSUE TITLE
convertToBlob farbling

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#8682]
Chromium supports a non-standard extension to the offscreen canvas API called `convertToBlob` which could be used to get access to the unfarbled canvas contents. We should patch this API in the same way as `toDataUrl` and `toBlob`.

**Comment by bsclifton** [comment]
@pilgrim-brave any QA needed for this?  If so, can you add steps here and label with `QA/Yes`. If not, can you share why (ex: covered by automated tests) and label with `QA/No`. Thanks! 😄

**Comment by rebron** [comment]
@LaurenWags I think we should stick with farbling. Maybe for relnotes: "Enhanced fingerprinting protection [or privacy?] by farbling convertToBlob
