### ISSUE TITLE
cosmetic blocking flag causes shields ad toggle to not work correctly

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8688]
## Description 

If you enable the cosmetic blocking flag (you must do this manually on 1.5.x, but it is enabled by default on 1.7.x), and you change the cross site trackers toggle to OFF, ads do not start appearing on web pages as expected. You must toggle shields off entirely.

Note - if you disable cosmetic blocking flag, this is not an issue, the Cross-site trackers toggle works as expected.

## Steps to Reproduce

   1. If using 1.5.x, enable the brave://flags/#brave-adblock-cosmetic-filtering flag. If using 1.7.x it should be enabled by default.
   2. Navigate to a site like slashdot.org --> ads not displayed as expected.
<img width="935" alt="Default shields - cosmetic blocking flag enabled" src="https://user-images.githubusercontent.com/28145373/76648481-282e0c80-6535-11ea-88ae-1e9ae99a40f8.png">

   3. Open shields, toggle off `Cross-site trackers blocked`.
--> ads are not displayed on the page
<img width="934" alt="ad block toggled off - cosmetic blocking enabled" src="https://user-images.githubusercontent.com/28145373/76648495-2bc19380-6535-11ea-9737-71cf2457dded.png">

   4. Toggle shields off entirely.
--> now ads are displayed on the page
<img width="935" alt="shields off entirely - cosmetic blocking enabled" src="https://user-images.githubusercontent.com/28145373/76648501-2ebc8400-6535-11ea-9c34-163e44d2404b.png">

If you disable the brave://flags/#brave-adblock-cosmetic-filtering, then the `Cross-site trackers blocked` toggle begins working as expected (after browser restart. 

## Actual result:
When cosmetic blocking flag is enabled and you toggle `Cross-site trackers blocked` OFF, sites do not show ads as expected 

## Expected result:
Toggling `Cross site trackers blocked` to OFF should show ads regardless of the cosmetic blocking flag setting:
<img width="929" alt="ad block toggled off - cosmetic blocking disabled" src="https://user-images.githubusercontent.com/28145373/76648628-6d523e80-6535-11ea-975f-0adfe7e5c7cf.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.5.111 Chromium: 80.0.3987.132 (Official Build) (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | macOS Version 10.14.6 (Build 18G3020)

Brave | 1.7.58 Chromium: 80.0.3987.132 (Official Build) dev (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.4.x n/a, but yes to 1.5.x
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? unsure but probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? disabling shields entirely is the solution
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

reproduces on other sites like buzzfeed.com, etc.

**Comment by LaurenWags** [comment]
for comparison, here's how the same site behaves when cosmetic blocking flag is Disabled on brave://flags

Default shields:
<img width="933" alt="Default shields - cosmetic blocking disabled" src="https://user-images.githubusercontent.com/28145373/76648824-ccb04e80-6535-11ea-9754-20702f29ccaa.png">

Only `Cross-site trackers blocked` toggled off:
<img width="929" alt="ad block toggled off - cosmetic blocking disabled" src="https://user-images.githubusercontent.com/28145373/76648837-d639b680-6535-11ea-856b-d57024b2f602.png">

Shields off entirely:
<img width="933" alt="shields off entirely - cosmetic blocking disabled" src="https://user-images.githubusercontent.com/28145373/76648844-dc2f9780-6535-11ea-9a19-e44f4ee64435.png">

**Comment by LaurenWags** [comment]
cc @rebron @kjozwiak @bsclifton as this will be an issue in 1.5.x, but the flag must be enabled manually on 1.5.x. we should fix this for 1.7.x release though.

**Comment by pes10k** [comment]
@LaurenWags is the expected behavior here to tie cosmetic filtering to the Cross-site trackers toggle?  If so, i'd vote against that, since there is (in almost all cases) no connection between the cosmetic filtering and tracking.

Would either of the following solutions work?
1) keeping the flag for cosmetic filtering, enabled by default, but which people can turn off globally if they really don't want it
2) add a shields toggle for cosmetic filtering

FWIW, i have a weak pref against putting cosmetic filtering in shields, since the shield metaphor suggests privacy-protections

**Comment by LaurenWags** [comment]
@pes10k those are probably better aimed at product 😄 I was just confused when I toggled cross-site trackers (the "ad" toggle) and ads didn't display - until I tracked it down to the cosmetic blocking flag.

@rebron could you take a look @pes10k suggestions?

**Comment by ryanbr** [comment]
Having a separate shields switch for cosmetic filtering would be helpful for debugging purposes if there an issue with a cosmetic filter we could track down more quickly

**Comment by pes10k** [comment]
I've got no beef with another toggle, its just a matter of slotting it in w/ the other priorities.  I know @tomlowenthal is also pushing for more shield configurability.  @ryanbr could you create an issue for it, if it doesn't exist here, and we can triage and work through it from there?

**Comment by rebron** [comment]
cc: @antonok-edm

**Comment by rebron** [comment]
Closing. No longer valid with fix to https://github.com/brave/brave-browser/issues/8475. 
`Allowing all trackers and ads` in the `Advanced View` of Shields, yields the desired result of showing ads on Slashdot.
