### ISSUE TITLE
Archlinux/Manjaro missing on Download page

### ISSUE THREAD

**Issue by itsTyrion** [brave/brave-browser#8690]
## Description 
There's brave / brave-beta packages in the pacman (Archlinux'/Manjaro's package manager) repository ("community" branch), but no mention of those packages on the [linux download page](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux). 

## Steps to Reproduce
Doesn't apply

## Actual result:
Doesn't apply

## Expected result:
The packages / commands should be added to the documentation page

## Reproduces how often: 
No steps to reproduce

## Brave version (brave://version info)
Doesn't apply

## Version/Channel Information:
Doesn't apply

## Miscellaneous Information:
The command to install the brave package is `sudo pacman -Sy brave`/`sudo pacman -Sy brave-beta`
The -S flag on pacman stands for sync (sync installation with the current version (install/update/reinstall), the y flag updates the local db before, in apt-ish that's `sudo apt update && sudo apt install foobar`

The packages seem to be actively maintained/updated.

@fmarier You said should feel free to tag you in https://community.brave.com/t/archlinux-manjaro-missing-on-download-page/110997

**Comment by afiestas** [comment]
Hey, I might be horribly wrong but I think that there are no brave packags in the official repos:
[Archlinux package search](https://www.archlinux.org/packages/?sort=&arch=any&arch=x86_64&repo=Community&repo=Community-Testing&repo=Core&repo=Extra&repo=KDE-Unstable&repo=Multilib&repo=Multilib-Testing&repo=Testing&q=brave&maintainer=&flagged=)

**Comment by itsTyrion** [comment]
> Hey, I might be horribly wrong but I think that there are no brave packags in the official repos:
> [Archlinux package search](https://www.archlinux.org/packages/?sort=&arch=any&arch=x86_64&repo=Community&repo=Community-Testing&repo=Core&repo=Extra&repo=KDE-Unstable&repo=Multilib&repo=Multilib-Testing&repo=Testing&q=brave&maintainer=&flagged=)

![image](https://user-images.githubusercontent.com/17730120/76684173-f89d0400-6609-11ea-9b82-c4d53b9bea80.png)

**Comment by salifm** [comment]
Brave is on official repos in Manjaro, but not in Arch. On Arch you have to install `brave-bin` from AUR.

**Comment by bsclifton** [comment]
Unfortunately, Brave is not officially packaged (yet). I believe the unofficial URL you can use is:
https://aur.archlinux.org/packages/brave/

We're tracking official support with this issue: https://github.com/brave/brave-browser/issues/1950

**Comment by fmarier** [comment]
Reopening since this issue is about adding Manjaro/Arch to the unofficial builds section of the installation instructions: https://brave-browser.readthedocs.io/en/latest/installing-brave.html#unofficial-packages

**Comment by fmarier** [comment]
@salifm What's the equivalent command to install Brave in a brand new Arch installation?

Is it just `sudo pacman -Sy brave-bin` or do you also need to enable AUR somehow?

**Comment by NumDeP** [comment]
Hi @salifm how is it Brave is on the official repos of Manjaro and not in Arch, surely if it were in Arch then it can be easily adoptable in Manjaro, as is with typical software in Arch? One other thing, who's maintaining it constantly?

**Comment by programmer-04** [comment]
@NumDeP Although they're pretty similar, Manjaro has its own software repository. From its [wiki](https://wiki.manjaro.org/index.php?title=Manjaro:_A_Different_Kind_of_Beast), 

>  To ensure continued stability and reliability, Manjaro utilises its own dedicated software repositories. With the exception of the community-maintained Arch User Repository (AUR), Manjaro systems do not –and cannot– access the official Arch repositories. More specifically, popular software packages initially provided by the official Arch repositories will first be thoroughly tested (and if necessary, patched), prior to being released to Manjaro's own Stable Repositories for public use. 

If needed, I could help with the wiki documentation.

**Comment by fmarier** [comment]
The Manjaro installation instructions are now live on the page: https://brave-browser.readthedocs.io/en/latest/installing-brave.html#unofficial-packages

Thanks @programmer-04 !
