### ISSUE TITLE
[Android] Rewards page: promotion expiry date is not correct

### ISSUE THREAD

**Issue by gdregalo** [brave/brave-browser#8692]
## Description 
 Rewards page: promotion expiry date is not correct (see attached picture)

![Screenshot_20200305-163256](https://user-images.githubusercontent.com/37560650/76686194-12315200-65f0-11ea-96e5-d2e3df084fa3.png)

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
@gdregalo this looks fixed on 1.5.111 x64 build
![image](https://user-images.githubusercontent.com/17010094/76759230-456f0f00-67b1-11ea-9f65-539f338db284.png)

Also moved to Android 1.5.x milestone as it was wrongly added to Desktop milestone

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.113 x64 stable build
- Verified promotion page shows correct expiry date
![image](https://user-images.githubusercontent.com/17010094/77144984-51a6e500-6aad-11ea-9d61-a42caf52b49a.png)
-------
Verification passed on Samsung Ta A with Android 9.0 running 1.5.113 x64 stable build
- Verified promotion page shows correct expiry date
![image](https://user-images.githubusercontent.com/17010094/77145654-27eebd80-6aaf-11ea-93ec-ed1bde755039.png)
