### ISSUE TITLE
HTTPS Upgrades doesn't avoid mixed content error

### ISSUE THREAD

**Issue by mKoonrad** [brave/brave-browser#8693]
## Description 
HTTPS Upgrades doesn't avoid mixed content error. When on page I have http image link that redirects to other https link I can see mixed content error.
![image](https://user-images.githubusercontent.com/11725227/76687814-d3b78980-6627-11ea-83d7-62759175d076.png)
![image](https://user-images.githubusercontent.com/11725227/76687885-44f73c80-6628-11ea-99d4-4ac19732941c.png)

When I have installed on my Brave browser additional HTTPS Everywhere extension (it should do the same thing) I can see on network timeline just second https request and browser doesn't cause mixed content error.

## Steps to Reproduce
   1.  Open page with http link that redirect to other https resource. I can't provide example link because it's example from my webmail page.

## Actual result:
Mixed content error

## Expected result:
No mixed content issue like with installed HTTPS Everywhere extension

## Reproduces how often: 
Every time in cases above

## Brave version (brave://version info)
Brave	1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
Revision	fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS	Windows 10 OS Version 1909 (Build 18363.720)
JavaScript	V8 8.0.426.26
Flash	(Wyłączone)
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Command Line	"C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=NotificationTriggers,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,AutofillServerCommunication,AudioServiceOutOfProcess,SmsReceiver,WebXR,VideoPlaybackQuality,WebXrGamepadModule --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path	C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\User\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations	5e3a236d-4113a79e

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? Yes
- Is the issue reproducible on the latest version of Chrome?  Yes

**Comment by bsclifton** [comment]
This should be fixed now with https://github.com/brave/brave-core/pull/4537 😄 

The fix is in 1.7 and later. 1.7 will be released early next week! You can also try a release candidate here:
https://github.com/brave/brave-browser/releases/tag/v1.7.90
