### ISSUE TITLE
Green or red https lock

### ISSUE THREAD

**Issue by brechtgijsens** [brave/brave-browser#8694]
## Description 
When you visit an https adres the lock is white, maybe it would be easier to see if this turned green.
![image](https://user-images.githubusercontent.com/29354411/76691257-58ff6600-6649-11ea-9938-d71fb52325ce.png)

An insecure website is also white, this would be more alarming when it is red.
![image](https://user-images.githubusercontent.com/29354411/76691301-b4c9ef00-6649-11ea-904d-067ab7079cd0.png)

I use the desktop version v1.4.96

Would it be possible to add this feature?

**Comment by VukAnd** [comment]
Normal insecure could be orange maybe, while warning insecure could be red?

![image](https://user-images.githubusercontent.com/46850780/77786754-9eb32a00-705e-11ea-93d6-c964515c475d.png)
![image](https://user-images.githubusercontent.com/46850780/77786772-a83c9200-705e-11ea-8718-9bc183980a4e.png)

**Comment by bsclifton** [comment]
cc: @bradleyrichter @diracdeltas

**Comment by diracdeltas** [comment]
We had this in the old muon browser at some point. I would be more in favor of keeping the secure icon how it looks currently and changing the insecure state to be red or something. @tomlowenthal

**Comment by rebron** [comment]
@diracdeltas @tomlowenthal We're going to label as wontfix, ok to close?

**Comment by diracdeltas** [comment]
@rebron sgtm

**Comment by rebron** [comment]
Closing as wontfix. Discussed and our preference is to keep as is.
