### ISSUE TITLE
Allow a shield toggle to enable/disable cosmetic filtering

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#8702]
## Description 
Having another shield option to allow us to disable/enable cosmetic filtering on a per site basis.

Was discussed here; https://github.com/brave/brave-browser/issues/8688

To be used to help debug webcompat issues (by us and by the user), an easy option to disable cosmetic filter to help where we need to. Cosmetic filter default should stay enabled by default.

## Miscellaneous Information:

uBO has a similar filter option, https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering

If a cosmetic filtering shield option isn't viable, making a custom option in `chrome://settings/content/siteDetails` might be a middle ground (just an idea).

**Comment by tomlowenthal** [comment]
@ryanbr How would you describe the functionality of the cosmetic filter from the perspective of the person using the browser?

**Comment by rebron** [comment]
cc: @karenkliu @pes10k @antonok-edm

**Comment by ryanbr** [comment]
Using cosmetic filtering, allowing the user to collapse elements on site, removing white space where needed. So cleaning up a site and making it more readable.

**The potential downsides:**

1. **Unintentional:** Occasionally this can cause issues where whitespace collapsing may inadvertently remove content (that shouldn't be blocked). This is where a site would roll out a div element, without relising it's causing issues with Adblock users. Or we have a bad site-specific cosmetic  filter being used in Easylist that should be removed.

2. **Intentional:** A site intentionally uses a cosmetic filter to check for Adblock users, to either limit or disable site functionality based on a simple cosmetic check.

We can get around cosmetic filtering in Easylist issues when we're notified. But for the end user having a quick option to just disable this while still keeping the rest of the Shield blocks on site tracking (or until a fix is deployed) would be great.

**Comment by antonok-edm** [comment]
There is already a toggle in `brave://flags`, called `#brave-adblock-cosmetic-filtering`. However, it can't be changed per-website and changing it and requires a browser restart.

I think it's important to get a consensus from the product team on where this toggle should go and how it should work - a Shields panel option has already been proposed and implemented for the original cosmetic filtering PR but was ultimately decided against and removed.

**Comment by pes10k** [comment]
@antonok-edm that initial decision (no shields toggle) was because, in the initial proposal, the original options were either "default on, with 1p vs 3p distinctions" (i.e. what we shipped) or "default off, with shields toggle".

But now that we're default on, I think a shields toggle would be fine with
- off
- 3p (default)
- all

options.

**Comment by rebron** [comment]
Closing this one out. Fixed with -> https://github.com/brave/brave-browser/issues/8475
