### ISSUE TITLE
[Android] Other device name is not visible on Sync sheet in dark theme

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8703]
## Description 
Other device name is not visible on Sync sheet on dark theme

## Steps to reproduce 

   1. Set device theme to dark
   2. Create a sync chain or join an existing sync chain
   3. Other device name is not visible

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/76754692-8ca4d200-67a8-11ea-9a32-9359d0fb1b80.png)

## Expected result
![Screenshot_20200316-170525](https://user-images.githubusercontent.com/17010094/76754821-caa1f600-67a8-11ea-8b2b-2718b9c313d6.jpg)

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No 
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version:10
   
## Brave version
1.5.111 x64 stable build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome?  NA

**Comment by srirambv** [comment]
+1 from @AlexeyBarabash  via https://github.com/brave/brave-browser/issues/10864

**Comment by AlexeyBarabash** [comment]
Oh, this is already filed :)
Thanks @srirambv

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.12.108
- Verified other devices in the list is visible when the theme is set to dark
![image](https://user-images.githubusercontent.com/17010094/89635505-fe3c0480-d89e-11ea-9360-4225ea18d3f9.png)

-------------
Verification passed on OnePlus 6T with Android 10 running 1.12.108
- Verified other devices in the list is visible when the theme is set to dark
![image](https://user-images.githubusercontent.com/17010094/89635461-e8c6da80-d89e-11ea-9518-b4a5879f2fb4.png)
