### ISSUE TITLE
[Android] Sync fail with "Cannot read property 'length' of undefined" 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8704]
## Description 
While testing #8642 ran into a situation where sync started erroring out with "Cannot read property 'length' of undefined" message

## Steps to reproduce 

   1. Clean install 1.5.111 x64 build
   2. Follow steps from #8642 and verify there is no crash
   3. After steps are done it starts showing error message

## Actual result 
ARM Device
![image](https://user-images.githubusercontent.com/17010094/76756556-e9ee5280-67ab-11ea-91d7-d52b869bc161.png)
Tablet
![image](https://user-images.githubusercontent.com/17010094/76756646-1efaa500-67ac-11ea-8ab5-66c7a3363475.png)

## Expected result
No error message. Sync should work fine

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone and Tablet
   - Android version: 9 and 10
   
## Brave version
1.5.111

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Marking it for Android 1.5.x release. Please move it if required @SergeyZhukovsky @anthonypkeane

**Comment by AlexeyBarabash** [comment]
I can confirm I can reproduce the issue.
I had to restart browser after executing STR from https://github.com/brave/brave-browser/issues/8642 .

**Comment by AlexeyBarabash** [comment]
There are an easier STR:
1. Create sync chain on desktop
2. Connect Android device to the chain
3. Wait for 2 device appear in chain on Android
4. Close Android app from carousel
5. Open Android app
6. Go to settings => sync

**Comment by AlexeyBarabash** [comment]
Error happens on this line 
https://github.com/brave/sync/blob/master/client/sync.js#L56
because Android  does not save and give the deviceIdV2 value.

Solution is to  add support of deviceIdV2, save/load this string pref on `save-init-data` / `got-init-data` .

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.113 x64 stable build
- Verified steps from https://github.com/brave/brave-browser/issues/8704#issuecomment-599550335
-------
Verification passed on Samsung Tab A with Android 9.0 running 1.5.113 x64 stable build
- Verified steps from https://github.com/brave/brave-browser/issues/8704#issuecomment-599550335
-------
