### ISSUE TITLE
[Android] Safe Browsing doesn't work in android-core (Follow up to #8381)

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8705]
## Description 
Safe Browsing isn't blocking anything in android core.

## Steps to reproduce 

   1. Visit https://testsafebrowsing.appspot.com/
   2. Try all of the links in the "Webpage Warnings"

## Actual result 
Not blocked.

## Expected result
Should be showing the red interstitial pages just like on desktop.

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? NA

## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.5.x Android-core release 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Follow up to #8381

**Comment by OnlinePlayer865** [comment]
Any updates to this issue? I think it would be good to have on Mobile, at least on Android, maybe iOS, since this feature is on Desktop. With the ability for users to turn it off of course. I for one would have it on just to be on the more secure side.

**Comment by bsclifton** [comment]
Hi there @OnlinePlayer865 - we are making progress 😄 We're wrapping up this feature on iOS (see https://github.com/brave/brave-ios/pull/1339) and are looking to merge soon (iOS product version 1.19?). We can then look at doing this on Android after taking care of some other priority work. I believe @jumde would be able to look at this in the next few months

**Comment by OnlinePlayer865** [comment]
Perfect! Didn't think to check the iOS page. Thank you for the info!

**Comment by fmarier** [comment]
As mentioned in the [security review](https://github.com/brave/internal/issues/632), we decided against having our own implementation and went with Apple's built-in one.

For Android, we could either reuse the desktop implementation (this is what Firefox does on Android) or go with the [SafetyNet API](https://developer.android.com/training/safetynet/safebrowsing).

**Comment by ByJumperX4** [comment]
Any progress on this ? Brave still has no safebrowsing working on Android :/

**Comment by bsclifton** [comment]
We'll be starting work on this soon 😄 Doing some pre-work to see what is needed. We had taken a first step with https://github.com/brave/brave-browser/pull/8664 (which looks correct) but that didn't work

I verified our build servers are setting the `safebrowsing_api_endpoint` value. Will update when I find out more.

**Comment by stephendonner** [comment]
## Verified `PASSED` using `1.48.134` on a `Google Pixel XL` (`arm64`) running `Android 9`

### Steps:
1. installed `1.48.134`
2. launched Brave
3. opened `brave://flags`
4. set `Safe Browsing` to `Enabled`
5. relaunched Brave
6. tapped the 3-dots menu
7. tapped `Settings`
8. tapped `Brave Shields & privacy`
9. tapped on `Safe Browsing` (defaulted to `Off`)
10. tapped on `Standard protection`
11. loaded `https://testsafebrowsing.appspot.com/`
12. went through the `Webpage warnings` tests

#### Confirmed I got `Safe Browsing` warnings for each condition except `malware, bad assets` (will investigate)

`phishing warning` | `malware warning` | `malware, bad subresource` | `unwanted software warning` | `malware, bad assets` | `billing warning`
-------|-------|-------|-------|-------|-------
![Screenshot_20230122-015304](https://user-images.githubusercontent.com/387249/213909861-2c8318ea-baf3-47a7-b3e8-a74f838c5bb6.png) | ![Screenshot_20230122-015318](https://user-images.githubusercontent.com/387249/213909863-a08bd5a9-a870-4a81-930e-388a05fc31d7.png) | ![Screenshot_20230122-015325](https://user-images.githubusercontent.com/387249/213909864-20920086-b9c1-4a1e-8841-0e23c10af5af.png) | ![Screenshot_20230122-015332](https://user-images.githubusercontent.com/387249/213909865-83aae8b8-d833-4a7f-bc44-9e5f79005687.png) | (loaded assets; shouldn't have)  |  ![Screenshot_20230122-015353](https://user-images.githubusercontent.com/387249/213909866-dcb32220-1fe4-4fc2-9d4b-e6aecc9fad19.png)
