### ISSUE TITLE
Aww snap on youtube playback, doesn't happen on vimeo / other video sites

### ISSUE THREAD

**Issue by Twiggeh** [brave/brave-browser#8706]
## Description 

Playing YouTube videos results in an aww snap after some random period of time ... Sometimes it happens after 20 seconds, sometimes it takes multiple hours for it to crash. It happens even after I've cleared all Browser data, after a clean install and in a private window.
brave://crashes is empty, I don't know where to look for the "Aww snap Issues".

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

https://imgur.com/bG7Rmuw.png

## Expected result:
No "aww snap"

## Reproduces how often: 

No steps to reproduce

## Brave version (brave://version info)

Brave | 1.4.96 Chromium: 80.0.3987.132 (Official Build) unknown (64-bit)
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Linux
JavaScript | V8 8.0.426.26
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Command Line | /usr/lib/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,WebXR,VideoPlaybackQuality,WebXrGamepadModule --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /usr/lib/brave/brave
Profile Path | /home/twiggeh/.config/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the dev channel? Not sure
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by outforpublic** [comment]
Can you attempt to try the nightly version of brave?

More information at https://brave-browser.readthedocs.io/en/latest/installing-brave.html#nightly-channel-installation

**Comment by kjozwiak** [comment]
@Twiggeh next time you run into the a webview crash, mind checking `brave://crashes` and sharing the the `Crash Report ID` with us? Should look similar to the following example:

<img width="839" alt="Screen Shot 2020-03-25 at 5 15 08 PM" src="https://user-images.githubusercontent.com/2602313/77586265-43493680-6ebc-11ea-95cc-5a2ec09dfe4b.png">

**Comment by Twiggeh** [comment]
@kjozwiak "aww snap" error doesn't generate a crash report ...

**Comment by Twiggeh** [comment]
@outforpublic nightly has the same issue ...
It seems all javascripty things have crashing issues - discord client crashes on screenshare and on voicecalls, video playback in the embedded player also crashes the client. The webpage version is much more stable, but still crashes.
Discord's server for bugreports doesn't work and those discord crashes also do not produce any kind of logs. Only in xfce I got some kind of log in dmesg that happend on those crashes 
`[ 5787.347494] SGI_video_sync[13453]: segfault at e6 ip 00005584030c920d sp 00007ffb491ab840 error 6 in Discord[5583ffc28000+53ad000]`

The thing is also that it doesn't crash gracefully, but the whole system locks up, every other program stutters / gets blocked.

I'm putting this here because the crashing behavior is the same (and maybe it is useful somehow?)

The crashes also become more frequent when I am working on animations, aka playing back animations in Krita makes this error appear ~5min

**Comment by rebron** [comment]
@Twiggeh Can you update to 1.8.86? This maybe an issue with Chromium 80 and resolved in the latest Chromium 81.

**Comment by Twiggeh** [comment]
Has not been fixed with the latest release, Brave now displays this error message on crashing `SIGILL`

**Comment by iefremov** [comment]
@Twiggeh please reopen if this is still an issue
