### ISSUE TITLE
Eliminate network leaks

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#871]
Several processes in Chromium call out the OS APIs which can make independent network requests. Extensions can make network requests. Plugins like Widevine might make network requests. The proxy support in Chromium is explicitly designed for reachability not privacy — Chromium makes no attempt to ensure that all network connections go out via the user-set proxy.

We should ensure that we can confidently control every network request caused by Brave.

**Comment by pes10k** [comment]
I dont think this issue still useful?  The actionable parts are already captured by other, more specific issues.  I'm going to close, though if others disagree no fight from me to reopen it
