### ISSUE TITLE
Rewards: Update "Verify Wallet" banner to include redemption utility option

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#8710]
## Description 

With the [TAP redemption utility implementation that is now available in Nightly,](https://brave.com/brave-and-tap-network-partnership-connects-consumers-and-brands-via-blockchain/) it may be a good time to update the Verify Wallet banner copy to include a bullet point to explain that users that verify their wallets can redeem BAT for gift cards through the TAP storefront. 

A bullet with: 

> _Redeem Basic Attention Tokens (BAT) for real-world rewards offered by over 250,000 top brands and merchants in the TAP Network._

I pulled the bullet above from the blog post. 

It would be good to include this, as it opens up additional utility and functionality for users that are interested in going forward with wallet verification. 

## Steps to Reproduce

   1. Open brave://rewards in v1.7 
   2. Click to "Verify user wallet" 
   3. See current copy: 

![Screenshot from 2020-03-16 11-10-58](https://user-images.githubusercontent.com/8979240/76788375-06709780-6778-11ea-9ba4-503fc17915d8.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
cc @mandar-brave

**Comment by Miyayes** [comment]
This modal has since been redesigned and replaced, so closing out this issue!
