### ISSUE TITLE
Amazon Seller Central account form doesn't show anything when Shields are up

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#8712]
## Description 

While trying to close my Amazon account, I discovered that the options don't show with Shields up.
Depending on the state of your amazon seller account, the yellow content area shows different options. For example, sometimes seller accounts can't be closed because of outstanding balances or stranded inventory, so the page would detect that and the "close my account" button would be disabled, and that area would show steps I need to take before closing my account.

Instead, with Shields up that area was completely blank.

## Steps to Reproduce

   1. OAuth/login to your Amazon Seller Account
   2. Go to close your account page
   3. Area with close account options is blank

## Actual result:

I didn't grab a screenshot of this, but basically the page has headers and looks normal, except the part where they inject content specific to your seller account is blank.

## Expected result:
The content area should show options like this:
![image (4)](https://user-images.githubusercontent.com/2388823/76795787-455a1980-6787-11ea-9e20-c1aea1a6760c.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Release

## Version/Channel Information:

All channels 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

**Comment by ryanbr** [comment]
@karenkliu are you still seeing this issue? Is there a specific shield option causing the blank page?

**Comment by karenkliu** [comment]
@ryanbr Unfortunately I'm not able to test this issue anymore because I closed my seller account, so I don't have access to that page. If we were to continue chasing this issue, I recommend that we create an Amazon seller account to get access to the account page again.
