### ISSUE TITLE
[Android] Settings reset during migration

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8713]
## Description 
Settings reset during migration 

### Bottom Toolbar
   1. Install tabs 1.5.9
   2. Go to Settings > Appearance
   3. Change `Enable bottom toolbar` to off.
   4. Restart. Confirm you see the change.
   5. Upgrade to core 1.5.111.
   6. Launch

### Private tab SE
  1. Install 1.5.9 via GPS
  2. Open a PT and set DDG as default SE
  3. Upgrade to 1.5.111
  4. Default SE for private tab is reset to Google

### Background Media Play
  1. Install 1.5.9 via GPS
  2. Enable Background media play via settings and relaunch the browser
  3. Upgrade to 1.5.111
  4. Background media play is reset to default (disabled)

## Actual result 
Settings are not migrated upon upgrade

## Expected result
Settings should be retained during migration

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.5.9 -> 1.5.111

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Reproduced on Asus Zenfone (x86) and Google Pixel 3 (ARM)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.113 x64 stable build 
- Verified `Bottom toolbar` setting is retained after upgrade
- Verified `Background media play` setting is retained after upgrade
- Private SE setting isn't retained. Logged followed up #8768
- Verified all other settings are retained during upgrade
-------
Verification passed on OnePlus 6T with Android 10 running 1.5.113 x64 stable build 
- Verified `Background media play` setting is retained after upgrade
- Private SE setting isn't retained. Follow up issue #8768
- Verified all other settings are retained during upgrade
-------
