### ISSUE TITLE
https://coronavirus-map.com/ Doesn't work with Fingerprinting

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#8714]
## Description 

The map on https://coronavirus-map.com/ doesn't work with cross-site fingerprinting blocked, but will work if all fingerprinting is allowed.

## Steps to Reproduce

   1.  Go to https://coronavirus-map.com/
   2. The map doesn't work with cross-site fingerprinting blocked

## Actual result:

![Screen Shot 2020-03-16 at 4 21 46 PM](https://user-images.githubusercontent.com/2388823/76807689-70059b80-67a2-11ea-945f-b422c9171ef8.png)

## Expected result:
![Screen Shot 2020-03-16 at 4 22 04 PM](https://user-images.githubusercontent.com/2388823/76807696-73008c00-67a2-11ea-9e4d-382ab8f1fb06.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 1.8.12 Chromium: 80.0.3987.132 (Official Build) nightly (64-bit)

## Version/Channel Information:
All versions

**Comment by ryanbr** [comment]
See: https://github.com/brave/brave-browser/issues/8630

**Comment by ryanbr** [comment]
Hey @karenkliu is this still an issue?

**Comment by karenkliu** [comment]
@ryanbr Now it seems to work!
