### ISSUE TITLE
Wayback 404 notice appears even when page loads overall

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#8716]
## Description 

Wayback 404 notice appears even though the page (or much of the page) loads. Occurs frequently on websites like Reddit, particularly if some component doesn’t fully load (notice the top right component in following screenshot), or a component takes a little longer to saturate with data. However, the overall page loads and does not appear to be an overall "404". 

## Steps to Reproduce

Navigate directly to a Reddit page such as https://reddit.com/r/BATProject or https://reddit.com/u/SOMEUSERNAME. 

**Estimate**: Occurs up to 10% of the time. 

**Possible observation (not necessarily reliable):** It might occur more frequently when one is browsing the web very intensely and quickly across tabs, or when one requests a page that is not cached by Reddit (e.g., a user's individual comment history). 

## Brave version (brave://version info)

Version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)

## Version/Channel Information:

Release channel 

## Other Additional Information:

uBlock Origin is also installed. 

![image](https://user-images.githubusercontent.com/11497541/76815810-03f05b00-67d5-11ea-9634-c1d0ba0dfe82.png)

**Comment by jonathansampson** [comment]
I was able to reproduce this with a few refreshes. The server eventually responded with a 504.

```
Request URL: https://www.reddit.com/r/BATProject/
Request Method: GET
Status Code: 504 
Remote Address: 151.101.57.140:443
Referrer Policy: no-referrer-when-downgrade
```

**Comment by bsclifton** [comment]
Wayback status is purely based on the HTTP code returned by the page

Per the spec, here are codes which trigger this infobar showing:
```cpp
  static base::flat_set<int> responses = {
      net::HTTP_NOT_FOUND,              // 404
      net::HTTP_REQUEST_TIMEOUT,        // 408
      net::HTTP_GONE,                   // 410
      451,                              // Unavailable For Legal Reasons
      net::HTTP_INTERNAL_SERVER_ERROR,  // 500
      net::HTTP_BAD_GATEWAY,            // 502,
      net::HTTP_SERVICE_UNAVAILABLE,    // 503,
      net::HTTP_GATEWAY_TIMEOUT,        // 504,
      509,                              // Bandwidth Limit Exceeded
      520,                              // Web Server Returned an Unknown Error
      521,                              // Web Server Is Down
      523,                              // Origin Is Unreachable
      524,                              // A Timeout Occurred
      525,                              // SSL Handshake Failed
      526                               // Invalid SSL Certificate
  };
```

cc: @rebron for triage

**Comment by rebron** [comment]
closing as wontfix. Per codes above, working as expected.

**Comment by benwiggins** [comment]
It is extraordinarily shitty that Brave explicitly says "404" in the infobar when triggered by some 14 response codes that are *not* 404.

**Comment by jonathansampson** [comment]
@benwiggins Good feedback. As an engineer, I agree with you that 5xx errors aren't 4xx errors, and 404 is different from other 4xx errors. That said, the average user understands "404" as "The wasn't working any longer." This tool isn't meant to be developer-oriented, but instead user-oriented. All that said, it may be necessary to consider losing the "404" entirely, and simply go with "Sorry, that page is missing."

**Comment by jonathansampson** [comment]
Conversation taking place here: https://github.com/brave/brave-browser/issues/8959

**Comment by bsclifton** [comment]
@benwiggins quick heads up that you can turn this off actually, if it's something you don't find useful. Preference is under brave://settings/braveHelpTips

In either case, thanks for the feedback 😄
