### ISSUE TITLE
When a user of today's Brave updates to Brave Core, all data should be imported automatically (without prompting)

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#872]
When a user of today's Muon-based Brave browser updates to Brave Core (via the current browser's autoupdate system), Brave Core should automatically trigger an import of all data and settings from the old browser into the new browser, for continuity. 

This process should be the same as what would happen if a user were to manually download/install Brave Core, and then choose to import data from Brave.

**Comment by bsclifton** [comment]
Closing as the individual tasks to accomplish this are captured in https://github.com/brave/brave-browser/projects/12
