### ISSUE TITLE
Redirecting AMP to canonical pages

### ISSUE THREAD

**Issue by AndriusA** [brave/brave-browser#8720]
## Description 

Give users an option to disable AMP by automatically redirecting to the canonical pages when possible. AMP standard  manifests that AMP pages contain a `<link rel="canonical" ...>` element pointing to the canonical page, making it straightforward to discover it and redirect. 

Interest from community:

- https://community.brave.com/t/de-amp-pages-automatically/47258
- https://www.reddit.com/r/brave_browser/comments/bpzrsk/disable_amps/
- https://www.reddit.com/r/brave_browser/comments/8n22ax/can_you_disable_google_amp_pages/
- https://www.reddit.com/r/brave_browser/comments/aocio0/what_prevents_you_from_using_brave_browser/

## Steps to Reproduce

Visit any AMP page

## Actual result:

See mobile-optimised AMP version of the content

## Expected result:

See the original content

## Reproduces how often: 

Easily reproduced

**Comment by Peacock365** [comment]
Perhaps relevant in this context:

https://github.com/bromite/bromite/blob/master/build/patches/Inject-scripts-for-AMP-tracking-ads-and-video.patch

**Comment by Dev-i-l** [comment]
+1 amp pages are really annoying

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
Any update on this?

**Comment by ChildishGiant** [comment]
In the meantime there's this site (https://www.amputatorbot.com/) but i really hope this gets implemented.
