### ISSUE TITLE
Amex chat is broken 

### ISSUE THREAD

**Issue by Northshoot** [brave/brave-browser#8721]
## Description 

After logging in to amex, the chat doesn't work even after disabling the shields.

## Steps to Reproduce

   1.  Go to https://global.americanexpress.com/
   2. login, click help
   3. watch chat wheel spin for ever

## Actual result:

nothing happens

## Expected result:

Chat button appear

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | macOS Version 10.15.3 (Build 19D76)
JavaScript | V8 8.0.426.26
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,AllowPopupsDuringPageUnload,AudioServiceOutOfProcess,SmsReceiver,WebXR,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,VideoPlaybackQuality,WebXrGamepadModule --flag-switches-begin --allow-insecure-localhost --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator,TabGroups --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
NO

- Does the issue resolve itself when disabling Brave Rewards?
NO

- Is the issue reproducible on the latest version of Chrome? 
NO

## Miscellaneous Information:

Need account on Amex

**Comment by rebron** [comment]
@Northshoot This one is a bit difficult as we have to have an Amex account to check, but we're digging into this. Just wanted to confirm you tried toggling Shields on and off and it still didn't work. It sounds like you did.

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
I don't have an Amex account either, this is a guess. but lets see

https://github.com/easylist/easylist/commit/db6a9602e573d977744d4df7e7642d64d24199e2

WIll be updated in the next 24-48hrs.

**Comment by ryanbr** [comment]
@Northshoot checking on this, is still problematic?

**Comment by Northshoot** [comment]
Hi, yes it doesn't work. if you ping me from brave email, happy to provide more details. I can see where it is potentially blocking from the headers.

**Comment by ryanbr** [comment]
Related issue (for the dashboard) https://github.com/brave/brave-browser/issues/9803

I got confirmation amex chat is now working, can you reconfirm @Northshoot ?

**Comment by Northshoot** [comment]
Should I test it on dev or any specific build?

**Comment by ryanbr** [comment]
Any build should work. We're still working on the cookie issues

**Comment by ryanbr** [comment]
@Northshoot  everything working now?

**Comment by Northshoot** [comment]
Hey, no it doesn't. I have sent support email to connect offline because since I don't want to share details publicly 🤷🏻‍♂️
