### ISSUE TITLE
npm vulnerability: `minimist`

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#8722]
## Description 
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jest [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jest > @jest/core > jest-runner > jest-jasmine2 >            │
│               │ jest-runtime > @jest/transform > jest-haste-map > sane >     │
│               │ @cnakazawa/watch > minimist                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1179                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

## Steps to Reproduce

   1. Have full setup of Brave
   2. run `npm run audit_deps` from root
   3. have a bad time

**Comment by bsclifton** [comment]
**\*Angry fist shaking at NPM vulnerability\***

**Comment by bsclifton** [comment]
Notes about attempted fix here:
https://github.com/brave/security/issues/101#issuecomment-600994528

Current status: not solved. Will need to revisit once deps are updated and it's fixable by `npm audit fix` (unless there is a better solution)

**Comment by bsclifton** [comment]
Almost there! Fixes in progress

**Comment by kjozwiak** [comment]
<img width="1352" alt="Screen Shot 2020-03-20 at 3 25 41 PM" src="https://user-images.githubusercontent.com/2602313/77199361-16151680-6abf-11ea-90b3-0fec44bd7a2f.png">

Awesome sir! Sent you a BAT ;)

**Comment by bsclifton** [comment]
Opening as this is still a problem actually

**Comment by bsclifton** [comment]
Should be completely resolved with https://github.com/brave/brave-core/pull/5013 and https://github.com/brave/brave-browser/pull/8788
