### ISSUE TITLE
[Android] Manual test run on Android ARM for 1.5.x Android core release

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8731]
## Installer

- [x] Check that installer is close to the size of the last release
- [x] Check the Brave version in About and make sure it is EXACTLY as expected

## Visual look

- [x] Make sure thereafter every merge
  - [x] No Chrome/Chromium words appear on normal or private tabs
  - [x] No Chrome/Chromium icons are shown in normal or private tabs

## Data
Pre-Requisite: Put previous build shortcut on the home screen. Also, have several sites 'Added to home screen' (from 3 dots menu) and then upgrade to new build
- [x] Verify that data from the previous build appears in the updated build as expected (bookmarks, etc)
- [x] Verify that the cookies from the previous build are preserved after upgrade
- [x] Verify shortcut is still available on the home screen after upgrade
- [x] Verify sites added to home screen are still visible and able to be used after upgrade
- [x] Verify sync chain created in the previous version is still retained on upgrade
- [x] Verify settings changes done in the previous version are still retained on upgrade

## Bookmarks

- [x] Verify that creating a bookmark works
- [x] Verify that clicking a bookmark loads the bookmark
- [x] Verify that deleting a bookmark works
- [x] Verify that creating a bookmark folder works

## Custom tabs

- [x] Make sure Brave handles links from Gmail, Slack
- [x] Make sure Brave works as custom tabs provide with Chrome browser
- [x] Ensure custom tabs work even with sync enabled/disabled

## Context menus

- [x] Make sure context menu items in the URL bar work
- [x] Make sure context menu items on content work with no selected text
- [x] Make sure context menu items on content work with selected text
- [x] Make sure context menu items on content work inside an editable control (input, textarea, or contenteditable)

## Developer Tools

- [x] Verify you can inspect sublinks via dev tools

## Find in page

- [x] Ensure search box is shown when selected via the hamburger menu
- [x] Verify that you can successfully find a word on the page
- [x] Verify that the forward and backward navigation icons under find are working
- [x] Verify failed to find shows 0 results

## Site hacks

- [x] Verify https://www.twitch.tv/adobe sub-page loads a video and you can play it

## Settings and Bottom bar

- [x] Verify changing default settings are retained and don't cause the browser to crash
- [x] Verify bottom bar buttons (Home/Bookmark/Search/Tabs) work as expected 

## Downloads

- [x] Verify downloading a file works and that all actions on the download item work.
- [x] Verify that PDF is downloaded over HTTPS at https://basicattentiontoken.org/BasicAttentionTokenWhitePaper-4.pdf
- [x] Verify that PDF is downloaded over HTTP at http://www.pdf995.com/samples/pdf.pdf

## Fullscreen

- [x] Verify that entering HTML5 fullscreen works and pressing restore to go back exits full screen. (youtube.com)

## Autofill Tests

- [x] Verify that autofill works on https://srirambv.github.io/formfiller.html

## Zoom

- [x] Verify zoom in / out gestures work
- [x] Verify that navigating to a different origin resets the zoom

## Bravery settings

- [x] Check that HTTPS Everywhere works by loading http://https-everywhere.badssl.com/
- [x] Turning HTTPS Everywhere off and shields off both disable the redirect to https://https-everywhere.badssl.com/
- [x] Check that toggling to blocking and allow ads works as expected
- [x] Verify that clicking through a cert error in https://badssl.com/ works
- [x] Visit https://brianbondy.com/ and then turn on script blocking, nothing should load. Allow it from the script blocking UI in the URL bar and it should work.
- [x] Verify that default Bravery settings take effect on pages with no site settings
- [x] Verify that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/7/ when 3rd party cookies are blocked
### Fingerprint Tests
  - [x] Visit https://browserleaks.com/webrtc, ensure 2 blocked items are listed in shields
  - [x] Verify that https://diafygi.github.io/webrtc-ips/ doesn't leak IP address when `Block all fingerprinting protection` is on

## Content Tests

- [x] Go to https://brianbondy.com/ and click on the twitter icon on the top right. Verify that context menus work in the new twitter tab
- [x] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved. Make sure the saved password is auto-populated when you visit the site again
- [x] Open a GitHub issue and type some misspellings, make sure they aren't autocorrected
- [x] Open an email on http://mail.google.com/ or inbox.google.com and click on a link. Make sure it works
- [x] Verify that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run)

## Brave Rewards/Ads

- [x] Verify wallet is auto-created after enabling rewards(either via Panel or Rewards page)
- [x] Verify account balance shows correct BAT and USD value
- [x] Verify actions taken (claiming grant, tipping, auto-contribute) display in wallet panel
- [x] Verify `Check back soon for a free token` grant is shown in the panel when grants are not available for ads unsupported region only
- [x] Verify grant details are shown in expanded view when a grant is claimed
- [x] Verify monthly budget shows correct BAT and USD value
- [x] Verify you can exclude a publisher from the auto-contribute table by clicking on the trash bin icon in the auto-contribute table
- [x] Verify you can exclude a publisher by using the toggle on the Rewards Panel
- [x] Verify you can remove excluded sites via `Restore All` button
- [x] Verify when you click on the BR panel while on a site, the panel displays site-specific information (site favicon, domain, attention %)
- [x] Verify when you click on `Send a tip`, the custom tip banner displays
- [x] Verify you can make a one-time tip and they display in tips panel
- [x] Verify you can make a recurring tip and they display in tips panel
- [x] Verify you can tip a verified publisher
- [x] Verify you can tip a verified YouTube creator
- [x] Verify tip panel shows a verified checkmark for a verified publisher/verified YouTube creator
- [x] Verify tip panel shows a message about the unverified publisher
- [x] Verify BR panel shows the message about an unverified publisher
- [x] Verify you can perform a contribution
- [x] Verify if you disable auto-contribute you are still able to tip regular sites and YouTube creators
- [x] Verify that disabling Rewards and enabling it again does not lose state
- [x] Verify that disabling auto-contribute and enabling it again does not lose state
- [x] Verify unchecking `Allow contribution to videos` option doesn't list any YouTube creator in ac list
- [x] Adjust min visit/time in settings. Visit some sites and YouTube channels to verify they are added to the table after the specified settings
- [x] Verify you can reset rewards from advance setting. Resetting should delete wallet and bring it back to the pre-optin state
- [x] Upgrade from an older version
  - [x] Verify the wallet balance (if available) is retained
  - [x] Verify auto-contribute list is not lost after upgrade
  - [x] Verify tips list is not lost after upgrade
  - [x] Verify wallet panel transactions list is not lost after upgrade
### Brave Ads
- [x] Verify ads is auto-enabled when rewards is enabled for the supported region
- [x] Verify ads are only shown when the app is being used
- [x] Verify ad notification are shown based on ads per hour setting
- [x] Verify ad notifications stack up in notification tray
- [x] Verify swipe left/right dismisses the ad notification when shown and is not stored in the notification tray
- [x] Verify clicking on an ad notification shows the landing page
- [x] Verify `view`,`clicked` and `landed` and `dismiss` states are logged based on the action

## Sync

- [x] Verify you are able to join sync chain by scanning the QR code
- [x] Verify you are able to join sync chain using code words
- [x] Verify you are able to create a sync chain on the device and add other devices to the chain via QR code/Code words
- [x] Verify that bookmarks from other devices on the chain show up on the mobile device after sync completes
- [x] Verify newly created bookmarks gets sync'd to all devices on the sync chain
- [x] Verify existing bookmarks before joining sync chain also gets sync'd to all devices on the sync chain
- [x] Verify sync works on an upgrade profile and new bookmarks added post-upgrade sync's across devices on the chain
- [x] Verify adding a bookmark on custom tab gets synced across all devices in the chain
- [x] Verify you are able to create a standalone sync chain with one device

## Top sites view

- [x] Long-press on top sites to get to deletion mode, and delete a top site (note this will stop that site from showing up again on top sites, so you may not want to do this a site you want to keep there)

## Background

- [x] Start loading a page, background the app, wait > 5 sec, then bring to front, ensure splash screen is not shown

## Session storage

- [x] Verify that tabs restore when closed, including active tab

**Comment by GeetaSarvadnya** [comment]
Looks good hence closing the issue.
