### ISSUE TITLE
Request: Remove default blocking of Google Tag Manager

### ISSUE THREAD

**Issue by jimmi-joensson** [brave/brave-browser#8736]
## Description 
Hello I am a developer who is enjoying using Brave and the strong privacy you provide. However I think blocking Google Tag Manager by default is missing the mark. I have read all comments on this [post](https://community.brave.com/t/how-to-use-a-tag-manager/112876/6) at your forum and want to put my voice to Deester4x4jr's.  I am working at a startup where we are using multiple third-party services to ensure, that we provide our users with the best user experience possible. These third-parties include Intercom, FullStory and more. I agree that Brave should block analytics tools like Google Analytics, but by blocking GTM you make managing these necessary third-party scripts more time consuming. The scripts will then have to be included and clustering in the codebase. It also means that every time the product owner wants to try out a new service, we developers has to get involved as well.

I really hope that you will consider to remove the default block of GTM, so that we easily can initialize the necessary tools for ensuring our users UX.

Best regards!

## Brave version (brave://version info)
```
Brave | 1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit)
-- | --
Revision | dc00a510e4c2ae25c4d084cc3d946fc782249224-refs/branch-heads/3987@{#917}
OS | macOS Version 10.15.3 (Build 19D76)
JavaScript | V8 8.0.426.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
```

**Comment by bsclifton** [comment]
cc: @pes10k @ryanbr

**Comment by pes10k** [comment]
Hi @jimmi-joensson thanks for you message, and I hear what you're saying, but we're confident at this point that our users want the current policy, so I dont think we're going to change anything at this point. I appreciate that this causes some inconvenience for you, but Brave's position is that the browser serves the browser user first, before anyone else.  

If you think your users want to use the services you mentioned on your site, you might ask them to drop shields; they'd then load GTM and the other services you describe uninterrupted.

**Comment by m5kr1pka** [comment]
Maybe a good option would be to be able to tie this with cookie consents or is it block for good?

**Comment by m5kr1pka** [comment]
Cookie consent is related, you accept the terms in most cases that you accept that web owner will collect information about you, upon acceptance google analytics would be initialised.
