### ISSUE TITLE
[Android] Unable to download files, complains about storage access

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8737]
## Description 
Clear download history causes conflict in storage access and doesn't remove data

## Steps to reproduce 

   1. Clean install 1.8.19
   2. Download files using the browser. Ensure its shown in the Downloads page
   3. Clear browsing data including download history
   4. Try to download a new image, storage access is blocked
   5. Open `Storage -> Android -> com.brave.browser_nightly -> files -> Download` using file manager, all downloaded files are still retained and not removed 

## Actual result 
![download-storage](https://user-images.githubusercontent.com/17010094/76962625-96b00780-6945-11ea-960b-21381276294d.gif)

## Expected result
Clearing data should remove the files from local storage and not conflict with storage access

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? NA

## Device details
   - Install type (ARM, x86): AMR
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.8.19 Nightly x64 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome?  NA

### Additional information

cc: @bbondy @SergeyZhukovsky

**Comment by srirambv** [comment]
Multiple +1's from community https://community.brave.com/t/cant-download-sd-card-not-found/110216/70

**Comment by srirambv** [comment]
+1 from @ristein via https://github.com/brave/browser-android-tabs/issues/2606

**Comment by samartnik** [comment]
It wasn't completely resolved. For now it's just removed `Downloads` from clean up section.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.117 x64 build
- Verified on upgrade from 1.5.9 to 1.5.117 still allows to download files without showing SD card error message
- Verified on clean install there is no SD card error shown while downloading images
- Verified able to download all file formats without any issues
----------
Verification passed on Samsung Tab A  with Android 9.0 running 1.5.117 x64 build
- Verified on upgrade from 1.5.9 to 1.5.117 still allows to download files without showing SD card error message
- Verified on clean install there is no SD card error shown while downloading images
- Verified able to download all file formats without any issues
----------

**Comment by davotoula** [comment]
When will 1.5.117 be in the play store? Not being able to save downloads is a show stopper for me.

Thanks
