### ISSUE TITLE
Implement machine learning user model changes for Brave Ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#8739]
Implement machine learning user model changes for Brave Ads

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.78 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5035
* Opened both 1.10.x and 1.11.x and viewed logs as I browsed. Visited the same sites in both versions. Confirmed that generally the page classifications were the same. However, once or twice 1.10.x was better, once or twice 1.11.x was better (so neither is perfect of course). Generally confirmed that pages are still being classified, more or less in the same manner as previously from my limited set of sites (~25-30 different sites).
