### ISSUE TITLE
[Android] sync crashes when node is removed and then same objectId comes from cloud - follow up to 8642

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8740]
## Description 
Found while testing #8642 

Issue 8642 is reproducible on x86 device. When resolved, should probably be retested with ARM to ensure no regressions.

## Steps to reproduce 

1. Take a brave-browser desktop containing the changes from brave/brave-core#4404, I was using 1.8.19 on Nightly
2. Create a chain on desktop
3. Connect Android browser (1.5.111) to the chain
4. On desktop, navigate to Bookmarks Manager and create folder OtherBookmark01 inside of Other bookmarks root folder
5. On desktop create a bookmark OtherBookmark01.com inside of OtherBookmark01 folder from pt2
6. Wait until OtherBookmark01 and OtherBookmark01.com appear on Android browser
7. Verify the structure of bookmarks on Android is
```
Other bookmarks
 +OtherBookmark01
    +OtherBookmark01.com
```
8. Delete folder `Other bookmarks` on Android
9. Working quickly, on desktop create folder OtherBookmark02 inside of Other bookmarks root folder
10. Again, working quickly, on desktop create a bookmark OtherBookmark02.com inside of OtherBookmark02 folder from pt9
11. Wait for sync to complete

## Actual result 
12. See crash on Android
![Screenshot_20200318-093440](https://user-images.githubusercontent.com/28145373/76966343-33e64e00-68fc-11ea-8061-b16db14f4908.jpg)

Note - after the crash sync is basically unusable - any further additions/changes are not synced.

## Expected result
12. No crash on Android. Bookmarks structure is
```
Other bookmarks
 +OtherBookmark02
   +OtherBookmark02.com
```

## Issue reproduces how often 
easily, reproduced 3x

## Issue happens on 
   - Current Play Store version? n/a
   - Beta build? yes, 1.5.111

## Device details
   - Install type (ARM, x86): x86
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.5.111

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @srirambv @AlexeyBarabash

**Comment by AlexeyBarabash** [comment]
Done two attempts on both versions 1.5.111 (current beta in GP) and 1.8.42 (current master build) on Android 9 x86 emulator - cannot reproduce this issue.

@LaurenWags which version of Android is installed on your x86 device?

**Comment by LaurenWags** [comment]
@AlexeyBarabash - Android 6

**Comment by AlexeyBarabash** [comment]
Thanks @LaurenWags 
I could not reproduce it with Android 6 emulator, because emulator crashed once it tried to use the camera to scan QR code, but I could reproduce it with Android 5 emulator.

**Comment by AlexeyBarabash** [comment]
I could reproduce this on arm Android 9 physical device.
The tricky step is
8.5 Don't wait until deleted folder  would be on desktop, to to step 9 immediately.
