### ISSUE TITLE
huge CPU spike on web.telegram.org

### ISSUE THREAD

**Issue by fhoshino** [brave/brave-browser#8741]
## Description 

Heavy CPU usage on latest brave release on telegram web without excess use.
Problem does not occur on 1.4.96.

## Steps to Reproduce

   1. Using telegram web (https://web.telegram.org/)

## Actual result:

CPU usage constantly on 30% to 40%, spikes up to 50% to 60%.

## Expected result:

CPU usage is around 10% to 20%

## Reproduces how often: 

Always reproduced.

## Brave version (brave://version info)

Brave | 1.5.112 Chromium: 80.0.3987.132 (Official Build) (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Windows 8.1 (Build 9600.19652)

## Version/Channel Information:

On latest release only

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by rebron** [comment]
@kjozwiak to sign up for telegram and make new friends!

**Comment by bsclifton** [comment]
OK folks - we've done some investigation and are fairly sure we have found the root cause and the fix  😄 Build is happening now and we'll look at releasing a hotfix. Stay tuned 😄

**Comment by bsclifton** [comment]
@fhoshino (or others experiencing the issue) if you wanted to try a work-around while we're prepping the hotfix, here's what you can try:
1. Visit brave://flags/#brave-adblock-cosmetic-filtering
2. Enable this option
3. You'll be prompted to restart- go ahead and do that
4. Problem should be fixed 😄

**Comment by fhoshino** [comment]
Though this workaround seems fixing the idle hog, when loading stickers there is a much higher CPU usage when compared to 1.4
Before it might be using up to 50% total CPU, now it is up to 70% of total CPU.

**Comment by kjozwiak** [comment]
Going to use https://github.com/brave/brave-browser/issues/8779 as the main issue that QA will use to verify that https://github.com/brave/brave-core/pull/4999 fixed the problem. We'll also use the same issue for the release notes once we push the `1.5.x` in a few hours.
