### ISSUE TITLE
Can't disable crypto wallets

### ISSUE THREAD

**Issue by wooque** [brave/brave-browser#8742]
## Description 

There is no setting anymore to disable crypto wallets

## Steps to Reproduce

   1. Open chrome://settings/ -> Extensions
   2. No setting to disable crypto wallets

## Actual result:

There is no setting to disable crypto wallets

## Expected result:
There is setting to disable crypto wallets

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave	1.5.112 Chromium: 80.0.3987.132 (Official Build) unknown (64-bit)
Revision	fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS	Linux
JavaScript	V8 8.0.426.26
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Command Line	/usr/lib/brave-bin/brave --enable-features=OverlayScrollbar --disable-features=TabHoverCards --disable-smooth-scrolling --enable-gpu-rasterization --ignore-gpu-blacklist --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,SimplifyHttpsIndicator,WebUIDarkMode,OverlayScrollbar --disable-features=AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AutofillServerCommunication,AudioServiceOutOfProcess,TabHoverCards,SmsReceiver,VideoPlaybackQuality,WebXrGamepadModule,WebXR --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path	/usr/lib/brave-bin/brave
Profile Path	/home/vuk/.config/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? /
- Can you reproduce this issue with the dev channel? /
- Can you reproduce this issue with the nightly channel? /

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? /
- Does the issue resolve itself when disabling Brave Rewards? /
- Is the issue reproducible on the latest version of Chrome? /

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/disable-brave-wallet/116840/4?u=eljuno

**Comment by rohitghali** [comment]
+1 from me.

**Comment by RJVB** [comment]
+1

I noticed it popping up in the task manager, with a few percents of CPU usage. Not consistently but enough to send me on a search that made me land here.

The IPFS extension is downloaded on demand, why not do the same with this one (and any other extension that most users will probably never have use for)?

**Comment by Rhevin** [comment]
+1 from me

**Comment by juanmcortez** [comment]
+1 from me too ...

**Comment by dandai** [comment]
+1

**Comment by say4n** [comment]
+1

**Comment by Taomyn** [comment]
+1

**Comment by calebbarr** [comment]
+1

**Comment by Deses** [comment]
Extension Crypto Wallets is using about 70 MB of RAM and I wish for it to be gone. I have plenty of ram but I just don't want this crap installed.

I switched from Chrome to avoid this kind of BS, and this is pretty disappointing.

Also, wtf is this?
![image](https://user-images.githubusercontent.com/1654959/83317221-616c4380-a22b-11ea-9d66-3fb1c06b6e28.png)
If it's crypto related I just want it **gone**.

**Comment by RJVB** [comment]
On Friday May 29 2020 19:10:13 Carlos R wrote:

>Also, wtf is this?
>![image](https://user-images.githubusercontent.com/1654959/83317221-616c4380-a22b-11ea-9d66-3fb1c06b6e28.png)

I've been wondering about those too. They bring back not-fond old memories of something called "The Bat" in relation to spam, so seeing "Bat Ads Service" isn't very nice.

**Comment by Deses** [comment]
> On Friday May 29 2020 19:10:13 Carlos R wrote: Also, wtf is this? ![image](https://user-images.githubusercontent.com/1654959/83317221-616c4380-a22b-11ea-9d66-3fb1c06b6e28.png)
> I've been wondering about those too. They bring back not-fond old memories of something called "The Bat" in relation to spam, so seeing "Bat Ads Service" isn't very nice.

Nothing to do with spam. BAT is their Basic Attention Token, Brave's crypto to pay creators because we block ads.

I can't even enable the thing in my country! Let me get rid of this.

**Comment by nightcometh** [comment]
+1 from me as well, this a very big negative

part of the reason people switched to brave is to avoid these type of background resources that are always on without the user's permission,
sucking resources and sending data to ???

back to seamonkey until this is resolved

**Comment by joshxyzhimself** [comment]
https://news.ycombinator.com/item?id=23442027

**Comment by Deses** [comment]
> https://news.ycombinator.com/item?id=23442027

Thanks for that link. I guess I'm better off going back to Chrome.

**Comment by micnguyen** [comment]
Thanks for that link. I'm also deleting Brave and going back to Chrome. This GH Issue along with that link shows to me unfortunately that the developers are not only sneaking in stuff but blatantly lying about it. Sorry guys, it was a good 3 months run with the browser.

**Comment by codybrom** [comment]
+1. Don't waste my RAM for features I've disabled.

**Comment by bbondy** [comment]
Just an FYI that this is now lazy loaded with 1.10.x (which will be released either today or Monday), so it will only load Crypto Wallets if you navigate to brave://wallet. 

A further change also makes it so you need to explicitly opt-in and without that it will never start it at all.

Keeping this open since there's still no option to disable it after you explicitly opt-in though. But it will be already off for most users as of 1.10.x.

**Comment by Invisible40** [comment]
Can I turn off the "Set up Crypto Wallets" banner that appears on some websites?

**Comment by marcbousaleh** [comment]
> Can I turn off the "Set up Crypto Wallets" banner that appears on some websites?

That's exactly what I'm looking for, it is really annoying. Please notify me if you found a way to disable it.

**Comment by bbondy** [comment]
Yes you can set `Web3 provider for using Dapps` setting to `None` in brave://settings/extensions or you can just keep it on Brave Wallet but turn on `Load Crypto Wallets on startup`

**Comment by AJolly** [comment]
I'd like to fully disable it, it keeps interfering with nifty or metamask.

**Comment by bbondy** [comment]
@AJolly see 2 messages up, you can set it to MetaMask.

**Comment by Rishirandhawa** [comment]
Brave wallet is making Metamak unusable... there has to be a feature to fully disable/remove Brave wallet.  Surprised that this is not a top priority. I think Brave is the best browser but will sadly have to be deleted

**Comment by bbondy** [comment]
@Rishirandhawa I think you just want to set this setting to MetaMask:
<img width="1213" alt="Screen Shot 2020-10-08 at 12 26 32 PM" src="https://user-images.githubusercontent.com/831718/95486826-843d0000-0961-11eb-9442-d1397a23e876.png">

There's code in Beta now by the way going to Release in 3 weeks that will auto set that to MetaMask for new installs instead of prompting.

**Comment by RJVB** [comment]
> I think Brave is the best browser but will sadly have to be deleted

Have you tried Slimjet? It too has a builtin ad blocker, and it's quite fast.

**Comment by Rishirandhawa** [comment]
I haven't.. will give it. try. Thanks

**Comment by guttermonk** [comment]
The Crypto Wallets extension (that can't be disabled in v1.15) is keeping my Ledger hardware wallet from connecting to MetaMask. Ledger and MetaMask work fine in other browsers.

Even after setting "Load Crypto Wallets on startup" to OFF and setting the "Web3 provider for using Dapps" to MetaMask, I still can't connect my Ledger to MetaMask. There's no way to disable the Crypto Wallet extension that no one wants/supports... For that, I'm out.

**Comment by Rishirandhawa** [comment]
@guttermonk I have exactly the same setup and problem. It renders it completely unusable.

**Comment by guttermonk** [comment]
Tried uninstalling MetaMask, clearing my cache, rebooting, connecting my Ledger, starting Brave, opened Crypto Wallets, and tried to "Connect Hardware Wallet" ...still getting the eternal spinner of death.

**Comment by damianocasula** [comment]
+1

**Comment by tomgo5k** [comment]
+1

**Comment by M09NST3R** [comment]
As a workaround, I've disabled it under "Extensions" ([brave://extensions/](brave://extensions/)).

![image](https://user-images.githubusercontent.com/77220130/116927345-8c27fe80-ac29-11eb-9f12-b6f9c8b32cbb.png)

Does anyone know what the benefit of the Brave wallet is over Metamask? I gave the Brave wallet a shot, but it complained about Trezor Connect being incompatibly versioned, so I just went back to Metamask. Thank you.

**Comment by Taomyn** [comment]
@M09NST3R how do you get the extension to appear because it's not listed as one in my extension manager?

**Comment by srirambv** [comment]
@Taomyn you can got to `brave://extensions` when you have CW installed to see what @M09NST3R  has shown

**Comment by Taomyn** [comment]
@srirambv not there either

![image](https://user-images.githubusercontent.com/4365929/116975439-f25f6080-acbf-11eb-8e72-f9ff5310fd47.png)

**Comment by srirambv** [comment]
@Taomyn you need to have the CW page open and then check. The component only loads when you have CW page open

**Comment by Taomyn** [comment]
> @Taomyn you need to have the CW page open and then check. The component only loads when you have CW page open

Ok, so maybe if I do not go beyond this when I go into Settings and click on "Crypto Wallets" then I will not have it anyway?

![image](https://user-images.githubusercontent.com/4365929/116980416-7fa5b380-acc6-11eb-9f14-61e68f769ee4.png)

**Comment by srirambv** [comment]
@Taomyn I don't think you have CW installed so not sure why you want it to be removed? If you are looking to disable/remove UI elements for CW that is not possible. You can only remove/uninstall the extension if its installed. Please see @bbondy's message [above](https://github.com/brave/brave-browser/issues/8742#issuecomment-643375839)

**Comment by bbondy** [comment]
You'll be able to set the new Default wallet to none with this https://github.com/brave/brave-browser/issues/18213

**Comment by zacka77ack89** [comment]
+1

**Comment by bbondy** [comment]
You can do this via brave://settings/wallet by setting `Default cryptocurrency wallet` to `None` and cahnging `Show Brave Wallet icon on toolbar` to off.
