### ISSUE TITLE
brave-installer not available for release 1.5.112

### ISSUE THREAD

**Issue by crazy-max** [brave/brave-browser#8743]
Hi,

`brave-installer-ia32.exe` and `brave-installer-x64.exe` are not available for release [v1.5.112](https://github.com/brave/brave-browser/releases/tag/v1.5.112).
Is it on purpose? Because these artifacts are required for [Brave portable](https://github.com/portapps/brave-portable)

Thanks

**Comment by akash07k** [comment]
Yes, I too am noticing the same. if it is by purpose, then please let us know the reason?

**Comment by bsclifton** [comment]
cc: @mihaiplesa @mbacchi @linhkikuchi do we still upload these? (or should we)

I think the `Standalone` ones should work too

**Comment by mbacchi** [comment]
We have stopped uploading these to the Github releases in order to prevent issues [like this](https://github.com/brave/devops/issues/920) where users inadvertently install the `brave-installer` executable without a tag and therefore become stuck on that single version and never get updated because the tag doesn't match what is used on our update server.

There are multiple other installation options so this shouldn't be required for standard installation support.

**Comment by crazy-max** [comment]
> I think the Standalone ones should work too

@bsclifton Unfortunately `Standalone` setups cannot be extracted programmatically so this is not an option for Brave portable.

> ...to prevent issues like this where...

@mbacchi This issue point to a private repo I think. Can you tell me more about this issue here?

**Comment by mbacchi** [comment]
I updated the issue that I linked to above. It was related to the tag for the installer not being set.

**Comment by crazy-max** [comment]
@mbacchi Hmmm I don't see anything about the removal of `brave-installer-ia32.exe` and `brave-installer-x64.exe` artifacts in brave/brave-browser#2221. And this also concerns Brave 0.56.14 and the artifacts have been removed since 1.5.112 so...
Can you enlighten me please?

**Comment by mbacchi** [comment]
Issue #2221 was simply an example, our plan has been to discontinue distributing the `brave-installer-*.exe` files for quite a while, in order to prevent situations where users installed that raw executable and were never able to update automatically. Sorry if this inconveniences you.

**Comment by LazyZhu** [comment]
Even corp like Google does provide extractable none-updated version of chrome.
BraveBrowser is becoming another product like Waterfox, become famous, acquired by big corp, etc.

@crazy-max 
Check [Ungoogled-Chromium](https://github.com/Eloston/ungoogled-chromium)
https://github.com/macchrome/winchrome/releases

**Comment by crazy-max** [comment]
@mbacchi As @LazyZhu rightly says, these installers are also available from Google for Chrome. For me this is the responsibility of the user. I find it very radical and regressive that your team simply prefers to remove these artifacts.

**Comment by bsclifton** [comment]
@mbacchi could we re-add these with a name that makes it obvious it shouldn't be used by regular users? and/or update the text that gets automatically put onto the release page? Could be something like `Brave-Browser-Win32.7z` (rather than uploading the `.exe` ending)

**Comment by bsclifton** [comment]
re-opening as examples have been provided where the files are provided

**Comment by mihaiplesa** [comment]
@crazy-max working on a fix for you now.

**Comment by akash07k** [comment]
> @crazy-max working on a fix for you now.

Thanks in advance for the willingness to provide the fix.

**Comment by mihaiplesa** [comment]
Here goes:

https://brave-browser-downloads.s3.brave.com/latest/brave_installer-x64.exe
https://brave-browser-downloads.s3.brave.com/latest/brave_installer-ia32.exe

These will always be the latest stable version.

@crazy-max thanks for your work on the portable version and if you're interested in verifying your GitHub profile at https://creators.brave.com/ you can ear BAT tips from the community.

**Comment by crazy-max** [comment]
@mihaiplesa Great! Thanks a lot!
