### ISSUE TITLE
Change the way reset data works

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#8747]
https://github.com/brave/brave-core/pull/4983/files#diff-a6f72947f972d23efcaaae3256e5e3ccR177

<img width="635" alt="Screen Shot 2020-03-18 at 3 09 27 PM" src="https://user-images.githubusercontent.com/831718/76997891-79ba0b00-692a-11ea-990d-e1c6e7615b86.png">

FYI @ryanml

**Comment by bridiver** [comment]
`ExtensionPrefs::Get(browser_context)->DeleteExtensionPrefs(extension_id);` will take care of it and doesn't require any async calls either so it's simpler
