### ISSUE TITLE
Google meet causes high CPU usage

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#8749]
Consistently across all of my latest (per Date March 18th, 2020 including 1.5.*), all of my release, dev, and nightly browsers are thrashing when i use G-Meet. 

Images for Task Manager for me calling myself on 2 brave browsers
<img width="784" alt="Screen Shot 2020-03-18 at 1 50 05 PM" src="https://user-images.githubusercontent.com/35932307/77013350-239a9700-692d-11ea-9236-b1d916e2b5f1.png">
<img width="1357" alt="Screen Shot 2020-03-18 at 2 13 40 PM" src="https://user-images.githubusercontent.com/35932307/77013354-285f4b00-692d-11ea-926c-3a6cd1223945.png">

@rebron @kjozwiak

**Comment by iefremov** [comment]
one more similar case (hangouts and docs) in Slack https://bravesoftware.slack.com/archives/C7VLGSR55/p1584550502423500

**Comment by rebron** [comment]
Reminder to check Chrome performance.

**Comment by jumde** [comment]
Reports from Reddit: 

https://www.reddit.com/r/brave_browser/comments/fm3ca0/brave_eating_up_my_memory/
https://www.reddit.com/r/brave_browser/comments/fm30pv/cpu_usage_becoming_serious_problem/
https://www.reddit.com/r/brave_browser/comments/flruia/i_installed_brave_browser_last_year_and_was/

**Comment by bsclifton** [comment]
OK folks - we've done some investigation and are fairly sure we have found the root cause and the fix  😄 Build is happening now and we'll look at releasing a hotfix. Stay tuned 😄

**Comment by kjozwiak** [comment]
Going to use https://github.com/brave/brave-browser/issues/8779 as the main issue that QA will use to verify that https://github.com/brave/brave-core/pull/4999 fixed the problem. We'll also use the same issue for the release notes once we push the `1.5.x` in a few hours.
