### ISSUE TITLE
make tabs scrollable

### ISSUE THREAD

**Issue by chuegel** [brave/brave-browser#8758]
## Description 

Tabs are not scrollable if you have multiple tabs open which span across the width of the main window. Tabs are shrinked to the size of the favicon thus its impossible to unmute a tab.

![image](https://user-images.githubusercontent.com/6955465/77100052-41432b80-6a15-11ea-8b37-3735685d875f.png)

![image](https://user-images.githubusercontent.com/6955465/77100129-6cc61600-6a15-11ea-9316-620bad23981a.png)

Firefox:
![image](https://user-images.githubusercontent.com/6955465/77100278-aa2aa380-6a15-11ea-8a3f-222522c62459.png)

## Steps to Reproduce

   1. open multiple tabs to span across the main window
   2. mute one tab
   3. try to unmute it. only option to close the tab

## Actual result:

see above

## Expected result:
make tabs vertically scrollable and not shrink them

## Reproduces how often: 

easy

## Brave version (brave://version info)

Mac OS Version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
yes
- Can you reproduce this issue with the beta channel?
yes
- Can you reproduce this issue with the dev channel?
didn't try
- Can you reproduce this issue with the nightly channel?
didn't try
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
nope
- Does the issue resolve itself when disabling Brave Rewards?
nope
- Is the issue reproducible on the latest version of Chrome? 
yes

**Comment by bsclifton** [comment]
Thanks for the report @chuegel! We have an issue captured for this already with https://github.com/brave/brave-browser/issues/35 (subscribe for updates)!

I'm going to close this one as a duplicate. Please feel free to give that issue a +1 or leave a comment 😄
