### ISSUE TITLE
Introduce command line switch to have shorter component update checking interval

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#8762]
Brave checks component update right after the launching for our some components or some minutes later. Then periodically checks the new update every 5 hours in background.
It would be good to have shorter background timer to test component update during the runtime.

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` for now - discussing with @simonhong 😄

**Comment by simonhong** [comment]
OMG, command line switch name was changed to `component-update-interval-in-sec` during the code review. but forgot to update in issue's description. Sorry for this inconvenience.

**Comment by LaurenWags** [comment]
Thanks for the update @simonhong 😄 works like a charm now!

Verified passed with

Brave | 1.8.82 Chromium: 81.0.4044.113 (Official Build) dev (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4991
