### ISSUE TITLE
Ability to toggle shields (up/down) via keyboard shortcut

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#8763]
## Description 
(Requested via email)
Users should be able to use a keyboard shortcut to toggle the status of shields

**Comment by rebron** [comment]
cc: @karenkliu help on suggestions for keyboard shortcut for shields toggle.

**Comment by karenkliu** [comment]
how about:

- on Mac - CMD+SHIFT+S
- on Windows - CONTROL+SHIFT+S
- on Linux - need help here; I have no experience with Linux 😅

**Comment by iamzubin** [comment]
For Linux I guess CONTROL+SHIFT+S should be fine.

**Comment by edwardqiu** [comment]
Hey, I would like to give this a go! 

@bsclifton - I would like your thoughts on if I'm looking at the right files (https://github.com/edwardqiu/brave-core/commit/b30878f006f2d2c8d7673ff84b767ab8a801be1a)

**Comment by bsclifton** [comment]
@0xedward sorry for not following up on this - there are a large number of notifications and sometimes things get lost ☹️ 

For this, we'd want something in in the hamburger menu. The `Show Bookmarks Manager` would be a good example to look at for implementation; Ctrl + Shift + B. There may be a complexity in catching the event in C++ and then sending a message (picked up in JavaScript) to disable shields

**Comment by 0xedward** [comment]
No problem, @bsclifton! 

Thanks for the pointer! I'll continue working on it when I get the chance 🙂

**Comment by Aadi-27** [comment]
Hi,
If no one is working on this issue, can I pick it ?

**Comment by 0xedward** [comment]
I haven't gotten around to this yet, so feel free to take it over @Aadi-27

**Comment by Aadi-27** [comment]
Can someone help me with this ? I ran "npm run init" and it took around 3-4 hrs, used up 30+ gb of my data and still gave this error at the end. Now everytime I am running "npm run init", it throws this error.

![errror part 1](https://user-images.githubusercontent.com/52901335/96216373-c4256800-0f9d-11eb-98be-d35857ec0ad6.png)
![errror part 2](https://user-images.githubusercontent.com/52901335/96216389-cc7da300-0f9d-11eb-9372-98da19f7a433.png)

**Comment by bsclifton** [comment]
@Aadi-27 did you follow dev setup README here?
https://github.com/brave/brave-browser/wiki/Windows-Development-Environment

**Comment by dwarburt** [comment]
I had the same problem on Linux today and I had to edit file `brave-browser/src/brave/build/rustup/0.1.4/registry/src/github.com-1ecc6299db9ec823/semver-parser-0.10.1/src/generated.rs` to remove the line `#![rustfmt::skip]` (on line 4, just delete the whole line) and then it built correctly. https://github.com/steveklabnik/semver-parser/issues/53

**Comment by M09NST3R** [comment]
Hey friends, I strongly support this feature. However, I would suggest that you also add ways to change the granular shield settings via shortcuts.

Currently, people who use the most aggressive settings as their default (no cookies, full anti-fingerprint, aggressive tracker blocking, etc.) and then relax things on a site-by-site basis have a horrible user experience. **This strongly discourages use of restrictive defaults, which can't be in the interest of the Brave project.**

E.g., we need a shortcut that switches cookies from "all blocked" to "only cross-site blocked".

If this would mean too many shortcuts, there should be some other UI mechanism to make it easier to change the defaults. E.g., after pressing a certain shortcut, a popup appears in the middle of the browser window where people can quickly adjust shield settings.

**Comment by asubedy** [comment]
Hey @bsclifton, I see no PRs for this issue, Can you assign it to me? I was thinking maybe first let us implement the toggle shields shortcut first, then later work what @xanoni suggested. I would love your advice here. 
Also, I was reading the[ Linux development environment](https://github.com/brave/brave-browser/wiki/Linux-Development-Environment), and there on [system requirements](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/linux/build_instructions.md#system-requirements) it said a minimum of 100GB free space required. Is this a must-have requirement?

Thank you

**Comment by bsclifton** [comment]
@asubedy sure thing! You're assigned

For a complete compile, the 100GB is recommended. The Chromium source (and accompanying git history) are fairly large, and then when compile the object files, etc take up a decent chunk of space too

**Comment by fallaciousreasoning** [comment]
I'm closing this because as of https://github.com/brave/brave-core/pull/18526 if you enable brave://flags/#brave-commands you can add your own shortcut for this at brave://settings/system/shortcuts (search for shields).

Right now, I don't think we're going to add a default shortcut for this.

cc @rebron
