### ISSUE TITLE
SE is not retained during upgrade (Follow up to #8458)

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8768]
## Description 
SE is not retained during upgrade (Follow up to #8458)

## Steps to reproduce 
Scenario 1:

   1. Install 1.5.9 
   2. Change Private tab SE to DDG via modal
   3. Upgrade to 1.5.113
   4. Open PT and search uses Google
   5. Open settings, PT shows as DDG but opening the setting shows its set to Google

Scenario 2:
   1. Install 1.5.9 (GPS version)
   2. Skip the on boarding flow
   3. Navigate to Settings->change the default search engine to `Bing` or any other search engine
   3. Upgrade to 1.5.113
   4. Open a new tab and enter `test` in URL bar and hit enter
   5. Search engine used is `Google` instead of `Bing`

Note: If you do a search on Private tab or Normal tab before upgrading the setting is retained and correct search engine is used for searching any string in URL bar

## Actual result 
https://bravesoftware.slack.com/archives/CM17J5QMU/p1584689727202100

## Expected result
Ssetting should be retained

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone (OnePlus 6T)
   - Android version: 10
   
## Brave version
1.5.9 -> 1.5.113

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by GeetaSarvadnya** [comment]
The issue is happening in both Normal and PT's , updated the title and added scenario 2 in the issue.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.117 x64 stable build
- Verified both scenarios from issue description
- Verified SE setting is retained on upgrade 
-------
Verification passed on Samsung Tab A with Android 9.0 running 1.5.117 x64 stable build
- Verified both scenarios from issue description
- Verified SE setting is retained on upgrade 
-------
