### ISSUE TITLE
[Android] Unable to claim rewards via chrome://rewards

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8769]
## Description 
 Unable to claim rewards via chrome://rewards

## Steps to reproduce 

   1. Enable staging wallet
   2. Open chrome://rewards
   3. Click on claim button on the rewards page, button disappears no grant claimed
   4. Click on BR panel, page shows claim grant button again
   5. Claim grant via panel, wallet updates

## Actual result 
![claim-rewards](https://user-images.githubusercontent.com/17010094/77145518-cd556180-6aae-11ea-927b-102e3fbac235.gif)

## Expected result
Should be able to claim grant via BR panel and chrome://rewards page

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.5.113

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Not marking for core release as there is still a way to claim grant via panel

**Comment by gdregalo** [comment]
Fix uplifted into 1.5.x with https://github.com/brave/brave-core/pull/5005.

**Comment by wysow** [comment]
Can't find how to do this... Can someone help? Thanks a lot.
