### ISSUE TITLE
No UI prompt of update available or to relaunch to install update

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#877]
## Description 

No UI prompt of update available or to relaunch to install update

## Steps to Reproduce

   1. Install an older version
   2. Wait till a new version is released
   3. No UI indication of update available unless you go to `chrome://settings/help` it doesn't prompt to update and relaunch

## Actual result:

No UI prompt of update available or to relaunch to install update

## Expected result:
Should show some indication that update is available and a restart is pending to install it

## Reproduces how often: 

100%

## Brave version (about:brave info) 

All version

### Reproducible on current release:

No. Any update shows a notification bar to install update or defer until restart

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @rossmoody @bradleyrichter @bbondy

**Comment by simonhong** [comment]
We are using chrome's update strategy for now.
Brave will install newer version in background(with some hours interval checking) and wait users re-launch.
When newer version install is finished, brave does not immediately inform to users. (It will distract user)
Instead, it waits some times then informs to users by using app menu.

@bbondy  Do we have a plan for adding our own update inform UI?

**Comment by bbondy** [comment]
I think we might have something already if it is marked as an urgent release? In any case as long as it updates in the background and when going to about, that is all we need for initial release.

**Comment by simonhong** [comment]
I tested `is critical` check box option and I think this feature doesn't affect anything.

`UpgradeDetectorImpl` determines whether currently install version in background is critical or not by checking `cpv` register value. (`GetCurrentlyInstalledVersionImpl(&critical_update);`)
When new version (`is critical` checked) is installed, our updater (omaha) doesn't set `cpv` to registry.
Also, I can't find any `cpv` related code in omaha project.

CC: @RyanJarv

**Comment by bsclifton** [comment]
Closing as I don't think this is a problem anymore. Update icon is shown on Hamburger menu when update is available 😄
