### ISSUE TITLE
Send the segment of the chosen ad in the payload as part of Brave Ads confirmation calls

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#8770]

**Comment by ShivanKaul** [comment]
@tmancey I think this is related to https://github.com/brave/security/issues/476, but the first line of the issue description says "we would like to include channel and platform in our confirmation requests" which I think is already done.

**Comment by tmancey** [comment]
@ShivanKaul this feature is on hold and needs updating. I am just making sure any issues for Ads that would require a privacy review are marked as such
