### ISSUE TITLE
[Android] Missing recurring tips sections on rewards page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8771]
## Description 
Recurring tips aren't displayed in Tips panel as there is no `Monthly contribution` section in brave://rewards page

## Steps to reproduce 

   1. Clean profile 1.5.113 - launch using staging flag 
   2. Enable rewards and claim UGP grants
   3. Open https://duckduckgo.com/ and send a recurring tip to it
   4. Open google.com and send a recurring tip 
   5. Recurring tips are not displayed under Tips panel also there is no `Monthly contribution` section in brave://rewards page 
   6. Trigger AC, monthly contribution goes through

## Actual result 
Recurring tips are not displayed under Tips panel as there is no `Monthly contribution` section in brave://rewards page 

## Expected result
Similar to Desktop - Recurring tips should be displayed under `Monthly contribution` section in brave://rewards page 

## Issue reproduces how often 

Always
## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy j3
   - Android version: 5.1.1
   
## Brave version
1.5.113

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @anthonypkeane @SergeyZhukovsky @gdregalo @brave/legacy_qa

**Comment by gdregalo** [comment]
The feature is available on 1.5.113.
![Screenshot_20200323-105126](https://user-images.githubusercontent.com/37560650/77342018-f1f74680-6d05-11ea-8835-6f8598b77222.jpg)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.115. x64 stable build
- Verified rewards page has a `Monthly contribution` section
![image](https://user-images.githubusercontent.com/17010094/77513782-a676a100-6e9b-11ea-922e-839908bc7634.png)
- Verified monthly tip set to a publisher is added in the section under details view
- Verified able to remove monthly contribution set to a publisher and readd it
- Verified on upgrade from GPS build onetime tips and recurring tips are segregated correctly 
![image](https://user-images.githubusercontent.com/17010094/77513761-9e1e6600-6e9b-11ea-88e5-1b44610bc12f.png)
--------
