### ISSUE TITLE
[Android] AC contribution message shows 0.0 BAT

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8772]
## Description 
 AC contribution message shows 0.0 BAT

## Steps to reproduce 

   1. Clean install or upgrade to 1.5.113
   2. Trigger AC
   3. Ac notification shows 0.0. BAT

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/77149023-badf2600-6ab6-11ea-847b-ee0026042c90.png)

## Expected result
Should show proper amount that is contributed

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? NA
   - Beta build? Yes
 
## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.5.113

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Not a blocker as panel shows contribution amount correctly. This was an issue on tabs as well

**Comment by GeetaSarvadnya** [comment]
Reproduced in Samsung Galaxy J3 version 5.1.1 running `BraveModernarm 1.5.113`

**Comment by Miyayes** [comment]
Not sure if this is still an issue? cc: @srirambv

**Comment by srirambv** [comment]
Don't think its an issue any more. This is a very old issue. haven't seen it in recent times. @Uni-verse Please keep an eye on this while running through the https://github.com/brave/brave-browser/issues/23284 and reopen this issue if it repro's

**Comment by DaniloRoque501** [comment]
https://github.com/brave/brave-browser/issues/8772#issuecomment-1149558083
