### ISSUE TITLE
[Android] Update Graphics on Rewards page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8774]
## Description 

Update Graphics on Rewards page
## Steps to reproduce 
Scenario 1:
   1. Clean profile 1.5.113
   2. Enable rewards via Panel or Hamburger menu
   3. Turn OFF Ads and AC switches
   4. Observe the icons in brave://rewards page
   5. Old icon is shown in Ads panel and there is no icon for AC

Scenario 2:
  1. Clean profile 1.5.113
  2. Enable rewards via hamburger menu
  3. Text `By clicking ‘Yes, I'm in!’, you indicate that you have read and agree to the Terms of Service and Privacy Policy.` is missing in two places ( as shown in below images)

## Actual result 
Scenario 1:

Android:
![image](https://user-images.githubusercontent.com/38657976/77158160-c0456c00-6ac8-11ea-8c62-02216fc37f14.png)

Desktop:
![image](https://user-images.githubusercontent.com/38657976/77158093-9f7d1680-6ac8-11ea-9e74-16da9f7f9a82.png)

Scenario 2:

Android: 
![image](https://user-images.githubusercontent.com/38657976/77158558-8e80d500-6ac9-11ea-87e4-0c3a8f027199.png)

![image](https://user-images.githubusercontent.com/38657976/77158493-6f824300-6ac9-11ea-880f-911b9167d710.png)

Desktop:
![image](https://user-images.githubusercontent.com/38657976/77158367-2af6a780-6ac9-11ea-83e0-59641e966b5b.png)
![image](https://user-images.githubusercontent.com/38657976/77158400-3fd33b00-6ac9-11ea-914d-831a548ddc8f.png)

## Expected result

Graphic icons should be same as desktop

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version?
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.5.113

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  na
- Does the issue resolve itself when disabling Brave Rewards? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional information

cc: @anthonypkeane @SergeyZhukovsky @brave/legacy_qa

**Comment by Miyayes** [comment]
Solved with new Settings page
