### ISSUE TITLE
Etoro Ads on the new tab page

### ISSUE THREAD

**Issue by tiagoboldt** [brave/brave-browser#8775]
## Description 
New tab pages with brave are usually beautiful. I had friends migrating to brave just because of them. Nevertheless, recently, you guys started pushing some e-toro backgrounds with them. That's an ad. Ads in brave pay the user. These have undefined behavior, as they look just like any other background. Not nice. 

So, if these are ads and paying the user, that makes sense, as the user has the ads enabled. Still, it would be nice if there was a small disclaimer somewhere on the new tab page stating that the image is an Ad. If these are not paying the user, for consistency, they should not be shown. 

On a side note, if these are paying ads, I would like to have an option to disable them despite leaving the ads enabled, as images typically shown there are really nice and these arent'.  

## Steps to Reproduce
   1. Open a new tab
   2. See etoro ad ![Screenshot 2020-03-20 11 12 22](https://user-images.githubusercontent.com/147858/77158675-b2c5bd00-6a9b-11ea-9aab-eb0bd54a9220.png)

## Expected result:
* Option to disable Ads from new tab background.
* When enabled, pay the user for the Ad shown. 

## Reproduces how often: 
* About 1/4 new tabs

## Brave version (brave://version info)
1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)

**Comment by sav-valerio** [comment]
You can disable it in the *Dashboard Settings*.
![image](https://user-images.githubusercontent.com/14777542/77159178-25876600-6aa5-11ea-8e55-4bea8ddff8c8.png)

**Comment by NejcZdovc** [comment]
cc @davidtemkin @jsecretan

**Comment by tiagoboldt** [comment]
Thanks, @sav-valerio. I only searched for it in the main settings, my bad. Then the only non-clear thing for me is if these are paying the user. If they are, then they are within brave's modus-operandi and this issue is good to be closed.

**Comment by sav-valerio** [comment]
Welp, my comment just disappeared.

You can disable it from the Dashboard Settings:
![image](https://user-images.githubusercontent.com/14777542/77159639-089f6280-6aa6-11ea-8e58-41b275b6f431.png) 

@tiagoboldt 
Brave is being paid for this: https://brave.com/introducing-sponsored-images-in-brave/

**Comment by tiagoboldt** [comment]
Thanks, sorry for not finding that myself. keep up the good work!
