### ISSUE TITLE
[Android] Reset rewards doesn't work

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8776]
## Description 
 Reset rewards doesn't reset correctly if rewards page is opened

## Steps to reproduce 

   1.  Install 1.5.9 and enable rewards
   2. Open rewards page in a new tab
   3. Use browser normally with other rewards page opened in a tab
   4. Upgrade to 1.5.113
   5. Reset rewards from advance settings doesn't prompt for relaunch
   6. Go back to rewards page its turned off instead of reset
   7. Try rewards reset again, prompts for restart and finally is reset

## Actual result 
https://bravesoftware.slack.com/archives/CM17J5QMU/p1584684109200800

## Expected result
Rewards should be reset even if rewards page is opened

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? no
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.5.113

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
+1 from @Maxime-J via #14055 and @newuser-web via  #15351

**Comment by stephendonner** [comment]
## Verified `PASSED(*)` using `1.44.95, Chromium 106.0.5249.40` on a `Google Pixel XL` running `Android 9`.

### Steps:

1. install `1.44.95`
2. launch Brave
3. tap on the 3-dots menu
4. tap on `Settings`
5. tap on `About Brave`
6. tap 10x on `Application version`
7. tap on `Developer options`
8. tap on `QA Preferences`
9. enter the code
10. tap to set `Use Rewards staging server` to `Enabled`
11. tap `Later`
12. tap to set `Verbose Logs for Ad-Rewards`
13. tap `Relaunch now`
14. tap on the `BAT` icon
15. tap `Start using Brave Rewards`
16. tap on `Unverified`
17. tap `Continue`
18. tap `Uphold`
19. tap on `Authorize`
20. log in to staging/sandbox
21. tap `Next`
22. wait
23. you'll see `0.300 BAT` added to `Estimated Earnings`
24. tap on the 3-dots menu
25. tap `Settings`
26. tap `Brave Rewards`
27. tap `Reset Brave Rewards`
28. tap `Confirm`
29. tap `Relaunch Now`
30. look at your `brave://rewards` window

### Confirmed that everything except for `Estimated Earnings` was cleared and reset (with `Brave Private Ads` and `Auto-Contribute` both now set to `Disabled`)

example | example | example | example | example
---------|----------|---------|----------|--------
![Screenshot_20220922-000559](https://user-images.githubusercontent.com/387249/191626391-a160ebaa-3cdc-49d2-bdaa-055887be5501.png) | ![Screenshot_20220922-000611](https://user-images.githubusercontent.com/387249/191626421-a6b8e7e0-625f-4449-8b96-f23fb0d418ab.png) | ![Screenshot_20220922-000620](https://user-images.githubusercontent.com/387249/191626449-2e026c11-27c7-481b-9e8a-414f0e82a73d.png) | ![Screenshot_20220922-000628](https://user-images.githubusercontent.com/387249/191626451-06cb7950-664d-45dc-b82f-5c0dc772bd04.png) | ![Screenshot_20220922-000638](https://user-images.githubusercontent.com/387249/191626452-d76709ac-df7c-48c3-8ab7-f64727a450e2.png) | 
![Screenshot_20220922-000650](https://user-images.githubusercontent.com/387249/191626601-aab98f66-591a-4e0e-b9a0-ce5c8a5275f9.png)


#### (*) NOTE: spun off https://github.com/brave/brave-browser/issues/25541 for `Estimated Earnings`.  It's correct when tapping on the `BAT` icon overlay, as shown below:

![Screenshot_20220921-155727](https://user-images.githubusercontent.com/387249/191626671-e315fc72-9514-4031-918d-f42358815508.png)
