### ISSUE TITLE
remove Apps shortcut from Bookmarks bar

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#878]
## Test plan
See https://github.com/brave/brave-core/pull/639#pullrequestreview-164883233

## Description
Remove Apps shortcut from Bookmarks bar. 
Also remove the Show Apps Shortcut in the context menu of the Bookmarks bar.

Chrome Apps is EOL:
https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/639
