### ISSUE TITLE
[Android] Rewards reset not working (settings are retained even after rewards is reset) 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8780]
## Steps to reproduce 

   1. Clean profile 1.3.115
   2. Enable rewards via onborading flow
   3. Open brave://rewards page
   4. Change `Monthly Payment` to 5 BAT in Auto -contribute panel
   5. Click on advanced `Auto-Contribute Settings`
   6. Change min page time settings to 1 min
   7. Open Tip settings and uncheck `Reddit` and `GitHub` check boxes
   8. Click on hamburger menu and navigate to settings->Brave Rewards->click on `Reset Brave Rewards`
  9. Click on `Confirm` in Reset Brave Rewards notification
 10. Click on `Relaunch Now` button in notification
11. Click on BR panel and click on `Join Rewards` to create a new wallet
12. Changes which are done in steps 4,5,6 and 7 are retained in new wallet

**Note**: `Relaunch Now` option is not always shown

## Actual result 
Settings are retained even after rewards is reset

## Expected result
Settings should not retained after rewards is reset

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 1.5.113
   
## Brave version

1.5.113
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? na
- Does the issue resolve itself when disabling Brave Rewards? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional information

cc: @SergeyZhukovsky @samartnik @anthonypkeane @brave/legacy_qa

**Comment by Miyayes** [comment]
Same issue as: https://github.com/brave/brave-browser/issues/8776
