### ISSUE TITLE
lost pinned top sites on NTP upon upgrade

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#8781]
## Description 

Using 1.8.25 and upgrading via download/install of 1.8.28 (but likely in 1.8.27 also), 3 pinned tabs disappear upon relaunch. Expectation is that those pinned tabs and all tabs remain the same after upgrading. Subsequent attempts to reload or open new brave://newtab don't bring them back.

## Steps to Reproduce

   1. Older profile. Pin 2 or 3 top sites on the New Tab Page brave://newtab
   2. Download 1.8.27 or 1.8.28
   3. Notice that the pinned top tiles are missing. 

## Actual result:

<img width="648" alt="Screen Shot 2020-03-20 at 8 20 37 AM" src="https://user-images.githubusercontent.com/5951041/77178018-bb11fe00-6a83-11ea-92d5-632c07e444a3.png">

## Expected result:

<img width="701" alt="Screen Shot 2020-03-20 at 8 19 53 AM" src="https://user-images.githubusercontent.com/5951041/77177943-9ae23f00-6a83-11ea-978d-14201a886ede.png">

## Reproduces how often: 
Might be difficult to reproduce. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? No
- Can you reproduce this issue with the nightly channel? 1.8.27 and higher

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.8.79 Chromium: 81.0.4044.92 (Official Build) dev (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
- Logged a follow-up issue https://github.com/brave/brave-browser/issues/9299
