### ISSUE TITLE
[Android] crash after upgrading when attempting to play a video on YT

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8786]
## Description 
If you enable Background playback option on 1.5.9 and upgrade to 1.5.113, setting is retained as expected. However, when you go to play a video on YT, Brave will crash the first time.

## Steps to reproduce 

   1. Install 1.5.9 tabs version (skip onboarding if using ARM)
   2. Enable background playback in settings
   3. Restart, confirm setting is retained.
   4. Close, remove from memory.
   5. Update to 1.5.113
   6. Launch, navigate to settings and confirm it shows Enabled
   7. Navigate to YT and attempt to play a video

*Note, this crash does not occur when updating to 1.5.111 but setting was not retained on upgrade to 1.5.111.

## Actual result 
Brave crashes

## Expected result
Video is played

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? n/a
   - Beta build? yes

## Device details
   - Install type (ARM, x86): both
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.5.113

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

I did not see the crash in the following scenarios, but they should be double checked when this is fixed:
1. Install 1.5.9. Do not change setting for background playback (leave disabled). Update to 1.5.113. Go to Youtube to play video. No crash.
2. Install 1.5.113. Do not change setting for background playback (leave disabled). Go to Youtube to play video. No crash.
3. Install 1.5.113. Change setting for background playback (make enabled). Restart. Confirm still enabled in settings. Go to Youtube to play video. No crash.

**Comment by GeetaSarvadnya** [comment]
Reproduced in Samsung Galaxy J3 version 5.1.1 running BraveModernarm 1.5.113

**Comment by LaurenWags** [comment]
Marked as `QA/Blocked` on https://github.com/brave/brave-browser/issues/8871

**Comment by srirambv** [comment]
This works fine on OnePlus 6T with Android 10 running 1.5.117 x64 stable build
- Verified steps from issue description and no crash when playing YT video

**Comment by LaurenWags** [comment]
Appears to be working on Asus Zenfone x86, no crashes when attempting to play YT after upgrade. However, sometimes I do encounter https://github.com/brave/brave-browser/issues/8871 as noted by @GeetaSarvadnya
