### ISSUE TITLE
BraveUpdateSetup.exe being tagged as malicious by AV vendors

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#8789]
https://www.virustotal.com/gui/file/287edc072ecac10239db9b28e9c1330ecfc4b7b7bfd9ba28dc46b8adeea5fa58/details

**Comment by jonathansampson** [comment]
Note, the resource is no longer being detected as malicious by any of the engines. Closing.

![image](https://user-images.githubusercontent.com/815158/77234596-9f8b1e00-6b7d-11ea-8356-7914b7f31d43.png)
