### ISSUE TITLE
[Android] clear download history missing an icon 

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8790]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/8417
On the 'Basic' tab of clear browsing data the `Download history` option is missing an icon, but on the 'Advanced' tab download history has an icon.

## Steps to reproduce 

   1. Open Settings > Privacy > Clear Browsing Data
   2. Compare Basic and Advanced tabs
  

## Actual result 
![Screenshot_20200320-145618](https://user-images.githubusercontent.com/28145373/77198185-de0cd400-6abc-11ea-8fba-309cc84fcbc6.jpg)

## Expected result
![Screenshot_20200320-145622](https://user-images.githubusercontent.com/28145373/77198200-e402b500-6abc-11ea-828f-d2860bcb1ed9.jpg)

## Issue happens on 
   - Current Play Store version? 
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.5.113

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by anthonypkeane** [comment]
We removed download history previously
