### ISSUE TITLE
Missing creative set segments and unknown types in the Brave Ads catalog should not fail to parse the catalog

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#8799]
Missing creative set segments and invalid types in the Brave Ads catalog should not fail to parse the catalog.

**Comment by bsclifton** [comment]
Added link to test plan - @tmancey is this something we'd want to call out in release notes? (if not, can you please add `release-notes/exclude`)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.8.77 Chromium: 81.0.4044.92 (Official Build) dev (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/5003
Catalog file used : 
[Different creative sets with empty segment and unknown code along with non-empty segment and known code.txt](https://github.com/brave/brave-browser/files/4493300/Different.creative.sets.with.empty.segment.and.unknown.code.along.with.non-empty.segment.and.known.code.txt)

![image](https://user-images.githubusercontent.com/38657976/79575866-0b5e9900-80e0-11ea-8a73-d25687de9c01.png)
