### ISSUE TITLE
1password can't connect

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#88]
1password wants to use the google chrome path for the native extension dir

**Comment by bbondy** [comment]
QA notes:
I think this will still fail because of our app ID, new issue though please.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

* Verified 1PasswordX works fine on Linux. No support for 1Password though on Linux as app is not available
