### ISSUE TITLE
Supporting $generichide in Brave

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#8803]
## Description

We should support $generichide and $ghide (ubo style) in Brave, bring us inline with uBO, ABP, Adguard and other adblockers. Generichide filter is used to counter sites against Anti-adblock measures for checking generic css divs.

## Popularity (as of 22/03/2020)

uBO Filters.txt (1535 generichide/ghide lines):
`grep \$ghide filters.txt | wc -l`
`1535`

Easylist (295 $generichide lines):
`grep -r generichide * | wc -l`
`295`

## How its implemented:
**Sample domain filter:** 
`@@||domain.com^$generchide`

**Cosmetics wouldn't apply to domain.com:**
`##.adblock`
`###adbanner`
`###ad_text:not(textarea)`
`###tads + div + .c`
**Cosmetic would apply:**
`domain.com##.topBarAd`
`domain.com###sidebar-ad`
`domain.com##a[href^="https://dltags.com/"]`

**Original Implementation:**
https://adblockplus.org/development-builds/new-filter-options-generichide-and-genericblock

## Steps to Reproduce

   1. Visiting `https://www.forbes.com`
   2. Expecting uBo filters.txt `@@||forbes.com^$generichide` to hide the generic filters the site is using. 
   3. See the work around: https://github.com/brave/adblock-lists/pull/352

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.92 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5581
<img width="1196" alt="Screen Shot 2020-07-17 at 9 02 13 AM" src="https://user-images.githubusercontent.com/28145373/87788935-3a35f980-c80c-11ea-8fbd-b73f034e951e.png">

--------

**Comment by srirambv** [comment]
Removing `OS/Android` label as there is no aggressive/standard setting available yet on Android.
