### ISSUE TITLE
Remove auto-increment from contribution_queue

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#8804]
Currently we have auto increment on contribution_queue. This complicates things now that we moved DB into shared lib. To simplify this we should switch from INT AUTOINCREMENT to string uuid. This way we generate it ahead of time and publishers for the queue can be inserted without any problems.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.11.65 Chromium: 83.0.4103.97 (Official Build) dev (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/5642
* Confirmed on `contribution_queue` and `contribution_queue_publishers` tables the `contribution_queue_id` is of type Text.
<img width="897" alt="Screen Shot 2020-06-16 at 12 10 47 PM" src="https://user-images.githubusercontent.com/28145373/84799701-a681cb00-afca-11ea-81ee-a50c7e2c64bb.png">

* Confirmed tipping via various methods was processed and displayed in UI as expected:

Scenario 1 - tipping using VG (UGP grant)
<img width="402" alt="8804 - scenario 1 - tip with VG - 1" src="https://user-images.githubusercontent.com/28145373/84799778-c3b69980-afca-11ea-89fb-486ff6b85cc0.png">
<img width="655" alt="8804 - scenario 1 - tip with VG - 2" src="https://user-images.githubusercontent.com/28145373/84799784-c618f380-afca-11ea-8552-de08b67d3d47.png">
<img width="955" alt="8804 - scenario 1 - tip with VG - 3" src="https://user-images.githubusercontent.com/28145373/84799789-c87b4d80-afca-11ea-90ab-5656f1920dde.png">

Scenario 2 - tipping with restored wallet (anon user funds)
<img width="414" alt="8804 - scenario 2 - tip with restored wallet - 1" src="https://user-images.githubusercontent.com/28145373/84799814-d335e280-afca-11ea-8d71-fdaa0ada590a.png">
<img width="668" alt="8804 - scenario 2 - tip with restored wallet - 2" src="https://user-images.githubusercontent.com/28145373/84799820-d5983c80-afca-11ea-80c8-ef92259dbc76.png">
<img width="938" alt="8804 - scenario 2 - tip with restored wallet - 3" src="https://user-images.githubusercontent.com/28145373/84799831-d7fa9680-afca-11ea-836b-2664cdbb1a9f.png">

Scenario 3 - tipping with KYC'd Uphold wallet
<img width="404" alt="8804 - scenario 3 - tip with Uphold - 1" src="https://user-images.githubusercontent.com/28145373/84799858-e21c9500-afca-11ea-9dc5-ebbdf47c645f.png">
<img width="652" alt="8804 - scenario 3 - tip with Uphold - 2" src="https://user-images.githubusercontent.com/28145373/84799863-e3e65880-afca-11ea-9248-d1e8e4bd638b.png">
<img width="943" alt="8804 - scenario 3 - tip with Uphold - 3" src="https://user-images.githubusercontent.com/28145373/84799866-e648b280-afca-11ea-9c44-a5e442c559e6.png">
