### ISSUE TITLE
Check failure while importing from welcome page

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#8808]
Crashed with master build (`Version 1.8.32 Chromium: 81.0.4044.69 (Developer Build) (64-bit)`)
```
[47456:47456:0323/135125.549138:FATAL:import_data_handler.cc(116)] Check failed: args->GetDictionary(1, &types). 
#0 0x7f2dfa3f882f base::debug::CollectStackTrace()
#1 0x7f2dfa11444d base::debug::StackTrace::StackTrace()
#2 0x7f2dfa114408 base::debug::StackTrace::StackTrace()
#3 0x7f2dfa15a21d logging::LogMessage::~LogMessage()
#4 0x56514c25099b settings::ImportDataHandler::HandleImportData()
#5 0x56514c252bdb base::internal::FunctorTraits<>::Invoke<>()
#6 0x56514c252ac6 base::internal::InvokeHelper<>::MakeItSo<>()

```

Reproduce step
1. Launch browser and load brave://welcome
2. Try to import from any profile
3. Importing should be done w/o crash

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.8.71 Chromium: 81.0.4044.92 (Official Build) dev (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from description
* Confirmed history and bookmarks imported from Firefox using brave://welcome (note, encountered logged issue https://github.com/brave/brave-browser/issues/2198)
* Confirmed history, bookmarks, and passwords were imported from Chrome using brave://welcome.
* Confirmed no crashes observed when importing from brave://welcome
