### ISSUE TITLE
[Android] Twitter: Unverified Channels Marked as Verified

### ISSUE THREAD

**Issue by gdregalo** [brave/brave-browser#8816]
## Description 
Duplicate of https://github.com/brave/browser-android-tabs/issues/2374

## Steps to reproduce 
Please see the original issue (2374) for steps.
   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.117 x64 stable build
- Verified on both  clean install and upgrade
![image](https://user-images.githubusercontent.com/17010094/77744511-b9c27180-703f-11ea-9770-cafad737575a.png)
------
Verification passed on Samsung Tab A with Android 9.0 running 1.5.117 x64 stable build
- Verified on both  clean install and upgrade
![image](https://user-images.githubusercontent.com/17010094/77744520-be872580-703f-11ea-9dcb-bad45e94fd64.png)
------
