### ISSUE TITLE
`Canvas.toBlob` doesn't work when device recognition shield is up

### ISSUE THREAD

**Issue by dwelle** [brave/brave-browser#8817]
## Description 

`HTMLCanvasElement.toBlob()` doesn't work as it doesn't call the callback.

## Steps to Reproduce

   1. enable the device recognition shield (is this how it's done? It looks like reporting setting, not a shield enable/disable workflow):
        
         ![image](https://user-images.githubusercontent.com/5153846/77338382-94292580-6d2a-11ea-850d-bbd4b1656e7e.png)

   1. `document.createElement('canvas').toBlob(blob => console.log(blob))`

## Actual result:

Nothing called. No error emitted.

## Expected result:

Callback should be called with the `Blob`.

## Reproduces how often: 

100% when the shield is up.

## Brave version (brave://version info)

1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? YES
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

Use case: Reported in https://github.com/excalidraw/excalidraw/issues/1061. In [Excalidraw](https://excalidraw.com/), we use it to export canvas to `image/png` and when copying canvas to clipboard as PNG. Both cases use `canvas.toBlob`.

**Comment by rebron** [comment]
@pes10k Can you take a look? I know we're reworking these settings could close out in favor of the settings work.

**Comment by pes10k** [comment]
Yep, this is 1.5.  The farbling protections came in in 1.7, and solve this

**Comment by pes10k** [comment]
with fingerprinting protections up, the app will see very minor changes to the output (random flips of the low order bit in some pixels) to protect against fingerprinters

**Comment by LaurenWags** [comment]
@pes10k what could QA use as a test plan for this issue? Or, since this was implemented in a previous version should this be marked `QA/No` & `release-notes/exclude`?

cc @rebron @kjozwiak

**Comment by pes10k** [comment]
@LaurenWags You can test by looking at the canvas rows in https://dev-pages.brave.software/farbling.html and https://dev-pages.bravesoftware.com/farbling.html

If the values on the two sites differ from each other, than things are working correctly (they'd be the same on every page if the API was broken).

If you'd prefer a more direct / specific test too, i can add another one to that page too

**Comment by dwelle** [comment]
Primarily, we should ensure the OP issue is fixed (which it seems it is on v11 :+1:).
