### ISSUE TITLE
Clicking offsite links in pinned tab should always open a new tab

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#882]
Carried over from https://github.com/brave/browser-laptop/issues/569
> When I pin a tab, I want links to other sites to open in a new tab and only on-site links to open in the pinned tab. For example, if I pin gmail, I want to be able to navigate around gmail in that pinned tab but I want a link in an email to some other site to open in a new tab.

## Steps to reproduce
1) Visit https://media.clifton.io/issue-569/2016-05-27-brave-pin.html
2) Pin the site
3) Click the "same domain" link, notice it works as expected (opens in same tab)
4) Click back
5) Click the "external link"
6) Notice it didn't work; it opens in the same tab

**Comment by srirambv** [comment]
Its the same behaviour on Chrome as well. Not really sure if this bug was even valid for b-l as well.

**Comment by LaurenWags** [comment]
+1 from my husband

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/7423
