### ISSUE TITLE
Do not include failed contributions in monthly statement

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#8821]
## Steps to Reproduce

   1. enable rewards
   2. claim grant
   3. do AC
   3. go to DB, go to contribution_info table and change step from -1 to -3

## Actual result:

Contribution is shown in the monthly statement

## Expected result:
Contribution should not be shown in monthly statement

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.79 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/5028

Monthly statement after successful AC:
<img width="938" alt="Screen Shot 2020-03-31 at 10 38 51 AM" src="https://user-images.githubusercontent.com/28145373/78039476-28ebde80-733c-11ea-96c2-d8c4deaeced1.png">
<img width="943" alt="Screen Shot 2020-03-31 at 10 38 59 AM" src="https://user-images.githubusercontent.com/28145373/78039478-29847500-733c-11ea-8460-1d3d26d138a4.png">

Monthly statement after changing `step` value in `contribution_info` table:
<img width="952" alt="Screen Shot 2020-03-31 at 10 40 19 AM" src="https://user-images.githubusercontent.com/28145373/78039511-35703700-733c-11ea-84d1-1c1805900117.png">
<img width="939" alt="Screen Shot 2020-03-31 at 10 40 26 AM" src="https://user-images.githubusercontent.com/28145373/78039515-3608cd80-733c-11ea-9a54-c9276dc65d18.png">

Note - as mentioned in https://github.com/brave/brave-core/pull/5028#issuecomment-604658217, confirmed with @NejcZdovc that the Auto Contribute will still show in the summary (upper right corner) of monthly statement as well as on panel and brave://rewards summaries.
