### ISSUE TITLE
Rename Site Settings to Site and Shields Settings in 

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#8826]
Shields settings are subset in Site settings.
So, `Site Settings` in settings page is renamed to `Site and Shields Settings`.

In brave://settings/privacy and Clear browsing data dialog, all the `Site Settings` title is renamed.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

Brave | 1.7.67 Chromium: 80.0.3987.149 (Official Build) beta (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified that `Site Settings` in settings page is renamed to `Site and Shields Settings`.
![image](https://user-images.githubusercontent.com/38657976/77394062-74ded680-6dc4-11ea-92e8-18acb89536ea.png)
- Verified that `Site Settings` is renamed to ` `Site and Shields Settings` in clear browsing data dialog
![image](https://user-images.githubusercontent.com/38657976/77394192-bf605300-6dc4-11ea-8c1d-a8599c0f0ad7.png)
