### ISSUE TITLE
Unblinded tokens not contributed correctly when not enough funds

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#8828]
## Steps to Reproduce

   1. Enable rewards
   2. Claim grant (20 BAT)
   3. Connect KYC uphold
   4. Set AC to 50 BAT and add verified publishers to AC table
   5. Wait for AC to be triggered

## Actual result:

50 is taken from Uphold account

## Expected result:
20 BAT from grant and 30 BAT from Uphold

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.79 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/5050. Confirmed that when a mix of UGP and Uphold BAT are available, the UGP BAT is used first, then the remainder of the Auto Contribute is pulled from Uphold BAT.
<img width="407" alt="Screen Shot 2020-03-31 at 2 46 01 PM" src="https://user-images.githubusercontent.com/28145373/78063804-c5bf7380-735e-11ea-8260-772cac50070e.png">
<img width="1174" alt="Screen Shot 2020-03-31 at 2 45 43 PM" src="https://user-images.githubusercontent.com/28145373/78063808-c7893700-735e-11ea-9058-0741e65d6376.png">
<img width="950" alt="Screen Shot 2020-03-31 at 2 46 07 PM" src="https://user-images.githubusercontent.com/28145373/78063811-c952fa80-735e-11ea-8fc3-dc6764515d37.png">

* Also verified the 3 additional scenarios listed in https://github.com/brave/brave-core/pull/5050#issuecomment-604674063:
   1. Confirmed that if only Uphold BAT is available (KYC'd wallet), auto contribute worked as expected
   2. Confirmed that if only UGP BAT is available (anon wallet, no KYC'd uphold account connected), auto contribute works as expected.
   3. Confirmed that if only BAT from a restored wallet (user funded) is available, auto contribute works as expected.
