### ISSUE TITLE
[Android] Remove autofill dialog

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#8832]
## Description 
We need to remove autofill dialog on Android browser

## Steps to reproduce 

   1. Visit [https://buy.logitech.com/store/#dr_CheckoutStep2](url)
   2. Pick a Credit Card Number field
   3. Observe that picture

## Actual result 
![received_2558336837714847](https://user-images.githubusercontent.com/12011303/77436799-4c51df00-6dba-11ea-9d4f-819a04a1289e.jpeg)

## Expected result
No autofill dialog at all

## Issue reproduces how often 
all the time

## Issue happens on 
   - Current Play Store version? no
   - Beta build? yes

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 x64 stable build
- Verified no autofill dialog shown during checkout process
![image](https://user-images.githubusercontent.com/17010094/77627995-bb236980-6f6d-11ea-9da5-ec8914da6cff.png)
-----------
Verification passed on Samsung Tab A with Android 9.0 x64 stable build
- Verified no autofill dialog shown during checkout process
![image](https://user-images.githubusercontent.com/17010094/77628574-3dac2900-6f6e-11ea-98a0-84cd93887646.png)
-----------
