### ISSUE TITLE
Please add the ability to back up data to the cloud.

### ISSUE THREAD

**Issue by oky2abbas** [brave/brave-browser#8835]
If my operating system (unexpectedly) becomes unusable all my important information including (passwords, histories, etc) will be **erased**.

Also, if my laptop or ‍mobile phone is stolen, all of my confidential information will be lost like my passwords.

However, while `Chrome browser` is needed at any time, it is possible to delete data from the browser **(because it has cloud synchronization)**.

**Please add this important feature.**

**Comment by RaveenBouy** [comment]
I read in reddit that a new version of sync is being worked on. Hope it would be released soon!

**Comment by rebron** [comment]
Closing as duplicate of #9241
