### ISSUE TITLE
monthly statement drop down shows previous month in dropdown for current month

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8836]
## Description 

Monthly statement drop down shows `February 2020` however data is being shown (right side summary and bottom lists) for current month of March.

## Steps to Reproduce

   1. Clean profile w/ staging flags
   2. Enable Rewards, claim grant
   3. Make a one time tip
   4. Open monthly statement

## Actual result:
Dropdown says 'February 2020' (note, this is the only option in the drop down) however data shown is for current month of March:
<img width="954" alt="Screen Shot 2020-03-24 at 12 23 33 PM" src="https://user-images.githubusercontent.com/28145373/77450977-6eebf400-6dca-11ea-891d-324748870bc4.png">
<img width="939" alt="Screen Shot 2020-03-24 at 12 20 37 PM" src="https://user-images.githubusercontent.com/28145373/77450980-70b5b780-6dca-11ea-9a22-83fbf545a8f5.png">

## Expected result:
I expected the drop down to say 'March 2020' or 'current month' something like that. 

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.7.71 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? unsure, probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc @mandar-brave

**Comment by LaurenWags** [comment]
Reproduces on Nightly 

Brave | 1.8.36 Chromium: 81.0.4044.69 (Official Build) nightly (64-bit)
-- | --
Revision | 6813546031a4bc83f717a2ef7cd4ac6ec1199132-refs/branch-heads/4044@{#776}
OS | macOS Version 10.14.6 (Build 18G3020)

<img width="1002" alt="Screen Shot 2020-03-24 at 2 22 30 PM" src="https://user-images.githubusercontent.com/28145373/77462796-00636200-6ddb-11ea-93d6-d0065c52f640.png">

**Comment by LaurenWags** [comment]
from the spec (outdated):

```
Statement means ‘past tense’. For activities which have concluded. If users want insight into current status, the Rewards Settings page should be modified to accommodate.
```

based on the above, should the statement show current activity (in this case, data for March - tips, token grants accepted, etc)? Maybe the statement shouldn't be available as there isn't any data for previous month? 

cc @mandar-brave for product insight

**Comment by NejcZdovc** [comment]
@LaurenWags yes we decided to show current month as well, I think it's just selection problem (showing wrong month)

**Comment by LaurenWags** [comment]
great, thanks for clarification @NejcZdovc 👍

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.79 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified STR from description
<img width="943" alt="Screen Shot 2020-03-31 at 10 10 33 AM" src="https://user-images.githubusercontent.com/28145373/78036969-e8d72c80-7338-11ea-8f10-009c04ac15a9.png">

* Verified that when you have multiple months, you can select a different month and the monthly statement is updated accordingly:
<img width="953" alt="Screen Shot 2020-03-31 at 10 19 16 AM" src="https://user-images.githubusercontent.com/28145373/78037095-17ed9e00-7339-11ea-8528-add2b76aff9d.png">
<img width="951" alt="Screen Shot 2020-03-31 at 10 19 03 AM" src="https://user-images.githubusercontent.com/28145373/78037102-19b76180-7339-11ea-8ee4-ebba6a115aa3.png">
<img width="952" alt="Screen Shot 2020-03-31 at 10 19 10 AM" src="https://user-images.githubusercontent.com/28145373/78037110-1ae88e80-7339-11ea-9df2-c74c80e59762.png">
