### ISSUE TITLE
move brave://adblock/ to brave://settings/shields

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#8838]
## Description 
Move brave://adblock/ to brave://settings/shields. 
- [ ] Remove Brave Adblock from hamburger menu.
- [ ] Redirect brave://adblock to brave://settings/filters
- [ ] New design for Ad Block page in brave://settings/filters
- [ ] Add Content Filtering section in brave://settings/shields
- [x] Add a link to brave://adblock in the Shields panel

## Designs
<img width="1127" alt="Screen Shot 2022-05-27 at 9 24 16 AM" src="https://user-images.githubusercontent.com/5951041/170739926-50e2f541-addc-413b-bd5d-6400d138d745.png">
remaining screens in Figma

Settings page/shields section and filters page:
https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=1636%3A30096

**Comment by karenkliu** [comment]
@tomlowenthal Can you help fill out some content on the new adblock page?
- `Regional and specific filters` now have a one-line description underneath
- `Custom Filters` now have a one-line description underneath
-  Each filter now has a one-line description of what they are best used for underneath

**Comment by tomlowenthal** [comment]
* Regional and specific filters: "These filters block regional and language-specific trackers and annoyances."
* Custom filters: "Get technical by adding your own specific filters in Adblock Plus filter syntax."

**Comment by Brave-Matt** [comment]
@tomlowenthal,
I'd love to make a nicely formatted copy of this cheat sheet on our Help Center. I feel like we should be linking to our own sources as much as possible (even if "our source" is just a reformatting of something that already exists). 

Will write up a draft and share here if interested 👍

**Comment by rebron** [comment]
@karenkliu Can you update the design section as it relates to https://github.com/brave/brave-browser/issues/9975 I think #9975 has the more recent work.

**Comment by karenkliu** [comment]
@rebron Yep, thanks for catching that. Updated!

**Comment by rebron** [comment]
cc: @pes10k

**Comment by karenkliu** [comment]
Designs updated due to https://github.com/brave/brave-browser/issues/8107

**Comment by Furax-31** [comment]
Hello, is the new interface for Brave Shield going to be on the Nightly version soon?

**Comment by bsclifton** [comment]
@Furax-31 while we have some designs, no work has started yet

**Comment by aguscruiz** [comment]
Updated designs here: 
https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=1636%3A30096

**Comment by MadhaviSeelam** [comment]
Verification `In-progress` using


Brave | 1.41.50 Chromium: 102.0.5005.99 (Official Build) nightly (64-bit)
-- | --
Revision | 870f7bcc58dfa811cc68c2186439721385e086d0-refs/branch-heads/5005@{#1125}
OS | Windows 11 Version 21H2 (Build 22000.675)

**Comment by stephendonner** [comment]
Verification `In-progress` using


Brave | 1.41.50 Chromium: 102.0.5005.99 (Official Build) nightly (64-bit)
-- | --
Revision | 870f7bcc58dfa811cc68c2186439721385e086d0-refs/branch-heads/5005@{#1125}
OS | Windows 11 Version 21H2 (Build 22000.675)


Case 1:`brave://adblock` redirects to  `brave://settings/shields/content-filters`

1. Install `1.41.62`
2. Launch brave
3. Load `brave://adblock` 
4. Confirmed the redirect to `brave://settings/shields/content-filters`


Dark | Light
---|---


Case 2:`brave://adblock` redirect to  `brave://settings/shields/content-filters` from Shields Panel

1. Launch Brave
2. Load `brave.com`
3. Click to open `Shields` panel
4. Click `Filter lists`
5. Confirmed redirect to `brave://settings/shields/content-filters`

Filter_lists | content_filter
---|---

Case 3: `brave://adblock` redirect to  `brave://settings/shields/content-filters` from context menu

1. load `brave.com`
2. right click on the page to open context menu (`Brave > Manage custom filters`)
3. select Manage custom filters
4. confirmed the redirect to `brave://settings/shields/content-filters` in a new tab (or an existing one is present)

Step 2 | Step 4
---|---

**Comment by stephendonner** [comment]
## Verification `PASSED` using




### Case 1:`brave://adblock` redirects to  `brave://settings/shields/filters` - `PASSED`
<details>

1. Install `1.41.82`
2. Launch brave
3. Load `brave://adblock` 
4. Confirmed the redirect to `brave://settings/shields/filters`


Dark | Light
---|---
<img width="1515" alt="Screen Shot 2022-06-28 at 2 22 10 PM" src="https://user-images.githubusercontent.com/387249/176296888-c3ec98e5-d324-415a-88c5-7c2fda735784.png"> | <img width="1515" alt="Screen Shot 2022-06-28 at 2 22 03 PM" src="https://user-images.githubusercontent.com/387249/176297080-91c176bd-4d2f-4a06-a3dc-b6de4bcf8de3.png">



</details>


### Case 2:`brave://adblock` redirect to  `brave://settings/shields/filters` from Shields Panel - `.`
<details>


1. Launch Brave
2. Load `brave.com`
3. Click to open `Shields` panel
4. Click `Content Filtering`
5. Confirmed redirect to `brave://settings/shields/filters`

Content Filtering | filters
---|---


</details>

### Case 3: `brave://adblock` redirect to  `brave://settings/shields/filters` from context menu - `.`
<details>

1. load `brave.com`
2. right click on the page to open context menu (`Brave > Manage custom filters`)
3. select `Manage custom filters`
4. confirmed the redirect to `brave://settings/shields/filters` in a new tab (or an existing one is present)

Step 2 | Step 4
---|---

</details>

### Case 4: Add Content Filtering section in brave://settings/shields - `.`
<details>

1. Launch Brave
2. Load `brave://settings/shields`
3. Verified `Content Filtering` section is displayed
4. Content Filtering text/sub text match to (updated) Figma design
5. Click `Content Filtering` section
6. brave://settings/shields/content-filters page should load in the same tab.
7. Click back arrow next to `Content filters` on top of the page to return to `brave://settings/shields`

Step 3 | Step 7
-------|-------
<img width="1312" alt="Screen Shot 2022-06-14 at 3 42 21 PM" src="https://user-images.githubusercontent.com/387249/173701340-9e76bc55-672c-4e2c-b6e4-45730cf4fb0c.png"> | <img width="1312" alt="Screen Shot 2022-06-14 at 3 42 26 PM" src="https://user-images.githubusercontent.com/387249/173701344-ad6fbb4c-8df5-4e71-b1b6-ebc06bf4fc55.png">


</details>

## New Adblock page functionality

### Case 5:  Content Filtering Functionality in  `brave://settings/shields/filters` - `.`
<details>

1.  Launch Brave
2.  Load `brave://settings/shields/filters`
3. `Content filters` page is loaded successfully
4.  Click  `Show List` to expand the lists in the `Content filtering`
5.  Refresh the page to collapse
6. Search for `EasyList Dutch`
7. `EasyList Dutch` filter should be displayed
8. Select it and refresh the page to see the selection is persisted
9. Uncheck to disable the filter. 
10. Search with a keyword `Easy` and confirmed filtered list displayed

Step 3 & 4| Step 5|Step 6&7|Step 8|Step 10
---|---|---|---|---


</details>

### Case 6:  `Add custom filter lists` functionality - `.`
<details>


1. Load  `brave://settings/shields/filters` 
2. `Content filters` page should be loaded
3. Navigate to `Add custom filter lists` section
4. Enter the URL in the input field `https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Anti-'Custom%20cursors'%20List.txt`
5. Click `Add` button
6. URL is added to `Custom lists` 
7. It should display `Last updated` time when added
8. Click on ellipsis (3 dots) menu 
9. click `Update now` to see the change
10. Click `View Source`
11. The list opens in a new tab 
12. Click `Unsubscribe`
13. Entry should be removed
14. Add one more URL `https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt`
15. URL is displayed in the `Custom filter list` 

Step 6|Step 8|Step 9|Step 10|Step 11|Step 12|Step 13|Step 15
---|---|---|---|---|---|---|---



</details>


### Case 7: `Custom Filters` - Verify blocked page elements are added to the `Custom Filters` section and removing unblocks it - `.`
<details>

1. Load `nytimes.com`
2. Right-click on the page to open context menu 
3. Select `Block element` and click `Create`
4. Select `Manage custom filters` to redirect `brave://settings/shields/filters` in NTP
5. `Custom Filters` field displayed page elements
6. Delete the page elements from the field and click `Save changes`
7. Return to the website
8. Reload the page

Step 3|Step 4|Step 5|Step 7|Step 8
---|---|---|---|----


</details>

### Case 8: Metadata from filter list subscriptions should be available in `brave://settings/shields/content-filters` - `.`
<details>

This was tested as part of #17910: https://github.com/brave/brave-browser/issues/17910#issuecomment-1155703659


</details>

### Case 9: Regression: Verify `Easylist-Cookie List - Filter Obtrusive Cookie Notices` filter list works as expected - `.`

<Details>

1. Visit `https://digikey.com` and confirm that a cookie notice is shown. It will appear either as a banner at the top, or as a popup along the bottom depending on window size.
2. Visit `brave://settings/shields/content-filters` and manually toggle the `Easylist-Cookie List - Filter Obtrusive Cookie Notices` entry to be `enabled`
3.  Visit `https://digikey.com` and refresh page 
4.  Confirm that no cookie notice is shown.
6. Return to `brave://settings/shields/content-filters` and uncheck  `Easylist-Cookie List - Filter Obtrusive Cookie Notices`  
7. Return to `https://digikey.com` and reload the site 
9.  Confirmed that the cookie notice is shown again.

Step 1|Step 2|Step 4|Step 5|Step 7
---|---|---|---|---




</details>
