### ISSUE TITLE
coin URL parameter in Binance Buy URL needs to be changed to crypto

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#8839]
`https://www.binance.us/en/buy-sell-crypto?coin=` -> `https://www.binance.us/en/buy-sell-crypto?crypto=`

**Comment by LaurenWags** [comment]
@ryanml could you please take a look and see if this issue requires manual QA? If no manual QA needed, please add `QA/No` label. If manual QA is needed, please add `QA/Yes` label and a test plan. Thanks! cc @kjozwiak

**Comment by ryanml** [comment]
@LaurenWags `QA/No` added for this one, as it was a small oversight. Thanks!

**Comment by LaurenWags** [comment]
awesome, thanks for reviewing @ryanml!
