### ISSUE TITLE
Dynamically generated PDF does not load properly

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#884]
## Test plan
See https://github.com/brave/brave-core/pull/2342

## Description
Carried over from https://github.com/brave/browser-laptop/issues/8687

## Steps to reproduce
1. Try to load http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.105.6357&rep=rep1&type=pdf
2. Notice there is an error
3. Try same URL in Chrome and verify it works as expected

**Comment by btlechowski** [comment]
+1 from community. The user uses this feature for work.
https://community.brave.com/t/beta-crashes-accessing-sigma-aldrich-site/33524

The page contains dynamically generated pdf, which is placed in an iframe.

link to the [page](https://www.sigmaaldrich.com/MSDS/MSDS/DisplayMSDSPage.do?country=PL&language=pl&productNumber=C1016&brand=SIGALD&PageToGoToURL=https%3A%2F%2Fwww.sigmaaldrich.com%2Fcatalog%2Fsearch%3Fterm%3DCalcium%2Bchloride%26interface%3DAll%26N%3D0%26mode%3Dmatch%2520partialmax%26lang%3Dpl%26region%3DPL%26focus%3Dproduct)

![image](https://user-images.githubusercontent.com/34715963/46219178-ef9d7180-c346-11e8-9692-66b20dca0c4d.png)

**Comment by jasonrsadler** [comment]
Viewing paystubs on namely also produces `invalid pdf structure` error. 

Viewing on browser-laptop works properly
<img width="1410" alt="screen shot 2018-10-07 at 1 06 56 pm" src="https://user-images.githubusercontent.com/25326067/46584510-40d9ef00-ca32-11e8-8db2-f1e1b6b5ff54.png">

**Comment by Liunkae** [comment]
+1 from brave/browser-laptop#15326.

**Comment by SilverPuppy** [comment]
This still is not working, so I'm assuming that for the time being this issue is being overlooked. My current workaround is simply to download instead of using PDF.js but this is a clunky solution. Is this going to be addressed any time soon? As shown by the duplicate bug I just marked, this is affecting more people than just me.

**Comment by jaminroe** [comment]
Not working for me either on Version 0.60.48 Chromium: 72.0.3626.121 (Official Build) (64-bit)

**Comment by GeetaSarvadnya** [comment]
1+https://community.brave.com/t/desktop-sync-error-couldn-t-contact-sync-servers/50543/3

**Comment by GeetaSarvadnya** [comment]
1+ https://community.brave.com/t/cant-download-pdf-unexpected-response-from-server/51666/2

**Comment by Brave-Matt** [comment]
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/bm8xb3/issue_cant_scroll_using_mouse_in_pdfs/

**Comment by GeetaSarvadnya** [comment]
1+https://community.brave.com/t/pdf-will-not-open-due-to-invalid-pdf-structure/64623/2

**Comment by taylormade2k** [comment]
This issue is still persisting as of July 9th, 2019. I guess I will have to download chrome as a backup...

https://www.screencast.com/t/eaUUh0pwnXkD

**Comment by bsclifton** [comment]
@taylormade2k you are definitely welcome to try our Nightly version - it should be fixed there 😄 
https://brave.com/download-nightly/

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

Verified test plan from https://github.com/brave/brave-core/pull/2342
Also successfully opened links from the comments.
