### ISSUE TITLE
monthly contributions not reflected in panel summary

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8841]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/8467

After monthly contributions (recurring tips) have been contributed, they are not reflected on the summary displayed from the rewards panel. They are displayed on the summary on brave://rewards and in the Monthly Contributions table.

## Steps to Reproduce

   1. Launch clean profile from staging with short reconcile interval
   2. Enable Rewards, claim UGP
   3. Do a one time tip, see it reflected in panel summary
   4. Set up a recurring tip.
   5. Add sites to AC table, adjust monthly budget if necessary depending on wallet balance.
   6. Wait for reconcile.
   7. Once reconcile is complete, look at panel summary

## Actual result:

Monthly Contributions are not listed in panel summary
<img width="418" alt="Screen Shot 2020-03-24 at 1 47 25 PM" src="https://user-images.githubusercontent.com/28145373/77460617-b75dde80-6dd7-11ea-9496-c183e4726ed1.png">

## Expected result:
Should be listed in panel summary. Here is what should be shown (from brave://rewards page)
<img width="395" alt="Screen Shot 2020-03-24 at 1 46 12 PM" src="https://user-images.githubusercontent.com/28145373/77460676-cd6b9f00-6dd7-11ea-9b81-f29b579476af.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.7.71 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, does not reproduce in 1.5.115
- Can you reproduce this issue with the beta channel? unsure, probably
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc @mandar-brave @brave/legacy_qa

**Comment by btlechowski** [comment]
Reproduced on Ubuntu

Brave | 1.7.71 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/77511590-acf02300-6e71-11ea-8cd7-ef1f8532a86b.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.79 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/5060
* Verified STR from description
<img width="863" alt="Screen Shot 2020-03-31 at 10 09 55 AM" src="https://user-images.githubusercontent.com/28145373/78036184-02c43f80-7338-11ea-8476-eb4ba518c6f5.png">

* Unable to confirm monthly contributions are reflected in the widget due to https://github.com/brave/brave-browser/issues/8867
