### ISSUE TITLE
monthly statement - AC values sum to amount greater than AC budget

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8844]
## Description 
Probably due to rounding, but AC values on the monthly statement (in Auto-Contribute section) sometimes add up to greater than the actual AC amount.

## Steps to Reproduce

   1. Have mix of verified and non-verified sites set up for AC
   2. Have AC to thru
   3. Look at monthly statement

## Actual result:

0.1 + 0.1 + 0.3 + 4.3 + 0.5 = 5.3, but AC amount was only 5.0 BAT
<img width="972" alt="Screen Shot 2020-03-24 at 3 31 14 PM" src="https://user-images.githubusercontent.com/28145373/77469383-5dfcac00-6de5-11ea-8c67-ac9aa0ab2b03.png">

## Expected result:
AC values add up to AC budget

## Reproduces how often: 

fairly easily, number of sites you have and your budget determines how far off you are though.

## Brave version (brave://version info)

Brave | 1.7.71 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? unsure, probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc @mandar-brave

**Comment by LaurenWags** [comment]
Note, amount on Transactions section matches the amount in the Summary above, not what the sum from Auto Contribute section is:
<img width="890" alt="Screen Shot 2020-03-24 at 3 40 05 PM" src="https://user-images.githubusercontent.com/28145373/77469671-d4011300-6de5-11ea-89db-d5224612e964.png">

**Comment by NejcZdovc** [comment]
@mandar-brave what should we do in this case? if we have one decimal place we will always have this rounding problems
