### ISSUE TITLE
[Android] Estimated bandwidth savings in NTP

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#8845]
## Description 
Please replace HTTPS with Data Saved on Android

@AndriusA has created the code for estimating data saved

For design see: https://github.com/brave/brave-browser/issues/8256#issuecomment-594238584
For implementation see: https://github.com/brave/brave-browser/issues/7783

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm.apk 1.9.74`
![Screenshot_2020-05-22-13-33-55](https://user-images.githubusercontent.com/38657976/82646567-6f6e0300-9c32-11ea-856f-9209b2e078f9.png)
