### ISSUE TITLE
Attribution for Will Christiansen background image(s) link is broken

### ISSUE THREAD

**Issue by mbacchi** [brave/brave-browser#8848]
The photo [Glacier Peak](https://images.squarespace-cdn.com/content/v1/57210e28d51cd4ec63a281b6/1487804158450-CH08RACT0ANGR79WSN5D/ke17ZwdGBToddI8pDm48kGPVK--wGoWXJsqwlxbZlQN7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z4YTzHvnKhyp6Da-NYroOW3ZGjoBKy3azqku80C789l0mwONMR1ELp49Lyc52iWr5enfxu_O4VeONvneR-F6W8oeFhFqSrYyNrfPB9Y70_gvQ/glacier_peak_3600px.jpg) came up and I clicked on the attribution but it brought me to chrome://newtab/www.theskyfolk.com instead of the correct URL.

It looks like the [background.ts](https://github.com/brave/brave-core/blob/7e26b362a8ced71ecae373e5872c088eaaf67fa4/components/brave_new_tab_ui/data/backgrounds.ts#L71-L85) `link` field needs to include https:// at the beginning of the link address, else it will prepend chrome://newtab to the beginning, sending users to the wrong location.

Image 14 also would require the complete link, in addition to image 13.

**Comment by kjozwiak** [comment]
Both of the images from `Will Christiansen` are missing links as @mbacchi mentioned. These are the ones that don't have links when clicking on the credit link:

* https://raw.githubusercontent.com/brave/brave-core/8c4bcfee376033fe8d5528f00657b3b603c16d8c/components/img/newtab/backgrounds/will-christiansen-glacier-peak.webp
* https://raw.githubusercontent.com/brave/brave-core/8c4bcfee376033fe8d5528f00657b3b603c16d8c/components/img/newtab/backgrounds/will-christiansen-ice.webp

**Comment by mbacchi** [comment]
@kjozwiak I opened a PR ([5068](https://github.com/brave/brave-core/pull/5068)) to fix this but the test-install steps failed on mac/windows. I'm going to restart the pr builder and see if it works today.

**Comment by kjozwiak** [comment]
Awesome, thanks @mbacchi 👍 Ran into this when I started running through https://github.com/brave/brave-browser/issues/6904 and noticed you created the issue. Thanks for finding/spotting it!

@rebron @bsclifton should we get this uplifted into `1.7.x` as the new images will be on `Release` in ~a week or so as per https://github.com/brave/brave-browser/issues/6904?

**Comment by bsclifton** [comment]
Sure- that's a small enough one. Let me check out the PR real quick 👍

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.78 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from description
<img width="946" alt="Screen Shot 2020-03-30 at 9 02 18 AM" src="https://user-images.githubusercontent.com/28145373/77915273-2e2a2a00-7265-11ea-9659-d0911ecdb5d4.png">

* Also verified for this image from Will Christiansen
<img width="948" alt="Screen Shot 2020-03-30 at 9 01 24 AM" src="https://user-images.githubusercontent.com/28145373/77915276-2ec2c080-7265-11ea-8ef7-a0f855e2da19.png">
