### ISSUE TITLE
[Android] Update graphics on rewards page when rewards is turned off

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8851]
## Description 
 Update graphics on rewards page when rewards is turned off

## Steps to reproduce 

   1. Enable rewards and turn it off

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/77513479-1d5f6a00-6e9b-11ea-8783-7f3f36ee2191.png)

## Expected result
![image](https://user-images.githubusercontent.com/17010094/77513311-c35ea480-6e9a-11ea-8a79-6382d2be4e86.png)

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.5.115

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc: @jamesmudgett

**Comment by SergeyZhukovsky** [comment]
pushing the issue back as waiting for a new design

**Comment by anthonypkeane** [comment]
Will be fixed once the settings page is added
