### ISSUE TITLE
Fix upgrade path for creds

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#8852]
## Steps to Reproduce

   1. Have old profile with ad promotions
   2. Upgrade to the latest Nightly

## Actual result:

DB is not migrated

## Expected result:
DB should be migrated

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
@NejcZdovc could you take a look and see if this issue requires manual QA? PR says "covered with tests" but I would like to confirm. If no manual QA needed please add `QA/No` label. Thanks! cc @kjozwiak

**Comment by NejcZdovc** [comment]
added `QA/No`

**Comment by LaurenWags** [comment]
thank you!
