### ISSUE TITLE
Implement search volume P3A metric

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#8854]
**Question 1**: 
_How many times did you search last week?_
(The omnibox input doesn't resolve and triggers a search)

**Answers**: 
```
0) Never
1) 1 to 5 times
2) 6 to 10 times
3) 11 to 20 times
4) 21 to 50 times
5) 51 to 100 times
6) 101 to 500 times
7) More than 500 times 
```

**Justification**: 
The volume of search activity generated via Brave will help us identify the optimal search strategy for both product development and partnerships

**Comment by bsclifton** [comment]
@iefremov can you provide a simple test plan for QA to try? Thanks 😄

**Comment by iefremov** [comment]
@LaurenWags For QA:
Do several navigations from omnibox - navigations resolved as web searches should be counted on `brave://local-state`as `Brave.Omnibox.SearchCount` in p3a section. 

Directly typing search queris on e.g. https://google.com should not be counted.

**Comment by GeetaSarvadnya** [comment]
@iefremov If I perform search in different tabs like NT/PT/Guest window tab/Tor tab - Should it consider the search performed in all the type of tabs? or `Brave.Omnibox.SearchCount` response value should show only the search count specific to one type of tabs?

**Comment by iefremov** [comment]
@GeetaSarvadnya good catch - in general, this is expected (by design, we don't care about multiple profiles) But I think in any case we shouln't persist incognito stats. Could you please file a follow-up?

**Comment by rebron** [comment]
@iefremov Adding to the search count for Normal+Private window is ok. Not adding to the search count from Guest window is also ok. I'm going to close out the follow-up issue. 

Thanks @GeetaSarvadnya for clarifying the different window types.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.9.70 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

Verified test plan from the description.
The actual search count is stored in `Preferences` file under `brave->weekly_storage->search_count`
Tested in normal window.

Verified 0 on clean install
`"Brave.Omnibox.SearchCount":{"sent":false,"value":"0"}`
Verified 1 for 1 search
"Brave.Omnibox.SearchCount":{"sent":false,"value":"1"}
Verified 1 for 5 searches
"Brave.Omnibox.SearchCount":{"sent":false,"value":"1"}
Verified 2 for 6 searches
`"Brave.Omnibox.SearchCount":{"sent":false,"value":"2"}`
Verified 2 for 10 searches
`"Brave.Omnibox.SearchCount":{"sent":false,"value":"2"}`
Verified 3 for 11 searches
`"Brave.Omnibox.SearchCount":{"sent":false,"value":"3"}`
Verified 3 for 20 searches
`"Brave.Omnibox.SearchCount":{"sent":false,"value":"3"}`
Verified 4 for 21 searches
`"Brave.Omnibox.SearchCount":{"sent":true,"timestamp":1589868296.894225,"value":"4"}`
Verified 4 for 50 searches
"Brave.Omnibox.SearchCount":{"sent":true,"timestamp":1589868296.894225,"value":"4"}
Verified 5 for 51 searches
"Brave.Omnibox.SearchCount":{"sent":true,"timestamp":1589868296.894225,"value":"5"}
Verified 5 for 100 searches
"Brave.Omnibox.SearchCount":{"sent":true,"timestamp":1589868296.894225,"value":"5"}
Verified 6 for 101 searches
"Brave.Omnibox.SearchCount":{"sent":true,"timestamp":1589868296.894225,"value":"6"}
Verified 6 for 500 searches
"Brave.Omnibox.SearchCount":{"sent":true,"timestamp":1589868296.894225,"value":"6"}
Verified 7 for 501 searches
"Brave.Omnibox.SearchCount":{"sent":true,"timestamp":1589868296.894225,"value":"7"}
