### ISSUE TITLE
Stop blocking: Canvas.{getLineDash,isPointInPath,isPointInStroke,measureText}

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#8855]
see https://github.com/brave/brave-browser/issues/8787

**Comment by bsclifton** [comment]
Updated this issue and PR (https://github.com/brave/brave-core/pull/5062) to have 1.8 milestone

@pilgrim-brave is QA required for this? If so, do you mind updating your top post here to have a basic test plan (and then adding label `QA/Yes`). Thanks 😄
