### ISSUE TITLE
Add transition animation when selecting a widget

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#8856]
## Description 
Add transition animation when selecting a widget from the widget stack to clearly show the change in widget selection.

CSS3 space down animation
See: https://share.goabstract.com/3a8360be-1b3a-4031-928f-d3b2fe40e8f0

## Steps to Reproduce

   1. Go to the new tab page brave://newtab
   2. Ensure two widgets are open: Brave Rewards and Binance.
   3. Select Binance or Brave Rewards. Notice there should be a transition animation when selecting one of the widgets and bringing into the foreground.

## Actual result:
No transition animation.

## Expected result:
Transition animation on selection.

**Comment by TheFlute07** [comment]
Hey, I can help you but I'm new to Github and I really don't know where I can find HTML, CSS and JS files used for these widget to edit them.

**Comment by rebron** [comment]
Closing as stale.
