### ISSUE TITLE
clock widget shouldn't shift when showing/hiding Brave Rewards widget

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#8857]
## Description 
Hiding the Brave Rewards widget shifts the clock widget right. Showing the Brave Rewards widget centers the clock to the Brave Rewards widget. 

Clock should not shift.

## Steps to Reproduce

   1. Go to brave://newtab
   2. Toggle Show/Hide Brave Rewards widget
   3. Notice clock shifts when Brave Rewards widget is toggled. 

## Actual result:
<img width="1283" alt="Screen Shot 2020-03-25 at 8 20 40 AM" src="https://user-images.githubusercontent.com/5951041/77553095-98ac2600-6e71-11ea-8689-56ac57913bed.png">
<img width="1280" alt="Screen Shot 2020-03-25 at 8 20 52 AM" src="https://user-images.githubusercontent.com/5951041/77553107-9d70da00-6e71-11ea-9d72-067db028b5fc.png">

## Expected result:
Clock should stay in the same position as the first screenshot above regardless of whether Brave Rewards widget is shown or hidden.

## Version/Channel Information:
1.5.115 and above.

**Comment by rebron** [comment]
cc: @karenkliu

**Comment by karenkliu** [comment]
@rebron I think we can close this issue - seems like it's fixed.
