### ISSUE TITLE
Stop blocking: SVG.{getTotalLength, getComputedTextLength}

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#8858]
see https://github.com/brave/brave-browser/issues/8787

**Comment by bsclifton** [comment]
Added missing milestone (1.8) to this issue and the PR (https://github.com/brave/brave-core/pull/5063)

@pilgrim-brave any QA needed for this? If so, can you add some manual test steps and label as `QA/Yes`? Thanks 😄

**Comment by KOLANICH** [comment]
>see #8787

is not the rationale for removal. Is it mitigated in ankther way or what?
