### ISSUE TITLE
Send tips button gone

### ISSUE THREAD

**Issue by jeggy** [brave/brave-browser#8859]
## Description 

I can't figure out how to send tips to a websites anymore.

I remember some time ago I just pressed the brave triangle icon in the url bar and there was a big "Send tip" button, but it's gone now.

![image](https://user-images.githubusercontent.com/51459/77582226-f45cca80-6ed6-11ea-84ef-c0f904f67f72.png)

## Brave version (brave://version info)

Brave | 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 2004 (Build 19041.153)
JavaScript | V8 7.8.279.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36

**Comment by rebron** [comment]
@jeggy Can we get you to update to 1.5.115 and see if it's still a problem? https://www.brave.com/download

**Comment by jeggy** [comment]
I just thought it was auto updating itself as there has been times it asked me to restart the browser to install updates.

Anyway this worked, thanks 😃
