### ISSUE TITLE
Indicate Audio During Speech Synthesis Utterance

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#886]
Carried over from https://github.com/brave/browser-laptop/issues/10278

## Steps to reproduce
1. Visit https://jonathansampson.github.io/browser-tests/brave/speech-synth-indicator/
2. Click 'Speak' button
3. Notice no audio icon is shown on tab

**Comment by good-praxis** [comment]
The audio simply doesn't play for me at all
```
Brave: 0.25.2 
V8: 6.9.427.23 
rev: 8ea2a9ce5ca329478186e6393e07f1cf87d34a22 
Muon: 8.1.8 
OS Release: 4.15.0-36-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100
```

Is the API used OS specific?

**Comment by srirambv** [comment]
@good-praxis  You are currently on muon version. The issue will be fixed on [Brave Browser](https://brave.com/download) which is the new version that will replace the muon browser.

**Comment by pes10k** [comment]
@bsclifton is this issue still needed?  Has it been addressed by the Brave Browser update?

**Comment by bsclifton** [comment]
@pes10k the API itself (in the demo) is working for me - but Chromium is not intercepting and marking the tab as playing Audio (doesn't show speaker icon on tab). I think at this point, we can close the issue as stale
