### ISSUE TITLE
Constant cryptocompare and infura calls

### ISSUE THREAD

**Issue by igaul** [brave/brave-browser#8860]
## Description 

Appears that after Brave updated yesterday (24/3/20), it began making many calls to mainnet-infura (every 2 seconds when fails, varying intervals otherwise) and cryptocompare (every 3 minutes). I have never used wallet or any crypto currency features (on this machine).

Only similar issue I could find was on 
[Reddit/brave_browser](https://www.reddit.com/r/brave_browser/comments/f3e27q/why_is_brave_constantly_connecting_to/)

Not end of the world, but would prefer an option to disable, since I and many users do not use Brave for crypto.

## Steps to Reproduce

   1. Brave installed with autoupdate
   2. Brave updates
   3. 

## Brave version (brave://version info)

Brave | 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Windows 10 OS Version 1909 (Build 18363.720)
JavaScript | V8 8.0.426.27
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=LookalikeUrlNavigationSuggestionsUI,AllowPopupsDuringPageUnload,WebXR,NotificationTriggers,AutofillServerCommunication,AudioServiceOutOfProcess,SmsReceiver,VideoPlaybackQuality,WebXrGamepadModule --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\ig\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | 5e3a236d-4113a79e

## Version/Channel Information:

Current

**Comment by kjozwiak** [comment]
@ryanml mind taking a look whenever you have some time? CCing @bbondy @srirambv

**Comment by srirambv** [comment]
Moving to 1.10.x Beta as brave/brave-core#5624 is uplifted

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 Catalina x64` using the following build:

```
Brave | 1.10.81 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.5 (Build 19F101)
```

**`Test Case #1`**

* Launched `1.10.81 CR: 81.0.4044.138` and loaded `brave://wallet` in a new tab without opting into Crypto Wallets
* ensured that `Extensions: Crypto Wallets` wasn't being launched
* ensured that there weren't any `mainnet-infura` calls being made while `Extensions: Crypto Wallets` wasn't running (waited ~30min)

**`Test Case #2`**

* Launched `1.10.81 CR: 81.0.4044.138` and loaded `brave://wallet` in a new tab
* Opted into Crypto Wallets and ensured that `Extensions: Crypto Wallets` was launched
* ensured that `mainnet-infura.brave.com` calls were being made while `Extensions: Crypto Wallets` was running
* ensured `mainnet-infura` calls are going through the `brave.com` proxy

Example:

```
outgoing to mainnet-infura.brave.com (151.101.125.7), Port https (443), Protocol TCP (6), 23.3 kB sent, 1.73 MB received
```

* Restarted the browser and ensured `Extensions: Crypto Wallets wasn't running and `mainnet-infura` calls are not being made.

QA also went through several cases re: lazy loading Crypto Wallets via https://github.com/brave/brave-browser/issues/9757#issuecomment-638480788.

**Comment by kjozwiak** [comment]
@srirambv let me know if there's anything else that needs to be checked that I might have missed with the above STR 👆

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.10.81 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1809 (Build 17763.379)
Component | `0.1.54`

- Verified there is no calls to `api-infura.io` or `min-api.cryptocompare.com` when component is not loaded
- Verified all calls are proxied through `${network}-infura.brave.com`
-------
Verification passed on 

Brave | 1.10.81 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Linux
Component | `0.1.54`

- Verified there is no calls to `api-infura.io` or `min-api.cryptocompare.com` when component is not loaded
- Verified all calls are proxied through `${network}-infura.brave.com`
-------
Verification passed on 

Brave | 1.10.81 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.4 (Build 19E287)
Component | `0.1.54`

- Verified there is no calls to `api-infura.io` or `min-api.cryptocompare.com` when component is not loaded
- Verified all calls are proxied through `${network}-infura.brave.com`
-------

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.10.81 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1809 (Build 17763.379)
Component | `0.1.54`

- Verified there are no calls to infura when component is not loaded
- Verified all calls are proxied through `${network}-infura.brave.com`
