### ISSUE TITLE
Error when clicking any products on burton.com

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#8861]
## Description 
When cross-site trackers blocked switch is on, cannot visit any product page on burton.com, fixed when the switch is off.

## Steps to Reproduce

   1. Visit burton.com
   2. Go to its shop and click any product

## Actual result:
<img width="1283" alt="Screen Shot 2020-03-25 at 2 10 54 PM" src="https://user-images.githubusercontent.com/4730197/77586171-f2791400-6ea2-11ea-86a3-795da2f7c4be.png">

## Expected result:
Product page is shown normally.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
Version 1.8.36 Chromium: 81.0.4044.69 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes, when turning off the cross-site trackers blocked switch on this site.
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by pes10k** [comment]
Can't reproduce, looks like the solved or EL/EP solved.  Closing
