### ISSUE TITLE
macos crash reports are missing channel

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#8864]
## Description 
Crash reports for beta, dev and nightly should have a channel

## Steps to Reproduce
   1.  using a non-release channel go to `brave://crash`
   2. go to `brave://crashes` and make sure that the crash has been sent
   3. check backtrace for the crash id metadata

## Actual result:
No channel value exists

## Expected result:
channel is correctly populated

## Reproduces how often: 
always

## Brave version (brave://version info)
since https://github.com/brave/brave-core/pull/2634

## Version/Channel Information:
beta, dev and nightly

- Can you reproduce this issue with the current release?
no
- Can you reproduce this issue with the beta channel?
yes
- Can you reproduce this issue with the dev channel?
yes
- Can you reproduce this issue with the nightly channel?
yes

**Comment by kjozwiak** [comment]
Moving issue into https://github.com/brave/brave-browser/milestone/92 👍

**Comment by LaurenWags** [comment]
Verified passed using `macOS Mojave 10.14.6 x64`

Brave | 1.7.85 Chromium: 80.0.3987.162 (Official Build) dev (64-bit)
-- | --
Revision | f2c5dd6138153bb0658091205bd1a1717f16081a-refs/branch-heads/3987@{#1034}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified STR from description
* Verified test plan from https://github.com/brave/brave-core/pull/5064#issuecomment-608094245
   * crashed brave using `brave://crash` and noted the `Crash Report ID`
   * crashed brave using `brave://gpucrash` and noted the `Crash Report ID`

<img width="845" alt="Screen Shot 2020-04-03 at 11 52 05 AM" src="https://user-images.githubusercontent.com/28145373/78380526-ffcc8780-75a1-11ea-9708-bd0f14eae014.png">

Checked and ensured that the crashes were reporting the correct channel:

#### Using `brave://crash`

<img width="1563" alt="Screen Shot 2020-04-03 at 11 52 28 AM" src="https://user-images.githubusercontent.com/28145373/78380662-360a0700-75a2-11ea-9ff7-0429c3c4d546.png">

#### Using `brave://crashgpu`

<img width="1568" alt="Screen Shot 2020-04-03 at 11 53 04 AM" src="https://user-images.githubusercontent.com/28145373/78380668-3904f780-75a2-11ea-89b8-12d09622a1d6.png">
