### ISSUE TITLE
Empty new tab page

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#8867]
After updating to  `1.8.42` nightly, NTP rendered nothing like below.

<img width="824" alt="Screen Shot 2020-03-26 at 12 36 23 PM" src="https://user-images.githubusercontent.com/6786187/77611114-da1efd00-6f67-11ea-8d48-1120e04d4aa2.png">
<img width="559" alt="Screen Shot 2020-03-26 at 12 38 25 PM" src="https://user-images.githubusercontent.com/6786187/77611119-dc815700-6f67-11ea-943c-5c53dc3dc63d.png">

Reproduce STEP.
1. Launch with fresh profile
2. Open NTP and only turn rewards On and wait `NaN BAT` is visible in reward widget.
3. Launch again and can see empty NTP
<img width="366" alt="Screen Shot 2020-03-26 at 1 59 50 PM" src="https://user-images.githubusercontent.com/6786187/77612073-84981f80-6f6a-11ea-9bc7-a4f6adf49fdc.png">

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.81 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified the STR from the description. Rewards widget no longer shows NaN and tab does not go blank on restart.
