### ISSUE TITLE
Brave community banned me because I brought up an AI ethics issue they didn't want to talk about

### ISSUE THREAD

**Issue by Tectract** [brave/brave-browser#8869]
A Brave community admin has banned my account on the Brave community since I brought up some issues they apparently didn't like, regarding notification systems like i18n and "red dot" warning systems, and how I said that it is unethical to make humans interact with robotic systems.

They instantly dismissed my discussion about AI ethics and then banned my account for even bringing up the topic, and closed the topic so nobody else can comment. 

Then they had a robotic system send me a warning that my account was disabled. I'm seriously questioning the ETHICS of the Brave community managers. 

I request that AI ethics issues should not be insta-closed and new accounts should not be BANNED and then harassed by AI accounts, on your community board.

**Comment by Tectract** [comment]
Making humans interact with AI, without their consent, is a form of abuse.

**Comment by gingiginger** [comment]
ok boomer

**Comment by Tectract** [comment]
AI ethics is funny, to ignorant little children.

**Comment by gingiginger** [comment]
I seriously don't understand your issue dude, are you complaining because a bot deactivated your account?

**Comment by Tectract** [comment]
Sorry you can't read. Please leave this conversation if you have nothing to add but insults.

> Making humans interact with AI, without their consent, is a form of abuse.

There should be no "bots" that interact with humans, unless those humans ask for the bots to interact with them. "Discobot" is unethical, and it's a form of abuse. I shouldn't have to ignore it. It shouldn't be there, in the first place. 

Instead of saying "OK, your opinion is noted", the mods insta-closed the thread and banned my account, and then had a robot abuse me. The mods have acted unethically. Brave Community is moderated by unethical people who abuse the users.

**Comment by gingiginger** [comment]
Well, there's a simple solution. Don't use the internet

**Comment by Tectract** [comment]
You shouldn't be in this thread. You are contributing nothing but insults.

**Comment by gingiginger** [comment]
Cool

**Comment by gingiginger** [comment]
'tis a throwaway account any daddy <3

**Comment by Tectract** [comment]
I have reported your account to Github admins, Gingiginger. You are a new account with no repos or code contributions who appears to have come to github only to insult and abuse other users.

**Comment by Tectract** [comment]
Mods, please remove Gingigingers comments in this thread.

**Comment by gingiginger** [comment]
oh.. no.. you reported me? what am I going to do. 

Also on a real note. I have no idea how anyone can fathom that humans interacting with AI is any sort of "abuse", like dude fr, what is your deal with that. I didn't mean to troll in the beginning but that really got me. I honestly want to know your answer to that.

**Comment by Tectract** [comment]
Mods, please remove Gingigingers comments in this thread.

**Comment by gingiginger** [comment]
Mods pls do so, Tectract is correct. I need my comments removed.

**Comment by Tectract** [comment]
Mods, please remove Gingigingers comments in this thread.

**Comment by gingiginger** [comment]
dude I'm agreeing with you <3

**Comment by smac89** [comment]
If you include a link to the forum thread where this happened, that would be helpful for others to see what the problem was

**Comment by Tectract** [comment]
I reached out directly to the Brave team management through LinkedIn about this issue. Thanks.

**Comment by bsclifton** [comment]
Hi @Tectract - I've asked a few folks that provide support on Community about this and haven't found anything. Do you have links to the threads? What's your username? If you don't want to share those details here, you can email me at `clifton@brave.com`

`Discobot` is part of the Discourse software that was chosen for community.brave.com; seems you might be having a problem using it. We have no plans to change that software at this time

As GitHub is for tracking issues with the software itself (bugs in product, infrastructure, etc) I'm going to close this out.

**Comment by Tectract** [comment]
I don't like the way your forums are being run. You are banning people and "closing" discussions. I see it as a very hostile forum with mods eager to close issues and censor users, and a "deletionist" as opposed to "archivist" mentality, and here we are in the github issue tickets and I'm facing trolling and abuse from throwaway accounts. 

I think I'll just stop bothering to contribute to Brave issues. Maybe I'll go back to Iceweasel and help them instead.

**Comment by bsclifton** [comment]
@Tectract if you aren't able to provide links/username/etc, I can't personally verify any issues that you've ran into unfortunately. With regards to moderation, discussions which don't follow the [community guidelines](https://community.brave.com/tos) may be closed, not much I can do about that ☹️ For example, the support area [has clear guidelines](https://community.brave.com/t/about-the-support-and-troubleshooting-category/31474).

What in particular are you wanting to discuss that you feel is being hidden or banned? Maybe you're posting in a section that's not related to your topic. There is a `misc` section you can try posting to
