### ISSUE TITLE
[Android] Background video playback settings are reset to default after upgrade

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8871]
## Description 

Background video playback settings are reset to default after upgrade

## Steps to reproduce 

   1. Clean profile 1.5.9
   2. Go to settings and enable background video playback option
   3. Remove the app from memory
   4. Upgrade to 1.5.117
   5. Navigate to settings and observe that the background video playback option is `disabled`

Note:  After upgrade, if I play any YT video and spend sometimes on video and navigate to settings shows the correct state for `background video playback`
## Actual result 
Background video playback settings are reset to default after upgrade

## Expected result

Settings shouldn't  reset to default values
## Issue reproduces how often 
Intermittent

## Issue happens on 
   - Current Play Store version? 
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy
   - Android version: 5.1.1
   
## Brave version

1.5.117
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Linking issue to background video playback crash issue #8786 
cc: @brave/legacy_qa @samartnik @SergeyZhukovsky

**Comment by GeetaSarvadnya** [comment]
The issue still persists in `BraveModernarm 1.5.118.apk`

**Comment by LaurenWags** [comment]
happens intermittently for me on my device. 2x it remained enabled, 1 time it did not.

**Comment by kjozwiak** [comment]
Going to close this off after talking to @SergeyZhukovsky. `1.5.120` is at 100% on the release channel so most of the migrations have been completed. We did get some reports of users experiencing issues but we'll create new issues if those need to be addressed.

However, now that `1.5.120` is released and users are migrating, there's nothing we can do with this particular issue.

@GeetaSarvadnya @srirambv @LaurenWags if feel differently, please create a follow up issue 👍
