### ISSUE TITLE
[Android] Rewards Settings is not visible when grants dropdown is expanded and has multiple entries

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8872]
## Description 
Rewards Settings is not visible when grants is expanded and has multiple entries

## Steps to reproduce 

   1. Claim a few ad grants and UGP grant
   2. Open BR panel and expand the grants dropdown
   3. Settings button is not visible 

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/77668739-cf855780-6fa9-11ea-98af-a334a6c5e17c.png)

## Expected result
Should still be able to see and access rewards setting via panel when grants dropdown is expanded

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc: @gdregalo not sure if this gets fixed on the native UI implementation

**Comment by Miyayes** [comment]
solved with new panel 1.35
