### ISSUE TITLE
[Android] Fix bat points text for jp locale

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#8873]
## Description 
![Screenshot from 2020-03-26 12-19-04](https://user-images.githubusercontent.com/30602739/77670060-0b91cb80-6f5c-11ea-94f3-7dbe2be852eb.png)
For grants instead of `bat` should be `bat points`

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@srirambv does this need to get QA'd or was it checked/QA'd via https://github.com/brave/brave-browser/issues/8541? If so, lets label this as `QA/No` 👍

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.118 x64 stable build
- Grants details on BR Panel
![image](https://user-images.githubusercontent.com/17010094/78005152-c6eda200-7358-11ea-9f45-fd860ba44557.png)
- Rewards panel 
![image](https://user-images.githubusercontent.com/17010094/78005022-9c034e00-7358-11ea-91c2-9588c15be13a.png)
- Tips panel 
![image](https://user-images.githubusercontent.com/17010094/78005046-a45b8900-7358-11ea-9217-e7abbe221ef9.png)
- AC monthly setting
![image](https://user-images.githubusercontent.com/17010094/78005093-b5a49580-7358-11ea-9204-f288d7e81047.png)
- One time tip
![image](https://user-images.githubusercontent.com/17010094/78004982-8beb6e80-7358-11ea-96c6-c1aa3c5e42ce.png)
![image](https://user-images.githubusercontent.com/17010094/78004949-7d9d5280-7358-11ea-871a-533e338f093c.png)
- Recurring tip 
![image](https://user-images.githubusercontent.com/17010094/78004993-9148b900-7358-11ea-979d-0eec02557258.png)
![image](https://user-images.githubusercontent.com/17010094/78004970-8726ba80-7358-11ea-8c6b-d96fc7c8c776.png)
-------------
Verification passed on Samsung Tab A with Android 9.0 running 1.5.118 x64 stable build
- Grants details on BR panel
![image](https://user-images.githubusercontent.com/17010094/78008896-de7b5980-735d-11ea-96ea-ff9ff8a6256b.png)
- Rewards panel
![image](https://user-images.githubusercontent.com/17010094/78008887-dc18ff80-735d-11ea-9dfb-680e42629c06.png)
- Tips panel
- AC monthly setting
![image](https://user-images.githubusercontent.com/17010094/78008861-d3c0c480-735d-11ea-8d01-d52afbc9bc07.png)
- One time tip
![image](https://user-images.githubusercontent.com/17010094/78008832-cb688980-735d-11ea-8e0e-dd53db1b00ec.png)
![image](https://user-images.githubusercontent.com/17010094/78008917-e3400d80-735d-11ea-8918-ad14b0ad6207.png)
- Recurring tip
![image](https://user-images.githubusercontent.com/17010094/78008815-c60b3f00-735d-11ea-9ddc-54eb30127f75.png)
![image](https://user-images.githubusercontent.com/17010094/78008849-cf94a700-735d-11ea-8fe3-08fa0cc9d6e0.png)
- Wallet details 
![image](https://user-images.githubusercontent.com/17010094/78008947-ee933900-735d-11ea-95d4-3518b4586ced.png)
