### ISSUE TITLE
[Android] Follow up of #8259 - Restore All is overlapping on Auto-contribute text 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8875]
## Description 
Follow up of #8259 - Restore All is overlapping on Auto-contribute text 

## Steps to reproduce 

   1. Launch brave with staging flag
   2. Enable rewards and claim grants
   3. Add 4 sites in A-C table
   4. Exclude 3 sites by clicking on the trash icon
   5. Open Auto-Contribute advanced settings dialog 
   6. Click on Sites Excluded menu
   7. `Restore All` is overlapping on `Auto-contribute` text 
   

## Actual result 
Restore All is overlapping on Auto-contribute text 
![image](https://user-images.githubusercontent.com/38657976/77677078-365c3e00-6fb5-11ea-93b7-a53bbe852fe9.png)

## Expected result

Restore All is should not overlap on Auto-contribute text 
## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.5.117

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @gdregalo @samartnik @SergeyZhukovsky

**Comment by srirambv** [comment]
Moving to 1.7.x release as this is not critical for this release

**Comment by SergeyZhukovsky** [comment]
waiting for a new design of settings page

**Comment by anthonypkeane** [comment]
Once the screen is built natively we can close this issue. See #10472

**Comment by emerick** [comment]
I'm unable to repro, see screenshot. Can we retest this one please?

![Screenshot_20220125-093517](https://user-images.githubusercontent.com/5033691/150997205-2534903c-4644-4827-9626-4bd36450270f.png)

**Comment by Uni-verse** [comment]
Was able to repro with STR above on `Samsung GS 21` | `Android 12` | `1.36.90, Chromium 98.0.4758.87`

![Screenshot_20220211-073348_Brave](https://user-images.githubusercontent.com/17885425/153520550-5d9330a2-32dd-4f18-8968-5b5db39b1499.jpg)

**Comment by Uni-verse** [comment]
Repro'd on 1.36.105, C99

**Comment by Uni-verse** [comment]
@SergeyZhukovsky Im still able to repro this on 1.36.107 version.

**Comment by SergeyZhukovsky** [comment]
cc @emerick

**Comment by kjozwiak** [comment]
@emerick I don't see any PRs associated with this one. If there's a PR opened, we usually don't re-open the issues and just create a new follow up. This is so we don't have several PRs associated with a single issue that have been merged into `master` at different times. It just makes things confusing. However, if there's no PR,  we can just re-open this one.

Removing this from the `1.36.x` as well as it's not `release/blocking`.

**Comment by emerick** [comment]
@kjozwiak Hey Kamil, thanks for the note on that. Yeah, there was no PR for this one as we just wanted to retest it to see if it's still an issue. Will keep that in mind for the future though, makes total sense!

Marking this for triage in Rewards so we can figure out how best to address this.

**Comment by Miyayes** [comment]
@GeetaSarvadnya Is this still an issue?

**Comment by GeetaSarvadnya** [comment]
Verified the issue against the build `1.51.12` - Issue is not reproducible any more hence closing the issue.

Example | Example
----------|----------
![Screenshot_20230602_131629](https://github.com/brave/brave-browser/assets/38657976/8a2dd081-afa3-494e-acc3-7d6e9d1f9f51) | ![Screenshot_20230602_131634](https://github.com/brave/brave-browser/assets/38657976/b59c1a2b-a8db-40c5-85cc-b58e4a23f0f3)
