### ISSUE TITLE
[Issue] : Chrome App Issue - Zoom.us

### ISSUE THREAD

**Issue by jasonkolodziej** [brave/brave-browser#8877]
## Description 
When adding the zoom.us application to Brave from chrome web store `https://chrome.google.com/webstore/detail/zoom/hmbjbjdpkobdjplfobhljndfdfdipjhg?hl=en-US`
The application installs fine. However, there must be a setting or flag with in brave that is prohibiting the ability to sign in to any zoom.us account. Signing into this application works just fine with Google Chrome.

## Steps to Reproduce

   1. Download app
   1a. One might need to redownload the extension if there is a failure through brave. I got this with my Mac running Catalina latest version.
   2.  go to `brave://apps/` click on zoom
   3. try either signing in to a normal zoom account or even via SSO

### Via SSO login:
![image](https://user-images.githubusercontent.com/42076058/77689002-f5413b00-6f6e-11ea-8698-2d8543968623.png)
You can click the `continue` button as much as you would like, it will not communicate with the necessary servers to properly show the next screen.
### Via normal login:
![image](https://user-images.githubusercontent.com/42076058/77689191-44876b80-6f6f-11ea-86f0-6dc804b0ee44.png)
![image](https://user-images.githubusercontent.com/42076058/77689270-654fc100-6f6f-11ea-9739-1631c7d687e4.png)
As you can see there is a login timeout for this one.

## Expected result:
Simply to either login or have a redirect to your SSO to login.

## Reproduces how often: 
N/a

## Brave version (brave://version info)

Brave | 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.15.3 (Build 19D76)
JavaScript | V8 8.0.426.27
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --disable-domain-reliability --disable-features=WebXR,VideoPlaybackQuality,WebXrGamepadModule,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,AutofillServerCommunication --disable-sync --disable-webrtc-apm-in-audio-service --enable-audio-service-sandbox --enable-dom-distiller --enable-features=SimplifyHttpsIndicator,WebUIDarkMode,PasswordImport --extension-content-verification=enforce_strict --extensions-install-verification=enforce --no-pings --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,AllowPopupsDuringPageUnload,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,WebXrGamepadModule,VideoPlaybackQuality,WebXR --flag-switches-begin --extensions-on-chrome-urls --load-media-router-component-extension=1 --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator,BraveAdblockCosmeticFiltering --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/------------/Library/Application Support/BraveSoftware/Brave-Browser/Default

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 
     *you can reproduce these steps on the latest version to see how it should work.*

## Miscellaneous Information:
You will need to have a zoom.us account.

**Comment by jasonkolodziej** [comment]
@rebron Were you able to resolve this by chance?

**Comment by JGuo** [comment]
This is still broken btw - zoom login via google or facebook is broken if brave is your default browser

**Comment by rebron** [comment]
Closing and marking as wontfix per https://blog.chromium.org/2020/08/changes-to-chrome-app-support-timeline.html
Apps via the Chrome Web Store have been gone for quite some time now.
