### ISSUE TITLE
Delay incrementing shields counter until first render

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#888]
## Description 

Shields starts showing blocked count even before page is loaded in webview

## Steps to Reproduce

   1. Upgrade to 0.54.3
   2. Open a new tab and load a site
   3. Before the page is loaded in webview, shields starts showing blocked count in badge even on disabled icon before changing to active icon (see recording below)

## Actual result:

![blockcount](https://user-images.githubusercontent.com/17010094/44852647-cdbeab00-ac31-11e8-84ad-08f3a9fcf02b.gif)

## Expected result:
Should only show badge when icon is active and not on inactive icon

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Brave | 0.54.3 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | Windows

### Reproducible on current release:

No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @brave/legacy_qa @bbondy @petemill

**Comment by LaurenWags** [comment]
Reproduced on macOS with `0.55.3`

**Comment by tomlowenthal** [comment]
Updated title. Cezar, if this isn't implementable with the APIs you currently have access to, I'll move it to the backend pile.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.68.116 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Windows 10 OS Version 1803 (Build 17134.523)

- Verified the test plan from https://github.com/brave/brave-core/pull/2507
- Verified on clean profile and upgraded profile
