### ISSUE TITLE
[Android] Migrate ref code from tabs to core

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#8880]
Add ref code to migration process.
Steps for QA on how to check will be discussed on slack.

**Comment by kjozwiak** [comment]
**`Case #1 - Updating from 1.5.9 CR: 80.0.3987.132 --> 1.5.117 CR: 80.0.3987.149`**

* install `1.5.9 CR: 80.0.3987.132` using a production referral code
* once installed, ensured that the `promoCode` appears under `Referrer program info` in settings
* updated `1.5.9 CR: 80.0.3987.132` --> `1.5.117 CR: 80.0.3987.149` using the APK's @samartnik provided QA with the 10min confirmation pings
* once updated, share the `download_id` with @keur so he can set the timestamp in the production database to +30 days for your particular referral
* wait ~10min and you the referral should eventually finalize
* ensure that @keur also verifies that the referral appears as finalized via the back-end

```
[ERROR:brave_referrals_service.cc(203)] SAM: BraveReferralsService::OnFinalizationChecksTimerFired
[ERROR:brave_referrals_service.cc(427)] SAM: BraveReferralsService::MaybeCheckForReferralFinalization start
[ERROR:brave_referrals_service.cc(432)] SAM: BraveReferralsService::MaybeCheckForReferralFinalization attempt
[ERROR:brave_referrals_service.cc(445)] SAM: BraveReferralsService::MaybeCheckForReferralFinalization actual check
[INFO:brave_referrals_service.cc(333)] SAM: Finalized!!!
```

**`Case #2- Clean install of 1.5.117 CR: 80.0.3987.149`**

* visit a production referral page and select `Download for Android` which opens the GPS
* once the GPS is opened, side load/install `1.5.117 CR: 80.0.3987.149` using the APK's @samartnik provided QA with the 10min confirmation pings
* visit `brave://local-state` and ensure that `promoCode` is being listed
* share the `download_id` with @keur so he can set the timestamp in the production database to +30 days for your particular referral
* wait ~10min and you the referral should eventually finalize
* ensure that @keur also verifies that the referral appears as finalized via the back-end

```
[ERROR:brave_referrals_service.cc(203)] SAM: BraveReferralsService::OnFinalizationChecksTimerFired
[ERROR:brave_referrals_service.cc(427)] SAM: BraveReferralsService::MaybeCheckForReferralFinalization start
[ERROR:brave_referrals_service.cc(432)] SAM: BraveReferralsService::MaybeCheckForReferralFinalization attempt
[ERROR:brave_referrals_service.cc(445)] SAM: BraveReferralsService::MaybeCheckForReferralFinalization actual check
[INFO:brave_referrals_service.cc(333)] SAM: Finalized!!!
```

Also ensured that once finalized, any subsequent pings returned the following as the referral was already finalized:

```
[ERROR:brave_referrals_service.cc(314)] SAM: Failed to perform referral finalization check, error: 0, response code: 409, payload: {"statusCode":409,"error":"Conflict","message":"download already finalized"}, url: https://laptop-updates.brave.com/promo/activity
```

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy S10+` with `Android 10` using the custom APK's builds that @samartnik which pings the referral server ~10min for confirmations.

* ensured that the STR/Cases outlined via https://github.com/brave/brave-browser/issues/8880#issuecomment-606432002 passed without any issues.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10

Upgrade test
- Installed 1.5.9 via referral code
- Verified Ref code and Download ID are shown in settings
- Verified Download ID is shown in backend
- Upgrade to 1.5.117 x64 build and migration works fine and ref code is retained in `chrome://local-state
- Verified backend confirmation about download finalizing 

Clean install test
- Visit referral page to trigger GPS install
- Side load 1.5.117 x64 build with 10 min confirmation
- Backed verified Download ID
- Verified backend confirmation about download finalizing
