### ISSUE TITLE
`TipConnectedPublisherAnonAndConnected` browser test intermittently times out

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#8881]
## Description 
Currently, master has intermittent failures for `BraveRewardsBrowserTest.TipConnectedPublisherAnonAndConnected`. All other browser tests seem to work fine- but as a reviewer we need to either make a call:
1. Replay and hope that tests run fine 2nd time
2. Ignore that test

## Steps to Reproduce

   1. Have a pull request against master
   2. Check PR builder

## Actual result:
Sometimes you'll see an error like:
```
11:28:39  [508/508] BraveRewardsBrowserTest.TipConnectedPublisherAnonAndConnected (TIMED OUT)
11:28:39  1 test timed out:
11:28:39      BraveRewardsBrowserTest.TipConnectedPublisherAnonAndConnected (../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:2762)
```

## Expected result:
- Test should either pass or (if there is a problem) fail.
- If test is unreliable, it should be disabled

## Reproduces how often: 
Intermittent

cc: @NejcZdovc @tmancey

**Comment by rebron** [comment]
At @emerick @NejcZdovc can you guys take a look? Causing a lot of CI failures.

**Comment by NejcZdovc** [comment]
moving to global project

**Comment by NejcZdovc** [comment]
should be fixed with https://github.com/brave/brave-core/pull/4114
