### ISSUE TITLE
Reduce flicker on the New Tab Page caused by dark widget overlays and make widgets in widget stack easier to hide

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#8883]
## Description 
Currently, hovering over the widgets on the New Tab Page creates a distracting flickering effect:

![widget overlay flickers](https://user-images.githubusercontent.com/2388823/77709213-950ac300-6f87-11ea-8841-0332cf253ee2.gif)

## Designs
Reduce the flickering effect by updating the hover interaction on widgets. 

For Brave Stats, Top sites, and Clock:
1. When the user hovers over widget area, show menu icon
2. When the user hovers over the menu icon, show darkened widget overlay

For widgets in the widget stack (Binance and Brave Rewards):
1. When the user hovers over the widget area, show menu icon inside the widget area

The result should look like this:

![widget hover update](https://user-images.githubusercontent.com/2388823/77710848-6b07cf80-6f8c-11ea-9b21-91508799e8ed.gif)

Clicking on the menu icon should still show widget options.

Brave Stats:

<img width="663" alt="menu brave stats" src="https://user-images.githubusercontent.com/2388823/77790504-33e3fd80-7022-11ea-8124-73d2870339c8.png">

Top Sites:

<img width="366" alt="menu top sites" src="https://user-images.githubusercontent.com/2388823/77790522-39d9de80-7022-11ea-83f7-f9c43ae8c34b.png">

Brave Rewards:

<img width="237" alt="menu brave rewards" src="https://user-images.githubusercontent.com/2388823/77790535-4100ec80-7022-11ea-8ade-fd99420104c7.png">

"Learn more" links to [https://brave.com/brave-rewards/]

Binance: 

<img width="238" alt="menu binance" src="https://user-images.githubusercontent.com/2388823/77790546-45c5a080-7022-11ea-96d6-ba7fcced2119.png">

"Learn more" links to **TBD**

## Specs and Assets
new icon for "Learn more" and "Hide" in the widget menu
[assets.zip](https://github.com/brave/brave-browser/files/4395417/assets.zip)

the titles on widgets in the widget stack have a reduced size now to make room for the widget menu icon. check Abstract for css/sizing/layout here: https://share.goabstract.com/d479d637-86a1-40d5-a7e1-b1fb09ce2621?mode=design&sha=84ab0ce6b6e28d23439f74fdad9b2c07770e35f7

Widget menu icon padding:

![specs menu icon in widget](https://user-images.githubusercontent.com/2388823/77798389-fe461100-702f-11ea-8966-8c48569064ea.png)

![specs menu icon in card stack](https://user-images.githubusercontent.com/2388823/77808403-630d6580-7048-11ea-89f1-77f93e2f7ae7.png)

**Comment by rebron** [comment]
@karenkliu Is this nightly?

**Comment by LaurenWags** [comment]
@ryanml could you take a look and let us know if this issue requires manual QA? Please add `QA/Yes` label and a test plan (sometimes designs include items not implemented - if this is the case please specify). If no manual QA needed, please add `QA/No` label. Thanks! cc @kjozwiak

**Comment by LaurenWags** [comment]
@ryanml pinging on https://github.com/brave/brave-browser/issues/8883#issuecomment-611623397 - could you take a look please? Thanks! cc @kjozwiak @bsclifton

**Comment by ryanml** [comment]
@LaurenWags `qa/yes` added, test plan included. It mostly is just verifying what Karen described above. Thanks!

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.8.82 Chromium: 81.0.4044.113 (Official Build) dev (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from description
*Encountered/logged the following issues:
   - https://github.com/brave/brave-browser/issues/9247
   - https://github.com/brave/brave-browser/issues/9387
   - https://github.com/brave/brave-browser/issues/9389
   - https://github.com/brave/brave-browser/issues/9390
   - https://github.com/brave/brave-browser/issues/9391
