### ISSUE TITLE
[Android]  No entry for chrome://rewards/ and chrome://rewards-internals/ under  chrome://chrome-urls

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8886]
## Description 
 No entry for chrome://rewards/ and chrome://rewards-internals/ under  chrome://chrome-urls

## Steps to reproduce 

   1. Open chrome://chrome-urls
   2. No entry for chrome://rewards/ and chrome://rewards-internals/

## Actual result 
 No entry for chrome://rewards/ and chrome://rewards-internals/

## Expected result
Have an entry for chrome://rewards/ and chrome://rewards-internals/

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.5.117

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by kjozwiak** [comment]
Believe this needs to be fixed on desktop as well as both `chrome://rewards` and `brave://rewards-internals` are not listed in `brave://about` or `chrome://about`.

Also created https://github.com/brave/brave-browser/issues/7422 a while back that would resolve the above as well.

**Comment by emerick** [comment]
@Miyayes @deeppandya Those URLs were added for desktop and Android recently, so I think this can probably be closed out.
