### ISSUE TITLE
[Android] Removed bookmarks are not synced across the devices in sync chain

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8888]
## Description 
Removed bookmarks are not synced across the devices in sync chain

## Devices
 Android ARM - 1.5.117
Desktop Windows - 1.7.74

## Steps to reproduce 

   1. Clean profile android 1.5.117
   2. Add few bookmarks before sync
   3. Clean profile desktop 1.7.74
   4. Add few bookmarks before sync
   5. Establish sync between Android and Desktop via QR code
   6. Make sure BM's which are added before the sync chain are synced across both devices
   7. Add few new bookmarks in Desktop and Android 
   8. Make sure new bookmarks added across both devices
   9. Remove few bookmarks from desktop
  10. Bookmarks which are removed from desktop are not removed from android

## Actual result 
Removed bookmarks are not synced across the devices in sync chain
## Expected result

Removed bookmarks should sync across the devices in the sync chain

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? Not sure
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.5.117

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @AlexeyBarabash @SergeyZhukovsky

**Comment by madhums** [comment]
Also doesn't work on iOS or Mac! It just stopped syncing suddenly. I also find that the documentation on sync is outdated, I am using version `Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)` and cannot find any sync menu or feature as described [here](https://support.brave.com/hc/en-us/articles/360021218111-How-do-I-set-up-Sync-)

**Comment by madhums** [comment]
To me it looks like brave simply removed sync feature on desktop! Is this true? @brave-dev 

Nothing at `brave://sync/` 

<img width="400" alt="Screenshot 2020-04-07 at 17 01 23" src="https://user-images.githubusercontent.com/123815/78685041-814d4e00-78f1-11ea-98a6-9b09249eb0a8.png">

**Comment by madhums** [comment]
Oh I see the [reddit post](https://www.reddit.com/r/brave_browser/comments/f1yyl3/regarding_brave_v13113_frequent_crashes_and/), looks like it's still not working after all the updates. Any ETA on when sync will be enabled again? @brave-dev

**Comment by jsecretan** [comment]
@madhums there is a new version of Brave sync that should address these issues, coming in 1.12.  You can try in Desktop Nightly and Android Nightly.
