### ISSUE TITLE
Video not loading

### ISSUE THREAD

**Issue by InternetDownloader** [brave/brave-browser#8889]
## Description 
Sometimes YouTube doesn't load the videos; it just gets stuck

## Steps to Reproduce

   1. Visit https://www.youtube.com/watch?v=dQw4w9WgXcQ
   2. Wait for video to load
   3. Be sad about it

## Actual result:
![image](https://user-images.githubusercontent.com/26020638/77780705-a6001680-7011-11ea-909c-0a4fda3ce529.png)

## Expected result:
Video should load

**Comment by bsclifton** [comment]
Get outta here with this Roll Roll stuff! It's 2020 already 😂

**Comment by rebron** [comment]
@InternetDownloader YouTube has been having some issues lately: `https://www.theverge.com/2020/3/24/21192384/youtube-video-quality-reduced-hd-broadband-europe-streaming`

Please try again. You can try unplugging your machine and plug it back in again.
