### ISSUE TITLE
Provide additional details under crash id tries to open code.google.com 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#889]
## Description 

Provide additional details under crash id tries to open code.google.com 

## Steps to Reproduce

   1. Open a new tab
   2. Visit `chrome://crash` in a new tab, tab crashes
   3. Visit `chrome://crashes` in a new tab, ensure crash report is uploaded
   4. If the crash report is not uploaded click  send now and restart the browser
   5. Click on `Provide additional details` under the sent crash report, opens a 
 new tab with the following link and opens Google login page to send the report details https://code.google.com/p/chromium/issues/entry?template=Crash%20Report&comment=IMPORTANT%3A%20Your%20crash%20has%20already%20been%20automatically%20reported%20to%20our%20crash%20system.%20Please%20file%20this%20bug%20only%20if%20you%20can%20provide%20more%20information%20about%20it.%0A%0A%0AChrome%20Version%3A%2070.0.54.3%0AOperating%20System%3A%20Windows%20NT%2010.0.17134%0A%0AURL%20(if%20applicable)%20where%20crash%20occurred%3A%0A%0ACan%20you%20reproduce%20this%20crash%3F%0A%0AWhat%20steps%20will%20reproduce%20this%20crash%3F%20(If%20it%27s%20not%20reproducible%2C%20what%20were%20you%20doing%20just%20before%20the%20crash%3F)%0A1.%0A2.%0A3.%0A%0A****DO%20NOT%20CHANGE%20BELOW%20THIS%20LINE****%0ACrash%20ID%3A%20crash%2F<CRASH ID> &labels=Restrict-View-EditIssue%2CStability-Crash%2CUser-Submitted

## Actual result:

Provide additional details under crash id tries to open code.google.com 

## Expected result:
Should point to brave gh repo

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Brave | 0.54.3 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | Windows

### Reproducible on current release:

No b-l points to gh repo to log an issue

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @bbondy please move it back to backlog if needed 
cc: @simonhong @bridiver

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/specify-more-details-under-chrome-crashes-leads-to-a-google-page/53368?u=eljuno

**Comment by pilgrim-brave** [comment]
QA test plan: https://github.com/brave/brave-core/pull/2564#issuecomment-497713476

**Comment by btlechowski** [comment]
Still reproducible on 0.66.92.

@rebron @kjozwiak It seems that the fix is ready to be merged, but was no merged. https://github.com/brave/brave-core/pull/2564

**Comment by kjozwiak** [comment]
Adding the following into `0.68.x - Nightly` as per https://github.com/brave/brave-core/pull/2564#event-2424907276.

**Comment by srirambv** [comment]
Marking as Windows and Mac as there is no send more info button on Linux for crash reports
![image](https://user-images.githubusercontent.com/17010094/62155053-02216800-b2d6-11e9-8eef-c5a22bb8dc0d.png)

**Comment by GeetaSarvadnya** [comment]
Step4: After clicking on send now and restart the browser, uploaded crash report is NOT reflected in Windows 10 x64 - `0.68.113`

![image](https://user-images.githubusercontent.com/38657976/62158137-6bcc6100-b32c-11e9-8701-d92aa390e7cb.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.68.118 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2564#issuecomment-497713476
![Screen Shot 2019-08-05 at 4 53 53 PM](https://user-images.githubusercontent.com/28145373/62494508-b3764100-b7a1-11e9-8179-84a893f1202f.png)
