### ISSUE TITLE
[Android] Crash on Tracing settings

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#8890]
## Description 
Browser crashes if you click Tracing settings from Settings->Developer options->Tracing

## Steps to reproduce 

   1. Navigate to Settings->Developer options
   2. Click a Tracing menu

## Actual result 
There is a crash

## Expected result
Should not crash

## Issue reproduces how often 
always

## Issue happens on 
   - Current Play Store version? no
   - Beta build? yes

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5. 118 x64 stable build
- Verified no crash on when selecting tracing option from developers menu
------
Verification passed on Samsung Tab A  with Android 9.0 running 1.5.118 x64 stable build
- Verified no crash on when selecting tracing option from developers menu
------
