### ISSUE TITLE
About Brave dialog Reporting Wrong Brave Version in Ubuntu 19.1

### ISSUE THREAD

**Issue by Firewall999** [brave/brave-browser#8891]
## Description 
After successfully upgrading Brave-Browser to latest Linux version (1.5.??) using Ubuntu 19.1 Terminal, and getting confirmation in terminal, the "About Brave" dialog still reports the old version (1.1.23).  

## Steps to Reproduce
   1.   In Ubuntu 19.1, use terminal to upgrade Brave version 1.1.23 to the latest Brave Linux version.  Notice terminal output, "...upgraded to 1.5.xx..."
   2.   Close the browser.
   3.   Open the browser, and select "About Brave."

## Actual result:
Says it is still 1.1.23.

## Expected result:
Should give the new version number, in my case 1.5.??.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
Brave	1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)
Revision	c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS	Linux
JavaScript	V8 7.9.317.32
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
Command Line	/snap/brave/63/opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-oop-rasterization=Enabled --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,WebXR,WebXrGamepadModule,UnifiedConsent,AllowPopupsDuringPageUnload,SyncUSSBookmarks --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service
Executable Path	/snap/brave/63/opt/brave.com/brave/brave
Profile Path	/home/jackson/snap/brave/63/.config/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:
UNKNOWN

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  NO
- Does the issue resolve itself when disabling Brave Rewards?  NO
- Is the issue reproducible on the latest version of Chrome?  UNKNOWN

**Comment by bsclifton** [comment]
@Firewall999 we haven't updated the snaps in a bit, unfortunately. There is a pending issue to be solved before we can https://github.com/brave/devops/issues/2690 (`Brave v1.4.95 snap build fails with desktop-gtk3 conflict`)
cc: @mbacchi @mihaiplesa

**Comment by fmarier** [comment]
@Firewall999 It looks like you have two separate versions of Brave installed. One is the officially supported package (up-to-ate) and one is the snap (out-of-date).

Like @bsclifton, I suggest you remove the Snap from your system:

    sudo snap remove brave

Then you should be able to launch the latest version of Brave which appears to already be installed on your machine.

**Comment by bsclifton** [comment]
The executable name should be `brave-browser` now; I think `brave` is used for the snap and also (in older cases) for the old Muon browser

**Comment by Firewall999** [comment]
2 PROBLEMS SOLVED BY REMOVING DUPLICATE INSTALL

1. Now running latest version
2. Default flag now being honored.

THANK YOU!
     On Monday, March 30, 2020, 04:30:26 PM EDT, Brian Clifton <notifications@github.com> wrote:  
 
 


The executable name should be brave-browser now; I think brave is used for the snap and also (in older cases) for the old Muon browser

**Comment by bsclifton** [comment]
Thanks for following up and confirming, @Firewall999! 😄 Super glad that you're resolved
