### ISSUE TITLE
[Android] NTP page image cropped after rotation

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#8892]
After rotating the device, NTP image is cropped

## Steps to reproduce 

   1. Open NTP
   2. Open `google.com` in another tab
   3. Rotate the screen
   4. Make the NTP from step 1 active

## Actual result 
NTP image is cropped
![Screenshot_20200327-180934_Brave](https://user-images.githubusercontent.com/34715963/77782173-26953600-7057-11ea-9da2-f8e378a988fc.jpg)

## Expected result
NTP image is not cropped

## Issue reproduces how often 
100% repro rate

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Tablet
   - Android version: 9.0
   
## Brave version
BraveModernarm v1.5.117 on Samsung Galaxy Tab S5e (Android 9.0)

cc @brave/legacy_qa @deeppandya @SergeyZhukovsky

**Comment by kjozwiak** [comment]
Verification **PASSED**  on `Samsung Galaxy S10+` running `Android 10` using the following build:

```
Brave 1.8.93 CR: 81.0.4044.129
```

**`Case #1`**

* Open a NTP
* Open another tab and load https://www.google.ca and rotate into `landscape`
* switch back to the NTP (you'll notice it being cut off)

**`Case #2`**

* Open a NTP
* Open another tab and load https://www.google.ca
* switch back to the NTP and rotate to `landscape`
* switch back to the tab with https://www.google.ca and rotate to `portrait`
* switch back to the NTP
