### ISSUE TITLE
Two one time tips are sent at a time

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8895]
## Description 

Two one time tips are sent at a time

## Steps to Reproduce

   1. Clean profile 1.7.74
   2. Enable rewards
   3. Connect KYC'd uphold account 
   4. Open a verified publisher
   5. Send a one time tip of 1 BAT to above pubs
   6. Two one time tip entries are shown for the same publisher in Tips panel also 1st entry will always have 0.8 BAT allocated and 2nd entry will have 1 BAT allocated. But from uphold only 1 BAT is deducted at a time

## Actual result:

Two one time tips are sent at a time
![image](https://user-images.githubusercontent.com/38657976/77784800-23af3b00-7081-11ea-916b-72ab1a81214c.png)

## Expected result:
At a time only one tip should be sent

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.7.74 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA 

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron

**Comment by NejcZdovc** [comment]
let's recheck this one with build higher then `1.7.76`. There was a fix for this

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya could you please test it again on 1.7.78

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc I just verified one tip against the build Dev 1.7.78. I sent the one-time tip of 1 BAT to brinabondy.com. After tip I can see two entries in Tips panel one entry with `0.3 BAT` and 2nd entry with `0.8` BAT. Wallet balance is deducted by 1 BAT and `One-time Tips` in the Summary section is showing correctly 

![image](https://user-images.githubusercontent.com/38657976/77893917-2fbe1700-7292-11ea-8535-f888d92a1f61.png)

Summary section and wallet balance is showing correctly
![image](https://user-images.githubusercontent.com/38657976/77894235-9fcc9d00-7292-11ea-85a5-68280b4ba456.png)

**Comment by NejcZdovc** [comment]
you see two of them as some was taken from unblinded tokens and some was taken from uphold. Can you please send me publisher_info_db to confirm it.

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc Unknowing I have deleted the profile where I have reproduced the issue initially. I have verified it again on a clean profile in 1.7.78 - It's working fine now.
![image](https://user-images.githubusercontent.com/38657976/77907097-afee7780-72a6-11ea-9599-c29500701248.png)

**Comment by NejcZdovc** [comment]
great

**Comment by NejcZdovc** [comment]
Fixed with https://github.com/brave/brave-browser/issues/8828
