### ISSUE TITLE
[Android] Disable unneeded permissions

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#8898]
## Description 
Disable permissions that we don't need and that are disabled on tabs repository

## Steps to reproduce 

   1. Pick a device on Android OS version < 6
   2. Install current play store build
   3. Upgrade to brave-core based stable build.

## Actual result 
You will notice a similar screen on update
![Screenshot_2020-03-27-10-28-16](https://user-images.githubusercontent.com/12011303/77790694-a6ada280-703b-11ea-828e-14fd7aebde39.png)

## Expected result
No new permissions should be added

## Issue reproduces how often 
always

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm 1.5.118.apk`
  - Verified STR from the description, No new permission is added while installing stable android core build on top of GPS version
 
![image](https://user-images.githubusercontent.com/38657976/78019872-04105f00-736e-11ea-9441-c58f1c4bee6d.png)
