### ISSUE TITLE
[Android] link to google support

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8899]
## Description 
When tapping on the padlock or info icon in the URL, you can ultimately get navigated to a google support page when looking for information on the connection to the site.

## Steps to reproduce 

   1. Visit a site (I used brave.com and pdf995.com)
   2. Tap on the padlock or information icon in URL bar.
   3. On the resulting window, select the 'Details' link
   4. Then tap on 'What do these mean?' link.

## Actual result 
After tapping on one of the links in the red boxes below, you are directed to a google support page

![Screenshot_20200327-154700](https://user-images.githubusercontent.com/28145373/77795017-3b67ce80-7043-11ea-88c2-dc22158fe6fa.jpg)

![Screenshot_20200327-154709](https://user-images.githubusercontent.com/28145373/77795024-3efb5580-7043-11ea-81d5-3b45bdf122d0.jpg)

## Expected result
should link to a Brave support page with an explanation.

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.5.117

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @brave/legacy_qa

**Comment by LaurenWags** [comment]
Comparing to tabs 1.5.9 version, looks like this link was not available there:
![Screenshot_20200327-155950](https://user-images.githubusercontent.com/28145373/77795543-16c02680-7044-11ea-99d0-f4716d74ab12.jpg)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 x64 stable build
- Verified learn more link points to [Brave Support page](https://support.brave.com/hc/en-us/articles/360018185871-How-do-I-check-if-a-site-s-connection-is-secure-)
- Verified for both HTTP/HTTPS pages
-------
Verification passed on Samsung Tab A with Android 9.0  x64 stable build
- Verified learn more link points to [Brave Support page](https://support.brave.com/hc/en-us/articles/360018185871-How-do-I-check-if-a-site-s-connection-is-secure-)
- Verified for both HTTP/HTTPS pages
