### ISSUE TITLE
Geolocation prompts not shown for all sites

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#890]
## Description 

Geolocation prompts not shown for all sites

## Steps to Reproduce

   1. Upgrade to 0.54.3
   2. Visit https://browserleaks.com/geo in a new tab
   3. Click Allow in notification bubble, shows correct user location
   4. Open Google.com in a new tab, no prompt shown for accessing user location

## Actual result:

![geo](https://user-images.githubusercontent.com/17010094/44861677-0452f080-ac47-11e8-8f74-000fb98cf9ae.gif)

## Expected result:
Geolocation prompts should be shown on all sites that request for it

## Reproduces how often: 
100%

## Brave version (about:brave info) 

Brave | 0.54.3 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | Windows

### Reproducible on current release:

No, b-l prompt for all sites which request location

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

#25 
cc: @darkdh @bbondy @mbacchi

**Comment by darkdh** [comment]
Can you use maps.google.com and click "Your location" as the second site?
google.com doesn't always ask for geo location

**Comment by srirambv** [comment]
Yes using maps.google.com as second site on the same tab still shows the permission bubble and clicking allow detects correct location. 

>google.com doesn't always ask for geo location

This is not true for muon browser. It shows location permission notification every time the page is opened unless allow/deny is selected

**Comment by srirambv** [comment]
Discussed with @darkdh. 
1. On clean profile, google search shows location based on ISP 
2. Clicking on `Use precise location` prompts the permission bubble. 
    Click allow shows exact location based on ISP
   Click on deny, shows Location unavailable
3. Same behaviour on Chrome and FF as well

Muon b-l has the same behaviour but irrespective of location tracked by ISP it prompts for location access. 

Closing the issue as its the same behaviour on Chrome (version)
