### ISSUE TITLE
can't claim ad rewards as "claim" button doesn't do anything

### ISSUE THREAD

**Issue by MinisterFister** [brave/brave-browser#8904]
## Description 

I press claim button it don't do anything. Here is my claim button see it 

![image](https://user-images.githubusercontent.com/12465253/77833276-7be24d80-7112-11ea-87d0-ffe661e8cb81.png)
## Steps to Reproduce

   1. Press claim button
   2. Button doesn't do anything
   3. V1.5.115 of Brave

## Expected result:
It doesn't give captcha or sometimes it give but captcha it doesn't do nothing

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Didn't try
- Can you reproduce this issue with the dev channel? Didn't try
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes sir

**Comment by kjozwiak** [comment]
@MinisterFister mind taking a look at `brave://rewards-internals` and emailing me the info via `kamil@brave.com` and I'll get someone to take a look to see why you're not able to claim your grant.

CCing @LaurenWags @NejcZdovc

**Comment by MinisterFister** [comment]
I have desktop version. Sometimes I get the captcha but then when I do it it doesn't work 
![image](https://user-images.githubusercontent.com/12465253/77834164-ef875900-7118-11ea-9963-471a488cc9b1.png)
![image](https://user-images.githubusercontent.com/12465253/77834175-0463ec80-7119-11ea-9503-d28232433bf9.png)

**Comment by MinisterFister** [comment]
Working now! Issue can be closed sirs thanks you for the fixing
