### ISSUE TITLE
[Android]

### ISSUE THREAD

**Issue by edddddddddddddddddddddddddddddy** [brave/brave-browser#8905]
All my downloaded files (images and videos) were deleted when I uninstalled the app

I just want to know why when I uninstalled Brave from my android all the images and videos that I had download were deleted. Is there any way to recover them? I think this is very unffair. I just want my files back.

I hope someone please can help me
Regards.

**Comment by bsclifton** [comment]
@edddddddddddddddddddddddddddddy do you have more information about which version of Brave you were using?

The current stable version is using the code at https://github.com/brave/browser-android-tabs

The BETA version is using this code-base (brave-browser). Knowing this and also some basic information like hardware info should help troubleshoot

cc: @SergeyZhukovsky @samartnik @AlexeyBarabash @deeppandya

**Comment by deeppandya** [comment]
@bsclifton @edddddddddddddddddddddddddddddy by default, all the downloads go to the internal storage of the app. so if you uninstall the app, it would remove everything from an internal memory of the app.

**Comment by bsclifton** [comment]
ah- if that's the case (default location wasn't changed), I don't think there's anything we can do ☹️
