### ISSUE TITLE
brave stops showing ads after waking from sleep mode

### ISSUE THREAD

**Issue by afonsolopez** [brave/brave-browser#8909]
## Description 
Every time my MacOS turns into sleep mode for example, after some minutes to save energy, when I log back in Brave won't show any ad until I close my browser and restart my machine.

## Steps to Reproduce
Just let MacOs turn into sleep mode with Brave working.

## Reproduces how often: 
On my machine it happens every time it enters into sleep mode.

## Brave version (brave://version info)
1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)
5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
Yes
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:
macOS Version 10.15 (Comp. 19A602)

**Comment by tmancey** [comment]
Works as expected on macOS 10.14, need to test on 10.15 as reported

**Comment by tmancey** [comment]
Confirmed working on macOS 10.15. @afonsolopez Can you please let me know your locale as it may be a case there are no eligible ads to be shown.

**Comment by afonsolopez** [comment]
> Confirmed working on macOS 10.15. @afonsolopez Can you please let me know your locale as it may be a case there are no eligible ads to be shown. Also can you please confirm if the browser was in the foreground when trying to view ads?

I'm located in Brazil and yes the browser was in the foreground.
I've discovered a workaround, if I close the browser with Command + Q and open it again the ads are back and I can receive BAT's for then again.

**Comment by tmancey** [comment]
@kjozwiak @LaurenWags I have tried to reproduce without success, so adding QA/Yes label for QA to test too.

@afonsolopez Would you be willing to screen share so I can investigate further?

**Comment by afonsolopez** [comment]
Hi @kjozwiak unfortunately, I'm not with my MacBook anymore I'm sorry. 😔

**Comment by bsclifton** [comment]
Closing as it's not reproducible. Please re-open and let us know if you run into this again @afonsolopez. Thanks!
