### ISSUE TITLE
I can't install Brave do to it unable to connect to the Internet

### ISSUE THREAD

**Issue by AlexanderKimmel** [brave/brave-browser#8910]
## Description 

I downloaded Brave befor on my Laptop no issues what so ever. 
But when I've tried to install it on my PC the intaller can't connect to the Internet.
Yes I've checked my Internet connection... I'm writing this on my PC so the Internet works.
I've also restarted my PC and tryed to Install it multiple times but nothing seemed to work.

**Comment by jhhoffma3** [comment]
Confirmed, tried x86 and x64 installation exe's.

**Comment by AlexanderKimmel** [comment]
Yes I tried that

**Comment by willone2** [comment]
Exact same issue here. Had to download the latest standalone installer from the repo.

**Comment by bsclifton** [comment]
cc: @mihaiplesa

**Comment by masternetra** [comment]
Same.

**Comment by mihaiplesa** [comment]
Hi all, we're doing some maintenance, we'll update at https://status.brave.com/ once done, thanks for the patience.

**Comment by mihaiplesa** [comment]
@AlexanderKimmel @jhhoffma3 @willone2 @masternetra please try now.

**Comment by kjozwiak** [comment]
Went through the following cases:

* `Win 10 x64` --> downloaded `BraveBrowserSetup.exe` via https://brave.com using `Edge` and ensured `1.5.115 CR: 80.0.3987.149 (Official Build) (64-bit)` was being installed
* `Win 10 x86` --> downloaded `BraveBrowserSetup32.exe` via https://brave.com using `Chrome` and ensured `1.5.115 CR: 80.0.3987.149 (Official Build) (32-bit)` was being installed

@srirambv @btlechowski @GeetaSarvadnya mind checking to make sure that you're able to download the latest version via the stub installers in your locales?

**Comment by GeetaSarvadnya** [comment]
Went through the following cases in `Windows 10 x64`

- Downloaded `BraveBrowserSetup.exe` via https://brave.com using `Edge` and ensured 1.5.115 CR: 80.0.3987.149 (Official Build) (64-bit) was being installed
- Downloaded `BraveBrowserSetup.exe` via https://brave.com using `Chrome` and ensured 1.5.115 CR: 80.0.3987.149 (Official Build) (64-bit) was being installed
Downloaded `BraveBrowserSetup.exe` via https://brave.com using `Firefox` and ensured 1.5.115 CR: 80.0.3987.149 (Official Build) (64-bit) was being installed

**Comment by btlechowski** [comment]
Went through the following cases:

* `Win 7 x64` --> downloaded `BraveBrowserSetup.exe` via https://brave.com using `Firefox` and ensured `1.5.115 CR: 80.0.3987.149 (Official Build) (64-bit)` was being installed
* `Win 7 x86` --> downloaded `BraveBrowserSetup32.exe` via https://brave.com using `IE` and ensured `1.5.115 CR: 80.0.3987.149 (Official Build) (32-bit)` was being installed

**Comment by masternetra** [comment]
works now.

**Comment by kjozwiak** [comment]
Going to close this off as it seems like it's now working as per the above 👍
