### ISSUE TITLE
Remove older cosmetic filter integration from Context Menu?

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#8914]
## Description 
There is a newer cosmetic filter integration which is available which @antonok-edm and @pes10k have worked on. This loads and processes rules that are on lists or are manually supplied on brave://adblock/

We have an older integration which is available by right click under the `Brave` menu. This is basically obsolete now and should be removed:
<img width="396" alt="Screen Shot 2020-03-29 at 10 40 07 PM" src="https://user-images.githubusercontent.com/4733304/77878944-533f7e00-720e-11ea-8439-634f8b4ab166.png">

Having both run at the same time can introduce some unstable behavior and it's also confusing for users

## Steps to Reproduce

   1. Visit a web page in Brave
   2. Right click something
   3. Notice there are `Block element via selector` and other items under `Brave` context menu item

**Comment by bsclifton** [comment]
Code which can be removed can be found on https://github.com/brave/brave-browser/projects/21 under `Work was finished (may need revert)` column

**Comment by drq883** [comment]
I just found out about this old, deprecated, cosmetic filter (right-click, brave, block element via selector) today when removing gitlab's annoying "README", "Add licence', etc. buttons.

Now I find out that it's going away. I can't find any documentation on the new cosmetic filter process. How to add things that way?

Hopefully it's as easy as the obsolete way?

**Comment by bsclifton** [comment]
@drq883 this needs to be reviewed before we remove. It's quite possible we can just link this functionality to the new cosmetic filter functionality instead of removing. Right now, they're not related and it's definitely confusing

**Comment by bsclifton** [comment]
Closing as `wontfix`; per discussion with @pes10k, we can keep this in place and work towards integrating it with the existing cosmetic filters. Priority for this has not been assigned, so there will continue to be two filters for a bit

For more information on that, please check out:
https://github.com/brave/brave-browser/issues/9577

**Comment by ugultopu** [comment]
@bsclifton https://github.com/brave/brave-browser/issues/8914#issuecomment-619166338 Exactly. Why not just make the context menu adblock and `brave://adblock` custom filters use that same data store, so that whenever you block something using context menu adblock, the adblock rule for it appears on `brave://adblock` custom filters (since both are stored in the same place)? I expected it to be this way but apparently it is not.
