### ISSUE TITLE
[Android] Port l10n from master with c81 update

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#8917]
We miss translation for certain languages in 1.5.x and 1.7.x and need to update them from master

## Steps to reproduce 

   1. Switch your device language to Japanese.
   2. Open a Brave Rewards panel

## Actual result 
![Screenshot from 2020-03-30 08-34-54](https://user-images.githubusercontent.com/12011303/77912919-6b8cb880-7261-11ea-9de4-1356983ddf5a.png)

## Expected result
Messages should be translated

## Issue reproduces how often 
always

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrolikeme?

**Comment by SergeyZhukovsky** [comment]
done https://github.com/brave/brave-core/pull/5104 https://github.com/brave/brave-core/pull/5105

**Comment by srirambv** [comment]
- Verification passed on OnePlus 6T with Android 10 running 1.7.102 x64 build
![image](https://user-images.githubusercontent.com/17010094/80686513-6f249100-8ae6-11ea-8243-4cebb65cb915.png)
![image](https://user-images.githubusercontent.com/17010094/80686539-777ccc00-8ae6-11ea-83e0-c437da8a6e2f.png)
![image](https://user-images.githubusercontent.com/17010094/80686531-7481db80-8ae6-11ea-9205-f3d8bc62898d.png)
![image](https://user-images.githubusercontent.com/17010094/80686545-7a77bc80-8ae6-11ea-9ae8-c0bc715570c5.png)
![image](https://user-images.githubusercontent.com/17010094/80686549-7cda1680-8ae6-11ea-93fa-16e8f4c9e7ec.png)
![image](https://user-images.githubusercontent.com/17010094/80686560-7fd50700-8ae6-11ea-87f6-493e40146997.png)
---------
- Verification passed on Samsung Tab A with Android 9 running 1.7.102 x64 stable build
![image](https://user-images.githubusercontent.com/17010094/80686941-27ead000-8ae7-11ea-927c-3e236db94e04.png)
![image](https://user-images.githubusercontent.com/17010094/80686932-24efdf80-8ae7-11ea-99e5-541e0bb4ec94.png)
![image](https://user-images.githubusercontent.com/17010094/80686953-2a4d2a00-8ae7-11ea-9f35-5302698dd678.png)
![image](https://user-images.githubusercontent.com/17010094/80686922-228d8580-8ae7-11ea-9970-d5289e924c5a.png)
![image](https://user-images.githubusercontent.com/17010094/80686967-30430b00-8ae7-11ea-8e8e-de713150940d.png)
![image](https://user-images.githubusercontent.com/17010094/80686959-2caf8400-8ae7-11ea-9fba-39646cd94535.png)
