### ISSUE TITLE
[Android] Replace forward button icon

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#8918]
## Description 
A forward icon should look like an arrow instead of a play button

## Steps to reproduce 

   1. Open Settings
   2. Check a forward button that is in the bottom left

## Actual result 
![Screenshot_20200328-134305](https://user-images.githubusercontent.com/12011303/77913190-d0e0a980-7261-11ea-8711-4e01c25e7a94.png)

## Expected result
![Screenshot_20200328-134253](https://user-images.githubusercontent.com/12011303/77913199-d4743080-7261-11ea-8185-226e71c88224.png)

## Issue reproduces how often 
always

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
- Verification passed on OnePlus 6T with Android 10 running 1.5.118 x64 stable build
![image](https://user-images.githubusercontent.com/17010094/77999722-c3eeb380-7350-11ea-9b62-04d77c64755d.png)
------
- Verification passed on Samsung Tab A with Android 9.0 running 1.5.118 x64 stable build
![image](https://user-images.githubusercontent.com/17010094/78000230-96eed080-7351-11ea-982e-294d490ddec4.png)
- Logged follow up issue #8928 for  back button on Tab
