### ISSUE TITLE
[P3A] Ask about switching search engines

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#8919]
**Question:**
Did you switch search engines? If so, which one did you switch to?

**Answers:**
```
0) No
1) Other
2) Google
3) DDG
4) Startpage
5) Bing
6) Qwant
```

**Justification:**
Switching from a particular source to another that would tell us if we should change our defaults

**Comment by rebron** [comment]
@mattmcalister Is this post onboarding? 

We offer and set a default search engine through onboarding. Switching would then be a user going to brave://settings/search and switching search engines that was set during the onboarding process.

Or is this, did you choose a different engine then what was default offered during onboarding process?

**Comment by mattmcalister** [comment]
This is post-onboarding. We want to know about users who have decided the current default (whether they selected it or not) is no longer sufficient.

**Comment by rebron** [comment]
Any more outstanding questions with this one or are we ready to implement?

**Comment by rillian** [comment]
Is this superceded by #18224?

**Comment by mattmcalister** [comment]
Yes, this question is no longer required. Closing.
