### ISSUE TITLE
Browser crashes when zooming out on Google maps using mouse scroll button

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#892]
## Description 

Browser crashes when zooming out on Google maps using mouse scroll button

## Steps to Reproduce

   1. Upgrade to 0.54.3 build
   2. Open maps.google.com in a new tab 
   3. Click on your location button and click allow in notification bubble
   4. Click on your location button again and zoom out using mouse scroll button, after a couple of scroll browser crashes

## Actual result:

Browser crashes when zooming out on Google maps using mouse scroll button
Crash ID: 099ebf601f66a041 

## Expected result:
Should not crash and should zoom out to max available 

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Brave | 0.54.3 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | Windows

### Reproducible on current release:

No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @bbondy

**Comment by srirambv** [comment]
This is fixed on 0.55.2.

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}

Also updated `0.54.3 Chromium: 70.0.3528.4` --> `0.55.6 Chromium: 70.0.3538.16` and ensured that zooming didn't break after upgrading. Zoomed in as close and as far as possible.
