### ISSUE TITLE
Deep links to advanced settings don't work until "Additional settings" is clicked

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#8921]
## Description 
*General issue*. It's possible to link to items in settings (ex: `brave://settings/clearBrowserData`). If linking to a setting which is normally hidden behind `Additional settings`, the link won't work until `Additional settings` is clicked either in the sidebar or at the bottom of the settings page. It seems from the perspective of the person using the browser that the link just went to the settings page.

*Specific example*. The hamburger menu has a `More Tools` > `Clear Browsing Data…` menu item. This item deep-links to settings item `brave://settings/clearBrowserData`. However the actual `Clear browsing data` interface is not visible when this link is clicked — Clicking `Additional settings` either in the sidebar or at the bottom of the settings page immediately brings up the `Clear browsing data` interface.

## Steps to Reproduce
1. Click the hamburger menu `More Tools` > `Clear Browsing Data…` item or use the s ⇧⌘⌫ keyboard shortcut.
  a. Expected result: `Clear browsing data` interface visible in settings.
  b. Actual result: generic settings page.
2. Click `Additional settings` either in the sidebar or at the bottom of the settings page.
  a. `Clear browsing data` interface appears.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
```
Brave | 1.8.43 Chromium: 81.0.4044.69 (Official Build) nightly (64-bit)
Revision | 6813546031a4bc83f717a2ef7cd4ac6ec1199132-refs/branch-heads/4044@{#776}
OS | macOS Version 10.15.3 (Build 19D76)
```

## Other Additional Information:
The issue is not present in Chrome

**Comment by bsclifton** [comment]
Issue called out above fixed with https://github.com/brave/brave-core/commit/58d4ba14841b7dee195d12baffb526730c378854#diff-166e28418b661667403b64249ce36c3a

There are some other places that needed fixing too; like how privacy was moved under advanced- this was fixed with https://github.com/brave/brave-core/commit/9d2f803f091caa2994e3ba28862cc6c4dbbef507#diff-166e28418b661667403b64249ce36c3a
