### ISSUE TITLE
Cannot toggle settings in menu more than once

### ISSUE THREAD

**Issue by Nuc1eoN** [brave/brave-browser#8923]
The ON|OFF toggles in Brave's settings are currently broken, at least for me. You can only toggle the state once, the second toggle has no effect.

Example how to reproduce:

1. Open Settings
2. Go to 'Appearance'
3. Toggle 'Use wide address bar' state
4. Toggle again, now you will see it has no effect and the change is not saved

System info:
ArchLinux
Brave v1.5.115

**Comment by rebron** [comment]
Linux only. Not reproducible on Windows 10 or macOS 1.5.115.

**Comment by Nuc1eoN** [comment]
@rebron Did you make test on Linux too?

**Comment by simonhong** [comment]
Tested on ubuntu 19.04 with brave stable(`1.5.115`) and beta(`1.7.67`) and can't reproduce this issue on both.

**Comment by rebron** [comment]
@Nuc1eoN Is this still an issue for you with current Brave, we're on 1.9.72? If so, refreshing the settings page, will the toggle work again?

**Comment by Nuc1eoN** [comment]
Cannot reproduce it anymore.
