### ISSUE TITLE
Brave constantly polling sites in the background, please stop. 

### ISSUE THREAD

**Issue by notoriousturtle** [brave/brave-browser#8925]
## Description 
Brave is constantly polling:
```
GET /data/price?fsym=ETH&tsyms=USD HTTP/1.1
Host: min-api.cryptocompare.com
```
and
```
GET /v2/blacklist HTTP/1.1
Host: api.infura.io
```
Web3 provider for dapps is set to none. 

If I browse to brave://wallet it loads the new wallet page, with hardware wallet connector options. 

## Steps to Reproduce
Intercept traffic with a web proxy. 

## Expected result:
To not constantly poll anything. 

## Brave version (brave://version info)
1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)

**Comment by snieg** [comment]
Same here, even if crypto wallet and rewards are disabled - also I can see a lot of connections to **api.infura.io**. 

So far I've blocked it directly on PiHole and after 1 day both domains appeared in Top Blocked Domains ;)

![image](https://user-images.githubusercontent.com/35065344/79498248-45b92f00-8029-11ea-925f-291f23f015f5.png)

**Comment by notoriousturtle** [comment]
Yeah, and some of those requests to api.infura.io are big!

**Comment by ChrisB85** [comment]
I have also noticed this and honestly, I don't like it. I'm not using Crypto Wallet feature.

**Comment by notoriousturtle** [comment]
@BrendanEich can we get some movement on this?

**Comment by bsclifton** [comment]
@bbondy @ryanml I believe these are only reached if user visits brave://wallets page, right?

Unfortunately even if you are not enabling, just visiting the page I believe causes the extension to load

**Comment by snieg** [comment]
@bsclifton Nope, it's constantly polling min-api.cryptocompare.com & api.infura.io (even if you're not visiting brave://wallets).

Almost 1k requests daily:

![image](https://user-images.githubusercontent.com/35065344/81754576-d6fbb400-94b6-11ea-88ec-cc481b59c372.png)

**Comment by bsclifton** [comment]
@snieg correct - I think just visiting the page once activates the extension. Looks like @bbondy has a fix coming up with https://github.com/brave/brave-core/pull/5513 😄

**Comment by srirambv** [comment]
Moving to 1.10.x Beta as brave/brave-core#5624 is uplifted

**Comment by CHEF-KOCH** [comment]
Why is the issue closed if the issue still exists?

### Background
* [Why is Brave constantly connecting to min-api.cryptocompare.com (40.115.22.134)?](https://old.reddit.com/r/brave_browser/comments/f3e27q/why_is_brave_constantly_connecting_to/)
* [Brave browser sending traffic to Cryptocompare yet Brave Rewards are disabled](https://old.reddit.com/r/privacytoolsIO/comments/gr8nue/brave_browser_sending_traffic_to_cryptocompare/)

### Reproducable with 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit) + the same Build for Linux

![1111111111111111111111111](https://user-images.githubusercontent.com/727123/83463968-d6c85600-a46f-11ea-8cdd-6b5a2dee2d12.png)
![22222222222222222222222222222222](https://user-images.githubusercontent.com/727123/83463970-d7f98300-a46f-11ea-83d2-c95c11b5b1b2.png)

### Disabled
- Brave Rewards
- IPFS Companion
- All Wallets, I checked `brave://settings/?search=wallet`
- I do not use MetaMask extension

Only thing I have enabled is Brave Sync v1.

Please re-open the ticket it's clearly not fixed.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 Catalina x64` using the following build:

```
Brave | 1.10.81 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.5 (Build 19F101)
```

**`Test Case #1`**

* Launched `1.10.81 CR: 81.0.4044.138` and loaded `brave://wallet` in a new tab without opting into Crypto Wallets
* ensured that `Extensions: Crypto Wallets` wasn't being launched
* ensured that there weren't any `mainnet-infura` calls being made while `Extensions: Crypto Wallets` wasn't running (waited ~30min)

**`Test Case #2`**

* Launched `1.10.81 CR: 81.0.4044.138` and loaded `brave://wallet` in a new tab
* Opted into Crypto Wallets and ensured that `Extensions: Crypto Wallets` was launched
* ensured that `mainnet-infura.brave.com` calls were being made while `Extensions: Crypto Wallets` was running
* ensured `mainnet-infura` calls are going through the `brave.com` proxy

Example:

```
outgoing to mainnet-infura.brave.com (151.101.125.7), Port https (443), Protocol TCP (6), 23.3 kB sent, 1.73 MB received
```

* Restarted the browser and ensured `Extensions: Crypto Wallets wasn't running and `mainnet-infura` calls are not being made.

QA also went through several cases re: lazy loading Crypto Wallets via https://github.com/brave/brave-browser/issues/9757#issuecomment-638480788.

**Comment by kjozwiak** [comment]
@srirambv let me know if there's anything else that needs to be checked that I might have missed with the above STR 👆

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.10.81 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1809 (Build 17763.379)
Component | `0.1.54`

- Verified there is no calls to `api-infura.io` or `min-api.cryptocompare.com` when component is not loaded
- Verified all calls are proxied through `${network}-infura.brave.com`
-------
Verification passed on 

Brave | 1.10.81 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Linux
Component | `0.1.54`

- Verified there is no calls to `api-infura.io` or `min-api.cryptocompare.com` when component is not loaded
- Verified all calls are proxied through `${network}-infura.brave.com`
-------
Verification passed on 

Brave | 1.10.81 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.4 (Build 19E287)
Component | `0.1.54`

- Verified there is no calls to `api-infura.io` or `min-api.cryptocompare.com` when component is not loaded
- Verified all calls are proxied through `${network}-infura.brave.com`
-------

**Comment by bsclifton** [comment]
@CHEF-KOCH can you please try Beta / Dev / Nightly channel? The fix is not in release channel yet. Will be in our next release (as confirmed by QA above). Thanks! 😄
