### ISSUE TITLE
[Android] Replace back button to match forward button on Tablets

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#8928]
## Description 
Replace back button to match forward button on Tablets

## Steps to reproduce 

   1. Upgrade or clean install to 1.5.118 on a tablet

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/78000480-f816a400-7351-11ea-9f20-93125bf57ba0.png)

## Expected result
Similar buttons for back and forward button

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Tablet
   - Android version: 9.0
   
## Brave version
1.5.118

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.5.120 on Samsung Galaxy Tab S5e (Android 9.0)
![Screenshot_20200401-214311_Brave](https://user-images.githubusercontent.com/34715963/78179936-529f2580-7462-11ea-8ca9-4caad6aa312a.jpg)
![Screenshot_20200401-214554_Brave](https://user-images.githubusercontent.com/34715963/78179953-5763d980-7462-11ea-8b50-5553bde2d213.jpg)
Also verified private browsing
