### ISSUE TITLE
switch chromium src to use github mirror to speed up the build

### ISSUE THREAD

**Issue by linhkikuchi** [brave/brave-browser#8929]
We are currently using https://chromium.googlesource.com/chromium/src.git. 
Git clone speed on mirror https://github.com/chromium/chromium.git >>> the above

**Comment by bsclifton** [comment]
To do a faster clone, see steps here:
https://chromium.googlesource.com/chromium/src/+/master/docs/mac_build_instructions.md#Get-the-code

```
If you don't need the full repo history, you can save time by using fetch --no-history chromium. You can call git fetch --unshallow to retrieve the full history later.
```

**Comment by bridiver** [comment]
do we have actual times for googlesource vs github? What about testing with `--no-history`? `--no-history` may or may not be a good choice for devs, but it seems ideal for ci

**Comment by bridiver** [comment]
@bsclifton actually I'm not sure that it's possible to use `--no-history` on a specific tag

**Comment by bridiver** [comment]
while it is possible to do a shallow clone of a tag using git, it doesn't seem to work with `gclient sync` and the `--revision` is ignored during the clone

**Comment by bsclifton** [comment]
😢

**Comment by linhkikuchi** [comment]
closed this one as there is not much speed improvement with this approach. As discussed and confirmed with @bridiver, `init` on a repo with no history (just the branch=tag) is a lot faster. Open #8976 for this
