### ISSUE TITLE
Allow for different default search engines based on region

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#893]
## Test plan
See https://github.com/brave/brave-core/pull/516

## Original Description
(Work on `browser-laptop` was done with https://github.com/brave/browser-laptop/pull/14713)

Brave should use region detection when considering how to set the default search engine (globally and for private tabs)

For example, if I'd like to default to bing.com for Brazil, this should be possible. Currently, the default search is applied regardless of region

The region detection should happen via Node (ex: looking at the computer settings)

Carrying over from browser-laptop 
https://github.com/brave/browser-laptop/issues/14647

**Comment by bsclifton** [comment]
The default search engines (by country) are set in Chromium here:
`src/components/search_engines/template_url_prepopulate_data.cc`

The first one in the list is set as the default.

There's an accompanying file which has the specifics for each search engine (URL, suggest URL, favicon URL, etc):
`src/components/search_engines/prepopulated_engines.json`

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

* Verified setting device language to `de_DE.UTF-8` or `fr_FR.UTF-8` changes default search engine to Qwant
* Verified setting FR/DE language shows the localized version of Yahoo page in search list
