### ISSUE TITLE
Linux - Software only. Hardware acceleration disabled

### ISSUE THREAD

**Issue by francoism90** [brave/brave-browser#8931]
## Description 
I'm unable to enable/use any sort of hardware acceleration.

## Steps to Reproduce

   1. Enable some HWAccel `chrome://flags`
   2. Debug using `chrome://gpu`

## Actual result:

![image](https://user-images.githubusercontent.com/5028905/78011327-bbdc4700-7343-11ea-820a-a83a44281509.png)

## Expected result:

Use hardware acceleration.

## Reproduces how often: 

At launch, every time

## Brave version (brave://version info)

```
1.5.115 Chromium: 80.0.3987.149 (Official Build) unknown (64-bit)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  No, in Chromium GPU/hardware acceleration can be enabled/forced and works fine.

## Miscellaneous Information:

https://aur.archlinux.org/packages/brave-bin/

**Comment by francoism90** [comment]
Got it working!

![image](https://user-images.githubusercontent.com/5028905/78012428-3a85b400-7345-11ea-92f7-e4a49a6e3164.png)

```
/usr/lib/brave-bin/brave --disable-domain-reliability --disable-features=WebXR,VideoPlaybackQuality,WebXrGamepadModule,NotificationTriggers,SmsReceiver,AudioServiceOutOfProcess,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,AutofillServerCommunication --disable-sync --disable-webrtc-apm-in-audio-service --enable-dom-distiller --enable-features=SimplifyHttpsIndicator,WebUIDarkMode,PasswordImport --extension-content-verification=enforce_strict --extensions-install-verification=enforce --no-pings --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,AllowPopupsDuringPageUnload,AudioServiceOutOfProcess,SmsReceiver,NotificationTriggers,WebXrGamepadModule,VideoPlaybackQuality,WebXR --flag-switches-begin --enable-gpu-rasterization --enable-oop-rasterization --enable-zero-copy --ignore-gpu-blacklist --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator,DecodeJpeg420ImagesToYUV,DecodeLossyWebPImagesToYUV --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
```

**Comment by mind-overflow** [comment]
This doesn't work anymore. Launching Brave with that terminal line still results in HW acceleration being disabled.
