### ISSUE TITLE
Ad notifications are not shown until a non ad notification has been authorized

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#8932]
## Description 

Ad notifications are not shown until a non-ad notification has been authorized by the user, i.e. visiting http://bennish.net/web-notifications.html

## Steps to Reproduce

   1. View an ad notification (after a fresh install, before notifications have been authorized)

## Actual result:

Ad notification is not shown

## Expected result:
User should be requested to authorize notifications (if not already enabled in the Windows notification settings area) and an ad notification should be shown

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Ad notifications are not requesting authorization.

Based upon diagnostic information from the Windows APIs, notifications are not enabled due to failure when initializing, likely because Brave Browser notification settings are missing from the Windows settings area.

**Comment by GeetaSarvadnya** [comment]
Verification is in progress


Brave | 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/5131

**Clean profile:** 
- Uninstalled existing profile and installed 1.7.x and confirmed that ads are shown and `Estimated pending rewards` and `Ad notifications received this month` stats are shown as expected
![image](https://user-images.githubusercontent.com/38657976/79138774-b4e91600-7dd2-11ea-823d-1a2f851aab29.png)
- Verified that ads history is shown as expected for viewed ads
![image](https://user-images.githubusercontent.com/38657976/79138827-ccc09a00-7dd2-11ea-9c05-113c70e3c173.png)
