### ISSUE TITLE
Brave Ads campaign startAt and endAt should be based on UTC and not local time

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#8933]
## Description 

Brave Ads campaign startAt and endAt should be based on UTC and not local time

## Steps to Reproduce

   1. View an ad notification (which has expired in UTC, but not expired in your local time zone)

## Actual result:

Ad notification is shown

## Expected result:
Ad notification should not be shown

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

See catalog and search for `startAt` and `endAt` in a campaign

**Comment by GeetaSarvadnya** [comment]
@tmancey As per the subject of the issue `Brave Ads campaign startAt and endAt should be based on UTC and not local time` - we have set the expired UTC time for the Campaign end date and tested the issue, we are not getting ads in 1.9.x as UTC time is already expired. (working as expected)


As per the description of the issue `1. View an ad notification (which has expired in UTC, but not expired in your local time zone)` -  are we supposed to get ads based on the local time when UTC time expired? - Please clarify this. Thanks!

**Comment by tmancey** [comment]
No you should not get ads based on locale time. Start and end dates are in UTC

**Comment by btlechowski** [comment]
Verification passed on


Brave | 1.9.66 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

[PASS] Verified `startAt` available local time and UTC - ad was shown
[PASS] Verified `startAt` available local time but not UTC - ad was not shown
[PASS] Verified `startAt` available UTC but not local time - ad was shown
[PASS] Verified `endAt` available local time and UTC - ad was shown
[PASS] Verified `endAt` available local time but not UTC - ad was not shown (UTC-2)
[PASS] Verified `endAt` available UTC but not local time - ad was shown (UTC+2)
