### ISSUE TITLE
uphold auto contribute has incorrect processor in DB

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8938]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/8571

When you have a KYC'd wallet connected, the processor in the DB should be 2 for Uphold. One time and recurring tips have correct processor of 2, but AC does not, it has 0.

## Steps to Reproduce

   1. Clean profile, staging, short reconcile interval
   2. Enable rewards, connect KYC'd wallet (have BAT in the wallet to do ac and tips.)
   3. Do one time tip, set up recurring tip.
   4. Add verified sites to AC table.
   5. Wait for AC to go thru and complete.
   6. Close Brave.
   7. Open `publisher_info_db` and go to `contribution_info` table.

## Actual result:
AC line has processor 0
<img width="768" alt="Screen Shot 2020-03-31 at 12 12 17 PM" src="https://user-images.githubusercontent.com/28145373/78049711-5db26280-7349-11ea-8490-ab030f2c0602.png">

## Expected result:
AC should have processor 2 like one time and recurring tips

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.8.55 Chromium: 81.0.4044.83 (Official Build) nightly (64-bit)
-- | --
Revision | 5718ca617723806b9aacfb41108a0d911d1bde74-refs/branch-heads/4044@{#853}
OS | macOS Version 10.14.6 (Build 18G3020)

Brave | 1.7.79 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? unsure
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc

**Comment by GeetaSarvadnya** [comment]
Reproduced in windows 10 x64 - 1.7.82

![image](https://user-images.githubusercontent.com/38657976/78236701-fedf1b80-74f7-11ea-846e-6e27a15dd11e.png)

**Comment by btlechowski** [comment]
Reproduced on

Brave | 1.7.82 Chromium: 80.0.3987.162 (Official Build) dev (64-bit)
-- | --
Revision | f2c5dd6138153bb0658091205bd1a1717f16081a-refs/branch-heads/3987@{#1034}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/78271279-3eaffe00-750c-11ea-8a46-f901f26c2661.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on
```

Brave | 1.10.74 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Verified STR from the description
![image](https://user-images.githubusercontent.com/38657976/83012874-a761b580-a039-11ea-8e7a-54d1a6c2f05e.png)
- Logged https://github.com/brave/brave-browser/issues/9962
