### ISSUE TITLE
Sometimes purchase intent weight in not increased on google

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#8939]
Follow up to https://github.com/brave/brave-browser/issues/8047

The query string in URL is composed of a series of field-value pairs. Position of the field- value pairs can change.

We handle only: 
`https://www.google.com/search?q=audi+a4`
We don't handle:
`https://www.google.com/search?ei=bY2CXvHBMK2tytMPqYq--A4&q=audi+a4`
`https://www.google.com/search?source=hp&ei=y2eDXsWuI6fIrgThwZuQDw&q=audi+a4`

## Steps to Reproduce

1. Clean profile
2. Connect to US
3. Run Brave with command line: `/usr/bin/brave-browser --enable-logging=stderr --vmodule=brave_ads=3 --brave-ads-staging --rewards=staging=true`
4. Enable Rewards
5. Open `google.com`
6. Search for `audi a4`  

## Actual result:

purchase intent weight is not increased
`automotive purchase intent by make-audi` in `Default/ads_service/client.json` is empty or doesn't even exists

## Expected result:
purchase intent weight is increased
`automotive purchase intent by make-audi` in `Default/ads_service/client.json` is not empty and contains one element

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.7.78 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @rebron @tmancey @moritzhaller

**Comment by GeetaSarvadnya** [comment]
Verification passed on
```

Brave | 1.10.80 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Reproduced issue in 1.9.x
- Verified the test plan from https://github.com/brave/brave-core/pull/5183 and from issues description
```
"automotive purchase intent by make-audi": [
      {
        "timestamp_in_seconds": 1591099501,
        "weight": 1
      }
    ]
  },
```
