### ISSUE TITLE
Single word keywords does not increase purchase intent when searching 

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#8942]
Follow up to https://github.com/brave/brave-browser/issues/8047

Searching for `audi` does not increase purchase intent 

## Steps to Reproduce

1. Clean profile
2. Connect to US
3. Run Brave with command line: `/usr/bin/brave-browser --enable-logging=stderr --vmodule=brave_ads=3 --brave-ads-staging --rewards=staging=true`
4. Enable Rewards
5. Search for `audi`  in URL bar

## Actual result:

purchase intent weight is not increased
`automotive purchase intent by make-audi` in `Default/ads_service/client.json` is empty or doesn't exists

## Expected result:
purchase intent weight is increased
`automotive purchase intent by make-audi` in `Default/ads_service/client.json` is not empty and contains one element

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.7.78 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @rebron @tmancey @moritzhaller

**Comment by btlechowski** [comment]
@moritzhaller Is this PR merged in 1.9.x? Can you double check?

The issue is still reproducible on

Brave | 1.9.55 Chromium: 81.0.4044.129 (Official Build) dev (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Linux

**Comment by moritzhaller** [comment]
> @moritzhaller Is this PR merged in 1.9.x? Can you double check?

@btlechowski apologies, I tagged the wrong release it should be in 1.10.x!

**Comment by btlechowski** [comment]
Changed the milestone to 1.10.x

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.10.74 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/5182

Searched for `audi`
```
"purchaseIntentSignalHistory": {
	"automotive purchase intent by make-audi": [{
			"timestamp_in_seconds": 1590649595,
			"weight": 1
		}
	]
},
```
Searched for `acura`
```
"automotive purchase intent by make-acura": [{
		"timestamp_in_seconds": 1590649955,
		"weight": 1
	}
],

```
