### ISSUE TITLE
Do not show failed contributions in Tips section

### ISSUE THREAD

**Issue by corymcdonald** [brave/brave-browser#8945]
## Description 

Currently if you have a verified wallet and send a tip to a `connected_wallet` then the tip will show up in the Brave Rewards Tip panel. We should only show successful contributions that were sent. 

Additionally there is some weirdness because those tips should show up as "pending", but they are not in the "Pending Contributions" table.

## Steps to Reproduce
   1. Have a verified wallet 
   1.  Send a tip to Khanacademy.org or Lichess.org
   2. See that the tips show up in the tips panel, but not the verified pending contribution
   3. the "Show all pending contributions" does not have the tips in the panel.

<img width="1236" alt="Screen Shot 2020-03-31 at 3 50 24 PM" src="https://user-images.githubusercontent.com/5459225/78076337-d62a1b00-736b-11ea-8850-5be3b969b78e.png">
<img width="656" alt="Screen Shot 2020-03-31 at 3 50 40 PM" src="https://user-images.githubusercontent.com/5459225/78076328-d2969400-736b-11ea-9833-10a5caec807f.png">

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.7.82 Chromium: 80.0.3987.162 (Official Build) dev (64-bit)
-- | --
Revision | f2c5dd6138153bb0658091205bd1a1717f16081a-refs/branch-heads/3987@{#1034}
OS | Windows 10 OS Version 1803 (Build 17134.1006)


- Verified th test plan from https://github.com/brave/brave-core/pull/5121#issuecomment-607498049
![image](https://user-images.githubusercontent.com/38657976/78237725-55008e80-74f9-11ea-881d-3641378ca63f.png)
![image](https://user-images.githubusercontent.com/38657976/78237783-69dd2200-74f9-11ea-9cc2-5ce8e52acb94.png)
![image](https://user-images.githubusercontent.com/38657976/78237816-73668a00-74f9-11ea-80f4-4a02552e295c.png)
![image](https://user-images.githubusercontent.com/38657976/78237859-81b4a600-74f9-11ea-9ded-8e235a381938.png)
![image](https://user-images.githubusercontent.com/38657976/78237881-8bd6a480-74f9-11ea-964b-071a55334c2b.png)
