### ISSUE TITLE
Task manager lists all processes as occupying 0 bytes

### ISSUE THREAD

**Issue by isiahmeadows** [brave/brave-browser#8946]
## Description 

While trying to figure out why Brave was occupying 3 GB+ memory (lots of internal web pages like to leak), I opened the task manager and saw everything at 0 bytes of memory

## Steps to Reproduce

   1. Open task manager

## Actual result:

<img width="600" alt="Screen Shot 2020-03-31 at 1:34:42 PM" src="https://user-images.githubusercontent.com/4483844/78074323-6316a980-7357-11ea-8fc3-fa8722d297ab.png">

## Expected result:
Memory usage to display as something at least a little more realistic

## Reproduces how often: 

100% of the time

## Brave version (brave://version info)

```
Brave:    1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)
Revision: 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS:       macOS Version 10.14.6 (Build 18G3020)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tried
- Can you reproduce this issue with the dev channel? Not tried
- Can you reproduce this issue with the nightly channel? Not tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? Yes (haven't enabled it)
- Is the issue reproducible on the latest version of Chrome?

## Miscellaneous Information:

This is on a managed work computer with internet access logged.

**Comment by bsclifton** [comment]
I've seen this before too- sometimes it takes a while, but the value will eventually show up. I'm not sure why it can take a while

**Comment by isiahmeadows** [comment]
If it helps, it persisted through multiple browser restarts for me, and I only first noticed it after the latest update.

**Comment by gttotev** [comment]
Happens for me too on:
```
Brave: 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)
Revision: e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS: macOS Version 10.14.6 (Build 18G4032)
```

**Comment by gttotev** [comment]
It appears to be fixed for me now on:
```
Brave: 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)
Revision: e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS:  macOS Version 10.14.6 (Build 18G4032)
```

**Comment by bsclifton** [comment]
@isiahmeadows would you please be able to retest?

**Comment by isiahmeadows** [comment]
Appears fixed for me, too, and I'm on the same version of Brave.
