### ISSUE TITLE
Link error in Windows builds

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#895]
```
[30002/30012] LINK(DLL) chrome.dll chrome.dll.lib chrome.dll.pdb
FAILED: chrome.dll chrome.dll.lib chrome.dll.pdb
ninja -t msvc -e environment.x64 -- ../../third_party/llvm-build/Release+Asserts/bin/lld-link.exe /nologo /IMPLIB:./chrome.dll.lib                               /DLL /OUT:./chrome.dll /PDB:./chrome.dll.pdb @./chrome.dll.rsp
lld-link.exe: error: undefined symbol: ?GetForProfile@ToolbarActionsModelFactory@@SAPEAVToolbarActionsModel@@PEAVProfile@@@Z
>>> referenced by C:\brave\src\chrome\browser\ui\toolbar\toolbar_actions_model.cc:83
>>>               extensions.lib(toolbar_actions_model.obj):(?Get@ToolbarActionsModel@@SAPEAV1@PEAVProfile@@@Z)
```
Happens after `npm run sync -- --all` using master.
cc @petemill @srirambv

**Comment by yrliou** [comment]
cc @simonhong

**Comment by yrliou** [comment]
Causing by https://github.com/brave/brave-core/pull/343

**Comment by petemill** [comment]
Any idea what the cause is @simonhong @yrliou? I'm having trouble getting my windows building to even that point anymore, so doing a fresh clone now.

**Comment by simonhong** [comment]
From the link error log, I assume that `ToolbarActionsModel` object compiled with `ToobarActionsModel* ToolbarActionsModelFactory::GetForProfile(Profile* profile)` signature.

When linking, I think `BraveToobarActionsModel* ToolbarActionsModelFactory::GetForProfile(Profile* profile)` is existed not `ToobarActionsModel* ToolbarActionsModelFactory::GetForProfile(Profile* profile)`.

I assume this causes link error but not sure.
