### ISSUE TITLE
Failing browser test: BraveRewardsBrowserTest SplitProcessorAutoContribution

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#8956]
## Description 
```
20:13:31  [  FAILED  ] BraveRewardsBrowserTest.SplitProcessorAutoContribution, where TypeParam =  and GetParam() =  (8647 ms)
20:13:31  [507/507] BraveRewardsBrowserTest.SplitProcessorAutoContribution (8721 ms)
20:13:31  1 test failed:
20:13:31      BraveRewardsBrowserTest.SplitProcessorAutoContribution (../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:3111)
```

**Comment by bsclifton** [comment]
Test was introduced with https://github.com/brave/brave-core/pull/5050 - however, CI was passing at the time it was merged. Something may have changed after this which broke the test

**Comment by bsclifton** [comment]
First PR that I see which has a failure (working backwards) is https://github.com/brave/brave-core/pull/5058. Not sure if this is the cause... but the PR before that (https://github.com/brave/brave-core/pull/5109) ran on macOS (which runs browser tests) and passed without issue

**Comment by NejcZdovc** [comment]
@bsclifton is this something that is failing all the time? As just one PR that I did yesterday was green, so I think this is intermittent

**Comment by bsclifton** [comment]
@NejcZdovc possibly intermittent - it has failed with the last few PRs though (started happening today). Would you be able to try on master?

**Comment by NejcZdovc** [comment]
Have https://github.com/brave/brave-core/pull/5129 running right now on the latest master, let's see what will happen. Trying locally as well

**Comment by NejcZdovc** [comment]
This one is all green, PR created couple of hours ago https://github.com/brave/brave-core/pull/5121. So for sure is intermittent

**Comment by NejcZdovc** [comment]
this test passes on my machine as well, but get some other failing tests. Will log an issue for them

**Comment by NejcZdovc** [comment]
should be fixed with https://github.com/brave/brave-core/pull/4114

**Comment by LaurenWags** [comment]
@NejcZdovc could you please take a look and let us know if this issue requires manual QA? Issue seems to be for browser tests but would like to confirm. If no manual QA needed please add `QA/No` label. Thanks! cc @kjozwiak

**Comment by NejcZdovc** [comment]
done

**Comment by LaurenWags** [comment]
thank you!
