### ISSUE TITLE
Payment made text needs to be updated in Monthly statements

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8960]
## Description 

Payment made text needs to be updated in Monthly statements

## Steps to Reproduce

   1. Clean profile 1.7.79
   2. Setup a recurring tip
   3. Send a one time tip
   4. Trigger AC and check the monthly statement for `Auto-Contribute`
   5. The text `Payment made every 1th each month` is displayed - this needs to rephrased to ` Payment made on every 1st of each month`

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/78127494-e4db0580-7431-11ea-8f35-34098c0f5526.png)

## Expected result:
The text needs to be rephrased to ` Payment made on every 1st of each month`

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.7.81 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron

**Comment by NejcZdovc** [comment]
@mandar-brave @jenn-rhim do we even need this text?

**Comment by rebron** [comment]
@mandar-brave I think this text can be removed. You already have Next Payment date on the main Rewards page.

**Comment by mandar-brave** [comment]
Yes. Makes sense. @NejcZdovc @rebron

**Comment by LaurenWags** [comment]
Verified passed with


Brave | 1.11.65 Chromium: 83.0.4103.97 (Official Build) dev (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/5644

<img width="952" alt="Screen Shot 2020-06-16 at 8 21 38 AM" src="https://user-images.githubusercontent.com/28145373/84773561-90fca900-afaa-11ea-8846-378a98872cef.png">
<img width="947" alt="Screen Shot 2020-06-16 at 8 21 48 AM" src="https://user-images.githubusercontent.com/28145373/84773573-93f79980-afaa-11ea-9a9b-c15bdbf16439.png">
<img width="941" alt="Screen Shot 2020-06-16 at 8 21 56 AM" src="https://user-images.githubusercontent.com/28145373/84773583-95c15d00-afaa-11ea-8850-e767a1a9fc24.png">

------
