### ISSUE TITLE
UGP Token grants claimed value is 0.0 BAT in Monthly Statement

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#8961]
## Description 

Token grants claimed value is 0.0 BAT in Monthly Statement

## Steps to Reproduce

   1. claim UGP grant
   2. claim Ad grant
   3. set up & perform AC
   4. set up & perform recurring tips
   5. set up 1-time tips
   6. Trigger AC and verify the monthly statement
   7. Token grants claimed value is 0.0 BAT in Monthly Statement
   
## Actual result:

Token grants claimed value is 0.0 BAT in Monthly Statement
![image](https://user-images.githubusercontent.com/38657976/78128347-5bc4ce00-7433-11ea-94dc-a41daa065174.png)

## Expected result:

Token grants claimed value should show 20 BAT in Monthly Statement
## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.7.81 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron

**Comment by LaurenWags** [comment]
Does not reproduce on macOS

Brave | 1.7.81 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

<img width="955" alt="Screen Shot 2020-04-01 at 8 09 26 AM" src="https://user-images.githubusercontent.com/28145373/78135723-5abe7d00-73f0-11ea-81e5-45138dc78976.png">

Did not encounter this when testing on 1.7.79 either.

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya do you see 0 on rewards page as well?

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc In Rewards settings page Token grants claimed isn't displayed. when I expand `Detail` I can see token grants claimed. Also, I observed one more thing, after claiming UGP grants the wallet balance is reflected as 20 BAT when I restore ad grants the I get ad grants notification at the same time wallet balance turns to zero from 20 BAT. After claiming ad grants wallet balance shows both amounts (UGP+Ad grants) = 25. Please find the steps below:

1. Clean profile ( use staging flag)
2. Claim UGP grants
3. Wallet balance is 20 BAT and Token grants claimed is shown is rewards setting page 
4. Restore ad grants
5. wallet restored is 0 is shown in wallet balance and Ad grants with `claim` button notification is shown in the rewards settings page
6.  Claim ad grants
7. wallet balance shows `0` for few seconds and then it shows 25 BAT
8. In rewards setting page now only `Earning from ads` is showing as 5 BAT there is no entry for UGP grants
9. Open monthly statement - token grants claimed is `0` (shown in 1st two images below )

I can reproduce this issue consistently.

![image](https://user-images.githubusercontent.com/38657976/78348667-11248c80-75c0-11ea-8f43-33fb460b34d4.png)
![image](https://user-images.githubusercontent.com/38657976/78348696-1a155e00-75c0-11ea-99eb-2505bbf44378.png)

![image](https://user-images.githubusercontent.com/38657976/78347587-58118280-75be-11ea-9d54-f605b03cf8ca.png)
![image](https://user-images.githubusercontent.com/38657976/78347617-6364ae00-75be-11ea-8a3f-c1fc13e8c0f6.png)

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya ok key thing is that you restored a wallet. When you do this summary is automatically cleared. 

@mandar-brave we need to talk about this use case. What data should be removed when you restore a wallet? Right now we have a mix. We delete summary data that are store in json, but we keep db data

**Comment by GeetaSarvadnya** [comment]
Reproduced in Windows `10 x64 - 1.24.65`
