### ISSUE TITLE
sometimes TAP image isn't shown

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#8964]
## Description 

Sometimes the image isn't shown on the TAP message box on brave://rewards. Page refresh fixes it.

## Steps to Reproduce

This is one scenario where I've noticed it, maybe there are others.
   1. Clean profile, US locale, staging env
   2. Enable Rewards
   3. Connect a KYC'd user wallet

## Actual result:

When you're directed back to brave://rewards, look at the TAP message box
<img width="425" alt="Screen Shot 2020-04-01 at 8 38 09 AM" src="https://user-images.githubusercontent.com/28145373/78144021-0cfc4180-73fd-11ea-99f5-3fdc8c66b776.png">

If you refresh the page, image shows

## Expected result:
Image should be displayed in the box

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.7.81 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @brave/legacy_qa

**Comment by NejcZdovc** [comment]
cc @ryanml

**Comment by LaurenWags** [comment]
Verified using

Brave | 1.9.49 Chromium: 81.0.4044.129 (Official Build) dev (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | macOS Version 10.14.6 (Build 18G3020)

* Issue as originally reported in description still reproduces. Logged follow up issue https://github.com/brave/brave-browser/issues/9553
