### ISSUE TITLE
Ads Purchase Intent funnel keyword with higher weight is ignored

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#8965]
Follow up to https://github.com/brave/brave-browser/issues/8047

keyword `dealer opening times` has weight 3
keyword `sell ` has weight 2

audi a5 dealer opening times - weight 3
audi a5 dealer opening times sell - weight 2
audi a5 sell dealer opening times - weight 2

The highest weight should be used

## Steps to Reproduce

1. Clean profile
2. Connect to US
3. Run Brave with command line: `/usr/bin/brave-browser --enable-logging=stderr --vmodule=brave_ads=3 --brave-ads-staging --rewards=staging=true`
4. Enable Rewards
5. Search for `audi a5 dealer opening times sell`  in URL bar
6. Check weight for `automotive purchase intent by make-audi` in `Default/ads_service/client.json`

## Actual result:

audi a5 dealer opening times sell - weight 2

## Expected result:
The highest weight should be used
audi a5 dealer opening times sell - weight 3

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.7.78 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @rebron @tmancey @moritzhaller

**Comment by LaurenWags** [comment]
@moritzhaller when you get a chance, please ensure the following:
- this issue is assigned a milestone (in most cases the milestone should probably be the version master is on)
- corresponding PR is assigned a milestone (in most cases the milestone should probably be the version master is on)
- corresponding PR has a test plan to test this issue

let me know if you have any questions 😄

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.9.55 Chromium: 81.0.4044.129 (Official Build) dev (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/5180
Verified weight is 3.

`"automotive purchase intent by make-audi":[{"timestamp_in_seconds":1588708652,"weight":3}]`
