### ISSUE TITLE
replace "HTTPS Upgrades" stat with "Bandwidth saved" stat

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#8969]
## Description 
Follow-up to #8256 (which added the "Estimated Bandwidth Saved" stat and pushed out the content).

- [ ] Remove HTTPS Upgrades stat and label.
- [ ]  Replace with the same formatting and location with stat and "Bandwidth saved" label.
- [ ] Fix sentence casing so it reads "Ads & trackers blocked" and "Estimated time saved" 

## Actual result:
<img width="1341" alt="74566850-46e6b680-4f29-11ea-83a5-a551abc89eb8" src="https://user-images.githubusercontent.com/5951041/78171376-2dca9400-7409-11ea-9f6e-b9dff9bbed5f.png">

## Design
![replace https with estimated data saved](https://user-images.githubusercontent.com/2388823/78176165-ed6f1400-7410-11ea-9bfd-cf827d66cba1.png)

## Reproduces how often: 
n/a

## Brave version (brave://version info)
n/a

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the dev channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
Check l10n strings for "Estimated Bandwidth Saved" and possible alternate text so that layout flows properly with longer translations.

**Comment by rebron** [comment]
cc: @bradleyrichter

**Comment by karenkliu** [comment]
designs added!

**Comment by rebron** [comment]
@AndriusA Can you grab this one?

**Comment by bsclifton** [comment]
Setting missing milestone to 1.10

**Comment by btlechowski** [comment]
@rebron I am confused about expected behavior. Should `Bandwidth saved` stat be shown in 1.10.x?

Right now `HTTPS Upgrades` is hidden, but `Bandwidth saved` is not shown:
![image](https://user-images.githubusercontent.com/34715963/82853267-9879e680-9f05-11ea-83e9-49cf809294c7.png)

Brave | 1.10.71 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.10.74 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

The stats stings are not translated. Logged https://github.com/brave/brave-browser/issues/9990
The `Estimated bandwidth saved` stat is not shown on clean install. Logged https://github.com/brave/brave-browser/issues/9993

Verified the test plan from the description.
Verified `Estimated bandwidth saved` stat is shown
![image](https://user-images.githubusercontent.com/34715963/83208385-d0776880-a155-11ea-9b8c-cda71ce59882.png)
Verified `Estimated bandwidth saved` stat is retained after restart
