### ISSUE TITLE
Provide a switch to enable / disable WebTorrent in settings

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#897]
We should provide a switch for webtorrent, probably in a brave-specific settings section.

**Comment by Brave-Matt** [comment]
+ 1's from Community:

https://community.brave.com/t/is-there-any-way-to-disable-webtorrent/33872

https://community.brave.com/t/how-to-disable-webtorrent/33659?u=eljuno

**Comment by marintoo** [comment]
Agree

**Comment by NejcZdovc** [comment]
+1 from me

**Comment by lordirfan99** [comment]
+1 from me. i would like to use 3rd party torrent apps

**Comment by DarkDibblez** [comment]
+1 from me

**Comment by justmwa** [comment]
+1. Opt-in by default for an optional feature is bad design. No opt-out ability is wtf.

**Comment by AoDev** [comment]
Same complain. I've told people to start using Brave then this came up. Nobody using the browser until this is fixed.

**Comment by damienOlsen** [comment]
This is really impacting my transition from Chrome to Brave.
Can we please get a flag to disable this, or just revert to default protocol handling

**Comment by boggle247** [comment]
+1 would love to be able to toggle this off or have a work around in the meantime until the fix is pushed to stable. Thanks

**Comment by Brave-Matt** [comment]
+1 from Reddit (several users requesting this in the thread):
https://www.reddit.com/r/brave_browser/comments/a0dl7y/torrents_with_brave/

**Comment by psypher246** [comment]
Due to lack of switch to turn of webtorrent and this bug: https://community.brave.com/t/webtorrent-in-incognito-mode/37461 NO torrent files can be downloaded in incognito mode. It was mentioned here https://community.brave.com/t/possibility-of-disabling-webtorrent/35699 on Oct 23rd that a switch to turn off webtorrents is coming. What is the progress of that?

**Comment by Brave-Matt** [comment]
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/a0u7ro/how_do_i_open_torrents_with_my_default_torrent/

**Comment by rht** [comment]
I tried adding a command line flag `--disable-webtorrent-extension` (which should have worked according to https://github.com/brave/brave-core/blob/46601383bbc6da47c0ac60f0ba0bc5613de2944e/common/brave_switches.cc#L30) but it had no effect on 0.56.12 on NixOS (from a .deb file). It might have worked on other platforms.

**Comment by InVItroVeritas** [comment]
+1 from me

**Comment by ItsiAdam** [comment]
unbelievable i will murder the brave developers

**Comment by peyao** [comment]
+1, prefer to use my own client with SOCKS5 proxy.

Right now the experience is copy and pasting magnet links, which gets old pretty quickly.

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/trying-to-use-remote-torrent-adder-extension/38775/

cc: @rebron need to prioritize this. Lots of community feedback to provide a switch.

**Comment by Brave-Matt** [comment]
Several more +1's from Reddit:
reddit.com/r/brave_browser/comments/9rmnlv/how_can_i_disable_the_built_in_torrent_client/

**Comment by Brave-Matt** [comment]
Another +1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/a3upj1/a_couple_anoying_issues/

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/set-behavior-for-torrent-and-magnet-links-and-other-files-types/39693/2

**Comment by pongraczi** [comment]
> Since the command line switch already existed, adding it to `brave://flags`, should be straightforward:
> ...
> +    {"disable-webtorrent-extension",
> ...
> At least the about flag should be added until the switch is moved to the web preferences.

Hmmm, I tried to use this command line switch, I guess it is my fault, but nothing worked.  
The command line switch is working for somebody? How to use (syntax) it exactly?  
For me, it should be a quick workaround.  
Thanks.

**Comment by rht** [comment]
@pongraczi the command line switch exists at >= 0.58.10.

**Comment by pongraczi** [comment]
0.58.10 is from the beta channel?  After an upgrade, I got only 0.57.18.

**Comment by eljuno** [comment]
+1 via Twitter https://twitter.com/Not_Vash/status/1073750538976665608?s=09

**Comment by eljuno** [comment]
+1 via Twitter https://twitter.com/KaterOrr/status/1073912044020211712?s=09

**Comment by pongraczi** [comment]
Thanks, the command line switch is working on linuxmint 19.x (ubuntu bionic), v.58.16 today.  
```brave-browser  --disable-webtorrent-extension```

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/how-to-disable-webtorrent-in-the-new-version/41039?u=eljuno

**Comment by ItsiAdam** [comment]
wowzers

**Comment by srirambv** [comment]
>Why is this not done yet? I have a system set handler for magnet links and .torrent files and it is extremely obnoxious for you to completely override it, I don't understand why anyone thought this was a good idea.

@xlexi You are more than welcome to do a fix for it and submit a PR so that it can be verified and pushed out

**Comment by 2635599** [comment]
this thread may not be all that old, but this issue has been repeatedly asked about since at least feb 2017. this means there is no legitimate reason that there isn't a way to disable and or remove web torrents. this should of NEVER been added without a way to disable and or remove it.

**Comment by NejcZdovc** [comment]
@2635599 we hear you and we bumped priority of it so should be done quite soon

**Comment by 2635599** [comment]
@NejcZdovc thanks for the quick reply, much appreciated.

**Comment by gyrocog** [comment]
That's a +1 from me as well.

I can't really find anything wrong with Brave (I quite like it), but this annoys me very much.

**Comment by 2635599** [comment]
tested the one switch and it worked perfectly,however i was in the process of replacing some files and the first few went to deluge and then it just reenabled webtorrent half way through add the magnet links. i used the script again and it fixed it again, but seems to be only temporary.

**Comment by emojisrr** [comment]
> tested the one switch and it worked perfectly,however i was in the process of replacing some files and the first few went to deluge and then it just reenabled webtorrent half way through add the magnet links. i used the script again and it fixed it again, but seems to be only temporary.

Hi Mr Grimm, i'm hoping you can assist please now that (https://community.brave.com/t/solved-loving-the-speed-feel-tor-integration-and-th-sleek-design-of-brave-only-one-issue-and-that-is-turning-off-torrent-integration-so-i-can-use-deluge/41556/5) is closed, I can't  post this there; are you able to please let me know where (switch to disable default webtorrent client) is? I can't find it where Maatches is referring to (https://github.com/brave/brave-browser/issues/897), nor can I find where to apply/check (brave-browser --disable-webtorrent-extension)

Using: Brave Version 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)

Thanks in advance.

**Comment by pongraczi** [comment]
There is a command line switch in the recent version. My version is 0.58.18 on linux.  
The switch is:    --disable-webtorrent-extension 

Quick fix: change the command using your menu editor.  
For example, I use mate and I change the menu item like this:  
**brave-browser  --disable-webtorrent-extension -- %U**

**Comment by 2635599** [comment]
yesterday i asked on the forums about disabling webtorrent cause i want to use deluge. i was given a link to this thread that has a solution that worked perfectly, but it seems that when i close the browser the fix breaks, and i have to apply it each time. i’d like to create a shortcut that when clicked launches terminal, executes the fix which launches brave once applied. thanks

just closed brave and i noticed the following in terminal. pretty sure i didn’t get that using the fix on the release version.

```
[3551:3567:0104/024139.367396:ERROR:rewards_service_impl.cc(164)] Failed to read file: /home/mc2635599/.config/BraveSoftware/Brave-Browser-Dev/Default/ledger_state
[3652:3652:0104/024139.510987:ERROR:ledger_impl.cc(202)] Failed to load ledger state
[3652:3652:0104/024139.511036:ERROR:ledger_impl.cc(285)] Failed to initialize wallet
[3551:3567:0104/024140.177351:ERROR:nss_util.cc(748)] After loading Root Certs, loaded==false: NSS error code: -8018
[1:1:0104/024140.270788:ERROR:audio_context.cc(52)] Create
[1:1:0104/024140.271034:ERROR:audio_context.cc(130)] AudioContext
[1:1:0104/024140.271157:ERROR:audio_context.cc(138)] user gesture
[1:1:0104/024140.488214:ERROR:audio_context.cc(436)] IsAllowedToStart
[1:1:0104/024140.488317:ERROR:audio_context.cc(93)] starting
[3551:3551:0104/024141.746508:ERROR:CONSOLE(2374)] "Possibly unhandled rejection: Not connected.", source: chrome-extension://jndkngpbgmnkbhbjafmjhabcjmgeogfc/dist/deps.js (2374)
[3551:3551:0104/024156.784923:ERROR:CONSOLE(2374)] "Possibly unhandled rejection: Not connected.", source: chrome-extension://jndkngpbgmnkbhbjafmjhabcjmgeogfc/dist/deps.js (2374)
[3551:3551:0104/024212.784650:ERROR:CONSOLE(2374)] "Possibly unhandled rejection: Not connected.", source: chrome-extension://jndkngpbgmnkbhbjafmjhabcjmgeogfc/dist/deps.js (2374)
[3551:3551:0104/024228.779837:ERROR:CONSOLE(2374)] "Possibly unhandled rejection: Not connected.", source: chrome-extension://jndkngpbgmnkbhbjafmjhabcjmgeogfc/dist/deps.js (2374)
[3551:3551:0104/024244.783274:ERROR:CONSOLE(2374)] "Possibly unhandled rejection: Not connected.", source: chrome-extension://jndkngpbgmnkbhbjafmjhabcjmgeogfc/dist/deps.js (2374)
[3551:3551:0104/024259.803799:ERROR:CONSOLE(2374)] "Possibly unhandled rejection: Not connected.", source: chrome-extension://jndkngpbgmnkbhbjafmjhabcjmgeogfc/dist/deps.js (2374)
[3551:3551:0104/024259.946577:ERROR:CONSOLE(2374)] "Possibly unhandled rejection: Not connected.", source: chrome-extension://jndkngpbgmnkbhbjafmjhabcjmgeogfc/dist/deps.js (2374)
[3551:3551:0104/024259.946762:ERROR:CONSOLE(2374)] "Possibly unhandled rejection: Not connected.", source: chrome-extension://jndkngpbgmnkbhbjafmjhabcjmgeogfc/dist/deps.js (2374)
/usr/lib/python2.7/dist-packages/deluge/ui/gtkui/mainwindow.py:151: GtkWarning: gtk_window_realize_icon: assertion 'info->icon_pixmap == NULL' failed
  self.window.present()
[3551:3551:0104/043055.770892:ERROR:CONSOLE(2374)] "Possibly unhandled rejection: Error executing Deluge getTorrents", source: chrome-extension://jndkngpbgmnkbhbjafmjhabcjmgeogfc/dist/deps.js (2374)
```

**Comment by 2635599** [comment]
puzzled out the shortcut, still need help with the error though. thanks

**Comment by pongraczi** [comment]
> puzzled out the shortcut, still need help with the error though. thanks

Sorry in advance, what is the problem with the command line switch, which is working in recent brave?  
Did you try that? It is working as expected, no need to run any fix.  

Just start brave like this:  
brave-browser --disable-webtorrent-extension

**Comment by 2635599** [comment]
was concerned about the error messages there, and the fact that twice that popup after simply clicking the new shortcut / launcher and once when i actually opened terminal and entered the command.

**Comment by bbondy** [comment]
Credit to @yrliou for the fix 🎉, looks like this:

<img width="792" alt="screen shot 2019-01-04 at 3 59 50 pm" src="https://user-images.githubusercontent.com/831718/50710751-e43e9e00-1039-11e9-82c8-1c673ec61a5d.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux


![image](https://user-images.githubusercontent.com/17010094/50810150-efd9df80-132d-11e9-87fb-317627bd43d1.png)

**Comment by Farfie** [comment]
cant believe this is a thing. considering this is an issue from 2018, pretty sure im gonna drop brave now. someone go ahead and message me if this changes

**Comment by kjozwiak** [comment]
> cant believe this is a thing. considering this is an issue from 2018, pretty sure im gonna drop brave now. someone go ahead and message me if this changes

@Farfie what's the exact issue that you're having? The ability to turn off WebTorrent has been available under `brave://settings/extensions` for a long time. It comes enabled by default but you can always disable it via the settings. I double checked and made sure it was working as expected.

![torrent](https://user-images.githubusercontent.com/2602313/150207404-b53c5db8-56e8-4dd7-b0cc-72c024682c67.png)

You can see that I have it disabled on my profile. Either way, please let me know what the issues you're having.
