### ISSUE TITLE
Filter out Drip's email tracker from URLs

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#8975]
Drip uses the `__s` query string parameter to link user visits to a website back to their email address.

Here's an abridged example:

```
$ curl -i https://t.dripemail2.com/c/eyJhY2NvdW50X2lkIjoiNTQzOTc1OSIs...WxwLTEwMS8_X19zPXpjcmFhdHNqYnRlc3NzbjJraXlrIn0
HTTP/2 307 
date: Thu, 02 Apr 2020 00:02:48 GMT
content-length: 0
location: https://skipperotto.com/kelp-101/?__s=zcra...2kiyk
```
The long parameter in the first URL is a base64 encoding of the following information:
```
{
    "account_id": "5439759",
    "delivery_id": "9ne...gdv",
    "url":"https://skipperotto.com/kelp-101/"
}
```

According to the [Drip documentation](https://www.drip.com/learn/docs/manual/email-builder/suppress-__s-from-rendered-links), removing this parameter "disables Drip’s ability to identify new people and track already identified people."

**Comment by fmarier** [comment]
Since this is a pretty generic-looking parameter name, we might want to restrict the query filter further before adding this to the list:
- exempt same-site requests from the query filter
- require a minimum value length (e.g. 6 characters) before stripping

**Comment by stephendonner** [comment]
Verified `FIXED` using the testplan from https://github.com/brave/brave-core/pull/7968 with

Brave | 1.22.39 Chromium: 89.0.4389.58 (Official Build) nightly (x86_64)
-- | --
Revision | 1a139f28ecc27719439e37c6b1533cee999cb802-refs/branch-heads/4389@{#1134}
OS | macOS Version 11.2.1 (Build 20D74)

1. Open https://brave.com/?fbclid=1234 in a new tab.
2. Check that the fbclid query parameter is missing from the URL bar.
![drip-shields-on](https://user-images.githubusercontent.com/387249/108774821-02670100-7515-11eb-8e99-1f9549b64456.gif)
3. Turn Shields OFF for brave.com.
4. Open https://brave.com/?fbclid=5678 in a new tab.
5. Check that the fbclid query parameter is present in the URL bar.
![drip-shields-off](https://user-images.githubusercontent.com/387249/108774822-03982e00-7515-11eb-80c7-c1bfe7819381.gif)
6. Turn Shields ON for brave.com.
7. Open https://brave.com/?__s=abcd in a new tab.
8. Check that the __s query parameter is missing from the URL bar.
![drip-abcd-shields-on](https://user-images.githubusercontent.com/387249/108775038-67225b80-7515-11eb-8773-46a2e2699caa.gif)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.22.54 x64 beta build
- Verified test plan from https://github.com/brave/brave-core/pull/7968

https://user-images.githubusercontent.com/17010094/110446041-aa083580-80b6-11eb-9024-c603d759d38c.mp4

---------------

Verification passed on Samsung Tab A with Android 10 running 1.22.54 x64 beta build
- Verified test plan from https://github.com/brave/brave-core/pull/7968

https://user-images.githubusercontent.com/17010094/110447702-61ea1280-80b8-11eb-912a-6666a4379850.mp4
