### ISSUE TITLE
Switch chromium.googlesource to use repo with no history

### ISSUE THREAD

**Issue by linhkikuchi** [brave/brave-browser#8976]
Relates to #8929, the approach is to maintain each repo per version of chromium without any other history to speed up the build
- starting with version `81.0.4044.83`
- repo name will be `chromium-releases-81.0.4044.83` (e.g. https://github.com/brave/chromium-releases-81.0.4044.83)
- package.json needs to be updated to point to each repo for each chromium release, e.g.
```
"projects": {
      "chrome": {
        "dir": "src",
        "repository": {
          "url": "https://github.com/brave/chromium-releases-81.0.4044.83.git"
        },
        "custom_deps": {
          "src/third_party/WebKit/LayoutTests": "%None%",
          "src/chrome_frame/tools/test/reference_build/chrome": "%None%",
          "src/chrome_frame/tools/test/reference_build/chrome_win": "%None%",
          "src/chrome/tools/test/reference_build/chrome": "%None%",
          "src/chrome/tools/test/reference_build/chrome_linux": "%None%",
          "src/chrome/tools/test/reference_build/chrome_mac": "%None%",
          "src/chrome/tools/test/reference_build/chrome_win": "%None%"
        }
      }
```
Task:
[ ] Create a pipeline to create chromium release version repo
[ ] Update chromium-update-mirror pipeline to update package.json accordingly
[ ] Update package.json to point to new repo with no history

**Comment by linhkikuchi** [comment]
Have tested `init` speed on a github repo (no history) vs codecommit repo (no history) without cache: on github it's around 7min+, on codecommit it's around 8min+-9mins+. Build was successfully without issues on both.

Given the speed is not that much difference, we can go with either type of repo:
- cost wise: codecommit first 5 users free, $1 for additional one user
- codecommit will not be transparent for Devs as github

If we decide to go with github:
- should we create another team brave-chromium for these repos?

@mihaiplesa @bridiver @bsclifton

**Comment by mihaiplesa** [comment]
Added `QA/No` label and milestone to issue. Have to decide how we uplift this.
