### ISSUE TITLE
[Android] Fix url bar on tablet without rewards icon

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#8983]
## Description 
On tablet without rewards icon url bar on the right side has straight corners. They should be rounded.
![Screenshot from 2020-04-01 15-12-51](https://user-images.githubusercontent.com/30602739/78265812-f45e5b00-74d2-11ea-8a5c-4eaf57778d9e.png)

## Steps to reproduce 

   1. On tablet go to settings and hide rewards button
   2. Restart browser

## Actual result 
Straight corners on the right side

## Expected result
Rounded corners on the right side

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? yes
   - Beta build? yes

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.5.120

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 9 running 1.7.100 x64 stable build
- Verified disabling rewards retains rounded edge on URL bar
![image](https://user-images.githubusercontent.com/17010094/80208556-18ced280-864e-11ea-97c1-af0c36db19c9.png)
