### ISSUE TITLE
[Android] don't copy resources into chrome res dir

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#8995]
We currently copy a lot of resources from brave/android/java/res to chrome/android/java/res and we should not be doing things like if we can avoid it

**Comment by GeetaSarvadnya** [comment]
@SergeyZhukovsky General testing would be fine or do you have any specific test plan for this issue?

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm.apk 1.9.74`
- Executed tests from https://github.com/brave/brave-browser/issues/9885
- Performed testing around NTP layout as per https://github.com/brave/brave-browser/issues/8995#issuecomment-608103542
