### ISSUE TITLE
Disable ads in new tab.

### ISSUE THREAD

**Issue by divrse** [brave/brave-browser#9005]
Would like to disable the new ads that have been added to new tab screen.
Do not see in settings anywhere.

Brave appears to rotate between the default image system and the ads at an exact 1:4 ratio.

For example this is an ad for new egg.

I like the monetization method but would like to turn it off,

Thanks.

![Screenshot from 2020-04-02 21-37-08](https://user-images.githubusercontent.com/18077440/78324677-35358e80-752a-11ea-8e2c-967be48c830e.png)

**Comment by Ravendwyr** [comment]
On the bottom right corner of the new tab page there's a settings icon that looks like three lines (the one to the left of the cogwheel). You can disable sponsored images there.

**Comment by rebron** [comment]
Thanks @Ravendwyr. 

@divrse It's the "Show Sponsored Images" toggle. 

We're also looking to make this easier to find with https://github.com/brave/brave-browser/issues/4930
and https://github.com/brave/brave-core/pull/5151 

Latest Nightly has the fixes.

**Comment by rebron** [comment]
@divrse and @Ravendwyr Also, don't be so quick to turn off these sponsored images on the new tab page. We work really hard to make these images look great. If you have issues with a specific image or advertiser, please let us know. We want these to look nice. 

https://brave.com/introducing-sponsored-images-in-brave/

**Comment by divrse** [comment]
@rebron It’s actually more an aesthetic.
I usually don’t see images repeat that often with the defaults, although I would like it to be a bit more unique and new image date from Unsplash.

However, the sponsored images display the same image every 4 tabs you open which doesn’t provide a nice experience for me personally cause I notice it right away and they keep being re used.

**Comment by Ravendwyr** [comment]
I've left sponsored images on. Some of them are really beautiful!

**Comment by divrse** [comment]
Thanks for the new images in latest update :)

**Comment by rebron** [comment]
@divrse  I like these new ones too.
