### ISSUE TITLE
Duplicated top site entries after update

### ISSUE THREAD

**Issue by congard** [brave/brave-browser#9008]
## Description 
After updating to the last nightly and opening Google Translate from top sites bar, this bug occurred. Instead of my sites, there were only pinned ones. In addition, the GitHub icon has disappeared (perhaps the disappearance of the GitHub icon is due to its updating?).

## Steps to Reproduce
   1. Update to last nightly
   2. Open something from top sites bar

## Actual result:
![Screenshot_20200403_134055](https://user-images.githubusercontent.com/35779485/78352803-a8ceae80-75b1-11ea-9c4b-3f4a4c1fdf8d.png)

## Expected result:
List of my top sites and correct displaying of GitHub icon.

## Reproduces how often: 
N/A

## Brave version (brave://version info)
```
Brave: 1.9.1 Chromium: 81.0.4044.83 (Official build) unknown (64-bit)
Version: 5718ca617723806b9aacfb41108a0d911d1bde74-refs/branch-heads/4044@{#853}
OS: Linux
```

## Version/Channel Information:
- Q: Can you reproduce this issue with the nightly channel? A: Yes

## Other Additional Information:
- Q: Does the issue resolve itself when disabling Brave Shields? A: No
- Q: Does the issue resolve itself when disabling Brave Rewards? A: No
- Q: Is the issue reproducible on the latest version of Chrome? A: Yes

**Comment by cezaraugusto** [comment]
Hi @congard, did you take any action before this bug happened like pinned/excluded/re-ordered top sites?

**Comment by cezaraugusto** [comment]
Also if you don't mind, could you send me (either in this thread or Twitter DM if you prefer, same username @cezaraugusto) your NTP localStorage file? Here's the steps:

1. Go to brave://newtab and open the developer tools (`context menu` -> `inspect`).
2. Find the console tab, click
3. Paste the following:
3.1 `JSON.parse(localStorage.getItem('new-tab-data')).pinnedTopSites`
3.2 `JSON.parse(localStorage.getItem('new-tab-data')).ignoredTopSites`
3.3 `JSON.parse(localStorage.getItem('grid-sites-data-v1')).gridSites`
3.4 `JSON.parse(localStorage.getItem('grid-sites-data-v1')).topSites`

Please note that we do not store this information and it's only available in your computer (specifically your new tab). I'm requesting it because your top sites data appear to be corrupted after the update and I need a broken profile to try to reproduce your issue. Thanks for reporting!

**Comment by congard** [comment]
Hi @cezaraugusto, I didn't do anything before this happened. Just updated the browser.
3.1. undefined
3.2. undefined
3.3. 
![Screenshot_20200403_232825](https://user-images.githubusercontent.com/35779485/78402273-f32c4b80-7602-11ea-922c-7ab0c185bdc2.png)
![Screenshot_20200403_232906](https://user-images.githubusercontent.com/35779485/78402276-f45d7880-7602-11ea-88f2-8d110f7915e6.png)


3.4. undefined

**Comment by cezaraugusto** [comment]
Thanks @congard, with the data you shared I was able to reproduce and just opened a pull-request.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.8.85 Chromium: 81.0.4044.122 (Official Build) (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/5173

Before upgrade (1.7.98)
![image](https://user-images.githubusercontent.com/38657976/80479165-3fea1480-896c-11ea-93e2-5510d446d958.png)

After upgrade to 1.8.85
![image](https://user-images.githubusercontent.com/38657976/80479204-49737c80-896c-11ea-8471-4a1cc25bcd13.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.4 x64 Catalina` using the following build:

```
Brave | 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | macOS Version 10.15.4 (Build 19E287)
```

Went through the cases outlined under https://github.com/brave/brave-core/pull/5173#issue-400312677 and https://github.com/brave/brave-core/pull/5173#issuecomment-617724800 x2 times to ensure everything was working as expected.

Populated several tiles on the NTP using `1.7.98 CR: 81.0.4044.113` as per the following:

<img width="1505" alt="Screen Shot 2020-04-28 at 11 40 59 PM" src="https://user-images.githubusercontent.com/2602313/80558953-151eb100-89aa-11ea-81ab-2dfccdb92528.png">

Updated to `1.8.86 CR: 81.0.4044.129` and ensured that I didn't lose any tiles on the NTP:

<img width="1534" alt="Screen Shot 2020-04-28 at 11 42 21 PM" src="https://user-images.githubusercontent.com/2602313/80558957-194ace80-89aa-11ea-9941-5c6b7cfebf4e.png">

Used the script from https://github.com/brave/brave-core/pull/5173#issue-400312677 and ensured that both `https://translate.google.com` and `https://github.com/congard` where added in the correct positions:

![Screen Shot 2020-04-28 at 11 45 13 PM](https://user-images.githubusercontent.com/2602313/80559050-69299580-89aa-11ea-8ad0-4ac7252244bc.png)
