### ISSUE TITLE
Autoplay impossible on about:blank

### ISSUE THREAD

**Issue by Jip-Hop** [brave/brave-browser#9009]
## Description 
It's impossible to allow autoplay on about:blank (pop-up windows).

## Steps to Reproduce
   1. See example on [jsitor](https://jsitor.com/MMYtLZPvM).
   2. Allow autoplay for jsitor.
   3. Click the button to continue playback in a pop-up window.
   4. Autoplay doesn't work in the pop-up, and permission can't be given.

## Actual result:
<img width="616" alt="Screenshot 2020-04-03 at 13 41 01" src="https://user-images.githubusercontent.com/2871973/78357044-01ea1280-75b1-11ea-9074-ba6e1325c386.png">

It's not possible to click "Always allow autoplay on about:blank".
Also it's not possible to add "about:blank" to the whitelist in settings (not a valid url).

## Expected result:
Pop-up windows from a whitelisted origin should be allowed to autoplay.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
Brave | 1.5.122 Chromium: 80.0.3987.162 (Official Build) (64-bit)
-- | --
Revision | f2c5dd6138153bb0658091205bd1a1717f16081a-refs/branch-heads/3987@{#1034}
OS | macOS Version 10.14.6 (Build 18G4032)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes.
- Can you reproduce this issue with the beta channel?
Yes.
- Can you reproduce this issue with the dev channel?
Yes.
- Can you reproduce this issue with the nightly channel?
No, it's working in the nightly channel. Let's hope this behaviour makes it to the release.

## Other Additional Information:

Works fine on Chrome.

## Miscellaneous Information:
Related [post](https://community.brave.com/t/cannot-whitelist-chrome-newtab-to-allow-video-autoplay-because-chome-is-not-a-valid-url-protocol/97942).

**Comment by rebron** [comment]
Closing. @Jip-Hop We made some changes to autoplay. This shouldn't be an issue anymore. Can you check on 1.9.72, our latest version.

**Comment by rebron** [comment]
Please re-open if you're still seeing this issue.
