### ISSUE TITLE
[Desktop] Clicking Brave Shields button on a New Tab leaves button on a clicked state

### ISSUE THREAD

**Issue by afonsojramos** [brave/brave-browser#9015]
## Description 

When clicking the Brave Shields button while on a New Tab, the button stays on a clicked state, which persists even after changing tabs.

## Steps to Reproduce

   1. Open New Tab
   2. Click Brave Shields button
   3. Change tabs to observe Brave Shields button remaining on a clicked state

## Actual result:

![image](https://user-images.githubusercontent.com/19473034/78380802-5bac0600-75cc-11ea-9a1a-67965ffd0636.png)

## Expected result:

![image](https://user-images.githubusercontent.com/19473034/78380813-62d31400-75cc-11ea-823a-3675ac2880dd.png)

## Reproduces how often: 

Easy to reproduce. Always happens.

## Brave version (brave://version info)

Brave | 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Windows 10 OS Version 1909 (Build 18363.720)

**Comment by rebron** [comment]
@afonsojramos Can you try this again on 1.9.72 our latest version from yesterday? On a New Tab Page, shields should actually be disabled as it's an internal page plus and doesn't apply there, so icon should be orange and there should be a number displayed.

**Comment by afonsojramos** [comment]
I'll try it as soon as sync is back! 😊
 I need the feature too much to live without it!

**Comment by bsclifton** [comment]
Looks like this happens still - but @afonsojramos we do have sync now 😄

**Comment by afonsojramos** [comment]
This seems to be now fixed, thanks! After 1 year and a half, I've now moved back to brave! 😁

PS: I left because of the lack of proper sync.
