### ISSUE TITLE
Notification bar for top sites should auto-close after 3 seconds

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#9016]
## Description 

When you exclude a top site, a notification bar pops up with additional options. This notification should auto-close after 3s.

## Steps to Reproduce

   1. Have a top site in NTP
   2. Remove it
   3. Notification bar should pop up
   4. Wait 3 seconds

## Actual result:

Nothing happens.

## Expected result:
Notification should auto-close.

## Reproduces how often: 

Always

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.9.52 Chromium: 81.0.4044.129 (Official Build) dev (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/5156
* Confirmed notification bar auto-dismisses
* Confirmed `Undo`, `Restore All`, and `x` all still work on the banner before it auto-dismisses
* Confirmed for clean and upgrade profiles
