### ISSUE TITLE
Filter out HubSpot's email trackers from URLs

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#9019]
Fhe following query string parameters are used by HubSpot:

- `_hsenc`
- `_hsmi`
- `__hssc`
- `__hstc`
- `__hsfp`
- `hsCtaTracking`

The ones that start with double underscores are [tied to cookies](https://knowledge.hubspot.com/reports/what-cookies-does-hubspot-set-in-a-visitor-s-browser) though they are also [added to URLs](https://meta.stackexchange.com/questions/263392/what-are-these-very-long-parameters-in-so-careers-feedback-always-welcome-url).

According to https://knowledge.hubspot.com/email/links-in-emails-or-ctas-lead-to-an-error-page,
`_hsenc` [tracks the identity](https://knowledge.hubspot.com/email/manage-your-marketing-email-account-settings#identity-tracking
) of the user who clicked on the email.

They have a [number of other ad-related query string parameters](https://knowledge.hubspot.com/ads/ad-tracking-in-hubspot) which do not tie back to an individual. In particular `hsa_acc`, `hsa_cam`, `hsa_grp`, and `hsa_ad` [map to](https://knowledge.hubspot.com/ads/troubleshoot-ad-tracking-issues#resolve-facebook-ad-tracking-errors) account ID, campaign ID, ad set ID, and ad ID respectively.

Based on the examples I found on Google:
- `https://www.kaspersky.com/?utm_campaign=DM1803US-KAS&utm_source=hs_automation&utm_medium=email&utm_content=61943687&_hsenc=p2ANqtz-9CCi0_DS3jtutvTinArk34tAszuq7xG7pEtsDqlUdZzgPcPmkJdLEd9B5e2O17uqs7U29rxsQiUWOrbiOpxbohyWLAkK4ah0blhC0U7mvgHtmCcWE&_hsmi=61943687`
- `https://www.netguru.com/hubfs/Downloadables/Mobile%20Analytics%20Comparison.pdf?utm_campaign=%5BS%5D%20mobiledev&utm_medium=email&_hsenc=p2ANqtz-89X7vHUlo85kO9K_OchfKFWHe5HTWbgG9Lw_3kPHEHZBl985uCAv-k7dXKuIX9DV17jUGqqpJhDDtkhAwTEvj-lAeeOQ&_hsmi=58517518&utm_content=58517518&utm_source=hs_automation&hsCtaTracking=2871793b-e6ce-42c7-8977-7b0a3d7d3915%7C2b401771-c713-4fd9-aa59-4d3eaef6f109`

it looks like `_hsmi` is relatively low-entropy.

`hsCtaTracking`, `__hssc`, `__hstc` and `__hsfp` are high-entropy though and are
involved with [Calls-To-Action tracking](https://knowledge.hubspot.com/ctas/calls-to-action-frequently-asked-questions#why-is-the-landing-page-url-so-long-after-i-click-on-a-cta).

So we should add the following to our query string filter:
- `_hsenc`
- `__hssc`
- `__hstc`
- `__hsfp`
- `hsCtaTracking`

**Comment by fmarier** [comment]
On [this page](https://get.invisionapp.com/weekly-digest-23-2016?ecid=ACsprvudJMrZb2bze1dVaGJH4nRSLZK-89KvYIVa7J_J4sxxGQHc3LyQjuzILco_GJFgWqZpYTVl&utm_campaign=Weekly+Digest&utm_source=hs_email&utm_medium=email&utm_content=30425508&_hsenc=p2ANqtz-9T7OV7u-e6SqArP-QFd_id1smBnDtJVApCqXwdB7NojvJdMg0gnapAYq-ruSLuzqELzSOjwv53ueIR1BONjttBzqprQA&_hsmi=30425508) (linked to from a [HubSpot blog post](https://blog.hubspot.com/marketing/email-newsletter-examples-list)) I found a real unsubscribe link:

    https://get.invisionapp.com/hs/manage-preferences/unsubscribe?d=Vn0sX899rzQZW3zcgHq4fdJd6W43WJH43P3Q7wW3ZsjYm3_fYjfVGRMvr72XjpmV1yf0N3091q-W1vtlC442x6CWW5CBmdK3jsC6j183&v=3&utm_campaign=Weekly%20Digest&utm_source=hs_email&utm_medium=email&utm_content=30425508&_hsenc=p2ANqtz-9aK6cmhAju0L5bvc7wYfHZz-OZcWCDYc3M0L5u8bwzeeDF1DIkt6ihb-EqA0XZ4ojH0k1Ta2ubZS53tG1TT9vb5jagdg

which seems to also pre-fill the email address if I remove the `_hsenc` parameter. The `d` parameter in this case is the one that's used for the pre-fill. I did try it out and confirmed that I could update the subscription preferences successfully.

**Comment by bsclifton** [comment]
Added missing milestone 😄

**Comment by GeetaSarvadnya** [comment]
Verification passed on
```

Brave | 1.11.68 Chromium: 83.0.4103.106 (Official Build) dev (64-bit)
-- | --
Revision | ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
OS | Windows 10 OS Version 1903 (Build 18362.30)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/5554

 Reproduced in 1.10.x
![image](https://user-images.githubusercontent.com/38657976/85134809-b3b4e900-b25a-11ea-9319-9cc22d387b20.png)

1.11.x
![image](https://user-images.githubusercontent.com/38657976/85134863-c3ccc880-b25a-11ea-8372-731f4f777d4f.png)
