### ISSUE TITLE
Exempt intra-site requests from the query string filter

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#9020]
We have in brave-core a query string filter which removes [parameters known to be tracking individuals](https://github.com/brave/brave-core/blob/2ca5b1fc2b6fce2ed15b674c3ffb7252def29674/browser/net/brave_site_hacks_network_delegate_helper.cc#L38).

While the existing ones are pretty unlikely to conflict with legitimate query string parameters, some of the [proposed ones](https://github.com/brave/brave-browser/issues/8975) are generic enough that they might break sites which use them for non-tracking purposes.

We are proposing the following change to the query string filter: exempt same-site requests from the filter.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.16.46 Chromium: 86.0.4240.55 (Official Build) nightly (64-bit)
-- | --
Revision | a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS | Windows 10 OS Version 1903 (Build 18362.1016)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/6609
- Cross-site tests are not working as expected Logged https://github.com/brave/brave-browser/issues/11930

<details>
<summary>Verifications for Redirected same-site tests</summary>


</details>

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.16.69 x64 build
- Verified all scenarios works as expected from https://github.com/brave/brave-core/pull/6609
---------------
Verification passed on OnePlus 6T with Android 10 running 1.16.69 x64 build
- Verified all scenarios works as expected from https://github.com/brave/brave-core/pull/6609
