### ISSUE TITLE
Remove unused lastSearchTime, searchActivity, searchUrl, lastShopTime, shopActivity and shopUrl from locally persisted Brave Ads state

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#9022]
Remove unused lastSearchTime, searchActivity, searchUrl, lastShopTime, shopActivity and shopUrl from locally persisted  (`Default/ads_service/client.json`) Brave Ads state

**Comment by GeetaSarvadnya** [comment]
Verification passed on
```

Brave | 1.9.62 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/5159
- Reproduced in 1.8. 95 - `lastSearchTime`, `searchActivity`, `searchUrl`, `lastShopTime`, `shopActivity` and `shopUrl` are persisted in Default/ads_service/client.json
- ensured that `lastSearchTime`, `searchActivity`, `searchUrl`, `lastShopTime`, `shopActivity` and `shopUrl` are NOT persisted in `Default/ads_service/client.json` in 1.9.x
```
{
  "adPreferences": {
    "filtered_ads": [],
    "filtered_categories": [],
    "saved_ads": [],
    "flagged_ads": []
  },
  "adsShownHistory": [],
  "purchaseIntentSignalHistory": {},
  "adUUID": "30915544-c707-4a94-aa05-77e03cae3c73",
  "adsUUIDSeen": {},
  "advertisersUUIDSeen": {},
  "nextCheckServeAd": 0,
  "available": true,
  "userModelLanguage": "en",
  "userModelLanguages": [
    "de",
    "en",
    "fr"
  ],
  "pageScoreHistory": [],
  "creativeSetHistory": {},
  "adConversionHistory": {},
  "campaignHistory": {},
  "score": 0,
  "version_code": ""
}
```
