### ISSUE TITLE
Relabel the Private Browsing options

### ISSUE THREAD

**Issue by matteqa** [brave/brave-browser#9023]
I believe that the "New Private Window" option should be a Tor window by default and a non-Tor private window should be labelled as "New Private Window without Tor". 

This would make it more clear to people that Tor is required for a truly private session.

**Comment by rebron** [comment]
Closing as wontfix. 

Hi @matteqa. Thanks for the suggestion. Labels using the negative are hard for users to understand. 

Both Private Window and Private Window with Tor are advanced browsing options which we explain in the new tab page for both window types. They each come with their own benefits and limitations (speed and captchas in the case of Tor Window browsing).
