### ISSUE TITLE
BAT "tip" integration messes up Github's 'People' page

### ISSUE THREAD

**Issue by Nuc1eoN** [brave/brave-browser#9024]
![brave_gihub_bug](https://user-images.githubusercontent.com/2538022/78451168-18ad6980-7684-11ea-9651-0c6618565557.png)

At the bottom right you see how the BATs "tip" feature messes up the rows.

Brave v1.5.122

**Comment by LaurenWags** [comment]
Verified passed with
```
Brave | 1.9.51 Chromium: 81.0.4044.129 (Official Build) beta (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5215

Using 1.8.86, confirmed BAT tip logo visible on org's people page 
<img width="965" alt="Screen Shot 2020-05-01 at 8 27 07 AM" src="https://user-images.githubusercontent.com/28145373/80805631-95017280-8b86-11ea-8235-27f867febb6f.png">

Verified using 1.9.x that org's people page does not contain BAT logo:
<img width="958" alt="Screen Shot 2020-05-01 at 8 29 52 AM" src="https://user-images.githubusercontent.com/28145373/80805641-9f237100-8b86-11ea-8146-eb6078f115dc.png">
