### ISSUE TITLE
npm run init fails. Cannot find path of Visual Studio 17

### ISSUE THREAD

**Issue by CredixYt** [brave/brave-browser#9025]
## Description 
`npm run init` fails when trying to find Visual Studio path.

## Steps to Reproduce
   1. Download the required software and dependencies mentioned on the Windows requirements Wiki page
   2. Download the repository using `git clone`
   3. Run `npm install` and `npm run init` in the directory

## Actual result:
[npm logs](https://pastebin.com/NidSSncZ)
[Screenshot of terminal](https://i.ibb.co/FzfXR6d/Capture.png)

## Expected result:
`npm run init` runs succesfully

## Reproduces how often: 
Easily reproduced (on my machine)

## Brave version (brave://version info)
Irrelevant

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Did not try
- Can you reproduce this issue with the dev channel? Did not try
- Can you reproduce this issue with the nightly channel? Did not try

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? Irrelevant
- Does the issue resolve itself when disabling Brave Rewards? Irrelevant
- Is the issue reproducible on the latest version of Chrome? Irrelevant

## Miscellaneous Information:
Operating System: Windows 10 Pro x64 (Version 1909)
Visual Studio: Community 17, Version: 15.9.21
Windows SDK: 10.0.18362.1
Git: 2.25.1.windows.1 (x64)
Node: v12.16.1 (x64)
npm: 6.13.4
Python: 2.7.17:c2f86d86e6 (x64)

**Comment by bsclifton** [comment]
Updated the wiki to recommend using VS 2019 - I think it might be required now and the compile problems originally reported have been fixed as far as I know. Thanks!
