### ISSUE TITLE
[Feature] Support for policies for Brave specific features

### ISSUE THREAD

**Issue by r3pek** [brave/brave-browser#9026]
## Description 

Chrome/Chromium has support to manage certain features using [policies](https://cloud.google.com/docs/chrome-enterprise/policies/). I'd like to ask that for Brave specific features, exists an equivalent Policy so that it can be managed/configured centrally and deployed to all clients.

## Brave version (brave://version info)

Brave | 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)

**Comment by Prowler2** [comment]
See my github page at the link below. For Brave v1.3 and above, I have been testing some ADMX templates to ease applying policy to Brave in an enterprise environment. Policy for Brave specific features such as TOR are included. It is still a work in progress.
https://github.com/Prowler2/Brave-Browser-GPO-Policy

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/9458

@Prowler2 awesome! Thanks for sharing that 😄 I may hit you up with questions, as we'd like to have some official templates available 😄

**Comment by Prowler2** [comment]
@bsclifton, happy to help. I knew this was going to be a non-negotiable requirement for wide deployment within enterprises. These have been working fine in my domain. Is there a way to get a list of the chrome policy (registry keys) Brave still uses?

**Comment by bsclifton** [comment]
@Prowler2 I usually go off `common/html/en-US/chrome_policy_list.html`  from here:
https://dl.google.com/dl/edgedl/chrome/policy/policy_templates.zip

They also include a reg file with all values set. But it looks like there's an online version now:
https://cloud.google.com/docs/chrome-enterprise/policies/
