### ISSUE TITLE
Support UBO twitch-videoad js snippet

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#9027]
## Description 
Viewing twitch,tv with shields up /site-tracking enabled, video ads are getting through in Nightly.

## Steps to Reproduce

   1. Open Nightly (tested in 1.9.4)
   2. Browse various streams. (Tested on https://www.twitch.tv/esl_csgo)
   3. In-video ad will show.

## Actual result:
(sample of video ad)
![twitch-ad](https://user-images.githubusercontent.com/1659004/78464968-275b5580-7744-11ea-9d53-091497274673.png)
![twitch-ad2](https://user-images.githubusercontent.com/1659004/78465222-d00ab480-7746-11ea-8da3-a90f488f82b3.png)

## Expected result:
Expect no invideo ads

## Reproduces how often: 
May require a bit of browsing of twitch streams to replicate.

## Brave version (brave://version info)
Tested in `Version 1.9.4 Chromium: 81.0.4044.83 (Official Build) nightly (64-bit)`

## Miscellaneous Information:
uBO is using the following filter: `twitch.tv##+js(twitch-videoad)`

**Orginal PR**: `https://github.com/uBlockOrigin/uAssets/pull/3517`
**Snippet:** `https://github.com/gorhill/uBlock/blob/a94df7f3b27080ae2dcb3b914ace39c0c294d2f6/assets/resources/scriptlets.js#L913`

**Comment by antonok-edm** [comment]
Should have been fixed by https://github.com/brave/brave-core/pull/5402 which is in Brave Stable as of 1.9.72, feel free to reopen if that hasn't fixed it.
