### ISSUE TITLE
NTP favicon tiles appear to be invisible (same color as tile)

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#9030]
For example, in the below image, the blank item is github.com, which shows favicon when visited directly as expected.  I've also seen for other items, like politico.com (fourth from the left in the image).
<img width="706" alt="Screen Shot 2020-04-05 at 8 33 12 PM" src="https://user-images.githubusercontent.com/76526/78521799-f0a33080-777f-11ea-9b4e-05df29c8837d.png">

As @simonhong asked, chrome://favicon/size/64@1x/https://www.github.com shows the below currently, as this is happening on my machine
<img width="173" alt="Screen Shot 2020-04-05 at 8 48 51 PM" src="https://user-images.githubusercontent.com/76526/78521784-de28f700-777f-11ea-8d42-55315809891b.png">

**Comment by simonhong** [comment]
After reloading github.com and after restarting, @pes10k still can't see github favicon in NTP.

**Comment by cezaraugusto** [comment]
This is a design issue (cc @karenkliu). GitHub is theme-aware and will load the icon based on the opposite browser color (dark theme == white logo/light theme = black logo). Icon is there, it's just the same color as the background.

Adding @rebron for coordination.

**Comment by karenkliu** [comment]
Yeah, I definitely think we should do this; can we fix the fuzzy icons and make the top site tiles theme-aware? There is already a spec for this @rebron

**Comment by rebron** [comment]
Related to #480

**Comment by bsclifton** [comment]
+1 from @l3lackcurtains via https://github.com/brave/brave-browser/issues/11650

Comment from @karenkliu https://github.com/brave/brave-browser/issues/11650#issuecomment-690598316
> @rebron We need to stop using hard background colors and instead dynamically generate the background color for tiles similar to how iOS has it implemented:
> 
> > Default color: #A7ACB2
> > Icon color is derived in the following order:
> > 
> > * “theme-color” meta tag value, if available return this color.
> > * “msapplication-navbutton-color” meta tag value, if available return this color.
> > * “apple-mobile-web-app-status-bar-style” meta tag value, if available return this color.
> > * Final sample attempt - sample color from three points on website
> >   Desktop version - https://github.com/brave/browser-laptop/blob/6ac06a4bcb60e2fd2a4bba6795dbe240f399c234/app/extensions/brave/content/scripts/themeColor.js
> >   Mobile version - https://github.com/brave/browser-ios/blob/97d2eddeb023660d47c05de0215f2157471655da/Client/Assets/ThemeColor.js(uses y=1 vs y=3 for more accurate sampling — mobile site headers are smaller)
> > * Determine if color result is too light to be displayed. Text will always appear white over color, if background color lacks contrast (several sites may return white) we fallback to default color.
> > 
> > Checking if a color is too light
> > 
> > * Color RGB value is converted to grayscale format and checked against our acceptable value, > 50% white would require a fallback to default color #A7ACB2
> > * iOS uses internal color function getWhite() which returns a white color alpha based on %. You can achieve a similar check in javascript by using W3C recommended formula for accessibility (accepted answer here https://stackoverflow.com/questions/3942878/how-to-decide-font-color-in-white-or-black-depending-on-background-color)
> 
> We should end up with different colored tiles that have good contrast:
> <img alt="Screen Shot 2020-09-10 at 11 21 38 AM" width="421" src="https://user-images.githubusercontent.com/2388823/92780348-dfc2a080-f357-11ea-99a2-3d1e42945ade.png">

**Comment by bsclifton** [comment]
Some icons (GitHub for example) will be fixed with https://github.com/brave/brave-core/pull/8339

**Comment by bsclifton** [comment]
@pes10k this should now be fixed 😄 Can you please confirm?

**Comment by pes10k** [comment]
lgtm! <3
