### ISSUE TITLE
Dashboard clock should be toggled between 12- and 24-hour time (Enhancement)

### ISSUE THREAD

**Issue by theHedster** [brave/brave-browser#9038]
The Dashboard on a new tab displays 12-hour time and cannot be changed to 24-hour time.

## Steps to Reproduce

   1. Launch Brave.
   2. Open a new tab. The Dashboard displays the current time in AM/PM 12-hour format.
 
## Expected result:
Time display should allow toggling between 12- and 24-hour time.

## Reproduces how often: 
Occurs by design.

## Brave version (brave://version info)
Brave	1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)
Revision	e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS	Windows 10 OS Version 1903 (Build 18362.720)
JavaScript	V8 8.0.426.30
Flash	(Disabled)
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
Command Line	"C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AllowPopupsDuringPageUnload,AutofillServerCommunication,AudioServiceOutOfProcess,SmsReceiver,LookalikeUrlNavigationSuggestionsUI,WebXR,NotificationTriggers,VideoPlaybackQuality,WebXrGamepadModule --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path	C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\hedley.MONICA-PC\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations	5e3a236d-4113a79e

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  No

## Miscellaneous Information:
This issue has been previously raised in #1308 where the request was for the Dash clock to respect the locale setting. However, most OSs allow the user to override the locale setting to force either 12- or 24-hour time. Therefore, the Dash clock should honour system time format, not locale format.

**Comment by DanielVenturini** [comment]
I'm using the Brave version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit) in Lubuntu 16.04 and it'd very nice to have an option to change between 12-24 hour time. Like in https://github.com/brave/brave-browser/issues/1308#issuecomment-525482063, I changed to pt-BR (Brazilian Portuguese) and relaunch, but it didn't work.

**Comment by bsclifton** [comment]
Related https://github.com/brave/brave-browser/issues/7951

**Comment by eugeneseppel** [comment]
I also would vote for this issue. I live in Estonia and when I saw clock value "2:19" during daytime it was astonishing -- my first idea was that something is wrong with computer clock, battery and time synchronization. Of course in spoken language we say "two o'clock and nineteen minutes", but almost never write in this way. The same story for all post-soviet countries, like Russia and Ukraine.
Winter nights (as well as days) in the northern Europe are dark and full of terrors, so if you wake up and see "4 o'clock" there is no chance to distinguish whether it is a day or night. Same story during white nights in June:)

**Comment by BunnyTheLifeguard** [comment]
Yes, please!

**Comment by scofieldbrks** [comment]
bsclifton, you are soooo full of bs.

This issue is still not fixed due to interference by a Brave VP of Engineering, bsclifton. He is hung on the locale of the system, not the fact that it needs to be a user toggle. And c++ is too hard for him to program a wee bit of time code.
bsclifton stated over 2 years ago that this issue can not be fixed and if you follow him over the years, he closes this issue time and time again. He claims he can't write any code that will allow for a 24 hour clock (he claims he writes c++ and Java). This is bunk. C++ most definitely can support a 24 clock (it does). As a supposed VP of Engineering at Brave, he should assign this issue to a programmer. Here's a little code to refresh bsclifton's memory of c++ and how easy it would be to fix this issue.

// C++ program to convert 12 hour to 24 hour
// format
#include
using namespace std;

void print24(string str)
{
// Get hours
int h1 = (int)str[1] - '0';
int h2 = (int)str[0] - '0';
int hh = (h2 * 10 + h1 % 10);

// If time is in "AM" 
if (str[8] == 'A') 
{ 
	if (hh == 12) 
	{ 
		cout << "00"; 
		for (int i=2; i <= 7; i++) 
			cout << str[i]; 
	} 
	else
	{ 
		for (int i=0; i <= 7; i++) 
			cout << str[i]; 
	} 
} 

// If time is in "PM" 
else
{ 
	if (hh == 12) 
	{ 
		cout << "12"; 
		for (int i=2; i <= 7; i++) 
			cout << str[i]; 
	} 
	else
	{ 
		hh = hh + 12; 
		cout << hh; 
		for (int i=2; i <= 7; i++) 
			cout << str[i]; 
	} 
} 
}

// Driver code
int main()
{
string str = "06:15:30PM";
print24(str);
return 0;
}

**Comment by sethasaurus** [comment]
PLEASE!

**Comment by wavesurf432** [comment]
It would be great to have the choice between 24 hour and am/pm!

On Windows 7 I noticed Brave would recognise system time, but not with Linux.

**Comment by sethasaurus** [comment]
OK I don't care anymore. Just removed the clock from my start page :)

**Comment by eugeneseppel** [comment]
On my MacOS Brave also shows the system time like "18:02", meanwhile on GNU/Linux it is a weird "6:02"

**Comment by bsclifton** [comment]
Great news everybody - I set aside some time earlier this week and got this sorted out 😄 
https://github.com/brave/brave-core/pull/6667

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.16.54 Chromium: 86.0.4240.72 (Official Build) dev (64-bit)
-- | --
Revision | 581582174c512f44f44fd1aea340471f54b2365f-refs/branch-heads/4240@{#1134}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/6667

Verified in 12h format
![image](https://user-images.githubusercontent.com/34715963/95309627-aebc8980-088b-11eb-9c2a-3e9dcac3228e.png)

Verified in 24h format
![image](https://user-images.githubusercontent.com/34715963/95309736-d1e73900-088b-11eb-8d59-b5732a64d38c.png)

Verified Automatic (en_US) format
![image](https://user-images.githubusercontent.com/34715963/95309805-e6c3cc80-088b-11eb-989a-827e201e8be6.png)

Verified Automatic (pl) format
![image](https://user-images.githubusercontent.com/34715963/95310088-44f0af80-088c-11eb-8af1-5055725a20c9.png)

Logged https://github.com/brave/brave-browser/issues/12029 for missing translations.

Verified cycling formats by clicking the clock works

**Comment by howdev** [comment]
wonder why this is a problem. before 116.68, it has been displaying 24hour clock
