### ISSUE TITLE
[Android] URL is shown behind tab count on private tab when bottom toolbar is disabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9040]
## Description 
URL is shown behind tab count on private tab when bottom toolbar is disabled

## Steps to reproduce 

   1. Disable bottom tool bar
   2. Open a long URL in a private tab
   3. Tab count is shown inside URL bar making it transparent and looks very clumsy 

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/78542036-34477a00-7814-11ea-9d97-8a2970087a87.png)

## Expected result
Not what is in screenshot

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
10

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
+1 from @derekantrican via #9145

**Comment by AlexeyBarabash** [comment]
I also was able to see it.

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J5 version 5.1.1 running `BraveModernarm.apk 1.8.93`
![image](https://user-images.githubusercontent.com/38657976/81152920-0afb4480-8fa0-11ea-82d1-941cb3e698d6.png)
