### ISSUE TITLE
[Android] WebRTC test fails

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9041]
## Description 
WebRTC test fails

## Steps to reproduce 
Upgrade
   1. Install 1.5.9 and enable fingerprinting, ensure 2 items are blocked
   2. Upgrade to 1.5.120, fingerprinting fails. IP address is shown
   3. Upgrade to 1.5.130, fingerprinting still fails

Clean Install
   1. Clean install 1.5.130
   2. Visit https://browserleaks.com/webrtc
   3. IP address is shown and not blocked 
## Actual result 
![image](https://user-images.githubusercontent.com/17010094/78547533-e1be8b80-781c-11ea-98e9-512582c7f915.png)

## Expected result
WebRTC should be blocked by default 

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes on 1.5.120
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.5.9 - Blocked
1.5.120 - Not Blocked
1.5.130 - Not Blocked

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

No

**Comment by samartnik** [comment]
Unlike android-tabs, on brave-core we block only 3rd party fingerprinting. We need new design to add ability to set blocking fingerprinting and cookies fully.
cc @anthonypkeane @jamesmudgett

**Comment by anthonypkeane** [comment]
@karenkliu has a design for that and it is detailed here: https://github.com/brave/brave-browser/issues/6831

Can you cherry pick the design you need from https://github.com/brave/brave-browser/issues/6831? If not please LMK and a specific design can be added here.

**Comment by karenkliu** [comment]
@samartnik 
![shields subpanels](https://user-images.githubusercontent.com/2388823/78924668-14e86100-7a4f-11ea-9966-8118a52ec143.png)

**Comment by SergeyZhukovsky** [comment]
we are going to redo the shields UI and add appropriate controls

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/unable-to-disable-webrtc-in-brave-android/122548/2 for not able to disable WebRTC on Android

**Comment by SergeyZhukovsky** [comment]
That will be fixed in context of that issue https://github.com/brave/brave-browser/issues/6831

**Comment by anthonypkeane** [comment]
@kjozwiak can you please re-test

**Comment by srirambv** [comment]
This is still an issue. Irrespective of Fingerprinting settings (standard/strict) IP address is still shown. On the contrary desktop blocks it irrespective of FP setting

**Comment by waynea** [comment]
This issue is still live - has there been any progress towards a fix?

**Comment by samartnik** [comment]
@srirambv is it stil n issue? WebRTC is not tied to fingerprinting option anymore, but controlled by `WebRTC IP handling policy` option.

**Comment by srirambv** [comment]
Yes the issue can be closed based on @pes10k  comment https://bravesoftware.slack.com/archives/C0816QH3R/p1618496425224300?thread_ts=1618487465.215300&cid=C0816QH3R
