### ISSUE TITLE
Canvas fingerprinting is not blocked

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#9043]
## Description 

Fingerprinting blocked is not working

## Steps to Reproduce

   1. Clean profile 1.7.86 CR 80.0.3987.163
   2. Navigate to https://jsfiddle.net/bkf50r8v/13/
   3. Open shield and check the fingerprinting blocked count in the shield
   4. fingerprinting isn't blocked for cancas

STR 2: 
   1. Clean profile 1.7.86
   2. Open browserleaks.com/canvas 
   3. Open shield and select `Fingerprints attemps blocked`
   4. Fingerprint info is shown which is not correct (see image 2 in the actual result)

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/78556111-0110e500-782c-11ea-89d8-c5429aaa8c94.png)

```
fingerprinting test
got canvas fingerprint data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB9AAAADICAYAAACwGnoBAAAgAElEQVR4Xu3d23LbOBAFQOT/P1pbKjtZp2zHFAmAc+l9XRIY9CCSzCNSv4b/CBAgQIAAAQLtBH6NMR7tVm3BBAgQIECAQGcBn386d9/aCRAgQIAAAQIECBA4LvD868l/BAgQIECAAAECBAgQIECAQDoBg
```

![image](https://user-images.githubusercontent.com/38657976/78559197-96fb3e80-7831-11ea-99ee-4ae4fe8d5ee7.png)

## Expected result:
Canvas fingerprint should be blocked

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.7.86 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron

**Comment by srirambv** [comment]
cc: @diracdeltas @pes10k @fmarier

**Comment by LaurenWags** [comment]
is this related to https://github.com/brave/brave-browser/issues/1091 ?

**Comment by srirambv** [comment]
No this is a failure in blocking canvas fingerprinting

**Comment by pes10k** [comment]
Now that we use farbling / randomization as our primary defense against canvas fingerprinting, we no longer add the notification to shields (since it'd result in way too many false positives).

But canvas fingerprinting is being blocked; you can see this when you run the fiddle in two different sessions.  You get a different fingerprint both times.

I think this is not a bug
