### ISSUE TITLE
[Android] Closing all tabs doesn't close Brave when setting is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9044]
## Description 
 Closing all tabs doesn't close Brave

## Steps to reproduce 

   1. Enable `Closing all tabs closes Brave` from settings
   2. Close all open tabs
   3. Browser doesn't quit

## Actual result 
 Closing all tabs doesn't close Brave when setting is enabled

## Expected result
 Closing all tabs should close Brave when setting is enabled

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): All
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.5.120

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Doesn't reproduce on my x86 device - Asus Zenfone 1.5.120

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.131 x64 stable build
- Verified closing all tabs don't close browser when the setting is disabled
- Verified closing all tabs closes browser when the setting is enabled
- Verified closing all normal tabs with a private tab open doesn't close the browser
- Verified closing all private tabs with a normal tab open doesn't close the browser
