### ISSUE TITLE
[Android] Greek Translation Words after latest update

### ISSUE THREAD

**Issue by giwrgosmant** [brave/brave-browser#9045]
After latest update to 1.5.120 some words are in English and not in Greek like it was.
![Screenshot_2020-04-06-15-57-34-940_com brave browser](https://user-images.githubusercontent.com/51835189/78561235-0a945000-7820-11ea-9ea1-f9e9141fe446.jpg)
![Screenshot_2020-04-06-15-57-41-135_com brave browser](https://user-images.githubusercontent.com/51835189/78561241-0e27d700-7820-11ea-8c25-9ab9c7fe3e7a.jpg)

**Comment by giwrgosmant** [comment]
@srirambv 
I've already translated most of the words at transifex but still after updates the Greek translation haven't be fixed.
Please if you can take a look and push the changes in next update.

**Comment by srirambv** [comment]
cc: @mkarolin

**Comment by giwrgosmant** [comment]
Translation seems to be fixed in version Brave 1.12.113. 👍
