### ISSUE TITLE
[Android] Replace Chromium incognito icon 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9046]
## Description 
Replace Chromium incognito icon 

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/78575625-3c6ddc80-7849-11ea-856c-464a765606d2.png)
![image](https://user-images.githubusercontent.com/17010094/78575672-4e4f7f80-7849-11ea-9e99-acf3b393f37f.png)

## Expected result
Use Brave icons

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Tab A
   - Android version: 9.0
   
## Brave version
1.5.120/1.5.130

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by eljuno** [comment]
+1 from Community with Tab Grid flag enabled

https://community.brave.com/t/change-incognito-icon/117170/2?u=eljuno

**Comment by kjozwiak** [comment]
@srirambv believe this tablet specific so I added `android-tablet-specific`. Please remove if this affects mobile/phones as well.

**Comment by srirambv** [comment]
This affects both

**Comment by srirambv** [comment]
- Verification passed on Samsung Tab A with Android 9 running 1.5.131 x64 stable build
![image](https://user-images.githubusercontent.com/17010094/78747155-552fdc80-7986-11ea-94a2-f178e31df547.png)

- This is not fixed on mobile when `Tab grid layout` is set to `Enabled New Tab Variation` 
![image](https://user-images.githubusercontent.com/17010094/78747236-8b6d5c00-7986-11ea-9cfe-c6d2cf21b759.png)
