### ISSUE TITLE
[Android] Brave block cookies and can't be be deleted

### ISSUE THREAD

**Issue by eljuno** [brave/brave-browser#9055]
## Description 

After updating to 1.5.120 via Play Store, Brave automatically logged me out from community.brave.com and Twitter -- I'm not logged in on many sites.

Site settings show Brave block cookies for Community and Twitter. Reset will not clear the cookies setting.

I need to allow 3rd party cookies in order to relogin.

So far only happens on Community and Twitter. Other site like BAT Community is not affected.

## Steps to reproduce 

   1. Visit community.brave.com
   2. Click padlock icon > Site settings. Cookies blocked. Unable to login.
   3. Allow 3rd party cookies and relogin.
   4. Changing to block 3rd party cookies will logged me out again.

## Actual result 

https://drive.google.com/file/d/1LhlGSiMm6oUn8OTSUR1bcjxQ13EPNge-/view

## Expected result

With 3rd party cookies blocked, I'm able to login and Brave will keep me logged in. And resetting Site settings will also clear the cookies setting.

## Issue reproduces how often 

Easy on my end

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? NDA

## Device details
   - Install type (ARM, x86): NDA
   - Device (Phone, Tablet, Phablet): Redmi Note 5
   - Android version: 9
   
## Brave version
1.5.120

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? With 3rd party cookies allowed
- Does the issue resolve itself when disabling Brave Rewards? NDA
- Is the issue reproducible on the latest version of Chrome? NDA

### Additional information

cc @srirambv @SergeyZhukovsky

**Comment by samartnik** [comment]
Steps for QA:
Case 1:
1. install 1.5.9
2. on community.brave.com turn `Block 3rd party cookies` off and back on
3. login to community.brave.com
4. upgrade to 1.5.120 and make sure login doesn't work
5. upgrade to the newest version with fix, make sure login works

Case 2:
1. install 1.5.120
2. on community.brave.com turn `Block 3rd party cookies` off and back on
3. login won't work
4. upgrade to the newest version with fix
5. on community.brave.com turn `Block 3rd party cookies` off and back on
6. login should work

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.5.131 x64 stable build
- Verified test plan from https://github.com/brave/brave-browser/issues/9055#issuecomment-610455287
-------
Verification passed on Samsung Tab A with Android 9 running 1.5.131 x64 stable build
- Verified test plan from https://github.com/brave/brave-browser/issues/9055#issuecomment-610455287
-------
