### ISSUE TITLE
Notifications not working on Wordpress site

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#9064]
## Description 
Visiting `https://cookandcount.wordpress.com/` (while logged into wordpress.com) stops  notifications from showing up.

## Steps to Reproduce

   1. Login to `wordpress.com` first
   2. Then visit `https://cookandcount.wordpress.com/` 
   3. With shields up, click on the Wordpress Bell on the top right.

## Actual result:
![wp-broken](https://user-images.githubusercontent.com/1659004/78618896-e001d000-78cf-11ea-9353-24fe7d60bfbe.png)

## Expected result:
With `Allow all cookies` / Shields Down.

![wp-unbroken](https://user-images.githubusercontent.com/1659004/78618883-d8422b80-78cf-11ea-96e6-5c4f92877e71.png)

## Reproduces how often: 
Easily

## Brave version (brave://version info)
``Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)``

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
Tested in the referrer list: (without any luck)
`                "​​https://*.wordpress.com/*",`
`                "https://*.wp.com/*",`

Cookies being blocked:
![wp-cookies](https://user-images.githubusercontent.com/1659004/78619069-57cffa80-78d0-11ea-9130-6f32881aec02.png)

`Allow all cookies is needed`

**Comment by ryanbr** [comment]
@pes The cookies being affected:

```
*.public-api.wordpress.com/wp_api
*.public-api.wordpress.com/wp_api_sec
```

Whitelisting these cookies seems to fix the wordpress notifications issues.

**Comment by pes10k** [comment]
From slack convo:

> @pes: The problem here is third party cookies.  This seems crazy, but the reason why is that the side widget is an iframe pointing to widgets.wp.com, and that iframe tries to set up a websocket back to wordpress.com.  Since that request to wordpress is 3p (relative to wp.com) the websocket setup request doesn’t carry cookies, and it falls over

**Comment by rebron** [comment]
<img width="1278" alt="Screen Shot 2020-05-27 at 5 48 40 PM" src="https://user-images.githubusercontent.com/5951041/83085993-64f0a680-a042-11ea-8e64-442487439824.png">

verified works on following STR:
Brave | 1.10.73 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.5 (Build 19F83c)

**Comment by rebron** [comment]
<img width="1290" alt="Screen Shot 2020-05-27 at 5 53 09 PM" src="https://user-images.githubusercontent.com/5951041/83086255-18f23180-a043-11ea-966e-47fcf4fcd547.png">

Verified works on Nightly version below following STR:
Brave | 1.11.31 Chromium: 83.0.4103.61 (Official Build) nightly (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | macOS Version 10.15.5 (Build 19F83c)

**Comment by GeetaSarvadnya** [comment]
Verification passed on
```

Brave | 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Verified STR from the description
- Verified that with default shield settings Wordpress Bell notifications are shown

![image](https://user-images.githubusercontent.com/38657976/83147398-40b1ca00-a115-11ea-940b-089cf9b936a3.png)
