### ISSUE TITLE
Promotion transfer db problem

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9065]
We have an error in https://github.com/brave/brave-core/blob/1b8ce32b77ba1353ed84e3a7cc55c88390b55afc/vendor/bat-native-ledger/src/bat/ledger/internal/database/database_unblinded_token.cc#L416 function as query is not correct. 

Command type should be `READ` and we should have record bindings.

Introduced with https://github.com/brave/brave-core/pull/4960

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.8.82 Chromium: 81.0.4044.113 (Official Build) dev (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/5172

```
[ RESPONSE - OnTransferAnonToExternalWallet ]
> time: 1587499913
> result: Success
```

```
[ RESPONSE - DeleteTokens ]
> time: 1587499913
> result: Success
```

<img width="1167" alt="Screen Shot 2020-04-21 at 4 12 43 PM" src="https://user-images.githubusercontent.com/28145373/79909548-29334300-83eb-11ea-8d9b-f89dccd99d26.png">
