### ISSUE TITLE
[Desktop] Responsive design are not working. (Media Queries or @media)

### ISSUE THREAD

**Issue by NicolasZim** [brave/brave-browser#9068]
## Description 
I'm a web developer and i use Brave primarly. However usually i got some difference between the websites workflow in Chrome/Firefox and Brave. So, last week i got this problem when i was trying to make my website project responsive.

Create a project and create media queries like this -> `@media all and (max-width: 700px)`.
Then you should test resizing the screen inside the browser with "Responsive Design Mode" truned on with console elements oppened in some elemnt with media querie.

## How to Reproduce

I don't know if you need to put some specific width to work, but i used 700px|600px|500px but you should randomnly media queries sizes and test if works correct.

## Actual result:

Brave screenshots:
`@media all and (max-width: 700px)`
In 631px http://prntscr.com/rutj7n
and  630px http://prntscr.com/rutjre
As you can see in the **console elementes** the media querie it's in 700px.

## Expected result:
Chrome screenshots:
http://prntscr.com/rutmtl

Mozilla Developer Edition screenshots:
http://prntscr.com/rutns1

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

Brave | 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)

Maybe can be useful too:
OS | Windows 10 OS Version 1809 (Build 17763.1098)
JavaScript | V8 8.0.426.30
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36

# If has something else i can do to help, please submit a awnser in this post, and i will try my best.

**Comment by rebron** [comment]
@NicolasZim Are you still seeing this issue in 1.9.72?
