### ISSUE TITLE
Purchase intent keyword matching should use different variations of the keyword

### ISSUE THREAD

**Issue by moritzhaller** [brave/brave-browser#9070]
Improve Purchase Intent Keyword Matching with stemming keywords, e.g. "reviews" should match the same as "review"

**Comment by tmancey** [comment]
https://github.com/brave/brave-browser/issues/9806

**Comment by tmancey** [comment]
@dimmu Can you please hook up with @moritzhaller to further discuss implementation detail

**Comment by tmancey** [comment]
Blocked as needs more info

**Comment by moritzhaller** [comment]
I gave it some thought and suggest we close this issue since keyword matching doesn't require fuzzy matching. If advertisers wanted to match e.g. "reviews" in addition to "review" then it should be added explicitly to the list.
