### ISSUE TITLE
[Android] renaming 'Other Bookmarks' on Android does not propagate changes to desktop - follow up to 7639

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9073]
## Description 
Follow up to https://github.com/brave/brave-browser/issues/7639 - specifically the "Rename" test plan from PR https://github.com/brave/brave-core/pull/4404

## Steps to reproduce 

 1. Go to `about:flag#brave-sync` and enable sync on desktop A and desktop B
 2. Sync desktop A, desktop B and then sync mobile C
 3. Wait until each device has 3 devices on its device list
 4. Add `folder A` in "Other Bookmarks" permanent node on desktop A
 5. Desktop B should have `folder A` appears in “Other Bookmarks” permanent node
 6. Mobile C should have `folder A` appears in “Other Bookmarks” folder
 7. Add `folder B` after `folder A` on mobile C
 8. Desktop A and desktop B should have `folder B` after `folder A`
 9. Rename “Other Bookmarks”  folder on mobile C
--> Desktop A & B should have all children of "Other Bookmarks" moved to the renamed folder

Once above is working, should also confirm these steps from the original PR (they are also not working currently)
- Add `folder D` on desktop A in "Other Bookmarks" permanent node
- Confirm mobile C should have new "Other Bookmarks" folder created with `folder D` in it

## Actual result 
Nothing happens on desktop (waited 20+ minutes)

## Expected result
Desktop A & B should have all children of "Other Bookmarks" moved to a renamed folder

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? yes, 1.5.120
   - Beta build? n/a

## Device details
   - Install type (ARM, x86): all
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
using 1.7.86 on macOS for both desktop devices A and B, using Pixel 3XL with 1.5.120 on Android as device C

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
This issue is reproducible in IOS also. In place of mobile C instead of using Android, I have used IOS -iPhone 8- Issue still persists renamed `Other bookmarks` on ios is not propagated to desktop Devices A and Device B 
@srirambv Is there any separate issue filed for this in IOS or can we add IOS label to the same issue?

**Comment by srirambv** [comment]
If its happening on both mobile platforms then its probably an issue with the sync library. @GeetaSarvadnya  please log an issue on iOS so that it can be checked with iOS as well 

cc: @AlexeyBarabash @darkdh

**Comment by GeetaSarvadnya** [comment]
Logged an issue in IOS repo:  https://github.com/brave/brave-ios/issues/2458
cc: @AlexeyBarabash @darkdh @srirambv

**Comment by anthonypkeane** [comment]
Sync v2 should solve this
