### ISSUE TITLE
[Android] Open tabs in Custom Tabs option

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#9074]
## Description 
In old tabs version we had an option `Settings->Accessibility->Open tabs in Custom Tabs`. It looks like it is missed in the brave-core based build

## Steps to reproduce 

   1. Go to `Settings->Accessibility`.

## Actual result 
There is no `Open tabs in Custom Tabs` option

## Expected result
There is `Open tabs in Custom Tabs` option
![Screenshot_20200407-160845](https://user-images.githubusercontent.com/12011303/78714601-2b28dc80-78ea-11ea-8fa5-ba8a31d9898c.png)

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
As per discussion https://bravesoftware.slack.com/archives/CM17J5QMU/p1586351671279700
option is moved to `Controls` section
![Screenshot from 2020-04-08 15-40-27](https://user-images.githubusercontent.com/30602739/78827085-91783280-79b0-11ea-9dcc-2c939ea38b2f.png)

**Comment by samartnik** [comment]
It also requires additional translations

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.7.100 x64 stable build
- Verified opening a link in custom tab works when the setting is enabled
- Verified custom tabs are not loaded when the setting is turned off
- Verified toggle setting doesn't require browser restart
- Verified `Open tabs in Custom Tabs` is under Controls section in settings
![image](https://user-images.githubusercontent.com/17010094/80203405-b9b89000-8644-11ea-85cf-8ac6c5722274.png)
