### ISSUE TITLE
Brave not using native notification on Arch Linux

### ISSUE THREAD

**Issue by alexb7711** [brave/brave-browser#9075]
## Description 
I enabled native notifications and it is still using the default notification manager. It sometimes works after toggling it on and off, but after I restart my computer it goes back to the default notification style.

OS: Arch Linux 

## Steps to Reproduce

1. Install dunst
2. Install brave-bin through AUR on Arch Linux
3. Enable native notifications
4. Try sending yourself a [notification](https://www.bennish.net/web-notifications.html)

## Expected result:
Notification to come through notify-send rather than Brave

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

```
Brave | 1.5.123 Chromium: 80.0.3987.163 (Official Build) unknown (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | Linux
JavaScript | V8 8.0.426.30
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
Command Line | /usr/lib/brave-bin/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,WebXR,AllowPopupsDuringPageUnload,NotificationTriggers,SmsReceiver,AudioServiceOutOfProcess,LookalikeUrlNavigationSuggestionsUI,VideoPlaybackQuality,WebXrGamepadModule --flag-switches-begin --enable-features=PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator,NativeNotifications,ReaderMode --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /usr/lib/brave-bin/brave
```
## Version/Channel Information:

I have not tried it using brave-git.

**Comment by congard** [comment]
On Brave nightly everything OK, but can see another problem. There is something wrong with the theme.

```
Brave: 1.9.1 Chromium: 81.0.4044.83 (Official build) unknown (64-bit)
Revision: 5718ca617723806b9aacfb41108a0d911d1bde74-refs/branch-heads/4044@{#853}
OS: ArchLinux
```

![Screenshot_20200408_104809](https://user-images.githubusercontent.com/35779485/78758894-7fce6500-7987-11ea-94a4-cf75acfda3a0.png)
![Screenshot_20200408_105051](https://user-images.githubusercontent.com/35779485/78759043-b4dab780-7987-11ea-9ccd-e8fdf2fcc423.png)
![Screenshot_20200408_105106](https://user-images.githubusercontent.com/35779485/78759066-bb692f00-7987-11ea-8b25-22b01e5ae793.png)

**Comment by alexb7711** [comment]
Update:

I installed libnotify on my system and it sort of works. Before opening Brave, if I send myself a notification just by typing `notify-send test` in the console, Brave will then send notifications through my notification daemon.

**Comment by nsklaus** [comment]
it doesn't work for me.

i'm on arch and using dunst too. i installed brave-nightly from aur.
in brave://flags i have set it to use native notifications.
but brave somehow won't use dunst and keep using his own notification system.
i'm using brave version 1.13.51 at the moment.

**Comment by mixedCase** [comment]
@alexb7711 This is not a Brave issue, you need to setup your notification daemon properly. It needs to be run at startup in order for some applications (like Brave) to use it and you do need libnotify since it's the interface used by most applications to send the right messages.

See: https://wiki.archlinux.org/index.php/Desktop_notifications

Same should apply to you @nsklaus 

I'll add libnotify to optdepends in brave-bin to make this more explicit. Please close this issue.

Cheers.

**Comment by jemadux** [comment]
sorry for necroposting i have the same issue on artix

**Comment by ndavd** [comment]
I'm also having this issue... libnotify is installed and that flag seems to no longer exist. Notifications are working for me in every other app but the browser.
