### ISSUE TITLE
Widget menu dropdown is not shown when browser is in restore mode

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9078]
## Description 

Widget menu dropdown is not shown when browser is in restore mode

## Steps to Reproduce

   1. Install PR build for Binance
   2. Open a new tab and click on Binance widget to bring it to view
   3. Hover over the menu button, shows menu options 
   4. Restore browser window 
   5. Hover over the menu button, menu options are not visible

## Actual result:

<img width="1050" alt="Screen Shot 2020-04-08 at 6 59 49 AM" src="https://user-images.githubusercontent.com/17010094/78735059-77fec880-7967-11ea-811a-26010f6a457e.png">

## Expected result:
<img width="1440" alt="Screen Shot 2020-04-08 at 7 00 21 AM" src="https://user-images.githubusercontent.com/17010094/78735158-af6d7500-7967-11ea-8300-6369f03fa7bb.png">

## Reproduces how often: 

Easy 

## Brave version (brave://version info)

Brave | 1.8.60 Chromium: 81.0.4044.83 (Official Build) nightly (64-bit)
--|--
Revision | 5718ca617723806b9aacfb41108a0d911d1bde74-refs/branch-heads/4044@{#853}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? NA

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.10.74 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

![image](https://user-images.githubusercontent.com/34715963/83103091-49bf7e80-a0b6-11ea-97ce-5b5bb86dcf9d.png)
