### ISSUE TITLE
Make it easier to troubleshoot website compat problems with Brave shields

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#908]
Carried over from https://github.com/brave/browser-laptop/issues/3732
> Currently you can open the Bravery Panel, and click on a stat.  It will show a list of the URLs affected. 
> 
> This task is to make it easier to troubleshoot the problems by making each of the URLs into a clickable on/off whitelist toggle.  I'm thinking we can have a list of exceptions URLs for each resourceName that we keep in the siteSettings. 
> 
> It's also useful for people that use noScript to incrementally add only the things they need. 
> 
> Main purpose though is it'll help our QA, especially @srirambv get the info they need to report a bug that is easy for us to fix, and eventually they can make those fixes themselves to a config file and PR it.
> 
> /cc @diracdeltas, this would save us a lot of time in the long run

**Comment by tomlowenthal** [comment]
Exploding this issue into its constituent parts:
- individual cookie management: #1925
- individual fingerprinting management: #1927
- individual ad/tracker management: #1926 
- fingerprinting control by method: #93 
- scripts control by 1st/3rd party: #538
