### ISSUE TITLE
Integrate with a bot for issue triage, etc

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#909]
Carried over from https://github.com/brave/browser-laptop/issues/11137

We can consider using a bot to interact with our GitHub repo which can:
- auto-respond to new issues
- add `needs-rebase` label to PRs which are out of date
- automatically add `stale` label to issues older than X
- etc

**Comment by parkr** [comment]
Hey @bsclifton! In lieu of setting up a custom bot, may I recommend Probot? It was developed by a few GitHubbers and each component can be installed on your organization as a GitHub App, making manag sing Access to your repos easy. It has several of your above use cases pre-built and ready to be installed! Check it out: https://probot.github.io/
