### ISSUE TITLE
Ref code doesn't auto populate all the time while registering a new account

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9091]
## Description 

Ref code doesn't auto populate all the time while registering a new account

## Steps to Reproduce

Scenario 1: 
   1. Clean profile from Binance branch
   2. Open a new tab and focus on Binance widget
   3. Click `Connect` 
   4. New tab opens with `https://accounts.binance.com/xxx`
   5. Click on `Register` to create a new account
   6. Ref code is not populated

Scenario 2: (Intermittent)
   1. Clean profile from Binance branch
   2. Open a new tab and focus on Binance widget
   3. Click `Buy BTC` 
   4. New tab opens with `https://www.binance.com/en/buy-sell-crypto`
   5. Click on `Register` to create a new account
   6. Ref code is not populated

Scenario when it auto populates
Scenario 3: 
   1. Clean profile from Binance branch
   2. Open a new tab and focus on Binance widget
   3. Click `Connect` 
   4. New tab opens with `https://accounts.binance.com/xxx`
   5. Click on `Register` to create a new account
   6. Ref code is not populated
   7. Close tab and go back to NTP and click on `Buy BTC`
   8. Click `Register` on the new tab that loads, ref code is auto populated
   9. Close tab from step 8 and click on `Connect` on Binance widget
  10. New tab opens to login, click on register Ref code is autopopulated

## Actual result:

![Binance-Ref-code](https://user-images.githubusercontent.com/17010094/78778299-b07ac280-79b8-11ea-984c-3dd25491d14e.gif)

## Expected result:
Ref code should be auto-populated when either connect or buy button is clicked and an account is being registered

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.8.60 Chromium: 81.0.4044.83 (Official Build) nightly (64-bit)
-- | --
Revision | 5718ca617723806b9aacfb41108a0d911d1bde74-refs/branch-heads/4044@{#853}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? NA

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome?  NA

## Miscellaneous Information:

cc: @bbondy @ryanml

**Comment by bbondy** [comment]
@srirambv can this be closed or still an issue?

**Comment by srirambv** [comment]
This is still reproducible on the latest nightly. Here's the steps
- Clean profile on nightly 
- Click on Connect
- Click on register account on the landing page
- Ref Code is field is not auto-populated
- Close tab and open a new one 
- Click on Buy BTC button 
- Click on register on the landing page, ref code filed is auto-populated and not selectable 

Here's a recording of the issue on the latest nightly  https://youtu.be/hU3Hj0YUFik

Brave | 1.10.24 Chromium: 81.0.4044.129 (Official Build) nightly (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Windows 10 OS Version 1909 (Build 18363.778)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.9.71 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{# 999}
OS | Linux

- Verified ref code is auto populated on the landing page when connecting to the account
- Verified clicking on connect button on widget adds the /en/login?ref=39346846&to the landing page. Clicking on register auto populates the ref code
- Verified manually updating the ref code on the login page and then clicking on register still auto populates the correct ref code and discards the manually entered ref code.
- Verified refid is set on the login page when clicked on connect
 ![image](https://user-images.githubusercontent.com/17010094/82406730-0432fe00-9a85-11ea-8318-4c4f5e4f1989.png)
- Verified ref id is retained on register page
![image](https://user-images.githubusercontent.com/17010094/82409113-a43f5600-9a8a-11ea-83a1-f953fe3daad3.png)
- Verified manually updating the local storage cookie to a different value resets it when account permission page shows up to authorise the widget

-----------------
Verification passed on 

Brave | 1.9.71 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{# 999}
OS | Windows 10 OS Version 1809 (Build 17763.379)

- Verified ref code is auto populated on the landing page when connecting to the account
- Verified clicking on connect button on widget adds the /en/login?ref=39346846&to the landing page. Clicking on register auto populates the ref code
- Verified manually updating the ref code on the login page and then clicking on register still auto populates the correct ref code and discards the manually entered ref code.
- Verified refid is set on the login page when clicked on connect
![image](https://user-images.githubusercontent.com/17010094/82417543-52ea9300-9a99-11ea-8f12-199a76d1b8d3.png)
- Verified ref id is retained on register page
![image](https://user-images.githubusercontent.com/17010094/82417557-567e1a00-9a99-11ea-98e1-5731a1f758cd.png)
- Verified manually updating the local storage cookie to a different value resets it when account permission page shows up to authorise the widget

-----------------

Verification passed on 

Brave | 1.9.71 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.4 (Build 19E287)

- Verified ref code is auto populated on the landing page when connecting to the account
- Verified clicking on connect button on widget adds the /en/login?ref=39346846&to the landing page. Clicking on register auto populates the ref code
- Verified manually updating the ref code on the login page and then clicking on register still auto populates the correct ref code and discards the manually entered ref code.
- Verified refid is set on the login page when clicked on connect
![image](https://user-images.githubusercontent.com/17010094/82422475-20906400-9aa0-11ea-8508-7c90b15a695b.png)
- Verified ref id is retained on register page
![image](https://user-images.githubusercontent.com/17010094/82422432-10788480-9aa0-11ea-87a4-d38cd2366d78.png)
- Verified manually updating the local storage cookie to a different value resets it when account permission page shows up to authorise the widget


- Logged https://github.com/brave/brave-browser/issues/9845 for widget not loading on first connection
