### ISSUE TITLE
Settings toggle to enable IPFS Companion causes segmentation fault on Linux

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#9092]
## Description 

Enabling IPFS Companion via Settings causes instant crash on Linux, while installing it via https://chrome.google.com/webstore/detail/ipfs-companion/nibjojkomfdiaoajekhjakgkdhaomnch works fine.

This seems to be similar to https://github.com/brave/brave-browser/issues/7325 however the crash is instant and did not have any problems on Linux before, so I am assuming this is a separate problem.

## Steps to Reproduce

   1. Open Brave with a fresh profile on a Linux box
   2. Go to _Settings_ → _Extensions_ 
   3. Click on the toggle to enable _IPFS Companion_

## Actual result:

Instant crash, process exits

```console
segmentation fault
```

## Expected result:

Enable IPFS Companion

## Reproduces how often: 

Every time. I tested  it on two different Linux boxes: Gentoo (using .zip from `/releases` in this repo) and Debian 10 (using official `.deb` and apt). 

## Brave version (brave://version info)

```
Brave    | 1.7.86 Chromium: 80.0.3987.163 (Official Build) unknown (64-bit)
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS       | Linux (5.6.2)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release?
  - Yes 
- Can you reproduce this issue with the beta channel?
  - Yes [v1.8.66](https://github.com/brave/brave-browser/releases/tag/v1.8.66)
- Can you reproduce this issue with the dev channel?
  - Did not check
- Can you reproduce this issue with the nightly channel?
  - Yes: [v1.9.9](https://github.com/brave/brave-browser/releases/tag/v1.9.9)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
  - No
- Does the issue resolve itself when disabling Brave Rewards?
  - No
- Is the issue reproducible on the latest version of Chrome? 
  - No, the same version installs just fine on Chrome.

## Miscellaneous Information:

cc https://github.com/brave/brave-browser/issues/7325 https://github.com/brave/brave-browser/issues/819 https://github.com/ipfs-shipyard/ipfs-companion/issues/716

@bbondy  I suspect something changed in Chrome or Chrome Web Store and there is now a bug in Brave around one-click-install.

Note that manual installation via button at https://chrome.google.com/webstore/detail/ipfs-companion/nibjojkomfdiaoajekhjakgkdhaomnch works fine – so so this is not a bug in ipfs-companion, but something related to the toggle button on _Settings_ page

I enabled crash reporting and retried, but it seems to crash before it can report the crash(?) anyway Report Id is `6c280000-9fe2-3a`

```console
--2020-04-08 14:14:22--  https://cr.brave.com/
Resolving cr.brave.com (cr.brave.com)... 151.101.13.7
Connecting to cr.brave.com (cr.brave.com)|151.101.13.7|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 36
Saving to: ‘/dev/fd/4’

/dev/fd/4                    0%[                                       ]       0  --.-KB/s               
Failed to get crash dump id./dev/fd/4                  100%[======================================>]      36  --.-KB/s    in 0s      

Report Id: 
6c280000-9fe2-3a
```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.8.76 Chromium: 81.0.4044.92 (Official Build) dev (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | Ubuntu 18.04 LTS

Reproduced the crash on 1.7.95.

Verified test plan from https://github.com/brave/brave-core/pull/5205
Verified ipfs extension installed without issues
![image](https://user-images.githubusercontent.com/34715963/79400027-46988500-7f85-11ea-97e0-8c7ef23c6e5d.png)
![image](https://user-images.githubusercontent.com/34715963/79400134-9b3c0000-7f85-11ea-89e2-cdc6663e6d0b.png)
