### ISSUE TITLE
HTTPSE toggle not working correctly

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9099]
## Description 

If you're on a site (like https://https-everywhere.badssl.com/) and you toggle HTTPSE off from shields, page still shows that HTTPSE is enabled even if you refresh the page.

This does not reproduce on 1.5.123.

## Steps to Reproduce

   1. Clean profile 1.7.86.
   2. Navigate to https://https-everywhere.badssl.com/
   3. Open shields, disable HTTPSE.

Same thing happens on a profile upgraded from 1.5.123.

## Actual result:
Page still says HTTPSE is working (same thing happens even if you refresh the page. 
<img width="826" alt="Screen Shot 2020-04-08 at 2 34 31 PM" src="https://user-images.githubusercontent.com/28145373/78822278-d26c4900-79a8-11ea-8039-73fc29368f86.png">

## Expected result:
Page should indicate that HTTPSE is not working or not enabled as it does on 1.5.123:
<img width="825" alt="Screen Shot 2020-04-08 at 2 33 10 PM" src="https://user-images.githubusercontent.com/28145373/78822301-dc8e4780-79a8-11ea-8453-2839b8b8699c.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.7.86 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? does not reproduce on 1.5.123
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @brave/legacy_qa

**Comment by btlechowski** [comment]
Reproduced on Linux

Brave | 1.7.86 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/78833946-0cac0980-79ee-11ea-99dd-a8a26de46b55.png)

**Comment by bsclifton** [comment]
There is a regression with the website itself - which happened starting with https://github.com/brave/brave-core/pull/4537

However- the functionality is working as expected 😄 Thanks to @fmarier for the following test plan, which I also ran through and verified

> I tested it successfully in Beta like this:
> 1. Open http://https-everywhere.badssl.com/ (you then get redirected to https://https-everywhere.badssl.com/).
> 2. Open shields, disable HTTPSE.
> 3. Open http://https-everywhere.badssl.com/ (you do not redirected).

I believe we should close this as expected behavior
