### ISSUE TITLE
Allow storage in 1p frames, regardless of the relative parents of that 1p frame 

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#9105]
Currently storage is blocked in 3p frames, where 3p-ness is determined relative to the parent frame.  So, all the following are true:

3p frames get no storage
```
https://example.com <-- storage
  <iframe src="//other.com"> <-- no storage
```

same origin frames get storage 
```
https://example.com <-- storage
  <iframe src="//example.com"> <-- storage
      <iframe src="//other.com"> <-- no storage
```

frames that have the same origin as the top level document, but are embedded in a 3p frame, also don't get storage.
```
https://example.com <-- storage
  <iframe src="//other.com"> <-- no storage
      <iframe src="//example.com"> <-- ALSO no storage
```

This breaks some sites, specially wordpress's dashboard, which has the following pattern
```
https://yoursite.wordpress.com
  <iframe src="//api.wp.com"> <-- no storage
      <iframe src="//yoursite.wordpress.com"> <-- ALSO no storage
```

We can unbreak wordpress here by changing the storage rule to being: frames get storage if they're the same eTLD+1 as the top level document, regardless of immediate parent document.

This doesn't add any direct privacy loss, but as a side effect of unbreaking sites, might also re-enable some privacy harming flows.

Related: https://github.com/brave/brave-browser/issues/9064

**Comment by pes10k** [comment]
Fixed by @bridiver this is fixed by https://github.com/brave/brave-core/pull/5433

**Comment by LaurenWags** [comment]
@pes10k @bridiver does this require manual QA? If so, please add `QA/Yes` label and a test plan. If not, please add `QA/No` label. Thanks!

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` until there is a test plan.
