### ISSUE TITLE
Possible crash with sync migration

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#9110]
## Description 

PR https://github.com/brave/brave-core/pull/4816 contained a bug making crash on bookmarks migration, if there are nested bookmarks folders and bookmarks with the duplicated object id

This PR reached stable version, but fixing PR (https://github.com/brave/brave-core/pull/5139) is still not merged , because it hadn't yet resolved all the issue with duplicated bookmarks migration.

## Steps to Reproduce

To go through STR, you will need to download
1. Old version without bookmark sync USS https://github.com/brave/brave-browser/releases/tag/v0.73.42
2. Current 1.7.x candidate https://github.com/brave/brave-browser/releases/tag/v1.7.90

Example below is for Linux, if you need such for Windows or macOS, they are similar, let me know if it is required.

Steps to reproduce:
1. Install v0.73.42
2. Create folders `/home/test/TESTBRAVE/A` and `/home/test/TESTBRAVE/B`. We need to create the sync chain, it requires to have 2 devices, but we will use two different profiles.
3. Create two scripts to be able to run two nightly browser instances against the different profiles
```
#RunNightlyA.sh
/opt/brave.com/brave-nightly/brave  --user-data-dir=/home/test/TESTBRAVE/A    --enable-logging=stderr --v=0 --vmodule=*/sync/*=3,*/brave_sync/*=3,*/sync_bookmarks/*=3,sync_cycle=0
```
```
#RunNightlyB.sh
/opt/brave.com/brave-nightly/brave  --user-data-dir=/home/test/TESTBRAVE/B    --enable-logging=stderr --v=0 --vmodule=*/sync/*=3,*/brave_sync/*=3,*/sync_bookmarks/*=3,sync_cycle=0
```
4. in different terminals in the same time run `RunNightlyA.sh` and `RunNightlyB.sh` to have two running browsers
5. enable sync on browserA and connect browserB to the chain
6. wait until two browsers will have a device list
7. create bookmarks A.com, B.com and folder FolderF in root Bookmarks folder
8. Copy and paste <A.com, B.com> into FolderF and beyond folderF
9. Copy and paste FolderF 3 times, the result will be as on the picture
![image](https://user-images.githubusercontent.com/24739341/78910474-b4c4df80-7a8d-11ea-9b3b-e1deb54293eb.png)

10. Close browserB - we will not need it anymore for these STR
11. Close browserA
12. Install 1.7.90
13. Create a script to be able to run stable browser against the profile A:
```
#RunStableA.sh
/opt/brave.com/brave/brave  --user-data-dir=/home/test/TESTBRAVE/A    --enable-logging=stderr --v=0 --vmodule=*/sync/*=3,*/brave_sync/*=3,*/sync_bookmarks/*=3,sync_cycle=0
```
14. Run `RunStableA.sh`

## Actual result:

Browser crashes
![image](https://user-images.githubusercontent.com/24739341/78910443-a971b400-7a8d-11ea-9686-f9f448369ec1.png)

## Expected result:
Should not crash

## Version/Channel Information:

- Can you reproduce this issue with the current release? No, but yes for RC
- Can you reproduce this issue with the beta channel? it should be yes
- Can you reproduce this issue with the dev channel? it should be yes
- Can you reproduce this issue with the nightly channel? it should be yes

**Comment by AlexeyBarabash** [comment]
Here is an example of crash report https://brave.sp.backtrace.io/p/brave/debug?time=all&error=1eb9a&debug=(%221eb9a%22,0,0)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/5139
Verified no crash after upgrade to 1.7.92
Verified no crash after upgrade to 1.7.92 with `--disable-sync`

![image](https://user-images.githubusercontent.com/34715963/79102218-93ecda80-7d6a-11ea-9632-17e1b63d6156.png)
