### ISSUE TITLE
blank new tab page

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#9111]
## Description 
Blank new tab page, should not be blank. Likely introduced with this PR:
https://github.com/brave/brave-core/pull/5097

## Steps to Reproduce

   1. Open New Tab page with normal window. Notice that it's blank

## Actual result:
<img width="1374" alt="Screen Shot 2020-04-09 at 9 18 18 AM" src="https://user-images.githubusercontent.com/5951041/78916956-1318a080-7a43-11ea-92fe-d7c5d20bca1c.png">

<img width="597" alt="Screen Shot 2020-04-08 at 4 13 44 PM" src="https://user-images.githubusercontent.com/5951041/78929378-26ce0200-7a57-11ea-8343-3b0e7fd5a799.png">

## Expected result:
Should see usual New Tab Page.

## Reproduces how often: 
Easily for effected profiles (likely older profiles, Top Sites related).

## Version/Channel Information:

- Can you reproduce this issue with the current release? Possible. Seen in 1.7.80 but blank ntp with 1.7.x could be a different issue.
- Can you reproduce this issue with the beta channel? No, even though on 1.8.70 so due to a profile.
- Can you reproduce this issue with the dev channel? 1.8.68
- Can you reproduce this issue with the nightly channel? 1.9.x No, but again likely profile specific

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards?n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
Not related to previous Empty NTP issue #8867

**Comment by kjozwiak** [comment]
Adding `release-notes/exclude` as this hasn't made it into release yet.

**Comment by kjozwiak** [comment]
@rebron mind checking this one we get a new `1.8.x` now that https://github.com/brave/brave-core/pull/5224 was approved and merged?

**Comment by kjozwiak** [comment]
Labeling as `QA/No` as discussed before. We currently don't have STR that reproduces this 100%. Lets keep an eye on `1.8.x` to make sure this doesn't happen/appear again.

@rebron @karenkliu confirmed that they're not seeing this problem anymore.
