### ISSUE TITLE
[Android] Shield icon is in wrong place when I use in-app Brave browser mode in Twitter app

### ISSUE THREAD

**Issue by mKoonrad** [brave/brave-browser#9113]
## Description
Shield icon is in wrong place when I use in-app Brave browser mode in Twitter app.
![Screenshot_20200409-185727__01](https://user-images.githubusercontent.com/11725227/78921440-34a27800-7a95-11ea-88c3-78f01713c176.jpg)

## Steps to reproduce
   1. Open Twitter app with in-app browser mode in Twitter Android app settings.
   2. Click on any external link on Twitter app.
   3. See tweet button and shield logo in the same place.

## Actual result
See screenshot above

## Expected result
Shield logo should be in safe place, not overwrite any other interface.

## Issue reproduces how often
Easily reproduced

## Issue happens on
   - Current Play Store version? Yes
   - Beta build? No

## Device details
   - Install type: ARM64
   - Device (Phone): OnePlus 5T
   - Android version: 9
   
## Brave version
1.5.131

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? No

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/braves-icon-at-url-bar-in-in-app-browser/125222?u=eljuno

**Comment by rodrigoswz** [comment]
Please Brave Team, fix this issue.

This bug breaks one of the best features of the [Lynket](https://play.google.com/store/apps/details?id=arun.com.chromer) app. That space is used to quickly open the page in a favorite sharing action or secondary action.

With Brave set as browser engine in Lynket, the shield overrides this functionality: https://i.imgur.com/oQscmad.jpg

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/brave-in-app-browser/148882?u=eljuno

**Comment by srirambv** [comment]
cc: @anthonypkeane to triage and add it to a milestone

**Comment by srirambv** [comment]
+1 from @FrostedIce339 via #11109

**Comment by srirambv** [comment]
+1 from @etridgely via #12652

**Comment by srirambv** [comment]
+1 from @afroz1198 via #13746

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.23.69 x64 build
- Verified steps from issue description
---------
Verification passed on Samsung Tab A with Android 10 running 1.23.69 x64 build
- Verified steps from issue description
