### ISSUE TITLE
Binance Version 2 Trading Widget

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#9118]
https://docs.google.com/document/d/1RGIfaPyfY9v7QRx2e5B4k1W88oRHxUNSKlaMjzFDY-s/edit#heading=h.lzlktw5ja2pg

There are some deviations from the doc, as per recent changes, notably:

1. Hiding account balances by default
2. API keys are not in use, rather we are using the new Oauth method of authenticating users.
3. The widget is built in to the new Crypto Stack as opposed to being standalone.

**Comment by srirambv** [comment]
Verification notes on nightly build `1.9.21` and `1.9.24` is here for reference https://github.com/brave/brave-core/pull/5160#issuecomment-614463615

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.8.85 Chromium: 81.0.4044.122 (Official Build) (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | Windows 10 OS Version 1809 (Build 17763.1158)

- Verified able to successfully connect to Binance widget 
- Verified able to disconnect and reconnect to the widget 
- Verified able to successfully convert assets after connecting
- Verified deposit balance shows up after specified amount of time 
- Verified widget state is not lost when browser is closed and relaunched
- Verified asset address and QR code is shown correctly when available
- Verified widget shows correct error messages when conversion fails
- Verified preview conversion is auto-dismissed after 30sec
- Verified manually able to refresh the balance via menu button
- Verified visiting Binance page and logging out doesn't disconnect the widget state
