### ISSUE TITLE
crash with Google autocomplete and Private Window

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#9119]
## Description 
Instant crash with Google's autocomplete pref on and opening a New Private Window.
Crash ID: 4f71746f-6429-4691-aa1a-32107e6428e5
Crassh ID: f3634a1b-bc46-4181-b04b-cbcc5c54f647

## Steps to Reproduce

   1. Turn on `Autocomplete searches and URLs` in brave://settings/privacy with Google as the search engine. 
   2. Open New Private Window.
   3. Start typing in url bar in Private Window and notice immediate crash.

## Actual result:
See str.

## Expected result:
No crash with Google's new autocomplete feed in Private Window.

## Reproduces how often: 
Easily. CR 81 related.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.5.x or 1.7.x no.
- Can you reproduce this issue with the beta channel? 

Brave | 1.8.70 Chromium: 81.0.4044.83 (Official Build) beta (64-bit)
-- | --
Revision | 5718ca617723806b9aacfb41108a0d911d1bde74-refs/branch-heads/4044@{#853}
OS | macOS Version 10.15.5 (Build 19F53f)

- Can you reproduce this issue with the dev channel? c81 related
- Can you reproduce this issue with the nightly channel? Yes. 1.9.x c81 related.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by kjozwiak** [comment]
@rebron nice find 👍Reproduced using the following builds:

```
Brave | 1.8.69 Chromium: 81.0.4044.83 (Official Build) dev (64-bit)
-- | --
Revision | 5718ca617723806b9aacfb41108a0d911d1bde74-refs/branch-heads/4044@{#853}
OS | macOS Version 10.15.3 (Build 19D76)
```

* Uploaded Crash Report ID: `35300000-9fe2-3a04-0000-000000000000`

```
Brave | 1.9.7 Chromium: 81.0.4044.83 (Official Build) nightly (64-bit)
-- | --
Revision | 5718ca617723806b9aacfb41108a0d911d1bde74-refs/branch-heads/4044@{#853}
OS | macOS Version 10.15.3 (Build 19D76)
```

* Uploaded Crash Report ID: `3d300000-9fe2-3a04-0000-000000000000`

However, I can't reproduce the crash using the following build:

```
Brave | 1.7.90 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | macOS Version 10.15.3 (Build 19D76)
```

Seems like C81 related as @rebron mentioned above.

**Comment by kjozwiak** [comment]
I can still reproduce this on `1.7.95 CR: 81.0.4044.92` which is the latest RC for the next release. We'll need to make sure this is uplifted into `1.7.x` before we release on April 20th. Moved into https://github.com/brave/brave-browser/milestone/102.

Used the following build to reproduce on `Win`:

```
Brave | 1.7.95 Chromium: 81.0.4044.92 (Official Build) (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | Windows 10 OS Version 1909 (Build 18363.752)
```

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | Linux

- Verified no crash when typing in URL on a private tab
- Verified no crash when typing in URL on a private Tor tab
- Verified no crash when typing in URL on a guest tab
