### ISSUE TITLE
Remove balance api

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9132]
we should remove balance api for majority of users. Flow should be like this:

- introduce migration flag (default = false)
- if migration flag is false fetch from balance server
- if user has any balance there (which is user funds) we should continue normally
- if user don't have any balance set flag to true as user can't create new user funds anymore
- if flag is set to true skip brave balance server ping

We need to force balance pull when user restores wallet. When user funds are gone we need to set flag to true so that we don't pull anymore.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.78 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Verified plan 1 from https://github.com/brave/brave-core/pull/5737.
- Confirmed no calls to `https://balance-staging.mercury.basicattentiontoken.org/v2/wallet/<paymentID>/balance` when opening panel or brave://rewards page
- Confirmed after claiming grant balance is displayed as expected and still no calls to balance server when opening panel or brave://rewards page
- Confirmed after restoring a user wallet (with non-zero balance), `https://balance-staging.mercury.basicattentiontoken.org/v2/wallet/<paymentID>/balance` was called. Confirmed thereafter additional calls to balance server were made when opening panel or brave://rewards page.
- Confirmed after restoring a user wallet (with 0 BAT balance), `https://balance-staging.mercury.basicattentiontoken.org/v2/wallet/<paymentID>/balance` was called once where it returned the zero balance. Confirmed thereafter additional calls to balance server were not made when opening panel or brave://rewards page.

Verified plan 2 from https://github.com/brave/brave-core/pull/5737.
- Installed 1.10.97, enabled Rewards (staging env). Claimed UGP grant.
- Upgraded to 1.11.x. Confirmed one call to `https://balance-staging.mercury.basicattentiontoken.org/v2/wallet/<paymentID>/balance`. 
- Confirmed opening panel and brave://rewards page did not invoke calls to the balance server.
- Confirmed close/restart of browser did not invoke calls to the balance server.

Verified plan 3 from https://github.com/brave/brave-core/pull/5737.
- Installed 1.10.97, enabled Rewards (staging env). Restored an anon wallet with non-zero BAT balance.
- Upgraded to 1.11.x. Confirmed call to `https://balance-staging.mercury.basicattentiontoken.org/v2/wallet/<paymentID>/balance`. 
- Confirmed opening panel and brave://rewards page did invoke calls to the balance server.
- Confirmed close/restart of browser did invoke calls to the balance server.

-----
