### ISSUE TITLE
[Desktop] Use GreaseLion for YouTube publishers

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9133]
we should switch to GL for YT so that we can have faster turn around rate when something breaks.

**Comment by LaurenWags** [comment]
Verification in progress

```
Brave	1.16.42 Chromium: 86.0.4240.55 (Official Build) nightly (x86_64)
Revision	a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS	macOS Version 10.14.6 (Build 18G3020)
```

<details>
<summary>General</summary>

 - Confirmed Greaselion script no longer needs to be installed manually, just need to confirm that Brave Local Data Updater is version >=1.0.27.

<img width="357" alt="Component" src="https://user-images.githubusercontent.com/28145373/94448429-e1be9900-0178-11eb-9869-f03db0a64a70.png">

 - Confirmed visiting non-verified publishers showed the generic YT favicon in panel and AC table. Visited each of the below using a clean profile:
   - https://www.youtube.com/user/gordonramsay
   - https://www.youtube.com/channel/UCIEv3lZ_tNXHzL3ox-_uUGQ
   - https://www.youtube.com/watch?v=9i4SKHbhbqk
</details>

<details>
<summary>Channel URL</summary>

- Verified steps from https://github.com/brave/brave-core/pull/5440, used staging env
- Verified publisher:
  - Confirmed tip to https://www.youtube.com/channel/UCD7siefto4I33L4U61IU5LQ showed on Tips panel of brave://rewards as expected
  - Confirmed recurring tip showed on Monthly Contributions panel of brave://rewards as expected
  - Confirmed able to adjust monthly contribution amount from panel
  - Confirmed able to remove monthly contribution from panel and brave://rewards page
  - Confirmed panel, 1 time tip, and recurring tip banners all had verified checkmark
- Non-verified publisher:
  - Confirmed tip to https://www.youtube.com/channel/UCIEv3lZ_tNXHzL3ox-_uUGQ showed on pending table
  - Confirmed recurring tip showed on Monthly Contributions panel of brave://rewards as expected
  - Confirmed able to adjust monthly contribution amount from panel
  - Confirmed able to remove monthly contribution from panel and brave://rewards page
- Custom banner:
  - Visited https://www.youtube.com/channel/UCCs7AQEDwrHEc86r0NNXE_A, confirmed custom banner was displayed 

<img width="1194" alt="channel - sampson" src="https://user-images.githubusercontent.com/28145373/94448513-fa2eb380-0178-11eb-84b1-8caf6318c867.png">
<img width="1192" alt="channel - ramsay" src="https://user-images.githubusercontent.com/28145373/94448521-fb5fe080-0178-11eb-87a8-bb13af4c5feb.png">
<img width="667" alt="channel 2" src="https://user-images.githubusercontent.com/28145373/94448529-fd29a400-0178-11eb-91ab-331384b00e59.png">
<img width="974" alt="channel - 3" src="https://user-images.githubusercontent.com/28145373/94448539-fe5ad100-0178-11eb-82a3-61bc1991ed3a.png">
<img width="1199" alt="channel - custom banner" src="https://user-images.githubusercontent.com/28145373/94448542-ff8bfe00-0178-11eb-9a1d-1de1ac6db31d.png">

</details>

<details>
<summary>User URL</summary>

- Logged https://github.com/brave/brave-browser/issues/11883 for favicon

</details>

<details>
<summary>Activity</summary>

Ran thru steps from https://github.com/brave/brave-core/pull/5440, substituted a shorter video (https://www.youtube.com/watch?v=XoxrQr-w8Kg). Video length was 1min 33s or 93s which matches the duration in the DB.

<img width="690" alt="Nightly DB - Activity TC" src="https://user-images.githubusercontent.com/28145373/94448633-1d596300-0179-11eb-8acb-e70a43337e07.png">
<img width="1196" alt="Nightly AC table - Activity TC" src="https://user-images.githubusercontent.com/28145373/94448639-1f232680-0179-11eb-9b73-15165e506dee.png">

</details>
