### ISSUE TITLE
Support UN M49 area codes (which do not contain embargoed countries) in Brave Ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#9134]
Support UN M49 area codes (which do not contain embargoed countries) in Brave Ads (see https://unstats.un.org/unsd/methodology/m49/) as area codes are used for certain OS regional settings such as Spanish (Latin America) for Brazil

**Comment by LaurenWags** [comment]
Removing `release-notes/include` label as issue is not working per the test plan in https://github.com/brave/brave-core/pull/5217. 

Logged follow up issue https://github.com/brave/brave-browser/issues/9828

**Comment by LaurenWags** [comment]
Verified using 


Brave | 1.9.70 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.14.6 (Build 18G3020)

* Test plan from https://github.com/brave/brave-core/pull/5217 did not work, ads were not supported for region = Brazil, language = Spanish (Latin America).

<img width="736" alt="Captura de Pantalla 2020-05-18 a la(s) 14 48 49" src="https://user-images.githubusercontent.com/28145373/82249936-9ec1fe80-9918-11ea-8fdc-063e372d3c8b.png">

Logged follow up issue https://github.com/brave/brave-browser/issues/9828

**Comment by LaurenWags** [comment]
@tmancey is going to grab some examples that will work for QA and then we will test this one out.

**Comment by GeetaSarvadnya** [comment]
Verification passed on
```
Brave | 1.9.70 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)
```
- Confirmed UN M49 area codes supported
- Verified the scenarios mentioned in https://bravesoftware.slack.com/archives/C43LW5U2H/p1589896372175100

**Comment by btlechowski** [comment]
On Ubuntu 18.04 LTS area codes are not supported. Setting the issue as `OS/Windows` and `OS/macOS`. Regression test for regions will be done under https://github.com/brave/brave-browser/issues/7817

![image](https://user-images.githubusercontent.com/34715963/82372984-2abd4e80-9a1d-11ea-9d08-8d55dd67aa04.png)
