### ISSUE TITLE
placeholder issue - Rewards notifications updates needed

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9135]
## Description 
Per discussion in slack, https://bravesoftware.slack.com/archives/CB0KCRCQN/p1584978377455300?thread_ts=1584814280.450900&cid=CB0KCRCQN

we should make updates to some rewards notifications, in particular @davidtemkin noted the "Insufficient Funds" notification for updates. 

This was tracking (somewhat) under https://github.com/brave/brave-browser/issues/6546 but that's a fairly old issue and stale, hence logging this new issue so what is needed can be clearly defined for implementation.

cc @NejcZdovc @mandar-brave @jenn-rhim @alexwykoff as per the slack discussion

**Comment by bsclifton** [comment]
Closing in favor of the following:
- https://github.com/brave/brave-browser/issues/7942 (`Make "Insufficient funds...pending tips" BR notification have more friendly messaging`)
- https://github.com/brave/brave-browser/issues/7941 (`Add more details to the red "...problem processing your contribution" BR notification`)
- https://github.com/brave/brave-browser/issues/7943 (`Expire BR notifications/alerts`)
