### ISSUE TITLE
rewards panel shows wrong site info when tweeting about a tip sometimes

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9136]
## Description 

While retesting https://github.com/brave/brave-browser/issues/5544, I found that I get the wrong publisher info on the rewards panel in certain cases.

## Steps to Reproduce

1. Clean profile, launch with staging, enable rewards and claim grant
2. Open `https://www.reddit.com/user/jsadler-brave`
3. Tip the publisher
4. Click the tweet button from the thank you area of the banner
5. On Twitter page open Brave Panel

## Actual result:

Panel shows info for previous tab (reddit/jsadler)
<img width="1194" alt="Screen Shot 2020-04-10 at 9 18 19 AM" src="https://user-images.githubusercontent.com/28145373/78993974-0bbdc980-7b0d-11ea-9a44-dc461bd36d50.png">

## Expected result:
panel should show twitter:
<img width="1195" alt="Screen Shot 2020-04-10 at 9 24 46 AM" src="https://user-images.githubusercontent.com/28145373/78994015-255f1100-7b0d-11ea-9cd6-9f1324987965.png">

## Reproduces how often: 

Doesn't always happen, seems to be about 50% of the time

## Brave version (brave://version info)

Brave | 1.9.15 Chromium: 81.0.4044.92 (Official Build) nightly (64-bit)
-- | --
Revision | 32921c79b6f01a0fb2deef0e1d45b42f96581051-refs/branch-heads/4044@{#883}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? unsure
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @NejcZdovc @brave/legacy_qa

**Comment by emerick** [comment]
We just need to add `/intent/` to the list of excluded pages in our Twitter Greaselion script.

**Comment by urbenlegend** [comment]
This is also happening when simply browsing random posts on the Brave subreddit.
![image](https://user-images.githubusercontent.com/241316/107258515-c00bd300-69f0-11eb-86d7-3ed9b9159d9c.png)
You can see that posts are randomly attributed to CryptoJennie.

**Comment by LaurenWags** [comment]
@urbenlegend I think you're seeing https://github.com/brave/brave-browser/issues/12302

**Comment by Miyayes** [comment]
stale
