### ISSUE TITLE
Blocking All Device Recognition Attempts Breaks Map on coronavirus.iowa.gov

### ISSUE THREAD

**Issue by Cybo1927** [brave/brave-browser#9139]
## Description 
Blocking device fingerprinting on `https://coronavirus.iowa.gov/` prevents the map from loading

## Steps to Reproduce

   1. Go to `https://coronavirus.iowa.gov/`
   2. Click the Brave shields icon and set Brave to block all device recognition attempts
   3. Reload page and scroll down to the map

## Actual result:

![image](https://user-images.githubusercontent.com/39284087/79012874-e786da80-7b56-11ea-8458-5902e11d4990.png)

## Expected result:
![image](https://user-images.githubusercontent.com/39284087/79012899-fc636e00-7b56-11ea-993d-bc7a3b084320.png)

## Reproduces how often: 

Easily reproduced - Just make Brave block all device recognition attempts

## Brave version (brave://version info)

Brave | 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | Linux

(Also tested and doing the same thing on a Windows 10 laptop)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Yes
- Can you reproduce this issue with the dev channel?
Unknown
- Can you reproduce this issue with the nightly channel?
Unknown

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
Yes
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
cc: @pes10k

**Comment by pes10k** [comment]
Yep, this is a result of APIs the embedded map uses that are also used for fingerprinting. So, currently there is not a way to allow the map to function and enable fingerprinting blocking.  

However, https://github.com/brave/brave-browser/issues/8787, which is currently being implemented, will enable us to allow sites to use more complex functionality in a way that still protects against fingerprinting.

**Comment by pes10k** [comment]
@Cybo1927 also, fwiw, the relevant bits of this change are in nightly currently.  I'm able to browse that map with all fingerprinting protection blocked currently.  If you're a nightly user, could you let us know if it looks fixed for you too?

**Comment by pes10k** [comment]
Confirmed that this is fixed in nightly, and will be rolling out to other channels accordingly.  Thanks again for the report @Cybo1927 !

**Comment by pes10k** [comment]
Also, @Cybo1927 , you're Brave version is pretty behind.  You might just make sure you're on the current stable version of Brave (if not Beta or Nightly).  Current stable is 1.8.x, and you're on 1.5.x
