### ISSUE TITLE
Allow disabling some "default" filter lists

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#9144]
Some users would like the ability to enable some, but not all, of the [default filter lists](https://github.com/brave/adblock-rust/blob/master/src/filter_lists/default.rs).

This would be similar to what uBO does, and so might be part of this work: https://github.com/brave/brave-browser/issues/8478

**Comment by elemanhillary** [comment]
can i get assigned this

**Comment by pes10k** [comment]
If we decided to go down this path, it'd require some server side changes too, since currently we bundle and preprocess all these filter lists into the [adblock-rs](https://github.com/brave/adblock-rust/) serialized format.  So I dont think it's something that'd make sense to assign externally.  but if this is a change you're interested in, would be happy to talk / plan through!

**Comment by elemanhillary** [comment]
yeah surely

**Comment by pes10k** [comment]
@elemanhillary hi just wanted to check with you on this.  Are you still working on it?  If so, would love to review.  Otherwise, i'll close since i dont think we have any plans for this

**Comment by elemanhillary** [comment]
I didn't work on it as there were many opinions on it and nothing came to
conclusion, close it please

**Comment by pes10k** [comment]
thanks for the update @elemanhillary !
