### ISSUE TITLE
Bookmark button shown twice on URL Bar 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#915]
## Description 

Bookmark button shown twice on URL Bar 

## Steps to Reproduce

   1. Upgrade to 0.54.4
   2. See two bookmark buttons one inside omnibox and one outside
   3. Click boomkark button inside omnibox, bookmark balloon is shown under the icon which is outside omnibox

## Actual result:

![bookmarkbutton](https://user-images.githubusercontent.com/17010094/44946310-f9739980-adc7-11e8-81d9-b3f56600d02b.gif)

## Expected result:
Should not show the button inside omnibox

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Brave | 0.54.4 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | Windows

### Reproducible on current release:

No
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @bbondy please move to 0.55.x milestone if required

**Comment by simonhong** [comment]
https://github.com/brave/brave-core/pull/379 will fix this issue

**Comment by bbondy** [comment]
Closing as a duplicate to #899
