### ISSUE TITLE
[Android] [Feature Requests] Extension and External Download Manager Support 

### ISSUE THREAD

**Issue by Raul1198** [brave/brave-browser#9151]
Extension - A good add-on as we can use password manager like Bitwarden, KeepassX, Lockwise (rather than relying on google autofill api ), Dark Reader , Ublock Origin,…etc

External Download Manager - A feature to download files via any External Download manager like ADM and Navi Download Manager (FOSS) on Android which Supports downloading file in multiple thread which is fast than the default Download Manager in Brave Browser

**Comment by srirambv** [comment]
There is an issue open for adding Extension support #4493. This will be done pretty soon. As of now there is no plans of adding an external download manager support to Brave. Closing as wont fix for now. Added a +1 for extension support. Please track progress for it in #4493
