### ISSUE TITLE
Remove deprecated timers from Brave Ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#9153]
Remove deprecated timers (SetTimer, OnTimer and KillTimer) from `bat-native-ads` and `bat-native-confirmations`

**Comment by bsclifton** [comment]
Updated original post to link to test plan

**Comment by LaurenWags** [comment]
@tmancey is this issue for desktop? Test plan from PR says:

> Confirm Brave Ads onboarding notification times out if not clicked

I'm assuming that's referring to the sample ad, but desktop onboarding doesn't have a Brave Ads sample ad. Should this be marked as `OS/Android` instead? or do we need to follow a different test plan on desktop?

**Comment by tmancey** [comment]
@LaurenWags I have updated the test plan as this refers to the "Brave Ads have arrived" on-boarding notification. This issue only affects desktop and android (not iOS)

**Comment by LaurenWags** [comment]
Thanks @tmancey - could we get some additional clarification - what is the timeout for this? So if you never open the panel to see this notification, when should it go away?

**Comment by tmancey** [comment]
@LaurenWags The Brave Ads onboarding notification is removed after 1 week. You can also reduce this time to 5 minutes with the `--brave-ads-debug` command-line arg

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.9.62 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
Revision	8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS	macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5229
* Confirmed that if I install 1.8.x on a non-Ads region (ex. Aruba), and upgrade to 1.9.x, I get the Brave Ads have arrived notification on BAT logo as expected.
   * Confirmed that if I use the `--brave-ads-debug` flag as noted in https://github.com/brave/brave-browser/issues/9153#issuecomment-626567087, the notification goes away after 5 minutes as noted
   * Confirmed that if I do not use the `--brave-ads-debug` flag, the notification does not go away after 5 minutes, but does go away after 1 week (+ some time for jitter).
