### ISSUE TITLE
Ad notification timeout timers are not cancelled if a Brave Ad is clicked

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#9154]
## Description 

Ad notification timeout timers are not cancelled if an ad is clicked

## Steps to Reproduce

   1. Click an ad notification (before it times out)

## Actual result:

Ad notification 120 second timeout timer is not stopped

## Expected result:
Ad notification 120 second timeout timer should be stopped

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

This is not a critical issue as when an ad event for timeouts was triggered we already had defensive code in place, however, we should fix this so that the timer is not using unecessary resources

**Comment by GeetaSarvadnya** [comment]
Verification is in progress


```
[2832:18556:0504/182106.934:INFO:ads_service_impl.cc(1928)] Timeout ad notification with uuid f9382126-cab5-4f0f-9b52-152ac3f65636 in 120 seconds
[2832:18556:0504/182106.935:INFO:ads_service_impl.cc(2095)] AdsService Event Log: {"data":{"type":"restart","timestamp":"2020-05-04T18:21:06Z"},"data":{"type":"notify","timestamp":"2020-05-04T18:21:06Z","eventType":"generated","classifications":["arts & entertainment"],"adCatalog":"b2054163-9998-4b88-aa0c-9939f55d414a","targetUrl":"https://travala.com/"}}
[2832:18556:0504/182106.935:INFO:ads_service_impl.cc(2095)] AdsService Event Log: {"data":{"type":"confirmation","timestamp":"2020-05-04T18:21:06Z","creativeInstanceId":"6b9deba5-01bf-492b-9bb8-7bc4318fe272","confirmationType":"view"}}
[14452:7540:0504/182106.935:INFO:confirmations_impl.cc(1146)] Confirm ad:
  creativeInstanceId: 6b9deba5-01bf-492b-9bb8-7bc4318fe272
  creativeSetId: b2054163-9998-4b88-aa0c-9939f55d414a
  category: arts & entertainment
  targetUrl: https://travala.com/
  geoTarget: US
  confirmationType: view
```

**Comment by GeetaSarvadnya** [comment]
@tmancey Need clarification on scenarios 5th and 6th from the test plan https://github.com/brave/brave-core/pull/5230 are not working as mentioned in the test plan 

Scenario 5: when user clicks on Ad, we are getting `Timed out ad notification with uuid` in the logs. I will share the recorded file along with logs shortly
Scenario 6: when the user dismiss an Ad, we are getting `Timed out ad notification with uuid` in the logs. I will share the recorded file along with logs shortly

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` as @GeetaSarvadnya is still pending answers from https://github.com/brave/brave-browser/issues/9154#issuecomment-623580902.

**Comment by tmancey** [comment]
@GeetaSarvadnya I have searched your logs and `Timed out ad notification with uuid` do not appear for #5 and #6. After checking your comments you were searching for `timeout` and not `timed out` :-)

**Comment by LaurenWags** [comment]
Thanks for the clarification @tmancey 😄
