### ISSUE TITLE
[Android] Transferring bookmark file from Android to Desktop

### ISSUE THREAD

**Issue by artella-coding** [brave/brave-browser#9155]
Is it possible to transfer the "bookmark file" from Android to Desktop? 

Currently the only way to do this is via sync which has been disabled. Even if it was enabled, I have found that syncing takes a long time and is unreliable. Would it be possible to have a method that would allow one to transfer the bookmarks file from android to desktop, which one could then use to import into brave (i.e. allowing one to completely bypass sync)?

**Comment by artella-coding** [comment]
And also where is the bookmark file stored on an android device?

**Comment by srirambv** [comment]
Currently there is no feature to transfer bookmark from Android to Desktop apart from Sync. We have an issue opened for allowing Import/Export of bookmarks outside of sync. https://github.com/brave/brave-browser/issues/6378 but currently there is no ETA on this feature availability.

**Comment by artella-coding** [comment]
@srirambv Is there any way to do this via Android Studio e.g. transferring the sqlite file that contains the bookmarks?

**Comment by anthonypkeane** [comment]
Please use sync for this one. No plans for import/export now :) Thanks
