### ISSUE TITLE
Can't download the repo

### ISSUE THREAD

**Issue by terroriser11** [brave/brave-browser#9157]
![Annotation 2020-04-12 175744](https://user-images.githubusercontent.com/40738816/79073473-28adf480-7ce7-11ea-98f2-d9f483c0e9ca.png)

## Description 

I tried to download the repo sadly this failed and I followed the wiki it's steps.

## Actual result:

Permission denied

## Expected result:
That it succeeded successfully.

## Brave version (brave://version info)

Latest build: v1.9.17

**Comment by radustanca** [comment]
You don't need to clone over ssh, do it over https. 

`git clone https://github.com/brave/brave-browser.git`

If you really need to clone over ssh make sure you have the ssh key setup

https://help.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account

**Comment by bsclifton** [comment]
Thanks for the assist, @rst10124492 😄 Those steps are exactly right. If you add an SSH key, you can clone over ssh. HTTPS will work fine though 👍
