### ISSUE TITLE
Proxmox Web Interface Terminal does not work

### ISSUE THREAD

**Issue by Hanyoro** [brave/brave-browser#9158]
<!-## Description 

Using Proxmox terminal in Brave just shows a black screen no text. 

## Steps to Reproduce

Access Proxmox web interface>open shell

## Actual result:

![Screenshot_20200412-123035~2](https://user-images.githubusercontent.com/46978939/79074280-83305c00-7cb9-11ea-9013-6b2ece8a490d.jpg)

## Expected result:
The terminal should show text, it works fine in chrome and Firefox, even Brave mobile on Android works fine. 

## Reproduces how often: 

Every shell in Proxmox does this in Brave

## Brave version (brave://version info)
Brave    1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)
Revision    e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS    Windows 10 OS Version 1909 (Build 18363.752)
JavaScript    V8 8.0.426.30
Flash    (Disabled)
User Agent    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36

I don't have the version info, but this issue also happens on my Thinkpad running Arch Linux in Brave.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by Hanyoro** [comment]
For anyone having this issue, turn off Brave shield and it works. I noticed people on google were having problems with this so I wanted to comment the solution.

**Comment by GiorgioRX** [comment]
To me is happening with firefox and i tried disabling all exestension, cleaning cookies and cache and deactivated the privacy feature of firefox.
It was working fine and randomly started doing this and i don't know what have i done to cause it.
Chrome,Arc and Brave are working fine
