### ISSUE TITLE
[hackerone] webtorrent should clear redirect URL if not http:// or https://

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#9159]
originally reported at https://hackerone.com/reports/847848

this is a very minor phishing risk.

STR:
1. make sure webtorrent is enabled (by accessing https://webtorrent.io/torrents/sintel.torrent)
2. enter chrome-extension://lgjmpdmojkpocjcopdikifhejkkjglho/extension/brave_webtorrent.html?chrome://wallet/ in the urlbar and hit enter
3. urlbar shows brave://wallet with a blank page
4. click urlbar and hit enter again. wallet loads.

Expected behavior:
In step 3, either nothing should happen or you should be navigated to about:blank

(Expected behavior updated by @yrliou ) In step 3, a blank extension page is shown with original URL (chrome-extension://lgjmpdmojkpocjcopdikifhejkkjglho/extension/brave_webtorrent.html?chrome://wallet/) and nothing will be changed when doing step 4.

**Comment by fmarier** [comment]
Here are the steps I found to reproduce this reliably:

1. Start the browser.
2. Go into `chrome://settings`.
3. **Toggle WebTorrent OFF, and then ON**.
4. Load the test page at <https://fmarier.github.io/brave-testing/brave-browser-9159.html>.

If I skip Step 3, I get the following error page:

![Screenshot from 2020-04-29 17-55-03](https://user-images.githubusercontent.com/167821/80661131-9aee3b00-8a42-11ea-88f8-3b71c925f63b.png)

This suggests that perhaps the extension load order matters.

**Comment by fmarier** [comment]
Based on the [Slack thread](https://bravesoftware.slack.com/archives/C2X6K7EGN/p1586726963001300), I made this simple fix:
```
--- a/components/brave_webtorrent/browser/net/brave_torrent_redirect_network_delegate_helper.cc
+++ b/components/brave_webtorrent/browser/net/brave_torrent_redirect_network_delegate_helper.cc
@@ -54,13 +54,16 @@ int OnHeadersReceived_TorrentRedirectWork(
 
   if (!original_response_headers ||
       !IsMainFrameResource(ctx) ||
+      !ctx->request_url.SchemeIsHTTPOrHTTPS() ||
       ctx->is_webtorrent_disabled ||
       // download .torrent, do not redirect
       (IsWebtorrentInitiated(ctx) && !IsViewerURL(ctx->request_url)) ||
       !IsTorrentFile(ctx->request_url, original_response_headers)) {
+    LOG(ERROR) << "NO REDIRECT";
     return net::OK;
   }
 
+  LOG(ERROR) << "REDIRECT";
   *override_response_headers =
     new net::HttpResponseHeaders(original_response_headers->raw_headers());
   (*override_response_headers)
```
but it didn't help since it's not even entering that function and printing anything to the console when I click on the offending links.

**Comment by fmarier** [comment]
@feross Was that the fix you were trying to test or did you have something else in mind?

**Comment by feross** [comment]
> This suggests that perhaps the extension load order matters.

I think this is just a quirk of how the lazy-loading feature was implemented. The WebTorrent extension is not loaded until it's needed. So it seems like linking directly to an extension URL doesn't cause the extension to get enabled. Going into settings and toggling it OFF -> ON seems to force it to be enabled. Another option to your steps 1-2 is to load a torrent from https://webtorrent.io/free-torrents which has the same effect.

**Comment by feross** [comment]
> @feross Was that the fix you were trying to test or did you have something else in mind?

Indeed, this was the intended fix. Are neither of your logs ("NO REDIRECT" and "REDIRECT") getting printed out?

I think the issue may actually be in `brave/components/brave_webtorrent/browser/content_browser_client_helper.h` in the `TranslateTorrentUIURLReversed` method which handles the URL rewriting.

https://github.com/brave/brave-core/blob/2ccf47f6ecdc6694a10b003dd8ba520d8bd42546/components/brave_webtorrent/browser/content_browser_client_helper.h#L42-L49

If I understand that code correctly, it appears to be taking the query portion of the URL and just using that.

So the URL `chrome-extension://lgjmpdmojkpocjcopdikifhejkkjglho/extension/brave_webtorrent.html?chrome://settings/` gets translated to `chrome://settings/` without first checking that it is HTTP or HTTPS.

@fmarier Can you try moving the check into that function instead?

**Comment by yrliou** [comment]
Test plan specified in https://github.com/brave/brave-core/pull/5595#issue-420408963

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.73 Chromium: 83.0.4103.106 (Official Build) dev (64-bit)
-- | --
Revision | ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5595

Step 3:
<img width="1195" alt="Screen Shot 2020-06-23 at 12 56 45 PM" src="https://user-images.githubusercontent.com/28145373/85432602-34bcfa80-b551-11ea-81b1-01d0e03d2422.png">

Step 5: 
<img width="1194" alt="Screen Shot 2020-06-23 at 12 57 10 PM" src="https://user-images.githubusercontent.com/28145373/85432614-3686be00-b551-11ea-932f-1a5109329086.png">
