### ISSUE TITLE
Add balance check

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#916]
When you are on rewards page we need to check for balance every minute

**Comment by NejcZdovc** [comment]
I think this should be done in JS with setInterval and calling getBalance into c++

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

* Verified adding funds to wallet showed up within 1 minute of transfer
