### ISSUE TITLE
`Customize` text on NTP is not translated

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#9161]
Follow up to https://github.com/brave/brave-browser/issues/4930

## Steps to Reproduce

   1. Openn NTP in Polish locale

## Actual result:

`Customize` is not translated
The tooltip is not translated

![image](https://user-images.githubusercontent.com/34715963/79096922-baa51400-7d5e-11ea-9d2b-1da8c09b4f66.png)

## Expected result:
`Customize` is translated
The tooltip is translated

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Reproduced on

Brave | 1.8.72 Chromium: 81.0.4044.92 (Official Build) dev (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | Ubuntu 18.04 LTS

Reproduced on

Brave | 1.9.18 Chromium: 81.0.4044.92 (Official Build) nightly (64-bit)
-- | --
Revision | 32921c79b6f01a0fb2deef0e1d45b42f96581051-refs/branch-heads/4044@{#883}
OS | Ubuntu 18.04 LTS

cc @mkarolin @rebron @brave/legacy_qa @cezaraugusto

**Comment by elemanhillary** [comment]
i would like to be assigned this

**Comment by mkarolin** [comment]
The string was added via brave/brave-core#5103 after we did the latest l10n round (brave/brave-core#5089). If it's important to have this localized sooner than the next round (for 1.9.x) then pls let me know.

**Comment by elemanhillary** [comment]
@mkarolin yes it is.

**Comment by bsclifton** [comment]
@elemanhillary you can sign up for our Transifex project here:
https://www.transifex.com/brave/brave/

This is where we pull the translations from 😄 Anything other than English on GitHub gets destroyed and replaced with the contents of Transifex when we pull latest

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.8.84 Chromium: 81.0.4044.122 (Official Build) (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | Windows 10 OS Version 1803 (Build 17134.1006)


- Verified the test plan from the description
![image](https://user-images.githubusercontent.com/38657976/80365941-08b13000-88a6-11ea-945d-1d33c60b9c51.png)
