### ISSUE TITLE
Brave Beta hangs on start after update

### ISSUE THREAD

**Issue by the-sushi** [brave/brave-browser#9162]
## Description 
Upon updating Brave Browser Beta, upon launch it instantly hangs, preventing any interaction with the application.  Additionally, it has incredibly high CPU usage, with Activity Monitor reporting 100%.  Brave will not close until force quit.

![Activity Monitor](https://i.imgur.com/msb5KwW.png)

## Steps to Reproduce
   1. Update to latest(?) Beta build
   2. Launch Brave / let Brave restart

## Actual result:

![Activity Monitor](https://i.imgur.com/msb5KwW.png)

![Empty Brave window that I can't interact with](https://i.imgur.com/Wt2G1Ci.png)

## Expected result:

Brave works as normal

## Reproduces how often: 
For me on every launch, but one would need multiple installs to actually test this.

## Brave version (brave://version info)
Can't check, as Brave hangs.  However, `~/Library/Application Support/BraveSoftware/Brave-Browser-Beta/RunningChromeVersion` is linked to 81.1.8.70

## Other Additional Information:

Device is a Macbook Pro (2019), on macOS Catalina 10.15.4.

Removing `~/Library/Application Support/brave/*Cache` and session-store-1 did not resolve the problem.

**Comment by the-sushi** [comment]
Update: The issue seems to have fixed itself, possibly due to the latest macOS update?

**Comment by the-sushi** [comment]
Update 2: It appears to have started happening again

**Comment by bsclifton** [comment]
@the-sushi is this still happening? Is the UI usable at all? If so, can you use the hamburger menu (top right, three lines) and pick "More Tools" => "Task Manager" to see what within Brave is taking up the CPU?

**Comment by bsclifton** [comment]
Related https://github.com/brave/brave-browser/issues/9372, https://github.com/brave/brave-browser/issues/7914

**Comment by the-sushi** [comment]
> @the-sushi is this still happening? Is the UI usable at all? If so, can you use the hamburger menu (top right, three lines) and pick "More Tools" => "Task Manager" to see what within Brave is taking up the CPU?

Still happening.  The UI is completely unusable so I cannot open the menu.

**Comment by bsclifton** [comment]
Thanks for confirming @the-sushi. Do you have to force kill Brave? or does it eventually crash?

I'm going to close this issue in favor of a parent issue that I'm collecting all reports, since there are many similar ones. You can subscribe to that here:
https://github.com/brave/brave-browser/issues/9481
