### ISSUE TITLE
[Desktop] WebTorrent shows a blank, non-responsive page

### ISSUE THREAD

**Issue by ggrelet** [brave/brave-browser#9163]
## Description 
When clicking on torrent links, WebTorrent shows a blank page with tab title to `WebTorrent`. The page do nothing more.
Alas, this behaviour happens 95% on the time on redirection-download torrents (thinking `/torrents.php?action=download&id=2650964`) and 10% of the time on direct `.torrent` links like on the video below.

## Steps to Reproduce
There's no way to reproduce this behaviour deterministically. However, you can try the following:

   1. Go to the [Ubuntu Alternative Download page](https://ubuntu.com/download/alternative-downloads), BitTorrent section.
   2. Click on any distribution link.
   3. Notice the bug **OR** retry from step 2

## Actual result:

![output](https://user-images.githubusercontent.com/10114131/79111485-e6cf8d80-7d7c-11ea-8db3-457a5cf18289.gif)

## Expected result:
The classical WebTorrent page is displayed.

## Reproduces how often: 
**Intermittent issue**: seen 1/10 times on direct `.torrent` files, but 95% of the time on link redirection torrent files (`/torrents.php?action=download&id=2650964`)

## Brave version (brave://version info)
Field | Value
-- | --
Brave | 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | macOS Version 10.15.4 (assemblage 19E287)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
**Yes**
- Can you reproduce this issue with the beta channel?
**Haven't tried**
- Can you reproduce this issue with the dev channel?
**Haven't tried**
- Can you reproduce this issue with the nightly channel?
**Haven't tried**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
**No**
- Does the issue resolve itself when disabling Brave Rewards?
**No**
- Is the issue reproducible on the latest version of Chrome? 
**Not applicable**

**Comment by matheusmurden** [comment]
Any updates on this issue?

**Comment by Brave-Matt** [comment]
+1 from Community here: 
https://community.brave.com/t/cant-download-torrent-files-from-yify-yts-am/281348/11

**Comment by klepp0906** [comment]
same issue.  assume its just low priority or im retarded and havent found the cause of it yet, just disabled webtorrent for now.

**Comment by stephendonner** [comment]
Duping to the fix at https://github.com/brave/brave-browser/issues/24552.

**Comment by Daybayzayd** [comment]
I have the same behavior randomly.
