### ISSUE TITLE
Missing string to translate - New Tab

### ISSUE THREAD

**Issue by mKoonrad** [brave/brave-browser#9169]
## Description
You have missing string to translate "New Tab". I check few languages like Polish, French, Czech, Italian, German - no translation in any of them.
![image](https://user-images.githubusercontent.com/11725227/79123546-b4cd2400-7d9a-11ea-99a0-78ffb513cdec.png)

## Steps to Reproduce
   1. Open Brave
   2. See description of empty tab at the top or open new tab.

## Actual result:
English strings "New Tab"

## Expected result:
Translated string

## Reproduces how often: 
Always

## Brave version (brave://version info)
```
Brave	1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)
Revision	e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS	Windows 10 OS Version 1909 (Build 18363.752)
JavaScript	V8 8.0.426.30
Flash	(Wyłączone)
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
Command Line	"C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --disable-domain-reliability --disable-features=WebXrGamepadModule,WebXR,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,AllowPopupsDuringPageUnload,VideoPlaybackQuality,LookalikeUrlNavigationSuggestionsUI,AutofillServerCommunication --disable-sync --disable-webrtc-apm-in-audio-service --enable-audio-service-sandbox --enable-dom-distiller --enable-features=WebUIDarkMode,SimplifyHttpsIndicator,PasswordImport --extension-content-verification=enforce_strict --extensions-install-verification=enforce --no-pings --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,SimplifyHttpsIndicator,WebUIDarkMode --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,VideoPlaybackQuality,AllowPopupsDuringPageUnload,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,WebXR,WebXrGamepadModule --flag-switches-begin --enable-features=PasswordImport,SimplifyHttpsIndicator,WebUIDarkMode,DnsOverHttps --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path	C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\User\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations	5e3a236d-4113a79e
```

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? No

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.4 x64 Catalina` without the following build:

```
Brave | 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | macOS Version 10.15.4 (Build 19E287)
```

**`New Tab translated in Polish`**

<img width="885" alt="Zrzut ekranu 2020-04-28 o 7 22 25 PM" src="https://user-images.githubusercontent.com/2602313/80547390-10480600-8986-11ea-8c25-eabb13ed5834.png">

**`New Tab translated in Italian`**

<img width="822" alt="Schermata 2020-04-28 alle 7 23 21 PM" src="https://user-images.githubusercontent.com/2602313/80547415-235ad600-8986-11ea-8783-995acc66dcc4.png">

**`New Tab translated in German`**

<img width="806" alt="Bildschirmfoto 2020-04-28 um 7 24 16 PM" src="https://user-images.githubusercontent.com/2602313/80547429-2950b700-8986-11ea-9177-6b67ba31b68c.png">
