### ISSUE TITLE
Remove min-height from Rewards settings wallet box to allow auto-height

### ISSUE THREAD

**Issue by bradleyrichter** [brave/brave-browser#9174]
description:

The existing layout of the BR settings wallet box forces the panel to a minimum height which pushes elements off the page for small monitors. Removing this min-height in the DIV will allow the TAP banner and future banners to appear higher in the page for most users.

current

![image](https://user-images.githubusercontent.com/13509546/79142044-c220e900-7d6f-11ea-9c24-43cf9c1edffb.png)

desired: 
![image](https://user-images.githubusercontent.com/13509546/79142202-fb595900-7d6f-11ea-9d73-cefd48c8750d.png)

**Comment by elemanhillary** [comment]
can i get assigned this
