### ISSUE TITLE
Bandwidth Savings Predictor changes for Chromium 83.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#9176]
[This Chromium change](https://chromium.googlesource.com/chromium/src/+/aa4f7b3f23460707dea0d73ca9dbbd5d9aff8c8a) (landing in Cr83) has removed 
<pre>
  // The first time the page is considered 'interactive'. This is determined
  // using heuristics based on main thread and network activity. Time delta is
  // relative to navigation_start.
  mojo_base.mojom.TimeDelta? interactive;
</pre>
value from `struct InteractiveTiming`.

Underlying Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1055806

A commit in brave/brave-core#5102 (WIP for upgrade to Cr83) named `InteractiveTiming.interactive was removed from page load metrics.` removes direct use of the field from the bandwidth savings predictor, but doesn't touch the model components/brave_perf_predictor/python/resources, which uses the field.

This is a followup issue to determine what needs to happen in the model (or if the `interactive` field needs to be restored in the code).

cc: @bsclifton

**Comment by bsclifton** [comment]
Setting missing milestone to 1.10
