### ISSUE TITLE
Don't download Tor binaries until a new Private Tab with Tor is opened

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#9177]
## Description 
With new installs of Brave, we register the platform specific (Windows, macOS, Linux) `Brave Tor Client Updater` component with Component Updater. Users will hit our `go-update` service to fetch these binaries which can cause a few problems:
1. Without user even opening a new `Private Tab with Tor` tab, they have the Tor executable installed on their machine in their profile directory. Some enterprise software will flag this as "potentially malicious".
2. Downloads and subsequently updates are pushed to all users even if they're not using the feature.
    - 2a. This puts additional stress on the `go-update` service
    - 2b. There is a bandwidth cost for this too

I'd like to propose NOT downloading the software until a new `Private Tab with Tor` is opened. This would basically mean not registering the component with Component Updater until that happens. When this feature IS used, the user would then have a worse experience (would need to wait for initial download / unzip / install) on their first run. Subsequent runs would be just fine and the software would stay up to date.  We might be able to show a progress bar or another interstitial page while download is happening

cc: @rebron @w0ts0n @bbondy @kjozwiak

**Comment by kjozwiak** [comment]
> When this feature IS used, the user would then have a worse experience (would need to wait for initial download / unzip / install) on their first run. Subsequent runs would be just fine and the software would stay up to date. We might be able to show a progress bar or another interstitial page while download is happening.

Agreed, we'll need some type of indicator that the binary is being actually being downloaded as some users on slower connections might think the feature is completely broken. Maybe having some type of mechanism that checks to make sure that the component is downloaded and a connection to a Tor circuit has been established before allowing users to use the feature?

**Comment by diracdeltas** [comment]
> Agreed, we'll need some type of indicator that the binary is being actually being downloaded as some users on slower connections might think the feature is completely broken. Maybe having some type of mechanism that checks to make sure that the component is downloaded and a connection to a Tor circuit has been established before allowing users to use the feature?

muon had a feature where the urlbar would be unusable (and show percentage complete) until a tor circuit was established. we could just do that and show "downloading tor..." in the urlbar.

**Comment by diracdeltas** [comment]
re-assigning to @darkdh per discussion on slack

**Comment by bridiver** [comment]
> > Agreed, we'll need some type of indicator that the binary is being actually being downloaded as some users on slower connections might think the feature is completely broken. Maybe having some type of mechanism that checks to make sure that the component is downloaded and a connection to a Tor circuit has been established before allowing users to use the feature?
> 
> muon had a feature where the urlbar would be unusable (and show percentage complete) until a tor circuit was established. we could just do that and show "downloading tor..." in the urlbar.

@diracdeltas we don't need to do that here because we can defer any page loads with a navigation throttle. We do the same thing for Webtorrent.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.13.71 Chromium: 84.0.4147.125 (Official Build) dev (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/6081

**New profile and relaunch**
Verified there is no `Tor Client Updater` in `brave://components` on clean install
Verified Tor started to work eventually
Verified that after Tor window is opened `Tor Client Updater` is present in `brave://components`
Verified Tor binary was not deleted after restarting the browser
![image](https://user-images.githubusercontent.com/34715963/90298989-9ab06900-de94-11ea-868f-6d94f86982b6.png)
Verified that Tor works after browser restart

**Emulate slow network**
Verified the page was eventually loaded in Tor Window

**Disable Tor by settings**
Verified that after disabling Tor, `biahpgbdmdkfgndcmfiipgcebobojjkp` Tor extension folder was deleted
![image](https://user-images.githubusercontent.com/34715963/90299307-dd267580-de95-11ea-89de-0c8f26db278d.png)
Verified re-enabling Tor, downloaded the binary and opened a page in Tor Window
