### ISSUE TITLE
Contribution process

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#918]
Depends on GMP.

Add contribution process for rewards

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.17 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Mac OS X

* Verified with flags from #1161 and test plan in https://github.com/brave/brave-core/pull/578
