### ISSUE TITLE
[Android] Implement Scoped Storage per Android API target 30

### ISSUE THREAD

**Issue by increasingawareness** [brave/brave-browser#9180]
Apps that target Android 11 will need to implement Scoped Storage: https://developer.android.com/preview/privacy/storage

> To give developers additional time for testing, apps that target Android 10 (API level 29) can still request the requestLegacyExternalStorage attribute. This flag allows apps to temporarily opt out of the changes associated with scoped storage, such as granting access to different directories and different types of media files. After you update your app to target Android 11, you cannot use requestLegacyExternalStorage to opt out of scoped storage.

See this [Android Developer's Medium post for more details](https://medium.com/androiddevelopers/modern-user-storage-on-android-e9469e8624f9)

**Comment by anthonypkeane** [comment]
We should get these changes as they are made in Chromium. Thanks
