### ISSUE TITLE
Fingerprinting 2.0: Canvas

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#9186]
This is a sub-issue of the larger font defense reorganization https://github.com/brave/brave-browser/issues/8787

### Serialization Endpoints

`CanvasRendering2dContext.getImageData`
`HTMLCanvasElement.toDataURL`
`HTMLCanvasElement.toBlob`
`OffscreenCanvas.convertToBlob`

**default protection**: farble output, by using eTLD+1 session seed and canvas contents to determine offsets into the canvas to flip randomly selected low order bits
**max protection**: Generate psuedo-random output (w/o regard to canvas contents), derived from the eTLD+1 session seed

### Content Querying Endpoints

`CanvasRendering2dContext.measureText`
`CanvasRendering2dContext.isPointInPath`
`CanvasRendering2dContext.isPointInStroke`

**default protection**: no changes
**max protection**: return respective bottom value (0, false, false, respectively)

**Comment by LaurenWags** [comment]
@pes10k assuming this one is also waiting on the same items mentioned in https://github.com/brave/brave-browser/issues/8661#issuecomment-632352239 ? 

cc @rebron @kjozwiak

**Comment by pes10k** [comment]
@LaurenWags yep! Let me ping #devops folks and see how far out the "set up more test infrastructure" issue is in their queue. If its way out, then i'll see if i can figure something else out on my own

**Comment by LaurenWags** [comment]
thanks @pes10k - marking as `QA/Blocked` until we're sorted!

**Comment by pes10k** [comment]
Hi @LaurenWags I've written up some manual tests for this here.  I tried to write up some instructions here.  Just let me know if its not clear or it'd be good to talk through.

Thanks to @bkero, i can add more tests easily as needed too, so just let me know how i can be helpful :)

**Comment by LaurenWags** [comment]
per discussion w/ @pes10k info is here: https://github.com/brave/devops/issues/3067#issuecomment-640949572

**Comment by LaurenWags** [comment]
Per discussions w/ @pes10k here's the test plan:
Using 
- https://dev-pages.bravesoftware.com/farbling.html
- https://dev-pages.brave.software/farbling.html

Confirm that:
- with shields up, FP values are the same for each individual item (ex. WebGL Drawing) on a given page, but the values are different between the two pages above.
- with shields up, if you close and relaunch the browser, and visit the pages again the values are different (they are not retained between sessions).
- with shields down, FP values are the same for each individual item on a given page and are the same for both pages.
- with shields down, if you close and relaunch the browser, and visit the pages again, the values are the same (they are retained between sessions).

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.10.88 Chromium: 83.0.4103.97 (Official Build) (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{# 657}
OS | Linux

<details>
<summary>Verified with shields up, FP values are the same for each individual item (ex. WebGL Drawing) on a given page.</summary>

URL 1 | URL 2
-- | --
![image](https://user-images.githubusercontent.com/17010094/84490559-f4dc5480-acc0-11ea-93ff-9cbb3cdde2fd.png)  | ![image](https://user-images.githubusercontent.com/17010094/84490599-0160ad00-acc1-11ea-95ae-238d7ccd2ad4.png)

</details>

<details>
<summary>Verified with shields up, close and relaunch the browser, and visit the pages again the values are different except for WebGL Drawing - Passed</summary>

- Canvas and WebAudio has different values between relaunches

URL 1 | URL2
-- | --
![image](https://user-images.githubusercontent.com/17010094/84492452-d3309c80-acc3-11ea-82ec-b759c6489ad9.png) | ![image](https://user-images.githubusercontent.com/17010094/84492513-e479a900-acc3-11ea-9915-06029b5bcf17.png)
![image](https://user-images.githubusercontent.com/17010094/84492571-f78c7900-acc3-11ea-8a10-7f301c0298d7.png) | ![image](https://user-images.githubusercontent.com/17010094/84492644-1ab72880-acc4-11ea-8d9b-cc201bd1cf2a.png)

</details>

<details>
<summary>Verified with shields down, FP values for WebGL Drawing/Canvas/Web Audio are all the same on a given page and are the same for both pages.</summary>

URL 1 | URL2 
-- | --
![image](https://user-images.githubusercontent.com/17010094/84493026-ba74b680-acc4-11ea-8acf-d44b66df969b.png) |![image](https://user-images.githubusercontent.com/17010094/84493258-1a6b5d00-acc5-11ea-8c97-2b2b8fc16fab.png)
![image](https://user-images.githubusercontent.com/17010094/84493059-c6607880-acc4-11ea-8656-fd22dbc265c1.png) | ![image](https://user-images.githubusercontent.com/17010094/84493086-cfe9e080-acc4-11ea-8634-1fb4d0a6dacc.png)
![image](https://user-images.githubusercontent.com/17010094/84493112-daa47580-acc4-11ea-9839-e880b479fa23.png) | ![image](https://user-images.githubusercontent.com/17010094/84493141-e8f29180-acc4-11ea-8473-a3879a242e03.png)

</details>

<details>
<Summary>Verified with shields down, if you close and relaunch the browser, and visit the pages again, the values are the same (they are retained between sessions).</summary>

- No screenshots to show here
![image](https://user-images.githubusercontent.com/17010094/84494096-84d0cd00-acc6-11ea-8324-ec06c9bc1537.png)
</details>
