### ISSUE TITLE
Fingerprinting 2.0: Web Audio

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#9187]
This is a sub-issue of the larger fingerprint defense reorganization issue: #8787 

### Audio data serialization endpoints
`AnalyserNode.getByteTimeDomainData`
`AnalyserNode.getFloatTimeDomainData`
`AnalyserNode.getByteFrequencyData`
`AnalyserNode.getFloatFrequencyData`
`AudioBuffer.getChannelData`

**default protection:** Farble output volume by [0,-.01] under eTLD+1 session seed
**max protection:** randomly generate low amplitude white noise under eTLD+1 session seed (with max amplitude / volume being 1% of max representable volume).

**Comment by abrahamjuliot** [comment]
@pes10k 
Side note: Should AudioBuffer.copyFromChannel be added in this list? It should match AudioBuffer.getChannelData.

**Comment by pes10k** [comment]
@abrahamjuliot that is a very good question!  Let me check and see if thats already covered by the current instrumentation point and get back to you.  Thanks for the suggestion!

**Comment by pes10k** [comment]
@abrahamjuliot so good news from @pilgrim-brave (who's doing the actual hard work on all this), we already cover `copyFromChannel`, I just neglected to include it in the issue text.  So, i'll update the issue text now to make it clear.  Apologies for the omission, and takes again for catching it!

https://github.com/brave/brave-core/blob/master/patches/third_party-blink-renderer-modules-webaudio-audio_buffer.cc.patch#L44
